### ISSUE TITLE
inCondi ET660i support

### ISSUE THREAD

**Issue by konrad-cz** [cagnulein/qdomyos-zwift#1004]
### Discussed in https://github.com/cagnulein/qdomyos-zwift/discussions/1002

<div type='discussions-op-text'>

<sup>Originally posted by **konrad-cz** October 24, 2022</sup>
Good evening, 

I wanted to ask if the app is supporting the inCondi ET660i. The app did not find the device when I searched for it. I'd like to use it fo running. 
Thank you!
Kind regards,
O. </div>

**Comment by konrad-cz** [comment]
I'm able to find the device and connect to it using the SW which was provided by the manufacturer, but not with QZ. I'm not able to get any relevant info from this app, however - meaning Bluetooth information, but I am able to control the elliptical from this application.

**Comment by cagnulein** [comment]
@konrad-cz i don't remember, how is the implementation right now? did i send you a version?

**Comment by cagnulein** [comment]
#1007
