### ISSUE TITLE
Fire Tablet 8 (8th gen)

### ISSUE THREAD

**Issue by mattm382** [cagnulein/qdomyos-zwift#101]
Can't connect to Zwift.  Open Zwift and it recognizes the tablet but shows "No Signal".
![20210102_092750](https://user-images.githubusercontent.com/76880353/103463393-e1d2b580-4ce0-11eb-8405-9a2d1235debd.jpg)

The first two logs are from when I manually paired the tablet with my PC before starting everything.  The second two logs are from when I unpaired the tablet and then started everything.  They end up with the same result as in the picture.
[debug-Sat Jan 2 09_19_01 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5760650/debug-Sat.Jan.2.09_19_01.2021.log)
[debug-Sat Jan 2 09_20_33 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5760651/debug-Sat.Jan.2.09_20_33.2021.log)
[debug-Sat Jan 2 09_25_48 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5760652/debug-Sat.Jan.2.09_25_48.2021.log)
[debug-Sat Jan 2 09_29_23 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5760654/debug-Sat.Jan.2.09_29_23.2021.log)

**Comment by cagnulein** [comment]
did you turn the peloton setting off?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 gen 2021 alle ore 19:00 mattm382 <notifications@github.com>
ha scritto:

**Comment by mattm382** [comment]
Yes.  Cadence Sensor (Peloton compatibility) set to Off.

**Comment by cagnulein** [comment]
do you have the beta access to my app? if not, send me a mail to
roberto.viola83@gmail.com with your google play account email address and i
will add you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 gen 2021 alle ore 19:23 mattm382 <notifications@github.com>
ha scritto:

**Comment by mattm382** [comment]
Mail sent, thank you.

**Comment by cagnulein** [comment]
@marklogan17 remember to give it a try with nrfconnect, thanks!

**Comment by cagnulein** [comment]
@mattm382 i don't remember. Have you got any update?

**Comment by mattm382** [comment]
I don't yet.  @marklogan17 was going to give it a shot, but I haven't heard back.  I don't know how to use nrfconnect but I assume mark does.

**Comment by cagnulein** [comment]
@mattm382 do you still have this issue? i'm closing this one. in case feel free to reopen this!
