### ISSUE TITLE
Could QZ control the treadmill speed, just like iFit can control NordicTrack treadmills?

### ISSUE THREAD

**Issue by JuergenNeubauer** [cagnulein/qdomyos-zwift#1010]
Hello,
I might have missed that in the documentation whether QZ is or is planned to be able to control the treadmill speed. In my case I have a NordicTrack professional series inclination trainer (without bluetooth, but WIFI) that is being controlled by iFit for both inclination and speed control.
I want to create my own running workouts with undulating inclinations and slightly varying speeds to create a more natural (and much less boring and monotonous) running experience. Can QZ help with that? Can I upload my custom workouts (e.g. in ZWO format) and let QZ control the treadmill? For some more entertainment I could run Zwift in parallel but only for the visuals, similar to the way Zwift works in Riding workout mode where it doesn't control the resistance of my bike trainer according to slope, but according to workout intensity.
Thanks for your help.
Regards, Juergen

**Comment by cagnulein** [comment]
> Hello,
> 
> I might have missed that in the documentation whether QZ is or is planned to be able to control the treadmill speed. 

Hi, QZ is already able to control speed and incline of most of the treadmills. It will be able to do also for ifit Wi-Fi ones, I just need time :)

> In my case I have a NordicTrack professional series inclination trainer (without bluetooth, but WIFI) that is being controlled by iFit for both inclination and speed control.
> 
> I want to create my own running workouts with undulating inclinations and slightly varying speeds to create a more natural (and much less boring and monotonous) running experience. Can QZ help with that? 

Absolutely! It's what I do every single time I use qz standalone:) 

> Can I upload my custom workouts (e.g. in ZWO format) and let QZ control the treadmill? 

Yes! Zwo is already supported and this already works for all the treadmills supported for qz!

> For some more entertainment I could run Zwift in parallel but only for the visuals, similar to the way Zwift works in Riding workout mode where it doesn't control the resistance of my bike trainer according to slope, but according to workout intensity.

Yes I did also the same in the past.

> 
> Thanks for your help.
> 
> Regards, Juergen

**Comment by cagnulein** [comment]
Check #589 #954 @JuergenNeubauer

**Comment by JuergenNeubauer** [comment]
Great, sounds awesome. Can't wait to try.
Thanks, Juergen

**Comment by JuergenNeubauer** [comment]
What would you recommend is the best workflow to use my own ZWO workout for running? Copy it into the workout folder on Android? Or let Zwift use the workout file and control the speed and inclination of the treadmill?

**Comment by JuergenNeubauer** [comment]
I forgot to ask how to encode running pace and inclination. Is it possible to use the ZWO syntax for that? Or do you use your own XML file format? What are the elements in you XML file. Is there documentation for that?
Thanks, Juergen

**Comment by cagnulein** [comment]
> What would you recommend is the best workflow to use my own ZWO workout for running? Copy it into the workout folder on Android? Or let Zwift use the workout file and control the speed and inclination of the treadmill?

zwift can only control the incline, so it will be better to use directly the zwo inside qz for sure

**Comment by cagnulein** [comment]
> I forgot to ask how to encode running pace and inclination. Is it possible to use the ZWO syntax for that? Or do you use your own XML file format? What are the elements in you XML file. Is there documentation for that?
> 
> Thanks, Juergen 

yes the zwo is fully supported and in the training program settings of qz you can set your different paces as you do on zwift :)

**Comment by cagnulein** [comment]
@JuergenNeubauer we are getting closer https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/11

**Comment by cagnulein** [comment]
@Majorswigs QZ works on iOS, yes.

**Comment by Majorswigs** [comment]
To be more specific does it allow speed and inclination control on proform 2000 now?
I read somewhere that it’s wip.

**Comment by cagnulein** [comment]
hah yes it's wip @Majorswigs

**Comment by JuergenNeubauer** [comment]
Hello, have plans changed? The status says that this issue has been closed "as not planned"?

**Comment by cagnulein** [comment]
nono @JuergenNeubauer absolutely! it's just a way to say that the thread doesn't close an issue. check here the development https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/15

**Comment by cagnulein** [comment]
@JuergenNeubauer we got it! we just need to fix the coordinates of the slider for the inclination and speed! are you able to provide them for your tablet?

**Comment by JuergenNeubauer** [comment]
That sounds promising. Here's an estimate of the coordinates of the slider locations for the NordicTrack X11i Commercial Inclination Trainer:

Speed slider (in units of km/h, increments of 0.1 km/h are possible):
![image](https://user-images.githubusercontent.com/4317013/203900493-85a2f26f-b471-4b00-868e-347099df1462.png)

lowest value: 1.0, location: x = 1207.0, y = 600.2
![image](https://user-images.githubusercontent.com/4317013/203900655-589fbd90-b6b0-46a4-8ed7-18d7d2b3bf5f.png)
highest value: 19.3, difference in vertical y direction from location of 1.0 km/h: delta y = -382.5

intermediate values and differentials: 
from 1.0 km/h to 2.0 km/h: delta y = -21.0
from 2.0 km/h to 3.0 km/h: delta y = -21.0
from 3.0 km/h to 11.0 km/h: delta y = -161.8
from 11.0 km/ to 1.0 km/h: delta y = 202.6

Inclination slider (in units of %, increments of 0.5% are possible):

0% location: x = 74.9, y = 558.2
![image](https://user-images.githubusercontent.com/4317013/203901759-55efabde-86b0-4c3a-b572-36cbda75cf42.png)

lowest value: -6.0%, delta y = 77.9 (at about y = 636.2)
highest value: 40.0%, differential from lowest value (-6%): delta y = -404.5

from 40% to 0%: delta y = 326.6
from 0% to 10%: delta y = -79.9
from 10% to 0%: delta y = 80.9

I hope that helps.

Thanks, Juergen

**Comment by cagnulein** [comment]
hi @JuergenNeubauer amazing job! could i ask you if you can create a math formula or similar?

@victorypoint it's the same tablet of yours?

**Comment by JuergenNeubauer** [comment]
Hi Roberto,

Sure. A linear fit for the **speed slider** goes like this:
measured data: slider value v in km/h, slider location y on screen:
array([[  1. , 600.2],
       [ 19.3, 217.7],
       [  2. , 579.2],
       [  3. , 558.2],
       [ 11. , 396.4],
       [  1. , 599. ]])

The best linear fit is: y = 620.997 - 20.785 * v

**Inclination fit**: slider value inclination in %, slider location y on screen:
array([[  0. , 558.2],
       [ -6. , 636.1],
       [ 40. , 231.6],
       [  0. , 558.2],
       [ 10. , 478.3],
       [  0. , 559.2]])

Best linear fit: y = 565.491 - 8.440 * inclination

The y location for -6% inclination looks wrong, I might have to redo this measurement. The fit residuals are very large, too.
So I re-fitted without the -6 % data point:
array([[  0. , 558.2],
       [ 40. , 231.6],
       [  0. , 558.2],
       [ 10. , 478.3],
       [  0. , 559.2]])
y = 558.833 - 8.173 * inclination

I hope that works. I can test some more soon.

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer Perfect! I will create an apk for you with these formulas. I will tell you when I will be ready, hopefully during this weekend

**Comment by cagnulein** [comment]
[app-debug.apk.zip](https://github.com/cagnulein/qdomyos-zwift/files/10095850/app-debug.apk.zip)
@JuergenNeubauer this is the apk for you, please follow this step
1. remove the current qz companion form your treadmill
2. install this apk
3. grant all the permission for it
4. enable the developer setting in order to to see the touchscreen pressions on the screen visually
5. open qz on your phone as usual
6. try to use the speed and inclination plus/minus button to send the command to the companion

in case something is wrong send me an adb logcat

let me know!

**Comment by JuergenNeubauer** [comment]
Hi Roberto,

Works great. Just a few little hickups. I can use the QZ Android app to control the X11i treadmill after I granted all permissions. I don't know whether all permissions are necessary, but I didn't investigate any further. I only noticed that it did not work when I had not granted any permissions.

I tried to set the changes for speed and incline to 0.1 km/h and 0.5 in the settings for the treadmill in QZ. But QZ seems to ignore this and change speed by at least 0.5 km/h and inclination by at least 1.0%.

I can change speed in both directions to increase and decrease speed. But again only in increments of 0.5 km/h. I would like to have increments of 0.1 km/h, that's what the treadmill natively is capable of doing.

However, I can only increase inclination, but not decrease it. I'm also not sure whether some general processing in QZ will not allow me to set the inclination to negative values? Somewhere in the code I saw that some portion of the code would limit inclinations to non-negative values. I don't know whether that happens here.

Another random observation: I had switched on the Random training option so the treadmill was going quite crazy. What I would expect to be able to do for my safety is to over-write any input from QZ by using the local controls. But that doesn't work right now.

Thanks so much for this work.

Cheers, Juergen

**Comment by cagnulein** [comment]
> Hi Roberto,
> 
> 
> 
> Works great. 

yeah!

> Just a few little hickups. I can use the QZ Android app to control the X11i treadmill after I granted all permissions. I don't know whether all permissions are necessary, but I didn't investigate any further. I only noticed that it did not work when I had not granted any permissions.

yes that's right, i should add a popup to ask about this to the users.


> I tried to set the changes for speed and incline to 0.1 km/h and 0.5 in the settings for the treadmill in QZ. But QZ seems to ignore this and change speed by at least 0.5 km/h and inclination by at least 1.0%.

does your treadmill offer this possibility as well? i mean with the slide on the ifit app are you able to do this small changes?

> I can change speed in both directions to increase and decrease speed. But again only in increments of 0.5 km/h. I would like to have increments of 0.1 km/h, that's what the treadmill natively is capable of doing.

check my above question

> However, I can only increase inclination, but not decrease it. I'm also not sure whether some general processing in QZ will not allow me to set the inclination to negative values? 

oh right your treadmill has negative values! i will handle this tomorrow, it's an easy task!


> Another random observation: I had switched on the Random training option so the treadmill was going quite crazy. 

random is random :) i mean i'm using this feature to have a crazy workout :)

> What I would expect to be able to do for my safety is to over-write any input from QZ by using the local controls. But that doesn't work right now.

what do you mean? anyway random training programs doesn't this for sure :)

**Comment by cagnulein** [comment]
@JuergenNeubauer actually I checked the code and the negative inclination should be already handled. Do you see the negative values on qz? if so don't you see at all the gesture on the treadmill tablet?

**Comment by JuergenNeubauer** [comment]
Ok. I also tried again and sometimes it works, sometimes it doesn't. Sometimes the inclination jumps by 3%, sometimes I can increase and decrease in 1% increments, sometimes I can only increase, but not decrease. I generated a debug log from QZ but I don't know whether that contains any relevant information. 

[debug-Sun_Nov_27_20_33_07_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10100299/debug-Sun_Nov_27_20_33_07_2022.log)
[debug-Sun_Nov_27_20_35_55_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10100301/debug-Sun_Nov_27_20_35_55_2022.log)

Should I try to debug the Companion? How would I do that?

To answer your previous questions, my treadmill offers speed increments of 0.1km/h on the tablet interface and also via the hardwired buttons. It offers inclination increments of 0.5% also via both soft and hard buttons.

Thanks, Juergen

**Comment by cagnulein** [comment]
> Should I try to debug the Companion? How would I do that?

yes, in this way `adb logcat -d > logcat.log`

**Comment by cagnulein** [comment]
use this apk that has more debug informations 
[app-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/10101355/app-debug.zip)

**Comment by JuergenNeubauer** [comment]
I'm having some trouble getting the logcat. When I run adb via WIFI, do I first have to connect to the device similar to your installation script? I am getting an error message saying that the service is not available or that adb could not connect. I will try again after I restart the computer (it's a Windoze box).
Any other ideas in the meantime?

**Comment by TomD87** [comment]
Adding info from our facebook chat.
I have installed app-debug.apk.zip as listed above. Nothing seems to have changed, no function when using + or - in the QZ app but it still reads speed and incline correctly.

My T8.5 s has a similar X-Y location as above, not sure how to get an exact measurement for you.

**Comment by cagnulein** [comment]
@TomD87 enable all of this. after this, don't you see any swipe? ![image](https://user-images.githubusercontent.com/48216/204620049-c87c4692-03e9-455d-8e82-7cad2313dc33.jpeg)![image](https://user-images.githubusercontent.com/48216/204620082-c403bdf4-b7c7-4de4-9a06-c20a06b29c6a.jpeg)![image](https://user-images.githubusercontent.com/48216/204620098-1aab8928-c345-47c0-b8bd-7074c843061d.jpeg)![image](https://user-images.githubusercontent.com/48216/204620105-2eb09cea-96fe-4a19-aadd-c914ee1dd5fe.jpeg)

**Comment by cagnulein** [comment]
> I'm having some trouble getting the logcat. When I run adb via WIFI, do I first have to connect to the device similar to your installation script? I am getting an error message saying that the service is not available or that adb could not connect. I will try again after I restart the computer (it's a Windoze box).
> 
> Any other ideas in the meantime?

yes the flow is the same as when you installed the apk. maybe the adb flag on the tablet is not enabled anymore? can you try also with a usb cable?

**Comment by JuergenNeubauer** [comment]
It's been flaky lately to even install the Companion via adb. I will try again after a reboot.

How can I enable the adb flag on the tablet?

I don't think I have access to the tablet to connect a usb cable? The tablet is mounted into the panel of the treadmill and I would have to take the treadmill apart which is not something I want to do right away (although it shouldn't be difficult to do).

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer i mean this one ![image](https://user-images.githubusercontent.com/48216/204623363-eae66581-35ee-4de8-81d7-3219bb65bbc7.jpeg) 

hah ok i didn't know about the usb. try to reboot both (pc and tm)

**Comment by JuergenNeubauer** [comment]
Finally I was able to get the logcat. It seems I have to first "Revoke USB debugging authorizations" and then re-enable USB debugging for adb to reconnect to port 5555.

But now the QZCompanion doesn't work any more. I think I'm using the latest version that has the treadmill selection GUI where I select the X11i treadmill. I can not control neither speed nor incline. I can't see any swipe movements any more.

Anyhow, here are some logcat files. I don't know whether there's anything useful in them.

[qzdebug.zip](https://github.com/cagnulein/qdomyos-zwift/files/10117333/qzdebug.zip)

Please let me know what else I can do? Maybe go back to a previous version that had worked?

Thanks, Juergen

**Comment by victorypoint** [comment]
@JuergenNeubauer, I was having the same issues.. no swipes or control of incline or speed. For me the trick was to go to the properties of the companion app, hit stop, clear cache under storage (don't clear data), relaunch the companion app, then back to iFit to test.
-Al

**Comment by JuergenNeubauer** [comment]
Ok, thanks, I will try that. I can't keep track of how many times I've done that already, though.

I've seen some messages in the logcat from QZ, received by the Companion with the message load -1, -100. I don't know what that means, but it just never changed, regardless of what I've been doing. In other cases this happened:

QZ:UDPListenerService: Got UDP broadcast from 192.168.0.14, message: 4.5;-100

Inclination value of -100, where does that come from?

**Comment by JuergenNeubauer** [comment]
I tried to 'force stop' and clear the cache of QZCompanion on the treadmill, but this didn't change anything. I am using the latest app that has the treadmill selection interface. Can I use a previous one? Which one should I use?

**Comment by victorypoint** [comment]
@JuergenNeubauer, I just added a new batch script to the QZ Companion install package - called 'QZ-Companion-reset.bat - at https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage. Download the file and run it in your installation folder after restarting your trainer and enabling USB Debugging.

Let me know if this helps.
-Al

**Comment by JuergenNeubauer** [comment]
[logcat.long.log](https://github.com/cagnulein/qdomyos-zwift/files/10119697/logcat.long.log)
[logcat.brief.log](https://github.com/cagnulein/qdomyos-zwift/files/10119698/logcat.brief.log)
[logcat.default.log](https://github.com/cagnulein/qdomyos-zwift/files/10119699/logcat.default.log)
[logcat.log](https://github.com/cagnulein/qdomyos-zwift/files/10119700/logcat.log)

**Comment by JuergenNeubauer** [comment]
Hi Al,

I tried the reset script but it didn't help in any way that I noticed. Whenever adb can't connect to the treadmill, I have to "Revoke USB debugging authorizations" and the switch USB debugging back on. 

I used your installation script to re-install QZCompanion that I also downloaded again from your install repo. Then I was able to control inclination and speed from QZ. But again speed and inclination jumped by large steps.

Then I tried to get a logcat, but then adb couldn't connect any more. And after resetting the USB debug stuff, and finally running the debug capture, QZ wouldn't change any speed or inclination any more.

I got some logcat again from when I was using QZ to change speed and inclination while the treadmill seemed to ignore all of this.

**Comment by cagnulein** [comment]
> [logcat.long.log](https://github.com/cagnulein/qdomyos-zwift/files/10119697/logcat.long.log) [logcat.brief.log](https://github.com/cagnulein/qdomyos-zwift/files/10119698/logcat.brief.log) [logcat.default.log](https://github.com/cagnulein/qdomyos-zwift/files/10119699/logcat.default.log) [logcat.log](https://github.com/cagnulein/qdomyos-zwift/files/10119700/logcat.log)

@JuergenNeubauer from these log the main problem is that QZ companion can't connect to the adb, so that's why you don't see a swipe command.

So I had an idea to simplify all of this: I will add in the companion a button with the ability to save a logcat file directly from the app, so then you have just to attach it here. Should it help?

**Comment by JuergenNeubauer** [comment]
Yes, that would help. Just need to figure out how to get the logcat off the tablet?

Weren't there any message such as this in the logcat?
QZ:UDPListenerService: Got UDP broadcast from 192.168.0.14, message: 4.5;-100

Did the latest QZCompanion app in @victorypoint 's repo contain some more debug outputs? Otherwise I'll try to re-install your debug version again.

**Comment by cagnulein** [comment]
> Yes, that would help. Just need to figure out how to get the logcat off the tablet?

you can use the browser on the tablet and upload it here?

> 
> Weren't there any message such as this in the logcat?
> 
> QZ:UDPListenerService: Got UDP broadcast from 192.168.0.14, message: 4.5;-100

yes but there are also the adb connection error. that's why you don't see the swipes

> 
> Did the latest QZCompanion app in @victorypoint 's repo contain some more debug outputs? 

use only my repository, i'm doing the modifications for the logcat inside the app

> Otherwise I'll try to re-install your debug version again.

wait until i will have a stable build for the debug log from the companion itself

**Comment by cagnulein** [comment]
@JuergenNeubauer can you try to use the 3.0.5 and check if the logcat button works?
it writes inside /sdcard/ a log file

let me know

**Comment by cagnulein** [comment]
@JuergenNeubauer @victorypoint confirm me that the last apk has the logcat button working.

so you can install it and try, you don't need to play with adb settings. you have to reach the point where the swipe commands are working from qz companion.

then we should understand the coordinates issue

let me know

**Comment by JuergenNeubauer** [comment]
You might have thought about this already. It might be possible (for you, not for me ;-)) to have a setup step for QZCompanion where a QZCompanion Setup Wizard asks for swipes on the treadmill tablet. Touch events should get logged somewhere, see for example the discussion here:
https://stackoverflow.com/questions/38692705/log-the-key-event-when-using-adb-input
https://stackoverflow.com/questions/27701071/how-to-find-the-coordinates-of-my-touch-event
https://stackoverflow.com/questions/21180649/get-maximum-x-and-y-coordinates-from-android-screen-from-command-line
https://developer.android.com/studio/command-line/dumpsys

After that the Setup Wizard could figure out the linear mapping and do a test evaluation, etc.

**Comment by cagnulein** [comment]
@JuergenNeubauer nice idea :) but 2 days ago we weren't able to change the swipe so, for now we can proceed in this way :) at least in order to have a stable behavior for you and @victorypoint  :)

**Comment by JuergenNeubauer** [comment]
Sure, one problem at a time. This was just an idea for the future.

**Comment by cagnulein** [comment]
@JuergenNeubauer yeah a really nice one! i will start a branch for this!

did you test the new one?

**Comment by JuergenNeubauer** [comment]
I will once I get home.

**Comment by JuergenNeubauer** [comment]
content://com.android.externalstorage.documents/document/primary%3AeruCrashLog%2F6fed5aa4c2%2F2022-11-29.logs.txtcontent://com.android.externalstorage.documents/document/primary%3AeruCrashLog%2F6fed5aa4c2%2FcrashManifest.jsoncontent://com.android.externalstorage.documents/document/primary%3AeruCrashLog%2F6fed5aa4c2%2FadbLogs.txtcontent://com.android.externalstorage.documents/document/primary%3AeruCrashLog%2F6fed5aa4c2%2F2022-11-30.logs.txt

**Comment by JuergenNeubauer** [comment]
content://com.android.externalstorage.documents/document/primary%3AeruCrashLog%2F6fed5aa4c2%2F2022-11-29.logs.txt

**Comment by JuergenNeubauer** [comment]
I can see the log button. Where can I find the log? How can I get the logs out? I feel so lost trying to do anything on this ancient tablet or on an Android system in general.

**Comment by JuergenNeubauer** [comment]
I'm not able to control speed and inclination from QZ any more. I reinstalled the first version that somehow worked from about 5 days ago: https://github.com/cagnulein/qdomyos-zwift/files/10095850/app-debug.apk.zip

It seems I can get the debug log via adb logcat from the Windoze machine. Just once in a while I have to uncheck and recheck USB debugging and also first revoke USB authorizations. Then I can reliably connect to the treadmill via adb logcat.

I don't know how to go back to the state of five days ago when it kind of worked.

**Comment by cagnulein** [comment]
> I can see the log button. Where can I find the log?

`/sdcard/logcat.log`

> How can I get the logs out? 

Can't you use a browser on the tablet? If so you can login to github and post directly the log here.

> I feel so lost trying to do anything on this ancient tablet or on an Android system in general.

our timezone are not playing with us. With @victorypoint i'm chatting every day by messenger because we have a similar hours, maybe the weekend will be ok for us to chat on messenger or whatsapp? What do you think?

> I'm not able to control speed and inclination from QZ any more. I reinstalled the first version that somehow worked from about 5 days ago: https://github.com/cagnulein/qdomyos-zwift/files/10095850/app-debug.apk.zip

yes I was suggesting the same thing: we have to rollback to this version and we have to reproduce the working scenario. Maybe a full reset of the tablet could help?

> It seems I can get the debug log via adb logcat from the Windoze machine. Just once in a while I have to uncheck and recheck USB debugging and also first revoke USB authorizations. Then I can reliably connect to the treadmill via adb logcat.

with my last apk you shouldn't do this anymore. So use the https://github.com/cagnulein/qdomyos-zwift/files/10095850/app-debug.apk.zip , put the tablet in the scenario that the swipe works, and WITHOUT modifing anything else, put the newer apk.

> I don't know how to go back to the state of five days ago when it kind of worked.

as i said above, try to reset the tablet, it's the only thing that comes into my mind since I can't test with your tablet :(

**Comment by cagnulein** [comment]
hi @JuergenNeubauer any news?

**Comment by JuergenNeubauer** [comment]
Sorry, I lost some steam here. I want to reset the treadmill to factory and start from scratch. I'm not sure when I will have time, hopefully over the winter break. I guess my marathon training goals that rely on the Zwift treadmill are too ambitious ;-)

**Comment by cagnulein** [comment]
> Sorry, I lost some steam here. I want to reset the treadmill to factory and start from scratch. I'm not sure when I will have time, hopefully over the winter break.

ok no problem :)

> I guess my marathon training goals that rely on the Zwift treadmill are too ambitious ;-)

ahahah never train for a marathon with a treadmill. A treadmill train your heart but not your legs
