### ISSUE TITLE
Life fitness T5 Track Connect Treadmill

### ISSUE THREAD

**Issue by Alavana** [cagnulein/qdomyos-zwift#1013]
Hi,

My name is Alan. (A.S. Webb)
I am pasting this here as was posted on the Facebook group following your request for me to open a ticket with your help.
I thank you in advance.

"I have a Life Fitness T5 Track Connect treadmill which is Bluetooth/Zwift compatible. It can be programmed via the LF App to respond to speed intervals but as this is a `Domestic` grade treadmill and not classed as a `Facility` grade treadmill, the intervals have to be divided equally and this is very limiting in what you are allowed to select. 
With a `Facility` type treadmill, (Gyms/Clubs/Leisure Centres) costing in excess of £8000 you have an unlimited combination of speed setting intervals that you can input.
Would your App/system allow me to bypass this annoying and frustrating limit they have imposed on the lower end market treadmills? I say `lower end` but it still costs around £4500."

Kind Regards
Alan

**Comment by cagnulein** [comment]
Hi @Alavana did you already test it with qz? Are you able to post a screenshot from nrfconnect app to double check the Bluetooth characteristics of it? Nrfconnect is a free app on the store. Let me know

**Comment by Alavana** [comment]
Thank you for replying. I have not as yet but I will do this as soon as I am able and reply to you with the answer.

**Comment by Alavana** [comment]
I have paid, downloaded and installed your app on my Samsung Galaxy S21 Ultra but the actual app is not showing up on my phone. If I go into the android list of Apps, only then can I locate it.

**Comment by cagnulein** [comment]
never saw such an issue. can you open it from the app list?
it could be an issue of the latest android version. join also the beta of qz from the google play page.
let me know

**Comment by cagnulein** [comment]
p.s. i'm going out with my family, i will be back in a couple of hours

**Comment by Alavana** [comment]
![Screenshot_20221030-131511_nRF Connect](https://user-images.githubusercontent.com/117019543/198880662-b3b72929-a209-4198-a8b7-6e06cc627480.jpg)
![Screenshot_20221030-130208](https://user-images.githubusercontent.com/117019543/198880664-4dd9762e-53e4-46b3-b431-601fabd36c3a.jpg)

The NRF connect app installed on phone (as did yours) and is visible on screen of phone. I have installed two screenshots, so it seems your app does see the treadmill but I am trying to figure out how to use it.

We will have to work through this over next couple of days or coming week as i have work commitments also. Let me know what else to do please?

**Comment by cagnulein** [comment]
perfect @Alavana did you try to start the treaadmill so? do you see the metrics? if not send me a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
