### ISSUE TITLE
Samsung S6 Active (Android 7.0)

### ISSUE THREAD

**Issue by mattm382** [cagnulein/qdomyos-zwift#102]
I have connection stability issue.  The app will not stay connected to my Echelon Connect Sport bike.  It connects instantly but within 1 minute it loses connection.  Force close the app and reopen and same thing happens.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5760750/btsnoop_hci.log)

**Comment by mattm382** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5760752/btsnoop_hci.log)

**Comment by mattm382** [comment]
Here is a log I did with the Echelon app.  It did lose connection briefly one time during a 5 minute ride.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5760789/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@mattm382 so looking on your #101 you don't have this issue on the fire tablet 8" isn't it? i guess it just a matter of the hardware inside of the S6. I mean, for what i quicly saw, when the bridge advertise ends, the connection to bike drops too. i can try to add an option to disable the bridge, just to understand if i'm right. If this is the issue, i could add an option to change the way i advertise the bridge for these devices.

**Comment by cagnulein** [comment]
#75

**Comment by mattm382** [comment]
Correct.  The fire tablet has no connection issue to the bike.

**Comment by mattm382** [comment]
Here is a log with Relaxed Bluetooth mode enabled.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5760853/btsnoop_hci.log)

**Comment by cagnulein** [comment]
just a note: with "Virtual Device" setting to off, the connection is stable. It means that the advertising of the bridge make it drops (not at the very start, i guess when it stops)

**Comment by cagnulein** [comment]
https://bugreports.qt.io/browse/QTBUG-89757

**Comment by cagnulein** [comment]
@mattm382 did you try reducing the name of your device to "run" ? i'm closing this one, if you still need help, feel free to reopen it
