### ISSUE TITLE
[BUG] QZ / ZWIFT / Treadmill / Smartwatch: Different distance value

### ISSUE THREAD

**Issue by istvanszegedi** [cagnulein/qdomyos-zwift#1022]
**Describe the bug**
It is more like a technical question.

The setup is the following:
Treadmill: Capital Sports Infinity Pro 4
QZ app: Running on Xiaomi 12T (Android 12)
ZWIFT: running on Lenovo Yoga Tab 11 (Android 12)
Huawei Watch 3 Pro: to have a totally independent result about my run ;-) (Harmony OS)

After a 10.0km run measured by the QZ app, the values are not the same on other devices
Treadmill: 10,3 km
QZ app: 10.0 km
ZWIFT: 10,41 km
Huawei Watch 3 Pro: 10.21 km

Can I finetune something in the QZ app to have "almost" the same result on QZ as ZWIFT shows?
I know the difference is less than 5% between QZ and ZWIFT, but I expected totally equal numbers.

I assumed that QZ gets the distance value (or speed  + time) from the Treadmill and synchronizes with ZWIFT.
I attached the screenshot and QZ debugs file.

[2022_NOV_3.zip](https://github.com/cagnulein/qdomyos-zwift/files/9931999/2022_NOV_3.zip)

**Comment by cagnulein** [comment]
Thanks, I will check this tomorrow

**Comment by cagnulein** [comment]
I guess I fixed this morning @istvanszegedi 
It was releated to your specific treadmill.
It will be in the 2.11.86 (i will upload it today)
Let me know when you will try

**Comment by istvanszegedi** [comment]
I will try Already Today. might be within a shorter distance.

**Comment by cagnulein** [comment]
ok i didn't built it yet, busy day :(

**Comment by istvanszegedi** [comment]
OK. It is not urgent, just tell me when you did it.

**Comment by cagnulein** [comment]
done @istvanszegedi

**Comment by istvanszegedi** [comment]
![IMG_20221106_171956](https://user-images.githubusercontent.com/23429485/200188541-b804134b-9b6e-4511-9e4e-f055cd2a2e4c.jpg)
![IMG_20221106_172413](https://user-images.githubusercontent.com/23429485/200188544-fcb561e6-14bd-4349-aba7-58a814a44984.jpg)
![Screenshot_2022-11-06-17-19-16-651_org cagnulen qdomyoszwift](https://user-images.githubusercontent.com/23429485/200188549-63d5778d-d3f9-40e6-a8d8-1a0e8739c2dc.jpg)
![Screenshot_20221106-172009](https://user-images.githubusercontent.com/23429485/200188550-32acbd0d-a471-482c-97d7-d13bdcb19547.jpg)

**Comment by cagnulein** [comment]
amazing! thanks @istvanszegedi
