### ISSUE TITLE
[REQ] Octane Fitness Q37xi Support

### ISSUE THREAD

**Issue by sethgregory** [cagnulein/qdomyos-zwift#1023]
**The machine**
Octane Fitness Q37xi elliptical

**The problem**
Once Octane Fitness was sold by Nautilus to TRUE Fitness, they basically stopped any and all development on the companion apps.  It's not even available for download anymore from the Play Store, needs to have an APK sideloaded, and the app is truly awful:
![image](https://user-images.githubusercontent.com/471394/199831720-2c04550e-4265-424c-bcd0-038ad95287db.png)

Would be great to be able to breathe some new life into it.

**Steps Taken For Bluetooth Snoop Log**

- Opened app and connected to machine
- Chose "quick start"
- Slowly raised resistance level from 1 to 10, and then up to 20
- Put hands on heart rate monitor leads
- Selected all three different machine "booster" modes
- Selected "end workout"

**Bluetooth Snoop Log**
[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/9932876/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
great @sethgregory i will check it tomorrow!

**Comment by sethgregory** [comment]
In case this is helpful, it's also seen by nRF Connect:
![image](https://user-images.githubusercontent.com/471394/199835107-56fcd643-573d-44dc-ac62-a9816139e85a.png)

**Comment by cagnulein** [comment]
> * Slowly raised resistance level from 1 to 10, and then up to 20

did you change them by the app itself? I can't see any frame about this.
In the meantime I'm adding all the rest :)

Do you have already the qz app installed @sethgregory  ? ios or android?

**Comment by cagnulein** [comment]
also at which speed you run more or less for the workout? @sethgregory

**Comment by sethgregory** [comment]
Sorry, I changed it on the machine itself, I'm not sure if the app even allows you to.  The end of the workout was done at resistance level 20.  I didn't do a full workout, only a few minutes' worth.  I can do another capture later today or tomorrow if it's helpful.

**Comment by cagnulein** [comment]
ok no problem, let's see if the other metrics are right

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

i'm going to bed right now so i will manage this in 8 hours

**Comment by cagnulein** [comment]
@sethgregory any news?

**Comment by sethgregory** [comment]
Reopening the issue; life happened and I wasn't able to pay attention to this for quite some time, and then Bluetooth stopped working on my machine altogether.  Got it fixed, flashed new firmware on the Q37xi, and bought the qz app on Android, ready to focus attention on it again.  Here is a new bt snoop log, including changing resistance values from the app, should see the packets there now hopefully!

[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/11559998/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
@sethgregory did you collect this hci snoof using the octane app? did you change the resistance from their app? i don't see them. also from the qz side, are you seeing the right metrics? If not send me a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

**Comment by sethgregory** [comment]
Hi @cagnulein - please find attached the [debug log](https://github.com/cagnulein/qdomyos-zwift/files/11619249/debug-Tue_May_30_14_31_29_2023.zip) and the corresponding [screen recording](https://youtu.be/9CvBj7gbUDo) of the session with QZ.

**Comment by sethgregory** [comment]
I would likely need an Android build.

**Comment by cagnulein** [comment]
perfect, i already built it, 
send me an email to roberto.viola83 at gmail.com indicating this ticket if you are not seeing the version 2.13.64 in the play store
Let me know!

**Comment by cagnulein** [comment]
@sethgregory any news?

**Comment by cagnulein** [comment]
@sethgregory are you still interested on this?

**Comment by sethgregory** [comment]
Yes, thank you for the ping.  I will post an update this week.

**Comment by cagnulein** [comment]
i updated the ios version with the speed fix. if you want i have an android
build ready too here on github

Il giorno mar 12 dic 2023 alle 20:28 Seth Gregory ***@***.***>
ha scritto:

**Comment by UnmutualHA** [comment]
Hello.  I have an Octane XR6xi that is no longer broadcasting on Bluetooth.  I've identified relevant UUIDs from another Octane machine and was hoping to create a replacement radio using an ESP32, but I can't get the Octane to recognize the ESP32 as a radio.  Are you aware of anyone who has analyzed the firmware from the original Nordic chip?  I have a .bin file from Octane that was intended to get the radio working again (I believe a patch to v. 1.48), and although it worked for more than 10 years, it no longer does as it is stuck on "Upload."  Any thoughts would be appreciated.  Thank you.

**Comment by cagnulein** [comment]
Unfortunately no, I don't have experience on this. Did you try running
claude fable?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno lun 7 set 2026 alle 01:44 UnmutualHA ***@***.***>
ha scritto:

**Comment by UnmutualHA** [comment]
Thank you for the reply.  I was able to wake the chip by using nRESET on the debugger footprint.  I’ll see if that is enough to get the Octane communicating again.  Octane does not make it easy!

**Comment by cagnulein** [comment]
Let me know how it goes, I'm a firmware developer so in case I could help


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno lun 7 set 2026 alle 06:32 UnmutualHA ***@***.***>
ha scritto:

> *UnmutualHA* left a comment (cagnulein/qdomyos-zwift#1023)
> <https://github.com/cagnulein/qdomyos-zwift/issues/1023#issuecomment-5565061591>
> Thank you for the reply. I was able to wake the chip by using nRESET on
> the debugger footprint. I’ll see if that is enough to get the Octane
> communicating again. Octane does not make it easy!
>

**Comment by UnmutualHA** [comment]
Thanks.  Will do.
