### ISSUE TITLE
Android user. Apps from amazon appstore and playstore are different. 

### ISSUE THREAD

**Issue by itzamiguel** [cagnulein/qdomyos-zwift#1026]
**Describe the bug**
Seems like the version on amazon appstore is running behind compared to the one on playstore. Noticed that the app from playstore can read my wahoo strap HR while the app on the amazon appstore can't. 

**To Reproduce**
1-Install app from amazon app store. I'm able to add the HR strap but the tile won't display any number, always cero. 
2- Uninstall app
3-Install app from playstore. After connecting same wahoo HR strap I'm able to see without issues the value of my HR.

Decided to try another Bluetooth HR which seem to show HR value on the tile but it losses connection very often that it's unusable. This all happens when using the amazon appstore qdomyos-swift app.

**Expected behavior**
Would expect both apps from either stores to be the same. Found this by accident.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 12

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - OS: Android 12

**Comment by cagnulein** [comment]
Yes thanks, I'm waiting the review from Amazon 
Thanks for the reminder

**Comment by cagnulein** [comment]
submitted https://forum.unity.com/threads/64-bit-support-amazon-build-issue.1111333/
