### ISSUE TITLE
Does not work in Proform TDF 10.0

### ISSUE THREAD

**Issue by ea1ggb** [cagnulein/qdomyos-zwift#1028]
Greetings, I enclose a log. I can't get it to work on a Proform TDF 10.0 bike. This bike has an integrated tablet and doesn't allow you to connect it to the Ifit app installed on another device, I think that's the problem, this bike doesn't send data or by bluetooth or wifi.

**Comment by cagnulein** [comment]
hi @ea1ggb you need to use the https://github.com/cagnulein/QZCompanionNordictrackTreadmill
Let me know

**Comment by ea1ggb** [comment]
I follow all the steps indicated for the installation but it does not work

**Comment by cagnulein** [comment]
@ea1ggb it doesn't work it's quite generic :) could you please describe what do you get? Did you allow all the permission for the QZ companion app? Also share a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
@ea1ggb any news?

**Comment by cagnulein** [comment]
Yes @ea1ggb

**Comment by ea1ggb** [comment]
@cagnulein yes, I have it activated but it does not adjust the resistance according to zwift

**Comment by cagnulein** [comment]
@ea1ggb the qz companion app doesn't allow auto resistance. It's currently under development 

Actually it sends the metrics to zwift (so it's opening your bike to any other platform different from ifit).

**Comment by ea1ggb** [comment]
@cagnulein  Ok, good job, at least I'm not a slave to Ifit anymore, thanks and I'll keep an eye on your development.

**Comment by cagnulein** [comment]
@ea1ggb i'm closing this one, since the auto resistance/speed is already covered by this ticket https://github.com/cagnulein/qdomyos-zwift/issues/954 follow this one instead. Thanks!
