### ISSUE TITLE
[BUG] connection problems connect ex3 to trainerroad 

### ISSUE THREAD

**Issue by Surlyfrs** [cagnulein/qdomyos-zwift#1037]
> **Describe the bug**

Qdomyoszwift app connects to iOS app and shows all information (power cadence). Using android device for trainerroad. Android device sees QZ#2 and can pair. Correct battery % of iOS device is displayed but power and cadence are not shared. 

**To Reproduce**
Start bike, start qdomyoszwift app. 

Open TR on second device, connect to QZ device

App connects but no live data are transmitted 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 N/a

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS:  ios 16.1.1
 - Version 2.10.116 qdomyoszwift 

**Append a debug log**

 Can’t attach see email
  
**Additional context**
 See email from Forrest Svingala.

**Comment by cagnulein** [comment]
[debug-Sun_Nov_13_16_08_34_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10000462/debug-Sun_Nov_13_16_08_34_2022.log)
[debug-Sun_Nov_13_16_09_47_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10000463/debug-Sun_Nov_13_16_09_47_2022.log)
[debug-Sun_Nov_13_16_05_54_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10000464/debug-Sun_Nov_13_16_05_54_2022.log)

**Comment by cagnulein** [comment]
Hi @Surlyfrs can you try disabling the iOS peloton workaround on the experimental settings on QZ and restart QZ?
Let me know if it's better
Thanks

**Comment by cagnulein** [comment]
any news @Surlyfrs ?

**Comment by Surlyfrs** [comment]
Roberto,

I finally got around to a quick test of your solution (turning off the iOS
peloton workaround) and it seems to work now! I will let you know if it
works after a full length ride.

Best,
-Forrest
