### ISSUE TITLE
[REQ] Footpod (Stryd) support with manual incline

### ISSUE THREAD

**Issue by victorypoint** [cagnulein/qdomyos-zwift#1038]
The Stryd footpod (and perhaps others) are currently supported in QZ via Accessories - Power Sensor and 'Power Sensor as a Treadmill'. This works fine in Zwift, however adding manual incline to the workout is requested. That is, provide the ability to adjust the QZ incline +/- values (e.g. negative 25% or less to positive 25% or more) manually to match the treadmill incline, so that when Zwift exports to Strava the elevation graph will reflect the incline changes. Currently, pressing the incline +/- buttons does not change inclination values while using Stryd as a speed sensor. This functionality would be similar to what the Runcline app offers, however Runcline does not offer negative incline (going downhill).

**Comment by victorypoint** [comment]
Wow! That was fast! Can you do Android version as well for testing?

**Comment by victorypoint** [comment]
Ok, did some detailed testing of the new Android QZ with manual inclination controls and used fitfileviewer.com to inspect the resulting FIT files.

Test 1: November 15 2022 - Afternoon run with Stryd footpod
  - NT 2950 TM, Stryd footpod for speed and cadence, QZ Android, Zwift Windows 11
  - Ran for 2 km and made manual incline changes
  - Zwift FIT file (imported Strava workout at https://www.strava.com/activities/8124394097) - altitude goes up to 25m where it stays then up to 71.2 where it stays
  - QZ FIT file (imported Strava workout at https://www.strava.com/activities/8124395724) - altitude decends to -30 then climbs to -12.8 then decends to -22 then climbs to -16.6m

Test 2: November 15 2022 - Evening run with QZ Companion
  - NT 2950 TM, QZ Companion for speed and cadence, QZ Android, Zwift Windows 11
  - Ran for 2 km and made manual incline changes
  - Zwift FIT file (imported Strava workout at https://www.strava.com/activities/8124348146) - altitude stays at 0-1 then climbs to 17.6 and stays then climbs to 25.2m
  - QZ FIT file (imported Strava workout at https://www.strava.com/activities/8124349054) - altitude decends to -30 then climbs to -12.8 then decends to -22 then climbs to -16.6m

Findings:
  - In both runs, it appears that Zwift is not recording negative elevation/decents but instead only records positive elevation/ascents. During a decent (negative incline), Zwift maintains the current elevation.
  - Is this a bug in Zwift? Are negative inclines recorded for Zwift cyclists and not runners?
  - A QZ FIT file imported in Strava does not show a map or an elevation graph. I suspect this is due to the FIT file not containing lat/long coordinates. A Zwift FIT file contains lat/long coordinates and shows a map and elevation graph in Strava

See attached Stryd FIT files for inspection:
[stryd.zip](https://github.com/cagnulein/qdomyos-zwift/files/10025033/stryd.zip)

See attached QZ Companion FIT files for inspection:
[qz-companion.zip](https://github.com/cagnulein/qdomyos-zwift/files/10025037/qz-companion.zip)

**Comment by cagnulein** [comment]
> * Is this a bug in Zwift? Are negative inclines recorded for Zwift cyclists and not runners?

it's possible. there is another user that was a specialist on this, let me find him


> * A QZ FIT file imported in Strava does not show a map or an elevation graph. I suspect this is due to the FIT file not containing lat/long coordinates. A Zwift FIT file contains lat/long coordinates and shows a map and elevation graph in Strava

yes this is highly possible, you can try generating a fit file from qz using the "gpx following feature" with only a downhill and we will find out ;)

**Comment by victorypoint** [comment]
> > * A QZ FIT file imported in Strava does not show a map or an elevation graph. I suspect this is due to the FIT file not containing lat/long coordinates. A Zwift FIT file contains lat/long coordinates and shows a map and elevation graph in Strava
> 
> yes this is highly possible, you can try generating a fit file from qz using the "gpx following feature" with only a downhill and we will find out ;)

@cagnulein , how do I enable GPX following in QZ? I don't see that option anywhere in latest Android version.

**Comment by cagnulein** [comment]
@victorypoint left side bar-> open gpx :)

**Comment by aherrang** [comment]
Hello, I do not have a treadmill supporting negative inclination. Maybe I cloud try simulating it by using a negative offset to see if I can record it and see it reflected on the strava’s inclination profile.

Regarding to the second question, effectively direct sinc from QZ to strava does not records the coordinates in order to see the map in Strava.

**Comment by victorypoint** [comment]
> @victorypoint left side bar-> open gpx :)

Sorry, Just a bit confused. So you want me to open one of the GPX files provided with QZ and do what?

**Comment by cagnulein** [comment]
> Sorry, Just a bit confused. So you want me to open one of the GPX files provided with QZ and do what?

no you have to create/download one with negative inclination (maybe a simple gpx trip on a downhill). In this way QZ will write GPS coordinates and you will give negative inclination. If this time will work on Strava, it means that it's simply how Strava works :)

**Comment by victorypoint** [comment]
> > Sorry, Just a bit confused. So you want me to open one of the GPX files provided with QZ and do what?
> 
> no you have to create/download one with negative inclination (maybe a simple gpx trip on a downhill). In this way QZ will write GPS coordinates and you will give negative inclination. If this time will work on Strava, it means that it's simply how Strava works :)

Ok, I found a good source of treadmill GPX files with coordinates and elevation to use. So when I open avGPX in QZ, I get the message to press start to begin. Not sure exactly what this means. Do I simply start a treadmill workout with manual incline?

![Screenshot_20221121-200138](https://user-images.githubusercontent.com/63697253/203182745-7dc17425-bbc0-428f-ad4f-f6279a0ed142.png)

**Comment by cagnulein** [comment]
on qz then you have to press pause and start again in order to start the gpx following @victorypoint

**Comment by victorypoint** [comment]
@cagnulein, not sure if I did this right but here's what I tested:

- Exported one of my outdoor walks from Strava as GPX file - https://www.strava.com/activities/7841028184
- using treadmill with QZ and QZ Companion. In QZ I opened GPX file from previous step, press pause and start to start GPX following
- Ran treadmill with several negative inclines to override GPX elevation
- Exported FIT file on completion and imported to Strava - unfortunately the elevation is identical to the original outdoor walk - https://www.strava.com/activities/8162709245

**Comment by cagnulein** [comment]
@victorypoint so strava is throwing away the elevation in the fit file, and it's using the one from the gps coordinate. It has its sense after all

so what's the next step? I mean there is something that I can do on this? Did you check also on intervals.icu ? maybe different results? also garmin connect? You can try to reach strava support, but I guess they don't want to fix something like this

**Comment by app4g** [comment]
for Sträva, if you want strava to honour the elevation inside the FIT file, you have to tell it that the watch has a barometer when sending the FIT file over to strava. Then Strava will use the elevation within the FIT file.

**Comment by cagnulein** [comment]
it makes sense @app4g 
of course this is true when there are gps coordinates inside the fit file. For QZ workouts, the gps coordinates are not present unless you use the 3d maps feature. But in that case, it has sense to use the gps coordinate only to strava.

**Comment by app4g** [comment]
I have not tried to send a FIT file that doesn't contain GPS tracks (but has elevation) to Strava, so I am not sure about that.

**Comment by cagnulein** [comment]
you can use a simple one from QZ if you want to try :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 mar 2023 alle ore 09:17 app4g ***@***.***>
ha scritto:

**Comment by albertoherran** [comment]
> for Sträva, if you want strava to honour the elevation inside the FIT file, you have to tell it that the watch has a barometer when sending the FIT file over to strava. Then Strava will use the elevation within the FIT file.

Hello, and how do you specify it (the watch has a barometer) when sending the FIT file over to strava?

Thanks in advance,

**Comment by cagnulein** [comment]
@albertoherran it's a property of the fit file that, in case, I can add it. But as I said, this should be added into zwift instead, because it's zwift that writes the gps coordinates

**Comment by albertoherran** [comment]
Ah ok ok, and this is why Pascal Carrieres ads the Garmin Fenix 5S when synchronizing with Strava using his app RunCline.
OK, thanks!

**Comment by cagnulein** [comment]
@albertoherran it makes sense. But with the QZ fit file I already have the elevation even without that field, isn't it?
