### ISSUE TITLE
Follow Up Issue with/ Elite Suito-T #862 [BUG]

### ISSUE THREAD

**Issue by Arfaxad1** [cagnulein/qdomyos-zwift#1039]
Hi Roberto:

Hope all is good with you. 

I am bothering you up again because the issue with my e-trainer it does persist. 

Here is the issue:
https://github.com/cagnulein/qdomyos-zwift/issues/862#issuecomment-1189886628

When you shared the updated version on test flight it was working perfectly until the version get expired and I had to download the current version from the app store and the problem with the calibration came back.

Is there anyway you can help me? Or please just let me know if I have to download a new version of the app (currently I have 2.10.116).

Thanks

**Comment by cagnulein** [comment]
@Arfaxad1 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
