### ISSUE TITLE
[BUG]Care Fitness CV-351 : 

### ISSUE THREAD

**Issue by BoGaFi** [cagnulein/qdomyos-zwift#1042]
Here is the bug report for Care Fintess CV-351

The problem is the power and speed on android is not accurate at all with this bike on Android (it is  good on IOS).

However, here what has been done 

* part of a workout on kinomap last for 4 minutes. there are 24 levels of resistance on this bike. Resistance change automatically
with kinomap application.

1/ resistance starting from 12 and last one minute
2/ resistance go to 13 and last one minute
3/ resitance go to 14 and last one minute
4/ resistance go to 15 and last one minute

Globally i tried to have a cadence of  an average of70 during all the workout 

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10041184/btsnoop_hci.log)

**Comment by cagnulein** [comment]
done @BoGaFi You will see the version 2.11.98 in an hour!

**Comment by BoGaFi** [comment]
@cagnulein thanks, will check it !

**Comment by cagnulein** [comment]
[debug-Fri_Nov_18_16_15_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10042534/debug-Fri_Nov_18_16_15_08_2022.log)

**Comment by BoGaFi** [comment]
As dicussed with @cagnulein , here is the logs from the last session 

Starting from resistance 1 to 10 (just a small thing : when i want to go to 8, i tapped 2 times on the + button, so i get to level 9, and asap, i click on minus button, to go to leel 8).

What i saw, is that the power is depending of the speed cadance (undependantly of the resistance level).

So if i do a speed cadence of 70 level 1 or speed cadence 70 level 10, i have the same power.
Cadence seems not to be accurate (cadence of about 70 display 90).

Tests have been done with toorx hertz xr 770 on and off (same result)




[debug-Sat_Nov_19_16_08_09_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10047306/debug-Sat_Nov_19_16_08_09_2022.log)

**Comment by cagnulein** [comment]
@BoGaFi mmm I checked the log, i don't see a real wattage increment in the log. So you told me that was the same on the android app of your bike? Instead the iOS showing real wattage? what about kinomap instead? if kinomap on android showing the real wattage it would be good to collect a hci snoof running kinomap in order to check how they request wattage from the bike. What do you think?

**Comment by BoGaFi** [comment]
Hello Roberto

I answer here as I haven't access to my github account right now. (I will
update later). But yes I have the same problem on kinomap android.

Below is the example of the ride i mention in the first post of the issue
on github :

https://strava.app.link/2lsAbVJi6ub

(speed and power does not change even if resistance level increment)

If i do the same on ios on kinomap, it is working fine.

So possible a problem linked to Android from the bike.

Regards
Alain

Le dim. 20 nov. 2022 à 04:50, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
@BoGaFi actually you're answering on github 😃 

anyway we can try the qz version on ios, i'm sending you the version right now

let me know

**Comment by BoGaFi** [comment]
@cagnulein/qdomyos-zwift
***@***.***>

Ah yes, surprised as i havent my password on my github account on my phone
^^

OK will test on ios!


Le dim. 20 nov. 2022 à 06:10, Roberto Viola ***@***.***> a
écrit :

**Comment by BoGaFi** [comment]
I did the test on ios, but had same result as android. Perhaps in kinomap
they did some manual changes to have the watt/speed accurate.

Note that even if watt displayed does not take in consideration the
resistance level, it takes at least the cadence speed to compute it.

Not sure if in QZ it is possible to do some ratio of the resistance level
to compute a more accurate watt depending of the resistance level like
following :

Watt = watt from bike " resistance level / some ratio

Not sure if it is something already done in QZ for others bikes...




Le ven. 18 nov. 2022 à 14:24, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
@BoGaFi absolutely!
you can fill a table like the one on this thread https://github.com/cagnulein/qdomyos-zwift/issues/323

let me know if it's ok for you

**Comment by BoGaFi** [comment]
Roberto

Yes i thin it can be good.

Not sure what are the différents columns in the file:

Each line seem to start with epsilon
Second field seems to be the resistance level?
Next fields seem to be the power depending of the cadence?

I haven't found the template that describes the columns on github, just
some examples with datas filled.

Where do you put the file?

Le dim. 20 nov. 2022 à 09:45, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
put it here on github 😀 
columuns are cadence, power and resistance

**Comment by BoGaFi** [comment]
@cagnulein/qdomyos-zwift ***@***.***>

I created a doc file, not sure about the format itself. I did it manually
in kinomap and i did some extrapolation between resistance

Columns separated by comma

First column, the resistance level (from 1 to 24)
Second column, cadence (from 50 to 100)
Third column, watt





Le dim. 20 nov. 2022 à 10:05, Roberto Viola ***@***.***> a
écrit :

**Comment by BoGaFi** [comment]
with the file
[Cv351.docx](https://github.com/cagnulein/qdomyos-zwift/files/10049644/Cv351.docx)

**Comment by cagnulein** [comment]
great @BoGaFi ! i will implement this tomorrow !

**Comment by BoGaFi** [comment]
Great thanks!

Le dim. 20 nov. 2022 à 13:37, Roberto Viola ***@***.***> a
écrit :

**Comment by BoGaFi** [comment]
correction of a bug in docx
[Cv351.docx](https://github.com/cagnulein/qdomyos-zwift/files/10049861/Cv351.docx)

**Comment by cagnulein** [comment]
@BoGaFi I implemented it. I only worried about the fact you told me that the cadence wasn't precise. Do you have this same behaviour with and without toorx hertz xr 770 setting?

**Comment by BoGaFi** [comment]
@cagnulein 

Nice ! I will check it when the new apk will be uploaded !

Concerning the cadence, yes same resulst with hertz xr 770 settings on or off. But not a problem as i can add my cadence sensor device (as in this case the cadence is well displayed)

**Comment by BoGaFi** [comment]
@cagnulein 

I did some others checks concerning the cadence, and on the bike itself, looks like it is the good values.

It is only on QZ, that they are too high

(55 on the bike give 90 in QZ for instance)

**Comment by cagnulein** [comment]
@BoGaFi hertz xr 770 setting have different way to measure cadence. maybe can you do a video along with a debug log showing cadence from the bike display and cadence from qz?

**Comment by BoGaFi** [comment]
@cagnulein 

looks like we wrote at the same time :-) . 

Yes i can do a video and send you the logs along with this.

**Comment by BoGaFi** [comment]
@cagnulein 

Impossible to share a video with the size, as the bike loop over all the parameters, and until it get to the cadence display, there is one minute time elapsed. I put the log and a picture.

This time, it was different, i had displayed a cadence of zero (in both hertz xr 770 on/off).

in the picture, as you can see it is zero displayed in cadence on QZ and 58 in cadence on the bike (which is a good number)

I attached the log too.

perhaps i can use my cadence sensor as my cadence sensor gives good number on QZ ? not sure if you take the cadence from what it is displayed in
[debug-Mon_Nov_21_11_50_33_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10055890/debug-Mon_Nov_21_11_50_33_2022.log)

![20221121_115601](https://user-images.githubusercontent.com/47600047/203035061-fb7aa81a-daa6-4b82-9acf-dd1e6062f8c1.jpg)
 QZ for your computation ?

**Comment by BoGaFi** [comment]
i did another test, this time i have the cadence displayed on the screen. What i did, mose of the first part of the ride,
i was about 61/62 cadence, and the other part, about 76/77 cadence.

What was displayed for 61/62 on QZ : about 120 
What was displayed 76/77 : about 110

(looks like it put less when my cadence increase)

i joined the log too

[debug-Mon_Nov_21_11_59_48_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10056005/debug-Mon_Nov_21_11_59_48_2022.log)

**Comment by cagnulein** [comment]
ok thanks i will check. very crazy day today

**Comment by BoGaFi** [comment]
@cagnulein 

i have check others metrics 

* watts are not displayed on the bike so cannot say for this one
* heart rate is the same for QZ as the bike
* speed is about 4 times less that the bike in QZ
* calories are good between bike and QZ

i put that but not sure if some ot the settings in QZ are perhaps calculated like the speed and don't come from the bike

not sure it could help but in case of...

**Comment by cagnulein** [comment]
got the cadence! the developer that wrote this protocol is completely drunk! anyway i'm fixing it

**Comment by BoGaFi** [comment]
@cagnulein

Very nice !!!

**Comment by BoGaFi** [comment]
oh yes it is a big modification that you needed to do for this bike in the code !

**Comment by cagnulein** [comment]
Great! @BoGaFi sure i'm checking right now the cadence issue!

**Comment by cagnulein** [comment]
@BoGaFi new version online with the fix! I hope this will close this issue :)

**Comment by BoGaFi** [comment]
All looks like to run good !!! Going to test it on vzfit with authentic mode and denivellation on

Thanks so much for your support !

**Comment by cagnulein** [comment]
Great! Let me know how it goes!
