### ISSUE TITLE
Add ProForm Cadence LT Treadmill to QZ to connect to Peloton [REQ]

### ISSUE THREAD

**Issue by tuffdadsf** [cagnulein/qdomyos-zwift#1047]
I own a ProForm Cadence LT Treadmill. Basic treadmill with BT and works fine with the iFIT software and also has auto speed settings - meaning the iFIT workout can change the speed remotely using BT connection. The treadmill doesn't have an electric incline function.

The QZ app can see and connect to the treadmill via BT but it doesn't have a setting that reads the speed or distance, etc. built into the treadmill.

What I would like QZ to do is connect to my tread and then connect to Peloton to allow me to do treadmill workouts that will auto change speed - similar to the functions that QZ can do with a ProForm bike and PowerZone training.

Thanks for the help!

**Comment by cagnulein** [comment]
hi @tuffdadsf in order to add i need some logs following https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using ifit app and changing the speed from the app itself

let me know

**Comment by tuffdadsf** [comment]
Here's the log! Thanks again
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10050130/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks, i will check tomorrow

**Comment by cagnulein** [comment]
@tuffdadsf done! I added a new setting for you in the proform treadmill section. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@tuffdadsf did you try?

**Comment by tuffdadsf** [comment]
Hello, sorry for the late reply.

I got to try my treadmill and it does work with the QZ connect. The speed
shows up, though it is a little bit offset and hard to get it just right in
the app. Also the prompt for a Peloton workout comes up like it should.

Thanks so much for the help!

**Comment by cagnulein** [comment]
so we are good to go @tuffdadsf  ?
