### ISSUE TITLE
Connecting to VZfit

### ISSUE THREAD

**Issue by martinwprior** [cagnulein/qdomyos-zwift#1048]
I have installed the QZ app. I have managed to get both my HRM and Cadence sensors to attach 
I am able to see the HRM on the HUD toggling with the Incline.
I cannot however get any movement forward. Just stays stationary.
I am sure its something trivial that I do not understand . 
[debug-Sun_Nov_20_12_13_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10052103/debug-Sun_Nov_20_12_13_30_2022.log)
![image](https://user-images.githubusercontent.com/118702339/202950274-6fb6dde5-323f-49ca-8584-cb0a6e8dca84.png)

In VZFit when I connect it correctly finds my phone and upon starting a ride it displays the HRM. Unfortunately I do not go anywhere :(

**Comment by cagnulein** [comment]
@martinwprior the issue about this log is that you have the "XOSS S-42388" sensor in both cadence and power sensor. leave it only in the cadence sensor setting, disabling the power sensor one. Let me know if it helps and send me another log in case it doesn't
R.

**Comment by martinwprior** [comment]
Sorry I made the change and exited and re ran QZ. Still the same.

When VZfit connects to my phone it is so fast but I think the "empty" comes
up. I cannot catch more than that.

**Comment by cagnulein** [comment]
send me a fresh log now @martinwprior

**Comment by martinwprior** [comment]
Hi Roberto. Not sure if I did something or VZfit. Today was a VZfit update
and it all worked. On the HUD intead of togglng with Incline. Heart and
Incline side by side.

Thank you. Now I must back it up so I do not mess it up. :)

Regards

**Comment by cagnulein** [comment]
great! @martinwprior let me know if you still have issues!
