### ISSUE TITLE
Incorrect layout on settings page on smalls screen

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#105]
For example my Xiaomi Mi3

**Comment by AimanFarooq** [comment]
I just noticed that the UI shifts in a similar way on the tile screen when going from portrait>landscape>portrait on Samsung Galaxy S20.
![Screenshot_20210103-121003](https://user-images.githubusercontent.com/3269808/103487885-672b9800-4dbd-11eb-958c-a05ebc1c46ec.png)

**Comment by cagnulein** [comment]
@AimanFarooq does it happen right after the start if you just start it on portrait mode?

**Comment by cagnulein** [comment]
@AimanFarooq fixed this too! avaiable in the next beta!

**Comment by tanvach** [comment]
I’m having somewhat similar issue with the tiles being too wide to fit rows of 4 tiles on older iOS device (iPhone 6)

![84CB4986-E53A-4A61-91E3-EF55E1752FE1](https://user-images.githubusercontent.com/729913/104851093-ac64c500-58a7-11eb-8d7d-8d1902bd7495.jpeg)

**Comment by ptrinephi** [comment]
Beta 2.3.14 has the setup screen even larger than previous versions.

![148745070_406740870630288_3654636095623696188_n](https://user-images.githubusercontent.com/6604478/107548238-3dffe380-6b83-11eb-8b27-ca8d84573dab.jpg)

**Comment by cagnulein** [comment]
done in version 2.5.23!
