### ISSUE TITLE
Horizon treadmill inclination issue

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1050]
When peloton request inclination 6 it sends 6.5 to the treadmill @janabouc

**Comment by cagnulein** [comment]
[debug-Mon_Nov_21_07_20_34_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10056634/debug-Mon_Nov_21_07_20_34_2022.log)

**Comment by RickNY** [comment]
So - I tried this today.. With difficulty on "Average", it started out at 0 -- and callouts for 0 set the tread to 0, so that part is corrected... But callouts for 2 and 4 set the tread to 1.5 and 3.5.  I would expect for "average" difficulty, that tread incline would equal the called out value.
[debug-Wed_Nov_23_18_16_49_2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/10080038/debug-Wed_Nov_23_18_16_49_2022.zip)

**Comment by janabouc** [comment]
I think Roberto and I discussed this once before. I had the same expectation but I think he said that average was the average of lower and higher. 

I suggest adding another option: Exact or changing Average to Exact rather than average lower and higher.

**Comment by cagnulein** [comment]
@RickNY as @janabouc said, peloton sends only lower and upper inclination. So for the average I just use the middle point of them. Since you have a zwift inclination offset of -0.5 i'm also applying that value to the calculation. So I suggest to put the offset to back to 0 and you should have a better average during the workout.

Let me know your thoughts. Here you can see the metrics that I'm receving from peloton extracted from your log

`"target_metrics_performance_data":{"target_metrics":[{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":144,"start":60},"segment_type":"running"},{"metrics":[{"lower":2.1,"name":"speed","upper":4.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":211,"start":145},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":279,"start":212},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":330,"start":280},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":392,"start":331},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":422,"start":393},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":562,"start":423},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":591,"start":563},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":636,"start":592},"segment_type":"running"},{"metrics":[{"lower":2.5,"name":"speed","upper":4.5},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":689,"start":637},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":742,"start":690},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":786,"start":743},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":1.5,"name":"incline","upper":2.5}],"offsets":{"end":839,"start":787},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":926,"start":840},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1010,"start":927},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1037,"start":1011},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1107,"start":1038},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1168,"start":1108},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1230,"start":1169},"segment_type":"running"},{"metrics":[{"lower":3.2,"name":"speed","upper":5.4},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1261,"start":1231},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":3.5,"name":"incline","upper":4.5}],"offsets":{"end":1305,"start":1262},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1324,"start":1306},"segment_type":"running"},{"metrics":[{"lower":2.1,"name":"speed","upper":4.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1477,"start":1325},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1554,"start":1478},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1607,"start":1555},"segment_type":"running"},{"metrics":[{"lower":3.2,"name":"speed","upper":5.4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1623,"start":1608},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1736,"start":1624},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1792,"start":1737},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1880,"start":1793},"segment_type":"running"},{"metrics":[{"lower":3.2,"name":"speed","upper":5.4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1944,"start":1881},"segment_type":"running"},{"metrics":[{"lower":3.3,"name":"speed","upper":5.6},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":1992,"start":1945},"segment_type":"running"},{"metrics":[{"lower":3.4,"name":"speed","upper":5.8},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2048,"start":1993},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2103,"start":2049},"segment_type":"running"},{"metrics":[{"lower":2.1,"name":"speed","upper":4.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2157,"start":2104},"segment_type":"running"},{"metrics":[{"lower":2.2,"name":"speed","upper":4.4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2235,"start":2158},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2455,"start":2236},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2505,"start":2456},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2585,"start":2506},"segment_type":"running"},{"metrics":[{"lower":3,"name":"speed","upper":5},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2647,"start":2586},"segment_type":"running"},{"metrics":[{"lower":3.1,"name":"speed","upper":5.2},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2667,"start":2648},"segment_type":"running"},{"metrics":[{"lower":3.2,"name":"speed","upper":5.4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2700,"start":2668},"segment_type":"running"},{"metrics":[{"lower":2,"name":"speed","upper":4},{"lower":0,"name":"incline","upper":1}],"offsets":{"end":2760,"start":2701},"segment_type":"running"}],"time_in_metric":[{"name":"speed","value":0},{"name":"incline","value":0}]}})`

**Comment by RickNY** [comment]
Oh Ok - that explains it. I didn’t realize you fixed the offset to work with Peloton also

**Comment by RickNY** [comment]
> I suggest adding another option: Exact or changing Average to Exact rather than average lower and higher.

I agree.. For incline, exact callouts are fine with me.. What I wish was more granular is the speed callouts -- if there was an option to set speed smack in the middle of the called out range -- lower is too slow for me on most of these, and average is way too high for me on a power walk for some of these workouts.  

One question on the "Target speed" tile -- does that show the target speed after the adjustment for difficulty?  I wish the Peloton app displayed the callouts somewhere on the screen for each segment.. How does the actual Peloton tread do speed callouts?  Is it similar, i.e. a range combined with the user's specified difficulty level?

**Comment by cagnulein** [comment]
> I agree.. For incline, exact callouts are fine with me.. What I wish was more granular is the speed callouts -- if there was an option to set speed smack in the middle of the called out range -- lower is too slow for me on most of these, and average is way too high for me on a power walk for some of these workouts.

so you need a sort of "difficulty" level for the speed? Something that you can set from 50% to 200% for example like zwift does? Of course it's totally doable :) You saw above in my comment, what peloton sends to us, so we have to play with that number.

> One question on the "Target speed" tile -- does that show the target speed after the adjustment for difficulty?

yes the one that i'm sending to the TM

> I wish the Peloton app displayed the callouts somewhere on the screen for each segment.. How does the actual Peloton tread do speed callouts?

you can find them in my comment above, check the speed keyword

**Comment by cagnulein** [comment]
#1458
