### ISSUE TITLE
Norditrack S22i Error

### ISSUE THREAD

**Issue by jjharaldson** [cagnulein/qdomyos-zwift#1052]
When I try to install the Norditrack Treadmill APK I get an error that says "Unfortunately the Qz Companion Norditrack Treadmill has stopped working". Also I seem to not be able to download the APK at all. I added this to the S22i thread disregard, sorry.

**Comment by cagnulein** [comment]
@jjharaldson send me an adb logcat and i will be able to
help you ;)

**Comment by cagnulein** [comment]
let's talk about this on #954
