### ISSUE TITLE
Strava upload shows moving time - a lot longer than actual QZ recorded elapsed time.QZ 

### ISSUE THREAD

**Issue by N5PHT** [cagnulein/qdomyos-zwift#1057]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@N5PHT you need to put info about your issue and the fit file at least

**Comment by N5PHT** [comment]
I will do that in tomorrow ride.

**Comment by N5PHT** [comment]
I have no clue how to do this. Sorry just too beyond my ability.

**Comment by cagnulein** [comment]
> I have no clue how to do this. Sorry just too beyond my ability.

which part?

**Comment by cagnulein** [comment]
just attach here the fit file that you have in the qz folder

**Comment by cagnulein** [comment]
@N5PHT any news from strava?
