### ISSUE TITLE
QML layout on iPad Split Scren

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#106]
now:
![image](https://user-images.githubusercontent.com/48216/103473936-561f5e80-4d9e-11eb-9212-45bcadfa3f5c.png)

requested:
![image](https://user-images.githubusercontent.com/48216/103473939-59b2e580-4d9e-11eb-9c51-137fc478077a.png)

**Comment by AimanFarooq** [comment]
These screenshots are on the Desktop view of a Samsung device in Dex mode. My suggested layout is one take but I think this could work in other ways too. The user story for this request is: As an Android user with a single large display (Dex or larger phone/tablet) I would like a way to view just my relevant metrics while maintaining a large view of my class.

**Comment by AimanFarooq** [comment]
For reference, here is how I was doing this previously with the Echelon app. 
![Screenshot_20210103-001204_Echelon Fit](https://user-images.githubusercontent.com/3269808/103474434-9d82fc00-4d58-11eb-84c1-95fd413694b1.png)

**Comment by cagnulein** [comment]
done, you will find a new option in the next beta (i guess, i will release it today)! If you like it, when you will test it, close this :)

**Comment by cagnulein** [comment]
@AimanFarooq beta update is live ;)

**Comment by AimanFarooq** [comment]
This looks great know, thank you for the update! One last thing that would really put this over the top, it would be great to hide the action bar on scroll to maximize tile display in a small window.
![Screenshot_20210103-120249](https://user-images.githubusercontent.com/3269808/103487933-ae198d80-4dbd-11eb-9c2d-f102002f0b94.png)

**Comment by cagnulein** [comment]
done! it will be avaiable in the next beta :P

**Comment by AimanFarooq** [comment]
Amazing, thank you!

**Comment by cagnulein** [comment]
@AimanFarooq this is from 1 year ago, didn't you tryied yet? :D

**Comment by AimanFarooq** [comment]
Hahaha, I have been using it. I just got the notification and thought this another enhancement you added last month that I missed, not last year 😅
