### ISSUE TITLE
incline doesn't work

### ISSUE THREAD

**Issue by jonathanbolduc1** [cagnulein/qdomyos-zwift#1063]
[debug-lun__déc__5_11_37_06_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10156771/debug-lun__dec__5_11_37_06_2022.log)

treadmill horizon 7.0at 
kinomap

**Comment by cagnulein** [comment]
@jonathanbolduc1 in this log are you sure you were well connected to kinomap? did you see the speed on kinomap?

**Comment by jonathanbolduc1** [comment]
yes i see the speed on kinomap and i can adjust speed with qz or treadmill

**Comment by cagnulein** [comment]
@jonathanbolduc1 Could you please turn off the iOS peloton workaround in the experimental settings, restart qz and redo the test?
Thanks

**Comment by jonathanbolduc1** [comment]
with peloton workaround turned off, kinomap doesn't start

**Comment by jonathanbolduc1** [comment]
I made few test and I can only rise the incline with Qz, the incline - doesn't work. when I put it back to 0 incline on the treadmill, the qz app show 0 incline.

**Comment by cagnulein** [comment]
> I made few test and I can only rise the incline with Qz, the incline - doesn't work. when I put it back to 0 incline on the treadmill, the qz app show 0 incline.

could you create me a debug log for this?

> with peloton workaround turned off, kinomap doesn't start

I will try this next week when I will be at home again

**Comment by jonathanbolduc1** [comment]
[debug-mar__déc__6_18_20_12_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10171699/debug-mar__dec__6_18_20_12_2022.log)

**Comment by cagnulein** [comment]
the inclination minus should be already fixed in the beta @jonathanbolduc1 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

about the kinomap request it doesn't matter since that firmware request it's only when you use the treadmill directly to their app. Since you're using the QZ bridge, Kinomap is not aware of your firmware.

I will check the kinomap implementation tomorrow or friday.

**Comment by cagnulein** [comment]
@jonathanbolduc1 fixed! I'm gonna send you another version with the kinomap fix!

**Comment by jonathanbolduc1** [comment]
Hi, thank you very much, incline work now. still have few bugs but I can live with that. first one, when incline on kinomap is at 15%, qz and treadmill show 13.5 or 14.5. Next one, at the end of the video, the treadmill usually stop but it don't. I try pausing and stopping qz but it treadmill still running. I push stop on the treadmill to stop it. I attached the log if you want to take a look. Regards
[debug-jeu__déc__8_17_19_09_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10190582/debug-jeu__dec__8_17_19_09_2022.log)

**Comment by cagnulein** [comment]
> still have few bugs but I can live with that. first one, when incline on kinomap is at 15%, qz and treadmill show 13.5 or 14.5.

it's because kinomap is sending `requestInclination= 14.8` so qz is rounding. you can increase slightly the difficult of kinomap to force an upper rouding (for example 110%)

> I push stop on the treadmill to stop it. I attached the log if you want to take a look. Regards

found the issue. I will send you another one with the fix

**Comment by cagnulein** [comment]
@jonathanbolduc1 version sent!

**Comment by jonathanbolduc1** [comment]
Another bug today but the debug log was turned off.  The incline was 0 on the treadmill and on qz but the elevation gain was rising. I can record debug log later this week if you want.  Regards,

**Comment by cagnulein** [comment]
@jonathanbolduc1 Ok let me know

**Comment by cagnulein** [comment]
@jonathanbolduc1 any news?
