### ISSUE TITLE
[REQ]Proform Sports CX Custom Resistance/Watt Profile

### ISSUE THREAD

**Issue by Tinydancer1** [cagnulein/qdomyos-zwift#1068]
I tried calibrating the wattage power the QZ app calculates for my Proform Sports CX bike using the "Watt Gain" setting against the reading that my Garmin Power Pedals are displaying and have run into a couple of problems.

I've adjusted the Watt Gain against the garmin 3second average power and found a Watt Gain of 0.36 works well at resistance level 5 to 9. resistance level 10 and above and a delta starts to appear which gets larger as the resistance increases. 

I'm guessing that the app needs a custom profile which allows for individual watt gains per resistance level? Following this I can then test to see whether the watt gain remains reasonably accurate when cadence increases or whether a number of adjustments would be needed as cadence rises.  

Further, The Watt Gain set at 0.36 causes the wattage calculation to max out when the cadence is increased during a sprint.  for example, as an example the app may stop at 170watts even if cadence is 90 or 120, but the garmin app may show 250watts. Is there a way to increase the maximum watts for the app?

I see that there appears to have been a couple of conversations and solutions on this for Echelon bikes (mgarcea profile) but I couldn't find anything for the proform and no drop down in the bike settings to select a profile. I'm happy to provide bike/pedal data for if someone is able to create a specific profile or point me in the direction of how to tackle this.

**Comment by cagnulein** [comment]
hi @Tinydancer1 create a table like this one https://github.com/cagnulein/qdomyos-zwift/issues/323#issuecomment-894600090 and I will implement it!

**Comment by Tinydancer1** [comment]
By way of update, I've done a ride to capture some data.  The approach has been to cycle through the resistances and then ramp up the cadence - 60, 70, 80, 90, 100 & 110rpm - for a minimum of 30-45 seconds to get an average data sample. As I cannot pedal consistently at a required cande, I've included any variance in my pedaling cadence .  i.e. for 60rpm I've included data from 57-63rpm.   Resistance 14 and above is already a test of my fitness, especially by the time I'd got to that point in the test so there is minimal data at the moment. The attached image shows that data in a spreadsheet.  

Resistance level 4-10 all seem to have a steady consistent increase in power as the cadence increases.  I'd spent 30 minutes completing resistance 4 - 10.  Resistances 11 to 15 seem to break away from the pretty consistent increase of the lower resistances by quite a jump.  I'd have thought that the application of the brake on the cycle wheel would have been consistent.  

Further, upon completion of resistance 15 samples, I lowered the resistance to 7,8 &9  to cycle at around 80rpm for a 20-30min cool down.  I've looked at this data and the wattage is quite a bit higher - 15-30 watts - than the samples taken during the ramp up tests.  I did read  somewhere on here or the QZ facebook that another rider had identified accuracy issues with there echelon which was related to heat.  I'm not sure whether this is the same.   Maybe this is why resistance level 11 and above have moved away from the other power lines on the graph.

Unless anybody has any thoughts, I'll carry out the sample again but start the higher resistances to fill some gaps and also see whether temperature influences the reading.
  
<img width="1367" alt="ProformSportCX_Data_13Dec22" src="https://user-images.githubusercontent.com/120249416/207201289-24c9dce2-1b89-466b-b164-65eb5f784a14.png">

**Comment by cagnulein** [comment]
ok great!

> Unless anybody has any thoughts,

the profile will be optional, so we don't need to worry about this :)
@mgarcea any hints on this scenario?

**Comment by mgarcea** [comment]
Looks really good.  Not sure if you are already using it, but if you use Golden Cheetah to analyze the data you can average the power over some amount of time which can help smooth the data a little.

**Comment by Tinydancer1** [comment]
> 

Hello.  I've not used it before.  I've just downloaded it and will have a look. thanks

**Comment by Tinydancer1** [comment]
I've not forgotten about this.  I've been testing out the resistance reduction over time.  Noting that the power pedals are absolute I can only imagine that the resistance belt loosens when getting warm or the magnet and wheel friction weakens due to heat.  The attached graph example is a cadence average 90rpm on level 9 resistance.  the trend line is pretty stable for the first half of the sample (around 60 minutes) and then starts to drop around 10-20 watts, which in the scheme of things isn't much.  I'm not sure yet whether the resistance will continue to weaken the longer I ride as I typically ride no more than 2 hours on the exercise bike.

The second chart is a data dump of a bunch of various duration rides (1-2 hour rides).  and whilst there are some trend lines forming, I'm not happy with some of the spikes or overlapping power lines.  The lower resistance trend lines are notably smoother most likely because the bike is cold whilst warming up.  I don't think I'm going to be able to figure out the exact time that the resistance starts to weaken so I'll set out on resampling the data doing 10-20 minutes over the xmas break and go with that.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/120249416/208787510-64ed8c3e-155f-4818-a287-6fcf67356ba4.png">

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/120249416/208786981-e2bdab88-5646-4cff-9610-e446832d7256.png">

**Comment by cagnulein** [comment]
yeah this temperature issues are something that I already saw also in the echelon bikes, isn't it @mgarcea ?
I guess there is no simple solution for this, of course we can put the time variable in the equation but it will never be perfect.
Let me know and I will be happy to implement something more precise than the actual one :)

**Comment by mgarcea** [comment]
Yeah and it might be difficult to quantify the resistance shift because it's likely dependent on the intensity of the ride and how much heat is being generated.  We also resorted to keeping the rides short when testing each resistance level to try and get more consistent repeatable results so I think that is a good strategy.

**Comment by cagnulein** [comment]
@Tinydancer1 hi! good year! any news about this?

**Comment by Tinydancer1** [comment]
> 

Happy New Year.  I had been away on holiday (its summer here).  I did collect more data prior to Xmas but I don't seem to be able to get definitive trend lines for each resistance level.   I've collected about 25,000 data points but there just seems to be to much crossover on the lower resistances where I'd have expected there to be a clear power gap at a specific cadence rpm as the levels increased.  I think this issue might need to be on hold until I can get enough data for clear trend lines. 
  
<img width="958" alt="image" src="https://user-images.githubusercontent.com/120249416/213047147-23f09237-5746-4903-9005-fe5b2bd519bc.png">

**Comment by cagnulein** [comment]
Happy new year! Ok no hurry from me! Thanks for the updates!

**Comment by Tinydancer1** [comment]
Hello @cagnulein  .  

An update - 
I've captured a bunch more data.
I limited the rides to 30 minutes to try and offset any slippage that heat may be causing once the bike is warmed up (not sure whether this is a belt or magnet issue).
I have also set the data to capture power on a 5 second average rather than instant to smooth out any power surges when pedaling.

Their is still to much variance in the data, between 50 to 100 watts. I'm generally riding between 150-250 watts so its a huge range to be wrong.

As the resistance level does not stay constant as the ride progresses I don't believe that the original intent of a custom profile is going to be worthwhile as it will over estimate power production as the ride goes on and the resistance eases.

Unless anybody has any ideas on how to make the resistance stay constant I think this item should be closed until (if) I come up with a way to resolve the issue.

Thank you for offering to look at this though :)

Adam

**Comment by cagnulein** [comment]
that's a shame! do you have any idea about all this huge range of variability? maybe a not precise resistance mechanism on hardware?

**Comment by Tinydancer1** [comment]
It has to be something hardware related.  I'm pretty confident that the power pedals are reporting within tolerance.

Its either the belt or the resistance clamp.  The bike doesn't feel like its slipping so I don't think it is belt related.  I should be able to confirm this with a couple of marks on the wheels/belt and check for movement.

As I think about it I'm wondering whether it is the resistance clamp and its loosing clamping pressure as time goes.  I'm not scienced up enough to know whether an increase in heat in the wheel/clamp would significantly impact the friction resistance between wheel/clamp but assuming that the computer resistance levels are absolute and not relative to the previous level I think I should be able to test whether the actual clamping pressure is weakening by cycling the resistance every few minutes to "reset" the resistance level.  I'll report back.
