### ISSUE TITLE
[BUG]Domyos EL 520 Minimum Resistance

### ISSUE THREAD

**Issue by jjortizfernandez** [cagnulein/qdomyos-zwift#1069]
Domyos El 520 Elliptical in AutoResistance mode.
When Zwift or VzFit send Negative Resistance below 1, Domyos El 520 Servo Motor goes Out of Bounds and get Stuck, making necessary to disassemble the Bike to recalibrate ServoMotor.

**To Reproduce**
Connect Domyos El 520 to QzDomyos.
Open Zwift or VzFit with autoresistance enabled.(Caution, risk of blocking Resistance ServoMotor)

Please if possible, add a Minimun Resistance Limit For Domyos El520 Elliptical bike (same as Erg Minimum Resistance)

**Smartphone (please complete the following information):**
 - Device: Ipad
 - OS: 16.
  
  
**Additional context**

**Comment by cagnulein** [comment]
oh so they didn't implement a filter on hardware? unbeliavable!
Ok i'm adding a limit on the code so if the resistance is below 1 i will translate to 1 for this elliptical. Is it ok @jjortizfernandez  ?

**Comment by jjortizfernandez** [comment]
Many Thanks Roberto !!Enviado desde mi iPadEl 10 dic 2022, a las 12:23, Roberto Viola ***@***.***> escribió:﻿
oh so they didn't implement a filter on hardware? unbeliavable!
Ok i'm adding a limit on the code so if the resistance is below 1 i will translate to 1 for this elliptical. Is it ok @jjortizfernandez  ?

**Comment by cagnulein** [comment]
done, i'm sending you the new beta!

**Comment by jjortizfernandez** [comment]
That was a Fast Fix !!
Super Customer Service !!
Will you Upload Beta to TestFlight ?
Many thanks again !

**Comment by jjortizfernandez** [comment]
Tested!  Working Great !

**Comment by cagnulein** [comment]
Great!

**Comment by jjortizfernandez** [comment]
One last question.
I am checking the Gears option, but Gears tile does not show on main screen….

**Comment by cagnulein** [comment]
hah maybe i didn't add for the elliptical! i will add them for sure!
