### ISSUE TITLE
Gears tile for elliptical

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1071]
One last question.
I am checking the Gears option, but Gears tile does not show on main screen….

_Originally posted by @jjortizfernandez in https://github.com/cagnulein/qdomyos-zwift/issues/1069#issuecomment-1345281863_

**Comment by cagnulein** [comment]
done @jjortizfernandez send me an email to get the new beta!

**Comment by jjortizfernandez** [comment]
Hello Roberto
E-mail.    ***@***.***
Thanks

**Comment by cagnulein** [comment]
@jjortizfernandez you need to send me it to 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS, otherwise github will strip out your email. Thanks!
