### ISSUE TITLE
power calibration for Domyos Bike[REQ]

### ISSUE THREAD

**Issue by Polar778** [cagnulein/qdomyos-zwift#1078]
Hi,

Is it possible to re-calibrate the power input of the Domyos bike?
I am wirtting this because I known, by putting a powermetter on the domyos bike 500, that the power given by the training bike is highly overestimated, especially for some resistance levels.
So when I use it with applications like Zwift or Kinomap, it is not realistic, and for races it is cheating.
I don't want to swap my powermeter every time between my road bike and my training bike, that's why I want an accurate power from the training bike.
I do some measurments for resistances going from 8 (witch is low) and 15 (max) at different cadences, and wrote the power each time (for resistance level <8 is so low that it have no importance).
Knowing that power is the product of the torque and the speed rotation, I calculate the average torque for each resistance:
Resistance level:      8        9	        10	11	12	13	14	15
torque (N.m)           13.6    15.3	17.3	19.8	22.5	25.6	28.4	35.9

and: power =torque * cadence *2*pi/60

Can you implement this modification for my training bike?

Regards

Michel

**Comment by Polar778** [comment]
Excatly,
But If want to be more precise, the torque is not constant with resistance. I observe that the torque increase with the cadence. For example, the mesured power at max resistance for 100RPM is 414W. So it is less than 10% of error.
That's why I simplifie the model assuming that the torque is constant to an average value.

**Comment by cagnulein** [comment]
done @Polar778 i will send you the beta shortly.
When you will have it, remember to enable the new setting in the domyos bike section
Let me know

**Comment by Polar778** [comment]
Nice, thanks.
Can't wait to test it.
