### ISSUE TITLE
Tiles sticked to 0[BUG]

### ISSUE THREAD

**Issue by Polar778** [cagnulein/qdomyos-zwift#1079]
Hi,

Yesterday was my first real utilisation of the application.
I had a problem because all the tiles had a zero value. The treadmill was connected because I could change the resistance. 
Then I found that clicking pause, then start unlock the situation.
I open this ticket according to your advice.

Regards,

Michel

**Comment by cagnulein** [comment]
hi @Polar778 you need to generate a debug log with the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
