### ISSUE TITLE
[REQ] Strava Virtual Tag Setting

### ISSUE THREAD

**Issue by Fransysco** [cagnulein/qdomyos-zwift#1083]
Ability to not have rides that are imported into Strava be tagged as "Virtual".

A simple toggle in settings would be ideal to enable this for those that may want to not have their rides tagged as virtual. 

Rides that are marked as "Virtual" within Strava do not get imported into Fitbit

**Comment by cagnulein** [comment]
done @Fransysco are you on android or ios? 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Majorswigs** [comment]
***@***.***

**Comment by cagnulein** [comment]
hi @majorswigs you have to send me an email directly, not replying here otherwise github will hide your email. Thanks

**Comment by cagnulein** [comment]
also are you on android or ios?
