### ISSUE TITLE
[REQ] Support Nordictrack S25 treadmill

### ISSUE THREAD

**Issue by magicdude4eva** [cagnulein/qdomyos-zwift#1084]
**Is your feature request related to a problem? Please describe.**
I bought the app on iOS and can pair my Nordictrack S25 treadmill (https://www.nordictrack.de/laufbander/nordictrack-s25-laufband). I was expecting that I was able to control the incline / speed via the App, this does not seem to work. I also thought that I could stop/start the treadmill via the app.

The app does read the speed and incline correctly. I bought the app as I want to move off iFit and over to Zwift for running

**Describe the solution you'd like**
To be able to control speed/incline and start/stop the treadmill via the app.

**Describe alternatives you've considered**
This works via the treadmill console and the app shows the changes

**Additional context**

**Comment by cagnulein** [comment]
@magicdude4eva share a debug log from qz where you are trying to change speed or inclination 
thanks

**Comment by magicdude4eva** [comment]
[debug-So__Dez__18_12_39_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10253721/debug-So__Dez__18_12_39_25_2022.log)

Tks for quick feedback. Debug log attached. I did some manual increases/decreases on the treadmill as well - those are reflected on the app. To me it appears that the increase/decrease buttons are not responding on the app.

FWIW: I have never used the app before and wanted bought it to try out. Could very well be that I made an absolute Newb mistake somewhere. I am running the app on iPhone 13 mini with iOS 16.3.

**Comment by cagnulein** [comment]
ok checked @magicdude4eva 
What you have to do now is this:
- in the proform treadmill section in QZ there are several switches. Each one enable a different profile.
- It's possible that your treadmill has one of the profile already implemented.

In order to test them:
- enable one leaving disabled all the other ones
- restart qz
- try to change the inclination

repeat all these steps for all the profiles (be sure that ONLY one profile is enabled each time).

Let me know!

**Comment by magicdude4eva** [comment]
Hi,

I removed the app (clean-install, just in case I messed up some settings). Then:

- Started the Nordictrack S25 manually
- Started the QZ app, waited till the speed showed on the app
- Then I pressed the speed +/- on the app a few times.
- Then I also pressed the incline +/- on the app a few times.
- I then went back to the Settings, deactivated the device I was testing and selected the next one
- Then I force-closed the app. I did not stop the treadmill
- Then I repeated with the next device in the list

I tried it with all the device options under Proform (Nordictrack 10/T6.5S/T7.0/S30), Proform (1800i/SE/9.0).

I do see that the user-interface for the +/- buttons works - the buttons are pressed/depressed.

**Comment by cagnulein** [comment]
@magicdude4eva from the nordictrack app are you able to change incline or speed from the app itself? if so do you have an android device to collect some more data about your treadmill?

**Comment by magicdude4eva** [comment]
The iFit app (https://apps.apple.com/us/app/ifit-at-home-workout-fitness/id1274601042) does allow manual speed & incline adjustments. I did try to capture a trace with https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/ but this does not work (perhaps on iOS 16.3 this is different).

I am not sure if the S25 works any different to other Nordictracks - the model itself is a year old. I can only think that the QZ app is able to receive the broadcasts and perhaps needs to pair with the treadmill? 

I am not sure how else I could provide additional information other than the debug logs.

**Comment by cagnulein** [comment]
@magicdude4eva You just need an android device and follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md

With this info I will implement it too on qz

**Comment by magicdude4eva** [comment]
Tks for the info - I will look at this after my vacation in January - unfortunately our household is only Apple.

**Comment by cagnulein** [comment]
Ok let me know !

**Comment by magicdude4eva** [comment]
Hi - I struggle to get my hands on an Android device. I also reached out to the iFit community on Reddit (https://www.reddit.com/r/iFit/comments/zozl3j/looking_for_nordictrack_s25_user_who_also_has_an/) and Nordictrack forum (https://www.reddit.com/r/nordictrack/comments/zozm4n/looking_for_nordictrack_s25ifit_who_also_has_an/). 

I am hoping that at some point in time someone will post something. If I happen to stumble across a free Android device somewhere, I will try the above though.

**Comment by cagnulein** [comment]
Thanks for the update. I hope you will find something!

**Comment by cagnulein** [comment]
@magicdude4eva i guess implemented this for another user! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by magicdude4eva** [comment]
Perfect. I sent you an email. Happy to verify on iOS.

**Comment by cagnulein** [comment]
@magicdude4eva any news?

**Comment by magicdude4eva** [comment]
> @magicdude4eva any news?

I am sorry for delay. I tried it this morning and only enabled Nordictrack S25i in the settings. The iOS app finds the device and also instantly displays speed/incline. Clicking any buttons in the app does not change the speed/incline on the treadmill.

Across friends and family we have no Android device and emulators seem not work for me via MacOS - so I can not debug :-( 

I have attached the logs during testing today. If this does not help you, pls close this issue as I am not able to provide the diagnostics you need. thanks again for your help.
[debug-Sa__Jän__21_10_26_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10471879/debug-Sa__Jan__21_10_26_02_2023.log)

**Comment by cagnulein** [comment]
unfortunately no @magicdude4eva 
about the https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/ are you a iOS dev? because it requires a iOS dev license.
Let me know if I can help you somehow
