### ISSUE TITLE
oneplus 6t does not even appear in zwift

### ISSUE THREAD

**Issue by jadair32** [cagnulein/qdomyos-zwift#109]
using an echelon connect sport bike, Peloton compatible setting is turned off, app is connecting to the bike and showing metrics in the app (super useful in its own nice touch adding the 'Peloton equivalent') but when launching the Zwift game on my laptop nothing is being found when searching for a power source.

**Comment by cagnulein** [comment]
Check this
https://www.facebook.com/groups/149984563348738/permalink/151337329880128/

He has the same problem and he fix it ;)

Write here a feedback at the end, thanks

Il mer 6 gen 2021, 03:43 jadair32 <notifications@github.com> ha scritto:

**Comment by jadair32** [comment]
I completely uninstalled and reinstalled zwift (I'm on a windows machine by the way) to no avail; phone is already connected to the laptop via bluetooth; I also tried to disconnect their pairing and re-pair them once Zwift was searching, same results. I know that oneplus has some aggressive battery management, maybe it has to do with that (I turned off battery optimization on the qDomyos application in my oneplus's settings still the same results)?

**Comment by cagnulein** [comment]
@jadair32 do you have another phone on which you could install Zwift and try to see if it will find the OnePlus?
Just to understand of course

**Comment by jadair32** [comment]
I'll have to wait for the wife to get home and have her purchase the application on her google account, I have an OLD Blu device but it doesn't even connect to the bike with the Echelon Fit app.

**Comment by jadair32** [comment]
Oh, I just comprehended what you were asking, I tried Zwift from her phone last night it did not work, I have yet to try her phone with my laptop though.

**Comment by cagnulein** [comment]
@jadair32 try to check on her s8 if with nrfconnect you see the bridge when you have the q app opened on OnePlus and connected to the bike.
Maybe the OnePlus doesn't have the ability to broadcast itself, but it sounds strange to me.

**Comment by jadair32** [comment]
Using nrfconnect, I would look for the MAC address that I find in the status section of my oneplus correct? If so, it's not broadcasting while connected to the bike with the q app (at least not according to nrfconnect on that aforementioned Blu device).

**Comment by cagnulein** [comment]
No don't look for the mac because the mac is changing every time randomly
(Android security feature). Just look for the name of the OnePlus or
"Domyosbridge"

Il mer 6 gen 2021, 18:06 jadair32 <notifications@github.com> ha scritto:

**Comment by jadair32** [comment]
Nope no hits for either the oneplus using the q app and nrf on the blu or vise versa, I'll let you know if I have any success with the wife's s8+ in a few hours.

**Comment by jadair32** [comment]
The new update did something, I can connect to the bike with my blu and zwift on any device for 30 seconds, disabling the virtual device makes it so it doesn't work at all; same results with her S8+ using the q app and any device for zwift.

**Comment by cagnulein** [comment]
ok, sad news :(
i will reopen it if i will discover something more
