### ISSUE TITLE
[REQ] Increase speed on treadmill for the Peloton app for the whole run as upper is too fast and average is too slow

### ISSUE THREAD

**Issue by Holden74** [cagnulein/qdomyos-zwift#1091]
Increase speed on treadmill for the Peloton app for the whole run as upper is too fast and average is sluwtoo slow

**Comment by cagnulein** [comment]
@RickNY

**Comment by cagnulein** [comment]
ok my idea is to use the target speed and target incline tiles with the plus and minus buttons to override the one requested from peloton. What do you think guys?

@janabouc

**Comment by RickNY** [comment]
> ok my idea is to use the target speed and target incline tiles with the plus and minus buttons to override the one requested from peloton. What do you think guys?
> 
> @janabouc

Would that add an offset to the target speed and/or incline that stuck with that metric during changes?  I like the idea of a "difficulty target offset" tile - that is simply a percent change to T. Speed and T. Incline.

**Comment by cagnulein** [comment]
> Would that add an offset to the target speed and/or incline that stuck with that metric during changes?  

yes it's more like a gain than an offset. it's already implemented in this way for the target resistance tile

> I like the idea of a "difficulty target offset" tile - that is simply a percent change to T. Speed and T. Incline. 

exact what i had in mind :)
i will do this today, it's quite simple to do

**Comment by cagnulein** [comment]
done @Holden74 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Holden74** [comment]
Tried the beta unfortunately when I choose target speed it doesn't hold and just resets back to the peloton one when there is a change on the app

**Comment by RickNY** [comment]
I had some issues with this as well.. Just tried it and Im attaching my debug log...  First -- I don't know if its the size of my tiles on my iPhone or not -- but I have no indication of what percentage gain I've selected - nor how to get back to 'no gain'.  I do see the "100% @0%=1" under the T. Speed and T. Incline -- but nothing there changed, was it supposed to?  Also - it seems like it took multiple presses on the + buttons to implement some sort of change.  Finally, as @Holden74 mentioned, once there is a callout change, it seems to revert the gain back.  

I did have one other issue with this in this log -- please let me know if you want me to open a separate ticket for this -- because this has happened before, prior to this new build.  It is in regards to heartrate reported to QZ from the Apple Watch.  I will sometimes find that I will start the workout on the watch first by pressing Start.. I will wait until the watch app shows a heart rate, and then I start on the iPhone.. Sometimes -- the heartrate gets "stuck" in QZ where it is not updating, either on the watch app or on the phone -- and what I end up having to do is open the Heart Rate app on the watch briefly -- and then QZ starts updating again.  At any rate -- this happened at 6:29 PM, so if you see something in the log, please let me know.  

[debug-Thu_Dec_22_18_13_58_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10291000/debug-Thu_Dec_22_18_13_58_2022.log.txt)

**Comment by RickNY** [comment]
You can see where the heart rate thing occured at 18:28:44 - the heart rate was stuck at 95.. I then opened the Heart Rate app on the watch real quick, and QZ started updating again and jumped to 125 at 18:28:45

**Comment by cagnulein** [comment]
sorry @Holden74 @RickNY  I did an error, the behaviour on the version that I sent of the target speed and inclination tiles was equal to the speed and inclination tile. Now I fixed it.
For me today and tomorrow are travel day, so I will send you a new on xmas day.
Thanks for the feedback



> I did have one other issue with this in this log -- please let me know if you want me to open a separate ticket for this -- because this has happened before, prior to this new build. It is in regards to heartrate reported to QZ from the Apple Watch. I will sometimes find that I will start the workout on the watch first by pressing Start in the watch app.. I will wait until the watch app shows a heart rate, and then I start on QZ on the iPhone.. Sometimes -- the heartrate gets "stuck" in QZ where it is not updating, either on the watch app or on the phone -- and what I end up having to do is open the Heart Rate app on the watch briefly -- and then QZ starts updating again. It tends to get stuck sometime after 60 seconds, because it initially does report.. At any rate -- this happened at 6:29 PM, so if you see something in the log, please let me know.

it stucks on the watch itself? It never happened to me. Did you have low power enabled maybe?

**Comment by Holden74** [comment]
Awesome mate no rush merry Xmas

**Comment by RickNY** [comment]
> 
> it stucks on the watch itself? It never happened to me. Did you have low power enabled maybe?

It was stuck on the watch app this time - but opening the stock Apple Heart Rate app got it reading again.  I have seen other times where it was updating on the QZ watch app - but the changes werent showing in the iOS QZ app for a delay

**Comment by cagnulein** [comment]
@RickNY it sounds like a WatchOS bug, QZ just start the activity and a trigger is emitted from WatchOS to QZ every 2-3 seconds or so. Maybe the Watch can't find your HR anymore and opening the Heart Rate app reset the sensor. Let me know how it will go in the next days

Happy Xmas guys!

**Comment by RickNY** [comment]
Thanks Roberto - I hope you and your family have a very merry Xmas as well

**Comment by RickNY** [comment]
Looking a little further in to it, it does seem like the watch just stops measuring randomly - and some other people reported this on S8 with Watch OS 9

![hr_yest](https://user-images.githubusercontent.com/702933/209337193-7a6359d4-c7d1-4009-86c9-4d9401e52bec.jpg)

**Comment by cagnulein** [comment]
do you already updated to 9.2? I got mine S7 to 9.1 yet

**Comment by RickNY** [comment]
Yeah, Im on 9.2... Im just going through past workouts to see where I show a gap.. Wednesday was OK, Tuesday & Monday -- same gaps.. It does seem to occur around the same time -- around 5 minutes after the workout starts.  I cant see a whole lot more prior to Monday - but I cleaned the back of the watch this morning and for good measure, just did a unpair/re-pair to phone - so hopefully it will be better.

At this point - I def think this is a watch issue - not QZ.

**Comment by cagnulein** [comment]
@RickNY i checked my last 7 days workouts and i got a single hit using workoutdoors ![image](https://user-images.githubusercontent.com/48216/209338206-a5029c35-da45-410f-a7de-23da9c9b5986.png)

**Comment by cagnulein** [comment]
@Holden74 @RickNY sent the new version!

**Comment by Holden74** [comment]
Awesome will download

**Comment by RickNY** [comment]
So I tried this yesterday -- it worked pretty well.. Is it possible to add an option to de-couple the speed gain from the incline?  Changing the gain on one changes the same on the other as it is now - not sure if thats intentional.

**Comment by cagnulein** [comment]
Yeah i did in this way because for the bike there is only one difficulty metric. So ok I will add a different difficulty setting for the inclination ;)

**Comment by cagnulein** [comment]
done, i will send you it today or tomorrow

**Comment by cagnulein** [comment]
new version sent @RickNY @Holden74

**Comment by Holden74** [comment]
Awesome thanks mate

**Comment by RickNY** [comment]
I think I'm encountering an issue with this feature.. I'm noticing that if you increase the speed percentage by a specific number of clicks up, that clicking down does not get you where you would expect to be.  More importantly, I think -- the first time you try to go back down, it does not go down on the first attempt.  I could be wrong - its possible I didn't register the touch on the minus button?  Im attaching a log for what just happened to me here.  I started Peloton workout at 100%.  I then clicked up I think 3 times -- but the 3rd time, the speed jump was more than I expected - so I went down a step - however it did not lower the speed.  Additionally, reversing back the number of clicks down as I did up - did not return me to the speed it was at 100%.. In the end, I had to drop down below 100% and then click back up to 100% to get to the correct value.

Anyway - can you look at my log to see exactly what I did here?  Thanks
[debug-Thu_Dec_29_14_14_35_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10321264/debug-Thu_Dec_29_14_14_35_2022.log.txt)

**Comment by cagnulein** [comment]
i guess i didn't explain how it work. i'm adding a percentage to the current speed or the new speed. so if previously with the plus button you have

1 - 1.5 - 2.0

now you could have
1 - 1.62 - 2.12 for example (number are just to show you a difference from the classic case)

It's just a multiplier to the target speed or inclination. It affect peloton request but also the plus and minus button.

I don't think there is a possibility that i don't get a touch event, but also @victorypoint asks me to add a vibration feedback to the buttons.

**Comment by RickNY** [comment]
Ok thanks. Any reason each press is increasing 3% though?

**Comment by cagnulein** [comment]
@RickNY 3% it's a value that i choose :) 1% i guess it was too low. do you have any preference on this?

**Comment by Holden74** [comment]
Thanks for the explanation - would there be anyway to simplify this? Say just add .1 .2.3 etc mile per hour to speed across whole workout? And the same for incline set to a .5 1.0 etc increase across whole workout?

**Comment by cagnulein** [comment]
yes i can simple transform this from multipliers to offsets.
@RickNY what do you think?

**Comment by RickNY** [comment]
OK.. Take a look at this log.. I did this OFF the tread this time.. You can see the weirdness... This is what I observed.. The 0% gain (100%) speed was 3.0 MPH.  Changing it as follows did this:
100% - 3.0 MPH
+ 103% - 3.0 MPH
+ 106% - 3.1 MPH
+ 109% - 3.3 MPH
+ 112% - 3.6 MPH
- 109% - 3.8 MPH  (We are going up!)
- 106% - 4.0 MPH (Up again!)
- 103% - 4.1 MPH (And up again)
- 97% - 4.0 MPH (Starting to go down -- but remember our 100% was 3.0 MPH)
- 94% - 3.7 MPH  

I hope the formatting doesnt get all screwy


[debug-Thu_Dec_29_15_40_20_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10322017/debug-Thu_Dec_29_15_40_20_2022.log.txt)

**Comment by cagnulein** [comment]
@RickNY check my previous comment, maybe it will simplify everything?

**Comment by RickNY** [comment]
> @RickNY check my previous comment, maybe it will simplify everything?

Well, I think the multipliers is really the best way to do this -- I just think its applying the multiplier against the wrong t. speed somewhere.  To me -- it looks like the multiplier is being applied to our current speed - and not the Peloton's target speed for that difficulty level..

**Comment by cagnulein** [comment]
ok so i will check the log tomorrow, 10pm here and i'm completely burned out :) i counted more than 300 email about qz today :D

**Comment by RickNY** [comment]
I was going to say -- it seemed late for you!  Yes, yes - no hurry for this.. I will keep at 100% for now.

**Comment by Holden74** [comment]
All good mate no rush also - for me the average was a little too slow while the upper is a little fast - if I could set day the average .5mph to 1mph quicker across whole workout that would be easier then whatever the call-out used it would add this amount

**Comment by Holden74** [comment]
Atm when using the multiplier it's adding according to the current speed so it is different all the time depending on what speed is on at the time

**Comment by Holden74** [comment]
I guess both implementations are the same but for the average user it may be a little confusing in its current form

**Comment by cagnulein** [comment]
@RickNY i got the issue, it's just a simple math issue.
Everytime you're pushing the minus or plus target speed buttons, i'm also sending an event to change the speed with the current difficulty level.

Since the difficulty is higher than 100%, no matter if you're pressing plus or minus, the speed will be higher than it was :)

I'm fixing this :)

@holden74 i agree with @RickNY a multiplier on my mind is better than a offset. it's how, for example, zwift works for their difficulty. Maybe we can add a setting to set it as an offset instead.

But let's first fix this one and then we can think about this

**Comment by RickNY** [comment]
> @RickNY i got the issue, it's just a simple math issue. Everytime you're pushing the minus or plus target speed buttons, i'm also sending an event to change the speed with the current difficulty level.
> 
> Since the difficulty is higher than 100%, no matter if you're pressing plus or minus, the speed will be higher than it was :)
> 
> I'm fixing this :)

That makes sense!  Thanks.. LOL.. I wasn't quite ready to go that fast, and pressing down just made it go faster until it was below 100% again.

**Comment by cagnulein** [comment]
fixed :) i will send you the ios beta later

**Comment by cagnulein** [comment]
new version sent!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 30 dic 2022 alle ore 16:10 RickNY ***@***.***>
ha scritto:

**Comment by RickNY** [comment]
OK, I tried the updated version before.. Something seemed amiss -- trying to remember what my steps were, but I increased the T. Speed, then went negative to below 100% -- and then I think I went up again -- and while the percentages increased in QZ, the T. Speed did not increase.  I think I had gone as high as +18% with no results.  Anyway - I ended it there to generate the log for you.  Did another session with it left alone, which worked fine.  Below is the funky log

[debug-Fri_Dec_30_17_01_48_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10326541/debug-Fri_Dec_30_17_01_48_2022.log.txt)

**Comment by cagnulein** [comment]
@RickNY I got the problem, i'm trying to explain it in my bad english.

When you hit the target speed plus button, i'm incrementing the 3% the actual speed and sometimes it's not enough to give you a 0.1 miles increment, so the speed remains the same.
When you hit it again, and you expect a increase of 6%, since the speed wasn't changed last time, there is a math error because, the new speed is calculated on the "should be" speed instead of the real one.

Probably this is releated only to your treadmill but anyway I need to fix it somehow. I have to think how.

I thought that this mod would be easy, but it's starts to become a mess :D probably an offset as @Holden74 suggest will be easier to implement...but let's see if I will come to a solution

**Comment by Holden74** [comment]
Try the offset ha ha just have it so if we push the plus it increases the speed in .1mph increments for the duration of the workout eg if call out is 6.0 and we have .5 increment added our speed will be 6.5 when call-out is changed to say 7.0 our speed will be 7.5 and so on - simple ha ha

**Comment by cagnulein** [comment]
ok i guess I found a clean solution for this, I will send you another one today

**Comment by cagnulein** [comment]
new version sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 31 dic 2022 alle ore 08:37 Holden74 ***@***.***>
ha scritto:

**Comment by RickNY** [comment]
Thanks Roberto.. Ill try this in a bit, if it doesn't work as expected - maybe @Holden74 is right -- an absolute speed offset may be the best way to go, using the increments set for the treadmill - same with incline.

**Comment by Holden74** [comment]
Hey mate had a quick go seems to work better so awesome work! Still a little hard to get the correct speed increase would still be interested in just having a basic offset option to increase .1 .2 .3 etc across entire workout if possible

**Comment by cagnulein** [comment]
great @Holden74 ! maybe I can add a setting for this... @RickNY did you try it also?

**Comment by RickNY** [comment]
I did not get to try it yet, hurt my toe so resting a day or two.. I'll try to test it today without getting on the tread and let you know

**Comment by cagnulein** [comment]
argh @RickNY bad new year start! did you hurt yourself on the treadmill?

**Comment by RickNY** [comment]
Haha -- No, I didn't hurt it exercising at all

**Comment by RickNY** [comment]
OK, so I ended up having to take more days off than I'd like.. Finally started getting back into my normal routine.. I tried this once, and it seemed to be working well.. Were you planning on implementing the static offset that @Holden74 proposed, or has it been implemented yet?

**Comment by cagnulein** [comment]
@RickNY actually I was waiting for your feedbacks :) Maybe we should create a pool on the facebook group about this? Probably the 99% of the treadmill users don't know anything about this :)

**Comment by RickNY** [comment]
I'm not sure how much effort you should put into it.. For me, the percentage gain is sufficient.. For some reason I got this issue confused with a different one (I think it was one where a different user had asked that stats continue to be counted when paused) -- at any rate.. I'm happy with it in its current state

**Comment by cagnulein** [comment]
@Holden74 what do you think? are you still using this?

**Comment by RickNY** [comment]
OK, I do have a comment to add on this.. Using the percentage for the speed works quite well for me..  However -- for incline, I think an offset works better.  I experimented today with the incline, and noticed two issues -- first, the T. Incline changes to a value that doesn't jive with the "Inclination Step" setting for the tread.. So if you are at 0.5, pressing the plus sign takes it to 0.6, 0.7, etc -- all values that dont change the incline if your treat uses a 0.5 (mine) or 1.0 % incline step.  End result is you have to press multiple times if you are starting at a low incline - and I suspect it doesnt scale well once a callout is for higher incline values.

**Comment by cagnulein** [comment]
an easy fix for this would be instead of increasing of the 3% of each pressing, increase of 5% or more. but yes i understood your point. 

probably for incline is better an offset or adding a setting to choose for speed/incline multiplier/offset

i'm losing my mind with all these settings :D

**Comment by Holden74** [comment]
Yes I've been using it works fairly well i havnt actually played with the incline setting offset at all - for me I'd still just like a straight offset for both ha ha easier to get my head around it

**Comment by cagnulein** [comment]
@Holden74 @RickNY i'm adding this.
Check if you like the description of the setting

> Target Speed and Target Incline tile offer a way to increase/decrease the current difficulty with the plus/minus buttons. By default, with this setting disabled, the speed and the inclination change with a 3% gain for every pressure. Switching this ON, QZ will add a 0.1 speed offset or a 0.5 incline offset instead.

**Comment by cagnulein** [comment]
@RickNY  @Holden74 done, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Holden74** [comment]
Description is great awesome work - email sent 👏

**Comment by RickNY** [comment]
> @Holden74 @RickNY i'm adding this. Check if you like the description of the setting
> 
> > Target Speed and Target Incline tile offer a way to increase/decrease the current difficulty with the plus/minus buttons. By default, with this setting disabled, the speed and the inclination change with a 3% gain for every pressure. Switching this ON, QZ will add a 0.1 speed offset or a 0.5 incline offset instead.

Looks great
