### ISSUE TITLE
[BUG] echelon 3 metrics are not visible

### ISSUE THREAD

**Issue by divcurl0** [cagnulein/qdomyos-zwift#1093]
**Describe the bug**
When using QZ (on S22) with the Peloton app (on iPad), all the metrics on the QZ save for the HR (cadence, power, resistance, etc) show as 0 when they should not be (ie. when I am pedaling at a resistance). Please refer to the following screenshot:

![Screenshot_20221221_234100](https://user-images.githubusercontent.com/121197821/209029725-7fa9209d-099d-4758-9350-a9c34a58528a.jpg)

Furthermore, the cadence and HR are not displayed on the Peloton screen.

Interestingly, a little while ago, the problem was converse - all metrics *were* showing but the HR was not.

**Smartphone (please complete the following information):**
 - Device: S22 Ultra
 - OS: Android 13

**Append a debug log**

[temp_30585400448905.log](https://github.com/cagnulein/qdomyos-zwift/files/10282804/temp_30585400448905.log)

**Comment by cagnulein** [comment]
@divcurl0 which bike do you have? i don't see it in the log.
let me know

**Comment by divcurl0** [comment]
Hi,

It's the Echelon EX3

**Comment by cagnulein** [comment]
@divcurl0 founf your issue
You have enabled by mistake the "fake elliptical" setting in the experimental setting.
Disabled it and restart QZ
Let me know

**Comment by divcurl0** [comment]
Thanks. That worked! All the other metrics are working. But now, the HR isn't working. 

Two further issues have arisen:

-auto resistance doesn't seem to be working (the resistance does not automatically adjust during the workout as it should) 
-the cadence and resistance aren't showing on the Peloton screen 

Here is the newest debug log incase it helps:

[temp_40723766799373.log](https://github.com/cagnulein/qdomyos-zwift/files/10286443/temp_40723766799373.log)

Thanks in advance! Just bought you a few coffees for your ongoing support!

**Comment by cagnulein** [comment]
Hi thanks for the coffees!
I checked the log and the HR is not broadcasting anymore. Maybe it's already connected somewhere else? Or it still connected to the phone and it's not broadcasting anymore? Check in the bluetooth settings of your phone

For the auto resistance, in the log, i saw 3 resistance moves, resistance 8 to 9 to 14. Don't you see the movement of the resistance? the bike also confirms QZ about the resistance changed

Resistance can't be shown on the peloton screen. if peloton is running on ios you can pair hr and cadence. if peloton is running on android, only hr. also if qz is running on an android device with android 10 or above you can send only cadence or hr to peloton, not both.

Let me know

**Comment by divcurl0** [comment]
Thanks for getting back to me!

Regarding the HR belt, I think it is broadcasting. Refer to pic below:

![Screenshot_20221222_151752_nRF Connect](https://user-images.githubusercontent.com/121197821/209171705-ec692484-54e9-4cea-8a99-73c0b25b86e1.jpg)

The issue only persists when I use the QZ app on my S22 (with the Peloton app on an iPad) - when I switch to an iPhone, there are no issues (I can see all the metrics including HR). Really weird! 

Here is the most recent debug log in case this helps:

[temp_7315397444100.log](https://github.com/cagnulein/qdomyos-zwift/files/10288277/temp_7315397444100.log)

Regarding the auto resistance, the resistance didn't seem to be adjusting in sync with that of the instructor's, but I had my Peloton resistance set on the "low difficulty setting" which explains why - I think it's working okay now :)

Regarding what's shown on the screen - all noted. Thanks for clarifying.

**Comment by cagnulein** [comment]
@divcurl0 did you press scan on nrfconnect? otherwise it shows the cache instead of the actual devices. In the fresh log the HR is still not available :(
