### ISSUE TITLE
Kingsmith K15 Treadmill Connectivity Issue

### ISSUE THREAD

**Issue by haddadrm** [cagnulein/qdomyos-zwift#1096]
I'm trying to use the treadmill swift. I'm using: 
-Samsung Galaxy S10 plus
-Android 12
-One UI 4.1

Treadmill:
Kingsmith K15 with latest framework update.

The first time I ran the app it couldn't find the treadmill until I deleted the Mi Home profile for the app. Only then the App was able to find the the treadmills BT as "mi-mtk" but the app doesn't get a lock or show any Tiles. 

So I tried the 2 options for Kingsmith turned on on their own each and together without Manual Device, then again with Manual Device, but nothing happened. 

I also tried clearing App Data and started over again, still the same

TIA

**Comment by cagnulein** [comment]
@haddadrm thanks! Could you please attach also a nrfconnect screenshot about your treadmill?

FYI @d3m3vilurr

**Comment by haddadrm** [comment]
@cagnulein @d3m3vilurr 

Are the correct ones? let me know if not!
![Screenshot_20221227_151711_nRF Connect](https://user-images.githubusercontent.com/121486289/209659864-b210e35f-bc76-44dd-b2ce-103781ab00dc.jpg)
![Screenshot_20221227_151734_nRF Connect](https://user-images.githubusercontent.com/121486289/209659873-c442069e-461e-49c9-8bdc-ba2b7ed1f7eb.jpg)
![Screenshot_20221227_152128_nRF Connect](https://user-images.githubusercontent.com/121486289/209659879-f8867de0-cbbe-4566-84ef-f6235593324f.jpg)

**Comment by cagnulein** [comment]
@haddadrm yes they are right. it seems it has a completely different protocol than the other xiaomi treadmills.

could you please collect a hci snoof with the xiaomi app? following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by haddadrm** [comment]
@cagnulein 

That's misfortunate indeed! I hope it is a quick fix! The log below you asked for:

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10308382/btsnoop_hci.log)

**Comment by cagnulein** [comment]
maybe it's quick to fix. let me check it :)

**Comment by cagnulein** [comment]
@haddadrm did you use the xiaomi app during the hci snoof? I don't see any communication to the treadmill in the log

**Comment by haddadrm** [comment]
@cagnulein  Apologies, I might have forgotten to turn Mi Home app. But they have removed the controls from the app except for Start/Stop and the ability to customize the 3-speed buttons. 

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10309236/btsnoop_hci.log)
![Screenshot_20221227_185954_Mi Home](https://user-images.githubusercontent.com/121486289/209685852-2825898e-5864-4c0c-88c6-319e47e4e3d4.png)
![screenshot-2022-12-27-19-01-39-default](https://user-images.githubusercontent.com/121486289/209685854-9ccab944-b63f-4789-ab34-637b244f7599.png)
[btsnoop_hci.log.last.log](https://github.com/cagnulein/qdomyos-zwift/files/10309242/btsnoop_hci.log.last.log)

**Comment by cagnulein** [comment]
interesting...I saw the connection now but i don't see any metrics on bluetooth. Did you start a small workout? Because I'm thinking that the treadmill is working by wifi not by bluetooth

**Comment by haddadrm** [comment]
@cagnulein I did doa workout, changed the speed, started, stepped, and modified the settings in the app. But then I saw the network information, and I thought perhaps it was using WiFi. 

What's more interesting is that there appears to be a Bluetooth interface since the treadmill gets picked up in a BT scan on my laptop, on my phone, and also in qdomyos-zwift app.

I'll try and find an older Mi Home app, maybe this is something that was changed in the new app version!

**Comment by cagnulein** [comment]
@haddadrm ok let me know! here you can find some older version https://www.apkmirror.com/apk/xiaomi-inc/mihome/

**Comment by haddadrm** [comment]
@cagnulein I tried a ver 6 from 2017, and it still was WiFi.

**Comment by cagnulein** [comment]
@haddadrm ok so are you able to run the xiaomi app on android emulator on your pc and collect the wifi traffic via wireshark?

**Comment by haddadrm** [comment]
@cagnulein  Sure, I'll do that in the evening and get back to you. Thank you for the support, I appreciate it.

**Comment by haddadrm** [comment]
@cagnulein Sorry for the delay, but ran into issues with the android emulator!

I recaptured BT HCl; since I found out that the app required BT to locate the Treadmill when adding it as a device in the app.

I captured WiFi on my laptop! but without the emulator! the traffic should be decrypted but not sure if it is useful, I'm including it here anywhere.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10320810/btsnoop_hci.log)
[WireShark.zip](https://github.com/cagnulein/qdomyos-zwift/files/10320814/WireShark.zip)

**Comment by cagnulein** [comment]
@haddadrm thanks. which is the ip of your treadmill in the current session? Also how can you get the data from wireshark without using the same device to send commands? I'm confused
let me know

**Comment by cagnulein** [comment]
@haddadrm i don't see any traffic from/to 10.0.0.8 here
that's because you're not on the same device where you're sending data to the treadmill. that's why you need to use an emulator
Let me know

**Comment by haddadrm** [comment]
This is an example of the traffic to the treadmill!

![image](https://user-images.githubusercontent.com/121486289/209991844-25cb9343-c312-4556-8975-6e58148cbca9.png) 

I will try to resolve the emulator BT and emulator Network Name for the app to work.

**Comment by cagnulein** [comment]
they are only the ARP queries, not the real traffic itself. We need an emulator for sure. let me know!

**Comment by haddadrm** [comment]
@cagnulein So I tried a few emulators (Android Studio, Nox, Genymotion, VM Virtual Box), and the app kept crashing/failing to start on them.

Even if the app had worked, there is still the issue of the Wifi Network Name matching the WiFi network name used to register the Treadmill on the phone. the app saves the Network name and Password to the treadmill for future connection. Alternatively, re-initiating the treadmill on the emulator to make the WiFi name match would involve BT access for the app to find the treadmill at invitation, which would require an external USB BT device and some SDK tinkering to make it work in an emulator! I probably have a BT stick somewhere but it must be 15 years old!

So, I solved this by turning the laptop into a WiFi Hotspot, connected the Phone to the laptop WiFi Hotspot, and then re-initiated the treadmill in the Mi Home app on the phone. I used Wireshark on the laptop to capture the traffic of the Hotspot, which appears to have done the job (I can see DNS and TCP calls). I hope this is meaningful.

IP addresses of the devices:

![image](https://user-images.githubusercontent.com/121486289/210126857-0de52a82-b2a7-4ddf-af30-78a8fc96fd09.png)

Wireshark log:

[MiHomeCapture.zip](https://github.com/cagnulein/qdomyos-zwift/files/10326886/MiHomeCapture.zip)

**Comment by cagnulein** [comment]
@haddadrm ok this is a step forward! I can see now the logs from/to the treadmill but they are using a https web server, so the traffic is encrypted.

@d3m3vilurr @p3g4asus are you aware of some easy ways to decrypt https traffic from wireshark? I never did this before

**Comment by cagnulein** [comment]
@haddadrm ok this is a step forward! I can see now the logs from/to the treadmill but they are using a https web server, so the traffic is encrypted.

@d3m3vilurr @p3g4asus are you aware of some easy ways to decrypt https traffic from wireshark? I never did this before

**Comment by p3g4asus** [comment]
> @haddadrm ok this is a step forward! I can see now the logs from/to the treadmill but they are using a https web server, so the traffic is encrypted.
> 
> @d3m3vilurr @p3g4asus are you aware of some easy ways to decrypt https traffic from wireshark? I never did this before

I have no experience either but I don't think it's possible. I will think about something but for sure if the treadmill refuses to connect if there are certificate errors (as it should and probably does) there is absolutely nothing that can be done.

**Comment by cagnulein** [comment]
@p3g4asus even using a man in the middle like a proxy?

**Comment by p3g4asus** [comment]
> @p3g4asus even using a man in the middle like a proxy?

If the https client in the treadmill is configured to avoid connecting if there are certificate errors, even the proxy is impossible I think.

**Comment by cagnulein** [comment]
thanks @p3g4asus happy new year also!

@haddadrm maybe another approach: does the tablet have android? are you able to install app on it?

**Comment by haddadrm** [comment]
@cagnulein Yes it's android, and I can install apps with no issues. Does the app need root access?

**Comment by cagnulein** [comment]
@haddadrm my idea is to create an apk for your treadmill that can act as a companion for qz on the phone or directly qz installed on the treadmill. we need first to understand if there are some files inside the tablet that the qz companion can read.

for example are you able to share some log from the tablet itself? we are looking for logs where the app can trace the speed and inclination changes 

Let me know

**Comment by haddadrm** [comment]
@cagnulein, can you tell me the path or folder at which I should be looking for the logs?

**Comment by cagnulein** [comment]
@haddadrm i don't know :) i mean it's just an idea so i can't tell you where we can find the logs. if you want anyway, you can create a bug report from the treadmill itself and you can try to upload it here so we can have an overview of how the treadmill is did

**Comment by haddadrm** [comment]
@cagnulein I'll give it a try and get back to you. I feel this is beyond my technical skills tbh :) 
Happy New Year

**Comment by cagnulein** [comment]
@haddadrm let's do this together step by step when you will have time!

happy new year!
