### ISSUE TITLE
Rouvy Compatibility for Android below version 10

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1098]
@jra650 ok i got the issue. Rouvy did a very poor implementation of the FTMS protocol. They are reading only speed from it. Instead for cadence, hr and power they want separate characteristic over bluetooth.
I can do it for android, but only if you have an android below version 10. Is it your case?

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/issues/1085#issuecomment-1366026614_

**Comment by jra650** [comment]
OK Thanks.  Turning on "Run Cadence Sensor" does not help with the qz connection to Zwift (or of course Rouvy).  Right now I can only test the footpod on the Note 20 which is running Android 13.  I have both a Zwift and Garmin Ant+ footpod.  However only the Zwift will connect to qz on the Note 20 (which has a weird limited implementation of ANT+)

heres a debug from the Note 20 trying to connect to Zwift

[debug-Tue_Dec_27_11_53_47_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10309720/debug-Tue_Dec_27_11_53_47_2022.log)

**Comment by cagnulein** [comment]
run cadence sensor was only for Rouvy, to zwift it should run with the standard settings @jra650 
The standard ones doesn't allow you to connect to zwift?
Yes garmin ant+ footpod is not implemented in QZ

**Comment by jra650** [comment]
OK Heres a debug log with Run Cadence Sensor off.  Still no footpod connection to Zwift

[debug-Tue_Dec_27_12_24_00_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10309827/debug-Tue_Dec_27_12_24_00_2022.log)

**Comment by cagnulein** [comment]
> OK Heres a debug log with Run Cadence Sensor off. Still no footpod connection to Zwift
> 
> [debug-Tue_Dec_27_12_24_00_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10309827/debug-Tue_Dec_27_12_24_00_2022.log)

got the issue, you have the "virtual device" setting disabled in the experimental setting. You need to enable it and restart QZ
let me know

**Comment by cagnulein** [comment]
ios to ios is working without doing anything 

![image](https://user-images.githubusercontent.com/48216/209704492-12955e3d-7410-47fe-a1d6-60870f31230f.png)

so i have to try to run qz on android

**Comment by jra650** [comment]
OK with Virtual device on, qz with the footpod connects to Zwift, but turning Run Cadence Sensor back on still does not make a connection to Rouvy. In fact in Rouvy 'run mode' I dont see any available sensors at all.  (This is with the Note 20).  So I may have to wait for a version of the beta that wont crash when the Computrainer is not attached so I can try the footpod off my Note 8.

Should the Virtual Device setting be on for the Computrainer version too?  (Note the Computrainer connected to the Windows laptop will connect to Rouvy no problem with the two Ant+ dongles attached to rebroadcast the Computrainer signal).

Debugs from the Note 20
[debug-Tue_Dec_27_13_31_51_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10310170/debug-Tue_Dec_27_13_31_51_2022.log)
[debug-Tue_Dec_27_13_32_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10310171/debug-Tue_Dec_27_13_32_25_2022.log)

**Comment by cagnulein** [comment]
> OK with Virtual device on, qz with the footpod connects to Zwift, 

ok

> but turning Run Cadence Sensor back on still does not make a connection to Rouvy. 

did you try both way? i mean with and without the run cadence sensor?

> In fact in Rouvy 'run mode' I dont see any available sensors at all.  (This is with the Note 20).  

i will try also this tomorrow on android 

> So I may have to wait for a version of the beta that wont crash when the Computrainer is not attached so I can try the footpod off my Note 8.

oh right I forgot about this. You can try this already clearing the data of the qz app

> Should the Virtual Device setting be on for the Computrainer version too?  

yes, this setting enables the bridge to any 3rd party app

> (Note the Computrainer connected to the Windows laptop will connect to Rouvy no problem with the two Ant+ dongles attached to rebroadcast the Computrainer signal).

so using ant+. probably rouvy has a poor bluetooth implementation. anyway since it's working on ios it must work also on android. i will check tomorrow

**Comment by jra650** [comment]
OK Thanks.  I did try to connect the footpod to Rouvy with and without Run Cadence Sensor on, no devices show in Rouvy.  Virtual Device is on.

I was not able to test the footpod with the Note 8.  I have to have the Computrainer plugged into the Note 8 to keep qz open.  Hitting the Clear Data button, closing qz and unplugging the USB cable still prevents qz from staying open (an immediate crash when opened).

And yes, the laptop connection is through Ant+.  One of the frustrations with the laptop FEC bridge is that its ANT+ only so it requires 2 Ant+ dongles... it literally requires the signal to be sent and received by the same software!

**Comment by cagnulein** [comment]
> OK Thanks.  I did try to connect the footpod to Rouvy with and without Run Cadence Sensor on, no devices show in Rouvy.  Virtual Device is on.

Ok

> I was not able to test the footpod with the Note 8.  I have to have the Computrainer plugged into the Note 8 to keep qz open.  Hitting the Clear Data button, closing qz and unplugging the USB cable still prevents qz from staying open (an immediate crash when opened).

Ok tomorrow I will fix this

> And yes, the laptop connection is through Ant+.  One of the frustrations with the laptop FEC bridge is that its ANT+ only so it requires 2 Ant+ dongles... it literally requires the signal to be sent and received by the same software!

LoL

**Comment by cagnulein** [comment]
@jra650 it's working on my android in this way

setup: qz on android and rouvy on ios. if i click on the smart trainer directly i have your issue too, but if i'm using this flow it works. i guess it's a bug of rouvy

let me know 

https://user-images.githubusercontent.com/48216/209799404-55d51785-0baa-49f6-8b89-3f0c445c78c4.MOV

**Comment by cagnulein** [comment]
also tested on the same setup the running cadence sensor and it works

same setup as above

 ![image](https://user-images.githubusercontent.com/48216/209800423-7c3b55e1-1e5a-4970-9839-c10aa412c889.png)

**Comment by cagnulein** [comment]
so i guess the issue is about your android device. it should work with the s8. i will send you the version that doesn't crash without the computrainer

**Comment by jra650** [comment]
The issue is definitely between Rouvy and the samsung phones.  What type of Android device are you using?  I tried between both Samsung phones and a Windows 10 laptop using BLE and had a similar issue as I did with Rouvy running on a Samsung tablet.  Also Wahoo Fitness on the Samsung tablet also sees the sensors from the Note 8

Zwift on the laptop connects quickly to both Samsung phones (Note 8 or Note 20)  Per images below, Rouvy sees multiple phone sensors but wont connect (indicating its not the right kind of device). 

Is there some BLE sniffer device I could run on the laptop or the Android tablet??

![qz Rouvy sensors#2](https://user-images.githubusercontent.com/83240285/209839600-86d3a524-fa7b-4854-8ee3-b7f559c63791.png)
![qz Rouvy sensors](https://user-images.githubusercontent.com/83240285/209839605-99805679-2605-453b-8a95-d96099bafd1c.png)

**Comment by jra650** [comment]
Also the last update seems to have broken the Computrainer connection... I am no longer getting lights on the FTDI cable.  Do I need to clear all the qz data and start over with this version?

**Comment by cagnulein** [comment]
@jra650 samsung A40 :)
are you following the pattern that I show you in the video?

about the Computrainer no, I mean I just added an if case to check if the port is open. Try to clear the data and let me know

**Comment by jra650** [comment]
On patterns - Yes as far as I can tell... I'm starting with the heart rate sensor.  One other point is that if I'm wearing a HR sensor (BLE for the Note 20 or Ant+ for the Note 8) qz does not show HR.  

Clearing the data fixed the Computrainer issue on the Note 8 and now the Note 8 can also read the Zwift Foot Pod.  However, while the Wahoo Fitness app on the Samsung Tab can see the sensors on the Note 8 (shows as HR only) no data seems to be passed.  I tried a 'wahoo kicker' profile in the Wahoo Fitness app with the Computrainer connected to the Note 8 and qz data showing on the Note 8 screen, but nothing shows in the Wahoo fitness app.  So not sure its just Rouvy that has the issue.  

Was your ios device an iPad or Mac?  I can probably test on an iPad.

**Comment by cagnulein** [comment]
@jra650 so the computrainer is now working again?

> Was your ios device an iPad or Mac? I can probably test on an iPad.

iphone actually, but i don't think it matters

> On patterns - Yes as far as I can tell... I'm starting with the heart rate sensor. One other point is that if I'm wearing a HR sensor (BLE for the Note 20 or Ant+ for the Note 8) qz does not show HR.

are you able to select QZ device as  HR in rouvy even if you're seeing 0? I mean do exactly the step that I did in the video. Maybe can you create a video too? SO we can compare them

> I tried a 'wahoo kicker' profile in the Wahoo Fitness app with the Computrainer connected to the Note 8 and qz data showing on the Note 8 screen

you need also to enable the wahoo rgt compatibility setting in QZ (experimental setting) to use the Wahoo app

**Comment by jra650** [comment]
Yes the Computrainer is working again but no I cannot select the Note 8 (named Waho) in Rouvy as just HR.  It never connects, and per the earlier picture (without even selecting 'Show All Devices' in Rouvy, 6 versions of Waho come up... none connect.

I will try the Wahoo Fitness app later, but maybe thats not helpful.  I think what would be most useful is to run a sniffer for BLE on the Samsung Tablet or on the Windows laptop.  Is that even possible?

**Comment by cagnulein** [comment]
> It never connects, and per the earlier picture (without even selecting 'Show All Devices' in Rouvy, 6 versions of Waho come up... none connect.

it does only when running cadence sensor is disabled. Did you disabled it?

> I will try the Wahoo Fitness app later, but maybe thats not helpful. I think what would be most useful is to run a sniffer for BLE on the Samsung Tablet or on the Windows laptop. Is that even possible?

yes you can try to find a bluetooth scanner on windows, also maybe a rouvy log it could be useful?

**Comment by jra650** [comment]
How do I get a Rouvy log?? And when you say 'cadence sensor is disabled' do you mean the Run Cadence Sensor in qz or do you mean having the cadence selector 'disconnected' in Rouvy?  ( I would have to say I've tried it both ways at this point.  Certainly on the Note 8 the Run Cadence Sensor setting was never on until I tried to use the Note 8 to connect the footpod earlier today.)

Also the Wahoo RGT setting made no difference (at least with the footpod) in Wahoo Fitness on the Samsung Tab

**Comment by jra650** [comment]
I found this 
[rouvy.log](https://github.com/cagnulein/qdomyos-zwift/files/10315761/rouvy.log)

**Comment by cagnulein** [comment]
> And when you say 'cadence sensor is disabled' do you mean the Run Cadence Sensor in qz or do you mean having the cadence selector 'disconnected' in Rouvy?

i mean run cadence sensor.

**Comment by cagnulein** [comment]
> I found this [rouvy.log](https://github.com/cagnulein/qdomyos-zwift/files/10315761/rouvy.log)

the log is full of "unable to connect to the device" so yes a scanner on the same device where you are running rouvy will be useful.

But a scanner is useless if it's working with zwift, because if zwift works means that the BLE part is ok.

**Comment by jra650** [comment]
I am not sure there is any useful info in the sniffer file... it appeared to capture data, but the export method was not clear at all.  it saved a json file which is not the format I expected (this was on the Android tablet).  

I also tried Rouvy on an iphone.  Rouvy's behavior on the iPhone for the Computrainer data was identical to Rouvy on the Android tab.  It sees the Note 8 as a sensor but cant connect to it.  Rouvy on the iPhone did better with the footpod off the Note 20... it connected and worked.  So maybe the data change you made for the older version of Android did not work relative to the iPhone??

I want to do more testing of bike sensors on the Note 20 in the morning to see if they will connect to Rouvy through the Note 20.  qz on the Note 20 'sees' the sensors, but I dont get tiles so am confused by that...


[all.zip](https://github.com/cagnulein/qdomyos-zwift/files/10317052/all.zip)

**Comment by cagnulein** [comment]
> Rouvy's behavior on the iPhone for the Computrainer data was identical to Rouvy on the Android tab.

from the iphone can you make a screenshot about what nrfconnect shows about qz device (when qz is connected to the computrainer of course)? I mean your setup is the same of mine so it must works.

Also please share a video of what you're doing in this setup so we can compare with mine.



> So maybe the data change you made for the older version of Android did not work relative to the iPhone??

no i don't think so, there is no differences. Anyway nrfconnect will tell us the truth



> Will qz work with just a speed sensor?

run or cycling? qz can virtualize both. run cadence sensor for the run one, and "peloton cadence sensor" for the bike one. enabling one of these will shut down the ftms frames anyway. so be careful.

Let me know

**Comment by jra650** [comment]
OK Progress!  With the updated full version of qz I was able to get the Computrainer working on the Note 20 and connecting to Rouvy!!  So I guess it wasnt the thing with the old version of Android.  I will try to install the regular version of qz on the Note 8 in the morning and will see if it works from there too.  All the parameter settings still confuse me a bit but I'm trying to do profiles for Zwift and Rouvy etc to keep everything straight.

**Comment by jra650** [comment]
What are the differences between versions 2.12.29 and 2.12.30?  I can only load the older 2.11.xx or 2.12.30 on the Samsung Note 8.  Is this due to the older version of Android on the Note 8?  I still cant get Rouvy to connect to the Note 8 and tried to test the PowerTap wheel on the Note 8 but could only get tiles, no power or speed.  As far as I can tell I have 2.12.30 configured the same way as 2.12.29 which is on the Note 20 (where the PowerTap wheel is working (Bluetooth was off on the Note 20 when I was trying to make the Note 8 connection).  

What would be causing the difference in behavior?  And is there a way to export the PowerTap profile from 2.12.29 and import it into 2.12.30??

This is the log from the Note 8 trying to connect to the PowerTap wheel.

[debug-Thu_Dec_29_11_40_24_2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/10320596/debug-Thu_Dec_29_11_40_24_2022.zip)

**Comment by cagnulein** [comment]
no differences on your side. The fact that you can't load the newer version it's because the 2.12 is on beta, maybe you are not using the same google play account on both devices?

**Comment by jra650** [comment]
Yes I am using 2 different Play accounts so I could keep the beta separate from the regular version.  But when I deleted the beta from the Note 8, switched Play account (to the one used on the Note 20) and tried to download the non-beta I got 2.11.xx.  So the Computrainer wasnt there.  But the PowerTap didnt seem to work either.  Is 2.12.30 a beta as well??

**Comment by cagnulein** [comment]
the last stable version is the 2.11.x
So all the 2.12 are beta.
What is the powertap?

**Comment by jra650** [comment]
The PowerTap is an old Sarris power meter wheel.  It can do power, cadence, and speed but its obviously not controllable.  I was testing 2.12.30 on the Note 20 when I first got Rouvy to recognize power and cadence from qz.  I thought that this very simple test would be a good connection test for Rouvy.  Rouvy required that I first connect cadence.  When cadence connects, HR and Controllable are also connected.  And then I have to connect as a power source.  These connections do not re-establish if I close and re-open Rouvy (even though they are saved in Rouvy).  But they work on the Note 20.  Not on the Note 8... I'm trying to figure out why.

On the Note 20 I have:
-  Bike Options: Speed Calculates on Power on
- Advanced Settings: Manual Device: powertap hub
- Accessories: Power Sensor as Bike on
- Experimental: Enable Virtual Device
- Experimental: Virtual Device Bluetooth
- Experimental: Zwift Force Resistance
- Experimental: Android Wakelock
- Experimental: Debug Log


Does that look correct??   Should I do anything different on 2.12.29 on the Note 8??

**Comment by cagnulein** [comment]
They are all correct. And no you don't need to do anything different.
Do you see the tiles for the powertap at least? and also the metrics?

**Comment by jra650** [comment]
No metrics with these settings on the Note 8.  qz says PowerTap found, then the bluetooth symbol goes solid blue, but the text below just says connecting.  So something is different with the Note 8.  Maybe its an older BLE radio standard or something.  But I dont think the Computrainer broadcast will work if the PowerTap doesnt work.  Not even Zwift sees the Note 8 with this setup.

**Comment by cagnulein** [comment]
in this log https://github.com/cagnulein/qdomyos-zwift/files/10320596/debug-Thu_Dec_29_11_40_24_2022.zip the problem is that you have set the computrainer usb setting. When i find this settings filled, i'm giving the priority to this one, avoiding the power tap. Clear the setting and press ok and restart qz and it should work

**Comment by jra650** [comment]
At this point, I'd take getting a footpod from the Note 20 to connect to Rouvy.  I'm getting Rouvy to recognize qz as a HR, but get an 'cant connect as a speed sensor' error  when I try and additional connection.  I have tried with Run Cadence Sensor on and off.  I got the HR connection with this setting OFF.

![Rouvy Footpod  1](https://user-images.githubusercontent.com/83240285/210003206-3934e4c9-9881-4a64-a612-417f76b92182.png)
![Rouvy Footpod 2](https://user-images.githubusercontent.com/83240285/210003224-4e1817b5-354d-46a0-9206-5d05b090ab7f.png)

**Comment by jra650** [comment]
OK on the Computrainer... will test the PowerTap again later today.  And I think I have the Zwift Footpod working on the Note 20 with Rouvy... not sure exactly how but saved the profile.

**Comment by jra650** [comment]
Any final thoughts on making this work from the Note 8?  If not this can be closed.  Thanks!!

**Comment by cagnulein** [comment]
some android device are not compatible due to their bluetooth stack, so i guess we can close this. thanks!
Let me know if you need anything else! It was a pleasure to work with you!

**Comment by jra650** [comment]
Hi - I'm still looking for options to get away from using my main phone (the Note 20) for qz and am wondering what you thinks would be the minimum specs for an Android phone to connect the Computrainer to Rouvy?  I'm looking at a used Samsung S9 that probably has Android 10.

I have access to an Amazon Fire HD 8 Tablet that can run qz (after i installed Google Play) and can read the Computrainer but can not be seen by Rouvy other than as a cadence sensor.  Ironically this Fire Tablet can run Rouvy and see qz from the Samsung S6 Lite Tablet... BUT the Samsung S6 cant read the Computrainer because it has some weird USB restrictions.  So I'm still stuck.

Overall qz from my main phone (the Note 20) to the Samsung S6 Lite tablet has worked well (although not as good as with Zwift).  I have experienced some qz crashes while using Rouvy and if I'm in the middle of a Rouvy ride (say on a steep slope) and have to restart qz, (and reconnecting qz to Rouvy once Rouvy has experienced a disconnection is time consuming and hard) qz can get 'stuck' on the steep slope that is reported once it engages with Rouvy.  Sometimes toggling the resistance icon off and on fixes this but other times it has not seemed to.  

I realize you said Rouvy had a weak implementation of FTMS but wanted to know if you thought there could be any improvements?

**Comment by cagnulein** [comment]
> I have experienced some qz crashes while using Rouvy and if I'm in the middle of a Rouvy ride (say on a steep slope) and have to restart qz, (and reconnecting qz to Rouvy once Rouvy has experienced a disconnection is time consuming and hard) qz can get 'stuck' on the steep slope that is reported once it engages with Rouvy. Sometimes toggling the resistance icon off and on fixes this but other times it has not seemed to.

please send me a debug log about this, crashes must never happen!





> Hi - I'm still looking for options to get away from using my main phone (the Note 20) for qz and am wondering what you thinks would be the minimum specs for an Android phone to connect the Computrainer to Rouvy? I'm looking at a used Samsung S9 that probably has Android 10.

i was using a samsung a40 for the tests (very cheap) and it worked perfectly. let me know

**Comment by cagnulein** [comment]
ok thanks!

**Comment by jra650** [comment]
When you have a chance, please let me know how to configure qz for just a speed sensor (and/or a speed cadence sensor) to be used as a bike.  The Rouvy crashes happen after 30-50 minutes of use so I want to see if I can simulate the conditions in a test environment.  Although the crashes may be related to the Computrainer, I want to see if I can get a crash with another sensor and I can simulate long sessions if I can get just speed to work.

I have a speed sensor that the android device recognizes (shows speed in Wahoo Fitness) and qz recognizes the sensor and connects to (I get tiles and the bluetooth symbol is solid) but no speed shows in the tiles.

[debug-Mon_Jan_9_16_34_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10377120/debug-Mon_Jan_9_16_34_16_2023.log)

**Comment by cagnulein** [comment]
@jra650 i'm going to bed now i will answer you tomorrow. anyway i guess the debug log is not from the crash, it's too small. don't you have others one from today?

**Comment by jra650** [comment]
Ok yes I did not anticipate a response today.  And sorry I didn't specify
that the debug file was from the Fire tablet.  I am just using that device
to try to figure out the configuration for the speed sensor.

**Comment by cagnulein** [comment]
@jra650 anyway the log file is truncated, i can only see the last part so i can't see the settings. Anyway for the speed sensor just enable the peloton cadence sensor setting and you're good to go. Let me know

**Comment by jra650** [comment]
This current debug file is now from the Note20 which we know usually works.  The Peloton Cadence sensor setting is on.  The Xoss is the speed sensor.  Wahoo and Rouvy can see the Xoss as a speed sensor when they are running so I know it works.  But no speed is shown in qz. 

Am I missing some other setting?

[debug-Tue_Jan_10_10_42_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10384406/debug-Tue_Jan_10_10_42_48_2023.log)

**Comment by cagnulein** [comment]
@jra650 you need also to enable the "cadence sensor as a bike" setting.

**Comment by jra650** [comment]
no difference in qz with that setting on...

[debug-Tue_Jan_10_11_06_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10384574/debug-Tue_Jan_10_11_06_20_2023.log)

**Comment by cagnulein** [comment]
now your cadence sensor setting is set to Wahoo CADENCE C3DF
you have to change it if you want to use the XOSS to XOSS :)

**Comment by jra650** [comment]
OK Thanks - Now I'm getting tiles and speed and cadence in qz.  But Rouvy wont recognize the qz output as speed.  Rouvy connects to the qz output for cadence but nothing else.  Zwift will connect as speed and cadence.  So no testing of Rouvy is possible this way after all.

**Comment by cagnulein** [comment]
speed is derived from the cadence accordingly to the bluetooth standards https://github.com/oesmith/gatt-xml/blob/master/org.bluetooth.service.cycling_speed_and_cadence.xml if we don't use FTMS (since we enable the peloton cadence sensor setting). So I don't know why Rouvy complains about this
