### ISSUE TITLE
[BUG] Zwift RunPod OE run cadence does not match strava

### ISSUE THREAD

**Issue by brianjvolz** [cagnulein/qdomyos-zwift#1099]
**Describe the bug**
Zwift RunPod OE does cadence does not match strava SPM for tracking steps on treadmill. In the app currently, I have two options:
1: I can disable "doubling cadence for run" and this will report the correct SPM to strava, but display half the step count on the cadence tile in the app as I run. 
2: enable  "doubling cadence for run" and this will report the double the SPM to strava, but display the correct step count on the cadence tile in the app as I run. 

https://us.zwift.com/products/zwift-runpod?variant=42524430532864

**To Reproduce**
1. Add "Zwift RunPod OE as a power sensor 
2. select either "doubling cadence for run" disable or enable.
3. get error.

**Expected behavior**
I guess I would propose removing the "doubling cadence for run" option and adding two options in its place.
 "doubling cadence displayed in tile" and "doubling cadence reported to strava"

**Screenshots**
example of strava run with "doubling cadence for run" enabled.
https://www.strava.com/activities/8294370015

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ios
 - Version [e.g. 22] 2.11.95

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone se 3
 - OS: [e.g. iOS8.1]  16.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Yes sure @brianjvolz 
I will do your solution tomorrow!
Thanks for the feedback

**Comment by cagnulein** [comment]
@brianjvolz 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
