### ISSUE TITLE
TDF2 incline not working

### ISSUE THREAD

**Issue by cmorton57** [cagnulein/qdomyos-zwift#1101]
>  
[debug-Thu_Dec_29_17_01_32_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10320720/debug-Thu_Dec_29_17_01_32_2022.log)
[debug-Thu_Dec_29_17_02_16_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10320721/debug-Thu_Dec_29_17_02_16_2022.log)
[debug-Thu_Dec_29_17_12_56_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10320722/debug-Thu_Dec_29_17_12_56_2022.log)
**Describe` the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@cmorton57 logs are fine, so i guess tdf2 is working in a different way about the inclination.
Are you tech savvy? Could you please try to do a thing?
With qz closed, install the https://chrome.google.com/webstore/detail/web-socket-client/lifhekgaodigcpmnakfhaaaboididbdn?hl=it and in the address put

ws://YOURBIKEIP/control

so for example

ws://192.168.0.34/control

and then in the message box where you can send frames try to send

{"type":"set","values":{"Incline":"8.5"}}

or 

{"type":"set","values":{"Incline":"8.50"}}

or

{"type":"set","values":{"Resistance":"9"}}

let me know if one of these changes something on your bike

Let me know!

**Comment by cmorton57** [comment]
Hi,

 

Installed an tried all 3 – no response from the bike.

 

I did press the inclidne setting on the bike (hence the 3 “remote” entries

**Comment by cagnulein** [comment]
@cmorton57 did you see at least the metrics coming through in the websocket?

**Comment by cmorton57** [comment]
Hi, Yes see the image Sent from my iPhoneOn 29 Dec 2022, at 18:44, Roberto Viola ***@***.***> wrote:﻿
@cmorton57 did you see at least the metrics coming through in the websocket?

**Comment by cagnulein** [comment]
hi @cmorton57  i was checking your image, maybe we need to put whitespaces, for example

{ "type": "set" , "values" : { "Incline" : "8.5" } }

or

{ "type": "set" , "values" : { "Incline" : "8.50" } }

or

{ "type": "set" , "values" : { "Incline" : 8.50 } }

or

{ "values" : { "Incline" : "8.50" } }

or

{ "type": "set" , "values" : { "Resistance" : "10" } }

**Comment by cmorton57** [comment]
Hi

 

That diddnt work but I think I have solved it.

 

This is the command

 

{"type": "set", "values": { "Incline": "0.00", "Master State": "4"}}

 

Connecting to the bike it starts in master state “3”, but by changing to to master state 4 it seems to work

 

So you can 

 

{"type": "set", "values": { "Master State": "4"}}

 

Then use

 

{"type": "set", "values": { "Incline": "x.xx" }}

 

Or 

 

{"type": "set", "values": { "Incline": x.xx", "Master State": "4"}}

 

Both seem to work

 

-          Have no idea what master state means but it seems to work !

 

Regards

 

Chris

**Comment by cagnulein** [comment]
wow thanks! i will implement this tomorrow!

**Comment by cmorton57** [comment]
Just to clarify,

 

The bike has a bit of a wobbly if you set it to master state 4 then start your app as it just gives a disconnect message. And wont work

 

You need the bike in master state 3 (I think it starts like this - manual workout mode)

 

Once you are all hooked up on your app and rouvy  is all connected, - (so incline not working), whilst in the ride, open web socket and change to master state 4 then all works fine

 

Regards

 

Chris

**Comment by cagnulein** [comment]
hah ok so i can send master to 4 when i'm receiving the first inclination request from zwift. got it

**Comment by cagnulein** [comment]
done @cmorton57 i will send you the new beta today! Thanks!

**Comment by cmorton57** [comment]
Awesome, thank you will give it a go and let you know how I get on Sent from my iPhoneOn 30 Dec 2022, at 10:43, Roberto Viola ***@***.***> wrote:﻿
done @cmorton57 i will send you the new beta today! Thanks!

**Comment by cagnulein** [comment]
> Thanks for that,
> 
> So had the same issue to begin with so went back to web socket to try a few things.
> 
> It seems to work ok when you start up the bike and connect you have to press “quick start” this starts an excerise routine.
> 
> All works fine after that. 
> 
> If you start any other routine or pedal before pressing “quick start” master state 4 fails.
> 
> I have looked at web socket and can’t see any status change by pressing “quick start”, however it worked twice tonight (will test again tomorrow)
> 
> The only other problem is that now the app only sends master status 4 once, so if you finish a ride then start another the incline stops, so you have to quit out the app and restart again. 
> 
> I will try a few times again over the weekend but it maybe that the last version (with the continual send of status 4 might actually be better) - I can check this with web socket by hitting status 4 all the time to see
> 
> Keep you updated

**Comment by cagnulein** [comment]
> HI Roberto,
> 
>  
> 
> Done a load of testing today and have this worked out
> 
>  
> 
> The procedure works on both Rouvy and zwift. You have to switch on the bike, connect and the before pedalling or anything press quick start. Once in this manual mode the master state 4 code works fine – you can also keep sending master state 4 with no ill effect, this allows the user to end the ride and restart another ride as long as they hit “quick start” on the bike
> 
>  
> 
> If you start the bike or pedal 1st – when you send master state 4, the incline works but the other elements (speed etc) stop and the bike makes a bleeping noise.
> 
>  
> 
> To over come this the user has to press “home” to end the ride and “quick Start” – Master code 4 needs to be sent again to reactivate incline (your old flow will sort this).
> 
>  
> 
> The only code sent from the bike when pressing “quick start” is this……
> 
>  
> 
> {"type": "set", "values": {"MPH": "1.20", "KPH": "2.00"}}
> 
>  
> 
> However this also seems to be sent when starting a ride all ways, with this in mind I set the error (started a work out without “quick start” and sent master state 4) whilst the error was occurring sent
> 
>  
> 
> {"type": "set", "values": {"MPH": "1.20", "KPH": "2.00"}}
> 
>  
> 
> Then
> 
>  
> 
> {"type": "set", "values": { "Master State": "4"}}
> 
>  
> 
> This seems to fix the error (sometimes I had to send the 1st line twice) and all is good again,  I guess the only problem for you is knowing when the error occurs to send the remedy code. Im not sure if the 1st line has any effect on the ride stats as I guess you could send this anyway on the 1st incline before master status 4 to ensure it all works but not really been able to test if this will work every time. And like I said occasionally I had to send this twice for it to work.
> 
>  
> 
> I would think that ensuring the user starts in “quick start” mode and using the old flow (with Master state 4 all the time) will work, if the bike errors the user exits and presses quick start and all should be good again!
> 
>  
> 
> Happy to test out the last flow version if needed (or if you could send it anyway so I can ride in the meantime J
> 
>  
> 
> Works for me – this is amazing – got my bike back working again !!!!!!!
> 
>  
> 
> Thanks again
> 
>  
> 
> Chris
