### ISSUE TITLE
Tread Bootcamp only sends Partial Time remaining

### ISSUE THREAD

**Issue by gadi247** [cagnulein/qdomyos-zwift#1103]
When you do a Tread Bootcamp - say a 45 minute class -  it STARTS with 22.30 time remaining. On a 30 minute class, it shows about 16 minutes - so the class ends early in QZ
[debug-Wed_Dec_21_10_00_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10322845/debug-Wed_Dec_21_10_00_08_2022.log)

**Comment by cagnulein** [comment]
got it, i'm fixing it! thanks @gadi247 for sharing this!

**Comment by cagnulein** [comment]
Done! send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
