### ISSUE TITLE
[REQ] Floating Window - default to active

### ISSUE THREAD

**Issue by aaciii** [cagnulein/qdomyos-zwift#1105]
Many users will want to use the Floating Window "every time" - would be smoother for user if they can select to enable it by default vs having to first launch QZ, then turn on the floating window (and then position the window).

If the floating window came up automatically and in the right location on screen - then the user simply starts QZ and all is ready for them.

**Comment by cagnulein** [comment]
done also this! added a new setting in the general ui settings
