### ISSUE TITLE
[BUG] Toorx Experience plus all parameter (speed, inclination) = 0

### ISSUE THREAD

**Issue by Okinur** [cagnulein/qdomyos-zwift#1107]
Once connected the app with the treadmill, the app does not recognise the speed, the inclination etc. 
All parameter are equal to 0, I tried also to increase the speed but it is always 0
[debug-Fri_Dec_30_20_39_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10328909/debug-Fri_Dec_30_20_39_11_2022.log)

**Comment by cagnulein** [comment]
@Okinur the log is of zero bytes, can you try to upload it again? Thanks

**Comment by Okinur** [comment]
Uploaded!

**Comment by cagnulein** [comment]
@Okinur I checked and unfortunately the treadmill never answer to any request. I guess you need the toorx gate as you suggested before to make it work so :(

**Comment by Okinur** [comment]
Ok I bought the gate and now the app recognises the treadmill (I don't know why but I can't increase/decrease the speed with the app using + and -, instead the incline works also from the app).
But the main issue is: Zwift (on my computer) identifies and connect with bluetooh on my smartphone (where is installed the app) but once I enter in the map, Zwift doesn't recognise the speed 

Log attached. Thank you!
[debug-Mon_Jan_2_12_44_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10331377/debug-Mon_Jan_2_12_44_57_2023.log)

**Comment by cagnulein** [comment]
@Okinur rename your android device to "run" (only 3 letters) and reboot it. It should fix the issue.
You can also use the Wahoo KICKR device instead
Let me know

**Comment by Okinur** [comment]
After read your comment, at the first try, I tried Wahoo KICKR device and it works (not the speed by the app as before but at least the avatar follow the speed of the treadmill).

Then, I changed my name on my device but Zwift doesn't see "run" but the old name. I also disinstalled Zwift and reinstalled but it remains always the old name and Wahoo device does not appears anymore.

Attached the last debug and some screenshot
[debug-Mon_Jan_2_19_22_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10333088/debug-Mon_Jan_2_19_22_48_2023.log)
![WhatsApp Image 2023-01-02 at 19 26 37](https://user-ima
![screenshot_zwift](https://user-images.githubusercontent.com/33390599/210267766-3a93e296-3706-4ed6-a358-302bb1c4754e.png)
ges.githubusercontent.com/33390599/210267758-f4c83525-fa57-4ef9-a965-ba83466a9687.jpeg)
![WhatsApp Image 2023-01-02 at 19 19 57](https://user-images.githubusercontent.com/33390599/210267762-019b1336-e7e2-4f0b-a9d7-9bd600d8ce02.jpeg)

**Comment by cagnulein** [comment]
@Okinur did you reboot your phone after changing the name?

**Comment by Okinur** [comment]
Yes, more than 1 time (and also on the computer)

**Comment by cagnulein** [comment]
are you using the pc for zwift? if so you certainly need to buy this https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift#for-zwift-pc-users

don't you have another android device where install zwift?

**Comment by Okinur** [comment]
Installed on another android device and it works (with KICKR), so for the computer I need the dongle even if I have the bluetooth inside on the computer?
However, I tried to upload a custom workout (in folder training), in Open train program there is the workout created and if I click on it, I receveid the message: "Program has been loaded correctly. Press start to begin" but there is no start button to click (I have Pause and Stop) and the speed doesn't change accordingly to the zwo file. I also tried to press pause and then start but it's the same. 
My guess...it's related to the minus and plus button for the speed that doesnt work...
I attached the log with the test of the training program..
[debug-Mon_Jan_2_21_09_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10333368/debug-Mon_Jan_2_21_09_57_2023.log)

Thank you!

**Comment by cagnulein** [comment]
yes you need the dongle for pc because stock bluetooth chip are shit :) 
yes the training program issue is releated to the speed issue that you have with the speed tile.
tomorrow i will check the log
thanks and have a good night!

**Comment by cagnulein** [comment]
I already understood why @Okinur  :) the force speed implementation is empty for your treadmilll because no one has requested me so!
In order to implement this we need to clone the behaviour of another app. Does this usb key has a manufacturer app?

**Comment by Okinur** [comment]
No app is available from the USB..
But I attached screenshot from nRF connect with the USB connection...Hopefully it is useful..
![Screenshot_2023-01-03-09-31-36-669_no nordicsemi android mcp](https://user-images.githubusercontent.com/33390599/210322783-7fab6c75-45e3-433c-9f6a-27f8ae2caa23.jpg)
![Screenshot_2023-01-03-09-31-28-468_no nordicsemi android mcp](https://user-images.githubusercontent.com/33390599/210322804-47f92ba1-2681-4c19-bb73-c90238ef78db.jpg)

**Comment by cagnulein** [comment]
thanks @Okinur i have an idea in mind about this. I will develop this in the next days

**Comment by cagnulein** [comment]
modification done @Okinur i will send you another version today 2.12.36
you need to enable the toorx ftms treadmill new setting and restart qz when you will receive it.
Let me know

**Comment by Okinur** [comment]
Sadly doesn't work..

[debug-Thu_Jan_5_11_15_47_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10351301/debug-Thu_Jan_5_11_15_47_2023.log)

**Comment by cagnulein** [comment]
@Okinur on this log i don't see any attempt of writing speed. can you please try again? thanks

**Comment by Okinur** [comment]
Strange...
[debug-Fri_Jan_6_17_06_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10361458/debug-Fri_Jan_6_17_06_33_2023.log)

**Comment by cagnulein** [comment]
ok in this i saw them. unfortunately the usb just ignores my command. could you please try to ask to the manufacturer if there is any app compatible with their usb able to control the speed? if so we can clone the behavior 

let me know

**Comment by cagnulein** [comment]
@Okinur any news?
