### ISSUE TITLE
Horizon treadmill miss some frames in the init

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1108]
working log:
[debug-Thu_Dec_29_11_09_26_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/10327089/debug-Thu_Dec_29_11_09_26_2022.log.zip)

not working log:
[debug-Fri_Dec_30_19_56_35_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/10327090/debug-Fri_Dec_30_19_56_35_2022.log.zip)

**Comment by cagnulein** [comment]
@rickny @janabouc I hope this will not break the compatibility with your log. I'm trying to help Michelle with an issue on her treadmill

**Comment by PugMamma** [comment]
Was able to connect my treadmill to the regular (non beta) version of QZ: 
[debug-Sun_Jan_1_12_53_14_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329505/debug-Sun_Jan_1_12_53_14_2023.log)

Beta version of QZ that did connect
[debug-Sun_Jan_1_13_10_24_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329506/debug-Sun_Jan_1_13_10_24_2023.log)

Beta With Footpad: No Connection
[debug-Sun_Jan_1_13_17_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329507/debug-Sun_Jan_1_13_17_51_2023.log)

Beta Without Footpad: No Connection
[debug-Sun_Jan_1_13_26_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329508/debug-Sun_Jan_1_13_26_36_20
[debug-Sun_Jan_1_13_33_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329513/debug-Sun_Jan_1_13_33_03_2023.log)
[debug-Sun_Jan_1_13_30_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329515/debug-Sun_Jan_1_13_30_05_2023.log)
[debug-Sun_Jan_1_13_22_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10329512/debug-Sun_Jan_1_13_22_05_2023.log)

**Comment by cagnulein** [comment]
@PugMamma since i added Zwift Runpod as a single device #1097 , you have to set your horizon in the manual device setting in the advanced settings. I guess this is the main issue! Let me know

**Comment by PugMamma** [comment]
> @PugMamma since i added Zwift Runpod as a single device #1097 , you have to set your horizon in the manual device setting in the advanced settings. I guess this is the main issue! Let me know

I was able to connect and complete my runs without issue today. Thank you so much for the help!

**Comment by cagnulein** [comment]
wonderful news @PugMamma ! thanks for the feedback!

**Comment by cagnulein** [comment]
@RickNY wrote:

> Hi Roberto.. Im not sure if this has anything to do with what you changed here - https://github.com/cagnulein/qdomyos-zwift/issues/1108  -- but it started around the same time just before I hurt my foot.. Now that I’m back to using the tread every day, I’m having an issue like 25% of the time where I do my normal startup routine, and then once the Peloton intro finishes the countdown, I press Start in QZ – and I get nothing from the tread.  When this happens, I have to quit everything and start over – and I’ve found I’ve had to power cycle the tread as well.  I attached a debug log from today when it happened – not sure if you see anything going on..  For reference, here is my startup routine:
> 
>  
> 
> Wake tread up from sleep
> Start QZ on my iPhone – BT light on tread lights up (as of light there now seems like there is a 4-5 second delay before that happens that never happened before) – QZ does see the Horizon 7.4 and displays on the top
> Start Peloton app on my iPad and find a walk.. By the time I find one, usually 30-45 seconds has passed since QZ started init with tread
> Start Peloton workout – QZ picks it up on the phone and I answer Yes to follow the metrics
> Start QZ watch app once Peloton intro gets down to 30 seconds remaining
> Press Start on QZ on iPhone when intro gets to 0:00 --- this is where things are failing sometimes
>  
> 
> Thanks
> 
> Rick
> 
>  

[debug-Tue_Jan_17_17_50_06_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10442619/debug-Tue_Jan_17_17_50_06_2023.log.txt)


actually @rickny it's the same @PugMamma issue but with a slightly different behaviour. It should have a quick fix. I'm sending you a new one today. Thanks for the feedback!

**Comment by RickNY** [comment]
So far so good. I’ll keep you posted if that changes. Thanks!

**Comment by cagnulein** [comment]
@RickNY glad to hear it! @PugMamma i hope the same for you, isn't it?

**Comment by PugMamma** [comment]
> @RickNY glad to hear it! @PugMamma i hope the same for you, isn't it?

I will be trying it out tomorrow and can confirm then that it is still working for me.
