### ISSUE TITLE
Using two Android devices

### ISSUE THREAD

**Issue by gruessung** [cagnulein/qdomyos-zwift#111]
Hi!
First of all thanks for this great app!
One question...is it possible to use two Android devices for pairing my treadmill to zwift?

I have an Android phone and an Android tablet. 
Unfortunately zwift has no official linux support for my notebook :( 

Thanks!

**Comment by cagnulein** [comment]
yes sure! i'm using 2 android device too on my setup :)

**Comment by gruessung** [comment]
Is it also possible to use only one Android device 🤔?

**Comment by cagnulein** [comment]
no, you need one device for zwift and one for my software..it's over bluetooth, remember ;)

**Comment by gruessung** [comment]
Yeah, you're right. 
Mhh...my android tablet is to old. 
I will try to use my raspi3 for your software and my huawei p30 pro for zwift :)

**Comment by cagnulein** [comment]
rasp3 has some issue on the bluetooth stack. try it! if it doesn't work,
pi0w it's better!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 gen 2021 alle ore 10:09 Alexander Grüßung <
notifications@github.com> ha scritto:

**Comment by gruessung** [comment]
Ah, thanks! I have one pi0w :)

**Comment by cagnulein** [comment]
could i close this one? @gruessung
