### ISSUE TITLE
[BUG] Resistance icon not showing in Floating Window

### ISSUE THREAD

**Issue by aaciii** [cagnulein/qdomyos-zwift#1113]
![image](https://user-images.githubusercontent.com/80229871/210264870-1f4c2ca1-aefe-4aea-b244-0b09c9cfa7cf.jpeg)

**Comment by timkarnold** [comment]
<img width="387" alt="Screen Shot 2023-01-03 at 12 07 54 PM" src="https://user-images.githubusercontent.com/1531526/210405840-6e590f7f-740e-4dce-a57d-06a53919f886.png">

Reproducing on mine as well.

**Comment by cagnulein** [comment]
fixed!
