### ISSUE TITLE
[REQ] Settings / auto restart

### ISSUE THREAD

**Issue by aaciii** [cagnulein/qdomyos-zwift#1114]
Suggest that a deride be added to re-start the app after settings are changed.  

When user exits the settings page via the back button, if they had changed anything, the app could ask "re-start and apply changes now?"

**Comment by cagnulein** [comment]
> This would be especially helpful with the new floating window settings, as it takes a few tries to get the width/height settings the way you like them.

you don't need to restart qz to apply width and height for the floating. just double push the floating icon!

**Comment by timkarnold** [comment]
> you don't need to restart qz to apply width and height for the floating. just double push the floating icon!

Nice trick - perhaps in same realm as this request is to do that automatically for the user. The settings page states a restart is needed for things to apply, so if it just did whatever was needed upon setting change (offer to restart the app or re-launch the floating window) it would be much more intuitive.

**Comment by cagnulein** [comment]
@aaciii @timkarnold done! it will be in the 2.13.23 and above!
