### ISSUE TITLE
#1109  Nordic Track S25i Treadmill [BUG]

### ISSUE THREAD

**Issue by Afnug** [cagnulein/qdomyos-zwift#1115]
**Describe the bug**

Plus and minus not working in the tiles, all metrics at 0

 - Device: [e.g. iPhone6]Samsung S21+
 - Version [e.g. 22] Android 13
 

https://drive.google.com/file/d/1YSwXfBhYllqwnR8Yc7qlsdVAilz5uaz1/view?usp=drivesdk

I increased the speed in .1 increments then down again, I increased the incline from 1 to 12 (there is no 11) then down again.

**Comment by cagnulein** [comment]
@Afnug fixed the fact you don't see metrics. let's see if also the speed forcing was related. I will send you a new one ASAP!

**Comment by Afnug** [comment]
Thanks Roberto

I will try it later.

Steve
