### ISSUE TITLE
sportstech sx600 connection but no data

### ISSUE THREAD

**Issue by Chris0079** [cagnulein/qdomyos-zwift#1116]
Downloaded app connected to sportstech sx600 . Showing connected via Bluetooth but no data seems to be transmitted. Connected to Zwift it finds the app and all connection are made but once again nothing works no movement when peddling etc no watts are showing on app or zwift 

[debug-Mon_Jan_2_21_22_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10333533/debug-Mon_Jan_2_21_22_35_2023.log)

>

**Comment by cagnulein** [comment]
hi @Chris0079 enable the hammer_racer_s setting in QZ in the bike option and restart qz. It should work then.
Let me know!

**Comment by Chris0079** [comment]
Amazing works strait away now thanks so much for your help . One final question and I’ll leave you be , is there anyway I can enable zwift to auto change resistance on my sportstech bike ? Or is not compatible Thanks for quick response and getting it working On 3 Jan 2023, at 06:48, Roberto Viola ***@***.***> wrote:﻿
hi @Chris0079 enable the hammer_racer_s setting in QZ in the bike option and restart qz. It should work then.
Let me know!

**Comment by cagnulein** [comment]
Hi @Chris0079 for auto resistance, try this.
Disable the hammer_race_s setting and enable the snode bike instead and restart qz
If also this doesn't work, disable the snode bike and try the fitplus bike setting
If also this doesn't work, disable the fitplus bike bike and try the virtufit setiting

We have to understand if there is a different profile that enables the auto resistance

Let me know

**Comment by cagnulein** [comment]
ok if you have a sportstech app where you are able to change the resistance from the app itself, I can add this in case
Let me know

**Comment by Chris0079** [comment]
Hi mate I followed the instruction you left on fb about doing the bug report , I scratched around for a android phone and followed instruction numerous times but the log file only shows tomes tones in the fs folder and no bt logs , I presume this is no good to you but can forward the full log if you think it will help ??

**Comment by Chris0079** [comment]
Tomestone not tomes times sorry

**Comment by cagnulein** [comment]
you checked in all the subfolders? some android phone have different path to do this. maybe you can try with a different phone?

**Comment by Chris0079** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10362664/btsnoop_hci.log)

**Comment by Chris0079** [comment]
hope that make some kinda sense to you i have no idea

**Comment by cagnulein** [comment]
great @Chris0079 i'm going to bed now. i will check tomorrow!

**Comment by Chris0079** [comment]
no worries thanks again

**Comment by cagnulein** [comment]
Hi @Chris0079 I checked the log and unfortunately there is no communication between the phone and the bike. Did you use the app during the sniff? Could you please retry? Thanks!

**Comment by Chris0079** [comment]
Hi all I did was run a program from app to the bike , it was a set program that changes speed and distance . Unfortunately that kinda the best the app offers as it not very good . Is it worth trying again ? Happy to do so but I cannot change the speed or resistance manually only by running a program ? On 8 Jan 2023, at 07:07, Roberto Viola ***@***.***> wrote:﻿
Hi @Chris0079 I checked the log and unfortunately there is no communication between the phone and the bike. Did you use the app during the sniff? Could you please retry? Thanks!

**Comment by cagnulein** [comment]
yes please try again, and also send me the whole bug report, maybe there are some hidden file also.

**Comment by Chris0079** [comment]
Ok will do also just found another app that seems to allow me to change resistance etc direct from app without running an actual course . I will do one with that and send over as well . Can’t thank you enough for all your help On 8 Jan 2023, at 07:28, Roberto Viola ***@***.***> wrote:﻿
yes please try again, and also send me the whole bug report, maybe there are some hidden file also.

**Comment by cagnulein** [comment]
any time!

**Comment by Chris0079** [comment]
[bugreport-gta3xlwifieea-RP1A.200720.012-2023-01-08-13-38-29.zip](https://github.com/cagnulein/qdomyos-zwift/files/10368544/bugreport-gta3xlwifieea-RP1A.200720.012-2023-01-08-13-38-29.zip)

hi hopefully got it this time manged to get app to change resistance automatically and manual via Bluetooth. I've sent the full bug report as requested
thanks again chris

**Comment by cagnulein** [comment]
yes @Chris0079 ! i can see the data now, let me add this!

**Comment by cagnulein** [comment]
@Chris0079 how many resistance levels does your bike have? also in the log did you go from resistance 1 to the max?

**Comment by Chris0079** [comment]
Amazing On 9 Jan 2023, at 09:38, Roberto Viola ***@***.***> wrote:﻿
yes @Chris0079 ! i can see the data now, let me add this!

**Comment by Chris0079** [comment]
32 levels s and yes I did but not in any order went up and down but did get to 32 and 1 On 9 Jan 2023, at 09:56, Chris ***@***.***> wrote:﻿Amazing On 9 Jan 2023, at 09:38, Roberto Viola ***@***.***> wrote:﻿
yes @Chris0079 ! i can see the data now, let me add this!

**Comment by cagnulein** [comment]
@Chris0079 in order to determine exactly the resistance levels, i need a hci snoof where you're doing this:

start from res 1
put res 2
wait 5 seconds
put res 3
and on to the max

are you able to do so?

**Comment by cagnulein** [comment]
note for me: wireshark filter for resistance` (btatt.value contains 02:44:05 && len(btatt.value) == 7) `

**Comment by Chris0079** [comment]
Yes of course will do it when I get in from work and ping over the report . Thanks On 9 Jan 2023, at 10:14, Roberto Viola ***@***.***> wrote:﻿
@Chris0079 in order to determine exactly the resistance levels, i need a hci snoof where you're doing this:
start from res 1
put res 2
wait 5 seconds
put res 3
and on to the max
are you able to do so?

**Comment by cagnulein** [comment]
perfect! at the moment i already implemented the metrics reading !

**Comment by cagnulein** [comment]
yes i saw them! i will add them tomorrow! ( i only saw some missing step in the very early resistance steps, but we can add them in the future if they work fine)

**Comment by cagnulein** [comment]
@Chris0079 i implemented the resistance, unfortunately there are some holes probably because you were too fast changing the resistance. anyway let's see how it goes, in case you will create another hci snoof. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Chris0079** [comment]
Hi thanks for update can’t seem to get it to work probably being stupid . I’ve got the hammer bike setting on as previous and bike is connected it’s saying wahoo kick not qz . If I connect qz nothing work . All works on wahoo kick but not the auto resistance . Is their another setting I should be turning on ??On 10 Jan 2023, at 07:19, Roberto Viola ***@***.***> wrote:﻿
@Chris0079 i implemented the resistance, unfortunately there are some holes probably because you were too fast changing the resistance. anyway let's see how it goes, in case you will create another hci snoof.
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@Chris0079 first of all you have to enable the new sportstech sx600 setting and the Fit Plus Bike setting too. Disable all the rest. Restart qz and check if you can change the resistance with the resistance plus and minus button in the resistance tile.

Remember that in the last log I can't get all the resistance levels, so it could be that qz stucks into a resistance level for this reason

Let me know

**Comment by Chris0079** [comment]
Sorry you must think I’m an idiot I can’t find the setting for the sportstech bike ?? Do I need to do any update or something I can’t find it On 10 Jan 2023, at 16:14, Roberto Viola ***@***.***> wrote:﻿
@Chris0079 first of all you have to enable the new sportstech sx600 setting and the Fit Plus Bike setting too. Disable all the rest. Restart qz and check if you can change the resistance with the resistance plus and minus button in the resistance tile.
Remember that in the last log I can't get all the resistance levels, so it could be that qz stucks into a resistance level for this reason
Let me know

**Comment by cagnulein** [comment]
@Chris0079 do you update QZ to the version 2.12.40 ? I don't remember if I add you to the closed beta. In case I don't 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
[Uploading debug-Sat_Jan_14_07_06_16_2023 (1).log…]()

**Comment by cagnulein** [comment]
[debug-Sat_Jan_14_07_06_16_2023 (1).log](https://github.com/cagnulein/qdomyos-zwift/files/10417333/debug-Sat_Jan_14_07_06_16_2023.1.log)

**Comment by cagnulein** [comment]
@Chris0079  the error is `"fitplusbike::errorServiceCharacteristicWriteError"` now we need to figure this out.
Could you please disable the virtual device bluetooth on experimental settings and restart and try again with these settings? Send me a debug log then again. Thanks

**Comment by Chris0079** [comment]
Hi please find the bug test with virtual Bluetooth device disabled . Still no data on app On 14 Jan 2023, at 13:09, Roberto Viola ***@***.***> wrote:﻿
@Chris0079  the error is "fitplusbike::errorServiceCharacteristicWriteError" now we need to figure this out.
Could you please disable the virtual device bluetooth on experimental settings and restart and try again with these settings? Send me a debug log then again. Thanks

**Comment by cagnulein** [comment]
hi @Chris0079 you have to upload the log from the github interface, doesn't work by email. Thanks

**Comment by Chris0079** [comment]
[debug-Sat_Jan_14_17_15_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10418462/debug-Sat_Jan_14_17_15_27_2023.log)

hi sorry about that , please find log attached

**Comment by cagnulein** [comment]
ok thanks, it's an odd issue, i have to understand it first. I will let you know in the next days. Thanks and have a nice weekend!

**Comment by Chris0079** [comment]
[debug-Sun_Jan_15_16_11_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10420609/debug-Sun_Jan_15_16_11_12_2023.log)
once again thanks for all your help trying to get this working . please find bug log for the strange wattage. this is me pedalling pretty slow. thanks

**Comment by cagnulein** [comment]
hi @Chris0079 I checked the log and the wattage is quite high in the QZ app too. Are you able to record a video with the bike console and qz at the same time and share me a log about this session? I believe that your bike is sending wattage in a different way from the other fitplusbikes. Let me know, we're near!
