### ISSUE TITLE
[REQ] Attach fit file at end of workout

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#1117]
Roberto,

At the end of each workout, QZ sends an email with a png attachment,  It would be nice to also attach the fit file that's automatically saved and possibly delete that fit file once the email is sent to keep the folder clean and/or allow the fit and debug folder to be user configurable.

Thanks,

Pierre

**Comment by cagnulein** [comment]
@ptrinephi the fit file it's already in the email.
for safety reason it's better to
keep the fit file. you can clean the qz folder with the button in the bottom of the experimental settings 

let me know

**Comment by ptrinephi** [comment]
It's not on the email I get, is there an option to turn it on?

**Comment by cagnulein** [comment]
maybe your provider is stripping it. check it from the web interface of your mail account

**Comment by ptrinephi** [comment]
oh my! you're right! I see it in the gmail web!  thanks.
