### ISSUE TITLE
[BUG] No speed or incline control on T6.5S

### ISSUE THREAD

**Issue by Jaedee** [cagnulein/qdomyos-zwift#1119]
[debug-Wed_Jan_4_11_35_28_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10343735/debug-Wed_Jan_4_11_35_28_2023.log)
**Describe the bug**
Enabled the specific setting for my treadmill (T6.5S). Have tried all other treadmill options under Nordictrack/Proforma. App correctly reports speed and incline, and correctly sneds this data to Zwift. 

When tapping +/- icons for speed and incline, nothing happens.

Have tried Treadmill Speed Forcing on/off. 

IFit works to control speed and incline. 

**To Reproduce**
1. Get app working and correctly reporting speed and incline data. 
2. Attempt to change incline from app. 

**Expected behavior**
Incline (or speed) should change, but doesn't. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6a, fully updated
![PXL_20230104_115114441](https://user-images.githubusercontent.com/8293427/210549359-f1ce9eef-706c-4c1f-a020-39241edc6a1e.jpg)

**Comment by cagnulein** [comment]
hi @Jaedee in order to add your profile i need that you follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

let me know

**Comment by Jaedee** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/10344201/btsnoop_hci.log)
Hi @cagnulein, please see attached the HCI BT snoop log as requested.

This was from a session wherein I increased the inclination by 0.5% to a maximum of 10%, then back down again in differing steps. I also modified the speed in steps of 0.1km/h and higher.

**Comment by cagnulein** [comment]
perfect thanks @Jaedee 
today and tomorrow are travel days for me. i will check this in the weekend

**Comment by Jaedee** [comment]
Thanks @cagnulein  - perhaps I'm confused, but I actually thougt that the T6.5S already had a profile working, as it appears on the [Equipment Compatibility List](https://github.com/cagnulein/qdomyos-zwift/wiki/Equipment-Compatibility#treadmill-compatibility-table) here:

![image](https://user-images.githubusercontent.com/8293427/210561572-b0402111-70cc-4185-a5da-144ac5358d71.png)

Am I mistaked?

**Comment by cagnulein** [comment]
@Jaedee actually you're right , i already implemented this https://github.com/cagnulein/qdomyos-zwift/issues/592

maybe you have a different firmware? anyway when i will be at home i will check this

**Comment by Jaedee** [comment]
It could be a new firmware issue, yes. Interesting.

**Comment by cagnulein** [comment]
@hoveeman do you still have this treadmill?

**Comment by hoveeman** [comment]
> @hoveeman do you still have this treadmill?

I do! I just used QZ and the treadmill 2 days ago. I did a Peloton run and it adjusted the speed and incline perfectly for the whole run. I did not press + or - in QZ. I'd be happy to try that and report back, along with the QZ version I'm using. Any tips on how to check treadmill firmware?

**Comment by Jaedee** [comment]
I can check the firmware too. I think maybe I saw it already, when I pressed "settings" on mine. I'll check again.

**Comment by cagnulein** [comment]
@hoveeman glad to hear this!

yes a check on both firmware version will probably useful.

also maybe an us against an uk version?

**Comment by Jaedee** [comment]
Could be, I'm UK.

**Comment by hoveeman** [comment]
Everything worked properly for me. Treadmill is v81.210 and QZ is 2.11.96 

I can share a debug file shortly. 

![image](https://user-images.githubusercontent.com/18269595/210570225-8fa154c3-d4af-4ccc-8d3e-3ba91a5156a2.jpeg)

https://user-images.githubusercontent.com/18269595/210570498-aeabc172-11af-43df-beb1-bccf8ba821a0.MOV

**Comment by hoveeman** [comment]
Pic of treadmill settings in QZ

![image](https://user-images.githubusercontent.com/18269595/210570763-531c048c-4fed-481d-892d-1050424fa8bc.png)

**Comment by Jaedee** [comment]
![image](https://user-images.githubusercontent.com/8293427/210571596-5011661b-096c-441e-9fbb-d33d6bf21f47.png)

**Comment by hoveeman** [comment]
I could try and update my treadmill firmware if that would help. I would hate to update it though and find out we're stuck and I can't go back. Haha

**Comment by cagnulein** [comment]
@Jaedee confirmed, it's slightly different from the @hoveeman one. I'm adding a new setting for this i will call it t6_5s_yourfirmwareversion

I will let you know when I will be ready with a new beta

**Comment by Jaedee** [comment]
@cagnulein thank you so much!

**Comment by cagnulein** [comment]
@Jaedee 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@Jaedee are we ok with this? did i fix it?
