### ISSUE TITLE
capital sports evo pro

### ISSUE THREAD

**Issue by ccostantyt** [cagnulein/qdomyos-zwift#1123]
capital sports evo pro. logs collected trying different iConsole setup
[debug-gio_gen_5_18_48_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355238/debug-gio_gen_5_18_48_35_2023.log)
[debug-gio_gen_5_18_42_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355239/debug-gio_gen_5_18_42_56_2023.log)
[debug-gio_gen_5_18_45_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355240/debug-gio_gen_5_18_45_37_2023.log)
[debug-gio_gen_5_18_46_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355241/debug-gio_gen_5_18_46_49_2023.log)
[debug-gio_gen_5_18_38_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355242/debug-gio_gen_5_18_38_29_2023.log)
[debug-gio_gen_5_18_50_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355243/debug-gio_gen_5_18_50_08_2023.log)
[debug-gio_gen_5_18_41_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355245/debug-gio_gen_5_18_41_56_2023.log)
[debug-gio_gen_5_18_41_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355247/debug-gio_gen_5_18_41_00_2023.log)
[debug-gio_gen_5_18_47_50_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355248/debug-gio_gen_5_18_47_50_2023.log)
[debug-gio_gen_5_18_34_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355249/debug-gio_gen_5_18_34_57_2023.log)
[debug-gio_gen_5_18_44_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355250/debug-gio_gen_5_18_44_44_2023.log)
[debug-gio_gen_5_18_40_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355251/debug-gio_gen_5_18_40_06_2023.log)
[debug-gio_gen_5_18_43_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355252/debug-gio_gen_5_18_43_46_2023.log)
[debug-gio_gen_5_18_49_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355253/debug-gio_gen_5_18_49_17_2023.log)
[debug-gio_gen_5_18_39_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355254/debug-gio_gen_5_18_39_22_2023.log)
[debug-gio_gen_5_18_16_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10355255/debug-gio_gen_5_18_16_16_2023.log)

**Comment by cagnulein** [comment]
thanks #1122

**Comment by cagnulein** [comment]
@ccostantyt i don't remember are we ok with this? did i fix it?

**Comment by ccostantyt** [comment]
CIao Roberto,

tutto ok!

Grazie,
Claudio
