### ISSUE TITLE
Horizon Treadmill Auto speed off 0.1 

### ISSUE THREAD

**Issue by hnbrace** [cagnulein/qdomyos-zwift#1128]
[debug-Thu_Jan_5_19_27_24_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10366824/debug-Thu_Jan_5_19_27_24_2023.log)

[Uploading debug-Tue_Jan_3_18_13_42_2023.log…]()

When using auto speed to follow a Peloton class, if a range is given, the app seems to be 0.1 slower. Like if they say between 3-5 mph, the app takes it to 3.9 instead of 4. Other times, it goes right to the target speed. Using a Horizon 7 tread.  

Also on Jan 5 the treadmill stopped before peloton class was over. I think this was actually due to treadmill timing out after 30min than an issue with the app. Not sure if the debug log would show that

**Comment by cagnulein** [comment]
done @hnbrace 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@hnbrace did you try?

**Comment by hnbrace** [comment]
Yes! Worked! It was directly in the middle. If called out between 3-4 mph,
it would stop at 3.5mph. Thank you.

**Comment by cagnulein** [comment]
perfect!
