### ISSUE TITLE
[BUG] Reebok Treadmill not connecting

### ISSUE THREAD

**Issue by Harrytri** [cagnulein/qdomyos-zwift#1129]
Reebok treadmill connecting to app but app not picking up movement of treadmill at all.
Treadmill moving but app says it's not.

**Comment by Harrytri** [comment]
Find attached

**Comment by cagnulein** [comment]
hi @Harrytri i don't see the log

**Comment by Harrytri** [comment]
Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
You have to attach it to the GitHub interface

**Comment by Harrytri** [comment]
I wouldn't let me

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
you have to zip it :)

**Comment by Harrytri** [comment]
[Uploading inbound4878151333047502772.zip…]()

**Comment by Harrytri** [comment]
Try now

**Comment by cagnulein** [comment]
@Harrytri you have to wait the end of the upload before pushing the comment button

**Comment by Harrytri** [comment]
[inbound1159919849707179364.zip](https://github.com/cagnulein/qdomyos-zwift/files/10369357/inbound1159919849707179364.zip)

**Comment by cagnulein** [comment]
thanks @Harrytri 9pm here tomorrow i will check it

**Comment by cagnulein** [comment]
@Harrytri the problem about your setup is that the dkn_endurun_treadmill must be off in the settings. Let me know

**Comment by Harrytri** [comment]
Many thanks.
I now pairs with my phone but zwift can't find it at all.


Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
@Harrytri describe me your setup: where qz is running, where zwift does?

**Comment by cagnulein** [comment]
reset the network settings of your ipad and reboot it
let me know

**Comment by Harrytri** [comment]
No, it can't find it
[debug-Wed_Jan_11_08_50_15_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/10395560/debug-Wed_Jan_11_08_50_15_2023.zip)

**Comment by cagnulein** [comment]
@Harrytri did you try also qz and zwift on the same ipad? you should see the wahoo tread device on zwift

**Comment by cagnulein** [comment]
yes try on the same ipad as i did in this video Auto Inclination on Zwift with QZ app on any bluetooth Treadmill
https://youtu.be/KTQ2n7yeDbo

**Comment by Harrytri** [comment]
[debug-Fri_Jan_13_18_44_42_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/10414644/debug-Fri_Jan_13_18_44_42_2023.zip)

It still drops connection

**Comment by cagnulein** [comment]
@Harrytri any news?
