### ISSUE TITLE
Treadmill Workouts All Labeled as Run in Strava

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#1130]
Since January 6th all my treadmill workouts are being labeled as a "run" in Strava. I did 3 walks on January 5th and were all labeled correctly as a Walk. 
Small issue since I can correct the workout type in Strava manually, but unsure what caused the change overnight. 

Walks Labeled Correctly in Strava:
[debug-Thu_Jan_5_10_49_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10367857/debug-Thu_Jan_5_10_49_22_2023.log)

Tread Bootcamp and Walk Labeled as Run in Strava:
[debug-Fri_Jan_6_12_22_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10367859/debug-Fri_Jan_6_12_22_15_2023.log)
[debug-Fri_Jan_6_13_30_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10367860/debug-Fri_Jan_6_13_30_25_2023.log)

**Comment by cagnulein** [comment]
@PugMamma thanks! Checked and it's due to new peloton api. Now they are mark these activies as 

"fitness_discipline": "circuit",
"fitness_discipline_display_name": "Tread Bootcamp",

so how can I treat this?
In the fit file I can put as a Multisport activity if you want. Otherwise i will have to add a new setting for "bootcamp strava activity".

What do you think?

**Comment by PugMamma** [comment]
> @PugMamma thanks! Checked and it's due to new peloton api. Now they are mark these activies as
> 
> "fitness_discipline": "circuit", "fitness_discipline_display_name": "Tread Bootcamp",
> 
> so how can I treat this? In the fit file I can put as a Multisport activity if you want. Otherwise i will have to add a new setting for "bootcamp strava activity".
> 
> What do you think?

Not sure what will be easier, but prior to the Peloton update Treadmill Bootcamps were labeled as 'workout' in Strava. This worked out well since there are running and walking bootcamps. What are walks labeled as in the January 6th debug log?

**Comment by cagnulein** [comment]
@PugMamma the one from the 6th is

`"fitness_discipline":"walking"`

hah so from the 6th was not walking on strava, but workout instead?

**Comment by cagnulein** [comment]
also do you have the fit files @PugMamma ?

**Comment by PugMamma** [comment]
> @PugMamma the one from the 5th is
> 
> `"fitness_discipline":"walking"`
> 
> hah so from the 5th was not walking on strava, but workout instead?

From the 6th and 7th, Walks were labeled as Runs.

**Comment by cagnulein** [comment]
ok but in the 5th was marked with Walk or with workout? also do you have the fit files?

**Comment by PugMamma** [comment]
> also do you have the fit files @PugMamma ?
[Fit Files.zip](https://github.com/cagnulein/qdomyos-zwift/files/10367940/Fit.Files.zip)

**Comment by cagnulein** [comment]
ok checked the fit files, i was wrong. The fit files are perfect, sowing genric workout for bootcamp and walking for walking one on 7th jan. so it's a bug of strava. can you open a ticket to them?
let me know!

**Comment by PugMamma** [comment]
> ok checked the fit files, i was wrong. The fit files are perfect, showing generic workout for bootcamp and walking for walking one on 7th jan. so it's a bug of strava. can you open a ticket to them? let me know!
I got a response from Strava support.  Strava said the sport is labeled as generic. "Since the file didn't include any information on the sport type it will default to your account's "Default Sport" which is Running." I sent them the below FIT files as well. 
![Strava](https://user-images.githubusercontent.com/91086001/213238282-0a491e8d-ccfc-4804-9733-bc253d7e92c1.JPG)
[Fit Files.zip](https://github.com/cagnulein/qdomyos-zwift/files/10448581/Fit.Files.zip)

**Comment by cagnulein** [comment]
yes the generic one was the bootcamp, isn't it?

**Comment by PugMamma** [comment]
> yes the generic one was the bootcamp, isn't it?

Correct. I asked him what the more recent walk file said for sport type, but his reply didn't answer it. Since I can't view the FIT file on my laptop I couldn't verify on my own. 
I'm unsure what the sport type for bootcamps was prior to January 5th since those FIT files would be labeled as 'workout' previously vs 'running'.

**Comment by cagnulein** [comment]
one thing i can tell you for sure: i didn't change anything, so they have changed something for sure. Anyway I'm open to changes if I can help you somehow. Maybe changing the bootcamp workout type?

**Comment by PugMamma** [comment]
> one thing i can tell you for sure: i didn't change anything, so they have changed something for sure. Anyway I'm open to changes if I can help you somehow. Maybe changing the bootcamp workout type?

Does the walk FIT file has the sport type as generic as well? It's not that big of a deal to change it manually in Strava.

**Comment by cagnulein** [comment]
the 6th one is walking the 7th one is generic

**Comment by PugMamma** [comment]
> the 6th one is walking the 7th one is generic

I'll contact Strava again. I think sending both FIT files for a bootcamp and a Walk was too confusing for them.

**Comment by cagnulein** [comment]
ehehe ok let me know

**Comment by PugMamma** [comment]
> ehehe ok let me know


![Capture](https://user-images.githubusercontent.com/91086001/213324399-d24a7c39-0f2c-4260-a17e-593672bea4af.JPG)

**Comment by cagnulein** [comment]
is this answer about which file?  @PugMamma

**Comment by PugMamma** [comment]
> is this answer about which file? @PugMamma

That was from a walk file. I can attach it if you want

**Comment by cagnulein** [comment]
yes to double check it and in case also if you have the debug log from the same session

**Comment by PugMamma** [comment]
> yes to double check it and in case also if you have the debug log from the same session

[FIT and Debug Log.zip](https://github.com/cagnulein/qdomyos-zwift/files/10453399/FIT.and.Debug.Log.zip)

**Comment by cagnulein** [comment]
<img width="1661" alt="Screenshot 2023-01-19 at 06 56 12" src="https://user-images.githubusercontent.com/48216/213366587-1238acfa-a5b3-4159-807c-5671f2bd155e.png">
the fit file is a walking one but I understood now what they mean!

They changed the behaviour: they're not getting the sport from the fit file directly but they are using the meta information that i'm sending with the fit file. Since day 1 on qz, if you were using a treadmill i was send this bit like running, bike like riding and so on. So i have to modify also this now. Good to know! I will do this today!

**Comment by cagnulein** [comment]
for reference, I guess they are talking about this

<html>
<body>


activity_type: | string optional, case insensitive.Possible values : "AlpineSki", "BackcountrySki", "Canoeing", "Crossfit", "EBikeRide", "Elliptical", "Golf", "GravelRide", "Handcycle", "Hike", "IceSkate", "InlineSkate", "Kayaking", "Kitesurf", "NordicSki", "Ride", "RockClimbing", "RollerSki", "Rowing", "Run", "Sail", "Skateboard", "Snowboard", "Snowshoe", "Soccer", "StairStepper", "StandUpPaddling", "Surfing", "Swim", "Velomobile", "VirtualRide", "VirtualRun", "Walk", "WeightTraining", "Wheelchair", "Windsurf", "Workout", "Yoga" Deprecated: prefer using sport_type, will be ignored if sport_type is included. Overrides type detected from file, if left unspecified type detected from file will be used.
-- | --



</body>
</html>

https://developers.strava.com/docs/uploads/

**Comment by cagnulein** [comment]
done @PugMamma it will be in the 2.12.50 version

**Comment by PugMamma** [comment]
> done @PugMamma it will be in the 2.12.50 version

Thank you, I got the newest update today and it worked. Tread bootcamps are labeled as Workouts and walks are Walks!
![Screenshot_20230121_141943_Strava](https://user-images.githubusercontent.com/91086001/213889242-2a38ba4d-26aa-4be3-9454-000eccff8029.jpg)
![Screenshot_20230121_131108_Strava](https://user-images.githubusercontent.com/91086001/213889266-f05260dc-529f-45d0-bd3a-e8ff206bc70a.jpg)

**Comment by cagnulein** [comment]
yeah @PugMamma great!

**Comment by msw03** [comment]
@cagnulein Could you add me to the closed beta, as per the QZ FB group conversation? My e-mail is mattw82@gmail.com. You said to e-mail you but I couldn't find your e-mail so trying here instead :)
