### ISSUE TITLE
[BUG] Sole f80: Control incline/speed not working, ""virtualtreadmill connection error"??

### ISSUE THREAD

**Issue by jquiver** [cagnulein/qdomyos-zwift#1132]
Hi,

I own a Sole f80 treadmill (US Model) and I am trying to control incline/speed, but I can't get it to work.
I have enabled the "experimental" control incline option.
(On a side note, I don't understand why the incline control option is controlling the return from writeCharacteristic here https://github.com/cagnulein/qdomyos-zwift/blob/master/src/solef80treadmill.cpp#L51, since that function should be used for many things and not just the incline).

When I start QZ the treadmill beeps (successful connection), and when I change the speed on the treadmill controls I can see QZ reading correctly the speed. So I am confident QZ and the treadmill are somehow interacting correctly.

However, when I press "+" on the incline icon in QZ, the treadmill doesn't move and I see the following sequence on the debug log:

```
Sun Jan 8 17:56:29 2023 1673229389920 Debug: solef80treadmill.cpp void solef80treadmill::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  >>  "5b 04 00 10 4f 4b 5d"  //  "noop"
Sun Jan 8 17:56:29 2023 1673229389939 Debug:   HCI event triggered, type: 13
Sun Jan 8 17:56:29 2023 1673229389959 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "5b0400104f4b5d"
Sun Jan 8 17:56:29 2023 1673229389960 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "characteristicWritten 5b 04 00 10 4f 4b 5d"
Sun Jan 8 17:56:30 2023 1673229390620 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << {49535343-1e4d-4bd9-ba61-23c647249616} 5 5b 02 10 00 5d"
Sun Jan 8 17:56:30 2023 1673229390620 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "writing incline 1"
Sun Jan 8 17:56:30 2023 1673229390623 Debug: solef80treadmill.cpp void solef80treadmill::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  >>  "5b 02 f1 04 5d"  //  "Inclination up"
Sun Jan 8 17:56:30 2023 1673229390639 Debug:   HCI event triggered, type: 13
Sun Jan 8 17:56:30 2023 1673229390659 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "5b02f1045d"
Sun Jan 8 17:56:30 2023 1673229390659 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "characteristicWritten 5b 02 f1 04 5d"
Sun Jan 8 17:56:30 2023 1673229390686 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << {49535343-1e4d-4bd9-ba61-23c647249616} 7 5b 04 00 f1 4f 4b 5d"
Sun Jan 8 17:56:30 2023 1673229390714 Debug: virtualtreadmill.cpp void virtualtreadmill::treadmillProvider() "virtualtreadmill connection error"
```
The sequence of "noop" and "inclination up" repeats periodically, as if it is retried over and over (even if I don't press again the "+" icon in QZ).
What is suspicious to me is the message  "virtualtreadmill connection error", which I am not sure if it is the real issue here.

Also, the first instance of "virtualtreadmill connection error" appears just after init2, which also appears suspicious.

```
Sun Jan 8 17:52:49 2023 1673229169015 Debug: solef80treadmill.cpp void solef80treadmill::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  >>  "5b 01 f0 5d"  //  "init1"
Sun Jan 8 17:52:49 2023 1673229169039 Debug:   HCI event triggered, type: 13
Sun Jan 8 17:52:49 2023 1673229169057 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "5b01f05d"
Sun Jan 8 17:52:49 2023 1673229169057 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "characteristicWritten 5b 01 f0 5d"
Sun Jan 8 17:52:49 2023 1673229169079 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << {49535343-1e4d-4bd9-ba61-23c647249616} 11 5b 08 f0 92 01 01 78 05 0f 12 5d"
Sun Jan 8 17:52:49 2023 1673229169357 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << {49535343-1e4d-4bd9-ba61-23c647249616} 5 5b 02 03 02 5d"
Sun Jan 8 17:52:49 2023 1673229169358 Debug: solef80treadmill.cpp void solef80treadmill::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) stop/pause event detected from the treadmill
Sun Jan 8 17:52:49 2023 1673229169359 Debug: solef80treadmill.cpp void solef80treadmill::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  >>  "5b 02 03 01 5d"  //  "init2"
Sun Jan 8 17:52:49 2023 1673229169379 Debug:   HCI event triggered, type: 13
Sun Jan 8 17:52:49 2023 1673229169397 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "5b0203015d"
Sun Jan 8 17:52:49 2023 1673229169397 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "characteristicWritten 5b 02 03 01 5d"
Sun Jan 8 17:52:49 2023 1673229169637 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << {49535343-1e4d-4bd9-ba61-23c647249616} 5 5b 02 03 02 5d"
Sun Jan 8 17:52:49 2023 1673229169638 Debug: solef80treadmill.cpp void solef80treadmill::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) stop/pause event detected from the treadmill
Sun Jan 8 17:52:49 2023 1673229169641 Debug: solef80treadmill.cpp void solef80treadmill::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  >>  "5b 02 03 01 5d"  //  "init2"
Sun Jan 8 17:52:49 2023 1673229169657 Debug:   HCI event triggered, type: 13
Sun Jan 8 17:52:49 2023 1673229169679 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "5b0203015d"
Sun Jan 8 17:52:49 2023 1673229169679 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "characteristicWritten 5b 02 03 01 5d"
Sun Jan 8 17:52:49 2023 1673229169721 Debug: virtualtreadmill.cpp void virtualtreadmill::treadmillProvider() "virtualtreadmill connection error"
```

Attaching full debug log here:
[debug-Sun_Jan_8_19_17_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10370195/debug-Sun_Jan_8_19_17_25_2023.log)

Any idea of what could be going wrong?
Any help in debugging this is very appreciated.
Thanks,

Jack

**Comment by cagnulein** [comment]
> (On a side note, I don't understand why the incline control option is controlling the return from writeCharacteristic here https://github.com/cagnulein/qdomyos-zwift/blob/master/src/solef80treadmill.cpp#L51, since that function should be used for many things and not just the incline).

because if we use the FTMS, no need to send any data to the treadmill

**Comment by cagnulein** [comment]
@jquiver are you sure your model (US version) is able to change the inclination from bluetooth? Some US treadmill can't. Try with the sole app, if it works from there we have hope :)

Let me know

**Comment by jquiver** [comment]
From the Sole app I can't see any obvious way to manually change the incline/speed.

I can start training programs that change incline/speed, but I don't know if those changes are actually triggered by the app or simply by the training program itself running on the treadmill.

I will do some more research on difference between US and non-US models and if it is "just" a problem with the firmware. 

Thanks for the reply.

**Comment by cagnulein** [comment]
@jquiver as far as i know (from investigation here with other qz users) if the sole app doesn't allow the changes means that the firmware is locked.
the sole have the ability to do so, but when it see the us firmware it hides the buttons

you can try to check if you can load a uk firmware on your treadmill

**Comment by jquiver** [comment]
Probably not an issue with qz then. Let's close this issue.
Unfortunately I can' find anything on how to update firmware on the Sole f80.... it seems I am out of luck.

**Comment by cagnulein** [comment]
@jquiver i'm sorry about this :(
