### ISSUE TITLE
Garmin Fenix 5x Power Sensor 

### ISSUE THREAD

**Issue by 3583Bytes** [cagnulein/qdomyos-zwift#1137]
Does anyone know how to connect a Garmin Fenix to the qdomyoszwift app?    I can connect the watch to the cadence sensor but it does not seem to find the power sensor.  It works fine will RGT and zwift it just won’t connect to the watch.  Any suggestions?

Thanks

**Comment by cagnulein** [comment]
@3583Bytes did you enable the ant cadence setting in qz? does your android has ant+?

**Comment by 3583Bytes** [comment]
I am using iOS it should be transmitting as Bluetooth.  Cadence works it’s Power I am missing

**Comment by cagnulein** [comment]
enable the bike power setting in the experimental settings. be aware that enabling this will not allow you to connect to rgt or zwift by bluetooth. it's just a way to understand your issue

are you sure the cadence on your watch comes from qz? i had this watch too in the past and i don't think i was able to get it worked with any sensor by bluetooth, only ant+. maybe in the last 2 years they updated the firmware 

let me know

**Comment by 3583Bytes** [comment]
Thanks I will try that.  The 5 can connect to Bluetooth sensors but it can’t broadcast HR as Bluetooth (which is a bummer). 

https://www8.garmin.com/manuals/webhelp/fenix5plus/EN-US/GUID-0AA57B88-BA13-4983-ADAC-7EA7DABC735D.html
