### ISSUE TITLE
Zwift not seeing Renpho

### ISSUE THREAD

**Issue by DanielPHall** [cagnulein/qdomyos-zwift#1141]
When starting Renpho and Zwift I am only able to ride with resistance in workout mode, no race or ride mode. When I start QDOMYOS, Zwift is unable to pick up any change. Debug log attached.
[debug-Wed_Jan_11_10_20_26_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10391364/debug-Wed_Jan_11_10_20_26_2023.log)

**Comment by cagnulein** [comment]
hi @DanielPHall thanks 
I need a debug log from a zwift session showing the error. In this log i just see a connection to the bike.
Thanks

**Comment by cagnulein** [comment]
@DanielPHall where qz is running? where zwifti is running? android or ios? let me know

**Comment by DanielPHall** [comment]
Hi is this rigjt

**Comment by DanielPHall** [comment]
Qz running Android , zwift windows

**Comment by cagnulein** [comment]
don't you see the wahoo virtual device on windows? Also you can use QZ on windows too, you can download it from here https://github.com/cagnulein/qdomyos-zwift/suites/10303843883/artifacts/506664725

**Comment by DanielPHall** [comment]
sorry not sure what you mean. Does QZ and Zwift not need to be on separate
devices? Happy to download QZ to windows if you believe that will fix the
problem.

**Comment by DanielPHall** [comment]
I can see the Renpho device on Zwift, yes. But the resistance is not
working. It is stuck on 20 in game mode

**Comment by DanielPHall** [comment]
ok thanks will try and let you know

**Comment by DanielPHall** [comment]
same issue, Zwift sees the bike but QZ not connecting. Should Zwift be
connecting to QZ I assume?

**Comment by cagnulein** [comment]
let for now, zwift out of the scenario.
Just QZ.
Connect the bike from the bluetooth settings of windows
Open QZ
Do you see the metrics?

**Comment by DanielPHall** [comment]
yes QZ metrics I can see in the app

**Comment by cagnulein** [comment]
ok so with QZ open and connected to your bike, open zwift, in the pair screen you have to see a wahoo kickr device
Let me know

**Comment by DanielPHall** [comment]
just searching but not finding anything

[image: image.png]

**Comment by DanielPHall** [comment]
ah sorry got it under power source not controller

**Comment by cagnulein** [comment]
if you see under power source you will see also to the controller

**Comment by DanielPHall** [comment]
yes but only once I had found it under power source. Now in game, no
connection

[image: image.png]

**Comment by DanielPHall** [comment]
no signal

[image: image.png]

**Comment by cagnulein** [comment]
i don't see your images

**Comment by cagnulein** [comment]
now lunch time here i will be back in a couple of hours

**Comment by DanielPHall** [comment]
ok thank you very much for help thus far

**Comment by DanielPHall** [comment]
metric headings showing but all metrics are at 0. In Zwift same thing. This
is of course while pedalling.

[image: image.png]


[image: image.png]

**Comment by cagnulein** [comment]
@DanielPHall i'm not seeing any of your images. i guess you have to wait the upload has been completed before commenting.

please also share a debug log from the windows qz

let me know

**Comment by DanielPHall** [comment]
I hope attached is accurate. Not sure why you cant see pics as I can see
them in sent items.

[image: image.png]

**Comment by DanielPHall** [comment]
Can you see these?

![image](https://user-images.githubusercontent.com/122445237/211813846-be79d64f-8bcc-4984-a7a5-7b58a644a0d4.png)


![image](https://user-images.githubusercontent.com/122445237/211814036-bf4a50ca-3da7-462f-94f7-aff72d4924eb.png)

**Comment by DanielPHall** [comment]
Can you please explain where to find this as it seems to update the windows binary file every time the application closes down. This is what I have in that file under debug.




[debug-Wed_Jan_11_12_38_52_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10392721/debug-Wed_Jan_11_12_38_52_2023.log)

**Comment by cagnulein** [comment]
@DanielPHall you did right and I found the issue. I'm fixing it right now (it's due to a windows behaviour)

**Comment by DanielPHall** [comment]
wonderful thank you

**Comment by cagnulein** [comment]
it's building https://github.com/cagnulein/qdomyos-zwift/actions/runs/3893328589/jobs/6645795955
When it finishes, you will see the new windows version here https://github.com/cagnulein/qdomyos-zwift/actions/runs/3893328589

Let me know

**Comment by DanielPHall** [comment]
sorry but where exactly do I find the executable file. I cant see it on the link you provided

**Comment by cagnulein** [comment]
it's still building..wait 5 minutes

**Comment by DanielPHall** [comment]
ah ok, said it succeeded 8min ago. I will wait thanks

**Comment by cagnulein** [comment]
yes it's still building another process :)

**Comment by DanielPHall** [comment]
while I have you. the previous version I could run from the extracted file but after a while it seems to close down and then takes me to Patreon page. Is this normal? How do I make it an application that I can keep open on the desktop

**Comment by cagnulein** [comment]
yes you have to add your email to the email settings and press ok and restart qz. i aleady added your patreon account to the access list

**Comment by DanielPHall** [comment]
ok thanks, you can see I am new to the development world so thank you very much for all the help

**Comment by cagnulein** [comment]
@DanielPHall done https://github.com/cagnulein/qdomyos-zwift/suites/10308823354/artifacts/507015710

**Comment by DanielPHall** [comment]
still not showing any metrics. I am going into meeting now but will look at it again a little later. How do I know it is not using the previous application, should I uninstall something somewhere?

**Comment by cagnulein** [comment]
if you provide me a fresh debug log after the meeting I can check if it's the newest version. Thanks

**Comment by DanielPHall** [comment]
[debug-Wed_Jan_11_14_22_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10393230/debug-Wed_Jan_11_14_22_54_2023.log)

**Comment by cagnulein** [comment]
yes it's the new one. now we have an issue with the bluetooth dongle of your pc. Try to disable the "virtual bluetooth device" in the experimental settings in QZ and restart QZ. Let me know if it's any better

**Comment by DanielPHall** [comment]
[debug-Wed_Jan_11_15_06_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10393588/debug-Wed_Jan_11_15_06_49_2023.log)

**Comment by cagnulein** [comment]
`Unable to set value for descriptor "{00002902-0000-1000-8000-00805f9b34fb}" for characteristic "{00002ad2-0000-1000-8000-00805f9b34fb}" of the service "{00001826-0000-1000-8000-00805f9b34fb}" : "Access is denied."`

still this error.
Are you sure your bike is not connected somewhere else?
Did you try to reboot your pc? or at least turn off and turn on the bluetooth?

**Comment by DanielPHall** [comment]
no let me try that now, its not connected to anything else

**Comment by DanielPHall** [comment]
[debug-Wed_Jan_11_15_18_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10393759/debug-Wed_Jan_11_15_18_22_2023.log)

**Comment by DanielPHall** [comment]
metrics now working in Qz but Swift now not picking up Wahoo

**Comment by cagnulein** [comment]
because @DanielPHall you disabled too many settings! enable virtual device must be on (only the bluetooth one must be off)
Let me know

**Comment by DanielPHall** [comment]
but then the metrics dont work
[debug-Wed_Jan_11_15_55_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10393974/debug-Wed_Jan_11_15_55_20_2023.log)

**Comment by cagnulein** [comment]
@DanielPHall what you did before to fix this? i mean did you reboot the pc? I guess your dongle is not so compliant and needs to be rebooted every time you got a connection to the bike.

**Comment by cagnulein** [comment]
just create a shortcut from the qz folder of the executable ;)
