### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rapt0r41** [cagnulein/qdomyos-zwift#1143]
> #**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Here is my debug log.

**Comment by cagnulein** [comment]
hi @Rapt0r41 i don't see any description or log here

please detail
