### ISSUE TITLE
[REQ] Make Gears setting permanent

### ISSUE THREAD

**Issue by Benzinbruder** [cagnulein/qdomyos-zwift#1146]
**Is your feature request related to a problem? Please describe.**
Currently the Gears setting (any maybe others as well?) is reset to 0 when closing / reopening the app.

**Describe the solution you'd like**
It would be great if the last used value for the setting remained when reopening the app.

**Describe alternatives you've considered**
The alternative is having to set the Gears tile / Gears value every time when (re)opening the app.

**Comment by cagnulein** [comment]
@Benzinbruder done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
