### ISSUE TITLE
Proform Sport CX bike support

### ISSUE THREAD

**Issue by Tometoyou1983** [cagnulein/qdomyos-zwift#115]
Unable to connect to Proform CX bike. Uploading the bluetooth log file.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5793055/btsnoop_hci.log)

**Comment by cagnulein** [comment]
great @Tometoyou1983 ! could you please tell me something more about your bike?
Does it have controlled resistance? which range of resistance does it have?
What did you do in the log? do you remember the speed/cadence/distance/elapsed time and so on? they could be useful to decode the data,

**Comment by cagnulein** [comment]
BS-RGB-5008 is the name of your bike on bluetooth isn't it?

**Comment by cagnulein** [comment]
also write me your email associated to your google play account to roberto.viola83@gmail.com and i will add you to the beta tester.

BTW great year the '83! :)

**Comment by cagnulein** [comment]
#131

**Comment by cagnulein** [comment]
follow the #131

**Comment by Tometoyou1983** [comment]
Sorry. Got busy over the weekend. vnvsnaresh@gmail.com

**Comment by Tometoyou1983** [comment]
It has controllable resistance thru ifit app.
It has a lot of data you asked below. The app itself outputs wattage also

**Comment by Tometoyou1983** [comment]
Bluetooth is I_EB

**Comment by cagnulein** [comment]
> It has controllable resistance thru ifit app.

ok first of all, trying if the version 2.2.4 works. If it works i will try to add controllable resistance too!
