### ISSUE TITLE
[BUG] installation procedure seems broken

### ISSUE THREAD

**Issue by pssara** [cagnulein/qdomyos-zwift#1150]
**Describe the bug**
the installation on a Linux system and a raspberry pi is described here https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md
After I complete the steps of cloning the repository and updating the submodules, I change the directory to the src and execute qmake.
qmake fails to find any projects.

![image](https://user-images.githubusercontent.com/13958895/212411491-57c4063e-2900-46ff-bce2-5db56da12b36.png)

**Comment by cagnulein** [comment]
do a qmake without entering on src 

this is due to a pr that we merge 2 days ago 

@drmason789

**Comment by pssara** [comment]
thanks, it still doesn't compile.
In file included from powerzonepack.h:21,
                 from peloton.h:5,
                 from homeform.h:8,
                 from nordictrackifitadbbike.cpp:2:
trainprogram.h:113:13: error: ‘QRecursiveMutex’ does not name a type; did you mean ‘QBasicMutex’?
     mutable QRecursiveMutex schedulerMutex;
             ^~~~~~~~~~~~~~~
             QBasicMutex

**Comment by drmason789** [comment]
If it is only required to run the app, perhaps change to the src directory and specify the qdomyos-zwift.pro file in the qmake command.

**Comment by cagnulein** [comment]
@pssara did you fix it?

**Comment by pssara** [comment]
@cagnulein Thanks Roberto, I compiled it just fine. There was an additional dependency, the rasbian should be at the bullseye version. (Qt 15.5)

**Comment by cagnulein** [comment]
@pssara ok if you want make a PR about these, thanks!
