### ISSUE TITLE
[BUG] Echelon Stride treadmill stays in 'app' mode after the app has been closed (iOS keeps the connection alive)

### ISSUE THREAD

**Issue by jeremystern1963** [cagnulein/qdomyos-zwift#1155]
**Describe the bug**
The treadmill display changes from standard to in 'app' mode that is controlled by the QZ app. When the QZ app is closed, the connection stays open and remains as 'app' on the display.

**To Reproduce**
1. Launch QZ app
2. Treadmill display changes to 'app'
3. Close QZ app
4. Treadmill connection to app remains open and display continues to show 'app'

**Expected behavior**
The connection to the QZ app and the treadmill should close and the display should return to standard display.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks, I will check this tomorrow!

**Comment by cagnulein** [comment]
i did the code, i will send you a beta today @jeremystern1963

**Comment by cagnulein** [comment]
@jeremystern1963 are we ok with this?

**Comment by jeremystern1963** [comment]
Hi Roberto,Yes, everything is working perfectly now. Thanks so much for your help. On Jan 30, 2023, at 3:35 AM, Roberto Viola ***@***.***> wrote:﻿
@jeremystern1963 are we ok with this?
