### ISSUE TITLE
Rower AVG pace

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1158]
@cagnulein Thanks!

The second option would be perfect. With the initial pace field all needed metrics will be there: 
- the first tile with current, average over whole, max 
- the second new tile with average pace of last 500ma

_Originally posted by @Carael in https://github.com/cagnulein/qdomyos-zwift/issues/1118#issuecomment-1383103662_

@janabouc

**Comment by cagnulein** [comment]
done @Carael ! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@jonathancolledge

**Comment by cagnulein** [comment]
@Carael did you try?

**Comment by Carael** [comment]
Yes I did try it today. Pace 500m (m/km) was working fine. The value appeared but after some time (i think it maybe after 500m, can check on next training).
![IMG_2878](https://user-images.githubusercontent.com/6861396/213694075-67da21c7-e905-40c1-afce-ab1dd351f314.PNG)

For the first field as you see it's still only current, average and max are zero. What's strange when i close the app, start new then the values are there. But once I click Stop and restart training the values stays zero.

Also see the Speed tile - average and max are with value "inf".

**Comment by cagnulein** [comment]
> Yes I did try it today. Pace 500m (m/km) was working fine. The value appeared but after some time (i think it maybe after 500m, can check on next training).

strange, it should appear immediately along with the speed and pace.

> For the first field as you see it's still only current, average and max are zero. What's strange when i close the app, start new then the values are there. But once I click Stop and restart training the values stays zero.

ok let me check this

> Also see the Speed tile - average and max are with value "inf".

and also this :)

**Comment by cagnulein** [comment]
@Carael any news?

**Comment by Carael** [comment]
@cagnulein I think I don't get any update of the app on Test Flight for Ios - I'm on 2.12.45.

**Comment by cagnulein** [comment]
are you still experiencing the same 3 issues? @Carael

**Comment by Carael** [comment]
Yes.

**Comment by cagnulein** [comment]
got it, I will try to find time to fix them, thanks

**Comment by cagnulein** [comment]
@Carael i'm checking this now. which rower do you have? I guess I got the issue

**Comment by cagnulein** [comment]
fixed! @Carael 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
