### ISSUE TITLE
[BUG]Back character missing from title bar

### ISSUE THREAD

**Issue by aaciii** [cagnulein/qdomyos-zwift#1163]
On QZ app startup, the "back" icon is missing (appears to be undefined character - see image)

![image](https://user-images.githubusercontent.com/80229871/212748421-65031a13-b50c-41ce-a5dd-f2a9b488b587.jpeg)

**Comment by cagnulein** [comment]
yeah i have to find an utf character available for all the devices
thanks

**Comment by cagnulein** [comment]
done, thanks

**Comment by cagnulein** [comment]
changed in the 2.13.24 let's see if it's better
