### ISSUE TITLE
[BUG] Peltonapp  Heart rate not showing after connection

### ISSUE THREAD

**Issue by jjschlot** [cagnulein/qdomyos-zwift#1169]
**Describe the bug**
A clear and concise description of what the bug  #is.

When setting up to ride on my Echelon X5 I bring up the QZ app and apple watch like always. 

On my apple tv I bring up the Peloton app and connect my heart rate to the app, and then start the workout. 

 and connect my heart rate to the app, and then start the workout

After the counter and gets down to one, I hit follow and work out all the resistance like always.

The heart rate shows for like 3 seconds and goes to zero after that. 
[debug-Sun_Jan_8_09_12_43_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435757/debug-Sun_Jan_8_09_12_43_2023.log)
[debug-Wed_Jan_11_12_03_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435758/debug-Wed_Jan_11_12_03_40_2023.log)
![Wed Jan 11 12_03_34 2023_power](https://user-images.githubusercontent.com/110925988/212920095-2c6ec706-2bd9-4b27-b607-0dd3d8469ebf.png)
[debug-Fri_Jan_13_10_36_34_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435759/debug-Fri_Jan_13_10_36_34_2023.log)
[debug-Wed_Jan_11_11_51_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435761/debug-Wed_Jan_11_11_51_49_2023.log)
[debug-Wed_Jan_11_12_06_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435762/debug-Wed_Jan_11_12_06_25_2023.log)
[debug-Wed_Jan_11_10_46_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435763/debug-Wed_Jan_11_10_46_58_2023.log)
[debug-Fri_Jan_13_10_33_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435764/debug-Fri_Jan_13_10_33_21_2023.log)
[debug-Fri_Jan_13_10_35_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435766/debug-Fri_Jan_13_10_35_40_2023.log)
[debug-Wed_Jan_11_10_49_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435767/debug-Wed_Jan_11_10_49_18_2023.log)
[debug-Fri_Jan_13_11_24_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10435771/debug-Fri_Jan_13_11_24_49_2023.log)
![Wed Jan 11 11_50_53 2023_pelotonresistance](https://user-images.githubusercontent.com/110925988/212920140-8af4400a-9fd2-4152-a217-4e26c536b005.png)
[Uploading debug-Thu_Jan_5_14_32_24_2023.log…]()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ iPhone 13 pro]
 - OS: [ iOS16.2]
 - Version [2.11]

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @jjschlot you mean hr on peloton app? what about the HR on the qz app?

**Comment by jjschlot** [comment]
Yeah sorry was in a hurry when I did it.Sent from my iPhoneOn Jan 17, 2023, at 9:20 AM, Roberto Viola ***@***.***> wrote:﻿
hi @jjschlot you mean hr on peloton app? what about the HR on the qz app?

**Comment by cagnulein** [comment]
@jjschlot check while qz is running, on another device with nrfconnect if you can see the qz device with an heart icon and also if you can read the hr from qz. from your log everything is nominal so i guess it's a peloton issue. with nrfconnect we can be sure about this.

**Comment by jjschlot** [comment]
[Uploading debug-Tue_Jan_17_10_43_04_2023.log…]()

**Comment by jjschlot** [comment]
I also tried using another Apple Tv logged into the app along with deleted the apps.

**Comment by cagnulein** [comment]
hi @jjschlot a debug log in this case it's useless because qz is sending the metrics, the problem is on the other side, so it's why i asked you about the nrfconnect

**Comment by jjschlot** [comment]
![Uploading 809323AF-DBEE-4207-84F6-1859D6057E4A.jpeg…]()

**Comment by jjschlot** [comment]
![Uploading 9209441E-DCC4-4965-BE06-F30414BDAFBA.jpeg…]()

**Comment by jjschlot** [comment]
![Uploading image.jpg…]()

**Comment by cagnulein** [comment]
@jjschlot you have to wait the upload before pushing comment, otherwise i can't see anything :)

**Comment by jjschlot** [comment]
![14DF897D-730B-4495-9E12-3AC70895FEAF](https://user-images.githubusercontent.com/110925988/212992027-e775b98f-1e19-43ef-bf55-b6205d21a254.jpeg)

**Comment by cagnulein** [comment]
perfect, as you can see HR is visible on nrfconnect so qz is sending HR. Can't you run peloton app on this device to check if you can see the HR?

**Comment by jjschlot** [comment]
This is an issue that happened within the last 2 weeks. 

As I was on the app you stated to use it   The apple tv was connected with no readouts. But before starting the work out it stated it was connected. Showed my heart rate for like 3 seconds and went to zero after.

**Comment by jjschlot** [comment]
I can try running the Peloton app on my iPad Pro while using my phone for the metrics from QZ. I have never done this before It always worked through my apple tv without having to screen share.

**Comment by cagnulein** [comment]
maybe an ios update? maybe a peloton update? What I can 100% say is that qz is doing its thing. Try peloton on the ipad where nrfconnect runs. If it works, it says once again that qz is ok :) i'm sorry but you should contact peloton in this case

**Comment by cagnulein** [comment]
@jjschlot did you fix it? also is the ios peloton workaround enabled in the experimental setting?
