### ISSUE TITLE
[BUG] PZ classes not maintaining zone via auto-resistance

### ISSUE THREAD

**Issue by natjwest** [cagnulein/qdomyos-zwift#1171]
**Describe the bug**
Auto-resistance is not working on Peloton Power Zone classes. It does work on non-PZ classes.

**To Reproduce**
1. Turn on EX-5
2. Wait for qdomyos to connect to bike
3. Note that FTP in settings is set to 210
4. Note that startup resistance setting works, and bike moves to that setting
5. Load Peloton PZ class
6. qdomyos pop-up asks if I want to auto follow, say yes
7. Start session in qdomyos, ensure Peloton timing tile is accurate
8. No auto-adjustments of resistance
9. Turn magnet icon on and off, no change
11. Use tiles I made to set resistance, they work, so tablet/qdomyos is talking to the bike
12. Target Zone tile does automaticaly update from instructor cues.
13. Non-PZ classes auto-adjust resistance just fine

**Expected behavior**
PZ classes should automatically adjust resistance based on user's cadence to keep user in target zone.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Fire Tablet HD 10 7th Gen
 - OS: Fire OS 5.7.0.0 (659662020)
 - Version 2.11.91

**Append a debug log**

Debug log attached.
  
  
**Additional context**
I did have auto-adjust resistance work on PZ classes once but not for the last 10 or so classes.
[debug-Tue_Jan_17_07_36_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10439433/debug-Tue_Jan_17_07_36_17_2023.log)

**Comment by cagnulein** [comment]
ok thanks, i will check tomorrow. 10pm here :)

**Comment by cagnulein** [comment]
@natjwest you need to enable the "Zwift Force Resistance" in the experimental settings (Default: true)
Let me know

**Comment by natjwest** [comment]
Problem solved, thank you.

**Comment by cagnulein** [comment]
great!
