### ISSUE TITLE
[BUG] Auto-Resistance Breaks the "Gears" Settings

### ISSUE THREAD

**Issue by mikemac400** [cagnulein/qdomyos-zwift#1180]
Auto resistance does not work in Zwift. It does work if I adjust the setting in Zwift, but it disables the gears setting when I do this. Details below.

1. I have the auto resistance setting turned on in Zwift.
![image](https://user-images.githubusercontent.com/36450759/213333324-5b667c0c-2064-457e-8f84-5a1f985b4516.png)

2. have auto resistance turned on in your app.
![image](https://user-images.githubusercontent.com/36450759/213333381-4a1390f5-19d4-49cb-bbdb-aa0abea22732.png)
I think this is related to the "Gears" in the app, because when I change the "Trainer Difficulty" slider in the Zwift App, the "Gears" setting in your app does not work anymore.

**To Reproduce**
1. Open QZ Fitness. Make sure Auto-Resistance is turned on and the gears setting is set to a number. I use '5'.
2. Open Zwift - Auto resistance will not work. The resistance stays the same whether going uphill or downhill.
3. Click somewhere in the "trainer difficult" slider in Zwift to adjust the trainer difficulty. 
4. Error occurs - the gears setting no longer works in QZ fitness. However, the auto-resistance setting did not work beforehand. 

**Expected behavior**
Auto-resistance should work in Zwift when the "Gears" setting is enabled.

**Desktop (please complete the following information):**
 - Windows 10 
 - 10.0.19044

Debug log  is attached. I also attached testing notes of what I was physically doing.   

[debug-Wed_Jan_18_18_05_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10452590/debug-Wed_Jan_18_18_05_02_2023.log)

[debug notes.txt](https://github.com/cagnulein/qdomyos-zwift/files/10452598/debug.notes.txt)

**Comment by cagnulein** [comment]
@mikemac400 I checked your log and i saw clearly that QZ is applying the gear mod correctly. So i have a doubt about the zwift setup: could you send me a screenshot of the zwift pair screen? I would like to check which devices you choose there.

Because in the log I got that you're using the Wahoo KICKR virtual device correctly, but for what you're telling to me it seems that the bike is connected directly to zwift instead going through QZ.

Let me know

**Comment by cagnulein** [comment]
also in the log I saw a lot of 

```
Wed Jan 18 18:05:15 2023 1674090315269 Warning:   Unable to set value for descriptor "{00002902-0000-1000-8000-00805f9b34fb}" for characteristic "{00002a05-0000-1000-8000-00805f9b34fb}" of the service "{00001801-0000-1000-8000-00805f9b34fb}" : "Access is denied."
Wed Jan 18 18:05:15 2023 1674090315282 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "ftmsbike::errorServiceDescriptorWriteError"
```

it makes me think about this issue #1151

**Comment by mikemac400** [comment]
@cagnulein - That is interesting. I double checked that I sent you the correct log, and I did. The bike was connected. 

Unfortunately, I cannot connect my laptop to QZ fitness anymore. I am consistently getting the bluetooth error now. I will purchase one of the dongles we discussed in #1151 and see if that helps. I cannot send over anymore debug logs until then since my device will not connect. 

To clarify a few of your questions...

_Could you send me a screenshot of the zwift pair screen? I would like to check which devices you choose there._

- Here is a screenshot of the devices I choose in Zwift. I actually cannot choose the "Zwift Hub". It gets replaced by the fake wahoo kickr device. Let me know if this is correct.
- 
![image](https://user-images.githubusercontent.com/36450759/213481194-50f2733e-2027-4169-a349-bed9a86d68aa.png)

_I checked your log and i saw clearly that QZ is applying the gear mod correctly._ 

- To clarify, the "Gears" setting was working correctly UNTIL I tried to adjust the trainer difficulty in Zwift. When I did that, the bike became a lot easier to pedal imediately despite the ground still being flat in Zwift. This happened around 6:09 in the notes I attached. 
- 
![image](https://user-images.githubusercontent.com/36450759/213481979-a133c862-4c83-414d-ac41-695f69482df7.png)

Take a quick look at the logs, but don't spend too much time on it. This issue may resolve itself with a new bluetooth dongle. I will also try to connect to a friend's laptop and my desktop to see if that works. I will update the ticket when I test on other devices or test the new dongle.

**Comment by cagnulein** [comment]
> * Here is a screenshot of the devices I choose in Zwift. I actually cannot choose the "Zwift Hub". It gets replaced by the fake wahoo kickr device. Let me know if this is correct.

yes it is

> * To clarify, the "Gears" setting was working correctly UNTIL I tried to adjust the trainer difficulty in Zwift. When I did that, the bike became a lot easier to pedal imediately despite the ground still being flat in Zwift. This happened around 6:09 in the notes I attached.

yes what I saw in that moment is that the incline from zwift decreases, but qz was still applying the gear mod. That's why i'm confused...

Ok let me know when you will be ready to test it again.

**Comment by mikemac400** [comment]
@cagnulein - This issue is resolved. Getting the UB-400 dongle resolved the issue. Auto-Resistance works now. The bluetooth errors must have been interfering with auto-resistance.

**Comment by cagnulein** [comment]
great @mikemac400 ! yes i supposed this!
