### ISSUE TITLE
[BUG] my proform TDF4 wworks fine in Zwift and RGT except there is no incline feedback

### ISSUE THREAD

**Issue by Chalky600** [cagnulein/qdomyos-zwift#1186]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Chalky600 a debug log is needed. Thanks

**Comment by Chalky600** [comment]
[debug-Fri_Jan_20_10_06_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10465600/debug-Fri_Jan_20_10_06_37_2023.log)

here goes  Ichanged a few settings trying to get it to work so may have messed it up it used to connect as Wahoo but now sees my bike as nokia 5.3 which is my phone

thanks

**Comment by Chalky600** [comment]
just getting used to this format lol#

**Comment by cagnulein** [comment]
got the issue, you have "Zwift Force Resistance" in the experimental setting disabled, please turn on it and it will work!

**Comment by Chalky600** [comment]
Thanks Roberto  Will give it a try over the weekend Regards  DaveSent from Mail for Windows From: Roberto ViolaSent: 20 January 2023 11:00To: cagnulein/qdomyos-zwiftCc: Chalky600; MentionSubject: Re: [cagnulein/qdomyos-zwift] [BUG] my proform TDF4 wworks fine in Zwift and RGT except there is no incline feedback (Issue #1186) got the issue, you have "Zwift Force Resistance" in the experimental setting disabled, please turn on it and it will work!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Chalky600** [comment]
Its fixed  Thanks for the help Regards  Dave   Sent from Mail for Windows From: Roberto ViolaSent: 20 January 2023 11:00To: cagnulein/qdomyos-zwiftCc: Chalky600; MentionSubject: Re: [cagnulein/qdomyos-zwift] [BUG] my proform TDF4 wworks fine in Zwift and RGT except there is no incline feedback (Issue #1186) got the issue, you have "Zwift Force Resistance" in the experimental setting disabled, please turn on it and it will work!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by cagnulein** [comment]
Glad to hear this!
