### ISSUE TITLE
[BUG] App can't see any BT device

### ISSUE THREAD

**Issue by josetta** [cagnulein/qdomyos-zwift#1188]
**Describe the bug**
Stopped to see any BT device after starting application, it always saw all BT devices (even my soundbar LG), but now after start I can see only "Connecting..." and devices are not cycling :) I created debug log. About few days, it worked. Other apps on mobile phone can see BT devices (Kinomap is seeing my device too), I tried to rst phone, reinstall app, remove all data of application, nothing works... I am not sure, if there was some new release lately. THX :D

**To Reproduce**
1. Open qdomyos-zwift app

**Expected behavior**
After opening app, app should find BT devices nearby (it can see my LG soundbar too, of yourse it won't connect to it)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android
 - Version 12 or 13

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Fri_Jan_20_14_41_11_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10466880/debug-Fri_Jan_20_14_41_11_2023.log)

**Comment by cagnulein** [comment]
@josetta the problem is simple 

` Search not possible due to turned off Location service`

enable the location services and restart qz and you're good to go! this is a limitation on android :)

**Comment by josetta** [comment]
weird, I'll check it but I am sure I turned it on :D

**Comment by cagnulein** [comment]
let me know ;)

**Comment by josetta** [comment]
Ah I though you mean permissions :D it seems our baby played with phone and turned it off :D THX it works again now, I will create new bug that I sent you yesterday in email soon :D THX and have a nice day :)

**Comment by cagnulein** [comment]
Great!
