### ISSUE TITLE
[BUG] Domyos EL 520 elliptical probs

### ISSUE THREAD

**Issue by josetta** [cagnulein/qdomyos-zwift#1191]
**Describe the bug**
I have application qdomyos-zwift on android, I am using it with Domyos EL 520 elliptical, but I am not sure if I am using it right :) first problem is, how I should use it, as bike or as running? Because EL 520 is set to run, or precisely, to walk. So even as bike or as run, I can't get enough watts and speed to do some training program (engineer of this device does not count watts from cadence/speed and resistence and eventually heartrate, it is always defined only by cadence/speed, so I can have resistence 15, if I have 60 RPM/5,5kph, I will always have 80 watts, but that is bullshit :) and maybe it is counted by speed, when I changed in Domyos elliptical options speed ratio to 2, watts are higher, but stil same on resistance change). Autoresistence is not working on my EL520 either, I tried both free ride or training, but resistance is not raising (if I need to get 130w in training but can do only 80 at normal speed, ERG should automatically raise resistance, on free ride, it should do it by incline, but it is not doing it... at least at my bike trainer that is native compatible with zwift is working that way)... so if I am using application wrong, maybe you can help me :)

And last question, does this app work with Rouvy? I actually was able to connect it, but I don't have subscription, so I can't test it.

I am adding two logs, first is from ride on bike, second is from runing :) THX

**To Reproduce**
1. Open application and connect it with Domyos EL 520
2. Set autoresistance in app on
3. On desktop Zwift app, connect it with mobile phone
4. Start running/cycling
5. On ascending, descending, or during training, resistance stays the same (can change it only manually)
6. Watts are computed only by cadence or speed, resistance and heart rate doesn't matters on watts

**Expected behavior**
Watts should be computed by more factors, not only speed or cadence, it should count resistence and maybe heart rate
Resistence should be raised/lowered by incline or training program

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Zwift for desktop
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android
 - Version: 12

**Append a debug log**  
  
**Additional context**
[debug-Fri_Jan_20_15_26_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10467676/debug-Fri_Jan_20_15_26_04_2023.log)
[debug-Fri_Jan_20_15_35_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10467682/debug-Fri_Jan_20_15_35_31_2023.log)

**Comment by cagnulein** [comment]
thanks, i will check this tomorrow :)

**Comment by cagnulein** [comment]
hi @josetta for the wattage, the first thing that comes to my mind is to use the resistance value as an inclination value for your elliptical. In this way you should have a greater wattage when you increase the resistance.

What do you think?

**Comment by josetta** [comment]
yes, I think that is only way, cause this machine have only resistance and no inclination system :) I am not sure if watts should not be recalculated with heartrate too, but that is maybe too complex :) and I don't know if it is possible, but on training program, I noticed ERG works that way, that if I need to get wattage or cadence, it automatically raise or lower resistance to get near that value, but I am not sure, if it counts inclination from map in this training programs too :) but my wife is training on Kinomap for now and she is not going any training program, so if it will works correctly on free ride, we will be happily jumping :) THX
