### ISSUE TITLE
ERG Mode Stops Auto-Adjusting Resistance after beginning of workout [BUG]

### ISSUE THREAD

**Issue by tylerdau** [cagnulein/qdomyos-zwift#1194]
**Describe the bug**
When running a custom zwift workout that sets my target power at 100W and in ERG mode (with Zwift up/down filter at +/-10), initially the resistance auto-adjusts well and finds a stable resistance. Then say 5-10 min into the workout if I increase or decrease my power and hold that above the +10 threshold (say at 120W) for multiple minutes, it no longer adjusts down the resistance to meet that power target. 

**To Reproduce**
1. Connect QZ and start a Custom Zwift workout in ERG mode with power target of 100W in Zone 2
2. Remain within +/-10W threshold for approx 5-10 min
3. Increase or decrease power above the +/-10W threshold (hold steady at around 80W or 120W) for multiple minutes
4. Error: no further auto-adjustment in resistance to keep at that power target

**Expected behavior**
Throughout the entire workout, auto-resistance should adjust to maintain at power target

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS on iPad 6th Generation
 - Version 14.6

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.5
 - Version 

**Append a debug log**  
[debug-Sat_Jan_21_10_30_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10472612/debug-Sat_Jan_21_10_30_33_2023.log)

  
**Additional context**
![IMG_4730](https://user-images.githubusercontent.com/15957626/213877938-1c686d61-c824-474d-8c23-76358d78fafb.PNG)
![IMG_4731](https://user-images.githubusercontent.com/15957626/213877940-4ed394a2-af0a-4af4-af3e-8b375499a62f.PNG)
![IMG_4732](https://user-images.githubusercontent.com/15957626/213877942-31eda17c-c547-4aed-b8f7-b9ac84cd1e62.PNG)

**Comment by cagnulein** [comment]
hi @tylerdau the problem is that you lost the connection to zwift, i mean i don't see any request from zwift after 10:31. Is it happening all the time?

**Comment by tylerdau** [comment]
Yes, this is happening in every session. Any suggestions on how to fix it?

Thanks so much,

Tyler

**Comment by cagnulein** [comment]
ok i did a patch for this, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS to receive the new beta. Thanks
