### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fiddlepotter** [cagnulein/qdomyos-zwift#1195]
@
[debug-Sat_Jan_21_13_47_14_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10472725/debug-Sat_Jan_21_13_47_14_2023.log)
[Uploading debug-Sat_Jan_21_13_46_48_2023.log…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @fiddlepotter what is the issue here?

**Comment by cagnulein** [comment]
id207 is your HR? the issue is that it's not broadcasting itself. Maybe it was turned off during the log?

**Comment by fiddlepotter** [comment]
Yes, that’s the HR. Ok I will see, the screen goes to sleep but it still sends information to the VeryFit app on my phone.
Should it be connected to my phone as well through Bluetooth or just connected to QZ?
Thank you again.
Sarah

On Jan 21, 2023, at 2:10 PM, Roberto Viola ***@***.***> wrote:

﻿

id207 is your HR? the issue is that it's not broadcasting itself. Maybe it was turned off during the log?

**Comment by cagnulein** [comment]
the hr device must be connected to the qz device only and also the app of the heart rate device must be fully closed

let me know

**Comment by fiddlepotter** [comment]
Ok I did both of those things and it still doesn’t work.
Oh well, it’s ok, thanks very much, I’ll just look at the watch on my wrist.


On Jan 21, 2023, at 2:20 PM, Roberto Viola ***@***.***> wrote:

﻿

the hr device must be connected to the qz device only and also the app of the heart rate device must be fully closed

let me know

**Comment by cagnulein** [comment]
if so @fiddlepotter try to disable the ios heart caching on the experimental settings and restart qz 

let me know

**Comment by fiddlepotter** [comment]
Thanks Roberto. Sorry, I was outside shovelling snow. No that didn’t work either.
 :(
-Sarah

On Jan 21, 2023, at 3:02 PM, Roberto Viola ***@***.***> wrote:

﻿

if so @fiddlepotter<https://github.com/fiddlepotter> try to disable the ios heart caching on the experimental settings and restart qz

let me know

**Comment by cagnulein** [comment]
oh ok anyway if you want we can keep checking, i mean the simple issue is that the hr is not broadcasting itself. i guess there is a simple resason for this. maybe try to reboot the devices.

**Comment by fiddlepotter** [comment]
I just re-booted the watch and the phone, that didn’t work either.
Do any of the settings under Heart Rate Options (Heart Rate Service outside FTMS, Disable HRM) need to be on?
Thanks

On Jan 21, 2023, at 3:20 PM, Roberto Viola ***@***.***> wrote:

﻿

oh ok anyway if you want we can keep checking, i mean the simple issue is that the hr is not broadcasting itself. i guess there is a simple resason for this. maybe try to reboot the devices.

**Comment by cagnulein** [comment]
nope they doesn't matter.
if you want post another debug log if you can see the hr on nrfconnect now

**Comment by fiddlepotter** [comment]
Sorry I’m not sure what you would like me to do for the debug log. Just the same thing?
Hère is a screenshot of nRF:
[image0.png]


On Jan 21, 2023, at 3:36 PM, Roberto Viola ***@***.***> wrote:

﻿

nope they doesn't matter.
if you want post another debug log if you can see the hr on nrfconnect now

**Comment by cagnulein** [comment]
hi i don't see the screenshot: you need to upload from the github interface.
for debug log, maybe check when you're also near to the bike so i can check the full scenario
thanks

**Comment by fiddlepotter** [comment]
# #
[debug-Sat_Jan_21_15_40_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10472882/debug-Sat_Jan_21_15_40_20_2023.log)

**Comment by fiddlepotter** [comment]
![Uploading 7A354992-C960-44F7-B3DB-F12648B9E405.png…]()

**Comment by cagnulein** [comment]
@fiddlepotter still dont' see the screenshot :) you have to wait to finish the upload before pushing comment :)

**Comment by fiddlepotter** [comment]
Ok, sorry, thanks for your patience!!

On Jan 21, 2023, at 3:45 PM, Roberto Viola ***@***.***> wrote:

﻿

@fiddlepotter<https://github.com/fiddlepotter> still dont' see the screenshot :) you have to wait to finish the upload before pushing comment :)

**Comment by fiddlepotter** [comment]
![D6B7250A-D454-4D72-A3BA-48F844A57F38](https://user-images.githubusercontent.com/123264040/213884489-2b9d7373-d69b-4da2-b1e0-5c9a0c9588c1.png)

**Comment by cagnulein** [comment]
i guess you add the wrong device on the heart device setting in qz. in qz i saw ID207 but on nrfconnect is different. Please try to match them

**Comment by fiddlepotter** [comment]
I don’t have any other heart rate monitor except the ID207, but it never shows up in nRF as that. Sorry, I assumed it was correct because I don’t have any any other hr device. nRF is installed on my phone, where would it find another hr device? Could it be something from another Apple device? Like apple health on my iPad, for example?


On Jan 21, 2023, at 3:47 PM, Roberto Viola ***@***.***> wrote:

﻿

i guess you add the wrong device on the heart device setting in qz. in qz i saw ID207 but on nrfconnect is different. Please try to match them

**Comment by cagnulein** [comment]
try to click on the heart monitor device in nrfconnect, maybe it will add some details about it. are you sure that the id207 it's the same "Heart rate" device that you see on nrfconnect?


> nRF is installed on my phone, where would it find another hr device? Could it be something from another Apple device? Like apple health on my iPad, for example?

nope it can't be your ipad, this is a real bluetooth device. maybe you have some neighborhood around you ? it happens a lot here on the QZ project :)

**Comment by fiddlepotter** [comment]
Haha, nope, I’m in a rural area in Canada, the nearest neighbour is almost 1 km away. :)

On Jan 21, 2023, at 3:55 PM, Roberto Viola ***@***.***> wrote:

﻿

try to click on the heart monitor device in nrfconnect, maybe it will add some details about it. are you sure that the id207 it's the same "Heart rate" device that you see on nrfconnect?

nRF is installed on my phone, where would it find another hr device? Could it be something from another Apple device? Like apple health on my iPad, for example?

nope it can't be your ipad, this is a real bluetooth device. maybe you have some neighborhood around you ? it happens a lot here on the QZ project :)

**Comment by cagnulein** [comment]
ahaha lucky you! i always dream to live in a place like this!

**Comment by fiddlepotter** [comment]
Ok now I cannot see that hr in nRF at all. 
It was there this morning and just a few minutes ago. Ok, I guess I will just use my watch on my arm. I will be ok with that! It’s just a fun extra, nothing important. 
And I love where I live, but dream to live in France, my partner is from there, so at least we visit! :)
Here is my view:
![7EDA9C97-1FCB-40C0-8B76-52A58773ED89](https://user-images.githubusercontent.com/123264040/213885115-1c849108-4f86-4172-a4fd-f85f5f61c062.jpeg)
Thanks!

**Comment by cagnulein** [comment]
wow! that's amazing! You should be really proud about your house! I live in Italy, so not bad at all too, but I love the quiet of rural areas.
I plan to travel to Canada as soon as my daughter will grow up (5 months now).

I'm sorry about your HR, maybe the easiest way to achieve this is to buy a cheap standard hr device (around 20$)

Greetings from italy!

**Comment by fiddlepotter** [comment]
Yes, I LOVE my view. This was my dream land that I managed to buy, so I am very happy to live here. :)
I have never been to Italy, although I was close, in the French Alps this summer.
I read in a comment that you had a baby and I think your whole life must be taken up with your baby and QZ! So much work :)
Well I hope you will visit Canada some time.
Thanks again, I just bought this watch hoping it would work, but I don’t need a smart watch, so maybe I will just return it and buy a heart monitor!
Thanks again for all your help, nice to "meet" you.
Sarah



On Jan 21, 2023, at 4:08 PM, Roberto Viola ***@***.***> wrote:

﻿

wow! that's amazing! You should be really proud about your house! I live in Italy, so not bad at all too, but I love the quiet of rural areas.
I plan to travel to Canada as soon as my daughter will grow up (5 months now).

I'm sorry about your HR, maybe the easiest way to achieve this is to buy a cheap standard hr device (around 20$)

Greetings from italy!
