### ISSUE TITLE
[REQ] Update test data generators for changes since c9ec71

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#1197]
Saris #1173 
BH iBoxter Plus #1185 
Sole SB700 #1196

**Comment by cagnulein** [comment]
hah you're right, i should creeate a todo list when i'm adding things :)
thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 21 gen 2023 alle ore 20:38 David Mason <
***@***.***> ha scritto:

**Comment by drmason789** [comment]
I'm working on this one.

**Comment by cagnulein** [comment]
thanks! i have to work to #1168 when i have time

**Comment by drmason789** [comment]
> thanks! i have to work to #1148 when i have time

That will be much the same as for the CompuTrainer bike.

**Comment by cagnulein** [comment]
#1148 not #1168 i edited it just after posting it :)
