### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fiddlepotter** [cagnulein/qdomyos-zwift#1199]
**Describe the bug**
Hi Roberto, Sarah from Canada again. Sorry to bother you again but since we were trying to get the heart monitor working my Peloton auto-Resistance is now not working  and I do not get the pop up that asks for permission for Peloton to send info. I deleted and reinstalled both the Peloton app and the Qz app, but nothing changed (except I was not even seeing Cadence and that came back)
I am using an iPhone 7. 
thank-You.

[debug-Sun_Jan_22_11_50_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10474836/debug-Sun_Jan_22_11_50_16_2023.log)

**Comment by cagnulein** [comment]
hi again, the problem is simple 

invalid peloton credentials during login " 401

you have to see the green check mark in qz in the peloton credentials setting

your peloton username is the nickname that you see on peloton 

be sure about upper case and spaces 

let me know 

restart qz every time you change the credentials

**Comment by fiddlepotter** [comment]
Thank you, that worked! We have two people using the app and I guess it didn’t get put in properly. I’m so sorry to have bothered you. I will send coffee money after my ride! :)
Thanks,
Sarah

On Jan 22, 2023, at 12:06 PM, Roberto Viola ***@***.***> wrote:

﻿

hi again, the problem is simple

invalid peloton credentials during login " 401

you have to see the green check mark in qz in the peloton credentials setting

your peloton username is the nickname that you see on peloton

be sure about upper case and spaces

let me know

restart qz every time you change the credentials

**Comment by cagnulein** [comment]
no problem :) you can use profiles to save the 2 peloton credentials!
