### ISSUE TITLE
Avatar don't move

### ISSUE THREAD

**Issue by gruessung** [cagnulein/qdomyos-zwift#121]
I connected my windows laptop to my Android Smartphone and zwift find my phone. 
But my Avatar don't move...what do I wrong?

**Comment by cagnulein** [comment]
Do you have VSc++ redistributable installed? There is a lot of post about
this on zwift formus

Il mar 12 gen 2021, 18:53 Alexander Grüßung <notifications@github.com> ha
scritto:

**Comment by gruessung** [comment]
Yeah this is already installed. I checked these already.

**Comment by gruessung** [comment]
![IMG_20210113_173745.jpg](https://user-images.githubusercontent.com/433331/104481447-18a0a980-55c6-11eb-8ebe-0ade4a3dd821.jpg)

This is how it looks in zwift.

**Comment by gruessung** [comment]
I try it again with my linux notebook, same problem.

In zwift i cannot see any speed.

**Comment by cagnulein** [comment]
@gruessung tell more about your setup. Where domyos is? which machine are you using for zwift? which treadmill do you have? which phone do you have?

For start, try qdomyos on an android phone, and zwift on another android phone if you have it.
Zwift on PC and Macs are more difficult to setup than a phone.

**Comment by gruessung** [comment]
First my setup: 
- Domyos T540C (from 2020)
- Bridge with app: Huawei P30 Pro
- Zwift on Win10
Result: no speed

Second try:
- bridge with app: Huawei Mate 10 Pro (my wife's phone)
- zwift: Huawei P30 Pro
Result: I got speed for 30-60 seconds, then I have to reconnect the bridge in zwift directly. 

I can also try to use the bridge on my linux notebook (ubuntu 20.04) and zwift on my phone.

**Comment by gruessung** [comment]
Third try:
- bridge on my linux notebook
- - threadmill connected
- - Badge "zwift Connection" is disabled
- zwift on my Huawei P30 Pro
- Result: zwift isn't able to find my bridge (notebook and smartphone are connected over bluetooth)

![Bildschirmfoto vom 2021-01-13 18-43-37](https://user-images.githubusercontent.com/433331/104488892-4b02d480-55cf-11eb-94d3-a5eea3d7f6dc.png)

**Comment by gruessung** [comment]
On my linux notebook i got this message in terminal hundreds of time:
`Debug: bluetooth.cpp void bluetooth::debug(QString) "Mi. Jan. 13 18:48:46 2021 1610560126152 virtualtreadmill connection error"
"Mi. Jan. 13 18:48:46 2021 1610560126152 virtualtreadmill connection error"
`

maybe this helps you...?

**Comment by cagnulein** [comment]
ok so, leave the first setup on Win10 as the last one, because Win10 has its issue with zwift and phones.
Let's go to the second setup, if i understood correctly, it was a similiar issue that i've already seen on some samsung. I think your 10 Pro can't allow 2 connections (peripheral and central) at the same time, and so it drops one.
Could you try the second scenario reversing the phones?

Which bluetooth dongle do you have on linux?

**Comment by gruessung** [comment]
I'll try the android scenario with switching the phones today or tommorow, because i need my wifes phone for this and she is working. 

My notebook has the following wireless / bluetooth chip: Intel Corporation Wi-Fi 6 AX200 (rev 1a)
https://ark.intel.com/content/www/us/en/ark/products/189347/intel-wi-fi-6-ax200-gig.html

**Comment by cagnulein** [comment]
any news @gruessung ?

**Comment by cagnulein** [comment]
feel free to reopen it @gruessung
