### ISSUE TITLE
Max Resistance

### ISSUE THREAD

**Issue by Zvirani786** [cagnulein/qdomyos-zwift#1219]
Max Resistance.xml

Bike: ProForm 400 Ri

Issue: while using zoneHR the bike will keep changing resistance to increase your heart rate to match a dedicated zone, however when you are tired and cannot keep your heart rate up resistance will change and go to max because of this the workout is ruined. At this point you cannot reach your heart rate because you cannot peddle.

Solution: create a "Max Resistance" option just like "Duration" and it can limit the resistance change so you can at least stay at a useable resistance and increase your heart rate.

**Comment by cagnulein** [comment]
@Zvirani786 maybe you need to change the description and the title :)

**Comment by cagnulein** [comment]
done! @Zvirani786 new parameter added `"maxresistance"`
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
