### ISSUE TITLE
Toorx Appready 3.0

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#122]
[hci_snoop_2021_01_13_00_35_25.zip](https://github.com/cagnulein/qdomyos-zwift/files/5809564/hci_snoop_2021_01_13_00_35_25.zip)

**Comment by Vincyc77** [comment]
I think finally i made it.
Procedure to activate the log
Switch the option ON in the developer menu but also switch off and on back again the bluetooth (this will enable the log). The log interrupt when the phone reboot
Anyway here the log file (i checked that the dimension increase during the sniff) so hopefully something inside about the session should be recorded. In case you will find 2 session inside as the 1st one the trademill disconnected (prob as i was away from the app iconsole+ too long)


[hci_snoop_2021_01_14_08_47_08.zip](https://github.com/cagnulein/qdomyos-zwift/files/5813195/hci_snoop_2021_01_14_08_47_08.zip)

**Comment by Vincyc77** [comment]
I tried both filter active and not filtered. This time i added a video for both the capture. 
I hope in this you can find the infos you need
I used wetransfer as the file are quite big
https://we.tl/t-BywlBFYDYj

**Comment by Vincyc77** [comment]
here the mssing file 
[hci_snoop_2021_01_14_21_38_14_not filt.zip](https://github.com/cagnulein/qdomyos-zwift/files/5819445/hci_snoop_2021_01_14_21_38_14_not.filt.zip)

**Comment by Vincyc77** [comment]
Here the file acquired with a oneplus one with Android6
[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/5824902/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
Thanks i will look into it tomorrow ;)

Il sab 16 gen 2021, 19:47 Vincyc77 <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
done!
