### ISSUE TITLE
[REQ] Decouple bluetooth class from UI (i.e. template managers) and add test

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#1221]
Ulterior motive: decouple bluetooth class from UI for ease of refactoring main project into separate app and lib projects.

Move the setup of the template managers into homeform and replace the direct calls to the template managers with a signal that is caught by homeform which then starts/stops the template managers.

In the test project, capture the signals in another class and assert they've been called.

**Comment by drmason789** [comment]
An additional advantage of this change is that if the enormous device detection if statement was refactored, this would test that the instruction to set up the template managers is executed when a new device is added to the set of tests.

**Comment by cagnulein** [comment]
yes it makes sense! @drmason789 do you think it could be ready for merge? spring and summer could be good months for a restructuring plan :)

**Comment by drmason789** [comment]
@cagnulein Its PR (#1223) has been waiting for you to merge for around 2 months. I've simply been keeping it up to date with the master. But in the last update it's acquired a built error for Android so I'll need to look into that.

**Comment by cagnulein** [comment]
oh sorry too many things around qz, yes you are right! i will try to check it asap!

**Comment by drmason789** [comment]
> oh sorry too many things around qz, yes you are right! i will try to check it asap!

I thought so.

 I've merged in your latest changes and now it builds.
