### ISSUE TITLE
Wrong speed after update QZ on 31 Jan 2023

### ISSUE THREAD

**Issue by istvanszegedi** [cagnulein/qdomyos-zwift#1233]
Hi Roberto, 

Something went wrong in the QZ program in the version released on January 31.
For some reason, it multiplies the speed set on the treadmill in km/h by 1.6 and shows it, and somehow also sends the incorrect speed back to the treadmill.
I also attached 2 videos. One was made using QZ and the other was made using KinoMap.
It seems that the error only occurs when using QZ.
With QZ versions before January 31, the speed setting worked fine.

Files are on my Google Drive:
https://drive.google.com/drive/folders/1nPz-R_WfYSmkMYCnVjy2jIzCN_xOxyro?usp=share_link

**Comment by cagnulein** [comment]
yes it's about this one https://github.com/cagnulein/qdomyos-zwift/commit/ecbb40a375542a588b4afeac99810b063e073ae8

do you have the new setting on the "Miles unit from the device" disabled in the fitshow setting? disable it, i guess i have to change the default one to false

**Comment by istvanszegedi** [comment]
Where should I find this in the menu tree?
I do not see

**Comment by istvanszegedi** [comment]
I found it

**Comment by istvanszegedi** [comment]
I will test tomorrow, pretty late now to test it.
Many thx

**Comment by cagnulein** [comment]
ok from the 2.12.58 that setting is default false! Thanks for the feedback @istvanszegedi

**Comment by istvanszegedi** [comment]
THX. I also tested on my treadmill. Problem solved. thx
