### ISSUE TITLE
[REQ] Display step cadence on main app

### ISSUE THREAD

**Issue by RickNY** [cagnulein/qdomyos-zwift#1242]
**Is your feature request related to a problem? Please describe.**
When doing walk/run workouts, the Apple Watch QZ app displays step cadence on the watch, but this data is not visible in the QZ app on the phone.  Using the regular cadence tile does not update with the values from the watch

**Describe the solution you'd like**
Either allow the step cadence to display in the regular cadence tile or add a new tile to display step cadence

**Describe alternatives you've considered**
None

**Additional context**

**Comment by cagnulein** [comment]
a note for me: this requires to send also this parameter from the apple watch

**Comment by cagnulein** [comment]
also @RickNY with this we can calculate Stride Length, isn't it? Since AW doesn't do this for indoor run/walk

**Comment by RickNY** [comment]
Sure, that could be useful too.. I didnt realize that AW only calculated that for outdoor

**Comment by cagnulein** [comment]
#940 yes it's about this one

**Comment by cagnulein** [comment]
done @RickNY 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
I guess we are fine with this now, am I wrong @RickNY ?

**Comment by cagnulein** [comment]
I also added the step count tile now
