### ISSUE TITLE
[bug] peloton tread target incline and speed are not correct

### ISSUE THREAD

**Issue by brianjvolz** [cagnulein/qdomyos-zwift#1249]
Using a treadmill and noticed my target incline and speed do not match the callouts in the peloton class. They seem to change correctly at the time of the call out but do not match up. This class was the best example. During the warmup. Targets vary wildly. I am not able to use the magnet feature as my incline would go to 14 when it should be flat. https://members.onepeloton.com/classes/running?utm_source=ios_app&utm_medium=in_app&modal=classDetailsModal&classId=91b81a88d3084a7aa09649ebe7905a79&locale=en-US iPhone v 2.12.29. Horizon 7.0AT

**Comment by cagnulein** [comment]
please attach a debug log from this session @brianjvolz it's the only way to understand this. Thanks

**Comment by brianjvolz** [comment]
[Logfile](https://www.dropbox.com/s/dikz0xn50xtws14/debug-Sun_Feb_5_09_10_17_2023.log?dl=0) 

> please attach a debug log from this session @brianjvolz it's the only way to understand this. Thanks

https://www.dropbox.com/s/dikz0xn50xtws14/debug-Sun_Feb_5_09_10_17_2023.log?dl=0

**Comment by cagnulein** [comment]
@brianjvolz you have the random training program enabled, please turn it off :) this explains this behaviour :)

**Comment by brianjvolz** [comment]
Thank you!

**Comment by brianjvolz** [comment]
I can’t seem to find that setting. What section is it under?

**Comment by brianjvolz** [comment]
Found it
![Uploading 90583ACF-E1C9-4A3B-ACF3-7C825BA4CC34.png…]()

**Comment by cagnulein** [comment]
i don't see the image but I trust you :)
