### ISSUE TITLE
Heart Rate Monitor

### ISSUE THREAD

**Issue by Kahabka17** [cagnulein/qdomyos-zwift#1250]
I’m trying to get my heart rate monitor working with QZ and Zwift.  I have 2 options: use the HRM band that came with my Sole F85 or Garmen Forerunner watch 235. 

I’m looking to see what the best-easiest option-connection would be.  
I tried the running chest band and when I connected it to my treadmill, QZ didn’t work-sync.  

Please help. Thank you. 
[debug-Sun_Feb_5_11_35_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10668815/debug-Sun_Feb_5_11_35_40_2023.log)

**Comment by bestwithbob** [comment]
@Kahabka17 I will be interested in the resolution as well. I have a SOLE chest strap also, but it is for the E55 elliptical.

**Comment by cagnulein** [comment]
@bestwithbob @Kahabka17 the right way to do so is:
connect the HR directly to the treadmill and leaving the heart rate belt name in QZ set to "disabled".

In the log here i saw that you keep it disabled, but the treadmill is not sending HR to the appropriate field. Was connected to the treadmill the HR band? 

Let me know

**Comment by Kahabka17** [comment]
Roberto,I tried using my chest HRM to the treadmill last night and it wasn’t registering my HR.  It was paired to the treadmill but wasn’t working.  I have to figure out how to get the strap to work with the treadmill first, or I also tried pairing my Garmin Watch 235, but that wasn’t pairing.  Nothing was working, so I believe I have to get one of those registering first before I try putting it to QZ.  I’ll keep trying this week and see. Any thoughts.. let me know. Thanks. Sent from my iPhoneOn Feb 7, 2023, at 1:39 AM, Roberto Viola ***@***.***> wrote:﻿
@bestwithbob @Kahabka17 the right way to do so is:
connect the HR directly to the treadmill and leaving the heart rate belt name in QZ set to "disabled".
In the log here i saw that you keep it disabled, but the treadmill is not sending HR to the appropriate field. Was connected to the treadmill the HR band?
Let me know

**Comment by cagnulein** [comment]
yes exactly, thanks

**Comment by cagnulein** [comment]
any news @Kahabka17 ?

**Comment by bestwithbob** [comment]
FYI - although not my issue, I ended up buying another HRM (Schoche Rhythm+2), and it works great. For what they cost, not worth opening an issue, in my opinion. I have a SOLE and older Cateye HRM, neither worked.

**Comment by cagnulein** [comment]
ok if you're with the setup :) no it's not mandatory having the hr to qz if you have on zwift. but for example you have functions like pid on heart rate that requires an heart rate to qz.

for auto inclination check this Auto Inclination on Zwift with QZ app on any bluetooth Treadmill
https://youtu.be/KTQ2n7yeDbo
