### ISSUE TITLE
[REQ] Winfita treadmill "Pause" function (T532)

### ISSUE THREAD

**Issue by laurenweinstein1** [cagnulein/qdomyos-zwift#1255]
While the QZ functions START and STOP mostly work, the PAUSE function does not work at all with this treadmill. This function would be handy to have to suspend a sequence without a full stop that resets the treadmill including incline back to 0 at the next start.

**Comment by cagnulein** [comment]
I checked the code and it seems handled by @p3g4asus (thanks again!). Could you please collect a debug log about this event? So i can check it. Thanks

**Comment by laurenweinstein1** [comment]
After further testing with other apps, I am now suspecting that this treadmill simply does not support a pause/resume function, though it does support stop/start. So this may be moot issue.

**Comment by cagnulein** [comment]
ok i'm leaving this open just in case if you will find something
