### ISSUE TITLE
[BUG] Horizon Paragon X not able to control through qz

### ISSUE THREAD

**Issue by potnus** [cagnulein/qdomyos-zwift#1256]
**Describe the bug**
Qz connects to tread, bluetooth sign is blue, but start/pause button keep blinking red. Not able to set target speed or incline. Activity never starts.
Tread: Horizon Paragon X (also enabled in Setting)
Platform: Tried both on Android and IOS, with same issue. Log below is from an IPad.

**To Reproduce**
1. Starting Tread
2. Start Qz - tread "JFTMParagon X" is immediately found
3. Trying to start Tread through qz. Nothing happens.
4. Starting Tread manually on treadmill.
5. Trying to adjust Target speed/incline on qz. Nothing happens.

**Expected behavior**
Controllable tread through qz.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
IPad 7th gen
IPadOS 16.1
Horizon Paragon X - firmware 51.06

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-ons_feb__8_09_36_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10683587/debug-ons_feb__8_09_36_05_2023.log)

**Additional context**

**Comment by cagnulein** [comment]
#637 @OswaldKolle1977 which firmware do you have on your treadmill? @potnus has the same treadmill but his treadmill is acting different from yours.
Thanks

**Comment by potnus** [comment]
Not sure if there is any other firmware. At least on Horizon page I cannot find any at all for the Paragon X.

https://support.horizonfitness.com/hc/en-us/articles/5149009125005-Software-and-Firmware-Updates

**Comment by cagnulein** [comment]
ok let's the answer from @OswaldKolle1977 if so I guess I need to handle your TM differently

**Comment by OswaldKolle1977** [comment]
> 

I think my firmware is the "older one" - because the "new Horizon-App" doesn't work with my treadmill...
Here is a Bluetooth-Sniffer Picture:

![Screenshot_20210518_212748_no nordicsemi android mcp](https://user-images.githubusercontent.com/31157456/217510114-436d7ae5-6426-4ab8-89df-376b1019b04f.jpg)

**Comment by OswaldKolle1977** [comment]
Main difference: I am using Android - not iOS

**Comment by cagnulein** [comment]
> Main difference: I am using Android - not iOS

he tried with both so i guess it's not the issue, thanks

**Comment by cagnulein** [comment]
@potnus is your treadmill working with the horizon app? because checking the frames received there are malformed packets. It seems a firmware bug on the treadmill :O

**Comment by OswaldKolle1977** [comment]
> @potnus is your treadmill working with the horizon app? because checking the frames received there are malformed packets. It seems a firmware bug on the treadmill :O

And I would say: the bug is in my treadmill

**Comment by cagnulein** [comment]
> And I would say: the bug is in my treadmill

nope your treadmill is acting like the other horizon, for example the @rickyny one. So it's just the one of @potnus Of course I can try to handle but I have to add a special case for this. So first of all let's check with the horizon app

**Comment by OswaldKolle1977** [comment]
Well - my treadmill is working with the "old" fitDisplay App -- and not working with the @Zone app (which should be the newer one I think)

**Comment by potnus** [comment]
I have tried with two separate Android devices. Same problem there.

WIth the "Horizon app", I guess you mean FitDisplay? Yes, that works fine. I can start and stop, and I can also set target speed and inclination without any problems. Only problem I noticed for that app was that if I paus by pressing the button on the treadmill, the app cannot restart. The app can only start the treadmill when it is in user/workout selection mode.

**Comment by cagnulein** [comment]
ok @potnus that's a great news. Please collect a bug report with the fitdisplay app following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by potnus** [comment]
FYI, the tread works fine with Zwift, in the sense that Zwift can pickup the speed from it.

**Comment by potnus** [comment]
> ok @potnus that's a great news. Please collect a bug report with the fitdisplay app following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Can I do this on IOS? I only have FitDisplay working on IOS.

**Comment by cagnulein** [comment]
> FYI, the tread works fine with Zwift, in the sense that Zwift can pickup the speed from it.

yes because zwift use the ftms interface, instead QZ is trying to command in using the Horizon protocol that allow us to change speed and incline via bluetooth

> Can I do this on IOS? I only have FitDisplay working on IOS.

nope only on android. So fitdisplay doesn't work on android on your end? @OswaldKolle1977 any help about this?

**Comment by OswaldKolle1977** [comment]
> > Can I do this on IOS? I only have FitDisplay working on IOS.
> 
> nope only on android. So fitdisplay doesn't work on android on your end? @OswaldKolle1977 any help about this?

Well - fitDisplay is woking on all my android devices... (it's not a useable app, but it is working)

**Comment by potnus** [comment]
> > FYI, the tread works fine with Zwift, in the sense that Zwift can pickup the speed from it.
> 
> yes because zwift use the ftms interface, instead QZ is trying to command in using the Horizon protocol that allow us to change speed and incline via bluetooth
> 
> > Can I do this on IOS? I only have FitDisplay working on IOS.
> 
> nope only on android. So fitdisplay doesn't work on android on your end? @OswaldKolle1977 any help about this?

For some reason FitDisplay tells me a message that I need to enable location permissions for the app in Android, which I have done on both devices, but it does not seem to acknowledge that. So I never get to the part where FitDisplay connects to the tread. On my IPad there was no issue with this (I could just give the app the permissions as normal)

**Comment by potnus** [comment]
> > ok @potnus that's a great news. Please collect a bug report with the fitdisplay app following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
> 
> Can I do this on IOS? I only have FitDisplay working on IOS.

Now managed to get this, from yet another Android Tablet. However, 

> > > FYI, the tread works fine with Zwift, in the sense that Zwift can pickup the speed from it.
> > 
> > 
> > yes because zwift use the ftms interface, instead QZ is trying to command in using the Horizon protocol that allow us to change speed and incline via bluetooth
> > > Can I do this on IOS? I only have FitDisplay working on IOS.
> > 
> > 
> > nope only on android. So fitdisplay doesn't work on android on your end? @OswaldKolle1977 any help about this?
> 
> For some reason FitDisplay tells me a message that I need to enable location permissions for the app in Android, which I have done on both devices, but it does not seem to acknowledge that. So I never get to the part where FitDisplay connects to the tread. On my IPad there was no issue with this (I could just give the app the permissions as normal)

Now managed to get passed that hurdle on yet another Android tablet. However, on this tablet I am still not able to connect to the tread. It can find it "Paragon X", but then when I click it FitDisplay is just processsing without getting anywhere. Again, on my IPad this works fine (I can both connect and control the tread from FitDisplay).

Attached log from Android if that is of any help.
[bugreport-CMR-W09-HUAWEICMR-W09-2023-02-08-12-57-29.zip](https://github.com/cagnulein/qdomyos-zwift/files/10685290/bugreport-CMR-W09-HUAWEICMR-W09-2023-02-08-12-57-29.zip)

**Comment by cagnulein** [comment]
@potnus actually in this bugreport I can't find the hci snoof. did you enable it? Anyway if you can't get it to work i think it could be useless.

@potnus on iOS the only way to collect data from bluetooth it's with a developer credentials (99$ for a year on app store, i don't know if it worths for you)

other question: in the debug log that you posted me, did you start the tape from the tape directly? Maybe I can the metrics overriding the frames anyway.

Also another way to achieve this: we can try to use the FTMS way with this treadmill, but I don't know if it's controllable via FTMS. A very quick check that you can do about this, it's with kinomap for example.

**Comment by potnus** [comment]
> 

Yes, I enable the snoop log, restarted, stopped it, pulled the report. But as said, I was actually never able to connect it to the tred.

" in the debug log that you posted me, did you start the tape from the tape directly? Maybe I can the metrics overriding the frames anyway.". What do you mean "start the tape"? On IOS, I can start the tread from the FitDisplay app, and then control it from FitDisplay. As long as I do not Pause it, it works fine.

No, rather not get an iOS dev account. I am not a developer, although used to be doing some coding 20 years back!

**Comment by cagnulein** [comment]
> " in the debug log that you posted me, did you start the tape from the tape directly? Maybe I can the metrics overriding the frames anyway.". What do you mean "start the tape"? On IOS, I can start the tread from the FitDisplay app, and then control it from FitDisplay. As long as I do not Pause it, it works fine.

no i mean in the debug log from QZ in the first post, did you start the tread from the tread directly? or you just tried from qz? if you started from the treadmill did you change the speed also there? it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed.

Also did you try kinomap as I suggested?

**Comment by potnus** [comment]
> > " in the debug log that you posted me, did you start the tape from the tape directly? Maybe I can the metrics overriding the frames anyway.". What do you mean "start the tape"? On IOS, I can start the tread from the FitDisplay app, and then control it from FitDisplay. As long as I do not Pause it, it works fine.
> 
> no i mean in the debug log from QZ in the first post, did you start the tread from the tread directly? or you just tried from qz? if you started from the treadmill did you change the speed also there? it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed.
> 
> Also did you try kinomap as I suggested?

I am on it! :)

**Comment by cagnulein** [comment]
ok let me know first how kinomap goes. If it goes we're safe :)

**Comment by potnus** [comment]
Android or 

> ok let me know first how kinomap goes. If it goes we're safe :)

Android or iOS, and pref?

**Comment by cagnulein** [comment]
it's the same @potnus

**Comment by potnus** [comment]
Strangely, Kinomap is working fine on the IPad (I can start workshop, adjust incline, Kinomap receives the speed, stop workout), but on Android tablet it cannot find the tread. Tried restarting tread and app few times.

**Comment by cagnulein** [comment]
ok anyway this is a good news @potnus ! It means that we can use the FTMS protocol for this. What device did you choose on Kinomap? Standard FTMS one?

**Comment by potnus** [comment]
> ok anyway this is a good news @potnus ! It means that we can use the FTMS protocol for this. What device did you choose on Kinomap? Standard FTMS one?

I choose Horizon Paragon X

**Comment by cagnulein** [comment]
> I choose Horizon Paragon X

mmm ok, so can you take a hci snoof with kinomap instead? just to be sure

**Comment by potnus** [comment]
> it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed.

:)

"it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed." - Thought you asked for them!

**Comment by potnus** [comment]
> > I choose Horizon Paragon X
> 
> mmm ok, so can you take a hci snoof with kinomap instead? just to be sure

Of course, but as I wrote, I can only get Kinomap working on iOS. On my Android tablet it does not find the tread. Still worth while?

**Comment by cagnulein** [comment]
> > it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed.
> 
> :)
> 
> "it will be nice if you can collect a debug log from qz, where you start the tread directly and go from 1-2-3-4-5-6- and so on speed with a 5 second gap between them so i can check if i can grab the speed." - Thought you asked for them!

sorry i'm going crazy, i'm following 12 tickets at the same time and I'm completely out :D

**Comment by cagnulein** [comment]
> Of course, but as I wrote, I can only get Kinomap working on iOS. On my Android tablet it does not find the tread. Still worth while? I am trying another Android device now also, to be sure...

ok if you can, try to another android device. If we can't get it, I will do the change to FTMS directly without testing it

**Comment by potnus** [comment]
> > Of course, but as I wrote, I can only get Kinomap working on iOS. On my Android tablet it does not find the tread. Still worth while? I am trying another Android device now also, to be sure...
> 
> ok if you can, try to another android device. If we can't get it, I will do the change to FTMS directly without testing it

Kinomap actually did work on my other Android device, a Samsung phone. I chose the standard FTMS. HCI snoop is 30 mb large, seems not allowed to be attached here!

**Comment by potnus** [comment]
> > > Of course, but as I wrote, I can only get Kinomap working on iOS. On my Android tablet it does not find the tread. Still worth while? I am trying another Android device now also, to be sure...
> > 
> > 
> > ok if you can, try to another android device. If we can't get it, I will do the change to FTMS directly without testing it
> 
> Kinomap actually did work on my other Android device, a Samsung phone. I choose the standard FTMS. HCI snoop is 30 mb large, seems not allowed to be attached here!

I split the zip into two zip files. GitHub does not allow upload of files with ".z01" extension so you need to rename that file back to ".zo1"  from ".zip"!

[splitArchive.zip](https://github.com/cagnulein/qdomyos-zwift/files/10686404/splitArchive.zip)
[splitArchive_Rename extension to z01 instead of zip.zip](https://github.com/cagnulein/qdomyos-zwift/files/10686407/splitArchive_Rename.extension.to.z01.instead.of.zip.zip)

**Comment by cagnulein** [comment]
ok perfect, so i'm adding a setting in order to use FTMS for horizon treadmills too. Disabled by default

**Comment by cagnulein** [comment]
done @potnus 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by potnus** [comment]
> roberto.viola83

Wonderful, thanks!

**Comment by potnus** [comment]
> done @potnus send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

Wonderful, thanks!

**Comment by cagnulein** [comment]
@potnus did you try?

**Comment by potnus** [comment]
Yes, worked out great! Much appreciated!
