### ISSUE TITLE
[BUG] [ENHANCEMENT] Domyos EL 520 remembering device on kinomap and zwift

### ISSUE THREAD

**Issue by josetta** [cagnulein/qdomyos-zwift#1257]
**Describe the bug**
After connecting to Zwift or adding equipment to Kinomap, when I turn QD-Z app, I have to connect device again, on Zwift, it is not actually big problem, but on Kinomap, I have to add new device completely, even when it has a same name and I have to go through long adding procedure. It looks to me, that there is some change in some ID, so Kinomap and Zwift don't see added device as same device...

**To Reproduce**
1. Run QD-Z app
2. Connect device to QD-Z app
3. Connect QD-Z app to Zwift or add equipment to Kinomap
4. Turn off QD-Z
5. Run QD-Z again on same mobile phone
6. Connect device to QD-Z again
7. Kinomap/Zwift is not automatically connect to QD-Z, because it will see it as new device with same name

**Expected behavior**
After next connect with same device with QD-Z app to Zwift or Kinomap, it should see it as already known device, not as a new, that you have to pair again

**Screenshots**
I will add

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Smartphone (please complete the following information):**
 - Device: HTC 650; Samsung Galaxy S10
 - OS: Android
 - Version 6.0.1; 12

**Append a debug log**
I am not sure if debug log will help you here, but here are two debug logs to kinomap:
  
[debug-Tue_Feb_7_17_19_41_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10685477/debug-Tue_Feb_7_17_19_41_2023.log)
[debug-Tue_Feb_7_17_27_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10685478/debug-Tue_Feb_7_17_27_23_2023.log)

**Additional context**

**Comment by cagnulein** [comment]
it's seems a kinomap bug actually. Also in these days Kinomap is integrating the QZ library so I guess we should use the kinomap integration directly. I will ask to the kinomap dev to talk directly here.

**Comment by josetta** [comment]
well, this problem seems to be on Zwift too, but as I wrote, I can reconnect there fast... only problem is, when sometimes it disconnects me on zwift during workout, I have to go to menu, and pair it again as new device :) it doesn't happen too much that it disconnects me during workout, but it happens :) I can add screenshots when I will get home :)
and what it means, they are integrating QZ library? Actually, domyos works native with kinomap, but my wife don't like speed of EL 520, that is speed of walk (on our old elliptical, there was speed of bike :)) and actually she don't like watt calculation ignoring resistance, that your app fixes :) so what changes there will be, if you have knowledge about it? :)

**Comment by cagnulein** [comment]
> only problem is, when sometimes it disconnects me on zwift during workout, I have to go to menu, and pair it again as new device

but do you see a different name on zwift too? which name? did you try to rename your phone to "run"  (just 3 letters) and reboot it? also did you try to enable the notifcation icon setting in the experimental settings in qz?



> and what it means, they are integrating QZ library? Actually, domyos works native with kinomap, but my wife don't like speed of EL 520, that is speed of walk (on our old elliptical, there was speed of bike :)) and actually she don't like watt calculation ignoring resistance, that your app fixes :) so what changes there will be, if you have knowledge about it? :)

hah ok got it, so nevermind :)

**Comment by josetta** [comment]
well phone is named as HTC 650 (or Samsung Galaxy S10 on main device of wife :) ), I connecting it as HTC 650, but when it disconnects, I can see HTC 650 without signal and after refresh also HTC 650 with signal also (so I can see both, old disconnected one, and new one). I can try rename it (hope you mean to rename it in BT settings in phone, not in QZ app) and no, i didn't try to enable notification icon, so I'll try that too... :) maybe it will fix both Zwift and Kinomap :) THX and I let you know

**Comment by cagnulein** [comment]
> I can try rename it (hope you mean to rename it in BT settings in phone, not in QZ app)

yes phone settings.

ok let me know both tests!

**Comment by josetta** [comment]
I tried that yesterday, changed BT name of phone to "run" and turn on android notification in experimental setting, add Run as equipment to kinomap, turned off QZ app and kinomap, turned on QZ, after connecting with EL 520, I turned on Kinomap, run workout, but it couldn't connect to actually added equipment :( Should I turned on some other settings like those options As Virtual threadmill or Virtual Elliptical (not sure of exact name of those options :))... On Zwift, it was the same, When I turned off QZ and turned it on again, I saw old connected run in devices list and new run with signal (so it didn't connect to old one but to new one :) )

**Comment by cagnulein** [comment]
probably it's due to how your phone is advertising bluetooth. do you have a privacy setting enabled for bluetooth? it could cause this issue. also on zwift why don't you use the wahoo virtual device instead?

**Comment by josetta** [comment]
on zwift not always I can see wahoo virtual and I didn't even know, what it means :) but I can try that and I let you know... 
About BT privacy settings I don't know, there are default settings and this problem I am having on android 12 samsung galaxy and android 6 htc, two diff androids and manufacters... so both kinomap and zwift behave as every run of QZ has some new identification and even when name is same, device with name "run" looks for those apps as new device :) it looks to me like that :)

**Comment by cagnulein** [comment]
qz always use the same name but some android has the ability to change the mac address at each start to it leads to the issue that you're seeing. But usually this is releated to a setting.
Also I spoke with kinomap and I already told me that this pair mechanism is not good (to use a good words). Anyway there is nothing that I can do. You don't have this behaviour if you're using a iOS device.
Anyway the wahoo device would fix this for zwift

**Comment by josetta** [comment]
ok, I checked that BT and yes, from android 6, it has this ability but I can't see posibility to turn it off 😭 ... I will check if MAC is really changed (I noticed yesterday, that Kinomap shows MAC address of device) :) Maybe I have one last Question about connecting to kinomap, I can add this elliptical only as Domyos threadmill Initial Run, I can't it add as elliptical device... is it correct connection? (I was able to add it as elliptical AnyRun A30 Xer, but this way, it didn't measured anything, I can't even start workout, because app thought, I am not moving). THX

**Comment by cagnulein** [comment]
> can add this elliptical only as Domyos threadmill Initial Run, I can't it add as elliptical device.

the right way to pair it to kinomap is pair it as an FTMS device.

**Comment by josetta** [comment]
THX, I'll check it :) have a nice day :)

**Comment by josetta** [comment]
ok, I notice that everytime, I turn on QZ and try to connect new equipment, it has new MAC address in kinomap, so that is really the reason, I have to always add new equipment... and I can't see posibility to turn it off 😭 well nevermind, I found other problem, when I add equipment as elliptical FTMS, no data are coming from QZ to Kinomap (no speed, no cadence, everything is 0.0, but it is connected and QZ app shows all data)... when I add it as threadmill, data are coming :) in attached log, there should be both threadmill and elliptical connections. THX :)
[debug-Mon_Feb_13_16_35_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10723870/debug-Mon_Feb_13_16_35_31_2023.log)

**Comment by cagnulein** [comment]
yes qz is sending only treadmill / bike / rower ftms over bluetooth :) i don't think from the kinomap point of view it makes any difference

**Comment by cagnulein** [comment]
@josetta any news?

**Comment by josetta** [comment]
hi, it has always new MAC, so if you can' fake it through app somehow, I don' think, we can do anything with it :) on my phone, I can't turn it off, I didn't find it anywhere. You can close it :)

**Comment by cagnulein** [comment]
ok, yes unfortunately the only way to fake it, it with a raspberry for example
