### ISSUE TITLE
Domyos EL500 Gears [BUG]

### ISSUE THREAD

**Issue by jjortizfernandez** [cagnulein/qdomyos-zwift#1263]
Domyos EL500 Elliptical Gears Displays "0".
Gears works OK , and changes resistance but just a "O" is displayed

**To Reproduce**
Start QzDomyos
Connect to EL 500
Change gears and check display.

**Expected behavior**
Hope to have current Gear Shown on Gears Display.

**Screenshots**

**Desktop (please complete the following information):**
 - IOS
 - Version 22

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
fixed! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS in order to have the new beta! Thanks
