### ISSUE TITLE
iOS health support withuout Apple Watch

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1268]
### Discussed in https://github.com/cagnulein/qdomyos-zwift/discussions/1265

<div type='discussions-op-text'>

<sup>Originally posted by **dalparan** February 12, 2023</sup>
I don't have AW, But I have bluetooth HR monitor, and I will not buy AW! ^^;
but I want to see workout data on my Ios devices.

Thanks for your efforts!!</div>

**Comment by Qhilm** [comment]
Is this resolved, seeing #3594 was implemented? I don't see QDomyos-Zwift listed as possible source in the Apple Health settings, hence I feel like I forgot a setting somewhere.

**Comment by cagnulein** [comment]
Yes it's in beta! Send me an email to Roberto.viola83 at Gmail.com
indicating this and I will send you the beta

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno dom 18 gen 2026 alle 14:20 Qhilm ***@***.***> ha
scritto:
