### ISSUE TITLE
Peloton auto resistance not working

### ISSUE THREAD

**Issue by hefnawim** [cagnulein/qdomyos-zwift#1269]
@cagnulein Hi Roberto, I am using Echelon bike 4s+ connected to QZ version 2.12.60 on Huawei P30 and the Peloton app on iPad pro. I am having an issue with the auto resistance that is not following even if the magnet is activated. Please see the attached debug file. Many thanks

[debug-Sun_Feb_12_11_11_52_2023.txt](https://github.com/cagnulein/qdomyos-zwift/files/10716851/debug-Sun_Feb_12_11_11_52_2023.txt)

**Comment by cagnulein** [comment]
ok thanks, i will check this asap

**Comment by cagnulein** [comment]
Hi @hefnawim in this log I don't see a peloton workout in progress. Did you start one? Did you see the popup from qz? I guess not.
Also I see in the log that you have the pzp username set, but PZP community closed the doors to 3rd party app, so you have to set the pzp username setting to "username" (just username without the "").
Let me know!

**Comment by hefnawim** [comment]
Hi @cagnulein . Many thanks for your reply. I am attaching another log file. After adjusting PZP setting, it is sometimes working. Does target resistance affect auto resistance? 
Many thanks
[debug-Mon_Feb_13_17_58_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10727683/debug-Mon_Feb_13_17_58_04_2023.log)

**Comment by cagnulein** [comment]
hi @hefnawim yes in this log i see correctly the auto resistance is working. To each target resistance change there is also a resistance change on your bike. i see that also you're changing manually the resistance, isn't it? do you feel too easy? did you change the peloton difficulty setting?

**Comment by cagnulein** [comment]
@hefnawim any news?

**Comment by hefnawim** [comment]
Many thanks @cagnulein the auto resistance seems to be working. I still have a hard time synching with the start of peloton. Sometimes I get it, and sometimes not. Cheers

**Comment by cagnulein** [comment]
on android there is the autosync setting, but you have to run qz and peloton on the same android device
