### ISSUE TITLE
[REQ] Fixed treadmill incline

### ISSUE THREAD

**Issue by nieko-nera** [cagnulein/qdomyos-zwift#1273]
Can you add manual treadmill incline, for treadmills that dont have auto incline. For example my treadmill original incline angle is 1.6 % and i have made some blocks to rise treadmill front, so it have 7 % angle.

**Comment by cagnulein** [comment]
@laurenweinstein1 , already useful this modification :)

**Comment by nieko-nera** [comment]
Is it "Inclination Overrides"? How I should use it? I set Override 0% to 7, but inclination title still says its 0. Here is log
[debug-Mon_Feb_13_18_37_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10724388/debug-Mon_Feb_13_18_37_19_2023.log)

**Comment by cagnulein** [comment]
oh right i have to add also to your treadmill! i will do tomorrow!

**Comment by laurenweinstein1** [comment]
Perhaps it should be available generically for all treadmills? I'll bet many are not well calibrated for incline and users just haven't noticed since they never actually measured, and being able to correct this for any treadmill could be very useful!

**Comment by cagnulein** [comment]
> Perhaps it should be available generically for all treadmills? I'll bet many are not well calibrated for incline and users just haven't noticed since they never actually measured, and being able to correct this for any treadmill could be very useful!

yes it was my original plan but i prefer to play it safely and test it slowly with some treadmill types:)

**Comment by cagnulein** [comment]
@nieko-nera done! 
you will see this in the 2.12.64

**Comment by nieko-nera** [comment]
Thank you.
