### ISSUE TITLE
[BUG] Missing event_type start in Fit Export

### ISSUE THREAD

**Issue by mipapo** [cagnulein/qdomyos-zwift#1279]
**Describe the bug**
The whole exported fit file has never a "start" event_type. Only stop events. So if one parses the activity correctly the activity never really starts.

Another addition I've got by one of our users:
(There is a setting in the application that sets the application to pause on start-up. If I had to guess, that's why there's a stop event at the beginning. )
But even with enabling/disabling it, the created fit file doesn't contain an start event.

**To Reproduce**
- Export a fit file
- Look into it
[Tue Feb 14 20_51_47 2023.csv](https://github.com/cagnulein/qdomyos-zwift/files/10740649/Tue.Feb.14.20_51_47.2023.csv)
(RAW https://runalyze.com/tool/fit-viewer/f7b092b1393c2fdd90bb991b82188199/view) 

**Expected behavior**
Having start events in the fit file

**Desktop (please complete the following information):**
latest

**Smartphone (please complete the following information):**
latest

**Comment by cagnulein** [comment]
Hi @mipapo are you a runalyze developer? so do you need a session start message at the very beginning? it's strange that strava, garmin connect and other doesn't require this. I have to check if this will not create issue with other platform.
Do you have a FIT file that I can use as a reference?

**Comment by mipapo** [comment]
Yes, I'm a Runalyze developer. Of course one could ignore everything if there is absolutely no start event, but well it's not correct. Talked to a Garmin developer some time a ago and she was also sure that it shouldn't be correct.
Sorry, planned to attach the fit file not the csv.

[Tue Feb 14 20_51_47 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/10740979/Tue.Feb.14.20_51_47.2023.zip)

**Comment by cagnulein** [comment]
Nice to meet you so! Ok no problem, I can add this!
Could you please forward this ticket also to your users so I can send them the new beta to test it?
Thanks

**Comment by cagnulein** [comment]
@mipapo last thing, do you have also a FIT file with the start event so I can use it as a reference? thanks!

**Comment by cagnulein** [comment]
[9339847684_ACTIVITY.fit.zip](https://github.com/cagnulein/qdomyos-zwift/files/10741047/9339847684_ACTIVITY.fit.zip)
![Screenshot 2023-02-15 at 09 43 00](https://user-images.githubusercontent.com/48216/218976945-0419892c-8bdf-4ddb-a2f4-f8234e0b4e45.png)
ok do you mean something like this @mipapo ?

**Comment by mipapo** [comment]
[43f6d50b-edb4-4f06-8c11-067732b7d51c.zip](https://github.com/cagnulein/qdomyos-zwift/files/10741134/43f6d50b-edb4-4f06-8c11-067732b7d51c.zip)
Yes that is what I mean. 
Another fit file attached (produce by an garmin device)

**Comment by cagnulein** [comment]
perfect! Done! Thanks for the feedback!

**Comment by mipapo** [comment]
> Nice to meet you so! Ok no problem, I can add this! Could you please forward this ticket also to your users so I can send them the new beta to test it? Thanks

Not sure if he is on github. If you write a short mail to michael@runalyze.com I will forward the informations to you, so you can write with him.


> Nice to meet you so! Ok no problem, I can add this! 
Thank you so much!  Didn't know about this project until yesterday. It looks awesome!
If you are interested in a direct export to Runalyze let us know :) It's a "normal" oauth2+rest api.

**Comment by cagnulein** [comment]
sent @mipapo !

**Comment by laufhannes** [comment]
Thanks for the fast fix!

Just as addition (from the second Runalyze dev): We only need a start event iff there was a stop event. So for an activity without any stop events, we don't require a start event. But at least the one example file I saw from you contained a session event with `event_type=1=stop` at the very beginning. And we once saw an original file from Garmin with tons of stop events without related start event. I can't explain how Garmin was able to read that file without skipping all those (not intended) stopped parts.

**Comment by cagnulein** [comment]
Nice to meet you @laufhannes !
Ok thanks for the addition. QZ always writes a stop event so I guess a start event is needed.
I guess the main issues with the fit file is that there isn't any *clear* description about how to use all the fit files parts, so this will lead to these kind of issues.
When I wrote the fit file writer on qz, I based my fit file from a strava example :)

**Comment by cagnulein** [comment]
done, it will be in the 2.12.66
