### ISSUE TITLE
Bike panel informations have offset of 10

### ISSUE THREAD

**Issue by fcrozat** [cagnulein/qdomyos-zwift#128]
On Domyos EB900 bike, when connected to qdomyos-zwift is connected, all informations (speed, cadence, calories, etc..) are displayed on bike panel, divided by 10. The correct informations are displayed on qdomyos-zwift. 

For instance, cadence is 5 instead of 59.
![20210114_064740](https://user-images.githubusercontent.com/215487/104823937-31bb8b80-584e-11eb-9364-c9bee2528844.jpg)
![Screenshot_20210114-064731](https://user-images.githubusercontent.com/215487/104823955-59aaef00-584e-11eb-8f69-6705b18fc3f6.jpg)

**Comment by cagnulein** [comment]
Hi @fcrozat could you send me the log about a session, i need something to identify your bike, because I guess it works fine for other domyos bike models, isn't it @kenands ?

**Comment by kenands** [comment]
Hi @cagnulein, it works fine on my bike :)

**Comment by fcrozat** [comment]
[crash.log](https://github.com/cagnulein/qdomyos-zwift/files/5832374/crash.log)

Here are the logs. I've also noticed 3 crashes of qdomyos-zwift which I kept in the log files.

**Comment by cagnulein** [comment]
Nope. Not this kind of log. I need the debug log that i create in your
download folder

Il lun 18 gen 2021, 22:01 Frederic Crozat <notifications@github.com> ha
scritto:

**Comment by fcrozat** [comment]
Sorry, I thought you wanted a HCI dump log. 
[debug-Sat Jan 16 23_05_03 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5832428/debug-Sat.Jan.16.23_05_03.2021.log)

Now I better understand what is filling my Download folder ;)

**Comment by cagnulein** [comment]
ok now i understood the issue, @kenands has a changyow bike, @fcrozat has a telink bike. so i will try to multiply by 10 only for telink bikes

**Comment by fcrozat** [comment]
Please note Decathlon (owner of Domyos) has replaced the panel of EB900 bike in the beginning of 2020 to a new version (called 2020), which I own. I don't know if they switched the provider but at least "officially supporting" applications for this bike (Kinomap or Domyos e-connected ) only work with the "new" version of the console. The "old" version doesn't work properly over Bluetooth and it can be replaced for free by them.

**Comment by cagnulein** [comment]
ok, it will be avaiable in version >= 2.2.4
i'm closing this one. feel free to reopen it in case of issue @fcrozat

**Comment by fcrozat** [comment]
I tested latest version with the fix. Speed and calories are fine but cadence is still wrong

**Comment by cagnulein** [comment]
@fcrozat i checked again the code and the multiplier is on for cadence too. What did you read now on cadence?

**Comment by fcrozat** [comment]
![Screenshot_20210122-065511](https://user-images.githubusercontent.com/215487/105508346-90f52200-5ccc-11eb-86d5-6f3e06492e74.jpg)
![20210122_065531](https://user-images.githubusercontent.com/215487/105508350-918db880-5ccc-11eb-9235-615da1925963.jpg)

here are the screenshot (taken a few seconds one after the others). I have the debug trace for this particular session, if you need it.

**Comment by cagnulein** [comment]
@fcrozat i tried now to fix a possible casting issue. We will see it in version 2.2.9

**Comment by fcrozat** [comment]
Still present with latest beta

**Comment by cagnulein** [comment]
i guess i understood the issue. on your bike firmware, the cadence, i guess, has 2 bytes for describing the cadence. Which is the max cadence value that you see on the bike display with qdomyos connected? 25.5? and the min? @fcrozat

**Comment by fcrozat** [comment]
With version 2.3.18, only cadence is wrongly displayed and indeed, panel doesn't go higher than 25 (real cadence being is 52). Lower cadence than 52 are divided by 2 on display, higher are overflowing (display at 001)

**Comment by cagnulein** [comment]
@fcrozat perfect! So i Will handle it in the next beta version: i was just waiting your confirmation ;)

**Comment by cagnulein** [comment]
@fcrozat done, it will be avaiable in the next beta

**Comment by fcrozat** [comment]
Better with 2.3.19, but not there yet. The value is now double of what it should be.

Cadence of 52 is displayed at 104 on the panel

**Comment by cagnulein** [comment]
Yes because in the last message you told me that was always the half...ok i
will remove the *2 so
R.

Il mar 16 feb 2021, 22:31 Frederic Crozat <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment]
it will be avaiable in the next beta @fcrozat

**Comment by fcrozat** [comment]
Sorry for the slow answer, everything is fine with latest beta 2.4.15.

**Comment by cagnulein** [comment]
Great! Thanks for the feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 mar 2021 alle ore 08:23 Frederic Crozat <
notifications@github.com> ha scritto:
