### ISSUE TITLE
Noble Pro Elite e8i treadmill

### ISSUE THREAD

**Issue by paulreed999** [cagnulein/qdomyos-zwift#1298]
Beta app crashing once it connects to the treadmill and tiles are shown.
[debug-Tue_Feb_21_17_49_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10796220/debug-Tue_Feb_21_17_49_08_2023.log)

**Comment by cagnulein** [comment]
@paulreed999 could you please take a full nrfconnect screenshot about it? i would like to see all the characteristics of it. Thanks

**Comment by paulreed999** [comment]
Paul

**Comment by cagnulein** [comment]
@paulreed999 you have to attach them from the github web interface, otherwise I can't see them

**Comment by paulreed999** [comment]
![IMG_3486](https://user-images.githubusercontent.com/75583792/220450650-57854f84-6328-46bd-97e5-de14bf29fa6e.PNG)
![IMG_3485](https://user-images.githubusercontent.com/75583792/220450658-2e3a245c-dbfd-4097-a800-9f1ac287d4cc.PNG)
![IMG_3484](https://user-images.githubusercontent.com/75583792/220450660-aca833d6-7c72-4401-9f36-9d361ea9ef74.PNG)
![IMG_3483](https://user-images.githubusercontent.com/75583792/220450664-728dbde4-4117-4744-8bfc-aaf45b66b7c3.PNG)

**Comment by cagnulein** [comment]
ok got the issue now, noblepro had fan to change the characteristics :D
Let me see if I can fix this. I'm gonna to bed, you will have a new build tomorrow!
Thanks for the feedback!

**Comment by cagnulein** [comment]
ok modifications done, I will send you in the morning, all the build and upload stuff takes more than an hour and today I woke up at 5 due to my baby daugther and I have no more fuel in the tank :(
Have a nice evening!
