### ISSUE TITLE
[BUG]Cadence not showing

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#1302]
**Describe the bug**
Cadence is not showing on the QZ app on IPhone while using Apple Watch to send metrics while running. 

**To Reproduce**
Start app on watch, start app on phone, start treadmill, start Zwift.

**Expected behavior**

**Screenshots**
If applica
![EA277D6E-E2D6-4C28-BE7C-51285740E129](https://user-images.githubusercontent.com/117591496/220628294-51528beb-ce1b-4f0d-b7e1-2822dd323bc0.jpeg)
ble, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

[debug-Tue_Feb_21_15_16_32_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/10804035/debug-Tue_Feb_21_15_16_32_2023.zip)

  
  
**Additional context**

**Comment by cagnulein** [comment]
@Dwhetsel fixed! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by cagnulein** [comment]
@Dwhetsel did you try?

**Comment by Dwhetsel** [comment]
I got called away yesterday. I’ll try it in a little bit.DavidSent from my iPadOn Feb 23, 2023, at 4:20 AM, Roberto Viola ***@***.***> wrote:﻿
@Dwhetsel did you try?

**Comment by Dwhetsel** [comment]
Yep, it worked. Inclination still doesn’t but I believe you said you are still working on that.Thanks,DavidOn Feb 23, 2023, at 6:21 AM, David Whetsel ***@***.***> wrote:﻿I got called away yesterday. I’ll try it in a little bit.DavidSent from my iPadOn Feb 23, 2023, at 4:20 AM, Roberto Viola ***@***.***> wrote:﻿
@Dwhetsel did you try?

**Comment by cagnulein** [comment]
@Dwhetsel inclination should already work. Could you please share a debug log where you're changing inclination from the treadmill? In the last debug log grade was always 0 from the treadmill. Thanks

**Comment by cagnulein** [comment]
@Dwhetsel any news?

**Comment by Dwhetsel** [comment]
It’s been working perfectly. ThanksOn Mar 21, 2023, at 12:37 AM, Roberto Viola ***@***.***> wrote:﻿
@Dwhetsel any news?
