### ISSUE TITLE
[BUG] Beta 2.12(498) - Incline Step : Per Facebook

### ISSUE THREAD

**Issue by paulreed999** [cagnulein/qdomyos-zwift#1303]
Incline step is set to 0;5 but tile increases by 1% at a time. Treadmill is increasing by 0.5% as expected.

[debug-Wed_Feb_22_13_02_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10804074/debug-Wed_Feb_22_13_02_31_2023.log)

**Comment by cagnulein** [comment]
Got the issue @paulreed999 
It's because other fitshow treadmill has only 1.0 step for inclination, so i put a limit for this. Let me fix this!

**Comment by cagnulein** [comment]
done @paulreed999 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by paulreed999** [comment]
Great. Thanks.

From: Roberto Viola ***@***.***>
Date: Wednesday, 22 February 2023 at 13:18
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)

Got the issue @paulreed999<https://github.com/paulreed999>
It's because other fitshow treadmill has only 1.0 step for inclination, so i put a limit for this. Let me fix this!

**Comment by cagnulein** [comment]
[btsnoop_hci (7).log.zip](https://github.com/cagnulein/qdomyos-zwift/files/10814520/btsnoop_hci.7.log.zip)

**Comment by cagnulein** [comment]
@paulreed999 they use the same command that I'm using. Probably you have to use the workout thing that they say where they can control the incline with 0.5 precision.

**Comment by paulreed999** [comment]
Ok – thanks for looking. Strange that is giving different results.



From: Roberto Viola ***@***.***>
Date: Thursday, 23 February 2023 at 14:34
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)

@paulreed999<https://github.com/paulreed999> they use the same command that I'm using. Probably you have to use the workout thing that they say where they can control the incline with 0.5 precision.

**Comment by cagnulein** [comment]
what do you mean diffrent results? In kinni you told me that you're stepping 1% to 1% or I understood it wrong?

**Comment by paulreed999** [comment]
Yes – in Kinni, I press the +1% button and treadmill increases by 1%.

In QZ – I have inclination step set to 0.5%. I press the + button in the tile and the tile increases by 1% … but the treadmill incline increases by 0.5%.

***@***.***

I have submitted a feature request to Kinni to see if they can add a 0.5% incline button – then we can look at the HCI snoop log to see what is different between the 0.5% button and 1% button?

From: Roberto Viola ***@***.***>
Date: Thursday, 23 February 2023 at 14:49
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)

what do you mean diffrent results? In kinni you told me that you're stepping 1% to 1% or I understood it wrong?

**Comment by cagnulein** [comment]
Hah! Wait I didn't get this! So QZ when it send 1% the treadmill achieve a 0.5%? so it simple to fix! Let me do this!

**Comment by paulreed999** [comment]
Yes! Sorry – your English is so much better than my Italian but I obviously didn’t explain it clearly enough for you


From: Roberto Viola ***@***.***>
Date: Thursday, 23 February 2023 at 15:10
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)

Hah! Wait I didn't get this! So QZ when it send 1% the treadmill achieve a 0.5%? so it simple to fix! Let me do this!

**Comment by cagnulein** [comment]
fixed! I will send you a new one later today or tomorrow

**Comment by paulreed999** [comment]
﻿Thank you SO much

From: Roberto Viola ***@***.***>
Date: Thursday, 23 February 2023 at 15:12
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)

fixed! I will send you a new one later today or tomorrow

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 feb 2023 alle ore 16:25 paulreed999 <
***@***.***> ha scritto:

**Comment by paulreed999** [comment]
Hi

Strange behaviour when I press the + button on inclination tile in QX.

Press + once : QZ incline tile value increases from 0.0 to 2.0. Treadmill increases by 1%
Press + again : QZ incline tile value increases from 2.0 to 6.0. Treadmill increases by additional 2%
Press + again : QZ incline tile value increases from 6.0 to 14.0. Treadmill increases by additional 7%.
Press – button on inclination tile : QZ incline tile value increases to 26.0!!!

Bug report attached

From: Roberto Viola ***@***.***>
Date: Friday, 24 February 2023 at 09:32
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 feb 2023 alle ore 16:25 paulreed999 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@paulreed999 you need to attach the bug report to github web interface. so strange anyway, i just divided the inclination following your feedback. let's check

**Comment by paulreed999** [comment]
[debug-Fri_Feb_24_09_55_46_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10823467/debug-Fri_Feb_24_09_55_46_2023.log)

**Comment by cagnulein** [comment]
i guess i understood the treadmill sends in integer a fraction of incline, so i have to divide by 2 what i'm receiving from it. this is crazy 😂

**Comment by cagnulein** [comment]
sent a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 feb 2023 alle ore 12:12 paulreed999 <
***@***.***> ha scritto:

**Comment by paulreed999** [comment]
It works… thank you Roberto. It is going to change everything for my treadmill runs…!

From: Roberto Viola ***@***.***>
Date: Friday, 24 February 2023 at 13:07
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: paulreed999 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Beta 2.12(498) - Incline Step : Per Facebook (Issue #1303)
sent a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 feb 2023 alle ore 12:12 paulreed999 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
yeah! sorry for the multiple tests, but these guys to noblepro they complicated a simple thing!

**Comment by cagnulein** [comment]
@paulreed999 are you still using the app? #1609
