### ISSUE TITLE
[BUG] Crash on iOS

### ISSUE THREAD

**Issue by Rondegregorio** [cagnulein/qdomyos-zwift#1305]
**Describe the bug**
QZ app crashed at the end of peloton workout. The app is running on iPhone 12 Pro running newest iOS software and most updated version of QZ. Happened for both cycling and treadmill workouts. 

**To Reproduce**
No specific actions. Seems random but happens towards end of workouts. 

**Expected behavior**
App closes. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.3 (20D47)
[debug-Wed_Feb_22_22_18_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10810494/debug-Wed_Feb_22_22_18_25_2023.log)
[debug-Wed_Feb_22_22_45_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10810495/debug-Wed_Feb_22_22_45_18_2023.log)
[debug-Tue_Feb_21_00_01_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10810496/debug-Tue_Feb_21_00_01_32_2023.log)
[debug-Tue_Feb_21_00_03_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10810497/debug-Tue_Feb_21_00_03_54_2023.log)
[debug-Wed_Feb_22_22_53_50_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10810498/debug-Wed_Feb_22_22_53_50_2023.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Rondegregorio thanks i don't see nothing unusual on the log, could you please check if you have a crash report https://www.macobserver.com/tips/quick-tip/how-to-find-app-crash-reports-iphone-ipad/ also?

**Comment by Rondegregorio** [comment]
On Feb 23, 2023, at 12:51 AM, Roberto Viola ***@***.***> wrote:﻿
@Rondegregorio thanks i don't see nothing unusual on the log, could you please check if you have a crash report https://www.macobserver.com/tips/quick-tip/how-to-find-app-crash-reports-iphone-ipad/ also?

**Comment by cagnulein** [comment]
@Rondegregorio you have to attach any attachments from the github web interface otherwise i can't see it

**Comment by Rondegregorio** [comment]
Here is everything I have!
[Archive.zip](https://github.com/cagnulein/qdomyos-zwift/files/10819929/Archive.zip)

**Comment by cagnulein** [comment]
@Rondegregorio 
send me an email to roberto.viola83 at gmail.com indicating this ticket, I would like to send you the beta in order to check if you're still getting the same issue.

Also here https://www.macobserver.com/tips/quick-tip/how-to-find-app-crash-reports-iphone-ipad/ is enabled the "shared with app developers" switch?

**Comment by cagnulein** [comment]
@Rondegregorio any news?
