### ISSUE TITLE
Pro-form bt log

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#131]
Attached is the bt log for a pro-form bile running with the iFit app.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5832726/btsnoop_hci.log)

**Comment by cagnulein** [comment]
hi @ptrinephi thansk for the log. Unfortunately there is no connection inside the log. Are you sure you had enabled the hci snoof log BEFORE opening the iFit app? Could you try again?
Thanks

**Comment by ptrinephi** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5834594/btsnoop_hci.log)
Try this 1

**Comment by cagnulein** [comment]
@ptrinephi nope :( nothing in this too. could you tell me exactly your steps? I guess you were missing something

**Comment by ptrinephi** [comment]
-enable dev mode
-enable bt log HCI snoop
-restart phone
-unlock phone
-turn on bt on tablet
-start iFit app on tablet
-pedal around for a little bit, maybe 20 seconds
-turn off bt HCI on phone

To extract the log fie I had to follow these instructions https://medium.com/@charlie.d.anderson/how-to-get-the-bluetooth-host-controller-interface-logs-from-a-modern-android-phone-d23bde00b9fa

that's it

**Comment by ptrinephi** [comment]
I've tried the first time on galaxy s9+, second time on s9, both running android 10

**Comment by ptrinephi** [comment]
is there a program I can use on my PC to make sure the log file has data in it?

**Comment by cagnulein** [comment]
yes @ptrinephi you can use wireshark

**Comment by cagnulein** [comment]
@ptrinephi why did you write "on tablet"? you have to do these opeartions on the same device where iFit runs!

**Comment by ptrinephi** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5834912/btsnoop_hci.log)
how about this 1?

**Comment by cagnulein** [comment]
much better! i will tell you when i'm ready to try!

**Comment by ptrinephi** [comment]
The file has cadence at constant around 50, resistance started at 1, brought up to 5 then went down 4, 3, 2 back to 1

**Comment by ptrinephi** [comment]
[debug-Tue Jan 19 09_19_26 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5837950/debug-Tue.Jan.19.09_19_26.2021.log)
[debug-Tue Jan 19 10_38_37 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5837951/debug-Tue.Jan.19.10_38_37.2021.log)
[debug-Tue Jan 19 09_24_36 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5837953/debug-Tue.Jan.19.09_24_36.2021.log)
Here are 3 log files

**Comment by ptrinephi** [comment]
[debug-Tue Jan 19 11_15_40 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5838126/debug-Tue.Jan.19.11_15_40.2021.log)
cadence between 49-53 for about 1minute

**Comment by ptrinephi** [comment]
[debug-Wed Jan 20 11_58_03 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5845023/debug-Wed.Jan.20.11_58_03.2021.log)
[debug-Wed Jan 20 11_54_38 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5845024/debug-Wed.Jan.20.11_54_38.2021.log)

**Comment by ptrinephi** [comment]
[iFit Watt table - Sheet1.csv.txt](https://github.com/cagnulein/qdomyos-zwift/files/5846480/iFit.Watt.table.-.Sheet1.csv.txt)
iFit watt table

**Comment by cagnulein** [comment]
@ptrinephi i was looking your last log, and i saw the watt value in the log. Don't you see it in the UI? It seems also correct to me looking to your csv. Maybe am i lost something?

**Comment by ptrinephi** [comment]
[Uploading debug-Thu Jan 21 10_22_49 2021.log…]()

**Comment by ptrinephi** [comment]
[Uploading debug-Thu Jan 21 10_22_49 2021.log…]()

**Comment by ptrinephi** [comment]
[debug-Thu Jan 21 10_22_49 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5852167/debug-Thu.Jan.21.10_22_49.2021.zip)

**Comment by ptrinephi** [comment]
[debug-Fri Jan 22 09_27_05 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5857559/debug-Fri.Jan.22.09_27_05.2021.zip)

Included are 2 logs showing inconsistent speed at the beginning, it appears the speed becomes more stable and accurate after about 30sec of running
The latest log ends in an app crash which may be related to the fitbit HR.

**Comment by ptrinephi** [comment]
[debug-Fri Jan 22 09_43_04 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5857575/debug-Fri.Jan.22.09_43_04.2021.log)
App crash log

**Comment by ptrinephi** [comment]
[debug-Fri Jan 22 23_45_25 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5859868/debug-Fri.Jan.22.23_45_25.2021.zip)
2 app crash reports from my asus phone running android 6

**Comment by cagnulein** [comment]
Dis you still send the ANR?

Il lun 25 gen 2021, 18:52 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
Yes, they're actually from 2 days ago, I just forgot to click "submit" 
!! but the crash still occurs

------ Original Message ------

**Comment by cagnulein** [comment]
but you have another device isn't it? or you're blocked?
i mean fixing android 6 compatibility it's not a priority for me now ;)
but i will definetely do!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 gen 2021 alle ore 20:17 3phi <notifications@github.com> ha
scritto:

**Comment by ptrinephi** [comment]
I do have another device, android 7 also crashes sometimes

------ Original Message ------

**Comment by cagnulein** [comment]
Ok I will try to find some time to check it

Il lun 25 gen 2021, 20:23 3phi <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
Are you sure about your device has android 6? I can't find any anr in the
last 14 days for android 6

Il lun 25 gen 2021, 20:23 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
it's 6.0.01 to be exact on asus zen phone.  I've also noticed that on 
android 7 and 6 the app has more difficulty connecting to the HR 
monitor.  On android 10 I have no issue.  Coincidence? maybe!

------ Original Message ------

**Comment by cagnulein** [comment]
@ptrinephi nothing, i can't find anything about your devices. Could you please make it in this way? 
Let's become developer to your phone. When the crash happens, generate a bug report from the developer settings and send me it.
Thanks

**Comment by cagnulein** [comment]
as i said on messenger, i guess your problem is about the wake lock mechanism. I added a new option in the 2.3.1 to disable it by the setting. Of course you need to keep your display on during the workout (for example disabling the power saver setting on your android device)

**Comment by cagnulein** [comment]
@ptrinephi remember to close it if you will not have this issue anymore ;)
