### ISSUE TITLE
[BUG] IFit app

### ISSUE THREAD

**Issue by paulreed999** [cagnulein/qdomyos-zwift#1313]
Hi Roberto

- I have QZ on iOS (iPhone 14).
- I have iFit installed on Android Tablet 
- As you know, I have a Noble Pro Elite e8i treadmill - which now works perfectly with Zwift, including auto-incline.

I want to use QZ as the bridge between treadmill and iFit app on Android.
[Uploading debug-Sat_Feb_25_14_52_17_2023.log…]()

I open QZ, wait for tiles - treadmill connected.
I have virtual device, virtual bluetooth and virtual iFit switched on in QZ
I open iFit app on Android but it does not connect to QZ

I can see QZ visible in nrfConnect on Android tablet.

**Comment by cagnulein** [comment]
hi @paulreed999 the debug log is truncated, could you please upload it again?

**Comment by paulreed999** [comment]
[debug-Sat_Feb_25_14_52_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10831599/debug-Sat_Feb_25_14_52_17_2023.log)

**Comment by cagnulein** [comment]
sorry @paulreed999  I didn't remember that I didn't add the ifit for treadmill yet. follow this for update. #1065 
Thanks

**Comment by paulreed999** [comment]
No problem. Thanks.
