### ISSUE TITLE
Issue with Peloton ride 1/21/23

### ISSUE THREAD

**Issue by sparkyparkes** [cagnulein/qdomyos-zwift#1315]
[debug-Sat_Feb_25_10_49_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10831918/debug-Sat_Feb_25_10_49_54_2023.log)
Per our Facebook discussion, here is the debug log from this ride. - Ben Parkes

**Comment by cagnulein** [comment]
got the issue, check this https://www.facebook.com/groups/149984563348738/posts/592495512430972/?__cft__[0]=AZXhjzCLfO1MFkEfX61yyS3SqQfiBf1AXl96W2m6w-tjwliFg2Y4B5ExJaRIXPEgjygsC-ls9JRS4TOvWmaT8w2I5k4KzCau8CwG9BB62N8KM0IfQU-xjd7EonbUxobUyAGIu__BEzciWBQL6gBYpxlL&__tn__=%2CO%2CP-R
