### ISSUE TITLE
Resistance on Zwift or Rouvy AR or FullGaz doesn't work (EB900 bike)

### ISSUE THREAD

**Issue by fcrozat** [cagnulein/qdomyos-zwift#132]
Resistance (Controllable bluetooth "device") doesn't seem to work with either Zwift or Rouvy AR on Android:
- on Zwift, it takes a long time for the applicaiton to detect my device (Galaxy S9+) as Controllable but once it is connected, resistance doesn't change at all when riding (I'm new to Zwift, so I might do things incorrectly).
- on Rouvy AR, the device is never detected as Controllable
- on Fullgaz, device is detected as Controllable but again, no resistance change seems to be send from application back to qdomyos-swift.

Changing resistance directly on the bike or qdomyos-zwift works fine, so the issue seems to be on the exported bluetooth interface by qdomyos-zwift.
[debug-Tue Jan 19 06_56_31 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5836821/debug-Tue.Jan.19.06_56_31.2021.log)

**Comment by cagnulein** [comment]
ok let's start from zwift: i don't see any activity from zwift to my app in the log. Are you sure controllable is on? do you have peloton setting to off? Watt are displayed correctly on zwift?

**Comment by fcrozat** [comment]
Not sure how I did it tonight but Zwift was able to connect at least one time fully on the application, and this time, controllable was on and working (bike when immediatly to resistance 8). After restarting Zwift, I couldn't reconnect at all, even after restarting qdomyos-zwift. 

It is a bit unclear in the current UI if the Zwift icon is supposed to be enabled when qdomyos-zwift is "advertising" the bridge or when the bridge is being used by Zwift (or some other apps).

**Comment by cagnulein** [comment]
the zwift icon on android >8 is completey unreliable because of an android bug, so don't look at it :)
the behaviour that you saw it's something i'm aware of. when you have this kind of issue, try to reboot (or at least put in airplane mode and back) the phone. it should work again. Samsung phone have very bad bluetooth stack. If you have also a no-samsung device, give it a try! even if it is an older one!

**Comment by fcrozat** [comment]
Understood for the icon.

I only have android devices (phone and tablet). I'll try to use kinomap instead of Zwift, since it supports both natively too, so compare the behavior with or without qdomyos-zwift.

**Comment by cagnulein** [comment]
yes android device are fine, just try one not samsung :) kinomap is different because it's not reshare the bluetooth as i do in qdomyos, so it will work for sure (basically it's just works as the connection to the bike from qdomyos does)

**Comment by fcrozat** [comment]
Sorry, I was unclear, I plan to bind kinomap to qdomyos (since it should also FTMS protocol) instead of directly on the bike, so we can check if there are some inconsistency between your reverse engineering and their "official" support (unless you already tried that ;)

**Comment by cagnulein** [comment]
Oh ok i got it now ;)

Il mer 20 gen 2021, 10:50 Frederic Crozat <notifications@github.com> ha
scritto:

**Comment by fcrozat** [comment]
I did some tests with kinomap : I can confirm no resistance seems to be sent to QZ. On the same session, zwift properly detected controllable, initially sent a resistance of 5 and then nothing.

**Comment by cagnulein** [comment]
Could you send me the qdomyos-zwift logs of these sessions?
I guess with ZWIFT you should play with ZWIFT resistance ratio setting

Il lun 15 feb 2021, 07:50 Frederic Crozat <notifications@github.com> ha
scritto:

**Comment by fcrozat** [comment]
[debug-Mon Feb 15 07_09_41 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5991742/debug-Mon.Feb.15.07_09_41.2021.log)
Debug log attached

**Comment by cagnulein** [comment]
@fcrozat in this log Zwift send me always 0%. So that's normal that you don't see any resistance change. Do you have a log longer?
