### ISSUE TITLE
Low Speed based on calculation on wattage

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1325]
[debug-Di__Feb__28_19_46_22_2023 2023-02-28 20_01_19.zip](https://github.com/cagnulein/qdomyos-zwift/files/10860025/debug-Di__Feb__28_19_46_22_2023.2023-02-28.20_01_19.zip)

**Comment by cagnulein** [comment]
original posted by @Bepo7012

**Comment by cagnulein** [comment]
issue stars here 20:28:49

**Comment by cagnulein** [comment]
@bepo7012 fixed. It was due to the fact that the speed for several seconds was with the exact same value. I had a timer that check this but since it found always at the same value, it decreases the acceleration. It should be fixed from the 2.13.4 and above.
Let me kow

**Comment by Bepo7012** [comment]
@cagnulein Great, thanks!
