### ISSUE TITLE
Echelon exp beta not sending info to bike

### ISSUE THREAD

**Issue by Lilyttzo** [cagnulein/qdomyos-zwift#1329]
[debug-Wed_Mar_1_22_36_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10868427/debug-Wed_Mar_1_22_36_33_2023.log)
 
I haven't used the bike in 5 months. I used the echelon app and I was able to see the cadence and resistance no problem.

**Comment by cagnulein** [comment]
@Lilyttzo got your issue. In the experimental settings, disable all the fake device setting (fake bike and fake elliptical both) and restart QZ
Let me know

**Comment by Lilyttzo** [comment]
![Screenshot_20230301_234519](https://user-images.githubusercontent.com/126754229/222364171-9dfc1d71-2ce1-447f-841f-5a2cbaaad503.jpg)
You are the best. All is back to normal!! Thank you thank thank you!!!
