### ISSUE TITLE
Flywheel 1 - Does not connect in the app

### ISSUE THREAD

**Issue by randysok** [cagnulein/qdomyos-zwift#133]
It finds and runs through all bluetooth devices in the home but does not connect to the Flywheel 1 bluetooth device connection that it finds.

**Comment by cagnulein** [comment]
yes because you need the beta version 2.2.4 (android and ios).
if you want, i could add you to the beta testers

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 gen 2021 alle ore 17:28 randysok <notifications@github.com>
ha scritto:

**Comment by randysok** [comment]
Beta version would be great! Thanks Robert

**Comment by cagnulein** [comment]
did you write me on messenger, isn't it?

**Comment by randysok** [comment]
Hi Robert! Yes I did :) and thank you. Can't wait to try the Beta version,
let me know whenever it's available as I'd love to get on the flywheel to
give it a shot!

-Randy

**Comment by cagnulein** [comment]
It's already available! @randysok

**Comment by randysok** [comment]
That's awesome Robert!! Is there a place I can download the Beta Version? I
logged into my Apple Developer account but not sure where to look to get
the latest version of the iOS app :)

**Comment by cagnulein** [comment]
I don't remember if you send me your email address to
roberto.viola83@gmail.com
In case do it again

Il gio 21 gen 2021, 06:40 randysok <notifications@github.com> ha scritto:

**Comment by randysok** [comment]
Hi Roberto!

Per your prior email, sending an email with my email address here :)

randysok@gmail.com

Best Regards,
Randy
