### ISSUE TITLE
JLL T-350 Treadmill > Zwift [BUG]

### ISSUE THREAD

**Issue by Billpherry** [cagnulein/qdomyos-zwift#1339]
I have the above treadmill and am interested in using it with Zwift, being able to control the elevation.

I have tried to connect the app with no luck and it seems it fails to be found via nrfconnect too, the treadmill does not have ftms or WiFi, I believe the Bluetooth is built in for audio but understand this means it may still be possible?

Please let me know if there is any information you need, more than happy to poke around and figure it out!

To confirm I was unable to pick up the device in nrfconnect, I checked the Bluetoothac address when the treadmill was connected to my mobile, and when then disconnected, couldn't see nrfconnect pick up the same device Mac address.

**Comment by cagnulein** [comment]
hi @Billpherry do you have an app that works  with your treadmill?

**Comment by Billpherry** [comment]
Hey @cagnulein, no it doesn't that I'm aware of. Any documentation I found shows that Bluetooth is for audio so am unsure if it can send receive data... It's not a huge concern as I'm considering an upgrade in treadmill but it would be cool to get used to this functionality before I do upgrade.

**Comment by cagnulein** [comment]
the only way to give you a "smart" thing to your treadmill is doing this #627

**Comment by Billpherry** [comment]
Hey Roberto,

Thanks for your help, appreciated. I'm on the verge of a treadmill upgrade
so am currently looking out for models that have FTMS and will integrate
with your app, I'm very excited to start using it!!

Can I ask if you have a list of preferred models that work with the app?

Kind regards,

Phill

**Comment by cagnulein** [comment]
hi check this https://github.com/cagnulein/qdomyos-zwift/wiki/Equipment-Compatibility !

**Comment by Billpherry** [comment]
Huge thanks for your help Roberto, I notice that the Nordictrack
models seem popular, can I assume that any models released after the ones
listed would be supported as long as they have FTMS? I had my eye on the
Commercial 2950 which has been mentioned very briefly in some of the github
threads.

**Comment by cagnulein** [comment]
@Billpherry the main purpose of QZ is connecting to devices that are NOT supporting FTMS :) So if you buy a FTMS one is easy of course :) 
But watch out: not all the FTMS can have auto speed or auto incline. So I suggest to ask on the QZ Facebook group about this, so you can also ask about the feeling of the users about a particular model
