### ISSUE TITLE
Error during compile from source raspberry 

### ISSUE THREAD

**Issue by mauroski** [cagnulein/qdomyos-zwift#135]
Hi  Roberto 
when do "qmake" in raspberry pi3 latest release appear  this error:

**Info: creating stash file /home/pi/qdomyos-zwift/src/.qmake.stash
Project ERROR: Unknown module(s) in QT: networkauth**

Previously I had compiled correctly, any ideas?
Tanks
Mauro

.qmake.stash content:

QMAKE_CXX.INCDIRS = \
    /usr/include/c++/8 \
    /usr/include/arm-linux-gnueabihf/c++/8 \
    /usr/include/c++/8/backward \
    /usr/lib/gcc/arm-linux-gnueabihf/8/include \
    /usr/local/include \
    /usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed \
    /usr/include/arm-linux-gnueabihf \
    /usr/include
QMAKE_CXX.LIBDIRS = \
    /usr/lib/gcc/arm-linux-gnueabihf/8 \
    /usr/lib/arm-linux-gnueabihf \
    /usr/lib \
    /lib/arm-linux-gnueabihf \
    /lib
QMAKE_CXX.QT_COMPILER_STDCXX = 201402L
QMAKE_CXX.QMAKE_GCC_MAJOR_VERSION = 8
QMAKE_CXX.QMAKE_GCC_MINOR_VERSION = 3
QMAKE_CXX.QMAKE_GCC_PATCH_VERSION = 0

**Comment by cagnulein** [comment]
I think you need libqt5networkauth5

Il dom 24 gen 2021, 20:57 mauroski <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
libqt5networkauth5-dev

**Comment by mauroski** [comment]
Tank Roberto,, now compile fine! today I try it with fassi treadmill...
Mauro

**Comment by cagnulein** [comment]
@mauroski is it working for you? another user tell me this #138
