### ISSUE TITLE
Resistance dropping or going higher when using QZ + Zwift/Rouvy[BUG]

### ISSUE THREAD

**Issue by Roger-Smith111** [cagnulein/qdomyos-zwift#1356]
**Describe the bug**
When Riding in Zwift or Rouvy, my resistance gets all messed up. By default, I start at 14. After a few minutes, my resistance shoots up to 32 or drops down to 1 and I cannot get it back to where I want it. I need to restart QZ and Zwift to get it to work again.
I'm using an Echelon EX3.
Running QZ on a Google Pixel 7
Running Zwift/Rouvy on a Samsung S9+

**To Reproduce**
1. Open Zwift
2. Start any workout
3. The time varies but after a while the resistance shoots down to 1 or up to 32 and I cannot change the resistance through QZ or by manually turning the resistance knob on the bike.

**Expected behavior**
I expect the resistance to stay stable or vary in ERG mode.

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Mon_Mar_13_20_00_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10962918/debug-Mon_Mar_13_20_00_27_2023.log)

**Comment by cagnulein** [comment]
Hi @Roger-Smith111 you have the gears from bike setting enabled in the echelon setting. This is an experimental setting, so turn it off if you don't want to debug and help me with feature. 

Let me know

**Comment by Roger-Smith111** [comment]
I'm willing to help you make your app better.
Let me know how I can be of assistance.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
Ok in case I have to send you the new version because I guess I already fixed this one in the newest beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

The ticket about this setting is #1299

**Comment by cagnulein** [comment]
ok @Roger-Smith111 I guess I found the issue and I fixed it. The fix will be in the 2.13.14 and above. Thanks!

**Comment by Roger-Smith111** [comment]
okay great, I will try it once that version is installed and let you know.
thanks again for the great work on the application.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
@Roger-Smith111 any news?

**Comment by Roger-Smith111** [comment]
It does it about %20 of the time during workouts. I have not seen a pattern yet when it does it. A quick fix is to reset the resistance in the app and it comes back to normal. Keep in mind this happens in Rouvy so I can't speak for Zwift.

Apart from this little issue, it works great in Rouvy.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
if you want @Roger-Smith111 if you provide me a debug log with the issue i can check it. thanks

**Comment by Roger-Smith111** [comment]
ok great, I will send you the log once the issue happens again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
