### ISSUE TITLE
Negative grade on zwift doesn't decrease resistance on domyos bike 500, and grade send by zwift is about 50% of real value

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#136]
Hi @cagnulein, 

like I said you in messenger I tried to fixed this issue by myself ^^

I changed few lines of code below on calculation of the grade and resistance:

_ First change: is about format of "(**u**int8_t)(resistance * bikeResistanceGain)" replace by "(int8_t)(round(resistance * bikeResistanceGain)" in the aim to get negative value of grade and round it to the nearest integer.
_ Second change is about resistance variable, I multiplied it by 1.5, I think is the best setting for my domyos bike 500 but I'm not sure it it's the case for other bikes, you should maybe add an input value in settings like as Gain and Offset.
Zwift send the grade at 50% of the value showed in the app
https://forums.zwift.com/t/negative-grades-received-via-ftms-are-less-than-zwift-ui-display/100073,
I don't multiplied it by 2, if it was the case, I will reached the max resistance of my bike easily lol
_ Third change: I added 2 conditions for minimum and maximum resistance of my bike, I'don't know if it necessary you are the expert :D 

here is debug file:
[debug-dim. janv. 24 18_11_20 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5863067/debug-dim.janv.24.18_11_20.2021.log)

I didn't do a pull request because I'm not sur if changes I done it's correct but it works. 
And I have an other issue I couldn't update app on my raspberry, I get this message: Project ERROR: Unknown module(s) in QT: networkauth
![qmake issue](https://user-images.githubusercontent.com/16349940/105641966-10c6ec00-5e87-11eb-835a-d777046184d0.JPG)
I think I need to update qt but I don't how to do it correctly :/

```
          else if((char)newValue.at(0) == FTMS_SET_INDOOR_BIKE_SIMULATION_PARAMS) // simulation parameter
         {
             emit debug("indoor bike simulation parameters");
             reply.append((quint8)FTMS_RESPONSE_CODE);
             reply.append((quint8)FTMS_SET_INDOOR_BIKE_SIMULATION_PARAMS);
             reply.append((quint8)FTMS_SUCCESS);

             int16_t iresistance = (newValue.at(3) + (newValue.at(4) << 8));
             emit debug("new requested resistance zwift erg grade " + QString::number(iresistance));
             double resistance = ((double)iresistance * 1.5) / 100.0; 
   			 if((int8_t)(round(resistance * bikeResistanceGain)) <= ((bikeResistanceOffset + 1)*(-1)))
			 {
				 Bike->changeResistance(1);
			 }
			else if(((int8_t)(round(resistance * bikeResistanceGain)) + bikeResistanceOffset + 1) > 15)
			{
				
				 Bike->changeResistance(15);
			}
			else 
			{
				 Bike->changeResistance((int8_t)(round(resistance * bikeResistanceGain)) + bikeResistanceOffset + 1);
				 emit debug("calculated erg grade " + QString::number(resistance));
			 }
```

**Comment by cagnulein** [comment]
I guess you should need libqt5networkauth5-dev

**Comment by kenands** [comment]
You are right, it works with libqt5networkauth5-dev installed 😄

**Comment by cagnulein** [comment]
@kenands did you already try it out? i have to trust you, so i will wait your confirmation ;)

**Comment by kenands** [comment]
@cagnulein  Yes i tried it, there is the debug file, you can check :)
I don't know if you are in contact with other Domyos bike users, we can ask them to try

**Comment by cagnulein** [comment]
i guess you're the top domyos bike user, so they will have to follow your development :D

**Comment by cagnulein** [comment]
i think we can avoid the check that you did on min and max resistance: is alread been done on domyosbyke.cpp

**Comment by kenands** [comment]
I put it to be careful lol if it's check on domyosbyke.cpp you can delete it, you are the expert 😄

**Comment by cagnulein** [comment]
added to version 2.2.13
@kenands just put an eye on this commit, just to double check if it's correct :)

**Comment by fcrozat** [comment]
> @cagnulein Yes i tried it, there is the debug file, you can check :)
> I don't know if you are in contact with other Domyos bike users, we can ask them to try

I'll be happy to test on Domyos EB 900 ;)

**Comment by cagnulein** [comment]
@fcrozat are you using the current commits now on your raspberry? @kenands has some issue on connecting to the bike with the last commit. Could you double check it?

**Comment by fcrozat** [comment]
Sorry but I'm on Android (Samsung), so it will need to wait until you release a Android build :(

**Comment by cagnulein** [comment]
@kenands  i guess zwift has changed something. now i see this

Debug: ../src/bluetooth.cpp void bluetooth::debug(QString) "Wed Mar 3 20:04:32 2021 1614801872734 new requested resistance zwift erg grade 8"
Debug: ../src/bluetooth.cpp void bluetooth::debug(QString) "Wed Mar 3 20:04:32 2021 1614801872734 calculated erg grade 0.12"

it seems that the value is divided by 100. isn't it? does it work well on your setup?

**Comment by kenands** [comment]
Hi @cagnulein, I don't know, I will try.

**Comment by kenands** [comment]
It works well on my setup.

Below grade 372 means 3.72%, in your exemple "grade 8", I think it means 0.08% on Zwift.
I tried with Zwift on my W10 laptop and on my android phone.


`Debug:   client sends  write request for handle 7
Debug: bluetooth.cpp void bluetooth::debug(QString) "jeu. mars 4 10:02:23 2021 1614848543888 characteristicChanged 10969 11 00 00 74 01 28 33"
Debug: bluetooth.cpp void bluetooth::debug(QString) "jeu. mars 4 10:02:23 2021 1614848543889 indoor bike simulation parameters"
Debug: bluetooth.cpp void bluetooth::debug(QString) "jeu. mars 4 10:02:23 2021 1614848543889 new requested resistance zwift erg grade 372"
Debug: bluetooth.cpp void bluetooth::debug(QString) "jeu. mars 4 10:02:23 2021 1614848543890 calculated erg grade 5.58"
Debug: bluetooth.cpp void bluetooth::debug(QString) "jeu. mars 4 10:02:23 2021 1614848543890 virtualbike::writeCharacteristic Unknown Service  80 11 01"`

**Comment by cagnulein** [comment]
ok but so the resistance value will be always lower than 0 if you didn't put a resistance gain of 100 or similar, isn't it? which is your resistance gain in your setup @kenands ?
The resistance gain default is 1 now, so the echelon users have to change manually in order to get it works. This is why i asked you about your setup ;)

**Comment by kenands** [comment]
I let all setings by default.
So offset is 5 and gain is 1.
Zwift send 372 for a grade of 3.72, I multiplied by 1.50 to add 50% on script (I didn't think to use gain value for that :/ maybe need to put it to 1 on script), this give me 5.58.
and with the offset of 5, it give 10.58, but there is a round function also ^^ so my resistance on bike is 11.

**Comment by cagnulein** [comment]
mmm so probably the user was going on a flat surface...it's very strange, it seems that there is a 100 factor from you and the other user :O i will let you know. Thanks!

**Comment by kenands** [comment]
Maybe.
 I tried with an older version of QZ. Do you think, I need to try with your last version ?

**Comment by cagnulein** [comment]
No, i don't think that it's the issue. Because i didn't change anything there :)
