### ISSUE TITLE
Power calculation - domyos bike 500

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#137]
Hi @cagnulein,

Is it possible to replace calculation of power of domyos bike 500 by formula below.
I did an excel file like Mark Logan:
[power domyos bike 500.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/5863093/power.domyos.bike.500.xlsx)

I created formula based on value of the power table we used on app, I didn't have other referencies :/ I unsubscried Kinomap.
With formula, power value is more continuous than the power table. Because on power table, differences between values in each step are little bit high so it's difficult to hold target power value on training mode of zwift.

```
#include <math.h>

	v=((10.39 + 1.45 * (currentResistance()-1)) * (exp(0.028 * (double)(currentCadence()))));
        return v;
```

Thanks

**Comment by cagnulein** [comment]
done, it will be avaiable in the next beta 2.2.13
