### ISSUE TITLE
VZFit and QZ: Incorrect kilometers

### ISSUE THREAD

**Issue by Jazzy0806** [cagnulein/qdomyos-zwift#1382]
**Describe the bug**
When I start a session on the Apple Watch, I'm shown fewer miles via QZ than in VZfit.

**To Reproduce**
1. Open QZ app on iPhone
2. Start session on Apple Watch
3. Open VZfit and connect with QZ via iPhone
4. End session

**Expected behavior**
The kilometers shown should be the same.

**Smartphone (please complete the following information):**
 - iPhone 13 Plus, latest OS
 
**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
The sessions are doubled and show up twice in Strava/Health and on the Apple Watch

[debug-Mi__März_29_16_44_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11102462/debug-Mi__Marz_29_16_44_08_2023.log)

Thanks for your help!

**Comment by Jazzy0806** [comment]
@cagnulein Will load the debug of using "Speed calculates on power" later. I'm at the gym right now 😂
But nothing's going to happen there. The bike won't move in VZfit with this feature enabled.

**Comment by cagnulein** [comment]
@Jazzy0806 

> But nothing's going to happen there. The bike won't move in VZfit with this feature enabled.

that's the reason why I would like to check the debug log, it should move :) so I guess you have some settings wrong. Also speed calculates over power should be always enabled in order to have a realistic speed to report to vzfit. I added this settings expecially for vzfit 2 years ago :)

**Comment by Jazzy0806** [comment]
Here's the log. After pedaling 30 seconds it all of a sudden moved. Seems to work now. Will keep a eye on it tomorrow, it's bedtime here. 
[debug-Mi__März_29_19_40_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11103872/debug-Mi__Marz_29_19_40_49_2023.log)

**Comment by Jazzy0806** [comment]
The kilometers don't match even with "Speed calulates on Power" enabled. QZ says 0,79 kilometers, VZFit says 1,11 kilometers. Miles output is disabled in the settings.

**Comment by cagnulein** [comment]
@Jazzy0806 we need to know from @emalafeew how they calculate them. For what I knew, VZFit used the speed from QZ 2 years ago. I don't know how they calcualte now. Maybe they changed their algorithm and so it's impossible to have the same value. But if it's so, it seems to me a VZfit bug rather than something that I can do on QZ :)

**Comment by Jazzy0806** [comment]
Today I tried again. Opened QZ on my iPhone, started it on Apple Watch and connected to VZfit. Bike wouldn't move at all. Not a single meter, just pedaling in place. Same setting, nothing changed.

[debug-Do__März_30_16_58_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11113030/debug-Do__Marz_30_16_58_31_2023.log)

**Comment by cagnulein** [comment]
@Jazzy0806 I guess I understood this. Set disable to the cadence sensor setting in QZ under accesories (since your bike provide already the cadence). Let me know if it's better (at least with the speed thing).

For the distance thing we have to wait Vzfit (i asked him to check this ticket on messenger, if you can do the same, it's better, thanks)

**Comment by Jazzy0806** [comment]
> @Jazzy0806 I guess I understood this. Set disable to the cadence sensor setting in QZ under accesories (since your bike provide already the cadence). Let me know if it's better (at least with the speed thing).
> 
> For the distance thing we have to wait Vzfit (i asked him to check this ticket on messenger, if you can do the same, it's better, thanks)

Ah, you're right! The cadence sensor is still on the pedal. Oops! Will try it right now.

**Comment by cagnulein** [comment]
@Jazzy0806 in this log I still see the cadence sensor setting set to the bryton cadence sensor. Please set it to disabled and press ok and restart QZ. This is the right way to do this test. Thanks

**Comment by Jazzy0806** [comment]
> @Jazzy0806 in this log I still see the cadence sensor setting set to the bryton cadence sensor. Please set it to disabled and press ok and restart QZ. This is the right way to do this test. Thanks

That's exactly what I did. I set it to disabled, closed the app, restarted it. The battery is out of the sensor.

**Comment by cagnulein** [comment]
@Jazzy0806 maybe you send me the wrong log so, because in the log the sensor is there

`Do. März 30 16:58:31 2023 1680188311535 Debug: /Users/cagnulein/qdomyos-zwift/src/main.cpp int main(int, char **) "cadence_sensor_name" QVariant(QString, "Bryton Cadence")`

it's the timestamp right?

**Comment by Jazzy0806** [comment]
Tried it again, and again it didn't move. Cadence sensor is disabled, I double checked this.

[debug-Do__März_30_17_43_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11113409/debug-Do__Marz_30_17_43_06_2023.log)

**Comment by Jazzy0806** [comment]
Maybe I should delete the app and load new?

**Comment by Jazzy0806** [comment]
Something's still not right. I can not enable "Speed calculates on Power" with my Renpho bike. It still won't move in VZfit. Attached are two files: one trying to get the bike moving with "Speed calculates on Power", one with this function disabled (there it moves).
[debug-Fr__Apr__14_11_38_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11239643/debug-Fr__Apr__14_11_38_13_2023.log)

**Comment by Jazzy0806** [comment]
The second log file is too big :(

**Comment by cagnulein** [comment]
> The second log file is too big :(

zip it

**Comment by Jazzy0806** [comment]
[debug-Sa__Apr__15_13_35_29_2023.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/11239658/debug-Sa__Apr__15_13_35_29_2023.log.zip)

**Comment by cagnulein** [comment]
i will check it asap

**Comment by Jazzy0806** [comment]
![IMG_6169](https://user-images.githubusercontent.com/129307638/232228902-81898597-8f49-442a-b4e0-91704995fe57.JPEG)

![IMG_6170](https://user-images.githubusercontent.com/129307638/232228957-1afc7d56-f99f-4e08-acb3-71c09c29f3de.jpeg)

I don't know why it was splitted, but it was 28 something kilometers on VZfit. QZ says 18,49. Something's not right here and I don't know what it is.

**Comment by cagnulein** [comment]
@Jazzy0806 i still didn't receive any feedback from vzfit, did you? we need them to cross the information. because it seems that they over calculate speed. maybe using the difficulty in the game?

**Comment by Jazzy0806** [comment]
> @Jazzy0806 i still didn't receive any feedback from vzfit, did you? we need them to cross the information. because it seems that they over calculate speed. maybe using the difficulty in the game?

This could be. I'm riding on difficulty 5.
Didn't get a reaction so far.

**Comment by cagnulein** [comment]
try changing the speed, put the max difficulty and check if the delta is minor, if so, you should talk with them

let me know

**Comment by Jazzy0806** [comment]
> try changing the speed, put the max difficulty and check if the delta is minor, if so, you should talk with them
> 
> let me know

I'll try this and will let you know.

**Comment by emalafeew** [comment]
We use the speed and distance supplied by QZ if two conditions are true:

1. The fitness device reports speed at the wheel (as determined by FTMS
flags or reports as a hub speed sensor)
2. The user has enabled "Authentic Mode"

Note that authentic mode is not enabled by default, because

a. VZfit also supports cadence & power sensors that do not directly report
speed
b. It's a game and was tuned to go a bit faster than reported
c. Without resistance control we modify your virtual speed up and down hills

Hope that helps!
-Eric

**Comment by Jazzy0806** [comment]
Authentic mode made it! Unbelievable that I didn't try this 🙈

**Comment by cagnulein** [comment]
great!
