### ISSUE TITLE
[REQ] more y-axis gridlines/markers in HR report

### ISSUE THREAD

**Issue by haristdin** [cagnulein/qdomyos-zwift#1389]
Hi Roberto Viola .,. Thanks for keeping your support going.

I have a suggestion for your app., Please see if it makes sense.

In the exercise report., There's various charts.  For HR chart in particular, apart from the zone names on y-axis..is it possible to add some more grids (say for every 10 bpm)?  I often find it hard to remember what zone settings I have..and even if I do, I would like to have more detailed breakdown of bpm over the exercise duration.

Thanks again for your wonderful app.

**Comment by cagnulein** [comment]
thanks I will try to do asap
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 1 apr 2023 alle ore 20:58 haristdin ***@***.***>
ha scritto:
