### ISSUE TITLE
Heart Rate Monitor (Wahoo tick) going On and Off intermittently, only when in Domyos Elliptical bike setup.

### ISSUE THREAD

**Issue by jjortizfernandez** [cagnulein/qdomyos-zwift#1392]
**Describe the bug
Heart Rate Monitor (Wahoo tick) going On and Off intermittently, only when in Domyos Elliptical bike setup.

HRM works perfectly with Bodytone SMB setup.

**To Reproduce**
Start Domyos EL500 elliptical bike.
Start QzDomyos
Connect Wahho Tick HRM
Start exercising 

**Expected behavior**
Stable HRM reading

[debug-dom_abr_2_11_57_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11131811/debug-dom_abr_2_11_57_21_2023.log)

 - Ipad OS 16.1.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
fixed @jjortizfernandez ! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
