### ISSUE TITLE
Floating window missing target resistance (Android with bowflex c6 bike)

### ISSUE THREAD

**Issue by Debbles12** [cagnulein/qdomyos-zwift#1398]
Floating window missing target resistance (Android with bowflex c6 bike, peloton class)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy tab s6 lite
 - OS: Android
 - Version 13
[debug-Wed_Apr_5_06_08_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11161260/debug-Wed_Apr_5_06_08_04_2023.log)
[debug-Wed_Apr_5_06_08_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11161261/debug-Wed_Apr_5_06_08_57_2023.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok after a first quick lock the target resistance is available on the qz main window so the issue should be on the floating only. i will check this asap.
thanks for reporting it @Debbles12 !

**Comment by cagnulein** [comment]
Debbie  got the issue! you have the target resistance tile disabled in the settings! enable it and let me know!
