### ISSUE TITLE
I would like auto resistance synch feature using when using two separate Android devices like a tablet for QZ and a Android TV for the Peloton app. The synch auto resistance feature is only available when running QZ and the Peloton on teh same device.

### ISSUE THREAD

**Issue by krolikoski** [cagnulein/qdomyos-zwift#1399]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
@krolikoski amazon app store is ready! I can invite you in the beta if you send me an email of your amazon email to roberto.viola83@gmail.com

now I have to do the QZ part but it's quite easy
