### ISSUE TITLE
Connection Issue with Proform TDF 1.0

### ISSUE THREAD

**Issue by ppsears** [cagnulein/qdomyos-zwift#1401]
Have downloaded the app to my iPhone 14 plus and it connects to the bike (I-SB) ok and all the tiles appear. However it’s not picking up any metrics when I start cycling. I’ve toggled the Proform TDF 1.0 option in Bike Options and that sorted out the cadence but nothing else. Copy of debug log below - let me know if I need to provide any more information. Many thanks. 
[debug-Fri_Apr_7_10_28_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11177839/debug-Fri_Apr_7_10_28_56_2023.log)
`

**Comment by cagnulein** [comment]
hi @ppsears in the log i can see also power. you are missing only speed and distance. you can have it enabling the speed based on power setting under the bike option. let me know

**Comment by ppsears** [comment]
Thank you - speed/distance now working fine. Last question, am struggling to build up any real speed - is there a setting such as Zwift Resistance Offset that I need to change from the default level of 4 - or some other setting that I’ve not found yet.

**Comment by cagnulein** [comment]
yes the zwift resistance offset should be the resistance level that you feel like a flat road. so set a medium level for it and then with the gear tiles you can override the gears like a real bike during a zwift workout

Let me know!
