### ISSUE TITLE
Yesoul G1 Max

### ISSUE THREAD

**Issue by caleb2011x** [cagnulein/qdomyos-zwift#1410]
I opened the app then connected to the bike. I then selected free ride and pedaled some then stopped and adjusted resistance up and then down. 

Here is a link to my bug report. Wasn't able to upload bug report because of file size. 

https://drive.google.com/file/d/1W383bSdhc2RiUIT1RZaiaE8vqG1_IxwV/view?usp=drivesdk

**Comment by cagnulein** [comment]
![btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/11229192/btsnoop_hci.log)

Perfect I will check this asap @caleb2011x !

**Comment by cagnulein** [comment]
Hi @caleb2011x I checked the log but unfortunately there is no presence of the bike at all. Stupid question: did you use the yesoul app on the same device where you're taking the log? If not you have to do this in this way

Let me know!

**Comment by cagnulein** [comment]
#1443
