### ISSUE TITLE
Conversion gain setting and conversion offset setting do not work with Tacx Neo 2 and Peloton.

### ISSUE THREAD

**Issue by AnneAstrid88** [cagnulein/qdomyos-zwift#1418]
So it works, but unfortunately the conversion gain setting and conversion offset setting do not work. My resistance feels way too high, but I have no way to make it lower in the automatic resistance adjusting mode. I'm sorry I didn't mention it sooner, I didn't have the time to test it extensively.

_Originally posted by @AnneAstrid88 in https://github.com/cagnulein/qdomyos-zwift/issues/1370#issuecomment-1511646090_

**Comment by cagnulein** [comment]
I will check this in the next days @AnneAstrid88

**Comment by cagnulein** [comment]
@AnneAstrid88 are we ok with this?

**Comment by AnneAstrid88** [comment]
I'm sorry for the late response but this is still not working. 
The target resistance is always 1 below the peloton target resistance. 
I can't even adjust it manually. If I adjust the target resistance manually, the resistance crashes and goes to zero until Peloton pushes a new resistance to QZ.

**Comment by AnneAstrid88** [comment]
Maybe also relevant to know: 
I'm talking here about target resistance and target peloton resistance, because both resistance and peloton resistance are unusable for me. They change continuously and do not contain any comprehensible data, I think they change based on the cadence.
