### ISSUE TITLE
Peloton offset increases every second during ride

### ISSUE THREAD

**Issue by Debbles12** [cagnulein/qdomyos-zwift#1422]
I'm using the peloton auto-sync with the floating window and during my last 2 rides, the peloton offset tile increased every second to match the time in the ride until the ride ended and it was 2700 seconds.

Using qz android app without qz companion app

![20230419_064841](https://user-images.githubusercontent.com/102544939/233101477-f4d18860-56df-4280-a7c5-912ee1d4430b.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy tab s6 lite
 - OS: Android
 - Version [e.g. 
  
  

[debug-Wed_Apr_19_06_03_19_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/11274001/debug-Wed_Apr_19_06_03_19_2023.zip)

**Comment by Debbles12** [comment]
It's working. My app must have updated after my ride. Thanks for checking.

**Comment by cagnulein** [comment]
Glad to hear this!
