### ISSUE TITLE
Stroke Rate with WaterRower COM Module doesn't decrease when I stop rowing.

### ISSUE THREAD

**Issue by rbolinger** [cagnulein/qdomyos-zwift#1424]
Thank you Roberto for getting the WaterRower S4 COM Module added to devices the QZ app works with. As I mentioned via email the stroke rate will be stagnant after I stop rowing. Note I do see my speed going down after stopping.

I'm giving links to a few Debug Logs, the issue likely exists in all of them but should definitely be in the oldest one. I got so excited by iFit pairing at least sort of working that I didn't stay focused on this issue, I'll log something else for that.

https://www.dropbox.com/s/o51apcby5avcfqm/debug-Thu_Apr_20_10_44_06_2023.log?dl=0
https://www.dropbox.com/s/fb89o2f6br1162b/debug-Thu_Apr_20_10_44_47_2023.log?dl=0
https://www.dropbox.com/s/mlv6b8incfked8s/debug-Thu_Apr_20_10_45_56_2023.log?dl=0
https://www.dropbox.com/s/ol8tytsqp31wdyr/debug-Thu_Apr_20_10_46_31_2023.log?dl=0

**Comment by cagnulein** [comment]
@rbolinger got the issue, the main issue is that the rower is not clearing the speed or the pace when you stop rowing :D so it's a bug of the firmware :)

But good news, I can put a filter on this!

Let me do this, and I will tell you when I'm ready to test this!

**Comment by cagnulein** [comment]
@rbolinger modification done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by rbolinger** [comment]
@cagnulein , issue is fixed. When I stop rowing the stroke rate on the QZ app goes to 0 as it should. Thank you!

**Comment by cagnulein** [comment]
great!
