### ISSUE TITLE
[BUG]Cant connect a JTX Pro-Club Treadmill 

### ISSUE THREAD

**Issue by rjs2806** [cagnulein/qdomyos-zwift#1427]
Hi,

I cant connect a JTX club pro treadmill to the QD app (and Zwift). 

I can get qd to recognise and connect to the treadmill but as its moving no data appears in the tiles. If I try and then connect to zwift (running on Apple TV) it isnt able to see the device running qd. 

[debug-Thu_Apr_20_20_19_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11289875/debug-Thu_Apr_20_20_19_05_2023.log)

[debug-Thu_Apr_20_20_19_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11289878/debug-Thu_Apr_20_20_19_05_2023.log)
[](url)

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/commit/68bf628cf38cb1e1f9cfd9c370a70abea29abdea #1251 should be releated to this one

**Comment by cagnulein** [comment]
@rjs2806 are we ok with this?
