### ISSUE TITLE
Tacx Neo power lag

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#1431]
After reading about Wahoo Race Mode I became curious about responsiveness. NRX Connect shows that my Tacx Neo v1 transmits power once a second over Bluetooth. So if qz as a bridge sends power once a second to Zwift, doesn't that mean there could be a delay of up to 2 seconds between jumping on the pedals and having the effort show up in Zwift? (I personally always change "1s" to "100" in virtualbike.cpp and virtualtreadmill.cpp before compiling it, so for me the delay shouldn't be more than 1.1s.) The delay works out well for not getting dropped at the end of an effort, e.g. climbing a hill, but not so well for covering a break.

**Comment by cagnulein** [comment]
yes by default qz sends it every seconds so at worst case you have 2s at best 1s

putting it to 100ms you will have 1.2 as worst and 1s as best

**Comment by smulrine** [comment]
Would it maybe be worth making the advertisement interval a setting?

**Comment by cagnulein** [comment]
could be yes

**Comment by cagnulein** [comment]
I'm doing this now!
