### ISSUE TITLE
[BUG] power not syncing. No cadence 

### ISSUE THREAD

**Issue by SGoldst** [cagnulein/qdomyos-zwift#1434]
Power zone workout. Watts didn’t seem right to restarted QZ then ‘fast forwarded’ three min to catch up to peloton already in progress. Peloton went to zone 3. QZ didn’t update, stayed at zone 2. Let it wait for a min then quit. 
cadence signal never picked up 
1st gen wahoo Kickr.
[debug-Mon_Apr_24_12_13_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11313091/debug-Mon_Apr_24_12_13_38_2023.log)

**Comment by SGoldst** [comment]
Yup, that's the right class. Thanks!

**Comment by cagnulein** [comment]
@SGoldst ok so qz is using this
https://app.homefitnessbuddy.com/peloton/powerzone/details/106

![image](https://user-images.githubusercontent.com/48216/234194374-e820d52e-d831-455b-b8c3-fff7a32e195e.png)

in the log I was that qz is acting normal following this class (in the log there is a ramp up from 90W to 124W as described in the zwo file of homefitnessbuddy

What is not right? I mean the class it hasn't a warmup at the beginning?

**Comment by SGoldst** [comment]
I manually increased the power at one point during the warmup, but now I
don't recall when exactly. But then I waited for the next zone callout for
Z3, but the target zone displayed in QZ didn't change and the command to
the kickr didn't either.  Z3 for me should be ~140W based on the FTP I have
set up in QZ.

Can you also tell why I wasn't getting cadence? Do I have an incorrect
setting?

**Comment by SGoldst** [comment]
I just tried it again and the wattage was correct. Not sure what happened yesterday. Sent from my iPhoneOn Apr 24, 2023, at 1:09 PM, Roberto Viola ***@***.***> wrote:﻿
@SGoldst 
is this the right class? for this qz is using home fitness buddy api because peloton doesn't provide metrics for this class.
so first of all i need to check if it was the right class
let me know

**Comment by cagnulein** [comment]
Let me know if it happens again. Leave the debug log enabled. What about the cadence instead?

**Comment by SGoldst** [comment]
I also had the issue of the cadence from my duotrap sensor not getting
picked up, but not sure if  I have an incorrect setting?

**Comment by cagnulein** [comment]
@SGoldst the DuoTrap S is correcly setup in the settings but in the log I can't find it over bluetooth. It seems it was already connected to something else? Could you please check it?
Also, please, send me always a debug log when you find something strange in the peloton metrics as you did here, because, since I can't have peloton in Italy, the user's feedbacks it's the only way to me to debug new things.

Thanks

**Comment by SGoldst** [comment]
[debug-Wed_Apr_26_09_33_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11334503/debug-Wed_Apr_26_09_33_08_2023.log)

**Comment by cagnulein** [comment]
what about this one @SGoldst  ?

**Comment by SGoldst** [comment]
Here's a new one. All good to start, I did have to pause a few times, in which case I pause both the peloton app and QZ, and assume this what I should do to keep the timing synced? Although I'm not actually sure that works as sometimes I feel they still get out of sync, but with other variables it's hard to tell. 
In the last third of the workout I tried to increase the power by using the target power up arrow, but it did not change my Kickr, the watts were the same.  after that even when the target power changed again based on the class calling out a new zone the  kickr did not update. Then at the very end the displayed zone target dropped to around 1.9 (<100 watts) but the kickr increased to around 3.5 (~150 watts), so not sure if the target displayed 
Looking at the graph I see a black line that seems to reflect what the display was saying, and a yellow line of what the kickr was doing?

**Comment by SGoldst** [comment]
one more thing - I was running Peloton off my iphone rather than my firestick as I normally do, so peloton was displaying cadence! but it was off - QZ was showing 93 and Peloton was showing 155

**Comment by cagnulein** [comment]
> Here's a new one. All good to start, I did have to pause a few times, in which case I pause both the peloton app and QZ, and assume this what I should do to keep the timing synced? Although I'm not actually sure that works as sometimes I feel they still get out of sync, but with other variables it's hard to tell.

in this log the peloton companion setting was disabled, that's why the auto sync was not working.



> In the last third of the workout I tried to increase the power by using the target power up arrow, but it did not change my Kickr, the watts were the same.

I saw this and QZ was sending the right request to the kickr. How could you tell if the watt were updated on the kickr? Does it display somewhere?



> one more thing - I was running Peloton off my iphone rather than my firestick as I normally do, so peloton was displaying cadence!

i guess because the peloton version on firestick doesn't support cadence. that's normal because also the peloton app on android doesn't. only on ios the peloton app can accept the cadence sensor.



> QZ was showing 93 and Peloton was showing 155

this seems an issue on the peloton app. Also other users are reporting this. They solve this reinstalling the peloton app and resetting the network setting on their iphone and rebooting them

Let me know

**Comment by cagnulein** [comment]
@SGoldst are we ok with this?

**Comment by SGoldst** [comment]
Yup, seems to be working.  Thanks!
