### ISSUE TITLE
[BUG] Proform Bike: speed too fast

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#144]
Beta 2.3.1, PROFORM bike
Mileage is about 0.2 miles too fast on the app compared to the bike's LCD display

**Comment by cagnulein** [comment]
@ptrinephi i need the ratio of the bike for the right calculation. I mean the speed is ratio * cadence. Now i set 0.33 for the ratio but it's based on what you saw in the last tries.

If you want i could add this ratio as a parameter and you can play with it

**Comment by ptrinephi** [comment]
Please add the ratio as a parameter as each bike may have slightly different values.

**Comment by cagnulein** [comment]
it will avaiable in the 2.3.5
