### ISSUE TITLE
Proform 8 speed and inclination force

### ISSUE THREAD

**Issue by talwrii** [cagnulein/qdomyos-zwift#1454]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It'd be cool if I could control the incline of the treadmill and its speed with my phone. It might also be fun to have "routines"

**Describe alternatives you've considered**
I mean.. I can just press the buttons instead - but far less cool

**Additional context**
Do you want some money? Obviously I understand that money is not the only factor and often trading of time and money can be difficult - but if money helps I'd throw in 50-100 GBP for this feature... because it's cool and I hate ifit's policy (and what it implies about ifit). If a hundred of so other wanted this feature (not sure how likely that is...) it starts becoming worthwhile. 

Thanks again for reverse engineering the ifit protocol, it saved me a good half day getting a NPE RUNN and getting it working.

**Comment by cagnulein** [comment]
Hi! Which treadmill do you have? routines are already possible with the zwo or xml files! and you can force speed or incline with that if your treadmill support this 
Let me know

**Comment by talwrii** [comment]
Hey,

Ooh that's cool. I have a proform 8.0 treadmil and am using it with android (from the play store).  The plus and minus buttons for incline and speed didn't do anything if I remember correctly - so I assumed that this part of the ifit protocol had not been reverse engineered.

**Comment by cagnulein** [comment]
nope i did already for ifit! i guess you have just to use the right switch in the proform treadmill section. try them one by one and restart qz always after modifying them. only one must be enabled at a time
let me know

**Comment by talwrii** [comment]
Thanks... in a coffee shop at the moment, but I'll report back when I'm at home.

**Comment by talwrii** [comment]
I do have my phone with however, I was on a nordictrack device - there's no proform 8.0 , so I've selected proform 9.0 (there's also a proform 1800i, proform and proform cadence LT)

**Comment by cagnulein** [comment]
ok no problem, italy here so i'm going to bed soon. We will catch up
tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 mag 2023 alle ore 20:10 talwrii ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
yes try all the options one by one. remember to leave only one setting enabled at time and always restart qz

**Comment by talwrii** [comment]
Hmm. I tried all the proform settings one at a time. Most of them detected speed and incline okay (apart from the LT if I recall correctly), but the plus and minus buttons on my phone didn't seem to change the treadmill speed or incline. 

I also double checked and the ifit app could change speed and incline.

I might try the nordic ones in a bit.

**Comment by cagnulein** [comment]
Yes try also the Nordic ones and let me know

**Comment by talwrii** [comment]
So I've tried all the nordic/proformer models and the plus and minus options next to the speed and incline do nothing on any of the models :/

**Comment by cagnulein** [comment]
ok so collect this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using the ifit app and i will add it!
thanks

**Comment by talwrii** [comment]
Okay. I'm still pretty motivated so will try to get this done... maybe later this week.

**Comment by talwrii** [comment]
Okay, here's the logging from using the iFit app on an Android phone.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/11472511/btsnoop_hci.log)

I:

* Started the Ifit app (which decreased the incline)
* Long-pressed the start button as directed by the iFit app
* The incline decreased when I started a workout
* I increased and decreased the speed; then 
* I increased and decreased the inclination of the device.

**Comment by cagnulein** [comment]
perfect i will check this tomorrow!

**Comment by cagnulein** [comment]
@talwrii done. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Remember to enable the new proform 8 setting then (only that one!). Thanks

**Comment by talwrii** [comment]
Thanks for that. I had a play on in the evening I got the patch. None of the buttons did anything still :/. I'm away from home at the moment - but when I get home should I do anything run with the new code?

**Comment by cagnulein** [comment]
@talwrii did you enable the new setting for your bike (only that one!) and restarted qz?

**Comment by cagnulein** [comment]
any news @talwrii ?
