### ISSUE TITLE
Peleton login error

### ISSUE THREAD

**Issue by SGoldst** [cagnulein/qdomyos-zwift#1455]
Two issues, not sure if they are related
1) a few seconds into the ride a peleton logon error message appears. I dismiss it and keep going.
2) my HR appears in the peleton app,but freezes, showing the same value even as it changes in the QZ app
[debug-Mon_May_8_12_06_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11423714/debug-Mon_May_8_12_06_58_2023.log)

**Comment by cagnulein** [comment]
> 1. a few seconds into the ride a peleton logon error message appears. I dismiss it and keep going.

where on qz or in the peloton app? I don't see any logon error in QZ

> 2\. my HR appears in the peleton app,but freezes, showing the same value even as it changes in the QZ app

qz is sending the correct value all the time to the bluetooth. it sounds to me that the peloton app stops to poll it. Let me know if it happens again. Where are you running the peloton app?

**Comment by SGoldst** [comment]
The login error message appears on the QZ app. Peleton app is running on an Amazon firestick. Sent from my iPhoneOn May 9, 2023, at 4:32 AM, Roberto Viola ***@***.***> wrote:﻿


a few seconds into the ride a peleton logon error message appears. I dismiss it and keep going.


where on qz or in the peloton app? I don't see any logon error in QZ

2. my HR appears in the peleton app,but freezes, showing the same value even as it changes in the QZ app

qz is sending the correct value all the time to the bluetooth. it sounds to me that the peloton app stops to poll it. Let me know if it happens again. Where are you running the peloton app?

**Comment by cagnulein** [comment]
got the login error 

`Mon May 8 12:08:30 2023 1683565710360 Debug: /Users/cagnulein/qdomyos-zwift/src/peloton.cpp void peloton::login_onfinish(QNetworkReply *) "login_onfinish" QJsonDocument()`

the peloton server doesn't reply, so yes the toast message was right. QZ retried it after 10 seconds, and then peloton server answered.

About the HR issue, I got other HR issue from peloton on the firestick, so I guess it's a peloton issue on firestick on the bluetooth stack.

**Comment by cagnulein** [comment]
@SGoldst are we ok with this?
