### ISSUE TITLE
[REQ] add/allow minimum resistance for classic peloton workouts

### ISSUE THREAD

**Issue by billputney** [cagnulein/qdomyos-zwift#1469]
This feature already exists for PZ workouts, it would be nice to have it for classic workouts also.

**Comment by cagnulein** [comment]
sure! i will do this in the next days!

**Comment by cagnulein** [comment]
done @billputney ! it will be in the 2.13.46 and above. You should have already the 2.13.44 installed, isn't it?

**Comment by billputney** [comment]
Thank you!

I just updated and I have 2.13.33. I guess I need to leave the "public"
beta? But I'm not sure how to do that.

**Comment by cagnulein** [comment]
yes @billputney you need to go into the play store page of QZ, leave the beta program in the bottom and then join it again. It could required some hours to complete this process.
Let me know

**Comment by billputney** [comment]
Ok, I will do this.

**Comment by cagnulein** [comment]
@billputney are we ok with this?

**Comment by billputney** [comment]
Yes, thank you very much!
