### ISSUE TITLE
Zero ZT-2500 treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1471]
Zero ZT-2500 should use the mc460 for speed forcing but the standard profile for others.

**Comment by mslpatcher** [comment]
Thank for the response. I believe Zero ZT-2500 use the same features with Fitfiu MC-400, which have inclination physically, while mc460 is TM without inclination features.

https://manuals.plus/m/660165969688c8097688c4a38586117f2dd783ba15dfebae51479aa964783b21_optim.pdf

**Comment by cagnulein** [comment]
[debug-Sat_May_20_17_25_27_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/11522009/debug-Sat_May_20_17_25_27_2023.zip)
