### ISSUE TITLE
[REQ] Apply the override keyword where appropriate

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#1472]
> It's not mandatory, and it's not necessary for this PR, I'll remove it. 

>The keyword is relatively recent development in the C++ language, used to indicate if a method is overriding a virtual method from a superclass. I believe it is preferable to use it because it distinguishes a method that is intended to override something from a method put in without that intent - you can't use the override keyword where it's not overriding something.

hah ok! maybe we can do a separate PR for this?

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/pull/995#discussion_r1199556118_

**Comment by drmason789** [comment]
@cagnulein If you approve, I'll take care of this.

**Comment by cagnulein** [comment]
yes thanks! ^^

**Comment by drmason789** [comment]
@cagnulein Currently there is 

virtual bool bluetoothdevice::connected();

Then in bike, rower, treadmill and elliptical, this is redefined the same way.

On the basis of this recommendation, to use one of virtual, override, final

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final

I would remove the "virtual" keyword from overrides.

**Comment by cagnulein** [comment]
thanks @drmason789 !
