### ISSUE TITLE
Domyos - zwift

### ISSUE THREAD

**Issue by rica2323** [cagnulein/qdomyos-zwift#1476]
Hello,

I have Domyos EB fold and I try connect to Zwift via your app.
But doesnt work. 
Enclosed you will find debug file and screen zwift monitor.
Qzdomyos -iPhone
Zwift - pc with win10
 
![BFDD2324-185C-4C70-8C28-7E43BF8A0C29](https://github.com/cagnulein/qdomyos-zwift/assets/111796046/6da841e6-63b2-483f-afed-1a4998b3a6e0)
/
[debug-ne_kvě_21_20_29_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11525328/debug-ne_kve_21_20_29_04_2023.log)

**Comment by cagnulein** [comment]
@rica2323 use the wahoo kickr virtual device. let me know!

**Comment by rica2323** [comment]
I dont see wahoo kickr…

**Comment by cagnulein** [comment]
are the phone and the pc on the same wifi?

**Comment by cagnulein** [comment]
i'm going to bed, if they are one the same wifi, test first zwift on another mobile instead of the pc so we can understand if it's the pc version of zwift that is has this issue (driver issue, highly possible)

let me know

**Comment by rica2323** [comment]
Yes, both on 5G wifi

**Comment by cagnulein** [comment]
> i'm going to bed, if they are one the same wifi, test first zwift on another mobile instead of the pc so we can understand if it's the pc version of zwift that is has this issue (driver issue, highly possible)
> 
> let me know

**Comment by cagnulein** [comment]
any news @rica2323 ?
