### ISSUE TITLE
Nautilus U618 [BUG]

### ISSUE THREAD

**Issue by HavocCG** [cagnulein/qdomyos-zwift#1477]
**Describe the bug**
Bought a Nautilus U618. It connects to the QZ app as B618 via bluetooth but none of the stats are being recorded. Bluetooth light on bike is on. Bluetooth is working with the Explore the World app and the stats are recorded successfully on that. Since not working in QZ app, no other apps, such as Zwift, are detecting my bike. 

**To Reproduce**
1. Turn on bike.
2. Open qz app
3. Start manual workout
4. No stats recorded

**Expected behavior**
Expect qz app to show speed, distance, time, etc. when pedaling.

**Screenshots**
![Screenshot_20230522_201602](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/7fc71f4a-70ce-4a97-b767-db8cf4dd0078)
![20230522_201728](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/31bd2181-ee25-4e36-82e2-a1006db15e61)
![Screenshot_20230522_201808_Camera](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/9d970122-5889-429d-ab20-11d16a2f3d92)

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 Ultra 
 - OS: Android 13
 - Version One UI 5.1

**Append a debug log**

[debug-Mon_May_22_19_53_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11538051/debug-Mon_May_22_19_53_02_2023.log)

  
**Additional context**

**Comment by cagnulein** [comment]
@HavocCG good news, got the issue! Could you please append here a screenshot from the free nrfconnect app on the store showing all the bluetooth characteristics of your bike? Thanks!

**Comment by HavocCG** [comment]
![Screenshot_20230523_192855_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/8ac17193-b3bd-4667-8cf4-9fbc2e340469)
![Screenshot_20230523_192908_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/1adeb977-2824-40b4-b86d-874e63c284fb)
![Screenshot_20230523_192914_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/b490fe3a-1156-4298-9e25-9c4b5530953a)
![Screenshot_20230523_192920_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/b9d9835c-607c-4fe1-9496-66a1293ff3b2)
![Screenshot_20230523_192939_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/1a75bbea-85da-422e-9203-02d5ff6d3b00)
![Screenshot_20230523_192953_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/3700e4bf-b829-4470-b437-ddc68e5bc2f8)
![Screenshot_20230523_193001_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/1ff825cd-d972-4b36-a593-839fa4c4774b)
![Screenshot_20230523_193012_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/7c0bcb64-726f-41a2-8077-dca756e8f902)
![Screenshot_20230523_193021_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/472eb871-844c-4a8c-99e5-1098c3568843)
![Screenshot_20230523_193027_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/134343654/b327f677-2431-447b-a890-781cc7518a4d)

**Comment by cagnulein** [comment]
@HavocCG ok added! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the beta. Maybe we need one or two version to stabilize it, but it's definitely achievable. Thanks

**Comment by cagnulein** [comment]
@HavocCG are we ok with this?

**Comment by HavocCG** [comment]
Yes. If I come across another issue I will open a new request. Thanks for your help.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
