### ISSUE TITLE
[REQ] HR Re-Sync

### ISSUE THREAD

**Issue by gadi247** [cagnulein/qdomyos-zwift#1479]
**Is your feature request related to a problem? Please describe.**
Sometime my watch loses HR connectivity with QZ (not sure why). QZ then shows the last value it had and uses to send that to Peleton App.

**Describe the solution you'd like**
Ability to reconnect to HR in QZ without restarting app. Setting shows the device there but if I change setting it wasnt to force reboot and then I lose my program mid-ride. Need a way to force sync with HR Mid-workout

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
[debug-Mon_May_22_20_05_11_2023 (1).log](https://github.com/cagnulein/qdomyos-zwift/files/11539721/debug-Mon_May_22_20_05_11_2023.1.log)

**Comment by cagnulein** [comment]
@gadi247 are you sure this log is about this issue? In this log the HR is updating for the whole workout/file. Maybe this is the wrong one?

**Comment by gadi247** [comment]
Not sure so I sent the others.  As I restarted app a few times to try to
connect

**Comment by cagnulein** [comment]
[debug-Mon_May_22_19_47_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11544804/debug-Mon_May_22_19_47_01_2023.log)
[debug-Mon_May_22_19_48_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11544808/debug-Mon_May_22_19_48_32_2023.log)
[debug-Mon_May_22_20_04_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11544823/debug-Mon_May_22_20_04_48_2023.log)
[debug-Mon_May_22_19_46_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11544825/debug-Mon_May_22_19_46_48_2023.log)

**Comment by gadi247** [comment]
Glaaxy has no broadcast feature soe you must use a 3rd party app which works fine. Understood that at somepoint it sent 141 continously - but watch 'corrected itself'(I was able to change Peloton app to read watch HR directly vs usinz QZ broadcast). I need to be able to re-connect the HR if this occurs without reatarting QZ app and losing workout

**Comment by cagnulein** [comment]
> app which works fine.

it doesn't seem to work fine. I mean the issue that I'm seeing is that the app still send the same value in this scenario. 

Disconnecting it from QZ and connecting it to peloton, it forces to recreate a new connection and so you're workaround the issue in this way.

So the right solution is to contact the 3rd party app developer and tell him that you have this issue and that it has to be solved.

Another point could be to create a QZ companion app for android. I didn't do yet because I don't have time actually (my main job is killing me in these months)

Adding a feature to disconnect and reconnect the HR is doable of course, but I guess it's a very dirty workaround, don't you think?

**Comment by gadi247** [comment]
Fair enought. I will report bug to app developer.

Focus on your main job! :)

I had a similar issue last week (I had texted you) where I walked away from the workout to a different room and when I came back the HR would pick up where it was in QZ. Perhaps same issue. App loses connection with QZ and doesnt reconnect

**Comment by cagnulein** [comment]
Ok let me know if he will answer it back! You can invite him here, it will be nice to chat altogether!

**Comment by cagnulein** [comment]
@gadi247 any news?

**Comment by gadi247** [comment]
I basically cant walk away from the connection as it wont reconnect to QZ

**Comment by cagnulein** [comment]
ok i will answer back to him with you in CC. Let's reopen this so
