### ISSUE TITLE
[BUG] Proform bike, Erratic Speed in Strava

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#148]
Beta 2.3.2, Proform bike
When exporting to Strava, the speed shown is "erratic" it goes up and down very quickly.  The speed display in the bike and the app appears normal, no jumping up and down as seen in Strava.
[2021-01-27_12-20-11.pdf](https://github.com/cagnulein/qdomyos-zwift/files/5882797/2021-01-27_12-20-11.pdf)

**Comment by ptrinephi** [comment]
Here's the fit file

[Wed Jan 27 12_00_04 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5882807/Wed.Jan.27.12_00_04.2021.zip)

**Comment by cagnulein** [comment]
could you please also attach the debug file? thanks!

**Comment by ptrinephi** [comment]
Attached a debug log file and fit file
[Ride_qdomyos_zwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/5895093/Ride_qdomyos_zwift.zip)

**Comment by ptrinephi** [comment]
This appears to be an issue on the proform bike.
