### ISSUE TITLE
Bkool trainer

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1483]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/47fb1b12-3044-49c9-a01e-ea3e67c744da)

**Comment by cagnulein** [comment]
[btsnoop_hci.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/11551647/btsnoop_hci.log.zip)

**Comment by Bkool12** [comment]
Hi

**Comment by cagnulein** [comment]
@Bkool12 add the debug log, thanks

**Comment by cagnulein** [comment]
[debug-Wed_May_24_11_55_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11558396/debug-Wed_May_24_11_55_00_2023.log)

**Comment by cagnulein** [comment]
@Bkool12 any news?
