### ISSUE TITLE
[BUG] Disconnecting from Schwinn IC4 

### ISSUE THREAD

**Issue by rjbutler** [cagnulein/qdomyos-zwift#1488]
**Describe the bug**
During the last couple of days QZ disconnects from my IC4 during a workout.   I've seen similar behavior with my Smartspin2K but this log doesn't include that, probably since I never actually started a ride.

**To Reproduce**
1. Launch QZ.  Start pedaling to turn on IC4, QZ home screen displays.  
2. Sometimes it works for a while and then cadence/resistance stops updating
3. Sometimes it seems to disconnect immediately.

[debug-Sat_May_27_13_59_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11583025/debug-Sat_May_27_13_59_30_2023.log)

**Comment by cagnulein** [comment]
hi @rjbutler it seems that QZ can't create a connection at all with your bike. Can you try, using testflight, to check if a previous version works ok? try to use the oldest one that you have on testflight
Let me know!

**Comment by rjbutler** [comment]
I didn't think the dashboard would sho up without a connection to the bike?  It displayed as soon as I turned on the bike by pedaling 

I'll try an earlier version tomorrow

**Comment by cagnulein** [comment]
yes the tiles show up when QZ sees the broadcast advertisement from the bike, and it's the only thing that i see in this log, then QZ tries to connects but never got it.

**Comment by rjbutler** [comment]
@cagnulein Going back to build 538 it connected right away when I started pedaling and displayed cadence/resistance.  I then tried 563 again and it didn't connect or detect the bike.  I unplugged the bike and plugged it in, and it then detected it but apparently didn't connect.

[debug-build 563-no connection.log](https://github.com/cagnulein/qdomyos-zwift/files/11585201/debug-build.563-no.connection.log)
[debug-build 538-connected.log](https://github.com/cagnulein/qdomyos-zwift/files/11585202/debug-build.538-connected.log)

**Comment by cagnulein** [comment]
thanks @rjbutler 
the only thing that could explain this is this https://github.com/cagnulein/qdomyos-zwift/commit/c8cf9367dbeba959b628e04bfa654a3d5775dbd8

so i'm sending you the version with this patch (550) and the version without this (549 is the older one is without the patch). Let me know if the new one doesn't work and the old one yes, so that's means that this is the issue

**Comment by rjbutler** [comment]
Log from build 549 -- I was able to get it to connect by pressing the bluetooth button on the bike but it didn't stay connected.
[debug-Sun_May_28_10_45_58_2023 2.log](https://github.com/cagnulein/qdomyos-zwift/files/11585354/debug-Sun_May_28_10_45_58_2023.2.log)

**Comment by cagnulein** [comment]
on the 549 the connection seems fine (so differente from the 563) but it disconnects 4 seconds later. could you try without the ss2k?

**Comment by cagnulein** [comment]
@rjbutler are we ok now?
