### ISSUE TITLE
[BUG] -Pro-form Sport RL rower Bluetooth Name I_RW Pace and Speed are incorrect

### ISSUE THREAD

**Issue by afeith** [cagnulein/qdomyos-zwift#1498]
**Describe the bug**
I have QZ connected to a pro-form Sport RL Rower and the speed and pace are not showing correctly on the QZ tiles.  In fact when I row "slower" the pace decreases when it should go up because it would take longer to row 500M.  I have attached the debug log.

**To Reproduce**
[debug-Thu_Jun_1_19_24_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11630647/debug-Thu_Jun_1_19_24_19_2023.log)

**Expected behavior**
Pace should decrease as power increases.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 9 
 - Version 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @afeith i need a longer log showing the issue. in this log i just a single speed. Also a video with the console and qz for reference will be useful! Thanks

**Comment by afeith** [comment]
Here is another debug log.  I'll work on a video tomorrow.

**Comment by afeith** [comment]
[debug-Fri_Jun_2_19_15_10_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/11640462/debug-Fri_Jun_2_19_15_10_2023.zip)
Here's alog file from a class I did tonight.  I'll try to get a video tomorrow

**Comment by cagnulein** [comment]
good news @afeith I guess I fixed it! I'm pushing it (version 2.13.65) let me know if it works ok now!

**Comment by cagnulein** [comment]
sorry I mean 2.13.66

**Comment by afeith** [comment]
Worked perfectly.  Closing the issue!!!!

**Comment by cagnulein** [comment]
amazing!
