### ISSUE TITLE
[BUG] negative HR

### ISSUE THREAD

**Issue by castlerevolving** [cagnulein/qdomyos-zwift#1501]
![IMG_5771](https://github.com/cagnulein/qdomyos-zwift/assets/135349291/1d89ecac-77b3-4553-9f62-fb62717812b1)
**Describe the bug**

during session testing new support of SmartRow broadcasting, HR gave negative values during majority of session. HR was received from the iPad/SR app. On SR-app values were fine. 

**To Reproduce**
Connect QZ to SmartRow app for rower and also to same iPad/device for HR

Start a session. 

[debug-Fri_Jun_2_09_24_26_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11636457/debug-Fri_Jun_2_09_24_26_2023.log)

* sent by iPhone. Annoying to type.

**Comment by castlerevolving** [comment]
![IMG_5774](https://github.com/cagnulein/qdomyos-zwift/assets/135349291/b738dba7-dae1-4743-a6e6-64ed5ac22a09)

HR as SmartRow saw it for compare

**Comment by cagnulein** [comment]
fixed! I will send you a new beta in an hour or so
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 giu 2023 alle ore 16:57 castlerevolving <
***@***.***> ha scritto:

**Comment by castlerevolving** [comment]
Tested today and works now. Thanks.
