### ISSUE TITLE
[BUG] STOP , PAUSE , START buttons do not function on FTMS treadmill

### ISSUE THREAD

**Issue by Dnoam1959** [cagnulein/qdomyos-zwift#1503]
**Describe the bug**
When app is connected with my custom workout , the "STOP , PAUSE , START  buttons do not function . The machine has to be running in order the program to take over.
All other +- buttons are working and the machine is under app control.
**To Reproduce**

**Expected behavior**
Total app control on the treadmill. Speed , inclination up & down , training programs  , all ok .Just stop and pause and start  do not work 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 Ultra 
 - OS: Android  13 latest update.
 - Version UI 5.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
done @Dnoam1959 It will be in the 2.13.70
I will try to upload this today!
