### ISSUE TITLE
BUG ON ZERO ZT-2500 inclination control via QZ app

### ISSUE THREAD

**Issue by mslpatcher** [cagnulein/qdomyos-zwift#1506]
**Describe the bug**
QZ app can control ZT-2500 treadmill. However inclination Tiles has problem. Incremental of inclination can only be done via QZ app from 0 to 1 to 2 to 3. then it seems stopping. I can't increase inclination with (+) button. 

The TM machine itself is in good condition. Every time I press inclination button (increase or decrease) on the treadmill panel, it works. At the sametime, QZ app will update the number in inclination tiles.

Interestingly, I can only again increase inclination value from 10 to 11, when I continue testing. 

Basically this is how to test, first I will run QZ app, confirming it connect to TM. I press QZ app inclination + button. If QZ app fail to command TM to increase inclination , then I will manually press TM's inclinaton (+/up) button to see if failure has to do with my TM. I do it 15-16 times to test all inclination point/value. Of course my TM is still in good condition. 

**Expected behavior**
The said treadmill can incline from 0 to 15 %, meaning I can increase inclination up to no 15. Everytime I press (+), TM should incline incremantally, and at the same time QZ app will show increased number up to 15.

**Desktop (please complete the following information):**
Not related because I test directly between QZ app and the treadmill via bluetooth as per requested by you.

**Smartphone (please complete the following information):**
 - Device: Oppo Android phone A31 (CPH2015)
 - OS: Android
 - Version 9

**Append a debug log**

Files
[debug-Tue_Jun_6_14_27_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11662140/debug-Tue_Jun_6_14_27_15_2023.log)

**Comment by cagnulein** [comment]
thanks, i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 giu 2023 alle ore 10:34 mslpatcher ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mslpatcher we need a 3rd app that can control the inclination. I don't remember: did you already provide me a hci snoof from kinomap about changing the inclination from the app directly?
