### ISSUE TITLE
Powerzone line and zones not showing

### ISSUE THREAD

**Issue by mnasman1** [cagnulein/qdomyos-zwift#1509]
This has been going on for about two weeks, The powerzone line does not show in the after ride graph and the current zones during the ride are not displayed in qz even though homefitnessbuddy has the graphs so the data should be able to be accessed. 
[debug-Wed_Jun_7_06_29_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11676914/debug-Wed_Jun_7_06_29_54_2023.log)

**Comment by cagnulein** [comment]
before of this event all the QZ's engine was working ok. Let me know

**Comment by cagnulein** [comment]
@mnasman1 this was due to #1430

that's explain everything:)

**Comment by cagnulein** [comment]
so @mnasman1 you would like to disable auto resistance and showing the line in the chart. i will try to do this

**Comment by cagnulein** [comment]
> @mnasman1 this was due to #1430
> 
> that's explain everything:)

@mnasman1 yes as i said i changed for this ticket the behavior. so if you need the previous behavior i have to do a modification. i will check this in the next days.

**Comment by lpecan** [comment]
Will check tonight.

**Comment by lpecan** [comment]
Seems to still work fine disabling the resistance  and reenabling

**Comment by mnasman1** [comment]
I think I’m only on 2.13.71.Matt ***@***.*** Jun 7, 2023, at 8:40 PM, lpecan ***@***.***> wrote:﻿
Seems to still work fine disabling the resistance  and reenabling

**Comment by cagnulein** [comment]
@lpecan 2.13.73?
@mnasman1 Are you on the open beta maybe? Let me push it there too

**Comment by cagnulein** [comment]
@mnasman1 did you check the new version?

**Comment by mnasman1** [comment]
Yes I checked it today and it is back to the way it was before. Thank you so much!Matt ***@***.*** Jun 10, 2023, at 2:16 PM, Roberto Viola ***@***.***> wrote:﻿
@mnasman1 did you check the new version?

**Comment by cagnulein** [comment]
that's a great news! Thanks for the feedback!
