### ISSUE TITLE
[REQ] - Time Remaining tile within Floating Window

### ISSUE THREAD

**Issue by Apex98765** [cagnulein/qdomyos-zwift#1517]
I’m just wondering if you could implement a “time remaining” tile specifically within the floating window. This option would allow users who are completing a peloton class to see when the next cadence or resistance change will be. It would also allow the user to listen to their own music but still follow a peloton class and know when the changes will be coming up next.

Could this be added to a future build?

Thank you for considering

**Comment by cagnulein** [comment]
yes sure, I can add it!

**Comment by Apex98765** [comment]
Wow, you’re quick!
Thank you so much for your help!

**Comment by cagnulein** [comment]
@Apex98765 I checked and it's already there! Which QZ version do you have installed?

**Comment by Apex98765** [comment]
I actually updated the app today and noticed it was there. My apologies for making the request! Thank you for replying.

**Comment by cagnulein** [comment]
no problem at all!
