### ISSUE TITLE
NordicTrack 2450 Commercial on raspberry

### ISSUE THREAD

**Issue by smalldave** [cagnulein/qdomyos-zwift#1521]
[Uploading qz.log…]()
Running qdomyos-zwift on a Pi 3B with qz companion on a NordicTrack 2450 Commercial.

Was all running great but a few days back the treadmill speed  stopped registering on zwift.
Hadn't changed qz / qz companion but I have since updated to latest versions

Had a look through the logs but can't see anything obvious. IP addresses all look fine.

There is something in the logs (attached) about a virtual treadmill connection error.

I'm not sure where to go from there.
[](url)

**Comment by cagnulein** [comment]
create a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by smalldave** [comment]
Hi,

Looks like the upload failed.

This one is from the app rather than the pi. Seems to show the same thing. Empty messages from qz companion on the treadmill. Or at least that is what the logs look like to me.

[debug-Wed_Jun_14_09_27_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11743566/debug-Wed_Jun_14_09_27_30_2023.log)

**Comment by cagnulein** [comment]
yes the companion is not sending the metrics. Can you share a screenshot from the qz companion after pressing the dump log button? Thanks

**Comment by cagnulein** [comment]
yes sure if adb is working, you can use https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat after pressing the dump log button on the qz companion

**Comment by smalldave** [comment]
[](url)

**Comment by smalldave** [comment]
Sorry about delay. Injury meant the treadmill lost it's appeal for a bit.

I've attached the logs from running commands in the batch file

[logs.zip](https://github.com/cagnulein/qdomyos-zwift/files/11927304/logs.zip)

**Comment by cagnulein** [comment]
hi @smalldave I hope you are all right now!

About the log: in the log i don't see any metrics, but that's from the system itself. try this way: start the treadmill and change some times the speed and then, without stopping the treadmill, click the dump log button in the companion app.
then download the logcat.txt in the root folder of the tablet 

let me know

**Comment by smalldave** [comment]
Finally had the chance to spend some time on this last night. My problem seems to be the same as https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/54. Looking in wolflogs it says it's turning off logging and then it  doesn't add any more logs. I see you were looking at going direct to the treadmill over USB unlocking the treadmill. That would be amazing. Have any luck with it?

**Comment by cagnulein** [comment]
@smalldave not yet but i guess i fixed it in this way https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

give it a try (first update the companion!)

**Comment by smalldave** [comment]
Will give it a try in a bit. What is the idea, read the metrics from logcat rather than wolflogs? Is QZCompanion 3.3.5 what I need?

**Comment by cagnulein** [comment]
nope select the gran tour pro device for now and restart the treadmill (and just to be sure grant again the permission)
Let me know

**Comment by smalldave** [comment]
Great. That worked and didn't have to grant the permissions again. Weird thing is that the speed in kph doesn't match iFit. So 10 is 9.3, 0 is 0.2 etc. Some times though it will match like it's suddenly picked up the correct speed. That  make any sense? Want me to send you some logs of it happening.

**Comment by cagnulein** [comment]
that's funny: i guess ifit calibrate the speed coming from the firmware with some table inside the software. you can do the same with the speed gain and speed offset setting

**Comment by cagnulein** [comment]
@smalldave yes i will be very interested on the USB thing! Are you able to sniff the usb traffic somehow?

**Comment by smalldave** [comment]
I thought maybe you were able to :). I can have a look into it, do you have any hints?

**Comment by smalldave** [comment]
Had a look into it. Software sniffing seems to need usbmon available in the kernel. I don't think it is and I'm not sure I can do much unless the device is rooted which I'm not sure I want to run the risk of doing.
I'll see if I can get physical access to the usb interface / port and whether I can maybe get a sniffer in between

**Comment by cagnulein** [comment]
yes hardware sniffing could be the perfect solution!

Il giorno mer 30 ago 2023 alle 21:14 David Smith ***@***.***>
ha scritto:
