### ISSUE TITLE
[BUG] Peloton workout doesnt start on fake device

### ISSUE THREAD

**Issue by blautob** [cagnulein/qdomyos-zwift#1522]
I have a (dumb, non-smart) rower, which i want to use with the peloton row classes. i started the peloton workout on the tablet and qz picks up the workout correctly. i have setup my mobile phone as a "fake device" and once i hit "start" nothing happens. the peloton metrics don't change and the remaining time doesn't tick down. 
as the rower is dumb it will never send any details to qz. 

would be great if this can fixed.

**Comment by cagnulein** [comment]
when you will receive the new beta, remember to enable the "continuos move" setting also

**Comment by blautob** [comment]
ah got it. tried a bike class and this works now as expected with the continouos move setting :-D

**Comment by cagnulein** [comment]
done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by blautob** [comment]
hi Roberto

the fake rower device works. but somehow i seem to miss / cant find the peloton rower tiles.

based inb my research the metrics look like this
i would expect target metrics like target stroke rate and pace intensity according to pace intensity levels 

`target_metrics_data": {"target_metrics": [{"offsets": {"start": 60, "end": 62}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 63, "end": 133}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 22.0, "lower": 18.0}, {"name": "pace_intensity", "upper": 0.0, "lower": 0.0}]}, {"offsets": {"start": 134, "end": 185}, "segment_type": "caesar", "metrics": [{"name": "stroke_rate", "upper": 24.0, "lower": 20.0}, {"name": "pace_intensity", "upper": 1.0, "lower": 1.0}]},`

`"pace_intensities":
        [
            {
                "value": 0,
                "display_name": "Easy",
                "pace_levels":
                [
                    {
                        "slug": "level_2",
                        "display_name": "Level 2",
                        "fast_pace": 3.2,
                        "slow_pace": 3.5
                    },
                    {
                        "slug": "level_3",
                        "display_name": "Level 3",
                        "fast_pace": 3.0,
                        "slow_pace": 3.3
                    },
                    {
                        "slug": "level_1",
                        "display_name": "Level 1",
                        "fast_pace": 4.0,
                        "slow_pace": 4.3
                    },
                    {
                        "slug": "level_4",
                        "display_name": "Level 4",
                        "fast_pace": 2.5,
                        "slow_pace": 3.2
                    },
                    {
                        "slug": "level_5",
                        "display_name": "Level 5",
                        "fast_pace": 2.1,
                        "slow_pace": 2.4
                    },
                    {
                        "slug": "level_6",
                        "display_name": "Level 6",
                        "fast_pace": 2.0,
                        "slow_pace": 2.3
                    }
                ]
            },
            {
                "value": 1,
                "display_name": "Moderate",
                "pace_levels":
                [
                    {
                        "slug": "level_2",
                        "display_name": "Level 2",
                        "fast_pace": 3.0,
                        "slow_pace": 3.2
                    },
                    {
                        "slug": "level_3",
                        "display_name": "Level 3",
                        "fast_pace": 2.4,
                        "slow_pace": 3.0`

**Comment by blautob** [comment]
ok i stumbled on this issue https://github.com/cagnulein/qdomyos-zwift/issues/1481

if i understood the target stroke rate would be displayed in the Target Cadence tile.
however for me it stays at 0 for the whole workout on the fake rower device

**Comment by blautob** [comment]
sent via mail

**Comment by cagnulein** [comment]
checked the log, you need to disable the fake device (bike) and restart qz. only one fake device must be enable at a time

**Comment by blautob** [comment]
if i disable fake device (bike) and have only fake rower activated. i stay at the start screen ("This app should automatically connect..."

**Comment by cagnulein** [comment]
send me a log in this scenario
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 giu 2023 alle ore 21:43 blautob ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
my fault @blautob fixed, i will send you another one!

**Comment by cagnulein** [comment]
@blautob sent!

**Comment by blautob** [comment]
It works!

**Comment by blautob** [comment]
Thanks again for your great work

**Comment by cagnulein** [comment]
great!
