### ISSUE TITLE
[REQ] Training programs UI improvement

### ISSUE THREAD

**Issue by blautob** [cagnulein/qdomyos-zwift#1537]
Hi Roberto,

two things that came to my mind for the trainings program:

-would be great to change font size (maybe in the UI themes menu), with more and more training programs the standard font size it quite large and makes scrolling necessary

- once loaded: would be great to have the program name listed in the tile windows (just the same position like the peloton class name, just below the Start button)

- i dont know if it just me but for same folders the folder name is cut to only few characters

Cheers

**Comment by cagnulein** [comment]
Hi @blautob 

> -would be great to change font size (maybe in the UI themes menu), with more and more training programs the standard font size it quite large and makes scrolling necessary

maybe using subfolder could be a better solution? Because reducing the font size it will also reduce the touch area

> * once loaded: would be great to have the program name listed in the tile windows (just the same position like the peloton class name, just below the Start button)

sure, good idea! let me do it!

> * i dont know if it just me but for same folders the folder name is cut to only few characters

yes I saw this too. Are you on android, ios, pc or mac?

**Comment by cagnulein** [comment]
> * once loaded: would be great to have the program name listed in the tile windows (just the same position like the peloton class name, just below the Start button)

done! it will be in the 2.13.85 and above

**Comment by blautob** [comment]
yes i am on ios

subfolder is definately a possibilty (maybe with a user specified template where the completed peloton workouts are e.g. Cycling/Alex Toussaint/*Date*HIIT Ride

**Comment by cagnulein** [comment]
@blautob folder issue fixed! it will be in the next one!
I like the subfolder idea, but the user template sounds no so simple to implement :)

Let's run a poll on the facebook group about it

**Comment by cagnulein** [comment]
@blautob as you can see from the poll everyone wants a different things. So theoretically I should implement the full customization but it's a nightmare from the code prospective. So I'm thinking to leave it as it is or simply set a constraint like your example

Cycling/Alex Toussaint/DateHIIT Ride

thoughts?

**Comment by blautob** [comment]
setting the constraint like Cycling/Alex Toussaint/DateHIIT Ride
would help a lot i guess

**Comment by cagnulein** [comment]
done, it will be in the 2.13.96 and above

**Comment by blautob** [comment]
Hi Roberto, @cagnulein 

after doing several rides i have one improvement request for this functionality:

Would it be possible to save the file with a different date scheme
YY-MM-DD
instead of DD-MM-YY 

this would organize the files much more neatly in chronological order

Cheers

**Comment by cagnulein** [comment]
sure, where are you archiving them?

**Comment by blautob** [comment]
currently still in the built in functionality "Open Train program"

**Comment by cagnulein** [comment]
i will check this possibility in the next days, thanks

**Comment by blautob** [comment]
Exactly
![IMG_4681](https://github.com/cagnulein/qdomyos-zwift/assets/24385671/c05b47ec-91eb-4a06-bdcf-74550178b027)

**Comment by blautob** [comment]
Would still love to have the timestamp renamed to
YY-MM-DD
instead of MM-DD-YY

still beliefe it makes more sense sorting wise

**Comment by cagnulein** [comment]
yes i didn't forget, im doing other peloton fixes and i have this on the
back log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 3 ott 2024 alle 20:41 blautob ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@blautob done! are you on ios?

**Comment by cagnulein** [comment]
Sent!
I added a new peloton setting in the peloton settings to change the format

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle ore 14:53 blautob ***@***.***>
ha scritto:

**Comment by blautob** [comment]
Works great! Thanks Roberto. 
By the way would i need to switch to another testflight now in order to keep getting the newest updates?

**Comment by cagnulein** [comment]
That's great! Nope I'm sending regularly updates to testflight
