### ISSUE TITLE
[BUG] App Crash on Android 6

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#154]
Attached are bugreports and debug - thanks
[debug-Sat Jan 30 09_45_07 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5898430/debug-Sat.Jan.30.09_45_07.2021.zip)
[bugreport-2021-01-30-09-48-13.zip](https://github.com/cagnulein/qdomyos-zwift/files/5898431/bugreport-2021-01-30-09-48-13.zip)

**Comment by cagnulein** [comment]
which android is?

**Comment by ptrinephi** [comment]
android 7.1.2

**Comment by cagnulein** [comment]
@ptrinephi could you try with the current beta?

**Comment by ptrinephi** [comment]
I just finished a 30mn ride and it worked fine, will continue tests.

**Comment by ptrinephi** [comment]
Looks like beta 2.3.33 broke the connection, debug files attached


[debug-Thu Feb 25 21_21_06 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047552/debug-Thu.Feb.25.21_21_06.2021.log)
[debug-Thu Feb 25 21_20_01 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047553/debug-Thu.Feb.25.21_20_01.2021.log)
[debug-Thu Feb 25 21_21_55 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047555/debug-Thu.Feb.25.21_21_55.2021.log)
[debug-Thu Feb 25 21_20_44 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047556/debug-Thu.Feb.25.21_20_44.2021.log)
[debug-Thu Feb 25 21_23_16 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047557/debug-Thu.Feb.25.21_23_16.2021.log)

**Comment by cagnulein** [comment]
Which was the last working version that you used? Did you try to reboot
your phone?


Il ven 26 feb 2021, 06:36 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
After rebooting I was able to connect but the connection is unstable.  It connects then disconnects after a little while.
I try to upgrade every day so I believe I had the previous beta version.

[debug-Thu Feb 25 21_55_34 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047657/debug-Thu.Feb.25.21_55_34.2021.log)
[debug-Thu Feb 25 21_54_32 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047658/debug-Thu.Feb.25.21_54_32.2021.log)
[debug-Thu Feb 25 21_55_48 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047659/debug-Thu.Feb.25.21_55_48.2021.log)
[debug-Thu Feb 25 21_54_47 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047660/debug-Thu.Feb.25.21_54_47.2021.log)

**Comment by ptrinephi** [comment]
I'm pretty sure I was running 2.3.29

**Comment by cagnulein** [comment]
Did you already try to reboot?
Because i didn't change anything in these version for your side

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 feb 2021 alle ore 07:03 3phi <notifications@github.com> ha
scritto:

**Comment by ptrinephi** [comment]
Yes, I rebooted the bike and the phone

------ Original Message ------

**Comment by cagnulein** [comment]
Does it work with other phones that you have?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 feb 2021 alle ore 07:06 3phi <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment]
the only thing that i did, even in the 2.3.29 for android 6, is to remove the wake lock. so be sure the screen is on. i'm pushing the 2.3.34 but i didn't change anything about this...looking the log, seems that the bikes doesn't answer to the init commands :(

**Comment by ptrinephi** [comment]
It works with my S9 but it takes about 10seconds to connect.  My S9+ is 
still on 2.3.29 and it connects within 1 second.

------ Original Message ------

**Comment by cagnulein** [comment]
try to exit from the beta to your android 6 and see if it solves the issue. maybe try also to uninstall the beta and reinstall it back on android 6

**Comment by cagnulein** [comment]
maybe something about the cache

**Comment by ptrinephi** [comment]
I uninstalled and reinstalled with the same result.  How do I exit from 
beta?  would that also get me out of beta from my other devices?

------ Original Message ------

**Comment by cagnulein** [comment]
On the play store page. Yes i guess if you exit you will be kick out for
all your devices. But you can join later without issue

Il ven 26 feb 2021, 07:35 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
What I noticed with the release is when start the app it shows another 
BT device as found, stays there for a few seconds then finds the bike 
(same on android 6 and 10).  On 2.3.29 it finds the bike right away and 
connects.
On my android 7 with 2.3.33 it finds the bike right away, displays the 
tiles for a few seconds then connects and disconnects right away.  The 
tiles screen stays on and I can hear the bike beeps connect and 
disconnect very quickly.

------ Original Message ------

**Comment by ptrinephi** [comment]
I'll try that tomorrow if I have the same issue with your next release.

------ Original Message ------

**Comment by ptrinephi** [comment]
It worked ok today with 2.3.34, I think it might have been a BT interference.  Only problem I have now on this android is the HR disconnects and does not reconnect.

**Comment by cagnulein** [comment]
Are you sure that some other devices are unpaired with the HRM?

Il sab 27 feb 2021, 02:48 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
Yes, the HR is only connected to QZ

------ Original Message ------

**Comment by cagnulein** [comment]
At the end of the workout, if you try to close qz and reopen it's the heart
rate comes up again?

Il sab 27 feb 2021, 07:21 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
Yes, everytime I close QZ and reopen it reconnects.

------ Original Message ------

**Comment by cagnulein** [comment]
Could you send me again a log of a session with this behavior?
Thanks

Il sab 27 feb 2021, 07:28 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
Ok, I'll do that over the weekend, enjoy yours

⁣

**Comment by ptrinephi** [comment]
Version 2.3.4 does not connect at all.  IT sees the bike then displays the tiles but that's it.  
[debug-Sun Feb 28 18_07_36 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6058750/debug-Sun.Feb.28.18_07_36.2021.log)
[debug-Sun Feb 28 18_07_03 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6058751/debug-Sun.Feb.28.18_07_03.2021.log)
[debug-Sun Feb 28 18_06_29 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6058752/debug-Sun.Feb.28.18_06_29.2021.log)
[debug-Sun Feb 28 18_05_58 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6058753/debug-Sun.Feb.28.18_05_58.2021.log)

**Comment by cagnulein** [comment]
Again, i didn't touch anything. I think you have something on your setup
that comes and goes away. It's not strictly related to the version

Il lun 1 mar 2021, 03:21 3phi <notifications@github.com> ha scritto:

**Comment by ptrinephi** [comment]
Version 2.6.1

The resistance moves up and down constantly.

[debug-Mon_Apr_12_21_35_18_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6301310/debug-Mon_Apr_12_21_35_18_2021.log)
[debug-Mon_Apr_12_21_39_48_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6301311/debug-Mon_Apr_12_21_39_48_2021.log)
[debug-Mon_Apr_12_21_40_41_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6301312/debug-Mon_Apr_12_21_40_41_2021.log)

**Comment by cagnulein** [comment]
tell me more about this scenario: i mean in the 2.6 i didn't do anything
about training program. so what were you doing? training program? which one?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 apr 2021 alle ore 06:52 3phi ***@***.***> ha
scritto:

**Comment by ptrinephi** [comment]
When I enable training program random option the bike goes crazy with the resistance and stops as soon as I turn it off.  The interval is set to 30sec.

**Comment by cagnulein** [comment]
i guess i got it, just start ride it, and when the elapsed go to a
different value from 0:00:00 the resistance will follow the rand program.
I will fix ths
R.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 apr 2021 alle ore 07:53 3phi ***@***.***> ha
scritto:

> When I enable training program random option the bike goes crazy with the
> resistance and stops as soon as I turn it off.  The interval is set to
> 30sec.
>
>
>
>

**Comment by ptrinephi** [comment]
Thanks

⁣

**Comment by ptrinephi** [comment]
Version 2.6.5 training program random option still drives the resistance crazy.

**Comment by cagnulein** [comment]
Could you please share the log?

Il gio 15 apr 2021, 23:37 3phi ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@ptrinephi do you still have this? i'm closing this one. in case you still need help, reopen it :)
