### ISSUE TITLE
[BUG] ANT+ not working

### ISSUE THREAD

**Issue by DoctorMeltdown** [cagnulein/qdomyos-zwift#1548]
**Describe the bug**
ANT+ features not working on Samsung tablet with built in ANT+ hardware and running Android 11.

**To Reproduce**
1. Enable ANT+ features in settings and restart
2. ANT+ output and HR reading not working

**Screenshots**
![signal-2023-07-04-112836_002](https://github.com/cagnulein/qdomyos-zwift/assets/138611470/9d2ef225-be8e-48dd-80cf-51f092af8b9d)

**Possible Solution:**
 It seems there was an update to ANT+ services on Android, now requiring:
-Android ANT Lib 4.16 on devices running Android 11 or higher
-Android ANT+ Plugin Lib 3.9.0 on devices running Android 11 or higher

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks @DoctorMeltdown i'm trying to do this in the next hours. I will send you a message here when I'm ready to test this out!

**Comment by DoctorMeltdown** [comment]
Great! Thanks a bunch @cagnulein. I applied for beta access in google play. Let me know if there are any other steps I'll need to take to be able to test it.

**Comment by cagnulein** [comment]
@DoctorMeltdown nope exit from the beta, i will invite you in the private beta when i will be ready

**Comment by cagnulein** [comment]
ok version 4.16 available here https://github.com/ant-wireless/ANT-Android-SDKs/tree/master/ANT_Android_SDK/API (note for me)

**Comment by cagnulein** [comment]
@DoctorMeltdown it's building, 
send me an email to roberto.viola83 at gmail.com indicating this ticket . Thanks

**Comment by DoctorMeltdown** [comment]
@cagnulein 
Email sent!

**Comment by cagnulein** [comment]
@DoctorMeltdown I'm having a crash with the new library, I'm trying to figure it out. I thought it could be easy but I already spent 4 hours on this. I will resume this tomorrow (11pm here in Italy:) )

**Comment by cagnulein** [comment]
@DoctorMeltdown https://github.com/cagnulein/qdomyos-zwift/assets/48216/e735da5b-074d-4248-9611-ffaf9f07f7e3

it works! i'm uploading the 2.13.93 !

**Comment by cagnulein** [comment]
@DoctorMeltdown 2.13.93 available on the store!

**Comment by DoctorMeltdown** [comment]
@cagnulein NICE!! I just tested and it's working on my end too. I can see the power and cadence sensors on my garmin over ANT+. It also works on my phone using the Garmin ANT+ usb dongle!! So both built-in ANT+ hardware and the usb dongle works!
Thanks a bunch for working on this!

**Comment by cagnulein** [comment]
just a note for me for the next time that I had to update the ANT+ library:
- download the new aar
- unzip original_lib.aar -d out/
- cd out/
- zip -d classes.jar "com/dsi/ant/channel/PredefinedNetwork.class"
- jar cvf ../my_new_lib.aar *

then use the generated aar into QZ, enjoy it ;)

**Comment by BrettPrintz** [comment]
Does this fix the speed coming from QZ to Garmin? The speed was always all wacky saying 130+ km/HR

**Comment by cagnulein** [comment]
@BrettPrintz yes! be sure to set the manual wheel ratio on your garmin  to 100mm

**Comment by BrettPrintz** [comment]
Works for me!!

**Comment by cagnulein** [comment]
great @BrettPrintz  ! sorry to took so long!
