### ISSUE TITLE
[BUG] Proform TDF 2.0 and Ifit integration - Incline not adjusting as expected

### ISSUE THREAD

**Issue by CAR1800** [cagnulein/qdomyos-zwift#1549]
**Describe the bug**
Set up - I'm using a TDF 2.0 connected via wifi to my android phone (S23). I'm using the phone to simulate as a device for my android tablet (S3) to connect to via bluetooth and run the Ifit app on the tablet.

When I start QZ it connects to the bike, however the include section on the QZ app seems to stay at 0 when i change the incline. If I change the incline on the QZ app it doesn't do it correctly. Then when I connect to Ifit it increase the incline a lot (too much, ie. Should be 1% and is 9%) at the start and then doesn't adjust it again during a ride as the incline changes.

I've tried using the Zwift incline section in the advance settings but couldn't get this to work.

**To Reproduce**

Unsure how to reproduce, as is a lack of expected function rather than a specific action bug

**Expected behavior**
To run Ifit on my tablet and connect that to my phone running QZ which will correctly control the bike for changes of incline and resistance whilst reporting back performance on RPM etc to Ifit.

**Screenshots**

**Desktop (please complete the following information):** 

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS: Latest stable release
 - Version unsure

**Append a debug log**  Logs attached - I hope I got the right bits.

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
![Tue Jul 4 18_52_21 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/e14b41ce-cb60-47a8-b098-5a7bd813fccf)
![Tue Jul 4 18_52_21 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/a1dfa834-33df-4ba1-9800-305d638b0a6a)
![Tue Jul 4 18_52_21 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/5c562142-d3d7-4282-8eac-8abe3cfb1d90)
![Tue Jul 4 18_52_21 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/51c88d34-9502-4586-ba79-7f25846c155b)
![Tue Jul 4 18_52_21 2023_res
![Tue Jul 4 18_52_21 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/da6de8f0-089e-4b99-87b6-780f5d146d3f)
![Tue Jul 4 18_31_49 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/edcdac25-4000-4006-af00-2b812cdb01de)
![Tue Jul 4 18_31_50 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/8f41e761-d847-4626-b1d2-9544e25bcd77)
![Tue Jul 4 18_31_51 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/6a788bdd-4592-4cd9-89ed-dd7fbaa63dd4)
![Tue Jul 4 18_31_51 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/105fa418-7b4c-43af-a89a-e4da6e2c02bc)
![Tue Jul 4 18_48_48 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/724a4f77-3e3c-4ee6-9449-43382ae7f986)
![Tue Jul 4 18_48_49 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/b4ab798d-910f-4dd7-afc0-666db64714dc)
![Tue Jul 4 18_52_21 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/0cfdc428-da7f-4cc6-b0c1-0678c934863e)
![Tue Jul 4 18_52_21 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/496dcf1d-28a0-4c29-be0e-5b05e8905bd0)
![Tue Jul 4 18_52_21 2023_pow
![Tue Jul 4 18_48_49 20
![Tue Jul 4 19_09_34 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/bedf6fb9-30a2-406f-8ba0-0350247ecbb5)
![Tue Jul 4 19_09_34 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/e9e54ddc-54d3-4a24-a312-9f5da188011f)
![Tue Jul 4 18_52_20 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/c47ae7d3-18ef-49bd-af23-e62456ef4a69)
![Tue Jul 4 18_55_34 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/341db3a9-605a-4e21-8728-d0b02831f9ac)
![Tue Jul 4 18_58_38 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/6c4607cd-8552-4392-80dd-a67b3f4fbd68)
![Tue Jul 4 18_58_38 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/4a09b90b-7cd9-4427-ad9b-b83e9622b0fe)
![Tue Jul 4 18_58_42 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/e64b6c78-1e80-436e-91a4-099cc415c4d5)
![Tue Jul 4 18_58_42 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/9c1b0292-464c-4353-81f2-3d7cd45945ce)
![Tue Jul 4 18_58_42 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/e05b66ea-4d6f-46fd-a6da-da6fc38725ed)
![Tue Jul 4 18_58_42 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/312e5f28-89ab-483c-b685-a66a5c1d578f)
![Tue Jul 4 19_09_34 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/aea80de2-72a4-4e2f-a84a-4691722f2739)
![Tue Jul 4 19_09_34 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/7edb6b5c-ac74-4e35-b6c4-8681ea9fd60e)

![Tue Jul 4 18_48_48 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/3a0f3ff6-3119-4e20-addd-637ca02685ad)
![Tue Jul 4 18_48_49 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/b992c1c9-8815-4446-a651-366199d9be30)
23_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/0
![Tue Jul 4 19_09_33 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/b6e9dc91-0e8b-42c5-a068-85f44a3e413c)
![Tue Jul 4 19_09_33 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/67cde7b4-5c1a-4e8f-9c96-9603f79c9c3f)
[debug-Tue_Jul_4_17_56_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11952402/debug-Tue_Jul_4_17_56_17_2023.log)
![Tue Jul 4 19_09_34 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/be6b03e4-fe4e-4573-b900-ed66cc32473f)
![Tue Jul 4 19_09_34 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/fdea7d10-be27-47c9-8384-b05c4aa52e34)
d731e57-0688-4602-bfb9-b4bdfc342787)
![Tue Jul 4 18_52_20 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/5346e91f-2c20-443f-97c7-3a91b368b48e)
![Tue Jul 4 18_58_37 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/d97c968c-a170-49a7-ab04-7b59811e9d1e)
![Tue Jul 4 18_58_38 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/3e4ae9c6-3edc-41c5-8862-ac0aa434ef4b)
![Tue Jul 4 18_58_38 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/6f076687-af30-48b8-b69e-c5b45e0628d7)
er](https://github
![Tue Jul 4 18_58_37 
[debug-Tue_Jul_4_18_31_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11952401/debug-Tue_Jul_4_18_31_58_2023.log)
2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/da8238a6-bfe4-4c9d-abc8-9602cd77624b)
.com/cagnulein/qdomyos-zwift/assets/138626552/80638c49-7195-4de0-9deb-e996ad6def0d)
![Tue Jul 4 18_52_21 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/b47bf312-81cd-49bd-87bd-afbfc940bce0)
![Tue Jul 4 18_52_21 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/d1e5d8cc-58e3-47bd-ab43-78f72242d15b)
istance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/fb634cc0-8014-45e2-a06e-0613be0a3b2d)
![Tue Jul 4 18_52_21 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/68e57a93-6000-4671-98f7-e2533fcc800b)

**Comment by cagnulein** [comment]
hi @CAR1800 the debug log seems truncated, could you please generate again the issue and send me a new one? thanks

**Comment by CAR1800** [comment]
Hi

I tried to replicate the issue but the recording is short because it goes crazy and you cant really continue the workout and the bikes onboard computer gets paused and you cant seem to unpause it

I connected the bike the QZ on my phone. Then i just cycles for a bit and you can see it records most stats correctly however I tried to adjust the incline on the bike and it dosent record this on QZ and visa versa when I try to adjust incline using the app the bike detects it, dosent move how it should and then pauses the bikes computer and crashes it until you disconnect the bike and start again.

Then when I connect to Ifit the same continues to happen, so I dont know if its an issue between QZ and the bike or Ifit and QZ.

I've attached what are hopefully better debug reports. I cant seem to upload the .fit files to Github

I've done my best to try and work out the settings to be as accurate as possible for what I need. I did find your youtube video showing Ifit & QZ working but I couldnt see any instructions attached to it. 

Thanks

![Wed Jul 5 12_57_20 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/e80471fd-f604-463e-b718-e81a496a8c82)
![Wed Jul 5 12_57_20 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/1da0a4dd-c911-4111-b03f-86108b72f8af)
![Wed Jul 5 12_57_20 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/635fcd4d-cee6-42cf-a60e-bb70ae4fee56)
![Wed Jul 5 12_57_20 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/90e2804f-f109-4eeb-97ba-e34c8fd26d50)
![Wed Jul 5 12_57_19 2023](https://github.c
[debug-Wed_Jul_5_12_53_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11957714/debug-Wed_Jul_5_12_53_48_2023.log)
![Wed Jul 5 12_57_19 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/5740ae6d-2f17-4d60-acc8-7778c5982541)
![Wed Jul 5 12_57_20 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/a066b8fb-0b56-4df7-a4b8-7d85d7226c45)
[debug-Wed_Jul_5_12_39_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11957716/debug-Wed_Jul_5_12_39_25_2023.log)
om/cagnulein/qdomyos-zwift/assets/138626552/8c66785d-f72e-47ee-b8b9-4cee2f54cdd8)
![Wed Jul 5 12_57_20 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/53f7276d-964e-416a-957d-f184896c1ba9)

**Comment by CAR1800** [comment]
yeah, the incline is too steep. and once it is set it dosen't change again as you cycle through the workout program

That's why I set to -9 to try and offset it going to steep. I think maybe i need to be able to put a fraction ie 0..5 in the zwift inclination gain? 

Do you know what the ifit incline number is for flat?

Also the issue is that I dont think QZ sets the bike incline correctly. Can you see that in the data?

**Comment by CAR1800** [comment]
Cool - I'll try it this evening

**Comment by CAR1800** [comment]
Hi Roberto, I tried and I'm still suffering an issue. I think it is between QZ and the bike. I just connected Qz to the bike to see if it worked and ignored Ifit for now. I recorded a video of what happened to help show the issue. Apologies for the quality, I had to compress quite a lot to upload.

As you can see QZ dosen't recognize changes in the incline and when I try to adjust the bike using Qz it crashes the manual programme so that you have to exit it and start again.

I hope you can see what I mean in the log/video.
[debug-Wed_Jul_5_19_06_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11960798/debug-Wed_Jul_5_19_06_25_2023.log)
[debug-Wed_Jul_5_19_00_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/11960799/debug-Wed_Jul_5_19_00_13_2023.log)
[debug-Wed_Jul_5_19_06_25_2023_1.log](https://github.com/cagnulein/qdomyos-zwift/files/11960800/debug-Wed_Jul_5_19_06_25_2023_1.log)
![Wed Jul 5 19_09_43 2023](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/9870119f-da4a-42ab-a3e8-e611d198abe2)
![Wed Jul 5 19_09_44 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/4e4cdece-6b9b-4435-ac9d-ea85e14baeef)

https://github.com/cagnulein/qdomyos-zwift/assets/138626552/3008d1c1-d877-4833-957a-bdbcb1b51eb4


![Wed Jul 5 19_09_44 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/2f35c44c-a084-4a5a-904d-c21b2a04b268)
![Wed Jul 5 19_09_44 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/f647ded9-d1a3-48aa-a92b-16bc96b91adb)
![Wed Jul 5 19_09_44 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/dda6cad1-9670-4ae0-9ea7-aa7d33a8f5d7)
![Wed Jul 5 19_09_44 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/5ba0910b-d74d-4959-a14b-f863aed77cf5)
![Wed Jul 5 19_09_44 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/740d5994-a2d4-450f-ab02-e492718f100d)
![Wed Jul 5 19_09_45 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138626552/2002d812-34e9-4902-86e2-324f22ebb376)

Thanks

**Comment by cagnulein** [comment]
ok 
send me an email to roberto.viola83 at gmail.com indicating this ticket: I would like to send you the latest version for android in order to check that I didn't already fix this. Thanks
