### ISSUE TITLE
[BUG] App Crash on Android 7 connecting to Echelon

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#155]
Beta 2.3.5 connects fine to PROFORM bike but when attempting to connect to android 7 the app crashes right after detecting the bike and displaying the data boxes for 1 second.  The bike makes 1 beep a pause and 2 quick beeps.

Attached are debug logs and bug report
[bugreport-NJH47F-2021-01-30-10-02-47.zip](https://github.com/cagnulein/qdomyos-zwift/files/5898448/bugreport-NJH47F-2021-01-30-10-02-47.zip)

[debug-Sat Jan 30 09_48_37 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5898441/debug-Sat.Jan.30.09_48_37.2021.zip)

**Comment by ptrinephi** [comment]
Beta 2.3.6 crash

[bugreport-NJH47F-2021-01-31-09-58-05.zip](https://github.com/cagnulein/qdomyos-zwift/files/5900389/bugreport-NJH47F-2021-01-31-09-58-05.zip)
[debug-Sun Jan 31 09_56_44 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/5900391/debug-Sun.Jan.31.09_56_44.2021.zip)

**Comment by ptrinephi** [comment]
With Beta 2.3.11 it no longer crashes but is does not connect to the echelon bike.

[debug-Sun Feb 7 23_18_19 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5941871/debug-Sun.Feb.7.23_18_19.2021.log)
[debug-Sun Feb 7 23_17_56 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5941872/debug-Sun.Feb.7.23_17_56.2021.log)
[debug-Sun Feb 7 23_19_05 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5941873/debug-Sun.Feb.7.23_19_05.2021.log)

**Comment by ptrinephi** [comment]
2.3.29
[debug-Wed Feb 24 11_05_26 2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/6040266/debug-Wed.Feb.24.11_05_26.2021.zip)
[bugreport-NJH47F-2021-02-24-18-55-11.zip](https://github.com/cagnulein/qdomyos-zwift/files/6040249/bugreport-NJH47F-2021-02-24-18-55-11.zip)

Still unable to connect to echelon bike then crashes

**Comment by ptrinephi** [comment]
2.3.33, still unable to connect.  The app displays the tiles even though the bike is not connected, the mike makes 2 quick beeps and that's it. 

[debug-Thu Feb 25 21_54_05 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047666/debug-Thu.Feb.25.21_54_05.2021.log)
[debug-Thu Feb 25 21_53_49 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6047667/debug-Thu.Feb.25.21_53_49.2021.log)

**Comment by ptrinephi** [comment]
Version 2.6.3.  Unable to connect to the bike.  The blue light blinks, the bike beeps and QZ shows the tiles  but no connection.  This is on my Xperia Z3+ newly reinstalled with fresh android 7.

[debug-Wed_Apr_14_19_35_11_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6312383/debug-Wed_Apr_14_19_35_11_2021.log)
[debug-Wed_Apr_14_19_35_39_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6312384/debug-Wed_Apr_14_19_35_39_2021.log)
[debug-Wed_Apr_14_19_34_52_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6312385/debug-Wed_Apr_14_19_34_52_2021.log)

**Comment by cagnulein** [comment]
Do a power cycle to your bike. It doesn't answer. Other echelon users with
this app confirmed me that it's working good.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 apr 2021 alle ore 18:37 3phi ***@***.***> ha
scritto:

**Comment by ptrinephi** [comment]
I did and it made no difference.

------ Original Message ------

**Comment by cagnulein** [comment]
But it's a new phone?
try to disable the manual device setting

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 apr 2021 alle ore 20:15 3phi ***@***.***> ha
scritto:

**Comment by ptrinephi** [comment]
It's my old sony phone that I reflashed with the factory firmware.  I 
disabled the manual device and still no luck

------ Original Message ------

**Comment by cagnulein** [comment]
Try to go out from the beta, just to be sure.

Il mer 14 apr 2021, 20:55 3phi ***@***.***> ha scritto:

**Comment by ptrinephi** [comment]
Now running 2.5.22.  Recycled the bike and the phone after reinstall but same result.

[debug-Thu_Apr_15_03_40_04_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314467/debug-Thu_Apr_15_03_40_04_2021.log)
[debug-Thu_Apr_15_03_41_01_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314468/debug-Thu_Apr_15_03_41_01_2021.log)
[debug-Thu_Apr_15_03_39_22_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314469/debug-Thu_Apr_15_03_39_22_2021.log)
[debug-Thu_Apr_15_03_46_04_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314470/debug-Thu_Apr_15_03_46_04_2021.log)
[debug-Thu_Apr_15_03_44_56_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314471/debug-Thu_Apr_15_03_44_56_2021.log)
[debug-Thu_Apr_15_03_45_38_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314472/debug-Thu_Apr_15_03_45_38_2021.log)
[debug-Thu_Apr_15_03_45_21_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6314473/debug-Thu_Apr_15_03_45_21_2021.log)

**Comment by cagnulein** [comment]
So you have something on your bike or phone not QZ itself.
Try the echelon app

Il gio 15 apr 2021, 02:50 3phi ***@***.***> ha scritto:

**Comment by ptrinephi** [comment]
Yeah, the bike works fine with my other phone.  It's this phone BT!  I wonder if I can upgrade the BT stack by itself on this phone!

**Comment by cagnulein** [comment]
Eheheh i don't think so. You should try a custom rom

Il gio 15 apr 2021, 18:31 3phi ***@***.***> ha scritto:

**Comment by ptrinephi** [comment]
Something with the phone.  Same issue after installing a different custom rom!

**Comment by cagnulein** [comment]
@ptrinephi do you still need help? i'm closing this one, in case feel free to reopen it!

**Comment by ptrinephi** [comment]
Close it thanks, I'm not using that phone anymore.
