### ISSUE TITLE
[BUG] Echelon bike staying on max resistance during auto resistance 

### ISSUE THREAD

**Issue by VeePags** [cagnulein/qdomyos-zwift#1556]
**Describe the bug**
I have not changed any settings in my app, but during my Peloton ride yesterday, with my settings on auto-resistance , my Echelon bike went immediately to max-resistance and stayed there for most of the ride. I had to turn auto-resistance off and adjust manually.   

**Expected behavior**
I would like auto-resistance to work properly on my bike. It has been working fine up until yesterday, and I have been using this app for close to 2 years. 

**Screenshots**
I cannot figure out how to save and access my settings file. Here are screenshots of my current settings. 
![IMG_2638](https://github.com/cagnulein/qdomyos-zwift/assets/139138903/07b07c8e-0374-4ad9-92f2-23df615bc644)
![IMG_2639](https://github.com/cagnulein/qdomyos-zwift/assets/139138903/d1b93890-f07c-414b-8893-e5527edf8493)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.5.1
 - Version iOS 

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
My debug log is not saving.

**Comment by cagnulein** [comment]
@VeePags what do you mean about the debug log? did you enable the debug log setting and restarted qz? Do you see the qdomyos-zwift folder on your files app?

**Comment by VeePags** [comment]
Yes I did that , and I do not see anything saved in my files folder.

**Comment by VeePags** [comment]
Are my settings in these screenshots correct? I have not changed anything so I’m not sure why it just stopped working all of a sudden.
