### ISSUE TITLE
[REQ] Google Fit integration

### ISSUE THREAD

**Issue by cfharp** [cagnulein/qdomyos-zwift#1571]
As a non-subscription user (aka casual rider) it would be nice to have my rides sync to Google Fit for tracking stats. I created a Strava account and have rides syncing there, and have Strava and Google Fit connected, but rides don't automatically sync (seems like a decision made by the Strava team to not have rides sync from outside of Strava -> Strava -> back outside of Strava). As a manual workaround, you can edit a Strava ride (on an Android device) and that will then sync it to Google Fit, but this needs to be done for each ride individually. If QZ could have a built-in connection directly to Google Fit and send over rides like Strava (i.e. send ride when clicking 'stop') that would be awesome.

**Comment by cagnulein** [comment]
thanks i will add this on 2.14

**Comment by cagnulein** [comment]
ok i will start this reading the HR from any wearos device, then i can also write the activities

**Comment by daroczig** [comment]
I'm also looking for a solution on this (and marking #1613 as related). In the meantime: are there any other free providers we can use to sync to keep track of history? Preferably a vendor that also provides API access :)

**Comment by daroczig** [comment]
> maybe this one https://play.google.com/store/apps/details/Health_Sync?id=nl.appyhapps.healthsync&hl=it ?

I'm not sure if `qdomyos-zwift` is supported by this app, so I don't know how to push the data collected by `qdomyos-zwift`.

**Comment by cagnulein** [comment]
qz writes to strava, so you can sync strava to google fit @daroczig 
anyway as i suggested in another thread, why don't you use MQTT from QZ?

**Comment by cagnulein** [comment]
Done in the version 2.21.5
