### ISSUE TITLE
[REQ] 2023 Sole F80 integration

### ISSUE THREAD

**Issue by moosepearson** [cagnulein/qdomyos-zwift#1576]
**Is your feature request related to a problem? Please describe.**
The newest release of the Sole F80 breaks compatibility with the app. The app will connect with the treadmill, but all the tiles remain at zero, and cannot control the treadmill.

**Describe the solution you'd like**
Ability to have realtime information in the app as well as to control the treadmill from the app.

**Additional context**
Attached a bluetooth log from using the Sole+ app to control the treadmill. The app does not control speed, these buttons are disabled. It does control start, stop, and incline.
In the log, the app is used to Start treadmill->increase incline from 0 to 1->incline from 1 to 2->incline from 2 to 3->incline from 3 to 2->incline from 2 to 1-> incline from 1 to 0->stop treadmill
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12143320/btsnoop_hci.log)

**Comment by cagnulein** [comment]
done @moosepearson ! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by cagnulein** [comment]
@moosepearson any news?

**Comment by moosepearson** [comment]
Yes! Sorry! I thought I had responded. But yes, once I got on the beta I
was able to connect perfectly. It doesn't control speed or incline, but it
does receive data from the tread which was my main goal.

**Comment by cagnulein** [comment]
Great!
