### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JamesLunardi** [cagnulein/qdomyos-zwift#1578]
**Describe the bug**
I've gone through the setup guide and some instructions I've seen on here to configure things for Zwift, so I've set the Zwift offset to 18 and I've also set the resistance at startup to 10. I've got my chest HR sensor connected. All looks good.
The issue I seem to have is I switch on the bike and open the app and it connects and I hear and see it change the resistance setting to 10 (as per the resistance at startup setting) I then start Zwift and connect the device (I can connect 4 of the 5 options, power, controllable, cadence and HR) they show the name as iPhone 13 Pro 200. 
I then choose a world and a map and then as soon as the map starts the resistance changes to 1 and I'm basically just spinning. If I try to manually change the resistance I see it go up and then jump straight back to 1. If I disable the auto resistance and then manually change up to 18 (the offset that I configured in the app) it feels about right. 
So just not sure why when I'm connected to Zwift does it change the resistance to 1 and seemingly ignores the offset.

**To Reproduce**
1. Switch on bike
2. Connect iPhone app to bike 
3. Resistance sets to 10 as per the startup setting
4. Confirm Zwift offset is set to 18
5. Open zwift on iPad
6. Connect power, controllable, cadence and HR
7. Open Zwift map 
8. Resistance automatically changes to 1

**Expected behavior**
I expect resistance to be set to 18 as per the zwift offset setting

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Device: iPad
 - OS: iOS 16.6
 - Version: iPad (7th Generation)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 16.5.1 (c)
 - Version: iPhone 13 Pro

**Append a debug log**
[debug-Tue_Jul_25_08_29_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12158510/debug-Tue_Jul_25_08_29_37_2023.log)

**Additional context**
N/A

**Comment by cagnulein** [comment]
the resistance goes to 1 because you set up qz as a zwift erg mode session. Are you doring a zwift erg workout? If not you have to disable the zwift erg setting in qz as well
let me know

**Comment by JamesLunardi** [comment]
Thanks @cagnulein that has fixed it! I did't even know what ERG mode was I just thought I read it needed to be enabled when using zwift. I've disabled it and it works exactly as expected now. Thanks!

**Comment by cagnulein** [comment]
Glad it worked! Remember to rate the app on the app store if you didn't already! It means a lot to me! Thanks!
