### ISSUE TITLE
[BUG] - Power not showing in Watt Tile and Power Zone Tile

### ISSUE THREAD

**Issue by afeith** [cagnulein/qdomyos-zwift#1579]
I have a custom-made power and cadence meter that broadcasts via Bluetooth.  I can connect to QZ and everything works except the Watt Tile (Power).  Strangely, it shows the min and max values in the small font but the overall tile remains at 0.  The Zone Tile is also not updating.  I have attached the debug log.
[debug-Tue_Jul_25_09_07_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12161838/debug-Tue_Jul_25_09_07_12_2023.log)

**Comment by cagnulein** [comment]
put the "cadence sensor" setting to disabled and also the cadence sensor as
bike
then enable the "power sensor as a bike" and also set the sensor to the
power sensor setting and restart QZ
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 25 lug 2023 alle ore 15:42 afeith ***@***.***>
ha scritto:

**Comment by afeith** [comment]
yup, got it to work.  closing the issue.  thank you!
