### ISSUE TITLE
[REQ] Ramp Test to identify my maximal aerobic power (MAP)

### ISSUE THREAD

**Issue by ndevries84** [cagnulein/qdomyos-zwift#1584]
**Is your feature request related to a problem? Please describe.**
I'm looking into do some Sprint Interval Training (SIT) exercises, and improving my VO2Max, and I don't have a VO2Max machine to track my progress.

**Describe the solution you'd like**
It's a ramping test where the effort starts at 100w and every 1 minute ramps up 25 watts, until you can no longer continue. This article explains it beautifully https://www.cyclecoach.com/blog/2019/1/13/ramp-testing

**Describe alternatives you've considered**
I use this website to download a zwift file, upload to your app and fill in the appropriate field to determine it https://zwifthacks.com/app/map-ftp-calculator/

**Additional context**
This allows you to do something similar to that Carole is doing with SIT, although they brand it as REHIT.  
https://michaelkummer.com/health/carol-hiit-bike-review/

**Comment by cagnulein** [comment]
@ndevries84 you can simple create a workout like this using the https://www.zwiftworkout.com/editor/m4irlmpfnv and copy  it on the train program folder on qz!

Let me know!
