### ISSUE TITLE
[BUG] Incorrect Watt value on Echelon bike at 90RPM

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#159]
Beta 2.3.7

Please see attached image.  When going from cadence 89 UP TO 90 you'll notice that the power goes from 113 DOWN TO 103.  This happens at every resistance and only between 89 and 90 cadence.

When using the echelon app, cadence 90, 91, 92 show 115, 117, 119 watt respectively.

This would surely mess up the watt avg.

![2021-02-01_14-29-53](https://user-images.githubusercontent.com/6604478/106527135-a07a2500-649b-11eb-8d1d-23bbdeda6d4b.png)

**Comment by cagnulein** [comment]
Duplicate #95
