### ISSUE TITLE
Grand Tour Pro

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1591]
[debug-jeu__août_3_11_58_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12249525/debug-jeu__aout_3_11_58_01_2023.log)
[debug-jeu__août_3_11_46_45_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12249526/debug-jeu__aout_3_11_46_45_2023.log)
[debug-jeu__août_3_11_27_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12249527/debug-jeu__aout_3_11_27_05_2023.log)
[debug-jeu__août_3_11_17_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12249528/debug-jeu__aout_3_11_17_00_2023.log)

**Comment by lseufer** [comment]
[77.txt](https://github.com/cagnulein/qdomyos-zwift/files/12249706/77.txt)
[83.txt](https://github.com/cagnulein/qdomyos-zwift/files/12249707/83.txt)
[84.txt](https://github.com/cagnulein/qdomyos-zwift/files/12249708/84.txt)

**Comment by cagnulein** [comment]
ok 83 and 84 doesn't have metrics on it but 77 does. Maybe in the 77 you did something different? The timestamp is from last night I guess

**Comment by cagnulein** [comment]
`adb logcat -b all -d >  /storage/sdcard0/logcat.log`

**Comment by cagnulein** [comment]
https://github.com/termux/termux-app/issues/1821

**Comment by cagnulein** [comment]
adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS

**Comment by cagnulein** [comment]
@victorypoint FYI adb logcat, by default, from the app, reads only the log of the app. So i added a new permission to read the system wide log. Let's see if it works

**Comment by cagnulein** [comment]
`adb shell dumpsys package org.cagnulein.qzcompanionnordictracktreadmill | grep permission    `

**Comment by cagnulein** [comment]
it works @victorypoint

just another information: the 

`adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS`

works only when logcat runs in the same package, not using adb.

**Comment by cagnulein** [comment]
so actually the instructions are:

- install the companion
- set the grand tour pro device in the companion
- grant the permission with `adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS` from a mac or a pc
- enable adb debug for qz companion
- restart the companion

@lseufer will check if all these steps are necessary at every reboot. I'm leaving this open waiting for this information

**Comment by cagnulein** [comment]
@lseufer any news?
