### ISSUE TITLE
[BUG]Apple Watch will not connect to phone app

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#1592]
**Describe the bug**
The Apple Watch app will not connect to the IPhone app. The watch app is showing data but not transmitting to the phone app.
[debug-Thu_Aug_3_15_16_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12254986/debug-Thu_Aug_3_15_16_22_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
i can't see nothing wrong here. let's try to uninstall the app from the watch and install it back again. sometimes ios has this issue

let me know

**Comment by Dwhetsel** [comment]
I updated the watch and then uninstalled the app from the watch and reinstalled it to the watch. I did not uninstall the app from the phone. One strange thing I have noticed on the phone is, (first off I have two SAVED profiles in the app, one for my bike and one for my treadmill.) when I start the app on the watch then on my phone in the treadmill profile I see results in the Apple health rings for the bike. I see results in the Apple health rings under bike if I start the profile of treadmill. So the watch is transmitting data to the Apple health but not the QZ app.

**Comment by Dwhetsel** [comment]
Sorry, I should have said Apple fitness not health.

**Comment by cagnulein** [comment]
the bike thing it's because you need to select the right device on the watch app (scroll it to the bottom).
For the HR thing, I just tried on my end and it works. Instead of uninstall the qz app, let me send you a new beta: i didn't change anything but maybe this it will reset the cache. 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by Dwhetsel** [comment]
[debug-Sun_Aug_6_15_39_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12270426/debug-Sun_Aug_6_15_39_32_2023.log)

this is the one with the fake de ice on.

**Comment by Dwhetsel** [comment]
[debug-Sun_Aug_6_15_40_42_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12270432/debug-Sun_Aug_6_15_40_42_2023.log)

this the one with fake device off.

**Comment by cagnulein** [comment]
got the issue @Dwhetsel : qz is updating the HR tile for the nordictraadmill only when it receives a message from the companion. I can't see any message on the log from the companion.
Let me know!

**Comment by cagnulein** [comment]
@Dwhetsel are we ok with this?

**Comment by Dwhetsel** [comment]
Yes I believe so.On Sep 3, 2023, at 1:23 PM, Roberto Viola ***@***.***> wrote:﻿
@Dwhetsel are we ok with this?
