### ISSUE TITLE
Update FTP tile to include Watt Range

### ISSUE THREAD

**Issue by fooeynet** [cagnulein/qdomyos-zwift#160]
Current implementation of FTP tile seems to show percentage of FTP as the secondary text (below current zone).

A more useful metric might be the current zone's range in watts.  This, along with the Watts tile would help users keep in their desired Zone, and allow them to target upper/lower zone without doing math in their head.  ("this % range is this zone")

Mockup attached.

![2021-02-02 13_33_11-Facebook — Mozilla Firefox](https://user-images.githubusercontent.com/9012139/106665908-bd762d00-655b-11eb-8aa7-71033f21e606.png)

**Comment by fooeynet** [comment]
Can't remove 'bug' tag LOL :)

**Comment by fooeynet** [comment]
https://www.facebook.com/groups/149984563348738/permalink/164794931867701

**Comment by cagnulein** [comment]
Ok got it ;)

Il mar 2 feb 2021, 22:49 fooeynet <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
done @fooeynet ! sorry for the delay! it will be avaiable in the next beta version
