### ISSUE TITLE
Heart rate drops to zero intermittently 

### ISSUE THREAD

**Issue by Zenbloke** [cagnulein/qdomyos-zwift#1607]
**Describe the bug**
Heart rate drops to zero then back up to correct value.

Happens every time. 
Tried using Polar H10 and Polar Verity Sense. Same result.

ipados 16.6

Equipment is Sole E95 elliptical. Heart rate displays correctly on elliptical. 

![Mon Aug 14 13_59_41 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/58012175/7e1d1440-4289-4c03-b9b5-e10acb05bd25)

[debug-Mon_Aug_14_13_49_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12338462/debug-Mon_Aug_14_13_49_20_2023.log)

**Comment by cagnulein** [comment]
Got the issue, I will send you the patch tomorrow

send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta

**Comment by Zenbloke** [comment]
Cheers RobertoSent from my iPhoneOn 14 Aug 2023, at 20:19, Roberto Viola ***@***.***> wrote:﻿
Got the issue, I will send you the patch tomorrow
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta
