### ISSUE TITLE
[BUG] Rouvy controllable doesn't work

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#1616]
[**Describe](url) the bug**
A clear and concise description of what th
[Debug Log 8_21_2023.txt](https://github.com/cagnulein/qdomyos-zwift/files/12398493/Debug.Log.8_21_2023.txt)
e bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
got the issue, i will fix ASAP

**Comment by cagnulein** [comment]
@LDHig any news?

**Comment by LDHig** [comment]
Hello, I hope you are doing well. Sorry, I broke two toes on my left foot and have been unable to ride :-(. I will follow-up with you when I can get back on the bike. Thanks for checking, Lonnie
    On Thursday, September 14, 2023 at 12:06:35 AM EDT, Roberto Viola ***@***.***> wrote:  
 
 


@LDHig any news?

**Comment by cagnulein** [comment]
sorry to hear this :( i hope you will be fine! Feel free to open it back when you're ready to go!
