### ISSUE TITLE
[BUG]My grade does not work and I it's hard to connect and I lose connection about half way in the ride.

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#1619]
**Describe the bug**
[Debug Log 8_23_2023.txt](https://github.com/cagnulein/qdomyos-zwift/files/12419391/Debug.Log.8_23_2023.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work 
  
[Debug Log 8_23_2023.txt](https://github.com/cagnulein/qdomyos-zwift/files/12419565/Debug.Log.8_23_2023.txt)

**Comment by cagnulein** [comment]
#1616 please @LDHig don't open a new bug every time, use only one and append the new file there.

**Comment by cagnulein** [comment]
checked the log and rouvy it doesn't send the inclination. maybe you have some settings from rouvy? never used rouvy so I can't help with it, but if it worked the last time, it should still work.
Let me know

**Comment by LDHig** [comment]
What about the connection issue and losing the connection during the ride? Thanks Lonnie
