### ISSUE TITLE
Controlled resistance on Proform Bike 

### ISSUE THREAD

**Issue by shoulih** [cagnulein/qdomyos-zwift#162]
Following the following steps to install it from source on Raspberry pi 3, but it seems take a very long time to complete at the step in the attached screenshot.  Is this normal?

$ sudo apt update && sudo apt upgrade # this is very important on raspberry pi: you need the bluetooth firmware updated!
$ sudo apt install git libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-default libqt5networkauth5-dev
$ git clone https://github.com/cagnulein/qdomyos-zwift.git
$ cd src
$ qmake
$ make -j4

![PXL_20210206_001301205 MP](https://user-images.githubusercontent.com/66762397/107102723-3087d980-67d0-11eb-8ef3-97087c6986f1.jpg)

**Comment by cagnulein** [comment]
Yes it's normal, i wrote a lot of code in this month ;)

Il sab 6 feb 2021, 01:37 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
But, why it still didn't finish afternoon 12 hrs.?

It looks like getting stuck or hung...

Thanks,

**Comment by cagnulein** [comment]
@shoulih maybe it takes all the ram. Try run make without -j4

**Comment by shoulih** [comment]
Will try.  BTW, just checking to see if you have a complied binary
available for raspberry pi 3?

Thanks

**Comment by cagnulein** [comment]
nope, i didn't compile on raspberry for a very long time :) since i start
to develop on mobile.
but it works, other users are using raspberry pi :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 feb 2021 alle ore 18:08 shoulih <notifications@github.com>
ha scritto:

**Comment by shoulih** [comment]
"make without -j4" did the trick!   Got connected with my Proform Tour de
France CBC exercise bike from Costco, and most of the data were correctly
displayed on the qdomyos-zwift's UI, but for some reason I can't change the
"resistance" from qdomyos-zwift's UI to the bike.

**Comment by cagnulein** [comment]
Resistance controlled on pro-form is not implemented yet. If you want you
could help me on it!

Il mar 9 feb 2021, 18:47 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
That will be great and please let me know how can I help implement the
feature on the Proform Tour de France CBC?

Thanks again!

**Comment by cagnulein** [comment]
following these steps
https://github.com/cagnulein/qdomyos-zwift#your-machine-is-not-compatible
change the resistance from your bike app (not qdomyos) and tell me a little
overview of what you did (for example, at minut 1 i change resistance to
10, at minute 2 i changed resistance to 20, and so on)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 14 feb 2021 alle ore 18:52 shoulih <notifications@github.com>
ha scritto:

**Comment by shoulih** [comment]
Looks like my ifit app doesn't allow me to connect to my machine's
bluetooth anymore after my membership expired.

**Comment by cagnulein** [comment]
Ok we Will find someone ;)

Il dom 14 feb 2021, 21:20 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
Hi Rob,

I just started a new ifit subscription and I am able to help you now.

I performed the steps you asked for and where can I find the
"btsnoop_hci.log" file on the phone?

Shawn

**Comment by shoulih** [comment]
Somehow, I got a file called 'BT_HCI_2021_0226_103315.cfa.curf" and will
that be helpful?

**Comment by cagnulein** [comment]
Yes it is!

Il ven 26 feb 2021, 20:06 shoulih <notifications@github.com> ha scritto:

> Somehow, I got a file called 'BT_HCI_2021_0226_103315.cfa.curf" and will
> that be helpful?
>

**Comment by shoulih** [comment]
great, where do you want me to send the file to?

**Comment by cagnulein** [comment]
Put just here ;) Zipping it

Il ven 26 feb 2021, 20:33 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
here you are:

**Comment by shoulih** [comment]
increased the resistance from 1 to 16 every 6 seconds or so.  Let me know
if you need anything else.

**Comment by cagnulein** [comment]
@shoulih i guess you forgot the attachment :)

**Comment by shoulih** [comment]
[BT_HCI_2021_0226_111915.cfa.curf.zip](https://github.com/cagnulein/qdomyos-zwift/files/6057244/BT_HCI_2021_0226_111915.cfa.curf.zip)

@cagnulein Looks like the attachment got dropped when I attached it from my gmail account; attached it again from github.

**Comment by cagnulein** [comment]
i didn't find the time today. i will check it tomorrow ;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 feb 2021 alle ore 17:43 shoulih <notifications@github.com>
ha scritto:

**Comment by cagnulein** [comment]
@shoulih i think i got them! just a question. Does your bike has only 16 levels? or do you have more?

**Comment by shoulih** [comment]
Only 16 levels.

**Comment by cagnulein** [comment]
@shoulih done, tell me if it works :)

**Comment by shoulih** [comment]
@cagnulein the (+/-) from qdomyos-zwift's Resistance UI seemed to response my mouse clicks and randomly changed the resistance values on my Proform CBC bike.  Also, when restarting qdomyos-zwift after I killed qdomyos-zwift, I can't reconnect to the bike with the following errors

![image](https://user-images.githubusercontent.com/66762397/109541961-4740e980-7a79-11eb-8b40-e079f7fb7eab.png)
:

**Comment by cagnulein** [comment]
I have to understand what the resistance Numbers means. I will check them
in the next days

Il lun 1 mar 2021, 19:32 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
@cagnulein sure.  Some mouse-click behavior observed from the UI:  It only increased resistance value by 2 every 3-4 mouse clicks, then it jumped to resistance value, 11. 14 and 18.

**Comment by cagnulein** [comment]
@shoulih ok @p3g4asus will give us a hand on this! thank you both

**Comment by cagnulein** [comment]
@shoulih the resistance value shown from qdomyos without forcing it, is it correct?

**Comment by cagnulein** [comment]
@shoulih could you please take a longer HCI snoof log? we need one with you go to 1 to 16 and again to 1 and again to 16 and again to 1. each step delayed of 6 seconds each one. So in total we should see about 60 variations.
Thanks!

**Comment by shoulih** [comment]
Will do.

**Comment by shoulih** [comment]
[BT_HCI_2021_0302_084634.zip](https://github.com/cagnulein/qdomyos-zwift/files/6071801/BT_HCI_2021_0302_084634.zip)

Changed Resistance Values with ifit app via Bluetooth connection from 1 to 16 at about every 6 seconds, paused for about 12 seconds and then changed from 16 to 1 at about every 6 seconds.

**Comment by cagnulein** [comment]
@shoulih could you try the last commit?
@p3g4asus i guess i understood it. the resistance write frame must be always another frame. It's a just a sequence issue.

**Comment by shoulih** [comment]
@cagnulein 

Getting closer for this build and below is what I observed:

1) By clicking the + from qdomyos-zwift's Resistance UI,  I was able to increase the resistance of the bike from 1 to 5, but resistance value display stuck at 4 on the qdomyos-zwift's Resistance UI and can't increase the resistance anymore.

2) Increased bike's resistance to 6 from the bike's resistance control and  qdomyos-zwift's Resistance UI showed 6; able to continue increasing the resistance of the bike by clicking the + from qdomyos-zwift's Resistance UI from 7, 8, 9.

3) After 9, one mouse click of + will increase resistance of the bike by 2. ( 9, 11, 13, 15)

4) Decrease the resistance of the bike by clicking the (-) on qdomyos-zwift's Resistance UI doesn't seem to work correctly.

BTW, there no debug info. from the console of this build:

pi@raspberrypi:~/qdomyos-zwift/src $ sudo ./qdomyos-zwift
OK, you are root.
libEGL warning: DRI2: failed to authenticate
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

**Comment by cagnulein** [comment]
For the debug, i added a new parameter in the settings. Enable it and send
me the log. Thanks ;)

Il mer 3 mar 2021, 20:12 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
how to enable the debug setting?

**Comment by cagnulein** [comment]
are you using the QML interface?
if so go into the setting and go at the bottom.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 mar 2021 alle ore 21:08 shoulih <notifications@github.com>
ha scritto:

**Comment by shoulih** [comment]
no, I didn't see QML interface.

**Comment by cagnulein** [comment]
use the parameter -qml

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 mar 2021 alle ore 21:14 shoulih <notifications@github.com>
ha scritto:

**Comment by shoulih** [comment]
[debug-Wed Mar 3 14_42_12 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6079678/debug-Wed.Mar.3.14_42_12.2021.log)

@cagnulein debug log attached.

**Comment by cagnulein** [comment]
@shoulih i try to fix it. Could you try again? Thanks

**Comment by shoulih** [comment]
1) Clicking (+/-) UI works fine for resistance <5; it still got stuck at 4 on UI when resistance > 5;

not sure if it has anything to do with the following logic in proformbike.cpp?
  if(Resistance.value() > 4)
            Resistance =  Resistance.value() - 1;

     2)  Have to increase bike's resistance to 6 from the bike's resistance control manually and qdomyos-zwift's Resistance UI showed 6; able to continue increasing the resistance of the bike by clicking the + from qdomyos-zwift's Resistance UI from 7, 8, 9 (with a large click sound from the bike); then the resistance goes to 11, 13, 15, 18 for each (+) click.

**Comment by cagnulein** [comment]
Did you pull it? There is no more that logic now. Be sure to be updated

Il gio 4 mar 2021, 18:58 shoulih <notifications@github.com> ha scritto:

**Comment by shoulih** [comment]
yes, I cloned the repository again this morning:

    // filter some strange values from proform
    if(m_watts > 3000)
    {
        m_watts = 0;
    }
    else
    {
        switch((uint8_t)newValue.at(11))
        {
        case 0x02:
         Resistance = 1;
         break;
        case 0x04:
         Resistance = 2;
         break;
        case 0x07:
         Resistance = 3;
         break;
        case 0x09:
         Resistance = 4;
         break;
        case 0x0b:
         Resistance = 5;
         break;
        case 0x0e:
         Resistance = 6;
         break;
        case 0x10:
         Resistance = 7;
         break;
        case 0x13:
         Resistance = 8;
         break;
        case 0x15:
         Resistance = 9;
         break;
        case 0x18:
         Resistance = 10;
         break;
        case 0x1a:
         Resistance = 11;
         break;
        case 0x1d:
         Resistance = 12;
         break;
        case 0x1f:
         Resistance = 13;
         break;
        case 0x21:
         Resistance = 14;
         break;
        case 0x24:
         Resistance = 15;
         break;
        case 0x26:
         Resistance = 16;
         break;
        default:
         Resistance = 0;
         break;
        }

        Resistance = (((uint8_t)newValue.at(11)) / 2);

        if(Resistance.value() > 4)
            Resistance =  Resistance.value() - 1;

**Comment by cagnulein** [comment]
Argh! Did i leave the last lines? I'm so dumb! Sorry! I'm pushing it right
now

Il gio 4 mar 2021, 19:31 shoulih <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
Done, pull it again. Sorry

Il gio 4 mar 2021, 19:33 cagnulein <cagnulein@gmail.com> ha scritto:

**Comment by shoulih** [comment]
(+/-) are all working now from 1-16.  Thank you so much for your hard work!

**Comment by cagnulein** [comment]
Great!!!

Il ven 5 mar 2021, 00:44 shoulih <notifications@github.com> ha scritto:

**Comment by blancmunier** [comment]
Hello,
Would the resistance be controlled on the Proform BIKING SMART POWER 10.0 ?
The resistance is controllable through the application iFit...
Noote that it has 20 manuel level of resistance.
Thanks for your feedback and thanks for your work !!!
Yvan

**Comment by cagnulein** [comment]
@blancmunier if it works on ifit it will work on QZ too! :) if it doesn't provide me a debug log and we will make it work :)

**Comment by blancmunier** [comment]
great ! thanks !!
