### ISSUE TITLE
[REQ] Hammer Q.Vadis (7.0)

### ISSUE THREAD

**Issue by mistersoftee** [cagnulein/qdomyos-zwift#1621]
Hi Roberto,

first of all, have a nice vacation. I will close the discussion and we can proceed here later.

Best
Stefan

Topic in Discussions:

Hi Roberto,

I have a Hammer Q.Vadis treadmill with bluetooth and Zwift integration. Unfortunately it's has no auto-incline or speed. I tried to use it with QZ and the tiles are showing up as soon as I power on the treadmill, but it doesn't show metrics. If I press the start button, the treadmill starts. But the speed and cadence functions doing weird things. And if I change settings on the treadmill, the tiles stay at 0.

Is there anything I can do in the options to get it running?

Best
Stefan

[debug-Fr__Aug__25_14_34_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12439187/debug-Fr__Aug__25_14_34_05_2023.log)

**Comment by cagnulein** [comment]
hi @mistersoftee could you try to enable the "anyrun" setting in the fitshow settings section in qz and restart qz to check if it's better?
Let me know

**Comment by cagnulein** [comment]
can you install the free nrfconnect app on the store and send me a screenshot about your treadmill? thanks

**Comment by mistersoftee** [comment]
Are these the right ones? 
![IMG_3643](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/ea3d55b0-3e20-427d-be81-2a00de8dd978)
![IMG_3638](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/7de86b7e-4f6f-4651-8d6d-d8b08a18a1b4)
![IMG_3639](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/07758f7c-dbc2-400b-890f-b43be1bf641f)
![IMG_3640](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/8d7c37fe-36c6-43b3-93eb-d1ce0521bb75)
![IMG_3641](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/3c4f48ca-8cac-4471-9a34-b90e8c80d227)
![IMG_3642](https://github.com/cagnulein/qdomyos-zwift/assets/56932020/5b2874dc-5aa8-4faa-8927-7119eb4e023c)

**Comment by cagnulein** [comment]
yes i will send you a new version tomorrow with a possible fix

Il giorno mar 29 ago 2023 alle 20:23 mistersoftee ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mistersoftee I just sent you a new test flight version with a patch. Go into the settings, treadmill settings, under the ftms treadmill setting, select your treadmill, press ok and restart qz
Let me know if it's better
Thanks

**Comment by mistersoftee** [comment]
@cagnulein I am not using the beta at the moment. How do I get it?

**Comment by cagnulein** [comment]
@mistersoftee I sent you an email from apple to your address. Did you receive it?

**Comment by mistersoftee** [comment]
@cagnulein I checked all mailboxes and spam folders but found nothing.

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com indicating this ticket just to be sure

thanks

**Comment by mistersoftee** [comment]
Hi Roberto, the problem still persists. There is some communication between app and treadmill. If I press start in the app, it starts the treadmill. Also increasing speed and incline works. But the results are strange. There is no data from the treadmill in the tiles.

**Comment by cagnulein** [comment]
@mistersoftee ok send me a fresh debug log and i will check it

**Comment by mistersoftee** [comment]
Just to keep it open. I will have time to provide new logs this weekend. Thanks :)

**Comment by cagnulein** [comment]
@mistersoftee any news?

**Comment by mistersoftee** [comment]
The connection problem is fixed using the FTMS option

**Comment by cagnulein** [comment]
Hi @mistersoftee are you able to change both speed and inclination from qz?
