### ISSUE TITLE
Custom made broadcoaster connected to Nordicktrack s15 bike not sending resistance to QZ [BUG]

### ISSUE THREAD

**Issue by afeith** [cagnulein/qdomyos-zwift#1622]
**Describe the bug**
I have a homebuilt/custom-made box to plug my Nordicktrack s15i red and yellow cables to broadcast power, cadence, and resistance.  I can see everything in QZ but resistance from my bike.  The box works from other 3rd party apps (like mpaceline where power cadence and resistance are all sent and received).

I've attached a debug log from  a short ride today.

[debug-Sat_Aug_26_17_18_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12446756/debug-Sat_Aug_26_17_18_19_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi thanks, i'm currently on vacation i will check it when i come back

Il giorno sab 26 ago 2023 alle 22:31 afeith ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi @afeith checked the log but it seems truncated. Could you please send me another one?
Also i'm intereted about the box: could you please send me some info about it?

**Comment by afeith** [comment]
I will get you a new log soon.  I am not the creator of the device.  I reached out to the this person in Reddit after I saw his post. 

https://www.reddit.com/r/nordictrack/comments/zcai3j/zwift_working_on_nordictrack_s15i_bike/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=2

**Comment by cagnulein** [comment]
hah ok yes i knew that project.
Ok send me a fresh debug log and I will understand it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 29 ago 2023 alle ore 15:44 afeith ***@***.***>
ha scritto:

**Comment by afeith** [comment]
I've attached a log from a 5-minute class.  I also attached the pic.  It seems I'm not getting total output and distance as well.

[debug-Sat_Aug_26_17_18_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12470607/debug-Sat_Aug_26_17_18_19_2023.log)

![Tue Aug 29 20_42_24 2023_power_badge](https://github.com/cagnulein/qdomyos-zwift/assets/101931552/df675d7b-427b-432e-8d91-8448cd632a06)

**Comment by cagnulein** [comment]
@afeith the issue is that you set the cadence sensor, set it to disabled only. also in order to handle all the attritubes that the can send I will add a new setting to allow the user to pair a custom bluetooth device (like this one) to a FTMS bike profile.
I will tell you when I'm ready

**Comment by cagnulein** [comment]
done @afeith 

you will see this patch in the 2.6.5

what you have to do is:
- disable the cadence sensor
- disable the power sensor
- enable the new ftms bike sensor set it to ubike ftms device
- restart qz

let me know!

#1497

**Comment by cagnulein** [comment]
Thanks!
