### ISSUE TITLE
Holofit connection issue

### ISSUE THREAD

**Issue by sinimsdp** [cagnulein/qdomyos-zwift#1623]
We had spoken about this on the comment board.  I've renamed an older phone of mine to bike to use it as a bridge.  It shows up and I can select it.  It turns orange and the disconnect button becomes available.  I go into a ride, but it does not register input from the bike (echelon gt+) which is connected to QZ and QZ is showing the bike data.
![41c39d7045022ce2faad253bd6d8b3c4](https://github.com/cagnulein/qdomyos-zwift/assets/143354666/0f1dd618-89f9-473b-be8c-c8e522ad2664)
[debug-Sun_Aug_27_16_12_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12448770/debug-Sun_Aug_27_16_12_57_2023.log)

**Comment by cagnulein** [comment]
@sinimsdp Holofit supports auto resistance? If not enable the bike power sensor in the experimental settings in qz and restart qz. Let me know if it's better

**Comment by sinimsdp** [comment]
Didn't seem to help.

**Comment by cagnulein** [comment]
did you restart QZ? can you share a fresh debug log just to check now your settings? are you able to pair qz to zwift for example on this scenario? maybe the metaquest has a cache of the android device and so you need to clear it up
Let me know

**Comment by sinimsdp** [comment]
Interesting further update.  I was able to get zwift to work with my
current phone (not the one I changed the name on), by using the "power"
setting in the experimental settings.  However, still no luck on holofit
there.

**Comment by cagnulein** [comment]
@sinimsdp you can ask here https://github.com/cagnulein/qdomyos-zwift/issues/1407 if the OP has some tip

**Comment by cagnulein** [comment]
@sinimsdp virtual rower patch done.
When you will receive the version 2.16.13 enable the virtual rower device in the experimental settings and restart qz
If you don't see the 2.16.13 you need to join the beta on the play store page of qz (Google is reviewing it so it could take some hours/days)
Let me know!

**Comment by cagnulein** [comment]
@sinimsdp are we ok with this?

**Comment by sinimsdp** [comment]
I gave up getting it to work with holofit.  At least I finally got zwift working with my bike using QZ.  I really didn't know what else to do.
    On Saturday, October 7, 2023 at 04:19:08 AM EDT, Roberto Viola ***@***.***> wrote:  
 
 


@sinimsdp are we ok with this?

**Comment by cagnulein** [comment]
@sinimsdp another user did it with a patch in the 2.16.15 version of qz and with the virtual rower setting enabled! give it a try!

**Comment by cagnulein** [comment]
#1681
