### ISSUE TITLE
[BUG] TDF Proform 10 connect

### ISSUE THREAD

**Issue by HonzaBas** [cagnulein/qdomyos-zwift#1624]
#/**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @HonzaBas i don't see the log

**Comment by HonzaBas** [comment]
[debug-Mon_Aug_28_17_54_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12456440/debug-Mon_Aug_28_17_54_33_2023.log)

**Comment by cagnulein** [comment]
ok thanks i will check it tomorrow

Il giorno lun 28 ago 2023 alle 18:29 HonzaBas ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @HonzaBas checked the log. It seems the same issue from a iFit update that I covered here: https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

so update the companion on the bike and follow this. Let me know if it's working.

**Comment by HonzaBas** [comment]
Hi @cagnulein please,  where I put these command _adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS_ trough adb devices?

**Comment by cagnulein** [comment]
you should run this on a pc or mac

Il giorno mar 29 ago 2023 alle 19:42 HonzaBas ***@***.***> ha
scritto:

**Comment by HonzaBas** [comment]
I know, but where I have to copy the string? QZ companion is up to date. Any tutorial step by step?

**Comment by cagnulein** [comment]
try replacing adb with adb.exe in the line

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ago 2023 alle ore 14:22 HonzaBas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hah sorry you have to do

.\adb.exe instead of adb.exe


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ago 2023 alle ore 14:39 HonzaBas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hah yep

digit first

.\adb.exe connect ipofyuourbike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ago 2023 alle ore 14:45 HonzaBas ***@***.***>
ha scritto:

**Comment by HonzaBas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/143430221/ab9201eb-df17-4108-baf3-397f6c106517)

**Comment by cagnulein** [comment]
@victorypoint did you ever see this issue?

**Comment by cagnulein** [comment]
@HonzaBas did you try to reboot the TDF? did you check if the adb setting on the bike is enabled?

**Comment by victorypoint** [comment]
> ![image](https://user-images.githubusercontent.com/143430221/264340403-47accad8-13f5-4679-8918-b7fe1ba64793.png)

Just seeing this issue now. @HonzaBas, you have to run the adb permissions command within the QZ Companion install folder. It contains all the necessary adb files needed to run. The QZ Companion folder is the one created when you extract the QZ Companion installation files - https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage

**Comment by victorypoint** [comment]
@HonzaBas, oh I see, your using Powershell. So either run the adb command inside a cmd shell or use this in Powershell:

cmd.exe -/c ".\adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS"

**Comment by HonzaBas** [comment]
Ok, I unzip folder without rename to C:\ but still same problem USB Debbuging on bike is enabled.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/143430221/b1031f85-c835-46cf-a68f-62978adb9917)

**Comment by victorypoint** [comment]
@HonzaBas , it looks like you missed the first part with cmd.exe:

cmd.exe -/c ".\adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS"

Also try it from just a cmd shell/window. Don't use powershell. In this case, just use:

adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS

**Comment by HonzaBas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/143430221/b34efa41-b116-4e3e-bf92-d98879d1efe4)

**Comment by victorypoint** [comment]
@HonzaBas, okay interesting. I see you had a previous ADB connection still alive. I wonder if that's causing the problem. Are you able to run the installer script without any issues? qz-companion.bat? It contains commands that will reset your ADB server and connection. Or you could just try this manual sequence:

adb disconnect
adb kill-server
adb connect {IP address of treadmill}
adb devices -l

Probably best to reboot your PC before trying it.

**Comment by HonzaBas** [comment]
I´ve made bike factory reset, install QZ companion again. It works now. Boys, thanks for your time and great work.

**Comment by cagnulein** [comment]
great!
