### ISSUE TITLE
 saris m2

### ISSUE THREAD

**Issue by b-soder** [cagnulein/qdomyos-zwift#1625]
/*
/*Describe the bug**
when starting a session (start button) sometimes the distance and other fields have a random value

the trainer is a saris m2 https://saris.com/products/m2-smart-trainer

and you helped me get it set up using advanced settings

![IMG_0054](https://github.com/cagnulein/qdomyos-zwift/assets/131820815/b276679a-fce0-4578-b383-471ddc4df766)

**To Reproduce**

Start trainer first, then start app, sometimes it happens immediately, sometimes after hitting the stop and start buttons as in the debug log attached 

**Expected  #behavior**

zero on distance and other fields when starting

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 Pro Max
 - OS: [e.g. iOS8.1] current
 - Version [e.g. 22] current

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

[qdomyoszwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/12466709/qdomyoszwift.zip)

  
**Additional context**

**Comment by cagnulein** [comment]
@b-soder can you try to disable the magnus sensor from the power sensor setting? it shouldn't be required. let me know

**Comment by b-soder** [comment]
I turned it off there, and now the odometer is going up no matter what I do with the start/stop buttons. The start is flashing red/white, and with each flash the distance goes up about .15 mile. I tried setting the advanced settings / manual device to disabled, it's still finding the trainer though so I don't know if it could be somewhere else in the settings? I deleted and reinstalled the app, but same results, it's still finding it immediately and doing the .15 mile per flash thing. Is there a way to completely reset the settings?On Aug 29, 2023, at 11:20 PM, Roberto Viola ***@***.***> wrote:﻿
@b-soder can you try to disable the magnus sensor from the power sensor setting? it shouldn't be required. let me know

**Comment by cagnulein** [comment]
send me a fresh log of the current scenarios

**Comment by b-soder** [comment]
[qdomyoszwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/12476610/qdomyoszwift.zip)

**Comment by b-soder** [comment]
DoneOn Aug 30, 2023, at 7:18 AM, Roberto Viola ***@***.***> wrote:﻿
hi @b-soder you have to attach it from the github web interface, otherwise I can't see it
thanks

**Comment by cagnulein** [comment]
ok let me try to do a patch, the issue is the fact that the trainer itself sends a strange distance value.

**Comment by cagnulein** [comment]
@b-soder  send me an email to roberto.viola83 at gmail.com indicating this ticket so I will send you a new beta for ios

**Comment by b-soder** [comment]
Makes sense. The trainer also supports setting the resistance - ie. I've used it with the zwift app and had it changing resistance appropriately when climbing hills, but I haven't been able to figure out how to do it with the qz app yet, that would make sense if it sends weird values. On Aug 30, 2023, at 7:25 AM, Roberto Viola ***@***.***> wrote:﻿
ok let me try to do a patch, the issue is the fact that the trainer itself sends a strange distance value.
