### ISSUE TITLE
[BUG] Home trainee elite zumo no resistance

### ISSUE THREAD

**Issue by elvba5** [cagnulein/qdomyos-zwift#1626]
Hi, no resistance on home trainer élite zumo. .
[debug-Tue_Aug_29_18_27_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12467120/debug-Tue_Aug_29_18_27_12_2023.log)

**Comment by cagnulein** [comment]
hi @elvba5 the log is truncated. could you please send me another one?
also the problem is that you can't set the resistance on the trainer? if so I guess I understood why. Share me a fresh debug log.
Thanks

**Comment by elvba5** [comment]
hi Roberto, I think I did it well 
[debug-Wed_Aug_30_11_01_42_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12473904/debug-Wed_Aug_30_11_01_42_2023.log)

**Comment by cagnulein** [comment]
ok I guess I already fixed it. join the beta from the play store and you will have to see the version 2.16.5 (it will be available in the next hours)
then disable the cadence sensor setting and enable the ftms bike setting in the bike settings.
Let me know

**Comment by elvba5** [comment]
ok I will keep you informed thank you
