### ISSUE TITLE
 [BUG] - Incline and resistance not controlling s22i bike

### ISSUE THREAD

**Issue by rn2023qz** [cagnulein/qdomyos-zwift#1627]
**Describe the bug**
incline and resistance not working when running QZ on PC
**To Reproduce**
Clicking +- on the tiles for incline and resistance have no effect on the bike

**Expected behavior**
with android version of Qz, incline +- work to change the incline on the bike, and zwift will control incline.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22h2

**Append a debug log**
[debug-Tue_Aug_29_18_02_11_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12470239/debug-Tue_Aug_29_18_02_11_2023.log)
[logcat.log](https://github.com/cagnulein/qdomyos-zwift/files/12470236/logcat.log)
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/12470237/logcat.txt)

  
**Additional context**
qz on bike is set to c1750 as someone on facebook suggested.  this works for incline on android, tested yesterday.

**Comment by cagnulein** [comment]
thanks @rn2023qz 
did you enable on android the "ADB Remote" setting? if so I understood why on pc it doesn't work. Let me know!

**Comment by rn2023qz** [comment]
yes that setting is enabled on PC.  I mirrored the settings from my android

**Comment by cagnulein** [comment]
ok perfect, got it now. I will do the patch today/tomorrow. I will keep you informed!

**Comment by cagnulein** [comment]
@rn2023qz started the branch https://github.com/cagnulein/qdomyos-zwift/pull/1629

if it would build, it will be ready to use!

**Comment by cagnulein** [comment]
@rn2023qz ready! https://github.com/cagnulein/qdomyos-zwift/suites/15646027593/artifacts/893078020

let me know if it works, if not, send me a debug log! remember to enable the adb remote setting first!

**Comment by rn2023qz** [comment]
Thanks!  I will test tonight.  Just to be sure, should I choose s22i on the bike app, or c1750?

**Comment by cagnulein** [comment]
the same that was working with your android device

**Comment by rn2023qz** [comment]
not resolved..  Also unable to get a debug log from the app.  two things are happening now.  One, when I close qz on the computer the CMD window stays active and does not auto close itself.  Two, when i enable debug log, the screen with the tiles never shows.  it is just a white screen that says not responding.  the CMD window is scrolling constantly.  I paused it to save a snip.  

I tested incline and resistance but neither worked using the buttons on the tiles. As a secondary troubleshooting step I deleted the registry key with all settings, and only enabled Proform bike, companion IP for the bike, and adb remote for testing.  tiles appear and track data, but no incline or resistance.  
![Capture](https://github.com/cagnulein/qdomyos-zwift/assets/142918827/d83275a9-9289-4225-8cea-68d0c6e0c7bc)

**Comment by cagnulein** [comment]
ok let me check this, i did a small huge patch so i was prepared to the
fact that it couldn't work at first

Il giorno gio 31 ago 2023 alle 04:55 rn2023qz ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@rn2023qz could you please try this one https://github.com/cagnulein/qdomyos-zwift/suites/15677391644/artifacts/894939871 ?

**Comment by rn2023qz** [comment]
OK, resistance and incline do not work, but the other two issues are resolved.  I was able to create a debug. :)

[debug-Thu_Aug_31_06_54_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12485806/debug-Thu_Aug_31_06_54_16_2023.log)

**Comment by cagnulein** [comment]
great @rn2023qz I got the issue, it's building now. I will let you know in 30 minutes

**Comment by rn2023qz** [comment]
incline works on PC now :)

Resistance still doesn't work with the + - buttons, but that never worked on android either.  Could be a s22i issue i will keep playing with it. Thanks again!

**Comment by cagnulein** [comment]
Great news! Resistance buttons don’t work while you’re on zwift or even
without zwift? With zwift you have to use the gears tile instead of the
resistance tile to override it
Let me know

Il giorno ven 1 set 2023 alle 16:34 rn2023qz ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hah no I got why the resistance tile doesn’t work: I’m sending to the bike
the inclination information not the resistance one.

Il giorno ven 1 set 2023 alle 19:53 cagnulein ***@***.***> ha
scritto:

**Comment by rn2023qz** [comment]
HA!  makes sense.  Thank you!!

**Comment by cagnulein** [comment]
@rn2023qz could you try this version? https://github.com/cagnulein/qdomyos-zwift/suites/15829796661/artifacts/903240933

**Comment by rn2023qz** [comment]
This one has an issue when closing the app.  The cmd window stays open.  I will try the erg mode tonight.  Thanks

**Comment by cagnulein** [comment]
ok let me know, i don't think it's releated to the last change

**Comment by cagnulein** [comment]
ok so your setup is different from the one of the other users. ok rollback to the working one

**Comment by cagnulein** [comment]
it seems that somehow the adb logcat on your bike requires a lot of time to handle it. Does it hangs also if you disable the debug log and restart qz?

**Comment by rn2023qz** [comment]
Yes, consistent hangs with that version

**Comment by cagnulein** [comment]
i don't understand: on which version do you have hangs? with the one that works 1 month ago?

**Comment by rn2023qz** [comment]
The one you asked me to try 2 weeks ago.  903240933

**Comment by cagnulein** [comment]
yeah as i told you stick with the one from 1 month ago that worked for you

Il giorno gio 28 set 2023 alle 13:49 rn2023qz ***@***.***> ha
scritto:

**Comment by rn2023qz** [comment]
Yes, that's what I have been using.  The only thing not working is erg mode.  Not sure if any other users have tried it or if it's just something on my setup.  Not a big deal if it won't work.

**Comment by cagnulein** [comment]
@rn2023qz erg mode can't work with the actual code because I'm sending touch event only to the resistance/inclination button on the tablet touchscreen. Does the tablet have a screen where you can set the target power? I can try to do the same thing that I do for the incline/resistance
