### ISSUE TITLE
QZ not shown as controllable on zwift

### ISSUE THREAD

**Issue by the1robbo** [cagnulein/qdomyos-zwift#1628]
**Describe the bug**
QZ not controllable on Zwift, with Echelon E3 bike.

**To Reproduce**

**Expected behavior**
[debug-Wed_Aug_30_09_41_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12474052/debug-Wed_Aug_30_09_41_02_2023.log)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17 Beta 8

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by the1robbo** [comment]
Sorry my Mac kept hanging but looks like it added it.

**Comment by cagnulein** [comment]
@the1robbo the problem is that you have the bike power sensor setting enable in the experimental settings. disable it and restart qz

let me know

**Comment by the1robbo** [comment]
Changed the setting. It connected as controllable but when on an incline of 5%, the resistance didn't change.

**Comment by the1robbo** [comment]
[debug-Wed_Aug_30_10_34_53_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12474239/debug-Wed_Aug_30_10_34_53_2023.log)

**Comment by cagnulein** [comment]
you have the zwift erg/workout setting enabled, you need to disable it for free rides

**Comment by the1robbo** [comment]
I've disabled it. I'll give that a try

**Comment by the1robbo** [comment]
Awesome, worked. Thanks
