### ISSUE TITLE
[BUG] Auto resistance lagging

### ISSUE THREAD

**Issue by Aqfreitas** [cagnulein/qdomyos-zwift#1630]
#
[debug-Wed_Aug_30_11_59_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12477895/debug-Wed_Aug_30_11_59_38_2023.log)
**Describe the bug**

1.Auto resistance lagging. On this ride probably a good 3 mins. Cause an increase in resistance or decrease before/after callouts. Idk if you can see on report but I did  move resistance on my own with nob or + - in QZ app (8 min left mark) with no issue but it would drop again. 

2. Heart rate is not showing in QZ I have Apple Watch. Do I need QZ on watch?

**To Reproduce**
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
Echelon 4s with tablet jailbroke with peloton app installed. 

**Smartphone (please complete the following information):**
 - 
iPhone 14max pro iOS 16.6 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
yes you need qz on the watch.

i will check the first issue tomorrow

Il giorno mer 30 ago 2023 alle 18:17 Aqfreitas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @Aqfreitas in this log there is any workout, maybe you uploaded the wrong file? also do you mean a peloton workout? did you press yes to the popup on qz when the peloton timer is 0:00?

**Comment by Aqfreitas** [comment]
Sorry idk why but I had two logs from yesterday. I tried to attach but
email came back undelivered because of size. How can I get this to you?

Yes I click yes in the app when the workout starts. It is a peloton workout
in the peloton app was download on echelon 4s tablet screen that comes with
that bike. My husband wiped out echelon app and all that.

Thank you

**Comment by cagnulein** [comment]
zip them and then you can upload it here
thanks

Il giorno gio 31 ago 2023 alle 13:01 Aqfreitas ***@***.***>
ha scritto:

**Comment by Aqfreitas** [comment]
I did create a zip but it’s still saying exceeds 25MB and won’t attach

**Comment by Aqfreitas** [comment]
Did this work?

**Comment by cagnulein** [comment]
@Aqfreitas you have to attach file from the github web interface, otherwise they don't come online

**Comment by Aqfreitas** [comment]
Adding zip here 
[*debug-Wed_Aug_30_08_33_43_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12485654/debug-Wed_Aug_30_08_33_43_2023.zip)

**Comment by cagnulein** [comment]
ok this worked. could you tell me where you felt the delay? from the very beginning or after some minutes? it's very important to know because I don't have in the log the timestamp of your peloton workout. Thanks

**Comment by Aqfreitas** [comment]
So on this ride it was auto increasing resistance about 3 mins before call outs on peloton. So I would be riding on “flat ground” but the bike would jump to a hill sprint when that wasn’t for another few mins. Other  rides it would lag and not increase for about 30 seconds - 1min. 

I open QZ, I select the peloton ride I want. I hit start on ride and yes in QZ app.

**Comment by cagnulein** [comment]
@Aqfreitas maybe my question was unclear: this 3 mins delay happens from the very start of the workout or only, for example, 20 minutes?

because from the log i saw that the program is running smoothly, these are the auto resistance changes with the timestamps

```
Wed Aug 30 08:34:30 2023 1693398870401 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance8"
Wed Aug 30 08:35:43 2023 1693398943354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 9"
Wed Aug 30 08:36:50 2023 1693399010355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:37:32 2023 1693399052354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:40:42 2023 1693399242354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 14"
Wed Aug 30 08:41:12 2023 1693399272355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:41:25 2023 1693399285353 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 14"
Wed Aug 30 08:41:53 2023 1693399313355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:42:30 2023 1693399350355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 14"
Wed Aug 30 08:42:44 2023 1693399364355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:43:07 2023 1693399387354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 14"
Wed Aug 30 08:43:32 2023 1693399412354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 16"
Wed Aug 30 08:44:21 2023 1693399461354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 18"
Wed Aug 30 08:45:28 2023 1693399528354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 19"
Wed Aug 30 08:45:57 2023 1693399557355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 8"
Wed Aug 30 08:46:56 2023 1693399616354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 9"
Wed Aug 30 08:47:17 2023 1693399637354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 9"
Wed Aug 30 08:47:48 2023 1693399668355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 9"
Wed Aug 30 08:48:08 2023 1693399688354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:49:01 2023 1693399741354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:49:32 2023 1693399772354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:49:49 2023 1693399789354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:50:05 2023 1693399805350 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:50:21 2023 1693399821354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:51:03 2023 1693399863354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:51:08 2023 1693399868355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:51:35 2023 1693399895354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 12"
Wed Aug 30 08:51:48 2023 1693399908354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:52:17 2023 1693399937353 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 20"
Wed Aug 30 08:52:39 2023 1693399959354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 17"
Wed Aug 30 08:53:00 2023 1693399980355 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 20"
Wed Aug 30 08:53:28 2023 1693400008354 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change resistance 8"
```

could you indicate me from which one you feel the delay?

**Comment by Aqfreitas** [comment]
Sorry. Yes it was right when the workout started. Peloton 20 resistance was the start and then it jumped into 30-40 range before the call out for climb came. About 3 mins before. And then continued throughout the entire workout

**Comment by cagnulein** [comment]
@Aqfreitas i guess it's a peloton callouts wrong in the api, because I double checked all the resistance changes from qz and they match the peloton api.

If the next time you have the same issue, just note the timestamp of the issue so we can understand for sure if it's a peloton issue or a qz issue

**Comment by Aqfreitas** [comment]
Okay thank you. Can you confirm I have all my setting correct? Idk if that’s something you can see.

**Comment by cagnulein** [comment]
yes they look good

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 31 ago 2023 alle ore 14:29 Aqfreitas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/035a154b-2087-4eeb-be32-bf95218fb293)

they have for sure issues also with peloton bikes!
