### ISSUE TITLE
[BUG] TDF 5 dont connect to with the app.

### ISSUE THREAD

**Issue by PieroPatagonia** [cagnulein/qdomyos-zwift#1631]
**Describe the bug**
 TDF 5 dont connect to with the app. Didnt have that problem before

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 
**Additional context**
[debug-Wed_Aug_30_11_51_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12478067/debug-Wed_Aug_30_11_51_31_2023.log)

**Comment by cagnulein** [comment]
the problem is the location services are disabled. turn it on and restart qz

let me know

Il giorno mer 30 ago 2023 alle 18:25 PieroPatagonia <
***@***.***> ha scritto:

**Comment by PieroPatagonia** [comment]
yesssss work again, thanks Roberto
