### ISSUE TITLE
[REQ] DOMYOS 900 speed data > Strava 

### ISSUE THREAD

**Issue by Mikesz-MKA** [cagnulein/qdomyos-zwift#1632]
My setup: Domyos 900 Bike (from Decathlon) + IOS (with Apple Watch) + qdomyos-zwift IOS app on iPhone
Speed data from Domyos 900 Bike are collected in app. 
Speed data is not included in the data export to Strava. Only the average speed is exported.

I am committed to improving your wonderful application.

Maybe I am doing something wrong as I should? If so, let's help others avoid the mistake.

**Comment by cagnulein** [comment]
hi @Mikesz-MKA could you please attach the strava link of your activity and the fit file from qz?

thanks

**Comment by Mikesz-MKA** [comment]
Hello Roberto.
I added TXT extension as FIT is not supported for uploading.

[0QZ-backup-śr. sie 30 18_54_46 2023.fit.txt](https://github.com/cagnulein/qdomyos-zwift/files/12485946/0QZ-backup-sr.sie.30.18_54_46.2023.fit.txt)

Strava activity: https://www.strava.com/activities/9750995508

**Comment by cagnulein** [comment]
hi @Mikesz-MKA that's not the fit file. you should have one with the timestamp of the workout without the 0QZ tag

**Comment by Mikesz-MKA** [comment]
Reporting in STRAVA the lack of speed in the import of the FIT file from your application seems to me to complicate the subject with a focus on a single case, although probably all users of your application have this. You have the knowledge and capabilities to find the cause. Of course, you don't have to, but if you want to, I'm here to help if possible.

**Comment by cagnulein** [comment]
nope it's only your case, check for example this activity from another qz
user
https://www.strava.com/activities/9758827892

it's not the first time that we saw a strava issue that's why i'm saying so.

opening a ticket to strava it's very simple, like you did here :)

Il giorno gio 31 ago 2023 alle 23:37 Mikesz-MKA ***@***.***>
ha scritto:
