### ISSUE TITLE
[REQ] saris M2 control resistance from qz 

### ISSUE THREAD

**Issue by b-soder** [cagnulein/qdomyos-zwift#1634]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to control the resistance on the m2 trainer from the app, not sure which of the resistance tiles would be appropriate 

![IMG_0071](https://github.com/cagnulein/qdomyos-zwift/assets/131820815/e9895cfe-af21-48ed-9619-1b33bb2106cd)

I hit the - and + on both the resistance tile and the target r. Tile in this debug log

[qdomyoszwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/12494334/qdomyoszwift.zip)

**Comment by cagnulein** [comment]
@b-soder could you try a thing?
in the qz settings, accesories, smart spin 2k, enable the peloton bike setting. Try now to change the resistance and send me a fresh log.
Let me know!

**Comment by b-soder** [comment]
[qdomyoszwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/12494562/qdomyoszwift.zip)

![IMG_0072](https://github.com/cagnulein/qdomyos-zwift/assets/131820815/cbc5e16b-86a8-46c4-a6fc-6f66033137e6)

the numbers do change now, not sure what they represent though; I went up to 100 and I could feel it increasing. Is that watts?

![IMG_0074](https://github.com/cagnulein/qdomyos-zwift/assets/131820815/f17f86a7-2b64-4b5d-a1b6-7fce3272ac00)

when I disabled the "peloton bike" slider and reopened the app, it crashed repeatedly until I turned the slider on again, but did not select a device: 
![IMG_0075](https://github.com/cagnulein/qdomyos-zwift/assets/131820815/de20b8b4-129b-43fc-8fa5-fad79e065981)

this debug log should have the crashes, I believe. 

[qdomyoszwift.zip](https://github.com/cagnulein/qdomyos-zwift/files/12494594/qdomyoszwift.zip)

**Comment by cagnulein** [comment]
ok perfect! removing all these new setting, it was just a test to understand how your trainer works, and now i got it! I'm doing a patch now :)

**Comment by b-soder** [comment]
Awesome :) I will try it first thing tomorrow!On Aug 31, 2023, at 10:19 PM, Roberto Viola ***@***.***> wrote:﻿
ok perfect! removing all these new setting, it was just a test to understand how your trainer works, and now i got it! I'm doing a patch now :)

**Comment by cagnulein** [comment]
new beta sent!

Il giorno ven 1 set 2023 alle 07:24 b-soder ***@***.***> ha
scritto:

**Comment by b-soder** [comment]
Looks like it's working, I will do a full test later on today and report back. Thanks so much!On Sep 1, 2023, at 3:49 AM, Roberto Viola ***@***.***> wrote:﻿
new beta sent!



Il giorno ven 1 set 2023 alle 07:24 b-soder ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Glad to hear it!
let me know

Il giorno ven 1 set 2023 alle 16:42 b-soder ***@***.***> ha
scritto:

**Comment by b-soder** [comment]
Everything seems to be working, thanks again!On Sep 1, 2023, at 9:15 AM, Roberto Viola ***@***.***> wrote:﻿
Glad to hear it!

let me know



Il giorno ven 1 set 2023 alle 16:42 b-soder ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
amazing! thank you for your feedback!
