### ISSUE TITLE
Wahoo RGT connectivity

### ISSUE THREAD

**Issue by shuggyduggy** [cagnulein/qdomyos-zwift#1640]
I have a TDF5.0 bike and am using Qz 2.15.4 (on iPhone 14Pro IOS16) to connect to Zwfit on an Apple TV ( tvIOS 16.6 (20M73).  This works well.  I'm now looking at moving to a Wahoo subscription on my Apple TV.

Wahoo RGT works on the Apple TV, however, I cannot connect sensors, as per the screenshot.  When Wahoo searches for sensors it finds QZ, but returns a failed to connect message.  I raised a support call with Yahoo and they suggested disabling 'RemoteBLE' to off.  I have tried both on/off options but both fail to connect. 

Debug file attached.  Many thanks for your help.  Stephen

   

  

![WhatsApp Image 2023-09-09 at 15 03 24](https://github.com/cagnulein/qdomyos-zwift/assets/61912306/b949750e-0465-4bcf-8d4d-71208af20940)
[debug-Sat_Sep_9_14_25_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12565981/debug-Sat_Sep_9_14_25_03_2023.log)

**Comment by cagnulein** [comment]
hi did you enable the wahoo rgt compatibility in the experimental settings
in qz?

Il giorno sab 9 set 2023 alle 16:12 shuggyduggy ***@***.***>
ha scritto:

**Comment by shuggyduggy** [comment]
Yes, tried both on/off without success. So is on again and still not working.RegardsStephen+44 (0)7548 224054On 9 Sep 2023, at 15:43, Roberto Viola ***@***.***> wrote:﻿
hi did you enable the wahoo rgt compatibility in the experimental settings

in qz?



Il giorno sab 9 set 2023 alle 16:12 shuggyduggy ***@***.***>

ha scritto:

**Comment by shuggyduggy** [comment]
Here is another log file RegardsStephen+44 (0)7548 224054On 9 Sep 2023, at 15:43, Roberto Viola ***@***.***> wrote:﻿
hi did you enable the wahoo rgt compatibility in the experimental settings

in qz?



Il giorno sab 9 set 2023 alle 16:12 shuggyduggy ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
ok i'm in vacation, i will check on monday

Il giorno sab 9 set 2023 alle 17:32 shuggyduggy ***@***.***>
ha scritto:

**Comment by shuggyduggy** [comment]
No problem, I had a long run today and the weather here in the UK is scorching. That’s my exercise for the weekend. 🥵Have a nice vacation.RegardsStephen+44 (0)7548 224054On 9 Sep 2023, at 16:34, Roberto Viola ***@***.***> wrote:﻿
ok i'm in vacation, i will check on monday



Il giorno sab 9 set 2023 alle 17:32 shuggyduggy ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Hi @shuggyduggy I checked the log but unfortunately it's truncated on the top. Could you please recreate the issue and send me another one?
Also don't you see the wahoo virtual device from QZ on RGT? You should use this one

**Comment by shuggyduggy** [comment]
Hi Roberto

 

I’ll send you another log shortly, but just to clarify first. As below screenshot, are you referring to the “Wahoo RGT compatibility” in the experimental features? Or is it something else?

 

When I run Wahoo RGT on my AppleTV and select sensors, it appears to find “QZ”, then attempts to connect for about 20 seconds and then returns “Failed to Connect”.  I didn’t type “QZ” as the sensor name, I just turned on the search toggle for BLUETOOTH LE and I get the following screen. (Wahoo support, said to disable REMOTE BLE, I’ve tried both options an neither worked.)

 



 



 

.  

Regards

 

Stephen

+44 (0)7548 224054

**Comment by cagnulein** [comment]
> I’ll send you another log shortly, but just to clarify first. As below screenshot, are you referring to the “Wahoo RGT compatibility” in the experimental features? Or is it something else?

I can't see the attachment. You have to add to github directly. But Yes, it's the one in the experimental settings.



> When I run Wahoo RGT on my AppleTV and select sensors, it appears to find “QZ”, then attempts to connect for about 20 seconds and then returns “Failed to Connect”. I didn’t type “QZ” as the sensor name, I just turned on the search toggle for BLUETOOTH LE and I get the following screen. (Wahoo support, said to disable REMOTE BLE, I’ve tried both options an neither worked.)

the QZ interface is the one from bluetooth, but you should see also the Wahoo KICKR virtual device on RGT. DId you try to use another device for the Wahoo App?

**Comment by shuggyduggy** [comment]
I'm not seeing the Wahoo KICKR virtual device on Wahoo RGT AppleTV app.  No I have not used another device for the Wahoo app.  The Wahoo app doesn't allow me to select a device, it only allows to connect to sensors. This is the screenshot I've sent you.
[0QZ-backup-Mon Sep 11 14_00_23 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12578037/0QZ-backup-Mon.Sep.11.14_00_23.2023.zip)
[0QZ-backup-Mon Sep 11 14_13_18 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12578039/0QZ-backup-Mon.Sep.11.14_13_18.2023.zip)

**Comment by cagnulein** [comment]
these are the fit files, i need the debug log ones
also as i said, can't you test it wahoo app on another device instead of
apple tv just to understand if it's the apple tv the culprit?


Il giorno lun 11 set 2023 alle 17:40 shuggyduggy ***@***.***>
ha scritto:

**Comment by shuggyduggy** [comment]
I'm just downloading Wahoo RGT on my windows Laptop, which I'll try.  In the meantime here is the debut log


[debug-Mon_Sep_11_14_00_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12578291/debug-Mon_Sep_11_14_00_23_2023.log)

**Comment by cagnulein** [comment]
@shuggyduggy in this log I don't see any metrics from the bike at all. Are you sure is the right one?

**Comment by Ebatchelor** [comment]
[1QZ-backup-Thu Sep 14 11_18_41 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12608014/1QZ-backup-Thu.Sep.14.11_18_41.2023.zip)

**Comment by cagnulein** [comment]
wahoo rgt is closing, so i'm closing this too unfortunately
