### ISSUE TITLE
[BUG] ProForm Studio Bike 22

### ISSUE THREAD

**Issue by Ebatchelor** [cagnulein/qdomyos-zwift#1647]
**Describe the [bug**]
I have a ProForm Studio Bike 22 that I am unable to connect the QZ app to (it cannot detect my bike). 

**To Reproduce**
1. I have installed the QZ app on my phone. 
2. Installed the app on the bike
3. Input the IP address 
4. toggled the Enable Virtual Device
5. When the app is open it doesnt not connect. 

**Expected behavior**
The app to connect to the bike.

**Screenshots**

**Desktop (please complete the following information):**
- I havent got this far, but I'll be running Zwift off a MacBookPro 2018 13" (latest software installed).

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max 
 - OS: iOS 16.6.1=

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
 
I cannot attach anything? I also cannot see where the requested file is (in the folder)
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Ebatchelor I need the log as mentioned here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
hi @Ebatchelor it's in the files app under the qdomyos folder

**Comment by Ebatchelor** [comment]
[1QZ-backup-Thu Sep 14 11_18_41 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12608020/1QZ-backup-Thu.Sep.14.11_18_41.2023.zip)

**Comment by cagnulein** [comment]
this one is a fit file, i need the one starting with debug prefix

**Comment by Ebatchelor** [comment]
I cannot see  file on my phone with debug on (I've searched for it)

**Comment by cagnulein** [comment]
did you restart the app after enabling the debug log?

Il giorno gio 14 set 2023 alle 13:15 Ebatchelor ***@***.***>
ha scritto:

**Comment by Ebatchelor** [comment]
[debug-Thu_Sep_14_12_21_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12608126/debug-Thu_Sep_14_12_21_59_2023.log)

**Comment by cagnulein** [comment]
@Ebatchelor checked! it seems that the companion is not able to read the metrics. Could you please try to change the device seleciton in the companion to "c1750" and restart the bike?

Send me a fresh log if it doesn't work
Thanks

**Comment by Ebatchelor** [comment]
The companion had this as "C1750 Treadmill"?

**Comment by cagnulein** [comment]
yes use that one and restart the bike.
It uses a different way to read metrics and I would like to check if we can
use it for your bike too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 set 2023 alle ore 13:49 Ebatchelor <
***@***.***> ha scritto:

**Comment by Ebatchelor** [comment]
This has in part worked. But there is no speed transferred and my watt calculation seems off on the bike...

**Comment by Ebatchelor** [comment]
As in the watts are quite low?

**Comment by Ebatchelor** [comment]
Is there another workaround that I can do?

**Comment by cagnulein** [comment]
sorry I was in a meeting! That's awesome! yes sure send me the debug log so I can check wthat is wrong. I guess the main issue is that workaround is for treadmill, so I have to adjust it for the bikes.
Let me know

**Comment by Ebatchelor** [comment]
[debug-Thu_Sep_14_12_58_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12609571/debug-Thu_Sep_14_12_58_20_2023.log)

**Comment by cagnulein** [comment]
@Ebatchelor thanks, checked.
Actually the speed is not in the log at all, so it seems that ifit doesn't log it. It's not a big deal since we can use the qz algorithm to calculate it based on the wattage enabling the "speed based on watt" setting in the bike section.

Also for the wattage: they are the value sent from the bike directly. Maybe ifit log the raw value and then they applied a "multiplier" to compensate some calibration. You can do the same with the watt gain and the watt offset setting

let me know

**Comment by cagnulein** [comment]
@Ebatchelor are we ok with this?
