### ISSUE TITLE
[REQ] Add date tag to generic activities (Ride Row etc)

### ISSUE THREAD

**Issue by matthewdenny15** [cagnulein/qdomyos-zwift#1648]
Add a date tag to users activity for tracking in Strava and other apps.

**Comment by cagnulein** [comment]
thanks I will check this asap

Just to be sure, which format you would like to use?

"2023/09/14 Ride"

could be ok?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 set 2023 alle ore 13:26 matthewdenny15 <
***@***.***> ha scritto:

**Comment by matthewdenny15** [comment]
Sure, that would be perfect!

**Comment by cagnulein** [comment]
Done, it will be in the 2.16.13 version and above.
There is a new setting (default disabled) called "Date Prefix on Strava Workout"
Let me know when you will try it and close this ticket if it's ok :)
Thanks

**Comment by cagnulein** [comment]
@matthewdenny15 Did you test it?

**Comment by matthewdenny15** [comment]
I have not yet, I am in Amsterdam for work this week so I will when I get
back!

**Comment by cagnulein** [comment]
No rush! Have fun!

Il giorno sab 7 ott 2023 alle 18:24 matthewdenny15 ***@***.***>
ha scritto:

> I have not yet, I am in Amsterdam for work this week so I will when I get
> back!
>
