### ISSUE TITLE
Xiaomi T12 does not connect to treadmill (Capital Sport Infinity Pro 4) after 2023.Sep.13 update

### ISSUE THREAD

**Issue by istvanszegedi** [cagnulein/qdomyos-zwift#1650]
Hi Roberto! 

Before the Sep 13 update, I always used Xiaomi T12 (QZ running on this) to connect to my treadmill and my tablet (ZWIFT running).
I tried to find what was changed in the setting but I did not find what could cause this.
Xiaomi : Android 13
Tablet: Lenovo Yoga Tab 11 : Android 12
Treadmill: Capital Sport Infinity Pro 4
I attached the screenshot about the QZ version & the debug log
[debug-Thu_Sep_14_19_17_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12622306/debug-Thu_Sep_14_19_17_35_2023.log)
![Screenshot_2023-09-14-19-15-29-896_org cagnulen qdomyoszwift](https://github.com/cagnulein/qdomyos-zwift/assets/23429485/a58fd1dc-8b2b-4b93-9e07-d13996ca8c42)

I also realized that I cannot set manually the treadmill equipment (select manually by Bluetooth ID/Name of my treadmill)

I hope you can tell me what was changed and what should I set it to work again.
Regards,
István

**Comment by cagnulein** [comment]
you Need to enable the location services and restart QZ

Il giorno ven 15 set 2023 alle 19:50 István Szegedi <
***@***.***> ha scritto:

**Comment by istvanszegedi** [comment]
Hi!

I will try it, but it is the connection between Bluetooth and location services. Why it is needed? :-)

**Comment by istvanszegedi** [comment]
I tried. It worked.
Still not cleat what location permission needed to handle a treadmill that is in the room and not moving. lol
