### ISSUE TITLE
[BUG]  Echelon EX5S with 22" screen

### ISSUE THREAD

**Issue by Rezadue** [cagnulein/qdomyos-zwift#1652]
**Describe the bug**
 have recently purchase an Echelon EX5S with 22" screen and am having a few issues I would love some help with: I installed QZ on the bike'S 22" tablet. When waking up the bike by pedaling and then starting the QZ app , QZ finds the bike but doesn't seem to connect as I don't hear a beep, blue light does not go solid and no numbers are show. Bluetooth is on and there are no Bluetooth permissions to set with QZ. 

If I use my smartphone the bike immediately pairs and connect with QZ.

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 pro
 - OS: Android 10
Echelon tablet:
RK3288
Android Verison 9

![echelon](https://github.com/cagnulein/qdomyos-zwift/assets/145239602/8e6a4965-5b63-46b3-a183-2f09d34aaba2)

**Comment by cagnulein** [comment]
hi could you please attach a debug report?

Il giorno lun 18 set 2023 alle 19:44 Rezadue ***@***.***> ha
scritto:

**Comment by Rezadue** [comment]
[debug-Mon_Sep_18_13_26_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12651972/debug-Mon_Sep_18_13_26_13_2023.log)

**Comment by Rezadue** [comment]
Apologies.

**Comment by cagnulein** [comment]
No worries. i will  check it tomorrow, thanks

Il giorno lun 18 set 2023 alle 20:15 Rezadue ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @Rezadue the problem is that you enabled by mistake the "fake treadmill" setting in the experimental settings 
Disabled it and restart QZ
Let me know

**Comment by cagnulein** [comment]
Glad to hear this!
