### ISSUE TITLE
[REQ] Support for www.bestcycling.com

### ISSUE THREAD

**Issue by jorgehuedo** [cagnulein/qdomyos-zwift#1653]
Hi,
Would it be possible to work on compatibility with https://www.bestcycling.com/ ?
They support a small number of devices so far, I have raise them the same question if it would be possible to support your application.
Thanks.

**Comment by jorgehuedo** [comment]
I tried yesterday, using an Android phone and Surface tablet.
I will try again today with two android phones in case they have any
limitation on PC.
Is there any configuration option I should enable for FTMS? I'm running it
on default.
Thanks.

**Comment by cagnulein** [comment]
default one should be perfect. In case attach here a debug log so I can see your setup
Also be sure to try to rename your phone with QZ to "bike" (just 4 letters) and reboot it, it improves the bluetooth capabilities
Let me know

**Comment by jorgehuedo** [comment]
Hi Roberto,
I just changed the phone to Bike.
I tested it first with Zwift and no problem, but after I tried with
bestcycling and their app doesn't find the bluetooth.
I'm trying to contact their technical support and see if they can help here.
Thanks!
Jorge

**Comment by cagnulein** [comment]
ok let me know how it goes!

**Comment by jorgehuedo** [comment]
They might try...
Thanks Roberto for your fantastic support!!!


<img width="703" alt="image" src="https://github.com/cagnulein/qdomyos-zwift/assets/20927515/5b2b0b8a-3005-4309-a47e-2097af84d982">

**Comment by cagnulein** [comment]
@jorgehuedo any news?
