### ISSUE TITLE
Garmin watch heart rate won't show up in QZ[BUG]

### ISSUE THREAD

**Issue by Rezadue** [cagnulein/qdomyos-zwift#1654]
**Describe the bug**
I have installed the QZ companion in my Garmin Fenix 6X. I run the app, and start the timer but heart rate won't show up on my QZ app.

**Smartphone (please complete the following information):**
 - Device: Echelon EX-5S 22" tablet
 - OS: Android version 9

[debug-Tue_Sep_19_14_50_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12665825/debug-Tue_Sep_19_14_50_37_2023.log)

**Comment by cagnulein** [comment]
@Rezadue did you install the garmin connect app on the same device and the watch is paired to it?

**Comment by Rezadue** [comment]
I have not installed the garmin connect app on the Echelon tablet.

**Comment by cagnulein** [comment]
that's the issue. Garmin IQ apps work only when the device has the garmin connect app installed and paired

**Comment by cagnulein** [comment]
yep, otherwise you can use an ANT+ dongle on the echelon tablet ( I don't know if you will be the first one with this setup, but it *should* work)

**Comment by Rezadue** [comment]
Thanks. I used ANT checked and it seems my echelon tablet is compatible. I
then downloaded and installed all the services. And turned on Ant+ option
in the app. It did not pick up either my Garmin watch or my garmin ant+
enabled chest strap.

**Comment by Rezadue** [comment]
![20230920_125422](https://github.com/cagnulein/qdomyos-zwift/assets/145239602/06d1062d-9b07-49af-b51b-767555a381f7)

**Comment by cagnulein** [comment]
the echelon tablet is compatible but you need an ant+ dongle

Il giorno mer 20 set 2023 alle 18:59 Rezadue ***@***.***> ha
scritto:
