### ISSUE TITLE
[BUG] NordicTrack EXP 10i

### ISSUE THREAD

**Issue by tiju6998** [cagnulein/qdomyos-zwift#1655]
**Describe the bug**
I should be able to see the data in the app when the workout starts but it does not show.  Turn on Enable Virtual Device, Virtual Device Bluetooth in QZ, Turn on Wahoo Direct Connect in QZ.

**To Reproduce**
I was working fine initially and I was enjoying the app, Love the app thanks for this amazing app. I took a long gap for about 2-3 months. QZ on iphone does not pushes data, it says connecting but doe not connect. Tried to connecting to C1750 restarting the treadmill, tried by manually scanning wifi from the ios app but treadmill does not show up. Before raising this ticket I also reset the treadmill and install QZ companion app again but still the same. Treadmill and Iphone is connected on the same network and added the treadmill ip in the app as well. Treadmill model- NordicTrack  EXP 10i.  Thanks, any resolution would be much appreciated.

**Expected behavior**
I should be able to see the data in the app when the workout starts but it does not show. 

**Screenshots**
![376251389_10158936160882820_1670679175053716518_n](https://github.com/cagnulein/qdomyos-zwift/assets/114317374/0b830b1a-e379-4cc8-9bac-7d1ec896c525)
![378261946_10158936158292820_5491267640353143051_n](https://github.com/cagnulein/qdomyos-zwift/assets/114317374/436ab3d9-b54b-4e1b-8c54-d33901d7521a)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device:  iPhone 14 pro
 - OS: iOS
 - Version 17

**Append a debug log**
[debug-Tue_Sep_19_12_39_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12667319/debug-Tue_Sep_19_12_39_40_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
this debug log was using the C1750 setting? please add this one if not.
The problem is about an update of the ifit app on your treadmill. I always encourage to disable internet access to the treadmill in order to avoid this kind of issues
Let me know

**Comment by tiju6998** [comment]
Debug log was using the C1750.

[debug-Fri_Sep_22_19_48_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12705368/debug-Fri_Sep_22_19_48_04_2023.log)

**Comment by cagnulein** [comment]
thanks i will check it asap

Il giorno sab 23 set 2023 alle 03:56 tiju6998 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @tiju6998 checked but unfortunately i can't see any messages from the treadmill. are you able to ping the treadmill from the iphone? it seems that something it's preventing the treadmill to send messages to the phone

**Comment by cagnulein** [comment]
ok so the issue is in the companion somehow: i don't remember, did we check via adb?

**Comment by tiju6998** [comment]
I installed the companion through adb the second time after the treadmill reset,  and the payload and installed successfully.

**Comment by cagnulein** [comment]
ok so are you able to collect the debug log from the treadmill using this
script
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat
?

Il giorno lun 25 set 2023 alle 18:01 tiju6998 ***@***.***> ha
scritto:

**Comment by tiju6998** [comment]
Sure, on it. Give me some time.

**Comment by cagnulein** [comment]
no problem i got the flu so i'm at home waiting for issues 😂

Il giorno lun 25 set 2023 alle 18:06 tiju6998 ***@***.***> ha
scritto:

**Comment by tiju6998** [comment]
Attaching treadmill dump log screenshot as well. 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/114317374/a4296c41-86b9-4744-838c-eb57d1996618)

**Comment by cagnulein** [comment]
ah sorry that error is because you need to press the dump log button in the
companion before running the adb command

also the
2023-09-25_logs.txt
<https://github.com/cagnulein/qdomyos-zwift/files/12720901/2023-09-25_logs.txt>
file
is empty. also on your side?

Il giorno mar 26 set 2023 alle 02:57 tiju6998 ***@***.***> ha
scritto:

**Comment by tiju6998** [comment]
Sorry, will check and get back to you.

**Comment by tiju6998** [comment]
Generated the logs again. I confirmed the logs are not empty. 

[2023-10-14.logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/12906266/2023-10-14.logs.txt)
[logcat.log](https://github.com/cagnulein/qdomyos-zwift/files/12906267/logcat.log)
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/12906268/logcat.txt)
[2023-10-14_logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/12906269/2023-10-14_logs.txt)

**Comment by cagnulein** [comment]
hi @tiju6998 
log checked.
Unfortunately there isn't any string about the metrics of the treadmill. Did you collect them WHILE you're doing a workout?
Ifit removes the metrics when you stop the workout
Let me know

**Comment by tiju6998** [comment]
Had been travelling will upload the metric while doing the workout, thanks.

**Comment by cagnulein** [comment]
@tiju6998 any news?
