### ISSUE TITLE
Domyos EL500 elliptical Speed calculates on power

### ISSUE THREAD

**Issue by jjortizfernandez** [cagnulein/qdomyos-zwift#1656]
Hello Roberto
On bike Settings, QZ Domyos allows "Speed calculates on power".

I woul like If Possible, this feature"Speed calculates on Power"  also for Domyos El 500 Elliptical Bike.
Many thanks!!

**Comment by cagnulein** [comment]
sure i will do the same that i did here
https://github.com/cagnulein/qdomyos-zwift/discussions/1345

Il giorno mer 20 set 2023 alle 12:57 jjortizfernandez <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@jjortizfernandez actually I spoke too soon: your bike doesn't send the wattage, qz is calculating based on speed and inclination. So I can't calculate the speed based on the wattage based on the speed :) it's a dead loop :)

**Comment by jjortizfernandez** [comment]
I Understand.
Is it possible to activate Auto resistance mode  in Zwift  with Virtual Treadmill Mode?
Auto resistance Works Ok in Bike Mode for Domyos EL 500 Elíptical machine. (Resistance increases with terrain inclination)
Thanks !!

**Comment by cagnulein** [comment]
actually it should already work, are you using the meetup workaround https://www.youtube.com/watch?v=KTQ2n7yeDbo ?
