### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fscholaert** [cagnulein/qdomyos-zwift#1657]
**Describe the bug**
When the activity on QZ is stopped, Strava gets correctly the activity, except that the start time is two hours behind (see screenshots). 

**Screenshots**
![IMG_6192](https://github.com/cagnulein/qdomyos-zwift/assets/9047748/455f3677-693f-4b54-89c5-86d087f981c1)
![IMG_6191](https://github.com/cagnulein/qdomyos-zwift/assets/9047748/c7bd6789-4c2c-42fd-9610-5e5aabfe6034)

**Smartphone (please complete the following information):**
Device: IPhone 11
OS: iOS
Version 16.0.2

**Comment by cagnulein** [comment]
@fscholaert you need to correct your timezone on strava ;)

**Comment by fscholaert** [comment]
Ok, thanks!
