### ISSUE TITLE
[BUG]high wattage showing in Zwift , gain function not appearing to have an effect

### ISSUE THREAD

**Issue by Robsown** [cagnulein/qdomyos-zwift#1658]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
please attach a debug log @Robsown
