### ISSUE TITLE
[BUG]high wattage showing in Zwift , gain function not appearing to have an effect 

### ISSUE THREAD

**Issue by Robsown** [cagnulein/qdomyos-zwift#1659]
[debug-Fri_Sep_22_13_10_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12700657/debug-Fri_Sep_22_13_10_01_2023.log)
Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Robsown watt gain is 1 in this log (so the default one). i guess you're changing the wrong one. I'm talking about the one in the advanced settings "watt gain"

**Comment by Robsown** [comment]
Hi, I used the ‘Zwift resistance gain’ in bike settings, mistake on my part as I didn’t realise it was in advanced I’ll set that to 0.8 hopefully that will solve it

**Comment by cagnulein** [comment]
ok let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 set 2023 alle ore 14:41 Robsown ***@***.***>
ha scritto:

**Comment by Robsown** [comment]
Set to 0.7 working hard now .. many thanks for the great support

**Comment by cagnulein** [comment]
glad to hear this @Robsown !
