### ISSUE TITLE
[BUG]  ProForm Pro9000 treadmill

### ISSUE THREAD

**Issue by akyuzerkan** [cagnulein/qdomyos-zwift#1660]
[debug-Fri_Sep_22_05_12_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12700622/debug-Fri_Sep_22_05_12_27_2023.log)
**Describe the bug**

**To Reproduce**
1. Go to '.start the companion app on ProForm Pro9000 treadmill'
2. Click on 'Go to manual mode on the treadmill'
3. Scroll down to '.start the app on iPad '
4. iPad connects to the treadmill and shows the speed and incline changes. When clicked on + and - controls on the app, treadmill doesn’t respond. I tried an iPhone as well which had the same issue. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 17 public beta, iOS 15.7.1 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPad Pro 12 and iPhone 6s max 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@akyuzerkan adb is allowed for the QZ app in the treadmill android setting?

**Comment by akyuzerkan** [comment]
It was not. I just enabled the USB debug mode and attached is the new log. 
[debug-Fri_Sep_22_07_04_50_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12701590/debug-Fri_Sep_22_07_04_50_2023.log)

**Comment by cagnulein** [comment]
do you see now the touch events on the treadmill tablet when you press the
plus button on qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 set 2023 alle ore 16:08 akyuzerkan <
***@***.***> ha scritto:

**Comment by akyuzerkan** [comment]
No. Still the same behavior.

**Comment by cagnulein** [comment]
are you able to connect via adb from your pc?

**Comment by akyuzerkan** [comment]
I have a Mac, I don’t know if they have adb tools for it, but I’ll find a windows pc today and try it.

**Comment by cagnulein** [comment]
ok thanks, yes adb is also available for mac!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 set 2023 alle ore 17:00 akyuzerkan <
***@***.***> ha scritto:

**Comment by akyuzerkan** [comment]
I am not able to connect it via adb. It looks like adb service is not running on the treadmill

**Comment by cagnulein** [comment]
@akyuzerkan you have to enable it in the developer settings of android on your treadmill. if you can't you have to factory reset the treadmill 

let me know

**Comment by akyuzerkan** [comment]
I enabled the USB debugging in the developer settings on the treadmill but the attached is the error I get

<img width="572" alt="Screenshot 2023-10-13 at 7 53 46 AM" src="https://github.com/cagnulein/qdomyos-zwift/assets/145773290/3f60fdc5-b04a-4873-a730-18b824825f96">

**Comment by akyuzerkan** [comment]
Maybe I am connected ? Please see attached

<img width="569" alt="Screenshot 2023-10-13 at 7 57 32 AM" src="https://github.com/cagnulein/qdomyos-zwift/assets/145773290/70fd45a4-a040-4e47-9f4e-14e29d1c7611">

**Comment by akyuzerkan** [comment]
I think I am connected, how do I troubleshoot from here?

<img width="573" alt="Screenshot 2023-10-13 at 8 00 07 AM" src="https://github.com/cagnulein/qdomyos-zwift/assets/145773290/8656b344-f707-46bc-ad19-b576d8a25ac3">

**Comment by cagnulein** [comment]
ok perfect, you are still not showing any metrics in qz? if so try to set the c1750 device in the companion and restart the treadmill, let me know 

ifit locks some doors so we have to find the right way to achieve this for your treadmill

**Comment by cagnulein** [comment]
great you are connected to adb now. enable in the android developer settings of the treadmill the touch event so you will see a ghost under each touch

then in qz, if you see the speed and incline correctly in the qz app, try to change speed or incline from qz: are you seeing some touch events on the treadmill?

**Comment by akyuzerkan** [comment]
I can see the speed and incline on the app but app can’t change them on the treadmill. I don’t see any touch event on the screen

**Comment by cagnulein** [comment]
hi @akyuzerkan from shell on mac type

adb shell
input swipe 100 200 300 400 200

and let me know if you see a touch event

**Comment by akyuzerkan** [comment]
Now, when I connect it says device is offline

erkan.akyuz@Erkan-Macbook-Air adb % ./adb shell
adb: device offline

erkan.akyuz@Erkan-Macbook-Air adb % ./adb devices -l            
List of devices attached
10.0.0.21:5555         offline transport_id:4

**Comment by cagnulein** [comment]
means adb is disabled on the tablet. i don't what it's changed from the
last time , could you try to understand it?

Il giorno dom 15 ott 2023 alle 19:55 akyuzerkan ***@***.***>
ha scritto:

**Comment by akyuzerkan** [comment]
I disabled usb debugging and reenabled, its connected now.

Progress !!!

when I give the input swipe comment, I get a touch event. It goes into the pause screen like I touched somewhere on the screen myself.

**Comment by cagnulein** [comment]
perfect! that's perfect! so in this state, can you try to push the plus button on qz? is it working now?

**Comment by akyuzerkan** [comment]
Still the same, doesn't respond.

**Comment by cagnulein** [comment]
ok so we need to be sure that the companion is receiving the commands . in
order to do so:

1. start a manual workout on the treadmill
2. open the companion
3. press the plus button on the speed
4. press the dump log button in the companion
5. send me a picture of what you see

3-4-5 must be taken as fast as possible in order to not missing an event
thanks

Il giorno dom 15 ott 2023 alle 21:16 akyuzerkan ***@***.***>
ha scritto:

**Comment by akyuzerkan** [comment]
Nothing happens when I click on the dump log. Is it supposed to display a log?

**Comment by cagnulein** [comment]
yes you have to see the logs in the text box in the companion. Never happen before that a user can't see anything. Did you try pressing it multiple times?

**Comment by akyuzerkan** [comment]
I tried clicking multiple times.

**Comment by cagnulein** [comment]
ok let's go with the adb method to collect the logs
so:

1. prepare the adb script that you can find here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/3.3.6/InstallPackage/adb-debug.bat
2. start a manual workout on the treadmill
3. press the plus button on the speed
4. collect the logs with the script above

2-3-4 must be taken as fast as possible in order to not missing an event

Let me know!
thanks

**Comment by cagnulein** [comment]
@akyuzerkan any news?
