### ISSUE TITLE
[BUG] QZ KM to Miles conversion?

### ISSUE THREAD

**Issue by speedf1** [cagnulein/qdomyos-zwift#1662]
Not sure if this is a bug or just my lack of understanding of how QZ works......

The Echelon stride reports speed as km/h, but I really want to display it as mph in the speed tile.  When I have the "Use Miles unit in UI" set to off then the speed tile shows the same figure reported on the stride (i.e. km/h), even though the tile says mph.  If I switch the "Use Miles unit in UI" to on, then there is a conversion but not from km/h to mph.

Am I missing something?

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/5621f326-9cf6-49e5-a580-b6940913be9c)

toggle this and restart qz

let me know

**Comment by speedf1** [comment]
Hi, yes this is the setting I've toggled.  It certainly does something, but doesn't seem to convert the kmh reported by the stride into mph.  
If it is toggled off, then the number shown in the tile is the same as on the stride (i.e. kph)
If it is toggled on, then the numbers shown in the tile are greater than kmh; obviously they should be smaller.

**Comment by cagnulein** [comment]
so toggle this

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/43cf615b-da99-402e-9b64-df6082a9d7a8)

**Comment by speedf1** [comment]
Sorry, I completely misread your first comment!  I've been talking about the "Use Miles unit in UI" option in the General Options section of the settings, but just realised that your comment suggests toggling a Miles option in an Echelon section.  Where is that option, I can't see it in version 2.16.12?

**Comment by speedf1** [comment]
Ah, just found it; it's within the treadmill section!  I'll give that a go.

**Comment by speedf1** [comment]
Once again, thanks for your help.  I'm really impressed with how quickly your respond.  It's like you're sitting waiting for issues to come in!

**Comment by cagnulein** [comment]
more or less, actually i'm playing with my baby daughter :)

Il giorno ven 22 set 2023 alle 22:19 speedf1 ***@***.***> ha
scritto:

**Comment by speedf1** [comment]
All seems to be working now; thanks again for your help.  Hope you had some great daddy and daughter time!

**Comment by cagnulein** [comment]
great! thanks!
