### ISSUE TITLE
[BUG] No rpm/cadence Tunturi T80

### ISSUE THREAD

**Issue by Joeribar** [cagnulein/qdomyos-zwift#1663]
#@
[debug-Fri_Sep_22_23_20_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12704741/debug-Fri_Sep_22_23_20_58_2023.log)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
sorry @Joeribar i'm completely missed this notification. do you still have the issue?
