### ISSUE TITLE
[BUG] Apple Watch Heart Rate Not Being Picked Up On iPhone App

### ISSUE THREAD

**Issue by LiamJones-87** [cagnulein/qdomyos-zwift#1664]
**Describe the bug**
When starting a workout on the Apple Watch Apple, it tracks the heart rate and saves it to the health app. However, this is not picked up on the iPhone app (or in Zwift)

Debug file attached
[debug-Sat_Sep_23_14_49_11_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12706601/debug-Sat_Sep_23_14_49_11_2023.log)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17

**Comment by cagnulein** [comment]
settings  are fine, the iphone app is simply not getting any messages from
qz on the phone
i guess you don't see also any distance or kcal on the qz app on the watch
neither, right?

Il giorno sab 23 set 2023 alle 15:58 LiamJones-87 ***@***.***>
ha scritto:

**Comment by LiamJones-87** [comment]
Correct. Even under settings they’re showing as 0 as well. As you can see (see attached) ass permissions are on.
![IMG_9933](https://github.com/cagnulein/qdomyos-zwift/assets/72579080/b6dc1e90-380b-4bb8-9829-fe07df504eaf)

**Comment by cagnulein** [comment]
what do you mean " under settings they’re showing as 0 as well".

are all the permissions qz app on the phone are enabled?

**Comment by LiamJones-87** [comment]
So, on the iPhone, when you go into settings > health > data > qdomyoszwift > data. The Active Energy and distance are recorded as 0.

Yeah, all enabled

**Comment by cagnulein** [comment]
@LiamJones-87 i missed this notification. did you fix it?
