### ISSUE TITLE
[BUG] Peloton Resistance is not following the Targeted Peloton Resistance when using the "lower" option

### ISSUE THREAD

**Issue by Peaceout32** [cagnulein/qdomyos-zwift#1668]
**Describe the bug**
Peloton Resistance is not following the Targeted Peloton Resistance when using the "lower" option

**To Reproduce**
Pretty much any Peloton ride as long as the difficulty is set to lower (not sure if it happens with the other 2 options)

**Expected behavior**
As you can see in the attached pictures, the Target Peloton Resistance is between 27 and 42, however the actual Peloton Resistance is automatically set to 24. Normally when that happens it's because the Targeted Resistance doesn't exist but 27 exists and I can set it by manually pressing the "+" (second picture)
[debug-Mon_Sep_25_10_19_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12716934/debug-Mon_Sep_25_10_19_03_2023.log)

**Screenshots**
Attached

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.0.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
![IMG_1101](https://github.com/cagnulein/qdomyos-zwift/assets/110363509/c27ea53f-6bdd-4b0b-b983-287a34518b58)
![IMG_1102](https://github.com/cagnulein/qdomyos-zwift/assets/110363509/321144dd-2808-4fdd-939a-7876cabdc314)
[debug-Mon_Sep_25_10_19_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12716945/debug-Mon_Sep_25_10_19_03_2023.log)

**Comment by cagnulein** [comment]
thanks, i will check this. did we talk on the facebook group about this,
right?

Il giorno lun 25 set 2023 alle 17:24 Peaceout32 ***@***.***>
ha scritto:

**Comment by Peaceout32** [comment]
Yes!

**Comment by Peaceout32** [comment]
Just wait until you get better. Absolutely no rush for this.

**Comment by cagnulein** [comment]
Ok I did the math and the issue is that with echelon resistance = 10 the peloton conversion is 24, but with echelon resistance = 11 the peloton conversion is 27.5, that's why requesting peloton resistance 27, qz still use echelon resistance 10. 

Does it make sense to you?

**Comment by cagnulein** [comment]
what I can do, it's to not show directly the target peloton resistance value from the peloton api, but the conversion of the bike. so in this case you will see target peloton resistance 24.

Let me know what you think

**Comment by Peaceout32** [comment]
> what I can do, it's to not show directly the target peloton resistance value from the peloton api, but the conversion of the bike. so in this case you will see target peloton resistance 24.
> 
> Let me know what you think

No definitely not, the instructor says the range so that would just be confusing for everybody. 

I think you should leave it like it is or make it ignore the decimals and use the 27.5 because the way I personally see it, the settings should be:
"min" : be the first resistance available in the target range, in this case 27
"average": closest to (first available resistance + last available resistance)/2 
"max" : last available in the range, in this case, whatever is closest to 42

But that's just my point of view

**Comment by cagnulein** [comment]
actually min avg and max are from peloton directly, i'm not calculate them.

So, just to understand, the peloton instructors calls "27" directly? if so the only way I can change this is to try to change the bike resistance to the one nearest to the peloton requests

so for example for 27 the bike closest bike resistance is 11, i will set 11 (not the min one as I did now). but this is nice for this case, but could change also the behaviour for other resistance that are good...what do you think?

**Comment by Peaceout32** [comment]
Yes, they always say stuff like 25 to 40 like in this case. They probably said that and then said "add 2 to resistance" which gave us the 27 to 42.

Or sometimes they'll say 40 or more and then we'll see the actual range in the QZ app.

Do you want access to Peloton to check it out?

**Comment by cagnulein** [comment]
ok, no no i don't need it thanks. so actually the only way that I can see to achieve this is the method that I described above but this for sure be done under a new settings because it *may* change the behaviour for the other users

**Comment by Peaceout32** [comment]
Leave it as it is. It's not worth your time and effort more than you've spent already! Have a good day Roberto and thanks for checking it out.

**Comment by cagnulein** [comment]
Ok no problem, I will keep this in mind if someone will raise the same
issue!
Thanks for your feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 set 2023 alle ore 15:20 Peaceout32 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
similar to #1707

**Comment by cagnulein** [comment]
@Peaceout32 are you still interested on this? I guess I found an easy and elegant way to fix it. Let me know!

**Comment by Peaceout32** [comment]
Hey! Yeah sure :)

**Comment by cagnulein** [comment]
ok i will send you the patch asap!

Il giorno sab 28 ott 2023 alle 14:47 Peaceout32 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Peaceout32 done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you it. Thanks!

**Comment by cagnulein** [comment]
@Peaceout32 are we ok with this?

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/0daa93ca-974c-47c0-aab0-f9c26669f6c4)
