### ISSUE TITLE
Rowing With Zwift Avatar Keeps Moving When You Stop

### ISSUE THREAD

**Issue by jdmueller** [cagnulein/qdomyos-zwift#1671]
When rowing with Zwift everything works as expected except this one issue for me. I notice that when I am rowing at a steady say 120watts and then a stop to take a break the system will continue reading power from my device even when there is no input coming in. So If I take a short 2 minute break after a sprint at 300 watts my avatar keeps moving at that pace of 300 watts until I start pulling again.

**Comment by cagnulein** [comment]
hi @jdmueller can you attach the debug log as mentioned in the link https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

thanks

**Comment by jdmueller** [comment]
Ok I did another row with the log option checked. I looked in my files section on iPhone and couldn’t find any log files. I do see the files from my other apps there. So everything is up to date latest iOS and Zwift as of yesterday. When I stop rowing it takes my last power measurement and my avatar in Zwift keeps moving at that pace until I pull another stroke. Most of the rowing apps auto pause but maybe your app is more accurate for my 10k if I take short breaks. But is there an option to auto pause in your app? The Zwift power input would be good to fix because obviously it puts km on the clock if I take a bathroom break. But I love the fact I can Zwift with my rower.

Thanks

**Comment by cagnulein** [comment]
@jdmueller are you keeping the debug log always on? it sounds like you are enabling it only for a test drive and disabling it? also can you send me a full screenshot of your qdomyos folder?
It's impossible to understand your issue without a debug log
thanks

**Comment by jdmueller** [comment]
I have enabled the only option I see for debug I am not turning it off. I have checked my files section I see folders for the other apps but nothing for this app. I don’t see any log files or any files being created on my device.

**Comment by cagnulein** [comment]
could you please share a screenshot of the qdomyos folder? are all the permissions enabled for qz?

**Comment by jdmueller** [comment]
Sorry I’m dumb the files are there but the email won’t send I’ll try again through GitHub later

**Comment by cagnulein** [comment]
@jdmueller you can send me it by email to roberto.viola83@gmail.com

**Comment by cagnulein** [comment]
[debug-mié_sep__27_23_35_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12777920/debug-mie_sep__27_23_35_36_2023.log)
[debug-jue_sep__28_09_38_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12777921/debug-jue_sep__28_09_38_12_2023.log)
[debug-jue_sep__28_09_33_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12777922/debug-jue_sep__28_09_33_29_2023.log)

**Comment by cagnulein** [comment]
I will check them tomorrow

**Comment by cagnulein** [comment]
@jdmueller I patched it (it was a error of your rower implementation in the firmware :). 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by cagnulein** [comment]
@jdmueller  any news?

**Comment by jdmueller** [comment]
Yeah! It works. I have had the power drop out maybe 2 or 3 times in an hour (just for a split second) but I think that might be my cadence getting low and not registering on my machine. No issues with the app it works perfectly! I am rowing on Zwift now 2 days a week.

Awesomeness 🤩 thank you ! This app is such a great idea.

**Comment by cagnulein** [comment]
glad to hear this!
