### ISSUE TITLE
Can connect to Horizon t202-6  but no stats or control

### ISSUE THREAD

**Issue by Dilbert66** [cagnulein/qdomyos-zwift#1680]
QZ on Android will connect quickly to the Horizon threadmill model T202-6 but no stats will show and cannot control any functions.
Have tried restarting QZ repeatedly as well as threadmill.   
Threadmill is started first, then QZ.  Bluetooth light on threadmill then lights and QZ indicates connection is established with the T202 and displays the tiles for controls but not stats show and threadmill cannot be started or stopped.  Starting the threadmill manually also does not get seen by QZ.
Phone is a Pixel 6A running Android version 13

[debug-Fri_Sep_29_12_16_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12769693/debug-Fri_Sep_29_12_16_59_2023.log)
[debug-Fri_Sep_29_12_24_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12769694/debug-Fri_Sep_29_12_24_06_2023.log)

**Comment by cagnulein** [comment]
Hi, i checked the log and i guess the error is because horizon have a
different protocol on this machine.

could you please follow this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
with the horizon app?

Let me know!

Il giorno ven 29 set 2023 alle 19:30 Alain Turbide ***@***.***>
ha scritto:

**Comment by Dilbert66** [comment]
Ok, I will follow those steps and advise when complete! Thank you !

**Comment by Dilbert66** [comment]
Here is the btsnooop log from atzone.  Ran a sample workout program with various speeds and inclinations.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/12771611/btsnoop_hci.log)

**Comment by cagnulein** [comment]
hi @Dilbert66 in the horizon setting, enable the "Force Using FTMS" and restart QZ
Let me know!

**Comment by Dilbert66** [comment]
Ah! Yes that fixed it! Thank you!

**Comment by cagnulein** [comment]
great!
