### ISSUE TITLE
[BUG] on proform RL with Holofit, strokes and hr reported but not pace or calories

### ISSUE THREAD

**Issue by brupec** [cagnulein/qdomyos-zwift#1681]
Hi again Roberto,

Like we talked in email, I have:

Proform RL connected to QZ (with proform RL profile and virtual rower enabled)
Holofit connected to QZ

The rower is detected, I renamed the phone to row, (but same behavior with other name)

When I start a race, I can see the strokes rate and heart rate from my belt (also connected to QZ) reported correctly.
But the m/500m and the calories stays at 0, so I can not move.

I see in another holofit ticket similar that there should be a screen when I see the row values that holofit get, I'll try to find it because I think from that holofit get the speed from qz and not the m/500m directly (it probably recalculates it)

[debug-Sat_Sep_30_11_12_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774359/debug-Sat_Sep_30_11_12_36_2023.log)
[debug-Sat_Sep_30_11_17_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774356/debug-Sat_Sep_30_11_17_32_2023.log)

here are logs from last try

Cheers

**Comment by cagnulein** [comment]
try this one
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6362002257

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 set 2023 alle ore 11:33 brupec ***@***.***>
ha scritto:

**Comment by brupec** [comment]
Ok I'll try when buildt. Interesting fact I noticed is that it is having speed reported when I disable virtual rower. But detected as bike of course

**Comment by cagnulein** [comment]
yes i guess i understood why: i was sending strokes count at 0 to virutal fit, so they probably clear the pace since strokes count is 0 i guess

**Comment by brupec** [comment]
allright ;-) can't wait to try out

**Comment by cagnulein** [comment]
don't worry about the action error, you can download it

**Comment by brupec** [comment]
Seems build failed

Le sam. 30 sept. 2023, 12:01, Roberto Viola ***@***.***> a
écrit :

**Comment by brupec** [comment]
Ahh ok sorry

Le sam. 30 sept. 2023, 12:36, Roberto Viola ***@***.***> a
écrit :

**Comment by brupec** [comment]
here are some logs
[debug-Sat_Sep_30_13_36_39_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774548/debug-Sat_Sep_30_13_36_39_2023.log)

still same no pace
[debug-Sat_Sep_30_13_30_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774550/debug-Sat_Sep_30_13_30_35_2023.log)

[debug-Sat_Sep_30_13_33_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774549/debug-Sat_Sep_30_13_33_29_2023.log)

**Comment by cagnulein** [comment]
@brupec other test https://github.com/cagnulein/qdomyos-zwift/actions/runs/6363208067

**Comment by brupec** [comment]
same

[debug-Sat_Sep_30_16_31_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12774918/debug-Sat_Sep_30_16_31_20_2023.log)

calories increased so something may have changed, I think it didn't before

but m/500m stays at 00:00

**Comment by cagnulein** [comment]
ok let's try this
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6363840751
if it still doesn't work i will try to simulate it here somehow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 set 2023 alle ore 16:37 brupec ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
any news?

**Comment by brupec** [comment]
Hi Roberto, sorry still out of home, I'll try in the afternoon when back

Le dim. 1 oct. 2023, 09:21, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
No problem, take your time.

Il giorno dom 1 ott 2023 alle 11:34 brupec ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ok. Since i don't have a metaquest could you do a simple test for me? with qz running on a phone, could you open nrfconnect app on another phone and reading the rowing indoor data characteristics: i would like to see if you see the pace correctly there.
Let me know

**Comment by brupec** [comment]
Sure, i launched it abd connected to the rower, I see generic attribures,
generic access and fitness Machine, but can't see the speed pace and so on,
where do I see them?

Le lun. 2 oct. 2023, 10:30, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
under fitness machine, there is the rower data

**Comment by cagnulein** [comment]
> it was hard because it keeps connecting/disconnecting, but at one point it was stable so I could check the infos.

yes that's right because any BTLE communication needs to be pinged otherwise it will be on timeout and so disconnects.

> btw, is it normal I can see two times "row" sometimes (in holofit was the same). One works the other not. I imagine one is phone other is QZ. in nrf I could see two before but just one after. I also tried to bond but still it is not connecting stable.

yes it's normal too, because due to the android kernel, everytime qz brings up the inferface, the virtual mac address changes.


> So pace is there, just distance stays at 0. but from a screenshot in other issue (#876) I can see it uses distance so maybe it's the cause ? I looked everywhere and cannot find where that man saw this debug screen in the app, maybe it's because i'm still in trial in holofit.

let me check about the distance, it could be the culript

**Comment by cagnulein** [comment]
I guess you are right @brupec I was sending km instead of meters!
Let's try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/6378599134
Let me know

**Comment by cagnulein** [comment]
great! yes i will do in the next days!
