### ISSUE TITLE
[BUG] ERG setting high resistance on Merach S09

### ISSUE THREAD

**Issue by hortocam** [cagnulein/qdomyos-zwift#1683]
Default settings on QZ.  Set ERG mode on.  Exited and restarted. 

QZ running on iPhone.  Apple Watch for HRM.  Zwift running on Macbook Pro (M2).  

1.  Start workout (Slow Motion). 
2. Resistance set to 4 (default)
3. Warmup starts at 80w.  No issues
4. Once the warmup ramps to 115w, everything goes sideways. 
5. I think that my cadence was around 70.
6. Resistance jumps to 10 then to 24 and back to 14.  
7. Even though my power output is greater than the target power, the resistance never goes down.  

I stuck with it at 14 until my legs were on fire.  It never reduced.  

I did a free ride later (erg turned off) and had no issues.  

I've attached QZ logs and the corresponding Zwift logs.  

[debug-Sat_Sep_30_13_33_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12776059/debug-Sat_Sep_30_13_33_01_2023.log)
[Log.txt](https://github.com/cagnulein/qdomyos-zwift/files/12776060/Log.txt)
[debug-Sat_Sep_30_18_42_42_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12776061/debug-Sat_Sep_30_18_42_42_2023.log)
[Log 2.txt](https://github.com/cagnulein/qdomyos-zwift/files/12776062/Log.2.txt)

**Comment by cagnulein** [comment]
@hortocam the issue is that your bike doesn't handle directly the ERG mode. QZ is simulating for you.
Since I didn't add a specific ERG table for your bike, QZ is doing what it's right for this bike https://github.com/cagnulein/qdomyos-zwift/issues/1526

So if you want to add ERG mode to your bike, I need a similar cadence/wattage table for your bike too.
Let me know!

**Comment by hortocam** [comment]
Yeah, I had figured that out by looking at the logs and reviewing the source code.  

I'd love to get the right information to you.  Can you give me any idea on how to find that table?  I'm assuming that I'm not going to be able to compile it manually by hitting all of the points in that matrix and recording cadence and wattage.

**Comment by cagnulein** [comment]
> Can you give me any idea on how to find that table? I'm assuming that I'm not going to be able to compile it manually by hitting all of the points in that matrix and recording cadence and wattage.

yes exactly! you have to manually compile it. More points we have and more the equation could be "true"

Let me know if you have any doubts

**Comment by hortocam** [comment]
Ok.  I will see what I can figure out.  I probably won't have feedback until tomorrow.  Thanks.

**Comment by hortocam** [comment]
I've done a bunch of tests with debug turned on in QZ.  I wrote some basic grep and sed commands to capture the details that you're logging so that I could spit out a CSV file with all of the cadence, resistance, power values.  

I tested several specific sequences where I worked through each resistance level trying to stay as close to 60 rpm as I could.  I plugged the data into Excel and did a pivot table to look at the average power/rpm by resistance level.

I compared this to about 10 different rides I did over the past week and my findings are consistent.  

I've attached the power table based on my experiments.  

In the meantime, Merach sent me an entire new bike because I convinced them the controller wasn't functioning correctly.  The new one works exactly the same in Zwift which most likely means this is a Zwift problem.  

I did ask them for the power curve documentation so that I could get the right settings to compare with other equipment.  For each resistance level they provided a torque (nm) value and wattage.  I don't know how that really maps to the watt table needed.  I'm sharing it as well in case you have any use for it.  

I am eager to be able to have a working ERG mode.  Let me know if there's anything I can do to help.  
[MRK-S09-WattTable.csv](https://github.com/cagnulein/qdomyos-zwift/files/12851796/MRK-S09-WattTable.csv)
[MRK-S09-Torque.csv](https://github.com/cagnulein/qdomyos-zwift/files/12851797/MRK-S09-Torque.csv)

**Comment by cagnulein** [comment]
perfect! I'm adding it! I will let you know when I will be ready (hopefully
today!)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 ott 2023 alle ore 03:26 Cameron Horton <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@hortocam done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by cagnulein** [comment]
@hortocam are we good with this?
