### ISSUE TITLE
Echelon auto-resistance is not working

### ISSUE THREAD

**Issue by andregotz** [cagnulein/qdomyos-zwift#1684]
**Describe the bug**

Been talking to you on facebook, the issue where the app isn’t moving the resistance while I ride on Zwift or Mywoosh app. When I start my Zwift connect everything the resistance goes all the way up to 23 and stays there for as long as I ride the bike, it doesnt change. 

Using iPhone 14 plus with QZ app
Using IPad Pro for Zwift and Mywoosh, peloton etc.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @andregotz please attach a debug log

**Comment by andregotz** [comment]
I have told Roberto many times on the facebook posts, that I can’t find the debug folder to attach anything. I have debug settings ON for the app, but I have no idea what to do next. I’m getting frustrated, I have uninstalled the app multiple times, and I have not changed any settings. I connect to the app I want to use Zwift or Moosh and all I get is one resistance all the way till the end of the work out, it varies, sometimes its 5, sometimes is 8 sometimes is 23, and sometimes is max level 32

**Comment by cagnulein** [comment]
I'm Roberto :)
Share here a screenshot of your experimental settings and the qz folder
please
also of your permissions for qz
thanks

Il giorno dom 1 ott 2023 alle 17:52 andregotz ***@***.***> ha
scritto:

**Comment by andregotz** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/0cf74df7-ebbe-4cd1-b87c-98cdbe013e81)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/640f4897-d527-4c4f-909e-9955618dfba3)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/bf92fbd0-21d4-4ca6-b384-8770aa3ace4c)

**Comment by andregotz** [comment]
You need to be a little be more clear when you mention things, I still dont know where the qz folder is. I keep asking you.

**Comment by cagnulein** [comment]
sorry but i'm helping you on sunday with my baby on my arms.

all the information about the debug log are in the link that i provided 

you will see a folder like this in the files app

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/c9c92e80-ae6e-4830-b1a8-e30c6d9a704a)

**Comment by andregotz** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/26eb5a27-c30f-4763-ae79-abac7603c27c)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/2dc63df4-f349-4172-92af-b27fb1993132)
NO QZ folder on my Files app on my IPhone.

**Comment by cagnulein** [comment]
that's icloud drive, you have to browse back to the iphone local root
folder

Il giorno dom 1 ott 2023 alle 18:23 andregotz ***@***.***> ha
scritto:

**Comment by andregotz** [comment]
Ok, see I follow all the steps on your link, you may need to change that to a clear explanation on where to find the QZ file. I found it now. Give me a sec so I can upload the stuff

**Comment by cagnulein** [comment]
ok strange, there are more than 1600 tickets here, nobody complains about
it, but maybe you're right, i'm italian, so my english is very poor.
if you can, since qz is open source, please let me know how i can describe
it better
thanks

Il giorno dom 1 ott 2023 alle 18:27 andregotz ***@***.***> ha
scritto:

**Comment by andregotz** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/83249808/0f72e8bc-dd1c-4c9d-ab54-5f1a9899c3e5)
Not allowing me to upload now.

**Comment by cagnulein** [comment]
compress it from the files app, then upload directly the zip file or send
me by messenger or email. i will upload it for you

Il giorno dom 1 ott 2023 alle 18:31 andregotz ***@***.***> ha
scritto:

**Comment by andregotz** [comment]
[debug-Sun_Oct_1_12_14_34_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12777642/debug-Sun_Oct_1_12_14_34_2023.zip)

**Comment by cagnulein** [comment]
thanks, i will check as soon my baby will go to bed

Il giorno dom 1 ott 2023 alle 18:37 andregotz ***@***.***> ha
scritto:

**Comment by andregotz** [comment]
Thank you and I truly appreciate you taking your time trying to help me. I just can’t figure it out from the moment I got the app I got nothing working. Not matter what I do.

**Comment by cagnulein** [comment]
in this log i saw clearly the automatic resistance working changing the resistance from 5 to 7 than 8 than 7.

maybe you have a fault on the resistance on hardware?

to troubleshoot this, without any other 3rd party apps, just qz, use the resistance tile to change the resistance with the plus and minus button. do you feel the resistance on the bike?

**Comment by andregotz** [comment]
That was me changing manually because it wasn’t changing automatically when the slope came etc.. so I was pressing the buttons on the app the+ and - to change

**Comment by andregotz** [comment]
[debug-Sun_Oct_1_12_40_32_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12777885/debug-Sun_Oct_1_12_40_32_2023.zip)

**Comment by andregotz** [comment]
Here is another file where I didnt touch anything, went through a slope and didnt change the resistance at all.

**Comment by cagnulein** [comment]
> [debug-Sun_Oct_1_12_40_32_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/12777885/debug-Sun_Oct_1_12_40_32_2023.zip)

in this file zwift or the 3rd party app sent always 0.2 grade an qz set it correctly to resistance 5 accordingly to your setting (zwift resistance offset)

also in the previous file, the changes that I mentioned were automatically, I can see in the log. That's why I'm asking to check the hardware resistance from qz, maybe you have something wrong in the bike.

So please, first confirm that the bike is working ok without any 3rd party apps, then let's go on zwift or mywhoosh.

I'm going to bed soon, so in case I will answer back tomorrow

**Comment by andregotz** [comment]
Yeah the bike is working fine with the Echelon fit app, I can change the resistance, as you know when using the 
Echelon fit you have to change the resistance manually. The last file I sent was with Mywoosh.not sure what To do next.

**Comment by cagnulein** [comment]
@andregotz IDK I mean from here everything works ok. Maybe provide me a video along with a debug log where I can see the issue. Maybe you're expecting something different from the actual scenario?
Are you seeing the resistance tile on QZ? is it not change neither? try the video+debug so tomorrow I can check if there is something else

**Comment by cagnulein** [comment]
for example keep on the screen the tiles:
- target inclination and the resistance. 

they MUST move together (if the inclination changes is bigger enough to change the resistance)

**Comment by andregotz** [comment]
It’s ok,I think I’m tired of trying to solve this. I have tried it all. I appreciate Roberto.

**Comment by cagnulein** [comment]
ok if you will change your mind i'm here

Il giorno dom 1 ott 2023 alle 21:08 andregotz ***@***.***> ha
scritto:
