### ISSUE TITLE
[BUG] Echelon Sport Connect stopped talking to app after I moved some tiles around and played with settungsr

### ISSUE THREAD

**Issue by squamloon** [cagnulein/qdomyos-zwift#1687]
I'm sure I just need to turn something back on, but I can't figure out what I turned off. It's worked for years.

This is a follow-up to a message I sent you in Messenger. 

Pixel 6, Android 13
Echelon Connect Sport
Peloton on MacBook Pro

![inbound4356513030042436117](https://github.com/cagnulein/qdomyos-zwift/assets/25773520/c0d631f9-886c-4797-9ccc-5c901599d1e5)

**Comment by cagnulein** [comment]
hi @squamloon please attach a debug log
thanks

**Comment by cagnulein** [comment]
@squamloon the issue here is that you are in pause mode, you have only to press the start flashing red button on qz or disable the "pause on start" setting
let me know

**Comment by squamloon** [comment]
I wish it were that simple. I've pressed play, and nothing happens. Here are some more logs? 
[debug-Wed_Oct_4_20_49_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12811185/debug-Wed_Oct_4_20_49_58_2023.log)

**Comment by cagnulein** [comment]
hi the problem is that you have also the fake device enabled in the
experimental settings. Disable it and restart QZ
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 ott 2023 alle ore 02:58 squamloon ***@***.***>
ha scritto:

**Comment by squamloon** [comment]
God I'm an idiot. Grazie ! Sending you a coffee for your trouble.

**Comment by cagnulein** [comment]
Haha, no problem!

Il giorno gio 5 ott 2023 alle 08:46 squamloon ***@***.***> ha
scritto:
