### ISSUE TITLE
controllo resistenza

### ISSUE THREAD

**Issue by encer9598** [cagnulein/qdomyos-zwift#1691]
Toorx Speed Mag Pro
App su Samsung s23
ho caricato una traccia gpx che parte immediatamente in salita: vedo la mappa, vedo tutti i parametri compresa la pendenza ed il dislivello effettuato ma non si modifica la resistenza

grazie

[debug-Mon_Oct_9_11_56_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12844780/debug-Mon_Oct_9_11_56_06_2023.log)

**Comment by cagnulein** [comment]
credo di aver capito il problema: qz sta mandando i comandi per cambiare la resistenza ma la bici la ignora.

hai mai provato a vedere se con kinomap invece la resistenza cambia? o in generale anche l'app ifit

**Comment by encer9598** [comment]
sì, ma solo con kinomap, mentre invece non la modifica con zwift e con
mywhoosh

Il giorno lun 9 ott 2023 alle ore 12:16 Roberto Viola <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok forse ho capito: riesci a seguire questa guida con kinomap
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
?

Il giorno lun 9 ott 2023 alle 12:18 encer9598 ***@***.***> ha
scritto:

**Comment by encer9598** [comment]
problema risolto, ottimo supporto

**Comment by cagnulein** [comment]
grande! per i posteri potresti lasciare qui qual è stato il settaggio che
ha risolto?

Il giorno mar 10 ott 2023 alle 12:52 encer9598 ***@***.***>
ha scritto:
