### ISSUE TITLE
Cannot connect to Nordictrack Elite 900 treadmill[BUG]

### ISSUE THREAD

**Issue by barbenbar** [cagnulein/qdomyos-zwift#1693]
**Describe the bug**
qdomyoszwift cannot connect to Nordictrack Elite 900 treadmill after installation of QZ companion.

**To Reproduce**
1. Install QZcompanion as instructed on https://www.youtube.com/watch?v=_KRMSHxo5AQ&ab_channel=RobertoViola
2. Install qdomyoszwift on phone, enter IP in 'Nordictrack 2950 IP' field. 
3. Chose C1750 as a bike on the companion & reset treadmill. (I tried with other option as well)
4. Start a manual workout in Ifit. I can see the tiles on the phone App but no information appear in them.

**Expected behavior**
I expected the tiles to display same information as the treadmill. Nothing appears in the tiles, 'Connecting...' is always shown on top on screen on the app.

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: IOS
 - Version 16.6.1

**Append a debug log**
[debug-lun__oct__9_10_32_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12847834/debug-lun__oct__9_10_32_51_2023.log)

Let me know what I can do to help. I have also installed to app on another phone (Android) with the same result (no data sent).

Thanks!

**Comment by barbenbar** [comment]
How about in this one,
I am able to ping it from the phone but might have had network problems earlier.
Both are on the same wifi but I am uncertain about channels (how would I know).
Thanks!

[debug-lun__oct__9_12_59_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12848627/debug-lun__oct__9_12_59_23_2023.log)

**Comment by cagnulein** [comment]
unfortunately still the same :( for the wifi channel you can check it from the router 

do you have separate wifi names for 2.4 and 5ghz?

**Comment by barbenbar** [comment]
No different wifi names. 
How about this debug log?
I tried to reinstall the app & companion but therés still nothing happening.
[debug-lun__oct__9_15_32_26_2023 2.log](https://github.com/cagnulein/qdomyos-zwift/files/12849869/debug-lun__oct__9_15_32_26_2023.2.log)

**Comment by cagnulein** [comment]
nope, nothing. seems that something is filtering the packages

could you try to enable the tethering from your phone and connect the
treadmill to the wifi tethered from it?

Il giorno lun 9 ott 2023 alle 21:47 barbenbar ***@***.***> ha
scritto:

**Comment by barbenbar** [comment]
I tried with tethering from phone this morning. Looks like nothing is happening. Here are the debug & log from treadmill. 
[2023-10-10_logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/12857977/2023-10-10_logs.txt)
[debug-mar__oct__10_09_42_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12857978/debug-mar__oct__10_09_42_35_2023.log)
[debug-mar__oct__10_09_38_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12857979/debug-mar__oct__10_09_38_31_2023.log)
Thank you so much for your help.

**Comment by cagnulein** [comment]
very strange. I can't see in the log any reference to the QZ companion.
Seems dead? can you try to press the dump log button in the companion and
share a picture of the text box?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 ott 2023 alle ore 15:53 barbenbar ***@***.***>
ha scritto:

**Comment by barbenbar** [comment]
![Uploading IMG_2148.jpeg…]()
There you go

**Comment by barbenbar** [comment]
![IMG_2148](https://github.com/cagnulein/qdomyos-zwift/assets/147414523/ae440b38-e3bd-42fc-b8ed-19d4534b3cb1)
There you go.

**Comment by cagnulein** [comment]
I guess the issue is, in the treadmill logs, there isn't any log about
"changed speed" or "changed watt". So the companion is not reading nothing
at all.
are you able to run a

adb logcat -f | grep "Changed"

and try to start the treadmill and change speed? We should see the logs
about the speed changing.


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 ott 2023 alle ore 16:01 barbenbar ***@***.***>
ha scritto:

**Comment by barbenbar** [comment]
I can run a logcat on the device but I get no grep results for "Changed" / I do get pleny of data without 'grep'.
Here is an example of loagcat while treadmill is running.

[adb logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/12860077/adb.logcat.txt)

**Comment by cagnulein** [comment]
@victorypoint do you have any hints? This device seems completely locked

what do you think?

**Comment by barbenbar** [comment]
Here is another logcat, hope it helps. Thanks!
[adb logcat 2.txt](https://github.com/cagnulein/qdomyos-zwift/files/12860255/adb.logcat.2.txt)

**Comment by barbenbar** [comment]
Reverted Ifit admin (on treadmill) to factory (uninstall updates).
Also Uninstalled System settings app that had been installed by Ifit Admin. (because why not LOL)
Some grade change & speedchange started to appear in logcat.
[adb logcat 3.txt](https://github.com/cagnulein/qdomyos-zwift/files/12860597/adb.logcat.3.txt)
Still nothing on the app.

**Comment by cagnulein** [comment]
great @barbenbar !

i guess that we need to use this last trick now https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

let me know if it's clear

**Comment by barbenbar** [comment]
OK, I granted the READ_LOGS permission, how do I enable adb debug for companion?

**Comment by cagnulein** [comment]
in the developer setting in the android settings there is a setting to allow adb debug for a single application

**Comment by barbenbar** [comment]
Got locked out of privilege mode, can’t enable it anymore, therefore can’t access android settings. Suppose I’ll try to factory reset again tomorrow and proceed without deleting the IFit system settings app. Thanks for your help today.

**Comment by cagnulein** [comment]
sooner or later we will have to device to continue the usb implementation of qz on these treadmills

**Comment by victorypoint** [comment]
> @victorypoint do you have any hints? This device seems completely locked
> 
> what do you think?

Hi guys. I just got back from a trip and am reading through this now. Let me know if I can help in any way. It definitely looks like speed and incline metrics are not written to the wolflog on this machine. Hoping we can get it working with logcat. @barbenbar, definitely don't disable iFit Admin as it's needed to handle the onscreen taps to access privileged mode.

**Comment by barbenbar** [comment]
Good news!
@victorypoint I figured it's what was locking me out of privilege mode so I did the following:

1. Factory reset. **Only this time I did not enter my wifi information and I did not log into my iFit account.**
2. Enable privilege mode (no code required when not connected to Internet).
3. Enabled USB debug mode in android settings developper options
4. Connect wifi
5. Install QZ companion via a Windows PC
6. Treadmill reboots automatically
7. Grant QZcompanion required access & choose C1750 treadmill option
8. Setup QZ app on phone: Enter IP in Nordictrack 2950 IP field.  (Nordictrack 10 slider is also activated by default)
9. Start a manual workout without logging in to Ifit account > Success on reading all metrics in QZ app. (except fan speed but seriously I do not care)

Is there any good reason not to install a firewall to prevent updates to Ifit & Eru / Ifit admin?

Next I'll try to link up with Zwift which i suppose will be easy & also try to control speed & incline via the QZ app.

Thank you so so much for your help @cagnulein

**Comment by cagnulein** [comment]
wow amazing @barbenbar !

> Is there any good reason not to install a firewall to prevent updates to Ifit & Eru / Ifit admin?

yes it's what I did on my proform bike, I defintely suggest to do the same!

> Next I'll try to link up with Zwift which i suppose will be easy & also try to control speed & incline via the QZ app.

ok let me know!

**Comment by barbenbar** [comment]
It works very well with zwift. 
But I could not get the QZ app to control speed & incline as is.
Is there any additional setting I have to choose? Thanks!

**Comment by cagnulein** [comment]
yes actually with the grand tour pro setting it doesn't control speed and
incline.
are you able to run
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat
and post the results here, so i can try to add the support for this
treadmill as well

Let me know

Il giorno gio 12 ott 2023 alle 00:46 barbenbar ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@barbenbar any news?
