### ISSUE TITLE
[BUG] watts not being displayed 

### ISSUE THREAD

**Issue by iainscross** [cagnulein/qdomyos-zwift#1694]
Hi, The watts are not being displayed within the QZ app. 
I am using a Proform TDF4.
Debug log belowdecks
Many thanks
Iain
[debug-Tue_Oct_10_06_43_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12856155/debug-Tue_Oct_10_06_43_27_2023.log)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi very easy solution, you have the "Disable Wattage from Machinery"
setting enabled. Disable it and the wattage will come back!
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 ott 2023 alle ore 12:50 iainscross <
***@***.***> ha scritto:
