### ISSUE TITLE
[BUG] No data on most of the graphs other than power distribution. Most tiles not receiving data during workout.

### ISSUE THREAD

**Issue by JSMiniatures** [cagnulein/qdomyos-zwift#1695]
**Describe the bug**
No data on most of the graphs other than power distribution.  Most tiles not receiving data during workout.

**To Reproduce**
1. Start qz app on Apple Watch
2. Start qz app on iphone
3. start workout
4. stop qz app on watch
5. stop qz app on phone
6. receive email with workout data

**Expected behavior**
I was told the graphs would show data once the workout was stopped.  

**Screenshots**
![IMG_0030](https://github.com/cagnulein/qdomyos-zwift/assets/18285637/5846e699-a22d-4410-9286-3a104232efea)
Email received from workout earlier today from qz app showing lack of data.
[Tues-10-10-23_workout.pdf](https://github.com/cagnulein/qdomyos-zwift/files/12858905/Tues-10-10-23_workout.pdf)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17
 - Version: 17.0.3

**Append a debug log**

  debug-Tue_Oct_10_16_06_13_2023.log
  
**Additional context**
I did a 1 minute workout to recreate the problem.

**Comment by JSMiniatures** [comment]
I think the log didn't upload properly.  

[debug-Tue_Oct_10_16_06_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12858932/debug-Tue_Oct_10_16_06_13_2023.log)

**Comment by cagnulein** [comment]
checked. Your bike is sending only power and cadence.
Enable the ""Speed calculates on Power"" setting in qz to have also speed and distance and most of the other metrics

Let me know

**Comment by JSMiniatures** [comment]
Thanks will test that soon.

**Comment by JSMiniatures** [comment]
Okay, that seems to be fixed now.  Thank you.

**Comment by cagnulein** [comment]
glad to hear it!
