### ISSUE TITLE
[BUG] Dropped Speed Sometimes & No Cadence in Domyos Treadmill => Qz => Garmin Watch

### ISSUE THREAD

**Issue by hakun** [cagnulein/qdomyos-zwift#1699]
**Describe the bug**
Equipment:
Domyos intense run treadmill
Garmin watch Enduro 2
Qz app beta version on android with Ant+ Dongle
Issue:
(1) N/A pace/speed sometimes show on Qz App at around km 4.5 (happened two times at same km so far), there is no pace/speed on Garmin data screen, Garmin chart as well, odo start to different from treadmill from dropped speed timing
(2) Cadence is overwritten (no data on watch, there was if no qz sensor)

**To Reproduce**
1. Setup Domyos Treadmill => Qz App => Garmin Watch
2. Start run on Domyos
3. Issue: N/A sometimes shown on Qz App, no speed on Watch as well

**Expected behavior**
No dropped pace/speed.
Keep cadence of Garmin watch.

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/5cd37523-261e-4d6f-aeb4-179f92a0d613)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/33619b30-6a91-4654-9ba1-050666401c97)

Equipment:
 - Mobile: Galaxy A10 SM-A105G/DS, android 11
 - Qz: 2.16.15

**Append a debug log**
https://drive.google.com/file/d/1zZPXamAq0AEeeEy1QpBEGns27eNbj6pw/view?usp=drivesdk
  
  
**Additional context**
Ask me if any

**Comment by cagnulein** [comment]
Log checked: I already saw this issue from another user. The treadmill is sending pace 0 when it happens, so it's not QZ fault. On the other user, he tested also the same treaadmill with the domyos app and he had the same issue. It was an issue on the control board of the treadmill.
I suggest to try the domyos app as well
Let me know

**Comment by cagnulein** [comment]
try to do the same session with same speed and inclination. The other user doesn't have issue with 10km/h but have issue with 12km/h for example.

**Comment by cagnulein** [comment]
that's the ticket of the other user https://github.com/cagnulein/qdomyos-zwift/issues/1567

**Comment by cagnulein** [comment]
Ok keep me informed.

**Comment by hakun** [comment]
I have never saw Doymos sw updatw is possible anywhere. Means that thía Domyos issue will stay forever 🥲

**Comment by hakun** [comment]
Or equip it a fan 😄

**Comment by hakun** [comment]
Mine is still under warranty. Seems good to claim so.

**Comment by cagnulein** [comment]
> Mine is still under warranty. Seems good to claim so.

yes if you can demonstrate to them that it's happening with the domyos app, they have to replace it for sure!

**Comment by hakun** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/e0c62cbf-bd62-4941-8eeb-bb12c6bc3094)

Could not reproduce for now ...

**Comment by cagnulein** [comment]
are you running on it? or is just the treadmill without you?

Il giorno mer 11 ott 2023 alle 18:22 hakun ***@***.***> ha
scritto:

**Comment by hakun** [comment]
Just treadmill, I dont run on it. Should I run to make heat?

**Comment by cagnulein** [comment]
yes exactly

Il giorno mer 11 ott 2023 alle 19:07 hakun ***@***.***> ha
scritto:

**Comment by hakun** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/013b3c84-e132-4bf5-a5e8-f32c416f8a4f)

Tried again with actual run on treadmil. It happens at same km as well, around 4.6. Quite strang if it's hw issue then why it can happen at same km. I guess that it's problem of sw on board, they cannot update it OTA, then need to replace.

**Comment by cagnulein** [comment]
Good news that you can replicate it. Please let me know what they will told
you and also share the link of this ticket with them, they know me.

Il gio 12 ott 2023, 18:07 hakun ***@***.***> ha scritto:

**Comment by hakun** [comment]
Haha, really. Ok, I've contacted local Decathlon already. Let see what is their feedback.

**Comment by cagnulein** [comment]
@hakun any news?

**Comment by Smirnoff77** [comment]
Hi!
I have the same issue with Intense Run. After 20-25min at 9 km/h it drops speed and incline to 0. It really may be an overheating problem - should I install a fan? :D The warranty has already expired...

**Comment by cagnulein** [comment]
@Smirnoff77 for @hakun the issue was the treadmill itself. So yes it could be a overheated issue.
