### ISSUE TITLE
[BUG] Bluetooth stops broadcasting on raspberry pi after a long time

### ISSUE THREAD

**Issue by chreds** [cagnulein/qdomyos-zwift#1702]
I have a raspberrypi always on with qz running. If I leave the bike for a day and come back, the qz app is still connected to the bike and I see it updating with new watt values when I pedal, etc., but the qz app is no longer broadcasting a btle device for rough/zwift to see. Rebooting device brings btle back up.

Any ideas? Is this expected? Should I just schedule a regular reboot? I'll try to get more debug info before you spend much time on this.

Next time it's not working I can ssh to the pi. Any output you'd want me to get specifically other than debug logs?

**Append a debug log**
Will post regular log tomorrow. Will need to reproduce over another day or 2 to post debug.

**Comment by cagnulein** [comment]
i need a debug log to check it. maybe some daily task on the raspberry
restarts the bluetooth or so

Il giorno gio 12 ott 2023 alle 06:18 chreds ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@chreds any news?
