### ISSUE TITLE
Watts not working on Proform TDF4

### ISSUE THREAD

**Issue by iainscross** [cagnulein/qdomyos-zwift#1703]
Hi, I have disabled wattage from machinery but I am still not getting the watts displayed in the app.
[debug-Thu_Oct_12_07_14_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12877842/debug-Thu_Oct_12_07_14_01_2023.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
please don't open a new ticket, use the one for the same issue.
the problem is also that you set power sensor as wifi and enabled the power sensor as a bike. disabled both. let me know
#1694

**Comment by iainscross** [comment]
Hi, This worked a treat. Thanks very much

**Comment by cagnulein** [comment]
great!
