### ISSUE TITLE
[BUG] Garmin Cadence Sensor not sending data

### ISSUE THREAD

**Issue by rexbarrett** [cagnulein/qdomyos-zwift#1704]
**Describe the bug**
Cadence sensor is connected. QZ sees it. When crank spins there is no data coming through. All tiles are at 0.0.

**To Reproduce**
1. Start app
2. Connect Garmin Cadence sensor
3. Set cadence sensor as bike
4. Start moving
5. No data

**Expected behavior**
I expect the tiles to register cadence and speed.

**Screenshots**
On FB

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS
 - Version 17.0.3

**Append a debug log**
https://app.sparkmailapp.com/web-share/ymQtvjxZq_x3u38cy91uM1ofU-K7N_SB0icz01ve

**Comment by cagnulein** [comment]
thanks i will try to check this later today

Il giorno ven 13 ott 2023 alle 15:11 rexbarrett ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@rexbarrett can you try to disable the virtual bluetooth device setting in the experimental settings and restart QZ. Only this one, don't touch any other settings. Thanks

**Comment by rexbarrett** [comment]
Still same problem.

**Comment by cagnulein** [comment]
@rexbarrett could you please attach the blog in this scenario now? I would like to see if something has changed now. Thanks.

**Comment by rexbarrett** [comment]
You are done supporting your app with me?

**Comment by cagnulein** [comment]
nope i'm waiting a fresh log in this scenario

**Comment by rexbarrett** [comment]
I thought it came through already! It looks like it didn't send last week. Sorry!

https://www.dropbox.com/scl/fi/kel37p9ku8iq9d5fweqnu/debug-Fri_Oct_13_10_58_43_2023.log?rlkey=mkef6w40l7ovcwhq8gd82kr0d&dl=0

**Comment by cagnulein** [comment]
thanks, i'll check it tomorrow!

Il giorno lun 16 ott 2023 alle 19:23 rexbarrett ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@rexbarrett ok I guess I understood it. This sensor has a no-standard behaviour. I did a patch and I will send you a new beta version later today/tomorrow. If it doesn't work I have another idea in case.
let me know when you will receive it.

**Comment by cagnulein** [comment]
@rexbarrett could you please
send me an email to roberto.viola83 at gmail.com indicating this ticket so I will send you the new beta. Thanks

**Comment by rexbarrett** [comment]
Will do, thanks.

**Comment by rexbarrett** [comment]
Didn’t work. I’m bummed!

https://app.sparkmailapp.com/web-share/kgpxajB46Q5rRIS5AETa6QRRWqQxg0JTzmZhPe_s

**Comment by cagnulein** [comment]
ok i will do another patch later today or tomorrow, thanks, we will got it,
be sure!

Il giorno mer 18 ott 2023 alle 05:30 rexbarrett ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@rexbarrett new version sent! let me know, I did several lines of patches so since I can't test this on my own post me again the log if it still doesn't work
Thanks

**Comment by cagnulein** [comment]
hi @rexbarrett did you check it?

**Comment by rexbarrett** [comment]
Still not working.
https://app.sparkmailapp.com/web-share/Q2xxjg7j2O9kiAtS6vB0cOOc5RE59Gm1pPdO6gB4

**Comment by cagnulein** [comment]
@rexbarrett checked the log and at this point I have to make a question :) does this sensor work via bluetooth with any other app?

**Comment by rexbarrett** [comment]
Just checked Tacx App (Garmin’s own app) and it does work. Checked Zwift directly and no. So at this point I’m ready to send the sensor back to Amazon. Is there a brand you recommend for me?

THANK YOU for the time you spent.

**Comment by cagnulein** [comment]
hah what a relief! it was driving me crazy! probably it's a non standard device, what a shame for garmin!
Actually I don't have one to recommend, but just buy a non garmin one and it should work!
Let me know
