### ISSUE TITLE
[BUG] Proform TDF CSC not communicating with QZ

### ISSUE THREAD

**Issue by Spokesandsparks** [cagnulein/qdomyos-zwift#1706]
**Describe the bug**
[BUG] Preform TDF CSC not communicating with QZ

**To Reproduce**
No data shared when I cycle

**Expected behavior**
Data should be shared to the QZ app from the bike

**Screenshots**
![IMG_8304](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/267fb6b6-ec79-4396-ab44-21513bb9f293)
![IMG_DD01713F79EC-1](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/e8b6c0a0-f191-43a6-a2d0-c4c4ef82d048)

**Smartphone (please complete the following information):**
 - Device: iPhone15
 - OS: 17
 - Version .03

**Append a debug log**
[debug-Sun_Oct_15_10_14_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12909125/debug-Sun_Oct_15_10_14_31_2023.log)
[debug-Sun_Oct_15_10_14_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12909127/debug-Sun_Oct_15_10_14_31_2023.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
checked the log: could you try to set the c1750 device on the companion and
restart the fitness device?
let me know and in case post a fresh debug log

let me know

Il giorno dom 15 ott 2023 alle 11:27 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Hi Roberto,

Please see attached report. Using the new setting did transfer some data
which is progress!

**Comment by Spokesandsparks** [comment]
Apologies, here you go 
![IMG_8417](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/d3df6762-e2bd-4317-be0a-671057eff7bf)
[Uploading debug-Tue_Oct_17_16_46_30_2023.log…]()

**Comment by cagnulein** [comment]
hi unfortunately you pressed send too soon, it was uploading the file. could you please upload it again?

**Comment by Spokesandsparks** [comment]
[debug-Tue_Oct_17_16_46_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12938116/debug-Tue_Oct_17_16_46_30_2023.log)

**Comment by cagnulein** [comment]
perfect! Just enable now the speed based on power setting in the bike section in the QZ settings and you're ready to go!
Let me know!

**Comment by Spokesandsparks** [comment]
Brill thanks for all your help!

**Comment by cagnulein** [comment]
I'm closing this one, feel free to open it again if you have any issues!

**Comment by Spokesandsparks** [comment]
Hi,

I’m afraid that this has completely stopped communication. 
[debug-Sat_Oct_28_11_14_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195485/debug-Sat_Oct_28_11_14_06_2023.log)
[debug-Sat_Oct_28_11_16_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195486/debug-Sat_Oct_28_11_16_20_2023.log)

**Comment by Spokesandsparks** [comment]
[debug-Sat_Oct_28_12_13_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195583/debug-Sat_Oct_28_12_13_40_2023.log)

**Comment by Spokesandsparks** [comment]
[Uploading debug-Sat_Oct_28_12_33_56_2023.log…]()

**Comment by cagnulein** [comment]
@Spokesandsparks log corrupted, you need to wait the upload before pushing comment

**Comment by Spokesandsparks** [comment]
[debug-Sat_Oct_28_12_33_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195665/debug-Sat_Oct_28_12_33_56_2023.log)

**Comment by Spokesandsparks** [comment]
I thought I had

**Comment by cagnulein** [comment]
ok follow this https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by Spokesandsparks** [comment]
Thanks can you tell me how to do this from terminal on mac

**Comment by cagnulein** [comment]
i'm riding now, i will do later today. you just need to install adb for mac

Il giorno sab 28 ott 2023 alle 14:05 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Thanks will install

**Comment by Spokesandsparks** [comment]
Did you get chance to look at this?

**Comment by cagnulein** [comment]
did you install adb on mac? 10pm here :)

**Comment by Spokesandsparks** [comment]
i did but there but you do know there is no USB port on my bike right?

**Comment by cagnulein** [comment]
Adb will use wifi. Did you enable adb on your bike?

Il giorno dom 29 ott 2023 alle 09:22 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Yes

**Comment by cagnulein** [comment]
Perfect, so did you run the command that I sent you in the link? Did it
give you an error?

Il giorno dom 29 ott 2023 alle 09:40 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
all i get is adb: no devices/emulators found

**Comment by Spokesandsparks** [comment]
when i try to connect directly to the IP I get 'connection refused'

**Comment by cagnulein** [comment]
99% is because ifit closed the adb port to protect themselves from qz.
You have to fully reset your bike and don't allow ifit to update it

Unfortunately ifit is trying to keep all the users with them so we have to fight them

**Comment by Spokesandsparks** [comment]
Ive just tried again and the error is now failed to authenticate

**Comment by cagnulein** [comment]
adb doesn't have authentication
You have to reset it as I said, trust me

Il giorno dom 29 ott 2023 alle 10:34 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
ok buddy thanks

**Comment by Spokesandsparks** [comment]
any ideas how i stop ifit from updating? It will not continue the setup without connecting to wifi. I can get to privilege mode so I have altered the settings to prevent auto system update. However, there is plenty of chat online that this doesn't work. Some people mention a modified Ifit version?

**Comment by cagnulein** [comment]
Can't you disable internet access to your bike from your router?

Or simply connect it to an access point without internet access

Il giorno dom 29 ott 2023 alle 10:51 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Yes I could but then my wife wouldn't be able to use Ifit

**Comment by cagnulein** [comment]
As far as I know, once you granted the adb permission, you will be ok
forever (as I read from other users here)

Il giorno dom 29 ott 2023 alle 11:01 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
ah ok thanks

**Comment by Spokesandsparks** [comment]
I may have done it:

 % adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
surgeseo@Surges-Air ~ %

**Comment by Spokesandsparks** [comment]
![Image 29-10-2023 at 10 46](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/e41dd42f-df8c-4ebc-a4f2-f5aaa3616e0a)

**Comment by cagnulein** [comment]
Yes seem so, follow the other steps then

Il giorno dom 29 ott 2023 alle 11:46 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
I cannot locate the setting to enable adb debugging? Once I have done that I am free to restart the bike and allow it to update as it would? I should be good to go?

**Comment by cagnulein** [comment]
Adb debugging should be already enabled, but search it , it's in the
developer settings (I don't have a Nordic track bike so I can't show you a
screenshot)
Yes you should be free to reboot the bike.
I don't know about the update. Let's do a step by step

Il giorno dom 29 ott 2023 alle 12:03 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
I searched for adb debug and the only thing that comes up is Usb debug and that was already enabled. The bike restarted and I signed in, it gave me the option to update which I declined. Still nothing transmitting to the iPad though. Do I leave the companion setting on grand tour or do I need to change it?

**Comment by cagnulein** [comment]
You have to set it to gran Tour on companion. Did you?

Il giorno dom 29 ott 2023 alle 12:21 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
yes

**Comment by cagnulein** [comment]
Run from your Mac while you are doing a manual workout on your bike

adb logcat -f > output.txt

And share the output file here

Il giorno dom 29 ott 2023 alle 12:28 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
entered the command.. it just says waiting for device. Nothing happens. I was riding at the time

**Comment by cagnulein** [comment]
So maybe adb is not working anymore?

You have to collect an adb logcat while you are riding otherwise I cannot
understand what's the issue.

now I'm starting my riding session. I will be back in a couple of hours.

If you want, you can search here the other users that did this, maybe they
can help you since they have a similar tablet

Il giorno dom 29 ott 2023 alle 12:37 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Debug had turned itself off. I managed to get the output file but it was empty even though I was riding when I sent the command. Will try again

**Comment by cagnulein** [comment]
Try to run only

adb logcat -f

You should see the error in case

I hope it will help

Il giorno dom 29 ott 2023 alle 13:59 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
stuck on waiting for device... debug seems to turn off whenever I start ifit

**Comment by Spokesandsparks** [comment]
i can only get a response from the machine to my mac while i am in the android backend

**Comment by cagnulein** [comment]
Try to enable it back or restart the tablet. Others found a way to do so,
@victorypoint any help on this? Thanks

Il giorno dom 29 ott 2023 alle 14:18 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
I managed to connect it again using adb connect and IP but again the output file was empty. I used the adb logcat -f which seemed to work but didn't create an output file. How do I get the report for you?

**Comment by Spokesandsparks** [comment]
I think i may have got the report but I'm not sure, see attached. 
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13198279/logcat.txt)

**Comment by Spokesandsparks** [comment]
Qz seems to be working now and I’m getting data from the bike. When I connect to Zwift there is nothing coming up for the power source or cadence 
![12B80E63-FC98-4B1A-9ED8-7BDC5D202C09](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/4b11d277-c2e2-496e-b8fd-958b77a5c8f7)
![3A27CBDF-1190-48BD-AA50-0B916EA7ACDC](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/6dcb972f-e490-4183-8703-aec73b9495d5)
![9472540F-8D7B-4611-BA43-A19D60A36356](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/be2b9937-a1fe-4aff-bed2-681b4ef38977)

**Comment by Spokesandsparks** [comment]
![D3F0B4F7-2F2A-4C1F-B315-346D2C5AE0B2](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/d429c860-9d98-47bd-bf96-8c6b62c6f1ab)
![1A5229E8-B6B5-4301-A499-56226C8EBB3B](https://github.com/cagnulein/qdomyos-zwift/assets/147975887/2ecc0b38-31bd-4aba-90ac-440e5564f614)

**Comment by cagnulein** [comment]
Great! What you did in order to get it?
Did you already unpair it from zwift and pair it again? Its a simple cache
issue on zwift now

Il giorno dom 29 ott 2023 alle 15:28 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
I have no idea what I did but hey Ho, thanks for your support 👍

**Comment by Spokesandsparks** [comment]
Any ideas why the HR would not transfer from AW. I have agreed all permissions in AW app, pressed start but nothing. I have checked the heart strap setting in qz is disabled

**Comment by cagnulein** [comment]
Try to restart both aw and phone. It could happen
Let me know

Il giorno dom 29 ott 2023 alle 17:28 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Will do 👍
