### ISSUE TITLE
[BUG] echelon connect - speed & cadence not showing

### ISSUE THREAD

**Issue by Rbrenchak1** [cagnulein/qdomyos-zwift#1709]
![Thu Sep 28 23_14_30 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/148140988/44324764-ee17-4369-99f8-b8f57fe59976)
[debug-Mon_Oct_16_14_21_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12920704/debug-Mon_Oct_16_14_21_15_2023.log)
[debug-Mon_Oct_16_14_21_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12920712/debug-Mon_Oct_16_14_21_15_2023.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Rbrenchak1 are we ok with this?

**Comment by Rbrenchak1** [comment]
Yes!  Thank you!  Works great!
