### ISSUE TITLE
[BUG] Joroto MR280 Rower - Unable to connect

### ISSUE THREAD

**Issue by scottmoser-dot-io** [cagnulein/qdomyos-zwift#1710]
**Describe the bug**
I have a Joroto MR280 and I confirmed that it does in fact support FTMS but I'm unable to get it to connect to the Qz app. I've used it with Kinomap numerous times and it connects without issue. I have tried to manually select it through the FTMS rower setting but I haven't had any luck. 

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 17.0.3
 - Version: 21A360

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
Hi! What was the issue?

Il giorno mar 17 ott 2023 alle 00:23 Scott Henderson <
***@***.***> ha scritto:
