### ISSUE TITLE
[BUG] Can't get to connect Garmin Forerunner 255s HR to QZ app

### ISSUE THREAD

**Issue by BobbyFerdi** [cagnulein/qdomyos-zwift#1711]
**Describe the bug**
Heart rate from Garmin Forerunner 255s won't show up on QZ app

**To Reproduce**
1. Attach USB dongle to my Samsung A52 phone
2. Start QZ app on the phone
3. Start pedalling my Yesoul S3 bike
4. The other stats shows up, except for the HR from my watch

**Expected behavior**
The heart rate shows up on the app

**Screenshots**
![WhatsApp Image 2023-10-17 at 13 10 01_dd366a61](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/7945ffe2-ab69-4097-a29d-bb657e597e9a)
![WhatsApp Image 2023-10-17 at 13 10 02_f856b65a](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/2eb27ee9-15e4-43fc-bf5d-c10e09465708)
![WhatsApp Image 2023-10-17 at 13 10 01_ac7406ab](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/e26ddf82-6763-4bc5-802f-199f6957d7a1)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52
 - OS: Android 13

**Watch**
- Device: Garmin Forerunner 255s
- OS version: 16.19

**Bike**
- Device: Yesoul S3

**Append a debug log**

[debug-Tue_Oct_17_13_04_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12924941/debug-Tue_Oct_17_13_04_04_2023.log)

I also have installed QZ companion app and tried running it, but still no sign of any HR recorded. Please advice on what steps needed to be taken to connect the HR from my watch to QZ app. Thank you

**Comment by cagnulein** [comment]
hi @BobbyFerdi thanks for the detailed feedback!
Join the beta from the play store page, the issue is already been fixed!
Let me know then!
R.

**Comment by BobbyFerdi** [comment]
wows, what a prompt response @cagnulein ! 😄 

I will try the beta and get back to this issue then

**Comment by BobbyFerdi** [comment]
Sadly, I still can't get the HR reading from my watch.

![WhatsApp Image 2023-10-17 at 15 30 51_88c7d71a](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/2b5d29f3-1b94-47c8-9e02-3858a543c161)

Just curious, does the blue zero on the HR section above give sign of anything?

I have enabled both Ant+ Heart  and enable companion app settings, but still nothing

![WhatsApp Image 2023-10-17 at 15 31 59_880078e1](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/a2619dec-944e-4179-9ecc-afa6f2a54921)
![WhatsApp Image 2023-10-17 at 15 32 00_144e748a](https://github.com/cagnulein/qdomyos-zwift/assets/22292065/57c37309-dc9a-4184-ac82-5234265a2982)

Is there anything I should do?

**Comment by cagnulein** [comment]
> Just curious, does the blue zero on the HR section above give sign of anything?

nope

> Is there anything I should do?

yes you have to disable ant heart, otherwise qz is trying to get HR from the ANT+ instead of using the companion app.

Let me know

**Comment by BobbyFerdi** [comment]
Yay, it works now. thank you @cagnulein 

I'm closing this issue now

**Comment by cagnulein** [comment]
amazing!
