### ISSUE TITLE
[BUG] Proform RL Rower - A 5 minutes countdown starts rower side when using QZ

### ISSUE THREAD

**Issue by jscti** [cagnulein/qdomyos-zwift#1713]
**Describe the bug**
When using QZ and starting a basic "rowing session", as soon as I start rowing, the "0:00" timer on the rower becomes a countdown timer starting at "5:00".
QZ side, the "elapsed time" show the correct value, and I would like the same value rower side

Activated option: 
- Proform RL Rower
- Virtual Rower (tried on/off)

**To Reproduce**
- start rower. Elapsed time shows as "0:00". Don't start rowing yet.
- start QZ
- start rowing (rower quit "paused mode" to "rowing mode")
- Rower elapsed time shows 5:00 and start going backward (countdown)

**Expected behavior**
Let rower count time normally/forward from 0:00.

**Smartphone (please complete the following information):**
 - Pixel 6 
 - OS: Android 14 (bug occured also on android 13)

**Append a debug log**
[debug-Wed_Oct_18_17_34_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13030728/debug-Wed_Oct_18_17_34_27_2023.log)

Thanks :)

**Comment by cagnulein** [comment]
#1643

**Comment by cagnulein** [comment]
@brupec are you still using QZ? do you see the same behaviour?

**Comment by brupec** [comment]
> @brupec are you still using QZ? do you see the same behaviour?

Hi Roberto, sorry was quite busy this week and forgot to answer you. I'll check today

**Comment by brupec** [comment]
Indeed I have same behavior as mentionned by jscti

**Comment by brupec** [comment]
I need to do it in the official app from proform right? I think I did
manual training in the latest I sent you

Le mar. 24 oct. 2023, 15:00, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
> I need to do it in the official app from proform right?

yes

> I think I did manual training in the latest I sent you

maybe didn't check about the countdown?

**Comment by brupec** [comment]
> > I need to do it in the official app from proform right?
> 
> yes
> 
> > I think I did manual training in the latest I sent you
> 
> maybe didn't check about the countdown?

the problem is I did the try with the trial of the app and it's finished, I have no access anymore. maybe OP didn't do his trial and could do the HCI ?

**Comment by cagnulein** [comment]
@jscti can you help?
@brupec maybe you can create another fake account with another email account?

**Comment by jscti** [comment]
Trial also ended but there is  a "free manual workout" mode working without any subscription

**Comment by jscti** [comment]
How can I help ? I didn't follow the "hci snoof" stuff and willing to try ^^

**Comment by cagnulein** [comment]
@jscti this way https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by jscti** [comment]
Ok it should be this : [btsnooz_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13188917/btsnooz_hci.log)

I did (while bt spoof was active) : 
- start rowing (rower powered on)
- paused rowing (rower then auto paused timer)
- change resistance to 3
- re-started rowing
- paused rowing

**Comment by cagnulein** [comment]
argh @jscti unfortunately this android device seems to truncate the messages :( it happens with some chinese phones. which phone is it? do you have another one?

**Comment by jscti** [comment]
Oh that's a Google Pixel 6 -_-
I don't have any other device :/

**Comment by cagnulein** [comment]
that's strange, I have a pixel 7 and it's not doing this...is the default rom?

**Comment by jscti** [comment]
Yeah full stock, nothing special.
Is it better ? : 
[btsnooz_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13229722/btsnooz_hci.log)

If not @brupec could you try a "Manual workout" in the ifit app ? (the button is at the bottom of the "rower" screen) :  
![image](https://github.com/cagnulein/qdomyos-zwift/assets/1594035/8a0841ed-75d1-4710-bb10-61f5508aec1f)

**Comment by brupec** [comment]
Hi, sorry I went to live in Spain for some month and left rower back
home... Good luck guys, if still need when I come back I'll try

**Comment by jscti** [comment]
Hi there.

I found a device where the frames are not truncated.

Here is the logs : 
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13404604/btsnoop_hci.log)

What I did with IFIT app :  
- warmup with a 3 minutes countdown. I stoped warmup after 30s of rowing
- practice starting with a standard timer starting at 00"00'. Rowed 30s
- stopped practice/session

Hope that helps

**Comment by cagnulein** [comment]
perfect @jscti I will create a branch for you to test this out! I will let you know when I will be ready (hopefully today!)

**Comment by cagnulein** [comment]
done @jscti download this https://github.com/cagnulein/qdomyos-zwift/suites/18332912934/artifacts/1060853568 and let me know if it's any better!

**Comment by cagnulein** [comment]
argh, thanks, i will check again the log in order to check if there are other differences

**Comment by cagnulein** [comment]
@jscti are you seeing the 5 min countdown as soon as qz is connected? or some seconds after?

**Comment by jscti** [comment]
Well, i tried many things :
 
- Rower is turned off & QZ app is closed
- I start QZ, it is not connected to the rower
- Say, like 10 seconds after : I start the rower by rowing (only once just to power it on but rower is still in PAUSED mode)
- here the "elapsed time" on the rower shows a static stopwatch at 0"00'
- I start rowing, rower detect it and UNPAUSE itself
- On the "time elapsed" screen on the rower: countdown from 5"00'

Same scenario without QZ, the last step becomes  :
- I go to the "time elapsed" screen on the rower: stopwatch from 0"00'

I also got a weird behavior when I stoped the session from QZ : 
- Rower doesn't detect me rowing and all data (on rower and QZ) are at 0, nothing moves while I row
- As soon as I force-close QZ, rower detects activity and "un-pause" / start showing data
- If I re-open QZ  : rower is still blocked
- If I poweroff & on rower (even unplugging from the wall) : rower is still blocked when QZ is open
- Only way to going back to normal : disable/enable bluetooth

Lastly (not related to my issue), the "stop" button doesn't seem to reset the data from the main screen (when we come back to the main screen after closing the session graphs). Only when clickgin "start" the data resets.

**Comment by cagnulein** [comment]
ok thanks, i will check again the log. Last thing: in ifit instead what do you see? i mean you start the ifit app, it connects and the time elasped how it behaves?

**Comment by jscti** [comment]
All my tests from today are without using IFIT app.
Just basic training directly on the rower without anything except QZ

**Comment by cagnulein** [comment]
yeah i was meaning about the ifit session that you collect with the hci snoof. How it behaves?

**Comment by jscti** [comment]
Whe I recorded the HCI log the timer shown in the app and the one on the Rower were totally in sync (stopwatch from 0"00') without any second difference.
QZ was not active during the HCI log

**Comment by cagnulein** [comment]
ok, that's strange, should be same now. Ok thanks for the details, I will check the log again

**Comment by cagnulein** [comment]
interesting, note for me: i found a Value: fe022003 packet that could be a
start packet
did you press a start button in the ifit app when you collect the hci
snoof? I guess so (this packet is after 20 seconds from the connection with
the rower)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 nov 2023 alle ore 16:28 jscti ***@***.***>
ha scritto:

**Comment by jscti** [comment]
During the collect, I started a workout where the IFIT app control the rower so I think the app itself may have send a "forced start" once I started the training from the app (without even rowing myself yet) yeah

**Comment by cagnulein** [comment]
confirmed, it's the start. let me try to implement this! i will send the start when you connect to qz, do you agree? or do you want to add it to the start button of qz?

**Comment by jscti** [comment]
Well I don't know at all.

Things to consider :  

- I may start rower before QZ, or QZ before rower
- I will be auto-paused by the rower If I stop rowing a few seconds

But this "start thing" only fixes the second "weird behevior" found today here https://github.com/cagnulein/qdomyos-zwift/issues/1713#issuecomment-1821108822 ? The 5minute countdown is not related ?

**Comment by cagnulein** [comment]
this start thing should fix the 5 minute countdown. i'm doing it right now, i will put it in the connection phase

**Comment by cagnulein** [comment]
it's building https://github.com/cagnulein/qdomyos-zwift/actions/runs/6946442999
Let me know when you will try!

**Comment by jscti** [comment]
Well I'm lost ^^ 

Tried a lot of things, and got totally different results each time.
At first: same bug, countdown starts from 5'00"
Then tried /stop/play/pause from app : Still a countdown but this time from 4"00'
Then bug not reproducted and timer starts at 0"00' yipiii
Until rower is totally blocked (no response when rowing).

It's like the  "start packet" is more like a "lock packet". Before QZ never did "start" the timer/countdown of the rower.

Rower side, the "start" only trigger when I start rowing or does not trigger at all when QS is active (and bugged)

Seems really complicated to debug to me :/

**Comment by cagnulein** [comment]
if you agree i will continue the analysis tomorrow. unfortunately only you
can test this, i can only see the log :)

Il giorno mar 21 nov 2023 alle 17:49 jscti ***@***.***> ha
scritto:
