### ISSUE TITLE
[BUG] QZ can't control speed/incline of NordicTrack X32i

### ISSUE THREAD

**Issue by arthur-ryoo** [cagnulein/qdomyos-zwift#1716]
**Describe the bug**
QZ doesn't control the speed/incline of NordicTrack X32i when touching the + or - icon in the speed and incline tile. The value in the tile doesn't get updated either.

**To Reproduce**
1. Start Manual Workout using iFit
2. Start QZ
3. Increase/decrease the speed or incline value in QZ

**Expected behavior**
QZ should be able to control the speed/incline of NordicTrack X32i.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.6.1
 - Version: 20G81

**Append a debug log**
[debug-Wed-Oct-18-23-21-45-2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13039047/debug-Wed-Oct-18-23-21-45-2023.log)
  
**Additional context**
When increasing/decreasing the speed or incline multiple times in QZ, NordicTrack X32i responds as if a person touched the screen. Ex) It shows the options to pause the workout or to start the cooldown

**Comment by cagnulein** [comment]
> When increasing/decreasing the speed or incline multiple times in QZ, NordicTrack X32i responds as if a person touched the screen. Ex) It shows the options to pause the workout or to start the cooldown

perfect! this means that I just need to remap the touchscreen of your treadmill! Could you please take a picture of the manual workout interface of your treadmill using this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/3.3.6/InstallPackage/adb-screenshot.bat ?

Let me know!

**Comment by arthur-ryoo** [comment]
@cagnulein Here is the screenshot.

![Thu10-19-2023@0-38-24 66](https://github.com/cagnulein/qdomyos-zwift/assets/51396212/c267f0e8-06a6-441a-ada5-d568b2f498c3)

**Comment by cagnulein** [comment]
@arthur-ryoo perfect!
did you already select the x32i device in the companion?
the device should be already handled by this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/29
@Kodanen are you still using it?

**Comment by cagnulein** [comment]
ok indeed the coordinates are different from the @kodanen one

could I ask you the ifit version so i will add it as a label in the setting that I'm creating for your case

**Comment by arthur-ryoo** [comment]
The iFit app version is 2.6.86.4458. I'm not sure if it matters, but the model number is NTL39019

**Comment by cagnulein** [comment]
ok the other one was X32i ETNT39221-INT.0 in EU so maybe it's why is different. I will do the mod and I will update you!

**Comment by cagnulein** [comment]
@arthur-ryoo last question: when you tried to change the speed or inclination from QZ you were on the manual window on the tablet, right?

**Comment by cagnulein** [comment]
@arthur-ryoo release ready https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.3.7
be sure to change the device in the companion to the right one ;)

**Comment by arthur-ryoo** [comment]
@cagnulein Thanks! I've installed the new one and tested it. It seems the inclination part is still not working as expected.

My inclination step value in QZ is 0.5. The + icon in the inclination tile doesn't work at all. The - icon works, but the value gets decreased like -1.0 -> -3.0 -> -6.0 (This is the max negative value X32i can handle)

**Comment by cagnulein** [comment]
the speed one instead?

Il giorno gio 19 ott 2023 alle 19:00 Arthur Ryoo ***@***.***>
ha scritto:

**Comment by arthur-ryoo** [comment]
What do you mean? The speed part works fine

**Comment by cagnulein** [comment]
i mean with the last companion, the incline has that issue but instead the speed control is working ok?

**Comment by arthur-ryoo** [comment]
@cagnulein 
With 3.3.6

- The speed control using QZ didn't work
- The incline control using QZ didn't work

With 3.3.7

- The speed control using QZ works fine
- The incline control using QZ partially works
    - The + icon in the inclination tile doesn't work
    - The - icon works, but the value gets decreased like -1.0 -> -3.0 -> -6.0 when the inclination step value is set to 0.5

**Comment by cagnulein** [comment]
ok perfect! so i just need to trim the incline scale! i will update you ASAP

Il giorno ven 20 ott 2023 alle 06:42 Arthur Ryoo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@arthur-ryoo in order to set the right calibration it's better to try directly on your treadmill via adb and then, when we found the right offset I can add it to the apk

In order to do so, open a shell on the adb directory and prompt this

adb shell input 74 749 74 761 200

where the 74 numbers are the coordinate X so they are ok for sure, the 200 is the speed of the touch so it's ok for sure. 
the 749 is the start Y coordinate and the 761 is the final Y coordinate.

looking at the screenshot that you sent me should be right to move from 0% to 1% so try and let me know

Thanks!

**Comment by Kodanen** [comment]
> ok indeed the coordinates are different from the @Kodanen one
> 
> could I ask you the ifit version so i will add it as a label in the setting that I'm creating for your case

One of the updates broke this a while back but I have not run much on it during the summer so it did not bother me at the time. Now training is kicking in again and having this working is paramount for the upcoming races 😂

I checked my new coordinates today with iFIT App version 2.6.87.4518 and they are as follows:
Speed = -26,946x + 834,85 ; X = 1847
Incline = -12,297x + 734,07 ; X = 76

I also tested these with "adb shell input swipe 76 734 76 808 200" etc flike you suggested above, or full range. These work perfectly for me.

**Comment by cagnulein** [comment]
@Kodanen thanks

we know have 2 devices for your device

x32i:
x32i_NTL39019:

which one are you using?

**Comment by Kodanen** [comment]
in QZ Companion X32i ENTL39221-INT.0 is the one I have selected now. I updated the companion software today.

**Comment by cagnulein** [comment]
@Kodanen  done https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.12/QZCompanionNordictrackTreadmill.apk

**Comment by Kodanen** [comment]
> @Kodanen done https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.12/QZCompanionNordictrackTreadmill.apk

Tested by replaying yesterday's GPS track from iDevice and works 👍 Thank you again 🫡

**Comment by cagnulein** [comment]
Glad to hear it!

Il giorno dom 5 nov 2023 alle 13:26 Kodanen ***@***.***> ha
scritto:
