### ISSUE TITLE
[BUG]QZ not showing metrics with Proform Smart 10 bike

### ISSUE THREAD

**Issue by TripleSeas** [cagnulein/qdomyos-zwift#1717]
QZ isn’t reading metrics from proform smart power 10 bike during peloton workout. Debug log attached. 

[debug-Fri_Oct_20_17_34_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13058905/debug-Fri_Oct_20_17_34_49_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: IPhone 12
 - OS: 17.1
 - Version 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check this asap

Il giorno sab 21 ott 2023 alle 00:01 TripleSeas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @TripleSeas checked the log and i don't see any messages from the companion indeed. Could you please make a test selecting the C1750 device on the companion and restart the bike? in any case send me another log so I will check it.
Thanks!

**Comment by TripleSeas** [comment]
I have some pics of some other logs. Will do that too. Sent from my iPhoneOn Oct 21, 2023, at 7:58 AM, Roberto Viola ***@***.***> wrote:﻿
hi @TripleSeas checked the log and i don't see any messages from the companion indeed. Could you please make a test selecting the C1750 device on the companion and restart the bike? in any case send me another log so I will check it.
Thanks!

**Comment by TripleSeas** [comment]
Proform Smart Power 10dropbox.comSent from my iPhoneOn Oct 21, 2023, at 8:09 AM, Walter Carmichael ***@***.***> wrote:﻿I have some pics of some other logs. Will do that too. Sent from my iPhoneOn Oct 21, 2023, at 7:58 AM, Roberto Viola ***@***.***> wrote:﻿
hi @TripleSeas checked the log and i don't see any messages from the companion indeed. Could you please make a test selecting the C1750 device on the companion and restart the bike? in any case send me another log so I will check it.
Thanks!

**Comment by cagnulein** [comment]
@TripleSeas I can't see your message. Post it from github directly. Thanks

**Comment by TripleSeas** [comment]
Here you go
https://www.dropbox.com/scl/fo/o9mqt4qb97b8i3g9cg2v8/h?rlkey=9ydpf7sqg2s55psacpfbwu0ex&dl=0

**Comment by cagnulein** [comment]
> Here you go https://www.dropbox.com/scl/fo/o9mqt4qb97b8i3g9cg2v8/h?rlkey=9ydpf7sqg2s55psacpfbwu0ex&dl=0

thanks, same thing. try the c1750 as I said above and let me know. Thanks

**Comment by TripleSeas** [comment]
[debug-Sat_Oct_21_08_46_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13060727/debug-Sat_Oct_21_08_46_10_2023.log)
![Sat Oct 21 08_46_12 2023](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/994f970b-e9a7-4b95-a458-70c04c4d2de2)
![Sat Oct 21 08_51_36 2023](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/081139f5-7645-47dd-8761-47fd7d272eb4)

**Comment by cagnulein** [comment]
@TripleSeas in this one did you change to c1750? did you restart the bike? if so It means that we need to bypass the ifit protection in this way https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559
Let me know if you have any questions

**Comment by TripleSeas** [comment]
Yes, restarted the bike and changed to 1750. I’m not able to make a adb connection between the bike and pc

**Comment by cagnulein** [comment]
did you enable adb on the bike first?

Il giorno sab 21 ott 2023 alle 15:05 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Where can I find that setting? I have usb debugging enabled Sent from my iPhoneOn Oct 21, 2023, at 9:07 AM, Roberto Viola ***@***.***> wrote:﻿
did you enable adb on the bike first?



Il giorno sab 21 ott 2023 alle 15:05 TripleSeas ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
yes usb debugging is the one.
it could be possible that the last versions of ifit closed adb. try to
reset the factory settings to your bike, and WITHOUT updating ifit again,
try adb.
It works for the other users
let me know

Il giorno sab 21 ott 2023 alle 15:36 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Enabled usb debugging again in developer options. It somehow disabled itself. Power cycling and running another test ride.

**Comment by TripleSeas** [comment]
Still nothing. Debug log below. 

[debug-Sat_Oct_21_08_46_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13060876/debug-Sat_Oct_21_08_46_10_2023.log)

**Comment by cagnulein** [comment]
@TripleSeas did you use this method https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559 ?

**Comment by TripleSeas** [comment]
Adb debug log
![IMG_7140](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/af7d36b7-6363-422b-8557-447d29b872c1)

**Comment by cagnulein** [comment]
so adb is still doesn't work even after a factory reset?

Il giorno sab 21 ott 2023 alle 16:04 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
I'll try factory reset from within tablet? I can't seem to find a reset pinhole on the tablet.

**Comment by TripleSeas** [comment]
Factory data reset within settings?

**Comment by cagnulein** [comment]
yes, maybe there is some button on the software to do this like in any
android device

Il giorno sab 21 ott 2023 alle 16:06 TripleSeas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
yes seems right, unfortunately i don't have a proform/nordictrack device on
my own


Il giorno sab 21 ott 2023 alle 16:09 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Okay resetting
![IMG_7141](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/c438c7e3-5c93-459c-8dd2-5b6e8d00498c)

**Comment by TripleSeas** [comment]
1.Factory reset data
2.enabled privelege mode
3.enabled developer options
4.enabled usb debugging in developer options
5.connected to wifi

now going to try to install qz through qzcompanion.bat

**Comment by TripleSeas** [comment]
![IMG_7142](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/7c0e3541-0145-40c8-8d79-b294868c7191)

**Comment by cagnulein** [comment]
great news!

Il giorno sab 21 ott 2023 alle 16:21 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Treadmill has rebooted, still in privilege mode. QZ companion has started, allowed access to all media. Default selection is other in companion. Going to try manual mode in iFIT to see if metrics are read. On the right track?

**Comment by cagnulein** [comment]
yes seems so! fingers crossed!

Il giorno sab 21 ott 2023 alle 16:23 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
If it admin attempted to apply updates. Maybe I closed the app in time. Going into if it admin to disable updates

**Comment by cagnulein** [comment]
i usually suggest to disable internet access to ifit devices from the router

Il giorno sab 21 ott 2023 alle 16:25 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Okay will logon to router and attempt

**Comment by TripleSeas** [comment]
blocked the device on my router.  Will try to open ifit again

**Comment by TripleSeas** [comment]
On warmup in manual workout. Two mins left. Opened qz app. Any settings to make sure of before starting in qz after warmup?

**Comment by TripleSeas** [comment]
Metrics not reading in warmup

**Comment by cagnulein** [comment]
the ip on the companion setting as usual
I'm going to run so i will be back in 2 hours

Il giorno sab 21 ott 2023 alle 16:32 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
👍🏼

**Comment by cagnulein** [comment]
@TripleSeas any improvements?

**Comment by TripleSeas** [comment]
no IFIT keeps overriding.  Bikes with built in monitors don't seem to be compatible

**Comment by cagnulein** [comment]
nope because all the nordictrack and proform ones has a built in monitor
and I handled all of them so far. is adb still working?
if so did you follow the method that i described above?

Il giorno sab 21 ott 2023 alle 19:11 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
![IMG_7143](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/98281a7b-8d8b-4f32-890f-211d837ca710)

**Comment by TripleSeas** [comment]
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13061382/logcat.txt)

**Comment by TripleSeas** [comment]
How do I grant permission once in grand tour pro mode in companion? Which file in installpackage?

**Comment by TripleSeas** [comment]
ifit admin just forced another update

**Comment by TripleSeas** [comment]
[2023-10-21_logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/13061420/2023-10-21_logs.txt)

**Comment by cagnulein** [comment]
> [logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13061382/logcat.txt)
> 
> 

did you take this while you're doing a workout? because ifit removes the metrics when you finish it

**Comment by cagnulein** [comment]
> How do I grant permission once in grand tour pro mode in companion? Which file in installpackage?

you have to run the adb shell line directly from  a prompt in the adb folder

**Comment by cagnulein** [comment]
> ifit admin just forced another update

don't you disable in the router?

**Comment by TripleSeas** [comment]
still connected via adb so update must not have overridden

**Comment by cagnulein** [comment]
> still connected via adb so update must not have overridden

ok but ifit updates could hide metrics from qz, so when we will get a stable scenario, you have to lock it

**Comment by TripleSeas** [comment]
understood.  I deleted and reinstalled qz on iphone, should I try another manual workout with other selected and record log?

**Comment by cagnulein** [comment]
first complete the gran tour steps

**Comment by TripleSeas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/bea1db1d-5e58-454c-afe5-f984503b113f)

**Comment by cagnulein** [comment]
you have to go in that directory in the prompt first

Il giorno sab 21 ott 2023 alle 19:57 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/64f4ed28-cdd6-46cf-a225-dd4e728c5449)

**Comment by cagnulein** [comment]
you have to run the full line

./adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS

**Comment by TripleSeas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/c0129f09-b1b0-433e-afb4-912477c5f383)

**Comment by TripleSeas** [comment]
Nothing happened when I executed

**Comment by cagnulein** [comment]
no you have to first go in that dir with the cd command

and then run my line

**Comment by cagnulein** [comment]
i created a batch file for you if you want download again the zip file

**Comment by TripleSeas** [comment]
Download the new zip to pc then to bike?

**Comment by cagnulein** [comment]
nope just on the pc
you will see the new batch file grant permission . bat

Il giorno sab 21 ott 2023 alle 20:12 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Have downloaded, opens then closes

**Comment by cagnulein** [comment]
should be right. if you want to download it ok i updated it leaving it open so you will see the output

**Comment by TripleSeas** [comment]
Okay restart companion then give it a go?

**Comment by cagnulein** [comment]
no i mean download again the zip so you will have the updated batch file
and rerun it

Il giorno sab 21 ott 2023 alle 20:19 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Rerun qz companion? 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/1b0e4b39-2e07-4f0e-acd5-a9309f202601)

**Comment by cagnulein** [comment]
ok should be ok. now select the gran tour device in the companion

Il giorno sab 21 ott 2023 alle 20:23 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/dd358556-af40-4c9b-8d79-0c2ac1ae5549)

**Comment by cagnulein** [comment]
ok reboot the bike and try again
in case it doesn't work i need the wolflogs while the workout is in
progress

Il giorno sab 21 ott 2023 alle 20:27 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Seems to be working! Getting metrics

**Comment by TripleSeas** [comment]
Will try through peloton

**Comment by cagnulein** [comment]
amazing!!!
for sure in this way (at least for now) you can't have auto resistance

Il giorno sab 21 ott 2023 alle 20:38 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Why no auto resistance?

**Comment by cagnulein** [comment]
because with this method we are only reading metrics

in order to have auto resistance we have also to write, but don't worry, it
should be possible!

Il giorno sab 21 ott 2023 alle 20:41 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Okay

**Comment by TripleSeas** [comment]
![Sat Oct 21 15_13_31 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/2ce60d59-4ec2-45fb-969b-aa056c4ee757)
![Sat Oct 21 15_13_29 2023](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/58d0f2c5-9b11-4b79-a40d-782482e1bd06)

**Comment by cagnulein** [comment]
everything works?

Il giorno sab 21 ott 2023 alle 21:20 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Yes, everything but auto resistance

**Comment by cagnulein** [comment]
ok for this let's try to understand if it can work.
so first in the tablet setting, developers settings, enable the touch event
thing, so you will see a shadow when you will press the touchscreen

then, i created a new batch called
test-touch.bat

so download the install package again and run the batch file

if you see a touch event we will be able to auto resistance!

Il giorno sab 21 ott 2023 alle 21:30 TripleSeas ***@***.***>
ha scritto:

**Comment by TripleSeas** [comment]
Pointer location? 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148592340/1801af42-027a-40d6-8249-043ff13b8f4e)

**Comment by cagnulein** [comment]
yes

Il giorno sab 21 ott 2023 alle 22:04 TripleSeas ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@TripleSeas Any news?
