### ISSUE TITLE
[REQ]Colours for speed tile on Echelon Stride aren't correct?

### ISSUE THREAD

**Issue by speedf1** [cagnulein/qdomyos-zwift#1718]
I'm not sure if this is a bug, but noticed that the colours presented on the Speed tile when I'm connected to my Echelon stride and following a Peloton tread workout aren't right.  I can't see anywhere in the app to change?

**Comment by speedf1** [comment]
![Screenshot_2023-10-14-16-09-27-67_120113f1488aeb60b5b2ed37e9784b82](https://github.com/cagnulein/qdomyos-zwift/assets/87641705/4f8e8bd0-20fd-496a-a8b6-2b0de15d7a43)

**Comment by cagnulein** [comment]
hi @speedf1 actually QZ doesn't set the color based on the target speed from the peloton workout.
The coloring is now fixed following these steps

```
if (bluetoothManager->device()->currentSpeed().value() < 9) {
                speed->setValueFontColor(QStringLiteral("white"));
                this->pace->setValueFontColor(QStringLiteral("white"));
            } else if (bluetoothManager->device()->currentSpeed().value() < 10) {
                speed->setValueFontColor(QStringLiteral("limegreen"));
                this->pace->setValueFontColor(QStringLiteral("limegreen"));
            } else if (bluetoothManager->device()->currentSpeed().value() < 11) {
                speed->setValueFontColor(QStringLiteral("gold"));
                this->pace->setValueFontColor(QStringLiteral("gold"));
            } else if (bluetoothManager->device()->currentSpeed().value() < 12) {
                speed->setValueFontColor(QStringLiteral("orange"));
                this->pace->setValueFontColor(QStringLiteral("orange"));
            } else if (bluetoothManager->device()->currentSpeed().value() < 13) {
                speed->setValueFontColor(QStringLiteral("darkorange"));
                this->pace->setValueFontColor(QStringLiteral("darkorange"));
            } else if (bluetoothManager->device()->currentSpeed().value() < 14) {
                speed->setValueFontColor(QStringLiteral("orangered"));
                this->pace->setValueFontColor(QStringLiteral("orangered"));
            } else {
                speed->setValueFontColor(QStringLiteral("red"));
                this->pace->setValueFontColor(QStringLiteral("red"));
            }
```

If you want I can do it. Are you using a treadmill that has auto speed and auto incline?

**Comment by speedf1** [comment]
Hi @cagnulein  it would be great to have similar functionality in the QZ app to match the QZ Peloton bike functionality.  Ideally if we could have a "target speed" tile that is populated by data from the Peloton class and then the existing speed tile could be user adjusted to be colour coded by an easy/intermediate/advanced setting (like the way that the QZ app does for Peloton bike classes)

I've got an Echelon stride treadmill.  I think you said to me in the past that QZ can't control incline and speed, but again it would be good if that was possible?  I seem to remember a couple of version of QZ ago that pressing the +/- buttons on the speed tile on QZ did control the stride speed; but I could be wrong as this was the time when I was still getting QZ and the stride working today having just bought the stride!

**Comment by cagnulein** [comment]
> I've got an Echelon stride treadmill. I think you said to me in the past that QZ can't control incline and speed, but again it would be good if that was possible? I seem to remember a couple of version of QZ ago that pressing the +/- buttons on the speed tile on QZ did control the stride speed; but I could be wrong as this was the time when I was still getting QZ and the stride working today having just bought the stride!

as far as I know the echelon stride can't have speed or incline control.
If you have a PC I can try to make a custom version of qz that can try to control it. Let me know (in case I will open a new ticket for this)

> Ideally if we could have a "target speed" tile that is populated by data from the Peloton class

there is already! You can enable the target speed and the target incline from the tile settings.

> the existing speed tile could be user adjusted to be colour coded by an easy/intermediate/advanced setting (like the way that the QZ app does for Peloton bike classes)

yes I can do this

**Comment by cagnulein** [comment]
done @speedf1 it will be in the 2.16.20
Are you already in the beta channel on qz?

**Comment by speedf1** [comment]
Thanks!  I must've missed the target speed tile (unless it's been added recently!).  Colour coding speed in accordance with target speed would be great!

I have a laptop that I'd be happy to use to help see if we can do anything about controlling speed/incline.  If it helps, when the QZ app is connected to the stride and I press the start button on QZ, the treadmill does start to move.  I guess this might just be a simple "if app connected then start treadmill moving" type logic.

Yes I'm in the beta programme on Google Play for QZ.  I'm running version 2.16.18

**Comment by cagnulein** [comment]
> Thanks! I must've missed the target speed tile (unless it's been added recently!). Colour coding speed in accordance with target speed would be great!

yes already done while you were writing :)

> I have a laptop that I'd be happy to use to help see if we can do anything about controlling speed/incline. If it helps, when the QZ app is connected to the stride and I press the start button on QZ, the treadmill does start to move. I guess this might just be a simple "if app connected then start treadmill moving" type logic.

ok perfect I will start a branch for this and I will update you with the necessary test!

> Yes I'm in the beta programme on Google Play for QZ. I'm running version 2.16.18

perfect! you will see it in the next days (in the last weeks Google is very slow reviewing the beta)

**Comment by cagnulein** [comment]
@speedf1 check this https://github.com/cagnulein/qdomyos-zwift/issues/1721

**Comment by speedf1** [comment]
@cagnulein  Brilliant!  Thank you for your help once again.  I'll set up the laptop for #1721 later tonight and give feedback.
