### ISSUE TITLE
[BUG] refer from e-mail this morning. Mistake setting and Bluetooth issue

### ISSUE THREAD

**Issue by Koykie** [cagnulein/qdomyos-zwift#1719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
/
[debug-Mon_Oct_23_11_52_45_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13066307/debug-Mon_Oct_23_11_52_45_2023.log)

**Comment by cagnulein** [comment]
thanks, i will check it later today (6 am here in italy :) )

Il giorno lun 23 ott 2023 alle 07:13 Koykie ***@***.***> ha
scritto:

**Comment by Koykie** [comment]
Well noted and thank you so much!

**Comment by cagnulein** [comment]
@Koykie log checked. The issue here is that QZ can't see the bluetooth bike signal at all. It saw it in the past, confirmed, but it can't now. Is it possibile that the yesoul app is running in backgroun?
Can you download the free app nrfconnect and check if you can see the yesoul bike?
Let me know

**Comment by cagnulein** [comment]
@Koykie are we ok with this?

**Comment by Koykie** [comment]
Sorry I haven’t tried using it yet. Will feedback to you today.Sent from Koykie's iPhone (・ω・)ノOn 15 Nov 2023, at 13:05, Roberto Viola ***@***.***> wrote:﻿
@Koykie are we ok with this?
