### ISSUE TITLE
Test Possitibily to have control speed and incline on Echelon Stride

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1721]
Hi @cagnulein  it would be great to have similar functionality in the QZ app to match the QZ Peloton bike functionality.  Ideally if we could have a "target speed" tile that is populated by data from the Peloton class and then the existing speed tile could be user adjusted to be colour coded by an easy/intermediate/advanced setting (like the way that the QZ app does for Peloton bike classes)

I've got an Echelon stride treadmill.  I think you said to me in the past that QZ can't control incline and speed, but again it would be good if that was possible?  I seem to remember a couple of version of QZ ago that pressing the +/- buttons on the speed tile on QZ did control the stride speed; but I could be wrong as this was the time when I was still getting QZ and the stride working today having just bought the stride!

_Originally posted by @speedf1 in https://github.com/cagnulein/qdomyos-zwift/issues/1718#issuecomment-1774683718_

**Comment by cagnulein** [comment]
@speedf1 new ticket in order to check the possibility to control speed or incline on Echelon Stride

**Comment by cagnulein** [comment]
@speedf1 this is the custom build for windows https://github.com/cagnulein/qdomyos-zwift/suites/17523443805/artifacts/1001073903

**please be safe: this version could start or change the speed of the treadmill automatically! Don't test with you on the treadmill!**

In order to test it
1. extract the zip
2. run qdomyos-zwift.exe, go into the experimental settings and enable the debug log
3. close qz
4. pair the treadmill with the bluetooth settings of windows
5. start qz again
6. now you should see the tiles, if so, start the tape at the min speed and wait at least 7 minutes leaving it running

If we have a success, I'm expecting to change automatically the speed to 5 km/h (or 5 miles/h) at a some point.

let me know

**Comment by speedf1** [comment]
Hi, taken a while for me to get to this, but looks like the tread can't be controlled with the windows build.

**Comment by cagnulein** [comment]
hi @speedf1 please attach a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by speedf1** [comment]
@cagnulein  
[debug-Sun_Nov_19_14_08_24_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13403467/debug-Sun_Nov_19_14_08_24_2023.log)
Attached is the debug log

**Comment by cagnulein** [comment]
thanks @speedf1 I chcked the log but you need to let it run for more time. you completed more or less the 40% of the test in that time. please repeat leaving it running 20 or more minutes, i thought it could be faster, but i was wrong, in order to test it, it has to test all the possibilities.
Thanks

**Comment by speedf1** [comment]
Hi @cagnulein , I tried running it for longer, but after a few minutes I got some message that QZ needs to be activated/subscribed to?  It then exited.  Here's the log up to that point though
[Uploading debug-Mon_Nov_20_17_35_07_2023.log…]()

**Comment by cagnulein** [comment]
hah ok write me your email on messenger and i will unlock it!

Il giorno lun 20 nov 2023 alle 18:52 speedf1 ***@***.***> ha
scritto:

**Comment by speedf1** [comment]
@cagnulein Just sent you an email.

**Comment by cagnulein** [comment]
unlocked, also the last log from your is truncated, could you please upload it again? thanks!

**Comment by speedf1** [comment]
Thanks, please find completed file attached
[debug-Sun_Nov_26_16_43_26_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13493272/debug-Sun_Nov_26_16_43_26_2023.log)

**Comment by cagnulein** [comment]
thanks @speedf1 during this test, did you observe if the speed changed randomly?

**Comment by speedf1** [comment]
Hi @cagnulein , I wasn't watching the treadmill extensively, but I didn't notice any changes in speed.

**Comment by cagnulein** [comment]
if it's so, it means that they didn't implement on the firmware unfortunately :(

**Comment by speedf1** [comment]
OK.  No problem.  Thanks for your time in looking at this though.
