### ISSUE TITLE
[BUG] No resistance control on Proform PFEX39421-INT TDF CBC

### ISSUE THREAD

**Issue by foehammer** [cagnulein/qdomyos-zwift#1723]
**Describe the bug**
Automatic resistance controls do not work during workout or if attempting to change via the app interface.
No 'controls' are found by zwift when pairing either. Resistance 'connects' but no changes to intensity or resistance translate through the app.

Bike type: PFEX39421-INT TDF CBC

**To Reproduce**

**Expected behavior**
Would have hoped that resistance controls would translate through from Zwift onto the bike.

**Screenshots**

**Smartphone (please complete the following information):**
iPhone 11 on iOS 17.0.3

**Append a debug log**
[debug-Sun_Oct_22_19_18_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13069081/debug-Sun_Oct_22_19_18_44_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by foehammer** [comment]
OK, take 2. Just tried it out, still no joy on the resistance changing automatically.

[debug-Mon_Oct_23_13_30_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13070126/debug-Mon_Oct_23_13_30_19_2023.log)

**Comment by cagnulein** [comment]
@foehammer perfect i see the resistance writing frames now.
In the proform bike section in qz there are several switches for different bikes type.
You can enable one at a time (so disable the other for this test).
You need to find the right one for you. How?
Simply follow this:
1. enable only one setting there
2. restart qz
3. try to press the plus button on the resistance tile
4. repeat this until you will see a switch that works for you

Let me know!

**Comment by foehammer** [comment]
Working with 'Tour De France CLC' enabled. I swear I did this last night. Must have been doing something else wrong though.

Thanks for the clarity! <3

**Comment by cagnulein** [comment]
great! let me know if you have any other issues!
