### ISSUE TITLE
Connectivity issue with Saris/ Cycleops Hammer trainer

### ISSUE THREAD

**Issue by arosemeier** [cagnulein/qdomyos-zwift#1724]
I am trying to use qz with a saris controllable trainer 
The trainer is a cycle ops hammer which was also sold as a saris h2 and h3 

1.The qz app seems to connect from phone(Iphone XS) to tablet(Ipad) ok (zwift shows connection) but from the phone to the trainer it shows found,   but I never see any data in the qz screen. 
No data ever flows to zwift either.  ( no rpm or power data) 
14,58 log
2. pressing resistance button kills app 
15,14log

**Expected behavior**
1.There should be some data flowing from the trainer to my phone 
2. resistance button shouldn't crash app, and change trainer resistance 

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148819122/c593f9e4-0884-4329-973e-2f6b9629f373)

**Smartphone (please complete the following information):**
 - Device: [iphone xs]
 - Ios: [16.6.1]

 Saris Trainer info:
![image](https://github.com/cagnulein/qdomyos-zwift/assets/148819122/200b4a6a-b8f8-4cd7-b2b1-84e9f8bbe672)
****
[debug-Mon_Oct_23_15_14_48_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13079246/debug-Mon_Oct_23_15_14_48_2023.log)
[debug-Mon_Oct_23_14_58_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13079247/debug-Mon_Oct_23_14_58_08_2023.log)

**Comment by cagnulein** [comment]
Hi @arosemeier 
Enable the setting under "Hammer Racer Bike Options" and restart QZ

#1019

**Comment by arosemeier** [comment]
Logs attached.

For the record it is not a hammer bike it is a direct drive trainer. Same as the saris h2 and h3




On Oct 24, 2023, at 3:18 AM, Roberto Viola ***@***.***> wrote:

﻿

Hi @arosemeier<https://github.com/arosemeier>
Enable the setting under "Hammer Racer Bike Options" and restart QZ

#1019<https://github.com/cagnulein/qdomyos-zwift/issues/1019>

**Comment by cagnulein** [comment]
hi @arosemeier you have to attach it from github otherwise I can't see it
Thanks

**Comment by arosemeier** [comment]
Hi
Sorry logs attached now.  
This first should just be enabling hammer. 
Results are the same, Still no data to QZ. 

[debug-Tue_Oct_24_07_11_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13115220/debug-Tue_Oct_24_07_11_36_2023.log)
[debug-Tue_Oct_24_07_10_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13115221/debug-Tue_Oct_24_07_10_35_2023.log)

**Comment by cagnulein** [comment]
ok got the issue, your trainer is sending power information only. Trying to do this:
- in the accessories section in the qz settings, set your trainer as a power sensor and press ok
- also enable the "power sensor as a bike"
- restart qz

I hope it will be enough otherwise I will do a mod for you
Let me know

**Comment by arosemeier** [comment]
Thank you will give it a try! It will be later today.

**Comment by cagnulein** [comment]
just for reference, the saris that I implemented had the FTMS support #1147
that's why is not working on yours, let's see if we can fix this!

**Comment by arosemeier** [comment]
I have made the setting changes,  Now I see power and other data on the qz screen, 
It appears cadence data is roughly doubled actual, power data looked close,  Speed was very far off ( very high) but I have not added any setting for wheel geo beyond what might have been default. 

I tried to start zwift:

- The first time it gave me the option to connect to qz- No power or cadence data showed in zwift. 

- the second/third time it just gave me the option to connect to my iphone,  again still no power or cadence data in zwift. 

[debug-Tue_Oct_24_12_59_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13126205/debug-Tue_Oct_24_12_59_22_2023.log)
[debug-Tue_Oct_24_12_56_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13126206/debug-Tue_Oct_24_12_56_17_2023.log)
[debug-Tue_Oct_24_12_55_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13126207/debug-Tue_Oct_24_12_55_05_2023.log)

**Comment by cagnulein** [comment]
hi, are you using 2 devices: one for zwift and one for qz?

Il giorno mar 24 ott 2023 alle 21:15 arosemeier ***@***.***>
ha scritto:

**Comment by arosemeier** [comment]
yes, qz on an iPhone XS, Tablet(ipad) for Zwift

**Comment by cagnulein** [comment]
found the issue. as i guessed i need to do a mod for this. i will let you
know when i will be ready

Il giorno mar 24 ott 2023 alle 21:18 arosemeier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done! I will send you it later today!

**Comment by arosemeier** [comment]
Thanks for the note on testflight..

It appears power is now working and transmits to Zwift
 trainer as a power sensor 
 "power sensor as a bike"

Remaining Issues: 
Cadence appears to be about 3x actual  ( 80 RPM shows roughly 240 rpm in zwift and on qz ap) 

Zwift world incline doesn't seem to change trainer resistance at all.  (resistance is constant- this would normally change based on incline)  ( I did not try EGR mode in zwift, only free-ride) 

Changing gears in qz also does not change resistance on trainer ( with a MTB on the trainer this is the major QZ benefit)

I tried a few other random settings in later logs. 

[debug-Wed_Oct_25_16_54_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13171374/debug-Wed_Oct_25_16_54_13_2023.log)
[debug-Wed_Oct_25_16_47_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13171372/debug-Wed_Oct_25_16_47_16_2023.log)

[debug-Wed_Oct_25_16_46_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13171371/debug-Wed_Oct_25_16_46_04_2023.log)

**Comment by cagnulein** [comment]
> It appears power is now working and transmits to Zwift
> trainer as a power sensor
> "power sensor as a bike"

Great!

> Cadence appears to be about 3x actual ( 80 RPM shows roughly 240 rpm in zwift and on qz ap)

Got it and fixed this morning, thanks.



> Zwift world incline doesn't seem to change trainer resistance at all. (resistance is constant- this would normally change based on incline) ( I did not try EGR mode in zwift, only free-ride)

yes because I don't see any possibility for your trainer to change the resistance, am I wrong? does it work out of the box with zwift? if so I have to add it but I need a hci snoof from an android device running zwift directly to your trainer.

Let me know!

**Comment by arosemeier** [comment]
Yes this trainer is capable to change resistance, run EGR mode in zwift etc.  
https://saris.com/products/h3-direct-drive-smart-trainer 
It does work out of the box with zwift- absolutely no issues.
I do not have an  current android device, could a log be generated via a PC in anyway?

**Comment by cagnulein** [comment]
no unfortunately an android device is required for this. even an old one:
could anybody borrow you one for 10 minutes?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 ott 2023 alle ore 14:41 arosemeier <
***@***.***> ha scritto:

**Comment by arosemeier** [comment]
I can try to borrow something,

Do i just need to try and connect to the trainer via blutooth?
Do I also need QZ on that device ( then a very old device may not work?)

________________________________

**Comment by cagnulein** [comment]
you have to install zwift or any other apps that control the trainer on
that device and follow this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

no you don't need qz on that device

Il giorno gio 26 ott 2023 alle 15:00 arosemeier ***@***.***>
ha scritto:

**Comment by arosemeier** [comment]
I have not been able to locate an android device I can borrow that is new enough to get the log,  Can a log be generated from a PC that you can use?

**Comment by cagnulein** [comment]
nope unfortunately only an android device can do it

Il giorno mer 1 nov 2023 alle 21:21 arosemeier ***@***.***>
ha scritto:

**Comment by arosemeier** [comment]
any chance at a refund for this app since it will not work with my trainer then?

**Comment by cagnulein** [comment]
i'm sorry but developers can't refund directly, you have to ask to apple.
my will is to help you but I need that information otherwise it's
impossible for me :(

Il giorno mer 1 nov 2023 alle 21:25 arosemeier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@arosemeier simply buy an android device from amazon and then ask for a refund. it will be very fast!

**Comment by arosemeier** [comment]
could wireshark be used on my pc to generate the log you need?

**Comment by cagnulein** [comment]
@arosemeier nope because you need to run the app that works with your trainer. if you have an app that works with your trainer on your pc, then we can do it. otherwise just buy an android phone on amazon, do the log, and then just ask for a refund on amazon ;)

**Comment by arosemeier** [comment]
Zwift on my PC can work with the trainer,  this was what I was asking about: https://github.com/darthcloud/BlueRetro/wiki/Bluetooth-HCI-trace-with-Win10

**Comment by cagnulein** [comment]
@arosemeier Hah ok I didn't get this! So yes it should be possible, never tried. Give it a try!

**Comment by arosemeier** [comment]
1. Started log
2. Started zwift
3. Connected trainer, power, then resistance, 
4. Cadence auto connected after resistance 
5. Started a ride in zwift, Road to the sky
6. Rode the first few minutes of that ride,  tried to keep cadence at about 80 RPM, resistance varied with road grade ( the lead in varies from around 2% starting, goes up to about 3%, then to about -2% in the first couple minutes of riding on that route. ) 



Wireshark log and TXT file copy and past of log attached. 
[Saris_hammer.txt](https://github.com/cagnulein/qdomyos-zwift/files/13231837/Saris_hammer.txt)
[wireshark_log.zip](https://github.com/cagnulein/qdomyos-zwift/files/13231840/wireshark_log.zip)

**Comment by cagnulein** [comment]
Awesome, thanks for the update!
I will check it asap!

Il giorno mer 1 nov 2023 alle 22:19 arosemeier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok got it! it's using the wahoo protocol! I'm adding it now and I will build a new Windows version

**Comment by cagnulein** [comment]
done @arosemeier it will be available at the bottom here https://github.com/cagnulein/qdomyos-zwift/actions/runs/6729749884

I added a new setting for the Saris trainer in the settings, enable it also disable it from the power sensor and disable also the power sensor as a bike and restart QZ

Let me know!

**Comment by arosemeier** [comment]
Glad the log worked for you! 

is there a version coming through IOS / testflight?  I am running qz on an Iphone xs?  
Thank you

**Comment by cagnulein** [comment]
yes I'm building it now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 2 nov 2023 alle ore 14:26 arosemeier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 2 nov 2023 alle ore 14:26 cagnulein ***@***.***> ha
scritto:

**Comment by arosemeier** [comment]
enabled saris trainer support, restarted qz
started trainer,
started qz, 
started zwift, 
connected zwift to phone: showed as iphone not qz ( it has sometimes shown up as qz in the zwift connection screen) 
started a route,

NO power or cadence reported to qz screen on phone or to zwift. 
[debug-Thu_Nov_2_17_48_41_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13245681/debug-Thu_Nov_2_17_48_41_2023.log)
[debug-Thu_Nov_2_17_46_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13245682/debug-Thu_Nov_2_17_46_29_2023.log)

**Comment by cagnulein** [comment]
@arosemeier the problem here is that you enable by mistake I guess, the fake rower setting in the experimental settings. Disable it and restart QZ

Let me know!

**Comment by arosemeier** [comment]
Appears everything is working now!  Gear function is awesome for MTB's 
Thanks for your help and prompt response.  I will plan to stay on your development branch( test flight) until and official release comes with support! 
Thanks again!

**Comment by cagnulein** [comment]
Glad to hear it!

Il giorno ven 3 nov 2023 alle 21:14 arosemeier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Hi @ryanwalexander send a debug log and I will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
