### ISSUE TITLE
Support for Domyos EL540 (Domyos-EL-1350)

### ISSUE THREAD

**Issue by lnussbaum** [cagnulein/qdomyos-zwift#1725]
Hi,

Thanks for QZ Fitness!

I just got a Domyos EL540 elliptical bike and am trying to use it with QZ Fitness (Android).

The elliptical bike gets detected over bluetooth as Domyos-EL-1350.

After disabling "Inclination supported" in Domyos Elliptical Options, the power ratings look approximately reasonable compared to what I would assume from my experience with a bike power meter (maybe a bit low, but maybe I should train more :-) ).

Problems I noticed so far:
* When uploading the activity to Strava from QZ Fitness, the activity type is "walk" and the power data is labelled as cadence, and the cadence data is not available.
    * However, if I delete the auto-uploaded Strava activity, and then upload the FIT file manually as an Elliptical activity, the data looks OK.
* When downloading the FIT file and and opening it in GoldenCheetah, the Hardware type is "Development 1" (I would expect the model name here).

Best,

Lucas

**Comment by cagnulein** [comment]
hi @lnussbaum could you please attach the fit file?

**Comment by lnussbaum** [comment]
[fit.zip](https://github.com/cagnulein/qdomyos-zwift/files/13114128/fit.zip)

Here it is

**Comment by cagnulein** [comment]
log checked, these are my observations

> When uploading the activity to Strava from QZ Fitness, the activity type is "walk" and the power data is labelled as cadence, and the cadence data is not available.
> * However, if I delete the auto-uploaded Strava activity, and then upload the FIT file manually as an Elliptical activity, the data looks OK.

yes in the file there is the walk type. Because in the fit file there isn't the main activity elliptical, there is only the subtype activity that you can already enable, disabling the Strava Virtual Activity Tag setting in the advanced setting.



> * When downloading the FIT file and and opening it in GoldenCheetah, the Hardware type is "Development 1" (I would expect the model name here).

yes this is a fixed field. If you want I can add the bluetooth name of the device, yes.

**Comment by cagnulein** [comment]
comment updated

**Comment by lnussbaum** [comment]
> log checked, these are my observations
> 
> > When uploading the activity to Strava from QZ Fitness, the activity type is "walk" and the power data is labelled as cadence, and the cadence data is not available.
> > 
> > * However, if I delete the auto-uploaded Strava activity, and then upload the FIT file manually as an Elliptical activity, the data looks OK.
> 
> yes in the file there is the walk type. Because in the fit file there isn't the main activity elliptical, there is only the subtype activity that you can already enable, disabling the Strava Virtual Activity Tag setting in the advanced setting.

Thanks, that works !

> > * When downloading the FIT file and and opening it in GoldenCheetah, the Hardware type is "Development 1" (I would expect the model name here).
> 
> yes this is a fixed field. If you want I can add the DECATHLON id there instead.

I think that would be useful, even though it's a minor issue of course.

My only remaining issue is that, when I try to connect both my phone with QZ Fitness, and my cardio belt (bluetooth as well), the console goes crazy. Probably it cannot handle two BLE devices at the same time. But that does not seem specific to QZ Fitness (the behaviour is the same with the Domyos E Connected app), so there's probably nothing QA Fitness can do about that.
Apparently the console can handle analog/non-coded belts as well, I'll try that and report back (it could be useful for other QZ Fitness users).

**Comment by cagnulein** [comment]
> I think that would be useful, even though it's a minor issue of course.

done! it will be in the 2.16.20 version of QZ!

> My only remaining issue is that, when I try to connect both my phone with QZ Fitness, and my cardio belt (bluetooth as well), the console goes crazy. Probably it cannot handle two BLE devices at the same time. But that does not seem specific to QZ Fitness (the behaviour is the same with the Domyos E Connected app), so there's probably nothing QA Fitness can do about that.
> Apparently the console can handle analog/non-coded belts as well, I'll try that and report back (it could be useful for other QZ Fitness users).

on my domyos intense run console, qz is writing the BPM field on the console directly. I don't know if it's possible on yours too. Do you see the metrics on the console fom QZ?

**Comment by lnussbaum** [comment]
> > My only remaining issue is that, when I try to connect both my phone with QZ Fitness, and my cardio belt (bluetooth as well), the console goes crazy. Probably it cannot handle two BLE devices at the same time. But that does not seem specific to QZ Fitness (the behaviour is the same with the Domyos E Connected app), so there's probably nothing QZ Fitness can do about that.
> > Apparently the console can handle analog/non-coded belts as well, I'll try that and report back (it could be useful for other QZ Fitness users).
> 
> on my domyos intense run console, qz is writing the BPM field on the console directly. I don't know if it's possible on yours too. Do you see the metrics on the console fom QZ?

Ah, it's QZ that is sending data to the console? But how does it acquire data from the sensor?

What I see is:
* Without any bluetooth app running, the console displays HR with both a bluetooth belt and an analogic belt
* With QZ fitness :
   + with the bluetooth belt, it looks like the console keeps trying to acquire a bluetooth connection, but fails (it displays the bluetooth logo for a few seconds, then gives up, then displays it again, then gives up, etc.)
   + with the analogic belt, the console display 0 BPM
* With the Domyos e-connected app:
   + with the bluetooth belt, the behaviour is the same as with QZ Fitness
   + with the analogic belt, both the app and the console displays a heart rate (strangely, not in a synchronized way)

I will do more tests tomorrow. Is there something I can do to help debug this?

**Comment by cagnulein** [comment]
just a test, on qz disable the virtual bluetooth device (only this!) and restart qz
is the behavior the same?

**Comment by lnussbaum** [comment]
Hi,

Regarding the console getting confused about bluetooth devices (when there's my phone with QZ or E-Connected, and my BT belt), the behavior is the same after disabling the bluetooth virtual device. Since this also happens with E-Connected, I suppose there's nothing to do about it.

Regarding QZ not displaying HR, I "fixed" it ... I had accidentally enabled "Disable HRM from Machinery" while testing. So what works fine is using an analog cardio belt, that is compatible with the bike, and then the bike pushes that HRM data to bluetooth (and QZ).

Another question: I built the desktop app and noticed that in the debug log, I get:
```
Sun Nov 5 08:10:29 2023 1699168229673 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " << f0 bc 00 01 00 1c 00 19 00 1e 00 00 00 00 01 00 01 00 53 00 06 00 00 00 01 5c"
Sun Nov 5 08:10:29 2023 1699168229673 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current speed: 2.5"
Sun Nov 5 08:10:29 2023 1699168229673 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current cadence: 30"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current resistance: 1"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current inclination: 0"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current heart: 83"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current KCal: 0"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Distance: 0"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current CrankRevs: 29"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Last CrankEventTime: 16384"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Watt: 49"
Sun Nov 5 08:10:29 2023 1699168229674 Debug: bluetooth.cpp void bluetooth::debug(const QString&) " exit for timeout"
```

It looks like the device is sending power data ("current watt: 49"). Is this used by QZ ? In the desktop app, there is a "Disable wattage from machinery" option, but I cannot find it in the android app.

**Comment by cagnulein** [comment]
nope qz is calculating it based on the speed inclination and weight :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 5 nov 2023 alle ore 08:51 Lucas Nussbaum <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
No domyos device sends wattage :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 5 nov 2023 alle ore 10:00 Lucas Nussbaum <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@lnussbaum are we ok with this?
