### ISSUE TITLE
[BUG] Wahoo Kickr and Virtual Gears

### ISSUE THREAD

**Issue by michaelfisher44** [cagnulein/qdomyos-zwift#1726]
**Describe the bug**
I'm using QZ with a Wahoo Kickr and connect fine to the Kickr on one phone via QZ, then boot up Zwift on another phone and connect on that (it's just shows up as Wahoo KICKR 4EC7 160). However despite changing gears on QZ to increase the base resistance, it doesn't seem to be changing in Zwift. I've tried increasing the gears up to 20 but unfortunately don't feel any change in Zwift. Any help much appreciated. I've attached a debug log for reference. Thanks. 

**Screenshots**
[debug-Tue_Oct_24_09_47_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13113380/debug-Tue_Oct_24_09_47_54_2023.log)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@michaelfisher44 Found the issue, I didn't managed the gear event for this particular bike. I will do today and I will submit the new version! It will be in the 2.16.20

Join the beta channel from the play store page of QZ to receive the update automatically!

Let me know

**Comment by cagnulein** [comment]
@michaelfisher44 in the log that you sent me I don't see a connection to zwift. In order to apply the gear mod to the base resistance I need to check a log where you are connect to zwift
Let me know!

**Comment by michaelfisher44** [comment]
Sure, I've tried again and this time when I change the gears the resistance spikes dramatically for a few seconds, but then returns back to normal (despite being on a free ride). Attached is the debug log and a photo of the connection options I see in Zwift once the Kickr is connected to QZ, in case there's another option I should be choosing. 
Thanks. 

![20231027_110540](https://github.com/cagnulein/qdomyos-zwift/assets/129891251/1853d306-e4ea-414d-8484-e7118292175e)
[debug-Fri_Oct_27_10_58_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13187738/debug-Fri_Oct_27_10_58_18_2023.log)

**Comment by cagnulein** [comment]
Hi in the log I see the connection to your trainer but not from zwift. Where are you running QZ? on the same iphone? That's the issue if so. You need 2 devices: 1 for qz and 1 for zwift (1 device only is available only on android for zwift)

Let me know

**Comment by michaelfisher44** [comment]
I'm running it on two devices, both Android - one for QZ and one for Zwift. Not sure if certain devices would be more compatible than others?

**Comment by cagnulein** [comment]
are both on the same wifi?
also on the qz device try to rename it to "bike" only 4 letters and reboot
it

you should see it on the zwift device

also be sure qz will be always in foreground

Il giorno ven 27 ott 2023 alle 12:45 michaelfisher44 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@michaelfisher44 any news?

**Comment by cagnulein** [comment]
@michaelfisher44 is it working or you are not interested on this?

**Comment by michaelfisher44** [comment]
No I've not had any luck unfortunately. Can't seem to find the option in QZ to rename the device to "bike" - where is it? I've also just had a bike shop change cassette on the Kickr  and realign gears so hoping that will help the issue with spinning out.

**Comment by cagnulein** [comment]
you have to rename the device from your android setting of the qz device , so your phone will change name to bike
then reboot it, let me know

**Comment by michaelfisher44** [comment]
Thanks that fixed it! I can see the 'bike' device now separate to the Kickr and have connected to that. All works fine now. 

Many thanks

**Comment by cagnulein** [comment]
Glad to hear it!
