### ISSUE TITLE
[BUG] QZ app not reporting watts from stryd power sensor 

### ISSUE THREAD

**Issue by taxi333** [cagnulein/qdomyos-zwift#1729]
**Describe the bug**
QZ app does not show watts from stryd power sensor
my setup is the following:
- Horizon 7.8AT ( 2023 model ) treadmill
- HRMpro+ ( garmin ) sensor
- stryd pod  ( as power sensor ) 
 
**To Reproduce**
1. Open App
2. Start Run 
3. notice current watts vs stryd watts
4. watts displayed by qz don't match stryd watts

**Expected behavior**
qz fit file ( and current watts ) to match stryd power sensor 

**Screenshots**
TODO

**Smartphone (please complete the following information):**
 - Device: iPhone 15 pro max
 - OS: iOS 17.0.3
 - Version qz app version 2.15.4

**Append a debug log**
TODO
 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
done! 
https://github.com/cagnulein/qdomyos-zwift/commit/f79eae87a991dea64c91f1ac50fcec10430acff6

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by taxi333** [comment]
QZ is now getting power from stryd pod when using a Horizon 7.8AT treadmill. 

**Nice to have:** I also noticed that when using an incline on the treadmill, QZ continues to display same power as if the incline was still 0%, probably is because the **client** ( the device where the power is being recorded) is the one responsible for applying the power gain to the data and not the stryd pod itself ( probably the stryd pod is just sending the raw power). 

PS when I say "client" I am using the stryd pod app on a garmin fenix 7x watch, and in there I specify the incline so the power changes on the watch ... I can simply change the power gain on the QZ app to match the power I am seeing on the watch ( I've change the power live and it changes nicely). It would be ideal ( not needed ) to have some preset power gains based on the incline that the treadmill is reporting.

Thank you for all the work you do, I did not expect this level of support!

**Comment by taxi333** [comment]
The bug can be considered closed.

**Comment by cagnulein** [comment]
thanks! yes adding the inclination component it's possible! let me try the
implementation in the next days ;)

Il giorno ven 27 ott 2023 alle 21:59 taxi333 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@taxi333 I created #1741 for this, I'm planning to do it today
