### ISSUE TITLE
[BUG] Proform TDF 4.0 Auto Incline not working at all, auto resistance sort of works

### ISSUE THREAD

**Issue by dan1282** [cagnulein/qdomyos-zwift#1731]
**Describe the bug**
Auto Incline: Not functioning at all with Zwift
Auto Resistance: With ftp set to 225, warmup and below 200 target watts seems relatively normal (compared to my experience with echelon ex3).  As target wattage goes above 200, it the resistance of my bike seems to max out making it next to impossible to pedal.  

**To Reproduce**

**Expected behavior**
Auto incline: Verified that motor is functioning properly on bike.  I can manually adjust the incline on the TDF console and incline will automatically adjust if I select a workout from the TDF console.
Auto resistance: seems to function as normal with TDF console.  I've played around with a variety of settings in QZ to try and get auto incline/auto resistance to work properly without success.  Hopefully the debug log captures all of these attempts. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Iphone 15 Pro for QZ, Ipad Pro 10.5 for Zwift
 - OS: 17.03

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @dan1282 please attach the debug log (you can zip it first)

**Comment by dan1282** [comment]
[debug-Wed_Oct_25_20_38_55_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13178534/debug-Wed_Oct_25_20_38_55_2023.zip)

Here you go!

**Comment by dan1282** [comment]
![connected devices](https://github.com/cagnulein/qdomyos-zwift/assets/147757256/21bd3d8c-da55-46d0-84da-056267335c71)

Image of what is connected to zwift if this is helpful

**Comment by cagnulein** [comment]
the main issue of this log is that you're doing free ride in zwift with the
"zwift erg" setting enabled in qz. you have to disable it and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 ott 2023 alle ore 16:09 dan1282 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I need a log where you don't change settings and you do the ride that is ok
for the qz settings otherwise it's very hard to understand
Also I'm seeing A LOT of disconnection from your bike, is the wifi strong
where you have the bike?
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 ott 2023 alle ore 16:17 dan1282 ***@***.***>
ha scritto:

**Comment by dan1282** [comment]
Ok.  I'm sorry i really should have separated things out.  I'll create a log focusing on auto resistance and a separate one for incline.  Wifi signal is good.  I think that the disconnects were occurring bc I was going into QZ settings and changing things as I was in a zwift ride.

**Comment by cagnulein** [comment]
no I don't think disconnection are about settings, because it happens every
4 seconds from the start to the end of the log. It could be reason of the
most of your issues.
We should investigate this.
Maybe you can try to ping the bike from the phone as a beginning for a 5-10
minutes just to check that the wifi is strong.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 ott 2023 alle ore 16:31 dan1282 ***@***.***>
ha scritto:

**Comment by dan1282** [comment]
interesting... ok i will give that a shot.  How would I ping the bike from my Iphone?

**Comment by cagnulein** [comment]
download a classic ping app for free from the app store :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 ott 2023 alle ore 16:35 dan1282 ***@***.***>
ha scritto:

**Comment by dan1282** [comment]
Roberto-

regarding pinging the bike: first attempt it was failing like crazy. I suspect it’s bc I’m in my basement and I’m between my main router and an access point (really need to upgrade to mesh). After making sure bike and devices were all connected to the same network, it seemed much more stable.

onto workout mode: if I select a training session in zwift, erg mode is enabled in qz and zwift. As I begin a workout, things appear to be working as expected but eventually the resistance gets too high to be sustainable (this is what I’ve noticed prior as well). Incline does not work at all.

i then turned off erg mode in qz and joined a group ride. Incline works! As well as resistance changes going up and down hills. Shifting from the bike worked well additionally. Very impressive overall! 

So I guess the question is, what should I have enabled/disabled for zwift workouts? Should auto incline function with that? I have logs if you need them but I’m thinking maybe this is just a configuration thing…

**Comment by cagnulein** [comment]
on workout you have to enable the erg mode in qz and you have to stay in the home screen of the bike, not the manual one.

here inclination will not work, it's not supposed to be, you're training with wattage, not inclination.

about the resistance, be sure you select the right ftp on zwift, otherwise you will have this behavior: here is zwift the master ;)

**Comment by dan1282** [comment]
Ok I think I got it! Just to be clear, in free ride mode, erg disabled but on proform console select manual workout (which I have been doing.)

if I go into training mode, I re-enable erg mode in qz but also stay on Home Screen of proform? Out of curiosity, what’s the reason for this? 

Regarding ftp: I suppose I should test on the new bike. 225 was a good number for echelon but I understand it could be different here

**Comment by cagnulein** [comment]
> Ok I think I got it! Just to be clear, in free ride mode, erg disabled but on proform console select manual workout (which I have been doing.)
> 

yes!

> 
> if I go into training mode, I re-enable erg mode in qz but also stay on Home Screen of proform? Out of curiosity, what’s the reason for this? 
> 

yes! that's how the firmware works , probably the manual mode doesn't handle erg mode by default. i discovered this after a lot of headaches 

> 
> Regarding ftp: I suppose I should test on the new bike. 225 was a good number for echelon but I understand it could be different here 

yes could be, this is more real as far as I see on my bike with watt gain to 0.8

**Comment by dan1282** [comment]
Thank you for this explanation! That makes sense! I'm guessing that all the funky stuff happening with workout mode was due to having the proform in manual mode.  Will try this today! 

BTW- aside from watt gain, what are you setting your zwift resistance offset to? Any other gains/offsets I should be going in and explicitly setting? 

If I haven't said it already-this is an amazing piece of sw you wrote that adds so much functionality into bikes

**Comment by cagnulein** [comment]
mmm i guess the rest is by default, let me know if you have any other
questions!

Il giorno ven 27 ott 2023 alle 14:58 dan1282 ***@***.***> ha
scritto:
