### ISSUE TITLE
[REQ] fr30z support/multiuser xp

### ISSUE THREAD

**Issue by faljse** [cagnulein/qdomyos-zwift#1735]
My Treadmill does support kinomap and zwift directly.
However, every time somebody else wants to use the treadmill it has to be removed/unpaired from one phone and re-paired to the other.

Currently my treadmill doesnt work with qz (found REEBOK0673, but all values remain zero)
If qz would support my treadmill; could it improve the multiuser xp?

**Comment by cagnulein** [comment]
hi! your treadmill should be already compatible with qz. please append a
debug log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Il giorno sab 28 ott 2023 alle 12:30 Martin Kunz ***@***.***>
ha scritto:

**Comment by faljse** [comment]
Required root and total commander to access android/data.. but here it is!
i could only find references to "fr30" in your code, which in contrast to "fr30z" is not zwift compatible
[debug-Sat_Oct_28_13_55_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13195925/debug-Sat_Oct_28_13_55_58_2023.log)

**Comment by cagnulein** [comment]
thanks , I'll check it out asap

Il giorno sab 28 ott 2023 alle 15:49 Martin Kunz ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
got the issue, it's a simple one. i will fix it tomorrow or monday

Il giorno sab 28 ott 2023 alle 16:31 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@faljse done! It will be in the 2.16.21 in the store.
If you want, in the meantime you can test it getting the android build from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/6689815579 as soon as it finish the build (15 minutes trial)

Let me know!

**Comment by cagnulein** [comment]
sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/6690036707

**Comment by cagnulein** [comment]
again sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/6690200007

**Comment by faljse** [comment]
hi,
qz-app seems to be working fine now!
However, kinomap stays at "Your equipment is connecting..."  (i added a FTMS treadmill)

**Comment by cagnulein** [comment]
are you running kinomap on a second device?

Il giorno mar 31 ott 2023 alle 18:01 Martin Kunz ***@***.***>
ha scritto:

**Comment by faljse** [comment]
Yes, kinomap is running on a seperate android phone

**Comment by cagnulein** [comment]
rename your phone running qz to run only 3 letters and reboot it
let me know

Il giorno mar 31 ott 2023 alle 18:47 Martin Kunz ***@***.***>
ha scritto:

**Comment by faljse** [comment]
Didnt help :(
i can add the treadmill without issues
when i start a training it displays "Begin running to start training"
If i press start on the treadmill it switches to "Your equipment is connecting..."

**Comment by cagnulein** [comment]
just to be sure about the qz setup, try with zwift
then if it works we will try to understand the kinomap issue (maybe
contacting them)

Il giorno mar 31 ott 2023 alle 18:55 Martin Kunz ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@faljse Any news?
