### ISSUE TITLE
[BUG] Unable to get Ex3 bike to connect properly to QZApp

### ISSUE THREAD

**Issue by Stlou16** [cagnulein/qdomyos-zwift#1738]
**Describe the bug**
I am unable to connect my ex3 to the QZ App correctly, it will not show any data as i try and ride my bike
**Expected behavior**

**Screenshots**
![Screenshot_20231028-110410](https://github.com/cagnulein/qdomyos-zwift/assets/149258866/d732542e-693f-4ccb-b50a-7495fcaff564)

**Smartphone (please complete the following information):**
Samsung Galaxy Note 8
Android 9
**Append a debug log**
[debug-Sat_Oct_28_11_27_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13196328/debug-Sat_Oct_28_11_27_17_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
good news, i see the metrics on the file. is the screenshot about the
session of the file that you sent me?

Il giorno sab 28 ott 2023 alle 18:53 Stlou16 ***@***.***> ha
scritto:

**Comment by Stlou16** [comment]
Yes that is correct, I can get them to show up and record for a short period and then it freezes.

**Comment by cagnulein** [comment]
ok that's because the bike disconnects. did you experience the same on the
echelon app? did you also try with another phone?

Il giorno sab 28 ott 2023 alle 19:54 Stlou16 ***@***.***> ha
scritto:

**Comment by Stlou16** [comment]
Yes I can get the echelon app to connect and show data.

**Comment by cagnulein** [comment]
that's strange: try to disable the virtual bluetooth setting in the
experimental settings and restart qz

the only difference between the echelon app and qz about bluetooth is the
fact that qz also streams the data over bluetooth.

let me know

Il giorno sab 28 ott 2023 alle 20:15 Stlou16 ***@***.***> ha
scritto:

**Comment by Stlou16** [comment]
Success!! Everything looks good now, data is showing up and not freezing anymore!! Wonderful, thank you so very much!!

**Comment by cagnulein** [comment]
Glad to hear it!

Il giorno sab 28 ott 2023 alle 20:38 Stlou16 ***@***.***> ha
scritto:
