### ISSUE TITLE
[BUG] Nautilus T616 Treadmill not displaying data in tiles

### ISSUE THREAD

**Issue by DoctorMeltdown** [cagnulein/qdomyos-zwift#1740]
**Describe the bug**
Looks as if the Nautilus T616  is detected, but the tiles display is not showing real time values (all zeros).
The QZ chart after the activity is displaying as if it got some values from the treadmill, but tiles showed zeros the whole time, screenshot included.
**Screenshots**
nrf connect screens:
![Screenshot_20231029_194309_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/138611470/6906835b-772e-4087-b3b2-0fb300700526)

![Screenshot_20231029_194352_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/138611470/771c3a53-cac9-40cc-b06a-e50bf16704de)

It looks as if it is getting some kind of data based on the end of activity chart:
![Sun Oct 29 20_13_11 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/138611470/2722c43b-aa13-4d52-b47f-3541e04a26bc)

**Smartphone (please complete the following information):**
 - Samsung S21
 - Android
 - Version (newest?)

**Append a debug log**
[debug-Sun_Oct_29_20_11_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13200192/debug-Sun_Oct_29_20_11_00_2023.log)

**Additional context**
It looks like similar issues have been resolved here:
#1074 
#1383 
#1477

**Comment by cagnulein** [comment]
@DoctorMeltdown yes the communication with the treadmill is perfect. Is it the first time that you're running qz? or other older version worked? also can you please attach a screenshot from a session of the treadmill? i would like to see the tiles on QZ while you're running.
Thanks

**Comment by DoctorMeltdown** [comment]
@cagnulein 
I just tried with my **tablet** with the profile I had made for a treadmill and it works perfect.
I'm not sure what the issue was on my phone.
I'll be out of town starting today, but once I'm back I'll try again with the **phone** and check my settings to see if I can get the tiles to display.

**Comment by cagnulein** [comment]
Sounds good, let me know.

Il giorno lun 30 ott 2023 alle 18:04 DoctorMeltdown <
***@***.***> ha scritto:

**Comment by DoctorMeltdown** [comment]
@cagnulein 
I finally got around to testing with my phone again. I cleared my cache and data from my phone's app and its reading the appropriate data in the tiles now on the S21 phone. Thanks, and sorry for the unnecessary report.
This can be closed.

**Comment by cagnulein** [comment]
no problem @DoctorMeltdown 

remember to rate the app on the store if you didn't already, it means a lot to me!
Thanks!
