### ISSUE TITLE
[BUG] QZ not working correctly with smart spin 

### ISSUE THREAD

**Issue by Dpmiller1986** [cagnulein/qdomyos-zwift#1745]
**Describe the bug**
Connect my echelon connect sport with QZ. Once connected I turn on smart spin. Notification for smart spin to connect to iPad. I usually push pair but have tried not.

Smart spin is connected as an accessory 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Dpmiller1986 Hi, I need a debug log to understand your issue. Thanks

**Comment by cagnulein** [comment]
@Dpmiller1986 any news?
