### ISSUE TITLE
[BUG] Assault bike

### ISSUE THREAD

**Issue by eliasmalek** [cagnulein/qdomyos-zwift#1746]
**Describe the bug**
When I connect to the assault fitness assault bike, once the bike starts moving, the app crashes. 

**To Reproduce**
1. Connect to assault bike 
2. start moving assault bike
3. app crashes

**Expected behavior**
view wattage and cadence data

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 13 pro max
 - OS: iOS 17.1
 - Version: 2.16.13

**Append a debug log**
[debug-Mon_Oct_30_09_22_09_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13207542/debug-Mon_Oct_30_09_22_09_2023.log)
[debug-Mon_Oct_30_09_22_09_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13207543/debug-Mon_Oct_30_09_22_09_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check out tomorrow

Il giorno lun 30 ott 2023 alle 17:33 eliasmalek ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fixed! it will be in the 2.16.21
if you want to try the 15 minutes trial version of qz with the patch without waiting the play store download the android build from here (at the bottom) https://github.com/cagnulein/qdomyos-zwift/actions/runs/6703370284

let me know!

**Comment by cagnulein** [comment]
@eliasmalek any news?

**Comment by eliasmalek** [comment]
Yes! It is working great. Thank you!
