### ISSUE TITLE
Question on ERG mode

### ISSUE THREAD

**Issue by oel59** [cagnulein/qdomyos-zwift#1748]
hi,

I am already using qz for a long time to connect my Domyos 900 to Zwift and I am very happy that it works pretty good.
today I wanted to try the Zwift workout feature which requires ERG mode.

I just changed one setting in QZ, switching Zwift workout/ERG mode on.

Result is, that the resistance on the bike is always staying at position 1 during the workout.

What could be wrong?
thanks for any suggestions.

LEO.

**Comment by cagnulein** [comment]
hi, erg mode is handled for your bike. please attach a debug log with the issue and I will check it
Thanks

**Comment by oel59** [comment]
HI,

Thx for your quick reply.

I actually get it working now. I just did not lower my cadence enough for getting a higher resistance. I have to get used to this different approach. It is fine for now. thanks again.

**Comment by cagnulein** [comment]
Thanks for the feedback!
there is also a different power profile in the domyos setting in qz if you
want to try

Il giorno lun 30 ott 2023 alle 19:13 oel59 ***@***.***> ha
scritto:
