### ISSUE TITLE
[BUG]odometer keeps going when stopped echelon row 

### ISSUE THREAD

**Issue by Dpmiller1986** [cagnulein/qdomyos-zwift#1750]
**Describe the bug**

when qz is paused or I’m not rowing it keeps logging distance.

using the echelon row

I’m also not getting any input from the resistance buttons on echelon row

qz vers 2.16.13
[debug-Mon_Oct_30_18_16_39_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13208584/debug-Mon_Oct_30_18_16_39_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Dpmiller1986 fixed! It was a firmware bug of the rower: it sent speed even if the cadence is 0. Probably ghosts (we are on hallowen so the timing is perfect :D )

Anyway, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by cagnulein** [comment]
@Dpmiller1986 Any news?

**Comment by Dpmiller1986** [comment]
Apologies I haven’t been on the rower for far too long!Sent from my iPhoneOn 23 Nov 2023, at 06:30, Roberto Viola ***@***.***> wrote:﻿
@Dpmiller1986 Any news?
