### ISSUE TITLE
[BUG] Auto resistance not occuring - Echelon EX3, Peloton workout, Fire 10 HD

### ISSUE THREAD

**Issue by Yogitation** [cagnulein/qdomyos-zwift#1751]
**Describe the bug**
I connect QZ on my Fire Tablet 10 HD (9th generation, 2019) to my Echelon EX3 bike. Then I begin a Peloton workout using the app on the same tablet. The bike does not seem to auto adjust resistance.

**To Reproduce**
See above. 

**Expected behavior**
I expected the bike to automatically adjust the resistance based on the workout occurring in the Peloton app.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Amazon Fire HD 10 (9th Generation, 2019)
 - Fire OS 7.3.2.7

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Mon_Oct_30_14_15_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13208671/debug-Mon_Oct_30_14_15_08_2023.log)
[debug-Mon_Oct_30_13_52_09_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13208672/debug-Mon_Oct_30_13_52_09_2023.log)

**Comment by cagnulein** [comment]
thanks i will check it asap, i could be slower than usual since i'm
overwhelmed by tickets

Il giorno lun 30 ott 2023 alle 19:42 Yogitation ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Yogitation in the log the main issue is that you are in pause mode (play button flashing red in qz). Press play and you will have auto resistance.
Let me know!

**Comment by Yogitation** [comment]
@cagnulein Thanks! That worked. I had to enable the display bar (with the Play/Pause and Stop buttons) to get it to work. It doesn't seem to work without that bar. Not a problem because I like seeing the buttons and the title of the workout and the control that the buttons afford. I appreciate the great work on this app and the phenomenal support!

**Comment by cagnulein** [comment]
Glad it worked!


Il giorno mer 1 nov 2023 alle 15:53 Yogitation ***@***.***>
ha scritto:
