### ISSUE TITLE
[BUG] Virtual Echelon bridge: Echeolon bike screen (EX5s) will not connect to QZ attached to device

### ISSUE THREAD

**Issue by nskinner07** [cagnulein/qdomyos-zwift#1752]
I while back echelon changed the way the software and bike screen interacts with the software when using an echelon bike with attached screen.  @cagnulein  had previously fixed this issue for me when I was using Echelon bike (EX5s) connected to QZ on iPhone 6s Plus (ios 15.4).
(Please refer to case #762). This fixed the issues. 

I no longer have access to the  iPhone 6s Plus phone device to bridge QZ/EX5s.  This phone has not been available since late August. 

Current android devices available to connect:
(preferred) Galaxy S9+(called EX5, UI version 2.5, Android 10) 
Galaxy S21+ 5G (called Nicole's S21+, UI version 5.1, Android 13)
I belive virtual echelon is not compatible with the devices I have above.

Only ios device available (least preferred):
iPad Air (3rd generation) (called iPad, iPad ios 17.0.3)

When "virtual bike" is enabled in QZ experimental settings:
- Open QZ app on phone (or iPad), turn bike on.  QZ connects to the bike bluetooth.
-  Echelon bike (EX5s) is connected to QZ on Galaxy S9+(called EX5, UI version 2.5, Android 10) or S21+, or iPad.
- Echelon software (on attached screen) starts to load, displays "available equipment" asks to connect to bike.
User chooses bike  (says available bike EX5 on android phones, or when using iPad ECHEX-5s). Please note with the previous fix using iPhone 6s Plus, the available bike displayed used to end in 399.
- Software may may connect, but then the screen says "getting equipment info"... but does not go further. It will time out.
- I realize that "virtual Echelon" is not compatible with the Android devices I have, but it's the only way I can get the bike to recognize "available equipment".

When "virtual bike" is turned off in QZ experimental settings:
- Open QZ app on phone (or iPad), turn bike on.  QZ connects to the bike bluetooth.
-Echelon bike (EX5s) is connected to QZ on Galaxy S9+(called EX5, UI version 2.5, Android 10) or S21+, or iPad.
- Echelon software (on attached screen) starts to load, displays "available equipment" asks to connect to bike but there is no equipment option to choose. The software will go no further.

When QZ is not running (normal bike functionality):
-turn bike on.
-Bike bluetooth connects to the attached screen. Software loads.
-Echelon software (on attached screen) displays "available equipment" - ECHEX-5s-XXX397 (bike serial number) and auto connects.
- User is able to log into the Echelon app as normal. 

Have tried reproducing/ relaoding software by:
- unplugging/re-plugging in bike
- turning bike off/on
- reset the network setting on S21+ phone.
- using different devices
- ** last time (case #762) I reset the screen software, but I'm unsure how to do this now**

- have restarted the attached bike screen.

-  I have tried my other echelon EX5s bike with older software.

**Smartphone (please complete the following information):**
see above for information on phones/iPad

Echelon EX5s bike:
software version : 2.4.3.4-mounted 137
Tablet Firmware version (attached screen): Z33PM-JST-0-9.0-21.5-SW0.2-3V20210429

QZ version on Android: 2.14.0
QZ version on iPad: 2.15.4

**Append a debug log**
-See attached using 
[debug-Mon_Oct_30_12_13_53_2023.log G9 virtual off.log](https://github.com/cagnulein/qdomyos-zwift/files/13208558/debug-Mon_Oct_30_12_13_53_2023.log.G9.virtual.off.log)
[debug-Mon_Oct_30_12_14_15_2023.log G9 virtual on.log](https://github.com/cagnulein/qdomyos-zwift/files/13208561/debug-Mon_Oct_30_12_14_15_2023.log.G9.virtual.on.log)

G9= Galaxy S9+(called EX5, UI version 2.5, Android 10) 
![Screenshot_20231030-123017](https://github.com/cagnulein/qdomyos-zwift/assets/103256662/dd18191d-46c1-41d3-b4c8-bf7614e46b9b)
![Screenshot_20231030-122943](https://github.com/cagnulein/qdomyos-zwift/assets/103256662/d306e205-c3e2-4e04-8893-190025660c2f)

**Comment by cagnulein** [comment]
thanks i will check it asap. currently i'm overwhelmed by ticket so I could
be slower than usual

Il giorno lun 30 ott 2023 alle 19:44 nskinner07 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i'm checking the log, first observation: virtual bike MUST be on in order to bridge it to the echelon app

**Comment by cagnulein** [comment]
log checked @nskinner07 the main issue is that the echelon app doesn't connect at all to the phone. I guess because the EX5 name is not a valid name for it, try to name your android device like your bike so "ECHEX-5s-111397" and reboot the android device.
Let me know

**Comment by nskinner07** [comment]
@cagnulein I just finished trying multiple variations of the device name (using the Galaxy 9+)  I think the entire serial number is too long.  I tried the entire bike name, then just the last serial number digits, then ECHEX-5s. None of those would be recognized as "available equipment".  The bike was able recognize ECHEX - but that was after an extended period of time.  Even with that, the bike was again unable to get the equipment info.

**Comment by cagnulein** [comment]
i guess that echelon tight the rope in order to restrict access. Are you able at least to try on ios with the right name if it works?

**Comment by nskinner07** [comment]
No luck. The recognized equipment says ECHEX-5s (truncated), but is never able to get the equipment information.  Will you need the debug for the iPad?  I need my partnes fingerprint to download - and they're out for the day.

**Comment by cagnulein** [comment]
> Will you need the debug for the iPad? I need my partnes fingerprint to download - and they're out for the day.

Yes it would be useful, I would like to see if on the ipad we got a connection at least.
Thanks

**Comment by nskinner07** [comment]
@cagnulein 
[debug-Tue_Oct_31_09_04_32_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13220543/debug-Tue_Oct_31_09_04_32_2023.log.txt)
[debug-Tue_Oct_31_12_59_59_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13220545/debug-Tue_Oct_31_12_59_59_2023.log.txt)

**Comment by cagnulein** [comment]
thanks i will try to check it tomorrow

Il giorno mar 31 ott 2023 alle 20:13 nskinner07 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@nskinner07 checked. Unfortunately I can't see any connection at all indeed. I will try to do a test on my own, never installed the echelon app in my life :D

**Comment by cagnulein** [comment]
I will probably be able to test something next week

**Comment by cagnulein** [comment]
argh it seems I need a valid serial number of a echelon device to create an account :( if you can share somehow your account, changing your password, I can test it. Thanks

**Comment by nskinner07** [comment]
@cagnulein I have sent you an email to roberto.viola83 at gmail.com.

**Comment by cagnulein** [comment]
good / bad news is that I'm seeing the same error too. The fact is that with my android I can't even see my echex device on nrfconnect on my iphone (advertising error). That's very strange! @nskinner07 when was the last time you tried this configuration and it worked?

I will test it but not sooner than this Wed. due to important stuff on my main job :(

**Comment by nskinner07** [comment]
@cagnulein - it's been a long time.  Before the major update to the echelon app April 2022. When that update occured, none of my devices would connect, but I was mostly using an iPhone 6 for QZ. You got that running with my last case. I just don't have access to that device any longer.

**Comment by cagnulein** [comment]
ok thanks for this detail. i do have an iphone 6 and a 5s that I can try
just to check if it's about something on ios too but i don't think so.

I will keep you updated

Il giorno dom 5 nov 2023 alle 17:15 nskinner07 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I did a first test today: Mac with QZ and Echelon app on my iphone.
Everything was fine. Next step is trying ios to ios device, and then
android to ios and viceversa.
I will keep you posted

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 5 nov 2023 alle ore 17:19 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@nskinner07 ios to ios works flawlessy here, i tried iphone 6 to iphone 13 and also ipad to iphone 13. Can you show me what do you see on nrfconnect on the echelon device when you have qz open on the other device?

**Comment by nskinner07** [comment]
I have no idea if I've done this correctly or not...



Samsung S21 running QZ attached to bike.

nRF Connect, 2023-11-09
ECHEX-5s (5D:23:89:8B:14:BA)
V 21:57:07.852 Connecting to 5D:23:89:8B:14:BA...
D 21:57:07.852 gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE,
preferred PHY = LE 1M)
D 21:57:08.652 [Callback] Connection state changed with status: 0 and new
state: CONNECTED (2)
I 21:57:08.652 Connected to 5D:23:89:8B:14:BA
D 21:57:08.664 [Broadcast] Action received:
android.bluetooth.device.action.ACL_CONNECTED
D 21:57:08.684 wait(1600ms)
I 21:57:09.590 PHY updated (TX: LE 2M, RX: LE 2M)
I 21:57:10.188 Connection parameters updated (interval: 7.5ms, latency: 0,
timeout: 5000ms)
V 21:57:10.299 Discovering services...
D 21:57:10.299 gatt.discoverServices()
D 21:57:10.975 [Callback] Services discovered with status: 0
I 21:57:10.975 Services discovered
V 21:57:11.012 Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- Manufacturer Name String [R] (0x2A29)
- Model Number String [R] (0x2A24)
Apple Continuity Service (d0611e78-bbb4-4591-a5f8-487910ae4366)
- Continuity [E N W] (8667556c-9a37-4c91-84ed-54ee27d90049)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
Apple Nearby Service (9fa480e0-4967-4542-9390-d343dc5d04ae)
- Nearby [E N W] (af0badb1-5b99-43cd-917a-a77bc549e3cc)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
Battery Service (0x180F)
- Battery Level [N R] (0x2A19)
   Client Characteristic Configuration (0x2902)
Current Time Service (0x1805)
- Current Time [N R] (0x2A2B)
   Client Characteristic Configuration (0x2902)
- Local Time Information [R] (0x2A0F)
Apple Notification Center Service (7905f431-b5ce-4e99-a40f-4b1e122d00d0)
- Control Point [E W] (69d1d8f3-45e1-49a8-9821-9bbdfdaad9d9)
   Characteristic Extended Properties (0x2900)
- Notification Source [N] (9fbf120d-6301-42d9-8c58-25e699a21dbd)
   Client Characteristic Configuration (0x2902)
- Data Source [N] (22eac6e9-24d6-4bb5-be44-b36ace7c7bfb)
   Client Characteristic Configuration (0x2902)
Apple Media Service (89d3502b-0f36-433a-8ef4-c502ad55f8dc)
- Remote Command [E N W] (9b3c81d8-57b1-4a8a-b8df-0e56f7ca51c2)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
- Entity Update [E N W] (2f7cabce-808d-411f-9a0c-bb92ba96c102)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
- Entity Attribute [E R W] (c6b2f38c-23ab-46d8-a6ab-a3a870bbd5d7)
   Characteristic Extended Properties (0x2900)
D 21:57:11.012
gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb,
true)
D 21:57:11.014
gatt.setCharacteristicNotification(8667556c-9a37-4c91-84ed-54ee27d90049,
true)
D 21:57:11.015
gatt.setCharacteristicNotification(af0badb1-5b99-43cd-917a-a77bc549e3cc,
true)
D 21:57:11.017
gatt.setCharacteristicNotification(00002a19-0000-1000-8000-00805f9b34fb,
true)
D 21:57:11.017
gatt.setCharacteristicNotification(00002a2b-0000-1000-8000-00805f9b34fb,
true)
D 21:57:11.018
gatt.setCharacteristicNotification(9fbf120d-6301-42d9-8c58-25e699a21dbd,
true)
D 21:57:11.020
gatt.setCharacteristicNotification(22eac6e9-24d6-4bb5-be44-b36ace7c7bfb,
true)
D 21:57:11.021
gatt.setCharacteristicNotification(9b3c81d8-57b1-4a8a-b8df-0e56f7ca51c2,
true)
D 21:57:11.022
gatt.setCharacteristicNotification(2f7cabce-808d-411f-9a0c-bb92ba96c102,
true)
I 21:57:11.069 Connection parameters updated (interval: 48.75ms, latency:
0, timeout: 5000ms)
V 21:57:25.653 Reading all characteristics...
V 21:57:25.653 Reading characteristic 00002a00-0000-1000-8000-00805f9b34fb
D 21:57:25.653 gatt.readCharacteristic(00002a00-0000-1000-8000-00805f9b34fb)
I 21:57:25.744 Read Response received from
00002a00-0000-1000-8000-00805f9b34fb, value: (0x) 45-43-48-45-58-2D-35-73,
"ECHEX-5s"
A 21:57:25.744 "ECHEX-5s" received
V 21:57:25.754 Reading characteristic 00002a01-0000-1000-8000-00805f9b34fb
D 21:57:25.754 gatt.readCharacteristic(00002a01-0000-1000-8000-00805f9b34fb)
I 21:57:25.839 Read Response received from
00002a01-0000-1000-8000-00805f9b34fb, value: (0x) 80-02
A 21:57:25.839 "[640] Generic Media Player (Generic category)" received
V 21:57:25.846 Reading characteristic 00002a29-0000-1000-8000-00805f9b34fb
D 21:57:25.846 gatt.readCharacteristic(00002a29-0000-1000-8000-00805f9b34fb)
I 21:57:25.936 Read Response received from
00002a29-0000-1000-8000-00805f9b34fb, value: (0x)
41-70-70-6C-65-20-49-6E-63-2E, "Apple Inc."
A 21:57:25.936 "Apple Inc." received
V 21:57:25.943 Reading characteristic 00002a24-0000-1000-8000-00805f9b34fb
D 21:57:25.943 gatt.readCharacteristic(00002a24-0000-1000-8000-00805f9b34fb)
I 21:57:26.033 Read Response received from
00002a24-0000-1000-8000-00805f9b34fb, value: (0x) 69-50-61-64-31-31-2C-33,
"iPad11,3"
A 21:57:26.033 "iPad11,3" received
V 21:57:26.040 Reading characteristic 00002a19-0000-1000-8000-00805f9b34fb
D 21:57:26.040 gatt.readCharacteristic(00002a19-0000-1000-8000-00805f9b34fb)
I 21:57:26.182 Read Response received from
00002a19-0000-1000-8000-00805f9b34fb, value: (0x) 31, "1"
A 21:57:26.182 "49%" received
V 21:57:26.192 Reading characteristic 00002a2b-0000-1000-8000-00805f9b34fb
D 21:57:26.193 gatt.readCharacteristic(00002a2b-0000-1000-8000-00805f9b34fb)
I 21:57:26.376 Read Response received from
00002a2b-0000-1000-8000-00805f9b34fb, value: (0x)
E7-07-0B-09-15-39-18-04-9A-02
A 21:57:26.376 "9 Nov 2023, 21:57:24, Day of week: Thursday
Fractions: 154 / 256 s
External reference time update" received
V 21:57:26.384 Reading characteristic 00002a0f-0000-1000-8000-00805f9b34fb
D 21:57:26.384 gatt.readCharacteristic(00002a0f-0000-1000-8000-00805f9b34fb)
I 21:57:26.571 Read Response received from
00002a0f-0000-1000-8000-00805f9b34fb, value: (0x) E4-00
A 21:57:26.571 "Time Zone: UTC+57:0, Standard Time" received
V 21:57:26.581 Reading characteristic c6b2f38c-23ab-46d8-a6ab-a3a870bbd5d7
D 21:57:26.581 gatt.readCharacteristic(c6b2f38c-23ab-46d8-a6ab-a3a870bbd5d7)
E 21:57:26.667 Error 160 (0xa0): UNKNOWN (160)
V 21:57:26.668 8 characteristics read

S9 with QZ attached to bike

nRF Connect, 2023-11-09
ECHEX-5s (5D:23:89:8B:14:BA)
V 22:17:20.631 Connecting to 5D:23:89:8B:14:BA...
D 22:17:20.631 gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE,
preferred PHY = LE 1M)
D 22:17:21.418 [Callback] Connection state changed with status: 0 and new
state: CONNECTED (2)
I 22:17:21.418 Connected to 5D:23:89:8B:14:BA
D 22:17:21.419 wait(1600ms)
D 22:17:21.420 [Broadcast] Action received:
android.bluetooth.device.action.ACL_CONNECTED
I 22:17:21.918 Connection parameters updated (interval: 7.5ms, latency: 0,
timeout: 5000ms)
I 22:17:22.028 PHY updated (TX: LE 2M, RX: LE 2M)
I 22:17:23.022 Connection parameters updated (interval: 48.75ms, latency:
0, timeout: 5000ms)
V 22:17:23.038 Discovering services...
D 22:17:23.039 gatt.discoverServices()
D 22:17:23.065 [Callback] Services discovered with status: 0
I 22:17:23.065 Services discovered
V 22:17:23.098 Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
   Client Characteristic Configuration (0x2902)
Device Information (0x180A)
- Manufacturer Name String [R] (0x2A29)
- Model Number String [R] (0x2A24)
Apple Continuity Service (d0611e78-bbb4-4591-a5f8-487910ae4366)
- Continuity [E N W] (8667556c-9a37-4c91-84ed-54ee27d90049)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
Apple Nearby Service (9fa480e0-4967-4542-9390-d343dc5d04ae)
- Nearby [E N W] (af0badb1-5b99-43cd-917a-a77bc549e3cc)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
Battery Service (0x180F)
- Battery Level [N R] (0x2A19)
   Client Characteristic Configuration (0x2902)
Current Time Service (0x1805)
- Current Time [N R] (0x2A2B)
   Client Characteristic Configuration (0x2902)
- Local Time Information [R] (0x2A0F)
Apple Notification Center Service (7905f431-b5ce-4e99-a40f-4b1e122d00d0)
- Control Point [E W] (69d1d8f3-45e1-49a8-9821-9bbdfdaad9d9)
   Characteristic Extended Properties (0x2900)
- Notification Source [N] (9fbf120d-6301-42d9-8c58-25e699a21dbd)
   Client Characteristic Configuration (0x2902)
- Data Source [N] (22eac6e9-24d6-4bb5-be44-b36ace7c7bfb)
   Client Characteristic Configuration (0x2902)
Apple Media Service (89d3502b-0f36-433a-8ef4-c502ad55f8dc)
- Remote Command [E N W] (9b3c81d8-57b1-4a8a-b8df-0e56f7ca51c2)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
- Entity Update [E N W] (2f7cabce-808d-411f-9a0c-bb92ba96c102)
   Characteristic Extended Properties (0x2900)
   Client Characteristic Configuration (0x2902)
- Entity Attribute [E R W] (c6b2f38c-23ab-46d8-a6ab-a3a870bbd5d7)
   Characteristic Extended Properties (0x2900)
D 22:17:23.099
gatt.setCharacteristicNotification(00002a05-0000-1000-8000-00805f9b34fb,
true)
D 22:17:23.101
gatt.setCharacteristicNotification(8667556c-9a37-4c91-84ed-54ee27d90049,
true)
D 22:17:23.103
gatt.setCharacteristicNotification(af0badb1-5b99-43cd-917a-a77bc549e3cc,
true)
D 22:17:23.103
gatt.setCharacteristicNotification(00002a19-0000-1000-8000-00805f9b34fb,
true)
D 22:17:23.104
gatt.setCharacteristicNotification(00002a2b-0000-1000-8000-00805f9b34fb,
true)
D 22:17:23.105
gatt.setCharacteristicNotification(9fbf120d-6301-42d9-8c58-25e699a21dbd,
true)
D 22:17:23.106
gatt.setCharacteristicNotification(22eac6e9-24d6-4bb5-be44-b36ace7c7bfb,
true)
D 22:17:23.107
gatt.setCharacteristicNotification(9b3c81d8-57b1-4a8a-b8df-0e56f7ca51c2,
true)
D 22:17:23.108
gatt.setCharacteristicNotification(2f7cabce-808d-411f-9a0c-bb92ba96c102,
true)
D 22:17:53.271 [Callback] Connection state changed with status: 19 and new
state: DISCONNECTED (0)
W 22:17:53.272 Connection terminated by peer (status 19)
I 22:17:53.272 Disconnected
D 22:17:53.318 [Broadcast] Action received:
android.bluetooth.device.action.ACL_DISCONNECTED

-Nicole

**Comment by cagnulein** [comment]
nope unfortunately, let me explain better what I would like to see.
First of all, let's try first qz running on ios. Since i only tested with it, it's better to start from this scenario if you can.

So open qz and check that it's correctly connected to the bike.

Then from another device (even an android one), open nrfconnect and you should see the ios device running QZ called ECHEX-5s-113399

Send me the screenshot about this (the screnshoot is better than the log so I can have a full overview): screenshot of the main page of nrfconnect showing all the devices including the ECHEX and also a screenshot when you are clicking connect on the echex device of its client characteristics

Let me know

**Comment by nskinner07** [comment]
iOS (iPad) connected to QZ.

**Comment by cagnulein** [comment]
@nskinner07 i can't see any images

**Comment by nskinner07** [comment]
Trying this
https://drive.google.com/drive/folders/13GTA0Gs5fO6Kj6PSlmCP38O9r-Rc2Ltv

**Comment by cagnulein** [comment]
@nskinner07 i checked and it's the same as mine. did you already try ios to ios? in this scenario must work on ios to ios.
i will test on android asap (busy days here :( )

**Comment by nskinner07** [comment]
I don't have another iOs device:(

**Comment by cagnulein** [comment]
ok no problem i will investigate further

Il giorno ven 10 nov 2023 alle 21:04 nskinner07 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I didn'f forget about this, I'm just busy :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 10 nov 2023 alle ore 21:08 cagnulein ***@***.***> ha
scritto:

**Comment by nskinner07** [comment]
Hi @cagnulein - no worries about this case, you can close it.  I purchased aother used iPhone 6S and got things up and running.  I have another question for you that I will pose in the facebook group.

**Comment by cagnulein** [comment]
Glad to hear it!
I will try to check it anyway, I’m just in short of time lately :(

Il giorno lun 11 dic 2023 alle 19:43 nskinner07 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mickllf got it i guess, disable the ios_peloton_workaround in the experimental settings and restart qz. let me know

**Comment by cagnulein** [comment]
great @mickllf yes HR is not supported from the virtual bridge (i'm sending it but echelon app doesn't use it). You have to use the HR directly in the echelon app if you would like to see it there

**Comment by mickllf** [comment]
That’s a shame.

So if I want my HR to show in echelon I need to use their app, but then I
won’t get the full reporting from your app….

I’m assuming your app keeps the HR info and sends that into Apple fitness
and Strava?

**Comment by cagnulein** [comment]
> I’m assuming your app keeps the HR info and sends that into Apple fitness and Strava?

yes! you shouldn't use the echelon app to track metrics, just use qz for this purpose :)
