### ISSUE TITLE
[BUG] unable to control resistance on echelon row

### ISSUE THREAD

**Issue by Dpmiller1986** [cagnulein/qdomyos-zwift#1753]
**Describe the bug**
Can’t control the buttons on the echelon rower. Pace is coming through 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks, are you able to test a solution on windows? it could be faster for
me to check if the rower allow this
Let me know

Il giorno lun 30 ott 2023 alle 20:14 Dpmiller1986 ***@***.***>
ha scritto:

**Comment by Dpmiller1986** [comment]
I can certainly try. I don’t have an amazing laptop though so I might struggle

**Comment by cagnulein** [comment]
a cheap laptop is enough, it has to have only bluetooth

i will prepare a test version asap

Il giorno lun 30 ott 2023 alle 20:17 Dpmiller1986 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Dpmiller1986 windows build ready https://github.com/cagnulein/qdomyos-zwift/suites/17774148807/artifacts/1018475268

WARNING: this version will try automatically to find a way to change the resistance on the rower, so don't use it for your workout.
What you have to do is:
run it and check if you see the metrics. Leave it running for 10 minutes and check if the resistance changed randomly, if so we have an hit!

Let me know

**Comment by cagnulein** [comment]
@Dpmiller1986 any news?

**Comment by cagnulein** [comment]
@scottmoserhenderson thanks, could you please share the debug log of this test? is the qz default app working ok instead, right?

**Comment by cagnulein** [comment]
for the pace issue, create a new ticket with a debug log and I will check it

for the freeze of this is strange. aren't you able to turn off your rower,
enable the debug log in qz, and test it again? in this way we should have
the debug log

let me know

Il giorno lun 11 dic 2023 alle 17:24 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
lol perfect i will check it asap

Il giorno lun 11 dic 2023 alle 17:28 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Hah ok,so that’s why maybe

Il giorno lun 11 dic 2023 alle 20:38 Scott Henderson <
***@***.***> ha scritto:
