### ISSUE TITLE
[REQ] Speed/Incline support for ProForm Pro 1000 Treadmill

### ISSUE THREAD

**Issue by anthony-barclay** [cagnulein/qdomyos-zwift#1755]
Speed/Incline support is currently not working for ProForm Pro 1000 Treadmill

As well as being able to see the current incline/speed etc. I would like to be able to control them from the app

Attached is the Android bug report including USB HCI snoop info taken while running an iFit workout containing both speed and incline changes. It was too big to attach so I have split it in to two parts.

[bugreport_part2.zip](https://github.com/cagnulein/qdomyos-zwift/files/13215741/bugreport_part2.zip)
[bugreport_part1.zip](https://github.com/cagnulein/qdomyos-zwift/files/13215743/bugreport_part1.zip)

**Comment by anthony-barclay** [comment]
It case it makes for easier testing / debugging - I have access to various Linux boxes so can build from source and test using that

**Comment by cagnulein** [comment]
thanks I will check ASAP (i'm currently overwhelmed by ticket :( )

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 31 ott 2023 alle ore 13:11 anthony-barclay <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/13218799/btsnoop_hci.zip)
ok for my reference, this is the one I was looking for. Let me check it

**Comment by cagnulein** [comment]
done @anthony-barclay 

if you want you can test already the 15 minutes trial of qz downloading it from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/6709575773 (at the bottom) when the build will finish.

I added a new setting for your treadmill in the proform settings, enable it and disable all the others

let me know
it will be in the 2.16.22 in the play store

**Comment by anthony-barclay** [comment]
I've tried that android test build and it's producing some interesting results. The tiles no longer show values for speed/incline etc. and I have confirmed if I switch back to NordicTrack 10 it then works. When it comes to settings values, if I press the buttons on the speed tile 5-6 times then it makes a difference, but it seems to jump around the speeds i.e. it goes from 3.0 to 1.5 when I press + a few times, then the next time it might go to 2.0 so I'm guessing there's some odd maths they are doing for what needs to be sent. Incline worked once then didn't seem to work again so not sure if there's something similar there. Let me know if there's anything I can do to produce any more useful info / debug traces etc.

**Comment by cagnulein** [comment]
hi, maybe i did something wrong in the poll side. yes if you could please
attach a debug log with the new setting I will check it.

the control oddity is about to the fact that you don't see the metrics, so
once we fix this we will have full control

let me know

Il giorno mar 31 ott 2023 alle 18:24 anthony-barclay <
***@***.***> ha scritto:

**Comment by anthony-barclay** [comment]
Ah, that makes sense. Here are the logs from the new version.
________________________________

**Comment by cagnulein** [comment]
you have to attach them from the Github interface directly otherwise I can't see them ;)

**Comment by anthony-barclay** [comment]
Here you go - you'd never guess I use Azure DevOps not Github :)

[debug-Tue_Oct_31_18_02_13_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13220328/debug-Tue_Oct_31_18_02_13_2023.log)

**Comment by cagnulein** [comment]
Haha, thanks!
I will check tomorrow

Il giorno mar 31 ott 2023 alle 19:45 anthony-barclay <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@anthony-barclay I guess I fixed it https://github.com/cagnulein/qdomyos-zwift/actions/runs/6718739790

Let me know

**Comment by anthony-barclay** [comment]
That's done it :) Thank you so much.

**Comment by cagnulein** [comment]
great! i will push it to the android store asap!

Il giorno mer 1 nov 2023 alle 14:05 anthony-barclay <
***@***.***> ha scritto:
