### ISSUE TITLE
NordicTrack C1750 - iOS - No Incline Control/Control from app

### ISSUE THREAD

**Issue by Sephzer** [cagnulein/qdomyos-zwift#1756]
I have a NordicTrack C1750 with the companion app installed as of 30/10/23. The setup works well in general and I can control Zwift running via the app.

A few points to note that need investigating.

1. Admin access is not sticking on reboot, not sure whether this is down to constant updates from iFIT everytime I rebooted (I did NOT install the app on the default image that comes with the Treadmill as it updated too quickly for me to do so).
2. I cannot control the treadmill from the companion app (not sure if this is expected). If I try and increase the speed or incline, I have to do this on the treadmill itself.
3. Automatic incline adjust is not working on any app, such as Zwift. I did a quick run test this morning, go to a 1% incline and nothing happened.

Happy to gather whatever data you need, am technically inclined so I am not new at this kind of thing.

Also, I installed the companion app via the tinyurl link in the guide, rather than the ADB method. Happy to try this method as well to see if it makes any kind of a difference. C1750 is also listed in the app.

**Comment by cagnulein** [comment]
ok @Sephzer let's check first the control ability of this treadmill

update the companion with this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/suites/17785090787/artifacts/1019145304

then in the developer setting of the treadmill, enable the touch setting that shows a shadow when you touch the screen.
Reboot the device and let's check that you see the shadow with your fingers

If so, open qz check if you are still seeing the metrics from the treadmill, and then try to press the plus button of the incline and/or the speed tile. If pressing it, you see a reaction on the touchscreen we have a hit and we can continue on this way

let me know!

**Comment by Sephzer** [comment]
@cagnulein so I tried the apk, it tried to install and then said app not installed... very strange. But then there was the usual dot on the app to say it had been updated.

I enabled the touch setting like you said and that persisted on reboot, still locked out of admin mode each time but it's a non-issue really. I can still see the metrics in the app on my phone, so that is working fine however tapping the buttons does nothing. I am guessing you map the action on my phone to a finger press somewhere on the treadmill screen? Not sure how this would work as there is no where to increase speed/inclination etc on the touchscreen itself, it's done on the physical buttons below (forgive me if that isn't the case though).

**Comment by cagnulein** [comment]
> so I tried the apk, it tried to install and then said app not installed... very strange. But then there was the usual dot on the app to say it had been updated.

because you have to uninstall the previous one and install the new one (the signature changes every time in github CI)



> I enabled the touch setting like you said and that persisted on reboot, still locked out of admin mode each time but it's a non-issue really

so you can see the shadow when you press with the fingers?



> I can still see the metrics in the app on my phone, so that is working fine however tapping the buttons does nothing

maybe it's because you didn't update the apk or because it's not working. let's try with the uninstall/install process and redo this



> . I am guessing you map the action on my phone to a finger press somewhere on the treadmill screen? Not sure how this would work as there is no where to increase speed/inclination etc on the touchscreen itself, it's done on the physical buttons below (forgive me if that isn't the case though).

Yes qz in order to control the incline and the speed it simulates the touch on the manual workout window on ifit

**Comment by Sephzer** [comment]
Thanks for the explanation.

Uninstalled and tried this again, no change really. I do see the the app pop-up on the treadmill before iFIT is started now which is a plus. I have C1750 selected (though there is an older version of this model). I can still see the stats on my phone, however it now says 'connecting' at the top. I don't remember seeing that before.

Also still have to enter admin mode manually everytime, so no change there either.

Still can't use any of the buttons in the app, when I press on something I can't see anything being pressed on the treadmill.

Cheers.

**Comment by cagnulein** [comment]
> I can still see the stats on my phone, however it now says 'connecting' at the top. I don't remember seeing that before.

yes that's right. That label is about bluetooth devices only.

> Still can't use any of the buttons in the app, when I press on something I can't see anything being pressed on the treadmill.

ok so we have to test it via adb.

are you able to test the adb connection somehow? do you have a pc or a mac?

**Comment by Sephzer** [comment]
Yeah I can test adb, let me give that a shot. I'm on Windows but have access to a mac if need be, or linux or whatever we need.

**Comment by cagnulein** [comment]
ok so download this on windows https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/tags/3.3.8.zip

and inside the installpackage folder try to run the adb-debug.bat file

let me know

**Comment by Sephzer** [comment]
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13224722/logcat.txt)
[QZ-Companion-log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13224724/QZ-Companion-log.txt)
[dumpsys.log](https://github.com/cagnulein/qdomyos-zwift/files/13224725/dumpsys.log)
[2023-11-01_logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/13224728/2023-11-01_logs.txt)

Uploaded log files, re-installed the app via ADB. I now get persistent admin mode so that's a plus, still suffering the same issues however. I noticed now that when I try to push something on my phone app, it tends to change screen on my treadmill and then it shows the android bar at the top, with the wifi info and what apps are running etc.

Let me know if there's anything else you need.

Important to note that I set the treadmill to C1750 in the app, not 'other'.

**Comment by cagnulein** [comment]
> I noticed now that when I try to push something on my phone app, it tends to change screen on my treadmill and then it shows the android bar at the top

wait so when you press on the plus button on the phone you're seeing some touch event on the tablet? if so we got an hit!

**Comment by Sephzer** [comment]
Just double checked.

- started manual mode
- opened the app on my phone
- walked for 2 mins without pressing anything
- clicked increase speed on my phone constantly (nothing happened on the treadmill or treadmill screen)
- clicked increase gradient on my phone constantly - after some rapid presses, I can confirm that the treadmill screen changes to a different stat page and then shows the android bar at the top. So yes, I'd say this was a hit :). I can't see the shadow as in something being 'pressed' but it definitely reacts to a button press on my phone so we have progress! :)

**Comment by cagnulein** [comment]
ok perfect so now we have only to calibrate the screen!

on the qzcompanion zip there is a https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat file

if you run it from your pc and stay on the Manual workout window on your tablet you should collect a screenshot of your tablet so I can grab the coordinates!

Let me know!

**Comment by Sephzer** [comment]
Where does the .bat file place the screenshot? It just runs and then disappears. I can't find any .png in the log directories.

**Comment by cagnulein** [comment]
@Sephzer should be %SAVESTAMP%.png (so the date.png)

run the batch from a prompt so you will see the errors in case

**Comment by Sephzer** [comment]
![02-11-2023@9-20-52 14](https://github.com/cagnulein/qdomyos-zwift/assets/3299596/bffec9b1-615c-4548-94f6-32e33032d2c4)

So I couldn't get this to work, I had to make some changes to your .bat file. By default I was getting the following error.

adb.exe: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
adb.exe: no devices/emulators found

I changed the .bat to read as follows and then it worked.

::assumes android treadmill usb debugging is turned on 

@echo off

set /p TMIP="Enter treadmill IP address: "

ping %TMIP%
timeout 5

adb disconnect
adb kill-server
adb connect %TMIP%
adb devices -l
timeout 5

set SAVESTAMP=%DATE:/=-%@%TIME::=-%
set SAVESTAMP=%SAVESTAMP: =%

adb shell screencap -p /sdcard/%SAVESTAMP%.png

adb pull /sdcard/%SAVESTAMP%.png
adb shell rm /sdcard/%SAVESTAMP%.png

**Comment by cagnulein** [comment]
great! can you do a PR in the repo about this? I'm checking the screenshot now

**Comment by Sephzer** [comment]
> great! can you do a PR in the repo about this? I'm checking the screenshot now

Can do, need more info on the repo version though. Not obvious when I had a look and also I'm not used to github so this will be a first for me.

Good luck with the screenshot :)

**Comment by cagnulein** [comment]
> Can do, need more info on the repo version though. Not obvious when I had a look and also I'm not used to github so this will be a first for me.

just edit on github directly creating a fork, it's very easy!

i'm building the new companion version!

**Comment by cagnulein** [comment]
here you go https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.9/QZCompanionNordictrackTreadmill.apk

**Comment by Sephzer** [comment]
> here you go https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.9/QZCompanionNordictrackTreadmill.apk

Just to confirm, you want me to install this and give it a test run? Did't think you'd be making changes quite so quickly... hah.

**Comment by cagnulein** [comment]
yes, i'm fast :)

**Comment by Sephzer** [comment]
Will give it a shot, can this be pushed by adb again? As it's not a zip. Based on previous experience, installing via google drive or something similar causes issues, as admin mode doesn't stay unlocked etc. I will still give it a shot in the meantime.

**Comment by cagnulein** [comment]
> can this be pushed by adb again?

yes sure, you can both way, the way that you like more :)

**Comment by Sephzer** [comment]
Ok so we have some good news and some bad news.

The good news, I can now control the gradient of the machine :) and the precision seems to be accurate. I turned on the pointer mode as well as shadows so after it's 'pressed' the location stays on screen for me to see.

The bad news, no presses are being registered at all when I try and change the speed of the machine in the app. Not sure why.

Progress is progress though :)

Question now is, should I test something like Zwift to see if auto-changes the gradient? I'm less concerned about speed but it would be nice to get that sorted as well. I have a run planned for this evening thankfully but I can continue to tinker whilst working my day job.

**Comment by cagnulein** [comment]
> The good news, I can now control the gradient of the machine :) and the precision seems to be accurate. I turned on the pointer mode as well as shadows so after it's 'pressed' the location stays on screen for me to see.

wow! i'm fast and accurate so :D



> The bad news, no presses are being registered at all when I try and change the speed of the machine in the app. Not sure why.

can you provide me a debug log from qz while you're trying this?



> Question now is, should I test something like Zwift to see if auto-changes the gradient? I'm less concerned about speed but it would be nice to get that sorted as well. I have a run planned for this evening thankfully but I can continue to tinker whilst working my day job.

check this https://github.com/cagnulein/qdomyos-zwift/wiki/Controlling-Treadmill-Incline-Speed-following-Peloton-Class
Then so, you can use auto incline with the meetup trick ;) or if you want we can try to setup the windows version of qz to have the full support without the meetup trick ;)

**Comment by Sephzer** [comment]
Is that the right link? It will be different for Zwift though as I've already tried it in the past. It connects just fine but I'll give it another shot.

Sure I can grab you another debug log, do you want me to run it after I've tried? Can't do it any other time really as my machine is in another room. Guessing it will just capture the session.

Will let you know how I get on. Should probably do some work of my own now.... :)

**Comment by cagnulein** [comment]
> Is that the right link? It will be different for Zwift though as I've already tried it in the past. It connects just fine but I'll give it another shot.

sorry, it's not https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F



> Sure I can grab you another debug log, do you want me to run it after I've tried?

i mean this kind of log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Sephzer** [comment]
Cheers, will get you the logs a bit later today and I'll experiment with Zwift this evening using the meetup trick. If I'm having issues I'll see if I can use Windows instead.

**Comment by cagnulein** [comment]
Sounds like a plan!

**Comment by Sephzer** [comment]
Just checked out the video, unfortunately, that means I'd have to start paying for Zwift again as it's free for runners (which was the whole point of me checking this out hah). If you need to start on a bike then it's a no go for me at the moment.

Will give Windows a shot though :)

**Comment by cagnulein** [comment]
nope you don't! you can use the free bike km (25) to create as many meetup you want! (because you're not using kms in zwift for this!)

**Comment by Sephzer** [comment]
True but I already have an account :) so I don't have any free km's anymore as I used to cycle as well.

**Comment by Sephzer** [comment]
Suppose I could create a 'running only' account though... I have options at least. Thanks for pointing this out.

**Comment by cagnulein** [comment]
> True but I already have an account :) so I don't have any free km's anymore as I used to cycle as well.

no! you have every months! they are resetting every months :)

**Comment by Sephzer** [comment]
oh that's news to me! nice, in which case... here I go! :)

**Comment by Sephzer** [comment]
[debug-Thu_Nov_2_13_32_23_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13239400/debug-Thu_Nov_2_13_32_23_2023.log)

Debug log attached.

- started by increasing the gradient twice
- decreased the gradient twice
- increased the speed 10 times (nothing happened)

**Comment by cagnulein** [comment]
@Sephzer thanks, from the qz side everything is perfect. Ok let's investigate on the companion side. Could you please, after pressing 2-3 times the plus speed button on your iphone, press the dump log button on the companion and send me a picture of the textbox with the log?

**Comment by Sephzer** [comment]
@cagnulein can do :)

Also, I've managed to test Zwift.... I am totally working today hah. Few points.

- Using the meetup function worked perfectly, though the wahoo virtual devices didn't appear until my second attempt, but that's fine
- Gradient was adjusted automatically, I remember you saying that this is based on what is sent from Zwift so the Zwift % and the app % will differ
- Speed worked when I adjusted it manually on the treadmill itself, still can't do this from the app as expected
- Cadence doesn't work for me, not sure what I need to do here or if I even want it, but happy to take a look at this as well
- Yet to try my heart rate monitor/iWatch but lets concentrate on this first, and I can open other tickets if necessary

Thanks for the hard work so far! :)

**Comment by cagnulein** [comment]
> * Gradient was adjusted automatically, I remember you saying that this is based on what is sent from Zwift so the Zwift % and the app % will differ

yes exactly, zwift shows in the UI an average but it sends the actual one

> * Cadence doesn't work for me, not sure what I need to do here or if I even want it, but happy to take a look at this as well

you need to use the QZ app on the Apple Watch for this as well

**Comment by cagnulein** [comment]
interesting @Sephzer i added some debug log to the companion in a new version https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.10/QZCompanionNordictrackTreadmill.apk

could you try the same test? it will not fix anything, it will just log everything better in the logcat file, thanks!

**Comment by Sephzer** [comment]
[logcat2.log](https://github.com/cagnulein/qdomyos-zwift/files/13241930/logcat2.log)

done :)

**Comment by cagnulein** [comment]
@Sephzer fixed https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.11/QZCompanionNordictrackTreadmill.apk !

Let me know

**Comment by cagnulein** [comment]
@Sephzer great! could you identify "a lot"? i mean 1km/h? 10km/h?
share me a logcat and I will understand which is the issue :)
I'm going home now, I will check this again tomorrow! Thanks

P.S. let me know if tonight will do a zwift session, I will watch you (i'm R.Viola on zwift, add me as a friend ;) )

**Comment by Sephzer** [comment]
Yeah no worries no rush on getting any of this done.

Will grab you another logcat file. I'll do another test, but I'm pretty sure I went from 2.0km/h to 4.7km/w and then if I tried to decrease it it shot up to 12.xkm/h. 

Sure we'll sort it, and yeah no problem I'll add you. Not sure what time exactly but planning to do at least 10km.

**Comment by Sephzer** [comment]
Will do a speed test in the morning and will grab log files.

Now onto the Zwift test!

- Had to reboot the treadmill to get it to work this time, first time failed. I suspect sleep mode is to blame on the treadmill
- HR monitor didn't work from my iWatch however cadence did, not  big issue as I could use an external one
- Gradient worked, however I noticed a few things
     - It would only ever go to -1% even though my treadmill supports -3% and Zwift was reporting -2% and below. 
     - This I suspect is down to the virtual Wahoo Tread which probably only supports 1% but just a guess, not a big issue
     - Anything above 3% in Zwift meant that the treadmill would actually _decrease_ the gradient. 
     - This I suspect is due to the fact you only have a single point for up and down on screen however in reality, when you increase this to say 8% then you need to reference the control higher up on the screen (see the previous screenshot of the screen). So on steep sessions, this would become an issue for sure.
     - I can see the app trying to keep up with Zwift as it is pressing the screen but is not registering a lot of the time

I think that's everything, just wanted to put it down before I called it a night. Still really impressed by this though, it's by no means perfect but it beats paying for iFIT anyday.

**Comment by cagnulein** [comment]
> * HR monitor didn't work from my iWatch however cadence did, not  big issue as I could use an external one

did you see HR on the apple watch qz app? if not check that all the permission are enabled

> * It would only ever go to -1% even though my treadmill supports -3% and Zwift was reporting -2% and below.

do you have the log?

> * This I suspect is down to the virtual Wahoo Tread which probably only supports 1% but just a guess, not a big issue

nope, it supports all the grades



> * I can see the app trying to keep up with Zwift as it is pressing the screen but is not registering a lot of the time

maybe because the coordinates are not right at 100%

could you do a test without zwift, pressing the plus and minus button and check that you can do a 0.5% increment or decrement each time?

**Comment by Sephzer** [comment]
@cagnulein will get to this over the weekend, unfortunately had some import work to get done today :)

**Comment by Sephzer** [comment]
[Speed Test.log](https://github.com/cagnulein/qdomyos-zwift/files/13259709/Speed.Test.log)
[Gradient Test.log](https://github.com/cagnulein/qdomyos-zwift/files/13259710/Gradient.Test.log)
[Zwift Test.log](https://github.com/cagnulein/qdomyos-zwift/files/13259711/Zwift.Test.log)

Tests uploaded.

I actually think the gradient works fine from the app, it's always 0.5% so it doesn't need adjusting. The problem is that when used with Zwift, it doesn't recognize the push more often than not. So you'll be doing 6% in Zwift and the treadmill will be at 2% because it takes so long to recognize the input. By the time it's done, you're on your way back down anyways.

For the speed test, hopefully, you can see what I mean. 2km/h > 4.7km/h > 12.x km/h, pressing minus on my phone makes the increment go up, but at smaller values.

Still can't get the HR monitor to work from my watch, I double checked the permissions and it's allowed.

**Comment by cagnulein** [comment]
thanks! i will check them tomorrow!

Il giorno dom 5 nov 2023 alle 14:37 Sephzer ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi @Sephzer thanks but I need the debug log from qz, do you have for these sessions? Otherwise i can't see what zwift sent

> Still can't get the HR monitor to work from my watch, I double checked the permissions and it's allowed.

do you see HR on your watch? also set the "disable hr from machinery"

I will see also this in the QZ debug log
Thanks

**Comment by Sephzer** [comment]
Ah sorry, thought you meant the qz-app on the treadmill itself. No, I didn't save the log on my phone, I didn't turn debugging on. Not to worry, will see if I can get a mini session in at some point that shows what I mean.

No HR on my watch, I have disable HRM from machinery enabled on the app, just checked.

If there's a way to get logs of previous sessions off my phone let me know and I'll grab them.

Cheers.

**Comment by cagnulein** [comment]
> Ah sorry, thought you meant the qz-app on the treadmill itself. No, I didn't save the log on my phone, I didn't turn debugging on. Not to worry, will see if I can get a mini session in at some point that shows what I mean.

argh ok

> No HR on my watch, I have disable HRM from machinery enabled on the app, just checked.

stupid question: are you pressing start on the watch qz app? are you running ONLY the qz app on your watch?

> If there's a way to get logs of previous sessions off my phone let me know and I'll grab them.

nope unfortunately

**Comment by Sephzer** [comment]
My bad, at least I know now.

Yes, just the app on my watch, Zwift links directly to strava so I am not using any other app on my watch to record data. That's how I get my cadence/stride info into zwift and I can see that reporting fine. It's just HR that doesn't seem to work for me. Not an issue as I used my external HR monitor last time, but happy to help troubleshoot.

**Comment by cagnulein** [comment]
are you sure about ALL the permissions? also do you see the HR instead if you use the zwift app on the watch? Try also to put your finger on the crown for 10 seconds, it's usually helps to get the HR

**Comment by cagnulein** [comment]
Haha, thanks!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 6 nov 2023 alle ore 09:10 Sephzer ***@***.***>
ha scritto:

**Comment by Sephzer** [comment]
@cagnulein sorry been crazy busy the past few days/weeks. 

[Uploading debug-Tue_Nov_14_20_23_19_2023.log…]()

I’ve switched phones which doesn’t help, either way I’ve uploaded a debug from my phone with me trying to change speeds from the app. HR is working fine from my watch now btw. 

Will see if I can capture a Zwift one when I get chance as well.

**Comment by cagnulein** [comment]
hi @Sephzer no problem, log is corrupted, you need to wait the finish of the upload before pressing comment

thanks

**Comment by Sephzer** [comment]
@cagnulein yeah I noticed, phone went into low power mode I think that's why. Will send myself an email and will upload from my PC. Two secs.

**Comment by Sephzer** [comment]
@cagnulein here's your log, finally :) 
[debug-Tue_Nov_14_20_23_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13356151/debug-Tue_Nov_14_20_23_19_2023.log)

**Comment by cagnulein** [comment]
ok thanks i will check it tomorrow

Il giorno mar 14 nov 2023 alle 21:40 Sephzer ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Sephzer sorry what I should see in the log? i'm seeing that you're changing speed from the plus/minus button and it changes but with a different speed values, is this the issue?

**Comment by Sephzer** [comment]
@cagnulein that is correct, the speed increase needs tuning heavily. They should small increments, the smaller the better. Also when I pressed decrease it still increased.

This is the only real thing that needs sorting for it to be fully functional with auto speed increases/auto incline. Unless there's something you can do to make it recognize presses quicker from the treadmill as it (the app/treadmill) doesn't react quick enough when changes are made in Zwift in terms of incline. I can treadmill presses on the screen but it takes forever for one to recognise. This is probably down to the treadmill itself though rather than the app :). Hope that makes any sort of sense!

**Comment by Sephzer** [comment]
Btw, happy to open another ticket for this as the initial issue is technically fixed now :)

**Comment by cagnulein** [comment]
ok so there are 2 different issues:
- calibration of the coordinates
- reactivity of the changes

For the first one I did another change in the companion, here you can get the new apk, let me know if it's better https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.18/QZCompanionNordictrackTreadmill.apk

For the reactivity, instead, I need to understand if the time gap is about getting from zwift the value or it's caused from qz to the treadmill. In order to understand this, when you press the plus button of the speed, the touch event is immediate on the treadmill?

**Comment by Sephzer** [comment]
@cagnulein Morning, sorry another busy week.

Speed is much better now, 0.5km increments up and down so it is at least usable. If you can try and get this to be 0.2km increments that would make it even better in my opinion, but I am pretty happy with this now :) so nicely done!

In terms of updates, there is a good 2 second delay when pressing the button on the app to the treadmill making any kind of change.

**Comment by cagnulein** [comment]
> Speed is much better now, 0.5km increments up and down so it is at least usable. If you can try and get this to be 0.2km increments that would make it even better in my opinion, but I am pretty happy with this now :) so nicely done!

you can change this in the QZ settings in the treadmill section ;)

> In terms of updates, there is a good 2 second delay when pressing the button on the app to the treadmill making any kind of change.

so this is the major delay when you're doing a zwift workout, or there is also a bigger delay from zwift to qz?

@victorypoint 2 seconds is the same delay that you're observing from qz to the companion when you control your treadmill?

**Comment by Sephzer** [comment]
> so this is the major delay when you're doing a zwift workout, or there is also a bigger delay from zwift to qz?

So what happens is Zwift changes the gradient in game, say for instance I'm going up a steep hill and the gradient keeps increasing. On my treadmill I can see it actively trying to press the 'increase gradient' section of the screen but it doesn't register quickly enough probably due to the 2 second delay. By the time it has changed on the treadmill, Zwift has changed the gradient again (going downhill) so you miss the increase. Hope that makes sense.

It's a combination of the 2 second delay and the treadmill not recognising every press.

**Comment by cagnulein** [comment]
about the delay, when you have time, upload a debug log of a session, I would like to see it in the code, so I can understand where and how I can improve it
Thanks

**Comment by victorypoint** [comment]
> @victorypoint 2 seconds is the same delay that you're observing from qz to the companion when you control your treadmill?

@cagnulein, yes.. a delay due to OCR unfortunately. I'm working on speeding this up. Hope to have a solution soon.
