### ISSUE TITLE
[BUG] Horizon 7.8AT - will not start or stop

### ISSUE THREAD

**Issue by nberardi** [cagnulein/qdomyos-zwift#1757]
[debug-Tue_Oct_31_15_29_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13220728/debug-Tue_Oct_31_15_29_38_2023.log)
[debug-Tue_Oct_31_15_16_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13220729/debug-Tue_Oct_31_15_16_59_2023.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@nberardi i checked the log, the main issue is that the treadmill is not ready when you press start the first time. from that moment on the treadmill seems to ignore the command received

could you please and post a debug log in this scenario

- horizon ftms setting enabled
- start qz and wait 20 seconds before doing any action
- finally press start

let me know

**Comment by cagnulein** [comment]
@nberardi are we ok with this?

**Comment by cagnulein** [comment]
if you can do with the horizon app I can investigate it. Let me know if you would like to proceed. I asked some details in my previous comment in case
Let me know
