### ISSUE TITLE
[BUG] nordictrack x22 treadmill not connecting to android app

### ISSUE THREAD

**Issue by dukemarlon** [cagnulein/qdomyos-zwift#1760]
**Describe the bug**
Followed the below guide to install this app to my treadmill via adb. In step 5, when we should see data sending to the mobile app, this treadmill is not shown. It appears to not be connected.

**To Reproduce**
1. Turn treadmill on
2. Open mobile app
3. No treadmill connected

**Expected behavior**
Step 5. Configure QZ to communicate with QZ Companion. On your 2nd QZ device (Windows PC or laptop, Android phone or tablet, or iOS iPhone or iPad), open QZ and go to Settings. Expand Treadmill Options, Proform/NordicTrack Options, and enter the treadmills IP address under NordicTrack 2950 IP and hit OK. Exit and relaunch QZ to activate the change. If done correctly, QZ will display live data tiles to indicate it is communicating directly with QZ Companion on the treadmill.

Attempted to collect debug log, however unable to locate files.  This directory does not exist: /android/data/org.cagnulein.qdomyoszwift/

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android
 - Version 14

Unable to locate debug log using below guide.

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @dukemarlon could you please attach a debug log?

**Comment by dukemarlon** [comment]
Would love to, but after following the steps in the guide (https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F), there is no  /android/data/org.cagnulein.qdomyoszwift/ directory.

I did figure out that part of the issue was because location services permission was denied for the mobile app. I didn't find any mention of this in the install guide. After approving this permission I was able to test receiving metrics from the treadmill, but could not control speed or incline from the mobile app. Will test zwift integration tonight.

**Comment by cagnulein** [comment]
ok so your treadmill is bluetooth! great! for the speed incline control
from qz check in the proform treadmill section in qz. there are several
switches: try them one by one (only one must be enabled at a time) and
restart qz every time you change one. then try the plus button on the speed
or incline qz until you will find one that works.

if no one works, let me know

Il giorno mer 1 nov 2023 alle 20:01 dukemarlon ***@***.***>
ha scritto:

**Comment by dukemarlon** [comment]
I've been able to get Zwift to display my current speed and elevation through the qc app, but so far I cannot get zwift to control speed or incline. In the qc app I also cannot control these using the speed and inclination tile + and - buttons. I've tried with every nordictrac and proform option in the qc app, with only 1 selected and restarting the app each time. I did see a few posts also mentioning to enable auto-inclination in the zwift settings, but this option does not exist in my qc app (https://github.com/cagnulein/qdomyos-zwift/wiki/Zwift-Auto-Inclination-with-one-Android-Device-Only-Guide). I did notice my specific treadmill is not listed on the supported equipment page, it's a Nordictrac x22i with zwift running on a windows 11 22h2 laptop and an android Pixel 6 running android 14. Wondering if maybe this treadmill model is not supported at the moment? Happy to provide any more information.

**Comment by cagnulein** [comment]
Hi! Sure I can add the support for this!
Follow this with the ifit app
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

Il giorno sab 4 nov 2023 alle 19:05 dukemarlon ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@dukemarlon any news?
