### ISSUE TITLE
[BUG] JTX Fitness Sprint 5 disconnects when changing incline

### ISSUE THREAD

**Issue by kangaroomadman** [cagnulein/qdomyos-zwift#1762]
**Describe the bug**
When using with the JTX Fitness Sprint 5 Treadmill (using iConsole+), any change in incline will cause the treadmill to start altering the incline but then disconnect from bluetooth.

The 'JTX Fitness Sprint Treadmill' compatibility setting was used in QZ.

**To Reproduce**
1. Turn on treadmill
2. Open QZ and wait for it to connect
3. Start the treadmill
4. Attempt to increase incline

**Expected behavior**
Incline to change and bluetooth to remain for metrics collection.

**Tablet (please complete the following information):**
 - Device: Android Fire HD 8 (12th Generation)
 - OS: Fire OS
 - Version 8.3.2.0

**Append a debug log**

[debug-Mon_Oct_30_21_02_28_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13231908/debug-Mon_Oct_30_21_02_28_2023.log)
  
**Additional context**

A capture of Kinomap successfully controlling the incline can be found here:
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13231883/btsnoop_hci.log)

Each time this successfully controlled the incline, the same command as QZ was sent, but the different being that it was repeated 1 second later.

`f0ac01d301646439` sent at 41.38
`f0ac01d301646439` send at 42.44
`f0ac01d30264643a` sent at 55.71
`f0ac01d30264643a` sent at 56.73

At the end of the capture, the incline was increased by several points which caused multiple commands to be sent by Kinomap without repeats. This caused a bluetooth disconnect.

`f0ac01d30564643d` sent at 77.16 (there was no `f0bc...` response for this)
`f0ac01d30764643f` sent at 78.19
`f0ac01d309646441` sent at 79.21
`f0ac01d30b646443` sent at 80.24
After the `f0bc...` response for the command above, the connection drops.

**Comment by cagnulein** [comment]
#598

Thanks I will check it asap

**Comment by cagnulein** [comment]
@kangaroomadman do you have also a PC? we can test quickly my solution on the PC build. Let me know

**Comment by kangaroomadman** [comment]
> @kangaroomadman do you have also a PC? we can test quickly my solution on the PC build. Let me know

Yep, Windows 11 do?

**Comment by cagnulein** [comment]
yep! let me create the branch for you!

**Comment by cagnulein** [comment]
ok @kangaroomadman did it. It's building now https://github.com/cagnulein/qdomyos-zwift/actions/runs/6730276253
When the build it's completed you will see the files of the windows version at the bottom of the page.
What I did in this version is:
- i added the second inclination rep. as kinomap does
- i split inclination requester higher than 1% in several request each one of 0.5%

let's see if it's better

Let me know!

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/6730423803

**Comment by cagnulein** [comment]
zip ready https://github.com/cagnulein/qdomyos-zwift/suites/17843955976/artifacts/1023721967

**Comment by cagnulein** [comment]
@kangaroomadman any news?

**Comment by kangaroomadman** [comment]
@cagnulein Sorry, I did test the changes but they made no difference. Looking back through the logs and the packets sniffed from using Kinomap, I can see the response to incline requests is different. Perhaps something needs to be set up differently. 

I plan to see the initialisation differences between this and Kinomap to try and see if I can get it to work. Limited time at the moment but I’ll get some things tested when I can.

**Comment by cagnulein** [comment]
@kangaroomadman did you test this https://github.com/cagnulein/qdomyos-zwift/issues/2223#issuecomment-2001994910 ?

**Comment by kangaroomadman** [comment]
> @kangaroomadman did you test this [#2223 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/2223#issuecomment-2001994910) ?

@cagnulein Sorry, no - My treadmill has been inaccessible for a while so not had a chance. Has there been improvement under #2223?

**Comment by cagnulein** [comment]
@kangaroomadman i guess so, ask it to the other user ;)
