### ISSUE TITLE
[REQ] Use user determined power gain values with Stryd and Incline 

### ISSUE THREAD

**Issue by taxi333** [cagnulein/qdomyos-zwift#1765]
I was not clear on the feature that lead to this code: 
https://github.com/cagnulein/qdomyos-zwift/blob/ec966d60363ca62985894563b16c3c69b413790e/src/treadmill.cpp#L181C1-L188C44

Instead of QZ making its own calculation, I was thinking of QZ using some predetermined `Watt Gain:`  and the user having the opportunity to set beforehand what the `Watt Gain` is supposed to be based on the incline.

i.e. Have some sort of editable by the user table where we have something like the following 

if incline 0%, Watt gain 1.0
if incline 1%, Watt gain 1.05
if incline 2%, Watt gain 1.10
if incline 3%, Watt gain 1.3
if incline 4%, Watt gain 1.32
if incline 5%, Watt gain 1.35
if incline 10%, Watt gain 1.58
etc.

Where the watt gain is editable by the user. 

______________________________________________

If the above is to difficult or confusing, could we just get a button under `Power Sensor Options` to not apply anything extra to the Raw power being received from stryd other than the  `Watt Gain` from `Advanced Settings` ? If I have that, it would allow me to match exactly what I am seeing on the stryd pod when training on an incline, and I could memorize what the different gains are supposed to be on different incline %s and edit the gain live while running ( what I was doing before the future was implemented). 

On another note (I could report this as a bug), when using the stryd pod as treadmill  ( Option under `Power Sensor Options -> Power Sensor as a Treadmill` ), I have noticed that the power reported on QZ is all over the place, I am not sure if QZ is adding some speed/incline component to the total power reported ( need to find the piece of code where this is happening) ... I can't match what stryd is reporting, I am guessing there is more than just the stryd power that come into play to the total power reported by QZ 

I can jump on a call to explain the feature request or just can just dismiss it, all good.

QZ Version 2.16.20  (656)
Device: iphone 15 pro max, 
OS version: iOS 17.0.3 
Treadmill: Horizon 7.8AT

**Comment by cagnulein** [comment]
Hi @taxi333 I don't think the watt gain table makes a lot of sense for most of the user (but of course most of the user can keep the gain 1 for all the inclination :D), but I don't undestand why the current implementation is not right for you.

QZ is taking the stryd power and it's adding the cofficent for the inclination that reads from the treadmill.

Since I did this *ONLY* for you, I guess the easiest way is to revert the code, but I liked the way it's now (i don't have a stryd, but it has sense the current implementation since the stryd can't know the inclination of the treadmill).

Let me know if I can revert the code so.

**Comment by taxi333** [comment]
yes, could you please revert? it makes more sense for all users, thank you! 

When using the stryd as treadmill, how is the power being calculated?

**Comment by cagnulein** [comment]
> yes, could you please revert? it makes more sense for all users, thank you!

done it will be in the next one

> When using the stryd as treadmill, how is the power being calculated?

the power comes directlty from the stryd, in case send me a debug log and I will check it

**Comment by taxi333** [comment]
sounds good, I will collect a debug log the next time I use the stryd pod as treadmill ( only happens when I don't have access to my treadmill  :(  )  ... thank you!
