### ISSUE TITLE
No elevation and resistance on s15i[BUG]

### ISSUE THREAD

**Issue by miktou** [cagnulein/qdomyos-zwift#1766]
[debug-Fri_Nov_3_11_07_06_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13249159/debug-Fri_Nov_3_11_07_06_2023.zip)
**Describe the bug**

**To Reproduce**
1. Go to '...' zwift

**Expected behavior**
Watts are too much 100 on pedals 400 on qz elevation and resistance auto doesnt work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: android malatamedi1tekargon2
 - Version 9 

**Smartphone (please complete the following information):**
 - Device: samsung s23 ultra
 - OS: Android 14
 - Version 

**Append a debug log**

 I can t ad the file it don t support but i send you on menssenger mickael vrgs
  
  
**Additional context**
Could you explain how to have zwift launch on my pc and connect to qz on my Phone or tab

**Comment by cagnulein** [comment]
hi @miktou could you please attach a debug log?

**Comment by cagnulein** [comment]
[debug-Fri_Nov_3_05_51_28_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13248622/debug-Fri_Nov_3_05_51_28_2023.zip)

**Comment by cagnulein** [comment]
more than one issue in the log:
1. you don't have to set the ip of your bike in the nordictrack 2950 setting (clear it and press ok) but instead in the bike, nordictrack settings, tdf companion ip press ok and restart qz
2. I don't see any metrics in this log, did you see them?

please generate a new log with these changes and let me know

**Comment by miktou** [comment]
Ok i hope there is no next time 🙄

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miktou** [comment]
I just try it s the same.



Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>

**Comment by cagnulein** [comment]
@miktou please attach a fresh log into github interface.

**Comment by miktou** [comment]
Could you tell me if here it s ok to select other


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
if you see the metrics is ok, but then I have to map the coordinates of your touchscreen to enable auto resistance. But in order to to so, I have to first check that the log is correct.

I'm not doing an easy job here @miktou (I'm literally hacking your bike's tablet), so please follow my guide and we will got it together :)

**Comment by miktou** [comment]
Ok tanks you so so much
I m waiting for you when you ready ...

Big thanks

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
nope, I guess I didn't explain myself (sorry I'm italian), I need a fresh debug log with the current settings to check your setup

**Comment by miktou** [comment]
This one is okay ?


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
You have to attach it from the GitHub interface directly otherwise I can
see it, thanks

Il giorno ven 3 nov 2023 alle 11:31 miktou ***@***.***> ha
scritto:

**Comment by miktou** [comment]
I think it s ok

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
no you are still answering by email, you have to open your browser and go to the github web interface

**Comment by miktou** [comment]
It s in the first comment at the top

**Comment by cagnulein** [comment]
hah ok , next time you can add it to a comment so I will receive a notification :) 

i'm in a meeting now, i will check it asap

**Comment by cagnulein** [comment]
@miktou perfect! now i'm seeing the correct wattage, do you? for auto resistance try to check if with the other bike profiles in the companion you will see a touch event in the manual workout when you're changing gradient. I suggest the         s22i,
set it and restart the bike.
You can quickly check if it works using the plus/minus button in the resistance/inclination tile in qz

Let me know!

**Comment by miktou** [comment]
Yes wattage seems correct. .
Ok i will at home in 2h hours ... i give you feedback asap.


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miktou** [comment]
You can tell me how i do to have zwift on my pc and qz on my Phone or tab connect too please...


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miktou** [comment]
For the moment y use zwift and qz on the same aparel s23 ...
But as you i have à computer with tv but when i launch zwist on my pc it don t see the machine ... nothing to do special as setup on computer ?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
they must have on the same wifi and same wifi channel, nothing else. You have to see the Wahoo device or the phone name. If you don't see them, try to rename your s23 to "bike" in the android settings on your phone and reboot it

let me know

**Comment by miktou** [comment]
As you ask me i select s22i and reboot and it doesnt work... and bad the screen be in pause like i stop pedaling.
With qz i can t change elevation or résistance and on zwift it doesn t work too... 
I give you New debug file
[debug-Fri_Nov_3_15_06_22_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13251181/debug-Fri_Nov_3_15_06_22_2023.zip)

**Comment by cagnulein** [comment]
> the screen be in pause like i stop pedaling

which screen? the bike one? if so we got an hit! it means that we need only to calibrate the screen.
Please do the test that I asked without zwift

> You can quickly check if it works using the plus/minus button in the resistance/inclination tile in qz

if you see a touch reaction when you press the plus and minus button then you have to collect a screenshot from your bike using the adb screenshot script https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by miktou** [comment]
Yes it was bike screen . 
Without zwift from qz elevation and resistance dont work and when i push on the bike no pause this time ... 
New file
[debug-Fri_Nov_3_15_29_11_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13251383/debug-Fri_Nov_3_15_29_11_2023.zip)

**Comment by cagnulein** [comment]
do you see touch event when you press that buttons? in the android developer setting of the bike tablet you can enable the touch event shadow that can show you if the bike got them

**Comment by miktou** [comment]
I find : show visual feedback for taps on the tab bike
 no tap on screen during moving résistance or elevation on the bike

**Comment by cagnulein** [comment]
ok try to enable the adb setting in the proform bike section and restart qz and try again.
let me know if it's different

**Comment by miktou** [comment]
Adb remote ?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
yes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 3 nov 2023 alle ore 15:54 miktou ***@***.***>
ha scritto:

**Comment by miktou** [comment]
It s the same nothing change

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miktou** [comment]
Last file

**Comment by miktou** [comment]
In the nordictrack proform option on qz none bike is selected.... normal or i forget something ?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
ok following this, https://github.com/cagnulein/QZCompanionNordictrackTreadmill
Check if ADB works on your bike

**Comment by miktou** [comment]
It s with this method i install all
With method 1

I do allready 2 times this but i can do it Again if you want ..

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
ok so adb works? can you send me a debug log with this setting enabled so i
will check that it's sending correctly?
also if you want you can test the same thing on the pc
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary-no-python.zip


let me know

Il giorno ven 3 nov 2023 alle 16:36 miktou ***@***.***> ha
scritto:

**Comment by miktou** [comment]
Yes adb works because i install companion on my tab bike from my computer... i dont understand which debug log you want ?
Where i find this debug log ?

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
the debug log as you already did from qz on the phone this time with adb setting enabled

also try the same thing from the pc build that I linked 

thanks

**Comment by miktou** [comment]
You have allready... 2 last was with adb enable

Y try with the computer asap

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
I don't see any log with that setting enabled. You have to upload them from the web interface of github, maybe you sent by email that's why I don't see them

**Comment by miktou** [comment]
Ok and this one
[debug-Fri_Nov_3_16_01_02_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13252844/debug-Fri_Nov_3_16_01_02_2023.zip)

**Comment by miktou** [comment]
Ok thanks

I dont know what i have to do with output file on my computer

Wainting for you


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
It's the qz version for pc, unzip it and run it :)
