### ISSUE TITLE
No H/R from Apple Watch [BUG]

### ISSUE THREAD

**Issue by Spokesandsparks** [cagnulein/qdomyos-zwift#1768]
**Describe the bug**
No Heart Rate data is being sent to the QZ app. I have restarted both devices. Pressed Start on the Apple Watch but still nothing. Both are on the same wifi connection. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
are you seeing Hr on the qz app on the watch?

Il giorno sab 4 nov 2023 alle 11:59 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
yes

**Comment by cagnulein** [comment]
please attach a debug log

Il giorno sab 4 nov 2023 alle 12:10 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
[debug-Sat_Nov_4_12_08_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13256600/debug-Sat_Nov_4_12_08_40_2023.log)

**Comment by Spokesandsparks** [comment]
👍

**Comment by cagnulein** [comment]
ant heart setting is enabled, disable it, and restart QZ

**Comment by cagnulein** [comment]
also, in this log, I can't see a connection to your bike

**Comment by Spokesandsparks** [comment]
That seems to be working. Thank you. I’ve just checked with the bike and it’s working fine. Can you see if the auto incline feature is connected properly? I can say I have noticed it on Zwift. See latest bug report. 
[Uploading debug-Sat_Nov_4_12_16_37_2023.log…]()

**Comment by Spokesandsparks** [comment]
[debug-Sat_Nov_4_12_16_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13256624/debug-Sat_Nov_4_12_16_37_2023.log)

**Comment by Spokesandsparks** [comment]
I think I commented too early

**Comment by cagnulein** [comment]
for auto resistance: did you set the right device on the companion?

**Comment by Spokesandsparks** [comment]
You said I needed to use grand tour so that is the one it’s on

**Comment by cagnulein** [comment]
yeah sorry i can't remember every case, im following more than 100 users
every day :)

so in this log i can't see a zwift connection for auto resistance, did you?

Il giorno sab 4 nov 2023 alle 16:28 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
[debug-Sat_Nov_4_15_34_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13257054/debug-Sat_Nov_4_15_34_18_2023.log)

**Comment by Spokesandsparks** [comment]
I was climbing when this bug report was taken

**Comment by cagnulein** [comment]
yes i can see the inclination sent to the companion. don't you see any
reaction on the bike's tablet while you were riding?

Il giorno sab 4 nov 2023 alle 16:40 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
No I don’t but then the tablet dosent really work like that, there’s no lights etc. nothing comes up on the qz app under the inclination tile

**Comment by cagnulein** [comment]
what do you mean about lights? you have to stay in the manual workout
window in the tablet

for qz you can see that's it's working checking the target
resistance/inclination. anyway i can see from the log that it's sending it
correctly to the companion

can you try via adb to do

adb input swipe 100 200 300 400 200

and check if you see a movement  on the touch?

Il giorno sab 4 nov 2023 alle 16:53 Spokesandsparks <
***@***.***> ha scritto:

**Comment by Spokesandsparks** [comment]
Went on to try this morning and said me how I fit had updated and I was back to square one. I’ve got it all going again but it will obviously update again at some point. Is there a way to prevent this? I can’t block the internet access as ifit will not load and it also stops qz receiving data. My wife uses ifit.

**Comment by cagnulein** [comment]
nope, we are hacking it, so or you stop ifit to update it or you have to do
the procedure every time

Il giorno dom 5 nov 2023 alle 15:01 Spokesandsparks <
***@***.***> ha scritto:
