### ISSUE TITLE
[BUG] QZ on iOS does not receive data from the bike

### ISSUE THREAD

**Issue by AdrianBaginski** [cagnulein/qdomyos-zwift#1770]
Hi,

I installed QZapplication on my bike (PROFORM PRO C22) according to this guide "https://github.com/cagnulein/QZCompanionNordictrackTreadmill"

Installation went well, unfortunately the QZ on iOS does not receive data from the bike - All indicators are at zero.
When I PING Bike from computer connection is sucessfull.

I attached LOG file from iOS. Hope you can help me  :)
[0QZ-backup-czw. lis 2 20_46_46 2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13259606/0QZ-backup-czw.lis.2.20_46_46.2023.zip)

**Comment by cagnulein** [comment]
hi try select the c1750 device in the companion and restart the bike

also you attached a fit file not the debug log, thanks!

Il giorno dom 5 nov 2023 alle 13:45 AdrianBaginski ***@***.***>
ha scritto:

**Comment by AdrianBaginski** [comment]
Hi,
Thanks for your quick response :)
I change device for c1750, unfortunatelly still didn't work, QZ app not receive any data from bike

**Comment by cagnulein** [comment]
ok please attach a debug log and i will check it

thanks!

Il giorno dom 5 nov 2023 alle 13:56 AdrianBaginski ***@***.***>
ha scritto:

**Comment by AdrianBaginski** [comment]
Debug log attached
[debug-niedz__lis_5_14_03_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13259646/debug-niedz__lis_5_14_03_08_2023.log)

**Comment by cagnulein** [comment]
thanks, i'm out with my family now, i will check it asap

Il giorno dom 5 nov 2023 alle 14:05 AdrianBaginski ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi log checked, you filled the wrong field with the ip. remove the ip on
the tdf4 ip setting and press ok, and fill it in the tdf companion ip and
press ok and restart QZ
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 5 nov 2023 alle ore 14:06 cagnulein ***@***.***> ha
scritto:

**Comment by AdrianBaginski** [comment]
One good news, looks like QZ received cadance data, but odometer and speed data are missing

**Comment by cagnulein** [comment]
Could you please attach a fresh debut log? Do you see also power?

Il dom 5 nov 2023, 16:16 AdrianBaginski ***@***.***> ha
scritto:

**Comment by AdrianBaginski** [comment]
I see cadence and Watt / Log attached
[debug-niedz__lis_5_16_17_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13260005/debug-niedz__lis_5_16_17_33_2023.log)

**Comment by cagnulein** [comment]
perfect so just enable the speed based on power setting on the bike setting
and you are good to go

Il giorno dom 5 nov 2023 alle 16:21 AdrianBaginski ***@***.***>
ha scritto:

**Comment by AdrianBaginski** [comment]
I did, but still nothing :(
New log attached
[debug-niedz__lis_5_16_31_40_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13260064/debug-niedz__lis_5_16_31_40_2023.log)

**Comment by cagnulein** [comment]
in the log i see only watts to 7 max, it's not enough to have speed. could
you please try to ride a bit more?
anyway for zwift speed it's not necessary

Il giorno dom 5 nov 2023 alle 16:34 AdrianBaginski ***@***.***>
ha scritto:

**Comment by AdrianBaginski** [comment]
It dosent change anything, still no speed data. Anyway ZWIFT is working fine
Many thanks for you help :)

**Comment by cagnulein** [comment]
ok i will check tomorrow the speed issue, i guess i already fixed in the
beta

Il giorno dom 5 nov 2023 alle 20:11 AdrianBaginski ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@AdrianBaginski speed based on power fixed, if you would like to receive the new beta 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@AdrianBaginski are we ok with this?
