### ISSUE TITLE
[BUG] Proform TDF 2.0 Power and Incline Bug Zwift

### ISSUE THREAD

**Issue by Dje-Hiboux** [cagnulein/qdomyos-zwift#1771]
**Describe the bug**
Hello everyone,
I have a bug configuring the App with my Proform TDF 2.0 Bike with Zwift. I have the QZ App on my IPhone, Zwift on my Windows 10 computer. 

I achieve to Connect the bike with thé app. It Wells fine but d’Henry I Connect it to Zwift the power remaid to 0 W, the incline doesn’t work and my bike makes Bip sounds constently. 
I used the Ip adress of my bike to Connect it to thé app. 

**Screenshots**
![IMG_6993](https://github.com/cagnulein/qdomyos-zwift/assets/142584027/5f063d31-b808-499e-b279-8ef6e239aab9)
![IMG_6994]

here is the app when I’m not connected to Zwift.

![IMG_6994](https://github.com/cagnulein/qdomyos-zwift/assets/142584027/7f8bc72a-4e67-4440-a494-850c6c6a321a)

when I start Zwift and connect my phone on it only the cadence is transmit. ALL the other data are at 0. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: IPhone 14 Pro
 - OS: iOS 16.6.1

Many thanks
Jérémie

**Comment by cagnulein** [comment]
hi @Dje-Hiboux please attach a debug log from QZ
Thanks

**Comment by Dje-Hiboux** [comment]
Hi. Thanks for your Quick answer. 
when trying to do a debug file I achieve to have data on Zwift and on the app. 
But I still have my bike that bips everytime. 
And it seems I cannois change my gears. I have a constant Resistance on the bike and I cannot change it. 

Here is the debug file :
[Uploading debug-lun__nov__6_08_30_10_2023.log…]()

many thanks

**Comment by cagnulein** [comment]
Hi @Dje-Hiboux you have to wait the upload to finish before click "comment", the file is corrupted :) let me know

**Comment by Dje-Hiboux** [comment]
> Hi @Dje-Hiboux you have to wait the upload to finish before click "comment", the file is corrupted :) let me know

Sorry. Now it’s OK

**Comment by cagnulein** [comment]
log checked and QZ is sending to zwift all the metrics. Don't you see also a wahoo device in zwift from qz?

**Comment by cagnulein** [comment]
mmm it could be a zwift bug, do you have another ios device or android to run zwift instead of the pc?
also pc and your iphone are both in the same wifi and same wifi channel?

**Comment by Dje-Hiboux** [comment]
Yes Ok I will try on an other device. 
Yes they are on the same Wifi.

**Comment by cagnulein** [comment]
ok let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 6 nov 2023 alle ore 09:40 Dje ***@***.***> ha
scritto:

**Comment by Dje-Hiboux** [comment]
I made a new test with my MacBook with Zwift. 
i can see the Wahoo device on Zwift but when I Connect to it I only have the RPM. My bike make a soins biping and I have a hard résistance on the bike. And the power remain to 0 W. 

Here is the log
![IMG_6996](https://github.com/cagnulein/qdomyos-zwift/assets/142584027/5ecb0eeb-4b06-4cbc-b6a3-e006863d9115)

[debug-lun__nov__6_10_19_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13264844/debug-lun__nov__6_10_19_35_2023.log)

**Comment by cagnulein** [comment]
that's so strange, QZ is sending all the data correctly for example here 36W

`lun. nov. 6 10:20:50 2023 1699262450356 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp bool DirconProcessor::sendCharacteristicNotification(quint16, const QByteArray &) "Wahoo KICKR 0000" sending to "::ffff:192.168.1.63" : 53250  notification for uuid =  "2ad2" rv= true "64 02 df 05 ae 00 14 00 26 00 00 00"`

it seems some sort of bug on zwift but I don't undestand, I used also zwift this morning on my side and it worked fine on my apple tv.

try to unpair them all in zwift and pair it again, sometimes it happen that zwift pair only some part of the QZ metrics.

qz, accordingly to what zwift sends in the pairing screen sent these messages

```
lun. nov. 6 10:21:02 2023 1699262462453 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Master State\":\"4\"}}"
lun. nov. 6 10:21:02 2023 1699262462453 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Incline\":\"1.5\"}}"
lun. nov. 6 10:21:36 2023 1699262496801 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Master State\":\"4\"}}"
lun. nov. 6 10:21:36 2023 1699262496802 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Incline\":\"1\"}}"
lun. nov. 6 10:21:38 2023 1699262498002 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Master State\":\"4\"}}"
lun. nov. 6 10:21:38 2023 1699262498003 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp void proformwifibike::forceResistance(double) forceResistance "{\"type\":\"set\",\"values\":{\"Incline\":\"0\"}}"
```

maybe these are the beeps that you heard? they are only 3 events

Let me know

**Comment by cagnulein** [comment]
#1101 @cmorton57 are you still using QZ and your bike? are you familiar with the issue of @Dje-Hiboux  ?

**Comment by Dje-Hiboux** [comment]
I think I found something. 
when I Connect QZ app to Zwift it seems it déconnect my bike from the wifi. And it makes bip sound. 

Here is a new log
[debug-lun__nov__6_10_43_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13265045/debug-lun__nov__6_10_43_00_2023.log)

**Comment by cagnulein** [comment]
the bike in the log is well connected to qz for the whole log, so it doesn't seems to be a wifi issue, at least for what I can see from the log.

also the wattage is still strong here

`lun. nov. 6 10:44:42 2023 1699263882916 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp bool DirconProcessor::sendCharacteristicNotification(quint16, const QByteArray &) "Wahoo KICKR 0000" sending to "::ffff:192.168.1.63" : 56024  notification for uuid =  "2ad2" rv= true "64 02 92 08 9c 00 3e 00 52 00 00 00"`

maybe in the zwift log there is some errors that could explain this?

**Comment by Dje-Hiboux** [comment]
Each test I have something new 😬
But everytime I have a good connection with QZ and the bike. 
but when I connect it to Zwift and when Zwift takes control of the bike it’s making the problem. 

Here a video and the log of the test


https://github.com/cagnulein/qdomyos-zwift/assets/142584027/a123327a-6888-481a-9b4f-ed528e657f51

[debug-lun__nov__6_10_55_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13265148/debug-lun__nov__6_10_55_02_2023.log)

as long as I don’t say Ok on Zwift to Connect the Wahoo device everything is fine. Zwift power is Ok I can change my gears,…
But when I click Ok it’s making the issue

**Comment by cagnulein** [comment]
are you in the manual workout mode in the console?

**Comment by cagnulein** [comment]
@Dje-Hiboux check this comment https://github.com/cagnulein/qdomyos-zwift/issues/1101#issuecomment-1368192869

**Comment by Dje-Hiboux** [comment]
> @Dje-Hiboux check this comment [#1101 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/1101#issuecomment-1368192869)

It’ s working for some times with this solution. 
I have the incline, power and gears are Ok also. 

But my bike is constantly disconnecting from the wifi. I think it’s what making troubles. 
and my wifi box is not so far. 

Here is the new log. 

[debug-lun__nov__6_11_27_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13265440/debug-lun__nov__6_11_27_19_2023.log)
[debug-lun__nov__6_10_55_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13265441/debug-lun__nov__6_10_55_02_2023.log)

**Comment by cagnulein** [comment]
I don't see any disconnection on both logs, actually if you're still seeing the metrics on QZ it means that the bike is well connected. 
Maybe when QZ change the incline the bike freezes? I'm thinking about an electrical issue.
Disable the auto resistance by the magnet in the top right icon in qz, if it works it means that your bike could have an hardware issue.
Let me know

**Comment by Dje-Hiboux** [comment]
I have done it with the auto resistance disabled.
It's still the same problem. 
For now, with the quick start solution I don't have the beeping sound and incline problems. Everything is fine except when I start connecting to Zwift.
It's fine during fews seconds, I can do everything but
I still have my bike that deconnect to the QZ APP and Wifi after few seconds of pedaling in Zwift.

Here the pictures are at the same time : 
![IMG_6999](https://github.com/cagnulein/qdomyos-zwift/assets/142584027/6c18774e-6ee0-451b-b338-0e3b751e93a7)
![IMG_7001 3](https://github.com/cagnulein/qdomyos-zwift/assets/142584027/5264d699-5e73-4e34-beb3-c137f0ed6e9c)
[debug-lun__nov__6_11_43_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13265643/debug-lun__nov__6_11_43_03_2023.log)

**Comment by cagnulein** [comment]
ok I found the issue in the log too

```
lun. nov. 6 11:43:53 2023 1699267433398 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Cadence: 81"
lun. nov. 6 11:43:53 2023 1699267433575 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\": { \"Current MPH\": \"11.30\", \"KPH\": \"18.10\", \"Miles\": \"0.16\", \"Kilometers\": \"0.25\", \"Total Time\": \"0:40:22\", \"Total Miles\": \"6.62\", \"Current Watts\": \"57\", \"Workout Time\": \"55\", \"Calories Per Hour\": \"369\" } }"
lun. nov. 6 11:43:53 2023 1699267433576 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.25"
lun. nov. 6 11:43:53 2023 1699267433578 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Watt: 57"
lun. nov. 6 11:43:54 2023 1699267434073 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.26"
lun. nov. 6 11:43:54 2023 1699267434535 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.26"
lun. nov. 6 11:43:55 2023 1699267435147 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.26"
lun. nov. 6 11:43:55 2023 1699267435151 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Cadence: 80"
lun. nov. 6 11:43:56 2023 1699267436682 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpNewConnection() New connection from "::ffff:192.168.1.63" : 52131  uuid =  "Wahoo KICKR 0000"
lun. nov. 6 11:43:56 2023 1699267436828 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpDataAvailable() Data available for uuid  "Wahoo KICKR 0000" : "010100000000"
lun. nov. 6 11:43:56 2023 1699267436829 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpDataAvailable() Pkt for uuid "Wahoo KICKR 0000" parsed rv= 6  -> "vers=1 Id=1 sn=0 resp=0 len=0 req?=1 uuid=0000 dat= uuids=[]"
lun. nov. 6 11:43:56 2023 1699267436830 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpDataAvailable() Sending resp for uuid "Wahoo KICKR 0000" : "vers=1 Id=1 sn=0 resp=0 len=0 req?=0 uuid=0000 dat= uuids=[1826,1818,1816,]"
lun. nov. 6 11:43:56 2023 1699267436831 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpDataAvailable() Pkt for uuid "Wahoo KICKR 0000" parsed rv= -3  -> "vers=1 Id=255 sn=0 resp=0 len=0 req?=0 uuid=0000 dat= uuids=[]"
lun. nov. 6 11:43:57 2023 1699267437262 Debug: /Users/cagnulein/qdomyos-zwift/src/dirconprocessor.cpp void DirconProcessor::tcpDataAvailable() Data available for uuid  "Wahoo KICKR 0000" : "0102010000100000182600001000800000805f9b34fb"
```

 I will check it if could be releated to QZ. It seems that the socket is open but the connection is interrupted

**Comment by Dje-Hiboux** [comment]
Ok Many thanks.

**Comment by cmorton57** [comment]
Hi Roberto,Unfortunately not. My bike has an issue and will not connect to wifi anymore (I think it’s a common problem with these bikes, I had one new console under warrant for this reason)the flashing 1.44 on the console was happening when we worked on this. The flashing 1.44 occurs when you are not in the correct start mode. It sometime occurs if you start a session then stop and restart as the bike exits the correct mode.To test this. Switch the bike on Do Not touch the pedals (this puts the bike into the incorrect mode) connect to app and zwift etc start you zwift ride only then touch the pedals. This should be ok if i recall correctlyHope that helpsChrisSent from my iPhoneOn 6 Nov 2023, at 09:39, Roberto Viola ***@***.***> wrote:﻿
#1101 @cmorton57 are you still using QZ and your bike? are you familiar with the issue of @Dje-Hiboux  ?

**Comment by cmorton57** [comment]
Hi Roberto,This was my original routine for reference……..HI Roberto, Done a load of testing today and have this worked out The procedure works on both Rouvy and zwift. You have to switch on the bike, connect and the before pedalling or anything press quick start. Once in this manual mode the master state 4 code works fine – you can also keep sending master state 4 with no ill effect, this allows the user to end the ride and restart another ride as long as they hit “quick start” on the bike If you start the bike or pedal 1st – when you send master state 4, the incline works but the other elements (speed etc) stop and the bike makes a bleeping noise. To over come this the user has to press “home” to end the ride and “quick Start” – Master code 4 needs to be sent again to reactivate incline (your old flow will sort this). The only code sent from the bike when pressing “quick start” is this…… {"type": "set", "values": {"MPH": "1.20", "KPH": "2.00"}} However this also seems to be sent when starting a ride all ways, with this in mind I set the error (started a work out without “quick start” and sent master state 4) whilst the error was occurring sent {"type": "set", "values": {"MPH": "1.20", "KPH": "2.00"}} Then {"type": "set", "values": { "Master State": "4"}} This seems to fix the error (sometimes I had to send the 1st line twice) and all is good again,  I guess the only problem for you is knowing when the error occurs to send the remedy code. Im not sure if the 1st line has any effect on the ride stats as I guess you could send this anyway on the 1stincline before master status 4 to ensure it all works but not really been able to test if this will work every time. And like I said occasionally I had to send this twice for it to work. I would think that ensuring the user starts in “quick start” mode and using the old flow (with Master state 4 all the time) will work, if the bike errors the user exits and presses quick start and all should be good again! Happy to test out the last flow version if needed (or if you could send it anyway so I can ride in the meantime J Works for me – this is amazing – got my bike back working again !!!!!!! Thanks again ChrisSent from my iPhoneOn 6 Nov 2023, at 11:33, Dje ***@***.***> wrote:﻿
Ok Many thanks.

**Comment by cagnulein** [comment]
thanks @cmorton57 for your feedbacks!

**Comment by Dje-Hiboux** [comment]
Many thanks for your answer.
I'm not sure I understood everything but I'm now doing everything in quick start mode.
The problem now is the wifi disconnection when I ride in Zwift.

I will try one time with setting everything like you said and pedaling only when I'm on the Zwift session on my ride

**Comment by cagnulein** [comment]
@Dje-Hiboux my thought is: my tdf4 streams by bluetooth the heart rate. if your does the same, maybe when you open zwift, the bike is talking with zwift for hr. check if you can disable bluetooth at all on your console

let me know

**Comment by Dje-Hiboux** [comment]
You mean disable bluetooth on my bike ?

**Comment by cagnulein** [comment]
yes @Dje-Hiboux

**Comment by Dje-Hiboux** [comment]
I tried but it’s not possible from the console

**Comment by cagnulein** [comment]
@Dje-Hiboux very strange, i was checking the log and the bike stops to communicate for 40 seconds while zwift is connected and then it resumes, did you see the same? then again it stop and never resume.

The fact is that connection from the QZ is side seems strong, but maybe the bike stop to send the metrics for sure.
It seems some strange firmware issue.

Did you try to factory reset the console?

Another thing that I could try is to recreate the connection if i don't see metrics for 10 seconds for example, but it will be just a workaround and also I don't know if it will accept it since it would probably disconnected from the wifi.

Let me know

**Comment by Dje-Hiboux** [comment]
Ok it’s working !
I used my IPhone and not the Wahoo device to Connect to Zwift. And i was able to do everything fine. 

I Will try an other Time after to see if it happen a gain

here the log
[debug-lun__nov__6_11_43_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13267031/debug-lun__nov__6_11_43_03_2023.log)

**Comment by cagnulein** [comment]
ok perfect! Let me know!

**Comment by Dje-Hiboux** [comment]
Made a new test. 
the bike disconnect from the app after some times riding. 
Don’t know when because everything is fine except that point. 

Here the log
[debug-lun__nov__6_14_47_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13267330/debug-lun__nov__6_14_47_31_2023.log)

**Comment by Dje-Hiboux** [comment]
I have done nothing instead of pedaling.
When the connection is lost it's impossible to make it connect again. I have to shut everything down an start the process.

When it disconnect the wifi icon on the bike blink. But I don't know why.

**Comment by Dje-Hiboux** [comment]
Yes many thanks @cagnulein . I used my phone close to the bike and it's working well...

Many thanks for the time you spend on my issue !

**Comment by cagnulein** [comment]
Great! Remember to rate the app on store store if you like it, it means a lot to me! Also please support the app with the swag bag on the app if you like it!
Thanks!
