### ISSUE TITLE
Zwift on my PC doesn’t connect to my android device

### ISSUE THREAD

**Issue by Crystal3113** [cagnulein/qdomyos-zwift#1773]
**Describe the bug**
Zwift on my PC does not connect to my android phone. For my echelon connect bike.
My PC does find wahoo kickr which I do not have but is my understanding that it's a test

**To Reproduce**
1. Go to Qz
2. Connect to bike
3. Open zwift on my pc
4. Search for power source

**Expected behavior**
Zwift connect to my phone and in turn my bike

**Screenshots**
![20231106_161325](https://github.com/cagnulein/qdomyos-zwift/assets/150045023/fff35a35-e206-479d-848b-3525515d0d1e)
![Screenshot_20231106_161344](https://github.com/cagnulein/qdomyos-zwift/assets/150045023/db27a5ee-b577-4564-b24d-4cea12ce478e)

**Desktop (please complete the following information):**
 IdeaPad duet 5
Windows 11

**Smartphone (please complete the following information):**
 Samsung s23 ultra

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
I tried to find the log but it didn't log anything for bugs...
  
**Additional context**

**Comment by cagnulein** [comment]
Hi! You have to use the wahoo device! It's qz! Also press start on QZ

Let me know

Il giorno mar 7 nov 2023 alle 01:23 Crystal3113 ***@***.***>
ha scritto:

**Comment by Crystal3113** [comment]
I will try that this morning!! 🤞
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/6/23  8:32 PM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
Hi! You have to use the wahoo device! It's qz! Also press start on QZ



Let me know



Il giorno mar 7 nov 2023 alle 01:23 Crystal3113 ***@***.***>

ha scritto:

**Comment by Crystal3113** [comment]
Ok it does connect but it hardly moves my bike on zwift what settings do I change to fix this?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/6/23  8:32 PM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
Hi! You have to use the wahoo device! It's qz! Also press start on QZ



Let me know



Il giorno mar 7 nov 2023 alle 01:23 Crystal3113 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
set the zwift resistance offset in the bike setting to 18 and press ok

let me know

Il giorno mar 7 nov 2023 alle 14:46 Crystal3113 ***@***.***>
ha scritto:

**Comment by Crystal3113** [comment]
That was the default. I'm going like 20mph and it shows 4 on zwift
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/7/23  5:47 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
set the zwift resistance offset in the bike setting to 18 and press ok



let me know



Il giorno mar 7 nov 2023 alle 14:46 Crystal3113 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
nope the default is 4. Zwift calculates your speed based on your wattage
and the inclination and power ups in the game.
do you see the right wattage on zwift? how many wattage are you generate?

Il giorno mar 7 nov 2023 alle 14:56 Crystal3113 ***@***.***>
ha scritto:

**Comment by Crystal3113** [comment]
Honestly I think I need to reset my app. I tried to put it back just to do a normal workout and it won't show my speed at all anymore on the QZ app. How can I reset the app and start over?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/7/23  5:58 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
nope the default is 4. Zwift calculates your speed based on your wattage

and the inclination and power ups in the game.

do you see the right wattage on zwift? how many wattage are you generate?



Il giorno mar 7 nov 2023 alle 14:56 Crystal3113 ***@***.***>

ha scritto:

**Comment by Crystal3113** [comment]
Should the setting be changed in the echelon bike setting as well?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/7/23  5:47 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
set the zwift resistance offset in the bike setting to 18 and press ok



let me know



Il giorno mar 7 nov 2023 alle 14:46 Crystal3113 ***@***.***>

ha scritto:

**Comment by Crystal3113** [comment]
Tried again. QZ app did show connected to the bike and zwift brought up the wahoo
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/7/23  7:18 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
nope only in the bike section
to reset the setting uninstall the app

**Comment by cagnulein** [comment]
so is it working now?

**Comment by Crystal3113** [comment]
No its not.  It  says it's connected to wahoo but when I start the ride it doesn't move the rider and then says connection failure. 
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/7/23  10:37 PM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
so is it working now?

**Comment by cagnulein** [comment]
unpair zwift and pair it again, it's a zwift bug. i have to do all the time too

**Comment by Crystal3113** [comment]
Ok, I've decided to be done with Zwift it just too frustrating and time consuming to get it to work. I'm just going to use an on-demand platform.  What do I need to change in my settings for it to be accurate to my echelon? 
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/8/23  6:32 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
unpair zwift and pair it again, it's a zwift bug. i have to do all the time too

**Comment by Crystal3113** [comment]
Ok, thank you for your time!
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/8/23  9:42 AM  (GMT-08:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Crystal3113 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] Zwift on my PC doesn’t connect to my android device (Issue #1773) 
nothing , it's already ok with the stock settings



Il giorno mer 8 nov 2023 alle 18:41 Crystal3113 ***@***.***>

ha scritto:
