### ISSUE TITLE
Lost settings for resistance adj with Mywhoosh

### ISSUE THREAD

**Issue by MFR100** [cagnulein/qdomyos-zwift#1774]
Roberto, sorry I was trying to make my proforma tour de France work better with MyWhoosh and I think I changed a setting and now it is not automatically changing the resistance on the bike  if I use only qz it works, but not from the mywhoosh app I attached a screenshot on how the app is now showing that it does not connected to the automatic control, and a short log file . I hope you can tell me what settings I messed up because it was working  the only issue I had was that mywhoosh was reporting a variable and wrong speed depending on the inclination, so I started playing with some settings in qz. It seems mywhhoosh assumes I have gears and assumes it goes to lower gears uphill and higher gears downhill, making my speed appear very slow up and very fast down. But I can live with it as long as you make the resistance work again  

By the way, is there a way that I can save in a text file in readable format the settings once it is working?
![Screenshot_20231106-183910_MyWhoosh](https://github.com/cagnulein/qdomyos-zwift/assets/146393526/91e43945-9910-4d42-85d7-6c3bd345ab04)
[debug-Mon_Nov_6_19_26_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13273852/debug-Mon_Nov_6_19_26_00_2023.log)

**Comment by cagnulein** [comment]
thanks i will check this tomorrow.
you can save the settings and export them in the settings page of qz, with
the tops icon

Il giorno mar 7 nov 2023 alle 01:37 MFR100 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi you have to disable the power sensor setting in the experimental
settings and restart qz
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 7 nov 2023 alle ore 05:33 cagnulein ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
I set it to off but now nothing connects to mywhoosh, it simply timeouts and does not find  bike device.i will add the log from today but for some reason from this phone I have to do it in 2 steps

**Comment by cagnulein** [comment]
ok show me the log and i will check it

Il giorno mer 8 nov 2023 alle 23:49 MFR100 ***@***.***> ha
scritto:

**Comment by MFR100** [comment]
I attached the log to the last comment. I also tried the few kms that zwift  gives me as free trial and it connected to zwift, but I noticed the following:
1. Zwift was not controlling resistance based in inclination, but I could change in QZ and it changed in the bike.
2. I kept my cadence Constance without changing resistance, and the speed in QZ was more or less constant, but zwift was showing higher speed if I was going downhill, and lower speed if I was going uphill without changing the resistance. Similar to what MyWhoosh did when it was working.
3. Unfortunately I could not test longer because my zwift free trial kms ended.
4. After that I tried MyWhoosh again and still it does not connect, does not see the QZ in the android phone called bike.

Thanks


Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
> [debug-Wed_Nov_8_17_43_14_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13302472/debug-Wed_Nov_8_17_43_14_2023.log) I set it to off but now nothing connects to mywhoosh, it simply timeouts and does not find bike device.i will add the log from today but for some reason from this phone I have to do it in 2 steps Finally, I had to log in from my computer to be able to see the attachment option.

in this log there is the virtual device ifit enaled, disable it that's one issue for sure.
Let me know

**Comment by MFR100** [comment]
Hello Roberto, you are right that made it work again with MyWhoosh. I have a question of something I observed in QZ, Zwift and MyWhoosh.

I have a spinning exercise ProForm bike, it has no gears like other trainers, but it has automatic magnetic resistance. So I keep a constant cadence, lets say 80, my bike display may show something like 20 KM/h speed. If the terrain in the app is flat (Inclination=0), this speed  is very close to the speed displayed in QZ and MyWhosh.  However,  if there is a positive vali of inclination (uphill in the MyWhoosh or Swift app), the resistance goes up so I have to do bigger effort to keep my cadence of 80). The speed on the bike continues steady, but the speed shwon in QZ and the MyWhoosh or Zwift apps goes down to 12, 10 or so depending on the inclination. Also if the app shows a downhill (negative incl. value) the speed shown in QZ and the app is higher that the speed shown in my bike, even though I am keeping the same cadence regardless of the resistance. So it seems that QZ (and maybe the app) think that I have gears and because I am going uphill, I go to a lower gear and therefore my speed is lower and the opposite going downhill.
The end result is if I am doing a ride that is all uphill I end pedaling a lot more to cover the same distance, which does not  seem right if I do not have gears to play with.
So is there a way to keep the resistance going up with positive incl. and down with negative, but somehow disable what I would describe as a virtual gear shift?

Thanks.

________________________________

**Comment by cagnulein** [comment]
> Hello Roberto, you are right that made it work again with MyWhoosh. I have a question of something I observed in QZ, Zwift and MyWhoosh.

Great!

> So is there a way to keep the resistance going up with positive incl. and down with negative, but somehow disable what I would describe as a virtual gear shift?

I don't think I have understood everything right. Anyway 2 things that could help you:
- speed: QZ have 2 different algorithm to calculate the speed. The first one is reading the speed directly from the bike. The second one is calculating the speed based from power and inclination.
- virtual gears: is QZ already able to change the resistance on your bike? if so you can easily have auto resistance on it, am I missing something?

Also, final point, in indoor bikes, the distance and speed are useless indicators, you should just check the output (Kjouls) to calculate your effort.

Let me know your thougths

**Comment by MFR100** [comment]
Hi Roberto, thanks a lot for the answer. Yes QZ or the MWhoosh app vi QZ are able to change the resistance, so I am happy with it.
I would like to try the option to use the bike speed instead of the calculated one,  if it does not change the automatic resistance change.  If I want to try the bike speed, what would be the setting I have to change?
Thanks.

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
just disable the speed based on power setting

**Comment by cagnulein** [comment]
just for my understanding: so do you have 2 bikes?

**Comment by MFR100** [comment]
No only one for indoors spinning bike to exercise  when I can't go outside, and a regular outdoors mountain bike for end of spring to being of fall to ride in the trails close to my home.

Miguel Rodriguez

________________________________

**Comment by cagnulein** [comment]
ok let me know if you have any other questions
