### ISSUE TITLE
Allow Multiple Power Device Inputs

### ISSUE THREAD

**Issue by UCICoachJim** [cagnulein/qdomyos-zwift#1776]
I use Whipr devices with QZ. For swim and kayak activities, a person could use two devices. The two Whipr units do not communicate with each other as far as I can tell. 
Allow QZ to accept input from both units and total the power output 
It would be similar to using two power meter pedals on a bike. (Though, I think the power meter pedals communicate with each other and total that output)

**Comment by cagnulein** [comment]
can you show me the detail of the 2 devices on the nrfconnect app?

Il giorno mar 7 nov 2023 alle 20:36 UCICoachJim ***@***.***>
ha scritto:
