### ISSUE TITLE
[BUG] Unable to get QZ to pass rower data to Zwift (BT or Eth)

### ISSUE THREAD

**Issue by jhneuerburg** [cagnulein/qdomyos-zwift#1778]
**Describe the bug**
QZ is not passing speed/power data to Zwift from rower (Pro-Form 750R).

**To Reproduce**
1. Start QZ
2. Verify QZ has successfully connected to the rower.
3. Verify QZ is reading data from rower.
4. Start Zwift.
5. Start "run" activity. (Similar results when selecting "ride" instead of "run")
6. Pair "Wahoo KICKR 000033" as treadmill.
7. Select and start route within Zwift.
8. At this point rower data does not pass to Zwift.  If I use rower, rower data (Speed, power, cadence, etc...) displays in QZ, but not Zwift.  Character on Zwift does not move.

**Expected behavior**
Character on Zwift should move.  Zwift should display, at minimum, speed.

**Screenshots**
Here is what I get now when pairing:
![pairing](https://github.com/cagnulein/qdomyos-zwift/assets/124743459/189ba202-a3b8-419e-a84a-d66567cc5519)

Selecting Wahoo I get this (no speed in Zwift):
![result](https://github.com/cagnulein/qdomyos-zwift/assets/124743459/9e385af4-2173-49b5-922c-506040b6c49b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21+
 - OS: Android
 - Version: 13

**Append a debug log**

[debug-Wed_Nov_8_12_03_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13299927/debug-Wed_Nov_8_12_03_51_2023.log)

  
  
**Additional context**
Refer to email discussion we had for background context that may be missing above.

**Comment by cagnulein** [comment]
Thanks, I will check it tomorrow

Il giorno mer 8 nov 2023 alle 19:07 J Neuerburg ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
got the issue! I already fixed it in the beta. Join it from the play store page of QZ
Let me know!

**Comment by jhneuerburg** [comment]
I joined the beta and am waiting for the signup period to complete.  I'll give it a try tonight and let you know how it turns out!

**Comment by cagnulein** [comment]
Cool, let me know.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 9 nov 2023 alle ore 15:15 J Neuerburg <
***@***.***> ha scritto:

**Comment by jhneuerburg** [comment]
The beta worked!!  Thanks so much for you help and hard work on this project!

**Comment by cagnulein** [comment]
glad to hear it @jhneuerburg
