### ISSUE TITLE
[BUG] Broken link in Macos install instructions

### ISSUE THREAD

**Issue by Aspvik** [cagnulein/qdomyos-zwift#1779]
Download link to QT for Mac is broken. New working link:

https://download.qt.io/archive/qt/5.12/5.12.12/qt-opensource-mac-x64-5.12.12.dmg

**Comment by cagnulein** [comment]
thanks, you can do a PR if you want

Il giorno mer 8 nov 2023 alle 20:17 Rune Aspvik ***@***.***>
ha scritto:
