### ISSUE TITLE
[BUG] Incorrect distance on QZ with Sole S77 treadmill

### ISSUE THREAD

**Issue by jjanier** [cagnulein/qdomyos-zwift#1781]
**Describe the bug**
Hello,

It seams that I'm getting inaccurate distance/odometer while connecting QZ to my Sole S77 treadmill.

**To Reproduce**
1. Make a 60mins run session at 10.1km/h
2. Check total distance on QZ after 60mins and it show 9.46km
3. Export fit file from QZ
4. Check fit file record distance fields

**Expected behavior**
The fit file show correct speed, incline, heart rate and power date, but the distance field in the records events does not match the actual session speed.
On a 1h run session at 10.1km total distance show 9456.73meters, while the speed was 2.806m/s on almost all records. making the sum of the 3606 speed records give a total of 10047meters.

**Screenshots**
![Thu  Nov  9 20_44_57 2023](https://github.com/cagnulein/qdomyos-zwift/assets/6456138/9614a951-0498-4ed9-9939-d79006b5f04e)
![records](https://github.com/cagnulein/qdomyos-zwift/assets/6456138/a4d3bdae-5677-4be0-80d1-6f323eccec74)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab E 8.0
 - OS: Android 7.1.1
 - Version QZ 2.16.22

**Append a debug log**
[Thu. Nov. 9 20_44_56 2023.fit.gz](https://github.com/cagnulein/qdomyos-zwift/files/13315447/Thu.Nov.9.20_44_56.2023.fit.gz)
[Thu. Nov. 9 20_44_56 2023_record_1.csv](https://github.com/cagnulein/qdomyos-zwift/files/13315449/Thu.Nov.9.20_44_56.2023_record_1.csv)

  
**Additional context**
All fields report properly in QZ from the treadmill, not sure if the distance is sent by the treadmill or computed by QZ but QZ quickly show drift in the distance.

**Comment by cagnulein** [comment]
hi i need also the debug log from qz, thanks!

Il giorno ven 10 nov 2023 alle 05:27 Julien Janier ***@***.***>
ha scritto:

**Comment by jjanier** [comment]
I did not enabled the log for previous session, so I just did a new 10m session at 6km/h.

Here is the :

- fit file
- picture of drift: 1.01km in Sole vs 0.96km on QZ.
- debug log

![Thu  Nov  9 23_53_56 2023](https://github.com/cagnulein/qdomyos-zwift/assets/6456138/5ce7a8c2-cd22-44ce-b77b-be7a86e39595)
![20231109_235354](https://github.com/cagnulein/qdomyos-zwift/assets/6456138/e90564f0-f255-4fdd-b1d5-a9ebc55cd5ba)
[debug-Thu_Nov_9_23_43_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13315677/debug-Thu_Nov_9_23_43_06_2023.log)
[Thu. Nov. 9 23_53_56 2023.fit.gz](https://github.com/cagnulein/qdomyos-zwift/files/13315683/Thu.Nov.9.23_53_56.2023.fit.gz)

Regards,

Julien

**Comment by cagnulein** [comment]
Thanks, I'll check it out today (7am here in italy :) )

Il giorno ven 10 nov 2023 alle 06:02 Julien Janier ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fixed! it will be in the 2.16.23
Let me know when you will try it!

**Comment by cagnulein** [comment]
yes i know that some sole treadmills can send the distance but most of them are sending the life time distance so i'm discarding it. Also since in qz you can play, pause and stop session, the distance field could be not in sync with the treadmill.

If you would like to check my patch, use the trial version of qz that you can download if from here https://github.com/cagnulein/qdomyos-zwift/suites/18075676280/artifacts/1041465616

let me know

**Comment by jjanier** [comment]
Just tested it and it fixed the distance drift. We are all set :) thanks you so much for you responsiveness ! This issue can definitely be closed :)

**Comment by cagnulein** [comment]
Glad to hear it!

Il giorno ven 10 nov 2023 alle 10:39 Julien Janier ***@***.***>
ha scritto:
