### ISSUE TITLE
No numbers from Proform cross trainer

### ISSUE THREAD

**Issue by Mudshark21** [cagnulein/qdomyos-zwift#1783]
[debug-Sat_Nov_11_11_38_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13325366/debug-Sat_Nov_11_11_38_21_2023.log)
**Describe the bug**
I tested on install and numbers from the trainer came through to the app ok but no don't, since my initial test I installed an up to date graphics driver and zwift

**To Reproduce**
turned on trainer then started app - bluetooth connected

**Expected behavior**
See some numbers coming through from the trainer

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok thanks, i will check it on monday

Il giorno sab 11 nov 2023 alle 12:47 Mudshark21 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Mudshark21 is it from the windows version right? did you try also with the android or ios one? i guess the issue is only for the pc version (fixable, but let's check on the mobile first)

Let me know!

**Comment by Mudshark21** [comment]
Looks like there was a bluetooth issue - said connected but not really. So seems to work fine, Need to see what my wife wants to do, as she wasn't that excited about using it unfortunately! Is the windows version a monthly cost and the phone ones a one off?
Thanks

**Comment by cagnulein** [comment]
> So seems to work fine,

great!



> Is the windows version a monthly cost

yes for the windows version you need to join patreon



> nd the phone ones a one off?

yes even if i also ask to join the swag bag if you like it so you will help me to keep this alive!

let me know if you have any other questions!

**Comment by Mudshark21** [comment]
Thanks, my wife is only using the trainer occasionally so hoping this will help. Oh, if this is is installed on a phone can that then be connected to a laptop to run zwift there? Or does it have to be run on the same device?

**Comment by cagnulein** [comment]
yes you can use qz on the phone and zwift on the pc

Il giorno gio 16 nov 2023 alle 10:29 Mudshark21 ***@***.***>
ha scritto:
