### ISSUE TITLE
[BUG] ProForm Pro C22 can’t connect between QZ Companion and QZ iOS App

### ISSUE THREAD

**Issue by danielsa27** [cagnulein/qdomyos-zwift#1784]
Tengo instalada la última release de la app QZ Companion en mi ProForm C22, y seleccionado en esta mi modelo de bici:

![IMG_6853](https://github.com/cagnulein/qdomyos-zwift/assets/17600294/d77e28af-7236-4b33-9f66-dc3f9e4b0192)

Sin embargo, desde mi iPhone, no logro conectar con la bici.

Siguiendo indicaciones de Roberto por el grupo de Facebook, adjunto el l log generado en el móvil:

[debug-dom_nov_12_15_43_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13328343/debug-dom_nov_12_15_43_56_2023.log)

Muchas gracias de antemano por la ayuda.

Saludos

**Comment by cagnulein** [comment]
hi @danielsa27 please attach a debug log as described in the above link

**Comment by danielsa27** [comment]
> hi @danielsa27 please attach a debug log as described in the above link

Agregado en la descripción del issue. Gracias!

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

**Comment by cagnulein** [comment]
@danielsa27 the main issue is that the companion is not sending anything at all. Could you please, start a workout in the bike, while you're doing the workout, open the compnaion and press the dump log button and take a picture of the message box under it?
Thanks

**Comment by danielsa27** [comment]
@cagnulein 

In first place sorry for the delay, but since today i can not do the log. I was out of home for business.

I enclose the log maked during session on iFit.

One mor time sorry for delay.

Regards

**Comment by cagnulein** [comment]
hi @danielsa27 thanks for the log, but what I need to understand the issue is 

>  Could you please, start a workout in the bike, while you're doing the workout, open the compnaion and press the dump log button and take a picture of the message box under it?

could you do it?

**Comment by cagnulein** [comment]
also you can try to select the c1750 device on the companion, reboot the bike and see if it makes any difference

**Comment by danielsa27** [comment]
Hi @cagnulein ,

I try C1750, but the result is the same.

I enclose two captures, each one with the test realized.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/17600294/a64ed0b7-9968-485f-ab28-3883baf8554d)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/17600294/af73ca33-abca-41de-b8f3-f918bf7dd57e)

**Comment by cagnulein** [comment]
were you riding during this picture? if so it seems that ifit locked the statistics, I guess we should proceed to use this method  https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

could you try it?

**Comment by cagnulein** [comment]
@danielsa27 if you run a 

adb logcat 

from your pc or mac do you see the metrics while you're riding?

**Comment by danielsa27** [comment]
@cagnulein , I enclose the logcat file cached just now during a sesion:

[iFit_20231217_outputlog.txt](https://github.com/cagnulein/qdomyos-zwift/files/13695710/iFit_20231217_outputlog.txt)

**Comment by cagnulein** [comment]
ok good news @danielsa27 I can see the metrics! And also I'm seeing that QZ companion is sending it to the qz on the phone! So you don't still see the metrics on the phone? It could be the router is dropping the broadcast messages from the companion. Which router do you have? you can try to use the phone as an hotspot for the treadmill. Or in case I can add a setting in the companion to specifiy the pc ip address.
Let me know

**Comment by cagnulein** [comment]
qz can run standalone and you don't need a 3rd device unless you want to use zwift or any other app with. also zwift for example can run on the same qz device.

did i answer to your questions ?

**Comment by danielsa27** [comment]
That is, can I have any App + QZCompanion on the tablet that incorporates the ProForm Pro C22 to send data via WiFi to the mobile, where using the QDomyosZwift app, manage the resistance? In the end it's just what I need... to be able to raise and lower the resistance of the bike from my phone... is this possible? Or am I wrong and I won't be able to do it?
Another question that arises for me is if in order to increase or reduce the resistance of the bike from my mobile phone, do I necessarily have to always have the iFit App running on the bike, even when I am going to use another app for my exercise?
Sorry for the doubts, but if I manage to manage the resistance from my mobile, a very big world of possibilities opens up for me...
