### ISSUE TITLE
Cannot get Nordic Track Studio Bike - NTEX71021 to work w/ QZ

### ISSUE THREAD

**Issue by ashishlalani** [cagnulein/qdomyos-zwift#1785]
Hello, 

I have a Nordic Track Studio Bike. I have very little ADB or coding experience so may need to help with step by step. 
I was able to follow all instructions to install QZCompanion on treadmill, and have these settings enabled on my QZ Fitness App on my phone. 

I tried to select the bike as treadmill: c1750, with settings on my phone: Nordic Track Bike Option selected to check Proform Studio Bike, and TDF Companion IP set at 192.168.0.38 with no other changes (treadmill options not selected and at default). I restarted the treadmill multiple times with no success. 

Then I was told to try this method:
install the companion 
set the grand tour pro device in the companion
grant the permission with adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS from a mac or a pc 
enable adb debug for qz companion
restart the companion

I was able to get some data now, but when I increase resistance, or incline, it does not change on Application. I also have a Scosche Rhythm 24 HR monitor attached to the bike (on QZ App, it shows Rhythm 24 found as well, but does not utilize that data, do I connect it to phone?), and it displays HR on the iFit App when on manual mode, but doesn't show it on the app, if you could please help with that. 

Thanks so much for all your help!
-------
Other info:
**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold 4
 - OS: Android 13
 (cannot access QZcompanion logs as access is limited as phone is not rooted)
Thanks

**Comment by ashishlalani** [comment]
![Installed QZCompanion on Treadmill](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/84967b35-9019-404c-8b2c-2e3b5fd2a095)

![QZ Fitness setup](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/37574b7e-cc85-40e1-ad2b-f5091272c9a1)

Attached is what I have setup so far to show that the command prompt can connect to treadmill

**Comment by cagnulein** [comment]
thanks, i will check this tomorrow

Il giorno dom 12 nov 2023 alle 17:24 ashishlalani ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok so perfect, for your bike I have to inherit the Grand tour pro reading and add a custom touchscreen coordinates for the resistance. Run this batch file to map the touchscreen https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

Let me know!

**Comment by ashishlalani** [comment]
I was able to get Zwift to work and connected it directly with my HR monitor. Everything is working perfectly except for the ERG Resistance (it is not automatically updating resistance). Is there any way to have it automatically change resistance when I go up a hill on Zwift?

![Sun11-12-2023@11-53-41 20](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/e151250c-813c-4622-9d93-faf549d4d384)

Thanks so much for all your help so far!

**Comment by cagnulein** [comment]
yes sure with this screenshot tomorrow i will add automatic resistance.
for erg mode instead i will need a a different thing, but let's fix auto
resistance for free ride and races first
have a nice sunday!

Il giorno dom 12 nov 2023 alle 18:55 ashishlalani ***@***.***>
ha scritto:

**Comment by ashishlalani** [comment]
Perfect. I set up the treadmill so that I can adjust the resistance by tapping, and hopefully that makes it easier for you to map tomorrow. Here is attached screenshot. Thanks so much!
![Uploading Sun11-12-2023@13-23-22.19.png…]()

**Comment by cagnulein** [comment]
@ashishlalani I did the modification on the companion side but i have also to do a modification at the qz side, in particular, note for me,

`bool nordictrackifitadbbike::inclinationAvailableByHardware() { return true; }`

i will add your device as a switch in both companion and QZ, I will update you when I will be ready

**Comment by cagnulein** [comment]
companion new version https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.3.17

remember to select your device from the list

i will try to build the new ios version later today/tomorrow

**Comment by ashishlalani** [comment]
I was able to install the QZcompanion on the bike, and reboot treadmill but now when I try using the app on my android phone, it doesn't connect to anything or update any tiles at all (like original issue I was having). I'm assuming that it's because the QZ app for Android needs to be updated? 

Thanks

**Comment by cagnulein** [comment]
yes exactly, but this companion version should work as the last one at least. maybe you have to reset the permission and stuff that you did in the Bike to get the metrics in QZ?

**Comment by cagnulein** [comment]
if you want the trial version of qz is ready with the patch https://github.com/cagnulein/qdomyos-zwift/suites/18141836485/artifacts/1046211456

**Comment by ashishlalani** [comment]
Thanks. I will try it in few hours and let you know.

**Comment by ashishlalani** [comment]
I have installed the new application on the bike and also my phone. It does
not register the bike. When I try running the QZcompanion simple.bat. This
is what shows up. It is connected to the same WiFi network. Any ideas?

**Comment by cagnulein** [comment]
what did you changed since when you saw the metrics? the apk on the bike?
try to put the old again just to be sure


Il giorno lun 13 nov 2023 alle 19:03 ashishlalani ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Ok let me know

Il lun 13 nov 2023, 19:12 ashishlalani ***@***.***> ha
scritto:

**Comment by ashishlalani** [comment]
Hi Roberto, I was able to remove everything and started from Scratch. I was able to get the new QZCompanion App to show my bike and also the beta version you sent me, I installed it and also was able to set it up for my bike. The bad news is, resistance still doesn't update. It doesn't go past one for resistance and doesn't change when I update it on the bike.

![Screenshot_20231113_221928](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/ba8ace9e-a0c2-4e09-a34a-0d7a6643fabb)

![Screenshot_20231113_221652 (1)](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/7de383d0-08b4-4837-a31b-6a3046f9eb0c)

**Comment by cagnulein** [comment]
please attach a debug log, thanks

Il giorno mar 14 nov 2023 alle 05:22 ashishlalani ***@***.***>
ha scritto:

**Comment by ashishlalani** [comment]
How would I go about getting the debug log? Thanks!

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Il giorno mar 14 nov 2023 alle 05:43 ashishlalani ***@***.***>
ha scritto:

**Comment by ashishlalani** [comment]
[debug-Mon_Nov_13_22_46_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13344583/debug-Mon_Nov_13_22_46_00_2023.log)
[debug-Mon_Nov_13_22_47_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13344584/debug-Mon_Nov_13_22_47_12_2023.log)

Attached are the debug logs, it does not update resistance on the app when I change on the bike.

**Comment by cagnulein** [comment]
ok thanks i will check later today, 5am here in italy, im starting my
morning zwift ride :)

Il giorno mar 14 nov 2023 alle 05:51 ashishlalani ***@***.***>
ha scritto:

**Comment by ashishlalani** [comment]
No worries at all! Thank you so much! I really appreciate you working on this, really shows how dedicated you are to this service! Hopefully we can get it working!

**Comment by cagnulein** [comment]
ok so you don't see any touch event at all when you press the resistance?
if not try from your pc/mac to run the following command

`adb shell input swipe 100 200 300 400 200`

and check if you are able to see a touch input on the touch when you run it. If so I know where the issue is and it will be easy fixable.
Let me know

**Comment by ashishlalani** [comment]
The touch command works, it does scroll up when I insert that command on the bike.
Attached is video when I run command

https://github.com/cagnulein/qdomyos-zwift/assets/104768949/334a1198-5c37-4b90-8c9b-39c44b68d393

**Comment by cagnulein** [comment]
sorry, new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/6865044658

**Comment by ashishlalani** [comment]
I tried w/ new app with ADB remote enabled, but now it shows nothing for resistance 0, avg 0, max 0 again. I tried to adjust the resistance on the bike and it didn't update on the app. I tried to press the plus button on my phone app, and it did nothing. I have attached debug log again. 
[debug-Tue_Nov_14_13_03_43_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13355092/debug-Tue_Nov_14_13_03_43_2023.log)
[debug-Tue_Nov_14_13_05_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13355094/debug-Tue_Nov_14_13_05_18_2023.log)

**Comment by cagnulein** [comment]
i will check the log tomorrow, thanks

Il giorno mar 14 nov 2023 alle 20:18 ashishlalani ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@ashishlalani log checked: now I can't see the changed resistance message at all from the companion. It's not an issue of the new qz version, it seems that the bike just stopped to log it. Maybe did you change something on bike side?

About the swipe commands, I'm seeing that the new qz version is sending the adb commands correctly, in order to debug it further I need a bug report from the android settings in this scenario. You can send me it by email roberto.viola83 at gmail.com if you are concerned about privacy.

Thanks

**Comment by ashishlalani** [comment]
How do I get the debug report from Android system? You mean the debug
report from bike or from the phone?

**Comment by cagnulein** [comment]
from the phone, check here https://developer.android.com/studio/debug/bug-report

**Comment by ashishlalani** [comment]
I will do it when I am home from work and let you know.

Thanks

**Comment by ashishlalani** [comment]
I have sent you the log from my phone via email. I also think that the touch input is not set correctly, and this is causing issue on resistance. When I open the app on my phone and also open iFit on the bike, it keeps clicking on a random area, which I think may be the issue. I have attached a video along with the new debug log. 

https://github.com/cagnulein/qdomyos-zwift/assets/104768949/71cf34ba-8755-412f-885e-384df48adc3f

[debug-Wed_Nov_15_16_24_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13370331/debug-Wed_Nov_15_16_24_08_2023.log)

**Comment by cagnulein** [comment]
they are the adb tocuh event from qz! that's a success! now we need only to calibrate them, let me check the log

**Comment by cagnulein** [comment]
mmm the coordinates seems right according to the screenshot you send me above. could you please run this command and check the reaction

`adb shell input swipe 950 493 950 520 200`

if you see the same random touch event, it means that the screenshot is not right somehow. Let me know!

**Comment by cagnulein** [comment]
ok so it means that the screenshot that you sent me above probably wasn't
get from the adb screenshot batch file, isn't it?

about the resistance from the bike: i thought it came through in the past,
am i wrong? did you change something?

Il giorno gio 16 nov 2023 alle 16:31 ashishlalani ***@***.***>
ha scritto:

**Comment by ashishlalani** [comment]
The resistance never came through on the App on my phone. It never worked
and never updated as I increased or decreased the resistance on the bike.
As for the screenshot, I used the adb screenshot batch file.

**Comment by cagnulein** [comment]
ok so let's focus on getting the resistance first. can you check on the wolflogs directory on the tablet if you can see the resistance in the logs?

**Comment by ashishlalani** [comment]
I see the wolflogs, and it does show resistance update, but not all the time, maybe I am checking incorrectly. I have also attached the wolflogs log, which displays information about tablet size as well. 

[2023-11-16_logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/13381025/2023-11-16_logs.txt)
![20231116_114139](https://github.com/cagnulein/qdomyos-zwift/assets/104768949/2211a4c1-410d-4e26-a067-36550cc36aa7)

**Comment by cagnulein** [comment]
Ok in the dump log I see the resistance, could you please send me a debug
log from qz. We should see the same line in the log too so

Il gio 16 nov 2023, 18:55 ashishlalani ***@***.***> ha
scritto:

**Comment by ashishlalani** [comment]
I have a feeling that the problem is the QZTreadmill application and it is not updating the resistance when I change it. It looks like when I have the QZ app on the phone, it will update once with the resistance I start with, and then if I update it on the bike, for example switching from 16 to 4, it doesn't update on the phone. I have attached 2 logs of the QZcompanion and it doesn't look like it gets any resistance changes. I updated the resistance to 4 on bike, and it didn't update on the phone at all. 

[debug-Thu_Nov_16_12_52_41_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13382354/debug-Thu_Nov_16_12_52_41_2023.log)

**Comment by cagnulein** [comment]
thanks but the debug log is a 0 byte file

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 nov 2023 alle ore 20:03 ashishlalani <
***@***.***> ha scritto:

**Comment by ashishlalani** [comment]
I wanted to show you what I mean by I think that QZCompanion is the culprit. I closed the QZcompanion app. Restarted it, and then used iFit, updated reisistance multiple times, and on the QZcompanion log, it doesn't show that the resitance changes properly. Only shows resistance change to 17, but video you can see multiple times resistance changes (4,7,11,17,1 etc). 

I can send you the log again if you need, but I think the culprit is the QZCompanion app on the bike and not updating the resistance values correctly. 

https://photos.app.goo.gl/oQbjwRuZi9D2E9dw5

**Comment by cagnulein** [comment]
but in the wolflog are you seeing all the events? or also in the logcat
(adb logcat -b all -d)?
because the companion is simply getting data from it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 nov 2023 alle ore 20:29 ashishlalani <
***@***.***> ha scritto:

**Comment by ashishlalani** [comment]
On wolflog, it says logging disabled at 12:47pm, not updating past that, the event for resistance changes happened at 1:14pm

**Comment by cagnulein** [comment]
```
11-16 13:38:06.022 28893 28893 I QZ:Service: 11-16 13:14:35.061 25612 25704 V mono-stdout: [10] [Trace:FitPro] Changed Resistance to: 17
11-16 13:38:06.973 28893 28893 I QZ:Service: 11-16 13:38:06.022 28893 28893 I QZ:Service: 11-16 13:14:35.061 25612 25704 V mono-stdout: [10] [Trace:FitPro] Changed Resistance to: 17
```

yeah this is the only event.

unfortunately I can get something that it's not logged at all.
it's strange that logs something but not everything.

The only way to override this, it's connecting directly to the usb, but i need a bike on my end to reverse engineering it by hardware. check #1577 

Do you have any other idea?
@victorypoint any idea?

**Comment by ashishlalani** [comment]
I wouldn't quite know what to do either.
For now, I will just use it without resistance values and update resistance
myself, and see how it goes. Thanks for the help! Please do let me know if
you come up with anything else.

Thanks

**Comment by cagnulein** [comment]
ok I will think about it, there must be a solution for this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 nov 2023 alle ore 21:10 ashishlalani <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@ashishlalani check this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/67#issuecomment-1816352825 !!

**Comment by ashishlalani** [comment]
Hi, I read the comments and looks like well on way to finding a fix! Once
you get that one sorted, I can try on my bike and see if it works for me as
well!

Thanks
