### ISSUE TITLE
[BUG] Unable to enable auto-resistance when riding with Zwift.  Ex-5 Connect

### ISSUE THREAD

**Issue by scouser27** [cagnulein/qdomyos-zwift#1787]
**Describe the bug**
Using Zwift with the qdomyoszwift app on a Echolon Ex-5 connect bike, I'm unable to leverage any auto resistance changes when in a higher ERG zone, therefore unable to generate any additional wattage at maximum rpg.  If I turn off auto-resistance and use the manual knob to alter resistance, I'm able to experience an expected workout/ride.  
[debug-Mon_Nov_13_18_10_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13343047/debug-Mon_Nov_13_18_10_33_2023.log)

It is likely my settings.  Thank you in advance

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
just to be sure: are you talking about ERG workout or free ride/race?

**Comment by scouser27** [comment]
Sadly it’s any ride in Zwift. If I take off auto resistance I can enjoy the ride and the apps that I’m using. Sorry I can’t be more helpful I’m brand new to this. Sent from my iPhoneOn Nov 14, 2023, at 2:23 AM, Roberto Viola ***@***.***> wrote:﻿
just to be sure: are you talking about ERG workout or free ride/race?

**Comment by cagnulein** [comment]
@scouser27 in order to understand your issue I need at least a debug log with the problem (the debug log attached is only a 10 second session).
Also keep in mind that if you're doing a ERG workout in zwift, the zwift erg mode setting in QZ must be enabled. Disabled it instead if you are doing a free ride/race

Let me know

**Comment by scouser27** [comment]
[debug-Wed_Nov_15_17_52_26_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13370820/debug-Wed_Nov_15_17_52_26_2023.log)
Here's a log.  let me know if you find anything interesting....  thanks very much

**Comment by cagnulein** [comment]
@scouser27 log checked, the main issue seems about the watt gain to 1.2 
why do you put this to 1.2? in this way you're "cheating" increasing the wattage reading from your bike. Maybe you wanted to put 0.8 instead?

**Comment by scouser27** [comment]
Ok I’ll try that. So you think that when I hit zone 2/3 that 1.2 is throwing the auto resistance off ? I bumped it up since I couldn’t get the wattage over 120 even at 80-90 rpm.  Thanks. Sent from my iPhoneOn Nov 16, 2023, at 2:52 AM, Roberto Viola ***@***.***> wrote:﻿
@scouser27 log checked, the main issue seems about the watt gain to 1.2
why do you put this to 1.2? in this way you're "cheating" increasing the wattage reading from your bike. Maybe you wanted to put 0.8 instead?

**Comment by cagnulein** [comment]
Yes, actually in this way you're are obtaining the Opposite  Inviato da Apple WatchIl giorno 16 nov 2023, alle ore 13:03, Geoff McCormack ***@***.***> ha scritto:
Ok I’ll try that. So you think that when I hit zone 2/3 that 1.2 is throwing the auto resistance off ? I bumped it up since I couldn’t get the wattage over 120 even at 80-90 rpm.  Thanks. Sent from my iPhoneOn Nov 16, 2023, at 2:52 AM, Roberto Viola ***@***.***> wrote:﻿

@scouser27 log checked, the main issue seems about the watt gain to 1.2

why do you put this to 1.2? in this way you're "cheating" increasing the wattage reading from your bike. Maybe you wanted to put 0.8 instead?

**Comment by scouser27** [comment]
Hi Roberto - Sadly dropping the resistance down to 0.8 didn't increase the auto resistance of the bike when I hit the higher zones.  I was just left with lower wattage output and having to pedal harder 120 rpm to make any difference.  At this point, I can get a good workout in with the auto resistance turned off and use the knob on the bike.  I appreciate you looking into this for me.  Perhaps I'll discover something the more I use the app and Zwift.

**Comment by cagnulein** [comment]
if you want i can continue to check your case.
could you please send me a debug log of a small session with watt gain to
1. in this scenario everyone uses it, and it must work, so i would like to
address any issue if there is one. thanks

Il giorno ven 17 nov 2023 alle 02:44 Geoff McCormack <
***@***.***> ha scritto:

**Comment by scouser27** [comment]
Will do. I’ll ride later today. Thanks very much. Sent from my iPhoneOn Nov 17, 2023, at 12:28 AM, Roberto Viola ***@***.***> wrote:﻿
if you want i can continue to check your case.

could you please send me a debug log of a small session with watt gain to

1. in this scenario everyone uses it, and it must work, so i would like to

address any issue if there is one. thanks



Il giorno ven 17 nov 2023 alle 02:44 Geoff McCormack <

***@***.***> ha scritto:

**Comment by scouser27** [comment]
Hi uploading two files.  The first one was a 3 minute ride with auto resistance turned on.  My resistance setting never  changed from 12, when I would expect it to go up and down based upon the Zwift ride.  So the problem lies in the communication between Zwift and the qdomyos app regarding what the current resistance should be based upon the terrain.
[debug-Fri_Nov_17_18_21_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13398612/debug-Fri_Nov_17_18_21_25_2023.log)

**Comment by scouser27** [comment]
The second file was my ride with auto resistance off and no other settings changed.  In case you see something interesting.
[debug-Fri_Nov_17_18_32_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13398619/debug-Fri_Nov_17_18_32_30_2023.log)

**Comment by cagnulein** [comment]
In the first log the resistance doesn’t change due to the fact that you
have the setting
zwift_erg_resistance_down to 12 and the resistance required for the request
of zwift is less than that value

If you put it to 0 you will see that the resistance will change accordingly

Let me know

Il giorno sab 18 nov 2023 alle 02:25 Geoff McCormack <
***@***.***> ha scritto:

**Comment by scouser27** [comment]
Ok. I can do that. But anything less than 12 and it feels like I’m pedalling without a chain. Should I be spinning at over 120 rpm ? It doesn’t feel safe. Sent from my iPhoneOn Nov 18, 2023, at 3:17 AM, Roberto Viola ***@***.***> wrote:﻿
In the first log the resistance doesn’t change due to the fact that you

have the setting

zwift_erg_resistance_down to 12 and the resistance required for the request

of zwift is less than that value



If you put it to 0 you will see that the resistance will change accordingly



Let me know



Il giorno sab 18 nov 2023 alle 02:25 Geoff McCormack <

***@***.***> ha scritto:

**Comment by cagnulein** [comment]
nope if it's so it means that you have to increase the ftp in zwift

means that: or your bike has something with the resistance or you're really
strong and moving 100W for you it's very easy.

for example, for me a male of 40y and 78kg the ftp is 240W

maybe you can try to set a similar value on zwift

which value do you have now?

Il giorno sab 18 nov 2023 alle 14:30 Geoff McCormack <
***@***.***> ha scritto:

**Comment by scouser27** [comment]
That might be it. My FTP is set at 0. I’m 54 and 73kg. So I’ll try 200 and see what happens. Thanks. Sent from my iPhoneOn Nov 18, 2023, at 8:42 AM, Roberto Viola ***@***.***> wrote:﻿
nope if it's so it means that you have to increase the ftp in zwift



means that: or your bike has something with the resistance or you're really

strong and moving 100W for you it's very easy.



for example, for me a male of 40y and 78kg the ftp is 240W



maybe you can try to set a similar value on zwift



which value do you have now?



Il giorno sab 18 nov 2023 alle 14:30 Geoff McCormack <

***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok let me know!

Il giorno sab 18 nov 2023 alle 18:52 Geoff McCormack <
***@***.***> ha scritto:

**Comment by scouser27** [comment]
[debug-Sat_Nov_18_15_11_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13401540/debug-Sat_Nov_18_15_11_32_2023.log)
[debug-Sat_Nov_18_15_20_49_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13401541/debug-Sat_Nov_18_15_20_49_2023.log)
Hi sadly, setting the FTP on Zwift to 200 wasn't enough to shift the auto resistance automatically.  I wonder if I should reset the app to the default settings.  The first file is a short ride with the default resistance at 12.  Not sure why 12, but it never shifted from that.  And the second file is the same settings with auto resistance off and me using the knob on the bike.

**Comment by cagnulein** [comment]
in the first log zwift asks always more or less 90w that's the issue. you
have to select a workout where zwift requests more wattage. also from the
zwift workout setting you can increase the wattage baseline. 90w is more
less resistance 12
Let me know

Il giorno sab 18 nov 2023 alle 22:49 Geoff McCormack <
***@***.***> ha scritto:

**Comment by scouser27** [comment]
I cut the first workout when zwift was asking for 135w and the resistance stayed at 12.  I don't think that's the issue.  I'm going to try an FTP today to see if I can somehow alter the auto resistance on the app.

**Comment by cagnulein** [comment]
during the ftp test zwift will not handle the resistance, you have to yourself.

i will check the log again tomorrow, but for what i saw on my mobile 12 was the resistance for 90W.

anyway i will let you know after my deep analysis

**Comment by scouser27** [comment]
[debug-Sun_Nov_19_16_32_14_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13405111/debug-Sun_Nov_19_16_32_14_2023.log)
Hi sadly I can't seem to find any setting that will automatically switch the auto resistance beyond its original value at start up.  I've played with all the different settings available and I'm at a loss.  I don't think it is the app nor the bike, since the knob can alter the resistance just fine and between the QZ app and Zwift I can get what I need from a workout.  I just don't know what else to try - other than a reset of the QZ app and alter one or two settings.  Sorry I haven't been much help on my end.

**Comment by cagnulein** [comment]
ok i will check this later today
thanks

Il giorno lun 20 nov 2023 alle 01:34 Geoff McCormack <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i checked both https://github.com/cagnulein/qdomyos-zwift/files/13405111/debug-Sun_Nov_19_16_32_14_2023.log and https://github.com/cagnulein/qdomyos-zwift/files/13401540/debug-Sat_Nov_18_15_11_32_2023.log and the issue here is that you were doing a free ride or race on zwift, isn't it? if so you need to disable the zwift erg mode setting in QZ. This setting must reflect the mode that you're using on zwift.

Disabled: if you're doing a free ride or race
Enabled: if you're doing a workout

Let me know
