### ISSUE TITLE
[BUG] Focus Fitness Senator 54 iplus

### ISSUE THREAD

**Issue by tom-pauwels** [cagnulein/qdomyos-zwift#1790]
**Describe the bug**
Treadmill 'Focus fitness senator 54 iplus' does not show activity in QZ app

**To Reproduce**
Plug in treadmill
Start QZ app
QZ app recognizes the crosstrainer treadmill, it is show within the app as 'i-Running0210 found'
The bluetooth signal turns from light-blue to clear blue, indicating the connection is established
Activity is automatically started (Pauze button enabled on top), yet not activity is shown when using the treadmill (e.g. speed remains 0.0 km/h).

**Expected behavior**
expected app to show data (speed, distance,...) when pressing staring the activity on the treadmill. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 10 PRO
 - OS: Android 13

**Append a debug log**
  
[debug-Wed_Nov_15_11_52_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13363882/debug-Wed_Nov_15_11_52_03_2023.log)

  
**Additional context**

**Comment by cagnulein** [comment]
thanks @tom-pauwels log checked, from what I saw your treadmill has a different protocol from the ones that I already implemented. Could you please follow this guide https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device with an app that already works with it? Thanks!

**Comment by tom-pauwels** [comment]
[Uploading bugreport-NE2213EEA-SKQ1.221119.001-2023-11-15-14-07-21.zip…]()

**Comment by cagnulein** [comment]
please @tom-pauwels wait the finish of the upload process, otherwise the file is corrupted

**Comment by tom-pauwels** [comment]
[bugreport-NE2213EEA-SKQ1.221119.001-2023-11-15-14-07-21.zip](https://github.com/cagnulein/qdomyos-zwift/files/13365635/bugreport-NE2213EEA-SKQ1.221119.001-2023-11-15-14-07-21.zip)

**Comment by cagnulein** [comment]
log checked but unfortunately there isn't the hcisnoof file on it. Did you
enable that setting?
Could you please try again?
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 15 nov 2023 alle ore 15:03 Tom Pauwels <
***@***.***> ha scritto:

**Comment by tom-pauwels** [comment]
[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/13368551/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
thanks, i will check this tomorrow!

**Comment by cagnulein** [comment]
[btsnoop_hci_20231115_162941.cfa.zip](https://github.com/cagnulein/qdomyos-zwift/files/13373769/btsnoop_hci_20231115_162941.cfa.zip)
ok this is the right one, i'm checking

**Comment by cagnulein** [comment]
ok @tom-pauwels enable the "JTX Fitness Sprint Treadmill" setting in the iconsole settings in QZ and restart it. Let me know if it's any better

**Comment by cagnulein** [comment]
also in the bug report there is the confirmation that adb is working right
` QZ:AdbRemote: notifyConnectionEstablished`

we're near!

**Comment by tom-pauwels** [comment]
Oke, thanks. I will check this this evening. I am not at home right now.

**Comment by tom-pauwels** [comment]
Hello, enabling "JTX Fitness Sprint Treadmill" in the settings did not change anything. No data from the treadmill is showing in the app.

**Comment by cagnulein** [comment]
that's strange! could you please attach a debug log from QZ in this scenario? I would like to check if the behavior has changed correctly.
Thanks

**Comment by tom-pauwels** [comment]
[debug-Fri_Nov_17_10_51_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13390262/debug-Fri_Nov_17_10_51_02_2023.log)

**Comment by cagnulein** [comment]
got the issue: i don't know why, but the firmware of your treadmill is sending 2 bytes max to each frame, so i have to build it up manually.

Last question: in this log that you sent me the tape was at 0 km/h right?

**Comment by tom-pauwels** [comment]
Tape? 
I can change the speed on the treadmill, but it is not reflected in QZ. I tried the speed and incline buttons in QZ but they do not respond.

**Comment by cagnulein** [comment]
tape= treadmill :)



> I can change the speed on the treadmill, but it is not reflected in QZ. I tried the speed and incline buttons in QZ but they do not respond.

yes I mean, in the log https://github.com/cagnulein/qdomyos-zwift/files/13390262/debug-Fri_Nov_17_10_51_02_2023.log that you sent me, did you start the treadmill from the treadmill itself? i saw the speed always at 0 in the frames from the treadmill (i'm not checking the tiles, i'm checking the raw data from the treadmill)

**Comment by tom-pauwels** [comment]
Yes, I have to push the Start button on the treadmill itself. The treadmill start speed is 1km/h. I can change the speed on the treamill itself, but it is not reflected in QZ

**Comment by tom-pauwels** [comment]
"i saw the speed always at 0 in the frames from the treadmill"
When I use the iConsole+ app on my ipad, the incline and speed is reflected correctly in the app.

**Comment by cagnulein** [comment]
I got it, but did you do this in this log https://github.com/cagnulein/qdomyos-zwift/files/13390262/debug-Fri_Nov_17_10_51_02_2023.log ? If not could you please do it in a new session, I would only to check if I'm already getting the raw data correctly.
Thanks

**Comment by cagnulein** [comment]
ok never mind, I saw everything that i need in this log https://github.com/cagnulein/qdomyos-zwift/files/13363882/debug-Wed_Nov_15_11_52_03_2023.log

**Comment by cagnulein** [comment]
I'm starting the patch, I will let you know later today when I will have a new version!

**Comment by tom-pauwels** [comment]
Thanks!

**Comment by cagnulein** [comment]
@tom-pauwels done! it's building https://github.com/cagnulein/qdomyos-zwift/actions/runs/6902861624
In 30-40 minutes you will see completed. Then you will see the trial apk at the bottom. Give it a test and let me know! Send me a new debug log if it still doesn't work. Thanks

**Comment by tom-pauwels** [comment]
It doesn't work. There are data shown in QZ but they are completely erratic. 
![Screenshot_2023-11-17-12-40-12-02_120113f1488aeb60b5b2ed37e9784b82](https://github.com/cagnulein/qdomyos-zwift/assets/15791596/79e2ae4a-a21b-49a9-a447-bf46637cdfe6)

When I start the treadmill, the data doesn't change in QZ
Do I still have to select the "JTX Fitness Sprint Treadmill" in the settings? I tried this, but then the data remains at zero (like before)

**Comment by tom-pauwels** [comment]
I am not able to create a new log file, I enabled the option and opened the app, but no file is created (not official apk?)

**Comment by cagnulein** [comment]
they are under /Documents/QZ/

Il giorno ven 17 nov 2023 alle 12:45 Tom Pauwels ***@***.***>
ha scritto:

**Comment by tom-pauwels** [comment]
[debug-Fri_Nov_17_12_39_15_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13391257/debug-Fri_Nov_17_12_39_15_2023.zip)

**Comment by cagnulein** [comment]
got the issue @tom-pauwels I'm fixing it

**Comment by tom-pauwels** [comment]
Do I still have to select the "JTX Fitness Sprint Treadmill" in the settings with the new version?

**Comment by cagnulein** [comment]
yes @tom-pauwels 
new build is building https://github.com/cagnulein/qdomyos-zwift/actions/runs/6903722693

**Comment by tom-pauwels** [comment]
Still no data with the "JTX Fitness Sprint Treadmill" setting selected.
[debug-Fri_Nov_17_13_44_31_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13391917/debug-Fri_Nov_17_13_44_31_2023.1.log)

**Comment by cagnulein** [comment]
ops sorry I forgot a condition 
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/6904234825

**Comment by tom-pauwels** [comment]
Please note that everytime I start QZ, the activity is already started without having to press the 'Start' button on the treadmill itself.

**Comment by tom-pauwels** [comment]
In the iconsole+ app, I have to press the start button on the treadmill in order to start the activity in the app.

**Comment by tom-pauwels** [comment]
This seems to be better now. The data of the treamill is showing in QZ. 
One thing though, a few seconds after QZ has started up but the treadmill is not running, there is some dummy data shown in QZ (see screenshot). They go back to zero after a few seconds, but they influence the min/max values of the run.
![Screenshot_2023-11-17-14-30-33-39_120113f1488aeb60b5b2ed37e9784b82](https://github.com/cagnulein/qdomyos-zwift/assets/15791596/308fc455-552d-4325-9736-2c462c5a57c0)

**Comment by tom-pauwels** [comment]
Already a big thank you for the quick support.

**Comment by cagnulein** [comment]
ok perfect, show me the log and i can fix this as well!

**Comment by tom-pauwels** [comment]
[debug-Fri_Nov_17_15_11_59_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13392697/debug-Fri_Nov_17_15_11_59_2023.1.log)

**Comment by cagnulein** [comment]
ok i hope this will be the last one!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/6905145631

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 nov 2023 alle ore 15:13 Tom Pauwels <
***@***.***> ha scritto:

**Comment by tom-pauwels** [comment]
Fingers crossed...

**Comment by tom-pauwels** [comment]
No more data anymore with the lastest version. :(
[debug-Fri_Nov_17_17_23_47_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13394322/debug-Fri_Nov_17_17_23_47_2023.1.log)

**Comment by cagnulein** [comment]
got it, sorry for the issue https://github.com/cagnulein/qdomyos-zwift/actions/runs/6906630393

**Comment by tom-pauwels** [comment]
Still no data. 
[debug-Fri_Nov_17_18_19_42_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13394824/debug-Fri_Nov_17_18_19_42_2023.1.log)

**Comment by cagnulein** [comment]
are you sure you updated it? i saw the same behavior as before

**Comment by cagnulein** [comment]
sorry stpuid me https://github.com/cagnulein/qdomyos-zwift/actions/runs/6907324310

**Comment by cagnulein** [comment]
@tom-pauwels are we ok?

**Comment by tom-pauwels** [comment]
Yes, everything works as requested. Even the Zwift integration works, I only need to disable the 'Virtual device bluetooth' in the experimental settings and then the Wahoo tread is showing up in Zwift. Do you know if the automatic incline works in Zwift with this treadmill?

**Comment by cagnulein** [comment]
great! yes it has auto incline!

Il giorno mer 22 nov 2023 alle 15:21 Tom Pauwels ***@***.***>
ha scritto:

**Comment by tom-pauwels** [comment]
hello, the app is quitting after a few minutes of use with a trail period limit message. I bought the app some weeks ago...

**Comment by cagnulein** [comment]
yes @tom-pauwels the version that you installed it's a trial outside the play store. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and i will unlock it. set the same email address in the email setting in qz 

let me know

**Comment by tom-pauwels** [comment]
mail sent
