### ISSUE TITLE
[REQ] Support for Focus fitness senator 54 iplus treadmill

### ISSUE THREAD

**Issue by tom-pauwels** [cagnulein/qdomyos-zwift#1791]
**Is your feature request related to a problem? Please describe.**
[https://github.com/cagnulein/qdomyos-zwift/issues/1790](url)

**Describe the solution you'd like**
Support for Focus fitness senator 54 iplus treadmill to make it compatible with Zwift, Kinomap,...

**Describe alternatives you've considered**
N/A

**Additional context**
[Uploading bugreport-NE2213EEA-SKQ1.221119.001-2023-11-15-14-07-21.zip…]()

**Comment by cagnulein** [comment]
please use the #1790 also wait for the file to be uploaded before pressing comment otherwise the file will be truncated. thanks
