### ISSUE TITLE
Tour De France Bike does not change resistance with MyWhoosh Program

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#1793]
Hello, I hope you are doing well. My Tour De France bike does not change with the MyWhoosh Program. 
[Debug Log_11_15_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13370653/Debug.Log_11_15_2023.zip)

**Comment by cagnulein** [comment]
hi @LDHig you have the zwift erg setting enabled in qz, you have to turn it off for free ride on mywhoosh
let me know

**Comment by LDHig** [comment]
It works with the free rides. Thanks for all your help :-)
