### ISSUE TITLE
Support for treadmill NordicTrack Z1300i (Bluetooth only model NTL99418.0)

### ISSUE THREAD

**Issue by JosePadron** [cagnulein/qdomyos-zwift#1805]
**Is your feature request related to a problem? Please describe.**
* No problem. Device is just not supported yet. 

**Describe the solution you'd like**
* Add support treadmill NordicTrack Z1300i

**Describe alternatives you've considered**
* None

**Additional context**
* Treadmill info:
   * Max incline: 12%
   * Max speed: 12 miles/h (19.3 Km/h)

* Steps during Bluetooth HCI snoop log:
   * Increase incline 0.5 percent up to 4.0%
   * Increase speed 0.1 miles/hour up to 3.0 miles/hour

* Log file:
   * `CE:DD:B5:2E:16:49 [  LE  ] I_TL`
[hci_snoop_2023_11_22_07_45_33.cfa.zip](https://github.com/cagnulein/qdomyos-zwift/files/13439940/hci_snoop_2023_11_22_07_45_33.cfa.zip)

**Comment by cagnulein** [comment]
thanks! i will check this tomorrow!

Il giorno mer 22 nov 2023 alle 14:22 Jose Padron ***@***.***>
ha scritto:

**Comment by JosePadron** [comment]
Data seems to be in byte 11 and 12 for the incline and velocity.  Values are multiplied by 100. 

Byte 10 is set to 2 for incline, and is set to 1 for speed. 

* Example 0.5% Incline (Raw data is 50):
0000   02 03 00 1b 00 17 00 04 00 12 0e 00 ff 0d 02 04   ................
0010   02 09 04 09 02 01 *02* **32 00** 00 44 00 00 00 00 00   .......2..D.....

* Example 4.0% incline (Raw data is 400):
0000   02 03 00 1b 00 17 00 04 00 12 0e 00 ff 0d 02 04   ................
0010   02 09 04 09 02 01 *02* **90 01** 00 a3 00 00 00 00 00   ................

* Example 3 mph speed (raw data is 482, 4.82 kmh = 3mph):
0000   02 03 00 1b 00 17 00 04 00 12 0e 00 ff 0d 02 04   ................
0010   02 09 04 09 02 01 *01* **e2 01** 00 f4 00 00 00 00 00   ................

**Comment by JosePadron** [comment]
It looks like you need to update `proformtreadmill.cpp` to have one more condition in `forceIncline` and `forceSpeed`. 
Incline data and speed bytes doesn't need to be updated.
```c

} else if (nordictrack_z1300i_treadmill) 
   // Nothing to do; data is valid
} else {
   write[14] = write[11] + 0x12;
}
```

**Comment by JosePadron** [comment]
I found configuration: https://github.com/cagnulein/qdomyos-zwift/pull/1817  Small change to just update the label.
