### ISSUE TITLE
Qdomyos[BUG]

### ISSUE THREAD

**Issue by Blink2661** [cagnulein/qdomyos-zwift#1807]
**Describe the bug**

This is in reference to doing Powerzone rides using auto resistance. 

Auto resistance seems to be following the ride correctly, where the target powerzone will automatically set the resistance based on my cadence. 

Problem is that my target powerzone, current powerzone, and heart rate are usually colored yellow instead of green, indicating I’m outside of the prescribed range. It seems to work better in zone 1 and 2, than in zones 3+. It seems like to be in the green, I have to drop my current zone lower

For example, if the prescribed zone is 3.5 and I’m riding 3.5, I’ll have to drop down to 2.9 to get it to turn green. 

**To Reproduce**
[debug-Tue_Nov_21_06_07_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13444298/debug-Tue_Nov_21_06_07_04_2023.log)
[debug-Tue_Nov_21_06_07_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13444301/debug-Tue_Nov_21_06_07_04_2023.log)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @blink2661 

the heart color is not about the current workout, but it's about your heart zones.
the power zone color and the target power zone color are not about the current workout, but they're about your FTP setting

if you would like to change this behavioir, do a pool on the facebook group and I can add a setting to add this ability if others are interested on this

Let me know!

**Comment by Blink2661** [comment]
I see. I thought it had worked like target resistance and cadence colors. Thank you for explaining. You’ve done a great job with the app and it’s much appreciated.

**Comment by cagnulein** [comment]
Thanks for your understanding.
Remember to rate the app if you didn't already, it means a lot to me!
Thanks!

Il giorno gio 23 nov 2023 alle 18:19 Blink2661 ***@***.***>
ha scritto:
