### ISSUE TITLE
[BUG]Floating window is not transparent

### ISSUE THREAD

**Issue by k818mn1** [cagnulein/qdomyos-zwift#1810]
**Describe the bug**
The floating window is background is black and does not respond to the transparency setting

**To Reproduce**
Any time the window is enabled

**Expected behavior**
The floating window should be transparent as selected on the transparency setting

**Screenshots**
![Screenshot_20231122_102742](https://github.com/cagnulein/qdomyos-zwift/assets/39540440/ffc45ed3-715a-4b41-a1e5-5a154efd9a06)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: Samsing Z Flip4
 - OS: android
 - Version 13

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks I will check this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 nov 2023 alle ore 14:38 k818mn1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok i guess i did i, i will let you test ASAP

**Comment by cagnulein** [comment]
i created a demo trial version
https://github.com/cagnulein/qdomyos-zwift/suites/18446218544/artifacts/1069579146
if you want to try, uninstall the actual one and install this
you can reinstall the play store one without paying again of course

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 nov 2023 alle ore 14:39 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i tried myself, it worked but let's set the webview with alpha to 1 so you can see the text. i will  update you

**Comment by cagnulein** [comment]
try if it's better for you https://github.com/cagnulein/qdomyos-zwift/suites/18448156705/artifacts/1069717309
it's not possibile to have the full background transparent and the font completely not trasparent. so i don't know if this will be ok for you

**Comment by k818mn1** [comment]
Not really any better. Can't see the text at 50%, and the background is still too dark.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/23/23  9:40 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG]Floating window is not transparent (Issue #1810) 
try if it's better for you https://github.com/cagnulein/qdomyos-zwift/suites/18448156705/artifacts/1069717309
it's not possibile to have the full background transparent and the font completely not trasparent. so i don't know if this will be ok for you

**Comment by cagnulein** [comment]
yes as i said everything will be transparent, it's a android limitation as
far as i know

Il giorno gio 23 nov 2023 alle 19:20 k818mn1 ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
Oh well, thanks for trying. It works very well with a black background anyway. Your app is great, I use it on my Echelon Bike and my Echelon Row.Thanks, Martin Nicholls
-------- Original message --------From: Roberto Viola ***@***.***> Date: 11/23/23  12:21 PM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG]Floating window is not transparent (Issue #1810) 
yes as i said everything will be transparent, it's a android limitation as

far as i know



Il giorno gio 23 nov 2023 alle 19:20 k818mn1 ***@***.***> ha

scritto:
