### ISSUE TITLE
Specify the sport and activity type as "Running" "Treadmill" in .fit file output

### ISSUE THREAD

**Issue by yellowbarchetta** [cagnulein/qdomyos-zwift#1813]
Strava and other services handle "virtual" activities differently to "treadmill" activities.

For a treadmill run recorded by QZ app it would be preferable to have the sport types correctly defined or user-definable so that all of the features of the web services like Strava etc appear.

**Comment by cagnulein** [comment]
you can already do this, you can enable/disable the virtual tag in the advanced setting in QZ. does this cover your request?

**Comment by yellowbarchetta** [comment]
Aha, may well do.  I'll have to experiment.  But thanks for pointing me in that direction; there are sooooo many options in QZ it's not easy to keep track of what is or isn't available!!

**Comment by cagnulein** [comment]
eeheh yeah i can imagine, I started a way to search setting here #1374

**Comment by yellowbarchetta** [comment]
Disabling the virtual flag does seem to do what I wanted it to.  So will close the issue.

**Comment by yellowbarchetta** [comment]
Closing!

**Comment by cagnulein** [comment]
great!

Il giorno ven 24 nov 2023 alle 22:16 yellowbarchetta <
***@***.***> ha scritto:
