### ISSUE TITLE
Cadence is doubled when using the garmin watch app

### ISSUE THREAD

**Issue by yellowbarchetta** [cagnulein/qdomyos-zwift#1814]
When using the QZ watch app to broadcast HR / cadence data from my Garmin 645, the resulting output file reports cadence as double the value it should be.  e.g. 360 rather than 180.

As a workaround I think I'm able to use the "gain" feature in the app, but would be better if it handled the input data normally without doubling.

**Comment by cagnulein** [comment]
under settings, accesories, power sensor, there is a doubling cadence for run and half cadence on strava. Play with them, I guess you will obtain your target
Let me know

**Comment by yellowbarchetta** [comment]
> under settings, accesories, power sensor, there is a doubling cadence for run and half cadence on strava. Play with them, I guess you will obtain your target Let me know

I will play - I thought those settings though were only for cadence from a bike, so I'd overlooked those.  Still I think it's odd that the QZ companion displays "normal" cadence (e.g. 180 - I think it does this) but the app records double.

**Comment by cagnulein** [comment]
it's because each device sends cadence in a different way. these settings are the default one, everyone could decide how they want to see the data. I still don't understand which is the right way to show cadence for running :) So for me is a black hole :) plus i don't have a garmin watch, i developed the garmin app totally blind and you're the first reporting me this (thanks!).

So let's see if we can achieve your target with these settings

**Comment by yellowbarchetta** [comment]
Tried the cadence setting in the "Cadence Gain" setting, but having a different issue with that.  I've got speed gain set to 0.975 (thanks for helping on FB a few days ago with that), but the "Cadence gain" sets itself to the same value even if I overtype and save the value as 0.5.  Tried repeatedly, also rebooted the app and the phone.  Do you want me to log this as a separate bug?

**Comment by cagnulein** [comment]
nope i didn't say the cadence gain, i talked about the
under settings, accesories, power sensor, there is a doubling cadence for
run and half cadence on strava.

Il giorno ven 24 nov 2023 alle 22:19 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
Yes, I noted that but I wanted to try the gain setting first as that was conveniently close to the speed setting gain which works well. After a few more attempts yesterday I got speed gain of 0.975 and cadence gain of 0.5 to "stick" in the settings so next time I will report success. I will then try out the cadence half option too as a separate way of addressing this.

**Comment by yellowbarchetta** [comment]
Cadence doubling resolves the issue for runners.  Probably should be the default setting for runners / cadence.

**Comment by yellowbarchetta** [comment]
Yes, close it down completely.
