### ISSUE TITLE
Allow auto-laps to be recorded by the app

### ISSUE THREAD

**Issue by yellowbarchetta** [cagnulein/qdomyos-zwift#1815]
Simple request, most activity recording apps allow for a user defined (or hard coded) "lap" to be recorded.  When running on the treadmill it can be difficult to hit the manual "lap" button on the screen, and for easy runs paying attention to where you are in a mile / km is quite distracting, so would like to see an option in the settings to define a distance at which point an auto-lap is created and then recorded in the .fit file.

**Comment by cagnulein** [comment]
sounds right. Maybe if the user is playing a workout, this could trigger a lap at the end of each step of the workout, what do you think?

BTW are you on android or ios?

**Comment by yellowbarchetta** [comment]
Android for me.  I don't use the workouts though, but would agree that laps triggered at steps in a workout should also record a "lap" point, in the way that a Garmin watch or zwift (I think) would too.

**Comment by cagnulein** [comment]
just a question: did you already try the lap feature in qz? does it work ok
for you? so adding just the distance trigger will be enough?
I didn't implement this because I saw that strava already split the workout
in laps based on distance (usually 1km) so I guess most of the user will
not use this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 nov 2023 alle ore 11:08 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
Actually I've not tested it so I can do that tonight too.  

Strava does present automatically the splits for individual miles but many other ones do not - e.g. Garmin Connect.

**Comment by cagnulein** [comment]
Ok let me know if it will work so I will proceed with this!
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 nov 2023 alle ore 11:57 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
The lap button works perfectly to record laps properly on Garmin Connect etc, so the implementation is correct.  

So if you are able to implement auto-laps that would be great.

**Comment by cagnulein** [comment]
perfect, i will do in the next days

Il giorno ven 24 nov 2023 alle 22:08 yellowbarchetta <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done @yellowbarchetta 
If you want to try it, install the trial version from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7004204224 whe the build is done (you will find the apk at the bottom of the page).
You need first to uninstall the play store version of QZ (don't worry you can install back without paying again) and then install this one. There is a new setting in the advanced setting called "Auto Lap based on Distance".

Let me know

**Comment by yellowbarchetta** [comment]
That's great, I'll give it a download / test - might not get on the treadmill tonight, but I can run it without me being on there as a test anyway.

**Comment by cagnulein** [comment]
Sounds good.

Il giorno lun 27 nov 2023 alle 12:48 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
By the way, will I lose any settings that I've configured if I uninstall
the play store version and side load the APK instead?

**Comment by cagnulein** [comment]
yes make a backup on the settings page and move the file on another folder
so you will not
lose them

Il giorno lun 27 nov 2023 alle 13:53 yellowbarchetta <
***@***.***> ha scritto:

> By the way, will I lose any settings that I've configured if I uninstall
> the play store version and side load the APK instead?
>

**Comment by yellowbarchetta** [comment]
Thanks.  Not sure how to access this though, I think (may be wrong) that
Android 14 hides away the file system more than Android 13 did.  I can't
extract .fit files from the file system any more (the email option works
fine) and I think that stopped at the same time as I upgraded to Android 14.

**Comment by cagnulein** [comment]
hah ok, the apk version is also fixing this one (that it's in the closed beta on the play store).

**Comment by yellowbarchetta** [comment]
I'm in the beta I think (on play store), is that the same thing as the
closed beta?  ***@***.*** on there, I'm on 2.16.22 if that
helps.

**Comment by yellowbarchetta** [comment]
Tried to install the .apk with the autolaps feature, but after side-loading it and firing it up whenever I clicked on "settings" it did nothing.  Is that "as designed"?  Uninstalled it and reinstalled the play store version, but the closed beta isn't yet there for me.  I'll wait patiently for google!

**Comment by cagnulein** [comment]
the open beta it's the same of the close now, google just released. which
version do you see?

nope the settings must opening, i will check it tomorrow

thanks

Il giorno mer 29 nov 2023 alle 22:26 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
2.16.24 still

**Comment by cagnulein** [comment]
2.16.24 is good, it's the new one. the log are in documents so

Il giorno mer 29 nov 2023 alle 22:32 yellowbarchetta <
***@***.***> ha scritto:

**Comment by yellowbarchetta** [comment]
I tried to find them there, but there were no new files tonight.  The only files in there were from 10 hours ago.  Odd.

**Comment by cagnulein** [comment]
are you sure you were with the 2.16.24 tonight during the workout? maybe
you were on the previous one

just open qz and check if it creates a debug log in the new folder

Il giorno mer 29 nov 2023 alle 22:49 yellowbarchetta <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
> Tried to install the .apk with the autolaps feature, but after side-loading it and firing it up whenever I clicked on "settings" it did nothing. Is that "as designed"?

fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/7042486515

let me know!

**Comment by yellowbarchetta** [comment]
Think the android build has failed?

**Comment by cagnulein** [comment]
yes i'm trying to fixing it, stupid CI that updates something during the
night :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 nov 2023 alle ore 09:15 yellowbarchetta <
***@***.***> ha scritto:

> Think the android build has failed?
>

**Comment by yellowbarchetta** [comment]
Gave it a try last night, seemed to work ok. Only issue was that the trial period thing kept stopping the activities, I'd obviously missed some way of authenticating my purchase history against this test version.  Was expecting to see the screen flash like the manual lapping does, but it didn't. Would be nice to see that confirmed, or maybe create a set of tiles that displays per lap info?

**Comment by cagnulein** [comment]
> Only issue was that the trial period thing kept stopping the activities, I'd obviously missed some way of authenticating my purchase history against this test version.

i don't remember: did you send me an email in order to add your email address to the white list of the app? if not, send me it and I will unlock it.



> Was expecting to see the screen flash like the manual lapping does, but it didn't.

so you would like to see something in the UI too? it complicates the thing but it's doable :)



> or maybe create a set of tiles that displays per lap info?

there are already some tiles about this, check in the tiles settings

**Comment by yellowbarchetta** [comment]
Thanks - email sent to you for whitelist.  Will check out the lap tiles.

Not too bothered about the flashing screen thing, but it's a common aspect to apps that record stuff that they make some alert to the user that a lap has been recorded.

**Comment by cagnulein** [comment]
whitelisted , thanks

yes you are right, i will add it

**Comment by cagnulein** [comment]
toast message added too https://github.com/cagnulein/qdomyos-zwift/actions/runs/7058804495

**Comment by yellowbarchetta** [comment]
All seems to be working.

**Comment by cagnulein** [comment]
perfect! i will merge it!

Il giorno ven 1 dic 2023 alle 20:46 yellowbarchetta <
***@***.***> ha scritto:
