### ISSUE TITLE
 [BUG] App connexion issue with PROFoRM TDF 10.0[BUG]

### ISSUE THREAD

**Issue by Alienabilite** [cagnulein/qdomyos-zwift#1818]
Hi again, I'm sorry I was abroad and not close to my TDF 10.0 so I'm coming back to the installation today. 
I saw a conversation you have with BREARD28 here (https://github.com/cagnulein/qdomyos-zwift/issues/1759), and I just followed the same steps. 

If I quote you, I'm today at this step : 
"so actually the instructions are:
install the companion
set the grand tour pro device in the companion
grant the permission with adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS from a mac or a pc
enable adb debug for qz companion
restart the companion"

install the companion is done. 
What I don't understand is "set the grand tour pro device in the companion". Could you explain what exactly does it mean ? 

Thank you very much for your help !

**Comment by cagnulein** [comment]
hi, you have to select that device in the companion list on the bike

Il giorno sab 25 nov 2023 alle 13:28 Alienabilite ***@***.***>
ha scritto:

**Comment by Alienabilite** [comment]
Ok thank you, so I did it in the Companion
Then, when I run the "grant-permissions.bat" I have this : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/2c7e4bd5-85e4-40fe-a397-de622cd60806)

**Comment by cagnulein** [comment]
you need to open a terminal, go in that folder and then run it

**Comment by Alienabilite** [comment]
I'm sorry but what do you mean by a "terminal" ? I'm in the Command Prompt

**Comment by cagnulein** [comment]
yes open a prompt, go into the dir where you unzipped the master.zip and go to the install package folder and then run that command. run also the adb-debug first

**Comment by Alienabilite** [comment]
Ok, so I just did it. 
But I think I have an issue because when running the abd-debug, it still says that "abd is not recognized" : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/7d173388-8589-4c01-818a-1e0349b229e4)

**Comment by cagnulein** [comment]
did you have the adb.exe in that folder? maybe the antivirus removed it?

**Comment by Alienabilite** [comment]
Yes I have it, however, when I try to run it, I have this error message : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/3cdf3bdf-d912-4c04-8c55-31caf59fb786)

What is strange is that I have the AbdWinApi.dll in the folder, please see below the folder : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/0218821b-c5ab-4457-874d-5d6c4d515e2c)

**Comment by cagnulein** [comment]
you are running from a compressed folder. unzip to c:\ for example and then use a terminal to run it from there

**Comment by Alienabilite** [comment]
Ok perfect !
It seems that the machine refused the connection.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/fd67e36b-90a7-4a7c-b278-44dfe2032075)

When I run the permission : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/dd0e8e26-2a65-49fd-b7b7-40552d0f4642)

**Comment by cagnulein** [comment]
did you enable adb on the bike?

**Comment by Alienabilite** [comment]
Could you remind me how to do it because I followed all the steps so I think it should be fine but not sure which steps allow abd on the bike
