### ISSUE TITLE
[REQ] Auto Incline for Treadmill: XTERRA TRX3500

### ISSUE THREAD

**Issue by iamdmf** [cagnulein/qdomyos-zwift#1819]
Hi Roberto,

I reached out to you on Facebook to help with the compatibility of your QZ app and my smart treadmill the XTERRA TRX3500. I really want to be able to use the hack you’ve shown in your Zwift video whereby you can enable auto inclines transmitted by the Zwift app. I currently use the following equipment:

Treadmill - XTERRA TRX3500 - Speed/ Incline
Apple iPhone 15 Pro Max - To run QZ.
Apple iPad Pro - To run Zwift 
Apple Watch Series 8 - Heart Rate
Stryd Footpod Next Gen - Power / Cadence / Speed

I’ve attached the BLE information screenshots that I believe you need to make the requested possible.

Many thanks for your help with this issue. It’s very much appreciated.

Thanks & Kind regards,
David
![IMG_0401](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/5b70a2e3-38e8-4ea9-a2e0-099787e86e2f)
![IMG_0400](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/dc80591e-98f4-4145-8650-c9704c1fdb63)
![IMG_0399](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/f257f04a-a406-44d3-906b-781857402039)
![IMG_0398](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/33acf0ae-0929-4ab4-974f-0c256659b899)
![IMG_0397](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/89e4863e-faad-4ceb-b3ea-8cbe77ea7b2f)
![IMG_0396](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/1c152a72-5eee-4376-bf7e-d9fef13236df)
![IMG_0395](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/8c726a22-83f4-440a-b6cd-c16621c98c6f)
![IMG_0394](https://github.com/cagnulein/qdomyos-zwift/assets/152033245/20a073ba-a5ba-4bbf-b3b4-b14f698beaed)

**Comment by cagnulein** [comment]
thanks ! i will check it asapInviato da Apple WatchIl giorno 25 nov 2023, alle ore 21:41, iamdmf ***@***.***> ha scritto:
Hi Roberto,
I reached out to you on Facebook to help with the compatibility of your QZ app and my smart treadmill the XTERRA TRX3500. I really want to be able to use the hack you’ve shown in your Zwift video whereby you can enable auto inclines transmitted by the Zwift app. I currently use the following equipment:
Treadmill - XTERRA TRX3500 - Speed/ Incline
Apple iPhone 15 Pro Max - To run QZ.
Apple iPad Pro - To run Zwift
Apple Watch Series 8 - Heart Rate
Stryd Footpod Next Gen - Power / Cadence / Speed
I’ve attached the BLE information screenshots that I believe you need to make the requested possible.
Many thanks for your help with this issue. It’s very much appreciated.
Thanks & Kind regards,
David
IMG_0401.png (view on web)
IMG_0400.png (view on web)
IMG_0399.png (view on web)
IMG_0398.png (view on web)
IMG_0397.png (view on web)
IMG_0396.png (view on web)
IMG_0395.png (view on web)
IMG_0394.png (view on web)

**Comment by cagnulein** [comment]
hi @iamdmf I checked now that I'm home: TRX3500 it's already implemented in QZ. Download it and let me know if you have any issues!

**Comment by iamdmf** [comment]
Hi Roberto, thanks for confirming I’m at a Xmas party today. Hoping to test tomorrow but depends on how much wine I consume! Thanks for your help 😃

**Comment by iamdmf** [comment]
Hi Roberto, I've tried testing a few times now but not having much luck.

QZ recognises all of my devices however I can't get it to control the treadmill. It flashes red on the start icon then seems to disconnect in a loop. I've removed virtual device as per the start screen instructions but no luck.

I've done the work around in Zwift and have seen the inclination triangle flashing etc but when I press start my avatar remains still. 

I'm running QZ on my iPhone 15 Pro Max, not sure if because it's a fairly new phone that would effect anything? 

Also just to check when I pair everything in ride I'm pairing to my iPhone or the other devices such as wahoo tread etc?

The only thing I can't see in ride is the controls. Nothing appears when I try to pair in that option? 

Any advice please?

Thanks,
David

**Comment by cagnulein** [comment]
could you please attach a debug log following this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ? I have also another idea in mind if the current implementation doesn't work

**Comment by iamdmf** [comment]
I've added the various bug logs of the different options I've tried. Hopefully this will help. Thanks!!
