### ISSUE TITLE
CV-390 compatibility

### ISSUE THREAD

**Issue by jeremy10tie** [cagnulein/qdomyos-zwift#182]
hello, I have a quick question I have a care CV-390 bike which has one resistance per motor (numeric) and I would like to know if the resistance changes automatically with zwift without giving a value? thanks

**Comment by cagnulein** [comment]
it could be possible but i need some more information about your bike. @jeremy10tie could you please install nrfconnect app on your mobile and send me here some screenshot?
Thanks

**Comment by cagnulein** [comment]
@jeremy10tie any follow ups?

**Comment by cagnulein** [comment]
@jeremy10tie  ?

**Comment by cagnulein** [comment]
feel free to reopen this
