### ISSUE TITLE
[BUG] Echelon 4s+ qz freezing, not reading resistance

### ISSUE THREAD

**Issue by cqmetal** [cagnulein/qdomyos-zwift#1820]
[debug-Fri_Nov_24_13_25_01_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13465512/debug-Fri_Nov_24_13_25_01_2023.log)

My setup:
Qz app purchased from the Amazon app store (latest version)
Echelon 4s+ bike with "hacked" built-in glory star nebula tablet running Android 9.0

Problem:
Qz usually doesn't read resistance from the bike (starts and stays at 0 or 1 for native resistance and 0 for peloton resistance).  Rarely it will read it for the first 30 or so seconds, but that is it.
Elapsed time will count up but will eventually stop, usually the first time I turn the red knob (but not always) to change the resistance.  Once the resistance and elapsed time freezes it does not move from there.
Once frozen, I can feel and hear the resistance changing on the bike when I turn the red knob but qz doesn't respond.

Troubleshooting steps:
Reinstalled qz
Tried beta qz app
Turned off battery optimization in Android
Disabled "auto-resistance" in the upper right hand corner of qz
Tried the "start paused" option and then started the ride manually
Downloaded an app called EchoBTStats from the amazon app store which is able to read and follow the resistance without issue (so I don't think it's the bike).

**Comment by cagnulein** [comment]
hi, i checked the log and i saw resistance changing from 1 to 4 to 6 to 7.
don't you see it in the tiles?
I don't understand the issue, could you please make a video?

Il giorno dom 26 nov 2023 alle 01:09 cqmetal ***@***.***> ha
scritto:

**Comment by cqmetal** [comment]
Then it froze and wouldn't change from there. Also the elapsed time stopped
counting.

Sometimes it freezes right away. Sometimes it takes some time (always less
than one minute).
Once it freezes, the bike still responds to changes in resistance (I can
hear it and feel it) though qz does not.

I will repeat and send a video and log.

**Comment by cagnulein** [comment]
ok try to disable the virtual bluetooth device setting in the experimental settings and restart qz
let me know

**Comment by cqmetal** [comment]
Disabling virtual bluetooth seems to have solved the problem.  Thank you.

Do you mind explaining what that option does?

**Comment by cagnulein** [comment]
Glad it worked!
That’s the setting to send metrics over Bluetooth but probably your tablet
doesn’t have the hardware specs to do so. That’s why other simpler apps
worked, because they don’t sdo this kind of things

Il giorno dom 26 nov 2023 alle 17:30 cqmetal ***@***.***> ha
scritto:

**Comment by cqmetal** [comment]
I have my qz settings exactly the way I want them. Is there a way I can
back up my profile off my device? I am able to transfer files off my
tablets.

**Comment by cagnulein** [comment]
sure @cqmetal in the settings page there is a icon to save them in the top right corner

**Comment by cqmetal** [comment]
Thank you. I found that. Is there a specific file that contains the
settings that I can offload off the tablet (in case the tablet stops
working)?

**Comment by cagnulein** [comment]
that button saves the profile under the profiles subfolder so you can backup it
