### ISSUE TITLE
My avatar does not move in swift. Tdf1.0 .

### ISSUE THREAD

**Issue by Arnie1a** [cagnulein/qdomyos-zwift#1821]
**Describe the bug**
I spoke with Roberto and he advised me to log a new issue. QZ seems to connect coorectly to the bike. When I launch Zwift, it does not see me tdf but Roberto advised me to choose the Kickr. 
Then I choose a stage, see my avatar but he does not move. Roberto asked me if I could see the wattage in QZ and it seems not. See screen copy 
![IMG_4156] and log file as requested. Thanks 
Arnaud 
(https://github.com/cagnulein/qdomyos-zwift/assets/152060517/feb4e013-86b5-4f23-a75f-e158e9f28aad)
![IMG_4155](https://github.com/cagnulein/qdomyos-zwift/assets/152060517/8c9c2d0d-303e-4ca1-926b-71ab91628341)
[debug-dim__nov__26_09_56_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13466346/debug-dim__nov__26_09_56_33_2023.log)
![IMG_4156](https://github.com/cagnulein/qdomyos-zwift/assets/152060517/3b903a79-4590-4812-a6b8-efb02edba8d7)
![IMG_4155](https://github.com/cagnulein/qdomyos-zwift/assets/152060517/fe1e3548-981e-491f-8a81-c14eaa499590)
[debug-dim__nov__26_09_56_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13466352/debug-dim__nov__26_09_56_33_2023.log)

**Comment by cagnulein** [comment]
@Arnie1a could you please enable the speed based on power setting in the bike setting? let me know if it's the same

**Comment by Arnie1a** [comment]
I have no settings anywhere. The bike connects to IFIT and IFIT recognize the bike. I have no other settings…Arnaud Envoyé de mon iPhoneLe 26 nov. 2023 à 11:44, Roberto Viola ***@***.***> a écrit :﻿
@Arnie1a could you please enable the speed based on power setting in the bike setting? let me know if it's the same

**Comment by cagnulein** [comment]
the setting is in qz, under the bike section

**Comment by cagnulein** [comment]
@Arnie1a did you solve it?

**Comment by cagnulein** [comment]
Nope your bike doesn't have erg mode, or at least not in the firmware. I can virtualise it, but it requires that you provide me an erg table.
Let's first do some rides and then we can go on if you want
Let me know

**Comment by cagnulein** [comment]
@Arnie1a are we ok with this?
