### ISSUE TITLE
Hammer Q.Vadis (10.0)

### ISSUE THREAD

**Issue by VinCe59Muc** [cagnulein/qdomyos-zwift#1824]
### Discussed in https://github.com/cagnulein/qdomyos-zwift/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **mistersoftee** August 25, 2023</sup>
Hi Roberto,

I have a Hammer Q.Vadis treadmill with bluetooth and Zwift integration. Unfortunately it's has no auto-incline or speed. I tried to use it with QZ and the tiles are showing up as soon as I power on the treadmill, but it doesn't show metrics. If I press the start button, the treadmill starts. But the speed and cadence functions doing weird things. And if I change settings on the treadmill, the tiles stay at 0. 

Is there anything I can do in the options to get it running?

Best 
Stefan
</div>

Hi Roberto,
I own a Hammer q.vadis 10 treadmill with Bluetooth embedded. It works properly with Zwift (Zwift retrieves infos from the treadmill). I purchased your app on iOS to be able controlling both incline and speed. Your app recognises the treadmill immediately and connects to it ("FS-AECEEC found"). The Start button initiates a run on the machine but then all metrics are kept to 0. Pressing "+" for the incline sets the machine to 1% but the app keeps showing "0.0". Trying to increase the speed will set the incline back to 0. It seems your app sends absolute values based on what it reads from the treadmill. Is there a specific setting to use for making your app compatible with these treadmills? (I tried "Forcing using FTMS" in the Bodytone Treadmill Options for instance...)
Many thanks in advance!
 VinCe

**Comment by cagnulein** [comment]
@VinCe59Muc please attach a debug log, thanks

**Comment by VinCe59Muc** [comment]
Hi Roberto! Here is a debug log of a test session. Thanks in advance!
[debug-Sun_Nov_26_12_41_55_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13466659/debug-Sun_Nov_26_12_41_55_2023.log)

**Comment by cagnulein** [comment]
thanks i will check it in the next days

Il giorno dom 26 nov 2023 alle 12:50 VinCe59Muc ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@VinCe59Muc in the fitshow setting under the treadmill settings, enable the anyrun setting and restart QZ. Let me know if it's better

**Comment by VinCe59Muc** [comment]
Hi Roberto! Just did the test: enabled "AnyRun" in "Fitshow Treadmill Options", unfortunately it behaves the same. Tried also the "Relaxed Bluetooth for mad devices" under "Experimental Features": no improvement. Log is attached (AnyRun enabled). I hope this can help.

Thanks!
 VinCe

[debug-Tue_Nov_28_16_49_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13490277/debug-Tue_Nov_28_16_49_19_2023.log)

**Comment by cagnulein** [comment]
ok @VinCe59Muc I guess your treadmill has a different protocol. I would like to send you a new beta where you can set your treadmill under settings, treadmill, FTMS treadmill. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks!

**Comment by VinCe59Muc** [comment]
Hi Roberto! Just tried the beta you sent (2.16), enabled the FTMS treadmill. It still does not display the proper speed in the app (remains 0.0) but in the logs (see attached) I can see the proper value appearing ("Current Speed: 4").
Cheers,
 VinCe
[debug-Wed_Nov_29_19_15_42_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13504266/debug-Wed_Nov_29_19_15_42_2023.log)

**Comment by cagnulein** [comment]
got the issue , i will fix it tomorrow
thanks

Il giorno mer 29 nov 2023 alle 19:26 VinCe59Muc ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
version sent! let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 nov 2023 alle ore 19:36 cagnulein ***@***.***> ha
scritto:

**Comment by VinCe59Muc** [comment]
Hi Roberto! Some updates regarding the last version you sent (2.16 (672)). Tested on both iPhone and iPad. The speed is now being displayed properly by your app, also if the speed is adjusted directly on the treadmill it is reflected properly in the app. Some issues though:
- When adjusting the speed from your app (+/-0.1 km/h) the machine does three (3) beeps (like during the startup phase) and then applies the speed. This lasts some seconds so it is basically impossible to adjust the speed rapidly from the app (it takes to much time between each increment)
- When adjusting the inclination from your app (e.g. +1%) it works as well, but with the beeps as described above. Here when setting it back to 0% from the app (no inclination) the treadmill does it, shows 0% but your app keeps displaying 1%. Tried with 2%: it works as well, but setting it back to 0% still shows 1% in your app.
- The heart rate displays weird values, like increasing every second by 1, sometimes showing negative values (it's like this value spans between -127 and +128 (8 bits signed?))
I did a Zwift training using your app, adjusting the speed directly on the treadmill is reflected perfectly in your app and in Zwift. Is it possible, when performing a workout with Zwift in which all intervals are pre-set to specific speed values, to have your app controlling the speed of the treadmill automatically? (I actually installed the app with this perspective / goal in mind)

Attached a debug log for the behaviours listed above.

Cheers,
 VinCe 
[debug-Sat_Dec_2_10_18_32_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13534000/debug-Sat_Dec_2_10_18_32_2023.log)

**Comment by cagnulein** [comment]
> * When adjusting the speed from your app (+/-0.1 km/h) the machine does three (3) beeps (like during the startup phase) and then applies the speed. This lasts some seconds so it is basically impossible to adjust the speed rapidly from the app (it takes to much time between each increment)

you can change the 0.1 step in the treadmill settings in qz!



> * When adjusting the inclination from your app (e.g. +1%) it works as well, but with the beeps as described above. Here when setting it back to 0% from the app (no inclination) the treadmill does it, shows 0% but your app keeps displaying 1%. Tried with 2%: it works as well, but setting it back to 0% still shows 1% in your app.

checked and the treadmill is sending 1%! i don't know why, it seems a firmware bug to me :)





> * The heart rate displays weird values, like increasing every second by 1, sometimes showing negative values (it's like this value spans between -127 and +128 (8 bits signed?))

fixed! I will send you another one for this



> * Is it possible, when performing a workout with Zwift in which all intervals are pre-set to specific speed values, to have your app controlling the speed of the treadmill automatically? (I actually installed the app with this perspective / goal in mind)

yes, check this https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F

**Comment by cagnulein** [comment]
@VinCe59Muc are we ok with this?

**Comment by mistersoftee** [comment]
Hi and thanks to both of you figuring out a lot. I got it basically working now.

What I mentioned:

Every change from the tiles in the app seems to send a start request to the treadmill. It behaves like it’s starting a workout (3 beep countdown).

Regard the inclination, that’s a bug in the treadmill firmware. I also see it in Strava after ending a Zwift session. As soon I change incline, it doesn’t go back to zero and always sends 1 as minimum incline.

Thanks a lot

**Comment by cagnulein** [comment]
Hi @mistersoftee great! i can remove the request on the treadmill if you like it. Let me know if you are interested. Are you on android or ios?

> Regard the inclination, that’s a bug in the treadmill firmware. I also see it in Strava after ending a Zwift session. As soon I change incline, it doesn’t go back to zero and always sends 1 as minimum incline.

hah ok!

**Comment by mistersoftee** [comment]
I did a run and would like to test it without the start request on each change. I am on iOS.

Apart from the triggered start sequence, which is more or less only a lot beeping, it does what I want. I do mostly free runs and I have auto incline now. That’s great 😃
