### ISSUE TITLE
[BUG] bowflex C7 not loading metrics in qz

### ISSUE THREAD

**Issue by Asink48** [cagnulein/qdomyos-zwift#1826]
[debug-Sun_Nov_26_09_10_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13467219/debug-Sun_Nov_26_09_10_06_2023.log)

**Describe the bug**
Metrics are not loading in qz 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung s22 ultra 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi, this log is truncated, do you have another one?

**Comment by Asink48** [comment]
Let me know if this one works

**Comment by cagnulein** [comment]
i don't see any new files :(

**Comment by Asink48** [comment]
[debug-Sun_Nov_26_09_34_53_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13467360/debug-Sun_Nov_26_09_34_53_2023.log)

**Comment by cagnulein** [comment]
`errorConnectionErrorError occurred trying to connect to remote device."`

on nrfconnect are you able to connect to it?

**Comment by Asink48** [comment]
Is this in the settings in qz? I can't find it

**Comment by cagnulein** [comment]
no nrfconnect is a free app on the store

**Comment by Asink48** [comment]
![Screenshot_20231126_102033_nRF Connect](https://github.com/cagnulein/qdomyos-zwift/assets/152081983/e65b4b23-a878-4344-9b12-262af0121539)

It is showing up but it doesn't look like I can connect to it

**Comment by cagnulein** [comment]
So unfortunately this firmware is bugged in a so hard way! I suggest to
contact their support, they completely broken the connection with any other
app in this way :(

Il giorno dom 26 nov 2023 alle 17:21 Asink48 ***@***.***> ha
scritto:

**Comment by Asink48** [comment]
I appreciate your help! I hope they fix it so I can use QZ again.

**Comment by cagnulein** [comment]
Ok I'm leaving this open, let me know if they will do something!
