### ISSUE TITLE
[REQ] Yesoul g1 plus support

### ISSUE THREAD

**Issue by LamCH89** [cagnulein/qdomyos-zwift#1827]
Hello. Sorry for my bad English. I'm using yesoul g1 plus. When i use Eshare app android, the app just show "no device found", so i can't connect to my bike to install app on bike to use with QZ app. My phone turn on bluetooth, location, same wifi as bike and not connect to bike, and the bike just show the screen with qr code.

**Comment by cagnulein** [comment]
hi @LamCH89 please refer to this ticket https://github.com/cagnulein/qdomyos-zwift/issues/1443
