### ISSUE TITLE
Req: Fanspeed as XML Tag for Treadmill

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#183]
**Describe the bug**
Would be nice to add Fan Speed to the Training Program XML file

**Expected behavior**
Fan Speed can be changed on each step of the Training Program

**Comment by cagnulein** [comment]
@ErnieV done! i didn't tried already ;) i will do one of this evening.

**Comment by cagnulein** [comment]
@ErnieV did you test it? can we close this?

**Comment by ErnieV** [comment]
Test it? Is it already deployed in the IOS app?
I wasn’t aware, I will test it ASAP! What is the xml tag?

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
yes, which is your icloud email address? send me it to
roberto.viola83@gmail.com

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 mar 2021 alle ore 13:16 ErnieV <notifications@github.com>
ha scritto:

**Comment by ErnieV** [comment]
Erwin.velthuis@unity-bi.nl
Are you using TestFlight Beta testing?

Verstuurd vanaf mijn iPhone

**Comment by ErnieV** [comment]
I also found a small bug when registering with Strava.
I’ll report in when I find some time.

Regards,
Erwin Velthuis 

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
yes i'm using test flight. I added you!

**Comment by ErnieV** [comment]
I tested it, it works perfect!
