### ISSUE TITLE
No power with Saris/Cyclops trainer. 

### ISSUE THREAD

**Issue by arosemeier** [cagnulein/qdomyos-zwift#1831]
Saris/ cycleops hammer trainer no longer showing power in qz or zwift 

Trainer connects,  cadence shows up but resistance never changes and no power is reported on qz app or in zwift. 

Tried several restarts / settings, nothing seemed to restore power. 

 - OS:IOS 

**Smartphone (please complete the following information):**
 - Device: Iphone XS
[debug-Sat_Nov_25_15_33_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13476772/debug-Sat_Nov_25_15_33_31_2023.log)

 - OS 17.1.1

**Comment by cagnulein** [comment]
watt gain is 0, set it to 1. that's the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 27 nov 2023 alle ore 16:10 arosemeier <
***@***.***> ha scritto:
