### ISSUE TITLE
[BUG]proform 10.0

### ISSUE THREAD

**Issue by Fred1100r** [cagnulein/qdomyos-zwift#1832]
Bonjour
Ci joint le journal de debug
J espere que j ai bien fait….
Impossible de me connecter a mon proform 10.0 TDF
Merci d avance 
[debug-lun__nov__27_21_29_07_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13480277/debug-lun__nov__27_21_29_07_2023.log)

**Comment by cagnulein** [comment]
hi, you have to set the ip of your bike under settings, bike, proform, tdf
companion ip. press ok and restart qz

also be sure to have installed the qz companion on the bike

let me know

Il giorno lun 27 nov 2023 alle 22:00 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
Quelle rapidite 😎La tablette du velo  est verrouillée Je ne peut rien installer dessusJe n ai qu IFIT defaut
Cordialement F BailleulACE
Envoyé de mon Iphone


Le lundi, novembre 27, 2023, 22:04, Roberto Viola ***@***.***> a écrit :



hi, you have to set the ip of your bike under settings, bike, proform, tdf
companion ip. press ok and restart qz

also be sure to have installed the qz companion on the bike

let me know

Il giorno lun 27 nov 2023 alle 22:00 Fred1100r ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
no you can, following this
Nordictrack Treadmills Wifi only finally compatible with Zwift using QZ
https://youtu.be/_KRMSHxo5AQ

Il giorno lun 27 nov 2023 alle 22:08 Fred1100r ***@***.***>
ha scritto:

> Quelle rapidite 😎La tablette du velo  est verrouillée Je ne peut rien
> installer dessusJe n ai qu IFIT defaut
> Cordialement F BailleulACE
> Envoyé de mon Iphone
>
>

**Comment by Fred1100r** [comment]
OkMerci pour l infoJ ai deverouille la tablette et installer l appli ( parfait merci)Mais toujours pas rien….☹️


Cordialement F BailleulACE
Envoyé de mon Iphone


Le lundi, novembre 27, 2023, 22:10, Roberto Viola ***@***.***> a écrit :



no you can, following this
Nordictrack Treadmills Wifi only finally compatible with Zwift using QZ
https://youtu.be/_KRMSHxo5AQ

Il giorno lun 27 nov 2023 alle 22:08 Fred1100r ***@***.***>
ha scritto:

> Quelle rapidite 😎La tablette du velo est verrouillée Je ne peut rien
> installer dessusJe n ai qu IFIT defaut
> Cordialement F BailleulACE
> Envoyé de mon Iphone
>
>

**Comment by Fred1100r** [comment]
Comme ca c bon?Merci 

Cordialement F BailleulACE
Envoyé de mon Iphone


Le mardi, novembre 28, 2023, 08:54, Roberto Viola ***@***.***> a écrit :




share a debug log now so i can check if you did everything right

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Fred1100r** [comment]
Dsl
J avais oublié 
Ci joint le journal 
Merci 
🙏🏻
[debug-mar__nov__28_13_07_05_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13487982/debug-mar__nov__28_13_07_05_2023.log)

**Comment by cagnulein** [comment]
ok perfect, I'm seeing the messages coming from the companion correctly. what's the issue? You don't see the metrics changing on QZ? they are still to 0?

**Comment by Fred1100r** [comment]
Oui
Rien ne change
C est etrange le nom qu il trouve en connection 
![IMG_5697](https://github.com/cagnulein/qdomyos-zwift/assets/152221432/45094b13-d47a-4536-98f5-f5d0768a1c8f)

**Comment by cagnulein** [comment]
ok set the c1750 device on the companion and restart the bike
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 nov 2023 alle ore 14:04 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
Rebonjour
Toujours rien
Je pense qu il ne se connecte pas ….

**Comment by cagnulein** [comment]
ok so use this method
https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

it will work for sure

Il giorno mar 28 nov 2023 alle 18:10 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152221432/f58222c4-6c1e-41f4-9da2-c217d6825c32)

j ai installé le companion directement sur la tablette du velo 
Je n arrive donc  pas à appliquer cette methode ….
Je ping le velo a partir du pc mais l application trouve de nombreux appareils aleatoirement

merci encore

**Comment by cagnulein** [comment]
open a terminal windows and go to the installpackage folder than run that
command from there

let me know

Il giorno mar 28 nov 2023 alle 21:56 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
Bonjour
Je n arrive pas a installer sous Windows le fichier install ) qcompanionnorfitrackytesdmill)
Je peux le faire sous Mac mais je ne trouve pas l archive.
Pour l application sur iphone , je l ai egalement téléchargé sur une tablette samsung et meme problème 
Il indique -en connection-et n a trouvé le velo qu une seule fois. Et cela ne marchait pas 
Je désespère 😭🤪
Merci de votre aide

**Comment by cagnulein** [comment]
sorry but i don't understand, what issue do you have? unzip the file and go into the terminal to that folder. where are you blocked?

**Comment by Fred1100r** [comment]
C est bon
J ai tout réinstallé et c est ok
Nikel 👍🙏🏻
Tout est synchronisé sur l appli 
Il me reste a regler zwift car il ne trouve pas 
J ai remis bike tdf 10.0 sur companion

**Comment by cagnulein** [comment]
Super, merci !
let me know if you need help!

Il giorno mer 29 nov 2023 alle 17:01 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
C est bon tout est ok
Merci
Est ce que le velo doit s incliner dans les cotes?
Il faut paramétrer ?

**Comment by cagnulein** [comment]
without zwift, if you're pressing on the resistance or inclination plus tile on qz, are you seeing a touch event on the bike's tablet?

**Comment by Fred1100r** [comment]
Bonjour
Non
Quand je modifie sur le velo c est ok sur Qz mais qyand je tape sur Qz pas de reaction du velo

**Comment by cagnulein** [comment]
because we have to use the adb method that I described above. It could be tricky so be prepared :)

**Comment by Fred1100r** [comment]
Re bonjour
Je pense avoir tout fait et toujours pas d inclinaison et de resistance....
j ai le retour des donnees sur QZ uniquement si je parametre le companion en C1750...
J ai utilise adb debug et idem....
je seche...

**Comment by cagnulein** [comment]
@Fred1100r did you enable the scroll bar for change the inclination and or the resistance in the ifit app?

**Comment by Fred1100r** [comment]
Bonjour
Je ne vois oas où sont ces paramètres dans l appli Ifit..?
Merci du retour

**Comment by cagnulein** [comment]
i don't have an ifit device but it's in the ifit settings, you can write or
search in the qz facebook group about it, there are a lot of user with the
same bike
Let me know

Il giorno dom 10 dic 2023 alle 08:50 Fred1100r ***@***.***>
ha scritto:

**Comment by Fred1100r** [comment]
[debug-mar__janv__2_12_03_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13809378/debug-mar__janv__2_12_03_02_2024.log)

**Comment by cagnulein** [comment]
hi @Fred1100r what should I check here?

**Comment by Fred1100r** [comment]
SalutVous m avez demandé sur messenger d iuvrir un ticket avec le fichier debug Non?Tjs problemeLes valeurs s affichent mais pas de resction sur l appli ( inclinaison , force…)Fonctionne donc avec zwift mais en manuelL auto inclinaison et force  non)
Metci d avance 

Cordialement F BailleulACE
Envoyé de mon Iphone


Le mardi, janvier 2, 2024, 12:20, Roberto Viola ***@***.***> a écrit :




hi @Fred1100r what should I check here?

**Comment by cagnulein** [comment]
@Fred1100r without zwift, if you press the inclination plus button, do you see a reaction on the touchscreen of your bike?

**Comment by Fred1100r** [comment]
NonC est le problème 🙄


Cordialement F BailleulACE
Envoyé de mon Iphone


Le mardi, janvier 2, 2024, 13:37, Roberto Viola ***@***.***> a écrit :




@Fred1100r without zwift, if you press the inclination plus button, do you see a reaction on the touchscreen of your bike?

**Comment by cagnulein** [comment]
so we have 2 ways:
1) do a factory reset, then DON'T update the IFIT app and try again in this way
2) use the adb method, this will require a pc to test the adb connection at least

which one do you want to follow?

**Comment by Fred1100r** [comment]
Avec l adb method ca n a pas fonctionné.Si je fais reset factory , ifit fonctionnera t ilQd meme ?


Cordialement F BailleulACE
Envoyé de mon Iphone


Le mardi, janvier 2, 2024, 13:40, Roberto Viola ***@***.***> a écrit :




so we have 2 ways:
   
   - do a factory reset, then DON'T update the IFIT app and try again in this way
   - use the adb method, this will require a pc to test the adb connection at least

which one do you want to follow?

**Comment by cagnulein** [comment]
I don't know, we have to try. Could I ask you to translate the messages here in english? otherwise other users with the same issue would find hard to check this. Thanks (I'm italian, so english is also not my first language ;) you can use google translator)

**Comment by Fred1100r** [comment]
For sureSorry
Translate :
With the adb method it didn't work.
If I reset factory, will ifit work?
Qd even? 
Cordialement F BailleulACE
Envoyé de mon Iphone


Le mardi, janvier 2, 2024, 13:44, Roberto Viola ***@***.***> a écrit :




I don't know, we have to try. Could I ask you to translate the messages here in english? otherwise other users with the same issue would find hard to check this. Thanks (I'm italian, so english is also not my first language ;) you can use google translator)

**Comment by cagnulein** [comment]
with the reset it should work everything, a lot of user had already do this. Of course each bike could be different, but I can help you!

**Comment by cagnulein** [comment]
@Fred1100r any news?

**Comment by Fred1100r** [comment]
Good morning
After factory reboot
Not carried out Ifit update
Always the same
No auto tilt and force
I'm giving up
Thanks anyway😎
Cordialement F BailleulACE
Envoyé de mon Iphone


Le jeudi, janvier 11, 2024, 10:59, Roberto Viola ***@***.***> a écrit :




@Fred1100r any news?

**Comment by cagnulein** [comment]
ok let me know in case if you want to try again
