### ISSUE TITLE
[BUG] (-10) inclination using swift

### ISSUE THREAD

**Issue by Ccujar** [cagnulein/qdomyos-zwift#1837]
**Describe the bug**
When I’m using swift on my 22si suddenly put the incline (-10)
[debug-Tue_Nov_28_08_05_18_2023.log]
(https://github.com/cagnulein/qdomyos-zwift/files/13490073/debug-Tue_Nov_28_08_05_18_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check it asap

Il giorno mar 28 nov 2023 alle 16:35 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
Thank you for checking the issue.  I downloaded the beta you sent me and now doesn’t go to -10 inclination.  But in swift or with the tiles no change of inclination or resistance at all.  I can do it manually on my bike but no automatic from swift or manually from tiles.  Here is the file
[debug-Thu_Nov_30_08_35_57_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13513757/debug-Thu_Nov_30_08_35_57_2023.log)
[debug-Thu_Nov_30_08_28_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13513758/debug-Thu_Nov_30_08_28_59_2023.log)
![IMG_7831](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/d79a76e6-c295-4379-9966-b6a8a1fb4884)
![IMG_7830](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/e60aeacb-fa5c-4487-b10f-87e3c659d1a5)
![IMG_7829](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/69107db0-5294-4182-b631-84d21c514950)
![IMG_7828](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/7a7602ed-0293-4818-a229-1f311a6521d5)
![IMG_7827](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/15f6a7fc-90a0-4eaf-906d-7941d1ecd1b6)
![IMG_7826](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/16cc5646-0d7a-4dc8-a16b-8788f5bc54cb)

**Comment by Ccujar** [comment]
Last night I have the -10 inclination issue few times on my ride but it was changing the inclination  as MyWhoosh road

**Comment by cagnulein** [comment]
ok but disabling the new setting is now working as the apple store version?
if so i know how i can fix it

Il giorno gio 30 nov 2023 alle 15:43 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
No the tiles

**Comment by cagnulein** [comment]
sorry but i don't understand, please detail which is the difference between this version and the apple store version one with the new setting disabled 

thanks

**Comment by Ccujar** [comment]
Original Version "Apple Store":
When I was using the QZ app only or Swift or MyWhoosh  the bike suddenly goes to (-10 Inclination) few times during the ride.
Only QZ: Inclination or resistance Tiles never work with +or - but it kicks the (-10 Inclination)
Swift or MyWhoosh: When I'm riding kicks the (-10 Inclination) few times I corrected manually and de Inclination works automatically.

Beta Version: with new setup:
Didn't do the (-10 Inclination) either in OZ or Swift but in doesn't automatically change inclination when I'm using swift
OZ only:  Tiles +- don't work either

Beta Version no new setup:   Same as with new setup... no changes on inclination or resistance from tiles

Thank you for taking the time to help me with the issue

Camilo Cujar

**Comment by cagnulein** [comment]
@Ccujar last question: which device did you select on the qz companion?

**Comment by Ccujar** [comment]
S22i
I tried selecting NTEX71021 but no reading on Tiles.

when I deselect the new setting on QZ the companion app jumps the equipment selection to exp 71 treadmill automatically 
![IMG_7844](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/ed73f723-0af6-4658-86e3-bfc61306258b)

**Comment by cagnulein** [comment]
Ok, I'll check it out
thanks

Il giorno ven 1 dic 2023 alle 21:54 Ccujar ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
so you didn't see no inclination or resistnace changing on the bike on both version right? if so we have to use the adb method.
Let me know

**Comment by Ccujar** [comment]
I saw change on inclination only in Apple version when I was using swift.
What is the adb method? So uninstall and install companion again?

**Comment by cagnulein** [comment]
@Ccujar are you still interested in?
