### ISSUE TITLE
[BUG] QZ delay with peloton and Tacx Neo 2

### ISSUE THREAD

**Issue by AnneAstrid88** [cagnulein/qdomyos-zwift#1839]
**Describe the bug**
During a bike workout with Tacx Neo 2 and peloton, I continuously have to add seconds to the peloton time because during the workout a delay occurs. In total it's usually a total of +- 300 seconds I have to add during the ride on a ride of 30 min. 
This was not a problem in 1 of the previous versions of QZ about a month ago (I'm 100% certain it wasn't a problem in 2.16.18). I have not changed anything in my settings.

**To Reproduce**
Connect Tacx Neo 2 and HRM pro to QZ
Connect QZ with Forerunner 955 through ANT+ 
Start peloton workout
Accept Peloton popup in QZ
Start QZ when peloton workout starts

**Expected behavior**
There should not be a delay between the QZ app and the peloton app once I've synced it properly

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Version 2.16.24
 - Peloton is done on Ipad Pro

**Append a debug log**
3 Debug logs below
[debug-Wed_Nov_29_06_28_43_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13498569/debug-Wed_Nov_29_06_28_43_2023.zip)

**Comment by cagnulein** [comment]
are you keeping qz always on foreground?

**Comment by AnneAstrid88** [comment]
Yes, QZ is open and in the foreground the whole time.

**Comment by cagnulein** [comment]
got the error @AnneAstrid88 it seems that your phone is missing some beats

```
Mon Nov 27 06:53:10 2023 1701064390802 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 176current row len104"
Mon Nov 27 06:53:12 2023 1701064392998 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 177current row len104"
Mon Nov 27 06:53:15 2023 1701064395550 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 178current row len104"
Mon Nov 27 06:53:18 2023 1701064398409 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 179current row len104"
Mon Nov 27 06:53:21 2023 1701064401511 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 180current row len104"
Mon Nov 27 06:53:24 2023 1701064404197 Debug: ../src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed 181current row len104"
```

we should see these lines every seconds, but instead some seconds are missing. which phone do you have? maybe it's with a power save mode?

**Comment by AnneAstrid88** [comment]
Device: Pixel 7 Pro
OS: Android 14

It's not in power save mode. 

I believe you said previously that you had the same phone, so you should then have a similar problem?

**Comment by cagnulein** [comment]
here in italy we don't have peloton, it's forbidden. so I can't test this case. i'm checking in your log if i can understand something more

**Comment by AnneAstrid88** [comment]
Ah yes, I also had to buy it through the American Apple store to get it.

If I need to test something specific, let me know.

**Comment by cagnulein** [comment]
@AnneAstrid88 I guess I understood your issue, when this is happening, your trainer is streaming A LOT of data. I have some ideas how to bypass this, but let's try first disabling the debug log setting because for sure it's writing a lot, decreasing the performance.

If this doesn't help, i will do a mod trying to disabling some requests to the trainer.

Let me know how it will go

**Comment by AnneAstrid88** [comment]
Ok I'll try that tomorrow. Thank you. 
It's weird that this issue wasn't there a month ago.

**Comment by cagnulein** [comment]
I didn't change anything in the code, so it could be a patch of android that caused this for example. I have some ideas in mind to avoid this anyway

**Comment by cagnulein** [comment]
@AnneAstrid88 any news? in the mean time I created a patch for this anyway https://github.com/cagnulein/qdomyos-zwift/actions/runs/7060901858

You will see the android build in the bottom when the build is finished, i don't remember if you are in the whitelist of the non-play store version, in case not 
send me an email to roberto.viola83 at gmail.com indicating this ticket  Thanks

**Comment by cagnulein** [comment]
sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7061057203

**Comment by cagnulein** [comment]
Ok perfect  I also created a patch if you would like to test it with the
debug log enabled

Il giorno ven 1 dic 2023 alle 17:33 AnneAstrid88 ***@***.***>
ha scritto:

**Comment by AnneAstrid88** [comment]
Yes I will when the version is available :-)

**Comment by AnneAstrid88** [comment]
I'm sorry, I didn't test it yet. I will try to do it this week.

**Comment by cagnulein** [comment]
@AnneAstrid88 any news?

**Comment by AnneAstrid88** [comment]
I'm so sorry, I haven't tested it yet. I will test it tomorrow on my peloton ride.

**Comment by AnneAstrid88** [comment]
I tested it and it seems to be working. However, I noticed when scrolling through the settings there was the screen was lagging and that never happened before. I wasn't running any other apps at the same time.

**Comment by cagnulein** [comment]
The lagging is not something controllable from QZ. I mean I'm trying with my pixel 6a and it runs smooth. The settings page could be improved for sure, trying to add some subpages in order to reduce the size of the main one
