### ISSUE TITLE
Req: Option to send HR data only

### ISSUE THREAD

**Issue by d-nx** [cagnulein/qdomyos-zwift#184]
I'd love to transmit my HR data to the peloton app (running on my googletv) while recording the workout on QZ.

This way I can save my HR in Peloton but also have QZ upload to my Strava.

This could be achieved by adding a new setting to send only Heart rate.

**Comment by cagnulein** [comment]
@d-nx done. It will be avaiable in the version 2.4.6
There is a new setting called "Virtual Heart Only", you have to enable it and restart the app.
let me know if it will work. Are you already in the beta group?
Remember to close this if it works.
Thanks

**Comment by d-nx** [comment]
I'm already in beta group and will be able to test.

Thanks!

**Comment by cagnulein** [comment]
Ok i will upload today or tomorrow ;)

Il gio 4 mar 2021, 14:08 d-nx <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
@d-nx did you test this? does it work? can we close this?

**Comment by d-nx** [comment]
Will test today and report back!

**Comment by d-nx** [comment]
It works!

**Comment by cagnulein** [comment]
great! could you please make a post about this feature. In order to help other user on FB? Thanks!

**Comment by d-nx** [comment]
Will do.

I have to test it a bit more to make sure my settings are correct.

At first it wasn't working until I played with some of the other settings.

My last settings were like this:
Heart rate outside FTMS (On)
Virtual device (On)
Virtual heart only (On)

Based on your knowledge what settings do you recommend having?

**Comment by cagnulein** [comment]
Yes they are correct


Il giorno sab 6 mar 2021 alle ore 16:59 d-nx <notifications@github.com> ha
scritto:
