### ISSUE TITLE
Holofit connected to echelon row

### ISSUE THREAD

**Issue by chiefsfan58** [cagnulein/qdomyos-zwift#1848]
@RobertKaldenbach fixed! i'm gonna send you a new version! @janabouc i don't know if you are interested on this too. In case let me know

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/issues/876#issuecomment-1207229507_

**Comment by chiefsfan58** [comment]
I am having the same issue. I can connect Holofit to QZ but it doesn’t seem to pass data as there is no movement even though WZ shows data.

**Comment by cagnulein** [comment]
@chiefsfan58 did you enable the virtual rower setting in the experimental settings?

**Comment by cagnulein** [comment]
what do you would like to adjust? speed? I don't know if holofit uses power or speed from QZ, in case speed gain or watt gain anyway
Let me know

**Comment by chiefsfan58** [comment]
Roberto,

It displays min/500m and s/m so not sure whether it uses speed or watt but is there a recommended scale to use? I see it currently set to one should I decrease to 0 or set it to -1?

Thanks,

Steve

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
watt gain is a multiplier so in case set it to 0.5 to have a 50% of wattage

same thing for speed gain

Il giorno ven 1 dic 2023 alle 20:55 chiefsfan58 ***@***.***>
ha scritto:

**Comment by chiefsfan58** [comment]
Perfect, that seems to have done the trick. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
great!
