### ISSUE TITLE
Echelon 2.3.34 regression

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#185]
[debug-Wed Mar 3 21_33_33 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6081855/debug-Wed.Mar.3.21_33_33.2021.log)

**Comment by cagnulein** [comment]
@marklogan17 check if in your log with the current version you have too these

echelonconnectsport::errorConnectionErrorError occurred trying to connect to remote device."

**Comment by marklogan17** [comment]
I tested this with 2.3.34 on iOS and did not see that issue.  I tested on a build from about a week ago for Android and also did not see it.  I am rebuilding Android and will test again later just in case.
