### ISSUE TITLE
[BUG] Nordictrack S20 Treadmill - No speed or incline control

### ISSUE THREAD

**Issue by dxbydy** [cagnulein/qdomyos-zwift#1850]
App connects fine (as I_TL) and displays speed and incline on the tiles but I am unable to change these from the app itself.

Tried all of the Nordictrack treadmill options and none of them allow me to change speed/incline from the app.

App running on a Google Pixel 6a with android 14.

Is it possible to add this treadmill?

Bluetooth snoop attached
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13527726/btsnoop_hci.log)

https://www.fitness-superstore.co.uk/nordictrack-s-20-treadmill.html

**Comment by dxbydy** [comment]
No, the only app running was qz,  the ifit app is not currently installed on the phone.

Attached the debug log and a new hci spoof log below:

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13529744/btsnoop_hci.log)

[debug-Fri_Dec_1_16_20_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13529745/debug-Fri_Dec_1_16_20_36_2023.log)

**Comment by cagnulein** [comment]
Ok so the hci snoof is from an ifit session? If so, I will check it next
week. Thanks

Il giorno ven 1 dic 2023 alle 17:28 dxbydy ***@***.***> ha
scritto:

**Comment by dxbydy** [comment]
No the hci spoof is from treadmill to qz app communication only. Am I meant to use the ifit app for this? Is so I can do so.

The hci spoof is from when I have been manually adjusting the speed and incline on the treadmill (no screen on this one, just the buttons) and seeing the changes in the qz tile values. I have then tried to press the plus and minus in the qz app which has no effect.

**Comment by cagnulein** [comment]
Yes you have to generate an hci snoof using the ifit only with the treadmill, changing speed and inclination from the app directly 
Thanks

**Comment by dxbydy** [comment]
Sorry - didn't realise - thanks again! Ran again with ifit making the changes in speed and incline.

hci spoof attached:

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13530419/btsnoop_hci.log)

There was also another file in the folder with .last appended - I am not sure if it is the older one or a continuation so I attached that too:

[last.btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13530430/last.btsnoop_hci.log)

**Comment by cagnulein** [comment]
Ok, I'll take a look next week
Thanks

Il giorno ven 1 dic 2023 alle 18:32 dxbydy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Thanks, I'll check it out!

Il giorno sab 2 dic 2023 alle 19:11 dxbydy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Glad to hear it! if you want i can unlock this version for you, just write
me an email to roberto.viola83 at gmail.com indicating this ticket.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 dic 2023 alle ore 09:34 dxbydy ***@***.***>
ha scritto:

**Comment by dxbydy** [comment]
Just a quick question - Are the Pause/Start and Stop buttons in the app meant to control the treadmill too or do they just affect the current workout? At the moment the only way to start and stop the treadmill is from the actual machine.

**Comment by cagnulein** [comment]
they should start the treadmill also, i will check in the hci snoof again, i didn't add them indeed

**Comment by dxbydy** [comment]
You are certainly quick with these fixes!

Okay - Start now works although it is initially showing Pause when I load a workout file. If I click pause then it flashes red Start and allows me to start the treadmill.

Clicking Pause then takes the treadmill down to 1mph -  I am not sure if this is required behaviour or not.

**Comment by cagnulein** [comment]
> You are certainly quick with these fixes!


thanks!

> Okay - Start now works although it is initially showing Pause when I load a workout file. If I click pause then it flashes red Start and allows me to start the treadmill.
> 
> Clicking Pause then takes the treadmill down to 1mph - I am not sure if this is required behaviour or not.

nope it's not the right one because i didn't implement the stop event. Did you collect the stop button from the app directly in the hci snoof? I tried to check it but I can't see it

Let me know

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7086710662
try to press start and then stop. it should works so.
so then try to press start and pause let's see if it everything works
R.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 dic 2023 alle ore 13:30 dxbydy ***@***.***>
ha scritto:

**Comment by dxbydy** [comment]
Initially it takes a few presses of start to make it start (it defaults to a pause button when I start the app)

Once started I can change speed and incline. Pressing pause brings it back down to 1mph. 

Pressing Stop takes me to the end workout screen on the qz app but does not stop the treadmill.

**Comment by cagnulein** [comment]
ok let me try a difffernt approach, try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/7087404728

**Comment by cagnulein** [comment]
perfect thanks, i will check it out!

Il giorno lun 4 dic 2023 alle 20:22 dxbydy ***@***.***> ha
scritto:
