### ISSUE TITLE
Can't receive data qbo smart elite b+ trainer using the FTMS bike option

### ISSUE THREAD

**Issue by patricebeaulieu** [cagnulein/qdomyos-zwift#1851]
**Describe the bug**
No data is received from the trainer 

Tried connecting to qbo smart elite b+ trainer but it did not connect to it automatically . Had to use the ftms bike options but no data is received from QD bluetooth connection.

Included a log of me doing a really small training on myETraining apps connected with the bluethoot trainer.

[btsnoop_hci[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13529489/btsnoop_hci.1.log)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: Android G8x THinQ 
 - Android 12

Thank you !

**Comment by cagnulein** [comment]
hi, please attach a debug log from qz as well
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Il giorno ven 1 dic 2023 alle 17:01 patricebeaulieu <
***@***.***> ha scritto:

**Comment by patricebeaulieu** [comment]
[debug-Fri_Dec_1_11_20_28_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13529979/debug-Fri_Dec_1_11_20_28_2023.log)

**Comment by cagnulein** [comment]
Disable it from ftms bike and press ok and instead set it under
accessories, power sensor, and also enable the power sensor as a bike and
restart qz
Let me know

Il giorno ven 1 dic 2023 alle 17:46 patricebeaulieu <
***@***.***> ha scritto:

**Comment by patricebeaulieu** [comment]
Hi   Thanks the app receive the power information & cadence . Should I be able to  adjust the resistance directly on the app ? I don't seem to be able to. Thanks !

**Comment by patricebeaulieu** [comment]
Well the zwift and other apps does change the resistance of the trainer . I wanted QZ to add more resistance to it .

**Comment by cagnulein** [comment]
#1834

**Comment by cagnulein** [comment]
@patricebeaulieu If you are able to do this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device with the Zwift app I will add support as well. It seems that your trainer doesn't have a standard way to change resistance 

Let me know

**Comment by patricebeaulieu** [comment]
Thank you , yes here is the new bluetooth file with zwift
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13530502/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks! I will check it next week!

Il giorno ven 1 dic 2023 alle 18:36 patricebeaulieu <
***@***.***> ha scritto:

**Comment by patricebeaulieu** [comment]
Thank you very much 👌

**Comment by cagnulein** [comment]
perfect @patricebeaulieu this is for free ride, right? could you also do the same for a workout with erg mode enabled?

**Comment by patricebeaulieu** [comment]
Hi @cagnulein For sure . I will send it to you asap . Yes , the one I sent is with free ride .Wish I had your knowledge haha , Are you decoding all this with Wireshark ?

**Comment by cagnulein** [comment]
yes it's a very easy protocol :)

Il giorno sab 2 dic 2023 alle 15:22 patricebeaulieu <
***@***.***> ha scritto:

**Comment by patricebeaulieu** [comment]
Thanks A lot Roberto ,  I won't be able to test the Update right now
because my trainer actually broke ... the thread moving the resistance
magnet was stripped and it was stuck in high gear .I managed to fix the
thread but while repairing I broke the magnet 😅 . I will get back to you
next week when I receive the replacement 👍

**Comment by cagnulein** [comment]
ehehe ok no problem, I hope you will fix it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 dic 2023 alle ore 12:50 patricebeaulieu <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@patricebeaulieu any news?

**Comment by patricebeaulieu** [comment]
Sorry roberto , happy holidays . The trainer is currently in pieces and the
original part to fix it is out of stock at this moment . I bought a tacx
neo 2 at this moment (much better ) . When the part gets back in stock
depending of the shipping price , i will probably order it for my dad . The
fix i tried lasted only one training lol

**Comment by cagnulein** [comment]
Happy Holidays too!
No problem! I was just checking!
In case you can also use the tacx with peloton and qz if you want to ;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 12:55 patricebeaulieu <
***@***.***> ha scritto:
