### ISSUE TITLE
[BUG] not connecting c7

### ISSUE THREAD

**Issue by Bbaeznutrition** [cagnulein/qdomyos-zwift#1853]
[debug-Fri_Dec_1_09_24_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13530496/debug-Fri_Dec_1_09_24_03_2023.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Bbaeznutrition I'm still seeing the manual device set to disabled. Did you press ok and restart qz?
Let me know

**Comment by cagnulein** [comment]
No problem! I will probably asleep but the problem is for sure this one :)

Il giorno ven 1 dic 2023 alle 18:47 Bbaeznutrition ***@***.***>
ha scritto:

**Comment by Bbaeznutrition** [comment]
Here is a screen recording to show what I did (again) and then I hopped on my bike and pedaled with an open manual ride and no data/ connection still Sent from my iPhoneOn Dec 1, 2023, at 9:43 AM, Roberto Viola ***@***.***> wrote:﻿
@Bbaeznutrition I'm still seeing the manual device set to disabled. Did you press ok and restart qz?
Let me know

**Comment by cagnulein** [comment]
I can’t see the attachment from email, you have to attach at the ticket
here in the link at the bottom

Il giorno ven 1 dic 2023 alle 18:50 Bbaeznutrition ***@***.***>
ha scritto:

**Comment by Bbaeznutrition** [comment]
[debug-Fri_Dec_1_09_48_29_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13530646/debug-Fri_Dec_1_09_48_29_2023.log)

**Comment by cagnulein** [comment]
Yes that’s right, but now the issue is that the bike doesn’t talk. Seem an
issue on the bike. Did it work with any other apps?

Il giorno ven 1 dic 2023 alle 18:53 Bbaeznutrition ***@***.***>
ha scritto:

**Comment by Bbaeznutrition** [comment]
It connected to my phone for audio but it didn’t connect to peloton for cadence 🤷‍♀️Sent from my iPhoneOn Dec 1, 2023, at 9:55 AM, Roberto Viola ***@***.***> wrote:﻿
Yes that’s right, but now the issue is that the bike doesn’t talk. Seem an

issue on the bike. Did it work with any other apps?



Il giorno ven 1 dic 2023 alle 18:53 Bbaeznutrition ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Did you try also with another phone?

Il giorno ven 1 dic 2023 alle 18:59 Bbaeznutrition ***@***.***>
ha scritto:

**Comment by Bbaeznutrition** [comment]
No I did not- I don’t have any others to test with and in fact- the “tablet” stand on the c7 is so crumby my current phone fell off this morning while trouble shooting and cracked my screen 😫Sent from my iPhoneOn Dec 1, 2023, at 10:02 AM, Roberto Viola ***@***.***> wrote:﻿
Did you try also with another phone?



Il giorno ven 1 dic 2023 alle 18:59 Bbaeznutrition ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
great! I like people that don't give up!

Il giorno ven 1 dic 2023 alle 20:44 Bbaeznutrition ***@***.***>
ha scritto:

**Comment by Bbaeznutrition** [comment]
Yay! It was the bike, I watched some tutorials and replaced the display console and it’s perfect and all linked up. Thanks so much for helping me resolve this. Sent from my iPhoneOn Dec 1, 2023, at 11:59 AM, Roberto Viola ***@***.***> wrote:﻿
great! I like people that don't give up!



Il giorno ven 1 dic 2023 alle 20:44 Bbaeznutrition ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Amazing!
