### ISSUE TITLE
[BUG] concept 2 rower metric missing

### ISSUE THREAD

**Issue by kmtowell** [cagnulein/qdomyos-zwift#1856]
**Describe the bug**
PM 5 is located and connected but not all metrics are shown. Strokes per min, elapse time etc are missing.
![inbound4572874868891039889](https://github.com/cagnulein/qdomyos-zwift/assets/97712237/611c05dc-aac1-4f5a-954d-85820175406d)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Compress it first

Il giorno dom 3 dic 2023 alle 19:31 kmtowell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@kmtowell Found the issue: is your pm5 a classic one? Usually the pm5 rower has the row suffix in the name, this one's doesn't. I can easily fix it, I just want to be sure to address correctly this one.
Let me know

**Comment by kmtowell** [comment]
I'm unsure if it's classic.or not, it was bought new in 2018. I'll attach some pics if that helps
![17016292095876704870977283713830](https://github.com/cagnulein/qdomyos-zwift/assets/97712237/1bf7d3ae-49ef-4906-a0e8-47a26c038bd9)
![17016292375152217981362730958152](https://github.com/cagnulein/qdomyos-zwift/assets/97712237/52b97c5e-a6fc-4d66-b4f0-a0e9035cbfd4)

**Comment by cagnulein** [comment]
Seems so, maybe it had a different firmware version.
Anyway I already created a patch for this.
It's building now and it will ready in 30 minutes

If you want you can try it uninstalling the current qz version and installing the new one that I will send you or I can upload the new version on the play store but you have to wait more or less a week since Google is very slow now to review new versions

Let me know

**Comment by kmtowell** [comment]
Sure if you want to send it I will switch it out and try it again and let you know.

**Comment by cagnulein** [comment]
@kmtowell any news? can you share a debug log from the last QZ?

**Comment by kmtowell** [comment]
Sorry I was sick and didn't get a chance to do a debug. My trial has
expired

**Comment by cagnulein** [comment]
@kmtowell the trial doesn't expire, just run it again :) it's a 15 minutes trial forever. send me an email and i will unlock it

i hope you are fine now

**Comment by kmtowell** [comment]
[inbound3038061729763967741.zip](https://github.com/cagnulein/qdomyos-zwift/files/13572894/inbound3038061729763967741.zip)

**Comment by cagnulein** [comment]
got the issue, i will try to fix in the next days

Il giorno mar 5 dic 2023 alle 22:08 kmtowell ***@***.***> ha
scritto:

**Comment by kmtowell** [comment]
Today it would not connect to my bike at all.

**Comment by cagnulein** [comment]
. remember to set your bike at the manual device otherwise it will connect
to the rower

also send me an email to unlock this otherwise it will quit after 15
minutes, otherwise install the play store version again

Il giorno mar 5 dic 2023 alle 22:14 kmtowell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@kmtowell checking your first log, i saw this "Device inactive. Zeroing speed, cadence, and watts." that's why all the tiles are 0. Maybe you have to start something on the rower console? Of course you have to remove the current version of qz, and installing it back the one from the store to try this.
Let me know!

**Comment by cagnulein** [comment]
@kmtowell ok i created a new one for you https://github.com/cagnulein/qdomyos-zwift/suites/18833143287/artifacts/1098503384
Let me know!

**Comment by kmtowell** [comment]
[debug-Sun_Dec_10_15_23_08_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13629102/debug-Sun_Dec_10_15_23_08_2023.zip)

**Comment by cagnulein** [comment]
@kmtowell any better? I see the wattage now!

**Comment by kmtowell** [comment]
No stroke rate

**Comment by cagnulein** [comment]
ok thanks i will check tomorrow

Il giorno dom 10 dic 2023 alle 21:35 kmtowell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
fixed! https://github.com/cagnulein/qdomyos-zwift/suites/18926821373/artifacts/1105625613

**Comment by kmtowell** [comment]
It works!!!! Thank you so much! I jist need to figure out how to get out of
trial mode.

**Comment by kmtowell** [comment]
I did that but it still cut off at 15min

**Comment by cagnulein** [comment]
I added
Kristytowell at gmail.com

Check the uppercase too . The last time you entered the upper case that’s
why I used the uppercase

Il giorno lun 11 dic 2023 alle 18:39 kmtowell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
did you fix the trial thing @kmtowell  ?

**Comment by kmtowell** [comment]
Yes, I did.

**Comment by cagnulein** [comment]
great! i will upload it as well on the play store .
let me know if you have any other issue / questions
