### ISSUE TITLE
Proform Smart Power 10.0

### ISSUE THREAD

**Issue by toddanash** [cagnulein/qdomyos-zwift#1866]
[debug-Tue_Dec_5_17_25_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13573628/debug-Tue_Dec_5_17_25_44_2023.log)
**Describe the bug**

I am still not able to get my Proform Smart Power 10.0 to communicate with QZ app on my iPhone. I was successful in downloading the companion app and have tried using both C1750 and Other in the companion. The QZ app always says “connecting” when have WiFi selected in advanced. The bike says it is connected to QZ in Bluetooth accessories. 

Have spent hours trying to get this to work. Hope you can figure out what is wrong. 

Thanks

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
log checked, ifit locked your tablet, you have to use this method to get the metrics

let me know 

https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by toddanash** [comment]
Sorry but I don’t understand what to do. 


Sent from Yahoo Mail for iPhone


On Tuesday, December 5, 2023, 5:42 PM, Roberto Viola ***@***.***> wrote:




log checked, ifit locked your tablet, you have to use this method to get the metrics

let me know

#1591 (comment)

**Comment by cagnulein** [comment]
which part of the instructions?

**Comment by cagnulein** [comment]
first of all you need to run/install adb on a pc or a mac. do you have one?

Il giorno mer 6 dic 2023 alle 00:27 toddanash ***@***.***> ha
scritto:

> I asume you want me to follow these?
>
> so actually the instructions are:
>
> install the companion
> set the grand tour pro device in the companion
> grant the permission with adb shell pm grant
> org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
> from a mac or a pc
> enable adb debug for qz companion
> restart the companion
> I assume grand pro tour instead of C1750 or other as I had mentioned.
>
> No idea what to do with that 3rd bullet since there is no link and cutting
> and pasting that doesn’t work.
>
> 4th bullet no idea how to do that either.
>
> Thanks
>
>

**Comment by toddanash** [comment]
I do have a MacBook in addition to an iPhone (QZ installed) and a Fire Tablet (Zwift installed). 
Unfortunately I am not a developer and have no idea what adb is 🤷🏻
Thanks


Sent from Yahoo Mail for iPhone


On Wednesday, December 6, 2023, 12:40 AM, Roberto Viola ***@***.***> wrote:



first of all you need to run/install adb on a pc or a mac. do you have one?

Il giorno mer 6 dic 2023 alle 00:27 toddanash ***@***.***> ha
scritto:

> I asume you want me to follow these?
>
> so actually the instructions are:
>
> install the companion
> set the grand tour pro device in the companion
> grant the permission with adb shell pm grant
> org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
> from a mac or a pc
> enable adb debug for qz companion
> restart the companion
> I assume grand pro tour instead of C1750 or other as I had mentioned.
>
> No idea what to do with that 3rd bullet since there is no link and cutting
> and pasting that doesn’t work.
>
> 4th bullet no idea how to do that either.
>
> Thanks
>
>

**Comment by cagnulein** [comment]
no problem, I will help you. Download and install adb from here https://dl.google.com/android/repository/platform-tools-latest-darwin.zip

extract in on a folder

then on that folder, in the finder click on open in a terminal. you will see a terminal window then

then type 

adb connect IPOFYOURBIKE

let me know if you can reach this point

**Comment by toddanash** [comment]
Got this message:

￼

**Comment by cagnulein** [comment]
I don't see anything, you have to upload the picture on the github web interface directly

**Comment by toddanash** [comment]
![IMG_8867](https://github.com/cagnulein/qdomyos-zwift/assets/153030863/dac01350-8cb3-43b3-8b62-796b3b7f7eaa)

**Comment by cagnulein** [comment]
yes go into the security settings to allow it
