### ISSUE TITLE
[BUG] Sole F80 Auto Speed Is Not Adjusting with Peloton App

### ISSUE THREAD

**Issue by bakerk7** [cagnulein/qdomyos-zwift#1867]
**Describe the bug**
Am using my sole F80 2023 model with the peloton app to control the incline and speed during a workout. The incline works fine, but the auto speed is not working at all. The QZ app is picking up what the target speed is from the peloton class but the speed is not adjusting on the treadmill. 

**To Reproduce**
1. Start Treadmill
2. Open QZ app
3. Wait for QZ to detect treadmill and populate tiles
4. Open Peloton App
5. Start workout class
6. Select YES on QZ notification
7. Target speed and target include populate on QZ app
8. Auto Incline works but speed does not adjust

**Expected behavior**
Auto incline and auto speed should adjust based on the peloton class. 

**Screenshots**

**Tablet (please complete the following information):**
 - Galaxy Tab 8 running peleton app

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 17.1.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by bakerk7** [comment]
[Uploading debug-Tue_Dec_5_22_35_42_2023.log…]()

**Comment by cagnulein** [comment]
hi @bakerk7 the debug log is corrupted, you need to wait the finish of the upload before clicking comment. also are you sure that without peloton, are you able to change speed and incline from the speed/incline tiles of qz?
Let me know

**Comment by bakerk7** [comment]
[debug-Tue_Dec_5_22_40_56_2023.log](https://github@cagnulein com/cagnulein/qdomyos-zwift/files/13588249/debug-Tue_Dec_5_22_40_56_2023.log)

@cagnulein - sorry about that. see the debug log from last night.

To answer your question, no I not able to change speed or include from the speed/include tiles of QZ using the +/- buttons.

**Comment by cagnulein** [comment]
ok i also answered you on facebook, check it

Il giorno mer 6 dic 2023 alle 16:55 Kyle Baker ***@***.***>
ha scritto:

**Comment by bakerk7** [comment]
[debug-Tue_Dec_5_22_40_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13588262/debug-Tue_Dec_5_22_40_56_2023.log)

@cagnulein  - sorry about that. see the debug log from last night.

To answer your question, no I not able to change speed or include from the speed/include tiles of QZ using the +/- buttons.
