### ISSUE TITLE
Unknown Pins Motor PCB Board

### ISSUE THREAD

**Issue by melidron** [cagnulein/qdomyos-zwift#1871]
Hello and sorry for the issue I open...
I have a damaged TREADMILL control board but the Motor Control board works fine... I want to connect it with an Arduino or other famous Board but Ican  not find  the schematics of the Motor Control Board... 
The Model Number of it it is SW03-CA-REV1.0
it has 4 pinouts that connect with the control board [4 is White cable, 3 is Green cable,2 is Red Cable and 1 is Black]
I have no idea what its pin do I only believe Black is GND and red is V+ but when I short Black (1) with Green (3) I hear the relay clicks and board's red funcion Led turns ON
But I have no idea how to make the the motor to start spinning and what other pins to connect and where
I upload a sketch of the PCB that maybe help u give me a solution
Thanks and sorry again if  that post it doesnt fit here...

![treadmil motor pcb](https://github.com/cagnulein/qdomyos-zwift/assets/25795126/cf62fb14-ff7d-4d9d-a56d-dc260642d7ff)

**Comment by cagnulein** [comment]
sorry but i don't know. did you try ask on reddit?

Il giorno sab 9 dic 2023 alle 21:16 melidron ***@***.***> ha
scritto:

**Comment by melidron** [comment]
no first try ask here cause I ve seen u know a lot about treadmills and connections and code...
Thanks u a lot my friend

**Comment by cagnulein** [comment]
eheheh yes but not electrical speaking, just software :)

Il giorno sab 9 dic 2023 alle 21:29 melidron ***@***.***> ha
scritto:

**Comment by melidron** [comment]
Oh I see... Thanks anyway my friend...If I learn the pinouts can u help me code an arduino Uno R4 board to work as a control board?

**Comment by cagnulein** [comment]
i already developed the code for the raspberry version here on a branch,
there is also a ticket about this

Il giorno sab 9 dic 2023 alle 21:47 melidron ***@***.***> ha
scritto:

**Comment by melidron** [comment]
can Arduino read raspberry version?

**Comment by cagnulein** [comment]
check this https://github.com/cagnulein/qdomyos-zwift/issues/525

**Comment by cagnulein** [comment]
nope it can't

Il giorno sab 9 dic 2023 alle 22:03 melidron ***@***.***> ha
scritto:

**Comment by melidron** [comment]
I see thank U
