### ISSUE TITLE
[BUG] Advance metrics Stryd and correct Wattage

### ISSUE THREAD

**Issue by Barnello83** [cagnulein/qdomyos-zwift#1873]
**Describe the bug**
Can’t see and record advance metrics from Stryd (only length stride)and can’t see correct wattage from stryd using Wattage offset

**To Reproduce**
Recording normal activity

-First screenshot the real wattage from stryd during a walking activity (Garmin screen)
-Second screenshot the wattage in the app after a few seconds (only the time to make a second screenshot)
![IMG_5326](https://github.com/cagnulein/qdomyos-zwift/assets/148382584/2f390fb9-3af3-442d-8aa9-af03245e7bfb)
![IMG_5325](https://github.com/cagnulein/qdomyos-zwift/assets/148382584/df067b19-71c0-4259-842a-e1fa6da93663)
[Debug qdomyoszwift .zip](https://github.com/cagnulein/qdomyos-zwift/files/13633587/Debug.qdomyoszwift.zip)

**Expected behavior**

Record all advance metrics from Stryd and see correct wattage offset

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR]
 - OS: [e.g. iOS 17.1.2]
 - Version [2.16.20]

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by Barnello83** [comment]
> @Barnello83 i fixed the wattage thing, thanks. For the other metrics I guess stryd in this case it sends in a custom way. In the stryd app on ios, can you see these value in realtime?

In the aftertoon I’ll try both things!!

thank you @cagnulein

**Comment by cagnulein** [comment]
you can't try the fix, i didn't build it yet. I was waiting your confirmation about the stryd metrics :)
In the log I saw some raw values from the stryd but I have to "give them a name". it would be nice recording a video of your watch reading the stryd by ant+ and showing all the metrics while you're recording a session with qz. so i can compare video and log and give a name correctly.

Let me know!

**Comment by cagnulein** [comment]
perfect! i implemented the GroundContactMS that in your video is 980ms. but i need to see also in the video the VerticalOscillationMM with a value different than 0. could you do the same with this?
thanks

**Comment by Barnello83** [comment]
> perfect! i implemented the GroundContactMS that in your video is 980ms. but i need to see also in the video the VerticalOscillationMM with a value different than 0. could you do the same with this? thanks

I have opened a ticket to stryd because the fields shows only 0!!

Thanks

**Comment by cagnulein** [comment]
lol ok 😄 
In the meantime I will send you this new version.
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you it

**Comment by cagnulein** [comment]
@Barnello83 are we ok with this?

**Comment by Barnello83** [comment]
Hi @cagnulein unfortunately I’m not able to test the latest version with the increasing watt with the inclination due to a lack of time to test.

I’la test as soon as possible, for the moment you can close the ticket as resolved.

Thank you very much

Federico

**Comment by cagnulein** [comment]
ok thanks!
