### ISSUE TITLE
[BUG] Echelon Row Sport Freezes

### ISSUE THREAD

**Issue by scottmoserhenderson** [cagnulein/qdomyos-zwift#1875]
**Describe the bug**
The Echelon Row Sport connects but the pace seems a bit weird. It doesn't seem to correspond to how I'm actually rowing. I have seen it bounce all over the place. This debug log is more realistic to my effort BUT I still don't think it's correct. I think I need to row more with it and get a better feel of it before coming to a conclusion on that. However, there is an immediate issue that I'm facing with the Peloton row classes. If you pause rowing during a class, the Peloton class timer on Qz stops but the class on the tablet continues to run which quickly becomes out of sync and it's nearly impossible to sync up because you have to be rowing while you're adjusting the offset. 

**Expected behavior**
The Peloton class remaining timer should continue to run even when not rowing. There are moments in classes where you pause for a quick rest for water/etc. 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 Pro
 - OS: [e.g. iOS8.1] 17.2
 - Version [e.g. 22] 2.15

**Append a debug log**
[debug-Mon_Dec_11_10_59_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13638758/debug-Mon_Dec_11_10_59_21_2023.log)

**Additional context**
Debug log shows me starting a Peloton class and rowing with random pauses.

**Comment by cagnulein** [comment]
Hahah the echelon guys are funny, they probably saw that the pace wasn’t so
good and they removed from the UI :)

Ok for now you can see use the avg speed In the speed tile.

An average of 3 seconds should be ok right?

Il giorno lun 11 dic 2023 alle 20:36 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
The average speed Is already available In the speed tile. The average that
I talked about it’s just an idea, I didn’t do yet :) I’m fast but not so
fast :)

Il giorno lun 11 dic 2023 alle 20:43 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
The commit was about the speed glitch on the startup

Il giorno lun 11 dic 2023 alle 20:46 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
version ready @scottmoserhenderson 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@scottmoserhenderson are we ok with this?

**Comment by cagnulein** [comment]
so sorry to hear this @scottmoserhenderson i hope you are ok now! i can't see the debug log, you have to wait the upload before commenting it

**Comment by cagnulein** [comment]
ok thank i will check it tomorrow

**Comment by cagnulein** [comment]
I didn't quite get the issue but I tried to add a patch. I will send you another one ASAP. Share the debug log if the problem is the same. Thanks!

**Comment by cagnulein** [comment]
sent a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 18 gen 2024 alle ore 20:24 Scott Henderson <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@scottmoserhenderson are we ok?
