### ISSUE TITLE
Freemotion Coachbike b22.7: Making adjustments on the bike through the app does not work. Manually or Automatically

### ISSUE THREAD

**Issue by giittyy** [cagnulein/qdomyos-zwift#1877]
**Describe the bug**
When I try to adjust the inclination, fan speed, resistance, etc. nothing changes on the app and on the bike tablet screen. And by effect  auto resistance does not work either.

**To Reproduce**
1. Go to resistance 
2. Click on the plus sign
3. Nothing happens

**Expected behavior**
The desired outputs to change on the bike and on the [screen]([debug-Mon_Dec_11_12_48_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13641143/debug-Mon_Dec_11_12_48_16_2023.log))

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.2

**Append a debug log**
[debug-Mon_Dec_11_12_48_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13641167/debug-Mon_Dec_11_12_48_16_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
hi @giittyy any news from adb commands?

**Comment by giittyy** [comment]
![Wed12-13-2023@0-04-16 13](https://github.com/cagnulein/qdomyos-zwift/assets/72840497/c3203cde-55fd-47da-88f2-4e062a78cf23)

My screen for changing incline and resistance.

**Comment by cagnulein** [comment]
ok the UI is very similar to the proform studio one. So in the nordictrack bike settings, enable the adb remote and also the proform studio one setting. Even without zwift, if you change the inclination in the qz tiles you should see an event in the touch. Let me know, send me a debug log here in case it doesn't.

**Comment by cagnulein** [comment]
ok the UI is very similar to the proform studio one. So in the nordictrack bike settings, enable the adb remote and also the proform studio one setting. Even without zwift, if you change the inclination in the qz tiles you should see an event in the touch. Let me know, send me a debug log here in case it doesn't.

**Comment by cagnulein** [comment]
ok the UI is very similar to the proform studio one. So in the nordictrack bike settings, enable the adb remote and also the proform studio one setting. Even without zwift, if you change the inclination in the qz tiles you should see an event in the touch. Let me know, send me a debug log here in case it doesn't.

**Comment by giittyy** [comment]
[debug-Wed_Dec_13_09_20_02_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13663734/debug-Wed_Dec_13_09_20_02_2023.log)
 
 debug log for only inclination working

**Comment by cagnulein** [comment]
let's use the inclination tile and/or the target inclination tile to change
it. in the log that you posted I only saw that the resistance doesn't do
anything as it's expected.
what I would like to see are:
- changing the inclination send the adb command to the bike with the
correct coordinates
- in the same log, try to connect to zwift so I will see why it's not
handling it

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 13 dic 2023 alle ore 18:23 giittyy ***@***.***>
ha scritto:

**Comment by giittyy** [comment]
[debug-Wed_Dec_13_09_52_07_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13663997/debug-Wed_Dec_13_09_52_07_2023.log)
It should have all those logs, better news this time. The auto inclination worked in terms of it moved, but when I went down steep hills 5-7% it only did 1% tops. So not completely accurate, but did work a lot better this time

**Comment by giittyy** [comment]
[debug-Wed_Dec_13_09_43_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13664244/debug-Wed_Dec_13_09_43_38_2023.log)
Yes it should be this one.

**Comment by cagnulein** [comment]
ok got the issue and already fixed why it was changing the inclination and not the resistance. so if you want I can send you this version when the resistance on the bike will affected, but for the moment the inclination will not moving. Are you ok with this or you would like to wait tomorrow when I will try to add both? it will be the first time ever for nordictrack bikes so i don't know it will work.
Let me know!

**Comment by giittyy** [comment]
Awesome! I appreciate your work on this. I can wait until it's ready.

**Comment by giittyy** [comment]
Plan B is great.

**Comment by cagnulein** [comment]
@giittyy done and sent. You have to disable now the proform studio setting and enable the new one that I created for your bike called freemotion coachbike. restart qz then.
what I did is to control both resistance and inclination. What I would like to see it that, when zwift changes the inclination, both sliders should move. Maybe the calibration of the touch area could be improved, but the important thing now, is that both sliders are moving more or less at the same time.
Let me know!

**Comment by cagnulein** [comment]
@giittyy I guess you misunderstood my test: with this build I would like to check if we can change the inclination and the resistance at the same time. If so we can calibrate the resistance of course! Anyway you can disable the auto resistance pressing the magnet icon in the top right corner of qz.
The half thing of zwift it's only about the zwift difficulty in zwift: zwift has a 50% by default, set it to 100% and you will have the full inclination.
Let me know

**Comment by giittyy** [comment]
Yes that worked. The only thing that happened is it got stuck at -2 incline at one point and it was trying to make a button press but was pressing in the wrong area. I'll need to test more to see if it was just a one off issue. I'm realizing it's probably best to just stick with inclination auto for Zwift and resistance auto  for peloton if that's possible.

**Comment by cagnulein** [comment]
You can toggle the proform studio on, and disable the new setting so.
It should work, right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 dic 2023 alle 17:29 giittyy ***@***.***> ha
scritto:

**Comment by giittyy** [comment]
That's true. The only weird thing with the new one is manual presses on the QZ app do not update on the app. In fact they don't even register the clicks. I'll give it some more test runs to make sure, but this is how it was behaving.

**Comment by cagnulein** [comment]
Are you talking about the resistance? With the proform studio setting will behave at the same of the previous one

**Comment by giittyy** [comment]
Trying match peloton resistance to bike 
[debug-Sun_Dec_24_14_36_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13791417/debug-Sun_Dec_24_14_36_44_2023.log)

**Comment by cagnulein** [comment]
ok i'm building the version for you. remember to disable the proform one
setting and enable back the freemotion one when you will get it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 dic 2023 alle ore 07:38 giittyy ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@giittyy are we ok with this?

**Comment by giittyy** [comment]
It's off but I don't know how to fix it. Still trying to gather data to get a better result.

**Comment by cagnulein** [comment]
ok let me know if i can help you!

**Comment by cagnulein** [comment]
@giittyy any news?
