### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by bakerk7** [cagnulein/qdomyos-zwift#1879]
**Is your feature request related to a problem? Please describe.**
This request assumes Sole F80 can automatically adjust speed via QZ.  

I get frustrated when the Sole F80 (2023 model) takes so long to increase and decrease speed. It becomes hard to keep pace with the class when there is such a delay by the treadmill. 

**Describe the solution you'd like**
Id like the ability to set an offset in QZ to account for the difference. Starting my increase or decrease of speed about 7 seconds before the instructor says, seem to work. 

**Describe alternatives you've considered**
Whenever the coach says "10 seconds left" i adjust my speed up or down to account for the delay. 

**Additional context**
This assumes Sole F80 + QZ + Peloton can increase/decrease speed automatically.

**Comment by cagnulein** [comment]
hi Kyle, did you try the fast inclination setting in the sole settings in
qz?
if it works for the inclination i can do the same for speed

let me know

also the offset it's doable but it could be better if we can speed up the
process of changing speed or incline

Il giorno mar 12 dic 2023 alle 04:09 Kyle Baker ***@***.***>
ha scritto:

**Comment by bakerk7** [comment]
Hi @cagnulein - just tried fast inline, i didnt notice a difference honestly

**Comment by cagnulein** [comment]
Did you use with also the inclination experimental one, I mean both enabled?

**Comment by bakerk7** [comment]
> Did you use with also the inclination experimental one, I mean both enabled?

No, are both required?

**Comment by cagnulein** [comment]
yes in order to test the fast auto inclination

**Comment by cagnulein** [comment]
@bakerk7 are we ok with this?

**Comment by bakerk7** [comment]
Yes
