### ISSUE TITLE
Req: Add tile with "Target Resistance" from Zwift

### ISSUE THREAD

**Issue by d-nx** [cagnulein/qdomyos-zwift#188]
It would be AMAZING to have a new tile that shows "Target Resistance" for bikes that don't have controlled resistance.

This way we can Zwift, and manually match our resistance to what the "Target Resistance" shows.

**Comment by cagnulein** [comment]
Interesting idea. I will add it for sure!

Il sab 6 mar 2021, 05:16 d-nx <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
Done! it will be available in version 2.4.9!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 mar 2021 alle ore 07:30 cagnulein <cagnulein@gmail.com> ha
scritto:

**Comment by d-nx** [comment]
Absolutely genius!

I tweaked my Resistance offset and it's working great but I'm not sure what resistance gain does.

Could you explain to me how the resistance gain works? Is it a multiplier or an offset?

Thanx

**Comment by cagnulein** [comment]
It's a multiplier. Usually it should stay to 1 for echelon

Il sab 6 mar 2021, 18:33 d-nx <notifications@github.com> ha scritto:
