### ISSUE TITLE
[REQ] Rebook FR30z

### ISSUE THREAD

**Issue by sor609** [cagnulein/qdomyos-zwift#1880]
**Is your feature request related to a problem? Please describe.**
Treadmill gets recognized by the QZ app however no metrics are flowing in and treadmill speed/incline cannot be adjusted via app.
Phone (iOS) does not show up in Zwift, possibly due to previous issue

**Describe the solution you'd like**
I would like Zwift to control my treadmill's incline/decline and speed in fartlek or intervals workouts

**Describe alternatives you've considered**
I'm manually pushing the incline/decline buttons on the treadmill! :)

**Additional context**
Treadmill is bluetooth enabled via a provided USB dongle. I have been using it with Zwift without issues.
Debug log attached

[debug-Tue_Dec_12_09_25_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13646535/debug-Tue_Dec_12_09_25_38_2023.log)

**Comment by cagnulein** [comment]
hi @sor609 good news! i guess i already handle this in the beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@sor609 are we ok with this?

**Comment by sor609** [comment]
Hi @cagnulein the beta app you supplied worked with my treadmill and it displayed all the metrics (speed/incline) but since I wasn't able to create group runs (as part of the workaround), the automatic incline did not work.
Windows app didn't work for me either. It started fine, recognized the treadmill but didn't receive any data from it (neither speed or incline). It would then freeze shortly afterwards (became unresponsive).
Unfortunately, I'm travelling now and will be moving afterwards so I won't have time to play with this more in the near future. You can keep the issue closed and hopefully I'll get back to this one day.
Thanks for all the help you've provided!

**Comment by cagnulein** [comment]
ok let me know when you will be again and we resume this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 19:49 Sasha ***@***.***> ha
scritto:
