### ISSUE TITLE
[BUG] shaky cadence and power with yesoul s3

### ISSUE THREAD

**Issue by Muellejm** [cagnulein/qdomyos-zwift#1882]
**Describe the bug**
Been using the QZ app for a while and lately the cadence jumps very high randomly

**To Reproduce**
Happens randomly but seems to be more prevalent in higher resistances

**Expected behavior**

**Screenshots**
[debug-Tue_Dec_12_09_57_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13649753/debug-Tue_Dec_12_09_57_37_2023.log)

**Smartphone (please complete the following information):**
 - device: iPhone 14
 - 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
```
Tue Dec 12 09:59:28 2023 1702393168337 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 06 2b 48 00 8e 01 f3 08 f4 00"
Tue Dec 12 09:59:28 2023 1702393168351 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Watt: 499"
```

@Muellejm checked, unfortunately it's the bike itself that is sending wrong values. It seems the cadence sensor is faulty. I suggest to buy a cadence sensor or better a power pedal if you are still happy with the bike. Let me know

**Comment by Muellejm** [comment]
Thanks so much for looking into it

**Comment by Muellejm** [comment]
Hey! 

I just wanted to follow up to say I got a new battery for the Bluetooth sensor and restarted the  sensor and we’re back running smooth!

thank you so much for this app!

**Comment by cagnulein** [comment]
glad to hear this!
