### ISSUE TITLE
[BUG] qz not detecting HR from garmin forerunner 265 w companion app

### ISSUE THREAD

**Issue by Kekobe2023** [cagnulein/qdomyos-zwift#1883]
I can’t seem to get my heart rate from my garmin forerunner 265 to come up on QZ on my iPhone. Qz companion app installed, heart belt name disabled, enable companion app for garmin enabled, heart rate outside ftms disabled. What am I missing here?

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 17.1.2
 ]l
![IMG_3887](https://github.com/cagnulein/qdomyos-zwift/assets/131414335/337cdb90-629a-4936-972f-c3ab4f3a471d)
![IMG_3888](https://github.com/cagnulein/qdomyos-zwift/assets/131414335/ad8ff999-f529-44b8-b9b9-13c850b79502)
[debug-Tue_Dec_12_10_44_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13651663/debug-Tue_Dec_12_10_44_19_2023.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi, I'm actually riding now, I will check it asap

Il mar 12 dic 2023, 18:59 Kekobe2023 ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@Kekobe2023 it seems all right. Do you have already try to reboot both devices? garmin connect is well connected to the watch?

**Comment by Kekobe2023** [comment]
I’ll try restarting my watch and cell phone tonight. I had closed the apps and relaunched last time. Let you know what happensSent from my iPhoneOn Dec 12, 2023, at 12:52 PM, Roberto Viola ***@***.***> wrote:﻿
@Kekobe2023 it seems all right. Do you have already try to reboot both devices? garmin connect is well connected to the watch?

**Comment by Kekobe2023** [comment]
Unfortunately I rebooted both the phone and watch and tried again, still didn’t work. Is there anything else I should try? Thanks!On Dec 12, 2023, at 12:52 PM, Roberto Viola ***@***.***> wrote:﻿
@Kekobe2023 it seems all right. Do you have already try to reboot both devices? garmin connect is well connected to the watch?

**Comment by cagnulein** [comment]
i'm adding some new debug log for your case @Kekobe2023 , 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta. Thanks!
