### ISSUE TITLE
I like to know if Horizon Andes 7i crosstrainer works with this app?

### ISSUE THREAD

**Issue by TribunMaximus** [cagnulein/qdomyos-zwift#1885]
Hi,

I'm interessted in this app and like to know if Horizon Andes 7i crosstrainer is supported by this app.
Thanks for help.

Br
Jens

**Comment by cagnulein** [comment]
hi @TribunMaximus in order to be sure about this, send me a nrfconnect screenshot about your crosstrainer. nrfconnect is a free app on the store. Let me know

**Comment by TribunMaximus** [comment]
Hi Roberto, thanks for fast reply.
I just checked, but didn’t get a signal. So I think, Horizon Andes 7i comes without a blutooth signal. ☹

Br
Jens

Von: Roberto Viola ***@***.***>
Gesendet: Mittwoch, 13. Dezember 2023 07:59
An: cagnulein/qdomyos-zwift ***@***.***>
Cc: Greeb, Jens ***@***.***>; Mention ***@***.***>
Betreff: Re: [cagnulein/qdomyos-zwift] I like to know if Horizon Andes 7i crosstrainer works with this app? (Issue #1885)


hi @TribunMaximus<https://github.com/TribunMaximus> in order to be sure about this, send me a nrfconnect screenshot about your crosstrainer. nrfconnect is a free app on the store. Let me know

**Comment by cagnulein** [comment]
does it have an android tablet?

**Comment by TribunMaximus** [comment]
No,

Just WLAN to Export trainingsdata to viewfit.com and Support of their one Solution: https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwj-iaPZ-IuDAxWMkYMHHSRUDW0YABAJGgJlZg&ohost=www.google.com&cid=CAESVOD2f4QMDK4WtrtpniXjqkKvLGhF6lxeUk_ch_xU4bDKMqWxwyu88q701_tX0b2V1rmH0u7L8w3bxsFYxeH8KcjUZgOsR5RLnKyUCMACixImzN_jIw&sig=AOD64_19DOKgdIgnJLPE97FDkMSlEAJ0rQ&ctype=5&q=&ved=2ahUKEwj5v5vZ-IuDAxWbgP0HHbm2DOkQwg8oAHoECAIQEQ&adurl=

Am 13.12.2023 um 08:23 schrieb Roberto Viola ***@***.***>:

﻿

does it have an android tablet?

**Comment by cagnulein** [comment]
no i guess it's not compatible so :( maybe we can intercept somehow this data. do you see data in realtime on viewfit.com ?

**Comment by TribunMaximus** [comment]
Hi,

not in viewfit.com. Only on the screen of the crosstrainer. ☹


Von: Roberto Viola ***@***.***>
Gesendet: Mittwoch, 13. Dezember 2023 09:13
An: cagnulein/qdomyos-zwift ***@***.***>
Cc: Greeb, Jens ***@***.***>; Mention ***@***.***>
Betreff: Re: [cagnulein/qdomyos-zwift] I like to know if Horizon Andes 7i crosstrainer works with this app? (Issue #1885)


no i guess it's not compatible so :( maybe we can intercept somehow this data. do you see data in realtime on viewfit.com ?

**Comment by cagnulein** [comment]
ok so does it have other way to communicate? maybe it has other port?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 13 dic 2023 alle ore 09:13 TribunMaximus <
***@***.***> ha scritto:
