### ISSUE TITLE
QZ app not connecting to Echelon Stride Treadmill[BUG]

### ISSUE THREAD

**Issue by msheldo1** [cagnulein/qdomyos-zwift#1886]
**Describe the bug**
The QZ app is not connecting to my Echelon Stride Treadmill on startup.  I don't get the tiles on the main screen and the name of my treadmill only briefly flashes at the top of the screen as the QZ app cycles through looking for devices.

**To Reproduce**
Turn on treadmill
Open QZ app

**Expected behavior**
QZ app connects to treadmill

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS
 - Version 17.1.2
[debug-Wed_Dec_13_14_19_59_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13664498/debug-Wed_Dec_13_14_19_59_2023.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
The treadmill is brand new, delivered 5 days ago, and works fine in all other aspects.  I have not tried it with the Echelon Fit app as I don't want to pay for their services and you must sign up for a monthly plan to even create a profile with Echelon.  The QZ app connected briefly with the treadmill, but when I turned off the "virtual device" as directed, it no longer could find the treadmill.

**Comment by cagnulein** [comment]
@msheldo1 the issue is that you have the manual device setting in the advanced setting set to your ipad. set it to your echelon stride (ECH-UK) and it will be fine. press ok and restart qz
let me know!

**Comment by msheldo1** [comment]
Ok, so that worked to get the QZ app connected to the treadmill and it was showing my pace in the QZ app.  Thank you. 
 However, my iPad (Zwift app) is not seeing my iPhone to send the speed/cadence data to Zwift.  I have bluetooth turned on with no restrictions (that I'm aware of) on both devices.  They are on the same wifi network, in the same room and neither are connected to any other devices (except the iPhone connected to the treadmill).  Is there a setting I've missed to make help the QZ app connect to the iPad?

Thanks for your really fast responses, but don't worry if you can't get to this until tomorrow.

**Comment by cagnulein** [comment]
yes virtual device must be on. if you encounter any issues with this enabled, disable ONLY the virtual device BLUETOOTH, not the entire virtual device switch.
let me know how it goes :)
no problem, 8pm here in italy and I'm watching one of my favourite movies, Interstellar :)

**Comment by msheldo1** [comment]
Ahh, good movie.  Ya, I'm in the UK, so getting ready to settle into some TV for the evening.  Slow Horses on Apple TV is my current favorite.  

So, turning on the Virtual Device allowed the ipad to see the iphone, but then the speed/cadence data was not displaying on the QZ app (iphone) when I got the treadmill going.  I turned off just the Virtual Device Bluetooth as you said, but then the iPad couldn't find the iPhone again.  It's like each time I flip a switch, it breaks the connection on one of the devices.

**Comment by cagnulein** [comment]
on zwift you see only the iphone? not the wahoo kickr virtual device from qz? what about zwift on apple tv? neither there can see it? 
leave the virtual device bluetooth disabled. it's the right setting

**Comment by msheldo1** [comment]
On Zwift I only saw the iphone when both the virtual device and virtual device bluetooth were turned on.  When I turned off the virtual device bluetooth (virtual device still on) I could no longer find the iphone in Zwift.  

I haven't seen the wahoo kickr device since the first time I tried to set up the app/zwift.  I thought it might be a neighbors devices, so I have just ignored them.  Should I be connecting to those?

**Comment by cagnulein** [comment]
yes you have to use the wahoo tread or the wahoo kickr.
the issue you're encountering it's a classic zwift/ios bug.
That's why I suggest to try with your apple tv. Install zwift there and give it a shot
Let me know

**Comment by msheldo1** [comment]
Unfortunately, the apple TV is downstairs and the treadmill is upstairs, so I can't use the apple tv.  

Hmm, I would try using the Wahoo Tread, but it no longer shows up on my iPad when searching for Bluetooth devices for speed/cadence.  Would it make sense for me to reset the QZ app to factory defaults and start again just in case?

**Comment by cagnulein** [comment]
wahoo signal is wifi, so you can test it around the house, even on your apple tv ;)
no it's not qz the issue, it's the wifi cache. you can install the https://apps.apple.com/de/app/discovery-dns-sd-browser/id305441017 on your ipad and in the bottom you should see a wahoo one. if you see it, qz is doing it great, it's just zwift now the issue ;)

**Comment by msheldo1** [comment]
I downloaded Discovery DNS on my iPad, and it found wahoo-fitness-tnp_tcp..  However, Zwift does not see the wahoo one when I search for speed/cadence sensors.  Zwift does see my iphone (QZ app), but when I connect, it doesn't receive the speed/cadence data from QZ and the tiles are showing movement from the treadmill.  Is there anything else I can try?  Otherwise, I may have to forego the app and try a Runn sensor on the treadmill.  I get the sense from reading a few blogs that a lot of people struggle with the Echelon Stride treadmill on the QZ app.  I wonder if Echelon has just done some things to their software to lock out anyone making a bridge app like QZ and forcing everyone onto their app?

**Comment by cagnulein** [comment]
no, echelon stride is fine and qz is also fine since you are getting the
wahoo service on the ipad. the problem is zwift now. try to do a network
reset on the ipad and reboot it
also try the reserve
and also try the apple tv as i suggested
i'm currently on my treadmill right now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 dic 2023 alle 12:16 msheldo1 ***@***.***> ha
scritto:

**Comment by msheldo1** [comment]
Thanks Roberto,

Unfortunately, I can't use the apple tv as it is downstairs and is our main tv entertainment box, so I can't move it upstairs just for myself.  What do you mean by "try the reserve"?

I did a reboot of the ipad and checked that it is on the same channel of my router as the iphone, but no luck.  

Have a good run!

**Comment by cagnulein** [comment]
the test with the apple tv is only to check if it works. i don't want to set it as your main zwift device, but in this way we can understand, if, as I'm guessing, the problem is zwift on the ipad.

For the reverse I was meaning to test zwift on iphone and QZ on the ipad with the same iphone settings of course.

Did you do a network reset as I suggested and then reboot your ipad?

Try all of these and then we will have a much clear idea about the issue that we are facing of.
Anyway, just to give you a statistics, more than 100 users are using echelon stride with QZ, so it's for sure not an issue on qz or the echelon stride. It's just some issue about connectivity on the ipad on zwift that we have to figure out. If you check on the zwift forum, there a lot of users with similar issue, it's just zwift that is coded by a monkey :)

**Comment by msheldo1** [comment]
Hi Roberto,

Thank you for the additional clarity on your previous comments.  I didn't reset the router, just the ipad and iphone.  I tried the reverse where I ran QZ on the ipad and zwift on the iphone.  That had the same results where the iphone couldn't see the ipad for speed/cadence sensor.  However, the iphone did see the Wahoo tread and kickr... so I tried connecting to the Tread, but nothing happened.  Then I connected to the Wahoo kickr and it works.  Now I've got to figure out how to get it to work with the devices reversed so I'm not staring at a tiny phone screen.  I think that tells us it is something with Zwift on iPad.  I've checked and I'm on the latest Zwift version for iPad.  I haven't upgraded the iPad OS to 17.2... I'm still on 17.1.2, but I can't imagine that is the problem.

**Comment by msheldo1** [comment]
Ok, created a hotspot with my phone and that worked for a second until my reception dropped out (bad phone reception here) and the ipad went back to Wifi.  So, that feels like we have narrowed it to the iPad, Zwift and possibly my router.  The router is on factory settings from the ISP (BT/EE).  I'll try resetting it to see if that helps, but would there be any settings on the router I should check to ensure it's setup to work for this?

**Comment by msheldo1** [comment]
Also, I'm updating both the iphone and iPad to iOS 17.2 to help with the cache issue.

**Comment by cagnulein** [comment]
ok that's a good news. Can you try to disable the wifi 5ghz on your router and use only the 2.4ghz? also you have to check if the router has some kind of firewall or something, in case, disable it, at least to check if it's the issue

**Comment by cagnulein** [comment]
@msheldo1 any news?
