### ISSUE TITLE
[BUG] Companion app Nordictrack 2450 (2019) not sending speed and incline to QZ

### ISSUE THREAD

**Issue by gitoutofhere8** [cagnulein/qdomyos-zwift#1887]
**Describe the bug**
The QZ tiles always show 0 for speed and either 0, 0.5 or 1 depending on treadmill model that set in companion app.

**To Reproduce**

Followed all detailed instructions to install companion app fromweb browser option.  Rebooted after everytime I tried another treadmill model.

QZ is [configured]([url]([debug-Thu_Dec_14_09_21_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13675322/debug-Thu_Dec_14_09_21_27_2023.log))) per those instructions including IP address of treadmill.

Connected QZ.  I see tiles but values do not update.

**Expected behavior**

I expect that qz tiles would update speed and incline values when adjusted in ifit by pressing physical buttons.

**Screenshots**
Not available

**Desktop (please complete the following information):**
 - OS: n/a
 - Version 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android
 - Version 10

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@gitoutofhere8 please attach a debug log from qz here. thanks

**Comment by gitoutofhere8** [comment]
[debug-Thu_Dec_14_09_21_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13675350/debug-Thu_Dec_14_09_21_27_2023.log)

**Comment by cagnulein** [comment]
ok companion is sending only the grade information, did you already try the C1750, right?
If so you need to follow this guide https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559
Let me know if you have any doubts

**Comment by gitoutofhere8** [comment]
Thank you.  Yes I tried C1750, will try to follow the supplemental guide tonight.

**Comment by gitoutofhere8** [comment]
Read through the cases attached to #1591.

Struggled, but was able to connect with adb only once successfully.  I was able to execute 
"adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS".

Set Treadmill to C1750 in companion app.  Restarted the treadmill and tried again.  Launched iFit then relaunched Qz.  I didn't notice any updates when trying to change incline and speed.  Attached the latest log.

[debug-Thu_Dec_14_21_32_43_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13680289/debug-Thu_Dec_14_21_32_43_2023.log)

**Comment by cagnulein** [comment]
hi @gitoutofhere8 the companion app must be set to grand tour device in order to work. Could you please do it, reboot the treadmill and try again and send me a debug log in any case?
Thanks!

**Comment by cagnulein** [comment]
actually I can't see no more messages now. are you still able to connect to adb? if so we can check another way. Let me know

**Comment by gitoutofhere8** [comment]
unfortunately I keep failing to connect with adb.  Is it worth trying another log?

**Comment by cagnulein** [comment]
if you can't connect to adb it means that ifit is closing it every time. I suggest to do this:
- do a factory reset
- after the reset DON'T update ifit
- in this way it could be that the standard qz companion works
- if not, try again the grand tour trick
- if it doesn't work neither check that the adb is still open

As you may understood the important thing is adb and ifit that must be a factory version (ifit is closing down every doors now that they saw QZ). So we have to fight with them to *unlock* your treadmill.

Let me know

**Comment by gitoutofhere8** [comment]
I have an adb connection now after toggling USB debugging off and on again.  Are we able to proceed with more troubleshooting steps?

I'm reluctant to factory reset as I remember well that the default and early versions of software were unstable and would regulalry crash.

**Comment by cagnulein** [comment]
Great! Let me know!

**Comment by gitoutofhere8** [comment]
@cagnulein unfortunately several aspects of the integration aren't working and I'm going to stop troubleshooting for now.

-QZ was not picking most of the speed and incline changes.  Working maybe 10% of the time.

-After reboot no values changing.  I'm afraid that toggling usb debugging and pushing adb permission would likely be required on every reboot.

-Was able to connect QZ to Peloton FTMS running on tread however no values displayed on Peloton.  This is the main thing I was trying to get working .  This did work when Peloton was running on ios, but is not my desired device.

-I expect you're right, I'd probably get better results with a factory reset.  Thank you for your time, appreciate it!

**Comment by cagnulein** [comment]
> unfortunately several aspects of the integration aren't working and I'm going to stop troubleshooting for now.

consider QZ like a never ending working field, so I'm always happy to check the users issues, so if you want we can continue



> -QZ was not picking most of the speed and incline changes. Working maybe 10% of the time.

with a debug log and some of your time we can get this



> -After reboot no values changing. I'm afraid that toggling usb debugging and pushing adb permission would likely be required on every reboot.

yes, that's why i was talking about factory reset.
Also I already started a way to don't use ifit anymore but I need person like to you to test the usb access. Let me know if you are interested





> -Was able to connect QZ to Peloton FTMS running on tread however no values displayed on Peloton. This is the main thing I was trying to get working . This did work when Peloton was running on ios, but is not my desired device.

you mean qz on android? you have only probably to rename your qz device to "bike" (only 4 letters) and reboot it.

**Comment by gitoutofhere8** [comment]
Hi @cagnulein , wanted to give you a final update.  It's working great after resetting the treadmill to factory defaults and using 1750 in the companion app. Just a brief test, haven't tried it for a full class yet.  Thank you!!!!!!!!

The issue I mentioned about Peloton also seems to be encountered by other users on Pelobuddy and has nothing to do with QZ.  While Peloton now accepts speed and incline from FTMS, you can only see it when Peloton is in portrait mode or after the class.  It does not display in landscape mode which appears to be a Peloton bug.

**Comment by cagnulein** [comment]
glad to hear this @gitoutofhere8 !
Let me know if you have any other questions!
