### ISSUE TITLE
[BUG] debug log for not showing HR from garmin companion 

### ISSUE THREAD

**Issue by Kekobe2023** [cagnulein/qdomyos-zwift#1888]
This is with the new beta you sent me. I didn’t do an actual ride but started QZ companion, then started zwift on iPad. And finally QZ on iPhone. 
[debug-Thu_Dec_14_22_16_03_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13681326/debug-Thu_Dec_14_22_16_03_2023.log)

**Comment by cagnulein** [comment]
#1883

**Comment by Kekobe2023** [comment]
[debug-Fri_Dec_15_10_36_53_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13688269/debug-Fri_Dec_15_10_36_53_2023.log)

New debug log with qdomyos started first and we companion on garmin after and start button with elapsed time showing

**Comment by cagnulein** [comment]
ok thanks, i have to think why it's not receiving anything. maybe it's some
incompatibility with the watch model. i will think about and maybe i will
add some debug messages also on the watch itself

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 dic 2023 alle 18:47 Kekobe2023 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Kekobe2023 just to be sure I did a test on the same iOS version that I sent with your garmin and it works perfectly unfortunately here.
So it must be something on your setup, I'm wondering if it's not a limitation of the watch itself but I don't think so.
Unfortunately the garmin simulator doesn't handle the bluetooth communication so I can't test your watch on my debug scenario. Do you have any other garmin apps that you can try to check if your watch can send custom data to custom app on your phone?

**Comment by cagnulein** [comment]
@Kekobe2023 Amy news?

**Comment by Kekobe2023** [comment]
I never got it to work with garmin companion but I found a workaround. I use bike indoor activity and set it to broadcast heart rate during activity and my iPad can get the HR directly from that so I just do it that way now. Thanks for trying!Sent from my iPhoneOn Jan 7, 2024, at 12:22 AM, Roberto Viola ***@***.***> wrote:﻿
@Kekobe2023 Amy news?

**Comment by cagnulein** [comment]
ok great! anyway it's working for the rest of the users so maybe there is
something on your setup, anyway great that you have a workaround!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 16:32 Kekobe2023 ***@***.***>
ha scritto:
