### ISSUE TITLE
Unable to connect qz to exp7i norditrack treadmill

### ISSUE THREAD

**Issue by rainvd** [cagnulein/qdomyos-zwift#1890]
[inbound1524855971018718334.txt](https://github.com/cagnulein/qdomyos-zwift/files/13690767/inbound1524855971018718334.txt)
**Describe the bug**
Unable to connect qz to exp7i norditrack treadmill

**To Reproduce**

**Expected behavior**
I want to know how can i make it work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ios Ipad 8
 - Version 17.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi,if it has an android tablet, you have to follow this Nordictrack Treadmills Wifi only finally compatible with Zwift using QZ
https://youtu.be/_KRMSHxo5AQ

Let me know

**Comment by rainvd** [comment]
Hi, 
![PXL_20231217_002010060](https://github.com/cagnulein/qdomyos-zwift/assets/125037454/22b6bf3d-f9f5-4638-917b-8be285f35333)
I did like in the video, but nothing works. here is a picture of what i get, tank you

**Comment by cagnulein** [comment]
Please share a debug log so I can check your setup.
 The instructions are here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by rainvd** [comment]
[debug-dim__déc__17_19_28_24_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13698375/debug-dim__dec__17_19_28_24_2023.log.txt)
[debug-dim__déc__17_19_29_46_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13698376/debug-dim__dec__17_19_29_46_2023.log.txt)
[debug-dim__déc__17_19_31_54_2023.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13698377/debug-dim__dec__17_19_31_54_2023.log.txt)

**Comment by rainvd** [comment]
here are the ldebug ogs. Thank you

**Comment by cagnulein** [comment]
ok @rainvd the good news is that i'm getting the companion messages, the bad news is that the companion is not able to get the metrics from the treadmill. Did you already try to set the "c1750" device in the companion and restart the treadmill?
Try this and if it doesn't work neither, do this:
1) start a manual workout on the treadmill
2) while you're running, move to the companion app and press the dump log button
3) share here a picture of the text box of the companion

Let me know!

**Comment by rainvd** [comment]
![PXL_20231219_013857240 MP](https://github.com/cagnulein/qdomyos-zwift/assets/125037454/bc3407ac-9268-4939-8aa8-2db32c1383ae)

**Comment by rainvd** [comment]
There's the dump log

**Comment by cagnulein** [comment]
ok @rainvd could you please try with the "t75s" on the companion? restart the treadmill then and share me a new debug log from qz if it doesn't work. We have to find the way how the treadmill is logging the stats

let me know!

**Comment by rainvd** [comment]
![PXL_20231219_232403172](https://github.com/cagnulein/qdomyos-zwift/assets/125037454/dfe0319b-6cba-4325-8f81-bd978912e8e5)

**Comment by rainvd** [comment]
Not working with t75s

**Comment by cagnulein** [comment]
were you running a workout while you get this screenshot? if so, are you able to collect the wolflogs so i can check it if it's correct? and also are you able to connect to the treadmill via adb from your pc or mac?

**Comment by rainvd** [comment]
Hello Roberto, I take photos of the dump logs when I start a manual workout on the Ifit application on exp7i treadmill. I have access to Android in the background. Maybe I could recover the logs but I don't know how. As for Adb I think so. I installed qz on the treadmill via my PC and installation method 2 from your installation guide. Thanks again.

**Comment by cagnulein** [comment]
Ok if you have adb access is perfect: use this script https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat to collect the debug logs from the treadmill while a small workout

Don't worry we will get it!

**Comment by rainvd** [comment]
[2023-12-15.logs.txt](https://github.com/cagnulein/qdomyos-zwift/files/13733050/2023-12-15.logs.txt)

**Comment by cagnulein** [comment]
ok that's the issue, your ifit version doesn't log the metrics on the wolflogs file.
could you please upload also the files logcat.log, logcat.txt ? I would like to check if there is nothing also there.
If there is anything also, the last test is with a factory reset without updating the ifit app.
Let me know

**Comment by rainvd** [comment]
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13746468/logcat.txt)

**Comment by rainvd** [comment]
thank again

**Comment by cagnulein** [comment]
ok i will check this in a couple of days, im traveling for christmas
holidays

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 dic 2023 alle 23:06 rainvd ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@rainvd unfortunately there is no metrics at all, so ifit developers discovered QZ for sure and they removed all the metrics. In order to bypass this, you need to do a facatory reset and DON'T UPDATE the ifit app anymore then. Then install the companion and it should work. Let me know

**Comment by rainvd** [comment]
Hello, Roberto your application finally works on my exp7i treadmill. I followed a method to block ifit updates and afterward everything worked perfectly. Thank you again for your quick responses and your involvement. have a happy holiday.
