### ISSUE TITLE
echelon ex3 with samsung galaxy tab t6 light with peloton

### ISSUE THREAD

**Issue by berboris** [cagnulein/qdomyos-zwift#1891]
**Describe the bug**

During last session app lost connection  with bike (echelon start blinking and i felt like 0 resistance). 
It was fixed after restart but appears again in 6 minutes after.

all todays logs are attached

[archive (2).zip](https://github.com/cagnulein/qdomyos-zwift/files/13693788/archive.2.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[archive (2).zip](https://github.com/cagnulein/qdomyos-zwift/files/13693790/archive.2.zip)

**Comment by cagnulein** [comment]
could you tell me the time when you  experienced the disconnection?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 dic 2023 alle ore 21:03 berboris ***@***.***>
ha scritto:

**Comment by berboris** [comment]
I do not notice time. This screenshot I took then app even showed heart rate at the moment I took   Heart bit monitor off. 2.35 pm On Dec 16, 2023, at 3:12 PM, Roberto Viola ***@***.***> wrote:﻿
could you tell me the time when you  experienced the disconnection?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 16 dic 2023 alle ore 21:03 berboris ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
you have to upload the picture from the github web interface otherwise i
can't see it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 dic 2023 alle 21:38 berboris ***@***.***> ha
scritto:

**Comment by berboris** [comment]
![IMG_2774](https://github.com/cagnulein/qdomyos-zwift/assets/44621704/71a0ba43-8efb-41f9-836a-b559a43581ea)

**Comment by cagnulein** [comment]
checked, happened here Sat Dec 16 14:32:49 2023 1702755169497 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) " << f0 d1 09 00 c8 00 00 01 28 00 55 00 10"

the bike stopped to send data. did you need to reboot the bike as well? or only qz?

**Comment by berboris** [comment]
I rebutted app. And bike. And then it’s happen again. And I just finished workout woo it any resistance. On Dec 16, 2023, at 3:50 PM, Roberto Viola ***@***.***> wrote:﻿
checked, happened here Sat Dec 16 14:32:49 2023 1702755169497 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) " << f0 d1 09 00 c8 00 00 01 28 00 55 00 10"
the bike stopped to send data. did you need to reboot the bike as well? or only qz?

**Comment by cagnulein** [comment]
it's a problem on the bike i guess. Try the echelon app. if it happens also with the echelon app I suggest to contact echelon.
Try also a different tablet if it's the first time that you are using this tablet.

**Comment by cagnulein** [comment]
@berboris any news?
