### ISSUE TITLE
Support for Pro-Form Cycle Trainer 300 ci

### ISSUE THREAD

**Issue by fitzd** [cagnulein/qdomyos-zwift#1892]
**Is your feature request related to a problem? Please describe.**
Resistance control within app do not work on the bike. The data from the bike is being displayed on the app though.

**Describe the solution you'd like**
I would like to control the resistance of the bike through the app.

**Describe alternatives you've considered**
I tried to enable the different bike settings within the app for Proform one by one with no luck.

**Additional context**
None

**Comment by cagnulein** [comment]
hi @fitzd please attach a debug log with the issue, thanks

**Comment by fitzd** [comment]
Here you go 
[debug-Sun_Dec_17_10_52_36_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13697518/debug-Sun_Dec_17_10_52_36_2023.log)

**Comment by cagnulein** [comment]
got it, did you try to enable the proform cycle trainer 400 setting in the
proform bike settings (only this one enabled there) and restart qz?
if it doesn't work, try all of them, one by one, (only one must be enabled
at a time) and restart qz after each change.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 17 dic 2023 alle ore 20:26 Fitzgerald Daiz <
***@***.***> ha scritto:

**Comment by fitzd** [comment]
Hi Roberto, yes I've tried one by one listed in the Proform bike section including the cycle trainer 400 setting, except for the last 3 (the ip ones and the adb one). When I tried enabling the first 4 on the list one by one, each time my bike would constantly disconnect and reconnect from the app, if that's relevant at all.

**Comment by cagnulein** [comment]
so this means that your bike has a different profile. you can collect it
from the ifit app following this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 17 dic 2023 alle 20:37 Fitzgerald Daiz <
***@***.***> ha scritto:

**Comment by fitzd** [comment]
Here you go. I adjusted resistance and fan speed while logging.
[BT_HCI_2023_1217_124211.cfa.zip](https://github.com/cagnulein/qdomyos-zwift/files/13697590/BT_HCI_2023_1217_124211.cfa.zip)

**Comment by cagnulein** [comment]
thanks, i will check in the next days!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 17 dic 2023 alle 20:58 Fitzgerald Daiz <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
I checked the "NordicTrack GX 2.7" setting available in QZ and seems perfect for your bike, did you try it?

**Comment by fitzd** [comment]
I just tried it again and the resistance does not change if I try to increase or decrease through the app. The app's speed stays stuck at whatever speed the bike is set to. I also noticed when I adjust the fan setting through the app, the fan speed will change in the app but the bike's fan doesn't actually change.

**Comment by cagnulein** [comment]
i will check it again, it seemed the same
the fan is not handled for proform bike in qz, but i can do for sure
I will let you know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 14:16 FIT Dz ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@fitzd ok i understood why it's not changing the resistance. i need a hci snoof where you set all the resistance from the first one to the last one and then back to the first one by the ifit app directly
same thing for the fan

keep 2-3 seconds between change

Let me know!

**Comment by fitzd** [comment]
Here you go!
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13711382/btsnoop_hci.log)

**Comment by fitzd** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13711661/btsnoop_hci.log)
Set resistance from 1-16. No actual fan control in app. I thought you meant to control resistance from bike itself before my mistake.

**Comment by cagnulein** [comment]
ok perfect, i'm start working on this, thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 dic 2023 alle ore 06:50 FIT Dz ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@fitzd done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7274620672 download from the bottom of this page

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link. In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by fitzd** [comment]
Hi Roberto,
I tried the new version you linked on two different devices but the bike's resistance does not change when tapping on the - or + sign in the resistance tile within QZ

**Comment by cagnulein** [comment]
could you please share a debug log so i can check what i did wrong?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 dic 2023 alle 05:20 FIT Dz ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
did you enable the new setting for your bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 dic 2023 alle 07:35 cagnulein ***@***.***> ha
scritto:

**Comment by fitzd** [comment]
[debug-Thu_Dec_21_06_26_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13742329/debug-Thu_Dec_21_06_26_18_2023.log)
Hello here it is. Yes I enabled the new bike settings

**Comment by cagnulein** [comment]
@fitzd i guess the file is corrupted. it's only a 0 byte file.
Thanks!

**Comment by fitzd** [comment]
Sorry about that re-uploaded above

**Comment by cagnulein** [comment]
@fitzd can you check, if you change manually the reistance on the bike, if it changes correctly on the qz as well? and if it does, what if now you press the plus button on the resistance tile on qz?
Let me know!

**Comment by cagnulein** [comment]
do you mind upload also a debug log in this scenario, I can't see any issue in the code explaining this. Thanks

**Comment by fitzd** [comment]
[debug-Thu_Dec_21_09_38_58_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13744200/debug-Thu_Dec_21_09_38_58_2023.log)

**Comment by cagnulein** [comment]
thanks I will check probably in a couple of days. Tomorrow I will have a
travel day (more or less 700km alone along Italy :) )

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 dic 2023 alle ore 17:42 FIT Dz ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@fitzd i added more init frames in the code since i can't fine any other differences. It's building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7321444729

Let me know and merry christmas!

**Comment by cagnulein** [comment]
@fitzd any news?

**Comment by fitzd** [comment]
@cagnulein Hi sorry was out of country but came back recently. I had a chance to try the new build today but still the same issue. Changes on bike show up on tile but pressing the - or + on the tile doesn't change the bike itself.

**Comment by cagnulein** [comment]
argh, could you please upload another debug log with this?

**Comment by fitzd** [comment]
[debug-Sun_Jan_28_20_12_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14079258/debug-Sun_Jan_28_20_12_41_2024.log)

Sorry for the late reply. Here's my latest debug where I tried to increase and decrease resistance after I waited for the correct bike stats to populate the tiles before I tapped the tiles.

**Comment by cagnulein** [comment]
ok note for me: exported file to comapre
[converted_full_hex_to_cpp.txt](https://github.com/cagnulein/qdomyos-zwift/files/14085432/converted_full_hex_to_cpp.txt)

**Comment by cagnulein** [comment]
argh the debug log is a 0 byte. can you upload it again?
Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle ore 04:19 FIT Dz ***@***.***>
ha scritto:

**Comment by fitzd** [comment]
Sorry, not sure why it sometimes copy no data to the file when uploading
[debug-Sun_Jan_28_20_12_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14098436/debug-Sun_Jan_28_20_12_41_2024.log)

**Comment by cagnulein** [comment]
@fitzd ok i tried to add more frames too

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7723358007

can you try this?

also if it still doesn't work, can you try to change manually the resistance on the bike to a different resistance value, check that qz is getting it and then try to change again from the qz tile?

Let me know!

**Comment by fitzd** [comment]
Thanks for working with me thus far. Still no response from the bike after tapping the tile. When I first start up qz it looks like it finds I_EB right away, and then it takes about 10 seconds before QZ shows the actual resistance setting from the bike.

After getting the resistance setting, I adjust the bike resistance and see it reflected on QZ right away. Then I try to set the resistance via the +/- buttons on QZ but it doesn't change the resistance on the bike.

Here's my debug log from my latest attempt.
[debug-Fri_Feb_2_17_54_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14147289/debug-Fri_Feb_2_17_54_16_2024.log)

**Comment by cagnulein** [comment]
Argh i will check it once again, it must be something!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 01:59 FIT Dz ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@fitzd never give up, let's try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/7783558952
share always a debug log if it still doesn't work. i hope we are near

**Comment by fitzd** [comment]
[debug-Mon_Feb_5_19_42_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14174101/debug-Mon_Feb_5_19_42_59_2024.log)
Sorry still the same issue. Here's the steps I performed during logging:
1. Resistance was already set to 3 on the bike
2. Start QZ after setting bike settings to proform 300 ci and restarting app
3. About 10 seconds later the resistance tile shows 3, I increase the resistance on the bike 3 times, then decrease it 3 times. It shows the correct resistance on the app almost right after I change it on the bike.
4. With the resistance back to 3 on the bike, I try to increase the resistance by tapping on the tile 3 times, then I try to decrease it 3 times. No change to the bike's actual resistance or reading on the tile.

**Comment by cagnulein** [comment]
@fitzd looking deeply i found 2 inverted bytes in the init phase. maybe that's the issue
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7828462423

finger crossed!

**Comment by fitzd** [comment]
It worked!!! Those inverted bytes were the issue. I can successfully change the resistance on the bike using the app's tiles. Thank you!

**Comment by fitzd** [comment]
Thank you! Can't wait to update to the latest version

**Comment by cagnulein** [comment]
@fitzd any news?

**Comment by cagnulein** [comment]
it's the Cycle Trainer 300 CI
which version do you see on the store? it should see 2.16.46
Let me know

**Comment by fitzd** [comment]
It works now, sorry for the confusion! I uninstalled and re-installed and cleared app storage data as well. I may have still been on the non-beta earlier. I can confirm that I'm on beta version 2.16.46.

**Comment by cagnulein** [comment]
Glad to hear it!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle ore 17:40 FIT Dz ***@***.***>
ha scritto:
