### ISSUE TITLE
[BUG] Won’t read incline 

### ISSUE THREAD

**Issue by Vljohnson904** [cagnulein/qdomyos-zwift#1894]
**Describe the bug**

the app will not read my incline 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14
[debug-Sun_Dec_17_19_18_37_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13698345/debug-Sun_Dec_17_19_18_37_2023.log)

 - OS: [e.g. iOS8.1] IOS 
 - Version [e.g. 22] 17.2 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Vljohnson904 you have to disable the "Force Using FTMS" setting in qz under the horizon settings. This will use the same protocol of the horizon app and it will read also the inclination. THe counterside is that the initial connection will take up to a minutes.
Let me know!

**Comment by cagnulein** [comment]
@Vljohnson904 any news?
