### ISSUE TITLE
[BUG] Incline and speed not working from iOS app on c1750 2021

### ISSUE THREAD

**Issue by compucoder** [cagnulein/qdomyos-zwift#1895]
**Describe the bug**
When I hit incline up or down the screen registers a tap but nothing happens. Speed up and down doesn’t register a tap. Force experimental feature is enabled 

**To Reproduce**
1. Go to QZ iOS app. 
2. Click on incline + or - 
3. Screen registers a tap somewhere but no incline happens. Speed up or down doesn’t register a tap and doesn’t change. 
4

**Expected behavior**
Incline should change and speed should change as per supported feature and treadmill model. 

**Screenshots**

![IMG_0195](https://github.com/cagnulein/qdomyos-zwift/assets/2752153/245e86ae-f572-4e3d-b846-56bc2893a254)
![IMG_0199](https://github.com/cagnulein/qdomyos-zwift/assets/2752153/8ab28121-3a98-40fc-b2bc-d039082751ba)
![IMG_0200](https://github.com/cagnulein/qdomyos-zwift/assets/2752153/6f03be9b-9c9b-4527-ad68-19bafc75118b)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Plus
 - OS: iOS 
 - Version 17.2

**Append a debug log**
[debug-Sun_Dec_17_18_50_22_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13698739/debug-Sun_Dec_17_18_50_22_2023.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by compucoder** [comment]
App is installed on my nordictrack c1750. Bought it end of 2022. So not latest model. One before that. Have 1750 selected. Also tried the 2950 ones plus the other. Also tried with ADB remote setting on and off. Don’t have any other settings set except for the IP. App reads treadmill data fine. 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/2752153/df2b51a8-fbb2-4b95-8254-a84b755deaef)

**Comment by cagnulein** [comment]
hi @compucoder if you see the random touch events on the console when you press the plus and minus buttons in qz it means that we just need to change the coordinates.
Using adb run this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat and share the output here so i can check the coordinates and implement them

Let me know!

**Comment by compucoder** [comment]
Here is the screenshot.


________________________________

**Comment by compucoder** [comment]
@cagnulein here is the screenshot. Thank you so much! 
![Mon12-18-2023@8-48-02 20](https://github.com/cagnulein/qdomyos-zwift/assets/2752153/e20eaf39-aa51-41e6-8519-4ee24885046a)

**Comment by cagnulein** [comment]
thanks, I will check this in the next days

**Comment by compucoder** [comment]
Just wondering if there is a way to do this without touch events? I assume iFit just sends commands to the treadmill for changing incline and speed. Is there anyway to figure out how they are doing that and tap into it? If I can be of any assistance helping provide access or debug logs of the treadmill in this area let me know.

**Comment by cagnulein** [comment]
yes we can do bypassing directly the use. I started the code for this here #1577 but i need help because i need some info on the usb part. are you tech savvy?

**Comment by compucoder** [comment]
very cool! And yes, I am ok on the technical side. I was a senior web developer for 20 years ; now manage a team of Ruby devs. So, not a coder like I once was but might be able to lend a hand if you need it.

**Comment by cagnulein** [comment]
what i would need is sniff the usb serial port from a treadmill using a
raspberry or similar
could you be able to do it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 17:57 Ron Craig ***@***.***>
ha scritto:

**Comment by compucoder** [comment]
I didn't even know it had a usb serial port ; must be hidden away. I don't have a raspberry - only have a macbook pro or windows laptop. Will one of those work?

**Comment by cagnulein** [comment]
mmm nope we need a raspberry because it needs to act like a device. what we
need to do is sniffing the usb serial port traffic

anyway i will update the coordinates for your treadmill hopefully later
today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 18:06 Ron Craig ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done! new apk ready @compucoder  https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.21/QZCompanionNordictrackTreadmill.apk

**Comment by compucoder** [comment]
Thank you!

**Comment by compucoder** [comment]
Hi @cagnulein - I can confirm the mapping worked. There is a fair bit of delay from changing the incline or speed to when it happens but that might just be network related. It is about 5 seconds from touch to change. I'll have to give it a try with zwift - my next task. As for the usb hacking ; let me know if there is anything else I can do to help there. My model doesn't have a port nor do I have a PI. But maybe I can install something that logs the commands sent from the ifit command to the incline and speed modules. Perhaps some type of inline debugger. Whatever you need :)

**Comment by cagnulein** [comment]
It has a usb port but is inside, I guess it’s a flat cable
Another way to do this without any hardware modifications, it’s using a usb
module sniffer on the android tablet directly
https://www.baeldung.com/linux/usb-sniffing


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 dic 2023 alle 23:29 Ron Craig ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@compucoder any news?

**Comment by compucoder** [comment]
Everything worked well. Sadly I could not do the port sniffing. Hopefully someone can do that eventually

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
