### ISSUE TITLE
[BUG] Apple watch  HR questions

### ISSUE THREAD

**Issue by gitoutofhere8** [cagnulein/qdomyos-zwift#1897]
Hi @cagnulein, I've noticed a few behaviours that were surprising.  These may not be bugs but I wanted to get your confirmation.

-It appears that Apple watch integration requires write permissions in Apple Health, otherwise the values do not show in the QZ iOS app.  Is this expected?

I am trying to prevent a QZ entry in the Apple Fitness log after a session as it is duplicating the Peloton log entry.

-When configured to connect to the tread companion app, the HR does not appear in QZ unless QZ is first connected to the companion app.

-The start button on the watch seems to be required to be pressed, otherwise the QZ HR tile is not updated.  If stop is pressed, the value in QZ stays frozen unless start is pressed again.

**Comment by cagnulein** [comment]
> -It appears that Apple watch integration requires write permissions in Apple Health, otherwise the values do not show in the QZ iOS app. Is this expected?

yes these are apple rules :)



> I am trying to prevent a QZ entry in the Apple Fitness log after a session as it is duplicating the Peloton log entry.

just close the qz apple watch app instead of pressing stop there



> -When configured to connect to the tread companion app, the HR does not appear in QZ unless QZ is first connected to the companion app.

right



> -The start button on the watch seems to be required to be pressed, otherwise the QZ HR tile is not updated. If stop is pressed, the value in QZ stays frozen unless start is pressed again.

right!
