### ISSUE TITLE
[BUG] auto resistance not working with smart spin 2k

### ISSUE THREAD

**Issue by Dpmiller1986** [cagnulein/qdomyos-zwift#1899]
**Describe the bug**
Smart spin 2k auto resistance not working. I can change the resistance with the controller but it won’t automatically adjust with the peloton class

**To Reproduce**
1. Turn on bike
2. Link with qz
3. Turn on smart spin
4. Accept pairing with iPad via Bluetooth for smart spin
5. Start peloton class
6. Sync class start with qz for adjustment 

**Expected behavior**
Resistance should adjust with smart spin. Qz does show the levels correctly and I can use the controller that comes with smart spin but it won’t do auto resistance 

**Screenshots**
![IMG_0600](https://github.com/cagnulein/qdomyos-zwift/assets/149392174/3af7c600-4a19-49a7-a0af-37b77a00e63b)
![IMG_0599](https://github.com/cagnulein/qdomyos-zwift/assets/149392174/d0e763fd-40a0-40d4-b66b-7e11bb5adde6)
![IMG_0601](https://github.com/cagnulein/qdomyos-zwift/assets/149392174/f3042061-4b78-4c16-9feb-025a3a7f1c21)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Dpmiller1986 please attach a debug log of the issue following this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Dpmiller1986** [comment]
Just tested it and it worked ok today will try again tomorrow

**Comment by cagnulein** [comment]
great! let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 dic 2023 alle 10:26 Dpmiller1986 ***@***.***>
ha scritto:

**Comment by Dpmiller1986** [comment]
Did two classes this evening. First one perfect. Second one was a bit off but did still work.If I get the notification pair smart spin with iPad I assume I press pair. I get it mid ride so I’m thinking it might be that causing the issue. Also doesn’t like it sometimes when I try and manually adjust using smart spin controller. Does eventually correct itself.Attached the debug anyway see what you think.Sent from my iPadOn 22 Dec 2023, at 11:02, Roberto Viola ***@***.***> wrote:﻿
great! let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 22 dic 2023 alle 10:26 Dpmiller1986 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
hi @Dpmiller1986 you have to attach the debug log from the GitHub web interface directly otherwise i can't see it

**Comment by cagnulein** [comment]
@Dpmiller1986 any news?
