### ISSUE TITLE
[BUG] Mobvoi TM Incline - SPM data isn't being reported

### ISSUE THREAD

**Issue by kvj** [cagnulein/qdomyos-zwift#1900]
**Describe the bug**

Follow-up of https://forums.zwift.com/t/mobvoi-tm-incline-android-connection-lost/610261/10

SPM/Cadence isn't being reported to the QZ. Speed, distance, inclination is reported correctly.

**To Reproduce**
1. Buy Mobvoi TM Incline :smile: 
2. Connect it via QZ
3. Optionally connect QZ to Zwift
4. SPM is always 0

NRF Connect screenshot and app log is attached

**Expected behavior**
Correct value should be reported, as total number of steps is being shown on the TM display

**Scree
![Screenshot_2023-12-20-17-21-37-52_3c2e989be58abe9ca7463ffb1e6967d2](https://github.com/cagnulein/qdomyos-zwift/assets/159124/5b7d5ee0-6acd-4304-a8f5-c7e7207feb1a)
nshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version latest

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 13

**Append a debug log**
[debug-Wed_Dec_20_17_07_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13729784/debug-Wed_Dec_20_17_07_30_2023.log)

    
**Additional context**

**Comment by cagnulein** [comment]
@kvj thanks. Log checked. Are you sure your treadmill send this information? On the FTMS characteristics this information is not present. Also this treadmill doesn't have any RSCMeasurement characteristic. Maybe it's sending it on a custom characteristic. If you have an app that can read the SPM from this treadmill I can check it.
Otherwise you can use a external foot pod on QZ

Let me know

**Comment by cagnulein** [comment]
> @cagnulein 
> 
> that makes sense. I wasn't sure about the cadence support, I thought maybe "Step Count" is an indirect metric for that.


where do you see the step count? you mean on the qz tile? all the qz tiles are available for all the treadmills, but not all the treadmills are sending the same metrics 

> 
> 
> 
> Then, what would you suggest, what should I do?
> 
> 1. Reanimate old Stryd sensor that I have, probably without any clips left, hoping it will work. Is Stryd supported by QZ and/or Zwift without stryd app and subscription?

absolutely, qz supports it without any subscription 

> 
> 2. Spend 45 EUR on Garmin Running Pod https://amzn.eu/d/7lS9lAw Will it work with QZ/Zwift?

it will work but if you have already a stryd is useless :)

> 
> 3. Try to integrate Coros POD 2. Has anyone ever approached you with this device? It's BLE, but probably uses own proprietary protocol. Only Coros watches are officially supported

sure we can also do this!

let me know

**Comment by kvj** [comment]
> where do you see the step count?

I refer to the NRF Connect report - you can see that "Step Count" is being reported as a supported feature.

> but if you have already a stryd is useless

Not sure that Stryd is functional after 3 years on the shelf. Battery could be dead. Charging it now. I also have no clips for it.

**Comment by cagnulein** [comment]
> > where do you see the step count?
> 
> 
> 
> I refer to the NRF Connect report - you can see that "Step Count" is being reported as a supported feature.

mmm interesting, i will definitely check it again

> 
> 
> 
> > but if you have already a stryd is useless
> 
> 
> 
> Not sure that Stryd is functional after 3 years on the shelf. Battery could be dead. Charging it now. I also have no clips for it.

**Comment by cagnulein** [comment]
triple checked.
<img width="813" alt="Screenshot 2023-12-20 at 21 41 51" src="https://github.com/cagnulein/qdomyos-zwift/assets/48216/bd5ca7a6-4e80-42aa-8407-226625de78e1">

the step count is only for step climber data. So I thought, "ok, maybe they send both treadmill data and step climber data" but no, they aren't. so i guess they probably set this but they forgot to add this characteristcs.
Probably in a custom characteristics they are sending this information (do you see on the console of the treadmill too?)

**Comment by kvj** [comment]
Hi @cagnulein 

I keep playing with QZ + Treadmill + Stryd + Polar.
Do I get it right that QZ doens't expose `0x1814` BLE characteristic and therefore Stryd's running cadence (is SPM) isn't being exposed to Zwift?

**Comment by cagnulein** [comment]
on android, it's an android limitation @kvj you have to use the wahoo tread sensor instead in zwift (wifi bridge from qz), not the bleutooth bridge.

**Comment by kvj** [comment]
thanks! I'm currently looking into the dircon data. Could you pleas point me which service/characteristic exposes it?

**Comment by cagnulein** [comment]
the 0x1814 on dircon, it's automatically recognized from zwift, you don't have to do anything ;)

**Comment by kvj** [comment]
@cagnulein hmm. doesn't work for me.

In QZ, I've configured Stryd via Accessories -> Cadence Sensor Options. Is it a right place?

In my case, dircon shows three services: 0x1826, 0x1818 and 0x1816.

Zwift always shows Cadence as 0 SPM when I use QZ and works correctly with Stryd natively

**Comment by cagnulein** [comment]
@kvj nope you should set to the power sensor setting. Disable it from the cadence sensor setting.
Also where you are looking the dircon services?

**Comment by kvj** [comment]
Thanks! Power sensor finally working for me.

>  Also where you are looking the dircon services?

mdns + tcp + dircon protocol isn't a rocket science :) I'm sending `DPKT_MSGID_DISCOVER_SERVICES` (so far) and checking the response.

**Comment by cagnulein** [comment]
eheheh i'm using discovery app on ios :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 13:06 Konstantin ***@***.***>
ha scritto:

**Comment by kvj** [comment]
Hi @cagnulein 

Few questions about the dircon implementation:
1. I see that QZ broadcasts all NOTIFY characteristics without waiting for `DPKT_MSGID_ENABLE_CHARACTERISTIC_NOTIFICATIONS` message. Is this a part of protocol or you just simplify the implementation?
2. Are `DPKT_CHAR_PROP_FLAG_` actually bit masks? I see that for some characteristics which designed as READ, NOTIFY but you report them as DPKT_CHAR_PROP_FLAG_NOTIFY. Again is it a part of protocol or implementation?

**Comment by cagnulein** [comment]
hi @kvj i don't remember the implementation, you can check the code directly. what are you trying to do?

**Comment by kvj** [comment]
> hi @kvj i don't remember the implementation, you can check the code directly. what are you trying to do?

:smile: 

I'm trying to grab the metrics I'm interested in from QZ and send it to the home automation server (Home Assistant). And eventually get a way to control parts of my treadmill from there. On a practical side I'd like to create shortcuts to predefined speed (pace) values to simplify my workouts.

So far, dircon protocol looks very promising

**Comment by cagnulein** [comment]
wow that what I would like to do too! i guess we can just write a dircon
plugin for home assistant :)
I don't have much time right now, but i guess it should be quite easy to do
simply parsing it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:09 Konstantin ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
also remember that qz has also the ability to create xml workout program if
you want :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:16 cagnulein ***@***.***> ha
scritto:

**Comment by kvj** [comment]
> wow that what I would like to do too! i guess we can just write a dircon
plugin for home assistant :)

sure, I'm already half way there

**Comment by cagnulein** [comment]
amazing! are you doing it here on github?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:17 Konstantin ***@***.***>
ha scritto:

**Comment by kvj** [comment]
> amazing! are you doing it here on github?

yes, all my Home Assistant stuff here. I will publish the custom integration shortly
