### ISSUE TITLE
TDF 5 inclination going crazy

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#1901]
It happens around the 5:35 minutes into the ride and again around 16:44 minutes in.

[debug-Wed_Dec_20_12_40_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13731593/debug-Wed_Dec_20_12_40_10_2023.log)

[debug-Wed_Dec_20_12_40_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13731605/debug-Wed_Dec_20_12_40_10_2023.log)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks, i will check this asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 dic 2023 alle 20:49 Dwhetsel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @Dwhetsel I guess you uploaded the wrong logfile, this is more or less empty. You probably have another from today.
Let me know!

**Comment by Dwhetsel** [comment]
[debug-Wed_Dec_20_12_40_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13732687/debug-Wed_Dec_20_12_40_10_2023.log)

this is the only one I see.

**Comment by cagnulein** [comment]
so maybe you enable the debug log AFTER the issue? anyway let's log again, keep this setting enabled, so the next time we will have it. Thanks

**Comment by Dwhetsel** [comment]
Try this one 
[debug-Wed_Dec_20_11_35_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13732767/debug-Wed_Dec_20_11_35_12_2023.log)

**Comment by cagnulein** [comment]
same thing :(
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 dic 2023 alle ore 22:33 Dwhetsel ***@***.***>
ha scritto:

**Comment by Dwhetsel** [comment]
I actually see there are three different ones with different times in the name. Here is the other.
[debug-Wed_Dec_20_11_35_12_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13732801/debug-Wed_Dec_20_11_35_12_2023.log)

**Comment by Dwhetsel** [comment]
One says it is 30 MB and too big to upload. I have tried competing but won’t seem to do it. It’s on my iPhone.

**Comment by cagnulein** [comment]
> One says it is 30 MB and too big to upload. I have tried competing but won’t seem to do it. It’s on my iPhone.

that's the one that i need. compress it before upload it :)

**Comment by Dwhetsel** [comment]
Compressing is what I meant to say. It doesn’t seem to do it. I select it and then select compress but nothing happens.On Dec 20, 2023, at 3:43 PM, Roberto Viola ***@***.***> wrote:﻿

One says it is 30 MB and too big to upload. I have tried competing but won’t seem to do it. It’s on my iPhone.

that's the one that i need. compress it before upload it :)

**Comment by cagnulein** [comment]
it creates a new file zipped in the files app :)
anyway i'm going to bed now (11 pm here in italy).

**Comment by Dwhetsel** [comment]
I keep messing with it. Good night.On Dec 20, 2023, at 3:51 PM, Roberto Viola ***@***.***> wrote:﻿
it creates a new file zipped in the files app :)
anyway i'm going to bed now (11 pm here in italy).

**Comment by cagnulein** [comment]
thanks! in case upload it on wetransfer and share here the link

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 dic 2023 alle 22:54 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
This is the one from the zip files. 
[debug-Wed_Dec_20_11_35_35_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13732913/debug-Wed_Dec_20_11_35_35_2023.zip)

**Comment by cagnulein** [comment]
Checked and it’s very strange, the bike change the inclination by itself.
It was not commanded by qz In that case. I will check the log again
tomorrow, but it seems a firmware bug on the bike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 dic 2023 alle 22:58 Dwhetsel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
yes double checked, qz is doing the right thing, sometimes the bike starts from a inclination swipe without any intervention. The only thing that I could think of, it's that maybe 1 second polling to the bike is too much and this creates this issue. We can slow it down but probably the best way it's to completely switch off the inclination motor to remove this side effect (i have mine disconnected actually too)

**Comment by Dwhetsel** [comment]
Is there a way to turn it off without physically unplugging it? Also why is the resistance not showing any data on the QZ app?

**Comment by cagnulein** [comment]
> Is there a way to turn it off without physically unplugging it

i don't know if from the settings of the bike you can disable it. i guess so.



> Also why is the resistance not showing any data on the QZ app?

because for zwift i'm using the inclination as reference, it has more sense in the game

**Comment by elfonashelfna** [comment]
I have unplugged the inclination motor and I believe it might’ve fixed it. Granted it was only a 2 mile ride but I’ll try a much longer ride shortly.
![IMG_2622](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/8f5e1bce-f24d-43d3-8ff5-16fd6f486fc8)
There is the image of the connection you need to unplug. It’ll be the very bottom right connection. In order to get to this board, watch https://youtu.be/qrFOkTV5VRY?si=RjTgO_xPTAm1ee2s and do NOT go past 0:50, you’ll be doing more steps than you need. Once you get the plastic clear cover off, you can reach a long flat head screwdriver or any tool down to that connection and fiddle it off. It’ll be easy because there’s no clips or anything you have to hold in while pulling it off. 

Try Zwifting again and let me know what you think on your side! I didn’t do any other changes other than unplugging it.

**Comment by Dwhetsel** [comment]
Great, Thanks, I'll give it a try.

**Comment by Dwhetsel** [comment]
I unhooked mine and it continually cycles back and forth trying to adjust the inclination anyway. The resistance changed a couple times but the noise of it trying to incline never stopped. I have attached a debug here. 
[debug-Fri_Dec_22_10_20_12_2023.zip](https://github.com/cagnulein/qdomyos-zwift/files/13754318/debug-Fri_Dec_22_10_20_12_2023.zip)

**Comment by Dwhetsel** [comment]
Okay, never mind. I went into machine settings and re-calibrated it. It attempted and then said it failed. However then it quit trying to incline. I rode a 6 mile ride on Zwift and the resistance seemed to work great. Now I’m wondering if just re-calibrating with the motor hooked up would have fixed the problem. I don’t think I will re-hook it up though, don’t really need it. I do think the resistance was a tad easier without the inclination though, may just be me.
Roberto, here is the debug log from after the re-calibration if it helps you do the fantastic things you do.
[Uploading debug-Fri_Dec_22_10_37_54_2023.zip…]()

**Comment by elfonashelfna** [comment]
That’s great to hear! I guess I could’ve mentioned to recalibrate it but I thought it didn’t do anything because where it said “failed to calibrate”. Looks like that is an important thing to mention now! I DO KNOW that recalibrating it with the motor hooked up didn’t fix the issue.. I tried it last night matter in fact and the issue still was still active.

**Comment by cagnulein** [comment]
@elfonashelfna @Dwhetsel I don't know if i mentioned, but you have ALWAYS to stay in the manual workout window in the bike console, or even better in the main menu window. Otherwise the bike could receives input also from the console itself
