### ISSUE TITLE
[BUG]Bowflex BTX116 Not Connecting

### ISSUE THREAD

**Issue by Redventuress** [cagnulein/qdomyos-zwift#1902]
[**Describe]([debug-Thu_Dec_21_06_50_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13743309/debug-Thu_Dec_21_06_50_33_2023.log)) the bug**

1.opened app (qdomyo zwift)
2. Treadmill show blue sold light indicating Bluetooth is connected. 
3. Dashboard shows treadmill found, start button is blinking red
4. Click on start button, red flash stops briefly but then starts again. No other variables change. 

**Expected behavior**
It appears the app finds treadmill and connects but no info if flowing back & forth. 

**Screenshots**

![IMG_8525](https://github.com/cagnulein/qdomyos-zwift/assets/154535727/457fe9db-26ef-40fe-8afc-5dd9ba73ade3)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 pro
 - OS: 17.1.2
 - Version 2.15

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Redventuress could you please attach the debug log file following this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?

**Comment by sosaha** [comment]
I am having the same issue. Please find the debug log attached.
[debug-Tue_Jan_9_09_17_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13877013/debug-Tue_Jan_9_09_17_42_2024.log)

**Comment by sosaha** [comment]
Here are the logs.
[nfrconect-Log 2024-01-09 09:40:41.log](https://github.com/cagnulein/qdomyos-zwift/files/13877209/nfrconect-Log.2024-01-09.09.40.41.log)

**Comment by sosaha** [comment]
![20240109_113951](https://github.com/cagnulein/qdomyos-zwift/assets/1514678/ac28b5f8-3434-4357-b316-d305f6cfae45)
![20240109_113938](https://github.com/cagnulein/qdomyos-zwift/assets/1514678/bc5748e3-306a-46ee-9757-6c5924ab8425)

**Comment by cagnulein** [comment]
ok from the last service i need its children, you should get them clicking on it or disconnect and reconnecting to it. 

or in case i will build a new version of qz getting them if you can't from nrfconnect. let me know

**Comment by cagnulein** [comment]
never mind, the log has everything! i will implement this tomorrow!

**Comment by sosaha** [comment]
Great. Thanks

**Comment by cagnulein** [comment]
@sosaha @Redventuress done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7471629750

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link. In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded. Be aware that you will lose your settings, so in case backup them or let me know if you want to wait the google official version in the beta.

This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by sosaha** [comment]
Seeing same issue.

**Comment by cagnulein** [comment]
@sosaha share a debug log so i can check it

**Comment by sosaha** [comment]
Here you go. The attachment got dropped on github.
[debug-Wed_Jan_10_11_00_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13892382/debug-Wed_Jan_10_11_00_51_2024.log)

**Comment by cagnulein** [comment]
@sosaha thanks, actually i can see the metrics now in the log, i just need to parse them, we are getting closer! was the treadmill running? if so at which speed?

**Comment by sosaha** [comment]
In this case it was not running but I tried from my phone while it was
running at 1mph and the start button was showing blinking red as before.

**Comment by cagnulein** [comment]
ok could you please attach a debug log where the treadmill is running at
1km even if you don't see nothing in qz? thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 21:05 Soumyajit ***@***.***>
ha scritto:

**Comment by sosaha** [comment]
I ran a minute on 1 Miles per hour and then moved up to 3 MPH
[debug-Wed_Jan_10_12_14_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13893722/debug-Wed_Jan_10_12_14_55_2024.log)
[debug-Wed_Jan_10_12_15_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13893723/debug-Wed_Jan_10_12_15_38_2024.log)

**Comment by cagnulein** [comment]
thanks! i will check it tomorrow!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 21:20 Soumyajit ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
sorry @sosaha last request: are you able to collect a debug log where you are changing the speed from 1 to 2 to 3 to 4 to 5 to 6 and also the incline to the same steps? because leaving to just 1 it makes the thing harder!
Thanks! after this I should be able to parse them!
Thanks!

**Comment by cagnulein** [comment]
@sosaha any news?

**Comment by sosaha** [comment]
I will get it today

**Comment by sosaha** [comment]
Please find the logs attached. I icreased incline from 1-15 initially, than changed incline to 1 and increased speed from 1-10 mph
[debug-Fri_Jan_12_06_59_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13922559/debug-Fri_Jan_12_06_59_17_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it tomorrow!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 gen 2024 alle 19:02 Soumyajit ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
perfect @sosaha give it a try to this https://github.com/cagnulein/qdomyos-zwift/actions/runs/7508899168/artifacts/1166679314 it should works now! let me know in case not!

**Comment by cagnulein** [comment]
@sosaha sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7513137529

**Comment by cagnulein** [comment]
@sosaha any news?
