### ISSUE TITLE
[BUG] TDF 4.0 Incline Unplugged 

### ISSUE THREAD

**Issue by elfonashelfna** [cagnulein/qdomyos-zwift#1906]
[Log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13756771/Log.txt)
**Describe the bug**
I know we have discussed the incline/resistance problems with my TDF 4 and Davids TDF 5 and we are thinking the potential solutions is to unplug the inclination motor. I did a 10 mile ride and something still seemed off, I wanted to provide another log that included zwift and QZ.  

An example of what the problem is, I will be in a group ride and we will be riding on a 0% incline straight stretch. Then randomly, the resistance on TDF/QZ will go to -5% or vise versa. This will lead me get dropped from the group because it messes with all the other metrics. 
**To Reproduce**
[Uploading debug-Fri_Dec_22_14_37_35_2023.log…]()

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max. 
 - OS: 17.1.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @elfonashelfna the debug log is truncated. could you please upload it again?

**Comment by elfonashelfna** [comment]
[Log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13756781/Log.txt)
[debug-Fri_Dec_22_14_37_35_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13756782/debug-Fri_Dec_22_14_37_35_2023.log)

![IMG_2636](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/de7fd648-f759-4940-aec6-6a67f66fa962)
![IMG_2635](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/34573d17-3402-45b6-9569-e20e3baf8673)
![IMG_2634](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/d7e4f3ce-0152-4cbf-a2af-6f6cb1102f4c)
![IMG_2633](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/fd173369-d4bb-4e98-b067-dbb062b6e765)
![IMG_2632](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/745775a0-0543-4d71-bf57-037d2842d798)
![IMG_2630](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/5638b52c-3b65-4651-b785-5994b46d9e57)
![IMG_2629](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/e4cd1705-df04-48f9-b2e9-793bcae01baf)

The screenshots show the differences in the incline with TDF and Zwift. Please note what is shown on the TDF is what also is shown on QZ.

**Comment by cagnulein** [comment]
ok i will check this in the next days
remember to 2 things: zwift shows an average of inclination but it sends to
qz the instant value, so both value could be not aligned . this is true for
all the bikes.

also gears on qz affect the incline. are you using them?

if we don't speak sooner, have a nice christmas

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 dic 2023 alle 22:28 elfonashelfna ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
linked to #1901

**Comment by cagnulein** [comment]
@elfonashelfna i checked the log and it's the bike that it's going itself. but i guess i understood your issue. From your screenshot I saw that you're not on a manual workout on the bike. You must be, otherwise the bike is receiving command from QZ but it's trying also to follow the workout in the map view. So stay in the manual window on the bike and you should be fine (my tdf4 bike has the same console and I don't have this issue in the manual workout)
Let me know

**Comment by Dwhetsel** [comment]
I use the gears on the bike but can not say that I have ever seen the gears shown on the app show anything. I also do not see a resistance shown on the app, just the incline. And it is usually the same as I do run in manual mode. Could there be a setting in the app I don not have turned on?

**Comment by cagnulein** [comment]
> I use the gears on the bike but can not say that I have ever seen the gears shown on the app show anything. 

ok so if you are using the gears on the bike, my question is answered, that's not the issue.

> I also do not see a resistance shown on the app, just the incline. And it is usually the same as I do run in manual mode. 

yes because qz for this bike populate only the inclination, correct.

> Could there be a setting in the app I don not have turned on?

nope, for what i saw in your log the only thing that could cause this issue is the fact that you aren't in the manual window or home window on the bike. can you confirm this?

**Comment by Dwhetsel** [comment]
Sorry Roberto, this is David. I did’t mean to hijack the thread. I did t have the problem, just questions.

**Comment by cagnulein** [comment]
> Sorry Roberto, this is David. I did’t mean to hijack the thread. I did t have the problem, just questions.

sorry i was answering from the phone and i didn't realize the sender :)

**Comment by elfonashelfna** [comment]
@cagnulein I just finished a 14 mile ride while in manual workout and from the grand scheme of things, I had no issues. I do have one quick question and final question. Although everything is working and connected, why does QZ always associate my bike with my white noise machine in the bedroom? Haha. Definitely nothing to worry about I was just curious! 
![IMG_2637](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/80010829-5f41-4aba-8de6-35d28f779971)

**Comment by cagnulein** [comment]
that label is just a description of the last bluetooth device that it
discovered :)
nothing to be worried about :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 dic 2023 alle 15:39 elfonashelfna ***@***.***>
ha scritto:
