### ISSUE TITLE
[BUG] Nordictrack Treadmill / speed and inclination 

### ISSUE THREAD

**Issue by Mariemartin** [cagnulein/qdomyos-zwift#1908]
Following messenger conversation with Roberto, created a bug report with android device while using iFit for auto speed and inclunation.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[bugreport-2023-12-23-12-14-07.zip](https://github.com/cagnulein/qdomyos-zwift/files/13759772/bugreport-2023-12-23-12-14-07.zip)

**Additional context**

**Comment by cagnulein** [comment]
L6.0s treadmill (info for me)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 dic 2023 alle 18:36 Mariemartin ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Mariemartin are we ok with this?

**Comment by Mariemartin** [comment]
Yes Roberto!Everything works just fine 😀Thank you so much!Marie-ClaudeEnvoyé de mon iPhoneLe 11 janv. 2024 à 04:55, Roberto Viola ***@***.***> a écrit :﻿
@Mariemartin are we ok with this?

**Comment by cagnulein** [comment]
perfect! have a nice day!
