### ISSUE TITLE
[BUG] erg doesn’t seem to work, watts very low

### ISSUE THREAD

**Issue by Scott902** [cagnulein/qdomyos-zwift#1909]
[debug-Sun_Dec_24_09_10_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13761925/debug-Sun_Dec_24_09_10_16_2023.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Scott902 did you enable erg mode in zwift? i don't see any power requests from zwift
did you also enable the resistance tile in the pair screen of zwift?

**Comment by Scott902** [comment]
I enabled the toggle in bike settings. I toggled it off and on in the companion app during this test. Was no change. When I toggled it off in QZ settings my watts would come up to normal.

**Comment by cagnulein** [comment]
no i mean in zwift. also zwift has the same setting that must be enabled
for erg mode. for sure the one in qz must be enabled for workouts

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:35 Scott902 ***@***.***> ha
scritto:

**Comment by Scott902** [comment]
I did the one in qz. I also did the one in the Zwift companion app. I also tried toggling in the menu in Zwift

**Comment by cagnulein** [comment]
for what i saw in the log zwift is not sending it, so it seems that zwift
was misconfigured. are you sure you were doing a workout in zwift and not a
free ride or race?
sorry for stupid questions but since Im seeing a strange thing on your log,
i have to think to all the possibilities

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:39 Scott902 ***@***.***> ha
scritto:

**Comment by Scott902** [comment]
No worries worth the questions. I was doing a ftp test today but the last few tries been a workout. I don’t usually see erg mode in the Zwift menu if I’m not doing a race or workout.

**Comment by cagnulein** [comment]
maybe it worth to collect another debug log to be sure that erg mode was
enabled on zwift? or you are already sure it is in the debug log above?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 18:46 Scott902 ***@***.***> ha
scritto:

**Comment by Scott902** [comment]
I’ll try and get another over the next few days 👍

**Comment by cagnulein** [comment]
also you can disable the ios peloton workaround just to have more log (after this enable it back because with this disabled you will have crashes)

otherwise you can try to use the wahoo kickr device instead of bluetooth to collect more logs

let me know 

have a nice christmas!

**Comment by cagnulein** [comment]
@Scott902 any news?

**Comment by Scott902** [comment]
Sorry, I tried it once more and it seemed to be working, but that was after
a long ride. I'll give it a try tonight again and see what happens.

Scott
