### ISSUE TITLE
Req: HR Zones

### ISSUE THREAD

**Issue by d-nx** [cagnulein/qdomyos-zwift#191]
It would be great to see your HR zone as part of the HR tile. 
Maybe a small text under the BPM number, a small "Z1, Z2, Z3, Z4, Z5"

Z1= Blue
Z2= Green
Z3= Yellow
Z4= Orange
Z5= Red

Below is a description of how Garmin calculates the zones:

> **(https://www.garmin.com/en-US/blog/general/get-zone-train-using-heart-rate/)**
> 
> Zone 1 is 60-70% of threshold heart rate (the 220 minus your age).  This is a very light intensity effort.  Think nice walking pace where you can carry on a conversation.
> 
> Zone 2 is 70-80% of threshold heart rate.  Think of this as a warm-up or cool-down run.  Easy conversation pace as well.
> 
> Zone 3 is 80-90% of threshold heart rate.  This is a long run type of effort.  Breathing a bit harder here but I would say comfortable.
> 
> Zone 4 is 90-100% of threshold heart rate.  Harder intensity effort.  You can reply in single word responses.  Tempo type of run.  Raising lactate threshold levels.
> 
> Zone 5 is 100-110% of threshold heart rate. Think of sprinting to the finish line.  Cannot hold a conversation.

**Comment by cagnulein** [comment]
Yeah absolutely!

Il dom 7 mar 2021, 07:49 d-nx <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
Of course this requires a new parameter: the age ;)

Il dom 7 mar 2021, 07:51 cagnulein <cagnulein@gmail.com> ha scritto:

**Comment by cagnulein** [comment]
Done!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 mar 2021 alle ore 11:04 cagnulein <cagnulein@gmail.com> ha
scritto:
