### ISSUE TITLE
[BUG] Wahoo Dircon characteristics incompatibilities

### ISSUE THREAD

**Issue by kvj** [cagnulein/qdomyos-zwift#1910]
**Describe the bug**
I'm using `Wahoo TREAD 0003` Virtual Wahoo device and I've found few incompatibilities. Not sure were them added purposely, or it's implementation flaw:

1. Characteristic `0x2acc`: the control flag, both `speed` and `incline` aren't reported as controllable features, when treadmill being used (but QZ UI gives me that control). For the read flag, `incline` is being reported (speed is always available).
2. Characteristic `0x2ad3`: now it's `READ` only, but in BLE it's READ, NOTIFY. Without NOTIFY support, it's impossible to know whether devices is moving or not (START/PAUSE) state. Real FTMS device correctly reports it's status via this chr.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 13
 - Version Latest stable

**Comment by cagnulein** [comment]
are you able to do a PR for this?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 dic 2023 alle 20:11 Konstantin ***@***.***>
ha scritto:

**Comment by kvj** [comment]
Not sure, maybe later. This [code](https://github.com/cagnulein/qdomyos-zwift/blob/4f7cfbbfc17a3940e2dd1d80d3760c83ef3d91c6/src/dirconmanager.cpp#L11) scares me :smile: 

It's not a blocker for me right now, I'll get back to it later

**Comment by cagnulein** [comment]
hahaha ok i can do this but in some days.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 dic 2023 alle 10:53 Konstantin ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@kvj I did the 1., for the 2. actually the value of that charateristic is static, so if you need it, i need to handle the value on it. Anyway you can basically check the speed to understand if it's in pause/stop or it's moving

**Comment by kvj** [comment]
@cagnulein 

Battle-tested for a couple of days: https://github.com/kvj/hass_Wahoo_Dircon

![Screenshot from 2023-12-27 13-03-59](https://github.com/cagnulein/qdomyos-zwift/assets/159124/3e34c141-17a2-4250-81bf-a1a35cd9976d)

![Screenshot_2023-12-27-09-42-25-61_c3a231c25ed346e59462e84656a70e50](https://github.com/cagnulein/qdomyos-zwift/assets/159124/18ecefc5-bea8-4a31-97de-e9d50f205d17)

**Comment by cagnulein** [comment]
wow that's amazing! Can you share it on the QZ facebook group?
