### ISSUE TITLE
[BUG] Can't see NordicTrack 1750C (from 2020) on QZ

### ISSUE THREAD

**Issue by alwant** [cagnulein/qdomyos-zwift#1911]
**Describe the bug**

I've tried all steps on the guide. From a windows machine installed the companion app, it all worked fine. I can access the companion app from the UI, it's set to 1750C.

The QZ app on my phone is set according to the guide, and I can ping the IP address from the phone (I installed a ping app).

Yet, none of the metrics appear on the QZ app when I start a manual workout.

Here's a video of the entire setup: https://photos.app.goo.gl/BUa3weA4BGywCkAt6

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - OS: Android 14

**Append a debug log**

[debug-Sun_Dec_24_17_06_06_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13762938/debug-Sun_Dec_24_17_06_06_2023.log)
  
  
**Additional context**

QZ often (but not always) shows a connection to a smartdevice (Google Nest Hub Max) without me having ever instructed to connect to it.

**Comment by cagnulein** [comment]
@alwant do a factory reset and don't update the ifit app then. ifit blocked qz from the new updates.
let me know

**Comment by alwant** [comment]
It updates itself when it restarts and it's connected over WiFi. Is there a way to prevent it?

**Comment by cagnulein** [comment]
yes on my pro-form device i disable internet access on the router.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 dic 2023 alle 13:24 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
Ah, great idea. I have a Google WiFi pro mesh network, I think I can use the kids lock functionalities to prevent a MAC address from connecting. I suspect it will also block connections to the phone running QZ, but worth trying. 

My long term plan is to run a raspberry pi anyway, as long as it works, I can use an Ethernet switch between the rpi and the treadmill so that the router can block Internet connectivity but not inter device connections.

Will try and report back. And merry Christmas!! ☃️🎅 (Greetings from New York, although I'm originally from near you, Carpi MO)

**Comment by cagnulein** [comment]
wow sono di Carpi anche io!
Let me know!

**Comment by cagnulein** [comment]
you can also block the ifit domain

**Comment by alwant** [comment]
Bad news. The Google WiFi firmware only allows to block a device from connecting to the network altogether, including local LAN devices, and it doesn't allow to block access to single websites either. I'm going to try another route: trying to boot without WiFi, get privileged mode and manually configure WiFi by hard coding an IP address without a default gateway. That should block all connections outside the LAN.

**Comment by alwant** [comment]
Aaaaaaand, we're in business! Went back to a factory reset, skipped WiFi & iFit login screens and enabled privileged mode (the latest firmware does not require the code anymore, apparently). Then I went back to the settings, and configured the WiFi network opting for "Advanced settings" and switching from DHCP to a fixed IP address. I still left a 24 netmask so that it can connect to other devices on the local network, but configured the default gateway to the wrong IP (which is not in use).

Now the QZ app on my phone receives realtime data from the treadmill. Works amazingly well! @cagnulein you're a super⭐

The only apparent downside of this configuration is that the iFit loading time is quite long, with a spinning wheel on the screen. But it's a big deal.

Somehow the peloton app (on the same device) is not picking up the metrics but that's a different problem, so I'll close this thread here. Thanks again for the support!

**Comment by cagnulein** [comment]
Awesome, thanks for the update!


Il giorno lun 25 dic 2023 alle 18:03 alwant ***@***.***> ha
scritto:
