### ISSUE TITLE
Rower Distance is Not Included in Strava

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#1912]
I reached out to Strava about why my rowing workouts were not including distance on the workouts. Their email response, "Thanks for writing in. I've taken a look at those activity files and it looks like qdomyos-zwift is not including distance data with their uploads. We suggest reaching out to the company directly for any questions."

I've attached a file from December 18th when the distance was showing up in Strava vs December 25th. 

[debug-Mon_Dec_18_06_54_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13768636/debug-Mon_Dec_18_06_54_54_2023.log)

[debug-Mon_Dec_25_12_21_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13768638/debug-Mon_Dec_25_12_21_19_2023.log)

[Fit Files.zip](https://github.com/cagnulein/qdomyos-zwift/files/13768640/Fit.Files.zip)

**Comment by cagnulein** [comment]
ah! they were right, sorry for the issue. It was due to some modifications that I did for this https://github.com/cagnulein/qdomyos-zwift/discussions/1838 following @yellowbarchetta :) fixed now. I'm pushing to google play, it will require some days to Google to review it.

**Comment by PugMamma** [comment]
Yes, the issue is fixed. Thanks again.
