### ISSUE TITLE
[BUG] QZ running on rpi is not detected by Peleton app running on Android phone

### ISSUE THREAD

**Issue by alwant** [cagnulein/qdomyos-zwift#1913]
**Describe the bug**
I have two instances of QZ running separately on an android phone, and on a raspberry pi. Both read metrics from a Nordictrak 1750 commercial treadmill running the Nordictrack companion app.

Only QZ running on the android phone is detected by the Peloton app on a different phone.

Here's a few screenshots of "nRF Connect" for the two devices

Here's how the rpi shows up
![rpi - profile](https://github.com/cagnulein/qdomyos-zwift/assets/427717/11143bdf-19e7-4c1d-bbef-9bd1c293211d)
![rpi details](https://github.com/cagnulein/qdomyos-zwift/assets/427717/a584f5f3-5eb6-4bdd-ae9e-7b76ac5542a9)

And this is the pixel phone
![Pixel 8 pro - profile](https://github.com/cagnulein/qdomyos-zwift/assets/427717/78a0bcde-e066-4cd0-ac4f-0c69890aaefd)
![Pixel 8 Pro details](https://github.com/cagnulein/qdomyos-zwift/assets/427717/1187ae7e-f30b-42eb-9b2e-17c502d46886)

And this is what is detected by the Peloton app
![Peloton app - connection page](https://github.com/cagnulein/qdomyos-zwift/assets/427717/8b5880ec-8e90-418a-8b70-665a7574ba30)

**Comment by alwant** [comment]
By the way under "treadmill data" I can see correct and changing values of incline and speed, so the rpi is streaming the right metrics over bluetooth. It's just not picked up by the Peloton app.

**Comment by cagnulein** [comment]
maybe it's only a name issue on the peloton app? or maybe it's not about metrics, it's about the device name characteristics

**Comment by cagnulein** [comment]
i mean the 1800 and 1801 characteristics. raspberry doesn't have and phone does, right? i guess that's the issue

**Comment by alwant** [comment]
oh, interesting. From a cursory search, it appears that generic services 0x1800 and 1801 are mandatory for BT compliance: https://devzone.nordicsemi.com/guides/short-range-guides/b/bluetooth-low-energy/posts/ble-services-a-beginners-tutorial

**Comment by cagnulein** [comment]
yeah but not for zwift or any other apps :) anyway it's very easy to add them, i will create a branch for you in the next days

**Comment by alwant** [comment]
I don't know if it's helpful, but I have a Garmin EPIX 2, and it's supposed to emit FTMS when using the "Virtual race" activity broadcasting HR and speed and cadence (if you have a HRM strap or a running dynamics pod, which I do). Somehow the Peloton app also doesn't detect it.

Now that I know where to look, I explored the BT profile and I can see it's broadcasting the 1800 and 1801 generic services along with other stuff. This makes me think that there's something else going on with the Peloton app (could they be filtering based on the name to limit "competitors" like Garmin from connecting with their stuff?).

I'm posting a screenshot here of the watch profile in case it's useful and you spot something interesting. And TYSM for looking into this!

### EPIX 2 Garmin watch profile for Virtual Run

![image](https://github.com/cagnulein/qdomyos-zwift/assets/427717/bbd3ad7b-5dc4-42b1-a591-d6a9bd2f21f6)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/427717/02f715f1-c039-4276-9026-21acfb1ba56b)

### Pixel 8 Pro generic profiles values (for reference)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/427717/fa84aae6-9ac2-41b2-ba11-198a6ee39f6a)

**Comment by cagnulein** [comment]
thanks , no i don't think peloton is so smart :) i guess they are maybe
just checking something in the name or something.

anyway we will find out

do you have also a pc or a mac to test qz on it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 dic 2023 alle 22:23 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
I have a windows box (and linux on ChromeOS)

**Comment by cagnulein** [comment]
ok so give it a try to the windows build
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7328217767/artifacts/1134946528

it's a 15 minutes trial that you can restart as many as you want

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 dic 2023 alle 22:27 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
you're on to something here... the windows version shows up right away without any issues. It's something to do with the rpi

**Comment by cagnulein** [comment]
ok so for sure they are the generic services :)


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 dic 2023 alle 22:48 alwant ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@alwant I created a new PR for you https://github.com/cagnulein/qdomyos-zwift/pull/1915
Pull it, build it and give it a try. I didn't test it myself because I don't have access to a raspberry ATM

**Comment by alwant** [comment]
I'll be honest. I don't know how gitgub works. So I asked chatgpt and it told me to run "git fetch origin" after which I discovered there's a branch called peloton_raspberry_treadmill. I then did _git checkout peloton_raspberry_treadmill_ and _git pull origin peloton_raspberry_treadmill_

Let me know if I'm completely off track

**Comment by cagnulein** [comment]
yes that's right, then build it :)
I'm going to bed soon :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 21:13 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
I wasn't able to get a new binary. This is what I got (after a long time recompiling)

```
g++ -Wl,-O1 -s -pipe -fno-sized-deallocation -O3 -std=gnu++1z -flto=4 -fno-fat-lto-objects -fuse-linker-plugin -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu -fPIC -o qdomyos-zwift androidactivityresultreceiver.o androidadblog.o apexbike.o pelotonbike.o wahookickrheadwind.o ziprotreadmill.o Computrainer.o PathController.o characteristicnotifier2a53.o characteristicnotifier2a5b.o characteristicnotifier2acc.o characteristicnotifier2acd.o characteristicnotifier2ad9.o characteristicwriteprocessor.o characteristicwriteprocessore005.o computrainerbike.o fakeelliptical.o faketreadmill.o lifefitnesstreadmill.o mepanelbike.o nautilusbike.o nordictrackelliptical.o nordictrackifitadbbike.o nordictrackifitadbtreadmill.o octaneelliptical.o octanetreadmill.o proformellipticaltrainer.o proformrower.o proformwifibike.o proformwifitreadmill.o abstractserver.o bitmap.o browser.o cache.o dns.o hostname.o mdns.o message.o prober.o provider.o query.o record.o resolver.o server.o service.o activiotreadmill.o bhfitnesselliptical.o bike.o bluetooth.o bluetoothdevice.o characteristicnotifier2a37.o characteristicnotifier2a63.o characteristicnotifier2ad2.o characteristicwriteprocessor2ad9.o bowflext216treadmill.o bowflextreadmill.o chronobike.o concept2skierg.o cscbike.o dirconmanager.o dirconpacket.o dirconprocessor.o domyoselliptical.o domyosrower.o domyostreadmill.o echelonconnectsport.o echelonrower.o echelonstride.o eliterizer.o elitesterzosmart.o elliptical.o eslinkertreadmill.o fakebike.o filedownloader.o fitmetria_fanfit.o fitplusbike.o fitshowtreadmill.o fit.o fit_accumulated_field.o fit_accumulator.o fit_buffer_encode.o fit_buffered_mesg_broadcaster.o fit_buffered_record_mesg_broadcaster.o fit_crc.o fit_date_time.o fit_decode.o fit_developer_field.o fit_developer_field_definition.o fit_developer_field_description.o fit_encode.o fit_factory.o fit_field.o fit_field_base.o fit_field_definition.o fit_mesg.o fit_mesg_broadcaster.o fit_mesg_definition.o fit_mesg_with_event_broadcaster.o fit_profile.o fit_protocol_validator.o fit_unicode.o flywheelbike.o ftmsbike.o ftmsrower.o gpx.o heartratebelt.o homefitnessbuddy.o homeform.o horizongr7bike.o horizontreadmill.o iconceptbike.o inspirebike.o keepawakehelper.o keepbike.o kingsmithr1protreadmill.o kingsmithr2treadmill.o main.o mcfbike.o metric.o nautiluselliptical.o nautilustreadmill.o npecablebike.o pafersbike.o paferstreadmill.o peloton.o powerzonepack.o proformbike.o proformelliptical.o proformtreadmill.o qfit.o qzsettings.o renphobike.o rower.o schwinnic4bike.o screencapture.o sessionline.o shuaa5treadmill.o signalhandler.o simplecrypt.o skandikawiribike.o smartrowrower.o smartspin2k.o emailaddress.o mimeattachment.o mimecontentformatter.o mimefile.o mimehtml.o mimeinlinefile.o mimemessage.o mimemultipart.o mimepart.o mimetext.o quotedprintable.o smtpclient.o snodebike.o solebike.o soleelliptical.o solef80treadmill.o spirittreadmill.o sportsplusbike.o sportstechbike.o strydrunpowersensor.o tacxneo2.o tcpclientinfosender.o technogymmyruntreadmill.o technogymmyruntreadmillrfcomm.o templateinfosender.o templateinfosenderbuilder.o stagesbike.o toorxtreadmill.o treadmill.o truetreadmill.o trxappgateusbbike.o ultrasportbike.o virtualrower.o wahookickrsnapbike.o yesoulbike.o trainprogram.o trxappgateusbtreadmill.o virtualbike.o virtualtreadmill.o m3ibike.o domyosbike.o scanrecordresult.o zwiftworkout.o mainwindow.o charts.o inappproductqmltype.o inappstoreqmltype.o inappproduct.o inapppurchasebackend.o inappstore.o inapptransaction.o qdomyos-zwift_qmltyperegistrations.o qrc_icons.o qrc_qml.o moc_androidadblog.o moc_apexbike.o moc_pelotonbike.o moc_wahookickrheadwind.o moc_ziprotreadmill.o moc_characteristicwriteprocessore005.o moc_computrainerbike.o moc_fakeelliptical.o moc_faketreadmill.o moc_lifefitnesstreadmill.o moc_mepanelbike.o moc_nautilusbike.o moc_nordictrackelliptical.o moc_nordictrackifitadbbike.o moc_nordictrackifitadbtreadmill.o moc_octaneelliptical.o moc_octanetreadmill.o moc_proformellipticaltrainer.o moc_proformrower.o moc_proformwifibike.o moc_proformwifitreadmill.o moc_abstractserver.o moc_browser.o moc_cache.o moc_hostname.o moc_prober.o moc_provider.o moc_resolver.o moc_server.o moc_browser_p.o moc_cache_p.o moc_hostname_p.o moc_prober_p.o moc_provider_p.o moc_resolver_p.o moc_server_p.o moc_activiotreadmill.o moc_bhfitnesselliptical.o moc_bike.o moc_bluetooth.o moc_bluetoothdevice.o moc_characteristicnotifier.o moc_characteristicwriteprocessor.o moc_characteristicwriteprocessor2ad9.o moc_bowflext216treadmill.o moc_bowflextreadmill.o moc_chronobike.o moc_concept2skierg.o moc_cscbike.o moc_dirconmanager.o moc_dirconprocessor.o moc_domyoselliptical.o moc_domyosrower.o moc_domyostreadmill.o moc_echelonconnectsport.o moc_echelonrower.o moc_echelonstride.o moc_eliterizer.o moc_elitesterzosmart.o moc_elliptical.o moc_eslinkertreadmill.o moc_fakebike.o moc_filedownloader.o moc_fitmetria_fanfit.o moc_fitplusbike.o moc_ftmsrower.o moc_homefitnessbuddy.o moc_horizongr7bike.o moc_iconceptbike.o moc_keepbike.o moc_kingsmithr1protreadmill.o moc_kingsmithr2treadmill.o moc_m3ibike.o moc_fitshowtreadmill.o moc_flywheelbike.o moc_ftmsbike.o moc_heartratebelt.o moc_homeform.o moc_horizontreadmill.o moc_inspirebike.o moc_material.o moc_mcfbike.o moc_nautiluselliptical.o moc_nautilustreadmill.o moc_npecablebike.o moc_pafersbike.o moc_paferstreadmill.o moc_peloton.o moc_powerzonepack.o moc_proformbike.o moc_proformelliptical.o moc_proformtreadmill.o moc_qfit.o moc_renphobike.o moc_rower.o moc_schwinnic4bike.o moc_screencapture.o moc_shuaa5treadmill.o moc_skandikawiribike.o moc_smartrowrower.o moc_smartspin2k.o moc_emailaddress.o moc_mimeattachment.o moc_mimecontentformatter.o moc_mimefile.o moc_mimehtml.o moc_mimemultipart.o moc_mimepart.o moc_quotedprintable.o moc_smtpclient.o moc_snodebike.o moc_solebike.o moc_soleelliptical.o moc_solef80treadmill.o moc_spirittreadmill.o moc_sportsplusbike.o moc_sportstechbike.o moc_strydrunpowersensor.o moc_tacxneo2.o moc_tcpclientinfosender.o moc_technogymmyruntreadmill.o moc_technogymmyruntreadmillrfcomm.o moc_templateinfosender.o moc_templateinfosenderbuilder.o moc_stagesbike.o moc_toorxtreadmill.o moc_gpx.o moc_treadmill.o moc_mainwindow.o moc_trainprogram.o moc_truetreadmill.o moc_trxappgateusbbike.o moc_trxappgateusbtreadmill.o moc_ultrasportbike.o moc_virtualbike.o moc_virtualrower.o moc_virtualtreadmill.o moc_domyosbike.o moc_wahookickrsnapbike.o moc_wobjectdefs.o moc_yesoulbike.o moc_charts.o moc_inappproductqmltype.o moc_inappstoreqmltype.o moc_inappproduct.o moc_inapppurchasebackend.o moc_inappstore.o moc_inapptransaction.o   /usr/lib/aarch64-linux-gnu/libQt5Charts.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Location.so /usr/lib/aarch64-linux-gnu/libQt5PositioningQuick.so /usr/lib/aarch64-linux-gnu/libQt5QuickControls2.so /usr/lib/aarch64-linux-gnu/libQt5Quick.so /usr/lib/aarch64-linux-gnu/libQt5Multimedia.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5Bluetooth.so /usr/lib/aarch64-linux-gnu/libQt5Xml.so /usr/lib/aarch64-linux-gnu/libQt5Positioning.so /usr/lib/aarch64-linux-gnu/libQt5QmlModels.so /usr/lib/aarch64-linux-gnu/libQt5Qml.so /usr/lib/aarch64-linux-gnu/libQt5NetworkAuth.so /usr/lib/aarch64-linux-gnu/libQt5WebSockets.so /usr/lib/aarch64-linux-gnu/libQt5Network.so /usr/lib/aarch64-linux-gnu/libQt5TextToSpeech.so /usr/lib/aarch64-linux-gnu/libQt5Core.so -lGL -lpthread   
/usr/bin/ld: /tmp/cc72ryYV.ltrans9.ltrans.o: in function `QMdnsEngine::ProviderPrivate::onMessageReceived(QMdnsEngine::Message const&)':
<artificial>:(.text+0x762c): undefined reference to `localipaddress::getIP(QHostAddress const&)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1508: qdomyos-zwift] Error 1
```

**Comment by cagnulein** [comment]
try a make clean and then make again

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 21:48 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
make clean made ended things a little earlier

```
g++ -c -pipe -fno-sized-deallocation -O3 -std=gnu++1z -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DIO_UNDER_QT -DSMTP_BUILD -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_LOCATION_LIB -DQT_POSITIONINGQUICK_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_XML_LIB -DQT_POSITIONING_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORKAUTH_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_TEXTTOSPEECH_LIB -DQT_CORE_LIB -I. -Iqmdnsengine/src/include -Iqmdnsengine/src/include -Ifit-sdk -Ipurchasing/qmltypes -Ipurchasing/inapp -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtLocation -I/usr/include/aarch64-linux-gnu/qt5/QtPositioningQuick -I/usr/include/aarch64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/aarch64-linux-gnu/qt5/QtQuick -I/usr/include/aarch64-linux-gnu/qt5/QtMultimedia -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtBluetooth -I/usr/include/aarch64-linux-gnu/qt5/QtXml -I/usr/include/aarch64-linux-gnu/qt5/QtPositioning -I/usr/include/aarch64-linux-gnu/qt5/QtQmlModels -I/usr/include/aarch64-linux-gnu/qt5/QtQml -I/usr/include/aarch64-linux-gnu/qt5/QtNetworkAuth -I/usr/include/aarch64-linux-gnu/qt5/QtWebSockets -I/usr/include/aarch64-linux-gnu/qt5/QtNetwork -I/usr/include/aarch64-linux-gnu/qt5/QtTextToSpeech -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -o provider.o qmdnsengine/src/src/provider.cpp
qmdnsengine/src/src/provider.cpp:36:10: fatal error: localipaddress.h: No such file or directory
   36 | #include "localipaddress.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12990: provider.o] Error 1
```

**Comment by cagnulein** [comment]
ok pull it again, i aligned with the master
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle ore 22:08 alwant ***@***.***>
ha scritto:

**Comment by alwant** [comment]
And, we're in business! 😄 

Works perfectly. I'll try to squeeze a workout later on today, but it shows up as an FTMS treadmill on the Peloton app, and I was able to connect to it just fine!

QQ - is there a way to rename the beacon to something else, like "qz-rpi" ?

**Comment by cagnulein** [comment]
amazing! for the name, yes but i love that name because it was one of the first line of the project :)

**Comment by cagnulein** [comment]
let me know if i can merge the code if it's working good!

**Comment by alwant** [comment]
I learned something else: because the daemon runs as a service as root, some of the files in my home directory had changed ownership/permission. Recompiling the source code kept failing because of that reason (but the error message was non-descriptive), as my username couldn't overwrite files.

I had to delete the directory altogether, and it worked when I started from scratch.

**Comment by alwant** [comment]
> let me know if i can merge the code if it's working good!

Will try tonight and let you know!

**Comment by cagnulein** [comment]
> QQ - is there a way to rename the beacon to something else, like "qz-rpi" ?

hah you mean the pixel 6? yes for sure! I was thinking about the DomyosBR :)

**Comment by alwant** [comment]
Confirmed, I was able to do an entire workout on the rpi beacon, and this time it also recorded the distance! Amazing, the issue is now resolved, you can merge this back into the main branch

**Comment by cagnulein** [comment]
perfect! i will try to do this tomorrow!

**Comment by cagnulein** [comment]
@alwant could you please pull it and build it again? I cleaned the code and i renamed the qz device.
Let me know!

**Comment by alwant** [comment]
I am not able to see it now. I see two devices with name "N/A" on nRF Connect, I wonder if it's one of those. But the peloton app can't see it now

**Comment by cagnulein** [comment]
can you share a debug log? i didn't change anything beside the name. maybe
that's it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 17:32 alwant ***@***.***> ha
scritto:

**Comment by alwant** [comment]
from nRF connect? Or where else?

**Comment by cagnulein** [comment]
enable the debug log from qz on the raspberry and upload the debug log created on the same folder

**Comment by alwant** [comment]
gotcha. I captured standard output and input here via
   `sudo /home/alberto/qdomyos-zwift/src/qdomyos-zwift -no-gui  -heart-service >& debug.log`
[debug.log](https://github.com/cagnulein/qdomyos-zwift/files/13850630/debug.log)

**Comment by alwant** [comment]
But only now I noticed that a debug file is created individually at every run 😄 

Here's the other one, they're probably the same

[debug-Sat_Jan_6_12_48_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13850636/debug-Sat_Jan_6_12_48_34_2024.log)

**Comment by cagnulein** [comment]
mmm i don't see anything strange in the debug log, did you still have the previous binary? is it still working? i can try to revert just the name modification to check that's the issue

**Comment by alwant** [comment]
I don't have the previous one anymore. But my phone also showed a weird
notification about a device with "no name" via Bluetooth. I wonder if it's
that one

**Comment by cagnulein** [comment]
i don't know anyway you can get the previous commit and build that one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 20:42 alwant ***@***.***> ha
scritto:

> I don't have the previous one anymore. But my phone also showed a weird
> notification about a device with "no name" via Bluetooth. I wonder if it's
> that one
>

**Comment by alwant** [comment]
I reverted back to 4ba070e0896b79646b4cc2c135de78e23cfad7b4 and things work as expected (see screenshot). Not sure why.

![Screenshot_20240106-175753](https://github.com/cagnulein/qdomyos-zwift/assets/427717/25d958b6-3f1a-488c-a621-b3db58b5acbb)

**Comment by cagnulein** [comment]
That’s strange I will try to on my end, maybe it doesn’t like the new name,
I will let you know! Thanks for your help

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 00:01 alwant ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I reverted the name modification and added a new debug log. Could you try to pull it again? You can save the binary of the working build in order to swap it quickly for the tests. Thanks!

**Comment by alwant** [comment]
Ok, this is weird. I tried running the newly compiled binary. Turned on the treadmill (in this sequence), then opened the peloton app. The peloton app could see the Bluetooth treadmill via QZ. However, I couldn't see any treadmill data in the app.

I thought that it was probably because I started the treadmill after the deamon.

So I killed the deamon, and the peloton app dropped the treadmill as the BT beacon wasn't there anymore

I restarted qz but at that point it wasn't visible by the Peloton app anymore despite repeated attempts.

Here are the two debug sessions for the attempt described above

[debug-Mon_Jan_8_17_54_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13867010/debug-Mon_Jan_8_17_54_46_2024.log)
[debug-Mon_Jan_8_17_49_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13867011/debug-Mon_Jan_8_17_49_28_2024.log)

**Comment by cagnulein** [comment]
i can't see any difference in the code, that's crazy! did you check with nrfconnect with the new build if you can see the same? can you a new build vs old build with nrfconnect to compare them? i just renamed the variables in a cleaner way, that's it!

**Comment by cagnulein** [comment]
@alwant Any news?
