### ISSUE TITLE
Zwift Connection to Bh i.artic

### ISSUE THREAD

**Issue by Cwo11** [cagnulein/qdomyos-zwift#1917]
As descriped in my mail I connect the app to my bike and zwift also connects to the bike, but I do not get any values. As requested I attach the log-file.
[debug-Mi__Dez__27_08_43_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13776724/debug-Mi__Dez__27_08_43_27_2023.log)

**Comment by cagnulein** [comment]
thanks, can you try to disable the virtual bluetooth device setting in the
experimental settings and restart qz and check if the issue is the same?
change only this setting
Share again a debug log if the error persist
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 09:02 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
I added the new debug-file.

**Comment by cagnulein** [comment]
where @Cwo11 ? i see only the old one

**Comment by Cwo11** [comment]
The debug-file is too big to upload. Shall I use we-transfer?

**Comment by cagnulein** [comment]
you can zip and then upload the zip

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 20:19 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
Here it is.
[Uploading debug-Mi__Dez__27_08_43_27_2023 2.zip…]()

**Comment by cagnulein** [comment]
it seems that it doesn't talk at all, qz is sending requests but the bike
doesn't answer.
is this bike working with other apps? if so I can mimic their behavior
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 20:27 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
No, it is not working with other apps. When I use your app it is the first time the bike says, that it is connected what it did not do before. I can also choose the bike on zwift in the menu for the first time, but there are nit datas as you pointed out. I tried to use only your app without zwift, it connects to the bike, but there are no data.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 20:30 schrieb Roberto Viola ***@***.***>:﻿
it seems that it doesn't talk at all, qz is sending requests but the bike

doesn't answer.

is this bike working with other apps? if so I can mimic their behavior

Let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 27 dic 2023 alle 20:27 Cwo11 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
for example it doesn't work with kinomap?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 20:45 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
I never tried kinomap.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 20:46 schrieb Roberto Viola ***@***.***>:﻿
for example it doesn't work with kinomap?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 27 dic 2023 alle 20:45 Cwo11 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
try it. if it works we can mimic it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 20:49 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
I mailed to BH support and I got the answer, that the bike is not compatibel with zwift. I asked, if there is another app that works with the bike and they said no. In my manual there  is mentioned that this bike comes with smartbluetooth and works with i.concept. The BH website sais i.concept is for working with zwift or kinomap, so I thought it would match somehow.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 20:49 schrieb Zahnarztpraxis Wollny ***@***.***>:﻿I never tried kinomap.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 20:46 schrieb Roberto Viola ***@***.***>:﻿
for example it doesn't work with kinomap?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 27 dic 2023 alle 20:45 Cwo11 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
yes indeed qz is handling iconcept protocol. and so qz can send the metrics
to qz. we can try some workaround. do you have also a pc or an android
device?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 20:55 Cwo11 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
is your bike similar to this one? https://github.com/cagnulein/qdomyos-zwift/issues/486

**Comment by Cwo11** [comment]
I can use an windows laptop or my office computer tomorrow.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 20:58 schrieb Roberto Viola ***@***.***>:﻿
yes indeed qz is handling iconcept protocol. and so qz can send the metrics

to qz. we can try some workaround. do you have also a pc or an android

device?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 27 dic 2023 alle 20:55 Cwo11 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
ok i will think what i can do to test some different protocol, i will let
you know tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 dic 2023 alle 21:02 Cwo11 ***@***.***> ha
scritto:

**Comment by Cwo11** [comment]
It is https://www.fitness-superstore.co.uk/bh-fitness-i-artic-upright-cycle-with-bluetooth.html this one.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 21:02 schrieb Roberto Viola ***@***.***>:﻿
is your bike similar to this one? #486

**Comment by Cwo11** [comment]
Thank you very much for your effort. This is really kind of you. Have a good night.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 21:07 schrieb Roberto Viola ***@***.***>:﻿
ok i will think what i can do to test some different protocol, i will let

you know tomorrow



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 27 dic 2023 alle 21:02 Cwo11 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
in the meantime it will be good if you can try kinomap

**Comment by Cwo11** [comment]
I found out how to do an hardreset with my bike. After that your App and Kinomap worked fine. Zwift did not find any contact to the bike.Mit freundlichen Grüßen / with best regards Christian WollnyZahnarzt  ZahnarztpraxisDental DreamsInhaber Christian WollnyZahnarzt Edenskamp 126409 Wittmund Tel.:       +49 (0)4462/94 26 96Fax:       +49 (0)4462/94 26 93E-Mail:   ***@***.***:      www.zahnarztpraxis-wollny.de VERTRAULICHKEIT: Dieses e-mail und alle angehängten Dateien sind vertraulich und privilegiert. Sollten Sie nicht als namentlicher Empfänger aufgeführt sein, informieren Sie unverzüglich den Absender und machen Sie den Inhalt nicht für Dritte zugänglich, noch darf dieser gedruckt oderfür andere Zwecke verwendet, kopiert oder auf irgendeinem Medium gespeichert werden.CONFIDENTIALITY:This e-mail and any attachments are confidential and may be privileged. If you are not a named recipient, please notify the senderimmediately and do not store, copy or disclose the contents to any other person.Am 27.12.2023 um 21:10 schrieb Roberto Viola ***@***.***>:﻿
in the meantime it will be good if you can try kinomap

**Comment by cagnulein** [comment]
that's great! so now with qz open, open zwift on another device and you
will see your phone name or a wahoo virtual device there. don't you see it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 21:36 Cwo11 ***@***.***> ha
scritto:
