### ISSUE TITLE
ZWIFT API

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1921]
@victorypoint , @Ghilm1986 did a HUGE discovery!
Check this https://github.com/snicker/zwift_hass/blob/master/custom_components/zwift/sensor.py 
@ghilm1986 is using with home assistant and it's giving realtime data!! 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/709e2b89-ca79-4ffe-b1e2-b6e542ff8178)

I'm implementing it!

**Comment by cagnulein** [comment]
of course @victorypoint I already started, I should have some code to test today (if ChatGPT code is ok :D )

**Comment by victorypoint** [comment]
@cagnulein, this looks really interesting. What information are you obtaining?

**Comment by cagnulein** [comment]
theorically everything you see on the companion :)
I'm finalizing right now, i hope to have something for today/tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 16:37 Al Udell ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
<img width="1416" alt="Screenshot 2023-12-28 at 18 10 34" src="https://github.com/cagnulein/qdomyos-zwift/assets/48216/3f9f32cc-9b12-4fe4-9cbe-528cd97965e1">
unbeliavable all the stats are in clear! for all the users!

**Comment by cagnulein** [comment]
i can also log the X e Y coordinate in the fit file @victorypoint  !!!!!

**Comment by victorypoint** [comment]
@cagnulein this is wonderful news! Are you able to obtain zwift elevation from the topography like bikes do and use it instead of incline for runners?

**Comment by cagnulein** [comment]
yes using the delta from the odometer and elevation...Now i need to pause it, baby is calling :)

**Comment by victorypoint** [comment]
@cagnulein, test of ios testflight build. Speed and incline tiles work with NT C2950 TM. +- controls work fine. Note that speed increments in values of 1, incline in values of 0.5. QZ to Zwift works good (dircon). Zwift auto-inclination does not work. Have not tested incline portal or workout yet.

[debug-Sat_Dec_30_16_48_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13799175/debug-Sat_Dec_30_16_48_56_2023.log)

**Comment by victorypoint** [comment]
@cagnulein, I should confirm which multitasking mode to use? I'm using ipad pro with latest ipados, currently using 'stage manager' mode, not 'view/slide over' mode.

**Comment by cagnulein** [comment]
no wait you can't use zwift on the same device. qz on ipad and zwift on pc
for example

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 22:14 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i guess it could be the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 22:17 cagnulein ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
Oh, okay my mistake. Will retest with Zwift on PC

**Comment by cagnulein** [comment]
thanks my fault, i didn't mentioned :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 22:19 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, ok retested with zwift on pc. Got auto-inclination this time but seemed to be sent very much delayed or maybe the swipe cache was getting overloaded?

[Uploading debug-Sat_Dec_30_17_21_24_2023.log…]()

**Comment by cagnulein** [comment]
it could be. just check the target incline tile to see the reaction from
the zwift api. if they are real time it means that the cache is the issue.
in my test it has only 5 secs delay (to don't over call the api). is this
the delay?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 22:31 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, will check after dinner

**Comment by victorypoint** [comment]
@cagnulein, okay this is looking very promising! I did more auto-incline testing. A few things I noticed:
- I'm getting an incline delay of anywhere from 3-8 seconds. I confirmed this by manually changing incline and timing how long it would take to auto-incline change back.
- Zwift onscreen incline value was not always the incline that was auto-sent (usually 1% off) but most times they agreed.
- Auto-incline only applies to logged-in person no matter who you look at (OCR auto-incline worked for whoever you looked at) - this confused me at first 🤣

[debug-Sat_Dec_30_18_08_04_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13799318/debug-Sat_Dec_30_18_08_04_2023.log)

**Comment by cagnulein** [comment]
> @cagnulein, okay this is looking very promising! I did more auto-incline testing. A few things I noticed:
> 
> - I'm getting an incline delay of anywhere from 3-8 seconds. I confirmed this by manually changing incline and timing how long it would take to auto-incline change back.

yes it sounds right, i have a 5 seconds polling so this delay is sounds like reasonable. i will try to put it to 1 but i guess zwift should be worried about this. how often the zwift companion updates their metrics?

> 
> - Zwift onscreen incline value was not always the incline that was auto-sent (usually 1% off) but most times they agreed.

yes because zwift shows the average of the next 100m but it sends the actual value

> 
> - Auto-incline only applies to logged-in person no matter who you look at (OCR auto-incline worked for whoever you looked at) - this confused me at first 🤣

ahahah yep :P

thanks for the test!

**Comment by victorypoint** [comment]
@cagnulein, so the API ties in with Zwift Companion and gets metrics from there?

**Comment by cagnulein** [comment]
the api that i added are the same that the companion uses. so all the info
that the companion has we can also have too now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 23:40 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@cagnulein, let's reduce the polling interval to something very small and I'll give it a good test. Oh, and Happy New Year!!! 🥳🎉

**Comment by cagnulein** [comment]
@victorypoint happy new year! i saw the companion updates every 5 seconds so i guess it's more or less a load limitation on the zwift server. i don't want to flood them (i don't want to encounter TOS issues). 

let's see what the users will say :) maybe i will put a 3 seconds at max
