### ISSUE TITLE
[BUG] Can not connect to Treadmill NordicTrack 2950 and App QZ Fitness

### ISSUE THREAD

**Issue by qnorkad** [cagnulein/qdomyos-zwift#1922]
**Describe the bug**
I followed all the step from the blog and set usb debug on, enable privileges mode, add IP address and install App in treadmill 2950. I can ping the IP adress and working. I have bought install the app in IoS device and add IP address and follow the step to enable everything but unfortunately I can see treadmill data in the app.

**Desktop (please complete the following information):**
 - Treadmill 2950 Speed 22 max

**Smartphone (please complete the following information):**
 - Device: iPhone 15

**Append a debug log**

[debug-Thu_Dec_28_12_29_33_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13786127/debug-Thu_Dec_28_12_29_33_2023.log)

**Comment by cagnulein** [comment]
Hi! Qz companion is doing its job but the ifit app removed the access to
the metrics.
do this, do a factory reset and then DON'T update the ifit app anymore.
install the companion and it should work.
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 12:46 qnorkad ***@***.***> ha
scritto:

**Comment by qnorkad** [comment]
Hi,Thanks for replying. I did a factory reset this morning before providing you the logs and still see the issue. (I did not update ifit at all).Cheers,NordoneOn 28 Dec 2023, at 12:50, Roberto Viola ***@***.***> wrote:﻿
Hi! Qz companion is doing its job but the ifit app removed the access to

the metrics.

do this, do a factory reset and then DON'T update the ifit app anymore.

install the companion and it should work.

Let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 28 dic 2023 alle 12:46 qnorkad ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
try to set the device on the companion to c1750 and reboot the treadmill so

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 14:17 qnorkad ***@***.***> ha
scritto:

**Comment by qnorkad** [comment]
Perfect. Thanks it’s working !One question, can we run QZ App in same device as Zwift … i tried but not working. I put zwift on another device, and it’s working …Cheers,NordineOn 28 Dec 2023, at 14:35, Roberto Viola ***@***.***> wrote:﻿
try to set the device on the companion to c1750 and reboot the treadmill so



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 28 dic 2023 alle 14:17 qnorkad ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
@qnorkad great! you can do one device only, on every platform but not on ios. on android you need to enable the android notification icon setting in the experimental settings!
