### ISSUE TITLE
[BUG] no resistance domyos 520 elliptical block 1

### ISSUE THREAD

**Issue by toto811** [cagnulein/qdomyos-zwift#1925]
the resistance does not work in gpx mode domyos 520 elliptical
[debug-Thu_Dec_28_22_56_31_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13789832/debug-Thu_Dec_28_22_56_31_2023.1.log)
](url)

**Comment by cagnulein** [comment]
you need to disable the domyos_elliptical_inclination setting
that's why

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 23:19 toto811 ***@***.***>
ha scritto:

**Comment by toto811** [comment]
[debug-Fri_Dec_29_10_59_00_2023[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13792504/debug-Fri_Dec_29_10_59_00_2023.1.log)

**Comment by cagnulein** [comment]
fixed!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7355928851
you will see the apk in the bottom of the page when it's done (30 minutes)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 dic 2023 alle ore 11:06 toto811 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7356002908

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/7356112712

**Comment by cagnulein** [comment]
@toto811 did you try it?
