### ISSUE TITLE
No Heart Rate nor distance showing in tiles on QZ 

### ISSUE THREAD

**Issue by Mariemartin** [cagnulein/qdomyos-zwift#1928]
**Describe the bug**
As discussed, BPM is showing on Apple Watch but no distance. On the tiles of the iPhone, no BPM nor distance.

Marie-Claude Turbide
[debug-ven__déc__29_14_41_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13795860/debug-ven__dec__29_14_41_44_2023.log)
[debug-ven__déc__29_14_41_44_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13795863/debug-ven__dec__29_14_41_44_2023.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
found the issue! i'm sending you a fix! let me know if it's better!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 dic 2023 alle ore 21:19 Mariemartin <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@Mariemartin are we ok with this?
