### ISSUE TITLE
JTX Sprint 5 auto incline not working [BUG]

### ISSUE THREAD

**Issue by Kalmosawi** [cagnulein/qdomyos-zwift#1929]
[debug-Sat_Dec_30_10_42_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13797857/debug-Sat_Dec_30_10_42_15_2023.log)
Auto incline not working. Seems to work with qz app intermittently

**To Reproduce**
Connect to qz app

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device⁹
[debug-Sat_Dec_30_10_42_15_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13797854/debug-Sat_Dec_30_10_42_15_2023.log)
: [e.g. iPhone6]

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @Kalmosawi for what I saw the incline is working with a delay as you told me but QZ is doing the right thing. Is this delay also on Kinomap?
Also for the speed, in my code I don't have a code to change speed from the app directly. Does Kinomap? if so follow this with kinomap and I will mimic the kinomap behaviour https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by cagnulein** [comment]
@Kalmosawi any news?
