### ISSUE TITLE
Unable to connect Tunturi T60[BUG]

### ISSUE THREAD

**Issue by lilalamballer** [cagnulein/qdomyos-zwift#1932]
**Describe the bug**
I have a brand new Tunturi T60 2022 model which i do not know if it is fully supported. I am able to see people having the 2019 model working but my model is not connecting, I do not know if there are major differences between the 2019 and 2022 model.
I downloaded the QZ app on my iphone and android tablet but both show the following behaviour.
I open the app and it is telling me it is able to find my treadmill Tunturi T60 but won't show any tiles.
On both the android and ios device I have manually set the app to connect to the Tunturi in the advanced settings but this is not solving the problem. Also i have enabled debug logging for both devices but I am only able to find the log on my ios device. On the android nothing is showing up in any folder.

**To Reproduce**
1. Turning on my Tunturi T60 treadmill 
2. Opening the QZ app  ( tried on both ios 17.1.2 and android 12 )
3. Tiles are not showing up even when the app is telling me the tunturi t60 is found
4. Manually setting the app to connect to the tunturi t60 is not working.

![1A81D7A4-5E21-4689-B29B-3135F0FA8E60](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/19390e1d-8678-4c41-8492-0077e80766d9)

[debug-za_dec_30_23_23_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13801210/debug-za_dec_30_23_23_10_2023.log)

**Comment by cagnulein** [comment]
@lilalamballer hi, can you install the free app nrfconnect and show me a screenshot of it in this app?

**Comment by lilalamballer** [comment]
Thanks for the quick response! 
These are some screenshots from the mentioned app. I don't know exactly what you need to know so i made a few.
![090C93BF-F631-49E6-9858-ACCF18E60D59 3](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/c9b45dd3-c950-4701-bfd7-d6d7e2ac867b)
![03269A4C-5F50-4020-A610-BE01A3C61106 3](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/86dd3f8e-9e09-4a05-86a5-1b791cf0cdf3)
![D15FD3A7-F955-4525-9677-AE7E88B5D637 3](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/4490acd6-c4bb-4430-8196-d32f8066303b)

**Comment by cagnulein** [comment]
perfect, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and i will send you a new version where there is a new setting under the treadmill settings, called ftms treadmill. add it there and you will be ready to go.

Thanks

**Comment by lilalamballer** [comment]
I had a chance to test yesterday and the treadmill now connects to QZ.
Also when I use zwift with the meetup trick it adjusts my inclination automatically so thanks for this, it really works well!
I do have one more thing. On the app it does show the speed and I can adjust it from the app.
The inclination on the other hand I can not change and it keeps saying zero even when the inclination is set via zwift to my treadmill .

So the inclination icon is blinking and QZ is indeed sending the correct inclination to my treadmill and the treadmill gives audio feedback and moves to the correct elevation.
Also the elevation the treadmill indicates and the one from zwift are somewhat in sync.
On the other hand the value inside the tile of QZ stays 0.0 and also the elev. gain tile remains zero for the whole run.
In the screenshot the treadmill was on 5% inclination and my run already had an elev. gain of about 30m.

How it looks on QZ:
![ED5806A7-9589-4DC6-8DD6-BA48CAE78B9B](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/4e4871a0-02db-4025-a37b-ef05b63e5016)

Treadmill inclination is working:
![13BA5C83-F18A-4464-AA5D-F781B5B12742](https://github.com/cagnulein/qdomyos-zwift/assets/51449552/fc0b23b0-d0e5-4f90-867a-2dca3e9b6c10)

This was the debug log from that training session:
[debug-zo_dec_31_16_21_51_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13804884/debug-zo_dec_31_16_21_51_2023.log)

**Comment by cagnulein** [comment]
mmm I checked and the treadmill it doesn't send at all the inclination. The only thing that I can do is "when i force the inclination, I can set the value on the inclination tile so it will take in account, what do you think?"

Also I don't know if you are aware, but you don't need the meetup tricks anymore! Just add the zwift credentials in qz and it will change automatically without the meetup!

**Comment by lilalamballer** [comment]
I have done some more tests this week and also tried Kinomap which is natively supported by my treadmill. Both the tests I did with QZ and also Kinomap seem to have the exact same behaviour. The incline works but it does not report the incline back. This is of course a problem of the treadmill and maybe just the version of firmware that I have. It would be very nice if you could make a temporary fix for me but I am also going to contact the manufacturer to fix the issue with the firmware.

**Comment by cagnulein** [comment]
sure i can do it, it will be great if you can join the patreon page to support the development!

**Comment by cagnulein** [comment]
version sent

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle ore 16:35 Eef Verheijden <
***@***.***> ha scritto:

**Comment by lilalamballer** [comment]
> sure i can do it, it will be great if you can join the patreon page to support the development!

I will do, Thanks you !

**Comment by cagnulein** [comment]
@lilalamballer is it working?

**Comment by nyszilard** [comment]
@cagnulein Tunturi is completely missing from the [Treadmill Compatibility Table](https://github.com/cagnulein/qdomyos-zwift/wiki/Equipment-Compatibility). Is there any particular reason for this?

**Comment by cagnulein** [comment]
That table is simply not update bevause now all the treadmill works (99%)

Do you have any issues with it?

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno sab 29 nov 2025 alle 14:19 Nyeste Szilárd <
***@***.***> ha scritto:
