### ISSUE TITLE
I_EB bike not connected?

### ISSUE THREAD

**Issue by Sparky2104** [cagnulein/qdomyos-zwift#1936]
[debug-Mon_Jan_1_11_21_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13804400/debug-Mon_Jan_1_11_21_54_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
what should I check on this debug log^

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 1 gen 2024 alle ore 12:56 Sparky2104 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @Sparky2104 I checked the log and the bike is well connected and I can see the metrics. Did you try to ride a little? I saw for a moment cadence to 15

**Comment by Sparky2104** [comment]
Hi Roberto,

I gave up, it was too frustrating trying to set up and then trying to manage via messages.

What was key for me was the accurate wattage and ERG coming from Zwift, but I didn’t know how to get there.

I may try again tonight or tomorrow but for now the brand new spin bike is parked aside and I continue to use the Turbo Trainer.

If I could get it set up it would be great.

Mark


Sent from my iPhone

On 11 Jan 2024, at 09:51, Roberto Viola ***@***.***> wrote:

﻿

@Sparky2104<https://github.com/Sparky2104> any news?

**Comment by cagnulein** [comment]
simply provide me a debug log while you're doing a 1 minute ride and i can check it which is your issue.

also I can the erg mode for your bike if you can collect a power tablet (i will tell you how in case)

let me know

**Comment by Sparky2104** [comment]
Hi

Can you clarify what you mean by a power tablet ? I have power pedals and a Garmin edge. Not sure what a power tablet is ?

Mark

Sent from my iPhone

On 11 Jan 2024, at 12:23, Roberto Viola ***@***.***> wrote:

﻿

simply provide me a debug log while you're doing a 1 minute ride and i can check it which is your issue.

also I can the erg mode for your bike if you can collect a power tablet (i will tell you how in case)

let me know

**Comment by cagnulein** [comment]
sorry I mean Power Table. A table collecting power, cadence and resistance
to implement erg tailored to your bike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:00 Sparky2104 ***@***.***>
ha scritto:

> Hi
>
> Can you clarify what you mean by a power tablet ? I have power pedals and
> a Garmin edge. Not sure what a power tablet is ?
>
> Mark
>
> Sent from my iPhone
>

**Comment by Sparky2104** [comment]
Ok,
So where to I get this power table ?
I would need some instruction on obtaining that.
Mark


Sent from my iPhone

On 11 Jan 2024, at 18:08, Roberto Viola ***@***.***> wrote:

﻿

sorry I mean Power Table. A table collecting power, cadence and resistance
to implement erg tailored to your bike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:00 Sparky2104 ***@***.***>
ha scritto:

> Hi
>
> Can you clarify what you mean by a power tablet ? I have power pedals and
> a Garmin edge. Not sure what a power tablet is ?
>
> Mark
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
sure check this
https://github.com/cagnulein/qdomyos-zwift/issues/1683#issuecomment-1741987920


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:13 Sparky2104 ***@***.***>
ha scritto:

> Ok,
> So where to I get this power table ?
> I would need some instruction on obtaining that.
> Mark
>
>
> Sent from my iPhone
>

**Comment by Sparky2104** [comment]
Thanks, I feel the turbo trainer is the way to go for me with Zwift. Maybe I will try and produce a table at some stage however I say I would have to compile something extensive with many data points ?

As this must be a common topic, is there already a sample template to leverage from ? Am assuming many different cadence readings across all resistance levels recording my power on the pedals at each point.  This is what I am understanding, please correct me if I am wrong.

Mark


Sent from my iPhone

On 11 Jan 2024, at 18:45, Roberto Viola ***@***.***> wrote:

﻿

sure check this
https://github.com/cagnulein/qdomyos-zwift/issues/1683#issuecomment-1741987920


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:13 Sparky2104 ***@***.***>
ha scritto:

> Ok,
> So where to I get this power table ?
> I would need some instruction on obtaining that.
> Mark
>
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
yes check the table in the thread that I linked, you can use that one as a template!

**Comment by Sparky2104** [comment]
It was not completed , the assurance was too diffucult to follow by constant messages.


Sent from my iPhone

On 3 Feb 2024, at 18:16, stale[bot] ***@***.***> wrote:

﻿

Closed #1936<https://github.com/cagnulein/qdomyos-zwift/issues/1936> as completed.

**Comment by cagnulein** [comment]
ok so @Sparky2104 do you want to complete it? how can i help you? which part is difficult?
