### ISSUE TITLE
[BUG] trouble connecting to Echelon Sport-S

### ISSUE THREAD

**Issue by Arash-Afshar** [cagnulein/qdomyos-zwift#1939]
**Describe the bug**
The app discovers the bike and connects the bluetooth but it fails to establish a reliable connection (I hear the bluetooth on the device keeps connecting and disconnecting).

**To Reproduce**
Close the Echelon app, start pedalling, open the qdomyos-zwift app

**Expected behavior**
It should show metrics such as Cadence, etc

**Smartphone (please complete the following information):**
 - Device: iPhoneXR
 - OS: iOS
 - Version: 17.2.1

**Append a debug log**

The log was too long to be attached as a whole. Here is the part that I think is relevant:

```
Tue Jan 2 16:13:16 2024 1704237196999 Debug: /Users/cagnulein/qdomyos-zwift/src/main.cpp int main(int, char **) "echelon_resistance_gain" QVariant(double, 1)
Tue Jan 2 16:13:16 2024 1704237196999 Debug: /Users/cagnulein/qdomyos-zwift/src/main.cpp int main(int, char **) "echelon_resistance_offset" QVariant(double, 0)
Tue Jan 2 16:13:16 2024 1704237196999 Debug: /Users/cagnulein/qdomyos-zwift/src/main.cpp int main(int, char **) "echelon_watttable" QVariant(QString, "Echelon")
Tue Jan 2 16:13:17 2024 1704237197116 Debug: /Users/cagnulein/qdomyos-zwift/src/main.cpp int main(int, char **) "virtual_device_echelon" QVariant(bool, false)
Tue Jan 2 16:13:58 2024 1704237238204 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::deviceConnected(QBluetoothDeviceInfo) echelonconnectsport(0x14380e800)
Tue Jan 2 16:13:58 2024 1704237238491 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::deviceDiscovered(const QBluetoothDeviceInfo &) "Found new device: ECH-SPORTS-XXXXXX (00:00:00:00:00:00)"
Tue Jan 2 16:13:58 2024 1704237238496 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::ConnectingState
Tue Jan 2 16:17:01 2024 1704237421408 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::ConnectedState
Tue Jan 2 16:17:01 2024 1704237421410 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp auto echelonconnectsport::deviceDiscovered(const QBluetoothDeviceInfo &)::(anonymous class)::operator()() const "Controller connected. Search services..."
Tue Jan 2 16:17:01 2024 1704237421414 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::DiscoveringState
Tue Jan 2 16:17:01 2024 1704237421986 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::UnconnectedState
Tue Jan 2 16:17:01 2024 1704237421987 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "trying to connect back again..."
Tue Jan 2 16:17:01 2024 1704237421989 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::ConnectingState
Tue Jan 2 16:17:01 2024 1704237421990 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp auto echelonconnectsport::deviceDiscovered(const QBluetoothDeviceInfo &)::(anonymous class)::operator()() const "LowEnergy controller disconnected"
```
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Arash-Afshar i need the full log to understand it. thanks

**Comment by Arash-Afshar** [comment]
[debug-Tue_Jan_2_16_13_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13819772/debug-Tue_Jan_2_16_13_16_2024.log)

Here is the full log. I redacted a couple of things:
* Deleted some of the lines that had my other bluetooth devices in it
* Changed the device id and replaced it with XXXX

**Comment by cagnulein** [comment]
@Arash-Afshar try to disable the virtual bluetooth device setting in qz in the experimental setting (only this!) and restart qz
Let me know if it's better

**Comment by Arash-Afshar** [comment]
@cagnulein it did not work. Here is the new log.
[debug-Wed_Jan_3_10_20_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13821731/debug-Wed_Jan_3_10_20_47_2024.log)

**Comment by cagnulein** [comment]
is the echelon app working fine on the same phone?

**Comment by cagnulein** [comment]
also please don't change the log otherwise it's impossible to help you. if you are worried about privacy send me it the full log by email. i guess there is something in the stripped file that's useful to understand it

**Comment by Arash-Afshar** [comment]
Sure, I'll email you the log.

**Comment by cagnulein** [comment]
what about the echelon app? is working fine on the same phone?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 gen 2024 alle 19:09 Arash Afshar ***@***.***>
ha scritto:

**Comment by Arash-Afshar** [comment]
Thanks for the help. It turned out to be a hardware issue.

**Comment by sha3banii** [comment]
Hi @Arash-Afshar , I am having a similar issue to what you are describing. How did you discover it was a hardware issue? How did you end up fixing it?

**Comment by cagnulein** [comment]
@sha3banii the fastest way is using the echelon app. if it does the same issue on the same phone, you are 100% sure it's an hardware issue

**Comment by sha3banii** [comment]
Yes @cagnulein , the app can find the bike, but cannot connect to it. The symptoms are different, but definitely there is a problem establishing connection between the bike and the app. I was curious if by "hardware problem", it means a replacement unit would potentially fix the problem, or the whole Echelon brand is junk.

**Comment by cagnulein** [comment]
a replacement will definitely fixed it. it's just a bluetooth defective unit
