### ISSUE TITLE
Build error with the last pull from the repository on Raspberry Pi

### ISSUE THREAD

**Issue by shoulih** [cagnulein/qdomyos-zwift#194]
QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o bluetooth.o bluetooth.cpp
In file included from bluetooth.h:29,
                 from bluetooth.cpp:1:
m3ibike.h:190:79: error: ‘QBluetoothDeviceInfo::Fields’ has not been declared
 d deviceUpdatedPriv(const QBluetoothDeviceInfo&, QBluetoothDeviceInfo::Fields);
                                                                        ^~~~~~

make: *** [Makefile:1524: bluetooth.o] Error 1

**Comment by cagnulein** [comment]
Yes it's coming from the keiser merge. I think debian should push the qt
5.15 soon

Il mer 10 mar 2021, 01:24 shoulih <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
@p3g4asus maybe we can use some #ifdef to avoid compiling m3i under old qt versions?

**Comment by p3g4asus** [comment]
Oh yes. I am sorry for that. That method is used only for debug purposes. Indeed an ifdef is needed in the m3i header file for the method declaration. In the .c file there should already be.

**Comment by p3g4asus** [comment]
Something like:
```
#if (QT_VERSION >= QT_VERSION_CHECK(5, 12, 0))
    void deviceDiscoveredPriv(const QBluetoothDeviceInfo &device);
#endif
```
in `m3ibike.h`.
Its absence is a bug (my forgetfulness).

**Comment by cagnulein** [comment]
pushed! thanks

**Comment by shoulih** [comment]
Now, it errors out at a different line with the latest pull:

![image](https://user-images.githubusercontent.com/66762397/110983052-2486be80-831e-11eb-8cd5-a92b1ac144be.png)

**Comment by cagnulein** [comment]
Ok other ifdef are missing after the merge.
I Will fix them tomorrow
Thanks

Il ven 12 mar 2021, 19:40 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
great and thanks again!

**Comment by p3g4asus** [comment]
@cagnulein Turns out that if you have QT < 5.12 m3ibike cannot be supported with QT API. You will have to use java search on android and Objective-C search on iOS. Manufacturerdata method is essential for m3i to work with qt search. I will modify my code to take that into account.

**Comment by shoulih** [comment]
@p3g4asus just checking to see if you get a chance to modify your code?  thanks!

**Comment by p3g4asus** [comment]
> @p3g4asus just checking to see if you get a chance to modify your code?  thanks!

That build error should be fixed after the last PR got merged. Do you still get build errors?

**Comment by shoulih** [comment]
yes, the build error has been fixed.  thanks again!
