### ISSUE TITLE
[REQ] Speed via ANT+ to Garmin Watches

### ISSUE THREAD

**Issue by fabcd14** [cagnulein/qdomyos-zwift#1941]
Hello,
Thanks for this app that allows me to sync cadence from my Domyos Bike 500 to biking activities to my Garmin.
However, I own a **Garmin Venu 2**. I've seen on other threads that speed is defined via the Power function which is synched to Garmin Forerunner type of watches. However, my watch doesn't have this power function and then can't see speed as its not a Forerunner.
The idea is to send via ANT+ the actual speed of the bike, so that I can connect my watch to Speed and Cadence via ANT+.
Is it possible to send both of the info via the qz app ?

For the story, I had previously 2 ANT+ sensors that I put to my bike, but it lacks stability and precision. Cadence was running from 0 to the actual cadence each 4-5 seconds randomly. And the speed was faster that showed on the bike. Since i use your app, I have not this issue. It will be great to see the speed too.
Thanks,

**Comment by cagnulein** [comment]
Hi @fabcd14 which kind of sensor are you getting from qz on your watch? did you get the cadence sensor?

**Comment by fabcd14** [comment]
Hello, yes i only get the cadence sensor, this is the only one recognized by my watch via ANT+.
Power is not supported by my watch as it is not from the Forerunner range.

**Comment by cagnulein** [comment]
qz is sending cadence and speed in the ant+ standard way so your watch should see it. It's not in the power context. There is no other way to send it unfortunately.

**Comment by cagnulein** [comment]
somewhere aren't able to set the wheel diamater?

**Comment by fabcd14** [comment]
!

> qz is sending cadence and speed in the ant+ standard way so your watch should see it. It's not in the power context. There is no other way to send it unfortunately.

That is weird because i get Cadence/Speed sensor from the Magene S3+ devices ( that i bought here : https://www.amazon.fr/dp/B085Q5C62J/ref=twister_B08BZDFFC9?_encoding=UTF8&th=1 ) and they are recognized as Cadence for one, and Speed for the other.

I'm not able to set wheel diameter only by using qz. As I understood, this is possible with only Speed sensor.
I have not tried with the Magene speed sensor to set the wheel diameter, I'll give a try this evening to see if it's related to speed sensor.

**Comment by fabcd14** [comment]
I forgot to say that I am using a Xiaomi 11T Pro as a mobile phone, and it's compatible with ANT+ (checked with the ANT Tester app you mentioned in your video).

**Comment by cagnulein** [comment]
with the ant tester app or similar are you able to check the difference from the qz ant device and the magene one?

**Comment by fabcd14** [comment]
A bit of news, I just made  a lot of trials yesterday, by switching off all external sensors (Magene ones). In fact, i didn't received ANT+ from the phone at all since the beginning. In fact Ant Tester says on my phone that onboard device is not detected but supports OTG, so i ordered an ANT+ dongle to test it.

In the meantime, i got my old phone (OnePlus 6) back from a drawer on Android 11. ANT Tester said the same thing than my Xiaomi 11T Pro. I downgraded it to Android 9 and then now fully supported (all items in green !). I suspect that Google removed a bit of ANT support since v11. I reinstalled qzdomyos-swift and activated ANT+ support. I'm at work so I'll do the trials in the evening.

**Comment by cagnulein** [comment]
ok! be sure to use the beta QZ app for ant! let me know!

**Comment by fabcd14** [comment]
Hello, a bit of news after a while. It works perfectly with my old OnePlus 6 and Android 9. Garmin recognizes it as Speed/Cadence ANT+ sensor.

**Comment by cagnulein** [comment]
great! so are you satisfied with it?
