### ISSUE TITLE
C1750 won't connect

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#1943]
Still can not get my C 1750 to connect. Could you please see if you can determine the issue from the attached debug? I can ping the treadmill from my phone but I get no data showing on the QZ app.

[debug-Wed_Jan_3_09_22_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13820754/debug-Wed_Jan_3_09_22_16_2024.log)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
about https://github.com/cagnulein/qdomyos-zwift/issues/1553

@Dwhetsel do a factory reset, don't update ifit app, and install the qz companion. In the log there is no messages at all from the companion, let's see if this will help.

**Comment by cagnulein** [comment]
@Dwhetsel any news?
