### ISSUE TITLE
Ant+ Connection to Garmin 705

### ISSUE THREAD

**Issue by omecabs** [cagnulein/qdomyos-zwift#1944]
**Describe the bug**

**To Reproduce**
1. Go to '...'QZ program with the ANT+ ATTACHED to the phone and required drivers installed

**Expected behavior**
Unsure what to expect

**Screenshots**
Provided via Email.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Google pixel 8
 - OS: [e.g. iOS8.1] Android 14
 - Version [e.g. 22] 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Wed_Jan_3_12_24_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13822277/debug-Wed_Jan_3_12_24_22_2024.log)

[debug-Wed_Jan_3_12_26_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13822265/debug-Wed_Jan_3_12_26_32_2024.log)
[debug-Wed_Jan_3_12_26_32_2024[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13822290/debug-Wed_Jan_3_12_26_32_2024.1.log)

**Comment by cagnulein** [comment]
@omecabs the main issue in this log is that the ant cadence setting is disabled! enable it and restart qz

let me know!

**Comment by omecabs** [comment]
It's enabled now. still no connection. THe Garmin still says "connecting". THe Grarmin's main display still has no data displaying.

[debug-Wed_Jan_3_13_20_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13822615/debug-Wed_Jan_3_13_20_46_2024.log)
[debug-Wed_Jan_3_13_22_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13822616/debug-Wed_Jan_3_13_22_07_2024.log)

**Comment by cagnulein** [comment]
hi both logs are 0 bytes. could you please upload them again?
also the garmin shows at least the sensor?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 gen 2024 alle ore 20:30 omecabs ***@***.***>
ha scritto:

**Comment by omecabs** [comment]
[debug-Wed_Jan_3_13_22_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13823103/debug-Wed_Jan_3_13_22_07_2024.log)
[debug-Wed_Jan_3_13_20_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13823104/debug-Wed_Jan_3_13_20_46_2024.log)

The Garmin does not show the sensor. where do I look for it?

**Comment by omecabs** [comment]
[debug-Wed_Jan_3_13_22_07_2024[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13823115/debug-Wed_Jan_3_13_22_07_2024.1.log)
[debug-Wed_Jan_3_13_20_46_2024[1].log](https://github.com/cagnulein/qdomyos-zwift/files/13823118/debug-Wed_Jan_3_13_20_46_2024.1.log)

**Comment by cagnulein** [comment]
> The Garmin does not show the sensor. where do I look for it?

pair new sensors page on garmin while qz is running and connected to the bike, search for it and it will find the power and cadence sensor.
are you doing in this way?

**Comment by omecabs** [comment]
no I am not. I did not know that's the procedure. I will and get back to you. thank you

**Comment by cagnulein** [comment]
@omecabs any news?

**Comment by omecabs** [comment]
Hi sorry I am in the office today and will try later when I go back home. thanks

**Comment by cagnulein** [comment]
@omecabs any news?

**Comment by omecabs** [comment]
Hi Roberto, thanks for following up. Im having issues with my Pixel 8 at
the moment that Im trying to resolve. I may end up getting a different
phone. I'll keep you posted.
THank you
