### ISSUE TITLE
[BUG]qdomyos doesn't see HR from garmin watches

### ISSUE THREAD

**Issue by OrislavK** [cagnulein/qdomyos-zwift#1948]
**Describe the bug**
HR from watches doesn't see in qdomyos on iphone and Zwift.

**To Reproduce**
On garmin watches fenix 6 pro installed qz companion.
On iphone installed test versions qzdomyos 2.16.30 and Garmin companion is enabled.

**Expected behavior**
HR must be shown to retranslate it to Zwift.

**Smartphone (please complete the following information):**
 - Device: iPhone 15 pro
 - OS: iOS 17.2.1

**Append a debug log**

[debug-Thu_Jan_4_18_54_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13832450/debug-Thu_Jan_4_18_54_10_2024.log)

**Comment by cagnulein** [comment]
@OrislavK do you have garmin connect installed and paired with the watch on this iphone? I don't see it.
I guess this is the issue

**Comment by OrislavK** [comment]
> @OrislavK do you have garmin connect installed and paired with the watch on this iphone? I don't see it. I guess this is the issue

of course Garmin Connect installed and paired with watches.

![F74C15F4-88AB-43D3-B350-B0518810D0B6_1_102_o](https://github.com/cagnulein/qdomyos-zwift/assets/25452579/93ecb5c2-d5b8-4cdd-9f43-7cc234548b1d)

**Comment by cagnulein** [comment]
do you see Garmin connect opening for a moment when you start QZ?
All the permissions are enabled for QZ?
It seems like garmin connect refuses to talk with qz on your device. I don't know if there are any restrictions in your country about this

**Comment by cagnulein** [comment]
this is what i saw https://github.com/cagnulein/qdomyos-zwift/assets/48216/13805892-8780-4770-be4e-d1aa96d8c318

you see the garmin connect for a second?

**Comment by OrislavK** [comment]
> > > Вот что я увидел https://github.com/cagnulein/qdomyos-zwift/assets/48216/13805892-8780-4770-be4e-d1aa96d8c318 > > > Вы на секунду увидели garmin connect?

No, i didn't see.

Can you add option to check permissions and if it unsuccessful, then force to ask?

I don't see the connection between the apps, but each app has all the permissions in the settings of ios.

**Comment by cagnulein** [comment]
let me check , maybe it's about the new yesoul implementation that i did
for you. i will update you tomorrow
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 18:35 Orislav ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@OrislavK good news! fixed! i will send you another one later today!

**Comment by cagnulein** [comment]
version sent! let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle ore 18:37 cagnulein ***@***.***> ha
scritto:

**Comment by OrislavK** [comment]
> sent now

Got it, Garmin Connect is now showing up and HR is now showing up in QZ when companion is active. As I understand it, HR transfer from the watch is only possible in this form, i.e. I can't start a training session Bike Indoor on the watches and get HR in QZ.

I have both garmin companion and garmin sensor enabled in QZ, but the QZ as a sensor is no longer detected by the watch - is it a bug or a feature?

[debug-Fri_Jan_5_21_20_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13845361/debug-Fri_Jan_5_21_20_57_2024.log)

**Comment by cagnulein** [comment]
great! yes it's only possible in this way . or if you have the possibility
to broadcast heart from watch in some other way. some garmin can.

about the sensor: are you running this from your mac? the sensors works
only on mac due to garmin limitation (they want a bluetooth device with
public address, check this
https://robertoviola.cloud/2023/03/24/why-my-sensor-cant-connect-to-a-garmin-device/
 )

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle 19:35 Orislav ***@***.***> ha
scritto:

**Comment by OrislavK** [comment]
> great! yes it's only possible in this way . or if you have the possibility to broadcast heart from watching in some other way.

Understood. Yes, fenix 6 pro can rebroadcast HR, but the battery eats faster :) Anyway, I already decided to buy, and I did, Polar verity sense - ant+ + BT for 2 channels, among other things.

> about the sensor: are you running this from your mac? the sensors works only on mac due to garmin limitation (they want a bluetooth device with public address, check this https://robertoviola.cloud/2023/03/24/why-my-sensor-cant-connect-to-a-garmin-device/ ).

No, as usual I want everything at once, this time I checked everything on iphone. Understood and hopefully already memorized for a long time. Oh these restrictions.  :)

**Comment by cagnulein** [comment]
@OrislavK i have the version for ipad or iphone that should stay alive in background. As I said I added the healhkit also in the qz app when it's running standalone to try to if iOS will keep QZ alive in background. If you want we can check if it's better for your case if you are still interested.
Let me know

**Comment by OrislavK** [comment]
yes, i want to try.

> @OrislavK i have the version for ipad or iphone that should stay alive in background. As I said I added the healhkit also in the qz app when it's running standalone to try to if iOS will keep QZ alive in background. If you want we can check if it's better for your case if you are still interested. Let me know

**Comment by cagnulein** [comment]
ok i'm sending it by email

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle ore 14:46 Orislav ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
sent

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle ore 15:05 cagnulein ***@***.***> ha
scritto:

**Comment by OrislavK** [comment]
I set read and write permissions on some parameters, but it didn't help, as soon as I switched from QZ to ZC - after a while data transfer stopped and to restore communication, I had to exit to the zwift window for it to see the sensors again.


> sent Roberto Viola Software engineer and open source enthusiast http://robertoviola.cloud Il giorno mer 10 gen 2024 alle ore 15:05 cagnulein ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
did you enable all of the permission? must be all enabled. also did you restart qz after enabling the permissions? you will know that you did right beucase in the health app you will see a workout from qz

**Comment by OrislavK** [comment]
> did you enable all of the permission? must be all enabled. also did you restart qz after enabling the permissions? you will know that you did right beucase in the health app you will see a workout from qz

no, not everything. I wouldn't want duplicate information, so I allowed everything about the bike on write and everything on read.

I'll try to include everything later, but it's purely for the test, as in reality you don't need QZ to write it all, as with zwift it will also come to garmin, and from there to healthkit.

**Comment by cagnulein** [comment]
> I'll try to include everything later, but it's purely for the test, as in reality you don't need QZ to write it all, as with zwift it will also come to garmin, and from there to healthkit.

i know but first we have to understand if creating an apple health workout will prevent ios to kill qz. after that we can customize everything, but first we have to check this

**Comment by OrislavK** [comment]
i checked with all permissions (iphone/ipad)- not worked.

**Comment by cagnulein** [comment]
ok so the only thing that it's possible it's the background task feature from iOS but it's a huge change for QZ so I guess it's not something that I can do right now. Sorry
