### ISSUE TITLE
Add cadence to virtualtreadmill for ellipticals

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#195]
Elliptical has cadence, so i should send it to Zwift

**Comment by cagnulein** [comment]
#173

**Comment by cagnulein** [comment]
in the FTMS profile for treadmill there isn't the possibility to add cadence. We need to add a new service for this (so on android > 9 it will not work)

**Comment by cagnulein** [comment]
@jonathancolledge i tried to add this on 2.8.28. Could you try it?

**Comment by jonathancolledge** [comment]
I tried - I couldn't get either Zwift or Kinomap to show/connect to run cadence. Is it supposed to send cadence as if it is a running footpod?

**Comment by cagnulein** [comment]
yep it should, i mean i didn't have the opportunity to test it. i'm sending
cadence as i do for a bike, maybe they need a foot sensor (but in order to
do so, only android <10 and ios devices can act like it)
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 14 ago 2021 alle ore 19:44 jonathancolledge <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done in the version 2.9.0
