### ISSUE TITLE
[BUG] Atletica Lightspeed Treadmill start issue (Fitshow)

### ISSUE THREAD

**Issue by Th3Raven** [cagnulein/qdomyos-zwift#1950]
**Describe the bug**
When I click start, the countdown of the treadmill starts from 5 to 3 and then it aborts (I think here it gets connected via bluetooth and then it stops whatever it was doing)

**To Reproduce**
Just starting the app and press "start"

**Expected behavior**
Treadmill works

**Smartphone (please complete the following information):**
 - Device: Redmi Note 12S
 - OS: Android 13
 - Version  TP1A.220624.014

[debug-Thu_Jan_4_17_39_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13833355/debug-Thu_Jan_4_17_39_18_2024.log)
[debug-Thu_Jan_4_17_12_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13833356/debug-Thu_Jan_4_17_12_43_2024.log)

**Comment by cagnulein** [comment]
if you start the treadmill on the treadmill directly then the stats are
fine? i mean is a start issue only?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 17:51 Th3Raven ***@***.***> ha
scritto:

**Comment by Th3Raven** [comment]
I just tried it and it seems to be only a start issue. If I start the treadmill on the treadmill it stops once when the bluetooth connection is established. Now when it's connected and I use again the start button of the treadmill I can change the pace, inclination and so on the app.

If I use the start button on the app, it starts but stops after like 3 seconds

**Comment by cagnulein** [comment]
ok so i will check the start issue!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle 08:30 Th3Raven ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Th3Raven ok i did a modification! It's building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7420510879
At the end you will see at the bottom of the page an apk. Give it a try uninstalling the current one and installing this one.
It will take up to 1h to build it up
Let me know!

**Comment by Th3Raven** [comment]
Ok, this one works a lot better now. If I just power the treadmill and open the app it shows "SW6830EAI-0008 found" but the treadmill does not recognize being "bluetoothed" (it doesn't show the bluetooth symbol). When I start now via app it starts the treadmill and like 3 seconds later it shows the bluetooth symbol to let me know it is connected. This aborts the starting.

But now the connection stays after the abort and when I start again via app it works. This didn't work before.

**Comment by cagnulein** [comment]
ok so it seems that your treadmill need 2 starts. one to start the communication and another one to really start the tape.

ok try this one so https://github.com/cagnulein/qdomyos-zwift/actions/runs/7421819229

**Comment by Th3Raven** [comment]
this one works! Now is my only question if it is possible to start custom workouts or predefined workouts like in kinni?

**Comment by cagnulein** [comment]
you can load custom workouts in the open train program (the preloaded one are only for bike, you can load or create new one from internet). check this article https://robertoviola.cloud/2023/11/20/exploring-the-versatility-of-qz-app-your-gateway-to-a-tailored-fitness-experience/

also you can load the gpx files and QZ will follow it changing speed and inclination!

Consider that the version is a 15 minutes trial, if you want to unlock it you need to join the patreon page https://patreon.com/cagnulein
