### ISSUE TITLE
Adb.exe stays resident on QZ exit (Windows)

### ISSUE THREAD

**Issue by victorypoint** [cagnulein/qdomyos-zwift#1951]
I've been experiencing no auto-incline sometimes when I leave my Zwift/QZ PC on during the day and then turn on the treadmill after several hours to start a Zwift session. I narrowed it down to the ADB.exe process staying in memory on PC. If I kill it, auto-incline works.

I confirmed.. single ADB.exe stays resident on QZ exit - both via quit from menu and x on window bar.

This works to kill adb.exe process.. 
`cmd /c wmic process where name='adb.exe' delete`

**Comment by cagnulein** [comment]
@victorypoint thanks for the feedback, could you check this build? https://github.com/cagnulein/qdomyos-zwift/actions/runs/7420467774

**Comment by victorypoint** [comment]
@cagnulein, I tested windows-binary.zip and windows-msvc2019-ai-server-binary.zip builds. In each case, adb.exe was not killed when exiting QZ by hitting window x close or Quit from menu.

[windows-binary-debug-Fri_Jan_5_11_20_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13843730/windows-binary-debug-Fri_Jan_5_11_20_46_2024.log)
[windows-msvc2019-ai-server-binary1-debug-Fri_Jan_5_11_15_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13843731/windows-msvc2019-ai-server-binary1-debug-Fri_Jan_5_11_15_42_2024.log)
[windows-msvc2019-ai-server-binary2-debug-Fri_Jan_5_11_16_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13843732/windows-msvc2019-ai-server-binary2-debug-Fri_Jan_5_11_16_49_2024.log)
[windows-msvc2019-ai-server-binary3-debug-Fri_Jan_5_11_17_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13843733/windows-msvc2019-ai-server-binary3-debug-Fri_Jan_5_11_17_53_2024.log)

**Comment by cagnulein** [comment]
thanks @victorypoint i added some debug log in the terminate function 
let's see if i can understand which is the issue
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7423599840

unfortunately i don't have a windows build to try :(

**Comment by cagnulein** [comment]
sorry wrong link https://github.com/cagnulein/qdomyos-zwift/actions/runs/7423659773

**Comment by victorypoint** [comment]
@cagnulein, ok new logs attached.

[windows-msvc2019-ai-server-binary2-debug-Fri_Jan_5_13_04_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13844784/windows-msvc2019-ai-server-binary2-debug-Fri_Jan_5_13_04_23_2024.log)
[windows-debug-debug-Fri_Jan_5_13_12_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13844785/windows-debug-debug-Fri_Jan_5_13_12_42_2024.log)

**Comment by cagnulein** [comment]
ok so QT thinks to did everything right

```
Fri Jan 5 13:13:31 2024 1704474811139 Debug: nordictrackifitadbtreadmill.cpp void nordictrackifitadbtreadmill::stopLogcatAdbThread() stopLogcatAdbThread()
Fri Jan 5 13:13:31 2024 1704474811141 Debug: nordictrackifitadbtreadmill.cpp void nordictrackifitadbtreadmill::stopLogcatAdbThread() stopLogcatAdbThread() quit
Fri Jan 5 13:13:31 2024 1704474811143 Debug: nordictrackifitadbtreadmill.cpp void nordictrackifitadbtreadmill::stopLogcatAdbThread() stopLogcatAdbThread() terminate
Fri Jan 5 13:13:31 2024 1704474811146 Debug: nordictrackifitadbtreadmill.cpp void nordictrackifitadbtreadmill::stopLogcatAdbThread() stopLogcatAdbThread() wait
```

Let's try to add this command at the end so

`cmd /c wmic process where name='adb.exe' delete`

**Comment by victorypoint** [comment]
@cagnulein, I forgot to mention the QZ terminal window stayed open indefinitely after QZ quit - so seemed to hang.

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7424793324

mmm..that's interesting..I should check what could cause this. let's try this build to see if it was ADB or something else

**Comment by victorypoint** [comment]
@cagnulein, you nailed it. Adb.exe is killed on exit and no more terminal window hang issue. Nicely done! 👍🎉🥳

**Comment by cagnulein** [comment]
actually you did it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle 19:18 Al Udell ***@***.***> ha
scritto:
