### ISSUE TITLE
No resistance / Incline on Zwift. Nordictrack S22i [BUG]

### ISSUE THREAD

**Issue by erimonf** [cagnulein/qdomyos-zwift#1952]
**Describe the bug**
Resistance and incline don't get any change from Zwift and I don't get any reaction when pushing the + incline button within QZ App.
Zwift runs in an Ipad and the QZ on a windows Lapot. My bike is a Nordictrack s221.
**To Reproduce**

**Expected behavior**
Resistance and incline automaically controlled by Zwift.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://
[debug-ju__ene__4_22_22_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13835856/debug-ju__ene__4_22_22_59_2024.log)
github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[debug-ju__ene__4_22_22_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13835860/debug-ju__ene__4_22_22_59_2024.log)

**Additional context**

**Comment by cagnulein** [comment]
thanks i will  check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 23:02 erimonf ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i see adb shell  input swipe 75 616 75 581 200

correctly.

do you see a touch reaction while the inclination should change?

without zwift, try also to press the inclination plus button qz to check if
you have a reaction on the touch screen

let me know


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 23:05 cagnulein ***@***.***> ha
scritto:

**Comment by erimonf** [comment]
What do you mean by a touch reaction? Without zwift the inclination plus button is also forzen (in fact, all of them are). There is no reaction on the ifit screen or in the resistance provided by the bike. 

Thanks again!

**Comment by cagnulein** [comment]
i mean: when you press the inclination plus button on qz, qz sends a commmand to the tablet to simulate a swipe on the inclination slider on your bike. so you should see a simulate touch event. don't you see it? if not we have to go with the adb method

**Comment by erimonf** [comment]
No, nothing happens on the bike's screen either pushing de plus button in QZ or when Zwift changes the inclination.

Thanks!

**Comment by cagnulein** [comment]
did you install the companion via adb?

**Comment by erimonf** [comment]
Yes, that step worked as described in your instructions! The QZ App I downloaded for windows is the following: windows-msvc2019-binary-no-python. That's right?

**Comment by erimonf** [comment]
Sorry Roberto, I don't hace programming skills...any thread or video to follow for it?

**Comment by cagnulein** [comment]
hah it's very easy. did you open a shell to run the installer?
just open a shell, go in to the adb directory that you unzipped and type that command

**Comment by erimonf** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/155685676/534190d4-a30c-4a5f-a3c9-ce64e5187ec8)

Ok! That's what I get. Just to clarify, the bike is open and I tried to run the command while using QZ App (and working good) and got the same result. I have an old Ipad at home  so I can try to run QZ app on this Ipad (instead of the laptop) and Zwift on another one, would that help in any way?

**Comment by erimonf** [comment]
Hi, Roberto.

For the first command I got a confirmation saying "already connected to the ip". When using the second, I got the same message "error: device offline".

Thank you for your patience.

**Comment by cagnulein** [comment]
that's strange, after the connect command if you type the

./adb devices -l 

are you seeing the bike?

**Comment by erimonf** [comment]
Yes, it appears the Bike's IP with the following text:  offline transport_id:3

**Comment by cagnulein** [comment]
is the adb setting on the bike still enabled? it seems somehow closed

**Comment by erimonf** [comment]
Do you mean if the USB debugging option is enabled? If so, yes it is! 've followed again the steps from the beginning (turning of the privilged mode and turning it on again) but didn't get any results.. Btw, I've seen that in the bike settings the bluetooth said disconnected. Is that right?

Thanks!!

**Comment by cagnulein** [comment]
that's so strange. are you able to run for example 

adb shell 

after the adb connect?

@victorypoint any advice? adb seems working for the installation but not for the adb swipes

**Comment by erimonf** [comment]
Thats the answer to ./adb shell 

avn_ref:/ $

Would be helpfull if I try to run QZ on an iphone? I assume that this will not work for inclination, but could work for resistance, right?

**Comment by cagnulein** [comment]
let's continue this, now adb is working. so try again the adb shell input command that i wrote above

**Comment by erimonf** [comment]
The manual workout gets paused!

**Comment by cagnulein** [comment]
Perfect! So now it’s working! Test again qz now without changing anything,
just press on the inclination plus button
Do you see an event?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 22:24 erimonf ***@***.***> ha
scritto:

**Comment by erimonf** [comment]
[debug-sá__ene__6_22_32_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13851433/debug-sa__ene__6_22_32_42_2024.log)

No, inclination remains at 0 in QZ and in  Bike.

**Comment by cagnulein** [comment]
Ok let's try on the iPhone with the same settings, there is something stupid that I don't understand. If it works manually, it has to work also with qz, I can't find any reason

**Comment by victorypoint** [comment]
Hi @erimonf. Can you confirm that the incline and resistance sliders are displayed on screen? They're necessary for swipe to work.

**Comment by erimonf** [comment]
You mean in QZ App ? Yes, but not clearly. I'm attaching a screenshot.
![QZ APP Screen  2024-01-06 224924](https://github.com/cagnulein/qdomyos-zwift/assets/155685676/1622a487-8e0b-47b7-a0fe-723f0d74ecc2)

**Comment by cagnulein** [comment]
No @erimonf in ifit on the bike tablet

**Comment by erimonf** [comment]
![20240106_225551](https://github.com/cagnulein/qdomyos-zwift/assets/155685676/69b5dc03-7a38-4d58-a07b-132f96c8d0d3)
 That's Ifit's screen. Btw, just noticed that the only slider that changes when pushing the buttons in QZ is the Fan Speed but it makes no event on the bike.

**Comment by cagnulein** [comment]
Good call @victorypoint ! @erimonf You need to enable the sliders in the settings!

**Comment by erimonf** [comment]
![20240106_232222](https://github.com/cagnulein/qdomyos-zwift/assets/155685676/ca91209d-27ae-42c0-b194-550000961313)

We are getting closer!! Thanks to both of you. This is the screen that must be displayed? If so, still no events with the resistance/inclination buttons..

**Comment by victorypoint** [comment]
@erimonf, yes that's the screen. And did you select your bike from the list of options in the companion screen on the bike?

**Comment by erimonf** [comment]
Yes, I had the s22i selected, which is mine. Anyway, these few minutes I have tried other options (all the bikes) but nothing changes. I have done it without turning off the bike between each ride, I think I have read in one of the threads that sometimes you do have to do it. Tomorrow I will continue testing the different options, unplugging between them. Any more ideas on what I could test? Thanks!!

**Comment by cagnulein** [comment]
Ok let me know and also try with the iPhone too. Just check if you can see a touch event reactions

**Comment by erimonf** [comment]
Hi, Roberto. Here my update:

Regarding the QZ on the laptop, no news. Not working with any of the bikes of the companion App.

Also bought the App for the iphone and it makes touching events on the screen but not what expected. When choosing "s22i bike" on the companion, only the incline button make a touching event and it only moves the resistance, not the inclination. 
When choosing "S22i bike (NTEX...)" also only the inclination button makes events but on this case it moves the inclination on the bike, but only upwards (event pushing the minus button moves up the inclination).
With the last Companion App option "Nordictrack studio bike" I don't get any touching events. Same with the Tour de France option.

**Comment by cagnulein** [comment]
ok that's a good news, so the iphone app can control the touch screen. did you enable the adb remote for this in the iphone app?

**Comment by erimonf** [comment]
Yeah, I've set the default settings plus the adb remote option enabled.

**Comment by cagnulein** [comment]
ok so first of all let's check with the latest qz verrsion (beta). 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS so i will send you the new beta and we will see if the behaviours it's the same

**Comment by erimonf** [comment]
Hi Roberto. To install the beta I used an iPad because the iphone I used for previous testing doesn't support ios 14. Unfortunately, with the iPad the result has been the same as I got with the Android and the Laptop, i.e. no touching events. With the Iphone with the Appstore version I did get touching events on the bike board, even if it didn't move the resistance and incline correctly. 

Thanks!

**Comment by erimonf** [comment]
Hi Roberto. To install the beta I used an iPad because the iphone I used for previous testing doesn't support ios 14. Unfortunately, with the iPad the result has been the same as I got with the Android and the Laptop, i.e. no touching events. With the Iphone with the Appstore version I did get touching events on the bike board, althpugh they didn't move the resistance and incline correctly.

Thanks!

**Comment by cagnulein** [comment]
what if you in the ipad you disabled the adb remote setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 21:22 erimonf ***@***.***> ha
scritto:

**Comment by erimonf** [comment]
Yeah, It works that way as it did with the Iphone. Both inclination buttons (plus and minus) move the inclination upwards.

**Comment by cagnulein** [comment]
ok so in the iphone app adb remote was disabled (the old version doesn't
have it). that's a good news , you don't need adb.

we just need to fix the coordinates now.

just to be sure: do you want to change resistance or inclination with qz
connected to zwift? i guess inclination, right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 21:32 erimonf ***@***.***> ha
scritto:

**Comment by erimonf** [comment]
At the moment none of it are working. Isn't it possible to automatize both?

**Comment by erimonf** [comment]
Oh yes, you are right sorry. I assume that ERG mode wouldn't work then, right?

Yes, when I said that i was referring to the absence of results when pushing the resistance button (no touch event and no changes in the resistance). On the other hand, I see them when pushing the inclination button in QZ.

Thank you!

**Comment by cagnulein** [comment]
yes it's how it supposed to works. i mean qz change only inclination for
your bike, we only to fix the coordinates. i will do it tomorrow

when this will work . i can also create an emulation of erg mode as i did
for echelon.

i just need a power table from you. but let's discuss about this when the
inclination will work perfectly.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 21:50 erimonf ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@erimonf when did you update the companion? because i made a patch 2 days ago for the s22i_NTEX02121_5 (original thread https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/70 ) that could apply to you. If you have an earlier version I suggest to update it and try
Let me know!

**Comment by cagnulein** [comment]
@erimonf did you try it?
