### ISSUE TITLE
Proform Treadmill 8.5

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1955]
[btsnoop_hci (1).log.zip](https://github.com/cagnulein/qdomyos-zwift/files/13840687/btsnoop_hci.1.log.zip)

**Comment by jsalas-code** [comment]
[debug-Fri_Jan_5_13_25_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13842080/debug-Fri_Jan_5_13_25_07_2024.log)
