### ISSUE TITLE
Lack of metrics in QZ companion app for NordicTrack s22i Bike

### ISSUE THREAD

**Issue by gapelp** [cagnulein/qdomyos-zwift#1956]
**Describe the bug**
Lack of cycling metrics generated in QZ companion app - only speed is accurate.

**To Reproduce**
1. Install completed on NordicTrack s22i bike
2. Connectivity to QZ app confirmed
3. Manual cycling mode started
4. Speed statistic is accurate and broadcast live.  Wattage is exaggerated.  No other metrics (cadence, resistance, incline etc.)are populated.

**Expected behavior**
Watts were actually approx 70w.  Cadence was approx 85rpm.  Resistance =1, incline = 0

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - OS: ios 17.1.2
 
**Append a debug log**

 
[debug-Wed_Jan_3_20_06_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13841521/debug-Wed_Jan_3_20_06_47_2024.log)

**Comment by cagnulein** [comment]
hi @gapelp you need to remove the ip of your bike from the nordictrack 2950 treadmill setting and press ok.
It will fix the issue ;)

**Comment by cagnulein** [comment]
@gapelp are we ok with this?

**Comment by gapelp** [comment]
Yes guys. Thanks so much for your help.

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno dom 14 gen 2024 alle 17:43 gapelp ***@***.***> ha
scritto:
