### ISSUE TITLE
Schwinn170 cadence sensor

### ISSUE THREAD

**Issue by Glideric** [cagnulein/qdomyos-zwift#1957]
The cadence rpm is not shown on qz app, when it’s show on schwinn 170 bike. See the bug sheet.

[
[debug-ven__janv__5_07_45_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13842260/debug-ven__janv__5_07_45_11_2024.log)
![ven  janv  5 07_45_52 2024](https://github.com/cagnulein/qdomyos-zwift/assets/155740517/f6db3ac9-59b0-4855-8a66-8ae1133ebbd4)
](url)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok thanks, i will check this in the next day!

checking the original ticket even the OP has the same issue https://github.com/cagnulein/qdomyos-zwift/issues/1365

I will try to find something useful in your debug log.

In order to simplify it, are you able to do a 1 minute workout with a debug log where you trying to keep a constant RPM?

**Comment by Glideric** [comment]
[debug-ven__janv__5_08_02_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13842464/debug-ven__janv__5_08_02_43_2024.log)
[debug-ven__janv__5_08_05_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13842466/debug-ven__janv__5_08_05_23_2024.log)
![ven  janv  5 08_05_10 2024](https://github.com/cagnulein/qdomyos-zwift/assets/155740517/d0e2e568-188e-41b8-8e51-c5123c9f4110)
[debug-ven__janv__5_07_45_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13842471/debug-ven__janv__5_07_45_11_2024.log)

**Comment by Glideric** [comment]
I was keeping 70rpm on the cadence on the bike.

**Comment by cagnulein** [comment]
@Glideric could be this the chart from your cadence workout session?

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/86222e30-4d40-4e6e-935e-ae85fb8de155)

**Comment by Glideric** [comment]
It looks like it, I was keeping around 70 rpm for that time.

Le 5 janv. 2024 à 08:32, Roberto Viola ***@***.***> a écrit :

﻿

@Glideric<https://github.com/Glideric> could be this the chart from your cadence workout session?

image.png (view on web)<https://github.com/cagnulein/qdomyos-zwift/assets/48216/86222e30-4d40-4e6e-935e-ae85fb8de155>

**Comment by cagnulein** [comment]
good news! i guess i got it! could you please do the same to another rpm
value? for example 60 or 80 or 90? so i will just double check it!
thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle ore 14:39 Glideric ***@***.***>
ha scritto:

> It looks like it, I was keeping around 70 rpm for that time.
>

**Comment by Glideric** [comment]
I've done it at 95rpm, here's the file.

**Comment by cagnulein** [comment]
i guess you forgot to attach the file :)

**Comment by Glideric** [comment]
Ad trouble joining the file, sent it to your mail.

**Comment by cagnulein** [comment]
done, i'm sending you a new version with the fix

**Comment by Glideric** [comment]
Thank you very much 👍

Le 5 janv. 2024 à 10:23, Roberto Viola ***@***.***> a écrit :

﻿

done, i'm sending you a new version with the fix

**Comment by cagnulein** [comment]
@Glideric are we ok with this?

**Comment by Glideric** [comment]
It’s better, I’ve had a -68 for cadence, it seems to work well when my resistance is 17. Every time I change resistance it change the value. But this setting is close to what I got. Thank you.

Le 11 janv. 2024 à 04:50, Roberto Viola ***@***.***> a écrit :

﻿

@Glideric<https://github.com/Glideric> are we ok with this?

**Comment by cagnulein** [comment]
ok let me know if you need any other issues
