### ISSUE TITLE
[REQ] WalkingPad R2(B?) support - TRR2FB

### ISSUE THREAD

**Issue by panaut0lordv** [cagnulein/qdomyos-zwift#1958]
Hello!
My Poland-distributed WalkingPad R2 TRR2FB advertises as KS-SC-BLR2C which doesn't go under the prefixes that are in source code currently.
I'd like to test adding this myself but I have M1 Mac and I am not sure how to build an M1 or iOS version from source code (didn't see guide in docs).
If you can suggest something then I'll try getting proper PR your way.

Thank you in advance!

**Comment by cagnulein** [comment]
done! did you already have the QZ app on your phone or mac from the store?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle ore 17:33 panaut0lordv <
***@***.***> ha scritto:

**Comment by panaut0lordv** [comment]
Wow, that was quick!
I'm testing with nightly APK (Android), on Mac I couldn't get the last official DMG to work.

**Comment by cagnulein** [comment]
ok you will see the build here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7424421508 in 30 minutes at the bottom of the page!
I guess we will need also to change the cypher key, but let's see

**Comment by panaut0lordv** [comment]
Thank you Roberto!
Now it seems to be connecting just fine, starts to show Treadmill fields and then I get in very quick succession crash prompt which disappears on its own.
The most interesting bit from logcat seems to be this, let me know what else would you like to see.
```
01-07 19:58:54.284 13816 13816 F DEBUG   : Process name is org.cagnulen.qdomyoszwift, not key_process
01-07 19:58:54.284 13816 13816 F DEBUG   : Cmdline: org.cagnulen.qdomyoszwift
01-07 19:58:54.284 13816 13816 F DEBUG   : pid: 11603, tid: 13681, name: qtMainLoopThrea  >>> org.cagnulen.qdomyoszwift <<<
01-07 19:58:54.284 13816 13816 F DEBUG   :       #00 pc 0000000000030a2c  /data/app/~~y2Y3DJj-kSoBO_asmatefw==/org.cagnulen.qdomyoszwift-DLQdaPe0iSQYdU5OlzLFIw==/lib/arm64/libQt5Bluetooth_arm64-v8a.so (QLowEnergyService::discoverDetails()+8) (BuildId: 0d8f92d417b7057c0df09c6a2c0f77ff42552de7)
01-07 19:58:54.284 13816 13816 F DEBUG   :       #01 pc 00000000004d707c  /data/app/~~y2Y3DJj-kSoBO_asmatefw==/org.cagnulen.qdomyoszwift-DLQdaPe0iSQYdU5OlzLFIw==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (kingsmithr2treadmill::serviceScanDone()+500) (BuildId: d5d1726577f8c401da36e9170ea6faf504d1997d)
01-07 19:58:54.284 13816 13816 F DEBUG   :       #02 pc 0000000000213418  /data/app/~~y2Y3DJj-kSoBO_asmatefw==/org.cagnulen.qdomyoszwift-DLQdaPe0iSQYdU5OlzLFIw==/lib/arm64/libQt5Core_arm64-v8a.so (BuildId: a320abe144862b516fe0a5f00a65f7d8897dc612)
01-07 19:58:54.284 13816 13816 F DEBUG   :       #03 pc 000000000005c090  /data/app/~~y2Y3DJj-kSoBO_asmatefw==/org.cagnulen.qdomyoszwift-DLQdaPe0iSQYdU5OlzLFIw==/lib/arm64/libQt5Bluetooth_arm64-v8a.so (BuildId: 0d8f92d417b7057c0df09c6a2c0f77ff42552de7)
01-07 19:58:54.304  3169 13820 W ActivityTaskManager:   Force finishing activity org.cagnulen.qdomyoszwift/org.qtproject.qt5.android.bindings.QtActivity

```

**Comment by cagnulein** [comment]
yeah we need to calculate the cypher key, could you please collect a debug
log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 20:02 panaut0lordv ***@***.***>
ha scritto:

**Comment by panaut0lordv** [comment]
Here you are.
[debug-Wed_Jan_10_10_28_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13885817/debug-Wed_Jan_10_10_28_32_2024.log)

**Comment by cagnulein** [comment]
thanks, can you try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/7473033465 (in 30 minutes) and send me a debug log if it still doesn't work. thanks!

**Comment by panaut0lordv** [comment]
That seems to work fine, both reported speed as well as controls (start, stop, speed).

Thank you for your effort Roberto!

**Comment by cagnulein** [comment]
amazing! i will upload this soon in the play store, beta channel!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 13:21 panaut0lordv ***@***.***>
ha scritto:
