### ISSUE TITLE
Resistance issues with Echelon bike and Zwift

### ISSUE THREAD

**Issue by Shaneymack** [cagnulein/qdomyos-zwift#1959]
**Describe the bug**
Hi Roberto,
This is to continue the email chain we have ongoing. Issues with the resistance. It either sits at 1 and doesn’t move or too high around 21. It does not move and does not allow me to change it. Cadence can be 120 or 60 and there is no change in resistance. I’m quit positive it’s something I don’t have correct in the settings. I have a brand new echelon 5s bike.  [
[debug-Fri_Jan_5_16_07_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13847832/debug-Fri_Jan_5_16_07_22_2024.log)
[debug-Fri_Jan_5_16_15_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13847833/debug-Fri_Jan_5_16_15_39_2024.log)
](url)
**To Reproduce**

**Expected behavior**
The day before It worked one time. The interval was let’s say 180 watts and if my cadence was slow the resistance would be high and if the cadence was fast, the resistance would be lower. This would help keep consistent watt output. 
**Screenshots**
![IMG_3156](https://github.com/cagnulein/qdomyos-zwift/assets/155787820/0adb180b-ddc1-4196-ae3b-8fe9b0795218)
![IMG_3155](https://github.com/cagnulein/qdomyos-zwift/assets/155787820/c5330f65-f8cd-4b3e-8e6f-14e21e98da57)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. 
 - 
 iPad Pro or Apple TV. I have zwift on both 

**Smartphone (please complete the following information):**
 - 
iPhone 14 Pro Max 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
> debug-Fri_Jan_5_16_07_22_2024.log

in this log the resistance is change accordingly to the zwift requests

```
Fri Jan 5 16:08:42 2024 1704488922875 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 19"
Fri Jan 5 16:08:43 2024 1704488923875 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 21"
Fri Jan 5 16:08:52 2024 1704488932875 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 22"
Fri Jan 5 16:08:53 2024 1704488933875 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 20"
Fri Jan 5 16:09:15 2024 1704488955875 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 21"
Fri Jan 5 16:13:01 2024 1704489181873 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 21"
```

it's a free ride. if it's too hard for you you have 3 methods to make it easy:
1. decrease the difficulty on zwift
2. decrease the zwift resistance offset on qz
3. decrease the gears in qz in real time

**Comment by cagnulein** [comment]
also I can't see if this was a free ride or a workout but remember to enable the zwift erg workout setting if it's a workout.
if you want, do a workout with the zwift erg setting enabled and if you have issues put the debug log and I can check it fo sure.
Let me know

**Comment by Shaneymack** [comment]
When I try to change the resistance, it goes right back to where it was. It does not allow me to. Let me try later and do another log

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
yes it's supposed to do so, you have to use the gear tiles for changing it realtime

**Comment by Shaneymack** [comment]
Ok I turned gears tile on. I’ll see if that works.

How do I get the resistance to change when the cadence gets faster or slower ? That is not working

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
you have to enable the zwift erg setting and you have to do a WORKOUT on
zwift, not a free ride or a race

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 14:04 Shaneymack ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
did you try?

**Comment by Shaneymack** [comment]
I’m not at home right now. I will as soon as I get home. I’ll get back to you asap

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shaneymack** [comment]
I just tried and it is not working. I did a workout and it’s just stuck in 21 resistance. I toggled ERG mode on and off and it did nothing. I turned the gear tile on and I do not see it….
here is the log

[debug-Sat_Jan_6_12_57_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13850696/debug-Sat_Jan_6_12_57_35_2024.log)

**Comment by cagnulein** [comment]
when you change the erg mode you have to restart qz.
in this log it starts disabled, do this again.
same thing for the gears.
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 19:08 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
Just to be clear on the process to do a workout in erg mode

Start the bike
Start qz on the phone
Start qz on the watch
Start zwift
Start workout
Restart qz  on phone
Restart qz on watch also ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
nope once you have the right setting you don't need to restart anything.
only when you change a setting you need to restart qz on the phone

so assuming you are the setting that you need just do

Start the bike
Start qz on the phone
Start qz on the watch
Start zwift
Start workout




Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 19:19 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
I see the gears now but the resistance is not changing in ERG mode. If I slow cadence or speed up cadence resistance stays the same and I’m not hitting target watts. 

Here is the log 

[debug-Sat_Jan_6_17_24_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13851574/debug-Sat_Jan_6_17_24_55_2024.log)

**Comment by cagnulein** [comment]
In this log the zwift erg setting is disabled at the startup of the app. As
I said enable it. Restart qz and then go on zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 23:39 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
Clearly i am not understanding what you mean here. There is an Erg setting to enable in QZ? Because erg is enabled on zwift and I was doing a workout.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
yes the is one must be enabled in your case

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/c0f231c2-d512-4001-a276-1ddb0824b8b6)

**Comment by Shaneymack** [comment]
A picture is worth 1000 words…..perfect I’ll try that.
Please see attached picture. I see you have “speed calculates on power” turned on. Should I as well?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
it's not mandatory. with this enable qz will estimate speed and distance in
a real way, otherwise qz uses the speed from the bike that it's just based
on cadence (completely no sense :) )

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 14:10 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
Ok I will turn it on. Do you have a page that goes through every setting and which one to turn on/off ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
every setting has a description in the app. and most of them are very
subjective. you can also check this
https://robertoviola.cloud/qz-fitness-app-guide/


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 14:13 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
This is very helpful! I will read this entire page. I will let you know if erg works soon! Thanks again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Shaneymack** [comment]
So the Erg is working now! Thanks. Curious as to why my KM/h are so low though. If I’m pedaling at 90 cadence I’m only going 14km/h….seems very low.
Also, when I do a free ride without erg, will the bike change resistance based on hills ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
because zwift calculates speed based on wattage, cadence is useless, you
have to focus only on power

for free ride you have to disable that qz setting that i show you in the
picture

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 18:55 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
Ok I will disable it and try a free ride. Will it still change resistance based on elevation changes ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
sure!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 19:18 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
Any idea why the resistance will no longer connect? Everything else connects to my phone except the resistance 

[Uploading debug-Sun_Jan_7_18_07_11_2024.log…]()

**Comment by cagnulein** [comment]
on zwift? just unpair them all and it will appear , it's a classic zwift bug

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 00:12 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
OK. I unpaired and reset everyhting 3x and nothing changed. I will try again when i get home from work today. Thank you. Shane WiedowOn Jan 7, 2024, at 11:28 PM, Roberto Viola ***@***.***> wrote:﻿
on zwift? just unpair them all and it will appear , it's a classic zwift bug



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 8 gen 2024 alle 00:12 Shaneymack ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
only the resistance? do you see the metrics on zwift for the other metrics? are you using the phone name or the wahoo one on zwift? anyway it does this sometimes zwift, i usually unpair them and i'm ready to go. try to reboot also the devices, maybe something glitched

**Comment by Shaneymack** [comment]
All the metrics connect to my iPhone except heart rate which is Apple Watch Ultra. All metric connected with no issue except resistance. I unpaired multiple times and reset the bike, phone app, watch app and zwift multiple times with no change. I will try again tonight.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
Just to understand it correctly: do you see the resistance on QZ?

**Comment by Shaneymack** [comment]
I see the resistance, it just wont connect. It stays orange. Shane WiedowOn Jan 8, 2024, at 11:47 AM, Roberto Viola ***@***.***> wrote:﻿
Just to understand it correctly: do you see the resistance on QZ?

**Comment by cagnulein** [comment]
ok so you see the correct resistance value in qz but you can't select in
zwift right? if so ok ì understood it correctly.
did you change some other settings?
anyway it should be only a zwift issue if it worked before.
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 18:14 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
I did not change any setting that im aware of. I only turned the ERG mode off as you suggested to do for a free ride. I included a log above in the post about this. The resistance was sitting at 1 in QZ. Shane WiedowOn Jan 8, 2024, at 12:42 PM, Roberto Viola ***@***.***> wrote:﻿
ok so you see the correct resistance value in qz but you can't select in

zwift right? if so ok ì understood it correctly.

did you change some other settings?

anyway it should be only a zwift issue if it worked before.

let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 8 gen 2024 alle 18:14 Shaneymack ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
the last log was corrupted, you have to wait the finish of the upload
before pushing commit

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 18:45 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
I tried again but It won’t allow me to upload it as it’s 32 mb- 25mb max

**Comment by cagnulein** [comment]
compress it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 18:56 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
So I tried again and this time the resistance recognized my iPhone. Now when I’m in zwift doing a free ride I’m back to one of the original problems where the resistance is stuck at 1. The zwift offset has not been changed it is still at 16. 
here is the log

[debug-Mon_Jan_8_20_31_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13868407/debug-Mon_Jan_8_20_31_49_2024.log)

**Comment by cagnulein** [comment]
this log has the zwift erg setting enabled. that's the issue. you have to
disable and restart qz to do a free ride

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle 04:15 Shaneymack ***@***.***>
ha scritto:

**Comment by Shaneymack** [comment]
I had turned this off when i had the issues with the resistance on Sunday….does this go back on automatically? Is this a setting I should be checking each time I use zwift to make sure it’s in the position I need for that day?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
no it doesn't go back automatically. It seems that you changed then again or maybe you loaded the setting back or similar. Anyway that must be off for free ride. So just check it before riding

**Comment by cagnulein** [comment]
@Shaneymack are we ok now?

**Comment by Shaneymack** [comment]
Hi Robert,

I did a free ride and it seems to be good.  Resistance went up and down with the hills.

THANK YOU. 🙏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
