### ISSUE TITLE
Remaining time in training block

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#196]
If you run or bike in XML training blocks it would be nice to be able to see how much time is left in the current block.
Maybe a visual element could be added or a Tile?

**Comment by cagnulein** [comment]
yes my GF asks me this too :D

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 mar 2021 alle ore 15:22 ErnieV <notifications@github.com>
ha scritto:

**Comment by ErnieV** [comment]
You should listen to her 👍 

I don't know if this is difficult to achieve and I can imagine you have more important things to do.

So if you ever come around to it, let me know. I'll gladly test it for you.

There is also a bug with the Calories sometimes exploding to 40000+ while running. I'm still trying to find out what is happing, so I can reproduce. Could be the Domyos Bike and Threadmill are to close together in the same room.

**Comment by cagnulein** [comment]
If you have the debug enabled, just send me the file, it should be easy to
fix it :)


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 mar 2021 alle ore 15:37 ErnieV <notifications@github.com>
ha scritto:

**Comment by ErnieV** [comment]
I have turned it on. Will see when it happens again!

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
Argh i forgot about this! I need to add this!
