### ISSUE TITLE
[REQ]That the treadmill always has a minimum slope

### ISSUE THREAD

**Issue by Eduardote80** [cagnulein/qdomyos-zwift#1960]
It would be nice to be able to set the treadmill to always have a minimum slope even if Zwift is at 0% or negative slope values. That is, I can say never go below 1%.

**Comment by cagnulein** [comment]
done @Eduardote80  https://github.com/cagnulein/qdomyos-zwift/actions/runs/7437118233

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link. In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/7437169290

**Comment by Eduardote80** [comment]
So should I uninstall the version that I have on my phone, click on
the link and click where it says android build?
Will that download an arvmchivon to install or does it install it directly?

**Comment by cagnulein** [comment]
> So should I uninstall the version that I have on my phone, click on the link and click where it says android build?

yes you have to uninstall it. then wait for the build finish (usually 40 minutes) and you will see the android build in the bottom

**Comment by cagnulein** [comment]
in this build i added 2 new settings in the treadmill settings in order to override the max and min inclination

**Comment by Eduardote80** [comment]
Ok, then when I install it I'll tell you how it goes. If it works, it
would be good if it lasted a little more than 15 minutes so I could
train at least an hour with it. but if it is only for so it works ok.

**Comment by cagnulein** [comment]
as I said I can unlock it then with your email address

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle ore 10:01 Eduardote80 <
***@***.***> ha scritto:

> Ok, then when I install it I'll tell you how it goes. If it works, it
> would be good if it lasted a little more than 15 minutes so I could
> train at least an hour with it. but if it is only for so it works ok.
>
>

**Comment by Eduardote80** [comment]
Perfecto

**Comment by Eduardote80** [comment]
Is it possible there was some error in my loading? too many symbols in
red and I don't see what to download

**Comment by cagnulein** [comment]
hold on, build fails. new buld
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7437545810
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle ore 11:00 Eduardote80 <
***@***.***> ha scritto:

> Is it possible there was some error in my loading? too many symbols in
> red and I don't see what to download
>
>
> El dom, 7 ene 2024, 10:02, Roberto Viola ***@***.***>
> escribió:
>
> > as I said I can unlock it then with your email address
> >
> > Roberto Viola
> > Software engineer and open source enthusiast
> > http://robertoviola.cloud
> >
> >
> >
> > Il giorno dom 7 gen 2024 alle ore 10:01 Eduardote80 <
> > ***@***.***> ha scritto:
> >
> > > Ok, then when I install it I'll tell you how it goes. If it works, it
> > > would be good if it lasted a little more than 15 minutes so I could
> > > train at least an hour with it. but if it is only for so it works ok.
> > >
> > >

**Comment by Eduardote80** [comment]
It seems that the compilation was successful, but I cannot find the
file to download

**Comment by cagnulein** [comment]
here
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7437545810/artifacts/1152414515

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle ore 12:10 Eduardote80 <
***@***.***> ha scritto:

> It seems that the compilation was successful, but I cannot find the
> file to download
>
>
> El dom, 7 ene 2024, 11:12, Roberto Viola ***@***.***>
> escribió:
>
> > hold on, build fails. new buld
> > https://github.com/cagnulein/qdomyos-zwift/actions/runs/7437545810
> > Roberto Viola
> > Software engineer and open source enthusiast
> > http://robertoviola.cloud
> >
> >
> >
> > Il giorno dom 7 gen 2024 alle ore 11:00 Eduardote80 <
> > ***@***.***> ha scritto:
> >
> > > Is it possible there was some error in my loading? too many symbols in
> > > red and I don't see what to download
> > >
> > >
> > > El dom, 7 ene 2024, 10:02, Roberto Viola ***@***.***>
> > > escribió:
> > >
> > > > as I said I can unlock it then with your email address
> > > >
> > > > Roberto Viola
> > > > Software engineer and open source enthusiast
> > > > http://robertoviola.cloud
> > > >
> > > >
> > > >
> > > > Il giorno dom 7 gen 2024 alle ore 10:01 Eduardote80 <
> > > > ***@***.***> ha scritto:
> > > >
> > > > > Ok, then when I install it I'll tell you how it goes. If it works,
> > it
> > > > > would be good if it lasted a little more than 15 minutes so I
> could
> > > > > train at least an hour with it. but if it is only for so it works
> > ok.
> > > > >
> > > > >

**Comment by Eduardote80** [comment]
Hello, I have installed the application.
On the one hand, I think it takes longer to connect to the tape and
also for the phone to be located on Zwift.
and now the automatic lift does not work.
I want my treadmill to move in the values ​​of 1 to 10% inclination.
So that Zwift only moves at these values, is it correctly configured
like this?

**Comment by cagnulein** [comment]
you have to set again the zwift credentials in qz.

for the inclination set the new min inclination setting to 1 and the max to 10

press ok on each line and restart qz

**Comment by Eduardote80** [comment]
I did these steps, but auto tilt no longer works. Even if I raise it
to lower it to what zwift says, it doesn't do it.

**Comment by cagnulein** [comment]
provide me a debug log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

it could be that the build here has something wrong with the zwift api. in
case i will have to fix or push it directly to google

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 14:40 Eduardote80 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
you have to attach it in github directly

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 15:04 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
[debug-Sun_Jan_7_14_36_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13853779/debug-Sun_Jan_7_14_36_26_2024.log)

**Comment by cagnulein** [comment]
yes it's an issue of this build. so install again the version from the store and i will push it to the store in the next days!

**Comment by Eduardote80** [comment]
Thanks, I will.

**Comment by cagnulein** [comment]
2.16.31 uploaded.
You will see this in the next days!
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle ore 15:23 Eduardote80 <
***@***.***> ha scritto:

**Comment by Eduardote80** [comment]
Ok

**Comment by Eduardote80** [comment]
Hello, how are you, I'm eager to try that update, in the meantime I'll
tell you some things I've tried.

I'll tell you in what order I've been doing things and the result or problem.

I turn on the treadmill, open qz, connect to zwitf, open a world and
start running and the auto incline works.
But if I load a zwo program in qz, the speed works but the zwift world
tilt stops working. I don't know if this is normal, meaning that if
you load a zwo it forgets about the inclination of the world and only
takes into account what is in the zwo.

Today I loaded a zwo en qz program on my phone, connected with zwift
on mac, and started running, so far everything is fine. I left zwift
in the background while watching the movie. I changed the screen twice
to see if Zwift was still working and if it was still ok, but... when
I finished the training, the Zwift dummy was stopped, it had stopped
when it had gone less than 2km.

On the other hand, I wanted to know if these things are possible:
Load a gpx route at the same time, so that it takes the slope and at
the same time load a zwo so that it takes the speed, time and
distance...

I imagine that if I load a gpx, when the slope is 0% I would have the
same problem as with zwift, so I would be interested in the option
that I mentioned to always have a minimum slope, not only is that
option for zwift but also for the gpx, right?

Conclusion: I don't know if it is possible for the zwo to take the
distance, speed, time... and the gpx or the inclination from the
zwift.

And on the other hand, I have tried to connect the Zwift runpod
pedometer again, I have tested it as a cadence sensor and as a power
sensor. and although in the mosaics if I move it it gives movement
values, when I try to locate it in zwift it does not find it as a
runpod or as a phone...

thank you.

**Comment by Eduardote80** [comment]
Another thing... is it possible that in beta version 2.16.30, the map
and gpx do not work? I have tried to try some of the things I
mentioned, but I can't get the map to work. It says that the gpx has
been loaded correctly but when you click start, you cannot see the
map. I thought that igaul was a thing of my gpx, but I see what
happens to me with all the ones that are installed in the qz app.

**Comment by cagnulein** [comment]
i will check it, anyway you can't actually do zwift with auto inclination and gpx, or one or another :) 

for the run pod open another ticket with a debug log, don't mix issue please.

for the gpx i will show you a video

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/assets/48216/9bff4db6-44c1-46f1-ba25-f7c29a1b2d78

**Comment by cagnulein** [comment]
> I don't want to use zwift and gpx, I'm wondering if it's possible to
> 
> use a gpx with incline and a zwo without incline in qz, without any
> 
> zwift. and between zwo and gpz have automatic inclination and speed.
> 


why don't you simply write the xml file of qz with speed and incline? it will be the perfection 
> 
> 
> On the other hand, what you have sent me in the video, I did try it
> 
> the day I bought the app, and it worked, but I don't know if since I
> 
> updated to the beta it no longer works with any gpx
> 
> 

show me what you are doing in a video.

**Comment by Eduardote80** [comment]
Does he return all the emails with the video, does he say that all
sizes are large?
but I tell you what I do:
I synchronize qz with treadmill,
pulse "open gpx"
I select one from the list or search for another by clicking on "other folders",
I touch on the name and it turns green,
again pulse in him,
a message says that it has been loaded successfully, and to press start,
pulse start,
but then I hit the map button and it doesn't respond.

I wanted to try uninstalling the beta version, to try to see if it was
a beta thing, since the day I bought it it worked, but I didn't want
to lose all the settings of the app... if it is the solution I would
do it, but yes It's doing it and it's not just anything...

**Comment by cagnulein** [comment]
upload a debug log so, so i can check what you are doing wrong

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 21:53 Eduardote80 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
you have to upload from github otherwise i can't see it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 22:06 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
[debug-Mon_Jan_8_21_59_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866294/debug-Mon_Jan_8_21_59_54_2024.log)

**Comment by cagnulein** [comment]
ok im going to bed. i will check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 22:13 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
Ok buenas noches, he probado a desinstalar y volver a instalar la versión
pública, y funcionaba. Después he vuelto a probar la versión beta y parece
que funciona otra vez. Mañana seguiré probando.
Gracias.

**Comment by cagnulein** [comment]
> [debug-Mon_Jan_8_21_59_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866294/debug-Mon_Jan_8_21_59_54_2024.log)

in this log you are not opening a gpx file. i need one where you're simulating the map issue. thanks

**Comment by Eduardote80** [comment]
I already solved it, uninstall and install again and it works now.

I just saw the new update on Google, I want to try it this afternoon.

But I have a question, the incline values ​​of the new parameter
default to -100 and 100. If I want my treadmill to always be between
1% and 10%, should I put 1 and 10?

thank you

**Comment by cagnulein** [comment]
> I just saw the new update on Google, I want to try it this afternoon.

great!



> If I want my treadmill to always be between 1% and 10%, should I put 1 and 10?

yes exactly!

**Comment by Eduardote80** [comment]
hello! I have tried the new update and it seems to work, the tape
remains between 1-10% even if zwift or gpx give 0% gradient or
negative values!!
I am very happy, thank you very much...

Now that I have the incline problem solved, I would like zwift to
adjust my speed...
I have created a zwo with zwiftworkout.com, but the speed does not
change... if I open the zwo as text, I see different parameters of
duration, power, etc...
Should I change "power" to another parameter? What should I put? To
test I put "speed" but then nothing comes out, I empty the program.
For me it is easier to work with rhythm or speed than with power.

thank you very much again

**Comment by cagnulein** [comment]
@Eduardote80 share a debug log and I will check it, but I strongly suggest to use the xml format like this https://github.com/cagnulein/qdomyos-zwift/blob/master/train-programs-examples/calorie-barbara.xml

**Comment by Eduardote80** [comment]
The xml could be fine, but for my workouts I combine distances,
speeds, rhythms, duration... that's why I can create it with
zwiftworkout and then modify the "power" field in the text editor with
a search and replace... it would be fabulous.
I attach a screenshot of the zwo that I am carrying, to see if it
could be adapted as I say in some way.

**Comment by cagnulein** [comment]
you have to attach the files from github otherwise i can't see them
also the zwo format is not something that we can change.
instead in the xml files there are dozens of attributes! distance, speed
time whatever you want it's already available!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 17:49 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
I finished the first training after the update, everything seemed to
be going well, the automatic elevation worked, but after 15-18 minutes
Zwift lost the connection with QZ. The other day the same thing
happened to me. Heart rate monitor without connection and the doll did
not move, everything stopped. I have continued training with qz.
I send the latest debug that is in the folder you told me.

**Comment by cagnulein** [comment]
i don't see the debug log, you have to upload on github.

where zwift runs? where qz?

**Comment by Eduardote80** [comment]
[debug-Wed_Jan_10_18_01_15_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13891844/debug-Wed_Jan_10_18_01_15_2024.log)

**Comment by Eduardote80** [comment]
Zwift en mac, qz en android

**Comment by cagnulein** [comment]
are you using the bluetooth name of the phone in zwift or the wahoo one?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 20:00 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
El de el teléfono... Alguna vez me sale wahoo kicker y wahoo no sé qué
más... Pero nunca lo selecciono.

**Comment by cagnulein** [comment]
the 15 minutes issue it's a classic of some android. use the wahoo one and
you should fix it
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 20:38 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
A veces me salen dos wahoo, un wahookicler y otro que no recuerdo, pero no
siempre salen cuando busco dispositivos..
Si no sale¿Hay que activar algo? Y si sale¿Cuál debo activar?

**Comment by cagnulein** [comment]
nope, you don't have to enable nothing, simply search for them: select
wahoo tread or even wahoo kickr

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 20:58 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
he probado a buscar dispositivos wahoo pero… después de un buen rato no aparecen…

Ahora estoy probando si poniendo qz en androir y zwift en otro android si también se desconecta


Con los últimos ejemplos de xml que me has mandado… veo buenas opciones, en caso de que sea por distancia y no duración,¿ cual es el parámetro? ¿“distance”?

**Comment by cagnulein** [comment]
use qz and zwift on the same device. just enable the android notification
icon setting in  the experimental settings.

the distance tag is distance :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 21:53 Eduardote80 ***@***.***>
ha scritto:

> he probado a buscar dispositivos wahoo pero… después de un buen rato no
> aparecen…
>
> Ahora estoy probando si poniendo qz en androir y zwift en otro android si
> también se desconecta
>
>
> Con los últimos ejemplos de xml que me has mandado… veo buenas opciones,
> en caso de que sea por distancia y no duración,¿ cual es el parámetro?
> ¿“distance”?
>

**Comment by Eduardote80** [comment]
Ok gracias, esta tarde probaré de nuevo, pero creo que un día probé a poner
qz y zwift en mi teléfono y zwift no lo encontraba.

**Comment by cagnulein** [comment]
you have to enable the android notification icon and select the wahoo
device on zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 05:40 Eduardote80 ***@***.***>
ha scritto:

> Ok gracias, esta tarde probaré de nuevo, pero creo que un día probé a
> poner
> qz y zwift en mi teléfono y zwift no lo encontraba.
>
>
> El jue, 11 ene 2024, 5:36, Roberto Viola ***@***.***>
> escribió:
>
> > use qz and zwift on the same device. just enable the android
> notification
> > icon setting in the experimental settings.
> >
> > the distance tag is distance :)
> >
> > Roberto Viola
> > Software engineer and open source enthusiast
> > http://robertoviola.cloud
> >
> >
> >
> > Il giorno mer 10 gen 2024 alle 21:53 Eduardote80 ***@***.***>
> > ha scritto:
> >
> > > he probado a buscar dispositivos wahoo pero… después de un buen rato
> no
> > > aparecen…
> > >
> > > Ahora estoy probando si poniendo qz en androir y zwift en otro android
> > si
> > > también se desconecta
> > >
> > >
> > > Con los últimos ejemplos de xml que me has mandado… veo buenas
> opciones,
> > > en caso de que sea por distancia y no duración,¿ cual es el parámetro?
> > > ¿“distance”?
> > >

**Comment by Eduardote80** [comment]
Ok, esta tarde lo pruebo

**Comment by Eduardote80** [comment]
Hola, estoy haciendo alguna prueba con los XML, y tal vez no sea tan
complicado planificar un entrenamiento como yo pensaba, y además me puede
dar mas parámetros... ¿Donde podría ver un listado de parametros que puedo
usar?
Por saber si por ejemplo puedo poner un random de inclinación o velocidad
entre algunos valores o no sé.. ver qué opciones hay.

**Comment by cagnulein** [comment]
check here
https://robertoviola.cloud/2023/11/20/exploring-the-versatility-of-qz-app-your-gateway-to-a-tailored-fitness-experience/

and in case you need something new let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 09:25 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
Hola he probado a poner en el mismo teléfono qz y zwift y a los 10' el
muñeco deja de moverse, pierde conexión.

**Comment by cagnulein** [comment]
did you enable the android notification icon setting in the experimental
settings as I said and restarted qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle ore 16:26 Eduardote80 <
***@***.***> ha scritto:

**Comment by Eduardote80** [comment]
Si si , está activado

**Comment by cagnulein** [comment]
it seems that your phone doesn't have enough RAM so, which phone is it?
my Pixel 6a can achieve both zwift and qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle ore 16:37 Eduardote80 <
***@***.***> ha scritto:

**Comment by Eduardote80** [comment]
Oh! Es un Redmi 10 2022

Probare otras cosas luego...

Por otro lado... He probado un XML en qz.. pero no sé si he metido bien el
parámetro distancia, el primer bloque que va por tiempo lo hace pero los
siguientes que son distancia se los salta y va al ultimo bloque que es por
duración también.

**Comment by cagnulein** [comment]
always attach the xml and debug log if you have an issue otherwise it's impossible to help. thanks

**Comment by Eduardote80** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<rows>
    <row duration="00:00:30" speed="10.43" inclination="1.111" forcespeed="1"/>
    <row distance="180" speed="10.69" inclination="1.578" forcespeed="1"/>
<row distance="100" speed="12" inclination="2.23" forcespeed="1"/>
    <row distance="200" speed="13.265" inclination="1.623" forcespeed="1"/>
    <row duration="00:00:30" speed="7.6" inclination="0.8" forcespeed="1"/>

</rows>

**Comment by Eduardote80** [comment]
Este sería el XML 

<?xml version="1.0" encoding="UTF-8"?>

<rows>
    <row duration="00:00:30" speed="10.43" inclination="1.111" forcespeed="1"/>
    <row distance="180" speed="10.69" inclination="1.578" forcespeed="1"/>
<row distance="100" speed="12" inclination="2.23" forcespeed="1"/>
    <row distance="200" speed="13.265" inclination="1.623" forcespeed="1"/>
    <row duration="00:00:30" speed="7.6" inclination="0.8" forcespeed="1"/>

</rows>

**Comment by cagnulein** [comment]
i don't see anything

**Comment by Eduardote80** [comment]
`<?xml` version="1.0" encoding="UTF-8"?>

<rows>
    <row duration="00:00:30" speed="10.43" inclination="1.111" forcespeed="1"/>
    <row distance="180" speed="10.69" inclination="1.578" forcespeed="1"/>
<row distance="100" speed="12" inclination="2.23" forcespeed="1"/>
    <row distance="200" speed="13.265" inclination="1.623" forcespeed="1"/>
    <row duration="00:00:30" speed="7.6" inclination="0.8" forcespeed="1"/>

</rows>`

**Comment by Eduardote80** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<rows>
    <row duration="00:00:30" speed="10.43" inclination="1.111"
forcespeed="1"/>
    <row distance="180" speed="10.69" inclination="1.578" forcespeed="1"/>
<row distance="100" speed="12" inclination="2.23" forcespeed="1"/>
    <row distance="200" speed="13.265" inclination="1.623" forcespeed="1"/>
    <row duration="00:00:30" speed="7.6" inclination="0.8" forcespeed="1"/>

</rows>

**Comment by cagnulein** [comment]
distance is in km so in your case put  0.18 and 0.1 and 0.2

**Comment by Eduardote80** [comment]
Probé a escribir esto; y sigue pasando que se salta las lineas que van por
distancia

<?xml version="1.0" encoding="UTF-8"?>

<rows>
    <row duration="00:00:30" speed="10.43" inclination="1.1"
forcespeed="1"/>
    <row distance="0.180" speed="10.69" inclination="1.578" forcespeed="1"/>
<row distance="0.100" speed="12" inclination="2.23" forcespeed="1"/>
    <row distance="0.200" speed="13.265" inclination="1.623"
forcespeed="1"/>
    <row duration="00:00:30" speed="7.6" inclination="0.8" forcespeed="1"/>

</rows>

**Comment by Eduardote80** [comment]
[Uploading debug-Thu_Jan_11_18_45_22_2024.log…]()

**Comment by cagnulein** [comment]
@Eduardote80 you have to wait the finish of the upload before press the button of comment.
anyway tomorrow i will check the xml file on my side

**Comment by Eduardote80** [comment]
[debug-Thu_Jan_11_18_45_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13906734/debug-Thu_Jan_11_18_45_22_2024.log)

**Comment by cagnulein** [comment]
good news @Eduardote80 fixed! it was an issue where training program has mixed distance and time lines. You will have it in the next one, or you can use the trial apk if you want to test this out!

**Comment by Eduardote80** [comment]
Genial! Hoy probaré a entrenar con el XML que me hice ayer con duración y a
ver si en los próximos días está ya la actualización

**Comment by cagnulein** [comment]
ok i will push it to the store in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 gen 2024 alle ore 09:04 Eduardote80 <
***@***.***> ha scritto:

**Comment by Eduardote80** [comment]
Hola , ¿Que tal? Hoy he probado la nueva actualización, y he probado con el
XML poniendo el parámetro distancia.
Pero tengo que hacer alguna prueba más , ya que algo ha fallado.
El calentamiento lo he puesto por varios tramos por duración con cambios de
velocidad e inclinación.
Después he puesto una cambios de velocidad pero por distancia, pero no sé
si ha sido por tocar la velocidad en la cinta de correr o al cambiar al
descanso que estaba de nuevo en duración, pero ya es como si no leyera el
XML. Incluso cogía pendiente de zwift.
Haré algunas pruebas más con otros XML y te comentaré.

**Comment by cagnulein** [comment]
ok in case remember always to share a debug log

**Comment by Eduardote80** [comment]
Hola he hecho una nueva prueba, empiezo XML con duración, luego cambio a distancia y bien, pero cuando vuelvo a cambiar a duración, se queda en la misma velocidad y ya no cambia...
[debug-Mon_Jan_22_21_28_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14015203/debug-Mon_Jan_22_21_28_47_2024.log)

**Comment by cagnulein** [comment]
ok share also the xml that you used

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 21:37 Eduardote80 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
you have to upload on github :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 22:00 Eduardote80 ***@***.***>
ha scritto:

**Comment by Eduardote80** [comment]
El XML no me deja subirlo por ahi

**Comment by Eduardote80** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<rows>
<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>

<row distance="0.100" speed="15.4" inclination="2.5" forcespeed="1"/>
<row distance="0.150" speed="15.6" inclination="2" forcespeed="1"/>

<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>


</rows>

**Comment by cagnulein** [comment]
zip it

**Comment by Eduardote80** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<rows>
`<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>

<row distance="0.100" speed="15.4" inclination="2.5" forcespeed="1"/>
<row distance="0.150" speed="15.6" inclination="2" forcespeed="1"/>

<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>


</rows>
`

**Comment by Eduardote80** [comment]
<rows>
<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>

<row distance="0.100" speed="15.4" inclination="2.5" forcespeed="1"/>
<row distance="0.150" speed="15.6" inclination="2" forcespeed="1"/>

<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>


</rows>

**Comment by Eduardote80** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<rows>
<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>

<row distance="0.100" speed="15.4" inclination="2.5" forcespeed="1"/>
<row distance="0.150" speed="15.6" inclination="2" forcespeed="1"/>

<row duration="00:00:20" speed="9.7" inclination="1" forcespeed="1"/>
<row duration="00:00:20" speed="9.9" inclination="1.5" forcespeed="1"/>


</rows>
![Screenshot_2024-01-22-22-09-15-535_com android chrome](https://github.com/cagnulein/qdomyos-zwift/assets/155820578/d3f14727-1187-4c50-93f6-bf0f5d2c0964)

**Comment by Eduardote80** [comment]
![Screenshot_2024-01-22-22-09-15-535_com android chrome](https://github.com/cagnulein/qdomyos-zwift/assets/155820578/0c92a63e-efa8-474d-96c7-6dfb04ccbc16)

**Comment by Eduardote80** [comment]
[prueba distacia.zip](https://github.com/cagnulein/qdomyos-zwift/files/14015491/prueba.distacia.zip)

**Comment by cagnulein** [comment]
great! addressed and patched also this! it will be in the 2.16.38 and above! let me know!

**Comment by Eduardote80** [comment]
Ok, perfecto.Espero con ganas la nueva actualización.
