### ISSUE TITLE
[BUG]proform 12.0

### ISSUE THREAD

**Issue by Bpleic** [cagnulein/qdomyos-zwift#1961]
**Describe the bug**

qz app correctly installed on the treadmill.  Qz app on mobile device with android 14 beta installed.  I don't have any data on mobile when I start the tape it's all 0.00
**To Reproduce**

**Expected behavior**

**Screenshots**
![20240106_115158](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/35c2d773-f0ca-42d1-a177-90c672f22155)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
![20240106_115205](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/6b78dede-9012-4314-801a-595a1670acd9)
![Screenshot_20240106_174225](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/3d3334f1-0125-44d5-b9e1-4ff15eb86d31)
![20240106_174237](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/1b602d95-336c-4ce3-8105-fed97bad6013)
![Screenshot_20240106_195215_Settings](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/16fc3b11-7213-4f1f-961d-0465ff57ad7d)

**Comment by cagnulein** [comment]
hi @Bpleic i don't see the debug log

**Comment by Bpleic** [comment]
[debug-Sat_Jan_6_19_54_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13850920/debug-Sat_Jan_6_19_54_31_2024.log)

**Comment by Bpleic** [comment]
Here is.....sorry

**Comment by cagnulein** [comment]
ok the problem seems to be the ifit log file. did you already try using the c1750 in the companion and restart the treadmill?

**Comment by Bpleic** [comment]
I did, but can I try again, to choose c1750 or c1750 2021?

**Comment by cagnulein** [comment]
c1750
also try the T75s

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 20:18 Bpleic ***@***.***> ha
scritto:

**Comment by Bpleic** [comment]
![Uploading 20240106_203105.jpg…]()
C1750

**Comment by cagnulein** [comment]
@Bpleic you have to wait the finish of the upload before pushing comment

**Comment by Bpleic** [comment]
![20240106_203105](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/635555ea-f41d-4218-ab7a-21eafa2c1088)
C1750 not worked

**Comment by Bpleic** [comment]
![Screenshot_20240106_203615](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/83883f8a-e5ce-4307-a35b-4349b25a77d6)
![20240106_203700](https://github.com/cagnulein/qdomyos-zwift/assets/155844546/60903e15-262e-4f37-afa2-ae826c7402b9)
Not work on the t75s

**Comment by cagnulein** [comment]
sorry @Bpleic i missed the notification. so we have to procede in the gran tour pro way. check this https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

let me know if you have any question about this

**Comment by Bpleic** [comment]
> sorry @Bpleic i missed the notification. so we have to procede in the gran tour pro way. check this [#1591 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559)
> 
> let me know if you have any question about this

Hi, it works fine as far as the connection between the tape and the qz application is concerned.  The only problem is that it doesn't give feedback from zwift for tilt.  Another thing is that on trademill I set, for example, 12.5 kmh, qz reads it as 10kmh and transfers it to zwift as 10kmh.  The slope percentages are correct in the trademill and on the QZ

**Comment by cagnulein** [comment]
> Another thing is that on trademill I set, for example, 12.5 kmh, qz reads it as 10kmh and transfers it to zwift as 10kmh.

yes because qz reads the real speed from the treadmill, not the one that you set (the motor has a reading sensor). Anyway you can use the speed offset and speed gain settings in qz to adjust it if you want



> The only problem is that it doesn't give feedback from zwift for tilt

what do you mean? Can you explain this?

**Comment by Bpleic** [comment]
Sorry for the expression, it doesn't receive commands from zwift related to incline, when zwift has an incline of 3% trademill doesn't respond.

**Comment by cagnulein** [comment]
yes that's normal, zwift doesn't send any information to any treadmill...BUT with qz now you can do this right now! You just need the new beta from the play store and set your zwift credential on qz and you will be ready to have auto inclination!

**Comment by Bpleic** [comment]
Ok, thank you, everything is clear now, I'll try it tonight.
I already have the latest beta version of QZ.

**Comment by cagnulein** [comment]
@Bpleic Are we OK with this?
