### ISSUE TITLE
Domyos Woodrower

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1963]
![unnamed (4)](https://github.com/cagnulein/qdomyos-zwift/assets/48216/a3f580f8-9131-4d0b-b7b1-a25750ace12a)
![unnamed (3)](https://github.com/cagnulein/qdomyos-zwift/assets/48216/9a7bc602-14fa-4f9a-abd8-7d00134fe5ad)
![unnamed (2)](https://github.com/cagnulein/qdomyos-zwift/assets/48216/01543316-f155-4686-b95a-afdb8c31c176)
![unnamed (1)](https://github.com/cagnulein/qdomyos-zwift/assets/48216/85a4fa2f-4dca-443a-b8fa-ce209997875d)
![unnamed](https://github.com/cagnulein/qdomyos-zwift/assets/48216/6110065b-67b1-4816-91f9-05e2506408dd)

**Comment by mmarchesani** [comment]
[debug-lun_gen_8_08_41_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13857381/debug-lun_gen_8_08_41_19_2024.log)

**Comment by mmarchesani** [comment]
[debug-mar_gen_9_18_03_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13877024/debug-mar_gen_9_18_03_53_2024.log)
[debug-mar_gen_9_17_57_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13877025/debug-mar_gen_9_17_57_04_2024.log)

**Comment by mmarchesani** [comment]
[debug-mer_gen_10_18_48_29_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13891843/debug-mer_gen_10_18_48_29_2024.log)

**Comment by cagnulein** [comment]
Risolto! ti mandero' un aggiornamento domani!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle ore 19:59 mmarchesani <
***@***.***> ha scritto:
