### ISSUE TITLE
[BUG] build error

### ISSUE THREAD

**Issue by mattwillems** [cagnulein/qdomyos-zwift#1964]
**Describe the bug**
Error during compile 
 
**To Reproduce**
1. Go to 'qdomyos-zwift/src'
2. run 'make'

**Desktop (please complete the following information):**
 - OS: raspberry pi OS - debian bullseye 6.1.21-v8+
 - Raspberry Pi Zero 2 W

make
g++ -Wl,-O1 -s -pipe -fno-sized-deallocation -O3 -std=gnu++1z -flto=4 -fno-fat-lto-objects -fuse-linker-plugin -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu -fPIC -o qdomyos-zwift QTelnet.o bkoolbike.o csafe.o csaferower.o eliteariafan.o fakerower.o proformtelnetbike.o virtualdevice.o androidactivityresultreceiver.o androidadblog.o apexbike.o handleurl.o iconceptelliptical.o localipaddress.o pelotonbike.o schwinn170bike.o wahookickrheadwind.o windows_zwift_workout_paddleocr_thread.o ypooelliptical.o ziprotreadmill.o Computrainer.o PathController.o characteristicnotifier2a53.o characteristicnotifier2a5b.o characteristicnotifier2acc.o characteristicnotifier2acd.o characteristicnotifier2ad9.o characteristicwriteprocessor.o characteristicwriteprocessore005.o computrainerbike.o fakeelliptical.o faketreadmill.o lifefitnesstreadmill.o mepanelbike.o nautilusbike.o nordictrackelliptical.o nordictrackifitadbbike.o nordictrackifitadbtreadmill.o octaneelliptical.o octanetreadmill.o proformellipticaltrainer.o proformrower.o proformwifibike.o proformwifitreadmill.o abstractserver.o bitmap.o browser.o cache.o dns.o hostname.o mdns.o message.o prober.o provider.o query.o record.o resolver.o server.o service.o activiotreadmill.o bhfitnesselliptical.o bike.o bluetooth.o bluetoothdevice.o characteristicnotifier2a37.o characteristicnotifier2a63.o characteristicnotifier2ad2.o characteristicwriteprocessor2ad9.o bowflext216treadmill.o bowflextreadmill.o chronobike.o concept2skierg.o cscbike.o dirconmanager.o dirconpacket.o dirconprocessor.o domyoselliptical.o domyosrower.o domyostreadmill.o echelonconnectsport.o echelonrower.o echelonstride.o eliterizer.o elitesterzosmart.o elliptical.o eslinkertreadmill.o fakebike.o filedownloader.o fitmetria_fanfit.o fitplusbike.o fitshowtreadmill.o fit.o fit_accumulated_field.o fit_accumulator.o fit_buffer_encode.o fit_buffered_mesg_broadcaster.o fit_buffered_record_mesg_broadcaster.o fit_crc.o fit_date_time.o fit_decode.o fit_developer_field.o fit_developer_field_definition.o fit_developer_field_description.o fit_encode.o fit_factory.o fit_field.o fit_field_base.o fit_field_definition.o fit_mesg.o fit_mesg_broadcaster.o fit_mesg_definition.o fit_mesg_with_event_broadcaster.o fit_profile.o fit_protocol_validator.o fit_unicode.o flywheelbike.o ftmsbike.o ftmsrower.o gpx.o heartratebelt.o homefitnessbuddy.o homeform.o horizongr7bike.o horizontreadmill.o iconceptbike.o inspirebike.o keepawakehelper.o keepbike.o kingsmithr1protreadmill.o kingsmithr2treadmill.o main.o mcfbike.o metric.o nautiluselliptical.o nautilustreadmill.o npecablebike.o pafersbike.o paferstreadmill.o peloton.o powerzonepack.o proformbike.o proformelliptical.o proformtreadmill.o qfit.o qzsettings.o renphobike.o rower.o schwinnic4bike.o screencapture.o sessionline.o shuaa5treadmill.o signalhandler.o simplecrypt.o skandikawiribike.o smartrowrower.o smartspin2k.o emailaddress.o mimeattachment.o mimecontentformatter.o mimefile.o mimehtml.o mimeinlinefile.o mimemessage.o mimemultipart.o mimepart.o mimetext.o quotedprintable.o smtpclient.o snodebike.o solebike.o soleelliptical.o solef80treadmill.o spirittreadmill.o sportsplusbike.o sportstechbike.o strydrunpowersensor.o tacxneo2.o tcpclientinfosender.o technogymmyruntreadmill.o technogymmyruntreadmillrfcomm.o templateinfosender.o templateinfosenderbuilder.o stagesbike.o toorxtreadmill.o treadmill.o truetreadmill.o trxappgateusbbike.o ultrasportbike.o virtualrower.o wahookickrsnapbike.o yesoulbike.o trainprogram.o trxappgateusbtreadmill.o virtualbike.o virtualtreadmill.o m3ibike.o domyosbike.o scanrecordresult.o windows_zwift_incline_paddleocr_thread.o zwiftworkout.o mainwindow.o charts.o inappproductqmltype.o inappstoreqmltype.o inappproduct.o inapppurchasebackend.o inappstore.o inapptransaction.o qdomyos-zwift_qmltyperegistrations.o qrc_icons.o qrc_qml.o moc_QTelnet.o moc_bkoolbike.o moc_csaferower.o moc_eliteariafan.o moc_proformtelnetbike.o moc_windows_zwift_workout_paddleocr_thread.o moc_fakerower.o moc_PlayerStateWrapper.o moc_zwift_client_auth.o moc_virtualdevice.o moc_androidadblog.o moc_apexbike.o moc_handleurl.o moc_iconceptelliptical.o moc_pelotonbike.o moc_schwinn170bike.o moc_wahookickrheadwind.o moc_ypooelliptical.o moc_ziprotreadmill.o moc_characteristicwriteprocessore005.o moc_computrainerbike.o moc_fakeelliptical.o moc_faketreadmill.o moc_lifefitnesstreadmill.o moc_mepanelbike.o moc_nautilusbike.o moc_nordictrackelliptical.o moc_nordictrackifitadbbike.o moc_nordictrackifitadbtreadmill.o moc_octaneelliptical.o moc_octanetreadmill.o moc_proformellipticaltrainer.o moc_proformrower.o moc_proformwifibike.o moc_proformwifitreadmill.o moc_abstractserver.o moc_browser.o moc_cache.o moc_hostname.o moc_prober.o moc_provider.o moc_resolver.o moc_server.o moc_browser_p.o moc_cache_p.o moc_hostname_p.o moc_prober_p.o moc_provider_p.o moc_resolver_p.o moc_server_p.o moc_activiotreadmill.o moc_bhfitnesselliptical.o moc_bike.o moc_bluetooth.o moc_bluetoothdevice.o moc_characteristicnotifier.o moc_characteristicwriteprocessor.o moc_characteristicwriteprocessor2ad9.o moc_bowflext216treadmill.o moc_bowflextreadmill.o moc_chronobike.o moc_concept2skierg.o moc_cscbike.o moc_dirconmanager.o moc_dirconprocessor.o moc_domyoselliptical.o moc_domyosrower.o moc_domyostreadmill.o moc_echelonconnectsport.o moc_echelonrower.o moc_echelonstride.o moc_eliterizer.o moc_elitesterzosmart.o moc_elliptical.o moc_eslinkertreadmill.o moc_fakebike.o moc_filedownloader.o moc_fitmetria_fanfit.o moc_fitplusbike.o moc_ftmsrower.o moc_homefitnessbuddy.o moc_horizongr7bike.o moc_iconceptbike.o moc_keepbike.o moc_kingsmithr1protreadmill.o moc_kingsmithr2treadmill.o moc_m3ibike.o moc_fitshowtreadmill.o moc_flywheelbike.o moc_ftmsbike.o moc_heartratebelt.o moc_homeform.o moc_horizontreadmill.o moc_inspirebike.o moc_material.o moc_mcfbike.o moc_nautiluselliptical.o moc_nautilustreadmill.o moc_npecablebike.o moc_pafersbike.o moc_paferstreadmill.o moc_peloton.o moc_powerzonepack.o moc_proformbike.o moc_proformelliptical.o moc_proformtreadmill.o moc_qfit.o moc_renphobike.o moc_rower.o moc_schwinnic4bike.o moc_screencapture.o moc_shuaa5treadmill.o moc_skandikawiribike.o moc_smartrowrower.o moc_smartspin2k.o moc_emailaddress.o moc_mimeattachment.o moc_mimecontentformatter.o moc_mimefile.o moc_mimehtml.o moc_mimemultipart.o moc_mimepart.o moc_quotedprintable.o moc_smtpclient.o moc_snodebike.o moc_solebike.o moc_soleelliptical.o moc_solef80treadmill.o moc_spirittreadmill.o moc_sportsplusbike.o moc_sportstechbike.o moc_strydrunpowersensor.o moc_tacxneo2.o moc_tcpclientinfosender.o moc_technogymmyruntreadmill.o moc_technogymmyruntreadmillrfcomm.o moc_templateinfosender.o moc_templateinfosenderbuilder.o moc_stagesbike.o moc_toorxtreadmill.o moc_gpx.o moc_treadmill.o moc_mainwindow.o moc_trainprogram.o moc_truetreadmill.o moc_trxappgateusbbike.o moc_trxappgateusbtreadmill.o moc_ultrasportbike.o moc_virtualbike.o moc_virtualrower.o moc_virtualtreadmill.o moc_domyosbike.o moc_wahookickrsnapbike.o moc_wobjectdefs.o moc_yesoulbike.o moc_windows_zwift_incline_paddleocr_thread.o moc_charts.o moc_inappproductqmltype.o moc_inappstoreqmltype.o moc_inappproduct.o moc_inapppurchasebackend.o moc_inappstore.o moc_inapptransaction.o   /usr/lib/aarch64-linux-gnu/libQt5Charts.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Location.so /usr/lib/aarch64-linux-gnu/libQt5PositioningQuick.so /usr/lib/aarch64-linux-gnu/libQt5QuickControls2.so /usr/lib/aarch64-linux-gnu/libQt5Quick.so /usr/lib/aarch64-linux-gnu/libQt5Multimedia.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5Bluetooth.so /usr/lib/aarch64-linux-gnu/libQt5Xml.so /usr/lib/aarch64-linux-gnu/libQt5Positioning.so /usr/lib/aarch64-linux-gnu/libQt5QmlModels.so /usr/lib/aarch64-linux-gnu/libQt5Qml.so /usr/lib/aarch64-linux-gnu/libQt5NetworkAuth.so /usr/lib/aarch64-linux-gnu/libQt5WebSockets.so /usr/lib/aarch64-linux-gnu/libQt5Network.so /usr/lib/aarch64-linux-gnu/libQt5TextToSpeech.so /usr/lib/aarch64-linux-gnu/libQt5Core.so -lGL -lpthread
{standard input}: Assembler messages:
{standard input}:2215: Warning: end of file not at end of a line; newline inserted
{standard input}:2510: Error: unknown pseudo-op: `.'
g++: fatal error: Killed signal terminated program lto1
compilation terminated.
make[1]: *** [/tmp/ccpWdZML.mk:32: /tmp/qdomyos-zwift.N5cGrM.ltrans10.ltrans.o] Error 1
make[1]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:1611: qdomyos-zwift] Error 1

**Comment by cagnulein** [comment]
maybe a ram issue? i never saw this issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 20:25 Matt Willems ***@***.***>
ha scritto:

**Comment by mattwillems** [comment]
It's a fresh Raspberry Pi OS 64-bit Lite install on a new Pi I got for this purpose. I've played with the GPU memory split but it doesn't seem to make a difference. Anything else you'd suggest, or a different OS/architecture?

**Comment by cagnulein** [comment]
mmm i guess i'm using 32bit raspberry OS usually, maybe it could be the
issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 20:50 Matt Willems ***@***.***>
ha scritto:

**Comment by mattwillems** [comment]
Installing 32 bit right now and I'll report back. Sorry for the off topic question but I haven't figured out how to edit settings like you can in the app when running headless.

**Comment by cagnulein** [comment]
you can edit the conf file directly or you can create a pr adding some
inline arguments to the executable

we can also create a custom argument that just writes whatever setting with
whatever value.

i don't have the time to do this now :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 21:17 Matt Willems ***@***.***>
ha scritto:

**Comment by mattwillems** [comment]
So it was a memory issue. Watching 'free' I could see it was just running out of RAM on that one compile step. I installed zram and it built successfully (at one point was consuming well over 600MB).

**Comment by cagnulein** [comment]
great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 05:17 Matt Willems ***@***.***>
ha scritto:
