### ISSUE TITLE
[REQ] Freeze Button

### ISSUE THREAD

**Issue by abronxtale** [cagnulein/qdomyos-zwift#1965]
Hi

I think the app should have a lock button on it similar to Apple witness as I’ve had the app reset 3x in one biking session

thanks

**Comment by cagnulein** [comment]
ok thanks, i will try to implement this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 01:11 abronxtale ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @abronxtale check the answer here https://discussions.apple.com/thread/255145619?sortBy=best I guess you can do following

> Since you upgraded to watchOS 10 access to the [Control Center](https://support.apple.com/guide/watch/control-center-apd06bc15da1/watchos), and has changed. You will find the "lock" icon using the following advice.
> 
> "Open or close Control Center
> 
> Open Control Center: Press the side button once.
> Close Control Center: With Control Center open, turn your wrist away from you or press the side button again.""

let me know

**Comment by cagnulein** [comment]
edited https://discussions.apple.com/thread/255145619?answerId=259599697022&sortBy=best#259599697022

**Comment by abronxtale** [comment]
You can’t lock it when QZ is running

I tried opening another app and it closing it but it still reverts back to the QZ app

**Comment by cagnulein** [comment]
it's not another app, it's the lock water symbol in the settings

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle 02:38 abronxtale ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@abronxtale did you find it?

**Comment by abronxtale** [comment]
Hi

no

you can’t lock it while in qz 

reset on me again today and when I hit start it went to an indoor run

personally I think there should be all icons

heart beat icon
Kms icon 
Kcal icon

so on the watch there would be little icons you could see your numbers.

**Comment by cagnulein** [comment]
yes that you can lock, just press the side button on watchos10 and press
the water icon

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 gen 2024 alle 22:51 abronxtale ***@***.***>
ha scritto:
