### ISSUE TITLE
Open Ride Tracking 

### ISSUE THREAD

**Issue by abronxtale** [cagnulein/qdomyos-zwift#1966]
Hi

so today I worked out

I own an Echelon bike and run QZ app for tracking cadence a d heart rate and Peleton for classes 

I did a 45 minute hit and hills

once I was done I closed the peleton app and QZ app

I opened the QZ app again so I could do some Zone 2,3,4 work for another 15
Minutes 

once I was done and closed the QZ app it had erased the data from my Hit and Hills class I did erasing all the calories from that workout in my Apple Health/Fitness and only showing the extra 15 minutes 

can you not do multiple rides a day?

**Comment by cagnulein** [comment]
you have to press stop on the watch first before closing the qz main app.
it's the stop event on the watch that we writes the stats to apple health

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 01:17 abronxtale ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@abronxtale did you try?
