### ISSUE TITLE
[BUG] Zwift show 0.0kph instead of 9.0 kph

### ISSUE THREAD

**Issue by nabulaer** [cagnulein/qdomyos-zwift#1967]
**Describe the bug**
when running a training plan workout ( not a normal run) and the plan says to run at 9.0kph I press the buttons on my treadmill to set the speed to 9.0 kph, the treadmill shows 9.0kph also qz app show same but on zwift it shows 0.0 and the avatar is not running. when I set the speed to 8.9 or 9.1 zwift shows the correct speed and the avatar is running it only happens when setting it to 9.0kph.
I am using treadmill domyos T900C , iPhone 12 pro max most up-to-date firmware Apple Watch Ultra 1

**To Reproduce**
1. Open Zwift and qz app on iPhone and on Apple Watch connect all
2. choose a workout running plan
3. start running during the workout
4. set the speed on the treadmill to 9.0

**Expected behavior**
I expect the avatar to keep running on when set to 9.0kph

**Screenshots**

![IMG_9287](https://github.com/cagnulein/qdomyos-zwift/assets/935503/c365c524-97ff-421a-924d-0c5b8d9cafec)
![IMG_9288](https://github.com/cagnulein/qdomyos-zwift/assets/935503/24a46ffa-8dd7-4f36-8d9a-959e603a95ab)

**Desktop (please complete the following information):**
 - OS:,ipados
 -  - Version ,17.1.2

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro max
 - OS: ios 17.1.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Sun_Jan_7_07_46_57_2024.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/13856728/debug-Sun_Jan_7_07_46_57_2024.log.zip)

  
**Additional context**

**Comment by cagnulein** [comment]
hi, where are you running zwift? i mean on which device?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 07:14 Yosi Oren ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
qz and zwift can't run on the same device on iphone, you need 2 devices :
one for qz and one for iphone

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 07:18 cagnulein ***@***.***> ha
scritto:

**Comment by nabulaer** [comment]
As written in the bug report, zwift is on ipad qz on iPhone. J. Sent from my iPhoneOn 8 Jan 2024, at 8:19, Roberto Viola ***@***.***> wrote:﻿
qz and zwift can't run on the same device on iphone, you need 2 devices :

one for qz and one for iphone



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 8 gen 2024 alle 07:18 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
how do you connect qz to zwift? phone name or wahoo device?

**Comment by nabulaer** [comment]
I am now using wahoo device tread network.

**Comment by nabulaer** [comment]
Hi,
I just now made a test for a non-schedule workout change connection to my phone name instead of a wahoo device and I can not reproduce the bug.
I have a scheduled workout for tomorrow and will let you know if it is also not reproducible.
thanks.

**Comment by cagnulein** [comment]
ok thanks for the feedback. it could be just a zwift bug :) if you check on the zwift forums unfortunately zwift has a lot of connection issues :( you have just to find the right setup for you that works all the time

**Comment by cagnulein** [comment]
@nabulaer Are we OK with this?
