### ISSUE TITLE
[BUG] - Unable to find IP address on treadmill

### ISSUE THREAD

**Issue by CharRich** [cagnulein/qdomyos-zwift#1969]
**Describe the bug**
Unable to find IP address on NordicTrack 1750 (2019 model) treadmill either according to README/ YouTube instructions or by manually searching through settings on the treadmill.

**To Reproduce**

When clicking on ‘About tablet’ on the treadmill, see picture of available information. IP address is not there. 

**Expected behavior**
Unsure - expect IP address to be available somewhere on the treadmill.

**Screenshots**

Picture added

![IMG_0054](https://github.com/cagnulein/qdomyos-zwift/assets/155968643/bc322652-8817-47c0-90f9-ba33f355c3f1)

Note: I have an Amazon Eero, which comes with an associated app where one can see a full lit of connected devices. I have been able to find the IP address of the treadmill through this app. Raising this bug report though in case that for some reason doesn’t work, and also to enable you to help others in the future who may have the same issue if they have this treadmill.

**Comment by cagnulein** [comment]
in the wifi settings of the treadmill there is anything?

@victorypoint any hints?

**Comment by victorypoint** [comment]
@CharRich, yes I would look into the WiFi settings of the treadmill to see if it's listed there.

**Comment by CharRich** [comment]
Found it under WiFi. This just brings a list of the all the WiFi networks available in the area. I then clicked on the three dots in the top right corner and selected ‘Advanced Settings’ and there it was. 

It was the same as the IP address listed in my Eero app, so all okay. 

Thanks for your help everyone. I think we can consider this one resolved.
