### ISSUE TITLE
KCal shoots up to 65K

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#197]
**Describe the bug**
When using the treadmill the Kcal shoots from 127 to 65408.

**To Reproduce**
1. Get on the treatmill
2. Run until you get to 127 Kcal
3. Run a bit more

**Expected behavior**
127 -> 128

**Screenshots**
do mrt. 11 19:54:32 2021 1615488872498 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:32 2021 1615488872502 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:32 2021 1615488872504 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:32 2021 1615488872506 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
do mrt. 11 19:54:32 2021 1615488872508 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 127"
do mrt. 11 19:54:32 2021 1615488872509 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:32 2021 1615488872511 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.77081"
do mrt. 11 19:54:32 2021 1615488872514 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:32 2021 1615488872612 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:32 2021 1615488872617 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:32 2021 1615488872762 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:32 2021 1615488872884 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 7f 00 12 00 00 01 00 00 00 4e 01 00 02 01 fd"
do mrt. 11 19:54:32 2021 1615488872887 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:32 2021 1615488872890 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:32 2021 1615488872893 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:32 2021 1615488872895 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
**do mrt. 11 19:54:32 2021 1615488872897 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 127"**
do mrt. 11 19:54:32 2021 1615488872898 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:32 2021 1615488872900 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.77206"
do mrt. 11 19:54:32 2021 1615488872903 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:32 2021 1615488872904 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:32 2021 1615488872907 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:33 2021 1615488873031 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:33 2021 1615488873035 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 80 00 12 00 00 01 00 00 00 4e 01 00 02 01 fe"
do mrt. 11 19:54:33 2021 1615488873038 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:33 2021 1615488873041 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:33 2021 1615488873043 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:33 2021 1615488873045 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
**do mrt. 11 19:54:33 2021 1615488873047 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 65408"**
do mrt. 11 19:54:33 2021 1615488873048 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:33 2021 1615488873050 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.77252"
do mrt. 11 19:54:33 2021 1615488873052 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:33 2021 1615488873054 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:33 2021 1615488873057 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 cb 03 0d 30 ff 01 00 b1 02 01 00 00 00 01 00 0a 01 01 00 // updateDisplay elapsed=828"
do mrt. 11 19:54:33 2021 1615488873212 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed current row109current row len300"
do mrt. 11 19:54:33 2021 1615488873303 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:33 2021 1615488873307 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:33 2021 1615488873310 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> 78 01 01 00 7f 01 b6 // updateDisplay elapsed=828"
do mrt. 11 19:54:33 2021 1615488873424 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 80 00 12 00 00 01 00 00 00 4e 01 00 02 01 fe"
do mrt. 11 19:54:33 2021 1615488873427 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:33 2021 1615488873430 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:33 2021 1615488873433 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:33 2021 1615488873435 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
do mrt. 11 19:54:33 2021 1615488873437 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 65408"
do mrt. 11 19:54:33 2021 1615488873439 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:33 2021 1615488873441 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.77378"
do mrt. 11 19:54:33 2021 1615488873443 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:33 2021 1615488873445 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:33 2021 1615488873447 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:33 2021 1615488873572 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten 00 00 00 00 04 00 00 00 10 bb 87 03 01 00 00 00 f0 11 9d 83"
do mrt. 11 19:54:33 2021 1615488873749 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:33 2021 1615488873812 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten 01 00 00 00 c0 c9 6d"
do mrt. 11 19:54:33 2021 1615488873816 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:33 2021 1615488873821 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:34 2021 1615488874051 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:34 2021 1615488874122 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:34 2021 1615488874171 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 80 00 12 00 00 01 00 00 00 4e 01 00 02 01 fe"
do mrt. 11 19:54:34 2021 1615488874173 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:34 2021 1615488874174 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:34 2021 1615488874175 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:34 2021 1615488874176 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
do mrt. 11 19:54:34 2021 1615488874177 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 65408"
do mrt. 11 19:54:34 2021 1615488874178 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:34 2021 1615488874179 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.77622"
do mrt. 11 19:54:34 2021 1615488874211 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram elapsed current row110current row len300"
do mrt. 11 19:54:34 2021 1615488874215 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:34 2021 1615488874217 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:34 2021 1615488874320 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:34 2021 1615488874441 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 80 00 12 00 00 01 00 00 00 4e 01 00 02 01 fe"
do mrt. 11 19:54:34 2021 1615488874442 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "packetReceived!"
do mrt. 11 19:54:34 2021 1615488874444 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current speed: 12"
do mrt. 11 19:54:34 2021 1615488874445 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current incline: 1"
do mrt. 11 19:54:34 2021 1615488874446 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current heart: 0"
do mrt. 11 19:54:34 2021 1615488874447 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current KCal: 65408"
do mrt. 11 19:54:34 2021 1615488874448 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance: 1.8"
do mrt. 11 19:54:34 2021 1615488874449 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Current Distance Calculated: 1.7771"
do mrt. 11 19:54:34 2021 1615488874451 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " exit for timeout"
do mrt. 11 19:54:34 2021 1615488874453 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Domyos Treadmill RSSI -49"
do mrt. 11 19:54:34 2021 1615488874455 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " >> f0 ac 9c // noOp"
do mrt. 11 19:54:34 2021 1615488874591 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "characteristicWritten f0 ac 9c"
do mrt. 11 19:54:34 2021 1615488874713 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) " << 26 f0 bc 03 f2 00 00 00 78 00 00 00 80 00 12 00 00 01 00 00 00 4e 01 00 02 01 fe"

**Desktop (please complete the following information):**
IOS

**Smartphone (please complete the following information):**
Iphone XS Max

**Additional context**
Is it a coincidence that it is from 128 (2e7) to 65xxx (2e16)?

**Comment by ErnieV** [comment]
If you need full log file let me know!

**Comment by cagnulein** [comment]
probably releated to #178

**Comment by cagnulein** [comment]
@ErnieV thanks for reporting it! fixed! it should be in the next beta ;)
Remember to close it when you will test it ;)

**Comment by cagnulein** [comment]
@ErnieV uploading now the 2.4.19
are you in the beta group?

**Comment by ErnieV** [comment]
Yes I am. Got 2.4.19 on ios.
Will test it this weekend.

Verstuurd vanaf mijn iPhone

**Comment by ErnieV** [comment]
Tested once, was ok.
Will test again today.
If ok again I will close.

Thank you

**Comment by ErnieV** [comment]
Tested again, no problems anymore!
