### ISSUE TITLE
Bluetooth connection is disconnecting during ride [BUG]

### ISSUE THREAD

**Issue by MBeckermann** [cagnulein/qdomyos-zwift#1973]
[debug-Mon_Jan_8_08_01_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866735/debug-Mon_Jan_8_08_01_37_2024.log)
[debug-Mon_Jan_8_07_43_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866744/debug-Mon_Jan_8_07_43_55_2024.log)
[debug-Mon_Jan_8_08_11_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866745/debug-Mon_Jan_8_08_11_27_2024.log)
[debug-Mon_Jan_8_08_23_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866749/debug-Mon_Jan_8_08_23_49_2024.log)
[debug-Mon_Jan_8_08_37_21_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866751/debug-Mon_Jan_8_08_37_21_2024.log)
[debug-Mon_Jan_8_08_09_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13866757/debug-Mon_Jan_8_08_09_34_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check them out

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 23:20 MBeckermann ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @MBeckermann  thanks for the log. I deeply analyzed them i didn't find a huge issue that explain everything but, the HR rate device that you are using is streaming A LOT (more than 5 times per second!). This could lead the iphone to saturate the bluetooth bandwinth maybe. So question: on the echelon app, did you use the same HR device connected directly to the echelon app? If not, try to disconnect the HR from the iphone and give it a try.
Let me know!

**Comment by cagnulein** [comment]
any news @MBeckermann  ?

**Comment by MBeckermann** [comment]
I’ve been sick the last few days and not able to ride.  I’ll let you know when I get a chance.Sent from my IPad On Jan 11, 2024, at 3:46 AM, Roberto Viola ***@***.***> wrote:﻿
any news @MBeckermann  ?

**Comment by cagnulein** [comment]
Ok, hope you feel better soon!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle ore 15:48 MBeckermann <
***@***.***> ha scritto:

**Comment by MBeckermann** [comment]
Roberto,Finally got back on the bike.  I did 3 10 minute rides.  The first ride I had QZ on my IPad, Peloton on my iPhone and wearing a Scosche heart rate band.  Bluetooth disconnected.  I turned off the Scosche band and used Apple Watch (Peloton app)for heart rate. Bluetooth disconnected again.  The second ride I had same set up but never turned on the Scosche heart band and only used Apple Watch for heart rate.  Bluetooth disconnected.  Third ride I had QZ on iPad and used the Peloton Guide for the ride.  Used Apple Watch for heart rate on Guide and Scosche heart band for heart rate on QZ.  The Bluetooth did not disconnect.I’ll upload the debug logs.Thanks Sent from my IPad On Jan 11, 2024, at 8:54 AM, Roberto Viola ***@***.***> wrote:﻿
Ok, hope you feel better soon!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 11 gen 2024 alle ore 15:48 MBeckermann <

***@***.***> ha scritto:

**Comment by cagnulein** [comment]
scenario 3 seems very similar to 1. the only difference is that qz is not
broadcasting metrics to the peloton app, am i right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 14 gen 2024 alle 19:35 MBeckermann ***@***.***>
ha scritto:

**Comment by MBeckermann** [comment]
[debug-Sun_Jan_14_11_26_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13932739/debug-Sun_Jan_14_11_26_53_2024.log)
[debug-Sun_Jan_14_11_40_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13932742/debug-Sun_Jan_14_11_40_31_2024.log)
[debug-Sun_Jan_14_11_54_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13932755/debug-Sun_Jan_14_11_54_45_2024.log)

**Comment by MBeckermann** [comment]
Scenario 3 I was using the Guide instead of the app on my iPhone.  Yes, the Guide is picking up the heart rate from the app on my watch.Sent from my IPad On Jan 14, 2024, at 12:51 PM, Roberto Viola ***@***.***> wrote:﻿
scenario 3 seems very similar to 1. the only difference is that qz is not

broadcasting metrics to the peloton app, am i right?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 14 gen 2024 alle 19:35 MBeckermann ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
did you try the iphone also? it has the same behavior?

i'm aware that some apple devices have issues on broadcasting data (peloton on your case). that's the main difference from the echelon app for example (it doesn't broadcast anything)

this is due to some cheap Bluetooth chips that apple is using

that's why i'm suggesting to try the iphone too, in order to check it it's the ipad the issue

let me know

**Comment by MBeckermann** [comment]
Just did another 10 minute ride.  QZ on my iPhone and Peloton on my iPad.  It worked.  The Bluetooth did not disconnect.  I have an old iPad that is running IOS 9.3.5.  Can I download QZ to it?Sent from my IPad On Jan 14, 2024, at 1:46 PM, Roberto Viola ***@***.***> wrote:﻿
did you try the iphone also? it has the same behavior?
i'm aware that some apple devices have issues on broadcasting data (peloton on your case). that's the main difference from the echelon app for example (it doesn't broadcast anything)
this is due to some cheap Bluetooth chips that apple is using
that's why i'm suggesting to try the iphone too, in order to check it it's the ipad the issue
let me know

**Comment by cagnulein** [comment]
that's a good news. for the ipad check directly from it, but i guess the
minimum ios version is 12

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 14 gen 2024 alle 21:21 MBeckermann ***@***.***>
ha scritto:
