### ISSUE TITLE
Xterra TRX3500 requested log file

### ISSUE THREAD

**Issue by johnmsie** [cagnulein/qdomyos-zwift#1974]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13866806/btsnoop_hci.log)

Started workout by pressing start on the machine.  Ended workout by pressing end on machine.

Increased incline from 0 to 5 degrees, and speed from 1kph to 5 in 0.1 increments, then down to 2 and back to 5 by pressing 5 on the machine interface.

**Comment by cagnulein** [comment]
thanks i will check it out

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 23:30 johnmsie ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got it @johnmsie ! this treadmill has a completely not-standard FTMS implementation. Let me to try a fix!

**Comment by cagnulein** [comment]
@johnmsie done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7459609882

you can use the android build in the link (it will appear in the bottom of the page in 30 minutes). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
I hope I did everything right, let me know!

**Comment by cagnulein** [comment]
sorry wrong link https://github.com/cagnulein/qdomyos-zwift/actions/runs/7459682669

**Comment by johnmsie** [comment]
Hi Roberto,

Thanks for your help. Apologies, but I am having trouble locating the apk
file to install. Can you possibly link it? I haven't previously installed
this app before just Kinni and Kinomap so won't need to delete it. If
treadmill control works with it, will the same update be implemented in
kinni?

Thanks,
John

**Comment by cagnulein** [comment]
sure https://github.com/cagnulein/qdomyos-zwift/actions/runs/7459682669/artifacts/1156421292
Kinni uses the QZ library, so yes it will bringed to kinni as well

**Comment by johnmsie** [comment]
Hi Roberto,

With this I was not able to control the treadmill, it is connecting.  I
could see the inputs I made to the treadmill reflect in the app.

Attached is the log file.

Steps I followed:
Pressed start in the app, nothing happened
Press start on the treadmill
Increase speed to 2
Increase elevation to 4, decrease elevation
Increase speed to 4
Decrease speed.
Press stop in the ap, nothing happened
Press stop on the machine.

Thanks,
John


Thanks,
John

**Comment by johnmsie** [comment]
Hi Roberto,

Please find attached.

In it I use treadmill manual controls, and after to change speed and
incline with app (doesn't work).

Thanks,
John

**Comment by cagnulein** [comment]
hi @johnmsie you have to attach it from the github web interface otherwise I can't see it. thanks

**Comment by johnmsie** [comment]
Ok, I will do that.

**Comment by johnmsie** [comment]
[debug-Tue_Jan_9_15_23_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13875821/debug-Tue_Jan_9_15_23_04_2024.log)

**Comment by johnmsie** [comment]
Will do, do I need to run it for longer?

**Comment by cagnulein** [comment]
nope I just need to see everything from the start and while you're changing the inclination.

**Comment by johnmsie** [comment]
[debug-Tue_Jan_9_15_52_29_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13876016/debug-Tue_Jan_9_15_52_29_2024.log)

**Comment by cagnulein** [comment]
still truncated, are you closing qz before send me the log?

**Comment by johnmsie** [comment]
I don't think I have been, I assumed the log was assocaited with the workout.  

Should I end workout, close QZ then send log?

**Comment by cagnulein** [comment]
just close qz could be enough. It depends from android device to android device, must of them they don't require a close app, but probably yours yes (it's caching in the RAM).

In the log file you have to see that it starts with the qz version, otherwise the file is truncated

**Comment by johnmsie** [comment]
Great, this one works, you will see movement from 15:55. Thanks!
[debug-Tue_Jan_9_15_54_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13876159/debug-Tue_Jan_9_15_54_12_2024.log)

**Comment by cagnulein** [comment]
yes this one is right but I don't see you pressing plus or minus buttons on the inclination or speed tile. could you please do this otherwise i can't compare it with the kinomap log. thanks

**Comment by johnmsie** [comment]
[debug-Tue_Jan_9_16_23_21_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13876356/debug-Tue_Jan_9_16_23_21_2024.log)

In this one I definitely do.  When I press + or - minus speed in QZ nothing happens. + inclination nothing happens, **but - inclination does work**.
Thanks

**Comment by cagnulein** [comment]
ok this time i can see it and also i'm seeing that it worked when you were on inclination to 2 and you press the minus. I got the issue, your treadmill can change only integer value of inclination, not 0.5.
change the Inclination Step in the treadmill settings to 1, it should fix this.
Share a debug log in case it doesn't: anyway your treadmill doesn't have the capabilities to accept speed control. I'm sending it but it just refuses.

**Comment by johnmsie** [comment]
Hi @cagnulein yes that works for inclination both ways now, it is a pity about the speed control as this would have been most useful.
Xterra's native app does not synchronise correctly with Strava, no detailed info. such as pace etc. is shared just brief summary (total distance, time, average pace).  Kinni shares all info. including detailed heart rate etc. so I will continue to use it.  Thanks

**Comment by cagnulein** [comment]
xterra native app can change the speed from the app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 gen 2024 alle 17:42 johnmsie ***@***.***> ha
scritto:

**Comment by johnmsie** [comment]
No, it doesn't have any control functionality
