### ISSUE TITLE
[BUG] Connectivity issues with Bowflex BTX116 treadmill

### ISSUE THREAD

**Issue by sosaha** [cagnulein/qdomyos-zwift#1979]
**Describe the bug**
Issues is same as described in https://github.com/cagnulein/qdomyos-zwift/issues/1902
Please find log attached.
[debug-Tue_Jan_9_09_17_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13877041/debug-Tue_Jan_9_09_17_42_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
let's use the #1902 thanks
