### ISSUE TITLE
[BUG] Cannot open GPX file from local folder on Android mobile device

### ISSUE THREAD

**Issue by hakun** [cagnulein/qdomyos-zwift#1980]
**Describe the bug**
Open GPX file -> Other folder -> select a GPX files (either exported from Garmin connect or Strava), no map is shown

**To Reproduce**
Open GPX file -> Other folder -> select a GPX files (either exported from Garmin connect or Strava)

**Expected behavior**
Map is shown for selected GPX file

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/661b10ed-b988-449e-b01e-b35df8c4d556)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/4510208/23ffd7f5-e613-41ce-81e2-92dc53e6360c)

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Device: Galaxy A10
 - OS: android 11
 - Version: 2.16.30

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@hakun build ready https://github.com/cagnulein/qdomyos-zwift/actions/runs/7476032877/artifacts/1159705035

**Comment by cagnulein** [comment]
@hakun Are you OK with this?
