### ISSUE TITLE
Power Profile for BodyTone du30

### ISSUE THREAD

**Issue by Paelwastaken** [cagnulein/qdomyos-zwift#1981]
I've found that the power on my spin bike (bodytone du 30) is very innacurate.
I tried to calibrate it using the mx+b option, but I could only calibrate it to a certain point of rpm.
So I wanted to have a personalized power profile for the bodytone du30, capable of comunicating with zwift and other apps with accurate power values, at every cadence value.

This file contains all the information needed about the bike

[QZ - Final.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/13891315/QZ.-.Final.xlsx)

Thanks

**Comment by cagnulein** [comment]
can you tell me which is the bluetooth name of your device ?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 19:05 Paelwastaken ***@***.***>
ha scritto:

**Comment by Paelwastaken** [comment]
DU30-D98F

**Comment by cagnulein** [comment]
i don't remember . did you connect it as a cadence sensor? could you please
append a debug log so i will check the current state of your bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 19:39 Paelwastaken ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
this way
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 19:50 Paelwastaken ***@***.***>
ha scritto:

**Comment by Paelwastaken** [comment]
[debug-Thu_Jan_11_20_08_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13908082/debug-Thu_Jan_11_20_08_07_2024.log)
[debug-Thu_Jan_11_20_05_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13908083/debug-Thu_Jan_11_20_05_30_2024.log)
[debug-Thu_Jan_11_20_06_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13908084/debug-Thu_Jan_11_20_06_50_2024.log)
[debug-Thu_Jan_11_20_05_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13908085/debug-Thu_Jan_11_20_05_56_2024.log)
[debug-Thu_Jan_11_20_18_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13908086/debug-Thu_Jan_11_20_18_14_2024.log)

Here It is.
Another thing I've noticed is that resistance on the app is never the same as in the bike.
If I ride on resistance 1, it can be something like 20 resistance on qz and on next second be 28, without me changing the bike resistance
The same happens on every other resistance

**Comment by cagnulein** [comment]
ok let's first fix this so! the bike doesn't send via FTMS the resistance but I'm seeing that it's sending other bluetooth custom characteristics so we can try to collect it from there!

so create me a debug log where you are changing the resistance from 1 to the max and again to 1 keeping 2-3 seconds between each change. So i can add the parser!

Let me know!

**Comment by Paelwastaken** [comment]
[debug-Fri_Jan_12_16_40_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13921768/debug-Fri_Jan_12_16_40_28_2024.log)
I did 1-32 with 3 seconds intervals. Do you need the 32 to 1 log too?

**Comment by cagnulein** [comment]
no it should be fine , i will check this tomorrow, thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 gen 2024 alle 17:51 Paelwastaken ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
chat gpt did the job https://chat.openai.com/share/7cbed94a-93ca-441f-ba0d-77e02b9990cf

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/83729218-992e-4b6d-ba84-a190ea07156b)

10th byte of the 02 42 line (note for me)

**Comment by cagnulein** [comment]
@Paelwastaken i implemented the resistance reading in order to use this for the power table

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7511014194

You can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
Let me know if the resistance is now correct

**Comment by Paelwastaken** [comment]
Yes, resistance is now correct

**Comment by cagnulein** [comment]
Glad to hear it!
I'm adding the power table now

Il giorno sab 13 gen 2024 alle 10:14 Paelwastaken ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
chatpgt gave me this equation for your power table

`    y = 1.46193548 * x + 0.0000887836638 * x * z + 0.000625 * z * z + 0.0580645161 * x + 0.00292986091 * z + 6.48448135542904;
`

I will implement this later today!

**Comment by cagnulein** [comment]
x is the cadence, z the resistance and Y the power

**Comment by Paelwastaken** [comment]
Is that right? I calculated with resistance 32 and 90 rpm and the power is just 144W, and should be +-315W

**Comment by cagnulein** [comment]
i tried with resistance 16 and the number seems right. i will test it
before committing it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 gen 2024 alle 12:57 Paelwastaken ***@***.***>
ha scritto:

**Comment by Paelwastaken** [comment]
![Captura de ecrã 2024-01-13 120122](https://github.com/cagnulein/qdomyos-zwift/assets/141184701/43408160-fbaf-4bba-94eb-4d8429e51b1d)

**Comment by cagnulein** [comment]
@Paelwastaken i did a first implementation https://github.com/cagnulein/qdomyos-zwift/actions/runs/7526467272
let me know! share a debug log of course I didn't test it
if you want you can use the target watt tile to test it without zwift. enable the erg mode setting in the bike section

**Comment by cagnulein** [comment]
new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/7526753537

**Comment by Paelwastaken** [comment]
Missing accurate power

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7538399339

**Comment by Paelwastaken** [comment]
The formula you used isn't right. I get similar power readings on resistance 1 and 32. 
[debug-Tue_Jan_16_14_30_06_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13951590/debug-Tue_Jan_16_14_30_06_2024.log)
[debug-Tue_Jan_16_14_32_40_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13951591/debug-Tue_Jan_16_14_32_40_2024.log)

**Comment by cagnulein** [comment]
for example? please try to fix it, the code is very easy. focus on this https://github.com/cagnulein/qdomyos-zwift/blob/00307eb2282650a7551f31885f4693749c672cf4/src/ftmsbike.cpp#L101

you can do a PR here on github.
Let me know

**Comment by Paelwastaken** [comment]
what do you mean?

**Comment by cagnulein** [comment]
change the code by yourself :) it's just a math function. So find the issue in the math function and change the code here on github :) QZ is an open source project

**Comment by Paelwastaken** [comment]
It says code view is read only

**Comment by cagnulein** [comment]
you have to fork and then do a PR when you do the modification. You can
read the Github documentation about this! Something new to learn :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 gen 2024 alle ore 15:55 Paelwastaken <
***@***.***> ha scritto:
