### ISSUE TITLE
[BUG] Incorrect speed on Kingsmith K12

### ISSUE THREAD

**Issue by marklogan17** [cagnulein/qdomyos-zwift#1982]
I've had the Kingsmith K12 for about 18 months.  Until recently (could be 6 months :) ) it operated correctly.  However now the speed is off.  Instead of 0.5 Km/h its at 18.2 and goes up from there.  The increment of 0.5KM/h seems to work reasonably well - in other words, it doesn't increase by 9 Km/h every time you hit the + button.  The distance reading seems to be correct too.

I did find the new Kingsmith treadmill settings and tried them all.  They all exhibited the same behaviour.

Output from last walk - note the speed vs the distance.  I was really walking at 4.5 Km/h the majority of the time:
Average Speed: 22.5
Max Speed: 23.0
Calories burned: 2056
Distance: 4.4
Elevation Gain (meters): 0.0
Average Watt: 484
Max Watt: 495
Average Watt/Kg: 5.9
Max Watt/Kg: 6.0
Average Heart Rate: 0
Max Heart Rate: 0
Total Output: 1708
Elapsed Time: 00:58:49
Moving Time: 00:58:49
Weight Loss (Kg): 0.27
Estimated VO2Max: 71

Log file attached.
[debug-Tue_Jan_9_10_58_17_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/13891797/debug-Tue_Jan_9_10_58_17_2024.zip)

**Comment by cagnulein** [comment]
easy call!

speed_offset" QVariant(QString, "18")


you have the speed offset setting to 18, probably you would like to set the
zwift resistance offset to 18 :)

you can put this to 0 and you are good to go!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 gen 2024 alle 19:54 marklogan17 ***@***.***>
ha scritto:

**Comment by marklogan17** [comment]
Ha Ha Ha Ha.  OK, sorry.  I should have made that leap!  Tested and closed!
