### ISSUE TITLE
Horizon 7

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1983]
[btsnooz_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13898786/btsnooz_hci.log)

**Comment by cagnulein** [comment]
hci snoof corrupted

**Comment by kellogg9662** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/13933762/btsnoop_hci.log)

Tried with a different device. Seems to be ok this time

**Comment by cagnulein** [comment]
@kellogg9662 it seems the classic horizon 7 profile. I don't remember your case, did you already try QZ? You need to disable the horizon force FTMS setting (in the settings, treadmill settings, horizon) to enable this protocol
Let me know!

**Comment by kellogg9662** [comment]
Ok, I tried again and it looks like the QZ app does mostly work with my treadmill. It doesn't seem to be able to start through the app, and it takes about a minute to connect, but I think that's just the treadmill being slow. 

However, when I try to use the treadmill with Kinni the speed adjustments don't work. Increasing one mph seems to set it to a random speed and the incline doesn't seem to change from the app at all.

**Comment by cagnulein** [comment]
attach a debug log of this issue and i will check it.
maybe it's just a km to miles conversion issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 gen 2024 alle 03:26 kellogg9662 ***@***.***>
ha scritto:

**Comment by kellogg9662** [comment]
Yeah, definitely seems like that could be it. I also noticed that my treadmill firmware is several versions behind. I'll update it and see if that fixes the issue. If not, I'll capture the debug log.

**Comment by cagnulein** [comment]
@kellogg9662 any news?

**Comment by cagnulein** [comment]
@xYoBro post a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

I will check it tomorrow, i'm going to bed

**Comment by cagnulein** [comment]
@xYoBro any news?
