### ISSUE TITLE
Zwift Play

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#1984]
https://github.com/ajchellew/zwiftplay

**Comment by cagnulein** [comment]
https://www.makinolo.com/blog/2023/10/08/connecting-to-zwift-play-controllers/

**Comment by cagnulein** [comment]
[debug-Tue_Feb_6_18_32_09_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14184255/debug-Tue_Feb_6_18_32_09_2024.zip)

**Comment by Clausmax** [comment]
[debug-tirs__feb__6_20_58_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14185587/debug-tirs__feb__6_20_58_55_2024.log)

Hi Roberto - here is my debug from testing the Zwift Play controllers. Let me know if you need something more.

**Comment by cagnulein** [comment]
perfect @Clausmax did you press the brake button in the last test? i guess not right? I guess that one will be the right one for the gears right? can you press it and post a new log so i can check if i can handle correctly?
thanks!

**Comment by wtafe** [comment]
[debug-Wed_Feb_7_21_29_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14203676/debug-Wed_Feb_7_21_29_05_2024.log)

Cycled through all of the buttons twice. Both controllers appeared connected.

FYI, pairing my bike gave me a *** stack smashing detected ***: terminated error. Had to unpair bike for it to run.

**Comment by cagnulein** [comment]
> Wed Feb 7 22:04:39 2024 1707361479924 Debug: zwift_play/abstractZapDevice.h int AbstractZapDevice::processCharacteristic(const QString&, const QByteArray&, AbstractZapDevice::ZWIFT_PLAY_TYPE) "SyncTx" "526964654f6e"
> "SyncTx" "526964654f6e"
> Wed Feb 7 22:04:39 2024 1707361479924 Debug: bike.cpp void bike::setGears(double) setGears -1
> setGears -1
> Segmentation fault

@wtafe are you able to run gdb and show me a bt (backtrace) screenshot?

**Comment by cagnulein** [comment]
great @Clausmax modification done to handle the brake. 
I'm sending you a new version today!

**Comment by cagnulein** [comment]
@wtafe any news?

**Comment by wtafe** [comment]
`Thread 1 "qdomyos-zwift" received signal SIGSEGV, Segmentation fault.
0x00007ffff6765283 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007ffff6765283 in _Unwind_Resume () at /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00005555555b58aa in  ()
#2  0x00007ffff5cf1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6fb809e in QLowEnergyService::characteristicChanged(QLowEnergyCharacteristic const&, QByteArray const&) () at /lib/x86_64-linux-gnu/libQt5Bluetooth.so.5
#4  0x00007ffff5cf1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff6fc7ea9 in  () at /lib/x86_64-linux-gnu/libQt5Bluetooth.so.5
#6  0x00007ffff5cf1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff6fbe770 in  () at /lib/x86_64-linux-gnu/libQt5Bluetooth.so.5
#8  0x00007ffff6fbe873 in  () at /lib/x86_64-linux-gnu/libQt5Bluetooth.so.5
#9  0x00007ffff587a59b in  () at /lib/x86_64-linux-gnu/libQt5DBus.so.5
#10 0x00007ffff5ce741e in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff776c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff5cb9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff5cbcf27 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5d13a67 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff4b20d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff4b76258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff4b1e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff5d130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff5cb875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x0000555555a3df23 in  ()
#21 0x00005555557d1ea5 in  ()
#22 0x00007ffff5cf1793 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff5cf57fe in QTimer::timeout(QTimer::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff5ce733f in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff776c713 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff5cb9e3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff5d123eb in QTimerInfoList::activateTimers() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff5d12cec in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff4b20d3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff4b76258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff4b1e3e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff5d130b8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff5cb875b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff5cc0cf4 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x0000555555653426 in main ()
`

**Comment by cagnulein** [comment]
Thanks! Did you already pull from the master?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle 20:11 wtafe ***@***.***> ha
scritto:

**Comment by wtafe** [comment]
rebuilt on Weds 2/7 @ 10pm EST. I can rebuild again if there's been a significant commit.

**Comment by cagnulein** [comment]
[debug-Sun_Feb_11_18_37_53_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14233390/debug-Sun_Feb_11_18_37_53_2024.zip)

**Comment by Clausmax** [comment]
[debug-ons__feb__14_21_02_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14285649/debug-ons__feb__14_21_02_13_2024.log)

**Comment by cagnulein** [comment]
note for me

this is the event

07080110011801200128013001380140c8014800

for the left brake button

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 21:16 Clausmax ***@***.***> ha
scritto:
