### ISSUE TITLE
Watts and Cadence no longer being sent to Zwift app (using Echelon EX-5)

### ISSUE THREAD

**Issue by Achillescode** [cagnulein/qdomyos-zwift#1987]
**Describe the bug**

For some reason, watts and cadence are no longer being sent to Zwift app, though it is showing it is connecting to app. 

**To Reproduce**
1. Echelon Ex-5 is plugged in
2. qdomyos app picks it up. 
3. zwift on ipad is turned on
4. it shows that it is connecting to iphone
5. it no longer shows cadence and wattage figures however (see images below) 

**Expected behavior**
It should be showing both cadence and wattage as it had done before

**Screenshots**

![IMG_6544](https://github.com/cagnulein/qdomyos-zwift/assets/44350195/581eb51a-6851-4010-93fa-4ce94ee30c2c)

![IMG_6543](https://github.com/cagnulein/qdomyos-zwift/assets/44350195/262922ab-ae5a-4bdd-8b7a-409548096d67)

**Desktop (please complete the following information):**
 
Zwift app is running on Ipad 8th generation, running 17.2

**Smartphone (please complete the following information):**

 App is running on an iphone 14 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by Achillescode** [comment]
Thank you for quick reply Roberto, love the app. 

I reset network settings.  

Uncertain what you mean by using wahoo virtual device. 

My understanding (and way it worked before) was that echelon connects to qdomyos and then ipad bluetooth picks it up with bluetooth. 

Is there a setting in app to set to wahoo virtual device? I see I can play around with enable virtual device in experimental section but it does not change anything 

Thanks!

**Comment by cagnulein** [comment]
qz is sending metrics in 2 ways: bluetooth and wifi

bluetooth with the iphone name
wifi with wahoo kickr name on zwift

don't you see the second one?

show me your experimental settings or create a debug log so i can check
everything

anyway when it happens this it's a cache issue. try to swap the device
(ipad for qz and zwift for iphone) i guess it will work (just to confirm my
hypothesis)

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:29 Achillescode ***@***.***>
ha scritto:

**Comment by Achillescode** [comment]
I just installed zwift on macbook and watts and cadence coming through. Issue is with tablet then. 

You think it is a caching issue there?

**Comment by Achillescode** [comment]
Fixed after clearing network settings and resetting bluetooth. Thanks again

**Comment by cagnulein** [comment]
yes for sure. that's why i said about reset the network setting on the ipad
and rebooting

usually helps

try also to toggle the ios peloton workaround i qz , restart qz , pair in
zwift and then enable it again  on zwift. this should clear the cache on
ipad

important: ios peloton workaround must be always enabled otherwise you will
have qz  crashes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:54 Achillescode ***@***.***>
ha scritto:
