### ISSUE TITLE
Change speed treadmill

### ISSUE THREAD

**Issue by Johnmat777** [cagnulein/qdomyos-zwift#1988]
Hello, I love the qz application, but I have a problem with my proform 9.0 treadmill after 33 min on qz the speed goes down to 3km/h I reset the desired speed around 45 min the treadmill stops I have to pause qz that I press stop on the treadmill and press play on qz. With the debug file is it possible to know if qz sends information to the carpet? I'm attaching the debug file to you
[debug-mer__janv__10_18_12_15_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13909064/debug-mer__janv__10_18_12_15_2024.log)

**Comment by cagnulein** [comment]
hi @Johnmat777 it's possible that when you collected the hci snoof for me here https://github.com/cagnulein/qdomyos-zwift/issues/805 you started a workout with a 33 minutes timing? i think it's the case, what do you think? Since QZ mimic the hci snoof that you sent me, if there was a 33 limit, it will do this every time.

**Comment by Johnmat777** [comment]
Maybe but is it a problem with qz or the treadmill? Envoyé de mon iPhoneLe 12 janv. 2024 à 07:58, Roberto Viola ***@***.***> a écrit :hi @Johnmat777 it's possible that when you collected the hci snoof for me here #805 you started a workout with a 33 minutes timing? i think it's the case, what do you think? Since QZ mimic the hci snoof that you sent me, if there was a 33 limit, it will do this every time.

**Comment by cagnulein** [comment]
@Johnmat777 is happening always after 33 minutes? or is it random? if it's happening always at 33 time mark, as I said before, it could be just a configuration sent to the treadmill that it's coming from the hci snoof that you did in the #805 
let me know!

**Comment by Johnmat777** [comment]
It happens very days at 33 minutes on qz (30 minutes on the treadmill) if I turn off the treadmill it starts again for 30 minutes. It's like when I throw qz it starts an exercise on the treadmillEnvoyé de mon iPhoneLe 12 janv. 2024 à 10:53, Roberto Viola ***@***.***> a ***@***.*** is happening always after 33 minutes? or is it random? if it's happening always at 33 time mark, as I said before, it could be just a configuration sent to the treadmill that it's coming from the hci snoof that you did in the #805
let me know!

**Comment by cagnulein** [comment]
so it's for sure about the hci snoof that you sent me. I suggest to recreate another hci snoof from ifit app without any time limit limitation, so i can overwrite to the current one in qz! Let me know if you have any question

**Comment by Johnmat777** [comment]
For hci snoof I need an android phone ? 
Envoyé de mon iPhone

**Comment by cagnulein** [comment]
yes following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by Johnmat777** [comment]
[bugreport-2024-01-26-21-58-50.zip](https://github.com/cagnulein/qdomyos-zwift/files/14069473/bugreport-2024-01-26-21-58-50.zip)
Hello attached Bluetooth file

**Comment by cagnulein** [comment]
thanks i will check it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 22:25 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
Thanks Good dayEnvoyé de mon iPhoneLe 26 janv. 2024 à 22:28, Roberto Viola ***@***.***> a écrit :﻿
thanks i will check it in the next days



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 26 gen 2024 alle 22:25 Johnmat777 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
hi @Johnmat777 just checked and there is no bluetooth log here. are you sure you enabled the hci snoof?

**Comment by Johnmat777** [comment]
Hello, how are you ?  And this this file ? Is it the good ?

**Comment by cagnulein** [comment]
I didn't check yet, completely overwhelmed by tasks.
I also got the flu right now  :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 08:37 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
No souci. Take care of yourself
Envoyé de mon iPhone

**Comment by cagnulein** [comment]
hi @Johnmat777 i don't see any other file. you have to attach on github directly otherwise i can't see it
Let me know!

**Comment by Johnmat777** [comment]
[Uploading bugreport-2024-01-30-07-58-35.zip…]()

**Comment by cagnulein** [comment]
it's corrupted, you have to wait the finish of the upload

**Comment by Johnmat777** [comment]
[bugreport-2024-01-30-20-14-19.zip](https://github.com/cagnulein/qdomyos-zwift/files/14103214/bugreport-2024-01-30-20-14-19.zip)

**Comment by cagnulein** [comment]
Unfortunately the hci snoop is still missing. Didn't you do already in the
past?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 20:25 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
Yes, I've already done it. I don't understand
Envoyé de mon iPhone

**Comment by cagnulein** [comment]
Changed phone?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 20:43 Johnmat777 ***@***.***>
ha scritto:

> Yes, I've already done it. I don't understand
> Envoyé de mon iPhone
>

**Comment by Johnmat777** [comment]
Hello how are you ? I find an another android phone, xiaomi redmi9 but I don’t find bug report. Do you help me ? Envoyé de mon iPhoneLe 30 janv. 2024 à 21:00, Roberto Viola ***@***.***> a écrit :﻿
Changed phone?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 30 gen 2024 alle 20:43 Johnmat777 ***@***.***>

ha scritto:



> Yes, I've already done it. I don't understand

> Envoyé de mon iPhone

>

**Comment by cagnulein** [comment]
search in the root of the phone. these chineses phones are behaving
differently from the classic google experience

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 feb 2024 alle 22:29 Johnmat777 ***@***.***>
ha scritto:

> Hello how are you ? I find an another android phone, xiaomi redmi9 but I
> don’t find bug report. Do you help me ? Envoyé de mon iPhoneLe 30 janv.
> 2024 à 21:00, Roberto Viola ***@***.***> a écrit :﻿
> Changed phone?
>
>
>
> Roberto Viola
>
> Software engineer and open source enthusiast
>
> http://robertoviola.cloud
>
>
>
>
>
>
>
> Il giorno mar 30 gen 2024 alle 20:43 Johnmat777 ***@***.***>
>
> ha scritto:
>
>
>
> > Yes, I've already done it. I don't understand
>
> > Envoyé de mon iPhone
>
> >
>

**Comment by Johnmat777** [comment]
Hello, attached. Tell me is good
[bugreport-2024-02-06-21-45-32.zip](https://github.com/cagnulein/qdomyos-zwift/files/14185927/bugreport-2024-02-06-21-45-32.zip)

**Comment by cagnulein** [comment]
nope unfortunately hci snoof is not present there

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 21:52 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
[bugreport-2024-02-06-21-45-32.zip](https://github.com/cagnulein/qdomyos-zwift/files/14186359/bugreport-2024-02-06-21-45-32.zip)

**Comment by cagnulein** [comment]
Same :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 22:48 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
There is a file or nothing ?

**Comment by cagnulein** [comment]
no, there isn't

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 23:13 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
[bugreport-2024-01-26-21-58-50.zip](https://github.com/cagnulein/qdomyos-zwift/files/14221942/bugreport-2024-01-26-21-58-50.zip)

**Comment by cagnulein** [comment]
same thing unfortunately :(
no hci files here :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle ore 14:46 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
Hello, attached 
[bugreport-2024-02-13-07-47-35.zip](https://github.com/cagnulein/qdomyos-zwift/files/14257366/bugreport-2024-02-13-07-47-35.zip)

**Comment by cagnulein** [comment]
still nothing :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 08:12 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
How, do I send the file ? Envoyé de mon iPhoneLe 13 févr. 2024 à 08:27, Roberto Viola ***@***.***> a écrit :﻿
still nothing :(



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 13 feb 2024 alle 08:12 Johnmat777 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
i mean in the zip there is no hci snoof file unfortunately

**Comment by Johnmat777** [comment]
I don't understand I follow the whole tutorial, I do have a newspaper report coming out and you tell me that there is nothing. Yet when we worked together to make it work with this treadmill I did it well with this same phone. I don't know what to doEnvoyé de mon iPhoneLe 13 févr. 2024 à 10:13, Roberto Viola ***@***.***> a écrit :﻿
i mean in the zip there is no hci snoof file unfortunately

**Comment by cagnulein** [comment]
try to enable the hci snoof setting after the reboot or don't reboot at all. maybe android on your phone changed this behaviour from the first time

**Comment by cagnulein** [comment]
@Johnmat777 any news?

**Comment by Johnmat777** [comment]
Hello, i retryEnvoyé de mon iPhoneLe 8 mars 2024 à 22:35, Roberto Viola ***@***.***> a écrit :﻿
@Johnmat777 any news?

**Comment by Johnmat777** [comment]
Hello, i try with a new device 
[bugreport-lineage_gtaxlwifi-SQ3A.220705.004-2024-05-27-21-30-24.zip](https://github.com/cagnulein/qdomyos-zwift/files/15461423/bugreport-lineage_gtaxlwifi-SQ3A.220705.004-2024-05-27-21-30-24.zip)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno lun 27 mag 2024 alle 22:10 Johnmat777 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
perfect @Johnmat777 this time worked! what did you change?

**Comment by Johnmat777** [comment]
I bought a new device, a Samsung galaxy with lineage os and more recently android Envoyé de mon iPhoneLe 28 mai 2024 à 08:29, Roberto Viola ***@***.***> a écrit :﻿
perfect @Johnmat777 this time worked! what did you change?

**Comment by cagnulein** [comment]
hi @Johnmat777 just to be sure: did you collect this hci snoof with the ifit app?

**Comment by Johnmat777** [comment]
Why ? Envoyé de mon iPhoneLe 29 mai 2024 à 08:30, Roberto Viola ***@***.***> a écrit :﻿
hi @Johnmat777 just to be sure: did you collect this hci snoof with the ifit app?

**Comment by cagnulein** [comment]
because in order to implement the speed and incline control i need the ifit bluetooth communication from ifit to your treadmill as described here https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by Johnmat777** [comment]
That's what I did.  I will try it
Envoyé de mon iPhone

**Comment by cagnulein** [comment]
of it it's what you did i will check it again, I was only be sure about this :)

**Comment by Johnmat777** [comment]
At 30 min treadmill jump at 3km/h and 45 min stop. I think it's because the first time I started a 30-minute workout. This time I started a manual training
Envoyé de mon iPhone

**Comment by cagnulein** [comment]
ok i found a very small difference,

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9283799136

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Johnmat777** [comment]
I use this app on iPhone and Apple Watch Envoyé de mon iPhoneLe 29 mai 2024 à 11:38, Roberto Viola ***@***.***> a écrit :﻿
ok i found a very small difference,
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9283799136
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to ***@***.*** mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
ok but can't you try on the same android phone where you got the hci snoof just for a test?

**Comment by Johnmat777** [comment]
It is possible on iOS with TestFlight ? Envoyé de mon iPhoneLe 29 mai 2024 à 11:49, Roberto Viola ***@***.***> a écrit :﻿
ok but can't you try on the same android phone where you got the hci snoof just for a test?

**Comment by cagnulein** [comment]
yes but for ios I have to build it manually instead with android you have already the build ready

**Comment by Johnmat777** [comment]
On android i don’t have application 

Envoyé de mon iPhone

**Comment by cagnulein** [comment]
I don't know how otherwise we can test this. Do you see something on the
treadmill display that can help you identify if it's manual workout or 30
minute workout?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 mag 2024 alle 12:19 Johnmat777 ***@***.***>
ha scritto:

> Ok i try but i run during 45 minutes ? Envoyé de mon iPhoneLe 29 mai 2024
> à 12:07, Roberto Viola ***@***.***> a écrit :﻿
> you don't need it. Just download the apk in the link that I sent above
>
>
>
> Roberto Viola
>
> Software engineer and open source enthusiast
>
> http://robertoviola.cloud
>
>
>
>
>
>
>
> Il giorno mer 29 mag 2024 alle ore 12:05 Johnmat777 <
>
> ***@***.***> ha scritto:
>
>
>
> > On android i don’t have application
>
> >
>
> > Envoyé de mon iPhone
>
> >
>

**Comment by cagnulein** [comment]
in the session where you sent me the file, the warmup was there on the treadmill?

**Comment by Johnmat777** [comment]
Yes, in the old training too. In the old training it lasts 3 minutes and this brings the treadmill time back to 0 minutes. In the file I sent you yesterday I don't know how long it lasts but it's there a little before I pass it.
Envoyé de mon iPhone

**Comment by Johnmat777** [comment]
I Will try tomorrow morning 
Envoyé de mon iPhone

**Comment by Johnmat777** [comment]
What do I charge apk android ? Envoyé de mon iPhoneLe 29 mai 2024 à 17:12, Roberto Viola ***@***.***> a écrit :﻿
maybe with the thing that I changed also this one is fixed. I guess it was part of the initialization frame. Did you try so?

**Comment by cagnulein** [comment]
Download, unzip, install

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 mag 2024 alle 00:22 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
Do I click on the link to GitHub? But then I click on what?Envoyé de mon iPhoneLe 30 mai 2024 à 06:25, Roberto Viola ***@***.***> a écrit :﻿
Download, unzip, install



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 30 mag 2024 alle 00:22 Johnmat777 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Click here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9283799136/artifacts/1547753709

**Comment by Johnmat777** [comment]
What app do you use for dezip in android ? Envoyé de mon iPhoneLe 30 mai 2024 à 07:44, Roberto Viola ***@***.***> a écrit :﻿
Click here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9283799136/artifacts/1547753709

**Comment by cagnulein** [comment]
The default file manager

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 mag 2024 alle 21:41 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
My android device doesn’t download the fileEnvoyé de mon iPhoneLe 31 mai 2024 à 05:44, Roberto Viola ***@***.***> a écrit :﻿
The default file manager



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 30 mag 2024 alle 21:41 Johnmat777 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
You have to sign up to github first from there

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 31 mag 2024 alle 06:46 Johnmat777 ***@***.***>
ha scritto:

**Comment by Johnmat777** [comment]
Hello, I can't download it, I downloaded it and unzip it from my iPhone and sent it to Android but when I click on it nothing happensEnvoyé de mon iPhoneLe 31 mai 2024 à 06:57, Roberto Viola ***@***.***> a écrit :﻿
You have to sign up to github first from there



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 31 mag 2024 alle 06:46 Johnmat777 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Send me a video of what you are doing on android

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 giu 2024 alle 07:33 Johnmat777 ***@***.***>
ha scritto:
