### ISSUE TITLE
Treadmill proform 8.5 - speed and incline tiles don't work

### ISSUE THREAD

**Issue by Jammy-Leroquet** [cagnulein/qdomyos-zwift#1989]
Dear Roberto,

I am using QZ Domyos on my Android phone and Zwift on a MacBook. Everything is fine, I can retrieve the speeds of my treadmill on Zwift. However, the actions on the speed and incline buttons of the Android app have no effect on the treadmill. In summary, communication from the treadmill to QZ Domyos is working (ok), but communication from QZ Domyos to the treadmill is not working (Not OK).
I have tried all of the Proform/Norditrack treadmills listed in the options, and only the Proform SE works as expected to achieve the results described above. All of the others work less well: false values are displayed in QZ and/or speed is not sent to Zwift.
I hope the log file will help you add a new treadmill to your impressive collection. I can help if needed even if I have limited abilities.
Thank you in advance for your help.

Desktop:
 - OS: MacOs
 - Version Big sur 11.7.10

Smartphone:
 - Device: Xiaomi 13T
 - OS: MIUI
 - Version 14.0.11

[debug-Fri_Jan_12_13_46_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13919402/debug-Fri_Jan_12_13_46_03_2024.log)

**Comment by cagnulein** [comment]
hi! in order to add the other side of the communcation follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device with the ifit app! let me know!

**Comment by cagnulein** [comment]
ah wait! i just added it 2 days ago #1955 !
so join the beta from the play store and you will be ready to go!
Let me know!

**Comment by cagnulein** [comment]
you will see the new proform 8.5 setting in the qz version 2.16.31

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will add you to the private beta to speed up the process!

**Comment by Jammy-Leroquet** [comment]
Roberto,

I tested with version 2.16.32 and I get the same result. The speed and incline buttons do not control the treadmill. However, I checked ProForm 8.5 in the options. Maybe it's not an 8.5 but another version that is not yet referenced in your list.

I am attaching:
- photos that may help to identify it, especially
- the HCI with the Ifit app.
- 
![IMG_20240116_135702](https://github.com/cagnulein/qdomyos-zwift/assets/124455249/e5b5d30a-c3a0-4fb5-9d57-c78cc515606e)
![Screenshot_2024-01-16-12-51-34-061_com ifit wolf](https://github.com/cagnulein/qdomyos-zwift/assets/124455249/a331c4db-7909-45ae-87ab-7510215c2303)

[BT_HCI_2024_0116_090436.log](https://github.com/cagnulein/qdomyos-zwift/files/13950586/BT_HCI_2024_0116_090436.log)


Thank you in advance.

**Comment by cagnulein** [comment]
@jsalas-code could you please check if the models is the same of yours?

**Comment by jsalas-code** [comment]
Roberto, That's not the same model as mine, I'm sorry.

**Comment by cagnulein** [comment]
perfect @jsalas-code it's the answer that I want :) could you please post the detail of your treadmill here @jsalas-code so in the setting I will differentiate them. Thanks

**Comment by jsalas-code** [comment]
This is the model I have: PFTL57721-INT.0
https://sfi.iconfitness.com/SalesForceInterface/download/file?fileName=PFTL57721-INT.0-437061.pdf&directory=%2Fpdf%2F

**Comment by cagnulein** [comment]
@Jammy-Leroquet do you have a similar spec file to compare them?

**Comment by Jammy-Leroquet** [comment]
I think mine is the ProForm Sport 8.5. Or at least, it's the closest one I can find. Here's the manual. It's not the Sport 9.0 because I don't have a fan.

[PETL98716.0.pdf](https://github.com/cagnulein/qdomyos-zwift/files/13951639/PETL98716.0.pdf)

**Comment by cagnulein** [comment]
ok thanks i will add it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 gen 2024 alle 15:49 Jammy-Leroquet <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
[formatted_hex_arrays.txt](https://github.com/cagnulein/qdomyos-zwift/files/13963262/formatted_hex_arrays.txt)
arrays for me

**Comment by cagnulein** [comment]
@Jammy-Leroquet  done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7555972314

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
ok no problem, it's this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7555972314/artifacts/1175196074

**Comment by Jammy-Leroquet** [comment]
I just tried this version and it's a mixed success. Thank you very much for the progress!

Without Zwift open:

The incline button works very well.
The speed button works, but I need to restart the treadmill to do so. Otherwise, I cannot use the QZ button or the treadmill's speed buttons. They remain at 0.

With Zwift open:

The incline is not automatic when following a course.
The speed is transmitted to Zwift correctly.

**Comment by cagnulein** [comment]
> I just tried this version and it's a mixed success. Thank you very much for the progress!
> 
> Without Zwift open:
> 
> The incline button works very well. The speed button works, but I need to restart the treadmill to do so. Otherwise, I cannot use the QZ button or the treadmill's speed buttons. They remain at 0.

Yes this supposed to do so, perfect!

> 
> With Zwift open:
> 
> The incline is not automatic when following a course. The speed is transmitted to Zwift correctly.

For auto incline on zwift you need to set your zwift credentials on qz. Did you?

**Comment by cagnulein** [comment]
hah nevermind about zwift, the github version can't connect to zwift. Are you already on the beta version of qz? If so i also sent it to the play store, and so you will see the same version there. So bring it back that version and give it a try
Let me know!

**Comment by cagnulein** [comment]
amazing! i'm so happy about this! please think about supporting this project joining the patreon membership https://patreon.com/cagnulein

Thanks!
