### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Christy603** [cagnulein/qdomyos-zwift#1990]
**Describe the bug**
My qz app on my Apple Watch is only calculating heart rate, not calories during cycling. It previously was working. 
[Uploading debug-Fri_Jan_12_07_26_48_2024.log…]()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Christy603 you have to upload the file again, you have to wait the finish of the upload before pushing the comment button. Thanks
