### ISSUE TITLE
Apple Watch connecting and calculating heart rate but not calories

### ISSUE THREAD

**Issue by Christy603** [cagnulein/qdomyos-zwift#1991]
**Describe the bug**
Trying again to upload. Apple Watch connecting and calculating heart rate but not calories 
[debug-Fri_Jan_12_07_26_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13920536/debug-Fri_Jan_12_07_26_48_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Fri_Jan_12_07_26_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13920542/debug-Fri_Jan_12_07_26_48_2024.log)

**Comment by cagnulein** [comment]
are you able to send me a screenshot of what you are seeing on the watch when the issue occurs? also the distance still stay to 0 on the watch?

**Comment by Christy603** [comment]
Distance says zero as well. Sent from my iPhoneOn Jan 12, 2024, at 9:21 AM, Roberto Viola ***@***.***> wrote:﻿
are you able to send me a screenshot of what you are seeing on the watch when the issue occurs? also the distance still stay to 0 on the watch?

**Comment by Christy603** [comment]
Sent from my iPhoneOn Jan 12, 2024, at 9:21 AM, Roberto Viola ***@***.***> wrote:﻿
are you able to send me a screenshot of what you are seeing on the watch when the issue occurs? also the distance still stay to 0 on the watch?

**Comment by cagnulein** [comment]
if you attached a picture you have to do on the github interface directly in the ticket otherwise i can't see it

i will check again the log but it was everything right for what i saw

**Comment by Christy603** [comment]
Ok, I will send via GitHub. Thanks Sent from my iPhoneOn Jan 12, 2024, at 11:08 AM, Roberto Viola ***@***.***> wrote:﻿
if you attached a picture you have to do on the github interface directly in the ticket otherwise i can't see it
i will check again the log but it was everything right for what i saw

**Comment by cagnulein** [comment]
attach to the same ticket, don't open a new one :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 gen 2024 alle 18:40 Christy603 ***@***.***>
ha scritto:

**Comment by Christy603** [comment]
![IMG_9270](https://github.com/cagnulein/qdomyos-zwift/assets/156444132/9a436074-1727-4a97-9a0e-5ec491ef10d4)
![IMG_9269](https://github.com/cagnulein/qdomyos-zwift/assets/156444132/4f06f620-cf40-4b30-be4c-6715f56ed8a1)
![IMG_9266](https://github.com/cagnulein/qdomyos-zwift/assets/156444132/852e4200-0453-4599-ac36-574cba63aeb9)

**Comment by Christy603** [comment]
Hopefully, i added this correctly! I am obviously not tech savvy!

**Comment by cagnulein** [comment]
yes you did right!

do you have also qz on the ipad? it's maybe open while you are doing a workout on the iphone? i'm thinking about a conflict where 2 instances of qz are trying to access to the same watch. does it make sense to you?

**Comment by Christy603** [comment]
﻿I have the app on my watch, open, my iPhone open but don’t use any other item. I am connected with Strava and it sends the data over after completing Sent from my iPhoneOn Jan 12, 2024, at 12:53 PM, Roberto Viola ***@***.***> wrote:﻿
yes you did right!
do you have also qz on the ipad? it's maybe open while you are doing a workout on the iphone? i'm thinking about a conflict where 2 instances of qz are trying to access to the same watch. does it make sense to you?

**Comment by cagnulein** [comment]
@Christy603 checked again the log and everything seems perfect. I have an idea: did you upgrade the WatchOS in the middle of the 27th Dec and the 3rd Jan? If so try to remove the QZ app on the watch only and then from the watch app on your phone, install it back and give it a try
Let me know!

**Comment by cagnulein** [comment]
amazing! thanks for the feedback!
