### ISSUE TITLE
Treadmill not respondingto the correct tiles in app. Incline goes up with incline tile but . [BUG]

### ISSUE THREAD

**Issue by Pymundo** [cagnulein/qdomyos-zwift#1992]
Treadmill not respondingbto the correct tiles in app. Incline goes up with incline tile but only 1%, then wont go back down, will go down if i use the speed tile.
Treadmill will start with the start tile, but will not respond to the stop tile.
![inbound2404575053537791153](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/8dfcfe2a-d234-4cb7-bb9d-cbc6ad73c8bd)
![inbound8613019775912995778](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/1cf10a87-a3e8-4199-a70d-e7e71fae75d9)
![inbound311151164080429686](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/17d253ea-bae1-413b-91d8-9db18d370b04)
![inbound1823248147290670647](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/92c6d449-23ae-4bf2-bebf-2ae1d599de21)
![inbound1586426912950981803](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/4f47f36c-a579-4a92-9472-6cb1274c01db)
![inbound3355698513968110690](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/25fc28f2-d05e-4c30-954b-aab1b7b5f66b)
![inbound1497389299161637132](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/84bcdb58-bede-4921-b3b8-6dc6fa3fbd57)
![inbound6329904167649798673](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/64a80e13-0b1c-4525-b253-f4b5d1de6db0)
![inbound7201504841695774990](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/67e76d92-d878-4da8-8024-505444d9624f)

**Comment by cagnulein** [comment]
hi @Pymundo could you please attach a debug log?
thanks!

**Comment by Pymundo** [comment]
[inbound3795453483390497059.docx](https://github.com/cagnulein/qdomyos-zwift/files/13939733/inbound3795453483390497059.docx)

**Comment by Pymundo** [comment]
Hope this is correct. 

Thanks Roberto

**Comment by cagnulein** [comment]
@Pymundo I guess I found the issue of your treadmill: does the treadmill have the ability to change only 1% of inclination at a time? so not 0.5% right? if so set the inclination step setting in qz to 1 instead of 0.5

Let me know!

**Comment by Pymundo** [comment]
Yes it can only change 1% at a time, but I already had the app set to 1( changed from 0.5)

**Comment by Pymundo** [comment]
![inbound7995863572936943512](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/b0c5f6be-7e01-427a-9452-d1c545497eea)
![inbound5103154847036072818](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/dd6cdf2c-2e7e-44c1-9647-865b6a8ae43c)
![inbound3448944896593180783](https://github.com/cagnulein/qdomyos-zwift/assets/149714232/2443e6c1-6904-4902-a052-c871d84d8353)

**Comment by cagnulein** [comment]
@Pymundo set the ftms treadmill in the treadmill setting to your treadmill and restart qz. Let me know

**Comment by Pymundo** [comment]
![Uploading inbound3814300038496285529.jpg…]()

**Comment by Pymundo** [comment]
> @Pymundo set the ftms treadmill in the treadmill setting to your treadmill and restart qz. Let me know

Ok, that's changed

**Comment by cagnulein** [comment]
ok so now it's better? i don't see your images. you have to wait the upload of them before pressing comment

**Comment by Pymundo** [comment]
Treadmill is now responding to to the app tiles. Perfect.Now to pair the app to zwift?Can you help me please.

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Jan 2024 at 15:46, Roberto ***@***.***> wrote:   


ok so now it's better? i don't see your images. you have to wait the upload of them before pressing comment

**Comment by cagnulein** [comment]
amazing! now simply enable the android notification icon in the experimetnal settings in qz, and restart qz
then on the same device open zwift and you will see a wahoo device, select it and you're ready to go!

**Comment by Pymundo** [comment]
Is it possible to get qz app onto appletv ? This is my device for zwift

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Jan 2024 at 15:49, Roberto ***@***.***> wrote:   


amazing! now simply enable the android notification icon in the experimetnal settings in qz, and restart qz
then on the same device open zwift and you will see a wahoo device, select it and you're ready to go!

**Comment by cagnulein** [comment]
you can run qz on your phone and zwift on apple tv, this is my default setup :)

**Comment by Pymundo** [comment]
> you can run qz on your phone and zwift on apple tv, this is my default setup :)

Everything is communicating now. It just won't auto speed/incline with zwift.
Any suggestions mate

**Comment by cagnulein** [comment]
did you set your zwift credentials in qz? then restart and this will work
only on free run not workouts
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle ore 18:00 Pymundo ***@***.***>
ha scritto:

**Comment by Pymundo** [comment]
Yes done that. 

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Jan 2024 at 17:02, Roberto ***@***.***> wrote:   

did you set your zwift credentials in qz? then restart and this will work
only on free run not workouts
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle ore 18:00 Pymundo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
share a debug log and I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle 18:03 Pymundo ***@***.***> ha
scritto:

> Yes done that.
>
> Sent from Yahoo Mail on Android
>

**Comment by Pymundo** [comment]
Ok. Much appreciated. 

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Jan 2024 at 17:05, Roberto ***@***.***> wrote:   

share a debug log and I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle 18:03 Pymundo ***@***.***> ha
scritto:

> Yes done that.
>
> Sent from Yahoo Mail on Android
>

**Comment by cagnulein** [comment]
ok but attach a debug log with the issue :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle 18:06 Pymundo ***@***.***> ha
scritto:

> Ok. Much appreciated.
>
> Sent from Yahoo Mail on Android
>

**Comment by cagnulein** [comment]
@Pymundo any news?

**Comment by Pymundo** [comment]
Give up Roberto.  I can't do it.I dont understandhow to create log etc, I don't know what I'm doing.Just thought better to admit defeat,  i took up enough of your time.I had to uninstall the app, it was adjusting my treadmill when I wasn't using the app?Doesn't matter about refund for the app, you have put alot of work into this, consider it my donation. 
Thanks Graham 

Sent from Yahoo Mail on Android 
 
  On Wed, 7 Feb 2024 at 5:53, Roberto ***@***.***> wrote:   


@Pymundo any news?

**Comment by cagnulein** [comment]
@Pymundo i'm sorry to hear this! i mean you already provided a debug log in the past (here for example https://github.com/cagnulein/qdomyos-zwift/issues/1992#issuecomment-1892249782 ) so it's something that you can do.
Anyway it's your choice.
Let me know!
