### ISSUE TITLE
[BUG] Bowflex T8J

### ISSUE THREAD

**Issue by Rafster1882** [cagnulein/qdomyos-zwift#1994]
**Describe the bug**
![IMG_1214](https://github.com/cagnulein/qdomyos-zwift/assets/156476366/ac65f804-0169-4bce-a644-ce486e098691)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi you need to attach the debug log to check it, thanks!

**Comment by cagnulein** [comment]
[debug-Sat_Jan_13_08_40_06_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13927732/debug-Sat_Jan_13_08_40_06_2024.log)
