### ISSUE TITLE
[BUG] watts no longer being above 0 in iOS 2.16.30 beta horizon treadmill

### ISSUE THREAD

**Issue by brianjvolz** [cagnulein/qdomyos-zwift#1997]
**Describe the bug**
Horizon treadmill 7.0 connected to iOS now shows zero watts for completed workout. Previous versions showed a wattage calculation 

**To Reproduce**
1. Connect to treadmill and start workout. 

**Expected behavior**
summary of workout would track Watts over time. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone SE 3
![IMG_0516]

(https://github.com/cagnulein/qdomyos-zwift/assets/468089/2d2fc43b-f9b7-401a-b756-f4f14d2fcc54)

 - OS: [e.g. iOS8.1] 17.2.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @brianjvolz please share a debug log and I can check it! Thsnks!

**Comment by brianjvolz** [comment]
[debug-Mon_Jan_15_06_58_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13940447/debug-Mon_Jan_15_06_58_43_2024.log)

**Comment by cagnulein** [comment]
@brianjvolz that's beucase you selected the Zwift RunPod in the power sensor setting. Are you still using it? otherwise remove it
Let me know!

**Comment by brianjvolz** [comment]
Yes I am using The Zwift RunPod to track my step cadence. This also gets sent to Strava

**Comment by cagnulein** [comment]
ok but the zwift pod doesn't send power right? that's the issue. if you
want disable it from qz and pair it directly on zwift, in this way qz will
calculate the power

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle 18:38 brianjvolz ***@***.***>
ha scritto:

**Comment by brianjvolz** [comment]
No power from the pod. I do want to be able to see my step cadence on qdomyos app though. The only way to show it is by adding it as a power sensor.

**Comment by cagnulein** [comment]
ok so i have to modify the current code. i changed this in order to allow
to use stryd with horizon treadmill.

i will send you a new one with a new patch

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 gen 2024 alle 20:50 brianjvolz ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@brianjvolz fix done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by brianjvolz** [comment]
Used 712. But issue still is the same

**Comment by cagnulein** [comment]
my bad, fixed. i'm sending you another one. thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle ore 14:18 brianjvolz <
***@***.***> ha scritto:

**Comment by brianjvolz** [comment]
[debug-Fri_Jan_19_06_50_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13989212/debug-Fri_Jan_19_06_50_45_2024.log)

**Comment by brianjvolz** [comment]
Still watts at 0

**Comment by cagnulein** [comment]
Sent another one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle ore 13:53 brianjvolz <
***@***.***> ha scritto:

**Comment by brianjvolz** [comment]
Wattage works!
![IMG_0556](https://github.com/cagnulein/qdomyos-zwift/assets/468089/4d1f00f6-eaff-4cf0-973c-0a62b483d1a1)

**Comment by cagnulein** [comment]
great finally! thanks for the help!
