### ISSUE TITLE
[BUG] QZ Companion not connecting to Nordictrack

### ISSUE THREAD

**Issue by MotivatedChris** [cagnulein/qdomyos-zwift#1998]
Treadmill: Nordictrack exp 10i

**Describe the bug**
Set everything up yesterday and had it working! But did not put an update barrier in and overnight iFit updated. Factory reset the treadmill and reinstalled through ADB, no issues. 

Treadmill is on original iFit now. Qz installed. Tried both c1750 and exp 7i settings with treadmill restart. Treadmill dump is showing speed changes so qz is accessing logs. But can not get companion to connect. Tried forcing Wi-Fi connection but nothing is working!

**To Reproduce**
Factory reset, set everything up correctly, not connecting

**Expected behavior**
Connect to companion 

**Screenshots**

**Desktop (please complete the following information):**
 Nordictrack ex10i
Windows machine used for ADB connection 

**Smartphone (please complete the following information):**
 Android s22 ultra, all permissions accepted

**Append a debug log**
[debug-Sat_Jan_13_23_06_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13930323/debug-Sat_Jan_13_23_06_31_2024.log)
[debug-Sat_Jan_13_23_06_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13930324/debug-Sat_Jan_13_23_06_31_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by MotivatedChris** [comment]
Just checked ping from phone, not reachable. Diving into some network settings now, confusing. Can ping from computer. Asus router shows 4 devices. Phone, computer, treadmill, tv. Odd.

**Comment by cagnulein** [comment]
@MotivatedChris Hi yes the main issue is about connection. Maybe you are in different subnets?

**Comment by cagnulein** [comment]
@MotivatedChris any news?
