### ISSUE TITLE
Inclination write from zwift

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2]

**Comment by cagnulein** [comment]
It seems not possible, at least, now. https://forums.zwift.com/t/zwift-and-treadmill-control-questions-recommendations/128710

**Comment by jameshindle1972** [comment]
Hi, I think it has been done https://github.com/RasPelikan/zwifit-incline-tracker

**Comment by cagnulein** [comment]
> Hi, I think it has been done https://github.com/RasPelikan/zwifit-incline-tracker

i will check it, thanks!

**Comment by cagnulein** [comment]
@jameshindle1972 i looked into it and i guess the only way to achieve this is to run hostapd on the raspberry. What do you think?

**Comment by firetrappe** [comment]
This feature would be great in the future. I run Zwift on my iPad, so can't use the RasPelikan mod. I prefer Kinomap for treadmill sessions at the moment as that app does control incline and lets me adjust speed manually.

**Comment by cagnulein** [comment]
@firetrappe i don't know if you are aware that my software could alread adjust the inclination through the train program. You could even load a GPX and follow it adjusting the difficulty level. I don't know if it's a feature that you could use.

Anyway i would like to develop this feature too, is it ok for you to use the raspberry as an Access Point for your iPad? I could write a guide of course.

By the way, thank you very much for your donation!

**Comment by firetrappe** [comment]
@cagnulein I am aware of the train program feature. This is the main reason I intend to capture a log from my Reebok treadmill. I'd like to try and import a GPX file from one of my runs and see how well the treadmill can simulate the actual activity.

I guess I can use the Pi as an AP for the iPad - with guidance lol.
I'm happy to test anything that will help progress.

You're welcome for the donation. It's much cheaper than buying power pedals!

**Comment by cagnulein** [comment]
@firetrappe I guess I could create a raspberry image in order to simplify the setup process.

**Comment by firetrappe** [comment]
> @firetrappe I guess I could create a raspberry image in order to simplify the setup process.

That might be a good idea. We need to get my Reebok TM working with your bridge first though... more work :/

**Comment by jameshindle1972** [comment]
Hi, sorry for not getting back sooner, work has got in the way of fun 👎 

I think development through a rasberry would open up your project, the Zero is very cheap and can be easily setup to start / shutdown so no need for keyboards / screens etc, it would just sit there and merrily 'make it happen'.  I'm not a programmer, just an enthusiast and like tinkering to get things to work, i'm happy to help in any way I can as think the market is really missing something. I was looking to see how I could add the speed changes (from Zwift plans) into the treadmill ......
