### ISSUE TITLE
"-+" keys not working properly with nordictrack x32i

### ISSUE THREAD

**Issue by FredBateman** [cagnulein/qdomyos-zwift#2001]
**Describe the bug**
The fields on the phone are updating correctly when I change the speed or inclination directly on the treadmill.

The speed and inclination "_+" keys work erratically when I use QZ on the phone.

**To Reproduce**
1. Select NT39221 in QZ Companion on the treadmill.
2. Enable "Show taps" and "Pointer location" in developer options on treadmill.
3. The key presses appear but not in the two rows of dots on the sliders. They appear in the middle of the sliders and behave erratically.

**Expected behavior**
The speed and incline should change.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Google Pixel Pro 8
 - OS: Android
 - Version 14 with January 5, 2024 security update

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
 
There is no /Documents/QZ directory. I only see PDFs created by browser in /Documents/ directory.
  
**Additional context**

**Comment by cagnulein** [comment]
hi, are you using the beta from the play store for the debug log? it's a
requirement for android 14

for the coordinates, grab it using this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

midnight here in italy so i will answer you back tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 14 gen 2024 alle 23:55 FredBateman ***@***.***>
ha scritto:

**Comment by FredBateman** [comment]
I updated qz on my phone from 2.14 to 2.16.30.

1) I still do not see a log file. I am using "Files" and clicking on "Documents & other". Is that correct?
2) I see adb-screenshot.bat on github. Where is it installed? It looks like Windows program? I have not installed qz on Windows.

**Comment by cagnulein** [comment]
> 1. I still do not see a log file. I am using "Files" and clicking on "Documents & other". Is that correct?

it's the /Documents folder. Can you show me a screenshot?



> 2\. I see adb-screenshot.bat on github. Where is it installed? It looks like Windows program? I have not installed qz on Windows.

you can download from it https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/tags/3.3.27.zip

**Comment by FredBateman** [comment]
Symptom changed.

Regardless of which "-+" key I pressed I got what you see in the screenshot.

1) I couldn't get to files with Google's "Files". Used a different program and found it.
2) Got screenshot.
3) Sending 7 files.

[debug-Mon_Jan_15_17_14_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13943440/debug-Mon_Jan_15_17_14_02_2024.log)
[debug-Mon_Jan_15_17_14_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13943443/debug-Mon_Jan_15_17_14_02_20
[debug-Mon_Jan_15_17_14_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13943444/debug-Mon_Jan_15_17_14_02_2024.log)
24.log)
![Mon01-15-2024@17-15-16 16](https://github.com/cagnulein/qdomyos-zwift/assets/143889305/7fd17bff-67f9-48e5-9c08-465635703437)
[QZ-Companion-log.txt](https://github.com/cagnulein/qdomyos-zwift/files/13943450/QZ-Companion-log.txt)
[dumpsys.log](https://github.com/cagnulein/qdomyos-zwift/files/13943452/dumpsys.log)
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/13943459/logcat.txt)
[Mon Jan 15 17_14_42 2024.txt](https://github.com/cagnulein/qdomyos-zwift/files/13943475/Mon.Jan.15.17_14_42.2024.txt)
[0QZ-backup-Mon Jan 15 17_14_05 2024.txt](https://github.com/cagnulein/qdomyos-zwift/files/13943476/0QZ-backup-Mon.Jan.15.17_14_05.2024.txt)

Changed .fit extension to .txt.

**Comment by FredBateman** [comment]
Here is a screenshot with the sliders.
![Mon01-15-2024@17-39-59 13](https://github.com/cagnulein/qdomyos-zwift/assets/143889305/b661efaa-356a-46f6-ba1a-7be1fb9fe728)

**Comment by cagnulein** [comment]
ok thanks i will check the coordinates in the next days

**Comment by cagnulein** [comment]
@FredBateman i checked the logs and in no one of them i'm seeing a plus/minus event from qz to the treadmill. did you try in that session?

Could you please do it again?
Also I saw that you were using the device "other" in the companion: did you try to use other profiles to check if the coordinates of the virtual touch event are better?

**Comment by cagnulein** [comment]
ok thanks i will try to check it asap

**Comment by cagnulein** [comment]
ok i'm do the remapping @FredBateman 
I saw in your first post that you said that you selected the NT39221 device. Is it your actual device name or it's one that is very similar?

I need to know your hardware and software version to write it in the companion so that also other users could use the same profile.
Thanks

**Comment by FredBateman** [comment]
It is actually NTL39221. I see that in a number of emails with Nordictrack and on my warranty service contract.

I do not see anything that looks like that on any screen on the treadmill. The following screenshot is the only screen that shows anything like you are asking for.

![Wed01-17-2024@15-27-02 19](https://github.com/cagnulein/qdomyos-zwift/assets/143889305/a861fec6-f65c-4969-b378-b60eef31b123)

**Comment by cagnulein** [comment]
ok perfect, tomorrow i will add these coordinates for your treadmill.
so now you are seeing random touch event when you are pressing the plus and
minus buttons, with the patch these touch events should be redirected to
the actual sliders

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle 21:32 FredBateman ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@FredBateman new build ready! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.28/QZCompanionNordictrackTreadmill.apk

select the new x32i setting that I created for you and restart the treadmill.
Let me know if it's better now. Maybe we need also to adjust a little the coordinates, but now at least you should see the sliders moving

**Comment by FredBateman** [comment]
Installed new version and changed to X32i NTL39211.

Set incline to 0 manually
Press + repeatedly
   6
   13
   21
   28
   36
   control screen
set to 21 manually
Press - repeatedly
   28
   36
set to 3 manually
Press + repeatedly
   9
   17

set speed to .5
Press + repeatedly
   0.7
   control screen 
set speed to 3.0
press + repeatedly (values did go DOWN)
   1.7
   1.2

**Comment by cagnulein** [comment]
seems very uncalibrated i will check the formula again tomorrow
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 18 gen 2024 alle 17:15 FredBateman ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@FredBateman ok i tried to fix the formula
let's try this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.29/QZCompanionNordictrackTreadmill.apk

In case it still doesn't work, I suggest to try manually to check the validity of my formula
Let me know in case

**Comment by FredBateman** [comment]
The incline buttons do not work at all - nothing happens when pressed.

At the default of 0.5 for speed, the changes vary from 0.3 to 0.5.

When I changed the default to 0.1, each press made a change but it was 0.3.

I tried both the "Open GPX" and "Open Train Program" options but they did not work. I pressed on the included workouts and it went to the workout but that was it.

**Comment by cagnulein** [comment]
ok so the speed is better now right?
instead the incline is worst?

are you able to use adb to validate my math formula?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle 18:09 FredBateman ***@***.***>
ha scritto:

**Comment by FredBateman** [comment]
What is your formula?

**Comment by cagnulein** [comment]
let's start from the speed one

this is the formula

```
                            x1 = 1845;     //middle of slider
                            y1Speed = 807 - (int) ((QZService.lastSpeedFloat - 1) * 46.63);
                            //set speed slider to target position
                            y2 = y1Speed - (int) (((reqSpeed * 0.621371) - QZService.lastSpeedFloat) * 46.63);

```

where the QZService.lastSpeedFloat is the current speed, and the reqSpeed is the speed requested for you. all these metrics are in KM/h.

then in order to test it, you have to run the following:
adb shell input swipe x1 y1Speed x1 y2 200

replace the x1, y1Speed and y2 variable with the one above

Let me know the results!

**Comment by FredBateman** [comment]
Just getting back to this. I was "snowed" and then sick.

The speed values are 10 boxes with the integers 0-12.

BUT! The zero box is actually 0.5 mph and the 4 mph and 11 mph boxes are missing. The means speed is not a linear function of y. 

1) is lastSpeedFloat the speed displayed on the treadmill? if so, y1Speed could be negative if the speed is 0.5.
2) how do you get the speed from iFit?

I wrote a program to "tap" each y value (243-808) hoping to create a mapping of y to speed. DIDN'T WORK. When you use "adb shell input tap" the speed goes to the value of the closest box, i.e., you only get integral values.

**Comment by cagnulein** [comment]
> Just getting back to this. I was "snowed" and then sick.

argh! I hope you're feeling better now!

> 
> The speed values are 10 boxes with the integers 0-12.
> 
> BUT! The zero box is actually 0.5 mph and the 4 mph and 11 mph boxes are missing. The means speed is not a linear function of y.

Argh! That's explain a lot!

> 
> 1. is lastSpeedFloat the speed displayed on the treadmill? if so, y1Speed could be negative if the speed is 0.5.

it is the current speed in Km/h got from the treadmill. yes if it's 0.5 it's negative but it shouldn't be an issue since it's just a relative offset to the y coordinate of the 1 mph block.


> 2. how do you get the speed from iFit?

from the ifit log

> 
> I wrote a program to "tap" each y value (243-808) hoping to create a mapping of y to speed. DIDN'T WORK. When you use "adb shell input tap" the speed goes to the value of the closest box, i.e., you only get integral values.


no you have to use the swipe function as I said above
Let me know!

**Comment by FredBateman** [comment]
I don't think your formula is correct.

Both y1Speed and y2 should be equal:
![image](https://github.com/cagnulein/qdomyos-zwift/assets/143889305/83b13e34-6d0b-4cc5-aae4-56ba2a58e58a)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/143889305/2698043e-99d6-49ba-ac81-4dadee2e9855)

**Comment by cagnulein** [comment]
req and last can't be the same
last is the current
req is the new one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 22:37 FredBateman ***@***.***>
ha scritto:

**Comment by FredBateman** [comment]
They might not actually be allowed to be the same but y1Speed and y2 should be the same if lastSpeedFloat and reqSpeed ARE the same.

**Comment by cagnulein** [comment]
yes but these 2 variables can't never be the same since that code is running only when qz is asking to change the speed. so last speed and requested speed are different for sure.

**Comment by cagnulein** [comment]
there is a missing -1 in the b6 formula after the b2. can you validate the formula using adb directly so?

**Comment by FredBateman** [comment]
The b6 cell is y2. I do not see a -1 in your formula.

**Comment by cagnulein** [comment]
yes i said that was an issue and i fixed on git.
but so now test it to find the right formula on your treadmill so i can add
the right one on the apk

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 20:10 FredBateman ***@***.***>
ha scritto:

**Comment by FredBateman** [comment]
I give up!

adb shell input swipe 1845 805 1845 241 200 sets speed to 12.0 (starting is 0.5)

adb shell input swipe 1845 257 1845 241 200 sets speed to 11.9 (starting is 11.6)

That is just one example.

**Comment by cagnulein** [comment]
@FredBateman can you create a formula and validate it? so i can add it inside the companion

it's faster for both of us because you can validate directly.

Remember that it's an open source app and so i need help of everyone to keep it running

thanks!

**Comment by FredBateman** [comment]
1) Is there a new  formula you want me to test?
      you said:
          yes i said that was an issue and i fixed on git.
          but so now test it to find the right formula on your treadmill so i can add
          the right one on the apk
2) I don't see how one (linear) formula can suffice, with the 4 and 11 speeds not on the slider and the 0 speed actually being 0.5. I am thinking we will need multiple equations. One for each of the following ranges:
    .5 - 1.0
   1.0 - 3.0
   3.0 - 5.0
   5.0 - 10.0
   10.0 - 12.0
or we have a table lookup.

That is assuming the fractional speeds are evenly spaced. There is no requirement that they did that. They could have a table lookup and they could choose one of multiple possible y values for one speed.

**Comment by cagnulein** [comment]
Nope, I just correct thst -1 but it wouldn't change the behavior

OK a lookup table sounds fine. Are you able to collect it?



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle 23:55 FredBateman ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@FredBateman Any news?

**Comment by FredBateman** [comment]
I have had some business and personal issues recently. I hope to get back
to this soon.

**Comment by cagnulein** [comment]
no problem, take your time!

**Comment by FredBateman** [comment]
Roberto,

I finally came up with something that I think works.

The slider is very weird. When you go past certain speeds (e.g., 10.1 MPH),
the same "point" starts corresponding with a different speed. It also does
weird things when you use the actual slider in between moving the slider
programmatically.

I looked at your code and saw how you got the "iFit" speed.

The following test code seems to work.

Short explanation: change speed. If iFit speed isn't what you want, change
speed again.

cat changeSpeed.sh
wolflog="/sdcard/.wolflogs/"$(date +%F)"_logs.txt"

speedToY=(0 0 0 0 0 805 799 794 789 784  #  0.5 -  0.9
779 774 770 765 760 755 750 745 740 735  #  1.0 -  1.9
730 725 720 715 710 706 701 696 691 686  #  2.0 -  2.9
681 676 671 666 661 656 651 646 642 637  #  3.0 -  3.9
632 627 622 617 612 607 602 597 592 587  #  4.0 -  4.9
583 578 573 568 563 558 553 548 543 538  #  5.0 -  5.9
533 528 523 519 514 509 504 499 494 489  #  6.0 -  6.9
484 479 474 469 464 459 455 450 445 440  #  7.0 -  7.9
435 430 425 420 415 410 405 400 396 391  #  8.0 -  8.9
386 381 376 371 366 361 356 351 346 341  #  9.0 -  9.9
336 334 331 327 322 317 312 307 302 297  # 10.0 - 10.9
292 287 282 277 272 268 257 252 248 246  # 11.0 - 11.9
241)                                     # 12.0

speedNew=$1

x=1845 # speed x coordinate

# get last iFit speed
adb shell 'grep -i "Changed KPH to:" '$wolflog' | tail -1' | tee logTemp.csv
speedOld=$(awk '/Changed KPH/ {printf "%4.1f\n", $8/1.60934};' logTemp.csv)
# multiple by 10 to remove decimal point
speedOld=$(echo "scale=0; 10 * $speedOld / 1" | bc) # divide by 1 to get
integer

# convert speeds to old and new y coordinates
yNew=${speedToY[$speedNew]}
yOld=${speedToY[$speedOld]}

echo speedOld: $speedOld yOld: $yOld speedNew: $speedNew yNew: $yNew
adb shell input swipe $x $yOld $x $yNew 200

# see if speed was changed to desired speed
adb shell 'grep -i "Changed KPH to:" '$wolflog' | tail -1' | tee logTemp.csv
speedOld=$(awk '/Changed KPH/ {printf "%4.1f\n", $8/1.60934};' logTemp.csv)
# multiple by 10 to remove decimal point
speedOld=$(echo "scale=0; 10 * $speedOld / 1" | bc) # divide by 1 to get
integer

if [ $speedOld -ne $speedNew ]
then
   yNew=${speedToY[$speedNew]}
   yOld=${speedToY[$speedOld]}
   echo '##### changing speed second time #####'
   echo speedOld: $speedOld yOld: $yOld speedNew: $speedNew yNew: $yNew
   adb shell input swipe $x $yOld $x $yNew 200
fi

**Comment by cagnulein** [comment]
hi @FredBateman that's great!

so could I take this one

```
speedToY=(0 0 0 0 0 805 799 794 789 784  #  0.5 -  0.9
779 774 770 765 760 755 750 745 740 735  #  1.0 -  1.9
730 725 720 715 710 706 701 696 691 686  #  2.0 -  2.9
681 676 671 666 661 656 651 646 642 637  #  3.0 -  3.9
632 627 622 617 612 607 602 597 592 587  #  4.0 -  4.9
583 578 573 568 563 558 553 548 543 538  #  5.0 -  5.9
533 528 523 519 514 509 504 499 494 489  #  6.0 -  6.9
484 479 474 469 464 459 455 450 445 440  #  7.0 -  7.9
435 430 425 420 415 410 405 400 396 391  #  8.0 -  8.9
386 381 376 371 366 361 356 351 346 341  #  9.0 -  9.9
336 334 331 327 322 317 312 307 302 297  # 10.0 - 10.9
292 287 282 277 272 268 257 252 248 246  # 11.0 - 11.9
241)                                     # 12.0

```

as a lookup table? shouldn't be enough? if they are static values, each changes should be right, isn't it?

**Comment by cagnulein** [comment]
@FredBateman ?
