### ISSUE TITLE
[BUG] Nordictrack C2150: incline data not showing

### ISSUE THREAD

**Issue by suzycc** [cagnulein/qdomyos-zwift#2002]
1. There is no incline data showing in the QZ app. 
(Additional but less significant issues I encountered: (a) The summary data in the QZ app at the end of my 30-minute run showed a distance of 2 miles but in the Peloton app it showed 0.2 miles (I will attach screenshots). (b) The email summary I received from QZ app said my max speed was 22.5 mph ;   )  (c) Pressing the + and - buttons on speed and incline had erratic results. Sometimes the incline would go up with a + press but the incline will still show as 0.0 in the app.

**To Reproduce**
1. Start a run.
2. No incline data shows in the QZ app. It says at 0.0 regardless of whether the incline is changing.

**Expected behavior**
I expected to see the treadmill incline data appear in the QZ app, reflecting the actual inline occurring on the treadmill.

**Smartphone (please complete the following information):**
 - Device: iPad mini 4
 - OS: iOS 15.7.8
[debug-Sun_Jan_14_14_53_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13933415/debug-Sun_Jan_14_14_53_38_2024.log)
![IMG_2662](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/3392445d-9e6e-4544-aac9-72aed4d6b418)
![IMG_2661](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/13a4e48f-49ef-4d58-aba6-2b672e6ff7eb)
[debug-Sun_Jan_14_14_55_21_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13933416/debug-Sun_Jan_14_14_55_21_2024.log)
[debug-Sun_Jan_14_14_51_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13933418/debug-Sun_Jan_14_14_51_16_2024.log)

**Comment by cagnulein** [comment]
hi @suzycc I guess I already fixed it for the https://github.com/cagnulein/qdomyos-zwift/issues/62
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta! Thanks

**Comment by suzycc** [comment]
The incline now seems to work perfectly! 

Unfortunately, the speed seems to be a little wonky. It fluctuates (in small amounts) almost continuously, even when I don't change anything on the treadmill. And when I press the speed + or - buttons in the QZ app, the results are erratic (it does move up and down but it doesn't necessarily match the speed on the treadmill.) It also didn't show the target speed from the Peloton class.

[debug-Mon_Jan_15_10_56_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13945436/debug-Mon_Jan_15_10_56_13_2024.log)

**Comment by cagnulein** [comment]
hi @suzycc in this session QZ didn't control the speed because you have the speed forcing setting in the treadmill setting disabled (it's disabled by default due to safety reason).
Enable it and restart qz and it will work!
Be aware that in the peloton program that you're doing there was a top speed of 16 Km/h! So be safe!

Let me know!

**Comment by suzycc** [comment]
Hi Robert,

Thanks so much for looking into this.

I don’t want Peloton to control the speed (perhaps I misunderstood the
Peloton target tile’s meaning—I thought it was displayed whether or not
speed was forced.) I want to control the speed on my own.

I was just wondering why the speed in the QZ app was fluctuating
cotinuously and did not match the treadmill speed. It was always close, but
it bounced around 0.1, 0.2, 0.3 from the treadmill’s speed.

Thanks again for your help!

Suzy

**Comment by cagnulein** [comment]
hah ok! i didn't understand your original issue so. So yes, the target speed tile should match the peloton calls (i didn't test this, i don't remember, give it a try).
For ths speed instead is because the treadmill it doesn't send the target speed, but the REAL speed. So it means that the treadmill is getting the real belt speed and it's reporting that to us. So this is so much better because you have a real feeling of what you're doing.

If you want I can add a patch to freeze it with the target ones, but you have a very rare data in this moment, and I guess you should keep it.

let me know what you think

**Comment by suzycc** [comment]
Great!   After I send my last email I did finally wonder if it is  a
feature,  not a bug…

Thanks. I will happily keep it like it is.

Suzy

**Comment by cagnulein** [comment]
usually twice a year in order to don't change often the behaviour to the users. if you send me an email with their email i will send the beta also to them. I'm updating the beta monthly usually

**Comment by suzycc** [comment]
Thank you!! I just signed us all up last night for a 5k race in June, so
they’re all motivated to beat each other right now :   ).

***@***.***
***@***.***
***@***.***
***@***.***

Suzy

**Comment by cagnulein** [comment]
Hi @suzycc github is hiding his email, send me it in a format like name at gmail.com for example
thanks

**Comment by suzycc** [comment]
Hi Roberto,

It’s tokyorockstar  at gmail dot com

Hope that works!

Thanks so much,

Suzy

**Comment by cagnulein** [comment]
done!

**Comment by suzycc** [comment]
Thank you!!

Suzy
