### ISSUE TITLE
Allow for a negative incline on treadmill that supports it when integrating with zwift

### ISSUE THREAD

**Issue by Jarlstig** [cagnulein/qdomyos-zwift#2005]
With the new beta version v 2.16(707) zwift autoincline is working great from a Sole F 85 2023 version.

The Sole F85 treadmill also supports a negative incline to 5  and it would be great if that option also would be supported!

/Best regards Andreas

**Comment by cagnulein** [comment]
sure, which is the bluetooth name of your sole? so i will address the right
profile

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 gen 2024 alle 21:35 Jarlstig ***@***.***> ha
scritto:

**Comment by Jarlstig** [comment]
![image0](https://github.com/cagnulein/qdomyos-zwift/assets/1833408/d39486c0-e7a4-4986-a3fa-c56b15aba5d8)
On Zwift it is F85

Best regards Andreas

**Comment by cagnulein** [comment]
ok great! i will do in the next days

**Comment by cagnulein** [comment]
hi @Jarlstig in qz are you using the sole inclination setting enabled or disabled?

**Comment by Jarlstig** [comment]
@cagnulein  
I am using Fast Inclination and miles unit from device.

The rest of settings under Sole are left unchecked.

**Comment by cagnulein** [comment]
ok perfect i'm doing this right now. are you on android or ios?

**Comment by cagnulein** [comment]
also sorry fast inclination with also inclination right in the sole settings? show me a screenshot so it will be clearer for me :) (the profile in qz are different)

**Comment by Jarlstig** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/1833408/faee3c78-ef3f-4361-9fe3-241c36a85094)

Super! I am using ios.

**Comment by cagnulein** [comment]
ok so you are using the FTMS profile. Got it, i will send you the new version asap.
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Jarlstig** [comment]
After update 2.16(716) it works perfectly! Thanks!
