### ISSUE TITLE
Row Bootcamp Distance in Strava Higher than Rowed

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#2006]
I noticed during the last 2 row bootcamps that the distance that was sent to Strava was almost double of what I completed. During this 30 minute row class I only did 2941 meters, but Strava has me at 5,158 meters. 
I'm assuming it might try to capture what I would have completed during 30 minutes of straight rowing since the bootcamps are 50/50 of rowing/strength. 

![419695223_1499840100561176_6346125381423931394_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/73163d4e-ad81-484d-bdb2-3c05b9b2d43d)
![Screenshot_20240117-090529](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/eae3acd0-1440-45f2-9f9f-b7576f070a5c)
[debug-Wed_Jan_17_08_01_51_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/13966479/debug-Wed_Jan_17_08_01_51_2024.zip)

**Comment by cagnulein** [comment]
thanks i will check this tomorrow!

**Comment by cagnulein** [comment]
got the issue! your rower is keeping send metrics even when you are not
rowing. I added a timeout. It will be in the 2.16.35, i'm pushing it right
now
Let me know when you will try it! Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle ore 18:23 PugMamma ***@***.***>
ha scritto:

**Comment by PugMamma** [comment]
I did a row bootcamp tonight. The distance that was sent to Strava was 20 meters more than rowed (I could see the moving time increasing while I was doing a floor section). I noticed the Moving Time was about 5 seconds behind from when I pressed start on QZ. Not sure if it is just being picky, but I liked when I used to Press Start and Stop that was the time that was sent to Strava. Not sure how the Elapsed time vs moving time goes to Strava. 
Elapsed Time: 00:38:00
Moving Time: 00:23:32
Strava Moving Time: 00:37:52
[debug-Mon_Jan_22_08_04_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14017159/debug-Mon_Jan_22_08_04_34_2024.log)
![Screenshot_20240122-170943](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/9c947321-27dd-4df5-8d18-07c8a0708
![420139986_1753972315071520_441835905591203646_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/c60d0a5f-9992-4501-8f14-fd8de989fc22)
8e8)

**Comment by cagnulein** [comment]
do you have also the fit file from qz? i would like to see if strava adds them somehow. thanks

**Comment by cagnulein** [comment]
> I noticed the Moving Time was about 5 seconds behind from when I pressed start on QZ.

this is because I added a 5 seconds timeout before resetting speed. As I told you your rower is sending metrics even when you stop, so a 5 seconds timeout it sounds to me reasonable as I trade off to stability and resetting. What do you think?

**Comment by cagnulein** [comment]
my guess is that when you press stop, since the rower is sending always metrics , qz is writing some seconds more on the fit file. In order to understand this (that's completely fixable in case), the next time try to press stop on qz, only when you see the speed and stroke rate to 0. Let me know if it's better. if it's so there is an easy fix for this

**Comment by cagnulein** [comment]
@PugMamma any news?

**Comment by PugMamma** [comment]
Can consider this fixed and closed. Thanks again for all your help.

**Comment by cagnulein** [comment]
did you test the thing that i said? did it happen again?
