### ISSUE TITLE
Domyos EB900 bike

### ISSUE THREAD

**Issue by xerobiro** [cagnulein/qdomyos-zwift#2007]
Hi,
I have an issue with automatic resistance when using qz app. I'm able to connect my bike with qz app on the iOS and than with Zwift on PC laptop. When I start pedaling, my cyclist in Zwift is moving... but the resistance is not changing automaticly, I can change it only manualy by +/- buttons on bike console. It can't be changed by +/- in qz app.
Should it be like that? On EB900 Decathlon FAQ page it's confimed that apps can automatically control bike resistance.
Do you have any experience with that?

Here is the log:
[debug-śr__sty_17_21_43_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13968797/debug-sr__sty_17_21_43_31_2024.log)

It could be visible in the log that I tried to change some app setting during this test session, changing resistance manually and re-opened an app.
If I should record it in a different way, please let me know.

Thanks for support in advance!

**Comment by cagnulein** [comment]
mmm that's strange, qz is sending the command to change resistance but the
bike doesn't handle it.

is it working with the domyos app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle 22:17 xerobiro ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
as far as i know all the domyos bikes with electronic resistance have
control by the app. so or it's a bug in the firmware or they changed
something. anyway if you are in time i will ask a refund to decathlon ,
without automatic resistance its losing a lot of its value IMHO

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 gen 2024 alle 22:45 xerobiro ***@***.***> ha
scritto:

**Comment by xerobiro** [comment]
Clear, thanks.
Unfortunately it's not no longer under warranty. It was not used with the app before, so I just found this issue now. I'll check with Decathlon service if they have any solution.
I read in Console 3.2 EN technical sheet
https://www.manualshelf.com/manual/decathlon-usa/console32/technical-specs-english.html
that there is something like Supplier Testing app for iOS. I could be an option to connect and test the hardware as spare parts like console or wires are available to buy.
Do you have any ideas here?

**Comment by cagnulein** [comment]
unfortunately not. but the decathlon support is great, so give it a try

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 18 gen 2024 alle 07:52 xerobiro ***@***.***> ha
scritto:

**Comment by xerobiro** [comment]
OK, will let you know.

**Comment by xerobiro** [comment]
Question sent to Decathlon, waiting for their response.
In the meantime I went through Domyos Console 3.2 technical spec and I found out that my console was produced in September 2019 (sticker with date stamp on its back) and in December 2019 Decathlon updated the firmware to v1.1 and Bluetooth mapping what allows bike to communicate with ‘New EConnected app’.
So as I understood, Bluetooth module is located in the console, so maybe this firmware is reason of my issue?

**Comment by cagnulein** [comment]
could be, but are you able to find the firmware?

**Comment by xerobiro** [comment]
Yes. As I assume that firmware 1.1 is marked by ‘1’ on traceability sticker.
Page 9:
https://fcc.report/FCC-ID/2AH2PCONSOLE32/4701855.pdf

**Comment by cagnulein** [comment]
maybe you can also try to found a console on ebay?

**Comment by xerobiro** [comment]
I can easy buy it directly from Decathlon:

https://www.decathlon.com/products/console-32-en-326569?variant=40020799619134

**Comment by xerobiro** [comment]
On my barcode sticker this ‘1’ is missing. Code is EWC32BKE…

**Comment by cagnulein** [comment]
hah great! they're selling it!

**Comment by xerobiro** [comment]
Hey! I bought a new Domyos 3.2 cosole (production date indicated on its back is March 2023, firmware 1.1) - and it works! Problem of missing auto resistance solved. Of course the production date when your buing new one is a lottery, but I assume that all spare consoles are equpped with v1.1
So no it's a question to Decathlon, do they reall killed all EB training bikes produced before December 2019? If yes, that's a pity.
I keep exchanging emails with Decathlon service, but they still claim ignorance of this problem. I'll let you know how the situation develops...

Now I have another question to you:
- are there any recommended qz presets/settings to use Zwift on my bike? Or should I use standard ones without changing anything?
- I noticed that I can Zwift, finish a ride, save... but save just in a theory, becouse my ride is not visible anywhere in the Zwift'ing history or Strava upload. Do you have any ideas what goes wrong?

Here you can find log from my today's test ride:
[debug-pt__sty_26_17_00_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14068908/debug-pt__sty_26_17_00_26_2024.log)

**Comment by cagnulein** [comment]
great!

the default settings are fine  if you have any issues

for strava you have to add it on the zwift website

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 21:08 xerobiro ***@***.***> ha
scritto:

**Comment by xerobiro** [comment]
Actually Zwift is connected with my Strava. I used to ride on Tacx bike trainer some time ago and it worked well.
So the issue is only with saving now, but there is no error pop-up. All seems to be saved properly. Could be a direct problem of Zwift application.

**Comment by cagnulein** [comment]
i don't know, it's for sure a zwift bug :)

anyway you can pair also qz to strava and when you press stop on qz it will
upload it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 21:48 xerobiro ***@***.***> ha
scritto:

**Comment by xerobiro** [comment]
OK, when I opened qz & Zwift Companion app on iOS and used the option 'Pair through phone' in Zwift on laptop, all works fine. I can save workout and export to Strava.

**Comment by cagnulein** [comment]
ok so you are good to go?

**Comment by xerobiro** [comment]
Exactly :)
