### ISSUE TITLE
[BUG] Does not control NordicTrack T6.5S

### ISSUE THREAD

**Issue by benlad** [cagnulein/qdomyos-zwift#2008]
**Describe the bug**
The qz app connects to the NordicTrack T6.5S and reports speed and incline.  But the controls of the app do not affect the treadmill.

**To Reproduce**
Go to the main qz app page
Click on + in Speed - Nothing happens.
Click on  + in Inclination - Nothing happens.

**Expected behavior**
The app should control the treadmill speed and inclination

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 
 - Version 14

**Append a debug log**
[debug-Wed_Jan_17_14_04_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13976219/debug-Wed_Jan_17_14_04_25_2024.log)

**Comment by cagnulein** [comment]
@benlad Any news?

**Comment by geojoh** [comment]
Hello, I am having the same issue with a v83 firmware. I tried both the ios and the android app. Incline seems to work but speed change, start and pause not. Also, the QZ training says it loads the program but pressing start doesn't do anything. Please let me know if you need further info. Thanks

**Comment by cagnulein** [comment]
@geojoh Is the ifit app allow you to change speed from the app?

Let's start providing a debug log showing the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by geojoh** [comment]
Yes, I can change the speed from the iFit app. I am attaching the debug from my iphone. So the speed is displayed correctly, but cannot be changed. Inclination is displayed correctly and can be changed. The start button and the pause buttons do not work.

**Comment by cagnulein** [comment]
did you try to start the treadmill directly from the treadmill itself and then try to change speed from qz?

**Comment by benlad** [comment]
Sorry for being tardy on this.  I can confirm the following profiles:
Nordictrack T6.5S v81 - Cannot control speed nor incline
Nordictrack T6.5S v83 - Can control incline, cannot control speed

**Comment by cagnulein** [comment]
@benlad @geojoh so please share a hci snoof if possible from an android device running ifit and I will check it https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

@Jaedee #1119 is it still working for you?

**Comment by benlad** [comment]
> did you try to start the treadmill directly from the treadmill itself and then try to change speed from qz?

This does seem to partially work.  With Nordictrack T6.5S v83, I could change the speed with qz after manually setting speed on treadmill button, but I was unable to stop the treadmill from qz.

**Comment by cagnulein** [comment]
> > did you try to start the treadmill directly from the treadmill itself and then try to change speed from qz?
> 
> 
> 
> This does seem to partially work.  With Nordictrack T6.5S v83, I could change the speed with qz after manually setting speed on treadmill button, but I was unable to stop the treadmill from qz.

OK so it should be easy to fix, I need to add the start and stop commands for your treadmill 

@benlad are you on android?

**Comment by benlad** [comment]
Bluetooth snooping...
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14322514/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks did you start and stop the treadmill from the ifit app directly?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 feb 2024 alle 13:39 benlad ***@***.***> ha
scritto:

**Comment by benlad** [comment]
Well, I didn't know how to use the app, so I started a walking workout from the iFIT app and it did start the treadmill.  I then played around a bit with the incline/speed and then stopped the workout from the app.

**Comment by cagnulein** [comment]
Ok, I'll check it out, tomorrow. thanks


Il giorno dom 18 feb 2024 alle 13:41 benlad ***@***.***> ha
scritto:

**Comment by geojoh** [comment]
Do you need any additional logs from the iphone device?

**Comment by cagnulein** [comment]
No I'm fine thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 feb 2024 alle 14:40 geojoh ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Bluetooth snooping... [btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14322514/btsnoop_hci.log)

@benlad unfortunately the file is a 0 byte :( are you able to zip it and upload it again? in the meantime i will check the previous log from the #1119

**Comment by cagnulein** [comment]
@benlad i tried a very alpha version
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7956665391

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by benlad** [comment]
> @benlad unfortunately the file is a 0 byte :( are you able to zip it and upload it again? in the meantime i will check the previous log from the https://github.com/cagnulein/qdomyos-zwift/issues/1119

Not sure why that is. I was surprised it is a binary file.  Try again zipped up: 
[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/14328865/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
@benlad perfect thanks. give it a try to the above link when the build will finish (10 minutes i guess). if it doesn't work I will use the hci snoof stop and start event directly

**Comment by geojoh** [comment]
Hello, is the fix available in the beta or not yet? I just tried the latest beta but the buttons do not work. Thanks!

**Comment by cagnulein** [comment]
hi @geojoh which version are you seeing in the store. the patch that I did it's in the 2.16.46
Let me know

**Comment by benlad** [comment]
I have version 2.16.46, but it doesn't start the treadmill.

**Comment by cagnulein** [comment]
ok i will check the hcisnoof and I will report back

**Comment by geojoh** [comment]
Same here 2.14.64

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/8092110970
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by benlad** [comment]
I have uninstalled the version form play store and installed the apk in [fdroid-android-trial](https://github.com/cagnulein/qdomyos-zwift/actions/runs/8092110970/artifacts/1285003586) (still says version 2.16.46 in the app). I chose the Nordic Track T6.5S v83 in settings (not sure if that is what was the expected).  No improvement.
[Stop button in app seems to go to a view with charts, odd]

**Comment by cagnulein** [comment]
@benlad please share a debug log, i would like to see if the patch was applied correctly

**Comment by cagnulein** [comment]
@benlad Any news?
