### ISSUE TITLE
[BUG] Domyos EL-0557 elliptical - resistance does not change

### ISSUE THREAD

**Issue by Wannageering** [cagnulein/qdomyos-zwift#2011]
**Describe the bug**
On the old Domyos EL-0557 elliptical - resistance does not change while running in Zwift

**To Reproduce**
1. Start elliptical, start QZ, start Zwift
2. Start running, resistance does not change

**Expected behavior**
Resistance should change (at least when +2% or +3%) in Zwift

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/59504339/3fd43ff2-7794-46b9-bb33-33ee4ff47278)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/59504339/4d3535ac-1612-4533-bd6e-8868bd3e10ec)

**Zwift device (please complete the following information):**
 - OS: Latest iPadOS on recent iPad Air (Apple silicon)
 - Version 17.2

**QZ device (please complete the following information):**
 - Device: ASUS P027 tablet (Asus Zenpad 3S 10 Z500M)
 - OS: Android 7.0

**Append a debug log**
[QZ.zip](https://github.com/cagnulein/qdomyos-zwift/files/13989195/QZ.zip)
  
**Additional context**
Running QZ beta (2024-jan-18 2.16.35)

**Comment by cagnulein** [comment]
hi @Wannageering the main issue in the log is `/src/zwift-api/zwift_client_auth.h void AuthToken::handleTokenResponse(QNetworkReply *) Error fetching token:  "Host secure.zwift.com not found"`

are you sure you have a internet connection in the qz device? I suggest to try again to check if you can reach that server.
If so, you have to see a green check mark in the zwift password setting.

Let me know 

#1921

**Comment by Wannageering** [comment]
I’m afraid that Zwift is blocking my old Android device…
Yes I have internet connection, but no green check ✅
[image0.jpeg]
Sent from my iPhone

On 19 Jan 2024, at 14:04, Roberto Viola ***@***.***> wrote:

﻿

hi @Wannageering<https://github.com/Wannageering> the main issue in the log is /src/zwift-api/zwift_client_auth.h void AuthToken::handleTokenResponse(QNetworkReply *) Error fetching token: "Host secure.zwift.com not found"

are you sure you have a internet connection in the qz device? I suggest to try again to check if you can reach that server.
If so, you have to see a green check mark in the zwift password setting.

Let me know

#1921<https://github.com/cagnulein/qdomyos-zwift/issues/1921>

**Comment by Wannageering** [comment]
[QZ phone.zip](https://github.com/cagnulein/qdomyos-zwift/files/13991776/QZ.phone.zip)
New device new error?
This is now an Android 12 device, Asus Zenfone 7 Pro, with the latest updates (android security patch level 5 october 2023 for Android 12).
There is now a green checkmark after the Zwift password (which appeared only after I tested running in Zwift).
But still nothing happens with the resistance, sorry...

**Comment by Wannageering** [comment]
![Screenshot_20240119-172658464](https://github.com/cagnulein/qdomyos-zwift/assets/59504339/26c8b59e-f79b-4776-8d98-a548573e10c1)

**Comment by cagnulein** [comment]
got the issue, i need to do another modification for your case because your elliptical doesn't have the inclination but only the resistance, right?

**Comment by Wannageering** [comment]
Yes that is correct 👍
Sent from my iPhone

On 19 Jan 2024, at 18:35, Roberto Viola ***@***.***> wrote:

﻿

got the issue, i need to do another modification for your case because your elliptical doesn't have the inclination but only the resistance, right?

**Comment by cagnulein** [comment]
perfect, i will do this mod in the next days and I will push another one
I will keep you posted :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle ore 18:40 Danny Hermans <
***@***.***> ha scritto:

> Yes that is correct 👍
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
version pushed on the store. it will be available in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle ore 18:40 cagnulein ***@***.***> ha
scritto:

> perfect, i will do this mod in the next days and I will push another one
> I will keep you posted :)
>
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
>
>
>
> Il giorno ven 19 gen 2024 alle ore 18:40 Danny Hermans <
> ***@***.***> ha scritto:
>
>> Yes that is correct 👍
>> Sent from my iPhone
>>

**Comment by Wannageering** [comment]
2.16.38, is that the right version? Doesn't seem to do anything different, what would be the best way to test it? I tried in Zwift with a 3% incline and that felt the same as before
[QZ phone version 38.zip](https://github.com/cagnulein/qdomyos-zwift/files/14042042/QZ.phone.version.38.zip)

**Comment by cagnulein** [comment]
ok i will check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle 18:58 Danny Hermans ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Wannageering log checked, actually it worked
check here

```
Wed Jan 24 18:39:42 2024 1706117982920 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 2"
Wed Jan 24 18:39:44 2024 1706117984471 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 3"
Wed Jan 24 18:39:45 2024 1706117985290 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 4"
Wed Jan 24 18:39:45 2024 1706117985979 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 4"
Wed Jan 24 18:39:48 2024 1706117988657 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 5"
Wed Jan 24 18:40:03 2024 1706118003413 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 5"
Wed Jan 24 18:40:04 2024 1706118004128 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 5"
Wed Jan 24 18:40:04 2024 1706118004896 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 6"
Wed Jan 24 18:40:05 2024 1706118005896 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 7"
Wed Jan 24 18:40:06 2024 1706118006708 Debug: ../src/bluetooth.cpp void bluetooth::debug(const QString &) "writing resistance 8"
```

maybe resistance 8 it's too low for you? increase the zwift resistance offset setting so (set it as the resistance that you feel like a flat road)

let me know

**Comment by Wannageering** [comment]
That might actually be me changing the resistance using the tile in the QZ app... In Zwift it never went higher than +3%
I was testing if the QZ app itself can still change the resistance, and yes it can. But Zwift is not changing it (I think).

**Comment by cagnulein** [comment]
got the issue, you have to disable the "Inclination Supported" setting in the domyos elliptical settings in qz
let me know!

**Comment by Wannageering** [comment]
Yes that is the one, now it works, thanks!!!
Question: is there are way to spread the resistance changes further apart?
At 3% in Zwift the elliptical goes to setting 10 already (of 15 total)

**Comment by cagnulein** [comment]
> At 3% in Zwift the elliptical goes to setting 10 already (of 15 total)

yes change the zwift resistance offset. that value is the resistance value that you have when the incline is 0% to zwift
