### ISSUE TITLE
[BUG] Qdomyos-zwift doesn't connect to Echelon 5x-22 (Glorystar nebula 215 tablet)

### ISSUE THREAD

**Issue by DomLam21** [cagnulein/qdomyos-zwift#2013]
**Describe the bug** (follow up from Facebook post, name is Dominic Lamoureux)
I rooted the tablet and installed the Lawnchair2 launcher on the tablet, from there I downloaded the QZ app from amazon store directly on the tablet. Opened the QZ app and it is stuck at Connecting (never connected). The blue light is flashing, location services is ON, bluetooth is ON. Thanks for looking into this for me, very appreciated!!

I have attached 2 debug logs of two different days (if that helps)
[debug-Fri_Jan_19_09_29_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13991555/debug-Fri_Jan_19_09_29_18_2024.log)
[debug-Thu_Jan_18_13_59_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13991556/debug-Thu_Jan_18_13_59_04_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi, this is the issue

Search not possible due to turned off Location service

as i said something is preventing qz to check the location services. can
you try with google maps or similar to see if the location services are
working?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle 17:16 DomLam21 ***@***.***> ha
scritto:

**Comment by DomLam21** [comment]
I tried google maps and you're right, it's not able to find my location.. but the location is on in my tablet's setting (see picture for reference)

Would you know a way to fix that? I'll try and look online to see if anyone has a similar issue

Dominic Lamoureux
Ostéopathe D.O
________________________________

**Comment by cagnulein** [comment]
on the facebook group i'm sure someone had the same issue. check on the
2022 threads

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle 18:18 DomLam21 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@DomLam21 did you fix it?
