### ISSUE TITLE
[BUG] Echolon Sport won’t connect to Zwift

### ISSUE THREAD

**Issue by manuelagostofl** [cagnulein/qdomyos-zwift#2014]
**Describe the bug**
Just switched from using Peloton to using Zwift. Followed the published instructions and I don’t see my bike (qz app from phone) under Power Source or Speed Sensor. I’m using an iPhone to run app and iPad to run Zwift just like I do with Peloton. I have disabled all Peloton options in the qz app.

phone with qz app is running iOS 17.2.1; 
iPad with Swift is running iOS 16.7.4

This is same setting used with Peloton with no issues; I can see bike cadence and resistance in my peloton app using qz app. 
[debug-Fri_Jan_19_12_34_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13993121/debug-Fri_Jan_19_12_34_08_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi! the main issue is that the virtual device setting in the experimental
settings is disabled. enable it and restart qz

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle 19:54 manuelagostofl <
***@***.***> ha scritto:

**Comment by manuelagostofl** [comment]
Perfect! It works. Thanks for your helpSent from my iPhoneOn Jan 19, 2024, at 12:59 PM, Roberto Viola ***@***.***> wrote:﻿
hi! the main issue is that the virtual device setting in the experimental

settings is disabled. enable it and restart qz



let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 19 gen 2024 alle 19:54 manuelagostofl <

***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Glad it worked!


Il giorno ven 19 gen 2024 alle 21:27 manuelagostofl <
***@***.***> ha scritto:
