### ISSUE TITLE
[BUG] KSports Fitshow / FTMS Bike won't connect

### ISSUE THREAD

**Issue by acgourley** [cagnulein/qdomyos-zwift#2016]
**Describe the bug**
This bike works with other apps like BitGym. I've confirmed it advertises both a FitShow and FTMS service. 

**Smartphone (please complete the following information):**
 - Device: iPadOS 17.2
 - Android 14

The device name is "KSU1102" and the model is [this one](https://www.kathysuniverse.com/products/ksports-exercise-bikes-black-magnetic)

[debug-Fri_Jan_19_12_46_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13994356/debug-Fri_Jan_19_12_46_53_2024.log)

**Comment by cagnulein** [comment]
perfect could you also please append a nrfconnect screenshot about it?
Confirmed, I never saw this bike :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 gen 2024 alle 21:51 acgourley ***@***.***>
ha scritto:

**Comment by acgourley** [comment]
![Screenshot 2024-01-19 at 1 03 05 PM](https://github.com/cagnulein/qdomyos-zwift/assets/7680/951f2255-f8a5-4ac9-b3ea-1b5fb492697d)

**Comment by cagnulein** [comment]
perfect , thanks. i will add it asap

in the meantime i just sent you a newer testflight version.

go into the settings, bike settings, ftms bike and select your bike and press ok.

it should be enough :) 

let me know

**Comment by acgourley** [comment]
Confirmed that TF version works!

**Comment by cagnulein** [comment]
great! does it also work the resistance tile to increase and decrease the resistance from qz directly?

**Comment by acgourley** [comment]
This bike only has a physical resistance setting.
