### ISSUE TITLE
[BUG] Domyos run 500 (TC-0421) crashes app

### ISSUE THREAD

**Issue by matthijsberk** [cagnulein/qdomyos-zwift#2017]
**Describe the bug**
The qz domyos app on MacOS, IOS, and IpadOS crashes when it connects to the treadmill. It recognizes the treadmill, it connects but shortly after that the qz app crashes. 

**To Reproduce**
1 turn on treadmill
2 start qz domyos app
3 qz domyos app connects with treadmill for a second
4 app crashes to homescreen (on all three platforms)

**Expected behavior**
The app should connect with the treadmill.

**Screenshots**
.
![IMG_8700](https://github.com/cagnulein/qdomyos-zwift/assets/9346885/0b96e2e5-6e1a-46ce-a32a-8273827f466a)
![IMG_8699](https://github.com/cagnulein/qdomyos-zwift/assets/9346885/8a7a6034-db86-4080-8934-9949b212b742)
![IMG_8698](https://github.com/cagnulein/qdomyos-zwift/assets/9346885/15926fec-a087-4f49-9125-279ff5b072f4)

**Smartphone (please complete the following information):**
 - Device: Iphone 12 pro, macbook pro 2018 (intel)
 - OS: IOS 17.2.1
 - Version  2.15

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ah that's a new version of domyos treadmill with ftms support! i will add it!
thanks

**Comment by cagnulein** [comment]
@matthijsberk i'm doing the patch, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you a new beta. Thanks

**Comment by matthijsberk** [comment]
Did a quick test this morning and the app connects to the treadmill and communicates (can change the speed and incline). Will try more in couple of days when connecting to zwift.

**Comment by cagnulein** [comment]
great! let me know!

**Comment by matthijsberk** [comment]
All Works in zwift! Even the auto incline function is working like a charm! Thank you for the fast responses and solution!

**Comment by matthijsberk** [comment]
All Works in zwift! Even the auto incline function is working like a charm! Thank you for the fast responses and solution!
