### ISSUE TITLE
Stacked Tread Classes Have Negative Distance 

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#2018]
When playing a Pelton tread classes back to back, I get a negative distance in the second class.  If I close down QZ and restart between each class it is fine. QZ recorded the accurate distance, but Peloton is not. 

[debug-Fri_Jan_19_12_19_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13995372/debug-Fri_Jan_19_12_19_02_2024.log)
![Screenshot_20240119-130806](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/c8bccf59-8493-49c6-a29b-57e7d286d241)
![420948123_10162887589748765_7601978955478384653_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/7225872d-4448-46cb-9525-942f2a54e374)
![421267213_10162887589738765_343688321598179119_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/d5ecd6b9-ab75-4241-a314-a522580dd62f)

**Comment by cagnulein** [comment]
found an issue @PugMamma i guess it's my fault! i'm fixing this in the 2.16.36 (already patched, I have only to send to google). Thanks for the feedback as always!

**Comment by cagnulein** [comment]
eheheh that's why I always want to check the issues, I'm not bulletproof :)
1:00am here, time to go to bed! Have a nice day!

**Comment by cagnulein** [comment]
version pushed on the store. it will be available in the next days

Roberto Viola
Software engineer and open source enthusias
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle ore 00:41 PugMamma ***@***.***>
ha scritto:

**Comment by PugMamma** [comment]
I saw there was a QZ update today and unsure if it included a fix for this issue. I tried to take 2 classes back to back and had the same problem. The distance QZ sends to Strava is still correct. 
[debug-Mon_Jan_22_17_59_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14017659/debug-Mon_Jan_22_17_59_27_2024.log)
![Screenshot_20240122-182343](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/c8b8af81-157d-41a6-a490-d8583694f706)
![Peloton DistanceJPG](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/976beabe-c218-4f93-a444-c552cfebfdd0)

**Comment by cagnulein** [comment]
ok so it wasn't the qz issue even before. I understood now what peloton does.
When you press the start button on qz, qz clear the odometer starting back from 0 and so it sends to peloton from 0 but peloton, when runs in stack mode, it wants to see a progressive odometer (so they are just stupid because they should manage this event, even or real treadmill).

So there are multiple fixes for this:
1) restarting qz after a class (it could be frustrating, since there is no need to do this)
2) unpair and pair the qz onto pelotn app (this should force peloton to consider qz as a new device). This could be frustrating too since there is no need to do this.
3) i can send not the odometer that you see on the screen but the accumulate of the odometer since the start of qz. This should fix at all the issue and should be transparent for you.

Do you agree that the 3rd option could be the one?

**Comment by cagnulein** [comment]
modification done. it will be in the 2.16.38 and above

**Comment by PugMamma** [comment]
Great thanks! Just as a note, Peloton has to pair with the treadmill/QZ during the start of each class.

**Comment by cagnulein** [comment]
version online

**Comment by PugMamma** [comment]
I did 2 classes back to back and at first it seemed promising. Peloton had the second class start off at 0 (not a negative distance). When there was about 5 minutes left in the class I noticed that Peloton was no longer having the metrics update. It stayed at 0.73 miles and it didn't change my speed or incline. 
I plan to try back to back classes again over the weekend so unsure if just a fluke or I can just blame Peloton 
[debug-Thu_Jan_25_08_32_46_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14057899/debug-Thu_Jan_25_08_32_46_2024.zip)
![Peloton Hike](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/d0705685-c2b9-4899-82e3-9daa38843a18)

**Comment by cagnulein** [comment]
ok that's definitely an improvement!
i checked the log and qz is writing the distance correctly to the peloton app till you press stop the 2nd time.
The total distance sent from QZ was 5km (so the sum for the first and the second one).
So everything is right from my side.
This time it's for sure a peloton bug :)
only the distance stopped? or also the other metrics?

**Comment by PugMamma** [comment]
Everyone on Peloton's side seemed to pause/freeze (distance and incline). I'll continue on testing it out and see if it was a one off issue.

**Comment by cagnulein** [comment]
Ok, thanks for the update.


Il giorno ven 26 gen 2024 alle 18:24 PugMamma ***@***.***> ha
scritto:

**Comment by PugMamma** [comment]
QZ and Peloton matched up in the second class. Thanks again!
![419450357_761794449187608_6450216483118651243_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/071cad2e-f740-4ffe-8adb-d3809947d960)

**Comment by cagnulein** [comment]
finally!
