### ISSUE TITLE
Not tracking peleton kms 

### ISSUE THREAD

**Issue by abronxtale** [cagnulein/qdomyos-zwift#2020]
Hi

wondering how it doesn’t track my kms

it tracks when I ride though. 

thanks 
![IMG_4946](https://github.com/cagnulein/qdomyos-zwift/assets/155926600/718ff3b7-71ea-4046-b676-ffe5dc09c4bd)

**Comment by cagnulein** [comment]
@abronxtale i'm not a peloton user, I suggest to make this question on the QZ Facebook group. thanks, anyway i guess it's not something on qz :)
