### ISSUE TITLE
[BUG]Heart Rate with Garmin watch not accurate

### ISSUE THREAD

**Issue by username4112** [cagnulein/qdomyos-zwift#2021]
**Describe the bug**
When using Garmin Forerunner 265s and QZ app and then with my iphone using the QZ app and Ipad using Peloton, my heart rate is very low for what it should be.  The heart rate works when I run or do other activities with my watch. There was one class where my heart rate seemed to be more accurate. 

I've attached the debug report and below is a photo of my heart rate on my watch about a minute after I finished my ride.
[debug-Sat_Jan_20_08_54_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13998259/debug-Sat_Jan_20_08_54_18_2024.log)

![IMG_5603](https://github.com/cagnulein/qdomyos-zwift/assets/157224851/f8d5bc0d-fc2f-4b87-aa93-c976e91c43b4)
**Smartphone (please complete the following information):**
 - Device: Garmin Forerunner 265s
 - OS: 17.26
 - Version 1.2.6

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 15:46 username4112 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
in the log i'm seeing hr from 88 to 108 from the garmin. is it not real? did you see the same value also on the qz companion?

**Comment by username4112** [comment]
Yes I do but that is not what my heart rate should be at.  It should be much higher.  After getting out of the app my garmin showed my heart rate at 139.  My average heart rate when cycling for a lower impact ride, is between 130-150. Even moderate activity (currently I'm cooking) my heart rate is 101.

**Comment by username4112** [comment]
I suspect that there is something in my qz watch app that is not allowing an accurate hr read.  My hr on garmin is 103, then going to the qz app where it starts at 82 goes down to 80, then up to 96.  It appears to have some effect on the hr reading in the garmin hr section where it starts at 96 goes down to 86, and then goes back up to 103.  I'm sitting down so there is no extra exertion for that.

**Comment by cagnulein** [comment]
ok so just to be sure to have understood correctly: the issue starts from
the watch itself with the qz companion app open right?

maybe you have an hr band connected to the watch? qz is getting the hr from
the garmin api, but maybe garmin is reading somewhere else? does it make
sense to you?

if not i will check the implementation to check if i can do something in
order to use only the wrist hr

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 19:56 username4112 ***@***.***>
ha scritto:

**Comment by username4112** [comment]
Yes, it starts with the qz app on the garmin watch.  I have no other hr band or anything to read hr.

Thanks for all your help!

**Comment by cagnulein** [comment]
sounds like a ghost! :D i will check this in the next days!
Have a nice weekend!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 20:49 username4112 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
SENSOR_ONBOARD_HEARTRATE | 8 | API Level 3.2.0
-- | -- | --


<br class="Apple-interchange-newline">

i found that Garmin added this kind of device too. Let me try to add this

**Comment by cagnulein** [comment]
@username4112 i'm uploading a new verison (1.2.7) of the companion to check if you see somehting different. i enabled the onboard_heartrate device as well. For my edge it wasn't necesserary but maybe it is for yours
let me know! i'm curious!

**Comment by username4112** [comment]
I'll ride tomorrow and see!  Thanks!!

**Comment by cagnulein** [comment]
did you get the update already?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 22:56 username4112 <
***@***.***> ha scritto:

**Comment by username4112** [comment]
I got the update and did the ride.  It worked for the first 5 minutes then dropped significantly (down to 90) then popped back in at minute 10.  Also, didn't realize that the HR does colors for the zones.  So it was colors then the grey for the drop down, then back to colors.

**Comment by cagnulein** [comment]
ok so that's great! why? because in the current version i left the both device : the onboard one and the classic one. i guess qz is now reading both.

so for sure your watch is getting an hr from an external device (probably an ant+ device around you). are you aware of this?

anyway i will try to put a condition to ignore it in the next version 

just a clarification: you never got a right bpm like this morning for 5 minutes on the past versions, right?

**Comment by username4112** [comment]
That is great! And out of all my rides I had one that had the right bpm and I can't explain how since I was doing everything the same.  I don't think that ride had the zone colors like the one this morning.

**Comment by cagnulein** [comment]
@username4112 in order to validate my idea, could you please check in the ant+ setting sensors ( https://www8.garmin.com/manuals/webhelp/vivoactivehr/EN-US/GUID-78517C88-66A5-4428-9CFC-05875815203E.html#:~:text=You%20can%20manually%20add%2C%20turn,or%20remove%20ANT%E2%80%8D%2B%C2%AE%20sensors.&text=Select%20Settings%20%3E%20Sensors.,Select%20an%20option. ) if you have a paired ant+ hr? if so can you please remove it and give it a try?

**Comment by username4112** [comment]
I have nothing else connected in that section. Auto Discover is on, then HR -  qdomyos0swift, compass, altimeter, barometer.

**Comment by cagnulein** [comment]
ok let's try so. version 1.2.8 pushed. let me know if it's better. i removed any possibility to get HR from external, i'm just using the onboard one.
I hope nobody is using qz with an ant+ hr device connected from the companion otherwise this will break it

**Comment by cagnulein** [comment]
hi @username4112 were you able to try? I'm very curious

**Comment by cagnulein** [comment]
amazing! I'm closing this one, let me know if you will have any other issues!

**Comment by cagnulein** [comment]
@username4112 i just updated a 1.2.9 to address another issue. could you please check that it's still working for you?

**Comment by username4112** [comment]
Still working for me perfectly!

**Comment by username4112** [comment]
Hi Robert! I haven't ridden in a while but today my HR was fine for the first minute, then dropped to 73 and was at 73 the rest of the 45 minute ride. I haven't changed any settings or done anything to my qz app on my phone or watch.

Thanks!

**Comment by cagnulein** [comment]
I didn't change anything on my side. Are you able to share a debug log from qz?

**Comment by username4112** [comment]
Yes. I have two for some reason.  
[debug-Sun_Feb_18_06_39_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14325626/debug-Sun_Feb_18_06_39_45_2024.log)

**Comment by username4112** [comment]
[Uploading debug-Sun_Feb_18_05_30_09_2024.log…]()

**Comment by cagnulein** [comment]
hi @username4112 unfortunately the second log is corrupt. could you please upload it again (you have to wait the finish of the upload before pushing the comment button). Thanks

**Comment by username4112** [comment]
> so sorry! Reuploading now. I did a ride this morning end it seemed to work fine. Did nothing different. Maybe yesterday was a fluke. 
[debug-Sun_Feb_18_05_30_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14335759/debug-Sun_Feb_18_05_30_09_2024.log)

**Comment by cagnulein** [comment]
Ok i will  chdck the log anyway

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 feb 2024 alle 19:22 username4112 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@username4112 I would like to send you the qz beta version to understand better. Could you please send me an email to Roberto.viola83 at gmail.com ?

Thanks

**Comment by username4112** [comment]
On it!

**Comment by username4112** [comment]
Ok, I used the beta version of the app this morning.  It was better, but I think the issue might be with the watch.  My heart rate was not stuck on this ride, but was about 70-80 below what it should have been.

**Comment by cagnulein** [comment]
are you able to share the debug log?

**Comment by username4112** [comment]
[debug-Tue_Feb_20_07_35_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14345076/debug-Tue_Feb_20_07_35_33_2024.log)

**Comment by cagnulein** [comment]
that's very strange, yes the watch is reporting a very low value that changes, so it seems that somehow is reading it from I don't know where.

Are you living in a condo or in a place where there could be any other devices outside the house that have Heart Rate readings?

**Comment by username4112** [comment]
Yeah I’m in an apartment complex.  It is strange that it would be reading something else but who knows  ¯\_(ツ)_/¯ I did just discover that it can broadcast the hr so perhaps that can be my workaround for now. See if that will help.

**Comment by cagnulein** [comment]
if so you can simply don't use the companion and bind your watch in the heart rate belt setting in qz and disable the garmin companion setting in QZ

**Comment by username4112** [comment]
Ok thanks! I’ll try that on my next ride.  Thanks for all your help!!
