### ISSUE TITLE
Enerfit SPX 9500

### ISSUE THREAD

**Issue by elisaceto** [cagnulein/qdomyos-zwift#2022]
La mia App QZ si collega correttamente alla mia bike Enerfit SPX 9500 che ha un computer iconsole identico alla Toorx SRX 500 ma mostra tutti i valori a zero. Cosa posso fare? Allego log
[debug-Sat_Jan_20_19_05_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13998870/debug-Sat_Jan_20_19_05_03_2024.log)

**Comment by cagnulein** [comment]
@elisaceto ciao, nei settaggi di iconsole in qz, abilita iconsole bike e riavvia l'app.

fammi sapere se risolvi altrimenti rimandami un debug log che ci guardo 

buona serata!

**Comment by elisaceto** [comment]
Grazie per la risposta. Lo avevo già fatto e continua a non funzionare. L'ho rifatto e preso i log che allego. Grazie ancora
[debug-Sat_Jan_20_20_50_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13999078/debug-Sat_Jan_20_20_50_37_2024.log)

**Comment by cagnulein** [comment]
ok però qui vedo la resistenza a 5 quindi qualcosa legge giusto?
domani provo a capirci qualcosa in più probabilmente dobbiamo solo cambiare
"dialetto " di protocollo
ti faccio sapere

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 21:05 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Effettivamente con la spunta iconsole legge la resistenza e posso anche modificarla. Il resto delle letture rimane a zero. Grazie

**Comment by cagnulein** [comment]
nell'ultimo log che hai messo stavi pedalando?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 21:13 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Si

**Comment by cagnulein** [comment]
ok quindi provo a vedere se c'è qualcosa oltre alla resistenza

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle 21:17 elisaceto ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok allora non c'è nulla ma direi di aver capito, la tua bici si aspetta una
differente richiesta da parte mia. per scoprirlo, semplicemnete raccogli i
dati con la app kinomap usando questa guida
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
dopo di che io farò lo stesso su qz e vedrai le metriche e le potrai
inviare su zwift!
Fammi sapere!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 gen 2024 alle ore 21:18 cagnulein ***@***.***> ha
scritto:

**Comment by elisaceto** [comment]
Ammesso che io sia riuscito a seguire bene la guida, allego 2 log: il primo collegando kinomap alla bike e il secondo iconsole+. Grazie

[Download.zip](https://github.com/cagnulein/qdomyos-zwift/files/14002641/Download.zip)

**Comment by cagnulein** [comment]
Ciao, ma come hai ottenuto questi file? non mi sembrano corretti a me serve un file chiamato hci snoof o similare.

**Comment by elisaceto** [comment]
Allora non sono riuscito a seguire la procedura perché non ho ben capito la seconda parte:
1) ho abilitato le opzioni sviluppatore
2) ho attivato i log HCI bluetooth
3) collego kinomap e pedalo un po'
4) disattivo i log HCI
5) .... Credo di non aver trovato la voce per i passaggi successivi nelle opzioni sviluppatore....

**Comment by elisaceto** [comment]
Ecco gli screenshot delle voci di debug
![Screenshot_2024-01-22-08-13-05-626_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/ede77d4e-7405-4935-9582-f14dc4a878dd)
![Screenshot_2024-01-22-08-12-57-791_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/d5b21e59-a4d2-4010-9770-c625b363f84b)
![Screenshot_2024-01-22-08-12-49-953_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/b19f3644-eb5a-4f29-8c72-b05e9c5d8d80)
![Screenshot_2024-01-22-08-12-43-672_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/bac6b5a6-b5d7-47f8-87a3-a167a4fdfbcc)
![Screenshot_2024-01-22-08-12-37-545_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/26156b8d-1e17-4e1c-a21f-267a7a362c1b)

**Comment by cagnulein** [comment]
è dentro a "gestore segnalazioni di debug"

**Comment by elisaceto** [comment]
Li dentro ho solo questo e non mi pare faccia nulla tieni conto che ho un Cell xiaomi
![Screenshot_2024-01-22-08-30-29-846_com android settings](https://github.com/cagnulein/qdomyos-zwift/assets/157239752/e625c899-bb23-4778-88dc-990b59f3b465)

**Comment by cagnulein** [comment]
che telefono è questo? provo a cercare direttamente per questo telefono, perchè in effetti non vedo la voce. lo si può fare via adb ma è richiesto un pc per farlo e non se sei in grado. Fammi sapere

**Comment by elisaceto** [comment]
È uno Xiaomi 11 lite 5g ne.
Stasera provo con un paio di tablet che ho. Se non trovo la voce provo con ADB che più o meno so come funziona. Ti aggiorno. Intanto grazie per la pazienza

**Comment by elisaceto** [comment]
Ecco, dovrei esserci riuscito col tablet. Il primo è acquisito collegando kinomap, il secondo collegando l'app iconsole+. Grazie
[bugreport-P3Pro_EEA-TP1A.220624.014-2024-01-22-19-05-20.zip](https://github.com/cagnulein/qdomyos-zwift/files/14014044/bugreport-P3Pro_EEA-TP1A.220624.014-2024-01-22-19-05-20.zip)
[bugreport-P3Pro_EEA-TP1A.220624.014-2024-01-22-19-13-51.zip](https://github.com/cagnulein/qdomyos-zwift/files/14014045/bugreport-P3Pro_EEA-TP1A.220624.014-2024-01-22-19-13-51.zip)

**Comment by cagnulein** [comment]
grazie domani guardo

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 19:26 elisaceto ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@elisaceto ho fatto la modifica! prima di pusharlo sul play store la possiamo provare da qui
fra 1 oretta circa troverai l'apk qui https://github.com/cagnulein/qdomyos-zwift/actions/runs/7626792816 (in fondo alla pagina quando la build avra' finito)

rimuovi prima qz dal tuo telefono (non preoccuparti, poi la potrai reinstallare gratuitamente) e poi installa questo.
abilita la nuova voce sotto iconsole chiamata come la tua bici e riavvia qz

fammi sapere se qualcosa non va e abilita il debug log cosi posso vedere se ho sbagliato qualcosa (purtroppo io non posso provare nulla senza la tua bici)

Fammi sapere!

**Comment by elisaceto** [comment]
Funziona! Non ho ancora avuto modo di provarlo con zwift ma il grosso del problema era la mancata rilevazione dei dati dei sensori. Sembra solo che i dati arrivino con un pizzico di ritardo, ma forse è solo una impressione.

**Comment by cagnulein** [comment]
grande! l'ho appena pushata sullo store in beta chiusa. mandami una mail a roberto.viola83 at gmail.con e indica questo ticket così ti aggiungo

la versione che hai appena installato e' una trial di 15 minuti che puoi riavviare quante volte vuoi

**Comment by elisaceto** [comment]
Ciao Roberto, stasera ho provato a utilizzare zwift con QZ: la bike si collega correttamente a QZ App e ora i parametri della bike vengono correttamente trasmessi e si vedono su QZ, ma zwift non rileva alcun dispositivo bluetooth da collegare. Cosa posso provare a fare?

**Comment by cagnulein** [comment]
dove hai qz? dove zwift? non vedi neanche un device bluetooth?
sto andando a letto, ci sentiamo domani

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 21:44 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
qz sul cellulare e zwift sul tablet. non vedo device bluetooth nella schermata iniziale di connessione di zwift (quella dopo aver cliccato sull'utente)

**Comment by cagnulein** [comment]
prova a mettere qz sullo stesso tablet e abilitare la android notificaton
icon setting in the experimental settings
fammi sapere

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 21:59 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Utilizzando lo stesso tablet funziona, ma devo ancora provare a fare un giro libero completo e un allenamento. Per la mia bike hai dei tuning o settaggi particolari dell'app da fare a parte i dati di peso, età ed FTP?

**Comment by cagnulein** [comment]
no semplicemente seIeziona la zwift resistance offset a come preferisci

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 17:39 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Siccome la mia fascia cardio si abbina prima al computer della bike, quindi a qz e poi a zwift, c'è maniera di togliere il dispositivo Bluetooth inutilizzato che mi compare su zwift?

**Comment by cagnulein** [comment]
no ma non ti da problemi

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 17:50 elisaceto ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@elisaceto novita'?

**Comment by elisaceto** [comment]
tutto ok: ho testato la bike durante una uscita libera di oltre 1 ora e il freno magnetico si aziona correttamente da solo. Come da tuo consiglio, ho anche settato la zwift resistance offset a 5 e mi trovo bene. ho notato queste cose:
1) c'è qualche discrepanza tra i dati indicati da zwift e quelli di QZ (es. l'ascesa e la velocità che forse ha udm differenti) 
2) quando uso zwift collegato diretto alla bike per una sessione di allenamento (in cui la resistenza automatica funziona), il display della bike rimane retroilluminato con la sola indicazione del livello di resistenza. Se invece uso zwift collegato alla bike tramite QZ per una sessione libera (in cui altrimenti la resistenza automatica non funzionerebbe) allora il display della bike si spegne completamente, non ha retroilluminazione e non mostra alcun dato.
3) utilizzando la schermata flottante di QZ visualizzata sopra zwift per monitorare i dati, non ho ben compreso perchè il livello di resistenza è mostrato nel formato x/x . Perchè 2 valori che molto spesso sono identici?

Provo anche a darti un suggerimento di sviluppo futuro, ammesso che non si possa già fare diversamente: durante l'uscita libera in zwift capita di sentire l'esigenza, soprattutto in discesa, di aumentare comunque la resistenza... non si potrebbe aggiungere alla schermata QZ flottante due pulsanti +/- per incrementare/decrementare l'offset di resistenza a piacere?

**Comment by cagnulein** [comment]
> 1. c'è qualche discrepanza tra i dati indicati da zwift e quelli di QZ (es. l'ascesa e la velocità che forse ha udm differenti)

per la velocita' leggi questo https://robertoviola.cloud/2024/01/27/dispelling-the-myth-speed-variations-between-qz-and-zwift-are-not-a-device-issue/



> 2\. quando uso zwift collegato diretto alla bike per una sessione di allenamento (in cui la resistenza automatica funziona), il display della bike rimane retroilluminato con la sola indicazione del livello di resistenza. Se invece uso zwift collegato alla bike tramite QZ per una sessione libera (in cui altrimenti la resistenza automatica non funzionerebbe) allora il display della bike si spegne completamente, non ha retroilluminazione e non mostra alcun dato.

non saprei, in caso puoi raccogliere un log da zwift con questo per capire cosa faccio di diverso https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device



> 3\. utilizzando la schermata flottante di QZ visualizzata sopra zwift per monitorare i dati, non ho ben compreso perchè il livello di resistenza è mostrato nel formato x/x . Perchè 2 valori che molto spesso sono identici?

il primo e' l'attuale il secondo e' il target. avendo tu la resistenza automatica, entrambi sono sempre uguali.

 

> Provo anche a darti un suggerimento di sviluppo futuro, ammesso che non si possa già fare diversamente: durante l'uscita libera in zwift capita di sentire l'esigenza, soprattutto in discesa, di aumentare comunque la resistenza... non si potrebbe aggiungere alla schermata QZ flottante due pulsanti +/- per incrementare/decrementare l'offset di resistenza a piacere?

lo puoi gia' fare se abiliti la tile gears!

fammi sapere!

**Comment by cagnulein** [comment]
> per il punto 2 ti avevo già inviato i log Bluetooth in uno dei primi post. comunque va anche bene così: spegnere il display della bike durante diverse ore di utilizzo potrebbe servire a preservarlo. Vorrà dire che guarderò il livello di resistenza dal pannello flottante

quello era da kinomap. anche li' il display rimaneva acceso?
comunque si, non lo vedo un gran problema :)

> Domanda: volessi utilizzare QZ anche per le sessioni di allenamento di zwift devo fare qualche configurazione particolare o basta lasciare tutto com'è?

dobbiamo creare una tabella di power zone a meno che la tua bici non gestisca la modalita' ERG. Che io sappia no, ma magari tu mi dici il contrario :) per esempio mi dicevi che da zwift, zwift ti comanda direttamente i watt sulla bici?

**Comment by cagnulein** [comment]
ok allora mi servirebbe un hci snoof in questa modalita' per capire cosa mandare alla tua bici
fammi sapere

**Comment by elisaceto** [comment]
ciao Roberto e grazie come al solito per la tua disponibilità.
Ho acquisito ciò che ti serve in questa maniera:
- abilitato Bluetooth HCI snoop log e riavviato il tablet
- aperto zwift e collegato i sensori direttamente alla bike
- iniziato una sessione di allenamento che mi ha fatto cambiare diversi livelli di potenza in automatico
- disabilitato Bluetooth HCI snoop log e generato lo zip che ti allego
[bugreport-P3Pro_EEA-TP1A.220624.014-2024-02-11-11-40-48.zip](https://github.com/cagnulein/qdomyos-zwift/files/14232065/bugreport-P3Pro_EEA-TP1A.220624.014-2024-02-11-11-40-48.zip)

ciao

**Comment by cagnulein** [comment]
Perfetto ci guardo appena possibile!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 feb 2024 alle 12:02 elisaceto ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fatto!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/7868495284

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
hah ho dimenticato di dirti di abilitare con questa nuova versione il settaggio Toorx Ftms Bike

**Comment by elisaceto** [comment]
Grazie. Posso anche attendere che si aggiorni da sola tramite playstore, vero?

**Comment by cagnulein** [comment]
si però poterebbero volerci giorni per vedere questa versione sullo store

**Comment by elisaceto** [comment]
Se è la versione 2.16.43 è arrivato l'aggiornamento sul play store.
Quindi in Toorx/iconsole option devo spuntare sia la mia bike Enerfit SPX 9500 che Toorx ftms bike?

**Comment by cagnulein** [comment]
Si

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 20:15 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Così QZ non mi legge mai i watt della bike e il ciclista su zwift, giustamente, non si muove. Cosa posso fare?

**Comment by cagnulein** [comment]
Fammi vedere un debug log, forse ho sbagliato qualcosa

**Comment by elisaceto** [comment]
Mi ricorderesti il link? Con qz aperto o no?

**Comment by cagnulein** [comment]
Solo qz aperto
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle 11:49 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Ecco i log... con Toorx ftms bike abilitato non riporta i valori dei watt mentre se e disabilitato di vedono (ma non funziona la regolazione automatica della bike in allenamento)

Non so se puo essere legato a questa cosa, ma ho avuto anche un malfunzionamento della frequenza cardiaca che a un certo punto si e fermata a 126 e non si e piu mossa da li. Tieni conto che io collego la fascia cardiaca al computer della bike e il computer della bike la ritrasmette inseme agli altri valori (potenza, cadenza, ecc...)
[debug-Sat_Feb_17_12_38_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14318820/debug-Sat_Feb_17_12_38_58_2024.log)

**Comment by cagnulein** [comment]
ok poi guardo. questo log e' con i watt che non funzionano giusto?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle 13:49 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Giusto. Con Toorx ftms bike abilitato

**Comment by cagnulein** [comment]
ok ora vado a correre , se stasera mia figlia mi lascia 2 minuti ci guardo

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle 14:49 elisaceto ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ho guardato il log ma forse ti sei sbagliato a caricarlo perchè io vedo i watt e cadenza

```
sab feb 17 12:39:54 2024 1708169994600 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current speed: 26.8"
sab feb 17 12:39:54 2024 1708169994600 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current cadence: 72"
sab feb 17 12:39:54 2024 1708169994601 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current heart: 107"
sab feb 17 12:39:54 2024 1708169994601 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current KCal: 3"
sab feb 17 12:39:54 2024 1708169994601 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current watt: 92"
sab feb 17 12:39:54 2024 1708169994601 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Elapsed from the bike (not used): 2940"
sab feb 17 12:39:54 2024 1708169994602 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Elapsed: 0"
sab feb 17 12:39:54 2024 1708169994602 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance Calculated: 0.409463"
```

**Comment by elisaceto** [comment]
Hai ragione, scusa, li ho ripresi con i 2 flag x la mia bike abilitati e i watt visualizzati a zero.
[debug-Sat_Feb_17_17_55_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14319596/debug-Sat_Feb_17_17_55_46_2024.log)

**Comment by cagnulein** [comment]
ho guardato il log, semplicemente devi premere lo start lampeggiante in rosso in alto per aver i watt. QZ li sta già leggendo correttamente. Fammi sapere!

**Comment by elisaceto** [comment]
Ah, ok, grazie. domani provo. E come mai per i giri liberi funziona senza dare lo start?

**Comment by cagnulein** [comment]
l'ho implementato così sotto richiesta degli utenti peloton che sono abituati a questo tipo di comportamento

**Comment by elisaceto** [comment]
Scusa se ti disturbo ancora, ma magari hai una spiegazione: con ftms bike abilitato, in modalità percorso libero di ZWift non mi applica le impostazioni come la ZWift resistance offset che invece ho se disabilito la ftms bike. Mi sfugge qualcosa?

**Comment by elisaceto** [comment]
Ciao, ho provato e c'è qualcosa che ancora non mi torna:
- ho abilitato ftms bike e riavviato qz
- ho fatto start in qz
- Ho aperto ZWift e collegato i sensori
- Ho iniziato una sessione di allenamento e la mia bike ha correttamente seguito automaticamente le potenze proposte. Durante l'allenamento non è stato possibile, credo correttamente, utilizzare gears per aumentare o diminuire la potenza.
- Ad allenamento terminato, senza toccare nulla in qz, ho cominciato un giro libero in ZWift. Durante il giro non era possibile modificare la potenza con gears.
Sbaglio qualcosa?

**Comment by cagnulein** [comment]
Quando passi dal workout al giro libero devi disattivare la zwift workout
erg setting in qz.

Esatto le gears non le puoi toccare durante il workout, in caso abbassa o
alza la difficoltà in zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 mar 2024 alle 22:43 elisaceto ***@***.***> ha
scritto:

**Comment by elisaceto** [comment]
Che vantaggio ho a disattivare zwift workout rispetto a ftms bike considerato che senza il giro libero funzionerebbe?

**Comment by cagnulein** [comment]
zwift workout abilitato informa QZ che deve usare la potenza richiesta invece che la pendenza. Disattivandolo funziona a viceversa.

**Comment by elisaceto** [comment]
Grazie, proverò. Esistono dei comandi da manubrio x controllare le gears compatibili con qz o che sai siano interfacciabili a zwift al di là di quelli marchiati zwift?

**Comment by cagnulein** [comment]
qualsiasi bluetooth remote con volume sono funzionanti già con QZ!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle ore 18:58 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Ho acquistato un controllo del volume bluetooth... Ora come devo fare? Devo fare qualche configurazione su QZ?

**Comment by cagnulein** [comment]
abilita volume on gears negli advanced settings

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 mar 2024 alle 18:54 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Ho collegato un controller volume bluetooth al tablet e abilitato l'opzione che mi hai indicato, ma non funziona e non cambia gears nemmeno con il tasto fisico del volume sul tablet. Cosa posso controllare?

**Comment by cagnulein** [comment]
ma tieni qz in foreground quando lo fai?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 mar 2024 alle 11:26 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Certamente, con la finestra flottante aperta in cui visualizzo le gears... Ed è lì che vedo che il volume non ha effetto, neppure i tasti fisici del tablet

**Comment by cagnulein** [comment]
ma che strano, mandami un debug log e ci guardo domani
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 mar 2024 alle 12:12 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Eccone un paio
[debug-Mon_Mar_25_23_28_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14796248/debug-Mon_Mar_25_23_28_20_2024.log)
[debug-Thu_Mar_28_23_37_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14796249/debug-Thu_Mar_28_23_37_30_2024.log)

**Comment by cagnulein** [comment]
nel secondo log vedo il volume e le gear cambiare correttamente ma non eri
connesso alla bici. me ne mandi uno dove sei connesso e cambi il volume?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 mar 2024 alle 23:43 elisaceto ***@***.***>
ha scritto:

**Comment by elisaceto** [comment]
Allego log con qz collegato alla bike. Sia nella finestra principale che in quella flottante le Gears rimangono sempre 0 pur aumentando e diminuendo il volume e anche la resistenza della bicicletta rimane ferma.
[debug-Sun_Mar_31_18_35_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14816957/debug-Sun_Mar_31_18_35_41_2024.log)
[debug-Sun_Mar_31_18_34_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14816958/debug-Sun_Mar_31_18_34_22_2024.log)

**Comment by cagnulein** [comment]
in effetti in entrambi i log non c'e' nessun evento del volume come invece c'era nel precedente. Domanda stupida: non e' che magari con il volume eri a fondo scala e quindi in realta' il volume non stava cambiando? su che versione di android sei?

**Comment by elisaceto** [comment]
si tratta di un android 13. il selettore volume non poteva essere al massimo anche perchè ho premuto diverse volte l'aumento e la diminuzione del volume

**Comment by cagnulein** [comment]
provo io oggi ma sono abbastanza sicuro che funzioni. si tratta di una qualche personalizzazone di android? che modello è?

**Comment by elisaceto** [comment]
No. È un android stock e il modello è un T30 della doogee

https://www.amazon.it/dp/B0C65PKKRV?starsLeft=1&ref_=cm_sw_r_apan_dp_2M18Z4DAZ714S8AAXHH9_1

Clemente Elis Aceto

Il mer 3 apr 2024, 05:09 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ho appena provato sul mio pixel 6a e funziona. Ora provo a farti una custimizzazione, credo che non sia esattamente stock il tuo android, probabilmente usa un driver audio diverso. Ti mando un apk di test quando sono pronto

Se hai un altro android, anche vecchio, prova in parallelo anche lì

Grazie

**Comment by elisaceto** [comment]
Ho provato dal telefonino e funziona. Prima di farti fare un cinema aspetta che stasera provo a resettare l'app sul tablet e rifare da zero le configurazioni di base.

**Comment by cagnulein** [comment]
Ok no problem  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 apr 2024 alle 08:15 elisaceto ***@***.***> ha
scritto:

**Comment by elisaceto** [comment]
Resettata l'app e configurata da zero. Funziona!
Ora devo vedere se mettendo altre configurazioni che avevo smette di funzionare. Ti aggiorno

**Comment by cagnulein** [comment]
grande! fammi sapere!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 apr 2024 alle 19:54 elisaceto ***@***.***> ha
scritto:
