### ISSUE TITLE
[BUG] Android Row doesn't send Distance to Garmin

### ISSUE THREAD

**Issue by HartD92** [cagnulein/qdomyos-zwift#2024]
**Describe the bug**
When connected to echelon rower, qz displays distance, but does not broadcast it to Garmin. Garmin is connected with power and cadance sensor, and gets all other stats

**To Reproduce**
1. Connect to rower
2. Connect to garmin
3. Start activities
4. Observe all stats change, but distance never increments.

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: 14
 - Version 2.16.30

**Comment by cagnulein** [comment]
by ant+? which garmin do you have?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle 18:26 David ***@***.***> ha
scritto:

**Comment by HartD92** [comment]
Ant+, descent mk2i (basically a Fenix 6x)

**Comment by cagnulein** [comment]
are you able to set the wheel diameter on the watch? you have to set to 100mm to see the speed and the distance

**Comment by HartD92** [comment]
The wheel diameter is set to 100mm, and it works fine for bike activities.

**Comment by cagnulein** [comment]
if you start a bike activity, do you speed from qz right? it sounds like a
garmin limitation of the rower activity so. what do you think?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle 18:35 David ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@HartD92 any news?
