### ISSUE TITLE
[BUG] Elliptical trainer "FAL-SPORTS0195" (Brand and model: Maxxus CX 5.1) won't connect correctly

### ISSUE THREAD

**Issue by MarcGyr** [cagnulein/qdomyos-zwift#2025]
**Describe the bug**
Elliptical trainer "FAL-SPORTS0195" (Brand and model: Maxxus CX 5.1) does connect to qdomyos-zwift app (or at least is being found as a BT device) but won't display any non-zero values.

**To Reproduce**
1. start the app on iPhone 15 Pro (iOS 17.2.1), go into settings, bike and set the trainer to ftms bike and restart qz.

**Expected behavior**
qdomyos-zwift app will display non-zero values.
With this working I'd hope to connect qdomyos-zwift app to Zwift on a different device (iPad) in Zwift Run mode and use the elliptical trainer to perform Zwift Run training.

**Screenshots**
Screenshot #1: QZ.PNG - qdomyos-zwift app screenshot with connection to "FAL-SPORTS0195" elliptical trainer. All values zero despite stepping on the elliptical.
![QZ](https://github.com/cagnulein/qdomyos-zwift/assets/157306515/477879b7-8f58-43fb-9930-27987601fdc0)

Screenshot #2: Zwift Run pairing.jpg
![Zwift Run pairing](https://github.com/cagnulein/qdomyos-zwift/assets/157306515/6b14144c-7030-46e7-854a-c4a86e9fc9c9)

**Smartphone:**
 - Device: iPhone15 Pro
 - OS: iOS17.2.1

**Append a debug log**
See: debug-So__Jan__21_17_22_30_2024.log  
[debug-So__Jan__21_17_22_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14002198/debug-So__Jan__21_17_22_30_2024.log)
  
**Additional context**
The trainer normally uses the iConsole+ app, with which is connects perfectly fine and displays all expected values, so I guess the trainer itself is OK. The iConsole+ app is fully closed when doing the qz tests.
The trainer can *directly* connect as a bike to Zwift Ride on an iPad with everything working as expected, including cadence. However, using an elliptical trainer but being on a bike avatar in Zwift does not fit and yields strange results (low wattage, cadence and all that).
The trainer can *directly* connect to Zwift Run on an iPad for "Run Speed" and "Heart Rate" but the runner avatar won't move with this alone. It's not possible to connect "Cadence" with Zwift Run - see Screenshot #2: Zwift Run pairing.jpg. I tested this on a second, older iPad as well (all devices running iOS 17.2.1), same result.

**Comment by cagnulein** [comment]
@MarcGyr disable the elliptical from the cadence and power sensor both and press ok on both and restart qz and if it doesn't work send me another debug log

let me know

**Comment by cagnulein** [comment]
leave it only in ftms bike

**Comment by cagnulein** [comment]
also share a nrfconnect about it showing all the characteristics. i guess i know which is the issue

**Comment by MarcGyr** [comment]
Thanks alot for the immediate reply!
So in QZ settings - Bike Options I kept the FAL-SPORTS0195 as FTMS Bike.
In QZ settings - Accessories - Cadence Sensor Options I disabled it.
In QZ settings - Accessories - Power Sensor Options I disabled it as well. Restarted QZ but that did not change anything.
Here's the log:
[debug-So__Jan__21_19_51_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14002561/debug-So__Jan__21_19_51_25_2024.log)

Installed nRF Connect by Nordic Semi on the iPhone, connected to the trainer, and here's the log (connected twice):
[nRF log.txt](https://github.com/cagnulein/qdomyos-zwift/files/14002564/nRF.log.txt)

I hope this is what was asked for :)
I am new to all this and have no real clue but the nRF log in Discovered Characteristics does not mention cadence or st. similar...
If there's no way to get cadence from the trainer to QC or Zwift then I could attach a Wahoo RPM cadence sensor to the trainer's flywheel. Well, I actually tried this but did not succeed yet in connecting the Wahoo RPM directly (or indirectly via the iPhone running QZ with data from the Wahoo RPM showing OK) to Zwift Run on an iPad as a cadence sensor (that's what the screenshot #2 Zwift Run pairing.jpg shows). It somehow seems Zwift Run does not want to connect to any cadence sensor at all in my setup (checked on 2 iPads).

**Comment by cagnulein** [comment]
ok thanks, we will got for sure. Just another tests:
disable also the virtual bluetooth setting in the experimental settings and send me another debug log. If so I will send you a patch.
No need to buy a cadence sensor for sure!
Let me know

**Comment by cagnulein** [comment]
yes the cadence gain should fix that issue, let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 19:59 MarcGyr ***@***.***> ha
scritto:

**Comment by MarcGyr** [comment]
A different value from 1 for Cadence Gain in Advanced Settings does not stick. I can enter 0.5 or 2 and hit OK but in Zwift I constantly get double cadence. Going back into QZ advanced settings I then see 1 again as Cadence Gain value. So it seems to reset itself to 1?

**Comment by cagnulein** [comment]
stupid question: did you press ok after changing it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 20:35 MarcGyr ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
you are right i'm seeing the same thing. i will check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 20:37 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
cadence gain already fixed from phone now !

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 20:39 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOs and tomorrow i will send you a new beta. Thanks

**Comment by MarcGyr** [comment]
Ok, mail was sent.
Meanwhile I also realized that my run speed in both, QZ and Zwift was doubled as well. This I could fix as expected with setting 0.5 for Speed Gain, which worked as it should (did not reset itself).
So it really just seems to be the Cadence Gain setting that does not stick.

**Comment by cagnulein** [comment]
Ok, thanks for the update!


Il giorno lun 22 gen 2024 alle 20:52 MarcGyr ***@***.***> ha
scritto:

**Comment by MarcGyr** [comment]
Thanks for sending the new version!
This is version 2.16 (716), right? I am asking for confirmation because in Testflight App Details it says this was released on January 18, while I thought the build or release date should be January 23 or maybe 22.

I was not able to do much testing today but it seems the 0.5 for cadence gain now sticks in qz settings. However, it does not have any effect in Zwift Run, where the step cadence still is twice the rpm I see in qz.
Well, now I am wondering whether I have a wrong understanding of what step cadence actually should be. If for this *both* feet need to be counted then it absolutely makes sense to have a step cadence in Zwift Run that is twice the rpm of the elliptical’s flywheel, which is the rpm value I see in qz. So maybe it‘s all good already?
I will do some more tests in the next few days…

**Comment by cagnulein** [comment]
you can turn off this so

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/5e660e0e-bc4e-47ce-9c4f-ab5365415719)

**Comment by MarcGyr** [comment]
Did some more testing and I think it‘s OK now with Zwift Run incl. the step/run cadence that shows up in Zwift. Thanks a lot again!
I am happy now but, well,  if there‘s a way to get the auto-incline feature work with this Maxxus elliptical then I‘d be intersted, of course. 
I can not change inclination with the +\- buttons in the qz app inclination tile but I am sure that Zwift can provide inclination data to the Maxxus trainer and that trainer also can apply it because when I connect the trainer to Zwift for riding a bike (which I did before learning about qz app, which made running possible) the Zwift bicycle track inclination was well applied by the trainer.

**Comment by cagnulein** [comment]
@MarcGyr Ok so first of all we need to be able to change the resistance from qz. 

Provide a debug log while you are changing it from qz even if it's not working.

Also do you have an app thst can change it?

**Comment by MarcGyr** [comment]
I can go up to level 16 with the iConsole+ app, which is the app that shall be used with the trainer according to the manual. There's no other recommended app for it as far as I can tell.

Here's the log. I first tried to increase inclination a few times, then decrease it a few times, then also tried the speed tile's +/- buttons but all to no effect.

[debug-So__Feb__4_19_49_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14157968/debug-So__Feb__4_19_49_46_2024.log)

**Comment by cagnulein** [comment]
perfect, do you have an android device for 10 minutes? you have only to use
iconsole following this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 20:06 MarcGyr ***@***.***>
ha scritto:

**Comment by MarcGyr** [comment]
Here's the Bluetooth HCI snoop log, taken from FS\data\misc\bluetooth\logs  (FS/Data/Log/bt was not there) on a Nexus 5x I borrowed at work (my own Android devices all were too outdated to install iConsole+).
In iConsole+ I increased inclination (or "level" in that app) a few times, maybe up to 5, then decreased to 1 again, and then once more up and down again. Speed adjustment can not be done with that app and elliptical crosstrainer, I believe.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14213688/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 feb 2024 alle ore 20:21 MarcGyr ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i would like to send you a version with a test, let's see if it works, otherwise i will completely do this using the iconsole protocol. I will send you it by email later today

**Comment by KeerdanA** [comment]
Hey Roberto,

maybe I can assist in solving this issue which also affects me. I have the Maxxus CX 7.8 elliptical (connected as FAL-SPORTS0364) running with your beta 2.16.44 for Android but cadence is reported with doubled value in zwift. The QZ App shows the correct cadence. 

The app settings under Advanced settings -> cadence gain has no effect at all regardless of value entered. Also playing around with the settings under Accessories -> Power sensor options -> Doubling cadence for run and Half cadence on Strava do not affect the reported cadence for Zwift.

Please let me know if I can assist you.

**Comment by cagnulein** [comment]
hi @KeerdanA are you using zwift in bike mode or run mode? are you able to share a debug log from qz showing the issue? thanks

**Comment by KeerdanA** [comment]
@cagnulein did not work. what I did so far:

- uninstalled app from store
- installed android app from build-link (2.16.45)
- under bike options I chose the trainer as ftms bike
- under accessories -> power sensor option I enabled "doubling cadence for run"
- closed the app
- started the trainer
- opened the app -connect successful
- started zwift run
- still double cadence

then I

- changed advanced settings - "cadence gain" to 0.5. klicked ok. closed and restarted qz app. reconnected the virtual kickr in zwift
- still double cadence

then I

- enabled debugging in the app. restarted the app and took another debug log. cadence 30-60 and back

[debug-Wed_Feb_21_12_21_02_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14358859/debug-Wed_Feb_21_12_21_02_2024.zip)

If it helps: I generated a bluetooth log with the elliptical only talking to zwift BIKE on my phone (no QZ app) as the elliptical works without issues in bike mode. but it looks like someone at Zwift doesn't like bluetooth looging enabled. there is only a small timeframe at around 12:49 where I got the trainer connected to Zwift AND logging enabled AND zwift showing cadence (correctly). All the other times zwift simply does not show anything.

[btsnoop.zip](https://github.com/cagnulein/qdomyos-zwift/files/14359212/btsnoop.zip)

**Comment by cagnulein** [comment]
actually i see that the patch worked. but maybe the issue is on the zwift pairing screen @KeerdanA 
Can you send me a screenshot how you select QZ in the pairing screen? I'm actually interested in the cadence sensor you select there

**Comment by KeerdanA** [comment]
![Screenshot_20240221_150047](https://github.com/cagnulein/qdomyos-zwift/assets/160718750/e244b378-35f0-4b8f-92b3-53d59b1fd04b)

**Comment by cagnulein** [comment]
so that's fine. just to be sure, with this version, is the value shown on qz is right? so you are seeing the double only on zwift? if you disable this setting in this new version, do you see a different on zwift? it should
Let me know!

**Comment by KeerdanA** [comment]
unfortunately no difference when changing the option "Doubling Cadence for Run"

Option enabled:
![Screenshot_20240221_152915](https://github.com/cagnulein/qdomyos-zwift/assets/160718750/eb79e00b-fca9-4d57-a50a-903b72eafc55)
![Screenshot_20240221_152924](https://github.com/cagnulein/qdomyos-zwift/assets/160718750/94da8a3a-04ee-4c96-a15b-389917720f55)

Option disabled:
![Screenshot_20240221_153656](https://github.com/cagnulein/qdomyos-zwift/assets/160718750/49baeae7-707b-43db-8efb-cbfbcaea5fd1)
![Screenshot_20240221_153659](https://github.com/cagnulein/qdomyos-zwift/assets/160718750/cdc51092-371b-4a14-a2e4-c7dc6cd20178)

**Comment by cagnulein** [comment]
ok could you try this now https://github.com/cagnulein/qdomyos-zwift/actions/runs/7990888073 ?

**Comment by KeerdanA** [comment]
yay - cadence in Zwift now matches cadence of QZ/elliptical. Thank you very much.

**Comment by cagnulein** [comment]
ok so I have to use also that setting there. I will create a new version to merge it. It will be good to test it then too.

**Comment by cagnulein** [comment]
done @KeerdanA could you please also test this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7991697055
so if it will work I will merge to the master
Thanks!

**Comment by cagnulein** [comment]
sorry this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/7991855150

**Comment by cagnulein** [comment]
sorry wait, i don't like the implementation that I did. in order to the right thing, it will be better to add a new setting for this

**Comment by KeerdanA** [comment]
uhm <blush>, to be honest I never thought about whether the Zwift cadence value could be correct. I come from a cycling background and cadence is always revolutions per minute. If it's true that Zwift Run cadence is a value for steps per minute then the doubled value makes perfect sense and I was mislead by the term "cadence sensor". In that case I will go back to the beta version you've linked me yesterday. Please excuse the hassle I've caused 

If you need an android user as guinea pig in the future just let me know

**Comment by cagnulein** [comment]
No worries, thanks!


Il giorno mer 21 feb 2024 alle 21:56 KeerdanA ***@***.***> ha
scritto:

**Comment by MarcGyr** [comment]
Just to confirm on the latest conversation here: I am on QZ app v2.16.42 (likely a beta via Testflight) on iOS with the Maxxus CX 5.1 and for me run cadence actually looks good at this point, also after doing a few more runs in Zwift and visually comparing my step cadence to other runners in game at similar speed. Initially I also thought the fact that Zwift shows twice the step cadence as QZ app is an issue but it seems OK.
Just wondering @KeerdanA: on your Maxxus CX 7.8, do inclination changes in Zwift Run, i.e. if you are running uphill, show any effect on your trainer's resistance setting? I assume your trainer firmware is similar to mine on CX 5.1 and so I guess this does not work for you, too.

**Comment by KeerdanA** [comment]
Hey @MarcGyr: no, the trainer does not change the resistance - but I'm not sure it's supposed to. 

Zwift itself says they do not controll treadmills in any way - FAQ https://support.zwift.com/en_us/running-faq-BJuPPqzwH 

On the other hand I just found this posting https://forums.zwift.com/t/auto-incline-on-treadmills-fully-working/555791 of a guy that reported @cagnulein did enable auto incline support for treadmills in QZ which I imagine could somehow work as a resistance control for ellipticals

**Comment by cagnulein** [comment]
yes guys i can add auto inclination for your elliptical! i need to add the iconsole protocol first!

i will let you know when i will be ready to test it!

**Comment by cagnulein** [comment]
ok guys I started the very first raw version to handle resistance on zwift for your elliptical. You need to disable the ftms bike setting in this new version.

https://github.com/cagnulein/qdomyos-zwift/actions/runs/8051729133

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by KeerdanA** [comment]
Hey @cagnulein, for me it looks like the build was unsuccessful. There is nothing to download?

**Comment by cagnulein** [comment]
ok let me know @KeerdanA

**Comment by KeerdanA** [comment]
[debug-Wed_Feb_28_07_45_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14429924/debug-Wed_Feb_28_07_45_16_2024.log)
This Version seems to register with the Trainer, but differently. Instead of a blue trainer screen where I still can choose the resistance and see the heartrate it goes completely dark. Unfortunately when I start moving QZ does not show it. QZ Debug file is attached

Thanks Roberto

**Comment by cagnulein** [comment]
Ok, I'll check it out.


Il giorno mer 28 feb 2024 alle 07:54 KeerdanA ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
thanks @KeerdanA 
there was a desync init frame
could you please check this https://github.com/cagnulein/qdomyos-zwift/actions/runs/8078140415 ?
thanks

**Comment by KeerdanA** [comment]
[debug-Wed_Feb_28_11_56_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14432876/debug-Wed_Feb_28_11_56_59_2024.log)

Unfortunately still nothing on the QZ app

**Comment by cagnulein** [comment]
Ok, thanks for the update.
I will try another approach


Il giorno mer 28 feb 2024 alle 12:01 KeerdanA ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
thanks @KeerdanA let's try another approach https://github.com/cagnulein/qdomyos-zwift/actions/runs/8081278656

**Comment by KeerdanA** [comment]
Thank you, still no data from the trainer 

[debug-Wed_Feb_28_15_18_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14435291/debug-Wed_Feb_28_15_18_02_2024.log)

**Comment by cagnulein** [comment]
got the issue, that's another one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 feb 2024 alle ore 15:21 KeerdanA ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/8082003626

**Comment by MarcGyr** [comment]
Thanks a lot for providing the Testflight version!
I did and saw the follwoing:
- disabled "FTMS Bike" in Bike Options
- connecting to Zwift Run still works as before
- I can now change Resistance with the +/- buttons. This is not very responsive and sometimes I had to hit the buttons 2 or 3 times to get the efect but possibly this is due to a lag in the trainer when it changes resistance mechanically
- resistance is at 2 in the beginning and I can't get below that value. I did not try to change any of the Resistance settings in the Bike Options such as Resistance Offset, Gain or Startup value
- Inclination can't be changed in qz app but maybe this does not make sense with an elliptical trainer and it's sufficient to be able to change resistance
- then in Zwift Run I chose a track that has inclination of up to +4 and down to -4 but that did not have any effect in QZ app or with the trainer. I did not try a workout in Zwift Run which possibly should effect in a resistance change when Watts go up during the workout. I can try that tomorrow.

**Comment by cagnulein** [comment]
That's a start @MarcGyr !

Do you have a debug log from qz?

**Comment by MarcGyr** [comment]
Here's a debug log.
I increased resistance a few times, from 2 up to 5 I think, and then back again to 2. To increase or decrease the + or - button needs to be hit 1 to 3 times to take effect (just a side note).
I then started up Zwift and connected to "Wahoo KICKR 0000 33", as I did before with qz app in Zwift pairing. 
The selection screen now also shows "Wahoo TREAD 0003". Should I try this as well?
I then started a Zwift Run workout but only went a few meters (warmup would have been several minutes before the workout would have really started with higher wattage).

[debug-Sa__März_2_08_24_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14468428/debug-Sa__Marz_2_08_24_00_2024.log)

**Comment by cagnulein** [comment]
> Here's a debug log. I increased resistance a few times, from 2 up to 5 I think, and then back again to 2. To increase or decrease the + or - button needs to be hit 1 to 3 times to take effect (just a side note).

thanks I will check this ASAP!

> I then started up Zwift and connected to "Wahoo KICKR 0000 33", as I did before with qz app in Zwift pairing. The selection screen now also shows "Wahoo TREAD 0003". Should I try this as well? 

that's the same for this purpose.

**Comment by cagnulein** [comment]
ok i guess i already fixed the issue about the resistance must be pressed twice

**Comment by cagnulein** [comment]
fixed also the resistance blocked to min 2

**Comment by cagnulein** [comment]
@MarcGyr can you provide me a log where you do a little free run on zwift so i can check the auto inclination thing on QZ. Remember to set the zwift username and password on qz for auto inclination on zwift

**Comment by MarcGyr** [comment]
Here's the debug log. 
I did enter Zwift credentials just now in qz Settings (and was happy that I could not find the password in the debug log in plain text :) )
I think when I was running in Zwift inclination (top right on the Zwift screen) in the beginning was -2%, then it changed up to 3% at some point when running over a bridge, then to -3% and so on.
[debug-Sa__März_2_16_45_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14469949/debug-Sa__Marz_2_16_45_43_2024.log)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!
yes no password are going through qz to outside. i don't have any analytics
as well :)

Il giorno sab 2 mar 2024 alle 17:02 MarcGyr ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the issue, i will send you the fix asap!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle ore 17:04 cagnulein ***@***.***> ha
scritto:

**Comment by MarcGyr** [comment]
OK, the latest version changed a few things indeed.
In qz app I can't modify resistance any more, and also inclination won't change with +/- buttons (but this did not work before). I did not try this when doing the attached debug log, though.
Initial resitance is at 1 now (was at 2 before).
However, in Zwift Run there's a very clear resistance change now. The track I chose starts with 2% inclination right away and the trainer after a few seconds (polling once every few seconds I guess) increases resistance significantly. I guess I will have to try resistance gain or some setting in qz to tweak this. When running further resistance goes down again with 0% Zwift track inclination and then goes up to quite strong resistance with a 3% track inclination in Zwift. I did also notice that the trainer changes resistance even if the Zwift inclination percentage does not change. That makes sense to me because obviously without adjusting this further with some gain the resistance change for a 1% change in Zwift inclination is too much (maybe 2 or even 3 trainer resistance steps).
All along there's no change in qz app for the resistance or inclination values shown. They stay unchanged from the beginning.
Also the speed and cadence vlaues do not seem to be as accurately updated in qz display as before.
I also think that after about a minute or so the connection between trainer and qz changes somehow. It does not disconnect, I believe, but the trainer's display, which was inactive all the time since after one of the recent updates, now activates itself again after a minute or so.
Attached is a debug log. What I did not do when recording this was to try changing resitance or inclination with the qz +/- buttons.
Thanks!

[debug-So__März_3_11_56_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14472670/debug-So__Marz_3_11_56_11_2024.log)

**Comment by cagnulein** [comment]
> OK, the latest version changed a few things indeed.
> 
> In qz app I can't modify resistance any more, and also inclination won't change with +/- buttons (but this did not work before). I did not try this when doing the attached debug log, though.

OK in case send me a new debug log for this. Thanks 

> 
> Initial resitance is at 1 now (was at 2 before).

Perfect 

> 
> However, in Zwift Run there's a very clear resistance change now. The track I chose starts with 2% inclination right away and the trainer after a few seconds (polling once every few seconds I guess) increases resistance significantly. I guess I will have to try resistance gain or some setting in qz to tweak this. 

Yes the zwift resistance offset is the setting you are looking for in the bike section 

> When running further resistance goes down again with 0% Zwift track inclination and then goes up to quite strong resistance with a 3% track inclination in Zwift. I did also notice that the trainer changes resistance even if the Zwift inclination percentage does not change. That makes sense to me because obviously without adjusting this further with some gain the resistance change for a 1% change in Zwift inclination is too much (maybe 2 or even 3 trainer resistance steps).


Consider that's zwift shows the average instead Z qz uses the actual value so that's the difference.

> 
> All along there's no change in qz app for the resistance or inclination values shown. They stay unchanged from the beginning.
> 
> Also the speed and cadence vlaues do not seem to be as accurately updated in qz display as before.

I didn't change anything about this. 

> 
> I also think that after about a minute or so the connection between trainer and qz changes somehow. It does not disconnect, I believe, but the trainer's display, which was inactive all the time since after one of the recent updates, now activates itself again after a minute or so.
> 
> Attached is a debug log. What I did not do when recording this was to try changing resitance or inclination with the qz +/- buttons.
> 
> Thanks!
> 
> 
> 
> [debug-So__März_3_11_56_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14472670/debug-So__Marz_3_11_56_11_2024.log)
> 
> 

Ok I will check the log ASAP!

**Comment by MarcGyr** [comment]
Here's another debug log. I did not connect to Zwift in this.
Resistance is 1 at startup but I can't change it anymore (changing this worked before). Also Inclination can't be changed but this did not work before.
I really think that after some time (less than a minute I guess) qz does not update speed and cadence values anymore.

[debug-So__März_3_18_39_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14474005/debug-So__Marz_3_18_39_45_2024.log)

After that debug log run I was curious and did another very brief run in Zwift. Also there connection somehow dropped and despite increasing my cadence on the trainer siginificantly the cadence value in both, qz app and in Zwift did not increase but stayed the same. I then stopped stepping completely but the avatar in Zwift just kept running (I could have collected some XP with this but then just quit, of course).

One question: there's a setting in the Advanced Settings section that is called "Zwift Inclination Gain". Is this something to try with maybe a value of 0.5 if I want to have less of a resistance change on the trainer for each percent of inclination change in Zwift?

Thanks again, as always, for the great support.

**Comment by cagnulein** [comment]
> One question: there's a setting in the Advanced Settings section that is called "Zwift Inclination Gain". Is this something to try with maybe a value of 0.5 if I want to have less of a resistance change on the trainer for each percent of inclination change in Zwift?

yes exactly.

for the other points i will check in the next days. I'm currently overwhelmed by requests

**Comment by cagnulein** [comment]
> Resistance is 1 at startup but I can't change it anymore (changing this worked before). Also Inclination can't be changed but this did not work before.

fixed. checking the other points

**Comment by cagnulein** [comment]
> After that debug log run I was curious and did another very brief run in Zwift. Also there connection somehow dropped and despite increasing my cadence on the trainer siginificantly the cadence value in both, qz app and in Zwift did not increase but stayed the same. I then stopped stepping completely but the avatar in Zwift just kept running (I could have collected some XP with this but then just quit, of course).

fixed too! i will send you another one tomorrow!

**Comment by cagnulein** [comment]
Sent a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle ore 19:05 MarcGyr ***@***.***>
ha scritto:

**Comment by MarcGyr** [comment]
Did a test run and this looks all good! Connection stable for 30 minutes with speed, cadence and other values updating as expected in qz and and in Zwift. Changing resistance works well now (with just one click on +/- buttons). Changing inclination does not work but I guess it‘s not supposed to if resistance can be changed.
I still need to play around with offset and gain values for resistance and/or inclination in qz app settings to get it all right for me. Will continue to look into that soon but in general changing those values does produce the intended effect.
Thanks again!

**Comment by cagnulein** [comment]
Awesome, thanks for the update!
For the inclination I would need a hci snoof from androis where inclination
would change from the app directly

Il giorno mar 5 mar 2024 alle 21:31 MarcGyr ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@MarcGyr are we good with this?

**Comment by MarcGyr** [comment]
Yes, looks good to me right now. Thanks for the great support.
