### ISSUE TITLE
[BUG] Floating window does not show Peleton row targets

### ISSUE THREAD

**Issue by k818mn1** [cagnulein/qdomyos-zwift#2026]
**Describe the bug**
Connected to echelon rower and following a peleton row class. Peleton Target stroke rate (cadence) tile is enabled and displays correctly, but is not displayed on the floating window. Same is true for the peleton target pace.

**To Reproduce**
Does it all the time

**Expected behavior**
Display peleton target stroke rate next to actual stroke rate in the floating window. Display peleton target pace next to actual pace in the floating window.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Echelon tablet
 - OS: Android
 - Version QZ 2.16.0

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Add any

**Comment by cagnulein** [comment]
don't you see the target cadence in the cadence row after the '/'?

**Comment by k818mn1** [comment]
No, only the actual cadence. Same for Pace, only the actual pace is displayed not the target.Target stroke rate from peleton and target pace are displayed in the relevant tiles, but not in the floating window.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/21/24  1:33 PM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
don't you see the target cadence in the cadence row after the '/'?

**Comment by cagnulein** [comment]
got the issue, I will do in the next versions.
note for me: templateinfosenderbuilder is the culprit

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 21:16 k818mn1 ***@***.***>
ha scritto:

**Comment by k818mn1** [comment]
That's great, thanks. My tablet is currently on version 2.16.0 which I downloaded from Amazon appstore. It's not the latest version, when will it get updated?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/21/24  2:18 PM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
got the issue, I will do in the next versions.

note for me: templateinfosenderbuilder is the culprit



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 21 gen 2024 alle ore 21:16 k818mn1 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
i will add you to the amazon beta tester then
send me an email to roberto.viola83 at gmail.com with your amazon email
account as a reminder. thanks
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 gen 2024 alle ore 21:33 k818mn1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@k818mn1 can you post a debug log with the issue. For the target pace you are right for sure, but the target cadence should be already in the floating window. Let me know!

**Comment by k818mn1** [comment]
[debug-Mon_Jan_22_11_09_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14013394/debug-Mon_Jan_22_11_09_50_2024.log)
I updated the QZ app to the test version on Amazon appstore. Debug log uploaded. Target cadence is displayed on the tile but not in floating window. Pace and Target pace are displayed on the tiles but pace in floating window shows 'N/A' and target pace not displayed.

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno lun 22 gen 2024 alle 18:27 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i just fixed the target cadence issue, but I can't find the issue on the pace. I also tried with the fake rower setting and the pace is populating well forcing a pace.

So let's try with the 2.16.38 version that I will upload it shortly and see if it makes any difference.
Thanks

**Comment by cagnulein** [comment]
just submitted to the amazon app store the new beta
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle ore 18:50 cagnulein ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
[debug-Wed_Jan_24_09_41_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14040826/debug-Wed_Jan_24_09_41_53_2024.log)
Target Cadence and Target Pace tiles are displayed but do not track the peleton class callouts reliably. Floating window Cadence and Target Cadence display same values as the tiles. Floating window Pace shows N/A with no Target pace. Gears tile value increments continously by 1 every second. Floating window Gears displays 0. Preset tiles function but set resistance to wrong value.

**Comment by k818mn1** [comment]
[debug-Wed_Jan_24_09_47_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14040988/debug-Wed_Jan_24_09_47_10_2024.log)
Another row class

**Comment by cagnulein** [comment]
> [debug-Wed_Jan_24_09_47_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14040988/debug-Wed_Jan_24_09_47_10_2024.log) Another row class

in this log you have preset resistance 1 to 10 and preset 2 to 15

and here is working as they have

```
Wed Jan 24 09:56:18 2024 1706111778149 Debug: ../src/homeform.cpp void homeform::LargeButton(const QString &) "LargeButton" "preset_resistance_2"
Wed Jan 24 09:56:18 2024 1706111778224 Debug: ../src/echelonrower.cpp void echelonrower::update() "writing resistance 10"
Wed Jan 24 09:56:21 2024 1706111781619 Debug: ../src/homeform.cpp void homeform::LargeButton(const QString &) "LargeButton" "preset_resistance_2"
Wed Jan 24 09:56:23 2024 1706111783826 Debug: ../src/homeform.cpp void homeform::LargeButton(const QString &) "LargeButton" "preset_resistance_1"
Wed Jan 24 09:56:23 2024 1706111783839 Debug: ../src/echelonrower.cpp void echelonrower::update() "writing resistance 5"
Wed Jan 24 09:56:46 2024 1706111806913 Debug: ../src/homeform.cpp void homeform::LargeButton(const QString &) "LargeButton" "preset_resistance_2"
Wed Jan 24 09:56:47 2024 1706111807023 Debug: ../src/echelonrower.cpp void echelonrower::update() "writing resistance 10"
```

what are you seeing instead?

also i don't see anywhere the increments to 1 continuosly in the first and in the 2nd log neither.

could you please create a log with this issue?

**Comment by cagnulein** [comment]
i also checked the last log and the 18 rpm for the cadence is right with the peloton program.

```
  "target_metrics_performance_data":{
      "target_metrics":[
         {
            "metrics":[
               {
                  "lower":18,
                  "name":"stroke_rate",
                  "upper":22
               },
               {
                  "lower":0,
                  "name":"pace_intensity",
                  "upper":0
               }
            ],
            "offsets":{
               "end":107,
               "start":60
            },
            "segment_type":"caesar"
```

**Comment by k818mn1** [comment]
[debug-Wed_Jan_24_10_27_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14041222/debug-Wed_Jan_24_10_27_47_2024.log)
Preset issue. Buttons are preset to 10 and 15 but when pressed they set resistance to 5 and 10 respectively.

**Comment by k818mn1** [comment]
https://github.com/cagnulein/qdomyos-zwift/assets/39540440/29fc9375-cc9a-4c42-9bf8-8cf6335fc8ff

Video of Gears tile incrementing.

**Comment by cagnulein** [comment]
> [debug-Wed_Jan_24_10_27_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14041222/debug-Wed_Jan_24_10_27_47_2024.log) Preset issue. Buttons are preset to 10 and 15 but when pressed they set resistance to 5 and 10 respectively.

that's because you have a gears value of -5

**Comment by cagnulein** [comment]
ok let me check if i can see this gear ghost too here

**Comment by k818mn1** [comment]
Target Cadence tile matches the peleton class initially but when the peleton class cadence changes the QZ tile does not change. Same for Target pace, it does not change when the peleton class instructor changes the intensity.

**Comment by cagnulein** [comment]
gears issue fixed!



> Target Cadence tile matches the peleton class initially but when the peleton class cadence changes the QZ tile does not change. Same for Target pace, it does not change when the peleton class instructor changes the intensity.

did you collect this in one of the above log?

**Comment by k818mn1** [comment]
Yes, it will be in the 9:47 am log.

**Comment by k818mn1** [comment]
Digging into the Gears tile, when QZ is paused the  + and - buttons on the Gears tile function correctly, changing the resistance by the Gears gain amount. But the number displayed on the Gears tile is always zero. When I press Start, the Gears number starts to increment by 1 per second continuously until I press Pause.

**Comment by cagnulein** [comment]
> Yes, it will be in the 9:47 am log.

perfect, i will check it tomorrow. thanks

don't worry about the gear issue it was just a stupid copy and paste that leads to the random thing that you are seeing

**Comment by k818mn1** [comment]
I just did a different row class and the target cadence followed the class cadence very well. I had the Peleton app in full screen with the QZ floating window on top and Auto Sync enabled (this is how I usually use QZ). When I switched to split screen mode with Peleton on the left and QZ on the right then it lost sync and stopped following cadence changes. How does QZ sync, does it read the time on the screen?

**Comment by k818mn1** [comment]
Yes, it is definitely the autosync that was causing the issue with syncing. I tried with manual sync and it tracked ok. I also tried with QZ running on my android phone and it tracked the changes well. So that's not an issue.

**Comment by k818mn1** [comment]
The only issue remaining is that Pace and Target Pace are not being displayed in the floating window, although they are displayed correctly in the tiles.

**Comment by cagnulein** [comment]
@k818mn1 i was checking the pace issue and in your last logs i can't find the issue, but maybe i guess i found a possible issue.

In the log i found that the speed is only evaluated in this little time frame

```
Wed Jan 24 09:54:05 2024 1706111645877 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.46218"
Wed Jan 24 09:54:05 2024 1706111645894 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.05882"
Wed Jan 24 09:54:06 2024 1706111646810 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.36134"
Wed Jan 24 09:54:06 2024 1706111646816 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.05882"
Wed Jan 24 09:54:07 2024 1706111647874 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.2605"
Wed Jan 24 09:54:07 2024 1706111647878 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.05882"
Wed Jan 24 09:54:08 2024 1706111648868 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.15966"
Wed Jan 24 09:54:08 2024 1706111648879 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.05882"
Wed Jan 24 09:54:09 2024 1706111649860 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.05331"
Wed Jan 24 09:54:09 2024 1706111649887 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
Wed Jan 24 09:54:10 2024 1706111650858 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.04779"
Wed Jan 24 09:54:10 2024 1706111650862 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
Wed Jan 24 09:54:11 2024 1706111651918 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.04228"
Wed Jan 24 09:54:11 2024 1706111651932 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
Wed Jan 24 09:54:12 2024 1706111652870 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.03676"
Wed Jan 24 09:54:12 2024 1706111652884 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
Wed Jan 24 09:54:13 2024 1706111653936 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.03125"
Wed Jan 24 09:54:13 2024 1706111653943 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
Wed Jan 24 09:54:14 2024 1706111654907 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed: 7.03125"
Wed Jan 24 09:54:14 2024 1706111654913 Debug: ../src/echelonrower.cpp void echelonrower::characteristicChanged(const QLowEnergyCharacteristic &, const QByteArray &) "Current Speed Raw: 7.03125"
```

are you able to see the pace correctly in the main qz app?

**Comment by k818mn1** [comment]
Yes. Pace and Target pace are both displayed correctly on the tiles. If I deselect the target pace tile and leave the pace tile selected then pace is displayed correctly in the tile and in the floating window. But if both pace and Target pace are selected then the floating window just displays pace as N/A, instead of 4:45/4:31 for example.

**Comment by cagnulein** [comment]
> Yes. Pace and Target pace are both displayed correctly on the tiles. If I deselect the target pace tile and leave the pace tile selected then pace is displayed correctly in the tile and in the floating window. But if both pace and Target pace are selected then the floating window just displays pace as N/A, instead of 4:45/4:31 for example.

oh this is important



> Maybe a formatting error in the floating window text string?

yes it could be, let me check

**Comment by cagnulein** [comment]
i can't find the reason the code in the html floating window is very easy

```
if(pace_s.toString() === "-1" || (pace_s.toString() === "0" && pace_m.toString() === "0"))
   $('.pace-value').html("<b>N/A</b>");
else {
   if(tile_target_pace_enabled && target_pace > 0)
       $('.pace-value').html("<b>" + pace_m.toString().padStart(2, "0") + ":" + pace_s.toString().padStart(2, "0") + "/" + target_pace_m.toString().padStart(2, "0") + ":" + target_pace_s.toString().padStart(2, "0") + "</b>");
   else
       $('.pace-value').html("<b>" + pace_m.toString().padStart(2, "0") + ":" + pace_s.toString().padStart(2, "0") + "</b>");
}
```

the only case with N/A is when the pace is 0 or null. but you're saying that you are seeing this with only the tile_target_pace_enabled == true.

i tried to simulate it on my own but it works fine here :O

**Comment by k818mn1** [comment]
I don't see why that condition to display N/A is even necessary. When I'm not rowing the pace tile displays 0:00, so why does the window display pace N/A? Why not just display 0:00 same as the pace tile. Anyway, I can't get the target pace to display in the floating window whatever I try, even though it is displayed just fine in the target pace tile and tracks the peleton class.So I decided to enable the target speed tile and use that instead of target pace. And I found the same issue applies. The target speed tile displays correctly in the tile and follows the peleton class, but target speed is NOT displayed in the floating window. I'm assuming it should be displayed?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/25/24  9:40 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
i can't find the reason the code in the html floating window is very easy
if(pace_s.toString() === "-1" || (pace_s.toString() === "0" && pace_m.toString() === "0"))
   $('.pace-value').html("<b>N/A</b>");
else {
   if(tile_target_pace_enabled && target_pace > 0)
       $('.pace-value').html("<b>" + pace_m.toString().padStart(2, "0") + ":" + pace_s.toString().padStart(2, "0") + "/" + target_pace_m.toString().padStart(2, "0") + ":" + target_pace_s.toString().padStart(2, "0") + "</b>");
   else
       $('.pace-value').html("<b>" + pace_m.toString().padStart(2, "0") + ":" + pace_s.toString().padStart(2, "0") + "</b>");
}

the only case with N/A is when the pace is 0 or null. but you're saying that you are seeing this with only the tile_target_pace_enabled == true.
i tried to simulate it on my own but it works fine here :O

**Comment by cagnulein** [comment]
> I don't see why that condition to display N/A is even necessary. When I'm not rowing the pace tile displays 0:00, so why does the window display pace N/A? Why not just display 0:00 same as the pace tile.

you have to ask to @laurenweinstein1  https://github.com/cagnulein/qdomyos-zwift/issues/1247
i'm just following your advices :)

> Anyway, I can't get the target pace to display in the floating window whatever I try, even though it is displayed just fine in the target pace tile and tracks the peleton class.So I decided to enable the target speed tile and use that instead of target pace. And I found the same issue applies. The target speed tile displays correctly in the tile and follows the peleton class, but target speed is NOT displayed in the floating window. I'm assuming it should be displayed?

the target speed should on the same line of the speed in the floating window separed by "/"

the lines are

```
          if (tile_target_speed_enabled && target_speed > 0)
            $('.speed-value').html("<b>" + speed.toFixed(1) + "/" + target_speed.toFixed(1) + "</b>");
          else
            $('.speed-value').html("<b>" + speed.toFixed(1) + "</b>");
```

@k818mn1 are you able to open a browser on your pc or mac and debug the javascript? the floating window is openable to any browser on your network and with the dev tools on chrome, safari, edge, you can add a breakpoint.

are you able to do so?

so you can help me a lot!
thanks!

**Comment by k818mn1** [comment]
Sure I can look at the javascript. It seems to me that target_pace and target_speed are not getting to the floating window.What change did you make to templateinfosenderbuilder.cpp in order to make target_cadence be displayed?

**Comment by k818mn1** [comment]
In templateinfosenderbuilder.cpp do we need to add target_pace and target_speed for tp == bluetoothdevice::ROWING?
I can only see target_cadence in the list of signals for Rowing.

**Comment by cagnulein** [comment]
> In templateinfosenderbuilder.cpp do we need to add target_pace and target_speed for tp == bluetoothdevice::ROWING? I can only see target_cadence in the list of signals for Rowing.

target pace is already here

https://github.com/cagnulein/qdomyos-zwift/blob/84c351e55c0b4eb5940301b4d597fd4e8e3fe478/src/templateinfosenderbuilder.cpp#L1093

i'm adding target speed, but for the pace it's not the issue

**Comment by cagnulein** [comment]
> Sure I can look at the javascript. It seems to me that target_pace and target_speed are not getting to the floating window.What change did you make to templateinfosenderbuilder.cpp in order to make target_cadence be displayed?

this https://github.com/cagnulein/qdomyos-zwift/commit/52b0d0c5a15cba780e83591c08396e176d9dda8c

**Comment by cagnulein** [comment]
you're right! i'm fixing it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle ore 16:36 k818mn1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
but it should just display the regular pace not N/A
anyway i'm committing it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle ore 16:39 cagnulein ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
Let me know when the new version is available on Amazon appstore, please.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/26/24  9:41 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
but it should just display the regular pace not N/A

anyway i'm committing it



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 26 gen 2024 alle ore 16:39 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
ok fixed but now there is a layout issue :) 
<img width="471" alt="Screenshot 2024-01-27 at 08 28 27" src="https://github.com/cagnulein/qdomyos-zwift/assets/48216/c743fbf9-1818-4c1b-baf7-0502b3a90db3">

**Comment by cagnulein** [comment]
<img width="498" alt="Screenshot 2024-01-27 at 08 35 38" src="https://github.com/cagnulein/qdomyos-zwift/assets/48216/21df5d8d-7191-4f2e-aec3-7410d9290cea">
are you ok with this when you have the target pace?

**Comment by k818mn1** [comment]
I would prefer one line without leading zeroes, eg 2:15:/2:45 if the window could be made a little wider.If that's too difficult then 2 lines is OK.Does it change color like the cadence?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/27/24  1:36 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
Screenshot.2024-01-27.at.08.35.38.png (view on web)
are you ok with this when you have the target pace?

**Comment by cagnulein** [comment]
yes i already removed the leading 0. i can't make it wider, people already
complaints about the fact that it's too wide :D

nope i don't set the color. i will do and i will push to amazon  app store
 beta in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 16:13 k818mn1 ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
I think you will have the same problem when displaying speed/target speed. For example 11.3/12.2 is 9 characters.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/27/24  10:13 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
yes i already removed the leading 0. i can't make it wider, people already

complaints about the fact that it's too wide :D



nope i don't set the color. i will do and i will push to amazon  app store

 beta in the next days



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 27 gen 2024 alle 16:13 k818mn1 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
yes that's why 2 lines are better
or another idea is to removing avg and max when there is a target pace

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 02:29 k818mn1 ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
I think that is a better idea. They aren't relevant and I  can't even read average or max because the font is too small for my eyes. 
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/28/24  12:51 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
yes that's why 2 lines are better

or another idea is to removing avg and max when there is a target pace



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 28 gen 2024 alle 02:29 k818mn1 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
ok i will try to do this tomorrow
there was already an idea to remove the avg and max for all the lines.
anyway let's do this first

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 14:06 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done! color and pace row fixed! i'm sending it to the amazon beta
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle ore 14:16 cagnulein ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
It's great! Pace and Target pace display correctly and change color as they should. I don't miss displaying the averages. The problem with always displaying N/A is fixed, I think it was a precedence issue due to target_pace being undefined.Cadence and target cadence already worked in the previous version.Speed and target speed still need some work. However, I don't think target speed is really necessary if target pace is displayed. I assume QZ calculates target speed from target pace, so they are really the same information? What metrics actually come from peleton, just cadence and intensity?

**Comment by cagnulein** [comment]
Great! Strange the speed is calculated from the pace. Which values do you see on the speed?
Peloton sends intensity and also speed and cadence if i remember correctly

**Comment by k818mn1** [comment]
Speed and speed target display the correct values, but don't change color. And they are too many digits to fit.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/30/24  9:50 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
Great! Strange the speed is calculated from the pace. Which values do you see on the speed?
Peloton sends intensity and also speed and cadence if i remember correctly

**Comment by cagnulein** [comment]
Ok so I will adopt the same patch of the pace
I will try to do in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 18:27 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I added a question here https://github.com/cagnulein/qdomyos-zwift/issues/1481 since I worked a lot on this topic in the last months. I don't want to break something (even if it's only the coloring).

**Comment by cagnulein** [comment]
In the meantime I'm removing avg speed and max speed when the target speed
is set

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle ore 18:29 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@k818mn1 so can we close this?

**Comment by k818mn1** [comment]
Yes, it works great for me thanks
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/15/24  9:32 PM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [BUG] Floating window does not show Peleton row targets (Issue #2026) 
@k818mn1 so can we close this?
