### ISSUE TITLE
[REQ] Manual control of Echelon Row resistance

### ISSUE THREAD

**Issue by k818mn1** [cagnulein/qdomyos-zwift#2028]
**Is your feature request related to a problem? Please describe.**
The Echelon rower has two buttons on the handle to increment or decrement the resistance. But it only changes once per button push, so it takes 5 button pushes to increment by 5. 

**Describe the solution you'd like**
Use the Gear tile to change the resistance by a user defined amount

**Describe alternatives you've considered

**Additional context**
For information, in the Echelon app there are buttons on the screen to select the resistance to high, medium or low, or to increment/decrement resistance by 5, but of course these buttons are not available for a peleton row class, so then it's limited to he two buttons on the handle

**Comment by cagnulein** [comment]
hi @k818mn1 you can do this on the beta already using the gear gain setting in the advanced setting. Are you already on the beta?

**Comment by cagnulein** [comment]
hah ok i will enabled also for rower
thanks for the feedback

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 18:50 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
note for me: i need to add gears completely to the rower, handle this on the homeform.cpp plus and minus events and enabling the tile

**Comment by k818mn1** [comment]
Yes, I can already use the Resistance tile to change the resistance. 
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/23/24  3:34 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Manual control of Echelon Row resistance (Issue #2028) 
@k818mn1 last information: are you already able to change the resistance from the qz app directly? this is a requirment to make gears working (after my patch that i'm doing). Let me know

**Comment by cagnulein** [comment]
perfect I will add it so! I will let you know when i will be ready!

**Comment by k818mn1** [comment]
I also tried using the Preset tiles to change the resistance on the rower but they did not work. Is that the same issue as the Gears tile? If so, will the Preset tiles also get fixed after your changes?
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/23/24  8:35 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Manual control of Echelon Row resistance (Issue #2028) 
perfect I will add it so! I will let you know when i will be ready!

**Comment by cagnulein** [comment]
ok done, it will be in the 2.16.39 and above!

**Comment by k818mn1** [comment]
Wow, that was fast! I'll test it out after I update to 2.16.39
-------- Original message --------From: Roberto Viola ***@***.***> Date: 1/23/24  9:01 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Manual control of Echelon Row resistance (Issue #2028) 
ok done, it will be in the 2.16.39 and above!

**Comment by k818mn1** [comment]
Tested with 2 16.40 and it works great. The resistance tile inc/dec changes the rower resistance, and the Gears tile changes resistance too by the Gears gain setting. Preset buttons also work great. The only issue I found is that the Gears value displayed in the floating window is always zero, although the + and - buttons do change the value it is not displayed.
![20240208_152740](https://github.com/cagnulein/qdomyos-zwift/assets/39540440/23b74baa-d54f-4303-b044-b8abda661739)

**Comment by cagnulein** [comment]
fixed! thanks!

**Comment by cagnulein** [comment]
i don't remember were you on play store or on amazon app store?

**Comment by k818mn1** [comment]
Amazon
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/9/24  1:07 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Manual control of Echelon Row resistance (Issue #2028) 
i don't remember were you on play store or on amazon app store?

**Comment by cagnulein** [comment]
ok I will push it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle 15:37 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
pushed!
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle ore 17:27 cagnulein ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
It's working great! Thank you for all your work!
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/12/24  2:44 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Manual control of Echelon Row resistance (Issue #2028) 
pushed!

let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 9 feb 2024 alle ore 17:27 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Amazing!
