### ISSUE TITLE
Sole F63 speed control 

### ISSUE THREAD

**Issue by Boux16** [cagnulein/qdomyos-zwift#2029]
**Describe the bug*
When pressing + just once in app to increase speed, the speed increases to max

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/
[debug-Sun_Jan_21_16_21_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14004471/debug-Sun_Jan_21_16_21_25_2024.log)
[debug-Sun_Jan_21_16_21_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14004474/debug-Sun_Jan_21_16_21_25_2024.log)
How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Boux16 enable the sole inclination experimental setting in the sole settings and also enable the f63 setting and restart qz
let me know!

**Comment by cagnulein** [comment]
@Boux16 any news?
