### ISSUE TITLE
[BUG] Echelon ex7s connects to qz, no apps connect to qz using bluetooth (zwift, rouvy, mywhoosh)

### ISSUE THREAD

**Issue by gitMeSumCode2600** [cagnulein/qdomyos-zwift#2031]
**Describe the bug**

- I have an echelon ex-7s, and use qz to connect to zwift, rouvy and mywhoosh
- the screen attached to the bike is disconnected, i dont use it
- zwift only works in wahoo direct connect
- nothing works connecting using bluetooth
- qz runs on my fire 8 tablet and samsung note 8 (android 9)
- zwift, rouvy, mywhoosh run on lenovo w541, i7 cpu, nvidia gpu, builtin bluetooth v4, also tried external asus bt-500 bluetooth v5 dongle
- I've tried rouvy on my phone ,while using qz on fire tablet, same behaviour

**the behaviour is** 
- zwift sees the phone or tablet name "bike" but when i select it and  connects, it says no signal
- zwift if i stay on the screen where it shows the list of devices to connect, i can see my device cycle from full bar , low bar, no signal, full bar...over and over (same behaviour whether i use my fire tablet or phone)
- in rouvy when i select "bike", it says connecting and never connects
- in mywhoosh, i select "bike" it says paring in progress, paired, then pairing in progress again.
- ive done all the standard things, read the github, facebook group...etc rebooted everything for each test I've done...etc
- many people do not have an echelon ex7s, perhaps there is something slightly different about it than the ex5 or ex3
- 
**To Reproduce**
1. turn on echelon ex7s, flashing blue 
2. turn on bluetooth on fire tablet or phone
3. launch qz, echelon bike connects without issue
4. test pedaling to ensure data is being sent to qz (it is)
5. turn on laptop
6. turn on bluetooth
7. wait 10 seconds (dont know why i just do it)
8. launch zwift
9. select power source
10. choose "bike" (name of tablet or phone, doesnt make difference)
11. power source is now selected and power source says no signal

**Expected behavior**
my expectation is for someone to determine what the issue is and rectify it.. this issue is most likely the reason i cannot use the other apps as well

**Screenshots**
this screenshot attached is what happens in zwift with bluetooth
![bt_2024-01-21-155241_002](https://github.com/cagnulein/qdomyos-zwift/assets/18559403/eea01b99-003f-48b5-b789-71ace1600e0e)

**Laptop (please complete the following information):**
 - windows 10 pro 22h2
 -  lenovo w541
 - CPU Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz   2.79 GHz
 - GPU Nivida K1100
 - 16gb ram
 - bluetooth v4 (realtek or ac 7260)
 - bluetooth v5 asus bt500 (when testing this i disable builtin bluetooth in bios)

**Smartphone (please complete the following information):**
 - samsung note 8 (android 9)
 - fire 8 tablet (2022 edition)
 

**Append a debug log**
[debug-Sun_Jan_21_16_51_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14005953/debug-Sun_Jan_21_16_51_35_2024.log)

**Comment by cagnulein** [comment]
mmm i found something in your log. is the "Heart Rate service outside FTMS" disabled? could you please turn it on and restart qz? share me another debug log if it still doesn't work
Let me know!

**Comment by cagnulein** [comment]
there is a reason if it's under experimental settings :)

glad it worked!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 gen 2024 alle 20:10 gitMeSumCode2600 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i don't see the picture. you have to send on the github interface directly

**Comment by cagnulein** [comment]
hah yes sorry is the right one. for me it was under the special settings. anyway glad that's the one!

**Comment by cagnulein** [comment]
glad to hear it!
