### ISSUE TITLE
[BUG] Nordictrack C2150: QZ app speed jumping wildly (top speed 24.5mph!) and distance not showing accurately in Peloton app

### ISSUE THREAD

**Issue by suzycc** [cagnulein/qdomyos-zwift#2033]
Hi Roberto,

I just did a run with the Peloton app and most of the time everything seemed to work smoothly but at times the speed was jumping wildly. I know I asked you previously about the speed changing and you explained that was the belt speed, but this was different. The speed in the app was bouncing to a much greater degree than before. For example, from 0.3 to 12 to 24mph. While that was happening, the treadmill speed was at 6mph and I wasn't touching anything. The treadmill speed felt consistent to me (it certainly did not drop to 0.3mph or speed up to 24mph). Also, the final distance that showed in the Peloton app was completely different to the QZ app odometer.

I have attached screenshots which show the variation in speed that was has happening, as well as the difference in the final distance between the QZ app and the Peloton app.

I'm running the QZ beta on my iPhone SE 2020 using iOS 17.2.1.

Thanks,

Suzy
![IMG_2731](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/21d70fe3-55c1-4a20-b04f-78ee9ae81446)
![IMG_2734](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/17fd5291-fe9d-4792-9a4e-dd1f508fea26)
![IMG_2733](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/81f64b85-6b56-425e-9b7d-4cabb0557510)
![IMG_2732](https://github.com/cagnulein/qdomyos-zwift/assets/15828157/462985eb-96e7-4e06-8cd2-971b330c1445)
[debug-Mon_Jan_22_12_47_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14015521/debug-Mon_Jan_22_12_47_31_2024.log)

**Comment by cagnulein** [comment]
hi @suzycc I would love to check the issue but this debug log is just an empty one, maybe you have another bigger one from the same date? Let me know

**Comment by cagnulein** [comment]
unfortunately is the treadmill itself that sends these random values

```
Mon Jan 22 12:28:34 2024 1705955314293 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"7.8\", \"Current KPH\":\"12.5\" } }"
Mon Jan 22 12:28:34 2024 1705955314295 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 12.5"
Mon Jan 22 12:28:34 2024 1705955314296 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetoothdevice.cpp void bluetoothdevice::update_hr_from_external() Current Heart from Apple Watch:  "153"
Mon Jan 22 12:28:34 2024 1705955314297 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"23.5\", \"Current KPH\":\"37.8\" } }"
Mon Jan 22 12:28:34 2024 1705955314298 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 37.8"
Mon Jan 22 12:28:34 2024 1705955314300 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetoothdevice.cpp void bluetoothdevice::update_hr_from_external() Current Heart from Apple Watch:  "153"
Mon Jan 22 12:28:34 2024 1705955314301 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"23.5\", \"Current KPH\":\"37.8\", \"Miles\":\"1.283\", \"Kilometers\":\"2.064\", \"Total Time\":\"545:46:18\", \"Total Miles\":\"2702.774\" } }"
Mon Jan 22 12:28:34 2024 1705955314303 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 37.8"
Mon Jan 22 12:28:34 2024 1705955314304 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 2.064"
Mon Jan 22 12:28:34 2024 1705955314305 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetoothdevice.cpp void bluetoothdevice::update_hr_from_external() Current Heart from Apple Watch:  "153"
Mon Jan 22 12:28:34 2024 1705955314334 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << { \"values\":{ \"Current MPH\":\"9.5\", \"Current KPH\":\"15.2\" } }"
```

in the same second the treadmill went from 9.5 to 23.5

did you try to reboot it? maybe it was a bug in their firmware?

**Comment by suzycc** [comment]
Hi Roberto,

I tried sending it by email but got an error message due to file size, so
I’ve uploaded it again on GitHub. Hopefully this time it’s not empty….!

Suzy

**Comment by suzycc** [comment]
Thanks so much for looking into it.

I won’t be able to run for the next couple of days but I’ll see what
happens next time. Hopefully a reboot will sort it out.

Suzy

**Comment by cagnulein** [comment]
@suzycc Any news?

**Comment by suzycc** [comment]
It has done it a few more times (weirdly, it mostly seemed to be halfway
through the class) but it’s been less of an issue in the last few runs. A
couple of times it’s happened so quickly that I don’t notice—I only see it
in my stats at the end when it says my top speed was 24mph :   )

I was also having minor problems with the connection between my phone (qz)
and my iPad (Peloton) dropping out 2-3 times per 30-min run but it worked
fine today.

Overall, I love your app! Thank you! The auto-incline is fantastic.

When are you going to release the beta to have iOS App Store? My daughter
wants to start using it too…

Suzy

**Comment by cagnulein** [comment]
@suzycc I found a way to fix the issue! Since the max MPH from your treadmill is 12, I can filter out values more than this one, do you agree?



> I was also having minor problems with the connection between my phone (qz) and my iPad (Peloton) dropping out 2-3 times per 30-min run but it worked fine today.

be sure to stay close with the devices and also avoid any other bluetooth devices around you. If it happens again I can check your log



> Overall, I love your app! Thank you! The auto-incline is fantastic.

Great! I don't know if you already left a review on the store, if not, please do it, it means a lot to me!





> When are you going to release the beta to have iOS App Store? My daughter wants to start using it too…

I plan to release the upgrade on the app store in the spring because I don't want to break anything during winter for the regular users, but if your daughter has already the app I can send the version to him as well!

Let me know!

**Comment by cagnulein** [comment]
@suzycc Any news?

**Comment by suzycc** [comment]
Hi Roberto,

Today, I noticed that the qz app connected automatically to the Peloton app at the start and for the first time in a while, the  connection did not drop out during my run. (It was only a 20min run vs my usual 30 min runs.)  It's hard to stay away from other bluetooth devices because the treadmill is in my husband's office and we also have a Peloton bike right near the treadmill, which he is often riding at the same as I am running. Interestingly, today he was not riding while I was running. I have my phone (running QZ app) and a tablet (running Peloton app) on the device ledge on the treadmill, so they are all very close together.

Also, I haven't been taking careful notes, but it feels like the speed readings have been fairly stable lately although today I did notice it bouncing around a little today (bouncing down rather than up).

I've attached a debug log from my run today.

Suzy

[debug-Sat_Mar_9_12_36_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14548272/debug-Sat_Mar_9_12_36_12_2024.log)

**Comment by cagnulein** [comment]
Ok, I'll take a look.
Thanks

Il giorno dom 10 mar 2024 alle 01:32 Suzy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Also, I haven't been taking careful notes, but it feels like the speed readings have been fairly stable lately although today I did notice it bouncing around a little today (bouncing down rather than up).

yes the patch worked for the high speed but also the treadmill is reporting lower speed sometimes. The only other thing that I can do is adding a averaging. Let me know what you think!

**Comment by suzycc** [comment]
Hi Roberto,

It's not a big deal—it's usually pretty short bursts of bouncing. It's much
more annoying when the Bluetooth connection drops out and I have to
reconnect it via the iPad as I'm running and the distance in the Peloton
app resets, but I don't think that has anything to do with your app....!

Suzy
