### ISSUE TITLE
[BUG] - QZ Connection with Proform TDF 10.0

### ISSUE THREAD

**Issue by Alienabilite** [cagnulein/qdomyos-zwift#2034]
**Describe the bug**
Hello, I just followed all the steps in order to connect my Pro Form TDF 10.0 to QZ App. Everything is working well but when I start the QZ App, the App is still "connecting". I tried to reinstall and to do it again but I still have the same issue. It seems that it is a Bluetooth issue. 

**To Reproduce**

**Expected behavior**
Connection between QZ App and my Pro Form TDF 10.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version : 22H2

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.1.2
 - Version : iOS 17.1.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

How can I send you the Debug File ? (It is in extension .fit and this extension is not supported by GitHub ?). I'm sorry, I have a really poor level in IT ...
Thank you very much for your help !
  
**Additional context**

**Comment by cagnulein** [comment]
for a debug log you have to follow this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
is there something unclear?

**Comment by Alienabilite** [comment]
[debug-mar__janv__23_10_06_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14021278/debug-mar__janv__23_10_06_59_2024.log)

Please find the debug file attached (I don't know, I didn't managed to find it before, sorry).

**Comment by cagnulein** [comment]
what about this one https://github.com/cagnulein/qdomyos-zwift/issues/1759 ? wasn't working already?
in this log that you posted the companion is not talking at all. did you install the companion on the bike?
also you set the ip on the treadmill setting instead of the tdf companion ip setting under the bike section. please remove the ip and press ok from the treadmill one, and put in the tdf companion ip instead.

anyway the issue is that the companion is not talking.
let me know

**Comment by Alienabilite** [comment]
About #1759, no it was not working, I tried 10 times every steps and I finally gave up ...

The bike was off earlier when I sent you the debug log. I just turned it on and now you will find the updated debug log attached. 
I also just modified the IP settings, indeed I used treadmill instead of bike ...

[debug-mar__janv__23_10_27_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14021506/debug-mar__janv__23_10_27_00_2024.log)

Is it better this way ?

**Comment by cagnulein** [comment]
no qz is still not receiving anything from the companion.

are you able to ping the bike 192.168.1.26 from the phone? using any ping
app from the store.
show me a screenshot

also are you sure about this IP?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 23 gen 2024 alle ore 10:29 Alienabilite <
***@***.***> ha scritto:

**Comment by Alienabilite** [comment]
![IMG_5566](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/36f9ea32-4553-4da6-b975-8e3e79a3ecd1)

For the IP adress, please find attached a screenshot of the 192.168.1.26 information, I may be wrong but it seems that it is the correct address. 

Please find the Ping test below : 

![Capture d’écran   2024-01-23 à 10 48 40](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/83234641-87f3-4f2a-8c8f-acad3bf2902e)

**Comment by cagnulein** [comment]
ok so could you please click on the dump log button on the qz companion app and share me a screen?

**Comment by Alienabilite** [comment]
![IMG_5569](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/b8b2931d-a99e-4c2a-814d-e24fa340b15b)
Please find the dump log attached !

**Comment by cagnulein** [comment]
@Alienabilite which wifi router do you have? it seems that it's dropping the qz companin packages.

**Comment by Alienabilite** [comment]
I'm in France, it's a LiveBox (from Orange). I'm not sure that's sufficient information for you ?

**Comment by Alienabilite** [comment]
Do you think I'm too far from the wifi box ? IFIT is working well on the bike

**Comment by cagnulein** [comment]
if you are not tech savvy to change the settings there, i suggest to try to use your phone as a repeater for your bike
no you are not too far, it's the router that it's dropping the packages from the qz companion app (i'm quite sure). using the phone as a repeater you will avoid this

**Comment by Alienabilite** [comment]
Hi Roberto, I hope you are well !
So I tried to remove wifi from the bike and then share the internet connection with my IPhone. The bike received correctly internet from the phone but I still had the same issue in the App (it was still in "connecting" and when I used the bike, the data were not visible on the App)

**Comment by cagnulein** [comment]
can you share a debug log in this context? i would like to see if the issue is the same. thanks

**Comment by Alienabilite** [comment]
Ok, I'm not home right now, but I will send it to you when I come back. 
Thank you very much for your help, I know I'm not helpful at all with my poor skills ...

**Comment by cagnulein** [comment]
ahah no problem, i'm here to help!

**Comment by Alienabilite** [comment]
![IMG_5575](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/45cb6e01-fa64-4d5b-82e9-74a018d125ba)

Hi Roberto, please find attached the dump log, thank you !

**Comment by cagnulein** [comment]
no i mean a debug log from QZ

**Comment by Alienabilite** [comment]
[debug-jeu__janv__25_12_31_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14051037/debug-jeu__janv__25_12_31_12_2024.log)

Sorry, please find it now attached

**Comment by cagnulein** [comment]
perfect! now i can see the messages from the bike! so the problem was for sure your router!

good!

now let's focus on the metrics: try to set the c1750 device on the bike and reboot it

let me know if you can see the metrics then

remember to keep this setup (so wifi from the phone directly to the bike)

let me know

**Comment by Alienabilite** [comment]
Ok, so I just changed in the QZ App on the bike from ProfForm 10.0 to C1750 Treadmill and rebooted the bike. Apparently there is no change, I still cannot see the metrics on the QZ App on my phone (it is still "connecting")

**Comment by cagnulein** [comment]
ok so follow this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 14:13 Alienabilite ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Alienabilite Any news?

**Comment by Alienabilite** [comment]
Hi Roberto, 
To be honest with you, I stopped when I saw that I needed to perform a factory reset of the Bike Tablet. I'm not confident with the impact that this could have on the bike and unsure to be willing to take the risk.

**Comment by Alienabilite** [comment]
Ok ok, I will try tonight.
In order to reset, is there an option in the bike tablet settings ?

**Comment by cagnulein** [comment]
yes you can check the video
Nordictrack Treadmills Wifi only finally compatible with Zwift using QZ
https://youtu.be/_KRMSHxo5AQ


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 17:19 Alienabilite ***@***.***>
ha scritto:

**Comment by Alienabilite** [comment]
Hi Roberto, 
I just followed all the instructions but it is still not working (I still cannot see the data on the QZ App). The only thing is, when you say "DON'T update IFIT App", I tried to cancel the updates but sometimes I didn't have any button to cancel it, it was automatic so i'm not sure if the updates occured. 

Another idea, would it be usefull if I try to reinstall the QZ App on my phone or reset it ? 

Thank you very much again for your help !

**Comment by Alienabilite** [comment]
I'm not really familiar with the concept of DHCP and Static IP but what I know is that the IP adress of the bike is always the same even after the reboots. Does it mean that it is a static IP ?
What I can do is to not connect the bike to the wifi but in this case I won't be able to reinstall QZ companion on it.

**Comment by cagnulein** [comment]
You have to connect to the wifi after the reset but in the access point
selection You have a way to DON'T use the dhcp so using a manual ip. Send.e
a screenshot of that view and I will help you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 20:01 Alienabilite ***@***.***>
ha scritto:

**Comment by Alienabilite** [comment]
I have this first view and then the second one when I click on my wifi : 

![IMG_5586](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/5d2cba62-a962-4106-ba0d-3f3e6625cd11)
![IMG_5587](https://github.com/cagnulein/qdomyos-zwift/assets/129524743/81ac62f7-6519-4b5d-b047-60e883e54474)

**Comment by cagnulein** [comment]
@Alienabilite mmm they oversimplify this. 

check this https://github.com/cagnulein/qdomyos-zwift/issues/2023#issuecomment-1902714501
that's the solution.

you can ask to the OP if you have any questions

**Comment by Alienabilite** [comment]
I'm sorry but I don't understand how this https://github.com/cagnulein/qdomyos-zwift/issues/2023#issuecomment-1902714501 is supposed to help me understand how to deal with not updating IFIT

**Comment by cagnulein** [comment]
@Alienabilite because using that tool will block ifit to update itself
