### ISSUE TITLE
[BUG]Horizon 7.4 with Peloton miles issue

### ISSUE THREAD

**Issue by hamster786** [cagnulein/qdomyos-zwift#2037]
Turn tread on. Start qz.  Star Peloton workout, add treadmill
2 options show up for pixel 7. My phone. 
Miles are way off on Peloton. App. 

**To Reproduce**

**Expected behavior**
Miles to be accurate

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: [e.g. iOS8.1]Android 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
[Uploading inbound6502048861706117975.txt…]()

  
  
**Additional context**

**Comment by cagnulein** [comment]
the debug log is truncated, you have to wait the upload before press the comment button

also are you sure it's just a miles to km conversion?

**Comment by hamster786** [comment]
Ok let me resend it.
I'm pretty sure it's not miles vs km.  It's way too off even with
conversion . I'll attach a screenshot as well.

**Comment by cagnulein** [comment]
ok write me here when you will do. i'm going to bed soon

**Comment by hamster786** [comment]
Oket me know if this works.
Qz shows the right miles, it is just the Peloton app which is weird

**Comment by hamster786** [comment]
![inbound6804270467229451951](https://github.com/cagnulein/qdomyos-zwift/assets/17281784/1389c15d-e351-4c1e-86f9-d6e053feb800)

**Comment by cagnulein** [comment]
is this the first time that you are using peloton for treadmill using qz to send distance? seems a cache issue of the peloton app

was wrong from the very startup of the peloton  session?

**Comment by cagnulein** [comment]
i check and the distance sent from qz is right. so it's for sure a cache issue on peloton app.
where peloton is running?

**Comment by hamster786** [comment]
Not sure I understand.  I've tried it since it became available to connect
to Peloton via ftms.  Yes wrong from very start of session.
There was one time it worked. Then started doing this. So maybe it is a
cache problem.   The Peloton app is running on iPad on  iOS 17.2

**Comment by hamster786** [comment]
Ok will try clearing cache and reset.  I’ll let you know.  Thanks!Sent from my iPadOn Jan 23, 2024, at 4:06 PM, Roberto Viola ***@***.***> wrote:﻿
i suggest to try to do the network reset, it's the only possible

explanation



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 23 gen 2024 alle 22:03 hamster786 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
@hamster786 Any news?

**Comment by hamster786** [comment]
So I deleted the Peloton app and reinstalled the app because there is no
other way to clear the cache any longer in iOS.  It fixed the issue for
awhile, however it starts happening again.  I don't know why.   I guess
just keep deleting cache??

I do have another question though but I will check FB first... Thanks

**Comment by cagnulein** [comment]
Peloton app has a lot of bug recently, I'm reading this in all the Facebook
group. So I guess yes, that's the only solution for now unfortunately

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 18:59 hamster786 ***@***.***>
ha scritto:

**Comment by hamster786** [comment]
Yeah.  Oh well. They need to get their act together. Lol.  Thanks for
follow up!!
