### ISSUE TITLE
[BUG] Healthrider H70T *control* support under iOS

### ISSUE THREAD

**Issue by Szepi** [cagnulein/qdomyos-zwift#2038]
**Describe the bug**
While my Healthrider H70T treadmill is recognized as a I_TL (IFit?) device, and the speed and inclination are correctly read from it, neither from the app itself, nor from Zwift can I control the speed (or inclination). Yet, the iFit app can connect to the same treadmill and control it from the phone. So it's not a capability that the Treadmill is missing.

**To Reproduce**

1. Install QZ on iPhone
2. Start QZ
3. Try to change the speed/inclination to no effect

**Expected behavior**
I expected the speed/inclination to be controllable.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: iOS (tried both on iPhone and a recent MacBook Pro, with latest iOS as of today)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 17.2.1

**Append a debug log**

Actually, on the Mac, settings does not scroll now, so I can't even do this anymore. I don't know what's going on there.
  
  
**Additional context**
That in the settings, I cannot even scroll and hence cannot even create a log file is quite annoying.

**Comment by cagnulein** [comment]
> Actually, on the Mac, settings does not scroll now, so I can't even do this anymore. I don't know what's going on there.

you have to hold the button and scroll down like you are doing on a phone

@Szepi for the control of the treadmill did you already tried all the profiles avaiable in the nordictrack treadmill settings? One by one enable them (only one enabled at a time) restart qz and try to force speed.

Let me know

**Comment by cagnulein** [comment]
check this also https://github.com/cagnulein/qdomyos-zwift/issues/1266#issuecomment-1428163408

**Comment by Szepi** [comment]
Thanks, this was helpful. Nordictrack T 6.5S v81 worked in my case to the degree that from my phone I can control the incline and speed. The latter only works once I start the treadmill (positive speed). Once the belt is going and the app shows positive speed, I could change the speed. So this is definitely progress.

Now, I am also trying to use the app as a bridge between Zwift and my treadmill. When doing this, as written above, I can see in Zwift the current speed and incline.

However, I would also like Zwift to control the speed of my treadmill when in a Zwift workout. This did not work.
Is there an easy fix to this? (I tried "speed forcing" but that did not change the outcome. When trying speed forcing, after enabling it, I quit the app, etc.)

Thanks for the help so far!

**Comment by Szepi** [comment]
Also, thanks for explaining how scrolling works on the Mac (I managed to scroll, yay!) Perhaps other users would appreciate a note about this in the documentation somewhere. And the same comment applies to the Healthrider treadmill. (And I hope we can sort out the remaining issue with Zwift).

**Comment by cagnulein** [comment]
> Also, thanks for explaining how scrolling works on the Mac (I managed to scroll, yay!) Perhaps other users would appreciate a note about this in the documentation somewhere. And the same comment applies to the Healthrider treadmill. (And I hope we can sort out the remaining issue with Zwift).

users doesn't read documentaion unfortunately :) things must work as users want, this is what I learned after 3 years of QZ development. So sooner or later, I will have to fix this scroll thing :)



> However, I would also like Zwift to control the speed of my treadmill when in a Zwift workout. This did not work. Is there an easy fix to this? (I tried "speed forcing" but that did not change the outcome. When trying speed forcing, after enabling it, I quit the app, etc.)

Auto inclination is already available on QZ beta (i can send you it, send me an email to roberto.viola83 at gmail.com indicating this ticket). When you will receive it add your zwift credentials to QZ.

For the auto speed instead, me and @victorypoint developed this only on Windows for the moment.
If you are interested, you can find the build in the release page of QZ here on github

Let me know!

**Comment by cagnulein** [comment]
@Szepi are we ok with this?
