### ISSUE TITLE
[BUG] Power Profile for Sportstech ESX600

### ISSUE THREAD

**Issue by hecuba** [cagnulein/qdomyos-zwift#2039]
**Describe the bug**
My Sportstech ESX600 is recognized by QZ and transmits data to Zwift, but the resistance value is set to double the value of the target resistance.

**To Reproduce**
1. Enable ERG mode in QZ
2. Pair with Zwift
3. Start Workout in Zwift

**Expected behavior**
The resistance should be set to adequate values.

**Smartphone:**
 - Device: iPhone14
 - OS: iOS 17.3
 - Version 2.15.4
  
**Additional context**
I added a wattage table and debug log to this issue.

[wattage.sportstech.esx600.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/14033414/wattage.sportstech.esx600.xlsx)
[debug-Di__Jan__23_22_59_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14033415/debug-Di__Jan__23_22_59_35_2024.log)

ChatGPT converted the table to a C function:

```C
// Function to calculate power based on resistance and cadence
double calculatePower(double resistance, double cadence) {
    // Coefficients from the polynomial regression
    double intercept = 14.4968;
    double b1 = -4.1878;
    double b2 = -0.5051;
    double b3 = 0.00387;
    double b4 = 0.2392;
    double b5 = 0.01108;

    // Calculate power using the polynomial equation
    double power = intercept +
                   (b1 * resistance) +
                   (b2 * cadence) +
                   (b3 * resistance * resistance) +
                   (b4 * resistance * cadence) +
                   (b5 * cadence * cadence);

    return power;
}
```

**Comment by cagnulein** [comment]
done! i will send you a new ios version asap

**Comment by hecuba** [comment]
That was fast!
Will try it when it is available and report back.

**Comment by cagnulein** [comment]
version sent! let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle ore 09:22 hecuba ***@***.***>
ha scritto:

**Comment by hecuba** [comment]
Just tried the Zwift ERG mode with the new power profile and it just works. Will extend the testing in the next days and weeks, but for now this issue is resolved!

I already mentioned it in my mail but i still can't have the heart rate signal from my apple watch while being connected to this bike.
When i turn on 'Fake Device' mode in experimental features, i see the heart rate in QZ from my watch.
When i'm connected to the bike, the built in heart rate monitor takes precedence over the watch. I can put my hands on the measurement plates and have the hr signal. 'Disable HRM from Machinery' is turned on.

Do you have an idea how to solve this?

**Comment by cagnulein** [comment]
Fixed!
I'm sending you another one today!
Thanks for the feedback

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle ore 22:35 hecuba ***@***.***>
ha scritto:

**Comment by hecuba** [comment]
Thank you!
Looking forward to try it out.

It seems like there are not all options available in every profile. 
Is there a 'complete' profile which can be compared to as a template?

**Comment by cagnulein** [comment]
this was just a copy and paste error :) this bike is not used from QZ users :) i guess you are the 2nd or 3rd person that uses this :)

**Comment by hecuba** [comment]
Friendly reminder :)
Can you send me the updated version on TestFlight?

**Comment by cagnulein** [comment]
i didn't find the time to build it. qz requests are going crazy during
winter!
i will try to do in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 19:23 hecuba ***@***.***> ha
scritto:

**Comment by hecuba** [comment]
Okay, no problem. You were so fast the last time, I thought you had forgotten. :)
Take your time. You‘re doing great work here!

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle ore 20:46 hecuba ***@***.***>
ha scritto:

**Comment by hecuba** [comment]
Tried it and HR sync now works!
Thanks for your time and effort.
All issues are now resolved. :)

**Comment by cagnulein** [comment]
amazing!
have a great weekend!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle ore 08:07 hecuba ***@***.***>
ha scritto:
