### ISSUE TITLE
[BUG] [Sportstech] ESX500 - incorrect logs for resistance 

### ISSUE THREAD

**Issue by ben75020** [cagnulein/qdomyos-zwift#204]
Client : QZ Android (latest stable)

What is working :
Resistance control from QZ Android client (with good values)

Problem : 
Resistance in logs is always displayed to '1' ( ih the given example should be at 7)

```
dim. mars 21 09:45:06 2021 1616316306577 Debug:   Characteristic change notification "{0000fff0-0000-1000-8000-00805f9b34fb}" 15 "f2d3100c34027a00c200c86901270007004f0103"
dim. mars 21 09:45:06 2021 1616316306580 Debug: ../src/bluetooth.cpp void bluetooth::debug(QString) " << f2 d3 10 0c 34 02 7a 00 c2 00 c8 69 01 27 00 07 00 4f 01 03"

dim. mars 21 09:45:06 2021 1616316306587 Debug: ../src/bluetooth.cpp void bluetooth::debug(QString) "Current resistance: 1"

```

Possible cause : 
https://github.com/cagnulein/qdomyos-zwift/blob/master/src/sportstechbike.cpp#L210

`    uint16_t convertedData = packet.at(18);`

This is not `packet.at(18)` but `packet.at(15)`

BUT 
Why it is currently correctly working on the android app screens  ?

**Comment by cagnulein** [comment]
yes it works because i don't use the resistance on the screen but i used
the request one!

    Resistance = requestResistance;


:)


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 mar 2021 alle ore 10:30 ben75020 ***@***.***>
ha scritto:

**Comment by ben75020** [comment]
solved with PR merged : 
https://github.com/cagnulein/qdomyos-zwift/pull/208
