### ISSUE TITLE
[BUG] Sportstech F37 cant Connect

### ISSUE THREAD

**Issue by trichter196** [cagnulein/qdomyos-zwift#2040]
**Describe the bug**

the App doesnt Connect to my treadmill (Sportstech F37)

**To Reproduce**
5. 

I open the app and no connection is made. I can connect to the Sportstech and Kinomap App though. 

**Expected behavior**

I expect the app to connect to my treadmill. 

**Screenshots**

**Desktop (please complete the following information):**
iOS 17.2.1

**Smartphone (please complete the following information):**
 
 iPhone 15 Pro
[debug-Mi__Jan__24_14_29_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14039029/debug-Mi__Jan__24_14_29_36_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @trichter196 were you near to the treadmill when you collect this debug log? i don't see it in the log
if so, which is the bluetooth name of this treadmill?

**Comment by trichter196** [comment]
Yes I was standing right next to it and it was turned on. In the Sportstech App the treadmill is called „FIT-1596“. 
I closed the Sportstech app before I opened the QZ App.

**Comment by trichter196** [comment]
Yes, I can see it in that app. 
![IMG_0434](https://github.com/cagnulein/qdomyos-zwift/assets/157608339/8efd752d-beca-4a00-b4b2-c95949211148)

**Comment by cagnulein** [comment]
ok perfect, so it's a FTMS one. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you a new version.
Then in the settings, treadmill settings, set the ftms treadmill settings to this device and press ok and restart QZ
Let me know
