### ISSUE TITLE
KingSmith Walkingpad A1 Pro

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2041]
![IMG_4639](https://github.com/cagnulein/qdomyos-zwift/assets/48216/e9de8d54-fa68-4135-a77d-09b4cfed0382)

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7642910179

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by SimonBB-DEV** [comment]
Working perfectly!
