### ISSUE TITLE
Device request: Tacx Satori Smart

### ISSUE THREAD

**Issue by tomroyal** [cagnulein/qdomyos-zwift#2044]
Hi

As per this Facebook thread: https://www.facebook.com/groups/149984563348738/posts/751195536560968

The Tacx Satori Smart trainer is picked up during Bluetooth scan, but does not connect.

CSV log file from nRF Connect attached - please let me know if you need any further info.

Thank you!

[satori_nrf.csv](https://github.com/cagnulein/qdomyos-zwift/files/14043726/satori_nrf.csv)

**Comment by cagnulein** [comment]
hi simply do this

set your Satori under settings, accessories, power sensor setting and press
ok and also enable power sensor as a bike and restart qz

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle 22:19 Tom Royal ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@tomroyal Hi, did you try?

**Comment by cagnulein** [comment]
also could you please share a nrfconnect screenshot as well? there are some information missing frm the log. Thanks

**Comment by tomroyal** [comment]
Will try this morning! 

In nRF Connect, what data is it you need, or which of the screens do you need a picture of?

**Comment by cagnulein** [comment]
just a picture showing the trainer it should be enough :)
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 09:58 Tom Royal ***@***.***>
ha scritto:

**Comment by tomroyal** [comment]
Sorry for the late reply on this! 

Your suggestion worked perfectly - thank you. Screenshots attached below FYI.

![IMG_0767](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/d3a9e477-3829-4e11-b50a-15f0a1400602)
![IMG_0771](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/f21f428b-3f33-415f-8332-58a5f5c1ecff)
![IMG_0770](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/1131feb5-f559-4eda-a5d3-8d5475e4031a)
![IMG_0769](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/cbb6a49f-ba71-4a30-92db-e0284a88d478)
![IMG_0768](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/d5e06fb6-4e03-4cd6-ab29-a2e58b38a8ff)

**Comment by cagnulein** [comment]
great! remember to rate the app on the store, it means a lot to me! thanks!
