### ISSUE TITLE
[BUG] Apple Watch Heart Rate won't appear on iPhone

### ISSUE THREAD

**Issue by rablatbenjamin** [cagnulein/qdomyos-zwift#2045]
I followed all the procedures to connect the Apple Watch to my QZ app but I never managaged to get some data on the iPhone.

I tried this procedure : 
be sure that the Heart Belt Name setting in QZ is "Disabled"
open the QZ app on the AW
giving ALL the permission to Apple Health
press start on the QZ app on the AW
the Heart value on QZ on the iphone will magically appear

I tried with restarting the iPhone and the Watch.
I tried by launching Apple Watch app before, and after, launching QZ app on the iPhone.

When I launch the Apple Watch app and touch start, I get my heart rate on the Watch screen a few seconds later.
The issue might be with the communication between the Apple Watch and the iPhone Apps

iPhone 15 Pro with IOS 17.3
Apple Watch 8 with WatchOS 10.3
QZ 2.15 (latest on Apple Store)

**Comment by cagnulein** [comment]
provide a debug log please
also try to reinstall the app on the watch
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 gen 2024 alle 22:39 BenjaminR ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi, in this log you are not connected to the bike. could you please collect
one while you are connected?
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle ore 11:08 BenjaminR ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@rablatbenjamin Any news?
