### ISSUE TITLE
[BUG] Nautilus T628 No Incline

### ISSUE THREAD

**Issue by DavidWiseman** [cagnulein/qdomyos-zwift#2046]
**Describe the bug**
Support for Nautilus T628 was [just added](https://github.com/cagnulein/qdomyos-zwift/issues/2043), but it doesn't display any incline information.  It's possible that the treadmill doesn't provide this info but if it does it would be nice to have.  

An option to specify it manually might be cool for devices that don't supply the info.

**Smartphone (please complete the following information):**
 - Device: S20
 - OS: Android 13

**Append a debug log**

[debug-Wed_Jan_24_21_23_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14043827/debug-Wed_Jan_24_21_23_28_2024.log)

I went through a range of inclines in the above debug log.

Thanks!

**Comment by cagnulein** [comment]
unfortunately it seems that it doesn't send the inclination over bluetooth. maybe you can try a debug log where you are going step by step from the min incline to the max and again to the min.
Let me know

**Comment by DavidWiseman** [comment]
[debug-Thu_Jan_25_19_20_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14057037/debug-Thu_Jan_25_19_20_47_2024.log)

Thanks for checking - that's what I did in the last test.  I've attached another one above just in case I attached the wrong file.  This test has the speed at 2mph and the incline going from 0% stepping to 15% then back down to 0% again.

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 20:30 David Wiseman ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
unfortunately I checked but any bytes in the log goes up and then goes back so the treadmill is not sending this information. are you sure you have the latest firmware possibile on your treadmill?

**Comment by DavidWiseman** [comment]
Hi, good shout to check the firmware.  It doesn't look like any firmware updates are provided so I don't think there is any more that can be done here.  The option to manually supply the incline in the app could maybe be considered.

Thanks for checking this out. 🙏

**Comment by cagnulein** [comment]
If you want I can add that if you press the plus and minus button of the inclination tile you can manually override it

**Comment by DavidWiseman** [comment]
> If you want I can add that if you press the plus and minus button of the inclination tile you can manually override it

I think that would be a good workaround for any treadmills that don't transmit incline.

**Comment by cagnulein** [comment]
Done! It will be in the next one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 09:06 David Wiseman <
***@***.***> ha scritto:

**Comment by DavidWiseman** [comment]
Wow.  That's great! 👍
