### ISSUE TITLE
Cardiostrong BX70i, Automatic resistance, ERG mode

### ISSUE THREAD

**Issue by Dominik2910** [cagnulein/qdomyos-zwift#2048]
Hello Roberto,
 I use a Cardiostrong ergometer, Model BX70i (iconsole+), and I also use Assioma duo for more precision. In the QZ settings, I use Fytter RI08 Bike instead of iConsole bike because iConsole bike didn't work well.

So far, I can use the system, but it would be extremely cool if the following could be possible:

- Automatically adjusting resistance for uphill or downhill rides would be nice. Currently, my avatar only gets slower or faster accordingly. Is there anything that can be done about this?

- I can only use the Zwift Workout option with Erg mode without the QZ app. I've already selected the Zwift Erg mode option in the bike settings, but it didn't improve the situation.

I would appreciate it if you have a solution for this.

Best regards,
Dominik Ostaszewski

**Comment by cagnulein** [comment]
hi @Dominik2910 let's start providing me a debug log from you current setup. Let me know

**Comment by Dominik2910** [comment]
Hello Roberto,

below you will get to the File. I hope you can find a solution for all BX70i riders 😅. If you need more information or you want that i try something new than feel free to contact me.

Best regards,
Dominik

https://github.com/Dominik2910/Bx70i/blob/main/debug-Do__Ja%CC%88n__25_15_28_11_2024.log

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

**Comment by cagnulein** [comment]
ok so log checked. first of all you need to setup this correctly. in order to do so, set the manual device setting in the advanced setting to your iconsole bike and press ok, also set your assioma under accesories, power sensor setting and press ok
restart qz then and share me a debug log then
Let me know

**Comment by Dominik2910** [comment]
Hello @cagnulein hope you are fine!

thanks for your quick answer! I put in the settings like you said and after a little waiting time (this was new for me) the ergometer display turns on again. So i was ready to make the test and take the first hill and i'm think it works well! My first opinion is that this is amazing Roberto!
Issue with Powermeter: I use the assioma duo is there a possibility to get both pedals linked with QZ? What solution do you think is the best?
I have already uploaded the Logfile.

Meanwhile i will try the Workoutmode with the same settings.

Thank you Roberto.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/f3cb81b5-c0e9-412c-81e1-289fcbea9028)


![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/c4e0088c-6920-4ccc-8c12-a7abe7edf7f0)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/96bdfcf8-c480-42f1-8473-e5eddf97d0b7)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/8262c88a-1220-4258-aea1-bab3e2b3c32a)

debug-Fr__Jän__26_10_12_35_2024.log

**Comment by cagnulein** [comment]
i can't see the debug file.
anyway for the moment is not possible to connect both power pedal.
Let me know how it will go the erg mode, as far as i can remember i didn't handle erg mode for your bike

**Comment by cagnulein** [comment]
i added in a beta a power table for #1999

**Comment by Dominik2910** [comment]
Ok i will look at this one and come back to you! Thanks

I tried something. via ant+ dongle i linked the assioma duo to zwift. i get now the right watts at zwift but only the half amount on QZ. 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/27b522ca-6203-45e2-8f5d-def4396f73dd)

**Comment by Dominik2910** [comment]
By the way: It is now possible to use the workout mode. It works perfect! 😝


![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/82c9f2b0-69ab-4a43-bcf3-acf881ff43e0)

**Comment by cagnulein** [comment]
@Dominik2910 set the watt gain to 2 to qz

**Comment by Dominik2910** [comment]
ok i will do it

**Comment by Dominik2910** [comment]
@cagnulein 

here the pic. just to be sure that i'm doing it correctly. 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/26b4328c-a998-4d8d-a920-1397f065a8cd)

**Comment by Dominik2910** [comment]
I'm sorry @cagnulein 
here is the file...

https://github.com/Dominik2910/Bx70i/blob/main/debug-Fr__Ja%CC%88n__26_10_12_35_2024.log

**Comment by cagnulein** [comment]
nope not that one, watt gain in the advanced setting

**Comment by Dominik2910** [comment]
thanks for the correction 👍. So it should double up the watt? that's a good solution.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/157697060/a769f83b-a6a3-48b9-b6f0-ec05351a76fe)

**Comment by cagnulein** [comment]
yes!

**Comment by Dominik2910** [comment]
@cagnulein 

Thanks a lot for the professional support! It is amazing what's possible! Can't believe it 😳.

best regards

**Comment by cagnulein** [comment]
no problem! remember to join the patreon to support the project! https://patreon.com/cagnulein
