### ISSUE TITLE
[BUG] Auto Resistance not working when manually loading .zwo file

### ISSUE THREAD

**Issue by sparkyparkes** [cagnulein/qdomyos-zwift#2049]
**Describe the bug**
When using a .zwo file that I loaded manually, the auto resistance isn’t working. This did work for me in previous sessions. 

**To Reproduce**
1. Go to Open Train Program
2. Load .zwo file
3. Start workout
4. Auto resistance not working

**Expected behavior**
Bike to follow auto resistance 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 2.16.34

**Smartphone (please complete the following information):**
 - Device: iPhone14
 - OS: iOS 17.2.1
 - Version 
[debug-Thu_Jan_25_07_05_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14053589/debug-Thu_Jan_25_07_05_45_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Thu_Jan_25_07_05_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14053599/debug-Thu_Jan_25_07_05_45_2024.log)

**Comment by cagnulein** [comment]
you have to press start after loading the zwo file. that's the issue. you can see it because the target wattage tile will popuplate
Let me know

**Comment by cagnulein** [comment]
great!
