### ISSUE TITLE
[BUG] [Android 10] Zwift bridge crashes at fixed hours (each quarter of hours)

### ISSUE THREAD

**Issue by ben75020** [cagnulein/qdomyos-zwift#205]
Client QZ  Android 10 (realme UI)

Every 15 minutes exactly, the zwift connected application to the QZ Bluetooth bridge looses signal.
It seems connected in bluetooth but displays "No data received"

I have to restart the application, to search for the captor in zwift AND it's working fine for another 15 minutes.

I deactivated every power optimization for the application in Android.
Wavelock is enabled in the application settings.

**Comment by cagnulein** [comment]
It's definitely something on your power management. Disable the screen
timeout on your android settings

Il dom 21 mar 2021, 11:53 ben75020 ***@***.***> ha scritto:

**Comment by ben75020** [comment]
[debug-Sun Mar 21 09_15_19 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6177241/debug-Sun.Mar.21.09_15_19.2021.log)
[debug-Sun Mar 21 09_45_20 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6177242/debug-Sun.Mar.21.09_45_20.2021.log)

![IMG-0203](https://user-images.githubusercontent.com/40180297/111902200-775a2780-8a3c-11eb-861b-77a37efccb93.PNG)

**Comment by ben75020** [comment]
let me be more accurate : 
This is happening EXACTELY when the clock reaches a quarter :  12:00, 12:15,  12:30. 
It happened again (with another application) after a 10 minutes ride.

The issue can be on the ipad side or the android side, the logs outputted from the application are not verbose enough.

However I think this is on the android side : we can clearly see that zwift detected another time the phone from the screenshot.

I'll have a try with an iphone this afternoon to check this theory.

**Comment by ben75020** [comment]
![IMG-0204](https://user-images.githubusercontent.com/40180297/111904869-3fa5ac80-8a49-11eb-90c6-daefd8afd589.PNG)

I'm now sure : this happened at 13:15 : the bluetooth mac address from the domyos service was rotated. We can see the previous and new mac address in the trainer app.

This is likely something related to privacy, I'm searching. This might be related to the manufacturer implementation of android or android 10 it self.

**Comment by cagnulein** [comment]
Android phone since android 10, every time they broadcasting itself, they
are changing the mac addresses randomly. It's a privacy feature.
So if every 15 minutes the mac changes means that your phone drops the
connection (or Zwift)

Il dom 21 mar 2021, 13:32 ben75020 ***@***.***> ha scritto:

**Comment by ben75020** [comment]
> And yes, this is only 24 bit of randomness. This can be assumed to be enough. Since your device changed it MAC regularly, a sniffer has a change of 1 / 16.777.216 to guess what is you next MAC. 

That makes me sad, cause everything else is working perfectly.

I found nothing to disable this feature on the phone settings.
I don't know what to do, I'm available for debuggings on my phone. 

(I am the only one android 10 user of the app ?)

**Comment by cagnulein** [comment]
I have 911 android 10 users according to google play statistics :)
So it's just something on your type of phone :)
Do you have an older phone?
You can try also creating a bug report from the developer settings after
the 15 minutes timeout and we could check what really happens on your phone
;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 mar 2021 alle ore 13:55 ben75020 ***@***.***>
ha scritto:

**Comment by ben75020** [comment]
I found the issue after factory-resetting my phone. (the app worked perfectly when it was the only-one installed)

So I searched what could be the cause and reinstalled applications one by one, and testing every time. 
In the end, this was the French official COVID-19 tracker responsible for the problem.

The french-government Android application "**Tous Anticovid**" (https://play.google.com/store/apps/details?id=fr.gouv.android.stopcovid&hl=en&gl=US) is resetting the Bluetooth stack at fixed hours for privacy compliance.

Immediately after deleting this app and restarting the phone : no more crashes at fixed hours.

**Comment by ben75020** [comment]
Still under observation for next days (well, you need to bike to test ! So you cannot test the whole day :)

**Comment by cagnulein** [comment]
Unbelieavable!
Great discovery!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 mar 2021 alle ore 08:29 ben75020 ***@***.***>
ha scritto:

**Comment by ben75020** [comment]
https://gitlab.inria.fr/stopcovid19/stopcovid-android/-/blob/master/stopcovid/src/main/assets/Privacy/privacy-en.json#L18
