### ISSUE TITLE
Issues Connecting to QZCompanion on NordicTrack X11i from iOS 17.3

### ISSUE THREAD

**Issue by mjohnsontri** [cagnulein/qdomyos-zwift#2050]
**Describe the bug**
I'm a new user trying to get this working with my NordicTrack x11i. I was able to install the companion on the treadmill using ADB and am trying to use the QZ app on my iPhone. I’ve exported the debug logs on my phone and it appears the app is connecting to my treadmill successfully but the logs indicating current incline, speed, etc are all always zero no matter what. I’ve also confirmed that the companion app is running on my treadmill. I also set the IP properly along with the required settings in the iOS app. 

**To Reproduce**
1. Start Treadmill and confirm QZ Companion App is Running
2. Start QDOMYOSZWIFT App on iPhone
3. No values are displayed in the app - all are zeroes.

**Expected behavior**
Incline and speed values are displayed in the iOS QDOMYOSZWIFT app.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.7.10
 (note - this was used to install the QZ Companion successfully to the treadmill via ADB)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 17.3
 - Version 17.3

**Append a debug log**

[debug-Thu_Jan_25_09_38_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14055692/debug-Thu_Jan_25_09_38_19_2024.log)
  
**Additional context**
N/A

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 17:58 mjohnsontri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @mjohnsontri checked the log and the good news is that the companion is correctly sending messages to qz on your phone. Unfortunately the messages are empty, this means that the compnaion can't read metrics from your treadmill. could you please follow this and report back?

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

Thanks

**Comment by mjohnsontri** [comment]
Hi! I tried all of the steps outlined above including the factory reset and am still getting all zeroes. When resetting the machine I declined installing any additional updates other than what it gives no choice on. I also confirmed the QZ companion app permissions are all enabled. Logs are attached. Thanks!
[debug-Sat_Jan_27_09_11_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14072809/debug-Sat_Jan_27_09_11_02_2024.log)

**Comment by cagnulein** [comment]
ok so we need to use the grand tour trick. did you already try it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 16:20 mjohnsontri ***@***.***>
ha scritto:

**Comment by mjohnsontri** [comment]
I tried that and was able to get speed, but no incline. Additionally, after a treadmill restart the issue came back.

**Comment by mjohnsontri** [comment]
[debug-Sat_Jan_27_11_57_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14073607/debug-Sat_Jan_27_11_57_02_2024.log)

**Comment by cagnulein** [comment]
i can see the grade in the log. i guess i already fixed it, i will check the commit in then next days and i will report back!

**Comment by cagnulein** [comment]
mmm checked actually in the log i see speed at 1.6kmh and the treadmill is reporting grade went from 3 to 0. is it real?

**Comment by mjohnsontri** [comment]
I actually increased the grade, then decreased it after several seconds. Unfortunately, it didn't reflect on my iPhone app. Additionally, it didn't work after I restarted my treadmill. Not sure if that's normal or not.

**Comment by cagnulein** [comment]
did you install the companion with the batch file or directly with a
browser on the tablet?
the first method should avoid the reboot issue

for the grade i need a adb debug while you are doing a workout using this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat


i'm going to bed  now, we will catch up tomorrow
have a nice saturday evening!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 22:08 mjohnsontri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mjohnsontri any news?

**Comment by mjohnsontri** [comment]
Apologies for the absence, life got busy! Back in action now though. Here's the log file generated today (2/25) with some testing. I did install QZ Companion using ADB on my Mac.

I tried a variety of profiles after updating QZ Companion to the latest on master as of today (X11i which is my actual model, X22i, Grand Tour). I did notice that I sometimes would get erroneous speed and incline readings on the iOS app, and that pressing buttons to change speed / incline in the app occasionally did something, but the app would read 5.5% grade when the treadmill was at 40%. I do have the touch speed/grade controls enabled. There's clearly some communication going on, but the mappings/values may be incorrect.
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/14397098/logcat.txt)

**Comment by cagnulein** [comment]
Hi again, did you took this while the workout was finished? if so you have
to take it while the workout is running because otherwise ifit will clear
it.
let me know!


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 17:58 mjohnsontri ***@***.***>
ha scritto:

**Comment by mjohnsontri** [comment]
Hi! That previous log was not taken while the workout was running. Here's a trimmed log file I just took during a workout moments ago. Hope this has what you need in it. Thanks!

Logfile: 
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/14397204/logcat.txt)

**Comment by cagnulein** [comment]
Unfortunately there is no metrics inside. Maybe you trimmed too much? You
have to see some "changed" lines inside of it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 18:35 mjohnsontri ***@***.***>
ha scritto:

**Comment by mjohnsontri** [comment]
I actually trimmed it based on the timestamps, so it contained everything from the recent session. I even changed speed/elevation as it was running.

**Comment by cagnulein** [comment]
Unfortunately there is anything, maybe the timestamp in the file is wrong. Chdck the full log with the "changed" keyword

**Comment by mjohnsontri** [comment]
Nothing turned up there either unfortunately. I'll try to run a test again later this afternoon and report back.

**Comment by cagnulein** [comment]
If you see the metrics on qz it means that qz can read it somehow so I
guess you are doing something differently when you are getting the log.
Let me know if I can help you somehow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 19:03 mjohnsontri ***@***.***>
ha scritto:

**Comment by mjohnsontri** [comment]
Well I’ve only gotten numbers to show in QZ once or twice and they weren’t accurate (5.5 grade in QZ and 40 on the treadmill for example) when they did show.  Could the lack of info in the log file be an explanation?

**Comment by cagnulein** [comment]
Nope they are 2 different issue

Anyway to solve the qz issue I suggest to reset  the treadmill and DON'T
update the ifit app. Probably ifit stops to log the metrics on the log
because they saw qz is spreading on their user bases

Let me know how it goes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 19:12 mjohnsontri ***@***.***>
ha scritto:
