### ISSUE TITLE
[BUG] Compilation fails on Raspberry Pi Zero W (Qt 5.11->5.14, QRecursiveMutex)

### ISSUE THREAD

**Issue by Szepi** [cagnulein/qdomyos-zwift#2051]
**Describe the bug**
I attempted to compile the code on Raspberry Pi Zero W, following the instructions from [here](https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md), and the compilation failed.
The first failure was that qmake was not available.
I solved this by running `sudo apt-get install qt5-default`
Next, when compiling the code, `QRecursiveMutex` was reported as undefined type when `pelotonbike.cpp` was compiling.

Here is the error message:
```
In file included from powerzonepack.h:21,
                 from peloton.h:5,
                 from homeform.h:8,
                 from pelotonbike.cpp:2:
trainprogram.h: At global scope:
trainprogram.h:143:13: error: ‘QRecursiveMutex’ does not name a type; did you mean ‘QBasicMutex’?
     mutable QRecursiveMutex schedulerMutex;
             ^~~~~~~~~~~~~~~
             QBasicMutex

```
My QT version is 5.11:

```
$ qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/arm-linux-gnueabihf

```
Googling around tells me that I need Qt 5.14

So how should I compile the code on my Raspberry Pi? (What is the best way of getting an appropriate version of Qt and what version is that?)

**To Reproduce**

Start with a Fresh Raspberry Pi Zero W!
Follow instructions (see above).

**Expected behavior**
I expected the code to compile.

**Desktop (please complete the following information):**

```
$ uname -a
Linux raspberrypi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux

```

**Comment by cagnulein** [comment]
i guess you don't have qt 5.15.2 right? it's a requirement

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 06:52 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
Yes, you are correct. Do you have some guidance of how to install 5.15.2? This would be helpful as the internet seems to have many many pages devoted to this, but it is unclear which of these are reliable. In particular, they are not official; and it seems there is no official support for 5.15.* on Raspberry Pi.

**Comment by cagnulein** [comment]
use this image
https://drive.google.com/file/d/1Zk27ArTUFb-2ySLpSSZMSHpLpxI1n1y9/view?usp=drivesdk


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 19:29 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
What is on this image and how to use it? (Do I burn this to a Micro SD card and then boot?? from it or..?)
Sorry for being terse!

**Comment by cagnulein** [comment]
yes just burn it, it has already everything
it was made from  another qz user

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 20:09 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
Thanks, this is great. But.. I can burn it, sure, but then what..?

**Comment by cagnulein** [comment]
it has already all the requirements

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 20:14 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
Sure, but do I copy the content over to my Raspberry PI? I guess that's what you are implying..? Some of these are system files..? Will this work? Just overwrite if needed?

**Comment by cagnulein** [comment]
this is a full image to replace your existing one
otherwise just install qt 5.15 on your distribution
if it's not supported for your distro, build it
which distro are you using by the way?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 20:24 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
```
$ uname -a
Linux raspberrypi 5.10.103+ #1529 Tue Mar 8 12:19:18 GMT 2022 armv6l GNU/Linux
```

**Comment by cagnulein** [comment]
yeah but where did you download this?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 21:11 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
raspbian..? (CanaKit sells Pi Zero W with NOOBS, and I went with the default choice there, which I think is Raspberry PI OS = raspbian) This is what I see in os-release:
```
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by cagnulein** [comment]
update it do debian 11

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 21:27 Csaba Szepesvari <
***@***.***> ha scritto:

**Comment by Szepi** [comment]
Update on my side: I have updated my Raspberry to Debian 11 and followed the instructions and I was able to compile the code. When running it, I cannot connect to my treadmill; no idea why. But I will add a separate ticket about that.
So to summarize, to compile on a Raspberry Pi, Debian 11 (or newer?) are essential. I added a pull request to document this.
