### ISSUE TITLE
ECHEX-7S connectivity issue with 2.16.38

### ISSUE THREAD

**Issue by vineman70-3** [cagnulein/qdomyos-zwift#2054]
**Describe the bug**

**To Reproduce**

**Expected behavior**

I am running 2.16.38. I got a new iPad Pro to run the app thinking it might have better connectivity. Unfortunately, I have not been able to get either the bike or treadmill to work at all, let alone get auto-incline adjustments on Zwift on the treadmill. I set up 2 profiles one for the bike and one for the treadmill.

For example, sitting on the bike again it finds everything except the bike but eventually I manage to find the bike and put it in manually in the advanced setting; Manual Device: ECHEX-7S-100974. But it does not show up at the top of the tiles under Pause & Stop – something always else does as in the attached screen shot. The Pause & Stop remain “greyed out”. I can push the “+” button in speed or inclination & then watts comes up, but there is never a cadence reading.

By turning the app, Zwift, BLE on and off somehow, I get the Zwift avatar to move if I can get a watt reading, BUT within less than a minute the app crashes and everything stops. Nothing I could figure to do stops the crash no matter how many times I tried. So, I am completely stuck.

Of less importance even though I indexed a set of tiles for the bike profile (0, watt; 1, cadence; 2, heart; 3, inclination; 4, elevation; 5, odometer; 6, pace; 7, FTP%; 8, elapsed; 9, time; and 10, speed) the tiles that appear, as in the attachment, never match what I put in the tiles options.

So, unless what I did makes any sense and you can suggest something, I cannot think what to do except to delete the beta version and go back to the 2.15 version and at least be able to do the bike and run on Zwift without auto-inclination etc.

**Screenshots**
![IMG_1179](https://github.com/cagnulein/qdomyos-zwift/assets/157830113/0515fd19-83ba-4c98-b033-cda98f38d294)

**Desktop (please complete the following information):**
IOS 17.3
**Smartphone (please complete the following information):**
iPad ro (11-inch) 4th generation
**Append a debug log**
[debug-Thu_Jan_25_10_24_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14067548/debug-Thu_Jan_25_10_24_14_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks I will check it as soon as possible

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 18:08 vineman70-3 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
log checked, i saw that you have a lot of fitness devices around you. So for sure when you want to use the bike you need to set it to the manual device setting in the advanced setting. You can create a profile for it to switch it quickly.

For the treadmill: which treadmill do you have? A life fitness one?

**Comment by vineman70-3** [comment]
Yes, there are 3 Lifefitness treadmills (plus ellipticals, stairmasters, etc)

**Comment by cagnulein** [comment]
ok so let's start from the bike. set it as a manual device and everything
should works.
let me know if it's not

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 12:22 vineman70-3 ***@***.***>
ha scritto:

> Yes, there are 3 Lifefitness treadmills (plus ellipticals, stairmasters,
> etc)
>

**Comment by vineman70-3** [comment]
That is exactly what I have been doing and it has not worked, Even though I set the bike in manual under advanced options it does not appear and remain at the top of the app under start/stop the way it did in 2.15.4. I have also set it up that way in a “bike” profile. However, I will try it all again today and see how it goes. Thank you.

**Comment by cagnulein** [comment]
send me a log in this context because the log you sent me it's about a
treadmill connection, not the bike.
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle ore 13:36 vineman70-3 <
***@***.***> ha scritto:

> That is exactly what I have been doing and it has not worked, Even though
> I set the bike in manual under advanced options it does not appear and
> remain at the top of the app under start/stop the way it did in 2.15.4. I
> have also set it up that way in a “bike” profile. However, I will try it
> all again today and see how it goes. Thank you.
>

**Comment by cagnulein** [comment]
@vineman70-3 i can't see the attachment, you have to upload it from the github web interface. The problem is that I will update the 2.15.4 on the store soon with the 2.16.30 so I have to fix this for you otherwise you can't use the app anymore.

**Comment by cagnulein** [comment]
#2069
