### ISSUE TITLE
[BUG] Connection hanging and HR not working

### ISSUE THREAD

**Issue by branmedi1993** [cagnulein/qdomyos-zwift#2055]
**Describe the bug**
I’m having 2 issues that I’m hoping you can help me with. First off I’m using a Bowflex btx6 treadmill and a series 5 Apple Watch. QZ version 2.15.4

First issue is that after about 24 minutes (or possibly 2.5miles) the connection seems to be lost and data from the treadmill is no longer transmitted to the app. In fact the app shows the pause/play button at the top blinking. 

Second issue is with getting my Apple Watch to show the heart rate in the app. I feel like I’ve tried everything but nothing works. I hit start on QZ on my watch (heart rate shows on watch), then start the app on my phone. But the heart rate is not displayed on QZ on my phone or in the data that is sent to Strava. 

**Screenshots**

![IMG_0703](https://github.com/cagnulein/qdomyos-zwift/assets/157848299/d3093335-4154-44d1-96d6-653235f297e0)
![IMG_0702](https://github.com/cagnulein/qdomyos-zwift/assets/157848299/e668532f-7234-42a7-a46b-83a8ea5b00ab)
![IMG_0701](https://github.com/cagnulein/qdomyos-zwift/assets/157848299/1253ec9b-0d9a-440a-ae0e-4e7bb7d88f66)
![IMG_0700](https://github.com/cagnulein/qdomyos-zwift/assets/157848299/6670d5ea-8804-48b7-967c-c4333c15788c)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - Version 17.2.1
 
 - Apple Watch 5 
 - Version 10.3

**Append a debug log**
[debug-Fri_Jan_26_13_43_13_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14069472/debug-Fri_Jan_26_13_43_13_2024.zip)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check this in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 22:25 branmedi1993 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok for the first issue i did something in the beta, anyway it's fixable if it isn't already.
i'm fixing the apple watch one now! thanks for the feedback!

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by branmedi1993** [comment]
@cagnulein Update. I just did a workout with the beta version and I can confirm that the HR is now working from my Apple Watch Ultra 2, but the connection is still hanging. After a few runs, it seems like the connection problem is connected to a distance of 2.55miles (it always hangs at this exact distance). 

Here are a couple debug logs with the bug in case they help: 
[debug-Mon_Jan_29_16_05_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14091390/debug-Mon_Jan_29_16_05_26_2024.log)
[debug-Mon_Jan_29_16_11_09_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14091391/debug-Mon_Jan_29_16_11_09_2024.zip)

**Comment by cagnulein** [comment]
got the issue, i'm sending you a fix today! let me know then!

**Comment by branmedi1993** [comment]
Just did a run and the fix was successful! You are awesome. Thank you!

**Comment by cagnulein** [comment]
That's great!
I don't know if you did already, but please take a minute to rate the app on the store, it means a lot to me! Thanks!
