### ISSUE TITLE
[BUG] EX5, gears changing by themselves

### ISSUE THREAD

**Issue by Scott902** [cagnulein/qdomyos-zwift#2059]
**Describe the bug**
[debug-Fri_Jan_26_18_17_19_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14072289/debug-Fri_Jan_26_18_17_19_2024.zip)

EX5, ipad running QZ, Apple TV running Zwift.  Gears will change randomly by themselves

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
yes confirmed the issue is the gears from knob setting.
I will try to fix it.
For the moment disable it and yoiu should be right
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle ore 13:40 Scott902 ***@***.***>
ha scritto:

**Comment by Scott902** [comment]
Perfect, thank you sir!

**Comment by cagnulein** [comment]
i was examining the log and I guess I found the issue: you are using the gears tile with this setting enable. With this enable you should just use the knob to change the gears.
When you have time, try it in this context.

**Comment by Scott902** [comment]
I’ll probably just disable the knob, as I prefer the tile tbh.

Scott
