### ISSUE TITLE
POWER AND CADENCE NORDICTRAK S22I CHART

### ISSUE THREAD

**Issue by Ccujar** [cagnulein/qdomyos-zwift#2060]
Good Morning
Here is the chart created.  Im trying to get ERG to work with TrainerRoad
Thank you
Camilo Cujar
[NORDICTRACK.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/14072422/NORDICTRACK.xlsx)

**Comment by cagnulein** [comment]
Thanks, I'll take a look in the next days!


Il giorno sab 27 gen 2024 alle 14:33 Ccujar ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok chatgpt calculates me the code

```
#include <stdio.h>

double estimate_power(double resistance, double cadence) {
    // Coefficients from the polynomial regression model
    double intercept = 176.2792955668276;
    double coeff[6] = {0.0, -24.0415287, -3.69535714, 0.657240597, 0.310843524, 0.0165869536};

    // Calculate the power using the polynomial equation
    double power = intercept 
                   + coeff[1] * resistance 
                   + coeff[2] * cadence 
                   + coeff[3] * resistance * resistance 
                   + coeff[4] * resistance * cadence 
                   + coeff[5] * cadence * cadence;

    return power;
}

int main() {
    // Example usage
    double resistance = 11;
    double cadence = 55;
    double predicted_power = estimate_power(resistance, cadence);
    printf("Estimated Power: %f\n", predicted_power);

    return 0;
}

```

@Ccujar can you share me a simple debug log from your bike so I will apply this to the correct profile? thanks

**Comment by Ccujar** [comment]
Here is the log for this morning.
Thank you for your help
[debug-Mon_Jan_29_10_36_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14087414/debug-Mon_Jan_29_10_36_51_2024.log)

**Comment by cagnulein** [comment]
hah ok you are using the companion. are you already able to change
resistance from qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle ore 18:02 Ccujar ***@***.***>
ha scritto:

**Comment by Ccujar** [comment]
I change resistance directly from the bike "NordicTrak SS221".  But the ERG mode on TrainerRoad doesn't work.  Is my understanding it has to change the resistance automatically and all give me the target power and all depends on cadence

**Comment by cagnulein** [comment]
yes your concept is correct, but the requirement is that you should be able to change resistance at least manually from qz right now without this patch. So i'm using this feature to also give you ERG mode.
I know that this is working for S22i qz users, so i would like to double check this with you before adding this!
Let me know!

**Comment by Ccujar** [comment]
Checking now

**Comment by Ccujar** [comment]
I can't control Resistance and/or Inclination from the tiles

**Comment by cagnulein** [comment]
what do you mean?

**Comment by Ccujar** [comment]
seems like my IOS doesn't support I tried in my phone that is newer and it runs but no change with the tiles

**Comment by cagnulein** [comment]
nope you shouldn't change anything to get the metrics at least

create me a debug log in this scenario so i will understand what you are
saying
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle 19:12 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
App running but I can change tiles résistance or inclination.  I press the + or - and numbers dont move at all. 
[debug-Mon_Jan_29_13_17_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14088139/debug-Mon_Jan_29_13_17_57_2024.log)

**Comment by cagnulein** [comment]
ok enable the adb remote under the nordictrack bike settings and restart qz
then try again and let me know if at least can you see a touch event when
you press the tile on qz
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle 19:23 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
Nope!  Tiles dont change even the numbers when I press + or -  They stay the same.  They only change the number only when I change on the bike.  I have the right readings but I can't control from QZ

**Comment by Ccujar** [comment]
Nope. No fake touch on ifit.  I installed the companion with adb.

Thanks for all your help

**Comment by cagnulein** [comment]
If from the pc ,in the adb folder you type

adb shell input swipe 100 200 300 400 200

Do you see a fake touch?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 00:22 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
Where is the ADB folder and how can I type it?
Thanks
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/bf652097-79a4-4f89-8680-94be07b589d4)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/8bbab494-341f-4065-b23c-2f3fca6ab7db)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/62d845c1-273f-4226-abea-4b3760c2971a)

**Comment by cagnulein** [comment]
installpackage is the right one. open a dos prompt there

**Comment by Ccujar** [comment]
That’s what I got

**Comment by Ccujar** [comment]
I’m here now
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/1890bd01-2152-445c-a4ff-18003f2d831a)

**Comment by cagnulein** [comment]
nope i mean, open a prompt using the run function on windows and type "cmd"

then navigate to the install folder using the windows command "cd"

then type the command that I wrote above.

Are you able to do so?

**Comment by Ccujar** [comment]
I’m stock here.  I’m not familiar wit this
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/2d9f5cee-f71f-4b5e-addb-e37b3990a6af)

**Comment by cagnulein** [comment]
unzip this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14078746/adb-swipe.zip onthe installpackage folder, it will be simplier for you
let me know

**Comment by Ccujar** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/7ccad89c-e85d-470b-b93b-351137df3492)
That’s what I got

**Comment by cagnulein** [comment]
did you put the file in the same directory there the adb is?

**Comment by Ccujar** [comment]
Now I did in got this
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/b60a45a6-b41f-496c-85ba-5d30cb023aa2)

**Comment by cagnulein** [comment]
Try to reboot the bike, it seems that adb is closed now

**Comment by Ccujar** [comment]
Restart the bike and now this.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/a293444b-7a4a-40bc-81b8-e4a7523a6a6a)

**Comment by cagnulein** [comment]
Perfect so did you see a virtual touch event on the tablet when you run it?

**Comment by Ccujar** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/09112213-e417-4dd8-9065-6cfac6c5f6d9)
So you think is anything with the developer options setup?
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/f7cbce37-e9e2-4654-9fed-e7c9c808edc6)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/e26b6710-0a1d-4bd3-9d64-a64511cf24ad)

**Comment by Ccujar** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/eb917acd-7b7d-4926-ae01-c0376f16f478)
Seem like is communicating now.  What is the next step please

**Comment by Ccujar** [comment]
No virtual touch

**Comment by cagnulein** [comment]
in the developer setting there is also a setting to enable a visual area when a touch is made. try to enable it and restart again the script. maybe you are not seeing it but it's doing it

**Comment by Ccujar** [comment]
Ok I found it “show taps” the test you asking me to do is from the qz beta right?

**Comment by cagnulein** [comment]
run first the batch script that i sent you here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14078746/adb-swipe.zip

**Comment by Ccujar** [comment]
Now same as before.  Is the bike have to be in special screen?
![image](https://github.com/cagnulein/qdomyos-zwift/assets/152306115/51a865a3-2b43-49d8-962b-9b6d3a8d5975)

**Comment by cagnulein** [comment]
nope as far as i know, for sure you have to stay in the manual workout window to see the sliders.
What did you change from when it works and when it doesn't?

**Comment by Ccujar** [comment]
Nothing.. just run the link you sent me

**Comment by Ccujar** [comment]
Ill try to reset and let you know as soon as I have the communication with the bike again.  
I really appreciated your time trying to help me with this

**Comment by cagnulein** [comment]
No problem, good luck!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle ore 15:31 Ccujar ***@***.***>
ha scritto:

**Comment by Ccujar** [comment]
I got the communication now.

**Comment by cagnulein** [comment]
ok do you also see the touch event?

**Comment by Ccujar** [comment]
no.  do you thing is a setting on qz that i need to turn on?

**Comment by cagnulein** [comment]
nope, it's not about qz, it's only about your tablet
maybe you can try to change the coordinates in the batch file to check if maybe you're out of the screen?
the first 2 values are the X and Y coordinate

**Comment by Ccujar** [comment]
Where is the batch file?

**Comment by cagnulein** [comment]
always here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14078746/adb-swipe.zip

**Comment by cagnulein** [comment]
first of using qz, use the script and check if you are able to see some
touch event, even if it's random

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle ore 16:05 Ccujar ***@***.***>
ha scritto:

**Comment by Ccujar** [comment]
I’m no sure how to use the script.  Could you please guide me on that?  Thank you

**Comment by cagnulein** [comment]
Just unzip in the installpackage folder and run it
You must see a touch event on the tablet of the bike when you run it. Keep
an eye on it, can be quick

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 17:38 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
Now I’m getting something.  Looks like is touching the 20% inclination button. Bike goes all the way up.  I tried with tiles but nothing yet.

https://github.com/cagnulein/qdomyos-zwift/assets/152306115/0319d75d-3724-46d4-8c9e-6d193f5c4b8a


https://github.com/cagnulein/qdomyos-zwift/assets/152306115/a782f224-061c-444c-8f4e-8767bdc27720

**Comment by cagnulein** [comment]
Ok that's perfect.
So probably you need to shut down the pc (so it disconnects from the bike) and then try with qz

Send me a debug log from qz so I will check if it's doing the right thing

**Comment by Ccujar** [comment]
[debug-Wed_Jan_31_06_02_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14110849/debug-Wed_Jan_31_06_02_42_2024.log)
Good Morning
Looks like the inclination tile now is working (couple seconds of delay but great improvement) resistance doesn’t move at all.
For your reference what I did yesterday to make it work:
is from the computer I selected the “restart QZ companion “ file and after that I start seen activity.
Notice that in order to ADb connection every time  after turning on the bike I have to go to developer settings and turn “off and on” USB debug option then I have expected connectivity.
I have to go to work now but tonight I have some more time to follow your next instructions.

thank you again for your help

**Comment by cagnulein** [comment]
amazing! great step forward! ok so yes for now I was handle only the inclination. I will add the resistance too associated to the zwift erg mode setting in qz and I will also enable the table that you created.
This will require some time. Otherwise we can handle the erg table with the inclination directly (since the inclination changes also the resistance).
In this case you should remap the excel file using the 0.5 step of inclination instead of resistance values.
Are you able to do so in case? (that will be faster since we don't have to remap also the resistance)

**Comment by Ccujar** [comment]
Sure I can do that tonight or tomorrow first thing in the morning.  And I think it make a lot of sense that the inclination is the one who changes as the real scenario when you ride a bike "inclination changes on the street" and manually you can use the resistance bar to mimic the gears on your bike.  
I'll send it over as soon as I have it.  to be in the same page; you need a chart with different cadence / inclination and power output.  right?

Thanks again for your time

**Comment by cagnulein** [comment]
> I'll send it over as soon as I have it. to be in the same page; you need a chart with different cadence / inclination and power output. right?

exactly, right!

**Comment by Ccujar** [comment]
[NORDICTRACK.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/14119425/NORDICTRACK.xlsx)
Here is the file with the inclination chart.  On the first readings I use 5 as a resistance with couple different cadences and in the last one I changed resistance to 10.  It was a little challenging because I couldn't go all the way up to the inclination %. but I hope is enough data to create the pattern.

Thank you

**Comment by cagnulein** [comment]
In the chart I still see the resistance column. Is it an error? I mean we
should replace resistance with inclination. My idea was changing only the
inclination for erg mode

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle 03:21 Ccujar ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
but i don't understand where is the inclination in this table so. for each level of inclination i need a value associated to 3 different cadence value as you already did for the resistance

**Comment by Ccujar** [comment]
[INCLINATION CHART FOR NORDICTRAK S22i.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/14126344/INCLINATION.CHART.FOR.NORDICTRAK.S22i.xlsx)
Here it is.  first column Inclination from 0 to 20 in increments of 0.5  and 3 different cadences with power.  I tried to get as much power in each one but it was a little to hard for my legs.  Hope you can have the information you need

**Comment by cagnulein** [comment]
thanks, I will try to add ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 15:03 Ccujar ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok I did the code. I will send you the new beta on iOS asap.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 15:10 cagnulein ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
Thank you.  Let me know when is available and I run it.  Thanks again.

**Comment by cagnulein** [comment]
@Ccujar 
send me an email to roberto.viola83 at gmail.com indicating this ticket , i can't find your email to send it.
Thanks

**Comment by Ccujar** [comment]
Is there any specific set up I have to do ?

**Comment by cagnulein** [comment]
Yes enable the zwift erg mode setting in the bike settings in qz and give
it a try!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 feb 2024 alle 12:28 Ccujar ***@***.***> ha
scritto:

**Comment by Ccujar** [comment]
I’ll check it out .  I’m at work early this week but at night I’ll try

**Comment by cagnulein** [comment]
@Ccujar any news?
