### ISSUE TITLE
[BUG] Nautilus u626

### ISSUE THREAD

**Issue by Paolopa1967** [cagnulein/qdomyos-zwift#2061]
[**Describe](url
[debug-Sat_Jan_27_23_54_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14074248/debug-Sat_Jan_27_23_54_14_2024.log)
[debug-Sat_Jan_27_23_53_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14074249/debug-Sat_Jan_27_23_53_54_2024.log)
[debug-Sat_Jan_27_23_43_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14074250/debug-Sat_Jan_27_23_43_51_2024.log)
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
yes unfortunately it doesn't have the possibility to change resistance from bluetooth, it's a firmware limitation

**Comment by Paolopa1967** [comment]
Grazie lo stesso per il prezioso lavoro. Va bene così, tutto il resto
funziona

Il Dom 28 Gen 2024, 00:03 Roberto Viola ***@***.***> ha
scritto:
