### ISSUE TITLE
Technogym - Changes Miles to [BUG]

### ISSUE THREAD

**Issue by kevhin18** [cagnulein/qdomyos-zwift#2064]
1.	When I turn on the app, it changes the units on my Technogym MyRun from Miles to Kilometers.  Even though, the app is set to miles.  Can you provide a fix?
[debug-Sun_Jan_28_06_41_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076898/debug-Sun_Jan_28_06_41_13_2024.log)
[debug-Sun_Jan_28_06_43_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076899/debug-Sun_Jan_28_06_43_14_2024.log)
[debug-Sun_Jan_28_06_49_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076900/debug-Sun_Jan_28_06_49_54_2024.log)
[debug-Sun_Jan_28_06_51_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076901/debug-Sun_Jan_28_06_51_18_2024.log)
[debug-Sun_Jan_28_06_59_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076903/debug-Sun_Jan_28_06_59_48_2024.log)
[debug-Sun_Jan_28_08_44_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076904/debug-Sun_Jan_28_08_44_55_2024.log)
[debug-Sun_Jan_28_09_05_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076905/debug-Sun_Jan_28_09_05_18_2024.log)
[debug-Sun_Jan_28_09_18_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14076906/debug-Sun_Jan_28_09_18_51_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle 18:05 kevhin18 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
for me https://github.com/cagnulein/qdomyos-zwift/issues/571

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 gen 2024 alle ore 18:15 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @kevhin18 in order to change the unit I need a hci snoof from you following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using the technogym app so I will check how they control the units on the treadmill (not a standard way, so I have to clone their behaviour)

Let me know

I guess that also @brumohr could be interested on this

**Comment by kevhin18** [comment]
Roberto,

 

I will see if I can figure this out and send you the information.  I don’t think I will have time this week and may need to defer until later next week.

 

Thank you, Kevin

**Comment by cagnulein** [comment]
No rush from me, let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle ore 14:45 kevhin18 ***@***.***>
ha scritto:

**Comment by kevhin18** [comment]
Roberto,

 

Just tried another test by changing the values for each of the Inclination Overrides by a factor of 2 (i.e. 0.5%, 1, 1.0%, 2, etc..) And, it still only changes the inclination by 50% of the Zwift reported incline.  It appears that none of the Inclination Overrides are getting to the Technogym, that is also including changing the values on Inclination Override Gain and Inclination Override Offset.  All have null response.  

 

Next week, I will try to setup my iPad for you to monitor the device.  Maybe, you might figure out the issue in the meantime.

 

Thank you, Kevin

**Comment by cagnulein** [comment]
If you can attach a debug log with the zwift inclination issue I can check it quickly

Thanks

**Comment by kevhin18** [comment]
Roberto,

 

Attached is a 1/2 mile test for you to evaluate.  Inclinations are all 50% of what Zwift is reporting.  And, the Inclination Overrides are not being sent to the Technogym.

 

Thank you, Kevin

**Comment by cagnulein** [comment]
You have to attach them to github otherwise I can't see them

**Comment by kevhin18** [comment]
Roberto,

Attached is a 1/2 mile test for you to evaluate.  Inclinations are all 50% of what Zwift is reporting.  And, the Inclination Overrides are not being sent to the Technogym.

Thank you, Kevin
[debug-Thu_Feb_1_09_29_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14128578/debug-Thu_Feb_1_09_29_00_2024.log)

**Comment by kevhin18** [comment]
Just sent.

 

Thank you, Kevin

**Comment by cagnulein** [comment]
The zwift inclination gain in this log is 1
You have to set it to 2 and press OK
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle 18:12 kevhin18 ***@***.***> ha
scritto:

**Comment by kevhin18** [comment]
Correct.  That is because I have each inclination in the list increased by a factor of 2.  And, I already tried changing the inclination factor from 1 to 2 and IT also did not work.

 

Thank you, Kevin

**Comment by cagnulein** [comment]
The inclination overrides are not meant for this. so please create a debug
log with the zwift inclination gain to 2 and i will check it
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 18:21 kevhin18 ***@***.***>
ha scritto:

**Comment by kevhin18** [comment]
Okay, I am now looking at the debug files.  Here is an older debug file where the "treadmill_inclination_ovveride_gain" QVariant(double, 10), but if you look farther down, the value does not factor through to the "zwift_inclination_gain" QVariant(double, 1) which is still 1.  I think this values should also be 10 and not 1.  Let me know.
[Override-Gain_10.log](https://github.com/cagnulein/qdomyos-zwift/files/14129190/Override-Gain_10.log)

**Comment by cagnulein** [comment]
You have to use this 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/fcaec152-9afc-4c89-b226-72f147938a94)

Only this has effect with auto incline

**Comment by kevhin18** [comment]
Victory!!!  That was the fix.  Inclinations between Zwift and Technogym match.  Looking back on my emails, I see now you were stating to change the Zwift Inclination Gain to 2 and not the Inclination Gain under Treadmill overrides.  Sorry, I missed this.

Now if you can figure out why kilometers is sent to the Technogym when if first connects and not miles, ticket #2064.  It seems that it is right up front in the app commands when connecting to bluetooth that it starts in kilometers before switching to miles, but by then the Technogym has already been switched and it has to be manually switched back before starting the workout.  Anyway, one issue solved for now.  Thank you.

**Comment by cagnulein** [comment]
Glad it worked!
As I said you need to collect a hci snoof log with android and the
technogym app following this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device


Il giorno gio 1 feb 2024 alle 20:34 kevhin18 ***@***.***> ha
scritto:
