### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hobbes121** [cagnulein/qdomyos-zwift#2065]
After upgrading to beta, qz no longer stays connected.  I enter zwift credentials and rebooted.  connected app on note 20 to treadmill, xterra trx3500 and then connected to zwift on my laptop.  pick a route and run and then laptop disconnects.  I tried going in several times and reconnecting but when i start treadmill my avatar doesn't move and then i disconnects.

[debug-Sun_Jan_28_14_01_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077678/debug-Sun_Jan_28_14_01_50_2024.log)
[debug-Sun_Jan_28_13_57_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077677/debug-Sun_Jan_28_13_57_37_2024.log)
[debug-Sun_Jan_28_13_40_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077669/debug-Sun_Jan_28_13_40_03_2024.log)
[debug-Sun_Jan_28_13_48_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077670/debug-Sun_Jan_28_13_48_39_2024.log)
[debug-Sun_Jan_28_13_48_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077671/debug-Sun_Jan_28_13_48_44_2024.log)
[debug-Sun_Jan_28_13_49_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077672/debug-Sun_Jan_28_13_49_08_2024.log)
[debug-Sun_Jan_28_13_53_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14077675/debug-Sun_Jan_28_13_53_52_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
enable the wahoo direct connect setting i n the experimenetal settings and use wahoo device in zwift.
don't change experimental settings because you could have similar issue.
Let me know

**Comment by cagnulein** [comment]
@hobbes121 any news?
