### ISSUE TITLE
Toorx Power Compact S: inclination or speed control works, but not both [BUG]

### ISSUE THREAD

**Issue by bjornju** [cagnulein/qdomyos-zwift#2067]
Attaching log file from QZ.

First run (Jan_29_12_07), the setting of 'Toorx->Toorx FTMS Treadmill' was Off
Second run (Jan_29_12_09),  the setting of 'Toorx->Toorx FTMS Treadmill' was On

Experienced behaviour:
Toorx FTMS Treadmill: Off: Incline control works, but not Speed
Toorx FTMS Treadmill: On: Speed control works, but not Incline

I am unable to make both work simultaneousely.

[debug-Mon_Jan_29_12_07_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14083610/debug-Mon_Jan_29_12_07_23_2024.log)
[debug-Mon_Jan_29_12_07_40_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14083611/debug-Mon_Jan_29_12_07_40_2024.log)
[debug-Mon_Jan_29_12_07_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14083612/debug-Mon_Jan_29_12_07_53_2024.log)
[debug-Mon_Jan_29_12_09_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14083613/debug-Mon_Jan_29_12_09_13_2024.log)
[debug-Mon_Jan_29_12_09_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14083614/debug-Mon_Jan_29_12_09_57_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check during this week. I actually have the flu :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle ore 12:19 Björn Julander <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@bjornju done! it's building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7696313665
in an hour you will see a new apk in this link in the bottom of the page
let me know!
