### ISSUE TITLE
2.16.38 crashes using an Echelon EX 7S bike and Zwift

### ISSUE THREAD

**Issue by vineman70-3** [cagnulein/qdomyos-zwift#2069]
![IMG_1184](https://github.com/cagnulein/qdomyos-zwift/assets/157830113/75315c8d-3c9d-4f82-b446-c80797b1bdf7)
![IMG_1185](https://github.com/cagnulein/qdomyos-zwift/assets/157830113/b585e8a0-bd9e-4912-b836-2c74f72f40ec)
![IMG_1186](https://github.com/cagnulein/qdomyos-zwift/assets/157830113/ec2fc623-fb2d-4e91-a5fa-716dc03a18fe)
On 240127 I tried to use QZ 2.16.38 on an iPad pro and Zwift on another iPad Pro. I had no problem with the same configuration with 2.15.4. I tried both this bike and a Lfefitness treadmill with a treadmill profile. On 240127 I was going back and forth between the Echelon app & Zwift. There was no problem with the Echelon app. I shut it down completely prior to trying Zwift. I attach a zip file of everything in the files folder from that day bud because of going back & forth between Zwift & Echelon not sure what is in here. I tried again today 240129 only going on the bike and only using 2.16.38. It worked with the Echelon app but Zwift crashed as usual within less than a minute. I attach a zip file from today, but there is no log file. I got an email attached but that appears to be from when I used the Echelon and not the Zwift app. I am obviously not good at this, but I do know what I am doing wrong. I do appreciate your help. I could not start the QZ app clicking "start" and had to use the + in speed to get watts to show & get Zwift avatar to move before the QZ app crash. Taping the "start" button did not do anything. Heart rate showed but only that. Cadence never showed in the QZ app. I had to get quoting both the QZ app & Zwift to get anything going. Only worked by 1st increasing the speed with the + speed button, watts showed, then open Zwift, & the avatar moved & < 1min the QZ app crashed. No information appears in my Zwift account in "My Feed". I put the 2.15.4 QZ app on a separate device (an iPad) so I could compare what was happening. Probably changing too many parameters.
[27.zip](https://github.com/cagnulein/qdomyos-zwift/files/14087517/27.zip)
[240129.zip](https://github.com/cagnulein/qdomyos-zwift/files/14087519/240129.zip)
<img width="1313" alt="email_Screenshot 2024-01-29 at 12 09 26 PM" src="https://github.com/cagnulein/qdomyos-zwift/assets/157830113/08b53ab8-2f4a-42b1-83d5-0a55d1d04d29">
![IMG_1181](https://github.com/cagnulein/qdomyos-zwift/assets/157830113/e60cbf0e-64ef-4f7f-a2b1-ab1afb56aa84)

**Comment by vineman70-3** [comment]
Thank you so much for taking so much time to try to help.

The QZ app crashes first and shuts down on the iPad. Then because there is nothing going to Zwift it stops & I try to save but there is nothing there. It is always the QZ app that crashes.

I have my HR in the HR options and the bike is definitely in manually in advanced setting. I just took a screen shot on the iPad & will try to attach it to this email. I have multiple times refreshed the device list and made sure the ECHEX-7s-100974 is there.

I do not know anything about the debug log setting or where to set it.

￼

**Comment by cagnulein** [comment]
remember that you have to attach any attachment on the ticket on github https://github.com/cagnulein/qdomyos-zwift/issues/2069 otherwise I can't see it.
The debug log is under the experimental settings, you already enable it once since you already sent me a debug log.
I'm quite sure that the problem is about the manual device, so if you can send me a debug log I can check this for sure!
Let me know

**Comment by vineman70-3** [comment]
The debug log was off. I will attempt to get back to the gym and try again this afternoon or more likely tomorrow morning.
 How can I attach an attachment to the existing ticket or do I need to start a new ticket?

**Comment by cagnulein** [comment]
simply go into the url that it's attached on every email at the bottom and
drop the file on the comment box
can you show me in the meanwhile the manual device setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle 19:29 vineman70-3 ***@***.***>
ha scritto:

> The debug log was off. I will attempt to get back to the gym and try again
> this afternoon or more likely tomorrow morning.
> How can I attach an attachment to the existing ticket or do I need to
> start a new ticket?

**Comment by vineman70-3** [comment]
I could see where there was a comment box. I tried to add 3 screenshots by editing #2069 2 of the experimental features & 1 of the manual device

**Comment by cagnulein** [comment]
ok perfect the manual device seems ok
be sure that is set when you will try again

**Comment by cagnulein** [comment]
#2075
