### ISSUE TITLE
[REQ] Apple Watch - Switch Device is too easy to accidentally hit in UI

### ISSUE THREAD

**Issue by Brodie01** [cagnulein/qdomyos-zwift#2070]
**Is your feature request related to a problem? Please describe.**
On the Apple Watch app, the "scrolling menu" for activity (Bike, running, row) is too easy to hit by accident, it has happened a few times that I switch the activity without noticing and then start my biking workout and not everything is logged properly.

**Describe the solution you'd like**
Adding a second "page" or different control that allows users to not have to more purposefully change the activity would be great. If you move it to a second page or swipe right action, then adding a simple label on the main screen for "Activity" would help the user identify which one is currently selected without swiping.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No added context.

**Comment by cagnulein** [comment]
yes sure it makes sense!
I will do this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle ore 18:53 Brodie01 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
my idea is to start and stop and get the activity type automatically. Actually I already did this in the #1580

**Comment by cagnulein** [comment]
i didn't deploy this yet, just did the code :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 gen 2024 alle 19:18 Brodie01 ***@***.***> ha
scritto:
