### ISSUE TITLE
[REQ] Allow "Minimum Resistance" setting to be changed during workout

### ISSUE THREAD

**Issue by Brodie01** [cagnulein/qdomyos-zwift#2071]
**Is your feature request related to a problem? Please describe.**
For Bike rides, I use the minimum resistance setting to not let my bike drop below a certain amount. When my legs get warmed up, I'd like to be able to increase that a little. Ex. for my echelon I have it start at a min of 18 resistance which is good for the warm up, but as I get into my peloton class, I'd like to tell the app to not let the bike drop below 20 or 22. 

**Describe the solution you'd like**
A tile with a + / - switch such as gears would be greatly appreciated. Display the current minimum and then allow the user to add or subtract from it in real time for the rest of the ride.

**Describe alternatives you've considered**
Utilizing gears down not work properly for this. If the target resistance for AR is way lower than my minimum (the class is calling for 14 but my bike is set to 18 min, then the gear up only takes into account the 14 when doing its calc and won't increase the minimum.  Also, sometimes the max resistance for the interval I'm doing it perfect and I don't want it geared up for that section.

**Additional context**

**Comment by cagnulein** [comment]
You know that you can do this already with the "Min. Resistance:" setting? you can change it in real time without rebooting qz
