### ISSUE TITLE
Won’t allow me to set a new flat road setting in zwift

### ISSUE THREAD

**Issue by Npaterso** [cagnulein/qdomyos-zwift#2072]
**Describe the bug**

My ftms smart bike keeps dropping the flat rate speed down to 1 or 2 as the normal flat rate setting even though I have set it to 25. 

I took a debug of both hooking up as the wahoo connection, then halfway changed it to my iPhone connection. Also, if in the wahoo connection it won’t detect my bike when trying to calibrate the spin down

**To Reproduce**

I would start the ride and it would normally amp up to a certain level if on a hill, then drop down to 1 once the include goes back to 0% or under. 

**Expected behavior**
I would expect the speed to drop to the set level and not below it… not sure what’s happening

**Screenshots**

**Desktop (please complete the following information):**
 Using IOS for QZ and brand new ipad for zwift

**Smartphone (please complete the following information):**
 - Device: iPhone 11 and iPad 10
 - 
**Append a debug log**

[debug-Mon_Jan_29_21_05_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14092046/debug-Mon_Jan_29_21_05_27_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context

bike is ascend S2 ftms Bluetooth magnetic spin bike - connects with no issue to zwift but the auto resistance is not working properly

**Comment by Npaterso** [comment]
Hi Roberto,

It works!! Amazing thank you so much for what you’ve done and helping me through this!!!

Neil Paterson
(807) 629 7769
***@***.***

On Jan 30, 2024, at 3:53 AM, Roberto Viola ***@***.***> wrote:

﻿

hi @Npaterso<https://github.com/Npaterso> your bike is ftms compatible, this means that when zwift asks for a inclination to qz, i'm routing directly to the bike adding the gear mod. So in order to set a new flat road value., just use the gear tile in qz. enable it from the tiles settings and then push the plus button to find your preferred value.
You can also choose to restore this value on the startup of qz in the advanced settings

Let me know if you have any questions!

**Comment by cagnulein** [comment]
That's great @Npaterso! Remember to rate the app on the store, it means a lot to me! Thanks!
