### ISSUE TITLE
NoblePro Cadence Data

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2073]
[debug-Tue_Jan_30_08_25_37_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14096387/debug-Tue_Jan_30_08_25_37_2024.zip)

this treadmill has also a {00001814-0000-1000-8000-00805f9b34fb} cadence/speed standard char, so i can use this

This is originally posted from Stuart

**Comment by Middy2000** [comment]
Cadence pairs as wahoo tread but app is not receiving data.
Cannot pair cadence direct to Zwift when QZ is in use as NoblePro Connect does not show. I guess treadmill cannot pair to two devices?

All other data is being received by app, Speed & HR but no cadence.

Thanks

**Comment by cagnulein** [comment]
Yes got it, there is a fix for this :)
I just need to find the time to develop it :)
Stay tuned!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle ore 11:58 Middy2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done @Middy2000 it will be in the next one (2.16.41 and above)

**Comment by Middy2000** [comment]
Great. Thanks R.


Sent from Samsung Mobile on Vodafone
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
qz is reporting exaclty the value reported from the treadmill. so probably i should instead averaging it as you mentioned. I'm doing it, it should be easy to do

**Comment by Middy2000** [comment]
Hi R.

I forgot to update the app before my run.  I've just updated it so tomorrow I can give you an update.

Cheers

Sent from Samsung Mobile on Vodafone
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
No worries, thanks for the update!


Il giorno mer 14 feb 2024 alle 11:13 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Hi R. 

No change in cadence reporting the live data on screen is still changing several times a second.

Also today my average cadence was around 20 lower than normal.

![Screenshot_20240215_100640_Companion](https://github.com/cagnulein/qdomyos-zwift/assets/119119816/d28692f9-135c-423c-bc9b-0b0e4d56b362)

**Comment by cagnulein** [comment]
Do you have the debug log?

**Comment by Middy2000** [comment]
No. I turned it off to save space! 🤦

I'll turn it on for tomorrow!

Sent from Samsung Mobile on Vodafone
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Middy2000** [comment]
My mistake. It was turned on.

Here are the logs. Before and after update.
[After.zip](https://github.com/cagnulein/qdomyos-zwift/files/14295634/After.zip)
[Before.zip](https://github.com/cagnulein/qdomyos-zwift/files/14295641/Before.zip)

**Comment by cagnulein** [comment]
ok the patch worked but the cadence it's more floating than I thought. Let's use ChatGPT to identify the best average value for this. I will report back

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/5d43eba6-a32d-44aa-83c2-74ca50911da8)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/2c44fdf6-1f04-4d2e-aa68-736d0f988f9e)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/24a5333a-1fc7-4483-af74-c7b63ee37855)

what do you think @Middy2000 ?
20 seconds could be right? or even 10?

**Comment by Middy2000** [comment]
I’m personally happy with 20 seconds. I run at a regular pace throughout my run so I don’t need to see constant changes in cadence.

**Comment by cagnulein** [comment]
👍 i will push it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 13:09 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Hi Roberto.

Tested the new version today with 20 second polling.

The cadence line is a bit flatter but for some reason the average cadence is still 20 lower than actual cadence.

![Uploading Screenshot_20240221_160154_Companion.jpg…]()

**Comment by cagnulein** [comment]
i don't see the image, you have to wait the finish of the upload

**Comment by cagnulein** [comment]
also is the real time cadence right on qz? or even that one is wrong?

**Comment by Middy2000** [comment]
Real time cadence is also wrong. It is better than before but still not correct.

![Screenshot_20240221_160154_Companion](https://github.com/cagnulein/qdomyos-zwift/assets/119119816/0f761c63-1b13-4322-8eee-36c3d96961ff)

**Comment by cagnulein** [comment]
that's strange. do you have also the log from today?

**Comment by Middy2000** [comment]
Of course.

[Cadence 20 seconds.zip](https://github.com/cagnulein/qdomyos-zwift/files/14362248/Cadence.20.seconds.zip)

**Comment by cagnulein** [comment]
ok i guess that i understood why it's lower. I had a filter before adding
the average. So now in the next one should be right
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle ore 19:14 cagnulein ***@***.***> ha
scritto:

**Comment by Middy2000** [comment]
3rd time lucky then.

**Comment by Middy2000** [comment]
Hi R. 

Latest update.

![Screenshot_20240228_100037_Companion](https://github.com/cagnulein/qdomyos-zwift/assets/119119816/a6bba0c2-c83b-41c4-86b5-f2a21f6eefac)
[debug-Wed_Feb_28_08_37_47_2024 (1).zip](https://github.com/cagnulein/qdomyos-zwift/files/14432023/debug-Wed_Feb_28_08_37_47_2024.1.zip)

**Comment by cagnulein** [comment]
ok i will try to implement the other bluetooth characteristic tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 feb 2024 alle ore 11:03 Middy2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok @Middy2000 i handled the rsc characteristic along with the fitshow one. Let's see if the treadmill can handle this and if i ddin't anything wrong (i changed a lot of things and I can't try anything so good luck :) ).

**Comment by Middy2000** [comment]
Ok, so am I trying to pair QZ to speed and the cadence direct from the treadmill to Zwift?

**Comment by cagnulein** [comment]
You could this already
What I did now is collecting speed and cadence from qz and so sending both
to zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 feb 2024 alle 11:29 Middy2000 ***@***.***>
ha scritto:
