### ISSUE TITLE
[Yesoul g1max resistance tile not showing reading

### ISSUE THREAD

**Issue by wassa22** [cagnulein/qdomyos-zwift#2074]
Connecting to ipad running ios 17.0.3 on a Yesoul G1 max

Resistance tile not showing the resistance level from the bike.

Resistance is showing on the companion app and also the Peleton Resistance tile is showing a figure which is 3 times what the bike is showing.

Cadence and power coming through fine

[inbound526499595351214655.txt](https://github.com
[inbound146460411083016312.txt](https://github.com/cagnulein/qdomyos-zwift/files/14097832/inbound146460411083016312.txt)
/cagnulein/qdomyos-zwift/files/14097825/inbound526499595351214655.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Got the point, it's because I'm using the same Nordic track profile. Do you
have a peloton conversion chart for your bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 13:41 wassa22 ***@***.***> ha
scritto:

**Comment by wassa22** [comment]
No I havent seen a conversion chart for the bike....I am not looking to use Peleton App was more just wanting to see the bikes resistance for adjusting in zwift etc running up inclines. If I know the peleton tile is multiplying by three I can base it off that

**Comment by cagnulein** [comment]
Why don't you turn off the peloton resistance tile and don't you use the
resistance tile directly? With also the target resistance tile? (Coming
from zwift)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 14:21 wassa22 ***@***.***> ha
scritto:

**Comment by wassa22** [comment]
Thats the problem....the resistance tile isnt working and is displaying 0.

**Comment by wassa22** [comment]
![inbound5429682022158843193](https://github.com/cagnulein/qdomyos-zwift/assets/157265595/b5d6e5fb-cc85-4c34-83a0-7f603fcebab3)

As shown in the email as well....no figures for resistance....only peleton resistance

**Comment by cagnulein** [comment]
Got the issue, you need the beta of qz for that. Send me an email to
Roberto.viola83 at Gmail.com indicating this ticket and I will send you it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 gen 2024 alle 14:31 wassa22 ***@***.***> ha
scritto:

**Comment by wassa22** [comment]
Brilliant that did the trick......

Thank you.

**Comment by cagnulein** [comment]
amazing!
