### ISSUE TITLE
[BUG] pro-form proshox2

### ISSUE THREAD

**Issue by daveadavidson** [cagnulein/qdomyos-zwift#2078]
**Describe the bug**

**To Reproduce**
No listing of model
1, not able to adjust speed or incline with tiles
2, not able to get automatic changes with gpx data
![screenshot-2024-01-31-13-45-21-default](https://github.com/cagnulein/qdomyos-zwift/assets/158297397/593f3852-1b9b-4a05-9341-cff9ec0b28a1)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi! i don't see the bug report with the hci snoop file

**Comment by daveadavidson** [comment]
This might be it

**Comment by daveadavidson** [comment]
[]https://www.dropbox.com/scl/fi/38lula47wuuvgzrtxe473/bugreport-panther_beta-AP11.231215.009-2024-01-31-13-45-22.txt?rlkey=wtoyihjd7i0mgi4xae8xbn6nk&dl=0(url)

**Comment by cagnulein** [comment]
Hi unfortunately I need the HCI snoof file. Don't you have in the bug
report? did you enable it in the dev settings?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 15:27 daveadavidson <
***@***.***> ha scritto:

**Comment by daveadavidson** [comment]
Yeah I enabled it and I had a notification of a screen shot. Look d in the
bugreport folder and found this file >
https://www.dropbox.com/scl/fi/38lula47wuuvgzrtxe473/bugreport-panther_beta-AP11.231215.009-2024-01-31-13-45-22.txt?rlkey=wtoyihjd7i0mgi4xae8xbn6nk&dl=0


95mb
Will have another go soon and see if the phone kicks out another file

Dave

**Comment by cagnulein** [comment]
try also to don't toggle the hci snoof setting (leaving always enabled).
some androids act differently

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 15:35 daveadavidson <
***@***.***> ha scritto:

> Yeah I enabled it and I had a notification of a screen shot. Look d in the
> bugreport folder and found this file >
>
> https://www.dropbox.com/scl/fi/38lula47wuuvgzrtxe473/bugreport-panther_beta-AP11.231215.009-2024-01-31-13-45-22.txt?rlkey=wtoyihjd7i0mgi4xae8xbn6nk&dl=0
>
>
> 95mb
> Will have another go soon and see if the phone kicks out another file
>
> Dave
>

**Comment by daveadavidson** [comment]
Ok will do

**Comment by daveadavidson** [comment]
[https://drive.google.com/file/d/168yH_NloIROhpbOwVGRvQvLhYjQ5poS8/view?usp=drivesdk](url)

**Comment by daveadavidson** [comment]
https://drive.google.com/file/d/168yH_NloIROhpbOwVGRvQvLhYjQ5poS8/view?usp=drivesdk

**Comment by daveadavidson** [comment]
Should be able to access it now

**Comment by cagnulein** [comment]
[btsnoop_hci - 1.zip](https://github.com/cagnulein/qdomyos-zwift/files/14113294/btsnoop_hci.-.1.zip)
perfect this the file. i'm checking it now

**Comment by daveadavidson** [comment]
And we got there in the end lol, probably isn't even the right data needed
lol

**Comment by cagnulein** [comment]
mmm yes unfortunately there is no data here. just to te sure: were you running ifit on this android device changing speed and inclination from this android device?

**Comment by daveadavidson** [comment]
Yes I used ifit and changed the speed using the treadmill buttons and then
ended the ifit run and pressed bug report. Will have another go and play
for 2mins and see if that helps

**Comment by cagnulein** [comment]
mmm i don't see any communication at all with the treadmill in this...
very strange

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 16:15 daveadavidson <
***@***.***> ha scritto:

> Yes I used ifit and changed the speed using the treadmill buttons and then
> ended the ifit run and pressed bug report. Will have another go and play
> for 2mins and see if that helps
>
>

**Comment by daveadavidson** [comment]
https://drive.google.com/file/d/16DpNRdnyjopnyCjm9KAJKglehCmbnUo9/view?usp=drivesdk


Try that one please

**Comment by cagnulein** [comment]
permission requested

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 16:23 daveadavidson <
***@***.***> ha scritto:

>
> https://drive.google.com/file/d/16DpNRdnyjopnyCjm9KAJKglehCmbnUo9/view?usp=drivesdk
>
>
> Try that one please
>

**Comment by cagnulein** [comment]
same thing, it seems that it's crypted or similar. never saw something similar. Do you have another android device? even an old one?

**Comment by daveadavidson** [comment]
I shall have a look for a tablet. Bloody typical lol

**Comment by cagnulein** [comment]
lol let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle ore 16:37 daveadavidson <
***@***.***> ha scritto:

> I shall have a look for a tablet. Bloody typical lol
>

**Comment by daveadavidson** [comment]
https://drive.google.com/file/d/16LlCKK0lRh-mEA46Dj4coffaxGcOhaUI/view?usp=drivesdk

**Comment by cagnulein** [comment]
im heading home, i will check it tomorrow!

**Comment by daveadavidson** [comment]
Ok mate, fingers crossed.
Have a good night mate and thanks again for all your help.
Oh one tiny request, when it exports the activity to Strava it does it as a
walk, is there a way to do it as a run by default??

Thanks
Dave

**Comment by cagnulein** [comment]
if the average speed is lower than 7km/h is tagged automatically as a walk
on qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle 17:31 daveadavidson ***@***.***>
ha scritto:

> Ok mate, fingers crossed.
> Have a good night mate and thanks again for all your help.
> Oh one tiny request, when it exports the activity to Strava it does it as
> a
> walk, is there a way to do it as a run by default??
>
> Thanks
> Dave
>

**Comment by cagnulein** [comment]
this one seems better but i can't see any communication with the treadmill. i see a versa communication (what is it? a watch?) but no treadmill. are you sure ifit was running here?

**Comment by daveadavidson** [comment]
Hi yes the versa is the wife's watch and yes ifit was running on the phone
and I was using it to adjust the treadmill. Strange as that isn't showing
up. Dear me lol. I shall see if I can dig out an old tablet

**Comment by cagnulein** [comment]
on some android the hci snoof must be enabled before rebooting the device,
on other it must be enabled on the same session. some device doesn't
require the reboot at all. you should play with this :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 14:52 daveadavidson <
***@***.***> ha scritto:

> Hi yes the versa is the wife's watch and yes ifit was running on the phone
> and I was using it to adjust the treadmill. Strange as that isn't showing
> up. Dear me lol. I shall see if I can dig out an old tablet
>

**Comment by daveadavidson** [comment]
I shall try that also, currently charging a device from the 1980s. It isn't
but I bet it's as slow as if it was. Stay tuned

**Comment by daveadavidson** [comment]
hi
i am still trying to get this old tablet to work, Will try again with the
wifes phone again later today and see if it will see the app and mill.
we will get there in the end ;)

have a good day
dave

**Comment by cagnulein** [comment]
for sure! I never lost a battle!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle ore 08:40 daveadavidson <
***@***.***> ha scritto:

> hi
> i am still trying to get this old tablet to work, Will try again with the
> wifes phone again later today and see if it will see the app and mill.
> we will get there in the end ;)
>
> have a good day
> dave
>

**Comment by cagnulein** [comment]
@daveadavidson any news?

**Comment by daveadavidson** [comment]
No not yet, will try again this afternoon.

**Comment by cagnulein** [comment]
@daveadavidson any news?

**Comment by daveadavidson** [comment]
Hi mate,
I can't get any other android device to work. Too old so stuck with the
ones I tried before and didn't work. So stumped until I can borrow another.
Have iPads and MacBooks but not android ;/

**Comment by cagnulein** [comment]
hi @daveadavidson maybe we can do with the macbooks. Is it a silicon one?

**Comment by daveadavidson** [comment]
It's a new M3 one

**Comment by cagnulein** [comment]
ok so try to install the proform app from apple store on your mac, if it works there use wireshark on mac to collect it

To use Wireshark on a Mac for network sniffing and saving the captured data:

1. **Install Wireshark**: Download it from the official website (wireshark.org) and install.

2. **Open Wireshark**: Launch the application.

3. **Select Network Interface**: On the start screen, choose the network interface for traffic capture.

4. **Start Capturing**: Double-click the selected interface to begin capturing.

5. **Stop Capturing**: Click the stop button in the toolbar to end the capture.

6. **Save the Capture**: Navigate to "File" > "Save As", select your save location and file name, then click "Save".

**Comment by daveadavidson** [comment]
Ok shall try that I. The morning after my run. Fingers crossed lol

**Comment by daveadavidson** [comment]
dear me
the proform app doesnt want to play with me unless i sign up for the year.
I shall look for another alternative. Pleased i enjoy running outside lol

will shout once i have found a way

Have a good day mate

Dave

**Comment by cagnulein** [comment]
Even with the trial period?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 09:10 daveadavidson ***@***.***>
ha scritto:

> dear me
> the proform app doesnt want to play with me unless i sign up for the year.
> I shall look for another alternative. Pleased i enjoy running outside lol
>
> will shout once i have found a way
>
> Have a good day mate
>
> Dave
>

**Comment by daveadavidson** [comment]
The trial just vanished and left me with 2 paying options when I dug in to
actually use it. Proform and ifit suck big time dammm them. I love zwift
though

**Comment by cagnulein** [comment]
Ok in case create a second account with another email, I guess you can
achieve it  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 09:40 daveadavidson ***@***.***>
ha scritto:

> The trial just vanished and left me with 2 paying options when I dug in to
> actually use it. Proform and ifit suck big time dammm them. I love zwift
> though
>

**Comment by daveadavidson** [comment]
ok i knew something was off, the proform app you said install isnt actually
anything to do with proform hence why i couldnt find stuff lol. iffit
doesnt run on the macbook pro and. I cant install wireshark on the ipad. I
shall give it another go with the phone to see if that will do it any
better than before lol

give me 10mins

**Comment by cagnulein** [comment]
Ok in case maybe you can have access to android device :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 09:51 daveadavidson ***@***.***>
ha scritto:

> ok i knew something was off, the proform app you said install isnt
> actually
> anything to do with proform hence why i couldnt find stuff lol. iffit
> doesnt run on the macbook pro and. I cant install wireshark on the ipad. I
> shall give it another go with the phone to see if that will do it any
> better than before lol
>
> give me 10mins
>
>
> On Sun, 10 Mar 2024 at 08:41, Roberto Viola ***@***.***>
> wrote:
>
> > Ok in case create a second account with another email, I guess you can
> > achieve it :)
> >
> > Roberto Viola
> > Software engineer and open source enthusiast
> > http://robertoviola.cloud
> >
> >
> >
> > Il giorno dom 10 mar 2024 alle 09:40 daveadavidson ***@***.***>
> > ha scritto:
> >
> > > The trial just vanished and left me with 2 paying options when I dug
> in
> > to
> > > actually use it. Proform and ifit suck big time dammm them. I love
> zwift
> > > though
> > >

**Comment by daveadavidson** [comment]
https://www.dropbox.com/scl/fi/3xv12woaaj37fqxn3gpzv/bugreport-panther_beta-AP21.240216.010-2024-03-10-09-04-29.zip?rlkey=ikfni5exr93myshvsxi431565&dl=0

**Comment by cagnulein** [comment]
perfect! i will check it asap!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle ore 16:45 daveadavidson <
***@***.***> ha scritto:

>
> https://www.dropbox.com/scl/fi/3xv12woaaj37fqxn3gpzv/bugreport-panther_beta-AP21.240216.010-2024-03-10-09-04-29.zip?rlkey=ikfni5exr93myshvsxi431565&dl=0
>

**Comment by daveadavidson** [comment]
Fingers crossed lol

**Comment by daveadavidson** [comment]
Ahhh I'm going mad but is there a direct link to what I need to install.
Sorry head a bit fluffy today.
And oh the zip file work today as that was from my pixel 7 same as before
lol

Dave

**Comment by cagnulein** [comment]
Here https://github.com/cagnulein/qdomyos-zwift/actions/runs/8230892129/artifacts/1314466209

**Comment by daveadavidson** [comment]
404 :/

**Comment by cagnulein** [comment]
You need to be login on GitHub first

**Comment by daveadavidson** [comment]
Ok selected the module from the list and the app sees my treadmill but
hitting the +- doesn't do anything on the app or my treadmill. Sorry mate.
I can see it change if I do it on the treadmill itself but not using the
app buttons

**Comment by daveadavidson** [comment]
Ok be be shortly

**Comment by daveadavidson** [comment]
https://www.dropbox.com/scl/fi/knyrp64q1hacnsp7t4v8a/bugreport-panther_beta-AP21.240216.010-2024-03-11-13-26-25.zip?rlkey=4tfqryp6ie1mv198ioure3yzd&dl=0

**Comment by cagnulein** [comment]
not a bug report, a debug log from qz as i described above. thanks

**Comment by cagnulein** [comment]
@daveadavidson any news?

**Comment by daveadavidson** [comment]
Irhe last thing was me sending the screenshot to you, which I did so I was
waiting lol

**Comment by cagnulein** [comment]
@daveadavidson the last action that i see here is my question https://github.com/cagnulein/qdomyos-zwift/issues/2078#issuecomment-1988460820

am I missing something?

**Comment by cagnulein** [comment]
@daveadavidson any news?

**Comment by daveadavidson** [comment]
I'm confused to where we are now as last thing I sent was a screenshot of
the bug as requested, but not sure where we are now.

**Comment by cagnulein** [comment]
> not a bug report, a debug log from qz as i described above. thanks

This is the last thing that I asked. Are you able to provide it?

**Comment by daveadavidson** [comment]
Ok I shall do it when I get back in. Shouldn't be long
Dave
