### ISSUE TITLE
[BUG] Rower Pace is not stable

### ISSUE THREAD

**Issue by dchintan1** [cagnulein/qdomyos-zwift#2079]
Hi Roberto, 

Attached are my debug files from my last rowing class. My Pace is not stable at all. The only somewhat stable reading I get is at 30+ stroke rate below 2 sec  m/500m reading.. Other than that most of the time the rower pace tile remains blank(out of range). 

[debug-Tue_Jan_30_18_40_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14114490/debug-Tue_Jan_30_18_40_08_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Ok I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 gen 2024 alle 17:37 dchintan1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi for the #1875 I already patched this i guess. I would like to send the newest version to you too. 
send me an email to roberto.viola83 at gmail.com indicating this ticket . Thanks

**Comment by dchintan1** [comment]
> hi for the #1875 I already patched this i guess. I would like to send the newest version to you too. send me an email to roberto.viola83 at gmail.com indicating this ticket . Thanks

Done!

**Comment by dchintan1** [comment]
Hi Roberto, 

The new patch works!! The pace is in the range now.. Thank you!!! :D 

I noticed one more bug last evening though. The timing is out of sync with the Peloton classes. I pressed the start button when the actual peloton class was at 0 as usual. Not sure if anyone else also noticed this..

**Comment by cagnulein** [comment]
Do you have a debug log of this? Out of sync of how many seconds?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle 16:39 dchintan1 ***@***.***> ha
scritto:

**Comment by dchintan1** [comment]
[debug-Thu_Feb_1_18_20_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14144763/debug-Thu_Feb_1_18_20_43_2024.log)
[debug-Thu_Feb_1_09_20_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14144764/debug-Thu_Feb_1_09_20_20_2024.log)
 
Here are the debug files from yesterday. I tried to count once and its more than 40 seconds behind.

**Comment by cagnulein** [comment]
ok i will check it there is something wrong. in the meantime you can use
the peloton offset to trim it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle 20:56 dchintan1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
these are not logs from workouts unfortunately, do you have others?
Anyway I suggest to disable the OCR autosync feature, I guess this could be
the reason of non sync .
Anyway if you can upload a complete log I can check this for sure!
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle ore 20:57 cagnulein ***@***.***> ha
scritto:

**Comment by dchintan1** [comment]
I can’t find QCR auto sync in the settings. Could you please tell me where
is it? To give you more idea, this is the screen shot of 20 mins class when
it ended. Also, I don’t think the class is out of sync so many seconds from
the beginning. It gradually increases!

**Comment by cagnulein** [comment]
i don't see the photos, you have to attach to github directly 

i'm talking about these ones
put both of them to disable 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/0ee305ba-a86e-47b1-9d21-4bd1b1043c04)

**Comment by dchintan1** [comment]
Ok I disabled them. Will keep you updated. Thank you!

**Comment by dchintan1** [comment]
Hi Roberto, 

I think I found out why the class is out of sync. Here are my debug logs from yesterday's class. Whenever I rack the handle for water or towel during the class, all readings on the QZ go zero. Even the class timer goes zero and I think it starts adding these seconds to the class timer. Let me see if you see something similar on these debug logs. 


[debug-Mon_Feb_5_18_45_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14184500/debug-Mon_Feb_5_18_45_12_2024.log)
[debug-Mon_Feb_5_18_46_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14184502/debug-Mon_Feb_5_18_46_26_2024.log)
[debug-Mon_Feb_5_18_47_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14184503/debug-Mon_Feb_5_18_47_32_2024.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out tomorrow


Il giorno mar 6 feb 2024 alle 19:14 dchintan1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@dchintan1 I guess your issue it's just about the "continuous_moving" (under general setting) setting that it's disabled.

By default, when the continuous_moving is disabled, qz is pausing the workout when the speed is 0.

Enable that setting and I guess you will fix your issue

Let me know

**Comment by dchintan1** [comment]
> @dchintan1 I guess your issue it's just about the "continuous_moving" (under general setting) setting that it's disabled.
> 
> By default, when the continuous_moving is disabled, qz is pausing the workout when the speed is 0.
> 
> Enable that setting and I guess you will fix your issue
> 
> Let me know

Okay! I will test this today evening and let you know. Thank you!

**Comment by dchintan1** [comment]
> @dchintan1 I guess your issue it's just about the "continuous_moving" (under general setting) setting that it's disabled.
> 
> By default, when the continuous_moving is disabled, qz is pausing the workout when the speed is 0.
> 
> Enable that setting and I guess you will fix your issue
> 
> Let me know

THIS was the solution, Roberto. It worked perfectly yesterday without any lag! Thank you!! :D

**Comment by cagnulein** [comment]
amazing!
