### ISSUE TITLE
[BUG] connecting to other household devices

### ISSUE THREAD

**Issue by Troy-McC1ure** [cagnulein/qdomyos-zwift#2080]
**Describe the bug**
I have not been able to get qz to connect to my gen 1 TDF.  Usually I get no connection or it will connect to other devices in my house like my sound machine.

**To Reproduce**
1. Open app and added IP address to tdf1 field
2. Checked tdf1 toggle
3. Restart
4. Connects to hatch rest

**Smartphone (please complete the following information):**
 - Device: pixel 7
 - OS: Android
 - Version 14
 
Debug
[debug-Wed_Jan_31_12_32_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14115290/debug-Wed_Jan_31_12_32_00_2024.log)

**Comment by cagnulein** [comment]
Actually it's connected don't mind about the label on top, that one is about Bluetooth. Your bike has wifi. Did you try to ride? Do you see the metrics?

The original post is this one https://github.com/cagnulein/qdomyos-zwift/issues/1825

Comment there so also the other owner of the tdf1 can help you!
