### ISSUE TITLE
[REQ] Adding support for NordicTrack X22i (wifi) on Raspberry PI 

### ISSUE THREAD

**Issue by amasolov** [cagnulein/qdomyos-zwift#2084]
**Is your feature request related to a problem? Please describe.**

I couldn't find command line parameters for connecting to my NordicTrack X22i in the same as way as I do on my iOS/android devices. What is the correct procedure?

**Comment by cagnulein** [comment]
are you running it with the UI?
there is not a command line arguments for this. You can add it easily if
you want

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 10:58 Alexey Masolov <
***@***.***> ha scritto:

**Comment by amasolov** [comment]
@cagnulein The UI with -noqml option doesn't give me any settings either. Treadmill Connection Status and Zwift Connection Status are greyed out

**Comment by cagnulein** [comment]
use the -qml instead
-noqml is out of date

**Comment by cagnulein** [comment]
did you install the qml modules?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 11:13 Alexey Masolov <
***@***.***> ha scritto:

**Comment by amasolov** [comment]
amasolov@raspberrypi:~ $ sudo su -
root@raspberrypi:~# apt install git libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-assistant libqt5networkauth5-dev libqt5websockets5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5 qtlocation5-dev qtquickcontrols2-5-dev libqt5texttospeech5-dev libqt5texttospeech5 g++ make

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

git is already the newest version (1:2.39.2-1.1).

libqt5bluetooth5 is already the newest version (5.15.8-2).

libqt5widgets5 is already the newest version (5.15.8+dfsg-11).

libqt5positioning5 is already the newest version (5.15.8+dfsg-3+deb12u1).

libqt5xml5 is already the newest version (5.15.8+dfsg-11).

qtconnectivity5-dev is already the newest version (5.15.8-2).

qtpositioning5-dev is already the newest version (5.15.8+dfsg-3+deb12u1).

libqt5charts5-dev is already the newest version (5.15.8-2).

libqt5charts5 is already the newest version (5.15.8-2).

qt5-assistant is already the newest version (5.15.8-2).

libqt5networkauth5-dev is already the newest version (5.15.8-2).

libqt5websockets5-dev is already the newest version (5.15.8-2).

qtmultimedia5-dev is already the newest version (5.15.8-2).

libqt5multimediawidgets5 is already the newest version (5.15.8-2).

libqt5multimedia5-plugins is already the newest version (5.15.8-2).

libqt5multimedia5 is already the newest version (5.15.8-2).

qtlocation5-dev is already the newest version (5.15.8+dfsg-3+deb12u1).

qtquickcontrols2-5-dev is already the newest version (5.15.8+dfsg-2).

libqt5texttospeech5-dev is already the newest version (5.15.8-2).

libqt5texttospeech5 is already the newest version (5.15.8-2).

g++ is already the newest version (4:12.2.0-3).

make is already the newest version (4.3-4.1).

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@raspberrypi:~#

**Comment by cagnulein** [comment]
you are missing qml-module* 

https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md#installation

**Comment by amasolov** [comment]
Gotcha! Thank you, rebuilding. I took the package list from the raspberry pi section which is for headless installation I believe. 

Will add the command line parameters in a pull request and link it to this RFE.

**Comment by cagnulein** [comment]
Awesome, thanks!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 11:41 Alexey Masolov <
***@***.***> ha scritto:
