### ISSUE TITLE
Sole F85

### ISSUE THREAD

**Issue by ryanmowry** [cagnulein/qdomyos-zwift#2086]
[debug-Thu_Feb_1_06_13_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14124673/debug-Thu_Feb_1_06_13_41_2024.log)

**Comment by cagnulein** [comment]
#2085

**Comment by cagnulein** [comment]
please toggle the inclination setting now in the sole treadmill and try again. there was the wahoo error before.
let me know

**Comment by ryanmowry** [comment]
Thank you, the QZ app is reading the treadmill speed and incline now.  I
opened Zwift on my other device and it’s reading the treadmill speed but
the incline from Zwift isn’t relaying to the treadmill (it isn’t
automatically incline or decline).  I have to leave for work but I can mess
around with it later today.

Thanks,
Ryan

**Comment by cagnulein** [comment]
Did you set the zwift credentials on qz? If you can't see the zwift
credentials setting in qz you need the beta of it
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle 12:50 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
I may not be looking in the correct spot but I don’t see anything on Zwift,
I see Strava.

**Comment by cagnulein** [comment]
just sent the latest beta by email
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 13:09 ryanmowry ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
first of all are you able to change the incline from the qz inclination tile? it not it means that we have to enable the inclination toggle enabled again and check why isn't working for you

let me know

**Comment by ryanmowry** [comment]
I cannot adjust incline from QZ.  Should incline be toggles on or off?

I have to leave for work but I will mess with it tomorrow morning.  Thanks
and sorry lol

**Comment by ryanmowry** [comment]
Still no luck, when I toggle it on Zwift no longer detects my speed, the avatar just stands there. When I toggle it back off he moves but no luck with the incline.

When I paste the debug in the comment it says that there are too many characters

**Comment by cagnulein** [comment]
don't paste the log. zip it and add it to the comments

i'm interested in the one with the inclination setting enabled

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 13:27 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
I'm really striking out, I have it zipped but something goes wrong when I try to put it in the comments

![image](https://github.com/cagnulein/qdomyos-zwift/assets/158461517/9c258b81-05f1-48c3-813c-327f4f9c2a6a)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/158461517/d32c123f-b916-49fc-b942-888915b3e2a1)

**Comment by cagnulein** [comment]
you have to do from a browser otherwise it doesn't allow to add it. github limitation unfortunately

**Comment by ryanmowry** [comment]
[debug-Sat_Feb_3_09_45_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14151894/debug-Sat_Feb_3_09_45_41_2024.log)

**Comment by cagnulein** [comment]
Thanks, I will check it ASAP. During the weekend I am trying to stay with
my family.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 16:05 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
No problem, I completely understand!  Have a good weekend

**Comment by cagnulein** [comment]
Hi again, I was checking your case (I'm too curious) and it seems it's
about the
https://github.com/cagnulein/qdomyos-zwift/issues/1599

So there i suggested also to enable the f65 setting in the sole treadmill
setting along with the inclination one.

Can you try it?

Is it your same f85 version?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 16:09 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
Still no luck, the avatar doesn't move.  The qz app reads the speed from the treadmill but the zwift avatar isn't moving.  When I downloaded the beta version the other day I think it reset all the settings to default (not sure if it's good, bad, or doesn't matter).  I tried to get back to what I thought the previous settings were.

When i turn off inclanation the zwift avatar moves per the speed of the treadmill but the incline on zwift doesn't relay to the app or treadmill

**Comment by cagnulein** [comment]
Ok let's leave zwift for a second out of the game.

With the sole f65 and inclination settings both enabled are you able to read metrics on qz and change the inclination or the speed?

**Comment by ryanmowry** [comment]
The app reads both the speed and incline but i cannot adjust the speed or incline from the app

**Comment by cagnulein** [comment]
Is this the 2019 version? Or another one? Are you able to change the
inclination from the sole app directly? It could be a firmware limitation
of your treadmill at this point

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 16:59 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
I think it's a 2023, I just bought it new.   I downloaded the app (both sole apps) and it does let me control the speed and incline from the sole app

**Comment by cagnulein** [comment]
Ok that's a good news! So we need to collect how it does, probably it uses
a different way from the 2019

In order to do so we need an android device: do you have any? Even for 10
minutes. Then follow this with the sole app
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 17:12 ryanmowry ***@***.***> ha
scritto:

**Comment by ryanmowry** [comment]
I tried it with an amazon fire tablet (I had to fight with my kid for it lol) but it doesn't give me a prompt screen when i keep clicking on Build Number

**Comment by cagnulein** [comment]
Maybe this can help you
https://www.alphr.com/fire-tablet-developer-options/

Amazon devices are  not 100% android. So this procedure could may not work

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 17:28 ryanmowry ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
You have to download the apk and side load it
For example from pureapk website

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 17:51 ryanmowry ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@ryanmowry any news?

**Comment by ryanmowry** [comment]
Hey Roberto,

No, I have kind of given up on it, I’m not real tech savvy.  But, I thank
you for all the help and effort you have given to try and get it to work on
my treadmill.

Thanks,
Ryan

**Comment by cagnulein** [comment]
ok i'm here in case you want to resume this

**Comment by ryanmowry** [comment]
Thank you
