### ISSUE TITLE
QZ with Windows 11 Pro

### ISSUE THREAD

**Issue by EnglandAngling** [cagnulein/qdomyos-zwift#2087]
HI all, I'm using a Nordictrack S22i and all is working OK with the QZ Phone app and Zwift but I cannot get the Windows version to work on my laptop. I am unable to pair the laptop to the bike. Nothing shows up in Windows for any Bluetooth connection to the bike. The laptop runs Windows 11 Pro, and the QZ ZIP file that I downloaded to try was "windows-msvc2019-binary-no-python.zip". All I get is zero's when I launch "qdomyos-zwift.exe". I have set the TDF Companion IP to the IP of my bike. Any help much appreciated. Debug Log attached.
[debug-Thu_Feb_1_11_58_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14124982/debug-Thu_Feb_1_11_58_49_2024.log)

**Comment by cagnulein** [comment]
Hi the problem is that the pc is not getting any udp frames
from 192.168.1.141
Did you disable the firewall on the pc?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 feb 2024 alle ore 13:00 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment]
Hi Roberto

I have now allowed 192.168.1.141 on the firewall and it is now working. Thanks for your help. One other question I have is I can't arrange the tiles, it looks a bit jumbled (see attached). I've tried adjusting font size, and re-sizing the window but no luck.

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
i don't see the image, you have to attach on github. anyway did you play with the dpi of your screen? also you can reduce the zoom ui setting in qz

**Comment by EnglandAngling** [comment]
OK thanks I'll give that a try.

I have already bought the app, do I also need to donate monthly on Patreon? 

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
yes the window license require more work to be mantained that's why i decided to add a patreon subscription

**Comment by EnglandAngling** [comment]
OK - I don't want to be tight :-) but what is your minimum custom pledge?

**Comment by cagnulein** [comment]
you can choose the one that you can effort and that you feel right for the support :)

**Comment by EnglandAngling** [comment]
OK thanks!

**Comment by EnglandAngling** [comment]
How does the Windows app know I'm a member on Patreon? Do I need to add an email address in settings or something ?

**Comment by cagnulein** [comment]
patreon is still validating it. it's saying "pending".
anyway then just add the same email address on the email settings on qz and press ok (be sure it's all lower case)

**Comment by EnglandAngling** [comment]
Hi Roberto - can the QZ companion when used with Zwift automatically change resistance and inclination? I do not notice any automatic change when using Zwift. Also the "+" and "-" on the QZ tiles do not change anything on my Nordictrack S22i bike. I have set the ADB remote in the QZ app to ON. Thanks. Tim.

**Comment by cagnulein** [comment]
Are you able to do on the ios or android version @EnglandAngling  

I'm asking to address correctly the issue

**Comment by cagnulein** [comment]
ok so it doens't work on the android version neither? please follow this and report back https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike

**Comment by EnglandAngling** [comment]
I have not tried IOS

**Comment by EnglandAngling** [comment]
But it doesn't work on Android or my laptop

**Comment by cagnulein** [comment]
Share the link above

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 12:20 EnglandAngling ***@***.***>
ha scritto:

**Comment by EnglandAngling** [comment]
Ok thanks, I'll try that this evening and let you know.

**Comment by EnglandAngling** [comment]
The QZ inclination + and - is now working when I use the QZ on my laptop. There's a 3 second delay between each click of the + or - on QZ and the response of my Nordictrack S22i. The resistance tile however still does nothing. During a Zwift ride, Zwift is now controlling inclination automatically. Another thing I'm trying to do is use Chrome Remote Desktop to display my laptop screen on the S22i console screen. It all works OK with Zwift but auto inclination stops working. As soon as I go back to iFit on the screen with the manual ride, the auto-inclination starts working again. Regards Tim.

**Comment by cagnulein** [comment]
ok so it seems that everything is working? qz is handling only the inclination because the bike when the inclination changes change also the internal resistance 

the delay it's seems high. if you send a debug log i can check it if i can do something

**Comment by cagnulein** [comment]
@EnglandAngling any news?

**Comment by EnglandAngling** [comment]
Hi Roberto - I've been using Zwift a lot and it seems to be ok, although I'm not sure how quickly the bike is responding to changes in Zwift inclination...maybe there's a delay there too, but I'm not sure. I've attached the latest log file (zip file as quite large)
[Uploading debug-Fri_Feb_16_21_37_53_2024.zip…]()

**Comment by cagnulein** [comment]
You have to wait to press comment until the upload is finished otherwise the log is corrupted

**Comment by EnglandAngling** [comment]
[debug-Fri_Feb_16_21_37_53_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14318553/debug-Fri_Feb_16_21_37_53_2024.zip)

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle 12:11 EnglandAngling <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@EnglandAngling i guess I got your issue. In the code i have this

>         // since the motor of the bike is slow, let's filter the inclination changes to more than 4 seconds
>         else if (lastInclinationChanged.secsTo(QDateTime::currentDateTime()) > 4) {

maybe it's not your case? so i can remove this for you?

**Comment by EnglandAngling** [comment]
OK - I can give it a try, thanks.

**Comment by cagnulein** [comment]
ok i'm build a new one without this, i will share a link here then

**Comment by cagnulein** [comment]
@EnglandAngling it's building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7943920640
you will see in the bottom of the page the zip to download the new version

**Comment by EnglandAngling** [comment]
Hi Roberto - yes that has improved the response time, thanks. It's now more like 1 to 1.5 seconds. Regards Tim

**Comment by cagnulein** [comment]
That’s great! I will add this as a setting so!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 feb 2024 alle 00:04 EnglandAngling <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done! in the master i added a new "inclination delay" in the advanced setting that you can set to 0 or any other value to add a delay

**Comment by EnglandAngling** [comment]
thanks, do you have a link to a download for the new version please?

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/actions/runs/7971241191/artifacts/1258918562

**Comment by EnglandAngling** [comment]
Thanks. Do you know if I somehow manage to install Zwift onto my Nordictrack S22i, would this method still work with QZ  ? Currently I just have my laptop screen next to the bike but it would be nice to use the S22i screen. I've tried Chrome remote desktop on the S22i but as soon as switch from the i-Fit manual session screen to Chrome Remote Desktop, the automatic inclination stops working.

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
in order to have auto incline you can't install other apps on the tablet
bike. also the tablet doesn't have the hardware capability sto run zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle ore 10:35 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment]
ok thanks

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by EnglandAngling** [comment]
Thanks, do you have a link to instructions on how to install it please?

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
are the same of the previous apk. you just need to replace the apk in the install folder. anyway i strongly suggest to DON'T update ifit to keep the compatibility with QZ

**Comment by EnglandAngling** [comment]
OK - with the previous APK I was able to do a series of taps on the IFIT screen to access the necessary options in order to change settings etc....but with the new iFIT beta, this doesn't work....It seems iFIT are making it harder to avoid updates, so I ended up having to reset my S22i bike to factory settings and now i have the latest iFIT beta installed. I don't know how to install the new APK...

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
you can ask here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/103 to @victorypoint how to install the apk on the beta, i didn't have the bike so i can't directly tell you which are the steps.
