### ISSUE TITLE
[BUG] - Norditrac S50 - Windows 11 QZ App

### ISSUE THREAD

**Issue by benfairclough** [cagnulein/qdomyos-zwift#2088]
**Describe the bug**
Issue with Windows 11 / Iphone App connecting to Norditrac S50 Treadmill

**To Reproduce**
Steps to reproduce the behaviour:
Follow instructions to deploy APK to the treadmill, Used the Bat file install method, Reset treadmill completely and tried again not working. 
Application in the windows app store does not connect at all, just leaves a connecting screen, Been provided a separate binary and this looks to connect but the tiles to not display any data at all.

FYI there is a Wahoo Kickr in the same location, which for now I have unplugged for debug.

FYI - Bluetooth connection ID's look to be different on connecting 

**Expected behavior**
App to display the data to the tiles

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows 11
 -

![image](https://github.com/cagnulein/qdomyos-zwift/assets/13221928/6a48ec27-3dd7-41d4-a427-d9573f7ab13f)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by benfairclough** [comment]
[debug-Thu_Feb_1_15_07_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14127238/debug-Thu_Feb_1_15_07_18_2024.log)
[debug-Thu_Feb_1_15_07_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14127239/debug-Thu_Feb_1_15_07_05_2024.log)
[debug-Thu_Feb_1_14_57_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14127240/debug-Thu_Feb_1_14_57_19_2024.log)
[debug-Thu_Feb_1_14_51_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14127241/debug-Thu_Feb_1_14_51_26_2024.log)

**Comment by cagnulein** [comment]
ok I can see the messages from the companion but they are all empty. this means that the companion can't access to the metrics. can you check these steps https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

**Comment by benfairclough** [comment]
Thanks - Performed the Companion change to C1750 still the same,
FYI - I have reset the treadmill already and tried again, same result,
I do not have a ifit account so its not signed in will this affect it?
log attached  
[debug-Thu_Feb_1_15_26_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14127394/debug-Thu_Feb_1_15_26_08_2024.log)

**Comment by benfairclough** [comment]
Not sure if this is worth mentioning:
Bluetooth ID's look different
![image](https://github.com/cagnulein/qdomyos-zwift/assets/13221928/926cd53e-4736-4ebb-abc0-9fa6c3a044a9)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/13221928/e2c6cdd2-b075-44b0-b534-922e30b9b9ed)

**Comment by cagnulein** [comment]
actually it seems worse now. i can't see the messages from the companion at all in this log. of course did you reinstall the companion after the reset?
in order to don't update the ifit version (i guess it does also even if you don't have a credentials), you have to remove the gateway from the wireless settings of the nordictrack devices as soon as it's resetted

if it doesn't work neither, you can try this https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by benfairclough** [comment]
Ill reset the Treadmill again and switch off the router,
Will report back in and hour
Thanks

**Comment by benfairclough** [comment]
OK - Update
Reseting the treadmill and not updating it has fixed the issue. I can connect now with the Apple IOS version and the bespoke Windows Version, The Amazon App store version still does not work though.
Treadmill is a Norditrack S50
It looks like the latest version of iFit breaks the application,
Please Mark this as Closed ill update the FB page if you like

**Comment by cagnulein** [comment]
Great! For the amazon app store if you want I can check it with a debug log if you need it
