### ISSUE TITLE
[REQ]Proform 2000 Pro -3% incline

### ISSUE THREAD

**Issue by bobc5025** [cagnulein/qdomyos-zwift#2092]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please add range to go  below 0% down to -3% for Profile Proform 2000 not pro or make a duplicate profile that is for the pro that has this capability
[debug-Fri_Feb_2_09_18_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14142705/debug-Fri_Feb_2_09_18_59_2024.log)

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
fixed! it will be in the 2.16.41
if you are not in the closed beta, send me an email to roberto.viola83 at gmail.com and I will add you! I will upload this in the next days! Thanks for the feedback!

**Comment by cagnulein** [comment]
@bobc5025 did you try?

**Comment by bobc5025** [comment]
How would I get this update on android? Sent from my iPhoneOn Feb 14, 2024, at 2:05 AM, Roberto Viola ***@***.***> wrote:﻿
@bobc5025 did you try?

**Comment by cagnulein** [comment]
did you join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift @bobc5025  ?

**Comment by bobc5025** [comment]
Ok just got the update I will let you know later today. Sent from my iPhoneOn Feb 14, 2024, at 9:22 AM, Roberto Viola ***@***.***> wrote:﻿
did you join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift @bobc5025  ?

**Comment by bobc5025** [comment]
It didn't seam to make a difference. If I use the app to control the
treadmill the incline stops at zero and doesn't change. If I use the
treadmill panel The app shows an incline of like 656.36 or something like
that. I'm on android version 2.16.42
*C Robert Christensen (Bob)*
***@***.*** ***@***.***>*

**Comment by cagnulein** [comment]
could you please send an update debug log? there is an easy fix for this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 23:29 bobc5025 ***@***.***> ha
scritto:

**Comment by bobc5025** [comment]
Email isnt working for me for some reason.
Here are the new logs.
[debug-Thu_Feb_15_15_06_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14453535/debug-Thu_Feb_15_15_06_42_2024.log)
[debug-Thu_Feb_15_15_21_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14453536/debug-Thu_Feb_15_15_21_42_2024.log)

**Comment by cagnulein** [comment]
ok thanks i will check this tomorrow!

**Comment by cagnulein** [comment]
fixed @bobc5025  https://github.com/cagnulein/qdomyos-zwift/actions/runs/8102858060
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by bobc5025** [comment]
The treadmill will now movee to -.5 from a command from the App but then the app losses control of incline until treadmill is returned to 0%. I made a few moves with the app then moved down to -3% manually when the app lost control 1% moves at a time. Thanks for your work on this.

[debug-Thu_Feb_29_16_05_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14454457/debug-Thu_Feb_29_16_05_45_2024.log)

**Comment by cagnulein** [comment]
Fixed also this one! Thanks
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8108169698
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 mar 2024 alle ore 00:11 bobc5025 ***@***.***>
ha scritto:

**Comment by bobc5025** [comment]
Ni e that works perfect. How do I get a non trial?

**Comment by cagnulein** [comment]
Glad to hear that!
