### ISSUE TITLE
[BUG]  Merach S09

### ISSUE THREAD

**Issue by markgoodrich** [cagnulein/qdomyos-zwift#2093]
[debug-Fri_Feb_2_11_55_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14146025/debug-Fri_Feb_2_11_55_18_2024.log)

**Comment by cagnulein** [comment]
ok i quickly checked your debug log

1. zwift resistance offset to 25 it's too high for your bike. you have to
set a value that you feel like a flat road for your bike. usually a
midlevwl resistance
2. i saw that you did a workout in zwift: your bike doesn't have erg mode
so you can't do it with auto resistance or you shouldn't :) if you want, as
i did for a lot of bike, i can virtualize the erg mode for your bike . i
would need a power table from your bike. let me know if you are interested

so summarizing: if you do a free ride with a lower zwift resistance offset
you should get a better experience

saying so, have a good night from italy (1130 pm here)



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle 23:16 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Heck.

I had moved the offset from 18 to 25 because at 18 it still felt like I had
no resistance.  I'll try again.

Not being able to do the workouts makes either Zwift or the bike not worth
it.

I have no idea what a power table is, how to find it, or how to send it to
you, but it sounds promising.

**Comment by cagnulein** [comment]
it's strange because in the log that you sent me you were doing a workout, that's why the resistance went from 6 to the max.
I suggest to do a free ride and show me the log
thanks

**Comment by markgoodrich** [comment]
[debug-Sat_Feb_3_09_25_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14152297/debug-Sat_Feb_3_09_25_03_2024.log)

**Comment by cagnulein** [comment]
so how did it go here @markgoodrich ?

**Comment by markgoodrich** [comment]
I'm about to give up on the bike. i've spent most of the morning on the
bike, but mostly trying to get things to work.

If I just ride and just use Zwift everything works perfectly. Workouts
don't work, as you pointed out.

I tried a ride several times with QZ and quit after a minute or less
because of the constant jump between 1-24 resistance level readings on the
bike display, but actually no change in resistance.

I did manage to save one ride, although I don't know how much information
you can get from it. I've sent the log to github.

QZ is now stuck in run mode (dunno how that changed) and I can't figure out
how to get back to bike.  Rides load but I can't start them. My avatar sits
on the side of the road.

**Comment by cagnulein** [comment]
i will follow you as long you like, i never give up.

the problem in this log is that i don't see any resistance changes, so i guess it's not the right one.

do you have other from today?

**Comment by markgoodrich** [comment]
I'll try later, I'm pooped, did a manual ride on the bike just so I could get some exercise.  Thanks for your persistence..

**Comment by cagnulein** [comment]
No problem, take your time.


Il giorno sab 3 feb 2024 alle 18:29 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
[debug-Sat_Feb_3_09_30_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14152325/debug-Sat_Feb_3_09_30_07_2024.log)

Let me know if you can see a ride that lasts any time and if it shows resistance change.

**Comment by cagnulein** [comment]
yes i'm seeing the error but i see also that the resistance offset its still to 25 here

just to be clear, i'm talking about this parameter, on this log is 25 on your side.

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/8d882177-0c02-4cad-80cf-2ada1406512f) 

did you change then? if so do you have a log with it changed?

how many resistance level has your bike?

**Comment by markgoodrich** [comment]
Yes, I left the offset at 25 this morning. I will lower it to 18 before
trying another ride.

The bike has 16 resistance levels. However QZ identifies the bike as a
Kickr, rather than a Merach, and when using QZ the app thinks the bike has
24 levels.

**Comment by cagnulein** [comment]
consider that settings can't never be higher than the resistance levels.

the result of doing this leads exactly to the behavior that you're
describing.

i suggest to lower it down, for example to 10 and using the gears tile if
you are not happy with the resistance set from qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 19:20 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Okay.

**Comment by markgoodrich** [comment]
I'm going to have to start over with basic questions.

I have QZ, Zwift, Merach bike, and Garmin FR 955 with your companion app
installed.

First I open QZ.

Then I start the bike, which QZ finds, and the bike's blue BT light comes on

Then I try connecting QZ to the FR using Virtual Run, but nothing happens
when the FR says "Ready to Pair".
I am obviously missing a step but I can't figure it out, despite a lot of
time online trying to find the answer.

So then I open Zwift, it connects ( I think ) to QZ, finds the KickR bike,
which QZ recognizes as the Merach, and power, cadence, etc connect.  HRM
monitor in QZ connects.

Start a free ride.  "I" just sit on the side of the road despite pedaling.
Nothing shows on the QZ tiles.

I literally feel stupid. I'm pretty adept at things like this, but I'm
stumped.

For what it's worth, trying a video ride in Kinomap also does not start
riding or providing data., despite being connected directly to the bike
from the tablet.

I am so sorry to be taking up so much time but darn it, this ought to be
easy!

**Comment by cagnulein** [comment]
Let's leave the watch out of the game for a minute. 

Let's understand your zwift issue 

First of all are you getting the metrics on qz correctly?

Where are you running zwift now? Where qz? If they are on the same android device you need to enable the android notification setting under the experimental settings 

Let me know

**Comment by markgoodrich** [comment]
No metrics, no start on the Zwift ride when I start pedaling.  Using Zwift
alone, everything works, although I didn't try to see if resistance
changes, I just pedaled enough to see that in Zwift metrics show.

Once again, in QZ am I connecting in proper order?

1.  Turn bike onj
2.  Open QZ, it finds the bike...BT light in app stops blinking
3.  Open Zwift, connect to "Kickr", not Merach
4. Choose ride, start and also start QZ ride.  Nothing happens, no metrics,
my avatar sitting on side of road.

**Comment by cagnulein** [comment]
if you can't see the metrics on qz is useless to try zwift, the problem is before zwift :) 

so we need to understand which issue do you have with the metrics . i thought they were working in the last days, isn't it?

anyway let's send me a debug log only try to ride 30 seconds on qz without zwift

**Comment by markgoodrich** [comment]
Okay, I will have to do it either later today or tomorrow.  Thanks.

**Comment by cagnulein** [comment]
don't worry we will get this :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 feb 2024 alle 20:01 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Log attached.  Turned bike on, then opened QZ.
QZ immediately found Merach:  "Found MRK-S09-880F"  Never got a "connected"
notification in QZ, but BT light on bike lit up and QZ BT search light quit
blinking,
QZ Start button started blinking (have it set to start in pause per your
suggestion in the instructions).  Pressed the start button and pedaled.
Nothing at all in the QZ data fields.

[The same behavior is exhibited with the Garmin Forerunner. If I open QZ
with the Forerunner the only device with BT on, it says "Found...." but
never says "connected" although QZ BT searching light quits blinking.

QZ used on Pixel 7 Pro Android 14
Zwift used on Samsung A7 Lite tablet, Android 13

While we are at it, is there a way to change from dark to light mode on
QZ?  Font is so small I can barely read it in dark mode.

**Comment by cagnulein** [comment]
you have to attach it to github otherwise i can't see it

in the ui customization you can change some color of qz ui interface

**Comment by markgoodrich** [comment]
Ok, I will do that.

**Comment by markgoodrich** [comment]
[debug-Mon_Feb_5_15_27_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14172266/debug-Mon_Feb_5_15_27_16_2024.log)

**Comment by cagnulein** [comment]
the problem here is that you enabled the fake elliptical setting in the
experimental settings. disable it

please don't change any settings until we will figure it out otherwise it's
very hard to help you.

just change what I'm asking to do so will fix this.

thanks
midnight here, so i will be back tomorrow

share me another log if you have other issue


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 feb 2024 alle 22:55 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
If I did that it was an accident, sorry.

**Comment by cagnulein** [comment]
no problem! let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 00:18 markgoodrich ***@***.***>
ha scritto:

> If I did that it was an accident, sorry.
>

**Comment by markgoodrich** [comment]
Some progress.  
With offset at 10 as you suggested, now  a flat road starts at 11.
However, I really need it to start at 8 or 9 on the flats, as hills jump to as high as 19 or 20 with up to 6% grade; my HR rockets up.  8 or 9 feels like my road bike on a flat road.  On downhills with no inclination change in Zwift, again there is a discrepancy in QZ. hilariously high, especially downhill.  I think I passed everyone on the route...not possible for me to be that fast.
HR showed up on Zwift this time, but still not on QZ.
Incline on QZ does not match Zwift, e.g. Zwift 3%, QZ shows maybe 1.8%. The higher the Zwift incline the wider the discrepancy.
This is going on what, ten days?  You're getting closer, but I'm beginning to think I should consider another bike if it's not resolved in the next few days.  I have a return window that closes fairly soon.  There's an Echelon EX-5S for sale for $500 near me, but I don't know if I'll run into the same problems setting up with QZ and I don't know if that bike has auto resistance adjustment.There's also a used Keiser M3i for sale at a store for $900, which is more than double the cost of the Merach, and again, I don't know if there will be problems with QZ.  

[debug-Tue_Feb_6_10_37_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14183773/debug-Tue_Feb_6_10_37_58_2024.log)

**Comment by cagnulein** [comment]
If you are not happy with the bike return it :)  I'm just following in the
process  :)

Keiser doesn't have auto resistance, remember this.

also remember that what zwift shows is not the inclination that sends. so
that's the discrepancy. zwift shows the average of the next 200

also for the speed calculation is all about zwift, it's not about qZ
https://robertoviola.cloud/2024/01/27/dispelling-the-myth-speed-variations-between-qz-and-zwift-are-not-a-device-issue/

let me know if i have to check the log tomorrow or you are returning this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 17:59 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Thanks.  I'm going to have to keep it, to get where I want to be is too
much money, even if I end up just riding manually.

If I can get the initial resistance down to 8 or 9 and get HR to show in QZ
I'll leave you alone....:)

**Comment by cagnulein** [comment]
ok no problem :)

so put the zwift resistance down to what you like and you are good to go!

for hr which hr device do you have?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 18:19 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
To get down to 8 or 9, should I experiment with lowering the offset from 10
i QZ?

I have a Garmin Forerunner 955.  QZ finds it when I set the watch to
Virtual Run and press buttons until it says Ready to, but I must be missing
a step somehow to get QZ to start reading the output.

**Comment by markgoodrich** [comment]
It was there, I have the companion app installed on the watch, but when I tried to refresh, it dropped it and my only options are Disabled and Wifi in QZ Heart Belt Name.

**Comment by cagnulein** [comment]
stay in that screen while you are using the virtual run thing on the watch.
just press once refresh and stay there for 10 seconds. be sure zwift is
closed

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 20:19 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Ah, got it, thanks.  the app says "Forerunner 955 Solar Found" now, I guess
that means it is connected.

You've really been great to deal with, thank you so much.

**Comment by cagnulein** [comment]
ok perfect let me know if it will work

remember to start the virtual run before opening qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 20:26 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Roberto, I'm back the guy with the Merach S09 that is problematic. I've
spent the last several days trying to troubleshoot connection issues and am
ready to give up and move on.

What bikes do you recommend that will work most easily with QZ and Zwift to
have auto resistance adjustment?  I mean, which ones have the least
problems with setup and connection?

Thanks, and again, a milion thanks for trying to help me get the bike to
work like it should.

Mark

**Comment by cagnulein** [comment]
which issue do you have now? if you want something cheap that works perfectly buy a echelon ex3

**Comment by markgoodrich** [comment]
Same issues, Roberto, Forerunner HRM is found, but no data is received,
resistance jumps all over the place, speeds are ridiculously high...on and
on.

To be clear:  The Echelon will auto-change resistance with Zwift grades?

Will an Echelon EX5-S also have auto resistance adjustment?  There's one
for sale near me at a good price, but cannot be returned.

I can't thank you enough for trying to help me get that nice bike to work.

Mark

**Comment by cagnulein** [comment]
> Same issues, Roberto, Forerunner HRM is found, but no data is received,

this is not about the bike. If you want we can still check it

> resistance jumps all over the place

with a debug log i can check again your settings

> speeds are ridiculously high

on zwift or qz?



> To be clear: The Echelon will auto-change resistance with Zwift grades?

yes but with qz, not standalone



> Will an Echelon EX5-S also have auto resistance adjustment? There's one for sale near me at a good price, but cannot be returned.

yes with qz, but you will have to turn off the screen.

**Comment by markgoodrich** [comment]
I'm really sorry about your back pain, I've suffered with it for five
years, three surgeries.  I literally feel your pain.

I hate to keep bugging you about this but I am definitely going to return
the Merach and I want an Echelon, either the EX3 or that EX5S used I
mentioned earlier, but I don't understand how a manual -change resistance
bike like the EX3 can be made to automatically change resistance using QZ
in Zwift. I asked in the FB group but no one answered.

**Comment by cagnulein** [comment]
Thanks :)

QZ changes the gears on the EX3 or EX5 in the same way that it's doing on the Merach. That's why I'm telling that it's not a bike issue, i guess it's more, no offence, a user error. That's why I'm still saying to show me the debug log of the issue that you have know so i can tell you which is the issue

Otherwise, if you don't want qz in the middle, buy a simply smart trainer and use a regular bike with it. Maybe it's better for you?

**Comment by markgoodrich** [comment]
Okay. I'll connect up today and try to do at least 20 minutes, and send you
the debug log.

Once again, in order

I have forerunner set to broadcast hr,

 have chosen virtual run, although when button is pressed all it seys is
ready to pair

QZ says Forerunner found, but there is no "connected' notification, which I
assume is fine?

Turn on and Connect bike to QZ, again says "Merach found" no "oonnected"
note.

Connect to Zwift, choose resistance, and it finds, not Merach, but Wahoo
Kickr, same with cadence and power

Connect forerunner HR to Zwift, HR shows.  HR never registers in QZ

No offence taken...:)

**Comment by cagnulein** [comment]
> QZ says Forerunner found, but there is no "connected' notification, which I assume is fine?

yes that's right



> Turn on and Connect bike to QZ, again says "Merach found" no "oonnected" note.

right



> Connect to Zwift, choose resistance, and it finds, not Merach, but Wahoo Kickr, same with cadence and power

correct



> Connect forerunner HR to Zwift, HR shows. HR never registers in QZ

nope forerunner must be connected only on qz. then qz sends the hr to zwift. did you set the fore runner in the heart rate belt name setting in qz?

**Comment by markgoodrich** [comment]
In HR Options HR name in settings is "Disabled" other opinion is wifi.
refresh devices list  does nothing.

Once broadcasting I choose virtual run, press start button, watch says
ready to pair, pressing again does nothing.

**Comment by cagnulein** [comment]
There you have to select the forerunner
If you don't see it. Start the HR broadcasting from the watch then start qz
and theb you will it there

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 17:06 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
I understand exactly what you are saying.  When I have the watch
broadcasting HR and choose virtual run the watch DOES connect to QZ but in
settings > Heart Rate Options > Heart Belt Name, all I see is "Disabled"
drop down list only shows "wifi".

I connected everything as listed earlier, still no HR in QZ, when Zwift
opened power, cadence, etc, connect to Wahoo (QZ) when try to connect HR to
Zwift eventually Forerunner is found  but "no signal".  QZ did not show hr
after connection nor after connecting to zwift.

**Comment by cagnulein** [comment]
Use the refresh button to populate the combo box while you are in the
settings

You have to see forerunner there

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 17:21 markgoodrich ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Record a video of what you are doing please
Including watch and phone

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 17:31 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
I feel like the village idiot.

Where and how do I get a video to you?  Google Drive?

**Comment by cagnulein** [comment]
Yes and share the link here then

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 17:54 markgoodrich ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
any news @markgoodrich ?

**Comment by markgoodrich** [comment]
Hi, quite a bit of progress...have not been able to do the video you asked
for, I need a third device to shoot it.

BUT, I've successfully completed a short 10 minute ride with all functions
showing on QZ dashboard and on Zwift screen. Auto resistance is changing as
desired, and even gear changing is working. Forerunner is also connecting.

The remaining issue, assuming things are now all working, is my speed and
power are much to high. I'm barely pedaling at 50-60 rpm and passing
everyone. If I increase to a little higher, my speed jumps up, too.  I need
to offset the speed being recorded to be more realistic.  Power output is
the same issue, but from what i"ve read, there may be no way to adjust
that...I definitely am not generating the wattage shown.

I hope I attached a debug log of the ten minute ride in case that will help
get the speed issue adjusted.

I have NO IDEA why or how it's all working!!!

**Comment by cagnulein** [comment]
to decrease power set the watt gain to 0.5 for example or even less

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 18:47 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
Okay, thanks, and will the power offset change my speed?

And of course I apparently didn't attach the debug log. It's here, in case you need it.

[debug-Thu_Feb_15_11_30_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14300857/debug-Thu_Feb_15_11_30_20_2024.log)

**Comment by cagnulein** [comment]
Yes watt gain will affect also the speed on zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 19:29 markgoodrich ***@***.***>
ha scritto:

**Comment by jli3388** [comment]
hi Roberto, sorry to butt in, I have the exact same bike,  using Mywhoosh atm. Similar problem initially with @markgoodrich , everything connects, and  Mywhoosh shows speed and power etc. But I am not getting any resistance change on training. 

Should I file another bug or we can use this bug to keep going.  Here is the log captured during my two short training attempt session, I did attempt to fast forward the training hoping to see resistance change but nothing happened.
[debug-Wed_Feb_21_20_42_13_2024.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/14368481/debug-Wed_Feb_21_20_42_13_2024.log.zip)

Again, please let me know if I should file a new bug instead. Tks.

**Comment by cagnulein** [comment]
Ok, I'll take a look.
It's fine to use this one, thanks

Il giorno gio 22 feb 2024 alle 04:58 jli3388 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi! the main issue is that you have to enable the zwift workout mode in the
bike setting in QZ as well
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 feb 2024 alle ore 05:44 cagnulein ***@***.***> ha
scritto:

**Comment by jli3388** [comment]
@cagnulein , I did tried another session before with that setting on but nothing changed if I remember correctly. Perhaps I have done something wrong. I will try that again later tonight and update you.  Tks

**Comment by jli3388** [comment]
@cagnulein I just tried ur suggestions. It WORKS!!!  
however I do noticed something might be off:

1. the power output is probably inflated. Not sure how to tune it. 
2. the resistance change in a training is not smooth. every time it needs to go to another level, it flip back and forth from the original level to the target level, then back to the original level and then finally to the target level.  Not sure if this is intentional to make the transition smoother.....
3. On higher resistance level, it pretty much flip back and forth at every right leg down stroke. It would for example set the resistance to 24, then I have to stand and power down on it, which cause it the quickly change to 13 or 15, then it will change to 24 again right before my right leg push down. Not sure if this is normal.  I will try to do google it to see how others tune the app. 

All in all, it works, very happy about the bike and the app. Thank you very much for the wonderful app.

**Comment by cagnulein** [comment]
for the wattage inflated use a lower watt gain setting, in the advanced
settings: for example a 0.8w

for the problem that it's changing resistance too quickly use a higher
number to the zwift erg filter up and down. set a 20 and 20 to start

a debug log will also be useful

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 23 feb 2024 alle 03:23 jli3388 ***@***.***> ha
scritto:

**Comment by jli3388** [comment]
hi Roberto, 

I did some more testing with the adjustment u suggested, however I believe the calculation is off somewhere.  When the training starts it feels fine. But when I fast forward to the higher intensity section things started to get strange.  The bike only has 16 level of resistances, however sometime I will see it try to set it to 24, which cause the bike to ram the resistance to as high as it can then quickly reset to what it was before.  I tried setting the Max Resistance level to 16 but then it will crank the resistance level to the highest at the beginning of the training when its simply a warmup.

Also during periods where it does seems to work, the ERG calculation still feels off. E.g. when the section only requires 90-130 watt and at the time when my output is almost double that at 230watt, it would still crank up the resistance to almost max.  It would only went down if I speed up my paddling even more.  And sometimes if I speed up too much, it feels like it would throw off the calculation completely and cause the ERG to go wild and set the resistance to 24 for no reason at all. 

The log attached should cover the scenario I mentioned.  I am not sure how to further divide it though to make it easier for u to look at. Please let me know if u want me to reproduce a particular scenario and have it captured in log.  

[debug-Sat_Feb_24_00_31_43_2024.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/14393429/debug-Sat_Feb_24_00_31_43_2024.log.zip)

**Comment by cagnulein** [comment]
@jli3388 i guess i got your issue: you need the beta for this. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by jli3388** [comment]
@cagnulein I finally tried the beta, its a lot smoother and not as erratic anymore. However another problem come up, the resistance has become very mild. I tried to bump up the min resistance, set the watt offset to 0.8 and lower, set the max resistance to 16 to match what actually is available with the bike. I doesn't move pass level 6 during a workout. I will try to do some more config tuning and if can't resolve it, will get another session with debug enabled.

In the meantime, please know if u have any additional suggestions on things that I might have missed. Tks

**Comment by cagnulein** [comment]
@jli3388 share a debug log of your current issue

**Comment by jli3388** [comment]
Thank you @markgoodrich for the suggestion, I just tried ur settings, somehow still not quite work out the way I thought it would be. The resistance level still doesn't much while my watt output is 20-30 lower than the target, only if I slow down my pedaling a lot then it would finally wake up and set the level to 13 or 16. However it would quickly dropped down the 5 (my min resistance setting) as soon as I stand on the pedal and step on it. Not sure if I messed up other settings along the way so I captured the log this morning and hope Roberto can help share some insight on that. 

@cagnulein , attached is the log would should showed that the resistance doesn't change when app is targeting ~160+ watt while my output is only 96 or so.  Hope u  can find what I screwed up and help correct it. Tks

[debug-Sat_Mar_2_11_18_13_2024.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/14470114/debug-Sat_Mar_2_11_18_13_2024.log.zip)

**Comment by cagnulein** [comment]
thanks i will check it asap
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle ore 17:46 jli3388 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@jli3388 the watt table that I added it was stricty releated to the watt gain inserted from @markgoodrich (i guess 0.5 right?). So i suggest to use the same 0.5 value

Also, if you want guys, we can try the new dynamic power table that i'm developping here #2175

**Comment by jli3388** [comment]
@cagnulein I will set the Watt Gain to 0.5 tonight and give it a try.

What's the procedure to get the version with the dynamic power table?

**Comment by cagnulein** [comment]
ok @jli3388 let me know how it goes

> What's the procedure to get the version with the dynamic power table?

it's quite easy in case. i will add your bike in the candidate list for this and we will try it.

**Comment by markgoodrich** [comment]
I reduced watt gain to 0.45, don't know if the offset goes to hundredths,
so it may be 0.4.  Closer to my perceived effort and speed on the road.  I
think it's likely an individual thing.  I also have starting resistance set
to 9.

**Comment by markgoodrich** [comment]
Sorry, I don't understand how to access that power table.

**Comment by markgoodrich** [comment]
Oh.  Maybe I understand...:)   But still leave watt gain offset as I've got
it?

**Comment by cagnulein** [comment]
yes :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 mar 2024 alle 18:11 markgoodrich ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@jli3388 any news?

**Comment by jli3388** [comment]
@cagnulein , sorry for the delay. Was pretty busy with work.

I tried again setting the Watt gain to 0.5 and then 0.3.  Similar experience, the MyWhoosh app would correctly indicated the watt is way under the the wanted watt but then resistance would still be at a relatively low setting and causing spinout.

Attaching the debug log from last night here, hope you can work some magic and make it work. 
I will try something else in the meantime or simply use it in manual mode.
[debug-Sun_Mar_10_23_52_29_2024.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/14565782/debug-Sun_Mar_10_23_52_29_2024.log.zip)

**Comment by cagnulein** [comment]
@jli3388 perfect! so let's go with the dynamic power table, i will share you a link for this!

**Comment by cagnulein** [comment]
@jli3388 done! 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8245160853

What you have to do:

in this version qz is collecting in real time watt values from your bike along with cadence and resistance. So give a quick spin to all the resistance and all the cadence to fill the internal table.
Then enable the erg mode in qz and on zwift as well and the magic should come!
Let me know if you have any questions

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@markgoodrich download it from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/8245160853/artifacts/1317711068
then save your settings and put the settings saved on a different directory in order to have a backup
then remove qz, and install the new one downloaded
then import the new setting and 

"in this version qz is collecting in real time watt values from your bike along with cadence and resistance. So give a quick spin to all the resistance and all the cadence to fill the internal table.
Then enable the erg mode in qz and on zwift as well and the magic should come!
Let me know if you have any questions"

**Comment by markgoodrich** [comment]
Thanks, I'll try it tomorrow.

**Comment by markgoodrich** [comment]
I'm embarrassed to say, once again, I am stumped. After several tries I
managed to download the file, named fdroid-android-trial.zip but when I try
to open it so I can install it, I get notice:  "can't open file".

**Comment by cagnulein** [comment]
you have to unzip it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 13 mar 2024 alle 13:27 markgoodrich ***@***.***>
ha scritto:

**Comment by markgoodrich** [comment]
I knew that, I kept banging my head against the wrong wall, finally found
the right folder.  Face red again.

**Comment by markgoodrich** [comment]
I gave up on the beta. I am too unfamiliar with tech stuff to be able to
figure out what to do.  I installed it but couldn't figure out what to do
with the "quick spin in each resistance level" instruction.  I got on the
bike, QZ running, and pedaled, turning the resistance up on step at a time,
but I couldn't see any difference, and starting resistance defaulted to 1
instead of 9 as I had set it.  Is it just for workouts?  Do I leave Erg
mode on all the time, even for rides?  See?  I need Instructions For
Dummies.

**Comment by cagnulein** [comment]
> I gave up on the beta. I am too unfamiliar with tech stuff to be able to figure out what to do. 

so i have to explain it or not? I don't understand your "i gave up"

> I installed it but couldn't figure out what to do with the "quick spin in each resistance level" instruction. I got on the bike, QZ running, and pedaled, turning the resistance up on step at a time, but I couldn't see any difference, and starting resistance defaulted to 1 instead of 9 as I had set it. Is it just for workouts? Do I leave Erg mode on all the time, even for rides? See? I need Instructions For Dummies. 

what I added in this version is the fact that the ERG table (only the ERG table) is calculated dinamically. So the changes is affected only when you're doing a workout on zwift with the erg mode enabled.

For the resistance to 9, did you reload the settings when you updated the version?

**Comment by jli3388** [comment]
@cagnulein,

do u have the link to download the beta for iOS? I am on ipad?  Last time I believe it was thru testFlight, should it be the same this time around?

**Comment by markgoodrich** [comment]
I'm sorry, I just saw this, Roberto.  I stumbled across a great deal on a
used Stages bike last weekend, and have been riding it, connected directly
to Zwift.  You've been a huge help, and I really appreciate all the efforts
you went to to try to get this luddite to understand how to use QZ with
that Merach bike.  I don't think I need QZ for the Stages.

**Comment by cagnulein** [comment]
no problem @markgoodrich i guess it's better for you .

qz can give you virtual gears on zwift even for stages bikes and also peloton support if you would like to try

**Comment by markgoodrich** [comment]
Thanks for the tip!
