### ISSUE TITLE
Echelon bike Ex3[BUG]

### ISSUE THREAD

**Issue by Lintlicker28** [cagnulein/qdomyos-zwift#2094]
**Describe the bug**
When I start the peloton workout the qz pop window doesn't pop on android.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi i need the debug log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 feb 2024 alle 15:19 Lintlicker28 ***@***.***>
ha scritto:

**Comment by Lintlicker28** [comment]
Where do I find the debug log?

**Comment by cagnulein** [comment]
it's described here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
@Lintlicker28 Any news?
