### ISSUE TITLE
[BUG] no data coming through from Woodway 4Front

### ISSUE THREAD

**Issue by DanMarshman** [cagnulein/qdomyos-zwift#2095]
**Describe the bug**
Hi Roberto,
Thanks for all your assistance today. Debug and screen grabs attached.

[debug-Sat_Feb_3_16_48_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14152225/debug-Sat_Feb_3_16_48_50_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_6425](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/5f9d1589-76f3-4e11-beb1-d8b63617e020)
![IMG_6424](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/544006b4-3f50-45d5-b222-f4fce836a513)
![IMG_6423](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/15bc25dd-da6e-4e26-bec6-7043c8e2fec2)
![IMG_6422](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/f256cfcb-7413-45ff-b0c8-e405971779ab)
![IMG_6421](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/7878c2cc-3026-4992-8e5b-b6ecf5eeffbb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
very strange: let's try to understand this. in the experimental settings, disable the virtual bluetooth device and restart qz 

let me know if it's the same and share a new log

thanks

**Comment by cagnulein** [comment]
did you try?

**Comment by DanMarshman** [comment]
No sorry been away with family commitments, will feedback tomorrow.

**Comment by DanMarshman** [comment]
Hi, [I turned virtual Bluetooth and restarted, it didn’t make any difference. Debug file attached. Regards Dan debug-Sun_Feb_4_13_02_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14156855/debug-Sun_Feb_4_13_02_12_2024.log)

**Comment by cagnulein** [comment]
Ok I will check it tomorrow, I'm out with my family now! Have a nice Sunday!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle 14:07 DanMarshman ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok i guess i understood the issue.
i will send a new beta later today.
thanks for your patience

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle 15:13 cagnulein ***@***.***> ha
scritto:

**Comment by DanMarshman** [comment]
Hi Roberto,
I’ve installed the new beta but get the same issue as before.  Regards Dan
[debug-Sun_Feb_4_18_41_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14157910/debug-Sun_Feb_4_18_41_24_2024.log)

**Comment by cagnulein** [comment]
ok got the issue now, i'm doing another one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 19:47 DanMarshman <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
if i'm right this treadmill can't change the inclination or speed from
bluetooth. do you have any other apps that can do this to your treadmill?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 19:49 cagnulein ***@***.***> ha
scritto:

**Comment by DanMarshman** [comment]
Hi Roberto,

I’ve only had paired so the speed is broadcast directly to Zwift. Rather than my previous treadmill where I’d use the Runn sensor to broadcast the speed. No never had any apps that could control the speed or incline.

**Comment by cagnulein** [comment]
ok so is there any app from the manufacturer? anyway let me send this
version to check if at least I can read read the metrics. but if we want
auto inclination we need to find an app that can control it. for example
kinomap?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 20:17 DanMarshman <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
you can disable the ftms treadmill setting now, it's another protocol for
you treadmill that's why it wasn't working so far

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 20:18 cagnulein ***@***.***> ha
scritto:

**Comment by DanMarshman** [comment]
Hi Roberto,

I’ve loaded the new app and ran it once with forms in and once off. As far as I’m aware there is no app for controlling the Woodway remotely. 

[debug-Mon_Feb_5_12_28_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14171606/debug-Mon_Feb_5_12_28_52_2024.log)
[debug-Mon_Feb_5_08_54_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14171609/debug-Mon_Feb_5_08_54_36_2024.log)

**Comment by cagnulein** [comment]
ok i'm seeing some metrics that i need to parse. i will do tomorrow anyway i guess it's not controllable at all.
i will update you tomorrow

**Comment by cagnulein** [comment]
ok i handled the speed, if you can provide me also a log where you change the inclination I can add it too. I'm sending a new one today. Leave the ftms treadmill disabled.
Thanks

**Comment by DanMarshman** [comment]
Hi Roberto,

Sorry for the delay the week got away from me, here’s a log file it should have incline adjustments in it. Regards Dan

[debug-Fri_Feb_9_16_45_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14224247/debug-Fri_Feb_9_16_45_42_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP!

**Comment by cagnulein** [comment]
hi thanks, do you remember which incline value set in this log?

**Comment by cagnulein** [comment]
note for me (16th byte)
could be @DanMarshman 1% then 5% then 4% and so on?

**Comment by cagnulein** [comment]
i guess so, i'm sending you this in the meantime!

**Comment by cagnulein** [comment]
version sent

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle 17:51 DanMarshman ***@***.***>
ha scritto:

**Comment by DanMarshman** [comment]
Hi Roberto,

your assumption La were all correct some reason it didn’t log it but screen grab attached 10kph 6.0%. Regards Dan
![IMG_6443](https://github.com/cagnulein/qdomyos-zwift/assets/158763074/05a5b3cc-b1c1-49a7-84e4-fbf082994a35)

**Comment by cagnulein** [comment]
What do you mean? 6% wasn't correct?

Could you please share a log and tell me what you did in the log session?

**Comment by DanMarshman** [comment]
Hi Roberto,

just to confirm it is all working correctly what is being displayed is true to what the treadmill is set to. For some reason it’s not saving log files in this version, is it something I need to switch back on? Regards Dan

**Comment by cagnulein** [comment]
Debug log under the experimental settings is enabled?
What do you see in the qz folder?

**Comment by DanMarshman** [comment]
Hi, 
Cleared the history and ran it again and it worked. 10kph 0% then up to 6% and then back to 0% log attached. Regards Dan
[debug-Sun_Feb_18_15_22_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14323067/debug-Sun_Feb_18_15_22_36_2024.log)

**Comment by cagnulein** [comment]
ok so what should I check in the log? which is the remaining error?

**Comment by DanMarshman** [comment]
Hi Roberto,

No errors it’s all working, If I understand from the previous messages it’s just that auto incline via Zwift won’t work with this treadmill via the app.

**Comment by cagnulein** [comment]
yeah unfortunately the firmware of the treadmill doesn't have this ability :(
