### ISSUE TITLE
[BUG] Inaccurate Data from Bowflex BXT216

### ISSUE THREAD

**Issue by amartya118** [cagnulein/qdomyos-zwift#2096]
**Describe the bug**
I have just completed my first activity using the qzapp, however, the data is quite inaccurate. Connecting to my Bowflex BXT216 was seamless but I noticed the odometer was way off from the start. Speed and incline were accurate though. I have attached some photos below. I ran 0.5 miles in 5:14 to test again after turning on the debug log. When the run synced to Strava it said 2.39 miles at 2:10/mi 🤔 this is a km-to-miles conversion issue or something. Also when I completed the activity, QZApp showed a picture of a bike.

**Expected behavior**
Accurate odometer data in miles.

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: IOS 17.3

GitHub says the debug file is too big so I have attached it in a Google Drive link below:

[](https://drive.google.com/drive/folders/1zLwEyKzgsBuxjqGWRBS0NTmLoDzJGSnY?usp=sharing)

I have also attached screenshots of my treadmill display showing the actual distance, a screenshot of qzapp after the run, and the Strava synced activity.

  
![IMG_1458](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/0b47c2cf-a109-44ce-9a72-dbb965240d2b)
![IMG_1459](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/9f23a934-7859-476b-b2f2-114e783e7812)
![IMG_1460](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/dc418810-5490-4a10-9d77-fdbb51f22aac)

**Comment by cagnulein** [comment]
Hi I don't see the logs yet anyway you can zip them and put it here

**Comment by amartya118** [comment]
> Hi I don't see the logs yet anyway you can zip them and put it here

I have zipped the file now. Thank you.


[debug-Sat_Feb_3_22_55_45_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14157550/debug-Sat_Feb_3_22_55_45_2024.zip)

**Comment by cagnulein** [comment]
ok the problem seems it was about some strange speed values (1000km/h!).
just fixed now
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by amartya118** [comment]
> ok the problem seems it was about some strange speed values (1000km/h!).
> 
> just fixed now
> 
> send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

Send the email. Cheers 😄

**Comment by cagnulein** [comment]
perfect, i'm uploading it now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 18:10 Amartya Poovaiah <
***@***.***> ha scritto:

**Comment by amartya118** [comment]
Will run later today...I'll let you know in several hours 😄👍🏽

**Comment by cagnulein** [comment]
Sounds good, thanks!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 18:32 Amartya Poovaiah <
***@***.***> ha scritto:

**Comment by amartya118** [comment]
Hi Roberto,

Unfortunately, the issue is still present. Within 10 seconds on the treadmill, the odometer immediately read to miles. I have attached another debug report.

Many thanks 👍🏽
[debug-Mon_Feb_5_19_51_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14184183/debug-Mon_Feb_5_19_51_16_2024.log)

**Comment by cagnulein** [comment]
hi, you didn't update the app. it's the store version. don't you get the
update?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 18:34 Amartya Poovaiah <
***@***.***> ha scritto:

**Comment by amartya118** [comment]
I don't see the update on the Apple App Store, do I have to do something on qdomyos?

Thank you

**Comment by cagnulein** [comment]
> > ok the problem seems it was about some strange speed values (1000km/h!).
> > 
> > just fixed now
> > 
> > send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
> 
> Sent the email. Cheers 😄

i guess i never received this. can you please send me again the email?

**Comment by amartya118** [comment]
amartyadeveloper@gmail.com

**Comment by cagnulein** [comment]
sent, let me know

**Comment by amartya118** [comment]
Received! Will run later and brief you on the results.

I've updated the app now.

Thanks!

**Comment by cagnulein** [comment]
Awesome, thanks!


Il giorno mar 6 feb 2024 alle 19:22 Amartya Poovaiah <
***@***.***> ha scritto:

**Comment by amartya118** [comment]
So I ran for about 2 minutes and initially, I got the same results...however, qzapp uploaded 2 activities to Strava, the first one was inaccurate as before but the second one seemed correct oddly. 
![w](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/8d6dde28-a6cd-4cb4-826f-8d398536222b)
![unnamed (18)](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/a7451aea-39c9-407f-867b-5a092b85f9fa)
![unnamed (17)](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/90ce6e37-128e-4752-8805-8a9f29712ac6)

**Comment by cagnulein** [comment]
do you have the debug log?

**Comment by amartya118** [comment]
I didn't find the one from the previous post but I ran 0.2 miles again and got the debug log. However, only one strava activity was uploaded. It seems there is still an issue with the speed values.
[debug-Tue_Feb_6_11_17_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14185177/debug-Tue_Feb_6_11_17_42_2024.log)
![unnamed (20)](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/5eb400c5-f1d8-4642-a0d4-1899b18035b3)
![unnamed (19)](https://github.com/cagnulein/qdomyos-zwift/assets/156844632/5fdc0065-f48c-4fe4-8826-e5cdb5ccab5d)

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 20:27 Amartya Poovaiah <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
got the issue, i will send you another one later today!
thanks for the feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle ore 20:29 cagnulein ***@***.***> ha
scritto:

**Comment by amartya118** [comment]
Thanks Roberto!

**Comment by cagnulein** [comment]
new version sent!

**Comment by cagnulein** [comment]
@amartya118 any news?

**Comment by amartya118** [comment]
> @amartya118 any news?

Distance is fixed now! Sorry for not getting back to you. However, power tracking and cadence seems a bit off, I don't even know if my treadmill supports it. I will attached a debug log tomorrow. Thanks again.

**Comment by cagnulein** [comment]
ok let me know

**Comment by cagnulein** [comment]
Any news @amartya118 ?

**Comment by amartya118** [comment]
Everything works fine now! Thanks. I guess it just took a few runs to adjust.
