### ISSUE TITLE
[REQ] Support for Kingsmith WalkingPad R2 TRR2F

### ISSUE THREAD

**Issue by ianpogi5** [cagnulein/qdomyos-zwift#2097]
**Is your feature request related to a problem? Please describe.**
I bought the android app but it does not connect to my treadmill.

**Describe the solution you'd like**
Add support for Kingsmith WalkingPad R2 with model TRR2F.

**Describe alternatives you've considered**
Followed all the instructions in the app but still it did not detect.

**Additional context**

![20240131_173913](https://github.com/cagnulein/qdomyos-zwift/assets/1063875/98f1bf48-ae2e-4c69-8ba1-9e5a3b3f875b)

**Comment by cagnulein** [comment]
hi @ianpogi5 can you show me what you see from the free app nrfconnect?
let me know!

**Comment by ianpogi5** [comment]
@cagnulein ![Screenshot_20240206_074826_nRF Connect.jpg](https://github.com/cagnulein/qdomyos-zwift/assets/1063875/9e4e6ce9-8de4-4714-95fe-7f13163003a3)

![Screenshot_20240206_074844_nRF Connect.jpg](https://github.com/cagnulein/qdomyos-zwift/assets/1063875/a3a83742-8fbb-4b9c-800c-1cd6caec53a3)

![Screenshot_20240206_074915_nRF Connect.jpg](https://github.com/cagnulein/qdomyos-zwift/assets/1063875/f5ceef67-4edb-4023-88f8-97864023de85)

![Screenshot_20240206_074924_nRF Connect.jpg](https://github.com/cagnulein/qdomyos-zwift/assets/1063875/7529211f-7c44-437b-9dae-48312e15be0a)

**Comment by cagnulein** [comment]
@ianpogi5 good news! i already added this to the beta. join it from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Let me know!

**Comment by ianpogi5** [comment]
@cagnulein it works!

https://www.strava.com/activities/10711305891

**Comment by ianpogi5** [comment]
Before I close, I did have an issue with the training plan.

I created this xml below and loaded to the app:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rows>
    <row duration="00:01:00" speed="2" />
    <row duration="00:01:00" speed="2.5" />
    <row duration="00:01:00" speed="3" />
    <row duration="00:01:00" speed="3.5" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="7" />
    <row duration="00:00:30" speed="3" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="4" />
    <row duration="00:01:00" speed="3.5" />
    <row duration="00:01:00" speed="3" />
    <row duration="00:01:00" speed="2.5" />
    <row duration="00:01:00" speed="2" />
</rows>
```

I was expecting that the speed of the treadmill will change for each duration. I am not sure if it's a bug of the implementation or my understanding on the training plan usage is wrong. I also tried ticking the **Treadmill Speed Forcing** but it still did not auto change the speed of the treadmill.

**Comment by ianpogi5** [comment]
Sorry I'm reopening again. I accidentally closed it earlier.

**Comment by cagnulein** [comment]
you missed the forcespeed tag

check this for reference
https://github.com/cagnulein/qdomyos-zwift/blob/master/train-programs-examples/calorie-barbara.xml


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 feb 2024 alle 04:28 Ian Dela Cruz ***@***.***>
ha scritto:

**Comment by ianpogi5** [comment]
All working! Thanks @cagnulein !

**Comment by cagnulein** [comment]
great! if you can i really appreciate a coffee or a patreon subscription to substain this open source project! https://buymeacoffee.com/cagnulein https://www.patreon.com/cagnulein
