### ISSUE TITLE
[SUGGESTION] Code organisation

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#2102]
@cagnulein 

Would you be interested in a reorganisation of the source code into folders, with a structure akin the test project.

e.g.

src\devices\bluetooth.*
src\devices\bluetoothdevice.*
src\devices\activiotreadmill\activiotreadmill.*
...
src\characteristics\characteristic*.*

src\virtualdevices\virtual*.*

I think this would make navigation easier, but on the downside, referencing the header files would need the foldername added.

**Comment by cagnulein** [comment]
yes sure i guess the only changes needed are

include files
pri project file
and probably the xcode project that i can fix


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 feb 2024 alle 19:10 David Mason ***@***.***>
ha scritto:

**Comment by drmason789** [comment]
@cagnulein I noticed there is a devices/kmlworkout folder now, with a couple of files that may not be used - it's not a "device" anyway so I think it's a typo/artifact of one of my bulk operations.  Perhaps this folder could be deleted?

**Comment by cagnulein** [comment]
done, thanks
