### ISSUE TITLE
Issues creating new rower profile

### ISSUE THREAD

**Issue by Wavescrash** [cagnulein/qdomyos-zwift#2104]
Initially I was unable to get certain rower related tiles to show up but I think I have that solved-It looks like having virtual rower left on by accident initially prevented those tiles from showing up for some reason. Now other than figuring which tiles I want to display and in what order (which I will play around  with), the profile is not broadcasting my heart rate from qz to the firestick I play the peloton workouts on.  
thank you for reviewing my debug file!
[Uploading debug-Tue_Feb_6_14_58_39_2024.log…]()

**Comment by cagnulein** [comment]
hi @Wavescrash the log is corrupted. you have to wait the finish of the upload before clicking comment

let me know

**Comment by Wavescrash** [comment]
Thanks. Here it is again
[debug-Tue_Feb_6_14_58_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14201451/debug-Tue_Feb_6_14_58_39_2024.log)

**Comment by cagnulein** [comment]
thanks i will check tomorrow

**Comment by cagnulein** [comment]
got the error.
note for me: fitplusbike

i will send you a new one tomorrow
thanks for the feedback

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 feb 2024 alle 21:57 Wavescrash ***@***.***>
ha scritto:

**Comment by Wavescrash** [comment]
Thanks so much!

**Comment by cagnulein** [comment]
done, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks!

**Comment by cagnulein** [comment]
hi @Wavescrash are we ok with this?

**Comment by Wavescrash** [comment]
Thank you for checking in.  Something is still funny with three heart rate
connection. I can not get my streaming devices to pick up the Qz broadcast
(either firestick or Google TV). I have been sick so haven't had a chance
to try again but I hope to have time this afternoon. I will run a debug log
when I use it.

**Comment by cagnulein** [comment]
No worries, thanks for the update!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle ore 14:45 Wavescrash <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
for the first issue, first of all do you see the hr on the qz watch app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 21:03 Wavescrash ***@***.***>
ha scritto:

**Comment by Wavescrash** [comment]
Yes the watch face gives me a bpm number

**Comment by cagnulein** [comment]
ok is the iphone qz app open at the same time? the iphone is routing the hr
from apple watch to ipad so must be open and alive (even without
connectivity to a fitness device)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 21:21 Wavescrash ***@***.***>
ha scritto:

**Comment by Wavescrash** [comment]
Oh no it is not. That must be the issue.

**Comment by cagnulein** [comment]
Give it a try and let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 21:39 Wavescrash ***@***.***>
ha scritto:

**Comment by Wavescrash** [comment]
Thank you! That worked as fast as the apple watch as a hr monitor but I
still can't get it to broadcast to streaming devices anymore.

**Comment by cagnulein** [comment]
Now the issue is that you have the virtual device setting disabled in the experimental settings 

Enable it and restart qz

Let me know

**Comment by Wavescrash** [comment]
I tried it and it worked for the fire stick, which is great, but the
googleTV is in the room with the exercise equipment and it is not showing
up as an option. Thank you for your help, do you have any other ideas?

**Comment by Wavescrash** [comment]
I will try to uninstall and reinstall the peloton app on GoogleTV and if
that doesn’t work I will ask the Facebook group if they have any ideas.
Thank you for your help and a great app!

**Comment by Wavescrash** [comment]
No  I did not.
