### ISSUE TITLE
Bike ERG mode not working TDF 4.0

### ISSUE THREAD

**Issue by Blubob101** [cagnulein/qdomyos-zwift#2105]
**Describe the bug**
When I connect the bike to QZ with Zwift workout/Erg mode on I am unable to control anything on the bike through the QZ app.
When I toggle the Zwift workout/Erg mode switch off, I am able to control inclination through the QZ app.
When I connect to MyWhoosh, I get metrics for the bike but no automatic resistance or inclination control.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
a debug log could be useful.
anyway in qz you have to enable the zwift erg mode setting and on the bike you have to stay to the main window, not to the manual workout window

let me know!

**Comment by Blubob101** [comment]
[debug-Wed_Feb_7_11_50_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199869/debug-Wed_Feb_7_11_50_32_2024.log)
[debug-Wed_Feb_7_11_50_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199870/debug-Wed_Feb_7_11_50_38_2024.log)
[debug-Wed_Feb_7_11_50_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199871/debug-Wed_Feb_7_11_50_54_2024.log)
[debug-Wed_Feb_7_09_34_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199872/debug-Wed_Feb_7_09_34_48_2024.log)
[debug-Wed_Feb_7_11_50_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199873/debug-Wed_Feb_7_11_50_35_2024.log)
[Uploading debug-Wed_Feb_7_11_53_26_2024.log…]()

**Comment by Blubob101** [comment]
[debug-Wed_Feb_7_11_52_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199881/debug-Wed_Feb_7_11_52_30_2024.log)
[debug-Wed_Feb_7_11_50_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14199883/debug-Wed_Feb_7_11_50_44_2024.log)

**Comment by cagnulein** [comment]
@Blubob101 i checked the logs but the only one with a session from zwift is the 

> debug-Wed_Feb_7_09_34_48_2024.log

and in this session you weren't do a workout but a regular zwift ride, or at least zwift it was sending like a zwift classic ride.

so i suggest to recreate the issue with a workout and send me a screenshot and the log of the issue!
let me know!

**Comment by cagnulein** [comment]
in this log, as i said, there is only 1 session from mywhoosh (i can't know if it's my whoosh or zwift in the log, they act the same from the QZ point of view) but it's a free ride not a workout. Are you able to recreate the issue again with a new log?

**Comment by Blubob101** [comment]
So it has to be a workout and not a free ride? Erg should work the same in either mode, it does on my spin bike.

**Comment by Blubob101** [comment]
[Uploading debug-Thu_Feb_8_08_18_13_2024.log…]()

**Comment by cagnulein** [comment]
the log is corrupted. you have to wait the finish of the upload before commenting



> So it has to be a workout and not a free ride? Erg should work the same in either mode, it does on my spin bike.

yes it's not about QZ, it's about mywhoosh. mywhoosh sends the ERG information only when it does a workout.

**Comment by Blubob101** [comment]
Just did a short ride in workout mode, still no automatic resistance, this time I also could not shift into different gears while riding using the handlebar shifters

**Comment by Blubob101** [comment]
[Uploading debug-Thu_Feb_8_08_18_13_2024.log…]()

**Comment by cagnulein** [comment]
the log is corrupted. you have to wait the finish of the upload before commenting

also check my previous comment

**Comment by Blubob101** [comment]
[Uploading debug-Thu_Feb_8_09_00_56_2024.log…]()

**Comment by cagnulein** [comment]
the log is corrupted! Please, wait the finish of the upload before pressing the button "comment"

**Comment by Blubob101** [comment]
[debug-Thu_Feb_8_09_31_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211336/debug-Thu_Feb_8_09_31_56_2024.log)
[debug-Thu_Feb_8_09_19_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211342/debug-Thu_Feb_8_09_19_43_2024.log)
[debug-Thu_Feb_8_09_22_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211343/debug-Thu_Feb_8_09_22_56_2024.log)
[debug-Thu_Feb_8_09_18_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211352/debug-Thu_Feb_8_09_18_36_2024.log)
[debug-Thu_Feb_8_08_10_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211353/debug-Thu_Feb_8_08_10_07_2024.log)
[debug-Thu_Feb_8_08_54_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211354/debug-Thu_Feb_8_08_54_17_2024.log)
[debug-Thu_Feb_8_09_20_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211355/debug-Thu_Feb_8_09_20_33_2024.log)
[debug-Thu_Feb_8_08_09_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211356/debug-Thu_Feb_8_08_09_57_2024.log)
[debug-Thu_Feb_8_09_00_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211357/debug-Thu_Feb_8_09_00_56_2024.log)
[debug-Thu_Feb_8_09_21_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211363/debug-Thu_Feb_8_09_21_03_2024.log)
[debug-Thu_Feb_8_08_52_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211364/debug-Thu_Feb_8_08_52_33_2024.log)
[debug-Thu_Feb_8_09_22_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211366/debug-Thu_Feb_8_09_22_33_2024.log)
[debug-Thu_Feb_8_08_11_15_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211367/debug-Thu_Feb_8_08_11_15_2024.log)
[debug-Thu_Feb_8_08_50_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211369/debug-Thu_Feb_8_08_50_14_2024.log)
[debug-Thu_Feb_8_08_18_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14211370/debug-Thu_Feb_8_08_18_13_2024.log)

**Comment by cagnulein** [comment]
Hi @Blubob101  I checked all of them and mywhoosh in any of them is asking for a target power. Only changes the grade. Are you sure you did a workout? Maybe it's simply a bug in mywhoosh. DId you try to fill a report to them? Did you also try zwift in the same condition? On zwift I know for sure that it's working.

If it also working for you on zwift, it means that 100% is a MyWhoosh bug

**Comment by Blubob101** [comment]
It's not changing the grade or the resistance as I ride.

**Comment by Blubob101** [comment]
I didn't do a full workout just a couple of minutes on each log

**Comment by cagnulein** [comment]
> It's not changing the grade or the resistance as I ride.

it didn't because you have the zwift erg mode setting enabled. You have to disable if mywhoosh only send the grade.

**Comment by Blubob101** [comment]
[debug-Thu_Feb_8_17_27_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217735/debug-Thu_Feb_8_17_27_10_2024.log)
[debug-Thu_Feb_8_16_32_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217737/debug-Thu_Feb_8_16_32_59_2024.log)
[debug-Thu_Feb_8_17_42_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217739/debug-Thu_Feb_8_17_42_37_2024.log)
[debug-Thu_Feb_8_16_31_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217741/debug-Thu_Feb_8_16_31_23_2024.log)
[debug-Thu_Feb_8_17_26_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217742/debug-Thu_Feb_8_17_26_10_2024.log)
[debug-Thu_Feb_8_17_03_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217743/debug-Thu_Feb_8_17_03_54_2024.log)
[debug-Thu_Feb_8_17_49_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14217749/debug-Thu_Feb_8_17_49_05_2024.log)

**Comment by cagnulein** [comment]
@Blubob101 the issue is that you have the zwift resistance gain to 0 in the bike setting. set it to 1 and try again
Let me know!

**Comment by Blubob101** [comment]
That did not work either, I feel like I do feel automatic resistance sometimes for a second but then it stops

**Comment by cagnulein** [comment]
please attach always a debug log otherwise it's impossible to understand the issue

**Comment by Blubob101** [comment]
[debug-Thu_Feb_15_09_03_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302365/debug-Thu_Feb_15_09_03_41_2024.log)
[debug-Thu_Feb_15_09_11_12_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302367/debug-Thu_Feb_15_09_11_12_2024.log)
[debug-Thu_Feb_15_09_37_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302369/debug-Thu_Feb_15_09_37_08_2024.log)
[debug-Thu_Feb_15_10_17_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302370/debug-Thu_Feb_15_10_17_20_2024.log)
[debug-Thu_Feb_15_09_37_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302371/debug-Thu_Feb_15_09_37_48_2024.log)
[debug-Thu_Feb_15_09_06_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302372/debug-Thu_Feb_15_09_06_34_2024.log)
[debug-Thu_Feb_15_12_27_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302374/debug-Thu_Feb_15_12_27_00_2024.log)
[debug-Thu_Feb_15_12_47_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302376/debug-Thu_Feb_15_12_47_50_2024.log)
[debug-Thu_Feb_15_13_12_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302377/debug-Thu_Feb_15_13_12_17_2024.log)
[debug-Thu_Feb_15_10_07_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302378/debug-Thu_Feb_15_10_07_22_2024.log)
[debug-Thu_Feb_15_09_36_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302381/debug-Thu_Feb_15_09_36_36_2024.log)
[debug-Thu_Feb_15_14_25_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302382/debug-Thu_Feb_15_14_25_20_2024.log)
[debug-Thu_Feb_15_12_12_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302385/debug-Thu_Feb_15_12_12_05_2024.log)
[debug-Thu_Feb_15_14_15_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302388/debug-Thu_Feb_15_14_15_25_2024.log)
[debug-Thu_Feb_15_09_21_22_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302389/debug-Thu_Feb_15_09_21_22_2024.log)
[debug-Thu_Feb_15_13_31_18_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302391/debug-Thu_Feb_15_13_31_18_2024.log)
[debug-Thu_Feb_15_10_28_01_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302392/debug-Thu_Feb_15_10_28_01_2024.log)
[debug-Thu_Feb_15_10_31_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302394/debug-Thu_Feb_15_10_31_51_2024.log)
[debug-Thu_Feb_15_09_31_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302395/debug-Thu_Feb_15_09_31_43_2024.log)
[debug-Thu_Feb_15_09_17_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302396/debug-Thu_Feb_15_09_17_42_2024.log)
[debug-Thu_Feb_15_13_12_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302397/debug-Thu_Feb_15_13_12_50_2024.log)
[debug-Thu_Feb_15_10_23_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302398/debug-Thu_Feb_15_10_23_58_2024.log)

**Comment by Blubob101** [comment]
On my last ride everything worked like it should have!
[debug-Tue_Feb_27_15_52_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14426176/debug-Tue_Feb_27_15_52_20_2024.log)

**Comment by Blubob101** [comment]
[debug-Wed_Feb_28_10_31_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14437557/debug-Wed_Feb_28_10_31_43_2024.log)

**Comment by cagnulein** [comment]
what should I look? please always add a description. i'm receiving hundreds
of email every day about qz, i can't remember everything
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 feb 2024 alle ore 17:41 Blubob101 ***@***.***>
ha scritto:
