### ISSUE TITLE
[BUG]values for speed, cadence and watts still remain at 0 or are displayed from time to time for 1-2 seconds in the qdomyoszwift app and then fall off

### ISSUE THREAD

**Issue by bsxsp** [cagnulein/qdomyos-zwift#2106]
in iOS version 2.15.4 and also the current beta 2.16.41 of qdomyoszwift app I have since iOS 17.3 update iPhone 15ProMax permanent interruptions of the transmission of speed, cadence and watts, although the app shows a permanent uninterrupted connection to Yesoul S3 and Resistance is also displayed permanently without interruption. So unfortunately I can not use Zwift at the moment, because the values are not transferred. Sometimes displayed again in the qdomyoszwift app for a few seconds in order to fall off permanently again.

I tested the "Kinomap" app iOS-Version to connect directly to Yesoul S3 on iOS 17.3 without qdomyoszwift app. There are no interruptions in data transmission there.  Can you please help me? The setup with the qdomyoszwift app ran error-free for months!

![IMG_0996](https://github.com/cagnulein/qdomyos-zwift/assets/159296576/408a0255-863e-48ca-9e2c-583c0f1dcdb7)

**Desktop (please complete the following information):**
 - OS: MacOS 14.3 Sonoma
 - Zwift for MacSilicon 1.57.3

**Smartphone (please complete the following information):**
 - Device: iPhone 15 ProMax
 - OS: 17.3
 - Version 17.3
 
 SpeedBike Yesoul S3

**Append a debug log**
[debug-Mi__Feb__7_17_10_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14196641/debug-Mi__Feb__7_17_10_47_2024.log)

**Comment by cagnulein** [comment]
thanks i will check tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 feb 2024 alle 17:43 bsxsp ***@***.***> ha
scritto:

**Comment by bsxsp** [comment]
You mean with mac version log a Zwift log ?

**Comment by cagnulein** [comment]
Qz Mac version

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 feb 2024 alle 17:46 bsxsp ***@***.***> ha
scritto:

**Comment by bsxsp** [comment]
So far I have never used a QZ Mac version. Where can I download them? Only the iPad version of QZ appears in the MacOS app store. Do you mean this one?

This morning I connected Zwift directly on the iPhone to the Yesoul S3, the HRV via AppleWatch Ultra2 with the original Zwift app.

Ales runs without complaint. Speed, cadence and watts are also recorded without interruption in Zwift.

**Comment by cagnulein** [comment]
> So far I have never used a QZ Mac version. Where can I download them? Only the iPad version of QZ appears in the MacOS app store. Do you mean this one?

if you have a mac silicon you can simply download qz from the app store directly!

i'm checking your log right now

**Comment by cagnulein** [comment]
@bsxsp this log is just a 5 minute log and the metrics are fine. Do you have a log of the issue?
i also see that you have the dircon setting in the experimental settings, disabled, why? enable it use the wahoo virtual device from qz on zwift

Let me know

**Comment by bsxsp** [comment]
During the cycling at the log, the cancellations of speed, cardence and watts should be visible?! For me in this log the values actually fell to 0 when stepping as can be seen in the screenshot.

I connect the Mac to the Internet via personal hotspot via the iPhone with 5G network and not via WLAN in this setup.

Therefore, I obviously can't see and activate the wahoo virtual device in Zwift on the Mac.

what do you mean with „dircon setting in the experimental settings is disabled“?

The log is only 5 minutes because it was a test drive to show the problem.

**Comment by cagnulein** [comment]
> During the cycling at the log, the cancellations of speed, cardence and watts should be visible?! For me in this log the values actually fell to 0 when stepping as can be seen in the screenshot.

yes it should be visible if you see in the UI of qz, but I don't understand what I should see. I mean, from what you told me it seems that QZ lost the connection from the bike, instead, in the log the connection is fine and the bike is sending me real data all the time. 

In the log i see the cadence going to 0, but it's the bike that it's sending 0

for example

```
Mi. Feb. 7 17:12:44 2024 1707322364782 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 7c 4a 00 19 00 1c 02 fb ff"
Mi. Feb. 7 17:12:44 2024 1707322364785 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetoothdevice.cpp void bluetoothdevice::update_hr_from_external() Current Heart from Apple Watch:  "86"
Mi. Feb. 7 17:12:44 2024 1707322364787 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Resistance: 74"
Mi. Feb. 7 17:12:44 2024 1707322364788 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 16.6583"
Mi. Feb. 7 17:12:44 2024 1707322364789 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Calculate Distance: 0.14334"
Mi. Feb. 7 17:12:44 2024 1707322364790 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Cadence: 25"
Mi. Feb. 7 17:12:44 2024 1707322364790 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 6.36"
Mi. Feb. 7 17:12:44 2024 1707322364791 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current CrankRevs: 20"
Mi. Feb. 7 17:12:44 2024 1707322364792 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Last CrankEventTime: 31306"
Mi. Feb. 7 17:12:44 2024 1707322364793 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Watt: 28"
Mi. Feb. 7 17:12:44 2024 1707322364802 Debug: /Users/cagnulein/qdomyos-zwift/src/yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x283cad740) true true true
Mi. Feb. 7 17:12:45 2024 1707322365003 Debug: /Users/cagnulein/qdomyos-zwift/src/yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x283cad740) true true true
Mi. Feb. 7 17:12:45 2024 1707322365104 Debug: /Users/cagnulein/qdomyos-zwift/src/templateinfosender.cpp bool TemplateInfoSender::update(QJSEngine *) "eval res " "{\"msg\":\"workout\",\"content\":{\"BIKE_TYPE\":2,\"ELLIPTICAL_TYPE\":4,\"ROWING_TYPE\":3,\"TREADMILL_TYPE\":1,\"UNKNOWN_TYPE\":0,\"deviceId\":\"{ec156d25-f7dd-62a4-5745-02e0dfb8d6e3}\",\"deviceName\":\"YESOUL276943\",\"deviceRSSI\":-74,\"deviceType\":2,\"deviceConnected\":true,\"devicePaused\":false,\"elapsed_s\":30,\"elapsed_m\":0,\"elapsed_h\":0,\"lapelapsed_s\":30,\"lapelapsed_m\":0,\"lapelapsed_h\":0,\"pace_s\":36,\"pace_m\":3,\"pace_h\":0,\"pace_color\":\"white\",\"avgpace_s\":36,\"avgpace_m\":3,\"avgpace_h\":0,\"maxpace_s\":12,\"maxpace_m\":2,\"maxpace_h\":0,\"moving_s\":30,\"moving_m\":0,\"moving_h\":0,\"speed\":16.658317390057395,\"speed_avg\":16.652219707269246,\"speed_color\":\"white\",\"speed_lapavg\":16.652219707269246,\"speed_lapmax\":27.068908023643047,\"calories\":2.4780894250000003,\"distance\":0.14333974133560162,\"heart\":86,\"heart_color\":\"lightsteelblue\",\"heart_avg\":86,\"heart_lapavg\":86,\"heart_max\":86,\"heart_lapmax\":86,\"jouls\":1869.6930000000002,\"elevation\":0,\"difficult\":1,\"watts\":28,\"watts_avg\":96.6701030927835,\"watts_color\":\"white\",\"watts_lapavg\":96.6701030927835,\"watts_max\":193,\"watts_lapmax\":193,\"kgwatts\":0.37333333333333335,\"kgwatts_avg\":1.2889347079037805,\"kgwatts_max\":2.5733333333333333,\"workoutName\":\"Ride\",\"workoutStartDate\":\"Mi. Feb. 7 17:11:04 2024\",\"instructorName\":\"\",\"latitude\":null,\"longitude\":null,\"altitude\":null,\"peloton_offset\":0,\"peloton_ask_start\":false,\"autoresistance\":true,\"row_remaining_time_s\":0,\"row_remaining_time_m\":0,\"row_remaining_time_h\":0,\"remaining_time_s\":0,\"remaining_time_m\":0,\"remaining_time_h\":0,\"nickName\":\"BSX\",\"gears\":0,\"target_resistance\":30,\"target_peloton_resistance\":0,\"target_cadence\":0,\"target_power\":0,\"power_zone\":1.1082251082251082,\"power_zone_lapavg\":1.0671301968471778,\"power_zone_lapmax\":1.7459802102659245,\"target_power_zone\":1,\"power_zone_color\":\"white\",\"peloton_resistance\":61.36360000000001,\"peloton_resistance_avg\":69.22081287128715,\"peloton_resistance_color\":\"white\",\"peloton_resistance_lapavg\":69.22081287128715,\"peloton_resistance_lapmax\":71.35270000000001,\"peloton_req_resistance\":0,\"cadence\":25,\"cadence_color\":\"white\",\"cadence_avg\":44.1,\"cadence_lapavg\":44.1,\"cadence_lapmax\":74,\"resistance\":74,\"resistance_avg\":81.07920792079207,\"resistance_lapavg\":81.07920792079207,\"resistance_lapmax\":83,\"cranks\":20,\"cranktime\":31306,\"req_power\":0,\"req_cadence\":0,\"req_resistance\":30}}"
Mi. Feb. 7 17:12:45 2024 1707322365202 Debug: /Users/cagnulein/qdomyos-zwift/src/yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x283cad740) true true true
Mi. Feb. 7 17:12:45 2024 1707322365403 Debug: /Users/cagnulein/qdomyos-zwift/src/yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x283cad740) true true true
Mi. Feb. 7 17:12:45 2024 1707322365605 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::update() "trainprogram random seconds 30 last_change \u0001 period <"
Mi. Feb. 7 17:12:45 2024 1707322365607 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::update() Current Distance 1s: 0.143394 16.6583
Mi. Feb. 7 17:12:45 2024 1707322365608 Debug: /Users/cagnulein/qdomyos-zwift/src/yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x283cad740) true true true
Mi. Feb. 7 17:12:45 2024 1707322365788 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 00 00 00 02 ad ff"
Mi. Feb. 7 17:12:45 2024 1707322365790 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetoothdevice.cpp void bluetoothdevice::update_hr_from_external() Current Heart from Apple Watch:  "86"
Mi. Feb. 7 17:12:45 2024 1707322365792 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Resistance: 70"
Mi. Feb. 7 17:12:45 2024 1707322365793 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 14.6571"
Mi. Feb. 7 17:12:45 2024 1707322365794 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Calculate Distance: 0.147432"
Mi. Feb. 7 17:12:45 2024 1707322365795 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Cadence: 0"
Mi. Feb. 7 17:12:45 2024 1707322365795 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 6.15"
Mi. Feb. 7 17:12:45 2024 1707322365796 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current CrankRevs: 20"
Mi. Feb. 7 17:12:45 2024 1707322365797 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Last CrankEventTime: 31306"
Mi. Feb. 7 17:12:45 2024 1707322365798 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Watt: 0"
```

here it was sending 25 and then 0. But this could be ok if you just stop to ride. So that's why I need a log, where maybe you can told me, ok at 12:44:47 i got the issue.

Anyway it's not a bluetooth issue for sure.

Also just to be sure: the problem is visible on qz and zwift both, or only on zwift?

> what do you mean with „dircon setting in the experimental settings is disabled“?

in the experimental settings enable

`Wahoo direct connect`

Let me know if something is unclear

**Comment by bsxsp** [comment]
At the point in the LOG where 0 comes, exactly my problem occurs, that the Cardence & Watts and as a result then also speed drops to 0. I continue to ride the bike at this point.

The problem occurs in qz and Zwift, so in combination when I bike with qz. The Bluetooth connection itself does not interrupt (i.e. at no time, although the three values Speed, Cardence and Watts fall to 0).

**Comment by cagnulein** [comment]
@bsxsp at that point is the bike that it's sending 0. You can also see it from the log. There is nothing that I can do from the QZ point of view.

Are you sure that maybe the issue in the bike itself? Did you test multiple time on kinomap? Maybe kinomap is doing a filter on the data so you are seeing an average? In qz how often is the drop? how is it long usually? if it's some seconds the averaging thing it could be the reason why with kinomap (that use the QZ library, so the code is the same) you don't see it. simply they are hiding it.

I strongly suggest to check also the Yesoul app, because the problem could be also there

Let me know!

**Comment by bsxsp** [comment]
of course, I have tried the Yesoul APP and Kinomap several times and the problems do not occur there. I have already spent many hours trying instead of training on Zwift to find the mistake.

Only since the update to iOS 17.3 did the malfunction only occurred with qz with Zwift.

Before I updated iOS 17.3, qz and Zwift ran for me for almost a year without errors or malfunctions. I'm very sad because of course it costs me a lot of time and nerves and unfortunately I can't find the mistake myself.

If it were the wheel Yesoul S3 itself, the Yesoul APP and Kinomap would also have to display 0 at Speed, Cardence and Watts, but this is not the case.

You are my last hope to get qz and Zwift up and running again.

**Comment by cagnulein** [comment]
@bsxsp believe me, i would like to help, i'm helping everybody but this case it's impossible. Please check with me this log exrtacted from your log

```
Mi. Feb. 7 17:12:43 2024 1707322363792 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 7c 4a 00 19 00 1c 02 fb ff"
Mi. Feb. 7 17:12:44 2024 1707322364782 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 7c 4a 00 19 00 1c 02 fb ff"
Mi. Feb. 7 17:12:45 2024 1707322365788 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 00 00 00 02 ad ff"
Mi. Feb. 7 17:12:46 2024 1707322366793 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 00 00 00 02 ad ff"
Mi. Feb. 7 17:12:47 2024 1707322367782 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 68 47 00 00 00 00 02 af ff"
Mi. Feb. 7 17:12:48 2024 1707322368787 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 00 00 00 02 ad ff"
Mi. Feb. 7 17:12:49 2024 1707322369792 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 00 00 00 02 ad ff"
Mi. Feb. 7 17:12:50 2024 1707322370782 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 68 47 00 49 00 b0 03 a8 ff"
Mi. Feb. 7 17:12:51 2024 1707322371787 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 49 00 ab 03 a1 ff"
Mi. Feb. 7 17:12:52 2024 1707322372793 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " << 51 1c 02 67 46 00 49 00 ab 03 a1 ff"
```

you see that the bike is sending 0 in the middle? How can i replace that data? Keeping the last values? Of course I can do it if you want but I can't invent data, I can only use the last known value. So in zwift you will have some seconds where the metrics are freezing. Also I can't do this for everybody because this means that one person with a working bike will use this special version will have a delay before turning the cadence to 0.

Is it clear in my poor english? :)

If you want I can do a special version for you with a 5 seconds delay, but I can't put in the main branch and this will have unfortunately a cost because I have to mantain this special one. If so the holes are usually 5 seconds or more? If they are more i guess this way is impossible :(

**Comment by cagnulein** [comment]
@bsxsp any news?
