### ISSUE TITLE
Non vedo la finestra del workout

### ISSUE THREAD

**Issue by robertocaboni** [cagnulein/qdomyos-zwift#2110]
Su android, carico un workout, vedo che funziona perchè dalle tiles vedo i watt target, ma non vedo la schermata divisa tra tiles e allenamento da seguire (che ho visto provando su un vecchio android che però ha "altri problemi".)

[debug-Thu_Feb_8_08_43_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14205917/debug-Thu_Feb_8_08_43_59_2024.log)

**Smartphone (please complete the following information):**
 - Device: Oppo Reno 4Z 5G
 - OS: Android
 - Version 12

Grazie, Roberto Caboni.

**Comment by cagnulein** [comment]
il training program in questo log sta correttamente girando, quindi ti confermo che sta funzionando.
non e' che semplicemente devi abiltiarti nelle tiles setting le tile che vuoi vedere? o semplicemente stai parlando che non vedi il grafico? il grafico e' nella beta, devi accederci da qui https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift e poi scaricare l'aggiornamento da play store

fammi sapere!

**Comment by robertocaboni** [comment]
O scusa...tutto è partito dalla beta che avevo prima di comprare l'app :-O

**Comment by cagnulein** [comment]
no problem, spero che ora funzioni tutto, fammi sapere!

**Comment by robertocaboni** [comment]
Ciao Roberto, il grafico del workout funziona! Quando potrai aggiungere la
possibilità di ridimensionare la dimensione della finestra ed eventualmente
anche la possibilità di zoom sarà il software più bello del mondo. Ti dirò,
va bene anche se non mi connetto con golden cheetah se posso fare da Qz,
poi con calma esporto e carico. Grazie mille

Il gio 8 feb 2024, 09:38 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ehehe si sono da solo, cerco di fare il possibile. Comunque il ridimensionamento e lo zoom e' fattibile, quello e' una pagina html.
Ti diro' di piu' in realta' quella pagina la puoi aprire anche su pc e vederla in realtime!
Se vuoi ti spiego come fare

**Comment by robertocaboni** [comment]
Assolutamente fammi sapere😱
Complimenti comunque eh

Il gio 8 feb 2024, 15:04 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
e' un po' arzigoggolato ma una volta che capisci e' semplice
1. dai setting vai su general ui options e premi su open floating windod
2. ti si apre il browser sul tuo cell con la floating window di qz
3. se tu copi incolli questa cosa sul browser su pc vedrai la floating window pure li
4. ora se prendi la url che ti dice che e' una cosa del tipo http://192.168.0.54:543323/floating/floating.htm e togli l'ultima parte e metti http://192.168.0.54:543323/chartjs/chartlive.htm 

avrai la schermata live grande quanto vuoi sul desktop!

fammi sapere!

**Comment by cagnulein** [comment]
grandissimo!
