### ISSUE TITLE
[BUG] No data from toorx BRX-300

### ISSUE THREAD

**Issue by rbmusica** [cagnulein/qdomyos-zwift#2111]
**Describe the bug**
Toorx 0126 found, but no incoming data on tiles

**Smartphone (please complete the following information):**
 - Device: s22 ultra
 - OS: android 14 (one ui 6.0)
[debug-Thu_Feb_8_14_25_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14209873/debug-Thu_Feb_8_14_25_34_2024.log)
[debug-Thu_Feb_8_14_34_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14209875/debug-Thu_Feb_8_14_34_20_2024.log)

**Comment by cagnulein** [comment]
it seems that the bike doesn't answer at all. are you able using the kinomap app to collect this log https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device ?
Let me know!

**Comment by rbmusica** [comment]
Will try kinomap and then report back, with the log

**Comment by rbmusica** [comment]
Ok, tried iConsole and Kinomap, and they detect the bike, but both are not able to receive any data from the bike. Could be a defective console, or could the power adapter be the source of this problem? I'm not sure I'm using the original - genuine from Toorx, as I've bought the bike used, but the specs on the input on the bike are 9v 1.3a and the power adapter is 12v 1.5a, so I'm quite sure it's not the toorx genuine adapter.

**Comment by rbmusica** [comment]
Should I get the log from kinomap anyway, would it be helpful in diagnosing the problem with the data?

**Comment by cagnulein** [comment]
for sure i will try to use the right voltage. 
yes sure share the log so i can check if at least we are getting any data

**Comment by rbmusica** [comment]
Replaced the power supply with one with the right voltage, kinomap is perfectly working, now! Created the full log (with BT HCI snooping activated) and sent it to your mail. Unfortunately QZ is still not working - same as before, bike is found but the tiles are not showing any data, and bike console remains lit up.

**Comment by cagnulein** [comment]
Great news! I will check the log and I will report back!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 feb 2024 alle ore 16:24 rbmusica ***@***.***>
ha scritto:

**Comment by rbmusica** [comment]
No joy, unfortunately...kinomap and also iconsole training are perfectly working now, but tried SPX9500 settings (alone and in combo with Toorx 3.0, Toorx/iConsole, Toorx FTMS bike)....and the situation is exactly as before, no tile data, bike is found but no BT data coming through, and bike console remains lit up, while as soon as I start kinomap the console goes black.

**Comment by cagnulein** [comment]
could you please upload a new debug log? i would like to check that the frames are correctly sent and the bike is actually no sending info.
Thanks

**Comment by cagnulein** [comment]
ok i will check this tomorrow, thanks.
It should fixable of course

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 feb 2024 alle ore 17:15 rbmusica ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok i tried to do a quick fix https://github.com/cagnulein/qdomyos-zwift/actions/runs/7832829270
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by rbmusica** [comment]
Ok, thanks, will install the APK and then report back ASAP!

**Comment by rbmusica** [comment]
Just to double check, should I enable only "enerfit_SPX_9500" in the TOORX settings, or other options should be enabled, too?

**Comment by cagnulein** [comment]
yes keep that one enabled!

**Comment by rbmusica** [comment]
The build is working perfectly fine...wow...thanks!! I had to keep QZ in the notification area, otherwise it won't stay active and the bike was not detected by Zwift. The default wattage was somewhat wrong (I can do 600/650w spikes on a power meter and on a tacx, and couldn't do anything over 150/200w on default settings), but I already found my way through the settings and will adjust/fine tune the parameters in the next weeks! PS The "change gears" with the volume it's not working for me, at the moment.

**Comment by rbmusica** [comment]
Downloading the windows binary now....do I need some code/activation for using it? I'll start testing it tonight (11PM-1AM) on my main rig for cycling, and then report back

**Comment by cagnulein** [comment]
that's great! the windows version requires a patreon subscription. thanks.

for the android one: set your email address in the email setting and press ok

**Comment by cagnulein** [comment]
about the volume share me a debug log? did you enable the gear on volume setting?

**Comment by rbmusica** [comment]
Subscribed your Patreon few moments ago! I'd like to test the windows app. Thanks Roberto (nice name, BTW ^_^ !)

**Comment by cagnulein** [comment]
sure! added there as well! add your email there too!

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 feb 2024 alle 19:51 rbmusica ***@***.***> ha
scritto:

**Comment by rbmusica** [comment]
> about the volume share me a debug log? did you enable the gear on volume setting?

Yes, the gear on volume setting is enabled, but while I'm in Zwift, pressing the volume rocker presents the android volume popup notification (as standard). Will send a debug log ASAP!

**Comment by cagnulein** [comment]
hah no qz must be on foreground in order to work with the volume on gears

**Comment by cagnulein** [comment]
@rbmusica everything is fine?

**Comment by rbmusica** [comment]
Hi Roberto....yes...thanks!!! I had some problems with the resistance settings, with tile dimensions and size (the tiles were overlapping and text was quite messy using the default view), but after some tweaking around I'm quite happy, at the moment!

Auto resistance change on hills / downhills works nicely, too!

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno dom 25 feb 2024 alle 10:48 rbmusica ***@***.***> ha
scritto:
