### ISSUE TITLE
[Issues with TDF4 and connectivityBUG]

### ISSUE THREAD

**Issue by Avongray** [cagnulein/qdomyos-zwift#2114]
[debug-Sat_Feb_10_10_35_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14229725/debug-Sat_Feb_10_10_35_44_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
are you on pc? connect a bluetooth device on the pc to trigger the
connection or use this build instead
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 feb 2024 alle 16:48 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
HiThanks for the quick response. The trial version works with zwlft but even though it connects to fulgaz with Bluetooth disabled (won't work with fulgaz Bluetooth enabled) the nothing really works speed cadence etc.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/10/24  10:53  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
are you on pc? connect a bluetooth device on the pc to trigger the

connection or use this build instead

https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip





Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 10 feb 2024 alle 16:48 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
for fulgaz you need to use 2 separate devices. as far as i know it can't
work with one device only.
do you see the wahoo device on fulgaz? i guess not, right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 feb 2024 alle 18:27 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
HiNo see wahoo kiikr 000 and hrm but when I pedal on the bike it moves ie power to 21 and then sticks there. My set up is a tdf4 bike and a pc wich has Bluetooth. As I say it looks like zwift is working properly using my setup. Why would fulgaz be different.As I said in my original enquiry. I am using Dan Bee's system but have been having issues with incline and decline cutting out mid ride(on all 4 of my bikes) so not hardware. Otherwise no other issue with fulgaz. I hope you have a solution. If I have to use  2 devises will it work using your app on a smartphone (andoid)and then opening fulgaz on the pc. Is there a trial android app that I can try and see if this solves the issue.As you can deduct from this email and time invested I am not just kicking the tires and am seriously looking to switchMaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/10/24  12:36  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
for fulgaz you need to use 2 separate devices. as far as i know it can't

work with one device only.

do you see the wahoo device on fulgaz? i guess not, right?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 10 feb 2024 alle 18:27 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
i'm out of town now anyway fulgaz it hasn't the wifi implantation that zwift has. that's why you need 2 devices or 2 bluetooth dongle on your pc.

so yes the android device could work

**Comment by Avongray** [comment]
Hi I do have dongle on the pc'sSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/10/24  13:05  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
i'm out of town now anyway fulgaz it hasn't the wifi implantation that zwift has. that's why you need 2 devices or 2 bluetooth dongle on your pc.
so yes the android device could work

**Comment by cagnulein** [comment]
you need 2, one for tx and one for rx

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 feb 2024 alle 19:15 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
HiWhere are we on this?Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/10/24  13:17  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
you need 2, one for tx and one for rx



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 10 feb 2024 alle 19:15 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
I answered, you need 2 dongles or a mobile and a pc.

I was waiting your answer.

Did you try?

**Comment by Avongray** [comment]
Hi I replied to you on this I have 2 ant drivers that I am using which drivers do they need?Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/12/24  21:05  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
I answered, you need 2 dongles or a mobile and a pc.
I was waiting your answer.
Did you try?

**Comment by cagnulein** [comment]
you need 2 bluetooth dongles, not ant+.

otherwise a mobile with qz and fulgaz on pc

**Comment by Avongray** [comment]
HiShould have Bluetooth dongles today. So will test. If all is fine how do I get the windows app and how do I pay you for it.Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/13/24  00:30  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
you need 2 bluetooth dongles, not ant+.
otherwise a mobile with qz and fulgaz on pc

**Comment by cagnulein** [comment]
Ok let me know!

**Comment by Avongray** [comment]
HiThis is pretty frustrating. I tried 2x  tp link Bluetooth ac600. The incline and decline is working but the watts cadence and speed are all not working. This really shouldn't be so difficult. I had minor issue with setup of Dan Bee's program and this is almost a week of trying to get your trial to work with fulgaz.Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/13/24  10:49  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Ok let me know!

**Comment by cagnulein** [comment]
Do you see correctly the speed and cadence on the qz app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 23:46 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
The screen is pretty jumbled so hard to tell. When I pedal I do see the counters moving but don't know the accuracy. On fulgaz it moves to a cadence of 21 and speed of 17km and then sticks even though I am actually doing 67 and 34 kph. Could we have a whatsapp call?Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/14/24  19:28  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Do you see correctly the speed and cadence on the qz app?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 14 feb 2024 alle 23:46 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
i'm in italy, 4am here :)
so provide a debug log and i will check it
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 02:30 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
Hi
Here is the log from today. Fulgaz sees re
[debug-Thu_Feb_15_16_16_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14302573/debug-Thu_Feb_15_16_16_13_2024.log)
sistance power and cadence wahoo kkickr but not working in the ride.

**Comment by cagnulein** [comment]
i'm seeing data from fulgaz and also that fulgaz it's sending inclination to qz.
What's not working? please be precise otherwise it's impossible for me to help you 
thanks

**Comment by Avongray** [comment]
Hi so bike connects to QZ fulgaz sees the wahoo kickr 0000 for cadence and power and resistance. When I ride the speed and cadence is stuck the speed is incorrect. So when I am riding at perhaps 32kph it is showing 16kph when my watts are at perhaps 200 is is showing 21watts

**Comment by cagnulein** [comment]
ok try to enable the wahoo rgt setting under the experimental setting,
let's see if it makes any difference on the fulgaz side

anyway it seems a bug of fulgaz on the wahoo implementation

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 22:36 Avongray ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
that's great!

for the UI set the custom dpi for the qz app. you can do it creating a shortcut of the executable 

to unlock it join patreon https://www.patreon.com/cagnulein

i'm going to bed now so i will unlock it tomorrow in case

thanks

**Comment by Avongray** [comment]
Hi Roberto. So screen is fine and it seems that all is workimg but will probably need some adjustment. I would.like to discuss offsets with you. My Bluetooth / ant+ heart monitor shows on QZ but does not work on Fulgaz I have joined  patron and entered Email under general settings but program is not unlocked. Lastly is the subscription model the only way to pay you or do you have a one time fee.

**Comment by cagnulein** [comment]
> I would.like to discuss offsets with you.

yes sure

> My Bluetooth / ant+ heart monitor shows on QZ but does not work on Fulgaz

probably because Fulgaz doesn't accept from the same source the HR along with the other metrics. I sugest to pair it directly on Fulgaz.



> I have joined patron and entered Email under general settings but program is not unlocked

I don't see you.  With which email did you subscribe to patreon?

> Lastly is the subscription model the only way to pay you or do you have a one time fee.

I can also accept a donation of 50$ as a life time fee.

Thanks!

**Comment by Avongray** [comment]
HiThanks I have joined under ***@***.*** nickname Avon.Hi more than happy to pay $50. I take that would give me the mobile and windows version to use in both locations.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/19/24  10:55  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 

I would.like to discuss offsets with you.

yes sure

My Bluetooth / ant+ heart monitor shows on QZ but does not work on Fulgaz

probably because Fulgaz doesn't accept from the same source the HR along with the other metrics. I sugest to pair it directly on Fulgaz.

I have joined patron and entered Email under general settings but program is not unlocked

I don't see you.  With which email did you subscribe to patreon?

Lastly is the subscription model the only way to pay you or do you have a one time fee.

I can also accept a donation of 50$ as a life time fee.
Thanks!

**Comment by cagnulein** [comment]
Hi github is filtering the email, write me to roberto.viola83 at gmail.com about your email address

**Comment by Avongray** [comment]
HiI had my first full ride and all went well. My incline decline worked throughout the ride. So I will put together an email I'm regard to incline decline offset as well as power and cadence. I also need to play around with the hrm as still not working correctly. I also note at the email description it says if you press stop then an email is sent with your stats. I tried this but didn't het an email.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/19/24  11:05  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Author ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Hi github is filtering the email, write me to roberto.viola83 at gmail.com about your email address

**Comment by cagnulein** [comment]
> I also note at the email description it says if you press stop then an email is sent with your stats. I tried this but didn't het an email

share a debug log and I will check which is your issue

**Comment by Avongray** [comment]
[debug-Wed_Feb_21_15_58_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14365462/debug-Wed_Feb_21_15_58_09_2024.log)
Hi Here is the debug log

**Comment by cagnulein** [comment]
thanks, i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 22:45 Avongray ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Avongray fixed, it's building it here https://github.com/cagnulein/qdomyos-zwift/actions/runs/8004100789

**Comment by cagnulein** [comment]
@Avongray  https://github.com/cagnulein/qdomyos-zwift/actions/runs/8004100789/artifacts/1266286971

**Comment by Avongray** [comment]
HiThanks will test it. Quick question. I am going up to my lake home this weekend. Can I copy the unzipped program and paste to my oc up tgere or do I use the unzipped download and unzipped to that pc and do I need a different email or will my current one work.I do appreciate your time on this.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/22/24  07:37  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
@Avongray  https://github.com/cagnulein/qdomyos-zwift/actions/runs/8004100789/artifacts/1266286971

**Comment by cagnulein** [comment]
yes you can use the same email

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 feb 2024 alle 22:35 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
Hi still have issues with email being sent.  See previous log.

**Comment by cagnulein** [comment]
did you use the new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/8004100789/artifacts/1266286971 ?

**Comment by cagnulein** [comment]
can you please upload a fresh log from this build?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 feb 2024 alle 22:43 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
[debug-Tue_Mar_5_16_18_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14501901/debug-Tue_Mar_5_16_18_51_2024.log)
Hi Here is the debug log. Still not sending email.
Thx Max

**Comment by cagnulein** [comment]
Ok, I'll check it out.


Il giorno mar 5 mar 2024 alle 22:58 Avongray ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
yes it's the solution but does work for you? On my end it doesn't yet

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 mar 2024 alle ore 11:24 Avongray ***@***.***>
ha scritto:

**Comment by Avongray** [comment]
hi have downloaded and extracted <html>
<body>

17611 | 2024-Mar-20 12:39:20 | openssl-3.3.0-alpha1.tar.gz (SHA256) (PGP sign) (SHA1
-- | -- | --
What am I supposed to do to set this up. I am not really familiar with this. I understand  that it is supposed to open ssl to allow trafic but dont know how to apply it to your program.

\

**Comment by cagnulein** [comment]
it's what i was trying to understand. i didn't have a chance yet
i will let you know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 mar 2024 alle 20:33 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
The question is really why the email works on some system and not others. Hope you can figure this out .

**Comment by cagnulein** [comment]
what do you mean? on android or ios? that's because they have their own
libraries. windows instead use the one of the software that it's running if
i understood right

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 mar 2024 alle 21:30 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
I was talking about windows. Does it work on some pc's or is it just my pc that doesn't work. It was just a comment.Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 3/22/24  16:32  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
what do you mean? on android or ios? that's because they have their own

libraries. windows instead use the one of the software that it's running if

i understood right



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 22 mar 2024 alle 21:30 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
all the windows pc as far as i know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 mar 2024 alle 22:10 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
HiHave you found a solution to the email issue yet?Sent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 6/2/24  08:34  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Reopened #2114.

**Comment by cagnulein** [comment]
Not yet, very busy weeks, it's still in my todo list

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 giu 2024 alle 23:54 Avongray ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Avongray fixed! you can download the new version from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9367151046 (at the bottom of the page)
Let me know

**Comment by cagnulein** [comment]
@Avongray any news?

**Comment by Avongray** [comment]
Hi Roberto
How are you doing? Have been using program without any issues and very happy with it. I am not sure if you know that Fulgaz was bought by Rouvy and they will be moving accounts over pretty soon. I have tried to connect my bike with Rouvy but it does not see it through your system. Is there a setting that I need to change in order to use Rouvy? I would want to be able to change back and forth until the accounts are moved over.  Thanks for your help.

**Comment by cagnulein** [comment]
change the name of your qz phone to "JUSTO" and reboot it. it should solve it
let me know

**Comment by Avongray** [comment]
HiNot sure what you mean as I use a pc to connect.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/8/25  11:59  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
change the name of your qz phone to "JUSTO" and reboot it. it should solve it
let me know

**Comment by cagnulein** [comment]
Qz where is it running? Android right? If so follow my previous advice there

**Comment by Avongray** [comment]
Hi Roberto Rouvy is running on pc,QZ is also on pc. If you recall I first had issues with Fulgaz connecting MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/8/25  12:43  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Qz where is it running? Android right? If so follow my previous advice there

**Comment by cagnulein** [comment]
I don't think you can use qz and rouvy on the same pc

But try and let me know

**Comment by Avongray** [comment]
I am using Fulgaz and QZ on the same PC. What are you suggesting I try. At this point QZ see my bike but Rouvy does not connect to QZ.MaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/8/25  12:52  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
I don't think you can use qz and rouvy on the same pc
But try and let me know

**Comment by cagnulein** [comment]
Because rouvy doesn't handle direct connection yet.
You need to use a phone for qz for this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 8 feb 2025 alle 18:58 Avongray ***@***.***> ha
scritto:

**Comment by Avongray** [comment]
Hi againDon't want to argue a point but not sure you are correct. If I connect ant+ dongle and use TDBF4 program then Rouvy does see the bike etc. Both on the same PC. I moved to QZ because your format is more stable and offers more adjustment and control. The only difference between the 2 is bluetooth and ant+ in connectivity. As I am set up with PC for both QZ and riding app in both locations (home and Lake) I assumed that this would be an easy transitionMaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/8/25  13:32  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Because rouvy doesn't handle direct connection yet.

You need to use a phone for qz for this



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 8 feb 2025 alle 18:58 Avongray ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Ant+ is not direct connect that it's wifi based. If qz is on pc, rouvy can't see the device on Bluetooth because they are sharing the same Bluetooth 

The only way is dircon, but rouvy didn't implement it. It's not a qz issue, but a rouvy missing 

Anyway use of course the method that you like more

I only would like to explain how technically the things work

**Comment by Avongray** [comment]
HiI do understand what you are saying now. The point is I am trying to use your program with Rouvy without using your phone app. Would it then work with 2 pj'sMaxSent from my Galaxy
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/8/25  13:59  (GMT-05:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: Avongray ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [Issues with TDF4 and connectivityBUG] (Issue #2114) 
Ant+ is not direct connect that it's wifi based. If qz is on pc, rouvy can't see the device on Bluetooth because they are sharing the same Bluetooth
The only way is dircon, but rouvy didn't implement it. It's not a qz issue, but a rouvy missing
Anyway use of course the method that you like more
I only would like to explain how technically the things work

**Comment by cagnulein** [comment]
As I said, as far as I know, no, because rouvy didn't implement the method to receive metrics from the same device

**Comment by cagnulein** [comment]
But try and report back
