### ISSUE TITLE
Domyos EB900 No resistence

### ISSUE THREAD

**Issue by CiccioFritz79** [cagnulein/qdomyos-zwift#2115]
Hi Roberto,

I Just made a clean installation of QZ and starts with default config. EB900 connect with QZ and Zwift see it, but there isnt resistence.

If i set resistence from EB900, the value chang in QZ, but if i try chang from QZ, nothing happens to EB900 (and the value in QZ don't change).

i Attach a log file

 - Device: iPad Air 2
 - OS: iOS 15.8
 

**Append a debug log**
[debug-sab_feb_10_18_52_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14230075/debug-sab_feb_10_18_52_45_2024.log)

Thanks in advance

**Comment by cagnulein** [comment]
did you check if the domyos app or the kinomap app are able to change the
resistance from the app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 feb 2024 alle 19:06 CiccioFritz79 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
#2007
