### ISSUE TITLE
[REQ] power table nautilus u626

### ISSUE THREAD

**Issue by Paolopa1967** [cagnulein/qdomyos-zwift#2118]
[wattage.nautilus.u626.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/14233590/wattage.nautilus.u626.xlsx)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Paolopa1967** [comment]
Hello Roberto I added the power table for the u626

**Comment by cagnulein** [comment]
thanks! i will add it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 feb 2024 alle 19:36 Paolopa1967 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
could you please attach a debug log in order to add this right your bike
profile?
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 feb 2024 alle 20:12 cagnulein ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
Thanks to you Roberto!

Il Dom 11 Feb 2024, 20:12 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
could you please attach a debug log in order to add this right your bike profile? thanks

**Comment by Paolopa1967** [comment]
[debug-Fri_Feb_9_20_00_01_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14234007/debug-Fri_Feb_9_20_00_01_2024.log)
Here it is, sorry the delay

**Comment by cagnulein** [comment]
i don't see any connection to it, could you please attach one where you have a connection? thanks

**Comment by cagnulein** [comment]
never mind, got it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 feb 2024 alle 21:48 Paolopa1967 ***@***.***>
ha scritto:

**Comment by Paolopa1967** [comment]
[debug-Fri_Feb_9_12_22_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14234025/debug-Fri_Feb_9_12_22_09_2024.log)

Sorry I don't know how to choose

**Comment by cagnulein** [comment]
this is the code that i'm adding it

```
#include <stdio.h>

double calculateWattage(double cadence, double resistance) {
    double intercept = 12.16860795336126;
    double coefCadence = 0.12260211;
    double coefResistance = -0.39240546;
    double coefCadenceSquared = 0.00464781;
    double coefCadenceResistance = 0.34516268;
    double coefResistanceSquared = -0.01031992;

    double wattage = intercept + 
                     coefCadence * cadence + 
                     coefResistance * resistance + 
                     coefCadenceSquared * cadence * cadence + 
                     coefCadenceResistance * cadence * resistance + 
                     coefResistanceSquared * resistance * resistance;

    return wattage;
}

int main() {
    double cadence = 55;
    double resistance = 13;
    double wattage = calculateWattage(cadence, resistance);
    printf("Predicted Wattage: %.2f Watts\n", wattage);
    return 0;
}

```

**Comment by cagnulein** [comment]
@Paolopa1967 i did the code but there is a GIANT question mark. Does your bike have autoresistance? It doesn't seem so. Am I missing something?

**Comment by Paolopa1967** [comment]
Yes it have. The bike have 25 programs with auto resistance that change
automatically, yet don't work in zwift

Il Lun 12 Feb 2024, 14:57 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
but from the bike directly I assume, right? are you able to change the resistance from any app?

**Comment by Paolopa1967** [comment]
No,  only from the bikes program

Il Lun 12 Feb 2024, 16:04 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
so unfortunately this bike doesn't have auto resistance on hardware :(

**Comment by cagnulein** [comment]
so unfortunately I can't help you. Did you check with the https://github.com/doudar/SmartSpin2k ? @doudar can you help here?

**Comment by Paolopa1967** [comment]
Oh that's sad. I was not aiming to have auto resistance, just a value that
Zwift could give to indicate the correct resistance during workout. This
can allow me to adjust resistance manually.

Il Lun 12 Feb 2024, 16:21 Roberto Viola ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
Ok thank you very much, very helpful as usual🙂

Il Lun 12 Feb 2024, 17:13 Roberto Viola ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
He he I can live without. I just push the buttons😉

Il Lun 12 Feb 2024, 17:20 Anthony Doud ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
Anyways I checked how it works smartspin2k, it's for spinning bike with
external knob. Mine is an Nautilus U626 upright bike with 25 level of
internal auto resistance. lt's the same of the Schiwnn 570U upright bike.

Il Lun 12 Feb 2024, 17:20 Anthony Doud ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
Hello Roberto, thanks. I will try later when I go home. After that I will
give you a feedback. 🙂

Il Lun 19 Feb 2024, 10:49 Roberto Viola ***@***.***> ha
scritto:

**Comment by Paolopa1967** [comment]
Ok Roberto, i remember you to insert the media cadence on 5 seconds.
Thank you.

**Comment by cagnulein** [comment]
Actually just did https://github.com/cagnulein/qdomyos-zwift/actions/runs/7964963728

**Comment by Paolopa1967** [comment]
So fast! You are unbelievable

Il Lun 19 Feb 2024, 21:42 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I’m doing my best while playing with my baby daughter

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 feb 2024 alle 21:45 Paolopa1967 ***@***.***>
ha scritto:

**Comment by Paolopa1967** [comment]
Thank you again, you do 2 things at same time, not usual for us men 😉

Il Lun 19 Feb 2024, 21:47 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Lol

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 feb 2024 alle 21:49 Paolopa1967 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Paolopa1967 Are we OK with this?

**Comment by Paolopa1967** [comment]
Yes, it's fine. Thank you again.

Il Mer 13 Mar 2024, 06:43 Roberto Viola ***@***.***> ha
scritto:
