### ISSUE TITLE
Reebok SL8.0 Bike - all tiles read zero

### ISSUE THREAD

**Issue by sharky-fil** [cagnulein/qdomyos-zwift#2124]
My bike appears to connect to the app but all the tiles read zero. The app seems to think my bike is a treadmill.

I have attached a debug file and screenshots from nrfconnect app.

Thanks

Phil

[debug-Tue_Feb_13_13_25_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14266457/debug-Tue_Feb_13_13_25_11_2024.log)
![Screenshot_20240213-130530](https://github.com/cagnulein/qdomyos-zwift/assets/159913742/c5093d66-8145-4a05-aec6-98793098a2b6)
![Screenshot_20240213-130541](https://github.com/cagnulein/qdomyos-zwift/assets/159913742/75e51a9c-7990-4a51-a4c0-87142db864fe)
![Screenshot_20240213-130553](https://github.com/cagnulein/qdomyos-zwift/assets/159913742/126fa79c-4c19-4de7-b4f2-9a931e60efd8)

**Comment by cagnulein** [comment]
ok i did a first patch @sharky-fil 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7887717542
use this and enable the toorx/iconsole bike setting in the toorx/iconsole setting section

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by sharky-fil** [comment]
Hi,

After the patch is seemed to work fine. Thun after entering my email address in the general part of settings i can zeros on all the tiles again.
Attached is a debug file

Phil


[debug-Tue_Feb_13_17_49_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14270330/debug-Tue_Feb_13_17_49_19_2024.log)

**Comment by cagnulein** [comment]
The bike doesn't send any frame at all, did you try to reboot It?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 18:54 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
This is strange, I rebooted the bike and it still didn’t work.. So I tried the reebok app that came with the bike and it said ‘connection failed’
I unplugged the usb dongle plugged it back in and the reebok app connected ok.. So I tried the QZ app and it showed no info again..
I reverted back to the reebok app and it wouldn’t connect again. Unplugging and re plugging the dongle in makes the reebok app work again.
Its as if the QZ app is breaking the Bluetooth somehow.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by cagnulein** [comment]
Do you have an android device as well? I would like to collect the reebok
app behavior to see how they handle the connection.

Anyway not a big deal to remove the dongle I guess :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 19:19 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
Yes i’m using android... how do I get reebok app data to you?

So do you know why the patched version worked when I 1st tried it and now it doesn’t?

Removing the dongle only makes the reebok app work again, it doesn’t make QZ work..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by cagnulein** [comment]
Hah so that's strange.

Follow this with the rebook app

https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android
device

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 20:08 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
Ok, I think I’ve done it...

I just don’t get why it worked before and now it doesn’t..

Files attached

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by cagnulein** [comment]
You have to attach the file from the github interface otherwise I can't see
it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 20:33 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
files attached

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14271402/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks, I'll check  it out in the next days

Il giorno mar 13 feb 2024 alle 20:43 sharky-fil ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @sharky-fil I checked but the log in a 5 seconds only. could you please do it again? I don't see any traces of communication.

**Comment by sharky-fil** [comment]
I've tried again whilst doing a 15 min bike ride. Hopefully there will be some useful information in there this time.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14278796/btsnoop_hci.log)

**Comment by cagnulein** [comment]
no unfortuantely the file is just a 0.5 second long.
It seems that you enble the hci snoof setting only for a short time? is it possible? also, stupid question: are you running iconsole on the same device?

**Comment by sharky-fil** [comment]
the bluetooth hci anoop log was on for over 20 mins.. when i tap on it there are several options..
enabled filtered
enabled
enabled headers filtered
enable media pkts filtered
enabled profiles filtered

i have been picking the enabled option, is that right?

**Comment by sharky-fil** [comment]
im not running iconsole (i dont know what it is)

**Comment by sharky-fil** [comment]
i dont know if its relevant or not, but ive just tried uninstalling QZ app again and reinstalling the patched version from yesterday but i didnt enter my email address... the 'cadence' tile worked but nothing else. the resistance also displayed a number but the actual resistance didnt change when i changed the number

**Comment by cagnulein** [comment]
sorry i mean the rebook app

**Comment by sharky-fil** [comment]
yes i was using the reebok app and did a 15 min route which changed resistance etc

**Comment by cagnulein** [comment]
it means that in the procedure something is incorrect from your phone. are you enabling the hci snoof before rebooting your phone? if so try to collect it without rebooting. Some android flavours wants a different flow (the guide described the google android way).
Let me know

**Comment by sharky-fil** [comment]
Hello, sorry for the delay. I've been trying all sorts of combinations and I'm either getting a file thats only 1kb in size or no file at all.. I seem to always get some 'cfa' files but not the file i need.
This is starting to feel really frustrating as it must for you. Am i best just accepting the app doesn't work for me? 
I still dont understand why the patch version worked and then entering my email address seem to break it,

**Comment by sharky-fil** [comment]
if i try and add a cfa file it says that the file type is not supported

**Comment by cagnulein** [comment]
zip it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle 18:37 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
I didnt't think of that.. haha

here you go
[hci_snoop20240214165114.zip](https://github.com/cagnulein/qdomyos-zwift/files/14284381/hci_snoop20240214165114.zip)

**Comment by cagnulein** [comment]
Haha, thanks! i will check this tomorrow. dinner time here :) Have a nice
day!


Il giorno mer 14 feb 2024 alle 18:40 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
and you, thanks again

**Comment by cagnulein** [comment]
done @sharky-fil 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/7912474372

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by sharky-fil** [comment]
Hi, thanks again for trying to sort it out..

Right I've tried it, initially i couldn't get it to work but I've discovered if I turn my bike off at the mains, then load the app before I tplug it back in, it seems to connect. If I try and connect the app after the bike is powered on i get zero readings in the tiles.. Do you think that's the best it will be? Its not a massive problem as it is.
Also, i tested on zwift and it worked great, but it couldnt find the sensors on 'mywoosh' Do I need to change a setting for that?
Id also like to try rouvy as well.. do i need to change settings for that?
Oh, could you unlock it for me as well please.

Thankyou

Phil

**Comment by cagnulein** [comment]
> Right I've tried it, initially i couldn't get it to work but I've discovered if I turn my bike off at the mains, then load the app before I tplug it back in, it seems to connect. If I try and connect the app after the bike is powered on i get zero readings in the tiles..

that's strange. maybe you can provide me a debug log that works and a debug that doesn't so i can compare them.



> but it couldnt find the sensors on 'mywoosh' Do I need to change a setting for that?

where are you running mywhoosh? you need a separate device for it



> Id also like to try rouvy as well.. do i need to change settings for that?

same for rouvy, another device.



> Oh, could you unlock it for me as well please.

already did it. Add your email in the settings as you already did before

**Comment by sharky-fil** [comment]
OK, I'll do a debug log for each scenario..

Tested out rouvy by the way and it worked great... It looks like we're nearly there..

**Comment by cagnulein** [comment]
Awesome, thanks for the update!


Il giorno gio 15 feb 2024 alle 19:21 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
Hello again, i've tried doing some more debug logs for both scenarios but annoyingly for some reason it hasn't recorded the logs - theyre all from yesterday, so ill have to try again.
This time though, it took about 5 reboots of the bike to get the app to connect for some reason.

**Comment by cagnulein** [comment]
ok with a debug log will be clear. enable the debug log setting

**Comment by sharky-fil** [comment]
Hello,

Sorry for the delay its taken me lots of goes just to get a log file..
So this log scenario is as follows:
Bike already powered up but in a kind of sleep mode - i start pedalling and launch QZ app on my phone. App connects to bike but all tiles read zero. Close app try reebok app. reebok app wont connect to bike. I unplug and re insert bt dongle reebok app will connect but not data shown.. close that app and try QZ app again.. bike connects but no data shown. try unplugging and re inserting dongle doesnt make any difference.

 
[hci_snoop20240216145725.zip](https://github.com/cagnulein/qdomyos-zwift/files/14312687/hci_snoop20240216145725.zip)

**Comment by cagnulein** [comment]
hi @sharky-fil thankx but i just need a debug log from qz in this scenario (maybe it will be great to have a debug log that works and one that doesn't).
Thanks

**Comment by sharky-fil** [comment]
This is another log file with a different scenario:

bike unplugged, load QZ app plug bike in and start pedalling - qz connects to bike but all tiles read zero. Unplug then reinsert bt dongle qz app starts responding and works perfectly. Close qz app bike goes back to sleep mode. Open reebok app bike wont connect - unplug reinsert bt dongle reebok app connects and works as it should..

Its not consistently like this, sometimes it may take 3 to 5 unplugs and re plugging in to make it work

[hci_snoop20240216151235.zip](https://github.com/cagnulein/qdomyos-zwift/files/14312849/hci_snoop20240216151235.zip)

**Comment by sharky-fil** [comment]
> hi @sharky-fil thankx but i just need a debug log from qz in this scenario (maybe it will be great to have a debug log that works and one that doesn't). Thanks

sorry, i didnt realise it was a qz specific log you wanted.. i thought you wanted to see why the qz app breaks the reebok app..
I'll do it again for just the qz app

**Comment by cagnulein** [comment]
thanks!
following this
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 16:27 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
this is a log file with it working. bike was unplugged initially. i had to unplug and re plug in the dongle about 5 times before it started working

[debug-Fri_Feb_16_15_40_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14313063/debug-Fri_Feb_16_15_40_33_2024.log)

**Comment by cagnulein** [comment]
Thanks! I will chdck out!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 16:46 sharky-fil ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @sharky-fil both files are 0 bytes. can you compress them and upload them again? thanks!

**Comment by sharky-fil** [comment]
Hi, that's strange I thought i'd checked the size before i sent them.

Here's another log file (from the qz app) with it not working

[debug-Mon_Feb_19_19_01_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14336190/debug-Mon_Feb_19_19_01_39_2024.log) It has a file size of 326kb 

Ive tried to do another log with it working but i cant get qz to work at all now with several attempts at rebooting and unplugging

**Comment by sharky-fil** [comment]
sorry, forgot to zip it

[debug-Mon_Feb_19_19_01_39_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14336313/debug-Mon_Feb_19_19_01_39_2024.zip)

**Comment by cagnulein** [comment]
No problem, thanks!
I will check it tomorrow

Il giorno lun 19 feb 2024 alle 20:44 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
I would say so yes..If I use the Reebok app the bike just connects and works as it should.If I try and use the qz app and then close it (after it fails to work) the Reebok app will only connect and work if I either reboot the bike or unplug/reinsert the bt dongle.When I tried yesterday, no amount of rebooting or dongle plugging in would make the qz app display any information..It's really strange how it seems to work then just stop. On 20 Feb 2024 09:11, Roberto Viola ***@***.***> wrote:
log checked and unfortunately yes the bike is not answering at all. with the rebook app this is not happening? but also if you close qz and you try with the rebook app it doesn't work neither right? So it seems something on the closing of qz, does it sound correct?

**Comment by cagnulein** [comment]
it's really strange, i checked your original hci snoof and also the rebook
app doesn't send anything before quitting.
It seems for sure a bug in the dongle somehow, also it's strange that
removing the dongle the bike is still not working. Maybe so it's a issue on
the phone? did you try to reboot the phone instead of the bike? I noticed
that you're using a nothing phone, so for sure not a android standard
flavour

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 feb 2024 alle ore 14:01 sharky-fil <
***@***.***> ha scritto:

> I would say so yes..If I use the Reebok app the bike just connects and
> works as it should.If I try and use the qz app and then close it (after it
> fails to work) the Reebok app will only connect and work if I either reboot
> the bike or unplug/reinsert the bt dongle.When I tried yesterday, no amount
> of rebooting or dongle plugging in would make the qz app display any
> information..It's really strange how it seems to work then just stop. On 20

**Comment by sharky-fil** [comment]
I have tried rebooting my phone several times, also turning Bluetooth on and off.I do still have my old phone so I could try that and see what happens if you think it would help.Will the patched QZ app work my other phone ?On 20 Feb 2024 13:05, Roberto Viola ***@***.***> wrote:
it's really strange, i checked your original hci snoof and also the rebook

app doesn't send anything before quitting.

It seems for sure a bug in the dongle somehow, also it's strange that

removing the dongle the bike is still not working. Maybe so it's a issue on

the phone? did you try to reboot the phone instead of the bike? I noticed

that you're using a nothing phone, so for sure not a android standard

flavour



Let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 20 feb 2024 alle ore 14:01 sharky-fil <

***@***.***> ha scritto:



> I would say so yes..If I use the Reebok app the bike just connects and

> works as it should.If I try and use the qz app and then close it (after it

> fails to work) the Reebok app will only connect and work if I either reboot

> the bike or unplug/reinsert the bt dongle.When I tried yesterday, no amount

> of rebooting or dongle plugging in would make the qz app display any

> information..It's really strange how it seems to work then just stop. On 20

**Comment by cagnulein** [comment]
the patch that I did today is for windows. Are you talking the patch verison for the bike? yes it would work for any android device
let me know

**Comment by sharky-fil** [comment]
Ok I'll try it on another phone when I get home from work and report back..Do you want me to send any more logs?On 20 Feb 2024 13:26, Roberto Viola ***@***.***> wrote:
the patch that I did today is for windows. Are you talking the patch verison for the bike? yes it would work for any android device
let me know

**Comment by cagnulein** [comment]
nope if it's not working it's very simple: the bike is not sending anything
unfortunately

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 feb 2024 alle ore 14:32 sharky-fil <
***@***.***> ha scritto:

> Ok I'll try it on another phone when I get home from work and report
> back..Do you want me to send any more logs?On 20 Feb 2024 13:26, Roberto

**Comment by cagnulein** [comment]
the log that I need is the log BEFORE the problem from QZ. I guess the only thing that QZ can make different from Reebok is changing the resistance quickly from zwift or any other apps. What do you think?

**Comment by sharky-fil** [comment]
The problem I have now is I cannot get qz to work at all .. it connects but all the tiles are zero I've tried restarting, rebooting everything.On 20 Feb 2024 15:11, Roberto Viola ***@***.***> wrote:
I mean: keep always the debug log enabled in qz so we will have always everything.
For what I understood:
you're doing a session, everything is fine (and qz is logging)you're doing a second session and it doesn't work anymore (qz is still logging)
So i need both log of this scenario (i guess you already sent me but the files were 0 bytes).
Is everything clear?

**Comment by cagnulein** [comment]
this wasn't clear to me (maybe I misunderstood it).

So let me summarize:
- after my patch, QZ worked. You have to remove the dongle sometimes, but it worked
- after somedays (i don't know what changed), now it doesn't work anymore, and also the rebook app doesn't work anymore?

Sorry but i'm not english native so maybe I'm missing something

**Comment by sharky-fil** [comment]
Your English is really good.. i think withall the the different tests and scenarios it has become confusing.Your summary is nearly correct..after my patch, QZ worked. You have to remove the dongle sometimes, but it workedI also had to power off the bike. Sometimes it took 3-5 attempts for it to workafter somedays (i don't know what changed), now it doesn't work anymore, and also the rebook app doesn't work anymore?Qz app doesn't seem to work now but Reebok app works fine..If I try and use qz app the Reebok app stops working until I reboot everything.I hope that makes sense, sorry for giving you problems.. On 20 Feb 2024 15:20, Roberto Viola ***@***.***> wrote:
this wasn't clear to me (maybe I misunderstood it).
So let me summarize:
after my patch, QZ worked. You have to remove the dongle sometimes, but it workedafter somedays (i don't know what changed), now it doesn't work anymore, and also the rebook app doesn't work anymore?
Sorry but i'm not english native so maybe I'm missing something

**Comment by cagnulein** [comment]
> now it doesn't work anymore, and also the rebook app doesn't work anymore?Qz app doesn't seem to work now but Reebok app works fine

sorry but this phrase is contradictory. the reebok app is still working or not?
It makes a difference because I need to understand if your bike is still working with the reebok app or not (means a broken dongle for example).

Maybe you updated the firmware since the working scenario?

**Comment by cagnulein** [comment]
Yes, it makes sense now.
i will check this again tomorrow
Thanks


Il giorno mar 20 feb 2024 alle 17:00 sharky-fil ***@***.***>
ha scritto:

> Sorry I'm struggling to explain it..The Reebok app works fine - so I could
> use my bike and do a Reebok fitness session all ok.If afterwards I try and
> use the qz app I get the problem with it we've discussed (tiles reading
> zero)If after that i try and use the Reebok app again it will not
> connect... If I then reboot the bike and or dongle the Reebok app works
> fine again.. it is as if the qz app makes the Reebok app not work.Does that

**Comment by cagnulein** [comment]
@sharky-fil did you try to disable the "virtual bluetooth device" setting in qz in the experimental settings? only this one and restart qz. does it make any difference? can you also share a debug log from qz in this scenario?

**Comment by sharky-fil** [comment]
Hi, I don't think I've tried that setting.. it is currently enabled so I will try disabling it and send you a debug log.I'm back at work now so will have to do it when I get home..Thankyou again for continuing to help me..PhilOn 21 Feb 2024 08:28, Roberto Viola ***@***.***> wrote:
@sharky-fil did you try to disable the "virtual bluetooth device" setting in qz in the experimental settings? only this one and restart qz. does it make any difference? can you also share a debug log from qz in this scenario?

**Comment by sharky-fil** [comment]
Hello again...Good news, I disabled the virtual Bluetooth device setting and it all appears to be working perfectly.I will try again tomorrow just to make sure it wasn't a one off 🙂On another note, I tested it using zwift which worked as it should but when i tried mywoosh using a different device  no Bluetooth sensors could be found. Do I need to change a setting to use mywoosh?Thanks again.On 21 Feb 2024 11:47, Phil Sunderland ***@***.***> wrote:Hi, I don't think I've tried that setting.. it is currently enabled so I will try disabling it and send you a debug log.I'm back at work now so will have to do it when I get home..Thankyou again for continuing to help me..PhilOn 21 Feb 2024 08:28, Roberto Viola ***@***.***> wrote:
@sharky-fil did you try to disable the "virtual bluetooth device" setting in qz in the experimental settings? only this one and restart qz. does it make any difference? can you also share a debug log from qz in this scenario?

**Comment by cagnulein** [comment]
you need to use the wahoo virtual device on mywhoosh (you need 2 devices
for this, one for qz and one for mywhoosh)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 19:59 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
In mywhoosh it's saying 'no device found' I can't see an option to pick wahoo virtual device. Do I need to turn something on in the qz app?I am using 2 devices by the way.On 21 Feb 2024 19:35, Roberto Viola ***@***.***> wrote:
you need to use the wahoo virtual device on mywhoosh (you need 2 devices

for this, one for qz and one for mywhoosh)



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 21 feb 2024 alle 19:59 sharky-fil ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
if zwift works, the same setup must working on mywhoosh as well.

zwift is on the same mywhoosh device?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 21:11 sharky-fil ***@***.***>
ha scritto:

**Comment by sharky-fil** [comment]
Zwift works perfect, mywoosh is on the same device as zwift (different device to qz)It says scanning for devices then just says no devices found?On 21 Feb 2024 20:17, Roberto Viola ***@***.***> wrote:
if zwift works, the same setup must working on mywhoosh as well.



zwift is on the same mywhoosh device?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 21 feb 2024 alle 21:11 sharky-fil ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
you have to ask with mywhoosh so, it's for sure a mywhoosh bug. i tried
iphone to ipad here and it works fine

try to enable the wahoo rgt compatibility setting under the experimental
settings

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 21:51 sharky-fil ***@***.***>
ha scritto:

> Zwift works perfect, mywoosh is on the same device as zwift (different
> device to qz)It says scanning for devices then just says no devices

**Comment by cagnulein** [comment]
I can't see the photo. You have to upload it on github directly.
Anyway mywhoosh is a beta app, so I suggest to reach them saying that zwift
works on the same setup
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 22:48 sharky-fil ***@***.***>
ha scritto:

> No unfortunately it doesn't work for me..I'll see if I can install it on
> another device and see what happens..I've a attached a photo of what I

**Comment by sharky-fil** [comment]
Ok I'll reach out to them but I'll doubt they will be interested with my equipment not been on their 'compatible device list'I'll also try a different phone and my laptop to see if there is any difference and report back.On another note, I noticed on the qz app there was an option to upload a gpx file.. is there anything I need to do to make that feature work? The one I tried just did nothing when I uploaded it.On 21 Feb 2024 22:02, Roberto Viola ***@***.***> wrote:
I can't see the photo. You have to upload it on github directly.

Anyway mywhoosh is a beta app, so I suggest to reach them saying that zwift

works on the same setup

let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 21 feb 2024 alle 22:48 sharky-fil ***@***.***>

ha scritto:



> No unfortunately it doesn't work for me..I'll see if I can install it on

> another device and see what happens..I've a attached a photo of what I

**Comment by cagnulein** [comment]
Yes open the gpx file, then press start on qz and qz will follow the gpx
track and it will also show a 3d map!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 feb 2024 alle 10:30 sharky-fil ***@***.***>
ha scritto:

> Ok I'll reach out to them but I'll doubt they will be interested with my
> equipment not been on their 'compatible device list'I'll also try a
> different phone and my laptop to see if there is any difference and report
> back.On another note, I noticed on the qz app there was an option to upload
> a gpx file.. is there anything I need to do to make that feature work? The
> one I tried just did nothing when I uploaded it.On 21 Feb 2024 22:02,

**Comment by cagnulein** [comment]
yes then press again on the file and it will load it, then press start on qz and you will see the map icon on the top right corner and also when you will ride the resitance will change it automatically! let me know!

**Comment by sharky-fil** [comment]
Hi, just to keep you up to date. The qz app is working fine for zwift which is great. Im going to test different device combinations to try and get mywoosh working but i've had no joy as yet.

Regarding the 'open gpx' feature, that still doesnt work for me. If i tap on the file again the whole screen goes a grey colour and i get a message saying 'program has been loaded correctly, press start to begin'
if i press start nothing happens and no map icon appears... If i turn my phone to landscape, i see the map icon but nothing happens when i press it.

[Screenshot_20240223-145313.zip](https://github.com/cagnulein/qdomyos-zwift/files/14386641/Screenshot_20240223-145313.zip)

**Comment by cagnulein** [comment]
Could you please share the gpx that you are trying to load?
Thanks

**Comment by cagnulein** [comment]
Ok I will check it thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 23 feb 2024 alle 16:18 sharky-fil ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
It works perfectly here
Check

https://github.com/cagnulein/qdomyos-zwift/assets/48216/24318e85-e5bb-495c-b1db-3d5db416ed1f

**Comment by sharky-fil** [comment]
wow, i wish it worked for me like that. ive tried recording a little video of what happens for me but the file is too big to send it here. can i share it another way?

**Comment by sharky-fil** [comment]
https://drive.google.com/file/d/1h4kYnAZLkmg9isDERLAdcAmtqpUCelaE/view?usp=sharing

**Comment by cagnulein** [comment]
you have to press pause and play to engage qz as my video :)

**Comment by sharky-fil** [comment]
I've tried doing that as well, it still doesn't work. It's the same on 2 devices.On 23 Feb 2024 19:02, Roberto Viola ***@***.***> wrote:
you have to press pause and play to engage qz as my video :)

**Comment by cagnulein** [comment]
Share me a video and a debug log. It's just a user error, trust me :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 23 feb 2024 alle 23:08 sharky-fil ***@***.***>
ha scritto:

> I've tried doing that as well, it still doesn't work. It's the same on 2

**Comment by sharky-fil** [comment]
Good morning, sorry for the delay.. I've been away for a few days and not had chance to do more testing.. I tried again last night and you were right the open gpx feature worked great.I think it all seems to working now (apart from mywoosh)Thankyou ever so much for your help to get it to work properly.In future what will happen regarding any updates to the app as the version I've got is the patched one you did for me..On 24 Feb 2024 07:16, Roberto Viola ***@***.***> wrote:
Share me a video and a debug log. It's just a user error, trust me :)



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 23 feb 2024 alle 23:08 sharky-fil ***@***.***>

ha scritto:



> I've tried doing that as well, it still doesn't work. It's the same on 2

**Comment by cagnulein** [comment]
Great! The patched version is online on the store

**Comment by sharky-fil** [comment]
That's great, so should I replace my version with the one from the store?On 27 Feb 2024 08:24, Roberto Viola ***@***.***> wrote:
Great! The patched version is online on the store

**Comment by cagnulein** [comment]
yes :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle 10:09 sharky-fil ***@***.***>
ha scritto:

> That's great, so should I replace my version with the one from the

**Comment by cagnulein** [comment]
you have to be in the beta
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle 10:10 cagnulein ***@***.***> ha
scritto:

> yes :)
>
>
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
>
>
>
> Il giorno mar 27 feb 2024 alle 10:09 sharky-fil ***@***.***>
> ha scritto:
>
>> That's great, so should I replace my version with the one from the

**Comment by sharky-fil** [comment]
I'll give it a go, cheers On 27 Feb 2024 09:11, Roberto Viola ***@***.***> wrote:
you have to be in the beta

https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 27 feb 2024 alle 10:10 cagnulein ***@***.***> ha

scritto:



> yes :)

>

>

> Roberto Viola

> Software engineer and open source enthusiast

> http://robertoviola.cloud

>

>

>

> Il giorno mar 27 feb 2024 alle 10:09 sharky-fil ***@***.***>

> ha scritto:

>

>> That's great, so should I replace my version with the one from the

**Comment by cagnulein** [comment]
@sharky-fil are we ok with this?
