### ISSUE TITLE
[REQ] Disable icons in floating window

### ISSUE THREAD

**Issue by k818mn1** [cagnulein/qdomyos-zwift#2125]
**Is your feature request related to a problem? Please describe.**
The icons in the floating window are not essential and take up space in each row.

**Describe the solution you'd like**
Do not display icons in the floating window when the UI theme icon setting is disabled

**Comment by cagnulein** [comment]
ok i will try to do this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 22:34 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done @k818mn1 
I linked this in the already available setting under ui settings, themes, icon setting.
Which qz version are you using? android? ios? pc? I would like to send you the new beta

**Comment by k818mn1** [comment]
I am on android using the Amazon appstore.
-------- Original message --------From: Roberto Viola ***@***.***> Date: 2/14/24  3:35 AM  (GMT-06:00) To: cagnulein/qdomyos-zwift ***@***.***> Cc: k818mn1 ***@***.***>, Mention ***@***.***> Subject: Re: [cagnulein/qdomyos-zwift] [REQ] Disable icons in floating window (Issue #2125) 
done @k818mn1
I linked this in the already available setting under ui settings, themes, icon setting.
Which qz version are you using? android? ios? pc? I would like to send you the new beta

**Comment by cagnulein** [comment]
ok i will build it in the next days
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle ore 14:04 k818mn1 ***@***.***>
ha scritto:

**Comment by k818mn1** [comment]
Any progress?

**Comment by cagnulein** [comment]
i did it but never had a chance to build it. i will try tomorrow
very busy days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 feb 2024 alle 22:14 k818mn1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done! let me know and remember to change the setting about the icon in the
general UI settings

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 feb 2024 alle ore 22:15 cagnulein ***@***.***> ha
scritto:

**Comment by k818mn1** [comment]
It works perfectly! Thanks for your hard work!

**Comment by cagnulein** [comment]
Glad to hear this!
