### ISSUE TITLE
[Issue] Zwift Click paired but not changing gears on Linux

### ISSUE THREAD

**Issue by wtafe** [cagnulein/qdomyos-zwift#2126]
**Describe the bug**
Zwift click is paired, but pressing buttons doesn't change resistance.

Works in android. Though it appears to be updating during press rather than on-release. I have to be quick to press to get a single gear adjustment.

**Desktop (please complete the following information):**
 - OS: Linux Mint 

**Append a debug log**
[debug-Tue_Feb_13_17_10_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14272803/debug-Tue_Feb_13_17_10_31_2024.log)

**Comment by cagnulein** [comment]
for android change the gear gain to a lower value, like 0.2 or similar

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 23:28 wtafe ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
which bluetooth dongle are you using on linux? it seems it can't connect
correctly to the play controller

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle ore 01:07 cagnulein ***@***.***> ha
scritto:

**Comment by wtafe** [comment]
Asus bt5. I'll try a different adapter

**Comment by wtafe** [comment]
BT5, shows paired in blueman.

![Screenshot from 2024-02-14 09-51-18](https://github.com/cagnulein/qdomyos-zwift/assets/35377312/3909a621-0d18-467e-a390-57ba44a39b4f)

**Comment by cagnulein** [comment]
if you use zwift with wine it works there?

**Comment by wtafe** [comment]
Unless you know of a way to do it. I've never been able topass through
Bluetooth devices or controllers in wine.

**Comment by cagnulein** [comment]
ok let's try something different

are you able to use

$ bluetoothctl


to connect to the zwift play devices and try if you can subscribe and read
notification, for example the battery characteristic?


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle ore 17:23 wtafe ***@***.***>
ha scritto:

**Comment by wtafe** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/35377312/d39a02ed-0a89-4e57-b6ab-96cee850d9d0)

**Comment by cagnulein** [comment]
@wtafe i received a notification but i don't see your message

**Comment by wtafe** [comment]
Forgive me as this is my first time trying to manually read bluetooth
events. I think? the handle on the battery life is 0x0027. It does pair
with battery percentage information in the blueman properties.

[image: image.png]

**Comment by wtafe** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/35377312/f71fba93-4f84-4aca-a10b-6d083d07b696)
Not sure why e-mailed photos aren't showing.

**Comment by cagnulein** [comment]
i created this branch for you https://github.com/cagnulein/qdomyos-zwift/pull/2132

build this one and send me a debug log

let me know!

**Comment by wtafe** [comment]
[debug-Fri_Feb_16_16_33_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14316242/debug-Fri_Feb_16_16_33_51_2024.log)

**Comment by cagnulein** [comment]
Ok no difference, I will about something else. Do you have only this Bluetooth dongle?

**Comment by wtafe** [comment]
This can be closed, I'm going to keep it on android and use floating window HTTP server as a workaround on linux. My current BT adapter works well with all my other devices and it was such trial and error finding one that worked.
