### ISSUE TITLE
[REQ]Add ability for *new* profile with defaults

### ISSUE THREAD

**Issue by n8udd** [cagnulein/qdomyos-zwift#2129]
**Is your feature request related to a problem? Please describe.**
Currently when creating a _new_ profile, it duplicates the settings of the existing profile selected. This isn't clear or intuitive.

When trying to debug what an issue is, or support a new user that cannot get their setup correct, it's a lot easier to start from the default settings to debug any issues.

**Describe the solution you'd like**
Have a "+" button, that creates a _new_ profile with the default settings loaded. 

**Additional context**
Currently if I want to have a profile with the default settings, so that I can test someting, or add a profile for a new platform, I either have to research what they would be, or delete the app and re-install.

EG: I would like a seperate profile for Peloton, Zwift and Intelligent Cycling for my EX-3 another profile for Zwift for my Tacx Neo and another when I'm using my Garmin Vector 3 on the EX-3.

Selecting prrofiles should just change to that profile.

If you wish to duplicate a profile, I'd suggest a "press and hold" on the profile that duplicates it.

**Comment by cagnulein** [comment]
Makes sense, i will definitely do this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 feb 2024 alle ore 17:17 Nathan Budd <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@n8udd done!
what I did is to add a new "+" button to restore the default settings. Before doing so, i added a message box that asks if you want to save the current profile (just to be sure), no or abort.

Do you think it would be ok?

**Comment by n8udd** [comment]
I'm not sure I follow.
Say I have 3 profiles already... 

- Zwift
- Zwift Erg
- Peloton

I'm currently in the Peloton profile.

Will pressing the + button reset my Peloton settings?

**Comment by cagnulein** [comment]
nope it doesn't touch the peloton settings, it just reset all the settings to the default and then you can save it as a new one with the default ones.

after pressing the + button qz will just ask to save the current profile in case you didn't already
