### ISSUE TITLE
Horizon 7.0AT 02

### ISSUE THREAD

**Issue by Robnewsham** [cagnulein/qdomyos-zwift#2130]
Afternoon, 

I've had your amazing app for ages, but never really used it.

I wanted to get the auto incline working in Zwift, however I am struggling. 

My horizon 7.0 Treadmill is connected / found on the app, however the is no flashing inclination icon and treadmill doesn't response to any changes on incline during my Zwift runs. 

Any advice please. 

Thanks

Rob Newsham

**Comment by cagnulein** [comment]
hi @Robnewsham let's start from the basic.
1. if you are using the plus and minus button on the inclination tile on qz are you able to change the inclination on the treadamill?
2. are you on ios or android?
3. did you set the zwift credentials on qz?

let me know

**Comment by Robnewsham** [comment]
Thanks for the quick reply

1. Plus and minus buttons will alter the incline on the treadmill

2. iOS 

3. I don't think I have put Zwift credentials anywhere on the QZ app, can't see where they would go.

**Comment by cagnulein** [comment]
@Robnewsham ok perfect, because you need the new beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the beta!

**Comment by Robnewsham** [comment]
All sorted, thank you. Auto incline working - extremely impressive indeed. 

I'm just confused with Wahoo Kickr and Wahoo Tread showing up on my available connections. 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/142440146/fcfacca3-9ad5-4e12-ad88-079b6f6ac6fb)

**Comment by cagnulein** [comment]
that's great! yes select the wahoo tread. QZ is sending 3 different soruces to zwift. Phone name (bluetooth), wahoo tread (wahoo dircon protocol over wifi for treadmill) and wahoo kickr (wahoo dircon protocol over wifi for bike).
