### ISSUE TITLE
Qz android wont be seen on zwift ios 

### ISSUE THREAD

**Issue by davidfernandezt** [cagnulein/qdomyos-zwift#2131]
Android qz would derect bike keiser im3 but wont send any signal readable under zwift running on ios . I am using an aditional ant dongle for connection withna gar,in device and there is working without any problem,  but wo t be any signal over zwift ios 

 clear and concise description of what you expected to happen.
It should be seen under Bluetooth devices , as when using qzios 
**Screenshots**

Qz under android 13 on a Samsung Atab with ant dongle
Zwift with last ios operation system under iPhone x and 15 pro max , Zwift and ios updated to last version 

***Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Qz is sending signal since my Garmin devices find the power and speed cadence sensors , but I guess it is an issue between ios and android Bluetooth Comunication 
[debug-Thu_Feb_15_00_00_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14292644/debug-Thu_Feb_15_00_00_17_2024.log)

**Comment by cagnulein** [comment]
Hi @davidfernandezt in this log the keiser is not broadcasting itself (maybe was off?). Could you please collect another log while you're connected to the bike?
Thanks

**Comment by davidfernandezt** [comment]
Herewith another file , hope I now have done it right , sorry I am certainly not too tech savvy 
[debug-Thu_Feb_15_13_53_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14301959/debug-Thu_Feb_15_13_53_30_2024.log)
[debug-Thu_Feb_15_13_53_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14301962/debug-Thu_Feb_15_13_53_30_2024.log)

**Comment by cagnulein** [comment]
ok here i can see everything and qz is broadcasting correctly itself. did you try to rename your android device to "bike" and reboot it?

**Comment by davidfernandezt** [comment]
I have just changed to Bike the mane of the tablet  and yes it is now seen by my iPhone , thanks !

**Comment by davidfernandezt** [comment]
Thanks!!!!

**Comment by cagnulein** [comment]
glad to hear this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle ore 22:05 davidfernandezt <
***@***.***> ha scritto:
