### ISSUE TITLE
[BUG]apex 

### ISSUE THREAD

**Issue by Maisienairn** [cagnulein/qdomyos-zwift#2135]
**the option of apex bike  is not there when I start a ride. When looking at Bluetooth I can see apex and it connects**  have an iPhone 14 in Peleton app I can see qz but no cadence or resistance shows on qz app
![IMG_1630](https://github.com/cagnulein/qdomyos-zwift/assets/160314920/0fa34d48-9742-4a4c-b04a-0dc773db4dbc)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi thanks I'm out with my family today, I will chdck later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle 10:16 Maisienairn ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @Maisienairn I need a debug log to understand your issue. The instructions: https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Maisienairn** [comment]
I have attached the file as per instructions 
I tried again and no cadence or resistance showing.  The Bluetooth is showing as connected 

[debug-Sat_Feb_17_16_39_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14319711/debug-Sat_Feb_17_16_39_45_2024.log)

**Comment by cagnulein** [comment]
@Maisienairn log checked but unfortunately is truncated. could you please do it again? just 30 seconds. open qz when you see the tile try to spin a little and just close qz and send me the debug log. thanks

**Comment by Maisienairn** [comment]
hopefully this works now 



[debug-Sat_Feb_17_19_03_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14319967/debug-Sat_Feb_17_19_03_39_2024.log)

**Comment by cagnulein** [comment]
yes perfect, i'm checking it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle ore 20:06 Maisienairn <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
mmm i got the issue: the bike is connected and it's talking with qz but it sends all the metrics to 0. maybe you have to press something on the bike to "start" it?

**Comment by Maisienairn** [comment]
No nothing to press.  With the apex app it would connect automatically (I’m not subscribed to that now)I think there was someone I saw a in previous posts who has an apex bike so I presumeIt worked 


Sent from Yahoo Mail for iPhone


On Saturday, February 17, 2024, 7:11 PM, Roberto Viola ***@***.***> wrote:




mmm i got the issue: the bike is connected and it's talking with qz but it sends all the metrics to 0. maybe you have to press something on the bike to "start" it?

**Comment by cagnulein** [comment]
yes indeed. it worked, i have other users that are using it. Do you have also an android device nearby? I would like to collect a log from the apex app to understand the issue if you agree

**Comment by Maisienairn** [comment]
No sorry I don’t have any android devices 😩 and I’m away tomorrow for a week.  Would it work with a laptop?  Sorry I’m a pest 

Sent from Yahoo Mail for iPhone


On Saturday, February 17, 2024, 7:25 PM, Roberto Viola ***@***.***> wrote:




yes indeed. it worked, i have other users that are using it. Do you have also an android device nearby? I would like to collect a log from the apex app to understand the issue if you agree

**Comment by cagnulein** [comment]
in order to collect a log from the apex app unfortunately we need an android device. nobody can borrow one just for 10 minutes? the time to collect a log

**Comment by Maisienairn** [comment]
I think my friends daughter has a Samsung so when I’m back in a week from I’ll borrow it Thanks 


Sent from Yahoo Mail for iPhone


On Saturday, February 17, 2024, 7:30 PM, Roberto Viola ***@***.***> wrote:




in order to collect a log from the apex app unfortunately we need an android device. nobody can borrow one just for 10 minutes? the time to collect a log

**Comment by cagnulein** [comment]
ok then install the apex app and follow this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
I will make it work!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle ore 20:33 Maisienairn <
***@***.***> ha scritto:

> I think my friends daughter has a Samsung so when I’m back in a week from
> I’ll borrow it Thanks
>
>
> Sent from Yahoo Mail for iPhone
>
>

**Comment by cagnulein** [comment]
Hi @Maisienairn Any news?
