### ISSUE TITLE
Getting running power from Garmin HRM PRO+

### ISSUE THREAD

**Issue by Lgxprod1** [cagnulein/qdomyos-zwift#2139]
Looking to get running power from the garmin HRM PRO+ hr strap to zwift/strava/garmin. I currently do not have a footpod but I know the strap can provide the power data in garmin but unsure if it translates on other platform. 

The debug log is attached.
[debug-Sun_Feb_18_13_27_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14323816/debug-Sun_Feb_18_13_27_24_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 feb 2024 alle 19:42 Lgxprod1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Lgxprod1 i checked and the band itself it's not sending it. I guess the garmin app is tranlsating HR + Cadence to get the power. Anyway, if you want we can check deeply. Are you able to see realtime power if you use the garmin app on your phone?

**Comment by Lgxprod1** [comment]
Thats possible that the app is calculating it based off hr + cadence. I dont see realtime power on the garmin app as the only real time data shows hr, steps, calories and intensity minutes. I read somewhere that its ant+ connection broadcasts more data than its Bluetooth counterpart which would include power and other running dynamics. Is there a way to get qz to connect to the strap by ant+ instead of bluetooth and test it that way?

**Comment by cagnulein** [comment]
it makes sense. First of all check with this app if you can read power https://play.google.com/store/apps/details?id=com.dsi.ant.antplus.pluginsampler&hl=it&gl=US
If so I can add in QZ as well.
Let me know!

**Comment by Lgxprod1** [comment]
Doesn't seem to popup in the sampler app for power. It only shows up for heart rate and also I was reading from the garmin website, it seems like garmin computes power from running dynamics. Looks like I'll need to get a stryd or something similar. Thanks for checking on this!

**Comment by cagnulein** [comment]
anytime!
