### ISSUE TITLE
Auto resistance on nordicktrack bike not working in zwift

### ISSUE THREAD

**Issue by Mrcholliday** [cagnulein/qdomyos-zwift#2143]
Hi Roberto 

Unfortunately the troubleshooting didn’t work. On the qz app the plus and minus buttons on the resistance tile tiles don’t work. 

I’m not able to connect the controls in the front screen of zwift in this anything to do with it

im using the qz companion on the nordicktrack bike and qz app on my Iphone with an iPad for zwift
![IMG_3266](https://github.com/cagnulein/qdomyos-zwift/assets/160531973/29801c7a-f5f6-42c3-9d6f-e6676f0204af)

**Comment by cagnulein** [comment]
are you able to provide a debug log? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Mrcholliday** [comment]
[Uploading debug-Mon_Feb_19_17_56_09_2024.log…]()

**Comment by cagnulein** [comment]
Hi you have to wait the finish of the upload otherwise the file is
corrupted

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 feb 2024 alle 21:47 Mrcholliday ***@***.***>
ha scritto:

**Comment by Mrcholliday** [comment]
[debug-Mon_Feb_19_17_56_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14336867/debug-Mon_Feb_19_17_56_09_2024.log)

**Comment by Mrcholliday** [comment]
HiNo when I press the incline or resistance tiles no impact is made to the bike. The tiles do not change when pressing the plus or minus buttons. I installed the APK on the S22i bike from the internal browser following the instructions in method2 Thank you for helping Kind Regards Chris Chris Holliday FPFS, MCSI,Regulation & ***@***.*** 774180On 19 Feb 2024, at 22:27, Roberto Viola ***@***.***> wrote:﻿
When you press the plus button in the inclination or the resistance tile

are you seeing a touch event on the bike tablet?

If not, did you install the apk with adb from pc?

Let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 19 feb 2024 alle 22:07 Mrcholliday ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Ok so in order to have auto incline you have to follow the method 1. Could you try it?
Midnight here so I will be back tomorrow

**Comment by Mrcholliday** [comment]
Hi Roberto,

 

I factory reset my machine, completed the install via method 1 (had to download each file individually as couldn’t find the ZIP file) but it worked and QZ Companion is installed on my Proform S22 studio bike, (install log attached) 

 

The QZ app is no longer communicating with the bike, so when I pedal, nothing changes on the tiles, I have selected every bike individually under the Proform options, including removing and reinstalling the app on my iPAD 

 

Appreciate your assistance in this,

**Comment by cagnulein** [comment]
> The QZ app is no longer communicating with the bike, so when I pedal, nothing changes on the tiles, I have selected every bike individually under the Proform options, including removing and reinstalling the app on my iPAD

could you share a debug log from qz? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Mrcholliday** [comment]
[debug-Tue_Feb_20_15_39_08_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14347835/debug-Tue_Feb_20_15_39_08_2024.log)
[debug-Tue_Feb_20_15_36_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14347836/debug-Tue_Feb_20_15_36_32_2024.log)
[debug-Tue_Feb_20_15_36_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14347837/debug-Tue_Feb_20_15_36_52_2024.log)

**Comment by cagnulein** [comment]
i don't see any message from the companion at all. are you sure that the companion is still running there?
are you able to collect an adb log using the [adb-debug.bat](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat) file in the zip (the zip is here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/tags/3.3.39.zip

let me know

**Comment by cagnulein** [comment]
just to be sure , are you sure the companion is running?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 feb 2024 alle 17:24 Mrcholliday ***@***.***>
ha scritto:

**Comment by Mrcholliday** [comment]
Hi. I had to go into the QZcompanion and select the proform bike. Apologies!

ok so now it’s connected and picking up cadance but not speed or incline 

![IMG_3285](https://github.com/cagnulein/qdomyos-zwift/assets/160531973/3dff6711-56c6-4b8f-b99b-37ba2e97efa4)



[debug-Tue_Feb_20_16_43_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14348669/debug-Tue_Feb_20_16_43_56_2024.log)
[debug-Tue_Feb_20_16_45_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14348671/debug-Tue_Feb_20_16_45_41_2024.log)
[debug-Tue_Feb_20_16_45_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14348672/debug-Tue_Feb_20_16_45_09_2024.log)

**Comment by cagnulein** [comment]
Ok perfect now enable the speed based on power setting under the bike settings in qz

**Comment by Mrcholliday** [comment]
This is already selected or is there another 

![IMG_3287](https://github.com/cagnulein/qdomyos-zwift/assets/160531973/001f3c19-fb49-4809-add0-a428dd5acacf)

**Comment by Mrcholliday** [comment]
![IMG_3288](https://github.com/cagnulein/qdomyos-zwift/assets/160531973/2c81f763-25a5-4cc3-ab6d-be1e97450090)

Meant this one

**Comment by cagnulein** [comment]
That's strange, Share me a debug log from qz https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Mrcholliday** [comment]
Here you go 

[debug-Tue_Feb_20_17_20_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14349098/debug-Tue_Feb_20_17_20_05_2024.log)

**Comment by cagnulein** [comment]
Now that metrics are OK, don't you see any touch event on bike tablet when you change inclination on zwift? Even on wrong position? If not enable the adb remote setting under the proform bike settings in qz, restart qz and try again


Let me know

**Comment by Mrcholliday** [comment]
Hi no on the QZ fitness app the inclination tile stays at zero no matter what I do and the resistance tile will only change if i manually alter it on the bikeThe ABD is set to onOn 20 Feb 2024, at 18:15, Roberto Viola ***@***.***> wrote:﻿
Now that metrics are OK, don't you see any touch event on bike tablet when you change inclination on zwift? Even on wrong position? If not enable the adb remote setting under the proform bike settings in qz, restart qz and try again
Let me know

**Comment by cagnulein** [comment]
ok so let's do a test.
from your pc, open a shell on the folder there you have adb
and run this command

`adb shell input swipe 100 200 300 400 200`

let me know the result

**Comment by Mrcholliday** [comment]
Nothing happens when I do the command. And I can’t see any log outcome. I can still ping my bike

**Comment by cagnulein** [comment]
which is the output of?

`adb devices`

**Comment by cagnulein** [comment]
that adb shell input swipe inject a swipe no matter what, so it's not about zwift or anything.
are you sure you don't see anything?
you can try to run it multiple times also changing the values (there are the x y coordinates of the screen).
Also you can enable the android developer setting that show a rectangle when there is a touch event on the bike tablet

**Comment by cagnulein** [comment]
i don't have your treadmill, anyway in the developer settings, where you also enable the usb debugging, there is a setting for the touch events (it's quite easy but i don't remember the name)

just try this, so will be evident if you can see a touch event or not

**Comment by Mrcholliday** [comment]
I have enabled ‘show taps’ under input on the bike 

And still nothing is changing unfortunately 😞 

I don’t know what parameters I can check the swipe event too. Where can I check

**Comment by cagnulein** [comment]
The `adb shell input swipe` command is used to simulate a swipe gesture on the screen of an Android device through ADB (Android Debug Bridge). This can be useful for automating interactions with the device for testing purposes or for controlling the device when direct touch input is not possible.

The basic syntax for the command is as follows:

```
adb shell input swipe [startX] [startY] [endX] [endY] [duration]
```

- **startX** and **startY**: These are the starting coordinates of the swipe, representing the point on the screen where the swipe begins.
- **endX** and **endY**: These are the ending coordinates of the swipe, representing the point on the screen where the swipe ends.
- **duration** (optional): This is the duration of the swipe in milliseconds. Specifying the duration allows you to control how fast or slow the swipe gesture should be. If not specified, the swipe will have a default duration.

For example, if you want to swipe from the center of the screen to the bottom on a device with a screen resolution of 1080x1920, you might use a command like this:

```
adb shell input swipe 540 960 540 1800
```

This command starts the swipe at the coordinates (540, 960), which is roughly the center for this hypothetical screen resolution, and ends the swipe at (540, 1800), which is near the bottom of the screen.

Adding a duration to the swipe gesture, say 300 milliseconds, would look like this:

```
adb shell input swipe 540 960 540 1800 300
```

This performs the swipe from the center to the bottom of the screen over a period of 300 milliseconds, making the swipe gesture appear faster or slower depending on the duration specified.

**Comment by Mrcholliday** [comment]
Not getting anywhere with the shell swipe instruction

I am running zwift on my tv and the qz companion on my iPad

**Comment by cagnulein** [comment]
yes that coordinates are about the tablet treadmill where the qz companion runs

**Comment by victorypoint** [comment]
@Mrcholliday, can you please upload a picture of your bike tablet while in manual workout mode?

**Comment by cagnulein** [comment]
@Mrcholliday Any news?
