### ISSUE TITLE
[BUG] Zwift Click on Linux

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#2146]
I think I read somewhere that it only works on Android, but is changing gears with Zwift Click supposed to work in Linux? It seems to pair OK, but as soon as I press a button, the application exits with a segmentation fault.

Debug log attached, but the last line is always:
Debug: devices/bike.cpp void bike::setGears(double) setGears -1

Device: Banana Pi M2 Zero
OS: Armbian 23.11

[debug-Tue_Feb_20_22_57_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14352337/debug-Tue_Feb_20_22_57_07_2024.log)

**Comment by cagnulein** [comment]
@smulrine did you build the latest version of the master? because yesterday i fixed a crash on android that could also be the same thing that you are seeing
Let me know

**Comment by smulrine** [comment]
Yes, working great now, thanks!

**Comment by cagnulein** [comment]
Amazing!
