### ISSUE TITLE
No shifting in Zwift

### ISSUE THREAD

**Issue by RobertoHerradura** [cagnulein/qdomyos-zwift#2151]
Hi Roberto,

I'm Roberto you've been helping me with the virtual gearing in Zwift.
The android version didn't workout for me.

Now on the PC version.
The avatar is moving but there's no resistance change when shifting from zero to 200.... I feel no change , nothing.

I hope you can help me and the debug log is useful.

Best regards,

Roberto
[debug-wo_feb_21_19_30_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14364232/debug-wo_feb_21_19_30_54_2024.log)

**Comment by cagnulein** [comment]
hi @RobertoHerradura sorry i completely missed the notification for this. are you still need help with this?

**Comment by RobertoHerradura** [comment]
You're too busy and can't remember we solved this through messenger 🤣
You can close this ticket,
Thanks again.

**Comment by cagnulein** [comment]
hahaha thanks!
