### ISSUE TITLE
[REQ] Option to not save a .fit file and write current gears value to a text file for no-GUI operation

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#2155]
Running qz on a Banana Pi M2 Zero, purely for use with Zwift, I don't want it to save a .fit file which I'm not going to use (to avoid writing to the SD card), so I always comment these lines out in homeform.cpp:

<PRE>
    /* backupTimer = new QTimer(this);
       connect(backupTimer, &QTimer::timeout, this, &homeform::backup);
       backupTimer->start(1min); */
</PRE>

Even less worth implementing is this hack to write the current gears value to a text file. BPI M2Z has 0.5GB of RAM and won't run the GUI without a swapfile, but I just need to display the gear (on a tiny HDMI screen). Immediately before _if (settings.value(QZSettings::gears_gain, QZSettings::default_gears_gain).toDouble() == 1.0)_ in homeform.cpp I added this and it totally worked (/tmp is in virtual memory in Armbian):

<PRE>
       QFile gearsFile("/tmp/gears.out");
       gearsFile.open(QFile::WriteOnly | QFile::Text);
       QTextStream ts(&gearsFile);
       ts << (((bike *)bluetoothManager->device())->gears());
       gearsFile.close();
</PRE>

Then I have this crude script which runs from systemd with output on /dev/console (I had to install sysvbanner):

<PRE>
#!/bin/sh

while true; do
  clear
  banner `cat /tmp/gears.out 2>/dev/null`
  sleep 0.5
done
</PRE>

Works exactly as intended with very light overheads although I have only performed minimal testing. I don't think it would be useful to very many people though, probably not worth adding to the codebase :smile:

**Comment by cagnulein** [comment]
Why don't you simply use a tmpfs for the running folder of qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 19:33 smulrine ***@***.***> ha
scritto:

**Comment by smulrine** [comment]
Indeed, WorkingDirectory=/tmp in the service file did the trick, thanks :+1:

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno sab 24 feb 2024 alle 21:35 smulrine ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
for the gear patch, if you want do a pr and link it to a new command line
arguments

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 21:37 cagnulein ***@***.***> ha
scritto:

**Comment by smulrine** [comment]
I wouldn't risk it, I know nothing about Qt5 programming and was surprised enough when that worked :smile:

**Comment by cagnulein** [comment]
lol

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 18:19 smulrine ***@***.***> ha
scritto:
