### ISSUE TITLE
[BUG] Zwift not receiving power data 

### ISSUE THREAD

**Issue by lefty175** [cagnulein/qdomyos-zwift#2156]
**Describe the bug**
Zwift does not receive power data from qdomyos-Zwift app despite it reading power data from Echelon Connect EX-4S. Issue happens with both the experimental echelon shifting enabled or disabled. 

**To Reproduce**
Followed all connection instructions. 

**Expected behavior**
Expected power, HR, and cadence data to be sent to Zwift. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios for iPad 
 - Version [e.g. 22] 17.3.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max 
 - OS: [e.g. iOS8.1] iOS 
 - Version [e.g. 22] 17.3.1
[debug-Sat_Feb_24_09_37_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14394252/debug-Sat_Feb_24_09_37_32_2024.log)
[debug-Sat_Feb_24_09_37_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14394253/debug-Sat_Feb_24_09_37_32_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Can you show me the pairing screen on zwift while you are trying to pair it
with qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 20:46 lefty175 ***@***.***> ha
scritto:

**Comment by lefty175** [comment]
So, this is kind of weird. Everything seems to be working now. I’m going to try here in a few to actually ride and will report back my results. RussellOn Feb 24, 2024, at 09:54, Roberto Viola ***@***.***> wrote:﻿
Can you show me the pairing screen on zwift while you are trying to pair it

with qz?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 24 feb 2024 alle 20:46 lefty175 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Ok, the last zwift version seems bugged

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 21:06 lefty175 ***@***.***> ha
scritto:

**Comment by lefty175** [comment]
Hey! Just wanted to let you know, I was successfully able to do several rides back to back. The only issues I encountered was the ERG mode being a little low for all efforts. I adjusted the sensitivity of ERG adjustments but didn’t try another ERG based ride today. I’ll probably try one tomorrow and can report back on that, although I’m wondering if you have any other advice on tweaks for that? Thank you,RussellOn Feb 24, 2024, at 10:07, Roberto Viola ***@***.***> wrote:﻿
Ok, the last zwift version seems bugged



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 24 feb 2024 alle 21:06 lefty175 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
for erg mode you need to increase the ftp value on zwift

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 23:42 lefty175 ***@***.***> ha
scritto:
