### ISSUE TITLE
[BUG] Tacx Neo flywheel spins up when freewheeling in a low virtual gear

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#2157]
I doubt anything can be done about this, but when using virtual gears, if you shift down to a sufficiently low gear, the Neo thinks you are going downhill and will spin the flywheel of its own accord :smile:

**Comment by cagnulein** [comment]
i can put a limit to this yes :)
if inclinations + gears are negative put 0
something like this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 feb 2024 alle 21:45 smulrine ***@***.***> ha
scritto:

**Comment by smulrine** [comment]
If the Neo spins the flywheel itself for a negative gradient (and no power) then wouldn't you have to send a gradient of 0 to stop it? Tested it myself today - on a flat section I set the gears to a negative number and stopped pedalling, and the flywheel started spinning itself. I got around it by switching to the small chainring, so I almost never have to set the gears below 0, and certainly not when on the flat or in such a way that gradient + gears would be negative.

Sometimes when freewheeling downhill I see strange RPM numbers, so it might be an idea to force the cadence to zero for extremely low power values (< 5W) when the gradient is negative. Screenshot:
![freewheel](https://github.com/cagnulein/qdomyos-zwift/assets/26405600/d16edaaa-7879-4c05-a04e-5ceab30493f0)

**Comment by cagnulein** [comment]
That's crazy :)

**Comment by cagnulein** [comment]
Do you have a debug log of this scenario?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 18:42 smulrine ***@***.***> ha
scritto:

**Comment by smulrine** [comment]
Unfortunately not, will try to save it next time I see it happening (although I don't climb up big hills very often). It would not surprise me if the Neo is sending the bogus RPM figures but Zwift knows to filter them out because of the flywheel-spinning feature.

**Comment by cagnulein** [comment]
Ok it should be easy to fix it as well
I just want to be sure to put the patch on the right place

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 18:56 smulrine ***@***.***> ha
scritto:

**Comment by smulrine** [comment]
Got the debug log from a short (mostly) downhill ride. I stopped pedalling completely after about 1:15 and then had plenty of phantom RPM from about 1:30 onwards.

[debug-Mon_Feb_26_19_33_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14410031/debug-Mon_Feb_26_19_33_33_2024.log)

**Comment by cagnulein** [comment]
hi @smulrine unfortunately on the linux build i can't see the messages because they are linked to the UI. Are you able to generate the same from the android build for example? otherwise i will decouple the log from the UI. Let me know

**Comment by smulrine** [comment]
I can certainly re-run the test with the UI enabled later on today, probably this evening.

**Comment by cagnulein** [comment]
Ok thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle ore 11:11 smulrine ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i still don't see any log. I guess you were not using the QML interface,
right? Can't you?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle ore 15:26 smulrine ***@***.***>
ha scritto:

**Comment by smulrine** [comment]
Strange, I enabled a swapfile and ran it with
QT_QPA_PLATFORM=eglfs /opt/qdomyos-zwift/bin/qdomyos-zwift -no-log -no-heart-service -qml
with log_debug enabled in the config file, and I could see the tiles on the screen OK. Do I maybe need to remove "-no-log"?

**Comment by cagnulein** [comment]
yes i guess the -no-log is the culprit

Let me know, otherwise I will change the source code to log it anyway

**Comment by smulrine** [comment]
Will give it another try this evening. Is there any particular field you are looking for in the log file, so I can make sure it's there before I upload it?

**Comment by cagnulein** [comment]
yes look for "current cadence"
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle ore 17:09 smulrine ***@***.***>
ha scritto:

**Comment by smulrine** [comment]
Got it! Phantom RPM for a few seconds at 1:53 and 2:24 while freewheeling.
[debug-Tue_Feb_27_19_54_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14425055/debug-Tue_Feb_27_19_54_31_2024.log)

**Comment by cagnulein** [comment]
Great, I will check it tomorrow. What was the issue  so?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle 21:02 smulrine ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/83bbc8a3-5faa-49e7-b995-65a0ad5c72d3)

Ok perfect so this is a sample of the ghost

**Comment by smulrine** [comment]
Yes, that's it, only ever happens when the flywheel is spinning automatically due to the negative gradient.

It was removing -no-log which made the difference. Also, this time I forgot to enable the swapfile but the UI still worked in 512MB, possibly because I had disabled a few tiles. (If I go into Settings without the swapfile it would crash for sure.)

**Comment by cagnulein** [comment]
done! update from master and build it. Let me know if it's better

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle ore 21:29 smulrine ***@***.***>
ha scritto:

**Comment by smulrine** [comment]
Confirmed, rode the same downhill route with the flywheel spinning and no pedalling, and the power stayed at 0W all the way down - thanks for the rapid fix!

Since the UI loaded OK without a swapfile, I didn't apply my patch to write the gears value to a file, and my device now boots straight into the UI :smile:

**Comment by cagnulein** [comment]
that's great!
