### ISSUE TITLE
[BUG] Two Concurrent Peloton Workouts: QZ replaces workout name even if second user chooses "No" to follow the resistance.

### ISSUE THREAD

**Issue by BarristQL** [cagnulein/qdomyos-zwift#2158]
**Describe the bug**
This occurs when two users want to work out with Peloton app + QZ at the same time (one on bike, one on rower). 

When second user starts workout on Peloton app, it replaces the workout name of the first user automatically even if they choose "No" to follow the second user's workout.

**To Reproduce**

**Example of current behaviour with two Peloton workouts at the same time:**

1. **User 1** starts a cycling workout in the Peloton app, loads resistance metrics in QZ and begins the workout as normal.
2. **User 2** starts a rowing workout in the Peloton app.
3. Pop-up to ask to follow rowing resistance shows appears on both Users' QZ apps
4. **User 1** chooses "No", but rowing workout name has already automatically replaced cycling workout name.
5. **User 2** chooses "Yes", and rowing workout begins as normal.

**Expected behavior**
Workout name for **User 1** shouldn't change unless user selects "Yes" to follow the resistance.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini + iPhone 14 Pro
 - OS: iOS 17.3.1
 - QZ Version 2.16

**Comment by cagnulein** [comment]
Thanks, can you append a debug log?

**Comment by BarristQL** [comment]
Darn, forgot to turn on Debug Log in settings before today's workout. I can do it next time!

**Comment by BarristQL** [comment]
Attaching log. For this one, I began a 10 Minute Low Impact Workout on the bike. Then a 20 minute HIIT rowing workout was started on another device. I clicked No when it asked if I wanted to follow the rowing resistance, but the name was already changed to the rowing workout's name. Hope you can make sense of the log!
[debug-Mon_Feb_26_15_21_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14411077/debug-Mon_Feb_26_15_21_44_2024.log)

**Comment by cagnulein** [comment]
Great! Thanks! I'll check it tomorrow!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 feb 2024 alle 21:46 BarristQL ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@BarristQL done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS so I will send you the beta. Thanks
Unfortunately I can't test myself this mod since Peloton is not allowed in Italy.

**Comment by BarristQL** [comment]
Thanks again. Did a quick test and it seems to work (second workout does not replace the first user's workout name if they click No). Will do a full workout soon to test it more thoroughly.  Only minor thing so far (not a big deal) is that after the workout, it seems to save the image of the second workout. Here you see this Cycling workout that has the image from the rowing workout.

**Comment by cagnulein** [comment]
thanks! fixed too! i'm sending you this new one too!

**Comment by cagnulein** [comment]
Yes I will send you it in 30 minutes

**Comment by BarristQL** [comment]
Yes seems to be working as expected! Thanks again.

**Comment by BarristQL** [comment]
Sorry, one thing we noticed is that the person who finishes their workout last, their workout is saved as the incorrect type of workout in Strava. E.g. my wife finished her cycling workout after my rowing workout and her workout was recorded as rowing in Strava. I'll try to get a debug log for next time.

**Comment by cagnulein** [comment]
that's strange! yes a debug log
would be very helpful

**Comment by cagnulein** [comment]
that's another issue :) on apple health you are in charge of the type of
the workout changing the workout type on the apple watch app :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 8 mar 2024 alle 08:26 BarristQL ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
in which one what should I check? it was a bike session right? could you please link the strava activity? and also the fit file on the qz folder or received by email? and also the email sent so i have the whole universe. Thanks

**Comment by BarristQL** [comment]
> in which one what should I check? it was a bike session right? could you please link the strava activity? and also the fit file on the qz folder or received by email? and also the email sent so i have the whole universe. Thanks

No problem.

It was a bike session:
- She started her bike session first
- I started my rowing shortly after
- I was still in my rowing session when she finished, and that was when it marked it as a rowing workout in Strava (Strava Link: https://www.strava.com/activities/10971357812)
- Attached the FIT file and email received after the workout.

[FIT file and email.zip](https://github.com/cagnulein/qdomyos-zwift/files/14640438/FIT.file.and.email.zip)

Thanks for looking into it!

**Comment by cagnulein** [comment]
Thanks, I will check tomorrow  deeply the files.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 mar 2024 alle 18:46 BarristQL ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@BarristQL something is not right :)

i checked the fit file and it's ok

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/22bcdb0d-3244-4212-8707-890f38e6a3c6)

then i checked the log again and the log shows that the user has a "#qzfitness" tag to append to strava but i don't see it in the https://www.strava.com/activities/10971357812

So i'm wondering if that activity comes directly from QZ or any other connected services. You can check on strava, download the original fit file from there, if it matches with the one in the zip file here https://github.com/cagnulein/qdomyos-zwift/files/14640438/FIT.file.and.email.zip

I guess not :)

Let me know!

**Comment by cagnulein** [comment]
@BarristQL any news?
