### ISSUE TITLE
Live Chart for Power and Heart Rate

### ISSUE THREAD

**Issue by GHBBL** [cagnulein/qdomyos-zwift#2159]
It would be great to see a live charts for current power and heart rate similar to the attached, except instead of the average information show above the charts, show the current power, heart rate and cadence which most riders are interested in.

![IMG_2305](https://github.com/cagnulein/qdomyos-zwift/assets/161251007/88e48061-39e8-4d3d-89de-c44c10f857fa)

**Comment by cagnulein** [comment]
hi @GHBBL 

did you see the real time power chart in the beta? if not i can send you the beta in order to see if it's what you need

**Comment by GHBBL** [comment]
I did not see the beta. I am not sure how/where
 to get the beta. Thanks so much of the quick response!

**Comment by cagnulein** [comment]
I just sent it. Download it and when you will do a power zone workout, you
will see the chart icon on the top right corner of the app. Let me know.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 21:39 GHBBL ***@***.***> ha
scritto:

> I did not see the beta. I am not sure how/where
> to get the beta. Thanks so much of the quick response!
>

**Comment by GHBBL** [comment]
I just got it. Will try it out shorty. Thanks

**Comment by GHBBL** [comment]
Hi Roberto, I’m using QZ as a stand alone app and just reading the metrics from the tiles I selected when I do my own HIIT or aerobic rides. I am not following power zone workouts from any other app. I was just looking for live charts while I ride to keep track of my progress (e.g. how many cycles of HIIT I have completed so far, etc). Thanks again.

**Comment by cagnulein** [comment]
yeah you can do power zone rides even with qz standalone! it's what i'm
doing everyday :)

just load a train program from the default ones if you want to try it.

so it will give you a feedback of what i did so far

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 feb 2024 alle 22:11 GHBBL ***@***.***> ha
scritto:

> Hi Roberto, I’m using QZ as a stand alone app and just reading the metrics
> from the tiles I selected when I do my own HIIT or aerobic rides. I am not
> following power zone workouts from any other app. I was just looking for
> live charts while I ride to keep track of my progress (e.g. how many cycles
> of HIIT I have completed so far, etc). Thanks again.
>

**Comment by GHBBL** [comment]
That worked great! I had not loaded a training program so could not see the graph. Your app rocks!.

Like many other IC4 owners, I had searched many times over the past year for a simple app that would be able to show the IC4 power and cadence which are not show on the bike. I used search terms including indoor bike, exercise bike, spin bike, indoor fitness equipment, IC4, etc. I tried every one and a few like Kinetic Fit or TrainerDay could read bike data, but not aways correctly (Kinetic show my speed off by 10x). The only way I found QZ was when I search for FTMS. I know QZ can do much more than I need, but finally success! I will write a review. 5 Stars for sure.
 
Thanks
Bruce

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno lun 26 feb 2024 alle 00:01 GHBBL ***@***.***> ha
scritto:

> That worked great! I had not loaded a training program so could not see
> the graph. Your app rocks!.
>
> Like many other IC4 owners, I had searched many times over the past year
> for a simple app that would be able to show the IC4 power and cadence which
> are not show on the bike. I used search terms including indoor bike,
> exercise bike, spin bike, indoor fitness equipment, IC4, etc. I tried every
> one and a few like Kinetic Fit or TrainerDay could read bike data, but not
> aways correctly (Kinetic show my speed off by 10x). The only way I found QZ
> was when I search for FTMS. I know QZ can do much more than I need, but
> finally success! I will write a review. 5 Stars for sure.
>
> Thanks
> Bruce
>
>

**Comment by GHBBL** [comment]
Roberto, a while back I contacted you about using QZ as a standalone app on my iPhone for my indoor bike. I was hoping to do a ride and see a live charts of my heart rate and power as I ride, but can get it to work with the most recent V2.16.6. Can you walk me through the steps on how to load a training program, start the ride, and then view live charts? I tried opening a training program but dont see anything after I select?

Thanks again
Bruce

**Comment by GHBBL** [comment]
Robert, I was able to get it to work after re-loading the app and rebooting my phone. I was able to see the live chart of power when I loaded a training program. Is it possible to see two live charts at the same time so I can see HR chart and power charts? I only have a few tiles displayed.

**Comment by cagnulein** [comment]
I didn't add hr live chart but it's possible. Do you need on the same chart?

**Comment by GHBBL** [comment]
It doesn’t need to be on the same chart. Just something like what you get if you click Chart after you finish would be great.

**Comment by GHBBL** [comment]
The only reason I like the power and HR charts is I am an old guy and sometimes when I do my intervals I forget how many cycles I have done and the charts are great for keeping track.

**Comment by cagnulein** [comment]
Ok, thanks.
I will think about

Il giorno ven 5 lug 2024 alle 20:58 GHBBL ***@***.***> ha
scritto:

> It doesn’t need to be on the same chart. Just something like what you get
> if you click Chart after you finish would be great.
>
>
>
>

**Comment by cagnulein** [comment]
since for me it's very easy to add on the same charts with a different color (for example red), would be ok?

**Comment by GHBBL** [comment]
That would be great. Thanks Sent from my iPhoneOn Jul 8, 2024, at 10:49 AM, Roberto Viola ***@***.***> wrote:﻿ since for me it's very easy to add on the same charts with a different color (for example red), would be ok? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this bec 

since for me it's very easy to add on the same charts with a different color (for example red), would be ok?

**Comment by cagnulein** [comment]
done @GHBBL ! I will test this, this evening and I will send you the beta if it's everything allright. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by GHBBL** [comment]
Outstanding as always. ThanksSent from my iPhoneOn Jul 10, 2024, at 7:50 AM, Roberto Viola ***@***.***> wrote:﻿ done @GHBBL ! I will test this, this evening and I will send you the beta if it's everything allright. send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android 

done @GHBBL ! I will test this, this evening and I will send you the beta if it's everything allright.
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@GHBBL remember to send me the email to roberto.viola83 at gmail.com

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/f087f6fb-865f-47e8-837c-b9e4b2b19330)

i have to fix a little the layout but it's working  ;)
