### ISSUE TITLE
The Technogym Excite Unity RUN 1000 Treadmill 

### ISSUE THREAD

**Issue by Melbtrip** [cagnulein/qdomyos-zwift#2166]
It be good if can connect with 
The Technogym Excite Unity RUN 1000 Treadmill with Unity 3.0

nRF Connect, 2024-02-28
RUN EXCITE 1402 (0C:1C:57:BE:6A:0F)
V	18:42:40.624	Connecting to 0C:1C:57:BE:6A:0F...
D	18:42:40.624	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	18:42:40.757	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	18:42:40.757	Connected to 0C:1C:57:BE:6A:0F
D	18:42:40.760	wait(1600ms)
D	18:42:40.807	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
I	18:42:41.241	Connection parameters updated (interval: 11.25ms, latency: 0, timeout: 20000ms)
I	18:42:41.349	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
I	18:42:41.547	Connection parameters updated (interval: 11.25ms, latency: 0, timeout: 20000ms)
I	18:42:41.878	Connection parameters updated (interval: 48.75ms, latency: 0, timeout: 5000ms)
V	18:42:42.366	Discovering services...
D	18:42:42.366	gatt.discoverServices()
D	18:42:42.405	[Callback] Services discovered with status: 0
I	18:42:42.406	Services discovered
V	18:42:42.424	Generic Attribute (0x1801)
- Service Changed [I] (0x2A05)
Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Unknown Service (ae4a2645-916e-4d6b-8884-500b6a2e244c)
- Unknown Characteristic [R W] (cf69e44f-4f89-44eb-a642-773e3acdb2dc)
- Unknown Characteristic [N] (1d160b86-073b-11e8-ba89-0ed5f89f718b)
   Client Characteristic Configuration (0x2902)
D	18:42:42.424	gatt.setCharacteristicNotification(1d160b86-073b-11e8-ba89-0ed5f89f718b, true)
[Log 2024-02-28 18_42_40.txt](https://github.com/cagnulein/qdomyos-zwift/files/14434953/Log.2024-02-28.18_42_40.txt)
[Log 2024-02-28 18_42_40.txt](https://github.com/cagnulein/qdomyos-zwift/files/14434965/Log.2024-02-28.18_42_40.txt)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
Hi! are you able to get the metrics into any app (for example the tecnogym app)? If so follow this with that one https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md
Let me know!

**Comment by cagnulein** [comment]
@Melbtrip any news?
