### ISSUE TITLE
[BUG] Domyos Incline Run resets to 0% incline above 15% on the treadmill

### ISSUE THREAD

**Issue by sergestoord** [cagnulein/qdomyos-zwift#2169]
**Describe the bug**
When using the Domyos Incline Run (which goes to 20% incline) above 15% incline the app reverts to 0.0% and disregards further incline information. The Domyos app works just fine above 15%. 

**To Reproduce**
1. Set incline above 15% on treadmill
2. QZ app jumps back to 0.0
3. Incline information is disregarded
4. No further error

**Expected behavior**
App should respond to 15%+ incline. 

**Screenshots**
[https://youtu.be/PvtBtGaCfO4?si=qWrUp7tuQZZLWzxE](url)

**Smartphone (please complete the following information):**
 - Device: iPad Air 5 or iPhone 15
 - OS: 17.3.1
 - Version [e.g. 22] 2.16.46 (is beta after Roberto tried to patch is. 

**Append a debug log**
[debug-do_feb_29_20_36_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14452859/debug-do_feb_29_20_36_46_2024.log)

  
  
**Additional context**
Love the app furthermore!

**Comment by cagnulein** [comment]
hi @sergestoord in this log i can't see you changing more than 1% 

i need a log where you are generating the issue

thanks

**Comment by sergestoord** [comment]
That’s weird just tried again. See attached. 
Did notice when using the app to change incline (for instance with shortcuts) the treadmill does respond but the app still reads 0.0 with no elevation gain. 
[debug-do_feb_29_21_04_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14453045/debug-do_feb_29_21_04_05_2024.log)

**Comment by cagnulein** [comment]
got the issue! a stupid variable casting! i will fix this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 feb 2024 alle 21:09 sergestoord ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fixed now, i'm sending it in 30 minutes
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 feb 2024 alle ore 21:19 cagnulein ***@***.***> ha
scritto:

**Comment by sergestoord** [comment]
Amazing, works like a charm!

**Comment by cagnulein** [comment]
glad to hear this! remember to rate the app on the store! it means a lot to me! thanks!
