### ISSUE TITLE
Not really a bug but I don’t understand what was happening,

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#2170]
After I finished a ride and had stopped peddling and had actually gotten off the TDF 5 bike my Zwift avatar kept going for two miles before I stopped the QZ app on my phone. It was going up and down hills and gaining speed and slowing down. Just like I was still peddling. I don’t know how long it would have kept going by itself? 
[debug-Thu_Feb_29_14_23_38_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14454702/debug-Thu_Feb_29_14_23_38_2024.zip)
[debug-Thu_Feb_29_14_23_38_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14454709/debug-Thu_Feb_29_14_23_38_2024.zip)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Dwhetsel can you tell me the right timeframe? because I checked the log and the cadence was changing from the bike like you were riding (changing values, not a fixed one) for the whole file
Let me know

**Comment by Dwhetsel** [comment]
All I know is the Zwift ride ended at 15.3 miles. That is about the mileage I stopped peddling. I then let it go by itself until mile 18. If I remember correctly the metrics on QZ continued to show as it did on Zwift. I will try to see if it does it again later today and see if I can video it with another device.

**Comment by cagnulein** [comment]
@Dwhetsel what I see in the log is that for the whole log someone is riding the bike or at least the bike is sending the metrics correctly (changing them, so they are not ghost metrics). So I completely don't understand :D

**Comment by Dwhetsel** [comment]
I know, it was strange. The peddles were not moving and the flywheel had stopped. I stood next to the bike and watched while it ( the avatar) continued on for two miles.

**Comment by cagnulein** [comment]
@Dwhetsel and you saw what I'm saying so that the cadence was changing in the time? like someone is riding? or the cadence was stuck (important: the cadence, not the speed)

**Comment by Dwhetsel** [comment]
Here is another debug from today along with a video of what it’s doing. I think maybe it’s getting the data from my watch for HR and that is what is keeping Zwift going. I have tried to attach a zipped video but it still says it’s too large. Can I send it somewhere else for you to see (if you want)? The cadence does not show on QZ.
[debug-Fri_Mar_1_13_29_43_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14465261/debug-Fri_Mar_1_13_29_43_2024.zip)

**Comment by cagnulein** [comment]
share it on google drive and it the link here

**Comment by Dwhetsel** [comment]
Google Drive: Sign-indrive.google.comOn Mar 1, 2024, at 2:01 PM, Roberto Viola ***@***.***> wrote:﻿
share it on google drive and it the link here

**Comment by cagnulein** [comment]
Sorry I don't see anything. Write directly on github

**Comment by Dwhetsel** [comment]
https://drive.google.com/file/d/1nLiTvvldshH0xmHvJFxzJ5gLSu78w4vG/view?usp=drivesdk

Hopefully this will work.

**Comment by cagnulein** [comment]
i asked access

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle 13:30 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
It should be granted now


Sent from AT&T Yahoo Mail for iPad


On Saturday, March 2, 2024, 6:31 AM, Roberto Viola ***@***.***> wrote:



i asked access

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle 13:30 Dwhetsel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
yes got it. question: which devices do you use in the zwift pair screen?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle 13:34 Dwhetsel ***@***.***> ha
scritto:

> It should be granted now
>
>
> Sent from AT&T Yahoo Mail for iPad
>
>

**Comment by Dwhetsel** [comment]
I believe it was the Whoo kicker for all except HR, it was IPhone (with Apple Watch)

**Comment by cagnulein** [comment]
ok perfect i will match the video with the debug log and i will check the
metrics

i will get to you asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle 13:39 Dwhetsel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Here is another debug from today along with a video of what it’s doing. I think maybe it’s getting the data from my watch for HR and that is what is keeping Zwift going. I have tried to attach a zipped video but it still says it’s too large. Can I send it somewhere else for you to see (if you want)? The cadence does not show on QZ. [debug-Fri_Mar_1_13_29_43_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14465261/debug-Fri_Mar_1_13_29_43_2024.zip)

@Dwhetsel i was trying to match the video with the log, but the log is about the next version. in the video I see 13:25. Do you have a previous log?

**Comment by Dwhetsel** [comment]
Not sure how the debug recorder works but here is what is listed from yesterday. Want me to send them all?
![IMG_6336](https://github.com/cagnulein/qdomyos-zwift/assets/117591496/62510c50-4246-4b50-9e06-e8569b208d3c)

**Comment by cagnulein** [comment]
the timestamp in the filename is when the workout start. anyway yes send
them all, i will get the right one :)
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle ore 14:02 Dwhetsel ***@***.***>
ha scritto:

**Comment by Dwhetsel** [comment]
I only started it once yesterday and then started the video soon after.
[debug-Fri_Mar_1_13_21_33_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14469446/debug-Fri_Mar_1_13_21_33_2024.zip)
[debug-Fri_Mar_1_13_29_43_2024 3.zip](https://github.com/cagnulein/qdomyos-zwift/files/14469447/debug-Fri_Mar_1_13_29_43_2024.3.zip)
[debug-Fri_Mar_1_13_29_43_2024 2.zip](https://github.com/cagnulein/qdomyos-zwift/files/14469448/debug-Fri_Mar_1_13_29_43_2024.2.zip)

**Comment by cagnulein** [comment]
got the issue: when you put the workout in pause on the bike, the bike stops to send data and so qz is using the last value got. I can put a timeout for this

**Comment by cagnulein** [comment]
done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by Dwhetsel** [comment]
How does it go into pause? If I stop peddling I have to wait for the end workout button to come up on the bike screen and then I usually stop it on the app. Seems like in the past the avatar would stop moving when I stopped pedaling.
Is the time out going to go into effect when I stop now?

**Comment by cagnulein** [comment]
> How does it go into pause? I

in your video it's in pause (do you see the resume button on the bike?) I guess it's auto pause when the cadence is 0.

anyway as I said i added a timeout, so the next version it will have a fix so you don't have to do anything different

**Comment by cagnulein** [comment]
@Dwhetsel any news?
