### ISSUE TITLE
[BUG] QZ app doesn't control inclination Nordictrack x22i

### ISSUE THREAD

**Issue by marsalbon** [cagnulein/qdomyos-zwift#2171]
Hi there

I installed QZ app and QZ companion on my Nordictrack x22i. All works well, the QZ tiles show all the data and Zwift works fine. However, I can't control the inclination using QZ app, noting happens. Any ideas? Does "adb remote" need to be enabled with QZ version 2.15.4?

Best
Marco

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi first of all could you please attach a debug log from qz where you try to change the inclination from qz itself? don't you see a virtual touch event on the treadmil tablet when you're doing so?

**Comment by cagnulein** [comment]
check this also https://github.com/cagnulein/qdomyos-zwift/issues/1916

i'm sending you the new beta for ios

**Comment by cagnulein** [comment]
and yes enable the adb remote

**Comment by marsalbon** [comment]
many thanks. I installed the beta and enabled adb remote. I can now control the incline using the QZ app but somehow, the inclination is "messed up". Example: i set it to 3%, it goes up to 3% and then without touching back to 1%. Or I go to 9%, it stops there for a while and goes up to 25%...Please find the log attached
[debug-Fr__März_1_14_38_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14461786/debug-Fr__Marz_1_14_38_50_2024.log)

**Comment by cagnulein** [comment]
in the log the x22i setting is disabled. Enable it in the settings, treadmill, nordictrack settings and restart QZ
Let me know!

**Comment by marsalbon** [comment]
[debug-Fr__März_1_15_03_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14462000/debug-Fr__Marz_1_15_03_36_2024.log)
Yes that worked. I now adapts the inclination using Zwift but somehow changes inclination every 5 seconds while Zwift indicates no inclination change at all.

**Comment by cagnulein** [comment]
hi this is not a zwift session log. could you send a file with the issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 mar 2024 alle 15:05 marsalbon ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@marsalbon any news?

**Comment by marsalbon** [comment]
Hi RobertoUnfortunately not. Somehow it stopped working at all. The companion app on the treadmill is up and running but the iphone app hardly receives any data or loses the connection and stops showing data after 2-3 minutes (speed). Reading all the positive comments about your app, I‘m sure the problem is on my end.BestMarcoVon meinem iPad gesendetAm 31.03.2024 um 04:49 schrieb Roberto Viola ***@***.***>:﻿
@marsalbon any news?

**Comment by marsalbon** [comment]
Herr you Go. Von meinem iPhone gesendetAm 01.04.2024 um 10:06 schrieb Roberto Viola ***@***.***>:﻿
Hi, if you want we can investigate it, but I need the log from the companion in order to understand what's the issue on your end.
You need to run the adb-log batch file from the install package
Let me know!

**Comment by cagnulein** [comment]
you have to upload it on the github interface directly otherwise I can't see it

**Comment by marsalbon** [comment]
debug-Mo__Apr__1_11_08_47_2024.log

**Comment by marsalbon** [comment]
[debug-Mo__Apr__1_11_08_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14821979/debug-Mo__Apr__1_11_08_47_2024.log)

**Comment by marsalbon** [comment]
It seems I don't have any connection between the treadmill (companion app) and the app. The IP ping works fine...

**Comment by cagnulein** [comment]
This is from qz, what I asked it's a log from adb while the workout is running with the logcat batch file. Are you able to provide this?

**Comment by cagnulein** [comment]
Hi the log is truncated but it seems that you put the ip in the wrong setting. show me where you put it

**Comment by marsalbon** [comment]
The IP is Treadmill Options > Proform / Nordictrack Options > Nordictrack 2950 IP (ADB Remote on). Is that incorrect?

**Comment by cagnulein** [comment]
that's correct but the log you provided shows that you have also the ip on another setting. please send me a new one not corrupted and i will show you

**Comment by marsalbon** [comment]
Yes I also typed it in the Proform IP field. But I tried several times just with the Nordictrack IP field only and that didn‘t work either. I appreciate all your held but I think I‘m going to quit here. I‘ve spent several hours on this and the wife starts getting mad :) I don‘t even know what an adb log is. Thanks for all your help!

**Comment by cagnulein** [comment]
ok in case i can help you, i just need a clean debug log.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 1 apr 2024 alle 12:00 marsalbon ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I'm out of town now (bank day here in Italy). I will check it tomorrow
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 1 apr 2024 alle 16:58 marsalbon ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @marsalbon I checked the logs.
From the logcat side (that's correct, it's helpful, i don't know if you collect it while you were doing a workout?) qz companion is acting right (i can actually just see a Wattage 102 from the 16:33), instead the qz app can't receive any frame from the companion.

This could be due to the router that it's filtering out the broadcast frames. Are both devices connected to the same access point with the same frequency?

Another thing that you can try is to install the qz app on the PC directly from here https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip
This could talk directly with adb on your treadmill.

Let me know!

**Comment by marsalbon** [comment]
Thanks, I’ll try it this evening. I usually work on mac, is the app available for mac too? Otherwise I still have a windows laptop laying around somewhere.BestMarcoVon meinem iPad gesendetAm 02.04.2024 um 08:48 schrieb Roberto Viola ***@***.***>:﻿
hi @marsalbon I checked the logs.
From the logcat side (that's correct, it's helpful, i don't know if you collect it while you were doing a workout?) qz companion is acting right (i can actually just see a Wattage 102 from the 16:33), instead the qz app can't receive any frame from the companion.
This could be due to the router that it's filtering out the broadcast frames. Are both devices connected to the same access point with the same frequency?
Another thing that you can try is to install the qz app on the PC directly from here https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip
This could talk directly with adb on your treadmill.
Let me know!

**Comment by cagnulein** [comment]
the adb part is available only on pc for now, so I suggest to start with this.

**Comment by marsalbon** [comment]
We’re getting there. It works fine on pc except inclination (i cant change it through qz). Seems there is some issue with my phone / network that my laptop doesn’t have…

**Comment by cagnulein** [comment]
ok that's perfect! so for the inclination, you can see it but you can't change it? what about the speed instead?

**Comment by cagnulein** [comment]
@marsalbon any news?
