### ISSUE TITLE
[BUG]App showing unexpected resistance changes when clicking the + or - in the resistance tile and then stopped connecting to the bike

### ISSUE THREAD

**Issue by Mrschley** [cagnulein/qdomyos-zwift#2176]
Qz app connected to echelon ex3 bike but when i clicked on the + or - in the resistance tile it would jump up or down to a different resistance that didn't make any sense.  For example I could be at a resitance of 20, click the + and it would change to 13.  I tried restarting the app and powering down the phone running Qz.  At that point it would no longer connect to the bike via bluetooth.  It would either find something else like our washer or dryer, or not find anything at all.  I also tried unplugging and replugging the bike.

Can you tell what is going on from the debug preports?  Not sure which ones to send so sending them all from that day.

[drive-download-20240302T202100Z-001.zip](https://github.com/cagnulein/qdomyos-zwift/files/14470678/drive-download-20240302T202100Z-001.zip)

**Comment by cagnulein** [comment]
for sure your issue is about the gear setting under echelon settings marked
as experimental . disable it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 mar 2024 alle 21:24 Mrschley ***@***.***> ha
scritto:

**Comment by Mrschley** [comment]
so i can't use the gears tile?

**Comment by cagnulein** [comment]
i'm not talking about the gear tile. i'm talking about this 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/b7cf2d38-8b3f-4a7d-84b8-23e69abb5160)

disable it

**Comment by cagnulein** [comment]
also during a workout with peloton or zwift you should never use the plus and minus resistance tile. only the gear one

**Comment by Mrschley** [comment]
Thanks

**Comment by Mrschley** [comment]
I disabled it and restarted the app.  Still having issues connecting.  It
says it found the bike but it doesn't register any movement.  There is also
a "stroke rate" tile showing up so it seems to think the bike is a rower?

**Comment by Mrschley** [comment]
Looks like i fixed it.  Somehow fake rower got turned on.  I can't imagine
why I would turn that on.  Maybe I accidentally changed it.

**Comment by cagnulein** [comment]
Set your bike on the manual device setting in the advanced setting and
restart Qz. You are not connected to the bike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 16:04 Mrschley ***@***.***> ha
scritto:

> I disabled it and restarted the app. Still having issues connecting. It
> says it found the bike but it doesn't register any movement. There is also
> a "stroke rate" tile showing up so it seems to think the bike is a rower?
>
>

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno dom 3 mar 2024 alle 16:31 Mrschley ***@***.***> ha
scritto:

> Looks like i fixed it. Somehow fake rower got turned on. I can't imagine
> why I would turn that on. Maybe I accidentally changed it.
>
