### ISSUE TITLE
[BUG]Heartrate from ant+ garmin 

### ISSUE THREAD

**Issue by ChrisRunner2020** [cagnulein/qdomyos-zwift#2177]
**Describe the bug**
Cannot get heart rate to qz app and bowlfex c7.

**To Reproduce**

Did multiple options with heart rate monitor using wrist sensor on fenix 6 as well as hrm-run chest strap. 

Toggled on ant+ sensor in qz.

If I do broadcast wrist during activity, bowflex picks up heart rate then immediately drops hr. Qz doesn't get it with cheststrap at all.

**Expected behavior**

I want heart rate on my watch, qz and bike recordings. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung s23
 - updated. Ui version 6
[debug-Sat_Mar_2_21_10_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14471769/debug-Sat_Mar_2_21_10_07_2024.log)
[debug-Sat_Mar_2_21_09_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14471770/debug-Sat_Mar_2_21_09_45_2024.log)

**Additional context**
 I posted about this in the Facebook thread.

**Comment by cagnulein** [comment]
hi, with any app on your phone are you able to get hr from ant+?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle 05:28 ChrisRunner2020 <
***@***.***> ha scritto:

**Comment by ChrisRunner2020** [comment]
Hello, yes I can get heartrate on the ant+ plugin sensor app.

**Comment by cagnulein** [comment]
is your watch also be able to broadcast the heartrate via bluetooth (standard bluetooth, so for example you will see in zwift directly if it's standard).
Otherwise, I need to see a bug report from android directly in this scenario to understand the issue. it could be that transmitting and receiving ant+ is not ok for your phone.

you can also try to disable the ant cadence setting in QZ to check if at least you can see the HR on qz. if so, it means that we can't send and receive both with your setup. I can investigate this with a bug report

**Comment by ChrisRunner2020** [comment]
QZ app picked up the heartrate when I broadcasted and have wrist set as the
heart rate in qz settings. That worked for bowflex bike to capture hr as
well. At that part I was only broadcasting hr from watch and not starting
an activity on watch.

When I started using the garmin to record activity as well and broadcasting
hr during workout, that's when I get issues with hr on bike and app.

Does that make sense? I can adjust settings and debug log more as needed.
Just let me know.

**Comment by cagnulein** [comment]
so why don't you leave the ant heart disabled and use the HR as before?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 mar 2024 alle ore 18:50 ChrisRunner2020 <
***@***.***> ha scritto:

> QZ app picked up the heartrate when I broadcasted and have wrist set as
> the
> heart rate in qz settings. That worked for bowflex bike to capture hr as
> well. At that part I was only broadcasting hr from watch and not starting
> an activity on watch.
>
> When I started using the garmin to record activity as well and
> broadcasting
> hr during workout, that's when I get issues with hr on bike and app.
>
> Does that make sense? I can adjust settings and debug log more as needed.
> Just let me know.
>

**Comment by ChrisRunner2020** [comment]
Hi!

I tried again yesterday. In the app I changed the listed heart rate device
to be my watch, turned off Ant+ and selected broadcast during activity.
Before when I tried this set up I thought it was dropping on the bike after
connection. Maybe I'm confused since I changed the settings a number of
times and only recently changed to record by the watch.

All that to say, it worked for the short ride! I tested for about 10
minutes and the bike, qz and watch never dropped the HR. I wanted to have
the chest strap as an option since they're considerably more accurate and
thought I could save the watch battery by not having to toggle the
broadcast wrist sensor on and off between activities because I use the
watch for outdoor workouts too.

Would you mind answering these remaining questions?

   - MPH still seems slightly too high. Should I adjust watts, resistance
   or something else? Is there a standard adjustment for bowflex bikes? I have
   set the wheel size in the garmin watch.
   - Does player age update automatically or is that a manual change
   annually?
   - If I start using Zwift, does the process of recording a ride on the
   bike/QZ/garmin fenix change at all?
   - Is it possible to do other things on my phone while the QZ app is on
   mid ride? For example, if I continue riding and don't touch any settings,
   but minimize the app to respond to a text, then return to QZ and hit stop
   at the end of my workout, will the data mess up either feeding to watch or
   the fit file in app?

Thanks so much!

**Comment by cagnulein** [comment]
That's great!

>- MPH still seems slightly too high. Should I adjust watts, resistance or something else?

In Zwift or QZ?

> Is there a standard adjustment for bowflex bikes? 

Nope, just generic

> I have set the wheel size in the garmin watch. - Does player age update automatically or is that a manual change annually?

Manually

> - If I start using Zwift, does the process of recording a ride on the bike/QZ/garmin fenix change at all?

Nope :)

> - Is it possible to do other things on my phone while the QZ app is on mid ride? For example, if I continue riding and don't touch any settings, but minimize the app to respond to a text, then return to QZ and hit stop at the end of my workout, will the data mess up either feeding to watch or the fit file in app?


Just be sure to enable the "android notification" setting in the experimental settings. Then QZ will can go on background!
Let me know if you have any other questions!

**Comment by ChrisRunner2020** [comment]
I appreciate the quick response. Some good features hidden in the
experimental section!

I haven't started using zwift yet. Only the jnry app that's native to the
bike. Seems like the mph is too high...maybe it's just that riding indoors
doesn't compare to outdoors, and I've only rode short distance indoors so
far. I'll ride outside to compare.

I'll add the auto age update as a feature request. Could base it on date
inputed + x years so users don't need to enter dob.

Thanks again!

**Comment by cagnulein** [comment]
for the speed I strongly suggest the "speed based on power" setting on the
bike section for a better speed calculation (instead of the bike one)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle ore 06:33 ChrisRunner2020 <
***@***.***> ha scritto:

**Comment by ChrisRunner2020** [comment]
Thank you!
