### ISSUE TITLE
I.concept BH932

### ISSUE THREAD

**Issue by tri-naranjus** [cagnulein/qdomyos-zwift#2182]
Buenos dias

Tengo una I.Spada Magnetica que me gustaria conectarla por BLE al Zwift

Me gustaria saber si es necesario su software o hay que hacerle algo mas. No hay problema en comprar su software.
Queria conocer si se regula automaticamente en Zwift o Trainied Road.
Gracias

**Comment by cagnulein** [comment]
hi @tri-naranjus in order to be sure about your request, could you please install the free app nrfconnect and show me a screenshot about your bike on that software? Also are you on android or ios?
Let me know!

**Comment by tri-naranjus** [comment]
Yes, I can.

**Comment by tri-naranjus** [comment]
I have IOS

This evening i send you

**Comment by cagnulein** [comment]
ok rememebr to attach directly on github otherwise i will not see the images

**Comment by tri-naranjus** [comment]
Ok, I will.

**Comment by cagnulein** [comment]
@tri-naranjus any news?

**Comment by cagnulein** [comment]
hah ok @tri-naranjus which bike do you have now?

**Comment by tri-naranjus** [comment]
nosotros estamos buscando ahora bici pero seguramente lo dejemos para despues del verano, aqui en España ya empieza el buen tiempo

**Comment by cagnulein** [comment]
ehehe same here in Italy :)
Have a great day!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 2 apr 2024 alle ore 09:17 tri-naranjus <
***@***.***> ha scritto:
