### ISSUE TITLE
 Nordictrack s15i Studio Cycle

### ISSUE THREAD

**Issue by SomniumCycle** [cagnulein/qdomyos-zwift#2183]
**Describe the bug**
My Nordictrack s15i Studio Cycle does not seem to connect to the QZ ios Application

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):** 
 - Windows 11 Pro OS Build 22631-3155 (Only used this to install companion)
 -

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS Version 16.1

**Append a debug log**
[debug-Mon_Mar_4_08_51_46_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14482483/debug-Mon_Mar_4_08_51_46_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by SomniumCycle** [comment]
Hi @cagnulein. They are, the workout shows the time of day, but all other metrics are either "0.0" or stuck.

**Comment by cagnulein** [comment]
follow these 2 steps of the wiki https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

> - Not fixed? Ok do a factory reset to your treadmill/bike tablet but then, after the reset, DON'T update the ifit app. Reinstall the companion and give it a try!
> - use this method https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559


on this 2 methods will fix your issue

**Comment by SomniumCycle** [comment]
Sorry for the delay. I am just trying this now. Through what application am I running this:
grant the permission with adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS from a mac or a pc

**Comment by cagnulein** [comment]
amazing!
