### ISSUE TITLE
Yesoul G1M Plus

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2185]
[btsnoop_hci (12).log.zip](https://github.com/cagnulein/qdomyos-zwift/files/14490654/btsnoop_hci.12.log.zip)

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8151465364

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by d235j** [comment]
Seems to work for me!

**Comment by cagnulein** [comment]
amazing!

**Comment by mikebeccaria** [comment]
Will this also work for iOS? Are the builds with android and iOS aligned?

**Comment by cagnulein** [comment]
@mikebeccaria yes the both betas are aligned. Did you already download the ios app? if so
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
that's great. @mikebeccaria remember to rate the app on the store! It means a lot to me!
Thanks!

For the garmin you can pull the heart rate from it but you can directly send metrics to the garmin on ios. You need an android 

Let me know if you have any other questions

**Comment by mikebeccaria** [comment]
Thank you. Just to be clear, if I buy a cheap android tablet off of ebay I
will be able to connect my bike for power/cadence data etc. and utilize the
sensors in my watch (HR etc.) and have it record all relevant data in
garmin connect as an activity?
Best,
Mike

**Comment by cagnulein** [comment]
yes it must have ANT+ or you can simply attach an ANT+ usb dongle to it on android

**Comment by mikebeccaria** [comment]
Thanks Roberto,
I ordered a used Galaxy S7. I purchased and installed QZ on it, installed
Garmin Connected, connected my watch to the S7 phone (garmin connect sees
it). I turned on my bike and opened your app and the bluetooth searches and
the bike shows up in the screen title "YSM...Found" but it doesn't show the
stats from the bike like my iphone QZ app does. I also don't know how to
connect my watch/garmin stats etc. to mirror the workout in garmin connect.
Not sure what I should be connecting to what via ANT+. Can you help?
Best,
Mike

**Comment by cagnulein** [comment]
Hi did you join the beta
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

You have to see version 2.16

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 mar 2024 alle 17:24 mikebeccaria ***@***.***>
ha scritto:

**Comment by mikebeccaria** [comment]
OK I joined the beta and updated the app - I can now see my bike sensors.
Now what?
Best,
Mike

**Comment by cagnulein** [comment]
Perfect, did you enable the ant cadence setting in qz? Is the ant tester app reporting everything right?

**Comment by mikebeccaria** [comment]
I think you're going to have to provide me with some background. Is there a
different app I have to install (ant tester app?)? Is there a document or
video I should have been referring to to understand your apps usage? Sorry
for the basic questions but want to make sure I reviewed/read everything I
should have beforehand.
Best,
Mike

**Comment by mikebeccaria** [comment]
Ok I got the heart rate to show up. How do I now take an activity that I
record in qz and get it into Garmin connect?
Thanks,
Mike

**Comment by cagnulein** [comment]
hi @mikebeccaria start from this and let me know if you have any questions https://robertoviola.cloud/2023/07/06/connect-any-indoor-bike-with-your-garmin-device/

**Comment by mikebeccaria** [comment]
Hi Roberto
Your link to the article worked but the link to the app from the article is
broken. Let me know what app I should use for ant testing.
Thanks
Mike

**Comment by cagnulein** [comment]
@mikebeccaria Hi Any ant app that you can find on the store 

The ant plugins for sure it's required
