### ISSUE TITLE
Treadmill cadence sensor

### ISSUE THREAD

**Issue by fernovus** [cagnulein/qdomyos-zwift#2187]
[debug-mar_mar_5_17_25_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14498448/debug-mar_mar_5_17_25_30_2024.log)
[](url)

**Comment by cagnulein** [comment]
Ciao mi servirebbe un log dove pero'  tu veda almeno le tile. Cosi' riesco
a capire come gestirlo.
Grazie

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle ore 17:28 fernovus ***@***.***>
ha scritto:

**Comment by fernovus** [comment]
Ah quindi devo fare il log visualizzando le tile, ok.


------ Messaggio originale ------
Da "Roberto Viola" ***@***.***>
A "cagnulein/qdomyos-zwift" ***@***.***>
Cc "fernovus" ***@***.***>; "Author" ***@***.***>
Data 05/03/2024 17:31:21
Oggetto Re: [cagnulein/qdomyos-zwift] Treadmill cadence sensor (Issue 
#2187)

**Comment by cagnulein** [comment]
si esatto, grazie

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle ore 17:37 fernovus ***@***.***>
ha scritto:

**Comment by fernovus** [comment]
[debug-mar_mar_5_17_54_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14498754/debug-mar_mar_5_17_54_52_2024.log)

**Comment by cagnulein** [comment]
Perfetto ci guardo appena ho un attimo!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle 17:56 fernovus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ho trovato un problema nella tua configurazione: hai il power sensor as a
bike Abilitato.disabilitalo e riavvia QZ
inoltre metti su disabled il cadence sensor
Se non funziona girami un altro log


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 mar 2024 alle 17:57 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ti ho mandato anche l'ultima versione per essere sicuro

**Comment by fernovus** [comment]
Grazie, appena torno a casa provo



------ Messaggio originale ------
Da "Roberto Viola" ***@***.***>
A "cagnulein/qdomyos-zwift" ***@***.***>
Cc "fernovus" ***@***.***>; "Author" ***@***.***>
Data 05/03/2024 18:56:45
Oggetto Re: [cagnulein/qdomyos-zwift] Treadmill cadence sensor (Issue 
#2187)

**Comment by fernovus** [comment]
[debug-mer_mar_6_13_30_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14509894/debug-mer_mar_6_13_30_09_2024.log)
Ciao, ti mando il nuovo log ma con queste impostazioni rimane tutto a zero, sia la velocità che la cadenza.

**Comment by cagnulein** [comment]
Ho guardato il log ma la cadenza è sempre a 0 inviata dal sensore. Io credo
che quel sensore non ti rilevi i passi semplicemente quando corri. Me lo
confermi? Devi prendere un runpod

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 13:32 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
No il sensore funziona se lo abbino direttamente a Vzfit, ma in QZ non va.

**Comment by fernovus** [comment]
Il runpod è una novità per me e mi sembra interessante! Forse è la migliore soluzione.

**Comment by cagnulein** [comment]
ma va quando corri? nel log che hai mandato il sensore manda sempre 0.
magari fammi un log dove il corri per 30 secondi

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 13:41 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
E' certo che va quando corro. Secondo me è qualche altra impostazione che mastrucciando ho cambiato nell'app, perché ieri mi segnava fisso cadenza 136 rpm. Non c'è un reset delle impostazioni nell'app?

**Comment by cagnulein** [comment]
hai ragione, hai erroneamente impostato la cadence gain a 0. devi metterla a 1
stessa cosa anche per la speed gain. devi metterla a 1. i gain non possono essere a 0

**Comment by fernovus** [comment]
Ecco vedi? Sono il solito pasticcione. Appena torno a casa provo, comunque ho preso il runpod e poi vediamo anche quello. Denghiu

**Comment by cagnulein** [comment]
perche' il sensore di cadenza applicato alla corsa non da un valore di velocita', sei tu a definirlo il settaggio "Wheel Ratio:" sotto i cadence sensor setting.

Per esempio. io so che a 160 bpm faccio i 10KM/h, quindi nel mio caso sarebbe 0.0625 (ovvero 160 * 0,0625 = 10)

tu sai una cadenza e una velocita' nota?

**Comment by fernovus** [comment]
Certo, posso vedere sul display del tapis-roulant la velocità, e la cadenza nel visore. Mi pare che a 5km/h nel visore vedo 260rpm

**Comment by cagnulein** [comment]
curiosita' che tapis hai?

**Comment by fernovus** [comment]
IDS W6 con camminata nordica, ma il sensore l'ho applicato io al rullo.

**Comment by cagnulein** [comment]
non ha bluetooth immagino, in caso potresti usare una soluzione fatta con qualche rele' come abbiamo fatto con #1889 per @Ghilm1986

cosi' avresti la velocita' perfetta e anche controllabile

comunque figo l'idea di usare un tapis del genere con il visore

**Comment by fernovus** [comment]
Se aveva il bluetooth non mi sarei scervellato ad applicarci un sensore. però ovviamente misura velocità elevate rispetto alla falcata. E poi lo spazio all'interno è molto risicato: ho dovuto togliere il circuito del sensore dalla sua custodia perché non ci entrava e applicarlo dove c'era un po' di spazio; con un convertitore step-down ho ricavato la 3v di alimentazione per evitare la pila dalla scheda principale del tapis-roulant. Per questo mi urta il fatto che non si risolve questo piccolo problema.

**Comment by cagnulein** [comment]
beh se te la cavi con l'elettronica secondo me puoi gestirlo con il link che ti ho segnalato. comunque prova intanto cosi come ti ho detto, vedrai che andra'

**Comment by cagnulein** [comment]
ora il problema è che hai ftms treadmill settato sul sensore cadenza.
rimettilo su disabled e riavvia qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 19:11 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Allora, aggiornamento odierno, è arrivato il runpod, ma già ci sono problemi: il cartoncino mi dice di scaricare Zwift e calibrare il runpod, ma l'app non lo vede nemmeno! La tua app, invece lo vede e quindi l'ho abbinato alla voce sensore di cadenza; mi escono le tile ma rimangono a zero! Il sensore l'ho applicato ovviamente alla scarpa. Dove mi sono inguaiato ancora?

**Comment by cagnulein** [comment]
Non devi Metterlo come sensore cadenza ma come sensore potenza.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 13:08 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Eh l'ho fatto, ho controllato che cadenza gain e speed gain siano a 1, ma niente, rimane a 0. Però sono riuscito ad abbinarlo a Zwift e l'ho calibrato. Ovviamente ho disconnesso il bluetooth sullo smartphone per abbinarlo alla tua app sull'ipad, ma niente, rimane a 0.

**Comment by cagnulein** [comment]
ma mi hai detto di averlo abbinato il sensore cadenza! Allega qui un debug log così lo controllo per sicurezza

**Comment by fernovus** [comment]
[debug-lun_mar_11_13_35_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14558662/debug-lun_mar_11_13_35_07_2024.log)
Eccolo, mettici una pezza tu che esco pazzo ;-)

**Comment by cagnulein** [comment]
toglilo da ftms treadmill (metti disabled) e riavvia qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 13:37 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
quella era solo una prova, ma non andava nemmeno con disabled. Ma in questo caso le tile possono stare speed e cadence?

**Comment by cagnulein** [comment]
mandamelo con quello a disabled

che significa la tua domanda, non ho capito

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 13:40 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Rieccolo! Dicevo che tile devo far vedere nella schermata iniziale se non ho un sensore di cadenza ma di potenza?
[debug-lun_mar_11_13_39_40_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14558761/debug-lun_mar_11_13_39_40_2024.log)

**Comment by cagnulein** [comment]
hai power sensor as a bike abilitato. disabilitalo e riavvia QZ
nella schermata iniziale vedrai sempre le stesse tile e vedrai il valore nelle tile velocita e cadenza

**Comment by fernovus** [comment]
Anche quella era una prova e non andava già prima che era disabilitato.

**Comment by cagnulein** [comment]
mandami sempre il debug log della condizione che ti chiedo altrimenti non ti riesco a dare una mano. grazie

**Comment by fernovus** [comment]
vabbè ora sono al lavoro, stasera vedo di mandarti la situazione aggiornata. Grazie per la pazienza

**Comment by cagnulein** [comment]
ok no problem

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle ore 14:25 fernovus ***@***.***>
ha scritto:

**Comment by fernovus** [comment]
però una cosa non capisco: l'app Vzfit non mi riconosce il runpod, ma il bluetooth dell'oculus invece lo vede! Me lo sai spiegare?

**Comment by cagnulein** [comment]
vzfit cerca un device ftms, oculus invece come qz vede tutti i device.
ma per il sensore cadenza ci hai rinunciatO?
hai il meta quest 2 o 3? te lo chiedo perche' lo vorrei prendere anche io ma il quest 3 ora su amazon e' out of stock

**Comment by cagnulein** [comment]
devi chiedere a loro in caso :)
come mai il 2 per il tapis?

**Comment by fernovus** [comment]
perché sul 3 ho abbinato la cyclettes con la tua app e funziona benissimo, quindi non voglio stravolgere la combinazione. Il 2 lo uso per esperimenti.

**Comment by fernovus** [comment]
Altro dilemma: nell'app Zwift, il runpod viene abbinato come sensore di cadenza per la corsa; mi chiedo quindi perché nella tua app non può essere considerato sensore di cadenza ma di potenza?

**Comment by cagnulein** [comment]
perche' ho scritto il codice cosi :)

**Comment by fernovus** [comment]
Sissignore!

**Comment by fernovus** [comment]
[debug-lun_mar_11_19_17_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14562984/debug-lun_mar_11_19_17_53_2024.log)
Ecco l'ultimo log, appenta munto. Inutile dirti che rimane tutto a 0!

**Comment by cagnulein** [comment]
Forse ho capito, il runpod di Zwift ha dei servizi particolari e
iscrivendosi a quelli lui non trasmette.

Domani ti faccio una patch

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 19:20 fernovus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ma aspetta forse stiamo complicando una cosa semplice. Io questo sensore
lho già gestito in automatico. Toglilo anche dal power sensor e fammi
sapere

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 19:23 cagnulein ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Allora l'ho tolto anche da power sensor e non cambia nulla. Comincio a pensare che sia difettoso, come scrivono anche nelle recensioni sul loro sito.

**Comment by cagnulein** [comment]
Ma se da zwift ti va non credo. Ma da zwift ti va ad ogni colpo?
Ma per il sensore cadenza come è finita?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 20:48 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Aspetta, su zwift viene solo visto ma non sono riuscito a vedere come funziona nelle corse, cioè non vedo muovermi, ma non vorrei che sono io a non capire come fare. Seconda domanda, il sensore di cadenza? Intendi quello che ho inserito nel tapis-roulant?

**Comment by cagnulein** [comment]
Hah cavolo allora potrebbe essere rotto sul serio. Ma te lo sei messo sulla
scarpa?

Si il sensore cadenza nel tapis, l'hai fatto funzionare?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 21:22 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Sì che l'ho messo sulla scarpa! Almeno lì ci arrivo :-0 Il sensore di cadenza, come dicevo in altri post, funziona benissimo ma andando troppo veloce il rullo del tappeto, vado troppo veloce in vzfit; per questo volevo usare la tua app per poterlo rallentare, ma la cadenza rimane sempre fissa e troppo alta.

**Comment by cagnulein** [comment]
Finché non va la velocità su zwift allora non può andare neanche in qz

Per il senaore cadenza ti avevo detto di fare la prova con il gain ma non
mi avevi detto il risultato e non avevo visto il log


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 21:38 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Mi sono perso una puntata allora: cosa intendi per prova del gain?

**Comment by cagnulein** [comment]
Questo https://github.com/cagnulein/qdomyos-zwift/issues/2187#issuecomment-1980891113

Da lì fai tutto!

**Comment by fernovus** [comment]
Sì ma non era il parametro gain ma ratio wheel; comunque niente non rallenta va sempre troppo veloce qualsiasi numero metto.

**Comment by cagnulein** [comment]
Ma fammi vedere il dbdug log non ti intestardire tu, è solo matematica

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 22:01 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Buondì, allora mi ci sono messo d'impegno e ti garantisco che il runpod funziona egregiamente con zwift! Infatti ha una soglia di attività di circa 3km/h, cioè se non cammini almeno a questa velocità rimani fermo nell'app. Appena la superi, vedo l'avatar che comincia a correre. Tuttavia su QZ rimane a zero anche se corro a quella velocità.

**Comment by cagnulein** [comment]
come sempre ti chiedo di generare un debug log altrimenti non riesco ad
aiutarti

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 16:03 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
[debug-mar_mar_12_16_25_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14574901/debug-mar_mar_12_16_25_16_2024.log)
tutto tuo

**Comment by cagnulein** [comment]
ok domani ci guardo

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle ore 16:26 fernovus ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
nel log vedo ancora il runpod come power sensor, rimuovilo proprio e
rifammi il log di qualche secondo mentre corri. grazie
devi vedere le mattonelle prima di prova a correre

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle ore 16:33 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
nel log non vedo nulla, forse me l'hai mandato senza chiudere qz? hai
premuto play su qz? vedi i watt su vzfit?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 18:53 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
[debug-mar_mar_12_18_39_26_2024(1).log](https://github.com/cagnulein/qdomyos-zwift/files/14576903/debug-mar_mar_12_18_39_26_2024.1.log)
Vedi questo se è buono. Su Vzfit vedo rpm, spin, bpm. I watt non li ho mai fatti visualizzare. Dovrei?

**Comment by cagnulein** [comment]
ok ora che vediamo i dati ho capito il problema: la speed la valorizzo solo
se metti il run pod come sensore di potenza e attivi il power sensor as a
treadmill

fammi sapere

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 19:18 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Ho fatto come mi hai detto ma non cambia nulla

**Comment by cagnulein** [comment]
ma la velocità la vedi su qz? e' quello secondo me il problema

**Comment by cagnulein** [comment]
se la vedi abilita anche la treadmill as a bike

**Comment by fernovus** [comment]
Effettivamente no, ho solo i valori di cadenza che funziona ma la velocità rimane a zero

**Comment by cagnulein** [comment]
rifammi un log con power sensor e power sensor as a treadmill

forse c'è qualcosa li

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 20:38 fernovus ***@***.***> ha
scritto:

**Comment by fernovus** [comment]
Ho trovato! Lo speed gain, non so come, ma era a zero! Ora va benissimo! L'ho impostato a 8 così ho una discreta e reale velocità nel visore senza sfegatarmi. Sono in debito di una birra. Se avrò altri problemi, sarai il primo a saperlo ;-) Buona serata bello, a presto.

**Comment by cagnulein** [comment]
grande ;) 👍

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 20:54 fernovus ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
poi sono curioso di sapere com'è l'esperienza con vzfit e tapis

**Comment by fernovus** [comment]
Veramente sono già due anni e mezzo che uso vzfit con il tapis-roulant; lo alterno con la cyclettes quando mi serve più velocità per finire le gare. Anche se un po' più lento, ma il tapis-roulant fa fare più fatica al fisico.
