### ISSUE TITLE
Treadmill focus fitness 9i

### ISSUE THREAD

**Issue by Robinpuy** [cagnulein/qdomyos-zwift#2191]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by Robinpuy** [comment]
Hi,
Treadmill focus fitness 9i
Followed procedure for debug log
Does not follow proper commands.
Started treadmill, opened app
Wanted to start with app stayed dead.
Pushed several times on stop start pauze.
Then the treadmill after 3 to 4 restarts it started
Tried to speed up no response slow down no response.
Then incline up speed up to 22kph and incline up.
Played with all kinds of commands none were the correct ones.
Pushed stop on the treadmill.
Regards
I hope the bugrepport is attached. I didn't give confermation 
[bugreport-P1075X_EEA-SP1A.210812.016-2024-03-06-14-28-00.zip](https://github.com/cagnulein/qdomyos-zwift/files/14510933/bugreport-P1075X_EEA-SP1A.210812.016-2024-03-06-14-28-00.zip)

**Comment by Robinpuy** [comment]
> hi @Robinpuy i don't see anything

Hard for me with phone. I hope it's there now?

**Comment by cagnulein** [comment]
yes i'm checking it

**Comment by cagnulein** [comment]
hi i already handled it here https://github.com/cagnulein/qdomyos-zwift/issues/2160 for you I guess.

Did you try this build? https://github.com/cagnulein/qdomyos-zwift/actions/runs/8047591719/artifacts/1274844806
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Robinpuy** [comment]
Yes it's the one you recommended me to use, if you want I can try again

**Comment by cagnulein** [comment]
so didn't work? Could you please create a debug log from this version https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?

**Comment by Robinpuy** [comment]
Hi ,

I tried today the qz app , made some movies and a debug file . 
Android v 12
Qz app : 2.16.46
Debug file in attachment

Seemed like the commands are wrong
To start the treadmill in the app, I needed to start, stop pauze for a few times b4 start
The speed up did nothing and the incline on + pushed it to 22kph speed Wich is strange as the top speed is 20kph. 
I attached some info, the movie eab47 is highly compressed in order to send it by mail
In short 
To start , i need to press several times .
Once started on speed up nothings happens 
On incline 1 push incline goes to 1 and speed to 22kph , second puch incline to 2 speed to 16kph , third push incline to 3 speed to 12.8 , fourth push incline to 4 speed drops to 0
And the i stopped

https://github.com/cagnulein/qdomyos-zwift/assets/161473220/9f4b3db7-38d0-44a1-97b1-9fdce91e2db6


I know that focus treadmills espacially the one that I have only have a decent communication with e-health app. 
But it follows commands , but they arent the correct ones.
 
Thx. For the effort anyways. 

Regards Robin
[bugreport-P1075X_EEA-SP1A.210812.016-2024-03-06-14-28-00.zip](https://github.com/cagnulein/qdomyos-zwift/files/14538059/bugreport-P1075X_EEA-SP1A.210812.016-2024-03-06-14-28-00.zip)

https://github.com/cagnulein/qdomyos-zwift/assets/161473220/f98c4290-0426-4c9b-871f-2d421433728b

![IMG_20240308_122533](https://github.com/cagnulein/qdomyos-zwift/assets/161473220/3a17d0b5-63f1-48ef-a65c-0d907ffb1079)
![IMG_20240308_122704](https://github.com/cagnulein/qdomyos-zwift/assets/161473220/1882f7f8-6a79-4960-b102-a6bdcf8c7d2d)

**Comment by cagnulein** [comment]
hi @Robinpuy what I really need is a debug file from qz directly as I mentioned here https://github.com/cagnulein/qdomyos-zwift/issues/2191#issuecomment-1981141868
Thanks

**Comment by Robinpuy** [comment]
followed these steps 
1 open qz app
2 settings / expirimental features all the way down enable debug log
3 close and restart app
4 recreate the issue
5 stop and close qz app.
6 open file explorer to android NO DATA MAP visible. only some other maps media and obj
i cant find the debug log

**Comment by Robinpuy** [comment]
on android 12 , i did it with my phone 
found the debug log , now i need to transfer to pc

**Comment by Robinpuy** [comment]
[debug-Fri_Mar_8_13_50_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14538404/debug-Fri_Mar_8_13_50_57_2024.log)
i hope this is the one.
so much trouble with google online drives.

**Comment by Robinpuy** [comment]
android V12 on my phone also

**Comment by cagnulein** [comment]
ok let's fix this by step
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8203827893
i fixed the speed issue
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Robinpuy** [comment]
Hi,
the update is very usefull, thanks for that great job
checked it today,
incline issiues are solved. on app as well on treadmill follows it correcly
speed issiues mostly - all is well except for the speed up speed down in the app, but it follows correctly when you use the buttons on the treadmill. for me this is solved
start button is the same - i start it through the app - i need to push a couple of times before it activates - not a big issiue - for me would be great if this get solved because start button on treadmill doesn't work.
as this is a beta i could it use for 15min
zwift
as you said this beta app doesn't work in zwift.
however when i logged in, in the sensor screen i could select wahookickr and it showed speed correctly.
cadence the same. however it counted 0 i wasnt running and my treadmill doesn't transmit this only speed and incline probably stays on 0
HR i use my fenix 6 this is ok . i could also select speed and cadence on fenix 6 but not my runn sensor
when i went to run, avatar did not move and speed showed 0.
shut down the app, settings back to runn sensor and did my workout.
QZ-2.16.47
android v12

it would be great if i could use the auto incline in zwift thats wat i wanted the app for.
anyway allready thanks for a great job
Robin

**Comment by cagnulein** [comment]
i'm hanging out with my family now, i will check it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 14:35 Robinpuy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok @Robinpuy so I will push this version to the play store soon. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS so I will add you to the closed beta! Thanks

**Comment by cagnulein** [comment]
@Robinpuy are we ok with this?

**Comment by Robinpuy** [comment]
hi Roberto, 

yes, as i mentioned i have bought a new treadmill. 
it should be full supported by bluetooth 
model virtuafit 500i where i is for smart treadmill. 

i hope QZ app supports and i can use the incline option in zwift, and be tortured more 

Thx anyway. 

regards, 
Robin 


Van: "Roberto Viola" ***@***.***> 
Aan: "cagnulein/qdomyos-zwift" ***@***.***> 
Cc: "robin puystjens" ***@***.***>, "Mention" ***@***.***> 
Verzonden: Woensdag 10 april 2024 08:24:37 
Onderwerp: Re: [cagnulein/qdomyos-zwift] Treadmill focus fitness 9i (Issue #2191) 





[ https://github.com/Robinpuy | @Robinpuy ] are we ok with this?
