### ISSUE TITLE
Garmin 945 heart rate disconnected and reconnected from QZ[BUG]

### ISSUE THREAD

**Issue by Dnoam1959** [cagnulein/qdomyos-zwift#2192]
Devices 
Android 23 Ultra  Android Version 14 latest update.
Garmin 945.
I notice that when I am connectiong my Garmin 945 To QZ the heart rate is getting connected and disconnected through all the excersise .It starting ok than disconnection and than starting again and disconnected again.The Service outside  FTMS is in it’s original checked position and the HRM is not connected to the machinery.

[debug-Wed_Mar_6_10_28_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14511813/debug-Wed_Mar_6_10_28_14_2024.log)

**Comment by cagnulein** [comment]
hi you have boh ant heart setting and heart rate belt name setting enabled.
They are conflicting. Which one you are using? Disable the other one :)
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle ore 16:13 Dnoam1959 ***@***.***>
ha scritto:

**Comment by Dnoam1959** [comment]
I have just one on me , the other is in the drawer not active at all.
I also found that the CX file explorer behaves diffrently although all premissions are given.Cannot get directly to the debug file.
Noam

From: Roberto Viola ***@***.***>
Date: Wednesday, 6 March 2024 at 16:17
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Author ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)
hi you have boh ant heart setting and heart rate belt name setting enabled.
They are conflicting. Which one you are using? Disable the other one :)
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle ore 16:13 Dnoam1959 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
no i mean that you have both settings enabled and this is conflicting in QZ. You have only to enable one at a time.
For CX file explorer issue: are you on android 14?

**Comment by cagnulein** [comment]
Yes you are on android 14 :) you have to use the /documents/qz path using the classic files app of Android

**Comment by Dnoam1959** [comment]
Hi.
I will check it all in my next run.
Another question (forgive me , I simply do not posses youre knowledge level):
My Console is a touch screen , I can hook my Android Tablet/Phone with an HDMI cable to the console , is it possible also activate somehow the touch capabilities that on the Tablet/Phone and not just miroring the screen?
Regards.

From: Roberto Viola ***@***.***>
Date: Wednesday, 6 March 2024 at 16:38
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Author ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)

Yes you are on android 14 :) you have to use the /documents/qz path using the classic files app of Android

**Comment by cagnulein** [comment]
@Dnoam1959 which bike do you have? can't you just cast the screen wirelessly there?

**Comment by Dnoam1959** [comment]
A treadmill ; Vision 600E


From: Roberto Viola ***@***.***>
Date: Thursday, 7 March 2024 at 13:11
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)

@Dnoam1959<https://github.com/Dnoam1959> which bike do you have? can't you just cast the screen wirelessly there?

**Comment by cagnulein** [comment]
can't you install app on it? can't you cast wierelessly there?

**Comment by Dnoam1959** [comment]
I can’t install anything on it and I can’t cast anything . I just connect it through cable.They blocked it quite effectivly.
Regards.

From: Roberto Viola ***@***.***>
Date: Thursday, 7 March 2024 at 13:49
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)

can't you install app on it? can't you cast wierelessly there?

**Comment by cagnulein** [comment]
does it have android? Maybe it's crackable :)

**Comment by Dnoam1959** [comment]
Sure it is android bases ,I enclose here the photos.
I cannot install anything or cast a screen , all is blocked.
The only I can hook is a USB or HDMI.In the machine setting Photo , I cannot check anything.
Cracble I am sure it is , I just have no idea where to start.
Regards


From: Roberto Viola ***@***.***>
Date: Thursday, 7 March 2024 at 15:18
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)

does it have android? Maybe it's crackable :)

**Comment by cagnulein** [comment]
i can't see pictures if you are sending them via mail, you have to send here directly on github

are you able to go in the developer settings of the tablet from the android settings?

**Comment by Dnoam1959** [comment]
Here are the Photos.
![WhatsApp Image 2024-03-07 at 15 30 55 (1)](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/f3ac39f9-bfe1-43bf-b1ab-1f62c26342d2)
![WhatsApp Image 2024-03-07 at 15 30 55](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/9cf2047b-8535-44fa-bfea-f41ad8b9e4be)
![WhatsApp Image 2024-03-07 at 15 30 56 (1)](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/d2170e59-7ddd-482e-93e2-cf677ba2112a)
![WhatsApp Image 2024-03-07 at 15 30 56](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/a4598ca9-bbe0-4981-9acb-7cbb7cc67f1b)

And i do not know how to get to developer mode.

**Comment by cagnulein** [comment]
did you try to put the usb cable from there to your pc?

**Comment by cagnulein** [comment]
do this
open a terminal
run a lsusb without the cable connected
run a lsusb with the cable connected
share the result

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 mar 2024 alle 19:18 Dnoam1959 ***@***.***> ha
scritto:

**Comment by Dnoam1959** [comment]
Ok . Will do tomorrow.
Thank you.

From: Roberto Viola ***@***.***>
Date: Thursday, 7 March 2024 at 19:36
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)
do this
open a terminal
run a lsusb without the cable connected
run a lsusb with the cable connected
share the result

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 mar 2024 alle 19:18 Dnoam1959 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
for the heart rate in the log i saw always the heart to 0. maybe you uploaded the wrong log?

for the usb i guess that usb port is only for usb key and not host.

so i guess they closed everything up :( 

did you try with a port sniffer to see if it has some network port open? i don't remember if it has wifi

**Comment by Dnoam1959** [comment]
It is a WiFi console.

**Comment by cagnulein** [comment]
ok give it a shot with zenmap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 8 mar 2024 alle 19:04 Dnoam1959 ***@***.***> ha
scritto:

**Comment by Dnoam1959** [comment]
[debug-Sun_Mar_10_10_31_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14551827/debug-Sun_Mar_10_10_31_50_2024.log)

The disappearing heart rate continues , it is working fine, than shows a 0 than back and than 0  again and so on .Feels like the communication is not flowing all the time .Might be the way Garmin is transmitting the data?
Regards.

**Comment by cagnulein** [comment]
The problem is the ant heart setting. Disable it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 22:27 Dnoam1959 ***@***.***>
ha scritto:

**Comment by Dnoam1959** [comment]
Hi.
Did not test it yet , probably tomorrow.
The Wifi port search require some help so lets see.
Regards.

**Comment by Dnoam1959** [comment]
Hi., Ho to transfer a file from the QZ log into trainingPeaks? Which data file of running TrainingPeaks can read?
Regards;

From: Roberto Viola ***@***.***>
Date: Sunday, 10 March 2024 at 22:29
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)
The problem is the ant heart setting. Disable it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 22:27 Dnoam1959 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I guess the fit file that you are receiving by email from qz and they are
also stored in the qz folder

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 12:05 Dnoam1959 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Dnoam1959 any news?

**Comment by Dnoam1959** [comment]
Hi.
I am out of the country on a long business trip so I am not on my home machine .Sorry.
Noam.

From: Roberto Viola ***@***.***>
Date: Thursday, 11 April 2024 at 00:51
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: Dnoam1959 ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Garmin 945 heart rate disconnected and reconnected from QZ[BUG] (Issue #2192)

@Dnoam1959<https://github.com/Dnoam1959> any news?

**Comment by cagnulein** [comment]
Have a great time! Let me know when you will be ready!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle ore 12:46 Dnoam1959 ***@***.***>
ha scritto:

**Comment by Dnoam1959** [comment]
Hi.
I am back and facing another problem .
As i cannot put my training plans to the data file on android 14 Phone , is there other way?
Through my Garmin watch ?

**Comment by cagnulein** [comment]
Hi @Dnoam1959 explain me better what you would like to do

**Comment by Dnoam1959** [comment]
I have a FIT/ZWO training routine file that i want to insert to ZQ training file , CF explorer is not permitted to open Android Data file , so i cannot insert it.An Android 14 issue.
Regards.

**Comment by cagnulein** [comment]
On android 14 you have to use the 2.16 version of qz (join the beta from here if you didn't already https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift ) and then you can use any file browser to copy the files to /documents/qz/training 

Let me know!

**Comment by Dnoam1959** [comment]
![WhatsApp Image 2024-05-26 at 16 15 29](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/cf544a6d-2b58-4d47-b610-e173df059fdf)
![WhatsApp Image 2024-05-26 at 16 18 11](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/50c933ef-8c36-44f0-ac8f-d7eff412e36f)
![WhatsApp Image 2024-05-26 at 16 22 41](https://github.com/cagnulein/qdomyos-zwift/assets/135517239/ac97240a-5a6f-456e-820d-7a79d1fa2a24)

I transferred (i tried both formats , just incase) and it does not show in the training option when i open the app.

What am i missing?
Regards.

**Comment by cagnulein** [comment]
use the other files button to import them. remove them from the training folder of qz first. let me know

**Comment by Dnoam1959** [comment]
Now the import worked .
Thank you.
Regards.
Noam.

**Comment by cagnulein** [comment]
that's great!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 26 mag 2024 alle ore 18:00 Dnoam1959 ***@***.***>
ha scritto:
