### ISSUE TITLE
Schwinn 810 treadmill

### ISSUE THREAD

**Issue by mwaldschmidt** [cagnulein/qdomyos-zwift#2194]
Schwinn 810 treadmill not working

I see tiles after upgrading to the beta but nothing is recorded.  

Expected to see the tiles.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Samsung Galaxy S23
 - OS: Android v 14 One UI v 6.0

**Append a debug log**

 Follow 
[debug-Wed_Mar_6_07_22_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14513346/debug-Wed_Mar_6_07_22_36_2024.log)
this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
Note that I had the garmin companion enabled in settings and heart rate monitor disabled and also no heart rate.  I will open a second ticket for the bike but this is the same behavior I saw there.

Mike

**Comment by mwaldschmidt** [comment]
Amazing. That did the trick.

The only thing I'm not seeing change on tiles is the incline.

Thoughts on why hr isn't working with Garmin?

Think that ticket can be closed out and I'll put one in for the bike when I
can.

Mike

**Comment by cagnulein** [comment]
for the inclination, could you please share another debug log in the
current scenario? For the watch did you enable the Garmin companion
settings on the qz main app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 18:28 mwaldschmidt ***@***.***>
ha scritto:

**Comment by mwaldschmidt** [comment]
Apologies, it seems it's generating more logs so I attached 3, I wasn't positive which was correct.  I also attached some screenshots.  I do have the garmin companion setting enabled. 

Thanks,

Mike
[debug-Wed_Mar_6_11_25_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14513663/debug-Wed_Mar_6_11_25_16_2024.log)
[debug-Wed_Mar_6_11_33_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14513664/debug-Wed_Mar_6_11_33_41_2024.log)
[debug-Wed_Mar_6_11_32_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14513665/debug-Wed_Mar_6_11_32_04_2024.log)
![Screenshot_20240306_113313_Connect IQ](https://github.com/cagnulein/qdomyos-zwift/assets/162485026/2c9dc69d-09b5-43f7-a585-d21de0c08529)
![Screenshot_20240306_113255_Connect IQ](https://github.com/cagnulein/qdomyos-zwift/assets/162485026/323b23e1-ab43-4f25-9c3b-c1c46d227043)
![Screenshot_20240306_113219](https://github.com/cagnulein/qdomyos-zwift/assets/162485026/94983367-70ae-46ec-8636-6caff89ead3b)
![Screenshot_20240306_113230](https://github.com/cagnulein/qdomyos-zwift/assets/162485026/cd56f695-0c76-4f81-8f48-71df19289f1f)

**Comment by cagnulein** [comment]
thanks i will check tomorrow, dinner time here :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 18:46 mwaldschmidt ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
quickly check them:
for the inclination: are you able to get in the schwinn app?
for the garmin: do you have only this watch paired to this phone? did you
press start on the companion? do you see the HR on the companion?

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle ore 19:27 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
the schwinn app i guess it's the jrny app 

for the watch, when you open the qz app there, you have to press the start button on the watch in order to see your hr and the timer counting 

did you?

**Comment by mwaldschmidt** [comment]
I am not sure it will allow me to add the treadmill on the jrny app.  I
don't see the model listed.  Does this mean it will not work with
inclination on qz?

And I wasn't using companion correctly, I didn't realize I had to start it
like that.  That should do the trick.

Mike

**Comment by cagnulein** [comment]
perfect for the companion!

for the inclination, your treadmill doesn't the inclination so i would like
to see if with another app, the manufacturer one, it could be possible. are
you able to talk to schwinn about this?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 mar 2024 alle 20:08 mwaldschmidt ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Thanks, you too!


Il giorno mer 6 mar 2024 alle 20:18 mwaldschmidt ***@***.***>
ha scritto:
