### ISSUE TITLE
[BUG] inclinaison and résistance unfonctional

### ISSUE THREAD

**Issue by Razia65** [cagnulein/qdomyos-zwift#2198]
Hi!
I have a proform tdf 10.0 with companion install from adb
Run with qz 2.15.4 and iOS 17.3.1
Adb remote is turn on 

When i press the plus button on the inclination tile, i  don't see any reaction. Same for résistance.

thank you for help!

[debug-sam__mars_9_19_35_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14547465/debug-sam__mars_9_19_35_17_2024.log)
[Uploading debug-sam__mars_9_19_35_17_2024.log…]()

**Comment by cagnulein** [comment]
I just send you the new ios Beta. Could you please share me a debug log
from this one too?

Also can you check if with the adb remote disabled you can see a virtual
touch event on the tablet of the bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 20:09 Razia65 ***@***.***> ha
scritto:

**Comment by Razia65** [comment]
Always the same problem!

i check with the adb remote disabled , i can’t see a virtual touch event on the tablet of proform bike
[debug-sam__mars_9_21_35_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14547755/debug-sam__mars_9_21_35_23_2024.log)

**Comment by cagnulein** [comment]
Ok so from the pc where you ran the adb script run this

adb shell input swipw 100 200 300 400 100

Do you see the virtual touch event in this way?

Show me the output if not

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 21:50 Razia65 ***@***.***> ha
scritto:

**Comment by Razia65** [comment]
I check from ifit settings and i able to see virtual command on proform’s tablet
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/56be0970-e1fb-48b5-9f84-062afc49a399)
So, on qz app no react with résistance tile
If i touch élévation tile : 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/b0d88b34-9fa7-43a9-b7fb-c562fec4a25b)

**Comment by cagnulein** [comment]
i'm not sure i understand what you're saying: so from qz you are seeing a virtual touch event even if in the wrong coordinates? if so with which setting? adb remote on or off?

**Comment by Razia65** [comment]
On qz, adb remote off : no react
On qz, adb remote on and push on résistance tile : no react
On qz, adb remote on and push on élévation tile: virtual touch on screen of proform tablet
This screen 


But no action on élévation or résistance from bike

Envoyé de mon iPhone

**Comment by cagnulein** [comment]
ok that's perfect!
so we just need to calibrate the touch event!

try to enable the ""Proform Studio Bike" setting now and restart qz

let me know if it's better. If not I just need to add your bike configuration as well! We are near

**Comment by Razia65** [comment]
This setting? 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/4509a626-3eac-4990-a29d-4d8add4ecc7a)

isn’t better!

**Comment by cagnulein** [comment]
ok so provide me a screenshot using the adb-screenshot batch file from the install package and I will add it!

**Comment by Razia65** [comment]
sorry but a screenshot of what screen? whith wich setting?

**Comment by cagnulein** [comment]
this one https://private-user-images.githubusercontent.com/162832413/311498909-56be0970-e1fb-48b5-9f84-062afc49a399.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjg4ODgsIm5iZiI6MTcxMDA2ODU4OCwicGF0aCI6Ii8xNjI4MzI0MTMvMzExNDk4OTA5LTU2YmUwOTcwLWUxZmItNDhiNS05Zjg0LTA2MmFmYzQ5YTM5OS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMTEwMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRmNGQxNTcyMWU2ZWJiMTc5YmFjZTUwMjcyNWVmNWU1NzJiYzVlNDE4MmMzODQ2MzI0OWMyZjM5MzdlZGNlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LOm4NWtXXWtVGsLUG9owrdVwgIp95odSmx9N_b6fi5A but with the batch file in the install package

**Comment by Razia65** [comment]
i can't see your screenshot, the link does not work : HTTP ERROR 404

**Comment by cagnulein** [comment]
the first one here https://github.com/cagnulein/qdomyos-zwift/issues/2198#issuecomment-1987161778

**Comment by Razia65** [comment]
And here!
![10-03-2024@12-45-03,14](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/454ef61b-d058-47ad-9d7c-aa1625106ac2)

**Comment by cagnulein** [comment]
ok i will add it in the next days

**Comment by cagnulein** [comment]
@Razia65 i checked the coordinates and, and least the Y, it's the same of the Proform Studio. So just to be sure, when you select the proform studio and you try to change the inclination from qz, do you see the inclination sliders change on your bike tablet? maybe on a wrong value, but is it changing?

**Comment by Razia65** [comment]
If I turn on proform studio bike in QZ settings, no react with tiles inclination or résistance.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/d67c9aa4-ac53-4687-88e4-d00ee61411ce)

if I turn off proform studio bike in QZ settings, only TDF companion IP, no react with tile résistance 
But tile inclination open this screen
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/c1ae0959-4a87-48d2-8a5b-4ff67f4b7bec)

no effect on virtual sliders on the bike’s tablet

**Comment by cagnulein** [comment]
Hah Ok got it, i'm adding the new coordinates for you later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 13:30 Razia65 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Razia65 done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
in the new beta enable the new proform tdf 10.0 setting (don't change anything else) and leave the proform studio disabled of course

**Comment by Razia65** [comment]
Hello Roberto!
above all, thank you for your unfailing availability!

The latest version of QZ that you sent me solved part of the problem but not completely.

-For inclination, QZ controls it perfectly. On the other hand on zwift, the bike moves constantly (almost every second and in an anarchic manner. for example, zwift displays a slope of 8%, QZ will make the bike move from 5% to 11% then immediately start again at 4.5 % and this in less than 4 seconds etc...)

-For the resistance, nothing happens when you order via QZ and of course zwift does not automatically manage the resistance

An idea of ​​the problem?

**Comment by cagnulein** [comment]
the resistance is changing when Qz changes the inclination so that's fine (inclination affects also the resistance) For the inclination issue instead we have to calibrate better the coordinates. It will be nice if you can do this by ADB from your PC. Are you already able to connect adb with your bike?

**Comment by Razia65** [comment]
This is ok for automatic resistance change with incline, but it doesn't work in ERG mode when zwift needs to change resistance based on target power since there is no incline.

I can use ABD from the PC, it works!

**Comment by Razia65** [comment]
can you tell me how to send this command please?
I've only used ADB with the contents of the QZ installation folder so far!

**Comment by cagnulein** [comment]
sure, open a windows terminal.
go into the installpackage folder wherre the adb.exe is.
then run the command, like

adb shell input swipe 100 200 300 400 200

of course change the 100 200 300 400 with the function above

**Comment by Razia65** [comment]
sorry Roberto, I did everything I could by searching in github to figure it out on my own, but it's late and after several hours I can't carry out your instructions...
I'm coming a long way and I think I'm close to the goal, but I need a helping hand
![image](https://github.com/cagnulein/qdomyos-zwift/assets/162832413/6cb61db7-191a-451f-89f2-c63c0a24aa5b)

**Comment by cagnulein** [comment]
You have to replace the variables with the numbers

The variables in my lines are only place holder to show you how do the calculation

**Comment by Razia65** [comment]
I hate doing things without understanding, I ended up using adb by searching on github and I spent several hours of the day trying to understand your instructions but then I give up, without explanations I don't I wouldn't make it.

How can I know the number for "new inclination" and "currentInclination" since these values ​​are only valid at a time T???

maybe I'm missing something because of the French translation...

**Comment by cagnulein** [comment]
current inclination is current inclination of the treadmill
new inclination is the grade that you want to set to the treadmilll.

what is still not clear?

**Comment by Razia65** [comment]
If I understood correctly, what you tell me is used to adjust the real inclination of the bike according to the order of QZ.

But it already works perfectly.

What doesn't work is when Zwift displays an incline, QZ (and therefore the bike too) changes the incline several times in a few seconds, exceeding the Zwift setpoint in positive/negative and sometimes even both.

The bike is a rocking horse on Zwift, but with QZ only it's OK

did you understand the problem? Should I still execute your order?

**Comment by cagnulein** [comment]
nope, i guess i don't understand.
Let's put this simple. if you press the plus and minus button, does the inclination work ok? going step by step? that's very important, test it deeply

**Comment by Razia65** [comment]
I just checked, everything is OK between QZ and the bike.
from -10% to +20% in increments of 0.5%

my problem is between Zwift and QZ

**Comment by cagnulein** [comment]
hah ok! that's a good news! so share me a debug log which i can see the issue

**Comment by Razia65** [comment]
[Uploading debug-ven__mars_15_19_40_55_2024.log…]()

**Comment by cagnulein** [comment]
Hi the file is corrupted, you have to wait the finish of the upload before commenting

**Comment by Razia65** [comment]
[debug-ven__mars_15_19_40_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14621272/debug-ven__mars_15_19_40_55_2024.log)

**Comment by cagnulein** [comment]
ok under the advanced settings, there is a "inclination delay seconds" .
now it's 0, try to put a 5 or a 10, i guess the issue it's the fact that
the bike is slow to change the inclination and so qz is always trying to
send a new inclination value
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 mar 2024 alle ore 23:30 Razia65 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Razia65 any news?
