### ISSUE TITLE
[BUG] phone getting data but not sending it to iPad or Mac running Zwift 

### ISSUE THREAD

**Issue by lefty175** [cagnulein/qdomyos-zwift#2199]
**Describe the bug**
Data shows up on the app but won’t transmit to Zwift on another device. RPM is the only thing coming across and it is intermittent. 

**To Reproduce**
1. Open app and connect to echelon connect ex-4s
2. Open Zwift on iPad or Mac. 
3. Pair phone with Zwift. 

**Expected behavior**
Power, HR, cadence data sent to Zwift. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios for pad (iPad pro) 
[debug-Sat_Mar_9_10_32_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14547758/debug-Sat_Mar_9_10_32_58_2024.log)

 - Version 17.3.1 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max 
 - OS: iOS 17.3.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Everything in the log is right, qz is sending the metrics to zwift. You
need 2 devices on ios, for example iPad and iPhone for this.

Also if you have a Mac silicon I recommend you to use both qz and zwift on
the same Mac

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 21:47 lefty175 ***@***.***> ha
scritto:

**Comment by lefty175** [comment]
Am using two iOS devices (iPad and iPhone) but let me try qdomyos on the Mac and running zwift on it. RussellOn Mar 9, 2024, at 10:51, Roberto Viola ***@***.***> wrote:﻿
Everything in the log is right, qz is sending the metrics to zwift. You

need 2 devices on ios, for example iPad and iPhone for this.



Also if you have a Mac silicon I recommend you to use both qz and zwift on

the same Mac



Let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 9 mar 2024 alle 21:47 lefty175 ***@***.***> ha

scritto:

**Comment by lefty175** [comment]
Mac with the QZ app and Zwift seems to be the solution! Much appreciated. 

My best, 

Russell

**Comment by cagnulein** [comment]
Glad to hear it!
