### ISSUE TITLE
[BUG]Inclination is not changing in Qz even though there are a few hills on the MyWhoosh route

### ISSUE THREAD

**Issue by Mrschley** [cagnulein/qdomyos-zwift#2200]
[debug-Sat_Mar_9_14_10_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14547781/debug-Sat_Mar_9_14_10_57_2024.log)

**Comment by cagnulein** [comment]
Mywhoosh doesn't send the inclination for the treadmill yet. Write to them
about this feature request  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 21:54 Mrschley ***@***.***> ha
scritto:

**Comment by Mrschley** [comment]
No, I'm on a bike.  Usually I can see the hill incline show up on the qz
app.  For this last ride it just remained at 0.2.

**Comment by cagnulein** [comment]
Hah Ok mywhoosh doesn't send any inclination here. I guess it's a bug in their application. Did you report it to them?

**Comment by Mrschley** [comment]
But I usually see it.  Am I getting confused with a different tile?

**Comment by cagnulein** [comment]
No as I said you are doing anything wrong, it's just a mywhoosh bug. Report
this to them. Mywhoosh is a beta app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 22:23 Mrschley ***@***.***> ha
scritto:

> But I usually see it. Am I getting confused with a different tile?
>

**Comment by Mrschley** [comment]
But you are saying you don't get that info and I'm saying I've seen it show
up in the tile before.

**Comment by cagnulein** [comment]
Yes I'm saying that IN THIS SESSION mywhoosh is not sending the inclination
information. So it's for sure something on mywhoosh. If you see the
inclination before it means that's a new bug on their app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 22:28 Mrschley ***@***.***> ha
scritto:

> But you are saying you don't get that info and I'm saying I've seen it
> show
> up in the tile before.
>

**Comment by cagnulein** [comment]
In this log there is only a 0.2 at the very startup from mywhoshh.nothing else

**Comment by Mrschley** [comment]
Ok, thanks for the clarification.

**Comment by cagnulein** [comment]
Let me know if they will fix it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 05:05 Mrschley ***@***.***> ha
scritto:

> Ok, thanks for the clarification.
>

**Comment by cagnulein** [comment]
That's a bot answer :) 

Ask on the qz Facebook group if someone else is experiencing the same issue
