### ISSUE TITLE
Noble Pro Elite e8.0 [BUG]

### ISSUE THREAD

**Issue by RoadRacer87** [cagnulein/qdomyos-zwift#2201]
Hi Roberto,

As mentioned on Facebook I'm struggling to connect my Noble Pro Elite e8.0. 

It is now recognising the treadmill occasionally (half the time it auto connects to the HRM accompanying it despite having used the advanced settings to force the connection to the Noble Pro profile).

It will now connect but when connected, no data is read or received from the treadmill. The system just records nil for the session until I hit stop. 

Any assistance would be much appreciated!

Best,
Bryn

Attached are the screenshot of the device connected and what I believe is the debug log. 

![Screenshot_20240309_202806](https://github.com/cagnulein/qdomyos-zwift/assets/162841561/bc920280-5171-4bd1-9150-aa63e81ea1db)

[debug-Sat_Mar_9_20_28_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14547881/debug-Sat_Mar_9_20_28_51_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Main issue is that you have enable the fake treadmill setting in the
experimental settings.:
 disabled it and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 mar 2024 alle 22:55 RoadRacer87 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@RoadRacer87 are we ok with this?

**Comment by RoadRacer87** [comment]
Absolutely. All working well now. Thanks!

________________________________
