### ISSUE TITLE
BXT216 Bowflex Pause have no effect on Zwift.[BUG]

### ISSUE THREAD

**Issue by hpcolus** [cagnulein/qdomyos-zwift#2203]
Avatar in Zwift keeps running after pressing the PAUSE button in the treadmill.
**Desktop
-OS: Windows 11
--Version 22H2
**Smartphone
-Device: Pixel 6
--OS: Android
--Version: 14

**Comment by cagnulein** [comment]
Hi @hpcolus attach a debug log with the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

**Comment by hpcolus** [comment]
In Android 14 Pixel 6, there is no folder 'Qz' in documents, and in /android/data there is no folder /android/data/org.cagnulein.qdomyoszwift/.  I tried different explorers.  I also connected to my laptop the Pixel 6.  I am able to see all kind of folders but nothing for QZ on the places you mentioned.

**Comment by cagnulein** [comment]
you have to use the beta
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and the
folder it's under /documents/Qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle 21:58 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment]
After waiting for a while, it says that the testing app is not available or that I am on the list of having access.  Maybe because my google play email is different that the email I used for GitHub.

**Comment by cagnulein** [comment]
did you join the beta with the google play address? which version do you see now on qz?

**Comment by hpcolus** [comment]
v 2.14.0  I did join the first time but it says it would take some time to push the new app on my phone.  I never got any notification to update the app.

**Comment by cagnulein** [comment]
2.14 it's definitely not the beta. What if you click now on the beta link
that I provided before? Did you see the joining button?
The update will be in the play store page of qz then

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 19:10 hpcolus ***@***.***> ha
scritto:

**Comment by hpcolus** [comment]
Finally.  I had to reinstall QZ.
In summary, the pause button on the treadmill has no effect on QZ or Zwift.  If I walk at 3 mi/h and pause nothing happens.  The QZ shows the speed as 3 mi/h and the Zwift avatar keeps walking.  When I resume the TM, the speed on QZ is updated accordingly from o mi/h upto 3 mi/hr.  
The stop button on the TM works, meaning it changes the speed to 0 on QZ and Zwift.
[debug-Mon_Mar_11_21_29_53_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14566841/debug-Mon_Mar_11_21_29_53_2024.zip)

**Comment by cagnulein** [comment]
thanks @hpcolus pause handled, it will be in the 2.16.49

**Comment by cagnulein** [comment]
@hpcolus are we ok with this?
