### ISSUE TITLE
NoblePro E10i

### ISSUE THREAD

**Issue by Middy2000** [cagnulein/qdomyos-zwift#2205]
When using Android version of QZ with the NoblePro E10i treadmill cadence data is not being read.
This happened with the E8i treadmill but was fixed with a patch.

Also the buttons on the tiles do not appear to work.
[debug-Sun_Mar_10_12_03_50_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14550185/debug-Sun_Mar_10_12_03_50_2024.zip)

**Comment by cagnulein** [comment]
@Middy2000 the patch works when you deselect the ftms treadmill. please redo it with it disabled. thanks

**Comment by Middy2000** [comment]
Will give it a try but when ftms is disabled it normally doesn't pick up treadmill. I'll try again.

**Comment by cagnulein** [comment]
hah sorry i was missing that this treadmill has only ftms. no you did right let me check again the log.

**Comment by cagnulein** [comment]
does zwift report cadence when you connect this treadmill directly?

**Comment by Middy2000** [comment]
Yes. When connected directly cadence is reported.

This is exactly the same issue we had with the E8i a couple of weeks ago but you fixed it.  The details will be on the other ticket?

**Comment by cagnulein** [comment]
that's a completely another thing. this treadmill reports different
characteristics
ok os if zwift reports it i guess i can get it too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle ore 17:42 Middy2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
got it, i will implement it in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle ore 17:43 cagnulein ***@***.***> ha
scritto:

**Comment by Middy2000** [comment]
Not the same as this then?

https://github.com/cagnulein/qdomyos-zwift/issues/2073#issuecomment-1916591524

The behavior is identical. It pairs as Wahoo tread but has zero reading on pairing page.
When go into Zwift app cadence is greyed out as if not paired at all.

**Comment by cagnulein** [comment]
note for me: 00001814 RSC

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle ore 17:45 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
similar but this protocol is different, that's why i'm saying that i can
apply the same :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 mar 2024 alle ore 17:46 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Great news. I almost sound like I understand... 😆

**Comment by Middy2000** [comment]
Hi R,

Tested today and it is working.  Cadence looks to be about correct.  
The total incline over the 10k course is different from this treadmill to my old one but this treadmill only goes up in single percentage but the old one was 0.5 so maybe that will be the difference.  This is the treadmill issue not QZ obviously.  Will do a few more tests in the week and then I think we can close this as complete!

**Comment by cagnulein** [comment]
that's great!

**Comment by Middy2000** [comment]
Another successful day of using the app.
Cadence is reporting correctly, lots of fluctuations but overall average is correct.

**Comment by cagnulein** [comment]
for the fluctuations you have to complain to Noble in this case :D

**Comment by Middy2000** [comment]
I don't tend to notice them when running to be honest.  More busy looking how high my heart rate is going!

**Comment by Middy2000** [comment]
I've never seen that option until now. Just looked and I might experiment with it. Looks to be a great option.

**Comment by cagnulein** [comment]
i used it until my treadmill died and it's a great way to keep your horses under control. Sometimes i'm running too fast for my heart and I guess that's not useful to your body.

About this there is also the tile to change the the HR zone at runtime or disable it at all

**Comment by Middy2000** [comment]
My old treadmill is still here waiting for you.

**Comment by Middy2000** [comment]
They've replaced it under warranty?

**Comment by cagnulein** [comment]
yes i had extended the warrant for only 70€

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 13 mar 2024 alle 17:57 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
That's great thinking by you!
