### ISSUE TITLE
[BUG] Buttons on floating window have no icons

### ISSUE THREAD

**Issue by k818mn1** [cagnulein/qdomyos-zwift#2206]
**Describe the bug**
The two buttons on the right of the bottom row of the floating window don't have icons on my Echelon tablet running QZ.
I examined the code and one of the button should have a 🧲 icon for autoresistance. The other button is the Close button. 

**Screenshots**

![Screenshot_20240310-124217](https://github.com/cagnulein/qdomyos-zwift/assets/39540440/3deb5ba8-15b1-4b8c-98ad-e6d03c2cc67a)

**Smartphone (please complete the following information):**
 - Device: Echelon Android tablet
 - OS: Android
 - Version 9

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
that's about the fact that old android doesn't have all the utf8 icons. i can't do anything about this :)

**Comment by k818mn1** [comment]
Ok, I guess this can be closed then.
