### ISSUE TITLE
Rpi Zero W keeps losing connection

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#221]
I'm trying a Rpi Zero W with qdomyos-zwift, installed is as described in the manual for my domyos bike 500.
(I missed a "cd qdomyos-zwift" after the "git" and before "cd src")

It keeps connecting / disconnecting all the time, it's never connected for more than a second, any idea why that is?

I can't find any documentation on parameters I can use when starting the service, is there any?
Is it possible to force parametrize the bluetooth device you want to connect with? Because I have 2 device next to each other and want to use one RPI for each.

Also can I change the name of the service I see on the Zwift device to discriminate between both RPI devices? Maybe add a parameter for this too?

For the Domyos 900 Treadmill I'm trying a RPI4 with a touchscreen, but still waiting for a few parts.
When it's all working I'll be sure to let you know!

**Comment by cagnulein** [comment]
Did you follow this one?
https://www.github.com/cagnulein/qdomyos-zwift/tree/master/docs%2F10_Installation.md
Also send me the debug log in order to understand the issue

Il dom 28 mar 2021, 10:04 ErnieV ***@***.***> ha scritto:

**Comment by ErnieV** [comment]
Yes.
It needs:

git clone https://github.com/cagnulein/qdomyos-zwift.git
*** cd qdomyos-zwift ***
cd src
qmake
make

I will look into log files.

Any chance on the parameter documentation? .\qdomyos-zwift -help didn’t work.

Regards,
Erwin

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
You can find all the parameters in the main.cpp

**Comment by ben75020** [comment]
Documentation updated, thank you for raising this. 

You can try adding `-name BLUETOOTH_BIKE_NAME` (where you change the placeholder with effective bluetooth name from your device).

Sending the logs (start the program without "-no-log" then retrieve the debug file .txt at the same place from the binary) will help too.

**Comment by cagnulein** [comment]
I love this kind of cooperation @ben75020 
Thank you again!

**Comment by ErnieV** [comment]
Thank you very much @ben75020 ! 
It seems to work perfect if I add the name to the service. Will test is some more than close the bug.

The display on my Domyos Bike is still a bit funny, switching between speed and distance very quick while riding.

Maybe there is something in the log file that tells you why?
I've added a single chunk of data here:

Mon Mar 29 20:03:42 2021 1617041022982 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  exit for timeout
Mon Mar 29 20:03:43 2021 1617041023014 Debug:   HCI event triggered, type: 13
Mon Mar 29 20:03:43 2021 1617041023079 Debug: virtualbike.cpp void virtualbike::bikeProvider() virtual bike not connected
Mon Mar 29 20:03:43 2021 1617041023124 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool) " >> f0 cd 01 00 00 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff // updateDisplay2"
Mon Mar 29 20:03:43 2021 1617041023150 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "f0cd01000001ffffffffffffffffffffffffffff"
Mon Mar 29 20:03:43 2021 1617041023155 Debug: domyosbike.cpp void domyosbike::characteristicWritten(const QLowEnergyCharacteristic&, const QByteArray&) "characteristicWritten f0 cd 01 00 00 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff"
Mon Mar 29 20:03:43 2021 1617041023162 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  exit for timeout
Mon Mar 29 20:03:43 2021 1617041023187 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool) " >> ff ff ff ff ff ff ab // updateDisplay2"
Mon Mar 29 20:03:43 2021 1617041023193 Debug:   HCI event triggered, type: 13
Mon Mar 29 20:03:43 2021 1617041023218 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "ffffffffffffab"
Mon Mar 29 20:03:43 2021 1617041023224 Debug: domyosbike.cpp void domyosbike::characteristicWritten(const QLowEnergyCharacteristic&, const QByteArray&) "characteristicWritten ff ff ff ff ff ff ab"
Mon Mar 29 20:03:43 2021 1617041023264 Warning:   L2Cap payload size 23 is smaller than specified size 30
Mon Mar 29 20:03:43 2021 1617041023271 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) " << f0 dd 01 00 00 01 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff bb"
Mon Mar 29 20:03:43 2021 1617041023276 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  exit for timeout
Mon Mar 29 20:03:43 2021 1617041023297 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool) " >> f0 cb 03 00 00 ff 01 00 00 02 01 00 00 00 01 00 00 01 01 00 // updateDisplay elapsed=0"
Mon Mar 29 20:03:43 2021 1617041023330 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "f0cb030000ff0100000201000000010000010100"
Mon Mar 29 20:03:43 2021 1617041023336 Debug: domyosbike.cpp void domyosbike::characteristicWritten(const QLowEnergyCharacteristic&, const QByteArray&) "characteristicWritten f0 cb 03 00 00 ff 01 00 00 02 01 00 00 00 01 00 00 01 01 00"
Mon Mar 29 20:03:43 2021 1617041023342 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  exit for timeout
Mon Mar 29 20:03:43 2021 1617041023365 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool) " >> 00 01 ff ff ff ff c1 // updateDisplay elapsed=0"
Mon Mar 29 20:03:43 2021 1617041023373 Debug:   HCI event triggered, type: 13
Mon Mar 29 20:03:43 2021 1617041023398 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "0001ffffffffc1"
Mon Mar 29 20:03:43 2021 1617041023405 Debug: domyosbike.cpp void domyosbike::characteristicWritten(const QLowEnergyCharacteristic&, const QByteArray&) "characteristicWritten 00 01 ff ff ff ff c1"
Mon Mar 29 20:03:43 2021 1617041023444 Warning:   L2Cap payload size 23 is smaller than specified size 30
Mon Mar 29 20:03:43 2021 1617041023455 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) " << f0 db 03 00 00 ff 01 00 00 02 01 00 00 00 01 00 00 01 01 00 00 01 ff ff ff ff d1"
Mon Mar 29 20:03:43 2021 1617041023462 Debug: domyosbike.cpp void domyosbike::writeCharacteristic(uint8_t*, uint8_t, QString, bool, bool)  exit for timeout
Mon Mar 29 20:03:43 2021 1617041023758 Debug:   Written Char: "{49535343-8841-43f4-a8d4-ecbe34729bb3}" "f0ac9c"
Mon Mar 29 20:03:43 2021 1617041023762 Debug: domyosbike.cpp void domyosbike::characteristicWritten(const QLowEnergyCharacteristic&, const QByteArray&) "characteristicWritten f0 ac 9c"
Mon Mar 29 20:03:43 2021 1617041023804 Warning:   L2Cap payload size 23 is smaller than specified size 29
Mon Mar 29 20:03:43 2021 1617041023811 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) " << f0 bc 00 00 00 00 00 b6 00 3e 00 00 00 00 01 00 01 00 00 00 00 00 00 00 01 a3"
Mon Mar 29 20:03:43 2021 1617041023820 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current speed: 18.2"
Mon Mar 29 20:03:43 2021 1617041023825 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current cadence: 62"
Mon Mar 29 20:03:43 2021 1617041023832 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current resistance: 1"
Mon Mar 29 20:03:43 2021 1617041023838 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current heart: 0"
Mon Mar 29 20:03:43 2021 1617041023844 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current KCal: 0"
Mon Mar 29 20:03:43 2021 1617041023850 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current Distance: 0"
Mon Mar 29 20:03:43 2021 1617041023857 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current CrankRevs: 1"
Mon Mar 29 20:03:43 2021 1617041023863 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Last CrankEventTime: 990"
Mon Mar 29 20:03:43 2021 1617041023870 Debug: domyosbike.cpp void domyosbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&) "Current Watt: 0"


[log.log](https://github.com/cagnulein/qdomyos-zwift/files/6223680/log.log)

**Comment by cagnulein** [comment]
Send me the full log because i think i already fixed it on mobile, and on
raspberry i need to add something
R.

Il lun 29 mar 2021, 20:21 ErnieV ***@***.***> ha scritto:

**Comment by ErnieV** [comment]
It was on bottom of message log.log.

Verstuurd vanaf mijn iPhone

**Comment by ErnieV** [comment]
Here it is again:

If there is anything I can do to help, let me know!


Met vriendelijke groet, 

Erwin Velthuis 
Business Intelligence Consultant 
Unity BI

M: 06-48268343 
E: ***@***.***

**Comment by cagnulein** [comment]
Ops sorry, i was reading it by email. I will check tomorrow.
Have a nice evening ;)

Il lun 29 mar 2021, 21:58 ErnieV ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@ErnieV as i guess it's something already fixed on mobile. You just need to disable a parameter only available on mobile.
@ben75020 it's working on this I guess (qml settings available on raspberry without -qml ;) )

**Comment by ben75020** [comment]
Good to ear that it is working. Documentation about usage will be written
this week.

A wide range of settings are available thru command line switches - you may
want to open src/main.cpp for details :)

Le lun. 29 mars 2021 à 22:13, Roberto Viola ***@***.***> a
écrit :

**Comment by ErnieV** [comment]
@ben75020 I have looked in src/main.cpp and made a list of options (see attached file). Maybe it helps you with writing documentation?
For most options I have no idea what they do though.

Looking forward to the whole list.

[Qdomyos-Zwift options.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/6226436/Qdomyos-Zwift.options.xlsx)

**Comment by ben75020** [comment]
You already did an amazing work @ErnieV. Thank you to much.
I'll get back to you by the end of the day with a pull request and a proper markdown file, based on your file.

At some point it might be interesting having a configuration file being read instead of switches, but it exceeds my current knowledge in C++ :(

**Comment by cagnulein** [comment]
@ErnieV if you want, in this line https://github.com/cagnulein/qdomyos-zwift/blob/bda4f5cf6b17b847ad393644a3e9cab928a22c93/src/domyosbike.cpp#L70 just change the true with the false.

Your distance issue should go away.

**Comment by ErnieV** [comment]
I will try it today.
I can just change it? No need for any qmake / make operations?

Met vriendelijke groet, 

Erwin Velthuis 
Business Intelligence Consultant 
Unity BI

M: 06-48268343 
E: ***@***.***

**Comment by ben75020** [comment]
of course, you need to rebuild after changing the source code !

**Comment by ErnieV** [comment]
I'm just a simple BI Developer, trying to learn this stuff... ;)

If we need any database development done on this project I have more to contribute...

**Comment by ErnieV** [comment]
> @ErnieV if you want, in this line
> 
> https://github.com/cagnulein/qdomyos-zwift/blob/bda4f5cf6b17b847ad393644a3e9cab928a22c93/src/domyosbike.cpp#L70
> 
> just change the true with the false.
> Your distance issue should go away.

This works perfectly, thank you!

I also figured something else out: If I turn on the Raspberry PI and let is start up before you power up the Domyos Bike 500 I get the continuously reconnecting Bluetooth connection.
If I turn on the bike (start pedaling -> self powered) and turn the PI on afterwards then everything is ok.

**Comment by cagnulein** [comment]
Yes because Linux uses a cache. I guess i can fix it. put here a full log
of this issue

Il mar 30 mar 2021, 12:32 ErnieV ***@***.***> ha scritto:

**Comment by ben75020** [comment]
https://github.com/cagnulein/qdomyos-zwift/pull/228/ 

@ErnieV Your table has been merged onto official documentation. 

@cagnulein 
Next step would be merge your blog article content onto QML Operations

**Comment by cagnulein** [comment]
@ErnieV i'm closing this one. if you still need help please feel free to reopen it!
