### ISSUE TITLE
[REQ] Add Profiles Shortcut or Widget

### ISSUE THREAD

**Issue by burrellka** [cagnulein/qdomyos-zwift#2210]
I often switch between a bike and a treadmill, and I also I have different profiles for my son and wife. Quite a process to switch between them and ensuring we use the right one in each case :). Is it possible to add either widgets or shortcuts to be able to launch QZ with a specific profile? Thanks and as always, I appreciate your help.

**Comment by cagnulein** [comment]
One more question : are you on android or ios?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 18:19 burrellka ***@***.***>
ha scritto:

**Comment by burrellka** [comment]
Hi Roberto. Android. Let me known if that helps and thanks.

**Comment by cagnulein** [comment]
note for me
src/ios/ios_app_delegate.mm


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 mar 2024 alle 22:23 burrellka ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done @burrellka I will pushing it in some days!

**Comment by burrellka** [comment]
Amazing!!! This is awesome Robert. Looking forward to using this cool new feature, Thank you for considering and implementing this.

**Comment by burrellka** [comment]
Perfect! Thanks Roberto. I've been using it and loving it. Thanks again for making this available.
