### ISSUE TITLE
EX3 connect/disconnect loop

### ISSUE THREAD

**Issue by Riddlechicken** [cagnulein/qdomyos-zwift#2211]
EX3 is recognized by the app and attempts to connect, no metrics or device information is updated within the app and then it disconnects. This is accompanied by the Bluetooth symbol in the app becoming solid and then greying out, along with the bike beeping like its connecting, staying solid for half a second, then beeping and reverting to the blue flashing "paring" indicator.
[debug-Mon_Mar_11_19_03_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14566061/debug-Mon_Mar_11_19_03_58_2024.log)

**Comment by Riddlechicken** [comment]
[debug-Mon_Mar_11_19_03_58_2024[1].log](https://github.com/cagnulein/qdomyos-zwift/files/14566084/debug-Mon_Mar_11_19_03_58_2024.1.log)

**Comment by cagnulein** [comment]
@Riddlechicken i suggest to change the power supply, could be the reason. otherwise it's the bluetooth controller that it's faulty

**Comment by cagnulein** [comment]
@Riddlechicken any news?
