### ISSUE TITLE
[BUG] QZ incorrectly reporting huge distance on bike and not recording details on Apple health

### ISSUE THREAD

**Issue by MrPicklesRocks** [cagnulein/qdomyos-zwift#2213]
**Describe the bug**
QZ seems to record distance as a multiple of real distance as per the bike. In the example photos you can see QZ reported a distance of 237mi versus the bike showing 33.7. The reported speed also seems to spike wildly (over 400mph) at times. When the session is over and hit stop on watch then stop on the app, the recorded data does not contain much of the session information (no calories, distance or such)

**To Reproduce**
Bike is nautilus b616. Start select bike on QZ hit start Apple Watch then start on QZ app on phone. Workout and watch the data get wildly out of range.

**Expected behavior**
Should record the proper distance and session data

**Screenshots**

**Smartphone (please complete the following information):**
iPhone 15 pro max
iOS 17.3.1
![IMG_0156](https://github.com/cagnulein/qdomyos-zwift/assets/162730216/7a027245-a824-492d-b9d2-d5abb2ddd814)
![IMG_0157](https://github.com/cagnulein/qdomyos-zwift/assets/162730216/45dc66c4-1ae3-4451-9934-4815d7e4dad0)
![IMG_0158](https://github.com/cagnulein/qdomyos-zwift/assets/162730216/6b6c562f-bee0-4e33-96e2-eaa231009923)
![IMG_0160](https://github.com/cagnulein/qdomyos-zwift/assets/162730216/7f5f7f7a-82d4-4933-91d7-68b623d0b26a)
![IMG_0159](https://github.com/cagnulein/qdomyos-zwift/assets/162730216/67874256-c8b2-49fc-9212-56826cb65856)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
 Debug log was too large to attach, link is at https://www.dropbox.com/scl/fi/xv1ninr8spo8gg5fe0fqp/debug-Mon_Mar_11_21_59_10_2024.log?rlkey=wy23l9kcvjiuxx99egqcr8k5z&dl=0
  
**Additional context**

**Comment by cagnulein** [comment]
@MrPicklesRocks got the issue! that's an easy one!
i will send you the fix tomorrow 

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@MrPicklesRocks fixed! i'm sending you the new version! for the other metrics on apple health, be sure to enable all the permission for QZ with the new beta!

**Comment by cagnulein** [comment]
@MrPicklesRocks any news?
