### ISSUE TITLE
[BUG] Heart rate vanishes when treadmill starts using Rhythm 24

### ISSUE THREAD

**Issue by laurenweinstein1** [cagnulein/qdomyos-zwift#2214]
This used to work fine, but no longer does. I'm unsure when it began failing.

Using a Rhythm 24 armband configured as a power device (which permits display of both heart rate and cadence), heart rate now goes to 0 (or alternates between 0 and the correct rate every few seconds) as soon as the treadmill is started. Cadence continues to display properly the entire time. When the treadmill is stopped, the correct heart rate appears and stays stable again. Debug attached. In this particular debug, heart rate goes to 0 and stays there the entire time the treadmill is running. 

[debug-Tue_Mar_12_11_57_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14577539/debug-Tue_Mar_12_11_57_14_2024.log)

Thanks.

**Comment by cagnulein** [comment]
@laurenweinstein1 enable this "Disable HRM from Machinery" under the heart rate settings in QZ
Let me know

**Comment by cagnulein** [comment]
do you mind share me a log in the scenario with this setting enabled? it's
the only way to see if there is another issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 20:44 Lauren Weinstein <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
never mind got the issue

Debug: ../src/devices/bluetoothdevice.cpp void
bluetoothdevice::update_hr_from_external() WearOS Companion Heart: 0

put the rhythm also as a heart device should solve the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 20:49 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the issue, line 524 of the fitshow treadmill (note for me)

i will fix it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 21:29 Lauren Weinstein <
***@***.***> ha scritto:

**Comment by laurenweinstein1** [comment]
Thanks! -L

**Comment by cagnulein** [comment]
this is about this
https://github.com/cagnulein/qdomyos-zwift/commit/eda7e72d04f15eec5e3abadb71ec5c6254040ed7#diff-cdd0f782ee2a62d0a8264535d5698d1284efc515c379694c1874fdb285b9de14
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle ore 21:43 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
fixed @laurenweinstein1 it will be in the 2.16.49
Thanks

**Comment by laurenweinstein1** [comment]
Hi. Just as an FYI, are you aware that Google Play lists the "Updated on"
date for the app as Aug 6, 2023 ? Bizarre. -L

**Comment by cagnulein** [comment]
Yes I would like to update it but I always put stability as first.

With android 14 I did a lot of changes so I'm waiting to push the beta as
the official one until I'm 100% sure

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 mar 2024 alle 00:48 Lauren Weinstein <
***@***.***> ha scritto:

**Comment by laurenweinstein1** [comment]
Is there a sense when .49 will be released? Thanks!

**Comment by cagnulein** [comment]
Into the beta channel? I guess this week

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 mar 2024 alle 23:00 Lauren Weinstein <
***@***.***> ha scritto:

**Comment by laurenweinstein1** [comment]
New beta appears to fix this bug, thanks! There does seem to be a
configuration change worth noting though. With this device, it was
previously necessary to have heart band disabled and the device selected as
the power sensor, if both heart rate and cadence were to be displayed. In
this configuration with the new beta, the bug still appears to be present
-- cadence is correct but heart rate alternates between correct and zero,
sometimes just sitting at zero for seconds at a time.

HOWEVER, if the device is ALSO chosen as heart band, everything now appears
to work correctly with this beta, with both cadence and heart rate
displaying correctly. Thanks again! -L

**Comment by cagnulein** [comment]
thanks for the feedback. could you please send me an actual debug log so i
can check how and where I modified the behavior?
thanks as always

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 mar 2024 alle 19:36 Lauren Weinstein <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@laurenweinstein1 any news?
