### ISSUE TITLE
[BUG] Unable to control my F80 (2023) treadmill

### ISSUE THREAD

**Issue by samibisfit** [cagnulein/qdomyos-zwift#2215]
**unable to control my F80 using QZ**
QZ demonstrates capability to find my F80 treadmill 2023 version, is able to show a count up on the timer, but does not start the belt at all. QZ does recognize my Bluetooth HRM, and it does submit the results to Strava, but it does not start the treadmill belt. 

**Expected behavior**
I expected to be able to start my treadmill using the QZ at as indicated by the developer.

 - OS: phone is Android 12, Samsung Note 10+
 - Version: treadmill version 1.5, most up-to-date.
 
When attempting to use QZ with my Peloton app, QZ notes the class information.

I am unable to submit the debug log from the app. It is not a supportable file type.

**Comment by cagnulein** [comment]
@samibisfit I need the debug log to understand the issue. I guess you was attempting to submit a fit file instead of a debug log that's why it was not supported. Debug log has the prefix debug 

Let me know

**Comment by samibisfit** [comment]
I will submit a new ticket with the log.

**Comment by cagnulein** [comment]
just attach it here as a new comment, thanks
