### ISSUE TITLE
Unable to control my F80 (2023) treadmill

### ISSUE THREAD

**Issue by samibisfit** [cagnulein/qdomyos-zwift#2218]
**unable to control my F80 using QZ**

QZ demonstrates capability to find my F80 treadmill 2023 version, is able to show a count up on the timer, but does not start the belt at all. QZ does recognize my Bluetooth HRM, and it does submit the results to Strava, but it does not start the treadmill belt.

**Expected behavior**
I expected to be able to start my treadmill using the QZ at as indicated by the developer.

OS: phone is Android 12, Samsung Note 10+
Version: treadmill version 1.5, most up-to-date.
When attempting to use QZ with my Peloton app, QZ notes the class information.

[debug-Tue_Mar_12_18_20_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14584881/debug-Tue_Mar_12_18_20_20_2024.log)

**Comment by cagnulein** [comment]
@samibisfit could you please try to disable the "inclination (experimental)" in the sole treadmill setting in qz and reboot? share a new log if it still doesn't work

thanks

**Comment by cagnulein** [comment]
@samibisfit Please attach the log as a file
Thanks

**Comment by samibisfit** [comment]
[debug-Tue_Mar_12_18_20_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14600567/debug-Tue_Mar_12_18_20_20_2024.log)

**Comment by cagnulein** [comment]
hi thanks, since the log is truncated I can't see the version of QZ. Are you on the beta? if not please join it https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

I guess the "inclination (experimental)"  was not handled in the regular version on the store.
Let me know!

**Comment by cagnulein** [comment]
@samibisfit any news?
