### ISSUE TITLE
[BUG] Pooboo cadence

### ISSUE THREAD

**Issue by caityjokes** [cagnulein/qdomyos-zwift#2219]
**Describe the bug**

Your app was recommended to me on Reddit after I asked about "jailbreaking" a built in cadence sensor on my cheap Amazon bike (Pooboo D262). I've gotten your app to actually find the Bluetooth connection, which is more than I've been able to otherwise! (Manual says it's only made to connect to Zwift and "Think Fit".) But the connection doesn't seem to be relaying the information. I've attached a screenshot I took while pedaling at probably 60 cadence. Your app connected to my Peloton login just fine. What do you think? What should I try? 

**Expected behavior**
Expect it to at least display cadence and resistance of bike. Ideally create bridge of that data with Peloton for FTP workouts

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 17.3.1
 
[debug-Wed_Mar_13_09_10_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14588222/debug-Wed_Mar_13_09_10_20_2024.log)
![IMG_0273](https://github.com/cagnulein/qdomyos-zwift/assets/163308966/47ead6df-84ae-4fea-8ab3-d7e239bf3fbb)
[debug-Wed_Mar_13_09_10_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14588234/debug-Wed_Mar_13_09_10_20_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @caityjokes i just checked your log and I sent you the new beta of the app.
On it, remove the sensor from the cadence sensor setting and also from the power sensor one. Set it instead on the ftms bike setting under the bike setting and restart the app.
Let me know!

**Comment by cagnulein** [comment]
great! let me know if you have any other questions!
