### ISSUE TITLE
Noble Pro E8 no data [BUG]

### ISSUE THREAD

**Issue by SebNoble** [cagnulein/qdomyos-zwift#2220]
**Describe the bug**
I am attempting to use the QZ feature for Kinni, it seems to be sending Kinni no data. Likewise when I use the QZ beta app the app does no detect the E8 treadmill is running and it can't stop/start the E8 treadmill.

**To Reproduce**
1. Go to QZ Beta app
2. Discover the Noble Pro E8 treadmill
3. Cannot stop or start / read any data from the treadmill

**Expected behavior**
I can stop/ start the treadmill, also read the speed etc of the treadmill

**Screenshots**

(please complete the following information):** I assume this is for the treadmill
 - OS: [Android]
 - Version [N/A]

**Smartphone (please complete the following information):**
 - Device: [Samsung A52]
 - OS: [Android]
 - Version [13]

**Append a debug log**

[debug-Wed_Mar_13_13_12_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14588308/debug-Wed_Mar_13_13_12_35_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
got the issue @SebNoble 

these are the services from the treadmill

```
Wed Mar 13 13:12:38 2024 1710335558520 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {00001800-0000-1000-8000-00805f9b34fb} 6144"
Wed Mar 13 13:12:38 2024 1710335558521 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {00001801-0000-1000-8000-00805f9b34fb} 6145"
Wed Mar 13 13:12:38 2024 1710335558522 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {0000180a-0000-1000-8000-00805f9b34fb} 6154"
Wed Mar 13 13:12:38 2024 1710335558523 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {00001826-0000-1000-8000-00805f9b34fb} 6182"
Wed Mar 13 13:12:38 2024 1710335558524 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {0000dca1-0000-1000-8000-00805f9b34fb} 56481"
Wed Mar 13 13:12:38 2024 1710335558524 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {00001814-0000-1000-8000-00805f9b34fb} 6164"
Wed Mar 13 13:12:38 2024 1710335558529 Debug: ../src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "serviceDiscovered {0000180d-0000-1000-8000-00805f9b34fb} 6157"
```

i don't see any FITSHOW characteristic here. Are you sure is fitshow enabled?
in order to use the FTMS instead, go into settings, treadmill, ftms treadmill and select the noblepro connect and restart QZ

Let me know

**Comment by cagnulein** [comment]
maybe the` 0000dca1-0000-1000-8000-00805f9b34fb` is the fitshow service? if so why it's not using the standard? I can add this of course in case

**Comment by cagnulein** [comment]
@SebNoble how did you fix it?
