### ISSUE TITLE
[BUG]Odometer showing value before workout begins

### ISSUE THREAD

**Issue by Jacquie501** [cagnulein/qdomyos-zwift#2221]
[debug-Tue_Mar_12_19_56_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14590598/debug-Tue_Mar_12_19_56_49_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Jacquie501 please describe this better. I just see the log and the distance is starting from 0 as it should. Let me know

**Comment by cagnulein** [comment]
@Jacquie501 this log doesn't have a strange distance value and it's not about the screenshot. maybe you have another log?

**Comment by Jacquie501** [comment]
That’s odd, my odometer was reading over 100 miles even before I started my workout… as you can see, it is showing 107 miles after just two minutes. It has happened before, but not consistently.I generally do two workouts a day, one bike, and one strength… did I submit the wrong log… I can submit the other as well…Sent from Jacquie’s iPadOn Mar 13, 2024, at 10:15 AM, Roberto Viola ***@***.***> wrote:﻿
@Jacquie501 please describe this better. I just see the log and the distance is starting from 0 as it should. Let me know

**Comment by cagnulein** [comment]
yes sure, send them all, so i will check the right one myself

**Comment by Jacquie501** [comment]
[debug-Tue_Mar_12_20_11_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14590778/debug-Tue_Mar_12_20_11_19_2024.log)
[debug-Tue_Mar_12_19_56_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14590779/debug-Tue_Mar_12_19_56_49_2024.log)

**Comment by cagnulein** [comment]
one is the same of the other one, and the second one is not a real session. if it happens again send me the log and I will check it for sure!

**Comment by Jacquie501** [comment]
Strange… I will send another if and when it happens again… as I said, it doesn’t happen every time… my bike odometer reads a little differently than QZ, but always starts at 0, so I think it is somewhere in my settings, but so odd that it doesn’t happen every time.Thanks for your help!Sent from Jacquie’s iPadOn Mar 13, 2024, at 10:30 AM, Roberto Viola ***@***.***> wrote:﻿
one is the same of the other one, and the second one is not a real session. if it happens again send me the log and I will check it for sure!

**Comment by cagnulein** [comment]
I have an idea about the issue but i need a confirmation from a log. Thanks, let me know

**Comment by Jacquie501** [comment]
Will do!Sent from Jacquie’s iPadOn Mar 13, 2024, at 10:37 AM, Roberto Viola ***@***.***> wrote:﻿
I have an idea about the issue but i need a confirmation from a log. Thanks, let me know

**Comment by cagnulein** [comment]
@Jacquie501 any news?

**Comment by Jacquie501** [comment]
No, it must have been a fluke because it hasn’t happened again… inexplicable! Thanks for asking.JacquieSent from Jacquie’s iPadOn Apr 10, 2024, at 11:53 PM, Roberto Viola ***@***.***> wrote:﻿
@Jacquie501 any news?
