### ISSUE TITLE
[BUG] Odometer Increasing while activity not started when using Stryd pod as Treadmill

### ISSUE THREAD

**Issue by taxi333** [cagnulein/qdomyos-zwift#2222]
**Describe the bug**
The odometer start accumulating distance while the activity has not been started while using Stryd pod as Treadmill

**To Reproduce**
Set stryd pod as treadmill.

**Expected behavior**
Odometer only increases if activity is started and not paused 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - iPhone15 Pro Max
 - iOS 17.0.3
 - QZ Version 2.16.34

Note: 1st .05 km of this activity were recorded while activity was not in `start` (start button was flashing red)
[debug-Wed_Mar_13_17_45_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14594776/debug-Wed_Mar_13_17_45_44_2024.log)

Here's the resulting .fit file (compressed)
[Wed Mar 13 18_15_32 2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14594800/Wed.Mar.13.18_15_32.2024.zip)

  Please let me know if you need me to record a shorter activity (I had to remove the a few thousand lines from the end of the debug file to comply with the 25MB attachment limit of github)

**Comment by cagnulein** [comment]
hi, the issue is that you set the sytrd also as a cadence sensor. Don't  :) remove it and put disabled there and the issue will go away

Let me know!

**Comment by taxi333** [comment]
Hi Roberto, this issue seems to still be present after removing the stryd pod as cadence sensor
[debug-Thu_Mar_14_17_35_23_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14608638/debug-Thu_Mar_14_17_35_23_2024.log)

Please let me know if you need me to try something different

**Comment by cagnulein** [comment]
ah yes this is the default behaviour. I'm reluctant to change it because most of the users check speed and distance to see that everything is working ok before starting. May I suggest to press start and stop to restart the activity or simiply close the app to start a blank activity when you are ready to start?

What do you think?

**Comment by taxi333** [comment]
Yes, that can work, is just something that I found, thank you for looking into it, I will close this bug.

**Comment by cagnulein** [comment]
ok thanks for understanding

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 mar 2024 alle 20:59 taxi333 ***@***.***> ha
scritto:
