### ISSUE TITLE
Heart Rate not uploading to Strava - [BUG]

### ISSUE THREAD

**Issue by ryanwehr** [cagnulein/qdomyos-zwift#2225]
Heart Rate not uploading to Strava
[45_min_Low_Impact_Ride_Sam_Yo_QZ.zip](https://github.com/cagnulein/qdomyos-zwift/files/14605985/45_min_Low_Impact_Ride_Sam_Yo_QZ.zip)

**Comment by cagnulein** [comment]
Yeah indeed there is no heart. So yes please create a debug log and I will
chdck the reason. Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 18:34 ryanwehr ***@***.***> ha
scritto:

**Comment by ryanwehr** [comment]
OK, I will send you the log in the morning

Ryan

**Comment by cagnulein** [comment]
i don't see it. You have to upload it to github directly

**Comment by ryanwehr** [comment]
[45_min_Low_Impact_Ride_Sam_Yo_QZ.zip](https://github.com/cagnulein/qdomyos-zwift/files/14616096/45_min_Low_Impact_Ride_Sam_Yo_QZ.zip)
Sorry here you go.

**Comment by ryanwehr** [comment]
[debug-Fri_Mar_15_06_49_12_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/14616110/debug-Fri_Mar_15_06_49_12_2024.zip)
Here you go.

**Comment by cagnulein** [comment]
got the issue. you where in pause all the time, the play button in the top
of qz must NOT be blinking red.
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 mar 2024 alle ore 14:37 ryanwehr ***@***.***>
ha scritto:

**Comment by ryanwehr** [comment]
OK, I did not notice that, I will give that a shot.  Thanks

**Comment by cagnulein** [comment]
@ryanwehr any news?
