### ISSUE TITLE
{BUG]no connection to Zwift using a KingSmith R2B Treadmill

### ISSUE THREAD

**Issue by Eggi1970** [cagnulein/qdomyos-zwift#2228]
**Describe the bug**
Started QZ-App, walking on the treadmill, everything ok, started Zwift app. No connection possiple

[debug-Fri_Mar_15_11_34_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14614231/debug-Fri_Mar_15_11_34_52_2024.log)

**Comment by cagnulein** [comment]
that's the issue. you disabled the virtual device in the experimental settings. enable it. also enable the virtual bluetooth device and the dircon one.
restart qz and let me know

**Comment by Eggi1970** [comment]
Well, this one works now. Zwift on same device as qz app.
What is not working is the app on desktop. 
Thanks for your help

**Comment by cagnulein** [comment]
it could be a windows issue. I suggest to test the windows version of qz on the same PC. This is a 15 minute trial version

https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip

**Comment by Eggi1970** [comment]
I was not able to connect to the device. Even though system told me that treadmill is connected I have seen no data...  I assume it was just a setup problem...

**Comment by cagnulein** [comment]
in the qz app on windows do you mean? can you share a log so i can check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?
debug log on windows are on the same folder of the executable once you enable the debug log settings.
thanks

**Comment by Eggi1970** [comment]
[debug-Fr_Mär_15_15_30_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14616893/debug-Fr_Mar_15_15_30_24_2024.log)
here ist the windows log :-)

**Comment by cagnulein** [comment]
thanks. could you please try with this one https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary-no-python.zip ?

**before starting qz, pair the treadmill with the window bluetooth settings.**
Let me know

**Comment by Eggi1970** [comment]
[debug-Fr_Mär_15_15_49_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14617158/debug-Fr_Mar_15_15_49_26_2024.log)
Well I was not able to connect it by the windows bluetooth settings. As you can see in the log, no device was found

**Comment by cagnulein** [comment]
ok so i guess there is a major issue with the bluetooth dongle of your pc. What are you using? I usually suggest this one https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift#for-zwift-pc-users

**Comment by Eggi1970** [comment]
I don't have a specific dongle, my pc has a built in bluetooth..

**Comment by Eggi1970** [comment]
But I ordered the dongle and then I will check if it works and will let you know :-)

**Comment by cagnulein** [comment]
another test that you can do in the meantime is renaming the android device to "run" (only 3 letters) and reboot it
Let me know

**Comment by Eggi1970** [comment]
ok, my android is now renamed to run, meanwhile I can see the KS-Remote-01 in my bluetooth devices, but I'm not able to set up a connection

**Comment by Eggi1970** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/163526532/5b4f6111-8f11-46c1-ab0a-bb926738a429)
[debug-Fr_Mär_15_16_20_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14617446/debug-Fr_Mar_15_16_20_42_2024.log)
Now I was able to connect now, see picture attached. But then app crashed. 
I also sent the new log

**Comment by cagnulein** [comment]
> ok, my android is now renamed to run, meanwhile I can see the KS-Remote-01 in my bluetooth devices, but I'm not able to set up a connection

ok so zwift still doesn't see the run device while qz is open on your android?

**Comment by Eggi1970** [comment]
no, if I start qz app and zwift app on my android device it works fine.
when I start qz app an zwift companion app and the zwift app on my pc it doesn't work

**Comment by cagnulein** [comment]
did you try also without the companion app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 mar 2024 alle ore 16:48 Eggi1970 ***@***.***>
ha scritto:

**Comment by Eggi1970** [comment]
yes, I tried with BT connection, but it did not work... 
But for me it's for the moment ok to have it on the smartphone. I will wait until next week when the dongle arrives. 
Then I will check again.
Many thanks for the moment for your valuable support.

**Comment by cagnulein** [comment]
Ok, let me know.


Il giorno ven 15 mar 2024 alle 16:57 Eggi1970 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Eggi1970 any news?
