### ISSUE TITLE
Horizon 7.4 AT - First Attempt with QZ on Android 14

### ISSUE THREAD

**Issue by hellobensalt** [cagnulein/qdomyos-zwift#2230]
I've attached two debug files from two different tests.

1) QZ quickly connects to my treadmill and I see a red, flashing play button. Clicking on the button initially appears to do nothing - the flashing just continues.

2) After around 30 seconds to 1 minute QZ responds and the start button starts the treadmill.

3) The incline function seems to work and correspond to what the treadmill is doing and displaying on the control panel.

4) But the speed displayed in QZ in kph did not correspond exactly to the speed displayed on the treadmill's lower control panel. Also, the speed displayed on the treadmill LCD screen is still in min/mile, while everything else is in min/km. This is a hangover from my attempts at connecting the related Kinni app. Otherwise, increasing the speed incrementally increases the speed on of the treadmill by the same amount.

5) The stop button stops the treadmill. But in the first debug test I had issues restarting the treadmill again for a new session and ended up restarting the app.

[debug-Fri_Mar_15_19_26_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14616149/debug-Fri_Mar_15_19_26_44_2024.log)

[debug-Fri_Mar_15_19_27_13_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14616150/debug-Fri_Mar_15_19_27_13_2024.log)

**Comment by cagnulein** [comment]
> * QZ quickly connects to my treadmill and I see a red, flashing play button. Clicking on the button initially appears to do nothing - the flashing just continues.
> * After around 30 seconds to 1 minute QZ responds and the start button starts the treadmill.

yes that's the right behaviour because the bleutooth protocol of your treadmill is very awful and it takes more than 50 seconds to complete the init phase.

it's the same with the horizon app if you try



> 4\. But the speed displayed in QZ in kph did not correspond exactly to the speed displayed on the treadmill's lower control panel.

could you make me an example? i mean which is the difference?



> 4\. Also, the speed displayed on the treadmill LCD screen is still in min/mile, while everything else is in min/km. This is a hangover from my attempts at connecting the related Kinni app. Otherwise, increasing the speed incrementally increases the speed on of the treadmill by the same amount.

I can try to change this behaviour but in case I will need some log from you from the Horizon app.



> 5\. The stop button stops the treadmill. But in the first debug test I had issues restarting the treadmill again for a new session and ended up restarting the app.

ok i will check it

**Comment by hellobensalt** [comment]
> > * QZ quickly connects to my treadmill and I see a red, flashing play button. Clicking on the button initially appears to do nothing - the flashing just continues.
> > * After around 30 seconds to 1 minute QZ responds and the start button starts the treadmill.
> 
> yes that's the right behaviour because the bleutooth protocol of your treadmill is very awful and it takes more than 50 seconds to complete the init phase.
> 
> it's the same with the horizon app if you try
> 
> > 4. But the speed displayed in QZ in kph did not correspond exactly to the speed displayed on the treadmill's lower control panel.
> 
> could you make me an example? i mean which is the difference?
> 
> > 4. Also, the speed displayed on the treadmill LCD screen is still in min/mile, while everything else is in min/km. This is a hangover from my attempts at connecting the related Kinni app. Otherwise, increasing the speed incrementally increases the speed on of the treadmill by the same amount.
> 
> I can try to change this behaviour but in case I will need some log from you from the Horizon app.
> 
> > 5. The stop button stops the treadmill. But in the first debug test I had issues restarting the treadmill again for a new session and ended up restarting the app.
> 
> ok i will check it

**Comment by hellobensalt** [comment]
> yes that's the right behaviour because the bleutooth protocol of your treadmill is very awful and it takes more than 50 seconds to complete the init phase.

Wow. That really is terrible. I didn't have many treadmill options to choose from where I'm based. This seemed the best of a bad bunch.

> could you make me an example? I mean which is the difference?

The speed was something like 0.3 kph out on my final test. I didn't check carefully on the previous test as I was so shocked it was actually working. I will run more tests tomorrow and play around with the settings.

> I can try to change this behaviour but in case I will need some log from you from the Horizon app.

I haven't used the Horizon app yet. What logs do you need and how will I go about creating them?

Many thanks for your help.

**Comment by cagnulein** [comment]
> The speed was something like 0.3 kph out on my final test. I didn't check carefully on the previous test as I was so shocked it was actually working. I will run more tests tomorrow and play around with the settings.

ok keep an eye if it's a 0.3 on each value or is something incremental. qz is reading the value directly from the treadmill, so maybe it's just a rounding issue?



> I haven't used the Horizon app yet. What logs do you need and how will I go about creating them?

following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device a log where you are setting the unit in the way that you would like (you don't need any reset from the Horizon technician to do so, just the horizon app)

**Comment by cagnulein** [comment]
[horizon2.txt](https://github.com/cagnulein/qdomyos-zwift/files/14905943/horizon2.txt)
[horizon1.txt](https://github.com/cagnulein/qdomyos-zwift/files/14905944/horizon1.txt)

about the km/h miles thing in the horizon treadmill. i guess i found the byte!

55aa2000010fe80285050100000000000000000000000000000000000000dc0526c207010100**01**5573657220
55aa1800010fe802a47f0400000000000000000000000000000000000000dc0526c207010100**00**5573657220

but i need a final help from you @hellobensalt 

you provided me:
- a log where you changed the miles to km 
- a log where you run the app all in miles

i need now a log where you run the app already all in km. I need this because otherwise I have to add the frames to change the user settings after the init, and this will take even longer in the init phase.

let me know!

**Comment by hellobensalt** [comment]
about the km/h miles thing in the horizon treadmill. i guess i found the
byte!

Glad to hear it! And, thank you!

but i need a final help from you @hellobensalt
<https://github.com/hellobensalt>

i need now a log where you run the app already all in km.

I've attached a log of a session in which I connected to the treadmill,
then clicked start in the app before manually changing the inclination and
speed (in min/km) a number of times. All user profiles were in metric.

you provided me:

   - a log where you changed the miles to km
   - a log where you run the app all in miles

So, now, I've attempted to send the log files from the following sessions
to you:

   - all profiles changes from miles to km, then from km to miles
   - all profiles changes from km to miles
   - all profiles in metric (km) and the treadmill started and stopped from
   the app, with the inclination and speed changed manually on the treadmill

Let me know if this worked and is now sufficient?

All the best.

**Comment by cagnulein** [comment]
hi @hellobensalt you have to attach the file on github directly or to my my personal email otherwise I can't see them

**Comment by hellobensalt** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14917057/btsnoop_hci.log)

Sorry, I thought I was replying to your personal email. Here it is.

**Comment by cagnulein** [comment]
perfect, i will check this and I will let you know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle ore 12:04 hellobensalt <
***@***.***> ha scritto:

**Comment by hellobensalt** [comment]
Do you need anything else from me here?

**Comment by cagnulein** [comment]
Nope I forgot to update you: it seems that in order to set the unit as
metric I need to send additional commands, I have to create a separate
branch for this for you to test it. . Hard days at work (my actual job is
not qz) so I will try to do ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 apr 2024 alle 12:34 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
No problem. I'd already realised this was something you did on the side. I didn't mean to pressure you, I was just curious if it had been done already, but wasn't working.
