### ISSUE TITLE
White screen after ride with iPhone and iPad 

### ISSUE THREAD

**Issue by Jrfrph** [cagnulein/qdomyos-zwift#2231]
**Describe the bug**
White screen after ride on Peleton with Qz on iPhone and Peleton on iPad 
**To Reproduce**
[debug-Fri_Mar_15_11_54_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14618297/debug-Fri_Mar_15_11_54_44_2024.log)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks I will  check it ASAP. Are you from Facebook?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 mar 2024 alle 17:38 Jrfrph ***@***.***> ha
scritto:

**Comment by Jrfrph** [comment]
Yes. No graphs after ride just white screen, but data sent to health app and strava. Running Qz on iPhone and Peleton on iPad with echelon ex5.Thanks,John Ferraro804-721-2205Sent from my iPhone On Mar 15, 2024, at 12:56 PM, Roberto Viola ***@***.***> wrote:﻿
Thanks I will  check it ASAP. Are you from Facebook?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 15 mar 2024 alle 17:38 Jrfrph ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
yes it's the same issue of https://github.com/cagnulein/qdomyos-zwift/issues/857
it's strange that it's coming back. I will analyze it, thanks!

**Comment by cagnulein** [comment]
got the issue, disable the "Peloton Auto Sync Companion (Exp.)" under the peloton settings

**Comment by Jrfrph** [comment]
Thanks. I’ll do that.It’s odd it happens only sometimes. Didn’t happen yesterday, but did today.Again, thanks for your help.This very remarkable app.Thanks,John Ferraro804-721-2205Sent from my iPhone On Mar 15, 2024, at 5:41 PM, Roberto Viola ***@***.***> wrote:﻿
got the issue, disable the "Peloton Auto Sync Companion (Exp.)" under the peloton settings

**Comment by cagnulein** [comment]
yes it was random but it was about that setting

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 mar 2024 alle 23:07 Jrfrph ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Jrfrph any news?

**Comment by Jrfrph** [comment]
FixedThanks,John Ferraro804-721-2205Sent from my iPhone On Apr 10, 2024, at 2:25 AM, Roberto Viola ***@***.***> wrote:﻿
@Jrfrph any news?
