### ISSUE TITLE
[BUG] Kcal same as bike even when "Disable KCal from Equipment" is enabled and can't control resistance with resistance tile.

### ISSUE THREAD

**Issue by JFMorgado** [cagnulein/qdomyos-zwift#2232]
**Describe the bug**
1- Calories spent are the same between the bike screen and QZ even though I enabled "Disable KCal from Equipment".

2-Can't control resistance when I click the "+" or "-" signs on the QZ resistance tile. When I click them resistance stays the same. I can't get the auto-resistance feature to work on mywhoosh in free ride or on ERG mode.

Thank you!

**Smartphone (please complete the following information):**
 - Device: Iphone 12 mini
 - OS: IOS 17.3.1
 - Version 17.3.1

**Append a debug log**

[debug-sex__mar__15_16_53_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14618725/debug-sex__mar__15_16_53_33_2024.log)

**Comment by cagnulein** [comment]
For the auto resistance check this

https://github.com/cagnulein/qdomyos-zwift/issues/2007

I will chdck for the kcal

**Comment by cagnulein** [comment]
fixed @JFMorgado 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@JFMorgado is it ok?

**Comment by JFMorgado** [comment]
Hi!

Sorry for the late response!

I see the same Kcal number on QZ and the display of the bike but now on QZ
the number comes 3 seconds earlier. So if for exemple 43Kcal comes on QZ,
then 3 seconds later, the bike goes from 42 Kcal to 43Kcal.

so something is changed for sure but maybe the numbers are just similar?
From your calculations QZ Kcals should be higher or lower than tyhe
Domyos900 bike? and how much % in difference?

Thank you so much!

Roberto Viola ***@***.***> escreveu (terça, 19/03/2024 à(s)
08:13):

**Comment by cagnulein** [comment]
are you using now the disable kcal setting or not now? with the standard setting (getting the kcal from the bike), qz uses the value received from the bike when the bike sents. Otherwise the calculation is completely different and it's based on weight, gender and wattage

**Comment by JFMorgado** [comment]
Yes just checked and I'm using the setting "disable KCal from Machinery", I
never took it off.

But something is definitely different! The Kcal number now comes first on
the QZ app and only 3s later on the bike, so I guess the bike is not
sending the data to QZ app.

Its just the same Kcal number, and I would guess they would give different
Kcal values over time

Thank you

Roberto Viola ***@***.***> escreveu (terça, 26/03/2024 à(s)
14:32):

**Comment by cagnulein** [comment]
with that setting on QZ is avoiding the kcal value from the bike, instead QZ is writing the kcal value TO the bike. Of course the bike is showing it with a delay because there is a bluetooth communication between this.

**Comment by JFMorgado** [comment]
Ok, so everything is fine!

Thank you for the help! :)

Roberto Viola ***@***.***> escreveu (terça, 26/03/2024 à(s)
14:48):
