### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lgnyjessica82** [cagnulein/qdomyos-zwift#2235]
[debug-Fri_Mar_15_18_30_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14621351/debug-Fri_Mar_15_18_30_27_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[debug-Fri_Mar_15_18_30_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14621373/debug-Fri_Mar_15_18_30_27_2024.log)

**Additional context**

**Comment by cagnulein** [comment]
Yeah actually I don't see the bike at all here

Let's try this: download the free app nrf connect from the store and try to check if you can find it there.

If so try again on qz

Let me know

**Comment by cagnulein** [comment]
@Lgnyjessica82 any news?

**Comment by Lgnyjessica82** [comment]
Qz and peleton are communicating but my target residence and cadence used to recommend somewhere in the middle now it recommends low number which is fine. As far as all my offset settings within qz I have no idea where to set all that. Thanks 

Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Apr 10, 2024 at 2:25, Roberto ***@***.***> wrote:   


@Lgnyjessica82 any news?

**Comment by cagnulein** [comment]
@Lgnyjessica82 Did you set the right peloton difficult in qz in the peloton settings?

**Comment by Lgnyjessica82** [comment]
Probably not lol. I haven't ever done anything with any settings besides my tiles and target peleton resistance and cadence
Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Apr 11, 2024 at 14:43, Roberto ***@***.***> wrote:   


Reopened #2235.

**Comment by cagnulein** [comment]
Eheheh ok let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 21:18 Lgnyjessica82 ***@***.***>
ha scritto:

> Probably not lol. I haven't ever done anything with any settings besides
> my tiles and target peleton resistance and cadence
> Yahoo Mail: Search, Organize, Conquer
>

**Comment by Lgnyjessica82** [comment]
Ok thanks. I set difficulty to average. What do I do with conversion gain and conversion offset?

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Apr 11, 2024 at 15:19, Roberto ***@***.***> wrote:   

Eheheh ok let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 21:18 Lgnyjessica82 ***@***.***>
ha scritto:

> Probably not lol. I haven't ever done anything with any settings besides
> my tiles and target peleton resistance and cadence
> Yahoo Mail: Search, Organize, Conquer
>

**Comment by cagnulein** [comment]
Leave as they are for now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 21:35 Lgnyjessica82 ***@***.***>
ha scritto:

> Ok thanks. I set difficulty to average. What do I do with conversion gain
> and conversion offset?
>
> Yahoo Mail: Search, Organize, Conquer
>

**Comment by Lgnyjessica82** [comment]
Will do! Thank you so much! 

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Apr 11, 2024 at 15:36, Roberto ***@***.***> wrote:   

Leave as they are for now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 21:35 Lgnyjessica82 ***@***.***>
ha scritto:

> Ok thanks. I set difficulty to average. What do I do with conversion gain
> and conversion offset?
>
> Yahoo Mail: Search, Organize, Conquer
>
