### ISSUE TITLE
[BUG] Pro-Form Pro 2000

### ISSUE THREAD

**Issue by mdaypersonal** [cagnulein/qdomyos-zwift#2237]
I have a Pro-Form Pro 2000 that I cannot get the tiles to update on. I was able to install via adb and select the treadmill model from the list. I have the IP set under Nordictrack 2950 IP:. I have both an Android phone and an iPad and I have the exact same issue on both. I have factory reset the treadmill and went through all the steps again but to no avail. I have verified I can connect via adb from my laptop, and I was able to connect successfully. I have also checked the Android permissions on the built-in treadmill screen for the app and the only permission is read storage and it is enabled. Still, none of the tiles (speed, incline, etc.) still update, they are all 0s. 

Treadmill Apps: 
Android version 7.0
Android buid: MKA1_20230310
iFit version 2.6.88
QZ Companion Nordctrack Treadmill version 3.3.41

Android:
Android version 14
qdomyos-zwift version 2.14.0

iPad:
iPadOS version 17.4
QZ - qdomyos-zwift version 2.15

Debug taken from iPad is attached.
[debug-Sun_Mar_17_14_50_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14628866/debug-Sun_Mar_17_14_50_59_2024.log)

**Comment by cagnulein** [comment]
hi the issue same the same of https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

follow the same steps and report back!

let me know

**Comment by cagnulein** [comment]
also check this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/41

**Comment by cagnulein** [comment]
wasn't u?

**Comment by mdaypersonal** [comment]
> hi the issue same the same of [#1591 (comment)](https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559)
> 
> follow the same steps and report back!
> 
> let me know

I ran the adb command but still have the same issue.

Also the other issue you linked was in fact me, but the fix from back then does not work anymore. I have the IP in the correct settings location. I have not used it in a few months and had to factory reset my treadmill and now it no longer works.

**Comment by cagnulein** [comment]
so that's ifit trying to block qz

only solution: do a factory reset but DON'T uodate ifit after the reset (block internet for your bike)

**Comment by cagnulein** [comment]
@mdaypersonal any news?

**Comment by cagnulein** [comment]
@mdayallegion ok let's try to undertand it a bit more: are you able to provide an adb logcat while you are doing a workout. Even a small 1 minute workout, the important thing is to run the adb logcat from your pc while you're still doing the workout

Let me know!

**Comment by cagnulein** [comment]
@mdaypersonal  @mdayallegion any news?

**Comment by mdaypersonal** [comment]
I haven't had time to dive back into it. Feel free to close this issue as I don't think I will be able to dedicate time in the near future.
