### ISSUE TITLE
[BUG] Zwift play won’t shift gears or steer

### ISSUE THREAD

**Issue by punter9** [cagnulein/qdomyos-zwift#2239]
**Describe the bug**

I have beta qz app on iPhone 7.  Zwift play connected to qz app not Zwift.  They don’t do anything (shift gears or steer).  

**To Reproduce**
1. Load qz app
2. Connect Zwift play 
3. Link to Zwift with wahoo devices
4. (Nothing shows up in controls)

**Expected behavior**

be able to steer and shift 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Apple TV 4K

**Smartphone (please complete the following information):**
[debug-Mon_Mar_18_09_21_06_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14639507/debug-Mon_Mar_18_09_21_06_2024.log)

 - Device: iPhone 7 and qz beta

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@punter9 log checked. the zwift play are both connected but they didn't reacts to the qz commands. There are 2 possible reasons for this:
1- firmware is not updated on the zwift play devices
2- reset them with pressing the Z button for 10 seconds each one if I remember correctly

Let me know

**Comment by punter9** [comment]
Ok all of that is done.  I can shift now but cant steer.  Is anything supposed to populate in the Zwift window for controls when linked to the phone?

**Comment by cagnulein** [comment]
Nope, steering is not implemented yet

**Comment by cagnulein** [comment]
So what was the issue before?

**Comment by cagnulein** [comment]
@punter9 are we ok with this?
