### ISSUE TITLE
[BUG] Decline from the gui does not go beyond -1 and metrics become garbled

### ISSUE THREAD

**Issue by erwinvol** [cagnulein/qdomyos-zwift#2240]
**Describe the bug**
When connected to my Sole F89 treadmill, i cannot change the decline beyond -1.

The value in the screen jumps to 6552 for example and i have to push the + to get back to 0 and 1 etc.

Zwift inclined works fine but again the QZ UI value becomes messed up when in decline. 

This also impacts the elevation and wattage values

**To Reproduce**
Open app
Click on - at the inclination setting and go beyond 0

**Expected behavior**
I would expect to see -1 -2 -3 etc

**Screenshots**
See attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: pixel 7 pro
 - OS: android
 - Version 14

**Append a debug log**
Will create one later today

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks, I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 mar 2024 alle 18:55 Erwin ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @erwinvol i need a debug log to check the issue. could you please provide me it with the issue?

**Comment by erwinvol** [comment]
Sure, attached.

**Comment by cagnulein** [comment]
Hi @erwinvol you have to push to github directly otherwise I can't see it
Thanks

**Comment by erwinvol** [comment]
My bad, Terry

[debug-Mon_Mar_18_17_50_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14650054/debug-Mon_Mar_18_17_50_44_2024.log)

**Comment by cagnulein** [comment]
done, the fix will be in the 2.16.49
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 mar 2024 alle ore 12:48 Erwin ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@erwinvol are we good with this?

**Comment by erwinvol** [comment]
I've been traveling since I received the update with the fix. I'll try
within the next couple of days.

**Comment by erwinvol** [comment]
Can confirm, it is working properly now.
Thanks again!

**Comment by cagnulein** [comment]
That's great! Thanks!
