### ISSUE TITLE
[BUG]Yesoul G1SPlus wifi off bt only

### ISSUE THREAD

**Issue by eringodzilla** [cagnulein/qdomyos-zwift#2241]
**Describe the bug**
Per Facebook comment I followed instructions here:
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md?fbclid=IwAR2cN4NHEt2XdB6YY3aP6pcPU0I3oIru7kvEo6M6_VZlPs8kXpRI5qNSXWg#android

I am trying to use companion app on my Yesoul S1Plus screen and was originally trying to follow the instructions here: https://github.com/cagnulein/QZCompanionYesoul?fbclid=IwAR1eAWprfKwwGYpPqbRgI3DsgAxSo_eeTOgJy8YyfQJPcZ4TQxV0gv0XWaI

Yesoul G1SPlus wifi off bt only - I connected to the app and pedaled while reducing the resistance.  Time was less than ~30 seconds before disconnecting.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version: 23H2

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 Ultra
 - OS: Android OS
 - Version: 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14643531/btsnoop_hci.log)

  
**Additional context**

**Comment by cagnulein** [comment]
hi @eringodzilla i can't see any bluetooth connection to your bike. Stupid question: did you run the yesoul bike with internet and wifi data off while you were collecting this log? It's the only way to force the app to talk via bluetooth with the bike

let me know!

**Comment by cagnulein** [comment]
@eringodzilla any news?
