### ISSUE TITLE
Auto Inclination on Zwift without meetups not able to get it working.

### ISSUE THREAD

**Issue by craigsale** [cagnulein/qdomyos-zwift#2243]
**Describe the bug**
Hiya Roberto I have a Spirit XT385 you helped me get it working a long time ago. I used meetups to get auto-inclination working on Zwift with you, I was happy to see you can now do Auto Inclination without meetups but I can't get it working.
Using meetups the Inclination icon flashes to show its engaged but not using meetups the indicator never flashes.
I have both Qdomyos for IOS and Android, prefer to use Android. Have tried both phones doesn't work on Apple either.
OnePlus 5 with Android 10 and Oxygen 10.1
Iphone 10 XS with latest updates installed.

Any combination of settings I need to check are correct. I removed app on both phones and installed beta and test flight versions

Will get some logs if required.

Hope your doing well, 
Craig
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @craigsale first question: did you set the zwift credentials on qz?

**Comment by craigsale** [comment]
Thanks for prompt reply, no I didn't ever fill that credential out before but will do and test it in the morning. Will let you know.

**Comment by craigsale** [comment]
Hello Roberto
No joy on either phone.
What I do is turn on the readmill and start up zwift on my Windows Laptop.
Open QZ and it finds the XT385 no problems and the TM beeps a few times, I have tried with pause on start switched on or off.
I then discover QZ on Zwift as TREAD 003.
if I start the readmill to a few KMH it registers on QZ but no Inclination Icon and the Speed can't be adjusted on QZ now, before that used to work to.

**Comment by craigsale** [comment]
Hiya Roberto
Ok tested again this morning, looks to be working much better as you can see from the elevation reported in Strava, I think those Zwift creds were not in correctly, it looked like they were all upper case before and now they are all lower case, not that it should matter with email address. Anyway What I need to do now is get the offset right. 
The Inclination has a delay which is good, but once it gets up above 6% the higher it gets the more difference there is between Zwifts reported Incline and QZs reported Incline, for example on zwift if its 10% the QZAPP will report it anywhere between 12 and 13%.
Only tested with Android phone so far so these are findings are Android based.

**Comment by craigsale** [comment]
What does Zwift Treadmill Climb Portal do.?

**Comment by cagnulein** [comment]
hi, remember that zwift shows the average instead qz the actual one. that's
the difference. anyway you can use the zwift inclination gain for example
to 0.9 to better match it

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 mar 2024 alle 07:14 craigsale ***@***.***>
ha scritto:

**Comment by craigsale** [comment]
I will test it, sorry for the delay, haven't forgotton.
