### ISSUE TITLE
[BUG] ERG mode

### ISSUE THREAD

**Issue by FGT10** [cagnulein/qdomyos-zwift#2244]
![Screenshot_20240320_223911](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/dfaf3978-3835-41b8-ac27-79b296d88730)
![Screenshot_20240320_223905](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/2d4022a0-8b7c-4232-89a2-d70e3dbef388)
![Screenshot_20240320_223851](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/42ce5a9e-1c81-4bd6-98c9-712848a0869e)
![Screenshot_20240320_223834](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/da9c2f43-dec1-4534-8da9-6c482eec7ef8)
![Screenshot_20240320_223817](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/4fbf89f8-f3a6-4199-ab4a-50f6acd8288c)
![Screenshot_20240320_223806](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/1bfa7dbd-c99f-46ee-9302-f96f7877d009)
![20240320_220632](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/6f868edf-5705-404e-86c9-bd0e880736c5)
![20240320_220627](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/ec02b7d4-f856-444c-abc4-99a73d7b28e4)

 I recently purchased your app on my Samsung galaxy S10+ to connect my proform tdf bike to Zwift on an iPad. Bike and phone connected by WiFi.

Everything seems to work, bike and zwift are connected except for one thing: ERG mode. I can see on the qz app that the power tile is changing but the bike doesn't receives the order.

I added screenshots of my settings 

Thanks for helping.

**Comment by cagnulein** [comment]
Thanks but I need a debug log to understand your issue

**Comment by FGT10** [comment]
OK I'll try tonight, this morning the app doesn't connect to the bike...

Le mer. 20 mars 2024, 22:45, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
maybe your bike ip has changed

**Comment by FGT10** [comment]
[debug-Thu_Mar_21_19_20_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14705477/debug-Thu_Mar_21_19_20_02_2024.log)

Hi, today my bike doesn't connect to my phone...
Here is the file
I checked the IP, it's OK. Even when it worked yesterday there was "connecting..." on the app (see the screenshot I sent yesterday)

**Comment by cagnulein** [comment]
You have the fake treadmill setting enabled in the experimental settings.
Disable it and restart qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 mar 2024 alle 19:28 FGT10 ***@***.***> ha
scritto:

**Comment by FGT10** [comment]
[debug-Thu_Mar_21_19_20_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14705477/debug-Thu_Mar_21_19_20_02_2024.log)

Hi, today my bike doesn't connect to my phone...
Here is the file
I checked the IP, it's OK. Even when it worked yesterday there was "connecting..." on the app (see the screenshot I sent yesterday)
![Screenshot_20240321_193550](https://github.com/cagnulein/qdomyos-zwift/assets/164257147/d77778e3-4f3a-4ae4-91e3-ac7eecc23d33)

**Comment by cagnulein** [comment]
You have the fake treadmill setting enabled in the experimental settings. Disable it and restart qz

**Comment by FGT10** [comment]
Okay ERG seems to work, thank you! Ciao !

**Comment by cagnulein** [comment]
Glad it worked!


Il giorno gio 21 mar 2024 alle 19:50 FGT10 ***@***.***> ha
scritto:
