### ISSUE TITLE
HealthRider H70T

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2245]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/14686901/btsnoop_hci.log)

**Comment by cagnulein** [comment]
nordictrack_t65s_treadmill ?

**Comment by BbqAddict** [comment]
Yes.  Currently running as T6.5 V81 on the QZ app and its working great.  I tried that setting on the kinni app and it didnt work tho.   No worries for me as I use Kinomap and only used Kinni for fitcast.  I will try it again soon on Kinni and report back if it works.  Its possible I didnt try hard enough.

Thanks again
