### ISSUE TITLE
[BUG] Noble Pro connecting but no data and insta pauses

### ISSUE THREAD

**Issue by RoadRacer87** [cagnulein/qdomyos-zwift#2246]
**Describe the bug**

After you looked at this recently ( c. week ago), my android device with the beta picked up Noble Pro and was receiving data and transmitting it to my Garmin watch. 

Now the device is connecting automatically to the Noble Pro but it no longer seems to be picking up any data (e.g. I start the treadmill and it doesn't register the speed or distance).

At the same time, whenever I hit "start", it instantly pauses. 

Any ideas gratefully received. Could it have anything to do with the change in the Android version on Google play? I am using the Beta but timing of when you pushed the new version was very similar to when I lost functionality. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

[debug-Thu_Mar_21_20_42_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14712916/debug-Thu_Mar_21_20_42_28_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Set it as a ftms treadmill in the treadmill settings and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 mar 2024 alle 00:58 RoadRacer87 ***@***.***>
ha scritto:

**Comment by RoadRacer87** [comment]
This worked! Thanks!

________________________________

**Comment by cagnulein** [comment]
glad to hear this!
