### ISSUE TITLE
[BUG] QZ not showing speed or other information, only inclination

### ISSUE THREAD

**Issue by mccarthyp64** [cagnulein/qdomyos-zwift#2247]
**Describe the bug**
I previously couldn't get QZ to show any information from the Nordictrack S22i bike in use, but have now got it only showing inclination.

**To Reproduce**
1 Configure QZ for the IP of the bike

**Expected behavior**
Show all information available (speed and cadence at a minimum)

**Screenshots**
None at this time, although looking at the log shows that the app is picking up on the information from the bike but not displaying it

**Smartphone (please complete the following information):**
Samsung Tab 9+

**Debug Log**

https://mccarthyp64.com.au/debug-Fri_Mar_22_10_00_51_2024.log

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by mccarthyp64** [comment]
[Uploading debug-Fri_Mar_22_10_00_51_2024.log…]()

**Comment by cagnulein** [comment]
remove the ip from the nordictrack_2950_ip setting and press ok and put it instead on the tdf companion ip under the bike options, nordictrack bike settings.
also join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and update the app from the store.
Let me know!

**Comment by mccarthyp64** [comment]
I've done exactly that along with a complete reinstall to try and get the beta version, now the inclination isn't even showing.

https://mccarthyp64.com.au/debug-Tue_Mar_26_15_49_38_2024.log

**Comment by mccarthyp64** [comment]
I've finally gotten a debug log of starting a manual workout and then setting up a Fulgaz ride, I also think the app updated to the beta version. Speed was still zero, I'm not sure if Fulgaz should be able to send updates to inclination etc back through QZ to the bike or not.

Log is at https://mccarthyp64.com.au/debug-Fri_Apr_12_15_32_50_2024.log

**Comment by cagnulein** [comment]
hi @mccarthyp64 speed based on power setting is enabled under the bike settings? enable it and it will fix the speed issue.
Let me know!

**Comment by cagnulein** [comment]
Hi @mccarthyp64 any news?

**Comment by mccarthyp64** [comment]
I've been able to test a little more, the speed is now working however the connection to Fulgaz still isn't. I've tried connecting using the available Wahoo KICKR 0000 and HRM devices that seem to exist because of QZ with no success in feeding back to the bike. I also noticed the Strava option, but the inbuilt browser isn't allowed by Google SSO.

**Comment by cagnulein** [comment]
For strava simple toggle the strava Auth on the advanced settings . for fulgaz: are you using a separate device for it?

**Comment by mccarthyp64** [comment]
I'm trying to use QZ companion and Fulgaz on the same device (Samsung Galaxy Tab S9), the bike tablet is separate.

**Comment by cagnulein** [comment]
Fulgaz doesn't suporrt this. Only zwift does. You need 2 devices

**Comment by mccarthyp64** [comment]
Could I run QZ on the bike tablet and Fulgaz on the Samsung tablet or QZ on an iPhone and Fulgaz on the Samsung tablet?

**Comment by cagnulein** [comment]
Yes the iPhone plus Samsung tablet is fine

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 14 giu 2024 alle 05:33 mccarthyp64 ***@***.***>
ha scritto:

**Comment by mccarthyp64** [comment]
What should I look for on the tablet for Bluetooth once the iPhone is picking up on the bike data?

**Comment by cagnulein** [comment]
the iphone name

**Comment by mccarthyp64** [comment]
I got QZ working on the iPhone, then tried connecting the tablet to "QZ" via Bluetooth since the iPhone itself wasn't showing in the list otherwise, but the tablet needed wifi disabled to do Bluetooth tethering. Once this was done, Fulgaz immediately goes not responding until wifi is connected again.

**Comment by cagnulein** [comment]
why are you using bluetooth tethering?

**Comment by mccarthyp64** [comment]
When connecting to "QZ" via Bluetooth, that was the only option to connect properly otherwise it would sit there waiting as a previously paired and available device.

**Comment by cagnulein** [comment]
ok so you weren't talking about bluetooth tethering from the android settings, but of the QZ tethering, right? If it's so yes is fine. So at then end is working?

**Comment by mccarthyp64** [comment]
I've got a screen recording of what happens. If QZ is not running on the iPhone then the Samsung tablet will connect but obviously nothing useful happens. If the Samsung connects when QZ is running, [this](https://mccarthyp64.com.au/BluetoothTethering.mp4) is what happens.

**Comment by cagnulein** [comment]
you don't have to pair qz there. that menu is for headphone and similar. just use nrfconnect app if you want to see if you are able to connect

**Comment by mccarthyp64** [comment]
<img width="969" alt="Bluetooth scan tablet" src="https://github.com/user-attachments/assets/d11b7294-d01d-4868-a670-2de36ff69a57">
We see this list of devices when QZ is opened on the iPhone with Bluetooth on and nRF Connect is scanning, what should we be seeing?

**Comment by cagnulein** [comment]
a qz named device. you have to enable the virtual device setting in the experimental settings (it's enabled by default but maybe you changed it by mistake?)

**Comment by mccarthyp64** [comment]
Virtual device is turned on, this is what it looks like in Bluetooth settings
![Bluetooth settings devices](https://github.com/user-attachments/assets/b117bee9-bb43-415b-97c6-8303342cc9d8)

This is what it looks like via nRF Connect
![Bluetooth scan tablet](https://github.com/user-attachments/assets/9a0d50fb-ab5b-46da-87b0-bda9b76c44d2)

**Comment by cagnulein** [comment]
Also the virtual Bluetooth devices is enabled in the experimental settings?

It doesn't make any sense, nrfconnect should see as the Bluetooth android screen does.

do you have also another spare device to try with?

**Comment by mccarthyp64** [comment]
Could you please advise if the connection between QZ on the iPhone and the bike needs to be established when running this second scan or if the virtual Bluetooth device setting is all that's needed when scanning. For reference, the two previous scans were run while QZ on the iPhone was connected to the bike.

**Comment by cagnulein** [comment]
yes you need to first connect qz to the bike and then run the scan on the second device

**Comment by cagnulein** [comment]
@mccarthyp64 are we OK with this?
