### ISSUE TITLE
[BUG]No metrics while connected to echelon bike

### ISSUE THREAD

**Issue by Lovebankvictory** [cagnulein/qdomyos-zwift#2251]
[debug-Sat_Mar_23_11_23_41_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14733329/debug-Sat_Mar_23_11_23_41_2024.log)
[debug-Sat_Mar_23_11_39_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14733331/debug-Sat_Mar_23_11_39_44_2024.log)
[debug-Sat_Mar_23_11_40_29_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14733332/debug-Sat_Mar_23_11_40_29_2024.log)

I purchased the app 3 weeks ago and when it works, it is an amazing experience using it with my echelon bike and peloton app. 

The issue is one day, everything works and its great. The next day, the app connects to the bike and the peloton app/workout but nothing happens - none of the indicators/tiles work, neither does the auto resistance. Restarting all devices and apps doesn’t help either. The inconsistency is very frustrating.

And today, it everything worked fine for 10 minutes and then in the middle of my workout, it stopped working.

Debug log is attached

**Comment by cagnulein** [comment]
Hi 2 questions :
1) is it the same on the echelon app? It could be an hardware issue
2) do you see always the tiles even when they don't change?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 mar 2024 alle 19:59 Lovebankvictory <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@Lovebankvictory any news?
