### ISSUE TITLE
[REQ] Support for iConsole+ 0096 bike (FMTS?)

### ISSUE THREAD

**Issue by tomroyal** [cagnulein/qdomyos-zwift#2255]
I'm hoping you might be able to help me get QZ working with a spin bike using the iConsole+ 0096 bluetooth console.

The bike connects instantly, but readings are wild (6543km/h, 128000W).

I've tried:

* Disabling virtual device
* Enabling "Toorx/iConsole Bike

.. with no luck.

Log file attached. NRF Connect screenshots are here:

https://drive.google.com/drive/folders/15hxk9MRc95_bYC4cyHipJxIc_pa6JOPp?usp=sharing

Thank you!

Tom

**Additional context**

[debug-Tue_Mar_26_11_42_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14758100/debug-Tue_Mar_26_11_42_58_2024.log)
![IMG_1393](https://github.com/cagnulein/qdomyos-zwift/assets/2796645/9f130bf5-581e-48d3-83aa-7e25a28bb612)

**Comment by cagnulein** [comment]
hi @tomroyal enable the Toorx FTMS Bike setting under the iconsole setting and restart QZ.
Let me know!

**Comment by tomroyal** [comment]
Hi @cagnulein - thanks for the quick response as usual! 

Enabled the  "Toorx FTMS Bike", restarted the app. With that setting enabled the app does not establish a Bluetooth connection with the app, just keeps scanning.

**Comment by tomroyal** [comment]
Done! Thank you again.

**Comment by tomroyal** [comment]
Confirming here that in the Beta - 2.16 (774) this works perfectly. QZ reads Cadence and Resistance from the bike.

Just for anyone searching - this allows you to connect the JTX Studio v5 Bluetooth Connect+ spin bike using the Toorx FTMS Bike option.

@cagnulein - Thank you again. Let me know if you have a ko.fi or similar, I owe you a drink :)

**Comment by cagnulein** [comment]
amazing @tomroyal ! you can use https://buymeacoffee.com/cagnulein thanks!
