### ISSUE TITLE
[BUG] Auto Incline not working

### ISSUE THREAD

**Issue by dateranima** [cagnulein/qdomyos-zwift#2256]
Using a NordicTrack c1750.

have setup the correct instructed version of QZ using a Windows PC to connect to ADB.

everything connects fine when using Zwift and starts ok. Speed is captured correctly. However the incline % is incorrect. Always increases it too much.

I have reduced the gain by 0.5 and still over inclines.
[debug-Tue_Mar_26_12_11_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14759111/debug-Tue_Mar_26_12_11_48_2024.log)
[debug-Tue_Mar_26_12_11_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14759114/debug-Tue_Mar_26_12_11_48_2024.log)

**Comment by cagnulein** [comment]
just to understand @dateranima if you change the inclination with the inclination tile in qz, does it change correctly without zwift?

**Comment by dateranima** [comment]
I am unable to change the incline with the tile, only in the treadmill. I did another run and attach the log.
[debug-Thu_Mar_28_12_57_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14820823/debug-Thu_Mar_28_12_57_49_2024.log)
![IMG_0230](https://github.com/cagnulein/qdomyos-zwift/assets/165039896/eb3f0d80-b137-49fe-ad7f-ca40e8a85800)

**Comment by cagnulein** [comment]
ok qz on the phone is doing it correctly but probably the companion can't react. Question: when you press the plus button on the qz inclination tile, do you see ANY touch event on the ifit screen? check also these points https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike

let me know!

**Comment by dateranima** [comment]
OK, I have tried again, if it press the + repeatedly 3 or 4 times the incline will go up .5 If I press the - repeatedly the incline goes ‘up’ .5 

nothing happening I press the + or - for Speed.

**Comment by cagnulein** [comment]
i will check your case on monday. have a great weekend !

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 13 apr 2024 alle 17:56 dateranima ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@dateranima in the companion app the device is correctly set to C1750?

**Comment by dateranima** [comment]
On the app on the treadmill C1750 is selected, on the app on the phone there is no option for C1750, but I have the IP Address configured.

**Comment by cagnulein** [comment]
@dateranima OK, so it means that your tablet is different from the one that I implemented. Are you able to run https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat from the install package folder so I will implement the coordinates of your sliders on your tablet. Let me know.

**Comment by dateranima** [comment]
![14-04-2024@17-48-30 20](https://github.com/cagnulein/qdomyos-zwift/assets/165039896/87b5bfac-af45-4a8b-aa31-0d04d668abc1)

**Comment by dateranima** [comment]
I have run that bat file and uploaded the png for you now.

**Comment by cagnulein** [comment]
perfect, i will check it tomorrow

**Comment by dateranima** [comment]
Hi, no I did not. What is the latest version of c1750? Mine is a 2023 version.

**Comment by cagnulein** [comment]
> Hi, no I did not. What is the latest version of c1750? Mine is a 2023 version.

i don't know but it's faster to test this and in case if it still doesn't work i will implement it using the 2023 tag for you.
Let me know!

**Comment by cagnulein** [comment]
@dateranima any news?
