### ISSUE TITLE
Classes Without Metrics are Not Showing Class Title in QZ

### ISSUE THREAD

**Issue by PugMamma** [cagnulein/qdomyos-zwift#2258]
I noticed recently older Peloton tread classes (that don't have target metrics) and live classes are not showing the class name in QZ. I know there is no metrics for QZ to pull from for these, but I would at least get the class name and photo in Strava/email. I did a live Walk today and since QZ didn't see the Peloton class it sent it to Strava as a Virtual run. 

![Screenshot_20240326-160440](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/6e4c8e41-9e08-49e4-8688-4d7ca0b5a4bc)
[debug-Tue_Mar_26_15_58_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14765571/debug-Tue_Mar_26_15_58_05_2024.log)

**Comment by cagnulein** [comment]
got the issue, (note for me: all the apis returns 0 train rows length).
the fix could be counter intuitive beucase I should popup the screen to follow the peloton workout but actually there is no workout to follow from the peloton api. What do you suggest?

**Comment by PugMamma** [comment]
I just know it used to have the class title for live classes, so wasn't sure what changed? QZ is connected to the Peloton login, so can't it recognize when doing a class, regardless of metrics being present?

**Comment by cagnulein** [comment]
hah ok! i got why it doesn't work anymore, it's about this one https://github.com/cagnulein/qdomyos-zwift/issues/2158
Long story short: the OP said that the peloton class name was overwritten from the one that the other user was playing. So I put the workout name under the peloton popup request (and he had right IMHO)  so now, since these workouts don't have metrics, the popups doesn't appear.

@BarristQL what do you think about this case too? I would like to have a solution that satisify everybody.

The only thing that could be a solution is asking to follow a peloton class even if the peloton apis doesn't have metrics at all (maybe showing also this on the popup? )

What do you think @PugMamma  ?

**Comment by PugMamma** [comment]
Is that why the class date doesn't show up in the title anymore either?

**Comment by cagnulein** [comment]
yes @PugMamma that's the reason, i mean that's the reason for the classes that don't have metrics from peloton. the ones that have them and you see the popup, the title should get the right value. can you confirm me this?

**Comment by PugMamma** [comment]
The class title is correct, but the date used to show be included in the name. 
Class from yesterday: 
![434184960_313839438382637_9188235211585350463_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/f0028ebc-de9c-4ae0-bdc2-01c33f7b3bab)
Class from March 12th:
![434168021_730549252621831_4985546157119632386_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/941add80-0b4f-4880-b238-000a3b2340c8)

**Comment by cagnulein** [comment]
argh, no that's a bug and this is about to the https://github.com/cagnulein/qdomyos-zwift/issues/2158 
ok fixed now. it will be in the 2.16.50 thanks for the feedback.

what about the name instead for the class that doesn't have metrics?

**Comment by PugMamma** [comment]
Can classes without metrics not have the name pulled from Peloton? The live class I did yesterday was just called 'Run - #QZ' in Strava until I manually renamed it to match the Peloton class I took.

**Comment by cagnulein** [comment]
> Can classes without metrics not have the name pulled from Peloton? The live class I did yesterday was just called 'Run - #QZ' in Strava until I manually renamed it to match the Peloton class I took.

yes it's the same issue that you had for the walk run. the counter effect of the #2158 is that classes without metrics don't have the name now on strava or in the top qz label. so for sure it's something that i have to fix.

The only question is "how"? I mean I would like to keep the compatibility with the #2158 but I don't want to break the compatibility with the naming that the users used to have.

I guess adding the popup is the only solution. thoughts? @PugMamma  @BarristQL

**Comment by PugMamma** [comment]
Besides the name, the live classes get categorized as 'run', 'walk' or 'rowing' class vs without the Peloton tie in, it comes into Strava as a Virtual class. 
I'm fine with a pop up, really whatever can satisfy the users and be an easier solution.

**Comment by cagnulein** [comment]
> Besides the name, the live classes used to get categorized as 'run', 'walk' or 'rowing' class vs without the Peloton tie in, it comes into Strava as a Virtual class.

yes same issue unfortunately. I didn't think about this use case when I did the modification. Unfortunately without having peloton on myself it's really hard to find these cases. Thanks again, i'm adding the popup so!

**Comment by cagnulein** [comment]
done! i will build it today (2.16.50)

**Comment by PugMamma** [comment]
Thank you!

**Comment by cagnulein** [comment]
Version live!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 27 mar 2024 alle 16:02 PugMamma ***@***.***> ha
scritto:

**Comment by PugMamma** [comment]
I finally had the chance to take a live class since the new version went live. The email has the class link, but the title is Row/Run, etc. There was no pop up when I took the live class (unsure if there should be?). 

![432965761_338359285400127_3328933369011528415_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/2a95a919-7844-491e-95be-c582b2259ea3)

![432842889_7344806418940077_8301383021088514550_n](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/4e24b1e8-a8dd-419d-9b3b-c02dc11b50e9)

![QZ Email](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/94a44035-d93c-4f12-9a29-917b731ab291)

**Comment by cagnulein** [comment]
argh, yes you should be able to see the popup. do you have the debug log of this? thanks

**Comment by PugMamma** [comment]
[Uploading debug-Mon_Apr_1_16_28_55_2024.log…]()

**Comment by cagnulein** [comment]
hi @PugMamma thanks but you have to wait the finish of the upload before clicking comment. thanks otherwise the file is corrupted

**Comment by cagnulein** [comment]
ok i guess i understood the issue anyway. I'm pushing the 2.16.51
If you have the debug log I will check it anyway
Let me know when you will try the 2.16.51
Thanks @PugMamma

**Comment by PugMamma** [comment]
[debug-Mon_Apr_1_16_28_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14837853/debug-Mon_Apr_1_16_28_55_2024.log)

**Comment by cagnulein** [comment]
perfect @PugMamma so my fix from today was right. You will see the new version soon! (just uploaded to google)

**Comment by cagnulein** [comment]
@PugMamma update is live. Fingers crossed!

**Comment by PugMamma** [comment]
Took a live class this morning and everything worked! 
![Screenshot_20240405-072730](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/f0eaf433-bdd1-41f3-b26d-ccaa2a5f6cbd)
![Screenshot_20240405_075307_Strava](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/15956d50-2ccb-42b7-af2e-b7e96225ac79)

**Comment by cagnulein** [comment]
finally! thanks so much for the feedback!

**Comment by PugMamma** [comment]
The June 21st log was from my parents treadmill and the metrics showed up in Peloton.
The June 23rd log was from my Horizon treadmill. Peloton found and connected to QZ, but no metrics showed up in Peloton. 
[drive-download-20240624T165327Z-001.zip](https://github.com/user-attachments/files/15958966/drive-download-20240624T165327Z-001.zip)

**Comment by cagnulein** [comment]
@PugMamma Can you try to disable for a quick test the zwift run pod from the settings?
Let me know

**Comment by PugMamma** [comment]
You are amazing! Thank you so much! 
![Screenshot_20240625_093219_Peloton](https://github.com/cagnulein/qdomyos-zwift/assets/91086001/afeb6773-4210-4b4a-b47e-0a846c7e8086)

**Comment by cagnulein** [comment]
probably was my fault since during our experiment i told to enable it :)
