### ISSUE TITLE
Suggestion: PID support for speed / inclination based on HR

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#226]
I would like to suggest a function that gives the user the possibility to use a PID controller to control speed and inclination on the treadmill to force the HR into a certain zone. I don't know if PID software is difficult to incorporate but I know there are some available on GitHub: https://github.com/pms67/PID, https://github.com/geekfactory/PID. I think the biggest difficulty will be to have 2 variables to control (speed and inclination) in stead of one.

This would give a whole new way to do interval training on a threadmill that no other app offers (as far as I know).

An example of a training program would be:

[PID Example.xml.txt](https://github.com/cagnulein/qdomyos-zwift/files/6227343/PID.Example.xml.txt)

The offset is used to randomize training times to prevent the body getting used to the same training pattern.
Maybe other randomization options could be used.

The HR zones would be (according to Polar):

Zone | Intensity | Percentage of HRmax
-- | -- | --
Zone 1 | Very light | 50–60%
Zone 2 | Light | 60–70%
Zone 3 | Moderate | 70–80%
Zone 4 | Hard | 80–90%
Zone 5 | Maximum | 90–100%

**Comment by cagnulein** [comment]
wow! amazing!
yeah i'm familiar with PID in the automation environment.
right now i don't have the time to develop it, but it sounds a great idea!
And also we can do the same for the bike with the controlled resistance (it
should be easier i guess because we have just one set point instead of two)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 30 mar 2021 alle ore 08:44 ErnieV ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
2 days ago i tried it statically (pressing + and - following my heart rate) and i guess a simple checking every 10 seconds should works for starting.

I mean something simple like

if heart is under the zone
  speed + 0.2
elseif heart is over the zone
  speed - 0.2

i will try to create something during this week because i wanna really try it out!

**Comment by ErnieV** [comment]
Do you think that would work? Will it react quickly enough? I am eager to try it out!
It is a really simple PID implementation like that, maybe it will work.

It would be nice to try it out in combination with the random training program, letting the treadmill change the inclination (or bike resistance) randomly every 60 seconds. This function should then overrule the random speed setting in some way to keep user within defined heart zone (or does using random training overrule xml input?).

I saw that the heart rate zones are already configurable in the app, do you calculate the MaxHeartRate based on settings in General Options? Wouldn't it be an option to let user define / override MaxHeartRate?

Good luck with the implementation! I look forward to testing it!

**Comment by cagnulein** [comment]
heart rate is not so quick to change, so i guess, after a ramp period, it will work fine. I mean not for an interval workout, but for a long run (steady heart rate), i guess it will work. For an interval we should just reduce the checking time from 10s idk to 1 second.

Random + PID = madness! No i don't think they can work together...2 brains will never come to a great decision :)

I calculated the max heart rate based on age, i can add a new parameter to override it

**Comment by cagnulein** [comment]
done, i did a quick test and i works great! when you're in the zone you're able to adjust speed and inclination if you're not happy with it.

This evening i will try it on a hour session and i will post you the strava activity :)

**Comment by ErnieV** [comment]
Nice! I hope to test it soon! I don’t know when it will be in Beta, I will be on holiday the next week.

I will see the Strava activity when it comes online also. Good luck on your run this evening!

Met vriendelijke groet, 

Erwin Velthuis 
Business Intelligence Consultant 
Unity BI

M: 06-48268343 
E: ***@***.***

**Comment by cagnulein** [comment]
today i will do another session with closing the loop every 10 seconds and i will run in zone 3. let's see if will suicide myself into the wall behind the treadmill :D

**Comment by cagnulein** [comment]
@ErnieV it works amazing!! i had one my best workout!! check strava! now it's time to add some argument to the xml as you suggested :)

**Comment by ErnieV** [comment]
Very nice! Good to hear you didn’t end up on the wall!! I am eager to test it myself!
Have you decided yet what parameters are configurable by the user? Looptime? Zone? As you said, it has to be a safe option to use, too short looptimes may cause strange behaviors...

Let me know when I can test it in iOS beta on domyos threatmill. I will also test domyos bike if you like.

Regards,
Erwin Velthuis

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
i guess i will use
maxspeed (optional), looptime (default 10) and of course hrzone

**Comment by ErnieV** [comment]
In addition to existing parameters? Fanspeed? Inclination? Duration?

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
yes of course in addition

**Comment by cagnulein** [comment]
done! it works! i tested the xml that i put in the example folder here on github!
i implemented for bike too (not tested)
tomorrow i will build it for ios, ok?

**Comment by ErnieV** [comment]
Nice! How does the app know the difference between regular or PID file? And is inclination still an (optional) xml tag? I didn’t see it in the example file.

Maybe we should get a few more people testing it in Beta? Just to be sure no strange behaviors appear? When I get back from holiday I could write a simple guide on how to use this and ask a few in the Strava group to help test it?

Very nice job indeed! Congrats!

Regards,
Erwin

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
Simply if i saw the zonehr tag i Will follow the hr, anyway i don't ;)
Yes inclination is still there, i just forgot to put it in the example :D

Yes just do a quick test you too and then will share with the others :)

Yes strava users could be a great start ;)

Il mar 27 apr 2021, 21:32 ErnieV ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Send me your email to roberto.viola83@gmail.com and i will add to ios beta tester

**Comment by ErnieV** [comment]
I am already beta testing. I started with the xml fanspeed idea. :)

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
yes but i would like to send it only to you right now :)
i don't remember your email :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 apr 2021 alle ore 14:03 ErnieV ***@***.***>
ha scritto:

**Comment by ErnieV** [comment]
Ah! Didn’t know you could do that! ***@***.***

Thank you!

Verstuurd vanaf mijn iPhone

**Comment by cagnulein** [comment]
GitHub filter it send it to my mail or messenger

Il mer 28 apr 2021, 18:26 ErnieV ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@ErnieV did you try it?

**Comment by ErnieV** [comment]
Feature is perfect! Thank you very much!
