### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MeKy28** [cagnulein/qdomyos-zwift#2261]
[debug-Thu_Mar_28_18_48_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14793713/debug-Thu_Mar_28_18_48_38_2024.log)
**Describe the bug**
Qz connects with my treadmill on android. Zwift on PC doesn't find QZ app (not on connect thru phone or connect thru bluetooth)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
 - windows 11

**Smartphone (please complete the following information):**
 - Device: OnePlus 10
 - OS: Android 13

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
You have the fake treadmill setting enabled, turn it off and let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 mar 2024 alle 19:04 MeKy28 ***@***.***> ha
scritto:

**Comment by MeKy28** [comment]
[debug-Thu_Mar_28_19_38_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14794171/debug-Thu_Mar_28_19_38_44_2024.log)

I've turned off the fake treadmill but my laptop still doesn't find the QZ app. 
When I select connect with bluetooth only my phone "oneplus" shows up...
Selecting the Oneplus as source doesn't make my avatar move...

**Comment by cagnulein** [comment]
enable the dircon in the experimental settings then you will see the wahoo
device on windows

also if it doesn't work rename your phone to "run" and reboot it

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 mar 2024 alle 19:47 MeKy28 ***@***.***> ha
scritto:

**Comment by MeKy28** [comment]
Thx Roberto,

Enabeling the Wahoo did it for me!

**Comment by cagnulein** [comment]
Glad it worked!


Il giorno gio 28 mar 2024 alle 20:04 MeKy28 ***@***.***> ha
scritto:
