### ISSUE TITLE
Connection with Garmin Watch [BUG]

### ISSUE THREAD

**Issue by 4lternative** [cagnulein/qdomyos-zwift#2263]
**Describe the bug**
Hi, coming from facebook : https://www.facebook.com/groups/149984563348738/posts/784548163225705/

So I've tried it again launching only an activity on my watch. I get cadence, but that's it, no distance or speed on the watch. Though, apparently on garmin connect I get a sliver of speed (see attached image). 

Should I need to push 'start' on the QZ phone app, or just on the watch? On the log I'm sending you, I did push start after starting the activity on the watch, just so you know. 

**To Reproduce**
Launching QZ phone app
Launching "Indoor Bike" activity on watch

[debug-Mon_Apr_1_20_28_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14827375/debug-Mon_Apr_1_20_28_45_2024.log)
![garmin connect report](https://github.com/cagnulein/qdomyos-zwift/assets/19288260/828d56a0-fc8e-4740-b25d-48ff7d1aab9e)

![watch](https://github.com/cagnulein/qdomyos-zwift/assets/19288260/35e99295-2a4d-44ab-8889-2e881cb0697d)

Phone is Samsung Galaxy S10+  on Android 12
Watch is Garmin Fenix 7X solar; in the sensor I get: 
  - PWR
  - Spd/Cad
Bike is Domyos e fold 6

Let me know if you need anything else to debug it further, if you need a longer log or whatever! 

Thanks
Christophe

**Comment by cagnulein** [comment]
I will check the log tomorrow, what I can say as reported from another user on Facebook last week, is that the fact that the phone has ant+ could be not enough to send speed to.a garmin ant+ dongle fixed this for the other user

**Comment by cagnulein** [comment]
log is fine from qz, so qz is doing everything in the right way. which wheel diamater did you set on the watch? this could be the issue too

**Comment by 4lternative** [comment]
Sorry for my late reply, so I just restested it biking for 10mn, qz is getting the distance and speed right, but the garmin watch is getting random speed and distance. I'm sharing you the log has it's longer than last time just in case; and a picture of the garmin app showing it picking speed near the end for few second, and a wrong distance. 

If you still can't find anything I'll try with a newer smartphone, and maybe a ant dongle. 

Thanks

**Comment by 4lternative** [comment]
[debug-Thu_Apr_11_18_07_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14948799/debug-Thu_Apr_11_18_07_57_2024.log)
![Screenshot 2024-04-11 182908](https://github.com/cagnulein/qdomyos-zwift/assets/19288260/2f810080-3527-4610-a254-13edc1826e34)

**Comment by cagnulein** [comment]
Did you set the wheel diameter to 100 mm?

**Comment by 4lternative** [comment]
sorry, yes I did set it to 100mm for the Spd/cad  sensor in the watch

**Comment by cagnulein** [comment]
it could be an ant dongle issue so

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 18:31 4lternative ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@4lternative any news?

**Comment by 4lternative** [comment]
Hey, sorry for not replying before, I can't say, I haven't got the time to look into an ant+ dongle, so until then can't really add anything new

**Comment by cagnulein** [comment]
ok let me know in case

**Comment by 4lternative** [comment]
I will!

**Comment by 4lternative** [comment]
Hi Roberto, 

Just got back to riding my indoor bike again, somehow it just work now, I don't know if you made an update. I didn't change anything same phone, same watch, I'm lauching qz app, then starting the indoor bike activity and my watch and it works great, I get the distance, and pace like it supposed to. Just wanted to let you know.

Cheers

**Comment by cagnulein** [comment]
Awesome, thanks for the update!


Il giorno sab 27 lug 2024 alle 18:11 4lternative ***@***.***>
ha scritto:
