### ISSUE TITLE
[BUG]Domyos EL 520 elliptical autoresistance not working

### ISSUE THREAD

**Issue by josetta** [cagnulein/qdomyos-zwift#2268]
**Describe the bug**
I have elliptical Domyos EL 520, in kinomap, I can connect, but autoresistance is not working. We were fixing this issue in #1252 , it worked then, but now, it is not working. I am connecting elliptical as threadmill, because as elliptical, there are not going any data, even when kinomap sees it.

**To Reproduce**
Steps to reproduce the behavior as threadmill:
1. Start QD-Z
2. Turn on elliptical
3. Turn on Kinomap
4. Connect as FTMS threadmill
5. Run workout
6. Resistance is not changing by incline change

Steps to reproduce the behavior as elliptical:
1. Start QD-Z
2. Turn on elliptical
3. Turn on kinomap
4. Try to connect as FTMS elliptical
5. Kinomap infomrs you, that it is not getting any data from elliptical after you connect it

**Expected behavior**
Threadmill: when inlcine is changing, it should raise resistance
Elliptical: it should read data from elliptical

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RaspberryOS
 - Version 11

**Append a debug log**
[logs.zip](https://github.com/cagnulein/qdomyos-zwift/files/14838062/logs.zip)
First log is workout threadmill, second is trying to connect as  elliptical

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
hi @josetta i don't see any request from Kinomap in these logs. I guess it's a kinomap bug

**Comment by josetta** [comment]
First log it measured workout as threadmill, but only autoresistance didn't work (so I was changing resistance manually), second log is when I tried to connect as elliptical to kinomap. I added other logs from today, maybe I added wrong logs :)
[logs.zip](https://github.com/cagnulein/qdomyos-zwift/files/14839147/logs.zip)

**Comment by cagnulein** [comment]
check also these. indeed in the debug-ut_apr_2_14_37_39_2024.log there are 4 inclination requests but they are all 0.
maybe do you want to do a fresh log?

**Comment by josetta** [comment]
Will send fresh logs, but I am not able now :)

**Comment by cagnulein** [comment]
@josetta any news?
