### ISSUE TITLE
[BUG] Connection Drop x3 in Race

### ISSUE THREAD

**Issue by elfonashelfna** [cagnulein/qdomyos-zwift#2271]
Nothing really to explain other than connection dropped 4 times… happened during a race, costed me first place. Any certain reason in debug log? Discord was open as well to be communicate with team!
[debug-Tue_Apr_2_20_33_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845516/debug-Tue_Apr_2_20_33_11_2024.log)
[debug-Tue_Apr_2_20_53_33_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845517/debug-Tue_Apr_2_20_53_33_2024.log)
[debug-Tue_Apr_2_21_14_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845518/debug-Tue_Apr_2_21_14_03_2024.log)
[debug-Tue_Apr_2_20_53_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845519/debug-Tue_Apr_2_20_53_35_2024.log)
[debug-Tue_Apr_2_20_53_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845520/debug-Tue_Apr_2_20_53_39_2024.log)
[debug-Tue_Apr_2_20_12_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845522/debug-Tue_Apr_2_20_12_55_2024.log)
[debug-Tue_Apr_2_20_53_38_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845525/debug-Tue_Apr_2_20_53_38_2024.log)
[debug-Tue_Apr_2_20_33_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845526/debug-Tue_Apr_2_20_33_03_2024.log)
[debug-Tue_Apr_2_21_13_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845527/debug-Tue_Apr_2_21_13_51_2024.log)
[debug-Tue_Apr_2_21_14_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845528/debug-Tue_Apr_2_21_14_00_2024.log)
[debug-Tue_Apr_2_20_33_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845529/debug-Tue_Apr_2_20_33_10_2024.log)
[debug-Tue_Apr_2_21_14_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845530/debug-Tue_Apr_2_21_14_02_2024.log)
[debug-Tue_Apr_2_21_14_04_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845531/debug-Tue_Apr_2_21_14_04_2024.log)
[debug-Tue_Apr_2_20_53_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845532/debug-Tue_Apr_2_20_53_28_2024.log)
[debug-Tue_Apr_2_21_14_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845533/debug-Tue_Apr_2_21_14_34_2024.log)
[debug-Tue_Apr_2_21_14_01_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845535/debug-Tue_Apr_2_21_14_01_2024.log)
[debug-Tue_Apr_2_21_13_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845536/debug-Tue_Apr_2_21_13_54_2024.log)
[debug-Tue_Apr_2_21_13_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845537/debug-Tue_Apr_2_21_13_55_2024.log)
[debug-Tue_Apr_2_21_13_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845538/debug-Tue_Apr_2_21_13_58_2024.log)
[debug-Tue_Apr_2_20_33_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845539/debug-Tue_Apr_2_20_33_02_2024.log)
[debug-Tue_Apr_2_20_11_32_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845540/debug-Tue_Apr_2_20_11_32_2024.log)
[debug-Tue_Apr_2_21_13_48_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845541/debug-Tue_Apr_2_21_13_48_2024.log)
[debug-Tue_Apr_2_21_13_50_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14845542/debug-Tue_Apr_2_21_13_50_2024.log)

**Comment by cagnulein** [comment]
Hi dropped from where? the bike? or zwift? are you using the wahoo virtual sensor from qz? where zwift runs?

**Comment by elfonashelfna** [comment]
All settings are default on the app; connection dropped because iOS app would crash and when you’d try to open the app soon right after, it would keep closing when trying to open it. Finally after 30 seconds, it would let you open the app and continue on reconnecting it in Zwift Bluetooth settings.

**Comment by cagnulein** [comment]
ok so this is an issue with the wifi. these bike are famous to be very problematic with the wifi side. you have to be very near to the router with this bike

**Comment by elfonashelfna** [comment]
Fortunately the bike is about 2 feet away from the modem/router (in the same room). It’s not the WiFi that’s dropping it’s the app that is crashing on iOS for some reason.. I’m not sure! As soon as the app crashes and you try to open it right back up, it crashes again. Over. Over. Over. Over. Then after a few seconds it lets you open it back up.

**Comment by cagnulein** [comment]
@elfonashelfna the problem is the wifi of the bike

`Tue Apr 2 20:53:20 2024 1712105600513 Debug: /Users/cagnulein/qdomyos-zwift/src/proformwifibike.cpp auto proformwifibike::proformwifibike(bool, bool, uint8_t, double)::(anonymous class)::operator()() const disconnected!`

there are plenty of this in the logs, so the wifi of the bike is not working correctly. maybe you can try to disable the wifi 5g and leaving only the 2.4g (usually it helps).

Anyway you can see also with a ping to your bike, i guess you will see the same behaviour from the ping

let me know!

**Comment by cagnulein** [comment]
@elfonashelfna any news?
