### ISSUE TITLE
NordicTrack s15i bike

### ISSUE THREAD

**Issue by Stiluats** [cagnulein/qdomyos-zwift#2277]
**Describe the bug*
I have a NordicTrack s15i bike. I have followed instructions to include:
-Factory resetting bike
-Enabling privilege mode
-Enabling debugging mode
-Installing qz companion on bike via bike browser ([tinyurl.com/qz-companion](http://tinyurl.com/qz-companion))
-Install qz app on iPad
-Entered bike IP address under TDF companion IP
-Enabled virtual device, virtual device Bluetooth and wahoo direct connect

When starting manual workout on bike, no data is transmitted to qz app. It continuously says connecting under pause/stop buttons but never connects to bike. Interestingly when I downloaded Zwift on iPad it says that it is connected to  Wahoo KICKR 0000 33 for power, resistance and cadence but does not display any data while spinning. I also tried downloading qz app to iPhone and tried to use that instead of iPad with same outcome. Bike bluetooth is turned on and when looking at available devices there is a ‘Qz’ listed but even after pairing this manually on bike no data transmits to Qz app. Any ideas on this connectivity issue?

Thanks for your time,

**To Reproduce**

**Expected behavior**
Bike Qz companion to communicate with iPad or phone Qz app

**Screenshots**
![IMG_7396](https://github.com/cagnulein/qdomyos-zwift/assets/166069499/cd797471-30c8-446a-aa33-4c383faec632)

**Desktop (please complete the following information):iPad 4th gen. iOS 17.3.1

**Smartphone (please complete the following information):iPhone 15 ios 17.3.1

**Append a debug log**
[debug-Thu_Apr_4_12_32_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14877203/debug-Thu_Apr_4_12_32_53_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Stiluats the problem is that the phone is not receiving the frames at all from the bike. I already see something similar on some ios devices. It could be the router that it's filtering it. Do you have a PC or a Mac as well? If it's a mac silicon you can try to download QZ as well there and try there.

Let me know!

**Comment by Stiluats** [comment]
Hey Roberto,
I do have a Mac but unfortunately it’s an older model and not silicon. Could you please elaborate on a router filtering issue and how I can look into that more as a possible cause?

Thanks,
-Alex

On Apr 4, 2024, at 22:31, Roberto Viola ***@***.***> wrote:

﻿

hi @Stiluats<https://github.com/Stiluats> the problem is that the phone is not receiving the frames at all from the bike. I already see something similar on some ios devices. It could be the router that it's filtering it. Do you have a PC or a Mac as well? If it's a mac silicon you can try to download QZ as well there and try there.

Let me know!

**Comment by cagnulein** [comment]
packet filtering is something that you have to find on the router,
unfortunately every router is different so i can't guide you directly. qz
companion is sending broadcast udp frames.
you can check if you can see something about this on the router

another workaround will be using your phone as an hotspot for the treadmill

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 apr 2024 alle 23:22 Stiluats ***@***.***> ha
scritto:

> Hey Roberto,
> I do have a Mac but unfortunately it’s an older model and not silicon.
> Could you please elaborate on a router filtering issue and how I can look
> into that more as a possible cause?
>
> Thanks,
> -Alex
>

**Comment by cagnulein** [comment]
@Stiluats any news?
