### ISSUE TITLE
Horizon t202 Zwift no auto incline [BUG]

### ISSUE THREAD

**Issue by redsted** [cagnulein/qdomyos-zwift#2278]
**Describe the bug**
Horizon t202 treadmill does not auto in line based off Zwift climb data

**To Reproduce**
1. Open qz and connect to treadmill (force ftms is enabled under horizon setting)
2. Start Zwift in hilly climb and the reverse to start running up the hill

**Expected behavior**
Going up hill should result in treadmill increasing incline

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung s21
 - OS: android 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[inbound9110494464605492523.txt](https://github.com/cagnulein/qdomyos-zwift/files/14892752/inbound9110494464605492523.txt)
[inbound8627629780972418330.txt](https://github.com/cagnulein/qdomyos-zwift/files/14892753/inbound8627629780972418330.txt)
[inbound5399367850874862935.txt](https://github.com/cagnulein/qdomyos-zwift/files/14892754/inbound5399367850874862935.txt)
[inbound8798989839841850007.txt](https://github.com/cagnulein/qdomyos-zwift/files/14892755/inbound8798989839841850007.txt)
[Uploading inbound7487169412516226408.txt…]()

**Comment by cagnulein** [comment]
@redsted first of all you need to fill the zwift username and password in the qz settings. also are the plus and minus buttons of the inclination tile in qz working to change the inclination manually?

Let me know

**Comment by redsted** [comment]
The app + and - does not appear to control the inclination. If I set the
max inclination to 12 then the + button will work but will jump all the way
to 12, not in 0.5 increments

**Comment by redsted** [comment]
Sorry, I had the mon and max around the wrong way. I have now set max to 12
and min to 0. I have added username and PW in to Zwift section and
inclination is now working. However in Zwift a 3% incline is setting 6 on
the treadmill, would this be correct?

**Comment by cagnulein** [comment]
great! just set the zwift inclination gain to 0.5 and you are good to go!

**Comment by redsted** [comment]
Hi Roberto, it still seems to be doubling the translation of the incline.
2% in game is 4% on the treadmill.

**Comment by cagnulein** [comment]
Are you sure you changed the right setting and pressed OK? Show me a fresh
debug log in this scenario and I will check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 apr 2024 alle 00:59 Adam ***@***.***> ha
scritto:

> Hi Roberto, it still seems to be doubling the translation of the incline.
> 2% in game is 4% on the treadmill.
>

**Comment by cagnulein** [comment]
@redsted any news?
