### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Drivelines** [cagnulein/qdomyos-zwift#2283]
[debug-Mon_Apr_8_10_26_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14909768/debug-Mon_Apr_8_10_26_09_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Drivelines the fact that the guy on zwift is not moving it's because you have to set the heart rate belt name here 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/0711ca5a-4122-45a8-b81b-753b7b1a1ce4)

do you have a heart rate device?

**Comment by cagnulein** [comment]
apple watch is perfect: so leave this setting to disabled and simply start
the qz app on the watch too and press start there too
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 apr 2024 alle 20:36 Drivelines ***@***.***>
ha scritto:

**Comment by Drivelines** [comment]
I have an Oura ring and an Iwatch

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by Drivelines** [comment]
Now QZ is not connecting 
Do I need to go in and turn off the de bug first?

**Comment by Drivelines** [comment]
Ok it hooked up
Have power source 
resistance
Cadence
And heart rate all connected
But QZ still doesn’t show speed and of course my dude is not moving

**Comment by cagnulein** [comment]
do you see hr and power on qz? is the play button flashing red? if so you have to press it

**Comment by Drivelines** [comment]
Pushed the red flashing button
Only see the wahoo cadence 
Speed and heart box not working 

![IMG_1905](https://github.com/cagnulein/qdomyos-zwift/assets/166435905/51693178-3af2-4ac2-b020-6fc7a7a2ff57)

**Comment by cagnulein** [comment]
do you see hr on the qz app on the watch?

**Comment by Drivelines** [comment]
qz on apple watch shows
Heart Rate
0 STEP CAD
Calories
Distance
and then you can scroll to highlight Bike

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
did you press start there? did you allow ALL the permissions on apple
health for qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 apr 2024 alle 21:10 Drivelines ***@***.***>
ha scritto:

**Comment by Drivelines** [comment]
Yeeee Haw!!!
Whos The Man....

You did it, all working!!!

What is the.   -   +.  box   in the speed box for?



          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by Drivelines** [comment]
Got it.

Last question...  Promise.  : )

This is on my less expensive Poo Boo bike at the shop.
So I can get another set of Wahoo Cadence and Speed sensors,
put them on the Pelaton at home, and then be able to easily,
hook up via QZ at either location, with no issues?




          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
yes sure! just need to set the right cadence sensor. you can also save profiles so you can switch between them quickly

**Comment by Drivelines** [comment]
Excellent.

Thank You Very Much!!

You are Amazing!!!

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by Drivelines** [comment]
Here you go
I hope🤠

**Comment by cagnulein** [comment]
i guess you forgot to attach it :)

**Comment by Drivelines** [comment]
Ahhh
I can't figure out now how to attach the bug file

**Comment by cagnulein** [comment]
send me by email if it's better for you :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 10 apr 2024 alle 20:08 Drivelines ***@***.***>
ha scritto:

**Comment by Drivelines** [comment]
Ok...  I think I got it???
Let me know

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
yes ! i guess i already fixed it! i sent you a newer version by email on test flight!

let me know

**Comment by Drivelines** [comment]
Will i need to open test flight on my phone to get the new version?

I see something on my lap from the first test flight....  not sure if that
is the newer vision or not.
It is in my menu bar.

Also I am more than willing to buy it again...   if it is easier to just
delete the one i have and get another one.
(Some times my ***@***.***   does not forward my emails properly.)

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by Drivelines** [comment]
Ok,
I deleted the app.
Reinstalled it, reset all the fields.
And...   all seems to be working fine.
I will be doing an hour ride tonight and let you know,
how it goes.

Thanks!

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by Drivelines** [comment]
finishes me ride.
My dude is responding all is good.
Only hiccup is that he does not go as fast as I go.
Which is no big deal except if someone passes me and i
want to try to catch up...  QZ shows me at 35 plus...  and Zwift
I am lucky to get anything over 20 no matter how fast I pedal.

So, I will take it...  but if you ever come across a sensor that may work
better than Wahoo with your app.   Let me know.

And second...  if you are ever anywhere in the states... Let me know.
I will get you a gift card to have a few meals on me

Have a Great Day

Smile,
Wade King

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
for the speed, you can use the watt gain setting if you want to increase it, but it could be cheating...

**Comment by Drivelines** [comment]
I wouldnt do that, Just would be better if
the avatar could speed up as I do...  but that is ok

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
qz is using the hr to determine the wattage, so when you speed up also the hr should increase, isn't it?

**Comment by Drivelines** [comment]
I think so, I will check it on tonights ride and let you know

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
If so you just need to increase the force with qz is changing it with the
watt gain

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 apr 2024 alle 20:50 Drivelines ***@***.***>
ha scritto:

**Comment by Drivelines** [comment]
Howdy,
Ok,I have my second set of Wahoo sensors on my bike at my house.
The QZ is showing that it recognizes it...  but it wont pair up.

Any suggestions.

          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
did you set it in the cadence sensor setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 apr 2024 alle 22:12 Drivelines ***@***.***>
ha scritto:

**Comment by Drivelines** [comment]
Not sure what you mean


Smile, Wade

**Comment by Drivelines** [comment]
Installed the second set of Wahoo sensors on the other bike.
started peddling the bike to active the sensors....
turned on the heart app with the QZ on my iwatch
turned on the QZ ap
QZ app shows in the flashing display...  the wahoo cadence, speed, my phone
connection...
but will not hook up


          *                       drivelinesinc.com
<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdrivelinesinc.com&data=02%7C01%7Cdwatson%40neapco.com%7Cde5761d94cfd49f6c9cd08d7154af0bb%7C58a01d8fc85948f4a09545630daba5de%7C0%7C0%7C637001283933924284&sdata=oPxlJQ5YRGR%2BPwYp5g5dCwHV2vdYm519lbj4rcmMsuM%3D&reserved=0>*

*                                     makiwara.com <http://makiwara.com>*
*                             truetransformations.com
<http://truetransformations.com>*

                     *"IGNITE YOUR INNER TORCH"®*

                              Yeeee Haw!!!

**Comment by cagnulein** [comment]
here 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/8a466048-ed49-45ad-be8b-a6e427b81984)

and select the cadence sensor as a bike setting

**Comment by Drivelines** [comment]
Yes I have the cadence set to bike but still wont hook up
Under the pause and stop button
It shows seeing the wahoo sensors and my watch but just keeps scrolling
through them

Smile, Wade

**Comment by Drivelines** [comment]
Smile, Wade
