### ISSUE TITLE
Schwinn 810 treadmill feature request

### ISSUE THREAD

**Issue by mwaldschmidt** [cagnulein/qdomyos-zwift#2284]
Could be described as problem.  Schwinn 810 treadmill does work, but it only shows calories and distance.  Watts show during workout but not on email report.

Inclination, cadence, elevation gain, watts, avg watts, would be nice to see on the report, if possible.  I also turned off ant settings like suggested but can't get the heart rate sensor to show from the Schwinn 810.

Would love for any or all of the above to be able to work and show during the workout and on the final report.  I need to call Schwinn to see if they can help me adjust inclination via any bluetooth app, wasn't sure if you could tell anything from the logs without that.  I will call today or tomorrow.

Not sure of any alternatives.

Would love to know what settings are needed to make the Schwinn 810 heartrate sensor to work, and also what settings to get the ant+ dongle to work, once it arrives.  Ordering that today, so will likely want to go back to using the garmin hr sensor once it arrives, providing that the garmin dongle does what i want it to do and will allow me to see my treadmill workouts and Schwinn ic4 bike workout stats.  Lately I have been doing 'walk activity' on garmin instead of 'qz companion' as when i used the qz companion it doesn't provide the overview of the walk with stats, like it does if i use 'walk' activity.

Thanks
[debug-Mon_Apr_8_15_17_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14911854/debug-Mon_Apr_8_15_17_53_2024.log)

**Comment by cagnulein** [comment]
the main issue @mwaldschmidt is that you are in pause mode (the play button is flashing red). Press it and you will see also the other metrics.

Also your treadmill doens't send heart rate over bluetooth. Which hear rate belt has it? I guess it's a custom one from schwinn.

Let me know

**Comment by mwaldschmidt** [comment]
You were right on pause mode, thank you.  For some reason it's not set to auto-pause, but does.  No biggie, I will just un-pause each time unless you have any ideas on that.

And you are correct, I just realized it is only a handbar sensor, otherwise on their site they say this: This treadmill will work with any uncoded heart rate strap from Polar Electro or an uncoded Polar Compatible model.  If I got one of the straps do you know if it would broadcast to QZ?  QZ does see the Schwinn 810 for heart rate sensor, but it does not work.  Zwift also sees the heart rate sensor but it doesn't work either.

And finally, I have called Schwinn and they said for apps it only works with Explore the world and Zwift.  I asked if you can adjust the incline via any app over phone and they said no.  I just asked over email support the same question / if it will allow you to at least view the incline over any app.  Once I have their answer I will let you know.  On zwift is only shows speed and heart rate (but doesn't work) - it for some reason doesn't see cadence even though it works on QZ.

On that note, I assume the incline would increase calories burned, but wanted to confirm.  If there is no possible way for incline to broadcast, is there some way to calculate how many calories it will burn on a 10% incline?  I only ever walk on 10% incline so this would be helpful if some way to show or calculate.

Attaching debug log from last walk in case it's helpful.

[debug-Thu_Apr_11_06_33_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14951651/debug-Thu_Apr_11_06_33_05_2024.log)


Thanks for all your help.

Mike

**Comment by cagnulein** [comment]
> And you are correct, I just realized it is only a handbar sensor, otherwise on their site they say this: This treadmill will work with any uncoded heart rate strap from Polar Electro or an uncoded Polar Compatible model. If I got one of the straps do you know if it would broadcast to QZ? QZ does see the Schwinn 810 for heart rate sensor, but it does not work. Zwift also sees the heart rate sensor but it doesn't work either.

any bluetooth heart rate device work with QZ. I have a polar one for example



> it for some reason doesn't see cadence even though it works on QZ.

did you also pair the cadence on zwift?



> On that note, I assume the incline would increase calories burned, but wanted to confirm. If there is no possible way for incline to broadcast, is there some way to calculate how many calories it will burn on a 10% incline? I only ever walk on 10% incline so this would be helpful if some way to show or calculate.

yes qz counts also the inclination to the calories burn. if you want I can add a way to force the inclination value to qz so you can use the qz inclination tile to manually change it so also the calories will change too. What do you think?

**Comment by mwaldschmidt** [comment]
If you could force the inclination that would be great.  Let me know.

Thank you!

Mike

**Comment by cagnulein** [comment]
sure, i will do next week!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 apr 2024 alle ore 14:14 mwaldschmidt <
***@***.***> ha scritto:

**Comment by mwaldschmidt** [comment]
Perfect.

Mike

**Comment by cagnulein** [comment]
done! it will be in the 2.16.53 !

**Comment by mwaldschmidt** [comment]
Amazing!  Thank you.

Mike

**Comment by cagnulein** [comment]
@mwaldschmidt are we OK with this?

**Comment by mwaldschm** [comment]
Yep, any idea when the next release will be?  Please close out but just curious.  Excited to be able to manually change the inclination.

Mike

**Comment by cagnulein** [comment]
It's in review from  Google,if you want I can add you to the private beta testing. Send me an email to Roberto.viola83 at Gmail.com indicating this ticket and I will add you!

**Comment by mwaldschmidt** [comment]
Thanks, I accidentally replied with work github, so deleted, reposting from personal to show interaction:

Yep, any idea when the next release will be? Please close out but just curious. Excited to be able to manually change the inclination.

I will email you to join the beta, thanks as always.

MIke
