### ISSUE TITLE
Data not passing over to Zwift

### ISSUE THREAD

**Issue by B4sler** [cagnulein/qdomyos-zwift#2286]
I can't get the connection to zwift working.
I have a DKN Endurun and do following:

Switch the treadmill on
Load up Zwift
Start QZ - detects the treadmill as i-console21
Select the treadmill in zwift as Wahoo Tread 0003
Load a run on Zwift
By the time it's gets to the screen, there is a Connection Failure message in Zwift
Both the treadmill and QZ are still in sync
I go to connections in zwift, deselect and select Wahoo Tead 0003 but this still does not send the data to Zwift

![inbound8674377162816234184](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/044237e0-1bc1-40b6-b58a-cfafbb36ff19)
![inbound3622775431110587394](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/eef9924f-d0f1-46f8-86c1-edaa18c93795)
![inbound2777905625120874341](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/d7b48b26-f16e-453e-8868-ea079ba3230e)
![inbound5008766425972904748](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/daf19ef8-b012-4972-80dc-d1226a973fd1)

![inbound583219236275806525](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/fa985c75-1856-43b0-b68d-2a5f234417de)
![inbound6938507932546735902](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/abf58384-9517-477a-887f-a0cd88725dd9)
![inbound2941396703925096846](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/28e99cff-787a-4f44-bd30-47e29ecda46f)
![inbound1782688856399298724](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/176b00f0-05d9-4c2a-9e70-5e7c0594c4d4)
![inbound4372732170366035155](https://github.com/cagnulein/qdomyos-zwift/assets/166552702/70cd0999-b840-4d8c-b55c-df054fc7e3b6)

**Comment by cagnulein** [comment]
hi @B4sler where qz is running? where zwift is running?

**Comment by cagnulein** [comment]
the wahoo virtual device must be on the same wifi network and same frequency of the apple tv, is it the case?
also try to rename your samsung phone to "bike" (only 4 letters) and reboot it. you should see the bike device on Zwift as well

Let me know

**Comment by B4sler** [comment]
Hi,

My phone (the virtual device?) is on my home WiFi and the Apple TV is also
on the same network.  The virtual device (Wahoo TREAD 0003) only displays
some kind of USB symbol on the paired devices screen and doesnt have the
green Wifi symbol underneath it like my phone has.
My phone is already renamed to BRun and i can see this as one of the
Bluetooth/Wifi options that come up when pairing the device (sometimes
comes up in duplicate??).  The other options are Wahoo TREAD 0003 and Wahoo
KICKR 0000 03.  I think i dropped a picture of this in Github.

**Comment by B4sler** [comment]
When you talk about frequency, do you mean whether the Apple TV and my
phone are both on either the 5Ghz or 2.4Ghz channel on my WiFi?

**Comment by B4sler** [comment]
Yes, i tried the phone name but nothing.

The good news is that i've just went into the garage and tried it again and
it works!  What i forgot is that i have a Deco Mesh Wifi so i 'think' what
has happened is that because the settings are set to 'Seamless Roaming'
then it's possible that my phone and the Apple TV box where on separate
frequencies and even separate Deco mesh boxes.  Could this explain that the
virtual device is visible to Zwift but the reason why i get the 'Connection
Failure' message once an activity is selected?  Seems as if Zwift is still
happy the connection is there but nothing comes through in that scenario.

**Comment by cagnulein** [comment]
yes this could explain the issue at 100%!

**Comment by B4sler** [comment]
Thanks again for your help, it is much appreciated!
