### ISSUE TITLE
automatic resistance no longer working

### ISSUE THREAD

**Issue by Chris0079** [cagnulein/qdomyos-zwift#2293]
**Describe the bug**
automatic resistance on fitplus bike ( sportstech sx600) 
**To Reproduce**
When using qz with zwift resistance used to automatically change with incline etc , I havent used app in a fair few months due to injury but something has changed and no longer works 
**Expected behavior**
When cycling up hill etc expected to increase resistance 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: ipad 11
 - OS: 17.5
 - Version 2.16.51
[debug-Sun_Apr_14_08_17_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14983262/debug-Sun_Apr_14_08_17_42_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
has any settings changed is this something I've done wrong , apologise in advance if its me .
thanks again for all your help

**Comment by cagnulein** [comment]
Hi @Chris0079 i checked  the log an the issue is that the bike is sending high resistance number like 100, 200... Did you talk to me in the past about your bike? do you have a debug log of a working scenario from some months ago?

**Comment by Chris0079** [comment]
Hi roberto yes we had spoken a lot about the bike in the past and you were amazing . I’m sure we and by that I mean you got it working fully although I may be wrong . Unfortunately I don’t have any older bug files as I think they were on an old tablet . On 15 Apr 2024, at 20:07, Roberto Viola ***@***.***> wrote:﻿
Hi @Chris0079 i checked  the log an the issue is that the bike is sending high resistance number like 100, 200... Did you talk to me in the past about your bike? do you have a debug log of a working scenario from some months ago?

**Comment by cagnulein** [comment]
by email? which is your email address? don't write here, write it like
roberto.viola83 at gmail.com

so i will find the conversation

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 apr 2024 alle 21:21 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
Hi thanks for  reply sure we’d tried that before tried it again and nothing works with the hammer bike disabled I’ll attach a couple of debug see if you On 16 Apr 2024, at 10:14, Roberto Viola ***@***.***> wrote:﻿
you have to disable the "Hammer Racer Bike Options" setting, under the bike settings.
Let me know

**Comment by cagnulein** [comment]
hi @Chris0079 in order to see the debug logs, you have to attach them on github directly otherwise I can't see them. Thanks

**Comment by Chris0079** [comment]
further to email here are the debug files with the hammer bike off . this is when nothing works

[debug-Wed_Apr_17_06_47_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15007516/debug-Wed_Apr_17_06_47_30_2024.log)
[debug-Wed_Apr_17_06_46_57_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15007517/debug-Wed_Apr_17_06_46_57_2024.log)

**Comment by cagnulein** [comment]
got it, leaving the hammer disabled, enable also the "Fit Plus Bike" setting and restart qz. let me know!

**Comment by Chris0079** [comment]
Ok cool I’ll try when I get in from work thanks On 17 Apr 2024, at 08:57, Roberto Viola ***@***.***> wrote:﻿
got it, leaving the hammer disabled, enable also the "Fit Plus Bike" setting and restart qz. let me know!

**Comment by Chris0079** [comment]
hi thanks for sorting this out amazing . ok so the auto resistance works great on the rides thank you so much. I'm desperately not trying to be a pain but if i try a workout on zwift with erg the resistance target will be just random sometime my resistance is 10 and same workout again will be 32 ive attached a debug log and wondered if you could have a quick look and see if im doing something stupid which is normal. thanks so much i owe you a coffee
[debug-Thu_Apr_18_15_50_20_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15026701/debug-Thu_Apr_18_15_50_20_2024.log)

**Comment by cagnulein** [comment]
this will be easy, I have to add the new erg dinamic for your bike profile. I will do this next week

**Comment by Chris0079** [comment]
ok wow you make it sound so easy . amazing thanks

**Comment by cagnulein** [comment]
done @Chris0079 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

What you will have to do when you will install this: do a free ride changing all the resistance manually so that qz can learn all the curve of power for all the resistance, then you will ready to enable the zwift erg setting in QZ

Let me know!

**Comment by Chris0079** [comment]
hi so i did what you said took the bike for a free ride and went though all the resistance setting 1-32 i then enabled the erg in the setting and tried a workout . the resistance went strait to maximum 32 and stayed there i did as long as i could to get a debug log which i will attach
[Uploading debug-Thu_Apr_18_15_50_20_2024.log…]()

**Comment by Chris0079** [comment]
i restarted the app a couple of time to see if it need it but to no avail just to let you know

**Comment by Chris0079** [comment]
sorry
[debug-Fri_Apr_19_14_05_01_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15041099/debug-Fri_Apr_19_14_05_01_2024.log)

**Comment by Chris0079** [comment]
Not sure what you mean but when entering a working with erg turned on the resistance goes strait to the max of 32 . I did the free ride with the resistance from 1 up to 32 so not sure where those high figures come from sorry On 19 Apr 2024, at 14:46, Roberto Viola ***@***.***> wrote:﻿
from the log I get strange resistance value on QZ like 100 200 300, are you seeing the same? that's the main issue

**Comment by Chris0079** [comment]
Oh just a thought resistance shows on qz so hike resitance is 10 restance shows as 100, 11 shows as 110 . 32 show on qz as 320 . Sorry never thought about that before didn’t affect use  On 19 Apr 2024, at 14:46, Roberto Viola ***@***.***> wrote:﻿
from the log I get strange resistance value on QZ like 100 200 300, are you seeing the same? that's the main issue

**Comment by cagnulein** [comment]
ok let me do this:
do a session where you manually change the resistance from 1 to 32 step by step and send me the debug log. we have to fix this first before going on erg mode,

**Comment by cagnulein** [comment]
hah ok so there is a 10x factor right? that's the issue! let me try to fix it

**Comment by Chris0079** [comment]
Yes x10 so sorry never mention it as it didn’t affect use on the free rides. . On 19 Apr 2024, at 14:55, Roberto Viola ***@***.***> wrote:﻿
hah ok so there is a 10x factor right? that's the issue! let me try to fix it

**Comment by Chris0079** [comment]
just in case you still needed the debug log going from step 1 to 32 
[debug-Fri_Apr_19_15_00_55_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15041507/debug-Fri_Apr_19_15_00_55_2024.log)

**Comment by cagnulein** [comment]
I will try to do it ASAP but my wife is at the hospital right now so I have
family urgency

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 16:07 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
Go family always first hope everything turns out ok On 19 Apr 2024, at 15:11, Roberto Viola ***@***.***> wrote:﻿
I will try to do it ASAP but my wife is at the hospital right now so I have

family urgency



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 19 apr 2024 alle 16:07 Chris0079 ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
ok i'm building a new one. when you will receive it, after installing it, go to the advanced settings and press ok on the watt offset ok button. this will clear the erg table.
then redo the spin for all the resistance. be sure that now the resistance is now shown correctly

let me know

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 16:52 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
you sir are a genius , all working in every mode thanks so much for all you help

**Comment by cagnulein** [comment]
amazing!

**Comment by Deluca2211** [comment]
That’s correct project setting. Apparently it’s where the updates are and also the factory reset, however I can’t seem to get into it. There must be a universal code, however from the manual the original owner sets this code in first set up. Mine is second hand recently bought for a bargain £130. I’m hoping there must be some way to reset it to new without it.

**Comment by Deluca2211** [comment]
I think you can update the console to a newer software and there’s certain settings for the onboard computer you can only use within project settings.

**Comment by Chris0079** [comment]
Yer really not too sure , when I first got it I hunted on the internet to find password or reset code but without any luck . Even the manual says only used for service . So no idea what is missing. I even emailed sportstech in Germany but they only stated that no updates had been released so there was no need for service access. Luckily I’ve had it two years now and have never had a problem as I used it with qz and Zwift . ( after much back and fourth with roberto ) 


Sent from Sky Yahoo Mail for iPhone


On Monday, November 25, 2024, 7:16 PM, Roberto Viola ***@***.***> wrote:




@Chris0079 @Deluca2211 but without the password what you are missing?
