### ISSUE TITLE
DKN AM-3i not connecting to QZ

### ISSUE THREAD

**Issue by alec100** [cagnulein/qdomyos-zwift#2294]
**Describe the bug**
DKN AM-3i not connecting to QZ - with iConsole setting toggled OFF or ON

**To Reproduce**
DKN powered on.
QZ started.

**Expected behavior**
iConsole OFF: DKN brief reset. QZ 'start flashes'. No Metrics
iConsole ON: DKN powers off. DKN screen shuts down. No QZ metrics.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.3.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Tue_Apr_16_11_40_03_2024 iConsole OFF.log](https://github.com/cagnulein/qdomyos-zwift/files/14995988/debug-Tue_Apr_16_11_40_03_2024.iConsole.OFF.log)
[debug-Tue_Apr_16_11_44_28_2024 iConsole ON.log](https://github.com/cagnulein/qdomyos-zwift/files/14995990/debug-Tue_Apr_16_11_44_28_2024.iConsole.ON.log)

**Comment by cagnulein** [comment]
let me check, for reference, the original ticket was https://github.com/cagnulein/qdomyos-zwift/issues/285

**Comment by cagnulein** [comment]
@alec100 the vescape app https://apps.apple.com/ae/app/vescape-fitness-training-app/id1065527796 works for your bike?

**Comment by alec100** [comment]
I have Vescape on my phone, but it wouldn't start, and a search on App Store says 'Not available in your location'.

in QZ I set Experimental Features / Virtual Device Bluetooth to OFF. Metrics are now displayed. DKN bike screen and buttons are off. Connected to Zwift (Bluetooth listed as Wahoo 003 or similar).
 
However, I can't change the resistance using the QZ Resistance or the Target Resistance metric. It seems to be stuck in ERG mode - with a very low gear. I was testing using a normal Zwift 'Just Ride' workout - so that should not be in ERG mode.

Is there a way to switch off ERG mode? The option was not available on Zwift.

Latest debug log attached.
[debug-Tue_Apr_16_18_33_11_2024 vert dev BT OFF.log](https://github.com/cagnulein/qdomyos-zwift/files/15003030/debug-Tue_Apr_16_18_33_11_2024.vert.dev.BT.OFF.log)

**Comment by cagnulein** [comment]
that's great @alec100 
In the log i see that QZ can already handle the resistance correctly, you have just to change the zwift resistance offset setting from 4 to a resistance value that you feel like the flat road resistance one.
Let me know!

**Comment by alec100** [comment]
I've not had a chance to test yet, but should ERG mode be ON or OFF? IE should QZ / DKN be constantly altering resistance to match Watts (as it did on last test), or not?
On a normal smart trainer, as you come to an incline, resistance gets harder, then you change gear to keep cadence constant. Is this what should happen using QZ?

**Comment by cagnulein** [comment]
> I've not had a chance to test yet, but should ERG mode be ON or OFF?

do you mean in qz? QZ ERG setting must follow the workout on zwift. so if you are doing a ERG mode workout on zwift, it must be enabled on QZ as well.



> should QZ / DKN be constantly altering resistance to match Watts (as it did on last test), or not?

yes it should on the latest version. If it doesn't already I can add it for sure!



> On a normal smart trainer, as you come to an incline, resistance gets harder, then you change gear to keep cadence constant. Is this what should happen using QZ?

Yes exactly, it's QZ has to do 

Let me know!

**Comment by cagnulein** [comment]
@alec100 any news?

**Comment by alec100** [comment]
Hi Roberto,

I have not had a chance to test recently. Just finished a training plan - and since unsubscribed from Zwift! I’ll re-subscribe and re-test in October and get back to you then.

Regards,
Alec

**Comment by cagnulein** [comment]
Ok no problem, thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 10 mag 2024 alle 18:00 alec100 ***@***.***> ha
scritto:

> Hi Roberto,
>
> I have not had a chance to test recently. Just finished a training plan -
> and since unsubscribed from Zwift! I’ll re-subscribe and re-test in October
> and get back to you then.
>
> Regards,
> Alec
>
