### ISSUE TITLE
Mywhoosh inclination and cadence 

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#2296]
**Describe the bug**

Using a TDF-5 with QZ in iPhone 13 and Mywhoosh on new iPad, the inclination will not auto adjust or allow me to change it. The cadence works and then intermittently will stop connecting for a few seconds and then reconnect. Continues to happen all during ride.

[debug-Mon_Apr_15_07_48_09_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/15009747/debug-Mon_Apr_15_07_48_09_2024.zip)

For some reason the date and time on this debug is incorrect. This should be the one from yesterday’s ride. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Dwhetsel I checked the log and there is a main issue: MyWhoosh is sending continusoly 0.3 and the real inclination all the time, so qz was crazy trying to accomodate the mywhoosh requests. Did you retry after this? It could be a bug of Mywhoosh (not the first one for sure :D)
I guess Zwift works correctly on the same setup, right?

**Comment by Dwhetsel** [comment]
Yes Zwift had no problems with the same setup. Do you work with Mywhoosh any in the case of letting them know about this? Or would they even care?

**Comment by cagnulein** [comment]
i'm not work with mywhoosh but i will be happy to help them but they are
not listening to me, already tried.

you can try to this again, maybe it was only a fluke

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 apr 2024 alle 20:28 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
I’ll try it again next time I ride. I’ll also try the Mywhoosh Facebook page now that I know it’s not a setting in QZ.
Thanks Roberto.

**Comment by cagnulein** [comment]
Ok, let me know.


Il giorno mer 17 apr 2024 alle 23:18 Dwhetsel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Dwhetsel any news?

**Comment by Dwhetsel** [comment]
No. I tried it again a couple days ago.

**Comment by cagnulein** [comment]
As far as I know it's working for the other qz users. Did you try to ask to the qz Facebook group?

**Comment by Dwhetsel** [comment]
I’m thinking it may be something to do with the Bluetooth connection from my iPhone to the iPad. When I tried riding on MyWhoosh last time it all connected to my iPhone on MyWhoosh but the cadence and HR would keep dropping and then come back on while all the metrics showing on QZ would stay working.

**Comment by cagnulein** [comment]
don't you ssee the wahoo device on mywhoosh as well? last time i tried mywhoosh it shows the Wahoo virtual device from QZ

**Comment by Dwhetsel** [comment]
I think it did but it would’t connect to my hart rate belt unless I used the iPhone connection. I have the HR belt connected to QZ to show the data there and thusly to MyWhoosh.

**Comment by cagnulein** [comment]
Yeah they didn't implement this yet

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 12 mag 2024 alle 18:36 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
So I should do it without the HR data and just connect to the wahoo connection?

**Comment by cagnulein** [comment]
You can try, it should works in both ways ,but since you have the issue
with  Bluetooth, it worth a try

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 12 mag 2024 alle 18:44 Dwhetsel ***@***.***> ha
scritto:

**Comment by Dwhetsel** [comment]
I pulled a hamstring racing my 7 year old grandson (I did win though, ha) so it may be a few days before I ride again.

**Comment by cagnulein** [comment]
Sorry to hear that!


Il giorno dom 12 mag 2024 alle 19:11 Dwhetsel ***@***.***> ha
scritto:
