### ISSUE TITLE
Autoresistance Issue with Sportstech sBike Lite and Zwift

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2297]
**Describe the bug**
I downloaded your app on my iPad and was hoping it will add auto resistance to my indoor bike for Zwift. Is this supported, I mean does your app function as a bridge for that? By now I cannot change the resistance for my bike in the app at all clicking on plus or minus. 

Update: I closed the app and restarted my bike and then opened the app. I can now see the resistance and can change it in the tile.
I then tried a climb portal workout in Zwift. When I start the workout, the resistance is on 8 like I was setting it up, so all good by now. When I enter the portal, the resistance goes up to 13 and stays there, no matter which section I enter, when I for example also try to change I manually, it jumps back to 13. so it seems there is some auto resistance but it’s not changing. After the secon attempt, the auto resistance stays at 8 on the way to and after entering the climb portal.

**To Reproduce**
Start the Bike
Start the QZ app
Resistance goes automatic to 8 as I was setting it up on the app
Starting Zwift, connecting the bike (shows as Wahoo kickr instead of sBike Lite)
Starting the Climb Portal Workout
Resistance still on 8
Entering the portal - resistance snaps to 13 on first attempt and stays there
Entering the portal -  resistance stays at 8 without any change over the course

**Expected behavior**
Change of autoresistance in Climb Portal

iPad OS 17.4.1, iPad Pro 12,9“

[debug-Thu_Apr_18_12_56_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15024097/debug-Thu_Apr_18_12_56_44_2024.log)

**Comment by cagnulein** [comment]
hi @Fysibisy the issue is that you have the zwift erg setting enable in the bike section. disable it and you will have auto resistance for free rides! Let me know!

**Comment by cagnulein** [comment]
hi, you have to attach the video on github directly otherwise i can't see it. Anyway send me a log in this scenario, it's better than a video

**Comment by Fysibisy** [comment]
Yo,it works now with the autoresistance, but theres one other thing. Some of those players are crazy fast on that uphill, I am wondering if the translation from resistance to speed in Zwift is correct? My cadence is around 85-90 but those guys just fly next to me, I mean like double the speed. Anyway, autoresistance is working now. Best, JanMit besten Grüßen,Jan SonntagAm 18.04.2024 um 14:46 schrieb Roberto Viola ***@***.***>:﻿
hi, you have to attach the video on github directly otherwise i can't see it. Anyway send me a log in this scenario, it's better than a video

**Comment by Fysibisy** [comment]
I can’t find that setting. What about „Speed calculates on power“-setting in your app. Is this helpful? Mit besten Grüßen,Jan SonntagAm 18.04.2024 um 14:55 schrieb Roberto Viola ***@***.***>:﻿
you can increase auto resistance in the settings increasing the zwift resistance offset. the default is 4, means that 4 is the flat road resistance. also you can change it in real time using the gear tile
Let me know and also remember to rate the app on the store, it means a lot to me!
Thanks!

**Comment by cagnulein** [comment]
This one ![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/9c3e73b4-5e16-45e1-9a64-6676a206ed88)

**Comment by Fysibisy** [comment]
Ok so this option does the job? I also found the resistance offset, but I think the power output to speed ratio seems more reasonable, right? Mit besten Grüßen,Jan SonntagAm 18.04.2024 um 15:14 schrieb Roberto Viola ***@***.***>:﻿
This one Upload.from.GitHub.for.iOS.png (view on web)

**Comment by cagnulein** [comment]
for the auto resistance you have to change the zwift resistance offset. the speed power based setting is affecting only the qz speed not the zwift one. zwift calculates it from the wattage on qz. if you want to change your wattage (cheating) you have to use the watt gain in the advanced section

**Comment by Fysibisy** [comment]
Ok, got you. I rated the app with five stars because I think it’s helping a lot of people including me and your support and reaction time is superb. As a designer and as a user I think there could be some improvements for the Ui, but other than that, great app, thanks. Best, JanAm 18.04.2024 um 15:44 schrieb Roberto Viola ***@***.***>:﻿
for the auto resistance you have to change the zwift resistance offset. the speed power based setting is affecting only the qz speed not the zwift one. zwift calculates it from the wattage on qz. if you want to change your wattage (cheating) you have to use the watt gain in the advanced section

**Comment by cagnulein** [comment]
thanks :) yes i'm a firmware develeoper so i'm thinking to the functionality first!

**Comment by Fysibisy** [comment]
Hi Robertothis morning it tried to do a group ride in the tutorials. The Resistance offset was on 4, Zwift pulled me into the group, but the bikes resistance stayed on 3 the whole time and I couldn’t keep up, even if the Zwift resistance offset was later set to 21.Then I thought maybe I should do an FTP Test. Zwift Resistance Offset to 21 as suggested on YouTube. „Speed calculation on Power“ is ON as suggested from you yesterday. The preset resistance is on 7. ERG Mode in Zwift was turned off. I startet the test and first there is a 8 minute free fride which I did on resistance = 7 as set up. When I entered the first section, the resistance automatically did not go down to 50,60,70 … watts for the next sections. So I activated ERG mode in the workout setting and the power output changed based on my cadence. But I wanted to keep my cadence on 80-90 as from Zwift suggested, but this was not possible because the power output then was too high. Also changing the resistance manually to equalize it with my cadence go the final power output was not possible. Turning off the ERG mode in the workout setting while doing the test allowed me to change my resistance manually but it was going all over the place. What is the correct setting your app to do an FTP test? Is it different from doing free rides?What is the correct setup for group rides? Sorry for asking that much questions but I don’t understand it fully. Best, Jan Mit besten Grüßen,Jan SonntagAm 18.04.2024 um 16:11 schrieb Roberto Viola ***@***.***>:﻿
thanks :) yes i'm a firmware develeoper so i'm thinking to the functionality first!

**Comment by cagnulein** [comment]
what do you mean by group ride? it was a workout or a free ride? for workouts you need to enable zwift erg setting in qz and erg mode in zwift as well. Your bike doesn't support erg mode by default so I can add it if you want

**Comment by Fysibisy** [comment]
Group rides are called robo pacers in Zwift. Pace setting bots—give you the option to ride with one of our many Pacer Groups. Whether you're looking to maintain an easy pace, or to push yourself hard, we have a pacer group for you! You can find more info on Pacer Groups hereSo for FTP Tests and workouts if have to turn on ERG mode in Zwift and your app? Does the work with autoresistance. I am confused, sorry. Other than that, it should be off?Mit besten Grüßen,Jan SonntagAm 19.04.2024 um 09:18 schrieb Roberto Viola ***@***.***>:﻿
what do you mean by group ride? it was a workout or a free ride? for workouts you need to enable zwift erg setting in qz and erg mode in zwift as well. Your bike doesn't support erg mode by default so I can add it if you want

**Comment by Fysibisy** [comment]
… and Wdym you can add it, if I want?Mit besten Grüßen,Jan SonntagAm 19.04.2024 um 09:18 schrieb Roberto Viola ***@***.***>:﻿
what do you mean by group ride? it was a workout or a free ride? for workouts you need to enable zwift erg setting in qz and erg mode in zwift as well. Your bike doesn't support erg mode by default so I can add it if you want

**Comment by cagnulein** [comment]
but do you see a requested wattage on zwift when you do this robo race? or not? i'm not friendly with this so send me a screenshot on github about this. 

ERG mode is a software module that I have to enable for this bike. I created it just a couple of weeks ago for bikes like your that doesn't have builtin on the firmware.

**Comment by cagnulein** [comment]
in order to be sure about what you are doing please attach a debug log during a pace ride following this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

So i can check myself what you are doing :) 

Anyway if erg mode is required will be an easy fix

**Comment by Fysibisy** [comment]
Here’s a more wider explanation for ftp and pace rides and the log file for the pace rides.Best, JanIssues with FTP Test and Pace Rides · Issue #2300 · cagnulein/qdomyos-zwiftgithub.comOn 19. Apr 2024, at 12:06, Roberto Viola ***@***.***> wrote:﻿
in order to be sure about what you are doing please attach a debug log during a pace ride following this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
So i can check myself what you are doing :)
Anyway if erg mode is required will be an easy fix
