### ISSUE TITLE
Zwift Click not working

### ISSUE THREAD

**Issue by Specsthadec** [cagnulein/qdomyos-zwift#2299]
Zwift click.  Confirmed connection to phone via Bluetooth.  Zwift click option turned on under accessories in the app.   Nothing is showing in controller option in Zwift.  

Nothing happens in game when I use the click.    The gears work using the tile button.  Echelon EX3.   

iPhone 13Pro
iOS 17.4.1
Qz v. 2.16.51

**Expected behavior**
I believe I’m supposed to be able to choose my phone under the controller option in Zwift.  Click will interface with the Qz app and gears will shift.  

This 
[debug-Thu_Apr_18_16_17_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15031394/debug-Thu_Apr_18_16_17_05_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi! the problem is that the click doesn't answer to qz. did you update its
firmware?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 01:39 Specsthadec ***@***.***>
ha scritto:

**Comment by Specsthadec** [comment]
Weird.  According to the Zwift Companion app it’s up-to-date but looking at the Zwift release notes it should be version 1.1.  I will reach out to them to see what the problem is.Sent from Tim's iPhoneOn Apr 18, 2024, at 11:07 PM, Roberto Viola ***@***.***> wrote:﻿
hi! the problem is that the click doesn't answer to qz. did you update its

firmware?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 19 apr 2024 alle 01:39 Specsthadec ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
Ok let me know!

**Comment by cagnulein** [comment]
@Specsthadec are we OK with this?
