### ISSUE TITLE
Issues with FTP Test and Pace Rides

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2300]
Sportstech sBike Lite
iPad Pro 12.9
Zwift

Basic settings in QZ Fitness:
- Zwift ERG mode = OFF
- Autoresistance = ON
- Zwift resistance offset = 21 (still dont understand, whats a good value for my bike, I am fit and a 100kg rider)
- Resistance on Start = 7

Basic settings in Zwift:
- ERG mode = OFF

UNEXPECTED BEHAVIOR FOR >> FTP TEST
The FTP test runs as follows: Successive zones, in each of which the resistance is increased by 10 watts after one minute until the target wattage is reached. Before the actual test takes place, you ride for 8 minutes to warm up. The cadence for the FTP test should be around 85-90 revolutions. The wattage is specified by Zwift, but the cadence is freely selectable.

PROBLEM 
Explanation: When warming up, Zwift starts at level 7 on my bike, as preset in the app. At a cadence of 80-90, this corresponds to around 140 watts. The resistance can no longer be changed manually on the bike after the start, but I would like to. 

Now the test starts: First section, 50 watts at 80-90 revolutions are required. Zwift does not automatically adjust the resistance to the required 50 watts for the first section and continues at level 7 on my bike. Manual adjustment of the resistance is not possible here either, so the test is aborted.

EXPECTED BEHAVIOR
Automatic adjustment of the resistance from Zwift to my bike for the respective sections of 50 - 250 watts for the FTP test at a cadence of 80-90.

- - - - - - - - - - - - - - - - - - - - 

Basic settings in QZ Fitness:
- Zwift ERG mode = OFF
- Autoresistance = ON
- Zwift resistance offset = 21
- Resistance on Start = 7

Basic settings in Zwift:
- ERG mode = OFF

UNEXPECTED BEHAVIOR FOR >> PACE RIDE

>> What is a pace ride?
https://zwiftinsider.com/robopacers/
https://www.youtube.com/watch?v=rbfZI72U3ic&t=2s&ab_channel=ZwiftInsider

Cycling RoboPacers
Taylor – 1.1 W/kg
Bernie – 1.5 W/kg
Miguel – 1.8 W/kg
Maria – 2.2 W/kg
Coco – 2.6 W/kg
Yumi – 2.9 W/kg
Jacques – 3.2 W/kg
Genie – 3.7 W/kg
Constance – 4.2 W/kg

UNEXPECTED BEHAVIOR FOR >> PACE RIDE
I would like to take part in a pace ride. I select a pace ride in Zwift and Zwift automatically throws me into the group. Now I have to maintain a pace to keep up with the group. For the first ten seconds after entering the pace, Zwift sets the resistance to 3 and virtually rides the bike itself so that I can get my bearings. After that, Zwift switches to my bike.  

PROBLEM:
Zwift automatically sets my resistance to 3 and after joining the group ride I can't change the resistance manually on my bike either. Even at a cadence of 100, I am too slow and lose the group. The resistance on the bike itself is no longer increased by Zwift, abort. 

EXPECTED BEHAVIOR
I can adjust the resistance on my bike so that I can produce more watts and therefore ride faster so that I don't lose touch with the group.

**Comment by Fysibisy** [comment]
[debug-Fri_Apr_19_12_14_01_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15038872/debug-Fri_Apr_19_12_14_01_2024.log)

**Comment by cagnulein** [comment]
Thanks, I will check later today!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 12:18 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Fysibisy log checked. This log report a classic zwift simulation, so no erg ride.
So QZ is adjusting the resistnace based on the zwift resistance offset and the resistance requested from zwift.

As I said earlier, you have first of all to decide which is the resistance that you feel like to ride a flat road. For example 12.
Then set this to the zwift resistance offset.

QZ will use this value as a base line for any zwift requests.

How many resistance level does your bike have?

**Comment by Fysibisy** [comment]
@cagnulein I did, as I wrote I was setting up the offset to 21. My bike has 24 resistance levels.

**Comment by Fysibisy** [comment]
Hi @cagnulein, I already sent you E-Mails from sonntag.jan@me.com

**Comment by cagnulein** [comment]
sent!
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle ore 14:37 Fysibisy ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
share the debug log. first of all test a free ride

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 17:28 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein tried the FTP first, attached the log.

ERG mode on in both apps
- can’t change the resistance manually 
- Zwift does not change the resistance based on wattage 

[debug-Fri_Apr_19_17_32_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15042700/debug-Fri_Apr_19_17_32_24_2024.log)

**Comment by cagnulein** [comment]
as i said please try first a free ride and post the log if it doesn't work

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 17:47 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
you have to use the gear tile to change the resistance once the auto resistance is engaged

**Comment by Fysibisy** [comment]
When I switch back to your app and then back to Zwift, Zwift loses the connection. I will update you with a free ride later. Should I turn ERG mode on or off? Mit besten Grüßen,Jan SonntagAm 19.04.2024 um 17:52 schrieb Roberto Viola ***@***.***>:﻿
you have to use the gear tile to change the resistance once the auto resistance is engaged

**Comment by cagnulein** [comment]
are you running to qZ and Zwift on the same device? Probably doesn't have
enough Memory to handles zwift in background. I suggest to use 2 devices
for this

For free rides erg mode on qz must be turned off
On Zwift always enable
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 17:55 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Yes, on my iPad Pro. It’s the latest model with M2 Chip, should be powerful enough and enough RAM. I can run QZ on my iPhone and Zwift on my Tablet and they still communicate with each other? Okay, I will check the free ride later. JanAm 19.04.2024 um 17:58 schrieb Roberto Viola ***@***.***>:﻿
are you running to qZ and Zwift on the same device? Probably doesn't have

enough Memory to handles zwift in background. I suggest to use 2 devices

for this



For free rides erg mode on qz must be turned off

On Zwift always enable

Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 19 apr 2024 alle 17:55 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
on iPad the only way to run the two apps together is with the split view.
You can't run qz background on iOS.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 apr 2024 alle 18:01 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Got you. Mit besten Grüßen,Jan SonntagAm 19.04.2024 um 18:04 schrieb Roberto Viola ***@***.***>:﻿
on iPad the only way to run the two apps together is with the split view.

You can't run qz background on iOS.



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 19 apr 2024 alle 18:01 Fysibisy ***@***.***> ha

scritto:

**Comment by Fysibisy** [comment]
Hi @cagnulein attached the log for two free rides. 

1st Free ride with ERG ON in Zwift and OFF in Qz. 
Qz open on iPhone, Zwift open on iPad. 
Can’t change the resistance in Qz manually, no resistance change on the bike. 
Turned ERG OFF in Zwift, something seems to change in resistance but idk under what conditions. Turned ERG back ON. 

2nd Free ride kinda the same behavior but tried to turn off auto resistance in Qz. Something seems to change, but I don’t understand it. 

I can do another free ride, if you want but then you need to tell me, what should me turned on and off in the Zwift and Qz Settings. 

Attached the log. 
[Uploading debug-Sa__Apr__20_12_28_28_2024.log…]()

**Comment by cagnulein** [comment]
I can't read the log, it's corrupted. You have to wait the finish of the upload before pushing comment.

As I said in order to change the resistance manually when auto resistance is engaged you have to use the gear tile

**Comment by Fysibisy** [comment]
@cagnulein 
[debug-Sa__Apr__20_12_28_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15047896/debug-Sa__Apr__20_12_28_28_2024.log)

I pressed very tile I could find which said „resistance“.

**Comment by cagnulein** [comment]
I said gear not resistance. You have to enable this tile in the tiles settings

**Comment by Fysibisy** [comment]
Okay so I found the gear tile and did a shirt free ride. I can now change my gears, thank you. When Zwift throws me into the free ride, the resistance is on 7 on my bike, the is set to 0 in Qz. Later for example 3 in Qz translates into 13 on my Bike. What can I do to match those numbers? I will later to the FTP test to keep you updated. Mit besten Grüßen,Jan SonntagAm 20.04.2024 um 13:59 schrieb Roberto Viola ***@***.***>:﻿
I said gear not resistance. You have to enable this tile in the tiles settings

**Comment by Fysibisy** [comment]
@cagnulein I did the FTP Test and on two different tests the bike lost the connection. First in the warm up, second time at 300 Watt. Couldn’t reconnect and Zwift aborted. Very annoying. Attached the log. 

[debug-Sa__Apr__20_17_14_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15048731/debug-Sa__Apr__20_17_14_07_2024.log)

**Comment by cagnulein** [comment]
> @cagnulein Okay so I found the gear tile and did a shirt free ride. I can now change my gears, thank you. When Zwift throws me into the free ride, the resistance is on 7 on my bike, the is set to 0 in Qz. Later for example 3 in Qz translates into 13 on my Bike. What can I do to match those numbers? I will later to the FTP test to keep you updated. Mit besten Grüßen,Jan SonntagAm 20.04.2024 um 13:59 schrieb Roberto Viola ***@***.***>:﻿ I said gear not resistance. You have to enable this tile in the tiles settings —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

You have to choose the right zwift resistance offset, then you can simply override it with the gears tile .In zwift the only thing that's important it's the wattage, so if you are trained you can set a higher zwift resistance offset to do more effort and go faster on zwift

**Comment by cagnulein** [comment]
> @cagnulein I did the FTP Test and on two different tests the bike lost the connection. First in the warm up, second time at 300 Watt. Couldn’t reconnect and Zwift aborted. Very annoying. Attached the log.
> 
> [debug-Sa__Apr__20_17_14_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15048731/debug-Sa__Apr__20_17_14_07_2024.log)

Where are you running qz? Where zwift? As I told you it must run on split view or on another device

**Comment by Fysibisy** [comment]
I run Qz on my iPhone and Zwift on my iPad. I use my Apple Watch as the heart rate monitor connected via the Qz App on my Watch, as suggested by you. On 20. Apr 2024, at 19:21, Roberto Viola ***@***.***> wrote:﻿

@cagnulein I did the FTP Test and on two different tests the bike lost the connection. First in the warm up, second time at 300 Watt. Couldn’t reconnect and Zwift aborted. Very annoying. Attached the log.
debug-Sa__Apr__20_17_14_07_2024.log

Where are you running qz? Where zwift? As I told you it must run on split view or on another device

**Comment by cagnulein** [comment]
Are you using the phone name on zwift or the wahoo one? I suggest the wahoo
one. Also qz must running foreground on iPhone

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 apr 2024 alle 19:23 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein Attached the new log. ERG mode on and after a few minutes the connection is lost. 

[debug-Mo__Apr__22_21_03_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15067613/debug-Mo__Apr__22_21_03_54_2024.log)

**Comment by cagnulein** [comment]
checked the logs @Fysibisy there is a bluetooth issue for sure on your bike/phone/enviroment. the bike stops to answer back after a while.

I suggest first to disable the "virtual bluetooth device" in the experimental settings and restart QZ (ONLY THIS SETTING THERE). 
This should prevent QZ to also create the bridge over bluetooth since you are not using it.
Let me know if it's better

**Comment by Fysibisy** [comment]
@cagnulein Hi, I did a lot of free rides, until now no issues. Will try to attempt a new FTP Test soon. Keep you updated.

**Comment by cagnulein** [comment]
that's great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 apr 2024 alle 20:52 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein Hi. Did the FTP test today and everything worked fine. 

I saved two setting profiles (ERG on and off) and tried to change my FTP value. So I changed the value, saved it, but after restarting the app is back to default. What can I do to fix this?

**Comment by cagnulein** [comment]
You have to press save on the profile screen when you do a modification,
profiles are not autosaved

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 18:01 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
That’s what I did. I’ll try it again and let you know. Mit besten Grüßen,Jan SonntagAm 25.04.2024 um 18:03 schrieb Roberto Viola ***@***.***>:﻿
You have to press save on the profile screen when you do a modification,

profiles are not autosaved



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 25 apr 2024 alle 18:01 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Changing profile it's reloading a lot of different things that requires a
restart of the app. That's it :)

The update will be available when  I will need to push a hot fix for
something widely spread, otherwise I'm keeping update the beta every month
or so.

I like to keep things stable for the most of the users

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 18:14 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Ok, thanks. Mit besten Grüßen,Jan SonntagAm 25.04.2024 um 19:04 schrieb Roberto Viola ***@***.***>:﻿
You can use the quick actions outside qz to load a profile without restarting it
