### ISSUE TITLE
NordicTrack s20i - treadmill

### ISSUE THREAD

**Issue by ptantot** [cagnulein/qdomyos-zwift#2301]
**Describe the bug**
I have a NordicTrack s20i treadmill, I am able to connect from the application and view the data from the treamill when I increase speed or inclination. But when I try to update the speed or inclination from the application it is not updated in the treamill.

**To Reproduce**
Step during log generation : 
- Start walking at 2km/h with 4 of inclination => info available in the application : OK
- Increase speed to 4km in the treamill => info updated in the application : OK
- Increase inclination to 6 in the treamill => info updated in the application : OK
- Increase / Decrease speed in the application => no action : KO
- Increase / Decrease inclination in the application => no action : KO

**Expected behavior**
When the speed or inclination is updated in the application it should update the speed / inclination of the treadmill

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/75063649/07fe00ef-4fd4-4a4e-9482-c3c6f16a391c)

**Desktop (please complete the following information):**
 - OS: Android 
 - Version 14

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 12
 - OS: Xiaomi HyperOS
 - Version 1.0.7.0

**Append a debug log**
See attach
[btsnoop_hci_240421_164809.log](https://github.com/cagnulein/qdomyos-zwift/files/15052682/btsnoop_hci_240421_164809.log)
ment

**Comment by cagnulein** [comment]
great! i will check later this week!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 apr 2024 alle 18:34 ptantot ***@***.***> ha
scritto:

**Comment by ptantot** [comment]
Hi Roberto,
Thanks for your help, your application seems great :)

I am available if you need more information.
Philippe
    Le dimanche 21 avril 2024 à 18:37:17 UTC+2, Roberto Viola ***@***.***> a écrit :  
 
 

great! i will check later this week!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 apr 2024 alle 18:34 ptantot ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @ptantot I checked the hci snoof and I have a good news.
The profile seems identic to the Nordictrack 10 one
Try to set this one and restart QZ
Let me know!

**Comment by ptantot** [comment]
Hi roberto,

Thanks for you quick feedback !

Unfortunatly it seems not working... or may be I have something wrong for setting profile...

I have set in QZ - settings -> Treadmill options -> Proform/Nordicktrack Option -> Specific Model => Set to "Nordictrack 10"

I have restarted QZ

Treadmill connected, run at 2km/h, increase to 3km/h : app is resfreshed.
Click on + /- for speed and then for inclination => no impact 🙁

I have generated a new log in attachment.
[btsnoop_hci_240422_223320.log](https://github.com/cagnulein/qdomyos-zwift/files/15068527/btsnoop_hci_240422_223320.log)

**Comment by cagnulein** [comment]
Hi @ptantot just to be sure: are you collecting the btnsoop with the nordictrack app? it's what I need to add auto speed and auto incliantion. Let me know!

**Comment by ptantot** [comment]
Hi @cagnulein. Sorry but I try only from QZ app...

Please find a new logs with update from iFIT (nordictrack app) . Sequence 
=> increase speed from 2km to 3km (increment of 0.1)
=> increase elevation from 0 to 1 (increment of 0.5)
=> decrease speed 3km to 2 km (increment 0.1)
=> decrease elevation 1 to 0 (increment 0.5)
[btsnoop_hci_240423_215540.log](https://github.com/cagnulein/qdomyos-zwift/files/15082760/btsnoop_hci_240423_215540.log)

**Comment by cagnulein** [comment]
[s20i.txt](https://github.com/cagnulein/qdomyos-zwift/files/15088606/s20i.txt)

all frame, now I can handle in the code. I will let you know when I will be ready!

**Comment by cagnulein** [comment]
init frames

```
unsigned char array1[] = {0xfe, 0x02, 0x08, 0x02};
unsigned char array2[] = {0xff, 0x08, 0x02, 0x04, 0x02, 0x04, 0x02, 0x04, 0x81, 0x87, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array3[] = {0xfe, 0x02, 0x08, 0x02};
unsigned char array4[] = {0xff, 0x08, 0x02, 0x04, 0x02, 0x04, 0x04, 0x04, 0x80, 0x88, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array5[] = {0xfe, 0x02, 0x08, 0x02};
unsigned char array6[] = {0xff, 0x08, 0x02, 0x04, 0x02, 0x04, 0x04, 0x04, 0x88, 0x90, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array7[] = {0xfe, 0x02, 0x0a, 0x02};
unsigned char array8[] = {0xff, 0x0a, 0x02, 0x04, 0x02, 0x06, 0x02, 0x06, 0x82, 0x00, 0x00, 0x8a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array9[] = {0xfe, 0x02, 0x0a, 0x02};
unsigned char array10[] = {0xff, 0x0a, 0x02, 0x04, 0x02, 0x06, 0x02, 0x06, 0x84, 0x00, 0x00, 0x8c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array11[] = {0xfe, 0x02, 0x08, 0x02};
unsigned char array12[] = {0xff, 0x08, 0x02, 0x04, 0x02, 0x04, 0x02, 0x04, 0x95, 0x9b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array13[] = {0xfe, 0x02, 0x2c, 0x04};
unsigned char array14[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x28, 0x04, 0x28, 0x90, 0x07, 0x01, 0x85, 0x08, 0x91, 0x18, 0xad, 0x30, 0xc1, 0x50, 0xe5};
unsigned char array15[] = {0x01, 0x12, 0x88, 0x11, 0xb8, 0x5d, 0xe0, 0x81, 0x20, 0xc5, 0x68, 0x31, 0xd8, 0x6d, 0x30, 0xc1, 0x90, 0x25, 0xe8, 0xb1};
unsigned char array16[] = {0xff, 0x08, 0x78, 0x3d, 0xc0, 0x98, 0x02, 0x00, 0x00, 0xed, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array17[] = {0xfe, 0x02, 0x19, 0x03};
unsigned char array18[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x15, 0x04, 0x15, 0x02, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array19[] = {0xff, 0x07, 0x00, 0x00, 0x00, 0x10, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array20[] = {0xfe, 0x02, 0x17, 0x03};
unsigned char array21[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x13, 0x04, 0x13, 0x02, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array22[] = {0xff, 0x05, 0x00, 0x80, 0x00, 0x00, 0xa5, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array23[] = {0xfe, 0x02, 0x19, 0x03};
unsigned char array24[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x15, 0x04, 0x15, 0x02, 0x00, 0x0f, 0x00, 0x10, 0x00, 0xd8, 0x1c, 0x48, 0x00, 0x00, 0xe0};
unsigned char array25[] = {0xff, 0x07, 0x00, 0x00, 0x00, 0x10, 0x00, 0x08, 0x6e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

```

noop frames

```
unsigned char array1[] = {0xfe, 0x02, 0x17, 0x03};
unsigned char array2[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x13, 0x04, 0x13, 0x02, 0x00, 0x0d, 0x13, 0x96, 0x31, 0x00, 0x00, 0x40, 0x10, 0x00, 0x80};
unsigned char array3[] = {0xff, 0x05, 0x18, 0x00, 0x00, 0x01, 0xe9, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array4[] = {0xfe, 0x02, 0x19, 0x03};
unsigned char array5[] = {0x00, 0x12, 0x02, 0x04, 0x02, 0x15, 0x04, 0x15, 0x02, 0x00, 0x0f, 0x80, 0x08, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
unsigned char array6[] = {0xff, 0x07, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x10, 0x82, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

```

**Comment by cagnulein** [comment]
done @ptantot 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8814902384
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by ptantot** [comment]
Hi @cagnulein,
Thank you very much for your help !!!

There is some progress. I tried build #6971 as #6968 failed.
==> After uninstalling the "official" version and installing beta #6971, I selected "Nordictrack S20i" in the treadmill options. After restarting the application I am able to communicate with the treadmill from QZ (+ - option of speed / incline induce action on the treadmill).

Now some problem / question 
=> When I start, it is set to [Uploading btsnoop_hci_240424_190128.log…]() and not 2 km. A problem with km vs miles? A known problem? Do you have a solution?
=> Pause / Stop does not seem to work => I have created a new log with pause and stop at the end of the scenario using iFIT.

For the integration with zwift, the speed change during the workout does not seem to be applied to the treadmill. I thought it could be automatic but maybe I am wrong or as a newbie I have not configured something correctly? Do you have any tuto?

**Comment by ptantot** [comment]
Sorry, the logfile : [btsnoop_hci_240424_190128.log](https://github.com/cagnulein/qdomyos-zwift/files/15108269/btsnoop_hci_240424_190128.log)

**Comment by cagnulein** [comment]
are you able to create a debug log from qz directly with the issue?
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Also i don't get it: instead of 2km/h which the  value that you read?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 12:33 ptantot ***@***.***> ha
scritto:

**Comment by ptantot** [comment]
I get 1.6 km h  see screen
![IMG_20240425_143156](https://github.com/cagnulein/qdomyos-zwift/assets/75063649/151df93f-a41a-48d0-adb1-65ba8bafb812)

+ on QZ go to 2kmh, and after 2,5kmh...

The log from QZ:
![IMG_20240425_143156](https://github.com/cagnulein/qdomyos-zwift/assets/75063649/d07fdeee-10cc-4c44-a26f-2b6d36978d61)

**Comment by cagnulein** [comment]
@ptantot in the log i saw that you didn't turn on the miles setting in qz under the general settings. let me know if it's better

**Comment by cagnulein** [comment]
@ptantot any news?

**Comment by cagnulein** [comment]
@ptantot are you still interested on this? https://github.com/cagnulein/qdomyos-zwift/issues/2992#issuecomment-2588245133
