### ISSUE TITLE
Elevation Gain Decreasing

### ISSUE THREAD

**Issue by hellobensalt** [cagnulein/qdomyos-zwift#2302]
**The elevation gain recorded by QZ decreases when the incline override in Horizon Treadmill settings is set to a negative number.**

 I've set the incline override to -2. 

1. When I start my treadmill with the treadmill incline on zero, the elevation gain recorded by QZ becomes negative.
2. When I increase the incline of my treadmill to 2, the elevation gain recorded by QZ does not change (this is correct).
3. When I increase the incline of my treadmill above 2 (e.g., to 3), the elevation gain recorded by QZ goes up (this is correct).
4.  But, when I decrease the incline of my treadmill back down to 1 or 0, the elevation gain recorded by QZ decreases.

**Elevation gain should never decrease and cannot be less than zero.**

Hardware/software: Horizon 7.4AT-03 treadmill, Pixel 6 phone running latest Android version, QZ 2.16.50

I've attached a bug report. However, QZ was stuck in pause mode when I ran this test (this is a separate issue), but I think the elevation data should still be shown. If not, please let me know.

[debug-Mon_Apr_22_16_35_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15060945/debug-Mon_Apr_22_16_35_10_2024.log)

**Comment by cagnulein** [comment]
yes fixed here this morning https://github.com/cagnulein/qdomyos-zwift/issues/2259#issuecomment-2068650015

**Comment by hellobensalt** [comment]
Oh, no! Sorry, I was too slow... I've been very busy. I'm about to post another issue.
