### ISSUE TITLE
Pause and Pause Mode Settings Not Working Correctly with Horizon 7.4-AT-03

### ISSUE THREAD

**Issue by hellobensalt** [cagnulein/qdomyos-zwift#2303]
Hardware/software: Horizon 7.4AT-03 treadmill, Pixel 6 phone running latest Android version, QZ 2.16.50

- QZ always connects to my treadmill in pause mode. The General and Horizon Treadmills pause mode settings are set to the default (off). Turning them on and off does nothing.

- If I pause my treadmill manually, QZ goes into pause mode. But I cannot restart my treadmill from QZ and if I restart my treadmill manually, QZ does not restart. I have to start a new activity.

- If I stop a QZ activity, my treadmill continues running (perhaps this is the normal, expected behaviour?).

I've attached an HCI snoof using Horizon's AFG Pro app. I did the following:

1. Start the treadmill in the AFG Pro app.
2. Pause the treadmill in the AFG Pro app.
3. Restart the treadmill in the AFG Pro app.
4. Pause the treadmill in the AFG Pro app.
5. Start the treadmill manually.
6. Pause the treadmill manually.
7. Start the treadmill manually.
8. Stop the treadmill in the AFG Pro app.
9. Start a new activity
10. Start the treadmill in the AFG Pro app.
11. Pause the treadmill manually.
12. Stop the treadmill manually.

Everything worked as expected. However, I realise there are a lot of steps above, so you may need separate logs for the different steps. Please let me know.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/15061702/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks, I will have a look

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 apr 2024 alle ore 12:54 hellobensalt <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
hi @hellobensalt I checked the pause frame used by the AFG app and it's the same that I implemented. Could you please create a debug log from QZ while you are trying to pause and unpause the treadmill from QZ directly?

The "Disable Pause" setting in the horizon treadmill must be disabled.

So follow this:
- start qz
- wait a minute for the connection with the treadmill
- start the treadmill as you usually do with qz
- try to pause it with qz
- try to unpause

Let me know
Thanks!

**Comment by hellobensalt** [comment]
I'll check later.

But it's not just pausing the treadmill in QZ. The app always starts the treadmill in pause mode. Every time. The General and Horizon Treadmill pause settings do not work. Also, once the treadmill is paused, the treadmill will not restart.

So, there are many issues. I can try to capture a debug log for each one, but I'm not sure what to do about the settings. I can turn them on/off and restart the app, then connect to the treadmill, if that helps?

Anyway, I'll start with what you asked for.

**Comment by hellobensalt** [comment]
Here it is:

[debug-Fri_Apr_26_17_23_54_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15129378/debug-Fri_Apr_26_17_23_54_2024.log)

Sorry for the delay. I'm going to try to look at all this during the next few days.

**Comment by cagnulein** [comment]
No problem, thanks!
I will get back to you ASAP

Il giorno ven 26 apr 2024 alle 12:32 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
Many thanks.

**Comment by cagnulein** [comment]
@hellobensalt i checked your debug log and the main issue of this is that you're pressing the pause/play button in QZ while the treadmill is still initializing. 

Consider that your treadmill took at least 1m 30s second to boot up.
Try to wait so 2 minutes (to be sure) and let's try to replicate the issue after this.

Let me know
