### ISSUE TITLE
[BUG] Kingsmith Walkingpad P1 no cadence reported

### ISSUE THREAD

**Issue by hubaiz** [cagnulein/qdomyos-zwift#2304]
No cadence is reported by Walkingpad P1

**To Reproduce**
1.Connect to walkingpad p1 with BT
2. start
3. the cadence field is 0 and does not change

**Expected behavior**
A cadence should be reported

**Screenshots**
![Screenshot_2024-04-22-19-47-03-694_org cagnulen qdomyoszwift](https://github.com/cagnulein/qdomyos-zwift/assets/1691871/4a6737ed-adcb-4ebd-82a5-40c14d64d6de)

**Smartphone (please complete the following information):**
 - Device: xiaomi MI 9 Lite
 - OS: Android 10 (MIUI 12.0.10

**Append a debug log**
[debug-Mon_Apr_22_19_37_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15066957/debug-Mon_Apr_22_19_37_39_2024.log)

**Additional context**
in the ks fit application the steps are reported

**Comment by cagnulein** [comment]
Thanks! I will check it! One question : do you see the cadence in the
original walking pad app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 apr 2024 alle 19:54 hubaiz ***@***.***> ha
scritto:

**Comment by hubaiz** [comment]
Yes, i can see it.
![Screenshot_2024-04-22-20-00-47-760_com kingsmith xiaojin](https://github.com/cagnulein/qdomyos-zwift/assets/1691871/3cb248e9-eeb9-4db3-aa5e-40939b247775)

**Comment by hubaiz** [comment]
Thanks :)

**Comment by cagnulein** [comment]
Note for me: byte 7

**Comment by cagnulein** [comment]
@hubaiz done!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/8797095704

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by hubaiz** [comment]
New debug log:
[debug-Tue_Apr_23_11_36_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15074747/debug-Tue_Apr_23_11_36_30_2024.log)

**Comment by cagnulein** [comment]
good news step counts works (you can see enabling the step count tile). let
me fix the cadence

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 23 apr 2024 alle 11:41 hubaiz ***@***.***> ha
scritto:

**Comment by hubaiz** [comment]
Yes now that you mentioned I enabled the steps tile and see it counting the steps.
My mistake that I assumed steps=cadence.

**Comment by cagnulein** [comment]
ok i guess i fixed cadence too now https://github.com/cagnulein/qdomyos-zwift/actions/runs/8798362310

**Comment by hubaiz** [comment]
Did checkout the new build but still no cadence is reported to zwift, also in the UI I only see the steps increasing but no cadence data.
Here is the log: 
[debug-Tue_Apr_23_13_22_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15076077/debug-Tue_Apr_23_13_22_51_2024.log)

**Comment by cagnulein** [comment]
sorry i forgot a casting

https://github.com/cagnulein/qdomyos-zwift/actions/runs/8800894239

**Comment by hubaiz** [comment]
Thanks, there is now cadence, as in app as in Zwift.
A bit fluctuating but probably it is because of the low speed.
log: 
[debug-Tue_Apr_23_15_47_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15077805/debug-Tue_Apr_23_15_47_39_2024.log)

**Comment by cagnulein** [comment]
i added a 5s average it should be better https://github.com/cagnulein/qdomyos-zwift/actions/runs/8801774094

**Comment by hubaiz** [comment]
Thanks, unfortunately I was traveling today and the build didn't finish till then. I can test it only on Sunday or Monday.

**Comment by cagnulein** [comment]
No problem! Let me know!

**Comment by hubaiz** [comment]
Tested it and now the cadance is working and it is more stable.  Works in Zwift to.

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno dom 28 apr 2024 alle 18:02 hubaiz ***@***.***> ha
scritto:
