### ISSUE TITLE
zwift click not working

### ISSUE THREAD

**Issue by Chris0079** [cagnulein/qdomyos-zwift#2307]
Zwift click not working when enabled in setting . no gear change is possible with click

Zwift click appear to be found by qz app and show on the app but does not provide any functionality

Device is showing up to date drivers 

Running ios 17.5 on iphone 11

qz version 2.16.52

I attach the debug file .
please note I press the up gear button 10 times and then the down gear button ten times and did that 3 times 
hopefully will provide the information you need
[debug-Thu_Apr_25_16_17_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15112384/debug-Thu_Apr_25_16_17_31_2024.log)
![IMG_1992](https://github.com/cagnulein/qdomyos-zwift/assets/121830852/6ca5a5bd-b86c-48fe-88cf-83c10443a679)

  

![IMG_1991](https://github.com/cagnulein/qdomyos-zwift/assets/121830852/616e016d-f8bf-4eda-851e-557e2d4aafc5)

**Comment by cagnulein** [comment]
hi! easy fix! the zwift click setting under accessories it's disabled.
enable it and let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 17:34 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
Hi sorry i have been running with it on and off in settings
 trying to get it to work without any luck . 
I've attached me debug with click enabled but still not working 
sorry
[debug-Thu_Apr_25_17_00_43_2024 (1).log](https://github.com/cagnulein/qdomyos-zwift/files/15112770/debug-Thu_Apr_25_17_00_43_2024.1.log)

**Comment by cagnulein** [comment]
now i see it, it doesn't answer to the qz requests. does it work with zwift?

**Comment by Chris0079** [comment]
its connect to the companion app and seems to work . but i have to use qz to get to the device connections on Zwift . so the minute i turn qz on the companion app loses connection . I've read the click will only connect to one Bluetooth connection at a time

**Comment by cagnulein** [comment]
Ok so do this: unpair it from the companion and remove the battery of the
zwift for a minute.

Then start it again and never pair it again with zwift or the Companion. It
would work then with qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 18:16 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
ok tried that still dosnt work , ive only turned on qz not sure its connecting ive attached a debug file , the click seems to turn itself off like its not connected to anything 
[debug-Thu_Apr_25_17_28_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15113010/debug-Thu_Apr_25_17_28_02_2024.log)

**Comment by Chris0079** [comment]
also if i go to advance settings qz seems to  finds the click when looking for manual devices but doesn't seem to connect when the bike is ??
![IMG_1994](https://github.com/cagnulein/qdomyos-zwift/assets/121830852/157e7898-5beb-4066-9197-af45dc1acc32)

**Comment by cagnulein** [comment]
Same issue, it seems that's still paired with zwift. I don't know if there
is a different way to reset it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 18:31 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
ok weird I haven't got any Zwift apps open only qz . not sure i can try again see what happens . Not a massive problem the app changes the gears nicely was just trying to get the click to work , I can always return it

**Comment by cagnulein** [comment]
I guess the click must be resetted somehow because the pairing is in its
memory in flash not touched from the  battery. Maybe try to check on
internet about a reset

I still have mine and it's working with the same firmware version

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 18:44 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
fair enough I have a look see what i can find

**Comment by cagnulein** [comment]
Ok, let me know.
It could be helpful also for other users

Il giorno gio 25 apr 2024 alle 18:49 Chris0079 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Confirmed, just retested on mine on ios and it's still working

**Comment by Chris0079** [comment]
thanks loads for trying , no idea why mines not . tried resetting multiply times , deleted device from companion app . did a fresh install of qz of ipad . qz does connect to click just dosnt work . not to worry i will return . thanks again and sorry to waste your time

**Comment by cagnulein** [comment]
No problem, that's very strange

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 apr 2024 alle 19:24 Chris0079 ***@***.***>
ha scritto:

**Comment by Chris0079** [comment]
Good afternoon ok after many hours and about 3 new clicks finally figured this little nugget out, so for anyone with this problem i thought id let you know. 
Zwift clicks come with firmware version 1.0.0 install there was a firmware release in oct 23 firmware version 1.1.0 
this firmware wasn't available  in the uk  for some reason. Anyway they sent me a new click with version 1.1.0 pre installed and it works . Zwift support said they will hopefully roll out firmware update shortly to uk customers

**Comment by Chris0079** [comment]
One slight problem it seems the longer you hold the click on my bike the more it changes gears which is fine but the smallest click i can do moves the gears up and down in 2's . is there a setting a can change to allow increments of 1

**Comment by cagnulein** [comment]
> One slight problem it seems the longer you hold the click on my bike the more it changes gears which is fine but the smallest click i can do moves the gears up and down in 2's . is there a setting a can change to allow increments of 1

yes use the gears gain in the bike settings. set it to 0.5 or less for example

**Comment by Chris0079** [comment]
amazing working perfectly thank you so much

**Comment by Specsthadec** [comment]
> Good afternoon ok after many hours and about 3 new clicks finally figured this little nugget out, so for anyone with this problem i thought id let you know. 
> 
> Zwift clicks come with firmware version 1.0.0 install there was a firmware release in oct 23 firmware version 1.1.0 
> 
> this firmware wasn't available  in the uk  for some reason. Anyway they sent me a new click with version 1.1.0 pre installed and it works . Zwift support said they will hopefully roll out firmware update shortly to uk customers 

Any order of operations to get to work consistently? Do you have to open the Zwift Companion app first then QZ then Zwift, etc.? I got it to work yesterday but couldn't get it to work today.

**Comment by cagnulein** [comment]
1. wake up the click pressing a button
2. open qz
3. when qz show the tiles, open zwift


let me know

**Comment by Chris0079** [comment]
Yes just as above , I always start click and my bike before starting qz and then I connect to Zwift . Works every time . Have you updated to the new firmware version 1.1.0 ??

**Comment by Sdoof** [comment]
Great thread, will click and QZ works on any torbo trainer (I have the Saris H3). Just wondering before I comit to the setup

**Comment by cagnulein** [comment]
@Sdoof let me know if you need help!

**Comment by estenssoros** [comment]
I was having issues with this, but found that enabling zwift play in addition to zwift click allowed the click to pair

**Comment by cagnulein** [comment]
That's strange but good that it's working.
If you want I can check your case with a debug log disabling the zwift play
setting
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 18:27 Sebastian Estenssoro <
***@***.***> ha scritto:
