### ISSUE TITLE
Incline Stuck at 15% with Zwift and Horizon 7.4AT-03

### ISSUE THREAD

**Issue by hellobensalt** [cagnulein/qdomyos-zwift#2308]
Setup: Horizon 7.4AT-03 treadmill, Pixel 6 phone running latest Android version, QZ 2.16.52

I attempted to do a Zwift controlled run with QZ today for the first time.

Since I'm on Android, I just used my phone and had QZ as a small floating window over Zwift. The floating window is too small to do anything, so I had to keep navigating back to the main QZ window. 

1. I started the activity in QZ, then moved back to the main Zwift window with QZ as a floating window.
2. I manually changed the incline of my treadmill to 2%, which is my baseline incline (I have the Inclination Override Offset on -2).
3. But I realised the incline had gone up to 15% and my treadmill beeped while it was increasing.
4. Every time I tried to put the incline down, it went back up to 15% again, with more beeping.
5. I navigated back to the main QZ window and tried there, but with the same result.
6. I stopped the activity and did a run without QZ.

I've attached a bug report in which I tried to recreate the above.

Is there something I need to do in Settings to correct this or is it a bug? For context, I did a free run with QZ yesterday, which was a hill workout. I had no issue with the incline then and made no changes to the settings, so this is only related to QZ with Zwift.

[debug-Sat_Apr_27_13_23_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15137301/debug-Sat_Apr_27_13_23_27_2024.log)

**Comment by cagnulein** [comment]
For sure treadmill override inclination gain can't be set to 0. It multiply
the inclination to 0 so it will give you unwanted effect. put the gain back
to 1 and try again. let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 08:36 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
I accidentally changed that to -2 when I was trying to change the Inclination Override Offset. I put it on zero, as I couldn't remember what it was and didn't know it was a multiplier.

Sorry! I've just rerun a few tests and it seems to work now. But I've noticed another issue: the elevation gain going negative. I'll create a new ticket here.

**Comment by cagnulein** [comment]
perfect! the elevation gain is already fixed i didn't deploy it yet. no
need to create a new one. thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:26 hellobensalt ***@***.***>
ha scritto:
