### ISSUE TITLE
Watt per kg in Zwift vs Qz

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2309]
@cagnulein Hi Roberto, I noticed the Zwift shows a significant lower W/kg than Qz. Which number is correct and what can I do to fix this?

**Comment by cagnulein** [comment]
did you set the right weight on both qz and zwift? same unit also?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:31 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein I did and repeated the saving process as follows 

Go to settings in my profile via quick actions, 
set the number, 
clicked OK, 
saved the profile, 
quit the app and still the changes are not saved. 🙄

**Comment by cagnulein** [comment]
make me a video of the full process, you are doing something wrong

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:39 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein Filesize exceeds 10 MB. Where can I send it?

**Comment by cagnulein** [comment]
put it on google drive and share here a link

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:48 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein 

https://github.com/cagnulein/qdomyos-zwift/assets/167186878/e430ecbd-088e-406d-970e-0d906b3a9c7e

**Comment by cagnulein** [comment]
got the issue: it's not the profile save button, the profile save button is this one

https://github.com/cagnulein/qdomyos-zwift/assets/48216/8e51eefb-45bc-4ce7-a342-90fe92f7f8a5

**Comment by Fysibisy** [comment]
Okay, got it. Is it possible to make Ui-Theme changes, that affect all profiles?Am 27.04.2024 um 10:45 schrieb Roberto Viola ***@***.***>:﻿
got the issue: it's not the profile save button, the profile save button is this one
https://github.com/cagnulein/qdomyos-zwift/assets/48216/8e51eefb-45bc-4ce7-a342-90fe92f7f8a5

**Comment by cagnulein** [comment]
you can use a profile as a template and create a new one inheriting all the
settings

also the profiles are text files so you can edit them if you want

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 10:56 Fysibisy ***@***.***> ha
scritto:
