### ISSUE TITLE
REQ : Zwift icon

### ISSUE THREAD

**Issue by d-nx** [cagnulein/qdomyos-zwift#231]
I used the Zwift icon to troubleshoot connectivity between QZ and Zwift but the icon is now gone.

I wonder if it could be brought back maybe on the top bar next to the resistance icon?

**Comment by cagnulein** [comment]
The zwift icon was broken on some device (android) this is why I removed it.
I wouldn't like to put it again. Maybe i can add a popup when an error
happen

Il ven 2 apr 2021, 21:34 d-nx ***@***.***> ha scritto:
