### ISSUE TITLE
Bike Calibration in Zwift 

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2310]
@cagnulein Hi Roberto, I want to calibrate my bike in Zwift. When I start the calibration process, Zwift says „Connection failure“, but the bike was successful connected via Qz. Do you have an idea what I can do to fix this?

**Comment by cagnulein** [comment]
you don't have to do any calibration on zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:31 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
@cagnulein ok, why is that?

**Comment by cagnulein** [comment]
because all the calibration thing is in qz directly

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 09:40 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Ah, very nice  👍🏻 Am 27.04.2024 um 09:42 schrieb Roberto Viola ***@***.***>:﻿
because all the calibration thing is in qz directly



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 27 apr 2024 alle 09:40 Fysibisy ***@***.***> ha

scritto:
