### ISSUE TITLE
Treadmill Beeping with Each Inclination Command

### ISSUE THREAD

**Issue by hellobensalt** [cagnulein/qdomyos-zwift#2311]
Setup: Horizon 7.4AT-03 treadmill, Pixel 6 phone running latest Android version, QZ 2.16.52

Is there any way to stop my treadmill from beeping every 5 seconds when QZ sends an inclination command to it? I realise this it probably there as a warning that the elevation is about to change, which is fine - and useful. But it also beeps when the elevation does't change, which is unnecessary.

So, if the beep could be stopped for any inclination command that is the same as the previous command, that'd be great.

However, I don't know if this is anything you can have any control over?

**Comment by cagnulein** [comment]
is this happen also on the agf app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 10:08 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
The treadmill beeps every time the user manually changes the incline.

But the AFG Pro app has no option to change the incline, so I cannot check or capture an HCI snoof using that.

**Comment by hellobensalt** [comment]
Actually, sorry, there's a Hill Climb workout in AFG Pro that I can run. There's also a custom workout, but that doesn't appear to work! (A lot of things don't work very well with Horizon equipment!)

Also, the treadmill beeps whenever there's a speed change.

**Comment by cagnulein** [comment]
so there isn't any setting in the app or in the treadmill? i suggest to cut
the wire directly :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 11:34 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
This is from Horizon....:

https://support.horizonfitness.com/hc/en-us/articles/360057964952-How-Can-I-Adjust-the-Volume-of-Machine-Beeping

And someone else suggested the same as you:

https://www.justanswer.com/fitness-equipment/4jh3p-disable-sound-beeping-every-time-change-speed.html

**Comment by cagnulein** [comment]
i guess we have our answer :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 apr 2024 alle 12:31 hellobensalt ***@***.***>
ha scritto:

**Comment by hellobensalt** [comment]
Note from Facebook:

Only send new Zwift incline commands to a treadmill (or any equipment?) when the incline changes.

If inclination NEW is same as inclination OLD, do not send.
If inclination New is different to inclination OLD, send.

**Comment by cagnulein** [comment]
could u attach a debug log from qz with the issue ? i checked the code and it should be already handled. thanks

**Comment by hellobensalt** [comment]
Setup: Horizon 7.4AT-03 treadmill, Pixel 6 phone running latest Android version, QZ 2.16.52
Settings: Incline Override Offset -2

I tried to recreate the issue here, but it wasn't exactly the same. I ran QZ with Zwift for around 6 minutes. The first 5 minutes were largely flat. I initially set my 2% baseline incline. Then, soon after, QZ put my treadmill down to 0% (equivalent to -2%) for around 4-5 minutes. The treadmill beeped every 5 seconds. Then, there was a steep climb where the incline changed regularly.

I'm not sure that first 4-5 minutes section of -2% was correct?

In the session I ran a few days ago, the treadmill beeped every 5 seconds when the incline was a non-zero setting as well. So, if there was a 2 minutes climb at 5%, the treadmill would be every 5 seconds for those 2 minutes.

This only happens with Zwift.

Thanks for your help.

[debug-Mon_Apr_29_12_56_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15145595/debug-Mon_Apr_29_12_56_10_2024.log)

**Comment by cagnulein** [comment]
i got the issue: the issues comes from the fact that you have the inclination overrides thing. I will try to add this in the control in order to don't send a writing command if the inclination is the same

**Comment by hellobensalt** [comment]
Brilliant, thanks, @cagnulein. I thought it might be something to do with that, as other people had not reported a problem.

**Comment by cagnulein** [comment]
fixed @hellobensalt if you want you can use the new apk directly https://github.com/cagnulein/qdomyos-zwift/actions/runs/8881147480

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@hellobensalt any news?

**Comment by hellobensalt** [comment]
Sorry, I was ill, then tapering for a race and away from home. Now, I'm on
a recovery week. So, I haven't had a chance to use my treadmill for 3-4
weeks.

There have been a number of updates to the app in the Playstore since I
last used it, so I will update mine to the latest version and test the
various fixes you've made.

I normally always wait for around 2 minutes during the initialisation
stage, but was rushing on the particular day I recorded that HCI snoof for
you. I hoped the problem would still be obvious. I'll record another for
you.

Many thanks.

**Comment by cagnulein** [comment]
I hope you will feel better soon!
Let me know when you will try it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 08:40 hellobensalt ***@***.***>
ha scritto:
