### ISSUE TITLE
[BUG] QZ Doesn't send send metrics to Peloton app when power sensor is selected in Accessories

### ISSUE THREAD

**Issue by RickNY** [cagnulein/qdomyos-zwift#2312]
**Describe the bug**
Normally, the Peloton app will utilize the virtual QZ device to get treadmill metrics such as speed, incline, distance, and HR if you a) use "Connect Devices" in the Peloton app and choose "Treadmill", and then select the "QZ" device listed.  Then, if the Peloton device is in a portrait orientation (Peloton limitation), it will display the treadmill's current speed, incline, distance, and HR on corresponding sections of the Peloton app.  However, if you also enable a "Power Sensor" in the Accessories and manually select a "Venu 3" Garmin smartwatch that is configured to transmit sensors during a treadmill workout, QZ no longer provides the speed, incline, distance metrics to the Peloton app - but still continues to relay the HR from the QZ virtual device.

**To Reproduce** (NORMAL behavior):
1. Ensure virtual device and virtual bluetooth are enabled.  Also, Heart Belt name is manually set to "Venu 3" in QZ
2. Allow QZ to establish connection to Horizon 7.4 tread and start a Peloton walk or run workout.  Use "Connect Device" in Peloton to select "QZ" as treadmill device.
3. Press Start on QZ once Peloton intro timer finishes
5. Treadmill starts, and Peloton app on iPad displays treadmill's current speed, incline, distance, and HR.  QZ app displays HR tile as it is updated from watch.  Cadence tile remains at 0.

**To Reproduce** (bug behavior):
1. Ensure virtual device and virtual bluetooth are enabled in QZ
2. On Venu 3 watch, ensure Treadmill activity is set to transmit sensors and go to the treadmill activity on the watch
3. in QZ, go to Power Sensor and choose "Refresh Device List", select "Venu 3" and click OK
4. Save settings and exit/restart QZ
5.  Allow QZ to establish connection to Horizon 7.4 tread and start a Peloton walk or run workout. Use "Connect Device" in Peloton to select "QZ" as treadmill device.
6.  Press Start on QZ once Peloton intro timer finishes
7.  Treadmill starts, and Peloton app on iPad displays 0.0 for treadmill speed, 0.0 for current incline, 0.00 for distance, and the current HR as reported on the watch.   Only HR updates.  In QZ, both the HR and Cadence tile update.

**Expected behavior**
Enabling the power sensor should still allow QZ to continue transmitting proper FTMS metrics to Peloton app

**Screenshots**
Attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro and iPad Pro
 - OS: iOS 17.5 (iPhone) iOS 17.4 (iPad)
 - Device: Garmin Venu 3 Smartwatch

![qz_pel_powerdisabled](https://github.com/cagnulein/qdomyos-zwift/assets/702933/23b0a489-2627-46e5-8869-3637d0f6855e)
![qz_pel_powerenabled](https://github.com/cagnulein/qdomyos-zwift/assets/702933/a463669f-2eb5-4e6f-8443-9d4218822f29)
[Power_Disabled_debug-Mon_Apr_29_08_09_01_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/15149945/Power_Disabled_debug-Mon_Apr_29_08_09_01_2024.log.txt)
[Power_Enabled_debug-Mon_Apr_29_08_05_56_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/15149948/Power_Enabled_debug-Mon_Apr_29_08_05_56_2024.log.txt)

**Comment by cagnulein** [comment]
Fixed! @RickNY stupid mistake! I will send you a new one later today/tomorrow

**Comment by RickNY** [comment]
Great – did that have anything to do with Michelle’s issue as well?

**Comment by cagnulein** [comment]
nope, her issue is about android peloton version

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 apr 2024 alle 17:00 RickNY ***@***.***> ha
scritto:

**Comment by RickNY** [comment]
I'm not sure what speed was being reported in the speed tile in both QZ as well as in Peloton -- but it was not the speed of the treadmill.  I think it may have been taking the speed portion of the speed/cadence broadcast?  The speed was all over the place, so I suspect that was the speed that was being reported.  Attaching debug log as well as screenshot again of the NRF capture from the watch.  
[debug-Mon_Apr_29_17_52_17_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/15155645/debug-Mon_Apr_29_17_52_17_2024.log.txt)
![garmin_spd_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/702933/83844d9b-b42a-4473-8d35-8c0451dcc85a)

**Comment by cagnulein** [comment]
my fault, sorry, it was about this #2121 #2141
fixed, i'm send you another one

**Comment by RickNY** [comment]
OK, just tried the new one for a quick 5 minute walk, and it seemed to work properly in all regards this time!

**Comment by RickNY** [comment]
> that's great! keep me posted in case of issues!

So -- I have not been able to catch up to this for a few weeks.. One of the things I notice is that it takes me two attempts at launching QZ, a Peloton workout, and starting a workout on the Garmin watch before QZ will report cadence - on the 2nd attempt.  Kind of strange, Im not sure why.  I am attaching two debug logs, one after the other.  The first one - no cadence was appearing -- the 2nd one, it was.  Anything stand out in the logs?  The one from 10:37 had no cadence reporting from the watch, and the one from 10:41 did.
[debug-Sun_Jun_2_10_41_52_2024.log.txt](https://github.com/user-attachments/files/15525775/debug-Sun_Jun_2_10_41_52_2024.log.txt)
[debug-Sun_Jun_2_10_37_04_2024.log.txt](https://github.com/user-attachments/files/15525776/debug-Sun_Jun_2_10_37_04_2024.log.txt)

**Comment by cagnulein** [comment]
In the first log the treadmill is not reporting any metrics. Maybe it was
something in the treadmill console? That's the original issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 giu 2024 alle 17:18 RickNY ***@***.***> ha
scritto:

**Comment by RickNY** [comment]
What is this then?
`Sun Jun 2 10:41:27 2024 1717339287166 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 3.21868"
Sun Jun 2 10:41:27 2024 1717339287167 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/treadmill.cpp static double treadmill::treadmillInclinationOverride(double) treadmillInclinationOverride 0.5 5
Sun Jun 2 10:41:27 2024 1717339287168 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Inclination: 0.5"
Sun Jun 2 10:41:27 2024 1717339287169 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current KCal: 5.59863"
Sun Jun 2 10:41:27 2024 1717339287170 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.0476519"
Sun Jun 2 10:41:27 2024 1717339287229 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) " << 06 4b"
Sun Jun 2 10:41:27 2024 1717339287231 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "Current heart: 75"`

**Comment by cagnulein** [comment]
Ops sorry I'm on the phone and I didn't spot this, let me check agaib

**Comment by cagnulein** [comment]
Ok the issue in the first log is that the watch it wasn't broadcasting itself

In the first one this is missing

Sun Jun 2 10:41:54 2024 1717339314148 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::deviceDiscovered(const QBluetoothDeviceInfo &) "Found new device: " "Venu 3" " (" "00:00:00:00:00:00" )   0 ":" 0 ("{0000180d-0000-1000-8000-00805f9b34fb}") "{9da88ea3-c03b-aa49-b4eb-fecd16414f85}"

**Comment by RickNY** [comment]
So, I think -- the watch may have to be on that activity (but not yet started) when QZ starts so that QZ establishes the BT connection with it before starting in order to pick up the cadence. The watch is transmitting HR and Cadence when just sitting idle but not yet started - it's just not recording it as one of the watch's workouts until starting it on the watch. I'll see if this sequence holds true over the next few days.

**Comment by cagnulein** [comment]
Makes sense.
Let me know how it goes

Il giorno dom 2 giu 2024 alle 19:27 RickNY ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi @RickNY any news?

**Comment by RickNY** [comment]
So, yes. This has been working properly, but the correct order of starting up must be used. First, the treadmill should be on and idle, and the Treadmill activity on the watch must be selected - but not yet started.  This will start broadcasting HR, and cadence. Then launch QZ.. QZ will start live showing the HR tile and if you move around a little will report cadence as well. Allow time for QZ to finish its other connection with the Horizon Bluetooth and launch Peloton class. I then start the watch activity 3 or 4 seconds before the pre-countdown and start QZ and everything reports properly.

**Comment by cagnulein** [comment]
Ok at least it's working. Thanks for sharing the right procedure

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 26 giu 2024 alle 12:53 RickNY ***@***.***> ha
scritto:
