### ISSUE TITLE
[BUG] Mismatch Cadence, power, speed 

### ISSUE THREAD

**Issue by juanmre** [cagnulein/qdomyos-zwift#2313]
**Describe the bug**
The Cadence and Power received by swift may not be accurate as sometimes im in a 100+ cadence trying to generate 120W power and my feet are bouncing from the pedals. (used an iPhone for the QZ app)

In a fresh install in android to send data to Garmin, I'm seeing mismatching data between what QZ APP displays, what Garmin receives and what Zwift receives... Power and Cadence seem right, but Speed and distance are way off.

Im adding a long exercise from this morning Swift link and Garmin link (both from garmin app) and a third attempt later today only 5 minutes with the QZ .fit file (after joining the beta and finding the file in Android 14). Unfortunately in this last attempt my Garmin lost the power and cadence sensor data.

**To Reproduce**
1. Connect Echelon EX-3 with QZ app in Android
2. Start activity in Garmin, connect Power and Spd/Cadence sensors
3. Open Zwift, connect power, cadence and speed sensors
4. Start a ride (without ERG option in QZ app)

If repeated without Garmin and with ERG enabled selecting a Zwift training, it will be hard to keep the power because pedals resistance is not enoug and feet will be bouncing.

**Expected behavior**
In the first attempt, Zwift ride and no ERG, Zwift screen seems reasonable but speed recorded by Garmin will be excessive...
In the second exercise, Zwift training with ERG, is hard to keep up with the power because pedal resistance is not enough

**Screenshots**
Sharing my setup an some off-data shown

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Android 14, Samsung A35 5G
 - QZ app: 2.16.52 (joined Beta)
 - Ipad os 17.4.1. Zwift 1.63.0
 - Garmin Epix Pro SW 16.22

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
Will add debug file in next excercise session..
[Mon Apr 29 11_56_51 2024.fit.zip](https://github.com/cagnulein/qdomyos-zwift/files/15153244/Mon.Apr.29.11_56_51.2024.fit.zip)
 
![Screenshot_20240429_115123](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/95919b5f-1154-430c-a48c-65ad41fa2086)
![Screenshot_20240429_123200](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/8dceb1bd-1835-42fc-bc48-c2f396a120f2)
![Screenshot_20240429_123255](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/017c9cc6-dc94-4d20-afb9-32352bd5d6a2)
![Screenshot_20240429_123313](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/63d3aacf-7e0c-4b21-b013-644413a56d45)
![Screenshot_20240429_123230](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/0f9c0475-9441-4666-a9ad-e1938382e6e6)
![Screenshot_20240429_123239](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/75740d6f-8d34-4c97-aec4-d646be05fd0d)
![Screenshot_20240429_123328](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/ea71a645-2bfc-4435-a346-fd6b202de80a)
![Screenshot_20240429_123338](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/baf90a6d-6f68-4ee1-9755-c8aeccc4f56c)
![Screenshot_20240429_123536](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/3788210b-6d11-49a2-9a96-6991d7c11c33)
![Screenshot_20240429_123431](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/c5fc207c-4c87-4a3e-81f6-bda70cafd5ad)
![IMG_0656](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/262625ae-64bd-4330-8848-1d710fa08aa8)
![Screenshot_20240429_122548_ANT Tester](https://github.com/cagnulein/qdomyos-zwift/assets/46355352/d4d58876-2ac0-49e7-aeaa-ec8b104274e1)

5 min recent exercises (both links from Garmin) Power, cadence and speed disconnected from Garmin
- Zwift 3.32km distance, reasonable: Check out my virtual ride activity on Garmin Connect. [#beatyesterday] (https://connect.garmin.com/modern/activity/15139149502)
- Garmin 9.01km distance, not real: Check out my indoor cycling activity on Garmin Connect. [#beatyesterday](https://connect.garmin.com/modern/activity/15139164190)

Earlier 45 min activity (from the .Fit file attached)
- Zwift, 18.12 km distance, reasonable: Check out my virtual ride activity on Garmin Connect. [#beatyesterday](https://connect.garmin.com/modern/activity/15135449164)
- Garmin 78.07 km distance, not real: Check out my indoor cycling activity on Garmin Connect. [#beatyesterday](https://connect.garmin.com/modern/activity/15135437331)

**Additional context**
Feel free to request any more data that could help

**Comment by cagnulein** [comment]
first of all read this,
https://robertoviola.cloud/2024/01/27/dispelling-the-myth-speed-variations-between-qz-and-zwift-are-not-a-device-issue/

garmin and qz must match if the wheel diameter is set to 100mm on the
garmin. does it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 apr 2024 alle 20:51 juanmre ***@***.***> ha
scritto:

**Comment by juanmre** [comment]
Hi, thanks for your attention... hold on, I'm thinking I may need to calibrate the speed sensor in my Garmin... let me look in to it and get back to you here...

thanks!

**Comment by cagnulein** [comment]
yeah just set the wheel diameter to 100mm and you are good to go
also enable the speed based on power setting in the bike setting in qz in
order to have a similar speed to zwift as referenced in the link
i'm going to bed soon

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 apr 2024 alle 20:59 juanmre ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@juanmre are we OK with this?
