### ISSUE TITLE
[BUG] Stages Solo Indoor Cycle Resistance Glitch

### ISSUE THREAD

**Issue by Kevans34** [cagnulein/qdomyos-zwift#2314]
**Describe the bug**
The resistance glitches between 1-15 units while riding without any manual changes. 

**To Reproduce**
1. Connect to bike via Bluetooth
2. Begin pedaling 
3. See resistance skip around 

**Expected behavior**
The resistance should not change without me manually changing it. 

**Screenshots**

https://github.com/cagnulein/qdomyos-zwift/assets/168491076/447502f2-2bc9-4e98-a694-3ebe464369c0

**Desktop (please complete the following information):**
Using Qz app on my iPhone iOS version 17.4.1

**Smartphone (please complete the following information):**
 -iphone xs, iOS version 17.4.1

**Append a debug log**
[debug-Mon_Apr_29_17_54_36_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15156277/debug-Mon_Apr_29_17_54_36_2024.log)
[debug-Mon_Apr_29_17_30_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15156278/debug-Mon_Apr_29_17_30_47_2024.log)
[debug-Mon_Apr_29_17_56_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15156280/debug-Mon_Apr_29_17_56_26_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
There doesn’t appear to be any difference between the resistance and peloton resistance outputs. I believe this is because stages doesn’t have a typical resistance range. It’s has gears and a knob for micro adjustments.

**Comment by cagnulein** [comment]
hi @Kevans34 log checked, as I said your bike doesn't report the resistance, so QZ is calculating it based on your wattage and cadence. Since cadence and wattage are changing fast also the resistance is effected. The only thing that I can do is adding a average on the resistance (maybe 5s of average is enough to stabilize it).
Let me know what do you think

**Comment by cagnulein** [comment]
@Kevans34 actually I'm using that setting only to the wattage tile. My idea was to try to extend this also the resistance to check if it's better if you agree. Try to disable the "power average 5 second" and see how bad is the wattage tile compared to the "power average 5 second" turned on. It should be the same on the resistance.
Probably the best way to see this is trying :)

I can try to simulate the implementation with chat gpt using your log, hold on

**Comment by cagnulein** [comment]
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/2e607eb8-20a3-4fe3-8347-c51bfb5723e2)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/4f7efb93-d34f-4706-8bed-57a2a31faf8b)

not so better...is your bike showing the resistance somehow?
another idea is to stabilizing it withing a range, for example 5 levels, so show a different resistance value only if it's outside a range of 5 or 10 for example

**Comment by cagnulein** [comment]
@blautob are you still using the patch that I did for you in the #1236 ? I would like to implement for @Kevans34 as well since the code is the same. Let me know, thanks!

**Comment by cagnulein** [comment]
@Kevans34 let me know if we want to proceed with with this anyway
