### ISSUE TITLE
QZ Stops Receiving Data from Horizon 7.8AT Treadmill

### ISSUE THREAD

**Issue by Nansterz** [cagnulein/qdomyos-zwift#2316]
**Describe the bug**
I am using the QZ app on an iPad, running the Peloton app from an iPhone. I also have a heart rate monitor that is connecting to QZ. Everything will connect with no issue, then I can see the heart rate, treadmill speed, incline, etc. Eventually, I'll notice that when changing incline or speed, it's no longer reflected in the QZ app. The incline and speed is frozen in the app and will continue to show for the duration of the run. These numbers that are frozen, become frozen in the Peloton app as well. This is an intermittent issue. 

**To Reproduce**
1. Start the Horizon 7.8AT treadmill and use the 'USER 1' account.
2. Start the Peloton run class, pause.
3. Open the QZ app and wait for it to connect.
4. In QZ, it detects the Peloton class, and I choose 'No' to not follow the speeds of the class.
5. QA starts to show the treadmill speed, pause QZ.
6. Connect QZ as the treadmill in Peloton
7. Unpause the Peloton class, skip the intro
8. Unpause QZ
9. Start the run. It is working at this point, I can adjust speed and incline and they are reflected in QA and in the Peloton app
10. Eventually, I notice that the QZ app is running, time is elapsing, heart rate is still correct and reflecting in Peloton app, but if I change the speed or incline on the tread, it no longer updates in the app. Its now stuck at the speed and incline for the remainder of the class.

**Expected behavior**
I expect to be able to change the speed or incline and have the reflected in QZ and see the same in the Peloton app.

**Screenshots**
In the highlighted section, I incrementally increased my speed until the end of the class, a little at a time until the end. You can see that it's completely flat.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/168682757/8a0dd15d-bcc7-42e5-badb-4afd05650c09)

**Desktop (please complete the following information):**
 - Device: iPad 9 (unning QZ app)
 - OS: iPadOS
 - Version 17.4.1

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro (running Peloton app)

**Append a debug log**
[debug-Tue_Apr_30_09_25_54_2024.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/15181476/debug-Tue_Apr_30_09_25_54_2024.log.txt)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @Nansterz log  checked. You have a disconnection from the treadmill. It could be due to a lot of factors. We need to exclude one subject at a time: maybe try without the heart band and see if it's the same.

Did you already try the agf app to see if you see the same issue?

Let me know

**Comment by cagnulein** [comment]
@Nansterz any news?
