### ISSUE TITLE
[BUG]Tile are registering 

### ISSUE THREAD

**Issue by Shanenewton** [cagnulein/qdomyos-zwift#2317]
**Describe the bug**
Tiles not registering, only the incline tile works

**To Reproduce**
![inbound2418961875656009497](https://github.com/cagnulein/qdomyos-zwift/assets/160474542/ca387434-6c4c-433d-a084-be92573ad5b5)
![inbound2107353150939243649](https://github.com/cagnulein/qdomyos-zwift/assets/160474542/28a214cc-055b-4e35-9a9a-989af7896497)
![inbound6766249625162224276](https://github.com/cagnulein/qdomyos-zwift/assets/160474542/a7280036-c546-4546-8717-42057b2aa26b)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Shanenewton i need a debug log as described here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F to understand your issue

**Comment by cagnulein** [comment]
@Shanenewton any news?

**Comment by Shanenewton** [comment]
No, not yet. I will give ago today

**Comment by Shanenewton** [comment]
The last 4 rides .all tiles are displaying data but cannot seem to get the
wahoo ticker heartrate chestband to connect not to much of an issue but
would nice to have.
Thanks

**Comment by cagnulein** [comment]
great! do you set the ticker HR to the heart rate setting in qz?
