### ISSUE TITLE
REQ : "Workout uploaded to Strava"

### ISSUE THREAD

**Issue by d-nx** [cagnulein/qdomyos-zwift#232]
Would it be possible to have a popup at the end of your workout confirming that your workout was uploaded to Strava?

**Comment by d-nx** [comment]
Speaking of Strava: I LOVE how QZ now names the workout with the Peloton name. SO COOL.

**Comment by cagnulein** [comment]
Yeah i guess there is another issue with the same subject ;)

Il ven 2 apr 2021, 21:53 d-nx ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done with https://github.com/cagnulein/qdomyos-zwift/commit/e94e030a001756ad63ac6eba3d57c91cfa0c54c6
