### ISSUE TITLE
[BUG] Bike not reading metrics

### ISSUE THREAD

**Issue by effecet** [cagnulein/qdomyos-zwift#2320]
Bike: bowflex velocore 19'
Android 9

Bike not reading stats or metrics. Speed, heart rate, etc. Not being detected.

Logs attached. 
[debug-Sun_May_5_16_15_16_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15214203/debug-Sun_May_5_16_15_16_2024.log)

**Comment by cagnulein** [comment]
hi @ing-federico-cetraro could you please download the free app nrfconnect and show me a screenshot about the bike from this app.
thanks

**Comment by cagnulein** [comment]
the fact the c9 is not working there neither it seems a problem  on the bike or on the tablet. do you have also another device to test?

**Comment by effecet** [comment]
But it does work with the original setup (factory apps)

**Comment by cagnulein** [comment]
do you mean the schwinn app or qz with default settings?

**Comment by cagnulein** [comment]
@effecet Any news?
