### ISSUE TITLE
[BUG] Exhelon row sport (200e) won't connect 

### ISSUE THREAD

**Issue by Phyr4** [cagnulein/qdomyos-zwift#2321]
Just got an Echelon row sport 200e, can't get it to connect on Bluetooth. Bluetooth is on, and my phone can see the rower, but the app doesn't. 

Android pixel 7

**Comment by cagnulein** [comment]
Hi! Did you already update the app to the beta?
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 6 mag 2024 alle 06:39 Phyr4 ***@***.***> ha
scritto:

**Comment by Phyr4** [comment]
Just updated to the 2.16.52 version and same issue

**Comment by cagnulein** [comment]
share a screenshot of the rower on qz so i will add it. thanks
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 6 mag 2024 alle ore 06:48 Phyr4 ***@***.***> ha
scritto:

**Comment by Phyr4** [comment]
a screenshot of what specifically? The rower doesn't show up on qz

**Comment by cagnulein** [comment]
install the free app nrfconnect and show me there your rower, i will be
able to add then
thanks
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 6 mag 2024 alle ore 06:59 Phyr4 ***@***.***> ha
scritto:

**Comment by Phyr4** [comment]
I figured out the problem was I didn't enable enough permissions. I had the
location, microphone, and camera permission disabled. Turned them on and qz
found the rower.

Sorry about that, but thank you for the quick response

**Comment by cagnulein** [comment]
That's great!
