### ISSUE TITLE
2024 Spirit XT485 Treadmill not communicating correctly with QZ app[BUG]

### ISSUE THREAD

**Issue by GasMast3r** [cagnulein/qdomyos-zwift#2323]
**Describe the bug**
I recently purchased the new 2024 model Spirit XT485. Using iPhone SE (2020 model) and the QZ app, I'm unable to get the app to work correctly. I'll turn the treadmill on. Wait and then turn the QZ app on. It correctly identifies the treadmill and connects. The treadmill immediately starts up the premade "Cardio" workout built into the treadmill and counts down to start when it connects. It shows the Bluetooth symbol on the treadmill saying it is connected to a device. None of the tiles work in the app when this happens and it shows zero for speed and incline, even if I change the speed or incline on the treadmill directly . I found that if I let it run but force quit the app, and reopen it while the treadmill is running this program, then it will now show the speed and incline correctly, even if I change them. It still won't let me control the speed or incline from the app. I tried to upload a ZWO run workout on one of my attempts to see if I could decide the program it runs when it connects. It only runs the same preset cardio workout from the treadmill. 

**To Reproduce**
Attempt to connect QZ app to Spirit XT485 treadmill

**Expected behavior**
Once the app opens and connects to the treadmill Inexpected that the app will gain control, allowing me to change speed and incline or upload a custom ZWO file for the QZ app to run.

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020 model 
 - OS: iOS 17.4.1

**Append a debug log**
 6 files attached
[debug-Mon_May_6_19_56_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228445/debug-Mon_May_6_19_56_10_2024.log)
[debug-Mon_May_6_19_59_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228447/debug-Mon_May_6_19_59_35_2024.log)
[debug-Mon_May_6_20_00_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228448/debug-Mon_May_6_20_00_05_2024.log)
[debug-Mon_May_6_20_00_45_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228449/debug-Mon_May_6_20_00_45_2024.log)
[debug-Mon_May_6_20_01_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228450/debug-Mon_May_6_20_01_28_2024.log)
[debug-Mon_May_6_20_02_03_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15228451/debug-Mon_May_6_20_02_03_2024.log)

**Comment by cagnulein** [comment]
ok i will try to add this firmware as well and i will send you a new beta .


send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by cagnulein** [comment]
sent a new version! let me know!

**Comment by GasMast3r** [comment]
The new version fixed a lot. The app connects to the treadmill right away. It doesn’t cause the treadmill to auto start a workout that is built into the treadmill. The tiles change with the treadmill now. I can change the incline from the app, but I can’t change the speed yet. 

I tried to use a custom workout that I made from zwiftworkout.com as well as one of the premade ones in the app without any luck. I’ve attached 2 logs to try and help.


[debug-Tue_May_7_19_53_53_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15242639/debug-Tue_May_7_19_53_53_2024.log)
[debug-Tue_May_7_19_46_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15242640/debug-Tue_May_7_19_46_07_2024.log)
[debug-Tue_May_7_19_56_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15242641/debug-Tue_May_7_19_56_07_2024.log)

**Comment by cagnulein** [comment]
@GasMast3r log checked: from the spirit app are you able to change the speed from the app itself?

**Comment by GasMast3r** [comment]
I haven't had a chance to test, but now that you bring it to my attention I think I'm reading that the Spirit+ app doesn't change speed "for safety reasons". I'll try and confirm this tomorrow. That will be disappointing if that is the case.

**Comment by cagnulein** [comment]
that was my thought as well :(
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 8 mag 2024 alle ore 06:37 GasMast3r ***@***.***>
ha scritto:

**Comment by GasMast3r** [comment]
I spoke with Spirit who says the app was disabled from controlling the treadmill speed for safety. I was unable to control it from the app. Do you think there is any workaround?

**Comment by cagnulein** [comment]
the only workaround is soldering 2 wires to the speed up and speed down button on the console and command them by qz from pc. i already this for the bowflex treadmills that have the same issue. let me know if you are interested

**Comment by GasMast3r** [comment]
Yes, if you have a walkthrough or explanation, this is a project I'd consider doing

**Comment by cagnulein** [comment]
yes sure 
have a look at this

https://github.com/cagnulein/qdomyos-zwift/issues/525

in few words: you have just to solder the wires to the buttons to a relè boards and then qz will do the magic!
