### ISSUE TITLE
[BUG] last version

### ISSUE THREAD

**Issue by jeremy10tie** [cagnulein/qdomyos-zwift#2325]
Phone : Poco X3 pro
Android : 14 QPR2(crdroid rom)
Qz : 2.16.53

Hello , there is a problem in the latest version, I wanted to use today but unfortunately I cannot, when I open qz it connects well to the bike (bike 900 Domyos) but the application closes just after being connected  on the bike. 
[debug-Wed_May_8_12_40_02_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15247777/debug-Wed_May_8_12_40_02_2024.log)

**Comment by cagnulein** [comment]
That's strange, everything seems nominal. Are you able to share a bug
report from android with the crash?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 8 mag 2024 alle 12:50 jeremy10tie ***@***.***>
ha scritto:

**Comment by jeremy10tie** [comment]
a video which shows, but what is strange remains at the bottom of the task, but when it closes the bike is on pause
https://github.com/cagnulein/qdomyos-zwift/assets/20781131/e76b75d3-83d1-4e43-a56a-b43d23fe1a47

**Comment by cagnulein** [comment]
Ok Create a bug report from android and I should be able to see the real issue
Thanks

**Comment by jeremy10tie** [comment]
I did a logcat with adb
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/15248327/logcat.txt)

**Comment by cagnulein** [comment]
thanks @jeremy10tie could you please upload it again? it's a 0 byte file. thanks

**Comment by jeremy10tie** [comment]
I changed

**Comment by cagnulein** [comment]
ok found the error

```
05-08 14:04:00.072 17744 17744 F DEBUG   :       #04 pc 00000000003c4988  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (QByteArray::at(int) const+84) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
05-08 14:04:00.072 17744 17744 F DEBUG   :       #05 pc 0000000000b272f4  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (domyosbike::GetKcalFromPacket(QByteArray const&)+52) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
05-08 14:04:00.072 17744 17744 F DEBUG   :       #06 pc 0000000000b25884  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (domyosbike::characteristicChanged(QLowEnergyCharacteristic const&, QByteArray const&)+2560) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
05-08 14:04:00.072 17744 17744 F DEBUG   :       #07 pc 0000000000b2d684  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QLowEnergyCharacteristic const&, QByteArray const&>, void, void (domyosbike::*)(QLowEnergyCharacteristic const&, QByteArray const&)>::call(void (domyosbike::*)(QLowEnergyCharacteristic const&, QByteArray const&), domyosbike*, void**)+144) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
05-08 14:04:00.072 17744 17744 F DEBUG   :       #08 pc 0000000000b2d5e4  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (void QtPrivate::FunctionPointer<void (domyosbike::*)(QLowEnergyCharacteristic const&, QByteArray const&)>::call<QtPrivate::List<QLowEnergyCharacteristic const&, QByteArray const&>, void>(void (domyosbike::*)(QLowEnergyCharacteristic const&, QByteArray const&), domyosbike*, void**)+76) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
05-08 14:04:00.072 17744 17744 F DEBUG   :       #09 pc 0000000000b2d4fc  /data/app/~~KH-bnObVQWQ1HwLE-AoioA==/org.cagnulen.qdomyoszwift-M7tFlXOpc3u4zLaK3_xaRA==/lib/arm64/libqdomyos-zwift_arm64-v8a.so (QtPrivate::QSlotObject<void (domyosbike::*)(QLowEnergyCharacteristic const&, QByteArray const&), QtPrivate::List<QLowEnergyCharacteristic const&, QByteArray const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)+176) (BuildId: cec8016eac46ff36e1a652efc76a2985dc67c3ae)
```

let me try to understand the cause

**Comment by cagnulein** [comment]
ok it should be about the #2232 

can you try to enable the setting "Disable KCal from Machinery" under the heart rate options and see if it helps?

let me know!

**Comment by cagnulein** [comment]
anyway i just fixed it, i'm pushing it to the store as well. anyway with that setting enabled you should fix the crash. thanks for the feedback!

**Comment by jeremy10tie** [comment]
> ok it should be about the #2232
> 
> can you try to enable the setting "Disable KCal from Machinery" under the heart rate options and see if it helps?
> 
> let me know!

That's right
