### ISSUE TITLE
[BUG] Treadmill won't connect via bluetooth

### ISSUE THREAD

**Issue by ctran4347** [cagnulein/qdomyos-zwift#2331]
**Describe the bug**
Xterra TR260 treadmill won't connect via QZ app. Treadmill is able to connect to a Samsung S24 Ultra and a Samsung Tab S8+ through Zwift and Kinomap. Kinomap's auto inclination works with the Xterra TR260. It seems to just cycle through available bluetooth connection and not doing anything with the XTerra TR260 bluetooth.

**To Reproduce**
1. Open QZ app
2. Wait for bluetooth to connect (it doesn't) or manually go to settings and select XTerra TR260 (still doesn't connect)

**Expected behavior**
A bluetooth connection to be made.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - Device: Samsung S24 Ultra/ Samsung Tab S8+
 - OS:  Android 14/One UI 6
 - App Version [e.g. 22]: 2.14.0 

**Append a debug log**
  
Can't find /android/data/org.cagnulein.qdomyoszwift/ folder on device using: https://play.google.com/store/apps/details?id=com.marc.files
  
**Additional context**

**Comment by cagnulein** [comment]
hi! join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and then you should see the log on the /documents/qz

Let me know!

**Comment by ctran4347** [comment]
Hi! I was able to get the logs and compressed the entire folder for you 

[QZ.zip](https://github.com/cagnulein/qdomyos-zwift/files/15294443/QZ.zip)

Surprisingly when I downloaded the beta version, it immediately connected to my smart bike right away (Renpho AI Smart Bike), but still doesn't connect to the Xterra TR260 even when manually setting the bluetooth device.

**Comment by cagnulein** [comment]
perfect, got the issue! in order to solve it, could you please download the free app nrfconnect and send me a screenshot about the treadmill from this app?
Thanks!

**Comment by ctran4347** [comment]
Here are the details that the nrfconnect app gave me for the treadmill. Let me know if you need more information 

![received_970680914610141.jpeg](https://github.com/cagnulein/qdomyos-zwift/assets/13368801/811ad478-f10a-46ab-af40-5aed5692191f)

**Comment by cagnulein** [comment]
perfect @ctran4347 setup qz in this way
- manual device to xterra
- treadmill settings, ftms treadmill set to xterra and press ok and restart QZ

let me know if it's ok!

**Comment by ctran4347** [comment]
I was able to get the treadmill to connect via bluetooth with the steps above. It's able to pick up the treadmill speed and inclination if I change it manually on the treadmill along with the automated Zwift inclination settings. I assumed I had to fill out the Zwift section in settings and toggle Climb Portal?

**Comment by cagnulein** [comment]
@ctran4347 you need just to fill the zwift credentials in qz. Let me know

**Comment by cagnulein** [comment]
@ctran4347 any news?

**Comment by ctran4347** [comment]
Sorry for the late response! I was able to get it to work with the instructions you specified!

**Comment by cagnulein** [comment]
Glad to hear it!
remember to rate the app on the store! It means a lot to me!
Thanks!

Il giorno gio 13 giu 2024 alle 19:17 Christian Tran <
***@***.***> ha scritto:
