### ISSUE TITLE
[BUG] Echelon EX5s no telemetry

### ISSUE THREAD

**Issue by Kasdal** [cagnulein/qdomyos-zwift#2337]
**Describe the bug**
Connected to Echelon EX5s but no telemetry is being sent or received on the app on Windows. 

**To Reproduce**

**Expected behavior**
Expected to see data on app when i move the pedals on bike.

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/36207533/bfc2fcb1-d725-482d-8190-c43553c3795d)

**Desktop (please complete the following information):**
 - OS: Windows 11
[Adebug-Thu_May_16_20_23_29_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15340016/Adebug-Thu_May_16_20_23_29_2024.log)

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi the problem is that you set the echelon bike to ftms bike in the bike
settings. Remove it
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 mag 2024 alle 21:33 Milan Ples ***@***.***>
ha scritto:

**Comment by Kasdal** [comment]
Yep that did it. 
Thank you for speedy response.
