### ISSUE TITLE
Nordictrack S22i    Incline/resistance problems

### ISSUE THREAD

**Issue by patricksmith1346** [cagnulein/qdomyos-zwift#2339]
I am Using a Nordictrack S22i bike(model NTEX02121.5) for zwift 
I am using QZ app on Windows PC as well as on my iphone IOS.  

The app relays the bikes real time workout info from my S22i to QZ and then to Zwift correctly on both the platforms.  

However from the Windows PC QZ application i can not control the Incline or Resistance of the bike.  

From my iPhone I can control the Incline (not resistance) but it takes about 10 fast clicks on either the + or - symbol to go up or down by the normal 0.5%.  

ADB Remote is enabled on both PC and IOS versions of QZ 
 
USB debugging is enabled on the physical NordicTrack s22i tablet settings

**Expected behavior**

I would like to be able to have the resistance/incline auto adjust like a smart trainer on this nordictrack s22i if possible.      (Would be cool if the resistance setting could be controlled instead of incline, even though increasing incline would increase resistance. )

Windows PC = HP omen windows 11 home edition
iPhone IOS = iPhone 15 up to date on all updates 

[debug-Fri_May_17_23_34_21_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15360393/debug-Fri_May_17_23_34_21_2024.log)   -- IPHONE

[debug-Fri_May_17_23_36_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15360397/debug-Fri_May_17_23_36_24_2024.log)   -- Windows PC 

Thanks

**Comment by cagnulein** [comment]
For the ios version : I just sent you a new version, give it a try and let
me know if it's better

For the pc version : I can't see in the log the pressure of the plus
button. Can you do it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 mag 2024 alle 09:05 patricksmith1346 <
***@***.***> ha scritto:

**Comment by patricksmith1346** [comment]
Alright tried the new QZ version on iPhone IOS . The inclination + - button will now raise or lower with one click in the app.  👍


I will load up pc and resend a log shortly .  Thanks

**Comment by cagnulein** [comment]
Awesome, thanks for the update!


Il giorno sab 18 mag 2024 alle 18:08 patricksmith1346 <
***@***.***> ha scritto:

**Comment by patricksmith1346** [comment]
Just tried PC 

incline not working from application 

i manually went up and down on incline on the bike then tried in app tile + -  .

[debug-Sat_May_18_09_36_37_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15366116/debug-Sat_May_18_09_36_37_2024.log)

**Comment by cagnulein** [comment]
Thanks, I will check it in the next few days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 mag 2024 alle 18:41 patricksmith1346 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
good news @patricksmith1346 I guess I fixed. It's building here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9160141069
You will see the new build output at the bottom of the page in 30 minutes. Let me know!

**Comment by patricksmith1346** [comment]
Thanks I noticed that recently.  I appreciate your help .  😎

**Comment by cagnulein** [comment]
Ok let me know when you will try!

**Comment by patricksmith1346** [comment]
ok i just tried on the pc .  The incline tiles will not let me control incline from pc .  however i have noticed some auto inclination during my last Zwift run.

**Comment by cagnulein** [comment]
Could you share a fresh debug log? I set a 4 seconds delay from one to another inclination change due to the fact that the inclination motor is slow on your bike, you can set this to 0 in the settings if you want

**Comment by patricksmith1346** [comment]
[Uploading debug-Mon_May_20_22_52_27_2024.log…]()

**Comment by cagnulein** [comment]
hi @patricksmith1346 the log is corrupted, could you please send it again? you have to wait the finish of the upload before pushing the comment button. thanks

**Comment by patricksmith1346** [comment]
my bad 

[debug-Mon_May_20_22_52_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15385625/debug-Mon_May_20_22_52_27_2024.log)

**Comment by cagnulein** [comment]
this is from the 2.16.54 version. you need to download the newer one from the link that I sent you yesterday.
direct link https://github.com/cagnulein/qdomyos-zwift/actions/runs/9160141069/artifacts/1519524066

**Comment by patricksmith1346** [comment]
[debug-Mon_May_20_23_54_07_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15385820/debug-Mon_May_20_23_54_07_2024.log)

the incline can now be controlled from the tile in QZ pc 
i went on quick 5 min free ride in Zwift and it seems to be auto adjusting the incline smoothly!  
i appreciate all the help! 
thanks 

let me know if you need any more info on my end

**Comment by cagnulein** [comment]
that's great! so we can consider the ticket closed?

**Comment by patricksmith1346** [comment]
Ya.  Thanks 🙏
