### ISSUE TITLE
[BUG] QZ app not connecting correctly to Zwift 

### ISSUE THREAD

**Issue by FlooKo24** [cagnulein/qdomyos-zwift#2340]
**Describe the bug**
I have Domyos EB 900 and was using app for a week now. Sometimes it bugged but I managed to get it going and everything was ok. But yesterday when I tried to have a ride like usually app on PC stopped to recognize my resistance level. Moreover it can see "power meter" and "cadence meter" but they actually at 0. And when I join the ride - Connection Failure. I used Pixel 8 and PC before. Tried with Samsung S20 - same story. Tried with Samsung and Pixel - same story. Only way I got it going when I launch QZ on Samsung and Zwift on Pixel and connect it not as "wahoo traineer" but as Samsung s20. I dunno what changed because everything worked good before.

**To Reproduce**
1. Launch Zwift
2. Launch bike and QZ
3. Tried to lauch QZ before Zwift - zwift doesn't see qz at all.

**Expected behavior**
I want Zwift on PC to see QZ app and it stats as it was before

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/139243578/652c344d-b854-4954-abd4-ba89f0668fb2)

**Desktop (please complete the following information):**
 - OS: Android for QZ and Zwift. Also Windows on PC
 - 14 android, 11 windows

**Smartphone (please complete the following information):**
Pixel 8 (android 14), Samsung S20(android 13), PC with windows 11

**Append a debug log**
 I tried like in guide but I don't even have a folder documents/QZ

**Comment by cagnulein** [comment]
Hi be sure that your pc and android are on the same wifi network and also
same channel. Also rename your phones in just 4 letters names like "bike"
and reboot the phone. You can avoid all of these setup issues using the qz
pc version
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 mag 2024 alle 13:08 FlooKo24 ***@***.***> ha
scritto:

**Comment by FlooKo24** [comment]
Where can I find QZ pc version? Today I bought and used iOS and and it worked fine. Interested in PC one now

**Comment by cagnulein** [comment]
Here
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 19 mag 2024 alle 00:16 FlooKo24 ***@***.***> ha
scritto:

**Comment by FlooKo24** [comment]
PC version connects but then app freezes. Any I will use QZ from iphone than. App is good and thank you, i even bought it 2 times haha.

I have a small question. Whats the formula for wattage output? Domyos 900 have 15 resistance levels for example. Hows it calculated for 90rpm for each resistance for 80kg man for example? It feels like 7-8 res level 90rpm is for sure like takes doubles watts to push compared to 3-4 for example. Or more? Or am I mistaken? I want to calibrate my bike properly and just get the idea how it works

**Comment by cagnulein** [comment]
Try this so https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary-no-python.zip

Remember to pair first your fitness device on the windows Bluetooth settings.

Domyos bikes doesn't sent wattage by Bluetooth so I'm calculating them using a static table based on cadence and resistance. You can use the wattage gain setting to change this table

Let me know

**Comment by FlooKo24** [comment]
Roberto, hello! Hope you doing fine. 

Can you please provide me info how much wattage Domyos 900EB according to your table should output at:
80, 90, 100 cadences on 4 and 5 resistance levels? Im trying to figure out if I need some adjustments for those. 
Would be really, really thankful for your answer

**Comment by cagnulein** [comment]
This is the formula under resistance 8

((10.39 + 1.45 * (resistance - 1.0)) * (exp(0.028 *
(currentCadence().value()))));


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 26 mag 2024 alle 22:31 FlooKo24 ***@***.***> ha
scritto:

**Comment by FlooKo24** [comment]
Thank you very much, Roberto!

**Comment by cagnulein** [comment]
@FlooKo24 are we OK with this?
