### ISSUE TITLE
Bug connexion between Treadmill elite 900 nordictrack / QZ application on IOS/ Zwift

### ISSUE THREAD

**Issue by Toniok6** [cagnulein/qdomyos-zwift#2341]
**Describe the bug**
No data on QZ app (ios) / No remote controle from QZ app / No remote from Zwift.

Treadmill on permanent privilege mode (android V7) - QZ companion installed by method 2 and not by method ".bat" - QZ app (2.16 beta) on iphone 11 ios  - Zwift on mac
Once tredmill is on, QZ companion running, starting IFIT in manual, the treadmill is running and no data is displayed on the QZ app screen, also the button of QZ app are not working.
Wifi is the same, treadmill is visible on QZ app, IP is the same but the model elite 900 doesn't exist on QZ app and QZ companion so I choose : C1750 on qz companion, and S25 ( by default ) on qz app.
All the settings are the default settings but maybe something wrong by mistake..?

Thanks in advance for your advice

**Append a debug log**
[debug-sam__mai_18_18_49_42_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15365768/debug-sam__mai_18_18_49_42_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
The issue is that no frames are leaving the fitness device. Maybe your
router is filtering them. Did you try to use your phone As the access point
for your fitness device?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 mag 2024 alle 17:19 Toniok6 ***@***.***> ha
scritto:

**Comment by Toniok6** [comment]
Hi, thanks for your advise but still the same, I change of routeur and also try the iphone as access point and no change. 
But at the first test of the beta I get the data and after few changes of speed I lost the data and it has never work again. 
I finally reinstall QZ app on iphone to try without all my changes but still nothing. As the model elite 900 nordictrack is not on the list of QZ companion and QZ app which one do you recomand to enable ? I enable C1750 on QZ comp and S25 on QZ app. May I have to reinstall QZ companion ? Do you think I did a wrong setting ? Thanks in advance.

**Comment by cagnulein** [comment]
Let me see know the debug log I would like to see if it now you can receive at least a connection from the companion. Then if it's so we can work on the companion side

**Comment by Toniok6** [comment]
You will find the debug log. 
I did a last test before sending you the debug log :  treadmill was starting at 2km/h and speed data was displayed on the sreen QZ app then the data stay fixed even if I changed speed of the treadmill.
[debug-dim__mai_19_13_43_47_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15369441/debug-dim__mai_19_13_43_47_2024.log)

**Comment by cagnulein** [comment]
Ok good news now i can see the frames!

Ok in the companion try to set the T75s and reboot the treadmill 

If it doesn't work again we will go with the grand tour pro trick

Let me know

**Comment by Toniok6** [comment]
Hi Rob, I did the different mode with companion and still no data. I send to you the debug log after trying T75s on companion and another one  after testing with the grand tour 
[debug-lun__mai_20_08_47_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15372912/debug-lun__mai_20_08_47_44_2024.log)
[debug-lun__mai_20_09_04_06_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15372915/debug-lun__mai_20_09_04_06_2024.log)

**Comment by Toniok6** [comment]
And I had you another debug log in mode which has displayed data for 2 minutes, working well with speed change from treadmill and then bloced on the value. No button active from QZ app also. It was the same pbme from the beginning, sometimes we can receive the data, setting speed and the like no connection with treadmill, QZ app data remain fixed...
[debug-lun__mai_20_09_25_05_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15373043/debug-lun__mai_20_09_25_05_2024.log)

**Comment by cagnulein** [comment]
Mmm ok are you able to follow this? 

https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

Otherwise we have to understand with a adb logcat log which is the issue on the tablet side

Let me know

**Comment by Toniok6** [comment]
Hi Rob, thanks I try with X11i on QZ app and looks good, but however the button of QZ app don't work and Zwift do not control the QZ app too. Only one way tredmill > QZ app > Zwift may be just a setting now ?

**Comment by cagnulein** [comment]
Yeah I just need to map your tablet. I will send you the instructions later
today, I'm working now
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 mag 2024 alle 08:54 Toniok6 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok i'm back,
run this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat to collect a picture showing the sliders for inclination and speed on the ifit app

Let me know!

**Comment by Toniok6** [comment]
Thanks a lot for your help Roberto. I have tested a lot of type of treadmill in QZ companion and most of them displayed data in QZ app very well. The bug of the app is coming when you  set the speed or inclin by the other touch.
For the .bat I'm not friendly with this method because I couldn't ping my treadmill and I don't understand why. 
I think it's better to give up because I make you loose time, I have the speed in zwift that's ok for me. Thanks for the suport !
![Sans titre](https://github.com/cagnulein/qdomyos-zwift/assets/170189932/26102edd-e90d-4c81-b9a3-39c448c92246)

**Comment by cagnulein** [comment]
Ok if you want we can continue, that's not a problem for me.
You  need a pc that can at least ping the treadmill
