### ISSUE TITLE
Tiles Not working

### ISSUE THREAD

**Issue by Shanenewton** [cagnulein/qdomyos-zwift#2342]
I have a Proform TDF4which as been working ok with the QZ app, it seem to be connecting to the bike ok but the only tiles that work now are the heartrate and the incline with the + and - buttons. the Qz apps is run on a Andriod phone

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Sat_May_18_09_31_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15375571/debug-Sat_May_18_09_31_27_2024.log)

**Comment by Shanenewton** [comment]
Yes, I am!

**Comment by cagnulein** [comment]
Were you ride so? It seems that the bike it doesn't send any metrics

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 mag 2024 alle 13:09 Shanenewton ***@***.***>
ha scritto:

> Yes, I am!
>

**Comment by Shanenewton** [comment]
I use the bike in a bedroom when I first purchased the app it work
perfectly I then moved it to garage but the WiFi was struggling to reach so
I returned back to the bedroom.

**Comment by cagnulein** [comment]
Ok so we are fine?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 mag 2024 alle 20:08 Shanenewton ***@***.***>
ha scritto:

> I use the bike in a bedroom when I first purchased the app it work
> perfectly I then moved it to garage but the WiFi was struggling to reach
> so
> I returned back to the bedroom.
>

**Comment by Shanenewton** [comment]
I will give it ago tonight
Thanks for your help

**Comment by Shanenewton** [comment]
I have tried the bike the last 2 nights and still doing the same thing

**Comment by cagnulein** [comment]
Try a factory reset and don't give internet to the bike, it should works then

**Comment by Shanenewton** [comment]
Nothing works when the bike as no Internet not even the incline but as soon
has the bike as Internet  the incline works but nothing else

**Comment by cagnulein** [comment]
Watch out: I’m talking about internet access not to wifi access. The bike
must have wifi access but not internet access.

Anyway try also to run it from the main menu.

Did it work in the past?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 21:01 Shanenewton ***@***.***>
ha scritto:

> Nothing works when the bike as no Internet not even the incline but as
> soon
> has the bike as Internet the incline works but nothing else
>
>

**Comment by Shanenewton** [comment]
When I originally purchased the app it worked fine that's what I can't
understand l did the preset routes and manual workouts

**Comment by cagnulein** [comment]
So if you didn’t change any settings the issue is on the bike. You can also
try to reinstall the app to be sure

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 21:24 Shanenewton ***@***.***>
ha scritto:

> When I originally purchased the app it worked fine that's what I can't
> understand l did the preset routes and manual workouts
>

**Comment by Shanenewton** [comment]
I have tried 3 separate sessions tonight seem to work than after  about 3
mins they fade out although these are bit sporadic I have also noticed that
the gpx map file's are missing from the app,and where it say connecting
under the stop / start it never connects to anything percivic.

**Comment by cagnulein** [comment]
Connecting label is right, that label is about Bluetooth devices.
What do you mean by “after 3 minutes they fade out”.?
The bike probably lost the connection to the wifi I guess
Check the debug log from qz
Let me know if I can help you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 23 mag 2024 alle 19:03 Shanenewton ***@***.***>
ha scritto:

> I have tried 3 separate sessions tonight seem to work than after about 3
> mins they fade out although these are bit sporadic I have also noticed
> that
> the gpx map file's are missing from the app,and where it say connecting
> under the stop / start it never connects to anything percivic.
>

**Comment by Shanenewton** [comment]
Thank you for informing me.

**Comment by cagnulein** [comment]
show me the debug log in case
let me know

**Comment by cagnulein** [comment]
@Shanenewton any news?
