### ISSUE TITLE
Wahoo Headwind, HRM

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2343]
Hi @cagnulein, I am ordering a Wahoo Headwind and I am curios if your app also can send my heart rate data to the Headwind via Bluetooth to control the fans speed? Do you have any experience with this or heard of somebody doing it? 

Jan

**Comment by Fysibisy** [comment]
Ok,got it, thanks.Am 20.05.2024 um 19:25 schrieb Roberto Viola ***@***.***>:﻿
Hi! Qz can already control the wahoo headwind based on your heart rate!

Don't you see the settings under accessories settings in qz?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 20 mag 2024 alle 18:16 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Let me know if you have any other questions

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 mag 2024 alle 19:48 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Hi, seems like it’s working but when I chance with plus or minus the speed of the fan or it changes based on my heart rate, the number in the tile stays at 0. What can I do to fix this? Mit besten Grüßen,Jan SonntagAm 20.05.2024 um 21:13 schrieb Roberto Viola ***@***.***>:﻿
Let me know if you have any other questions



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno lun 20 mag 2024 alle 19:48 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
when you press the plus or the minus button you are "trimming" the base value. so for example if 0 is the value at 80 bpm, with plus you are saying that with 80pbm the fan has to go to 1. and so on. of course you can change the scale of your heart rate the in the wahoo headwind fan setting in qz. Do I answer to your question?

**Comment by Fysibisy** [comment]
Not quite yet. At the moment in my profile the preset is min 0, max 100. When I start my workout, the tile shows 0. This means at a heart rate of 80 for example, the fan stays at 0 which means, the baseline 0 is equal to 80 bpm, correct? If I press +, 1 is the new baseline for 80 bpm, so the fan runs higher with 80 like before, right? The thing is, if I press + or -, the number stays at 0. It does not update in the tile. Am 21.05.2024 um 17:59 schrieb Roberto Viola ***@***.***>:﻿
when you press the plus or the minus button you are "trimming" the base value. so for example if 0 is the value at 80 bpm, with plus you are saying that with 80pbm the fan has to go to 1. and so on. of course you can change the scale of your heart rate the in the wahoo headwind fan setting in qz. Do I answer to your question?

**Comment by Fysibisy** [comment]
Yeah, it’s increasing or decreasing, manually and based on my heart rate. Only the displayed number does not update.Ok, I will do that later. Am 21.05.2024 um 18:25 schrieb Roberto Viola ***@***.***>:﻿
But do you feel the fan incrising?

Can you share a debug log showing the issue?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 21 mag 2024 alle 18:11 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Ok let me know, sounds an easy fix.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 mag 2024 alle 18:30 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Thanks, requested access

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 mag 2024 alle 22:35 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
log checked, do you see 0 all the time on the fan tile? it's very strange i can see the number changing in the log. i will try on my end the next week in case
thanks

**Comment by Fysibisy** [comment]
You should have acces now. Am 22.05.2024 um 06:00 schrieb Roberto Viola ***@***.***>:﻿
Thanks, requested access



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 21 mag 2024 alle 22:35 Fysibisy ***@***.***> ha

scritto:

**Comment by Fysibisy** [comment]
Yes, always at zero. When I press the minus button a couple times the fan jumps at 100 %, noticed this yesterday. But let’s see how it goes when it’s fixed. Thanks a lot. Am 22.05.2024 um 08:15 schrieb Roberto Viola ***@***.***>:﻿
log checked, do you see 0 all the time on the fan tile? it's very strange i can see the number changing in the log. i will try on my end the next week in case
thanks

**Comment by cagnulein** [comment]
Yeah that's the right behavior, when to 0 and you press the minus it goes
to the max and viceversa. It's so since day one
Anyway I will check the fan tile issue next week
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 mag 2024 alle 08:45 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
HI @cagnulein how is it going? Did you take a look at it?

**Comment by cagnulein** [comment]
not yet, i will update you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 7 giu 2024 alle 12:31 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Fysibisy i will check this next week, i'm still very busy

**Comment by cagnulein** [comment]
@Fysibisy just tried and it works perfectly here :( do you still have the issue? If so I will add some new debug logs in order to understand it. Let me know!

**Comment by Fysibisy** [comment]
Hi, since I put the Headwind in heart rate mode I didn’t test it anymore. I will check it this week and let you know. Am 08.07.2024 um 21:24 schrieb Roberto Viola ***@***.***>:﻿
@Fysibisy just tried and it works perfectly here :( do you still have the issue? If so I will add some new debug logs in order to understand it. Let me know!

**Comment by cagnulein** [comment]
ok let me know

**Comment by Fysibisy** [comment]
On the issue is that I chose the wrong tile (treadmill internal fan). What’s the name of the tile of the wahoo? Am 08.07.2024 um 21:24 schrieb Roberto Viola ***@***.***>:﻿
@Fysibisy just tried and it works perfectly here :( do you still have the issue? If so I will add some new debug logs in order to understand it. Let me know!

**Comment by cagnulein** [comment]
got it now and fixed! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@Fysibisy any news?

**Comment by Fysibisy** [comment]
What’s the tiles name? I can only see the tile for the treadmill in my tile settings, bit not for an external fan.On 2. Aug 2024, at 06:59, Roberto Viola ***@***.***> wrote:﻿
@Fysibisy any news?

**Comment by cagnulein** [comment]
it is the same one that you told me that it was always 0. it's the only fan tile available in qz. That tile assumes the value from the treadmill fan if available otherwise from the external one like your case with the wahoo headwind

**Comment by Fysibisy** [comment]
Hi @cagnulein, I can change the fan speed, but don’t see the number changing in the Tile. Best, JanAm 05.08.2024 um 14:59 schrieb Roberto Viola ***@***.***>:﻿
Reopened #2343.

**Comment by cagnulein** [comment]
@Fysibisy did you install the newer version? Send me a fresh debug log in case

**Comment by Fysibisy** [comment]
I am up to date. Last version installed via Testflight after your last info. No changes since, please check again. ﻿
@Fysibisy did you install the newer version? Send me a fresh debug log in case

**Comment by cagnulein** [comment]
Yes share the debug log so I can check if the patch was correctly
implemented
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 ago 2024 alle 15:54 Fysibisy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Fysibisy any news?

**Comment by Fysibisy** [comment]
It works, I can see a 10 percent increase up until 100 which is equal to 100 percent power of the Headwind. Am 15.09.2024 um 16:06 schrieb Roberto Viola ***@***.***>:﻿
@Fysibisy any news?

**Comment by cagnulein** [comment]
perfect!
