### ISSUE TITLE
[BUG] PC- Domyos Run500 not connecting, domyos-zwift close by itself,

### ISSUE THREAD

**Issue by VNT974** [cagnulein/qdomyos-zwift#2344]
**Describe the bug**
Installed [https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary.zip](https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary.zip) on PC Windows 11 Pro, and I am unable to connect Domyos Run500, Geforce Experience app do open itselft, and domyos-zwift do close right after few seconds not allowing me to do anything/even go in Settings. I do not have the Tiles showing up, nore the Play/Pause button working, nore something telling me it's connected.

**To Reproduce**
Treadmill is turned on, connected with a HRM belt, and 'found' on domyos-zwift (I don't know).
Treadmill is found but not connected on Windows Bluetooth settings.

1. Download and Extract windows-binary.zip folder
2. Click right-click as admin to open setup.bat, then Open domyos-zwift.exe
3. As I already setup the settings it's using the old settings
5. See error

**Expected behavior**
I understand treadmill should be turned on BEFORE (OK) to open the domyos-zwift.exe file, autoconnect the treadmill as it should be saved already; and if I  choose either to  "Pause when opening domyos-zwift it should detect, and wait for me to start the working. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 
 - Version: 23H2 (22631.3593)

**Append a debug log**
  
  
**Additional context**
[debug-Tue_May_21_12_36_14_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387062/debug-Tue_May_21_12_36_14_2024.log)
[debug-Tue_May_21_12_28_19_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387065/debug-Tue_May_21_12_28_19_2024.log)
[debug-Tue_May_21_12_25_52_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387066/debug-Tue_May_21_12_25_52_2024.log)
[debug-Tue_May_21_12_25_26_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387068/debug-Tue_May_21_12_25_26_2024.log)
[debug-Tue_May_21_12_21_00_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387069/debug-Tue_May_21_12_21_00_2024.log)
[debug-Tue_May_21_12_19_09_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387071/debug-Tue_May_21_12_19_09_2024.log)
[debug-Tue_May_21_12_16_15_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15387072/debug-Tue_May_21_12_16_15_2024.log)

**Comment by cagnulein** [comment]
got the issue and fixed.
You will see the new build down here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9173058594 in 30 minutes (bottom of the page).

DOwnload the new build and set first your treadmill to the ftms treadmill setting. This is required because of a bug of windows bluetooth subsystem

**Comment by cagnulein** [comment]
sorry new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/9174552085
