### ISSUE TITLE
[REQ] Domyos Run500 do have 5 speed/inclination quick-button

### ISSUE THREAD

**Issue by VNT974** [cagnulein/qdomyos-zwift#2345]
**Is your feature request related to a problem? Please describe.**
Waiting for a new build that fix #2344 to be able to test out.

**Describe the solution you'd like**
As some treadmill might have 5 quick-buttons for speed & inclinaison, I am requesting to have a 5th button for it.

Inclinaison : 0 - 4 - 6 - 8 - 10%
Speed: 6 - 10 - 12 - 14 - 16

Please, note that some treadmills might have more than 5 quick-buttons,
example Domyos T900C
https://www.decathlon.fr/p/tapis-de-course-t900c-connecte-18-km-h-50x143cm/_/R-p-161031

**Additional context**
Here is the screenshoot of Domyos Run500 board:
![441030188_811283000952688_3230708027473817720_n](https://github.com/cagnulein/qdomyos-zwift/assets/99896027/7d673f78-a99b-4034-9946-900324aa9e24)

**Comment by cagnulein** [comment]
thanks  I will check it out! I will be able to work on this the next week

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 mag 2024 alle ore 16:23 VNT974 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9177730814

**Comment by cagnulein** [comment]
hi @VNT974 i need a debug log where you are pressing that buttons running QZ.
Thanks

**Comment by VNT974** [comment]
Hi 
I don't recall if I sended you that debug log, I guess I haven't done it, right ?

**Comment by cagnulein** [comment]
Nope

**Comment by VNT974** [comment]
Hello
Here's the Debug log, I pressed the quick-button which have 6 - 10 - 12 - 14 - 16km/h
Please tell me if this is good to go.

[debug-Mon_Jun_3_15_25_21_2024.log](https://github.com/user-attachments/files/15533098/debug-Mon_Jun_3_15_25_21_2024.log)

**Comment by VNT974** [comment]
I'm afraid I don't understand, using the PC domyos app sure that I can use the treadmill quick-button, and it display well the corresponding speed on the PC domyos app.  On PC Domyos I have to test out the built in button which is kinda hard use the mouse while I'm on the treadmill.

**Comment by cagnulein** [comment]
Did you check also the mobile domyos version? The quick buttons are working also with this?
