### ISSUE TITLE
[BUG] rawdog2112 flywheel 

### ISSUE THREAD

**Issue by raw1973** [cagnulein/qdomyos-zwift#2346]
[**Describe]([url](url)) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. [iPhone6]]([url](
[debug-Tue_May_21_05_40_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15394355/debug-Tue_May_21_05_40_51_2024.log)
))

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Tue_May_21_05_40_51_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15394363/debug-Tue_May_21_05_40_51_2024.log)

**Comment by cagnulein** [comment]
hi @raw1973 log checked
the I_TL is a treadmill around you. 
I don't see the flywheel via bluetooth, is the battery OK on the bike?

**Comment by cagnulein** [comment]
@raw1973 any news?
