### ISSUE TITLE
Pause/Start Resets Peloton autofollow numbers

### ISSUE THREAD

**Issue by fooeynet** [cagnulein/qdomyos-zwift#235]
Hitting Pause and then Start seems to reset the Peloton auto follow for that ride. Are we triggering the program on the Start button keypress?

**Comment by cagnulein** [comment]
Oh yes, it's something need to be fixed. Thanks for addressing this.
R.

Il sab 3 apr 2021, 05:47 fooeynet ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@fooeynet so yes, start reset the peloton auto follow: i mean it resets from the beginning and i guess it's correct behaviour. Now i added also handling of the pause event.

Is it ok for you?

**Comment by fooeynet** [comment]
Yes that seems correct!
