### ISSUE TITLE
Inaccurate Speed  on Garmin Watches using ANT+

### ISSUE THREAD

**Issue by gigilauda** [cagnulein/qdomyos-zwift#2356]
**Describe the bug**
Scenario:

Echelon EX-15
QZ App installed on Samsung S9 ANT+
Garmin Forerunner 255 or Fenix 3 Watches
The Watches can only detect the Speed/Cadence  and power sensors using ANT+ 
If I start a bike indoor activity the Power and Cadence are accurate 
The speed instead is unstable and inaccurate jumping from 0 kmh to over 130 kmh at random
I tried to change the wheel size on the detected speed/cad sensor but problem persist
I tried to forget the power sensors and leave only Speed/cadence and problem persist
I tried on both watches and the problem persist

**To Reproduce**

**Expected behavior**
Speed on the app to reflect on Garmin Watches

**Screenshots**

**Desktop (please complete the following information):**
 Garmin Forerunner 255 Version 18.27

**Smartphone (please complete the following information):**
Samsung S9
Android V 10
QZ app Version 2.14.0

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
You have to set wheel diamater to 100mm
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 26 mag 2024 alle 11:59 gigilauda ***@***.***>
ha scritto:

**Comment by gigilauda** [comment]
Perfect! 
I tried and the speed is stable and accurate
Thank you!

**Comment by gigilauda** [comment]
Ciao Roberto, Per qualche ragione l’app non si collega piu’ al mio Garmin watch Forerunner 255 durante una sessione di bici Ho provato a rimuovere tutti i sensori sul garmin e rconnecter la cad/speed ma niente gira. La bici si collega bene e mostra i dati sull’androidSe hai qualche idea, fammi saperGrazieGigiSent from my iPadOn May 26, 2024, at 6:19 AM, Roberto Viola ***@***.***> wrote:﻿
Closed #2356 as not planned.

**Comment by cagnulein** [comment]
Hai provato a riavviare l'orologio?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 4 gen 2025 alle 19:00 gigilauda ***@***.***> ha
scritto:

**Comment by gigilauda** [comment]
No, ma recentemente ho ricevuto degli update che resettano l’orologioPrima e dopo gli update ho lo stesso problema ora provo a resettare l’orologioe e ci riprovo quiando la moglie ha finito la sua sessioneSent from my iPadOn Jan 4, 2025, at 1:01 PM, Roberto Viola ***@***.***> wrote:﻿
Hai provato a riavviare l'orologio?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 4 gen 2025 alle 19:00 gigilauda ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
L'altra cosa che puoi fare è vedere se le app ant+ sul play store
funzionano per leggere il battito via ant dal tuo orologio. Magari si è
impuntato qualcosa a livello di android

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 4 gen 2025 alle 19:05 gigilauda ***@***.***> ha
scritto:

**Comment by gigilauda** [comment]
Ciao Roberto, Ho reinstallato l’app - resettato sia il samsung s9 che il garmin - eliminato tutti i sensori sul garmin ed effettuato una auto discovery Sulla app how abilitato ANT+ sia per spd/cadence che per HR Vengono riconosciuti  spd/cadence e power - ho settato la wheel size a 100Adesso noto che l’app riesce a trasmettere i dati di power and cadenza giusti ma la velocita’ mi viene sporadicamente a valori bassissimi (0.1-0.2)Non e’ urgente ma si ci puoi dare un occhiataGrazieGigiSent from my iPadOn Jan 4, 2025, at 1:55 PM, Roberto Viola ***@***.***> wrote:﻿
L'altra cosa che puoi fare è vedere se le app ant+ sul play store

funzionano per leggere il battito via ant dal tuo orologio. Magari si è

impuntato qualcosa a livello di android



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 4 gen 2025 alle 19:05 gigilauda ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
prova a mettere la wheel size a 1 invece che a 100, credo che l'orologio faccia una compensazione

**Comment by gigilauda** [comment]
Ho provato a 1, 100, 3000 oppure auto ed il risultato non cambiaSent from my iPadOn Jan 5, 2025, at 11:06 AM, Roberto Viola ***@***.***> wrote:﻿
prova a mettere la wheel size a 1 invece che a 100, credo che l'orologio faccia una compensazione

**Comment by cagnulein** [comment]
Prova a giocare con l'ant+ speed gain negli ant options in qz
