### ISSUE TITLE
QZ app thinks my Nordictrack s22i bike is a treadmill. 

### ISSUE THREAD

**Issue by gwyndyn** [cagnulein/qdomyos-zwift#2358]
I'm having trouble getting the app to recognize that I am using a bike and not a treadmill. I'm using the Nordictrack s22i with the companion app installed on it but I can't get the cadence to be recognized, it always lists the workout as a run, and I have no resistance tile showing up. I'm using the QZ app on an Android Samsung Galaxy Zfold 5. I do not have a treadmill nearby though I do have other bluetooth/wifi appliances like my washing machine. 
[Uploading debug-Mon_May_27_13_53_30_2024.log…]()

**Comment by gwyndyn** [comment]
I'm not sure if it actually uploaded the log and if I try to attach it to a comment it says the file is too big so let me know if I need to send it another way.

**Comment by cagnulein** [comment]
Hi no unfortunately the log is corrupted. Zip it and wait the end of the upload before pushing the comment button 
Let me know

**Comment by gwyndyn** [comment]
[debug-Mon_May_27_13_53_30_2024.zip](https://github.com/cagnulein/qdomyos-zwift/files/15464084/debug-Mon_May_27_13_53_30_2024.zip)

**Comment by cagnulein** [comment]
thanks i will check it asap
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 mag 2024 alle ore 06:53 gwyndyn ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@gwyndyn very easy fix: you set the ip also in the treadmill nordictrack section. Remove completely from there and press ok and restart QZ. Let me know!

**Comment by gwyndyn** [comment]
Yep, that was it! Thank you! I am having am issue now with being able to adjust the resistance from the app though. It adjusts incline fine but not resistance. Should I submit a separate issue for that?

**Comment by cagnulein** [comment]
Nope it's the right behavior. I choose to change only inclination because
changing inclination it also change resistance. So with one thing I took 2
things :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 mag 2024 alle 23:52 gwyndyn ***@***.***> ha
scritto:

**Comment by gwyndyn** [comment]
Ok, thank you for your help!
