### ISSUE TITLE
Probably don't need to grab 100 workouts...

### ISSUE THREAD

**Issue by fooeynet** [cagnulein/qdomyos-zwift#236]
In peloton::getWorkoutList we're pulling down the last 100 rides from a user, if all we're using that list for is finding one that's "in progress" we could probably cut that waaaaay down.

**Comment by cagnulein** [comment]
Yes you're right, but they're only the list. Anyway i will fix it ;)
You should start a pull request ;)
R.


Il sab 3 apr 2021, 06:49 fooeynet ***@***.***> ha scritto:
