### ISSUE TITLE
JLL IC400 Pro and SS2k - Resistance problem

### ISSUE THREAD

**Issue by AJB-Mouse** [cagnulein/qdomyos-zwift#2360]
**Describe the bug**
I am using a JLL IC400 pro bike with SS2K attached.

Without QZ app running the SS2K responds correctly to the gear shift manual buttons.

QZ is set for a JLL IC400 Bike in the Toorx/iConsole option. SS2k is enabled in Accessories.
SS2K has both the Saved Power Meter and Saved HRM saved as 'none'. All else is at default in SS2K settings.

If running QZ app on Apple watch the speed, cadence, watts and HR tiles report correctly in QZ.

With QZ running and peddling, the resistance tile always shows around 50. The target shows as 0. If I press the resistance 'plus' button once the SS2K cranks up to max and grinds. I have to then unplug it to stop it.

The QZ gears tile buttons have no effect. 

If the QZ app on Apple watch is not running I get 'nan' in the resistance tile.

Any help would be appreciated!

**Expected behavior**
I would expect the resistance and target resistance to be similar/the same. 
I would expect the buttons on the resistance tile to cause the target resistance to change accordingly. 
I would expect the gears tile buttons to change the SS2K resistance/gear.

**Screenshots**
![IMG_7768](https://github.com/cagnulein/qdomyos-zwift/assets/171159532/46763770-6808-4347-8fd1-51a444e38d6b)

**Desktop (please complete the following information):**
 - MacOS
 - Version Sonoma

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: 17.4.1
 

**Append a debug log**
[debug-Wed_May_29_15_30_58_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15486161/debug-Wed_May_29_15_30_58_2024.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
hi, let's start from the basic: did you set the ss2k step value correctly in qz? i saw you set a 900

**Comment by cagnulein** [comment]
also in the log I don't see a connection to the SmartSpin2k (it seems it's not broadcasting itself)

**Comment by AJB-Mouse** [comment]
I left the step value at the default of 900. Do you know what it should be? How can I establish if SS2k is broadcasting?

**Comment by cagnulein** [comment]
the step value should be a setting in the ss2k itself. if the amount of step necessary to do a shift of 1 resistance level.
you will see if the ss2k is broadcasting, for example, if you open nrfconnect app, and you will see it there in the list
let me know

**Comment by cagnulein** [comment]
ok so took another log, i have to see the ss2k in the log otherwise I can't understand the issue. Thanks

**Comment by AJB-Mouse** [comment]
Hi, QZ is definitely talking to SS2K as the resistance 'plus' button make it respond (well it cranks it up to max until it grinds). 
I've attached a new log.
[debug-Wed_May_29_16_19_34_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15486607/debug-Wed_May_29_16_19_34_2024.log)

**Comment by cagnulein** [comment]
in this one yes. let me take a look

**Comment by cagnulein** [comment]
the issue seems that you pressed the plus gear before getting a real resistance from the ss2k. I see the resistance sent from the SS2k is 0 then, it sends 49. It shouldn't do this. Maybe the 900 is too high. Let's try with a lower value like 50 for example and restart qz 
Let me know

**Comment by AJB-Mouse** [comment]
Is that 50 in the QZ app or 50 in SS2k (or both)?

**Comment by cagnulein** [comment]
when QZ is connected, it's the master, so you can change it only on QZ

**Comment by AJB-Mouse** [comment]
OK, I'll change it to 50 and record another log.

**Comment by AJB-Mouse** [comment]
Right. Now, when I press the resistance tile 'plus'  button once the target resistance goes from 0 to 45/50ish. But the SS2K does not respond in any way if I press the 'plus' button over and over again. New log attached.

[debug-Wed_May_29_16_45_44_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15486981/debug-Wed_May_29_16_45_44_2024.log)

**Comment by cagnulein** [comment]
This resistance jump its very strange.

@doudar any help?

**Comment by doudar** [comment]
Any chance I could get a SmartSpin2k log? https://github.com/doudar/SmartSpin2k/wiki/Viewing-logs-via-UDP

**Comment by AJB-Mouse** [comment]
Here are a couple of SS2K logs and the QZ log for the same sessions. I tried using the physical SS2K gear buttons, the QZ gear button and the QZ resistance tile ‘plus’ button. The resistance tile ‘plus’ buttons appear to do nothing (its value nor the target resistance tile value change).  The physical SS2k gear buttons do work but the movement is very small – probably because the QZ step value is set to 50 at the moment. The QZ gear tile does appear to change the target resistance – I could bring it down from 43 to 3 by taking the gears down to -42. 
[debug-Thu_May_30_08_33_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/15495802/debug-Thu_May_30_08_33_11_2024.log)
[Custom UDP Receiver (Port 10000).txt](https://github.com/cagnulein/qdomyos-zwift/files/15495809/Custom.UDP.Receiver.Port.10000.txt)
[Custom UDP Receiver (Port 10000)2.txt](https://github.com/cagnulein/qdomyos-zwift/files/15495810/Custom.UDP.Receiver.Port.10000.2.txt)
![IMG_7777](https://github.com/cagnulein/qdomyos-zwift/assets/171159532/664ce8b0-a018-4475-b7cf-62e6bf72c23c)

**Comment by doudar** [comment]
The first shifter position request we receive is level 39 for some reason. 39 is a lot of shifts :)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/17362216/da1ca657-e732-4ef8-9c98-647f22340daa)

Still looking into why.

**Comment by doudar** [comment]
@cagnulein , there’s nothing extra I see on the logs here - are you able to see anything that might cause this?

**Comment by doudar** [comment]
@cagnulein , this bike (JLL IC400) doesn't report the actual knob position, so the 0x17 command that's being sent is the actual shifter position, which is always 0 from when the unit is powered on. Shift down from that should move it to -1, shift up should move it to 1. No clue why QZ is sending 49.

**Comment by cagnulein** [comment]
@doudar Got the issue: qz is creating the concept of resistance using cadence and wattage for bikes that doesn't have on hardware. This is conflicting with the ss2k. I will try to fix this next week @AJB-Mouse

**Comment by doudar** [comment]
Awesome! Thanks for checking into it!

**Comment by cagnulein** [comment]
@AJB-Mouse done. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by AJB-Mouse** [comment]
Hi,
Thanks for looking into this and the new app version. SS2K is working sensibly now and responds to the QZ resistance tile and also the gears tile. 

A couple of issues though. The minimum resistance that SS2K will go down to is quite stiff. Is there a setting for this?

When I connect to MyWhoosh things don’t go so well. MW finds and connects to all the right sources, including resistance device, but the target resistance does not change from 1 when on a slope (I’m not in erg mode). Any thoughts?

**Comment by cagnulein** [comment]
> A couple of issues though. The minimum resistance that SS2K will go down to is quite stiff. Is there a setting for this?

@doudar could you help here?



> When I connect to MyWhoosh things don’t go so well. MW finds and connects to all the right sources, including resistance device, but the target resistance does not change from 1 when on a slope (I’m not in erg mode). Any thoughts?

send me a fresh debug log and I will check it. Did you pair for resistance control on MW?

**Comment by AJB-Mouse** [comment]
Here's the debug log with MW. Resistance control was paired.

[debug-Mon_Jun_3_11_20_40_2024.log](https://github.com/user-attachments/files/15532493/debug-Mon_Jun_3_11_20_40_2024.log)

**Comment by doudar** [comment]
Set min brake watts to a low value. Try 30w. It might take a few minutes of pedaling between 70 & 100 rpm to re-learn your bike if things were acting crazy before.

**Comment by AJB-Mouse** [comment]
No joy with Zwift on iPad either. It connects correctly (including resistance) but nothing happens when I'm on a slope.
[debug-Mon_Jun_3_15_12_59_2024.log](https://github.com/user-attachments/files/15535183/debug-Mon_Jun_3_15_12_59_2024.log)

I tried VZFit as well on Quest - same issue.

**Comment by cagnulein** [comment]
@AJB-Mouse in this log i don't see any connection, i guess you uploaded the wrong one?

**Comment by AJB-Mouse** [comment]
Try this...
[debug-Mon_Jun_3_15_07_16_2024.log](https://github.com/user-attachments/files/15535337/debug-Mon_Jun_3_15_07_16_2024.log)

**Comment by cagnulein** [comment]
found the issue

Zwift Resistance Gain is set to 0. it can't be. Set it to 1.
Let me know

Also zwift resistance offset should be the value of resistance that you feel like a flat road.

**Comment by AJB-Mouse** [comment]
Yay! That’s fixed it. I’ll need to spend some time tweaking a few settings but we are almost where I want to be.

My remaining real issue is getting a lower resistance. Is it normal that the resistance tile will never drop below 1, even if target resistance is say -5? (If don’t use QZ but use the virtual shifter in the SS2K app I can get the resistance down nicely.)
Alternatively, I'll just have to get fitter! 
Thanks for all your help.

**Comment by cagnulein** [comment]
that's great!
yes resistance can't go lower than 0. i suggest to start qz while ss2k is already on a lower resitance, so you it will handle only positive resistance values
Remember also to rate the QZ app on the store, it means a lot to me!
Thanks!

**Comment by AJB-Mouse** [comment]
Hi,

Me again- sorry. All is going well except that with the latest app version I am getting negative calories. Sometimes huge values. I've attached a couple of recent logs. Hopefully there's a quick fix.

[debug-Sat_Jun_8_11_00_44_2024.log](https://github.com/user-attachments/files/15747727/debug-Sat_Jun_8_11_00_44_2024.log)
[debug-Sat_Jun_8_10_48_18_2024.log](https://github.com/user-attachments/files/15747728/debug-Sat_Jun_8_10_48_18_2024.log)

**Comment by cagnulein** [comment]
great! i will check it in the next days

**Comment by cagnulein** [comment]
i'm sending you a new version with the fix!
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 8 giu 2024 alle ore 13:43 AJB-Mouse ***@***.***>
ha scritto:

**Comment by AJB-Mouse** [comment]
Just tested - no change. Sorry.

￼￼

**Comment by cagnulein** [comment]
Ok strange, I will keep checking

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 9 giu 2024 alle 17:19 AJB-Mouse ***@***.***> ha
scritto:

> Just tested - no change. Sorry.
>
> ￼￼
>

**Comment by cagnulein** [comment]
sent another one, let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 9 giu 2024 alle ore 17:20 cagnulein ***@***.***> ha
scritto:

> Ok strange, I will keep checking
>
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
>
>
>
> Il giorno dom 9 giu 2024 alle 17:19 AJB-Mouse ***@***.***>
> ha scritto:
>
>> Just tested - no change. Sorry.
>>
>> ￼￼
>>
