### ISSUE TITLE
[Bug] Cannot find power source on Zwift

### ISSUE THREAD

**Issue by pyin2023** [cagnulein/qdomyos-zwift#2361]
**Describe the bug**
I downloaded Zwift app on my iPad today. I opened the QZ app on my iPhone 13 and Zwift was run on my iPad. However, Zwift only can detect the Wahoo KICKER 0000 33 (Wahoo virtual device, WiFi??) instead of my phone (Bluetooth). For the QZ, I have disabled the Peloton Cadence sensor.  But Zwift still cannot find the power source-my phone (Bluetooth connection).

**To Reproduce**
1. Launch Zwift on iPad
2. Launch Bike and Connect with QZ through iPhone 13
3. Tried to find the power source in Zwift, but cannot find bluetooth connection of my phone at all.

**Expected behavior**
I want Zwift on my iPad to Bluetooth connect my iPhone QZ.

**Screenshots**
![image](https://github.com/cagnulein/qdomyos-zwift/assets/171274886/54c054f0-f4b8-4d24-943c-3e107bcd6e65)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max for running QZ
 - OS: IOS 17.4.1

 - Device: iPad Pro for running Zwift
 - OS: IOS 17.4.1

**Append a debug log**
I tried like in guide but I don't even have a folder documents/QZ

**Comment by cagnulein** [comment]
Wahoo kickr is perfect. Give it a go with this one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 mag 2024 alle 19:05 pyin2023 ***@***.***> ha
scritto:

**Comment by pyin2023** [comment]
However, when I connect the Wahoo kickr, the Cadence and Heart Rate work fine, except for the Controls. There is no power source for the Controls, as shown below image.  I believe there should be a power source for the Controls once I use the Bluetooth connection.
![image](https://github.com/cagnulein/qdomyos-zwift/assets/171274886/f9ff43c4-b2f2-4320-bb1f-7d0cb682944a)
![image](https://github.com/cagnulein/qdomyos-zwift/assets/171274886/0a5d085e-fc9a-4f8a-936c-c24d08da070d)

**Comment by cagnulein** [comment]
That's perfect, control is for zwift play devices! You are good to go!

**Comment by pyin2023** [comment]
I see. So with this connection, Will the Bike resistance change automatically in the ZWift?

**Comment by cagnulein** [comment]
Yes if you bike has this possibility!

**Comment by pyin2023** [comment]
Great! And just want to know why the Bluetooth connection doesn't work at this time?

**Comment by cagnulein** [comment]
Bluetooth cache issue on the iPad for sure. You could try to do a network
reset on the iPad and reboot it. But wahoo connection is way better!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 mag 2024 alle 19:18 pyin2023 ***@***.***> ha
scritto:
