### ISSUE TITLE
[REQ] Does this work on Echelon EX-4S+ (non connect model)

### ISSUE THREAD

**Issue by cianpdx** [cagnulein/qdomyos-zwift#2362]
I am not sure of the feature set of the echelon range and what “connect” means with respect to this app.

Also I am a little confused about the usage of this app. As far as I can see you have 3 options 

1. Buy the app on the android tablet (integrated into bike)
2. Load app on a Pi which connects to bike with Bluetooth and rebroadcasts to the Zwift device
3. Buy the app from the App Store and run it on a second device 

Thanks for your help.

**Comment by cagnulein** [comment]
You can run on the same bike tablet but you need to hack it first. The straightforward solution is to completely turn off the tablet of your bike and download the qz app on your phone 

Let me know if you have any other questions

**Comment by cianpdx** [comment]
Does the bike need to be “connect” for the phone to connect to it?

**Comment by cagnulein** [comment]
What do you mean connect? It must be connected to qz by Bluetooth

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 31 mag 2024 alle 17:35 cianpdx ***@***.***> ha
scritto:

**Comment by cianpdx** [comment]
I could be mis-understanding echelon models - I was thinking there is "Connect" model and "Standard" model (no connect features) 

and wondering if qdomyos needs a particular version to work.

**Comment by cagnulein** [comment]
Nope it works with Both!
