### ISSUE TITLE
Horizon T202-04 No Connection[BUG]

### ISSUE THREAD

**Issue by dtay21** [cagnulein/qdomyos-zwift#2363]
**Describe the bug**
Horizon T202-04 does not allow control of speed/incline and does not report data.

**To Reproduce**
1. Start tread mill
2. Open QDOMYOS on iPhone
3. Wait 1 minute minimum after tiles screen is visible
4. Press Start

**Expected behavior**
After the Horizon delay of 1 minute, tiles should accurately show speed/incline and allow control. 

**Screenshots**
![IMG_1967](https://github.com/cagnulein/qdomyos-zwift/assets/120340228/19257079-5258-40f1-8942-64f3c1ce7f6f)
![IMG_1966](https://github.com/cagnulein/qdomyos-zwift/assets/120340228/cbbfe865-a20c-48e2-b86c-ea1d29a346c2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 
**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 17.4.1

**Append a debug log**
[debug-Fri_May_31_10_18_42_2024.txt](https://github.com/user-attachments/files/15515319/debug-Fri_May_31_10_18_42_2024.txt)

  
  
**Additional context**
After 1 minute, nothing is shown. If the treadmill is paused, after some time (various timings, nothing specific), the app will grab the data from the treadmill from when it was in motion (screen shots attached) but still will not allow control.

Force Using FTMS is on in settings. When Start is pressed, it will go back to flashing red after about 20 seconds. With FTMS off, it will go back to flashing almost immediately.

I tried turning virtual device bluetooth off in advanced settings and when I press start, it will stay that way; however, I still don't get the connection I expect.

**Comment by cagnulein** [comment]
Hah so the problem is only the control? Are you able to change them from the horizon app?

**Comment by cagnulein** [comment]
Ok log checked: for sure force ftms must be disabled because your treadmill doesn't have ftms

So I suggest do download an older apk of the horizon app or agf app from aptitude and check if everything is OK. If so I can compare the behavior of that app to qz.

Could you also send me a debug log with the force ftms disabled? And wait for a 90 seconds before doing everything 

Let me know

**Comment by dtay21** [comment]
Log : 
[debug-Fri_May_31_11_14_31_2024.txt](https://github.com/user-attachments/files/15515733/debug-Fri_May_31_11_14_31_2024.txt)

FTMS Disabled. When I wait the minute and hit start, it immediately goes back to flashing red.

I have narrowed down when it grabs data - when I pause the treadmill, and it times out (goes back to main "select user" prompt) it will show the last known speed/incline. I am also able to then hit start and stay connected; however, still no control.

**Comment by cagnulein** [comment]
It has for sure a different protocol from the ones that I already implemented : our only solution is to get the old horizon app to run on an android device. Are you able to?

**Comment by dtay21** [comment]
So my old android device with the Horizon app wouldn't work (suspect the device is garbage)

However, there is a Horizon app, specific to iPad that I downloaded (appears identical) but that connected right away and I was able to control all aspects of the treadmill from it.

Is that of any use or must it be the Android version for comparison?

**Comment by cagnulein** [comment]
Unfortunately only on android we can collect logs with this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 31 mag 2024 alle 21:45 dtay21 ***@***.***> ha
scritto:

**Comment by dtay21** [comment]
Still working on this. I tried the only two android devices I had (Fire Tablets) without success (no connection via the app). I'm trying to track down someone I know with a spare device.

**Comment by cagnulein** [comment]
Ok Thanks for the update

**Comment by dtay21** [comment]
Throwing in the towel on this one. I tried 3 different android devices and none of them will connect unfortunately.

**Comment by cagnulein** [comment]
Do you mean no connection with the horizon app? Did you also try the agf app? did you ever use bluetooth on this treadmill?

**Comment by dtay21** [comment]
Yes.

So, there are two versions of the app. AFG Pro, and AFG Sport (one is blue, one is orange). On my iPad, the AFG Pro says to use the AFG Sport app. AFG Sport works great, I can fully control the treadmill. On android, neither app will connect, only connection is to the built in speakers. 

Worth noting, I had to side load the AFG Sport app as Google Play Store doesn't advertise it anymore. Only AFG Pro is available.

**Comment by cagnulein** [comment]
on android both location services and bluetooth are enabled? sorry for the stupid questions but it worth to ask

**Comment by dtay21** [comment]
On for both. They both asked me when launching to allow, which I did, and confirmed through settings for each.

Bluetooth is on and asks to pair with the treadmill's speakers. I have tried both allowing and ignoring that request with the same result. Pairing to the speakers works and the Bluetooth connection light on the treadmill confirms connection, but nothing in the app wither way.

**Comment by cagnulein** [comment]
if you want you could try to ask here on github to some other horizon users
how they connect to the treadmill with the agf app. maybe there is a trick

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 8 giu 2024 alle 22:07 dtay21 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@dtay21 Are you still interested in this? There is a way with ios now to collect data https://ultrawyrypa.pl/index.php/2024/11/05/qz-fitness-connect-ifit-treadmil-to-zwift-and-not-only/
