### ISSUE TITLE
[BUG Unable to connect to TDF 2.0

### ISSUE THREAD

**Issue by linaabdelaal94** [cagnulein/qdomyos-zwift#2364]
**Describe the bug**
I have followed the process of adding mt IP to TDF 4.0 IP however, I am still not able to connect to the bike 
**To Reproduce**

**Expected behavior**
I expect to be able to change the inclined and resistance once connected to the app 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ipad
 - Version Ipad17.3.1 

**Smartphone (please complete the following information):**
 - Device: iPhone 15pro 
 - OS: 17.4.1
 

**Append a debug log**
[debug-Fri_May_31_20_13_50_2024.log](https://github.com/user-attachments/files/15517191/debug-Fri_May_31_20_13_50_2024.log)
  
**Additional context**
I created a post on Facebook. 

I can Ping my IP but this is an error that I get when I try to let the bike access the internet. 

![WhatsApp Image 2024-05-31 at 8 42 06 PM](https://github.com/cagnulein/qdomyos-zwift/assets/59689596/bc6d928d-22c4-4564-a084-207e902f1d05)

**Comment by cagnulein** [comment]
It seems more a tdf1 protocol. Remove the ip from the tdf4 setting and set it to the tdf1 setting and press OK. If you don't see this setting, send me a email to Roberto.viola83 at Gmail.com indicating this ticket and I will send you the beta 
Let me know

**Comment by linaabdelaal94** [comment]
I have attached the debug from the iphone, maybe it would generate a better understanding 

I tried to follow this https://robertoviola.cloud/qdomyos-zwift-guide/  connecting to zwift, however, my peddling is not recognized by QZ or Zwift 

-- Qz on my Iphone 15 pro OS: 17.4.1 and apple watch 
-- Zwift on  Ipad17.3.1 

[debug-Fri_May_31_21_24_32_2024.log](https://github.com/user-attachments/files/15517650/debug-Fri_May_31_21_24_32_2024.log)

Additional context
I am not a techie I am just trying to get my bike to work (I appreciate your help) 

Thank you,

**Comment by cagnulein** [comment]
The main issue is that the ip doesn't have the socket listening so or the ip is wrong or the bike hasn't this protocol. Did this bike worked with qz before? How can you be sure about the ip of the bike? Did you read from the console of the bike? Is the console of the bike working?

**Comment by linaabdelaal94** [comment]
- No it is the first time I am trying the QZ, 
- The console is no longer responding, a firmware issue (https://www.facebook.com/groups/149984563348738/permalink/817551003258754/)
- I am able to ping the IP from my computer 192.168.0.1

**Comment by cagnulein** [comment]
Ok so the wifi controller is working but the firmware responsible to answer to qz is dead. That's the reason unfortunately  :( any chance to replace the console?

**Comment by linaabdelaal94** [comment]
I am not able to find the console anywhere (especially that I am in Egypt) 

I am also getting this error (Error opening Access Point Key file (/ifit/config/login.txt)) when I try to connect the wifi to the internet. 

Is there any solution in mind that you think I should try?

**Comment by cagnulein** [comment]
Unfortunately nope, maybe you can add a power pedal or a cadence sensor to
the bike and use it with qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 31 mag 2024 alle 23:02 linaabdelaal94 <
***@***.***> ha scritto:
