### ISSUE TITLE
[BUG] HR drops with QZ Companion

### ISSUE THREAD

**Issue by rflemming** [cagnulein/qdomyos-zwift#2365]
**Describe the bug**
My last few rides the HR data drops out every 4min or so.  This is in combination with a Garmin 245M and using the latest QZ Companion app and QZ running on a Pixel 8.  The drop outs are visible in real-time when the QZ app is running on my phone and in the fit files, however even when the app is temporarily showing 0, the QZ Companion app on my watch shows the correct HR.  Similar drop outs are not present during other Garmin activities such as running, etc.  This has always been when doing a Peloton workout and most recently it looked like the first drop out matched up to hitting start when the Peloton class started (ie HR was present in the app before starting the workout, but temporarily disappeared once the workout was started).  Given the periodicity, perhaps this is some sort of threading issue where communication to QZ companion is lost as something else running.

**To Reproduce**
1. Start QZ Companion
2. Start QZ app
3. Begin Pelton workout.
4. Observe HR falling to 0 every ~4min

**Expected behavior**
I took a bit of a break using the bike so I can't say when this first started, but it has been working fine in January.  Obviously these drop outs shouldn't be there.

**Screenshots**
Here are my last 4 Peloton rides:
![hr](https://github.com/cagnulein/qdomyos-zwift/assets/7843512/c76b6978-a9cd-4240-996d-3c6d9e153f06)

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 14
 - Version: AP1A.240505.004

**Append a debug log**

I didn't grab one this last ride, I'll get one next time.

**Comment by cagnulein** [comment]
Hi attach a debug log of the issue thanks!
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by rflemming** [comment]
Alrighty, so it happens on a non Peloton ride as well.  Screenshot below and debug log attached

![Sat Jun 1 08_37_25 2024_heart](https://github.com/cagnulein/qdomyos-zwift/assets/7843512/214c5018-97bf-490e-9ef8-a63ca7214f08)
[
[debug-Sat_Jun_1_08_31_35_2024.log](https://github.com/user-attachments/files/15522353/debug-Sat_Jun_1_08_31_35_2024.log)
](url)

**Comment by cagnulein** [comment]
Disable the ant heart setting if you are using the qz companion app on
garmin
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 1 giu 2024 alle 17:44 rflemming ***@***.***> ha
scritto:

**Comment by rflemming** [comment]
That indeed solved it.  Thanks.

**Comment by cagnulein** [comment]
great!
