### ISSUE TITLE
IndieVelo, missing HR Monitor 

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2367]
hi @cagnulein I can connect Cadence & Power via Qz to IndieVelo, but not my HR (Apple Watch) via Qz like in Zwift. Do you have a suggestion? 

Best Jan

**Comment by cagnulein** [comment]
It's a limitation of indievelo, they didn't implement this yet

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 giu 2024 alle 18:46 Fysibisy ***@***.***> ha
scritto:
