### ISSUE TITLE
[BUG] Nordictrack S15i not receiving watts and cadence

### ISSUE THREAD

**Issue by Mhann37** [cagnulein/qdomyos-zwift#2368]
[debug-Mon_Jun_3_17_22_52_2024.log](https://github.com/user-attachments/files/15530445/debug-Mon_Jun_3_17_22_52_2024.log)

After following instructions and working through existing issues on github, have been able to connect QZ to my nordictrack s15i bike. It is receiving speed correctly and I'm able to control inclination, but not resistance.

Watts and cadence are not being received. 

**Smartphone (please complete the following information):**
 - Device: s23 ultra
 - OS:  android
 - Version 14

**Append a debug log** attached

 Any help greatly appreciated, apologies if it's a simple settings matter.

**Comment by cagnulein** [comment]
Hi @Mhann37 yes that's right. QZ can control inclination but not resistance. I did this in this way because inclination also affects resistance so in this way QZ is controlling both things with 1 bullet. Let me know if you have any other questions

**Comment by Mhann37** [comment]
Understood, thx. Primarily the issue is just the absence of watts and cadence metrics

**Comment by cagnulein** [comment]
@Mhann37 log checked. It seems that your bike is logging only speed, gears and resistance. that's why. 
are you able to collect the .wolflogs folder on the bike in order that I can double check the metrics there?

**Comment by Mhann37** [comment]
[Updating_03Jun2024 (1).txt](https://github.com/user-attachments/files/15532067/Updating_03Jun2024.1.txt)
[Workout_03Jun2024 (1).txt](https://github.com/user-attachments/files/15532068/Workout_03Jun2024.1.txt)
[MvxTrace_03Jun2024 (1).txt](https://github.com/user-attachments/files/15532069/MvxTrace_03Jun2024.1.txt)
[Usb_03Jun2024.txt](https://github.com/user-attachments/files/15532070/Usb_03Jun2024.txt)
[Wifi_03Jun2024.txt](https://github.com/user-attachments/files/15532071/Wifi_03Jun2024.txt)
[Dashboard_03Jun2024.txt](https://github.com/user-attachments/files/15532072/Dashboard_03Jun2024.txt)
[Navigation_03Jun2024.txt](https://github.com/user-attachments/files/15532074/Navigation_03Jun2024.txt)
[Connection_03Jun2024.txt](https://github.com/user-attachments/files/15532075/Connection_03Jun2024.txt)
[Ble_03Jun2024.txt](https://github.com/user-attachments/files/15532076/Ble_03Jun2024.txt)
[BadResponse_03Jun2024.txt](https://github.com/user-attachments/files/15532077/BadResponse_03Jun2024.txt)
[FitPro_03Jun2024.txt](https://github.com/user-attachments/files/15532078/FitPro_03Jun2024.txt)
[Benchmark_03Jun2024.txt](https://github.com/user-attachments/files/15532080/Benchmark_03Jun2024.txt)
[Startup_03Jun2024.txt](https://github.com/user-attachments/files/15532081/Startup_03Jun2024.txt)
[Combined_03Jun2024.txt](https://github.com/user-attachments/files/15532082/Combined_03Jun2024.txt)
[Video_03Jun2024.txt](https://github.com/user-attachments/files/15532083/Video_03Jun2024.txt)
[HeartRate_03Jun2024.txt](https://github.com/user-attachments/files/15532084/HeartRate_03Jun2024.txt)
[Error_03Jun2024.txt](https://github.com/user-attachments/files/15532085/Error_03Jun2024.txt)

**Comment by cagnulein** [comment]
unfortunately it doesn't write this information in the log. That's so strange. Maybe you can try to restore the factory setings and DON'T update the ifit app on the tablet. Ifit is probably trying to close the doors to qz on the last version.

**Comment by Mhann37** [comment]
Interesting. I did a factory reset in the hours preceding this and purposly didn't update ifit.

Should I try updating ifit?

**Comment by cagnulein** [comment]
you never tried the ifit updated app? If so yes give it a try, let's see if it's different.
Are you tech savvy? Another thing that we can do is to continue the QZ companion app that talks directly via USB instead of reading the logs. https://github.com/cagnulein/qdomyos-zwift/pull/1577

**Comment by Mhann37** [comment]
Updated ifit, lost ability to control incline. Now it's showing an incorrect and static cadence and watts, and nil speed.
Debug file attached for latest attempt

**Comment by cagnulein** [comment]
Hi, I don't see the log. Are you sure adb is working?

**Comment by Mhann37** [comment]
[debug-Mon_Jun_3_21_28_28_2024.log](https://github.com/user-attachments/files/15533230/debug-Mon_Jun_3_21_28_28_2024.log)

**Comment by cagnulein** [comment]
yeah it seems to get over and over the metrics from 11:05:14.4939
So we have to find a setup where we can read all the metrics.
Did you try with the adb logcat command from your pc, for example, to check if you can get real time metrics?

**Comment by Mhann37** [comment]
have been able to connect via ADB and run the grant permissions batch file.
also connected during live session and ran adb-debug which generated the attached logcat file
[logcat.txt](https://github.com/user-attachments/files/15541804/logcat.txt)

**Comment by cagnulein** [comment]
unfortunately the ifit on this console is not logging everything, i don't know how it's possible. It's the first time. If you want we can go on the USB way https://github.com/cagnulein/qdomyos-zwift/pull/1577
It's not about USB from outside, but the internal usb link from the tablet to the bike. In short: we need to close the ifit app at all and use qz there directly talking with the bike.

If you agree I can follow you on this but I have to warn you that it could be very time consuming because it's 100% R&D work.

let me know

**Comment by Mhann37** [comment]
That's a shame. Probably not worth my time in proceeding and just take the L on the app 👍 thanks anyway
