### ISSUE TITLE
[BUG] Auto follow workout based on heart rate

### ISSUE THREAD

**Issue by Rowdy** [cagnulein/qdomyos-zwift#2370]
**Description**
I've created a custom training program via Trainingroad, which uses their HR type workout. So I'd like the resistance to auto follow the workout based on my heart rate.

**Steps to reproduce the behavior:**
If I load the custom training program there is no change on the resistance of the bike.
I'm using a Schwinn IC4 and a SmartBike2k. Both are paired correctly. Resistance changes works with other programs like FTP workouts. I'm using my Apple watch with the qdomyos app as a heart rate monitor (which works fine).

**Expected behavior**
The resistance should change based on my heart rate and based on the custom training program.

**Screenshots**
![CleanShot 2024-06-03 at 13 43 56@2x](https://github.com/cagnulein/qdomyos-zwift/assets/309042/5b027763-c132-41df-8ece-703f9247ca88)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 17.4.1

[Archive.zip](https://github.com/user-attachments/files/15534526/Archive.zip)
Please find the debug.log and settings.qzs attached

**Comment by cagnulein** [comment]
hi @Rowdy are you able also to attach the TP program? I never saw anything like this.
BUT you can already write your own program on QZ based on your HR
Check this as a template https://github.com/cagnulein/qdomyos-zwift/blob/master/train-programs-examples/hrzones_1h_treadmill.xml

**Comment by cagnulein** [comment]
The attached file is not about hr

<workout_file>
	<author>fr3nks</author>
	<name>Zone 2 Workout</name>
	<description></description>
	<sportType>bike</sportType>
	<tags></tags>
	<workout>
		<SteadyState Duration="3600" Power="0.65"/>
	</workout>
</workout_file>

Just power :) 

I did on zones because HR has variability so putting a one value only will acts as continuously changing in the resistance, trust me :)

**Comment by Rowdy** [comment]
@cagnulein And what are these PID options about?
![IMG_6081](https://github.com/cagnulein/qdomyos-zwift/assets/309042/8dfa69bd-f0e4-4569-b9db-52ae5f579959)

**Comment by cagnulein** [comment]
With the pid hr min and max you can specify a custom hr range. So qz will try to keep the resistance on a way that your hr is always matching it. Of course if it's too narrow it's changing a lot

**Comment by Rowdy** [comment]
@cagnulein that's actually what I need. So I don't need to set a PID zone but can work with the specific values. And I don't have to use a training program for that as well, right?

**Comment by cagnulein** [comment]
Correct.
Let me know if you have any other questions

Il giorno lun 3 giu 2024 alle 21:36 Johns ***@***.***> ha
scritto:

**Comment by Rowdy** [comment]
I've no idea what the problem is but something is clearly not working here with my setup. The wattage thing looks fine. Haven't changed anything there.
But I wanted to try the PID training and used the specific min/max bpm values and also zones but the SS2K cranks up the wattage way to high, so that I cannot tread anymore and as soon as the heart rate is in the target area the SS2K releases the magnetic brake and also goes below zero so that I have to loose it in order that there is no hardware damage happening.

Is there any solution to this problem? I've also uploaded the debug file.
[debug-Mi__Juni_5_17_29_17_2024.log](https://github.com/user-attachments/files/15593130/debug-Mi__Juni_5_17_29_17_2024.log)

Thanks in advance.

**Comment by cagnulein** [comment]
Tomorrow I will check your case

**Comment by cagnulein** [comment]
@Rowdy i just did a patch for this. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you it. Thanks

**Comment by Rowdy** [comment]
I haven't had these issues anymore with the patched version, but it still acts sometimes kind of weird.
HR Zone is from 115-125 and I'm riding with 123bpm then it cranks up the watts from 110 to 170...

I've attached the log.
It would be beneficial if the resistance acts more often and faster but more subtle. A lot of times there were big increases / decreases ~20 watts...
[debug-Mi__Juni_5_17_29_17_2024.log](https://github.com/user-attachments/files/15647279/debug-Mi__Juni_5_17_29_17_2024.log)

It works way smoother in Zwift or Trainerroad.

**Comment by Rowdy** [comment]
Sorry mate. Here is the new debug.log.
I guess it would make more sense to do it on wattage instead of resistance since resistance is way of on the Schwinn?
[debug-Do__Juni_6_17_36_22_2024.log](https://github.com/user-attachments/files/15648704/debug-Do__Juni_6_17_36_22_2024.log)

**Comment by Rowdy** [comment]
These screenshots are good examples. I was already above the target HR zone and it still increased the resistance?
![IMG_6106](https://github.com/cagnulein/qdomyos-zwift/assets/309042/8368d3d4-a8a0-4dec-92ec-ab9eee5a6217)
![IMG_6107](https://github.com/cagnulein/qdomyos-zwift/assets/309042/47864374-a600-483b-9b21-0f855694247b)

**Comment by cagnulein** [comment]
try to change the step

> Author

in this log i don't see any connection, i guess you have more logs for today. anyway try to reduce the ss2k step and let's see if i'm right. 

another option will be using the ss2k like a ftms bike directly and so we can use the FTMS command like zwift and trainer road to use the erg mode (wattage).

Anyway let's do first the test with the ss2k step setting, thanks

**Comment by Rowdy** [comment]
I don't understand the options here. Is there any wiki for that settings?
![image](https://github.com/cagnulein/qdomyos-zwift/assets/309042/812aa220-c2d5-4d69-a745-2edf0b157226)

**Comment by cagnulein** [comment]
reduce the shift step, for example put a 90 instead of a 900. this is the step motor for each resistance level, probably too much for your case
