### ISSUE TITLE
[BUG] Watt values are not correct on Schwinn IC4

### ISSUE THREAD

**Issue by Rowdy** [cagnulein/qdomyos-zwift#2371]
**Description**
I'd like to see the values for Watt and resistance. I've configured the tiles to show these values but they are way off. I read that the resistance is not being sent via bluetooth and therefore calculated. Nevertheless the Watt values are also way off.

**Steps to reproduce the behavior:**
I'm using a Schwinn IC4 as my bluetooth bike. When I start a training the display of the watt values and also resistance is way off. In the screenshot the wattage should be around 70-100.

**Expected behavior**
The watt value should be accurate from the Schwinn IC4. It works in Kinetic or other apps without qdomyos.

**Screenshots**
![IMG_6072 2](https://github.com/cagnulein/qdomyos-zwift/assets/309042/51e62cb5-1514-43c4-b96c-c4633a9ed033)

**Comment by cagnulein** [comment]
hi @Rowdy i need a debug log with the issue. Thanks

**Comment by Rowdy** [comment]
I think the watt values are actually accurate. but the resistance is not. The Schwinn bike only has levels from 0 - 100.
[debug-Mo__Juni_3_20_45_19_2024.log](https://github.com/user-attachments/files/15538415/debug-Mo__Juni_3_20_45_19_2024.log)

**Comment by cagnulein** [comment]
Yes becauee your bike doesn't send resistance over Bluetooth so qz is calculating it from cadence and wattage. You can play with the schwinn settings on qz to change the algorithm but of course will not be the same of the bike.

It's unfortunately a lack on the schwinn firmware

**Comment by Rowdy** [comment]
@cagnulein got it thanks!
The SmartSpin2k advanced settings won't help with that, right? What are these about?

**Comment by cagnulein** [comment]
Nope only if you use the ss2k

@doudar  can give you more Info about this device!

**Comment by cagnulein** [comment]
Hah Ok so you set the step setting in order to have 100 steps to go to the full resistance?

**Comment by cagnulein** [comment]
> @cagnulein got it thanks!
> 
> The SmartSpin2k advanced settings won't help with that, right? What are these about?

So yes the advanced ones are right for your setup. There is a ticket here on github about a user with ic4 and ss2k with this settings 

Let me know if you can't find it

**Comment by doudar** [comment]
Creating our own method for calculating watts on the IC4 is on my timeline, however I'm currently not sure when I'll get development time for it. My work currently is a **lot** bit crazy.

**Comment by Rowdy** [comment]
> > @cagnulein got it thanks!
> > The SmartSpin2k advanced settings won't help with that, right? What are these about?
> 
> So yes the advanced ones are right for your setup. There is a ticket here on github about a user with ic4 and ss2k with this settings
> 
> Let me know if you can't find it

this one https://github.com/cagnulein/qdomyos-zwift/issues/392 ?
not sure if that's the correct one

**Comment by cagnulein** [comment]
This one https://github.com/cagnulein/qdomyos-zwift/pull/666
