### ISSUE TITLE
[BUG] PC app do detect that Domyos Run500 is connected while the treadmill is turned off.

### ISSUE THREAD

**Issue by VNT974** [cagnulein/qdomyos-zwift#2372]
**Describe the bug**
Opened the PC domyos-zwift app to take a screenshoot of the menu for another issue, and I was surprised to see that the app detected the treadmill /opened the dashboard, while the treadmill is turned off but power cord was connected in the wall. But for sure the treadmill is off.

**Expected behavior**
I expect PC domyos-zwift to not detect a BT connexion from a turned off device.

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows 11 Pro
Version: 23H2 (22631.3593)

**Append a debug log**
[debug-Tue_Jun_4_08_39_51_2024.log](https://github.com/user-attachments/files/15542645/debug-Tue_Jun_4_08_39_51_2024.log)

**Comment by cagnulein** [comment]
Yes that's normal, windows is reporting devices also when the devices are
missing

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 4 giu 2024 alle 06:47 VNT974 ***@***.***> ha
scritto:

**Comment by VNT974** [comment]
For now I will just use it for my treadmill, but what happen if there are multiple devices ?
