### ISSUE TITLE
[BUG] No data replication on the app

### ISSUE THREAD

**Issue by Unkpat** [cagnulein/qdomyos-zwift#2373]
**Describe the bug**
Nothing is replicate on the app 

**To Reproduce**
Launch a run on the treadmill 
Launch the app on my phone
Increase the speed or the inclinaison on the treadmill 
Nothing is replicate on the app

**Expected behavior**
Replication of the speed and inclinaison on the app

**Screenshots**

![mar  juin 4 13_30_11 2024](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/138da41f-55c5-4b73-8593-ce8e6f60c661)
![mar  juin 4 13_30_13 2024_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/5051a018-1339-494a-860d-81729018dc78)
![mar  juin 4 13_30_13 2024_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/f7a8adce-2a58-4c1d-acf8-66fd14548665)
![mar  juin 4 13_30_14 2024_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/716844d7-5427-4111-a749-ed37dbd90128)
![mar  juin 4 13_30_14 2024_heart](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/a0fcb55c-424a-4255-87e7-752b8fefbccc)
![mar  juin 4 13_30_14 2024_power](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/043dc97b-7e3a-48b0-b0c0-a0f3e1461f29)
![mar  juin 4 13_30_14 2024_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/837d879e-39e9-47e2-a155-982f8a1450e8)
![mar  juin 4 13_30_14 2024_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/863eef61-b5af-4f35-99c6-e4aca3cd7fd8)
![mar  juin 4 13_30_15 2024_power_badge](https://github.com/cagnulein/qdomyos-zwift/assets/171686442/673cdfda-6797-40c1-a22b-b3f02a30c988)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 9
 - OS: Android
 - Version: 12 SKQ1.211.19.001

**Comment by cagnulein** [comment]
hi @Unkpat I need a debug log to understand your issue. Thanks

**Comment by cagnulein** [comment]
[debug-Tue_Jun_4_13_29_25_2024.log](https://github.com/user-attachments/files/15551014/debug-Tue_Jun_4_13_29_25_2024.log)

**Comment by cagnulein** [comment]
@Unkpat let me understand better your issue: which is the issue? the fact that you can't see the metrics or the fact that you can't control the treadmill?

**Comment by Unkpat** [comment]
I can note see the info of my treadmill on the app.
Eg : Speed on my treadmill : 14 km/h
Speed on the app : 0 km/h

Same for all info.

Le mar. 4 juin 2024, 14:09, Roberto Viola ***@***.***> a
écrit :

**Comment by Unkpat** [comment]
The info = The metrics sorry :)

**Comment by cagnulein** [comment]
so this means that the companion can't collect the stats from the treadmill. Which device did you choose from the companion side?

**Comment by Unkpat** [comment]
I choose on the treadmill and app : Norditrack Incline Trainer x7i option.

But my treadmill is a Norditrack exp14i.


Le mar. 4 juin 2024, 14:38, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
try to use on the companion the x14i and restart the treadmill. let me know

**Comment by Unkpat** [comment]
There is not x14i on the app and the treadmill.

Le mar. 4 juin 2024, 15:59, Roberto Viola ***@***.***> a
écrit :

**Comment by Unkpat** [comment]
Yes sorry it's well on x14i on the treadmill but there is no this setting
on the app.

Le mar. 4 juin 2024, 17:33, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
Yes don't mind about the phone app, the important one is the companion. So
it was x14i already or did you set now? Any changes?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 4 giu 2024 alle 17:44 Unkpat ***@***.***> ha
scritto:

**Comment by Unkpat** [comment]
It's now set on x14i on the treadmill, I restarted it but it's the same. No
metrics.

Le mar. 4 juin 2024, 17:46, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
Ok so try the 7.5s
There are different methods to read the metrics and we have to find which is the right one for your treadmill

**Comment by Unkpat** [comment]
Same, no metrics.

Are these steps correct ? :
- Start treadmill
- Tap 10 times, 7 seconds, 10 times
- Enter the number and access to Privilege mode
- Open QZ and put it in "T7.5 treadmill"
- Leave and restart treadmill
- Go to ifit and launch a training
- Go on my phone and open QZ (with WiFi, Bluetooth, localisation)

Is it correct ?

Many thanks to you for your support 🙏


Le mar. 4 juin 2024, 19:23, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
Yes they are the right steps.
One thing that we can also try is to restore the factory reset of the
treadmill and NOT update the ifit app. Newer ifit version could have
removed the ability the metrics

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 4 giu 2024 alle 20:39 Unkpat ***@***.***> ha
scritto:

**Comment by Unkpat** [comment]
Ok i will do that in next days and I will keep in touch with you.

Many thanks and have a great evening.

Le mar. 4 juin 2024, 20:43, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
@Unkpat any news?
