### ISSUE TITLE
Reebok GT50 not syncing with Zwift

### ISSUE THREAD

**Issue by Krisdebastos** [cagnulein/qdomyos-zwift#2375]
**Describe the bug**
Originally when I connected the treadmill to the QZ app, it managed to connect the treadmill to Zwift, however the readings on the tiles on QZ were not registering the readings on the treadmill. Any changes made on the treadmill did nothing on QZ and when I went into Zwift, any of the running events would have the avatar walking at 3km/h and did not see any increase in speed or incline made on the treadmill. 
I then adjusted a few settings on QZ and managed to get QZ to see the changes but now it does not connect to Zwift. On the home page it shows the 3 blocks trying to connect with the little owl saying I must try wake the devices up. QZ is still running in the background.

**To Reproduce - Second Incident**
1. Powered Treadmill
2. Opened QZ and saw "Found Reebok0740" 
3. Treadmill beeped 
4. Adjusted speed and incline, QZ saw changes made
5. Opened Zwift 
6. Connection screen did not see any device

*To Reproduce - First Incident**
1. Powered Treadmill
2. Opened QZ and saw "Found Reebok0740" 
3. Treadmill beeped 
4. Opened Zwift and selected WahooTRD for Cadence and Speed, Selected WahooHRT for Heart Rate, these were the only option available
5. an event
6. Avatar did nothing but walk @ 3km/h

**Expected behavior**
I power the treadmill, then connect QZ to the treadmill, minimize QZ and log into Zwift. After the devices are connected I select an event and control the Avatar via the treadmill.

**Screenshots**
![Screenshot_20240604_191228 1](https://github.com/cagnulein/qdomyos-zwift/assets/171838394/20f79eb1-e053-435b-84d5-f7702389f069)

First incident image on QZ showing speed at 1km/h but the belt is still

**Smartphone (please complete the following information):**
 - Device: Samsung Z Fold5
 - OS: UI 6.1
 - Version Android v14

**Append a debug log**
[debug-Wed_Jun_5_17_49_54_2024[1].log](https://github.com/user-attachments/files/15604473/debug-Wed_Jun_5_17_49_54_2024.1.log)
[debug-Wed_Jun_5_17_50_46_2024[1].log](https://github.com/user-attachments/files/15604479/debug-Wed_Jun_5_17_50_46_2024.1.log)
[debug-Wed_Jun_5_17_55_09_2024[1].log](https://github.com/user-attachments/files/15604481/debug-Wed_Jun_5_17_55_09_2024.1.log)

**Comment by cagnulein** [comment]
the problem is that you disable the virtual device setting in the experimental settings. It must be enabled to run zwift. Also enable the dircon setting there too for zwift
Let me know

**Comment by Krisdebastos** [comment]
Thanks, will look into it. 
I noted though, if I enable the virtual settings, I cant use treadmill controls. does that mean I need to use QZ to increase Zwift and then again increase it on my treadmill to align?

**Comment by cagnulein** [comment]
do this so:
- enable virtual device
- enable dircon
- disable virtual bluetooth device

it should fix your issue

let me know

**Comment by Krisdebastos** [comment]
Under what heading is the dircon setting?
All other changes have been made.

**Comment by cagnulein** [comment]
@Krisdebastos any news?
