### ISSUE TITLE
Can’t get any resistance 

### ISSUE THREAD

**Issue by jack19681** [cagnulein/qdomyos-zwift#2376]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@jack19681 i don't see anything here
