### ISSUE TITLE
No resistance on bike 

### ISSUE THREAD

**Issue by jack19681** [cagnulein/qdomyos-zwift#2377]
[debug-Tue_May_7_04_43_57_2024.log]
[debug-Tue_May_7_04_43_57_2024.log](https://github.com/user-attachments/files/15684880/debug-Tue_May_7_04_43_57_2024.log)
(https://github.com/user-attachments/files/15684484/debug-Tue_May_7_04_43_57_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Hi I’m really not that good at this so hopefully you have got the debug log. Been using the app for a long time and it’s been brilliant then all of a sudden I’m getting no resistance on my echelon bike when set up to do a peloton class 
Many thanks

**Comment by cagnulein** [comment]
@jack19681 any news?
