### ISSUE TITLE
[BUG] QZ app crashes when pairing with Technogym Run treadmill

### ISSUE THREAD

**Issue by jlettFlintfox** [cagnulein/qdomyos-zwift#2380]
**To Reproduce**
1. On Technogym Run treadmill, press bluetooth button and activate bluetooth
2. Open QZ app, treadmill is detected and 2 seconds later app crashes.  
3. This is a "Technogym Run" treadmill, not MyRun, but tried the experimental feature "Enable MyRun" however the app still crashes

**Smartphone (please complete the following information):**
 - Device: Samsung zFlip
 - OS: Android
 
[debug-Mon_Jun_10_12_07_03_2024.log](https://github.com/user-attachments/files/15755248/debug-Mon_Jun_10_12_07_03_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 10 giu 2024 alle 02:38 jlettFlintfox ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@jlettFlintfox fixed!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9443843617

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by jlettFlintfox** [comment]
Thanks for looking in to this so quickly. Unfortunately that new version didn't help.  Attached is a new debug log.

[debug-Tue_Jun_11_17_22_57_2024.log](https://github.com/user-attachments/files/15782756/debug-Tue_Jun_11_17_22_57_2024.log)

**Comment by cagnulein** [comment]
i guess i got it. could you please try this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/9460856927 ?

**Comment by jlettFlintfox** [comment]
Looking better.  App doesn't crash any longer, but unfortunately none of the treadmill/cadence data shows in the tiles, and pressing the incline buttons doesn't control the treadmill.  Debug log attached.

[debug-Tue_Jun_11_20_11_38_2024.log](https://github.com/user-attachments/files/15784708/debug-Tue_Jun_11_20_11_38_2024.log)

I also tried with Technogym experimental MyRun option but that caused a crash on startup, although understandable as this is a "Run" not "MyRun" version.

**Comment by cagnulein** [comment]
mmm that's strange the treadmill sends the only some metrics but not everything...
Is it working with any other apps? if so which ones?

**Comment by jlettFlintfox** [comment]
Yes.  I've used the treadmill with Zwift, and works OK but I was hoping to use QZ to get the automatic inline feature, which Zwift does not support with treadmills.

**Comment by cagnulein** [comment]
I tried another thing https://github.com/cagnulein/qdomyos-zwift/actions/runs/9511986725

**Comment by jlettFlintfox** [comment]
Unfortunately no change with the new version.  The steps I followed are:
1. Turn on treadmill, and switch on bluetooth option
2. Turn on QZ, treadmill detected
3. Start treadmill using treadmill buttons and adjust speed
4. No data shown on the QZ app
5. Pressed the flashing red start button in QZ
6. No data shown on the QZ app
7. Press the QZ stop button

[debug-Fri_Jun_14_20_42_47_2024.log](https://github.com/user-attachments/files/15836165/debug-Fri_Jun_14_20_42_47_2024.log)

[Screenshot_20240614_203822](https://github.com/cagnulein/qdomyos-zwift/assets/67404425/12a86980-74d9-4b01-a49d-154679c94249)

I did also try switching on the Technogym MyRun setting, but as soon as the treadmill starts to move (step 3 above), the app shuts down.

**Comment by cagnulein** [comment]
last thing: could you try to disable the virtual bluetooth device on the experimental settings and restart QZ?
if it still doesn't work I need this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using your treadmill directly on zwift

Let me know!

**Comment by jlettFlintfox** [comment]
Unfortunately disabling the virtual bluetooth device in QZ didn't improve things; while QZ connects to the treadmill, it does not show any data.

I have followed the steps in the link you provided and attach the btsnoop log file below:
[btsnoop_hci.log](https://github.com/user-attachments/files/15897674/btsnoop_hci.log)

The steps I followed were:
1. Enabled debug mode on android phone, turned on Bluetooth HCI snoop log, and restarted
2. Started Zwift
3. Activated bluetooth on treadmill and connected Zwift to treadmill (run mode)
5. Started a running route
6. Manually adjusted treadmill speed up and down, as well as treadmill inclination
7. Stopped Zwift and treadmill
8. Disabled BT Snoop Log on phone developer options
9. Run a Full bug report and uploaded to PC, extracted btsnoop file and attached.

Ultimately what I am trying to achieve is to run Zwift, connected to treadmill via QZ app on phone, and use the option for QZ to read Zwift inclination and automatically control treadmill inclination.

**Comment by cagnulein** [comment]
Hi @jlettFlintfox I checked the log but there is no trace at all of blueooth connections with your treadmill from zwift.

Just to be sure: are you running zwift on the same phone where you are using the btsnoop log?

**Comment by jlettFlintfox** [comment]
Let me try it again.  Attached is an updated btsnoop file which looks to have some data this time.

[btsnoop_hci.log](https://github.com/user-attachments/files/15946674/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno lun 24 giu 2024 alle 00:57 jlettFlintfox ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@jlettFlintfox ok i guess i got it, could you please try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/9640716313

**Comment by jlettFlintfox** [comment]
That version is better in that the pause/play button doesn't flash red when connected anymore, however the tiles don't show any data i.e. no speed, cadence, or incline.

I haven’t yet tried connecting to QZ from Zwift running on a separate device (PC) but I'm assuming if the tiles don't show any data then Zwift will be the same.

**Comment by cagnulein** [comment]
could you please share a debug log from this?

**Comment by jlettFlintfox** [comment]
Attached is the debug log for a session where I connected the treadmill to QZ and adjusted the treadmill speed and treadmill incline using levers on the treadmill itself.  No speed or incline was updated on QZ tiles, although I noticed that cadence occasionally showed a value (usually 50) but would quickly revert back to 0.

[btsnoop_hci.log](https://github.com/user-attachments/files/15984320/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks but i need a https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

thanks

**Comment by cagnulein** [comment]
ok i guess i undertsood the issue, could you please also enable only the "power sensor as a treadmill" setting under the accessories, power sensor section. Change only this.
Let me know!

**Comment by cagnulein** [comment]
ok perfect, the issue now it seems that your treadmill is exposing a FTMS interface (the classic on with inclination and control) but it seems it doesn't handle it correctly. indeed also zwift use the same QZ interface..are you able to contact technogym about this? are you sure this is the latest firmware for your treadmill?

**Comment by jlettFlintfox** [comment]
Definitely the latest firmware; the treadmill just did a full OTA update earlier today.  

I was thinking I might try a commercial app alternative, similar to Zwift, but one that controls treadmill incline like Kinomap.  Assuming that doesn't work with the Technogym treadmill to control incline I can use that as a demonstration to Technogym to get them to resolve.  Otherwise I'm not sure what I should say specifically to them to get them to fix it.  

If I try Kinomap and it does happen to work and controls the treadmill, would that help you to make changes to QZ to control the treadmill if I create another bluetooth log?

**Comment by cagnulein** [comment]
> Definitely the latest firmware; the treadmill just did a full OTA update earlier today.

hah ok perfect.

> 
> I was thinking I might try a commercial app alternative, similar to Zwift, but one that controls treadmill incline like Kinomap. Assuming that doesn't work with the Technogym treadmill to control incline I can use that as a demonstration to Technogym to get them to resolve. Otherwise I'm not sure what I should say specifically to them to get them to fix it.

Yes it could be perfect!

> 
> If I try Kinomap and it does happen to work and controls the treadmill, would that help you to make changes to QZ to control the treadmill if I create another bluetooth log?

yes absolutely! I was about to tell you ;)
