### ISSUE TITLE
Connect QZ to Peloton

### ISSUE THREAD

**Issue by RowYourBoatWill** [cagnulein/qdomyos-zwift#2384]
**Describe the bug**

**To Reproduce**
1 - Load QZ
2 - Load Row class on Peloton
3 - Attempt to connect to Bluetooth rower

**Expected behavior*
* Connect QZ to Android Peloton app

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Lenovo M10
 - Android 12

**Append a debug log**
HCI file 1 is QZ running on iOS attempting to connect to Peloton on Android
HCI2 file is TEST version of QZ running on Peloton Tablet (Android 10) attempting to connect to Peloton on Android

[btsnoop_hci.log](https://github.com/user-attachments/files/15803245/btsnoop_hci.log)
[btsnoop_hci2.log](https://github.com/user-attachments/files/15803225/btsnoop_hci2.log)

  
**Additional context**

**Comment by cagnulein** [comment]
#2226

**Comment by cagnulein** [comment]
> HCI file 1 is QZ running on iOS attempting to connect to Peloton on Android

checked this; i can see the peloton app looking for the QZ on iOS but here the ios device is seems that it's not broadcasting the QZ services: can you try in this scenario to check on android if you can see the FTMS service from QZ? I guess that's the main reason why you can't see anything on peloton on android

**Comment by cagnulein** [comment]
> HCI2 file is TEST version of QZ running on Peloton Tablet (Android 10) attempting to connect to Peloton on Android

here i can't see any request at all. i guess peloton is not trying to contact it at all. So let's keep QZ on iOS for these tests, it seems better at least

**Comment by cagnulein** [comment]
ok but are you able to just check if in the context 1 are you getting FTMS data on nrfconnect on your peloton android device from qz on ios?

**Comment by RowYourBoatWill** [comment]
Hey, I uploaded a snoop file that is the C2 connecting to Android Peloton and the nRF Connect screenshots.I uploaded them to the other Peloton connection ticket (I hope that’s what you were after).ThanksRossSent from my iPhoneOn 12 Jun 2024, at 10:36 PM, Roberto Viola ***@***.***> wrote:﻿
ok but are you able to just check if in the context 1 are you getting FTMS data on nrfconnect on your peloton android device from qz on ios?
