### ISSUE TITLE
[BUG] Sole F85 ENT 2023 not receiving speed or inclination changes from QZ app

### ISSUE THREAD

**Issue by kristianberge** [cagnulein/qdomyos-zwift#2385]
**Describe the bug**

Using the QZ Fitness app on an ipad air (5th gen) ios 17.5.1. The app finds the treadmill (Sole F85 ENT 2023 software v1.5) and displays speed and inclincation from the treadmill, also when i change speed/incline on the treadmill. I am also able to start/stop the treatmill at the speed the treadmill was last on, but when i push + or - on speed or inclination nothing happens both in the app and on the treadmill.
I tried to check the Sole F63/65/TT8 one by one and exactly the same. Also tried all these four options with experimental inclination on but then the app does not read speed/inclincation from the treadmill. With fast inclination experimental activated the app still reads speed and inclincation but also not sending to the treadmill.

I append a debug log where i pressed + speed, - speed, + incl, - incl 5 times each.

Any help would be appreciated!!

Best regards,
Kristian
[debug-Wed_Jun_12_22_50_32_2024.log](https://github.com/user-attachments/files/15810871/debug-Wed_Jun_12_22_50_32_2024.log)

**Comment by kristianberge** [comment]
To follow up on my own problem. After more searching and reading I see that a similar problem has been reported (most likely the same model as I have) in issue #2086. I will collect the Bluetooth HCI snoop log this afternoon and post it here.

**Comment by cagnulein** [comment]
Hi @kristianberge are you able to change the speed and the incline directly from the sole app?

**Comment by kristianberge** [comment]
Hi @cagnulein, haven't tried yet, but was able to control incline with the kinomap app. I will test with the sole app this afternoon and post the Bluetooth HCI snoop log as described here: https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by cagnulein** [comment]
that's perfect!

**Comment by kristianberge** [comment]
Hello again,
So i tried running the sole app on an android phone but I can't find any controls for speed, only inclination.
Here is the full bug report after the turning the sole f85 ent 2023 on and off from the app and turning the inclination up and down a few times. Is it enough to learn how the app communicates with the treadmill?
[Uploading bugreport-bluejay-AP1A.240505.004-2024-06-13-18-28-24.zip…]()

**Comment by cagnulein** [comment]
So you change the inclination from the treadmill itself? In case no, I need to see a command from the phone. You said before that kinomap can control it? In case create a bug report from kinomap so

Let me know

**Comment by kristianberge** [comment]
Sorry the confusion. No I adjusted the inclination from the sole app.

**Comment by kristianberge** [comment]
posted the entire log in the previous post but replaced it with only the btsnoop_hci.log file.

**Comment by cagnulein** [comment]
Ok I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 13 giu 2024 alle 20:12 kristianberge ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok, good news, i can see all the frames! bad news, it's a completely new protocol, so i need time to implement it, but don't worry I will do it

**Comment by cagnulein** [comment]
@kristianberge wait i already handled this! send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the newer ios version. keep the "inclination experimental" disabled!
Let me know

**Comment by kristianberge** [comment]
Just did! Thank you for superb followup!

**Comment by kristianberge** [comment]
Update. I installed your new ios version. Strange behaviour. With the standard settings the app connected to by smart bike/trainer, was not able to change connected unit (if there isnt some way to select bluetooth unit within the app). Har du disconnect power from trainer and restart app, then it connected to my Sole F85 ENT 2023. The app read speed and inclination from the treadmill, and I was able to increase inclincation with 1 degree. After the first click on inclination+1 it was no longer able to change inclincation anymore. No response from speed. Should maybe have started by pressing speed. 
Tried to completely restart the app a few times, still no respons (but still reads data from the treadmill). By turning on inclination (experimental) it does not read data from the treadmill. Tried F/63/F65/TT8 one by one. same experience. can read data but not transmit inclincation/speed to the treadmill.

Any ideas?

**Comment by kristianberge** [comment]
another fast update. on the treadmill i pressed finish workout -> delete. then started a new session and opened the app. this time i pressed speed + / - in the ios app without any response, then pressed inclination + and again the treadmill received the signal, but only the very first time and then stayed at 1 percent inclination and after that did not respond anymore.

**Comment by cagnulein** [comment]
> I installed your new ios version. Strange behaviour. With the standard settings the app connected to by smart bike/trainer, was not able to change connected unit

you have to seleect the f85 in the advanced settings, manual device. press ok and restart qz



> he app read speed and inclination from the treadmill, and I was able to increase inclincation with 1 degree. After the first click on inclination+1 it was no longer able to change inclincation anymore

ok perfect, you have also to set inclination step setting from 0.5 to 1 because your treadmill is not handling 0.5 increment of the inclination. speed is not handled from the firmware of your treadmill



> By turning on inclination (experimental) it does not read data from the treadmill. Tried F/63/F65/TT8 one by one. same experience. can read data but not transmit inclincation/speed to the treadmill.

leave all these disabled, they don't work with your treadmill. your treadmill is a ftms standard one without speed control. try to power cycle the treadmill

Let me know

**Comment by kristianberge** [comment]
Thank you!
Consider moving the unit (manual) selector somewhere more visible ;)
After changing the inclination step to 1 it works perfect to change inclination from the ios app!
That speed is not handled from the firmware as bad news as this was the purpose of using the app, to run structured workouts. particularly when i do 20x 45/15 sec intervals the constant pushing on the console sucks and the workout functions on the treadmill itself is utter garbage.

Well, thank you again for the fast help.
I assume that if there is a firmware limitation to control speed on the treadmill there is nothing more we can do? Why on earth would they set such a limitation on the machine.....

Best regards,
Kristian

**Comment by cagnulein** [comment]
for other users i suggested to sold 2 wires and 2 relays to the speed buttons of the treadmill itself. in this way QZ on PC or MAC can talk also to change the speed.



> Consider moving the unit (manual) selector somewhere more visible ;)

which selector?

**Comment by kristianberge** [comment]
> for other users i suggested to sold 2 wires and 2 relays to the speed buttons of the treadmill itself. in this way QZ on PC or MAC can talk also to change the speed.
thanks for the tip, but thats a step too far for me, at least at this moment..

> which selector?
I meant where I can manually change the treadmill instead of the bike/trainer. but no biggie. On the main screen there is a large bluetooth symbol. It would be intuitive that I i press the bluetooth button I would be able to choose the bluetooth device/treadmill.

Good work with the app! You can close the ticket ;)
5 stars for service, 1 star for the structured workout function  on the sole f85

**Comment by cagnulein** [comment]
> thanks for the tip, but thats a step too far for me, at least at this moment..

ok let me know if you will change your mind

> I meant where I can manually change the treadmill instead of the bike/trainer. but no biggie. On the main screen there is a large bluetooth symbol. It would be intuitive that I i press the bluetooth button I would be able to choose the bluetooth device/treadmill.

hah ok, good observation

> Good work with the app! You can close the ticket ;)

oki!

> 5 stars for service, 1 star for the structured workout function on the sole f85

sorry but it's not my fault, i can reverse engineer everything but i can't change the work of other people in a control board. you can try to ask sole about this

**Comment by kristianberge** [comment]
I sent an email to sole about this issue. will let you know if they tell me something useful!

**Comment by cagnulein** [comment]
if you want to rate the service on the app store, it will be very important for me! Every review counts! Thanks
