### ISSUE TITLE
[BUG] Not updating heartrate on QZ app (iOS + applewatch)

### ISSUE THREAD

**Issue by anseok83** [cagnulein/qdomyos-zwift#2386]
**Describe the bug**
_A clear and concise description of what the bug is._

Hello, it's been a while since my last report.
Before describing bug, I want to say thank you for your great work. :)

The bug I want to report is about updating heartrate.
My equipment is Iphone 12mini and Applewatch series 6.

Version of QZ app is 2.16.51.

When I use QZ app on iphone with QZ app on my apple watch, heart rate is correctly updating on apple watch, but not on iphone.
(for example, iphone shows same HR and never update the value, when my HR is changing for sure..)

**To Reproduce**
_Steps to reproduce the behavior:
4. See error_

Maybe you can easily reproduce with my explanation above.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

My equipment is Iphone 12mini and Applewatch series 6. (iOS 17.5.1)
Version of QZ app is 2.16.51.

**Smartphone (please complete the following information):**

My equipment is Iphone 12mini and Applewatch series 6. (iOS 17.5.1)
Version of QZ app is 2.16.51.

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Currently, I don't have a log on this. If you need, I can make a log on this...

  
  
**Additional context**

I wan't to report another problem, which is app crush. Maybe I can report this on another issue. Thx!

**Comment by cagnulein** [comment]
yes please a debug log is required
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 13 giu 2024 alle 02:53 ans ***@***.***> ha
scritto:

**Comment by anseok83** [comment]
Thanx for reply!

Here is the short log that HR in QZ app doesn't change (as 97), while HR in applewatch changes (to 93).
You can check the log and pictures. 

[debug-목_6월_13_20_13_41_2024.log](https://github.com/user-attachments/files/15830102/debug-._6._13_20_13_41_2024.log)


![IMG_0018](https://github.com/cagnulein/qdomyos-zwift/assets/7554736/e12f1561-4596-49a3-a3b2-9b059e0ea0ec)
![IMG_0017](https://github.com/cagnulein/qdomyos-zwift/assets/7554736/3905adf2-cedb-45b0-b246-7e3c4ad642f0)


Thank you,
Anseok

**Comment by cagnulein** [comment]
@anseok83 are we ok with this?

**Comment by anseok83** [comment]
> @anseok83 are we ok with this?

Yes. HR update works perfectly now! 👍
