### ISSUE TITLE
[BUG] Does not connect to Proform TDF with Pi 0 W

### ISSUE THREAD

**Issue by cianpdx** [cagnulein/qdomyos-zwift#2387]
**Describe the bug**

Does not connect to Proform TDF when compiled and run on Pi 0 W

**Expected behavior**
Expect to match behavior as iphone app

**Screenshots**
Screenshot of Iphone working (proving bike is able to connect etc etc)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/46210891/269be006-0831-4af2-a4d2-cf4f98a87d72)

bike bluetooth details

![image](https://github.com/cagnulein/qdomyos-zwift/assets/46210891/96726f50-d67b-41c4-854e-766b2f8d10ad)

**Pi (please complete the following information):**
Raspbian 11 bullseye (not working)
[output.txt](https://github.com/user-attachments/files/15813731/output.txt)

**Smartphone (please complete the following information):**
iPhone 14 mini (working)

**Append a debug log**

attached
  
**Additional context**

building took several hours so I might look to cut out / reduce to only the applicable functions for my usage to make it more lightweight

**Comment by cagnulein** [comment]
the main issue is that the raspberry isn't finding the bike at all. check on the bluetooth side of the raspberry if you can find it
let me know

**Comment by cianpdx** [comment]
here is the log from the iphone which is **working**

[debug-Wed_Jun_12_21_43_51_2024.log](https://github.com/user-attachments/files/15813814/debug-Wed_Jun_12_21_43_51_2024.log)

**Comment by cianpdx** [comment]
> the main issue is that the raspberry isn't finding the bike at all. check on the bluetooth side of the raspberry if you can find it let me know

OK i will try some generic BLE scanner on the Pi

**Comment by cianpdx** [comment]
a generic BLE scan on the pi does return the bike:

`Device f0:c0:b7:de:df:26 (random), RSSI=-57 dB
  Appearance = 0000
  Flags = 05
  Complete 128b Services = 00001533-1412-efde-1523-785feabcd123
  Complete Local Name = I_EB`

**Comment by cagnulein** [comment]
That Mac address is not in the debug log of qz. Did you try again?

**Comment by cianpdx** [comment]
yep same thing

strange is i dont see the mac address even on the iphone log (which works fine?)

**Comment by cianpdx** [comment]
from working iphone logs:

"Found new device: I_EB (00:00:00:00:00:00)"

**Comment by cagnulein** [comment]
I'm at the hospital right now, I will investigate later this week

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 15 giu 2024 alle 07:25 cianpdx ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
iphone doesn't collect mac address so that's not important. try to scan first from the generic scan on pi0 and then run QZ

**Comment by cianpdx** [comment]
ok i ran generic scan (found), then q (not found), then generic scan again (found)

very strange

**Comment by cagnulein** [comment]
try a thing , on the raspberry enable this one

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/2f20cb16-db29-4609-b240-bca3ddd70a6c)

and restart qz

let me know

**Comment by cianpdx** [comment]
what is the flag for that? I don't see it listed here

https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/30_usage.md

**Comment by cagnulein** [comment]
there isn't the flag for this, use the UI for this

**Comment by cianpdx** [comment]
gui isn't going to work on pi0 i think... maybe i try a newer pi

but -no-gui finds the bluetooth but doesn't recognize as a bike?
,
```
Sat Jul 13 22:18:35 2024 1720905515230 Debug:   Discovered:  "I_EB" "F0:C0:B7:DE:DF:26" Num UUIDs 1 total device 0 cached RSSI -53 Num ManufacturerData 0
qt.bluetooth.bluez: Discovered:  "I_EB" "F0:C0:B7:DE:DF:26" Num UUIDs 1 total device 0 cached RSSI -53 Num ManufacturerData 0
```

[i_eb_found.txt](https://github.com/user-attachments/files/16203678/i_eb_found.txt)

**Comment by cagnulein** [comment]
remove the "" from I_EB in the arguments.

also for any flag, you can add it to the settings. there is a file with all your settings under the directory .config on your local user
be aware: you have to edit it carefully

**Comment by cianpdx** [comment]
`sudo ./qdomyos-zwift -no-gui -name I_EB`

still no connection. trying a pi3 and 4 in a few mins

**Comment by cagnulein** [comment]
ok midnight here. try also without the name arguments
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 14 lug 2024 alle ore 00:07 cianpdx ***@***.***>
ha scritto:

**Comment by cianpdx** [comment]
no problem at all 

same response on pi3B as 0W
1. gui can't run (to test that experimental option)
2. I_EB is listed on bluetooth scan but no connect

**Comment by cagnulein** [comment]
gui can't run? what's the error? i guess you forgot to install the qml dependencies?
for the i_eb share me a log without the name argument passed
thanks

**Comment by cianpdx** [comment]
It finds the bike:

`
Sat Jul 13 22:18:35 2024 1720905515230 Debug:   Discovered:  "I_EB" "F0:C0:B7:DE:DF:26" Num UUIDs 1 total device 0 cached RSSI -53 Num ManufacturerData 0
qt.bluetooth.bluez: Discovered:  "I_EB" "F0:C0:B7:DE:DF:26" Num UUIDs 1 total device 0 cached RSSI -53 Num ManufacturerData 0
`

but does not enter this branch in bluetooth.cpp

`            } else if ((b.name().startsWith(QStringLiteral("I_EB")) || b.name().startsWith(QStringLiteral("I_SB")) ||
                        b.name().toUpper().contains(QStringLiteral("_IFIT_BIKE"))) &&
                       !proformBike && filter) {`

[i_eb_found_no_name_arg.txt](https://github.com/user-attachments/files/16229819/i_eb_found_no_name_arg.txt)

**Comment by cianpdx** [comment]
aha i found the issue

it was never getting to the name check because it was returning here:

`#if !defined(Q_OS_ANDROID) && !defined(Q_OS_IOS)
    if(!homeformLoaded) {
        qDebug() << "homeform not yet loaded";
        return;
    }
#endif `


so I just comment out the return

`#if !defined(Q_OS_ANDROID) && !defined(Q_OS_IOS)
    if(!homeformLoaded) {
        qDebug() << "homeform not yet loaded";
        //return;
    }
#endif `

and now it connects

**Comment by cagnulein** [comment]
hah ok i will put a better if condition there

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 lug 2024 alle 06:12 cianpdx ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i did the patch @cianpdx thanks
