### ISSUE TITLE
Zwift Play, Virtual Shifting, Sportstech sBike Lite

### ISSUE THREAD

**Issue by Fysibisy** [cagnulein/qdomyos-zwift#2388]
Hi @cagnulein I heard about virtual shifting with Zwift Play in Zwift. Do you know if this is working with my bike? I am not so sure about how it works with Qz and if it makes sense to buy it. Do you have experience with that?

**Comment by cagnulein** [comment]
Hi! If your bike supports electronic resistance via Bluetooth qz can add
virtual shifting for sure!
let me know if you have any other questions

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 13 giu 2024 alle 21:27 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
I can change the resistance/gears with Qz so in this case it means … yes …?Am 13.06.2024 um 22:14 schrieb Roberto Viola ***@***.***>:﻿
Hi! If your bike supports electronic resistance via Bluetooth qz can add

virtual shifting for sure!

let me know if you have any other questions



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 13 giu 2024 alle 21:27 Fysibisy ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Yes so it's compatible! You can use the gears tile or any Bluetooth remote
controller for it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 13 giu 2024 alle 22:26 Fysibisy ***@***.***> ha
scritto:

**Comment by Fysibisy** [comment]
Great, thanks!Am 13.06.2024 um 22:28 schrieb Roberto Viola ***@***.***>:﻿
Yes so it's compatible! You can use the gears tile or any Bluetooth remote

controller for it!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno gio 13 giu 2024 alle 22:26 Fysibisy ***@***.***> ha

scritto:
