### ISSUE TITLE
[BUG] SHAWN PAVLIN ASCEND S2

### ISSUE THREAD

**Issue by shawnyboy60** [cagnulein/qdomyos-zwift#2389]
[debug-Thu_Jun_13_15_48_48_2024.log](https://github.com/user-attachments/files/15828085/debug-Thu_Jun_13_15_48_48_2024.log)

Resistance still drops to 1! 

Here are the settings: 
![image](https://github.com/cagnulein/qdomyos-zwift/assets/172649334/a229d69e-d8cb-415f-b3c6-5e22310cb399)

**Comment by cagnulein** [comment]
@shawnyboy60 checked the log, you have to use the gears tile to increase the effort (virtual shifting). I didn't see it in the log. Let me know!

**Comment by shawnyboy60** [comment]
Amazing, it works!! Thank you so much!!
Other question, and that might be outside the tools the app might offer... but my bike does a "beep" sound every time the resistance changes. I've contacted the manufacturer, and he claims it is not possible to remove the "beep" for "safety reasons". Anything the app can help with?
Thanks again!

**Comment by cagnulein** [comment]
That's great! Remeber to rate the app on the store, it means a lot to me!

For the beep I can't do anything unfortunately. It does only when the resistance changes or every second?

**Comment by shawnyboy60** [comment]
It beeps only when the resistance changes! Odds are I'll just open up the bikes monitor and try to remove the speaker from the bike.

Other question: is the app compatible with products such as this one to change gears?https://us.zwift.com/collections/training-accessories/products/zwift-click-virtual-shifter?variant=43859765297408

Cheers!

**Comment by cagnulein** [comment]
Yes Qz is compatible with zwift click!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 15 giu 2024 alle 17:45 shawnyboy60 ***@***.***>
ha scritto:

**Comment by shawnyboy60** [comment]
Great!! Thanks for all your help Roberto! :)

**Comment by cagnulein** [comment]
Any time! Remember to support the app with the swag bag in the app. I'm an indie developer so I need all the support to keep this running!
