### ISSUE TITLE
[BUG] Peloton App Not Connecting, Can’t View Content

### ISSUE THREAD

**Issue by Synaptic08** [cagnulein/qdomyos-zwift#2390]
**Describe the bug**

When trying to choose a cycling video from Peloton app on my iPad, it does not play and shows error occurred in yellow bar at top. 

**To Reproduce**
1. Go to qz app on iPhone. Wait for bike to connect. 
2. Click on cycling video in Peloton app on iPad
3. See Error

**Expected behavior**

expected for cycling video to play, with or without qz app

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 and iPad first gen 
 - OS: iOS
 - Version 17.5.1
[debug-Thu_Jun_13_16_21_23_2024.log](https://github.com/user-attachments/files/15829657/debug-Thu_Jun_13_16_21_23_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
So can we close this?

**Comment by Synaptic08** [comment]
Yes. Thank you.
