### ISSUE TITLE
Gear UI on Zwift 

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2391]
@doudar look what i found! https://github.com/cbj42/KickrBikeDisplay/blob/main/KickrBikeDisplay.ino

**Comment by cagnulein** [comment]
nope, did you remember when you talk to me about the possibility to have zwift showing the virtual gear even from QZ or SS2k? This is the answer about how we can do it! there is the protocol of the bluetooth custom char used by wahoo and from zwift!

**Comment by doudar** [comment]
Okay - I skimmed over it, and I thought it looked like a gear indicator for the kicker bike. 

Oh I understand. You're thinking about implementing this protocol in reverse of how they have it here and Zwift should in theory pick it up. Yes, that should work.

**Comment by cagnulein** [comment]
yep exactly. It should be quite easy to do, but I guess I have to expose a wahoo bike instead of a FTMS one

**Comment by doudar** [comment]
I bet it should work in addition to the FTMS.

**Comment by doudar** [comment]
The could be finger g by vendor string though

**Comment by cagnulein** [comment]
I will try :)

**Comment by doudar** [comment]
adding this here for more information. I'm trying to track down information about what might be in the flags field

https://forums.zwift.com/t/wahoo-kickr-bike-external-gear-display/597907/21?page=6

**Comment by doudar** [comment]
...Annnd I think this is another dead end for the onscreen support. It looks like there're working on this project because Zwift doesn't support the OSD for the Kicker bike. Bizarre.

**Comment by doudar** [comment]
@cagnulein  - Bingo! This should work! 

https://github.com/OevreFlataeker/ftms_emu/blob/0763c52864b55356eedd54d7811a6b02d96f8fe5/ble_atom/ble_atom.h#L85

**Comment by cagnulein** [comment]
wow that's great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 15 giu 2024 alle ore 20:57 Anthony Doud <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@doudar returning back on this, do you know if the atom wattbike has virtual shifting support on zwift natively?

**Comment by doudar** [comment]
It was one of the first smart bikes that had non-mechanical shifting. The shifters just change the magnet position on the eddy current brakes. 

It was also the first (of very few bikes) that Zwift developed an on-screen UI for displaying which gear the bike was in. 

So, yes, I think that all qualifies as "virtual shifting"

**Comment by cagnulein** [comment]
amazing! thanks for the confirmation, I will give it a go ASAP

**Comment by cagnulein** [comment]
this will simplify a lot the setup of the zwift play and zwift ride on qz

**Comment by cagnulein** [comment]
perfect, i have also the nrfconnect of the bike https://github.com/cagnulein/qdomyos-zwift/issues/2405

**Comment by doudar** [comment]
Yes! Combined with this: https://github.com/OevreFlataeker/ftms_emu/blob/0763c52864b55356eedd54d7811a6b02d96f8fe5/ble_atom/ble_atom.h#L85

That should be everything needed!

**Comment by cagnulein** [comment]
i just finished the implementation, let's see if it works!

**Comment by doudar** [comment]
It appears that Zwift is still supporting this feature. There have been bug reports of it not working and then was fixed recently. There are a few threads on the forums:
https://forums.zwift.com/t/gears-not-displaying-wattbike-atom-april-2024-ios/629331

**Comment by cagnulein** [comment]
i'm trying on ios but on ios i can't set the manufacturer data, so if it
doesn't work I will try on android, i guess zwift is looking for this.
Let's see!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle ore 16:05 Anthony Doud <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
![image](https://github.com/user-attachments/assets/bd6176e8-a3f6-4ed2-9763-8616297ad3b0)

I unlocked the watt bike kit simply changing to the wattbikeatom name my android with qz

I guess I'm near, I have to add the services now

**Comment by doudar** [comment]
Awesome!

**Comment by doudar** [comment]
I know the Zwift logging is fairly worthless, but it might be worthwhile to see what's in there when you connected.

**Comment by cagnulein** [comment]
Thanks for the tip!

I'm doing this with my daughter on my knee so I will try when I will be a
little stable :D

Il giorno dom 18 ago 2024 alle 18:59 Anthony Doud ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
it's working ![image](https://github.com/user-attachments/assets/e886518f-19a5-49a8-bed9-6b89ef4e98e3)

**Comment by doudar** [comment]
Awesome!

**Comment by doudar** [comment]
So is it just the device name and adding the characteristic according to the c++ header file I sent, or was there more to it?

**Comment by cagnulein** [comment]
exactly, just these

**Comment by doudar** [comment]
Kind of a bummer if we need the device name, it confuses users a bit, but I think overall, it's worthwhile. That will be a very nice feature you can add to any bike or trainer with QZ!!!

**Comment by doudar** [comment]
Also, it will give you a chance to see if any other apps support the gear indication!

**Comment by cagnulein** [comment]
> Also, it will give you a chance to see if any other apps support the gear indication!

i guess it's the only one, they have some agreements with the manufacturer

**Comment by cagnulein** [comment]
i don't have the zwift click here with me in vacation but it will be interesting if with the click connected directly on zwift, zwift controls the watt bike and so the gears on qz. This will be amazing!

**Comment by cagnulein** [comment]
i'm attaching also an ios bluetooth log from a zwift session with zwift ride that changes gears on zwift directly 
[gear_change.zip](https://github.com/user-attachments/files/16739140/gear_change.zip)

**Comment by cagnulein** [comment]
@doudar check this! https://github.com/jvivenot/KickrShiftr

**Comment by doudar** [comment]
Haha! That's a pretty cool idea!

**Comment by cagnulein** [comment]
i thought it was the code of the gear, nevermind :)

**Comment by cagnulein** [comment]
ok i have a lead, i guess it's about this https://github.com/cagnulein/qdomyos-zwift/commit/fbbd40a0f8a7358069c716dc3a75300eb3099717
Now I have to stay with my daughter, i will finish the analyze tomorrow! Thanks

**Comment by cagnulein** [comment]
ok the wahoo kickr sends the gears level to zwift using the indication of the characteristic [UUID: 0000000419ca465186e5fa29dcdd09d1] on the service [Service UUID: 0000000119ca465186e5fa29dcdd09d1]

for example on this Value: 3c08880412060a0440dcb702

the gears is the dcb7

```
f3ac
c891
90fa
d8e2
9fcb
dcb7
98a4
d490
90fd
dcec
a8dc
f3cb
c0bb
b8ad
b09f
a891
a083
c0bb
```

these should be the codificated gears levels

zwift request the gear change to the wahoo sending 2 frames on the characteristic [UUID: 0000000319ca465186e5fa29dcdd09d1] of the service [Service UUID: 0000000119ca465186e5fa29dcdd09d1]

first frame
Value: 042a0410c89103

where the c891 is the gear requested

and a fixed second frame

Value: 00088804

so my idea now is to add these 2 chars on qz and then zwift should handle everything
