### ISSUE TITLE
[BUG] NordicTrack S15i Resistance and Heart Rate not being received 

### ISSUE THREAD

**Issue by jones-d** [cagnulein/qdomyos-zwift#2392]
**Describe the bug**
Unable to change resistance via the app, no heart rate being received from the bike. 
Incline works as expected, receiving other data. 
[debug-Mon_Jun_17_12_23_31_2024.log](https://github.com/user-attachments/files/15866467/debug-Mon_Jun_17_12_23_31_2024.log)

**To Reproduce**

**Expected behavior**
When changing the resistance tile, expect change to reflect on the bike.  Expect heart rate to be visible in the app. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - Version 2.16.56

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
qz change only the inclination by design beacause resistance is affected by resistance, so with 1 thing i'm getting both inclination and resistance.

which hr device do you have?

**Comment by jones-d** [comment]
I have Whoop HR, connected to the bike.

**Comment by cagnulein** [comment]
is it bluetooth? if so why don't you connect it directly to qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 17 giu 2024 alle 13:40 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
Tried this approach, could connect in the app, but no data received.

**Comment by cagnulein** [comment]
is this scenario showed in the log?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 17 giu 2024 alle 13:43 jones-d ***@***.***> ha
scritto:

**Comment by jones-d** [comment]
Realised I hadn’t tested with new Beta app - now works.

**Comment by jones-d** [comment]
So to confirm, not being able to change the resistance in the app is by design. As incline does both?

**Comment by cagnulein** [comment]
Yes, that is correct.
At the end changing the inclination change both so there is no motivation
to do the resistance by itself (other than complicate the logic :) )

Il giorno lun 17 giu 2024 alle 13:46 jones-d ***@***.***> ha
scritto:
