### ISSUE TITLE
[BUG] Renpho smart bike r-q002 n

### ISSUE THREAD

**Issue by a-librarian** [cagnulein/qdomyos-zwift#2401]
**Describe the bug**
I bought the app on the play store and it sees the bike and connects automatically, but displays no information. Tried goofing around with settings to no avail. 

I've attached 3 debug logs from the sessions in which I was trying to connect.

**Screenshots**
![Screenshot_20240622-114727](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/ba699a91-61d5-4eb5-9da6-711dd6ce1b2d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Android 14, June 5 Update
Pixel 6 Pro

**Append a debug log**
[debug-Sat_Jun_22_11_51_06_2024.log](https://github.com/user-attachments/files/15937531/debug-Sat_Jun_22_11_51_06_2024.log)
[debug-Sat_Jun_22_12_09_53_2024.log](https://github.com/user-attachments/files/15937532/debug-Sat_Jun_22_12_09_53_2024.log)
[debug-Sat_Jun_22_12_04_18_2024.log](https://github.com/user-attachments/files/15937533/debug-Sat_Jun_22_12_04_18_2024.log)
 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @a-librarian that's very strange.
Can you try to enalbe the Hammer Racer Bike setting under the Hammer Racer Bike Options on the bike settings in QZ and restart QZ?
Send me another debug log in this scenario if it doesn't work
let me know!

**Comment by a-librarian** [comment]
Thanks. I turned on Hammer, no change. Two new logs for your viewing pleasure.

[debug-Sat_Jun_22_13_31_41_2024.log](https://github.com/user-attachments/files/15937612/debug-Sat_Jun_22_13_31_41_2024.log)
[debug-Sat_Jun_22_13_29_57_2024.log](https://github.com/user-attachments/files/15937613/debug-Sat_Jun_22_13_29_57_2024.log)

**Comment by cagnulein** [comment]
The problem is that the bike is not sending ftms data at all. Is the firmware on the bike updated?

**Comment by a-librarian** [comment]
I pressed the update firmware button in the AI Gym app. Nothing happens. I can confirm that the bike successfully pairs with and sends data to Zwift and Kinomap. It is not detected by the Peloton app.

**Comment by cagnulein** [comment]
Yes it sends only as a power meter. Let me try to do a modification about this

I will send you a new version in a hour

**Comment by a-librarian** [comment]
I took screenshots of the output of the bike in both apps, in case of use.
Zwift
![PXL_20240622_180603744 MP](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/b334c4bf-f765-4da9-ac57-9b8bca063d3f)
Kinomap
![Screenshot_20240622-135042](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/c5addd5a-db90-4e4f-80fd-817542ff7978)

**Comment by cagnulein** [comment]
Hah wait, I saw now that you set it under ftms bike setting. Remove it from there and restart qz 
Let me know

**Comment by cagnulein** [comment]
Hah wait, I saw now that you set it under ftms bike setting. Remove it from there and restart qz
Let me know

**Comment by a-librarian** [comment]
[debug-Sat_Jun_22_14_31_05_2024.log](https://github.com/user-attachments/files/15937947/debug-Sat_Jun_22_14_31_05_2024.log)
Like this?
![Screenshot_20240622-143136](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/779abd61-40a1-4391-9b6c-26c6588e5943)
No change to the output.

**Comment by cagnulein** [comment]
last test

set your bike under accesories, power sensor and also enable power sensor as a bike

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/ade60d23-d095-49bc-8fd5-73d97eb118ba)

let me know

**Comment by a-librarian** [comment]
Some progress! With Power Sensor set to R-Q002N, we get the following:
![Screenshot_20240622-145113](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/9d0a4a40-0428-445e-a3d6-1095a7302b3b)
[debug-Sat_Jun_22_14_50_29_2024.log](https://github.com/user-attachments/files/15938038/debug-Sat_Jun_22_14_50_29_2024.log)

**Comment by cagnulein** [comment]
ok wait i'm doing a modification

**Comment by cagnulein** [comment]
ok keep these settings and use this

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9627668039

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

I'm going to bed in an hour, I will answer you back tomorrow in case! Let me know

**Comment by a-librarian** [comment]
Hello,  installed the trial app. Displays the same metrics. The million dollar question for me is a) can I get peloton to automatically adjust my bikes resistance and maybe b) can I send cadence data to Peloton?

**Comment by cagnulein** [comment]
So the fix of yesterday worked?

in the actual setup qz can't change the resistance but i can do a mod for you.

i need a debug log from an app that can change directly the resistance following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Are you able to do so? For example kinomap or zwift can change the resistance on your bike?

**Comment by a-librarian** [comment]
Hi again. Ah, yes, I didn't have Power Sensor as a Bike enabled. It seems to work!
![Screenshot_20240623-125319](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/43acbc2f-ed70-4263-b39f-b8a4a25be4f7)

I connected to Kinomap and generated a BT log. 
[btsnoop_hci.log](https://github.com/user-attachments/files/15945382/btsnoop_hci.log)

I hope this is the right one. Let me know - it wasn't in exactly the same folder from your instructions.

Thanks.

**Comment by cagnulein** [comment]
ok that's great! so from kinomap did you change the resistance directly from the kinomap app?

**Comment by a-librarian** [comment]
Yes, Kinomap automatically adjusts the bike's resistance depending on the course - I could feel it adjusting. I noted that the display on the bike does not reflect the resistance value when connected to Kinomap, but I could tell it was working.

**Comment by cagnulein** [comment]
got it, you did right the log! I will check it tomorrow, it seems that kinomap is using ftms, so I probably need to understand what I did different from kinomap. So in the next version you will have to use to reset the power sensor to defaults (removing it from the power sensor) and set it back to the ftms bike.
I will update you!

**Comment by a-librarian** [comment]
Amazing. I really appreciate your work on this. Thank you!

**Comment by cagnulein** [comment]
hi @a-librarian i was comparing the hcisnoof with what QZ does in the standard configuration (no FTMS bike set and now power sensor set) and it looks the same. The only different thing is the fact that QZ also broadcast itself as a FTMS bike and I'm wondering if maybe this is the problem that inhibit the bike to send the metrics.
So:
- set the ftms bike to disabled
- set the power sensor to disabled
- set the power sensor as a bike to OFF
- set the virtual bluetooth device in the experimental settings to OFF
- restart QZ

let's see if you can get the metrics in this way. if not post again a debug log.
Let me know!

**Comment by a-librarian** [comment]
Did all those things, no display, I'm afraid.
[debug-Mon_Jun_24_08_40_56_2024.log](https://github.com/user-attachments/files/15955917/debug-Mon_Jun_24_08_40_56_2024.log)
[debug-Mon_Jun_24_08_42_46_2024.log](https://github.com/user-attachments/files/15955918/debug-Mon_Jun_24_08_42_46_2024.log)

**Comment by cagnulein** [comment]
this is crazy, i can't see any real difference between what kinomap does and what I did. Could you ask you one last favor? Could you please do the hcisnoof thing this time with qz? I would like to compare the one that you did for kinomap with the one from QZ so i will compare apple with apple.
Thanks!

**Comment by a-librarian** [comment]
Here you go:
[btsnoop_hci.log](https://github.com/user-attachments/files/15961206/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks i will check it tomorrow!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 24 giu 2024 alle 23:00 a-librarian ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok @a-librarian I tried to do the same thing that kinomap does (even if it doesn't have sense, but maybe it's a workaround for this bike) https://github.com/cagnulein/qdomyos-zwift/actions/runs/9657925370

Let me know, send me a debug log from qz in case it doesn't work
Thanks!

**Comment by a-librarian** [comment]
No display with default settings, alas.
[debug-Tue_Jun_25_08_48_34_2024.log](https://github.com/user-attachments/files/15971502/debug-Tue_Jun_25_08_48_34_2024.log)

**Comment by cagnulein** [comment]
it's truly unbelieavable. Do you have by chance a PC, or a Mac with Silicon processor or a iOS device? I would like to try QZ as well there (i can send you a free copy of course). Let me know

**Comment by a-librarian** [comment]
I have a Windows 11 PC and an iPad air that I can use.
________________________________

**Comment by cagnulein** [comment]
ok let's try first with the ipad. i just sent you a version by email

**Comment by a-librarian** [comment]
[debug-Tue_Jun_25_10_38_50_2024.log](https://github.com/user-attachments/files/15973147/debug-Tue_Jun_25_10_38_50_2024.log)
From iOS this time. Same as ever. It works when set as power sensor, but not otherwise.

**Comment by cagnulein** [comment]
ok thanks, it could be a good news since it's seems the same issue.
I have to think about
Thanks, i will keep you posted in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 25 giu 2024 alle ore 16:42 a-librarian <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok let's try one more thing https://github.com/cagnulein/qdomyos-zwift/actions/runs/9677397119

**Comment by a-librarian** [comment]
Still nothing (on android). 
[debug-Wed_Jun_26_21_49_13_2024.log](https://github.com/user-attachments/files/16006689/debug-Wed_Jun_26_21_49_13_2024.log)

**Comment by cagnulein** [comment]
unbelievable. I have to think about this, never had such an issue. All the communication is right now

**Comment by cagnulein** [comment]
@a-librarian could I ask you a test? 

https://github.com/cagnulein/qdomyos-zwift/assets/48216/032f21b8-d09d-49c4-a157-7f04a6eab7fc

If you are doing the same for your renpho bike do you see the metrics as I can see on mine?

**Comment by cagnulein** [comment]
hah sorry with the nrfconnect, free app from the store
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 giu 2024 alle ore 14:22 a-librarian <
***@***.***> ha scritto:

**Comment by a-librarian** [comment]
When I connect qz and debug I see this:
![Screenshot_20240627-083020](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/edc28d9b-e645-4db0-8295-f6ed2e1cfc63)

**Comment by cagnulein** [comment]
don't use qz for this, just use nrfconnect to connect to your bike. then
click on fitness machine and you will see indoor bike data. and then click
on the 3 arrow on the right next to indoor bike data

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 giu 2024 alle ore 14:32 a-librarian <
***@***.***> ha scritto:

**Comment by a-librarian** [comment]
![Screenshot_20240627-083830](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/5cc3ae7a-c34b-4fa1-9711-ec9a030e863c)
![Screenshot_20240627-083846](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/2f3143e0-9903-4fab-945b-715fd932dd1e)
![Screenshot_20240627-083825](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/c249c129-f2a0-4665-a681-d59b0537ebdb)

**Comment by a-librarian** [comment]
![Screenshot_20240627-084914](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/c961091d-ad05-4009-9822-1effb10d3148)

**Comment by cagnulein** [comment]
ok so same issue here. Ok that's a clue. Even if you click again the same icon and again? you never receive any metrics?

**Comment by a-librarian** [comment]
![Screenshot_20240627-085507](https://github.com/cagnulein/qdomyos-zwift/assets/84794090/66bc579f-fc29-4401-b57f-6b53cd953187)

**Comment by a-librarian** [comment]
Sorry, didn't think to be riding while doing this! I have to head to work but can gather more data later if needed.

**Comment by a-librarian** [comment]
😊 yes, always riding when testing qz. Didn't think this Bluetooth app could display metrics. Happy to do any other tests you can think of.

**Comment by cagnulein** [comment]
ok another approach https://github.com/cagnulein/qdomyos-zwift/actions/runs/9697597100

**Comment by cagnulein** [comment]
ok thanks for trying, I will think what else can i try to fix this.

**Comment by cagnulein** [comment]
hi @a-librarian when you will come back, can you please try the same version disabling the virtual device setting under the experimental settings? I know you did it already but since i did some changes, I would like to see if it makes any difference. Thanks. In the meantime I'm still thinking if I can do something else

**Comment by a-librarian** [comment]
Hey, tried that on Android and iPad. No data displayed.

**Comment by cagnulein** [comment]
Ok I will think about any other possible solutions. Thanks have a great weekend

**Comment by cagnulein** [comment]
I didn't forget about you, I'm still thinking about what I can do
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 lug 2024 alle ore 01:06 a-librarian <
***@***.***> ha scritto:

**Comment by a-librarian** [comment]
Would it be useful to pull BT data from the native Renpho app, AI Gym? I was riding with it yesterday, grabbed a screenshot.
![Screenshot_20240723-203934](https://github.com/user-attachments/assets/dbf0b236-322f-413e-a615-c71a32961225)

**Comment by cagnulein** [comment]
yeah maybe i can see something different. thanks!

**Comment by a-librarian** [comment]
Opened the AIGym app, it failed connection to the bike and then worked on reconnect. I did a quick bike where it reports what the bike is doing, then quit that and started a routine where the app controls the resistance.
[btsnoop_hci.log](https://github.com/user-attachments/files/16401268/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out.
thanks.

Il giorno sab 27 lug 2024 alle 21:30 a-librarian ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
this is very useful! this app use the native protocol of the bike! just one question and another request: on this log did you change the resistance from 17 to 18 to 19 several times, right? if so are you able to change, from the app directly, all the resistance from 1 to the max, leaving 5 seconds between each change? This will allow me to collect all the frames and to add them into qz as well!

Let me know!

**Comment by a-librarian** [comment]
During the first phase, I did a "free cycle" where I manipulated the dial on the bike and I did go up and down a few times. I don't remember that it was as high as 17-19 on my display (the resistance I can manually change goes from 1-24 in single digit increments) - that would have been fairly high resistance. When you are in free cycle, the app only displays information - you cannot change the resistance through the app, only on the bike's dial.

In the second phase, when I was doing a program, the bike takes control of the resistance and the dial doesn't do anything. I can't find a way through the app to get exactly what you're looking for.

I could, though, do one of the programs that moves through many increasing resistance levels in a row, if that would be useful.
![Screenshot_20240728-104958](https://github.com/user-attachments/assets/ad772401-d029-4497-971d-4dd1bf54d7bd)

Or if you have another idea, let me know.

**Comment by cagnulein** [comment]
ok i think i've done https://github.com/cagnulein/qdomyos-zwift/actions/runs/10141376002

i made a LOT of changes so hopefully it will work. Let me know with a debug log if something is doesn't work.
What I expect is that you can see the metrics from the bike as usual and also, with the plus and minus button in the resistance tile, you are able to change the resistance on the bike

let me know!

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10141437665

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10141861182

**Comment by a-librarian** [comment]
Used the newest one you posted. Metrics displayed on start, which is great. I could not adjust the resistance from the app, I could from the bike. I note that when one of the apps (AIgym, kinoapp) has control of the resistance, I cannot change it from the bike.[debug-Mon_Jul_29_08_40_10_2024.log](https://github.com/user-attachments/files/16413210/debug-Mon_Jul_29_08_40_10_2024.log)

**Comment by cagnulein** [comment]
got the issue, new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10144771741

**Comment by a-librarian** [comment]
Sorry for the delay, tried this one, no change. I think this is the right debug file.
[debug-Mon_Jul_29_19_06_38_2024.txt](https://github.com/user-attachments/files/16482627/debug-Mon_Jul_29_19_06_38_2024.txt)

**Comment by cagnulein** [comment]
thanks. I did a mistake in the last built. New one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10244344251

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/10246000591

**Comment by a-librarian** [comment]
Hi, this last build fails to launch for me. I'll restart my phone and double check.

**Comment by cagnulein** [comment]
argh i had to change a thing in the gradle script because a internet website was down. let me check on my side if i see the same issue. i will report back

**Comment by cagnulein** [comment]
confirmed, it doesn't work on my side neither.
I will report back ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 ago 2024 alle ore 15:18 a-librarian <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/10253059526
sorry for the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 ago 2024 alle ore 15:23 cagnulein ***@***.***> ha
scritto:

**Comment by a-librarian** [comment]
Hey, it worked. I got the introduction setup screens which I'd not seen before. It also took control of the bikes resistance though I'll need to experiment because it wasn't obvious what it was displaying vs what I was feeling. I'll try connecting to peloton next.

**Comment by cagnulein** [comment]
wow amazing! 

> I got the introduction setup screens which I'd not seen before

yes I added recently, what do you think?



> . It also took control of the bikes resistance though I'll need to experiment because it wasn't obvious what it was displaying vs what I was feeling. I'll try connecting to peloton next.

ok let me know!

**Comment by a-librarian** [comment]
Do want to keep open. Will post again upon return from vacation.

**Comment by a-librarian** [comment]
Hiya,
sorry for the long delay. I've tested the app with the bike, and in particular when connected to Peloton. As I noted above, the app will take control of the bike, and I can seemingly press up and down to manipulate the resistance (though I don't totally understand how the numbers relate to my bike). However, the app does not change the resistance along with the program - it's static resistance throughout.

I tried a few things and captured some debug logs. I admit though that I've now forgotten  what I did when I took these logs! I can do more specific testing if you have direction.
[debug-Mon_Aug_26_11_29_56_2024.log](https://github.com/user-attachments/files/16911119/debug-Mon_Aug_26_11_29_56_2024.log)
[debug-Mon_Aug_26_11_31_51_2024.log](https://github.com/user-attachments/files/16911120/debug-Mon_Aug_26_11_31_51_2024.log)
[debug-Mon_Aug_26_11_33_19_2024.log](https://github.com/user-attachments/files/16911121/debug-Mon_Aug_26_11_33_19_2024.log)

**Comment by cagnulein** [comment]
No worries, thanks for the update!
i will check it in the next days

Il giorno ven 6 set 2024 alle 19:15 a-librarian ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
> debug-Mon_Aug_26_11_33_19_2024.log

hi @a-librarian only in this log i can see the peloton resistance sent to the bike from resistance 8 to 12. it uses the same method that it did from the resistance tile. maybe you can try a longer session?

**Comment by a-librarian** [comment]
I'll def. try again. I think I've mentioned before the the Renpho bike only has 24 levels of resistance compared to the 100 that Peloton uses. Perhaps that is part of the disconnect?






________________________________

**Comment by cagnulein** [comment]
Yes I already handled the conversion : peloton was asking for resistance 38
and I was applying resistance 12 to your bike

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 22:05 a-librarian ***@***.***>
ha scritto:

**Comment by a-librarian** [comment]
Oh! I see. 
I would say :
Peloton resistance 25 : Renpho 6
Peloton resistance 50 : Renpho 12
Peloton resistance 75 : Renpho 18
Peloton resistance 100 : Renpho 24

**Comment by cagnulein** [comment]
There are several renpho conversion algorithm in qz settings. Experiment
with them :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 22:35 a-librarian ***@***.***>
ha scritto:

**Comment by a-librarian** [comment]
ok, will do.

**Comment by cagnulein** [comment]
@a-librarian any news?

**Comment by a-librarian** [comment]
[debug-Sun_Nov_3_10_13_49_2024.log.txt](https://github.com/user-attachments/files/17610959/debug-Sun_Nov_3_10_13_49_2024.log.txt)

I've created a new log for you. Here's what I did: 
- connected to qz, attempted to change resistance. Couldn't seem to, but I was pressing the buttons. Hard to pedal. 
- started a peloton ride.  It found it. The ride was a low resistance ride, but I could barely pedal, almost like it was at max resistance. It seemed to get easier right at the end.

I honestly can't figure out what the app is doing vis a vis the bikes resistance.

**Comment by cagnulein** [comment]
Ok I will check it, I thought we were ok

**Comment by a-librarian** [comment]
I can try to perhaps do a Bluetooth log from ai gym, but I have to imagine that it has to do with the fact that the bike only has 24 levels of resistance (when I change it manually on the console).

I'll connect AI gym to the bike later and see what it says.

AC

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
hah ok 24, that's the number that I was looking for. Now qz is sending numbers over 40 that's the reason! let me try to do a patch!

**Comment by cagnulein** [comment]
@a-librarian https://github.com/cagnulein/qdomyos-zwift/actions/runs/11666537926

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
@a-librarian Any news?
