### ISSUE TITLE
[REQ] Change keyboard shortcut for gear shifting on Windows 

### ISSUE THREAD

**Issue by CurtisVermeeren** [cagnulein/qdomyos-zwift#2404]
**Is your feature request related to a problem? Please describe.**

Using the windows release of QZ app the current way to shift gears is either clicking the icon buttons or using volume controls.

When running Zwift on the same Laptop as QZ App shifting with the keyboard method will change the volume of the laptop which isn't ideal.

Keyboards that don't have volume controls may not be able to shift via keyboard at all. 

**Describe the solution you'd like**

The option to change the keys for shifting on a keyboard in the Windows release 

Ideally one key each for up and down shifting would be efficient but a key combo of easy to reach keys would work. Something like "shift + z" for down and "shift + x" for up. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
Perfect I will try to do this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 23 giu 2024 alle 19:07 Curtis ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/9641836869

**Comment by cagnulein** [comment]
i used z and x 
z = gears down
x = gears up

remember to enable also the volumes on gears in the advanced settings

Let me know @CurtisVermeeren

**Comment by CurtisVermeeren** [comment]
Perfect! Thank you
