### ISSUE TITLE
[BUG] Unable to Bridge Apple Watch + Apple iPhone + QZ on Android Tablet

### ISSUE THREAD

**Issue by Skates1616** [cagnulein/qdomyos-zwift#2410]
**Describe the bug**
Continuing the discussion from Messenger, I am trying to Run QZ on my Android Tablet w/ Peloton app and transfer my Heart Rate from my Apple Watch using QZ on my iPhone.  As described, I am able to transfer the heart rate but the cadence from QZ on Android is transferring to the Peloton app.  I am also not getting calories or distance transferring from the Android back to the Apple Watch.

**To Reproduce**
Apple Watch Connected to Apple iPhone.  QZ App in Virtual Device and Fake Device activated.
QZ on Android Tablet with Peloton app.  The QZ app is connected to the bike and monitoring performance/auto resistance.

Peloton app I believe is connected the iPhone.  I only one option to select for qzDomyos listed, and this is why Cadence is not being pulled in.  I do not have an option to select Android QZ.

**Expected behavior**
I would like to use my Apple Watch for HR while QZ Android is being used for bike connection, Peloton app.  I would also like my Cadence transferred to theee Peloton app.  And my kcal/distance transferred to Apple Watch.

**Screenshots**
Attached is a NRF Connect screenshot along with a screenshot of the Peloton app:

![IMG_0083](https://github.com/cagnulein/qdomyos-zwift/assets/23196661/477ca9ad-1b6b-4887-a36a-fa08d5a5893f)
![IMG_0082](https://github.com/cagnulein/qdomyos-zwift/assets/23196661/e4d1bf1b-9d67-4277-8d2b-3a534a60e70d)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - iPhone 15 w/iOS 17.5.1
 - Samsung Galaxy Tab 5e

**Append a debug log**
[Log 2024-06-25 20_40_10.txt](https://github.com/user-attachments/files/15981310/Log.2024-06-25.20_40_10.txt)
[Log 2024-06-25 20_39_38.txt](https://github.com/user-attachments/files/15981311/Log.2024-06-25.20_39_38.txt)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

[debug-Tue_Jun_25_20_35_31_2024.log](https://github.com/user-attachments/files/15981341/debug-Tue_Jun_25_20_35_31_2024.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
did you try instead of using the fake device on ios, to use the ftms bike setting under the bike setting and setting the android phone there?

**Comment by Skates1616** [comment]
The Bike FTMS setting does not allow me to select the Galaxy Tab S5e.  It’s not listed in the options even after Bluetooth connecting the iPhone and tablet together.

On the tablet without a bike connected, I do see a qDomyos-zwift found as it cycles through potential connections.

**Comment by cagnulein** [comment]
Did you already renamed the android phone to "bike" and reboot it?
