### ISSUE TITLE
[BUG] Support Issue for iConsole+ 0158 on FitNord Racer 500i Spin Bike

### ISSUE THREAD

**Issue by Linkanblomman** [cagnulein/qdomyos-zwift#2411]
I am experiencing an issue when connecting the QZ app with an **iConsole+ 0158** LCD display for my FitNord Racer 500i spin bike. While I am able to establish a connection between them and receive data, the application fails to display accurate metrics for speed and watts, only showing like maximum values. This issue seems related to a previously reported issue #2255. Despite attempting the recommended solution from that issue, the problem remains unresolved.

<img src="https://github.com/cagnulein/qdomyos-zwift/assets/11296710/89739bda-f1fa-4f3b-8a3a-0907d8e090f9" width="40%" alt="image">

I have tried:
* Updating to the latest version of the app (2.16.58).
* Activating the 'Toorx/iConsole Bike' and 'Toorx FTMS Bike' settings under 'Toorx/iConsole options,' but not simultaneously, and restarted the app each time.

**Smartphone**
 - Device: Pixel 7
 - OS: Android 14

**Debug log**
[debug-Wed_Jun_26_18_07_33_2024.log](https://github.com/user-attachments/files/15993778/debug-Wed_Jun_26_18_07_33_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

**Comment by cagnulein** [comment]
hi @Linkanblomman log checked, unfortunately it's not about that other issue, it's a different one. It seems that your bike has a slightly different protocol. Do you have an app that already reads the metrics correctly? If so follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device with that app and I will implement it!

Let me know

**Comment by Linkanblomman** [comment]
@cagnulein, thank you for checking the log. I usually connect my bike to the iConsole+ training app ([iConsole+ Training on Google Play](https://play.google.com/store/apps/details?id=com.changyow.icp4th&hl=sv)).

Following your instructions, I've enabled the "Bluetooth HCI snoop log" and connected the bike to the iConsole+ Training app, which works with the iConsole+ 0158 display. I completed a short distance on the spin bike to gather some data that were successfully displayed on the app. Here is the log file:

[btsnoop_hci.log](https://github.com/user-attachments/files/16010186/btsnoop_hci.log)

Please let me know if there’s anything else you need.

**Comment by Linkanblomman** [comment]
@cagnulein, I enabled the JLL_IC400 setting as you suggested, and it fixed the speed and watt readings in the app now :+1:
Thanks so much for your quick help! I’ll buy you a [coffee](https://buymeacoffee.com/cagnulein) :coffee:

**Comment by cagnulein** [comment]
that's great @Linkanblomman !
