### ISSUE TITLE
[QUESTION]Can any Zwift bike work with the app?

### ISSUE THREAD

**Issue by sabotage3d** [cagnulein/qdomyos-zwift#2414]
Hi,
I have a question as I am looking to buy a Zwift bike, but at the same time many are not working with Peloton. This app is a perfect bridge. Would any Zwift compatible bike work with this app? If I want to add it manually what is the process to detect what sensors are available. At the moment I am looking at this bike: https://en.toorx.it/home-fitness/indoor-cycles/srx-speed-mag-pro/
and another one with motorized resistance https://en.toorx.it/home-fitness/indoor-cycles/srx-500/.
Any help would be appreciated as this app is a major factor in purchasing a bike.

**Comment by cagnulein** [comment]
hi, yes any bike compatible with zwift is compatible also with qz.
i suggest a electronic resistance bike as the second one that you linked
let me know if you have any other questions

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 giu 2024 alle 21:28 sabotage3d ***@***.***>
ha scritto:

**Comment by sabotage3d** [comment]
Thank you for your quick answer. Is there certainty that the electronic resistance can be changed through your app and remapped to apps like Peloton? Is that a big benefit as I am only used to manual one in cycling classes?

**Comment by cagnulein** [comment]
Yes 99% certainty
Automatic resistance is a must if one day you would like to try something
different than peloton and also for reselling it


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 27 giu 2024 alle 23:47 sabotage3d ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Actually the 99% of the bike with Bluetooth or wifi are compatible. Let me
know if you have one in particular

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 28 giu 2024 alle 18:39 sabotage3d ***@***.***>
ha scritto:
