### ISSUE TITLE
Multiplicator for speed gain is not working in QZ when increasing speed on the treadmill

### ISSUE THREAD

**Issue by ralfnec** [cagnulein/qdomyos-zwift#2417]
![Screenshot_20240630_002203_Chrome](https://github.com/cagnulein/qdomyos-zwift/assets/174216926/8be449a6-89e7-4c26-9105-4a88f349b9c4)
[debug-Sun_Jun_30_10_50_36_2024.log](https://github.com/user-attachments/files/16043779/debug-Sun_Jun_30_10_50_36_2024.log)

As already described to Robert on FB (see screenshot attached) QZ is not multiplicating the speed shown on the QZ monitor with the value I set under Speed Gain in the settings, when I increase the speed of my treadmill. Speed shown on the treadmill and on QZ always is the same even when e. g. Speed Gain is set with the factor 5.

I tried with different devices - Samsung S22 Ultra, Samsung Zflip 3, Samsung tablet. Working with Android 14
Debug log is attached

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks, fixed @ralfnec https://github.com/cagnulein/qdomyos-zwift/actions/runs/9731101710

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by ralfnec** [comment]
Hi, 
Unfortunately I cannot find at the bottom of the link you sent the android build  to download or another link to download the trial you speak about.
Where exactly do I have to look for?
Thanks

**Comment by cagnulein** [comment]
Here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9731101710/artifacts/1652602159

**Comment by ralfnec** [comment]
Great job! Works properly now with the treadmill and the VZfit, too. The avatar runs according to the Speed Gain I set. I'm going to send you an email for unlocking.
Best regards

**Comment by cagnulein** [comment]
That's great!

**Comment by ralfnec** [comment]
Hi Roberto,
below the issue, attached the log file, I hope I did everything right.
Thanks very much, best regards
Ralf




    Am Sonntag, 30. Juni 2024 um 17:06:04 MESZ hat Roberto Viola ***@***.***> Folgendes geschrieben:  
 
 


That's great!

**Comment by cagnulein** [comment]
Hi @ralfnec I can't see the log, I see only the one of the 30 jun. Can you please upload it here again via the GitHub web interface?

**Comment by ralfnec** [comment]
[btsnoop_hci.log](https://github.com/user-attachments/files/16736831/btsnoop_hci.log)
 
Hi Roberto, I hope the upload works now and the log file has been recorded correctly ..... Thanks!

**Comment by cagnulein** [comment]
Hi sorry what should I look inside this? Which is the issue ?

**Comment by ralfnec** [comment]
that was the issue, the log was made with using kinomap




    Am Samstag, 24. August 2024 um 16:06:26 MESZ hat Roberto Viola ***@***.***> Folgendes geschrieben:  
 
 


Hi sorry what should I look inside this? Which is the issue ?

**Comment by cagnulein** [comment]
but what issue? i mean i guess the gain thing was already solved in july, right?

**Comment by ralfnec** [comment]
Sorry, I think I have some problems with sending mails from my yahoo account.
The July issue concerned my treadmill and was solved, works well. 
The new issue concerned my new crosstrainer from three days ago
I try to copy it in here, hope it works

![image](https://github.com/user-attachments/assets/1128df68-9447-4e96-b32b-cbf6c0f89d13)
![image](https://github.com/user-attachments/assets/0068155a-2983-4b31-923a-3ac00c756653)

**Comment by cagnulein** [comment]
hah ok!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 ago 2024 alle 17:15 ralfnec ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i created this one https://github.com/cagnulein/qdomyos-zwift/issues/2538 for you. I will work it on these days. I will close this in the mean time. thanks
