### ISSUE TITLE
Not connecting to peloton via bt[BUG]

### ISSUE THREAD

**Issue by Jiffy176** [cagnulein/qdomyos-zwift#2418]
**Describe the bug**
Lenovo M8 tab v4 connects qd to treadmill jtx 5 with the settings you gave me in the below log start peloton class and BT cannot find qz to connect to.
Peloton running on Samsung s24
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Version [e.g. 22]android 

**Append a debug log**
[
[debug-Sun_Jun_30_19_14_31_2024.log](https://github.com/user-attachments/files/16045804/debug-Sun_Jun_30_19_14_31_2024.log)
](url)
 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi you have the virtual device setting disabled in the experimental
settings. enable it for this

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 30 giu 2024 alle 21:08 Jiffy176 ***@***.***> ha
scritto:

**Comment by Jiffy176** [comment]
Yep that worked just doesn't display the speed any ideas

**Comment by cagnulein** [comment]
what do you mean? where don't you see on qz or peloton? create a new debug
log in this scenario.

do you see inclination so on peloton?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 30 giu 2024 alle 21:21 Jiffy176 ***@***.***> ha
scritto:

> Yep that worked just doesn't display the speed any ideas
>

**Comment by Jiffy176** [comment]
Ok will be later in the week thanks b

**Comment by cagnulein** [comment]
No problem, take your time.


Il giorno dom 30 giu 2024 alle 21:47 Jiffy176 ***@***.***> ha
scritto:

> Ok will be later in the week thanks b
>

**Comment by cagnulein** [comment]
@Jiffy176 any news?

**Comment by Jiffy176** [comment]
Sorry not tried it yet been manic
