### ISSUE TITLE
Unable to direct the treadmill from the application

### ISSUE THREAD

**Issue by Johnmat777** [cagnulein/qdomyos-zwift#2421]
[debug-mar__juil__2_13_37_43_2024.log](https://github.com/user-attachments/files/16067466/debug-mar__juil__2_13_37_43_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
[Change speed treadmill](https://github.com/cagnulein/qdomyos-zwift/issues/1988#top)
#1988

**Comment by cagnulein** [comment]
@Johnmat777 try a thing: on the proform model selection, select another one and then again the proform 9. then restart qz and send me a debug log again if it doesn't work
let me know

**Comment by Johnmat777** [comment]
Thank you very much, could you look so that the treadmill was when I click on stopEnvoyé de mon iPhoneLe 2 juil. 2024 à 17:03, Roberto Viola ***@***.***> a écrit :﻿
@Johnmat777 try a thing: on the proform model selection, select another one and then again the proform 9. then restart qz and send me a debug log again if it doesn't work
let me know

**Comment by cagnulein** [comment]
ok i will do in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 2 lug 2024 alle 18:06 Johnmat777 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Johnmat777 i tried to add the stop event.
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9790186892

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Johnmat777** [comment]
Hello Roberto, I think there is always a problem. The treadmill does not follow the zwo training. I'm attaching the zwo file and the debug fileEnvoyé de mon iPhoneLe 4 juil. 2024 à 09:24, Roberto Viola ***@***.***> a écrit :﻿
@Johnmat777 i tried to add the stop event.
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9790186892
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to ***@***.*** mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
you have to attach the debug log from the github web interface directly otherwise i can't see it

**Comment by Johnmat777** [comment]
[debug-ven__juil__5_06_16_54_2024.log](https://github.com/user-attachments/files/16105263/debug-ven__juil__5_06_16_54_2024.log)

**Comment by cagnulein** [comment]
hi @Johnmat777 i don't see any opening of a zwo file. Maybe you sent me the wrong file?

**Comment by Johnmat777** [comment]
It’s good ? Envoyé de mon iPhoneLe 5 juil. 2024 à 08:44, Roberto Viola ***@***.***> a écrit :﻿
hi @Johnmat777 i don't see any opening of a zwo file. Maybe you sent me the wrong file?

**Comment by Johnmat777** [comment]
[Uploading debug-jeu__juil__4_17_05_59_2024.log…]()

**Comment by cagnulein** [comment]
you have to wait the finish of the upload before clicking comment, please upload it again

**Comment by Johnmat777** [comment]
[debug-ven__juil__5_06_16_54_2024.log](https://github.com/user-attachments/files/16106312/debug-ven__juil__5_06_16_54_2024.log)

**Comment by cagnulein** [comment]
@Johnmat777 you sent me again the 6:16 file. i need another file. you tried the 17:05 one but you fail to upload. please try again

**Comment by Johnmat777** [comment]
[debug-jeu__juil__4_17_05_59_2024.log](https://github.com/user-attachments/files/16106335/debug-jeu__juil__4_17_05_59_2024.log)

**Comment by cagnulein** [comment]
it gives me a 404 error. are you able to download if from the link? please zip it, i don't know why it's so hard :D

**Comment by cagnulein** [comment]
[debug-jeu__juil__4_17_05_59_2024 (1).log.zip](https://github.com/user-attachments/files/16106562/debug-jeu__juil__4_17_05_59_2024.1.log.zip)

**Comment by cagnulein** [comment]
@Johnmat777 in this log i can see QZ changing the speed following the zwo file

```
ven. juil. 5 05:50:06 2024 1720151406833 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 9.8"
ven. juil. 5 05:52:05 2024 1720151525633 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 9.9"
ven. juil. 5 05:54:05 2024 1720151645634 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10"
ven. juil. 5 05:56:05 2024 1720151765636 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.1"
ven. juil. 5 05:58:05 2024 1720151885635 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.2"
ven. juil. 5 06:00:05 2024 1720152005638 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.3"
ven. juil. 5 06:02:05 2024 1720152125642 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.4"
ven. juil. 5 06:04:05 2024 1720152245613 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.5"
ven. juil. 5 06:06:05 2024 1720152365612 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:08:05 2024 1720152485645 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.7"
ven. juil. 5 06:10:05 2024 1720152605614 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:04 2024 1720152784833 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:09 2024 1720152789632 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:12 2024 1720152792035 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:13 2024 1720152793233 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:30 2024 1720152810034 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:31 2024 1720152811234 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:32 2024 1720152812644 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:33 2024 1720152813818 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:35 2024 1720152815015 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:36 2024 1720152816213 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:51 2024 1720152831813 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 11.5"
ven. juil. 5 06:13:53 2024 1720152833013 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:13:57 2024 1720152837816 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 11"
ven. juil. 5 06:13:59 2024 1720152839017 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:14:15 2024 1720152855814 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 11"
ven. juil. 5 06:14:17 2024 1720152857019 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:14:42 2024 1720152882215 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 11"
ven. juil. 5 06:14:43 2024 1720152883441 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:15:09 2024 1720152909934 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:15:17 2024 1720152917043 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:15:20 2024 1720152920615 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
ven. juil. 5 06:15:23 2024 1720152923013 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/bluetooth.cpp void bluetooth::debug(const QString &) "writing speed 10.6"
```

which is the issue?

**Comment by Johnmat777** [comment]
At 20 minutes the speed should have changed and nothing I couldn't increase it either on the treadmill or on qz

**Comment by cagnulein** [comment]
but then i can see qz also forces it to 11 for example at minute 23, so maybe it was a glitch of your treadmill?

**Comment by Johnmat777** [comment]
I'm the one who forces manually with qz

**Comment by cagnulein** [comment]
hah ok now i got it. I need the vendrdi0507.zwo to check it

**Comment by cagnulein** [comment]
got the issue! i'm sending you a new version!

**Comment by Johnmat777** [comment]
Thanks. 
Wednesday qz didn't stop training, is it the same problem?

**Comment by cagnulein** [comment]
by default qz doesn't stop the training at the end. there is a stop the treadmill at the end setting to enable in the training program setting if you want this.

**Comment by Johnmat777** [comment]
I'd like to know this parameter

Envoyé de mon iPhone

**Comment by cagnulein** [comment]
I said, " there is a `stop the treadmill at the end` setting to enable in the `training program settings` if you want this."

**Comment by Johnmat777** [comment]
In zwift workout edit ? 

Envoyé de mon iPhone

**Comment by cagnulein** [comment]
no in QZ!, settings, training program settings, stop the treadmill at the end

**Comment by Johnmat777** [comment]
Yes also enable Envoyé de mon iPhoneLe 5 juil. 2024 à 10:55, Roberto Viola ***@***.***> a écrit :﻿
no in QZ!, settings, training program settings, stop the treadmill at the end

**Comment by cagnulein** [comment]
ok but before the new version that I just sent the treadmill didn't stop with the stop command. Now try first to check if you are able to use the stop button on qz to stop. If so it means that we fixed it and also that setting will work
