### ISSUE TITLE
MyWhoosh inclination 

### ISSUE THREAD

**Issue by Dwhetsel** [cagnulein/qdomyos-zwift#2422]
Debug discussed on FB.

[debug-Tue_Jul_2_09_06_14_2024.zip](https://github.com/user-attachments/files/16074200/debug-Tue_Jul_2_09_06_14_2024.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Dwhetsel you have the nordictrack 2950 ip set in your treadmill settings. remove it. It's this one that creates confusion. Let me know

**Comment by cagnulein** [comment]
@Dwhetsel any news?
