### ISSUE TITLE
[BUG] Unable to connect to Garmin Epix Pro via ANT+

### ISSUE THREAD

**Issue by itsredan97** [cagnulein/qdomyos-zwift#2424]
**Describe the bug**
Currently using QZ app with a Zipro indoor bike, I have correct readings from the app (except the fact that the resistance sets to 5 everytime i start a training and I need to set it manually to 1), but i'm not able to connect it to my Garmin via ANT+, using an usb dongle.

I enabled ANT+ Cadence option in QZ App.

I think don't have issues on dongle's side since i don't get errors from ANT Tester app. My phone is a S22 Ultra, but I tried also with an old Xiaomi Mi9 without success.

**To Reproduce**
1. Start the training on the bike
2. Open the app, flawless connection to the phone
3. On my watch, I start the device scan before starting indoor cycling activity
4. No devices found 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra, Xiaomi mi9 
 - OS: Android 
 - Version: 14 for both 

**Append a debug log**
[debug-Wed_Jul_3_15_11_29_2024.log](https://github.com/user-attachments/files/16085496/debug-Wed_Jul_3_15_11_29_2024.log)

**Comment by cagnulein** [comment]
this is the issue

```
07-03 15:41:00.753  1000  1621  2245 W ActivityManager: Permission Denial: Accessing service com.dsi.ant.server/.AntService from pid=7236, uid=10037 requires com.dsi.ant.permission.ANTRADIO
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: Initialising com.dsi.ant.chip.hal.AntAidlInterface@306a07d failed.
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.dsi.ant.server.IAntHal cmp=com.dsi.ant.server/.AntService }
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: 	at com.dsi.ant.chip.hal.AntAidlInterface.initService(SourceFile:62)
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: 	at com.dsi.ant.chip.hal.AntAidlInterface.init(Unknown Source:6)
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: 	at com.dsi.ant.adapter.AdapterStateMachine$2.initHardware(Unknown Source:9)
07-03 15:41:00.754 10037  7236  7500 E AdapterProvider: 	at com.dsi.ant.adapter.AdapterStateMachine$2.run(SourceFile:184)
```

Did you see a popup the first time you run qz with the dongle about using it in QZ? I guess you said by mistake no there
Let me know

**Comment by itsredan97** [comment]
> Did you see a popup the first time you run qz with the dongle about using it in QZ? I guess you said by mistake no there Let me know

Erased data on the app and gave all the permissions needed with the dongle plugged in **before** opening the app, but I'm still experiencing the same issue. DIdn't get a specific request of permission for ANT+ connection by the way, just the one for nearby devices scan.

**Comment by cagnulein** [comment]
@itsredan97 any news?
