### ISSUE TITLE
[BUG] Unable to switch gears on Kickr Core on Rouvy

### ISSUE THREAD

**Issue by okogut** [cagnulein/qdomyos-zwift#2426]
**Describe the bug**
I just received the new "Zwift Ride with Kickr Core" - but to my surprise the virtual shifting only works in the Zwift app.
I would like to try Rouvy and stumpled upon this app, as it seemed like it could be used for the virtual shifting, now that the controllers only works with Zwift.

From a clean install of QZ app (iOS) and with default settings, it has no effect when clicking the +/- buttons on the Gear tile.
I only tried with Rouvy. Am I missing something? Do I have to change some settings? I did try to adjust the "Gears gain" setting higher, to be sure to feel if it had an effect, but still none.

**To Reproduce**
1. Open QZ (default settings)
2. Connect to Kickr Core (3D14)
3. Open Rouvy 
4. Start a ride
5. Shift gears in QZ while riding - no change in resistance

**Expected behavior**
I expected that when pressing the + button resistance would increase and the - button resistance would decrease.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Apple TV
 - Version: 1st gen

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 
 - Version 17.5.1

**Comment by cagnulein** [comment]
i would like to send you the beta, i guess i already handled this. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by okogut** [comment]
Thanks for the help. I tried the beta version of the app. Unfortunately the gears +/- buttons still seems to have no effect. If I click the +/- buttons on the resistance tile however, I can feel an effect for 1-2 seconds, and then it seems like it goes back to the resistance on Rouvy.
I appreciate your help.

**Comment by cagnulein** [comment]
send me the debug log and i will check it
thanks
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by okogut** [comment]
[debug-fre__jul__5_20_41_14_2024.log](https://github.com/user-attachments/files/16113057/debug-fre__jul__5_20_41_14_2024.log)

I started out with trying to increase the gears up to ~25 - again, no effect. Pressed a bit on the resistance +/- buttons, it had some effect but for a short moment. Again shifting gears back down to 0 had no effect. Hope you can use the log.

**Comment by cagnulein** [comment]
Thanks , I will check it on Monday. I'm currently on vacation. Have a nice
weekend.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 lug 2024 alle 21:02 okogut ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@okogut I checked the log but I didn't see the connection with rouvy. The gears mod is applied only when you are connected to a 3rd party app. Did you do in the log? If not can you try again connected with rouvy?
let me know!

**Comment by okogut** [comment]
Can you describe to me how to do that correctly? What I do is:
1. Start qz on iPhone and connect to bike
2. Start ROUVY on Apple TV and connect ROUVY to bike
3. Start a ride

**Comment by okogut** [comment]
Ooh bummer… I didn’t realise I had to connect qz as controllable, but it makes perfect sense. It works now..
Thanks a lot for your help!

**Comment by cagnulein** [comment]
that's great!
Please remember to rate the app and the support on the store, it means a lot to me!
Thanks!
