### ISSUE TITLE
[BUG] Toorx srx 500 connects but no metrics load

### ISSUE THREAD

**Issue by vladnl76** [cagnulein/qdomyos-zwift#2428]
**Describe the bug**

[debug-Thu_Jul_4_19_36_30_2024.log](https://github.com/user-attachments/files/16101862/debug-Thu_Jul_4_19_36_30_2024.log)
[debug-Thu_Jul_4_19_26_47_2024.log](https://github.com/user-attachments/files/16101863/debug-Thu_Jul_4_19_26_47_2024.log)
 
Today I purchased qdomyoszwift, it connects to the bike, I can adjust the resistance, though software maximum isn’t equal to bike maximum, however my biggest problem is not being able to see any metrics, therefore also not able to start program, or start the zwift either, as metrics aren’t active.

log files in the message for further analysis.

**Screenshots**
![IMG_6935](https://github.com/cagnulein/qdomyos-zwift/assets/174739168/54d86b9c-e3f6-40c1-8e60-04fc63966709)
![IMG_6936](https://github.com/cagnulein/qdomyos-zwift/assets/174739168/97ca1826-888b-42c1-bae0-8d6bee72214c)
![IMG_6937](https://github.com/cagnulein/qdomyos-zwift/assets/174739168/4ec092e2-d278-4034-8599-ea5ac2a02806)
![IMG_6938](https://github.com/cagnulein/qdomyos-zwift/assets/174739168/a1094941-731d-4fcb-b13d-36bb6b829c49)

**Smartphone (please complete the following information):**
 - Device: iPhone15 max pro
 - OS: iOS17.5.1
 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @vladnl76 log checked. the connection with your bike is fine but it simply sends all 0. Do you have an app that already works with this bike? do you have also an android device to collect some data?
Let me know

**Comment by vladnl76** [comment]
I’ve just finished kinomap training, so yes that works, Iconsole+ works too, controls the bike, gathers the metrics, can do training there as well, however I can’t see the bike under settings > update device, it hangs on connecting. I wanted to update the firmware, however that isn’t possible anymore.

**Comment by vladnl76** [comment]
I do have android tablet, Iconsole behaves the same as on iOS. 
What data would you want me to gather?

**Comment by cagnulein** [comment]
perfect! from your android device, following this with kinomap or iconsole+ app https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device collect the log so i will check the implementation! then i will be able to fix both ios and android version.

I'm going to bed now, I will be back in 8 hour. 
Thanks

**Comment by vladnl76** [comment]
Will do tomorrow after work, missed the message and android tablet battery needs charging

**Comment by cagnulein** [comment]
Ok no problem!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 lug 2024 alle 22:56 vladnl76 ***@***.***> ha
scritto:

**Comment by vladnl76** [comment]
I hooe this is good one. My tablet is really old, running android 6.0, and some of instructions aren’t exact.

[bugreport-2024-07-05-18-47-07.zip](https://github.com/user-attachments/files/16112162/bugreport-2024-07-05-18-47-07.zip)

**Comment by cagnulein** [comment]
Thanks, I'll check it out!
I'm away for the weekend, I will check it on Monday

Il giorno ven 5 lug 2024 alle 18:52 vladnl76 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @vladnl76 unfortunately i can't see the hci snoof file here. Did you enable this setting in the android developer settings?

**Comment by vladnl76** [comment]
Yes I have, dollowed instructions, driven bike with hci on, then as instructions say switched hci off and downloaded bug report. 

I’ll do once more withi hci on all the time.

**Comment by cagnulein** [comment]
ok, yeah unfortunately every android flavours it acts differently. Thanks

**Comment by vladnl76** [comment]
[bugreport-2024-07-08-17-07-38.zip](https://github.com/user-attachments/files/16131123/bugreport-2024-07-08-17-07-38.zip)

how about now?

**Comment by cagnulein** [comment]
same thing, there is only the txt file :( do you have another android device to try with?

**Comment by vladnl76** [comment]
Unfortunately I don’t. I’ll check with friends, but I’m afraid it will take some time.

**Comment by cagnulein** [comment]
ok no problem, by the way which particular android device do you have?

**Comment by vladnl76** [comment]
Really old Asus zenpad tablet, with android 6.0

**Comment by cagnulein** [comment]
hah ok, it could be the reason so :(

**Comment by vladnl76** [comment]
Hi @cagnulein Roberto, I’ve managed to borrow somewhat newer Samsung Galaxy tablet, Android 11. Hopefully you’ll be able to see more here?

[bugreport-gta3xlwifieea-RP1A.200720.012-2024-07-10-17-38-50.zip](https://github.com/user-attachments/files/16164853/bugreport-gta3xlwifieea-RP1A.200720.012-2024-07-10-17-38-50.zip)

**Comment by vladnl76** [comment]
What is also surprising is that I can’t check or update my firmware from iConsole+, but I can control the machine and gather the metrics on the iConsole+.

![IMG_6978](https://github.com/cagnulein/qdomyos-zwift/assets/174739168/9d0aa20d-fae1-42b7-87f6-3fd5d9114295)

**Comment by cagnulein** [comment]
perfect, I can see everything, I will add it asap!

**Comment by cagnulein** [comment]
@vladnl76 done

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9887327347

enable the new toorx srx 500 setting and restart qz (disable the others in the same section)

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.


Let me know if you have any questions

**Comment by vladnl76** [comment]
Hi Roberto,

I am IOS user, I,ve purchased QZ on apple alp store, I don’t have good android device, however I can test this with the one I have on loan.

are you planning to recompile iOS version too?

**Comment by cagnulein** [comment]
hah sure, i'm doing it right now. send me an email so i will send you the beta

**Comment by cagnulein** [comment]
that's amazing! send me an email to roberto.viola83 at gmail.com

also remind to rate the app on the store, it means a lot to me!
also joining patreon will be very appreciated https://www.patreon.com/cagnulein

Thanks
