### ISSUE TITLE
[BUG] QZ app shows only zeros after connecting to bike (LifeFitness IC5 with TFT 1.0 console)

### ISSUE THREAD

**Issue by catdevrandom** [cagnulein/qdomyos-zwift#2429]
**Describe the bug**
I can connect the bike to the app, but all tiles show only zeros. 
Using QZ app version 2.16.55 on Xiaomi Redmi 13 Pro+, with Android 14.

**To Reproduce**
1. Pedal the bike to wake up the bike's console
2. Select Power Training or HR training in the bike's console
3. Say "yes" to pair app in the app console
4. Open the app in phone. The phone finds the bike and shows the tiles
5. The bike console says that pairing failed. I select cancel and input manually my stats, and start the training
6. The bike console shows my RPM, HR, power % and level while pedaling, but the app shows only zeros.

**Expected behavior**
I would expect to see in the app the same values as displayed in the bike's console.

**Screenshots**
![449637246_10169304952815475_3368868483035958273_n](https://github.com/cagnulein/qdomyos-zwift/assets/133627/d32c4fa2-b9b8-490f-8c78-67094a82b322)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 13 Pro+
 - OS: Android 14
 - Version: QZ app version 2.16.55

**Append a debug log**
[debug-Thu_Jul_4_20_37_37_2024.log](https://github.com/user-attachments/files/16102185/debug-Thu_Jul_4_20_37_37_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
I was able to use FlyTest to connect to the bike (using Chrome on a Linux laptop) and in Flytest I could calibrate the bike and I can see the data from the bike (same as in the bike's console). But in the app it only shows zeros. I have changed the batteries (2 D-sized batteries). The bike connects without issues to the official ICG app.

**Comment by cagnulein** [comment]
@catdevrandom under the bike settings, flywheel settings

enable `Life Fitness IC8` and restart QZ

Let me know

**Comment by catdevrandom** [comment]
@cagnulein Now I got something in the tiles! But the app seemed to have become unresponsive soon afterwards. I forcibly closed it. Here's the log:
[debug-Thu_Jul_4_21_11_48_2024.log](https://github.com/user-attachments/files/16102286/debug-Thu_Jul_4_21_11_48_2024.log)

**Comment by cagnulein** [comment]
i don't see anything strange in the log. maybe it's the debugging log that it streaming a log? try to disable it and let me know if it's better

**Comment by catdevrandom** [comment]
It worked! Indeed it seems that the log stream was making the app choke. 
Thank you so much, you're awesome!

**Comment by cagnulein** [comment]
that's great! remember to rate the app on the store! it means a lot to me! thanks!
