### ISSUE TITLE
Support for Proform 705 CST treadmill (firmware V80)

### ISSUE THREAD

**Issue by Novamusix** [cagnulein/qdomyos-zwift#2430]
### Description
The QZ app currently supports the Proform 705 CST treadmill for a previous firmware version. However, after updating the treadmill’s firmware through the iFit app, the QZ app can no longer control the treadmill’s speed. It still manages inclination, but the treadmill freezes and requires a power cycle to reset. The workaround is to select Norditrack 10 in the QZ app, which connects and reads both speed and inclination but does not control.

Could you please add support for the updated firmware to enable speed and inclination control? This would enhance the QZ app’s functionality during workout sessions with Runna.

### Supporting Information
**Treadmill**
Proform 705 CST V80.237
![image](https://github.com/cagnulein/qdomyos-zwift/assets/121513476/e0dda8b3-b5dd-4c4a-a3c1-339eda59920c)

For reference the previous firmware version that seemed to work was V78.239
![image](https://github.com/cagnulein/qdomyos-zwift/assets/121513476/5ffca051-15c6-40ca-97c9-f0068340cf5d)

**BT snoop log**
Attached is the BT snoop log file, whilst using iFit to connect and control the treadmills speed and inclination.
[btsnoop_hci.log](https://github.com/user-attachments/files/16116612/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks, I will check it next week!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 lug 2024 alle 17:50 Novamusix ***@***.***> ha
scritto:

**Comment by Novamusix** [comment]
Thank you for responding quickly :-) , the update now controls the speed of the treadmill both via QZ and Runna.

Useful information for anyone who has the same machine: The treadmill locks out the speed when trying to adjust using QZ starting from zero. You have to first directly set a speed on the treadmill and then you can adjust on QZ. The iFit app requires the user to press and hold the start button on the treadmill which then seems to send some unlock message to the treadmill, not sure if replicating this behaviour is beyond the scope of QZ. I will follow a sequence of steps at the start of a workout session, so can workaround this. 👍

**Comment by cagnulein** [comment]
that's great!
