### ISSUE TITLE
Watt problem

### ISSUE THREAD

**Issue by Dingdong765839** [cagnulein/qdomyos-zwift#2434]
[debug-Sun_Jul_7_22_49_46_2024.log](https://github.com/user-attachments/files/16120752/debug-Sun_Jul_7_22_49_46_2024.log)

As contacten via email (sandervaneck95@gmail.com)

**Comment by cagnulein** [comment]
ok thanks, i will check this tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 lug 2024 alle ore 23:01 Dingdong765839 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
hi @Dingdong765839 
disable the` Bike 500 wattage profile` setting in the domyos bike settings and let me know!
