### ISSUE TITLE
Unable to connect Echelon connect  Bike to Android TV box QZ app

### ISSUE THREAD

**Issue by lewisg1989** [cagnulein/qdomyos-zwift#2435]
![Screenshot_20240708-225534](https://github.com/cagnulein/qdomyos-zwift/assets/175061467/bded2069-d6d7-4b6b-90a8-50780acc5edd)

I could only upload a screen shot of the debug data which I think may have failed anyway. 

My past email is below with a  detailed description of issue, an update I can confirm the bike and app work perfectly of my phone and laptop, and it was connecting through the android box at the beginning.

Hi Roberto 

Great app by the way , hope you can help. This could be the bike it could be the newly purchased Android Tv Box or even our second hand Echelon connect bike.

All was working well, bike would connect to the android box Bluetooth then the QZ app showing all data. This would then all work through the Zwift app happy days. :)

As of a few days ago it would take a while for the bike to connect to the app and box, the bike bluetooth light flashed away and when asked to connect does but then quickly fails. With the QZ app open when it fails to connect says incorrect pin/code. In the end it would connect tho this may take an hour tho.

As of yesterday it won't stay connected at all, It connects for a few seconds when asked then disconnects. :(

Things I've tried, Android box on and off, Bluetooth on and off, bike on and off. Bluetooth data cashe deleted. Turned all local Bluetooth off, I haven't removed and reloaded the QZ app yet should I? 

Hope you can help I was thinking of returning the Android Box (photo attached)? I'm hoping it's not the bike, Bluetooth light is flashing away fine.

Many thanks

**Comment by cagnulein** [comment]
hi @lewisg1989 could you please post a photo in landscape, i can't read all
thanks
