### ISSUE TITLE
Please explain my options with qdomyos

### ISSUE THREAD

**Issue by snovvmann** [cagnulein/qdomyos-zwift#2439]
I am new to connected fitness machines.  This is what I know so far: With my new Proform iFit bike (no tablet, just LCD controller with "iFit" button), I need to have a subscription to get auto resistance on a ride.  

Now with qdomyos--is it essentially a bridge to other subscription services such as Zwift, Rouvy, Wahoo, etc.?  Obviously, they all require subscriptions, but provide alternatives to iFit?  I am still trying to wrap my head around what all that qdomyos does.

I do not need scenic rides, encouragement, or graphics--just auto resistance with pre-programmed rides.  Can this be accomplished using qdomyos without a subscription?

Another question--I see that qd can send some data to Strava.  I would like to integrate with Apple Health or Google Fit/Health Connect.  Can I send the data to Strave and have it send the data to Apple Health?

Thanks.

**Comment by cagnulein** [comment]
yes you can use qz standalone as i do it every day for this! no
subscription required!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 lug 2024 alle 22:02 snovvmann ***@***.***> ha
scritto:

**Comment by snovvmann** [comment]
> yes you can use qz standalone as i do it every day for this! no subscription required! 

Thanks for your quick reply!  I have an iPhone/iPad as well as Android and tablet.  **I presume the data does not sync between the two platforms?**  I am glad to buy the app on both and join the Swag Bag for what the app might provide.

Is it a matter of installing the app on, say, an iPhone or iPad, then pair with the iFit device on my Proform, and **there are pre-programmed rides where it can automatically control the resistance?**

Also, what are my options of getting this data to Apple Health or Google Fit?

Cheers.

**Comment by cagnulein** [comment]
> Thanks for your quick reply! I have an iPhone/iPad as well as Android and tablet. **I presume the data does not sync between the two platforms?** I am glad to buy the app on both and join the Swag Bag for what the app might provide.

if you buy on android, yes you have to buy also on apple store if you want to use it on ipad or iphone if it's what you mean. settings can be moved from android to ios if you want for example.



> Is it a matter of installing the app on, say, an iPhone or iPad, then pair with the iFit device on my Proform, and **there are pre-programmed rides where it can automatically control the resistance?**

yes exactly. there are pre programmed workouts, but you can write your own ( https://www.zwiftworkout.com/ ) or you can just download them from here for example https://whatsonzwift.com/workouts
they are all free



> Also, what are my options of getting this data to Apple Health or Google Fit?

apple health is supported if you have an apple watch too (qz runs also on apple watch).
there is also a version for android wear but i'm not exporting data to goole fit at the moment.
let me know if you have any questions, i'm going to bed now so i will be avaiable back in 8 hours

**Comment by snovvmann** [comment]
So I will be able to download the rides and your mobile apps will be able to use them directly?

Your app might just be the perfect solution for me.  Is it true that I can move the data between iOS and Android and vice versa?  Is it a manual process to do that?

I have an WatchOS (Samsung Galaxy) watch, but no Apple Watch at this time.  Do you have plans to implement writing of the data directly to Apple Health or Google Fit?

Thanks again!

**Comment by cagnulein** [comment]
> So I will be able to download the rides and your mobile apps will be able to use them directly?
> 
> 

yes!

> 
> Your app might just be the perfect solution for me.  Is it true that I can move the data between iOS and Android and vice versa?  Is it a manual process to do that?
> 
> 

yes manual process, simply copying a file :)

> 
> I have an WatchOS (Samsung Galaxy) watch, but no Apple Watch at this time.  Do you have plans to implement writing of the data directly to Apple Health or Google Fit?

yes i already started this process. in the meantime you can use the rungap app on ios to do sync everything coming from qz to both platforms 

> 
> 
> 
> One more thing--I read that iFit still has to be running.  Is that true?  Or, can your app pair with my bike directly?
> 
> 

if your fitness device connects to ifit via bluetooth on your phone, nope you don't need to run ifit in background 

let me know if you have any other questions 

> 
> Thanks again!

**Comment by snovvmann** [comment]
Thanks very much for your help.  I got the app, it paired with iFit easily. I visited https://whatsonzwift.com/workouts, I saw the workouts, but saw no obvious way to download them and import them into your app.  Will you please provide some insight?

**Comment by cagnulein** [comment]
hah they removed the ability to download them. here they are . you can open using the open training program menu on the left side bar, and clicking the bottom button other files. let me know 
[out.zip](https://github.com/user-attachments/files/16201116/out.zip)

**Comment by snovvmann** [comment]
Wow thanks for the zip file!  I will check it out and report back.
