### ISSUE TITLE
[REQ] iConsole + Torneo C-720BL won't connect

### ISSUE THREAD

**Issue by xmount** [cagnulein/qdomyos-zwift#2442]
Hello,
I have an elliptical trainer Torneo Premium Ergo C-720BL.
Installed the iConsole application. The application sees my trainer via Bluetooth, but when I try to connect, it says Connection Failure.
I tried it on both iPhone and Android.
Can you tell me what can be done and how to connect the simulator?

**Comment by cagnulein** [comment]
Hi @xmount can you show me what you see on nrfconnect app? nrfconnect it's free on the store
Let me know

**Comment by cagnulein** [comment]
also did you already try qz?

**Comment by xmount** [comment]
> Hi @xmount can you show me what you see on nrfconnect app? nrfconnect it's free on the store Let me know
Please look at the pictures.
haven't tried qz
![elt1](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/3f36aab3-425d-4366-9aff-9ee8f1114950)
![elt2](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/4d74a10b-0c5d-4e46-9c48-7e9d7f121031)
![elt3](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/c0748e76-b741-450d-a7a3-c10bdae08c4b)
![elt4](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/f4006bbf-42ac-47a1-8369-4825226b45d8)
![elt5](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/f9d81ec6-6459-4252-8f1c-5ae1b3b3fe99)

**Comment by cagnulein** [comment]
ok it's the same of #2419  !

https://github.com/cagnulein/qdomyos-zwift/actions/runs/9887567854

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial. 

Did you already download the qz app from the store?

Let me know if you have any questions

**Comment by xmount** [comment]
> ok it's the same of #2419 !
> 
> https://github.com/cagnulein/qdomyos-zwift/actions/runs/9887567854
> 
> Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded. This version is a 15 minutes trial.
> 
> Did you already download the qz app from the store?
> 
> Let me know if you have any questions

Thank you! But can you tell me how to download the apk-file for Android using your link?

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/9887567854/artifacts/1689963687

**Comment by xmount** [comment]
> or you can simply use the qz app from the store and set your device to ftms treadmill setting in the treadmill settings Let me know
I installed the apk using your link and see what’s in the picture. It seems that the simulator has connected, its screen has gone out, but at the same time no data in the fields on the screen changes, although I tried to pedal for a long time. I also tried clicking the Start button, but it didn’t help.
![photo_2024-07-11_11-41-58](https://github.com/cagnulein/qdomyos-zwift/assets/33452142/b97c2887-9fcc-49bc-8788-93e51b5a0d04)

**Comment by cagnulein** [comment]
attach here a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
thanks i will check it later

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 lug 2024 alle 13:25 xmount ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the issue @xmount i'm fixing it

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/9892016515
let me know!

**Comment by cagnulein** [comment]
qz is not compatibile with iconsole at the moment, or at least I never tried. So your final target is using QZ with iconsole on another device?

**Comment by xmount** [comment]
> qz is not compatibile with app iConsole at the moment, or at least I never tried. So your final target is using QZ with iconsole on another device?

I would like to use the app iConsole application with my simulator, which is what I originally wrote about :)
But I don’t know yet, maybe qz will suit me - my goal is to conduct classes on the simulator and save statistics on my phone.

**Comment by cagnulein** [comment]
you don't need iconsole for this. qz can save all the workouts on strava, following 3d maps or doing a training program directly on the app standalone!

**Comment by xmount** [comment]
> you don't need iconsole for this. qz can save all the workouts on strava, following 3d maps or doing a training program directly on the app standalone!
Amazing! Can you tell me if it’s possible to use the app qz application so that I can work out according to the simulator program, so that the screen doesn’t go dark, and at the end of the lesson I get statistics?

**Comment by cagnulein** [comment]
yes QZ does exactly this

**Comment by xmount** [comment]
Thank you! I'm going to try now!

**Comment by xmount** [comment]
I tried your build, thanks, the numbers appeared on the screen, and when you click on Stop, statistics are displayed.
But when the lesson starts, the screen goes dark and the program selected on the simulator apparently does not work.
Can you tell me if this can be configured somewhere so that I can select a program on my simulator and the screen won’t go blank?

**Comment by cagnulein** [comment]
sorry could you please explain what's is the simulator? do you mean the elliptical? i thought the "simulator" was QZ

**Comment by xmount** [comment]
Yes, I mean the elliptical trainer, I'm just writing through Google Translate :)

**Comment by cagnulein** [comment]
ok so that's a feature/bug of the firmware of the console. if you find an app that doesn't turn it black I can emulate it. Anyway you have all the stats in QZ so you can simply run QZ on a tablet to see everything!

**Comment by xmount** [comment]
Should I choose a workout program for the elliptical trainer directly in the app QZ? Can't you use the workout program from the elliptical trainer itself?

**Comment by cagnulein** [comment]
nope usually all the fitness devices, when you are connected to an app, they are slave, and they just play what the app says.
So yes you have to create a program in QZ.

**Comment by xmount** [comment]
Thank you! I'll try later.
Tell me, is there any way to make the iConsole app work with my elliptical trainer?

**Comment by cagnulein** [comment]
> Tell me, is there any way to make the iConsole app work with my elliptical trainer?

as I said you can try to use QZ on a device and check if the iconsole, on another device, can see the QZ device. Anyway as I said I don't think it's necessary to do your workouts :)

**Comment by xmount** [comment]
You probably misunderstood me :)
I'm talking about the iConsole+ application: https://play.google.com/store/search?q=iconsole&c=apps

**Comment by cagnulein** [comment]
yes I understood! I mean why you should use the iconsole if QZ standalone does the same and more?

**Comment by xmount** [comment]
I just wanted to try and compare :)

**Comment by xmount** [comment]
Hello Roberto!
As I understand it, you posted a test build for me and I now need to download it to Google Play?
Can you tell me when it will be possible to download?

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/actions/runs/9892016515/artifacts/1691096610 
lol I did 3 days ago, i thoguht you already tried this :)

**Comment by xmount** [comment]
According to your link, yes, I tried it, everything works.
But can I continue to use your assembly or should I download it from Google Play:?

**Comment by cagnulein** [comment]
i sent the update in the google play, i'm waiting for the google review. it could happen any minute. You can see it joining the beta https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

the version will be the 2.16.63

**Comment by xmount** [comment]
Thanks a lot!

**Comment by xmount** [comment]
Hello!
I noticed that your app has finally been updated in Google Play.
I tried to install it, but Google won't let me, because I'm from Russia.
Can you tell me if I can somehow buy your app without Google?

**Comment by cagnulein** [comment]
hi @xmount you can use the built from here https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk and then I can unlock it joining the patreon membership
Thanks!

**Comment by xmount** [comment]
Thank you! I installed the apk.
Can you tell me what to do next and what data to send?

**Comment by cagnulein** [comment]
hi join the membership here https://www.patreon.com/cagnulein and add the same email all lowercase in the qz email setting in the general setting
Let me know!

**Comment by xmount** [comment]
Tried to join but only monthly subscription is offered. Can you tell me if there is a one-time payment subscription?

**Comment by cagnulein** [comment]
Nope but you can do a month and stop it then (consider that I have
recurrent outcome for qz so I really need all the help for everyone that
can handle, even a  0.99$ monthly)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 12:48 xmount ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
On which way you can pay? send me a message to roberto.viola83 at gmail.com
it's better to talk in private :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 13:11 xmount ***@***.***> ha
scritto:

**Comment by xmount** [comment]
Ciao Roberto!
Ti ho scritto una lettera

**Comment by cagnulein** [comment]
@xmount i handled the kinomap protocol and i have a new build

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10879603102

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

[btsnoop_hci (70).zip](https://github.com/user-attachments/files/17009806/btsnoop_hci.70.zip)

**Comment by cagnulein** [comment]
sorry new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/10879890644

**Comment by cagnulein** [comment]
@xmount Did it work?
