### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kard8** [cagnulein/qdomyos-zwift#2444]
**Describe the bug**
The app shows my generic FTMS bike but does not connect to it.

**Expected behavior**
Connection to bike.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Would like to connect my generic FTMS bike made by FlexNest a manufacturer in India.

**Comment by cagnulein** [comment]
hi please give me more context adding a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
also if you can install the free app nrfconnect and send me a screenshot about your bike.
Thanks

**Comment by kard8** [comment]
Hi @cagnulein! Thank you for the lightning fast response 

Here's the device info.

Found that it's a variant of YesSoul bikes in its Bluetooth device information.

Need your help connecting...


![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/d38b53d5-7e13-4901-8920-d9decf1aecef)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/aa08229c-d08d-4947-8c6c-0e0669df4199)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/e0b23c1c-05f6-4732-998e-eb8a1a526fb4)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/c7c6326d-a32b-42dc-b5f3-e1cd0b53e2dc)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/8065c81f-9555-47fa-a18b-7d8f7be9eb0b)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/1c878de3-c446-46c6-ac0f-db83ddfd2762)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/50cb82a6-a416-4714-99c3-ba7a381b708f)

![image](https://github.com/cagnulein/qdomyos-zwift/assets/110168813/7f860bdb-5122-41fc-b050-5c8ad05c2212)

**Comment by kard8** [comment]
[debug-Thu_Jul_11_18_22_46_2024.log](https://github.com/user-attachments/files/16177842/debug-Thu_Jul_11_18_22_46_2024.log)
 Here's the debug file.

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com and I will send you a new beta.
When you will receive it, set this bike under settings, bike, ftms bike and press ok

Let me know!

**Comment by kard8** [comment]
Thank you @cagnulein!! Can't wait to test it out!

**Comment by kard8** [comment]
This works flawlessly with the nightly release on Android!! 🤩 I apologize if my request came across as a dumb one.

I have been wanting to connect this bike to my apple watch since they released the watchOS 10 Beta on my watch SE.
I tried gymnasticon method but that failed to work, and the dev was not reachable too after the pandemic. Then I stumbled upon your app a year back. I bought your app and it didn't work then.

I gave up all hope of connecting my bike without hardware mod to my Apple Watch. I opened this Bug as a last effort. And within a couple of hours, just like magic, you made this work. 

Tried it and it works flawlessly too.

Thank you so much @cagnulein for your efforts!! You made my day today! I am happy with the Android app.

The test fight version connected to my bike and showed the metrics. I started a bluetooth service for Cycling power. I connected it to my watch but the data was not receiving.

Here's the logs for it.

[debug-Thu_Jul_11_20_06_48_2024.log](https://github.com/user-attachments/files/16179255/debug-Thu_Jul_11_20_06_48_2024.log)

**Comment by cagnulein** [comment]
> The test fight version connected to my bike and showed the metrics. I started a bluetooth service for Cycling power. I connected it to my watch but the data was not receiving.

you have simply to use qz on the apple watch too without using the apple workout app. QZ saves all the metrics, included the power in apple health!
Let me know

Also please review the app on the store, it means a lot to me!

**Comment by kard8** [comment]
Thank you so much for your incredible support. Will use the android method for now. Will definitely leave a review as soon as possible.

**Comment by kard8** [comment]
On a side note. Got the setup working with my iPad too. Had my previous settings messing with the broadcast of data via BLE Cycle power service.

I copied the settings file from a working android phone and now it Works flawlessly. Your app just saved an old device from going to the bin!!

**Comment by cagnulein** [comment]
That's awesome!

**Comment by cagnulein** [comment]
qz already saves the speed and distance on apple health with the beta version. or are you talking just see them in realtime? it's possible of course

**Comment by kard8** [comment]
I mean in real time in apple watch  workouts app. 

I looked through this issue https://github.com/cagnulein/qdomyos-zwift/issues/1924
Is there an update or setting to activate the Bluetooth Cycling Power service with speed included?

**Comment by cagnulein** [comment]
hah nope but it's not a limitation of qz, it's a limitation of apple. they don't handle ftms sensors so qz can send or power sensor or speed data. also qz with the power sends also the cadence and watches like garmin can calculate speed and distance from it, but apple watch shows it only sometimes.

my suggestion is to don't use the apple workout app because it's so limited with the bluetooth connectivity.

qz already saves the same metrics

**Comment by kard8** [comment]
How do I get it to show in my Fitness app directly. Would love to complete my rings with it!
Currently I upload my data directly to Strava from your app. 
Thanks to your app, I am getting a lot of kms in strava.

Also I am importing the fit file generated by HealthFit App to Apple Health and Fitness, but woruld like a more streamlined approach like the Strava integration.

**Comment by kard8** [comment]
Also
1. Can we see the battery data from the machine on the app dashboard?
2. When can we expect a new update on the app store..??

**Comment by kard8** [comment]
I am using version 2.16 (810)

**Comment by cagnulein** [comment]
> Also
> 
> 1. Can we see the battery data from the machine on the app dashboard?


what is the battery data?

> 2. When can we expect a new update on the app store..??

i'm updating it only when an issue impacts a lot of users, so keep using the beta





> I am using version 2.16 (810)

so you have simply to use the qz app on the watch too instead of using the apple workout app. that's it!

**Comment by kard8** [comment]
Got It! Thank you so much!
The bike is powered by a coin battery. It Runs out pretty quickly too.
Its exposed as a number here

![image](https://github.com/user-attachments/assets/37dffa4f-0085-400d-8185-5ea92ab809ba)

**Comment by cagnulein** [comment]
yes i can read it of course but this will mean to create a new tile or something. or maybe i can show you a little toast message on the startup. what do you think?

**Comment by kard8** [comment]
A toast would be great! Would get the key info without occupying screen area...

**Comment by cagnulein** [comment]
done! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by kard8** [comment]
Thanks for the update. I. am not getting the popup when I start the App..
It's okay anyways. The app is really good. Thank you so much @cagnulein.

**Comment by cagnulein** [comment]
@kard8 did you install the update?

**Comment by kard8** [comment]
Yes, I did Install the update. 
Here's the debug for a trial ride I did today. 
Thank you.
[debug-Sun_Jul_28_16_27_35_2024.log](https://github.com/user-attachments/files/16403016/debug-Sun_Jul_28_16_27_35_2024.log)

**Comment by cagnulein** [comment]
Thanks, I will check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 lug 2024 alle 13:02 kard8 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i checked the log and I can see the battery level. Are you sure you don't
see it? It's popups at the bottom of qz for 3 seconds at the startup

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 lug 2024 alle ore 14:06 cagnulein ***@***.***> ha
scritto:

**Comment by kard8** [comment]
It doesn't appear... I don't mind that, it's not a deal breaker for me. 
However, I do want to know, how to turn on Cycling Speed and cadence sensor virtual device manually...

**Comment by cagnulein** [comment]
> It doesn't appear... I don't mind that, it's not a deal breaker for me.

that's so strange. anyway if you want in the next one i will a new debug log to understand it better. I can see it on my setup so maybe there is something different on yours



> However, I do want to know, how to turn on Cycling Speed and cadence sensor virtual device manually...

use the peloton cadence sensor setting in the peloton section in QZ.

**Comment by kard8** [comment]
Thank you @cagnulein! 
Fell ill for a couple of weeks. Now I'm good.

> use the peloton cadence sensor setting in the peloton section in QZ.


1. I can see only the cadence values missing the speed values. I want to know how to broadcast values in BLE CSC mode. 
2. Can the QZ App send data over Wifi to another device running QZ app?
3. Is it possible to make the battery value as a tile?

**Comment by cagnulein** [comment]
> Thank you @cagnulein! Fell ill for a couple of weeks. Now I'm good.

Great!

> > use the peloton cadence sensor setting in the peloton section in QZ.
> 
> 1. I can see only the cadence values missing the speed values. I want to know how to broadcast values in BLE CSC mode.

Speed is just a cadence * wheel ratio. Where do you want to use it?


> 2. Can the QZ App send data over Wifi to another device running QZ app?

Yes it's already doing in 2 ways: via dircon already compatible on zwift and via http on the floating window. I also added a branch to use OSC protocol

> 3. Is it possible to make the battery value as a tile?

The battery of the bike?

**Comment by cagnulein** [comment]
@kard8 I guess i fixed the battery notification, I'm sending you a new one!
