### ISSUE TITLE
Support For The NordicTrack Commercial 1750

### ISSUE THREAD

**Issue by JEMcats** [cagnulein/qdomyos-zwift#2448]
I want to use Zwift on my NordicTrack Commercial 1750 and I setup the app and can see the device on Zwift but none of the info is updating, my treadmill is at 2.5 MPH and Zwift is still displaying 0 MPH, Please Help. Also I was unable to find the Commercial 1750 in the device list.

**Comment by cagnulein** [comment]
hi @JEMcats first of all are you seeing the correct speed on QZ? if so where qz runs and where zwift does?

**Comment by JEMcats** [comment]
Zwift is running on my iPhone, QZ is running on the treadmill

**Comment by cagnulein** [comment]
you need qz running on the iphone and zwift on another device. the qz version that it's running on the treadmill, it's not qz itself, it's the companion. you have to follow this https://www.google.com/search?q=yt+qz+nordictrack&oq=yt+qz+nordictrack&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDM4MDdqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8#:~:text=Nordictrack%20Treadmills%20Wifi%20only%20finally%20compatible%20with%20Zwift%20...,https%3A//www.youtube.com%20%E2%80%BA%20watch

**Comment by JEMcats** [comment]
Why is the iPhone app $5 while the android app is free?

**Comment by cagnulein** [comment]
it's not free. the companion app it's free, but also the google play cost 5$ https://play.google.com/store/apps/details?id=org.cagnulen.qdomyoszwift&hl=it

**Comment by JEMcats** [comment]
then what's the apk file in the latest release?

**Comment by cagnulein** [comment]
where? here? yes you can use it on the android phone. it's a trial, requires patreon subscription then. all of this it's a huge work for me, so it's not free.

**Comment by JEMcats** [comment]
ok that makes sense thanks for the clarification.

**Comment by JEMcats** [comment]
sorry, I am not interested in paying the $5 for the app, thanks for the help!

**Comment by cagnulein** [comment]
no problem!
