### ISSUE TITLE
[QZ app crashes on Android after recent update]

### ISSUE THREAD

**Issue by mazatov** [cagnulein/qdomyos-zwift#2452]
Recently, I'm guessing after latest update the app started to crash on my Pixel 8 phone.  The last time I successfully used the app was on June 29th. Nothing has changed in my setup since. 

Attached in the screenshot. 

![WhatsApp Image 2024-07-15 at 16 41 29_078ddfd3](https://github.com/user-attachments/assets/3925a3f8-70f9-484d-8d60-602541a595ce)

**Comment by cagnulein** [comment]
i guess i already fixed it. google is reviewing the version . you can leave
the beta channel of qz to fix it right now

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 15 lug 2024 alle 15:45 Mike Azatov ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mazatov are we OK?

**Comment by mazatov** [comment]
@cagnulein , Yes last time I ran it already worked, thanks for checking in!
