### ISSUE TITLE
QZ not reading heart rate monitor [BUG]

### ISSUE THREAD

**Issue by garyness5** [cagnulein/qdomyos-zwift#2457]
**Describe the bug**

I have been using the QZ app for about 3 years. I have it connected to an Echelon Echex 3. I have a Samsung S23+ with Android 14 installed.

I never used to have problems with heart monitors being read on QZ. About 2 years ago, it stopped recognizing the monitor - whether Wahoo (2 different ones) or PowrLabs. On the Wahoo and Strava apps, I never had any problem. Once in a while, it would pick up the monitor, start registering for a minute or two, then stop, never to pick it back up during the session. Most of the time, it did not even recognize the monitor. In the late fall and winter months, I use the stationary bike 4-5 times per week

During spring/summer, I bike outdoors and do not use the stationary bike and the QZ app. I did this morning to test it. It was recognized 4 times without any problem with the PowrLabs monitor.  But it did not read the heartbeats. 

I have only attached one of this morning's logs, as the problem repeated itself all four times. It is not essential to have the heart monitor working, but with it I have a better reading of my performance. Let me know if anything can be done or that I need to do

Thanking you in advance
Best regards

**To Reproduce**
[debug-Wed_Jul_17_07_28_25_2024.log](https://github.com/user-attachments/files/16270482/debug-Wed_Jul_17_07_28_25_2024.log)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung S23+
 - OS: Android
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
you have ant heart setting enabled under ant settings , put it off. it
certainly an issue . let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 lug 2024 alle 18:55 garyness5 ***@***.***>
ha scritto:

**Comment by garyness5** [comment]
Robert

As asked, I disabled the Ant+
I have included several logs from tests I did to try to connect the monitor
A couple of times, the app was able to detect the powrlabs monitor, but most of the times it wasn’t able to.
I clicked on refresh list many times. Most of the  times, it was not detected at all. And when it was, after restarting the app, the app did not show the bpm’s. I’d go back into settings and the monitor was not in the listing, other than the selected field. 
I would select a different app from the list, click refresh a few times, but would the monitor would not appear
The app shows and registers within a few seconds on Wahoo and Strava. I always remove them from the phone before connecting to the QZ
[debug-Wed_Jul_17_17_51_21_2024.log](https://github.com/user-attachments/files/16275222/debug-Wed_Jul_17_17_51_21_2024.log)
[debug-Wed_Jul_17_17_52_46_2024.log](https://github.com/user-attachments/files/16275223/debug-Wed_Jul_17_17_52_46_2024.log)
[debug-Wed_Jul_17_17_53_27_2024.log](https://github.com/user-attachments/files/16275224/debug-Wed_Jul_17_17_53_27_2024.log)
[debug-Wed_Jul_17_17_54_18_2024.log](https://github.com/user-attachments/files/16275225/debug-Wed_Jul_17_17_54_18_2024.log)
[debug-Wed_Jul_17_17_55_54_2024.log](https://github.com/user-attachments/files/16275226/debug-Wed_Jul_17_17_55_54_2024.log)
[debug-Wed_Jul_17_17_57_07_2024.log](https://github.com/user-attachments/files/16275227/debug-Wed_Jul_17_17_57_07_2024.log)
[debug-Wed_Jul_17_17_58_32_2024.log](https://github.com/user-attachments/files/16275228/debug-Wed_Jul_17_17_58_32_2024.log)

**Comment by cagnulein** [comment]
I see indeed in your log that the heart rate device is not discovered and there is only a reason for this: the device is connected to another app. You can also check this behaviour using the free app nrfconnect. if you can see it in the nrfconnect app you can see it also on qz, otherwise not. The fact that the HR device is not broadcasting itself, it's because it turned off or connected on the same phone but with another app for example in background.


also i checked the case where in the log, the HR device is available but it can't connect. This also mean that's something is connecting too to it, or the HR device just doesn't reply. From the QZ point of view, this is just one line of code, "connect", all the lower layer is handled by the operative system.

Are you able to do the same test on a phone or a tablet where you didn't installed any app that can connect to it? and also turning bluetooth off of the current phone? so we will double sure about what I just said

Let me know

**Comment by garyness5** [comment]
With the QZ logs, I have added screenshots of both nrf results and QZ
In all the tests, QZ only picked up the monitor and displayed the bpms once. It picked up the  monitor a couple of times but did not display anything. The funny part was that once when it picked up the bpm's, Strava and Wahoo were running. But most of the times, it was not picking up the monitor
Every time that  I checked QZ, nrf was picking up the heart monitor
Sorry for all the logs. I tested a few times
Like I said, if this is a problem, it is not that important for me to display the bpms


![nrf 23](https://github.com/user-attachments/assets/bdb5c90b-2e1e-43af-82a9-6a4cb86bb9ac)
![QZ settings 1](https://github.com/user-attachments/assets/16f6b56f-ddd2-452d-a8ea-3b2c91c081ce)
![QZ settings 2](https://github.com/user-attachments/assets/d4c621b4-7e6e-4001-9026-17a0721102d9)

[debug-Thu_Jul_18_20_03_10_2024.log](https://github.com/user-attachments/files/16297411/debug-Thu_Jul_18_20_03_10_2024.log)
[debug-Thu_Jul_18_20_03_57_2024.log](https://github.com/user-attachments/files/16297415/debug-Thu_Jul_18_20_03_57_2024.log)
[debug-Thu_Jul_18_20_08_38_2024.log](https://github.com/user-attachments/files/16297417/debug-Thu_Jul_18_20_08_38_2024.log)
[debug-Thu_Jul_18_20_15_38_2024.log](https://github.com/user-attachments/files/16297419/debug-Thu_Jul_18_20_15_38_2024.log)
[debug-Thu_Jul_18_20_16_07_2024.log](https://github.com/user-attachments/files/16297423/debug-Thu_Jul_18_20_16_07_2024.log)
[debug-Thu_Jul_18_20_17_09_2024.log](https://github.com/user-attachments/files/16297425/debug-Thu_Jul_18_20_17_09_2024.log)
[debug-Thu_Jul_18_20_20_37_2024.log](https://github.com/user-attachments/files/16297427/debug-Thu_Jul_18_20_20_37_2024.log)
[debug-Thu_Jul_18_20_21_03_2024.log](https://github.com/user-attachments/files/16297430/debug-Thu_Jul_18_20_21_03_2024.log)
[debug-Thu_Jul_18_20_22_37_2024.log](https://github.com/user-attachments/files/16297431/debug-Thu_Jul_18_20_22_37_2024.log)
[debug-Thu_Jul_18_20_24_00_2024.log](https://github.com/user-attachments/files/16297433/debug-Thu_Jul_18_20_24_00_2024.log)
![nrf 1](https://github.com/user-attachments/assets/1574a584-bcf3-4ce3-bbbe-f3971d9c1141)

**Comment by cagnulein** [comment]
thanks, on nrfconnect click on connect on the hr device and show me a screenshot where the hr measurement characteristics is visible. i would like to check if it has on notify or read only

thanks

**Comment by garyness5** [comment]
nrf screenshot. It shows no
![1](https://github.com/user-attachments/assets/e6e1150e-dc89-4e03-ba8b-903e7f5797bf)
tify

**Comment by cagnulein** [comment]
that's so strange everything looks as usual. and if you click on the icon on the right with the 3 arrows that are pointing at the bottom are you getting there the hr measurement?

**Comment by garyness5** [comment]
Yes. 63bpm

![2](https://github.com/user-attachments/assets/9392e7f4-e7f2-4ce9-82ef-9d548dcf78fb)

**Comment by cagnulein** [comment]
ok perfect, now i'm in vacation i will check better the log when i will be back home on monday, thanks and have a nice weekend

**Comment by garyness5** [comment]
Thank you
Enjoy your weekend

**Comment by cagnulein** [comment]
Hi, I was checking for example the 
[debug-Thu_Jul_18_20_21_03_2024.log](https://github.com/user-attachments/files/16297430/debug-Thu_Jul_18_20_21_03_2024.log)

And I see the HR correctly for the whole session. it was updating correctly with 63 and 64 bpm. so it seems that when it's connected it works fine. am i missing something? in other logs qz can't see the device at all: just to clarify: qz search the hr device in a 10 seconds window after seeing your main fitness device. if it doesn't appear in this window, it will ignore it. maybe that's your issue? you weren't turning on in that timeframe?

**Comment by garyness5** [comment]
Hi Roberto
Right now, the sessions are only for testing the HR. The longest session that I left the app open was about 15 minutes. Most of the time closed and restarted it. Always for a few minutes. Of all the 30+ tests I did, the HR was read only once by the app. Only a few times was the monitor picked up in the list of monitors in QZ. Every time, it showed up in nRF.

The time if did read the bpms, I only left it run for a few minutes. In the past, when using the app, the very few times it picked up the monitor, it only read it for a few minutes, and never read it during the rest of the session, which usually ran 60-90 minutes. Also, when testing, to make sure the monitor was working, I checked on Wahoo and Strava, which I deleted right after before using QZ. And the funny part, the only time it did pick up the monitor, was when Strava and Wahoo was running. I had forgotten to turn them off. I tested a few times with the 2 apps running to see if QZ would pick it up, but it never did. Every time nRF had picked up and read the bpms. I never had any problems at the beginning. Then with same app, same monitor, same phone, it just stopped reading the monitor

**Comment by cagnulein** [comment]
It's a mistery. If you want, if you can provide me a longer session when it
lose connection I can check the reason, at least for the connectivity side.

For the broadcast side actually I really can't make anything better, I'm
simply polling the Bluetooth devices around you like any app does.

The only difference between qz and any other apps is the fact that qz
connects to more devices at the same time, this could cause strange effects
on some phones. In this 5 years of bluetooth developments I saw ghosts and
zombies around bluetooth  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 19:15 garyness5 ***@***.***>
ha scritto:

**Comment by garyness5** [comment]
It is not a problem Roberto. I am just surprised this has only happened to me. I don't use any special apps or do anything special on the phone. Let's leave it like that. It is not that important. If ever you think of anything, let me know. Everything else works well. The HR is just a feature I like, but is not important 
THank you for your attention in trying to solve this

Gary

**Comment by cagnulein** [comment]
it could be something special on the hr device.
anyway i'm always open to understand issue, if you will conduct any other
tests with different phones or different hr , i will be here
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 21:38 garyness5 ***@***.***>
ha scritto:
