### ISSUE TITLE
[BUG] No metrics showing on Apex Rides bike

### ISSUE THREAD

**Issue by Stevefsg** [cagnulein/qdomyos-zwift#2459]
**Describe the bug**
QZ app connects to Apex Rides bike but does not show any metrics other than resistance jumping from min to max units 

**Expected behavior**
Expect to see all metrics shown such as calories burned, resistance, odometer etc.

**Screenshots**
![IMG_0199](https://github.com/user-attachments/assets/c372f8ac-bd6f-4c32-8476-c87fadc09b0b)

**Desktop (please complete the following information):**
 Not using Desktop, using on phone only 

**Smartphone (please complete the following information):**
 - OS: IOS 16.6
 - Version: App version 2.15.4

**Append a debug log**
[debug-Wed_Jul_17_20_55_22_2024.log](https://github.com/user-attachments/files/16274616/debug-Wed_Jul_17_20_55_22_2024.log)

**Comment by cagnulein** [comment]
hi, thanks. i will check tomorrow. 11pm here
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 17 lug 2024 alle ore 22:47 Stevefsg ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Hi @Stevefsg when you collected this log were you riding? I can see the connection to the bike, but the bike is sending all 0, except for the resistance that it's changing as you saw.
If you were riding, do you have an app that already works with the bike? just to understand if it's a bike issue or something else.
Thanks

**Comment by Stevefsg** [comment]
Hi
I opened the app, cycled for a few minutes, pressed stop, closed the app
then collected the log.
I don’t currently have an app to use with the bike, I have just bought the
bike second hand and Apex charge £30 a month to use their app that’s why I
bought yours hoping it would work. There is an LED that comes on on the
front of the bike when the app connects

**Comment by cagnulein** [comment]
the apex app works with the bike?

**Comment by Stevefsg** [comment]
Yes that’s correct, the Apex app works with the bike but I am no longer
paying the subscription for it

**Comment by cagnulein** [comment]
ok so it seems that your bike has a different firmware from the one that I implemented in the past. In order to add the compatibility with this exactly firmware version, we need to use an android device, just to collect some logs with the apex app. Are you able to do so?

**Comment by Stevefsg** [comment]
Yes I have an android tablet I can use, although I’m in work till late
today. If you can tell me how to get the logs with the apex app, I can send
them to you later on today

**Comment by cagnulein** [comment]
sure, follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by Stevefsg** [comment]
Hi

sorry for getting back to you late
I think I’ve managed to get the file you need and have attached it 
[btsnoop_hci.log](https://github.com/user-attachments/files/16378620/btsnoop_hci.log)

**Comment by cagnulein** [comment]
hi @Stevefsg it gives me a 404 error. can you please upload it again?

**Comment by Stevefsg** [comment]
No problem, i have tried uploading it through my PC this time rather than my phone
[btsnoop_hci.log](https://github.com/user-attachments/files/16382813/btsnoop_hci.log)

**Comment by cagnulein** [comment]
did you use the apex app with this? i mean the bug report and the apex app are on the same device right? if so do you see the metrics on the apex app? i'm seeing the same behaviour of the qz app, talking with the bike over and over with 0 metrics.
Let me know

**Comment by cagnulein** [comment]
hah no wait i can see something

**Comment by Stevefsg** [comment]
Hi Roberto, that has seemed to fix it! All metrics are showing now, however they seem to be continuously jumping from minimum value to actual value, I have tried to attach a video showing what I mean and a debug log from my android tablet 


https://github.com/user-attachments/assets/e41391ce-be4a-4d9b-b22f-8a4f0ee5b960


[debug-Fri_Jul_26_20_13_06_2024.txt](https://github.com/user-attachments/files/16404716/debug-Fri_Jul_26_20_13_06_2024.txt)

**Comment by cagnulein** [comment]
hi @Stevefsg sort of a good news! can you upload again the debug log? it's corrupted. thanks

**Comment by Stevefsg** [comment]
[debug-Fri_Jul_26_20_13_06_2024.txt](https://github.com/user-attachments/files/16470320/debug-Fri_Jul_26_20_13_06_2024.txt)

**Comment by cagnulein** [comment]
@Stevefsg fixed https://github.com/cagnulein/qdomyos-zwift/actions/runs/10215453679

**Comment by Stevefsg** [comment]
Thank! I really appreciate you fixing these issues for me. Will these fixes
be available on the IOS version in the future?

**Comment by cagnulein** [comment]
yes sure, if you want I can build it for ios already
Let me know

**Comment by Stevefsg** [comment]
Hi Roberto, 
I uninstalled the previous trial app and installed  tested the new one you made for me last night but unfortunately I am getting the same issue now that I originally had, no metrics are showing at all (apart from Resistance)

[debug-Fri_Aug_2_18_55_34_2024.log](https://github.com/user-attachments/files/16479000/debug-Fri_Aug_2_18_55_34_2024.log)

**Comment by cagnulein** [comment]
ops sorry, i did it wrong. i will fix it tomorrow. i'm outside now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 ago 2024 alle 11:55 Stevefsg ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok i see now the reason: the bike seems with this new firmware doesn't send the cadence anymore. it sends only the distance so i have to derive it. i will try a new version later today

**Comment by cagnulein** [comment]
ok i did a new approach https://github.com/cagnulein/qdomyos-zwift/actions/runs/10244696576

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/10245989277

**Comment by cagnulein** [comment]
new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/10253051728

**Comment by cagnulein** [comment]
@Stevefsg are we OK?

**Comment by El-Reina** [comment]
Did this issue get resolved? 
Am wanting to use the app with my apex rides bike but on IOS and no access to Android device. Don’t want to purchase and then it doesn’t work.

**Comment by cagnulein** [comment]
@El-Reina As far as I know yes, @Stevefsg could you please confirm?

**Comment by cagnulein** [comment]
![Image](https://github.com/user-attachments/assets/b99165f4-2106-403a-9064-fb9f3332be3e)
