### ISSUE TITLE
[BUG] Echelon Connect EX-7 Bike Metrics Not Working

### ISSUE THREAD

**Issue by PavloKr** [cagnulein/qdomyos-zwift#2460]
**Describe the bug**
Tiles are visible but metrics do not change.

**To Reproduce**
1. Started Apple Watch App, waited for heart rate to appear
2. Started peddling on bike
3. Opened qdomyos app on iPhone 15
4. Opened zwift on iPhone Xs Max (also tried on iPad Pro, same result)
5. iPhone 15 qdomyos app does not show any changes in metrics. Biker not moving in zwift

**Expected behavior**
I expected the values to move when I started peddling on the bike. I am not sure the app is even connected to the bike (yet tiles are visible).

**Screenshots**
![IMG_0107](https://github.com/user-attachments/assets/cc5f261d-3e76-4bd0-b25f-c51268aa7c3b)
![IMG_1484](https://github.com/user-attachments/assets/dd159db6-8b26-4fdd-bb92-c7a1f0552e96)
![IMG_1485](https://github.com/user-attachments/assets/091d9263-c448-47b8-b060-97943dfb6039)
![IMG_0108](https://github.com/user-attachments/assets/a0dd2d99-9427-4d05-baf7-58c84eff44a8)

[debug-Thu_Jul_18_06_15_28_2024.log](https://github.com/user-attachments/files/16298652/debug-Thu_Jul_18_06_15_28_2024.log)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.5
 - Version: Newest version, just downloaded from app store yesterday.

- Zwift ran on both iPhone Xs Max iOS 16.7 and iPad Pro iPad OS 16

**Append a debug log**

[debug-Thu_Jul_18_06_15_28_2024.log](https://github.com/user-attachments/files/16299150/debug-Thu_Jul_18_06_15_28_2024.log)

  
  
**Additional context**
All settings are on default. I originally followed the guide, and got same result. Deleted app, restarted phone, reinstalled app. Tried all combinations of restarting bike, both phones, even tried using an iPad. Tried tapping start, pause, etc. I've tried all common sense fixes (at least so I think) but I'm just not convinced its connected to the bike (even though it shows it is). Really appreciate any help and direction!

I have tried connecting to both the Wahoo bluetooth, and also the iPhone 15 named Pavlo. At this point I don't even care about Zwift, I have echelon but I just want to access the stats.

**Comment by cagnulein** [comment]
hi, the app is connected to another device not the echelon. use the manual device setting in the advanced settings to force to connect to it

let me know

**Comment by PavloKr** [comment]
> hi, the app is connected to another device not the echelon. use the manual device setting in the advanced settings to force to connect to it
> 
> let me know

Hi, Still no luck. It seems that the only bluetooth device that even shows the metrics tiles the one with "Console" in the name. Here is the debug logs and bluetooth device names I have tried:

[
![IMG_0113](https://github.com/user-attachments/assets/c7a84209-bf4e-4ffb-8443-efff5f55631a)
![IMG_0112](https://github.com/user-attachments/assets/ce2c7b85-5b84-4512-a12e-996cbdd6e406)
[debug-Sun_Jul_21_13_47_26_2024.log](https://github.com/user-attachments/files/16336925/debug-Sun_Jul_21_13_47_26_2024.log)
[debug-Sun_Jul_21_13_47_11_2024.log](https://github.com/user-attachments/files/16336926/debug-Sun_Jul_21_13_47_11_2024.log)
[debug-Sun_Jul_21_13_46_02_2024.log](https://github.com/user-attachments/files/16336927/debug-Sun_Jul_21_13_46_02_2024.log)
[debug-Sun_Jul_21_13_44_19_2024.log](https://github.com/user-attachments/files/16336928/debug-Sun_Jul_21_13_44_19_2024.log)
](url)

**Comment by cagnulein** [comment]
are you able to use the echelon app from your phone? if not, do you have a LCD screen builtin on the bike? if so you have to completely turn off with the rear button, then the light on the bike should flash. then you should be available in QZ
Let me know

**Comment by PavloKr** [comment]
> are you able to use the echelon app from your phone? if not, do you have a LCD screen builtin on the bike? if so you have to completely turn off with the rear button, then the light on the bike should flash. then you should be available in QZ Let me know

You are the best, it worked! Thank you so much.

**Comment by cagnulein** [comment]
that's great! remember to rate the app on the store, it means a lot to me! thanks!
