### ISSUE TITLE
ProForm Carbon T7 connection issue

### ISSUE THREAD

**Issue by FurlongFX** [cagnulein/qdomyos-zwift#2461]
I have a ProForm Carbon T7, and I've been able to install the companion app, however, can't successfully get metrics. The only way I was able to get the tile view on the OZ app was to manually input the tread IP in the settings, however, there's no option for the model that I'm specifying on the companion app. 

I tried uninstalling, then reinstalling the companion app via the ADB bat file. This is the log:

Pinging 192.168.0.176 ... 

Pinging 192.168.0.176 with 32 bytes of data:
Reply from 192.168.0.176: bytes=32 time=106ms TTL=64

Ping statistics for 192.168.0.176:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 106ms, Maximum = 106ms, Average = 106ms
 
Connecting to treadmill via ADB ... 
 
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 192.168.0.176:5555
 
List of devices attached
192.168.0.176:5555     device product:argon model:MalataMediatekArgon1 device:argon transport_id:1

Android version: 
SDK version: 
 
Checking for previous installation ... 
 
QZ Companion not installed 
 
Installing QZ Companion ... 
 
Performing Push Install
adb: error: failed to get feature set: more than one device/emulator
 
Launching QZ Companion ... 
 
adb.exe: more than one device/emulator
 
Launching iFit ... 
 
adb.exe: more than one device/emulator
 
Rebooting treadmill ...

**Comment by cagnulein** [comment]
companion is installed now? you can put the companion apk directly on the tablet downloading it from the browser of the treadmill

**Comment by FurlongFX** [comment]
I installed it from the browser, it was the only way I could do it successfully. Just can't successfully connect through the OZ phone app

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
ok so share a debug log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
and I will check your scenario

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 19 lug 2024 alle 07:35 FurlongFX ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
#2474
