### ISSUE TITLE
[BUG] No cadence from Kettler Ecorun XS

### ISSUE THREAD

**Issue by Weiimyway9** [cagnulein/qdomyos-zwift#2462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[Uploading debug-Sat_Jul_20_12_16_07_2024.log…]()

**Additional context**

**Comment by cagnulein** [comment]
hi @Weiimyway9 you have to wait the finish of the upload before pushing comment, the log is corrupted. could you please upload it again?

**Comment by Weiimyway9** [comment]
Here is I upload again. Please check
[debug-Sat_Jul_20_12_16_07_2024.log](https://github.com/user-attachments/files/16319255/debug-Sat_Jul_20_12_16_07_2024.log)

**Comment by cagnulein** [comment]
checked , it seems doesn't stream cadence and step count neither. did it
send cadence with any other apps?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 lug 2024 alle 09:52 Weiimyway9 ***@***.***>
ha scritto:

**Comment by Weiimyway9** [comment]
Yes neither step counter record. I haven’t try connect it with other app, will try to connect with kinomap later and get back to you

**Comment by cagnulein** [comment]
ok let me know

**Comment by Weiimyway9** [comment]
Already check data from kinomap, its the same, no cadence and step count too.

**Comment by cagnulein** [comment]
yeah so it's a limitation of the treadmill itself. in this case with a
garmin or apple watch you can get the cadence using the qz companion app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 20 lug 2024 alle 19:09 Weiimyway9 ***@***.***>
ha scritto:
