### ISSUE TITLE
[BUG] cadence broken for zwift in beta  2.16.66 - Android

### ISSUE THREAD

**Issue by brianjvolz** [cagnulein/qdomyos-zwift#2463]
**Describe the bug**
I upgraded the beta to  2.16.66 - Android and my Cadence was lower mid 80s and jumpy coming from zwift pod. This worked in previous builds 

**To Reproduce**

error:
Average Pace: 9:34
Max Pace: 6:58
Average Cadence: 98
Max Cadence: 162

QZ version: 2.16.66 - Android
Device: HORIZON_7.0AT 688B
HR Device: H6M 19537

**Expected behavior**
This worked in this build:

Average Pace: 9:46
Max Pace: 9:22
Average Cadence: 151
Max Cadence: 160

QZ version: 2.16.61 - Android
Device: HORIZON_7.0AT 688B
HR Device: H6M 19537

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @brianjvolz you need to attach a debug log to show me issue. thanks

**Comment by brianjvolz** [comment]
Replaced batteries on zwift runpod and issue is resolved. Closing ticket

**Comment by cagnulein** [comment]
glad to hear it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 28 lug 2024 alle 17:14 brianjvolz ***@***.***>
ha scritto:
