### ISSUE TITLE
[BUG] no data from X22i to QZ

### ISSUE THREAD

**Issue by Haaland35** [cagnulein/qdomyos-zwift#2466]
**Describe the bug**
QZ installed was via method 2. QZ is running the the background and manual mode with sliders running in the foreground. QZ app on iOS device shows metric steady at zero with no change. Virtual wahoo device and QZ can be discovered inside of zwift.

**To Reproduce**
3. Scroll down to '....’

**Expected behavior**
With QZ open on iOS device, expect to see metrics transmitted from NT s22i after manual mode has started.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11 home

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 16.6.1
 - Version 20G81 
 - 
 
[debug-Sun_Jul_21_11_08_42_2024.log](https://github.com/user-attachments/files/16325662/debug-Sun_Jul_21_11_08_42_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok the issue seems that the companion can't parse the metrics from the tablet. try to set the x22i device on the companion and restart the whole bike

let me know if it's better and in case it's  not send me a newer debug log

thanks

**Comment by Haaland35** [comment]
I set the tablet to s22i then reset. I had the same results, the log is attached.
[debug-Sun_Jul_21_11_42_59_2024.log](https://github.com/user-attachments/files/16325720/debug-Sun_Jul_21_11_42_59_2024.log)
  
  

the setting on my iOS device for the bike are shown in the attached picture. I do not see a s22i option.
![IMG_5160](https://github.com/user-attachments/assets/06e9b554-bf74-4cb2-9e0e-144fc6208f11)

**Comment by cagnulein** [comment]
i said X22i not S22i
it's not a mistake, this setting trigger a different parser engine (there are many different on qz companion)

let me know

**Comment by Haaland35** [comment]
Tablet set to X22i, no change.
[debug-Sun_Jul_21_12_02_42_2024.log](https://github.com/user-attachments/files/16325762/debug-Sun_Jul_21_12_02_42_2024.log)

**Comment by cagnulein** [comment]
now i can see cadence and wattage in the log. don't you? did you try to a
quick session?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 21:05 Haaland35 ***@***.***>
ha scritto:

**Comment by Haaland35** [comment]
I tried reset the bike again, I did a short 60 second sessions. I do not see the cadence or wattage anywhere except the manual mode screen of the tablet. 

attached is the log.
[debug-Sun_Jul_21_12_18_41_2024.log](https://github.com/user-attachments/files/16325799/debug-Sun_Jul_21_12_18_41_2024.log)

**Comment by cagnulein** [comment]
ok got it, it's reading them , but always the same value over and over.

ok next test: use the 7.5s device in the companion and restart the bike

we have to find the right engine for your bike

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 21:25 Haaland35 ***@***.***>
ha scritto:

**Comment by Haaland35** [comment]
Switched to the 7.5s and restarted. I did a minute run again. I did not see cadence or wattage displayed anywhere but the manual mode screen again. 

attached is the log from 7.5s
[debug-Sun_Jul_21_12_36_45_2024.log](https://github.com/user-attachments/files/16325835/debug-Sun_Jul_21_12_36_45_2024.log)

**Comment by cagnulein** [comment]
ok this is worse, i don't see anything at all.
ok so you said that adb doesn't work, right?
so we have to find a  way to enable it or at least trying to get the logs
inside the .wolflogs directory on the tablet. are you able to install a
file browser there?



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 21:44 Haaland35 ***@***.***>
ha scritto:

**Comment by Haaland35** [comment]
I will continue to switch engines and report back, thank you for your help.

**Comment by cagnulein** [comment]
ok the main 3 are the ones that we already tried. that's why i asked about the logs in the folder to understand better your tablet

**Comment by Haaland35** [comment]
Unfortunately the attempt to install a file explorer have been unsuccessful. I tried a few different apk, all have failed to download properly. I’m not sure of any other options.

**Comment by cagnulein** [comment]
Did you try cx file Explorer?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 21 lug 2024 alle 23:01 Haaland35 ***@***.***>
ha scritto:

**Comment by Haaland35** [comment]
I apologize for the delay. I tried CX file explorer and other apk that were compatible with android 5.0. They all failed to download correctly and could not be installed.

**Comment by cagnulein** [comment]
@Haaland35 which error did you get about the installation of cx file explorer? @victorypoint do you have any hints?

**Comment by cagnulein** [comment]
also @Haaland35 you can ask in these tickets to other x22i owners how they did to get QZ https://github.com/search?q=repo%3Acagnulein%2Fqdomyos-zwift+x22i&type=issues

**Comment by Haaland35** [comment]
The error I received was “ Unsuccessful download” in the downloads app. I tried multiple times and versions of the apk. I have a wahoo kickr to use with zwift. I just wanted to make my NT more useful to me as a dedicated trainer. My treadmill has android 7 I will try to use QZ on that. Thank you very much for your assistance and the support of your software!

**Comment by cagnulein** [comment]
hah wait @Haaland35 try last thing

remove the ip from your current setting (don't leave space on it and press ok)

and instead put it here

![image](https://github.com/user-attachments/assets/a7d45068-a40e-44b7-8fc7-8dbf8b1de362)

press ok and restart qz

let me know !

**Comment by Haaland35** [comment]
I do not see that option in the drop down.
![IMG_5170](https://github.com/user-attachments/assets/c4e7da17-ae70-4ef8-b55a-a52a28494fd0)

**Comment by Haaland35** [comment]
I saw no change after deleting the ip from the bike options and placing it under the treadmill ip. I also switched the tablet from 7.5s,x22i, and s22i. Logs are attached.

7.5s
[debug-Tue_Jul_23_15_41_45_2024.log](https://github.com/user-attachments/files/16355043/debug-Tue_Jul_23_15_41_45_2024.log)

x22i
[debug-Tue_Jul_23_15_50_06_2024.log](https://github.com/user-attachments/files/16355047/debug-Tue_Jul_23_15_50_06_2024.log)


S22i
[debug-Tue_Jul_23_15_57_58_2024.log](https://github.com/user-attachments/files/16355048/debug-Tue_Jul_23_15_57_58_2024.log)

**Comment by victorypoint** [comment]
> @Haaland35 which error did you get about the installation of cx file explorer? @victorypoint do you have any hints?

I suspect the app may be too big for the available storage. You could try FV File Explorer which is a bit smaller if I recall.

**Comment by cagnulein** [comment]
@Haaland35 you put the ip in the wrong setting! not the tdf companion ip, check my above screenshot! it's under the treadmill settings, nordictrack treadmill. be sure to remove the ip from the one that you fill now

**Comment by cagnulein** [comment]
@Haaland35 any news?
