### ISSUE TITLE
[BUG] zwift play controllers not controlling virtual shifting 

### ISSUE THREAD

**Issue by jontnswift** [cagnulein/qdomyos-zwift#2468]
**Describe the bug**
Zwift play controller is not controlling virtual shifting 

**To Reproduce**
Open app
Start pedalliing trainer and wait for Suito Found
Start play controllers and wait for leds to turn blue
Start zwift and navigate to pairing screen 
Pair to virtual Wahoo Kickr on resistance, power and cadence. 
Ensure play controllers are not selected in zwift. 
Select route and start pedaling 
Power and cadence in zwift match qz numbers
Trying to shift using side buttons in zwift doesn't do anything. 

**Expected behavior**
Side buttons should control shifting 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Smartphone (please complete the following information):**
 - Device: samsung s24+
 - OS: android 
 - Version 14
[debug-Sun_Jul_21_00_18_51_2024.log](https://github.com/user-attachments/files/16326372/debug-Sun_Jul_21_00_18_51_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
I quickly check it and the main issue is that the zwift play is not
broadcasting themselves

Follow this path:
1) power on your trainer
2) wake up both controller
3) turn on qz
4) you have to see the trainer and the play quickly showing in the top
label in qz

I guess in your current scenario they are still connected to something else

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 22 lug 2024 alle 01:21 jontnswift ***@***.***>
ha scritto:

**Comment by jontnswift** [comment]
That worked.  Thanks so much!

**Comment by cagnulein** [comment]
Awesome, thanks for the update!
Remember to rate the app on the store, it means a lot to me
Thanks!

Il giorno lun 22 lug 2024 alle 03:11 jontnswift ***@***.***>
ha scritto:
