### ISSUE TITLE
[BUG] Virtual shifting lags

### ISSUE THREAD

**Issue by jontnswift** [cagnulein/qdomyos-zwift#2470]
**Describe the bug**
Resistance does not change quickly after shifting, sometimes resulting in overshifting

**To Reproduce**
upshift and increase power
resistance does not increase so I shifted again, several times
suddenly resistance catches up causing my cadence to grind down
downshifting takes several seconds to adjust as well

**Expected behavior**
Shifting should result in immediate or nearly immediate changes to resistance

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 22H2

**Smartphone (please complete the following information):**
 - Device: Samsung S24+
 - OS: Android
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
I tried both race mode and a direct ethernet connection to the phone.  Neither helped.

[debug-Mon_Jul_22_23_00_29_2024.zip](https://github.com/user-attachments/files/16343468/debug-Mon_Jul_22_23_00_29_2024.zip)

**Comment by cagnulein** [comment]
thanks i will check it later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 23 lug 2024 alle 05:48 jontnswift ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok same of this https://github.com/cagnulein/qdomyos-zwift/issues/2153
i'm applying the same patch
I will send you a new one today @jontnswift  !

**Comment by cagnulein** [comment]
done @jontnswift 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/10055228682
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by jontnswift** [comment]
I have the version from github installed and will test it this evening

**Comment by cagnulein** [comment]
perfect! let me know!

**Comment by jontnswift** [comment]
Attaching 2 new logs. The new build seems better.  Race mode with the new build seems worse. The lag is intermittent, not all the time, and it seems to get worse when I shift several gears quickly.

**Comment by jontnswift** [comment]
[QZdebuglogs.zip](https://github.com/user-attachments/files/16356212/QZdebuglogs.zip)

**Comment by cagnulein** [comment]
ok i guess i found the reason

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10071021979

can you try this?
thanks

**Comment by jontnswift** [comment]
I will take try it tomorrow after work.  Thanks again.

**Comment by jontnswift** [comment]
That made a huge difference!  The delay is now approximately the same as the change in resistance on my trainer when the incline changes on zwift  (~1 second).   I can upload a new log if you'd like, but I think we are good at this point.

**Comment by cagnulein** [comment]
Amazing! In case we can also lower the 200ms if you want, but this impact also on the battery of your qz device

**Comment by cagnulein** [comment]
@jontnswift did you send me an email to roberto.viola83 at gmail.com for the private beta?

**Comment by jontnswift** [comment]
I haven't.  Just the exchange about the problem with delayed shifting.  You
did give me a separate build for that but I wasn't sure if that added me to
the beta or not.

**Comment by cagnulein** [comment]
yes it's in the master branch!

**Comment by cagnulein** [comment]
for this you can simply click here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

**Comment by jontnswift** [comment]
Do I need to revert from the nightly build to the play store build in order
to get the beta version then?

**Comment by cagnulein** [comment]
yes :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle ore 20:18 jontnswift <
***@***.***> ha scritto:

> Do I need to revert from the nightly build to the play store build in
> order
> to get the beta version then?
>

**Comment by jontnswift** [comment]
Thanks! Now I just have to figure out how to export my settings.  :-)

**Comment by cagnulein** [comment]
save it from qz in the settings page using the top icons. then backup the
file somewhere safe out from the qz folder. then you will import them using
the opposite icon

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle ore 20:21 jontnswift <
***@***.***> ha scritto:

> Thanks! Now I just have to figure out how to export my settings. :-)
>

**Comment by jontnswift** [comment]
Thanks again!
