### ISSUE TITLE
[BUG] Using QZ to change Gears on JetBlack Volt stops randomly 

### ISSUE THREAD

**Issue by Curt0x** [cagnulein/qdomyos-zwift#2471]
**Describe the bug**
Occasionally in the middle of a ride when I'm using QZ to change Gears/resistance on my JetBlack Volt during a Zwift ride, it appears to stop working since my resistance no longer changes in game. QZ is still running and Zwift still shows its paired under Resistance. But changing gears stops having any effect. I've also seen it simply take 30 seconds or more to change, while other times it simply stops working completely. 

**To Reproduce**
1. Pair QZ as the Resistance in Zwift
2. Begin ride as normal
3. Some random amount of time later, shifting makes no difference anymore. QZ still shows gears changing as I press up or down on Volume, but nothing changes in Zwift. 

**Expected behavior**
Most of the time I'm able to pair QZ as my Resistance in Zwift and go about my ride able to "shift" with volume buttons, as intended. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 -  latest Windows update 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Fold4 
 - OS: Android
 - Version Android 14, latest July 1st security patch

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
[inbound4371711337620921021.zip](https://github.com/user-attachments/files/16343657/inbound4371711337620921021.zip)

  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks, i will check later today

**Comment by cagnulein** [comment]
hi @Curt0x you attached the fit file, i need the debug log file to understand it.
let me know!

**Comment by cagnulein** [comment]
ok thanks, attach it there when you will have it

**Comment by cagnulein** [comment]
yes indeed zwift stop to sending new inclination requests. Did you try to use the wahoo virtual device in zwift from qz instead of the phone name? it could be a bluetooth issue on the qz device.
also was qz always on foreground?

**Comment by Curt0x** [comment]
I will try using the Wahoo virtual device on my next ride and report back.
Yes QZ was always foreground. I'll let you know. Thanks

**Comment by cagnulein** [comment]
@Curt0x any news?
