### ISSUE TITLE
Home fitness buddy incompatibility?

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2472]
https://cloud.luanzi.de/s/pdmBATCA9a59APB

**Comment by cagnulein** [comment]
i need this file Peloton-907-BenAlldis-20230806-PZE-30.zwo.xml

**Comment by Luzl1** [comment]
[Peloton-907-BenAlldis-20230806-PZE-30.zwo.zip](https://github.com/user-attachments/files/16346558/Peloton-907-BenAlldis-20230806-PZE-30.zwo.zip)

**Comment by cagnulein** [comment]
@Luzl1 i guess i got the issue. The file itself it's right and I can open it. Due to new Android security policy, you can't move the file inside the qz folder from a file browser. Is it what you did? If so do this
- remove the file from the actual location
- open qz and go to the training program side bar option and click on "other folder" on the bottom
- select the file from your phone (not in the qz directory)
- try it

I guess in this way will work.
Let me know!

**Comment by cagnulein** [comment]
do you have a debug log of these tests?

**Comment by Luzl1** [comment]
Unfortunatley not. 
I will provide them. Today I have no time, I hope I get to it tomorrow.

**Comment by cagnulein** [comment]
ok no rush. i will do also a test on my own

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 lug 2024 alle 16:16 Luzl1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I'm able to reproduce myself. Hold on

**Comment by cagnulein** [comment]
![debug-Wed_Jul_24_19_47_41_2024.log.zip](https://github.com/user-attachments/files/16365863/debug-Wed_Jul_24_19_47_41_2024.log.zip)

**Comment by cagnulein** [comment]
fixed!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10082986137

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Luzl1** [comment]
I did a 10 min test and it worked \o/
Great work.
