### ISSUE TITLE
[BUG] Life Fitness T5 no stats showing

### ISSUE THREAD

**Issue by jh484** [cagnulein/qdomyos-zwift#2476]
**Describe the bug**
Life fitness T5 treadmill connects but no data is showing in any of the widgets.

**Screenshots**
![Screenshot_2024-07-23-22-29-26-223_org.cagnulen.qdomyoszwift.jpg](https://github.com/user-attachments/assets/a3f3ea17-9ab5-4aa2-b549-c7749d9b82a4)

**Smartphone (please complete the following information):**
 - Device: POCO F3
 - OS: 1.0.1.0 TKHEUXM
 - Version Android version 13

**Append a debug log**
https://drive.google.com/file/d/1vwZSOaejlVOzGM6XbAtwYLlv8RYY71Ml/view?usp=drivesdk

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
Hi Log checked, could you please enable the setting "GEM Module Options,
Inclination" under the treadmill settings and restart QZ?
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 23 lug 2024 alle ore 23:55 James ***@***.***>
ha scritto:

**Comment by jh484** [comment]
Hi Roberto, this seems to have fixed it. Thanks very much! James

**Comment by cagnulein** [comment]
that's great to hear this!
