### ISSUE TITLE
[BUG] Not collecting data from Bowflex IC SE bike

### ISSUE THREAD

**Issue by devleu** [cagnulein/qdomyos-zwift#2477]
**Describe the bug**
QZ connects to ICSE via Bluetooth. All tiles showing 0.0. Using the bike does not generate data in the app. Stopping the activity generates a report with zero data.

**To Reproduce**
1. Open QZ app
2. Wait for connectiong to ICSE
3. Click Start
4. Pedal bike

**Expected behavior**
Expected some data to show on the app.

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 
 - Version 14

**Append a debug log**
[debug-Tue_Jul_23_20_54_46_2024.log](https://github.com/user-attachments/files/16355838/debug-Tue_Jul_23_20_54_46_2024.log)

**Comment by cagnulein** [comment]
Log checked. Can you please enable the "Hammer Racer Bike Options" setting
under the bike settings and try again?
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 lug 2024 alle ore 03:11 devleu ***@***.***>
ha scritto:

**Comment by devleu** [comment]
Enabling the Hammer setting worked. The app is collecting data from the bike now.

Curiously, the bike screen no longer shows data when connected. It used to continue to show Cadence and resistance numbers when an exercise app was connected.

Not a big deal, but was convenient to look at while using another training app.

**Comment by cagnulein** [comment]
which was the app that keeps the console enabled on your bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 lug 2024 alle 14:20 devleu ***@***.***> ha
scritto:

**Comment by devleu** [comment]
I use the Peloton app to connect and get this screen with stats.
![ICSE_Stats](https://github.com/user-attachments/assets/048e5e3b-94ee-46c2-85ba-9f5289a0d434)

When QZ connects, I just get this.

![ICSE_NoStats](https://github.com/user-attachments/assets/0ec2d16a-7cc6-4a84-8785-528f6e6bf499)

**Comment by cagnulein** [comment]
the difference is that peloton connect only for reading, QZ instead it also can write values.
Try to force the resistance from qz, changing the resistance on the resistance tile. Does the display changes?

**Comment by devleu** [comment]
No.

The resistance number on the tile doesn't change.
There's no change on the bike display.

**Comment by cagnulein** [comment]
ok do you see in qz wattage and cadence? if so this is how the bike works in ftms (standard). Instead peloton shows only the cadence from your bike, right?

**Comment by devleu** [comment]
Yes, QZ shows Speed, cadence, odometer and wattage.

**Comment by cagnulein** [comment]
ok so this how your bike works :)
If you can find another app, example kinomap, that can show all the information (wattage is the most important) showing also the console on the bike we can study it
Let me know!

**Comment by devleu** [comment]
Ok, thank you.

I'll keep that in mind.

At least now I can get data out of the bike that I couldn't before.
