### ISSUE TITLE
[BUG] domyos bike, display multiplied * 10

### ISSUE THREAD

**Issue by Strangistra** [cagnulein/qdomyos-zwift#248]
**Describe the bug**
Bonjour. Je viens de tester Qdomyos prennant les données du vélo Domyos 500 et les transférants à mon PC Windows sur Zwift. Cela fonctionne correctement hormis la prise du rythme cardiaque. Ce dernier n'est pas actif sur l'application Qdomyos malgré le fait d'activer le vélo en prise de rythme cardiaque. Ce défaut a-t-il déjà été remonté ? 

J'ai constaté un autre défaut. Lorsque l'application Qdomyos est connectée au vélo,  les informations de l'applications semble bonnes mais les informations sur l'affichage du vélo sont totalement fausses. 

**Expected behavior**
Pouvoir visualiser le rythme cardiaque avec les capteurs du vélo Domyos 500 dans l'application Qdomyos pour par la suite pouvoir les visualiser sur les applications de vélo. 

Assurer la synchronisation des informations entre Qdomyos et le vélo Domyos 500.

**Comment by cagnulein** [comment]
For the display issue, toggle the distance settings on the settings page.

For the Heart rate, is the heart rate belt setting set to disabled? Are you
on Android or iOS? Do you have an Apple watch too?

Please write in English, this is an international group (I'm italian ;))
Thanks
R

Il dom 4 apr 2021, 11:39 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
So sorry. I will write in english now.  

For the  heart rate I don't have Apple watch or heart rate belt. I have on the Domyos e-bike 500 heart rate captor in  handlebar bike.

My phone is a Redmi9 in Android system.

**Comment by cagnulein** [comment]
Ok i will check it and i Will let you know
Thanks

Il dom 4 apr 2021, 12:08 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
Sorry it's my fault. I don't used the correct parameter in setting for the heart rate parameter. This point working fine finally.  

But for the display issue in fact you don't have the seperator point indicator visible on the e-bike screen.

For exemple in Qdomyos Speed widget you have 19.7 km/h and on the e-bike screen you have 197 km/h. 

This behavior is the same for the Speed,  calories and cadence e-bike widget

**Comment by cagnulein** [comment]
It's strange, i guess you have a different firmware on your bike. Could you
please send me the debug log?

Il dom 4 apr 2021, 12:54 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
[bugreport-2021-04-04-165634.zip](https://github.com/cagnulein/qdomyos-zwift/files/6254800/bugreport-2021-04-04-165634.zip)

Please find the bug report. I hope it's good to your analyse.

Best regards Strangistra

**Comment by cagnulein** [comment]
@Strangistra could you please send me the log that qdomyos generated? you have to enable the debug setting and than, restart the app, connect to your bike, and you will find the log on the download folder on android or the files app on iOS.
thanks

**Comment by Strangistra** [comment]
I don't arrived to generate the "btsnoop_hci.log" with my Xiaomi Redmi 9. 

I'm in developer mode, I active the Bluetooth HCI snoop log option, I active the bluetooth, I launch the Qdomyos application, the application connects to the e-bike domyos 500, I disconect the Qdomyos application, after I disconect the bluetooth and to finish the Bluetooth HCI snoop log option.

But after this I don't have the "btsnoop_hci.log" on the root of my SD card or in my Download folder. I can create the global bug report but I don't know if you have the correct informations in this Zip file?

I continue my search because I'm not a developper and I don't know where is the  "btsnoop_hci.log" file if this file is generated.

**Comment by cagnulein** [comment]
No i don't need the bluetooth hci snoof, just the log generated from
qdomyos itself!

Il dom 4 apr 2021, 21:36 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
Aaahhhh. In this case what is the process to generate there log ? The global report is good? Or you need another report?

**Comment by cagnulein** [comment]
No, just enable the debug log setting in qdomyos itself. On the bottom of
the settings page.
Than restart the app.
Do a little ride
Goto in the download folder and you will find a log called debug-datetime

Il dom 4 apr 2021, 21:55 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
OK, I do this

**Comment by Strangistra** [comment]
I have a generated file but it's not debug-datatime file.
[debug-Sun Apr 4 22_09_13 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6255285/debug-Sun.Apr.4.22_09_13.2021.log)

**Comment by cagnulein** [comment]
Yeah it's the one, date time i mean timestamp :D
Tomorrow i will check it. Thanks

Il dom 4 apr 2021, 22:21 Strangistra ***@***.***> ha scritto:

**Comment by Strangistra** [comment]
OK thank you very much for your time and your help. Good night. Best regards Strangistra

**Comment by cagnulein** [comment]
@Strangistra only the speed is affected by this multiplier or even the cadence and the calories widget on the bike console?

**Comment by Strangistra** [comment]
No only Speed is affected by this issue but also the cadence and the calorie.

**Comment by cagnulein** [comment]
@Strangistra sorry i don't get your phrase. only speed or all 3 metrics?

**Comment by Strangistra** [comment]
All 3 widgets are impacted.   The cadence, calories and Speed widget on bike don't have the point seperator where Qdomyos connected

**Comment by cagnulein** [comment]
ok it's strange because i needed to add a *10 multiplier for the others
users in order to have it correctly, so i guess i will add a parameter in
order to disable/enable this multiplier ;)
R.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 5 apr 2021 alle ore 12:37 Strangistra <
***@***.***> ha scritto:

**Comment by yambel** [comment]
I have a question @Strangistra, how did you manage to get the heart data from the bike working in zwift?
What parameters did you check? I have tried all the options and it is the only parameter that i couldn't get working with my domyos bike 500.

Thank you in advance,

**Comment by Strangistra** [comment]
Hello Yambel. I have effectivelly the same issue in Zwift. I don't have the heart data in Zwift but I have this heart informations correctlly synchronised between  the bike and Qdomyos.

Best regards Strangistra

**Comment by yambel** [comment]
Ok, thank you for your answer @Strangistra.
@cagnulein do you know if it is possible to get that working?

By activating virtual heart only i managed to get the heart data recognized in swift (with value of 0, but at least i got a bluetooth connection) but unfortunately, the rest couldn't work (speed, cadence,..).
I tried all the options possible but, with everything else, the heart data was the only thing that i couldn't get working.

Thank you,

**Comment by cagnulein** [comment]
Is a limitation of android 10 or higher.
You should ios or a phone with a android < 10

**Comment by yambel** [comment]
Ok, it's a shame, thank for the quick answer.

**Comment by jerlam06** [comment]
I have exactly the same issue with the x10 multiplier for RPM and calories (maybe also for speed, cannot remember).
Additionnaly, when I sync Qdomyios app with my bike, BPM is no more displayed on my bike and app.

**Comment by cagnulein** [comment]
> I have exactly the same issue with the x10 multiplier for RPM and calories (maybe also for speed, cannot remember).
> Additionnaly, when I sync Qdomyios app with my bike, BPM is no more displayed on my bike and app.

yeah i need to fix this one.
If you want, you can help me on this! are you a coder?

**Comment by jerlam06** [comment]
Yep I am a frontend developer mainly, but I don't really know C++, but it would me my pleasure to help.

**Comment by cagnulein** [comment]
@jerlam06 this should be ok now https://github.com/cagnulein/qdomyos-zwift/issues/481
feel free to reopen this
