### ISSUE TITLE
NoblePro E8i not receiving data

### ISSUE THREAD

**Issue by Middy2000** [cagnulein/qdomyos-zwift#2481]
Roberto,

Here is a debug log.

QZ is connecting but not receiving any data.  I have talked the user through the settings but may have missed one. 

[debug-Wed_Jul_24_21_37_34_2024.log.txt](https://github.com/user-attachments/files/16367536/debug-Wed_Jul_24_21_37_34_2024.log.txt)

**Comment by cagnulein** [comment]
in this log unfortunately the phone is not connected at all to the
treadmill.
i need one where the treadmill is connected and the user see the tiles
maybe he has another debug log there

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 lug 2024 alle ore 23:11 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Ok.

Tomorrow I will get him to create a new log.

**Comment by cagnulein** [comment]
Ok, thanks.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 24 lug 2024 alle ore 23:24 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Another log to analyze.  qZ installed on 2nd phone but same issue. Connects but doesn't receive data
[debug-Thu_Jul_25_21_04_45_2024.log.txt](https://github.com/user-attachments/files/16383402/debug-Thu_Jul_25_21_04_45_2024.log.txt)

**Comment by cagnulein** [comment]
set the ftms treadmill setting in the treadmill settings to the noblepro
and restart qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 lug 2024 alle ore 22:24 Middy2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
can we close this so @Middy2000  ?

**Comment by Middy2000** [comment]
Yes. 100%

User error.
