### ISSUE TITLE
[BUG] Help with Merach S09

### ISSUE THREAD

**Issue by cstack89** [cagnulein/qdomyos-zwift#2482]
Hello,

I'm pretty new to home indoor cycling, so forgive me if these questions are obvious.  Or send me to the MyWhoosh forum.

Based on some past tickets here I went ahead and bought a Merach S09 as it seemed like you got it working (or were close to getting it working).

I'm trying to run the QZ app on Android and I'm trying to use MyWhoosh on Windows.  I do not (yet) have a heart rate sensor.

I was able to connect the QZ app to the bike, and my phone to Windows/MyWhoosh with no issue at all.

The riding experience was not perfect to start, I was just warming up and was going 38 MPH in MyWhoosh with the default settings. Based on some old threads here I then altered the default settings to below: 

Zwift Offset Resistance: 7
Max Resistance: 16
Watt Gain: 0.55
MyWhoosh Compatibility: On
I have tried Zwift Workout Mode on and off.

In MyWhoosh when I connect I connect as a PowerSource, Cadence and Controllable.

That being said (for right now I think we can ignore MyWhoosh).

I put my phone where I can see it and locked the bike display to MPH.

At gears 7/8/9 my phone and the bike display MPH match pretty well. But in lower gears QZ is pretty far under and in high gears it's over estimating.

I guess my first question is: If the bike knows how fast it's going why is the QZ value different? Is it not reported? 
Second Question: What I'm currently doing feels "unscientific", is there a better way to dial in the settings?
Third Question: I see a "Disable Wattage from machinery" that is disabled. Is the assumption that the power meter in the bike is wrong (if it has one?)?

Bonus Question (possibly more of a MyWhoosh question):
Is there to have a gear override? Like for instance I have 7/8 as my default for flat ground. I would like to be able to change gears to work harder (or less), but something (not sure if it's QZ or MyWhoosh) changes the gear back quickly if I use the bike dial. I see a setting to change gears in QZ, would that do it? What I picture in my head is if flat ground is an 8 and I increase gears that would be kept as an offset somewhere (so inclination gear +1), then if I start going up hill the gears would go up and still keep my offset. For reference my gym has as Expresso equipment, and at least for a noob that appears to be how it works ((inclination and virtual gear combine to output resistance).

**Comment by cagnulein** [comment]
attach a debug log to check your scenario https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
#2093

**Comment by cstack89** [comment]
Thanks! I will follow the steps for the debug log (probably not for 24 hours). 2093 is what I followed to get inspiration for nearly right settings. I should not use the beta in that ticket should I? Also I'm not sure MyWhoosh supports ERG mode in Free Ride mode which is all I've tried.

Of note I did just do a quick spin with "Volume Buttons change gears" and the gears worked exactly as i expected. So you can drop the bonus question.

**Comment by cagnulein** [comment]
> I should not use the beta in that ticket should I?

the beta it's already the production one. With a debug log the questions will be clearer I hope :)

**Comment by cagnulein** [comment]
you have to collect a debug log in the same scenario where you have the issue, it's up to you setting all the scenario in that way. I need to see EXACTLY the issue you're explaining

**Comment by cstack89** [comment]
[debug-Fri_Jul_26_05_35_18_2024.log](https://github.com/user-attachments/files/16389971/debug-Fri_Jul_26_05_35_18_2024.log)

I've attached my debug log. I turned on the bike, started QZ so it found my bike. Then started MyWhoosh and connected to my phone. I tried to pay attention to all 3 speeds since that is the only metric that was easy to see. For resistance 8 and 9 all three devices seemed to be close, but I manually shifted gears up and my speed on the bike began lagging behind what QZ was reporting. Eventually I shifted back down to 0 in the gears section and around that time I started a slight downhill. Compared to the bike QZ and MyWhoosh were over reporting my speed.

MyWhoosh was kind of all over the place, it didn't feel like it matched either the bike or QZ. Possibly MyWhoosh has a lag for updating the speed metric? Even trying to be patient though it was hard to tell if the speed was matching my bike, QZ, or using it's own computed value.

**Comment by cagnulein** [comment]
Yes Mywhoosh calculates the speed on its own based on the wattage coming from QZ. Is the wattage on Mywhoosh matches the one of QZ? 

I can't download the log file, it seems it's corrupted, could you please upload it again?

**Comment by cstack89** [comment]
[debug-Fri_Jul_26_05_35_18_2024.log](https://github.com/user-attachments/files/16390733/debug-Fri_Jul_26_05_35_18_2024.log)

I will pay more attention to the wattage on my ride tomorrow sorry.

**Comment by cagnulein** [comment]
ok yes the speed is not sent from your bike. and this is not a big deal since the speed is not so important in indoor bike. THe most important thing is the wattage, check this out https://robertoviola.cloud/2024/01/27/dispelling-the-myth-speed-variations-between-qz-and-zwift-are-not-a-device-issue/

that's why changing the resistance, you see the speed also changes, because the wattage changes

Let me know if something is not clear

**Comment by cstack89** [comment]
I think that makes sense, basically don't worry about the 3 different speeds because they are each doing the calculation a little differently? The bike likely is not taking in virtual inclination data and the math behind QZ and MyWhoosh based on the info is probably just different?

Are the 
Zwift Offset Resistance: 7
Watt Gain: 0.55

basically the two tuning parameters I should be doing to make it feel natural? Is the best way to do it by feel? Basically set my outdoor bike to gear 1 and ride around flat at various efforts, then run inside and modify those two parameters and see if my speeds roughly match?

**Comment by cagnulein** [comment]
> I think that makes sense, basically don't worry about the 3 different speeds because they are each doing the calculation a little differently? 

Exactly 

> The bike likely is not taking in virtual inclination data and the math behind QZ and MyWhoosh based on the info is probably just different?

Exactly the point

> 
> 
> 
> Are the 
> 
> Zwift Offset Resistance: 7
> 
> Watt Gain: 0.55
> 
> 
> 
> basically the two tuning parameters I should be doing to make it feel natural? Is the best way to do it by feel? Basically set my outdoor bike to gear 1 and ride around flat at various efforts, then run inside and modify those two parameters and see if my speeds roughly match?

Yes, most of if you have a power meter you can calibrate it exactly, most important is the watt gain

**Comment by cstack89** [comment]
Thank you for helping clear up my misunderstanding!

**Comment by cstack89** [comment]
I have another question based on today's ride. My bike has 16 resistances. During today's ride, I believe MyWhoosh said the inclination was 15% which set my resistance to 16. Even if I stood and pedalled as hard as I could I could only get to 1MPH. My settings are still the same as yesterday. I can take a debug log on Monday if needed. 

In my head what I'm wondering is if I can fake out Mywhoosh and pretend my bike has 32 gears. Qz would then translate gear 32 to be 16. Non even numbers would go up or down. I tried setting zwift resistance gain to 2, but that didn't seem to do anything. I was hesitant to turn on treadmill as a bike because wasn't sure if that would mess up other bike settings.

**Comment by cagnulein** [comment]
did you check your wattage on that scenario? how much is what? to riding at 15% you have to have at least 200-300W to have a 6-8 km/h speed

It's not a resistance issue, I guess it's just a wattage issue

**Comment by cstack89** [comment]
I don't have time to setup MyWhoosh right now, but I hopped on the bike and set it to resistance 16. Then I bikes hard and QZ reported 220-250W. I was wrong 😂 I updated my watt percentage to be .75 but even with that increase that means the watt value in MyWhoosh would be <188? Unless what Qz displays is the scaled value?

**Comment by cagnulein** [comment]
qz already shows the scaled value and it sends the same value to MYW

**Comment by cagnulein** [comment]
hi @BDO811 i guess you are doing a erg workout? (workout based on power)
if so you need to calibrate first the power table inside qz: in order to do so, follow these steps:
1. set your bike under manual device in the advanced settings
2. restart qz
3. on qz standalone do 10 seconds of spin with cadence 50-60-70-80-90 for each resistance levels. it's important to stay more or less stable for at least 10 seconds on each cadence/resistance couple 
4. pair trainer day and give it a go then

if it still doesn't work send me a debug log

**Comment by BDO811** [comment]
Just to confirm

I go to manual. Hit ok. Then restart.

Go to resistance 1 and pedal at 50 then 60 then 70 etc
Go to resistance 2 and pedal at 50 then 60 etc

Am I supposed to change anything on the app while I do it or it just knows?
And do this for all 24 resistance levels?

Then turn off manual and restart and then the erg should work?

Thanks

**Comment by cagnulein** [comment]
all good except the last part, don't remove the bike from manual. as far as you finish to do the spins for all the 24 levels you are ready to go.
keep also the debug log enabled so in case of issues i can check them
let me know

**Comment by BDO811** [comment]
Getting closer 

I have done the calibration. 

1. When I’m cycling and the goal in TrainerDay is 150w and I’m at 250w should it auto decrease the resistance?  It’s not doing that. It does change the resistance but often goes the wrong way. 

My understanding is qz would increase or decrease the resistance to hit the target wattage?

how do I send you a debug log. It says 25mb max and it’s 34

**Comment by cagnulein** [comment]
yes it should follow the resistance, it means that something went wrong in the calibration 
for the debug log zip it 
let me know

**Comment by BDO811** [comment]
Could you check. I’ve used the beta and redone the calibration. Still not reacting to auto resistance the way I would think 

Is there an option to have qz look at the target watts on TrainerDay and try to adjust settings to hit that number?

https://drive.google.com/file/d/1AauAvpssKa7JAeorO9l3HMn8CkfguuVC/view?usp=drivesdk

**Comment by cagnulein** [comment]
Hi, i need the debug log. you attached the fit file
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 24 ago 2024 alle 22:36 BDO811 ***@***.***> ha
scritto:

**Comment by BDO811** [comment]
https://drive.google.com/file/d/1pLBC9jbCXgZWniO-BEWq2ccorf6973ks/view?usp=drivesdk

**Comment by cagnulein** [comment]
thanks, i will check it tomorrow
i'm on vacation

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle 06:43 BDO811 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i quickly checked the table that you trained and it seems ok, so I will
check about the implementation, maybe there is a small bug because it
mostly worked but there is a lot of bouncing. In the meantime you can
increase the erg filter up and down to 30 to check if it's better
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle ore 06:44 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i checked the log and when trainerday it was asking for 146W QZ is setting correctly the ressitance to 2, and when it asked for 222W it put it 6-7 based on your current cadence. anyway with the erg filter up and down set to 30 you should limit also the bouncing

let me know @cstack89

**Comment by cagnulein** [comment]
hi @tim-lang are you on ios or android first of all?

**Comment by tim-lang** [comment]
iOS

**Comment by cagnulein** [comment]
@tim-lang ok so you need first of all the new beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by tim-lang** [comment]
Sent, thanks! (from tim at timlang.com )
