### ISSUE TITLE
[BUG] resistance not working 

### ISSUE THREAD

**Issue by Radiopet** [cagnulein/qdomyos-zwift#2485]
hi Roberto

I’ve attached the debug file as requested 
[debug-fre__jul__26_19_04_21_2024.log](https://github.com/user-attachments/files/16394748/debug-fre__jul__26_19_04_21_2024.log)

**Comment by cagnulein** [comment]
#2484

thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 lug 2024 alle 19:11 Radiopet ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
did you check kinomap so?

**Comment by Radiopet** [comment]
Hey Roberto

Sorry for my late reply.
Thanks again for taking the time to help on the issue!
 I’ve been taking to the seller about the bike and the missing resistance
data as they promote the bike to have.

They have confirmed no data is collected on resistance, it’s a mechanical
setting.

So I ended up receiving a substantial price reduction on the bike. Which I
threw in wahoo’s direction, I should receive my new kicker core today.

Best regards
Thomas

lør. 27. jul. 2024 kl. 12.20 skrev Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
No worries, thanks for the update!


Il giorno gio 1 ago 2024 alle 12:54 Radiopet ***@***.***> ha
scritto:
