### ISSUE TITLE
[BUG] Tunturi FitCycle i70 - Incorrect RPM data after 99.

### ISSUE THREAD

**Issue by PikadorHU** [cagnulein/qdomyos-zwift#2490]
**Describe the bug**
The QZ App shows and transmit incorrect data to Zwift over 99. After 99 this starts from again, so if I ride with 110 RPM the QZ shows 10. The QZ speed meter drops also, but that is not affect Zwift, the watt is correct.

**To Reproduce**
Simple ride the bike with 100 RPM or over.
This easily reproduceable on this bike.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2

**Smartphone (please complete the following information):**
 - Device: Ipad mini 2
 - OS: 12.5.7

**Append a debug log**
Log attached (hopefully): I tired to keep the RPM around 95-105.

[debug-H_júl__29_13_02_54_2024.log](https://github.com/user-attachments/files/16411781/debug-H_jul__29_13_02_54_2024.log)

 
**Additional context**
If the bike connected to Zwift directly without QZ App the RPM is correct over 100 RPM.

**Comment by cagnulein** [comment]
fixed, i will send a new one later today

**Comment by PikadorHU** [comment]
Thank you for your quick update. I had not tried it yet.
One more thing I noticed during a sprint.
The RPM is good again around over 170+ RPM.

**Comment by cagnulein** [comment]
i guess they are both fixed now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 29 lug 2024 alle ore 15:23 PikadorHU ***@***.***>
ha scritto:

**Comment by PikadorHU** [comment]
I tried the fix, this looks fine.
The RPM count looks fine after 99.
My best performance was around 135 RPM, so the 170 RPM previously would be inrealistic and would a misleading data from the original version. 

The fix looks 100% correct.
