### ISSUE TITLE
[BUG]SS2K + Peloton Bike (Power Zone Rides)

### ISSUE THREAD

**Issue by Dekto** [cagnulein/qdomyos-zwift#2492]
**Describe the bug**

During the Peloton Power Zone workouts, the SmartSpin2k switches to a different zone, even though the specified zone has not yet been completed.

**To Reproduce**

Do a Power Zone Ride on the Peloton Bike with SmartSpin2k and the qdomyos-zwift (iOS) app.

**Expected behavior**

The automatic resistance should remain in the correct power zones.

**Smartphone:**
 - Device: iPhone SE 2022
 - OS: iOS 17.5.1
 - Version qdomyos-zwift 2.15.4

**Append a debug log**

[debug-Mi__Juli_31_21_33_00_2024.log](https://github.com/user-attachments/files/16447221/debug-Mi__Juli_31_21_33_00_2024.log)

  
  **Additional context**

Peloton Workout runs directly on the Peloton Bike Tablet.

**Comment by cagnulein** [comment]
ok i will check tomorrow. just to bbe sure, is it only a timing issue ?
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 lug 2024 alle ore 23:07 Dekto ***@***.***>
ha scritto:

**Comment by Dekto** [comment]
Yes, I think it's a timing problem because the upcoming Power Zone is the right one. But it starts before the current one is completed.

**Comment by cagnulein** [comment]
did u press yes in the qz popup when the timer is 0:00 on the peloton app?
you have to be in sync. then you can use the peloton offset tile to adjust
the delta
let me know
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 lug 2024 alle ore 23:23 Dekto ***@***.***>
ha scritto:

**Comment by Dekto** [comment]
I confirmed the popup immediately after opening it. But there is always an intro before the workout starts. So should I only confirm the popup once the intro is over?

**Comment by cagnulein** [comment]
yes exactly, when the timer is 0:00
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 31 lug 2024 alle ore 23:32 Dekto ***@***.***>
ha scritto:

**Comment by Dekto** [comment]
I understand. That makes sense. I'll test it in the next few days. Thanks for your support!

**Comment by Dekto** [comment]
I was just able to test it. The zone change works if the popup is confirmed at 0:00. Thanks for the support!

**Comment by Dekto** [comment]
I was just able to test it. The zone change works if the popup is confirmed at 0:00. Thanks for the support!

**Comment by cagnulein** [comment]
Glad to hear it!
Remember to rate the app on the store if you didn't already, it means a lot
to me!

Il giorno dom 4 ago 2024 alle 12:01 Dekto ***@***.***> ha
scritto:
