### ISSUE TITLE
X22i Not staying connected via ADB

### ISSUE THREAD

**Issue by bwthomas77** [cagnulein/qdomyos-zwift#2493]
**Describe the bug**
The QZ companion has trouble staying connected to the Treadmill. I have an NordicTrac X22i. I have tried multiple hard resets. I have never been able to get the PC running Zwift to be able to control incline or speed or from the +/- buttons on the app. The app is able to read the speed and inclination data and that is being sent to Zwift

**To Reproduce**
1. Install QZ Companion using instructions given. Both with and without updates. Both on my EERO network and on the AT&T router. 
2. Install via ADB goes fine
3. After install I get errors that it cannot connect via ADB. 

**Expected behavior**
Treadmill consistently connects and is able to change speed and incline (slide bars active)
[adb debug output.txt](https://github.com/user-attachments/files/16458024/adb.debug.output.txt)
[adb shell input message.txt](https://github.com/user-attachments/files/16458025/adb.shell.input.message.txt)
[dumpsys.log](https://github.com/user-attachments/files/16458027/dumpsys.log)
[logcat.txt](https://github.com/user-attachments/files/16458028/logcat.txt)
![Tue07-23-2024@17-31-21 16](https://github.com/user-attachments/assets/a1ff888a-c0d7-4eee-8d27-ca22a14ce582)

**Screenshots**
![Tue07-23-2024@17-31-21 16](https://github.com/user-attachments/assets/62adbb01-1e1b-4594-bdcb-1bd73f3308dd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Smartphone (please complete the following information):**
 - Device: iphone 14 pro
 - OS: iOS 17.5.1
 
**Append a debug log**

[adb debug output.txt](https://github.com/user-attachments/files/16458049/adb.debug.output.txt)
[adb shell input message.txt](https://github.com/user-attachments/files/16458050/adb.shell.input.message.txt)
[dumpsys.log](https://github.com/user-attachments/files/16458051/dumpsys.log)
[logcat.txt](https://github.com/user-attachments/files/16458052/logcat.txt)

  
  
**Additional context**
The problem seems to be the companion app lists the device as offline even though it successfully pings.  offline transport_id:1, I cannot seem to get to the root of this problem.

**Comment by cagnulein** [comment]
the problem seems adb, are you able to connect at all to the treadmill via adb from your pc?

**Comment by bwthomas77** [comment]
> the problem seems adb, are you able to connect at all to the treadmill via adb from your pc?

I am always able to connect on first try after hard reset. After that things don't seem to connect, continue to get device offline errors despite IP pinging fine

**Comment by bwthomas77** [comment]
After this most recent install only speed data was showing, incline did not

At one point I could control the fan with the app, but that no longer works either.

**Comment by cagnulein** [comment]
did you try to reset to factory reset WITHOUT updating ifit app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 ago 2024 alle 17:49 bwthomas77 ***@***.***>
ha scritto:

**Comment by bwthomas77** [comment]
Yes, similar behavior. Also without updating the sliders are not available.

**Comment by cagnulein** [comment]
the sliders must be enabled in the ifit settings , they are disabled by
default.

another trick would be allowing the qz companion root access so you
shouldn't adb at all then. are you able to do so?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 ago 2024 alle 17:52 bwthomas77 ***@***.***>
ha scritto:

**Comment by bwthomas77** [comment]
Do you have written instructions on how to give root access? I'm not very familiar with android...

**Comment by cagnulein** [comment]
Let me try first another approach based on the accessibility service. I
will try to implement now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 1 ago 2024 alle 19:27 bwthomas77 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
which android version have this treadmill?

**Comment by cagnulein** [comment]
ok @bwthomas77 done
i added a new device in the companion app called x22i no adb.
once you will click it it will prompt to enable the accessibility service. Enable it (you need to enable this at every startup, i don't know why it doesn't save it, but first of all, let's see if it works).

Then do this:
- go into the developer settings of the treadmill and enable the input shadow and input position in order to see swipe
- then press the dump log button in the companion: this will simulate a fake event. If it works we are ready to give it a try on a real workout

Let me know!

New apk: https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10204085440/artifacts/1766251655

**Comment by bwthomas77** [comment]
Will do

Android is 7.1.2

**Comment by bwthomas77** [comment]
Success, touch inputs work now.

I haven’t tried a Zwift workout yet but will report

Sent from my iPhone

On Aug 1, 2024, at 15:33, Brad Thomas ***@***.***> wrote:

﻿
Will do

Android is 7.1.2

**Comment by cagnulein** [comment]
OMG really!? That's an  amazing news!

**Comment by bwthomas77** [comment]
Tested it out this evening with Zwift, iPhone app controls working. I actually didn’t have to reselect the no and option on the treadmill. The increments for elevation are a little strange, increases by 6,5 degrees when pressing plus on app. Goes down bye one.
The Zwift elevation isn’t communicating from the pc to the iPhone app however.

Otherwise this is definitely a huge improvement as I couldn’t get app to control previously
Thanks Brad
Sent from my iPhone

On Aug 5, 2024, at 00:25, Roberto Viola ***@***.***> wrote:

﻿

OMG really!? That's an amazing news!

**Comment by cagnulein** [comment]
> I actually didn’t have to reselect the no and option on the treadmill.

great, that's a good news



> The increments for elevation are a little strange, increases by 6,5 degrees when pressing plus on app. Goes down bye one.

i will check the coordinates, i used the ones that I had already implemented.



> The Zwift elevation isn’t communicating from the pc to the iPhone app however.

did you add your zwift credentials in qz on the iphone? you must have the 2.16 version on iphone. if you don't have 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you it.

**Comment by cagnulein** [comment]
got the inclination issue, does your treadmill has negative inclination? @bwthomas77 if so which is the minimum one?

**Comment by bwthomas77** [comment]
Yes, the range is -6 to 40 degrees

**Comment by cagnulein** [comment]
ok try this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.4/QZCompanionNordictrackTreadmill.apk

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 6 ago 2024 alle ore 12:21 bwthomas77 ***@***.***>
ha scritto:

**Comment by bwthomas77** [comment]
Thanks

Downloaded new iOS app.

Two things:
When I press the up or down button on inclincation on the app the treadmill goes up by 5.5 or so degree increments.

When I enter by zwift credentials, the app stops talking to the pc running zwift.

-Brad

**Comment by cagnulein** [comment]
The zwift credentials should be unrelated to the communication with zwift, check again.

for the inclination i will check again the coordinates, i'm in vacation for the next 15 days so I will do my best

**Comment by cagnulein** [comment]
sorry for the delay, i'm on vacation , here there is a new one https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.5/QZCompanionNordictrackTreadmill.apk

**Comment by bwthomas77** [comment]
Thanks Robert,

No rush, whenever you get done with vacation.

Here's whats happening:

  1.  The new companion app does not seem to be mapped correctly. When I press the elevation button on the iOS app it brings up the controls so must be pushing the white space somewhere. Speed works.
  2.  Running a Zwift run on this setup, the inclincation does not translate to the iOS app. The speed data goes from the treadmill to the zwift running on PC but seems to intermittently drop.
  3.  Interestingly I ran a test session before updating the companion app while I was riding my bike in Zwift on a TACX NEO 2. The inclination from the bike ride was moving the treadmill up and down (at about double the inclination that zwift was showing). This was without the wahoo tread as the input as it was connected to my tacx.
Thanks,
Brad


***@***.***

**Comment by cagnulein** [comment]
Ok let's first the inclination coordinates first, then will check zwift. I will check again the coordinates in these days

**Comment by cagnulein** [comment]
ok i guess i got the error in the coordinates, try this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.6/QZCompanionNordictrackTreadmill.apk

**Comment by cagnulein** [comment]
> Running a Zwift run on this setup, the inclincation does not translate to the iOS app. The speed data goes from the treadmill to the zwift running on PC but seems to intermittently drop.

you need to add the zwift credentials on qz for this @bwthomas77

**Comment by bwthomas77** [comment]
The mapping now works! I can raise and lower the inclination from the app.

My Zwift credentials have been entered since I got the beta app that has that option, I don't think that is the issue. I may have had one of the options checked below that was? I will try again today.

**Comment by cagnulein** [comment]
Great! Show me the options, you have to attach the image on github.com interface directly otherwise I can't see them

**Comment by cagnulein** [comment]
@bwthomas77 are we ok with this?
