### ISSUE TITLE
[BUG] - Nordictrack elliptical C12.9 not connecting to iPhone running qz fitness

### ISSUE THREAD

**Issue by LeonardF65** [cagnulein/qdomyos-zwift#2494]
**Describe the bug**
Struggling to get my elliptical connected to my iPhone running qz fitness. My Nordictrack Commercial 12.9 Elliptical has a wifi internal console running Android 5.1.1 and as such I cannot load qz companion. Even when I go into Privileged Mode the options are very limited on Android 5.1.1 and I cannot set the enable USB debugging. I have captured the IP address in the Treadmill Proform section. Not sure what virtual setting I need to have on.
It seems to connect from my iPhone to my My pad running Zwift. Just not connecting between my phone running qa fitness and the wifi enabled elliptical

**To Reproduce**
1. Start zwift on my iPad and connect using the Power meter. link to my iPhone for the power meter and the cadence
2. Start the session with qa fitness running on my iphone
3. Avitar does not move
4. End the session

**Expected behavior**
Expected the avatar to move

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 Pro and iPad Pro 2
 - OS: [e.g. iOS8.1]I0S 
 - Version [e.g. 22] 17.5.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Thu_Aug_1_21_48_25_2024.log](https://github.com/user-attachments/files/16462127/debug-Thu_Aug_1_21_48_25_2024.log)
[debug-Thu_Aug_1_21_56_00_2024.log](https://github.com/user-attachments/files/16462128/debug-Thu_Aug_1_21_56_00_2024.log)

**Comment by cagnulein** [comment]
ok it's not using websocket, so it could be another version. Could you please install the free nrfconnect app and check, on the elliptical ip, if it has some open ports?
Let me know

**Comment by LeonardF65** [comment]
Thanks RobertoI am just away for the weekend. Will try when I get back.On which device do I install nrfconnect , the iPhone with qz fitness?How do I check for open ports on the elliptical?Thanks, I appreciate the helpKind regards LeonardSent from my iPhoneOn 02 Aug 2024, at 08:43, Roberto Viola ***@***.***> wrote:﻿
ok it's not using websocket, so it could be another version. Could you please install the free nrfconnect app and check, on the elliptical ip, if it has some open ports?
Let me know

**Comment by cagnulein** [comment]
yes fing on the iphone

check this

![image](https://github.com/user-attachments/assets/c24b0a1d-c826-4527-a667-a38bedfc30d5)

it says find open port

**Comment by LeonardF65** [comment]
Thanks 🙏🏻 Sent from my iPhoneOn 02 Aug 2024, at 13:16, Roberto Viola ***@***.***> wrote:﻿
yes fing on the iphone
check this
Upload.from.GitHub.for.iOS.png (view on web)
it says find open port

**Comment by LeonardF65** [comment]
Hi RobertoThere were 2 apps for nrfconnect nrfconnect for mobilenrfconnect device managerNot sure which one I should be using. I have downloaded them both.They both seem to be trying to g to connect to my elliptical via Bluetooth. The elliptical seems to very specific on what type of BT devices it is prepared to connect to via BT. My phone is not one of them🙈How is nrfconnecr supposed to communicate with the elliptical? by or WiFi?I assume the Qz fitness is supposed to connect to the elliptical with WiFi .I have attached 2 screen shots of the QZ settings or elliptical and treadmillElliptical TreadmillNot sure what to do if I cannot get the nrfconnect to connect toMy elliptical.Kind regards LeonardSent from my iPhoneOn 02 Aug 2024, at 13:16, Roberto Viola ***@***.***> wrote:﻿
yes fing on the iphone
check this
Upload.from.GitHub.for.iOS.png (view on web)
it says find open port

**Comment by cagnulein** [comment]
hi you have to upload the image directly from the github web interface otherwise i can't see it
qz call the dog with your fitness device with both Wi-Fi and Bluetooth, that's why I would like to check out it show there

**Comment by LeonardF65** [comment]
I have attached two screenshots, one of the QZ elliptical and then the treadmill settings.

I am concerned that the elliptical does not see my cellphone via Bluetooth and when I try an link to the elliptical from my cellphone while trying to setup nrfconnect app it does not see the elliptical when it scans. I assume if it can't see it, it can't connect to the elliptical. so what must I do now?

The elliptical was purchased by the original owner in 2020 so the machine is about 4 years old

The elliptical does see my heart rate monitor via BT

![IMG_1861](https://github.com/user-attachments/assets/629a5be1-99cf-4811-8595-667b6a9368ba)
![IMG_1862](https://github.com/user-attachments/assets/b80fa2dd-7200-49ed-8657-9ff7cda11d60)

**Comment by cagnulein** [comment]
Hi @LeonardF65 i requested the nrfconnect screenshots, were you able to send me them?

**Comment by LeonardF65** [comment]
Hi Below is the nrfcnnect trying to connect via BT. It is only seeing a Garmin Cadence sensor that I have attached to the flywheel, my TV and my iPad. It does not see the Nordictrack elliptical. 
![IMG_1870](https://github.com/user-attachments/assets/73a6e2ae-912d-4fc3-9c1d-ff3202c55b3d)

I have also attached a screenshot of of trying to connect to BT accessories from the elliptical machine. Here it is seeing my mi TV box.
![IMG_1871](https://github.com/user-attachments/assets/9496b40f-db53-4112-b469-a917e38b5297)

From my iPhone side I have attached another screenshot below of searching for BT devices and from my iphone I cannot see the elliptical. Also only picks up my mi TV box
![IMG_1872](https://github.com/user-attachments/assets/7800b0d6-9b96-463a-a75c-a0a27e7c55eb)

It is almost like the Nordictrack elliptical is only primed to look for certain types of BT devices. I will see my Garmin HR monitor, but not the Garmin Cadence and Garmin Speed sensor that I have attached to the elliptical.

**Comment by cagnulein** [comment]
Ok so yes it doesn't broadcast any metrics on Bluetooth. did you try the fing app as I suggested above?

**Comment by LeonardF65** [comment]
Hi, I loaded the fing app.
I run a scan and it does not pickup IP address ending in .37
It only sees 15 devices
![IMG_1884](https://github.com/user-attachments/assets/08f30d2e-7178-419a-b187-40d67b529517)
![IMG_1885](https://github.com/user-attachments/assets/f93c9998-3ef7-4fab-ab5c-a7479674dcc6)

If I check from my router side I can see .37
My router sees 18 devices
![IMG_1886](https://github.com/user-attachments/assets/060a864d-e8c4-4a78-bb0d-03a032c3e29e)
I compared the MAC address and it is the same as reported on the elliptical

I don't understand why fing does not see this device. 

I tried again to ping the IP from my laptop and I was able to ping the elliptical. Is there a DOS command that can reveal the available ports?

Pinging 192.168.50.37 with 32 bytes of data:
Reply from 192.168.50.37: bytes=32 time=717ms TTL=64
Reply from 192.168.50.37: bytes=32 time=3ms TTL=64
Reply from 192.168.50.37: bytes=32 time=3ms TTL=64
Reply from 192.168.50.37: bytes=32 time=4ms TTL=64

Ping statistics for 192.168.50.37:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 3ms, Maximum = 717ms, Average = 181ms

**Comment by cagnulein** [comment]
That's so strange that fing app can't find it. Anyway you can use the https://nmap.org/zenmap/ on windows searching for the all ports from 1 to 65535

**Comment by LeonardF65** [comment]
I have figured out that I am having issues with the wifi connection to the NordicTrack elliptical. It keeps dropping the connection and that is the reason why I think I was having issues seeing the IP address. Just trying to resolve that issue. I have set the date and time but that does not seem to have fixed the issue. Will let you know once I have fixed the wifi issue and can see the available ports.

**Comment by cagnulein** [comment]
Ok let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 00:53 LeonardF65 ***@***.***>
ha scritto:

**Comment by LeonardF65** [comment]
Hi I have managed to get the machine to connect with the WiFi on the IP address mentioned earlier but when I check for open ports it says "No open port found"

**Comment by LeonardF65** [comment]
If I scan for ports with NMap I get the following

Starting Nmap 7.95 ( https://nmap.org ) at 2024-09-09 23:06 South Africa Standard Time
NSE: Loaded 157 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 23:06
Completed NSE at 23:06, 0.00s elapsed
Initiating NSE at 23:06
Completed NSE at 23:06, 0.00s elapsed
Initiating NSE at 23:06
Completed NSE at 23:06, 0.00s elapsed
Initiating ARP Ping Scan at 23:06
Scanning 192.168.50.37 [1 port]
Completed ARP Ping Scan at 23:06, 1.54s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 23:06
Completed Parallel DNS resolution of 1 host. at 23:06, 0.22s elapsed
Initiating SYN Stealth Scan at 23:06
Scanning 192.168.50.37 [1000 ports]
Completed SYN Stealth Scan at 23:06, 0.94s elapsed (1000 total ports)
Initiating Service scan at 23:06
Initiating OS detection (try #1) against 192.168.50.37
Retrying OS detection (try #2) against 192.168.50.37
NSE: Script scanning 192.168.50.37.
Initiating NSE at 23:06
Completed NSE at 23:06, 0.02s elapsed
Initiating NSE at 23:06
Completed NSE at 23:06, 0.00s elapsed
Initiating NSE at 23:06
Completed NSE at 23:06, 0.00s elapsed
Nmap scan report for 192.168.50.37
Host is up (0.0051s latency).
All 1000 scanned ports on 192.168.50.37 are in ignored states.
Not shown: 1000 closed tcp ports (reset)
MAC Address: B0:02:47:A4:4C:95 (Ampak Technology)
Too many fingerprints match this host to give specific OS details
Network Distance: 1 hop

TRACEROUTE
HOP RTT     ADDRESS
1   5.07 ms 192.168.50.37

NSE: Script Post-scanning.

**Comment by cagnulein** [comment]
run nmap but this time set to scan all the ports from 1 to 65535
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 9 set 2024 alle 23:09 LeonardF65 ***@***.***>
ha scritto:

**Comment by LeonardF65** [comment]
Starting Nmap 7.95 ( https://nmap.org ) at 2024-09-10 22:55 South Africa Standard Time
NSE: Loaded 157 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 22:55
Completed NSE at 22:55, 0.01s elapsed
Initiating NSE at 22:55
Completed NSE at 22:55, 0.00s elapsed
Initiating NSE at 22:55
Completed NSE at 22:55, 0.00s elapsed
Initiating ARP Ping Scan at 22:55
Scanning 192.168.50.37 [1 port]
Completed ARP Ping Scan at 22:55, 1.37s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 22:55
Completed Parallel DNS resolution of 1 host. at 22:55, 0.21s elapsed
Initiating SYN Stealth Scan at 22:55
Scanning 192.168.50.37 [65535 ports]
Completed SYN Stealth Scan at 22:56, 53.56s elapsed (65535 total ports)
Initiating Service scan at 22:56
Initiating OS detection (try #1) against 192.168.50.37
Retrying OS detection (try #2) against 192.168.50.37
NSE: Script scanning 192.168.50.37.
Initiating NSE at 22:56
Completed NSE at 22:56, 0.01s elapsed
Initiating NSE at 22:56
Completed NSE at 22:56, 0.00s elapsed
Initiating NSE at 22:56
Completed NSE at 22:56, 0.00s elapsed
Nmap scan report for 192.168.50.37
Host is up (0.024s latency).
All 65535 scanned ports on 192.168.50.37 are in ignored states.
Not shown: 65535 closed tcp ports (reset)
MAC Address: B0:02:47:A4:4C:95 (Ampak Technology)
Too many fingerprints match this host to give specific OS details
Network Distance: 1 hop

TRACEROUTE
HOP RTT      ADDRESS
1   23.62 ms 192.168.50.37

NSE: Script Post-scanning.
Initiating NSE at 22:56
Completed NSE at 22:56, 0.00s elapsed
Initiating NSE at 22:56
Completed NSE at 22:56, 0.00s elapsed
Initiating NSE at 22:56
Completed NSE at 22:56, 0.00s elapsed
Read data files from: C:\Program Files (x86)\Nmap
OS and Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 57.65 seconds
           Raw packets sent: 65559 (2.886MB) | Rcvd: 65556 (2.623MB)

**Comment by cagnulein** [comment]
ok so this device doesn't expose anything on outside. we need to send metrics from inside. Are you able to install a terminal on the tablet itself to run a logcat command or to check the logs inside of it?

**Comment by LeonardF65** [comment]
I have managed to get into the console but it is running Android 5.1.1 . When you say run a logcat command I assume this is like a dos command would be to a PC.

I don't think the google play store will let me load anything as I do not think they support Android 5.1.1 apps anymore.
I take it there is no chance of loading a later operating system or even if the hardware does support that system it will become very slow and not even allow anything to run properly.

Is there an older version of QZ Fitness that can be loaded onto an Android 5.1.1 console?

**Comment by cagnulein** [comment]
> I have managed to get into the console but it is running Android 5.1.1 . When you say run a logcat command I assume this is like a dos command would be to a PC.

yes you need to run the terminal there. you can download any terminal app from the play store or apkpure for example



> Is there an older version of QZ Fitness that can be loaded onto an Android 5.1.1 console?

qz is running on android 5 but we need first to understand where we can take the metrics from it

**Comment by cagnulein** [comment]
@LeonardF65 any news?

**Comment by LeonardF65** [comment]
Hi

 

I have been rather busy and have not had time fiddle.

 

I am also not sure what to do once I am in

 

I also ended up renewing my iFit subscription

 

Kind Regards

 

 

Leonard Fernandez

082 4958302

**Comment by cagnulein** [comment]
@LeonardF65 i was waiting the logcat from the terminal of your device

anyway i'm here if you want to resuming this

**Comment by lescapel** [comment]
Hi Roberto,

I have the same Nordictrack eilliptical like Leonard and same issue to connect the QZ App from my IOS device with the QZ Companion App on the elliptical. Could you help me please to fix this issue? I hope it is okay for you to bring this outdated ticket alife again. Otherwise please tell me how to process.

Kind Regards

**Comment by cagnulein** [comment]
Hi @lescapel you can follow this

https://github.com/cagnulein/qdomyos-zwift/issues/2494#issuecomment-2343848002

**Comment by lescapel** [comment]
Thank you for your fast reply. As you Rolf in the past i installed a Terminal Emulator on the elliptical and run the command **logcat brief**.

Here is the Screenshot:

![image](https://github.com/user-attachments/assets/871f88c0-e13c-46a8-a940-343142d27894)

**Comment by cagnulein** [comment]
ok if you start a manual workout are you able to see the metrics there?

**Comment by lescapel** [comment]
It Shows me in a workout this:

![image](https://github.com/user-attachments/assets/14f366f1-1863-4fb5-a7ef-f725abcca795)

**Comment by lescapel** [comment]
I tried it but after used the gret command it didn't shows me anything.
I tried the previos step again (logcat). This time i see that. It is helpfull now?

![image](https://github.com/user-attachments/assets/b6af9308-1627-4a01-8e97-5b39f2541777)

**Comment by cagnulein** [comment]
No unfortunately not. Are you able to pull out the apk of ifit there so we can decompile it?

**Comment by lescapel** [comment]
I Downloaded the IFIT v 2.6.71  apk but i don't find newer Launcher apk and a newer IFIT admin apk. Just iFIT can be deinstalled. Both other Apps not.

How we can decompile iFIT?

**Comment by lescapel** [comment]
It worked fine. So i have the decompiled files of the apk. What i have to do now?

**Comment by cagnulein** [comment]
share me the apk here zipping it and I will check it myself when i have time. The idea is looking for the serial protocol there

**Comment by lescapel** [comment]
ok here it is. Thank you Roberto

**Comment by lescapel** [comment]
[Uploading 2iFIT - At Home Fitness Coach_2.6.71_APKPure.apk_Decompiler.com2.zip.zip…]()

**Comment by lescapel** [comment]
[Uploading 3iFIT - At Home Fitness Coach_2.6.71_APKPure.apk_Decompiler.com3.zip.zip…]()

**Comment by lescapel** [comment]
[Uploading 4iFIT - At Home Fitness Coach_2.6.71_APKPure.apk_Decompiler.com4.zip.zip…]()

**Comment by lescapel** [comment]
[Uploading 5iFIT - At Home Fitness Coach_2.6.71_APKPure.apk_Decompiler.com.zip.zip…]()

**Comment by lescapel** [comment]
sorry, i had trouble to split them.

**Comment by cagnulein** [comment]
@lescapel you have to wait the finish of the upload. please put it on a google drive link in case

**Comment by lescapel** [comment]
https://drive.google.com/file/d/1EOsKfQ-oNYcDpXCPcESic1EDaz8Zek8m/view?usp=sharing

**Comment by cagnulein** [comment]
thanks i will check it in the next days/weeks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 dic 2024 alle ore 15:15 lescapel ***@***.***>
ha scritto:

**Comment by lescapel** [comment]
Ok, Sounds good. I have to thank you.

**Comment by lescapel** [comment]
Wow, you are fast. Unfortunately i don't have these apk's. I will try to find them and let you know.

**Comment by lescapel** [comment]
Hi Roberto, found both apk´s on my machine. Here you will find them:

https://drive.google.com/file/d/1W4U3WT_IG5C1fusnZ9aGcZmeBlfUEk87/view?usp=sharing

https://drive.google.com/file/d/1rT5w-OctVbbS61tskN9jO4biE1iq6-Zm/view?usp=sharing

**Comment by cagnulein** [comment]
Thanks, I'll check them out.


Il giorno mer 4 dic 2024 alle 21:22 lescapel ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
unfortunately it seems that the decompiler for this doesn't decode any source code. can you share the apk directly?

**Comment by lescapel** [comment]
Ok, here you will find both apk´s:

https://drive.google.com/file/d/1Epop7VRCV4LY_W2aqlYxD8ZJuQqvEA5S/view?usp=sharing

https://drive.google.com/file/d/1MSLxhqBJzb0XO5bTO5EqeiDNd9M6ucto/view?usp=sharing

**Comment by cagnulein** [comment]
Thanks, I'll check them out.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 dic 2024 alle ore 11:48 lescapel ***@***.***>
ha scritto:
