### ISSUE TITLE
[BUG] Proform Pro 9000, Controlling speed and incline via QZ in app controls.

### ISSUE THREAD

**Issue by Being57** [cagnulein/qdomyos-zwift#2496]
**Describe the bug**
Connected the treadmill successfully to the QZ app, and speed and elevation readings work fine, but the - + to adjust speed and elevation don't work. I was told on reddit to take a screenshot of the manual workout screen and open a ticket, so I'll attach it here.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/4576d7b9-6c8b-4fd6-8827-14daa10e0b0d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Galaxy S22 Ultra
 - OS: Android 14
 - Version One UI 6.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Being57 when you press the speed plus and minus button on qz, do you see a fake touch event on the touch screen of the treadmill?

**Comment by Being57** [comment]
Yes when I press the - + buttons in the app my treadmill screen brings down the notification bar as if it were swiping from top down if that's what you mean.

**Comment by cagnulein** [comment]
perfect, so it just a coordinate issue. Let me check the screenshot above. Do you have the remote adb setting in qz disabled right?

**Comment by Being57** [comment]
Right, I have that setting disabled, 
![image](https://github.com/user-attachments/assets/3f67d5a8-e15b-4741-b779-2a242a01c0ff)

**Comment by cagnulein** [comment]
perfect, i'm doing the mod in the qz companion. i will be back in 30 minutes

**Comment by Being57** [comment]
Alright

**Comment by cagnulein** [comment]
new companion https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10215236815/artifacts/1769036633

**Comment by Being57** [comment]
Alright I'll give it a try and be back with an update.

**Comment by Being57** [comment]
Alright so here is the update For the incline, one tap on the plus button sends it from 0 to 8 which isn't good, pressing the minus button doesn't do anything. For the speed, 1 tap on the plus button in the app will change the speed from 1 mph to 1.2, giving it a second tap doesn't do anything. The minus button decreases the speed by .1 or .2 when going down from a speed of 4 mph, when going down from a speed higher than 4 mph it also goes down by .3 sometimes rather by .1 or .2.mph, also may be worth mentioning that not every tap is effective, sometimes one tap isn't effective so I have tap it again to get a reaction, so far the minus speed button seems to be the most functional tho.

If you don't mind, I see that the QZ app also has - and + buttons for the fan speed. Do you think it's possible to control my fan speeds as well with the app?

**Comment by cagnulein** [comment]
ok inclination fixed, for the speed, set the step speed setting in the treadmill settings to a bigger value. like 1 mi/h for example. due to the conversion to km/h you shouldn't have a perfect match but anyway it should work on both way then

let me know

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10216418668/artifacts/1769318531

**Comment by Being57** [comment]
Okay, inclination, pressing plus now goes from 0-2 pressing again goes from 2-5, then from 5-8, 8-11, 11-11.5, 11.5-12. Pressing the minus when at 2, 5 does nothing, when it's at 8 and I press the minus button it goes from 8-11, then 11-10, 10-9, 9-8 and then 8 back to 11.

Speed, it's working pretty good, it isnt perfect as the increments of speed arent 100% locked in and vary as you go up and down in speed, but I can live with it, now it's just the incline that still has some issues. I'd love to increase  and decrease the incline by 1s. 0 1 2 3 4 3 2 1 0

**Comment by cagnulein** [comment]
try this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.3/QZCompanionNordictrackTreadmill.apk

**Comment by cagnulein** [comment]
That's great!
Fan: nope, I can change only the things displayed on the ifit app at the moment. I'm investigating to remove completely the ifit app but I need a treadmill or a bike to play with for this.

**Comment by Being57** [comment]
Ah I understand, if you ever figure out how to operate these machines without the need of ifit that would be so great, I've been looking for something like that. Anyways thank you very much for your help and I wish you good luck in all your future projects.

**Comment by cagnulein** [comment]
Thanks! Remember to rate the app on the store, it means a lot to me!
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 ago 2024 alle 21:30 Being57 ***@***.***> ha
scritto:
