### ISSUE TITLE
QZ not connecting to Zwift Hub

### ISSUE THREAD

**Issue by DoobDawg** [cagnulein/qdomyos-zwift#2504]
**Describe the bug**
New to QZ, purchased the app recently, trying to set it up and my Zwift Hub is not connecting.

**To Reproduce**
1. Open the QZ app
2. The app sits on "Connecting" forever, with blinking bluetooth icon
3. Attempting "Manual Device" in advanced settings does nothing. The Zwift Hub does not show up in list, only Disabled and Wifi.

**Expected behavior**
I expect the Zwift Hub to connect immediately when opening the QZ app.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A, haven't gotten this far.

**Smartphone (please complete the following information):**
 - Device: Pixel 8
 - OS: Android
 - Version 14

**Append a debug log**

 Follow this guide [debug-Tue_Aug_6_18_28_36_2024.log](https://github.com/user-attachments/files/16516310/debug-Tue_Aug_6_18_28_36_2024.log)
  
  
**Additional context**
Nothing, just want the app to connect with the Zwift Hub.

**Comment by cagnulein** [comment]
Hi, location services must be enabled on your phone and also all the
permissions must be granted to the qz app.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 ago 2024 alle 00:34 DoobDawg ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@DoobDawg are we OK with this?

**Comment by DoobDawg** [comment]
Yes, connection worked once allowing location. Thank you!
