### ISSUE TITLE
Unable to connect to IndieVelo,

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#2505]
[temp_2727355485885.log](https://github.com/user-attachments/files/16529573/temp_2727355485885.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows
 - Version [e.g. 22] 11

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy S10+
 - Version [e.g. 22] 12

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Cycling Cadence Sensor (Peloton compatibility)
setting must be disabled in the peloton section in qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 ago 2024 alle ore 15:50 LDHig ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@LDHigare we OK with this?
