### ISSUE TITLE
Kingsmith WalkingPad Z1 not connecting to QZ

### ISSUE THREAD

**Issue by Sonia-81** [cagnulein/qdomyos-zwift#2506]
**Describe the bug**
I am trying to connect my walkingpad and my forerunner 965 to your app QZ on my iphone
[debug-sab_ago_10_16_28_46_2024.log](https://github.com/user-attachments/files/16570316/debug-sab_ago_10_16_28_46_2024.log)
[debug-sab_ago_10_16_32_30_2024.log](https://github.com/user-attachments/files/16570317/debug-sab_ago_10_16_32_30_2024.log)
[debug-sab_ago_10_16_33_07_2024.log](https://github.com/user-attachments/files/16570318/debug-sab_ago_10_16_33_07_2024.log)
[debug-sab_ago_10_17_41_37_2024.log](https://github.com/user-attachments/files/16570319/debug-sab_ago_10_17_41_37_2024.log)
[debug-sab_ago_10_18_09_51_2024.log](https://github.com/user-attachments/files/16570320/debug-sab_ago_10_18_09_51_2024.log)
 but it seems to connect, but walkingpad makes three beep and QZ shuts down.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  IPhone 11 pro
 - OS: [e.g. iOS8.1] IOS 16
 - Version [e.g. 22]  16.2

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Great I'm sending a new version by email

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 ago 2024 alle ore 18:43 Sonia-81 ***@***.***>
ha scritto:

**Comment by Sonia-81** [comment]
Hi, thanks. I send you the debug file of the new version of Qz.

[debug-dom_ago_11_16_30_23_2024.log](https://github.com/user-attachments/files/16575392/debug-dom_ago_11_16_30_23_2024.log)
[debug-dom_ago_11_16_29_44_2024.log](https://github.com/user-attachments/files/16575393/debug-dom_ago_11_16_29_44_2024.log)

**Comment by cagnulein** [comment]
Thanks, I'll check it out in the next days!


Il giorno dom 11 ago 2024 alle 18:49 Sonia-81 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I just sent a new one. Let me know if it's better!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 ago 2024 alle ore 20:06 cagnulein ***@***.***> ha
scritto:

**Comment by Sonia-81** [comment]
Hi. It's much better. now QZ stays open a few minutes longer than the first times. I'll send you the new debug file.

[debug-mar_ago_13_09_33_20_2024.log](https://github.com/user-attachments/files/16603887/debug-mar_ago_13_09_33_20_2024.log)
[debug-mar_ago_13_09_35_55_2024.log](https://github.com/user-attachments/files/16603888/debug-mar_ago_13_09_35_55_2024.log)
[debug-mar_ago_13_09_36_14_2024.log](https://github.com/user-attachments/files/16603890/debug-mar_ago_13_09_36_14_2024.log)

**Comment by cagnulein** [comment]
Got the issue, I'm sending you a new one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 20:32 Sonia-81 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Sent! Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 20:38 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
any news @Sonia-81 ?

**Comment by Sonia-81** [comment]
HI. It works. Qz immediately connected to the walking pad. Now I have to understand why the HR of the forerunner 965 is not displayed. You are amazing. I'll send you the debug files. Congratulations for your site, It’s very interesting. Thanks.

[debug-dom_ago_11_16_29_44_2024.log](https://github.com/user-attachments/files/16625276/debug-dom_ago_11_16_29_44_2024.log)
[debug-dom_ago_11_14_37_58_2024.log](https://github.com/user-attachments/files/16625277/debug-dom_ago_11_14_37_58_2024.log)
[debug-dom_ago_11_16_30_23_2024.log](https://github.com/user-attachments/files/16625278/debug-dom_ago_11_16_30_23_2024.log)

**Comment by cagnulein** [comment]
that's great!
in the heart rate belt name setting under general setting you have to set
your watch if it can broadcast heart rate. otherwise leave it to disabled
(instead of wifi) and enable the garmin companion setting and use the
garmin companion app on the watch!
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 14:49 Sonia-81 ***@***.***> ha
scritto:

**Comment by Sonia-81** [comment]
HI. Thanks for your instructions. I hope I followed them correctly. Hr is visible, but does not indicate the value of the watch. It starts from the correct value and then increases one by one to the maximum and then starts again at 1. I assume I didn't set the settings correctly.
I wonder if it is possible to start both Qz and the Garmin running activity on the Forerunner. In the end. the screen on the Qz Forerunner is correct as in the attached photo. Thanks Bye.

[debug-ven_ago_16_10_28_34_2024.log](https://github.com/user-attachments/files/16637013/debug-ven_ago_16_10_28_34_2024.log)
![E14A83CF-DD41-47CD-BC60-423B82D8F69F](https://github.com/user-attachments/assets/4b0c43e0-2dd2-49c2-8c35-8360699ff083)

**Comment by Sonia-81** [comment]
HI. Everything works perfectly. Thank you for your constant and precious help.

**Comment by cagnulein** [comment]
amazing! remember to rate the app on the store, it means a lot to me if you didn't already!
