### ISSUE TITLE
[BUG] zwift resistance in ERG mode goes through the roof 

### ISSUE THREAD

**Issue by dan1282** [cagnulein/qdomyos-zwift#2507]
**Describe the bug**
When doing a workout in zwift using tdf 4.0, erg mode works as expected for some time (5-15 minutes depending on workout). But at some point, the resistance will increase to what appears to be maximum and it won’t back down. Trying to pedal harder does not reduce it and neither does wattage changes in zwift.

**To Reproduce**
1. Ride in workout mode and it will happen after a bit.

**Expected behavior**
I would expect resistance to reduce especially when target wattage is 125w and pedal cadence is less than 25. Does this have anything to do with the fact that the pro form is able to freewheel? Is that somehow affecting this vs. a typical spin bike? 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: iPhone 15 po
 - OS: 17
 - Version 51
[debug-Sat_Aug_10_13_23_56_2024.log](https://github.com/user-attachments/files/16570443/debug-Sat_Aug_10_13_23_56_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Sat_Aug_10_13_23_56_2024.log](https://github.com/user-attachments/files/16570444/debug-Sat_Aug_10_13_23_56_2024.log)
[debug-Sat_Aug_10_13_23_56_2024.log](https://github.com/user-attachments/files/16570445/debug-Sat_Aug_10_13_23_56_2024.log)

**Comment by cagnulein** [comment]
Log checked: Qz is following the request of the app that you have connect to it (ZWift?) For example at the end i'm seeing request of 305W!
So i guess you have the FTP wrong in that app (Zwift or mywhoosh or anything else)
Let me know

**Comment by dan1282** [comment]
Roberto- 305 is correct. I have my ftp set around 250 now. There are other intervals of that earlier in the workout. As I ride through those earlier ones there is no problem keeping a decent cadence but where I stopped the workout, I could barely turn the cranks even if I stood up. I even tried to push through it and generated over 500 watts and the resistance still did not back off. This is not the behavior I see up until that point

**Comment by cagnulein** [comment]
The bike is handling directly the wattage, qz is just sending it. I guess
your ftp is too high?
Try first with a lower ftp, as I said qz is just a man on the middle in
this case, so it's sending only the requests.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 ago 2024 alle 20:39 dan1282 ***@***.***> ha
scritto:

**Comment by dan1282** [comment]
Hmm…ok maybe it’s an issue with the bike then. I can’t imagine changing the ftp would make that much of a difference especially since i have no problem pedaling at 305 watts earlier in the workout. Maybe it gets stuck at max resistance

**Comment by dan1282** [comment]
So I was reading that zwift should go into “bailout mode” if you stop pedaling in a workout. That definitely isn’t happening either. I didn’t do a spindown calibration so I’ll give that a shot I guess.

**Comment by dan1282** [comment]
I made a few changes and I’ve at least completed one workout with no problem:
Zwift resistance offset - changed from 18 to 2. I’ve messed around with this before so who knows.
Zwift resistance gain - changed from default to .8. This is based on your suggestion for the tdf at some point.
OS running zwift: went from iPad to windows pc. No idea of this would have any affect. It’s worth noting that the Bluetooth connection originally would say iPhone when using the iPad but on windows says wahoo or QZ… oh well at the end of the day, ERG now appears to be properly working and I have a larger screen. Win win!

**Comment by cagnulein** [comment]
Glad it worked!
for sure the issue was the calibration, zwift resistance offset are not
applied on erg mode.

Il giorno dom 11 ago 2024 alle 06:05 dan1282 ***@***.***> ha
scritto:

**Comment by dan1282** [comment]
I actually never had a chance to run the calibration so I guess there was something with my IPad? Sent from my iPhoneOn Aug 11, 2024, at 1:29 AM, Roberto Viola ***@***.***> wrote:﻿
Glad it worked!

for sure the issue was the calibration, zwift resistance offset are not

applied on erg mode.



Il giorno dom 11 ago 2024 alle 06:05 dan1282 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
no as i said qz is only sending the target, maybe you just reboot the bike?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 ago 2024 alle 11:23 dan1282 ***@***.***> ha
scritto:

**Comment by dan1282** [comment]
Yea I get what you’re saying. Gotta somehow be on the bike end but I have reset the bike a few times. I had it happen again in the middle of a workout tonight but was able to sort of reset it by manually pulling back the yellow magnetic resistance thing. Funny part is, it still didn’t really reduce resistance until it went into the next wattage change. One other thought- on the tdf you say keep it on the main screen for erg mode. Does it matter if the screen saver or whatever appears? It’s like a finger print that says tap here to start. I’ve seen it go to that screen occasionally during a workout but can’t say one way or another if it affects anything. 

I’ll look at the resistance mechanism again but I think it’s just a servo so not like there’s anything that should need oil

**Comment by cagnulein** [comment]
the screensaver doesn't affect the behavior at all.
the fact that you are saying that when it receives a new target wattage it
resets it, it means that we can do something to reset it
Let me know how it goes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 04:39 dan1282 ***@***.***> ha
scritto:

**Comment by dan1282** [comment]
I can’t say for sure that’s what triggered it but after giving rouvy a shot this evening, I think I’m switching over. I found their control over resistance to be much more stable than my experience with zwift (and I know this has nothing to do with your app). I also prefer the realism of their rides as well. If I find resistance issues with rouvy I will try and narrow it down so that if there is something on your end, I can help you pinpoint it.

**Comment by cagnulein** [comment]
Sounds good, thanks!


Il giorno mer 14 ago 2024 alle 04:16 dan1282 ***@***.***> ha
scritto:
