### ISSUE TITLE
[BUG] Peloton Bike+ Debug Logs : Just Ride Recording is not capturing data

### ISSUE THREAD

**Issue by rellimmot** [cagnulein/qdomyos-zwift#2509]
**Describe the bug**
Just Ride Recording is not capturing data. I have been able to connect the Bike+ to Zwift in the past using QZ.
QZ is able to see that a Just Ride is going, it will detect and connect to it, however it will not capture any data from the screen.
I do allow the Cast Screen when I am prompted when the software is open.

**To Reproduce**
(All app switching is done through the Android Settings Menu -> Apps since I can't get a launcher to work on the Peloton)
Open QZ, allow Cast Screen
Open Peloton, Just Ride, Start riding
Open QZ, now it detects the Just Ride and prompts to connect, I allow the connection
"01/01/70 Just Ride" shows as the title in QZ Fitness app
I'll switch back to Peloton app, or leave on QZ, sometimes  I open the QZ mini-viewer and it does overlay in the Peloton app.
All 0's for all fields (except the clock).
I have also in the past been able to connect the Peloton to Zwift running on a separate tablet over Bluetooth, and the sensors will populate but they will show 0's for watts and cadence.

**Expected behavior**
I expect QZ to gather the workout data.

**Screenshots**
See the screenshots in the Facebook group dated June 28
![449314646_10163565058839465_1605343040981261224_n](https://github.com/user-attachments/assets/174d96da-d02c-455d-9935-3fb96772421b)
![449307149_10163565072489465_349354475751509998_n](https://github.com/user-attachments/assets/409800b0-d7d4-456f-8fd3-f9155c120bd5)
![449511786_10163565064689465_2049219796439054796_n](https://github.com/user-attachments/assets/5ebd24b5-9b8d-4296-aa1e-a581adb4c028)
![449313325_10163565070549465_3809688150975768113_n](https://github.com/user-attachments/assets/1102827b-e26e-480f-9daf-3bfb98426d97)
![449598622_10163565069074465_5500602184867328278_n](https://github.com/user-attachments/assets/f1b6de83-8b55-436b-8bab-aa4093fc58bb)

**Peloton:**
Model: PLTN-TTR01
Touch FW: 5.1.0.12.ff.ff.ff.ff
Sensor FW Version: 5.4
Android Version: 10
Build Number: QT.231113.A release-keys
Android Security Patch Level: February 5, 2023
Kernel Version: 4.9.227-perf+  #1 Mon Nov 13 16:56:08 EST 2023

**Smartphone:**
 - Device: Samsung Galaxy Tab 8 Ultra
 - Android Version 14
 

**Append a debug log**

[debug-Sat_Aug_10_15_42_59_2024.log](https://github.com/user-attachments/files/16571015/debug-Sat_Aug_10_15_42_59_2024.log)
[debug-Sat_Aug_10_15_43_35_2024.log](https://github.com/user-attachments/files/16571016/debug-Sat_Aug_10_15_43_35_2024.log)
[debug-Sat_Aug_10_15_59_05_2024.log](https://github.com/user-attachments/files/16571018/debug-Sat_Aug_10_15_59_05_2024.log)
[debug-Sat_Aug_10_16_04_31_2024.log](https://github.com/user-attachments/files/16571020/debug-Sat_Aug_10_16_04_31_2024.log)
[debug-Sat_Aug_10_16_09_51_2024.log](https://github.com/user-attachments/files/16571021/debug-Sat_Aug_10_16_09_51_2024.log)
[debug-Sat_Aug_10_16_21_36_2024.log](https://github.com/user-attachments/files/16571022/debug-Sat_Aug_10_16_21_36_2024.log)
[debug-Sat_Aug_10_16_21_51_2024.log](https://github.com/user-attachments/files/16571023/debug-Sat_Aug_10_16_21_51_2024.log)
[debug-Sat_Aug_10_16_25_35_2024.log](https://github.com/user-attachments/files/16571024/debug-Sat_Aug_10_16_25_35_2024.log)
[debug-Sat_Aug_10_16_28_43_2024.log](https://github.com/user-attachments/files/16571025/debug-Sat_Aug_10_16_28_43_2024.log)
[debug-Sat_Aug_10_16_29_50_2024.log](https://github.com/user-attachments/files/16571026/debug-Sat_Aug_10_16_29_50_2024.log)
[debug-Sat_Aug_10_16_35_24_2024.log](https://github.com/user-attachments/files/16571027/debug-Sat_Aug_10_16_35_24_2024.log)
[debug-Sat_Aug_10_16_37_34_2024.log](https://github.com/user-attachments/files/16571028/debug-Sat_Aug_10_16_37_34_2024.log)

**Additional context**
I tried a few different configurations in the Experimental/Peloton/Advanced settings, hence the slew of debug files.
Thanks for the patience, it's been a bear trying to get these files made and pulled via adb with work/time/hardware/things just not talking. Turns out in order to get adb to connect to the Peloton either I plug it in and wait a long time or there's some services I can force close on the Peloton that make it connect to adb more reliably. 

Oh hey also the QZ app says Trial time expired! And closes even though I joined the Patreon QZ Membership (rellimmot@gmail.com)

Cheers

**Comment by cagnulein** [comment]
i unlocked the full version

add this email in the email setting all lowercase

***@***.***

i will check the debug log later: i'm in vacation for the next 15 days so i
will be slower than usual :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 ago 2024 alle 00:18 Thom ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @rellimmot there is major issue :)
you have to install this on the bike https://github.com/cagnulein/qzcompanionocr
and the qz app on your phone.
Use adb logcat to check if the qz companion is doing its job. With the last user I interrupted the development 1 year ago, so we have to resume this now
Let me know

**Comment by cagnulein** [comment]
@rellimmot any news?

**Comment by cagnulein** [comment]
@rellimmot Any news?
