### ISSUE TITLE
Treadmill incline multiplied on QZ output [BUG]

### ISSUE THREAD

**Issue by OctaviusBo** [cagnulein/qdomyos-zwift#2511]
As reported on Facebook, when using the latest QZ beta via Bluetooth connection with BH Fitness treadmill, manually adjusting incline by 1% causes QZ to display incline changes approx 6.5 times greater. Log attached. Thanks 🙂
[inbound5551479541375738472.txt](https://github.com/user-attachments/files/16602682/inbound5551479541375738472.txt)

**Comment by cagnulein** [comment]
Thanks, I'm running, I will check it later

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 18:41 OctaviusBo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@OctaviusBo I don't see any inclination  changing in the log. I need a file where you are changing it even manually thanks.

**Comment by OctaviusBo** [comment]
Hmmm, that's strange. I made several incline adjustments with the manual treadmill controls which were shown as changes in the app. I'll try again.

-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 13/08/2024 18:16 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


@OctaviusBo<https://github.com/OctaviusBo> I don't see any inclination changing in the log. I need a file where you are changing it even manually thanks.

**Comment by cagnulein** [comment]
Checked it again, no changes. Maybe you have several debug logs and so you
have to send all of them?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 19:30 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
It generated a BIN file originally which GitHub wouldn't accept so I changed it to .txt. perhaps it's truncated the data. I've attached the original.


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 13/08/2024 18:32 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


Checked it again, no changes. Maybe you have several debug logs and so you
have to send all of them?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 19:30 OctaviusBo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
you have to attach on the github web  interface directly otherwise I can't
see it. Also zip it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 19:35 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
[Log.zip](https://github.com/user-attachments/files/16603369/Log.zip)

**Comment by cagnulein** [comment]
Same thing, I suggest to collect a new one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 19:46 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
[debug-Tue_Aug_13_20_22_19_2024.zip](https://github.com/user-attachments/files/16604593/debug-Tue_Aug_13_20_22_19_2024.zip)

**Comment by cagnulein** [comment]
i see the inclination went from 0 to 6 but i don't see any event from the qz app to the treadmill. are you pressing the plus button on the inclination tile? or something else?

**Comment by OctaviusBo** [comment]
I've not used the app to adjust the incline, just the physical buttons on the treadmill. The jump from 0 to 6 was only one press on the treadmill button which should only equate to 1% incline. Is the data which says "6" being sent from the treadmill or is it how QZ calculates the information?

I've tried separately to use QZ buttons to control incline which also had problems but I'll send a separate log file for that.

-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 13/08/2024 21:04 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


i see the inclination went from 0 to 6 but i don't see any event from the qz app to the treadmill. are you pressing the plus button on the inclination tile? or something else?

**Comment by cagnulein** [comment]
so your treadmill sends indeed 6.5% inclinations each time, so it eeems a
bug of the treadmill that we can fix.
please provide also a log where you are using the qz inclination tile
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 ago 2024 alle 22:13 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
[debug-Wed_Aug_14_19_38_24_2024.log](https://github.com/user-attachments/files/16617598/debug-Wed_Aug_14_19_38_24_2024.log)
Here's the log of my test using the QZ Incline button to adjust incline. One press shows incline of 6 on QZ, a second press then jumps to 46! The treadmill responds but I don't know exactly how much it's increasing as it doesn't display stats on the treadmill screen when Bluetooth connected. It seems to be trying to extend to it's maximum incline.

**Comment by cagnulein** [comment]
ok i will do a patch for your treadmill in the next days. anyway you should
contact the manufacturer also, its a bug of its firmware

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 20:48 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
Thanks Roberto. I've sent them a message.

-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 14/08/2024 19:56 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


ok i will do a patch for your treadmill in the next days. anyway you should
contact the manufacturer also, its a bug of its firmware

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 20:48 OctaviusBo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@OctaviusBo one last thing to maps all the inclinations levels: collect a debug log where, from the treadmill directly, you are changing the inclination to all the levels, one by one, paused with 3 seconds between each others. it's important to do all the inclination steps so i can map them correctly.
thanks

**Comment by cagnulein** [comment]
@OctaviusBo by the way, is this your treadmill https://github.com/cagnulein/qdomyos-zwift/issues/1606 ?

**Comment by OctaviusBo** [comment]
I can map the incline levels this evening and send them over. That must be a treadmill from the same company. The iConcept 3.0 FTMS badge is the same. My model is the RS1000.

**Comment by cagnulein** [comment]
ok if you want i can invite here the other user to double check if its inclination levels have the same issues

**Comment by OctaviusBo** [comment]
Sure, it would be interesting to see.

**Comment by cagnulein** [comment]
done, let's see if he pings me back

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 11:15 OctaviusBo ***@***.***>
ha scritto:

**Comment by OctaviusBo** [comment]
Just recorded a log for the full range of incline settings. I think they've configured the incline output as a percentage relative to the treadmill maximum of 15 stages. 15% incline outputs as 100 which means each step is 6.6667 (100/15). Hope that makes sense!
[debug-Thu_Aug_15_18_30_13_2024.log](https://github.com/user-attachments/files/16628414/debug-Thu_Aug_15_18_30_13_2024.log)

**Comment by cagnulein** [comment]
Great! I will check it ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 20:00 OctaviusBo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
sent a new one! let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle ore 20:25 cagnulein ***@***.***> ha
scritto:

**Comment by OctaviusBo** [comment]
Amazing! Thank you. I will try it later.


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 16/08/2024 06:26 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


sent a new one! let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle ore 20:25 cagnulein ***@***.***> ha
scritto:

**Comment by OctaviusBo** [comment]
Hi! Thanks for patching so quickly. Just tested the beta, log attached.
I increased incline step by step and or seems to mostly work well but only on certain incline settings. On others it drops back to zero. Hope the log highlights this better but let me know if you need more detail!
[debug-Sat_Aug_17_17_50_00_2024.log](https://github.com/user-attachments/files/16645938/debug-Sat_Aug_17_17_50_00_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 ago 2024 alle 20:18 OctaviusBo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i'm sending you a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 ago 2024 alle ore 20:50 cagnulein ***@***.***> ha
scritto:

**Comment by OctaviusBo** [comment]
Amazing. Thank you.


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 18/08/2024 12:53 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


i'm sending you a new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 ago 2024 alle ore 20:50 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
sent!

**Comment by OctaviusBo** [comment]
Perfect! Works great. Just need to try a real workout now.

**Comment by cagnulein** [comment]
Great! Let me know!

**Comment by cagnulein** [comment]
that's great!

**Comment by cagnulein** [comment]
ProAction Nydo (BH Fitness) threadmill doesent incline

[debug-tirs__dec__10_20_44_11_2024.log](https://github.com/user-attachments/files/18092217/debug-tirs__dec__10_20_44_11_2024.log)

**Comment by cagnulein** [comment]
@OctaviusBo are you still using the app? could you please tell me which specific model of the treadmill do you have?

**Comment by OctaviusBo** [comment]
Hi Roberto,

Yep, still using the app regularly thanks although mostly on the bike. Works well will treadmill though (wish the treadmill accepted speed commands though!)

The model is BH Fitness RS1000. https://bhfitness.com/en/cintas-correr/rs1000/

Hope that helps.


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 26/01/2025 16:22 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)


@OctaviusBo<https://github.com/OctaviusBo> are you still using the app? could you please tell me which specific model of the treadmill do you have?

**Comment by cagnulein** [comment]
thanks @OctaviusBo

**Comment by cagnulein** [comment]
hi @OctaviusBo since this modification was conflicting with the #3839 i added a setting to enable this. it's under the iconsole options in the next version. Let me know if you are interested to try it

**Comment by OctaviusBo** [comment]
Sure, I'll take a look. Thank you


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 05/11/2025 08:40 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)

[https://avatars.githubusercontent.com/u/48216?s=20&v=4]cagnulein left a comment (cagnulein/qdomyos-zwift#2511)<https://github.com/cagnulein/qdomyos-zwift/issues/2511#issuecomment-3489954334>

hi @OctaviusBo<https://github.com/OctaviusBo> since this modification was conflicting with the #3839<https://github.com/cagnulein/qdomyos-zwift/issues/3839> i added a setting to enable this. it's under the iconsole options in the next version. Let me know if you are interested to try it

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by OctaviusBo** [comment]
Not sure if it's related but went to use the treadmill today with latest update of QZ and it doesn't seem to connect with Bluetooth anymore.


-------- Original message --------
From: Roberto Viola ***@***.***>
Date: 05/11/2025 08:59 (GMT+00:00)
To: cagnulein/qdomyos-zwift ***@***.***>
Cc: OctaviusBo ***@***.***>, Mention ***@***.***>
Subject: Re: [cagnulein/qdomyos-zwift] Treadmill incline multiplied on QZ output [BUG] (Issue #2511)

[https://avatars.githubusercontent.com/u/48216?s=20&v=4]cagnulein left a comment (cagnulein/qdomyos-zwift#2511)<https://github.com/cagnulein/qdomyos-zwift/issues/2511#issuecomment-3490018348>

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
latest update? did you receive an update? share a debug log and I will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

It shouldn't be releated

**Comment by OctaviusBo** [comment]
Hi Roberto,
Have you implemented this modification to the incline fix as I notice it's now reading incorrectly again on Android. You mentioned a new setting to enable this fix again?

**Comment by cagnulein** [comment]
@OctaviusBo Do you see the balloon on the startup of qz saying workaround is enabled?

**Comment by cagnulein** [comment]
The setting iconcept_ftms_treadmill_inclination_table is still enabled?

**Comment by OctaviusBo** [comment]
Sorry, I'm not really sure. It's just reverted back to displaying the incline in QZ as 6.5% increments as per the original problem before the fix. Have you now added it as an optional setting I need to enable?

**Comment by cagnulein** [comment]
yes this one under iconsole settings 

![image](https://github.com/user-attachments/assets/88520179-9c8c-4c94-94f4-a95e5207881a)

**Comment by OctaviusBo** [comment]
Perfect. I'll try. Thank you
