### ISSUE TITLE
Cannot Get Windows Version To Display HR

### ISSUE THREAD

**Issue by Middy2000** [cagnulein/qdomyos-zwift#2512]
[debug-Wed_Aug_14_08_42_33_2024.zip](https://github.com/user-attachments/files/16611089/debug-Wed_Aug_14_08_42_33_2024.zip)
Hi Roberto,

I will start with an apology as it's likely I have changed something to cause this issue.

Now the windows version of QZ is working perfectly I decided to setup the PID Heart rate feature that I had used on Android.  I copied the settings from my phone to Windows and tested it and it worked.

However now QZ will not display HR.  On the log it is detecting HR but not displaying it on the tiles.  

The procedure is I start QZ companion on my watch.  I then pair my watch to the treadmill as otherwise QZ displays the treadmill heart rate of the hand sensors and not my watch.  This normally worked fine.  However now nothing.  

I am not sure if I should set QZ Heart rate device to Fenix 6 or disabled etc...  On my phone it was Fenix 6.  
Before I changed QZ settings for PID on Windows it was disabled.  

Should I have left it disabled?

**Comment by cagnulein** [comment]
Hi, I saw that you were in pause mode the whole time in qz. Did you try to
press start?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 11:55 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Yes, normally I get the display even when paused.  I know the PID function will not work until I press start. 
I've made that mistake before! 🤣

**Comment by cagnulein** [comment]
Ok I will check the log later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 12:33 Middy2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I guess your watch is connected directly to the treadmill and qz is taking the HR from the treadmill so set the heart rate device to disabled. Actually it was writing 2 times the value (one from the treadmill and one with 0 from the "unreadable" watch)
Let me know

**Comment by Middy2000** [comment]
Before I changed the settings on Qz the following would happen.

Qz would detect the HR of the treadmill.  Then I would pair my watch and the HR on qz would change to the watch HR. 

Now QZ is not displaying the HR from treadmill or watch.
I would be happy if qz never showed HR from the treadmill as it is never accurate. 

To add more complication when I pair watch to Zwift I use ANT+ 
I guess QZ companion transmits the signal in Bt ?

**Comment by cagnulein** [comment]
in the log the hr was coming from the treadmill directly, so simply
disabling it on qz should works. did you try? same thing will be ok also on
android, it just works because of timing, but the correct settings are with
the hr disabled on qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 16:30 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
![Screenshot_20240814_184601](https://github.com/user-attachments/assets/4dd0145e-4d86-4d17-b0b6-664222c82054)

It was when I disabled HRM from machinery that everything stopped.  I'll check all the settings again.

The question is when I pair my treadmill to my watch is it then the treadmill that is then sending the data to qz?
The treadmill screen shows my watch hr when I pair it and forgets about its own sensor.

**Comment by cagnulein** [comment]
heart rate belt name setting must be set to disabled instead disable hrm from the machinery must be OFF.



> The question is when I pair my treadmill to my watch is it then the treadmill that is then sending the data to qz?

yes the treadmill collects the hr from the watch and it bridges to qz with its metrics.

try in this way

**Comment by Middy2000** [comment]
Ok. Will report back with results.

**Comment by Middy2000** [comment]
Happy to report things are back working.

It appears the issue is with the treadmill not maintaining the connecting to my watch in the background.  When you click away from the pairing screen it was dropping the connection.  

This is a known issue but previously hadn't affected me. 

Feel free to close this.

Thanks

**Comment by cagnulein** [comment]
ok maybe you want to use qz for hr unpairing it from the treadmill?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 11:10 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Ha, you are asking a lot there. I don't like to change things. I will have to learn which one of the options in Zwift works as when pairing my HR there is 4 or 5 options.

**Comment by cagnulein** [comment]
you can use the wahoo device in zwift from qz if you are pairing the watch
directly on qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 16:36 Middy2000 ***@***.***>
ha scritto:
