### ISSUE TITLE
Tour de France Bike won't connect to QZ

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#2513]
Hello, I hope you are doing well. I can not get my Tour de France bike to connect to QZ. I was trying to connect to IndieVelo this weekend and it would not. I thought it would help if I uninstalled the app and reinstalled it. The bike did connect to the app at that time. Now it does not. Thanks, Lonnie

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10+
 - OS: One UI version 4.1
 - Version 12

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-cas
[Debug log 8_14_2024.txt](https://github.com/user-attachments/files/16614026/Debug.log.8_14_2024.txt)
e-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
are you using 2 devices: 1 for qz and 1 for indievelo?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 15:43 LDHig ***@***.***> ha
scritto:

**Comment by LDHig** [comment]
Hello Roberto, correct. I am using my phone for the QZ to connect to my bike and then using the phone to connect to indievelo. Currently my phone can not connect to my bike nor indievelo. Thanks, Lonnie 
    On Wednesday, August 14, 2024 at 09:51:21 AM EDT, Roberto Viola ***@***.***> wrote:   

 

are you using 2 devices: 1 for qz and 1 for indievelo?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 15:43 LDHig ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
you can't, indievelo doesn't support this.
you have to use your bike, qz on the phone connected to the bike and, for
example, a tablet for indievelo

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 15:55 LDHig ***@***.***> ha
scritto:

> Hello Roberto, correct. I am using my phone for the QZ to connect to my
> bike and then using the phone to connect to indievelo. Currently my phone
> can not connect to my bike nor indievelo. Thanks, Lonnie
> On Wednesday, August 14, 2024 at 09:51:21 AM EDT, Roberto Viola

**Comment by LDHig** [comment]
Sorry I forgot to add that I have the indievelo on my laptop. I use my phone as a bridge between my bike and my laptop. Sorry for not being clear on that.

**Comment by cagnulein** [comment]
so don't you see at all the qz device there? did you rename your android
phone to "bike" and reboot it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 16:01 LDHig ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@LDHig any news?
