### ISSUE TITLE
[BUG] resistance or speed isn’t increasing 

### ISSUE THREAD

**Issue by Dav359** [cagnulein/qdomyos-zwift#2514]
[new-touareg-brochure.pdf]
[debug-Wed_Aug_14_20_35_03_2024.log](https://github.com/user-attachments/files/16618269/debug-Wed_Aug_14_20_35_03_2024.log)
(https://github.com/user-attachments/files/16618249/new-touareg-brochure.pdf)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi, in this log I can't see any connections to your bike. I need a debug
log where the issue is present
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 21:53 Dav359 ***@***.***> ha
scritto:

**Comment by Dav359** [comment]
Roberto

I reset my app and resistance appears to work. However my speed isn’t showing on Swift as per the app.

Example: qdomyos app says 35 km/h
Zwift says 4 km/h

However wattage matched fine. I’ve got a debug log attached.

Thanks



On 15 Aug 2024, at 07:26, Roberto Viola ***@***.***> wrote:

﻿

Hi, in this log I can't see any connections to your bike. I need a debug
log where the issue is present
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 ago 2024 alle 21:53 Dav359 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
yes because zwift calculates the speed on its own based on the wattage. you can have a similar speed on qz too enabling the speed based on power setting in the bike setting. 

for increasing the speed on zwift you have to increase the resistance. does your bike has auto resistance?

**Comment by cagnulein** [comment]
@Dav359 any news?
