### ISSUE TITLE
[BUG] Pro-form Carbon E7 not connecting 

### ISSUE THREAD

**Issue by sanicki** [cagnulein/qdomyos-zwift#2515]
**Describe the bug**
QZ app on Android phone appears to connect to the QZ Companion app installed on a Pro-form Carbon E7 elliptical, but tiles show no readings and do not control the elliptical.

**To Reproduce**
1. Complete steps on https://github.com/cagnulein/QZCompanionNordictrackTreadmill, using QZ Installation Method 2.
2. In QZ Companion app, select "Other" as equipment type

**Expected behavior**
Expected QZ tiles to display speed, incline, resistance, etc. of elliptical and to be able to control incline and resistance from QZ app.

**Screenshots**
![Screenshot_20240815_125610](https://github.com/user-attachments/assets/f13e18f5-c128-4ad2-9776-51a7af813712)
![Screenshot_20240815_125538](https://github.com/user-attachments/assets/68cedc5f-4752-4745-8fa7-e8428f818101)
![20240815_125412](https://github.com/user-attachments/assets/86f8f92e-a6da-4d9b-886c-80350d5f58cf)
![20240815_125441](https://github.com/user-attachments/assets/da699495-39a6-48e1-8795-d246dff2a93a)

**Desktop (please complete the following information):**
 - No desktop used

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Flip 6
 - OS: Android (One UI)
 - Version: 14 (6.1.1)

**Append a debug log**
[debug-Thu_Aug_15_12_55_04_2024.log](https://github.com/user-attachments/files/16629185/debug-Thu_Aug_15_12_55_04_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
there is a setup error: don't set the ip in the proform ip setting: remove
it completely from there and press ok. set it instead on the 2950 ip
setting and press ok and restart qz

if it still doesn't work send me a fresh debug log
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 20:49 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
Reinstalled QZ Companion app using QZ Installation Method 1 (from Windows 11.)

Moved IP as instructed and restarted QZ app.

Still nothing.

[debug-Thu_Aug_15_13_41_03_2024.log](https://github.com/user-attachments/files/16629626/debug-Thu_Aug_15_13_41_03_2024.log)

**Comment by cagnulein** [comment]
i still see the ip in the other setting

Thu Aug 15 13:41:04 2024 1723750864087 Debug: ../src/main.cpp int main(int,
char **) "proformtreadmillip" QVariant(QString, "192.168.1.72")

you have to complete remove it (no spaces or any character) and press ok
and restart qz

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 21:45 Scott Sanicki ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i'm going to bed soon, i will be back in 10 hours

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 21:47 cagnulein ***@***.***> ha
scritto:

**Comment by sanicki** [comment]
IP removed (my oversight -- missed the need for ok per line item.)

Elliptical incline now seen. Incline not adjustable in app. Speed not registering.

[debug-Thu_Aug_15_13_46_50_2024.log](https://github.com/user-attachments/files/16629702/debug-Thu_Aug_15_13_46_50_2024.log)

**Comment by cagnulein** [comment]
perfect! for the speed no problem, we can use the ratio between rpm and
distance to calculate it. i just need two different speed/cadence couple to
calculate it

for the inclination control i need a adb screenshot that you can take using
the adb screenshot batch file in the zip file

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 ago 2024 alle 21:54 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
> i just need two different speed/cadence couple to calculate it

Apologies. It is _only_ the Inclination reading that is displaying. No other tile displays any information.

> for the inclination control i need a adb screenshot that you can take using the adb screenshot batch file in the zip file

What screen do you need? When I used that bat I only got:

![Thu08-15-2024@14-24-51 19](https://github.com/user-attachments/assets/21dab047-0fa5-4214-adb5-cae14f29e278)

**Comment by cagnulein** [comment]
the adb screenshot is perfect but you need to enable the sliders in the ifit settings to change the inclination in that screen and so redo a screenshot.
let me know!

**Comment by cagnulein** [comment]
@sanicki i just pushed a new version handling all the metrics from this elliptical (inclination pending due to sliders missing in the screenshot). 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by sanicki** [comment]
![Fri08-16-2024@8-00-36 11](https://github.com/user-attachments/assets/b507c9aa-a303-4c59-acec-6b894a0b2ebe)

Better? Sending email now.

**Comment by cagnulein** [comment]
yes better thanks!
i will add it in the next days!
for instead the qz version , 
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10414985767/artifacts/1818779341

**Comment by sanicki** [comment]
Readings seem to be working!

![Screenshot_20240816_083551](https://github.com/user-attachments/assets/507b6d7c-a25e-494a-ac5f-8d5434c513dc)

Adjustments attempted in the phone app do not appear to work, but may be because the companion app is expanding the notification window?

**Comment by cagnulein** [comment]
yes i need to add your specific carbon device to
the companion, i will try to do later today!

**Comment by cagnulein** [comment]
remember then you have to
stay in the manual window with the slider bar to have it working correctly

**Comment by sanicki** [comment]
> remember then you have to stay in the manual window with the slider bar to have it working correctly

The screenshot I added above shows the layout iFit switches to when I start the phone app while iFit is in manual workout with the sliders present.

**Comment by cagnulein** [comment]
yeah i said so because i saw this screenshot 
![image](https://github.com/user-attachments/assets/8f2ce2b9-9cf9-4ec7-8480-6744e1f29c21)
i would like to be sure that you got that you have to stay in the manual workout when you will receive the new companion app

**Comment by sanicki** [comment]
Understood. I think that the current companion app switched screens due to the same touch misalignment that is lowering the notification window.

Oh, also FYI in the beta phone app: Since I need to enter the companion app IP I had to skip the new setup wizard, but skipping it seems to  cause the wizard to launch again the next time the app is started.

**Comment by cagnulein** [comment]
hah yes i have to fix this, thanks for the reminder!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 ago 2024 alle 17:24 Scott Sanicki ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@sanicki done
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.7/QZCompanionNordictrackTreadmill.apk

select the new e7 elliptical device in the companion. let me know!

**Comment by sanicki** [comment]
The phone app is now reading everything correctly, except Heart Rate (from the built-in HR monitor) and Fan Speed. Neither of those are particularly important to me, because I'll be relying on my watch for heart rate and don't need to monitor or control the fan from my phone.

Equipment adjustments attempted in the phone app still do not appear to do anything. I also tried using a GPX, but I wasn't able to select one in the beta phone app. (It had worked in the prod version.)

**Comment by cagnulein** [comment]
> The phone app is now reading everything correctly, except Heart Rate (from the built-in HR monitor) and Fan Speed. Neither of those are particularly important to me, because I'll be relying on my watch for heart rate and don't need to monitor or control the fan from my phone.

Yeah unfortunately it seems to doesn't log them, so I can't show them .

> 
> 
> 
> Equipment adjustments attempted in the phone app still do not appear to do anything. 

do you see a random touch as you saw before? or nothing? you have to use the inclination tile to change it 

> I also tried using a GPX, but I wasn't able to select one in the beta phone app. (It had worked in the prod version.)

what do you mean? what do you see?

**Comment by sanicki** [comment]
Sorry for the delay. I was AFK yesterday.

> do you see a random touch as you saw before? or nothing? you have to use the inclination tile to change it

Nothing. No change to elliptical settings when I'm pressing the -/+ in Inclination or Resistance in the phone app.

> what do you mean? what do you see?

I don't see file names, only partial folder names in the file picker. Selecting "Other folders" allows me to view the contents of other folders but does not let me pick the correct folder (worked in non-beta) or a GPX file.

![Screenshot_20240818_101647](https://github.com/user-attachments/assets/881e1ad9-f312-46dc-a2cd-0d9229c45126)

**Comment by cagnulein** [comment]
But when you selected other on the companion are you still see a wrong touch event or not anymore?

Are you on android 14? Delete the /documents/qz folder and restart qz and then  browse there to /documents/qz

**Comment by sanicki** [comment]
When I select "Other" on the Companion app I no longer see a wrong touch event. Pressing the -/+ in Inclination or Resistance in the phone app do not work when other is selected either.

When I exit the phone app the service appears to automatically restart, which causes touch events on the elliptical when it is no longer in workout mode. This causes the elliptical to lose Privileged mode. I don't believe this is the cause of the -/+ issue but figure I should mention it. I have to force close the app to stop the service from restarting.

I deleted that folder and now see the stock GPX files. So I was able to confirm that GPX maps also do not affect the workout Incline or Resistance.

**Comment by cagnulein** [comment]
I'm missing something : i thought you were able to see a wrong touch event
when you press the inclination tile on qz: how?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 23:47 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
> I'm missing something : i thought you were able to see a wrong touch event when you press the inclination tile on qz: how?

No, I have not seen a wrong touch event since you provided the test companion app which includes the E7.

**Comment by cagnulein** [comment]
that's strange because if you set the "other" it should behaves like the
previous one. are you able to reinstall the previous just to confirm this?
we need a stable starting point
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 14:16 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
Can you please send me links to the versions you'd like me to revert to for:

1. The phone app (I have the 15 minute one from earlier in this thread currently installed)
2. The companion app (when I download from https://tinyurl.com/qz-companion it still lists the E7)
3. The watch app (I have the beta for Samsung currently installed)

I can't seem to locate the companion APK prior to the addition of my elliptical.

**Comment by cagnulein** [comment]
The one that I would like to revert is the companion only for now
You can find all of them here
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases
the previous one is
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.6/QZCompanionNordictrackTreadmill.apk


Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 19:51 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
👍 3.4.6 companion installed. No wrong touches with Other, though.

Maybe because of different phone app?

**Comment by cagnulein** [comment]
Ok so yes it could be the phone app.
So try this: reinstall back the latest companion and put back the ip on the
2950 treadmill ip blanking the elliptical one and check. if you see them
means that i did something wrong in the elliptical side, thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 20:10 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
It looks like the Google Play store version has been updated. I checked https://github.com/cagnulein/qdomyos-zwift/releases/ but it only has the July 2023 and nightly trial apks. Where can I get the previous release?

I don't know if this is useful but I turned on "Show taps" in Developer Mode on the elliptical and nothing displays when I tap the -/+ for Inclination or Resistance from the current phone app.

**Comment by sanicki** [comment]
Progress!

I realized that even though I had started the Companion app and selected Other, I needed to open it again in order for the ADB debugging request.

Once I did that, the Companion app began showing the wrong touches.

So I reinstalled the Companion app with the E7 and after manually starting the app twice (first to select E7, second to permit ADB) I was able to use -/+ to change Inclination.

But once I did, the workout zoomed in to the track-only and overlayed a screen with an option to full-screen.

**Comment by cagnulein** [comment]
i don't get the last phrase: what do you mean? you can't stay in the manual workout or the companion is sending faking touch that changes the screen?

**Comment by sanicki** [comment]
It looks like this:

![Fri08-16-2024@8-00-36 11](https://github.com/user-attachments/assets/b507c9aa-a303-4c59-acec-6b894a0b2ebe)

Until I tap + on the Inclination tile in the phone app, at which time the elliptical inclination changes but the screen displays:

![Mon08-19-2024@12-43-57 21](https://github.com/user-attachments/assets/92c17fa5-9eb6-4cc5-bda0-5a45ef374e94)

Then cycles back and forth between that and this every second or two:

![Mon08-19-2024@12-45-12 18](https://github.com/user-attachments/assets/be938035-766d-4eea-a24e-39454cb7a925)

**Comment by cagnulein** [comment]
ok so it means that it's a coordinates issue. are you able to collect a adb logcat while you are doing this experiment?

**Comment by sanicki** [comment]
Not sure if this worked, but...

[logcat.txt](https://github.com/user-attachments/files/16664333/logcat.txt)

**Comment by cagnulein** [comment]
yes it worked thanks. did you change the resistance tile on qz on this right? change instead the inclination, it should be fine then

**Comment by sanicki** [comment]
It was definitely Inclination that I was able to change with the tile, but I may have tried both. (If Resistance changed I may not have noticed.)

**Comment by cagnulein** [comment]
i'm going to bed now, if you can collect a fresh adb log with only the inclination i will check it. anyway we are very near! have a nice evening!

**Comment by cagnulein** [comment]
hi @sanicki any news?

**Comment by sanicki** [comment]
Sorry for the extremely long delay. Here is a new logcat where I unsuccessfully attempted to control inclination and resistance from the phone app.

[logcat.txt](https://github.com/user-attachments/files/16985516/logcat.txt)

**Comment by cagnulein** [comment]
i got the issue, QZ (on the version that you are trying now and with the configuration that you have) is sending resistance instead of inclination. so in order to understand the setup issue i need also a debug log from qz, https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

let me know! we are very near!

**Comment by sanicki** [comment]
Attempted + Inclination for first 20 seconds, then switched to + Resistance. No effect using either.

[debug-Fri_Sep_13_07_52_22_2024.log](https://github.com/user-attachments/files/16994963/debug-Fri_Sep_13_07_52_22_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 16:03 Scott Sanicki ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Got the issue, disable the adb remote setting and restart qz

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 16:29 cagnulein ***@***.***> ha
scritto:

**Comment by sanicki** [comment]
That appears to have returned us to the potential [incorrect coordinates issue](https://github.com/cagnulein/qdomyos-zwift/issues/2515#issuecomment-2297223931).

**Comment by cagnulein** [comment]
i will investigate it in the next week, after the break i have to resume the whole topic :)

**Comment by cagnulein** [comment]
ok new build with the companion with the fix hopefully https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.15/QZCompanionNordictrackTreadmill.apk

let me know!

**Comment by sanicki** [comment]
Inclination ✅  Working!
Resistance ❌ Not working.

**Comment by cagnulein** [comment]
Perfect! Yes it's how supposed to! I mean inclination also affect the resistance, isn't it?

**Comment by sanicki** [comment]
No, Inclination and Resistance are two separate controls. They have to be used together to have significant impact on the exercise. For example, hill climbing at maximum Inclination is laughably easy until combined with significant Resistance.

Is it possible for the QZ app to increase and decrease Resistance remotely, or is it currently only possible to read Resistance because the touch interface is limited to only controlling Inclination?

**Comment by cagnulein** [comment]
Qz can control both but the question is when it should. I mean manually it can change both, but automatically, from zwift for example, how does it should combine them?

**Comment by sanicki** [comment]
I'm not sure I understand what you're asking.

In a Manual workout, I can change the Inclination and Resistance settings independently on the elliptical. Those settings are read and displayed by the QZ app on my phone. I can now also use the Inclination tile +/- buttons in the QZ app to modify the elliptical Inclination, but using the +/- buttons in the Resistance tile has no effect on the elliptical.

It should though, right?

**Comment by cagnulein** [comment]
yes i know this :)
I can replicate manual changes in QZ too. But which is the purpose of this? I mean how would you like to use qz? QZ standalone? or with zwift?

**Comment by sanicki** [comment]
I mostly want to use QZ with GPX which I create.

However I would like to also be able to manually adjust Inclination or Resistance.

For example, I am section hiking the Arizona Trail. I would like to use a GPX of a portion of the trail, but be able to increase the Inclination or Resistance on the fly if the track doesn't seem as difficult as the trail IRL.

**Comment by cagnulein** [comment]
Ok got it, I will add it
Anyway other proform bikes have both inclination and resistance linked. Are
you 100% sure that at max inclination you don't have in the legs also the
max resistance?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 18:21 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
Yes, I'm sure. The elliptical controls for Inclination and Resistance are separate. Thanks.

**Comment by cagnulein** [comment]
Ok, thanks for the clarification.

I will add it in the next days

Il giorno lun 16 set 2024 alle 18:28 Scott Sanicki ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@sanicki done, this is the new companion https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.17/QZCompanionNordictrackTreadmill.apk

**Comment by sanicki** [comment]
We're getting closer.

Resistance is being controlled by the QZ phone app. However pressing +/- has no effect. The resistance just automatically increases by 2 every second.

**Comment by cagnulein** [comment]
Can you share a log? That's so strange!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 17 set 2024 alle 18:00 Scott Sanicki ***@***.***>
ha scritto:

**Comment by sanicki** [comment]
First attempt here it raised Resistance by 1 then stopped. Trying to adjust Resistance in the app had no effect. Second attempt shows Resistance being adjusted by 1 to max with no human interaction with the app.

[logcat.txt](https://github.com/user-attachments/files/17062133/logcat.txt)

**Comment by cagnulein** [comment]
@sanicki ok the problem is that ifit doesn't log the current resistance to the log, that's why you were saying this.
A way to achieve this, it's trying my new approach based on OCR instead of reading the log. This is will record the bike's screen, getting the information from the manual workout and sending it back to qz.
You can try it downloading this one  https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10956268294/artifacts/1957277921

It's a huge change from the previous one so we would try to check that everything still work.
Let me know!

**Comment by sanicki** [comment]
Unfortunately that didn't seem to work.

Appeared to not read any stats. Resistance and Inclination +/-  in app appeared to have no effect, though Resistance did + seemingly on its own.

**Comment by cagnulein** [comment]
please append a debug log so i can check it

did you grant the permission to record the screen?

**Comment by sanicki** [comment]
Sorry again for the delay. Was out of town for a bit.

Yes. Permission was granted.

[logcat.txt](https://github.com/user-attachments/files/17235903/logcat.txt)

**Comment by cagnulein** [comment]
@sanicki it could be something similar to https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/114#issuecomment-2388892630
could you try to do the same steps?
we have to see some OCR lines in the logcat if it's working

**Comment by sanicki** [comment]
No effect.

I'm going to be leaving this location for a few months, so have reverted to [this partially-working version](https://github.com/cagnulein/qdomyos-zwift/issues/2515#issuecomment-2351618908) but may re-open this issue when I return.

Thanks for all the assistance!

**Comment by cagnulein** [comment]
Ok I'm here to help you in case! Let me know
