### ISSUE TITLE
QZ fitness and virtual shifting

### ISSUE THREAD

**Issue by khawks** [cagnulein/qdomyos-zwift#2516]
Hello:
I have a kickr v5 using direct connect, windows pc that both are hardwired ethernet, i also have an android phone and purchased a zwift clicker in anticipation of wahoo implementing virtual shifting for the v5. when wahoo announced they were not pursueing this i purchased your QZ fitneess app on google play. 
the only feature i am trying to implement is virtual shifting with either the zwift clicker or using my android phone.
I do have a bluetooth dongle that i am not using that i could put into my PC if needed.
could you please send me steps on how to do this?

Thank You
Kirk Hawks

**Comment by cagnulein** [comment]
hi @khawks first are: download the qz app on your pc https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip

unzip it
close zwift and run it
it should connect straightaway to your trainer if the bluetooth dongle works

also you can recall back the wizard back from the left side bar to enable the zwift click/play controller 

also if you want you can do these steps from your phone too
let me know!

**Comment by cagnulein** [comment]
@khawks any news?
