### ISSUE TITLE
Incline Fluctuating

### ISSUE THREAD

**Issue by Middy2000** [cagnulein/qdomyos-zwift#2518]
[debug-Fri_Aug_16_08_40_02_2024.zip](https://github.com/user-attachments/files/16635362/debug-Fri_Aug_16_08_40_02_2024.zip)

Hi Roberto,

Have a look at this to see whats happening.

It's noticeable around 0924hrs onwards.

The gradient kept changing to 0 every poll.  The course was an 8% gradient but qz/treadmill kept going 8% then 0% then 8%.

It did this the entire session, whenver there was a gradient it would go to 0% each poll.

I only ever saw this happen once on a new road that Zwift released but I believed it was the road rather than an issue.

The route I ran today I run every Friday and this never happened before.

**Comment by cagnulein** [comment]
i will check it asap!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 ago 2024 alle 11:17 Middy2000 ***@***.***>
ha scritto:

**Comment by Middy2000** [comment]
Ok will check.

Do I not need treadmill auto inclination enabled if I'm running zwift and Qz on the same PC?

**Comment by cagnulein** [comment]
you need only the first auto inclination enabled, the one that say only for android or ios (in your case is also for pc :) )

**Comment by Middy2000** [comment]
Hi Roberto.

It's not happened again but only happened twice in hundreds of runs so hard to say it's 100% fixed.

But yes let's close it and if it happens again we'll revisit it.

**Comment by cagnulein** [comment]
Sounds good, thanks!


Il giorno gio 29 ago 2024 alle 18:01 Middy2000 ***@***.***>
ha scritto:
