### ISSUE TITLE
Virtual shifting not working

### ISSUE THREAD

**Issue by Kaowin32** [cagnulein/qdomyos-zwift#2519]
[debug-Fri_Aug_16_18_27_43_2024.log](https://github.com/user-attachments/files/16639814/debug-Fri_Aug_16_18_27_43_2024.log)

Trainer on, QZ app open. Trainer connects
Open Zwift app. Controllers on and connect (can’t connect to phone AND choose phone as controller). Choose phone as power source

app shows movement, but gears have no effect

**Comment by cagnulein** [comment]
hi @Kaowin32 i don't see the zwift play devices at all here. it means that or they already connected to zwift (you shouldn't !) or you didn't wake them up before opening qz

also where are you running zwift? on ios you can't run qz and zwift on the same iphone, you need 2 devices for this

let me know!

**Comment by Kaowin32** [comment]
Hey,So I have to open the companion app for them to connect to my phone. But if the ZC app is open, they won’t connect to Zwift running on my I’m running QZ on my phone, my Kickr 2018 and Zwift on my iPad ☺️I’ll try again with the controllers connect to my phone and NOT my iPad/Zwift. I did that yesterday and that didn’t work either though. I’ll try again!On 16 Aug 2024, at 19:05, Roberto Viola ***@***.***> wrote:﻿
hi @Kaowin32 i don't see the zwift play devices at all here. it means that or they already connected to zwift (you shouldn't !) or you didn't wake them up before opening qz
also where are you running zwift? on ios you can't run qz and zwift on the same iphone, you need 2 devices for this
let me know!

**Comment by cagnulein** [comment]
i don't understand; why you need ZC at all for this? you should

1. turn all the zwift and qz app down
2. wake up your trainer and zwift play
3. open qz and check that you can change gears with zwift play
4. open just zwift and pair the qz device with it. zwift must be running on
another device

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 ago 2024 alle 20:16 Kaowin32 ***@***.***> ha
scritto:

**Comment by Kaowin32** [comment]
Ha! Well what do you know, it worked that time! Maybe I was turning on the controllers after opening the appIt shifts though ☺️ I was expecting to see it on screen though, but it probably can’t do that?Is the amount of gears pressure sensitive? Looks like the smaller clicky button jumps 1, the orange bumpers jump anywhere between 5-15 depending on how hard I push On 16 Aug 2024, at 19:19, Roberto Viola ***@***.***> wrote:﻿
i don't understand; why you need ZC at all for this? you should



1. turn all the zwift and qz app down

2. wake up your trainer and zwift play

3. open qz and check that you can change gears with zwift play

4. open just zwift and pair the qz device with it. zwift must be running on

another device



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 16 ago 2024 alle 20:16 Kaowin32 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
sorry what  would you like to see on screen? that fact that you are connected to zwift play? i can add it, yes!

for the gears jump, just set the gears gain setting to 0.5 to avoid this

let me know!

**Comment by Kaowin32** [comment]
I think I was expected Zwift itself to think it was connected to the controllers, and have the gear you’re in on screen in the top left like this - so you can be in what gear you need without seeing the QZ appOn 16 Aug 2024, at 19:35, Roberto Viola ***@***.***> wrote:﻿
sorry what  would you like to see on screen? that fact that you are connected to zwift play? i can add it, yes!
for the gears jump, just set the gears gain setting to 0.5 to avoid this
let me know!

**Comment by cagnulein** [comment]
ah no this is not possible yet, maybe i can add a voice feedback on qz?

**Comment by cagnulein** [comment]
@Kaowin32 are we OK with this?
