### ISSUE TITLE
[BUG] Activating volume to change gears breaks app  

### ISSUE THREAD

**Issue by Pidge-byte** [cagnulein/qdomyos-zwift#2522]
**Describe the bug**
App recognises my Tacx Neo 2T and I can see data in the app while using it, for example in the cadence tile. 

When I activate the ‘volume to change gears’ feature and restart the app no data appears.

It states that the Tacx Neo is still found but there is no data in the tiles.

In addition, the volume does not change the gear value in the gears tile either. 

**To Reproduce**
1. Go to '.Settings > Advanced Settings'
2. Click on '.Volume to change gears'
3. Restart app
4. Trainer connects but no data in app

**Expected behavior**
Data in app and the ability to change gears using the volume buttons.

**Screenshots**
[debug-Sun_Aug_18_15_26_52_2024.log](https://github.com/user-attachments/files/16647299/debug-Sun_Aug_18_15_26_52_2024.log)

**Smartphone (please complete the following information):**
 - Device: iPhone14
 - iOS 17.5.1
 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok the main issue is that qz is connected to your other fitness device
FS-FAD8F5

to avoid this set your tacx to the manual device setting in the advanced
settings

let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 07:41 Pidge-byte ***@***.***>
ha scritto:

**Comment by Pidge-byte** [comment]
Thanks Roberto!This worked and now the volume adjusts the gears in the app.This doesn’t however change the resistance on my Tacx trainer? I have tested using the app only. The watts remain the same at the same cadence no matter what ‘gear’ it’s showing in the app. I also tested with Zwift and the watt and cadence show correct in Zwift but again, changing the ‘gear’ in the app doesn’t change the resistance on the trainer. I have tried with both auto-resistance enabled and disabled in the app.Any ideas?Thank you,GregOn 18 Aug 2024, at 15:44, Roberto Viola ***@***.***> wrote:﻿
ok the main issue is that qz is connected to your other fitness device

FS-FAD8F5



to avoid this set your tacx to the manual device setting in the advanced

settings



let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 18 ago 2024 alle 07:41 Pidge-byte ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
the gears works only with another app like zwift or mywhoosh for now: on
zwift did you pair on all the tiles qz? i guess that's the reason why you
don't see any changes
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 22:35 Pidge-byte ***@***.***>
ha scritto:
