### ISSUE TITLE
JTX Sprint 8 Auto-Incline Peloton

### ISSUE THREAD

**Issue by dannynixon83** [cagnulein/qdomyos-zwift#2523]
**Describe the bug**
Auto-Speed and Target speed working great. Can see metrics for Target Incline on tile - but incline not adjusting.

**To Reproduce**

**Expected behavior**
Tread matches the target incline tile.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android
 - Version: 13

**Append a debug log**
[debug-Sun_Aug_18_14_55_41_2024.zip](https://github.com/user-attachments/files/16649409/debug-Sun_Aug_18_14_55_41_2024.zip)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
log checked: are you you can change the inclination from the inclination
tile on qz? qz is sending inclination correctly in the log. are you able to
send me also where you are changing manually to compare them?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 16:56 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Thanks Roberto...unable to manually change the incline on the tile also.

**Comment by cagnulein** [comment]
ok so it means that it's blocked somehow. are you aware of an app that can
change the inclination from the app directly on your treadmill? maybe the
kinomap app? if so i can clone the behavior

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 17:11 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Right ok thank you, I'll have a look at Kinomap...only switched the tread on for the first time this afternoon. I'll signup for Kinomap now.

**Comment by cagnulein** [comment]
ok you can use the trial of kinomap to check this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 17:18 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
![20240818_165621](https://github.com/user-attachments/assets/c2f62062-2559-45e0-8053-729a47313b4b)
Roberto, kinomap allowing me to use the +/- button on the attached image to control the incline, works great. Auto incline working on the kinomap videos too.

**Comment by cagnulein** [comment]
that's great so i can mimic the same, are you able to follow this with kinomap? https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by dannynixon83** [comment]
Got down to Step regarding bug report but no notification appears...what's ABD?

**Comment by cagnulein** [comment]
Wait some minutes, it will appear then

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 18:14 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
[Dan.zip](https://github.com/user-attachments/files/16650067/Dan.zip)
Hopefully these are correct?

**Comment by cagnulein** [comment]
Perfect, I will check it ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 18:32 dannynixon83 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok note for me: JTX Fitness Sprint Treadmill setting under the toorx/iconsole settings
i have to do a patch for this, i will do in the next days

**Comment by cagnulein** [comment]
hah no wait you can do already. disable the treadmill from the ftms treadmill settings and press ok and then enable JTX Fitness Sprint Treadmill setting under the toorx/iconsole settings

Let me know

**Comment by dannynixon83** [comment]
Roberto that works on incline but disables the speed tile manually and auto-speed in the class! 😭

**Comment by cagnulein** [comment]
On kinomap did you also change speed?

**Comment by dannynixon83** [comment]
Speed wasn't an option to change through that kinoapp screen...

**Comment by cagnulein** [comment]
Ok so I guess they did an hybrid. I don't know if it's possible to have
both. I will try a patch on the next days but I can't promise that we will
have success, they did a bug on the firmware. Do you have any contact with
the manufacturer?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 21:00 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
No, no contact. So close, hopefully a patch might solve it! Thank you again for all your help this afternoon, really appreciate it Roberto.

**Comment by cagnulein** [comment]
Ok I will try something in the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 ago 2024 alle 21:07 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Perfect, thanks again. Enjoyed trying to troubleshoot it all this aft, learnt loads! 🤞 it's doable.

**Comment by cagnulein** [comment]
@dannynixon83 ok i did it. I did a lot of changes so it's possible that it wouldn't work at first.

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10449186879

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by dannynixon83** [comment]
Morning Roberto, wow wasn't expecting you to have it patched and ready for testing so quickly today. Thank you! I'll keep my eye out for the download at the bottom of the page.

**Comment by cagnulein** [comment]
new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/10449369565

**Comment by dannynixon83** [comment]
Roberto have downloaded, the app when connecting to the tread just crashes and closes.

**Comment by cagnulein** [comment]
create me a debug log, as i said i did a lot of changes (and i can test
them without the treadmill) so i need to see a log to understand if there
is any error
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 10:30 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Think I've missed creating the debug log, I removed the app, reinstalled and now it won't even connect to the treadmill.

**Comment by cagnulein** [comment]
reinstalled which one? the newer one? create a debug log so i can check it.
i can't help you without a debug log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 10:42 dannynixon83 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
remember to enable back the jtx spring setting and the debug log one

**Comment by dannynixon83** [comment]
Yes enabled the JTX sprint setting - created the debug log but I can't send it from my phone this morning. It won't let me share/zip do anything with it currently, nightmare.

**Comment by dannynixon83** [comment]
[debugstartup.zip](https://github.com/user-attachments/files/16658290/debugstartup.zip)

**Comment by cagnulein** [comment]
it doesn't connect because you didn't allow all the permissions to qz,
check on the app settings on the android settings. probably due to the
reinstall process

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 11:15 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
![Screenshot_20240819_102712_Permission controller](https://github.com/user-attachments/assets/a76aa83a-ccd3-444e-ad18-b8163cb76507)

**Comment by cagnulein** [comment]
got this issue, i'm fixing it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 11:34 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Thanks Roberto!

**Comment by cagnulein** [comment]
new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/10451650835

**Comment by dannynixon83** [comment]
Just tried the incline on the app with the +, that is working!

**Comment by dannynixon83** [comment]
[debugstoptreadinclineworking.zip](https://github.com/user-attachments/files/16659488/debugstoptreadinclineworking.zip)

**Comment by dannynixon83** [comment]
Also just tried with Peloton - when pressing start at 0:00 seconds on peloton countdown, it also stopped the tread.
[debugstoptread_pelotonstart.zip](https://github.com/user-attachments/files/16659545/debugstoptread_pelotonstart.zip)

**Comment by cagnulein** [comment]
let's try a different thing https://github.com/cagnulein/qdomyos-zwift/actions/runs/10452921170

**Comment by dannynixon83** [comment]
[debugstoptreadv2.zip](https://github.com/user-attachments/files/16660267/debugstoptreadv2.zip)

Same again - installed, connected, incline + working, speed + = tread stops.

**Comment by cagnulein** [comment]
ok so it means that we can't cross the 2 protocols unfortunately. i have to
try the brute force: this means that in the next build i will start a 256
tests automatically looking for a code that work. i will let you know when
its available.
if this will not work we don't have any other chances

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 14:37 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Thanks Roberto!

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10458818094
enable the debug log and the jtx as usual
what you will see in this one is that qz by itself will try to change the speed every 5 seconds. you will see a message after each request, it will try 255 times. so leave it running by itself. don't touch anything. if you will see the speed changing by itself would mean that we have a hit! let me know!

**Comment by dannynixon83** [comment]
👍Thanks Roberto, I'll wait for download and then get on it!

**Comment by cagnulein** [comment]
in the meantime: does jtx talk about a official app for their treadmills?

**Comment by dannynixon83** [comment]
Not sure it has its own stand alone app.
https://www.jtxfitness.com/running-apps-and-technology/
On their site but the write ups are quite dated now. 
Only bought the tread for the build quality really and hoped to get it working with QZ.

**Comment by cagnulein** [comment]
new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/10459118608

**Comment by dannynixon83** [comment]
It's running now - into 50s of bruteforce notification but no speed changes happening.

**Comment by cagnulein** [comment]
ok let's wait
i'm going to bed now
have a nice evening!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 ago 2024 alle 21:37 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
[debugstopbytrialnotification.zip](https://github.com/user-attachments/files/16664682/debugstopbytrialnotification.zip)

No worries - thanks. The trial notification stopped the brute force from running and the tread stopped.

**Comment by cagnulein** [comment]
argh sorry you were right, anyway i guess i had already an answer from the log and  i also did a small patch https://github.com/cagnulein/qdomyos-zwift/actions/runs/10465637210

send me your email to roberto.viola83 at gmail.com mentioning this and I will unlock the trial. thanks!

**Comment by dannynixon83** [comment]
Email sent...am I good to install and give it a go Roberto? Thanks

**Comment by cagnulein** [comment]
sorry i was running, yes you are good to go!
set also your email 
in the email settings in qz all lowercase to unlock it

**Comment by dannynixon83** [comment]
Incline straight upto 15% on starting, upto 50 bruteforce notifcations again and no speed changes, still at 1.0

**Comment by dannynixon83** [comment]
[debugbruteforcetest.zip](https://github.com/user-attachments/files/16673638/debugbruteforcetest.zip)

Does this mean all hope is lost?

**Comment by cagnulein** [comment]
not yet: i was checking kinomap and they have workout with speed changes for the treadmill that support this


https://github.com/user-attachments/assets/9c7409a4-8d01-4df0-a206-173bcc0fcb24

do you see the speed tag there?

**Comment by dannynixon83** [comment]
Yes, just tried. Pressing the +/- on the screen doesn't adjust the tread speed at all...

**Comment by cagnulein** [comment]
i just had a blast!
restore the play store version: use the treadmill in the ftms treadmill and
press ok AND set the incline step to 1 instead of 0.5
Let me know if it makes any difference!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 12:42 dannynixon83 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok i'm not surrendering 

new lead

in the tiles settings enable these

![image](https://github.com/user-attachments/assets/8bfdc1bc-189b-4166-89e6-b1e8dfeefb8a)

here you can enable inclination presets.

set them to values, 10, 20, 50 and 100 and try them. we just need that one of these moves so we will understand how it's implemented in the firmware 

this with the current version and settings.

in the meantime i suggest to open a dialogue with their support putting me in CC so we can discuss with them. basically we have to say that they are not standard about FTMS protocol and inclination 

let me know

**Comment by dannynixon83** [comment]
Thanks Roberto, you've lost me. Isn't the max value 15 = 15% incline or am I misunderstanding?
![Screenshot_20240820_142453](https://github.com/user-attachments/assets/320f6896-4bfb-43fd-b6ea-b119c4d9c3bd)

**Comment by cagnulein** [comment]
Yes if the treadmill would be standard, since it's not, we are trying to understand how crazy the developers were. So setting crazy values we are understanding if, for example, they are thinking instead of % in 1/100 of %

**Comment by dannynixon83** [comment]
![Screenshot_20240820_143605](https://github.com/user-attachments/assets/95a7893f-d01b-43d5-adfa-95a9ebcdf82a)

Like this then...

**Comment by cagnulein** [comment]
yes exactly

**Comment by cagnulein** [comment]
i don't see anything here, maybe it's the wrong log? anyway no changes? i
would like to be sure that this try was made correctly
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 16:13 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Very strange - maybe because I didn't restart the treadmill? Second run attached.

[debuginclinepresetsv2.zip](https://github.com/user-attachments/files/16678002/debuginclinepresetsv2.zip)

**Comment by cagnulein** [comment]
in this log the ftms treadmill disabled: you should enable it for this test
as i said. thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 17:26 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
Sorry - FTMS enabled and no pre-set buttons functioning.

[debuginclinepresetsv3.zip](https://github.com/user-attachments/files/16678176/debuginclinepresetsv3.zip)

**Comment by cagnulein** [comment]
ok let's try to collect some other information
install the free app nrfconnect on your phone, connect to the treadmill,
you will see a lot of characteristics, the one that i would like to see its
the feature list of the treadmill, its under the fitness machine service
let me know if you can't see it. in case send me a short video and i can
guide you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 17:39 dannynixon83 ***@***.***>
ha scritto:

**Comment by dannynixon83** [comment]
![Screenshot_20240820_164733_nRF Connect](https://github.com/user-attachments/assets/331952cd-9591-4608-8cfb-cc1b9e45ea1d)

That correct?

**Comment by cagnulein** [comment]
yes and we have the issue here, check the max and min inclination supported, they are all 0 :(
can you please show also the other supported one? i can see resistance , i would like to see the value

**Comment by dannynixon83** [comment]
![Screenshot_20240820_165238_nRF Connect](https://github.com/user-attachments/assets/bcb07bfe-6c1f-44a3-acb8-396d25a380d3)

**Comment by cagnulein** [comment]
ok so they did a very horrible job here unfortunately. let's try another way: if on kinomap you connect as an ftms device, are you able to change inclination? im try to think everything

**Comment by dannynixon83** [comment]
Yes inclination changes on kinomap using the +/-.

![358918781-c2f62062-2559-45e0-8053-729a47313b4b](https://github.com/user-attachments/assets/4afc5781-2414-41be-a804-3138fa50ff9c)

**Comment by cagnulein** [comment]
using the treadmill as a ftms device there? i guess on the back layer they are using the other protocol, but the only way to know this is using again the hci snoof method

**Comment by dannynixon83** [comment]
Just says iConsole connected...assume that's not FTMS then? Unsure how to connect then in kinomap as FTMS...

**Comment by cagnulein** [comment]
yes it's using the iconsole protocol
you have to click here 

![image](https://github.com/user-attachments/assets/4146ce18-811b-4560-a2fb-9961ecbeead1)

**Comment by dannynixon83** [comment]
![Screenshot_20240820_171505_Kinomap](https://github.com/user-attachments/assets/85eaa0c9-c860-46ae-911e-8c77d0776d54)

Thanks - no, no incline happening on button pushes. 😭

**Comment by cagnulein** [comment]
I suggest to write to the manufacturer we are entering In a dead way

**Comment by dannynixon83** [comment]
Thanks Roberto, think I'll just have to suck it up and use it in Peloton without the auto-function. It's not the end of the world...just would've be nice! I'm that used to it being automated on the EX3 now it detracts from the tread experience a little. Thank you again anyway.

**Comment by cagnulein** [comment]
I will think something else. But I guess we tried almost everything

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 18:27 dannynixon83 ***@***.***>
ha scritto:
