### ISSUE TITLE
[BUG]SS2K + Peloton Bike (Low Impact Rides)

### ISSUE THREAD

**Issue by Dekto** [cagnulein/qdomyos-zwift#2527]
**Describe the bug**

With Peloton Low Impact Rides, the automatic resistance only controls once at the start of the workout and then no more.

**To Reproduce**

Do a Low Impact Ride on the Peloton Bike with SmartSpin2k and the qdomyos-zwift (iOS) app.

**Expected behavior**

The resistance should change automatically when the trainer indicates the new range.

**Smartphone:**

Device: iPhone SE 2022
OS: iOS 17.6.1
Version qdomyos-zwift 2.15.4
SmartSpin2k 24.8.16

**Append a debug log**

[debug-Mo__Aug__19_15_18_25_2024.log](https://github.com/user-attachments/files/16662593/debug-Mo__Aug__19_15_18_25_2024.log)
  
  
**Additional context*

Peloton Workout runs directly on the Peloton Bike Tablet.

**Comment by cagnulein** [comment]
hi @Dekto i saw in these log these changes

![IMG_5851](https://github.com/user-attachments/assets/26408cf4-942c-45de-b4e9-6e0e03ad6081)

did you notice them?

**Comment by Dekto** [comment]
No, unfortunately not! 

The SmartSpin2k doesn't move...

**Comment by cagnulein** [comment]
ok so it's a problem there. do you have also the ss2k logs? @doudar can you help here?

**Comment by doudar** [comment]
@Dekto , what firmware version are you running?

**Comment by doudar** [comment]
I just looked at the QZ log. Please try starting with the resistance at 5 or higher, and let me know if that helps.

**Comment by Dekto** [comment]
@doudar SmartSpin2k Firmware  24.8.16

I started with the resistance at about 40.

**Comment by Dekto** [comment]
I'll be back home by the middle of next week. Then I can upload the SS2k logs...

**Comment by cagnulein** [comment]
welcome back @Dekto 
in this log i can see only a resistance requests from qz

Mi. Aug. 28 12:40:53 2024 1724841653685 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) " >> 04 1e // forceResistance 30"

so this was happening at the very beginning?
it seems that the SS2K wasn't at the home position. What do you think @doudar  ?

**Comment by Dekto** [comment]
@cagnulein 

Yes, right at the beginning the resistance turned towards 100 very quickly. 

What do you mean by home position? 

How can I set it?

**Comment by cagnulein** [comment]
@Dekto for sure @doudar is the best man to say this, but i guess you have to put the ss2k to the resistance 1 BEFORE opening QZ. because when you open qz, the SS2K took the actual position as the resistance 1 position. am i right @doudar  ?

**Comment by doudar** [comment]
I believe I have QZ on my Peloton working correctly now (had to activate a special Bluetooth developer mode). I'll see if I can duplicate this later today.

**Comment by doudar** [comment]
Also, it shouldn't damage the SS2k. The noise you hear if it hits the end stop is just the motor magnetically slipping. One of the reasons we chose a stepper motor in the design - it's like having a magnetic clutch built right into the motor.

**Comment by doudar** [comment]
> > had to activate a special Bluetooth developer mode
> 
> 
> 
> @doudar what do you mean?

"Enable Gabeldorsche"

**Comment by doudar** [comment]
Neither had I. Neither QZ nor the SS2k config app run correctly on my
Peloton tablet without it enabled. Without it enabled, we can see the
devices correctly, but cannot pair with them.

**Comment by Dekto** [comment]
@cagnulein 
@doudar 

Hello everyone, 

unfortunately there was no reply here. That's why I would like to ask again. 
I would love to do the normal courses too, which is why I bought the Qdomyos app and the SmartSpin2k. 

Is there further data I can provide to resolve the issue? 

I just tried a low impact ride again. Set the Peloton resistance to zero and start the workout. 
The Qdomyos app displayed the correct Target R. But the SS2k went from zero to 100 again. 
I noticed that in the Qdomyos app the Peloton R.% stays at 0. 
Is the resistance from the Peloton Bike perhaps recognized in the Qdomyos app? 

I would be very happy if you would help me...

**Comment by cagnulein** [comment]
@doudar were you able to do some test on your side?

**Comment by doudar** [comment]
Unfortunately not, because I don't have QZ on my iPhone and I can't get the QZ Android version to work properly on the Peloton tablet (the only android device I have available to me while I'm traveling this month).

**Comment by Dekto** [comment]
@cagnulein 

Could you perhaps provide @doudar with a free version for iOS?

**Comment by cagnulein** [comment]
> Unfortunately not, because I don't have QZ on my iPhone and I can't get the QZ Android version to work properly on the Peloton tablet (the only android device I have available to me while I'm traveling this month).

sure just sent! i thought you already had! let me know if you get it!

**Comment by cagnulein** [comment]
i got the issue now that i update the firmware: @doudar the SS2K doesn't return a inclination or a resistance value in the 2AD2 when i change the inclination or resistance from qz. Are you aware of this? This is the reason of the behaviour that @Dekto is seeing.

I did a small modification, removing the need to read the resistance from the SS2k and now it's working, but i guess it will be nice to have a feedback from the SS2K. What do you think?

**Comment by doudar** [comment]
Okay - I can look into this. It's probably a very easy fix, I just need to see if there was a reason I removed it.

**Comment by cagnulein** [comment]
Sounds good, thanks!


Il giorno ven 13 set 2024 alle 16:03 Anthony Doud ***@***.***>
ha scritto:

**Comment by doudar** [comment]
@cagnulein , I took a look at the code, and as long as a Peloton bike is connected, it *should* be outputting the resistance on 2AD2 bytes 6&7. If a bike that doesn't output resistance is connected, currently it outputs 0's. I should change that so that the 2AD2 hasResistance flag isn't set, or optionally calculate a resistance number from 1-100 by using the calculated end stops. I'll look into implementing those.

**Comment by cagnulein** [comment]
Hah wait! I didn't know you treat differently the bike. I observed this
behavior with my dumb bike! So it behaviors differently?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 19:48 Anthony Doud ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@doudar I was checking again the log from @Dekto and also his one doesn't have resistance on 2ad2 characteristic. Am I wrong?

**Comment by Dekto** [comment]
@cagnulein 
@doudar 

Hello Guy‘s, 

how are things going? 

What's new? 

Best regards

**Comment by cagnulein** [comment]
@Dekto i was waiting a feedback from @doudar

**Comment by doudar** [comment]
I've reviewed the code, It should be reporting resistance, but I'm having emad look at some logs for me since my hands are tied for another week or so.

**Comment by doudar** [comment]
In the mean time, @Dekto , make sure you're on https://github.com/doudar/SmartSpin2k/releases/tag/24.9.3 and have the Peloton cable plugged in.

**Comment by eMadman** [comment]
> i got the issue now that i update the firmware: @doudar the SS2K doesn't return a inclination or a resistance value in the 2AD2 when i change the inclination or resistance from qz. Are you aware of this? This is the reason of the behaviour that @Dekto is seeing.
> 
> I did a small modification, removing the need to read the resistance from the SS2k and now it's working, but i guess it will be nice to have a feedback from the SS2K. What do you think?
The logs off my SmartSpin2k are picking up and correctly reporting resistance: 
![image](https://github.com/user-attachments/assets/39aae1d0-22e3-47a4-9955-6170e8c9761b)

Also shows through on QZ.  Didn't try a controllable ride - just threw it into a free ride mode.
[debug-Thu_Sep_19_17_38_19_2024.log](https://github.com/user-attachments/files/17067185/debug-Thu_Sep_19_17_38_19_2024.log)

@Dekto - have you had luck running your SmartSpin2k in Zwift or Mywhoosh or some other training app (without QZ).  Just want to make sure we're not dealing with an issue elsewhere

**Comment by Dekto** [comment]
@eMadman
@doudar 
@cagnulein 

Hello, 

I have already installed firmware 24.9.3. 

I tested Zwift and the automatic resistance control works. 

It also works for Peloton Powerzone classes. It doesn't show the resistance of the Peloton Bike in the Qdomyos app, but changing the resistance works. Could it be that the calculation is different there? 

Do I have to configure the Qdomyos app in any special way? 
I chose the SS2k as an accessory. 

Best regards

**Comment by cagnulein** [comment]
> I chose the SS2k as an accessory.

did you try setting it as a ftms bike instead?

**Comment by Dekto** [comment]
@cagnulein 

No, not yet. 

I heard about the FTMS option and searched for it. But unfortunately I couldn't find it in the Qdomyos app. 

Can you give me information on how I can change this?

**Comment by cagnulein** [comment]
it's in the bike settings @Dekto 
you need the new beta of ios for this 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by Dekto** [comment]
@cagnulein 
@doudar 
@eMadman 

I still have access to version 2.16 via Testflight due to a previous issue. 

There I found the FTMS function. I will test it as soon as possible and give feedback here. 

I want to ask again about the other bug since we're all here together right now. (The shifter no longer works after using Qdomyo's app) 

https://github.com/doudar/SmartSpin2k/issues/561 

There is no solution for this yet, is there?

**Comment by cagnulein** [comment]
@Dekto if you use the ftms bike setting, the shifter should still work since it's like connecting ss2k to zwift

**Comment by Dekto** [comment]
@cagnulein 

If I use the SS2K as an FTMS device, do I also have to select it as an accessory?

**Comment by cagnulein** [comment]
Nope only on ftms

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 17:39 t0bM ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Dekto Is it OK now?

**Comment by Dekto** [comment]
@cagnulein 

Hello, I was no longer able to test it due to an injury. But thank you for your inquiry...

**Comment by cagnulein** [comment]
Oh so sorry to hear this! I hope the best for you!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 nov 2024 alle 09:48 t0bM ***@***.***> ha
scritto:
