### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by speedf1** [cagnulein/qdomyos-zwift#2529]
Hi Roberto, 

Not sure what's changed, but Bluetooth transmission of metrics from QZ  aren't detected anymore on my iPad Peloton app for either bike rides (cadence) or runs (speed and incline).  QZ looks to be functioning well apart from this.

All was working well a few weeks ago, but Peloton app says can't find any device transmitting.

I haven't changed any QZ settings, but guess that something else has changed.  QZ app is version 2.16.67 on OnePlus 10T Android 14.  iPad is gen 9, iOS 17.6.1 running Peloton app v15.86.0.

No debug log collected, but can do this if required?

**Comment by cagnulein** [comment]
i suggest to collect a debug log because it can be a lot of things, so the
easiest way to check it it's with a debug log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 17:16 speedf1 ***@***.***> ha
scritto:

**Comment by speedf1** [comment]
I guessed you'd probably need a debug log.  Attached is a very short one.  QZ linked to my Echelon tread (and picking and displaying up all the stats) but guess not transmitting them over FTMS?
[debug-Tue_Aug_20_16_24_26_2024.log](https://github.com/user-attachments/files/16678052/debug-Tue_Aug_20_16_24_26_2024.log)

**Comment by cagnulein** [comment]
everything is ok here, i guess it's just an ipad cache issue.
let's try first to install the nrfconnect app on the ipad with qz open on
the other side: you see the android phone name there, post a screenshot so
i can check that that's the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 17:31 speedf1 ***@***.***> ha
scritto:

**Comment by speedf1** [comment]
Assuming I'm doing everything right, the Android phone doesn't seem to show up in the nrfconnect app.

Just to double check, I have the nrfconnect app open on the iPad and QZ running on the Android phone right next it to.  The nrfconnect app shows lots of bluetooth devices, but none of them look like the Android phone.  Screenshot attached.

![ipad screenshot](https://github.com/user-attachments/assets/d7890676-9cad-4598-a846-142f042603fb)

**Comment by cagnulein** [comment]
did you check the whole list? i'm checking again the log in the meantime

**Comment by cagnulein** [comment]
maybe you changed the phone name? set it to "bike" just 4 letters and reboot your android phone

**Comment by cagnulein** [comment]
The name of your phone it could be definitely the issue
Let me know

**Comment by speedf1** [comment]
Interesting!  Changing the BT name to "bike" as you suggested worked.  The BT name has been the same for a long time and not been a problem before.  Perhaps a recent Android update has broken something.......
