### ISSUE TITLE
[ENH] Email Chart image when workout is complete

### ISSUE THREAD

**Issue by ptrinephi** [cagnulein/qdomyos-zwift#253]
When pressing the stop button to end the workout, QZ saves the fit file and the QZ tile screenshot and updates Strava.  It also displays the new charts.  I think this would be a good time to email the tile screenshot and charts images to whatever email address is in the setup page.

**Comment by cagnulein** [comment]
qzapp.it domain has been bought :)

**Comment by cagnulein** [comment]
did you see the email now?

**Comment by ptrinephi** [comment]
Yes, email is working but it's only sending the Power image.  Please 
send the Heart and Cadence image too.

Thanks

------ Original Message ------

**Comment by cagnulein** [comment]
It does for everyone of course not for you :)

Il mar 20 apr 2021, 19:00 3phi ***@***.***> ha scritto:

**Comment by ptrinephi** [comment]
Are you serious?  I tried 2 email addresses!



------ Original Message ------

**Comment by cagnulein** [comment]
Yes I'm serious. On which phone do you have this?

Il mar 20 apr 2021, 19:21 3phi ***@***.***> ha scritto:

**Comment by ptrinephi** [comment]
Hey, maybe I need to run longer tests? I'll give it another try!

------ Original Message ------

**Comment by ptrinephi** [comment]
This is on my good phone, S9.

------ Original Message ------
