### ISSUE TITLE
[BUG] Ant dongle transfering cadence, power but not speed to garmin watch

### ISSUE THREAD

**Issue by okmijn22** [cagnulein/qdomyos-zwift#2530]
**Describe the bug**
Followed the instructions here: https://robertoviola.cloud/2023/07/06/connect-any-indoor-bike-with-your-garmin-device/ and everything was working until yesterday. Now when I do indoor bike activity on my garmin watch, the speed from qz app does not transfer over to garmin watch but cadence and power still transfers over. I used the Garmin ANT dongle. Is there a bug in the app or something wrong with the dongle? I'm using Pixel 6a for phone which is where qz app is installed and Epix Pro Gen2 for Garmin watch. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
there are others reporting this but it's not about qz, it should be
something about a garmin update. did you set the wheel diameter on your
watch?

i suggest to reboot and repair everything, also a factory reset on the
watch could help (on fb a user solved this in this way)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 17:17 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
I reset the watch and reset wheel size to 100mm in speed/cadence sensor but still not working. Could you please link me the post on fb?

**Comment by cagnulein** [comment]
This is one
https://www.facebook.com/share/p/bMfZH7eQzRWsYjHb/?
There is also a video of me showing that it's working on my end.
But I guess the users answered me by email because I don't see the final
answer.

Don't you see at all the cadence sensor? Did you also check this?

This was the post about that it's working
https://github.com/cagnulein/qdomyos-zwift/issues/2263#issuecomment-2254189331


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 18:12 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
On my watch both PWR 19302 and Spd/Cad 19251 shows connected. It's just that when I start the indoor bike activity, the speed from qz app cannot be transferred to the watch. When I end the indoor bike activity and view the activity summary, it says speed and distance is 0 but show correct values for cadence and power.

**Comment by okmijn22** [comment]
Similar to Tomasz Bogacki, even when I remove the Spd/Cad 19251 sensor, I still get the cadence from PWR sensor.

**Comment by okmijn22** [comment]
So I think the issue is with Spd/Cad 19251 sensor, in that it shows connected but does not get the values from qz app.

**Comment by cagnulein** [comment]
Qz sends both 3 metrics at the same time. Do you have another
android/watch/ dongle to test?
Since I didn't change anything it's something outside that changed

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 18:42 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
I only have 1 watch and ant tester app does not seem to work on Pixel tablet. Not sure if the dongle is the issue because it says connected in watch.

**Comment by cagnulein** [comment]
Strange, I have a pixel and ant app works. Which dongle do you have?

**Comment by okmijn22** [comment]
I have garmin ant: https://www.amazon.ca/Garmin-USB-Stick-Fitness-Devices/dp/B00CM381SQ/ref=sr_1_1?dib=eyJ2IjoiMSJ9.q-2beJcQaahVgjPnpYtpKai-tKy3JuekYmvZya19cdLDhcgaY3pJHfPM3o_U91Bwr6-0_xQaB6n5pOU4kkQcHkbBh5T5U7IAzkDTeYg54lIkB54XqbHOL4eCDFk6CMwx8QXhmJWoho5GPgYQNtIQFmPp3qmyMzIW5H953CA2PRxdp-P5oTPPa4HFG8AXEx6GOTJ1rifrURy2dE_duVfPARYRWOvwSsiCj-e5BOWAqVbcvdJTzkpVz24eW1-5rIdSZ0wRF2j2ApFfFj55JrhQ1e8IifNONPuXJkoRHOt9FDM.qdvaQDBBLvkYAy6sTnmZ9fgMX2_BYYxhOackBPySN9Q&dib_tag=se&keywords=garmin+ant&qid=1724173442&sr=8-1

**Comment by cagnulein** [comment]
Garmin ant is usually the best, I don't think is broken. It sounds more a
bug on the watch somehow. Are you able to track when this started? Maybe a
firmware upgrade on the watch? What if you unpair the power sensor: are you
able to see the speed?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 19:04 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
Matt Wood said issue was with his phone so try resetting phone instead of watch?

**Comment by cagnulein** [comment]
It could be. It worth a try if you can

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 19:09 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
It started yesterday. It was working the day before yesterday. Do you mean to connect Spd/Cad 19251 sensor but disconnect PWR 19302?

**Comment by cagnulein** [comment]
Yes it's a quick test and it can give us some idea

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 ago 2024 alle 19:11 okmijn22 ***@***.***> ha
scritto:

**Comment by okmijn22** [comment]
Restarting my phone seems to have fixed the issue!
