### ISSUE TITLE
[BUG]The zwift play controllers don't connect and the app crashes

### ISSUE THREAD

**Issue by Lanmarcin** [cagnulein/qdomyos-zwift#2531]
**Describe the bug**
The zwift play controllers don't connect and the app crashes

**To Reproduce**
I have the zwift hub trainer and zwift play controllers paired with my computer. After starting the application, you can see that the application connects to the trainer, the zwift play controllers flash so they are not connected and after a while the application crashes. If I turn off Bluetooth on the computer, the application no longer crashes. I have zwift controllers enabled in the application in the accessories settings.

I tried the integrated bluetooth card in the computer, the ugreen bluetooth adapter 5.4 (there are also logs from this) ,the tp link ub500 adapter and the results are always the same.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 10.0.22631 Build 22631
 - 
[debug-st_aug_21_11_59_09_2024.log](https://github.com/user-attachments/files/16690132/debug-st_aug_21_11_59_09_2024.log)

**Comment by cagnulein** [comment]
@Lanmarcin 

the main issue is 

qbluetoothdevicediscoveryagent_win.cpp void QBluetoothDeviceDiscoveryAgentPrivate::start(QBluetoothDeviceDiscoveryAgent::DiscoveryMethods) Device does not support Bluetooth

which bluetooth dongle do you have?

**Comment by Lanmarcin** [comment]
@cagnulein  Sorry, when I started this ticket, I accidentally attached a log that was created when I turned off Bluetooth. However, I immediately corrected and attached the correct log [debug-st_aug_21_11_59_09_2024.log](https://github.com/user-attachments/files/16690132/debug-st_aug_21_11_59_09_2024.log) , "Device does not support Bluetooth" no longer appears there.

**Comment by Lanmarcin** [comment]
I tried using bluetooth dongles: UGREEN Bluetooth 5.4  (with antenna) and TP-Link UB500 v1

**Comment by cagnulein** [comment]
ok i guess i got the issue, i will try to handle this in these days.
is it working ok on mobile?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 ago 2024 alle 12:34 Lanmarcin ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Lanmarcin done https://github.com/cagnulein/qdomyos-zwift/actions/runs/10490004741

check the build in the link (check at the bottom of the page in about 1 hour)

**Comment by Lanmarcin** [comment]
@cagnulein  Thank you.  In the new build of the application, the controllers are already connected. Shifting the gears just seemed quite slow to me. The second  problem is that only at the first start-up the gears can be changed. When I started the application repeatedly, the controllers were connected, but changing the gears didn't work anymore. 
[zwift_play_gears_not_working.log](https://github.com/user-attachments/files/16696945/zwift_play_gears_not_working.log)
[zwift_play_working.log](https://github.com/user-attachments/files/16696955/zwift_play_working.log)

**Comment by Lanmarcin** [comment]
From the point of view that after pressing the button, the change of gears in qz is displayed with a delay
For the second problem, I restarted the computer. It helped, but now I have a new problem.
The buttons on the controller now react in the opposite way, the right button on the controller lowers the gears and the left button increases gears.
I tried to run the qz application again after the first run after restarting and again I can't change the gears,

I am attaching a log of the problem for the opposite change of gears
[debug-st_aug_21_21_02_43_2024.log](https://github.com/user-attachments/files/16697668/debug-st_aug_21_21_02_43_2024.log)

**Comment by Lanmarcin** [comment]
I tried to test a few things

1.on my PC, switching gears with zwift play only works after restarting the computer, and only if I run the application for the first time.  If I start it repeatedly, the switching of gears does not work anymore.

2.the slow change of display of gears when pressing the button happens only in the PC version, sometimes the change of display of gears in qz takes even 3 seconds.  the displayed time in qz also gets stuck.

on the samsung galaxy tab s9 , changing gears works for me and there is no slowdown to be seen. 

3.On the android version, zwift play controllers are not connected after each launch.  I tried to restart the qz application 10 times and both controllers were connected in 3 cases, otherwise there was a situation where neither one was connected, only the right one was connected or only the left one was connected.  I have the feeling that they both connected successfully when flashing at the same intervals and I started the application at a certain moment.  I also had this problem in the Windows version, but less often.

4.my biggest problem with the qz application for Windows is that it only works for me in Zwift but not in Rouvy, so I don't see any devices in the connections at all.  I don't know whether to create a ticket for this problem or whether this problem can be solved at all.
the problem why I can't use the android version is that when I restart the qz application I have to pair everything again in Rouvy. 


I owe you a coffee

**Comment by cagnulein** [comment]
> I tried to test a few things
> 
> 1.on my PC, switching gears with zwift play only works after restarting the computer, and only if I run the application for the first time.  If I start it repeatedly, the switching of gears does not work anymore.
> 

Yeah this is something that I'm aware of, this doesn't happen on the mingw version but you have first to pair your Bluetooth devices on the windows Bluetooth settings 

https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary-no-python.zip

> 2.the slow change of display of gears when pressing the button happens only in the PC version, sometimes the change of display of gears in qz takes even 3 seconds.  the displayed time in qz also gets stuck.

Yes same as 1.

> 
> on the samsung galaxy tab s9 , changing gears works for me and there is no slowdown to be seen. 
> 

Perfect 

> 3.On the android version, zwift play controllers are not connected after each launch.  I tried to restart the qz application 10 times and both controllers were connected in 3 cases, otherwise there was a situation where neither one was connected, only the right one was connected or only the left one was connected.  I have the feeling that they both connected successfully when flashing at the same intervals and I started the application at a certain moment.  I also had this problem in the Windows version, but less often.
> 

That's strange, do you have a debug log of this?

> 4.my biggest problem with the qz application for Windows is that it only works for me in Zwift but not in Rouvy, so I don't see any devices in the connections at all.  

Yes it's a limitation of rouvy, rouvy didn't implement the same device thing that zwift implemented, you need 2 devices 

> I don't know whether to create a ticket for this problem or whether this problem can be solved at all.

Nope, it can't be solved or you can solve it using another bluetooth dongle on the same pc.

> the problem why I can't use the android version is that when I restart the qz application I have to pair everything again in Rouvy. 

yeah but i guess it's a small thing after all :) you should ask to rouvy to fix this. you can put me in CC

> 
> 
> I owe you a coffee

thanks! feel free to contribute on patreon https://www.patreon.com/cagnulein

**Comment by cagnulein** [comment]
any news @Lanmarcin ?

**Comment by Lanmarcin** [comment]
unfortunately I haven't had time to test mingw version yet. 

I tried the android version now. I am attaching the logs from the qz on the Samsung Galaxy Tab S9, where both controllers could not be connected in the first case.  in the second log, only the left controller connected.
[debug-problem_left_right.log](https://github.com/user-attachments/files/16784401/debug-problem_left_right.log)
[debug-problem_right.log](https://github.com/user-attachments/files/16784402/debug-problem_right.log)

I will try to use a second usb dongle on the computer to test the connection from qz to the  Rouvy.

I also tried running qz on the phone and rouvy on the tablet. The phone and mobile phone were paired via bluetooth. When I restarted the qz application on the phone and started the rouvy again, everything connected without problems. This way it everything is working.

The problem qz(anroid phone) -> rouvy(windows pc) would be possible if the developers in Rouvy fixed it? Isn't it somehow a limitation of Android? I can write to them, even if I don't expect much from it because I don't have a good experience with their support.

**Comment by cagnulein** [comment]
> tried the android version now. I am attaching the logs from the qz on the Samsung Galaxy Tab S9, where both controllers could not be connected in the first case. in the second log, only the left controller connected. [debug-problem_left_right.log](https://github.com/user-attachments/files/16784401/debug-problem_left_right.log) [debug-problem_right.log](https://github.com/user-attachments/files/16784402/debug-problem_right.log)

they simple don't advertise themself. this means that you don't wake up them before starting qz, or they connected somewhere else. Is it possible?



> I will try to use a second usb dongle on the computer to test the connection from qz to the Rouvy.

ok



> I also tried running qz on the phone and rouvy on the tablet. The phone and mobile phone were paired via bluetooth. When I restarted the qz application on the phone and started the rouvy again, everything connected without problems. This way it everything is working.

perfect



> The problem qz(anroid phone) -> rouvy(windows pc) would be possible if the developers in Rouvy fixed it? Isn't it somehow a limitation of Android? I can write to them, even if I don't expect much from it because I don't have a good experience with their support.

yes there is an easy fix, i already contacted them but they simply don't listen. Try and put me in CC if you want! QZ can give them a lot of new users if only they want!

**Comment by cagnulein** [comment]
> I always turn on the controllers before starting qz. But the situation is that the controllers are always running, the only thing I turn off and on is is the qz application.

in order to be sure that they are disconnected, check the bluetooth settings of the phone, they should be disconnected from there. Probably android is keeping alive the connection somehow and this prevents the zwift play to go into the advertise mode.

**Comment by cagnulein** [comment]
Check that the controller are advertising themselves on the nrfconnect app before opening qz. Nrfconnect use the same method that qz does

**Comment by Lanmarcin** [comment]
> Check that the controller are advertising themselves on the nrfconnect app before opening qz. Nrfconnect use the same method that qz does

I tried nfconnect and the controllers always appear there.  in every situation when some of the controllers could not connect to qz, I saw them in nfconnect.

**Comment by cagnulein** [comment]
ok can you please upload a fresh debug log with the issue. i guess there is
something that i need to address in this case

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 set 2024 alle 09:00 Lanmarcin ***@***.***> ha
scritto:

**Comment by Lanmarcin** [comment]
I have the latest version qz on my tablet.I am attaching several logs for the situations that occurred.


[both-connected.log](https://github.com/user-attachments/files/16895247/both-connected.log)
[both_connected_2.log](https://github.com/user-attachments/files/16895248/both_connected_2.log)
[right_connected.log](https://github.com/user-attachments/files/16895249/right_connected.log)
[none_connected.log](https://github.com/user-attachments/files/16895250/none_connected.log)

**Comment by cagnulein** [comment]
got the issue! i'm fixing it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 set 2024 alle ore 16:32 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Lanmarcin done!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10723648740

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Lanmarcin** [comment]
Thank you very much.   I tried to launch the qz application about 30 times, and one of the controllers always connects first, then after a few seconds the second controller connects. both controllers always connect after a few seconds.so it already works reliably.

Thank you for your work.  I also contributed via patreon last week.I will also write to the email regarding the trial version

**Comment by cagnulein** [comment]
Glad it worked! And thanks so much for patreon!
Send me the email so I will unlock it!
Thanks for reporting this!


Il giorno gio 5 set 2024 alle 21:17 Lanmarcin ***@***.***> ha
scritto:
