### ISSUE TITLE
Sole B94 (Hammer B94)

### ISSUE THREAD

**Issue by chrise3112** [cagnulein/qdomyos-zwift#2532]
Hello!  Does anyone have a Sole B94 (also known as a Hammer B94) working with auto resistance on Zwift or MyWhoosh?

I've got it connecting via QZ on my android phone but auto resistance doesn't work.

**Comment by cagnulein** [comment]
Hi @chrise3112 it should have auto resistance 
https://github.com/cagnulein/qdomyos-zwift/issues/393

Create a debug log and I will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by chrise3112** [comment]
Here you go...
[debug-Fri_Aug_23_12_23_06_2024.log](https://github.com/user-attachments/files/16727940/debug-Fri_Aug_23_12_23_06_2024.log)

Hope this helps

**Comment by cagnulein** [comment]
@chrise3112 could you try to enable this and restart qz 

![image](https://github.com/user-attachments/assets/7f9478fa-a182-4716-9073-4c11602f5925)

you can simply check if it works changing the resistance tile in qz without mywhoosh. let me know

**Comment by chrise3112** [comment]
No, that didn't seem to work.  The resistance buttons didn't do anything,
either with auto resistance enabled or disabled.

**Comment by cagnulein** [comment]
do you have any apps that can control the resistance of your bike? for example kinomap?

**Comment by chrise3112** [comment]
Just installed Kinomap and that works.

**Comment by cagnulein** [comment]
perfect so collect a log with it following this and i will add it!
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 23 ago 2024 alle 15:02 chrise3112 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@chrise3112 any news?

**Comment by chrise3112** [comment]
Sorry - my phone had a work profile on it which prevented access to certain
settings... That's been removed now so I'll get the log over to you

**Comment by cagnulein** [comment]
No worries, thanks for the update!
Let me know

Il giorno lun 16 set 2024 alle 22:01 chrise3112 ***@***.***>
ha scritto:
