### ISSUE TITLE
[BUG] Domyos eb 900 still connects but stopped showing pedalling data 

### ISSUE THREAD

**Issue by laminado** [cagnulein/qdomyos-zwift#2533]
![inbound5374808558805201557](https://github.com/user-attachments/assets/227ed313-2e42-4c86-a7da-d3d8f048dab1)
**Describe the bug**
Domyos eb 900 stopped showing bike data despite still recognizing the bike and still successfully connecting with bluetooth.

**Expected behavior**
Show bike data as it has always shown.

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 
 - Version: Emui 12.0.0.22
[inbound2970619354801718934.txt](https://github.com/user-attachments/files/16697348/inbound2970619354801718934.txt)
(had to change log extension to .txt to be allowed to upload) 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@laminado could you please enable this and restart qz

![image](https://github.com/user-attachments/assets/fac72a36-72c6-41f4-87b9-abda13e608ea)

**Comment by laminado** [comment]
Hello Roberto
![inbound1545600856623736904](https://github.com/user-attachments/assets/75a511ea-a7f3-4b4a-8ec4-abddf9440733)

Changed settings and restarted QZ. 
Still no data.

**Comment by cagnulein** [comment]
send me a fresh log with this, thanks

**Comment by laminado** [comment]
![debug-Wed_Aug_21_20_06_11_2024.log.txt](https://github.com/user-attachments/files/16697650/debug-Wed_Aug_21_20_06_11_2024.log.txt)

Here goes! Thanks

**Comment by cagnulein** [comment]
try to restart the bike, it doesn't send anymore the right services.


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 ago 2024 alle 21:14 laminado ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
im going to bed now, i will answer back tomorrow

**Comment by laminado** [comment]
![debug-Wed_Aug_21_21_27_36_2024.log.txt](https://github.com/user-attachments/files/16698369/debug-Wed_Aug_21_21_27_36_2024.log.txt)

![debug-Wed_Aug_21_21_23_42_2024.log.txt](https://github.com/user-attachments/files/16698370/debug-Wed_Aug_21_21_23_42_2024.log.txt)

![debug-Wed_Aug_21_21_24_23_2024.log.txt](https://github.com/user-attachments/files/16698371/debug-Wed_Aug_21_21_24_23_2024.log.txt)

![debug-Wed_Aug_21_21_24_19_2024.log.txt](https://github.com/user-attachments/files/16698368/debug-Wed_Aug_21_21_24_19_2024.log.txt)

Here go some more logs. Hope you can sort this without too much trouble.

**Comment by cagnulein** [comment]
hi @laminado log checked and the bike is going strange: it's presenting itself like a way and then it changes itself. did you upgrade the firmware of the bike? did you change something on the bike itself? did you try also to reset it? i can create a patch for this but unfortunately today and tomorrow for me are travel day and i can't access to my computer. 
Let me know

**Comment by cagnulein** [comment]
ok just did https://github.com/cagnulein/qdomyos-zwift/actions/runs/10502106389

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

you will see a popup with the instructions to restart qz if everything that I did is working correctly
Let me know!

**Comment by laminado** [comment]
Hello, no change to the bike. Last night i rolled back to a trial version you have here in git (2.14) and it worked well. I will try to use this patch you did. There's an apk on the link you sent?

**Comment by cagnulein** [comment]
Yes here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10502106389/artifacts/1840706239

**Comment by laminado** [comment]
![debug-Thu_Aug_22_10_24_04_2024.log.txt](https://github.com/user-attachments/files/16708339/debug-Thu_Aug_22_10_24_04_2024.log.txt)

Still not working.

**Comment by cagnulein** [comment]
You have the manual device setting in the advanced settings set to wifi.
Put it to your bike and restart qz
Then you will see the popup about ftms and restart again
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 ago 2024 alle 11:27 laminado ***@***.***> ha
scritto:

**Comment by laminado** [comment]
![Screenshot_20240822_124202_org.cagnulen.qdomyoszwift.jpg](https://github.com/user-attachments/assets/8a3eb475-c50c-4b75-82c3-b93bf5c243f9)

Working 👌

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno gio 22 ago 2024 alle 13:43 laminado ***@***.***> ha
scritto:

**Comment by laminado** [comment]
Thank you very much!!!
