### ISSUE TITLE
[REQ] Add Support for Echelon Stride 6S

### ISSUE THREAD

**Issue by hifihedgehog** [cagnulein/qdomyos-zwift#2534]
**Is your feature request related to a problem? Please describe.**
Missing support for Echelon Stride 6S. In examining the code, it appears we are needing a check for Echelon 6S’s Bluetooth device name.  

**Describe the solution you'd like**
Support for Stride 6S. Hopefully, it is as simple as adding this:

> (b.name().toUpper().startsWith(QLatin1String("STRIDE6s-10-“))

to this:

https://github.com/cagnulein/qdomyos-zwift/blob/78101b61912d1afef9c566df099cab8f95acbd43/src/devices/bluetooth.cpp#L1625-L1630

**Describe alternatives you've considered**
None. A change is needed.

**Additional context**
![IMG_1752](https://github.com/user-attachments/assets/a5b734a7-0f2c-434b-ba9f-bf3c55d944b5)

**Comment by hifihedgehog** [comment]
Maybe add the Stride 6S (and what appears to be m missing Echelon treadmill references) here as well:

https://github.com/cagnulein/qdomyos-zwift/blob/78101b61912d1afef9c566df099cab8f95acbd43/tst/Devices/EchelonStrideTreadmill/echelonstridetreadmilltestdata.h#L10-L14

**Comment by cagnulein** [comment]
> **Is your feature request related to a problem? Please describe.** Missing support for Echelon Stride 6S. In examining the code, it appears we are needing a check for Echelon 6S’s Bluetooth device name.
> 
> **Describe the solution you'd like** Support for Stride 6S. Hopefully, it is as simple as adding this:
> 
> > (b.name().toUpper().startsWith(QLatin1String("STRIDE6s-10-“))
> 
> to this:
> 
> https://github.com/cagnulein/qdomyos-zwift/blob/78101b61912d1afef9c566df099cab8f95acbd43/src/devices/bluetooth.cpp#L1625-L1630
> 
> **Describe alternatives you've considered** None. A change is needed.
> 
> **Additional context** ![IMG_1752](https://private-user-images.githubusercontent.com/16614343/360261271-a5b734a7-0f2c-434b-ba9f-bf3c55d944b5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDIyMDUsIm5iZiI6MTcyNDMwMTkwNSwicGF0aCI6Ii8xNjYxNDM0My8zNjAyNjEyNzEtYTViNzM0YTctMGYyYy00MzRiLWJhOWYtYmYzYzU1ZDk0NGI1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNDQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzk4N2FkYjM0MDU3YjQwNjVhYjg0ZWMzZGY4ZWI0NzFiYjlkZmRhZmM1MTMyZmI3MTQ5Y2Y3NTRhMDI2NjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZylDnu1Dcgxz6jXYoEkQD73i1Wxq-olRknz7c9wFXTI)

hi, yes that's the reason. it's a new device name. i will try to build a patch for you asap

**Comment by cagnulein** [comment]
building now, i'm sending you a new one in 30 minutes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 ago 2024 alle ore 06:42 hifihedgehog <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@hifihedgehog i sent the newer version by email! let me know!

**Comment by hifihedgehog** [comment]
Hi! Can you send an Android one as well? I also purchased on the Play Store!

**Comment by cagnulein** [comment]
You can download it from here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10502051593/artifacts/1840695822

Add your email, all lowercase to the email setting to unlock it

**Comment by hifihedgehog** [comment]
Works… somewhat! Speed and incline control don’t appear to be working at the moment, but it will start and stop from the app and heart rate is also detected. Another issue I am noticing is when I set the app to imperial, (1) weight is actually understood as metric at the wizard and then converted to pounds despite showing pounds for the units for the free text field in the wizard.

**Comment by cagnulein** [comment]
> Works… somewhat! Speed and incline control don’t appear to be working at the moment, but it will start and stop from the app and heart rate is also detected. 


Yes echelon stride doesn't have these controls from Bluetooth 

> Another issue I am noticing is when I set the app to imperial, weight is actually understood as metric at the wizard and then converted to pounds despite showing pounds for the units for the free text field in the wizard. So if I select imperial and then set pounds to 160, the app actually registers that as 160 kilograms and then saves it as 352.74 kilograms despite it me selecting imperial and it showing pounds as the units for the free text field.

The wizard is very new, set everything in the settings and I will check the wizard code, thanks

**Comment by hifihedgehog** [comment]
Sounds good then. Resolved! 😄

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno gio 22 ago 2024 alle 15:52 hifihedgehog ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
> Works… somewhat! Speed and incline control don’t appear to be working at the moment, but it will start and stop from the app and heart rate is also detected. Another issue I am noticing is when I set the app to imperial, weight is actually understood as metric at the wizard and then converted to pounds despite showing pounds for the units for the free text field in the wizard. So if I select imperial and then set pounds to 160, the app actually registers that as 160 kilograms and then saves it as 352.74 kilograms despite it me selecting imperial and it showing pounds as the units for the free text field.

fixed, thanks!
