### ISSUE TITLE
[BUG] Cannot Permanently Acknowledge App Permissions Notification, Keeps Reappearing at Startup

### ISSUE THREAD

**Issue by hifihedgehog** [cagnulein/qdomyos-zwift#2535]
**Describe the bug**
See title. Keeps requesting permissions when already granted.

**To Reproduce**
1. Open app.

**Expected behavior**
No notification.

**Screenshots**

**Tablet (please complete the following information):**
 - OS: Android 9
 - Version: 2.16.68

**Append a debug log**

 
[debug-Thu_Aug_22_11_58_44_2024.log](https://github.com/user-attachments/files/16714735/debug-Thu_Aug_22_11_58_44_2024.log)
[debug-Thu_Aug_22_12_00_23_2024.log](https://github.com/user-attachments/files/16714736/debug-Thu_Aug_22_12_00_23_2024.log)

  
**Additional context**

**Comment by hifihedgehog** [comment]
![Uploading IMG_1760.jpeg…]()

**Comment by hifihedgehog** [comment]
![IMG_1760](https://github.com/user-attachments/assets/25ddb5d5-1a75-44b3-9e90-4b7118b5ed3a)

**Comment by cagnulein** [comment]
when a device doesn't have the gps, it has the issue https://github.com/cagnulein/qdomyos-zwift/issues/2036#issuecomment-2360885332

@hifihedgehog can you confirm me this?

**Comment by cagnulein** [comment]
fixed #2716
