### ISSUE TITLE
NordicTrack S22i Auto Incline and Resistance Issues

### ISSUE THREAD

**Issue by ghost** [cagnulein/qdomyos-zwift#2536]
Hello. I'm having problems with incline and resistance using Zwift. When start a ride the metrics show on my phone, but i can't the incline and resistance doesn't seem to work. Please assist. Also, when I open the QZ app, I notice that it doesn't pick up on my bike. Do you know why that is.

I'm running the QZ app on the iPhone iOS 18 Beta/

[debug-Sat_Aug_24_20_38_21_2024.log](https://github.com/user-attachments/files/16738836/debug-Sat_Aug_24_20_38_21_2024.log)

**Comment by cagnulein** [comment]
hi , could you please follow this troubleshooting
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle 05:03 Phila1988 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@acgourley Any news?
