### ISSUE TITLE
Hammer Finnlo BF 90

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2538]
[btsnoop_hci.log](https://github.com/user-attachments/files/16736831/btsnoop_hci.log)
 
Hi Roberto, I hope the upload works now and the log file has been recorded correctly ..... Thanks!

_Originally posted by @ralfnec in https://github.com/cagnulein/qdomyos-zwift/issues/2417#issuecomment-2308403116_

**Comment by cagnulein** [comment]
@ralfnec instead of enabling the iconsole elliptical setting (disable it!) enable the iconsole bike setting under the toorx iconsole setting and it should work! let me know!

**Comment by ralfnec** [comment]
Hi Roberto, no doesn't work. I tried it already in the beginning by myself and now again - no success

**Comment by cagnulein** [comment]
could you please share a debug log from qz in this scenario? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F 
the protocol is exactly the same

**Comment by ralfnec** [comment]
Hi Roberto,
attached the file, hope it is the right one and you will receive it as my yahoo account is driving me crazy currently
Yahoo Mail: Suchen, organisieren, erobern 
 
  Am Mo., Aug. 26, 2024 at 16:22 schrieb Roberto ***@***.***>:   


could you please share a debug log from qz in this scenario? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
the protocol is exactly the same

**Comment by cagnulein** [comment]
Hi you have to attached from the github web interface otherwise I can't see
it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 ago 2024 alle 17:53 ralfnec ***@***.***> ha
scritto:

**Comment by ralfnec** [comment]
I tried to do so before, but your system is refusing by not supporting  that file type. It has the ending "fit".  Can I rename it?

**Comment by cagnulein** [comment]
The fit file it’s not a debug log. You have to upload the one starting with
debug

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 ago 2024 alle 19:52 ralfnec ***@***.***> ha
scritto:

**Comment by ralfnec** [comment]
I don't know why but QZ didn't create a debug log on my Smartphone I usually take for my trainings with QZ. Now I took another phone, here the log file was created (but this phone doesn't work with my crosstrainer and QZ either). But I'm not sure if I installed on that phone the QZ beta app you sent me in June for my treadmill. 
[debug-Mon_Aug_26_20_49_50_2024.log](https://github.com/user-attachments/files/16752635/debug-Mon_Aug_26_20_49_50_2024.log)
Hope I took the right file that provides you with the information needed.

**Comment by cagnulein** [comment]
> I don't know why but QZ didn't create a debug log on my Smartphone I usually take for my trainings with QZ. 

I guess it was because you installed the GitHub version. You have to delete the /documents/Qz and try again

I will check the log tomorrow

**Comment by cagnulein** [comment]
Got the issue in the log

Mo. Aug. 26 20:49:56 2024 1724698196344 Debug: ../src/devices/trxappgateusbbike/trxappgateusbbike.cpp void trxappgateusbbike::serviceScanDone() "invalid service" "49535343-FE7D-4AE5-8FA9-9FAFD205E455"

I will fix it tomorrow!

**Comment by cagnulein** [comment]
@ralfnec done

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10572907840

Remember to enable back the iconsole bike setting after installing this

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
that's great! simply add your email  ralfnec at yahoo.de (replace at
with @) all lowercase in the email setting in qz to unlock it!
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 ago 2024 alle ore 17:25 ralfnec ***@***.***>
ha scritto:

**Comment by ralfnec** [comment]
Hi Roberto,

made tonight my first workout after the update. It works without any problem now in VZFit,  even with authentic resistance, which was the main reason for me for buying my new crosstrainer. It only seems that the change of the resistance level is postponed to my device for a couple of seconds, but this is not a big issue. Thanks for your patience and your outstanding support, enjoy the coffee I invited you for on your homepage. I'm sure one day i'll will be back with a new device because your app is a big support for my sports training. Keep on working on it, its worth to!

**Comment by cagnulein** [comment]
That's great, thank you!
