### ISSUE TITLE
[BUG] Skipping gears in Zwift on IOS 

### ISSUE THREAD

**Issue by RobertoHerradura** [cagnulein/qdomyos-zwift#2540]
As we discussed today, my remote is often skipping a gear while the IOS slider does not.

Thanks,

Roberto

Edit : updated the debug file with new date

[debug-Tue_Aug_27_07_55_23_2024.log](https://github.com/user-attachments/files/16759256/debug-Tue_Aug_27_07_55_23_2024.log)

**Comment by cagnulein** [comment]
[debug-Tue_Aug_27_07_55_23_2024.log](https://github.com/user-attachments/files/16757429/debug-Tue_Aug_27_07_55_23_2024.log)

**Comment by cagnulein** [comment]
@RobertoHerradura did you try so?

**Comment by RobertoHerradura** [comment]
> @RobertoHerradura did you try so?

Yes Roberto, we've been in contact on messenger
