### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by decbroo** [cagnulein/qdomyos-zwift#2544]
[debug-Tue_Aug_27_18_24_12_2024.log](https://github.com/user-attachments/files/16766558/debug-Tue_Aug_27_18_24_12_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Got the issue, I already fixed in the beta. Send me an email to
Roberto.viola83 at Gmail.com and I will send you the new beta
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 ago 2024 alle 19:30 decbroo ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@decbroo can we close this?

**Comment by decbroo** [comment]
Sorry never used it before think I’ve done it.

**Comment by cagnulein** [comment]
no problem :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 ago 2024 alle ore 16:41 decbroo ***@***.***>
ha scritto:
