### ISSUE TITLE
[BUG] Echelon Stride no data. 

### ISSUE THREAD

**Issue by pifiuk** [cagnulein/qdomyos-zwift#2545]
**Describe the bug**
I am able to connect to the Echelon Stride treadmill and it starts correctly but other than that I get no data. When I end the activity every field is 0 on iPhone. 

**Expected behavior**
I believe that according to the settings for Echelon in the app it converts miles to kmh so I assume it should be showing some data. 

**Screenshots**
![IMG_0774](https://github.com/user-attachments/assets/64ec143f-dfa1-4422-8306-fd0b2dacedaa)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro 
 - OS: ios 18 Public Beta
 - Version 18.0 (22A5338b)

**Append a debug log**

[debug-Tue_Aug_27_21_09_01_2024.log](https://github.com/user-attachments/files/16768484/debug-Tue_Aug_27_21_09_01_2024.log)

**Comment by cagnulein** [comment]
Hi, disable the virtual Bluetooth device setting in the experimental setting and restart Qz
Let me know!

**Comment by pifiuk** [comment]
> Hi, disable the virtual Bluetooth device setting in the experimental setting and restart Qz Let me know!

That seem's to have done the trick. Thanks
