### ISSUE TITLE
Unable to connect pixel watch qz to qz on pixel 7 phone

### ISSUE THREAD

**Issue by cqmetal** [cagnulein/qdomyos-zwift#2546]
Initially was trying to pass along play store pixel watch qz heart rate to Amazon app store qz on echelon bike via play store qz on pixel 7 phone.

Was able to see heart rate on pixel 7 phone from pixel watch only once (and never on echelon qz). Now can't even see pixel watch heart rate on pixel phone qz. Pixel watch does not show up on heart rate devices list on pixel phone qz.  
[debug-Tue_Aug_27_16_35_18_2024.log](https://github.com/user-attachments/files/16769391/debug-Tue_Aug_27_16_35_18_2024.log)

**Comment by cqmetal** [comment]
Restarted watch and phone a few times and it worked

**Comment by cagnulein** [comment]
That’s great

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 28 ago 2024 alle 00:56 cqmetal ***@***.***> ha
scritto:
