### ISSUE TITLE
[BUG] Domyos Challenge Bike crashes app (iOS 18.0)

### ISSUE THREAD

**Issue by A-James** [cagnulein/qdomyos-zwift#2549]
**Describe the bug**
The qdomyos-zwift app crashes to home screen around 1 second after connecting to the Domyos Challenge Bike. I have tried restarting the phone, and the bike, as well as updating to the newest iOS and app. Results always the same.

Appears to be same symptoms as previously reported / marked fixed Android bug: https://github.com/cagnulein/qdomyos-zwift/issues/2120 

**To Reproduce**
1 turn on the bike
2 start qz domyos app
3 qz domyos app connects with bike for a second, dashboard displays for a second
4 app crashes to homescreen

**Expected behavior**
App does not crash after bluetooth connection established.

**Smartphone (please complete the following information):**
 - OS: iOS 18.0 (note: same behaviour was present on iOS 17.X before I updated my phone)
 - iPhone 15 Pro Max
 - Domyos Challenge Bike

**Append a debug log**

Debug  logs attached

[debug-Thu_Aug_29_12_06_06_2024.log](https://github.com/user-attachments/files/16798104/debug-Thu_Aug_29_12_06_06_2024.log)
[debug-Thu_Aug_29_12_06_25_2024.log](https://github.com/user-attachments/files/16798105/debug-Thu_Aug_29_12_06_25_2024.log)

**Comment by cagnulein** [comment]
hi 
send me an email to roberto.viola83 at gmail.com indicating this ticket Thanks

**Comment by A-James** [comment]
App no longer crashes in Testflight version. Confirmed twice.

Many thanks!

**Comment by cagnulein** [comment]
amazing!
