### ISSUE TITLE
[BUG] s15i connection to zwift

### ISSUE THREAD

**Issue by AtheChris** [cagnulein/qdomyos-zwift#2550]
**Describe the bug**
s15i bike with the QZ companion.  Have tried qz on the iphone and PC with the ip address set under bike, Tiles show data reaching the app however nothing is reaching zwift.  Noted that Zwift is running however has no option to connect a controller?  I'm sure is a small setting i have wrong somewhere but cant find a fix.

**To Reproduce**
1. start bike
2. start application
3. start zwift

**Expected behavior**
Zwift to recieve data from the qz application 
[debug-Thu_Aug_29_12_43_03_2024.log](https://github.com/user-attachments/files/16798523/debug-Thu_Aug_29_12_43_03_2024.log)

**Screenshots**
Log attached ... can add a video if needed.

**Desktop (please complete the following information):**
 - OS: win11 pro
 - Version 23H2

**Smartphone (please complete the following information):**
 - Device: iphone 14
 - OS: 17.6.1
 - Version latest
 - same issue whether using PC or iphone 

**Append a debug log**
debug attached from PC version of QZ  
  
**Additional context**
all devises tested on a separate wifi network to other devices in the house

**Comment by cagnulein** [comment]
Hi, don't you see a wahoo device in the zwift setup pairing screen?
qz is ok from its side from what I can see from the log
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 ago 2024 alle ore 13:54 AtheChris ***@***.***>
ha scritto:

**Comment by AtheChris** [comment]
Thanks for checking.  In Zwift there is a wahoo device for the power source, cadence and resistance but not for the controls.  When I go into a ride no data is coming through.  I have the same running zwift off the PC or the iPhone, same connections no data.

![Screenshot 2024-08-29 181103](https://github.com/user-attachments/assets/89b883a1-8a99-416d-a4a2-074b28a18600)
![Screenshot 2024-08-29 181135](https://github.com/user-attachments/assets/4463af08-273e-4c6b-8833-21a3b7fe7bf0)

**Comment by cagnulein** [comment]
is the firewall disabled on the pc? do you see the right metrics on qz? did you already restart the pc? reinstalled zwift?

**Comment by AtheChris** [comment]
Thanks,

Firewall is off, Metrics come through on the QZ (Speed, incline, resistance all showing, tried on both iphone and PC versions).  PC, QZ and Bike all restarted and zwift reinstalled (cleared out any trace of it) and tried running it from PC and iPhone.  on Both Wahoo is connected for the power but no watts are coming through from QZ to zwift.
Tried, PC qz to PC zwift, iPhone qz to PC zwift, pc qz to iphone zwift

QZ Companion   set to s15i bike
QZ app: IP set, resistance, elevation and speed showing values in the tiles
Zwift set to Wahoo KICKR 0000 33 no controlled found or values coming through

**Comment by AtheChris** [comment]
Thanks those show the wahoo device so qz is def doing something.  Tried MyWhoosh as well as Zwift today but both have the same issue.

**Comment by cagnulein** [comment]
So it's definitely something or the pc or the network that it's filtering
broadcast frames. Are you able to connect the pc to the wifi casted from
the iPhone to test it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 30 ago 2024 alle 19:20 AtheChris ***@***.***>
ha scritto:

**Comment by AtheChris** [comment]
Tried phone and pc hotspots, created a new private guest network network with no other devices, but no difference with Zwift and mywoosh.  Qz doesn’t show a device name but the info comes through on the tiles.  Have reset pc and s15i, firewalls all off so everything was default but no luck.  Open to any ideas what to try as I really resent the price of ifit now 💸.  Appreciate all the help given.

**Comment by cagnulein** [comment]
Did you already try to use Qz on the same pc?

**Comment by AtheChris** [comment]
Yip tried pc running qz with Zwift and mywoosh.  Qz shows no device name but tiles have speed, incline and resistance coming through from the s15i.  Zwift has wahoo device showing but again no data comes through to it.

**Comment by cagnulein** [comment]
Are you sure you selected the wahoo kickr on zwift and not the wahoo hrm?

**Comment by AtheChris** [comment]
Sorry for the late reply … been away with work.  Yes it’s selected.  Here is 
![IMG_3955](https://github.com/user-attachments/assets/28822fb0-8375-4560-912a-1b974de44c07)
the images of Qz and the mywoosh.  Data is hitting qz and wahoo is picked up.
![IMG_3954](https://github.com/user-attachments/assets/aed1f694-4d96-4aa2-9d20-9c900821dbc2)
Don’t know what else I can try to be honest except find an android phone maybe?

**Comment by cagnulein** [comment]
Did you enable the mywhoosh compatibility setting in the experimental settings?

**Comment by AtheChris** [comment]
Thanks for the patience; I get exactly the same if I connect in Zwift as well. Qz is version 2.15 (latest available on iOS?) and doesn’t seem to have that mywoosh setting.  
![IMG_3956](https://github.com/user-attachments/assets/9636bca9-b550-4bbd-a857-d8ece529341d)

**Comment by cagnulein** [comment]
Enable the wahoo rgt compatibility so, I renamed it in the last beta

Let me know!

**Comment by AtheChris** [comment]
Thanks ... tried that and it had no effect.
Have just reset / reinstalled everything ... all devices put on a separate wifi network:
On the S15i bike: reset bike to factory settings, (ifit update blocked by blacklisting the web addresses on the router), developer debug option on, installed QZ and set it to s15i, 
QZ App: fresh installation, set the IP address, virtual device settings on, tried with mywoosh setting on and off as well (tried on windows and iphone versions) ... Computer firewall is off
Speed comes through to the QZ app on both iphone and windows versions (no watts or cadence and just shows 0).  
Zwift and mywoosh will both find the wahoo device but dont receive values (both on PC and iphone)

Anything I've missed there that you can think of?  Having a quick look at previous issues 2368 sounds similar and was on the same bike.

Appreciate the fast replies and help given.  I'm still hoping there is a magic setting that gets it all working.  But accepting I've got something setup wrong and I make have to fall back to ifit for the winter.

**Comment by cagnulein** [comment]
Hah wait the main issue is the power value is to 0, could you please upload a fresh debug log from qz? It should be easy to fix! Let me know

**Comment by AtheChris** [comment]
Here are the logs from the bike and the PC version of QZ.  Thanks!

[from s15i.zip](https://github.com/user-attachments/files/17034744/from.s15i.zip)
[PC debug-Tue_Sep_17_21_36_02_2024.log](https://github.com/user-attachments/files/17034745/PC.debug-Tue_Sep_17_21_36_02_2024.log)

**Comment by cagnulein** [comment]
@AtheChris Thanks. Did you collect the adb logcat while you were still on the workout? Because I don't see any metrics there

If it's so that's the reason. In case we can switch approach to the OCR engine

I can do this in the next days, I'm on a business trip


Let me know

**Comment by AtheChris** [comment]
[logcat.txt](https://github.com/user-attachments/files/17040069/logcat.txt)
[logcat.log](https://github.com/user-attachments/files/17040070/logcat.log)

These are the files retrieved from the ado_debug.  Sorry I thought Id included them in that last zip.  

No rush, appreciate the help and know you're busy.
Thanks

**Comment by cagnulein** [comment]
Ok, I'll take a look.
i'm on a business trip, it could take some days

Il giorno mer 18 set 2024 alle 09:21 AtheChris ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
yes seems so. ok let's change approach, let's use this one https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10887476182/artifacts/1938458708
this will use OCR to send metrics to qz, so you will see a requst to record the screen on the ifit tablet
Let me know!

**Comment by AtheChris** [comment]
Loaded the APK onto android ... and we have some movement in Zwift!  Thanks for getting that version over ... I very much appreciate the patience and help with this!
[logcat.txt](https://github.com/user-attachments/files/17065657/logcat.txt)

Power comes through though drops off regularly ... Could I check:
- The ifit app continually switches within the manual exercise between paused and resumed every sec or so.  This only happens when the iphone or PC QZ app connects ... I had noticed this previously as well so its not specific to the apk thats just loaded.
- Power shown in zwift keeps dropping to 0 (tried mywoosh has this as well but the power doesnt come through properly as it was dropping to 0 more regularly) ... guessing this is linked to the continual pausing of the app?
- Power shown in ifit is not whats seen in zwift ... I think I read there was a different calculation of power?  Is there a setting that can be adjusted to spoof it so its the same in zwift (not sure if the pause issue causes the difference).?

Again, I'm really thankful for the efforts with this!

**Comment by cagnulein** [comment]
great! could you please also provide a debug log from qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 19 set 2024 alle 22:10 AtheChris ***@***.***>
ha scritto:

**Comment by AtheChris** [comment]
[debug-Thu_Sep_19_20_49_20_2024.log](https://github.com/user-attachments/files/17065832/debug-Thu_Sep_19_20_49_20_2024.log)

**Comment by cagnulein** [comment]
thanks i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 19 set 2024 alle 22:13 AtheChris ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
> * The ifit app continually switches within the manual exercise between paused and resumed every sec or so.  This only happens when the iphone or PC QZ app connects ... I had noticed this previously as well so its not specific to the apk thats just loaded

this is because qz is trying to change the resistance of the bike. do you selected the s15i device in the companion?



> * Power shown in zwift keeps dropping to 0 (tried mywoosh has this as well but the power doesnt come through properly as it was dropping to 0 more regularly) ... guessing this is linked to the continual pausing of the app?

fixed! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10957673863/artifacts/1957652432



> * Power shown in ifit is not whats seen in zwift ... I think I read there was a different calculation of power?  Is there a setting that can be adjusted to spoof it so its the same in zwift (not sure if the pause issue causes the difference).?

no qz is sending exactly what it saws from ifit. do you see the same value on qz and ifit? maybe it was about the pause issue, in case we have to first fix this. let's see if the power now it comes correctly

**Comment by AtheChris** [comment]
thanks ... that version doesnt return any values to the app from the device (speed, power, cadence etc).  The only value that seemed to change was the elevation that read at 10x the bikes value.

**Comment by cagnulein** [comment]
do you have the log? it's the only way to fix it

**Comment by AtheChris** [comment]
sorry forgot to add them.
[logcat.log](https://github.com/user-attachments/files/17079977/logcat.log)
[logcat.txt](https://github.com/user-attachments/files/17079978/logcat.txt)
[debug-Fri_Sep_20_20_12_48_2024.log](https://github.com/user-attachments/files/17079979/debug-Fri_Sep_20_20_12_48_2024.log)

logs from the bike and from the windows app (same result using iphone)

**Comment by cagnulein** [comment]
Thanks, I'll check them out in the next days!


Il giorno ven 20 set 2024 alle 21:17 AtheChris ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @AtheChris i checked the log but the logcat.txt and logcat.log seems to be before the qz log. can you do a little session while you're capturing the logcat.log so i can check the issue?
thanks

**Comment by AtheChris** [comment]
No worries ... I thought they were so apologies ... These ones have just been captured now changing the speed, resistance and incline on the bike.

The only value I could see coming through and altering on the qz app was the incline as I changed it on the bike (speed, cadence, watts, resistance didnt change).  When I set the bike to 3deg it was showing as 30 in QZ, then jumped to 75deg etc ...

[logcat.log](https://github.com/user-attachments/files/17085301/logcat.log)
[logcat.txt](https:
[debug-Sat_Sep_21_18_51_07_2024.log](https://github.com/user-attachments/files/17085304/debug-Sat_Sep_21_18_51_07_2024.log)
//github.com/user-attachments/files/17085302/logcat.txt)

I owe you a few cups of coffee now I think!

**Comment by cagnulein** [comment]
Thanks, I will check them ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 21 set 2024 alle 20:01 AtheChris ***@***.***>
ha scritto:

**Comment by AtheChris** [comment]
no worries, I thought I had ... this one is taken from the bike using ADB_Debug.bat during the exercise ... 19:27 the elevation changed on the app but everything else was showing as 0 the rest of the time.

[logcat.txt](https://github.com/user-attachments/files/17102505/logcat.txt)
[logcat.log](https://github.com/user-attachments/files/17102506/logcat.log)
[debug-Mon_Sep_23_19_25_34_2024.log](https://github.com/user-attachments/files/17102552/debug-Mon_Sep_23_19_25_34_2024.log)

Thanks

**Comment by cagnulein** [comment]
Thanks I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 set 2024 alle 20:34 AtheChris ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
perfect now the log is perfect, let me check the issue!

**Comment by cagnulein** [comment]
@AtheChris i guess i fixed them! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11010660989/artifacts/1970559335
Let me know!

**Comment by AtheChris** [comment]
Thank You Mr Wizard ... you seem to have worked your magic!

[logcat.txt](https://github.com/user-attachments/files/17137673/logcat.txt)
![image](https://github.com/user-attachments/assets/5fabe820-93aa-4cc4-8441-6af9055cc9ad)

That one works much better!  Movement in Zwift and mywoosh.  There is a lag on watts (see screenshot) and some strange results with elevation if you use that but it seems usable and to be working!

Appreciate all the hard work on this one, dont know how you find the time to answer all the questions on here and the facebook group!

**Comment by cagnulein** [comment]
> Thank You Mr Wizard ... you seem to have worked your magic!
> 
> 
> 
> [logcat.txt](https://github.com/user-attachments/files/17137673/logcat.txt)

amazing! 


> 
> 
> 
> That one works much better!  Movement in Zwift and mywoosh.  There is a lag on watts (see screenshot) and some strange results with elevation if you use that but it seems usable and to be working!

How many seconds of lag? Unfortunately the tablet doesn't have a high cpu capacity to do a great ocr. With @victorypoint we are experimenting a ai.server that runs locally to fix this

Unfortunately in the logcat I don't see the current workout so I can't understand the wattage issue, if you will have a new one the next workout I will check it: remember to collect it while you are doing the workout 

> 
> 
> 
> Appreciate all the hard work on this one, dont know how you find the time to answer all the questions on here and the facebook group!
> 
>  

i don't me neither, it's 10pm here with my daughter on my legs while im answering you :)
