### ISSUE TITLE
Qz sets inclination to -15 on sole f85 treadmill, whenever zwift sends negative inclination 

### ISSUE THREAD

**Issue by Santa87-cyber** [cagnulein/qdomyos-zwift#2552]
**Describe the bug**
When using zwift on a hilly route, whenever the route goes downhill I.e. negative inclination, QZ sets inclination to 15 on my sole f85 treadmill.

**To Reproduce**
1. Open QZ and connect to Sole F85
2. Open Zwift and connect to wahoo tread 003.
3. Find a route that has negative inclination
4. See that inclination on treadmill increases to 15, whenever inclination drops below 0 in zwift

**Expected behavior**
I am unsure what I would expect, as treadmill cannot decline but only goes from 0-15. I think I would however expect incline to be 0, whenever zwift incline was <= 0, and 15 whenever zwift incline was >=15.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung zfold 5
 - OS: android 
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
ok thanks, i need the debug log to check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 29 ago 2024 alle ore 14:52 Santa87-cyber <
***@***.***> ha scritto:

**Comment by Santa87-cyber** [comment]
[inbound6238579147790698094.zip](https://github.com/user-attachments/files/16799557/inbound6238579147790698094.zip)

**Comment by Santa87-cyber** [comment]
I am unsure if I have grabbed the right version, or if I should change a setting or something, but the issue seems to persist for me: as soon as inclination drops to -1 in zwift, inclination on treadmill goes to 15.

**Comment by cagnulein** [comment]
grab another debug log, i did a critical part of code without the possibility to test it so i could did something wrong

**Comment by Santa87-cyber** [comment]
Alright, will do tomorrow, it's getting quite late here. Thank you for all your help

**Comment by Santa87-cyber** [comment]
[inbound4617813242840690822.zip](https://github.com/user-attachments/files/16812370/inbound4617813242840690822.zip)
![inbound6894115374025363586](https://github.com/user-attachments/assets/5fba75ee-d227-485c-b1e0-eb77b6645830)
![inbound3805644962983787510](https://github.com/user-attachments/assets/44d78de8-2a0f-489e-b87c-50c3397a66df)

**Comment by cagnulein** [comment]
Good Morning @Santa87-cyber unfortunately the zip is corrupted, can you upload it again? thanks

**Comment by Santa87-cyber** [comment]
[inbound6168197252105030235.zip](https://github.com/user-attachments/files/16813408/inbound6168197252105030235.zip)

**Comment by Santa87-cyber** [comment]
Try this one. If still corrupted I will have to create a new log 🙃

**Comment by cagnulein** [comment]
got it now, i'm checking it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 30 ago 2024 alle ore 09:36 Santa87-cyber <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok i guess i have a workaround in the meantime. go into the qz settings, treadmill, and set the min inclination to 0 instead of -100 this should fix the issue.
also, in the meantime, could you please download the free app nrfconnect from the store, connect to the treadmill with it and go into the characteristics page, scroll to the ftms service and check for a inclination supported characteristic. could you please share me a screenshot of it? i would like to check why i can't read it.
Thanks

**Comment by Santa87-cyber** [comment]
Tried connecting to treadmill through app. Could not find anything in the app called characteristics or ftms sevice
![inbound6315463658727423236](https://github.com/user-attachments/assets/94605ea2-8d2e-40ef-810d-9a9e24b5aaf1)

**Comment by cagnulein** [comment]
tes click connect there and then you will see the list of all the services

**Comment by Santa87-cyber** [comment]
![inbound5685527962759967679](https://github.com/user-attachments/assets/e1e4a5d8-4a23-4568-b411-0116055ba039)
![inbound3663764882449213962](https://github.com/user-attachments/assets/2c99e5cf-5bb0-4766-9e3f-9254b394b799)

Is this what you are looking for? Should I Bond the treadmill?

**Comment by Santa87-cyber** [comment]
![inbound3772064082768386805](https://github.com/user-attachments/assets/21aa85fb-8f93-4109-b7fd-0abf3b0fcc9c)
![inbound7106074573486957681](https://github.com/user-attachments/assets/4db09d3c-ccd1-497d-92ae-8fa31f4b0971)
![inbound208819695834788782](https://github.com/user-attachments/assets/3c75b797-91cf-4cf4-bbcf-62d92f9caaad)
![inbound8171154266206341769](https://github.com/user-attachments/assets/4674e7a7-7799-4237-a32e-ac00a48acd75)

**Comment by cagnulein** [comment]
thanks! in the meantime try to change the min inclination setting and let me know if it works correctly

**Comment by Santa87-cyber** [comment]
Just tested with min inclination set to 0, and it seemed to do the trick.. will that also work in the app in Google play, or only in the version you have here on github?

**Comment by cagnulein** [comment]
yes it should work also on the play store version. i will check if i can do
this automatically with the patch so anyone in this situation would not  to
do this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 30 ago 2024 alle 12:51 Santa87-cyber ***@***.***>
ha scritto:
