### ISSUE TITLE
[BUG] App does not work with WalkingPad G1

### ISSUE THREAD

**Issue by b3nd1k** [cagnulein/qdomyos-zwift#2557]
I just got the WalkingPad G1, and while it appears as ‘Found’ in the QZ app, the app can’t read or control the treadmill’s speed. I’ve attached the debug log as requested.
[debug-Fri_Aug_30_11_07_04_2024.log](https://github.com/user-attachments/files/16814644/debug-Fri_Aug_30_11_07_04_2024.log)

**Comment by cagnulein** [comment]
simple fix: you need to disable the ftms treadmill setting. press ok and then restart qz
let me know!

**Comment by b3nd1k** [comment]
> simple fix: you need to disable the ftms treadmill setting. press ok and then restart qz let me know!

That fixed the issue.
