### ISSUE TITLE
[BUG] NPE Runn sensor fantasy values

### ISSUE THREAD

**Issue by geierf1** [cagnulein/qdomyos-zwift#2558]
**Describe the bug**

NPE Runn sensor (BBB0632C) connected, but shows fantasy values for speed and incline (real values should be 3.5 kph and 0.2% incline).

**To Reproduce**
Well, I am using the app as fake treadmill, no device fake, and with Runn connected. HR and Cadence from AW works fine. 

**Expected behavior**
expect the correct values being used

**Screenshots**
see attached file

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS 17.6.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12

**Append a debug log**
[debug-Sa__Aug__31_15_18_01_2024.log](https://github.com/user-attachments/files/16824849/debug-Sa__Aug__31_15_18_01_2024.log)
![Sa  Aug  31 15_20_47 2024](https://github.com/user-attachments/assets/cbbcd8f8-f5b3-48ab-8e77-c313753bcd7c)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
No Zwift, no Strave connected

**Comment by cagnulein** [comment]
Hi @geierf1unfortunately the log file is corrupted, could you please create another?

**Comment by geierf1** [comment]
It does not even show values for speed unless I select the +button in the tile.

Sending all files:
![Sa  Aug  31 15_53_03 2024_resistance](https://github.com/user-attachments/assets/a95ab222-80c3-4959-80ca-9b33658ff889)
![Sa  Aug  31 15_53_04 2024_speedInclination](https://github.com/user-attachments/assets/66512be2-2b14-4e1e-b05a-25c710498feb)
![Sa  Aug  31 15_53_04 2024_power_badge](https://github.com/user-attachments/assets/5bbfaa42-f38b-4e7e-97b3-885c5e11e966)
[debug-Sa__Aug__31_15_48_25_2024.log](https://github.com/user-attachments/files/16824915/debug-Sa__Aug__31_15_48_25_2024.log)
![Sa  Aug  31 15_53_04 2024_cadence](https://github.com/user-attachments/assets/f5ecb018-906f-4ac6-9ca0-cdd5adca4f21)
![Sa  Aug  31 15_53_03 2024_pelotonresistance](https://github.com/user-attachments/assets/a11afd0f-ebce-48c1-972e-fde55cfca520)
![Sa  Aug  31 15_53_04 2024_powerDistribution](https://github.com/user-attachments/assets/5faa1c1e-8ba9-4816-9f92-e89e9337c985)
![Sa  Aug  31 15_53_04 2024_power](https://github.com/user-attachments/assets/0b847c16-a80c-4cf0-993c-de45f8f88a72)
![Sa  Aug  31 15_53_02 2024](https://github.com/user-attachments/assets/30f9c246-4751-4e78-adac-83333fcc34d5)
![Sa  Aug  31 15_53_04 2024_heart](https://github.com/user-attachments/assets/62f23f5b-ae5e-4593-82d5-8b8f26da4f1c)

**Comment by cagnulein** [comment]
i guess you have some settings wrong but both debug log are corrupted. close qz before sending me it otherwise i'm missing the important header 

thanks

**Comment by geierf1** [comment]
I did close it (and removed from history of running apps). I can read the log - not sure what you mean with corrupted though. Maybe you are missing some entries you expected. 

Anyways - it seems that your app is not for me. I am struggling to understand about half of the settings, but I understand that my use case might be niche only (not using it for Zwift). 

I will continue using runcline, or workoutdoors. I was looking for an alternative as I am not entirely happy with the way these store values in Apple Health, leading to issue with cadence. Have a great day. I will send the S10 pictures in reddit.

**Comment by cagnulein** [comment]
please don't give up, i just need the debug log to understand your setup issue :) about the settings just ask :)


check this debug log for example, do you see all the settings on the top? 

[debug-Fri_Aug_30_14_09_04_2024.log](https://github.com/user-attachments/files/16824981/debug-Fri_Aug_30_14_09_04_2024.log)

**Comment by geierf1** [comment]
If I just open the app and close it again, I have a similar file. Is this more useful?
[debug-Sa__Aug__31_16_09_43_2024.log](https://github.com/user-attachments/files/16825017/debug-Sa__Aug__31_16_09_43_2024.log)

**Comment by cagnulein** [comment]
yes this shows the main issue! you enabled the fake treadmill in the
experimental settings!

this, indeed, fake a treadmill! so disable it and you should be fine then

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 31 ago 2024 alle 16:24 geierf1 ***@***.***> ha
scritto:

**Comment by geierf1** [comment]
If I disable the fake treadmill setting, I do not get tiles with the Runn as sensor. It just stays on the grey screen.

 That was the original reason I set this - to allow the phone to show my data.

**Comment by cagnulein** [comment]
share a nrfconnect screenshot about the runn , i will tell you how to setup
it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 31 ago 2024 alle 16:46 geierf1 ***@***.***> ha
scritto:

**Comment by geierf1** [comment]
nrfconnect
![IMG_5990](https://github.com/user-attachments/assets/e399a49b-a599-41d6-a41a-9f72806f8dfd)
![IMG_5993](https://github.com/user-attachments/assets/bc559941-c666-4a76-b8e9-6798f1504310)
![IMG_5992](https://github.com/user-attachments/assets/52602677-6d23-4c79-a8b0-b0cde80d9b95)
![IMG_5991](https://github.com/user-attachments/assets/0b3ca9b1-fb3a-4856-a9c9-23e738e3bba7)
![IMG_5994](https://github.com/user-attachments/assets/6415c146-ae2f-4b9f-98a5-48ad16cd6574)
![IMG_5995](https://github.com/user-attachments/assets/ec95492c-c742-43ca-a94f-363d3a980035)
![IMG_5996](https://github.com/user-attachments/assets/8c8116a1-dd94-414b-acf7-5685430ccff8)

**Comment by cagnulein** [comment]
perfect! set it under the manual device setting and also set it under the ftms treadmill in the treadmill setting. if you don't see the ftms treadmill setting, send me your email on reddit and i will send you the new beta!

**Comment by geierf1** [comment]
Yeah, unfortunately no FTMS setting in the treadmill options. There seem to be some under individual treadmills (eg Bodytone) but maybe the beta would be better?

**Comment by cagnulein** [comment]
yes you will see the option in the beta

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 31 ago 2024 alle 17:21 geierf1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
so we are ok with this @geierf1  ?

**Comment by geierf1** [comment]
Yes, it is fine, thank you.

A few things I noticed:
-The cadence displayed seems to be halfed. Not a problem, just unusual. 
- As you said, cadence is not visible in the Apple Fitness charts. Average cadence is however noted in 3rd party apps like Healthfit and Gentler Streak. Both are showing different average values though (Gentler Streak looks more plausible).
- The watch start and stop is taken as the main workout values, starting the dashboard on the phone probably has no effect. It might be nice to sync that with the watch state, if possible.
- The incline matches with NPE Runn. You could consider calculating the „virtual height gain“ and write it to AH, but I know no other app doing this.

thanks again for all your help!

For completeness, would you also send me the required settings for Stryd? I only use it rarely, but just in case I run in a hotel gym one day :)

cheers
Frank

**Comment by cagnulein** [comment]
> Yes, it is fine, thank you.
> 
> 
> 
> A few things I noticed:
> 
> -The cadence displayed seems to be halfed. Not a problem, just unusual. 

it depends if you are considering for one leg or 2 legs :) 

try to toggle this

![image](https://github.com/user-attachments/assets/7d7c4fc8-7997-44fe-8880-17a28de2afaa)

> 
> - As you said, cadence is not visible in the Apple Fitness charts. Average cadence is however noted in 3rd party apps like Healthfit and Gentler Streak. Both are showing different average values though (Gentler Streak looks more plausible).

ok so i guess it's writable too. are you sure that healthfit writes for indoor runs?

> 
> - The watch start and stop is taken as the main workout values, starting the dashboard on the phone probably has no effect. It might be nice to sync that with the watch state, if possible.

yes i did already the code for this on a PR, i need the time to test some edge cases

> 
> - The incline matches with NPE Runn. You could consider calculating the „virtual height gain“ and write it to AH, but I know no other app doing this.
> 

as far as i know AH doesn't allow this for indoor runs. qz is already writes it to strava for example

> 
> 
> thanks again for all your help!
> 

no problem! remember to rate the app and the support on the store if you didn't already, it means a lot to me!

> 
> 
> For completeness, would you also send me the required settings for Stryd? I only use it rarely, but just in case I run in a hotel gym one day :)
> 
> 

simply set it in the power sensor setting. you can also decide if enabling the speed from power sensor setting if you want to use the speed from the stryd instead of the treadmill ones (if you are using the stryd without a bluetooth treadmill you need also to enable the power sensor as a treadmill setting)

> 
> cheers
> 
> Frank
> 
>

**Comment by geierf1** [comment]
What I meant with cadence average values in Gentler Streak and Healthfit is that these apps extract the average cadence value from your (QZ) log in Apple Health. Healthfit only displays workouts, it does not record them.

But… Healthfit shows 120, Gentler Streak shows 153 (probably correct), and Rungap / Garmin show 60, with an average step length of 2.65m 😃

I will try to double the cadence, thanks.

On a side note, there is probably a reason you placed the cadence doubling switch in the power sensor settings section (biking or Stryd, I presume). But you might consider moving the cadence switch to the cadence section of the settings - it really has nothing to do with a power sensor settings, in my opinion. I am not even registering the Runn sensor as a power sensor - it does deliver cadence, but does not deliver power. 

All the best!

**Comment by cagnulein** [comment]
> What I meant with cadence average values in Gentler Streak and Healthfit is that these apps extract the average cadence value from your (QZ) log in Apple Health. Healthfit only displays workouts, it does not record them.

hah yes because qz is writing it on apple health every seconds, so they read them and they are calcuating the average, makes sense.



> But… Healthfit shows 120, Gentler Streak shows 153 (probably correct), and Rungap / Garmin show 60, with an average step length of 2.65m 😃

hahaha i love the software guys :D



> But you might consider moving the cadence switch to the cadence section of the settings - it really has nothing to do with a power sensor settings, in my opinion. I am not even registering the Runn sensor as a power sensor - it does deliver cadence, but does not deliver power.

i put it there because originally was for the stryd sensor that has power and cadence and that's the most used sensor for running. i can also put it on the cadence section but in the end the module used even for the RUNN device is the power sensor source code in QZ

**Comment by cagnulein** [comment]
@geierf1 are we ok with this?
