### ISSUE TITLE
[BUG] Master Fitness T25 treadmill connect issue

### ISSUE THREAD

**Issue by krirau** [cagnulein/qdomyos-zwift#2559]
Hi,

Master Fitness T25 treadmill connects, starts treadmill then drops connection.
iOS 17.6.1 
Was able to control treadmill with nrfconnect and commands from FTMS, as with Kinni App for testing. 

 

![nrfconnect](https://github.com/user-attachments/assets/b2bfde1a-7be6-40e1-895c-cbbfa16b32ee)

**Comment by cagnulein** [comment]
first of all which version do you have of qz? if 2.15 please send me an email to roberto.viola83 at gmail.com to get the new beta to confirm that you have the same issue with the latest one

**Comment by krirau** [comment]
> first of all which version do you have of qz? if 2.15 please send me an email to roberto.viola83 at gmail.com to get the new beta to confirm that you have the same issue with the latest one

Thanks for quick reply, version 2.15.4.

**Comment by cagnulein** [comment]
so send me the email :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 31 ago 2024 alle 17:18 krirau ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@krirau are we ok with this?

**Comment by krirau** [comment]
Yes, thanks for the support.
Kristian

man. 30. sep. 2024 kl. 07:50 skrev Roberto Viola ***@***.***>:
