### ISSUE TITLE
Fitbike Ride 6 iPlus

### ISSUE THREAD

**Issue by Berkers06** [cagnulein/qdomyos-zwift#2560]
**Describe the bug**
[debug-Sun_Sep_1_18_27_36_2024.log](https://github.com/user-attachments/files/16829752/debug-Sun_Sep_1_18_27_36_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi enable the toorx iconsole bike setting in the toorx console section
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 set 2024 alle 18:42 Berkers06 ***@***.***> ha
scritto:

**Comment by Berkers06** [comment]
THANKS! That did the trick

**Comment by cagnulein** [comment]
That's great!
