### ISSUE TITLE
[BUG] Cannot use ERG mode in BKool

### ISSUE THREAD

**Issue by AndrewCrystal** [cagnulein/qdomyos-zwift#2561]
Hi Roberto,

Please find attached the logs from this afternoon.

The first one is when I open the Bkool app and connect up, seems to work fine and picks up cadence but no distance so the rider never starts moving.  If I disconnect and reconnect a few times or sometimes use forget device then it seems to start working eventually.

Second one is after closing the Bkool app and opening the Bkool spin studio it won't detect an ERG even though that box is ticked in QZ.

Debug logs and photos attached.

Thanks, 

Andrew

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Mon_Sep_2_15_14_41_2024.log](https://github.com/user-attachments/files/16838883/debug-Mon_Sep_2_15_14_41_2024.log)

[debug-Mon_Sep_2_15_08_51_2024.log](https://github.com/user-attachments/files/16838886/debug-Mon_Sep_2_15_08_51_2024.log)
![Screenshot_20240902_151459](https://github.com/user-attachments/assets/57d06319-248f-4218-8c43-49ee9594be9f)
![20240902_151323](https://github.com/user-attachments/assets/9fa88ed3-c9ce-40f2-8d3c-c8afb4880b28)
![20240902_151239](https://github.com/user-attachments/assets/bf9aa934-1488-4cce-8368-86be3fdbcb2d)
![20240902_151129](https://github.com/user-attachments/assets/c6738778-451c-47be-b7e3-4339bf869541)
![20240902_151053](https://github.com/user-attachments/assets/f466ef3e-e289-4e07-aa98-a7b0a559d44f)
![20240902_151026](https://github.com/user-attachments/assets/a3dfacdc-c994-46e7-b4e4-cb5d0b9c08c1)
![20240902_151002](https://github.com/user-attachments/assets/67e66139-8ab7-4b68-91be-057cffcf932d)

**Comment by cagnulein** [comment]
Thanks, I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 set 2024 alle 16:38 AndrewCrystal ***@***.***>
ha scritto:

**Comment by AndrewCrystal** [comment]
Thanks Robert, if it's BKool specific I wouldn't worry too much as I'm only on a free trial and if it's going to be hit and miss I'll proabably try MyWhoosh or Zwift instead - every chance it's a user error as well! 😉

**Comment by cagnulein** [comment]
hi @AndrewCrystal i tried to download the logs here but it returns an error. can you please upload them again? thanks

**Comment by AndrewCrystal** [comment]
Will try again 1 log at a time as it said it was too large...

**Comment by cagnulein** [comment]
zip them

**Comment by AndrewCrystal** [comment]
[QZ debug logs.zip](https://github.com/user-attachments/files/16845426/QZ.debug.logs.zip)

**Comment by cagnulein** [comment]
log checked @AndrewCrystal 
there is indeed a major setting issue. You have to disable the "Cycling Cadence Sensor (Peloton compatibility)" setting to use erg mode

Let me know!

**Comment by AndrewCrystal** [comment]
Thanks Roberto,

I've disabled that and will try again this afternoon so that will hopefully
sort ERG mode - will it also allow the option to use the SIM mode on Bkool
(if I turn ERG mode back off on QZ?).

Thanks,

Andrew

**Comment by cagnulein** [comment]
> will it also allow the option to use the SIM mode on Bkool (if I turn ERG mode back off on QZ?).

yes exactly and yes for SIM mode you have to disable the erg switch on qz as well

**Comment by AndrewCrystal** [comment]
That's great, thanks Roberto, will try all that out this afternoon and
hopefully will all work fine now, I'd missed the Cadence Sensor setting 🙄

Kind Regards,

Andrew

**Comment by AndrewCrystal** [comment]
Hi Roberto,

Just retried everything with the Cycling Cadence Sensor (Peloton
compatibility) turned off and everything works fine now thanks. 👍

I tried the BKool Spin App in ERG and none ERG mode although that defaults
to auto resistance anyway and also tried the main BKool app in ERG and SIM
mode and they all seemed to work fine with auto resistance based on the
slope as far as I could tell.  It's all very new to me but if I increased
the resistance manually in SIM mode it seemed to reset itself back down -
how would I go faster if racing is it just on cadence?

The only slightly odd thing is that cadence didn't work - this didn't
matter as speed / distance / power were all fine and didn't know if that
was expected too - could see it on QZ anyway so doesn't matter.  I do have
Speed Calculates on Power ticked if that makes any difference?

Thanks for your help,

Kind Regards,

Andrew

**Comment by AndrewCrystal** [comment]
Hi Roberto,

Actually I thought about this some more and wondered if I was on the wrong
track here and overcomplicating it.  On the EX3 the only variables are the
cadence and the resistance level whereas I think I'm trying to mentally add
gears which aren't physically there.  So the resistance matches how steep
the hill is and then how fast you pedal will affect your speed - I presume
you could turn off auto resistance on QZ and increase the resistance
manually for racing if you want to, which would increase the power and
therefore speed too.

On a more expensive trainers I believe that they have gears as well so you
would have cadence, resistance and gears so you could then have the same
resistance (to give the steepness of the slope effectively) and cadence but
the gear would also affect the power output so is there something else to
change and effectively a third variable to add into the power calculation?

Think I'm just overcomplicating this in my mind! lol

Regards,

Andrew

**Comment by cagnulein** [comment]
You have gears too in qz! Just enable it in the tiles settings!

**Comment by AndrewCrystal** [comment]
Oh dear now my mind is even more blown!! Virtual gears! 🙂

Thanks Roberto, I'll play around with this some more and hopefully get the
hang of it once I've done some more rides 🙂

Kind Regards,

Andrew

**Comment by cagnulein** [comment]
Glad to hear it!
remember to rate the app on the store if you didn't already ! It means a
lot to me!
Thanks!

Il giorno mar 3 set 2024 alle 20:07 AndrewCrystal ***@***.***>
ha scritto:

**Comment by AndrewCrystal** [comment]
Morning Roberto,

Review left on Play Store 🙂

Thanks,

Andrew

**Comment by cagnulein** [comment]
Awesome, thank you so much!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle ore 10:00 AndrewCrystal <
***@***.***> ha scritto:
