### ISSUE TITLE
[REQ]

### ISSUE THREAD

**Issue by Berkers06** [cagnulein/qdomyos-zwift#2562]
Hello,

I'd like to add the steps calculated from the cycling from the bike if that's possible

**Comment by cagnulein** [comment]
hi @Berkers06 i was thinking that we were talking about treadmill, why we should count steps for bikes? also please detail which bike or treadmill do you have. thanks

**Comment by Berkers06** [comment]
It indeed is a bike. Sorry i thought it was possible for the bike to
convert the info to steps

Op di 3 sep. 2024 08:47 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
i mean the cadence is possible to convert in steps but it's quite useless
information :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle ore 09:55 Berkers06 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i have to do myself in the code, it's not something that you can do, but i don't see how it could be an useful information. steps for walking are not the same effort of steps on the bike. for example you're usually riding at 90rpm on the bike, so I could convert it to 90 steps for minutes, but this is useful? i don't think so.

**Comment by Berkers06** [comment]
That's right. I just thought it would be useful as when calculating
calories burned  using a fitness tracker, but then I think it would be
better to use calculate it using wattage

Op di 3 sep 2024 om 10:05 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
Yes for sure :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle 11:39 Berkers06 ***@***.***> ha
scritto:
