### ISSUE TITLE
[BUG] Zwift play controllers not recognized on Android

### ISSUE THREAD

**Issue by FrenchClimber** [cagnulein/qdomyos-zwift#2564]
**Describe the bug**
I cannot pair the Zwift Play controllers to QZ application
Android version 14
Zwift Play version 1.1.0 on both controllers
QZ version 2.16.66
Wahoo KickR Core well recognized by QZ

**To Reproduce**
1. QZ Option Zwift Play on 
2. Switch on Zwift controllers (blue light flashing)
3. Start QZ
4. Switch on Zwift controllers still flashing blue (and then shut down because it is not paired)

**Expected behavior**
Pairing betwwen QZ and Zwift Play controllers (blue lights on without flashing)

**Smartphone (please complete the following information):**
 - Device: Samsung A54
 - OS: Android
 - Version 14

**Append a debug log**
File inclosed
[debug-Tue_Sep_3_21_05_08_2024.log](https://github.com/user-attachments/files/16853927/debug-Tue_Sep_3_21_05_08_2024.log)

**Comment by cagnulein** [comment]
Hi you need to join the beta
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift
And update the app, let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle 21:29 FrenchClimber ***@***.***>
ha scritto:

**Comment by FrenchClimber** [comment]
I joined the beta, update the QZ app and did the same procedure
Find inclosed the result
Thanks
[debug-Tue_Sep_3_21_43_26_2024.log](https://github.com/user-attachments/files/16854298/debug-Tue_Sep_3_21_43_26_2024.log)

**Comment by FrenchClimber** [comment]
Hi,
I joined the beta, update the QZ app and did the same procedure
Find inclosed the result
Thanks

[debug-Tue_Sep_3_21_49_10_2024.log](https://github.com/user-attachments/files/16854568/debug-Tue_Sep_3_21_49_10_2024.log)

**Comment by cagnulein** [comment]
now the issue is that i can't see anymore the wahoo kickr core, isn't it? i
can't see the right qz version indeed

the right flow should be
- close alll the app
- wake up your wahoo
- wake your play devices
- open qz
- wait that all is connected
- open zwift or any other app

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle 21:57 FrenchClimber ***@***.***>
ha scritto:

**Comment by FrenchClimber** [comment]
Hi Roberto,

Following your procedure, the Zwift Play controllers did pair with QZ.

I launched IndieVelo, paired correctly all devices to QZ and the gears are not switching when I click on the Zwift controllers (It did change when I click up and down in the IndieVelo interface)
Find inclosed the logs

Thanks
[debug-Wed_Sep_4_10_25_35_2024.log](https://github.com/user-attachments/files/16863296/debug-Wed_Sep_4_10_25_35_2024.log)

**Comment by cagnulein** [comment]
i can see the gears changing in QZ (enable the gears tile to see them too) and also the effort will change with it.
indievelo can't update the gears from qz because it doesn't see request it, you have to ask to the indievelo developers to open a channel for qz as zwift does. You can invite the developer here.
Also set the wahoo kickr on the bike settings, ftms bike and press ok.
Let me know!

**Comment by FrenchClimber** [comment]
I set on the gears tile and see that Zwift controllers can set the gears up and down.
I can see "KICKR CORE 498A" in the FTMS Bike option

Unfortunatly, changing the gears from 0 up to 70 on QZ does not affect the resistance of th Kickr Core
Fin inclosed the logs.

Thanks
[debug-Wed_Sep_4_11_19_11_2024.log](https://github.com/user-attachments/files/16866965/debug-Wed_Sep_4_11_19_11_2024.log)

**Comment by cagnulein** [comment]
the problem now is that you don't connect qz as controllable there on
indievelo so qz is not receiving any inclination from it.
You have to set it as controllable in indievelo and then it will work!
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle ore 11:28 FrenchClimber <
***@***.***> ha scritto:

**Comment by FrenchClimber** [comment]
My test was only between QZ and Kickr Core (as you said that IndieVelo cannot update the gears)
I may have missed something in your explanations I guess

**Comment by cagnulein** [comment]
indievelo writes the inclination of the game to qz and qz applies it to the
trainer plus the gears effect.
i didn't add the gears behavior to qz standalone but i can do as well
give it a test with indievelo first

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 11:35 FrenchClimber ***@***.***>
ha scritto:

**Comment by FrenchClimber** [comment]
With IndieVelo on, it is working fine !
Very pleasant to use the Zwift Ride on IndieVelo and not being locked by a provider

Thanks Roberto for the support

**Comment by cagnulein** [comment]
Glad to hear it!
please remember to rate the app on the store! It means a lot to me!
Thanks!

Il giorno mer 4 set 2024 alle 13:51 FrenchClimber ***@***.***>
ha scritto:

**Comment by FrenchClimber** [comment]
Sure, I'll do that
