### ISSUE TITLE
[REQ] Skandika Morpheus Support

### ISSUE THREAD

**Issue by dadude2607** [cagnulein/qdomyos-zwift#2566]
The Skandika Morpheus is not recognized on start (bluetooth name HT2011015332). I have attached a wireshark capture and the datasheet.

it has power, resistance, rotation speed, heart rate. So actually a perfect candidate.

for the log I connected the bike, pedaled a few times and touched the heart rate sensor.

it would be really great if the bike is added.

Thanks and regards
Andre

[Skandika Morpheus.zip](https://github.com/user-attachments/files/16855249/Skandika.Morpheus.zip)

**Comment by dadude2607** [comment]
[Skandika Morpheus.zip](https://github.com/user-attachments/files/16855242/Skandika.Morpheus.zip)

**Comment by cagnulein** [comment]
thanks i will add it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle 22:27 dadude2607 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/10696139694

@dadude2607 
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by dadude2607** [comment]
Perfect, thank you very much. I will test it tomorrow evening and will give you a feedback

**Comment by dadude2607** [comment]
Although I'm not at home to test, I reviewed your code. I see you expanded the size a HT* bluetooth name can be (from 11 to 12). So it should be discovered.

But in skandikawiribike.cpp the heart rate is not read from the packet. But the Morpheus transmits this data (Position 8, after calories high and low). What I see is:

`double skandikawiribike::GetSpeedFromPacket(const QByteArray &packet) {
    uint16_t convertedData = (convertHexToDec(packet.at(2)) * 100) + convertHexToDec(packet.at(3));
    double data = (double)convertedData / 10.0;
    return data;
}

double skandikawiribike::GetWattFromPacket(const QByteArray &packet) {
    uint16_t convertedData = (convertHexToDec(packet.at(9)) * 100) + convertHexToDec(packet.at(10));
    double data = (double)convertedData;
    return data;
}

double skandikawiribike::GetCadenceFromPacket(const QByteArray &packet) {
    uint16_t convertedData = (convertHexToDec(packet.at(2)) * 100) + convertHexToDec(packet.at(3));
    double data = (double)convertedData;
    return data;
}

double skandikawiribike::GetKcalFromPacket(const QByteArray &packet) {
    uint16_t convertedData = (convertHexToDec(packet.at(6)) * 100) + convertHexToDec(packet.at(7));
    return (double)convertedData;
}`

Am I wrong and the heart rate is read in a different file or is the heart rate not added for the Morpheus? Would be cool if the feature was added :)

Next Part is noWriteResistance. I see code for building/sending the resistance (position 2 in this bytearray {0x20, 0x00, 0x00, 0x00, 0x00}):

`noOpData[1] = 0x01;
            noOpData[2] = lastRequestedResistance().value(); // + ((lastRequestedResistance().value() / 10) * 6);
            if (noOpData[2] == 0)
                noOpData[2] = 1;`

So the bool for noWriteResistance is making me wondering. Even in the "supported bikes" list is "Auto Resistance" marked with "no". So, can you tell me if writing resistance to the bike is included or not?

Again: thank you very much for your great work!

Regards 
Andre

**Comment by cagnulein** [comment]
The resistance is already handled, don't worry :) for the HR create a PR
and I will add it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 12:04 dadude2607 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Or of course I can add it in the next days :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 12:09 cagnulein ***@***.***> ha
scritto:

**Comment by dadude2607** [comment]
I forked and made the changes. Will try the changes tomorrow and create a PR if it works :)

Regards
Andre

**Comment by cagnulein** [comment]
Awesome, thanks!


Il giorno mer 4 set 2024 alle 17:05 dadude2607 ***@***.***>
ha scritto:

**Comment by dadude2607** [comment]
PR created. Works for me :)

![HR working](https://github.com/user-attachments/assets/e0e844da-6fe2-46dc-ad4b-2cebb5b7c25a)
