### ISSUE TITLE
[BUG] distance is being recorded before Ride starts

### ISSUE THREAD

**Issue by fooeynet** [cagnulein/qdomyos-zwift#257]
Distance is being recorded/tracked before a ride starts, which ends up messing with Strava graphs when the FIT files are later uploaded. (Strava expects distance values to start at zero, and if they are not they show gaps at the beginning of rides to account for the "missing" corresponding data)

The longer you ride/setup before you hit Start, the bigger the gap will be.

This can be quickly verified by watching the odometer tile:
1. Use auto pause option
2. Start QZ and start pedaling, watch tiles. Odometer starts being tracked
Should either reset or not start until Start button is pressed

![Screenshot_20210410-074313](https://user-images.githubusercontent.com/9012139/114273818-6fa0f980-99d0-11eb-8ed9-dab5e252bcc0.jpg)

**Comment by cagnulein** [comment]
done, it will be available from the 2.6.1 version
