### ISSUE TITLE
[BUG]Proform Carbon TL Connects But Peloton Cannot Force Speed and Incline

### ISSUE THREAD

**Issue by bkeown64** [cagnulein/qdomyos-zwift#2571]
**Describe the bug**
Using the QZ App on Android tablet and/or phone my Carbon TL treadmill will report speed and incline that is manually entered on treadmill, but the Peloton class will not control speed or incline

**To Reproduce**

**Expected behavior**
Upon staring a class, speed and incline should automatically change per coach's speed/incline directions within Peloton app.  

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android Lenovo Tablet P12 running Android 14, Samsung S24 Running Android 14 - same response
 - OS:Android 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
[debugfiles.zip](https://github.com/user-attachments/files/16899570/debugfiles.zip)

  
  
**Additional context**

**Comment by cagnulein** [comment]
You just need to use the ifit app with the treadmill and change the speed and inclination from it without qz to gain the log that I can add in qz as well https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by bkeown64** [comment]
Forgive me for my ignorance, but how will I obtain a log file for QZ if my treadmill is connecting to my tablet that is using the iFit app on that tablet? I am unable to connect simultaneously to iFit and QZ with my treadmill.Sent from my iPadOn Sep 6, 2024, at 1:12 AM, Roberto Viola ***@***.***> wrote:﻿
You just need to use the ifit app with the treadmill and change the speed and inclination from it without qz to gain the log that I can add in qz as well https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by cagnulein** [comment]
@bkeown64 you don't have to use simultaneously the ifit and the qz app for this. Just ifit. Then with the bug reports method described in the link, i will implement in QZ and then you don't have to run ifit anymore

**Comment by bkeown64** [comment]
I just found an article on Bluetooth HCI and how to access what you
were talking about. Now I understand what you  need and will get you that
log file. Thank you for your patience.

**Comment by cagnulein** [comment]
no problem, just follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by bkeown64** [comment]
[bugreport-YT-X705F-QKQ1.zip](https://github.com/user-attachments/files/16966584/bugreport-YT-X705F-QKQ1.zip)

Sorry for the delay in getting this to you.  I had to find an Android tablet that wouldn't require me to go into "ADB Mode".  I ran this bug report along side a Peloton walking class.  The QZ app reports back the speed, inclination, etc. but will just let the speed and incline be controlled by the Peloton instructions provided in the class.  Hoping there is a simple setting that will allow my Proform Carbon TL treadmill to be used with Peloton classes with speed and incline controlled by the class.

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno mer 11 set 2024 alle 18:24 bkeown64 ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
Just wanted to add to this that the same issue happens when connecting with my iPhone and running Peloton on an iPad.  The iPad will show the speed and incline manually entered - the app just won't control the speed or resistance called out by the Peloton coaches/app.

**Comment by cagnulein** [comment]
Ok, I'll check it out.


Il giorno mer 11 set 2024 alle 22:27 bkeown64 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @bkeown64 in the proform treadmill seection in the QZ settings, could you please select the proform_carbon_tl one and restart qz?
let me know if it's better

**Comment by bkeown64** [comment]
As per my previous message, same result even though I did notice the
following additions:

When broadcasting Peloton on an Android device, the Speed and Inclination
blocks now have color indicators for the target speed/inclination and on
iPad it even produced an incline graph under the pace block. Nice touches!

**Comment by bkeown64** [comment]
[debug-Thu_Sep_12_10_03_17_2024.log](https://github.com/user-attachments/files/16981299/debug-Thu_Sep_12_10_03_17_2024.log)

New Debug file attached.  Thanks much for looking into this.

**Comment by cagnulein** [comment]
Ok i'll check it out tomorrow
Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 12 set 2024 alle ore 16:44 bkeown64 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @bkeown64 i tried a little patch

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10845050054

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by bkeown64** [comment]
[debug-Tue_Sep_17_07_40_32_2024.log](https://github.com/user-attachments/files/17027656/debug-Tue_Sep_17_07_40_32_2024.log)

Roberto, attached is the DeBug File for the Carbon TL using QZ on my iPhone 15 Pro Max.  The settings for this should be identical to the settings you provided to me for the Android beta you created for me.

**Comment by cagnulein** [comment]
hi! got the reason! i was waiting your confirmation to merge the branch! ok i'm doing now, remember always to give me a feedback here, otherwise the modification will stay pending. I will send you a new ios beta later. 
send me an email to roberto.viola83 at gmail.com indicating this ticket . Thanks

**Comment by bkeown64** [comment]
No, neither one has worked by controlling speed or resistance. We may be misunderstanding each other.  

If you mean by "working" the Peloton app can report the manually entered speed and the incline of the treadmill as entered by me on the treadmill and then delivered to the QZ app, then on BOTH Android and iOS it "worked" by this definition immediately after installation of the Beta app by reporting the speed and incline on the Peloton app, BUT then did stopped working when attempting to take a second or third class on either Android or iOS.  

If you mean by "working" that the Peloton app actually changes the speed and incline of the treadmill based on the Peloton instructor's callouts, then neither Android or Apple has worked at all.

**Comment by cagnulein** [comment]
Ok so I'm reverting it and I will check again the log. Thanks for the
clarification

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 20:00 bkeown64 ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
Here is a Debug File from my Lenovo P12 Android Tablet.  Same issue as reported above - since the initial class, it will no longer show the speed or incline of the treadmill on the Peloton App nor will it control speed or incline on treadmill.
[debug-Wed_Sep_18_14_25_43_2024.log](https://github.com/user-attachments/files/17048846/debug-Wed_Sep_18_14_25_43_2024.log)

**Comment by cagnulein** [comment]
> [bugreport-YT-X705F-QKQ1.zip](https://github.com/user-attachments/files/16966584/bugreport-YT-X705F-QKQ1.zip)
> 
> Sorry for the delay in getting this to you. I had to find an Android tablet that wouldn't require me to go into "ADB Mode". I ran this bug report along side a Peloton walking class. The QZ app reports back the speed, inclination, etc. but will just let the speed and incline be controlled by the Peloton instructions provided in the class. Hoping there is a simple setting that will allow my Proform Carbon TL treadmill to be used with Peloton classes with speed and incline controlled by the class.

just to be sure, did you collect this with the IFIT app? Qz on this should be completely closed
Let me know!

**Comment by bkeown64** [comment]
No, sir.  Here is the issue

1. I have a Proform Carbon TL treadmill
2. I have a Peloton account that I am wanting to use the Treadmill classes
with on the Proform Carbon TL treadmill
3. I am wanting to use the QZ app to connect my treadmill to the Peloton
app so that when the Peloton instructor says to set your treadmill to 4 mph
and your incline to 6%, the treadmill automatically adjusts to those
settings (4mph/6% incline).

I didn't use iFit because (1) I don't want to subscribe to that service and
(2) How am I able  to provide you with a debug report on how QZ is
responding with the QZ app completely closed?  Also, there would be no need
for me to use the QZ app for this treadmill if I was already subscribed to
iFit.  The primary purpose for wanting to use the QZ app is to provide my
treadmill with additional functionality of connecting to another service
(other than iFit).

Does that make sense?

**Comment by cagnulein** [comment]
yes i understood this but in order to clone the behavior of inclination and speed changes from ifit app, i need that you just install the ifit app on your android , without a subscription, run a manual workout and change the speed and inclination from the ifit app itself while you are collecting the bug report as you already did. 

is it clear?

**Comment by bkeown64** [comment]
I don’t believe that is possible to collect a debug report using qz with my Android  if I am simultaneously connected to both QZ and to iFit. With the same device.  My treadmill does not have an iFit screen built in. I have to use an external tablet or phone wit the iFit app to connect to iFit.Sent from my iPhoneOn Sep 19, 2024, at 11:00 AM, Roberto Viola ***@***.***> wrote:﻿
yes i understood this but in order to clone the behavior of inclination and speed changes from ifit app, i need that you just install the ifit app on your android , without a subscription, run a manual workout and change the speed and inclination from the ifit app itself while you are collecting the bug report as you already did.
is it clear?

**Comment by bkeown64** [comment]
But how do I get the bug report?  I am using your QZ app to generate that report. Sent from my iPhoneOn Sep 19, 2024, at 11:16 AM, Roberto Viola ***@***.***> wrote:﻿
you don't have to use qz at all for this! only ifit and the bug reports as you did before.
then i will integrate the protocol on qz and you don't need to use ifit anymore

**Comment by bkeown64** [comment]
Ok let me see how I can generate a bug report without using your app. I am unable to do so using adb.Sent from my iPhoneOn Sep 19, 2024, at 11:18 AM, Bob Keown ***@***.***> wrote:﻿But how do I get the bug report?  I am using your QZ app to generate that report. Sent from my iPhoneOn Sep 19, 2024, at 11:16 AM, Roberto Viola ***@***.***> wrote:﻿
you don't have to use qz at all for this! only ifit and the bug reports as you did before.
then i will integrate the protocol on qz and you don't need to use ifit anymore

**Comment by cagnulein** [comment]
> [bugreport-YT-X705F-QKQ1.zip](https://github.com/user-attachments/files/16966584/bugreport-YT-X705F-QKQ1.zip)
> 
> 
> 
> Sorry for the delay in getting this to you.  I had to find an Android tablet that wouldn't require me to go into "ADB Mode".  I ran this bug report along side a Peloton walking class.  The QZ app reports back the speed, inclination, etc. but will just let the speed and incline be controlled by the Peloton instructions provided in the class.  Hoping there is a simple setting that will allow my Proform Carbon TL treadmill to be used with Peloton classes with speed and incline controlled by the class.  

exactly as you did here but only with ifit, no qz at all

**Comment by cagnulein** [comment]
[BT_HCI_2024_0919_112754.cfa.zip](https://github.com/user-attachments/files/17062412/BT_HCI_2024_0919_112754.cfa.zip)

**Comment by cagnulein** [comment]
@bkeown64 got it, it has different init packet indeed!
so it's a different firmware version from the #2149 @ConorIA @davcho80 are you still using QZ? which firmware version has yours?

**Comment by bkeown64** [comment]
If I understood correctly, the version of QZ on that particular tablet I obtained the bug report is version 2.16.69.  
I am also using the Beta version for iOS - Version 2.15.4

**Comment by cagnulein** [comment]
@bkeown64 I was talking about firmware version of the treadmill, not of the app. I guess you can check this from the treadmill  directly

**Comment by bkeown64** [comment]
The software version on the treadmill is v83.122, the model number is PFTL59720.0, and the Serial number is NN240C00016106Sent from my iPhoneOn Sep 19, 2024, at 1:10 PM, Roberto Viola ***@***.***> wrote:﻿
@bkeown64 I was talking about firmware version of the treadmill, not of the app. I guess you can check this from the treadmill  directly

**Comment by cagnulein** [comment]
Perfect thanks, I will add this as a new name for your profile

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 19 set 2024 alle 20:34 bkeown64 ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
Thank you for your time (and patience!)

**Comment by bkeown64** [comment]
Good morning, Roberto.  Just thought about this.  Not sure if you are modifying the code for my Carbon TL Treadmill for Android, iOS or both.  If you have not started yet, my preference would iOS as all my machines are using iPad (lol..I have an iPad on each machine - how is that for lazy?).  However, if you have started on Android, that will be fine to start with. I can make do until you modify the iOS version of the app.

**Comment by cagnulein** [comment]
@bkeown64 just sent the ios version. (anyway the source code is the same so also the android one is already ready :) )
select the new carbon tl PFTL59720.0 device in the proform settings in qz and restart qz
then try without peloton to change speed and incline from the speed and inclination tile. Let me know if it's ok

**Comment by bkeown64** [comment]
Thanks for the quick reply. i uninstalled the old app and installed the app currently showing in Test Flight.   The current build showing in my test flight app is 2.16 (870) but does not have the profile PFTL59720.0 available in the Proform drop down selections.  Do I have the correct build?Sent from my iPhoneOn Sep 20, 2024, at 8:01 AM, Roberto Viola ***@***.***> wrote:﻿
@bkeown64 just sent the ios version. (anyway the source code is the same so also the android one is already ready :) )
select the new carbon tl PFTL59720.0 device in the proform settings in qz and restart qz
then try without peloton to change speed and incline from the speed and inclination tile. Let me know if it's ok

**Comment by cagnulein** [comment]
nope it's the 873 and you haven't to uninstall it. did you receive an email from apple 1 hour ago?

**Comment by bkeown64** [comment]
No email yet

**Comment by bkeown64** [comment]
Just received!  I have a meeting now but will give it a shot right afterwards.  Thank you!

**Comment by bkeown64** [comment]
Received it and it updated my version.  However I believe there may be some corruption.  When trying to access settings it will not allow me to access to change the treadmill.  After pushing settings menu it just returns back to the tiles.  When starting treadmill it does read speed and elevation though.  I also uninstalled and reinstalled but the same issue occurs - cannot access the settings menuSent from my iPhoneOn Sep 20, 2024, at 8:53 AM, Bob Keown ***@***.***> wrote:﻿No email yetOn Sep 20, 2024, at 8:51 AM, Roberto Viola ***@***.***> wrote:nope it's the 873 and you haven't to uninstall it. did you receive an email from apple 1 hour ago?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by cagnulein** [comment]
my fault, i'm building a new one. sorry for the issue!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle ore 15:35 bkeown64 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
sent the new one!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle ore 15:37 cagnulein ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
Congratulations!  It control the speed and elevation via the tiles in the app.  I did try it with a Peloton class afterwards and noticed it locked the speed at zero with no way to manually control the speed.  But looks like you are getting close!!Sent from my iPhoneOn Sep 20, 2024, at 9:59 AM, Roberto Viola ***@***.***> wrote:﻿
sent the new one!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 20 set 2024 alle ore 15:37 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Amazing! Did you enable the speed force in the treadmill settings?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 18:27 bkeown64 ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
OMG!!!!  You did it!!!! You did it!!!! You did it!!!! Fantastic!! It’s working with speed and elevation changing.  This is beautiful. Great work!Sent from my iPhoneOn Sep 20, 2024, at 12:42 PM, Roberto Viola ***@***.***> wrote:﻿
Amazing! Did you enable the speed force in the treadmill settings?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 20 set 2024 alle 18:27 bkeown64 ***@***.***> ha

scritto:

**Comment by bkeown64** [comment]
Hello Roberto,  I have been using this on my iPads and it has been working fantastically.  The instructions for use are basically the same as on the Treadmill instructions on the wiki.  As an FYI - the treadmill must be started and running first or the speed controls get locked out, just like on the Horizon treadmill in the wiki article.  Yesterday, I tested it out using QZ app running on top of the Peloton class on the same iPad and it worked perfectly.  Could you update the Android version of your app to include Proform Carbon TL PFTL59720?  My issue with my iPads are that I have old  6th generation iPads with 32GB of memory and am constantly having to unload apps on it to keeps Zwift, Kinomap, Peloton, Echelon, etc. running.  Would love to give this a try on my Android Lenovo P12 with larger screen (and 128GB of memory).  Thank you for all your great work!

**Comment by cagnulein** [comment]
hi @bkeown64 glad to hear it! it's already available https://github.com/cagnulein/qdomyos-zwift/actions/runs/11008547380/artifacts/1970086897

Let me know! Remember to set the email that I unlock you in the email setting

**Comment by vasudevan-s** [comment]
Hello @cagnulein,
Good evening.
I'm planning to get the Proform Carbon TL during Thanksgiving.
I've a Apple TV 4K and also have a iPhone X (iOS 16.5) and a Samsung Z Flip 5 (Android 14). I'm planning to run Zwift/Kinomap/Peloton app on Apple TV. Wanted to control speed and incline automatically when those apps run. Since I'm new to all this, where should I begin?
Please advise.

**Comment by cagnulein** [comment]
@vasudevan-s Simply downloading the qz app. You should get the metrics automatically. If so open zwift on apple TV and you are good to go!

Select your bike under the nordictrack bike settings in qz

Let me know

**Comment by vasudevan-s** [comment]
Thank you for the reply.
Is there a step by step guide on how to do this?
Do you have to custom make a iPhone app or android app based on the logs from the one I'm buying?
I should download qz app on my z flip 5 or on my iPhone X as a first step?

Appreciate your help.
________________________________

**Comment by cagnulein** [comment]
My previous comment was a step by step guide :) it's just this :)  

You need to download qz on the device that you would like to use it, for example qz on a android and zwift on iPhone

I shouldn't need a custom build since I already did the work for the OP

Let me know if you have any other questions!

**Comment by bkeown64** [comment]
This may help.

**Comment by vasudevan-s** [comment]
@cagnulein Thank you so much. Can I do this:
QZ app on iPhone X or Z Flip 5 and have the Zwift/Peloton app on Apple TV 4K? I would like to use the phone for the QZ app and drive the run using Zwift/Peloton app on Apple TV. Btw, does this app also support using AppleTV fitness app?
Please advise.

**Comment by cagnulein** [comment]
Yes you can do this! Qz can't run on apple TV, but zwift does and qz can
talk from your phone to it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 17 nov 2024 alle 15:44 Vasudevan ***@***.***>
ha scritto:

**Comment by vasudevan-s** [comment]
Awesome. One more question. Where can I download the QZ app? directly from Apple AppStore or from Google Playstore? Between Proform Carbon XL and NordicTrack 5S or 6.5S, which one gives me the best experience in terms of automatic speed and incline control using Zwift/Peloton app thru QZ app?
