### ISSUE TITLE
[REQ] Power profile Domyos bike 500

### ISSUE THREAD

**Issue by Gilbocc** [cagnulein/qdomyos-zwift#2573]
Hello,

thanks for your great work. The app is working perfectly with the Domyos bike 500.

The only thing I find quite annoying concerns the watt profile available in the settings. I find the values it produces for resistance levels from 8 to 15 much more realistic. However, since the power is calculated with the standard formula for the lowers levels, it is quite unusable in simulation mode in zwift due to the range mismatch.

Would it be possible to complete the profile? Estimating the values from the ones available would be enough to have a smoother power curve. For example, we could have:

resistance 1 : torque 5,0
resistance 2 : torque 5,7
resistance 3 : torque 6,5
resistance 4 : torque 7,5
resistance 5 : torque 8,6
resistance 6 : torque 9,9
resistance 7 : torque 11,4

I obtained them applying a simple regression on the original experimental data (this is the resulting function used to sample the above values: y=4.31163*e^(0.138619*x)).

![image](https://github.com/user-attachments/assets/0f140ea5-ee69-488a-91dc-959b3f288e67)

The chart on the right shows the new power curves using different values for the cadence. The chart on the left shows the power curves produced by the actual watt profile.

**Comment by cagnulein** [comment]
Hi @Gilbocc did you already try also this?

![image](https://github.com/user-attachments/assets/14304167-da0e-4ea3-ab74-526fc5ea93be)

**Comment by Gilbocc** [comment]
@cagnulein Yes, I was referring to the values the app produces when that setting is turned on. 
The values produced by disabling it seem to be too high.

**Comment by cagnulein** [comment]
ok i can add a new power profile. are you on ios or android?

**Comment by Gilbocc** [comment]
thank you!! I'm on android

**Comment by cagnulein** [comment]
almost did, could you please conveert your math formula in this format

`return ((10.39 + 1.45 * (resistance - 1.0)) * (exp(0.028 * (currentCadence().value()))));`

thanks

**Comment by Gilbocc** [comment]
Something like this would do I think:

```c++
return (4.31163 * exp(0.138619 * resistance)) * currentCadence().value() / 9.5488;
```

but it would also approximate the original values used in the wattage profile.

Alternatively you could just add the missing conditions to the switch, i.e.:

```c++
else {
        switch ((int)resistance) {
        case 1:
            return (5.0 * Cadence.value()) / 9.5488;
        case 2:
            return (5.7 * Cadence.value()) / 9.5488;
        case 3:
            return (6.5 * Cadence.value()) / 9.5488;
        case 4:
            return (7.5 * Cadence.value()) / 9.5488;
        case 5:
            return (8.6 * Cadence.value()) / 9.5488;
        case 6:
            return (9.9 * Cadence.value()) / 9.5488;
        case 7:
            return (11.4 * Cadence.value()) / 9.5488;
        case 8:
            return (13.6 * Cadence.value()) / 9.5488;
        case 9:
            return (15.3 * Cadence.value()) / 9.5488;
        case 10:
            return (17.3 * Cadence.value()) / 9.5488;
        case 11:
            return (19.8 * Cadence.value()) / 9.5488;
        case 12:
            return (22.5 * Cadence.value()) / 9.5488;
        case 13:
            return (25.6 * Cadence.value()) / 9.5488;
        case 14:
            return (28.4 * Cadence.value()) / 9.5488;
        case 15:
            return (35.9 * Cadence.value()) / 9.5488;
        }
        return 0;
    }
```

**Comment by cagnulein** [comment]
done 

https://github.com/cagnulein/qdomyos-zwift/actions/runs/10736435916

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Gilbocc** [comment]
Thank you! I'll try it this afternoon and let you know.

**Comment by Gilbocc** [comment]
Everything is working perfectly. Thank you!

**Comment by cagnulein** [comment]
amazing!

**Comment by cagnulein** [comment]
hi @danielctin14 yes you can use the same profile of @Gilbocc ! are you on ios or android?

**Comment by danielctin14** [comment]
Thanks @cagnulein, I am on Android

**Comment by danielctin14** [comment]
When do you think the update will be live on Google Store as well?

Since all my data is screwed I might just finish the last month of my training plan with these insane wattage number and then activate the 500 profile :(

**Comment by danielctin14** [comment]
I wasn't, applied now. **Thank you**, will do some tests when the App updates, it's currently on version 2.16.66

**Comment by danielctin14** [comment]
Hello @cagnulein, 2.16.69 downloaded on my phone and there have been some major changes.

First the display of the bike doesn't show all its stats like before (KM, cadence, time etc.) it only shows the Bluetooth icon once connected to the app.

Secondly, it appears the Domyos 500 profile is now working, at least there are differences from before, cannot tell if all gears 1-15 have been redone as I didn't test it before the update.
But the profile is **always active**. Tested in Gear 1 and 9 with 85rpm and the wattage is the same with the profile on as well as off.

**Comment by cagnulein** [comment]
> First the display of the bike doesn't show all its stats like before (KM, cadence, time etc.) it only shows the Bluetooth icon once connected to the app.

i didn't change anything on the domyos side. maybe you need to powercycle the bike?



> Secondly, it appears the Domyos 500 profile is now working, at least there are differences from before, cannot tell if all gears 1-15 have been redone as I didn't test it before the update.

did you set the profile in the settings?



> But the profile is **always active**. Tested in Gear 1 and 9 with 85rpm and the wattage is the same with the profile on as well as off.

yes it's what @Gilbocc asked me to do

**Comment by danielctin14** [comment]
> > But the profile is **always active**. Tested in Gear 1 and 9 with 85rpm and the wattage is the same with the profile on as well as off.
> 
> yes it's what @Gilbocc asked me to do

What I mean is that regardless of the Setting the wattage profile is on. I cannot go back to how it was before, changing it to off doesn't do anything for me.

Don't know if that will be the case for other bikes as well

**Comment by cagnulein** [comment]
did you disable the "Bike 500 wattage profile v2" setting? show me a debug log of your current setup and i will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
