### ISSUE TITLE
[BUG]Wahoo Kickr not changing resistance when QZ acting as bridge for MYWHOOSH

### ISSUE THREAD

**Issue by mgarcea** [cagnulein/qdomyos-zwift#2574]
**Describe the bug**
Wahoo Kickr not changing resistance when QZ acting as bridge for MYWHOOSH.  Garmin Power Pedals connected and working, Shows QZ as power and that is working, as cadence and that is working. QZ is shown as being connected as Controllable, but resistance doesn't change.

**To Reproduce**
At 16:49 I started a ride with some gradient changes. 

**Expected behavior**
Kickr should change resistance according to gradient.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Pixel 7

**Append a debug log**
[debug-Thu_Sep_5_16_42_16_2024.log](https://github.com/user-attachments/files/16901055/debug-Thu_Sep_5_16_42_16_2024.log)

  
**Additional context**

**Comment by cagnulein** [comment]
that's strange: i can see correctly the inclination changing to the wahoo kickr from 0% to 2% don't you feel it? Did you try also to use the gears from qz to increase the virtual ratio to it?

**Comment by mgarcea** [comment]
No, I can't feel it, but I can manually change the resistance by changing the resistance tile.  I will test some more today.

**Comment by cagnulein** [comment]
ok let me know, in case I will check again the log. we can try to use the FTMS profile instead of the wahoo ones in case.

**Comment by mgarcea** [comment]
Ok, so when I choose the Wahoo Kickr bluetooth in the FTMS profile in the "Bike Options" setting, the resistance tile changes values and I can feel the resistance change as I am pedaling.  If I don't choose that in the "Bike Options" the resistance tile doesn't change and there is no change in the feel of the gradient.

**Comment by cagnulein** [comment]
ok this makes sense, probably your bike answers only to the standard ftms
commands, good to know! thanks for the feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 8 set 2024 alle 04:44 mgarcea ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i added a popup to remind the user about this , thanks
