### ISSUE TITLE
[BUG] Can't connect QZ to Zwift

### ISSUE THREAD

**Issue by johnatas-henrique** [cagnulein/qdomyos-zwift#2579]
**Describe the bug**
My trainer and the HR armband are connected to the QZ app in Android and works within the app, but when I opened Zwift, nothing showed to me to connect the trainer and the armband.

**To Reproduce**
1. Powered on everything
2. Opened QZ on my android phone
3. Tested that everything was working on the QZ app
4. Opened Zwift on PC
5. The sensors didn't show in connections page on Zwift

**Expected behavior**
I expected the sensors to show on Zwift to pair.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Samsung S21 FE
 - OS: Android 14 / One UI 6.1

**Append a debug log**
[debug-Fri_Sep_6_16_23_22_2024.log](https://github.com/user-attachments/files/16912309/debug-Fri_Sep_6_16_23_22_2024.log)

**Comment by cagnulein** [comment]
Thanks, it's an issue with the cadence I'm trying to fix it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 21:41 Johnatas Henrique <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done @johnatas-henrique 
https://github.com/cagnulein/qdomyos-zwift/actions/runs/10744352261

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by johnatas-henrique** [comment]
Unfotunately, didn`t wok at all.

The game doesn`t show qz fo me to connect, but trainer works on qz app, this powertap pedal I use for secondary powemeter and isn`t connected to qz
![image](https://github.com/user-attachments/assets/90ea7c28-5269-429b-ad20-d8e1b9ef0860)

![image](https://github.com/user-attachments/assets/a989ad03-a33d-45bc-83c3-d52c15d028b6)

**Comment by cagnulein** [comment]
ok so the fix worked because now you can see the metrics in qz!
now let's check the experimental settings: did you change something there? virtual device, virtual bluetooth and dircon must be enabled

**Comment by johnatas-henrique** [comment]
Enable virtual device / Virtual device bluetooth / Wahoo direct connect are all enabled, and they were enabled when I started the app in the first time, I didn't need to change these configs.

Do you want a new log?

![image](https://github.com/user-attachments/assets/1099acc5-d04b-4d2c-bf07-951baa956cdf)
![image](https://github.com/user-attachments/assets/3f8b4a86-4e43-4ef6-853a-221b06e42864)

**Comment by cagnulein** [comment]
A fresh log will be useful, yes.
Anyway try to enable also the android notification icon setting in the experimental settings and restart qz and try to run then zwift on the same android, if it works it means that we have to check the zwift device that you are using. by the way where does zwift run now?

**Comment by johnatas-henrique** [comment]
> A fresh log will be useful, yes.
> Anyway try to enable also the android notification icon setting in the experimental settings and restart qz and try to run then zwift on the same android, if it works it means that we have to check the zwift device that you are using. by the way where does zwift run now?

Will try to enable this and test in 2h, when I will be back on my house.
I run Zwift on my PC, same wifi as the android phone.
Which config I need to make to use Qz and Zwift on same android phone?

**Comment by johnatas-henrique** [comment]
Tested in same android phone and it worked, although a bit laggy to change power and cadence, and sometimes putting cadence at 0. So the problem is with my PC, right?
Could it be helped if I use QZ for Windows?

**Comment by cagnulein** [comment]
Only enable the android notification icon setting in the experimental
settings plus the other ones that you have already

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 7 set 2024 alle 17:18 Johnatas Henrique <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Yes you can try qz on the same pc. You can download the nightly build from
the release page here on github.
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 7 set 2024 alle 19:26 Johnatas Henrique <
***@***.***> ha scritto:

**Comment by johnatas-henrique** [comment]
Hi, was travelling and got back to my house today.
Tried to use the qz nightly, but qz app didn't saw any bt items.
When I open Zwift on this PC all items are encountered.
Aside disabling the firewall, what I need to do fo qz see the trainer and armband?

![image](https://github.com/user-attachments/assets/c3a6c9dc-2c2e-4539-b90f-92aa21d83594)

**Comment by johnatas-henrique** [comment]
After, I installed the qz app on my Samsung Watch 5 Pro and tried to connect the HR to QZ desktop app, but QZ didn't found the watch too.

**Comment by cagnulein** [comment]
Watch works only with the android version (installed from the play store)

For the windows version you need to use the msvc build, did you?

**Comment by johnatas-henrique** [comment]
Used [windows-binary.zip](https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-binary.zip) version, will try to use [windows-msvc2019-binary.zip](https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary.zip) and get back to say if it has worked.

Thanks!

**Comment by cagnulein** [comment]
Glad it worked!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 15 set 2024 alle ore 15:27 Johnatas Henrique <
***@***.***> ha scritto:

**Comment by johnatas-henrique** [comment]
The msvc version shows my equipments, but started to force close after 1 or 2 minutes.
[debug-dom_set_15_10_47_21_2024.log](https://github.com/user-attachments/files/17005962/debug-dom_set_15_10_47_21_2024.log)

**Comment by cagnulein** [comment]
is it your first time you use the windows msvc version?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 15 set 2024 alle ore 15:50 Johnatas Henrique <
***@***.***> ha scritto:

**Comment by johnatas-henrique** [comment]
Yeah, I tried to use the wrong version before

**Comment by cagnulein** [comment]
@johnatas-henrique i guess I saw something similar here https://github.com/cagnulein/qdomyos-zwift/actions/runs/10871613685

wait for the build and download the msvc from there at the bottom and share a debug log if the crash persists.

are you on windows 11?

**Comment by cagnulein** [comment]
@johnatas-henrique Any news?
