### ISSUE TITLE
Sportstech ESX500

### ISSUE THREAD

**Issue by Umibio** [cagnulein/qdomyos-zwift#2581]
I own a Sportstech esx500 and i finally can connect to Zwift. Fantastic! Unfortunately i cant get a proper calibration. Watt power is totally disconnected with cadence and resistance and i cant really enjoy the ride in Zwift. I am pretty sure there is a way to adjust. 
Can you or anyone help?

[debug-sab_set_7_09_31_06_2024.log](https://github.com/user-attachments/files/16918827/debug-sab_set_7_09_31_06_2024.log)

**Comment by cagnulein** [comment]
@Umibio in order to help you i need a debug log where you are connected with the bike showing the issue

Let me know

**Comment by cagnulein** [comment]
@Umibio any news?
