### ISSUE TITLE
Xterra 4500 Incline Issue

### ISSUE THREAD

**Issue by twarty** [cagnulein/qdomyos-zwift#2582]
[debug-Sun_Sep_8_07_36_39_2024.log](https://github.com/user-attachments/files/16922318/debug-Sun_Sep_8_07_36_39_2024.log)

**Comment by cagnulein** [comment]
with kinomap inclination works, so i need to use the trxappgateusb profile

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/issues/696

**Comment by cagnulein** [comment]
@twarty patch done, let's see if it works
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
