### ISSUE TITLE
Adding “Next Rows” metric on QZ AI app

### ISSUE THREAD

**Issue by lalgaze** [cagnulein/qdomyos-zwift#2584]
Adding “Next Rows” metric on QZ AI app before other timed metrics (time to next, peloton remaining, etc)

**Comment by lalgaze** [comment]
![IMG_3354](https://github.com/user-attachments/assets/faecff98-0c1f-4b68-82f8-43a3d95c11a4)

**Comment by cagnulein** [comment]
thanks

![image](https://github.com/user-attachments/assets/b57ae1e1-d074-480d-9214-574f08ee37c4)

**Comment by lalgaze** [comment]
Can we also have the Power target metric color coincide with the power zone target metric color?
![IMG_3357](https://github.com/user-attachments/assets/3f9a8b2d-b35e-40c4-b0bd-3898a4f66434)

**Comment by cagnulein** [comment]
I guess we already discussed about this and the actual behavior it's the same of the qz main app

**Comment by lalgaze** [comment]
And it’s not possible to change it on the main app so that the two target values behave the same? I’m not a programmer so I have no idea how much that entails.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
i can do this but i have also to put it customizable because every change
on the main UI must be voted from the community and the actual behaviour
was already approved. So I wouldn't create thousands of settings for each
aspect if possible :)
But it's certainly possible to add. I will consider it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle ore 14:52 lalgaze ***@***.***>
ha scritto:

**Comment by lalgaze** [comment]
I thought that in the poll it was understood it would be both since the wording asked for both the power and power zone.

**Comment by cagnulein** [comment]
Ok, thanks for the clarification.
I'm very busy lately so I'm trying to do my best with all the tasks here. I
will let you know

Il giorno mar 17 set 2024 alle 04:22 lalgaze ***@***.***> ha
scritto:

**Comment by lalgaze** [comment]
Just posting so it doesn’t go stale

**Comment by lalgaze** [comment]
iOS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
Perfect I will send you the new beta tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 19:36 lalgaze ***@***.***> ha
scritto:

**Comment by lalgaze** [comment]
Great. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle ore 22:14 lalgaze ***@***.***>
ha scritto:

**Comment by lalgaze** [comment]
Got it. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lalgaze** [comment]
Works perfectly! Thanks!! Just want to keep on your radar the making color of target power wattage to be same as target power zone color.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lalgaze** [comment]
Hi Roberto. Not sure if  you saw my other email about the power target wattage and the power zone target colors?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
yes but i already say that i will need to create a new setting for this and
its another topic :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 16:18 lalgaze ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Yes, please!


Il giorno gio 10 ott 2024 alle 16:43 lalgaze ***@***.***> ha
scritto:

**Comment by lalgaze** [comment]
Done. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
