### ISSUE TITLE
[BUG] Echelon Bike Connecting and Disconnecting

### ISSUE THREAD

**Issue by D43G** [cagnulein/qdomyos-zwift#2586]
**Describe the bug** 
Echelon EX-1 keeps connecting and disconnecting from the app. On the QZ (or echelon app) the bike will appear and the blue Bluetooth will appear, then it beeps and the button goes gray. This keeps repeating as long as the app stays open.

**To Reproduce**
1. I plug Echelon EX-1 into the wall to turn on
2. I open the Echelon app or the QZ app
3. The bike is found and connects
4. The bike disconnects
5. A beeping occurs as it connects and disconnects
6. 3-5 repeat until I shut the apps off
7. beeping stops

**Expected behavior**
I expect the bike to connect to the app and stay connected

**Screenshots**
Screen record of the app is attached

https://github.com/user-attachments/assets/bcbfd8e4-c9bb-4804-b2e7-4ad875943ecc

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS17.6.1
 - Version 21G93

**Append a debug log**
Attached
  
[Echelon Bug Issue QZ.docx](https://github.com/user-attachments/files/16949780/Echelon.Bug.Issue.QZ.docx)
  
**Additional context**
This is a used bike I bought recently. It is in good condition.

**Comment by D43G** [comment]
Hi thank you so much for your help and quick reply! Here is the original format. [debug-Tue_Sep_10_14_56_34_2024.log](https://github.com/user-attachments/files/16949824/debug-Tue_Sep_10_14_56_34_2024.log)

It does the same thing with the echelon app. It just connects and disconnects with the beeping till I close the app. I was reading on reddit someone was having a similar issue with their EX3 and you commented to file a bug report. That it may be a Wi-Fi problem interfering with the Bluetooth?

**Comment by cagnulein** [comment]
Unfortunately it seems a hardware issue on the Bluetooth controller. You
need to call echelon for a replacement. Did you do already?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 set 2024 alle 21:20 D43G ***@***.***> ha
scritto:

**Comment by D43G** [comment]
So its definetly not a wifi problem? I was chatting with Echelon but they really weren't helpful with troubleshooting. I can try reaching back with this specific information now though.

**Comment by cagnulein** [comment]
Nope absolutely. It's just the Bluetooth controller of the bike that it's
broken. It's a common hardware issue on the echelon bikes unfortunately

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 set 2024 alle 21:25 D43G ***@***.***> ha
scritto:

**Comment by D43G** [comment]
Thank you for your help! Do you know if its easy to replace?

**Comment by cagnulein** [comment]
Yes you can ask instructions on the qz Facebook group! Let me know if you
have any other questions!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 10 set 2024 alle 21:32 D43G ***@***.***> ha
scritto:
