### ISSUE TITLE
Qdomyos Displaying all Zeros on first connect regularly. Gears tile not working. Zwift session still working and Zwift controlling auto resistance

### ISSUE THREAD

**Issue by Qdomyos1978** [cagnulein/qdomyos-zwift#2588]
When I open Qdomyos every tile is set to Zero even if pedalling.
Eventually I can get it to work by closing the app several times until it works.

**To Reproduce**
1. Open Qdomyos as normal.
2. I do nothing. But everything is set to Zero even if pedalling.

**Expected behavior**
I expected it to work like it used to, for example I open the app, it connects and then, the tiles have values instead of zeros for instance. I don't have to open it multiple times to get it to work, only once.

**Screenshots**
![QdomyosEverythingIsZero](https://github.com/user-attachments/assets/e659aca4-6168-49e6-8e5c-aa273b714176)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A71
 - OS: Android / One UI
 - Version: 15 / 5.1

**Append a debug log**

  
  
**Additional context**
[debug-Wed_Sep_11_15_19_03_2024.log](https://github.com/user-attachments/files/16965584/debug-Wed_Sep_11_15_19_03_2024.log)

**Comment by cagnulein** [comment]
hi @Qdomyos1978 i can't download the log file, could you please upload it again?

**Comment by Qdomyos1978** [comment]
[debug-Wed_Sep_11_15_19_03_2024.log](https://github.com/user-attachments/files/16965793/debug-Wed_Sep_11_15_19_03_2024.log)

**Comment by Qdomyos1978** [comment]
There was apparently two files created (or possibly modified) today, but the other file is too big to attach.
And I can't attach a zip here either.
But if you want that file or the other files, I would be glad to email them to you perhaps?

![image](https://github.com/user-attachments/assets/c8daba69-1928-4afe-9984-382ac42e1cb8)

**Comment by cagnulein** [comment]
i need the big one,  the small one doesn't have nothing useful. just zip and upload it here. if you can't send me to roberto.viola83 at gmail.com mentioning this

**Comment by Qdomyos1978** [comment]
Github doesn't accept zip files so I will email.

**Comment by cagnulein** [comment]
be sure are zip and not 7z, that's the issue of gitub

**Comment by cagnulein** [comment]
easy fix: set your bike to the manual device into the advanced settings and press ok and restart qz
let me know!

**Comment by cagnulein** [comment]
@Qdomyos1978 all good?

**Comment by Qdomyos1978** [comment]
Apologies I've been away and have a bit of a running focus at present so I haven't tried it yet.
I will. But feel free to close the ticket anyway.
Thanks for looking into it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by cagnulein** [comment]
No problem, feel free to reopen it again if you need help

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 5 ott 2024 alle 11:04 Qdomyos1978 ***@***.***>
ha scritto:
