### ISSUE TITLE
Tim Wartenberg Zwift Debug 

### ISSUE THREAD

**Issue by twarty** [cagnulein/qdomyos-zwift#2589]
[debug-Sun_Sep_8_07_36_39_2024.log](https://github.com/user-attachments/files/16966908/debug-Sun_Sep_8_07_36_39_2024.log)

Xterra 4500 Pauses by itself

I am using an Apple iPhone

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi i need the log with the problem on it
in the meantime i'm sending an update version just to check if it's already
solved somehow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 18:53 twarty ***@***.***> ha
scritto:

**Comment by twarty** [comment]
Did the log I put on Githud not have the attachment? I will recreate the issue again and put that log on Githud.
    Get Outlook for iOS
  

 From: Roberto Viola ***@***.***>Sent: Wednesday, September 11, 2024 12:07 PMTo: cagnulein/qdomyos-zwift ***@***.***>Cc: twarty ***@***.***>; Author ***@***.***>Subject: Re: [cagnulein/qdomyos-zwift] Tim Wartenberg Zwift Debug (Issue #2589) 
hi i need the log with the problem on it

in the meantime i'm sending an update version just to check if it's already

solved somehow



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 11 set 2024 alle 18:53 twarty ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
it has the attachment but the log must be of a session with the issue on it

**Comment by twarty** [comment]
The updated log is on Githud.
