### ISSUE TITLE
Pro Form Smart power 10,

### ISSUE THREAD

**Issue by Meerkat1971** [cagnulein/qdomyos-zwift#2590]
**Describe the bug**
Pro Form Smart power 10, configured everything as per instructions, everything appears to connect, the metrics connect, even in Zwift it shows as connected, however no metrics/data are being transmitted from the bike

**To Reproduce**

**Expected behavior**

**Screenshots**
![PXL_20240911_144946051 RAW-01 COVER](https://github.com/user-attachments/assets/daa28cd4-d41d-42aa-98bd-ad7177337e70)
![PXL_20240911_145111656 RAW-01 COVER](https://github.com/user-attachments/assets/9a9fd8d7-a6b0-499b-bbcc-ab6eccefa295)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Append a debug log**

[debug-Wed_Sep_11_18_20_03_2024.log](https://github.com/user-attachments/files/16967446/debug-Wed_Sep_11_18_20_03_2024.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
log checked. the communication with the bike is working but the companion
can't get the metrics .

try to set the proform carbon t14 in the devices on the companion and
restart the bike

you didn't upgrade your bike to the latest ifit update right? qz doesn't
work yet with it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 19:34 Meerkat1971 ***@***.***>
ha scritto:

**Comment by Meerkat1971** [comment]
Hi, it may be set to auto update, 
App Version is 2.6.89.4850

**Comment by Meerkat1971** [comment]
[debug-Wed_Sep_11_19_24_32_2024.log](https://github.com/user-attachments/files/16968376/debug-Wed_Sep_11_19_24_32_2024.log)

**Comment by cagnulein** [comment]
i don't know about the version number. the important this is that it must
be not the newer version. you can try to restore the factory reset and
don't update the ifit app then

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 20:13 Meerkat1971 ***@***.***>
ha scritto:

**Comment by Meerkat1971** [comment]
Tested with the carbon, above debug

**Comment by Meerkat1971** [comment]
No, it didn't work

**Comment by Meerkat1971** [comment]
Also when you do a factory reset, you have no way of stopping it doing the latest update, its automatic as part of the reset build

**Comment by cagnulein** [comment]
the previous log worked but the metrics were frozen

you can disable the update without adding the gateway in the internet
settings or disabling internet access to the bike

otherwise, if you install the companion via adb, we can check if we can
have metrics from adb

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 20:48 Meerkat1971 ***@***.***>
ha scritto:

**Comment by Meerkat1971** [comment]
i've now installed via ADB and no difference, I'm assuming I don't need to go through the wizard and choose a connection?

**Comment by cagnulein** [comment]
im going to bed soon: via adb run a adb logcat and check while you are
riding if you can see the metrics in the log
if so i can get them
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 21:23 Meerkat1971 ***@***.***>
ha scritto:

**Comment by Meerkat1971** [comment]
[logcat.txt](https://github.com/user-attachments/files/16969913/logcat.txt)

**Comment by cagnulein** [comment]
I don't see any metrics unfortunately so I guess it's the new beta.
If you want I have an almost ready solution here  if you want to test to
have it work. But I need you to test and report the result several times to
optimize it
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/105


Let me know if it's OK for you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 22:07 Meerkat1971 ***@***.***>
ha scritto:

**Comment by Meerkat1971** [comment]
Hi, happy to give it a go and help you optimise it.

⁣Get BlueMail for Android ​

**Comment by cagnulein** [comment]
perfect! you can use this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10592813760/artifacts/1863668226

and this will use OCR to get the info from the screen. In order to check the result i would need a debug log frm qz  after installing the new companion (it should ask the permission to record the screen on the tablet's bike). also it would be nice a photo of the manual view of the ifit app to check where the metrics are shown there (OCR needs to map the view to get the info)

let me know

**Comment by Meerkat1971** [comment]
Hi, I have installed the apk, it asked permission to record screen which I granted, what now?

Included manual screen inc warm-up 


⁣Get BlueMail for Android ​

**Comment by cagnulein** [comment]
Hi, i don't see the picure: you have to add it to github directly otherwise I can't see it.
For the apk, ok perfect, send me a debug log from qz now so i will check what the companion is sending. or you can also collect a adb logcat if it's simpler for you
Let me know

**Comment by Meerkat1971** [comment]
[debug-Thu_Sep_12_18_32_56_2024.log](https://github.com/user-attachments/files/16983418/debug-Thu_Sep_12_18_32_56_2024.log)
![WIN_20240912_18_38_11_Pro](https://github.com/user-attachments/assets/ec47239d-ca87-4058-aa4a-8d8f2b59e24d)
Debug is without iFit running, when I tried to log in to iFit I get the image attached

**Comment by cagnulein** [comment]
thanks i will check it tomorrow, 8pm here :) have a nice evening

**Comment by Meerkat1971** [comment]
![WIN_20240913_14_40_39_Pro](https://github.com/user-attachments/assets/a30c43cf-691b-4135-9c82-0a081e8b86ac)
![WIN_20240913_14_40_56_Pro](https://github.com/user-attachments/assets/a26ec57e-1773-4c68-849a-0a8a4fcc56f4)

**Comment by cagnulein** [comment]
thanks @Meerkat1971 i did another build of the companion https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10850420813/artifacts/1930046199

let me know!

**Comment by Meerkat1971** [comment]
Hi there, uploaded the new build, gave all the permsissions it requested.
Restarted iFit, ran the apk, selected the bike Tour de France 10 (Assuming this is the correct model)
Ran the app on the tablet, connected as normal but not working., have attached the log, hope this helps, let me know if you want anything else tested.
[debug-Sun_Sep_15_20_30_11_2024.log](https://github.com/user-attachments/files/17007139/debug-Sun_Sep_15_20_30_11_2024.log)

**Comment by cagnulein** [comment]
Perfect I can see cadence and speed in the log. I will check it carefully tomorrow!
Have a nice evening!

**Comment by cagnulein** [comment]
hi @Meerkat1971 in the ifit UI you have to show also the wattage so you will see speed and wattage on qz as well! Let me know how it goes!

**Comment by Meerkat1971** [comment]
[debug-Mon_Sep_16_16_38_52_2024.log](https://github.com/user-attachments/files/17015888/debug-Mon_Sep_16_16_38_52_2024.log)
Changed to Watt on the iFit UI, still no output, Zwift shows green but no movement

**Comment by cagnulein** [comment]
fixed! new apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10887476182/artifacts/1938458708

**Comment by Meerkat1971** [comment]
Hi, tested with the new APK and now getting feedback, tested in Zwift and there is movement, however it doesn't match up with iFit, where iFit told me I'd done 0.4km Zwift said I has done half that 0.2km

**Comment by Meerkat1971** [comment]
Hi, that makes sense and I did think that was maybe the case so I increased resistance considerably and it didn't really have any effect on the Wattage, maybe I need to give it another go

**Comment by cagnulein** [comment]
ok let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 20:47 Meerkat1971 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Meerkat1971 did it work?

**Comment by mikeod73** [comment]
> @Meerkat1971 did it work?

yea, so far its working great !
