### ISSUE TITLE
Tim Wartenberg Zwift Debug #2589 Redo

### ISSUE THREAD

**Issue by twarty** [cagnulein/qdomyos-zwift#2591]
[debug-Wed_Sep_11_12_53_31_2024.log](https://github.com/user-attachments/files/16967898/debug-Wed_Sep_11_12_53_31_2024.log)

The issue occurred 6 minutes into the walk. The treadmill rebooted. When the treadmill screen came back up, the treadmill started going. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by twarty** [comment]
Great. No problem.

**Comment by cagnulein** [comment]
in the meantime you can try to disable the auto inclination since it doesn't work yet on your treadmill, i guess it could cause this

![image](https://github.com/user-attachments/assets/5d491ef4-70fe-4cb0-8800-9daee1dc0337)

**Comment by twarty** [comment]
Any luck with the inclination issue? I have not had a issue since I disable the auto inclination as you suggested. My wife used the Kinomap app with no problems. I have done several 5k workouts without issues. We did not use the QZ app during these workouts.Also, I purchased 2 more QZ apps for my wife’s and daughter’s iPhones. I didn’t want them looking for my phone when they are using the treadmill. From: Roberto Viola ***@***.***> Sent: Wednesday, September 11, 2024 2:42 PMTo: cagnulein/qdomyos-zwift ***@***.***>Cc: twarty ***@***.***>; Author ***@***.***>Subject: Re: [cagnulein/qdomyos-zwift] Tim Wartenberg Zwift Debug #2589 Redo (Issue #2591) in the meantime you can try to disable the auto inclination since it doesn't work yet on your treadmill, i guess it could cause thisUploadfrom.GitHub.for.iOS.png (view on web)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by cagnulein** [comment]
Ops i forgot this. I will check it tomorrow

**Comment by cagnulein** [comment]
@twarty just checked. the treadmill disconnects by itself from bluetooth. this sounds like a firmware issue. the difference between kinomap and qz, it is that QZ is using the profile for changing the inclination, instead kinomap the one to change the speed only. am I right? are you able to change both  inclination and speed from kinomap from the app itself? 

also did you try if the same issue it's happening with the other 2 phones?
Let me know

**Comment by twarty** [comment]
On the Kinomap app, we manually adjust speed and the inclination is auto. When you say 2 different phones, do you mean another different iPhone or a iPhone and a Android phone? Does QZ app work better on an Android phone? We only want to the Auto Inclination if possible. No auto speed. From: Roberto Viola ***@***.***> Sent: Monday, September 16, 2024 10:43 PMTo: cagnulein/qdomyos-zwift ***@***.***>Cc: twarty ***@***.***>; Mention ***@***.***>Subject: Re: [cagnulein/qdomyos-zwift] Tim Wartenberg Zwift Debug #2589 Redo (Issue ***@***.*** just checked. the treadmill disconnects by itself from bluetooth. this sounds like a firmware issue. the difference between kinomap and qz, it is that QZ is using the profile for changing the inclination, instead kinomap the one to change the speed only. am I right? are you able to change both inclination and speed from kinomap from the app itself?also did you try if the same issue it's happening with the other 2 phones?Let me know—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by cagnulein** [comment]
yeah sorry i was meaning the opposite, right. when i said 2 different phones, i mean did you try if you see the same issue with your wife's phone and your daughter's phone?

in case I can handle the same profile of kinomap to check if the problem is the profile that qz is using (not implemented correctly from the treadmill probably)

let me know

**Comment by twarty** [comment]
Sure will. It will be tomorrow when I get you answer.

**Comment by cagnulein** [comment]
Do you have an android phone? We can collect it with this guide https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

You just need the android phone for the time to get the log, then I can add also on ios

Let me know

**Comment by twarty** [comment]
Ok. I will ask around. If I can’t find someone with an android phone, I may have to look on EBay for a used one. Is there a specific Android phone I need to look for?
    Get Outlook for iOS
  

 From: Roberto Viola ***@***.***>Sent: Tuesday, September 17, 2024 8:37 PMTo: cagnulein/qdomyos-zwift ***@***.***>Cc: twarty ***@***.***>; Mention ***@***.***>Subject: Re: [cagnulein/qdomyos-zwift] Tim Wartenberg Zwift Debug #2589 Redo (Issue #2591) 
Do you have an android phone? We can collect it with this guide https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device
You just need the android phone for the time to get the log, then I can add also on ios
Let me know

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
Get Outlook for iOS

**Comment by cagnulein** [comment]
any android phone, even with an old one, works. don't buy an amazon phone
or tablet
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 14:50 twarty ***@***.***> ha
scritto:
