### ISSUE TITLE
[BUG] No cadence or resistance reading

### ISSUE THREAD

**Issue by Macsmudger** [cagnulein/qdomyos-zwift#2592]
No cadence or resistance readings from Echelon EX3 to QZ app on Samsung S9 ultra.

QZ version 2.16.69
Samsung S9 Ultra 
One UI 6.1 Android 14

cadence and power showing disabled in QZ accessories settings.

Bike is detected by QZ app and cadence and resistance tiles are displayed but all read zero.

I refreshed cadence and power settings and echelon bike is detected. I hit ok on both settings and restart app.  Same result.

Bike is definitely transmitting cadence and resistance settings over Bluetooth normally, as I can read these using other apps e.g. Echelon Fit and Bike Cadence.

QZ also works properly on the same bike when running the IOS version on an IPad so 
something strange on Android.

QZ also works (slowly !) on an old Fire tablet !

One other thing, despite uninstalling the QZ app and deleting the QZ folder  in the documents directory, then a tablet restart. A fresh Google Play download of QZ and install seems to retain a version of my configuration in settings. I could find a factory reset option. Don’t know if that helps.  

Debug log attached as requested…

cheers

John

**Comment by smudgermac** [comment]
[debug-Wed_Sep_11_20_36_09_2024.log](https://github.com/user-attachments/files/16969920/debug-Wed_Sep_11_20_36_09_2024.log)

**Comment by cagnulein** [comment]
You have ftms bike setting set to your echelon. Set it disabled and press
OK and you will be good
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 set 2024 alle 22:08 smudgermac ***@***.***>
ha scritto:

**Comment by smudgermac** [comment]
Ciao RobertThat fixed it !Thank you.JohnSent from my iPhoneOn 12 Sep 2024, at 05:57, Roberto Viola ***@***.***> wrote:﻿
You have ftms bike setting set to your echelon. Set it disabled and press

OK and you will be good

Let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 11 set 2024 alle 22:08 smudgermac ***@***.***>

ha scritto:

**Comment by cagnulein** [comment]
glad to hear it!
