### ISSUE TITLE
Galaxy watch 7 QZ companion not transmitting hr to main app

### ISSUE THREAD

**Issue by Wiseiguana** [cagnulein/qdomyos-zwift#2593]
Just installed the companion qz app on galaxy watch 7. It is failing to transmit the hr data to main app on galaxy s24 smartphone. My phone is paired to my watch and it is still not transmitting. The hr is showing correctly on the watch.

**Comment by Wiseiguana** [comment]
Problem solved after setting hr belt to disabled. Thanks

**Comment by cagnulein** [comment]
amazing!
Please remember to rate the app on the store! It means a lot to me!
Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 12 set 2024 alle 04:40 Wiseiguana ***@***.***>
ha scritto:
