### ISSUE TITLE
Can’t get QZ to connect

### ISSUE THREAD

**Issue by RobertQuinn4** [cagnulein/qdomyos-zwift#2595]
When I open the app it recognises equipment such as my Saris trainer and Apple TV but the app does not start, I can’t see the tiles and I can’t log on to Zwift with QZ. I expected to see the gear tiles I had set up and also to be able to log onto Zwift with QZ and use Zwift click for virtual gears.  I am using an iPhone 13  iOS version 17.6.1

[debug-Thu_Sep_12_22_14_05_2024.log](https://github.com/user-attachments/files/16985703/debug-Thu_Sep_12_22_14_05_2024.log)
![IMG_6926](https://github.com/user-attachments/assets/92605cb8-09dc-4952-8647-9442dea7df49)

**Comment by cagnulein** [comment]
in the manual device under the advanced settings you select apple tv. you
must set your hammer device there and press ok and restart qz

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 12 set 2024 alle 23:42 RobertQuinn4 ***@***.***>
ha scritto:

**Comment by RobertQuinn4** [comment]
Thanks Roberto,

That seems to have worked, all good to go! Do you start with the gear at zero and then go up or down from there.

Thanks again

Robert
Sent from my iPhone

On 13 Sep 2024, at 03:50, Roberto Viola ***@***.***> wrote:

﻿

in the manual device under the advanced settings you select apple tv. you
must set your hammer device there and press ok and restart qz

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 12 set 2024 alle 23:42 RobertQuinn4 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Yes! Great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 20:22 RobertQuinn4 ***@***.***>
ha scritto:

> Thanks Roberto,
>
> That seems to have worked, all good to go! Do you start with the gear at
> zero and then go up or down from there.
>
> Thanks again
>
> Robert
> Sent from my iPhone
>

**Comment by RobertQuinn4** [comment]
Hello again

Just to say I have the gear tile working with Zwift click but when I go in Zwift and complete a test ride and save the ride does not show up on activities in the Zwift comp app and it does not upload to strava? Do I need to adjust some setting. My Zwift rides are set to load automatically to strava.

Thanks


Sent from my iPhone

On 13 Sep 2024, at 19:23, Roberto Viola ***@***.***> wrote:

﻿

Yes! Great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 20:22 RobertQuinn4 ***@***.***>
ha scritto:

> Thanks Roberto,
>
> That seems to have worked, all good to go! Do you start with the gear at
> zero and then go up or down from there.
>
> Thanks again
>
> Robert
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
That's a zwift bug not qz releated. Qz did its job sending the metrics and
handling the gear right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 19:24 RobertQuinn4 ***@***.***>
ha scritto:

> Hello again
>
> Just to say I have the gear tile working with Zwift click but when I go in
> Zwift and complete a test ride and save the ride does not show up on
> activities in the Zwift comp app and it does not upload to strava? Do I
> need to adjust some setting. My Zwift rides are set to load automatically
> to strava.
>
> Thanks
>
>
> Sent from my iPhone
>

**Comment by RobertQuinn4** [comment]
My mistake, the test ride was under 2k so don’t register! All ok now. The only other feedback is about the sensitivity of the Zwift click, if you press it too hard it goes up 2 settings instead of 1. Maybe it is about getting used to it!

Thanks

Robert
Sent from my iPhone

On 18 Sep 2024, at 18:26, Roberto Viola ***@***.***> wrote:

﻿

That's a zwift bug not qz releated. Qz did its job sending the metrics and
handling the gear right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 19:24 RobertQuinn4 ***@***.***>
ha scritto:

> Hello again
>
> Just to say I have the gear tile working with Zwift click but when I go in
> Zwift and complete a test ride and save the ride does not show up on
> activities in the Zwift comp app and it does not upload to strava? Do I
> need to adjust some setting. My Zwift rides are set to load automatically
> to strava.
>
> Thanks
>
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
Enable the debounce setting in the zwift setting in the accessories in qz

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 20:19 RobertQuinn4 ***@***.***>
ha scritto:

> My mistake, the test ride was under 2k so don’t register! All ok now. The
> only other feedback is about the sensitivity of the Zwift click, if you
> press it too hard it goes up 2 settings instead of 1. Maybe it is about
> getting used to it!
>
> Thanks
>
> Robert
> Sent from my iPhone
>

**Comment by RobertQuinn4** [comment]
Yes, that is better. Thanks.
Sent from my iPhone

On 18 Sep 2024, at 19:49, Roberto Viola ***@***.***> wrote:

﻿

Enable the debounce setting in the zwift setting in the accessories in qz

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 20:19 RobertQuinn4 ***@***.***>
ha scritto:

> My mistake, the test ride was under 2k so don’t register! All ok now. The
> only other feedback is about the sensitivity of the Zwift click, if you
> press it too hard it goes up 2 settings instead of 1. Maybe it is about
> getting used to it!
>
> Thanks
>
> Robert
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
Glad to hear it! Please remember to rate the app on the store! It means a lot to me!
Thanks!
