### ISSUE TITLE
[BUG] - Can't connect to Zwift and speed control not working

### ISSUE THREAD

**Issue by SimonBB-DEV** [cagnulein/qdomyos-zwift#2600]
**Describe the bug**
Noi able to connect to Zwift anymore. It worked well before, but now Zwift do not detect the treadmill using QZ

Also,with the QZ App, the speed control no longer works in 0.5 km/h increments,  it's only stop or maximum speed when I try to adjust the speed.

**To Reproduce**
1. Go to main view, when tredmill is working.
2. Click on '+' in the Speed tile, if you click to time it's gos all up to maximum speed. If you click on '+'  it stop the treadmill

Also, even if I can start the treadmill with QZ app, Zwift do not detect any device and I'm not able to pair my treadmill.

**Expected behavior**
I want to be able at least to connect to the device with Zwift.

**Desktop (please complete the following information):**
Windows 11, with last version of Zwift

**Smartphone (please complete the following information):**
I have QZ fitness (version 2.16.39) installed on my Galaxy S21 Ultra (Android version 14 / One UI 6.1) and I'm trying to get my King Smith Walkingpad A1 Pro to work with Zwift. 

**Append a debug log**
[debug-Mon_Sep_16_13_02_36_2024.log](https://github.com/user-attachments/files/17017069/debug-Mon_Sep_16_13_02_36_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**[debug-Mon_Sep_16_13_02_36_2024.log](https://github.com/user-attachments/files/17017072/debug-Mon_Sep_16_13_02_36_2024.log)

**Comment by cagnulein** [comment]
You set the ftms treadmill setting in the treadmill settings to your
treadmill .I guess it's wrong.

Put it there disabled and press OK and restart qz

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 19:21 SimonBB-DEV ***@***.***>
ha scritto:

**Comment by SimonBB-DEV** [comment]
Just did it, change it for disabled, press ok and restart the app, and treadmill still does not appear in zwift

**Comment by SimonBB-DEV** [comment]
In Experimental features I have : 

-Turn On Enable Virtual device
-Turn On Virtual De vice Bluetooth
-Turn on Wahoo direct connect

I still can't see anything in Zwift

**Comment by cagnulein** [comment]
did you restart qz then?
where zwift is running?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 19:50 SimonBB-DEV ***@***.***>
ha scritto:

**Comment by SimonBB-DEV** [comment]
Yes, I restarted everything, the treadmill, the QZ app and even my cell phone. 

Still nothing on Zwift, 

I'm able to connect my Garmin Tactix 7 for the cardio but it's the only device Zwift detects at the moment.

I'm able to turn on the treadmill with the app and start the treadmill as well.

Zwift is installed on my Windows 11 PC.

**Comment by cagnulein** [comment]
it could be a windows issue. try this
enable the android notification icon setting in qz and restart qz
install zwift on the same android 

if this works it's some sort of issue on zwift on windows (maybe a new update with new bug?)

let me know

**Comment by SimonBB-DEV** [comment]
I closed Zwift on my PC and used the one on my cell phone and I can confirm that it works...

So definitely something with my PC... 

For now it solves my problem.


Thanks a lot!

**Comment by cagnulein** [comment]
Glad to hear it!
check the firewall (disable it)

Il giorno lun 16 set 2024 alle 20:16 SimonBB-DEV ***@***.***>
ha scritto:

**Comment by SimonBB-DEV** [comment]
I do not have firewall except the Microsoft basic one... and Zwift on my pc can log to my garmin equipement (Tacx and watch)... but something block it from connecting to treadmill true the QZ app.. but no worries as long as I can connect with my phone I'm ok

**Comment by cagnulein** [comment]
yeah i mean disable also the microsoft firewall. it could lead to these
issues

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 20:55 SimonBB-DEV ***@***.***>
ha scritto:

**Comment by SimonBB-DEV** [comment]
I did try with Firewall Off and still not working

**Comment by cagnulein** [comment]
probably something else so
let me know if you would like to try again in the future

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 16 set 2024 alle 21:04 SimonBB-DEV ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@SimonBB-DEV Any news?
