### ISSUE TITLE
[BUG] Resistance not updating

### ISSUE THREAD

**Issue by Berkers06** [cagnulein/qdomyos-zwift#2602]
[debug-Tue_Sep_17_08_23_37_2024.log](https://github.com/user-attachments/files/17026306/debug-Tue_Sep_17_08_23_37_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[Uploading debug-Tue_Sep_17_08_23_37_2024.log…]()

**Comment by cagnulein** [comment]
hi @Berkers06 yes this is why the toorx ftms setting is enabled. In this way the Bike doesn't send the resistance value at all.
If you need to see the resistance value, you need to try to disable that setting and enabling the toorx bike setting instead.
If in this way it doesn't work show me a fresh debug log

**Comment by Berkers06** [comment]
where do I enable / disable that? Right now I'm in toorx/iConsole settings
and I only have toorx ftms bike enabled and toorx srx 500

Op di 17 sep 2024 om 11:44 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
here 

![image](https://github.com/user-attachments/assets/d83a96f1-ec11-43fb-b65c-22fc453bd293)

**Comment by Berkers06** [comment]
would I then still be able to control my bike resistance level from both my
bike and phone?

Op di 17 sep 2024 om 14:05 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
yes it should. if it doesn't work I can add it in case. We have to try to understand how it reacts :) I'm here to help you along this way :)

**Comment by Berkers06** [comment]
the app crashes when doing that, ill stick to my old settings

Op di 17 sep 2024 om 15:47 schreef Roberto Viola ***@***.***>:

**Comment by Berkers06** [comment]
How do I do that?

Op di 17 sep 2024 om 19:44 schreef Roberto Viola ***@***.***>:

**Comment by Berkers06** [comment]
Okay,

I do not have a lot of time this week, do you mind if I do it whenever I've
time?

Op di 17 sep 2024 om 19:47 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
Sure, no problem. I will be here waiting for you, no rush!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 17 set 2024 alle ore 19:49 Berkers06 ***@***.***>
ha scritto:
