### ISSUE TITLE
[BUG] Proform Carbon TL Connects But Peloton Cannot Force Speed and Incline

### ISSUE THREAD

**Issue by bkeown64** [cagnulein/qdomyos-zwift#2605]
**Describe the bug**
When attempting to run the latest iOS beta release of QZ to attempt to use the Peloton app with my Proform Carbon TL treadmill, the Peloton app (upon initial installation of the iOS QZ beta app) will report the manually set treadmill speed and inclination settings and the speed/inclination ranges called out by the Peloton instructors, but will not control speed and inclination through the instructors callouts.  

Additionally, when attempting additional classes after the initial class has been run after installation of the beta app, the manually set treadmill speed and inclination settings no longer report on the Peloton app. 

**Expected behavior**
Have the app control the speed and inclination settings called out by Peloton instructors.  At a minimum, the treadmill's manually set speed and inclination settings should be reported on screen within the Peloton app.  After the initial installation and first class run, these setting no longer appear.

**Screenshots**
![unnamed](https://github.com/user-attachments/assets/1fe47ff5-770a-4a6e-8c1b-c281154321c2)

This is what the peloton screen looks like on Android tablet after the initial installation and first class run using beta QZ app. Classes beyond initial class run no longer report treadmill settings, just suggested Peloton treadmill metrics called out by coaches.

 - Device: iPhone 15 Pro Max
 - OS: 17.6.1 
 - Also ran on a Lenovo P12 Tablet using Android 14 - identical results and bugs on both devices. 

**Append a debug log**

[debug-Tue_Sep_17_07_40_32_2024.log](https://github.com/user-attachments/files/17044123/debug-Tue_Sep_17_07_40_32_2024.log)

  
**Additional context**

**Comment by cagnulein** [comment]
@bkeown64 as i said by email i also need a debug log from android so i can compare why it's working ok on android after my patch and it doesn't on ios

thanks

https://github.com/cagnulein/qdomyos-zwift/issues/2571

**Comment by bkeown64** [comment]
It’s not working on either android or iOS.  I get the same results with both.  Sent from my iPhoneOn Sep 18, 2024, at 10:27 AM, Roberto Viola ***@***.***> wrote:﻿
@bkeown64 as i said by email i also need a debug log from android so i can compare why it's working ok on android after my patch and it doesn't on ios
thanks
#2571

**Comment by cagnulein** [comment]
But you said it was working on android with the beta that I sent you! So it
wasn't?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 18:42 bkeown64 ***@***.***> ha
scritto:

**Comment by bkeown64** [comment]
No, neither one has worked by controlling speed or resistance. We may be
misunderstanding each other.

If you mean by "working" the Peloton app can report the manually entered
speed and the incline of the treadmill as entered by me on the treadmill
and then delivered to the QZ app, then on BOTH Android and iOS it "worked"
by this definition immediately after installation of the Beta app by
reporting the speed and incline on the Peloton app, BUT then did stopped
working when attempting to take a second or third class on either Android
or iOS.

If you mean by "working" that the Peloton app actually changes the speed
and incline of the treadmill based on the Peloton instructor's callouts,
then neither Android or Apple has worked at all.

**Comment by bkeown64** [comment]
It is working!
