### ISSUE TITLE
[BUG] older power zone class does not grab homefitnessbuddy erg 

### ISSUE THREAD

**Issue by tmills1073** [cagnulein/qdomyos-zwift#2606]
**Describe the bug**
I’m taking an older power zone class. It used to pull down the Settings from Home fitness buddy if it wasn’t able to do the erg mode from peloton.  However, I am not getting any erg data to follow along.

**To Reproduce**
1: Start QZ and connect
2: Start older PZ class - this one was from '21
3: QZ doesn't connect to HFB

**Expected behavior*
QZ app should pull down the ERG mode from Home fitness buddy to follow class.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Device: iPHone 13 
 - OS: [e.g. iOS18

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @tmills1073 I don't see the debug log with the error

**Comment by tmills1073** [comment]
[debug-Wed_Sep_18_11_53_06_2024.log](https://github.com/user-attachments/files/17046801/debug-Wed_Sep_18_11_53_06_2024.log)

**Comment by tmills1073** [comment]
SOrry, I hit comment before I found the debug log

**Comment by cagnulein** [comment]
No worries.
I will check it ASAP I'm currently on a business trip

Il giorno mer 18 set 2024 alle 18:03 tmills1073 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @tmills1073 i guess you have the pzp username not set to "username" all lowercase and without the "". if not set it to it and it will work, I also handled this case so we don't need HFB for this because peloton is also adding them in the API!

**Comment by tmills1073** [comment]
Great. Thank you!!!
