### ISSUE TITLE
Sole F85 Not Inclining

### ISSUE THREAD

**Issue by Middy2000** [cagnulein/qdomyos-zwift#2607]
User has a Sole F85 treadmill.  Australia based.

Qz is connecting via iPhone and speed is being reported on Zwift which is running on Windows.

However there is no auto incline.
![Messenger_creation_1DFC24F0-9EA9-4423-AB9B-D9D594A2AC56](https://github.com/user-attachments/assets/10147c7b-e56f-44d8-944a-9fcce4f9597f)
![Messenger_creation_A9C879D4-C10D-47BA-BF8B-F0831F3D0765](https://github.com/user-attachments/assets/3e1f4328-6221-41b9-87f8-bc73f5220f18)
![Messenger_creation_B3CD6BB9-8477-4DE9-80CA-1AAE6D7EB156](https://github.com/user-attachments/assets/dfa5d43c-602d-4777-a8e7-35e87cddf0e8)

[debug-Thu_Sep_19_12_03_23_2024.log.txt](https://github.com/user-attachments/files/17053862/debug-Thu_Sep_19_12_03_23_2024.log.txt)

**Comment by cagnulein** [comment]
@Middy2000 This firmware doesn't handle the ftms command for security reasons : ask to the user if she is able to change the inclination from the sole app

**Comment by Middy2000** [comment]
I thought this issue had been resolved with the F85? I know USA users it was locked?

**Comment by cagnulein** [comment]
Every country has a different firmware 
It could be that with the sole inclination experimental settings she could be able to do it, but first she need to check with the sole app

Fitness world is really crazy @Middy2000  ;)

**Comment by Middy2000** [comment]
Just checked and she can adjust it using Sole App.

So Is there a setting to change?

**Comment by cagnulein** [comment]
Yes start with enable this 

![image](https://github.com/user-attachments/assets/d3ee8017-8a55-4b43-bd65-e8e889677812)

And restart Qz

**Comment by Middy2000** [comment]
[debug-Thu_Sep_19_15_00_30_2024.log.txt](https://github.com/user-attachments/files/17055049/debug-Thu_Sep_19_15_00_30_2024.log.txt)
User has done a quick test and reports this.

"Ok…very short on time, but I quickly loaded qz and Zwift after turning on Inclination (experimental) as you suggested.

Once I was into Zwift and repaired, I initially could not start or stop my TM to begin my run.

Tried again but this time I was able to start and stop my TM, but my runner in Zwift never moved, as i kept getting the connection dropped error in Zwift."

**Comment by cagnulein** [comment]
we have to distinguish the issues.
Let's first check that with the sole inclination experimental settings the user is able to start the treadmill (even with the start physicail button of the treadmll) and change the inclination up and down from the app. Do you know if it's so?

**Comment by Middy2000** [comment]
I will get them to check.  As they are in Australia the time difference makes it hard to get answers during our working time.

**Comment by cagnulein** [comment]
@Middy2000 for example this f85 has ftms with auto inclination https://github.com/cagnulein/qdomyos-zwift/issues/2552
maybe we can try to double check the firmware? maybe the user has a pending firmware update?

**Comment by Middy2000** [comment]
Hi, Stuart.

Here is the latest error log.

Please note, I was able to Bluetooth connect to Zwift, but I could not actually start running.  In fact, once I told Zwift to start run, I immediately received a connection error message.  So I went into menu and reconnected, but was still unable to actually start running.

So, this is my setup:

Zwift is running on a PC and displays on a large screen TV.
QZ and Companion App are installed on my iPad.  QZ is the latest beta version.
My TM is a Sole f85, apparently a 2014/2015 Model running software version 
AC00490-02 191122 D-V1.01
20190122 11-0
As far as I can determine, there is no update to this software.  Newer versions of the f85 can be updated, but this is a slightly older version.  I’ve been running it since about 2016/2017, I think.
[debug-Sat_Sep_21_16_56_57_2024.log.txt](https://github.com/user-attachments/files/17083522/debug-Sat_Sep_21_16_56_57_2024.log.txt)
![Screenshot_20240921_102105_Messenger](https://github.com/user-attachments/assets/bf117c66-1b9c-48bb-a768-1fa98b079aae)

**Comment by cagnulein** [comment]
Ok so I guess that these new firmware needs different commands from the standard one. 

We can try 2 ways:

The first one, the easier one: enable one by one (only one active at a time) these setting and restart qz. Try to control the treadmill, if you can't, pass to the next one

![image](https://github.com/user-attachments/assets/53f55707-0a05-462e-ae69-7488a18d8f66)

If no one of them are working we need an android device to collect the logs with the sole app https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know
