### ISSUE TITLE
hR monitor keeps losing connection 

### ISSUE THREAD

**Issue by FL9Tor** [cagnulein/qdomyos-zwift#2612]
**Describe the bug**

**To Reproduce**

**Expected behavior**
[debug-Thu_Sep_19_19_09_04_2024.log](https://github.com/user-attachments/files/17067994/debug-Thu_Sep_19_19_09_04_2024.log)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi! In the ant settings, you have ant heart enabled. Try to disable it,
it's conflicting with the Bluetooth one
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 01:54 FL9Tor ***@***.***> ha
scritto:

**Comment by FL9Tor** [comment]
That worked perfectly. The wahoo ID for the HRM  was different than cadence and  resistance. I disconnected all on Zwift and started again and it worked fine. Enjoy the coffees.Lorne Erenberg On Sep 19, 2024 10:59 PM, Roberto Viola ***@***.***> wrote:
Hi! In the ant settings, you have ant heart enabled. Try to disable it,

it's conflicting with the Bluetooth one

Let me know



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 20 set 2024 alle 01:54 FL9Tor ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Glad to hear it!
Thanks for the coffees
Have a nice weekend!

Il giorno ven 20 set 2024 alle 18:20 FL9Tor ***@***.***> ha
scritto:

> That worked perfectly. The wahoo ID for the HRM  was different than
> cadence and  resistance. I disconnected all on Zwift and started again and
> it worked fine. Enjoy the coffees.Lorne Erenberg On Sep 19, 2024 10:59 PM,

**Comment by FL9Tor** [comment]
Heart rate monitor stopped working. I must have changed something i shouldn't have because now  zwift connection stops after 15 secs.Can i pls send u a few screen grabs ?Lorne Erenberg TorontoOn Sep 20, 2024 1:18 p.m., Roberto Viola ***@***.***> wrote:
Glad to hear it!

Thanks for the coffees

Have a nice weekend!



Il giorno ven 20 set 2024 alle 18:20 FL9Tor ***@***.***> ha

scritto:



> That worked perfectly. The wahoo ID for the HRM  was different than

> cadence and  resistance. I disconnected all on Zwift and started again and

> it worked fine. Enjoy the coffees.Lorne Erenberg On Sep 19, 2024 10:59 PM,

**Comment by cagnulein** [comment]
Sure send me a debug log

**Comment by FL9Tor** [comment]
[debug-Tue_Jan_21_20_08_53_2025.log](https://github.com/user-attachments/files/18498575/debug-Tue_Jan_21_20_08_53_2025.log)

after numerous reboots of the tablet i run your app on and my pc, i am not able to see the app as Tab which is better then nothing.  seems like the heart rate sensor wont be found. though, thank you for all your help - Lorne

**Comment by cagnulein** [comment]
I can't download the log, could you please upload it again?
