### ISSUE TITLE
[BUG] Bluetooth volume controls on Android not working to change gears

### ISSUE THREAD

**Issue by marklogan17** [cagnulein/qdomyos-zwift#2614]
Running QZ on android - tried Samsung Galaxy tab 6 lite, S20FE phone and OnePlus Open phone.  Connecting to Echelon EX-1 bike.  Configured setting for ‘volume buttons to change gears’.  Run QZ, connect to bike, hit start (tried while paused with same results), Resistance gets set to the minimum that is configured.  Use volume buttons on device and gears change as expected.  Use volume changer on Bluetooth device and the ‘Bluetooth’ volume changes on the tablet or phone but no change to gears.  Tried a Bluetooth audio device with volume and prev/next buttons - neither the volume nor the prev/next buttons worked.  Also tried my Bluetooth earbuds with same result.

Note that when you use the volume buttons the ‘volume’ on the phone/tab doesn’t change.  When I use the Bluetooth volume controls the actual volume on the phone/tab changes.

Looked in the log file (attached) and you can see the OnVolumeUpButton call when using the physical buttons but no other log entries at all that I could find for when the Bluetooth volume changed.

I did a little research and found that Android passes media events to the most recent media source.  Some people have worked around it by playing a quick sound at start to make it a media source.  Not sure if that’s the problem since the physical volume buttons worked, but I guess it’s possible.  All the devices are on recent android so there could also have been a change to the API.

This link shows the flow chart for how they find the right app to send media events to.  I’m not sure its changed recently so again, not convinced that this is the source of the problem
https://developer.android.com/media/legacy/media-buttons

Two logs attached, one from S6 tab and one from OnePlus Open phone.  OnePlus log has a ‘volume down’ event too.

[debug-Sat_Sep_21_14_31_33_2024.log](https://github.com/user-attachments/files/17085953/debug-Sat_Sep_21_14_31_33_2024.log)
[debug-Sat_Sep_21_15_20_42_2024.log](https://github.com/user-attachments/files/17085954/debug-Sat_Sep_21_15_20_42_2024.log)

**Comment by cagnulein** [comment]
thanks mark i will try to investigate this. the only strange thing is that
it's working with the majority of the users, maybe it's something about the
bluetooth remote that you are using? is it a bluetooth 2.0?
i will try on my pixel 6 to check that's working properly and i will update
you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 22 set 2024 alle 01:01 marklogan17 ***@***.***>
ha scritto:

**Comment by marklogan17** [comment]
The problem could be the device, although it’s the same one that  @Brodie01 uses for iOS (he opened the issue for the prev/next track suggestions - #2347.   I also tested with a pair of Bluetooth earbuds and got the same result.  Happy to try something else too.  

Here’s the device.  It’s Bluetooth 5.3:
https://www.amazon.ca/dp/B0C5CZDT65?ref=ppx_yo2ov_dt_b_fed_asin_title

**Comment by cagnulein** [comment]
ok i guess the difference it's because it's not a bluetooth 2.0
i will check this in the next days

**Comment by cagnulein** [comment]
@marklogan17 i created  a branch for this
the new apk will be here at the bottom
https://github.com/cagnulein/qdomyos-zwift/actions/runs/10990878591

can you try to give it a go: i'm just logging the events, it will not change the gears. let's see if it's better
show me a debug log then
thanks

**Comment by cagnulein** [comment]
sorry new link https://github.com/cagnulein/qdomyos-zwift/actions/runs/10992013380/job/30515561534

**Comment by cagnulein** [comment]
new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/10995996933/artifacts/1966678511 @marklogan17

**Comment by marklogan17** [comment]
New log...
[debug-Mon_Sep_23_10_50_23_2024.log](https://github.com/user-attachments/files/17099587/debug-Mon_Sep_23_10_50_23_2024.log)

**Comment by Nagusia** [comment]
Just to say that by chance I downloaded the QZ app today and have experienced the exactly same problem as described by marklogan17 in the first post above. My setup is Zwift on ATV with QZ app on a Pixel 4A. I have tried three different bluetooth headphones (Bluetooth 3.0, 4.1 and 5.1). I can get everything working (including Zwift Play controllers and HRM) via QZ and can use the phone volume control to change gear but not the bluetooth. If it helps I will work out how to get a debug log to you.

**Comment by cagnulein** [comment]
@Nagusia Hi, give it a try to this build too https://github.com/cagnulein/qdomyos-zwift/actions/runs/10995996933/artifacts/1966678511

It's promising

**Comment by Nagusia** [comment]
Hi. I've given it a try but still can't get gear changes with bluetooth volume control. Here's a debug log - hope I've done it right. With Android these days the only way to get at settings/profile/debug files is using ADB.
[debug-Mon_Sep_23_20_18_26_2024.log](https://github.com/user-attachments/files/17102568/debug-Mon_Sep_23_20_18_26_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it tomorrow. What do you mean about adb?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 set 2024 alle 20:35 Nagusia ***@***.***> ha
scritto:

**Comment by marklogan17** [comment]
> Hi. I've given it a try but still can't get gear changes with bluetooth volume control. Here's a debug log - hope I've done it right. With Android these days the only way to get at settings/profile/debug files is using ADB. [debug-Mon_Sep_23_20_18_26_2024.log](https://github.com/user-attachments/files/17102568/debug-Mon_Sep_23_20_18_26_2024.log)

The debug logs are in the Documents/QZ folder.  You should be able to get there with any Android File manager app....

**Comment by Nagusia** [comment]
> The debug logs are in the Documents/QZ folder. You should be able to get there with any Android File manager app....

Not on my Pixel 4A (Android 13), but on a Samsung Tab A8 (Android 14) the folder is there. 

> What do you mean about adb?

On the Pixel, I get "access denied" with the folders where the QZ files are stored, even if I use the CX File Manager. The only way I can access them is via ADB and a terminal window on a PC.

Anyway, I am going to try this using the Samsung Tab tomorrow.

**Comment by cagnulein** [comment]
Enable the android document setting in the experimental setting to fix this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 set 2024 alle 22:22 Nagusia ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Hi. I've given it a try but still can't get gear changes with bluetooth volume control. Here's a debug log - hope I've done it right. With Android these days the only way to get at settings/profile/debug files is using ADB. [debug-Mon_Sep_23_20_18_26_2024.log](https://github.com/user-attachments/files/17102568/debug-Mon_Sep_23_20_18_26_2024.log)

I checked the log and I can see 5 events of volume up in this log with gears up for 5 times. Don't you see that? Or were you using the volume of your phone?

**Comment by Nagusia** [comment]
Yes, I 'm afraid I could only change gear with the phone's volume control (no effect on volume). The bluetooth headphones would only change volume with no effect on gears.On 24 Sept 2024 09:18, Roberto Viola ***@***.***> wrote:

Hi. I've given it a try but still can't get gear changes with bluetooth volume control. Here's a debug log - hope I've done it right. With Android these days the only way to get at settings/profile/debug files is using ADB. debug-Mon_Sep_23_20_18_26_2024.log

I checked the log and I can see 5 events of volume up in this log with gears up for 5 times. Don't you see that? Or were you using the volume of your phone?

**Comment by cagnulein** [comment]
so in the log you pressed the phone one? are you able to collect an adb logcat from this phone while you are changing the volume with the bluetooth one?

**Comment by Nagusia** [comment]
I pressed both but it seems the log only picks up the phone volume control.Re the logcat I will have a go. A bit above my skill level but it can't be that difficult, can it?I also need to try the tablet as well to see if that works.On 24 Sept 2024 14:06, Roberto Viola ***@***.***> wrote:
so in the log you pressed the phone one? are you able to collect an adb logcat from this phone while you are changing the volume with the bluetooth one?

**Comment by cagnulein** [comment]
I guess the tablet will have the same behaviour. If you can run a adb logcat it will be perfect otherwise we can wait @marklogan17 for the end of the week.

**Comment by Nagusia** [comment]
Do you need the logcat with QZ running at the same time as the bluetooth controller? Or just the bluetooth? It's a logistics problem at my end.On 24 Sept 2024 14:40, Roberto Viola ***@***.***> wrote:
I guess the tablet will have the same behaviour. If you can run a adb logcat it will be perfect otherwise we can wait @marklogan17 for the end of the week.

**Comment by cagnulein** [comment]
yes with QZ running and also with the remote connected and while you are pressing several times the buttons, thanks

**Comment by Nagusia** [comment]
Here you go. I changed gear with the phone volume control once or twice, and then tried with the Bluetooth headphone which I was listening to.

**Comment by cagnulein** [comment]
thanks but you have to attach the file on github web interface otherwise i can't see it @Nagusia

**Comment by Nagusia** [comment]
[logcatQZ.zip](https://github.com/user-attachments/files/17116276/logcatQZ.zip)
Like this?

**Comment by cagnulein** [comment]
yes perfect, i'm checking it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 set 2024 alle ore 16:40 Nagusia ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
perfect i did a modification based on

`09-24 16:19:00.055  2465  2465 I vol.VolumeDialogImpl: showH r=volume_changed`

on your logcat.

I will publish it the new apk when it's ready, more or less 30 minutes

**Comment by Nagusia** [comment]
Great. I have done another logcat with the Samsung Tab. Same process and result re gear change.
[logcatQZtab.zip](https://github.com/user-attachments/files/17116617/logcatQZtab.zip)

**Comment by cagnulein** [comment]
here the new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/11016387178/artifacts/1972313610
it will not change the gears yet, but you can share a log cat with the debug log enabled also in qz so i can check if the flow is correct
let me know!

**Comment by cagnulein** [comment]
wait i need to do another small thing

**Comment by Nagusia** [comment]
I had an issue with a trial expired notification with this version but I managed to make a couple of clicks with the bluetooth volume control before this happened. Here is the logcat: 
[logcatQZ2.zip](https://github.com/user-attachments/files/17118622/logcatQZ2.zip)

**Comment by Nagusia** [comment]
[debug-Tue_Sep_24_19_43_03_2024.log](https://github.com/user-attachments/files/17118730/debug-Tue_Sep_24_19_43_03_2024.log)
Here is the debug.

**Comment by cagnulein** [comment]
It's working! Tomorrow I will do the final implementation!
Thanks for your help

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 set 2024 alle 20:08 Nagusia ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Nagusia if i'm right this will work! https://github.com/cagnulein/qdomyos-zwift/actions/runs/11028066142/artifacts/1975526018

**Comment by Nagusia** [comment]
Almost there. Both + or - on the volume control shift gears down. -1, -2 etc. Can't shift up.

**Comment by cagnulein** [comment]
can  you share a debug log?

**Comment by Nagusia** [comment]
[debug-Wed_Sep_25_10_01_24_2024.log](https://github.com/user-attachments/files/17127662/debug-Wed_Sep_25_10_01_24_2024.log)

**Comment by cagnulein** [comment]
ok i guess i fixed, i will send you the new one in 30 minutes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 25 set 2024 alle ore 10:15 Nagusia ***@***.***>
ha scritto:

**Comment by Nagusia** [comment]
OK. Will try later. Going out for a coffee!

**Comment by cagnulein** [comment]
new build
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11029092930/artifacts/1975805752

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 25 set 2024 alle ore 10:20 Nagusia ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
perfect! so do you have a problem of "debouncing" the click or you are good to go?

**Comment by Nagusia** [comment]
Depends which headphones I use. Is there a denouncing option? I think I've seen it somewhere but wasn't sure what it meant.

**Comment by cagnulein** [comment]
there is the setting but i didn't handle for this specific case, would you like to add this as well?

**Comment by Nagusia** [comment]
If it could avoid erratic shifts I guess it would be a good idea. Where is the denouncing option?

**Comment by cagnulein** [comment]
ok i'm adding it, i will send the new apk in 30 minutes
it's under the accessories->zwift->debounce

**Comment by cagnulein** [comment]
new build
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11033778084/artifacts/1977078856

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 25 set 2024 alle ore 15:12 Nagusia ***@***.***>
ha scritto:

**Comment by Nagusia** [comment]
All good now. The only problem is that the app's trial period times out!  Would it be possible to have a full version?  In any case, I've enjoyed helping you with this. The app is fantastic and seems to work better than the Zwift Companion (much faster connection and apparently more solid with ATV), as well as offering the option of virtual shifting.

**Comment by cagnulein** [comment]
sure @Nagusia 
send me an email to roberto.viola83 at gmail.com indicating this ticket!
Set then the same email where you are sending me it to the email setting in qz all lower case to unlock it

**Comment by cagnulein** [comment]
i will also wait @marklogan17 to merge this to the master!

**Comment by marklogan17** [comment]
I tried it and it works!  The debounce was important for the rotating knob control that I have!  Thanks for doing this @cagnulein

**Comment by cagnulein** [comment]
Glad it worked!
I will merge it today!

Il giorno ven 27 set 2024 alle 01:20 marklogan17 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@marklogan17 one question: what happens if you change the volume with the physical buttons of the phone? do you see a step of 2?

**Comment by Nagusia** [comment]
No. It works perfectly for me. Doesn't change the volume of media either which is good. The bluetooth button does though. In fact you have to have some media running (or on pause) for it to work.Yesterday I did a session on Zwift listening to media via Bluetooth. Changing gear with the phone control didn't affect volume. However, changing volume with the bluetooth headset did change the gears.On 27 Sept 2024 08:50, Roberto Viola ***@***.***> wrote:
@marklogan17 one question: what happens if you change the volume with the physical buttons of the phone? do you see a step of 2?

**Comment by Nagusia** [comment]
Actually re my comment above it may be a feature of Android. The volume control on my bluetooth headset only works with media playing. If the media is stopped you can't adjust the volume. This is true on both my devices.

**Comment by Nagusia** [comment]
I just left a review on your app on reddit for Zwift users in my position re no update of Wahoo firmware to enable virtual shifting on our Kickrs. https://www.reddit.com/r/Zwift/comments/1fqj9vk/my_experience_of_virtual_shifting_in_zwift_using/

**Comment by cagnulein** [comment]
amazing!

**Comment by marklogan17** [comment]
> @marklogan17 one question: what happens if you change the volume with the physical buttons of the phone? do you see a step of 2?

I definitely saw a step of one  with the volume buttons 'before' turning on the debounce.  Almost certain I tried it again after turning on the debounce and got a step of one.  Basically I've never seen a problem with the physical buttons

**Comment by cagnulein** [comment]
ok my doubt was that the new handling will causing a +1 with the old one. So you are saying that it's not the case right? If so I will merge it!

**Comment by cagnulein** [comment]
guys are you both on android 14 for this? this it's causing issues with android 6 and 7 so i'm trying to understand which filter add

**Comment by Nagusia** [comment]
I

> guys are you both on android 14 for this? this it's causing issues with android 6 and 7 so i'm trying to understand which filter add

I'm on Android 13. I bought a Zwift Click instead of a BT volume control gadget so in any case can't really give much useful feedback.

**Comment by cagnulein** [comment]
Ok Thanks anyway @Nagusia

**Comment by marklogan17** [comment]
Currently using on a OnePlus Open on Android 14.  I think the Galaxy Tab that I was using it on before was on 14 at the time too...
