### ISSUE TITLE
[BUG] App freezes and lags when connected to my bike

### ISSUE THREAD

**Issue by TomFugere** [cagnulein/qdomyos-zwift#2617]
[debug-Tue_Sep_24_06_42_49_2024.log](https://github.com/user-attachments/files/17113402/debug-Tue_Sep_24_06_42_49_2024.log)

**Describe the bug**
App is laggy and freezes when connected to my bike, no data can be sent in real time. Seems to work fine without the bike connected, but has soon as my bike connects it no longer works.

**Smartphone (please complete the following information):**
 - Device: google Pixel 8
 - OS: Android 14

**Comment by cagnulein** [comment]
hi @TomFugere from the log i don't see anything unusual. do you already reboot your phone? maybe android was going mad?

**Comment by TomFugere** [comment]
Yes, I already tried rebooting my phone, still lagging. It's like everything is slowed down when my bike connects. Some data appears after 10-15 seconds, then freezes and refresh 10-15 seconds later. The only thing I did not try is deleting the app to download again since I don't want to lose my settings.

**Comment by cagnulein** [comment]
i can see the delay on the UI but I don't understand what's happening. Do you have the same behaviour also with the debug log turned off?

**Comment by TomFugere** [comment]
Weirdly I turned off the debug log and tried everything again as usual and it worked perfectly fine. I just ended a ride without any problems!

**Comment by cagnulein** [comment]
so it seems a problem on the flash of the phone..if you turn on back you will have again the issue?
