### ISSUE TITLE
[BUG] Domyos 500 profile Always on

### ISSUE THREAD

**Issue by danielctin14** [cagnulein/qdomyos-zwift#2618]
Continuing discussion from [issue 2573](https://github.com/cagnulein/qdomyos-zwift/issues/2573).

Regardless of the Setting the wattage profile is on. I cannot go back to how it was before, changing it to off doesn't do anything for me.

Version 2.16.69
Log below where I did gear 1 with setting on and gear 1 with setting off and it's the same wattage.

[debug-Wed_Sep_25_15_13_13_2024.log](https://github.com/user-attachments/files/17130827/debug-Wed_Sep_25_15_13_13_2024.log)

**Comment by cagnulein** [comment]
@danielctin14 i checked the log and the code.
The modification https://github.com/cagnulein/qdomyos-zwift/commit/2955ac9751a7027f1a543a8a69a62944a2b2aef2 is completely retrocompatible.

You have now the setting domyos wattage v1 enabled and with resistance < than 8 this is the algorithm used

`return ((10.39 + 1.45 * (resistance - 1.0)) * (exp(0.028 * (currentCadence().value()))));`

this is untouched from the very beginning!

the modification above it's not in the 2.16.69, it's in the 2.16.70 and there is a new v2 profile. so i guess you were using the v1 setting disabled?

**Comment by danielctin14** [comment]
Ok, but how to I change it? Since I am clicking on the toggle on and off, is the setting not saving by just doing that? Do I need to press something after it?

**Comment by cagnulein** [comment]
@danielctin14 let's start from the beginning: on the previous version which was the value of the v1 setting? disabled? so put it disabled again.
if so, if you reopen qz, it's still disabled?

**Comment by cagnulein** [comment]
> When the new update downloaded and I opened the App another Permissions pop-up for Bluetooth showed, any chance it has something to do with this?

nope :)



> Also can I somehow downgrade back to .66 in the meantime?

yes you can leave the beta from the play store, you should see then the button to downgrade the app.

do you have a debug log from a previous version? i would like to compare the result.

**Comment by danielctin14** [comment]
Ok, downgraded to .66 and make a mini ramp test to get a new debug log. Here come the crazy watt numbers:

[debug-Wed_Sep_25_16_20_08_2024.log](https://github.com/user-attachments/files/17131609/debug-Wed_Sep_25_16_20_08_2024.log)

**Comment by cagnulein** [comment]
ok so can you do a simple resistance 1 test with cadence 80 so i can compare the both logs? from a first point of view it seems that .66 and .69 are doing the same. which is the number that it's telling you the different behaviour? wattage? at which resistance? 
sorry but i'm still confusing

**Comment by danielctin14** [comment]
Yes, the Watts from all the Resistances. From this test it looks like .66 is showing 100+ watts compared to 60+ in .69

[debug-Wed_Sep_25_16_35_13_2024.log](https://github.com/user-attachments/files/17131758/debug-Wed_Sep_25_16_35_13_2024.log)

**Comment by cagnulein** [comment]
got it now, i'm trying to understand this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 25 set 2024 alle ore 15:38 danielctin14 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
got it the issue! it's because the 2.16.69 it's using the standard FTMS profile from your bike! since the bike it's now providing the wattage value directly, QZ was using it by default. In case I can add a setting to revert this behaviour

**Comment by danielctin14** [comment]
If the bike is providing real data, maybe EB 520B is not the same as Bike 500 when it comes to settings.

I'll do some more tests in the future to see if at least they are the same. Tried this morning for the first time connecting the bike directly to Kinomap to see the watts but they were way off, 400W in resistance 1, do you know another app to test the FTMS directly?

**Comment by cagnulein** [comment]
you can try also zwift for example
