### ISSUE TITLE
[BUG]Pro-Form City T7

### ISSUE THREAD

**Issue by Bob16180** [cagnulein/qdomyos-zwift#2619]
**Describe the bug**
Unable to connect iPhone to treadmill. 

**To Reproduce**
Followed directions, installed the app on the Treadmill. Adding the IP address in App. App doesn't show any update.
Zwift running in Windows 10 see the Wahoo Tread 0003.

**Expected behavior**
Connect to Treadmill

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS18
 - Version 2.15.4

**Append a debug log**
[debug-Wed_Sep_25_16_00_37_2024.log](https://github.com/user-attachments/files/17138008/debug-Wed_Sep_25_16_00_37_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi you have to set the ip in the nordictrack 2950 ip setting not in the proform ip.
remove from the proform ip completely and press ok and set it in the 2950

restart qz then

i'm going to bed, i will reply back tomorrow

**Comment by Bob16180** [comment]
Thank you, that resolved it. Should I have known to use Nordictrack when I have a Proform and there's a section for Proform?
