### ISSUE TITLE
[REQ] Sportstech SX200

### ISSUE THREAD

**Issue by fab0nymous** [cagnulein/qdomyos-zwift#262]
Hi,

I got a Sportstech SX200.

I can connect via Android qdomyos-zwift App to the bike. Setting of iconsole Bike is enabled. No data is provided by the bike to the app. Other apps seem to get the connection e.g. MyHomeFit. I would like to use my bike with zwift :)

I tried to grab the hci log, but on huawei it is not as straight forward as the manual says.. hopefully this file is correct.
Thanks !
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6292252/btsnoop_hci.log)

**Comment by cagnulein** [comment]
hi, could you attach here also the debug log from QZ itself?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 apr 2021 alle ore 18:33 fab0nymous <
***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
Hi, 
sure
[debug-Sun_Apr_11_19_06_48_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6292318/debug-Sun_Apr_11_19_06_48_2021.log)

**Comment by cagnulein** [comment]
thanks, i will check it tomorrow (GMT+1 here).

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 11 apr 2021 alle ore 19:08 fab0nymous <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@fab0nymous i guess you have to enable the JLL_IC400 setting too. your bike has the same procotol of it i guess. If it still doesn't work, send me again the new debug log

**Comment by fab0nymous** [comment]
Hi,

I enabled also the JLL_IC400 setting. While I now have a readout f or speed and rpm, this readout is fixed and not changing when using the bike. It also seems a bit high ;)

![Mo  Apr  12 10_35_50 2021](https://user-images.githubusercontent.com/20743863/114366220-85065700-9b7b-11eb-933c-50d5e1b8745d.jpg)
[debug-Mon_Apr_12_10_35_08_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6295129/debug-Mon_Apr_12_10_35_08_2021.log)

**Comment by fab0nymous** [comment]
I see you have already fixed this issue with #243 . I guess I'll wait for the Android update then :)

**Comment by cagnulein** [comment]
@fab0nymous  yes exactly :)

**Comment by fab0nymous** [comment]
Great! Thanks ! Is there a beta apk to test with ?

**Comment by cagnulein** [comment]
i will upload it today. are you on the beta channel? if not, send me an email to roberto.viola83@gmail.com and i will add you

**Comment by cagnulein** [comment]
update is live. tell me if it works

**Comment by fab0nymous** [comment]
Via Beta Channel? I am not added, I send you a mail :) If via regular update via play store maybe it takes a moment to have the update shown ..

**Comment by cagnulein** [comment]
Answered to your mail ;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 12 apr 2021 alle ore 15:28 fab0nymous <
***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
Hi Roberto,

thanks for adding me and sharing the beta. I have tested it with my bike.

First of all Speed, RPM and the Odometer works. But Watt and built in Heart Rate are not shown unfortunately. Tested Heart Rate with and without FTMS and directly assigned my bike as a heart rate sensor. No values are shown. Watt is never updated.
Overall performance of refresh rates of Speed, RPM and Odometer is poor. It takes a few moments to first show data and refresh can take minimum 10 seconds.
Have not tested connection to Zwift in detail as no Wattage is supplied. But first test did show my Phone as Power Source but directly saying No Signal, will need to look at this in depth.
[debug-Tue_Apr_13_10_25_50_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6302343/debug-Tue_Apr_13_10_25_50_2021.log)

**Comment by cagnulein** [comment]
i already fixed the poor refresh rate in the 2.6.2, i'm waiting that google will review it (since yesterday :O)
i don't think heart rate is sending to bluetooth neither watt. Infact i saw only one byte changing in your frames and it's the cadence.
On zwift we have 2 scenario:
1) use only the cadence with the cadence peloton setting set to ON
2) use an external HR and use my new HR based algorithm to provide watt (better than nothing)

anyway we have to wait google for the reviewing

**Comment by fab0nymous** [comment]
Ok I will check refresh rates with the next update ! Thank you :)

Regarding HR and Wattage I was sure to see the readouts on other apps. MyHomeFit at least for HR and I think I saw Watt & HR on Kinomap-app. Shall I provide a new bluetooth log when running the Kinomap app ?

**Comment by cagnulein** [comment]
Yes sure, because the one you uploaded in the very first post is corrupted
R.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 apr 2021 alle ore 10:57 fab0nymous <
***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
My damn Huawei giving me hard time, btsnoop log is not that easy accessible.. Maybe one of these files are valid .. 
[btsnoop_hci_20210413_114107.log](https://github.com/cagnulein/qdomyos-zwift/files/6302816/btsnoop_hci_20210413_114107.log)
[btsnoop_hci_20210413_113816.log](https://github.com/cagnulein/qdomyos-zwift/files/6302817/btsnoop_hci_20210413_113816.log)

**Comment by cagnulein** [comment]
in the 1138 file i saw finally the heart rate (more or less 80 is it right?)
no sign of power, i guess kinomap uses my algortithm based on heart rate.
Do you see the SAME Wattage between the console of your bike and kinomap?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 apr 2021 alle ore 11:49 fab0nymous <
***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
Oh man .. My console does not even show wattage, I guess you are correct.. sorry for distraction.
Yes I think HR was about right, I uploaded another log with heart rates between 80 and 100+ 
[btsnoop_hci_20210413_120817.log](https://github.com/cagnulein/qdomyos-zwift/files/6302938/btsnoop_hci_20210413_120817.log)
[btsnoop_hci_20210413_114107.log](https://github.com/cagnulein/qdomyos-zwift/files/6302939/btsnoop_hci_20210413_114107.log)

**Comment by fab0nymous** [comment]
Just had a look at the 2.6.3 beta.

Cadence and RPM are looking good with very good refresh times 👍 
I have not gotten built in HR sensor to work. With outside of FTMS and no bluetooth device defined in that option, the HR is about 100 bpm when not touching anything on the bike and becomes greater when accelerating and also not touching the sensor. Defining the bluetooth device and und check the outside FTMS option the HR is at 0 and stays at that value when touching the sensors. But I think as you saw HR in my preview log, this is also transmitted :)

BR

**Comment by cagnulein** [comment]
Could you send the qdomyos-zwift log of this version?

Il mer 14 apr 2021, 17:41 fab0nymous ***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
Sure, should be this one.

In this setting, Zwift can see my phone as speed and rpm source, but both readouts with 0 mph and 0 rpm. app shows correct values.

[debug-Wed_Apr_14_18_54_13_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6312477/debug-Wed_Apr_14_18_54_13_2021.log)

**Comment by cagnulein** [comment]
Heart rate fixed. I did an error but you have to unselect the heart rate
name setting, leave it to disabled.
For Zwift: in the next version (i will upload it this evening i guess) i
added a simulated power algorithm based on your heart rate.
I will explain later how does it work.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 14 apr 2021 alle ore 18:58 fab0nymous <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Version online

**Comment by cagnulein** [comment]
An user confirms me that it worked ;)
