### ISSUE TITLE
[BUG] No linear resistance for virtual shifting 

### ISSUE THREAD

**Issue by RainerSaemann** [cagnulein/qdomyos-zwift#2620]
**Describe the bug**

I configured the gear gain to 0.1. If I increase shifting starting from 1.0 there is more or less not noticeable resistance up to 2.9.
Shifting from 2.9 to 3.0 there is a major increase. 

Can the delta between the gears somewhere configured? Or let say I would expect
similar to a real bike a more or less linear increase during the gear range.

**To Reproduce**

Installed QZ App version 2.16.69 (via testflight / Beta version)

Zwift Ride with KICKR CORE (standard from Zwift shop)
coming along with Zwift play controller and 
Zwift Cog. (latest firmware applied before testing)

Setting - Bike Option
- Gears Gain: 0.1
- FTMS Bike: KICKR CORE 46F4

QZ connected to KICKR CORE via BT

I tested the behavior without connecting to a 3rd party app (myWhoosh or Rouvy)
to see if it behaves in the same way, and indeed it can be reproduced
in QZ standalone.
 

- QZ connectec to Zwift Ride via BT
- Gear numbers can be seen tile of QZ (e.g 1.x --> 5.x)
- by shifting on the Zwift play buttons I see the value in the tile in- or decreasing
- in the range from 1.0 till 2.9 there is a minor or no real change in the resistance during paddaling
- with the next shift 2.9 to 3.0 there is a massive change in resistance
- between 3.0 and 4.0 seems stable or slightly linear increase of resistance
- 4.1 to 5.0 seems lower resistance compared than before
**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Apple iPhone XS
 - OS:  iOS v17.7
 - Version QZ v2.16.69 (beta via testflight)

**Append a debug log**

[debug-Do__Sept__26_09_15_30_2024.log](https://github.com/user-attachments/files/17145155/debug-Do__Sept__26_09_15_30_2024.log)

**Comment by cagnulein** [comment]
hi @RainerSaemann i will check the log asap, in the meantime, could you please try the new experimental setting called 

`Use Zwift app ratio for gears (Experimental)`

under the zwift accessories setting?

**Comment by cagnulein** [comment]
hah i just saw that you already it enabled. let's check with the new version that I sent you. I updated the gear value as the zwift ones!

**Comment by RainerSaemann** [comment]
@cagnulein: Yes, I already had this enabled. With the latest version you sent (2.16.70) it seems fixed. 
log debug-Do__Sept__26_10_35_34_2024_1.log  --> same test as initially done --> linear resistance as expected
log debug-Do__Sept__26_10_35_34_2024_2.log --> adapted Gear Gain to 1.0 --> conected to myWhoosh and also working fine. 

one thing I recognized - when shifting from 2 to 17 it is increasing by 1 always, decreasing from 17 to 2 it is decreasing by 2. Maybe a missconfiguration on my side, also no issue, I only recognized it :-)


[debug-Do__Sept__26_10_35_34_2024_1.log](https://github.com/user-attachments/files/17145921/debug-Do__Sept__26_10_35_34_2024_1.log)
[debug-Do__Sept__26_11_12_41_2024_2.log](https://github.com/user-attachments/files/17145924/debug-Do__Sept__26_11_12_41_2024_2.log)

**Comment by cagnulein** [comment]
that's great @RainerSaemann 



> one thing I recognized - when shifting from 2 to 17 it is increasing by 1 always, decreasing from 17 to 2 it is decreasing by 2. Maybe a missconfiguration on my side, also no issue, I only recognized it :-)

for this i sent a newer version! I guess I already fixed this too!

**Comment by RainerSaemann** [comment]
@cagnulein 

the last test, where I recognized the downl shifting by two instead of one was already performed with this latest version (2.16.70) or wasn't the rev. changed by only functionality, so I can retest again

**Comment by cagnulein** [comment]
Don't mind about the 2.16.70, the important one is the build, and I send a
newer one :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 set 2024 alle 13:01 RainerSaemann ***@***.***>
ha scritto:

**Comment by RainerSaemann** [comment]
@cagnulein Great job - is fixed too👍

**Comment by cagnulein** [comment]
Awesome, please remember to rate the app on the store! It means a lot to me!
Thanks!


Il giorno gio 26 set 2024 alle 13:21 RainerSaemann ***@***.***>
ha scritto:

**Comment by RainerSaemann** [comment]
sure I'll do and enjoy the coffees

**Comment by cagnulein** [comment]
Thank you so much! I'm closing this one, feel free to open it again if you have any issues!
