### ISSUE TITLE
Only getting Inclination and Resistance - NordicTrack S22i - Beta Update

### ISSUE THREAD

**Issue by EnglandAngling** [cagnulein/qdomyos-zwift#2622]
**Describe the bug**
Only getting Inclination and Resistance - other metrics such as speed, cadence, power stay at zero.

**To Reproduce**
Start the companion app on the laptop as normal then start peddling on manual mode on the S22i bike.

**Expected behavior**
Normal metrics to display

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 
 - Version 11

[Uploading debug-Thu_Sep_26_20_21_28_2024.log…]()

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @EnglandAngling i can't see the debug log, you have to wait the finish of the upload before pushing the comment button.
please upload it again
thanks

**Comment by EnglandAngling** [comment]
[debug-Thu_Sep_26_20_21_28_2024.log](https://github.com/user-attachments/files/17161357/debug-Thu_Sep_26_20_21_28_2024.log)

**Comment by EnglandAngling** [comment]
@cagnulein Done

**Comment by cagnulein** [comment]
ok are you able also to send me an adb logcat? unfortunately the issue is on the companion, and I need an adb logcat to understand what it is
Thanks

**Comment by EnglandAngling** [comment]
Can you let me know how I can do that please?

**Comment by EnglandAngling** [comment]
Ah ok...I'll try that this evening, thanks.

**Comment by EnglandAngling** [comment]
[logcat.txt](https://github.com/user-attachments/files/17167183/logcat.txt)
[2024-09-22_logs.txt](https://github.com/user-attachments/files/17167188/2024-09-22_logs.txt)

**Comment by EnglandAngling** [comment]
@cagnulein are these the files?

**Comment by cagnulein** [comment]
i will check them in the next days thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 set 2024 alle 18:43 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment]
thanks

**Comment by cagnulein** [comment]
> [logcat.txt](https://github.com/user-attachments/files/17167183/logcat.txt) [2024-09-22_logs.txt](https://github.com/user-attachments/files/17167188/2024-09-22_logs.txt)

hi i was checking the log and the OCR was getting these values

09-27 17:38:04.619  1809  1809 D OCRlines: 1 incline
09-27 17:38:04.619  1809  1809 D OCRlines: 2 idoe
09-27 17:38:04.619  1809  1809 D OCRlines: 3 VIued
09-27 17:38:04.619  1809  1809 D OCRlines: 4 iFIT:
09-27 17:38:04.619  1809  1809 D OCRlines: 5 4
09-27 17:38:04.619  1809  1809 D OCRlines: 6 resistance
09-27 17:38:04.619  1809  1809 D OCRlines: 7 I| Workout

were you on a manual workout window when you collect this log?

**Comment by EnglandAngling** [comment]
Yes it was a manual workout.

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
so in that view did you see the other values? because the OCR seems to see only these words

**Comment by EnglandAngling** [comment]
I'm not sure.....I'll give it another go this week and see what values it displays and do another log

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment]
ok share me also a picture so i can check the manual workout view too, also don't interrupt the manual workout before getting the log

**Comment by EnglandAngling** [comment]
OK

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by EnglandAngling** [comment]
![20241007_202508](https://github.com/user-attachments/assets/bc2ec3d0-2c7d-4da4-a2d2-2f068c43d488)
[debug-Mon_Oct_7_20_11_25_2024.log](https://github.com/user-attachments/files/17283557/debug-Mon_Oct_7_20_11_25_2024.log)
[debug-Mon_Oct_7_20_15_36_2024.log](https://github.com/user-attachments/files/17283559/debug-Mon_Oct_7_20_15_36_2024.log)
[debug-Mon_Oct_7_20_25_56_2024.log](https://github.com/user-attachments/files/17283562/debug-Mon_Oct_7_20_25_56_2024.log)
[logcat.txt](https://github.com/user-attachments/files/17283563/logcat.txt)

**Comment by EnglandAngling** [comment]
@cagnulein I've tried with the new APK that you listed but only get inclination and nothing else....

**Comment by cagnulein** [comment]
i will check the log asap in the mean time check this too! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/116

**Comment by EnglandAngling** [comment]
[logcat.txt](https://github.com/user-attachments/files/17298463/logcat.txt)

Is this logcat better?

**Comment by cagnulein** [comment]
perfect! ok companion is doing the right thing: could you please share a
debug log from qz?
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 21:47 EnglandAngling ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Hah wait I can see only speed and inclination in the logcat

**Comment by cagnulein** [comment]
Can you also share the file

"/sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt"

?

I'm going to bed now

**Comment by EnglandAngling** [comment]
@cagnulein OK no worries, but can you tell me how I get that file from the bike to my laptop :-)

**Comment by EnglandAngling** [comment]
[debug-Tue_Oct_8_20_44_14_2024.log](https://github.com/user-attachments/files/17298584/debug-Tue_Oct_8_20_44_14_2024.log)

**Comment by cagnulein** [comment]
> @cagnulein OK no worries, but can you tell me how I get that file from the bike to my laptop :-)

adb pull "/sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt"

**Comment by EnglandAngling** [comment]
[log.latest.txt](https://github.com/user-attachments/files/17298683/log.latest.txt)

**Comment by EnglandAngling** [comment]
see above @cagnulein thanks.

**Comment by cagnulein** [comment]
@EnglandAngling the /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt was taken during a workout? because I don't see any metrics at all.

Anyway, you see only inclination, because you have the speed based on power setting enabled on the bike settings. if you disable it, you should see also speed on qz. since i can't see the wattage and cadence from the bike, if you want, we can try to emulate the wattage from the speed value. Of course if we can read the power directly from the log it's better for both of us :)

maybe do on pc a 

adb shell tail -f /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt 


while you're doing a workout to check if you can see the metrics while you're riding

let me know!

**Comment by cagnulein** [comment]
ok so your bike is not logging neither cadence or power, that's a big
issue. if you want i can simulate it starting from the speed. this is the
only thing that i can do.
did you already try to revert the version a non beta one?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 20:17 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment]
I guess if that's the only thing you can do then I'll give it a try please before going back to non-beta....

**Comment by cagnulein** [comment]
or otherwise we have to find something else in the logs the power and the
cadence, but only you can find it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 20:38 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment]
which logs do I need to look at, and are they on the bike or the lapto?

**Comment by EnglandAngling** [comment]
@cagnulein Permission denied...

C:\EnglandAngling\Perso\MTB\QZbeta\QZCompanionNordictrackTreadmill-master\InstallPackage>adb shell grep -r Changed /
grep: /proc/aed/generate-ee: Permission denied
grep: /proc/aed/generate-dal: Permission denied
grep: /proc/aed/generate-scp: Permission denied
grep: /proc/aed/generate-wdt: Permission denied
grep: /proc/aed/generate-md32: Permission denied
grep: /proc/aed/generate-oops: Permission denied
grep: /proc/aed/generate-combo: Permission denied
grep: /proc/aed/current-ke-console: Permission denied
grep: /proc/aed/generate-nested-ke: Permission denied
grep: /proc/aed/current-ee-coredump: Permission denied
grep: /proc/aed/current-ke-mmprofile: Permission denied
grep: /proc/aed/current-ke-mini_rdump: Permission denied
grep: /proc/aed/generate-kernel-notify: Permission denied
grep: /proc/aed/current-ke-android_main: Permission denied
grep: /proc/aed/current-ke-android_radio: Permission denied
grep: /proc/aed/current-ke-android_system: Permission denied
grep: /proc/aed/current-ke-userspace_info: Permission denied
grep: /proc/hps/num_base_perf_serv: Permission denied
grep: /proc/hps/num_limit_power_serv: Permission denied
grep: /proc/m4u: Permission denied
grep: /proc/net/vlan/config: Permission denied
grep: /proc/net/wlan/setCAM: I/O error
grep: /proc/net/wlan0/met_ctrl: I/O error
grep: /proc/net/wlan0/met_port: I/O error
grep: /proc/net/fib_trie: Permission denied
grep: /proc/net/netfilter/nfnetlink_log: Permission denied
grep: /proc/net/netfilter/nfnetlink_queue: Permission denied
grep: /proc/net/nf_conntrack: Permission denied
grep: /proc/net/ip_tables_names: Permission denied
grep: /proc/net/arp_tables_names: Permission denied
grep: /proc/net/ip6_tables_names: Permission denied
grep: /proc/net/ip_tables_matches: Permission denied
grep: /proc/net/ip_tables_targets: Permission denied
grep: /proc/net/arp_tables_matches: Permission denied
grep: /proc/net/arp_tables_targets: Permission denied
grep: /proc/net/ip6_tables_matches: Permission denied
grep: /proc/net/ip6_tables_targets: Permission denied
grep: /proc/net/nf_conntrack_expect: Permission denied
grep: /proc/sys/fs/protected_hardlinks: Permission denied
grep: /proc/sys/fs/protected_symlinks: Permission denied
grep: /proc/sys/kernel/cad_pid: Permission denied
grep: /proc/sys/kernel/usermodehelper/bset: Permission denied
grep: /proc/sys/kernel/usermodehelper/inheritable: Permission denied
grep: /proc/sys/net/ipv4/route/flush: Permission denied
grep: /proc/sys/net/ipv4/tcp_fastopen_key: Permission denied
grep: /proc/sys/net/ipv6/conf/all/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/default/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/ifb0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/ifb1/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/ip6_vti0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/ip6tnl0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/ip_vti0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/lo/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/p2p0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/sit0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/tunl0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/conf/wlan0/stable_secret: Permission denied
grep: /proc/sys/net/ipv6/route/flush: Permission denied
grep: /proc/sys/vm/compact_memory: Permission denied
grep: /proc/sys/vm/mmap_rnd_bits: Permission denied
grep: /proc/sys/vm/mmap_rnd_compat_bits: Permission denied
grep: /proc/sys/vm/stat_refresh: Permission denied
grep: /proc/tty/driver: Permission denied

**Comment by cagnulein** [comment]
Permission denied it's not the issue, the issue is that it doesn't find any file with the metrics...  Don't we have any possibility to restore the original ifit version?

**Comment by EnglandAngling** [comment]
That is possible...but I was hoping to use the new Beta version as my wife uses the bike too and prefers the Beta version :-) Oh well...thanks anyway.

**Comment by cagnulein** [comment]
Let's try another one

Run a 

adb pull "/sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt"

And share the file here

**Comment by cagnulein** [comment]
Hah sorry we already did this

**Comment by EnglandAngling** [comment]
I've reset the bike, gone back to the original version of i-Fit (non Beta) and all is working as normal again.

**Comment by cagnulein** [comment]
Glad to hear, I suggest to block the update if you want to continue to use qz

**Comment by EnglandAngling** [comment]
@cagnulein An unrelated question, but does entering a login and password in Zwift options have any affect on anything?

**Comment by cagnulein** [comment]
Only for treadmills

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 ott 2024 alle 23:12 EnglandAngling <
***@***.***> ha scritto:
