### ISSUE TITLE
Debug for auto resistance

### ISSUE THREAD

**Issue by Paulieva** [cagnulein/qdomyos-zwift#2623]
I cannot get QZ to match resistance. I am using an echelon ex5 and trainerroad. I am trying to get the bike to operate with TR. Auto resistance will return to a preset level.   I am using iOS with no watch or ifit. 

[debug-Fri_Sep_27_10_22_51_2024.log](https://github.com/user-attachments/files/17166082/debug-Fri_Sep_27_10_22_51_2024.log)

*Describe the bug*. 
A clear return to predetermined resistanceand concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi! i need a log from a real session with trainer road showing the issue
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 set 2024 alle 17:04 Paulieva ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Paulieva Any news?
