### ISSUE TITLE
[BUG] Can not auto adjust downhill inclination in Kinomap- Sole TT8 treadmill

### ISSUE THREAD

**Issue by Kelvin-Wu** [cagnulein/qdomyos-zwift#2625]
Kinomap only work on inclination greater than 0. It does nothing when the value is less than 0.
For example:
The route inclination is 0 -> 5 -> -2 -> -10 -> 2 , but the actually appears is 0 -> 5 -> 5 -> 5 -> 2

[debug-Sun_Sep_29_01_00_02_2024.log](https://github.com/user-attachments/files/17175698/debug-Sun_Sep_29_01_00_02_2024.log)

**Comment by cagnulein** [comment]
I guess I found the issue!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11085924041


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by Kelvin-Wu** [comment]
Hi there, 
Thank you for your quick reply.
This version does not solve the problem.

[debug-Sun_Sep_29_10_57_20_2024.log](https://github.com/user-attachments/files/17177398/debug-Sun_Sep_29_10_57_20_2024.log)
[debug-Sun_Sep_29_11_01_52_2024.log](https://github.com/user-attachments/files/17177399/debug-Sun_Sep_29_11_01_52_2024.log)

**Comment by cagnulein** [comment]
Hi I checked the log and Kinomap is not sending any negative inclination.
Can you please put me in CC in the communication with them so I can share
the log and explain what's the issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 29 set 2024 alle 05:13 Kelvin-Wu ***@***.***>
ha scritto:

**Comment by Kelvin-Wu** [comment]
Hi Roberto,
I've added you in the mail loop. Thanks for your help.

**Comment by cagnulein** [comment]
No problem!


Il giorno dom 29 set 2024 alle 07:40 Kelvin-Wu ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Kelvin-Wu based on the kinomap answer (they are using resistance instead of inclinations!!) i did a patch
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11107952180

can you try it?

**Comment by Kelvin-Wu** [comment]
@cagnulein Thanks for your help. It is not resolve, still the same.
Attached is the log, and also attach the screenshot in nRF Connect app.

[debug-Mon_Sep_30_22_50_33_2024.log](https://github.com/user-attachments/files/17192051/debug-Mon_Sep_30_22_50_33_2024.log)
![Screenshot (2024年9月30日 下午10_36_58)](https://github.com/user-attachments/assets/912d47d7-aa05-4da3-8301-fec6814b8a80)

**Comment by cagnulein** [comment]
yes it's still don't sending negative inclinations. you should check what nrfconnect see from the qz interface not for the treadmill one, and then sending them that too (first show me it here)

let me know

**Comment by Kelvin-Wu** [comment]
Hi Here is the screenshot from connect to QZ.
![Screenshot_20240930-232646](https://github.com/user-attachments/assets/245ccd25-39b9-42f1-8926-d57d0310aaef)

**Comment by cagnulein** [comment]
ok i replied to kinomap now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 30 set 2024 alle ore 17:45 Kelvin-Wu ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Kelvin-Wu I don't remember : are we OK with this?

**Comment by Kelvin-Wu** [comment]
@cagnulein No, they didn't answer your latest question on Kinomap support web site.
Your latest question: "This is what QZ shows to kinomap. Are you using the supported resistance instead of the supported inclination?"

**Comment by cagnulein** [comment]
Could you try to ping them again on the same thread? It's unbelievable that they are not replying back!
