### ISSUE TITLE
[REQ] proform endurance 720E

### ISSUE THREAD

**Issue by ali-w** [cagnulein/qdomyos-zwift#2626]
**Is your feature request related to a problem? Please describe.**
Request to improve support for Pro-Form endurance 720e elliptical.  
Currently it connects to QZ and displays some status but QZ can't seem to control resistance or incline. Some status is missing from tiles too - more details to be attached.
Device is ifit compatible over BLE.

**Describe the solution you'd like**
QZ able to control resistance and incline on device, metrics updating in app panels (details of missing metrics to follow).

**Comment by cagnulein** [comment]
hi are you on android? could you please follow this with the ifit app https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

**Comment by ali-w** [comment]
Thanks for fast response - have data gathered, then realised it was kids bedtime!  
But yes, android 🙂

**Comment by cagnulein** [comment]
Perfect ! upload them and i will check it asap!

**Comment by ali-w** [comment]
[btsnoop_hci.log](https://github.com/user-attachments/files/17176644/btsnoop_hci.log)
see attached,  paired with ifit - span the pedals a bit, ran a manual session and set incline (2) and resistance (5) from the app; reset them on the device console (incline 0 / res 2); then set incline and resistance from the app again before ending the session.

FI - found the log in a slightly different location in the dump: FS\data\misc\bluetooth\logs
shout if you need more info from nRF Connect etc...

thanks loads :)

**Comment by cagnulein** [comment]
Awesome, thanks!
I will check it ASAP

Il giorno sab 28 set 2024 alle 23:26 Al ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
which is the max incline and resistance of this trainer? also i need to change ALL the resistance and the inclination levels from the app, starting from value 1 to the max, same for resistance and trainer.
Thanks

**Comment by ali-w** [comment]
hey - incline and resistance go up to 10 - i'll get the hcilogs when I'm next on it - by end of week.  thanks for your help

**Comment by cagnulein** [comment]
Sounds good!


Il giorno mer 2 ott 2024 alle 23:22 Al ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@ali-w Are you still interested?

**Comment by ali-w** [comment]
Yes, sorry I've been away - just home today and will upload logs.

**Comment by cagnulein** [comment]
@ali-w Any news?
