### ISSUE TITLE
[REQ] Resistance Automation?

### ISSUE THREAD

**Issue by TheCase** [cagnulein/qdomyos-zwift#2629]
**Is your feature request related to a problem? Please describe.**
I was wondering if it is possible to wire in or add (via ESP32 or similar) an automated resistance feature for bikes with manual resistance

**Describe the solution you'd like**
I would envision a stepper motor (with controller) replacing the manual knob, perhaps with a disconnect feature that would all manual adjustment when disengaged.  It would have to be calibrated (steps/mm) to adjust the resistance mechanically, as I'm sure each machine's range (and turns from min/max) is different.  I don't have a problem designing/building such a solution, I just don't know how or if the signal logic could be tied into the existing bike electronics (if the same board might possibly be used for both manual and automatic bikes) or if it would be possible to pair a standalone hardware solution (microcontroller + stepper control) into the `qdomyos-zwift` software

Let's brainstorm on it!

**Comment by cagnulein** [comment]
hi @TheCase did you check the https://github.com/doudar/SmartSpin2k/ ? @doudar

**Comment by TheCase** [comment]
I had not!  This is perfect!  Thank you for the pointer.
