### ISSUE TITLE
Speed Adjustment Issue on FS 465D50 Walking Pad

### ISSUE THREAD

**Issue by travsosborne** [cagnulein/qdomyos-zwift#2630]
Description: I am experiencing an issue with my FS 465D50 Walking Pad. When I manually adjust the speed using the + buttons, the speed changes for approximately 3 seconds before reverting back to 1 km/h. This issue also occurs when using the preset speed buttons. However, when I manually adjust the speed directly on the walking pad, the speed adjustment is reflected correctly in the QZ app.

Steps to Reproduce:

Connect the FS 465D50 Walking Pad to the QZ app on an iPad Air 3rd Gen.
Open the QZ app (Version 2.16.70).
Manually adjust the speed using the + buttons on the walking pad.
Observe the speed change for approximately 3 seconds before it reverts to 1 km/h.
Repeat the process using the preset speed buttons.
Expected Behavior: The speed should remain at the manually adjusted value and not revert to 1 km/h.

Actual Behavior: The speed reverts to 1 km/h after approximately 3 seconds of adjustment using the + buttons or preset speed buttons.

Sorry if I've gone into too much information, i do work with developers all day and know what they expect for Bug reports 
Device Information:

Walking Pad Model: FS 465D50
QZ App Version: 2.16.70
Device: iPad Air 3rd Gen
Additional Information:

When manually adjusting the speed directly on the walking pad, the speed adjustment is correctly reflected in the QZ app.
Attachments:

Debug log (attached)
[debug-Thu_Oct_3_16_47_23_2024.log](https://github.com/user-attachments/files/17240471/debug-Thu_Oct_3_16_47_23_2024.log)

**Comment by cagnulein** [comment]
hi @travsosborne i checked the log but the speed was always 0 and i don't see any events on qz to change the speed. Can you create debug log showing the issue?

**Comment by travsosborne** [comment]
[debug-Thu_Oct_3_17_10_01_2024.log](https://github.com/user-attachments/files/17240614/debug-Thu_Oct_3_17_10_01_2024.log)
 take two 
I ran manually adjust and with presents

**Comment by cagnulein** [comment]
i did a quick patch @travsosborne 

Do you have by chance a android device? if so you can test it right now, otherwise i have to create a new ios build. Let me know

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11157639734

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by travsosborne** [comment]
Robert we run in an Apple Household I don't have any android devices for testing sorry

**Comment by cagnulein** [comment]
ok i will build a test one. 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by travsosborne** [comment]
email send i am also on testflight if that helps

**Comment by travsosborne** [comment]
I have tested it and it changes from desired speed back to one km repeatedly 

i have attached a cloud link for video of what is happening 
https://share.icloud.com/photos/07eWLk5V5GUxvFYHe0HPKRYkQ

**Comment by cagnulein** [comment]
few things:
- press start on qz, you are in pause mode. i don't think it's the issue anyway
- share me a debug log with this version
- do you have an app that can control the speed without this issue?

**Comment by travsosborne** [comment]
[debug-Thu_Oct_3_18_15_33_2024.log](https://github.com/user-attachments/files/17241318/debug-Thu_Oct_3_18_15_33_2024.log)

I have just tested on the FS app for my device and was able to adjust speed no issues with buttons

**Comment by travsosborne** [comment]
sorry start button didn't change anything

**Comment by cagnulein** [comment]
i saw that you set the treadmill in the ftms treadmill setting. Did you try without it? setting it to disabled i mean. I guess the FS app it's not using the FTMS protocol, that's why. Let me know

**Comment by travsosborne** [comment]
thats worked up to 3km per hour and would go past that, is there a speed restriction that im missing

**Comment by cagnulein** [comment]
in the FS app can you go faster than 3km?

**Comment by travsosborne** [comment]
It keeps FTMS Enabled after restart and turns back on

**Comment by cagnulein** [comment]
set disabled and then press ok, if you don't press ok it doesn't set it

**Comment by travsosborne** [comment]
couple of other issue since patch is when stop button is pressed and it stops app and send email but doesn't stop treadmill  
and it does work when I turn off FTMS but when app is restarted it auto applies it see attached screenshot and stops working 
![Uploading unnamed.jpg…]()

**Comment by cagnulein** [comment]
i can't see the image, wait the finish of the upload

**Comment by travsosborne** [comment]
![unnamed](https://github.com/user-attachments/assets/5b7851ca-fcb8-438b-a2d4-c9537a785aa1)

**Comment by cagnulein** [comment]
hah ok got the issue, let me check

**Comment by cagnulein** [comment]
sent a new one. disable again the ftms treadmill, this time will stay there
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 3 ott 2024 alle ore 12:09 travsosborne <
***@***.***> ha scritto:

**Comment by travsosborne** [comment]
that worked
I know in the previous release not the major issue when i pushed the stop in the QZ app it would stop the treadmill 
I doesn't seem to do that, is that to do with FTMS turned off

**Comment by cagnulein** [comment]
that's perfect! so we can close this?

**Comment by travsosborne** [comment]
Thanks for your help  i bought a coffee

**Comment by cagnulein** [comment]
thanks!
