### ISSUE TITLE
[BUG] ifit integration issue: always starts manual ride after connected to I_EL and resistance is not synced

### ISSUE THREAD

**Issue by ann-one** [cagnulein/qdomyos-zwift#2633]
**Describe the bug**
ifit integration with qz on Android phone and ifit on iphone. ifit always launches a manual ride as soon as it connects to I_EL virtual device even before hitting start. Also the resistance shown on ifit isn't synced with qz, resistance adds and subtracts to the current starting resistance on bike. For example, if qz is started with resistance 3 ifit will add resistance based on that starting number so that when ifit shows 5, the bike will increment to resistance 8.

**To Reproduce**
qz on Android, ifit on iphone with ifit integration
launch qz and connect to bike without hitting start
launch ifit on iphone, connect to Android I_EL device
ifit immediately starts manual ride, and adding any resistance in ifit will add to the current actual starting resistance of bike

**Expected behavior**
ifit should not automatically start a manual bike ride, or should at least wait until hitting start in qz
ifit should sync the resistance with qz rather than adding additional resistance

**Smartphone (please complete the following information):**
Samsung S24 Ultra latest os with qz
iphone SE2 latest os with ifit

**Comment by ann-one** [comment]
That worked! Thanks. What about the ifit integration issue?

**Comment by cagnulein** [comment]
That's not easy to fix because the ifit protocol is a nightmare , i will
check if i can do something

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 5 ott 2024 alle 08:48 Ann ***@***.***> ha
scritto:
