### ISSUE TITLE
[BUG] Pro-Form TDF model PFEX01312.0 doesn't connect

### ISSUE THREAD

**Issue by aaronrryan** [cagnulein/qdomyos-zwift#2637]
**Describe the bug**
I tried all the different Pro-Form bikes in the QZ app settings and it doesn't connect

**To Reproduce**
1. go to settings
2. click on "Bike Options"
3. Click on Proform/Norditrack Options"
4. turn on "ProForm TDF 1.0"
5. add IP to "TDF4 IP:" field
6. restart app and it tries to connect but nothing shows in tiles

**Expected behavior**
I would expect the data would start showing, but it does not.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro 
 - OS: 14.6.1
 - Version 2.15.4

[debug-Sun_Oct_6_16_33_43_2024.log](https://github.com/user-attachments/files/17271280/debug-Sun_Oct_6_16_33_43_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
I assume that maybe this version of the QZ doesnt support Pro-Form TDF PFEX01312.0 

I was able to telnet to the port 4348, so I know that the data can be collected.

$ netcat 192.168.1.206 4348
### EBPF01311, version 2.0.30.
+SOP
         User Number: 100
           User Name: Guest
       Program State: Unknown  (06)
             Workout: MANUAL
          Session ID:
            Calories: 0.5
            Distance: 0.072
      Elevation Gain: 0
       Vertical Feet: 0
             Incline: 0.0
               Pulse: 0
        Workout Time: 00:27
               Speed: 0.0
               Watts: 0
+EOP

**Comment by aaronrryan** [comment]
https://github.com/cagnulein/qdomyos-zwift/issues/1825 This looks like the same bike version.  I'm able to telnet to the ip and run the ./utconfig command

**Comment by cagnulein** [comment]
@aaronrryan Hi! 2 things : the ip must be set ONLY on the tdf1 ip, remove the ip from the other fields.

also you need the beta , 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by aaronrryan** [comment]
Got the Beta installed and it is working. Very cool!

**Comment by cagnulein** [comment]
amazing! please remember to rate the app on the store! It means a lot to me!
Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 7 ott 2024 alle 07:36 Aaron Ryan ***@***.***>
ha scritto:
