### ISSUE TITLE
Connection Issue with QZ app and Zwift on Xterra TRX4500

### ISSUE THREAD

**Issue by twarty** [cagnulein/qdomyos-zwift#2638]
**Describe the bug**
QZ app and Zwift app not connecting on Xterra TRX4500 treadmill. All 3 were working on QZ 2.16 (874). After update zwift 2.17 (883), I can see Zwift is not communicating with QZ because on Zwift top left it shows communicate failure. When I just use the Zwift app and no QZ there is no communication failure. 

**To Reproduce**
1. Start QZ app
2. Start Zwift Running
3. Zwift Top Left Screen
4. Shows error Communication Failure

**Expected behavior**

**Screenshots**
![IMG_1571](https://github.com/user-attachments/assets/e3e35c36-b843-4f91-b6df-d9fcfc01b6c3)     Using QZ and Zwift App
![IMG_1572](https://github.com/user-attachments/assets/daada291-91a8-4590-afb9-5fcc0bc60734)     Communication Failure top left

![IMG_1573](https://github.com/user-attachments/assets/a9d5d186-f7f7-4c56-8ef2-c7d297b70026)    Using Zwift app only
![IMG_1574](https://github.com/user-attachments/assets/3256516e-de13-46a8-82b0-918f74978982)   Xterra Trx4500

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - iOS Version: 17.6.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
i don't see any log. please upload them

**Comment by twarty** [comment]
[debug-Tue_Oct_8_06_13_03_2024.log](https://github.com/user-attachments/files/17292471/debug-Tue_Oct_8_06_13_03_2024.log)

I hope I did correct.

**Comment by cagnulein** [comment]
@twarty i checked this log: QZ is sending correctly the metrics but zwift doesn't answer. Where Zwift is running? It seems that there is a network issue. Are both on the same wifi?

**Comment by twarty** [comment]
I am using the QZ app and Zwift app on the same iPhone. I tried it on a different iPhone and got the same issue. Also, the screen shots image 1571 and 1572 are from the iPhone using both apps at the same time.  As you see image 1571,  Zwift is showing Wahoo equipment while using both apps. Screenshots image 1573 and 1574 is the iPhone using the Zwift app only-no QZ. As you see from screenshot image 1573, Zwift sees the equipment as TRX4500 which is the actual treadmill I am using. I have a Xterra TRX4500.
    Get Outlook for iOS
  

 From: Roberto Viola ***@***.***>Sent: Tuesday, October 8, 2024 6:55 AMTo: cagnulein/qdomyos-zwift ***@***.***>Cc: twarty ***@***.***>; Mention ***@***.***>Subject: Re: [cagnulein/qdomyos-zwift] Connection Issue with QZ app and Zwift on Xterra TRX4500 (Issue #2638) 
@twarty i checked this log: QZ is sending correctly the metrics but zwift doesn't answer. Where Zwift is running? It seems that there is a network issue. Are both on the same wifi?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
Get Outlook for iOS

**Comment by cagnulein** [comment]
you can't use qz and zwift on the same iphone. you have to use zwift on a
phone or a tablet and qz on another.
then be sure they are using the same wifi network

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 15:44 twarty ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
yes but you will see the iphone name with qz on zwift, not your treadmill because qz is doing the bridge

let me know

**Comment by cagnulein** [comment]
hi @twarty I checked the log and the issue is that the treadmill disconnects from the phone directly. What if you swap the iphones? the one that you are using with zwift, use for qz and viceversa?

**Comment by twarty** [comment]
I have a question. Can QZ app use Bluetooth? I see the icon on the QZ app. And the Zwift app on setup the connection, Zwift app has a option to use Bluetooth thru a laptop. Is it better to use QZ on a iPhone and Zwift on a laptop?

**Comment by cagnulein** [comment]
qz already uses bluetooth to connect to your trainer and send metrics to zwift :) 
the issue here is the bluetooth of the treadmill disconnects from the phone. that's why i suggest to swap them . this is the first thing to try.

**Comment by twarty** [comment]
I having issues with the 2 iPhones when using the QZ and Zwift apps. On the Zwift app when choosing Pair Device, it shows the iPhone's name not QZ. I tried it on the other iPhone and get the same thing. I bet you have seen this, please help.

**Comment by cagnulein** [comment]
It's Ok if you see the iPhone name, did you try it?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 12 ott 2024 alle 15:10 twarty ***@***.***> ha
scritto:

**Comment by twarty** [comment]
After 3-6 minutes, it looks like QZ is disconnecting from the treadmill. I switch apps on the 2 iPhones and still getting the same issue. I see the bluetooth icon on the QZ app. I moved the iPhone on the treadmill until I got 3 bars and the same issue. Another thing, a  popup asking to pair the iPhones. I cancel it and no difference. Then, next time the pairing popup came up- I accept it and same issue.  Any ideas?
I have another question. Could I get QZ version qdomyos-zwift 2.16 (874) ? The reason I asking for that version is because when the iPhone was using that version, I did several workouts with auto inclination and it worked. And the workouts were over 30 minutes long. When I updated to 879, I started having issues. This may sound crazy but I was able to run QZ and Zwift apps together at the same time when doing a workout. That workout worked without issues. I wanted to see if 874 will fix my issues

**Comment by cagnulein** [comment]
You can rollback to that version on the testflight app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 12 ott 2024 alle 16:43 twarty ***@***.***> ha
scritto:

**Comment by twarty** [comment]
[debug-Mon_Oct_14_10_45_14_2024.log](https://github.com/user-attachments/files/17368459/debug-Mon_Oct_14_10_45_14_2024.log)

I ran this log during a workout this morning. I did not quit and restart QZ and Zwift app during this workout. QZ stopped the workout 3 times in this log. During those stoppages, I stopped and changed running speed in this workout with QZ. Then started the workout with QZ, auto incline worked just fine on the 3 starts. On the last stoppage, the running was going but I no control over the  speed.  The auto incline in Zwift was working correctly, that was weird. I hope this helps.

**Comment by cagnulein** [comment]
But did you try to revert back to the one that you told me that worked on
 testflight?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 14 ott 2024 alle 21:31 twarty ***@***.***> ha
scritto:

**Comment by twarty** [comment]
I could not find the version I asked about. TestFlight only shows version 2.17 (883). I wanted to try version 2.16 (874). Do know another location I could look?

**Comment by cagnulein** [comment]
Follow this and select the version that you need and let me know https://github.com/user-attachments/assets/9ba1bb08-760f-4ace-81e5-5681a58838f9

**Comment by twarty** [comment]
First, I wanted to say thank you for the time you have put into this issue. 

I was able to see the previous QZ versions on 1 of the 3 iPhones using the
video you sent me. I used that iPhone with the QZ older version and the
treadmill still stops around 13 minutes. But, then I can start the treadmill
back up. I going to say I can work with this issue. The auto inclination
works. I thought it's weird that I can see the pervious QZ versions on one
iPhone. All 3 iPhones are at the same software version. I tried sharing that
QZ version but the share icon wasn't there. Thanks again with your help.

**Comment by cagnulein** [comment]
I can try to restart the connection automatically. What did you do when you
lost connection? Did you just close qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 19:57 twarty ***@***.***> ha
scritto:

**Comment by twarty** [comment]
No, I hit the Stop button. I wait for the treadmill totally stop, then I hit the Pause/Start button and the treadmill starts up where it stopped. I never quit the QZ and Zwift apps. I run the treadmill until all stops again.

Also, when I first start using the QZ app, it shows TRX4500 on the main display. When the treadmill display changes from BLU to Manual QZ stops, TRX4500 changes to Run on the QZ display thru the iPhone. I don’t try to restart the QZ app get the TRX4500 on QZ display. The treadmill, QZ and Zwift all work together. I hope that wasn’t too confusing, Whew, I feel like I am confusing.

**Comment by cagnulein** [comment]
Hah Ok just a start that's interesting. I will check the log about this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 22:17 twarty ***@***.***> ha
scritto:
