### ISSUE TITLE
[BUG] Connectivity problem between Zwift on iPad and Ascend S2 bike connected on iPhone

### ISSUE THREAD

**Issue by cotantoine** [cagnulein/qdomyos-zwift#2639]
**Describe the bug**
I'm connecting my bike on my iPhone trought the Test QZ app. 
I'm connecting Zwift on iPad to my iPhone
When I start a route and start pedaling, nothing is happening neither on the bike or both app. 
No metrics. 

**Desktop (please complete the following information):**
- Device: IPad Pro
- Model: 5th generation
- Version: 17.6.1

**Smartphone (please complete the following information):**
 - Device: iPhone
 - Model: 13
 - Version: 17.6.1

**Append a debug log**
[debug-Tue_Oct_8_11_36_41_2024.log](https://github.com/user-attachments/files/17295929/debug-Tue_Oct_8_11_36_41_2024.log)

**Comment by cagnulein** [comment]
@cotantoine log checked : the bike is not talking indeed. that's so strange. do you have any other apps that are working with the bike? like kinomap
for example?

**Comment by cotantoine** [comment]
I'm running Zwift directly from my iPad with the bike in Bluetooth and it's working great. 
I was just looking to have an option to adjust the base resistance so I landed on your app. 
So, I know the bike can talk to apps, but not yet with the QZ app.

**Comment by cagnulein** [comment]
ok so i will check the log tomorrow, i guess the bike is needing something
from qz

i will let you know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 20:01 cotantoine ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@cotantoine i guess i understood the issue

enable this

![image](https://github.com/user-attachments/assets/ec117aa6-269d-4976-bc08-fb69026b0fb2)

and restart qz

let me know

**Comment by cagnulein** [comment]
@cotantoine Did it work?
