### ISSUE TITLE
Master T40 treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2640]

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11257332818

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by OnkelKoks** [comment]
[debug-Wed_Oct_9_21_48_23_2024.log](https://github.com/user-attachments/files/17317927/debug-Wed_Oct_9_21_48_23_2024.log)
Didn't work with your modifications. I got into the control panels now but nothing happened with the treadmill no matter my button presses and the panels didn't report anything happening when I started the treadmill manually. FYI I also wore my Garmin HRM-PRO plus but it didn't register my heart beats either.

**Comment by cagnulein** [comment]
thanks, it was a random test to see if i can make it work without having a hci snoof. i will check the log tomorrow, maybe i can get useful information anyway.

i still suggest to find a way to collect a hci snoof from an app somehow or to contact the manufacturer about this

let me know!

**Comment by OnkelKoks** [comment]
I've tested every version of the apk I can find of the only app that is supposed to work, Run on Earth, but they all crash 🙁. I have found another app that might work which controls the treadmill and I've just requested a trial version to see if it works with my device.

________________________________
Från: Roberto Viola ***@***.***>
Skickat: den 9 oktober 2024 21:58
Till: cagnulein/qdomyos-zwift ***@***.***>
Kopia: OnkelKoks ***@***.***>; Comment ***@***.***>
Ämne: Re: [cagnulein/qdomyos-zwift] Master T40 treadmill (Issue #2640)


thanks, it was a random test to see if i can make it work without having a hci snoof. i will check the log tomorrow, maybe i can get useful information anyway.

i still suggest to find a way to collect a hci snoof from an app somehow or to contact the manufacturer about this

let me know!

**Comment by cagnulein** [comment]
Which is the name of this app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 9 ott 2024 alle 22:28 OnkelKoks ***@***.***> ha
scritto:

**Comment by OnkelKoks** [comment]
Run on Earth

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
Hah Ok let me know!
Today I will check your log!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 07:08 OnkelKoks ***@***.***>
ha scritto:

**Comment by OnkelKoks** [comment]
Sorry too early in the morning 😂. Original app that was bundled with the treadmill is called Run on Earth. New app I found that I've requested trial of is this:

https://play.google.com/store/apps/details?id=xyz.rfit.fitness.workout.pafers.pro

another app I've found and asked of trial is this:

http://ergo.ub-online.de/index.php/en/download

I have gotten a trial of the bottom app but it crashes as soon as I start it. I will try on an older phone today.

________________________________
Från: Roberto Viola ***@***.***>
Skickat: torsdag, oktober 10, 2024 7:10:23 AM
Till: cagnulein/qdomyos-zwift ***@***.***>
Kopia: OnkelKoks ***@***.***>; Comment ***@***.***>
Ämne: Re: [cagnulein/qdomyos-zwift] Master T40 treadmill (Issue #2640)


Hah Ok let me know!
Today I will check your log!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 07:08 OnkelKoks ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Eheheh ok

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 07:26 OnkelKoks ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
I was checking the log and it was working, the first time it tooks more than a minute to fully connect to these device.
So please try again and leave QZ running for at least 2-3 minutes. Then send me a debug log so i can check if we made progresses
Let me know!

**Comment by OnkelKoks** [comment]
[debug-Thu_Oct_31_12_24_58_2024.log](https://github.com/user-attachments/files/17587092/debug-Thu_Oct_31_12_24_58_2024.log)

Very sorry for the delay, I've been away from home. Here is a log of the app being connected to the treadmill for a few minutes while it was running and I was playing around with the incline and speed settings.

Sometimes the app crashes randomly after about one minute after connecting to the treadmill. I will upload a log right after this one when it crashed if that can help you out somehow.

**Comment by OnkelKoks** [comment]
[debug-Thu_Oct_31_12_17_12_2024.log](https://github.com/user-attachments/files/17587120/debug-Thu_Oct_31_12_17_12_2024.log)
[debug-Thu_Oct_31_12_15_47_2024.log](https://github.com/user-attachments/files/17587121/debug-Thu_Oct_31_12_15_47_2024.log)

Both files are when the app crashed.

**Comment by OnkelKoks** [comment]
[btsnoop_hci.log](https://github.com/user-attachments/files/17587689/btsnoop_hci.log)
sorry, sent you the wrong file. This is the correct one in regards to my notes above.

**Comment by cagnulein** [comment]
thanks. could you please collect also a hci snoof using qz when it doesn't crash so i can compare them? thanks

**Comment by OnkelKoks** [comment]
Attached is both the hci snoof when running qz and its own log from the same instance. In case you are able to see what I did to the treadmill I did in this order:
Start treadmill
Maximum incline (15)
Lowest incline
Maximum speed (22)
Slowest speed
Stop
[btsnooz_hci.log](https://github.com/user-attachments/files/17588180/btsnooz_hci.log)
[debug-Thu_Oct_31_14_05_49_2024.log](https://github.com/user-attachments/files/17588184/debug-Thu_Oct_31_14_05_49_2024.log)

**Comment by cagnulein** [comment]
hi @OnkelKoks both files seem unavailable. could you please upload them again?

**Comment by OnkelKoks** [comment]
[debug-Thu_Oct_31_14_05_49_2024.log](https://github.com/user-attachments/files/17588294/debug-Thu_Oct_31_14_05_49_2024.log)
[btsnooz_hci.log.txt](https://github.com/user-attachments/files/17588307/btsnooz_hci.log.txt)
lets try again

**Comment by OnkelKoks** [comment]
[debug-Thu_Oct_31_14_05_49_2024.log](https://github.com/user-attachments/files/17588320/debug-Thu_Oct_31_14_05_49_2024.log)
and again....

**Comment by cagnulein** [comment]
ok it worked now, thanks. let me check

**Comment by cagnulein** [comment]
[btsnooz_hci.log.txt](https://github.com/user-attachments/files/17588307/btsnooz_hci.log.txt) this is downloadable but it doesn't have the right format. could you please check?

**Comment by OnkelKoks** [comment]
[btsnooz_hci.log](https://github.com/user-attachments/files/17588400/btsnooz_hci.log)

I think outlook messed the file up. How about this?

**Comment by cagnulein** [comment]
i don't know what happen with this file but i can't open it. i can open the one that you sent me earlier from the app that you purchased but not this. You can try to open them with wireshark before sending me them. Maybe they are corrupted because are not compressed on a zip file? never had this issue before

let me know

**Comment by OnkelKoks** [comment]
I'll try from another phone later on. I have no clue why it's not working 🤔
________________________________
Från: Roberto Viola ***@***.***>
Skickat: den 31 oktober 2024 14:45
Till: cagnulein/qdomyos-zwift ***@***.***>
Kopia: OnkelKoks ***@***.***>; Mention ***@***.***>
Ämne: Re: [cagnulein/qdomyos-zwift] Master T40 treadmill (Issue #2640)


i don't know what happen with this file but i can't open it. i can open the one that you sent me earlier from the app that you purchased but not this. You can try to open them with wireshark before sending me them. Maybe they are corrupted because are not compressed on a zip file? never had this issue before

let me know

**Comment by cagnulein** [comment]
ok let me know!

**Comment by OnkelKoks** [comment]
Okay, new day, new device. Unfortunately, QZ keeps on crashing on this device as well (Samsung S23). All logs have been pulled from ADB to be sure the email app doesn't interfere with the logs.

This BT log is from the other app that at least (sometimes) gets the treadmill started. It starts with one minute at 6km/h, then two minutes at 22km/h and an incline of 15 (but that doesn't work, nothing happens on the treadmill) then back for one minute at 1km/h.
[btsnoop_hci.log](https://github.com/user-attachments/files/17599460/btsnoop_hci.log)

**Comment by OnkelKoks** [comment]
And here is the BT + QZ logs of when I start the app until it keeps crashing x2. I start the treadmill manually on its own control panel and it runs for a minute or two before crashing. Nothing shows up in the app in the different tiles, they all show 0.
[debug-Fri_Nov_1_12_59_19_2024.log](https://github.com/user-attachments/files/17599478/debug-Fri_Nov_1_12_59_19_2024.log)
[debug-Fri_Nov_1_12_58_40_2024.log](https://github.com/user-attachments/files/17599479/debug-Fri_Nov_1_12_58_40_2024.log)
[btsnoop_hci.log](https://github.com/user-attachments/files/17599480/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Ok perfect, I will check it out, it's bank holiday today in Italy

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 13:14 OnkelKoks ***@***.***> ha
scritto:

**Comment by OnkelKoks** [comment]
Update:
I installed the other app and also your app on another tablet, an old crappy Lenovo.
The other app will not adapt to the 7" screen of the tablet so I can't press on the accept button on its disclaimer... 😒.
However, your app doesn't crash and also something new happens. After a few minutes of doing nothing a BT icon shows up on the treadmill. If I press pause and then start in your app it takes maybe 10 seconds and the treadmill starts for just two seconds before stopping again. So apparently it can connect, somehow. Strange that it doesn't work on my other two Samsung devices, however.
Unfortunately, even though I've activated BT snoop in the developer menu and restarted the device, it doesn't log anything in regards to Bluetooth in its logfiles. I've also tested dialing *#800# but nothing happens. Attached logfile from QZ.
[debug-Fri_Nov_1_14_01_14_2024.log](https://github.com/user-attachments/files/17599947/debug-Fri_Nov_1_14_01_14_2024.log)

**Comment by OnkelKoks** [comment]
Same in Sweden, enjoy your day off and the weekend.

**Comment by cagnulein** [comment]
hi @OnkelKoks can you try to use this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/11667383508

**Comment by cagnulein** [comment]
perfect! the treadmill now is talking! which speed the treadmill was at
when you took the log?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle ore 14:18 OnkelKoks ***@***.***>
ha scritto:

**Comment by OnkelKoks** [comment]
I can't say for sure as the display in the treadmill turns off when it connects to bluetooth and it's only running for two seconds, but it sure seems to be running at the slowest setting (1 km/h).

**Comment by cagnulein** [comment]
ok are you able to change it from the treadmill directly? because I can see
a 1.0 value, i would like to see if it changes accordingly to what you do
on the treadmill itself.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle ore 14:27 OnkelKoks ***@***.***>
ha scritto:

**Comment by OnkelKoks** [comment]
Unfortunately not, once the treadmill connects to the software a Bluetooth icon appears in its display and all buttons become inoperapable. Not even the stop button function.

**Comment by cagnulein** [comment]
did you try to use the plus speed button on the speed tile to check if
something is changed?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle ore 14:34 OnkelKoks ***@***.***>
ha scritto:

**Comment by OnkelKoks** [comment]
I did not, but just tested it. The speed tile doesn't show anything, it just stays at 0, however, holding the + button makes the treadmill go up to somewhere around maybe 5km/h. If I press plus multiple times it goes up to some random (slow) speed and then suddenly it goes back to 0 again.
[debug-Wed_Nov_6_15_56_28_2024.log](https://github.com/user-attachments/files/17648947/debug-Wed_Nov_6_15_56_28_2024.log)
Log attached

**Comment by cagnulein** [comment]
@OnkelKoks great, can you try this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/11706734148

**Comment by OnkelKoks** [comment]
Lenovo doesn't crash. Tiles (except incline) show numbers when it starts and when I press the speed buttons. However it just starts, goes for 30-40 cm and then stopps working. Doesn't matter what I press. QZ seems to believe it's still going though as the tiles still show numbers.
[debug-Wed_Nov_6_17_48_00_2024.log](https://github.com/user-attachments/files/17650469/debug-Wed_Nov_6_17_48_00_2024.log)

**Comment by cagnulein** [comment]
I thought the previous version would command the treadmill correctly even
if it's showing 0, wasn't the case?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 17:56 OnkelKoks ***@***.***> ha
scritto:

**Comment by OnkelKoks** [comment]
yes. it could control the speed at least (up to roughly ~5km/h)

**Comment by cagnulein** [comment]
Ok so this version can too right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 18:00 OnkelKoks ***@***.***> ha
scritto:

**Comment by OnkelKoks** [comment]
No, it just starts and goes for 30-40cm and then stops on the Lenovo. No matter what I press, nothing more is happening. Only if I press pause twice it starts again and goes for 30-40 cm.
On the Samsung it crashes so I can't test it.

**Comment by cagnulein** [comment]
Ok so I will check it. Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 18:03 OnkelKoks ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
sorry wrong link https://github.com/cagnulein/qdomyos-zwift/actions/runs/11775443977

**Comment by OnkelKoks** [comment]
[debug-Sat_Nov_16_18_52_36_2024.log](https://github.com/user-attachments/files/17787488/debug-Sat_Nov_16_18_52_36_2024.log)
No worries, hope you are better!

Samsung = app crashes
Lenovo = it connects, the treadmill beeps at me like it's about to start and then nothing happens.

**Comment by OnkelKoks** [comment]
We're back to where it starts and goes for 30-40 cm and then stops.
[debug-Tue_Nov_19_11_34_14_2024.log](https://github.com/user-attachments/files/17813754/debug-Tue_Nov_19_11_34_14_2024.log)

**Comment by cagnulein** [comment]
ok so it means that it requires something else after the commands that i
added, i will check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 nov 2024 alle ore 11:38 OnkelKoks ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@OnkelKoks could I ask to genearte a hcisnoof running qz? i would like to compare with this https://github.com/cagnulein/qdomyos-zwift/issues/2640#issuecomment-2451776071
there is for sure some differences at the very beginning because the treadmill is answering in a different way but I can't understand why

Thanks
