### ISSUE TITLE
[BUG] Cannot change ifit bike resistance through qz app

### ISSUE THREAD

**Issue by AdamDanklefsen** [cagnulein/qdomyos-zwift#2641]
I have QZ companion installed on my S22i ifit bike, and have it connected to the qz app on my iphone. I am able to read cadence, watts, and resistance (Speed is zero but that is not a big deal to me). When I try to increment the resistance in app, my bike is not affected.

I am able to connect to zwift, except for the controls.
![image](https://github.com/user-attachments/assets/ef31ed74-8b08-49a4-975b-a9906d718e7b)

Please let me know if there are any other details you need and thank you for any help.

**Comment by cagnulein** [comment]
Please show me a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by AdamDanklefsen** [comment]
[0QZ-backup-Thu Oct 10 18_43_36 2024.txt](https://github.com/user-attachments/files/17335124/0QZ-backup-Thu.Oct.10.18_43_36.2024.txt)
Made txt to let me upload it.

Do you have a public tool for reading these?

**Comment by cagnulein** [comment]
Hi this is a fit file, I need a debug log one. It's the one starting with the prefix debug
Let me know

**Comment by cagnulein** [comment]
@AdamDanklefsen Any news?
