### ISSUE TITLE
[BUG] QZ disconnects from Zwift during activity

### ISSUE THREAD

**Issue by spacebeez** [cagnulein/qdomyos-zwift#2643]
**Describe the bug**
Using QZ with Horizon 7.4 AT Treadmill and Zwift.  After approximately 20-30 minutes QZ will disconnect from Zwift and stop the treadmill.  This behavior has happened both using QZ and Zwift on a single android device, and on separate devices.  Log below is from my two-device setup.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S24 (QZ Device)
 - OS: Android 14
 - QZ version 2.16.66

 - Device: Samsung Galaxy Tab S7 (Zwift Device)
 - OS: Android 13
 - QZ version 2.16.66

Same issue was present using Galaxy Tab S7 to run both QZ and Zwift, did not test S24 alone.

**Append a debug log**
  
[debug-Wed_Oct_9_16_38_15_2024.log](https://github.com/user-attachments/files/17331290/debug-Wed_Oct_9_16_38_15_2024.log)

-Note, I removed some of the middle and end of the log to reduce the file size to 25MB limit.

**Comment by cagnulein** [comment]
Does the treadmill have this problem even connected directly to zwift
without qz using the same devices?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 18:24 spacebeez ***@***.***>
ha scritto:

**Comment by spacebeez** [comment]
I have not tested connecting the treadmill directly to Zwift since I don't have an interest in Zwift without the auto-incline feature that QZ provides.  I will try this though at my next opportunity to see if I can replicate the issue that way.

**Comment by cagnulein** [comment]
my doubt  is that the treadmill or the phone as some issue on Bluetooth
So first of all, let's check this. Let me know.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 19:20 spacebeez ***@***.***>
ha scritto:

**Comment by spacebeez** [comment]
I have tried a couple sessions now with the treadmill paired directly to Zwift on the Galaxy Tab S7.  One around 35 minutes and one around 47 minutes.  Neither session had bluetooth issues and held a connection until I ended it.

**Comment by cagnulein** [comment]
That's great!

**Comment by spacebeez** [comment]
Well, perhaps I should have communicated more clearly.  The original problem is still present when using QZ, I have just confirmed that the problem is NOT present when I connect the Horizon 7.4 directly to Zwift on the same tablet, without QZ.

**Comment by cagnulein** [comment]
It could be a firmware issue about the Inclination, I already saw this on another treadmills 

Could you try to use qz without the auto inclination?

**Comment by spacebeez** [comment]
I tried running with Zwift auto-inclination disabled in the QZ app and it still disconnected around 23-ish minutes.

**Comment by cagnulein** [comment]
I will check again your log tomorrow if there is something else strange

**Comment by cagnulein** [comment]
@spacebeez i guess i found the issue. The issue is that QZ is using the custom horizon protocol to write the inclination, this protocol starts a manual workout on the horizon that could have a timeout after more or less 30 minutes.

You can try 2 things:
- enable the "Horizon 7.8 start issue" setting in the horizon treadmill settings. It should fix the timeout. Reference here https://github.com/cagnulein/qdomyos-zwift/issues/704
- you can enable instead the "Force Using FTMS" setting there, but in this way i guess you will lose the inclination writing (you can try). For sure, enabling this you will not have the 23 minutes issue. (it's how zwift talks with the treadmill)

Let me know!

**Comment by cagnulein** [comment]
@spacebeez Any news?

**Comment by spacebeez** [comment]
> @spacebeez Any news?

@cagnulein apologies for the delay, I wanted to test multiple times to confirm and then forgot to update.  Enabling "Horizon 7.8 Start Issue" appears to have completely solved the problem.  I have done multiple workouts with and without elevation control for 45+ minutes with no issues.  

It would appear this fix is valid for the Horizon 7.4 as well!  Thank you very much for your help.

**Comment by cagnulein** [comment]
That's great!
