### ISSUE TITLE
Proform trainer 12.0 shows random speed on startup

### ISSUE THREAD

**Issue by Lildebbyproducts** [cagnulein/qdomyos-zwift#2646]
On startup QZ it will show a random speed and pace, even with treadmill turned off. After about 10 seconds it returns to zero. If i try to control treadmill with this random speed active, QZ will show inaccurate speed/pace.  Oddly enough, Zwift displays correct speed regardless of what QZ is displaying.

**To Reproduce**
1. Start QZ app
2. Speed will show 2.X and a given pace will be shown
3. After a short time, speed/pace will read zero.

**Expected behavior**
On startup, with treadmill off/key removed, QZ should show speed as zero/NA

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23 Ultra
 - OS: Android
 - Version 14

  
[debug-Thu_Oct_10_13_50_17_2024.log](https://github.com/user-attachments/files/17334241/debug-Thu_Oct_10_13_50_17_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 10 ott 2024 alle 23:12 Lildebbyproducts <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
for reference is a Proform trainer 12.0

**Comment by cagnulein** [comment]
@Lildebbyproducts  i guess if you enable one of these profiles in the nordictrack treadmill settings you will solve this

```
nordictrack_t65s_treadmill || proform_pro_1000_treadmill || nordictrack_t65s_83_treadmill || nordictrack_s30_treadmill ||
          nordictrack_s20_treadmill || proform_treadmill_se || proform_cadence_lt || proform_8_5_treadmill || nordictrack_treadmill_exp_5i || proform_carbon_tl ||
          nordictrack_s20i_treadmill || proform_treadmill_8_7 || proform_carbon_tl_PFTL59720
```

let me know

**Comment by Lildebbyproducts** [comment]
I enabled the proform pro 1000 and the issue is gone! Thanks!
