### ISSUE TITLE
Tacx Neo 2 freewheel keeps spinning 

### ISSUE THREAD

**Issue by RobertoHerradura** [cagnulein/qdomyos-zwift#2650]
Hi Roberto,

I have 2 Wahoo Kickr's that work beautiful with Zwift & QZ for virtual shifting.
My Tacx Neo 2 however has a strange issue.
After closing down Zwift my Neo freewheel keeps spinning !
It stops spinning after closing QZ on my phone.

I've sent you a log before but you didn't find anything.
Here it is again because it's a concerning issue.

Thanks,

Roberto

[debug.zip](https://github.com/user-attachments/files/17355048/debug.zip)

EDIT : I see QZ in Zwift and when I connect my cadence it is always at ZERO.
In the the DEBUG file you will see 

1 cadence connect with QZ
2 cadence connect with Tacx Neo trainer
3 cadence connect with Garmin Vector Pedals

Number 1 = NO READINGS
Number 2 +3 work normally as it reads my sensors ( ANT+ or BT)

The Freewheel spinning AFTER closing Zwift but QZ still connected to number 1 or 2 keeps the freewheel spinning at high velocity without pedalling...
The freewheel stops AFTER closing QZ !

**Comment by MarkusZwift** [comment]
I also have a Tacx Neo 2 and I have the same issue. After my rides the free wheel keeps on spinning.

**Comment by cagnulein** [comment]
@MarkusZwift It's fixed in the 2.18.1 version. Which version do you have?

**Comment by MarkusZwift** [comment]
Roberto, it is the version I have.

**Comment by cagnulein** [comment]
@MarkusZwift Show me a debug log which the issue and I will check it 
Thanks
