### ISSUE TITLE
Proform 575i

### ISSUE THREAD

**Issue by Bairn31** [cagnulein/qdomyos-zwift#2652]
**Describe the bug**
Andriod app connects to treadmill and reports back correct speed/incline but cannot control speed/incline from app. 

**Smartphone (please complete the following information):**
 - Device: pixel 7
 - OS: android
 - Version 14

**Append a debug log**
[btsnoop_hci.log](https://github.com/user-attachments/files/17349880/btsnoop_hci.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Add any other

**Comment by cagnulein** [comment]
Thanks I will add it ASAP!

**Comment by Bairn31** [comment]
Hi, 
Thanks for the build. When I select the treadmill as 575i I got some odd data reported via the app, see attached image. 
![Screenshot_20241014-190605](https://github.com/user-attachments/assets/f6419751-adee-43b5-8f23-47bf7bd2c5a0)

I had a little play with some of the other treadmill settings (namely 595 and nordictrack t7) which are around the same spec and age of the 575i and  found they reported the correct speed and incline via QZ but I couldn't control the treadmill from QZ (should I be able to?).  I pulled a log from the app ( Speed: 0/2/10/20/10/2 : Incline: 0/5/10). 

[debug-Mon_Oct_14_20_42_53_2024.log](https://github.com/user-attachments/files/17369032/debug-Mon_Oct_14_20_42_53_2024.log)

**Comment by cagnulein** [comment]
hi @Bairn31 in this log i saw you selected the proform_proshox2, i need a log where you select the new 575i (the last one device at the bottom) restart qz.
Let me know!

**Comment by Bairn31** [comment]
[debug-Tue_Oct_15_18_05_18_2024.log](https://github.com/user-attachments/files/17382189/debug-Tue_Oct_15_18_05_18_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 19:10 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @Bairn31 i guess I solved the strange metrics issue, could you please try https://github.com/cagnulein/qdomyos-zwift/actions/runs/11360161298 ?
let me know!

**Comment by Bairn31** [comment]
hi @cagnulein, 
Tried the build, no strange metrics this time but no metrics at all..... 
[debug-Wed_Oct_16_18_21_01_2024.log](https://github.com/user-attachments/files/17400752/debug-Wed_Oct_16_18_21_01_2024.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out it means I forgot something. I will update you asal


Il giorno mer 16 ott 2024 alle 19:59 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Bairn31 i did another small patch here https://github.com/cagnulein/qdomyos-zwift/actions/runs/11380271820
but I suggest to reboot the treadmill because in the log you provided me it was acting strange. Let me know

**Comment by Bairn31** [comment]
Hi @cagnulein,  

I'm working at the moment but will try this later this evening.

Thanks for all your support with this, it's much appreciated.

**Comment by Bairn31** [comment]
[debug-Thu_Oct_17_18_19_36_2024.log](https://github.com/user-attachments/files/17418482/debug-Thu_Oct_17_18_19_36_2024.log)

Further log attached. Connects to treadmill but still no metrics reported. Displaying heart rate from watch fine, 

Treadmill was reset before collecting log.

**Comment by cagnulein** [comment]
Argh i will check it
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 ott 2024 alle 20:17 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Bairn31 could you please show me a debug log from qz with the 575i setting disabled reporting correct incline and speed? thanks

**Comment by Bairn31** [comment]
[debug-Fri_Oct_18_09_54_28_2024.log](https://github.com/user-attachments/files/17431612/debug-Fri_Oct_18_09_54_28_2024.log)

Hi Attached is log taken from clean install of the last build - didn't touch treadmill settings and it correctly reported speed and incline. 
Thanks

**Comment by cagnulein** [comment]
that's so strange, qz is sending the same frames at startup but with the 575i setting the treadmill it's answering differently. the only thing that changes is the fact that in the log with the 575i you have also your HR connected to QZ. can you try to disable as well there so i can have a comparable logs?

so 575i setting enabled with HR disabled

thanks

**Comment by Bairn31** [comment]
[debug-Fri_Oct_18_10_07_54_2024.log](https://github.com/user-attachments/files/17431804/debug-Fri_Oct_18_10_07_54_2024.log)

**Comment by cagnulein** [comment]
ok it seems a desync thing. let's try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/11437866185

**Comment by Bairn31** [comment]
Apologies - been away for a week.

Tried the latest build but still nothing reported back to the app. See
latest logs attached.

Appreciate your help- dont worry if you cannot get this to work I can use
the app without the control element. When I select another treadmill I can
interface with zwift.

**Comment by Bairn31** [comment]
[debug-Mon_Oct_28_16_05_46_2024.log](https://github.com/user-attachments/files/17545644/debug-Mon_Oct_28_16_05_46_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 28 ott 2024 alle 17:22 Bairn31 ***@***.***> ha
scritto:

**Comment by Bairn31** [comment]
Hi @cagnulein 

I had some time earlier and almost every treadmill I select in the proform/nordic track dropdown connects and reports back correct speed and incline but nothing with the 575i selected. No idea if this information is of any use.

**Comment by cagnulein** [comment]
Thanks that's very iseu, I plan to Check it again next week. Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 nov 2024 alle 17:02 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Bairn31 i guess I got the problem: my idea is the issue is inside the hci snoof that you originally sent me. It has some strange init packages that no one treadmill has. So just a question: did you collect it with the ifit app during a manual workout? are you able to collect it again just to be sure?
Let me know!

**Comment by Bairn31** [comment]
This is quite embarrassing. I can't for the life of me work out where that log file came from. Could it potentially have come from when I had my runn treadmill sensor connected rather than directly connected to treadmill? Sorry.

**Comment by cagnulein** [comment]
It seems from the treadmill for sure but it seems in another mode. Anyway no problem, let's try to get another one and I will compare it!

**Comment by cagnulein** [comment]
No problem, thanks! I will check it out!


Il giorno mer 6 nov 2024 alle 20:27 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
that's so strange @Bairn31 it's still so different from the others treadmill! I can implement this of course, I just would like to be sure that it's correct. was it a manual workout?

**Comment by Bairn31** [comment]
Hi @cagnulein,

It was a manual workout. I have some time tonight. I'll  have another play around and get some more data.

**Comment by cagnulein** [comment]
be sure also to change the inclination and speed from the ifit app too

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 nov 2024 alle 20:08 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/actions/runs/11776651125
let me know if it's better! @Bairn31

**Comment by Bairn31** [comment]
hi @cagnulein,

It seems like a step in the right direction.  

I get no reporting through the app (everything reported as 0) but using the +- buttons on the app (QZ) was registering with the treadmill. I could hear the audible beep I get with a button touch on the treadmill although the response was somewhat erratic. Speed jumped up and down  1kmph up to 5.5kmph then back to 1. The incline seems to change somewhat erratically as well. 
[debug-Mon_Nov_11_18_35_39_2024.log](https://github.com/user-attachments/files/17707137/debug-Mon_Nov_11_18_35_39_2024.log)

Attached the debug log from the QZ app. 
Thanks
Bairn

**Comment by cagnulein** [comment]
Thanks I guess it's all because we read 0 to the metrics. Tomorrow I will
check this
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 nov 2024 alle 19:48 Bairn31 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Bairn31 ok i guess i fixed the reading metrics, let me know https://github.com/cagnulein/qdomyos-zwift/actions/runs/11793653060

**Comment by Bairn31** [comment]
Superb. Works perfectly. Thanks for all your help!

Sorry, feel like I sent you down a rabbit hole with the wrong btsnoop file originally. 

👍 👏

**Comment by cagnulein** [comment]
That's great! No problem!
