### ISSUE TITLE
[REQ] Test project update

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#2653]
**Is your feature request related to a problem? Please describe.**

The test project:
- separation of Bluetooth config and settings config in test data inhibits specifying test data for conditions that refer to both, e.g has service or setting is true.
- Has at least 1 test data class for each bluetoothdevice class. These have to be defined and built, which perhaps discourages creating new ones and takes time to compile and link.
- the TestSettings class needs to be updated in multiple places when there is an additional setting used in testing device detection.

**Describe the solution you'd like**

- Merge the bluetooth configuration into the settings configuration. 
- Make the TestSettings class work off QZSettings keys to reduce maintenance
- Use builder objects (e.g. like ASP.NET Core) to construct test data objects for each bluetoothdevice class instead of having a class for each bluettoothdevice class.

**Comment by cagnulein** [comment]
thanks @drmason789 for your hard work! I will check it asap!

**Comment by drmason789** [comment]
> thanks @drmason789 for your hard work! I will check it asap!

For me it's not work, it's an interesting adventure.
