### ISSUE TITLE
Proform Tour De France in Mywhoosh

### ISSUE THREAD

**Issue by LDHig** [cagnulein/qdomyos-zwift#2656]
[Debug Log 10_13_2024.txt](https://github.com/user-attachments/files/17356055/Debug.Log.10_13_2024.txt)
Hello, I am trying to connect my TDF to MyWhoosh. I am finally about to connect my bike to your app but not MyWhoosh. My phone is showing up in the platform but will not connect. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 22] Windows 11 is my computer

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung 10+
 - Version [e.g. 22] Android Version 12

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
did you set the phone name to bike in the android settings and reboot it?
also mywhoosh is running on another device?
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 13 ott 2024 alle ore 16:58 LDHig ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@LDHig Any news?
