### ISSUE TITLE
[REQ] Use Volume buttons for manually changing speed

### ISSUE THREAD

**Issue by rafaelmartinsrm** [cagnulein/qdomyos-zwift#2657]
**Is your feature request related to a problem? Please describe.**
I am currently using QZ for running since my treadmill doesn't have Bluetooth feature. I also don't have a foot pod. I am currently running using QZ Companion application on my Garmin watch and I change speed and inclination on my treadmill manually. Although it's working great, changing speed using the UI buttons on tiles is hard when you are running, also because it has "delay", so you end up clicking more than once sometimes. My idea to solve this problem is using the volume buttons on the phone to change the speed up and down.

**Describe the solution you'd like**
Volume buttons should manually set the speed according the the "step" defined on settings.

**Describe alternatives you've considered**
Having huge buttons on UI to change speed would also work, although volume buttons seems perfect solution.

**Additional context**
None

**Comment by cagnulein** [comment]
done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/11326729403
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11326927837

in this i added also the inclination fix
let me know!

**Comment by rafaelmartinsrm** [comment]
@cagnulein - Thank you for the changes, I have tested the build version you mentioned on your last comment and it fully works for me.

A couple comments:
1. The settings option to enable this is "Advanced Options > Volume buttons change gears", maybe it should be renamed to mention speed in case of treadmill or at least the description?
2. Inclination on Zwift doesn't have fractions, but I have seen sometimes I see 1% on Zwift but it's 2% on App. I understand there's a "pooling time", but in this case I am mentioning, Zwift never shown more than 1% on that path. So is it Zwift rounding down when it shouldn't?
3. If you click the "Side Menu", volume buttons stop working (doesn't change speed) until you click on something. In my case, it worked again after I "Paused/Unpaused" or used "+/-" on speed.

**Comment by cagnulein** [comment]
> 1. The settings option to enable this is "Advanced Options > Volume buttons change gears", maybe it should be renamed to mention speed in case of treadmill or at least the description?

yeah i guess your it's a side case, anyway i will keep this in mind



> 2\. nclination on Zwift doesn't have fractions, but I have seen sometimes Zwift shows 1% but it's 2% on QZ. I understand there's a "pooling time", but in this case I am mentioning, Zwift never shown more than 1% on that path. So is it Zwift rounding down when it shouldn't?

zwift is showing an average, qz the actual one. anyway you can try to set the zwift inclination gain to 0.5 that it helps to have a similar behaviour



> 3\. f you click the "Side Menu", volume buttons stop working (doesn't change speed) until you click on something. In my case, it worked again after I "Paused/Unpaused" or used "+/-" on speed.

yeah because you're changing the focus of the window
