### ISSUE TITLE
[BUG] Swift Ride doesnt shift gears

### ISSUE THREAD

**Issue by mbrouwer** [cagnulein/qdomyos-zwift#2658]
After following https://www.youtube.com/watch?v=X3Q2WjbqMJo to setup the app I cant shift gears

**To Reproduce**
1. Follow https://www.youtube.com/watch?v=X3Q2WjbqMJo
2. Start App
3. Shift gears

**Expected behavior**
Gear shift in the app

 - Device: Surface Duo
 - OS: Android 12

[debug-Mon_Oct_14_20_06_58_2024.log](https://github.com/user-attachments/files/17367974/debug-Mon_Oct_14_20_06_58_2024.log)

**Comment by cagnulein** [comment]
Please join the beta here
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Update the app and also set your kickr under bike settings, ftms bike and
press OK and restart qz

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 14 ott 2024 alle 20:19 Marco Brouwer ***@***.***>
ha scritto:

**Comment by mbrouwer** [comment]
Hi,
Thanks that seems to work! Any way to get this to work on the Windows app as well, I dont usually use an Android phone :)

**Comment by cagnulein** [comment]
Yes sure download it from here
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 14 ott 2024 alle 20:50 Marco Brouwer ***@***.***>
ha scritto:
