### ISSUE TITLE
Wellfit treadmill support

### ISSUE THREAD

**Issue by SockAnimals** [cagnulein/qdomyos-zwift#2659]
**Describe the bug**
The app shows the "WELLFIT TM Linker" bluetooth device in the search list, but did not connect.  I attempted to filter to just this device, but it was unable to connect as a generic treadmill.

This treadmill works fine in Peloton and Zwift directly as a FTMS treadmill to gather the metrics.

**Expected behavior**
Be able to connect to the treadmill and collect speed, distance, and energy metrics.  Speed control would be a bonus, but not required.

**Screenshots**
Screenshots of nRF Connect device details
![IMG_7133](https://github.com/user-attachments/assets/2b2ff400-7ecd-453a-a0a5-4111b62c8491)
![IMG_7134](https://github.com/user-attachments/assets/bbf2d19f-1a91-43c6-9ed7-c363210df8dd)
![IMG_7135](https://github.com/user-attachments/assets/ba42b48e-633c-4350-9872-b9f78b12e453)
![IMG_7136](https://github.com/user-attachments/assets/5bf43e90-1964-4681-b403-924c411f10ac)
![IMG_7137](https://github.com/user-attachments/assets/df4c153c-762b-47ce-ac6d-a175d62c4a5f)
![IMG_7138](https://github.com/user-attachments/assets/3628cea5-d10c-44de-a246-1c26015fe7c8)

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro Max
 - OS: iOS 18.0.1
 - Version 18.0.1

**Append a debug log**

[debug-Tue_Oct_15_11_16_46_2024.log](https://github.com/user-attachments/files/17381211/debug-Tue_Oct_15_11_16_46_2024.log)
  
**Additional context**
Thank you for any support you can provide.

**Comment by cagnulein** [comment]
hi @SockAnimals simply set the treadmill under qz settings, treadmill, ftms treadmill and press ok and restart qz
Let me know!

**Comment by SockAnimals** [comment]
Is that under "Treadmill Options"?

**Comment by cagnulein** [comment]
yes @SockAnimals if you don't see it, please be sure you are running the version 2.17 of the QZ app
Let me know!

**Comment by SockAnimals** [comment]
Let me try that.  The update just showed

**Comment by SockAnimals** [comment]
Thank you for adding this in the update.  It connects now.  Let me check the metrics.

**Comment by SockAnimals** [comment]
The metrics work.  I really appreciate your support of this app.  

Is there any information I can provide to control the speed via QZ?  There is a standalone app for this treadmill that can do it.

**Comment by cagnulein** [comment]
speed + and - in qz doesn't work already out of the box?

**Comment by SockAnimals** [comment]
No, unfortunately it didn't.  It may be a non-standard interface as it didn't work in the other FTMS apps I've used

**Comment by cagnulein** [comment]
Ok do you have an android device to collect some logs? Or a Mac?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 18:00 SockAnimals ***@***.***>
ha scritto:

**Comment by SockAnimals** [comment]
I have a Mac.  Do I need to grab the developer tools?

**Comment by cagnulein** [comment]
You should be able to install the treadmill app there and with wireshark
grab the Bluetooth logs. Are you able?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 18:03 SockAnimals ***@***.***>
ha scritto:

**Comment by SockAnimals** [comment]
I installed Wireshark.  Oddly, I'm not seeing bluetooth as a device in the capture list.  Going to google that now

**Comment by cagnulein** [comment]
I always did this on android with
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

On mac you could need a developer license I guess

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 18:09 SockAnimals ***@***.***>
ha scritto:

**Comment by SockAnimals** [comment]
I have the macOS PacketLogger from the dev tools.  Let me try that

**Comment by SockAnimals** [comment]
I collected one log by running the iOS app from my Mac, which turned on and off the treadmill.  I imported this into Wireshark successfully.  It won't let me upload the zip file though.

I'm going to see if I can get the iOS remote capture working to gather this.

**Comment by SockAnimals** [comment]
[iOS on, speed up, speed down, off.zip](https://github.com/user-attachments/files/17382005/iOS.on.speed.up.speed.down.off.zip)

Here is the iOS bluetooth packet capture as a zip.  This is a pklg, but I can provide a btsnoop if that's better.  

As a FYI, it seems to require the iOS bluetooth profile installed on the target device, then connected via USB to the Mac, and running a version of PacketLogger from the extra Xcode Tools.  A new capture can be started with an iOS device.

The device connects, does a count down before it starts the treadmill to 0.6.  I then increased the speed a few times, decreased it back to 0.6, and then issued the stop command.

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno mar 15 ott 2024 alle 19:01 SockAnimals ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@SockAnimals i was checking the log and I saw that there are many custom characteristics from the treadfmill. in the nrfconnect screenshot, did you show me everyone? or did you miss someone? The problem of the log took from iOS is that I can't see the UUID from the characteristic. This is crucial to implement this

Let me know!

**Comment by SockAnimals** [comment]
Unfortunately, that's all I see in the attribute table in nRF Connect.

I'm attaching a trace from the nRF Connect app starting just before hitting connect and then clicking the read button for each property.  I saw some packets using the Attribute Protocol that contained UUID early on in the trace after filtering by `(bluetooth.src == c6:80:93:ff:c1:24) || (bluetooth.dst == c6:80:93:ff:c1:24)`.  Maybe that will show something? 
[nRF Connect.zip](https://github.com/user-attachments/files/17396187/nRF.Connect.zip)

I also recaptured the app trace, starting before app launch in case something useful shows up.  Speed goes from 0 -> 0.6 -> 1.4 -> 0.6 -> 0.  
[App Trace.zip](https://github.com/user-attachments/files/17396239/App.Trace.zip)

If this doesn't have the details you are looking for, then feel free to close this.  Thank you for investigating this.

**Comment by cagnulein** [comment]
Thanks, I'll check it out tomorrow!

**Comment by cagnulein** [comment]
Unfortunately not :( can't you borrow an android device just for this test? you just need 10 minutes with it

**Comment by SockAnimals** [comment]
I don't have an android device, but I'll try to repurpose a raspberry pi to install an android image and see how that goes.  Otherwise, I'll try the official emulator and run nRF Connect there.

**Comment by cagnulein** [comment]
ok! consider that bluetooth doesn't work on emulator
let me know! Never give up!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 ott 2024 alle ore 16:57 SockAnimals <
***@***.***> ha scritto:

**Comment by SockAnimals** [comment]
Loading Android 14 on a pi 4 seemed to work.  Here are the nRF Connect screenshots via Android.  Is there a way to snoop the traffic from the treadmill app while it's running in Android to capture the speed changes and start/stop commands?

![Screenshot_20241017-222957_nRF Connect](https://github.com/user-attachments/assets/0ed6ebaa-da66-4bcc-b97b-abe7a8e212e3)
![Screenshot_20241017-223003_nRF Connect](https://github.com/user-attachments/assets/42e6d0c2-1fd3-4e08-b97e-de80d5bdde74)
![Screenshot_20241017-223008_nRF Connect](https://github.com/user-attachments/assets/d82cc15e-673c-4068-b43f-88d7479fbde3)
![Screenshot_20241017-223013_nRF Connect](https://github.com/user-attachments/assets/e41fd32b-a03e-4d29-9992-3d9ce295c298)
![Screenshot_20241017-223017_nRF Connect](https://github.com/user-attachments/assets/1ba1eaf3-b483-4f36-bf4a-f15448e549fa)
![Screenshot_20241017-223022_nRF Connect](https://github.com/user-attachments/assets/819b4451-60bf-4a6b-8652-5e533e0c2dea)

**Comment by cagnulein** [comment]
That's great, yes following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by SockAnimals** [comment]
Here is the zip file.
[bugreport-lineage_rpi4-AP2A.240805.005-2024-10-18-09-32-43.zip](https://github.com/user-attachments/files/17436336/bugreport-lineage_rpi4-AP2A.240805.005-2024-10-18-09-32-43.zip)

I opened the app, started the treadmill, increased the speed four times, decreased the speed four times, set the speed to 3 mph, and then stopped the treadmill via the app.  Thank you for your help investigating this.

**Comment by cagnulein** [comment]
Ok, I'll check it out In the next days


Il giorno ven 18 ott 2024 alle 15:39 SockAnimals ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@SockAnimals were you using their app in this log? because I saw that they are using the classic FTMS commands but with specific speed values.

maybe the issue is that qz was trying to change 0.5 km/h speed increments? does the app allows only to change 1.0 mph as minimum step?

maybe the issue is that qz was trying to set a too slow speed as beginning? which is their minimum speed?

**Comment by SockAnimals** [comment]
Yes, I was using their app for this capture.  The app started at 0.6 mph, and incremented by 0.2 mph up to 1.4 mph, and then back down the same way. There should also be a set to 3.0 mph before the stop command.On Oct 20, 2024, at 10:26 AM, Roberto Viola ***@***.***> wrote:﻿
@SockAnimals were you using their app in this log? because I saw that they are using the classic FTMS commands but with specific speed values.
maybe the issue is that qz was trying to change 0.5 km/h speed increments? does the app allows only to change 1.0 mph as minimum step?
maybe the issue is that qz was trying to set a too slow speed as beginning? which is their minimum speed?

**Comment by SockAnimals** [comment]
I saw this in the above nRF screenshots.  Maybe that explains it?On Oct 20, 2024, at 11:19 AM, Michael Swift ***@***.***> wrote:﻿Yes, I was using their app for this capture.  The app started at 0.6 mph, and incremented by 0.2 mph up to 1.4 mph, and then back down the same way. There should also be a set to 3.0 mph before the stop command.On Oct 20, 2024, at 10:26 AM, Roberto Viola ***@***.***> wrote:﻿
@SockAnimals were you using their app in this log? because I saw that they are using the classic FTMS commands but with specific speed values.
maybe the issue is that qz was trying to change 0.5 km/h speed increments? does the app allows only to change 1.0 mph as minimum step?
maybe the issue is that qz was trying to set a too slow speed as beginning? which is their minimum speed?

**Comment by SockAnimals** [comment]
![image](https://github.com/user-attachments/assets/b4e2c766-c82f-4114-9ac9-b938236ddfbd)

**Comment by cagnulein** [comment]
So strange! Can you show me a debug log from qz trying to change the speed? I would like to compare it

**Comment by SockAnimals** [comment]
Here’s the debug log.  I changed the speed via a remote, as hitting the + and - circles on the speed tile didn’t change it.

[debug-Sun_Oct_20_14_05_27_2024.log](https://github.com/user-attachments/files/17451545/debug-Sun_Oct_20_14_05_27_2024.log)

**Comment by cagnulein** [comment]
i guess i understood the issue. what if you change the speed manually to 1km/h or above from the treadmill and then you try to increase and decrease the speed. Everything works normally, right? If so i have only to set the min speed to 0.96 in this case
Let me know

**Comment by SockAnimals** [comment]
I turned on the treadmill and set the speed to 1.0 mph via the remote (according to the display and QZ app).  I then hit the + and - buttons on the speed tile without any effect.

For reference, the remote, when it starts sets the speed to 0.6 mph or the 0.96 km/h value.

I saw that "Speed Step" in the Treadmill settings was set to 0.2, which appears to match the 0.32 km/h granularity.  I changed this to 1.0 and retried the steps above, but nothing happened.

**Comment by cagnulein** [comment]
@SockAnimals i tried to made a patch to align QZ to the hci snoof collected from the raspberry

can you install the apk here https://github.com/cagnulein/qdomyos-zwift/actions/runs/11456617615 to the raspberry with android

you can use the android build in the link (check at the bottom of the page in about 1 hour).

**Comment by SockAnimals** [comment]
[bugreport-lineage_rpi4-AP2A.240805.005-2024-10-22-09-51-55.zip](https://github.com/user-attachments/files/17477362/bugreport-lineage_rpi4-AP2A.240805.005-2024-10-22-09-51-55.zip)

Here's the HCI snoop from the new apk.  I kept all the settings at the default and simply pressed the +/- buttons on the speed tile a few times without any changes.  Then I switched to the remote to start it at 1.0 kph and tried again.

If I've missed anything, please let me know

**Comment by cagnulein** [comment]
Thanks, i don't see any requests from qz, could you please create a debug log from this version https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
thanks!

**Comment by SockAnimals** [comment]
[bugreport-lineage_rpi4-AP2A.240805.005-2024-10-22-10-40-30.zip](https://github.com/user-attachments/files/17478097/bugreport-lineage_rpi4-AP2A.240805.005-2024-10-22-10-40-30.zip)
[debug-Tue_Oct_22_10_39_05_2024.log](https://github.com/user-attachments/files/17478099/debug-Tue_Oct_22_10_39_05_2024.log)

Here are the two files

**Comment by cagnulein** [comment]
ok i guess I got the issue
please check this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/11462793492

thanks!

**Comment by SockAnimals** [comment]
That seemed to make things work.  I changed it to miles from km and set the speed increment step to 0.2.

Pressing the start button in the app, it did the count down and went to 0.6 mph.  Pressing +/- worked perfectly.  Pausing set the speed back to zero until resumed.  Stopping turned it off.

Looks like it's working perfectly.  Thank you.
