### ISSUE TITLE
SHAWN PAVLIN ASCEND S2 Erg Mode

### ISSUE THREAD

**Issue by shawnyboy60** [cagnulein/qdomyos-zwift#2660]
Hey Roberto,
I've been trying to do Zwift Workouts in ERG mode on my Ascend S2 bike along with the QZ app. Even if I set the option in the Settings > Bike Options > Zwift Workout/Erg mode, the bike will not return any resistance value back to the bike (even when ERG mode is ON in the Zwift options). Any idea why it doesn't work?
Thanks and cheers!
Shawn

**Comment by cagnulein** [comment]
I guess the bike doesn't have erg mode on the firmware. You can be sure
about this if erg mode doesn't work on zwift with the bike direct either.

If it's so i have a good news for you because I can add it

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 19:12 shawnyboy60 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Ok, I'll try to do this in the next days


Il giorno mar 15 ott 2024 alle 19:26 shawnyboy60 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi @shawnyboy60 could you please share a debug log from your setup? I would like to double check a thing so I can apply the patch correctly https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

**Comment by shawnyboy60** [comment]
[Archive.zip](https://github.com/user-attachments/files/17398711/Archive.zip)

Hey Roberto, here's a few logs from my past sessions.

**Comment by cagnulein** [comment]
Thanks, I'll check them out.

**Comment by cagnulein** [comment]
perfect, in order to understand if i'm doing the right thing I just sent a new version via testflight where, in the settings, you can enable the Use Resistance instead of Inclination in the advanced setting.
Enable it and restart QZ.
Then just test, without zwift, only with qz, if using the plus and minus button on the resistance tile, you're able to change the resistance level on the bike. If so, we are good to go!
Let me know

**Comment by shawnyboy60** [comment]
Hey Roberto, 
Yes, with the advanced settings changed, I can change the bike's resistance using the + and - buttons on the resistance tile!
Cheers!

**Comment by cagnulein** [comment]
Awesome, I will implement this tomorrow!


Il giorno gio 17 ott 2024 alle 20:00 shawnyboy60 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
sent a new beta! show me a debug log if it doesn't work
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 ott 2024 alle ore 20:01 cagnulein ***@***.***> ha
scritto:

**Comment by shawnyboy60** [comment]
Hey Roberto, it works perfectly!! Once again, thanks for your help. :)

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno ven 18 ott 2024 alle 21:44 shawnyboy60 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Hi @shawnyboy60 show me a debug log with this issue and I will check it! https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by shawnyboy60** [comment]
[debug-Wed_Oct_30_15_23_03_2024.log](https://github.com/user-attachments/files/17578310/debug-Wed_Oct_30_15_23_03_2024.log)

Here it is!

**Comment by cagnulein** [comment]
In this log I can see a one resistance change only to 10. Is this the issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ott 2024 alle 20:58 shawnyboy60 ***@***.***>
ha scritto:

**Comment by shawnyboy60** [comment]
Numerous times during that ride, my bike's resistance went down below 10, all the way down to 1.
I want to avoid having a bike resistance under 10!

**Comment by cagnulein** [comment]
I guess maybe it's not the right log? Do you have others on that time frame?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ott 2024 alle 23:04 shawnyboy60 ***@***.***>
ha scritto:

**Comment by shawnyboy60** [comment]
[debug-Wed_Oct_30_15_23_03_2024 2.log](https://github.com/user-attachments/files/17589202/debug-Wed_Oct_30_15_23_03_2024.2.log)

Here is another one!

![IMG_4603](https://github.com/user-attachments/assets/27fd2de6-d772-4631-bf1d-7ba70dcb09b0)

**Comment by cagnulein** [comment]
even this one is not valid. let's do in this way. zip them all and send me all of them so I will pick the right one myself :)

**Comment by shawnyboy60** [comment]
[logs_roberto.zip](https://github.com/user-attachments/files/17589332/logs_roberto.zip)

Here's a few logs from the last few days! The "Min. Resistance" option has always been set to 10. Thanks :)

**Comment by cagnulein** [comment]
ok the debug-Wed_Oct_30_13_31_49_2024.log was the right one. i'm
investigating it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 31 ott 2024 alle ore 15:59 shawnyboy60 <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
got the issue. that setting is applying for erg mode only. in this case you are doing a free ride or a race so zwift is sending inclination and i'm bridging it to your bike.  so there are 2 solutions for this:
- use the gear to increase it
- adding a new couple of setting, similar to res min and max, but this time about the inclination, so like inclination min and max. so in this case you can set for example 1% and all the values below 1% sent from zwift will be capped to 1%

Let me know

**Comment by shawnyboy60** [comment]
![IMG_4604](https://github.com/user-attachments/assets/e5609ea5-e455-4cc1-8c03-091047934ea0)

Would your second solution be this option in the app?

**Comment by cagnulein** [comment]
i was thinking more about a new setting. because te zwift inclination offset is for treadmill, and for the bike is exactly what the gear does

**Comment by shawnyboy60** [comment]
Ahhh I understand now.
The problem I have happens in steep inclines. Whenever a ride brings me from +5% down to -5% inclination quickly, I always end up down at my lowest resistance even with a gear change. If I could set a minimum resistance, I wouldn't have to play around with the gears this much.
Let me know!

**Comment by cagnulein** [comment]
So you would be fine with a min inclination setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 16:56 shawnyboy60 ***@***.***>
ha scritto:

**Comment by shawnyboy60** [comment]
If I understand correctly, I do believe a minimum inclination setting would fix my problem!

**Comment by cagnulein** [comment]
Ok I will implement it in the next days!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 2 nov 2024 alle 16:44 shawnyboy60 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done @shawnyboy60

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by shawnyboy60** [comment]
Done!


*SHAWN PAVLIN*
Directeur de la photographie / Cinematographer
Associate Member CSC
AQTIS-IATSE 514
www.shawnpavlin.ca
+1-514-794-2565
