### ISSUE TITLE
Send power/cadence to garmin edge 1030 pro

### ISSUE THREAD

**Issue by markussiebert** [cagnulein/qdomyos-zwift#2661]
Hi,
I want to send the power / cadence data to my edge 1030 plus. I see a BLE Sensor on my edge device, but it won't connect. Stock on 'connecting'
 ![image](https://github.com/user-attachments/assets/62c7d5a7-12ac-4112-aeeb-691450f4a1e5)

Am I doing something wrong?

**Comment by markussiebert** [comment]
I can't use it on iPhone?

**Comment by cagnulein** [comment]
No it's a garmin limitation unfortunately

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 16 ott 2024 alle 06:50 Markus Siebert <
***@***.***> ha scritto:

**Comment by markussiebert** [comment]
good to know
