### ISSUE TITLE
Cannot login to Strava with google

### ISSUE THREAD

**Issue by markussiebert** [cagnulein/qdomyos-zwift#2662]
I cannot connect to Strava via google login because this app uses an insecure browser.

![image](https://github.com/user-attachments/assets/bd64ce77-6a21-4134-8fb7-79e95c09d894)

**Comment by cagnulein** [comment]
Toggle the strava Auth in the advanced settings and restart qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 15 ott 2024 alle 22:51 Markus Siebert <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@markussiebert All Ok?
