### ISSUE TITLE
[BUG] android beta does not connect to vitufit htr 2.1 and does not broadcast for mywoosh

### ISSUE THREAD

**Issue by DeManMetDeHamer** [cagnulein/qdomyos-zwift#2663]
**Describe the bug**
Android beta does not connect to vitufit htr 2.1 and does not broadcast for mywoosh

**Desktop (please complete the following information):**
 - Android
 - Version 13

**Smartphone (please complete the following information):**
 - Device: oneplus x
 - OS: android 11
 
**Append a debug log**
[Uploading debug-Wed_Oct_16_08_03_27_2024.log…]()

  
  
**Additional context**

**Comment by DeManMetDeHamer** [comment]
[debug-Wed_Oct_16_08_03_27_2024.log](https://github.com/user-attachments/files/17390307/debug-Wed_Oct_16_08_03_27_2024.log)

**Comment by cagnulein** [comment]
@DeManMetDeHamer remove the VIFHTR2 device from the heart rate belt setting and press ok and restart QZ
Let me know!

**Comment by DeManMetDeHamer** [comment]
@cagnulein 
That fixed the issue with the bike not connecting to the phone, however mywoosh still does not find the qz device.
I renamed the bluetooth name to bike like you said, and restarted the phone.

Anything else i can try?

**Comment by cagnulein** [comment]
on which device mywhoosh is running?

**Comment by DeManMetDeHamer** [comment]
It is running on an android 13 tablet.
If im using qz from my iPhone it finds the device normally but from this android version it does not

**Comment by cagnulein** [comment]
you can't run mywhoosh and qz on the same device. you need one device for qz and one for mywhoosh. I guess this is your issue
Let me know

**Comment by cagnulein** [comment]
if you are instead using 2 device (2 android devices), be sure to rename your phone with qz to "bike" from the android settings and reboot it

**Comment by DeManMetDeHamer** [comment]
im using an android phone with qz on it and a tablet running mywoosh.
For the phone i renamed it in the system settings to bike and rebooted.
im currently trying the same with the bluetooth name.

**Comment by cagnulein** [comment]
ok let me know

**Comment by DeManMetDeHamer** [comment]
[debug-Wed_Oct_16_09_38_50_2024.log](https://github.com/user-attachments/files/17391316/debug-Wed_Oct_16_09_38_50_2024.log)

I renamed the qz phone in both Bluetooth and system settings. Now the app seems to think it connected but the bike does not. And mywoosh still does not find it

**Comment by cagnulein** [comment]
@DeManMetDeHamer Any news?

**Comment by DeManMetDeHamer** [comment]
Hi Roberto,

I was not able to get it working, so I decided to switch it back to my iOS phone.

Kind regards,

Robin

Met vriendelijke groet,

Robin Pols
________________________________
Van: Roberto Viola ***@***.***>
Verzonden: Thursday, November 14, 2024 7:32:51 AM
Aan: cagnulein/qdomyos-zwift ***@***.***>
CC: DeManMetDeHamer ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cagnulein/qdomyos-zwift] [BUG] android beta does not connect to vitufit htr 2.1 and does not broadcast for mywoosh (Issue #2663)


@DeManMetDeHamer<https://github.com/DeManMetDeHamer> Any news?
