### ISSUE TITLE
[BUG] Horizon 7.0at-02 auto speed and incline not working

### ISSUE THREAD

**Issue by kbortnik** [cagnulein/qdomyos-zwift#2664]
**Describe the bug**
When doing a Zwift workout, auto speed and incline on the Horizon 7.0at-02 treadmill does not work.
Changing the speed and incline with the tiles works fine.

Speed does not change automatically at any point.

Incline kind of works, but it's reflecting the inclination of the map (displayed in top right-hand corner), instead of the inclination set in the workout. I've set the offset to 1 (so that I get 1% on the treadmill for 0% in Zwift), and it randomly fluctuates +/- 0.5% from the map inclination.

**To Reproduce**
1. Open QZ and wait for it to connect to treadmill
2. Connect to Wahoo TREAD 0000 on Zwift
3. Start workout
4. Start treadmill through QZ

**Expected behavior**
* Speed is automatically set
* Incline is automatically set to follow the workout incline

**Smartphone:**
 - Device: iPhone 16 Pro
 - OS: iOS 18.0.1
 - QZ version: 2.17

**Append a debug log**
[debug-Wed_Oct_16_17_22_19_2024.log](https://github.com/user-attachments/files/17390991/debug-Wed_Oct_16_17_22_19_2024.log)
  
**Additional context**

Treadmill <-> QZ on iOS <-> Zwift on Apple TV (Wahoo TREAD 0000 selected)

QZ settings:
* Zwift username and password set
* Zwift Treadmill Auto Inclination (iOS) enabled
* Other Zwift settings disabled
* Treadmill options - Treadmill Speed Forcing enabled
* FTMS Treadmill is disabled

**Comment by cagnulein** [comment]
if you are doing a workout, disable the "Zwift Treadmill Auto Inclination" in the zwift setting, otherwise QZ is changing the inclination got from Zwift world.

in the debug log posted I don't see any train program loaded on QZ. Did you? You must do this because Zwift doesn't send by itself the workout requests. Read this also https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F

Let me know if you have any questions!

**Comment by kbortnik** [comment]
That makes sense, thank you. I was under the impression that the Zwift API integration eliminates the need to load a ZWO file.
I'm assuming it's not possible to use this feature on a headless Raspberry Pi, since there's no way to load a ZWO file?

**Comment by cagnulein** [comment]
You can use it on a raspberry using vnc on it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 17 ott 2024 alle 01:12 Kristian Bortnik <
***@***.***> ha scritto:
