### ISSUE TITLE
[BUG] App has stopped connecting to Echelon 3

### ISSUE THREAD

**Issue by Matt138976** [cagnulein/qdomyos-zwift#2665]
[debug-Tue_Oct_15_07_17_54_2024.log](https://github.com/user-attachments/files/17390881/debug-Tue_Oct_15_07_17_54_2024.log)
**Describe the bug**
I've been using the app for over a year with no issues. Last week during a ride I decided to update the settings for the Zwift ERG Watt Down Filter. Once updated the app had a pop up message saying to restart in order to update the settings. I did this and since then the app has been unable to connect to the Echelon again.

**To Reproduce**
1. start ride
2. go to settings and update Zwift Watt Down Filter
3. Restart app

**Expected behavior**
This should update the setting and then reconnect to the Echelon.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 8 pro
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
As an additional note to start with it did have the Echelon blue tooth details at the top of the app. Since I've been trying to reconnect I have reinstalled the app and it now no longer states the Echelon details but has a seemingly random connection stated of S38 0A92 LE. but this doesn;t seem to correspond with any available bluetooth connections that I can see when I go to my bluetooth settings.
I've attached a debug log from this week. I have also attached 2 debug logs from last week. I think one of these probably captures the session where the initial problem occured.
[debug-Fri_Oct_11_11_14_19_2024.log](https://github.com/user-attachments/files/17391049/debug-Fri_Oct_11_11_14_19_2024.log)

[debug-Fri_Oct_11_11_11_33_2024.log](https://github.com/user-attachments/files/17391047/debug-Fri_Oct_11_11_11_33_2024.log)

**Comment by cagnulein** [comment]
hi @Matt138976 the log from oct 15 is corrupted. You need to close qz before sending me it. Could you please create a new one?

Thanks

**Comment by Matt138976** [comment]
No problem. I'll do that now.

Thanks

Matt

**Comment by Matt138976** [comment]
[Uploading debug-Wed_Oct_16_08_31_41_2024.log…]()

**Comment by cagnulein** [comment]
@Matt138976 you have to wait the upload before pushing comment, please redo again. thanks

**Comment by Matt138976** [comment]
[debug-Wed_Oct_16_08_31_41_2024.log](https://github.com/user-attachments/files/17391293/debug-Wed_Oct_16_08_31_41_2024.log)

**Comment by cagnulein** [comment]
@Matt138976 the problem is that you enabled the fake device and fake elliptical in the experimental settings. disable both and restart qz and you will solve the issue
Let me know!

**Comment by Matt138976** [comment]
Brilliant, thank you, that's sorted it, although no idea how those settings changed!

**Comment by cagnulein** [comment]
please join the swag bag on the app to support the app! thanks!
