### ISSUE TITLE
[BUG] Heartrate wont show Galaxy Watch 7

### ISSUE THREAD

**Issue by Brecherbernd** [cagnulein/qdomyos-zwift#2668]
**Describe the bug**
Hi, the QZ App on the watch it wont show any heartrate, i tried reinstalling, enabling beta and restarting the watch, but still no heart rate.

![20241016_195101](https://github.com/user-attachments/assets/cbc05175-2bd7-4862-bc43-b028baafc938)

**Comment by cagnulein** [comment]
Check the permissions of the qz app on the watch, must be all enabled. Let me know

**Comment by Brecherbernd** [comment]
> Check the permissions of the qz app on the watch, must be all enabled. Let me know

Checked and everything is enabled, deleted the cache and data, restarted checked all permissions again, rechecked in settings everythings fine, but still the same error as in the screenshot above.

**Comment by cagnulein** [comment]
You can try to ask here https://github.com/cagnulein/qdomyos-zwift/issues/2593

Are you able to collect an adb logcat from the watch?

**Comment by cagnulein** [comment]
@Brecherbernd Any news?
