### ISSUE TITLE
[BUG] Can't connect to Strava on linux build

### ISSUE THREAD

**Issue by wtafe** [cagnulein/qdomyos-zwift#2669]
**Describe the bug**
Trying to connect to Strava on 2.18.0 causes the application to crash. 

**To Reproduce**
Open Qdomyos-Zwift on Linux, Press Connect with Strava button. I have tried enabling Strava External Browser Auth and it still has the same effect.

**Expected behavior**
Open a broswer window to authenticate with Strava.

**Screenshots**

**Desktop (please complete the following information):**
Linux 6.2.0-32-generic

**Append a debug log**
[debug-Thu_Oct_17_13_36_08_2024.log](https://github.com/user-attachments/files/17416723/debug-Thu_Oct_17_13_36_08_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
If there is a way to get a token to manually do this so no development is needed to resolve, I'd be happy to do that.

**Comment by wtafe** [comment]
Thank you Roberto!

**Comment by wtafe** [comment]
[debug-Tue_Nov_19_17_21_34_2024.log](https://github.com/user-attachments/files/17822261/debug-Tue_Nov_19_17_21_34_2024.log)

Attached debug from issue.

**Comment by EPiSKiNG** [comment]
Trying to get Strava connected on rpi/Linux.  Where is the secrets.h file located and what should the file contain?  I don't see a secrets.h file anywhere currently.

Thank you!!!

**Comment by EPiSKiNG** [comment]
Ok.  I created secrets.h in src folder and populated it with the following data:

```
STRAVA_SECRET_KEY={STRAVA CLIENT SECRET KEY}
STRAVA_CLIENT_ID={CLIENT ID FROM STRAVA API APPLICATION}
```

Doesn't seem to work... Perhaps I'm not defining properly?  Should I be adding quotes?

Thanks!

**Comment by cagnulein** [comment]
You need to use

#define STRAVA_SECRET_KEY {STRAVA CLIENT SECRET KEY}


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 feb 2025 alle 19:49 EPiSKiNG ***@***.***> ha
scritto:

**Comment by EPiSKiNG** [comment]
Ok, I have defined just the Secret Key as you specified without quotes as subsitution for the {STRAVA CLIENT SECRET KEY} part, and in the Advanced Settings of QML, I set "Strava Upload" to Request.  When I finish a run, I do not get a prompt to upload to Strava.

Thanks for the help!

**Comment by cagnulein** [comment]
Did you specify also the app ID? Mine was just to explain how it was the
syntax

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 2 feb 2025 alle 22:01 EPiSKiNG ***@***.***> ha
scritto:

**Comment by EPiSKiNG** [comment]
Yes, here is my secrets.h file:

![Image](https://github.com/user-attachments/assets/7ba60ce2-8d96-4db3-a6e0-13c0b50f45c7)

**Comment by cagnulein** [comment]
do you see any warning during the build?

**Comment by EPiSKiNG** [comment]
Ahhh, do I need to "make" again after adding that file?  That's probably the problem! :)

**Comment by cagnulein** [comment]
Yes for sure!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 feb 2025 alle 16:17 EPiSKiNG ***@***.***> ha
scritto:

**Comment by EPiSKiNG** [comment]
Ok, I rebuilt using:

```
cd src
qmake qdomyos-zwift.pro
make -j4
```

Then ran again, and set the Strava upload option to Request.  Ran for about 3 minutes, then stopped, and was presented with the graphs in QZ, but no option to upload to Strava.  Tried again using automatically upload and still not seeing anything coming in to Strava...?

Thanks!!

**Comment by EPiSKiNG** [comment]
Got the following when doing build -B  (this error was repeated several times)


![Image](https://github.com/user-attachments/assets/1fdba8dc-cb7f-4214-9849-c8d415a9a426)

**Comment by cagnulein** [comment]
So the define it's not right.
Check exactly the name and the sure secret.h is on the right folder

**Comment by EPiSKiNG** [comment]
Ha!  I was using secrets.h not secret.h.  :)

```
mv secrets.h secret.h
make -j4 -B

```
Re-ran, and still not getting prompt to upload to Strava... Sorry!

Thanks!

**Comment by cagnulein** [comment]
Do you see any error on qz? Set to always to double check if it's not a
"request" issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 feb 2025 alle 19:43 EPiSKiNG ***@***.***> ha
scritto:

**Comment by EPiSKiNG** [comment]
See attached debug log.  Seems like Strava ID is coming in as null...

Thanks!

[debug-Mon_Feb_3_11_59_56_2025.log](https://github.com/user-attachments/files/18647618/debug-Mon_Feb_3_11_59_56_2025.log)

**Comment by cagnulein** [comment]
That one was peloton. Did you click on the strava banner to authenticate qz
to strava?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 feb 2025 alle 21:07 EPiSKiNG ***@***.***> ha
scritto:

**Comment by EPiSKiNG** [comment]
I would have preferred to use the button to authenticate with Strava initially, but when I click that orange button in the menu, it closes QZ app.  Here's another log file:

[debug-Mon_Feb_3_12_18_28_2025.log](https://github.com/user-attachments/files/18647740/debug-Mon_Feb_3_12_18_28_2025.log)

**Comment by cagnulein** [comment]
That button is a requirement to create a token on strava

If it's crash run qz through gdb to understand where and why it's crashing

Now I'm going to bed, I will be back tomorrow

Chat gpt could help you in this process meanwhile I'm on bed :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 feb 2025 alle 21:21 EPiSKiNG ***@***.***> ha
scritto:
