### ISSUE TITLE
[BUG] Con Rouvy il cambio marce non funziona 

### ISSUE THREAD

**Issue by inesfra63** [cagnulein/qdomyos-zwift#2670]
**Describe the bug**
Funziona tutta la parte coreografia, lo vedi a video che al cliccare del comando remoto BT si verifica una risposta grafica numerica in meno o in più della marcia.
Ma all'atto pratico, tu avverti solo per un attimo la risposta sulla pedalata al tuo comando, si alleggerisce un attimo se metti una marcia più leggera, si indurisce per un attimo se metti una marcia più dura, ma poi è come se il rullo riprendesse il controllo dei comandi e ritorna alla originaria durezza che aveva prima di dargli il comando su Qz.

Però io l'ho provata solo con Rouvy, poi magari con Mywhoosch o BKOOL o Zwift o IndieVelo funziona alla grande.

Andrebbe anche rivisto il collegamento a Strava. Una volta accoppiata Qz a Strava, il logo di Strava che invita a creare il collegamento va eliminato, sennò uno pensa che il collegamento non sia avvenuto. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide http
[debug-Fri_Oct_18_07_52_46_2024.log](https://github.com/user-attachments/files/17430533/debug-Fri_Oct_18_07_52_46_2024.log)
[debug-Thu_Oct_17_18_57_31_2024.log](https://github.com/user-attachments/files/17430534/debug-Thu_Oct_17_18_57_31_2024.log)
[debug-Thu_Oct_17_19_37_49_2024.log](https://github.com/user-attachments/files/17430536/debug-Thu_Oct_17_19_37_49_2024.log)
s://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@inesfra63 log controllato e ho capito il tuo problema, non hai collegato la parte controllabile di rouvy a qz! ecco il motivo
fammi uno screenshot di come colleghi rouvy a qz
fammi sapere

**Comment by cagnulein** [comment]
@inesfra63 Tutto ok?

**Comment by inesfra63** [comment]
Si, perfettamente!

Avevo avuto qualche problema con il cardio che non era più visto dalla apk
Qz. Ma poi ho appurato che il problema era dovuto al cardio stesso che
aveva esaurito la batteria.
Su Rouvy, poi, mi compariva giustamente come rullo utilizzato la dicitura
anonima "Bike".
Ho provato a sostituire, nell'accoppiamento dei sensori di Rouvy, al
sensore di potenza proprio il mio rullo Elite Direto xr, ed ho risolto.
Quindi, come controllabile ho lasciato "Bike", come sensore di potenza ho
inserito il mio rullo Elite Direto Xr.

Ed ho risolto.


Saluti carissimi.

Il gio 14 nov 2024, 07:31 Roberto Viola ***@***.***> ha
scritto:
