### ISSUE TITLE
ifit no longer pairing with QZ App

### ISSUE THREAD

**Issue by bkeown64** [cagnulein/qdomyos-zwift#2676]
**Describe the bug**
When attempting to pair my phone running qz with my Echelon bike, iFit sees the phone but times out during the pairing process.

**To Reproduce**
1. Renamed phone “I_EL” and rebooted phone
2. Started qz app (behavior is similar on iPhone or Galaxy S24 with Virtual iFit selected in Experimental Section of QZ app
3. Started iFit app on Android tablet. Attempted to pair bike in iFit app. App sees bike (I_EL)
4. Error pops up in iFit after several seconds stating something went wrong, turn Bluetooth off and on the tablet and to try again.
5. Repeat. 

**Expected behavior**
Bike should (and had in the past) connected. It appears iFit may have changed something in their app.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 14 

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: [e.g. iOS 18
 - Version QZ 2.17.0
[btsnoop_hci (2).log](https://github.com/user-attachments/files/17447484/btsnoop_hci.2.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Share first of all a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

**Comment by bkeown64** [comment]
[debug-Sun_Oct_20_16_27_14_2024 2.log](https://github.com/user-attachments/files/17452014/debug-Sun_Oct_20_16_27_14_2024.2.log)

**Comment by cagnulein** [comment]
the problem is that ifit doesn't even connect on QZ: QZ is broadcasting itself without receiving a reply.
can you try renaming it to "I_EB" ?

also, with nrfconnect app from the tablet, can you show me how the I_EB device is there?
