### ISSUE TITLE
[BUG] resistance against negative gradient

### ISSUE THREAD

**Issue by Kaowin32** [cagnulein/qdomyos-zwift#2677]
**Describe the bug**
Trainer doesn’t react as expected for negative gradients/downhill

**To Reproduce**
I started a free ride on road to Sky on Zwift and immediate U turn as it’s all downhill. Resistance actually INCREASES as gradient gets steeper downhill. -8 is harder than -2

**Expected behavior**
Negative numbers should be easier resistance

*ios18
[debug-Sun_Oct_20_10_21_25_2024.log](https://github.com/user-attachments/files/17449718/debug-Sun_Oct_20_10_21_25_2024.log)

**Comment by cagnulein** [comment]
I checked and indeed i see only positive values. Could I ask to enable the target incline tile in QZ and show me a little video in the same context with this tile and the inclination from zwift?
Thanks

**Comment by cagnulein** [comment]
fixed! i will send a new one soon, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@Kaowin32 Any news?
