### ISSUE TITLE
No connection to Wahoo Kicker Core

### ISSUE THREAD

**Issue by AaIiGee** [cagnulein/qdomyos-zwift#2678]
**Describe the bug**

The app does not connect with the new Wahoo Kickr Core, even though the device appears in the Bluetooth devices menu. I have also successfully connected the device to Zwift, among others.

**To Reproduce**

Just start the app.

**Expected behavior**
A clear and concise description of what you expected to happen

The bletooth connection should be established.

**Smartphone (please complete the following information):**
 - Galaxy tab S6
 - OS: Android
 - Version 12

**Append a debug log**
[debug-Sun_Oct_20_15_17_57_2024.log](https://github.com/user-attachments/files/17450325/debug-Sun_Oct_20_15_17_57_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
su lokak. 20 15:17:58 2024 1729426678281 Warning:   Search not possible due
to missing permission (ACCESS_COARSE|FINE_LOCATION)

this is the issue, you dind't enable location services on your phone.
enable it and restart qz, let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 20 ott 2024 alle ore 15:00 AaIiGee ***@***.***>
ha scritto:

**Comment by AaIiGee** [comment]
Hi,

OK and thanks, it was that!

Anton



Lähetetty laitteesta Galaxy



-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 20.10.2024 16.31 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Author ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


su lokak. 20 15:17:58 2024 1729426678281 Warning: Search not possible due
to missing permission (ACCESS_COARSE|FINE_LOCATION)

this is the issue, you dind't enable location services on your phone.
enable it and restart qz, let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 20 ott 2024 alle ore 15:00 AaIiGee ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Glad it worked!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 20 ott 2024 alle ore 15:37 AaIiGee ***@***.***>
ha scritto:

**Comment by AaIiGee** [comment]
Hi,

I'm sorry to bother you again, but I can't get the app work with Rouvy and Zwift Ride as possibility to change gears is missing.

I followed the steps in this video (https://www.youtube.com/watch?v=ltpihRqGARU), but the difference is that in Rouvy's device settings I have many options:

  *   Smart trainer: Kicker Core 392B with Bluetooth logo and ANT 14365 connection with power and FE-C logo
  *   Cadence: same as above
  *   Controllable: only the ANT 14365 connection with the FE-C logo.
Should I see something like my phone on the list and then connect it to Rouvy as a device? Those listed devices are just the same as I can see and use without QZ.
The system is like QZ is installed on my Android phone which is connected to Kicker Core and that connection is fine now. Rouvy is installed on my Android tablet with bluetooth connection on and tablet and phone are paired together via bluetooth. Zwift controllers are on and they are paired with the phone. Location is allowed for the phone and tablet.
I’m out of ideas what to try next. It also seems that app and Rouvy have changed lately and all old googled information is not valid anymore.
Apologies for the inconvenience, but I would greatly appreciate it if you could help with this!
Anton



-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 20.10.2024 16.37 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Author ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


Glad it worked!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 20 ott 2024 alle ore 15:37 AaIiGee ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@AaIiGee  did you rename the phone with QZ to "bike" (only 4 letters) and reboot the phone?
let me know

**Comment by AaIiGee** [comment]
That step was missing, now all sensors are connected via bluetooth to "bike" but the still no shifting.

Anton



-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 23.10.2024 13.55 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Mention ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


@AaIiGee<https://github.com/AaIiGee> did you rename the phone with QZ to "bike" (only 4 letters) and reboot the phone?
let me know

**Comment by cagnulein** [comment]
Did you see shifting on Qz? If so set the trainer as FTMS bike in the bike
settings and press ok and restart Qz

Let me know

**Comment by AaIiGee** [comment]
No gears, it stays 0 position in the app.

I set trainer as FTMS bike and connected sensors both to "bike" and Kicker core and no shifting.

Anton



Lähetetty laitteesta Galaxy



-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 23.10.2024 16.35 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Mention ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


Did you see shifting on Qz? If so set the trainer as FTMS bike in the bike
settings and press ok and restart Qz

Let me know

**Comment by cagnulein** [comment]
Ok the problem is for sure the gears to 0. Show me fresh debug log while you are trying to change the gears and I will check it!

**Comment by AaIiGee** [comment]
OK and thank you, I'll do that after couple of hours, need to go now...

Anton


-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 23.10.2024 17.10 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Mention ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


Ok the problem is for sure the gears to 0. Show me fresh debug log while you are trying to change the gears and I will check it!

**Comment by AaIiGee** [comment]
Please find attached the file.

Anton


-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 23.10.2024 17.10 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Mention ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


Ok the problem is for sure the gears to 0. Show me fresh debug log while you are trying to change the gears and I will check it!

**Comment by cagnulein** [comment]
I don't see it. Please attach to github web interface in a new comment

**Comment by AaIiGee** [comment]
Another try...

Anton
[debug-Wed_Oct_23_20_49_13_2024.log](https://github.com/user-attachments/files/17496604/debug-Wed_Oct_23_20_49_13_2024.log)

**Comment by cagnulein** [comment]
got the issue! You need the better! Join it from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

and update the app from the store

**Comment by AaIiGee** [comment]
Still no shifting, but a new file... 

[debug-Wed_Oct_23_21_36_19_2024.log](https://github.com/user-attachments/files/17496948/debug-Wed_Oct_23_21_36_19_2024.log)

**Comment by cagnulein** [comment]
The problem here is that I don't see the zwift ride Device. Did you wake it
up before opening QZ? Also, Zwift was closed at that time.
?



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 20:47 AaIiGee ***@***.***> ha
scritto:

**Comment by AaIiGee** [comment]
Yes, it's on before the app startup, but I think it's not pairing with any device as zwift ride controller lights are flashing. However, I can see Zwift ride on phone's bluetooth list. Zwift app is off all the time.

-------- Alkuperäinen viesti --------
Lähettäjä: Roberto Viola ***@***.***>
Päivämäärä: 23.10.2024 21.56 (GMT+02:00)
Saaja: cagnulein/qdomyos-zwift ***@***.***>
Kopio: AaIiGee ***@***.***>, Mention ***@***.***>
Aihe: Re: [cagnulein/qdomyos-zwift] No connection to Wahoo Kicker Core (Issue #2678)


The problem here is that I don't see the zwift ride Device. Did you wake it
up before opening QZ? Also, Zwift was closed at that time.
?



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 20:47 AaIiGee ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hah wait zwift play setting is disabled under accessories, zwift setting!
Enable it and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 21:06 AaIiGee ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno mer 23 ott 2024 alle 21:21 AaIiGee ***@***.***> ha
scritto:
