### ISSUE TITLE
[REQ] filter domyos bike power peaks

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#268]
Could you prevent to broadcast such peaks because no one is be able to get a cadence from 90 to 168 or?

_Originally posted by @mgsimon in https://github.com/cagnulein/qdomyos-zwift/issues/91#issuecomment-818744269_

**Comment by cagnulein** [comment]
which algorithm should i use? i mean on my bike i can go from cadence 60 to 120 in 1 second if i want...so it's very hard to find an algorithm that could achive this without destroy the experience of other users

**Comment by mgsimon** [comment]
maybe with a configurable threshold value because I know that i will never drive with a cadence e.g. > 130 and then accept so high value only if these is recognized more as one time ...

**Comment by cagnulein** [comment]
The log report that strange cadences for 2 seconds. It goes from 137 to 168 also. So if you are agree, i can add a new setting that will allow to do this:

value 0 = filter disabled (default)
value eg. 130 = when the cadence value has a value greater than 130 i will use the last one good value.

Are you ok with this?

**Comment by mgsimon** [comment]
Yes will help to eliminate such wrong peaks in my training sessions!

 As I remember it was also a short cadence break ~1 sec. due to this high values in this training session.

**Comment by cagnulein** [comment]
done. It will be in the 2.6.4
