### ISSUE TITLE
[BUG]Controls not working on mobvoi treadmill plus

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2683]
Impossible to control Mobvoi Home Treadmill Plus

**To Reproduce**
1. Open app it will connect to the treadmill and it will show all the data from it
2. Tap on the the control buttons (speed) and the app will not send the command to the treadmill.

The app reads and receives properly all the data from the treadmill.
The treadmill should change the speed.

- OS: Xiaomi Mi Lite 5G
- Mobvoi Home Treadmill Plus
- Latest published QZ app (no beta)

Log attached.
Thank you.

[debug-Mon_Oct_21_14_21_53_2024.log](https://github.com/user-attachments/files/17460741/debug-Mon_Oct_21_14_21_53_2024.log)

**Comment by cagnulein** [comment]
hi @lorenzogavanna the treadmill doesn't answer me at all to the commands. Do you have any apps that can control the speed by bluetooth?

**Comment by lorenzogavanna** [comment]
> hi @lorenzogavanna the treadmill doesn't answer me at all to the commands. Do you have any apps that can control the speed by bluetooth?

No, no apps for that. I'm sorry.

**Comment by lorenzogavanna** [comment]
> even the manufacturer's one? if so it means that the treadmill doesn't have bluetooth control capabilities unfortuantely. Did you try also Kinomap?

Yes I'm afraid you're right. Didn't think about the Kinomap test. But when I increase the force in kinomap app it doesn't increase the speed on the treadmill. I can connect it as a FTMS treadmill. Thank you.

**Comment by cagnulein** [comment]
sorry to hear this. did you try to contact the manufacturer?

**Comment by lorenzogavanna** [comment]
I wrote them and I will be back to you. In the mean while you can close the bug report I think...It's clearly not an app bug. Thank you!

**Comment by lorenzogavanna** [comment]
Writing here as requested by Roberto on FB:
We decided to close the report because it was not an app bug. But I could control the treadmill speed (it has a fixed incline) with the nRF Connect app by Nordic Semiconductors and Kinni Treadmill Workouts APP. Let me know if you need more info, or maybe I was not setting the qz app properly.

**Comment by lorenzogavanna** [comment]
Writing here as requested by Roberto on FB and please @cagnulein reopen it (i can't directly):
We decided to close the report because it was not an app bug. But I could control the treadmill speed (it has a fixed incline) with the nRF Connect app by Nordic Semiconductors and Kinni Treadmill Workouts APP. Let me know if you need more info.

**Comment by cagnulein** [comment]
@lorenzogavanna on nrfconnect what are you sending to change the speed? so i will do the same in qz

**Comment by lorenzogavanna** [comment]
> @lorenzogavanna on nrfconnect what are you sending to change the speed? so i will do the same in qz
I'm following these steps from the Kinni FTMS check guide page

Controlling speed
Safely start the treadmill manually and set speed to 1 km/hr and incline to 1%
Find the “Fitness Machine Control Point” in the list below “Fitness Machine”
We are now going tell the treadmill to increase the speed to 2 km/hr. Be safe!

Click on the ↑ arrows on the side of the word.
In the input field type called “New value” enter 02C800 and press send

02 – let the treadmill know you are sending it a speed change request
C8 – is hexadecimal for 200 which is 2 km/hr at a resolution of 0.01 km/h
00 – spacer

**Comment by cagnulein** [comment]
ok so you are simply setting the speed, qz is asking control permission before doing this. Ok let me do a patch for this. I will let you know!

**Comment by lorenzogavanna** [comment]
> ok so you are simply setting the speed, qz is asking control permission before doing this. Ok let me do a patch for this. I will let you know!

perfect! I'm also able to control the start with "07" code. In the guide they ask to put 08 code to stop it, this doesn't work, but with the kinni app I can start and stop it without problems. Hope it can be useful.

**Comment by lorenzogavanna** [comment]
It seems to be working perfectly!! I tried to start, stop, change speed +/-, set a PID with hr belt ant+ from the app. Everything worked succesfully. Let me know if you think that I should try something more. Sending you email for the trial unlock. Thank you!

**Comment by cagnulein** [comment]
that's amazing! i'm closing this, let me know if you have any other issues. I'm unlocking the version for you!
