### ISSUE TITLE
[BUG] Raspberry pi no connection via bluetooth

### ISSUE THREAD

**Issue by satchafunkilus** [cagnulein/qdomyos-zwift#2684]
**Describe the bug**
Not possible to connect to qz running on 64bit raspberry pi via bluetooth. Connection via dircon works and bike stats are shown in zwift.

Also not able to connect to qz via nrfconnect.

**Append a debug log**

[debug-Mon_Oct_21_21_01_34_2024.log](https://github.com/user-attachments/files/17466098/debug-Mon_Oct_21_21_01_34_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it
I never test it on a 64 bit arm, so it could be the issue or not

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 21 ott 2024 alle 21:26 satchafunkilus <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i found a small issue on the bluetooth side https://github.com/cagnulein/qdomyos-zwift/actions/runs/11456030967
let's see if it was the issue
try first with nrfconnect. if it doesn't work with it we still have an issue
let me know!

**Comment by satchafunkilus** [comment]
Still not working - both with nrfconnect and Zwift. 
[debug-Tue_Oct_22_18_47_52_2024.log](https://github.com/user-attachments/files/17479653/debug-Tue_Oct_22_18_47_52_2024.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out.
there is something else for sure
the problem is that it will require some time for to test it
i will let you know

Il giorno mar 22 ott 2024 alle 18:52 satchafunkilus <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
can you try if setting the -only-virtualbike setting help? this should just enable the module to bluetooth without connecting to your bike.

Let me know

**Comment by satchafunkilus** [comment]
With this setting i am able to connect via nrf

**Comment by cagnulein** [comment]
Ok that's a great news but also a bad one, means that the raspberry doesn't handling well both Bluetooth connection. Which model is it? I tested successfully with raspberry 3 and 4

**Comment by satchafunkilus** [comment]
Raspberry pi zero 2W

**Comment by cagnulein** [comment]
I guess that’s the issue, the Bluetooth chip is too poor for this. Don’t
you have an higher version?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 18:24 satchafunkilus <
***@***.***> ha scritto:

**Comment by satchafunkilus** [comment]
I have a pi 3 as well. Will test over the weekend if I find some time

**Comment by satchafunkilus** [comment]
So i can confirm it‘s working fine on the raspberry 3. The problem seems to be limited to the raspberry zero 2w.

**Comment by cagnulein** [comment]
That’s great to hear it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 25 ott 2024 alle 21:57 satchafunkilus <
***@***.***> ha scritto:
