### ISSUE TITLE
[REQ]Zwift Cog Virtual Gearing in ERG mode

### ISSUE THREAD

**Issue by ctstdelt9** [cagnulein/qdomyos-zwift#2685]
My log files per this request:
[https://www.reddit.com/r/qdomyos_zwift/comments/1g8m7nv/zwift_cog_virtual_gearing_in_erg_mode/](url)

I used a workout in Zwift and toggled ERG on and off while shifting in-between. 

[https://we.tl/t-sG54p8ejnd](url)

Cheers!

**Comment by cagnulein** [comment]
[btsnoop_hci.zip](https://github.com/user-attachments/files/17470285/btsnoop_hci.zip)
Perfect! This is the file, I will check it later today!

**Comment by cagnulein** [comment]
implemented! I will give it a test tomorrow! Thanks!

**Comment by cagnulein** [comment]
thanks for your help!
