### ISSUE TITLE
[BUG] Elite Justo + Zwift Click

### ISSUE THREAD

**Issue by GumasPL** [cagnulein/qdomyos-zwift#2687]
Hi,
Open QZ app, connect to Elite Justo trainer and Zwift Click. When I start pedaling nothing happens, no values ​​change. Zwift Click remote does not change the load.

Phone: Samsung Galaxy A52s
OS: Android 14

Please help.

**Comment by cagnulein** [comment]
Hi @GumasPL you set your trainer under ftms rower. Set it to disabled and instead set the trainer under ftms bike under the bike section 

Let me know!

**Comment by GumasPL** [comment]
Ok, i set my trainer in bike option and now values change.
Unfortunately zwift click still doesn't work, it doesn't change the gear in QZ app the setting as in the YT video

**Comment by cagnulein** [comment]
In the log that you sent me I don't see the zwift click, did you wake it up
before opening qz with zwift closed?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 22 ott 2024 alle 20:27 GumasPL ***@***.***> ha
scritto:

**Comment by GumasPL** [comment]
Sorry my fault. In accessories I had zwift play selected instead of zwift click. 
I corrected it and the pilot changes gears in the QZ app. I will check in zwift if the load changes and let you know.

**Comment by cagnulein** [comment]
Great! Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 22 ott 2024 alle 22:41 GumasPL ***@***.***> ha
scritto:

**Comment by GumasPL** [comment]
I started the QZ app today, the gears in the app changed without a problem. Then I start Zwift, select the Wahoo trainer and when changing gears nothing happens. I can't see on the screen that the gears are changing, the resistance does not increase.

[debug-Wed_Oct_23_21_23_29_2024.log](https://github.com/user-attachments/files/17497369/debug-Wed_Oct_23_21_23_29_2024.log)

**Comment by cagnulein** [comment]
Did you select qz on all the tiles on zwift? It doesn't seem so, I can't
see any inclination received from zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 21:34 GumasPL ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I mean also the resistance one on zwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 21:38 cagnulein ***@***.***> ha
scritto:

**Comment by GumasPL** [comment]
Yes, i select all tiles on zwift, especialy resistans 🙂

**Comment by cagnulein** [comment]
ok i will deeply check the log tomorrow
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 22:11 GumasPL ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
could you please join the beta
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and update
the app from the store and try again?
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 22:13 cagnulein ***@***.***> ha
scritto:

**Comment by GumasPL** [comment]
I downloaded the beta version.
 I still have the same situation as before. Should I see virtual runs and their changes in zwift?
[debug-Sun_Oct_27_14_44_08_2024.log](https://github.com/user-attachments/files/17534162/debug-Sun_Oct_27_14_44_08_2024.log)

**Comment by cagnulein** [comment]
I can see Qz applying the correct offset, did you try also increasing or
decreasing more the gears? Do you see the variation also when zwift change
the inclination?
In this version you don't have to see the gears on zwift, once solved this
issue I can also invite you in the closed beta for that feature

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle 14:58 GumasPL ***@***.***> ha
scritto:

**Comment by GumasPL** [comment]
Yes the qz app changes gears without a problem. Should I feel an increase in resistance when changing in the qz app?
however now in zwift I can feel that the gears are changing, I just have to think what value to set so that they change by 1 not 0.1. 
If you have a closed beta for visible gear changes , I would be happy to join it 😁

**Comment by cagnulein** [comment]
That's great send me an email to Roberto.viola83 at Gmail.com indicating
this!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle 15:55 GumasPL ***@***.***> ha
scritto:
