### ISSUE TITLE
[BUG] Shows Peloton Login Error 

### ISSUE THREAD

**Issue by phungshum** [cagnulein/qdomyos-zwift#2692]
**Describe the bug**

shows Peloton Login Error - was able to use bike yesterday (Echelon EX-5) with no issues. No password or username changes on Peloton.

**To Reproduce**

**Expected behavior**

Should be able to connect to ride but window does not pop up to do [so](
[debug-Wed_Oct_23_10_08_09_2024.log](https://github.com/user-attachments/files/17495901/debug-Wed_Oct_23_10_08_09_2024.log)
[debug-Wed_Oct_23_10_07_42_2024.log](https://github.com/user-attachments/files/17495902/debug-Wed_Oct_23_10_07_42_2024.log)
[debug-Wed_Oct_23_10_08_09_2024.log](https://github.com/user-attachments/files/17495909/debug-Wed_Oct_23_10_08_09_2024.log)
[debug-Wed_Oct_23_10_07_42_2024.log](https://github.com/user-attachments/files/17495910/debug-Wed_Oct_23_10_07_42_2024.log)
[debug-Wed_Oct_23_10_06_57_2024.log](https://github.com/user-attachments/files/17495911/debug-Wed_Oct_23_10_06_57_2024.log)
[debug-Wed_Oct_23_10_06_57_2024.log](https://github.com/user-attachments/files/17495898/debug-Wed_Oct_23_10_06_57_2024.log))

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9 4th gen
 - OS: iOS 18.0.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Peloton server issue

Wed Oct 23 10:08:11 2024 1729703291158 Debug:
/Users/cagnulein/qdomyos-zwift/src/peloton.cpp void
peloton::workoutlist_onfinish(QNetworkReply *)
"peloton::workoutlist_onfinish Peloton API doesn't answer, trying back in
10 seconds..."


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 23 ott 2024 alle 19:17 phungshum ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Yes, please!


Il giorno mer 23 ott 2024 alle 19:24 phungshum ***@***.***>
ha scritto:

**Comment by phungshum** [comment]
Ok thank you! Will let you know I’ll try again this evening - Shum PhungOn Oct 23, 2024, at 10:32 AM, Roberto Viola ***@***.***> wrote:﻿
Yes, please!





Il giorno mer 23 ott 2024 alle 19:24 phungshum ***@***.***>

ha scritto:
