### ISSUE TITLE
[BUG] Technogym Skillbike not communicating w/ Zwift

### ISSUE THREAD

**Issue by hobermanj** [cagnulein/qdomyos-zwift#2699]
Zwift is not registering my cycling input on my Skillbike. QZ is not registering my cycling input Zwift not getting my Cadence, Power, etc.

**To Reproduce**
1. Open qz on iPhone. 
2. Skillbike connects to qz
3. Open Zwift on iPad and login
4. Zwift connects to “Phone” (qz) on all sensors
5. Select Volcano Circuit
6. Once avatar appears on the cycling course, I begin to pedal on the Skillbike.
7. Qz is not registering any stats from my Skillbike so in turn Zwift is not getting the sensors input so watts remain at 0.

**Expected behavior**
I want to have a seamless connection between the Skillbike/qz and iPad/Zwift.

Zwift on iPad
 - Device: iPad
 - OS: iOS 18.0.1

QZ on iPhone
 - Device: iPhone XS 
 - OS: iOS 17.6.1

debug log appended below:

[debug-Fri_Oct_25_17_55_35_2024.log](https://github.com/user-attachments/files/17528234/debug-Fri_Oct_25_17_55_35_2024.log)

**Comment by cagnulein** [comment]
Hi! In this log the bike is not in range. Do you have other debug log in
the folder?
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 26 ott 2024 alle 01:36 hobermanj ***@***.***>
ha scritto:

**Comment by hobermanj** [comment]
The iphone that is running qz is right on top of the bike. I understand
that it appears the bike is not in range which is confusing to me because
of how physically near the iphone and the bike are to each other. I will
add a photo showing that the bike is connected.

**Comment by cagnulein** [comment]
What I mean is that in particularog the bike was not in range. Maybe you have other logs

**Comment by hobermanj** [comment]
[
![IMG_5247](https://github.com/user-attachments/assets/d9f05cfa-e3c4-4ab3-b16c-4d9e65fc0d5f)
](url)

**Comment by hobermanj** [comment]
I will look for other logs right now.  Are you looking for a .fit file or a .txt file?

**Comment by cagnulein** [comment]
They are the log with the prefix debug in the name as you previously uploaded

**Comment by cagnulein** [comment]
@hobermanj any news?
