### ISSUE TITLE
[REQ] Peloton cadence and Resistance graph

### ISSUE THREAD

**Issue by markonline1** [cagnulein/qdomyos-zwift#270]
I don’t know whether this would be possible....... for the peloton users, would it be possible to activate both a cadence and (peloton) resistance graph that overlays the peloton graphs that determine the cadence and resistance of the class? So the end result would show your cadence in relation to what the cadence was programmed into the class, and then the same with resistance? Thanks.

**Comment by cagnulein** [comment]
Yes sure!

Il ven 16 apr 2021, 00:15 markonline1 ***@***.***> ha scritto:

**Comment by markonline1** [comment]
That would be awesome. I saw it after I did a ride on an actual peloton bike and it’s great to see where you were throughout the class in comparison to where you were supposed to be if you were following the coach’s calls. 

Thanks

**Comment by cagnulein** [comment]
@markonline1 are you ok with the current implementation?

**Comment by markonline1** [comment]
Yep, it’s a welcome addition.
