### ISSUE TITLE
[REQ] Add support for Nordictrack Elite 900

### ISSUE THREAD

**Issue by prabirsekhri** [cagnulein/qdomyos-zwift#2700]
**Is your feature request related to a problem? Please describe.** 
Firstly the app is a game changer. I am able to get speed and incline data from my Treadmill. 

**Describe the solution you'd like**
I am unable to control the treadmill from the app. I see that when I click on incline from the app, it does something on the tablet but doesn't change the incline. I am guessing the tablet needs to be mapped. 

**Describe alternatives you've considered**
I have tried experimenting with different treadmill settings on the qz companion app and they all successfully transmit data to the app but I can't get the app to control the treadmill. 

**Additional context**
I would ideally like Zwift to control my treadmill. I have already signed in to Zwift on the app and I see that when I start the workout, the app is trying to send instructions to the treadmill but it doesn't change the speed or the inclination. I am happy to provide any logs that you may require to help support my treadmill. I see that couple of other people in the past have raised issues regarding this treadmill. Luckily, I don't have any issues with connectivity but just want the app to control the treadmill. Thanks!

**Comment by prabirsekhri** [comment]
Here are the logs and a screenshot from ABP just in case. 
![2024-10-26@19-33-04 16](https://github.com/user-attachments/assets/81451286-762b-4141-90e6-87434f52aac2)
[logs.zip](https://github.com/user-attachments/files/17532279/logs.zip)

**Comment by cagnulein** [comment]
Perfect! I will add it ASAP! Just a question : when you try to use the inclination or speed plus and minus buttons on qz, do you see a reaction on the treadmill side?

**Comment by prabirsekhri** [comment]
> Perfect! I will add it ASAP! Just a question : when you try to use the inclination or speed plus and minus buttons on qz, do you see a reaction on the treadmill side?

Thanks a lot for the quick reply! When I try the incline, there is a reaction on the treadmill's tablet similar to random touch strokes on the screen but no changes to the incline. The speed button doesn't do anything.

**Comment by cagnulein** [comment]
Ok that's perfect, this means that I have only add the coordinates of your
treadmill. I will do tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle 10:08 Prabir Sekhri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i created a new apk version https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.5.3/QZCompanionNordictrackTreadmill.apk
set the elite 900 device in the companion and restart the treadmill
let me know!

**Comment by prabirsekhri** [comment]
I tried with the new package and unfortunately I couldn't get the app to control the treadmill. The touch strokes aren't working either. However, The app displays the speed and incline correctly as before. I have tried setting the treadmill on the mobile app as S25 and also tried with couple of other treadmill options randomly. Is there something that I should try to troubleshoot this further on my end? PS :I haven't tried try to run Zwift yet with the new package as I assume that getting the app to control the treadmill is a prerequisite for Zwift to work? 

Thanks for your help once again!

**Comment by cagnulein** [comment]
But did you see the touch strokes as before? You should see them now in the
inclination and speed slider area
You can enable the touch shadow setting in the android developer setting on
your tablet to see them better
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 28 ott 2024 alle 22:39 Prabir Sekhri ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
Ok, I'll check it out.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 29 ott 2024 alle ore 12:29 Prabir Sekhri <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i don't see any particular differences between the elite 900 profile and
the c1750 2020 kph except the coordinates.
Are you able to collect an adb logcat from the treadmill while are
you trying to change the speed or inclination from qz? so i will check why
it's not working
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 29 ott 2024 alle ore 12:30 cagnulein ***@***.***> ha
scritto:

**Comment by prabirsekhri** [comment]
Yes I can do that later today and send it to you! Thanks for your help again!

**Comment by prabirsekhri** [comment]
Hello, Good news is that when I tried to switch between the treadmill settings and selected Elite 900, I got the speed to work from the mobile app. The incline is not working however. 

Here are the logs : 

[logcat.log](https://github.com/user-attachments/files/17564140/logcat.log)
[logcat.txt](https://github.com/user-attachments/files/17564141/logcat.txt)

Initially around timestamp 10-29 19:15 onwards, I had the treadmill set to the C1750. I tried the incline button to which the treadmill was reacting by opening the pause workout pop window. Later around 0-29 19:18 I toggled it to Elite 900 and tested the speed and it is working absolutely fine. 

Lastly, I also touched the screen manually around 10-29 19:22 to simulate the coordinates if the appear in the logs. 

Let me know if you need more info. Thanks for helping out once again!

**Comment by prabirsekhri** [comment]
Another update is that I tried a workout with Zwift and it did not change the speed but it randomly changed the incline on the treadmill during the workout. I have my treadmill settings set auto workout

**Comment by cagnulein** [comment]
log checked, i saw the speed working! the inclination is not working because the request from qz to change the incliantion is to set it to 0 but it was already at 0. did you press the plus button the inclination tile on qz? if so can you try to set the settings in qz "Inclination Step:" in the treadmill section from 0.5 to 1 and press ok and try again?
Thanks

**Comment by prabirsekhri** [comment]
It works when I set the incline to 1! but no response when I set go 0.5. The treadmill does support incline in 0.5 increments but honestly it doesn't bother me at all since Zwift's increments are not in 0.5. Thanks a lot! Another behaviour why the app didn't work initially is that I need to toggle between treadmills to get the companion app to recognize the commands. It's like the app stops listening even though it is running in the background. 
Lastly, I want to understand if Zwift's speed and incline is supported on iOS? According to the app description, I must run QZ app and the Zwift app on the same computer to get it to work but I wasn't sure from your release notes. ![image](https://github.com/user-attachments/assets/5ce81cc9-893c-4646-af26-cc1cf6d79bd3)

**Comment by cagnulein** [comment]
That's great! Check this for auto speed and auto inclination on zwift https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F

Let me know if something is unclear

**Comment by prabirsekhri** [comment]
It's very clear! Do you have any plans to add support for Mac too to support auto incline? I see instructions for windows and iOS/Android

**Comment by cagnulein** [comment]
it's based on pyhton so it's doable but you are the first one asking this :)
the problem of the mac version is that it's based on ios on mac with apple silicon so it could be a pain.
Any chance you can use a virtual machine on the mac with windows 10?

**Comment by prabirsekhri** [comment]
Yeah I should be able to run it on a VM. 
I will test it on the Mac and let you know nonetheless. Thanks once again! This really helps!

**Comment by cagnulein** [comment]
@victorypoint is the mind behind all of this nordictreadmill hack :)

**Comment by prabirsekhri** [comment]
@victorypoint thanks for the help!

**Comment by prabirsekhri** [comment]
@victorypoint @cagnulein wondering if you guys came across a workout parsar that downloads zwo files of Zwift running workouts? @victorypoint I see that you logged an issue in one of the projects but wondering if you came across a project like that which works?

**Comment by cagnulein** [comment]
@prabirsekhri  check this 
[out.zip](https://github.com/user-attachments/files/17581394/out.zip)

**Comment by prabirsekhri** [comment]
Super cool! you are the man! 😎

**Comment by cagnulein** [comment]
@prabirsekhri please remember to rate the app on the store if you didn't already, it means a lot to me! thanks!

**Comment by prabirsekhri** [comment]
@cagnulein I thought I did in the past but I just submitted another one! thanks a lot for helping out! You are doing the community a great favour!

**Comment by prabirsekhri** [comment]
out of curiosity, how did you pull the whatsonzwift.com workouts?

**Comment by cagnulein** [comment]
@p3g4asus helped us with some code, i guess i still have it

**Comment by prabirsekhri** [comment]
great! thanks again! I will close this enhancement request. Cheers!
