### ISSUE TITLE
[BUG] gears increased but torque / resistance remains the same 

### ISSUE THREAD

**Issue by 66David6** [cagnulein/qdomyos-zwift#2702]
**Describe the bug**
I followed the instructions of your YouTube video in the quaintness beta version. Further I added the forms bike setting. Gears are shifting in the dashboard, but the Zwift hub remains the same torque all time.

**To Reproduce**

**Expected behavior**
Expected increasing torque 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 18]
 - Version [e

**Smartphone (please complete the following information):**
 -
 - OS: [e.g. iOS 18.0.1]
[debug-So__Okt__27_10_24_23_2024.log](https://github.com/user-attachments/files/17533385/debug-So__Okt__27_10_24_23_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Are you trying only with qz standalone? Did you try also with rouvy or
mywhoosh or indievelo?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 27 ott 2024 alle 10:35 66David6 ***@***.***> ha
scritto:

**Comment by 66David6** [comment]
Hi,

I guess I found the error. In mywhoosh it now works.
