### ISSUE TITLE
Zwift Erg with Gears from Zwift enabled

### ISSUE THREAD

**Issue by gianmarcodamb** [cagnulein/qdomyos-zwift#2708]
[debug-lun_ott_28_10_48_48_2024.log](https://github.com/user-attachments/files/17540624/debug-lun_ott_28_10_48_48_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@gianmarcodamb any news?
