### ISSUE TITLE
[BUG]Keiser M3i Heart Rate is Erratic

### ISSUE THREAD

**Issue by Mjconroy3** [cagnulein/qdomyos-zwift#2711]
Using a Polar H10 (which pairs and works fine with my treadmill and erg), I get very erratic heart rate readings.
Readings can drop to 0 and go into the 200s.

Doesn't matter if I turn off getting the heart rate from the bike - the app and the bike monitor give me the same erratic readings.

[debug-Tue_Oct_29_18_18_52_2024.log](https://github.com/user-attachments/files/17564411/debug-Tue_Oct_29_18_18_52_2024.log)

 
Using a Samsung Galaxy S24  running Android 14.

[debug-Tue_Oct_29_18_18_52_2024.log](https://github.com/user-attachments/files/17564410/debug-Tue_Oct_29_18_18_52_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks I will check it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 30 ott 2024 alle 01:23 Mjconroy3 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fixed!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/11589582113
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/actions/runs/11589582113/artifacts/2121911108 @Mjconroy3

**Comment by Mjconroy3** [comment]
Grazie!
I will check it out.

**Comment by cagnulein** [comment]
Glad to hear it!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 31 ott 2024 alle ore 16:01 Mjconroy3 ***@***.***>
ha scritto:

**Comment by Mjconroy3** [comment]
Now I am puzzled. I just went to try a longer test and I don;t get past the startup screen- 
QZ says it has found the H10 and the bike and the bluetooth icon is flashing, but I get no tiles. 
I checked bluetooth settings and all is well. 
I restarted the phone and that did not help. 
When I end the session it shows no data.

Meanwhile, the native heart rate readings on the bike seem more stable, but how can that be???

**Comment by Mjconroy3** [comment]
I am getting an error message - "Bluetooth name too long, change it to a 4 letters one in the android settings"
Not clear what needs to be renamed or how.

**Comment by cagnulein** [comment]
> I am getting an error message - "Bluetooth name too long, change it to a 4 letters one in the android settings"
> 
> Not clear what needs to be renamed or how.

This is just a hint because on zwift you can have issue with a longer name

Do you see your bike with the free app nrfconnect? Did you try to reboot the bike?

**Comment by Mjconroy3** [comment]
I don't use Zwift. Don't see how I would reboot the Keiser M3i unless I
open the monitor and take out the batteries.

**Comment by cagnulein** [comment]
So don't mind at that popup. Check if the nrfconnect sees your bike
I guess there is some issue on the Bluetooth side of the bike

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 11:56 Mjconroy3 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Yes I read it and that's why I said to check nrfconnect because if qz can't
find the bike it seems that the bike is not sending data anymore. Check
with the nrfconnect app if you can see the bike so we know that at least
the bike is working

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 16:10 Mjconroy3 ***@***.***> ha
scritto:

**Comment by Mjconroy3** [comment]
Okay. I downloaded and installed NRFconnect. It sees the bike.
QZ seems to see the bike too, I just get stuck on the opening screen with the bluetooth icon flashing.

**Comment by cagnulein** [comment]
Is the manual device under the accessories settings set to disabled?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 16:47 Mjconroy3 ***@***.***> ha
scritto:

**Comment by Mjconroy3** [comment]
Well, I  uninstalled the test version, reinstalled it and it now seems to working okay.
Heart rate readings look accurate! You rock!
But they also look accurate on the bike's (M3i) screen for the first time ever. How? How can your app change do that???

**Comment by cagnulein** [comment]
I guess it's because the bike is connected to qz for hr :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 18:28 Mjconroy3 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Yes send me an email mentioning it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 18:32 Mjconroy3 ***@***.***> ha
scritto:

**Comment by Mjconroy3** [comment]
Roberto,
Okay, please remove the 15 minute time limit on this version.
Many thanks!

**Comment by cagnulein** [comment]
You have to send me to my email not on github otherwise I can't see your
email address  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 19:34 Mjconroy3 ***@***.***> ha
scritto:

**Comment by Mjconroy3** [comment]
This was from Gmail.
***@***.***

**Comment by cagnulein** [comment]
Yes but the destination is not my email is github :) set the destination to
my email :) otherwise I can't see it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle 19:55 Mjconroy3 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Mjconroy3 are we ok with this?
