### ISSUE TITLE
[BUG] random gear change

### ISSUE THREAD

**Issue by camkspencer** [cagnulein/qdomyos-zwift#2714]
Was able to have it recreate the problem once at the end of the ride. Gears will bounce randomly either up or down generally on inclines or declines. Volume debouncing is on

**Comment by cagnulein** [comment]
sorry @camkspencer but the log is unreadable, please attach it as a attachment not in the text field
thanks

**Comment by camkspencer** [comment]
Anyway I can change the format of the file? When I tried to upload it,
GitHub said it doesn't support the file

**Comment by cagnulein** [comment]
compress it before upload it

**Comment by camkspencer** [comment]
Is it ok if I send it over email? For some reason, even with it compressed
I can't select anything for GitHub to attach

**Comment by cagnulein** [comment]
yes send me by email and i will upload it

**Comment by camkspencer** [comment]
Thank you
