### ISSUE TITLE
[BUG] App crashes when attempting to connect to Kingsmith X21

### ISSUE THREAD

**Issue by LinziBligh** [cagnulein/qdomyos-zwift#2717]
**Describe the bug**

After selecting Kingsmith X21 in treadmill setting and being prompted to restart app, app attempts to connect to treadmill and I see a flash of the tiles, the apps then crashes and closes

**To Reproduce**
1. Open app after selecting kingsmith X21
2. It crashes

**Expected behavior**

I expected it to show the tiles with the data from my treadmill

**Screenshots**

![IMG_2676](https://github.com/user-attachments/assets/3bb6f82a-5d1e-4d8b-b448-f181b33b69b2)

this displays for about half a second before it crashes and close the app

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 12 Pro Max
 - OS: [e.g. iOS8.1] 17.6.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
[debug-Wed_Oct_30_20_33_04_2024.log](https://github.com/user-attachments/files/17578844/debug-Wed_Oct_30_20_33_04_2024.log)

  
**Additional context**

Hoping to connect to Peloton app on iPad. Could have all three apps on there together (king smith, qz, and peloton but currently king smith and qz are on phone, peloton on iPad)

**Comment by cagnulein** [comment]
@LinziBligh Good news! I guess I already fixed it here https://github.com/cagnulein/qdomyos-zwift/commit/88ba9563adf1a4a499f9a88d735b79efaa6021ab


send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks
