### ISSUE TITLE
[REQ] Improvements made for Proform 705 CST support

### ISSUE THREAD

**Issue by Novamusix** [cagnulein/qdomyos-zwift#2719]
I've been using QZ on both Android and a Raspberry Pi to control the Proform 705 CST treadmill. You kindly updated QZ to accommodate the latest firmware update https://github.com/cagnulein/qdomyos-zwift/issues/2430

One major issue was that I needed to manually start the treadmill before connecting QZ; otherwise, the treadmill would lock out and not respond to the start button on the console or set speed requests from apps.

After lots of trial and error and monitoring bluetooth sequences sent from iFit app, I've made some updates to the `proformtreadmill.cpp` source code which looks to help address this:

- **App-Controlled Start:** If the treadmill is not running and ready to start, when an app sends a request to set the speed, an initiate start command sequence is sent. This defaults to 2 kph with an incline of 1, followed by setting the requested speed and incline. This works fantastically with Runna. `(Line changes on 338-339, 382, 838-930)`
- **Console-Controlled Start:** If the treadmill is not running and ready to start, pressing the Start button on the console will trigger QZ to send an initiate start command sequence of 2 kph with an incline of 1. This is perfect for other family members who are not using an app.` (Line changes on 2159-2169)`

It may be that this will work with other Proform models with updated firmware, but I cannot check this.

I've attached my updates using the latest `proformtreadmill.cpp` , 
[proformtreadmill.zip](https://github.com/user-attachments/files/17591802/proformtreadmill.zip)
which successfully compiled and is running on the RPi. Unfortunately I have no experience with pull requests so I hope attaching is ok.

**Comment by cagnulein** [comment]
Thank you I will check the code and I will do a pull request for you

**Comment by cagnulein** [comment]
i created it and i added some comments https://github.com/cagnulein/qdomyos-zwift/pull/2723 
Let me know
