### ISSUE TITLE
[Bug] Offset settings issue for Domyos bike

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#272]
Hi @cagnulein , 
Offset settings doesn't work for my domyos bike.
I changed the offset value on settings to 2, I pushed to the Ok button and restart the app. But when I'm on zwift the Offset value seems to still at 4.
I don't have a log file, if you need I can make a new session if it could help you :)

Thanks 😄

**Comment by cagnulein** [comment]
on android or in the raspberry? i fixed it in the beta on android

**Comment by kenands** [comment]
On android. Ok I will try again and will inform you :)

Le ven. 16 avr. 2021 à 11:42, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
fixed! it will be in the 2.4.6!
