### ISSUE TITLE
[BUG] Can only shift up and not down with Zwift Ride

### ISSUE THREAD

**Issue by slovelo** [cagnulein/qdomyos-zwift#2721]
**Describe the bug**
With a new Zwift Ride, I am able to shift up (right controller) in QZ but not down (using left controller). 

**To Reproduce**
1. Turn on Kickr Core, then Zwift Ride controllees then open QZ
2. Click on left controller shifting button

**Expected behavior**
Shift down gears.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23
 - OS: Android
 - Version 14

**Append a debug log**

[debug-Thu_Oct_31_17_36_18_2024.log](https://github.com/user-attachments/files/17594092/debug-Thu_Oct_31_17_36_18_2024.log)
  
  
**Additional context**
Latest beta QZ, latest Kickr Core firmware, latest Zwift Ride controller firmware, no other software paired via Bluetooth

Note: When gears are shifted up from zero to 24, there is no resistance change to the trainer. Not sure if that is expected

**Comment by cagnulein** [comment]
Hi @slovelo unfortunately the log is truncated. Can you please send it again, remember to close qz before sending me it
Let me know

**Comment by cagnulein** [comment]
@slovelo any news?
