### ISSUE TITLE
[BUG] QZ inclination is different from Zwift

### ISSUE THREAD

**Issue by rafaelmartinsrm** [cagnulein/qdomyos-zwift#2722]
**Describe the bug**
Noticed that on some climbs, QZ inclination is higher than Zwift's. I tried using gain to 0.5 but it didn't help

**To Reproduce**
When climbing, compare QZ inclination values with Zwift screen.

**Expected behavior**
Have the same approximate value on QZ inclination as Zwift.

**Screenshots**
<img src="https://github.com/user-attachments/assets/ee279262-045a-473a-9be2-4c1e7659da78" width="100"/>
At this place I am stopped at a 9% climb in Zwift.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: motorola edge 40 neo
 - OS: Android
 - Version 14

**Append a debug log**
[debug-Fri_Nov_1_10_01_17_2024.log](https://github.com/user-attachments/files/17599917/debug-Fri_Nov_1_10_01_17_2024.log)

  
  
**Additional context**
It could be just wrong setting somewhere, but I was not able to identify.

**Comment by cagnulein** [comment]
I still see 1 in the inclination gain. It's this under advanced settings 

![image](https://github.com/user-attachments/assets/eff3161f-f21d-4897-b9fc-1de261ad1d60)

Set 0.5 here

**Comment by rafaelmartinsrm** [comment]
@cagnulein Changing to 0.5 under 'Advanced Settings' as shown on image worked. The mistake was that I did change 'Threadmill Options > Inclination Overrides > Inclination Override Gain' instead.

**Comment by cagnulein** [comment]
that's great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 1 nov 2024 alle ore 14:40 Rafael Martins <
***@***.***> ha scritto:
