### ISSUE TITLE
[REQ]Add one more treadmill in the compatible list

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2725]
Of course it's not urgent at all. I have a very old cuscar treadmill that was working with his app Gfit by [FutureGo Inc](https://apkpure.net/it/developer/FutureGo%20Inc) at the moment the app is not working anymore, in that way the treadmill is usable only with the proprietary remote. I tried to connect QZ to the treadmill and it connects automatically, you can change the speed with i.e. speed defined tiles, but you cannot change the speed with the speed tiles +/- btns.

I would like to use it with all the scenary that QZ gives you when is fully working. I'm sure the genious of Roberto can do it easely.

Of course I understand this is an edge case that could bring the time away from more important things, but it's just a try.

Sending you the debug file I created while I was trying to control the treadmil with QZ.
Let me know if you need more information.
Thank you for all the hard work!

[debug-Fri_Nov_1_17_03_53_2024.log](https://github.com/user-attachments/files/17602419/debug-Fri_Nov_1_17_03_53_2024.log)

**Comment by cagnulein** [comment]
@lorenzogavanna Can you try to enable 

![image](https://github.com/user-attachments/assets/eaaf18b6-aced-455a-ada2-5cdd15b150e2)

On of these (one at a time) and restart qz

Let me know

**Comment by lorenzogavanna** [comment]
Ciao Roberto! It works perfectly! Thank you for the Quick reply5 and sorry for the late feedback... All the best!

**Comment by cagnulein** [comment]
Amazing!
