### ISSUE TITLE
[BUG] QZ does not detect Echelon EX-5 Bike or any other bluetooth devices

### ISSUE THREAD

**Issue by Alpndb** [cagnulein/qdomyos-zwift#2728]
I have the QZ app on my phone (S24+) and the Echelon EX-5 will be detected immediately without fail.

I installed the QZ app on my Samsung S9FE and it does not detect the bike nor does it detect any other bluetooth devices. On the phone, the app usually cycles through some other BT device before it sees the bike and connects automatically.

I have re-installed the app on the tablet and enabled all permissions include notifications and precise location. Tablet has been power cycled and the bluetooth on the devices does detect the bike.

**To Reproduce**
Turn on app, doesn't see any BT devices include bike

Problem is on a Samsung Tablet S9FE running Android 14, One UI 6.1.1

Debug attached.
[debug-Sat_Nov_2_23_31_14_2024.log](https://github.com/user-attachments/files/17609613/debug-Sat_Nov_2_23_31_14_2024.log)

**Comment by cagnulein** [comment]
hi @Alpndb the problem is  "Search not possible due to turned off Location service"

does the tablet has gps? i guess that's why it's complaining. you can use a fake gps app on the play store to fake this in case. unfortunately it's a google policy requirements to find nearby devices
let me know

**Comment by Alpndb** [comment]
> hi @Alpndb the problem is "Search not possible due to turned off Location service"
> 
> does the tablet has gps? i guess that's why it's complaining. you can use a fake gps app on the play store to fake this in case. unfortunately it's a google policy requirements to find nearby devices let me know

Oh man. You are just the best. I didn't activate the GPS for the tablet for privacy reasons as it never leaves the house.

Your recommendation solved the problem. Thank you so much for your help, your app, and the fantastic support you give this community.

**Comment by Alpndb** [comment]
Solved.

**Comment by cagnulein** [comment]
That's great! Please remember to rate the app on the store! It means a lot to me!
Thanks!
