### ISSUE TITLE
[BUG] Zwift Ride shifting doesn’t work properly in combination with Rouvy App

### ISSUE THREAD

**Issue by RiDDLER1907** [cagnulein/qdomyos-zwift#2729]
[debug-So__Nov__3_11_49_29_2024.log](https://github.com/user-attachments/files/17610158/debug-So__Nov__3_11_49_29_2024.log)
Reproduce**

**Expected behavior**
The shifting with Zwift Ride in Rouvy is reacting but the resistance doesn’t stay at the level I shifted too. Nearly immediately the resisistance is going up again.  

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 18.1
 - Version 22B83

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @RiDDLER1907 I don't see the debug log. Attach it please

**Comment by cagnulein** [comment]
@RiDDLER1907 Any news?

**Comment by RiDDLER1907** [comment]
Hi Roberto! I attached the debug log, today I ran another try but it had the same outcome. The problem was described by some more users in the Facebook group. the resistance rises short time after shifting down.

Thank you and regards

[debug-Do__Nov__28_22_18_37_2024.log](https://github.com/user-attachments/files/17952520/debug-Do__Nov__28_22_18_37_2024.log)

**Comment by cagnulein** [comment]
I would like to send you the latest beta. I already fixed this
Send me your icloud email to Roberto.viola83 at Gmail.com
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle 23:02 RiDDLER1907 ***@***.***>
ha scritto:

**Comment by RiDDLER1907** [comment]
Thank you very much for your support and all the effort you put in this 👍🏼😊
Is an iCloud address necessary or does it work with an ordninary gmx adress too? 

Regards!

**Comment by cagnulein** [comment]
It must be the email address registered to your phone
