### ISSUE TITLE
[BUG] Zwift can't find my heart rate belt through QZ app with domyos bike 500

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#273]
Hi @cagnulein ,

**Describe the bug**
My heart rate belt (bluetouth) it recognized and works well on QZ app and on my domyos bike 500 console, but zwift can't find it.
I tried with changing the setting "Heart Rate service outside FTMS", but when I pushed it to off and restart the app it become again to on.

The same heart rate works perfectly when I use it with my domyos treadmill through QZ app, and zwift able to find it.

**Expected behavior**
Zwift able to find my heart rate through QZ app when I use my bike

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 
**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 10
 - Version: 10 QKQ1.190825.002

**Additional context**
Dectahlon bluetouth heart rate belt

Thanks !

**Comment by cagnulein** [comment]
yes because android 10 can't allow more than 1 service on bluetooth and zwift can't read heart rate from ftms. 
So bug of google and zwift, not QZ itself :)

**Comment by cagnulein** [comment]
you should try with android 9 or lower

**Comment by kenands** [comment]
But it works with the treadmill, QZ app dosen't use two services in this case ?

**Comment by cagnulein** [comment]
on your treadmill it works with Heart ftms ON? isn't it? i guess zwift treat ftms bytes in different way if you're running a treadmill or a bike

**Comment by kenands** [comment]
Yes you're right it works with ftms ON, anyway I can't disable this settings on QZ app.
From wich version of android QZ app works (the oldest one) because I have just an very old android device beside my main phone.

**Comment by cagnulein** [comment]
yes you can't disable because i force it to ON if you have android > 9.
I guess the oldest one is android 6

**Comment by cagnulein** [comment]
i'm closing this, just because it's not a QZ bug, but feel free to continue here to keep me posted

**Comment by kenands** [comment]
No problem many thanks for your help :)
I know if it was Qz bug you will reslove it faster than your shadow lol

My old phone is on android 7, I will try with it :)

![IMG_20210416_122006](https://user-images.githubusercontent.com/16349940/115011634-27da1080-9eaf-11eb-9e17-30afd7ea2368.jpg)
