### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Geide88** [cagnulein/qdomyos-zwift#2730]
[debug-So__Nov__3_15_29_14_2024.log](https://github.com/user-attachments/files/17610778/debug-So__Nov__3_15_29_14_2024.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Geide88 You have to enable this

![image](https://github.com/user-attachments/assets/00356381-465a-4825-a4e7-758087a12138)

**Comment by Geide88** [comment]
Which order is this?Von einem Handtelefon aus gesendet. Am 03.11.2024 um 15:51 schrieb Roberto Viola ***@***.***>:﻿
@Geide88 You have to enable this
Upload.from.GitHub.for.iOS.png (view on web)

**Comment by cagnulein** [comment]
Whatever the order is just where you see the tile. You can put even 0
I'm driving now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 3 nov 2024 alle 16:01 Geide88 ***@***.***> ha
scritto:
