### ISSUE TITLE
[BUG]bug unevenness not fair gpx

### ISSUE THREAD

**Issue by toto811** [cagnulein/qdomyos-zwift#2733]
gpx problem
I don't know if I made the links correctly..:/
[debug-Mon_Nov_4_12_31_02_2024[1].log](https://github.com/user-attachments/files/17617934/debug-Mon_Nov_4_12_31_02_2024.1.log)

[0QZ-backup-lun._nov._4_12_31_59_2024[1].zip](https://github.com/user-attachments/files/17617860/0QZ-backup-lun._nov._4_12_31_59_2024.1.zip)

**Comment by toto811** [comment]
I don't know if it's good?
lun._nov._4_14_45_28_2024[1].zip](https://github.com/user-attachments/files/17619081/lun._nov._4_14_45_28_2024.1.zip)
I tried for 10 minutes, the altitude difference is wrong for example the route is 300 real altitude difference on qz know written 650

**Comment by cagnulein** [comment]
no i mean the gpx file that you are importing in qz. Sortie_Route_dans_l_après_midi.gpx

**Comment by toto811** [comment]
forget it it doesn't matter thank you you can close the subject!

**Comment by cagnulein** [comment]
why? i can help you! i just need the files

**Comment by toto811** [comment]
the original gpx file not in qz? I don't know how to send it since I know about gpx

**Comment by cagnulein** [comment]
simply zip it and attach it here :)
also i need a debug log with the error becaue in the first one that you sent me the session was only of 50 seconds

**Comment by toto811** [comment]
I can't find the file that I created in 10 minutes

**Comment by toto811** [comment]
I don't know if it's still the right file : [debug-Mon_Nov_4_15_15_01_2024[1].zip](https://github.com/user-attachments/files/17621758/debug-Mon_Nov_4_15_15_01_2024.1.zip)
[Sortie_vtt_dans_l_après_midi.zip](https://github.com/user-attachments/files/17621762/Sortie_vtt_dans_l_apres_midi.zip)

**Comment by cagnulein** [comment]
The gpx is OK.but the log must be much larger than this one with a workout.
Send me them all so I can pick up the right one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 18:25 toto811 ***@***.***> ha
scritto:

**Comment by toto811** [comment]
I will stay this evening, I have already sent everything

!

**Comment by cagnulein** [comment]
Ok let me know! I need a debug log to understand your issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 18:41 toto811 ***@***.***> ha
scritto:

**Comment by toto811** [comment]
I only tried 2 minutes to see if it works, and also the orange logo does not follow the line of the course often it moves next to the line
[1QZ-backup-lun._nov._4_19_00_57_2024[1].zip](https://github.com/user-attachments/files/17622227/1QZ-backup-lun._nov._4_19_00_57_2024.1.zip)
[debug-Mon_Nov_4_19_00_55_2024[1].log](https://github.com/user-attachments/files/17622253/debug-Mon_Nov_4_19_00_55_2024.1.log)

**Comment by cagnulein** [comment]
Thank you I will check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 19:12 toto811 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I'm seeing it correctly https://github.com/user-attachments/assets/930a19e4-b934-48ef-8be5-b502f01c598d

Do you see the same?

**Comment by toto811** [comment]
so no on my side the orange dot advances every 5 seconds and not continuously like in the video! and its sort of red line too!

**Comment by cagnulein** [comment]
Which android device is it? I guess you have some issue on the performance?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 19:22 toto811 ***@***.***> ha
scritto:

**Comment by toto811** [comment]
note 8 pro xiaomi I tried another one it's the same translation

**Comment by cagnulein** [comment]
I will check later this week your log
And I will let you know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 19:25 toto811 ***@***.***> ha
scritto:

**Comment by toto811** [comment]
ok no worries thank you. If you want I can send a video here to see the problem?

**Comment by cagnulein** [comment]
Yes please

**Comment by toto811** [comment]
https://github.com/user-attachments/assets/013df298-bba0-44e8-b580-b894f0d93011

**Comment by cagnulein** [comment]
There is a missing step here in the video: you didn't press pause and play
to engage the fox

Let me know!

**Comment by toto811** [comment]
it changes nothing..I also tried to take a non-exporting route created by qz even chose its bug it advances every 5 seconds and sideways :(

**Comment by cagnulein** [comment]
I checked also my pixel 6a and it's perfect. I will check your log if there is some issues

**Comment by cagnulein** [comment]
fixed! it was about this particular bike version

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11683414034

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by toto811** [comment]
hi, great! I would like to test it right away! Where should I download?

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/actions/runs/11683414034/artifacts/2146326011

**Comment by toto811** [comment]
Much better like the video you sent me yesterday! on the other hand, when increasing the percentage my speed increases instead of decreasing?

**Comment by cagnulein** [comment]
Do you have a log of this?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 17:33 toto811 ***@***.***> ha
scritto:

**Comment by toto811** [comment]
today I will do this

**Comment by toto811** [comment]
Hi Roberto, the speed problem is caused by my bike and not by qz..on the other hand, your version that you sent me works well! but like I said I'm going to buy another exercise bike👍

**Comment by toto811** [comment]
when I press the + button of the resistance with the domyos 500 the speed increases for example resistance 15 I am at the speed of around 40 but I feel the resistance.. even without connection the bike does this I increase the resistance and the speed of the bike computer increases the rpm is good on the other hand

**Comment by cagnulein** [comment]
did you use the speed based on power setting in the bike settings?

**Comment by cagnulein** [comment]
give it a try, it will fix your issue

**Comment by toto811** [comment]
I'm going to try where is the option?

**Comment by cagnulein** [comment]
> I'm going to try where is the option I think I found the option I'm testin

bike options in qz



> Is the option the speed calculated according to the power?

yes so it will be more realistic

**Comment by toto811** [comment]
t doesn't work don't worry my bike has always had problems it never works well! ;)

**Comment by toto811** [comment]
one last thing I have a proform sport 7.0 treadmill it must be 10 years old do you think the inclination can be done automatically or not?
![488921ffdd7be328ff2788fa18d2d2cd45513be7](https://github.com/user-attachments/assets/025949bc-a68d-49d7-a647-6ad56b504432)

**Comment by cagnulein** [comment]
> t doesn't work don't worry my bike has always had problems it never works well! ;)

Whats do you mean with "doesn't work"?

**Comment by cagnulein** [comment]
> one last thing I have a proform sport 7.0 treadmill it must be 10 years old do you think the inclination can be done automatically or not?
> 
> ![488921ffdd7be328ff2788fa18d2d2cd45513be7](https://github.com/user-attachments/assets/025949bc-a68d-49d7-a647-6ad56b504432)
> 
> 

If ifit can connect to it yes

**Comment by toto811** [comment]
ok but I don't have automatic tilt, how should I proceed?

**Comment by cagnulein** [comment]
Collect this with ifit https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by cagnulein** [comment]
@toto811 any news?
