### ISSUE TITLE
Not connecting to Zwift

### ISSUE THREAD

**Issue by dmnufc1892** [cagnulein/qdomyos-zwift#2736]
**Describe the bug**
Stages SB20 won’t connect to Zwift app. Stages SB20 seemingly connected to QZ though. 

**To Reproduce**

**Expected behavior**
iPad on Zwift app shows ‘Stages Bike 0162’, ‘Wahoo Kickr 0000 33’, and ‘IPhone’ but power and cadence is zero and no connection. 

**Screenshots**
Attached 
[debug-Mon_Nov_4_10_39_29_2024.log](https://github.com/user-attachments/files/17619712/debug-Mon_Nov_4_10_39_29_2024.log)
![IMG_9213](https://github.com/user-attachments/assets/84ac222a-80ea-43ca-ba15-ef0e9bbccb7c)
![IMG_9212](https://github.com/user-attachments/assets/2ffc1245-85d3-45d0-ab54-0fb5ca417d7b)
![IMG_9211](https://github.com/user-attachments/assets/dbb72478-1002-4a1d-ab31-fa268c1ff7e0)
![IMG_9214](https://github.com/user-attachments/assets/a74f45f1-44ea-439c-8586-251be1e3390b)

**Desktop (please complete the following information):**
 - Using Zwift on iPad (latest iOS) 

**Smartphone (please complete the following information):**
 - Using QZ on iPhone 14 Pro (latest iOS) 

**Append a debug log**
#ATTACHED#  

**Additional context**

**Comment by cagnulein** [comment]
@dmnufc1892 log checked. the bike is connected to qz but it's not reporting wattage and cadence. that's why you are seeing 0. without qz are you able to connect it to zwift and see the metrics correctlt?

**Comment by dmnufc1892** [comment]
No. Issues with Stages SB20 since the company went into administration. My bike has been unable to connect to Zwift for a few months hence why I turned to your app. Other Stages owners in a similar predicament had said QZ offered a solution.

**Comment by cagnulein** [comment]
ok do you have an app that already read the power from it? for example kinomap? or even the stages app?

**Comment by dmnufc1892** [comment]
Apologies for the delay in replying. It would appear that the issue was due to ‘user error’. I’ve managed to get Zwift working with my Stages SB20 again 😊 TYVM for your attention to this matter 👍🏻

**Comment by cagnulein** [comment]
No problem, what was the error for future reference?

**Comment by dmnufc1892** [comment]
Incorrect battery in one of the power meters … 😕
