### ISSUE TITLE
no zwift play

### ISSUE THREAD

**Issue by Starsailorgold** [cagnulein/qdomyos-zwift#2737]
The headwind connects first to the QZ, then the Kickr. Zwift Play just stays in pairing mode. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - latest version

**Smartphone (please complete the following information):**
 - Pixel 8
 - latest Android

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Sun_Nov_3_17_14_56_2024.log](https://github.com/user-attachments/files/17621234/debug-Sun_Nov_3_17_14_56_2024.log)

**Comment by cagnulein** [comment]
What if you disable the wahoo fan setting in qz? Do the zwift play devices
work properly then?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 4 nov 2024 alle 17:44 Starsailorgold ***@***.***>
ha scritto:

**Comment by Starsailorgold** [comment]
No. I also disabled every other bluetooth in the house. I still don't get a connection with the QZ with zwift play.

**Comment by cagnulein** [comment]
Can you show me a debug log without the headwind? Also can you please
download the nrfconnect app and check if you can see there the Zwift play
devices?

**Comment by Starsailorgold** [comment]
I can see and connect to Zwift Play (left and right) using nrfconnect.  For some reason I can't produce a debug log.

**Comment by cagnulein** [comment]
Could you please join the beta here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and update the app from the store then, I guess I already fixed this

Let me know!

**Comment by Starsailorgold** [comment]
Now I have a connection between QZ and the Zwift Play and appears to be gear changing in QZ. The problem now is connecting to Zwift itself. When I can connect bluetooth from my phone to "Power Source" as soon as I go to "Controls" I loose the connection to "Power Source". 
![PXL_20241107_183538240 MP](https://github.com/user-attachments/assets/2948ca02-1160-47b9-84e9-d4c8775ed16e)
[debug-Wed_Nov_6_18_14_43_2024.log](https://github.com/user-attachments/files/17668440/debug-Wed_Nov_6_18_14_43_2024.log)

**Comment by cagnulein** [comment]
On which device zwift is running?

**Comment by Starsailorgold** [comment]
It’s running on a PC. 

 

      Mark

**Comment by cagnulein** [comment]
Rename your phone to "bike" and reboot it
Disable firewall on windows
Be sure both phone and pc are on the same wifi and channel

You have to see both phone name and virtual wahoo on zwift 

Let me know

**Comment by Starsailorgold** [comment]
I have a better Bluetooth connection to Zwift but Zwift Play does not show a connection. The computer lan card is only 2.4 ghz and everything else is 5.0.  Could this be the issue? 

 

      Mark

**Comment by cagnulein** [comment]
Would you like to pair zwift play directly to zwift? Did you disable it from qz? You have to enable the get gear from zwift setting in the zwift settings in qz for this like in my video Zwift Virtual Gearing for all the trainers !
https://youtu.be/mJl2zkQ2SuA

**Comment by Starsailorgold** [comment]
Here's the photo 
![PXL_20241108_165210214 MP](https://github.com/user-attachments/assets/1f36ccfd-0509-4a0e-8a61-95e234c867e7)

**Comment by cagnulein** [comment]
Ok perfect select bike, then bike also for cadence and resistance, then also zwift play and then set wahoo for power and cadence

**Comment by Starsailorgold** [comment]
The problem is Zwift Play, it’s not there to select. 

 

      Mark

**Comment by cagnulein** [comment]
Are they blinking? Are you sure you disabled the zwift play under the accessories, zwift setting in qz?

**Comment by Starsailorgold** [comment]
No, they are solid blue, I have the connection between QZ and "Play" but
"Play" doesn't show up in Zwift. I did not disable "Play" in accessories.
Mark

**Comment by cagnulein** [comment]
That's the issue: for this scenario you have to disable zwift play setting
in qz and connect them only on zwift

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 nov 2024 alle 16:59 Starsailorgold ***@***.***>
ha scritto:

**Comment by Starsailorgold** [comment]
Ok, now Play is connected. The issue now is that I'm only getting the
lowest gear. I can only get to 50 watts with a very high cadence. The gear
number changes in Zwift but has no effect on resistance.
Mark

**Comment by cagnulein** [comment]
Do you see the gear changing in qz as well?

**Comment by Starsailorgold** [comment]
Yes, I do.
Mark

**Comment by cagnulein** [comment]
so share a debug log, if it was working before must have also now

**Comment by Starsailorgold** [comment]
[debug-Sat_Nov_9_09_22_25_2024.log](https://github.com/user-attachments/files/17692314/debug-Sat_Nov_9_09_22_25_2024.log)

**Comment by cagnulein** [comment]
Got the issue, I guess already fixed this on 2.18.4
If you want you can wait the Google review (2-3 days) or I can invite you on the closed beta. In this case 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks
