### ISSUE TITLE
[BUG]Cannot connect to Kinomap from TDF 5.0/QZ

### ISSUE THREAD

**Issue by HEKA-LFC** [cagnulein/qdomyos-zwift#2738]
**Describe the bug**
My TDF 5.0 connects perfectly to QZ and one time I have also succeeded connecting to Kinomap with full control of inclination, resistance etc. 

That it no longer possible. I attach debug report from Qz.

**To Reproduce**

I attach debug report from Qz.

**Expected behavior**
Kinomap cannot find my equipment when choosing Biketrainer/FTMS….
Kinomap states ‘No peripherals detected’

**Screenshots**
Attached
![IMG_3309](https://github.com/user-attachments/assets/cab0160a-2ea5-4db1-bb13-d3eedd85c979)
![IMG_3308](https://github.com/user-attachments/assets/8c4c09bf-2002-42bc-bc57-0cc9a16c43e6)

**Desktop (please complete the following information):**
 - Qz; iPhone 15pro/IOS 18.1
 - Kinomap; iPad Air 4/IOS 18.1

**Append a debug log**
Attached
[debug-Tue_Nov_5_06_51_09_2024.log](https://github.com/user-attachments/files/17627829/debug-Tue_Nov_5_06_51_09_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by HEKA-LFC** [comment]
OMG - is it that simple - sorry for bothering you with that. I'll try
tonight and let you know.

Have a great day.

Den tirs. 5. nov. 2024 kl. 07.47 skrev Roberto Viola <
***@***.***>:

**Comment by cagnulein** [comment]
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 08:49 HEKA-LFC ***@***.***> ha
scritto:

**Comment by HEKA-LFC** [comment]
Kinomap connected with the ‘Enable Vitual Device’. However, also had to enable ‘Vitual Device Bluetooth’, ‘Relaxed Bluetooth for mad devices’ and ‘Bluetooth hangs after 30m’. 

With those enabled, Kinomap receives most data from QZ/TDF5.0, however it does not control inclination and resistance, which it did back in July, when I tested it the first time.

Any good ideas? Best /Henrik

**Comment by cagnulein** [comment]
Did you connect as ftms in kinomap? If so send me a fresh debug log

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 19:02 HEKA-LFC ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Solved?

**Comment by HEKA-LFC** [comment]
Not yet!

Den tirs. 5. nov. 2024 kl. 19.35 skrev Roberto Viola <
***@***.***>:

**Comment by HEKA-LFC** [comment]
Hi Roberto,

Here is a fresh debug log, attached. Also a few photos from Kinomap during the test-workout.

Still no resistance nor inclination. In addition the speed is totally meshed up, however less important as the watt is transferred from TDF5/QZ.
[debug-Tue_Nov_5_19_54_57_2024.log](https://github.com/user-attachments/files/17637271/debug-Tue_Nov_5_19_54_57_2024.log)
![IMG_3316](https://github.com/user-attachments/assets/22694788-8dbf-42df-b342-91975b620621)
![IMG_3315](https://github.com/user-attachments/assets/a2568d32-ef71-4c8b-a93f-237b898a1c51)

**Comment by cagnulein** [comment]
I don't see any message from kinomap. Are you sure you selected ftms bike on kinomap and also as controllable?

**Comment by HEKA-LFC** [comment]
Yes, Kinomap is configured as FTMS. Not sure what you mean with controllable?

I have added a new debug file, and pictures from Kinomap and QZ. Hope you can find the issue.
/Best Henrik
![IMG_3325](https://github.com/user-attachments/assets/379ba282-eaab-4441-b0f8-f2f6614c58ae)
[debug-Tue_Nov_5_23_35_02_2024.log](https://github.com/user-attachments/files/17639529/debug-Tue_Nov_5_23_35_02_2024.log)
![IMG_3317](https://github.com/user-attachments/assets/f096b460-9237-48c8-88dc-a4796e1a3eb0)
![IMG_3318](https://github.com/user-attachments/assets/b5d64faf-7240-4d3b-9a7b-cf8c97e1d23b)
![IMG_3319](https://github.com/user-attachments/assets/1c3762f0-1804-41ee-ace0-e9445a47e78d)
![IMG_3320](https://github.com/user-attachments/assets/bdd821f8-2cd9-4f1c-bac5-15a3d9476d62)
![IMG_3321](https://github.com/user-attachments/assets/d3e5e9e8-2ff2-4643-8fcb-f9586038180b)
![IMG_3322](https://github.com/user-attachments/assets/47f71bf7-5648-44e1-aa40-a8b265d296be)
![IMG_3323](https://github.com/user-attachments/assets/2bff4b0c-ce2f-4858-9d22-808986e59b94)
![IMG_3324](https://github.com/user-attachments/assets/8f0f8918-444d-407b-8745-2f028c2ac7ad)

**Comment by cagnulein** [comment]
@HEKA-LFC i would like to send you a new beta because I guess I found the issue. With the new beta there is not a fix yet but I'm collecting the information required to solve it. 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by HEKA-LFC** [comment]
Hi Roberto,

Attached latest debug log using Testflight. Also a few photos from Kinomap/TDF5.0/Testflight

The Kinomap UI looked a bit different from yesterday, as it now had other participants to compare. However, still no auto-controlled resistance nor inclination and speed it crazy🤪 

[debug-Wed_Nov_6_07_25_59_2024.log](https://github.com/user-attachments/files/17642748/debug-Wed_Nov_6_07_25_59_2024.log)
![IMG_3328](https://github.com/user-attachments/assets/137a97ca-87c4-4bdb-aa02-a01d40e3f9dc)
![IMG_3327](https://github.com/user-attachments/assets/394759e0-cef5-4abd-8de5-44ca609ecc16)
![IMG_3326](https://github.com/user-attachments/assets/574f0b77-fbb1-4eb5-a91a-e76405e5c7dd)

**Comment by cagnulein** [comment]
i just tried a kinomap session on my end and it works great, but indeed I see the issue on your log. I'm adding more logs to understand the issue deeply.

Thanks

**Comment by HEKA-LFC** [comment]
Could it be that those iFit guys still are controlling something on the TDF tablet - sorry for conspiring, but have had so many bad experiences with iFit. This morning, I suddenly had a login button and all settings i.e. gear, time zone etc. had to be reconfigured.

**Comment by cagnulein** [comment]
no it's not about this, in your setup the issue is what kinomap sending. I'm sending you another one, please collect again a debug log. We are near. Thanks

**Comment by cagnulein** [comment]
Yes I didn't solve anything I just added new log, let me check

**Comment by cagnulein** [comment]
In this log I can't see any inclination from kinomap, but on the last log I saw it. Maybe you selected a different workout? Can you please try again?

**Comment by HEKA-LFC** [comment]
I did another one, however still not working as it should. P
[debug-Wed_Nov_6_22_53_52_2024.log](https://github.com/user-attachments/files/17653560/debug-Wed_Nov_6_22_53_52_2024.log)
lease see attached.

**Comment by cagnulein** [comment]
Ok this log is fine, now I can check this

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 23:06 HEKA-LFC ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
I found finally your issue
You have "Ant+ Bike Over Garmin Watch" enabled on the ant+ setting in qz!
disable it and restart QZ

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 nov 2024 alle ore 07:09 cagnulein ***@***.***> ha
scritto:

**Comment by HEKA-LFC** [comment]
Hi there,

That helped - now inclination/resistance works🙏 However, now Kinomap starts out and adjust i.e. inclination, though shortly after miss connection to QZ/TDF. Attached debug file. 

I’m really sorry for being so troublesome.
[debug-Thu_Nov_7_22_08_46_2024.log](https://github.com/user-attachments/files/17669545/debug-Thu_Nov_7_22_08_46_2024.log)
![IMG_3342](https://github.com/user-attachments/assets/c29fa9d2-5769-4f7a-84af-a50f8e590507)

**Comment by cagnulein** [comment]
Just tested with qz on my iPhone and Kinomap on my iPad and works
beautifully. Maybe it was just a kinomap glitch? Did you try it again?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 nov 2024 alle 22:19 HEKA-LFC ***@***.***> ha
scritto:

**Comment by HEKA-LFC** [comment]
Unfortunately, it does not seem to be a glitch. Still same issue. TDF/QZ connects to Kinomap and Kinomap adjust the inclination at start, then disconnect.

Attached latest debug log
[debug-Fri_Nov_8_21_14_12_2024.log](https://github.com/user-attachments/files/17683707/debug-Fri_Nov_8_21_14_12_2024.log)

**Comment by cagnulein** [comment]
After when you see the disconnection from the first inclination change?

**Comment by cagnulein** [comment]
I did a 3 minute workout without issue before

**Comment by HEKA-LFC** [comment]
Give and take, 3 seconds after inclination change I loose connection

**Comment by HEKA-LFC** [comment]
No stress - take it easy. I'm just happy if you can figure it at some point.

Thanks

**Comment by cagnulein** [comment]
I tried again with my setup and it's working 

https://github.com/user-attachments/assets/e67f05ea-3159-44ab-88cb-c4643ddb5284

Did you try to swap the devices? Qz on ipad and kinomap on phone just to check it?

**Comment by HEKA-LFC** [comment]
Have been away for some time, but now I tried swapping devices, meaning QZ on iPad and Kinomap on iPhone. Result, everything worked smoothly.

Any idea, what's wrong on the opporsite setup?

**Comment by HEKA-LFC** [comment]
I did try to copy all QZ from iPad to iPhone, however I did not change anything, still not working.

Can you recommend what to write to Kinomap? It is a bit annoying to have the Kinomap on my smallest device😫

**Comment by cagnulein** [comment]
Yes they can only fix them from my point of view qz is doing the same on both apps
They can check on the server side but last time I contacted them they didn't answer at all unfortunately 

Try and if you want put me in CC

**Comment by HEKA-LFC** [comment]
I have reach out to Kinomap on their support site. Could not add you into the loop, but will revert when I hear from them.

**Comment by cagnulein** [comment]
Ok, thanks for the update.

**Comment by HEKA-LFC** [comment]
Hi Roberto, sorry for not responding earlier. I have today tried to install QZ on an iPhone 7, totally reinstalled and clean. Moreover I swiped an old iPad for use with Kinomap. Now I only need a Kinomap trial to test, if that might change something, since Kinomap as stated in their latest reply doesn’t acknowledge them having an issue.

Concerning using KM scenes/GPX I cannot download such in the free version, so I must wait to try the QZ with scenery, until I’m alive in the KM community again.

**Comment by cagnulein** [comment]
For KM you can simply create a new account with a different email to get
the trial

Anyway you can download it also in the free version, but it's better don't
talk about this here

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 7 dic 2024 alle 15:09 HEKA-LFC ***@***.***> ha
scritto:

**Comment by HEKA-LFC** [comment]
New update, the use of new HW (iPhone7 and iPadAir2) works. 

I did a test ride where inclination, resistance etc. worked smoothly, exactly like first I tried in summer. So I believe we can close the case, although we will never know what is wrong with my newest HW-setup (iPhone15pro and iPad Air4). I guess it proofs one of your first comments about KinoMap-logic or the lack of it 😆
