### ISSUE TITLE
Raspi 4 Yesoul S3 no sensor reading

### ISSUE THREAD

**Issue by sickdabig** [cagnulein/qdomyos-zwift#274]
Hi

my Yesoul S3 bike works with your android app. However, due to some lost connection issues I would like to use my raspi 4 (4GB rev1.2). The bike is recognised but sensors are not read (no values are shown in the gui). 

I am on a fresh and up to date raspbian system. QZ was compiled after a reboot.

The printout in the terminal is the following:

OK, you are root.
Sa. Apr. 17 13:50:22 2021 1618660222120 Debug: main.cpp int main(int, char**) version  ""
version  ""
Sa. Apr. 17 13:50:22 2021 1618660222121 Debug: main.cpp int main(int, char**) "battery_service" QVariant(bool, false)
"battery_service" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222121 Debug: main.cpp int main(int, char**) "bike_cadence_sensor" QVariant(bool, false)
"bike_cadence_sensor" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222122 Debug: main.cpp int main(int, char**) "bike_power_sensor" QVariant(bool, false)
"bike_power_sensor" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222122 Debug: main.cpp int main(int, char**) "bike_wheel_revs" QVariant(bool, false)
"bike_wheel_revs" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222122 Debug: main.cpp int main(int, char**) "bluetooth_no_reconnection" QVariant(bool, false)
"bluetooth_no_reconnection" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222123 Debug: main.cpp int main(int, char**) "bluetooth_relaxed" QVariant(bool, false)
"bluetooth_relaxed" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222123 Debug: main.cpp int main(int, char**) "miles_unit" QVariant(bool, false)
"miles_unit" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222124 Debug: main.cpp int main(int, char**) "run_cadence_sensor" QVariant(bool, false)
"run_cadence_sensor" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222124 Debug: main.cpp int main(int, char**) "service_changed" QVariant(bool, false)
"service_changed" QVariant(bool, false)
Sa. Apr. 17 13:50:22 2021 1618660222131 Debug:   Bluez 5 detected.
qt.bluetooth.bluez: Bluez 5 detected.
Sa. Apr. 17 13:50:22 2021 1618660222144 Debug:   Creating QtBluezDiscoveryManager
qt.bluetooth.bluez: Creating QtBluezDiscoveryManager
Sa. Apr. 17 13:50:22 2021 1618660222153 Debug:   Discovered:  "20:20:00:0F:C7:1D" "Bluetooth 3.0 Keyboard" Num UUIDs 3 total device 0 cached RSSI 0 Class 1344
qt.bluetooth.bluez: Discovered:  "20:20:00:0F:C7:1D" "Bluetooth 3.0 Keyboard" Num UUIDs 3 total device 0 cached RSSI 0 Class 1344
Sa. Apr. 17 13:50:22 2021 1618660222156 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: Bluetooth 3.0 Keyboard (20:20:00:0F:C7:1D) \u0005:\u0010"
"Found new device: Bluetooth 3.0 Keyboard (20:20:00:0F:C7:1D) \u0005:\u0010"
Sa. Apr. 17 13:50:22 2021 1618660222162 Debug:   Discovered:  "64:33:DB:88:18:AA" "YESOUL282142\u0005\u0012\u0010" Num UUIDs 5 total device 1 cached RSSI 0 Class 0
qt.bluetooth.bluez: Discovered:  "64:33:DB:88:18:AA" "YESOUL282142\u0005\u0012\u0010" Num UUIDs 5 total device 1 cached RSSI 0 Class 0
Sa. Apr. 17 13:50:22 2021 1618660222164 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: YESOUL282142\u0005\u0012\u0010 (64:33:DB:88:18:AA) \u0000:\u0000"
"Found new device: YESOUL282142\u0005\u0012\u0010 (64:33:DB:88:18:AA) \u0000:\u0000"
Sa. Apr. 17 13:50:22 2021 1618660222165 Debug:   void QBluetoothDeviceDiscoveryAgentPrivate::stop()
qt.bluetooth.bluez: void QBluetoothDeviceDiscoveryAgentPrivate::stop()
Sa. Apr. 17 13:50:22 2021 1618660222166 Debug: bluetooth.cpp void bluetooth::debug(QString) "BTLE scanning stops"
"BTLE scanning stops"
Sa. Apr. 17 13:50:22 2021 1618660222167 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: YESOUL282142\u0005\u0012\u0010 (64:33:DB:88:18:AA)"
"Found new device: YESOUL282142\u0005\u0012\u0010 (64:33:DB:88:18:AA)"
Sa. Apr. 17 13:50:22 2021 1618660222167 Debug:   Detecting bluetoothd version
qt.bluetooth.bluez: Detecting bluetoothd version
Sa. Apr. 17 13:50:22 2021 1618660222168 Debug:   Using /proc/<pid>/exe
qt.bluetooth.bluez: Using /proc/<pid>/exe
Sa. Apr. 17 13:50:22 2021 1618660222186 Debug:   Detected bluetoothd version 5.50
qt.bluetooth.bluez: Detected bluetoothd version 5.50
Sa. Apr. 17 13:50:22 2021 1618660222187 Debug:   Bluetoothd: "5.50"
qt.bluetooth.bluez: Bluetoothd: "5.50"
Sa. Apr. 17 13:50:22 2021 1618660222187 Warning:   Using BlueZ LE DBus API
qt.bluetooth: Using BlueZ LE DBus API
Sa. Apr. 17 13:50:22 2021 1618660222203 Debug:   QLowEnergyControllerPrivateBluezDBus::connectToDevice()
qt.bluetooth.bluez: QLowEnergyControllerPrivateBluezDBus::connectToDevice()
Sa. Apr. 17 13:50:22 2021 1618660222216 Debug: yesoulbike.cpp void yesoulbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::ControllerState(ConnectingState)
controllerStateChanged QLowEnergyController::ControllerState(ConnectingState)
Sa. Apr. 17 13:50:22 2021 1618660222366 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
Sa. Apr. 17 13:50:22 2021 1618660222370 Debug:   BluetoothManagement: Ignored event: 13
qt.bluetooth.bluez: BluetoothManagement: Ignored event: 13
Sa. Apr. 17 13:50:22 2021 1618660222408 Debug:   BluetoothManagement: found random device "4B:9D:76:C1:AA:94"
qt.bluetooth.bluez: BluetoothManagement: found random device "4B:9D:76:C1:AA:94"
Sa. Apr. 17 13:50:22 2021 1618660222566 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
Sa. Apr. 17 13:50:22 2021 1618660222766 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
Sa. Apr. 17 13:50:22 2021 1618660222900 Debug:   BluetoothManagement: found random device "12:3B:C4:BC:76:EE"
qt.bluetooth.bluez: BluetoothManagement: found random device "12:3B:C4:BC:76:EE"
Sa. Apr. 17 13:50:22 2021 1618660222967 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false
QLowEnergyController::ControllerState(ConnectingState) true QObject(0x0) false false false

**Comment by cagnulein** [comment]
Are you sure are you running the last commit? I guess this is a very old
one. I don't see the version neither

Il sab 17 apr 2021, 14:03 sickdabig ***@***.***> ha scritto:

**Comment by sickdabig** [comment]
I installed according to instructions, just some hours ago. How can I find the version?

**Comment by cagnulein** [comment]
But did you do a git clone?
Do a git log and post me the results

Il sab 17 apr 2021, 15:06 sickdabig ***@***.***> ha scritto:

**Comment by sickdabig** [comment]
commit 7f11cced2c14f585639562f7b465aa3a2bf11a1c (HEAD -> master, origin/master, origin/HEAD)
Author: Roberto Viola <roberto.viola83@gmail.com>
Date:   Sat Apr 17 09:14:55 2021 +0200

    avoid crashes on npecablebike

commit 756d78546c2ee6dd8702763e33d262e898dc2db3
Author: Roberto Viola <roberto.viola83@gmail.com>
Date:   Sat Apr 17 08:18:30 2021 +0200

    ibiking+ bike supported

commit dd304f684a7272c46fe5204e0e2a42c676eb75e4
Merge: 4c0af00 7997953
Author: Roberto Viola <roberto.viola@systemceramics.com>
Date:   Fri Apr 16 11:45:51 2021 +0200

    Merge branch 'master' of https://github.com/cagnulein/qdomyos-zwift

commit 4c0af00c9758dbc12dcc7e6df8cfe1fda28509c3
Author: Roberto Viola <roberto.viola@systemceramics.com>
Date:   Fri Apr 16 11:45:16 2021 +0200

**Comment by cagnulein** [comment]
Ok so it should work
Try to run it with -qml arguments

**Comment by sickdabig** [comment]
I can't get qml working: 

```
Sa. Apr. 17 21:47:40 2021 1618688860856 Warning:   qrc:/main.qml:1 module "QtQuick" version 2.12 is not installed

qrc:/main.qml:1 module "QtQuick" version 2.12 is not installed
```
Also, since `sudo ./qdomyos-zwift -no-gui -heart-service` doesn't work either, I assume it's not a GUI issue. Zwift finds the android bridge, but not the raspi.

**Comment by cagnulein** [comment]
You need to install all the qml modules available in the raspbian.

Il sab 17 apr 2021, 22:07 sickdabig ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Check #193

**Comment by sickdabig** [comment]
Took a while to get all running. However it only shows a blank screen:
![IMG_20210419_105951](https://user-images.githubusercontent.com/11087061/115210266-b8f2f680-a0fe-11eb-8ce4-c26b201822f3.jpg)

**Comment by cagnulein** [comment]
check again that thread, you need to modify the import qml version in the
source code to use the raspbian qt version.
there is a zip file with the qml files

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 apr 2021 alle ore 11:03 sickdabig ***@***.***>
ha scritto:

**Comment by sickdabig** [comment]
I will try, but shouldn't at least the non-gui version work? Because it isn't either...

**Comment by cagnulein** [comment]
i guess the main problem is this one

Mo. Apr. 19 10:58:21 2021 1618822701723 Debug: bluetooth.cpp void bluetooth::debug(QString) "BTLE stateChanged InvalidService"

it seems that qt on raspberry have an issue with the yesoul 

did you try also with a linux pc?

**Comment by sickdabig** [comment]
Same issue on my linux notebook.

Mo. Apr. 19 11:59:55 2021 1618826395104 Debug:   BluetoothManagement: Ignored event: 13
Mo. Apr. 19 11:59:55 2021 1618826395183 Debug:   BluetoothManagement: found random device "16:40:69:82:3F:69"
Mo. Apr. 19 11:59:55 2021 1618826395188 Debug:   Discovered:  "16:40:69:82:3F:69" "16-40-69-82-3F-69" Num UUIDs 0 total device 15 cached RSSI -77 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:55 2021 1618826395190 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 16-40-69-82-3F-69 (16:40:69:82:3F:69) \u0000:\u0000"
Mo. Apr. 19 11:59:55 2021 1618826395443 Debug:   BluetoothManagement: found random device "69:DE:24:99:7A:17"
Mo. Apr. 19 11:59:55 2021 1618826395451 Debug:   Discovered:  "69:DE:24:99:7A:17" "69-DE-24-99-7A-17" Num UUIDs 0 total device 16 cached RSSI -87 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:55 2021 1618826395453 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 69-DE-24-99-7A-17 (69:DE:24:99:7A:17) \u0000:\u0000"
Mo. Apr. 19 11:59:55 2021 1618826395602 Debug:   BluetoothManagement: found random device "56:BE:A8:99:96:EC"
Mo. Apr. 19 11:59:55 2021 1618826395608 Debug:   Discovered:  "56:BE:A8:99:96:EC" "56-BE-A8-99-96-EC" Num UUIDs 0 total device 17 cached RSSI -87 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:55 2021 1618826395610 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 56-BE-A8-99-96-EC (56:BE:A8:99:96:EC) \u0000:\u0000"
Mo. Apr. 19 11:59:56 2021 1618826396655 Debug:   BluetoothManagement: found random device "6B:9E:F5:EA:2E:67"
Mo. Apr. 19 11:59:56 2021 1618826396665 Debug:   Discovered:  "6B:9E:F5:EA:2E:67" "6B-9E-F5-EA-2E-67" Num UUIDs 1 total device 18 cached RSSI -75 Class 0 Num ManufacturerData 0
Mo. Apr. 19 11:59:56 2021 1618826396668 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 6B-9E-F5-EA-2E-67 (6B:9E:F5:EA:2E:67) \u0000:\u0000"
Mo. Apr. 19 11:59:57 2021 1618826397623 Debug:   BluetoothManagement: found random device "43:E4:52:4E:30:32"
Mo. Apr. 19 11:59:57 2021 1618826397631 Debug:   Discovered:  "43:E4:52:4E:30:32" "43-E4-52-4E-30-32" Num UUIDs 0 total device 19 cached RSSI -99 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:57 2021 1618826397634 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 43-E4-52-4E-30-32 (43:E4:52:4E:30:32) \u0000:\u0000"
Mo. Apr. 19 11:59:58 2021 1618826398891 Debug:   BluetoothManagement: found random device "60:C8:B3:9C:38:6B"
Mo. Apr. 19 11:59:58 2021 1618826398907 Debug:   Discovered:  "60:C8:B3:9C:38:6B" "60-C8-B3-9C-38-6B" Num UUIDs 0 total device 20 cached RSSI -95 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:58 2021 1618826398910 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 60-C8-B3-9C-38-6B (60:C8:B3:9C:38:6B) \u0000:\u0000"
Mo. Apr. 19 11:59:58 2021 1618826398919 Debug:   Updating RSSI for "B4:C9:B9:1D:32:45" QVariant(short, -89)
Mo. Apr. 19 11:59:58 2021 1618826398919 Debug: bluetooth.cpp void bluetooth::debug(QString) "deviceUpdated B4-C9-B9-1D-32-45 \u0001"
Mo. Apr. 19 11:59:58 2021 1618826398923 Debug:   Updating RSSI for "59:37:AE:19:F6:5F" QVariant(short, -91)
Mo. Apr. 19 11:59:58 2021 1618826398923 Debug: bluetooth.cpp void bluetooth::debug(QString) "deviceUpdated 59-37-AE-19-F6-5F \u0001"
Mo. Apr. 19 11:59:58 2021 1618826398923 Debug:   BluetoothManagement: found random device "59:37:AE:19:F6:5F"
Mo. Apr. 19 11:59:59 2021 1618826399512 Debug:   BluetoothManagement: found random device "21:A4:F8:E3:CD:0A"
Mo. Apr. 19 11:59:59 2021 1618826399523 Debug:   Discovered:  "21:A4:F8:E3:CD:0A" "21-A4-F8-E3-CD-0A" Num UUIDs 0 total device 21 cached RSSI -101 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:59 2021 1618826399526 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: 21-A4-F8-E3-CD-0A (21:A4:F8:E3:CD:0A) \u0000:\u0000"
Mo. Apr. 19 11:59:59 2021 1618826399813 Debug:   Discovered:  "D0:D0:03:7B:98:3E" "D0-D0-03-7B-98-3E" Num UUIDs 0 total device 22 cached RSSI -103 Class 0 Num ManufacturerData 1
Mo. Apr. 19 11:59:59 2021 1618826399815 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: D0-D0-03-7B-98-3E (D0:D0:03:7B:98:3E) \u0000:\u0000"
Mo. Apr. 19 12:00:04 2021 1618826404488 Debug:   Discovered:  "64:33:DB:88:18:AA" "YESOUL282142" Num UUIDs 1 total device 23 cached RSSI -57 Class 0 Num ManufacturerData 0
Mo. Apr. 19 12:00:04 2021 1618826404493 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: YESOUL282142 (64:33:DB:88:18:AA) \u0000:\u0000"
Mo. Apr. 19 12:00:04 2021 1618826404494 Debug:   void QBluetoothDeviceDiscoveryAgentPrivate::stop()
Mo. Apr. 19 12:00:04 2021 1618826404499 Debug: bluetooth.cpp void bluetooth::debug(QString) "BTLE scanning stops"
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::disconnect: No such slot yesoulbike::changeSpeed(double) in mainwindow.cpp:276
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::disconnect: No such slot yesoulbike::changeInclination(double) in mainwindow.cpp:277
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::disconnect: No such slot yesoulbike::changeSpeedAndInclination(double, double) in mainwindow.cpp:278
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::disconnect: No such signal trainprogram::changeResistance(double) in mainwindow.cpp:279
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::disconnect: No such signal yesoulbike::tapeStarted() in mainwindow.cpp:280
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::connect: No such slot yesoulbike::changeSpeed(double) in mainwindow.cpp:285
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::connect: No such slot yesoulbike::changeInclination(double) in mainwindow.cpp:286
Mo. Apr. 19 12:00:04 2021 1618826404500 Warning:   QObject::connect: No such slot yesoulbike::changeSpeedAndInclination(double, double) in mainwindow.cpp:287
Mo. Apr. 19 12:00:04 2021 1618826404501 Warning:   QObject::connect: No such signal trainprogram::changeResistance(double) in mainwindow.cpp:288
Mo. Apr. 19 12:00:04 2021 1618826404501 Warning:   QObject::connect: No such signal yesoulbike::tapeStarted() in mainwindow.cpp:289
Mo. Apr. 19 12:00:04 2021 1618826404501 Debug: mainwindow.cpp void MainWindow::trainProgramSignals() trainProgram associated to a device
Mo. Apr. 19 12:00:04 2021 1618826404501 Debug: bluetooth.cpp void bluetooth::debug(QString) "Found new device: YESOUL282142 (64:33:DB:88:18:AA)"
Mo. Apr. 19 12:00:04 2021 1618826404501 Debug:   Detecting bluetoothd version
Mo. Apr. 19 12:00:04 2021 1618826404507 Debug:   Using /proc/<pid>/exe
Mo. Apr. 19 12:00:04 2021 1618826404513 Debug:   Detected bluetoothd version 5.53
Mo. Apr. 19 12:00:04 2021 1618826404513 Debug:   Bluetoothd: "5.53"
Mo. Apr. 19 12:00:04 2021 1618826404513 Warning:   Using BlueZ LE DBus API
Mo. Apr. 19 12:00:04 2021 1618826404523 Debug:   QLowEnergyControllerPrivateBluezDBus::connectToDevice()
Mo. Apr. 19 12:00:04 2021 1618826404527 Debug: yesoulbike.cpp void yesoulbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::ConnectingState
Mo. Apr. 19 12:00:04 2021 1618826404528 Debug:   BluetoothManagement: Ignored event: 13
Mo. Apr. 19 12:00:04 2021 1618826404645 Debug:   BluetoothManagement: Ignored event: b
Mo. Apr. 19 12:00:04 2021 1618826404646 Debug:   ###### "org.bluez.Device1" QMap(("Connected", QVariant(bool, true)))
Mo. Apr. 19 12:00:04 2021 1618826404709 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:04 2021 1618826404920 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:05 2021 1618826405130 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:05 2021 1618826405340 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:05 2021 1618826405550 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:05 2021 1618826405760 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:05 2021 1618826405970 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:06 2021 1618826406180 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:06 2021 1618826406390 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:06 2021 1618826406594 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::ConnectingState true QObject(0x0) false false false
Mo. Apr. 19 12:00:06 2021 1618826406601 Debug:   ###### "org.bluez.Device1" QMap(("ServicesResolved", QVariant(bool, true))("UUIDs", QVariant(QStringList, ("00001800-0000-1000-8000-00805f9b34fb", "00001801-0000-1000-8000-00805f9b34fb", "0000180a-0000-1000-8000-00805f9b34fb", "0000180f-0000-1000-8000-00805f9b34fb", "0000fff0-0000-1000-8000-00805f9b34fb"))))
Mo. Apr. 19 12:00:06 2021 1618826406601 Debug: yesoulbike.cpp void yesoulbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::ConnectedState
Mo. Apr. 19 12:00:06 2021 1618826406601 Debug: bluetooth.cpp void bluetooth::debug(QString) "Controller connected. Search services..."
Mo. Apr. 19 12:00:06 2021 1618826406601 Debug: yesoulbike.cpp void yesoulbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::DiscoveringState
Mo. Apr. 19 12:00:06 2021 1618826406606 Debug: bluetooth.cpp void bluetooth::debug(QString) "serviceDiscovered {00001801-0000-1000-8000-00805f9b34fb}"
Mo. Apr. 19 12:00:06 2021 1618826406608 Debug: bluetooth.cpp void bluetooth::debug(QString) "serviceDiscovered {0000180a-0000-1000-8000-00805f9b34fb}"
Mo. Apr. 19 12:00:06 2021 1618826406609 Debug: bluetooth.cpp void bluetooth::debug(QString) "serviceDiscovered {0000fff0-0000-1000-8000-00805f9b34fb}"
Mo. Apr. 19 12:00:06 2021 1618826406610 Debug: yesoulbike.cpp void yesoulbike::controllerStateChanged(QLowEnergyController::ControllerState) controllerStateChanged QLowEnergyController::DiscoveredState
Mo. Apr. 19 12:00:06 2021 1618826406610 Debug: bluetooth.cpp void bluetooth::debug(QString) "serviceScanDone"
Mo. Apr. 19 12:00:06 2021 1618826406610 Debug: bluetooth.cpp void bluetooth::debug(QString) "BTLE stateChanged DiscoveringServices"
Mo. Apr. 19 12:00:06 2021 1618826406745 Debug:   ###### "org.bluez.Device1" QMap(("Alias", QVariant(QString, "YESOUL282142\u0005\u0012\u0010"))("Name", QVariant(QString, "YESOUL282142\u0005\u0012\u0010")))
Mo. Apr. 19 12:00:06 2021 1618826406795 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:06 2021 1618826406917 Debug:   ###### "org.bluez.Device1" QMap(("Modalias", QVariant(QString, "bluetooth:v000Dp0000d0110")))
Mo. Apr. 19 12:00:06 2021 1618826406994 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:07 2021 1618826407097 Debug:   Read Char: "{0000fff1-0000-1000-8000-00805f9b34fb}" "f5101020f6"
Mo. Apr. 19 12:00:07 2021 1618826407194 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:07 2021 1618826407277 Debug:   Read Desc: "Characteristic 1"
Mo. Apr. 19 12:00:07 2021 1618826407367 Debug:   Read Char: "{0000fff2-0000-1000-8000-00805f9b34fb}" "02"
Mo. Apr. 19 12:00:07 2021 1618826407394 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:07 2021 1618826407457 Debug:   Read Desc: "Characteristic 2"
Mo. Apr. 19 12:00:07 2021 1618826407548 Debug:   Read Desc: "Characteristic 3"
Mo. Apr. 19 12:00:07 2021 1618826407595 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:07 2021 1618826407637 Debug:   Read Desc: "\x01\x00"
Mo. Apr. 19 12:00:07 2021 1618826407728 Debug:   Read Desc: "Characteristic 4"
Mo. Apr. 19 12:00:07 2021 1618826407795 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false
Mo. Apr. 19 12:00:07 2021 1618826407995 Debug: yesoulbike.cpp void yesoulbike::update() QLowEnergyController::DiscoveredState true QLowEnergyService(0x5599c962c9b0) false false false

**Comment by cagnulein** [comment]
no it's different. did you try to let it running? it was reading the characteristic. send the full log as an attachment

**Comment by sickdabig** [comment]
[debug-Mo__Apr__19_12_08_13_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6335122/debug-Mo__Apr__19_12_08_13_2021.log)

**Comment by cagnulein** [comment]
pull it agai @sickdabig i tried to add a workaround to the linux bug

**Comment by sickdabig** [comment]
Different, but still no sensor readings.
[debug-Mo__Apr__19_13_29_21_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6335633/debug-Mo__Apr__19_13_29_21_2021.log)

**Comment by cagnulein** [comment]
"yesoulbike::errorServiceOperationError"

there is definitely something on the linux side that blocks it. I'm sorry i don't have the time to analyze it.
Why are you trying this solution? i mean which disconnection issue do you have on your mobile?

**Comment by cagnulein** [comment]
also another thing that you can try is to update the Qt to 5.15 on linux. They are the ones that i'm using on mobile

**Comment by sickdabig** [comment]
The connection breaks up about three times per hour. It is not very bad, but annoying if I am in a sprint ;-)

I have the suspicion that it is related to android power saving and my raspi 4 is running near to my bike anyways that's why I wanted to use it. Also I could run the Zwift Companion app on my mobile then. 

Thank you for looking into it. I will try QT5.15 in the next days and let you know if it works.

Do you think that if it works on Linux it will work on the raspi? Then I could avoid cross-compiling QT5.15 for testing...

**Comment by cagnulein** [comment]
yes absolutely. Test it on Linux before than raspbi

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 19 apr 2021 alle ore 13:45 sickdabig ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
hi any update on this?

**Comment by sickdabig** [comment]
I was able to crosscompile with qt 5.15 for the raspi. But after the changes you made no qml window is showing up anymore.

I am also lost on which exact QT and QTquick version to use (define in the qml files), it looks like to me that you are using different versions in different qml files. Also you seem to use 5.12 rather than 5.15.

**Comment by cagnulein** [comment]
with the 5.15 just use the standard QZ repo without modification.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 apr 2021 alle ore 13:49 sickdabig ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
i'm closing this one. feel free to reopen it
