### ISSUE TITLE
[BUG] Garmin HR over ANT+ not collected in QZ

### ISSUE THREAD

**Issue by svukom4n** [cagnulein/qdomyos-zwift#2740]
**Describe the bug**
Using a CooSpoo ANT+ dongle on my Android tablet or smartphone. When I broadcast HR data from my Garmin watch, I can see the data in the ANT+ Plugin Sampler app and also in Rouvy. But on the same tablet, I can't see the HR data in QZ.

My QZ settings are:
- Heart Rate Options > Hear Rate Belt: Disabled
- Garmin Options > Enable Companion App: Disabled
- Ant+ Options > Ant+ Heart: Enabled

**To Reproduce**
1. Start HR broadcast on a Garmin watch
2. Open ANT+ Plugin Sampler or Rouvy - HR over ANT+ is collected
3. Start QZ
4. No HR data (0 displayed in the HR tile)

**Expected behavior**
HR data should be displayed in the tile

**Smartphone (please complete the following information):**
 - Device: TCL NXTPaper, Samsung S22
 - OS: Android
 - Version 14

**Append a debug log**
[debug-Tue_Nov_5_14_39_15_2024.log](https://github.com/user-attachments/files/17633534/debug-Tue_Nov_5_14_39_15_2024.log)

**Comment by cagnulein** [comment]
That's interesting, are you able to collect a bug report from android while
you have this issue?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 15:03 svukom4n ***@***.***> ha
scritto:

**Comment by svukom4n** [comment]
Attaching a new QZ log together with the Android debug from the same time.
[android_log.log](https://github.com/user-attachments/files/17634716/android_log.log)
[debug-Tue_Nov_5_14_39_15_2024.log](https://github.com/user-attachments/files/17634739/debug-Tue_Nov_5_14_39_15_2024.log)

**Comment by cagnulein** [comment]
thanks @svukom4n 

```
11-05 16:09:11.621 23447 29835 D HeartChannelController: Rx: 0x40:[01][42][00]
11-05 16:09:11.621 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:11.625 23447 29835 D HeartChannelController: Rx: 0x40:[01][75][00]
11-05 16:09:11.625 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:11.627 23447 29835 D HeartChannelController: Rx: 0x40:[01][51][00]
11-05 16:09:11.627 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:11.629 23447 29835 D HeartChannelController: Rx: 0x40:[01][43][00]
11-05 16:09:11.629 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:11.631 23447 29835 D HeartChannelController: Rx: 0x40:[01][45][00]
11-05 16:09:11.631 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:11.633 23447 23447 D HeartChannelController: Opened channel with device number
11-05 16:09:11.633 23447 29835 D HeartChannelController: Rx: 0x40:[01][4B][00]
11-05 16:09:11.633 23447 29835 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:09:26.403 23447 29835 D HeartChannelController: Rx: 0x40:[01][01][01]
11-05 16:09:26.403 23447 29835 D HeartChannelController: Message Type: CHANNEL_EVENT
11-05 16:09:26.404 23447 29835 D HeartChannelController: Event Code: RX_SEARCH_TIMEOUT
11-05 16:09:26.404 23447 29835 E HeartChannelController: No Device Found
11-05 16:09:26.404 23447 29835 D HeartChannelController: Rx: 0x40:[01][01][07]
11-05 16:09:26.404 23447 29835 D HeartChannelController: Message Type: CHANNEL_EVENT
11-05 16:09:26.404 23447 29835 D HeartChannelController: Event Code: CHANNEL_CLOSED
11-05 16:12:51.116 23452 30944 D HeartChannelController: Rx: 0x40:[00][42][00]
11-05 16:12:51.116 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:12:51.128 23452 30944 D HeartChannelController: Rx: 0x40:[00][75][00]
11-05 16:12:51.128 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:12:51.131 23452 30944 D HeartChannelController: Rx: 0x40:[00][51][00]
11-05 16:12:51.132 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:12:51.134 23452 30944 D HeartChannelController: Rx: 0x40:[00][43][00]
11-05 16:12:51.134 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:12:51.136 23452 30944 D HeartChannelController: Rx: 0x40:[00][45][00]
11-05 16:12:51.136 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:12:51.140 23452 23452 D HeartChannelController: Opened channel with device number
11-05 16:12:51.140 23452 30944 D HeartChannelController: Rx: 0x40:[00][4B][00]
11-05 16:12:51.140 23452 30944 D HeartChannelController: Message Type: CHANNEL_RESPONSE
11-05 16:13:05.900 23452 30944 D HeartChannelController: Rx: 0x40:[00][01][01]
11-05 16:13:05.901 23452 30944 D HeartChannelController: Message Type: CHANNEL_EVENT
11-05 16:13:05.902 23452 30944 D HeartChannelController: Event Code: RX_SEARCH_TIMEOUT
11-05 16:13:05.902 23452 30944 E HeartChannelController: No Device Found
11-05 16:13:05.902 23452 30944 D HeartChannelController: Rx: 0x40:[00][01][07]
11-05 16:13:05.902 23452 30944 D HeartChannelController: Message Type: CHANNEL_EVENT
11-05 16:13:05.902 23452 30944 D HeartChannelController: Event Code: CHANNEL_CLOSED
```

is there a particular reason why you don't want to use the qz companion app on the watch?
In the meantime I'm checking what these messages meaning

**Comment by svukom4n** [comment]
The reason for not using the companion app is that on my wife's watch it's unreliable. She wants to use QZ on the tablet and not on the phone that the watch is paired to. Also she wants to start the Bike Indoor activity on the watch, which can't be done with the companion app running.

**Comment by cagnulein** [comment]
> The reason for not using the companion app is that on my wife's watch it's unreliable.

what do you mean? what's the issue?



> She wants to use QZ on the tablet and not on the phone that the watch is paired to.

hah ok



> Also she wants to start the Bike Indoor activity on the watch, which can't be done with the companion app running.

got it.

about the ant issue, can you show me ANT+ Plugin Sampler getting the HR from it, i would like to check if it does something different.

**Comment by svukom4n** [comment]
I'm attaching the screenshot. I also ran the ANT+ Plugin Sampler during the Android debug, before starting QZ, so maybe you can see something there.

![image](https://github.com/user-attachments/assets/42c8a268-6ccc-4eaf-9c9d-7b0ee77aaace)

**Comment by cagnulein** [comment]
it seems that it's not broadcasting it (qz aspects that a device is broadcasting rather than connecting to it), that's probably the reason. Did you start a workout on the watch when you tried this? I can also try with my forerunner 255 this evening.

**Comment by svukom4n** [comment]
When I'm testing I'm manually running "Broadcast Heart Rate" on my watch under Settings > Watch Sensors > Wrist Heart Rate. When I enable this I see the HR show up in the Plugin Sampler and Rouvy. I also tried running the Bike Indoor activity where I have broadcast HR enabled, same thing. If it's important, I have the QZ Beta and GarminOS 11.16.

**Comment by cagnulein** [comment]
Ok let me try if I can simulate this on my watch too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 17:39 svukom4n ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Stupid question / both rouvy and ant sampler are fully closed right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 18:08 cagnulein ***@***.***> ha
scritto:

**Comment by svukom4n** [comment]
Yes, I always close the apps before opening QZ. It's also worth noting that I'm seeing the exact same behavior on my tablet and my phone.

**Comment by cagnulein** [comment]
Ok, thanks for the clarification.
Tomorrow I will try it.
Thanks

Il giorno mar 5 nov 2024 alle 20:23 svukom4n ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ok good news I can see the same problem with my forerunner. I will fix it
asap, I guess Garmin changed something lately

**Comment by cagnulein** [comment]
start working on this, let's see how it goes

**Comment by cagnulein** [comment]
good news! i guess i have a working build!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11717840105/artifacts/2156202768

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by svukom4n** [comment]
I confirm that it works for me with the apk you provided (2.18.2). I sent you an email as instructed. Thank you!

**Comment by cagnulein** [comment]
Glad it worked!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 7 nov 2024 alle ore 09:28 svukom4n ***@***.***>
ha scritto:

**Comment by CodingDutchman** [comment]
Yup, working for me, too! Nice work!
