### ISSUE TITLE
[BUG] Not connecting to Zwift or Rouvy or other

### ISSUE THREAD

**Issue by akeix** [cagnulein/qdomyos-zwift#2743]
**Describe the bug**
I have a Domyos EB900B.
QZ sees the Domyos via Bluetooth and everything works well.

But no third-party application connects to Qz via Bluetooth.

[debug-Tue_Nov_5_18_12_58_2024.log](https://github.com/user-attachments/files/17637103/debug-Tue_Nov_5_18_12_58_2024.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Zwift ou Rouvy :**
 - Tablet : Samsung Galaxy TAB S6 Lite
 - OS: One UI 5.1.1 / Android 13
 - Version Zwift or Rouvy : old version

**Smartphone for Qz:**
 - Device: Xiaomi 11 Lite 5G NE
 - OS: Xiaomi Hyper OS 1.0.9.0 / Android 14
 - Version Qz : old version

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Did you rename your phone to bike and reboot it? Only 4 letters
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 19:48 akeix ***@***.***> ha
scritto:

**Comment by akeix** [comment]
Hello,

I tried it this morning.
The name change worked.

Thanks for your help

**Comment by cagnulein** [comment]
Awesome, thanks for the update!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle ore 07:25 akeix ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Remember to rate the app on the store, it means a lot to me! Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle ore 07:28 cagnulein ***@***.***> ha
scritto:
