### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Noutten** [cagnulein/qdomyos-zwift#2744]
**Describe the bug**
I downloaded QZ today in the hopes of using it with peloton and my 7.4AT horizon tread. The app will connect to the tread but is not receiving any data. When a peloton class is running, it will say connected to the class in QZ but no metrics are coming over and my peloton app does not show any devices as being connected. 

**To Reproduce**

**Expected behavior**
I just want all my metrics in peloton. 
[Uploading debug-Tue_Nov_5_13_47_30_2024.log…]()

**Comment by cagnulein** [comment]
Hi you have to wait the finish of the upload before commenting. Please upload it again 
Thanks

**Comment by Noutten** [comment]
[debug-Tue_Nov_5_13_47_30_2024.log](https://github.com/user-attachments/files/17637234/debug-Tue_Nov_5_13_47_30_2024.log)

**Comment by cagnulein** [comment]
Please try to enable this and restart qz 

![image](https://github.com/user-attachments/assets/dda4829e-5b78-412b-b358-1064f8fcab94)

**Comment by Noutten** [comment]
Enabled and restarted. App connected to tread but no metrics coming through. Screenshot of app and photo of turned on tread. 
![IMG_7141](https://github.com/user-attachments/assets/fc677c31-dfbd-4f0a-8f7f-2224085abe35)
![IMG_7142](https://github.com/user-attachments/assets/319d73de-d10a-4320-8e9c-f1ee3c61528a)

**Comment by cagnulein** [comment]
Please share a fresh log so I would like to check it's happening under the hood

**Comment by Noutten** [comment]
[debug-Tue_Nov_5_14_06_41_2024.log](https://github.com/user-attachments/files/17637327/debug-Tue_Nov_5_14_06_41_2024.log)

**Comment by cagnulein** [comment]
It seems it doesn't talk at all but it seems connected.

Do you have an app that actually works with it? 

I would like to understand if it's a treadmill issue or an app configuration issue

**Comment by Noutten** [comment]
But the Bluetooth is working because the sound is coming through the speakers on the tread.

**Comment by cagnulein** [comment]
Yes Bluetooth is working but the treadmill is not sending metrics.

Did you a factory reset?



Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 5 nov 2024 alle 20:25 Noutten ***@***.***> ha
scritto:

**Comment by Noutten** [comment]
I’m not sure how. I’ve tried to look it up but can’t find anything on it. Horizon 7.4AT

**Comment by cagnulein** [comment]
Did you try the horizon app as well?

**Comment by Noutten** [comment]
I have not tried the horizon app. I looked up resets again and tried a few things but I can’t even get the console to go into the engineering menu to reset. It’s like it’s not registering the combination buttons to get to the menu.

**Comment by cagnulein** [comment]
I suggest to call horizon, it's definitely locked after the upgrade unfortunately  :(
