### ISSUE TITLE
Capitol Sports Infinity Pro 4 treadmill

### ISSUE THREAD

**Issue by Mravljica** [cagnulein/qdomyos-zwift#2748]
[debug-Wed_Nov_6_17_13_50_2024.log.txt](https://github.com/user-attachments/files/17650253/debug-Wed_Nov_6_17_13_50_2024.log.txt)
**Describe the bug**

App does not show speed of treadmill, heartrate and cadence

**Expected behavior**

**Screenshots**

**Ipad (please complete the following information):**
 - OS: iPadOS
 - Version 17.6.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Mravljica Which is the issue? You didn't write the description

**Comment by Mravljica** [comment]
Issue is that qz don't show speed of treadmill. I didn't know exactly how to complete form.

**Comment by Mravljica** [comment]
I also try heart rate sensor and works ok.

**Comment by Mravljica** [comment]
@cagnulein Yes treadmill was running. I only tried at 3 km/h. When I bought treadmill I've got 6 month subscription on Kinomap and there worked everything including incline.

**Comment by cagnulein** [comment]
Ok so it's a fitshow treadmill, I will send you a new version tomorrow with
the fix!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 18:21 Mravljica ***@***.***> ha
scritto:

**Comment by Mravljica** [comment]
Ok, thank you!

**Comment by cagnulein** [comment]
Sent! Disable the treadmill from the ftms treadmill setting and press ok
and restart qz
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 18:25 Mravljica ***@***.***> ha
scritto:

**Comment by Mravljica** [comment]
Apologize for late ansver I was outside running. 
I've tested like you said and it works. From the moment I saw Bluetooth icon on treadmill screen I knew it will work. It's also working with Zwift.
So this was only test version?

**Comment by cagnulein** [comment]
Perfect! You can keep this version, I will update it once every month don’t
worry!
Please remember to rate the app on the store, it means a lot to me!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 6 nov 2024 alle 21:28 Mravljica ***@***.***> ha
scritto:
