### ISSUE TITLE
[BUG] Can't load any training except those already shipped

### ISSUE THREAD

**Issue by gabrielstelmach** [cagnulein/qdomyos-zwift#2754]
**Describe the bug**
I have a couple of custom training files (XML) which I used to load and execute in the app without issues. After a recent app update, the option for opening a custom train program stopped working.

**To Reproduce**
1. Go to the program menu (left top hand menu)
2. Click on 'Open Train Program'
3. Click on 'Other folders'
4. Select any custom training program (I have enclosed mine as ZIP)
5. The app displays the list of shipped programs -no error/warning messages

**Expected behavior**
The custom training program is loaded and the application displays the dashboard with 'Start' button available.

**Screenshots**
No errors, no screenshots

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
 - Device: Samsung Tablet SM-T5000
 - OS: Android
 - Version: 12

**Append a debug log**
Log file: 
[debug-Thu_Nov_7_16_38_56_2024.log](https://github.com/user-attachments/files/17671102/debug-Thu_Nov_7_16_38_56_2024.log)  
  
**Additional context**
Custom training program (unzip to use): 
[Training_Beco_II-58min_no-running.zip](https://github.com/user-attachments/files/17671126/Training_Beco_II-58min_no-running.zip)

**Comment by cagnulein** [comment]
I guess I already answered you by email directly, feel free to continue the
discussion here. Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 8 nov 2024 alle 02:03 Gabriel Stelmach <
***@***.***> ha scritto:

**Comment by gabrielstelmach** [comment]
Removing folder "QZ" and selecting again the training file from "Downloads" worked to load and start the training. However, when I hit 'Start', the treadmill started at 0.8 km/h speed instead of 4.5 km/h.

Here is the log: 
[debug-Fri_Nov_8_09_34_19_2024.log](https://github.com/user-attachments/files/17680168/debug-Fri_Nov_8_09_34_19_2024.log)

**Comment by gabrielstelmach** [comment]
Another update. The issue with starting at 0.8km/h seems random. Closing QZ and opening it again workaround the issue.

There is another problem I'm facing with any of the training programs (either shipped or custom), after starting the exercise, some telemetry is not received/displayed in QZ as "Elapsed" -it is still always 0:00:00. Due to this issue, the exercise is never progressing -my guess. Some other telemetries like "Odometer" and "Heart" are displayed in QZ.

**Comment by cagnulein** [comment]
> Another update. The issue with starting at 0.8km/h seems random. Closing QZ and opening it again workaround the issue.

i was saying this too because I wasn't able to see the same issue.



> There is another problem I'm facing with any of the training programs (either shipped or custom), after starting the exercise, some telemetry is not received/displayed in QZ as "Elapsed" -it is still always 0:00:00. Due to this issue, the exercise is never progressing -my guess. Some other telemetries like "Odometer" and "Heart" are displayed in QZ.

do you have the debug log from this one? i guess it could be connected to the previous one

**Comment by gabrielstelmach** [comment]
Another round... I did some tweaks in Settings and it seems working 'most' of the attempts now. There is only 1 left issue I found related to Zwift workouts and inclination command.

I created the same workout from my original XML format using Zwift format (see enclosed). When selecting the Zwift version, after the warm-up period of 5 minutes it is expected to have the treadmill inclination of 12% with a speed of 6.5 km/h. However, the treadmill seems to start speedying to 6.5 then suddenly drop to 2 km/h whilst the inclination goes as intended.

Also, I noticed that `textevent` does not have any effect.

It is worth noting that the same training program in XML version works fine.

Here is the training program: 
[Aerobic 18 intervals and 12 mins uphill on 56 mins training (Zwift).zip](https://github.com/user-attachments/files/17682118/Aerobic.18.intervals.and.12.mins.uphill.on.56.mins.training.Zwift.zip)

Here is the log: 
[debug-Fri_Nov_8_12_18_18_2024.log](https://github.com/user-attachments/files/17682122/debug-Fri_Nov_8_12_18_18_2024.log)

**Comment by cagnulein** [comment]
It's bevause zwift is asking 130w and so wirh that inclination, 130w are
with that speed. Zwift has internal function to match power using both
inclination and speed. If you want I can add a setting to disable this
behavior but this works beautifully for example with the pid hr feature

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 8 nov 2024 alle 18:33 Gabriel Stelmach <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
For reference this is about this one

https://github.com/cagnulein/qdomyos-zwift/commit/6cd52efe77c15b440c3c1a1e78b123dc3ca19b9c

**Comment by gabrielstelmach** [comment]
> If you want I can add a setting to disable this behavior but this works beautifully for example with the pid hr 

I don't want to create drama, but thinking about other futures users who are not going to dig so deep, such kind of feature would be nice to be around.

After all, is `textevent` a thing to QZ? As I mentioned above no message is displayed and I wonder if this is a bug or just not valid.

**Comment by cagnulein** [comment]
> > If you want I can add a setting to disable this behavior but this works beautifully for example with the pid hr 
> 
> 
> 
> I don't want to create drama, but thinking about other futures users who are not going to dig so deep, such kind of feature would be nice to be around.


Yeah no problem I can do, I'm just overwhelmed by tickets in these days 
> 
> 
> 
> After all, is `textevent` a thing to QZ? As I mentioned above no message is displayed and I wonder if this is a bug or just not valid.

I didn't handle at all but I can add easily, same as above :)

**Comment by gabrielstelmach** [comment]
Thanks for your assistance, mate. I'm going to close this with no further action.

**Comment by cagnulein** [comment]
Let leave this open, they are easy to do, let's see if I have time next week
