### ISSUE TITLE
[BUG]Matrix T75 XUR Console- No Incline

### ISSUE THREAD

**Issue by bobknox1007** [cagnulein/qdomyos-zwift#2758]
**Describe the bug**
QZ app won't receive incline from FTMS connection to Matrix T75 XUR console.

**To Reproduce**
Speed is working fine, but incline from Zwift to QZ app doesn't work.   However, if I use QZ app to control incline then the treadmill accepts the input from QZ app.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Sat_Nov_9_10_12_37_2024.log](https://github.com/user-attachments/files/17688423/debug-Sat_Nov_9_10_12_37_2024.log)
[debug-Sat_Nov_9_10_12_37_2024.log](https://github.com/user-attachments/files/17688424/debug-Sat_Nov_9_10_12_37_2024.log)

**Comment by cagnulein** [comment]
Did you set the zwift credentials in qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 nov 2024 alle 16:23 bobknox1007 ***@***.***>
ha scritto:

**Comment by bobknox1007** [comment]
Yes, i added my credentials in QZ.

**Comment by bobknox1007** [comment]
Sorry, my Username didn't save.  Let me retry.

**Comment by bobknox1007** [comment]
Thanks, that worked.  The Zwift incline must be an average because the treadmill changes incline constantly so I'm going to increase the # of delay seconds.

**Comment by cagnulein** [comment]
Yes it's an average. Qz is polling it every 5 seconds, I can't do more
because of ziwfr policy but in the closed beta you can use this
https://github.com/cagnulein/qdomyos-zwift/pull/2718

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 nov 2024 alle 16:36 bobknox1007 ***@***.***>
ha scritto:
