### ISSUE TITLE
[REQ] Manual Incline on FTMS

### ISSUE THREAD

**Issue by kard8** [cagnulein/qdomyos-zwift#2760]
**Is your feature request related to a problem? Please describe.**
I would like to add incline to my FTMS bike. I am missing out on elevation gain activities in Strava.

**Describe the solution you'd like**
Manual incline button which decreases speed and increases target resistance 

**Describe alternatives you've considered**
None

**Additional context**
-

**Comment by cagnulein** [comment]
Sorry but I don't understand @kard8  which bike do you have? Share a debug log from qz with the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
Do you mean changing the resistance automatically?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 10 nov 2024 alle 15:30 kard8 ***@***.***> ha
scritto:

**Comment by kard8** [comment]
Yes. I want to change resistance in order to simulate the incline. Is it
possible?

**Comment by cagnulein** [comment]
You can use the smartspin2k  @doudar 
Let me know
