### ISSUE TITLE
[BUG] echelon not staying connected

### ISSUE THREAD

**Issue by Kehill84** [cagnulein/qdomyos-zwift#2761]
**Describe the bug**

bike will connect to app for 3 or 4 seconds but then the bike will disconnect and the app will close. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 14 pro
[debug-Sun_Nov_10_18_09_45_2024.log](https://github.com/user-attachments/files/17693479/debug-Sun_Nov_10_18_09_45_2024.log)

 - OS: [e.g. iOS8.1] iOS 18.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi, is it working OK with the echelon app on the same phone?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 nov 2024 alle 00:24 Kehill84 ***@***.***> ha
scritto:

**Comment by Kehill84** [comment]
Yes/No. I was able to get the bike to connect to echelon app to see if
there was an update required but I the freestyle ride seems to be missing
so I cannot attempt a ride to see if it will stay connected.

**Comment by cagnulein** [comment]
are you able to download the free app nrfconnect and check if you can connect to it with this? in the log that you sent me it seems that the bike is not able to connect at all. seems like the bluetooth controller is broken. Let me know

**Comment by Kehill84** [comment]
It does connect to that app

**Comment by cagnulein** [comment]
did you also try to reinstall the QZ app?

**Comment by Kehill84** [comment]
No but I can.


Also it does connect to echelon app as I finally found the free style ride.

**Comment by cagnulein** [comment]
I don't think it's the issue but it worth a try

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 11 nov 2024 alle 12:55 Kehill84 ***@***.***> ha
scritto:

**Comment by Kehill84** [comment]
So that actually worked! Ugh!!! This is just since last update from apple
that I have had an issue.

Thank you! I will try a ride later today and make sure it holds up!

**Comment by cagnulein** [comment]
that's great! maybe a cache issue from iOS
