### ISSUE TITLE
Sole F65 Treadmill stopps a few seconds after starting a run

### ISSUE THREAD

**Issue by DoByG94** [cagnulein/qdomyos-zwift#2763]
**Describe the bug**
Sole F65 treadmill keeps stopping a few seconds after starting a run. This only happens when it's connected to the QZ app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on the treadmill
2. Start the QZ app
3. Start the treadmill (with the start button) and start a QZ activity

**Expected behaviour**
A continuous run on the treadmill, with the Power, Elevation, HR and Pace data being stored in a FIT file by QZ

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS: Android 14

**Append a debug log**

[drive-download-20241112T100935Z-001.zip](https://github.com/user-attachments/files/17714778/drive-download-20241112T100935Z-001.zip)

**Comment by cagnulein** [comment]
probably similar to #2712

**Comment by DoByG94** [comment]
Yes, but sending you a log so we can figure it out.

**Comment by cagnulein** [comment]
i set it as a reference for me :) you mentioned one important thing: that you see a cool down state on the treadmill when you start qz? is it the case?

**Comment by DoByG94** [comment]
Here is a [video](https://streamable.com/ikboq8) and a new log.
[debug-Tue_Nov_12_12_25_30_2024.log](https://github.com/user-attachments/files/17715058/debug-Tue_Nov_12_12_25_30_2024.log)

**Comment by cagnulein** [comment]
ok so there is for sure a command that is interpretated as a stop or similar. I will create a separate branch to find it out. I will be back in a couple of minutes

**Comment by DoByG94** [comment]
If the app is on when I start the run on the treadmill, It only goes for 3-4 sec and then counts back and stops. In the video, I started the app a few seconds later (it connects around 00:25), then goes for 3-4 sec again and starts counting back from 29 down before it stops. So it should be something going on in the first 5 sec of the app activity.

**Comment by cagnulein** [comment]
i guess i found something. it's about this. let me try without this https://github.com/cagnulein/qdomyos-zwift/commit/216440520fee3d6a59abdbc5fe1692545f941cbe

**Comment by DoByG94** [comment]
I will test and report back.

**Comment by cagnulein** [comment]
@DoByG94 any news?
