### ISSUE TITLE
SRAM AXS Controller for Virtual Gearing

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2768]
[Sram AXS Log (1).log](https://github.com/user-attachments/files/17718486/Sram.AXS.Log.1.log)
![image](https://github.com/user-attachments/assets/520eb129-9d50-42ed-88e6-745a9ae39dd8)
![image](https://github.com/user-attachments/assets/ca6b2830-75b2-49c2-bd42-5bdb70e3d8d1)

**Comment by cagnulein** [comment]
![Screenshot 2024-11-11 at 2 31 07 p m](https://github.com/user-attachments/assets/0543b207-6a6e-4b0b-b602-a0e1d8e9f68a)

**Comment by poett1** [comment]
@cagnulein seems like this has been disabled due to crypto with commit [fb8de46](https://github.com/cagnulein/qdomyos-zwift/commit/fb8de4606a74d75d3b2ddc8b16fca72163f6962f). Can you please explain this further?

Thanks!

**Comment by cagnulein** [comment]
@poett1 It never worked because of the crypto protocol of the controllers

**Comment by GaborWnuk** [comment]
FYI: crypto solved in https://github.com/GaborWnuk/sram-axs , feel free to analyse.

**Comment by cagnulein** [comment]
Wow @GaborWnuk thanks!

**Comment by cagnulein** [comment]
@poett1 are you still interesting on this? with the help of @GaborWnuk i created a pr for this https://github.com/cagnulein/qdomyos-zwift/pull/4943
