### ISSUE TITLE
[REQ] Resistance Offset for RGT cycling

### ISSUE THREAD

**Issue by shoulih** [cagnulein/qdomyos-zwift#277]
Like Zwift, RGT cycling is able to connect to Qz and the Auto Resistance control seems to work as well.
However, the resistance value set by RGT cycling seems to be a little too low for my bike, a Proform CBC with the digital resistance control from 1-16.
For example,
0% slope - > 5 resistance value
1% slope - > 6 resistance value
7% slope - > 10 resistance value
8% slope - > 11 resistance value

I tried to increase the Zwift Resistance Offset, but it didn't work.  Also, I can't seem to be able to adjust the resistance from QZ after the Auto Resistance has been disabled from QZ's UI.

Thanks in Advance!

**Comment by cagnulein** [comment]
The auto resistance button is designed to blocks every controlled
resistance, so it works fine ;) just reneable it.

About the swift resistance offset, do you have a log about it and rgt?

Il lun 19 apr 2021, 21:46 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
![image](https://user-images.githubusercontent.com/66762397/115311335-5a407380-a124-11eb-809b-fc13d00b7cb3.png)
[debug-Mon_Apr_19_15_12_02_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6339438/debug-Mon_Apr_19_15_12_02_2021.log)

swift resistance offset has been increased from 4 to 24, which makes no different.
Debug log has been attached.

BTW, qZ runs very well on Raspberry Pi Zero W for RGT to connect as it creates the same FTMS service every time qZ on Pi 0 restarts.  The hard part is that I still didn't figure out how to "Use Mile unit in UI" :-)

**Comment by cagnulein** [comment]
fixed, pull it and build.
what do you mean about Mile unit?

**Comment by shoulih** [comment]
Pulled your fix from the github and rebuilt it on my pi 0.  But for some reason, the result is the same - didn't see the swift resistance offset makes any difference.
New debug log attached:

[debug-Tue_Apr_20_11_11_17_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6345827/debug-Tue_Apr_20_11_11_17_2021.log)

BTW, I turned on "Use Mile unit in UI" option via qml interface on Pi 0, but this setting didn't persist and still shows "Km" in UL.

**Comment by cagnulein** [comment]
got it. for raspberry use
-bike-resistance-gain and -bike-resistance-offset parameter
also use -miles to enable the miles

**Comment by cagnulein** [comment]
pull it again, i guess i fixed it without using external parameters

**Comment by shoulih** [comment]
pulled your latest fix, but got a build error:

![image](https://user-images.githubusercontent.com/66762397/115577352-35114980-a279-11eb-92f2-58fc4713b39e.png)

**Comment by cagnulein** [comment]
@p3g4asus could you please check this?

**Comment by p3g4asus** [comment]
I am sorry for that. It is a 5.12 version issue.
Just replace the line:
```cpp
            qDebug() << "Scripts contains an error:"<< jscript << "error" << jsv.errorType();
```
with:
```cpp
#if (QT_VERSION < QT_VERSION_CHECK(5, 12, 0))
            int errorType = 255;
#else
            int errorType = jsv.errorType();
#endif
            qDebug() << "Scripts contains an error:"<< jscript << "error" << errorType;
```

@cagnulein Should I make a PR?

**Comment by cagnulein** [comment]
No thank you @p3g4asus i will commit later today

**Comment by shoulih** [comment]
Thank you both for your help.  I made the change @p3g4asus suggested locally and made a successful build on my Pi.
However,  "swift resistance offset" still doesn't seem to work when start the app without using external parameters on Pi.

Need another debug-log?

Thanks again guys!

**Comment by cagnulein** [comment]
Does the miles setting works?

Il mer 21 apr 2021, 19:50 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
Sorry "miles" doesn't seem to work either, which has been enable via "-qml"parameter:

![image](https://user-images.githubusercontent.com/66762397/115601969-42d3c880-a293-11eb-9222-1211f15d0e5c.png)

**Comment by cagnulein** [comment]
So strange, I'm missing something. Tomorrow i will check this again

Il mer 21 apr 2021, 20:20 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
no worries.

**Comment by cagnulein** [comment]
i rechecked again, it works for me...how can i start qdomyos? just with the -qml argument?

**Comment by shoulih** [comment]
sudo ./qdomyos-zwift -qml to open the qml interface to set the value or option, then I close it.
Next..
sudo ./qdomyos-zwift to start qdomyos

**Comment by shoulih** [comment]
BTW, do you want me to test it on Android?

**Comment by cagnulein** [comment]
Ok this is the issue! You will have to use ONLY and ALWAYS with -qml :)

Il mer 21 apr 2021, 21:54 shoulih ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
I didn't build it yet

Il mer 21 apr 2021, 21:57 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
ok, how do I switch the normal UI after starting from "sudo ./qdomyos-zwift -qml"?

**Comment by shoulih** [comment]
Just to confirm that now "swift resistance offset" works very well with RGT cycling when starting QZ with qml ""sudo ./qdomyos-zwift -qml".  How can I make it work with normal UI?

Thanks Again for this enhancement!

**Comment by cagnulein** [comment]
Why you want normal ui?
It's quite deprecated

Il gio 22 apr 2021, 03:24 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
the normal ui runs a lot faster than the qml interface on pi 0.

**Comment by cagnulein** [comment]
hah ok understood. in order to use the old UI you will always need to pass
the command line parameter

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 apr 2021 alle ore 06:57 shoulih ***@***.***>
ha scritto:

**Comment by shoulih** [comment]
I really don't mind passing command line parameters; what will be the correct syntax to use "swift resistance offset"?

Got a Segmentation fault:

![image](https://user-images.githubusercontent.com/66762397/115662998-a4784f00-a2f4-11eb-86c2-ee361032f49b.png)

Thanks!

**Comment by cagnulein** [comment]
add the value after the parameter, so for example
-bike-resistance-offset 10


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 apr 2021 alle ore 07:56 shoulih ***@***.***>
ha scritto:

**Comment by shoulih** [comment]
it works like a charm!!

**Comment by shoulih** [comment]
@cagnulein I can't seem to get "Miles" unit work with the "-miles parameter and I tried both:
 sudo ./qdomyos-zwift/src/qdomyos-zwift -no-log -bike-resistance-offset 10 -miles 1
 sudo ./qdomyos-zwift/src/qdomyos-zwift -no-log -bike-resistance-offset 10 -miles

The UI on the odometer still shows km, so does the odometer value.

![image](https://user-images.githubusercontent.com/66762397/117051784-c9dd6380-accb-11eb-8115-d01f9c3037f3.png)


Did I do anything wrong?

Thanks,

**Comment by cagnulein** [comment]
I didn't implemented there i guess

Il mar 4 mag 2021, 20:28 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
any easy workaround to get or rebroadcast the odometer value in miles? don't worry about the UI
I don't mind hard-coding and recompiling the QZ

**Comment by cagnulein** [comment]
Where do you want to see the Miles?

**Comment by shoulih** [comment]
I want to have the odometer value that rebroadcasts to RGT Cycling app in miles

Thanks

**Comment by cagnulein** [comment]
If i remember correctly i don't send distance over ftms. So you should
change then metric on RGT, isn't it?

Il mar 4 mag 2021, 21:53 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
Oh, I didn't know QZ doesn't send distance over ftms, so what data that QZ send to RGT in addition to Candance value?

For my Proform CBC, only Candance value is consistent across the LED display on the  bike, the QZ app and the RGT screen app.
The speed is the same between the LED display on the  bike and the QZ android app in mile/hour, but 10 mile/hour more displayed on the RGT screen app.  Is the RGT speed based on some conversion instead of the speed value over FTMS?

**Comment by cagnulein** [comment]
RGT use power, cadence and speed from QZ but i guess they recalculated it
using power as zwift does :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 5 mag 2021 alle ore 19:52 shoulih ***@***.***>
ha scritto:

**Comment by shoulih** [comment]
Both power and cadence are sent from QZ to the RGT screen app correctly.  Only speed is 10 mile/hour higher.

Is there a way to reduce the power on QZ?

Thanks,

**Comment by cagnulein** [comment]
I guess you're thinking it wrong. I mean rgt it's a simulation, you will
not have the same qZ speed, because, as i said, they're calculated it based
on Power, inclination, wind...

Il mer 5 mag 2021, 20:54 shoulih ***@***.***> ha scritto:

**Comment by shoulih** [comment]
I guess I understand the RGT's simulation now; I was just trying to see if I can match RGT speed to Bike/QZ speed by reducing the power output, which is used in the RGT's simulation I suppose, via some settings in QZ or RGT.

**Comment by shoulih** [comment]
Looks like you implemented the "Watt offset" in the advance settings already, which is what exactly I am looking for.

**Comment by cagnulein** [comment]
Yes :)

Il gio 6 mag 2021, 00:29 shoulih ***@***.***> ha scritto:

**Comment by blancmunier** [comment]
Hello @shoulih ,
I'm planning to buy the Proform CBC. Will I then be able to use Zwift/RGT, simply by downloading the QDomyos-Zwift application on my iphone, or do I need to use a Raspberry Pi Zero ?
Thanks a lot for your answer ;-))
Yvan

**Comment by cagnulein** [comment]
@blancmunier you can use just your iphone :)

**Comment by blancmunier** [comment]
great thanks @cagnulein !
@shoulih , sorry if it's off-topic, but cannot find a way to write you directly. Any feedback on the Proform CBC is very welcome? I'm quite tall - 195cm - do you think the Proform CBC fits any height ?
Thank you !
