### ISSUE TITLE
[BUG] Resistance does not recalibrate after incline

### ISSUE THREAD

**Issue by mlacey42** [cagnulein/qdomyos-zwift#2773]
**Describe the bug**
Sometimes after riding up an incline, the resistance will rise and not recalibrate after. I usually need to restart the app to fix the resistance.

For ex. Going up an incline, the resistance will rise to 27. After the incline, I’ll go downhill, but the resistance will remain at 27.

**To Reproduce**
1. Ride up an incline
2. See resistance rise
3. Continue past incline
4. Check if resistance is recalibrated

**Expected behavior**
After an incline, I expect the resistance to be recalibrated based on the terrain. If the terrain is flat/downhill after the incline, I expect the resistance to decrease.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 
 - Version 17.6.1

**Append a debug log**
[debug-Wed_Nov_13_03_00_34_2024.log](https://github.com/user-attachments/files/17729508/debug-Wed_Nov_13_03_00_34_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
it's because you have enabled the

Change gears using knob (Experimental)

in the echelon setting.

disable it and it would work fine

Let me know

**Comment by mlacey42** [comment]
Sorry, forgot to reply! I think you're right. Haven't seem to run into the issue in my most recent rides. Thanks!
