### ISSUE TITLE
[BUG] not connecting to treadmill 

### ISSUE THREAD

**Issue by Lmrsimpson** [cagnulein/qdomyos-zwift#2776]
**Describe the bug**

Treadmill is started, Peloton class started & paused, QZ started, heart rate connects, WZ never picks up treadmill stats.  I do say yes when asked to follow class.
**To Reproduce**
1. Go to tread start to .5
2. Start peloton on iPad 
3. Start QZ on iPhone
4. Say yes to follow class
5. Heart rate connects from heart rate monitor
6. Treadmill never connects to QZ
[debug-Wed_Nov_13_06_23_18_2024.log](https://github.com/user-attachments/files/17732204/debug-Wed_Nov_13_06_23_18_2024.log)
[debug-Wed_Nov_13_06_23_18_2024.log](https://github.com/user-attachments/files/17732229/debug-Wed_Nov_13_06_23_18_2024.log)
![Fri Mar 29 05_47_32 2024_peloton_image](https://github.com/user-attachments/assets/20e2f0ba-a2c8-4986-907e-8f5541be7d30)
![Fri Mar 29 05_44_33 2024_peloton_image](https://github.com/user-attachments/assets/7ea096c6-d8f2-4b10-9c4a-867a03a032c5)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 9
 - OS: [e.g. iOS18.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi enable this under settings, treadmills options 

![image](https://github.com/user-attachments/assets/d7b667d7-0801-4105-9bb2-6862a97ad7b0)

**Comment by Lmrsimpson** [comment]
Hi,

Turning that on stopped the app from picking up my heart rate monitor & didn’t pick up incline metrics. The only metrics it showed was speed.

Linda


On Nov 13, 2024, at 7:31 AM, Roberto Viola ***@***.***> wrote:

﻿

Hi enable this under settings, treadmills options

Upload.from.GitHub.for.iOS.png (view on web)<https://github.com/user-attachments/assets/d7b667d7-0801-4105-9bb2-6862a97ad7b0>

**Comment by cagnulein** [comment]
ok @Lmrsimpson so disable that setting and then restart qz.
From the startup of qz you have to wait more than 1 minutes to get the values from the treadmill. in the log that you sent me at the beginning you keep it open only for 10 seconds.
The 1 minute thing is about the firmware of your treadmill that's very old and it takes a lot. @janabouc helps me with this in the past. Let me know!
