### ISSUE TITLE
IFIT not loading at startup on nordictrack commercial 2950

### ISSUE THREAD

**Issue by bvdomo** [cagnulein/qdomyos-zwift#2777]
Hello, 

have installed QZ app on NordicTrack treadmill and can connect to Zwift.  Basic functions work fine, but had some loading bugs which were a nuisance, but are now worse since latest IFIT updates. Here’s a summary of what happened:

1) during startup get a tablet is loading message
2) treadmill boots to a blank screen that has a google search bar and a settings icon.  The settings icon opens and closes instantly when pressed. 
3) to open IFIT, I must swipe up from the bottom to see available apps and click on workout player. 
4) this autostarts a workout in IFIT.  
5) I must then stop and exit the workout to get to main IFIT startup page.  
6) from there, I can start a workout. 
7) when running workout in Zwift, the android contol board constantly pops up through the workout making it difficult to control treadmill through the screen. 
8) I’m unable to access treadmill settings from Android Screen like we did during the install
9) clicking on the system settings icon loads a blue screen that says ARDA IS RUNNING. 
10) have not been able to get auto incline feature to work at all.  This isn’t a big deal to me, but might be indicative of something else that may be wrong.  

I’ll attach some photos and to see if that helps.  

Let me know if you have any ideas on how to fix.  It’s workable, but a pain.  And my wife will never be able to figure how to start it.  

thanks, 
Brian
![IMG_3130](https://github.com/user-attachments/assets/b4a52862-d3b4-45da-9a51-8b34f2cf9c35)
![IMG_3131](https://github.com/user-attachments/assets/2a5d15f4-5c86-41fb-9e35-b369c399acae)
![IMG_3132](https://github.com/user-attachments/assets/ae3c91f7-6be8-4544-a565-44fdbaae834d)
![IMG_3133](https://github.com/user-attachments/assets/590b9d7b-11ab-487c-b0e4-3c4145b02d20)
![IMG_3135](https://github.com/user-attachments/assets/1e85a371-9d0f-4ad3-942f-46f33507ff5a)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
The ifit bridge is very hard to maintain because ifit is changing so many things in the time.

I will try to revisit it but I can't guarantee a timing. In the autumn and winter I'm overwhelmed by tickets 

I may suggest to use an old apk of the ifit app that it's more compatible with qz?

**Comment by victorypoint** [comment]
@bvdomo, some answers for you... Hope this helps.

1. during startup get a tablet is loading message
  - that's normal when in privileged mode.
2. treadmill boots to a blank screen that has a google search bar and a settings icon. The settings icon opens and closes instantly when pressed.
  - the blank screen is normal in privileged mode... just swipe up as you found out to access the android icons. The new iFit2 software has prevented access to the settings (gear icon)
3. to open IFIT, I must swipe up from the bottom to see available apps and click on workout player.
4. this autostarts a workout in IFIT. 
5. I must then stop and exit the workout to get to main IFIT startup page.
6. from there, I can start a workout.
  - Don't click on workout player first - this starts a manual iFit2 workout as you discovered. Instead click on the Account Login icon.
7. when running workout in Zwift, the android contol board constantly pops up through the workout making it difficult to control treadmill through the screen.
  - This sounds like the onscreen swipes that QZ is sending for workout auto-speed and auto-incline are making strange things happen onscreen. Note that QZ auto-workout mode does not work with iFit2 yet. I suggest reverting to the older iFit1 for now.
8. I’m unable to access treadmill settings from Android Screen like we did during the install
  - Again I suggest rolling back to iFit1 for now.
9. clicking on the system settings icon loads a blue screen that says ARDA IS RUNNING.
  - Yeah don't click on that icon. That's only for iFit2 settings.
10. have not been able to get auto incline feature to work at all. This isn’t a big deal to me, but might be indicative of something else that may be wrong.
  - Roll back to iFit1 for now.

**Comment by cagnulein** [comment]
@bvdomo Any news?

**Comment by bvdomo** [comment]
Oh, sorry for being slow.  Just saw the notification when clearing my spam folder.  I’ve just been running it as is with IFIT 2, and not having any issues other than not having the auto incline/ speed.  Having issues with the treadmill (again), so am finally replacing with a used Life Fitness Integrity SE3 HD.  Hoping QZ can connect to the Bluetooth to run Zwift. 

Thanks for your help and for the follow up.

**Comment by cagnulein** [comment]
Ok let me know if you need help!
