### ISSUE TITLE
[BUG] app doesn’t read heart rate from apple watch

### ISSUE THREAD

**Issue by doing180** [cagnulein/qdomyos-zwift#2779]
**Describe the bug**
I can see my heartrate on the iPhone app, but it doesn’t appear on either the qd phone app or the peloton app (which is running on my iPad). The only way to see my heartrate in the peloton app in my iPad is to connect it to the peloton app on my watch. 

**Expected behavior**
After I hit start on both the qd watch app and phone app, I used to be able to see my heartrate on rate in the phone app. That no longer occurs. 

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: [e.g. iOS18.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
Add any other context about the 
[debug-Thu_Nov_14_07_43_26_2024.log](https://github.com/user-attachments/files/17748829/debug-Thu_Nov_14_07_43_26_2024.log)
problem here.

**Comment by cagnulein** [comment]
Heart rate belt name setting in qz must be set to disabled and press OK and
restart qz
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 13:59 doing180 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@doing180 Any news?
