### ISSUE TITLE
Create Qz compatible with Xbox Controller 

### ISSUE THREAD

**Issue by rahmax7** [cagnulein/qdomyos-zwift#2783]
Kindly create QZ app compatible to use with Xbox wireless Controller... So we can operate virtual shifting of gears from Xbox controller instead of opening mobile /app to handle virtual gears in Rouvy app...

Please must implement this...

**Comment by cagnulein** [comment]
I can add it, but it wouldn't be simpler with a Bluetooth cheap remote
device already handled in qz?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 19:12 rahmax7 ***@***.***> ha
scritto:

**Comment by rahmax7** [comment]
I dont know please check xbox bluetooth controller
