### ISSUE TITLE
Zwift Ride Shifting has no Effect

### ISSUE THREAD

**Issue by Japhie84** [cagnulein/qdomyos-zwift#2785]
**Describe the bug**
Hi Roberto! I hope it‘s okay to reach out to you. I downloaded the iPhone App a couple of days ago. My goal: connect the Zwift Ride with MyWoosh. After testing for several hours and reading through the internet i decided to create this ticket.

What is working so far:
- Zwift Ride Play Buttons connected to the App
- Zwift Hub One successfully connected to the App
- Experimental Zwift Feature activated to shift from 1-24 and not 1-999
- I can see the gears shifting (tile activated)
- MyWoosh connection (heartrate, resistance, cadence) to app via bluetooth is working
- I can feel hills from MyWoosh while pedaling

What is not working:
- Shifting the gears has absolutely no effect. I can see the changes in the app 1-24 but there is no difference in the output.

—> Everything is working except for the gears to have an effect

**Expected behavior**
Shifting to a higher gear creates more resistance and due to this a higher watt output.

**Screenshots**
Unfortunately you can just feel it.

**Desktop (please complete the following information):**
 - MyWoosh is running on a desktop with windows 10

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18.1
 - App: 2.17.0

Am I doing something completely wrong?

Thank you!

Best
Philipp

**Comment by cagnulein** [comment]
Hi @Japhie84 I guess I already solved this. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
Yes bike settings, wahoo and you can customize them!

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 nov 2024 alle 13:36 Japhie84 ***@***.***> ha
scritto:

**Comment by Japhie84** [comment]
@cagnulein: I‘m really impressed. The amount of options is just amazing. I tested it today for a couple of hours an it was 100% stable. Thank you so much!

**Comment by Japhie84** [comment]
Hi Roberto! I tried to buy you a coffee but my credit card is not accepted. Do you own Paypal?BestPhilippAm 16.11.2024 um 13:50 schrieb Roberto Viola ***@***.***>:﻿
Yes bike settings, wahoo and you can customize them!



Let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 16 nov 2024 alle 13:36 Japhie84 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Thanks! PayPal.com/cagnulein
