### ISSUE TITLE
[REQ] Cadence Sensor As A Treadmill

### ISSUE THREAD

**Issue by ggdup** [cagnulein/qdomyos-zwift#2789]
I own a Nordic Trainer trainer which is a ski machine. I attached a Cycling Speed Sensor to it. I want to be able to use it as a treadmill in running apps because the skiing dynamics are closer to running than cycling (no free wheeel when skiing).

Thanks in advance!

**Comment by ggdup** [comment]
Note: it would be great if the Cadence Gain could take effects for treadmills. (This would allow me to make the speed realistic).

**Comment by cagnulein** [comment]
ok i will try to make it asap!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 16 nov 2024 alle ore 15:14 Guillaume Dupre <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
hi @ggdup I checked and if:
- you remove the sensor from the cadence sensor setting and press ok
- disable the cadence sensor as a bike
- set the sensor instead on the power sensor setting under accessories in qz and press ok
- enable the power sensor as a treadmill

you should already obtain the desired result

Let me know!

**Comment by guillaumedupre** [comment]
Hi @cagnulein this seems to work indeed however, the cadence reading is not correct. It seems capped at ~200rpm. A lot like https://github.com/cagnulein/qdomyos-zwift/issues/2769#issuecomment-2472905860

**Comment by cagnulein** [comment]
hi @guillaumedupre @ggdup are you on ios or android?

**Comment by guillaumedupre** [comment]
@cagnulein it works! Thank you very much

**Comment by cagnulein** [comment]
Glad to hear it!


Il giorno mar 19 nov 2024 alle 17:27 guillaumedupre <
***@***.***> ha scritto:
