### ISSUE TITLE
[REQ] Add URL to Peloton Ride in Email Summary

### ISSUE THREAD

**Issue by hoveeman** [cagnulein/qdomyos-zwift#279]
As a user it would be great to have a link to the ride in the Email Summary, so that I can review my emails and click the link to take me directly to the ride on Peloton. 

There are a lot of rides that have the same name on Peloton and can be hard to search for. It would be great to have a link directly to the ride in the email if I ever want to take the class again.

You could remove "Great workout!" and display a Hyperlink with the ride name, like the email subject, and a link to the ride. 

[30 min 90s Ride - Cody Rigsby](https://members.onepeloton.com/classes/cycling?modal=classDetailsModal&classId=16512b7dfd5f4b11801972e9aa3af77e)

![IMG_1115](https://user-images.githubusercontent.com/18269595/115404146-0af95200-a1bb-11eb-8c92-2b78738578c0.PNG)

**Comment by cagnulein** [comment]
@hoveeman could you point me to the right classid number in the API? i tried to search it quickly but i can't find it

**Comment by cagnulein** [comment]
now i'm using these ones:

"https://api.onepeloton.com/api/workout/" + workout + "/performance_graph?every_n="
"https://api.onepeloton.com/api/workout/" + workout
"https://api.onepeloton.com/api/workout/" + workout + "/summary"

i guess the rideid is not inside these ones. Could you help me on this? I mean if you can address me to the rideid i can do this task easily

**Comment by hoveeman** [comment]
@cagnulein If you're using 
​/api​/workout​/{workoutId}
Pass the workoutId and you will get the following. This is from the example above. 
workoutId: 2def90243d3a4905af7e342fd8d04efd

> {  "created_at": 1618913427,
  "device_type": "apple_tv",
  "end_time": 1618915316,
  "fitbit_id": null,
  "fitness_discipline": "cycling",
  "has_pedaling_metrics": false,
  "has_leaderboard_metrics": false,
  "id": "2def90243d3a4905af7e342fd8d04efd",
  "is_total_work_personal_record": false,
  "metrics_type": null,
  "name": "Cycling Workout",
  "peloton_id": "2d73fb2c0cdd47d0a9bc5eeb35ac46af",
  "platform": "apple_tv",
  "start_time": 1618913516,
  "strava_id": null,
  "status": "COMPLETE",
  "timezone": "America/New_York",
  "title": null,
  "total_work": 0,
  "user_id": "redacted",
  "workout_type": "class",
  "total_video_watch_time_seconds": 1965,
  "total_video_buffering_seconds": 3,
  "v2_total_video_watch_time_seconds": 1964,
  "v2_total_video_buffering_seconds": 2,
  "total_music_audio_play_seconds": null,
  "total_music_audio_buffer_seconds": null,
  "created": 1618913427,
  "device_time_created_at": 1618899027,
  "is_skip_intro_available": false,
  "ride": {
    "availability": {
      "is_available": true,
      "reason": null
    },
    "class_type_ids": [
      "c87e20095d80463db5ce04df7fe2b989"
    ],
    "content_provider": "peloton",
    "content_format": "video",
    "description": "Take a ride through the classic tracks of the 90s while you sweat it out on the Bike.",
    "difficulty_estimate": 7.3052,
    "overall_estimate": 0.9972,
    "difficulty_rating_avg": 7.3052,
    "difficulty_rating_count": 24395,
    "difficulty_level": null,
    "duration": 1800,
    "equipment_ids": [],
    "equipment_tags": [],
    "extra_images": [],
    "fitness_discipline": "cycling",
    "fitness_discipline_display_name": "Cycling",
    "has_closed_captions": true,
    "has_pedaling_metrics": true,
    "home_peloton_id": "redacted",
    "id": "16512b7dfd5f4b11801972e9aa3af77e",
    "image_url": "https://s3.amazonaws.com/peloton-ride-images/f776f5a3d62cad5590efe50a68813f89ad730766/img_1617825519_40dd365f00e84dc0940d4711f1a08b29.png",
    "instructor_id": "baf5dfb4c6ac4968b2cb7f8f8cc0ef10",
    "individual_instructor_ids": [],
    "is_archived": true,
    "is_closed_caption_shown": true,
    "is_explicit": false,
    "has_free_mode": false,
    "is_live_in_studio_only": true,
    "language": "english",
    "origin_locale": "en-US",
    "length": 1975,
    "live_stream_id": "16512b7dfd5f4b11801972e9aa3af77e-live",
    "live_stream_url": null,
    "location": "psny-studio-1",
    "metrics": [
      "heart_rate",
      "cadence",
      "calories"
    ],
    "original_air_time": 1618160400,
    "overall_rating_avg": 0.9972,
    "overall_rating_count": 20113,
    "pedaling_start_offset": 60,
    "pedaling_end_offset": 1860,
    "pedaling_duration": 1800,
    "rating": 0,
    "ride_type_id": "c87e20095d80463db5ce04df7fe2b989",
    "ride_type_ids": [
      "c87e20095d80463db5ce04df7fe2b989"
    ],
    "sample_vod_stream_url": null,
    "scheduled_start_time": 1618160400,
    "series_id": "ff9345a98f3d402e819b0eed30458a72",
    "sold_out": false,
    "studio_peloton_id": "6190358b318b4bd6a3d4847a0d059ea7",
    "title": "30 min 90s Ride",
    "total_ratings": 0,
    "total_in_progress_workouts": 62,
    "total_workouts": 121667,
    "vod_stream_url": null,
    "vod_stream_id": "16512b7dfd5f4b11801972e9aa3af77e-vod",
    "captions": [
      "en-US"
    ],
    "join_tokens": {
      "on_demand": "redacted"
    },
    "flags": [],
    "excluded_platforms": []
  },
  "achievement_templates": [
    {
      "id": "1b0f7ba0b9e945e88c93792484995c00",
      "name": "Three's Company",
      "slug": "threes_company",
      "image_url": "https://s3.amazonaws.com/peloton-achievement-images-prod/a1a3e04a6cd64933a5099dc26bd63552",
      "description": "Awarded for working out with 2 friends."
    }
  ],
  "leaderboard_rank": null,
  "total_leaderboard_users": 0,
  "ftp_info": {
    "ftp": 0,
    "ftp_source": null,
    "ftp_workout_id": null
  },
  "device_type_display_name": "App"
}

In the   "ride": { section you get an id, which is the rideid, which corresponds to the URL of the ride I pasted above. It also includes an image of the ride if you want to do something fun with that, maybe attach it to the email?

    "id": "16512b7dfd5f4b11801972e9aa3af77e",
    "image_url": "https://s3.amazonaws.com/peloton-ride-images/f776f5a3d62cad5590efe50a68813f89ad730766/img_1617825519_40dd365f00e84dc0940d4711f1a08b29.png",

You could append the id to the end of this URL
"https://members.onepeloton.com/classes/cycling?modal=classDetailsModal&classId=" + 16512b7dfd5f4b11801972e9aa3af77e

**Comment by cagnulein** [comment]
Thanks i will do tomorrow

**Comment by fooeynet** [comment]
How would this work when a user does multiple rides within the same session?

**Comment by cagnulein** [comment]
If you hit stop at the end of each one, there is no problem at all

Il mer 21 apr 2021, 07:51 fooeynet ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done @hoveeman 
the only thing is now i sent it as plain text, we should migrate to HTML.
Are you able to create (or copy) an html layout and add it to a new task?
i'm not so good in graphic :D

also if you want you can create a PR here in Github. The code is very simple: check the bottom function on the homeform.cpp, is where i create the email

**Comment by hoveeman** [comment]
@cagnulein great work! I’ll do a PR and take a look at that section. No guarantee on timing... 

I’ll also see if I can add the peloton ride stats https://github.com/cagnulein/qdomyos-zwift/issues/255 while I’m at it.
