### ISSUE TITLE
[BUG] Auto resistance jumping around

### ISSUE THREAD

**Issue by Brownsteiger92** [cagnulein/qdomyos-zwift#2796]
**Describe the bug**
When I’m in a peloton workout, using auto resistance to my Echelon EX3, the resistance frequently jumps around. Sometimes it starts a climb way too early, and sometimes it stops a climb way too early, easily 30-45 seconds ahead of the instructor. 

Other times it randomly drops down to 30-40%, and then back up to 70%, which can be way stronger than the requested resistance. 

This was raised yesterday on Facebook and I’ve been able to replicate it today. I don’t know if it’s a QZ issue or a peloton one, as the black line on the screenshot is what the autoresistance was trying to get to, and you’ll see the red line shoot back up/down where I’m having to manually adjust it. 

[debug-Mon_Nov_18_17_40_45_2024.log](https://github.com/user-attachments/files/17805056/debug-Mon_Nov_18_17_40_45_2024.log)

![IMG_0112](https://github.com/user-attachments/assets/a13dbe64-d695-4a13-b78e-354d4e906ab3)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 18.0.1
 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Thanks, I will check it ASAP, I'm currently at the hospital

**Comment by Brownsteiger92** [comment]
No problem, hope all is well. Certainly fixing this not as urgent as hospital!
________________________________

**Comment by Brownsteiger92** [comment]
Thanks, I will try that next time and hopefully it’ll work.

Will report back!
________________________________

**Comment by Brownsteiger92** [comment]
Hi Roberto,

Just to let you know that all is fixed with this now. It was me selecting “yes” on the auto resistance pop up during the intro that caused the problem. Starting it at 00:00 worked perfectly.

Thanks for your help.

Chris
________________________________
