### ISSUE TITLE
Bike not moving play not working

### ISSUE THREAD

**Issue by Dacallander** [cagnulein/qdomyos-zwift#2797]
**Describe the bug**
Not sure this a bug. Everything was working in both Rouvy and Zwift. Added Zwift play controllers and QZ stop working. The play controllers respond to Zwift but the bike won't move. I followed the connection process for shifting gears. 

**To Reproduce**

Just followed recommended process

**Expected behavior**
Expected to see the gear on screen and the play controllers to shift gears. It does change the resistance but no gear indicator is visible on Zwift. 

**Screenshots**

**Desktop (please complete the following information):**
 OZ on samsung tablet galaxy Tab 7. Android 12

Zwift on PC windows 

![inbound5594137782296835166](https://github.com/user-attachments/assets/5a18c0d5-08a0-4bcf-aa6c-225b0d7eb5fa)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by Dacallander** [comment]
I can't attach the bug report. The files are greyed out and I can't select them

**Comment by cagnulein** [comment]
Upload them from the github web interface

**Comment by cagnulein** [comment]
@Dacallander Any news?
