### ISSUE TITLE
[BUG] Distance in end report doesn't match distance in FIT file

### ISSUE THREAD

**Issue by fre-bod** [cagnulein/qdomyos-zwift#2798]
**Describe the bug**
Distance in end report doesn't match distance in FIT file. I'm using a Kingsmiths Walkingpad X23. 

**To Reproduce**
1. Start a walking session on treadmill 
2. Walk for some time 
3. Stop session
4. See distance in end report
5. Open .FIT file in viewer or upload to Garmin Connect
6. See distance from file
7. Distance from end report is always longer than in file, example 1.7 km vs. 1.2 km. 

**Expected behavior**
Distances should be the same. 

[debug-Tue_Nov_19_09_41_13_2024.log](https://github.com/user-attachments/files/17813576/debug-Tue_Nov_19_09_41_13_2024.log)

**Desktop:**
 - OS: Android
 - Version 14

**Smartphone:**
 - Device: Samsung S22+
 - OS: OneUI
 - Version 6.1

**Comment by cagnulein** [comment]
hi @fre-bod first of all can you please join the beta here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and update the version from the store to check that if i didn't already fixed? thanks!

**Comment by fre-bod** [comment]
Hi @cagnulein, you are correct in that the issue is resolved in the beta, thank you!

**Comment by cagnulein** [comment]
That's great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 nov 2024 alle 22:49 fre-bod ***@***.***> ha
scritto:
