### ISSUE TITLE
[ENH] Match emailed units to local preferences

### ISSUE THREAD

**Issue by fooeynet** [cagnulein/qdomyos-zwift#280]
If the user has chosen The option to use miles in the UI then the emailed stats after the ride should also be presented in miles/mph for distance and speed. The default seems to be kilometers/kph.

Additionally, total output in the email is presented in joules instead of kilojoules as in the UI.

**Comment by cagnulein** [comment]
i have already fixed in the 2.6.11
Which version do you have?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 apr 2021 alle ore 07:33 fooeynet ***@***.***>
ha scritto:

**Comment by fooeynet** [comment]
LOL I just saw the fix in the code, and then my app updated from 2.6.8 to 2.6.11. I'll close it! You're too fast!
