### ISSUE TITLE
Can’t connect app to treadmill or bike 

### ISSUE THREAD

**Issue by Arielsobelman** [cagnulein/qdomyos-zwift#2800]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
[debug-Tue_Nov_19_12_38_25_2024.log](https://github.com/user-attachments/files/17814061/debug-Tue_Nov_19_12_38_25_2024.log)

**Comment by cagnulein** [comment]
ok disable the ftms treadmill and press ok and restart qz. it's not a ftms treadmill, that's why
let me know!

**Comment by cagnulein** [comment]
also i checked and the treadmill doesn't have the capabilites to change the inclination or speed from the bluetooth interface (i guess for safety reason in your country) so it can't have auto speed or inclination unfortunately
