### ISSUE TITLE
No resistance change when changing virtual gears in my whoosh

### ISSUE THREAD

**Issue by ty2050** [cagnulein/qdomyos-zwift#2802]
**Describe the bug**
No resistance change when changing virtual gears in my whoosh

**To Reproduce**
open QZ nightly 
Settings - Accessories - Zwift devices- Zwift click on
Settings - tiles - Gears  - on order index 12 ok
Restart - open turn on zwift click confirm gear changing 1-12

**Expected behavior**
Resistance changing

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Andriod S6 tablet
 - 13
 - One UI 5.1.1

**Append a debug log**
[debug-Wed_Nov_20_18_01_56_2024.log](https://github.com/user-attachments/files/17827203/debug-Wed_Nov_20_18_01_56_2024.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @ty2050 can you upload the log in a new comment? i can't download it
Let me know!

**Comment by ty2050** [comment]
[debug-Wed_Nov_20_18_03_29_2024.log](https://github.com/user-attachments/files/17828528/debug-Wed_Nov_20_18_03_29_2024.log)
[debug-Wed_Nov_20_18_01_56_2024.log](https://github.com/user-attachments/files/17828532/debug-Wed_Nov_20_18_01_56_2024.log)
not sure which one it was

**Comment by cagnulein** [comment]
i still can't download them. are you able to from these links? otherwise send me to email to roberto.viola83 at gmail.com
maybe today github has some issues

**Comment by ty2050** [comment]
[debug-Wed_Nov_20_18_03_29_2024.log](https://github.com/user-attachments/files/17828605/debug-Wed_Nov_20_18_03_29_2024.log)
[debug-Wed_Nov_20_18_01_56_2024.log](https://github.com/user-attachments/files/17828608/debug-Wed_Nov_20_18_01_56_2024.log)

**Comment by cagnulein** [comment]
ok now they worked, let me check them

**Comment by cagnulein** [comment]
ok good news @ty2050 i guess it was i already fixed here https://github.com/cagnulein/qdomyos-zwift/pull/2801
can you please try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/11921984890/artifacts/2210048711
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by ty2050** [comment]
Will give it a go tomorrow thanks again for the super quick response!

**Comment by cagnulein** [comment]
Perfect let me know so I will merge it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 nov 2024 alle 11:15 ty2050 ***@***.***> ha
scritto:

**Comment by ty2050** [comment]
I was unable to change the inclination in the app. Using Mywoosh at a 3% incline I could definitely feel it. Gearing was working aswell. See attached logs. 
[debug-Thu_Nov_21_16_05_06_2024.log](https://github.com/user-attachments/files/17840812/debug-Thu_Nov_21_16_05_06_2024.log)
[debug-Thu_Nov_21_16_08_46_2024.log](https://github.com/user-attachments/files/17840813/debug-Thu_Nov_21_16_08_46_2024.log)
[debug-Thu_Nov_21_16_10_49_2024.log](https://github.com/user-attachments/files/17840815/debug-Thu_Nov_21_16_10_49_2024.log)
[debug-Thu_Nov_21_16_22_05_2024.log](https://github.com/user-attachments/files/17840817/debug-Thu_Nov_21_16_22_05_2024.log)

**Comment by cagnulein** [comment]
that's great!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 nov 2024 alle ore 07:25 ty2050 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
log checked @ty2050 are you sure they are the right log? i can see you changing the gears but not a connection from mywhoosh. did you set it as controllable? no inclination is sent
let me know!

**Comment by ty2050** [comment]
Not sure what you mean by setting as controllable? I just run QZ with the small pop up over the top. Then run mywoosh

**Comment by cagnulein** [comment]
@ty2050 on mywhoosh how do you pair qz? show me a screenshot

**Comment by ty2050** [comment]
Clearly I don't use the app connectly sounds like I am meant to virtualise the bike through QZ. I'd appreciate a guide. Screenshot attached 
![Screenshot_20241121_171013_MyWhoosh](https://github.com/user-attachments/assets/62c3022c-85ab-40d7-8a8b-a867bb7bef51)

**Comment by cagnulein** [comment]
nope :) you have to connect qz there and you can't use qz on the same device of mywhoosh. QZ must be on a device, and mywhoosh on another. on mywhoosh then, you have to pair your phone not the victory
Let me know

**Comment by ty2050** [comment]
You say that but it does work at least for what I'm using it for gear shifting. I'll be out the rest of the day I'll run some testing tomorrow.

**Comment by cagnulein** [comment]
ok but it's an unconventional way to use qz :) probably it works only on this trainer. Anyway if you are happy i'm happy too :)

**Comment by ty2050** [comment]
Just tried with version 2.18.6 on pixel connected to S6 Tab Gearing and inclination working on my woosh.

**Comment by cagnulein** [comment]
Ok with the same setup that you did on rouvy right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 02:51 ty2050 ***@***.***> ha
scritto:

**Comment by ty2050** [comment]
I've never used Rouvy only mywoosh

**Comment by cagnulein** [comment]
Sorry I was meaning mywhoosh  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 07:21 ty2050 ***@***.***> ha
scritto:

**Comment by ty2050** [comment]
Yeah same settings just ran the app the was it was meant to run instead of in the background.

**Comment by cagnulein** [comment]
@ty2050 Are we OK with this?

**Comment by ty2050** [comment]
> @ty2050 Are we OK with this?

Yeah mate running the beta works for now just waiting for the play store version to be updated. Ticket closed.
