### ISSUE TITLE
Virtual gearing is not working. Do not change resistance for my whoosh or Zwift. 

### ISSUE THREAD

**Issue by Gregorius2000** [cagnulein/qdomyos-zwift#2803]

**Comment by cagnulein** [comment]
Hi @Gregorius2000 I don't see anything. Put the debug log as a new comment here

Thanks

**Comment by Gregorius2000** [comment]
[debug-Wed_Nov_20_11_04_57_2024.zip](https://github.com/user-attachments/files/17830532/debug-Wed_Nov_20_11_04_57_2024.zip)

**Comment by cagnulein** [comment]
It's because you have the erg mode enabled in qz
Disabled it and it should work
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 nov 2024 alle 13:30 Gregorius2000 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Gregorius2000 Are we OK with this?
