### ISSUE TITLE
[BUG] proform carbon TL PFTL59722c.0

### ISSUE THREAD

**Issue by gaussien** [cagnulein/qdomyos-zwift#2806]
Phone samsung sm-a526w
Android 14 one ui 6.1

Ifit bluetooth I use
Speed from 2k/h to 2.9k/h up and down
I use inclination from 0 to 4% up and down 
End session
[inbound3404463843993596064.zip](https://github.com/user-attachments/files/17833374/inbound3404463843993596064.zip)

**Comment by cagnulein** [comment]
thanks i will check it in the next days!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 20 nov 2024 alle ore 17:05 gaussien ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@gaussien i checked the log and it seems that it's the same profile of proform_treadmill_505_cst. Can you try this specific one in qz? set it and restart qz
Let me know!

**Comment by gaussien** [comment]
I just tried the proform_treadmill_505_cst it doesn't work

Le jeu. 21 nov. 2024, 04 h 29, Roberto Viola ***@***.***> a
écrit :

**Comment by gaussien** [comment]
there is a connection I see the speed and incline but I cannot change them
from qz

Le jeu. 21 nov. 2024, 09 h 16, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
ok i will check if this profile have some small differences and I will
report back

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 nov 2024 alle ore 15:19 gaussien ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
yes got the small differences, i'm implementing them

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 nov 2024 alle ore 15:21 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@gaussien done

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11955609179

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by gaussien** [comment]
there is a connection  I see the speed and incline but I cannot change them
from the new trial qz

Le jeu. 21 nov. 2024, 09 h 45, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
can you please upload a debug log from qz so i can check if the implementation is fine https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?
thanks

**Comment by gaussien** [comment]
[debug-Thu_Nov_21_11_01_50_2024.log](https://github.com/user-attachments/files/17848759/debug-Thu_Nov_21_11_01_50_2024.log)

**Comment by cagnulein** [comment]
@gaussien could you please check if this is better? i added more init frames

https://github.com/cagnulein/qdomyos-zwift/actions/runs/11968203758

**Comment by gaussien** [comment]
detects speed and incline but still does not control

Le ven. 22 nov. 2024, 02 h 19, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
ok i will check for something else.
in the hci log that you provided, you were in the manual workout, right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle ore 10:18 gaussien ***@***.***>
ha scritto:

**Comment by gaussien** [comment]
Yes manual workout

Le ven. 22 nov. 2024, 04 h 40, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
I didn't forget about this. I'm really overwhelmed by tickets

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 11:02 gaussien ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @gaussien i found some issues on the init phase, i hope that was the error https://github.com/cagnulein/qdomyos-zwift/actions/runs/12048217281

let me know

**Comment by gaussien** [comment]
I'm coming home Monday, I'll keep you informed. Thanks a lot

Le mer. 27 nov. 2024, 04 h 18, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
Sounds good, thanks!


Il giorno mer 27 nov 2024 alle 22:06 gaussien ***@***.***> ha
scritto:

**Comment by gaussien** [comment]
I just tried the last proform_treadmill_505_cst today it doesn't work

Le mer. 27 nov. 2024, 16 h 13, Roberto Viola ***@***.***> a
écrit :

**Comment by gaussien** [comment]
Latest update not work

**Comment by cagnulein** [comment]
Do you have a fresh debug log?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 18:11 gaussien ***@***.***> ha
scritto:

> Latest update not work
>

**Comment by cagnulein** [comment]
Thanks just to be sure because it's starting to be a real mistery

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 18:57 gaussien ***@***.***> ha
scritto:

> I will create a new debug
>
> Le lun. 2 déc. 2024, 12 h 42, Roberto Viola ***@***.***> a
> écrit :
>
> > Do you have a fresh debug log?
> >
> > Roberto Viola
> > Software engineer and open source enthusiast
> > http://robertoviola.cloud
> >
> >
> >
> > Il giorno lun 2 dic 2024 alle 18:11 gaussien ***@***.***> ha
> > scritto:
> >
> > > Latest update not work
> > >

**Comment by gaussien** [comment]
Fresh debug log

Le lun. 2 déc. 2024, 12 h 59, Roberto Viola ***@***.***> a
écrit :

> Thanks just to be sure because it's starting to be a real mistery
>
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
>
>
>
> Il giorno lun 2 dic 2024 alle 18:57 gaussien ***@***.***> ha
> scritto:
>
> > I will create a new debug
> >
> > Le lun. 2 déc. 2024, 12 h 42, Roberto Viola ***@***.***> a
> > écrit :
> >
> > > Do you have a fresh debug log?
> > >
> > > Roberto Viola
> > > Software engineer and open source enthusiast
> > > http://robertoviola.cloud
> > >
> > >
> > >
> > > Il giorno lun 2 dic 2024 alle 18:11 gaussien ***@***.***> ha
> > > scritto:
> > >
> > > > Latest update not work
> > > >

**Comment by cagnulein** [comment]
You have to attach to github web interface otherwise I can't see it 
Thanks

**Comment by gaussien** [comment]
[debug-Mon_Dec_2_13_09_08_2024.log](https://github.com/user-attachments/files/17982573/debug-Mon_Dec_2_13_09_08_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 19:53 gaussien ***@***.***> ha
scritto:

**Comment by gaussien** [comment]
good work it works inclination and speed both work thank you

Le mar. 3 déc. 2024, 04 h 33, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
finally! glad to hear this!
