### ISSUE TITLE
[BUG] I can't connect the heart rate sensor Zephyr hrm

### ISSUE THREAD

**Issue by Daeamon** [cagnulein/qdomyos-zwift#2807]
**Describe the bug**
I dont see my HTM Zephyr in listing of hearth rate sensor.

**Smartphone (please complete the following information):**
Device: Huawei P60 Pro
OS: Android
Version EMUI 13.1.0

**Comment by cagnulein** [comment]
Is it a Bluetooth one? If so maybe it's connected already to another app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 nov 2024 alle 06:03 Daeamon ***@***.***> ha
scritto:

**Comment by Daeamon** [comment]
> it's connected already to another app

No, I haven't connected it to another program yet after recently factory resetting my smartphone.

**Comment by Daeamon** [comment]
> Is it a Bluetooth one?

Yes but i dont see it in nRF Connect, But I see it in the list of possible devices for connection in the Bluetooth settings of my smartphone.

**Comment by cagnulein** [comment]
So it's a Bluetooth 2. Qz can connect only to Bluetooth 4 and above
devices. I suggest to use another one

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 21 nov 2024 alle 06:48 Daeamon ***@***.***> ha
scritto:
