### ISSUE TITLE
No resistance change when changing virtual gears in Zwift w Saris H3

### ISSUE THREAD

**Issue by gagnonalex** [cagnulein/qdomyos-zwift#2809]
**Describe the bug**
No virtual gearing or resistance change is possible through the app (android 14) when connected to Zwift on both mac and windows (version 1.78.0 build 136426) 

**To Reproduce**
1. Setup the QZ app (gear from Zwift + Zwift click enable)
2. Connect the Saris H3 to the Qz app
3. Connect to Zwift keeping only the resistance with the phone, both cadence and power with the virtual wahoo kickr
4. Try to change the resistance on a free ride via the app or the click and nothing happens

**Expected behavior**
Gears change, resistance goes up

**Desktop (please complete the following information):**
 - OS: Windows 11

**Smartphone (please complete the following information):**
 - Device: Samsung 21fe 
 - OS: Android 14 

**Append a debug log**

[debug-Thu_Nov_21_21_21_55_2024.log](https://github.com/user-attachments/files/17856351/debug-Thu_Nov_21_21_21_55_2024.log)

**Additional context**

**Comment by cagnulein** [comment]
Hi set your saris under ftms bike setting in the bike options. It should
solve this

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 03:59 Alexandre Gagnon <
***@***.***> ha scritto:

**Comment by gagnonalex** [comment]
Hi, for others landing here, this did not fixed it but the new beta version currently being reviewed by Google did! Thanks @cagnulein  for the reactivness!

**Comment by cagnulein** [comment]
Glad to hear it!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle ore 15:12 Alexandre Gagnon <
***@***.***> ha scritto:
