### ISSUE TITLE
[BUG] Horizon 7.8AT-04 not sending data

### ISSUE THREAD

**Issue by VanhaPieru** [cagnulein/qdomyos-zwift#2812]
[inbound3753649469134251986.zip](https://github.com/user-attachments/files/17870553/inbound3753649469134251986.zip)
**Describe the bug**

Horizon 7.8AT-04 not sending any data. Works in Zwift directly, but not in QZ, and not in the official Horizon AtZone app.
![inbound2297513002835839420](https://github.com/user-attachments/assets/2458e5fc-7d73-4432-b472-1c38999454fa)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22+
 - OS: Android 14
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by VanhaPieru** [comment]
Wow, this worked! Thanks

**Comment by cagnulein** [comment]
Glad it worked.


Il giorno sab 23 nov 2024 alle 00:31 VanhaPieru ***@***.***>
ha scritto:
