### ISSUE TITLE
[BUG] Is there support for the Nordictrack R35?

### ISSUE THREAD

**Issue by chriswill3** [cagnulein/qdomyos-zwift#2814]
Greetings, is there support for the Nordictrack R35? I see it works with iFit, does that mean it will sync with QZ?

**Comment by cagnulein** [comment]
Yes! At least for reading metrics
If you want also control follow this with the ifit app
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 19:02 chriswill3 ***@***.***>
ha scritto:

**Comment by chriswill3** [comment]
That answers my question, thanks! Control might be nice, I may circle back to that in the future.
