### ISSUE TITLE
[BUG] zwift click not working 

### ISSUE THREAD

**Issue by Jflem81** [cagnulein/qdomyos-zwift#2815]
**Describe the bug**
Zwift click is found by QZ but is not changing virtual gears on QZ. 

**To Reproduce**
I followed the steps in the YouTube video to pair zwift click. 
I opened qz, paired in mywoosh, tried a 'free ride' and pressed buttons but nothing happened. Gear did change through the tiles in qz. 

**Expected behavior**
I expected to see the gears change on the app when I press zwift click buttons. I then expect the resistance change on my smart trainer. Which then changes in Mywoosh. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 11 home 

**Smartphone (please complete the following information):**
 - Device: motorola edge 23
 - OS: Android 
 - Version 14

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
[debug-Sat_Nov_23_09_30_19_2024.log](https://github.com/user-attachments/files/17880360/debug-Sat_Nov_23_09_30_19_2024.log)
[debug-Sat_Nov_23_09_39_36_2024.log](https://github.com/user-attachments/files/17880361/debug-Sat_Nov_23_09_39_36_2024.log)
[debug-Sat_Nov_23_09_45_13_2024.log](https://github.com/user-attachments/files/17880362/debug-Sat_Nov_23_09_45_13_2024.log)
[debug-Sat_Nov_23_09_41_21_2024.log](https://github.com/user-attachments/files/17880363/debug-Sat_Nov_23_09_41_21_2024.log)

  
  
**Additional context**
Thanks!

**Comment by cagnulein** [comment]
Is the zwift click firmware updated in the zwift companion app? This is
mandatory
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 nov 2024 alle 16:51 Jflem81 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Contact zwift, they will send a new unit. It's a known issue on their
device. I have already other users with the same thing

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 nov 2024 alle 17:11 Jflem81 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Jflem81 Any news?

**Comment by Jflem81** [comment]
Actually no. Zwift support kept directing me to what seemed like power users but not employees who keep not answering questions. Most recent advice I received was to get an apple device to update the firmware.

I have been sick then busy then sick again so haven't had time to play with it more. I will give it another try after the holidays.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
that's strange I have multiple users with the same issues, and they said that it's a known bug and they offer to a replacement. i guess you have to ask louder :)

**Comment by Jflem81** [comment]
It was definitely like talking to a wall. I'd literally say 'I have tried to follow instructions posted on your website' and the guy would respond with a link to those instructions and ask me to try.

I'll get back to you if I learn more.

Merry Christmas

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jflem81** [comment]
Happy new year Roberto

I got no help from Zwift but managed to borrow an iPad and installed the companion app. It was able to update the Click and I got it  to shift on Qz and that changed it in real life on my the trainer with Mywoosh.

Thanks again for the support!

Jeff

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
amazing! please remember to rate the app and the support on the store and if you can join patreon even with the smaller tier https://www.patreon.com/cagnulein
