### ISSUE TITLE
Virtual Gear not shown in Zwift

### ISSUE THREAD

**Issue by mattleech** [cagnulein/qdomyos-zwift#2816]
**Describe the bug**
Virtual Gear selection is not shown in Zwift.

 I'm sure I've tried every combination of QZ setting and Zwift connection multiple times, but to no avail. At one point, it did seem like changing gear on the Play Controllers had a small but delayed effect to the Kickr resistance and power output (as would a change of virtual gear), but the gear indicator did not show up in Zwift, and like I said, any significant change of resistance was delayed significantly.

On one of the video tutorials I tried, it suggested that I connect Zwift Power source to 'QZ Power', then connect the Play Controllers, then connect Zwift Resistance source to the virtual Kickr (...000 33), but in the first instance I don't even see a QZ Power meter as an available selection in the Zwift Pairing screen. I always see the Virtual Kickr (...0000 33), but the gear indicator does not show up for that connection anyway. 

**To Reproduce**
1. Too many attempts and combinations of settings to list.
2. Summary 1: Play controllers connected to QZ.
3. Zwift Resistance source is connected to Virtual Kickr V5 (...0000 33). 
4. Gear not shown in Zwift game.

**Expected behavior**
Gear selection indicator to be shown in top-left of Zwift game screen.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11

**Smartphone (please complete the following information):**
Samsung Note 10+
Android 12
QZ app 2.18.7

**Append a debug log**
Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
Used all kinds of file explorers, including CX, but none of them can find the directory org.cagnulein.qdomyoszwift. This means I am unable to attach the logs.
  
**Additional context**

**Comment by cagnulein** [comment]
I guess I answered you everywhere. Follow my suggestions there and share a debug log of the issue

Thanks

**Comment by mattleech** [comment]
I'll come back to the problem with uploading a log file, but for the moment, I have made progress with your suggestion of renaming my phone's bluetooth connection to something simple and short. I now see the virtual gear selection in Zwift 😍

**Comment by cagnulein** [comment]
Amazing!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 nov 2024 alle 11:10 Matt Leech ***@***.***>
ha scritto:
