### ISSUE TITLE
Fitness Master T25 incline doesn't work [BUG]

### ISSUE THREAD

**Issue by feymark** [cagnulein/qdomyos-zwift#2820]
The speed control works just fine with Master Fitness T25. The incline however is not registered in QZ. The incline gets stuck at 0 in the app and every time the incline is increased using the app the treadmill incline will be set to 1.

[debug-sun_nov_24_20_01_41_2024.log](https://github.com/user-attachments/files/17894604/debug-sun_nov_24_20_01_41_2024.log)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP
It seems a fitshow app. Did you try if wirh the kinomap app are you able to
change speed and inclination? I guess so. If so I will add this as a
fitshow too
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 24 nov 2024 alle 20:40 feymark ***@***.***> ha
scritto:

**Comment by feymark** [comment]
Hi,Fitshow doesn’t work. Kinomap works when I add the FTMS bluetooth. I attach a new debug log, don’t know if it tells you anything new.Vänliga hälsningarAndreas Feymark+46 73-369 39 6524 nov. 2024 kl. 20:46 skrev Roberto Viola ***@***.***>:﻿
Thanks I will check it ASAP

It seems a fitshow app. Did you try if wirh the kinomap app are you able to

change speed and inclination? I guess so. If so I will add this as a

fitshow too

Let me know!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 24 nov 2024 alle 20:40 feymark ***@***.***> ha

scritto:

**Comment by feymark** [comment]
Hi,I will attach from GitHub. Everything works with Kinomap.Vänliga hälsningarAndreas Feymark+46 73-369 39 6525 nov. 2024 kl. 06:39 skrev Roberto Viola ***@***.***>:﻿
Hi @feymark you have to attach any files from the github web interface directly otherwise I can't see it
About kinomap : do you have the same inclination issue also there?

**Comment by cagnulein** [comment]
Can you please follow this with kinomap https://ultrawyrypa.pl/index.php/2024/11/05/qz-fitness-connect-ifit-treadmil-to-zwift-and-not-only/ so I will check what they do?

I have an idea in mind (ftms start command as note for me) but in this way we will be sure

Let me know!

**Comment by feymark** [comment]
I will do this when I get home from work./Andreas25 nov. 2024 kl. 07:01 skrev Roberto Viola ***@***.***>:﻿
Can you please follow this with kinomap https://ultrawyrypa.pl/index.php/2024/11/05/qz-fitness-connect-ifit-treadmil-to-zwift-and-not-only/ so I will check what they do?
I have an idea in mind (ftms start command as note for me) but in this way we will be sure
Let me know!

**Comment by cagnulein** [comment]
#2559 
[Master T25 Kinomap 241126.log](https://github.com/user-attachments/files/17914185/Master.T25.Kinomap.241126.log)
