### ISSUE TITLE
[BUG] Continuos beeping when speed is modified by the %T. speed tile

### ISSUE THREAD

**Issue by lorenzogavanna** [cagnulein/qdomyos-zwift#2825]
**Describe the bug**
Continuos beeping when speed is modified by the T.Speed tile.
During a workout if you change the speed with the T.Speed tile the treadmill starts to beep every second. The speed changes only the first time but it seems that the treadmill gets some inputs that ignores (luckly).

**To Reproduce**
1. Load a workout zwo with powerzones
2. Start it and change the speed with the T.Speed tile
3. The treadmill statrs to beep every second

**Expected behavior**
No beep out of the one that changes the seed the first time or changes in the treadmill if qz is sending something.

**Screenshots**
No matter if it's under or over 100% of the T. Speed

OS: G7 thinkQ - Android 10
Mobvoi Home Treadmill Plus
QZ app 2.18.7
debug log attached.
[debug-Mon_Nov_25_10_21_31_2024.log](https://github.com/user-attachments/files/17900698/debug-Mon_Nov_25_10_21_31_2024.log)

**Comment by cagnulein** [comment]
it should be fixed now https://github.com/cagnulein/qdomyos-zwift/actions/runs/12007428217

let me know and thanks for the feedback

**Comment by lorenzogavanna** [comment]
Thank you for the fast quick! I tested it. Now it beeps not in all the % (i.e. 97 and 106 it does and 103 not) and less frequently, about every 3 seconds 
Debug attached 
[debug-Mon_Nov_25_11_25_42_2024.log](https://github.com/user-attachments/files/17901342/debug-Mon_Nov_25_11_25_42_2024.log)

**Comment by cagnulein** [comment]
got it, can you try this https://github.com/cagnulein/qdomyos-zwift/actions/runs/12008181619 ?

**Comment by lorenzogavanna** [comment]
Still does, can't figure out the "logic" behind those beeps. Can you see something from the log?
[debug-Mon_Nov_25_12_04_42_2024.log](https://github.com/user-attachments/files/17901979/debug-Mon_Nov_25_12_04_42_2024.log)

**Comment by cagnulein** [comment]
it's because the current speed and the request speed doesn't match. let me try another small patch

**Comment by cagnulein** [comment]
i have to do some simulation. it's just a math issue, don't worry :)
i will do it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 nov 2024 alle ore 12:10 lorenzogavanna <
***@***.***> ha scritto:

**Comment by lorenzogavanna** [comment]
okok don't worry it's not critical at all! Thank you again!

**Comment by cagnulein** [comment]
can you try this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/12010200801 ?

**Comment by lorenzogavanna** [comment]
Now is perfectly working! Sometimes it does a double beep (it happend randomly at 109%, 124%, 127% or 142%, of course edge case and not important since after that everythink worked properly). Let me know if you want more test or if, in your opinion, everyhing is ok! Thank you again

**Comment by cagnulein** [comment]
if you have a debug log to double check the double beeps i can check it
thanks

**Comment by lorenzogavanna** [comment]
[debug-Mon_Nov_25_14_18_43_2024.log](https://github.com/user-attachments/files/17909806/debug-Mon_Nov_25_14_18_43_2024.log)
That should be the one. If I recall correclty one was at around 8.4 km/h.

**Comment by cagnulein** [comment]
Thanks I will check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 nov 2024 alle 23:53 lorenzogavanna <
***@***.***> ha scritto:
