### ISSUE TITLE
Kickr Move Bluetooth Not found

### ISSUE THREAD

**Issue by alterverwalter1972** [cagnulein/qdomyos-zwift#2827]
I have a Kickr Move and set it up with the wizard
All Bluetooth devices appear but no connection is established. The Bluetooth symbol flashes and all the devices are displayed as Found.
I tried all options in settings but none worked.
I just want to be able to use my Zwift Play Controller in My Whoosh.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]17.7.1

**Smartphone (please complete the following information):**
 - IPhone 15 Plus

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Mo__Nov__25_11_28_05_2024.log](https://github.com/user-attachments/files/17901506/debug-Mo__Nov__25_11_28_05_2024.log)

  
**Additional context**

**Comment by cagnulein** [comment]
got the issue!
could you please install the free app nrfconnect and show me a screenshot about the move from the app?
Let me know

**Comment by alterverwalter1972** [comment]
completed😁Am 25.11.2024 um 11:58 schrieb Roberto Viola ***@***.***>:﻿
got the issue!
could you please install the free app nrfconnect and show me a screenshot about the move from the app?
Let me know

**Comment by cagnulein** [comment]
perfect set it under ftms bike in the bike options and restart qz and it should work
let me know!

**Comment by alterverwalter1972** [comment]
hi, I have another problem. Whenever I change gears with Zwift Play, my Wahoo Climb goes down or up. 😩

**Comment by cagnulein** [comment]
already fixed in the last build. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**remember to disable the ftms bike setting in the bike options in qz and press ok to engage this patch** when you will get the update

**Comment by alterverwalter1972** [comment]
My Wahoo Climb still goes down or up when I press the Zwift Play buttons.
I disable the ftms bike setting in the bike options in qz 2.18.8 and press ok.

**Comment by cagnulein** [comment]
can you provide a fresh debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?

**Comment by alterverwalter1972** [comment]
[debug-Do__Nov__28_12_20_42_2024.log](https://github.com/user-attachments/files/17947296/debug-Do__Nov__28_12_20_42_2024.log)

**Comment by cagnulein** [comment]
new version sent! let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle ore 12:27 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
please show me an update debug log, i would like to see if the patch is
working right
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle ore 13:41 alterverwalter1972 <
***@***.***> ha scritto:

**Comment by alterverwalter1972** [comment]
[debug-Do__Nov__28_13_45_53_2024.log](https://github.com/user-attachments/files/17948244/debug-Do__Nov__28_13_45_53_2024.log)

**Comment by cagnulein** [comment]
the log is still with the old version. that's why. i also sent you a newer version. build 961
update it from testflight app
let me know!

**Comment by alterverwalter1972** [comment]
perfect, it works. Thank you very much for the cool app and quick fix.

**Comment by cagnulein** [comment]
amazing! please remember to rate the app on the store if you didn't already and also join the patreon membership if you already did it to support the app https://www.patreon.com/cagnulein

Thanks!
