### ISSUE TITLE
[BUG] qz doesnt see Kickr Core via Bluetooth

### ISSUE THREAD

**Issue by di6i74l** [cagnulein/qdomyos-zwift#2828]
The qzApp does not see the Kickr via Bluetooth.
I have set FTMS to WIFI but still I cannot select the Kickr.
Moreover, the BT connection search of the qzApp loops indefinitely.
There was (only) once a note to restrict the bt device name to 4 letters which i did, but still, the problem remains.

The strange thing though is, that the QZ Windows 10 Version seems to work correctly and finds the Kickr but i need the Android Version of QZ up and running.

Kickr Core w/ Climb
Samsung Galaxy A33 5G on Android 14

I ve included a debug log:

[debug-Mon_Nov_25_13_14_29_2024[1].log](https://github.com/user-attachments/files/17902950/debug-Mon_Nov_25_13_14_29_2024.1.log)

What is going on here? Could this be an issue with the phone? am using it withouth error for other BT cycling apps (zwift, XERT, ...)

**Comment by cagnulein** [comment]
hi @di6i74l i guess you sent me the wrong debug log because i can't see any bluetooth devices at all here. could you please collect another one? do you see the devices in the top label in qz? if so it's for sure the wrong debug log, let me know!

**Comment by di6i74l** [comment]
Ciao Roberto, I ve generated a new one. but again, there is no reference to the Wahoo Kickr... 
[debug-Mon_Nov_25_13_59_33_2024[1].log](https://github.com/user-attachments/files/17903320/debug-Mon_Nov_25_13_59_33_2024.1.log)

**Comment by cagnulein** [comment]
i still don't see any device at all. does the nrfconnect app (free app on the store) shows your bluetooth devices? it seems there is a general issue on your phone. did you try to reboot it?

**Comment by cagnulein** [comment]
in qz what do you see in the top label? only connecting? are you sure about the permissions on qz? must be all granted
do you have another android device to try? which android flavour is it?

**Comment by cagnulein** [comment]
which android device is this? never found this issue before

**Comment by di6i74l** [comment]
yes and oddly enough the phone's bt connection did not fail on any other app
Galaxy A33 5G, Modellname SM-A336B/DSN
![image](https://github.com/user-attachments/assets/00fd7a73-0374-4bf3-964d-78422d4db38f)
![image](https://github.com/user-attachments/assets/7da11ce3-b9e7-446e-bc8a-993966953114)

**Comment by cagnulein** [comment]
did you try also to reinstall qz?

**Comment by di6i74l** [comment]
i did and also applied for the beta a bit a few days ago, and still it wasnt working. 
But i have reinstalled again just now and it works, this is great. who would have thought that it would be so simple. 
thank you very much indeed for taking your time!!
