### ISSUE TITLE
XT485 Spirit Treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#283]

**Comment by cagnulein** [comment]
[hci_snoop_2021_04_21_11_17_54.zip](https://github.com/cagnulein/qdomyos-zwift/files/6352826/hci_snoop_2021_04_21_11_17_54.zip)

**Comment by cagnulein** [comment]
#278 the protocol seems very similar to the sole one

**Comment by jonathancolledge** [comment]
I think both Spirit fitness and Sole are owned by Dyaco.

**Comment by cagnulein** [comment]
#918 @jonathancolledge do you still have this treadmill?

**Comment by jonathancolledge** [comment]
No, I had the Sole elliptical which I think has some similarities? I still have the elliptical and still hoping it'll come out of storage soon!

**Comment by cagnulein** [comment]
hah sorry I misread this ticket, you commented to help me ;)
