### ISSUE TITLE
[BUG] Usually i connect to a wahoo virtual connection

### ISSUE THREAD

**Issue by mminville** [cagnulein/qdomyos-zwift#2830]
Now i only see my iphone, i did a ride this morning with a wahoo connection, tonight its gone.

It still work, i still can use the app for riding, but why its gone all the sudden.

**To Reproduce**

Just try to connect.... i see my stryd pod that i dont use for biking and my iphone now.

**Expected behavior**
I was seeing 2 wahoo connection, i was always using the one with "33"

**Screenshots**
Nothing really to show, juste my iphone in the list and my stryd pod when zwift detect it.

**Desktop (please complete the following information):**
IOS

**Smartphone (please complete the following information):**
 - Device: Iphone 15
 - OS: iOS 18.01

**Append a debug log**

I can give you one, but i did a full reset of all options, and its still gone.
Maybe its on Zwift side ?  
  
**Additional context**

**Comment by cagnulein** [comment]
@mminville A debug log is required to check if you changed something.

If you didn't i suggest to reinstall zwift or check your router 

Let me know

**Comment by mminville** [comment]
Hi,

I got it!  Its my VPN (Nord VPN), i disabled it and the wahoo connection came back on both my apple tv and my ipad, i use one or the other.
Wierd because i have it since last week , i've use Zwift at least 3 times without any issue.

Sorry about that, but we know it can affect something now.

________________________________
De : Roberto Viola ***@***.***>
Envoyé : 26 novembre 2024 00:26
À : cagnulein/qdomyos-zwift ***@***.***>
Cc : Martin Minville ***@***.***>; Mention ***@***.***>
Objet : Re: [cagnulein/qdomyos-zwift] [BUG] Usually i connect to a wahoo virtual connection (Issue #2830)


@mminville<https://github.com/mminville> A debug log is required to check if you changed something.

If you didn't i suggest to reinstall zwift or check your router

Let me know

**Comment by cagnulein** [comment]
glad to hear it!

**Comment by mminville** [comment]
It didnt bug right away with the vpn, its why i never tought about it.


________________________________
De : Roberto Viola ***@***.***>
Envoyé : 26 novembre 2024 07:23
À : cagnulein/qdomyos-zwift ***@***.***>
Cc : Martin Minville ***@***.***>; Mention ***@***.***>
Objet : Re: [cagnulein/qdomyos-zwift] [BUG] Usually i connect to a wahoo virtual connection (Issue #2830)


glad to hear it!

**Comment by cagnulein** [comment]
it's about routing of the connection, not very easy to address it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 26 nov 2024 alle ore 13:37 Martin Minville <
***@***.***> ha scritto:
