### ISSUE TITLE
[BUG]no resistance with rouvy

### ISSUE THREAD

**Issue by DStaz** [cagnulein/qdomyos-zwift#2832]
**Describe the bug**
I don't have resistance with rouvy. Flat road or ascension is the same effort.

**Expected behavior**
At the same gear, if the road goes up I have to push more than on a flat road

**Desktop (please complete the following information):**
 Rouvy on windows 

**Smartphone (please complete the following information):**
 - Device: s20fe
 - OS: android
 - Version 13

**Append a debug log**
See file attached thx
[debug-Tue_Nov_26_10_36_57_2024.log](https://github.com/user-attachments/files/17917634/debug-Tue_Nov_26_10_36_57_2024.log)

**Comment by DStaz** [comment]
My trainer is a zwif hub

**Comment by cagnulein** [comment]
also you have the Use Resistance instead of Inclination setting enabled in the advanced settings. must be disabled

**Comment by cagnulein** [comment]
amazing!
