### ISSUE TITLE
App not displaying metrics

### ISSUE THREAD

**Issue by Jumbo829** [cagnulein/qdomyos-zwift#2835]
App connects fine to Pasyou s70 but does display any metrics while pedaling.

Google pixel 9
Android 15

**Comment by Jumbo829** [comment]
I'm having trouble getting a debug log. I enabled it in the experimental
settings and closed and reopened. I recreate the situation but there is no
debug file saved that I can find. I'm technically proficient. I'll keep
trying. Thanks.

**Comment by Jumbo829** [comment]
*not technically proficient

**Comment by Jumbo829** [comment]
It's downloading the debug log as a.fit file. Not sure how to open those.

**Comment by cagnulein** [comment]
Did you send them by email right? I will answer you there so
