### ISSUE TITLE
Echelon Bike not starting at correct resistance.

### ISSUE THREAD

**Issue by crossfit25** [cagnulein/qdomyos-zwift#2837]
**Describe the bug**
Echelon Bike not starting at correct resistance.  Bike is Connect EX-4S+.

**To Reproduce**
followed steps from FB post.

**Expected behavior**
I am expecting bike to start at 18 resistance.  It is starting at 32 instead.

**Smartphone (please complete the following information):**
Samsung Galaxy s22 ultra
 Android 14
 
[debug-Wed_Nov_27_08_38_06_2024.log](https://github.com/user-attachments/files/17935403/debug-Wed_Nov_27_08_38_06_2024.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@crossfit25 the problem is that you have the gear restore enabled in the bike options with value 17. this is applying to the current resistance of 18 going to the max. set the gear init value to 0 or to a lower value or disable the gear restore setting
let me know

**Comment by crossfit25** [comment]
Thanks.  That did it.  That option was not turned on.  I turned it on it changed it to 0 then turned it back off.  Thanks for all you do.  I know so many appreciate the great app you have put together.

**Comment by cagnulein** [comment]
glad it worked!
