### ISSUE TITLE
[BUG] WearOS HR not syncing to Android App HR tile

### ISSUE THREAD

**Issue by rdillinger** [cagnulein/qdomyos-zwift#2839]
**Describe the bug**
WearOS HR not syncing to Android App QZ HR tile (HR shows 0 in Android QZ App)

**To Reproduce**
1. Start Echelon Bike
2. Open Android QZ App, connect to bike
3. Click start
4. Open WearOS QZ app, click start
5. Android QZ App shows 0 HR, WearOS App shows actual HR

**Expected behavior**
Expect Android QZ app to show same HR as WearOS QZ app

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: S24Ultra
 - OS: 14
[debug-Wed_Nov_27_12_57_18_2024.log](https://github.com/user-attachments/files/17939224/debug-Wed_Nov_27_12_57_18_2024.log)
[debug-Wed_Nov_27_12_54_54_2024.log](https://github.com/user-attachments/files/17939225/debug-Wed_Nov_27_12_54_54_2024.log)
[debug-Wed_Nov_27_12_50_01_2024.log](https://github.com/user-attachments/files/17939226/debug-Wed_Nov_27_12_50_01_2024.log)
[debug-Wed_Nov_27_12_46_41_2024.log](https://github.com/user-attachments/files/17939227/debug-Wed_Nov_27_12_46_41_2024.log)

Several logs, I tried several times to get this to work.

**Comment by cagnulein** [comment]
@rdillinger Are we OK with this?
