### ISSUE TITLE
trying to get app to work with Wahoo Gymconnect to control treadmill

### ISSUE THREAD

**Issue by RussBrandt** [cagnulein/qdomyos-zwift#2840]
[debug-Wed_Nov_27_15_08_35_2024.log](https://github.com/user-attachments/files/17940531/debug-Wed_Nov_27_15_08_35_2024.log)
**Describe the bug**
I'm hoping you can supply some advice here.  I just purchased your QZ app with hopes to control my Woodway treadmill. It is an older Desmo model that has a csafe port on the control board. I cut a hole into the console and connected the csafe port to a Wahoo Gymconnect. I did this many many years ago right when Zwift was secretly beta testing Zwift Run. The Gymconnect wasa able to transmit the speed and grade of the treadmill (to my ipad at the time until they rolled out Android/PC compatibility).  I've always wanted to have Zwift control speed and grade and was hopeful that you app would  allow that.  I cannot get things to work.
Here's what I've done:
I've put Zwift credentials username and password into QZ. 
QZ will pick up the treadmill. However when I manually start treadmill QZ doesn't reflect any of the speed or grade the treadmill is doing.
In Zwift, I have new options to connect to Wahoo Treadmill and E25. I believe they are coming from the QZ app because I've never seen them before as choices.  Any one of them that I select doesn't pick up the manual speed or grade settings of the treadmill.
Do you happen to know if the communication to my treadmill is only "out"....meaning treadmill can only report out what it is doing and doesn't report back "in" to control speed or grade?
Any suggestions to get things working correctly? I attempted to attach debug as instructed

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  Android Galaxy S20 FE 5G
 - OS: Android
 - Version 13

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @RussBrandt just a confirmation first of all: is the E25 the right device coming from your treadmill?

**Comment by RussBrandt** [comment]
No, when Zwift works properly the Wahoo Gymconnect broadcasts Treadmill 067D.  Right after I loaded up your app, I noticed the app was picking Treadmill 067D also. I would think the app would then be able to at least display the speed and grade of the Treadmill like Zwift could do when connected to Treadmill but something isn't connecting right.ThanksOn Nov 28, 2024 12:32 AM, Roberto Viola ***@***.***> wrote:
hi @RussBrandt just a confirmation first of all: is the E25 the right device coming from your treadmill?

**Comment by cagnulein** [comment]
ok so this is the first issue: in the log qz is connect to the E25 not the treadmill.
in order to avoid this you have to choose the "TREADMILL" in the manual device setting in the advanced settings in qz and reboot it
If the problem persists, send me a fresh debug log
Let me know

**Comment by cagnulein** [comment]
show me a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

attach it directly from the github web interface otherwise i can't see it

**Comment by RussBrandt** [comment]
[debug-Thu_Nov_28_07_08_54_2024.log](https://github.com/user-attachments/files/17949523/debug-Thu_Nov_28_07_08_54_2024.log)
OK, hoping you now can see the debug file attached

**Comment by cagnulein** [comment]
@RussBrandt i guess i fixed the speed to 0 

but i have also to say that this treadmill doesn't have the capabilites to change speed/inclination by bluetooth. so you can't have auto speed/inclination using this treadmill by bluetooth.

the only way would be soldiering some wires from a raspberry with the qz raspberry build or the windows build of qz.

anyway this is the fix for android for the speed

https://github.com/cagnulein/qdomyos-zwift/actions/runs/12071304218

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by RussBrandt** [comment]
Ok thanks. So if I understand right that the wahoo gymconnect only allows me to read from the treadmill but it cannot allow commands back to the treadmill?  I suspect this is correct but do you know for sure?  Also, I do know that Woodway used to sell software for science laboratories that would allow treadmill control from a PC...so I'm thinking that it could be possible but needed someone to understand what protocol the Woodway uses and replicate it with their own software...this is what I thought you may have done.On Nov 28, 2024 8:02 AM, Roberto Viola ***@***.***> wrote:
@RussBrandt i guess i fixed the speed to 0
but i have also to say that this treadmill doesn't have the capabilites to change speed/inclination by bluetooth. so you can't have auto speed/inclination using this treadmill by bluetooth.
the only way would be soldiering some wires from a raspberry with the qz raspberry build or the windows build of qz.
anyway this is the fix for android for the speed
https://github.com/cagnulein/qdomyos-zwift/actions/runs/12071304218
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to ***@***.*** mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
do you have this software? i guess it's based on CSAFE right? qz can handle CSAFE but via serial port. there are other project on internet to play with csafe.

**Comment by RussBrandt** [comment]
No I don't have the software. I tried a few times to communicate with Woodway and I think I got a demo version. It was very old GUI and they wanted hundreds of dollars. On Nov 28, 2024 8:35 AM, Roberto Viola ***@***.***> wrote:
do you have this software? i guess it's based on CSAFE right? qz can handle CSAFE but via serial port. there are other project on internet to play with csafe.

**Comment by cagnulein** [comment]
yes but it's csafe based? if so csafe is a open protocol

**Comment by RussBrandt** [comment]
![csafe port on display panel](https://github.com/user-attachments/assets/82b04a4a-33b3-42a8-ad5f-1f2f54ce5006)
Yes I believe so. The Wahoo Gymconnect supposedly converts the csafe commands into a bluetooth and/or ANT signal that Zwift picks up.....at least that is what I understand. It seems you have WAY more aptitude and understanding of all this tech so I was thinking you'd know if it is possible to send commands to my treadmill to control it.  I know my treadmill is pretty old and the best solution is to probably just get a newer treadmill, but this Woodway Desmo is a tank and will last forever hardware wise.  Would this be a fun project for you to take on??

**Comment by cagnulein** [comment]
yes so the wahoo gymconnect converts them but only in a way, it doesn't accept command. so you should use the csafe directly. Unfortunately I don't have the time right now for this, maybe we can catch up in spring when all the people will stop to create ticket and send me email about this :D

**Comment by RussBrandt** [comment]
ok thanks. I defiantly will re contact you in the spring. In the mean time, is there anything you'd need to know that I can work on finding out? For instance, should I look for a schematic of the control board? A copy of the demo software that controls the treadmill? Anything else that can be useful? ....or is it pretty straight forward to program something in the csafe protocol?

**Comment by cagnulein** [comment]
First of all do you have already the pinout of the csafe port? You can try
to connect it to a pc and we can try to check if my assumption is correct

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle 21:51 RussBrandt ***@***.***>
ha scritto:
