### ISSUE TITLE
[BUG] peloton bike not working correctly with echelon app resistance

### ISSUE THREAD

**Issue by Dpmiller1986** [cagnulein/qdomyos-zwift#2841]
**Describe the bug**

iPhone running qz connected to smart spin. Peloton bike in just ride

iPad running echelon app

Qz is recognised as a bike but resistance isn’t correct.

echelon has 32 levels whereas peloton has 100

when changing gears on the smart spin controller the numbers will be the same so for
Example 32 resistance on peloton will be matched on echelon which isn’t correct 

conversion needs to be based on an ex3 or ex5s as sport bikes are too easy however I do have and have seen conversion tables for them.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

inhave a debug log and a video but it won’t let me attach them

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by Dpmiller1986** [comment]
Can’t attach video or debug log

**Comment by Dpmiller1986** [comment]
[ezyzip.zip](https://github.com/user-attachments/files/17944543/ezyzip.zip)

**Comment by cagnulein** [comment]
this is the fit file. I need the debug log one. The name of it starts with
the debug prefix
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle ore 08:51 Dpmiller1986 <
***@***.***> ha scritto:

**Comment by Dpmiller1986** [comment]
[debug-Wed_Nov_27_23_25_03_2024.log](https://github.com/user-attachments/files/17945875/debug-Wed_Nov_27_23_25_03_2024.log)
[debug-Wed_Nov_27_23_27_15_2024.log](https://github.com/user-attachments/files/17945876/debug-Wed_Nov_27_23_27_15_2024.log)

**Comment by cagnulein** [comment]
there are already 2 settings that are useful for this. in the echelon bike options in qz, there are the resistance gain and offset.

os you can set the offset to 0 and the gain to 0,32 to obtain a scaled value.
let's see if it now better on the echelon app

let me know

**Comment by Dpmiller1986** [comment]
![IMG_1408](https://github.com/user-attachments/assets/d1902987-7aaf-4ea4-8e1d-79e50324649d)

do I need to do it under echelon bike options?

**Comment by Dpmiller1986** [comment]
![IMG_1409](https://github.com/user-attachments/assets/1bab3a69-dafb-4cae-a67c-45463b27b055)

save the settings but it reverts back to default

**Comment by cagnulein** [comment]
did you press ok right to the value?

**Comment by Dpmiller1986** [comment]
Yes and I saw the message at the bottom saying settings saved

**Comment by cagnulein** [comment]
just tried and it worked on my end. are you setting 0.32 and not 0,32 ?

**Comment by Dpmiller1986** [comment]
So your original message had a , but using the . worked 👍

will test it and let you know thanks

**Comment by cagnulein** [comment]
yes my fault :)

**Comment by Dpmiller1986** [comment]
Ok tested it definitely much better two things I noticed…

resistance was too high so when they called out say a 15 I was on 11 on echelon for flat road - assume I adjust resistance offset by about 4?

Speed was really odd. Peloton screen showed say 18 echelon was sometimes higher or sometimes lower. QZ was always lower say around 11mph.

peloton said I did 5 miles echelon 3 and qz also said 3

**Comment by cagnulein** [comment]
Yes for the offset

For the speed you have also speed gain and speed offset under the advanced
settings

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 nov 2024 alle 23:29 Dpmiller1986 ***@***.***>
ha scritto:

**Comment by Dpmiller1986** [comment]
![IMG_1421](https://github.com/user-attachments/assets/eeef3535-5075-4af5-97b9-6e1d89e3e141)

this is what it’s currently set at. Any advice on what to set it as?

**Comment by cagnulein** [comment]
If it's almost lower you can set a speed gain of 1.6 to start

Peloton and echelon probably have 2 different complete algorithms for speed

**Comment by Dpmiller1986** [comment]
Ok great il fiddle round with the settings over the weekend but im happy this can be closed as its working  just needs fine tuning👍

**Comment by cagnulein** [comment]
ok let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 29 nov 2024 alle ore 12:07 Dpmiller1986 <
***@***.***> ha scritto:

**Comment by Dpmiller1986** [comment]
Tested today and used the speed gain under advanced settings.

qz and peloton match perfectly.

echelon about 2mph out at times but I’m very happy now thanks again!!!

**Comment by cagnulein** [comment]
glad to hear it!
