### ISSUE TITLE
[BUG] m1 mac support

### ISSUE THREAD

**Issue by droctothorpe** [cagnulein/qdomyos-zwift#2842]
**Describe the bug**
I downloaded the latest mac [release](https://github.com/cagnulein/qdomyos-zwift/releases/tag/2.10.97) but when I try to execute the binary, I get the following error:

```
zsh: exec format error: ./qdomyos-zwift
```

I suspect this is because it was compiled for intel macs rather than m-series / arm64 macs.

What are my options?

Thanks!

**Desktop (please complete the following information):**
 - OS: OSX
 - Version:  15.1

**Comment by droctothorpe** [comment]
I purchased qdomyos in the app store and that binary is m1-compatible apparently. It's running on my mac and connected to my teadmill, but I have no idea how to get it to connect to zwift running on the same device.

**Comment by cagnulein** [comment]
Yes you did right. Do you see the tiles in qz now? If so simply open zwift on the mac and you will see a wahoo kickr virtual device from qz 
Let  me know

**Comment by droctothorpe** [comment]
Thanks for getting back to me so quickly, @cagnulein! I saw the tiles, I confirmed that they update when I adjust the speed on my treadmill, but I never saw the virtual device in Zwift, regardless of if I tried to connect by bluetooth or by phone. Do I have to change any of the settings? I'm in zwift run as opposed to bike if that makes a difference.

**Comment by cagnulein** [comment]
of course zwift and qz are running on the same mac, right?
did you change any setting on qz? you shouldn't, the default are right for this. be sure for example that in the experimental settings the dircon is enabled. it must be for this
on zwift you don't have to use bluetooth or phone, it will just appear a wahoo kickr device there with the symbol of the ethernet

**Comment by droctothorpe** [comment]
I'm not sure what you mean by dircon (are you referring to `Wahoo direct connect`? If so, that's enabled). Here's what my experimental settings look like:
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/096debf7-6f8c-491f-820d-73411b0e91ef">
Here's a screenshot where you can see that qzdomyos has successfully connected to my norditrack treadmill:
<img width="1169" alt="image" src="https://github.com/user-attachments/assets/3929a949-217f-48b1-a1a5-a1a30fd2c6de">
Now that all of that is confirmed, I launch zwift. Here's what I see in the Paired Devices screen:
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/0f84029c-d3db-40e1-b6ea-a9427e23c285">
When I click `Run Speed`, nothing shows up:
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/6221a1eb-448e-4bdd-bd2b-182230869be3">
If I click `Pair with phone`, nothing shows up.

**Comment by cagnulein** [comment]
ok everything is right. does MacOS asks about permissions for both qz app and zwift? they must have permissions to look on your network to work. I have the same setup and it's working fine to me
You don't have to click "pair with phone"
also it could take 10-20 seconds to appear on the zwift screen the first time

**Comment by cagnulein** [comment]
hah also zwift must running on window mode, not full screen

**Comment by droctothorpe** [comment]
Zwift is in windowed mode. I definitely gave qz network permission:
<img width="477" alt="image" src="https://github.com/user-attachments/assets/c92ab676-45bb-4336-a95a-43ced00da7eb">
Zwift never asked.

**Comment by cagnulein** [comment]
the problem is that, zwift must ask it 
<img width="470" alt="Screenshot 2024-11-28 at 16 49 45" src="https://github.com/user-attachments/assets/77299437-8138-4fbd-bc0a-3c3abda275f9">
maybe you can try to reinstall it

**Comment by droctothorpe** [comment]
I'll give that a shot and report back. Thank you so much!

**Comment by droctothorpe** [comment]
Confirming that it worked! Thank you so much for your help!

**Comment by cagnulein** [comment]
Amazing! Please remember to rate the app and the support on the store, it means a lot to me!

Also if you can join https://www.patreon.com/cagnulein it will be highly appreciated!
