### ISSUE TITLE
[BUG] Virtual activity tag in Strava not applicable when sport type is set to walking

### ISSUE THREAD

**Issue by feymark** [cagnulein/qdomyos-zwift#2844]
In Strava, there is no option for "virtual walking," meaning the Virtual Activity tag is not applicable when the sport type is set to "walking." Therefore, if the Virtual Activity tag is selected, the sport type should never be set to "walking".

**Comment by feymark** [comment]
When I examin the fit file now it is still set at walking but now the subsport is set to treadmill instead of virtual activity. I think the correct would be running and virtual activity when checked.Andreas Feymark30 nov. 2024 kl. 14:13 skrev Roberto Viola ***@***.***>:﻿
Closed #2844 as completed.

**Comment by cagnulein** [comment]
> When I examin the fit file now it is still set at walking but now the subsport is set to treadmill instead of virtual activity

yes it's what i did



> I think the correct would be running and virtual activity when checked

i guess both are ok, what's the differences between the 2 options?

**Comment by feymark** [comment]
﻿There is a difference in how Strava handles the data and sadly you can not change it manually afterwards. For example, virtual activity will show you a map and elevation when applicable, the combination walk and treadmill will not. It is possible to remove the treadmill label manually to get map and elevation but then the activity will not be separated from your regular walks.Andreas Feymark30 nov. 2024 kl. 15:28 skrev Roberto Viola ***@***.***>:﻿
Reopened #2844.

**Comment by cagnulein** [comment]
Ok, thanks for the clarification.
I will do this so

Il giorno sab 30 nov 2024 alle 16:26 feymark ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done now, i'm sending the new one

**Comment by cagnulein** [comment]
@feymark Are we OK with this?

**Comment by feymark** [comment]
Yes!28 dec. 2024 kl. 07:21 skrev Roberto Viola ***@***.***>:﻿
@feymark Are we OK with this?
