### ISSUE TITLE
[BUG] can't connect NordicTrack 2450 to ZQ Fitness

### ISSUE THREAD

**Issue by Al-Dl** [cagnulein/qdomyos-zwift#2849]
Can't connect NordicTrack 2450 treadmill (2019 year) to QZ Fitness on the phone. 
Can see only tiles with 0

1. Start treadmill 
2. Start manual workout 
3. Start QZ Fitness 
4. QZ Fitness does not recieve data from treadmill (can't find and connect to treadmill) 

**Screenshots**
![20241130_233848](https://github.com/user-attachments/assets/f5f70842-17f0-4741-9903-c2ec74d95d7b)

![Screenshot_20241201_003950](https://github.com/user-attachments/assets/4d9474fa-ae91-424d-97c8-0b37b4a77baa)

**Smartphone (please complete the following information):**
 - Device: Samsung s10e
 - OS: Android
 - Version 12

**Append a debug log**
Debug files from Android phone 

debug-Sat_Nov_30_23_49_47_2024.log](https://github.com/user-attachments/files/17965903/debug-Sat_Nov_30_23_49_47_2024.log)
[debug-Sat_Nov_30_23_47_40_2024.log](https://github.com/user-attachments/files/17965904/debug-Sat_Nov_30_23_47_40_2024.log)
[debug-Sat_Nov_30_23_43_32_2024.log](https://github.com/user-attachments/files/17965905/debug-Sat_Nov_30_23_43_32_2024.log)
[debug-Sat_Nov_30_23_55_19_2024.log](https://github.com/user-attachments/files/17965906/debug-Sat_Nov_30_23_55_19_2024.log)

Debug files from treadmill NordicTrack 2450 :
[2024-11-29_logs.txt](https://github.com/user-attachments/files/17965918/2024-11-29_logs.txt)
[2024-11-30_logs.txt](https://github.com/user-attachments/files/17965919/2024-11-30_logs.txt)

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 nov 2024 alle 16:41 Al-Dl ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
hi @Al-Dl the problem is that i can't see at all the messages from the companion. can you try to set the device to "other" in the companion and reboot it? maybe also your wifi router is filtering broadcast messages?
let me know

**Comment by cagnulein** [comment]
@Al-Dl Any news?
