### ISSUE TITLE
[REQ] Support for DKN AM-3i

### ISSUE THREAD

**Issue by rvanrooy** [cagnulein/qdomyos-zwift#285]
**Is your feature request related to a problem? Please describe.**
Feature request for support for DKN AM-3i bike

Bike Name: DKN AM-3i
Bluetooth Device name: DKN MOTION0180

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6357315/btsnoop_hci.log)

[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/6357322/btsnoop_hci.zip)

I used the Vescape app to connect to the bike, and set the target resistance in the app. The app altered the resistance to keep the Watt consistent with the change in speed while cycling.

**Comment by cagnulein** [comment]
Great i will add it as soon as possible

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 apr 2021 alle ore 12:01 Reinhardt van Rooyen <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
do you have also the ability to change the resistance manually from the app? if so, could you collect another log changing the restisance every 5 seconds to the max and the to the minimum? so i will see the packet for sure. thanks!

anyway i guess your bike it's a similar iconsole bike, so the protocol should be almost written! :)

**Comment by cagnulein** [comment]
nevermind, the resistance packet is the same, so i don't need it.

**Comment by cagnulein** [comment]
done, it will be in the next beta. are you on android @rvanrooy  ? if yes, send me an email to roberto.viola83@gmail.com and i will add you to the beta tester.

**Comment by rvanrooy** [comment]
Mail sent.  Thanks!

**Comment by cagnulein** [comment]
#294
