### ISSUE TITLE
Virtual device not detected in zwift

### ISSUE THREAD

**Issue by Kisswejcer** [cagnulein/qdomyos-zwift#2855]
Mac and ipad can’t see and connect to virtual device.

[debug-Sun_Dec_1_15_07_04_2024.log](https://github.com/user-attachments/files/17969395/debug-Sun_Dec_1_15_07_04_2024.log)

**Comment by cagnulein** [comment]
Thanks, I'm out with my family, I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 16:22 Kisswejcer ***@***.***>
ha scritto:

**Comment by Kisswejcer** [comment]
👍👍


On Sunday, December 1, 2024, 3:39 PM, Roberto Viola ***@***.***> wrote:



Thanks, I'm out with my family, I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 16:22 Kisswejcer ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Kisswejcer Under experimental settings the ios peloton workaround MUST be enabled. Let me know

**Comment by Kisswejcer** [comment]
Magic!Many thanks!!When i am pairing to zwift It appears as Tamas’s iphone instead of virtual trainer.
Is that ok?


Sent from Yahoo Mail for iPhone


On Sunday, December 1, 2024, 5:41 PM, Roberto Viola ***@***.***> wrote:




@Kisswejcer Under experimental settings the ios peloton workaround MUST be enabled. Let me know

**Comment by cagnulein** [comment]
Yes that is perfect!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 19:35 Kisswejcer ***@***.***>
ha scritto:

> Magic!Many thanks!!When i am pairing to zwift It appears as Tamas’s iphone
> instead of virtual trainer.
> Is that ok?
>
>
> Sent from Yahoo Mail for iPhone
>
>
