### ISSUE TITLE
[BUG] QZ with Rouvy ignores Rouvy resistance.

### ISSUE THREAD

**Issue by Stand77** [cagnulein/qdomyos-zwift#2856]
**Describe the bug**
When riding a route on Rouvy the resistance on my Wahoo Kicker Core does not change when the incline changes. It remains at around ~52-58. This is the same resistance if I just ride QZ as a stand alone ap on my phone. In Rouvy while riding, the speed is altered according to the inclination; i.e., speed increases on negative inclinations and slows on positive inclinations.
QZ acts as if it's in ERG mode of some sort. 
All the other tiles reflect the same values as Rouvy in terms of inclination, watts, MPH. The peleton tile for resistance is the same as the resistance tile, ~52-58.
I can make the resistance go up some by increasing my force/power on the peddles. 

**To Reproduce**
I see this on any ride; power up the Wahoo Kicker Core, start the QZ app on my phone named "JUSTO", Start Rouvy, select a route, wait for the sensors to connect to "JUSTO", start riding. 

**Expected behavior**
When encountering changes in the terrain (inclination) I expect the ride to become harder, the resistance on the Wahoo Kicker should increase in proportion to the incline. At +7% it should be very hard and require selecting a lower gear on my bike.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Device name	HP-Omen
Processor	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz   4.20 GHz
Installed RAM	16.0 GB
Device ID	D260C11C-862F-4F9D-9697-5EFA56D9B667
Product ID	00325-96084-33096-AAOEM
System type	64-bit operating system, x64-based processor

**Smartphone (please complete the following information):**
Samsung Galaxy A13 5G
 - Version 13
**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Sun_Dec_1_10_30_16_2024[1].log](https://github.com/user-attachments/files/17970101/debug-Sun_Dec_1_10_30_16_2024.1.log)

**Comment by Stand77** [comment]
Here are all the files from riding today.
[debug-Sun_Dec_1_11_38_39_2024[1].log](https://github.com/user-attachments/files/17970184/debug-Sun_Dec_1_11_38_39_2024.1.log)
[debug-Sun_Dec_1_11_36_31_2024[1].log](https://github.com/user-attachments/files/17970187/debug-Sun_Dec_1_11_36_31_2024.1.log)
[debug-Sun_Dec_1_10_30_16_2024[1].log](https://github.com/user-attachments/files/17970195/debug-Sun_Dec_1_10_30_16_2024.1.log)

**Comment by cagnulein** [comment]
Hi, disable the ftms Bike setting and press ok in the bike options in qz
and restart qz
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 1 dic 2024 alle 21:06 Stand77 ***@***.***> ha
scritto:

**Comment by Stand77** [comment]
I disabled ftms and that made the resistance follow the incline, but it also took away + or - gears. So I put it back to Kicker Core. Now the peddle resistance seems to follow the Rouvy route enough to where I have to go down in gears (-) to climb.
Maybe that's the way it's supposed to e working?

**Comment by cagnulein** [comment]
It shouldn't, also if it didn't work before, why now with the same settings is working?
Anyway do some workouts and report back
Thanks

**Comment by Stand77** [comment]
"why now with the same settings is working?" Changing 'FTMS Bike:' from KICKER CORE 4F79 to Disabled changes the behavior of the Gears function. With 'Kicker Core' selected the gears will go negative to -15 and lower. With 'Disabled' the gears will go positive, but will not go below +1.

**Comment by cagnulein** [comment]
> Changing 'FTMS Bike:' from KICKER CORE 4F79 to Disabled changes the behavior of the Gears function. With 'Kicker Core' selected the gears will go negative to -15 and lower. With 'Disabled' the gears will go positive, but will not go below +1.

yes it's indeed the right behaviour. Maybe I didn't get it that you changed this in your last test. Anyway now are you ok with the setup?

**Comment by Stand77** [comment]
Almost, when does the + - function work in the Resistance tile? Does it not work with the Kicker Core? When FTMS Bike: is set to my KICKER CORE 4F79 why doesn't the Resistance come from Rouvy and the inclination changes?

**Comment by cagnulein** [comment]
Ignore the resistance tile for your trainer. You can disable it in the tiles settings 

Ftms doesn't work because your trainer use the wahoo profile. But there is not difference between them, so if with disable it works fine, keep it disabled

Let me know if you have any other questions

**Comment by Stand77** [comment]
OK thanks for your time.

**Comment by cagnulein** [comment]
@Stand77 But are you satisfied with the result or do you have any issues?

**Comment by Stand77** [comment]
Yes, I will be using QZ to ride on Rouvy. Thanks for your attention and support! No more issues.
