### ISSUE TITLE
[BUG] Cannot establish ADB connection on reset S22i NTEX02117NB.5

### ISSUE THREAD

**Issue by eh11111** [cagnulein/qdomyos-zwift#2857]
**Describe the bug**
Cannot establish ADB connection on reset S22i NTEX02117NB.5

**To Reproduce**
1. Factory reset S22i
2. Enabled privilege mode
3. Enabled developer options
4. Enabled USB debugging
5. Mac Terminal ran ./QZ-Companion-MacOS
6. Entered correct IP address and Ping successful
8. See error: "Connecting to treadmill via ADB ...
Cannot establish ADB connection."

**Expected behavior**
Expect successful ADB connection

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 15.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 16
 - OS: iOS 
 - Version 18.1.1

**Append a debug log**

Log generated at Sun Dec  1 12:00:27 PST 2024 for IP 192.168.4.249

Pinging 192.168.4.249 ...
PING 192.168.4.249 (192.168.4.249): 56 data bytes
64 bytes from 192.168.4.249: icmp_seq=0 ttl=64 time=265.412 ms

--- 192.168.4.249 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 265.412/265.412/265.412/nan ms

Connecting to treadmill via ADB ...

disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to connect to '192.168.4.249:5555': Connection refused
  
**Additional context**

**Comment by cagnulein** [comment]
Did you try after a factory reset, to don't update ifit?

**Comment by eh11111** [comment]
Yes, I factory reset and did not update iFit.

    On Sunday, December 1, 2024 at 09:27:53 PM PST, Roberto Viola ***@***.***> wrote:  
 
 


Did you try after a factory reset, to don't update ifit?

**Comment by cagnulein** [comment]
You can try to install the companion using the web browser there without adb

**Comment by cagnulein** [comment]
@eh11111 Any news?

**Comment by eh11111** [comment]
I gave up

**Comment by cagnulein** [comment]
ok let me know if you want to try again, s22i it's supported
