### ISSUE TITLE
[BUG] Sportstech SX200 / JLL_IC400 watt -25 and kcal high

### ISSUE THREAD

**Issue by fab0nymous** [cagnulein/qdomyos-zwift#286]
Hi,

me again with the SX200 ;)

when pedaling without touching the HR sensors, the wattage always display -25, not 0. Once using the HR sensor on the bike, the wattage seems ok calculated, but as it has prior been "-25", the average is pulled down.. (I mean it is also going low when letting off the sensors, but thats a different topic, i need an external hr sensor)

Other topic, but not important, is that kcal skyrockets once just starts to pedal just bit. 6.636 kcal in 1:38 min with around 50 rpm. Yay :)

Connection to Zwift is not working as expected. Zwift shows 255 watt when app shows -25, but Zwift does not show correct watt once touching the HR sensor. Zwift displays 0 while app e.g. shows 80. RPM cannot be connected at all, tried different settings in app :/

I am unable to provide a debug log as no debug log is generated anymore with the 2.6.11 android version. tried to reinstall and give permission again as well. Has the directory changed?

**Expected behavior**
Calculate with 0 watt once HR is not touched instead of -25.

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: Android 10, EMUI 11.0.0
 - Version 2.6.11

**Comment by cagnulein** [comment]
Yes directory now is under /Android path

Il gio 22 apr 2021, 12:37 fab0nymous ***@***.***> ha scritto:

**Comment by fab0nymous** [comment]
Ah ok. got it.
[debug-Thu_Apr_22_12_42_25_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6358431/debug-Thu_Apr_22_12_42_25_2021.log)

**Comment by cagnulein** [comment]
ok it's all clear now. i have to put a limit to wattage if you don't have the hr connected. i'm doing it right now. it will be avaible in the next beta ;)
