### ISSUE TITLE
[BUG] Not connecting to bike

### ISSUE THREAD

**Issue by Wednesday80** [cagnulein/qdomyos-zwift#2862]
**Describe the bug**

app was deleted and reinstalled and since then is not working.
App shows bike is connected, but when you start no data appears when pedalling. Start button on display starts and then changes to red after 5-10 seconds.still shows connected but nothing happens 
[debug-Tue_Dec_3_11_08_56_2024.log](https://github.com/user-attachments/files/17992001/debug-Tue_Dec_3_11_08_56_2024.log)
[debug-Tue_Dec_3_11_08_56_2024.log](https://github.com/user-attachments/files/17992006/debug-Tue_Dec_3_11_08_56_2024.log)

was working fine prior the app being reinstalled 

bike is DKN Am3i

**To Reproduce**

**Expected behavior**

**Screenshots**

Smartphone (please complete the following information):**
 - Device: iPad 
 - OS: [e.g. iOS8.1.1
 - Version IPad Air 4th gen

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Wednesday80 Are we OK with this?
