### ISSUE TITLE
[BUG] Bowflex T9 Not Starting When Connected

### ISSUE THREAD

**Issue by PollardPhotography** [cagnulein/qdomyos-zwift#2866]
**Describe the bug**
After successful connection of Bowflex T9 Treadmill and Qz app on iPhone, the T9 Treadmill will not start via the Qz app and goes back a blinking red start button after several seconds. If starting the treadmill manually from the physical treadmill start button, the Qz app does not recognize that it has started despite being connected via FTMS.

**To Reproduce**
1. Turn on treadmill
2. Start Qz app
3. Complete wizard and select Bowflex T9 Treadmill
4. Confirm connection is visible in Qz app and the FTMS light is illuminated on the T9, indicating successful connection
5. Attempt to start treadmill via Qz app, resulting in treadmill not starting
6. After a few seconds, Qz app goes back to flashing red start button

**Expected behavior**
I believe that pressing the start button should prompt the treadmill to begin operating.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  iOS
 - Version 18.1.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 18.1.1 (22B91) 
 - Version iOS 18.1.1 (22B91)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
n/a
![IMG_8078](https://github.com/user-attachments/assets/8a77cb27-9502-4af2-9206-2f42a828b40d)
![IMG_8077](https://github.com/user-attachments/assets/3f68b0cf-8814-42bf-a310-c340e38bae2f)
![IMG_8075](https://github.com/user-attachments/assets/0d4a04c4-bcd4-4203-9607-71e226948278)
![IMG_8074](https://github.com/user-attachments/assets/c2adf803-066f-4fa3-9527-c0c142c1fb0f)
![IMG_8073](https://github.com/user-attachments/assets/553f03e4-1fa6-4664-af9a-0ad0c914cac0)
[debug-Tue_Dec_3_09_02_33_2024.log](https://github.com/user-attachments/files/17995916/debug-Tue_Dec_3_09_02_33_2024.log)

**Comment by cagnulein** [comment]
got the issue: set the ftms horizon setting under settings, treadmill options, horizon and restart qz
Let me know!

**Comment by PollardPhotography** [comment]
> got the issue: set the ftms horizon setting under settings, treadmill options, horizon and restart qz Let me know!

Hi Roberto,

That seems to have enabled me to start the treadmill via Qz after selecting the user, weight, speed, and incline on the T9 so the treadmill displays "Press Start".

However, once starting I've found that if I press the "-" symbol in Qz to reduce treadmill speed, it quickly ramps up to full speed.

I've attached images, video, and debug code to this response. Please let me know if this needs to be opened as a separate issue.

Thank you for your help.

[debug-Tue_Dec_3_09_38_10_2024.log](https://github.com/user-attachments/files/17996311/debug-Tue_Dec_3_09_38_10_2024.log)

https://github.com/user-attachments/assets/e1fe3de1-36c1-46c3-a121-d0cdda4897af

![IMG_8081](https://github.com/user-attachments/assets/b26644f9-a2c9-44e7-ae27-090dd0876464)

**Comment by cagnulein** [comment]
yes i'm seeing this too, anyway if you do a single press is working right? i'm trying to fix it asap

**Comment by cagnulein** [comment]
fixed! i'm sending you the fix

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 dic 2024 alle ore 17:50 PollardPhotography <
***@***.***> ha scritto:

**Comment by PollardPhotography** [comment]
Hi,

I downloaded the test app and received the same result. Pressing the “-“ symbol on the app causes the treadmill to increase speed. 

I found that pressing it once causes it to increase speed by two levels (3 -> 5) pressing it again causes it to increase by 3 (5 -> 8) and pressing it once more causes it to jump 4 (8 -> 12). 

Please let me know if there’s any other information I can provide.

I have attached the relevant debug log.

[debug-Tue_Dec_3_10_27_00_2024.log](https://github.com/user-attachments/files/17996910/debug-Tue_Dec_3_10_27_00_2024.log)

Thank you for your help

**Comment by cagnulein** [comment]
it's something specific of this treadmill, maybe it's expecting speed in miles instead of km/h. is it in miles? if so they are out of standard and that's why you are seeing this strange behaviour

in case i can fix it
let me know

**Comment by cagnulein** [comment]
let's try a thing: are you able to set the treadmill in km/h?
if so give it a try, rebooting the treadmill

if it doesn't change anything, i will create a workaround for this tomorrow

let me know

**Comment by PollardPhotography** [comment]
The owner's manual does not provide a way to change from MPH to km/h. I have reached out to Bowflex and they are having an engineer confirm how it can be changed, but it may take 24-48 hours. I will follow up with you here when I have an answer.
 
 Thank you for your help

**Comment by cagnulein** [comment]
I was checking once again the Bluetooth ftms specs and they clearly talk about km/h as a standard 

![image](https://github.com/user-attachments/assets/b3896a9c-6f8f-494d-949d-d3bb44e31c05)

But no problem I can do a workaround for you tomorrow

**Comment by PollardPhotography** [comment]
Hi Roberto,

I got a response back from Bowflex and I successfully changed the console to KM/h measurements.

However, after connecting to Qz I found that pressing the "-" button for speed in the app still causes the speed to rapidly increase on the treadmill.

I've attached the latest debug log. 

Please let me know if there is any other information I can provide.

Thank you for your help
[debug-Tue_Dec_3_14_45_36_2024.log](https://github.com/user-attachments/files/17999531/debug-Tue_Dec_3_14_45_36_2024.log)

**Comment by cagnulein** [comment]
I guess they changed only the visualization but not the underlying
communication
Ok I will try to make a patch for you later today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 dic 2024 alle 22:52 PollardPhotography <
***@***.***> ha scritto:

**Comment by PollardPhotography** [comment]
Hi Roberto,

Thanks for the update. I tested the latest version and I am now able to press the "-" in Qz to reduce speed.

However, increasing speed with "+" in Qz exhibits some unusual behavior with the speed jumping in value while increasing. 

Ex: 1.4 -> 1.8 -> 2.0 -> 1.8 -> 2.0 -> 2.4, etc

I've attached the debug log for your reference.

A few other things of note:

- Speed in Qz is mismatched from the speed on the treadmill. When the treadmill displays a speed of 3.0 KM/h, Qz displays 4.8 KM/h, resulting in incorrect pace and distance being recorded.

- Fan control in Qz does not seem to activate the fans on the treadmill

- I connected to Strava and a workout automatically and successfully pushed to Strava, but it did _not_ include my elevation. GitHub will not allow me to post the FIT file, but I will link the Strava workout below. I do see the elevation in the FIT file using https://www.fitfileviewer.com/
I'll include a screenshot of the elevation being recorded in the workout in Qz. 
Link to workout on Strava: https://www.strava.com/activities/13048941143

- Last issue is that I noticed my heart rate reading erratically, with a max BPM of 249. Unsure why, but this was using the app on my Apple Watch Ultra 2.

If you'd like for me to email you the FIT file or send it in some other way please let me know. For me, the biggest concern is the elevation not feeding to Strava, as that was my primary reason for buying the app.

Thank you for your help!

[debug-Wed_Dec_4_16_41_29_2024.log](https://github.com/user-attachments/files/18015506/debug-Wed_Dec_4_16_41_29_2024.log)

![IMG_8119](https://github.com/user-attachments/assets/090d155f-4b49-4cec-b6b8-93f661cfb22a)
![IMG_8120](https://github.com/user-attachments/assets/edf68f80-a541-4074-896a-d7617b0ebc1e)

**Comment by cagnulein** [comment]
> * Speed in Qz is mismatched from the speed on the treadmill. When the treadmill displays a speed of 3.0 KM/h, Qz displays 4.8 KM/h, resulting in incorrect pace and distance being recorded.
> *

ok this means that also sends the speed in miles. The treadmill firmware is absolute a s**t! :D ok i will do also this
it also explain the issue that you have with the control of the speed +




> * Fan control in Qz does not seem to activate the fans on the treadmill

yes the treadmill doesn't expose this



> * I connected to Strava and a workout automatically and successfully pushed to Strava, but it did _not_ include my elevation. GitHub will not allow me to post the FIT file, but I will link the Strava workout below. I do see the elevation in the FIT file using https://www.fitfileviewer.com/
>   I'll include a screenshot of the elevation being recorded in the workout in Qz.
>   Link to workout on Strava: https://www.strava.com/activities/13048941143

![image](https://github.com/user-attachments/assets/a8fa7ad4-aa6b-435b-8a7c-80f702132379)

i do see the elevation on your strava activity!



> * Last issue is that I noticed my heart rate reading erratically, with a max BPM of 249. Unsure why, but this was using the app on my Apple Watch Ultra 2.

i don't see this on the log. do you see the issue on the watch directly too? do you have a log for this?

**Comment by cagnulein** [comment]
i sent the new version for the right speed

**Comment by cagnulein** [comment]
@PollardPhotography any news?
