### ISSUE TITLE
[BUG] at *exactly* 12 km/h -> 0 reported in Zwift

### ISSUE THREAD

**Issue by erugeri** [cagnulein/qdomyos-zwift#2867]
**Describe the bug**
I own a Domyos Intense Run TC 1545 and something very strange happen.
Everything works perfectly using your app and Zwift but when I run at exactly 12 km/h (5:30 pace), Zwift reports 0 km/h and considers that I stop. If I change to 11.9km/h or 12.1 km/h it works again.

**To Reproduce**
1. Run on Zwift with QZ in background
2. set 11.9
3. set 12.0
4. set 12.1

**Expected behavior**
value repôrted correctly all the time

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A9+
 - OS: Android 14
 - Version QZ 2.16.66

**Append a debug log**

[debug-Tue_Dec_3_17_18_54_2024.log](https://github.com/user-attachments/files/17995972/debug-Tue_Dec_3_17_18_54_2024.log)

Thnaks!

**Comment by cagnulein** [comment]
i checked the log on qz is doing the right thing. i tried also myself and it's working ok

<img width="1315" alt="Screenshot 2024-12-03 at 17 39 30" src="https://github.com/user-attachments/assets/0b8f6572-03ea-41c2-87f4-23fc843974ad">

can you try the same?

**Comment by erugeri** [comment]
Weird that they would have such an obvious bug. I think it must be at least
a bit linked to the specificity of QZ...
Is it normal that I see my domyos treadmill in zwift as a "wahoo tread". As
I also own a wahoo kickr bike I'm surprised.
Anyway, thanks for your quick support! I'll run 0.1 km/h faster to try to
avoid it 😀

Le mar. 3 déc. 2024, 18:24, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
You can try to see if you pair it with the Bluetooth name it does the same

Trust me, qz is doing right, the proof is the fact that you see it
correctly on the pairing screen  :)

Wahoo virtual device is the wifi bridge from qz

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 dic 2024 alle 18:54 Etienne Rugeri ***@***.***>
ha scritto:

**Comment by erugeri** [comment]
Hi,

I tried with :
 - WAHOO TREAD RJ45 logo -> problem @ 12km/h -> 0
 - WAHOO KICKR RJ45 logo -> perfect @ 12
 - My phone (S24) bluetooth logo -> perfect @ 12

That's weird, I thought "WAHOO KICKR" was my Wahoo Kickr Bike being on so I
didn't use it but it looks like QZ generates it. I don't really understand
why there is 3 different devices detected for QZ but anyway it works. I
think I'll use WAHOO KICKR as if I'm not wrong the connection using ANT+ is
better than bluetooth.

Best,

Etienne

Etienne

**Comment by cagnulein** [comment]
these 3 devices are from qz. the rj45 logo means that it's using dircon over wifi that it's better than bluetooth of course. so use that device, probably zwift didn't handle correctly the dircon with the TREAD name for some reason :)
