### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TK-tech353** [cagnulein/qdomyos-zwift#2871]
**Describe the bug**
The connection is not stable, the speed is not realistic and not constant. Connection with zwift did not work, zwift found another smarttrainer (kickr), which I dont have. 

I hope this helps, this is completely new to me. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Honor COL-L29
 - OS: 10.0.0.
[debug-Tue_Dec_3_21_17_12_2024.log](https://github.com/user-attachments/files/17999301/debug-Tue_Dec_3_21_17_12_2024.log)
189
 - Version 10

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
https://play.google.com/store/apps/details?id=com.cxinventor.file.explorer&hl=it&gl=US

**Comment by cagnulein** [comment]
A lot of issues :) 

Let's start from the basic: 
1. Where do you lost connection? From qz to the trainer or zwift to qz?
2. The wahoo kickr virtual bike on zwift is how qz is showing to zwift. It's normal. Did you select this?
3. For the speed read https://robertoviola.cloud/2024/01/27/dispelling-the-myth-speed-variations-between-qz-and-zwift-are-not-a-device-issue/amp/

Let me know

**Comment by cagnulein** [comment]
@TK-tech353 Any news?
