### ISSUE TITLE
Nordictrack c1750 (2018) no metrics to iphone

### ISSUE THREAD

**Issue by thomastt2020** [cagnulein/qdomyos-zwift#2876]
**Describe the bug**
Don’t see metrics on my QZ app on my iPhone 12 mini. Qz companion app installed on nordictrack c1750 treadmill from 2018. Part number 388129 version 78.238

App version 2.2.4.167 firmware 5.1.1.eng.xmlnb.20161111.095021 

**To Reproduce**
1. added IP address to qz phone app
2. I see tiles but all 0s and doesn’t update 

**Expected behavior**
See speed when moving on treadmill 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: 18.1.1
 - Version: 2.17.0

**Append a debug log**
I don’t see a debug just .fit

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @thomastt2020 I don't see the log
Please upload it

**Comment by thomastt2020** [comment]
My mistake, i didn't select C1750 from the companion app. the app wasn't opening when i pressed it so just went to next step. then realized to use the app switcher to open the companion app on the treadmill tablet. Thank you for everything. I will happily patron this goodness work

**Comment by cagnulein** [comment]
Amazing! Thank you!
