### ISSUE TITLE
[REQ] Automatically reduce / increase treadmill speed when incline increases / decreases

### ISSUE THREAD

**Issue by microadam** [cagnulein/qdomyos-zwift#2881]
**Is your feature request related to a problem? Please describe.**
Related to this reddit post https://www.reddit.com/r/qdomyos_zwift/comments/1h6pj4x/automatically_reduce_treadmill_speed_when_incline/?share_id=ODoJBhBbmMxVaWJtnCKSD&utm_content=2&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1

**Describe the solution you'd like**
The ability for the app to automatically increase / decrease (by a percentage) the speed of the treadmill, when Zwift automatically increases / decreases the incline.

For example if treadmill is currently at 10km/h and an incline of 1.0, if, from Zwift, it automatically gets increased to an incline of 5.0, the speed would automatically be reduced to say 9km/h and then if it goes back to an incline of 1.0, the speed would be increased back to 10km/h

Thank you!

**Comment by cagnulein** [comment]
hi @microadam i suggest to try first the PID heart funcionality. it does exactly this. so for example you can specify a heart min-max bpm or a heart zone (that you can change in the tile in the main dashboard) and qz will keep you in that range and when the inclination changes, qz will also changes the speed to remodulate the PID.

me and @Middy2000 are the main users of this feature! let me know!

**Comment by microadam** [comment]
> hi @microadam i suggest to try first the PID heart funcionality. it does exactly this. so for example you can specify a heart min-max bpm or a heart zone (that you can change in the tile in the main dashboard) and qz will keep you in that range and when the inclination changes, qz will also changes the speed to remodulate the PID.
> 
> me and @Middy2000 are the main users of this feature! let me know!

ooo! interesting. Thank you! I haven't got any sort of HR monitoring setup yet, but will try this!

**Comment by cagnulein** [comment]
let me know if you need help for setupping this! it will change the way you are training for sure!
also you can customize them with the xml training program from qz! @lorenzogavanna is one of the most users of this :)

**Comment by Middy2000** [comment]
You wouldn't want to reduce the pace based only on % of incline.  The hill may only be very short so you could hold pace for this short period of time. 

It is much better to allow the pace to be controlled by your HR.  The feature works very well.   Especially on long climbs.

**Comment by microadam** [comment]
Sounds sensible! Could you perhaps point me in the right directions of the exact settings I need to set for this? I see there is a whole bunch of different options! Any suggestions on how you have this setup yourselves would be really interesting!

**Comment by Middy2000** [comment]
@cagnulein Do you a guide for this or shall I do one like i did for auto incline?

**Comment by cagnulein** [comment]
Hi @Middy2000 if you can put down 2 lines for @microadam it will be amazing and I can add also to wiki

Thanks!

**Comment by lorenzogavanna** [comment]
Yes I really like the xml potential!! Let me know if you need any advice on
creating them!


---
Lorenzo Gavanna
www.lorenzogavanna.com
***@***.***
+39 347 6788352


Il giorno gio 5 dic 2024 alle ore 15:14 Roberto Viola <
***@***.***> ha scritto:

**Comment by lorenzogavanna** [comment]
@microadam If you want here you can find a set of 7 workouts based on hr. Here a visual breakdown of the workouts. They are all 36 to 40 minutes.
![image](https://github.com/user-attachments/assets/22fdb577-ece0-4c15-9b86-b60ca2cd148a)
[Interval HR.zip](https://github.com/user-attachments/files/18031392/Interval.HR.zip)

**Comment by microadam** [comment]
Thanks! I think this is way more advanced than I was after though! 😅 I was more curious how I enable this "PID" setting in QZ and where the settings are to configure the heart rate zones (there is a bunch of stuff, but not quite sure I know which ones I should be using, or recommended settings). I don't think I am quite at different training workouts yet! Appreciate the effort though :D

**Comment by cagnulein** [comment]
The HR zones are configurable in the heart rate options in qz
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 dic 2024 alle 10:14 Adam Duncan ***@***.***>
ha scritto:
