### ISSUE TITLE
[BUG] Connection Issue

### ISSUE THREAD

**Issue by TayJ26** [cagnulein/qdomyos-zwift#2890]
**Describe the bug**
Since downloading TestFlight to run version 2.18.1 I have not been able to connect to Zwift power, resistance etc. I’m running QZ on my iPhone and Zwift through my iPad. I’m wanting to see if I’ve got a bug or my settings are wrong as nothing else has changed besides trying the new version and I’m unable to ride when QZ won’t connect to Zwift. 

**To Reproduce**

**Expected behavior**
I should be able to find my iPhone name on the Zwift app to connect Power, Resistence etc. Not even the Wahoo option is showing up anymore. 

**Screenshots**

![image](https://github.com/user-attachments/assets/000032fa-a752-454d-af3e-0853adfbfd69)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18.1.1
 - Version 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-
[debug-Mon_Dec_9_13_49_11_2024.log](https://github.com/user-attachments/files/18056439/debug-Mon_Dec_9_13_49_11_2024.log)
![IMG_8420](https://github.com/user-attachments/assets/097055ae-1446-478e-a2f3-f5db4526dc84)
![IMG_8420](https://github.com/user-attachments/assets/d242435c-cdfd-44f8-926a-59459ef3bfdb)
zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Mon_Dec_9_13_49_11_2024.log](https://github.com/user-attachments/files/18056384/debug-Mon_Dec_9_13_49_11_2024.log)

**Comment by cagnulein** [comment]
The main issue is that you disabled the virtual device in the experimental
settings. It MUST be enabled. Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 9 dic 2024 alle 05:48 TayJ26 ***@***.***> ha
scritto:

**Comment by TayJ26** [comment]
![IMG_8438](https://github.com/user-attachments/assets/5c129c20-45ea-47a3-ad05-5a042739a1e4)

Thank you, I did that. Just wondering if there should be a different option for Resistance so that I can enter into events because it used to say Wahoo I believe? Or has it changed to only need to be run through my phone?

Thank you

**Comment by cagnulein** [comment]
Wahoo kickr virtual device is always the best options if you want to race

**Comment by TayJ26** [comment]
[debug-Fri_Dec_13_07_28_33_2024.log](https://github.com/user-attachments/files/18117724/debug-Fri_Dec_13_07_28_33_2024.log)

**Comment by TayJ26** [comment]
Yes I understand that but every time I’m logging in now it’s only giving me the option of my phone name not wahoo virtual. Had been working seamlessly for most of the year. Will attach a debug log if that helps you identify what’s going wrong?

**Comment by cagnulein** [comment]
In this log you are not connected to the bike but the settings are right. So qz is doing everything correctly. Did you change something on your network?
Did you try to reinstall zwift?

**Comment by eskimos20** [comment]
Same thing for me. Wahoo device is only showing sometimes. Tried it on Samsund S22 and Samsung A8 Tablet. It either shows the regular device name or sometimes shows Wahoo kickr 00 something. But its very rare that the wahoo kickr option is there.

**Comment by cagnulein** [comment]
@eskimos20 it's a network issue more then a QZ issue. Use the hotspot from your phone on both qz and zwift and be sure to disable the VPN just to simplify the setup

let me know

**Comment by TayJ26** [comment]
Tried deleting and re downloading the Zwift app and no joy. Also tried using my phone hotspot to my iPad running Zwift and still no joy showing wahoo? I’m looking to get this sorted so I can start doing events/races again and it’s quite frustrating it’s disappeared for some reason. 
[debug-Thu_Dec_19_09_10_38_2024.log](https://github.com/user-attachments/files/18189825/debug-Thu_Dec_19_09_10_38_2024.log)

**Comment by TayJ26** [comment]
Just deleted the qz app and had to remake my whole profile but that seemed to work along with deleting Zwift. Basically starting from scratch again to get wahoo to pop up.
Thanks for all your help

**Comment by cagnulein** [comment]
it was for sure a cache issue on the device, in the log qz was doing the right thing. anyway great that it's working now
