### ISSUE TITLE
Zwift gearing multi-shift feel as proposed by @GraVvVel

### ISSUE THREAD

**Issue by Nagusia** [cagnulein/qdomyos-zwift#2893]
> * When trying to shift a lot of gears (which is required in the very quick elevation changes on this route) Zwift gearing has an advantage because it combines debouncing with multi-shift, so for a single press you always only get one gear change (like debouncing active), but when you stay on the button it shifts about 1 gear per 0.5s or something similar. It would be great to have something similar, as you also have that in real world gearing

> yes I can do the same! open also another ticket for this! thanks.

I don't think a ticket has been created for this. It would be great if it were possible.

**Comment by cagnulein** [comment]
hi @Nagusia i already did 2 weeks ago https://github.com/cagnulein/qdomyos-zwift/commit/1d12f7e47512e7ea3f4de8d64366334cefead9c8#diff-7d5651645696488b077f1337c55a23d9723f25ffe3393504f5218f802905b49a

don't you try it?

**Comment by Nagusia** [comment]
No, I missed that. I will try it out, but where do I download it from? I can't see where the link on the the page you reference. In case I also missed it, did you manage to add tactile feedback to the Zwift Play gear buttons (also suggested by @GraVvVel)? And then there was the issue about Zwift virtual shifting via Wifi (for which you needed someone with a Jetblack Victory).

**Comment by cagnulein** [comment]
> No, I missed that. I will try it out, but where do I download it from? I can't see a link on the the page you reference. 

the 2.18.9 in the play store already has this

> In case I also missed it, did you manage to add tactile feedback to the Zwift Play gear buttons (also suggested by @GraVvVel)? 

nope, i didn't already 

> And then there was the issue about Zwift virtual shifting via Wifi (for which you needed someone with a Jetblack Victory). 

i didn't find anyone for this yet

**Comment by Nagusia** [comment]
OK. Many thanks for all your efforts.
