### ISSUE TITLE
[BUG] tunturi t90 inclination not working

### ISSUE THREAD

**Issue by bvdsande** [cagnulein/qdomyos-zwift#2915]
**Describe the bug**

inclination not working at all

changed the setting  inclination step to 1 in the treadmill options. 
when starting the app it is possible to go to inclination 1 with the + 
the - does not respond

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-di_dec__17_18_14_00_2024.log](https://github.com/user-attachments/files/18169161/debug-di_dec__17_18_14_00_2024.log)

**Comment by cagnulein** [comment]
got the issue, it's the same of the #1932 
for sure it's a crap of firmware in the treadmill :D anyway i'm sending you a fix. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by bvdsande** [comment]
i just send you the email. is there anything i can do with the firmware?

**Comment by cagnulein** [comment]
Nope, but with qz it will be OK :)

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 17 dic 2024 alle 21:03 bvdsande ***@***.***> ha
scritto:

**Comment by bvdsande** [comment]
this works! great job! 

at the end of the workout the machine does not stop. any suggestion what to add to do that?
this is the code i'm using.
<?xml version="1.0" encoding="UTF-8"?>
<rows>
    <row duration="00:00:10" speed="9.0" inclination="1.0" forcespeed="1"/>
    <row duration="00:00:20" speed="15.0" inclination="3.0" forcespeed="1"/>
    <row duration="00:00:10" speed="10.0" inclination="2.0" forcespeed="1"/>
    <row duration="00:00:10" speed="9.0" inclination="4.0" forcespeed="1"/>
    <row duration="00:00:20" speed="20.0" inclination="8.0" forcespeed="1"/>
    <row duration="00:00:10" speed="5.0" inclination="5" forcespeed="1"/>
    <row duration="00:00:10" speed="10.0" inclination="15" forcespeed="1"/>
    <row duration="00:00:10" speed="0.0" inclination="0" forcespeed="1"/>(this does not work to stop it)
</rows>

and is it possible to not use duration but distance? and how should that look?
thanks a lot!

**Comment by cagnulein** [comment]
I don't see the code. Maybe you forgot to share?

Are you using xml or zwo now?

**Comment by bvdsande** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<rows>
    <row duration="00:00:10" speed="9.0" inclination="1.0" forcespeed="1"/>
    <row duration="00:00:20" speed="15.0" inclination="3.0" forcespeed="1"/>
    <row duration="00:00:10" speed="10.0" inclination="2.0" forcespeed="1"/>
    <row duration="00:00:10" speed="9.0" inclination="4.0" forcespeed="1"/>
    <row duration="00:00:20" speed="20.0" inclination="8.0" forcespeed="1"/>
    <row duration="00:00:10" speed="5.0" inclination="5" forcespeed="1"/>
    <row duration="00:00:10" speed="10.0" inclination="15" forcespeed="1"/>
    <row duration="00:00:10" speed="0.0" inclination="0" forcespeed="1"/>
</rows>

**Comment by bvdsande** [comment]
(<?xml version="1.0" encoding="UTF-8"?>)
(<rows>)
 (   <row duration="00:00:10" speed="9.0" inclination="1.0" forcespeed="1"/>)
   ( <row duration="00:00:20" speed="15.0" inclination="3.0" forcespeed="1"/>)
  (  <row duration="00:00:10" speed="10.0" inclination="2.0" forcespeed="1"/>)
  (  <row duration="00:00:10" speed="9.0" inclination="4.0" forcespeed="1"/>)
    (<row duration="00:00:20" speed="20.0" inclination="8.0" forcespeed="1"/>)
   ( <row duration="00:00:10" speed="5.0" inclination="5" forcespeed="1"/>)
  (  <row duration="00:00:10" speed="10.0" inclination="15" forcespeed="1"/>)
 (   <row duration="00:00:10" speed="0.0" inclination="0" forcespeed="1"/>)
(</rows>)

**Comment by bvdsande** [comment]
i can not thare the file... its the xml

**Comment by bvdsande** [comment]
[testkort.zip](https://github.com/user-attachments/files/18171068/testkort.zip)

**Comment by cagnulein** [comment]
You can use the tag

duration with the format 0:00:00 instead of distance 

@lorenzogavanna do you have a file with distance to show to @bvdsande ?

**Comment by cagnulein** [comment]
I mean for example 

 <row distance="0.3" speed="9.0" inclination="1.0" forcespeed="1"/>

Where the 0.3 are 300 meters

**Comment by cagnulein** [comment]
Also enable this 

![image](https://github.com/user-attachments/assets/84549f86-7439-4d4e-b8a9-63ff9e8b036b)

**Comment by lorenzogavanna** [comment]
> duration with the format 0:00:00 instead of distance
> 
> @lorenzogavanna do you have a file with distance to show to @bvdsande ?
yep, here you can find an "hybrid" one with distances and durations as well.

[013.xml.txt](https://github.com/user-attachments/files/18171262/013.xml.txt)

**Comment by bvdsande** [comment]
great guys! now the belt stops and i'm able to also program distance!
is there a way to use repeats in this code? so not have to copy paste 20 times for example.

**Comment by cagnulein** [comment]
@bvdsande Do you want to repeat one line or a block of lines?

**Comment by lorenzogavanna** [comment]
@cagnulein 
I'm afraid he's thinking something about the intervalsT tag of the zwo files 
` <IntervalsT Repeat="3" OnDuration="60" OffDuration="300" OnPower="0.75" OffPower="0.5"/>` 
But then in the xml will be tricky to manage the distance and durations and all the other parameters that zwo files don't handle, but your xml does. It comes to my mind something like an interval tag for your xml something like this
`<row intervals="3">
		<row duration="00:05:00" powerzone="0.72" forcespeed="1"/>
		<row distance="5" powerzone="0.80" forcespeed="1"/>
<row closeintervals>`
in that way you just repeat x times anything is in the block....

**Comment by bvdsande** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Totale workoutduur: 54 minuten 35 seconden.>
<rows>
<row intervals="3" Repeat="3"
    
    <row distance="0.1" speed="11.5" inclination="0" forcespeed="1"/>
    <row distance="0.1" speed="13.0" inclination="0" forcespeed="1"/>
<row closeintervals>

</rows>

this is what i tried but belt started at 0.8km/h and stayed there.
any idea whats wrong?

**Comment by bvdsande** [comment]
[10x 400m - kopie.zip](https://github.com/user-attachments/files/18177263/10x.400m.-.kopie.zip)

**Comment by cagnulein** [comment]
i would suggest something about this instead

```
<rows>
    <row duration="00:01:30" powerzonefrom="0.50" powerzoneto="0.70" forcespeed="1"/>
    <repeat times="6">
        <row distance="0.4" powerzone="1.16" forcespeed="1" />
        <row duration="00:02:00" powerzone="0.75" forcespeed="1" />
        <row distance="0.4" powerzone="1.16" forcespeed="1" />
    </repeat>
    <row duration="00:03:00" powerzonefrom="0.65" powerzoneto="0.50" forcespeed="1"/>
</rows>
```

what do you think?

if you both agree i can add it

**Comment by bvdsande** [comment]
[10x 400m - kopie.zip](https://github.com/user-attachments/files/18177391/10x.400m.-.kopie.zip)
tested it but goed to 11 and then the speed dos not change.
looks  good made a little change to it.

**Comment by lorenzogavanna** [comment]
> hi guys, the repeat tag is not handled at the moment. so that's why i asked what was your target. ok so you would like to repeat some section! Let me try to handle this

yes yes I know! That's why I suggested the tag... sorry maybe it created some confusion in the other guy... Your suggestion about open amd close interval tag is excacltly what I said two comments before so for me is perfect!!

**Comment by lorenzogavanna** [comment]
> <Totale workoutduur: 54 minuten 35 seconden.> <row intervals="3" Repeat="3"
> 
> this is what i tried but belt started at 0.8km/h and stayed there. any idea whats wrong?

this is not a correct workout xml layout. Until Roberto will not implement the new tag (in any way he will find good and "code friendly") it will not work in any other way than the one I sent you yesterday.

**Comment by bvdsande** [comment]
for  me the suggestion Roberto made is perfect!

**Comment by bvdsande** [comment]
can you tell me what the forcespeed="1"/> command does?

**Comment by cagnulein** [comment]
> can you tell me what the forcespeed="1"/> command does?

it's a retrocompatibility tag, it asks to qz to handle the speed value. so if you need to change the speed, that value must be always set to 1

**Comment by cagnulein** [comment]
> but thats not something you can control, or am i wrong?

i don't understand the questions. Isn't qz already handle the speed of your treadmill?

**Comment by cagnulein** [comment]
@bvdsande  @lorenzogavanna done!

@lorenzogavanna can you try the build to check that it's working https://github.com/cagnulein/qdomyos-zwift/actions/runs/12389681632 ?

then if it works i can build the ios one for @bvdsande 

thanks

**Comment by bvdsande** [comment]
yes it does control the speed. but for example to go from 9km/h to 20km/h takes like 20sec. in the ideal world i would like to have control about this to be able to program shorter sprints for example.

**Comment by lorenzogavanna** [comment]
> would it be possible to add these buttons like in Kinni? ![20241218_094257](https://private-user-images.githubusercontent.com/88771863/396837067-c8c6d7c5-a42b-4a26-ae1f-946e9eb911c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTMyMjEsIm5iZiI6MTczNDUxMjkyMSwicGF0aCI6Ii84ODc3MTg2My8zOTY4MzcwNjctYzhjNmQ3YzUtYTQyYi00YTI2LWFlMWYtOTQ2ZTllYjkxMWMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA5MDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNDI5ZTRjODI2ZWYwOWUzNGM4NTUxYmJjN2IxMjE4OGRlMTMwZDVmZjEzNjhhMzc5ODE4MGE2N2VmMWYyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d4J3mFVF4RqYhEnEXMMu0lA4J1MoAapvily6uBzAY50)

Any suggestion different than the one of the repetition maybe is better you post separately. In github you can creat bug or suggestion post. Make a different one so everything will stay "tidy"!

**Comment by bvdsande** [comment]
okay i will create a new post for the buttons. 
where can i find the ''next step'' tile? remaining time does show the time for the current step but the ''next rows'' shows NA is there a different one available?

**Comment by cagnulein** [comment]
> where can i find the ''next step'' tile? remaining time does show the time for the current step but the ''next rows'' shows NA is there a different one available?

next rows is the right one. Are you sure you loaded a program? N/A is showing when there is no rows to process or when it set to distance (i didn't handle the distance in that tile, but in case i can add it). @lorenzogavanna did you experience the same?

**Comment by cagnulein** [comment]
handled also distance in the next rows tile https://github.com/cagnulein/qdomyos-zwift/actions/runs/12390323787 @lorenzogavanna  use this build instead, so you can try both

@bvdsande i will send you the new ios build if @lorenzogavanna will confirm that it works. thanks for the feedbacks

**Comment by bvdsande** [comment]
tried it with several programs. indeed the first one is not shown but after that it will show( a little weird overlapping though). looks like what you say is correct. distance is not shown but instead i get N/A
![Afbeelding van WhatsApp op 2024-12-18 om 11 50 57_bfa34dfa](https://github.com/user-attachments/assets/0cdf8936-f123-4411-8a5c-2173fe3e4c41)

this is during workout (in the middle )
![Afbeelding van WhatsApp op 2024-12-18 om 11 56 56_493702ef](https://github.com/user-attachments/assets/fdecb2d5-23ec-423b-83d2-f752dc569b42)

**Comment by bvdsande** [comment]
[10x 400m-test.txt](https://github.com/user-attachments/files/18180048/10x.400m-test.txt)
used file

**Comment by cagnulein** [comment]
for the overlapping, i'm adding the time in the second line so it will be better, thanks for the feedback @bvdsande

**Comment by cagnulein** [comment]
done! @lorenzogavanna new build also for this https://github.com/cagnulein/qdomyos-zwift/actions/runs/12391778211

**Comment by bvdsande** [comment]
do i need to update?

**Comment by cagnulein** [comment]
yes, i'm waiting the @lorenzogavanna before building the ios one and sending to you @bvdsande

**Comment by lorenzogavanna** [comment]
It works perfectly! Tried now with different tags and all of them were elapsed and showed properly. I tried with the windows version, but I don't think that this makes any difference. There is only one case that shows the N/A in the second row next line (the little one) that shows when it's the rep icludes distances. If it's only with durations it will be right without N/A. Since the first row show the next row properly (and calculates it everytime correctly), I don't think this is very important IMHO.

![{04259B78-01DF-4C19-8D2D-CD637133B269}](https://github.com/user-attachments/assets/20fd35e0-1ea9-4876-bd1e-26d3870628fa)

@cagnulein let me know if you need more test or anything else.

**Comment by cagnulein** [comment]
fixed also this @lorenzogavanna https://github.com/cagnulein/qdomyos-zwift/actions/runs/12394481844 thanks for the tests!
@bvdsande i'm building it!

**Comment by bvdsande** [comment]
how do i get the new version?

**Comment by cagnulein** [comment]
just sent on testflight as yesterday @bvdsande

**Comment by bvdsande** [comment]
just installed it. but im missing the start and stop buttons

**Comment by cagnulein** [comment]
i didn't change this, you probably disabled the top bar in the ui settings i guess

**Comment by bvdsande** [comment]
great, works like a charm!

**Comment by cagnulein** [comment]
amazing!
