### ISSUE TITLE
kinni speed (and incline) buttons 

### ISSUE THREAD

**Issue by bvdsande** [cagnulein/qdomyos-zwift#2917]
is it possible to add the quick buttons on the side like in Kinni?
![20241218_094257](https://github.com/user-attachments/assets/8ca558b2-0add-4269-afcb-6c433f06ea6d)

**Comment by cagnulein** [comment]
you can have the preset tiles in the tiles settings and you can put them in the order that you want :)

**Comment by bvdsande** [comment]
i dont understand. is it allready there?

**Comment by cagnulein** [comment]
yes, settings, tile settings, scroll to the bottom, preset speed and inclination. you can have 5 for each type!

**Comment by bvdsande** [comment]
wow this is great stuff! thanks!!
![Afbeelding van WhatsApp op 2024-12-18 om 12 53 08_4498eb05](https://github.com/user-attachments/assets/9b1b2411-70d0-4366-aa97-5b660e83bc36)

**Comment by cagnulein** [comment]
amazing! you can also customize the colors and the position if you want!
