### ISSUE TITLE
Problem with Zwift Play and QZ in ERG mode

### ISSUE THREAD

**Issue by serbasan** [cagnulein/qdomyos-zwift#2923]
Problem description with Zwift Play and QZ in ERG mode

I am using Zwift Play together with the QZ app to manage my indoor cycling setup. Below, I detail my setup and the specific issue I am experiencing:

Zwift Setup:

- Power and cadence source: Wahoo KICKR.
- Resistance control: My iPad.
- Additional device: Zwift Play is connected.

Behavior in SIM mode:

- Gear changes can be made directly from the Zwift Play controllers.
- The on-screen gear indicator reflects the changes accurately.
- The bike’s resistance responds correctly according to the selected gears.

Behavior in ERG mode:

- Performance is highly unstable.
- Target resistance is not consistently reached.
- There are fluctuations and a lack of precision in system response.

**Key note:**
When I configure the power, cadence, and resistance source directly on the Wahoo KICKR, ERG mode works perfectly, consistently achieving and maintaining the target resistance as expected.

Attached Data:
Two logs show poor performance in ERG mode.
One log reflects correct ERG mode performance when using the Wahoo KICKR exclusively as the source for all three settings.

[debug-CORRECT_vie_dic_20_23_35_40_2024.log](https://github.com/user-attachments/files/18216195/debug-CORRECT_vie_dic_20_23_35_40_2024.log)
[debug-POOR_vie_dic_20_00_11_13_2024.log](https://github.com/user-attachments/files/18216196/debug-POOR_vie_dic_20_00_11_13_2024.log)
[debug-POOR_jue_dic_19_23_59_15_2024.log](https://github.com/user-attachments/files/18216197/debug-POOR_jue_dic_19_23_59_15_2024.log)

**Comment by cagnulein** [comment]
Thanks it's the same of this https://github.com/cagnulein/qdomyos-zwift/issues/2897#issuecomment-2542092168

You can't use actually qz with zwift play on zwift and erg mode. You have to pair zwift play directly in qz for this at the moment 

I'm closing this one on favor of keeping one ticket only for the issue

Subscribe to that one

Thanks for reporting
