### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mrjcleaver** [cagnulein/qdomyos-zwift#2927]
**Describe the bug**
Can't move the gear  tiles on the UI because they appear off screen and there is no way to scroll

**To Reproduce**
1. Go to rearrange tiles
2. Try to move gears +/- to top
3. Try to scroll down to see gear +/-
4. See erroe

**Expected behavior**

**Screenshots**

![Screenshot_20241222_071851.jpg](https://github.com/user-attachments/assets/bd8c9412-02a1-41dc-bba8-b0067e567387)

**Smartphone (please complete the following information):**
 - Device: Samsung Ultra 22
 - OS: 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
It's possible a fo t size is bigger than defauly though ve reset what I thought is the culprit in the OS.

**Comment by cagnulein** [comment]
use the order index in the tiles settings: for example set the order index to 0 to have it on the first poisition! let me know
