### ISSUE TITLE
ProForm Bike and Rowwr stopped showing up on iphone[BUG]

### ISSUE THREAD

**Issue by scottljunggren** [cagnulein/qdomyos-zwift#2934]
**Describe the bug**

I used to be able to turn on QZ and it would automatically recognize my bike and my rower and suddenly it stopped working on my iPhone, even though it works perfectly still on my wife’s iPhone

**To Reproduce**
1. On Start
5. 

**Expected behavior**
Expect to reflect numbers on bike or rower, but no stats show up at all, even though it looks like it locks on correct device

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 18.3

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: 18.3
 - Version beta iOS 18.3 (22D5034e)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Mon_Dec_23_16_31_45_2024.log](https://github.com/user-attachments/files/18234433/debug-Mon_Dec_23_16_31_45_2024.log)

  
**Additional context**

**Comment by cagnulein** [comment]
@scottljunggren The problem is that you set ftms rower to your device. Put disabled there and press OK and restart qz and you will fix it!

**Comment by scottljunggren** [comment]
still not working sadly.  is there a way to totally reset app back to default?  i may have tried so many setting changes that maybe that is issue.

-Scott

**Comment by cagnulein** [comment]
Create a new profile and it will load the default settings. Then restart qz

**Comment by scottljunggren** [comment]
resetting profile did it, back up and running THANK YOU!!

-Scott
