### ISSUE TITLE
[BUG] Nordictrack S25 on Raspberry PI4 reporting 1km/h on Zwift

### ISSUE THREAD

**Issue by magicdude4eva** [cagnulein/qdomyos-zwift#2938]
**Describe the bug**
I am running https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md on a RaspberryPI 4 on Bookworm and am able to connect to Zwift via Apple TV through the Bluetooth bridge on the Pie. The speed shown is 1km/h and does not change. I attached the console log where I increase the speed from 2 > 4 > 6 > 8 > 12 and then back. I also adjusted the incline

**To Reproduce**
1. Compile from source
2. Run './qdomyos-zwift -no-gui -heart-service'
3. Connect to Zwift on AppleTV
4. Speed always shows 1km/h

**Expected behavior**
Zwift should display correct speed.

**Screenshots**
If applicable, add screenshots to help explain your problem:
![IMG_0519](https://github.com/user-attachments/assets/3a753700-34d6-4028-a8a9-bfb7d7269fe5)
![IMG_0520](https://github.com/user-attachments/assets/d7346728-6d51-40ec-b5e6-e7c9617192e6)

**Desktop (please complete the following information):**
 - OS: Linux gym-qdomyos 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
 - Version: Bookworm v12

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
[nordictrack-s25-appletv-zwift.txt](https://github.com/user-attachments/files/18246016/nordictrack-s25-appletv-zwift.txt)
  
  
**Additional context**
```root@gym-qdomyos:~/qdomyos-zwift/src # cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@gym-qdomyos:~/qdomyos-zwift/src # lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
root@gym-qdomyos:~/qdomyos-zwift/src # uname -a
Linux gym-qdomyos 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
root@gym-qdomyos:~/qdomyos-zwift/src # bluetoothctl --version
bluetoothctl: 5.66```

**Comment by cagnulein** [comment]
hi @magicdude4eva running QZ with the GUI did you try to enable instead the right profile of the treadmill under settings, treadmill, nordictrack options and restart QZ?

**Comment by magicdude4eva** [comment]
> hi @magicdude4eva running QZ with the GUI did you try to enable instead the right profile of the treadmill under settings, treadmill, nordictrack options and restart QZ?

I am running it headless / without a gui (my PI is in a rack and I do not have an easy way to connect it to output). Is there any way to do this via command-line? I see there is an option "-nordictrack-10-treadmill" and it would be great to perhaps have an option "-profile=norditrack_s25_treadmill" where I could pass this in.

**Comment by cagnulein** [comment]
you can use VNC. You can simply editing the settings file and add the setting norditrack_s25_treadmill and put it to true and restart QZ

**Comment by magicdude4eva** [comment]
> you can use VNC. You can simply editing the settings file and add the setting norditrack_s25_treadmill and put it to true and restart QZ

This is actually a bit of an overhead as i wanted to have a barebone install on Raspberry. Now I installed lxde and via the remote desktop started QZ - it shows no Bluetooth connections:
<img width="1348" alt="image" src="https://github.com/user-attachments/assets/41e009c8-178c-45dd-bb2a-8ed5a038a66f" />

I made no changes and the S25 was preselected:
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/223eb27d-d3c5-47f8-befa-641df0716c23" />

where is the settings file?

**Comment by magicdude4eva** [comment]
FWIW - found something under /root/.config/Roberto\ Viola/qDomyos-Zwift.conf
[qDomyos-Zwift.conf.txt](https://github.com/user-attachments/files/18246284/qDomyos-Zwift.conf.txt)

**Comment by cagnulein** [comment]
Yes that's the configure file

About connecting it means that you have Bluetooth turned off

Restart your raspberry 

The settings are applied also without the UI

**Comment by magicdude4eva** [comment]
Thank you very much @cagnulein, the config file did the trick. Was the file always there? i.e. was it created the first time QZ is run with default values? This would have been helpful to know and perhaps a reference should be made in the Wiki-article that the config-file is created with defaults.

Love your work and wish you and your loved ones a blessed holidays and successful new year.

**Comment by cagnulein** [comment]
> Thank you very much @cagnulein, the config file did the trick. Was the file always there? i.e. was it created the first time QZ is run with default values? 

Yes exactly, created at the first run

> This would have been helpful to know and perhaps a reference should be made in the Wiki-article that the config-file is created with defaults.


Yes good point!
> 
> 
> 
> Love your work and wish you and your loved ones a blessed holidays and successful new year.


Thanks, merry Christmas to you too and thanks for the coffees!
