### ISSUE TITLE
[BUG] DKN Motion0180 - no power or cadence

### ISSUE THREAD

**Issue by rvanrooy** [cagnulein/qdomyos-zwift#294]
**Describe the bug**
When connecting vie the beta android app, I can control the resistance via the plus and minus buttons in the app, but no cadence or power values are provided, and zwift or other apps cannot find the qdomyosbridge.

[debug-Wed_Apr_28_12_28_49_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6391276/debug-Wed_Apr_28_12_28_49_2021.log)
 
I am able to connect using my RPI and linux builds (UI doesn't show the tiles, but I can hear the random resistance changes if I select the random training option)

**To Reproduce**
In Settings,  Toorx/iConsole bike is selected. (Adding Jll IC400 does not work)

**Smartphone (please complete the following information):**
 - OS: Android
 - Version 2.6.18

**Comment by cagnulein** [comment]
Is it the first time that you test it on android?

**Comment by rvanrooy** [comment]
I tested it when the 2.6.18 beta came out over the weekend. I tried various settings to see if they made any difference, but I couldn't get the data to display or the bridge to be seen by Zwift.

**Comment by cagnulein** [comment]
i saw the data from your bike but, resistance apart, they are all 0.
could you also attach a log from the raspberry in order to compare them?

**Comment by rvanrooy** [comment]
[debug-Wed_Apr_28_15_56_01_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6392316/debug-Wed_Apr_28_15_56_01_2021.log)

Attached is a log from the raspberrypi.  Not quite comparable to the android one, since I can't get the tiles to display in the QML interface.

**Comment by cagnulein** [comment]
in this one the bike doesn't answer at all... try with another one :D

**Comment by rvanrooy** [comment]
[debug-Wed_Apr_28_16_30_44_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6392603/debug-Wed_Apr_28_16_30_44_2021.log)

App run on a raspberry pi with the Random training options setting enabled, The bike randomly changes resistance every 1-2 seconds while QZ is running, so I think the bike is connected in some manner to QZ, but no power, speed or cadence info displayed on either the bike or the app (though the tiles do not display, so I'm not sure what to expect from the app)

In order to get the qml interface to work, I had to change to downgrade QtQuick.* versions down to the ones available in the repos (5.11).

**Comment by cagnulein** [comment]
@rvanrooy i'm missing something.
In this log i saw only the raspberry talks, the bike never answer.

So question: did you ever see the cadence/power on raspberry? qml or not?

**Comment by rvanrooy** [comment]
No, I've never seen cadence/power reported on the pi or android.

**Comment by cagnulein** [comment]
ok now it's clear. i will recheck the hci so :) but i guess your raspi has some issue. it seems it can't receive frame

**Comment by rvanrooy** [comment]
Interesting, will swap it out for a newer rpi 4 I have available and test

**Comment by cagnulein** [comment]
i added some new frame on the init phase. give it a try on the rpi4

**Comment by rvanrooy** [comment]
[debug-Thu_Apr_29_15_56_01_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6399613/debug-Thu_Apr_29_15_56_01_2021.log)

Clean install on a rpi 4. The bike sets its resistance once QZ is started, but no obvious indication of speed / cadence / power, but qml doesn't work due QtQuick version compatibility issues

**Comment by cagnulein** [comment]
BTLE stateChanged InvalidService"


There is a bug in the qt, the same that i already fixed in android and ios.

Please wait the android one, i guess i will build it tomorrow


Il gio 29 apr 2021, 17:00 Reinhardt van Rooyen ***@***.***>
ha scritto:

**Comment by rvanrooy** [comment]
[debug-Tue_May_4_11_55_29_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6421073/debug-Tue_May_4_11_55_29_2021.log)

Tested with the updated beta Android app. No apparent change, can update the resistance from QZ, but no information regarding cadence, power

**Comment by cagnulein** [comment]
i just did a small modification in the init phase. I hope it will fix it. I'm uploading a 2.6.26 with this now.

**Comment by cagnulein** [comment]
@rvanrooy did you test the last beta?

**Comment by cagnulein** [comment]
@rvanrooy thanks for the log! i saw another small thing in the init phase! i hope it will be the last one :)
I will rebuild it tomorrow.

**Comment by rvanrooy** [comment]
HI Roberto. Thanks for the latest beta build. in v2.6.31, cadence and power is now working correctly and displayed on the application, 

I was not able to get zwift to find a qdomyosbridge, but that is likely unrelated to this issue. I'll continue for play with settings to see if it is a configuration issue on my side.

Thank you!

**Comment by cagnulein** [comment]
Great! So we can close this?
