### ISSUE TITLE
Issue with QZ 2.18 (982) and Zwift Play in SIM Mode

### ISSUE THREAD

**Issue by serbasan** [cagnulein/qdomyos-zwift#2944]
Yesterday, I updated the trial version of QZ to 2.18 (982), and this morning, I attempted to join a group ride on Zwift using QZ along with the Zwift Play controllers. In previous trial versions, SIM mode worked correctly, but today it was impossible to use, forcing me to completely disconnect QZ.

Afterward, I investigated the issue and identified the following:

Current Setup:

I use SmartSpin2k, which features virtual gears controlled via buttons for shifting up and down, allowing negative and positive values.
My bike has a screen displaying resistance, with values ranging from 1 to 24.

Previous Functionality:

When using the Zwift Play controllers with QZ, I could handle the gears without any issues, and my bike's resistance would adjust correctly.
New Behavior Observed:

Within a few seconds, QZ would automatically synchronize the gears with SmartSpin2k. For instance, if QZ was on gear 14 and SmartSpin2k on gear -9, QZ would abruptly drop the gear to 0.
This did not happen in previous trial versions, where SIM mode worked perfectly.
I suspect that a change or a newly enabled option is causing this behavior.
Attached is a log showing evidence of the issue.

Expected Functionality:

Pair Zwift with QZ and the Zwift Play controllers to manage gears from the controllers and see them reflected in Zwift's interface.
Be able to use the SmartSpin2k buttons to adjust bike resistance without interfering with the gear number in QZ/Zwift. In other words, QZ should not read the gear data from SmartSpin2k.
Previously, I used the SS2K buttons to synchronize the bike's resistance with the gear displayed in QZ/Zwift. For example, if QZ was on gear 8 and the bike's resistance was 0, I could use the SmartSpin2k buttons to adjust the resistance to 8 without any issues. Once done, I would no longer use the SS2K buttons.

I hope this information helps to resolve the issue.

[debug-vie_dic_27_08_31_27_2024.log](https://github.com/user-attachments/files/18259601/debug-vie_dic_27_08_31_27_2024.log)

**Comment by cagnulein** [comment]
@serbasan which version did you have before? can you create a similar log with the previous build using testflight app to going backward to that version? so i will compare the log, thanks

**Comment by serbasan** [comment]
I have already downgraded to a previous version and repeated the same process, and it works perfectly. I also noticed that QZ can shift to negative gears, which is not possible in the latest version. I’m attaching a log with this older version.

Thank you, and Happy Holidays!
[Uploading debug-vie_dic_27_13_30_05_2024.log…]()

**Comment by cagnulein** [comment]
hi @serbasan the log is corrupted because you pressed comment before waiting the finish of the upload, please upload it again and let me know when you did it. thanks

**Comment by cagnulein** [comment]
got the issue @serbasan it's because @doudar enabled the wattbike profile in the ss2k and i did this #2829 
let me do a patch for this

**Comment by cagnulein** [comment]
@serbasan 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and i will send you the new version. Thanks

**Comment by serbasan** [comment]
I have loaded the log again. Now I will send you an email to test the new version.

**Comment by cagnulein** [comment]
i already sent the new one @serbasan  :)

**Comment by serbasan** [comment]
Hello,  

I just tested it, but it still exhibits the same anomalous behavior. I’m attaching the log.  
[debug-vie_dic_27_16_09_53_2024.log](https://github.com/user-attachments/files/18261569/debug-vie_dic_27_16_09_53_2024.log)

**Comment by cagnulein** [comment]
I see the right behaviour now in the log. Did you restart both qz and ss2k?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 dic 2024 alle 16:30 serbasan ***@***.***> ha
scritto:

**Comment by serbasan** [comment]
Everything has been reset.  

I tested it again, and the SS2k shift buttons are still changing the gears in QZ. This didn’t happen before. I did notice that now I can switch to negative gear numbers in QZ with this new test version.  

Right now, it’s not working correctly because the SS2k buttons are still interfering with QZ, as far as I could observe.  
[debug-vie_dic_27_17_06_30_2024.log](https://github.com/user-attachments/files/18262094/debug-vie_dic_27_17_06_30_2024.log)

**Comment by doudar** [comment]
Ss2k shift buttons changing gears on QZ, that sounds desirable to me 😃

**Comment by cagnulein** [comment]
@serbasan sent a new version

**Comment by serbasan** [comment]
With this latest version, it now works as it did before.  

It’s fine for the SS2k buttons to change the gears in QZ, but it should also work the other way around, and that wasn’t happening. Changing gears from QZ or using the Zwift Play controllers didn’t affect the gear number in SS2k.  

However, I think it’s better this way—that SS2k doesn’t modify the gears in QZ. This allows for adjusting and synchronizing the gears or resistance between the bike and the gear displayed in Zwift. For example, if Zwift is on gear 10, I can use the SS2k buttons to set the bike to resistance 10, and from that point on, only use the Zwift Play controller buttons.  

Thank you for the quick response and for resolving this issue!

**Comment by cagnulein** [comment]
@doudar Using the ftms interface,  there is any way I can change gears to the ss2k?

**Comment by doudar** [comment]
Not through ftms. Only through the custom characteristic.

**Comment by doudar** [comment]
> @doudar Using the ftms interface,  there is any way I can change gears to the ss2k?

https://github.com/doudar/SmartSpin2k/blob/develop/include/BLE_Custom_Characteristic.h

**Comment by cagnulein** [comment]
@doudar Ftms and custom can cohesist? I mean can I write inclination over ftms and change gears over custom at the same time?

**Comment by doudar** [comment]
> @doudar Ftms and custom can cohesist? I mean can I write inclination over ftms and change gears over custom at the same time?

Yes

**Comment by cagnulein** [comment]
@doudar  I checked the list of the include commands, which is the right one to set the gears to a fixed number? For example at the startup zwift commands 8 and I want to set 8 to ss2k too in order to accommodate the @serbasan request

**Comment by doudar** [comment]
> @doudar Ftms and custom can cohesist? I mean can I write inclination over ftms and change gears over custom at the same time?

It's shifter position.

So (off my memory - double check this)

0x02,0x17,0x08

**Comment by cagnulein** [comment]
@serbasan So if I implement the sync command to the startup phase it will be OK? Then i leave everything as it is, right?

**Comment by serbasan** [comment]
Today, I completed a 50 km ride in SIM mode without any issues.

From my perspective, everything is working fine as it is. I turn on the SS2k, QZ, and Zwift, pair all the devices to have the gears visible on the HUD and control them with Zwift Play. Then I start a route or a race. I manually adjust the bike's resistance using the SS2k buttons to around ±8, and from there, I only use the Zwift Play controllers. This process takes me just a few seconds.

Trying to synchronize everything via software, like setting an initial automatic resistance, might create more problems than benefits. However, I understand that in other scenarios or for other users, it might be helpful to have SS2k and QZ synchronized in both directions. Adding this as an option in the settings could be interesting for those who need it.

For now, I believe the system works perfectly for me as it is. That enhancement could be considered as a future option if the need arises.
As far as I’m concerned, the issue can be closed.

**Comment by cagnulein** [comment]
thanks for the feedkback @serbasan !
