### ISSUE TITLE
Nordictrack commercial 1250  : don’t load at all when downloaded on tredmill

### ISSUE THREAD

**Issue by joshferg509** [cagnulein/qdomyos-zwift#2945]
https://github.com/user-attachments/assets/146dd6e4-68b1-489b-902f-17232754dcf6

**Comment by cagnulein** [comment]
Thanks @joshferg509it's the new ifit 2.0 right?
I uploaded today a 3.6.0 version of the companion, can you check if it's the same?
Also are you able to use adb wirelessly to it from your pc or Mac?

**Comment by joshferg509** [comment]
I’m sure it’s the I fit 2.0 I bought the tredmill brand new less then a month ago.  It’s version 3. 5. 3 
I tried the other way I couldn’t figure it out seemed super confusing. Downloaded the stuff to my windows and where it says to run the .bat file… there is absolutely no .bat file to be found so I don’t know

**Comment by cagnulein** [comment]
The 3.6.0 it's from today 

Did you also check the video Nordictrack Treadmills Wifi only finally compatible with Zwift using QZ
https://youtu.be/_KRMSHxo5AQ

**Comment by joshferg509** [comment]
Yeah that’s the video I been using to try and figure this out. Worked great til it told me I needed to open the app on the tredmill and select witch one I’m using. Just doesn’t open it pulls up the screen with the android icon and sits there forever. What should I try?

**Comment by joshferg509** [comment]
Am I doing something wrong cause I don’t see the home back or app overview buttons you’re talking about?? It just slides up shows all the apps

**Comment by cagnulein** [comment]
You can try to use the 3.6.0 as I said just to confirm if you have the same issue

If so I need adb logcat to understand it

**Comment by cagnulein** [comment]
@Maverick54400 can you help here? Did you have the same issue?

**Comment by joshferg509** [comment]
How do I update it to the newer one?

**Comment by cagnulein** [comment]
Same thing of installing it

**Comment by joshferg509** [comment]
The update worked. I don’t see the Nordic track 1250 on the list tho. What do I select??

**Comment by Maverick54400** [comment]
Yes if the companion app is not open, you should have to press on the square in the task bar and select the companion app in the list of opened app

**Comment by cagnulein** [comment]
Perfect, for now doesn't matter . enable the ocr flag and restart the treadmill

**Comment by cagnulein** [comment]
@joshferg509 By the way which model of treadmill is it?

**Comment by joshferg509** [comment]
Okay and I see debug log is check already should I leave that on?? And to restart you talking just hit the power switch and turn it back on?? Sorry dumb questions just wanna be sure lol

**Comment by joshferg509** [comment]
It’s a Nordic track commercial 1250

**Comment by cagnulein** [comment]
Yes enable also the debug log for now too. And yes restart the treadmill phisically

**Comment by joshferg509** [comment]
Okay and for device just select other?? It’s already selected on a Nordic machine and I can’t get it to go away

**Comment by cagnulein** [comment]
Don't worry for now about that selection. Leave it as it is

**Comment by joshferg509** [comment]
Appreciate your time brother!! See if I can’t finish it off with the video!! I’ll reach out if not

**Comment by joshferg509** [comment]
So when I open the app on my phone it says select your fitness device I don’t see mine popping up just a bunch of blue tooth devices I have that aren’t the tredmill. Any idea what Nordic track shows as??

**Comment by cagnulein** [comment]
There leave disabled and go on and then in the qz settings go to treadmill options, nordictrack, nordictrack 2560 and set the IP address of the treadmill and press ok and restart qz

**Comment by cagnulein** [comment]
Attach a debug log so I will check your setup https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by joshferg509** [comment]
2560 isn’t showing up on the list

**Comment by cagnulein** [comment]
Where did you set the IP? Show me a screenshot.
A debug log is better thanks
