### ISSUE TITLE
Qz connects to watch instead of tredmill

### ISSUE THREAD

**Issue by joshferg509** [cagnulein/qdomyos-zwift#2946]
https://github.com/user-attachments/assets/47bfbb26-f530-45e8-a654-5ca1fffde7e6

![IMG_1273](https://github.com/user-attachments/assets/09d3fc65-43f1-40d9-aec2-3e384c527dba)
![IMG_1274](https://github.com/user-attachments/assets/d7b35b7b-3e68-4fc5-b44b-8ed42596129d)

**Comment by cagnulein** [comment]
You shouldn't create a new one, you could attach it to the old one :) anyway I don't see the debug log.
Is the qz companion running?

**Comment by joshferg509** [comment]
Debug log? Yeah qz is running it just opens up farming and connects to my watch it’s not reading tredmill at all

**Comment by joshferg509** [comment]
Garmin not farming

**Comment by joshferg509** [comment]
I deleted the app and re downloaded it to my phone now it’s not connecting to my watch but I can’t get it to read data from tredmill

**Comment by cagnulein** [comment]
Follow this and share a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by joshferg509** [comment]
I’m giving up good luck with you app lol

**Comment by cagnulein** [comment]
I will be here if you want to try again

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 dic 2024 alle 17:21 joshferg509 ***@***.***>
ha scritto:
