### ISSUE TITLE
[BUG] Calories/distance directly from Treadmill instead of QZ

### ISSUE THREAD

**Issue by Djinn206** [cagnulein/qdomyos-zwift#2949]
Disable kcal from Machinery and everything is on, but still taken directly from Treadmill (Sportstech sTread Lite). 

Peloton Run Class on iPad Pro
QZ on iPhone 16 Pro

Debug log attached.
[debug-Fr__Dez__27_19_31_41_2024.log](https://github.com/user-attachments/files/18263095/debug-Fr__Dez__27_19_31_41_2024.log)

**Comment by cagnulein** [comment]
Beta sent, let me know!

**Comment by Djinn206** [comment]
It works, calories are calculated from QZ and not from Treadmill itself
anymore, thank you! 🙂

Best regards, Thomas

Roberto Viola ***@***.***> schrieb am Fr. 27. Dez. 2024 um
20:56:

**Comment by cagnulein** [comment]
Amazing!
