### ISSUE TITLE
[BUG] Connection issues - Proform Smart Bike 10.0c

### ISSUE THREAD

**Issue by godsmar** [cagnulein/qdomyos-zwift#2952]
**Describe the bug**
QZ app not displaying the expected stats when engaging the bike.

**To Reproduce**
N/A - still trying to make the connection

**Expected behavior**

Expect the QZ app will start showing stats when expected.

**Screenshots**

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy Z Flip4
 - OS: [e.g. iOS8.1] One UI / Android
 - Version [e.g. 22] 6.1.1 / 14

**Append a debug log**
Attached.
 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

Background - trying to use the QZ app / Companion app to connect a Proform Smart Bike 10.0c to MyWhoosh. Have successfully installed the companion app on the bike and while it seems the companion app and the mobile app are communicating, the QZ app is not showing stats and it keeps saying connecting....

Seems it is picking up my heart rate from my watch which has the QZ app installed also, which is good?

Wondering if I just have not configured correctly in either/both apps
Was unsure which bike to select from the Proform bikes as this model is not listed and so selected them all, and also not sure where to input the IP address and so put it in the Proform section under the TDF Companion IP option.

[debug-Sat_Dec_28_13_55_53_2024.log](https://github.com/user-attachments/files/18267403/debug-Sat_Dec_28_13_55_53_2024.log)
.

**Comment by cagnulein** [comment]
@godsmar enable the OCR flag in the companion
on the qz side you did everything right
Let me know!

**Comment by godsmar** [comment]
Enabled OCR and then granted QZ companion access and it worked.  Thank you.

My next challenge is to get his to work with MyWhoosh. Any advice?

**Comment by godsmar** [comment]
MyWhoosh is not detecting QZ. Are there other settings i need to switch on.

**Comment by cagnulein** [comment]
Perfect! Are you running mywhoosh on a device and qz on another? You can't run both on the same

**Comment by godsmar** [comment]
Running MyWhoosh on Win 11 laptop and QZ app on the Galaxy Z Flip4 (android).

Attaching log from QZ app for my current settings.
[debug-Sun_Dec_29_11_43_14_2024.log](https://github.com/user-attachments/files/18270306/debug-Sun_Dec_29_11_43_14_2024.log)

**Comment by cagnulein** [comment]
You have the virtual device ifit enabled in the experimental settings.
Disabled it and restart qz 
Let me know

**Comment by godsmar** [comment]
Have also noticed that sometimes the QZ app will continue to gather stats even if it is paused and I am not spinning the peddles.  At one point it said I was going 600 miles an hour during one of these pauses.  If I reset the app. it seems to stop doing it.  Not sure if there is another setting or something I should be selecting to prevent that.

**Comment by cagnulein** [comment]
> Have also noticed that sometimes the QZ app will continue to gather stats even if it is paused and I am not spinning the peddles.  At one point it said I was going 600 miles an hour during one of these pauses.  If I reset the app. it seems to stop doing it.  Not sure if there is another setting or something I should be selecting to prevent that.

Was the speed greater than 0? Probably because the last value was greater than 0 and it didn't receive a new one. Anyway this is of course fixable

**Comment by godsmar** [comment]
The disabling of the ifit setting worked. Thanks.

Regarding the continued stats, is it a good idea to bring everything to a stop before stopping the session?  I guess i am asking if there is a simple work around apart from resetting the app each time it does it.

**Comment by cagnulein** [comment]
That's great! Simply close the app before doing a workout so you will start a clean session

**Comment by godsmar** [comment]
Restarted the app, have not started a workout, and i have set it to pause using the pause setting.

And without doing anything speed is showing as 21.1 m/hr and the odometer is slowly incrementing, and the watts show a flashing 23. screen capture attached from my phone
![Screenshot_20241229_120725](https://github.com/user-attachments/assets/3ec27307-3470-4f26-9882-f20238ccaf89)

**Comment by cagnulein** [comment]
Anyway this doesn't matter since mywhoosh is counting the odometer and speed by itself.

I guess it's a speed read somehow from the bike 

Do you have a debug log with this issue?

**Comment by godsmar** [comment]
No debug issues logged at this time.  I did notice that if I turned on the speed calculated by cadence from QZ that it resolved that partially.  The QZ is picking up watts from the bike it seems, even when I am not doing anything. Just flashes 23 to 0 over and over. It is doing it every time now and so going to reboot the bike and see.  And then check if I have anything set around watts in qz.

Will log a debug if I am unable to fix.  Thanks

**Comment by cagnulein** [comment]
On the companion 3.6.0 should be already fixed this. Which companion
version are you using?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 29 dic 2024 alle 18:18 Richard Godsmark <
***@***.***> ha scritto:

**Comment by godsmar** [comment]
Version 3.6.0

**Comment by godsmar** [comment]
reboot of everything seems to have addressed it.

**Comment by godsmar** [comment]
Think you can close this ticket.  If I have other questions, where is the best place to ask?

Trying to figure out if I can get the auto resistance to work.

**Comment by cagnulein** [comment]
You can write it here even if it's closed :)

**Comment by godsmar** [comment]
ok, thanks.  The watts are stilling jumping around but not too bad but more interested in getting the automatic reistence to work.

I have it set to ERG mode right now and can hit the buttons to change it where required however this bike can automatically adjust itself through ifit and even in the manual ride if I set a target watt.  Just wondering if there are certain settings I need to make sure are enabled/disabled in QZ.

Thanks

**Comment by cagnulein** [comment]
It's quite hard to do this. First of all we need to check if pressing the
inclination tile on qz you are observing a touch event on the touch of the
bike
I'm  going to bed now
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 29 dic 2024 alle 22:03 Richard Godsmark <
***@***.***> ha scritto:

**Comment by godsmar** [comment]
The inclination and resistance tiles didn't do anything. However when I switched on target watts on the bike, the resistance tile changes to match that number.

Anyway, this is not required and am happy to manually adjust. Thanks.

**Comment by cagnulein** [comment]
In order to understand this we need to access to adb to the tablet. If you are able to we can continue to investigate this

**Comment by godsmar** [comment]
Happy to continue if it helps others however not a priority for me as i am ok to manually change the resistance.

If you wanted to send me some instructions I will tinker and send you the results.

Thanks
Richard

**Comment by cagnulein** [comment]
you can check this to gain adb https://github.com/cagnulein/qdomyos-zwift/issues/2878#issuecomment-2563809194
Let me know!
