### ISSUE TITLE
[BUG]Problem with initial resistence when using an initial gear setting

### ISSUE THREAD

**Issue by Mrschley** [cagnulein/qdomyos-zwift#2953]
**Describe the bug**
When I start a ride, gear is set to 18 as expected but resistance is 1.

**To Reproduce**
1. Start a ride
2. Notice gear is at 18 and resistance is at 1.
3. Try changing gears and notice resistance doesn't change.  
4. Change resistance and notice it jumps to 20.
5. Change resistance again and notice is jumps to 32 and gets stuck there.

**Expected behavior**
Bike should start at gear 28 and resistance 20.

**Screenshots**

![image](https://github.com/user-attachments/assets/b95be6b3-2fa9-4edd-aa63-e9a0e1070943)

![image](https://github.com/user-attachments/assets/bef8f999-8ce1-4cb5-a7bd-5726391224a1)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  Samsung S22
 - OS: [e.g. iOS8.1]  Android
 - Version [e.g. 22]  14

**Append a debug log**

  
[debug-Sat_Dec_28_15_11_08_2024.log](https://github.com/user-attachments/files/18267638/debug-Sat_Dec_28_15_11_08_2024.log)
[Uploading 0QZ-backup-Sat Dec 28 15_11_12 2024.fit…]()

  
**Additional context**
One other comment:
I tried to submit this bug report from my phone.  When I go into My Files, I can find the Qz log file just fine.  However, when I use the link below ("Paste, drop, or click to add files") to get the file, I can't seem to navigate to the correct folder.  I can find "Internal Storage" but not "Documents."  So I had to email the log to my desktop and submit this ticket from there.

**Comment by cagnulein** [comment]
thanks i will check it asap

**Comment by cagnulein** [comment]
i suggest to use the Resistance at Startup setting instead and disable the restore gear value at startup. this last setting is for the trainers, like zwift hub, to set a startup gear

Let me know!

**Comment by Mrschley** [comment]
Ok.  Thanks.  So it starts with a gear of 0 and resistence of 20.  If i
want to lower the resistence, I need to go into negative gears.  I guess
that will work.

Another question, when I'm in "unlock mode" to move tiles around, I can't
scroll down to tiles further down the page.  Is that true on your device?

**Comment by cagnulein** [comment]
yes it's a known bug, you have to change the order using the order index in the tiles settings

**Comment by cagnulein** [comment]
yes because the big gear tile is a single tile splitted in 2 :)

**Comment by Mrschley** [comment]
Last question, why is there a + and - on the speed tile?

**Comment by cagnulein** [comment]
For treadmills  :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 29 dic 2024 alle 20:32 Mrschley ***@***.***> ha
scritto:

**Comment by Mrschley** [comment]
thanks.  ok to close ticket.
