### ISSUE TITLE
[BUG] auto resistance not adjusting on hills

### ISSUE THREAD

**Issue by mystikice** [cagnulein/qdomyos-zwift#2959]
[**Describe](url) the bug**
Auto resistance does not work on hills
**To Reproduce**
[debug-Sun_Dec_29_21_12_45_2024.log](https://github.com/user-attachments/files/18271815/debug-Sun_Dec_29_21_12_45_2024.log)

**Expected behavior**
The auto resistance works on the training modes, but not hills

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
You have the zwift erg mode enabled in qz. Disabled it to have auto
resistance on hills

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 30 dic 2024 alle 04:31 mystikice ***@***.***>
ha scritto:

**Comment by mystikice** [comment]
It worked! Thank you!

**Comment by cagnulein** [comment]
amazing!
