### ISSUE TITLE
[BUG] No resistance change in rouvy

### ISSUE THREAD

**Issue by satchafunkilus** [cagnulein/qdomyos-zwift#2962]
**Describe the bug**
Been having this bug now for a couple of times, without being able to consistently reproduce it. When it happens, there is no change in resistance when shifting. Resistance in qz always stays at 0.0. I am using the wahoo virtual shifting implementation. 

When i select my trainer as ftms bike the resistance changes, but then i can shift above and below the boundaries which again leads to inconsistent behavior. 

The strange thing is that ln some days it works without issues and sometimes this problem appears, without having done any changes. 

Please see logs attached. First one should be with wahoo shifting. Second one is qz restart with ftms bike set. 

[debug-Mo__Dez__30_17_36_24_2024.log](https://github.com/user-attachments/files/18276423/debug-Mo__Dez__30_17_36_24_2024.log)
[debug-Mo__Dez__30_17_33_01_2024.log](https://github.com/user-attachments/files/18276424/debug-Mo__Dez__30_17_33_01_2024.log)

**Comment by satchafunkilus** [comment]
Haha nevermind, just noticed I had ERG mode turned on by mistake.

**Comment by cagnulein** [comment]
great! :)
