### ISSUE TITLE
[BUG] Kingsmith R2 Pro no steps 

### ISSUE THREAD

**Issue by mmolletje** [cagnulein/qdomyos-zwift#2964]
**Describe the bug**
Steps and steps per minute can be used by swift, but not read by the qz app

**To Reproduce**
1. Start treadmill
2. Start qz
3. Start running
4. Steps and steps per minute remain 0

**Expected behavior**
Show same as on treadmill display and forward to zwift.

**Screenshots**

**Tablet (please complete the following information):**
 - Device: Samsung Galaxy S5e
 - OS: Android (LineageOS)
 - Version 14

**Append a debug log*
[debug-Mon_Dec_30_20_34_34_2024.log](https://github.com/user-attachments/files/18277386/debug-Mon_Dec_30_20_34_34_2024.log)

**Comment by mmolletje** [comment]
![20241230_203737](https://github.com/user-attachments/assets/19530322-9e1e-4700-a2a1-6a0b54923d95)

**Comment by cagnulein** [comment]
Disable the ignore heart from the machinery. It's this the issue

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 30 dic 2024 alle 20:50 Mark Rietveld ***@***.***>
ha scritto:

**Comment by mmolletje** [comment]
It works! Thank you! Happy :-)

**Comment by cagnulein** [comment]
Amazing! Feel free to join patreon to support the app if you already didn't! https://www.patreon.com/cagnulein
