### ISSUE TITLE
[REQ] Support for Garmin Vector 3 power pedals

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#2966]
I don't see support for this device. Not a high priority, but I have a pair and can help you collect information for supporting them.

**Describe the solution you'd like**
QZ detects and connects to Garmin Vector 3 pedals and gets power readings from them.

**Describe alternatives you've considered**
None.

**Additional context**
NRF Connect log:
[Log 2024-12-30 21_31_44.txt](https://github.com/user-attachments/files/18277924/Log.2024-12-30.21_31_44.txt)

**Comment by cagnulein** [comment]
did you already try to pair them under settings, accessories, power sensor and press ok?

**Comment by drmason789** [comment]
That works, thanks.
