### ISSUE TITLE
[BUG] Compilation issue

### ISSUE THREAD

**Issue by grigory707** [cagnulein/qdomyos-zwift#298]
Compilation process freeze on this stage on rasperry pi 0.. This is fixable?
`fit-sdk/fit_mesg_broadcaster.cpp: In member function ‘FIT_BOOL fit::MesgBroadcaster::Run(std::istream&)’:
fit-sdk/fit_mesg_broadcaster.cpp:33:16: warning: variable ‘fileSize’ set but not used [-Wunused-but-set-variable]
     FIT_UINT32 fileSize = 0;
                ^~~~~~~~
`

Or maybe someone have latest compilled archive?

**Comment by cagnulein** [comment]
run make without -j options

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 mag 2021 alle ore 17:00 grigory707 ***@***.***>
ha scritto:

**Comment by grigory707** [comment]
Yes. This is just `$make` like in instructions.

**Comment by cagnulein** [comment]
please post here the command line that you'are executing, the freeze problem is usually a out of ram issue due to multithread build stuff

**Comment by grigory707** [comment]
![qz](https://user-images.githubusercontent.com/77836827/116899173-e7fd8200-ac3f-11eb-8b57-e5c849500f2b.png)

**Comment by grigory707** [comment]
i can interrupt it by ctrl+c. process just stopped here

**Comment by cagnulein** [comment]
Did you try to wait? I mean 10 minutes?

**Comment by grigory707** [comment]
Yes, during the night. ~8h i think.
But you say about memory.. i killed almost all other process and it start to move on. Hope it can run to finish line)

**Comment by cagnulein** [comment]
Keep top open on another she'll and you will see the memory

Il lun 3 mag 2021, 18:22 grigory707 ***@***.***> ha scritto:

**Comment by shoulih** [comment]
@grigory707 @cagnulein I also use the QZ on pi zero and I am never able to finish the compilation on Pi 0 until I found a workaround.  The workaround is to compile it on a pi3 b and use the binary on pi zero.

**Comment by grigory707** [comment]
@shoulih Yes. I am to. The solution is free memory is possible and it's work then. Thanks @cagnulein.

**Comment by cagnulein** [comment]
Thanks i didn't remember it

Il mar 4 mag 2021, 20:19 shoulih ***@***.***> ha scritto:
