### ISSUE TITLE
Frequent 20-30 seconds disconnections

### ISSUE THREAD

**Issue by PikPim** [cagnulein/qdomyos-zwift#300]
With the latest update in the Beta app, I get frequent bluetooth disconnections. This happened before (a bit less frequent though). What has changed now, is that it takes around 30sec for the connection to come back up. Before this update the connection would pick up almost instantaneously, making those disconnections barely noticeable. Now, with a disconnection every 3 minutes or so for 30 sec, it's quite anoying! I don't know what changed concerning reconnection with the last update but please revert it to the previous state.

Setup: Iphone 8 for qdomyos, paired with ipad 8th gen for Zwift and Echelon EX3 bike.

(attached log and strava graph to show how it looks)

![StravaSpeedGaps](https://user-images.githubusercontent.com/81532015/117301241-6e84b000-ae48-11eb-89e6-1669b6591697.jpg)

[debug-Thu_May_6_06_18_21_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6434551/debug-Thu_May_6_06_18_21_2021.log)

**Comment by cagnulein** [comment]
hi, i didn't do anything about bluetooth since a month :)
Which was the previous version for you? From your log i saw that it's the
bike that it doesn't answer after disconnection.
Also the disconnections seems to be very deterministic: i'm wondering if
you have something that starts every 3 minutes.
Anyway exit from the beta group and try the production one with this setup.
Also another thing to try is to swap the devices

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 6 mag 2021 alle ore 15:00 PikPim ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@PikPim any news?

**Comment by PikPim** [comment]
So I can't seem to connect zwift to my phone using the "retail" version of qdomyos (but beta version connects instantaneously).
I'll try with an older version of the app in the beta program and update afterwards.

**Comment by PikPim** [comment]
Hello, sorry for the delay.
So I've tried 2.6.12 and 2.6.30 on a brand new echelon ex3 bike (my old one had mechanical issues, they sent me a new one).
I can reproduce the exact same behavior on 2.6.30 (disconnections every 3 to 8 minutes, with 30 sec downtime before reconnecting)
On 2.6.12 the disconnections are less frequent, and the reconnection is instantaneous.
I don't have other IOs devices other than my Ipad and I haven't been able to run both Zwift and Qdomyos on the same device.
I could try on an android phone, if you can send me a beta access for Android.

**Comment by cagnulein** [comment]
Did you try to turn off the wifi on the iPhone?
For android, write me to roberto.viola83 at gmail.com and i Will add to the
beta.

Il mar 18 mag 2021, 13:11 PikPim ***@***.***> ha scritto:

**Comment by PikPim** [comment]
While disabling the wifi, I still get disconnections. They're a bit less frequent, but still present. And with the latest version (2.6.30) the reconnection still takes a solid 30 sec. I reverted back to 2.6.12 where reconnection are instantenous, which makes the app actually usable.
I'm not able to test on android unfortunately, it seems like my device is too old and can't connect more than one bluetooth device at once.

**Comment by cagnulein** [comment]
@PikPim could you please send me a 2.6.12 full debug log in order to compare them?

**Comment by PikPim** [comment]
[debug-Thu_May_27_11_54_52_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6560138/debug-Thu_May_27_11_54_52_2021.log)
[debug-Thu_May_27_12_21_51_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6560140/debug-Thu_May_27_12_21_51_2021.log)

**Comment by PikPim** [comment]
Attached 2 logs from yesterday, I also got a crash (sent a report from IOs for it), maybe the logs will give you additional infos!

**Comment by cagnulein** [comment]
@PikPim could you link me your strava account? i would like to check the 6th may workout. I checked again the log and i didn't understand the issue

**Comment by cagnulein** [comment]
@PikPim the crash was already fixed in the latest betas

**Comment by cagnulein** [comment]
@PikPim could you please try the 2.6.21 without the ios peloton workaround on?

**Comment by PikPim** [comment]
@cagnulein it seems like disabling the "ios peloton workaround" did fix my issue! thanks!
