### ISSUE TITLE
[BUG] QZ on Rasberry and Zwift on Android tablet : Disconnection after zwift recent update

### ISSUE THREAD

**Issue by urbanspike** [cagnulein/qdomyos-zwift#301]
Hello,
Since the last zwift update on android, I sometimes have QZ disconnections on the raspberry. Are other users having the same problem? Have you made any updates to QZ since my installation in January (I didn't install again)?

thank you,

**Comment by cagnulein** [comment]
i guess it's similar to #300

**Comment by cagnulein** [comment]
post the log here

**Comment by urbanspike** [comment]
I point out that this happens randomly. Sometimes QZ and zwift are ok for 10-20-30-40 ... minutes then zwift loses connection. And to put it back you have to close the bridge, relaunch and append to zwift again and there sometimes you have to start over several times before it is stable, it's pretty weird. And only since zwift spent 2 updates on android. I will try to find a log that illustrates this. Not easy to find because I did a lot of testing when it happened.

**Comment by cagnulein** [comment]
Ok i need the log to understand this.
Take your time

**Comment by cagnulein** [comment]
i'm closing this. If you have any other updates let me know
