### ISSUE TITLE
ANT+ for Linux

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#305]
Hi,
Do you think ANT+ broadcast support could be available on Linux using these please:

https://github.com/asantacreuTwoNav/python-ant

And

https://github.com/oldnapalm/vpower

(I got the Qt version of QZ built and running by using 32 bit Ubuntu 21.04 on my Raspberry Pi and then copying pre-built binaries (sadly were 32 bit, hence the OS choice) in to the QT folders to make up for anything missing, and it seems to work, as the QT version is the  right version. No ANT+ and it doesn't seem to save a fit file, but I had expected that.) 

Obviously this is a bit niche, so I understand if you don't want to take it on. More coffees would, of course, be in order. 

Jonathan

**Comment by jonathancolledge** [comment]
I use that, but searching the whole file system yields no fit files, where
might I find it? If there, then no need for ANT+ as I'll get my training
load on Garmin from heart rate.

**Comment by cagnulein** [comment]
It should be placed in the same binary directory.

Il lun 10 mag 2021, 18:25 jonathancolledge ***@***.***> ha
scritto:

> I use that, but searching the whole file system yields no fit files, where
> might I find it? If there, then no need for ANT+ as I'll get my training
> load on Garmin from heart rate.
>

**Comment by jonathancolledge** [comment]
OK, thanks, I'll check again tonight

**Comment by cagnulein** [comment]
Eheheh Great!

Il mar 11 mag 2021, 05:49 jonathancolledge ***@***.***> ha
scritto:
