### ISSUE TITLE
[BUG] Crash while Running iOS app built from source

### ISSUE THREAD

**Issue by kadaan** [cagnulein/qdomyos-zwift#306]
**Describe the bug**
Crash while running master

**To Reproduce**
1. Run app
2. Wait
3. Crash

**Expected behavior**
No crash

**Screenshots**
```
2021-05-10 23:55:00.081849-0700 qdomyoszwift[5199:615626] "Last CrankEventTime: 41448"
2021-05-10 23:55:00.290774-0700 qdomyoszwift[5199:615828] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: BundleVersion)'
*** First throw call stack:
(0x1a847e5b4 0x1bcefd7a8 0x1a84f0a80 0x1a84fcca8 0x1a835b178 0x109b55d90 0x109b57948 0x1f43bad28 0x1f43bc01c 0x1f43bc220 0x109b55d90 0x109b58e80 0x109b6eca0 0x109b5dcbc 0x109b5ecc4 0x109b6ba00 0x1f3e9a7a4 0x1f3ea174c)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: BundleVersion)'
terminating with uncaught exception of type NSException
```

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.5
 - Version: ???

**Additional context**

**Comment by cagnulein** [comment]
which bike are you using? also could you please attach a complete stack trace?
log file, when enabled in the experimental settings "debug log" are located in the files app, under qdomyos-zwift folder

**Comment by cagnulein** [comment]
as discussed by Telegram, probably related to some other devices around you (sole elliptical??)

**Comment by cagnulein** [comment]
are you still have this issue or we can close this @kadaan ?

**Comment by kadaan** [comment]
You can close it. TY
