### ISSUE TITLE
macOS binary issue

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#31]
@cagnulein I installed the QT package on my mac and then I launched your compiled 0.8 version.
But I'm obtained the following messages.
Have you some help for me?
Thank you 

/Users/Alberto/Downloads/qdomyos-zwift ; exit;
Alberto@Albertos-MacBook-Pro ~ % /Users/Alberto/Downloads/qdomyos-zwift ; exit;
dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/Alberto/Downloads/qdomyos-zwift
  Reason: image not found
zsh: abort      /Users/Alberto/Downloads/qdomyos-zwift

[Process completed]

_Originally posted by @alpat59 in https://github.com/cagnulein/qdomyos-zwift/issue_comments/711416056_

**Comment by cagnulein** [comment]
@alpat59 if you rebuild from source, recompile this tree https://github.com/cagnulein/qdomyos-zwift/tree/0.8.0 not the master, because i'm working on it

**Comment by cagnulein** [comment]
@alpat59 i've to rebuild the macOS package with https://doc-snapshots.qt.io/qt5-5.9/osx-deployment.html#macdeploy
I will do this evening or tomorrow evening. If you will rebuild it from source you shouldn't have this issue

**Comment by cagnulein** [comment]
@alpat59 i guess i solve the issue with this https://github.com/cagnulein/qdomyos-zwift/commit/34e69f55ae6fcc5d69da9fcf457baa9a83f72595
tonight i will update the mac version

**Comment by cagnulein** [comment]
[qdomyos-zwift.app.zip](https://github.com/cagnulein/qdomyos-zwift/files/5408274/qdomyos-zwift.app.zip)
@alpat59 could you please try?

**Comment by cagnulein** [comment]
@martoni74 could you please try the binary that i attached in the previous comment?

**Comment by Martoni74** [comment]
Hello,
We left in holliday for a few days (didn't find the time to test with the kids :-) ).
I will test on Sunday.
I got also a spare RPi 3 to compare now.
Have a nice week

**Comment by Martoni74** [comment]
same as alpat59 on MacOS :
/Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
  Reason: image not found
Abort trap: 6
I have installed qt5 with editor ...
Now, during installation, they asked me to install XCode, is it necessary ?

**Comment by cagnulein** [comment]
hi @Martoni74 , no xcode is not necessary. Could you please try to open the .pro file on QtCreator and try to build it? 
On my macbook air it works, i don't understand which are the differences on your side.

**Comment by cagnulein** [comment]
> same as alpat59 on MacOS :
> /Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
> dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
>   Referenced from: /Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
>   Reason: image not found
> Abort trap: 6
> I have installed qt5 with editor ...
> Now, during installation, they asked me to install XCode, is it necessary ?

Did you try to run directly the qdomyos-zwift.app icon by double clicking on it?

**Comment by Martoni74** [comment]
> > same as alpat59 on MacOS :
> > /Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
> > dyld: Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
> > Referenced from: /Users/martinlecossec/Downloads/Sport/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
> > Reason: image not found
> > Abort trap: 6
> > I have installed qt5 with editor ...
> > Now, during installation, they asked me to install XCode, is it necessary ?
> 
> Did you try to run directly the qdomyos-zwift.app icon by double clicking on it?

Yes (right-click + open, accept security warning), and in the package as well. I get that error 👍 
(I have not clone and compile the pro version however, I try that in the following days)

```
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /private/var/folders/*/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
  Reason: image not found

Binary Images:
       0x102381000 -        0x102417fff +com.cagnulein.qdomyos-zwift (0) <5D93688B-F6C6-3595-923F-16C6A6D19DE1> /var/folders/*/qdomyos-zwift.app/Contents/MacOS/qdomyos-zwift
       0x1032e3000 -        0x10334d70f  dyld (655.1.1) <DF71FC3D-E58F-3D48-9165-3B96FF8BFA22> /usr/lib/dyld
```

**Comment by Martoni74** [comment]
I've seen the readme update and the requirement of XCode CLI from @richardwait
I will install that.

**Comment by cagnulein** [comment]
> I've seen the readme update and the requirement of XCode CLI from @richardwait
> I will install that.

i guess it's useful only to compile it, not to running. Anyway install it, make Qt guys happy :D

**Comment by cagnulein** [comment]
this weekend i would like to build it statically, i think it's best solution https://doc.qt.io/qt-5.9/osx-deployment.html

**Comment by cagnulein** [comment]
built statically. @Martoni74 try https://github.com/cagnulein/qdomyos-zwift/releases/tag/1.3.1
