### ISSUE TITLE
Would like option  to use external cadence sensor on bike to override bike computer's cadence sensor

### ISSUE THREAD

**Issue by lychee128** [cagnulein/qdomyos-zwift#317]
My external cadence sensor (Wahoo) is more accurate than my bike’s built in sensor.  Therefore, I would like an option for the app to use this external sensor rather than read the bike's own cadence sensor when broadcasting to external apps via bluetooth (eg, Peloton digital app)

However, I would only like the cadence info to be substituted.  All other data for your app should continue to be read (and transmitted) from the bike's computer.

Thanks!

**Comment by cagnulein** [comment]
i don't remember, are you on iOS? i just finished to implement it @lychee128

**Comment by lychee128** [comment]
Yes, I’m on iOS

**Comment by lychee128** [comment]
I'm assuming since I'm on iOS, I need to wait for your latest beta to show up in TestFlight, correct?  Thanks.

**Comment by cagnulein** [comment]
Yes i Will build it tomorrow

Il gio 13 mag 2021, 18:04 lychee128 ***@***.***> ha scritto:

**Comment by lychee128** [comment]
Thanks!

**Comment by cagnulein** [comment]
Version sent

Il gio 13 mag 2021, 18:59 lychee128 ***@***.***> ha scritto:

**Comment by lychee128** [comment]
I assume the option is under FTMS Accessory Options?  And I just select my cadence sensor?

How can I confirm that it's working?  Right now, I selected it but I don't think it's actually reading my sensor even though it's connected.  I'm guessing because the cadence never drops below about 50.  The Wahoo can read when I'm pedaling slow so will display as low as 40-45.  However, the Flywheel doesn't really work below 50 or so.  When I connect to the Wahoo directly with my Peloton app (or Wahoo app), I see 45.  However, right now, when I connect to the Wahoo sensor from your app, I cannot get below 50 (just as the original situation if I just use the Flywheel sensor).

Is there a way to confirm that I'm displaying the Wahoo reading?  And if so, any reason why I can't see low readings?

Thanks.

**Comment by cagnulein** [comment]
no @lychee128 FTMS accessory is the setting about #299 
You have to use the cadence sensor setting without enabling the "cadence sensor as a bike" setting.

**Comment by lychee128** [comment]
Got it.  Sorry, my mistake.  So to confirm...  under the "Cadence Sensor Options" section, I select my cadence sensor and leave the "Cadence Sensor as a Bike" setting off, correct?

And is only the cadence data being substituted during transmission?  For other data displayed that uses the Flywheel cadence to make calculations, will the original Flywheel cadence rate be used to do calculations?

Thanks.

**Comment by cagnulein** [comment]
> Got it. Sorry, my mistake. So to confirm... under the "Cadence Sensor Options" section, I select my cadence sensor and leave the "Cadence Sensor as a Bike" setting off, correct?

yes, exactly

> And is only the cadence data being substituted during transmission?

yes!

 For other data displayed that uses the Flywheel cadence to make calculations, will the original Flywheel cadence rate be used to do calculations?

I will use the wahoo one, on every point that i'm actually using the Flywheel cadence. So it's like that your flywheel doesn't send at all the cadence ;)

**Comment by lychee128** [comment]
Great - thanks for the fast response!  I'll play around with this and let you know how it goes.  One problem with the Flywheel is that below around 50 or so for cadence, the data gets very erratic so I'm hoping the Wahoo data will be much more accurate.

Thanks again!

**Comment by cagnulein** [comment]
@lychee128 yesterday another user tried this with a echelon bike with a faulty cadence sensor and told me it worked well, so i guess it should work for you too :)
Close this in case it will work

**Comment by lychee128** [comment]
The app is definitely connected to my Wahoo sensor and can display low levels of cadence (30-35). However, the data displayed on my Peloton digital app that is connected to the app is wrong. Cadence shows as 99999 or other random numbers. I’m the past, it might show for a second or 2 and then correct. However, the cadence doesn’t correct. Any adjustments I can make?

**Comment by cagnulein** [comment]
Could you send me the debug log? It shouldn't be related to this one. Are you sure that ios Peloton workaround is ON?

**Comment by cagnulein** [comment]
@lychee128 any updates on this?

**Comment by lychee128** [comment]
For some reason, I could never eliminate the lag. I believe the debug log I sent you showed that they data was correct but the cadence always was significantly delayed in the display.  Currently, I’m just using the Flywheel cadence. It’s less reliable but no lag

**Comment by cagnulein** [comment]
let's wait for someone else with similar setup...

**Comment by lychee128** [comment]
Sounds good. I tested it again last week and still got the same delay.  I’ll wait to see if someone else with a Flywheel and Wahoo cadence sensor sees the same issue.  Thanks.
