### ISSUE TITLE
[BUG] Not able to change or save those "On" or "Off" settings of QZ on Raspberry Pi platform

### ISSUE THREAD

**Issue by shoulih** [cagnulein/qdomyos-zwift#326]
Complied from the github source with the correct qt version on the pi 3 and able to start qz "qdomyos-zwift -qml" command;
in the settings, the change to those "On" or "Off" settings didn't persist for some reason, but only the change to those text box values is saved and is working, which has been confirmed by starting qz w/o "-qml" parameter.

Can you please look into to it when you get a chance?

Thanks in Advance,

**Comment by cagnulein** [comment]
Ok i will check it

Il dom 23 mag 2021, 17:16 shoulih ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i tried this but it's working for me. Do you still have this issue @shoulih  ?
