### ISSUE TITLE
[REQ] Add strokes per minute tile for people using Rowers

### ISSUE THREAD

**Issue by eelwk** [cagnulein/qdomyos-zwift#330]
**enhancement request**
Thank you for Roberto for adding support to qdomyos-zwift for rowers and specifically the city rower / water rower! One tile that would be extremely helpful to add to the streaming workout statistics is "strokes per minute" which is like the cadence metric for rowers.

**Comment by cagnulein** [comment]
Just to be sure: you're just asking to rename the cadence tile to
strokes/minute isn't it?
I mean you are already seeing the stroke pee minute in the cadence tile,
right?

Il ven 28 mag 2021, 16:21 Kathy Lee ***@***.***> ha scritto:

**Comment by eelwk** [comment]
Just did a test and it is always 4x!

**Comment by cagnulein** [comment]
Ok i will fix this tonight :)

Il ven 28 mag 2021, 17:47 Kathy Lee ***@***.***> ha scritto:

**Comment by eelwk** [comment]
Thanks! Also, since the cadence tile has this, no need for an additional tile!

**Comment by cagnulein** [comment]
Sure, i will do on my tomorrow morning, your night. I'm too tired today ;)

Il ven 28 mag 2021, 20:41 Kathy Lee ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@eelwk i'm uploading it right now ;)
