### ISSUE TITLE
Smartrow

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#340]
https://smartrow.fit/#/home

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6594087/btsnoop_hci.log)

**Comment by cagnulein** [comment]
[btsnoop_hci_roberto1.log](https://github.com/cagnulein/qdomyos-zwift/files/6602148/btsnoop_hci_roberto1.log)

**Comment by cagnulein** [comment]
[2021-06-05T033749_25m-1.tcx.zip](https://github.com/cagnulein/qdomyos-zwift/files/6602964/2021-06-05T033749_25m-1.tcx.zip)

**Comment by cagnulein** [comment]
Missing tiles need to be added

**Comment by mgarcea** [comment]
Connects! However, .fit file requires some dialing in.  Here is output comparing metrics from a rowing session on my Garmin watch (which only counts strokes) vs  what QZ is sending currently. These are different sessions, just comparing the info as displayed in Garmin Connect.

Garmin Watch - Rowing Activity
![Row1](https://user-images.githubusercontent.com/84399684/121591061-4c0d2600-c9f6-11eb-9fda-1eb69707b9e9.jpg)
![Row2](https://user-images.githubusercontent.com/84399684/121591062-4ca5bc80-c9f6-11eb-9566-bcaa3ff52054.jpg)

QZ with SmartRow
![Row3](https://user-images.githubusercontent.com/84399684/121591064-4ca5bc80-c9f6-11eb-958c-bdd9ce961ec8.jpg)
![Row4](https://user-images.githubusercontent.com/84399684/121591066-4ca5bc80-c9f6-11eb-9d4c-280f7f7aca24.jpg)

**Comment by cagnulein** [comment]
Could you send me a debug log and the fit file?
Thanks

Il gio 10 giu 2021, 22:20 mgarcea ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
[debug-Wed_Jun_9_23_21_28_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6643559/debug-Wed_Jun_9_23_21_28_2021.log)
[1QZ-backup-Wed-Jun-9-23_21_28-2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/6643561/1QZ-backup-Wed-Jun-9-23_21_28-2021.zip)

**Comment by mgarcea** [comment]
Looks much better, almost perfect I think!  The "Best Pace" looks incorrect I think.  Would it also be possible to add the stroke metrics to the .fit file for import into Garmin. 
-Total Strokes
-Avg. Stroke Rate
-Max Stroke Rate
-Avg. Stroke Length would be nice too, but I don't know if that metric is available in Garmin

![QZ Rowing to Garmin ](https://user-images.githubusercontent.com/84399684/122153225-c63b1180-ce1f-11eb-9951-24b573fde666.png)

On the tiles, two things I noticed:

1. The pace is measured in m/km can that be changed to min/500m for rowing.  That is the common rowing pace metric?
2. Can the distance for rowing be shown in meters?

**Comment by cagnulein** [comment]
hi @mgarcea i did everything today. i guess the only thing that i'm unsure is Max Stroke Rate.
I only find MaxCadence on the fit file. So i don't know if you will see it correctly
You will see in the version 2.6.49
