### ISSUE TITLE
iFit Virtual Device

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#343]
i guess we should use the proform interface

![image](https://user-images.githubusercontent.com/48216/120888638-a9216a00-c5f9-11eb-8221-eebc8669e70d.png)
![image](https://user-images.githubusercontent.com/48216/120888643-afafe180-c5f9-11eb-97fb-71bb2569adb6.png)

**Comment by cagnulein** [comment]
https://www.ifit.com/blog/new-app-update

The app name will change from iFit Smart Cardio to “iFit—At Home Fitness Plans” on iOS and “iFit—Workouts at Home” on Android.

I'm waiting for confirmations

**Comment by cagnulein** [comment]
so it seems that with the new iFit version it works!

**Comment by cagnulein** [comment]
The new ifit version simple doesn’t look up for a device
@kadaan

**Comment by kadaan** [comment]
Correct, seems like we need to support Proform protocol in order for iFit to work.

**Comment by rtrice81** [comment]
Any update on support for an iFit virtual device?

**Comment by cagnulein** [comment]
not yet but it's one the next feature that i will develop :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 28 ago 2021 alle ore 19:02 Richie Trice <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
https://github.com/dawsontoth/zwifit

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/tree/ifit-virtualdevice

**Comment by cagnulein** [comment]
continuing the task here #441
