### ISSUE TITLE
Installing on MacOS - Requires xCode CLI

### ISSUE THREAD

**Issue by richardwait** [cagnulein/qdomyos-zwift#35]
For installing / running the project on MacOS

You will need to (at a minimum) to install the xcode Command Line Tools (CLI)
https://developer.apple.com/download/more/?=xcode

If you try and install without these prerequisites you will not be able to compile the project.

**Comment by cagnulein** [comment]
#31

**Comment by cagnulein** [comment]
thanks, reported into the readme!
