### ISSUE TITLE
Signals callbacks not found

### ISSUE THREAD

**Issue by lifof** [cagnulein/qdomyos-zwift#358]
@cagnulein  in bluetooth.cpp there are multiple connect functions ( at least 14 or so ) that don't have actual signal callbacks in code for example  :

`connect(this, SIGNAL(searchingStop()), cscBike, SLOT(searchingStop()));`

How do we deal with these.

N.B : these could've been hunted down at compile time or even when typing code if they were converted to [Qt5's New Signal Slot Syntax](https://wiki.qt.io/New_Signal_Slot_Syntax)

**Comment by cagnulein** [comment]
Yeah they are there future development. You can just comment them out.
Thanks

Il gio 10 giu 2021, 01:36 lifof ***@***.***> ha scritto:

**Comment by lifof** [comment]
Ok on it :+1:
