### ISSUE TITLE
[BUG] Power Zone Wattages Off Slightly

### ISSUE THREAD

**Issue by wbjenn** [cagnulein/qdomyos-zwift#374]
**Describe the bug**

Power Zone ranges in the app are off a little. Makes a bigger difference at higher FTPs (mine is 397). My Zone 1 should be 0-218 (or 217 based on how the forumla is viewed), but app shows 0-214. My Zone 2 is correct 218-298. Zone 3 should be 299-357, but the app shows 302-357. Interestingly, this 1% difference is enough to cause the app to show the Target Zone of 3.4 instead of 3.5. Zone 4 should be 358-417, but the app shows 361-417.

**To Reproduce**
Set a high FTP and you will see the deviation grow.

**Expected behavior**
Precise zones

**Screenshots**
Screenshot shows a Target Zone of 3.4 during a Power Zone ride.

**Smartphone (please complete the following information):**
Android v2.6.49

**Additional context**
Code for the zones should make sure there are no gaps. Z1 is 0%-55%; Z2 is Top Z1 +1 to 75%; Z3 is Top Z2 +1 to 90%; Z4 is Top Z3 + 1 to 105%; Z5 is Top Z4 + 1 to 120%; Z6 is Top Z5 + 1 to 150% ; Z7 is greater than Z6+1

**Comment by cagnulein** [comment]
Do you see this behavior only since i added a decimal point to the zone?

**Comment by wbjenn** [comment]
No, there has always been a small difference, but as my FTP has increased, so has the difference. The decimal isn't the cause. In the screenshot, you can see the Target Zone of 3.4 and the range for Z3 (302-357) and the range for Z4 (361-417).

![Screenshot_20210616-114615](https://user-images.githubusercontent.com/84189595/122272055-2082b380-ceae-11eb-8498-965f5b6c0528.jpg)

**Comment by wbjenn** [comment]
Also, the 11th tile is Target Power and it is correct at 328w based on what Z3 should be 299-357. Not sure how the calculation for the Target Power tile can be correct when the zones are wrong, but it is right.

**Comment by cagnulein** [comment]
Ok thanks, i will check this tomorrow

Il mer 16 giu 2021, 20:30 wbjenn ***@***.***> ha scritto:

**Comment by cagnulein** [comment]
done! it will be avaiable in the 2.6.51
