### ISSUE TITLE
Tacx Neo 2

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#388]
![1FB64E68-58A2-4E03-A7A5-79AB08E04AC7](https://user-images.githubusercontent.com/48216/123674152-93424600-d841-11eb-8db8-29151c01d863.jpeg)

**Comment by cagnulein** [comment]
[debug-Mon_Apr_26_14_17_44_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6731421/debug-Mon_Apr_26_14_17_44_2021.log)

**Comment by cagnulein** [comment]
[Uploading debug-Mon_Apr_26_14_17_21_2021.log…]()

**Comment by cagnulein** [comment]
[debug-Mon_Apr_26_14_17_21_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6732442/debug-Mon_Apr_26_14_17_21_2021.log)

**Comment by cagnulein** [comment]
![WhatsApp Image 2021-06-29 at 16 07 02](https://user-images.githubusercontent.com/48216/123812489-6c911780-d8f4-11eb-962f-af5b3e7c2aab.jpeg)
![WhatsApp Image 2021-06-29 at 16 06 21](https://user-images.githubusercontent.com/48216/123812496-6dc24480-d8f4-11eb-9b7c-303ab5286393.jpeg)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6736509/btsnoop_hci.log)

**Comment by cagnulein** [comment]
in order to set the resistance is necessary to use this https://github.com/GoldenCheetah/GoldenCheetah/blob/cabe078453cbe8e136b8adf8d4187a5be878671b/src/ANT/ANTMessage.cpp#L1127

**Comment by cagnulein** [comment]
https://github.com/abellono/tacx-ios-bluetooth-example/blob/master/How-to%20FE-C%20over%20BLE%20v1_0_0.pdf

**Comment by cagnulein** [comment]
[debug-Mon_Apr_26_16_17_20_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6739608/debug-Mon_Apr_26_16_17_20_2021.log)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6750457/btsnoop_hci.log)
erg mode on zwift

**Comment by cagnulein** [comment]
TACX smart bike
![image](https://user-images.githubusercontent.com/48216/142755209-e260647a-e0bf-42c3-bb0a-1d0be7fd32aa.png)

**Comment by cagnulein** [comment]
[debug-Mon_Apr_25_17_46_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8560485/debug-Mon_Apr_25_17_46_25_2022.log)
no peloton resistance 

originall posted frm @Jrw1982

**Comment by cagnulein** [comment]
[debug-Wed_Apr_27_14_55_23_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/8572809/debug-Wed_Apr_27_14_55_23_2022.log.zip)

> Hi Roberto
> 
> I've just tried this and the resistance now shows on the app but it doesn't seem to change on the bike, ie I can't feel pedalling getting harder or easier. 
> 
> It was only a quick test though so can try a full class later.
> 
> The target cadence from peloton also doesn't appear anymore? 
> 
> The debug log is attached.

**Comment by Jrw1982** [comment]
Hi

Cadence is now appearing (strange how it didn't initially) and resistance seems to work OK at higher levels but when it's low (20-30) on peloton it seems all over the place and sometimes far too easy. This is backed up by the resistance levels vs t.resistance as in screenshot. 
![Screenshot_20220427-165321](https://user-images.githubusercontent.com/104316078/165562637-f0cc8ed3-963e-47a2-bbce-ef18d3324859.jpg)


Also what do I need to do to make mph accurate as I no longer see this on bike screen to be able to calibrate it? 

Debug attached. 
[debug-Wed_Apr_27_16_51_07_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8573662/debug-Wed_Apr_27_16_51_07_2022.log)

**Comment by cagnulein** [comment]
@Jrw1982 thanks, for the resistance: when you're actually feeling the resistance? as i said now i translated peloton resistance to % hill grade / 10

so for example peloton resistance 50 is a 5% grade

what do you suggest? maybe the same with an offset of 5%

so at the peloton resistance 35 will be a 8.5% grade ?

for the speed: just tell me a couple of cadence and speed that you read on the tacx and i will tell you which cadence ratio you have to use

**Comment by Jrw1982** [comment]
> @Jrw1982 thanks, for the resistance: when you're actually feeling the resistance? as i said now i translated peloton resistance to % hill grade / 10
> 
> so for example peloton resistance 50 is a 5% grade
> 
> what do you suggest? maybe the same with an offset of 5%
> 
> so at the peloton resistance 35 will be a 8.5% grade ?
> 
> for the speed: just tell me a couple of cadence and speed that you read on the tacx and i will tell you which cadence ratio you have to use

OK that makes sense. Let me do a longer class to see. I know on that hill climb I tried it got a lot harder above 45 resistance on the peloton setting but at 25 to 30 it was fairly easy so I don't think it needs to be that extreme!

I'll have a look at speed and let you know the ratio difference we're running at. 

Thanks.

**Comment by cagnulein** [comment]
> I think the resistance is OK. There is sometimes a 10-20second delay or advance in the resistance and cadence changing in QS to what's on peloton but that's likely down to peloton being slow or fast with pushing the change out in the class.

yes you can trim it with the peloton offset tile, it's due to minilag to peloton server or wrong metrics on their servers ;)



> Re the speed. Here is a photo of my bike at 10mph and a screenshot of the app at the same speed. Hope this helps work out the offset required.

use 0.198 in the wheel ratio setting and disable the speed based on power setting. let me know

**Comment by Jrw1982** [comment]
Thanks, where is the peleton offset tile? 

Wheel ratio setting? I can't seem to see that, only this:

![Screenshot_20220430-155722](https://user-images.githubusercontent.com/104316078/166110722-534f5707-9836-46e7-98e9-6d0d5a93771e.jpg)

**Comment by cagnulein** [comment]
no, not that offset. leave it to 0.
the one in the cadence sensor section under accessories 
The peloton offset tile is under the section tiles
