### ISSUE TITLE
[REQ] Fast User Switching of Peloton Accounts

### ISSUE THREAD

**Issue by kadaan** [cagnulein/qdomyos-zwift#391]
**Is your feature request related to a problem? Please describe.**
Multiple people sharing one device with qdomyos-zwift must constantly change the Peloton username and password in settings.

**Describe the solution you'd like**
Support multiple profiles that can be easily switched between.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cagnulein** [comment]
@kadaan on Android i know there is the possibility to share the device with multiple accounts. Doesn't it possible with iOS too? I think it should be the natural solution :)

**Comment by kadaan** [comment]
As far as I know iOS is single user, unless apps build in support for switching profiles.

**Comment by cagnulein** [comment]
ah ok i didn't know. so probably the best way to fix this is to generate a profile as mentioned here #118 
what do you think?

**Comment by kadaan** [comment]
Works for me!

**Comment by cagnulein** [comment]
Ok i will close this as a duplicate for #118
