### ISSUE TITLE
[REQ] Schwinn IC4 Support Mapping Bike Resistance to Peloton Resistance

### ISSUE THREAD

**Issue by kadaan** [cagnulein/qdomyos-zwift#392]
**Is your feature request related to a problem? Please describe.**
When using a bike that cannot report resistance, Peloton resistance numbers are not representative of the bike resistance, and vice versa.

**Describe the solution you'd like**
As an option, support a mapping table of bike resistance to Peloton resistance.  If the Peloton resistance is not in the mapping table, interpolate between the surrounding values.  If the Peloton resistance is above the highest mapping table value, limit the result to the highest mapping table value.  If the Peloton resistance is below the lowest mapping table value, limit the result to the lowest mapping table value.

**Describe alternatives you've considered**
Currently we use a printed sheet, but it is much more labor intensive. 

![IMG_0002](https://user-images.githubusercontent.com/1904898/124558952-fdce2580-ddef-11eb-842a-114a8bce79c4.JPG)

**Additional context**
None

**Comment by cagnulein** [comment]
[schwinn.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/6769285/schwinn.xlsx)

**Comment by cagnulein** [comment]
done @kadaan
