### ISSUE TITLE
Xiaomi Kingsmith R1 Pro

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#409]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/6891325/btsnoop_hci.log)
![Screenshot_20210728-131219_nRF Connect](https://user-images.githubusercontent.com/48216/127286757-bfe7dc10-1ef9-4c5a-8836-bd4988d64c57.jpg)

**Comment by lamngocrang** [comment]
tôi bắt đầu bằng tốc độ 3km/h, sau đó tăng tốc liên tục lên 3.5km/h, 4km/h, 4.5km/h, 5km/h, 5.5km/h, 6km/h, 6.5km/h, 7km/h . Rồi dừng lại.

**Comment by cagnulein** [comment]
translated: i started at 3km/h, then continuously accelerated to 3.5km/h, 4km/h, 4.5km/h, 5km/h, 5.5km/h, 6km/h, 6.5km/h, 7km /H . Then stop.

@lamngocrang thanks!

**Comment by cagnulein** [comment]
just for reference for me:

f8 a2 01 23 0100000600000000000500000200d4fd

the byte 3 (0x23) is the speed multiplied by 10

@lamngocrang does this treadmill have also the inclination? did you move the inclination during this workout? which is the max speed of this treadmill? which is the max inclination?

**Comment by lamngocrang** [comment]
Máy chạy bộ của tôi không có độ nghiêng. Tốc độ thấp nhất là 2km/h, tốc độc cao nhất 10km/h

**Comment by cagnulein** [comment]
translation: My treadmill has no incline. The lowest speed is 2km/h, the highest speed is 10km/h

@lamngocrang ok thanks

**Comment by cagnulein** [comment]
@lamngocrang i've done. Did you already buy the app? i can add you to the beta channel in order to try this first version :)
