### ISSUE TITLE
Tooltip on the Settings

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#414]
in order to describe them

**Comment by Huhenyo** [comment]
I agree for this request.  Having some tool tips for each setting describing what it does or doesn't do would be very helpful to new users.  I would be happy to assist with refining the English verbiage if needed to help it be clear to a new user as I am still one.  :)  

I'm thinking a little question mark with a circle around it next to each setting which could be clicked on to see the tool tip would work great, but I don't know if that is something that can be programmed into the app.  

Thank you!

**Comment by cagnulein** [comment]
yes i guess that could be the right way to proceed, i will experiment a little about this! Thanks @Huhenyo for the feedback!

**Comment by cagnulein** [comment]
done!
