### ISSUE TITLE
Tiles no longer come up and says connecting

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#422]
[debug-Mon_Aug_9_05_23_01_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6952287/debug-Mon_Aug_9_05_23_01_2021.log)
[debug-Mon_Aug_9_05_20_23_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6952288/debug-Mon_Aug_9_05_20_23_2021.log)

This is on the Pi. It used to intermittently connect and I assumed it was dodgy Raspberry bluetooth. Now it connects, the elliptical beeps and starts a program, but QZ doesn't show the tiles and still says connecting...
The Android version works (not running when trying the Pi, which I tried first)

Do these logs shed any light?

Thanks,
Jonathan

**Comment by cagnulein** [comment]
i don't see disconnection here...maybe attach some longer logs when the
problem happens, for example, twice.
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 9 ago 2021 alle ore 07:29 jonathancolledge <
***@***.***> ha scritto:

**Comment by jonathancolledge** [comment]
[debug-Mon_Aug_9_12_17_38_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6954480/debug-Mon_Aug_9_12_17_38_2021.log)\

It doesn't disconnect, more like never fully connects. I rebuilt it. I tried a bluetooth dongle. It starts the program on the elliptical, but stays as in the image attached 
![IMG_20210809_131929](https://user-images.githubusercontent.com/4342400/128705820-ed402e9d-7c58-4cc5-8d91-c7f92b4af338.jpg)

**Comment by cagnulein** [comment]
@jonathancolledge hah ok i understood now, try to put a 

deviceConnected();

after the line 284 of the homeform.cpp. the linux blueooth cache doing this i noticed

**Comment by jonathancolledge** [comment]
[debug-Mon_Aug_9_14_26_05_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6955145/debug-Mon_Aug_9_14_26_05_2021.log)

It got cross with that! It didn't start. I hope this is the right log.

**Comment by cagnulein** [comment]
No i don't see nothing here :(
did you try also to restart the bluetooth daemon on the raspberry pi?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 9 ago 2021 alle ore 16:29 jonathancolledge <
***@***.***> ha scritto:

**Comment by jonathancolledge** [comment]
Oh, wait. It worked! Ignore that last one.

**Comment by jonathancolledge** [comment]
So it is working now - I just restarted. But Zwift incline doesn't change anything in running mode. (Also, no cadence found by Zwift in pairing mode (I noticed it didn't send that before - is it possible to send?)

The attached log has lots of flat till the end when the Zwift incline goes up to 4%

[debug-Mon_Aug_9_14_34_31_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6955359/debug-Mon_Aug_9_14_34_31_2021.log)

**Comment by cagnulein** [comment]
Yeah i saw that not everytime Zwift is sending inclination. I guess it send them only if you came from a cycling activity before the treadmill one..for the cadence there is already a ticket opened #195
