### ISSUE TITLE
Elite Rizer compatibility

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#424]
Hi Roberto,

Might you be interested in supporting this: https://www.elite-it.com/en/products/home-trainers/ecosystem-accessories/rizer

When paired with an Elite trainer, there is nothing for QZ to do as gradient gets sent to the Rizer from Elite trainers. But it is sort of compatible with other trainers like Wahoo and Tacx - for these non-Elite trainers, the Rizer calculates gradient by cadence and power, or speed, or something. But, Elite say that they allow for gradient to be sent to the device if the other device manufacturer wants to send it (I don't know what protocol, but they say it is an open standard). QZ could send gradient, so it'd be accurate instead of estimated!

In my case that would be QZ linking to Wahoo Kickr (uses a sort-of proprietary Bluetooth FTMS) and then sending gradient from that to the Elite Rizer.

The reason I ask is because my Kickr Climb has died and I could buy the Elite instead. I could copy you in to an email to the people at Elite if you are interested. Feel free to say "too niche" though!
Best wishes,

Jonathan

**Comment by cagnulein** [comment]
absolutely interested! put me in copy and let's see what could i do :)

**Comment by cagnulein** [comment]
done!
