### ISSUE TITLE
[REQ] Random function Speed Min and Max one more digit

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#425]
**Is your feature request related to a problem? Please describe.**
I use the treatmill for walking sometimes in stead of running. Putting it on Min = 4 and Max = 5 gives me only slow walks. Putting it on Max = 6 gives me too fast for walking speeds.

**Describe the solution you'd like**
It would be nice to be able to put Min = 4.5 and Max = 5.5 For running whole numbers are just fine.

**Describe alternatives you've considered**
I give the inclination a wider range so the differences between 4 and 5 increase in the way they feel.

**Comment by cagnulein** [comment]
are you sure this is not possible yet? i guess it's already a float. maybe
it's missing just the decimal point in the keyboard but if you copy and
past the value it should work

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 ago 2021 alle ore 20:01 ErnieV ***@***.***>
ha scritto:

**Comment by ErnieV** [comment]
I'll try it and let you know.
Isn't there a setting that lets the iPhone know decimals are allowed in the field?

No decimal symbol:
![IMG_1A26BCAAE272-1](https://user-images.githubusercontent.com/20909110/130732702-f511d94c-2af6-4eff-b6fd-545ae2786558.jpeg)

Copy/pasting it in seems to work:
![IMG_059DAC4B3B00-1](https://user-images.githubusercontent.com/20909110/130732854-4ea6e54a-0f88-4657-a3d2-28d6400e28b0.jpeg)

I'll try it on the machine to see if it actually works.

**Comment by cagnulein** [comment]
fixed :)
