### ISSUE TITLE
[REQ] HR Zone PID target buttons

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#426]
**Is your feature request related to a problem? Please describe.**
I notice that, while I’m running, I go in to the menu and find the different targets and change them. It would be easier if I could change the target zone on the primary screen.

**Describe the solution you'd like**
Buttons 1 - 5 on top of the tiles to activate the desired HR zone. Maybe the buttons should only be visible when PID function is enabled.

**Describe alternatives you've considered**
An alternative could be to have a tile that shows the active HR zone for PID and a + and - symbol to go up and down. Just like the Speed and Inclination tiles.

**Comment by cagnulein** [comment]
i like this!
a new tile is the best solution

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 ago 2021 alle ore 20:06 ErnieV ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
[#](https://github.com/cagnulein/qdomyos-zwift/issues/565) done! @ErnieV
