### ISSUE TITLE
[REQ] Export the result graphs

### ISSUE THREAD

**Issue by ErnieV** [cagnulein/qdomyos-zwift#428]
**Is your feature request related to a problem? Please describe.**
I think the emails that are send after each workout are a very nice feature. Would it be difficult to include the visual graphs that are shown after each run?

**Comment by cagnulein** [comment]
they are already as attachments, don't you see them?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 24 ago 2021 alle ore 20:16 ErnieV ***@***.***>
ha scritto:

**Comment by ErnieV** [comment]
Oh yes, on my Mac I see them now. Also the .fit file.
On my iPhone there is a very small clip to indicate there could be an attachment but I cannot open / view them.

I'll look into that, strange.
