### ISSUE TITLE
Auto or Manual Resistance for Domyos Elliptical

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#432]
### Discussed in https://github.com/cagnulein/qdomyos-zwift/discussions/431

<div type='discussions-op-text'>

<sup>Originally posted by **eko136** August 28, 2021</sup>
Hi, there.
Thank you for creating this qDomyos, I managed to do Zwifting with my existing Domyos elliptical trainer.

This may have been discussed in the previous posts, is there any future development to make the auto resistance for Domyos elliptical trainer. I know this is challenging to associate the resistance in Zwift with the resistance scaling in various elliptical trainers.

Or, is there any development to enable the manual resistance buttons on the trainer to work to control the resistance?
Currently, if I want to change the resistance manually, I have to do it with my bridge phone and it is really difficult pressing them in the phone while I am running.

Thank you again for making this happen.

Best regards,

Eko</div>

@eko136

Done!

**Comment by cagnulein** [comment]
@eko136 done! it will be in the next beta!

**Comment by thibaultmol** [comment]
Should this be updated then?
https://github.com/cagnulein/qdomyos-zwift/wiki/Equipment-Compatibility

**Comment by cagnulein** [comment]
Yes if it works you can edit yourself @thibaultmol 
Thanks

**Comment by cagnulein** [comment]
@eko136 which model do you have? so we can add it in the table.
Thanks @thibaultmol
