### ISSUE TITLE
CONSTEST: How long is your longest session on qdomyos-zwift?

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#44]
I had this idea during my LL today. For the first time, i ran for 1h 40m on my treadmill with my qdomyos-zwift on my raspberry pi0w! I guess the raspy was more sweaty than me 😆 

So i had this idea: why don't create a report ticket in order to collect our longest session. In this way we could keep tracking about uptime issues on new commits.

I used for this session commit https://github.com/cagnulein/qdomyos-zwift/commit/53e25c85921fe560708b4ac79b917042442b1fc7

Enjoy your ride!

ZWIFT Link: https://www.zwift.com/athlete/8cae4391-9f2a-4627-96e3-b55cebc17a02

![Screenshot_20201102_154237_com strava](https://user-images.githubusercontent.com/48216/97886658-282f8680-1d29-11eb-8ca1-cf337bdc73c5.jpg)

**Comment by firetrappe** [comment]
Cool idea!
My longest run to date is 1 hour and I only covered 6.6km!
I only started running in May and cycling this month. I have some catching up to do haha
Very happy to help collect data though.

**Comment by kenands** [comment]
My longest session :smile: :

![Screenshot_2020-11-05-22-29-01-478_com zwift android prod](https://user-images.githubusercontent.com/16349940/98304371-259a8e80-1fc0-11eb-88bc-2c8259e4adc2.jpg)

**Comment by cagnulein** [comment]
![strava8375336006001527622.jpg](https://user-images.githubusercontent.com/48216/98405387-7bc50b80-206c-11eb-850a-a46a54b98660.jpg)

@rickoneeleven is it enough for you? :D

**Comment by rickoneeleven** [comment]
Wow beautiful man!

**Comment by drmason789** [comment]
![image](https://user-images.githubusercontent.com/29954900/204946008-94af9d61-5b43-4335-bad2-1a70b463272d.png)

Contest

Whether or not you fix this, please feel free to delete this message. :-)

**Comment by cagnulein** [comment]
ops thanks @drmason789
