### ISSUE TITLE
[REQ] Add Support for Bikes when importing GPX Files

### ISSUE THREAD

**Issue by Bepo7012** [cagnulein/qdomyos-zwift#454]
Please add Support for automatically setting Bikes Resistance based on imported GPX Files. Would be nice, if a "Resistance Offset" could be added to for "simulating" some Kind of E-Bike Support.

**Comment by cagnulein** [comment]
Yea I will check tomorrow if it's not yet implemented. If not it should be easy to add it :)

**Comment by Bepo7012** [comment]
Works perfectly like excepted.
