### ISSUE TITLE
Nautilus T628 Treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#458]
![246230458_3010450672526542_91969530977160730_n](https://user-images.githubusercontent.com/48216/137882303-458acd96-c4ba-41e2-b47f-bedd7814b22f.jpeg)
The app is called explore the world (by Bowflex)

**Comment by Klaffys** [comment]
I created two as I think the first one didn't work properly. hopefiully this has what you need.

[bugreport-oriole-SQ1D.211205.016.A4-2021-12-27-14-56-51.zip](https://github.com/cagnulein/qdomyos-zwift/files/7780877/bugreport-oriole-SQ1D.211205.016.A4-2021-12-27-14-56-51.zip)
[bugreport-oriole-SQ1D.211205.016.A4-2021-12-27-15-10-06.zip](https://github.com/cagnulein/qdomyos-zwift/files/7780878/bugreport-oriole-SQ1D.211205.016.A4-2021-12-27-15-10-06.zip)
