### ISSUE TITLE
VIDEO/PHOTO of your setups

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#46]
I would like to create a short Youtube video in order to describe quickly the project.
I guess it should be useful and funny if i will add some of your videos playing with qdomyos-zwift.

So feel free to put here anything releated to your setup, even video files.

Thanks

**Comment by kenands** [comment]
Here is my temporary setup, I will improve it 😄

_ raspberry pi4 for the bridge.
_ Windows 10 laptop for zwift and remote the raspberry
_ Tv 
_ domyos bike 500

![IMG_20201105_220010](https://user-images.githubusercontent.com/16349940/98338319-50113980-200a-11eb-84ac-8f6b964e6f57.jpg)
![IMG_20201105_211840](https://user-images.githubusercontent.com/16349940/98338321-51426680-200a-11eb-9f8c-816e0ac1b0ea.jpg)
![IMG_20201105_211826](https://user-images.githubusercontent.com/16349940/98338322-51426680-200a-11eb-95cf-ea086cf9c103.jpg)

**Comment by czuczorf** [comment]
@kenands Nice setup! Sorry to ask it here, I am thinking about to buy Domyos 500 as a hobby cyclist (3-4000km-40000elevation/year) for the winter months. What do you think, is this device capable to keep me fit, and also increase my power?

I've seen there is a direct? bridge through PC (ProH4Ck/treadmill-bridge), is there a real need for Raspberry? 
Thanks!

Hopefully soon I can also post photos here ;-)

**Comment by cagnulein** [comment]
@czuczorf all bridges, (ProH4Ck/treadmill-bridge) and qdomyos-zwift, need 2 devices: 1 for the bridge and 1 for zwift.
Qdomyos-zwift can run on raspberry (all Linux devices), pc or Mac. I will release an android version too.
So we will waiting for you in our beautiful debug team :D

**Comment by czuczorf** [comment]
@cagnulein Thanks, I see! Android would be nice, so my phone can be the bridge and the PC can play the Zwift app.
Is there a two directional communication/controll, I mean if there is a hill in strava will be the pedal harder to push?

**Comment by kenands** [comment]
@czuczorf thanks 😄 
For me domyos bike 500 it's a good indoor bike, 
it's quite and confortable.
But the position and feeling it's not really as a real bike or a spinning bike, for exemple you can not train standing on the pedals.
But i think it's enough to keep fit and increase power mostly with training programs on zwift.
And thanks to @cagnulein nearly all features work with zwift 😄 and soon all will work.

**Comment by cagnulein** [comment]
> @cagnulein Thanks, I see! Android would be nice, so my phone can be the bridge and the PC can play the Zwift app.
> Is there a two directional communication/controll, I mean if there is a hill in strava will be the pedal harder to push?

now is monodirectional, but i'm adding the writing of resistance from zwift. it just matters of days

**Comment by czuczorf** [comment]
@cagnulein @kenands Thank you guys for your kind help! This looks really promising and adds a huge amount of extra to Domyos devices! Keep up the good work! Of course, I will help you debug! 
Now I have to go to the Decathlon ;-)

**Comment by RhysOnlyBetter** [comment]
My setup:
- Echelon Sport Connect
- 2015 Macbook
- Oculus Quest 2
- Holofit App
![PXL_20201220_164215727](https://user-images.githubusercontent.com/4860207/102718925-4a716980-42c1-11eb-9559-afcaa72adfba.jpg)

Went for my first VR ride this morning, the bridge worked great with the Quest 2! Thanks for all your hard work :)

**Comment by cagnulein** [comment]
@RhysOnlyBetter wonderful! so you can use zwift with the oculus?

**Comment by RhysOnlyBetter** [comment]
I don't think there's a zwift app for Oculus yet, but there are 2 similar apps; Holofit and VZFit Play. I tried out Holofit and it worked great, VZFit I was able to connect the bridge, but had trouble registering the app, so wasn't able to try it out fully.

**Comment by cagnulein** [comment]
@RhysOnlyBetter you have to definitely record a video of these :D

**Comment by blancmunier** [comment]
Hi @RhysOnlyBetter ,
When the qdomyos bridge works for zwift, will it then work with holodia as well?

**Comment by elfonashelfna** [comment]
![IMG_2462](https://github.com/cagnulein/qdomyos-zwift/assets/154609763/a819cf02-a862-4d21-bbfe-21c8944224f6)
