### ISSUE TITLE
[REQ] Add setting to calculate watts from polynomial curve equations

### ISSUE THREAD

**Issue by Jonseed** [cagnulein/qdomyos-zwift#461]
Some bikes (or other fitness equipment) use lookup tables to calculate watts based on cadence and resistance, but this can be problematic because there can be limits to the table. My bike, for example, is a ProForm TDF CBC, which limits wattage reported at 90+ cadence (no matter how fast I pedal, the watts stay the same over 90 cadence). This is especially problematic during sprints. It's a poor built-in lookup table in the bike's firmware.

A solution would be if QZ had a setting which used polynomial curve equations for each resistance level to calculate the wattage from the current cadence value. Then no matter what the cadence is, accurate wattage can be reported. For example, on my ProForm TDF CBC bike, here are the equations for the resistance levels 1-16 to generate the watts value. The x value is the cadence:

resistance 1: -13.5 + 0.999x + 0.00993x²
resistance 2: -17.7 + 1.2x + 0.0116x²
resistance 3: -17.5 + 1.24x + 0.014x²
resistance 4: -20.9 + 1.43x + 0.016x²
resistance 5: -27.9 + 1.75x+0.0172x²
resistance 6: -26.7 + 1.9x + 0.0201x²
resistance 7: -33.5 + 2.23x + 0.0225x²
resistance 8: -36.5 + 2.5x + 0.0262x²
resistance 9: -38 + 2.62x + 0.0305x²
resistance 10: -41.2 + 2.85x + 0.0327x²
resistance 11: -43.4 + 3.01x + 0.0359x²
resistance 12: -46.8 + 3.23x + 0.0364x²
resistance 13: -49 + 3.39x + 0.0371x²
resistance 14: -53.4 + 3.55x + 0.0383x²
resistance 15: -49.9 + 3.37x + 0.0429x²
resistance 16: -47.1 + 3.25x + 0.0464x²

These equations were found by collecting several data points on the bike (cadence and resistance = wattage), and then using a spreadsheet to draw a polynomial trendline to fit the curve, and generate the equation for that curve. Each resistance level has a different curve equation:

![chart2](https://user-images.githubusercontent.com/40897189/137988617-b721a1fa-830e-4406-8482-df6dc7dd20c3.png)

An alternative solution would be a better lookup table for the equipment, with values at more cadences defined, but to be as accurate as the equations it would have to have watts defined at every cadence increment, which is very cumbersome to collect. One could use the equations to generate such a comprehensive table, but then why not just use the equations directly (unless a lookup table is still needed for functions like ERG mode).

Of course, such a solution is still dependent on the watt curves in the equipment's firmware accurately reporting power, which most are not. But it is a fine approximation, and the existing "watt gain" and "watt offset" settings in QZ can be used to adjust the watts to more realistic levels if necessary. Also, unfortunately, each equipment would need its own unique curve equations. The fallback of such a setting, if there are no equations present for particular equipment is to use the existing table or other methods to calculate watts.

**Comment by cagnulein** [comment]
@Jonseed done! i added a new setting in the proform section of the QZ settings called "TDF CBC Jonseed Watt table" enable it in order to use your table instead.
Let me know if it suits for you. In case you can close this :)
The version with this feature will be the 2.8.85 or above

**Comment by Jonseed** [comment]
@cagnulein ok, great! I look forward to trying it!
