### ISSUE TITLE
[REQ] Peloton Auto Resistance countdown change tile

### ISSUE THREAD

**Issue by sk8ersquare** [cagnulein/qdomyos-zwift#467]
**Is your feature request related to a problem? Please describe.**
Current problem is I need to spend most of the start of my ride tweaking the peloton offset to ensure my resistance changes with the trainer. Sometimes - I don't know if its 20-30 seconds out !

**Describe the solution you'd like**
A tile which shows a countdown to the next change and what the value is going to be - so you can tweak your offset accordingly to align with the video stream.

**Additional context**
You can add an additional function to this tile that when you tap it - it immediately changes the peloton offset to match.

ie. 
1. on the video stream the coach says ... "changing to 45 in 3...2....1... GO"
2. this new 'peloton change countdown' tile was displaying "10 seconds to change to 45.." (therefore it's 10 seconds out from the actual stream)
3. you tap this new tile 
4. your 'peloton offset' tile immediately changes to 10 seconds
5. you're now perfectly in sync!

this is perfect if you stop/ start the workout too to get back in sync.

**Comment by cagnulein** [comment]
I guess the auto sync new setting and also the peloton remaining time tile could be perfect for this! In case let me know!
