### ISSUE TITLE
Autostart qdomyos-bridge on Raspberry Pi boot.

### ISSUE THREAD

**Issue by firetrappe** [cagnulein/qdomyos-zwift#47]
Have any of you using a Pi managed to get the bridge to work automatically at boot? I managed it once briefly by modifying the /etc/xdg/lxsession/LXDE-pi/autostart script. The bridge ran briefly and then disappeared. No logs were created I could check.
I think (guessing) it could be a root issue and I need to use a bash script?

**Comment by cagnulein** [comment]
@firetrappe try to start the executable with

`sudo ./qdomyos-zwift 2> /tmp/error.txt`

in this way you can collect any error to /tmp/error.txt file

**Comment by firetrappe** [comment]
@cagnulein Thanks. I'm at work right now, but from memory my autostart script looked like this -

```
@lxpanel --profile LXDE
@pcmanfm --desktop --profile LXDE
@lxterminal -e /qdomyos-zwift/src/qdomyos_zwift
@xscreensaver -no-splash@
```

**Comment by rickoneeleven** [comment]
ohhhhh yeah, i've not even tried this but I was thinking about it earlier, was thinking the same. maybe a crontab shell script that checks each minute to see if it's running and starts it if not - could use ps or something like that to see if it's running.

i use "supervisor" https://linoxide.com/linux-how-to/supervisor-monitor-linux-servers-processes/ for some queue management process on laravel, may even look into that if needs be. first things first, i want to get it working well at home (got some testing scheduled tonight) and once that's out the way look into this.

**Comment by firetrappe** [comment]
@rickoneeleven Thanks for the ideas. Totally above my skills, but i'm getting more exercise running up and down stairs at the moment than on the bike and treadmill ;)

**Comment by rickoneeleven** [comment]
it all counts :D

**Comment by cagnulein** [comment]
@firetrappe you could do a thing like this

`@lxterminal -e /qdomyos-zwift/src/qdomyos_zwift 2> /tmp/error.txt`

**Comment by cagnulein** [comment]
@firetrappe did you manage it?

**Comment by firetrappe** [comment]
@cagnulein I briefly tested adding your code line to my autostart script. The Pi rebooted to desktop and opened an empty text window called 'qdomyos-zwift'. No error.txt log was created.

**Comment by firetrappe** [comment]
@cagnulein I have now managed to figure out the autostart - at least one way that works so far.

I did the following..

`mkdir /home/pi/.config/autostart`

`sudo nano ~/.config/autostart/qdomyos.desktop`

```
[Desktop Entry]
Type=Application
Name=qdomyos-zwift
Exec=lxterminal -e bash -c 'sudo /home/pi/qdomyos-zwift/src/qdomyos-zwift;$SHELL'
Terminal=true
```
`sudo chmod a+r ~/.config/autostart/qdomyos.desktop`

`sudo reboot`

The `$SHELL` keeps the terminal window open if there is a SegFault etc.

**Comment by cagnulein** [comment]
@firetrappe close this when you're confident, thanks
