### ISSUE TITLE
[REQ] Domyos Bike - disable HR reporting

### ISSUE THREAD

**Issue by superandrew** [cagnulein/qdomyos-zwift#480]
**Is your feature request related to a problem? Please describe.**
It would be very nice to be able to disable HR reporting from Domyos Bike, avoiding interference between the data reported by the equipment when using Apple Watch

**Describe the solution you'd like**
As provided in other type of equipments, we could add a setting to disable HR reporting from Domyos Bike

Maybe there are other data reporte by the bike that could be disabled, not sure about it

**Comment by cagnulein** [comment]
done. It will be in the version 2.8.105
