### ISSUE TITLE
[BUG] Improperly reported / intermittent metrics on Domyos Bike

### ISSUE THREAD

**Issue by superandrew** [cagnulein/qdomyos-zwift#481]
**Describe the bug**
When running on a Domyos Bike, the distance and calories settings aren't properly reported

**To Reproduce**
1. Launch a training session with Zwift 
2. If you take a look at the bike equipment, the distance flashes with wrong values intermittently. So does calories

**Expected behavior**
It would be very cool if those settings, amongs the others such as HR, would be reported directly using the data provided by QZ

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOs 14+ (not relevant)
 - Version: last beta

**Smartphone (please complete the following information):**

**Comment by cagnulein** [comment]
as i said i need a help from you on this :)

**Comment by cagnulein** [comment]
i'm closing this one. The fix should be in the 2.8.137
In case it didn't, i will reopen this

**Comment by superandrew** [comment]
The metrics reported by the domyos seem to be mapped almost correctly, however these issues remain:

1. Calories are correct, but need to be multiplied x 10
2. Km are ok.
3. Km/h are correct but need to be multiplied x 10.
4. The alternance between Km and Km/h should be a few second per data. Right now its (more or less)
Km: 1/10 of a second 
Km/h: 9/10 of a second
I'd say that apart from this, data is Ok.

**Comment by superandrew** [comment]
Attaching a debug log in order to better investigating the issue

[debug-dom_dic_19_16_58_09_2021.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/7755686/debug-dom_dic_19_16_58_09_2021.log.zip)

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/147259326-a61028cd-604b-4eb7-b009-2fa90ef9baa9.png)

**Comment by superandrew** [comment]
when km/h overcome the limit of 25.5 the km/h his stops reporting the correct metrics

**Comment by cagnulein** [comment]
@superandrew are we ok with this now?

**Comment by superandrew** [comment]
yes @cagnulein everything is perfect.

**Comment by superandrew** [comment]
the problem seems to be present again on a newly installed app.

https://user-images.githubusercontent.com/71364/204100088-a43563fd-e980-4697-a240-daa6776d27bf.MOV

**Comment by cagnulein** [comment]
@superandrew the issue was about the switch fix calories/km to the console. did you try both ways?

**Comment by superandrew** [comment]
@cagnulein the calories are correct. It seems that km and km/h blink at a 1/10 and 9/10 seconds respectively though, not sure why because before reinstalling the app they worked properly

**Comment by cagnulein** [comment]
yes but that switch is releated to both, so try with and the without it and remember to restart the app after each modifications

**Comment by superandrew** [comment]
hi @cagnulein i tried and, with the setting disabled, the display is wrong in terms of scale. With the switch on, the values are correct. However this doesn't change the blinking behavior.

Km stays on for a flash, km/h for about 1.2 seconds.
