### ISSUE TITLE
Reebok GT50 Treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#485]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7481287/btsnoop_hci.log)

**Comment by cagnulein** [comment]
![Screenshot_20211104-070836](https://user-images.githubusercontent.com/48216/140473797-cd4d8660-8abb-4f5b-ab9b-73e5af82de08.png)

**Comment by cagnulein** [comment]
[debug.txt](https://github.com/cagnulein/qdomyos-zwift/files/7496196/debug.txt)

**Comment by cagnulein** [comment]
Relativamente al tapis, questo è stato il comportamento:

- avviato QZ che si è connessa correttamente
- alla connessione il tapis ha emesso un beep ed ha mostrato sul display la notifica di connessione BT
- Qz ha impostato la velocità a 1km/h , it tapis ha emesso un beep ma è rimasto fermo
- dopo 1 min e 10s ho fatto partire il tapis manualmente col tasto sulla console, e QZ ha impostato la velocità a 2km/h
- dopo un min dall'avvio il tapis ha modificato la velocità (o l'ha fatto QZ?)
- dopo un altro minuto, ancora, il tapis ha modificato la velocità
[Reebok-debug-Mon_Nov_8_13_13_12_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/7497187/Reebok-debug-Mon_Nov_8_13_13_12_2021.log)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7497424/btsnoop_hci.log)
ho avviato l'app, che si è connessa al tapis, ho selezionato allenamento libero, quindi ho fatto partire il tapis con il pulsante sulla console della macchina.
Ho lasciato girare senza toccare nulla, quindi ho premuto stop sulla macchina per terminare l'allenamento.
L'app non permette di comandare il tapis ma chiede di usare i comandi sulla console... non credo sia un limite tecnico, perchè con i programmi dell'app riesce a variare velocità ed inclinazione.
ho anche usato il sensore cardio incorporato nella macchina.


[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7497432/btsnoop_hci.log)
ho avviato l'app, che si è connessa al tapis, ho selezionato un programma quindi ho fatto partire il tapis con il pulsante sulla console della macchina.
Il programma è andato per circa 4 minuti variando inclinazione o velocità ogni minuto, quindi ho premuto stop sulla macchina per terminare.
Il treadmill ha 15 livelli di inclinazione che variano a step di 1, ed arriva a 18km/h a step di 0.1

**Comment by pasor1** [comment]
​Temo che in effetti l'app non cambi i valori in tempo reale bensì li prefissi dall'inizio​.
Infatti in nessun modo si possono variare velocità ed inclinazione dall'app nativa, viene sempre chiesto di farlo dalla console della macchina.
Nell'app c'e' anche una modalità che permette di impostare un percorso su google maps, quindi il tapis la esegue modificando l'inclinazione se la strada è in salita.
Però anche in questa modalità mi vien da pensare che i settaggi vengano impostati all' init... infatti modificando la velocità, l' inclinazione impostata va facilmente fuori sync con la strada seguita.

**Comment by cagnulein** [comment]
va bè dai poco male @pasor1 , almeno con questa patch dovresti poter essere abile di entrare su zwift. Compilo ora e te lo troverai fra poco sul play store. Tienimi aggiornato su #486  (sinceramente non ho molte idee fino a che non riusciamo a connetterci correttamente)

**Comment by cagnulein** [comment]
@pasor1 I'm closing this one because another user confirms that it's ok with your treadmill. Feel free to open it back in case
