### ISSUE TITLE
Zwift on Windows 10 doesn't seems to see the bridge

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#49]
@kenands 
Lenovo x230 for zwift
Zwift on my laptop doesn't see bluetooth from the bridge that's why I used zwift companion for the connection.

_Originally posted by @kenands in https://github.com/cagnulein/qdomyos-zwift/issues/22#issuecomment-721756085_

**Comment by kenands** [comment]
@cagnulein yes it's on windows 10.
On Windows 10 bluetooth configuration, I see the bridge but on zwift it doesn't appaer. 
I did few searches on google and it seems to be related to a windows issue.
In this topic, lot of people have the same issue:
https://forums.zwift.com/t/windows-10-and-bluetooth-connection-issues/105504/21

I will try with updating w10 and installing
vc_redistx64.exe

**Comment by kenands** [comment]
@cagnulein it works with vc_redistx64.exe installed :smile:

**Comment by cagnulein** [comment]
Great! Thank you for sharing!
