### ISSUE TITLE
[REQ] Hertz XR-770 spinning bike

### ISSUE THREAD

**Issue by JQu80** [cagnulein/qdomyos-zwift#494]
Hi,

I am attaching the BT communication log between the iConsole+ application and the Hertz XR-770 bike.
The sequence of my actions:

- start - resistance 1
- speed 20-25
- increasing the resistance to 10
- speed 30
- reduction of resistance to 5
- pause
- resume - resistance 1
- resistance at 5
- stop

[btsnoop_hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/7528589/btsnoop_hci.zip)

**Comment by cagnulein** [comment]
Hi @JQu80 ! Thanks!
I don't remember: did you already try the beta in order to check if the compatibility with your bike is already there?

**Comment by JQu80** [comment]
> 
> 
> Hi @JQu80 ! Thanks! I don't remember: did you already try the beta in order to check if the compatibility with your bike is already there?

Yes. Nothing worked.

**Comment by cagnulein** [comment]
Ok already see the differences! i will implement this this weekend. I will send you a new beta soon!
have a nice weekend!

**Comment by cagnulein** [comment]
Busy weekend. I will check this tomorrow

**Comment by cagnulein** [comment]
@JQu80 done i will send you the version later today
