### ISSUE TITLE
[BUG] Hertz XR-770 spinning bike - did not work

### ISSUE THREAD

**Issue by JQu80** [cagnulein/qdomyos-zwift#497]
I turned on the option for the bike but QZ communication still does not work. When I turn on the iConsole app, the bike display immediately goes blank. This does not happen with QZ. The bike display is still active. I think that as part of the bluetooth connection there must be some logical exchange of messages before the bike turns off the display end starts transmitting parameters over bluetooth.

[debug-pon--lis-15-19-57-43-2021.zip](https://github.com/cagnulein/qdomyos-zwift/files/7541110/debug-pon--lis-15-19-57-43-2021.zip)

**Comment by cagnulein** [comment]
#494

**Comment by cagnulein** [comment]
Got it, it just a stupid thing. I will fix it tomorrow

**Comment by cagnulein** [comment]
Enable the toorx bike setting as well

**Comment by JQu80** [comment]
I confirm. Enabling both options made the QZ app work with the bike.

**Comment by cagnulein** [comment]
ok great! so we can close this @JQu80 ?

**Comment by JQu80** [comment]
Basically yes. But having to enable both options, which appears independent, will be confusing for future users. It is not intuitive,

**Comment by cagnulein** [comment]
yeah you're right, leave this open so it will remind me to fix this thing
thanks for your feedback

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 nov 2021 alle ore 19:30 JQu80 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@JQu80 did it! it will be in the version 2.8.116
