### ISSUE TITLE
Zwift and Strava accounts

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#50]
Just to create a little sense of community here, let's share our zwift and strava accounts

These are mine:
Zwift: Roberto Viola-8556 https://zwift.com/athlete/8cae4391-9f2a-4627-96e3-b55cebc17a02
Strava: https://www.strava.com/athletes/2839759

We could also create a Zwift team 👍

**Comment by rickoneeleven** [comment]
https://www.strava.com/athletes/43508755
https://www.zwift.com/athlete/6cd84fef-8433-41cc-a9dc-c61a98aacd8a?__znl=en-gb Ryan Partington (it looks like im naked, im not)

**Comment by cagnulein** [comment]
> https://www.strava.com/athletes/43508755
> https://www.zwift.com/athlete/6cd84fef-8433-41cc-a9dc-c61a98aacd8a?__znl=en-gb Ryan Partington (it looks like im naked, im not) ...or am i

are you a '83 too? Very good year :D

**Comment by rickoneeleven** [comment]
like a fine whiskey my friend

**Comment by firetrappe** [comment]
Cool idea! Here's mine....

Zwift: Si Mills [https://zwift.com/athlete/3f1162bf-f8c0-41d4-accd-d5dd83842136?__znl=en-gb](url) Still in free trial.
Strava: https://www.strava.com/athletes/58124544

**Comment by kenands** [comment]
Good idea 😄 
My zwift account:
https://zwift.com/athlete/3123c2ba-d0f7-4ee6-92cf-7c3535eb755d
I don't have strava account.

**Comment by cagnulein** [comment]
> I don't have strava account.

BAD BAD BAD! 😆 
how could you train wihout strava? "if it's not on strava it didn't happen" 🤣

**Comment by kenands** [comment]
> > I don't have strava account.
> 
> BAD BAD BAD! 😆
> how could you train wihout strava? "if it's not on strava it didn't happen" 🤣

Haha until now I used addidas app (old runtastic). I will try strava lol

**Comment by cagnulein** [comment]
@rickoneeleven btw is this site https://pinescore.com/ yours?

**Comment by cagnulein** [comment]
guys I created a facebook group about Domyos stuff https://www.facebook.com/groups/1064761680643892

**Comment by rickoneeleven** [comment]
i don't have facebook unfortunately, just an onlyfans :laughing:

**Comment by cagnulein** [comment]
> i don't have facebook unfortunately, just an onlyfans :laughing: 

You will miss unbelievable things like this one ![IMG_20201113_094431.jpg](https://user-images.githubusercontent.com/48216/99048145-78161500-2595-11eb-84dd-d86cebd0f2cb.jpg)

**Comment by firetrappe** [comment]
That explains the profile pic 😳

**Comment by kenands** [comment]
Cool :) I joined the Facebook group.
And here is my strava account 😄 :
https://www.strava.com/athletes/71623539

**Comment by rickoneeleven** [comment]
you getting a strava club setup brother? @cagnulein

**Comment by cagnulein** [comment]
@rickoneeleven https://www.strava.com/clubs/783173 i will add some fancy pics to the club later

**Comment by rickoneeleven** [comment]
cool, I'm second in the leader board already.
