### ISSUE TITLE
Build an android version

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#51]

**Comment by cagnulein** [comment]
@czuczorf i will write here when i'm ready for an alpha version

**Comment by cagnulein** [comment]
@czuczorf first boot on android without changing a line of code :P

![Immagine](https://user-images.githubusercontent.com/48216/98516584-fceaf100-226c-11eb-942c-c871f9b324da.png)

**Comment by cagnulein** [comment]
@rickoneeleven do you wanna try android version too? in italy we say "we did 30, do 31!"

**Comment by rickoneeleven** [comment]
yeah, how? :smile: 

i'm in the office today, so will have to be tonight.

**Comment by czuczorf** [comment]
> @czuczorf first boot on android without changing a line of code :P
> 
> ![Immagine](https://user-images.githubusercontent.com/48216/98516584-fceaf100-226c-11eb-942c-c871f9b324da.png)
> 
> i would like to try bluetooth stack on it this evening. If it works, i will love Qt forever :D

Wow, that was quick! ;-) Oh how much do I hate those different type of screen aspect ratios.. ;-) Btw. Domyos bike is currently out of stock here in Hungary :-(

**Comment by cagnulein** [comment]
@rickoneeleven install the apk and pray (i just installed it on my phone, but i'm at work too, so i've not tested to TM yet)

@czuczorf nooo checkout how did i buy my TM https://robertoviola.cloud/2020/09/07/quando-un-nerd-vuole-un-tapis-roulant/ (translate it ofc)

[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5509057/android-build-debug.zip)

**Comment by rickoneeleven** [comment]
haha omg i absolutely love that little hack to track when treadmill comes back in stock :laughing:

**Comment by cagnulein** [comment]
guys i hide some UI components just to have a "usable" interface, i will be at home for lunch and i will test it, just to see if the connection with my TM works
[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5509864/android-build-debug.zip)

**Comment by firetrappe** [comment]
Nice! Much cleaner than the original screen :+1:

**Comment by czuczorf** [comment]
Meanwhile in Hungary.. ;-) Thanks for the stock check idea @cagnulein 
![image](https://user-images.githubusercontent.com/2247388/98534614-03856280-2285-11eb-94e5-f767848a32e5.png)

**Comment by cagnulein** [comment]
i love the people around this project, i guess we're all unknown brothers :D

**Comment by cagnulein** [comment]
Guys it's working https://youtu.be/ri-HJfzLnSY

**Comment by rickoneeleven** [comment]
ohhh yeah just wait until I get home, test it - it won't work and it will be my bloody drivers or something :laughing:

**Comment by firetrappe** [comment]
> Guys it's working https://youtu.be/ri-HJfzLnSY

Amazing! Congratulations! :tada:

Quick, everyone send their Pi's back for a refund :smile:

**Comment by cagnulein** [comment]
> ohhh yeah just wait until I get home, test it - it won't work and it will be my bloody drivers or something 😆

@rickoneeleven hahahah i was laughing alone in the street like an idiot :D

> Quick, everyone send their Pi's back for a refund 😄

@firetrappe  hahahah it's too soon to say so :D

**Comment by firetrappe** [comment]
@cagnulein I have some good news...

![IMG_0332 (Phone)](https://user-images.githubusercontent.com/66125348/98575591-49f0b680-22b1-11eb-8779-f9f0ba3ca6b9.PNG)

It's a bit unpredictable, but it is looking more hopeful than using the Pi. 👍

**Comment by rickoneeleven** [comment]
it connected to treadmill, and showed up in zwift, but the speed in zwift stayed at zero on the connection screen. and when i started run, the speed didn't show at all, but good start 👍

**Comment by cagnulein** [comment]
@firetrappe this means that the software on my side should be ok, it's just a matter of libraries and stuff. Do you have any news about the bisect?

@rickoneeleven i didn't try with zwift yet, tomorrow I will try and in case I fix this one too.

Thanks guys to testing it

**Comment by firetrappe** [comment]
> @firetrappe this means that the software on my side should be ok, it's just a matter of libraries and stuff. Do you have any news about the bisect?

@cagnulein I haven't had chance to bisect yet. I'll have a look later tonight.

I have been trying the android version again. Since the first test when it worked, I have had no success with subsequent attempts.

It is the same as all the other versions I have tested; the first run works, after that, bike always seems to connect to the bridge, but the bridge doesn't appear to receive any data. 

Are logs stored on android?

**Comment by cagnulein** [comment]
>  @cagnulein I haven't had chance to bisect yet. I'll have a look later tonight.
> 

Ok, np

> I have been trying the android version again. Since the first test when it worked, I have had no success with subsequent attempts.

Ok, i will do the same tomorrow with my TM

> It is the same as all the other versions I have tested; the first run works, after that, bike always seems to connect to the bridge, but the bridge doesn't appear to receive any data. 
> 

The bridge or zwift? I bet the is zwift that it doesn't receive. Infact, in this scenario, try to open nrfconnect and check if you see it.

> Are logs stored on android?

Yes but i didn't check where yet. I will tell you tomorrow

**Comment by firetrappe** [comment]
> > It is the same as all the other versions I have tested; the first run works, after that, bike always seems to connect to the bridge, but the bridge doesn't appear to receive any data.
> 
> The bridge or zwift? I bet the is zwift that it doesn't receive. Infact, in this scenario, try to open nrfconnect and check if you see it.

The bridge. The first time I tested and it worked, the 'speed' field on the android GUI updated as I pedalled. Nothing since, apart from resistance. Note that the display on the bike console worked with the first test. It has only shown resistance on following attempts.

**Comment by cagnulein** [comment]
No i guess you misunderstood me. If you say "the bridge doesn't receive data" you are meaning that my software can't talk with the bike. In your case, instead, the Bridge can't talk with zwift (you didn't see the bridge anymore on zwift)
Am I wrong?

Very curious the behavior of the display. We will have to go deeper on it, but i guess it's not a protocol issue, maybe some timings or something similar

**Comment by cagnulein** [comment]
Tomorrow I will do more test on my TM, maybe i found a common issue

**Comment by firetrappe** [comment]
One other observation... When the bridge is started Speed=0. When the bike connects Speed=0.0
Bridge also shows a connection with Zwift. However, I don't have Zwift running on any devices.

![Screenshot_20201109-194537 (Phone)](https://user-images.githubusercontent.com/66125348/98589343-0bfd8d80-22c5-11eb-821f-1552bab4953b.png)
![Screenshot_20201109-194600 (Phone)](https://user-images.githubusercontent.com/66125348/98589361-10c24180-22c5-11eb-8078-2fe28cf32ed3.png)

**Comment by cagnulein** [comment]
The speed changes because I received 0.0 from the bike.
The zwift icon is a bug i guess, i will look into too. Thanks

**Comment by cagnulein** [comment]
the log files will be in the downloads folder of your android device.

Guys, i don't know if i'm the luckiest guy in the world, but with my setup (Xiaomi Mi3 with qdomyos-bridge, Honor View 20 with Zwift and my Intense Run) everything works ALWAYS. I closed the bridge, open back again, zwift always saw it, and connect flawless. I don't know why it's not so stable to you. Anyway now with the log on android too, we should understand something more.

You need to enable the "STORAGE PERMISSION"

[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5515785/android-build-debug.zip)

**Comment by cagnulein** [comment]
a new version @firetrappe this one is for you: i guess i solved your console issue. please try. Of course the same solution is avaiable to linux too

tell me good news please!

[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5516216/android-build-debug.zip)

**Comment by firetrappe** [comment]
> a new version @firetrappe this one is for you: i guess i solved your console issue. please try. Of course the same solution is avaiable to linux too
> 
> tell me good news please!
> 
> [android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5516216/android-build-debug.zip)

@cagnulein Thank you! I will test later :pray:

**Comment by czuczorf** [comment]
![image](https://user-images.githubusercontent.com/2247388/98683902-dceb2880-2365-11eb-8e08-1d73f6b4d30a.png)
;-) sorry for interuppting the discussion

**Comment by cagnulein** [comment]
@czuczorf hahahah BUY BUY BUY

**Comment by cagnulein** [comment]
My first session on android of 1h15m. Everything works as on the raspberry!
I attach the log for future analysis: nerd porn :D
[debug-Tue Nov 10 18_44_07 2020.zip](https://github.com/cagnulein/qdomyos-zwift/files/5519916/debug-Tue.Nov.10.18_44_07.2020.zip)

**Comment by czuczorf** [comment]
> a new version @firetrappe this one is for you: i guess i solved your console issue. please try. Of course the same solution is avaiable to linux too
> 
> tell me good news please!
> 
> [android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5516216/android-build-debug.zip)

Hi Cagnulein, 

Thank you for your work! Finally my Domyos 500 bike arrived yesterday ;-) I've tried out this version, looks promising, here are my notes, hopes helps in the development

I have a Xiaomi Redmi Note 8, I've tried to allow every permission for the App

- Sometimes it takes a lot of time for Zwift to find my phone and there are cases it does not find it at all.
- There are cases I've got "No signal" message on Zwift eventough it says it's connected
- It happend once that I see duplicate of my phone on Zwift in device search, one with no signal message
- Zwift status feedback is not accurate on the Android app, it says connectected eventhough the app is not running on my computer
- What's the correct start order of connecting together the domyos-android-zwift, or how should I handle this type of connection issues?
- Is it normal that every data displayed on my Domyos "computer" is really laggy, elapsed time (and everything else)is only refreshed around in every 6-10sec
- If I start to change the resistence on Domyos computer for ex. to "6", it goes back to "1" after some sec
- Is the resistence controlled by the Android app or Zwift? 
- Would be nice if the resistence can be controlled by Zwift ;-)
- If the resistence is controlled by the Android app, please make the +/- buttons bigger
- It's easy to press the "chart" button accidentally, but I was not able to close that window so I have to restart it every time (landscape mode)
- What's the purpose of the start/stop button?
- It would be nice that the app does not let the phone go to sleep mode

Sorry for the long list ;-) Hope it helps somehow
Thanks!
All the bests,
Feri

**Comment by cagnulein** [comment]
> * Sometimes it takes a lot of time for Zwift to find my phone and there are cases it does not find it at all.

yeah, i saw it too, i saw that restarting the bluetooth on my zwift phone it helps. I will investigate more on it.

> * There are cases I've got "No signal" message on Zwift eventough it says it's connected

Saw it too. Same as above

> * It happend once that I see duplicate of my phone on Zwift in device search, one with no signal message

Never saw this, but i guess all these 3 points are releated.

> * Zwift status feedback is not accurate on the Android app, it says connectected eventhough the app is not running on my computer

Yes, there is already #55 

> * What's the correct start order of connecting together the domyos-android-zwift, or how should I handle this type of connection issues?

Usually i start the treadmill first, so the bridge and finally zwift.

> * Is it normal that every data displayed on my Domyos "computer" is really laggy, elapsed time (and everything else)is only refreshed around in every 6-10sec

No it's not normal. Seems that the communication is really bad. Did you try to reduce the distance between the bridge and the treadmill? Send me the log if it happens again

> * If I start to change the resistence on Domyos computer for ex. to "6", it goes back to "1" after some sec

Because zwift it's controlling it!

> * Is the resistence controlled by the Android app or Zwift?
> * Would be nice if the resistence can be controlled by Zwift ;-)

Yes it's already controlled!

> * If the resistence is controlled by the Android app, please make the +/- buttons bigger

Yes, in these days i'm completely rewriting the android GUI app. So you will see it in the next days :)

> * It's easy to press the "chart" button accidentally, but I was not able to close that window so I have to restart it every time (landscape mode)

Yes, for now i removed it from the android app

> * What's the purpose of the start/stop button?

Starting and stopping the treadmill

> * It would be nice that the app does not let the phone go to sleep mode

Yes, i will add this FR.

> 
> Sorry for the long list ;-) Hope it helps somehow
> Thanks!
> All the bests,
> Feri

Thanks you for your feedback!

**Comment by czuczorf** [comment]
> > * Sometimes it takes a lot of time for Zwift to find my phone and there are cases it does not find it at all.
> 
> yeah, i saw it too, i saw that restarting the bluetooth on my zwift phone it helps. I will investigate more on it.
> 
> > * There are cases I've got "No signal" message on Zwift eventough it says it's connected
> 
> Saw it too. Same as above
> 
> > * It happend once that I see duplicate of my phone on Zwift in device search, one with no signal message
> 
> Never saw this, but i guess all these 3 points are releated.
> 
> > * Zwift status feedback is not accurate on the Android app, it says connectected eventhough the app is not running on my computer
> 
> Yes, there is already #55
> 
> > * What's the correct start order of connecting together the domyos-android-zwift, or how should I handle this type of connection issues?
> 
> Usually i start the treadmill first, so the bridge and finally zwift.
> 
> > * Is it normal that every data displayed on my Domyos "computer" is really laggy, elapsed time (and everything else)is only refreshed around in every 6-10sec
> 
> No it's not normal. Seems that the communication is really bad. Did you try to reduce the distance between the bridge and the treadmill? Send me the log if it happens again
> 
> > * If I start to change the resistence on Domyos computer for ex. to "6", it goes back to "1" after some sec
> 
> Because zwift it's controlling it!
> 
> > * Is the resistence controlled by the Android app or Zwift?
> > * Would be nice if the resistence can be controlled by Zwift ;-)
> 
> Yes it's already controlled!
> 
> > * If the resistence is controlled by the Android app, please make the +/- buttons bigger
> 
> Yes, in these days i'm completely rewriting the android GUI app. So you will see it in the next days :)
> 
> > * It's easy to press the "chart" button accidentally, but I was not able to close that window so I have to restart it every time (landscape mode)
> 
> Yes, for now i removed it from the android app
> 
> > * What's the purpose of the start/stop button?
> 
> Starting and stopping the treadmill
> 
> > * It would be nice that the app does not let the phone go to sleep mode
> 
> Yes, i will add this FR.
> 
> > Sorry for the long list ;-) Hope it helps somehow
> > Thanks!
> > All the bests,
> > Feri
> 
> Thanks you for your feedback!

Amazing and Thank You!
Resistance is controlled by the Zwift is the greatest news, ever! ;-) 
Thanks I will collect some log, the phone is alredy nearby the domyos computer.
Btw Zwift and the android does detect the speed changes imeadiatelly, only the DC do the lagg, which does not really matter to me if it does not have any side effects.
Thanks again
Cheers

**Comment by cagnulein** [comment]
ok guys, this is the new android version. It's a very alpha version. I've only changed the UI using QML, so it should adapt to android better than before.

I tried to my treadmill and seems fine.

Known issues:
1) an icon missing in the top left corner
2) speed text may overlaps the icon
3) if you scroll the values, they will overlap the top bar

I added also an experimental support to #59 (always wake), so let me know if it works.

[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5581370/android-build-debug.zip)

**Comment by mitchoklemen** [comment]
The GUI looks fine on my androidTV. But sometimes maybe loose connection or freezes. I cant change + - . Otherwise works good.
I didnt notice any overlaps yet, top left icon is ON.
On my tredmill there is no "resistance%" to set, maybe you could hide it when treadmill is detected.

**Comment by cagnulein** [comment]
@mitchoklemen thanks!
1) could you please send me the logs that you should find in the download folder? i would like to understand the connection freezes.
2) what do you mean when you say you can't change + and  -? The treadmill doesn't react to the + or - button of the UI?
3) yes, you're right about the resistance, it's something that i would like to do too

**Comment by cagnulein** [comment]
ok i fixed the 3rd point, now i load the icon only when the connection is ok to the machine

[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5608386/android-build-debug.zip)

**Comment by cagnulein** [comment]
![IMG_20201127_191617](https://user-images.githubusercontent.com/48216/100476533-1651c100-30e6-11eb-9fc9-2ebaf932cf17.jpg)

So far so good with the new version

**Comment by cagnulein** [comment]
i've just release the android version on the main page https://github.com/cagnulein/qdomyos-zwift/releases/tag/1.0.0
I'm closing this one. If you have some android specific issue, feel free to open a new issue.
Thanks
