### ISSUE TITLE
[BUG] QZ - Focus is in wrong place for changing values in Settings

### ISSUE THREAD

**Issue by gadi247** [cagnulein/qdomyos-zwift#514]
**Describe the bug**

When you got to change values, such as zoom or HR zones, the cursor (focus) is in the wrong place. It is placed AFTER the value so you need to move the cursor first

**To Reproduce**
1. Go to '...' Settings -> General Options -> UI Zoom
2. Click on '....' Cursor is AFTER, so " <Cursor>80"

**Expected behavior**
Cursor should be BEFORE, so "80<Cursor>" so that you can simply delete and re-enter
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
done @gadi247 ! it will be in the version 2.8.138 and above! Thanks for reporting this
