### ISSUE TITLE
Schwinn conversion is increasingly off as resistance gets higher

### ISSUE THREAD

**Issue by rjbutler** [cagnulein/qdomyos-zwift#521]
Moved from the other Schwinn issue.  I'll do some experimentation later today and get some conversion and watt values

@cagnulein  I'm not sure if you want to deal with two things at once..  I did a regular class, and it tracked fine.  But I think there's something slightly off with the conversion.  There are two things I noticed:

1. As the resistance gets higher, the class target and the peloton r% get further apart -- the auto-resistance sets the peloton R% correctly (tuned by gears) at the lower resistance levels, but overshoots by an increasing amount as the target resistance increases.
2. The Schwinn conversion algorithm is wrong once the resistance is over 50.  Or maybe the power reported by the bike is wrong.  But once the converted resistance (Peloton R%) is over 50, the Schwinn resistance as shown on the bike is much higher than it should be.

It mostly works great, it just gets a more difficult than I think is intended at the higher resistances.

[debug-Fri_Dec_17_15_22_49_2021.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/7738325/debug-Fri_Dec_17_15_22_49_2021.log.zip)

_Originally posted by @rjbutler in https://github.com/cagnulein/qdomyos-zwift/issues/500#issuecomment-997096848_

**Comment by rjbutler** [comment]
@cagnulein 

Here's some data.  This is with the Schwinn calculation on and an offset of -10

`Cadence	Actual Schwinn R	Calculated Schwinn R	Peloton R	Watts
80	5	3	18	55
80	10	4	24	79
80	15	6	29	103
79	20	11	34	134
80	25	16	37	162
80	30	22	40	195
79	35	29	44	226
80	40	33	46	256
79	45	40	48	278
82	50	45	50	323
78	55	54	53	341
80	60	57	58	424

**Comment by cagnulein** [comment]
thanks @rjbutler 
Are you able to put that data in this https://github.com/cagnulein/qdomyos-zwift/issues/141#issuecomment-783390189 creating a copy of that file with these value. That file should recreate a polynomial function that i can add to as a separate schwinn profile in QZ.
Let me know

**Comment by rjbutler** [comment]
@cagnulein Do you need the whole table filled in?  And should I used Schwinn resistance or what I believe the equivalent Peloton resistance is?

**Comment by cagnulein** [comment]
@rjbutler yes, i mean we need to create a new formula, so the new formula should apply to all the cadence and resistance value...it's not an easy job, i know.

You should use the resistance accordingly to the table header ( i didn't create the file myself). It was from a QZ user

**Comment by cagnulein** [comment]
@rjbutler i was checking the source code and i found this https://github.com/cagnulein/qdomyos-zwift/blob/cb37687f0b7d7b21746be0ddb94de9bb7dd7841f/src/schwinnic4bike.cpp#L548

maybe it's responsible for what you're seeing? I mean that line says that if the peloton resistance calculated by the polynomial formula, is greater than 54, then the schwinn resistance conversion will be the same.
So for example:

polynomial conversion -> peloton resistance 57 -> schwinn resistance 57 -> ss2k resistance 57

Maybe this is your issue? If so how we could treat the peloton resistance over 54? This code has been done in this way cause a user told me that over resistance 54, the resistance of pelont and schwinn could be more or less the same.

Let me know

**Comment by rjbutler** [comment]
> Maybe this is your issue? If so how we could treat the peloton resistance over 54? This code has been done in this way cause a user told me that over resistance 54, the resistance of pelont and schwinn could be more or less the same.

@cagnulein, I see.  That might explain what I'm seeing.

Before I discovered QZ I played around with a few conversion points.  On the Peloton, 20 resistance is basically free spinning and I don't think I've ever heard them call out a lower resistance.  On the Schwinn (at least mine), that number is truly zero or maybe 2-3. So that means Peloton really uses a range of 20-100 with 81 steps, while Schwinn uses 0-100 for 101 steps.  

So using that, S=(P-20)*1.25 is a simple formula to do the conversion and it's actually pretty close to the QZ conversion with an offset of -10.

**Comment by cagnulein** [comment]
ok @rjbutler i will add a new setting to enable this conversion. Is it ok for you? (so it will not break the compatibility with the rest of the people that are using it in the actual way ;) )

**Comment by rjbutler** [comment]
Sure, I'd like to give it a try and see how it goes.

**Comment by cagnulein** [comment]
done @rjbutler 
it will be in the next beta (2.9.30 and above). There is a new setting, in the schwinn section, called "Resistance Alternative Calc.". Turn in on along with the other one "Calc. Resistance"
If you have idea for better naming, i'm happy to change them :)

**Comment by cagnulein** [comment]
@rjbutler what about this? is it ok?

**Comment by rjbutler** [comment]
@cagnulein I still need to take a regular class and see, I'll let you know

**Comment by rjbutler** [comment]
@cagnulein I think we can call this good.  The Schwinn calculated resistance tile is off as the resistance gets higher, but the Peloton resistance feels right up to as far as I took it on my last ride (55).  And that's the important one.  

I used a gain of -10 still.

I may try tweaking it a bit now that I got a build working.  I'll submit a PR if I get something better.
