### ISSUE TITLE
[REQ] Allow resistance adjustments from the Peloton Resistance tiles

### ISSUE THREAD

**Issue by ndesai510** [cagnulein/qdomyos-zwift#527]
Currently there are 4 tiles for resistance:
Resistance, 
Target Resistance,
Peloton Reistance,
Target Peloton Resistance.

For bikes that allow for auto resistance changes, there are + and - buttons on the Resistance and Target Resistance tiles.

It would be great to have the + and - buttons on the Peloton resistance tiles as well.  It would eliminate the need to have all 4 tiles showing.

**Comment by cagnulein** [comment]
Yeah sure!I will do this tomorrow!
Thanks for the idea! @ndesai510

**Comment by cagnulein** [comment]
@ndesai510 done! are you in the beta? it will be in the 2.9.13 and above

**Comment by ndesai510** [comment]
@cagnulein - awesome,thanks!  Is the beta version you are referring to available in the Google Play Store? I'm signed up through there, but it's currently on version 2.8.x

**Comment by cagnulein** [comment]
i didn't upload the android one yet. Do you have also iOS version? @ndesai510

**Comment by ndesai510** [comment]
Ok. No, I only have Android.  If you have pre beta version of the Android version, I can test it out and report back if you want. Else, I will wait for it to become available in the Play store. Thanks again!  The app is a great addition to my bike.

**Comment by cagnulein** [comment]
@ndesai510 no problem, i'm building the android one ;) just to be sure: send me an email to roberto.viola83 at gmail.com so i will be sure that you're in the private beta ;)
