### ISSUE TITLE
[BUG] TOORX TRX ROUTE KEY

### ISSUE THREAD

**Issue by MarcoFilosi** [cagnulein/qdomyos-zwift#541]
As described here: https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F 
I've attached the debug log files since at the moment, using an Android device, QZ does not control the TOORX 65S EVO Treadmill efficiently. At the moment it seems the treadmill starts to work suddenly and for me it is still a mystery when and how to start it.
The only thing that I understood is that if I press (+) button of Inclination on QZ app, the treadmill will be stopped.

I hope the debug logs could help. Thanks
[debug-Fri_Dec_31_15_56_20_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/7796527/debug-Fri_Dec_31_15_56_20_2021.log)
[debug-Fri_Dec_31_15_47_06_2021.log](https://github.com/cagnulein/qdomyos-zwift/files/7796528/debug-Fri_Dec_31_15_47_06_2021.log)

**Comment by cagnulein** [comment]
#15

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/issues/32

**Comment by cagnulein** [comment]
#537

**Comment by MarcoFilosi** [comment]
Here you can find Bluetooth logs after using treadmill with FitConsole app. I hope it helps

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7798151/btsnoop_hci.log)
![screenshot](https://user-images.githubusercontent.com/1218291/147858953-4c066062-af20-47b0-8b0d-e82a689eeb9f.jpeg)

**Comment by cagnulein** [comment]
Ciao @MarcoFilosi come eravamo rimasti con questo? Sinceramente non ricordo più

**Comment by MarcoFilosi** [comment]
I have to test your latest changes on Beta version. Once ok you can close it.

**Comment by cagnulein** [comment]
@MarcoFilosi qualche aggiornamento?

**Comment by MarcoFilosi** [comment]
On Android it works fine but the new setting "TOORX 65S EVO" doesn't work. 
To start the treadmill I have to open QZ app, then tap on app Start button, then Pause it and then tap on Start again. Once done I am able to have QZ working and communicate with treadmill. I think you can remove the setting "TOORX 65S EVO" setting. Now the experience is acceptable even if I have to tap start and stop some times.

**Comment by cagnulein** [comment]
ok thanks for the feedback. i'm leaving the setting for now, maybe it will help on debug in the future. I'm closing this now, but if you want to dig it, let me know and feel free to open it back. Thanks
