### ISSUE TITLE
Strava Upload isn’t working

### ISSUE THREAD

**Issue by Mtalanczuk** [cagnulein/qdomyos-zwift#544]
The Strava Upload isn't working. I download the FIT file and it doesn't do anything ```
```

```
```

**Comment by Mtalanczuk** [comment]
I can't figure out how to load the debug files

**Comment by cagnulein** [comment]
@Mtalanczuk you need to attach them from a pc/Mac

**Comment by Mtalanczuk** [comment]
debug-Sun_Jan_2_11_26_44_2022.log

**Comment by Mtalanczuk** [comment]
[debug-Sun_Jan_2_11_26_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7800093/debug-Sun_Jan_2_11_26_44_2022.log)

**Comment by cagnulein** [comment]
hi @Mtalanczuk 
i checked your log and it's all fine to the QZ side

"strava upload completed!"
status\":\"Your activity is still being processed.

I suggest 2 things:
1) be sure that you linked the right strava account to QZ (some QZ users have more than 1 account on strava)
2) contact Strava, it's possibile that your account has some issue (it happened in the past also to other users).

Let me know and in case, please update this ticket.
Thanks

**Comment by Mtalanczuk** [comment]
I was able to get one to update yesterday.   I will try one again today.

**Comment by cagnulein** [comment]
ok @Mtalanczuk maybe strava was having just a long backtrace

**Comment by cagnulein** [comment]
@Mtalanczuk any news? Can we close this?

**Comment by Mtalanczuk** [comment]
Yes!  Thanks
