### ISSUE TITLE
[BUG] Domyos EL520 - cadence support and connection to Rouvy

### ISSUE THREAD

**Issue by rteichmann** [cagnulein/qdomyos-zwift#548]
**Describe the bug**
I am trying to use qdomyos with my Domyos EL520 elliptical. After the initial connection I was happy that it works, but after that, I realised that cadence is not working. After the successful connection to the elliptical, I can see speed, I can control the resistance and also odometer is working. Nevertheless the cadence is always zero and also on the elliptical it shows zero (if I disconnect the qdomyos and use it without it or with KinoMap it is working properly). Also when I checked the debug log I can see, that the cadence is listed there, but it is not showed in the application. Also when I am trying to connect to Rouvy application, I am not able to add my device as the Cadence / Speed sensor - just heartbeat is working (on the speed / cadence it is saying that the device cannot be used).

Is there any experience with these ellipticals? Should it work, or is this feature not implemented?

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 15.1
 
**Append a debug log**
 - attached log and screenshot
[debug-po_led_3_08_02_59_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7800743/debug-po_led_3_08_02_59_2022.log)
![po led 3 07_32_35 2022](https://user-images.githubusercontent.com/11817771/147906639-751d93e0-f18a-4011-8bfc-937b5aae828a.jpg)
t

**Comment by cagnulein** [comment]
@rteichmann i already added cadence support in the beta. Write me an email to roberto.viola83 at gmail.com and i will add you! Please remember to close this if it fixed ;)

**Comment by rteichmann** [comment]
Thanks a lot!

**Comment by cagnulein** [comment]
@rteichmann sent! let me know! be sure the ios peloton workaround is on (it should be by default)

**Comment by cagnulein** [comment]
#195

**Comment by rteichmann** [comment]
Thanks a lot! It is working like a charm! Of course I need to test it more, but from the first insight, all issues are removed. When you are going to release this version?

**Comment by cagnulein** [comment]
@rteichmann great! I guess I will submit it this week
