### ISSUE TITLE
[BUG] Strava upload incorrect speed values

### ISSUE THREAD

**Issue by cimpresovec** [cagnulein/qdomyos-zwift#549]
**Describe the bug**
When using the automatic upload to Strava or manually uploading the .FIT file the speed data is wrong. It only shows the average speed but not the graph.

**To Reproduce**
1. Workout using the app
2. Save to FIT for automatic upload

**Expected behavior**
The speed graph should be correctly displayed in Strava.

**Screenshots**
Speed graph from qdomyos
![Mon Jan 3 17_22_47 2022_speedInclination](https://user-images.githubusercontent.com/615521/147957878-a689ae67-443a-4493-a142-1eb9a568ae7d.png)

Strava:
![strava](https://user-images.githubusercontent.com/615521/147958252-6a088220-418f-4643-95f4-079dc1185ff1.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android
 - Version 12

**Equipment:**
Bike: Indoor Exercise Bike Domyos 500

**Append a debug log**
[debug-Mon_Jan_3_16_52_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7803063/debug-Mon_Jan_3_16_52_49_2022.log)

**Fit file**
[Mon Jan 3 17_22_41 2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/7803069/Mon.Jan.3.17_22_41.2022.zip)

**Comment by cagnulein** [comment]
hi @cimpresovec thanks for the feedback. I checked the fit file and it seems allright,

![image](https://user-images.githubusercontent.com/48216/147958648-bc7e2485-22ca-4711-9c47-c6779059c8a0.png)

you can see here the speed. You can test yourself it with this https://www.fitfileviewer.com/
Did you try also to upload the fit file on another service? if it works well means that the issue is on strava (and then we should open a ticket to them)
Let me know

**Comment by cimpresovec** [comment]
@cagnulein I don't use any other services that graph the data, so I don't know if there is an issue with others.

**Comment by cimpresovec** [comment]
@cagnulein I'd say we have to report this with Strava then. What is the procedure for that?

**Comment by cagnulein** [comment]
> @cagnulein I don't use any other services that graph the data, so I don't know if there is an issue with others.

For example http://intervals.icu

**Comment by cagnulein** [comment]
> @cagnulein I'd say we have to report this with Strava then. What is the procedure for that?
> 
> 

You have to use the support page on strava

**Comment by cimpresovec** [comment]
@cagnulein Intervals.icu works. I'll try to contact Strava about this.

**Comment by cagnulein** [comment]
ok thanks! i guess another guy has the same issue and at the end it was
strava
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 gen 2022 alle ore 19:31 Luka Horvat <
***@***.***> ha scritto:

**Comment by cimpresovec** [comment]
@cagnulein This is the response I got from Strava:

---
Thank you for writing in. When I look at the fit file you provided I am not seeing GPS data which one would normally see when uploading an activity from Zwift. However, since you used qdomyos-zwift we suggest reaching out to the company directly for any questions. To provide some context, we have a publicly available API that hundreds of external developers use to integrate with Strava data. These integrations are built and maintained by those 3rd party developers which means that any troubleshooting questions are better directed their way.

Sorry about that and good luck!
---

Looks like they need GPS data for this to work and don't look like they want to be fixing it.

**Comment by cagnulein** [comment]
@cimpresovec Did you try to change the activity type to a virtual ride/run?

**Comment by cimpresovec** [comment]
@cagnulein Yeah I tried and it didn't change anything. I've been using Kinomap directly with my bike these days so I didn't really search for workaround for now. But it looks like Strava won't be doing anything on this.

**Comment by cagnulein** [comment]
the thing is that it's happening only for you as far as i know. maybe you can try to create a new fake strava account to test it in the future.

**Comment by cimpresovec** [comment]
Yeah I'll keep an eye out for this in the future. I'll post a workaround here if I will need it. Thank you.
