### ISSUE TITLE
[BUG] Echelon App displays incorrect resistance by default (affected by Swift resistance offset)

### ISSUE THREAD

**Issue by abraham09** [cagnulein/qdomyos-zwift#557]
**Describe the bug**
When using the Echelon app and Echelon bike with QZ beta virtual Echelon, the resistance shown on the Ecehelon app is 4 higher than it should be, messing up the total output calculation and other numbers. This is only on the Echelon app, QZ displays the correct resistance.

**To Reproduce**
1. Go to QZ beta, start ride, open Echelon app 
2. Notice resistance is off by 4 messing up the rest of the numbers 
3. Workaround: go to Settings - Bike Options - Swift Resistance Offset and notice it is defaulted to 4, change to 0 for the resistance in Echelon to display normally. 

**Expected behavior**
* Swift settings should not affect Echelon App display, resistance should display normally by default. If want to keep this as a feature for Echelon as well, then I would suggest:
* The app should not default to 4 as the Swift Resistance Offset and should default to 0 instead 
* The app should update the title of "Swift resistance offset" to "Swift/Echelon Resistance Offset" so that it is clear that this setting affects both Swift and Echelon 

**Screenshots**

**Desktop (please complete the following information):**
- Ipad Air 4 Echelon App

**Smartphone (please complete the following information):**
 - Device: iphone 12 pro 
 - OS: latest
 - Version: QZ beta

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
done @abraham09 it will be in the 2.9.35 version

**Comment by cagnulein** [comment]
i don't remember did i sent you this version? if not write me an email to roberto.viola83 at gmail.com

**Comment by cagnulein** [comment]
@abraham09 did i send you the email? are you still interesting on this?
