### ISSUE TITLE
Domyos Intense Run - distance and time falled to 0 on treadmill console 35 minutes after the start

### ISSUE THREAD

**Issue by kenands** [cagnulein/qdomyos-zwift#56]
> just a little issue but I don't know if relatad to your app, distance and time falled to 0 on treadmill console 35 minutes after the start, but there wasn't issue in communication between zwift and the treadmill.

if you will see it again, send me the full log. i will try to understand. thanks

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/issues/22#issuecomment-723855084_

Hi @cagnulein, this issue happened again.
On 4 sessions it happened 2 times.
Appart from that everything works great :)

**Comment by kenands** [comment]
[debug-sam. nov. 14 23_24_05 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5541594/debug-sam.nov.14.23_24_05.2020.log)

**Comment by cagnulein** [comment]
@kenands hahah wonderful bug! it's a midnight bug! when the clock reset to 0:00 i have some timer that gives negative value! :D i will fix asap

**Comment by cagnulein** [comment]
you're the only one who train himself at midnight :D

**Comment by cagnulein** [comment]
fixed!

**Comment by kenands** [comment]
Haha I never thought that was a midnight bug.
I know, this is the time I need to kick myself to doing training :D
Once again nice and fast debugging 👍 
Thanks :)

**Comment by kenands** [comment]
Hi @cagnulein , this issue happened once again at mignight lol

[debug-ven. nov. 20 23_39_39 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5580257/debug-ven.nov.20.23_39_39.2020.log)

**Comment by cagnulein** [comment]
> Hi @cagnulein , this issue happened once again at mignight lol
> 
> [debug-ven. nov. 20 23_39_39 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5580257/debug-ven.nov.20.23_39_39.2020.log)
> 

Are you sure you pulled and built the correct version?

**Comment by kenands** [comment]
Sorry :/, you are right, I thought that I updated after this commit but I checked and it's not the case.
thanks
