### ISSUE TITLE
[BUG] Bike not adjusting within Peloton Target Resistance

### ISSUE THREAD

**Issue by TechieJay** [cagnulein/qdomyos-zwift#563]
**Describe the bug**
At this time QZ does not set the resistance value to the minimum peloton resistance displayed within the Peloton R Tile. 

**To Reproduce**
1. Start qz app
2. Ride bike until cadence appears
3. Start Peloton Ride
4. skip intro and then Accept qz to follow with auto resistance

**Expected behavior**
Auto resistance to set the peloton R resistance to the minimum value within the Target Peloton Tile.

**Screenshots**
https://github.com/TechieJay/qzecheloon/blob/main/IMG_0463.PNG
https://github.com/TechieJay/qzecheloon/blob/main/IMG_0464.jpg
https://github.com/TechieJay/qzecheloon/blob/main/IMG_0467.jpg
https://github.com/TechieJay/qzecheloon/blob/main/IMG_0468.PNG

**Desktop (please complete the following information):**
 -ipad pro 
-iOS
14.6(18F72)

**Smartphone (please complete the following information):**
 - Device: Iphone 13 pro max
 - OS: iOS
 - Version 15.2(19c57)

**Append a debug log**

https://github.com/TechieJay/qzecheloon/blob/main/debug-Sat_Jan_8_09_58_05_2022.log
  
  
**Additional context**
Using Echelon ex-5 connect 
Class for test: 20 minute Low impact ride with Tunde Oyeneyin from 12/20/21

**Comment by cagnulein** [comment]
i saw auto resistance working in your log. Do you mean that it sets to average value instead of minimun one? @TechieJay

**Comment by TechieJay** [comment]
@cagnulein I can now see auto resistance shift but I thought it would shift to the minimum value in the T.PelotonR tile as I have the difficulty in peloton options set to lower. 

If you view the screenshots you see the Peloton R tile never appears in sync with the minimum value expressed in the T.Peloton R tile. Should these be in sync?

**Comment by cagnulein** [comment]
yes the should be in sync. I need time to check the log, i'm completely overwhelmed by request. I ask you to wait some days

**Comment by TechieJay** [comment]
@cagnulein Completely understand! Please take your time as I understand you are just one man. Thank you so much and cheers!

**Comment by cagnulein** [comment]
@TechieJay ok checked the log and it's a false positive.
The problem about the syncing of these tiles it's because, for your echelon bike, changing from peloton resistance 25 to 27 means doesn't change the resistance at all because your peloton to echelon scale, don't have all the step (1 to 32 vs 0 to 100).

I'm closing this, reopen if it's still unclear
