### ISSUE TITLE
[REQ] Implement PID Heart Tile

### ISSUE THREAD

**Issue by CiccioFritz79** [cagnulein/qdomyos-zwift#565]
Hi,

I think could be interesting have a new tile for setting PID Heart: 0 = Disabled, then 1, 2, 3 and 4 for setting the desired PID.

Thanks in advance

**Comment by CiccioFritz79** [comment]
2 icons example

![407db1f4e4ad1fc027d01a09ed569d7d](https://user-images.githubusercontent.com/95940420/148776429-75d21bc5-79c5-4df5-b434-320fd5a4bf13.png)
![664541_gear_512x512](https://user-images.githubusercontent.com/95940420/148776445-e6f1ff21-7704-41a6-917f-5a4be3aeb8f1.png)

**Comment by cagnulein** [comment]
done @CiccioFritz79 i didn't add the icon for now, just test if it will work first.
It will be in the 2.9.39 and above

**Comment by CiccioFritz79** [comment]
Hi @cagnulein 

Works perfectly!

Thanks!
