### ISSUE TITLE
[BUG] Cadence with Garmin and Zwift

### ISSUE THREAD

**Issue by CiccioFritz79** [cagnulein/qdomyos-zwift#566]
Hi,

I have a "strange" bug: i use my Garmin ( Forerunner 245 + Run Belt), and i can connect with QZ.

The "Strange Bug" is that if Garmin sends 180 cadence to QZ, QZ display 90, and in Zwift i can see 180.

If I double up the cadence (into QZ Settings), Garmin transmits 180, QZ view 180, but Zwift display 360.

**Comment by cagnulein** [comment]
fixed in the 2.9.37 and above
Feel free to reopen this if you have any issues

**Comment by cagnulein** [comment]
Yes the setting is the one that I told you to change. Share a debug log and
I will check it. Disable the run cadence sensor setting

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle 19:36 CiccioFritz79 ***@***.***>
ha scritto:
