### ISSUE TITLE
feature request: watch and restart

### ISSUE THREAD

**Issue by rickoneeleven** [cagnulein/qdomyos-zwift#57]
had a seg fault today with pi0w and t900c, unfortunately I didn't have logging on and will catch it next time and open a new issue, but it gave me an idea

maybe we'll never eliminate all seg faults as they may be limitations of the hardware (treadmill just not great with bluetooth)

so the idea: when i had seg fault i could just re-run the script and it connected back to zwift and treadmill - so could we implement a "wrapper" that:

1. starts the script and begins an infinite while loop (i'm talking in way I understand programming in php, you'll have to convert to how to write in C 😄 ) which exits only when you press CTRL+C or close the GUI
2. it checks for speed.txt and if exists, configures the treadmill to this speed on startup
3. the while loop is constantly checking for the seg fault message
   3.1 if seg fault is found, it restarts the process, and if speed.txt is found it automatically sets the start speed to this
   3.2 if no segfault is found, it just keeps looping, checking the speed and writing to speed.txt
4. when it detects a safe shutdown - CTRL+C or GUI closed, it deletes the speed.txt and stops the script

i appreciate it wouldn't be as easy as that, but I'm just trying to give you an idea of how I'd do something similar in a much easier php 😆

**Comment by cagnulein** [comment]
I've already put a "state file" on the code. I have just to put  one or two arguments in order to setting the speed and the inclination.
Anyway, first of all, try to reproduce it and send me the log.

In these days I'm writing the GUI for android and ios, after this I will take a look at this FR.

Thanks

**Comment by cagnulein** [comment]
@rickoneeleven with this https://github.com/cagnulein/qdomyos-zwift/commit/123df9db6b78c1ac4b994d387d8bcb6eefb51dad i did the first step: if you press stop and start or if you lost and regain connection to the treadmill, speed and inclination restart from the previous value.

So this commit covers the situation where the raspberry lost the connection but doesn't segfault.

For the segfault scenario i will add 2 parameters to the executable in order to set the speed and the inclination from outside.

Could you please try this commit and tell me if everything is ok on your side? Just do a quick start/stop/start/change speed and inclination/stop and so on.
If it works well, we can move on

**Comment by rickoneeleven** [comment]
ohhh brilliant, yes - i'll pull it down and give it a test tonight :bowing_man:

**Comment by rickoneeleven** [comment]
it will have to be tomorrow night, i ended up busy tonight 👍

**Comment by rickoneeleven** [comment]
okay bro's

started program, connected to treadmill, opened zwift and it wouldn't appear 
[debug-Tue Nov 24 17_21_05 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5591914/debug-Tue.Nov.24.17_21_05.2020.log) this is common but not a big issue, i just CTRL-C, started program again and it showed up in zwift straight away and reconnected to treadmill

then onto the main event:
completed session with zero issues, so at end:

took the incline up to 10% and 4 speed
back down to 4% incline 
pressed the stop button on the treadmill (treadmill stopped)
pressed the start button on the treadmill - it started again at 4% incline and 4 speed
brought treadmill down to 1% incline and pressed stop button on treadmill - treadmill stopped
pressed start button on treadmill and it resumed at 1% incline and 4 speed

not sure if that helps? not sure if I had any disconnects during the session, if I did, I didn't notice 
[debug-Tue Nov 24 17_23_23 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5591930/debug-Tue.Nov.24.17_23_23.2020.log)

**Comment by cagnulein** [comment]
Tommorow I will add the step 2 and i will check the logs! Thanks

**Comment by cagnulein** [comment]
@rickoneeleven about the zwift issue, did you try to run this command before start the bridge

`sudo hciconfig hci0 leadv 0`

just the first time. I would like to see if, with this command, the bridge will always appear.
Ok i'm starting the 2nd step, i guess it will be ready for tonight :)

**Comment by cagnulein** [comment]
ok @rickoneeleven i completed it.
It should work like magic, anyway i would like to explain the mechanism for future documentation purposes.

The bridge, everytime it intercepts a changing on speed or inclination, it will write an XML called status.xml, with the current values.
If you press CTRL-C, this file will be deleted.
If it segs fault, this file will still on the SD.

So when you rerun the bridge, i will read the file and if it exist, i will write automatically the value on the treadmill.

The only thing you have to do is to run the bridge in a loop, so for example

`while [ 1 ]; do sudo ./qdomyos-zwift; done`

I quickly tested it on my treadmill and it seems ok.

**Comment by rickoneeleven** [comment]
ahhhh okay, so it won't run multiple instances of the program? does it notice it is already running and kill the new instance or something like that? :heart:

**Comment by cagnulein** [comment]
No, with that statement will run one session at a time. When one session ends, another session will be lunched.

**Comment by rickoneeleven** [comment]
awesome thank you, i'll get it tested tonight or possibly tomorrow night :bow: 

i've sent you a coffee thank you :heart:

**Comment by cagnulein** [comment]
wow thank you! i hope that everything is ok

**Comment by rickoneeleven** [comment]
is this okay?

git pull
cd src
qmake
make -j4

![mstsc_KfkhdyXISj](https://user-images.githubusercontent.com/8156878/100238435-1906b780-2f28-11eb-86de-d5241970136b.png)

**Comment by cagnulein** [comment]
@rickoneeleven ops, no. i complied only on windows and i didn't see this issue. give me 2 minutes and i will fix it

**Comment by cagnulein** [comment]
@rickoneeleven ok, pull it again and rebuild.

**Comment by rickoneeleven** [comment]
builds thank you

with:
while [ 1 ]; do sudo ./qdomyos-zwift; done

CTRL-C doesn't end it, just trying to get logs, but struggling to stop it lol, just going to have to reboot

**Comment by rickoneeleven** [comment]
log doesn't seem to have my CTRL-C presses, but trust me I was smashing it :laughing: 
[debug-Wed Nov 25 14_24_22 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5597279/debug-Wed.Nov.25.14_24_22.2020.log)

**Comment by rickoneeleven** [comment]
note: i don't have treadmill or zwift turned on at the moment, i was just testing remotely

**Comment by cagnulein** [comment]
yes it's absolutely normal :) i mean: when you run such a loop, when you press CTRL+C it stops the current session but it starts another one in loop :D i didn't think about it this morning :D

The solution should be simple: put a sleep 1 between zwift and done in order to catch the ctrl+c
so for example:

`while [ 1 ]; do sudo ./qdomyos-zwift; sleep 1; done`

It's ok that you don't see anything in the log, i didn't insert it into the log file, but you should see SIGINT on the screen when you press CTRL+C (i guess it will be very fast!)

**Comment by rickoneeleven** [comment]
ahhh right, even with sleep 1 I can't run CTRL+C - I'll be running forever :laughing:

**Comment by cagnulein** [comment]
maybe beucase you're testing remotely and your band is not fast enough?
anyway you can kill the bash process from another shell, there a lot of possibility 👍 

so from another shell do

`$ ps ax | grep bash`

you will see several results, take one and do

`kill -9 [pid]`

you will definetely stop it :)

anyway if you just press the ctrl+c i delete the file and you can power off the pi0w without issue. The only important this is to manage the segfault issue, and with this loop we should get it!

**Comment by rickoneeleven** [comment]
cool i'll have a play with a few options, cheers :+1:

**Comment by rickoneeleven** [comment]
okay I had a little problem 😆 

I read a few articles and tried CTRL+Z and then killing the background task but nothing would stop the script running. So I thought I'd just let it run and reboot the pi when i've finished session.

So I started it with the while loop and also ran **hciconfig hci0 leadv 0** first but zwift couldn't find the bridge, and I had no way of exiting the script to restart it so the bridge could be found 😆 

had to reboot the pi, and this time just started it without the while loop and then got a seg fault 10 minutes in and had to start it again myself manually 😆

**Comment by cagnulein** [comment]
hahahah what a bad luck! XD

didn't you try to kill the session from another shell? i think it's the easiest way. 
When you restart it after the crash, did it take back the speed and the inclination? It should...

**Comment by cagnulein** [comment]
and remember that you have to kill the bash parent process not the bridge!

**Comment by rickoneeleven** [comment]
I tried everything there is absolutely zero way to kill it, it goes into beast mode :bear:

**Comment by cagnulein** [comment]
did you try also with the kill -9 option?

**Comment by rickoneeleven** [comment]
i mean absolutely everything https://pinescore.com/111/help.gif

**Comment by cagnulein** [comment]
no! you have to kill the bash parent process! :P

**Comment by rickoneeleven** [comment]
nothing works! https://pinescore.com/111/help2.gif :laughing:

**Comment by cagnulein** [comment]
yeah right! now kill the bridge and you will be the winner!

**Comment by rickoneeleven** [comment]
after that last animation I also killed the pi bash 533 and it killed the bash window, but if you ps aux |grep domyos the program was still running!"!212e32142fewrfsvsv :smile:

**Comment by rickoneeleven** [comment]
ohh and then kill the bridge, let me try that too

**Comment by rickoneeleven** [comment]
still no - i give up, ill just restart it manually maybe without running the loop :crying_cat_face: 

https://pinescore.com/111/help3.gif

**Comment by rickoneeleven** [comment]
typo in video, but even when i went back and kill **-9**

it was still running

**Comment by rickoneeleven** [comment]
go.sh
`#!/bin/bash
while :
do
        if pgrep -x "v3" > /dev/null
        then
            echo "Running"
        else
            /home/pi/qdomyos-zwift/src/v3 -no-gui
        fi

        sleep 5
done
`

kill.sh
`#!/bin/bash
killall -9 v3 && killall -9 go.sh`

:pray: works

./go.sh to start
./kill.sh to stop

:clinking_glasses:

**Comment by rickoneeleven** [comment]
this works (was having issues formatting code in comments)
![mstsc_FGFUGXLyLH](https://user-images.githubusercontent.com/8156878/100377068-838f2480-3008-11eb-926a-fbefb1b1b5a9.jpg)

**Comment by rickoneeleven** [comment]
cat'd kill twice by mistake 😆

**Comment by cagnulein** [comment]
So now it's working? Did you "test" a segfault?

**Comment by rickoneeleven** [comment]
ones does not simply "segment" - i'll have to wait until my next run on Friday 😄

**Comment by rickoneeleven** [comment]
okaaaaaaaaaaaaaaaaaaaaaaay then

so started it today, was running at speed 9.1, inc 1% - treadmill stopped: 
[debug-Fri Nov 27 12_50_28 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5608212/debug-Fri.Nov.27.12_50_28.2020.log)

whilst I was trying to understand what had happened, as the putty session showed information still scrolling, it started up again :smile: at speed **8.9** (a little under) and inc 1%! - about 5-10 seconds afterwards
[debug-Fri Nov 27 13_22_34 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5608218/debug-Fri.Nov.27.13_22_34.2020.log)

so i may update my sleep loop from 10 to 1

**Comment by cagnulein** [comment]
great news isn't it? :) 
i also solved the 8.9-9.1 issue! pull it and build it man!

**Comment by rickoneeleven** [comment]
beautiful my friend, thank you :heart:

**Comment by cagnulein** [comment]
Side effect of this FR: now it's available for free even on android XD but i have to manage the close event 😄

**Comment by rickoneeleven** [comment]
:smile: :smile: :smile: :smile: :smile: ahhh I see, a premium feature :smile_cat: 

what is the close event?

**Comment by cagnulein** [comment]
I mean the event that happened when you close the bridge on android

**Comment by rickoneeleven** [comment]
ahhh cool

still have to start it, kill it, and start it again today to get it to appear in zwift, really weird. 

I had 
`sudo hciconfig hci0 leadv 0`
in cron startup script, unless that was too early to have it ran, about 12 hours before I tried the connection (when the pi last rebooted), maybe I need to run it just prior to starting the program?

**Comment by cagnulein** [comment]
I really don't know. I read somewhere that zwift has some logs on PC. Maybe we can find something useful inside.

In the log you sent me, the only thing that changes is the timing. I could add some delay from the connection to the treadmill and the creation of the bridge.

But first of all I have to regenerate the issue myself

**Comment by rickoneeleven** [comment]
if it helps, i saw the issue on both running zwift on my iPad **and** laptop. again it's not a super big issue, i just restart it now i have my kill script. if you open another issue log and want me to help with logs, i'll happily provide, or if you want to focus on other pressing matters that's fine to, as it's not a big issue. i just thought i'd mention it in case it was something easy to tweak 🙉

**Comment by cagnulein** [comment]
can we close this? or it's too early?

**Comment by rickoneeleven** [comment]
Yeah let's close it, I had one seg fault and it reconnected, if I have any issues that aren't quite right I'll just raise a new issue.

Thanks for implementing this! ❤️

**Comment by cagnulein** [comment]
@rickoneeleven  hi, i'm releasing the app on the Apple store, do you have an iPhone or an iPad to test it? If yes, add yourself here https://www.facebook.com/groups/1064761680643892 and write on messenger (roberto viola, i'm the administrator of that group). I will send you a free invitation for the beta testing.
Thanks

**Comment by rickoneeleven** [comment]
i have an iPad, but not facebook. i don't use the iPad for my setup anymore, just laptop and pi and to be honest, it's pretty much working perfectly 👍 

not even had a seg fault the last few times. a few things are off like, the distance on the treadmill display is always a lot higher than in game and the having to restart the app sometimes to make zwift pick up the bridge, but other than that it's perfect. 

i use it every other day now with zero stress, so thank you 😻

**Comment by cagnulein** [comment]
> so started it today, was running at speed 9.1, inc 1% - treadmill stopped:
> [debug-Fri Nov 27 12_50_28 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5608212/debug-Fri.Nov.27.12_50_28.2020.log)

while i was checking about the #54 issue i guess i solved this issue too. i mean i guess i understood why, sometimes, your t900 disconnects. i wasn't wait the poll packet and, sometimes, 2 packet will be send before receiving the answer.
Anyway, before pushing it, i will test on my treadmill tonight. If it works i think we have finally found your root crash/disconnect issue!

**Comment by rickoneeleven** [comment]
beautiful - to be fair the last few sessions i've had, it hasn't even seg faulted anyway, it seems for the most part to be pretty sweet! but look forward to this improvement too :smile:

**Comment by cagnulein** [comment]
for example: another thing that i didn't see when i looked your log the first time was that your treadmill start always to speed 1 when connects to the bridge if no saved values are avaiable.
It isn't right: my treadmill, in that scenario, stays still to speed 0. I guess it's all releated.

**Comment by rickoneeleven** [comment]
sorry to go off topic here, I don't suppose you know what technology the cheap heart rate strap that came with my treadmill uses to connect to your bridge? i assumed you were grabbing it via bluetooth (as it works) so tried to pair the heartrate strap with an andriod app to read my rate through the day, but it won't show up. and i'm starting to think maybe it's not bluetooth?

it looks like this if it helps?

![PXL_20201212_111724220](https://user-images.githubusercontent.com/8156878/101982449-e3720600-3c6b-11eb-979b-c6eadba48390.jpg)

**Comment by cagnulein** [comment]
t900c and intense run have analogic heart rate belt, so no, it's not bluetooth. but for the t900c i read the heart rate from the treadmill, don't you get it ?

**Comment by rickoneeleven** [comment]
ahhhh i see, thanks for answering. on an unrelated note, ill go and download that andriod version now and give it a test.

will update in 20 minutes or so

**Comment by cagnulein** [comment]
@rickoneeleven great! just to be sure, use this apk http://80.211.67.253:8080/android-build-1.5.1a.zip
thanks!
