### ISSUE TITLE
No PZ pop-up for class in build your power zones program peloton

### ISSUE THREAD

**Issue by genik88** [cagnulein/qdomyos-zwift#577]

**Comment by genik88** [comment]
[debug-Thu_Jan_13_22_00_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7867537/debug-Thu_Jan_13_22_00_41_2022.log)

**Comment by cagnulein** [comment]
hi @genik88 that class is not available to https://app.homefitnessbuddy.com/peloton/powerzone/
You should need to use PZP library.
I'm closing this so, it's not a QZ issue :)
Let me know if you need further information
