### ISSUE TITLE
[BUG] TOORX SRX-500 (iConsole+ latest version) metrics not updating

### ISSUE THREAD

**Issue by travicom75** [cagnulein/qdomyos-zwift#578]
**Describe the bug**
Toorx SRX-500 will connect to QDOMYOS app but is not updating metrics (always 0)
BL Device name: TOORX0015

**To Reproduce**
1. wear HR (Toorx supplied one or BL compatible)
2. power on bike
2. wait for cardio data on console screen
3. open QDOMYOS app with BL enabled
4. TOORX0015 will be connected in a while 
5. iConsole data will be greyed out (means BL connection ok..same happens when using other apps)
6. but metrics are not updating (speed, resistance, watt.., HR)
PS: if (as suggested) TOORX iConsole flag (app settings) will be enabled QDOMYOS app will never connect to console

**Expected behavior**
After connected metrics should be updating based on bike data

**Screenshots**

** Spinbike Model **
Spinbike Toorx Srx-500 with iConsole+ firmware version 1.7.37 (224): magnetic resistance are controlled by console (32 levels)
Model is already compatible with ZWIFT but power data is completely wrong, that's why I want to use app in order to try normalize power-factor data.

**Smartphone (please complete the following information):**
 - Device: Honor View10 (BKL-L09)
 - OS: Android 10
 - Version 10.0.0.179

**debug logs**
attached are following logs:
nrfconnect data
QDOMYOS debug log
screenshoots
[debug-Fri_Jan_14_10_46_54_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870888/debug-Fri_Jan_14_10_46_54_2022.log)
[debug-Fri_Jan_14_10_48_06_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870889/debug-Fri_Jan_14_10_48_06_2022.log)
[debug-Fri_Jan_14_10_51_00_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870890/debug-Fri_Jan_14_10_51_00_2022.log)
[debug-Fri_Jan_14_10_51_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870891/debug-Fri_Jan_14_10_51_41_2022.log)
[debug-Fri_Jan_14_10_54_36_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870892/debug-Fri_Jan_14_10_54_36_2022.log)
[debug-Fri_Jan_14_10_55_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870893/debug-Fri_Jan_14_10_55_49_2022.log)
[debug-Fri_Jan_14_10_59_02_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870894/debug-Fri_Jan_14_10_59_02_2022.log)
[debug-Fri_Jan_14_11_00_22_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870895/debug-Fri_Jan_14_11_00_22_2022.log)
[debug-Fri_Jan_14_11_00_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7870896/debug-Fri_Jan_14_11_00_41_2022.log)
![iConsole+ App firmware version](https://user-images.githubusercontent.com/97729676/149529554-2f3d4fa8-9d2e-4def-b791-04925136787e.jpg)
![nrfConnect_HonorView10](https://user-images.githubusercontent.com/97729676/149529557-b3a7c633-72c6-4caa-9377-b30928f5450f.jpg)
![nrfConnect_TOORX15](https://user-images.githubusercontent.com/97729676/149529561-1733f1e7-c780-48c5-ae9e-b1d3ccfa7e8e.jpg)
![QDOMYOS screenshoot](https://user-images.githubusercontent.com/97729676/149529563-c060261a-a3d3-4a98-9697-ca92b7304642.jpg)

  
**Additional context**
a. HR has to be weared and detected by console before connecting app, otherwise QDOMYOS will not connect
b. TOORX iConsole flag (app settings) must be OFF in order to have connection

**Comment by cagnulein** [comment]
ok, thanks! i will update you here!

**Comment by cagnulein** [comment]
@travicom75 done! the support it will be in the version 2.9.49 and above. I will upload this later today. Click here to join the private beta on android https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

**Comment by cagnulein** [comment]
@travicom75 did you send me an email? i don't remember

**Comment by travicom75** [comment]
> @travicom75 did you send me an email? i don't remember

@cagnulein sorry, unfortunately after few rides bikes start having issues on magnetic actuator so I have to sent back and they refund me.. So I have no more that bike..

Regards

**Comment by cagnulein** [comment]
argh so sorry @travicom75 what did you buy instead?

**Comment by travicom75** [comment]
> argh so sorry @travicom75 what did you buy instead?

@cagnulein I move to Elite Direto XR that I found on offering (connected with my old road bike) and I can only suggest it..incredible filling using ZWIFT..

**Comment by cagnulein** [comment]
@travicom75 yeah i know Elite company (is an italian one ;) ) and i'm already collaborating with them :)

**Comment by travicom75** [comment]
> @travicom75 yeah i know the Elite company (is an italian one ;) ) and i'm already collaborating with them :)

@cagnulein Yes, I also prefer ELITE since no more than 30km from where I live and trainer is able to support 24% gradient and 2200W max for a price lower than others..
