### ISSUE TITLE
Using Precor 956i treadmill connected via NPE GEM Retro

### ISSUE THREAD

**Issue by JHanc** [cagnulein/qdomyos-zwift#579]
Wondering if this app can be used to auto incline on a Precor 956i (and others) connected to Zwift by a GEM Retro device from NPE.  App detects the treadmill but doesn't go any further.  A number of debug files are attached.
[debug-Fri_Jan_14_13_40_45_2022.txt](https://github.com/cagnulein/qdomyos-zwift/files/7871387/debug-Fri_Jan_14_13_40_45_2022.txt)
[debug-Fri_Jan_14_13_41_48_2022.txt](https://github.com/cagnulein/qdomyos-zwift/files/7871388/debug-Fri_Jan_14_13_41_48_2022.txt)
[debug-Fri_Jan_14_13_43_08_2022.txt](https://github.com/cagnulein/qdomyos-zwift/files/7871389/debug-Fri_Jan_14_13_43_08_2022.txt)
[debug-Fri_Jan_14_13_40_10_2022.txt](https://github.com/cagnulein/qdomyos-zwift/files/7871390/debug-Fri_Jan_14_13_40_10_2022.txt)
.

**Comment by JHanc** [comment]
Will do, give me an hour or so.

**Comment by JHanc** [comment]
![Screenshot_20220114-162340_nRF Connect](https://user-images.githubusercontent.com/2051260/149552284-e6206bfe-c169-4f87-9590-4d6a603ea674.jpg)
![Screenshot_20220114-162346_nRF Connect](https://user-images.githubusercontent.com/2051260/149552288-e0d297b1-363e-4837-9dc9-06077223920c.jpg)
![Screenshot_20220114-162406_nRF Connect](https://user-images.githubusercontent.com/2051260/149552290-20013254-e6b2-4e13-9ddf-3ab6cd62c5ff.jpg)
![Screenshot_20220114-162411_nRF Connect](https://user-images.githubusercontent.com/2051260/149552294-349d66c5-829d-4039-8020-32250aabcb82.jpg)
![Screenshot_20220114-162443_nRF Connect](https://user-images.githubusercontent.com/2051260/149552296-75332768-c8de-44e3-879f-f002d90ecf29.jpg)

**Comment by cagnulein** [comment]
@JHanc Does this adapter have an app? If so are you able to change the incline through the app?

**Comment by JHanc** [comment]
No app but auto incline worked briefly using Runcline but then stopped
without any changes to the GEM module or the treadmill so it can definitely
change the incline of the treadmill yes.

**Comment by cagnulein** [comment]
@JHanc Do you have any documentation about it?

**Comment by JHanc** [comment]
Unfortunately not.  I can put you in touch with someone at NPE if that
would help?

**Comment by cagnulein** [comment]
@JHanc Is this one https://fccid.io/PADGEMRET0101/User-Manual/User-manual-2941434 ? If so there are some app. Could you try them?

**Comment by JHanc** [comment]
That's the one.  I'll take a look although I'm fairly sure the app is a one
way thing and doesn't send data to the GEM.  I'll have a look through the
conversation I had with NPE last year.

**Comment by cagnulein** [comment]
Ok @JHanc if you want put me in CC with them and I will ask you them some questions

**Comment by seaweedsucker** [comment]
Hi, aplogise for dropping in on this tread but I have also been trying (hoping) to get my treadmill (LifeFitness 95Ti) connected  via GEM RETRO to auto incline. I have previously contacted NPE and a Tim Eskew advised

"Thank you for contacting us regarding our GEM RETRO. I am glad to hear it is working well for you.
In regards to receiving incline, yes, the GEM RETRO is able to receive incline information from apps that support sending incline to the GEM RETRO and pass it along to the console and pass this on to the console through the CSAFE port. The app would also need to support requesting control over the Bluetooth connection. Third, the console would also then need to allow for control operation over the CSAFE port.
So, in short, yes, the GEM RETRO does allow/pass through incline/control requests to consoles over the CSAFE port, however, the console and app being used would need to also support this functionality.
Let me know if you have additional questions."

I have also contacted LifeFitness and asked whether the CSAFE port on this treadmill is able to receive incline date and adjust accordingly. LifeFitness advised 
"We checked with software team for this enquiry.
For safety reasons, the Life Fitness treadmill will not allow changes from 3rd party devices through CSAFE. 
This are no Life Fitness treadmills available with this option.
Thank you for your understanding."

I would love to be able to get my treadmill to be able to auto incine. Please let me know if I you need any additional info.

**Comment by cagnulein** [comment]
@seaweedsucker From the answer of Lifefitness it seems to me that they had disabled this function by hardware. But of course we can try

**Comment by cagnulein** [comment]
Also @seaweedsucker did you try the app that I mentioned before?

**Comment by seaweedsucker** [comment]
Confirm JHanc responce that you can recieve data but I do not believe that you are able to send data to the GEM Retro module using the Wahoo app

**Comment by cagnulein** [comment]
@seaweedsucker Ok I will try to send Speed and inclination data as a standard Bluetooth. Let's see if it will work, I will update you when I will finish it

**Comment by cagnulein** [comment]
@JHanc @seaweedsucker with the informations in my hands i tried to add it. It will be in the version 2.9.49 and above that i'm uploading today. If you aren't in the beta, please send me a email to roberto.viola83 at gmail.com indicating this issue and if you're on android or ios.
Thanks

**Comment by cagnulein** [comment]
@JHanc @seaweedsucker any news?

**Comment by seaweedsucker** [comment]
Sorry I am away at the moment and unable to test. I am looking forward to testing when I get back on Mon 30 Jan and give you an updateOn 20 Jan 2022 22:21, Roberto Viola ***@***.***> wrote:
@JHanc @seaweedsucker any news?

**Comment by JHanc** [comment]
Hi Roberto,

I've also been away but have just emailed requesting beta access so I can
test.

Best regards,
Jon.

**Comment by seaweedsucker** [comment]
Robert,

Are you able to  provide version 2.9.49 (or higher) to enable me to test my LifeFitness 95Ti treadmill fitted with NPE GEM Retro

 

Cheers

Stephen

**Comment by cagnulein** [comment]
@seaweedsucker send me an email to Roberto.viola83 at gmail.com indicating this ticket and if you're on iOS or Android

**Comment by cagnulein** [comment]
@seaweedsucker did you send me an email? i don't remember

**Comment by seaweedsucker** [comment]
Robert,

Yes I sent an email to Roberto.viola83 at gmail.com indicating that I was having difficulties connecting my LifeFitness 95Ti treadmill fitted with NPE GEM Retro. 

I have tested version 2.10.18 but while my LifeFitness 95Ti treadmill fitted with NPE GEM Retro now connects to qdomyos-zwift, I am unable to get any readings (NO speed or incline indications).

I have been trying to find what I am doing wrong before annoying you (as I believe I may be doing something embarrassing). I have played with the settings but still can’t get any readings.

I have attached the latest debug logs.

Hopefully you are able to uncover my problem

 

Cheers

Stephen

**Comment by cagnulein** [comment]
@seaweedsucker i can't see the attachment, you have to attach from the github page. Let me know

**Comment by seaweedsucker** [comment]
Files attached

[debug-Sun_Feb_6_14_20_54_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8009857/debug-Sun_Feb_6_14_20_54_2022.log)
[debug-Sun_Feb_6_14_20_05_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8009858/debug-Sun_Feb_6_14_20_05_2022.log)
[debug-Sun_Feb_6_14_19_20_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8009859/debug-Sun_Feb_6_14_19_20_2022.log)
[debug-Sun_Feb_6_14_17_32_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8009864/debug-Sun_Feb_6_14_17_32_2022.log)

**Comment by cagnulein** [comment]
@seaweedsucker your NPE seems different from the @JHanc 's one. There is no FTMS service in the log. Are you able to connect it to zwift? I guess not. Could you provide a nrfconnect screenshot about it? Could you please ask NPE to send us the protocol of the custom communication that they have implemented?

**Comment by JHanc** [comment]
Hi both,

Sorry, been busy with other things.  My GEM has a different firmware to the
one sold in the store.  The treadmill now connects to the app and can be
paired with Zwift but I don't get any incline changes.

Best regards,
Jon.

**Comment by cagnulein** [comment]
@JHanc did you try the beta of QZ to double check if you're able to change the incline with the incline tile?

**Comment by JHanc** [comment]
No but I will give it a try later.

**Comment by seaweedsucker** [comment]
Hi, 
Please find below an update on my attempt to get QZ (version 2.10.20) running with my treadmill (LifeFitness 95Ti treadmill fitted with NPE GEM Retro).

Connected QZ (running on my Redmi Note 9 Pro) to my treadmill
Started Zwift (on my PC Windows 11)
In bike mode, connected my Redmi Note 9 as power, cadence and controllable
Joined Zwift in bike mode
Joined Run meetup (previously organised)
When in Run Meetup, connected speed with my Redmi Note 9 Pro

While I was able to connect my Redmi Note 9 Pro running QZ to Zwift as a controllable, my avatar did not move or incline did not change.

Attached are  the log files from above test
[debug-Mon_Feb_7_13_00_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8012003/debug-Mon_Feb_7_13_00_13_2022.log)
[debug-Mon_Feb_7_12_39_27_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8012004/debug-Mon_Feb_7_12_39_27_2022.log)
[debug-Mon_Feb_7_12_50_54_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8012005/debug-Mon_Feb_7_12_50_54_2022.log)
[debug-Mon_Feb_7_12_36_20_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8012006/debug-Mon_Feb_7_12_36_20_2022.log)
.

**Comment by cagnulein** [comment]
yes @seaweedsucker as i told you your NPE has a completely custom protocol. it's not implemented so we can manage this in different ways
1) try to upgrade the firmware to the @JHanc one
2) try to contact NPE about the custom protocol
3) I can add this protocol with reverse engineering but i can't control speed and incline because i need an app that can actually control speed and incline with your NPE

Let me know

**Comment by seaweedsucker** [comment]
Roberto, an update on my progress
1. Contacted NPE regarding the latest vesion for the GEM Retro and whether it is possible to convey auto incline commands to my treadmill (LifeFitness 95Ti) connected via the NPE GEM Retro
2. NPE advised the latest firmware for my GEM Retro is v1.12. I have updated to this version. 
3. NPE also advised that the GEM RETRO can support sending incline control commands to a console through a compatible app. 
4. Contacted LifeFitness regarding whether the LifeFitness 95Ti treadmill is able to receive incline information from the CSAFE port and thus control the incline of the treadmill.
5. LifeFitness advised that for safety reasons, the LifeFitness treadmill will not allow changes from 3rd party devices through CSAFE.
Note: QZ app version - 2.10.30
Since upgarding my GEM Retro to v1.12, I am now able to connect my treadmill using the QZ app with Zwift and the QZ app will display speed and incline. I have connect to Zwift using the create Run meetup work around. The incline does NOT auto incline but will display manual changes to incline (and speed). The incline triangle does blink. Please see attached debug log.
[debug-Tue_Feb_22_14_22_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8113593/debug-Tue_Feb_22_14_22_49_2022.log)
Cheers
Stephen

**Comment by cagnulein** [comment]
@seaweedsucker thanks! ok so i guess we are on an end road. i mean if life fitness blocked this on firmware we can't bypass this by bluetooth. the only way is bypassing via hardware as we did in another ticket

**Comment by seaweedsucker** [comment]
Roberto,
So are you proposing to utilise a raspi to independently control the incline on the treadmill (as directed by Zwift).
I have no experience with raspi but would be willing to learn if you are able to provide some guidance.
Note: the reply from LifeFitness regarding whether the 95Ti treadmill is able to receive incline information from the CSAFE port advised that they would not allow 3rd party apps to control incline but they did not say whether LifeFitness had a native app that can control incline. However, I do not know of any native LifeFitness app for the 95Ti treadmill.
Please let me know if you need any further info
Cheers
Stephen

**Comment by cagnulein** [comment]
@seaweedsucker yes with a raspberry and some relays you're able to control speed and incline on your treadmill. you need to be a little geeky to do so because some electrics stuff are involved. I can't guide you in details because every treadmill is different unfortunately and this will cause the warranty to stop of course 

About the csafe if we find good documentation we can go on that, otherwise i will go with a raspberry solution

**Comment by seaweedsucker** [comment]
Roberto, 
Sorry about the delay but I would like to pursue the option of utilising a raspi to independently control the incline on the treadmill (as directed by Zwift). I happy (and confident) to be able to connect a raspberry and some relays into my treadmill (LifeFitness 95Ti) to control speed and incline but would need your help with the programming of the raspi. (When I did my trade training, were we taught valve technology)
I have the Service Manual for my treadmill which I have included. 
I am not sure what information you need or what I can do to help at this stage. Please let me know what I can do to help
[lifefitness97ti95ti93t97te95te Customer Support Service Manual.pdf](https://github.com/cagnulein/qdomyos-zwift/files/8240945/lifefitness97ti95ti93t97te95te.Customer.Support.Service.Manual.pdf)
p

**Comment by cagnulein** [comment]
Hi @seaweedsucker first of all you have to connect the relays to your buttons of the treadmill, in this way you should be able to command statically your treadmill. After that we can use QZ to command the relays.
Of course you need to sold some wires from the relays to the buttons
