### ISSUE TITLE
[BUG]Virtufit etappe 2.0 I no auto resistance

### ISSUE THREAD

**Issue by Torstenmackenzie** [cagnulein/qdomyos-zwift#580]
**Describe the bug**
no auto resistance

as you recommended, it does work in kinomaps.
made y phone developer and made a bug report:

with google pixel 3a. you can find the file attached, hope i did  this right.

[bugreport-sargo-SQ1A.211205.008-2022-01-15-12-43-05 (1).zip](https://github.com/cagnulein/qdomyos-zwift/files/7874926/bugreport-sargo-SQ1A.211205.008-2022-01-15-12-43-05.1.zip)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7874953/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@Torstenmackenzie ok i added the support. (new setting under the fitplus bike section for your bike). In the log, anyway, there is only some resistance changes (from 11 to 17) so in order to add the force of all the levels, i need a full log where you can record all the resistance changes. Are you able to do so? If you want, meanwhile, i can build and send you this version. Let me know

**Comment by Torstenmackenzie** [comment]
Hi, so if I get this right. I have to ride on all resistance changes on kinomap and send u a new report ? I can do that in my break( around 12)

**Comment by Torstenmackenzie** [comment]
Oh, can I shift manually ?

**Comment by cagnulein** [comment]
> Oh, can I shift manually ?

if you can shift it manually FROM THE APP, yes this should be fine. Otherwise you have to do a workout that contains all the resistance changes

**Comment by Torstenmackenzie** [comment]
I can shift in ap by changing diffuculy from 0 to 150% ?

**Comment by cagnulein** [comment]
@Torstenmackenzie yes it could be a nice workaroud :) do  you see the resistance on the console of your bike? if so just be sure to get all the resistance levels! ;)

**Comment by Torstenmackenzie** [comment]
Unfortunately I do not.
I just did a bit of mont ventoux at 5% climb on 200% diffuculty. I try to do every climb % on every difficulty % for  5 seconds. Would that be ok?

**Comment by cagnulein** [comment]
@Torstenmackenzie i guess it's the near thing to the perfection :P

**Comment by Torstenmackenzie** [comment]
[bugreport-sargo-SQ1A.211205.008-2022-01-18-13-01-16.zip](https://github.com/cagnulein/qdomyos-zwift/files/7888875/bugreport-sargo-SQ1A.211205.008-2022-01-18-13-01-16.zip)

hi, attached the new bug rapport, i went as far as 10% uphill with difficulty on 200% hope this is enough, because i almost died :-D

**Comment by cagnulein** [comment]
@Torstenmackenzie how many resistance levels does it have? 24 is possible?

**Comment by Torstenmackenzie** [comment]
Exactly 24 indeed

**Comment by Torstenmackenzie** [comment]
Awesome!

**Comment by cagnulein** [comment]
@Torstenmackenzie check messenger, i need your gmail account for the beta

**Comment by kminkov** [comment]
Hi, I am using a virtufit bike but for some reason cannot make ERG mode to run. Went through the issues here but couldn't find what exactly settings I need to enable. I have enabled fitplus-> virtufit ettape 2.0 but still no success. Currently I am trying to run it with the trainerDay app, but tried also with zwift without success. Can you help on how should I set it in?

**Comment by cagnulein** [comment]
Which version of qz are you using?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 1 feb 2025 alle 15:26 kminkov ***@***.***> ha
scritto:
