### ISSUE TITLE
[REQ] Add to WebSocket API Elevation Control

### ISSUE THREAD

**Issue by gungun974** [cagnulein/qdomyos-zwift#581]
**Is your feature request related to a problem? Please describe.**
I manage to make works the WebSocket (after a long adventure) and now I discover than I can see on my treadmill the elevation but I can't control it like speed xD

**Describe the solution you'd like**
Add `set_elevation` like `set_speed` in `templateinfosenderbuilder.cpp`

**Comment by cagnulein** [comment]
@p3g4asus

**Comment by p3g4asus** [comment]
I will have a look on this ASAP.

**Comment by gungun974** [comment]
@p3g4asus don't bother with that i will make my own pull request for that.
I already write on my own the "onSetElevation" ^^

**Comment by cagnulein** [comment]
@p3g4asus you have concurrency now! :D

**Comment by gungun974** [comment]
> @p3g4asus don't bother with that i will make my own pull request for that. I already write on my own the "onSetElevation" ^^

Technically I can already publish the first fix but I want to take care of issue #582 at the same time and a third missing thing I discover and forgot to talk xD

**Comment by p3g4asus** [comment]
@gungun974 setspeed was already there. Wasn't it?

**Comment by gungun974** [comment]
@p3g4asus `setspeed` is for speed. I talk about an action like `setelevation` I already implemented in my code.

**Comment by p3g4asus** [comment]
@gungun974 @cagnulein both commands are already supported. They are setspeed and setresistance

**Comment by gungun974** [comment]
Ah woops Indeed...
Sorry for this issue.
