### ISSUE TITLE
[REQ] Add to WebSocket API Timer Control 

### ISSUE THREAD

**Issue by gungun974** [cagnulein/qdomyos-zwift#582]
**Is your feature request related to a problem? Please describe.**
In the GUI I can start and stop (and reset) the timer.
However in the api I do not control it and I am forced once the bluetooth connection is made to start immediately.

**Describe the solution you'd like**
Add `start_timer` to start the timer in `templateinfosenderbuilder.cpp`
Add `stop_timer` to stop the timer in `templateinfosenderbuilder.cpp`
Add `reset_timer` to reset the timer in `templateinfosenderbuilder.cpp`
Add maybe if it's not to hard `set_timer` to set timer time in seconds in `templateinfosenderbuilder.cpp`

**Comment by cagnulein** [comment]
@p3g4asus if you want take care of this :)
