### ISSUE TITLE
[BUG/QOL] Timer screen on T900C refresh in more than 3s

### ISSUE THREAD

**Issue by gungun974** [cagnulein/qdomyos-zwift#583]
**Describe the bug**
On my T900C. When i connect the program and start the timer. The timer counter on my treadmill take more than 1s to refresh the screen.
So i got :
1s
3s
5s
A little disturbing even if not very serious.

**To Reproduce**
Connect qdomyos on a T900C and start.

**Expected behavior**
Screen timer refresh in less than 1s

**Desktop (please complete the following information):**
 - OS: linux
 - Version latest

**Comment by cagnulein** [comment]
yes i know and the issue it's that i created the logic "relaxed" because some treadmill went mad with sending the metric every seconds. If you want you can play with it if you can find a better solution (the problem is that maybe it will work for you but not for everybody, so i guess we can't use the solution in production).

You can check the very first issue here on github about this

**Comment by gungun974** [comment]
@cagnulein So if sending Data make crash Treadmills. Why not add an option to make us the user to choose which speed we want try and hopes that will works ourselves ?

**Comment by cagnulein** [comment]
@gungun974 there is already in the parameters of the linux version i guess. I never ported to QML because at the end, it's not the end of the world :)
But now that we have you, you can start to do some PRs :)

**Comment by gungun974** [comment]
@cagnulein Oh what is the name of the parameter in the config file to test it ?

**Comment by cagnulein** [comment]
@gungun974 pollDeviceTime

**Comment by cagnulein** [comment]
@gungun974 hi, how are you? did you try something on this?

**Comment by gungun974** [comment]
> @gungun974 hi, how are you? did you try something on this?
Oh Hoi !

The `pollDeviceTime` config do nothing to the time of the refresh screen.

After now I don't really need anymore this cause I prefer use the new WebSocketAPI with an Ipad for the screen cause I hate that i can't turn off the screen of my treadmill xD

Soooo for this issue is not really anymore a problem for me so feel free to close it if you want.

**Comment by cagnulein** [comment]
ok, thanks for the update :)
