### ISSUE TITLE
ZWO workout file with treadmill not working

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#589]
Hi, I tried to use ZWO workout file with treadmill, but its not working, here is workout example:
[workout-2256U-economy.zip](https://github.com/cagnulein/qdomyos-zwift/files/7883851/workout-2256U-economy.zip)

_Originally posted by @nieko-nera in https://github.com/cagnulein/qdomyos-zwift/discussions/562#discussioncomment-1985231_

**Comment by cagnulein** [comment]
@nieko-nera

`<SteadyState Duration="300" pace="2" Power="0.6667">
      <textevent message="07:34/km - Warm Up" duration="60"/>
    </SteadyState>`

The issue is the ZWO contains power or pace=2 (i don't know what this means) as a request for treadmill. 
So we have to 2 way to solve this:
1) transform power to speed (i could do it using your ftp value)
2) using the speed reported in the textevent message (maybe this one is the safest one)

What do you think?

**Comment by nieko-nera** [comment]
- I think option 1 is better. Because textevent is just for information, and maybe some time it could not contain pace (workouts is generated by TrainAsONE service).  I think that speed is calculated from this tag ("FTP") : `<thresholdSecPerKm>302</thresholdSecPerKm>` 302 / 0.6667 = 453 sec for 1 km -> 07:33/km
- Also some workouts don't have tag `<durationType>time</durationType>`, then its not time based, but distance based.
- And some workouts contains workout tag `FreeRide` with duration but not speed, maybe in this step leave last speed, and I change it manually

Here is two more examples 
[zwo_workouts.zip](https://github.com/cagnulein/qdomyos-zwift/files/7887537/zwo_workouts.zip)

**Comment by cagnulein** [comment]
@nieko-nera done! are you able to test yourself or do you need a beta version? if so for which platform?

**Comment by nieko-nera** [comment]
Please send me beta for iOS

**Comment by cagnulein** [comment]
ok @nieko-nera as a reminder, write me an email to roberto.viola83 at gmail.com indicating #589
thanks, i will build it later today or tomorrow

**Comment by nieko-nera** [comment]
``Still no iOS version, so I tested on Android.

- If workout file don't have this tag `<durationType>time</durationType>`, when workout is distance based, not time. Then this tag `<FreeRide Duration="3200">` is 3200 meters not second, `<SteadyState Duration="200" pace="2" Power="0.6667">` is 200 meters, not seconds. If it possible to make this way. 

- Treadmill speed control works, but for some reason one speed was not correct.

  - "08:48/km - Warm Up" speed was 8:49 this is ok

  - "07:55/km - Easy" and here speed was 8:00, maybe its possible make it more accurate? 
[debug-Wed_Jan_19_17_46_07_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7898648/debug-Wed_Jan_19_17_46_07_2022.log)


```<workout_file>
  <author>TrainAsONE</author>
  <category>TrainAsONE Workouts</category>
  <durationType>time</durationType>
  <name>W1134Q 6 Min Assessment</name>
  <sportType>run</sportType>
  <subcategory>2022-01</subcategory>
  <tags>
  <tag name="6 Min Assessment"/>
  <tag name="Hard Assessment"/>
  </tags>
  <thresholdSecPerKm>351</thresholdSecPerKm>
  <workout>
    <SteadyState Duration="21" pace="2" Power="0.6667">
      <textevent message="08:48/km - Warm Up" duration="60"/>
    </SteadyState>
    <SteadyState Duration="22" pace="2" Power="0.7405">
      <textevent message="07:55/km - Easy" duration="60"/>
    </SteadyState>
    <SteadyState Duration="23" pace="2" Power="0.6667">
      <textevent message="08:48/km - Preparation" duration="60"/>
    </SteadyState>
    <FreeRide Duration="24">
      <textevent message="Extreme" duration="60"/>
    </FreeRide>
    <FreeRide Duration="25">
      <textevent message="Recovery" duration="60"/>
    </FreeRide>
    <SteadyState Duration="26" pace="2" Power="0.7405">
      <textevent message="07:55/km - Easy" duration="60"/>
    </SteadyState>
  </workout>
</workout_file>

**Comment by nieko-nera** [comment]
> the problem with the last one is that the 7.59487 has been converted to your treadmill to 7.5 because it can have only 1 decimal. Maybe you need a 7.6 in this case? so do you suggest to use a better round formula not a truncation?
> 

Yes round to next decimal, I think little bit faster is better than slower :)

> about the duration field on the free ride: i don't like it. I mean how can i identify _for sure_ if it's a time or a distance? there is a specification about zwo that we can follow? my idea is that every app that creates these files could have different implementations. Could you help me finding a specification about this file format?
> 
> Thanks

This is what I find https://github.com/h4l/zwift-workout-file-reference/blob/master/zwift_workout_file_tag_reference.md
If I have same workout loaded to Zwift but one without `<durationType>time</durationType>` what I see:

- with `<durationType>time</durationType>`
<img width="418" alt="test1" src="https://user-images.githubusercontent.com/10880681/150184872-524f87cd-2496-41ff-8711-143dedae7b89.PNG">

- without `<durationType>time</durationType>`
<img width="432" alt="test2" src="https://user-images.githubusercontent.com/10880681/150184957-fd805563-d7b3-4c83-92e2-eb81e8af0914.PNG">

```<workout_file>
  <author>TrainAsONE</author>
  <category>TrainAsONE Workouts</category>
  <durationType>time</durationType>              <------------------ This line
  <name>test1</name>
  <sportType>run</sportType>
  <subcategory>2022-01</subcategory>
  <tags>
  <tag name="Economy"/>
  <tag name="Easy Workout"/>
  </tags>
  <thresholdSecPerKm>324</thresholdSecPerKm>
  <workout>
    <SteadyState Duration="1000" pace="2" Power="0.6667">
      <textevent message="08:07/km - Warm Up" duration="60"/>
    </SteadyState>
    <SteadyState Duration="2000" pace="2" Power="0.7407">
      <textevent message="07:19/km - Easy" duration="60"/>
    </SteadyState>
  </workout>
</workout_file>

**Comment by cagnulein** [comment]
@nieko-nera Great! I didn't noticed the durationtype field. I will implement this tomorrow 
Thanks for the research!

**Comment by cagnulein** [comment]
#320 this one is releated too

**Comment by cagnulein** [comment]
unfortunately @nieko-nera the distance thing will break the compatibility with the homefitnessbuddy. They don't use that tag.
Check this https://app.homefitnessbuddy.com/peloton/powerzone/zwift_export.php?class_id=553
Maybe we should contact them to add it?

**Comment by nieko-nera** [comment]
homefitnessbuddy workouts is for bike? It has tag `<sportType>bike</sportType>` and treadmill workouts has tag `<sportType>run</sportType>`

**Comment by cagnulein** [comment]
done @nieko-nera it will be in the 2.10.1 version and above. Since a lot of code has been writter for this, could you please double check the commits?

**Comment by cagnulein** [comment]
Got the issue, it's a stupid thing. I'm gonna fix it today. And yes about the time to next, good idea. Thanks

**Comment by cagnulein** [comment]
@nieko-nera i don't see in your log the stop of the treadmill. is it the right log? could you please regenerate it? Thanks

**Comment by nieko-nera** [comment]
New log 
[debug-Thu_Jan_20_15_20_52_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7905470/debug-Thu_Jan_20_15_20_52_2022.log)

And workout file. 

````<workout_file>
  <author>TrainAsONE</author>
  <category>TrainAsONE Workouts</category>
  <name>W2254S 3.2K Assessment</name>
  <sportType>run</sportType>
  <subcategory>2022-01</subcategory>
  <tags>
  <tag name="3.2K Assessment"/>
  <tag name="Hard Assessment"/>
  </tags>
  <thresholdSecPerKm>298</thresholdSecPerKm>
  <workout>
    <SteadyState Duration="30" pace="2" Power="0.6667">
      <textevent message="07:27/km - Warm Up" duration="60"/>
    </SteadyState>
    <SteadyState Duration="30" pace="2" Power="0.7">
      <textevent message="07:27/km - Preparation" duration="60"/>
    </SteadyState>
    <FreeRide Duration="40">
      <textevent message="Extreme" duration="60"/>
    </FreeRide>
  </workout>
</workout_file>

**Comment by cagnulein** [comment]
@nieko-nera i guess i fixed both. Could you try to pull and build it again? Thanks!

**Comment by nieko-nera** [comment]
I think that everything works good now. Thank You! 🥇

**Comment by cagnulein** [comment]
Great!

**Comment by DenimDaisy26** [comment]
Roberto asked me to post my question here.
I'm wanting to create some interval workouts adjusting pace and incline.  
I won't be using Zwift - I'll just have a Peloton class running to listen to the music.
1.  How do I set my pace if not using Zwift.  I've read through the post, would it be thresholdSecPerMile?
2. Can I set an incline in my intervals?

**Comment by cagnulein** [comment]
@nieko-nera could you help @DenimDaisy26  ? Thanks!
also @DenimDaisy26 you will need the beta, because i just added this in the latest beta version.

**Comment by DenimDaisy26** [comment]
> @nieko-nera could you help @DenimDaisy26 ? Thanks! also @DenimDaisy26 you will need the beta, because i just added this in the latest beta version.

I think I've got the beta for iOS?  2.9.47

**Comment by cagnulein** [comment]
@DenimDaisy26 you need a new one, send me an email to roberto.viola83@gmail.com

**Comment by nieko-nera** [comment]
@DenimDaisy26 if not using Zwift you don't need to use ZWO workout files, just create simple XML workout, here is example:
```
<?xml version="1.0" encoding="UTF-8"?>
<rows>
	<row duration="00:01:00" speed="5" inclination="0" forcespeed="1"/>
	<row duration="00:05:00" speed="8" inclination="0" forcespeed="1"/>
        <row duration="00:25:00" zonehr="2" fanspeed="1" maxspeed="10" looptimehr="10"/>
        <row duration="00:05:00" speed="7.5" inclination="0" forcespeed="1"/>
	<row duration="00:02:00" speed="5" inclination="0" forcespeed="1"/>
	<row duration="00:00:01" speed="2" inclination="0" forcespeed="1"/>
</rows>

**Comment by cagnulein** [comment]
@DenimDaisy26 the speed in the xml file are in km/h

**Comment by nieko-nera** [comment]
Also don't forget to disable "Training Program Random Options" in settings. @cagnulein maybe you can do if loading workout file, automatically disable that option?

**Comment by DenimDaisy26** [comment]
Thanks!  I can do the calculations to convert my mph to kmh.  I'll set it up and give it a try once I get the updated beta.  Thanks again!

**Comment by cagnulein** [comment]
@DenimDaisy26 if you use the XML you can already try without the beta :) the beta is only for the ZWO file

**Comment by DenimDaisy26** [comment]
Thanks!  It worked!!!!
