### ISSUE TITLE
[REQ] Healthrider h70t 

### ISSUE THREAD

**Issue by JCanhan** [cagnulein/qdomyos-zwift#590]
https://user-images.githubusercontent.com/97910790/149821353-3e20b1b6-d2bd-4551-ae6e-067bbb47a138.MP4

https://user-images.githubusercontent.com/97910790/149821381-d8299c39-dae1-4edd-8943-34468136bdd4.MP4

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
@p3g4asus i guess this is a fitshow treadmill. Do you know an app that works with this just to double confirm my idea? Thanks

**Comment by cagnulein** [comment]
@JCanhan done, remember me to send you the new beta version for iOS later today

**Comment by cagnulein** [comment]
#600
