### ISSUE TITLE
[BUG] Unable to control speed/incline on NordicTrack T6.5S 

### ISSUE THREAD

**Issue by hoveeman** [cagnulein/qdomyos-zwift#592]
**Describe the bug**
While using QZ 2.9 on an iPad, it will successfully connect to the Nordictrack T6.5s treadmill showing all of the real-time stats. However, pressing on the + or - in the speed and incline tiles does not control the treadmill. I verified the treadmill can be controlled over bluetooth using the iFit application. 

Please find debug log and screenshots of NRF Connect attached.

**Expected behavior**
Pressing + or - in the speed or incline tile will control the treadmills speed and incline. Once this will successfully control the speed and incline, this will help enable auto-follow speed and incline for other applications like Zwift and Peloton.

**Smartphone (please complete the following information):**
 - Device: [iPad Pro (10.5 inch)]
 - OS: [iOS 15.2.1]

**Debug log**
[debug-Wed_Jan_19_13_23_50_2022 2.log](https://github.com/cagnulein/qdomyos-zwift/files/7900370/debug-Wed_Jan_19_13_23_50_2022.2.log)

![IMG_0348](https://user-images.githubusercontent.com/18269595/150208707-bc5bea74-6e27-4f14-896f-73ae9fa7b4b6.png)
![IMG_0349](https://user-images.githubusercontent.com/18269595/150208708-a2f6bda2-bbcc-49c4-a0ee-0c2ac06badcf.png)
![IMG_0350](https://user-images.githubusercontent.com/18269595/150208710-4281e629-9227-47d8-b894-a7302ce01175.png)

**Comment by cagnulein** [comment]
@hoveeman could you please send me a debug log where you pressed the plus button of speed and of the incline tile? also, in case, do you have an android device to collect some log about how the ifit controls you treadmill? i guess you treadmill has a different protocol from the one already managed in QZ
Let me know

**Comment by hoveeman** [comment]
Thank you @cagnulein. Please find a debug log with me pressing the + and - in the tiles for speed and inclination.

I also did a full android debug while using iFit and controlling the treadmill with the android device. Those debug files are attached as well.

Apologies for not including those from the start. Thank you
[debug-Thu_Jan_20_06_57_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7905589/debug-Thu_Jan_20_06_57_03_2022.log)
!
[bugreport-d1que-RP1A.200720.012-2022-01-20-08-25-50.zip](https://github.com/cagnulein/qdomyos-zwift/files/7905591/bugreport-d1que-RP1A.200720.012-2022-01-20-08-25-50.zip)

**Comment by cagnulein** [comment]
@hoveeman thanks. in this log i saw that you first "burst" on inclination plus doesn't change the inclination. But the second burst did, infact i saw the inclination changing from to 0 to 1. Probably because the treadmill needs some moment to change it. Can you confirm me this?

**Comment by hoveeman** [comment]
@cagnulein I had pressed the + a few times in QZ and nothing adjusted, so I hit the physical button for speed increase on the treadmill to make sure the speed actually increased and was represented appropriately in QZ. 

So that increase was a manual increase from the treadmill and not from the QZ application.

**Comment by cagnulein** [comment]
@hoveeman done! send me an email to roberto.viola83@gmail.com adding this ticket in the subject line also indicating if you're on ios or android.
When you will receive this version remember to add the new setting called "Nordictrack T6.5S" leaving the "Nordictrack 10" enabled.
Let me know

**Comment by hoveeman** [comment]
Email sent! Thank you for everything! Excited to try it out!

**Comment by hoveeman** [comment]
Thanks @cagnulein! I tried out the update this morning, however it was not able to control incline or speed. I made sure to turn on Nortictrack T6.5S and force quit the app and loaded it again. It is still able to read the stats from the treadmill, but the + and - did not work. Attached is a debug log of my testing. 

[debug-Sat_Jan_22_09_38_17_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7918568/debug-Sat_Jan_22_09_38_17_2022.log)

Steps in the debug log: I started the treadmill and manually adjusted speed to 1.5 and incline to 2.0 on the physical treadmill buttons. I then pressed + and - for speed and incline in QZ and the treadmill did not adjust. Really appreciate you looking at this! 

![IMG_0357](https://user-images.githubusercontent.com/18269595/150643299-b161ce81-af65-4a9b-b0d3-48065f9d901a.PNG)

**Comment by cagnulein** [comment]
@hoveeman as you can see in the last commit I did a lot of changes for your treadmill. So first of all disable now the Nordictrack 10 setting, leaving only the T6.5S setting on. Also send me an email again as a reminder for the new beta. I hope it will work but probably we need other serveral versions to trim all out.
Let me know

**Comment by hoveeman** [comment]
@cagnulein, Thanks! I disabled the Nordictrack 10 and then restarted the app. After QZ connected, I manually set the speed to 1.5 and inclination to 1.0 on the treadmill. I then hit the + and - from QZ in speed and inclination and nothing adjusted. It should also be noted that all the stats displayed in QZ while Nordictrack 10 is disabled are all incorrect numbers. Like 606.7 for inclination. Stats are correct when Nordictrack 10 is enabled.

Debug of steps above:
[debug-Mon_Jan_24_06_17_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7925125/debug-Mon_Jan_24_06_17_50_2022.log)

Screenshot of stats with Nordictrack 10 Disabled
![IMG_0363](https://user-images.githubusercontent.com/18269595/150775076-d4c4ffb3-9ea0-462a-8bb6-0732884f1f4b.PNG)

**Comment by cagnulein** [comment]
@hoveeman I mean in the new version :) send me the email :)

**Comment by hoveeman** [comment]
LOL my bad... It's early... ;) 

Email sent!

**Comment by hoveeman** [comment]
@cagnulein It works! Great work!!!

I was able to manually adjust speed and incline from the treadmill and then I tried adjusting speed and Incline in QZ. That worked successfully! I noticed that incline adjusted by 0.5 which is the same as the treadmill's up and down. However, the speed + and - adjusted by 0.3. Is that typical for the adjustment from the app? Is that related to conversion of Metric to Imperial? I was expecting a 0.1 adjustment for + and - on speed that would match the buttons on the treadmill. When adjusting from QZ at 0.3 increments, it will put the speed at strange values that the user may not be used to running at. This may not matter at all, but was just curious. 

One question I have with that speed change. If pressing + or - can only get you to a number that is accessible by 0.3 increments, are you still able to send specific speed values from zwift/peloton that may not align with that math.

ex. Hitting + or - on QZ speed can get me to 4.9mph speed, but zwift/peloton may say adjust speed to 5.0. Will the treadmill go to 5.0 from the QZ command?

debug and screenshot attached:
[debug-Tue_Jan_25_06_52_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7934126/debug-Tue_Jan_25_06_52_13_2022.log)

![IMG_0367](https://user-images.githubusercontent.com/18269595/150990691-982eb3e0-25a6-4482-a900-4f49c3d907d0.PNG)

**Comment by cagnulein** [comment]
> @cagnulein It works! Great work!!!

Yeah!!!!

> 
> I was able to manually adjust speed and incline from the treadmill and then I tried adjusting speed and Incline in QZ. That worked successfully! I noticed that incline adjusted by 0.5 which is the same as the treadmill's up and down. However, the speed + and - adjusted by 0.3. Is that typical for the adjustment from the app? Is that related to conversion of Metric to Imperial? I was expecting a 0.1 adjustment for + and - on speed that would match the buttons on the treadmill. When adjusting from QZ at 0.3 increments, it will put the speed at strange values that the user may not be used to running at. This may not matter at all, but was just curious.

Yes, because in QZ i set the default value of 0.5
I think it's time to set a setting also for this :) Maybe can you open a new ticket about this?

> 
> One question I have with that speed change. If pressing + or - can only get you to a number that is accessible by 0.3 increments, are you still able to send specific speed values from zwift/peloton that may not align with that math.

Yes, sure! I'm able to send any value to your treadmill ;)

> 
> ex. Hitting + or - on QZ speed can get me to 4.9mph speed, but zwift/peloton may say adjust speed to 5.0. Will the treadmill go to 5.0 from the QZ command?

Yes!

> 
> debug and screenshot attached: [debug-Tue_Jan_25_06_52_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7934126/debug-Tue_Jan_25_06_52_13_2022.log)
> 
> ![IMG_0367](https://user-images.githubusercontent.com/18269595/150990691-982eb3e0-25a6-4482-a900-4f49c3d907d0.PNG)

So can we close this?

**Comment by hoveeman** [comment]
@cagnulein WOO!! I'll open a ticket about speed increments. We can close this as it's working great! Thanks Roberto!!!

**Comment by cagnulein** [comment]
great! share the news on the FB group if you don't minde @hoveeman !
