### ISSUE TITLE
[BUG]  Unable to control incline or resistance on ProForm TDF 1.0

### ISSUE THREAD

**Issue by warrenmr** [cagnulein/qdomyos-zwift#593]
**Describe the bug**
Unable to control incline or resistance on ProForm TDF 1.0 through the app tiles.  Also, unsurprisingly, Zwift can't control resistance or incline.

**To Reproduce**
Install qdomyos on Android phone (have tried several versions of Android on Galaxy S8, Pixel 5 and old BlackBerry).
Connect to TDF 1.0 no problem.  Try to control resistance and incline with tiles.  Doesn't work.
Resistance, incline and other statistics changed on the machine are reported quickly to the app.

**Expected behavior**
Controling resistance and incline with tiles works.  It apparently does with TDF Studio.

**Screenshots**
  N/A

**Desktop (please complete the following information):**
 N/A 

**Smartphone (please complete the following information):**
 - Device: PIxel 5
 - OS: Android 12

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

[TDF 1.0.log](https://github.com/cagnulein/qdomyos-zwift/files/7902893/TDF.1.0.log)

**Comment by cagnulein** [comment]
@warrenmr did you try with the "Proform Studio Bike" setting off? Because your bike is different from the studio. Let me know

**Comment by warrenmr** [comment]
Yes, no data and no control with Studio off.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
@warrenmr ok so i guess your bike has a different protocol from the one in QZ. We need to collect log from android in this way https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using the ifit app.
Let me know

**Comment by warrenmr** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/7908415/btsnoop_hci.log)

Either I'm doing something wrong or the debug ZIP file structure has changed.  This file came from Bluetooth logs\FS\data\misc\bluetooth\logs.  I am on Android 12 if that matters.

**Comment by cagnulein** [comment]
@warrenmr Every android device has a different path. Thanks I will check it out. Please describe what you did in this test

**Comment by warrenmr** [comment]
What I did:  Turned on bike, started iFIT, connected to bike, selected workout, rode bike for a few minutes during workout.  iFIT changed resistance (gear) to 9 at the start (can't remember how many resistance levels are possible).  iFIT changed resistance to -0.5 then a bit later back to 0.  I changed resistance to 10 on the bike.  I played with gears and include a bit on the bike.  I select "follow trainer" on iFIT which changed resistance back to 9.  Ended workout.  Closed app.

**Comment by cagnulein** [comment]
@warrenmr the tiles are correctly populated on QZ? i mean the only issue is with the incline and resistance?

**Comment by cagnulein** [comment]
Done @warrenmr 
Send me an email as a reminder to roberto.viola83@gmail.com indicating this ticket and if you're on ios or android.
When you will receive the beta disable the proform studio setting and enable the new one proform tdf 1.0

let me know

**Comment by warrenmr** [comment]
> @warrenmr the tiles are correctly populated on QZ? i mean the only issue is with the incline and resistance?

Yes, the tiles seemed to be correctly populated.

**Comment by warrenmr** [comment]
> Done @warrenmr Send me an email as a reminder to [roberto.viola83@gmail.com](mailto:roberto.viola83@gmail.com) indicating this ticket and if you're on ios or android. When you will receive the beta disable the proform studio setting and enable the new one proform tdf 1.0

Email sent.

**Comment by warrenmr** [comment]
(I sent you an email from my gmail account which is linked to my Play Store account)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by warrenmr** [comment]
Progress!  Resistance and incline now work in Zwift and Rouvy.

I can also control resistance by tile, but incline does not show even when the tile is selected.  Please see screenshots.

![Screenshot_20220122-102132](https://user-images.githubusercontent.com/47881637/150651380-a657bc84-5263-434a-b1e3-01641dc02c55.png)

![Screenshot_20220122-102115](https://user-images.githubusercontent.com/47881637/150651378-a727a177-8d1b-410f-9169-db87994b6b68.png)
.

**Comment by cagnulein** [comment]
Great! Hah this is easy! I will add it tomorrow!
Thanks for the great news!


Il giorno sab 22 gen 2022 alle ore 19:42 warrenmr ***@***.***>
ha scritto:

**Comment by warrenmr** [comment]
Easy for you!  Grazie ancora Roberto.

**Comment by cagnulein** [comment]
done! i will build this tomorrow. you will see in the play store

**Comment by warrenmr** [comment]
Browsing through the code.  I don't fully understand it all, but given that the TDF 1.0 has 26 resistance levels, wondering if this is correct?  (I note that the Studio has 22 resistances levels, so different again).

    if (pelotonResistance <= 100) {
        return 16;

**Comment by cagnulein** [comment]
hah ok i didn't know about this difference, i'm changing it


Il giorno sab 22 gen 2022 alle ore 23:02 warrenmr ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
could you send me a conversion tablet for your bike to peloton? (if you
need this of course)

Il giorno dom 23 gen 2022 alle ore 05:25 cagnulein ***@***.***> ha
scritto:

**Comment by warrenmr** [comment]
I don't need Peloton conversion so can't help with that. Sorry.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
Ok @warrenmr no problem. The update is live! Tell me if the inclination tile is ok now
Thanks

**Comment by warrenmr** [comment]
Perfetto!  Incline tile works now.  And Target Resistance also seems to be coming in at 1-26 which is great.  And I like that I can change the offset and gain.

Much appreciated!

**Comment by cagnulein** [comment]
Great! @warrenmr Can we close this?

**Comment by warrenmr** [comment]
Yes.  Very fast!

**Comment by pastoradambee** [comment]
I am having issues getting my Tdf 1 to even connect with qz. Have input the IP and selected preform Tdf 1.0 as my bike

**Comment by warrenmr** [comment]
I am still using it in the winter. It would be helpful to get more information. I don’t think it is necessary (or possible) to enter an IP address  anywhere?  Need to ensure Bluetooth pairing is enabled on the bike first time I believe, probably by holding down the Bluetooth button on the bike.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pastoradambee** [comment]
I don’t believe mine has a Bluetooth.  It does connect to Wi-Fi and I make sure the router gives it the same IP. 
![Uploading IMG_0720.jpeg…]()
![Uploading IMG_0727.jpeg…]()

**Comment by warrenmr** [comment]
I don’t think the app will work unless your TdF has Bluetooth.

**Comment by cagnulein** [comment]
> I don’t think the app will work unless your TdF has Bluetooth.

actually qz can now connect also to tdf with wifi only, but i guess tdf 1 should have bluetooth also. @pastoradambee could you please post some images in order to show to @warrenmr if you guys have the same bike?
thanks

**Comment by pastoradambee** [comment]
![IMG_0727](https://github.com/cagnulein/qdomyos-zwift/assets/137828001/ab75d710-f902-4647-9e29-5e6edb93a826)

**Comment by warrenmr** [comment]
Different bike. I'm not at home so can't send a picture, but quite different.
________________________________

**Comment by cagnulein** [comment]
@ppsears could you please helo with @pastoradambee 
thanks @warrenmr

**Comment by pastoradamb** [comment]
Could I have the wrong bike selected? I chose the tdf1

**Comment by cagnulein** [comment]
> Could I have the wrong bike selected? I chose the tdf1
> 
> 

You have to follow my previous advice about the hotspot and collecting the log from your Mac. Let me know
