### ISSUE TITLE
Can’t connect bike (ex-4s+) to QZ

### ISSUE THREAD

**Issue by afreder0** [cagnulein/qdomyos-zwift#599]
**Describe the bug**
Hi! I have an echelon ex 4s+ and want to use QZ to load my ride detail into the Garmin ecosystem. To do that I’m using an iPhone and either a Garmin Fenix 6 or an Apple Watch. 

I got QZ connected to the bike for the first time yesterday. Then I did 2 things:
-updated the app to latest version
-applied the recommended settings in your help/setup page

Today the app will not recognize the bike. 

Can you help me troubleshoot? I’m not sure if I just need to restore default QZ settings, or if the latest version caused an issue

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13pro
 - OS: [e.g. iOS8.1] ios15.3

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@afreder0 if you want we can understand which is your issue but you have to provide me a debug log as descripted in the above link. Otherwise you can simply reinstall the app to restore the settings.
Let me know

**Comment by cagnulein** [comment]
@afreder0 any news?
