### ISSUE TITLE
HealthRider H70t iOS debug report - version 2.10

### ISSUE THREAD

**Issue by JCanhan** [cagnulein/qdomyos-zwift#600]
[debug-Fri_Jan_21_00_16_19_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7910668/debug-Fri_Jan_21_00_16_19_2022.log)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
@JCanhan ok i did a step forward. I did the fix in the version 2.10.2
Send me an email as a reminder indicating this ticket and that you're on ios.
Thanks

**Comment by cagnulein** [comment]
@JCanhan did you send me an email?

**Comment by cagnulein** [comment]
@JCanhan are you still interesting on this?
