### ISSUE TITLE
[REQ] Pre-set settings 

### ISSUE THREAD

**Issue by afreder0** [cagnulein/qdomyos-zwift#601]
**Is your feature request related to a problem? Please describe.**
I swap between my bike’s (echelon 4s) monitor (for Echelon connect and Peloton) and an iPad (for Zwift).  

I’m frustrated/overwhelmed by the number of settings that I need to fiddle with to get each to work. 

**Describe the solution you'd like**
Option 1: ability to save settings profiles ( e.g. Zwift/iPad and echelon)
Option 2: create a more basic settings menu. Perhaps the user could fill out a few questions (bike model, go between device, display device, and desired app) and QZ could automatically set the most-likely advanced settings. 

**Describe alternatives you've considered**

**Additional context**

thanks!
Alex

**Comment by cagnulein** [comment]
#118 there is already a task about this @afreder0 i'm closing this one, follow the other one. Anyway you can already save/load profile in QZ with the top right corner icons in the setting page
