### ISSUE TITLE
2 peloton classes in the same day with the same instructor

### ISSUE THREAD

**Issue by shmaddox** [cagnulein/qdomyos-zwift#602]
**Describe the bug**
Wrong class came up for auto resistance and instructor cues.

**To Reproduce**
Play 45 Minute Power Zone Ride from Matt Wilpers on August 21, 2021; the wrong information loads for his class.

**Expected behavior**
The correct class to play.

**Screenshots**
Class taken as described by instructor.
![271905654_1006536829934868_4466300139002184723_n](https://user-images.githubusercontent.com/98183101/150582335-d3107cc6-909f-420b-9166-10eafc24efda.png)

**Append a debug log**
[debug-Fri_Jan_21_11_22_31_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7915902/debug-Fri_Jan_21_11_22_31_2022.log)

**Comment by cagnulein** [comment]
@shmaddox fixed! if you want to try this out, send me an email to roberto.viola83@gmail.com indicating this ticket and i will send you the new beta to try this out
Thanks again for reporting this and remember to close this if it works ok

**Comment by cagnulein** [comment]
@shmaddox did you try this again with the new version?

**Comment by shmaddox** [comment]
Shoot, haven't had a chance. Is the current build with the fix version
2.9?  If so, I'll try this afternoon!

**Comment by cagnulein** [comment]
@shmaddox no i sent a 2.10 build some days ago. didn't you get it?

**Comment by shmaddox** [comment]
No - just checked my Test Flight app and there's no option to update.

**Comment by cagnulein** [comment]
@shmaddox sent it again now

**Comment by shmaddox** [comment]
Argh, I see it, but when I try to install it, it says I'm unable to accept
the invite because I'm already testing the app. My apple id is
***@***.*** - would that make a difference?

**Comment by shmaddox** [comment]
Scratch that - I stopped testing 2.9 and I was able to get 2.10!  Will
check ASAP.

**Comment by cagnulein** [comment]
great @shmaddox

**Comment by shmaddox** [comment]
Just tried it - didn't get the prompt to follow the class at all :( All of
my login info is there and correct. I tried the class I did earlier today
and that did show up with the prompt to follow.

**Comment by cagnulein** [comment]
so strange, did you have a debug log from this? @shmaddox

**Comment by shmaddox** [comment]
[debug-Tue_Feb_1_15_25_17_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7983506/debug-Tue_Feb_1_15_25_17_2022.log)
[debug-Tue_Feb_1_15_22_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7983507/debug-Tue_Feb_1_15_22_03_2022.log)
[debug-Tue_Feb_1_15_24_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7983508/debug-Tue_Feb_1_15_24_44_2022.log)


I'm not sure which one of these three it is. I think two of them were me trying to get the Matt Wilpers class I noticed the issue on to work, and one is a Ben Alldis class that I took earlier today (where the popup did come up).

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/files/7983507/debug-Tue_Feb_1_15_22_03_2022.log
yes this one shows the issue, i will try to dig into it more later today. Thanks for the feedback

**Comment by cagnulein** [comment]
fixed! i will send you a new one later today, thanks for the feedback @shmaddox

**Comment by cagnulein** [comment]
Sent @shmaddox

**Comment by shmaddox** [comment]
I didn't do the full ride, but the warmup seemed to be pulling the correct
ride and it all seemed to work well again!  Thanks for working on this!

Sarah

**Comment by cagnulein** [comment]
Great! And thanks so much for trying! I'm here if you find any other issues!
