### ISSUE TITLE
[BUG] Connection issue with JTX Fitness Sprint to Zwift

### ISSUE THREAD

**Issue by andrewrobertjones** [cagnulein/qdomyos-zwift#605]
Hi Roberto, 
As discussed via email, the qDomysos app can see the treadmill / iConsole, running on Samsung Galaxy S8. When I open up Zwift running on Windows 10, it pairs okay with Galaxy S8, but then when I try to start a run in Zwift it says Connection Failure. I attach the log her, thanks Andy Jones

[debug-Sat_Jan_22_16_48_23_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7918772/debug-Sat_Jan_22_16_48_23_2022.log)

**Comment by cagnulein** [comment]
Hi, i don't remember, did I already point you to https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift ? I believe that it could be a dongle issue or a phone name issue.
Also did you try with another android device instead of the Windows 10 one? Just to understand, because Zwift on Windows could be very tricky
Let me know

**Comment by cagnulein** [comment]
Also, which android version has the Galaxy?

**Comment by LeeGarb** [comment]
Do I just use the the android debug

**Comment by cagnulein** [comment]
@LeeGarb why do you comment here? :)

**Comment by andrewrobertjones** [comment]
Hi Roberto, sorry for slow reply. I am running your app on Android version 9. I have tried zwift on Android as well (Samsung tablet), this was worse! I couldn't even see the phone running the app at all via that version. When running Zwift in Win 10, it said it was pairing okay, although I noted that on the pairing screen it said 0 kph even when the treadmill was running, so evidently it was picking it up fully. On the main Zwift screen, it then said Connection Failure

**Comment by andrewrobertjones** [comment]
I might not get time to export more debugging info from my side till next weekend now, so don't feel like you need to do anything - I'm not expecting a magic solution! thanks

**Comment by cagnulein** [comment]
#598 
@andrewrobertjones do you have any news on this?
@LeeGarb has a disconnection issue, but i guess it's not dependent on the treadmill itself but to the samsung issue about their bluetooth stack

Let me know

**Comment by andrewrobertjones** [comment]
Hi Roberto, I sort of gave up on zwift with too many things. Did I understand you have a beta version of your app that can control incline on the JTX treadmill. If so, I would be happy to give it a go. I didn't try a windows dongle for Zwift, do you think this will solve the issue - I don't want to spend too much more money if it is all glitchy. Appreciate your efforts with the concept of the tool though :-)

**Comment by cagnulein** [comment]
@andrewrobertjones yes the android beta version controls the inclination/speed on your treadmill. The problem that you  and @LeeGarb have right now it's not dependent on QZ itself, but it's strictly releated to some samsung devices unfortunately. If you guys would come on the QZ group on facebook you will see yourself that everything works nicely with different devices, and it really changes the way you train yourself over the treadmill!

But of course it's a your decision, but we did the big step to decode the protocol and handled on QZ, so now we have to do just the easiest step :)

**Comment by andrewrobertjones** [comment]
Can you email me or point me at a link to try out the beta version, thanks!

**Comment by cagnulein** [comment]
sending me an email to roberto.viola83 at gmail.com indicating this ticket
and if you're on ios or android



Il giorno gio 3 feb 2022 alle ore 08:15 andrewrobertjones <
***@***.***> ha scritto:

**Comment by andrewrobertjones** [comment]
Hi Roberto, I tried the beta version on the jtx sprint 5. It made a noise like it was trying to change the incline but it didn't work, it just forced the treadmill to stop. I did enable jtx sprint in the options. Do I need to do anything else?

**Comment by cagnulein** [comment]
I guess it's the same thing that @LeeGarb see on #598
Let me understand it and fix it
