### ISSUE TITLE
[BUG] the app starts with 10 watts ,im not pedaling

### ISSUE THREAD

**Issue by Ric-Moreira** [cagnulein/qdomyos-zwift#607]
Hi,  when i connect the qz app with zwift,in power source always starts with 10 watts , and im not pedaling, rpm is the same, im not pedaling and it shows in between 20 or 30
qz app on android 9 phone
zwift on windows 11 laptop
![20220122_204210](https://user-images.githubusercontent.com/98238393/150657097-e06c395f-44cf-49f8-8fae-a8f0178d34a7.jpg)
![20220122_213258](https://user-images.githubusercontent.com/98238393/150657106-8edd9c94-e75c-4f6a-bebf-ce6e2aafb183.jpg)
![Screenshot_20220122-203936~2](https://user-images.githubusercontent.com/98238393/150657763-97768138-4a5d-4f05-b49b-f99263564734.png)

[debug-Sat_Jan_22_21_31_35_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7919399/debug-Sat_Jan_22_21_31_35_2022.log)

**Comment by cagnulein** [comment]
fixed! it will be in the new beta 2.10.4
If you aren't in the beta send me an email to roberto.viola83@gmail.com indicating this ticket and if you're on ios or android
Thanks for reporting this
