### ISSUE TITLE
Zwift discovery issue

### ISSUE THREAD

**Issue by UlicaKablowa4** [cagnulein/qdomyos-zwift#608]
I have Zwift installed on Samsung S6 lite (model SM-P610) and QDomy app on Samsung S9 phone

The Zwift (power source) on table does not recognize my phone, but the revers works, phone recognizes tablet.

However I would like to have Zwift on a tablet (bigger screen) that connects to QZ on a Samsung phone.
Can you help me get this solved?

**Comment by cagnulein** [comment]
Hi @UlicaKablowa4 did you already follow this https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift ? If so unfortunately it's an hardware issue of your device. Not all the android devices are capable of running bluetooth central and peripheral at the same time :( If you want you can buy a cheap iphone 6s or 7 for this purpose.
Let me know

**Comment by cagnulein** [comment]
any news @UlicaKablowa4  ?

**Comment by UlicaKablowa4** [comment]
Nothing changed

I am considering selling the Samsung tablets ( I have 3 now) and buying IPad Air 1.  I want to have Zwift on the tablet and QZ on a phone.
Do you think IPad will work?

**Comment by cagnulein** [comment]
iPad for zwift or ipad for qz? the main problem in your setup is the phone, not the tablet @UlicaKablowa4 
but you can use one tablet for qz and the ipad for zwift. In this way it will work

**Comment by UlicaKablowa4** [comment]
IPad Air 1 for Zwift and Samsung phone S9 for QZ

I put QZ on Iphone 8 and Zwift on Samsung Tablet S6 Lite.  The Table was still not able to recognize QZ on iPhone.

I am no expert in this, but this suggest to me that Tablet is the issue not the phone.

My phone worked for both QZ and Zwift.

**Comment by UlicaKablowa4** [comment]
OK

**Comment by cagnulein** [comment]
any news @UlicaKablowa4  ?

**Comment by UlicaKablowa4** [comment]
Yes,  I resolved it.
I bought iPad Air 1 and it worked.  The 4 different Samsung tablets I bought did not work.  I bought used ones on Kijiji so I hope to sell them back.
One Samsung tablet was not even able to download Zwift app.  I am not happy with Samsung tablets.

Thanks for following up.
