### ISSUE TITLE
[REQ] Implement "Pace Time" for Runner

### ISSUE THREAD

**Issue by CiccioFritz79** [cagnulein/qdomyos-zwift#609]
Hi,

it would be great if QZ could manage the various "Pace Times" (1ml, 5km, 10km, half marathon and marathon), in order to create workouts and manage them on a percentage of the chosen Pace Time.

Zwift, for example, manages the various workout phases as a percentage of the chosen "Pace Time" (eg: 60 seconds at 90% of Pace 10km)

Thanks in Advance

**Comment by cagnulein** [comment]
@CiccioFritz79 could you please attach a ZWO file about this?

**Comment by CiccioFritz79** [comment]
Here a simple workout file.

[Workout.zip](https://github.com/cagnulein/qdomyos-zwift/files/7920644/Workout.zip)

**Comment by cagnulein** [comment]
@nieko-nera what do you think about this? i guess the only way is to put a pace time settin as @CiccioFritz79 suggested

**Comment by CiccioFritz79** [comment]
i leave here some tags that, maybe, are not present in byke workout:

- <durationType>: 2 possibilities: time o distance

- pace (into <SteadyState Duration> tag):
a) 1 = 1mile
b) 2 = 5km
c) 3 = 10km
d) 4 = Half Marathon
e) 5 = Marathon

I'm here if i could help

**Comment by nieko-nera** [comment]
Yes it' good idea to add settings for Zwift workouts pace times, but:

- if there is tag `<thresholdSecPerKm>312</thresholdSecPerKm>` in workout, use it instead of pace times.
- which pace to use in workout (1ml, 5km, 10km, half marathon and marathon) tells this tag `<SteadyState Duration="300" pace="2" Power="0.6667">` **pace="2"**. Its from 0 to 4. 0=1mi, 1=5km, 2=10km, 3=hm, 4=m

**Comment by cagnulein** [comment]
@nieko-nera @CiccioFritz79 ok i like this..i will try to add if i get the time :D

**Comment by CiccioFritz79** [comment]
I don't know if it's difficult, but it's possibile to implement a check during ZWO workout parse?

IF "sportType" is "run" AND pace value non present in "SteadyState", THEN use pace value set in QZ Setting. 

Clearly, into QZ Setting,  where you set Pace Time, add a "use this pace time" selection (where you could insert value from 0 to 4).

So, if workout doesn't have the pace value, QZ can play workout correctly anyway.

**Comment by cagnulein** [comment]
@CiccioFritz79 give me the default values for all this 5 new settings, we should put them under the training program section, isn't it?

**Comment by CiccioFritz79** [comment]
No, there isn't a default value, but every runner must set it (as target time or a best personal time).

Mine, for example, is 60 minutes for 10km (so 6:00 min/km, or 10km/h). 

You should be let set time for every sector:

Pace 1 mile (0):      ________ (in seconds)
Pace 5 Km (1):        ________ (in seconds)
Pace 10 Km (2):      ________ (in seconds)
Pace HM (3):          ________ (in seconds)
Pace M (4):            ________ (in seconds)
Default Pace:         0,1,2,3,or 4 (selectable)

Zwift sets others pace time if the user input one (but it's not a mathematic operation: 10km 1h00m00s, 5km set 28m30s, for example). But in QZ a runner should copy what is set in Zwift (ore use personal value if not use Zwift).

**Comment by cagnulein** [comment]
@CiccioFritz79 which is the mean of "Default Pace: 0,1,2,3,or 4 (selectable)" ?

**Comment by cagnulein** [comment]
> Pace 1 mile (0): ________ (in seconds)
> Pace 5 Km (1): ________ (in seconds)
> Pace 10 Km (2): ________ (in seconds)
> Pace HM (3): ________ (in seconds)
> Pace M (4): ________ (in seconds)

also we need to put pace not seconds. So for example

Pace 1 mile (0): 4:00
Pace 5 Km (1): 5:00
Pace 10 Km (2): 5:20
Pace HM (3): 5:40
Pace M (4): 6:10

**Comment by cagnulein** [comment]
done. @nieko-nera could you pull it, build it and try? Thanks!

**Comment by nieko-nera** [comment]
I tested little bit.

- In Zwift pace times is time for whole distance, maybe in QZ it should bee same, so you don't need to convert? 

<img width="386" alt="pace" src="https://user-images.githubusercontent.com/10880681/151013055-3fe2c6e2-712c-4214-9cd8-dd8474cd22db.PNG">

- In QZ settings when I change 5 km pace and restart QZ it changes to same pace as 1 mile pace.
- Why do we need "Default pace"? In workout file should say which pace to use.
- In @CiccioFritz79 workout example there is tag `<Warmup Duration="60" PowerLow="0.5" PowerHigh="1" pace="0"/>`, how it should work? In 60 seconds interval increase pace from 0.5x of 1 mile pace to 1x of 1 mile pace?

I'm sorry but I don't have time this week to test more. @cagnulein maybe I can share apk with @CiccioFritz79 and he can test more?

````
<workout_file>
<author>Myself</author>
<name>Test Workout</name>
<description></description>
<sportType>run</sportType>
<durationType>time</durationType>
<tags></tags>
<workout>
<Warmup Duration="60" PowerLow="0.5" PowerHigh="1" pace="0"/>
<SteadyState Duration="30" Power="0.5" pace="0"/>
<SteadyState Duration="30" Power="0.5" pace="1"/>
<SteadyState Duration="30" Power="0.5" pace="2"/>
<SteadyState Duration="30" Power="0.5" pace="3"/>
<SteadyState Duration="30" Power="0.5" pace="4"/>
<Cooldown Duration="60" PowerLow="1" PowerHigh="0.5" pace="4"/>
</workout>
</workout_file>

**Comment by cagnulein** [comment]
> * In Zwift pace times is time for whole distance, maybe in QZ it should bee same, so you don't need to convert?

argh, you're right

> * In QZ settings when I change 5 km pace and restart QZ it changes to same pace as 1 mile pace.

Fixed!

> * Why do we need "Default pace"? In workout file should say which pace to use.

Read this https://github.com/cagnulein/qdomyos-zwift/issues/609#issuecomment-1019861368

> * In @CiccioFritz79 workout example there is tag `<Warmup Duration="60" PowerLow="0.5" PowerHigh="1" pace="0"/>`, how it should work? In 60 seconds interval increase pace from 0.5x of 1 mile pace to 1x of 1 mile pace?
> 

i implemented this only for steadystate, but i can do also for other modes of course

> I'm sorry but I don't have time this week to test more. @cagnulein maybe I can share apk with @CiccioFritz79 and he can test more?

ok no problem!

**Comment by CiccioFritz79** [comment]
some update:

with last update, workout doesn't work properly: 

1) Default Pace Time set in QZ overwrite the workout power (and maybe the workout pace set in file). QZ start and remain at "default Pace time" all the time. If i slow down, at the phase change it returns to default pace time.
2) Maybe the "Default Pace Time" should permit to set to "disable", to avoid misunderstanding

Right about whole distance, more confortable to set as Zwift.

i send log and relative workout to Roberto for debugging.

**Comment by CiccioFritz79** [comment]
I upload log and relative workout.

[debug-mar_gen_25_21_17_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7939697/debug-mar_gen_25_21_17_49_2022.log)
[Short Speed Reps mod.zip](https://github.com/cagnulein/qdomyos-zwift/files/7939703/Short.Speed.Reps.mod.zip)

**Comment by cagnulein** [comment]
i totally forgot to manage the power field in this case. That's the issue. I'm doing this right now @CiccioFritz79

**Comment by cagnulein** [comment]
managed everything @CiccioFritz79 i will build it later today 2.10.8

**Comment by CiccioFritz79** [comment]
I just tried a workout (attacched).

Warmup section starts correctly, but before ending, veoclity spin to 10Km/h and more. I pull down, and after a bit a new spike.

When warmup end, the velocity set correctly, but after a bit another velocity spike.

I attach a log (the big one).

After that i stop QZ, close the app, and restarted. When QZ connet to treadmill, velocity and inclination spike to 9,5k/h and 8,5% unclination (anq Zwift was closed). I attacch a log (the little one) but i don't know if it's related to workout or not.

P.S.: during workout i use auto inclination, and QZ receives inclination tha aren't  about workout or stage... could you check this?

[Hill + Tempo #3.zip](https://github.com/cagnulein/qdomyos-zwift/files/7944302/Hill.%2B.Tempo.3.zip)
[debug-mer_gen_26_18_13_07_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7944288/debug-mer_gen_26_18_13_07_2022.log)
[debug-mer_gen_26_18_35_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7944291/debug-mer_gen_26_18_35_11_2022.log)

**Comment by CiccioFritz79** [comment]
> > * In Zwift pace times is time for whole distance, maybe in QZ it should bee same, so you don't need to convert?
> 
> argh, you're right

i remember this point, thas  it would be really convenient as management.

**Comment by cagnulein** [comment]
> i remember this point, thas it would be really convenient as management.

@CiccioFritz79 ok i'm changing them right now, please be sure to change them accordingly when you will receive the new version (otherwise a HUGE speed will be applied!)

**Comment by cagnulein** [comment]
done @CiccioFritz79 i blame God a lot about this :D so please it carefully ;) i will try to build this later today

**Comment by cagnulein** [comment]
@CiccioFritz79 can we close this? or you want to do other tests?

**Comment by CiccioFritz79** [comment]
Hi @cagnulein 

I thinks that we can close this ticket. If i found some bugs in the future, i re-open this.

Thanks a lot for your work!
