### ISSUE TITLE
Avoiding the App to connect to another bike in reach

### ISSUE THREAD

**Issue by amueller000** [cagnulein/qdomyos-zwift#615]
Is there any chance to assure only my S3 connects to my iPhone and not any other bike nearby?
Sometimes the App connects automatically to another bike and there is no option to either avoid it or disconnecting it without disabling BT and waiting until the wrong bike stopped pairing mode.
Thx!

**Comment by cagnulein** [comment]
thanks @amueller000 just to be sure, the S3 bikes over bleutooth doesn't have an ID number after the "YESOUL" word?

**Comment by amueller000** [comment]
They have a 10 or 12 digit number for BT, unfortunately it gets connected to my phone automatically. As soon as the connection has been established, I cannot disconnect it from my iPhone. It either requires to turn BT off and wait until pairing mode gets off or I have to remove the batterie from the bike

 

Von: Roberto Viola ***@***.***>
Antworten an: cagnulein/qdomyos-zwift ***@***.***>
Datum: Montag, 24. Januar 2022 um 08:30
An: cagnulein/qdomyos-zwift ***@***.***>
Cc: A M ***@***.***>, Mention ***@***.***>
Betreff: Re: [cagnulein/qdomyos-zwift] Avoiding the App to connect to another bike in reach (Issue #615)

 

thanks @amueller000 just to be sure, the S3 bikes over bleutooth doesn't have an ID number after the "YESOUL" word?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cagnulein** [comment]
@amueller000  hah ok! if it's so you can use the "manual device" settting in the advanced section to filter your bike! Let me know

**Comment by amueller000** [comment]
Does it mean, I should enable “Manuel Device” and see if my S3 bike turns up, select it and press ok. 

This would force the App to only connect with the selected device?

Are there any other setup steps to consider along with the Manuel Device selection?

 

Von: Roberto Viola ***@***.***>
Antworten an: cagnulein/qdomyos-zwift ***@***.***>
Datum: Montag, 24. Januar 2022 um 08:38
An: cagnulein/qdomyos-zwift ***@***.***>
Cc: A M ***@***.***>, Mention ***@***.***>
Betreff: Re: [cagnulein/qdomyos-zwift] Avoiding the App to connect to another bike in reach (Issue #615)

 

@amueller000 hah ok! if it's so you can use the "manual device" settting in the advanced section to filter your bike! Let me know

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cagnulein** [comment]
yes @amueller000 the manual device force QZ to connect ONLY to the device selected. No, no other setup steps needed for this. Let me know

**Comment by amueller000** [comment]
Thx a lot. I didn’t know. I will test it tomorrow and keep you posted

 

Von: Roberto Viola ***@***.***>
Antworten an: cagnulein/qdomyos-zwift ***@***.***>
Datum: Montag, 24. Januar 2022 um 09:54
An: cagnulein/qdomyos-zwift ***@***.***>
Cc: A M ***@***.***>, Mention ***@***.***>
Betreff: Re: [cagnulein/qdomyos-zwift] Avoiding the App to connect to another bike in reach (Issue #615)

 

yes @amueller000 the manual device force QZ to connect ONLY to the device selected. No, no other setup steps needed for this. Let me know

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by amueller000** [comment]
Looks like it works. The manual setup forces the App to connect only to the right bike. 
So, no further need for another feature. :-) 
Many thanks for taking care.

**Comment by cagnulein** [comment]
Great!
