### ISSUE TITLE
Echelon Connect Sport Bluetooth Log

### ISSUE THREAD

**Issue by marklogan17** [cagnulein/qdomyos-zwift#62]
I got one of the Echelon Connect Sport bikes from Walmart.  I thought it would be nice to be able to connect to Zwift and/or Peleton (any reason we can't use the bridge to fake being a cadence sensor and connect to the Peleton app?).  I followed the instructions to collect the bluetooth log on my Pixel 2 XL.  I've attached the file here.  

I thought I would have a look at the file first so I sorta of winged it a bit while doing the testing, so the steps below are pretty close but probably not ideal for what you're looking for.  After opening the file I decided it was better to hand it to the experts :)  Happy to redo with more explicit planned steps if you want/need.

Steps I took:
- Cadence up to around 60, resistance started at 15
- Increased cadence to 70, increased resistance to 18
- Increased cadence to 80/85, increased resistance up to 22
- slowed cadence into high 60s/low 70s

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/5612880/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Great! Tomorrow I will check it and I'll start to implement it!

**Comment by marklogan17** [comment]
Thank you!  Please let me know what I can do to help.

**Comment by cagnulein** [comment]
@marklogan17 ok i will keep in mind. Just a info: which is your favourite device for the test? raspberry, linux device, android? I will build a test version for your device (or can you build it yourself?)

**Comment by cagnulein** [comment]
@marklogan17 ok, i've done! 👍 
you can build the last commit or, if you want, i can build it for you (tell me your favourite target device).

I guess we need several tries to have something working correctly, but we should see at least a connection on this commit.

Just a few questions:
1. i didn't see any frame to the display of the echelon. Do you have a display on your bike? If yes i guess it's auto updated
2. i didn't see any frame to force the resistance, i guess because your echelon can change the resistance only manually rotating the knob, isn't it?
3. i guess we have to update the watt table as we did for the domyos bike https://github.com/cagnulein/qdomyos-zwift/pull/52 but i need your help for this. We have several ways to achieve this: 1) find a watt table for your bike on internet 2) trim it manually

**Comment by cagnulein** [comment]
> One thing I thought of - as I've been using the bike, I have to turn the knob quite a way to go up one level of resistance. I'm somewhat wondering if they actual resistance levels coming from the bike may be more fine grained than 0-32 and it rounds up to the nearest whole number. No proof of that but something to keep in mind depending on the values you see.

you should see on the UI and also in the console log the resistance level. And yes, i guess it's more fine grained for what i saw in your snoof log.

**Comment by marklogan17** [comment]
Wow I woke up to all kinds of progress :) I do have a couple of pi's around but the quickest turn around time for me now would be an android build.  I'm happy to also test the pi one.  I'll read the build instructions to see if I can set up a manual dev environment to save that step in the future for you guys, but it may take a couple of days.

to answer your questions:
1) There is no display on the bike, it is all done through bluetooth to a personal iOS or Android device.
2) Its only a manual change of resistance (this is about a cheap a magnetic resistance bike as you can get currently - which is why its selling so well :) )
3) I'll look for a watt table on the internet.  I do get an output displayed - didn't even think of tracking that.  I can do another bluetooth snoop and get some values there.  I'll do that at some point today in between meetings.

**Comment by cagnulein** [comment]
[android-build-debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/5616152/android-build-debug.zip)
this is the android version. allow positiong and storage permission so it should log to the download folder.
if it works or if it doesn't, post here the log
thanks :)

1. , 2. and 3. ok :)

**Comment by marklogan17** [comment]
I installed it and tried it.  It starts up and connects to the bike.  All the values are zero except the Odometer is reading something like 2500Km.  I tried cycling at various different cadence and resistance levels but the displays stayed at zero.  I then went in the Download folder to get the log and there was none.  Researched the android build and realized I needed the storage permission so I added that.  Repeated everything but I still don't see a log.  I'm guessing I'm doing something silly :) 

Do I need to connect to Zwift or Peleton before getting values?  Anything else you can think of as to why I'm not seeing a log file?

**Comment by cagnulein** [comment]
@marklogan17 for the odometer i had already fixed it. I'm checking the log too, because it doesn't write it on my android 10 phone neither. I'm looking into it.

**Comment by cagnulein** [comment]
[android-1.1.0.zip](https://github.com/cagnulein/qdomyos-zwift/files/5616530/android-1.1.0.zip)
ok odometer and logs fixed. please retry ;)

**Comment by marklogan17** [comment]
Log attached.
[debug-Mon Nov 30 09_48_53 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5616684/debug-Mon.Nov.30.09_48_53.2020.log)

**Comment by cagnulein** [comment]
@marklogan17 did you ride during this log? because i saw everything to 0. maybe i missed something in the init phase in order to give a "start" command

**Comment by cagnulein** [comment]
[android-1.1.1.zip](https://github.com/cagnulein/qdomyos-zwift/files/5616751/android-1.1.1.zip)
fixed! stupid typo on init phase! @marklogan17

**Comment by marklogan17** [comment]
Nice work!  

- Cadence looks like its working correctly.  
- Distance is counting but seems off - felt like maybe its displaying meters are Km?  i.e. 2.50 Km should be 250m - but that's just a guess based on watching the display as I rode for a couple of minutes.  
- Resistance is just displaying '0'.  I did hit the +/- buttons on resistance a couple of times to see if that triggered it to start reading.  Obviously since this only has manual resistance hitting those buttons won't 'change' the resistance.

Log file below.

[debug-Mon Nov 30 11_00_54 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5617087/debug-Mon.Nov.30.11_00_54.2020.log)

**Comment by cagnulein** [comment]
Great! Now I'm outside but i Will check the log later today
For the odometer: i just read a pure number and i divide by ten, i really don't know which is the unit, but yes could be km. In any case this value is not useful to zwift.

See you later

**Comment by cagnulein** [comment]
[android-1.1.2.zip](https://github.com/cagnulein/qdomyos-zwift/files/5617853/android-1.1.2.zip)
resistance fixed! (another stupid typo :P)

about the odometer: i guess i will add a unit option in order to let you select the correct unit in the UI (zwift wants km)

**Comment by cagnulein** [comment]
[android-1.1.3.zip](https://github.com/cagnulein/qdomyos-zwift/files/5617967/android-1.1.3.zip)

ok i also fixed the odometer dividing it by 10

we have only to prepare a better watt table.

**Comment by cagnulein** [comment]
[android-1.1.4.zip](https://github.com/cagnulein/qdomyos-zwift/files/5618111/android-1.1.4.zip)

added a watt table too.

**Comment by marklogan17** [comment]
got a few calls for the next couple of hours.  Will test again as soon as I can get free.  Thanks again for all your work on this.

**Comment by cagnulein** [comment]
Ok, no problem, I'm GMT+1 so i guess we will update tomorrow ;)

Have a good day ;)

**Comment by marklogan17** [comment]
Cadence and Resistance looking good.  I'll have to pay some attention to distance to see if I can figure it out, but as you said, not a huge deal.  I think your watt table is a good start.  The Echelon app does output watts so I'll get some values of resistance vs cadence w/ associated watt values.  I'm just not sure if the app is calculating the watts based on resistance/cadence/bike version or if the bike is sending over the bluetooth interface.

Latest log:
[debug-Mon Nov 30 16_51_17 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5618991/debug-Mon.Nov.30.16_51_17.2020.log)

**Comment by marklogan17** [comment]
I did some more riding tonight.  Loos like the distance from the bike is in miles so that's likely the reason its still a touch off.  I've started creating a watt table.  I looked at your code and see how you have it set up so I'll get min/max values for various cadences and we can extrapolate from there.  I did find the equation that Peleton uses to calculate output watts from cadence and resistance. 
 Even modifying it to use the resistance scale of Echelon didn't really come close to matching what I saw so not likely useful.

**Comment by cagnulein** [comment]
I guest the best way is to have a reverse engineering approach: so, for example, record a video of the app showing the watt, cadence and resistance for 1-2 minutes and we can build a chart on excel and of course a math formula.
Does it sound good for you?

**Comment by marklogan17** [comment]
That's what I started. I did 60,70,80,90,100 cadence at various resistance levels and tracked output. I'm going to do 40 and 50 cadence, maybe some at 110 and possibly 120. I started at resistance 10 and went up to 31 by 3 to 4 levels at a time.  Will do some measurements at 0 and 5 resistance too. That should give enough info to extrapolate the rest. 

It's midnight here so going to sleep now. Will try and finish this table tomorrow.

**Comment by cagnulein** [comment]
Great! Here is already Tuesday :) have a good night!

**Comment by marklogan17** [comment]
I did a little ride and got more values and updated the spreadsheet.  So I have values for resistance levels 1, 5, 10, 13, 15, 18, 21, 25, 28 and 31 - and cadence values for 40, 50, 60, 70, 80, 90, 100 and 110.   I then extrapolated the likely values for the resistances in between (rows highlighted in blue in spreadsheet).  Finally I used the Excel/Google Sheets 'TREND' formula to populate the values for cadences 115-140).  I could push to 120 cadence or even 130 for some of them to get actual readings, but I figured this is probably close enough. 

Have a look and let me know your thoughts.  We can definitely extrapolate for more resistances too if you want, but I think your code was just looking for min/max watts for each cadence, correct?

**Comment by cagnulein** [comment]
Wow great work!
Yes my code uses only min and max watts for each cadence, but i did in this way only because i don't have so much data to use for domyos bike :)

If you want, you can do a final step (or i can do it tomorrow): we can generate a math formula from these datas. I know that Excel has this feature. (add the data to a chart, add also the trend line and the formula behind the trend line). What do you think?
Or if you think we'll get a too much complicated math, we could use my actual code with your new data.

You could also create a pull request with the code if you're able to generate some C++ code (i think it's very easy for the watt function). But again, if you want i'll could to tomorrow.

Now it's time to have some brain pause, have a nice evening :)

**Comment by marklogan17** [comment]
I'll play with it while I'm working out tonight.  When I tried out the trend line on the chart last night it generated a straight line approximation which would really just work out the same as the math you already have with the min/max values.  I'll see if I can use Excel to get a more precise formula that matches the real values more appropriately.

**Comment by marklogan17** [comment]
I played with Google Spreadsheets more than I care to admit.  I generated charts for the various cadences vs resistances and then found best fit.  Then I used the relationship of the values in the generated equations to the cadences - and generated a second equation to match that.  I combined them so that I now have two equations that come reasonably close to my measured values.  They get worse as the cadences go up, but those are also calculated outputs higher up vs real outputs so having a difference there is probably not unreasonable. 

If you look at the spreadsheet, on the second sheet you'll see my calculated values using the formulas and below that another set of data showing the discrepancies of original values to calculated values.

For Cadences lower than 90:
(3.59 * EXP(0.0217 * Cadence))*(EXP(0.095*Resistance))

For Cadences 90 and up (not that it makes that much difference)
(3.59 * EXP(0.0217 * Cadence))*(EXP(0.088*Resistance))

Have a look at the spreadsheet.  Play with it if you want.  Try different trend types on the graphs to see if there are better fits - and thus different/better equations.  Eventually I can ask some facebook groups to do WATT vs Resistance vs Cadence readings to get even better values, but I didn't want to do that before it was all working 'well enough'.

**Comment by cagnulein** [comment]
[android-1.2.4.zip](https://github.com/cagnulein/qdomyos-zwift/files/5627622/android-1.2.4.zip)
ok @marklogan17 i implemented the function inside the apk. Let's try!

**Comment by marklogan17** [comment]
Only had time for a quick test but its looking good!!  

I did also do a quick test to see if I could connect as cadence to Peleton but that didn't work - but that's a separate issue.  I will create a Zwift account and give it a try there too.

Now that we have it working I'll do a test of similar cadence over say a minute, between the Echelon app and this app and compare all the values - output, speed, distance, etc and make sure we have them all as consistent as possible.  That will probably be this evening my time.

**Comment by cagnulein** [comment]
> I did also do a quick test to see if I could connect as cadence to Peleton but that didn't work - but that's a separate issue. I will create a Zwift account and give it a try there too.

try to play with the heart rate setting (disable/enable it, reboot the app and retry)

**Comment by marklogan17** [comment]
1) Connected to Zwift on iOS no problem tonight.  Speed, Cadence, etc all seemed to come across.  Only did a very quick test.
2) Failed to connect to Peleton.  However it is just looking for a cadence sensor so I'm wondering if its a bluetooth connection priority thing?  Seems that Zwift connects to the speed sensor first and then auto connects to the others?

3) Watt calculations look to be 'close enough' to the table so I think the equations are OK and your implementation of them is good.  Only way to make it better now is to get more accurate readings in the tables and thus generate better equations.

4) I did a one minute ride at 70 cadence on the Echelon app and this app to look at speed and distance.  On this app I think the speed didn't appear and the distance was 0.67 Km.  On Echelon the speed at approx 70 cadence was 16.2-16.5 mph and after a minute I had gone 0.3 miles.  I tried to figure a relation ship between the value for distance that you're reading and dividing by 100 and the distance in miles in Echelon but I didn't think of anything obvious.  It seems that there's likely a speed reading in the bluetooth packets somewhere too, and its likely coming across in mph.  I'm attaching the log file from this ride in case its useful.

[debug-Wed Dec 2 19_35_13 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5633175/debug-Wed.Dec.2.19_35_13.2020.log)

Again, really appreciate all your hard work on this.  I can't believe how well its working already!

**Comment by cagnulein** [comment]
1. Great!
2. I created a separate issue
3. Ok i trust you :D
4. Ok this should be easy too to solve. Now I'm using a pure data on bluetooth that i guessed was the distance, but maybe it's something else. Anyway, we know the cadence so we can derive the speed and also the distance if you know the ratio. And what? We know the ratio, because the echelon app shows the speed! :)

So if we divide speed for cadence we know exactly how many miles per revolution we have. What do you think?

If all this mess works, next we can go to the moon :D

**Comment by marklogan17** [comment]
Alright, I did a quick ride and grabbed cadence vs speed.  I then figured out the ratio (its all in tab three of the spreadsheet), but the short answer is:  the speed in MPH is 0.233 times the cadence.  I agree with you that your software should live in Km/h so the actual formula is: 

speed (kph) = 0.233 * cadence * 1.60934 
(or slightly optimized) speed = 0.37497622 * cadence

**Comment by cagnulein** [comment]
@marklogan17 implemented, in the next release you will find the speed and distance (hopefully :D)
i guess to release a new one, tomorrow

**Comment by cagnulein** [comment]
i'm testing #61 with @urbanspike for tonight @marklogan17 , so i will release a version for you tomorrow, sorry ;)

**Comment by cagnulein** [comment]
ok [android-1.3.0.zip](https://github.com/cagnulein/qdomyos-zwift/files/5641563/android-1.3.0.zip) this is too for the speed and distance. I added also the miles setting

**Comment by marklogan17** [comment]
Did some testing.  Speed looks like its correct.  I'll repeat the one minute ride at 70 cadence a little later to confirm distance - ran out of time before my first meeting :) Will report in other issue on the peleton connection.

**Comment by marklogan17** [comment]
Repeated the test of one minute at 70 cadence.  Speed looked right and the distance looked correct too.  So I think that's all good.  Next step will be to do a full ride on Peleton and/or Zwift to make sure I don't get any connection issues over a longer time.

**Comment by cagnulein** [comment]
@marklogan17 hi, i'm releasing the app on the Apple store, do you have an iPhone or an iPad to test it? If yes, add yourself here https://www.facebook.com/groups/1064761680643892 and write on messenger (roberto viola, i'm the administrator of that group). I will send you a free invitation for the beta testing.
Thanks

**Comment by marklogan17** [comment]
Yes I have an iPhone.  Happy to test for you.  I registered for the group.

**Comment by istephenzz** [comment]
Hi! I've been using the app for a couple of days now on my Echelon Sport and have had a great experience. Previously I was using the HR2VP app which converted your heartrate to power but it wasn't the most accurate data especially during sprints. I had a couple questions:
1. Why does it seem that the speed on Zwift is always about 5-7 mph faster than what is being displayed in Zwift?
2. Is there a way to get a notification on Zwift to change your magnetic resistance to simulate the in-game hill gradients? I often find myself biking at 20mph and it drops to 5mph when encountering some sort of hill or gradient. Is there an option to enable a notification that tells you "increase magnetic resistance to 50%", for example?

**Comment by cagnulein** [comment]
Hi @istephenzz !
1) speed on zwift is calculated on power value, qdomyos instead, has the real speed based on the crank ratio. Just math :)
2) yeah i thought about it too! Maybe a vocal notification. What do you think?

Love to see that you're enjoying it!

**Comment by istephenzz** [comment]
Thanks for the quick response! 
1. That's what I anticipated the answer to be thank you for confirming! I'm sure Zwift has its own unique algorithm especially when dealing with hills and such as mentioned in my 2nd question
2. That would be an amazing feature but wouldn't it have to come from Zwift's end? I don't code but I figure I'd ask the question here because I'm not even sure where the issue lies. Would the qdomyos app be able to get real-time Zwift changes in elevation and be able to give the user audio feedback to change your resistance to match the angle you are climbing or going down?

**Comment by cagnulein** [comment]
2. Yes it comes from zwift, infact it already comes! On domyos bike, my app already controls the resistance based on the grade of the hills, so it's just a matter of coding to have a voice announcement :)

I will open a new issue for this ;)

**Comment by istephenzz** [comment]
Amazing thanks for being so responsive. I assume your app wouldn't be able to control the resistance on an Echelon Connect Sport, correct?

**Comment by cagnulein** [comment]
@istephenzz no because echelon sport connect has only manual resistance not automatic.

**Comment by istephenzz** [comment]
Got it. Thank you for the response and for opening an issue! Looking forward to it! :)

**Comment by cagnulein** [comment]
#95
