### ISSUE TITLE
QZ App iOS: Lock Out Technogym Myrun Speed & Inclination Paddles When QZ Paused.

### ISSUE THREAD

**Issue by brumohr** [cagnulein/qdomyos-zwift#620]
**Is your feature request related to a problem? Please describe.**

Upon initialization, QZ is paused, ie, Start/Pause button flashing red which is a good thing.  However, the user can still increase Myrun belt speed or inclination using the Myrun increase/decrease paddles with the following results:
-  QZ Start/Pause still paused and flashing red.
-  Zwift avatar begins running in Zwift
-  Myrun speed/inclination increases according to user input and QZ app follows.
-  In this situation I think auto inclination does not work.  I think it only works when QZ app Start/Pause button has been tapped to Start.  This requires verification.

**Describe the solution you'd like**
- First choice fix would be to "lock out" Myrun speed and inclination paddles whenever QZ app is Paused so that they remain inoperative until the user presses the QZ app Start/Pause button to Start resulting in:
- QZ Start/Pause button now shows Pause and not flashing red.
- Myrun Inclination and Speed paddles become operative.

**Describe alternatives you've considered**
- Second choice fix would be to have the QZ app Start/Pause automatically change from a Paused to Start mode extinguishing red flashing LED if the user uses either the Myrun Speed or Inclination paddles to increase speed or inclination.
- If, after running for some time, the user pauses the run then Myrun speed and inclination should go to 0 as they do now.
- If user uses Myrun speed or inclination paddles while QZ paused, then QZ starts with Start/Pause button LED extinguishing.

**Comment by cagnulein** [comment]
> * First choice fix would be to "lock out" Myrun speed and inclination paddles whenever QZ app is Paused so that they remain inoperative until the user presses the QZ app Start/Pause button to Start resulting in:

unfortunately there is no way to do it from bluetooth, so we should go with the alternative.

> Second choice fix would be to have the QZ app Start/Pause automatically change from a Paused to Start mode extinguishing red flashing LED if the user uses either the Myrun Speed or Inclination paddles to increase speed or inclination.

this is totally doable. Are you ok if we will proceed with this one?

**Comment by brumohr** [comment]
>Second choice fix would be to have the QZ app Start/Pause automatically change from a Paused to Start mode extinguishing red flashing LED if the user uses either the Myrun Speed or Inclination paddles to increase speed or inclination.
> 
> this is totally doable. Are you ok if we will proceed with this one?

This would be great.  

1. Upon booting QZ initially Start/Stop comes up as "Paused", then user has option to start run by either:
- User taps QZ Start/Pause to Start:  Game starts, QZ Start/Pause to Start and red LED extinguishes
or
- User taps Myrun Speed paddle:  Game starts, QZ Start/Pause to Start and red LED extinguishes (_this is not happening with current version.  Start/Stop remains "Stopped" with red LED flashing._)

2. When in-game after run has already started and user taps QZ Pause:
- Run pauses, QZ Start/Pause goes to Pause and blinking red LED
- Myrun to standby with speed and inclination to 0.
- To resume, go back to (1) above.

If not a huge time investment, I say lets do it! ;-)

**Comment by cagnulein** [comment]
done, @brumohr send me as always an email as a reminder

**Comment by brumohr** [comment]
>QZ - qdomyos-zwift 2.10 (8) is ready to test on iOS and watchOS

QZ app Start/Pause works perfectly now.  Upon initialization QZ app Start/Pause is Paused with red blinking LED.  Myrun is in standby and Myrun speed paddle in inoperative and has no effect.  Tap QZ Start/Pause to Start and Myrun now activates and Myrun speed paddle operative.  Pausing and restarting using QZ app Start/Pause button works as expected with Myrun going into standby when QZ app paused.  Works very nicely, thanks.

This ticket can be closed imo.  However, I did notice that when running on zwift meetup testing this QZ version that the cadence as seen on zwift is very erratic and hardly ever reads the correct cadence (spm or double the rpm shown on QZ).  The cadence (rpm) as displayed on the QZ app is solid and accurate.  I didn't have logging turned on but can retest to capture log if you like.

As a cross check, I did a brief test using Technogym LIVE paired to Zwift and cadence was stable and accurate.  Let me know if a new bug issue should be created and will do so.  Also let me know if you like a log.

Finally, I noticed that ver 2.10.8 is shown as 2.10.7 on the app itself at bottom of settings page.

**Comment by cagnulein** [comment]
> > QZ - qdomyos-zwift 2.10 (8) is ready to test on iOS and watchOS
> 
> Love the improvement. Upon initialization QZ app Start/Pause is Paused with red blinking LED. Myrun is in standby and Myrun speed paddle in inoperative and has no effect. Tap QZ Start/Pause to Start and Myrun now activates and Myrun speed paddle operative. When in game, pausing and restarting using QZ app Start/Pause button works as expected with Myrun going into standby when QZ app paused. Works very nicely, thanks.

Great!

> This ticket can be closed imo. 

Ok!

> However, I did notice that when running on zwift meetup testing this QZ version that the cadence as seen on zwift is very erratic and hardly ever reads the correct cadence (spm - double the rpm shown on QZ). The cadence (rpm) as displayed on the QZ app is solid and accurate. I didn't have logging turned on but can retest to capture log if you like.

Yes please, open a new bug with the debug file.

> Finally, I noticed that ver 2.10.8 is shown as 2.10.7 on the app itself at bottom of settings page.

Yeah, my fault, i forgot this
