### ISSUE TITLE
[BUG] Distance/Calories bug in DomyosT900C

### ISSUE THREAD

**Issue by CiccioFritz79** [cagnulein/qdomyos-zwift#621]
**Describe the bug**
in the last QZ test version, the calories value are written in the distance field on T900C display and viceversa (the distance displaied in QZ is written in the calories field on T900C)

**Screenshots**
![BUG Calorie-KM](https://user-images.githubusercontent.com/95940420/151126314-3d03e66b-d046-4e4a-906e-7dd02d6ca5d2.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS 15.1
 - Version: latest testflight
 
**Append a debug log**
[debug-mar_gen_25_21_17_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7939925/debug-mar_gen_25_21_17_49_2022.log)

**Comment by cagnulein** [comment]
i didn't change anything on this side, so it was in this way since forever? could you try to go back to previous versions to double check it?

**Comment by CiccioFritz79** [comment]
Sure. I try some version today and i report where works right.

**Comment by CiccioFritz79** [comment]
simply swith in option "Fix distance in dispplay was disabled after update. All ok. Thanks
