### ISSUE TITLE
[BUG] - Set the value <0 in Watt Offset

### ISSUE THREAD

**Issue by Miguelll86** [cagnulein/qdomyos-zwift#622]
Hi Roberto, as write you before, when I set the value <0 in Watt offset (Advance Setting tag), Zwift not ready the value and if I stop to cycling start the default power of 2000w. When I restart, everything returns as before.

I use iPhone XS Max for run qzdomyos app

Zwift run on the Mac 

Thanks

**Comment by cagnulein** [comment]
done @Miguelll86 it will be in the version 2.10.8
send me an email to roberto.viola83 at gmail.com to receive the beta later today

**Comment by Miguelll86** [comment]
Ok Thanks, I'll send you email in few minutes

**Comment by Miguelll86** [comment]
Hi robert, can you send me the last version? with the patch at bug of Set the value<0? Thank

**Comment by cagnulein** [comment]
@Miguelll86 hi, send me again a mail so I will send you it. Thanks

**Comment by cagnulein** [comment]
@Miguelll86 you have to send me the mail here 

roberto.viola83 at gmail.com 

:)

because otherwise i can't know where to send it :)
