### ISSUE TITLE
Timing difference between QZ and strava

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#623]
Originally posted by Gary S.
[Tue Jan 25 08_07_21 2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/7941731/Tue.Jan.25.08_07_21.2022.zip)

Average Speed: 10.6
Max Speed: 49.6
Calories burned: 1282
Distance: 36.0
Average Watt: 56
Max Watt: 166
Average Watt/Kg: 0.6
Max Watt/Kg: 1.8
Average Heart Rate: 0
Max Heart Rate: 0
Total Output: 681
Elapsed Time: 03:24:12
Moving Time: 03:24:12
Weight Loss (Oz): 5.86
Average Cadence: 52
Max Cadence: 242
Average Resistance: 3
Max Resistance: 3
Average Peloton Resistance: 25
Max Peloton Resistance: 25

![Screenshot_20220125-110414](https://user-images.githubusercontent.com/48216/151164887-1888bf61-2d66-4b14-840b-f3ae5f42bb8d.jpg)

**Comment by cagnulein** [comment]
[debug-Tue_Jan_25_04_14_14_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/7942622/debug-Tue_Jan_25_04_14_14_2022.log.zip)

**Comment by cagnulein** [comment]
i analyzed it. Strava counts the moving time as "end time - start time" ignoring the moving time that i wrote correctly in the file. DId you try to change this to "virtual ride" in strava?

**Comment by cagnulein** [comment]
Virtual ride fixes the issue

**Comment by N5PHT** [comment]
So is there a Beta that fixes this? I am still just uploading manually. If the automated upload to Strava was a virtual ride I think that would work?

**Comment by cagnulein** [comment]
I didn't fixed it yet. I will do in the next days and i will let you know



Il giorno dom 13 feb 2022 alle ore 14:58 N5PHT ***@***.***>
ha scritto:

**Comment by N5PHT** [comment]
Great - thanks

**Comment by cagnulein** [comment]
@N5PHT modification done. Could you please send me an email to roberto.viola83 at gmail.com indicating this ticket and if you're on android or ios? So will send you the beta with this fix. Thanks

**Comment by N5PHT** [comment]
Thanks for the fix. Roberto I am on Android.

Gary Stone

**Comment by N5PHT** [comment]
Tried the beta but no success. Did a test short ride and took a shower then another short ride and QZ accurately  recorded total elapsed time 11 minutes. But Strava showed 20 plus minutes as the elapsed time. The QZ readout I the email showed the correct 11 minutes.

**Comment by N5PHT** [comment]
The QZ email:
Average Speed: 11.1
Max Speed: 14.4
Calories burned: 63
Distance: 2.1
Average Watt: 46
Max Watt: 71
Average Watt/Kg: 0.5
Max Watt/Kg: 0.8
Average Heart Rate: 0
Max Heart Rate: 0
Total Output: 31
Elapsed Time: 00:11:15
Moving Time: 00:11:15
Weight Loss (Oz): 0.29
Average Cadence: 54
Max Cadence: 70
Average Resistance: 0
Max Resistance: 0
Average Peloton Resistance: 0
Max Peloton Resistance: 0


QZ version: 2.10.27 - Android
Device: I_EB
HR Device: I_EB

**Comment by cagnulein** [comment]
@N5PHT i didn't upload the beta yet. i will do today or tomorrow:) that's why is not working :)

**Comment by N5PHT** [comment]
Oh ok - thanks Roberto.

Gary Stone

**Comment by cagnulein** [comment]
@N5PHT new version is online. Did you update it?

**Comment by cagnulein** [comment]
so the problem was not about the virtual ride. the only modification that i did was forcing the fit file as virtual ride.

so i will revert this at this point

**Comment by N5PHT** [comment]
Thanks. I don't really understand because once before the virtual upload
manually seemed good? I will keep experimenting.

Is there any outcome difference in just stopping for 30 minutes or so and
starting back as opposed to hitting the pause button to take a break?

Gary Stone

**Comment by cagnulein** [comment]
yes it will make a difference for strava because they're also looking about start time and stop time. so pause will make a difference for them

**Comment by N5PHT** [comment]
I will experiment today and tomorrow.

Gary Stone

**Comment by N5PHT** [comment]
Please don't change it back yet and I will try utilizing the pause feature
and experiment and let you know.

Gary Stone

**Comment by cagnulein** [comment]
ok I already did but i can re-revert if you think it could be useful. Anyway i will not release a version today so you are free to go with this one

**Comment by N5PHT** [comment]
WORKED PERFECTLY. So please leave in the change. I left QZ running but took
2 breaks (around 30 minutes each) but utilized the PAUSE button and total
was 1:28 and QZ and Strava agreed!!

Excellent Roberto.  I would like to make a post on the Facebook page so
others know?

Gary Stone

**Comment by N5PHT** [comment]
WORKED PERFECTLY. So please leave in the change. I left QZ running but took 2 breaks (around 30 minutes each) but utilized the PAUSE button and total was 1:28 and QZ and Strava agreed!!

**Comment by cagnulein** [comment]
Great! So I will revert it again :)
Yes sure post about the fix
