### ISSUE TITLE
[BUG] App crashes when connecting to iconsole+ bike

### ISSUE THREAD

**Issue by abolsen** [cagnulein/qdomyos-zwift#624]
**Describe the bug**
App crashes when I open it, trying to connect to my Abilica Steam UB VIII bike.

**To Reproduce**
1. Go to Settings, enable iconsole
2. Restart app
(app crashes)

**Expected behavior**
Should connect without error to the bike.

**Screenshots**
![IMG_1184](https://user-images.githubusercontent.com/6937877/151170879-4193e5e5-60e2-44f7-a88c-2083d4a060d4.PNG)
![IMG_1182](https://user-images.githubusercontent.com/6937877/151170892-c3b26d47-65eb-4a3e-95f8-af2a4d7d1ad5.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS
 - Version: 2.9.47
 - 
**Append a debug log**
  [debug-ons__jan__26_14_01_12_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7942024/debug-ons__jan__26_14_01_12_2022.log)

**Comment by cagnulein** [comment]
done, i'm sending you an update in a couple of hours. Thanks

**Comment by cagnulein** [comment]
So we can close this @abolsen ?

**Comment by abolsen** [comment]
Yes, thanks again
