### ISSUE TITLE
[REQ] resistance conversion for Horizon GR7 bike for use with Peloton program

### ISSUE THREAD

**Issue by Trinhpthai** [cagnulein/qdomyos-zwift#625]
Bike has 12 resistance levels

**Comment by cagnulein** [comment]
done @Trinhpthai send me an email to roberto.viola83 at gmail.com indicating this ticket and if you're on android or ios to receive the beta
Remember to close the ticket after :)

**Comment by Trinhpthai** [comment]
Hi Roberto,
Sorry for misunderstanding...yes I thought I sent you email which you replied to? (See screenshot).

 Have you built yet? If you haven't, I have been having Bluetooth issues with this bike over the last 48hour which a tech person has not been able to fix despite firmware upgrade and Bluetooth card so today I have actually asked for a refund on the bike and will look at getting the echelon ex3 instead.  So if not done maybe save your time for something else? If you have done already, hopefully can help another GR7 owner. Sorry for the inconvenience!

Regards,
Trinh

[Image]


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Trinhpthai** [comment]
Thanks for your time and help Roberto.
Looking forward to using QZ with the echelon bike

All the best,
Trinh

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
