### ISSUE TITLE
[BUG] Cannot turn off "Heart Rate outside FTMS" mode on Android

### ISSUE THREAD

**Issue by ezankel** [cagnulein/qdomyos-zwift#638]
**Describe the bug**
I have attempted to turn off "Heart Rate outside FTMS" mode on two android devices, one running Android 11 and the other running Android 12. However, the change never saves upon restarting QZ. This prevents other apps (such as Peloton) from pairing with a heart rate monitor.

**To Reproduce**
1. Open QZ, go to settings
2. Click on Heart Rate settings
3. Toggle "Heart Rate outside FTMS" _OFF_
4. Restart QZ

**Expected behavior**
"Heart Rate outside FTMS" remains toggled off.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 2, Pixel 5a
 - OS: Android 
 - Version Android 11, Android 12

**Comment by cagnulein** [comment]
It's a android limitation when the android version is > 9 ;)
