### ISSUE TITLE
[REQ] Resistance limits for ERG mode 

### ISSUE THREAD

**Issue by fulldanad** [cagnulein/qdomyos-zwift#639]
ERG mode adjusts the resistance to best fit the required watts.

in order to do so it uses all available resistance levels.

My bike has 15 levels of resistance and when it gets above 8-9 it gets really tough to maintain the rythm for long. So when ERG requests level 15, it kills my legs and this is the end of my training session.

On the other end, I don't want to go below 3 as it is then to easy and I prefer to maintain a minimum resistance of 3.

So it would preferable for me if ERG mode would only adjust between 3 and 7 during my trainings.

Could you make such limitations parameter available in the settings panel ?

**Comment by cagnulein** [comment]
@fulldanad done! write me an email to roberto.viola83 at gmail.com indicating this ticket and also indicate if you're on iOS or android. I will send then the beta.

**Comment by cagnulein** [comment]
@fulldanad did you try it?

**Comment by fulldanad** [comment]
I just got the updated beta version installed. I should be trying at noon.

**Comment by fulldanad** [comment]
It works perfectly, thanks 🙏😉

**Comment by cagnulein** [comment]
Great!
