### ISSUE TITLE
[BUG] target resistance drops to 5

### ISSUE THREAD

**Issue by Elepage11** [cagnulein/qdomyos-zwift#643]
**Describe the bug**
Target resistance drops to 5 when connects to zwift

**To Reproduce**
1. Connect to qz app with iphone
2. Connect to zwift on apple tv
3. Pair zwift with qz app
4. Target resistance drops to 5

**Expected behavior**
Would expect target resistance to change around 20 based on incline vs around 5

**Screenshots**
![6634E2E8-AA13-495E-9B7E-4287C3C60844](https://user-images.githubusercontent.com/98956336/152348124-d143ebf1-189e-4cf0-8023-914aab9ada4d.png)
![BF0732BD-F6FF-465C-95A1-FD29E5708B7D](https://user-images.githubusercontent.com/98956336/152348126-c1887144-acf5-491c-8497-c43f72c4b838.png)

**Smartphone (please complete the following information):**
 - Device: iphone xr apple tv and schwinn ic4
 - Version [e.g. 

[debug-jeu__févr__3_07_42_34_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/7994740/debug-jeu__fevr__3_07_42_34_2022.log)

 
  
**Additional context**

**Comment by cagnulein** [comment]
@Elepage11 fixed! it will be in the next beta. send me an email to roberto.viola83 at gmail.com indicating this ticket and that you're on ios and i will send you the new version later today. Thanks for reporting this
