### ISSUE TITLE
[BUG] Fassi F 9.4 HRC

### ISSUE THREAD

**Issue by floresax** [cagnulein/qdomyos-zwift#646]
Il mio Fassi F 9.4 HRC viene riconosciuto ma non trasmette i dati, uso un Oppo Reno 2 con Android 11.
allego il file di log
[debug-Fri_Feb_4_12_16_31_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8002662/debug-Fri_Feb_4_12_16_31_2022.log)
.

**Comment by cagnulein** [comment]
@p3g4asus sorry to bother you again, but probably this week is the week of the fitshow. Could you help me with this too?

**Comment by p3g4asus** [comment]
Same problem as #641

**Comment by floresax** [comment]
> Same problem as #641. So [this commit](https://github.com/p3g4asus/qdomyos-zwift/commit/b0488128f5921c92c05f1b843e43fadc19bc3742) should fix it (or at least should be tested to see if it fixes this issue).

Non ho risolto nemmeno con la versione 2.10.17, una volta ha inclinato il tapis e portato la velocità a 0.5 da 1 a cui era impostata. Anche il tempo rimane a 0.
Allego i log
[debug-Fri_Feb_4_14_56_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8003659/debug-Fri_Feb_4_14_56_11_2022.log)
[debug-Fri_Feb_4_14_58_29_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8003660/debug-Fri_Feb_4_14_58_29_2022.log)
[debug-Fri_Feb_4_14_59_35_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8003661/debug-Fri_Feb_4_14_59_35_2022.log)

**Comment by cagnulein** [comment]
@floresax puoi raccogliere i log dall'applicazione nativa del tuo tapis seguendo questo metodo https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device ?

**Comment by floresax** [comment]
usando  Anyrun
17:22 SPEED +/-
17:23 INCLINE +/-
17:24 PAUSE
17:25 STOP
[hci.zip](https://github.com/cagnulein/qdomyos-zwift/files/8004772/hci.zip)

GRAZIE
CIAO

**Comment by cagnulein** [comment]
@floresax OK we will check them in the next days
@p3g4asus hAs already a clue

**Comment by cagnulein** [comment]
@floresax Update is live! Be sure to enable the anyrun setting in the fitshow section 
Let me know

**Comment by floresax** [comment]
Avete fatto degli ottimi passi avanti, ma ci sono ancora alcune cose che non vanno.
Intanto il Tapis ha due tasti uno Start/Pausa e uno Stop, se in QZ premo pause sul tapis si preme Stop sul tapis, e quindi azzera l'attività.
Quando avvio QZ non c'è il bottone Start cliccabile, è già con la scritta "Pause"
La velocità, l'inclinazione, i bpm funzionano.
Le calorie sono completamente sballate per 1 minuto 1256.
Il campo Elapsed durante il funzionamento è corretto ma appena si ferma l'attività il valore cresce in modo esponenziale, tipo al posto di 1 minuto segna 3:58:58
Fatemi sapere se serve che alleghi qualcosa.
Grazie

**Comment by cagnulein** [comment]
@floresax si un debug log è necessario per capire.
@p3g4asus per la sincronia di start e stop sistemo io. L'ho già fatto per altri tapis

**Comment by p3g4asus** [comment]
I can confirm I need the debug log to sort out those problems.
Thank you for collaboration.

**Comment by p3g4asus** [comment]
> [btsnoop_hci_20220211_164434.zip](https://github.com/cagnulein/qdomyos-zwift/files/8050086/btsnoop_hci_20220211_164434.zip)
> 
> Ecco il log e alcune immagini Segnalo che la vostra app segna il correttamente tempo dell'attività, mentre il tapis si attarda di 5" ogni 1', ovviamente il vostro timer è più utile, ma per "sincronia" forse si potrebbe mettere un'opzione nei settaggi "true timer"?
> 
> grazie

Scusa: mi sarebbe più utile il log di QZ quando canna i dati.
Grazie
I am sorry I must not have been enough clear. I need more QZ debug log when it is reporting crazy data.
Thank you.

**Comment by p3g4asus** [comment]
Can you confirm that QZ is reporting also wrong distance?
Thank you.

**Comment by p3g4asus** [comment]
I think I found the bug that is affecting calorie and distance data. The debug log could be useful to investigate the timer growing exponentially problem.

**Comment by floresax** [comment]
ecco il log, ora sembra che il tempo totale sia ok, sono ancora da corregere calorie e distanza
[debug-Sat_Feb_12_19_27_45_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8054507/debug-Sat_Feb_12_19_27_45_2022.log)
[debug-Sat_Feb_12_19_29_29_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8054508/debug-Sat_Feb_12_19_29_29_2022.log)
.

**Comment by cagnulein** [comment]
@floresax @p3g4asus  ha fatto delle modifiche, domani cerco di rilasciare

**Comment by cagnulein** [comment]
@floresax ok i fixed also the syncronizathion between start and stop from the UI and the treadmill itself. It will be in the 2.10.27 along with the @p3g4asus mods

**Comment by floresax** [comment]
con la versione 2.10.27 sembra rimasto solo il problema che se premo "pause"in realtà fa "stop", il resto sembra tutto sistemato, domani farò un test migliore.
grazie

**Comment by cagnulein** [comment]
@floresax dal punto di vista di qz non c'è differenza tra pause e stop. nel senso quel tasto ferma il nastro. tu cosa ti aspettavi?

**Comment by floresax** [comment]
la pausa del tapis non azzera i totali e puoi riprendere la sessione, sul tapis i tasti non sono separatri, start e pausa sono lo stesso tasto, stop è separato.

**Comment by p3g4asus** [comment]
> hah ok, @p3g4asus sui comandi bt sono 2 separati? se si ti faccio la modifica domani

Domani riguardo bene il codice e vedo se esiste un comando di pause. Sicuramente esiste. Devo capire qual é.

**Comment by cagnulein** [comment]
@floresax ho fatto le modifiche. Conto di rilasciare oggi se riesco. Sarà la versione 2.10.28 
Fammi sapere

**Comment by cagnulein** [comment]
rilasciato @floresax quando provi aggiorna il ticket. Grazie

**Comment by cagnulein** [comment]
@floresax qualche news?

**Comment by floresax** [comment]
Scusa ma non sono stato bene e non sono riuscito a provare, spero domani.

Il mar 22 feb 2022, 10:22 Roberto Viola ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@floresax azz mi dispiace tantissimo! Nessuna fretta, controllavo solo che fosse tutto ok ;)

**Comment by floresax** [comment]
> @floresax qualche news?
ciao ieri ho finalmente provato il tapis e mi sembra che vada tutto molto bene. grazie.

**Comment by cagnulein** [comment]
grande! bella notizia! chiudo il thread. In caso ti servisse altro sentiti libero di riaprirlo!
