### ISSUE TITLE
U.K. Horizon 7.0 AT 02 (Aug2020) does not connect

### ISSUE THREAD

**Issue by Woodsl1972** [cagnulein/qdomyos-zwift#648]
QZ cannot find tread when tread switched on.
When manually connect tread to QZ no metrics are displayed.
If select power sensor as a treadmill then select tread from devices list again some metrics display but these are incorrect.

**Screenshots**
![Sat Feb 5 13_10_09 2022](https://user-images.githubusercontent.com/99087233/152650088-e3d645ad-3a07-46fc-a18c-bc6c8cefccf5.jpg)

![4FBFC038-D29A-406F-B7FB-6C811AF420BA](https://user-images.githubusercontent.com/99087233/152650102-b18b1247-8c85-4a08-a3c6-20f886227cee.png)

![image](https://user-images.githubusercontent.com/99087233/152650370-70769db3-aeab-447e-a1d5-544e434478ba.png)

**Smartphone (please complete the following information):**
 - Device:iPhone 11
 - OS: [e.g. iOS15.2
 - Version - will updates to 15.3

**Append a debug log**
[debug-Sat_Feb_5_12_51_43_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8008370/debug-Sat_Feb_5_12_51_43_2022.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@Woodsl1972 done! it will be in the next beta. send me an email to roberto.viola83 at gmail.com indicating this ticket and if you're on ios or android. I will send you it tomorrow

**Comment by Woodsl1972** [comment]
Wow thank you!

**Comment by Woodsl1972** [comment]
[Uploading debug-Sat_Feb_5_20_00_51_2022.log…]()

**Comment by cagnulein** [comment]
@Woodsl1972 The log is corrupted, you have to wait the end of the upload . Thanks

**Comment by Woodsl1972** [comment]
[debug-Sat_Feb_5_20_00_51_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8008901/debug-Sat_Feb_5_20_00_51_2022.log)

**Comment by cagnulein** [comment]
@Woodsl1972 fixed! (at least the metrics reading). it will be in the next beta. send me an email to roberto.viola83 at gmail.com indicating this ticket and if you're on ios or android. I will send you it later today. Thanks for the feedback as usual!

**Comment by Woodsl1972** [comment]
Thanks Roberto. Will let you know how it goes.

**Comment by cagnulein** [comment]
send me an email so
i will send you the beta right now @Woodsl1972

**Comment by Woodsl1972** [comment]
Instant connection and metrics all seem to be working 😀. Thank you so much 👍🏻👍🏻

**Comment by cagnulein** [comment]
wow great! can we close this or you need to do some more test?

**Comment by Woodsl1972** [comment]
It seems to do what I need it to do!
