### ISSUE TITLE
[REQ]Add support for speed and incline on NordiTrack s30 treadmill

### ISSUE THREAD

**Issue by gegge10** [cagnulein/qdomyos-zwift#652]
**Is your feature request related to a problem? Please describe.**
I want to use zwift with my NordiTrack s30 threadmill and have zwift control incline and sepeed. Not able to send speed and incline commands to qdomyos-zwift today, but ifit are able to control speed and incline.

Attached log
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8013450/btsnoop_hci.log)

**Comment by gegge10** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8013445/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@gegge10 in this log which speed and inclination values did you change? I mean which values. Thanks

**Comment by gegge10** [comment]
@cagnulein both where changed, speed from 0-3.5 and incline from 0-6

**Comment by gegge10** [comment]
speed was changed first and then incline

**Comment by cagnulein** [comment]
could you redo with more changes? i need to see a pattern in the log. Thanks

**Comment by gegge10** [comment]
@cagnulein 
Here I did 10 times speed increase by 0.1 km/h after that I did 10 times speed decrease by 0.1 km/h.
After the speed test I did the same for incline, 10 times 0.5 % incline followed by 10 times 0,5 % decline. Hope this helps.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8014441/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@gegge10 perfect! i see them clearly now! i'm adding them!

**Comment by cagnulein** [comment]
#592 @gegge10 it's the same of this. Are you on the android beta version? you need to enable the nordictrack t65s setting in QZ. Let me know

**Comment by gegge10** [comment]
@cagnulein I have version 2.8.142, do I need to install other app from appstore to get beta? Only see Norditrack 10 in treadmill settings in app now

**Comment by cagnulein** [comment]
@gegge10 hah you are on iOS? If so send me an email to roberto.viola83 at gmail.com indicating this ticket and i will send you the beta for iOS

**Comment by gegge10** [comment]
I am on Android
<img width="276" alt="image" src="https://user-images.githubusercontent.com/226813/152778160-4f25111d-4fbe-4dd7-82f0-c61f966e3281.png">

**Comment by cagnulein** [comment]
@gegge10 ok so send me the email to my email so i can add you to the private beta

**Comment by gegge10** [comment]
I got the beta app now and enabled T.65 but no action when clicking in the app on speed or incline change

![Screenshot_20220207-134416](https://user-images.githubusercontent.com/226813/152790459-bc43788d-cb6a-4eef-9eaf-c275783594c3.jpg)

![Screenshot_20220207-133848](https://user-images.githubusercontent.com/226813/152790626-24e75606-41c3-4c4e-bafa-d376ba49e48c.jpg)

**Comment by cagnulein** [comment]
@gegge10 thanks, could you please send me a fresh debug log where you're pressing the plus/minus button of the tiles so i can compare it to the hci snoof? Thanks

**Comment by cagnulein** [comment]
@gegge10 there is something different in the init phase, maybe that's the reason, i'm adding a special setting for this treadmill too

**Comment by cagnulein** [comment]
done, i'm building. You will see a version 2.10.21 in an hour or so. remember to turn off the current treadmill setting and enable your s30 new setting and restart QZ. Let me know

**Comment by gegge10** [comment]
@cagnulein was the change deployed to google play? Not seeing 2.10.21 install

**Comment by cagnulein** [comment]
update is live @gegge10

**Comment by cagnulein** [comment]
Great! Very quickly fix :D
