### ISSUE TITLE
Support for Whipr kayak please

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#653]
2nd one: please support Whipr.

This is a rower, SUP, Kayak erg, and ski erg

A single Whipr broadcasts as a FTMS rowing erg.

My interest is the kayak where you use two Whipr units. I guess it might be easiest for QZ to connect to one and double everything? Maybe there could be a toggle to toggle kayak mode on or off.

To emulate a concept2 would enable most app compatibility, I suspect (EXR, Swell done).

I will attach nrfconnect images of only one Whipr when it is in Kayak mode.

**Comment by jonathancolledge** [comment]
![Screenshot_20220206_170248_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764129-1d45a64b-a2dd-4716-80fd-56c503b626ab.jpg)
![Screenshot_20220206_170315_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764143-b53f4eb0-9443-4b4b-8b6d-fce34bb80962.jpg)
![Screenshot_20220206_170323_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764150-c7108d1c-dcdd-4e54-ac20-8d7f30a7ff08.jpg)
![Screenshot_20220206_170328_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764160-c7a5c239-cbe8-4348-9435-53c6e31be12d.jpg)
![Screenshot_20220206_170337_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764174-2e82100e-efbb-4bbf-a661-ee1835313cdd.jpg)
![Screenshot_20220206_170341_no nordicsemi android mcp](https://user-images.githubusercontent.com/4342400/152764184-ada2a6f8-2326-46d5-8aad-c4d16e3dc9c5.jpg)

**Comment by cagnulein** [comment]
done @jonathancolledge but i don't understand the double thing. Could you please explain it better?

**Comment by jonathancolledge** [comment]
So on the rower you use one Whipr unit, but when setting up for kayaking one end of the "paddle" is attached to one unit and the other end to another unit. As far as I can see, they don't talk to each other so if you attach an app like Kinomap it'll only connect to one and just get half the strokes. I think! Maybe don't do more work till I check!

**Comment by cagnulein** [comment]
now i got it! for the qz point of view i can just connect to one of them and sending the double rate if needed
let me know

**Comment by jonathancolledge** [comment]
I have confirmed with Whipr - it'll only count half as the units don't talk to each other. So either it needs both to be connected or as I suspect easier, just a toggle to double the power, pace, and stroke rate from one. (If using the doubling method, a toggle in the settings would work well as it'd allow compatibility with a single unit for rowing like how many people will use it, or when activated it'll allow kayaking and swimming).
Thanks,
Jonathan

**Comment by jonathancolledge** [comment]
Hold off! Sorry! This is their email[]()![Screenshot_20220219_062725_com.microsoft.office.outlook.jpg](https://user-images.githubusercontent.com/4342400/154806142-96111045-96f5-48f8-b3fb-092c47759e11.jpg) I think I need to clarify if the unit auto doubles when set to kayak. (Unless you can see an easy way for QZ to connect to both as that would be much better as any left :right imbalance would be accounted for)

**Comment by cagnulein** [comment]
@jonathancolledge I guess we can easily test it. Did you already try the implementation in the beta? About the possibility to connect to both from qz: it's possible but it will require a lot of coding so, first of all, let's try the single implementation 
Let me know

**Comment by jonathancolledge** [comment]
> @jonathancolledge I guess we can easily test it. Did you already try the implementation in the beta? About the possibility to connect to both from qz: it's possible but it will require a lot of coding so, first of all, let's try the single implementation 
> Let me know 

Cool. I will test on Thursday then. I tested the SwimFast before I left for holiday and that worked 🙂

**Comment by jonathancolledge** [comment]
It works perfectly. Whipr were very unclear in how it handles stroke rate, but actually, what happens, is that if you set both the Whiprs to kayak, the units double the stroke rate independently and don't talk to each other. That means connecting to one unit you get one side's strokes doubled. I'm happy with that - it's just like having a single side power meter on a bike. Thanks.

**Comment by cagnulein** [comment]
Cool @jonathancolledge ! So we can close this already?!

**Comment by jonathancolledge** [comment]
Yes! Can close!

**Comment by cagnulein** [comment]
[debug-lun-ago-22-11-48-35-2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9393391/debug-lun-ago-22-11-48-35-2022.log.txt)
filtering 0 wattage

**Comment by jonathancolledge** [comment]
[Row_QZ.zip](https://github.com/cagnulein/qdomyos-zwift/files/9544965/Row_QZ.zip)

I think this is a Whipr fit file from QZ

**Comment by jonathancolledge** [comment]
Sorry it is short. I can't get either the Whipr app or QZ to connect now Huawei have updated my phone to EMUI 12. I will have to use the Pi and my other phone.

**Comment by cagnulein** [comment]
> Sorry it is short. I can't get either the Whipr app or QZ to connect now Huawei have updated my phone to EMUI 12. I will have to use the Pi and my other phone.

android 13? you have to use the beta 2.11.45 and higher. do you have it?

**Comment by jonathancolledge** [comment]
> > Sorry it is short. I can't get either the Whipr app or QZ to connect now Huawei have updated my phone to EMUI 12. I will have to use the Pi and my other phone.
> 
> android 13? you have to use the beta 2.11.45 and higher. do you have it?

Yes, got beta, but it is only Android 10. It updated this morning to the Huawei skin/whatever it is EMUI 12. QZ saw nothing, Whipr app saw nothing. Will try and figure it out more tomorrow morning when I find my other phone.

**Comment by cagnulein** [comment]
ok, i think it could be only to enable some permissions in the phone settings
