### ISSUE TITLE
Echelon Sport Connect & Fire Tablet HD

### ISSUE THREAD

**Issue by bdpna** [cagnulein/qdomyos-zwift#655]
My echelon sport connect shows in my bluetooth device list but "refuses connection" with my Amazon Fire Tablet 2nd generation (older tablet, just using for the bike).  Is there a workaround in QZ or if I can't get the bike connected to my tablet via the bluetooth menu am I stuck?  Bike beeps when I attempt to connect then just returns a "connection refused" message.  This is the model without a screen so no other way to connect to QZ.

**Comment by cagnulein** [comment]
Hi @bdpna you don't need to pair the device on the Bluetooth settings. Just open qz. Also, in the experimental settings of qz, disable the virtual device setting 
Let me know

**Comment by bdpna** [comment]
Thanks for the reply. The bike connects right up to the QZ app on my iPad but does not connect to QZ on my Amazon gen 2 fire hd tablet. It would appear that the Bluetooth stack on this generation to fire HD tablet running android marshmallow (v6) is not supported. That’s unfortunate as that’s the old tablet I wanted to use with the bike but it maybe is just too old to work even though it has Bluetooth. Maybe it’s too old of a Bluetooth stack?

**Comment by cagnulein** [comment]
yes @bdpna unfortuantely it's not a matter of age it's a matter of bluetooth chip: it doesn't have the hardware capabilites to run the bridge along with a connection to the bike. Unfortunately you have to change tablet :(

**Comment by cagnulein** [comment]
@bdpna unfortunately on android even same Model of phone/tablet could have different bluetooth chip inside so it's really a mess to know which works and which not. If you want to go for sure, go to an old ipad with at least ios15. It will work for sure
