### ISSUE TITLE
Wrong Class [BUG]

### ISSUE THREAD

**Issue by shmaddox** [cagnulein/qdomyos-zwift#660]
**Describe the bug**
Wrong class came up

**To Reproduce**
1. Feb 6, 2021 class plays a non-power zone class

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[debug-Tue_Feb_8_13_31_51_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8027288/debug-Tue_Feb_8_13_31_51_2022.log)

  
**Additional context**

**Comment by cagnulein** [comment]
sorry for the issue. i will check tomorrow

**Comment by shmaddox** [comment]
I haven't had problems with other classes (well, other than the two in one
day issue)...I wonder what's going on!

**Comment by cagnulein** [comment]
@shmaddox fixed! i will send you the new beta later today

**Comment by cagnulein** [comment]
@shmaddox did you try this?

**Comment by shmaddox** [comment]
Shoot, yes, I tried and it worked great. Sorry I forgot to update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
Great @shmaddox thanks!
