### ISSUE TITLE
 [REQ] Support for the BH Fitness i.FDC20 (crosstrainer/elliptical)

### ISSUE THREAD

**Issue by thibaultmol** [cagnulein/qdomyos-zwift#661]
Hi, 

So I ended up buying a BH Fitness  i.FDC20, I already tried to use it with Zwift and Kinomap. 
The crosstrainer has FTMS but seems to transmit it as a bike instead of an elliptical/crosstrainer. When connecting it via kinomap, it gets no data (not the expected data I suppose, i already informed Kinomap about this). 
And Zwift recognizes it only as a bike, while I haven't confirmed it changing resistance, it does seem to be able to tell it can control it. 
But obv using a walking/running speed in a cycling mode doesn't work well, so It'd like to use the app to make it appear either as a faster bike or as a treadmill.

I have attached the bluetooth snoop log when I connected it via Zwift, since BH Fitness has no app of itself to use. (They have a 'strong' partnership with Kinomap for their app experience.

.... But clearly never tried to actually use this (new?) machine with Kinomap before. I'm guessing..)

Hopefully you're able to extract what you need from the log

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8031577/btsnoop_hci.log)

**Comment by cagnulein** [comment]
yes sure i can handle this. I'm adding this in the next beta

**Comment by cagnulein** [comment]
@thibaultmol done! are you on android or ios?

**Comment by thibaultmol** [comment]
Android

**Comment by cagnulein** [comment]
@thibaultmol send me an email to roberto.viola83 at gmail.com indicating this ticket and i will add you to the beta tester

**Comment by thibaultmol** [comment]
It doesn't to recognize it? I can see it flash by when it's searching for
devices, but it doesn't actually stop at b10....

**Comment by thibaultmol** [comment]
2.10.22 is the version I'm on now

**Comment by cagnulein** [comment]
you have to wait version 2.10.24 as i said in the mail :)

**Comment by cagnulein** [comment]
google is reviewing it takes some hours

**Comment by thibaultmol** [comment]
Oh sorry right. I already could update but that was just to the previous
beta. I'll keep you posted

**Comment by cagnulein** [comment]
@thibaultmol great! it's a good step.
attach a debug log and i will add the rest tomorrow

**Comment by thibaultmol** [comment]
I think this should be the right file:
[debug-Wed_Feb_9_17_53_14_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8035031/debug-Wed_Feb_9_17_53_14_2022.log)

**Comment by cagnulein** [comment]
@thibaultmol i confirm you that the speed is not sent by the trainer. So we have different possibilites here:
1) you can tell me the ratio to add fixed in the code so i will multiply the cadence by that factor to have speed (very easy to do)
2) we can use the cadence ratio setting already avaiable in QZ to multiply it with the cadence to obtain the speed (very easy to do, but if it's fixed for all the i.FDC20 as i guess, we should go with the 1.)

Let me know

**Comment by cagnulein** [comment]
@thibaultmol i fixed the heart rate. Also for the resistance: does the BH app allow you to change the resistance?

**Comment by cagnulein** [comment]
@thibaultmol great about the log, so i can get resistance and i also can control it!

yea about the speed, so i will add a fix ratio

i will work on this Hopefully Tomorrow

**Comment by cagnulein** [comment]
@thibaultmol checked the log. Yes Kinomap controls it using the simulation FTMS settings (so sending inclination on the virtual world). If you want i can make the same, so you will have also auto incline on zwift. What do you think?
Or, another way to it is faking the incline command, simulating the % as 15 resistance levels. (this elliptical can also do 0.5% increments on the resistance?)
Maybe, these second option will give you more flexibility in the future with also training programs inside QZ.
Let me know

**Comment by thibaultmol** [comment]
I checked, the resistance control on the elliptical itself
![image](https://user-images.githubusercontent.com/1010226/153596313-963c05e5-b50a-4e25-a3d3-2e8fd4994963.png)
24 levels... :shrug: 

I don't which option is best tbh. I plan to try Zwift, Kinomap, the others, currently just using Peloton (I did see you integration with it, so that's nice.) and who knows, might also use QZ itself yeah, I don't know

**Comment by cagnulein** [comment]
when in kinomap you were at 15% which resistance level did you see? @thibaultmol

**Comment by thibaultmol** [comment]
sorry for the delay. Honestly, I haven't been able to reproduce being able to set the resistance in the kinomap app. It's always stuck on '162' on the segment of the display that previously changed when I changed the resistance in the app.
I've tried every device type with FTMS on kinomap, but none seem to work. So i'm not sure how it actually worked that one time.

I'm still in contact with kinomap, they've given up on getting it working. But I've hammered them they should contact BH Fitness. As they're partners yet the machine doesn't work.

i'll update you once I get it working again

**Comment by cagnulein** [comment]
#912 @thibaultmol are you still interesting on this?

**Comment by thibaultmol** [comment]
Yeah sorry, IRL has gotten very busy for me lately ,I don't have time to look into it atm

**Comment by cagnulein** [comment]
@thibaultmol no problem, i was just letting you know that i fixed the auto resistance issue. when you want i can send you the new beta
