### ISSUE TITLE
Request to add new bicycle model: FYTTER CROSSER CR-11R

### ISSUE THREAD

**Issue by IselcoP** [cagnulein/qdomyos-zwift#662]
Good afternoon,

I recently contacted to consult if my bicycle could be added to be compatible with QZ.

The brand and model of the elliptical bicycle is: Fytter Crosser CR-11R. It has a generic console compatible with IconSole +, Fithiway and Kinomap (I suppose mass manufactured in China because the structure is shared by many market fitness trainers).

Following its attachments two captures with the data that NRF_Connect throws over my model. One is contract and the other expanded but it is both of the Client section.

Thanks and kind regards.

![nRF_Connect_Devices_Collapsed](https://user-images.githubusercontent.com/22306903/153217767-40ecaa1a-3398-4c5d-a049-1fde00ddd3a2.png)
![nRF_Connect_Devices_Expanded](https://user-images.githubusercontent.com/22306903/153217770-530549ef-27c0-4b64-98f4-4b667317bf0a.png)

**Comment by cagnulein** [comment]
great @IselcoP i will try to add it tomorrow! I will let you know when i will be ready to test this

**Comment by cagnulein** [comment]
hi @IselcoP since with these bluetooth characteristics, there are different protocols already implemented on QZ, could you please follow this guide and append here the log https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

You can use the kinomap app or the iconsole+ app if you want.
If you can i will do a better target modification about this.
Thanks

**Comment by IselcoP** [comment]
Good afternoon @cagnulein.

I have made the log as it says in the instructions; however, I have had to do it on an old phone with LineageOS because my current phone uses miui 12.5 and the bug reports are extremely confusing and I can't find the bluetooth information if it collects it at all.

I upload the report that I have captured in LineageOS, the actions have been: connect with the IConsole+ app to the CR11R bicycle, start the activity, gradually increase the resistance to the maximum and reduce it again to the minimum, stop button, disconnection and made of the bug report.

Let me know if the file doesn't fit what you need so we can find an alternative method of logging bluetooth.

Thank you for everything and best regards.

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8053907/btsnoop_hci.log)

**Comment by cagnulein** [comment]
thanks @IselcoP i will check this in the next days!

**Comment by cagnulein** [comment]
good news @IselcoP ! i managed this bike in the version 2.10.17
When you will receive it, remember to enable the hertz bike setting in the toorx/iconsole settings in QZ and restart QZ
As a reminder to send you the beta, send me an email to roberto.viola83 at gmail.com indicating this ticket and the fact that you're under android
Update this ticket when you will try this
Thanks

**Comment by IselcoP** [comment]
Hello again @cagnulein ,

I tried to connect the app today to make sure it had been updated to 2.10.17, unfortunately I have not been able to connect to the bike.

I have tried with the configuration that you have indicated, restarted the application and the phone several times. After enabling some more option and I have not succeeded. The bike is detected but jumps to the next nearby device without connecting to it. 

![Screenshot_20220214-180614_qdomyos-zwift](https://user-images.githubusercontent.com/22306903/153913648-a0271281-2707-4c8e-8965-ac1b7571d6da.png)
.

**Comment by cagnulein** [comment]
@IselcoP hi, i guess you have some settings wrong, send here a debug log following this 

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

thanks

**Comment by IselcoP** [comment]
Hello again @cagnulein 

Sorry for my delay, I've had a lot of work and I couldn't do the log before today.

I'll put it here below to see if we can configure it correctly.

Thanks again for your help and consistency with this topic. All the best.

[debug-Wed_Feb_16_16_40_40_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8081309/debug-Wed_Feb_16_16_40_40_2022.log)

**Comment by cagnulein** [comment]
Hi  @IselcoP i don't know why but your settings aren't avialable in the log file. Could you please send here a screenshot about your iconsole settings in QZ? Thanks

**Comment by IselcoP** [comment]
Hello @cagnulein 

I have made another log, I think that the characteristics are in this one, I have not the slightest idea why they did not appear in the previous one.

If you still need the screenshots, tell me and I capture everything on several screens and paste them with photoshop. Thank you.

[debug-Wed_Feb_16_17_02_36_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8081413/debug-Wed_Feb_16_17_02_36_2022.log)

**Comment by cagnulein** [comment]
no it's not your fault, it's just something stupid on my code but i can't understand what :)
I will test it myself tomorrow. Thanks for the moment

**Comment by IselcoP** [comment]
@cagnulein  Ok then, I'm waiting until further notice. Thanks for the help and hard work and sorry for the inconvenience. Kind regards Roberto.

**Comment by IselcoP** [comment]
Good morning @cagnulein

Good and regular news. The bike connects! but the phone does not receive the information and does not issue orders to the bicycle, the resistance cannot be adjusted and it does not receive any data, no speed, no watts, nothing...

I have noticed that the bike console turns off when connected to IConsole+; however, when it is connected to QZ it stays on (the resistor can be manipulated manually), could it be that some instruction is missing for it to be connected at all?

First of all, thanks for the help so far, of course, with the work you've done, the price of the application is more than compensated, so if you finally get my damn bike to work, I'll owe you some ¿beers, coffee, water with gas..?

This week I will be away for work, so I will read your messages, but I will not be able to test if you make any modifications until Friday at least.

Thanks again for your attention.

A cordial greeting.

**Comment by cagnulein** [comment]
thank you @IselcoP you're very kind!
Could you please post a debug log? it's the only way for me to understand it
Let me know and have a great weekend!

**Comment by IselcoP** [comment]
Here it is, I just did it. With the application connected I have tried to raise the resistance through the program and I have manually raised it on the machine. If you need me to interact with the bike or the program in any specific way let me know.

Thank you for your help and speed and enjoy the weekend too!

[debug-Sun_Feb_20_14_18_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8104043/debug-Sun_Feb_20_14_18_30_2022.log)

**Comment by cagnulein** [comment]
found the issue and fixed @IselcoP ! I will release a new one soon (my wife is at the hospital in these days and i have to stay with her). Please keep a look at the google play for the update, it will be the version 2.10.31 or above

**Comment by cagnulein** [comment]
uploaded, it will be online today! @IselcoP

**Comment by IselcoP** [comment]
Hi again @cagnulein ,

I hope your wife is well, family always comes first, everything else is secondary. I'm sorry I didn't answer earlier, as I told you this week I've been traveling and overworked.

The problem continues, the mobile connects to the bike but does not send or receive any data. The bike operation screen remains active as well (with Iconsole+ it turns off when connected).

Kind regards and I hope everything goes well.

**Comment by cagnulein** [comment]
Hi, thanks. My wife is better now, thanks.
I will check the log tomorrow 
Have a nice Sunday 
R

**Comment by cagnulein** [comment]
fixed @IselcoP it will be in the 2.10.37
Let me know how it will go!

**Comment by IselcoP** [comment]
Good afternoon @cagnulein

Good news, I have been using the program for 2 sessions with no problems.

The truth is that I am very grateful for the treatment, the speed and the diligence that you have shown. I do not regret buying the app at all, I have given you support on buymeacofee and of course I will evaluate the app positively on GPlay. I hope this can help you or encourage your work.

PS: I have started another [thread](https://github.com/cagnulein/qdomyos-zwift/issues/711) with a proposal that could be interesting for the operation of the application in the background. We can close this now.

Thank you very much for everything.

**Comment by cagnulein** [comment]
Great! I'm closing this so. Feel free to reopen it in case you need help
