### ISSUE TITLE
Troubleshooting Stages SC3 powermeter

### ISSUE THREAD

**Issue by rmorenopdx** [cagnulein/qdomyos-zwift#664]
Hello -

I have a stages SC3 bike with power meter 
[debug-Wed_Feb_9_22_37_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8038720/debug-Wed_Feb_9_22_37_25_2022.log)
and trying to use WZ with Peloton. Cadence seems to be communicated/recorded but not resistance. Perhaps my bike doesn’t transmit resistance information? I took a slow test ride and “target” resistance and cadence seem to be received from Peloton, and I’m sending cadence, but not resistance. #

**Comment by cagnulein** [comment]
Hi @rmorenopdx , yes i checked the log and i confirm you that it sends only the metrics that you read in QZ (no resistance) over the standard bluetooth characteristics.

A couple of questions:
1. do you read somewhere (app or bike console) the resistance level?
2. if the 1 is a yes, do you have also an android to collect data about it?

Let me know

**Comment by rmorenopdx** [comment]
Sadly, there is no resistance on the display or in the stages app. This is Disappointing, as it has a power meter on the crank arm. Given that it is reporting power and cadence, it must know resistance. Oh well!

Ray

**Comment by cagnulein** [comment]
@rmorenopdx ok, i guess it's a similiar issue to #634 
I mean we should correlate the peloton resistance to wattage. If we have a table about this i can build up a resistance table for your bike based on wattage. Do you agree? Do you have something similar? Could you please try to looking for it on internet? Thanks

**Comment by cagnulein** [comment]
@rmorenopdx shame on me! i already have this! it's the same thing that i'm doing for the schwinn bikes. I'm adding this immediately

**Comment by cagnulein** [comment]
@rmorenopdx i did it! send me an email to roberto.viola83 @ gmail.com indicating this ticket as a reminder in order to send you the beta. Thanks

**Comment by rmorenopdx** [comment]
It works. The app beta is definitely receiving resistance data, through it's hard to know how it correlates with Peloton resistance. The stages SC3 bike has continuously adjustable magnetic resistance with no numbered settings. On a brief test (10 minute easy rode in Peloton), the resistance level varied form 0 to 150, with the Peloton value being the same. Is there anything I can do to help with the mapping of the resistance data to help creat a stages SC# -> Peloton conversion.

**Comment by cagnulein** [comment]
@rmorenopdx I'm using cadence and power to calculate it that's why it's changing constantly. Send me a debug log with the current version so I can check if the implementation is correct. Thanks

**Comment by cagnulein** [comment]
@rmorenopdx any news?

**Comment by rmorenopdx** [comment]
Thanks for reaching out. In general, it has been working out well, though I admit I’m thinking about a used Peloton if I can find one at a good price.

Thanks!

Ray

**Comment by cagnulein** [comment]
ok so we can close this?

**Comment by rmorenopdx** [comment]
Yes. Let’s close it. ZThanks again
