### ISSUE TITLE
[REQ] get speed from zwift companion app

### ISSUE THREAD

**Issue by december-soul** [cagnulein/qdomyos-zwift#669]
**Is your feature request related to a problem? Please describe.**
currently it is not possible to get the speed, for a treadmill, from Zwift.
Zwift has not enabled this function. So it is not possible that a training plan from Zwift controls the speed of the treadmill. 
For security reasons this may be good, but we know what we are doing :-)

**Describe the solution you'd like**
So now we would have to find an alternative way to get the speed. One possibility would be a screen reader which reads the Zwift screen and OCRs the speed.
A more elegant way would be to pretend to be a companion app. Then we would have access to all data.
It would be a lot of work to get that round but then you would have the full data.

**Additional context**
Here is a project that pretends to be a companion app and would then have access to all data.
https://github.com/talfstad/zwift-mitm

or here a project which analyzes the traffic.
https://github.com/ruffk/ZwiftActivityMonitor

You could write a small program which makes the data available via multicast in the network.

But as I said, this is a lot of work and I have a lot on my mind right now.

**Comment by december-soul** [comment]
here are some more interesting projects.
Some include a protobuffer decoder, which would help a lot.

https://github.com/jeroni7100/zwift-packet-monitor
https://github.com/braddwalker/ZwiftPacketMonitor
https://github.com/SauceLLC/zwift-packet-monitor

**Comment by cagnulein** [comment]
i tried this one https://github.com/jeroni7100/zwift-packet-monitor on my mac, with zwift on my mac too and it gives random values as i ride

<pre>PlayerState {
  id: 2940929,
  worldTime: Long { low: -838432945, high: 53, unsigned: false },
  distance: 64859,
  roadTime: 837099,
  laps: 5,
  speed: 45037264,
  roadPosition: 10030648,
  cadenceUHz: 1349607,
  heartrate: 126,
  power: 190,
  heading: Long { low: 5126373, high: 0, unsigned: false },
  lean: 1010517,
  climbing: 496,
  time: 7406,
  f19: 386727953,
  f20: 16777231,
  progress: 2050,
  justWatching: 0,
  calories: 286511,
  x: -214396.140625,
  altitude: 21935.828125,
  y: 49420.59765625,
  watchingRiderId: 2940929,
  groupId: 0,
  sport: Long { low: 0, hi  sport: Long { low: 0, high: 0, unsigned: false },
  f34: 6464166.5
}
PlayerState {
  id: 1505469,
  worldTime: Long { low: -838432875, high: 53, unsigned: false },
  distance: 3458,
  roadTime: 888214,
  laps: 0,
  speed: 25011244,
  roadPosition: 9771697,
  cadenceUHz: 1089760,
  heartrate: 155,
  power: 200,
  heading: Long { low: 1855429, high: 0, unsigned: false },
  lean: 991115,
  climbing: 24,
  time: 393,
  f19: 851989,
  f20: 33554447,
  progress: 9984,
  justWatching: 0,
  calories: 21450,
  x: -196904.078125,
  altitude: 23384.45703125,
  y: 78884.734375,
  watchingRiderId: 1505469,
  groupId: 0,
  sport: Long { low: 0, high: 0, unsigned: false },
  f34: 344730.5
}</pre>

it seems that zwift is crypting their frames?

**Comment by cagnulein** [comment]
do you have any luck to try them @december-soul  ?

**Comment by cagnulein** [comment]
did you see the same @december-soul  ?

**Comment by december-soul** [comment]
sorry I am busy with another project right now.
It is also possible that the protobuf file is outdated.
I have another project where the description is very up to date but the code is not so clear.
zoffline play but the other side.
In a branch there it is worked on.

Unfortunately I will not be able to do much here.

**Comment by cagnulein** [comment]
> I have another project

which is the other project @december-soul  ?
