### ISSUE TITLE
Mac  M1 version cannot scroll down 

### ISSUE THREAD

**Issue by shuaiwang88** [cagnulein/qdomyos-zwift#673]
<img width="1311" alt="Screen Shot 2022-02-13 at 1 46 49 PM" src="https://user-images.githubusercontent.com/14266357/153769920-686c2ce1-41d8-42e6-a752-db9712e35655.png">

Cannot scroll to further option

**Comment by cagnulein** [comment]
Hi @shuaiwang88 I don't have an M1, did you try to connect an external mouse 

@p3g4asus does yours already arrive?

**Comment by cagnulein** [comment]
@p3g4asus it seems a bug on the qt framework if it's so. Maybe with a mouse and the wheel is workaroundable

**Comment by shuaiwang88** [comment]
@cagnulein I just downloaded the app from apple store as M1 can run the universal app.

**Comment by cagnulein** [comment]
@shuaiwang88 Don't you have an external mouse to try? The scroll works on the iOS version, that's why I'm asking this

**Comment by shuaiwang88** [comment]
works now! Thanks! The watts does seem to work on the MacBook, and could you check that?
