### ISSUE TITLE
[REQ] Support for the Sole LCB Upright Bike

### ISSUE THREAD

**Issue by KurtRamsey** [cagnulein/qdomyos-zwift#675]
Requesting support for Sole LCB Upright Bike (https://www.soletreadmills.com/Bikes/LCB-SOLE-Upright-Bike).

I have attached the Bluetooth snoop log while the bike was connected to SOLE Fitness App (https://play.google.com/store/apps/details?id=com.soletreadmills.sole)

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8056545/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks!

**Comment by KurtRamsey** [comment]
Generated a new btsnoop_hci.log. Sole LCB was connected to Zwift for Power/Control, but since Zwift does not pick up its Cadence a Wahoo cadence sensor on the bike was providing that to Zwift via ant+. Attaching the btsnoop and fit file from Zwift.

[SoleLCB.zip](https://github.com/cagnulein/qdomyos-zwift/files/8064948/SoleLCB.zip)

**Comment by cagnulein** [comment]
Thanks @KurtRamsey the problem with this log is that with zwift, i see only FTMS packages. I'm trying to analyze the data of the first hci snoof and i will let you know. Don't you change the resistance automatically from the app, isn't it? I see a resistance change but only manually. is it correct?
Also how many resistance levels does it have?
I did the first wave of modification for this, send me an email to roberto.viola83 at gmail.com indicating this ticket and the fact that you're on android and i will add you to the private beta users group.
The version will be the 2.10.28
Let me know

**Comment by KurtRamsey** [comment]
All resistance changes are manual from the bike. As far as I know, even though Zwift recognizes it as having control, it does NOT support automatic resistance.

The Sole LCB has 40 levels of resistance

**Comment by cagnulein** [comment]
@KurtRamsey maybe it has automatic resistance but they don't expose it to zwift
let's do in this way: i will release a version that can show you the metrics on QZ. if it will work okay, we should investigate about automatic resistance
Is the resistance mechanic or magnetic? I mean do you change it by a knob connected to a screw or there is an engine to do so?

**Comment by cagnulein** [comment]
> The resistance is magnetic on the flywheel

Perfect! So it's highly possibile that it will have automatic resistance ;)

**Comment by KurtRamsey** [comment]
I'll do a bit more testing later this evening, but just got the update on Android. 
- Cadence and Watts are flipped (Cadence shows the correct Wattage value, and Wattage shows the correct Cadence value). 
- Resistance display on the app starts at 0, should that maybe start at 1 for the lowest?
- Ill check the other values, and test out bridging this to another device.

**Comment by KurtRamsey** [comment]
Log file from Raspberry Pi Zero 2 W. The bike beeps, when it has a another device connect via bluetooth. I hear that beep when the process starts running on the rpi, but it doesn't connect successfully like the Android app does. Using this to start on the pi: sudo ./qdomyos-zwift -no-gui -heart-service -name LCB

[debug-Tue_Feb_15_23_46_58_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8075507/debug-Tue_Feb_15_23_46_58_2022.log)

**Comment by cagnulein** [comment]
@KurtRamsey is the same raspberry that you use for #678 ? if so i guess you should fix this issue rebooting it. It seems an issue in the bluetooth stack.
Let me know
Also the same mod that i did for the #678 will be ok also for this

**Comment by KurtRamsey** [comment]
Yes, same raspberry pi.

**Comment by cagnulein** [comment]
@KurtRamsey ok give a try to the reboot, it should work as the #678

**Comment by KurtRamsey** [comment]
Same results for the LCB, it does not successfully pair with the qz app running on the raspberry pi

**Comment by cagnulein** [comment]
so strange. Anyway i will push the new android version tomorrow ;)

**Comment by KurtRamsey** [comment]
Android QZ Speed/Cadence/Power all pickup accurately
  Remaining 'issues':
  -When the bike is set to resistance 1 or 2, the qz app displays 1. After that it is n-1 (when resistance is 3 qz displays 2)

Is there anything that I can provide to better isolate the issue with the connection of the raspberry pi to the LCB bike?

**Comment by cagnulein** [comment]
hah sorry i forgot about this, i will fix the resistance today.
About the raspberry issue i really don't know what is it. You're still having this error

"   BTLE_DBUS::connect() failed "org.freedesktop.DBus.Error.NoReply" "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

?

**Comment by cagnulein** [comment]
@KurtRamsey the resistance issue is the same for the #678 ? or the r92 acts properly?
