### ISSUE TITLE
[REQ] Support for Bowflex BXT216 Treadmill

### ISSUE THREAD

**Issue by KurtRamsey** [cagnulein/qdomyos-zwift#677]
Requesting support for Bowflex BXT216 Treadmill (https://www.bowflex.com/treadmills/bxt216/100507.html).

I have attached the bluetooth snoop log while the bike was connected to JRNY (https://play.google.com/store/apps/details?id=com.nautilus.bowflex)

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8056635/btsnoop_hci.log)

**Comment by cagnulein** [comment]
Thanks @KurtRamsey I will check this tomorrow

**Comment by cagnulein** [comment]
@KurtRamsey do you have a fit file or a summary of what you did during this session? it could be useful to parsing correctly all the metrics. Thanks

**Comment by KurtRamsey** [comment]
Generated a new btsnoop_hci.log (Treadmill was again connected to JRNY app), along with a .fit file that I captured from an NPE Runn attached to the treadmill paired with GymTrakr.

The incline was increased from 1 to 15, then back down. Then the speed was increased from min to max.

[bowflex.bxt216.zip](https://github.com/cagnulein/qdomyos-zwift/files/8060733/bowflex.bxt216.zip)

**Comment by KurtRamsey** [comment]
The .fit file generated by GymTrakr was done on a separate mobile device from what was used to capture the btsnoop.

**Comment by cagnulein** [comment]
great @KurtRamsey this really makes my job easier. Do you have the fit file also for the other machineries?

**Comment by KurtRamsey** [comment]
@cagnulein 
Yes, I'll grab those later today.

**Comment by cagnulein** [comment]
@KurtRamsey does it have the inclination? i can't see here in the fit file and in the hci snoof

**Comment by cagnulein** [comment]
@KurtRamsey also did you already try this with QZ? I saw that already exist an implementation that i did some months ago but it seems different from yours #522

**Comment by KurtRamsey** [comment]
It does have incline, and while capturing the data I had raised and lowered the deck. 

While the treadmill does pair with Zwift for speed, at some point this last summer Zwift stopped picking up the incline data.

The Android app doesn't automatically attach, it will if I manually select. Once selected, it does not pickup any of the data.

**Comment by cagnulein** [comment]
> It does have incline, and while capturing the data I had raised and lowered the deck.
> 

ok so i will have to look at them deeply

> While the treadmill does pair with Zwift for speed, at some point this last summer Zwift stopped picking up the incline data.

hah ok

> 
> The Android app doesn't automatically attach, it will if I manually select. Once selected, it does not pickup any of the data.

you mean QZ android app? ok so probably i should use your hcisnoof about this

**Comment by cagnulein** [comment]
got the inclination byte now! :) @KurtRamsey

**Comment by KurtRamsey** [comment]
Correct, the qz app did not automatically attach like it does for the others.

Let me know if you need any other additional logs or fit files.

**Comment by cagnulein** [comment]
> Correct, the qz app did not automatically attach like it does for the others.

could you genearate a debug log without the manual device on?

**Comment by cagnulein** [comment]
in the meanwhile i did the modification if you want to try on android @KurtRamsey

**Comment by KurtRamsey** [comment]
See attached debug generated from Android QZ, manual disabled:
[debug-Sat_Feb_26_09_32_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8146804/debug-Sat_Feb_26_09_32_11_2022.log)

**Comment by cagnulein** [comment]
@KurtRamsey fixed! let me know if it works now

**Comment by KurtRamsey** [comment]
Incline is correct.

Speed is displayed, but it is not correct.

[debug-Mon_Feb_28_19_02_23_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8157779/debug-Mon_Feb_28_19_02_23_2022.log)

**Comment by cagnulein** [comment]
fixed @KurtRamsey ! Thanks

**Comment by KurtRamsey** [comment]
Can confirm, speed is now picked up correctly.

Bridging to Zwift is also successful, with both speed and incline (elevation gain).

**Comment by cagnulein** [comment]
Great! @KurtRamsey so can we close this or do you have other open points?

**Comment by KurtRamsey** [comment]
This can be closed, thanks again for the amazing work!
