### ISSUE TITLE
[REQ] Support for the Sole R92 Recumbent Bike

### ISSUE THREAD

**Issue by KurtRamsey** [cagnulein/qdomyos-zwift#678]
Requesting support for Sole R92 Recumbent Bike (https://www.soletreadmills.com/Bikes/R92-SOLE-Bike).

I have attached the Bluetooth snoop log while the bike was connected to SOLE Fitness App (https://play.google.com/store/apps/details?id=com.soletreadmills.sole)

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8056740/btsnoop_hci.log)

**Comment by cagnulein** [comment]
done this too @KurtRamsey 
i hope to be able to upload the new build today

**Comment by KurtRamsey** [comment]
Great. Updating my raspberry pi now with the latest changes....

**Comment by cagnulein** [comment]
hah ok! so you can try yourself! good! @KurtRamsey i did a new commit, please pull it too

**Comment by KurtRamsey** [comment]
Are the logs written to file, or do I need to redirect the output to file when I run ./qdomyos-zwift -no-gui -heart-service ?

`Tue Feb 15 11:39:58 2022 1644925198282 Debug:   BluetoothManagement: Ignored event: c
qt.bluetooth.bluez: BluetoothManagement: Ignored event: c
Tue Feb 15 11:39:58 2022 1644925198284 Debug:   ###### "org.bluez.Device1" QMap(("Connected", QVariant(bool, false)))
qt.bluetooth.bluez: ###### "org.bluez.Device1" QMap(("Connected", QVariant(bool, false)))
Tue Feb 15 11:39:58 2022 1644925198286 Debug: solebike.cpp void solebike::error(QLowEnergyController::Error) "solebike::errorConnectionErrorError occurred trying to connect to remote device."
"solebike::errorConnectionErrorError occurred trying to connect to remote device."
Tue Feb 15 11:39:58 2022 1644925198287 Debug: solebike.cpp solebike::deviceDiscovered(const QBluetoothDeviceInfo&)::<lambda(QLowEnergyController::Error)> "Cannot connect to remote device."
"Cannot connect to remote device."
Tue Feb 15 11:39:58 2022 1644925198288 Debug: solebike.cpp void solebike::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::UnconnectedState
"controllerStateChanged" QLowEnergyController::UnconnectedState
Tue Feb 15 11:39:58 2022 1644925198289 Debug: solebike.cpp void solebike::controllerStateChanged(QLowEnergyController::ControllerState) "trying to connect back again..."
"trying to connect back again..."
Tue Feb 15 11:39:58 2022 1644925198312 Debug:   QLowEnergyControllerPrivateBluezDBus::connectToDevice()
qt.bluetooth.bluez: QLowEnergyControllerPrivateBluezDBus::connectToDevice()
Tue Feb 15 11:39:58 2022 1644925198359 Debug: solebike.cpp void solebike::controllerStateChanged(QLowEnergyController::ControllerState) "controllerStateChanged" QLowEnergyController::ConnectingState
"controllerStateChanged" QLowEnergyController::ConnectingState`

**Comment by cagnulein** [comment]
@KurtRamsey you should see a debug log file in the same folder. anyway you can redirect it to a file. please send
me the full log
Anyway i will also push the version on android, it could be a bluetooth issue on the raspberry

**Comment by KurtRamsey** [comment]
-This device does pair with app running on the raspberry pi. I was then able to pair Zwift with the bridge!
-Cadence and Watts are flipped (Cadence shows the correct Wattage value, and Wattage shows the correct Cadence value).
-Resistance display on the app starts at 0, should that maybe start at 1 for the lowest?

[debug-Wed_Feb_16_00_18_56_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8075677/debug-Wed_Feb_16_00_18_56_2022.log)

**Comment by cagnulein** [comment]
Wow great! I will fix those today!
-- 
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud

**Comment by cagnulein** [comment]
done @KurtRamsey let me know if it will be better!

**Comment by KurtRamsey** [comment]
Using the raspberry pi with the R92:
-Cadence and Watts are accurate
-Successfully bridged to multiple applications including Zwift, TrainerDay and Kintetic
-Is resistance control still a possibility?

**Comment by cagnulein** [comment]
> -Is resistance control still a possibility?

@KurtRamsey yes i need to check it. I will let you know in the next days

**Comment by cagnulein** [comment]
@KurtRamsey ok let's try about the control resistance.
Pull and build the current release. Then, just with QZ, no zwift use the resistance tile with the plus button and let me know if something moves.
If it doesn't, search the line 

uint8_t up[] = {0x5b, 0x02, 0xf1, 0x02, 0x5d};

in the solebike.cpp

and change it to uint8_t up[] = {0x5b, 0x02, 0xf1, **0x04**, 0x5d};

and build it again and try

if it doesn't work put to uint8_t up[] = {0x5b, 0x02, 0xf1, **0x06**, 0x5d};

and build it again and try

if it doesn't work put to uint8_t up[] = {0x5b, 0x02, 0xf1, **0x08**, 0x5d};

and build it again and try and so on. We have to find the hidden function to change it. Once we have it, I can add auto resistance!

Let me know

**Comment by KurtRamsey** [comment]
It will be a day or two for me to test this out. My current pi setup does not have a gui. Will try to get that tonight or tomorrow.

**Comment by cagnulein** [comment]
@KurtRamsey i can release the android one, but the process will be much slower, that's why i asked you to make the modifications directly ;)

**Comment by KurtRamsey** [comment]
@cagnulein I understand that, and happy to test it out that way. I will let you know how it goes. Thank you for your work on this.

**Comment by KurtRamsey** [comment]
Got this built on raspberry pi with gui
-When the bike is set to resistance 1 or 2, the qz app displays 1. After that it is n-1 (when resistance is 3 qz displays 2)

See attached for the logs from the 4 attempts at changing resistance. None of the 4 variations resulted in change to resistance on the bike.

[logs.r92.zip](https://github.com/cagnulein/qdomyos-zwift/files/8103258/logs.r92.zip)
.

**Comment by cagnulein** [comment]
Hi @KurtRamsey could you try all the 0xFF values? It's the only way to be 100% sure that your machine doesn't have auto resistance

**Comment by KurtRamsey** [comment]
Should the resistance reading be corrected first? Would that impact the ability for the qa app to change the resistance?

**Comment by cagnulein** [comment]
@KurtRamsey No reading the resistance is easily fixable and it's not about this command ;)

**Comment by KurtRamsey** [comment]
Ok. I assume you were requesting that I change the values for the entire range as listed here https://www.hexadecimaldictionary.com/ranges/2?page=1?

If so I am up 0x0e

**Comment by cagnulein** [comment]
Yes exactly, I know that it's a tedious work but it's the only way to discover if your bike is capable of doing something about auto resistance.

**Comment by KurtRamsey** [comment]
Is there a way to have the app attempt each of the values, on its own in sequence?

**Comment by cagnulein** [comment]
Yes I can do a for-code, now I'm not in front of the pc. I will write it tomorrow

**Comment by KurtRamsey** [comment]
ok great. I'll look at it a bit myself to see if I can figure out a more efficient way of doing this. Thanks

**Comment by KurtRamsey** [comment]
Did not see the resistance change. I had tried the following:
void solebike::forceResistance(int8_t requestResistance) {
   qDebug() << QStringLiteral("writing resistance 0x01 ") + QString::number(requestResistance);
   uint8_t up1[] = {0x5b, 0x02, 0xf1, 0x01, 0x5d};
   writeCharacteristic(up1, sizeof(up1), QStringLiteral("up"), false, true);
   qDebug() << QStringLiteral("writing resistance 0x02 ") + QString::number(requestResistance);
   uint8_t up2[] = {0x5b, 0x02, 0xf1, 0x02, 0x5d};
   writeCharacteristic(up2, sizeof(up2), QStringLiteral("up"), false, true);
   qDebug() << QStringLiteral("writing resistance 0x03 ") + QString::number(requestResistance);
   uint8_t up3[] = {0x5b, 0x02, 0xf1, 0x03, 0x5d};
   writeCharacteristic(up3, sizeof(up3), QStringLiteral("up"), false, true);
   .....

**Comment by KurtRamsey** [comment]
I assume unrelated, but I did see in solebike.h, line 49 max resistance is set for 40.
- Resistance range for the Sole R92 is 1-20
- Resistance range for the Sole LCB is 1-40

**Comment by cagnulein** [comment]
@KurtRamsey that's a shame :( if it has a knob you can try also the SS2K

**Comment by KurtRamsey** [comment]
qdomyos-zwift (Android) does successfully READ: Speed/Cadence/Power
- BLE Bridge: Not currently able to get this to work on my Galaxy S7
- ant+ Bridge: Power and Cadence are accuratly picked up both by Zwift (Windows) and on Garmin Watch. However Speed is not. Zwift of course determines speed based on Power/Cadence. But in the case of Garmin Watch, it reads speed independently. That does not appear to be specific to the Sole R92 device. Is this something that could be fixed?

qdomyos-zwift (Raspberry Pi) does successfully READ: Speed/Cadence/Power
- BLE Bridge: Power and Cadence are accuratly picked up both by Zwift
- ant+ Bridge: Should this work, or is ant+ only possible on Android? Even if there is an ant+ usb dongle?

**Comment by cagnulein** [comment]
> qdomyos-zwift (Android) does successfully READ: Speed/Cadence/Power
> 
> * BLE Bridge: Not currently able to get this to work on my Galaxy S7

It could be that your S7 doesn't have the bluetooth capabilites to do the bridge

> * ant+ Bridge: Power and Cadence are accuratly picked up both by Zwift (Windows) and on Garmin Watch. However Speed is not. Zwift of course determines speed based on Power/Cadence. But in the case of Garmin Watch, it reads speed independently. That does not appear to be specific to the Sole R92 device. Is this something that could be fixed?

Yes it's a known issue #167 

> 
> qdomyos-zwift (Raspberry Pi) does successfully READ: Speed/Cadence/Power
> 
> * BLE Bridge: Power and Cadence are accuratly picked up both by Zwift
> * ant+ Bridge: Should this work, or is ant+ only possible on Android? Even if there is an ant+ usb dongle?

Currently ant is possible only on android but there is already a issue about this #305

**Comment by KurtRamsey** [comment]
Great. I will follow those other 2 issues. The ant+ support is of interest to me so that I can dual record. While I know Zwift can sync to Garmin, I would prefer the ability to record the activities independent of each other.

Unless you have anything, you want me to follow-up on or test, this request can be closed.

**Comment by cagnulein** [comment]
Ok! @KurtRamsey do you think you can get one of the 2 ANT+ tickets to manage it by yourself and do a PR?

**Comment by KurtRamsey** [comment]
I do have Android Studio setup, are there any specific steps that I need to do to setup the environment to build the android app locally?
