### ISSUE TITLE
[REQ] Kettler Alpha Run 800 Treadmill does not connect to QZ

### ISSUE THREAD

**Issue by meiermi** [cagnulein/qdomyos-zwift#681]
The Kettler Alpha Run 800 treadmill is fully Zwift compatible. I am using an old Iphone 6, iOS 12.55.
The treadmill will connect to the iphone via bluetooth, but does not show up in the QZ app.
attached are screenshots from the scanning app (forgot the name)
[gith.zip](https://github.com/cagnulein/qdomyos-zwift/files/8067009/gith.zip)

Thanks so much.

**Comment by cagnulein** [comment]
Hi @meiermi from the screenshot i see that this treadmill should be already compatible with Zwift, isn't it?
Anyway you should be able to get it running with QZ too adding your TM as a power sensor in the accessories section in the settings and enabling also the "power sensor as a treadmill". Let me know

**Comment by meiermi** [comment]
Yea, but the QZ app does not "find" the TM

**Comment by meiermi** [comment]
stop: What is the accessories section....:-)

**Comment by cagnulein** [comment]
@meiermi in the settings of QZ

**Comment by meiermi** [comment]
yea, found it, i have enabeld PS as a TM
two below Power Sensor is diabled, though.

**Comment by meiermi** [comment]
just tried again. perhaps I am super stupid...
I connect the TM with the iphone. Works fine. I open the QZ app. No connection

**Comment by cagnulein** [comment]
send here a screenshot of your actual setting of the power sensor section
What do you mean that the TM is connected with the iPhone? Where are you using QZ?

**Comment by meiermi** [comment]
what I do:
power up TM
go to APP (this is where TM connects with a device), enable (the the TM shows up as a BT device)
then i either connect via iphone BT (which works), but then QZ does not, OR

I open QZ app. The device (called S10) is found, but nothing happens.

FYI I need to punch in a 6 digit code for each BT connection (code shown on TM, inseting on phone)
Not sure what is wrong here....
![unnamed (1)](https://user-images.githubusercontent.com/99717746/154027187-6da4c466-daa4-4c84-80bd-469311c46651.jpg)
![unnamed (2)](https://user-images.githubusercontent.com/99717746/154027190-92005fd3-bde2-45ad-941e-dcfdbbb4af3e.jpg)

**Comment by cagnulein** [comment]
@meiermi you need to setup also the power sensor as S10 not disabled ;)

**Comment by meiermi** [comment]
so... stupid me. now it worked. sorry....
one last question: zwift asks for heartrate sensor, I guess I shall use my regular  (garmin) one right.

**Comment by meiermi** [comment]
Roberto,  all works and I will check how things work and let you know.
for my setup, the only two relevant topics are:
- use auto-incline (acc. to your video on YT)
- use peloton (but not sure whether I should go for another subsription in addition to zwift).
-

**Comment by cagnulein** [comment]
@meiermi For the auto incline feature you need to collect some data about your treadmill with the producer app. Does your treadmill have a standalone app?

**Comment by cagnulein** [comment]
@meiermi if the kettler app Doesn't allow you to change the incline or the speed it's possible that your treadmill doesn't have the capabilities on hardware to do so
Ask about this to kettler.
If you will find an app that allows you to change the speed or incline you have to follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by meiermi** [comment]
Well, since the Kettler TM is fully aligned with Zwift, we can steer speed. I have asked Kettler.

**Comment by meiermi** [comment]
If you will find an app that allows you to change the speed or incline you have to follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

---- this refers to android, i am iOs only... :-)

**Comment by cagnulein** [comment]
@meiermi in case you will find an app that allow you to do so, you need an android device to collect these data, only for the moments of the data collection. After then i will implement this on iOS too

**Comment by meiermi** [comment]
ok, i can do that.

**Comment by cagnulein** [comment]
@meiermi you have to wait the finish of the upload. But which app do you use at the end to collect it?

**Comment by meiermi** [comment]
I could download the app (its actually Kinomap), and link to the treadmill. I started a workout and played with incline and speed.
the app, I think only showed speed, but not sure.

**Comment by meiermi** [comment]
[Uploading bugreport-OnePlus3-PKQ1.181203.001-2022-02-15-14-02-01(1).zip…]()

**Comment by cagnulein** [comment]
@meiermi you have to wait the finish of the upload and then press comment, otherwise the file it will be corrupted. please re attach it. So in kinomap you will be able to change incline and speed? If so we should do the same on QZ! That's a great news!

**Comment by meiermi** [comment]
one more try. this is a 34mb file -

**Comment by cagnulein** [comment]
yes i confrm it :)

**Comment by cagnulein** [comment]
why it's a doc file? @meiermi don't the phone create a zip file on it's own? i need a file called "hci snoof" or something similar. it's a very small file

**Comment by meiermi** [comment]
oh dear. will see
yes, but i do not get the zip file from the phoone to his github

**Comment by meiermi** [comment]
[bugreport-OnePlus3-PKQ1.181203.001-2022-02-15-14-02-01(1).zip](https://github.com/cagnulein/qdomyos-zwift/files/8072072/bugreport-OnePlus3-PKQ1.181203.001-2022-02-15-14-02-01.1.zip)

**Comment by meiermi** [comment]
NOW the zip file

**Comment by cagnulein** [comment]
@meiermi there is the bluetooth file but it's empty. are you sure you did in the right way? do you have another android phone to use to collect it?

**Comment by meiermi** [comment]
![Capture](https://user-images.githubusercontent.com/99717746/154087210-0d730a7a-c372-43dd-8778-f5c0e48f9a92.JPG)


there was one zip file and that was in it
![Capture](https://user-images.githubusercontent.com/99717746/154087288-8d64f040-53b8-4630-b0b2-4f7d9dfd129c.JPG)

**Comment by cagnulein** [comment]
yes i see the files, but i guess that you did something wrong in the procedure (maybe you didn't enable the hci snoof options or you did in a wrong moment?) or your android phone is not capable to collect hci snoof log

**Comment by meiermi** [comment]
tried again. no incline on kinomap. I guess I call it a day. Thanks for all the efforts
:-)

**Comment by cagnulein** [comment]
ok let me know
