### ISSUE TITLE
iCloud support 

### ISSUE THREAD

**Issue by shuaiwang88** [cagnulein/qdomyos-zwift#682]
save the data on iCloud rather than local iPhone. Also to figure out where are the data saved on Mac.

**Comment by cagnulein** [comment]
@p3g4asus do you know where QZ saves the debug log on Mac M1? Sorry to bother you again on this

**Comment by shuaiwang88** [comment]
found it using find ~ -iname '*.fit' in terminal
/Users/xxxxx/Library/Containers/A4E3651B-9E79-44B7-A97A-ADB9B34335AA/Data/Documents/0QZ-backup-Sat Feb 12 23_45_12 2022.fit
