### ISSUE TITLE
[BUG] ERG mode on Zwift not functioning with QZ & EX3

### ISSUE THREAD

**Issue by matto89** [cagnulein/qdomyos-zwift#686]
ERG Mode on zwift not working. Enabled on zwift and in QZ. Screenshots & debug log attached. 

QZ 2.9.47 on iPhone 6S. Zwift on iPad 3. 
[debug-Wed_Feb_16_15_17_28_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8095894/debug-Wed_Feb_16_15_17_28_2022.log)
[Photos-001 (4).zip](https://github.com/cagnulein/qdomyos-zwift/files/8095905/Photos-001.4.zip)

**Comment by cagnulein** [comment]
@matto89 you have the "Zwift Force Resistance" setting disabled. It must be enabled for auto resistance

**Comment by matto89** [comment]
Brilliant, thank you!
