### ISSUE TITLE
Richiesta implementazione tapis roulant Fitfiu MC460

### ISSUE THREAD

**Issue by picchio9** [cagnulein/qdomyos-zwift#687]
![IMG_20220218_203009](https://user-images.githubusercontent.com/83451914/154752936-034f5368-6c99-4865-b290-681bf2eaac87.jpg)

**Comment by cagnulein** [comment]
Grazie! Ti faccio sapere domani

> Message ID: ***@***.***>
>
-- 
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud

**Comment by cagnulein** [comment]
@picchio9 buone notizie! in realtà non serve neanche la mia modifica, dovrebbe già andare. Hai provato? Fammi sapere

**Comment by picchio9** [comment]
Acquisto l'app e provo. Ti faccio sapere grazie

**Comment by picchio9** [comment]
L'app riconosce il tapis. Start e stop funzionano. Non aumenta/diminuisce la velocità.
Swift non trova il tapirulan.

**Comment by cagnulein** [comment]
@picchio9 le metriche di velocità e inclinazione le vedi su qz? su zwift stai usando un altro device? che devices stai usando?

**Comment by picchio9** [comment]
Inizialmente ho installato QZ su di un mi9t (Xiaomi) e zwift su un Poco F3. Metriche presenti (no inclinazione perché non la ho e tasti per aumentare velocità non funzionanti), zwift rimane in ricerca non trovando il Mi9t.
Ho provato ad invertire il tutto, ossia ho installato QZ sul Poco f3 e zwift sul Mi9t; QZ metriche funzionanti e tasti velocità no. Zwift però mi trova il poco f3 e si accoppia, quindi connesso, ma quando vado a correre l'avatar non si muove

**Comment by cagnulein** [comment]
hai provato a seguire questa https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift ?

**Comment by picchio9** [comment]
Provato, non cambia nulla. Ho provato anche ad installare zwift sul telefono di mio figlio un Mi9 e QZ sul Poco F3. Parametri presenti, tapis accoppiato e avatar che non si muove

**Comment by cagnulein** [comment]
Sicuro di aver rinominato il tuo cellulare e averlo riavviato? Vedi il nome nuovo su zwift? Ricorda che deve essere solo al massimo 4 lettere

**Comment by picchio9** [comment]
Si sono sicuro, vedo il nuovo nome di solo 4 lettere su zwift. Ho provato anche a cancellare tutte le associazioni BT, cancellare dati app. Mi ritrovo sempre con QZ che rileva tutti i parametri, zwift che associa il Cell (con nome di 4 lettere😉) e quindi mi fa andare avanti fino all'inizio della gara/allenamento e da quel momento in poi il mio avatar rimane fermo. Da notare che se aumento la velocità sul tapis, la visualizzo correttamente anche su QZ.

**Comment by cagnulein** [comment]
Fai così: fai il paring da zwift ma rimani nella visualizzazione dove fai il pairing. In alto a destra della icona della velocità in zwift deve apparire la tua velocità corrente. Prima di dare go, prova a cambiare La velocità del tapis, si deve riflettere su zwift.

**Comment by picchio9** [comment]
![IMG_20220219_164503](https://user-images.githubusercontent.com/83451914/154808238-a527408a-c3ae-4d4f-81b2-d96aaa635954.jpg)

**Comment by picchio9** [comment]
Questa è la situazione

**Comment by cagnulein** [comment]
E la velocità su qz quanto era? Genera un debug log perché sinceramente non riesco a capire che problema ci sia https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by picchio9** [comment]
La velocità su QZ era di 3km/h.
Su zwift non ho mai visualizzato la velocità. Sempre zero.

**Comment by cagnulein** [comment]
@picchio9 Genera un debug log come richiesto,grazie

**Comment by picchio9** [comment]
[debug-Sat_Feb_19_17_09_00_2022.2.log](https://github.com/cagnulein/qdomyos-zwift/files/8102607/debug-Sat_Feb_19_17_09_00_2022.2.log)

**Comment by cagnulein** [comment]
@picchio9 Dal log tutto funziona perfettamente quindi significa che il device che stai utilizzando non ha la possibilità di fare da bridge (qz è l'unica applicazione sullo store che usa il Bluetooth sia peripheral che central allo stesso tempo).
Hai altri device android da provare? Anche vecchi, considera che il mio Xiaomi mi3 di 10 anni fa va da dio.
Oppure se hai un device iOS qualsiasi ti mando la versione. Tutti i device iOS funzionano perfettamente 
Fammi sapere

**Comment by picchio9** [comment]
Più tardi provo con il Cell di mia moglie (Huawei Mate 9) dopo di ché ho finito le cartucce 🤤

**Comment by picchio9** [comment]
In attesa che torni mia moglie per sequestrargli il telefono ho fatto un'altra prova: precedentemente avevo provato con QZ sul mi9t e zwift su poco F3, ma zwift non trovava il mi9t. Ora ho provato sempre QZ su mi9t e zwift sul mio di mio figlio. Swift riconosce mi9t, avviene l'accoppiamento, ma il risultato sempre uguale, avatar che non si muove e velocità non rilevata

**Comment by picchio9** [comment]
E niente anche il Huawei Mate 9 stessa situazione.
Possibile 5 telefoni non compatibili?
Dovrò necessariamente ripiegare su di un foot pod per fare funzionare zwift

**Comment by cagnulein** [comment]
huawei e poco sono noti per aver bluetooth customizzato nella rom purtroppo. sicuro che non hai vecchi android nel cassetto?

**Comment by picchio9** [comment]
Purtroppo no, al momento ho finito tutte le risorse. Avevo scovato un s3mini (Samsung) l'ho rianimato ma nel PlayStore non mi compare l'app Qz

**Comment by cagnulein** [comment]
cerca qdomyos-zwift
ci deve essere

**Comment by picchio9** [comment]
Non c'è

**Comment by cagnulein** [comment]
ma scusa dal samsung clicca qui https://play.google.com/store/apps/details?id=org.cagnulen.qdomyoszwift&fbclid=IwAR3CVoYb0scvGf7gb0Y20VFh5Na5fDWwe7VACk-2c45Tm0x5s8sXpIGhGyw

**Comment by cagnulein** [comment]
@picchio9 Qualche novità? Considera che se pensi di prendere un foot pod Sara super Impreciso è come tutti te ne pentirai. È il motivo per cui ho sviluppato questa app. Investi 40€ in un iPhone 6s su eBay da usare con la mia app e vedrai che ne sarai contento ;)

**Comment by picchio9** [comment]
![IMG_20220220_203525](https://user-images.githubusercontent.com/83451914/154860914-c151ae98-7975-4b69-8c24-a9f1914c34b1.jpg)
Ecco perché non è presente sul PlayStore

**Comment by cagnulein** [comment]
Azz deve essere proprio vecchio. Che Android c'è sopra?

**Comment by picchio9** [comment]
Ho appena provato ad installare l'app Qz su uno Xiaomi redmi note 9 di un mio amico. Stesso problema di sempre. Inizio a pensare che il mio tapirulan non sia compatibile o ti sfugge qualcosa dal log.

**Comment by cagnulein** [comment]
@picchio9 Se l'app non fosse compatibile con la app non leggeresti le metriche su Qz. Quindi sicuramente la compatibilità da quello che mi hai scritto è corretta.
Fai una cosa: dal tuo telefono apri qz e connettiti al tuo tapis.
Da un altro, apri nrfconnect e guarda cosa vedi in merito al tuo telefono: devi vederlo come ftms e se guardi i treadmill data devi vedere anche la velocità 
Fammi sapere

**Comment by picchio9** [comment]
Ok, stasera provo e ti faccio sapere

**Comment by picchio9** [comment]
Allora, sinceramente mi sono un po' perso con l'app nrf.
Il poco f3 l'ho trovato (vedi screenshot). Il tapirulan non lo trovo. Domani con più calma riprovo. Nel frattempo ti posto qualche screenshot che ho fatto
![1645477308870_100211](https://user-images.githubusercontent.com/83451914/155026434-877a9892-867e-475c-ae83-908fad63515f.jpg)
![1645477308865_100206](https://user-images.githubusercontent.com/83451914/155026437-a1fba08e-faab-4ef5-bfbb-6186adf1bfad.jpg)
![1645477308861_100204](https://user-images.githubusercontent.com/83451914/155026440-dd359b12-958f-46d2-a809-9de6a241205e.jpg)
![1645477308854_100155](https://user-images.githubusercontent.com/83451914/155026442-df554725-1f8d-477a-b387-551461282483.jpg)
![1645477308857_100159](https://user-images.githubusercontent.com/83451914/155026446-420b225d-6720-46a1-8bc9-f290a916ab2b.jpg)

**Comment by cagnulein** [comment]
> ![1645477308861_100204](https://user-images.githubusercontent.com/83451914/155026440-dd359b12-958f-46d2-a809-9de6a241205e.jpg)

Da questa schermata devi vedere i treadmill data. Prova sia client che server. Se non li vedi è proprio il tuo device che non riesce a generarli (vedo che correttamente viene visualizzato il cuore per il tuo device su nrfconnect, quello è QZ che lo fa nel pacchetto di advertising in bluetooth)

**Comment by picchio9** [comment]
![1645520563629](https://user-images.githubusercontent.com/83451914/155098826-c21bdd87-10e3-4eba-b906-7fbb3189282e.png)
![1645520563620](https://user-images.githubusercontent.com/83451914/155098832-111cca4e-d109-41be-afb1-7fb98a4f4097.png)

**Comment by cagnulein** [comment]
@picchio9 perfetto! ora se clicchi sulle tre freccette corrispondendti a treadmill data doversti vedere i dati in tempo reale del tuo tapis! Se funziona allora il problema è su zwift
Fammi sapere

**Comment by picchio9** [comment]
Se clicco le 3 freccette compare il cerchietto del caricamento vicino a client e dopo un po' di tempo compare quello che vedi sullo screenshot (il primo dei due)

**Comment by cagnulein** [comment]
@picchio9 ok quindi si disconnette, l'unica cosa che puoi provare ed ad abiltiare il "bluetooth relaxed for madness devices" negli experimental settings e riavviare QZ. Prova a vedere se fa qualche differenza

**Comment by picchio9** [comment]
Nessuna differenza

**Comment by cagnulein** [comment]
devi guardare se tutti i device android ti fanno sto effetto. non hai nessuno intorno a te con un iphone da verificare? Io sono abbastanza sicuro che sia solo un problema di incompatibilità degli android che hai provato. Purtroppo android è un disastro per il bluetooth, è il motivo per cui io personalmente mi sono spostato completamente su iOS dopo 10 anni di android.

**Comment by picchio9** [comment]
Mi vieni l'orticaria solo a leggere iOS. Detesto tutto il mondo Apple. Ma questo è un mio problema 😆
No, non ho nessuno nelle vicinanze a cui sequestrare un merd@phone ☺️

**Comment by cagnulein** [comment]
guarda avevo il tuo stesso preconcetto fino ad 1 anno fa. però appena lo inizi ad usare capisci che i produttori di android sono solo dei cinesari maledetti. L'HW è proprio gestito da cani su android. Te lo dico da firmwarista. Comunque continua a provare con altri vecchi android da amici, vedrai che ce ne sarà uno che funzionerà! Se fossimo vicino ti farei provare i miei. BTW di dove sei? Io sono di Maranello

**Comment by picchio9** [comment]
Piena consapevolezza della superiorità nella gestione dell' hardware, ma non cambierò mai idea, è un odio profondo!😆
Getto la spugna! Ho finito gli Android accessibili!
Sono di Roma, grazie lo stesso

**Comment by cagnulein** [comment]
ok comunque ricordati, invece di spendere soldi per un RUNN o un qualsiasi altro pod, compra un iphone usato, fidati di me. dopo 2 anni in questo mondo, (come puoi vedere dai ticket qui), so di quello che sto parlando :) in italia, dal punto di vista degli attrezzi ginnici connessi, credo di essere quello che ne ha + esperienza :)

**Comment by picchio9** [comment]
Piuttosto stavo pensando: visto che ho acquistato il tapirulan da circa 1 settimana su Amazon, potrei fare il reso e optare per un altro. Anche se devo essere sincero per il momento mi soddisfa a livello hardware. 
Tu che dici? Eventualmente avresti qualche modello da suggerirmi su Amazon? Sempre su di un budget di 400/500€

**Comment by cagnulein** [comment]
su quel budget no sinceramente, al massimo andrei sull'usato. Se l'hw ti soddisfa io starei su quello sinceramente. Io comunque considera che zwift per la corsa praticamente non lo uso più (anche se questa app è nata per quello XD)
Io uso i training program che ho embeddato nella mia app (quello su base cardio è una figata sinceramente!)

**Comment by picchio9** [comment]
È più il pensiero di non avere un tapis roulant connesso, che l'uso che poi effettivamente ne farei. 
Lo "smart" ha invaso la mia vita.

**Comment by cagnulein** [comment]
si ti capisco benissimo! Scolta ho un'idea: ma un bel raspberry pi 0? funzionerebbe alla grande!

**Comment by picchio9** [comment]
Non ho conoscenze in merito anche se so bene cosa sia. Apprendo facilmente. Se a basso costo si potrebbe fare.
Mi sono scordato di dirti che il tapis ha una porta USB potrebbe servire a qualcosa?

**Comment by cagnulein** [comment]
@picchio9 super basso costo, con 10€ e una card microsd da 16 gb fai tutto! Le istruzioni per fare andare la app le trovi qui https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md

**Comment by picchio9** [comment]
Gentilmente puoi mandarmi un link per acquisto Amazon? Così sono certo che non sbaglio, eventualmente anche con una custodia.
Può essere utile l' USB sul tapis?

**Comment by cagnulein** [comment]
@picchio9 su amazon costano una fucilata, non ti consiglio dì prenderlo li. https://www.amazon.it/dp/B07C7FHJDX/?tag=forzacarpi-21 comunque questo è il prodotto.
prova su qualche altro sito. o anche su ebay o subito
fammi sapere

**Comment by cagnulein** [comment]
@picchio9 no perchè ti dicevo che QZ usa bluetooth peripheral and central allo stesso tempo. Questo tira il chip bluetooth a livelli di cui nessuna app sullo store fa. Ecco il motivo del problema dei tuoi telefoni ;) Infatti QZ standalone ti va su tutti i telefoni ;)

**Comment by picchio9** [comment]
Alla fine ho risolto in modo diverso. Dovevo cambiare sportwatch e ho acquistato un garmin Forerunner 245, che tramite "virtual run" si collega a zwift. Vedo tutti i parametri e finalmente ho il mio avatar animato

**Comment by cagnulein** [comment]
Hah ok @picchio9 ma sappi che la velocità sarà sballata e non ti prende comunque l'inclinazione
