### ISSUE TITLE
[BUG] Echelon App not displaying data from virtual echelon

### ISSUE THREAD

**Issue by ptgraham** [cagnulein/qdomyos-zwift#695]
**Describe the bug**
Echelon app no longer displays data (cadence, power, HR) from QZ virtual echelon

Was working Tuesday, stopped Wednesday.  Might have been due to Echelon app update from 2.5.4. to 2.5.5

**To Reproduce**
1. Open QZ on phone
2. Pedal Echelon bike to wake (QZ app connects)
3. Open Echelon app on ipad
4. Start workout
5. Connect to bike (select virtual bike being broadcasted by QZ)
6. Data not displayed (No cadence, Resistance or HR)

**Expected behavior**
Step 6 should display data from QZ
Echelon app (on ipad) should connect to virtual bike receive data from iphone running QZ

**Smartphone (please complete the following information):**
 - Device: iphone 8
 - OS:  iOS
 - Version 15.3.1

**Append a debug log**

 debug log available...

**Comment by ptgraham** [comment]
Debug log:

[debug-Wed-Feb-23-11-07-20-2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8125943/debug-Wed-Feb-23-11-07-20-2022.log)

**Comment by cagnulein** [comment]
got the issue @ptgraham 
echelon app is sending a new frame 
"f0 a4 00 94"
i have to manage this. I will let you know if i need other informations
Thanks

**Comment by cagnulein** [comment]
#275

**Comment by cagnulein** [comment]
@ptgraham as I wrote on the facebook group i need an hci snoof from an android device in order to fix this. Do you have one?

**Comment by ptgraham** [comment]
I tried following the instructions for hci snoop from my android tablet running the Echelon app connected to the echelon bike.  Let me know if I got the right file, or if I need to do something differently.  Thanks
[bugreport-2022-02-24-06-55-11.zip](https://github.com/cagnulein/qdomyos-zwift/files/8132327/bugreport-2022-02-24-06-55-11.zip)
.

**Comment by cagnulein** [comment]
@ptgraham do you have this android only? because i don't see the hci snoof here. Did you enable the hci snoof setting in the developer settings?

**Comment by ptgraham** [comment]
The hci snoop setting is on, but I'm not getting anything in FS/Data/Log/bt directory of the zipfile.

This tablet is pretty old

Trying again with my echelon 5s display... will post the file if I get that to work

**Comment by cagnulein** [comment]
ok thanks @ptgraham

**Comment by ptgraham** [comment]
@cagnulein Here's the full bug report from the Echelon 5s android display.  I'm still not seeing the FS/Data/Log/bt directory in the zip file.  
[bugreport-rk3288-PI-2022-02-24-09-00-21.zip](https://github.com/cagnulein/qdomyos-zwift/files/8133035/bugreport-rk3288-PI-2022-02-24-09-00-21.zip)

**Comment by ptgraham** [comment]
@cagnulein added .log at the end
[btsnoop_hci.cfa.log](https://github.com/cagnulein/qdomyos-zwift/files/8133117/btsnoop_hci.cfa.log)

**Comment by cagnulein** [comment]
wow so it was there? @ptgraham i'm checking it! thanks

**Comment by cagnulein** [comment]
@ptgraham arg there is no trace of communication of the echelon app there. are you sure you opened it and did a quick ride?

**Comment by ptgraham** [comment]
@cagnulein I did.  am I doing the steps correctly? Is Step 8 correct?

4. Go into developer options
5. Enable the option Enable Bluetooth HCI snoop log
6. restart your phone
7. open your machine app and play with it collecting inclination and speed
**8. Disable the option Enable Bluetooth HCI snoop log**
9. in Developer Options: Bug report->Full report
10. wait a random amount of time (10-20 seconds)
11. A notification will appear at the top of the device. Click on it, share, email it to yourself

**Comment by cagnulein** [comment]
@ptgraham yes is right but since the echelon tablet is a flavoured rom it could be different. You can try without that one. Also the restart phase could be a difference on this tablet. You can check the hci snoof with wireshark if you want before sending me it
Let me know

**Comment by ptgraham** [comment]
@cagnulein here's a log from the echelon tablet (RK3288) to QZ virtual echelon (ECHEX-5S-113399) 

[btsnoop_hci (QZ to Echelon).cfa.log](https://github.com/cagnulein/qdomyos-zwift/files/8136651/btsnoop_hci.QZ.to.Echelon.cfa.log)

The echelon app seems to drop the connection every few seconds and never displays correct data.  This is not new behavior but since I was recording log files I thought I may as well record this too.

**Comment by cagnulein** [comment]
@ptgraham i didn't check yet the log but i created a fake answer to the new frame of echelon. send me an email to roberto.viola83 at gmail.com indicating this ticket and i will send you the version

**Comment by cagnulein** [comment]
> @cagnulein This one seems to have data but I'm not sure what I'm looking for with wireshark [btsnoop_hci (1).cfa.log](https://github.com/cagnulein/qdomyos-zwift/files/8134082/btsnoop_hci.1.cfa.log)

this one is perfect! got it and implemented! it will be in the 2.10.34

**Comment by ptgraham** [comment]
@cagnulein Thanks, the update worked. 
iphone with QZ sends to iPad running echelon app and displays all the stats

**Comment by cagnulein** [comment]
great! could we close this so?

**Comment by ptgraham** [comment]
@cagnulein yes, bug fixed

**Comment by cagnulein** [comment]
@ptgraham is this still work? @nskinner07 reported me here #762 that the new version broke it again. Could you please confirm me this?
