### ISSUE TITLE
[REQ] - Add TRX 4500 Treadmill

### ISSUE THREAD

**Issue by JFont86** [cagnulein/qdomyos-zwift#696]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This is the NRF connect screenshot from my Treadmill that you requested. My name is Jeff Fontenot. 

![D5EA29B0-2D4E-4756-867C-92D20C339914](https://user-images.githubusercontent.com/99910816/155461208-9c7e8bab-444e-4f5c-8179-0d42a23adda8.png)
![9B3D51CA-F1F2-4FE1-A7B0-4724A9F8B6DF](https://user-images.githubusercontent.com/99910816/155461210-a2d0bb54-3a6c-4696-a22b-d755003b790a.png)
![776DD1EA-9A93-4F3B-86EC-12E6244E82F9](https://user-images.githubusercontent.com/99910816/155461215-53f8ef6d-43b6-4581-81f6-8dcfbf706b28.png)
![42A3CCD7-6258-4235-8479-D0F48637EA9F](https://user-images.githubusercontent.com/99910816/155461217-df8b3e34-4f3d-49c1-a14d-f4bc674f2dd8.png)
![0BF2DB67-63C4-4DD1-9906-B35B9395EA5A](https://user-images.githubusercontent.com/99910816/155461218-3435d7b4-a4ba-4e8e-bd26-20e412050226.png)
![2511221D-84AC-434B-BF21-092D62977B27](https://user-images.githubusercontent.com/99910816/155461219-b0558733-721d-46cc-8957-2a522eaa0cef.png)
![6754A4B0-2CDC-4A3F-9187-1144CE5B2F67](https://user-images.githubusercontent.com/99910816/155461220-e402be3b-e22b-4c4f-86a8-e1137b19bda4.png)

**Comment by cagnulein** [comment]
hi thanks @JFont86 i will to today

**Comment by JFont86** [comment]
Let me know if you can get it to work and I’ll go purchase your app. 

Jeffery Fontenot, PE
337-230-6131

**Comment by JFont86** [comment]
You are the man for doing this, by the way. Let me know if I can do anything to contribute!

Jeffery Fontenot, PE
337-230-6131

**Comment by cagnulein** [comment]
Done @JFont86 ! Send me an email to roberto.viola83 at gmail.com indicating this ticket and if you're on iOS or android. It will be in the version 2.10.32

**Comment by cagnulein** [comment]
@JFont86 did you try this?

**Comment by cagnulein** [comment]
No problem at all! Family comes always first!


Il giorno mer 2 mar 2022 alle ore 16:35 JFont86 ***@***.***>
ha scritto:

> I haven’t had a chance yet due to what’s going on at home but I will
> hopefully have time today. Sorry for the delay!
>
> Jeffery Fontenot, PE
> 337-230-6131
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
any update on this @JFont86 ?

**Comment by JFont86** [comment]
I tried getting the app to connect to my treadmill but it didn’t seem to give me the options to do anything.  No tiles popped up. I will try to see if I can go through some youtube videos to figure out how to get it started. 

Jeffery Fontenot, PE
337-230-6131

**Comment by cagnulein** [comment]
@JFont86 did you use the version that I sent you? Check the version in left side bar

**Comment by JFont86** [comment]
I thought that I did. 



Jeffery Fontenot, PE
337-230-6131

**Comment by cagnulein** [comment]
@JFont86 follow this so https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
@JFont86 i'm here if you need help

**Comment by cagnulein** [comment]
@JFont86 any news?

**Comment by cagnulein** [comment]
i'm closing this @JFont86 feel free to reopen when you're ready
