### ISSUE TITLE
[REQ] Schwinn 510U

### ISSUE THREAD

**Issue by Tuomaspi** [cagnulein/qdomyos-zwift#697]
**Is your feature request related to a problem? Please describe.**
Controlling the resistance through the zwift app does not work. Otherwise the bike is supported with power and cadence.

**Describe the solution you'd like**
Controlling the resistance through the zwift app

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20220224-155230](https://user-images.githubusercontent.com/100361453/155538337-e29d4d8c-5829-43d7-99c8-ddeff57562ec.jpg)
![Screenshot_20220224-155347](https://user-images.githubusercontent.com/100361453/155538346-d0b67924-7995-4712-b88b-d23fc4073ee1.jpg)
![Screenshot_20220224-155406](https://user-images.githubusercontent.com/100361453/155538349-e84714e1-e2e9-4b55-898b-4965f3a53ca2.jpg)

**Comment by cagnulein** [comment]
done @Tuomaspi send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
[debug-Thu_Feb_24_22_15_21_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8139341/debug-Thu_Feb_24_22_15_21_2022.log)

**Comment by cagnulein** [comment]
@Tuomaspi fixed! it will be in the 2.10.34
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Tuomaspi** [comment]
Hi, tested the fix. Now the app does not crash and also shows speed, watts etc. which is great! But controlling the resistance from the app is not working unfortunately.

**Comment by cagnulein** [comment]
@Tuomaspi could you please share a fresh log with the current version? i would like to check if it expose some bluetooth characteristics to manage it

**Comment by Tuomaspi** [comment]
@cagnulein Hi sure, here it is!
[debug-Fri_Feb_25_13_06_56_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8140662/debug-Fri_Feb_25_13_06_56_2022.log)

**Comment by cagnulein** [comment]
@Tuomaspi i checked the log and unfortunately the bike doesn't provide any characteristics to force the resistance over blueooth :( that's such a shame! maybe you can try with the ss2k #299  ?

**Comment by Tuomaspi** [comment]
@cagnulein Ok, that's a shame. But thank you so much for your help anyway! I will have to take a look at the ss2k project :)
