### ISSUE TITLE
Fitex F1 Treadmill

### ISSUE THREAD

**Issue by Rerkdee** [cagnulein/qdomyos-zwift#698]
[debug-พฤ__ก_พ__24_22_07_01_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8133555/debug-.__._.__24_22_07_01_2022.log) or https://drive.google.com/file/d/1oGgPCXAqb5OPH033H-nqQ6V7S6_Kkj9q/view?usp=drivesdk

**Comment by Rerkdee** [comment]
[Uploading debug-ศ__ก_พ__25_21_16_50_2022.log…]()

**Comment by cagnulein** [comment]
ok i'm checking it @Rerkdee

**Comment by cagnulein** [comment]
@Rerkdee it's very strange. Try this:
1) go into the experimental settings and disable the "ios peloton workaround"
2) restart qz
3) if it doesn't work send me again the debug log

Thanks

**Comment by Rerkdee** [comment]
[debug-ศ__ก_พ__25_21_44_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8141991/debug-.__._.__25_21_44_15_2022.log)

**Comment by Rerkdee** [comment]
The setup you suggested doesn't work, I've sent you a debug.

เมื่อ ศ. 25 ก.พ. 2565 เวลา 21:36 Roberto Viola ***@***.***>
เขียนว่า:

**Comment by cagnulein** [comment]
thanks, i have a new idea @Rerkdee i'm building another one. I will notify you when i'm ready to test again

**Comment by cagnulein** [comment]
@Rerkdee in the meanwhile, could you please try another thing?
1) disable the virtual device setting in the experimental settings
2) restart QZ
3) if it doesn't work send me again the debug log

**Comment by cagnulein** [comment]
also could you send me a full screenshot of the nrfconnect app (nrfconnect is a free app on the store) about your treadmill. thanks @Rerkdee Don't worry, we will manage it together!

**Comment by Rerkdee** [comment]
[debug-ศ__ก_พ__25_21_59_05_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8142087/debug-.__._.__25_21_59_05_2022.log)

**Comment by cagnulein** [comment]
ok thanks @Rerkdee send me a full screenshot of the nrfconnect app (nrfconnect is a free app on the store) about your treadmill. thanks @Rerkdee Don't worry, we will manage it together!

**Comment by Rerkdee** [comment]
เมื่อ ศ. 25 ก.พ. 2565 เวลา 22:02 Roberto Viola ***@***.***>
เขียนว่า:

**Comment by pichitru** [comment]
How do I view debug files from QZ?

**Comment by cagnulein** [comment]
@Rerkdee sorry i can't see nothing. you have to attach them from the Github website
@pichitru nevermind, now i need a nrconnect screenshot from an iOS device. Thanks

**Comment by Rerkdee** [comment]
![FA1B182B-CAEE-430F-9149-75D22FA10D9D](https://user-images.githubusercontent.com/100364785/155738671-5e6b9578-bd4d-4ceb-94e9-611968d06e0c.png)

**Comment by cagnulein** [comment]
@Rerkdee send me also screenshots of the full page of the client and server tabs, thanks

**Comment by Rerkdee** [comment]
![9351B530-4675-4120-9EA4-E1349E9083E1](https://user-images.githubusercontent.com/100364785/155739740-3af60ffb-d923-41aa-805d-65791f9758f9.jpeg)

**Comment by cagnulein** [comment]
Got it @Rerkdee ! I'm building it now! Thanks for the collaboration!

**Comment by Rerkdee** [comment]
เมื่อ ศ. 25 ก.พ. 2565 เวลา 22:10 Roberto Viola ***@***.***>
เขียนว่า:

**Comment by cagnulein** [comment]
@pichitru thanks, i got the issue. I'm building a new one. It should be online in an hour or so

**Comment by pichitru** [comment]
Thank you

**Comment by pichitru** [comment]
Tomorrow morning I will test

**Comment by cagnulein** [comment]
have a good night guys and thanks for your help!

**Comment by cagnulein** [comment]
@Rerkdee @pichitru version sent! i hope it will work!

**Comment by pichitru** [comment]
Hi Roberto 
QZ iOS Version 2.10.35 it succeeds. thanks for the help. will inform everyone.
Thanks

**Comment by cagnulein** [comment]
Great @pichitru thanks for the help!

**Comment by Rerkdee** [comment]
The app can now control the treadmill.  But the next problem I encountered
is that zwift can't see the bluetooth of qz both Ride and run.

เมื่อ ส. 26 ก.พ. 2565 เวลา 00:49 Roberto Viola ***@***.***>
เขียนว่า:

**Comment by Rerkdee** [comment]
I was able to connect qz to zwift by going enable virtual device settings
and connected as you suggested video clip put in ride mode first it works
fine it has auto incline but when i switch to run mode  The auto incline
function cannot work.

เมื่อ ส. 26 ก.พ. 2565 เวลา 06:16 ฤกษ์ดี ทองเล็ก ***@***.***>
เขียนว่า:

**Comment by Rerkdee** [comment]
[debug-ส__ก_พ__26_06_17_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8145442/debug-.__._.__26_06_17_30_2022.log)

**Comment by pichitru** [comment]
[debug-ส__ก_พ__26_00_25_55_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8146243/debug-.__._.__26_00_25_55_2022.log)

treadmill will start too. But when I press stop or pause on the qz app, the treadmill won't stop.

**Comment by Rerkdee** [comment]
@cagnulein incline in zwift app when it goes above 4%, but in Qz app it will only adjust half, it is 2% in zwift app 6%, in Qz app it is only 3%.
[debug-ส__ก_พ__26_18_58_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8146589/debug-.__._.__26_18_58_03_2022.log)

**Comment by pichitru** [comment]
Gain Zwift and QZ do not match, 50% difference.

**Comment by cagnulein** [comment]
> Gain Zwift and QZ do not match, 50% difference.

You have to use the inclination gain setting. Put it to 2

**Comment by pichitru** [comment]
> > Gain Zwift and QZ do not match, 50% difference.
> 
> You have to use the inclination gain setting. Put it to 2

setting of the QZ menu?

**Comment by cagnulein** [comment]
> > > Gain Zwift and QZ do not match, 50% difference.
> 
> > 
> 
> > You have to use the inclination gain setting. Put it to 2
> 
> 
> 
> setting of the QZ menu?

yes :) inclination gain setting is the name of that one

**Comment by pichitru** [comment]
> yes :) inclination gain setting is the name of that one

![30209](https://user-images.githubusercontent.com/100275779/155846193-33dbfdb1-bff7-4616-bbff-1242bfca409b.jpg)
right here

**Comment by cagnulein** [comment]
@pichitru yes, did it work?

**Comment by pichitru** [comment]
![274009667_622058068866371_2908128614345789672_n](https://user-images.githubusercontent.com/100275779/155850521-e57d431d-ac30-4269-8510-ee52a7ad1be7.jpg)
https://drive.google.com/file/d/1uTDHAOR-n4pTSwkoqPvnwytXzrD5Mo1g/view?usp=sharing
Thank you.
