### ISSUE TITLE
[BUG] 2.10.33 crashing

### ISSUE THREAD

**Issue by Tuomaspi** [cagnulein/qdomyos-zwift#699]
**Describe the bug**
Installed the new version and it seems to recognize my bike but the app chrashes instantly after it connects the bluetooth. I tried re-installing and also booted my phone but still the same problem.

**To Reproduce**
1. Go to 'app'
2. App recognizes bike
3. app closes

**Smartphone (please complete the following information):**
 - Device: [One plus 9 pro]
 - OS: [Oxygen OS]
 - Version [ 11.2.10.10.LE15BA]

**Append a debug log**
  
[debug-Thu_Feb_24_22_15_21_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8135633/debug-Thu_Feb_24_22_15_21_2022.log)

**Comment by cagnulein** [comment]
thanks @Tuomaspi i will check today

**Comment by cagnulein** [comment]
@Tuomaspi don't open a ticket every time, just update the #697
thanks
i will write you there
