### ISSUE TITLE
Add Total Output Metric

### ISSUE THREAD

**Issue by marklogan17** [cagnulein/qdomyos-zwift#70]
The Echelon app and I believe the Peleton app have measures of Total Output measured in KiloJoules.  Its essentially the sum of your output over time.  I found this definition on an Echelon/Peleton Facebook page:

A joule is 1 watt in 1 second. So if you pedal consistently and have an average output of 100, then that's 100 joules per second (on average). 100 watts x 1 second = 100 joules. If you pedal consistently for 10 seconds, you'll have 1 kilojoule (kj) in 10 seconds. 100 watts x 10 seconds = 1000 joules = 1 kilojoule. If you pedal consistently for 5 seconds at 200 watts, you'll generate the same energy. 200 watts x 5 seconds = 1000 watts, or 1 kj.  So you see, the energy or power (kj) you generate is directly related to both how hard you're working and how long you're working. Your total output number is a measurement of how much energy you've generated over the entire ride.

**Comment by cagnulein** [comment]
Yeah sure no problem. I could add it to UI in the app, do you need over bluetooth also? I think that peloton doesn't read, isn't it?

**Comment by marklogan17** [comment]
> Yeah sure no problem. I could add it to UI in the app, do you need over bluetooth also? I think that peloton doesn't read, isn't it?

Yes this would just be for the UI.

**Comment by cagnulein** [comment]
[android-1.4.0.zip](https://github.com/cagnulein/qdomyos-zwift/files/5648950/android-1.4.0.zip)
you asked for it you got it :)

**Comment by marklogan17** [comment]
Nice!  I'm out for a couple of hours but I'll test as soon as I'm home!!

**Comment by marklogan17** [comment]
I gave it a try. Looks like it's working!  Great job!

**Comment by cagnulein** [comment]
wow! can we close this so?

**Comment by marklogan17** [comment]
Yup I think so!

**Comment by cagnulein** [comment]
ok! in case feel free to reopen this ;)

**Comment by cagnulein** [comment]
i saw something very stupid last night @marklogan17 kjoules and calories are the same thing :D i guess you didn't noticied because the echelon bike doesn't send it via bluetooth. But instead, on my treadmill, that sends it, i saw kjoules and calories with the same value :D

what do you think?

**Comment by marklogan17** [comment]
In Echelon they show calories (likely calculated in app) but they are different than total output. Not a huge difference - I think they may take someone's weight into effect.  Here's a post from the Echeleon/Peleton Facebook page on it:

https://www.facebook.com/groups/pelotonplusecholon/permalink/270899844212690

**Comment by cagnulein** [comment]
ok so the kjouice that i added is more precise than calories?

**Comment by marklogan17** [comment]
It is an 'accurate' measure of total output.  I think calories is more personal and would change with different people/sizes/BMI/etc.  So having them the same as a base is probably not incorrect.  I think it would require more personal information to make the calories 'more' correct.
