### ISSUE TITLE
Fitex F1

### ISSUE THREAD

**Issue by Rerkdee** [cagnulein/qdomyos-zwift#701]
[debug-ศ__ก_พ__25_21_16_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8141835/debug-.__._.__25_21_16_50_2022.log)

**Comment by cagnulein** [comment]
#698 please @Rerkdee use the same ticket don't open a new one every time, thanks.

**Comment by Rerkdee** [comment]
I did.

เมื่อ ศ. 25 ก.พ. 2565 เวลา 21:23 Roberto Viola ***@***.***>
เขียนว่า:
