### ISSUE TITLE
[BUG] Spirit CT800 Treadmill data capture

### ISSUE THREAD

**Issue by paulcupo** [cagnulein/qdomyos-zwift#705]
**Describe the bug**
Data capture to understand how the Spirit app controls their treadmill

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by paulcupo** [comment]
[dumpstate-2022-02-28-10-10-00.zip](https://github.com/cagnulein/qdomyos-zwift/files/8154422/dumpstate-2022-02-28-10-10-00.zip)

**Comment by cagnulein** [comment]
@paulcupo please post it here #703 thanks
