### ISSUE TITLE
RUNN module + Hardware Buttons for Speed and Incline with a Raspberry

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#706]
Thank you for your prompt response. I am using a similar method to hb9ok with gpio pins to relay to simulate membrane keypad pressed on the treadmill console control board.  I have tested that system out by manually triggering the gpio pins -> relays and it works to change the speed and incline on the treadmill. The ideal solution would be yes to gather the speed data/cadence from the RUNN module and send that to zwift and receive the incline data from zwift and output it as changes via GPIO. RUNN also transmits out incline data measured from the treadmill but it can be noisy so would be confusing I think to use as true incline rather than just counting button presses.

_Originally posted by @skoregon in https://github.com/cagnulein/qdomyos-zwift/issues/525#issuecomment-1055049280_

**Comment by cagnulein** [comment]
@skoregon created :)

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/156703944-9fa543a8-da51-4838-b7a8-0151f1d6695b.jpeg)![image](https://user-images.githubusercontent.com/48216/156703955-80d1de31-0174-4fbe-809f-d084fe91a635.jpeg)![image](https://user-images.githubusercontent.com/48216/156703958-d20ba29c-bb90-49bb-afc1-0acb5c084c17.jpeg)![image](https://user-images.githubusercontent.com/48216/156703967-6cad3bbc-ace0-4492-9718-15d4a2204509.jpeg)

**Comment by skoregon** [comment]
What more information could I provide to allow the RUNN module to be used as a data source for qdomyos?

**Comment by cagnulein** [comment]
runn bluetooth info from my point of view could be useless if you use the gpios from the treadmill. I mean with the GPIO you can know the real speed and real incline at any moment

**Comment by skoregon** [comment]
Thanks for inquiring!  I did manage to get virtualtreadmill to show up as a bridge, but have a few questions about the GPIOtreadmill module.  I think having speed provided externally to the Pi might be helpful (e.g. RUNN), but see my comment in the GPIO issue. 
https://github.com/cagnulein/qdomyos-zwift/issues/525#issuecomment-1079578597

**Comment by skoregon** [comment]
I’d still suggest that have QZ pickup speed from a sensor (runn or Garmin or stryd or any other running speed bt sensor) would be helpful for treadmill mods since zwift won’t provide speed control data. Having qz accept speed source and send on to zwift would be helpful to allow incline only controls with zwift (the gpio project) and have speed just controlled from the treadmill buttons as usual. However, I know this project is a strong effort of mainly one person, so if not in scope, so goes it!

**Comment by cagnulein** [comment]
@skoregon probably i'm not getting this.
i mean qz is collecting the speed from your treadmill counting the gpio presses for the speed. so it should be perfect. a lot more than runn device m. but probably you have something different in mind and i don't get it

**Comment by cagnulein** [comment]
@skoregon what about this ticket? i mean do you still need it?
