### ISSUE TITLE
[REQ] Profiles for running and riding.

### ISSUE THREAD

**Issue by Kasdal** [cagnulein/qdomyos-zwift#707]
I was thinking about a useful feature to implement would be profiles.
Since a lot of people are using QZ with multiple devices, you could add a dropdown or tiles on main screen with pre-saved and pre-configured profiles for each user select devices. 

Example: Running, user would select a running profile which would display tiles only for running.

Ride a bike, bike tiles.
 Or i know that many use zwift workout erg mode and zwift free ride interchangeably which requires you to change settings for auto resistance to work.
 Or say a user could have multiple profiles with zwift resistance offsets and so on.

**Comment by cagnulein** [comment]
already here @Kasdal  #118 :)
You can do it with the load/save settings for now

**Comment by Kasdal** [comment]
Ahh, didn't even notice that. I guess i could have performed a more detailed search. :) 
Thank you.
