### ISSUE TITLE
[REQ] Can we get this working with the Weslo Cadence G 5.9i 

### ISSUE THREAD

**Issue by shaolin95** [cagnulein/qdomyos-zwift#709]
I opened the app and then connected the Treadmill and the app actually went to the Tiles window so I was pumped BUT nothing changes there..is not really reading things but at least there is hope that you can get it working?
Thank you!

**Comment by cagnulein** [comment]
Hi @shaolin95 please share a debug log

**Comment by cagnulein** [comment]
@shaolin95 Are you still interested on this?

**Comment by scotsman2k** [comment]
Not the OP but I’m also looking for this to be supported and can pull logs from app if that’s what’s needed. Log shows treadmill connection as a proform and none of metrics show on the tiles.

**Comment by cagnulein** [comment]
@scotsman2k yes sure send me a debug log and i will check it!

**Comment by scotsman2k** [comment]
[debug-Sat_Aug_20_16_25_11_2022.txt.log](https://github.com/cagnulein/qdomyos-zwift/files/9411238/debug-Sat_Aug_20_16_25_11_2022.txt.log)

**Comment by cagnulein** [comment]
`Good news, it registers the metrics. However it looks like the distance on the treadmill is showing as the speed in the app. It increments at the same rate. Therefore the pace/calories are off. Attached logs as well.

Thanks 
Easton`
[debug-Wed_Aug_24_23_14_23_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9422171/debug-Wed_Aug_24_23_14_23_2022.log)
![IMG_2427](https://user-images.githubusercontent.com/48216/186595537-a723f6f6-a02d-44da-a4a6-bf5b78de02de.jpeg)
![image](https://user-images.githubusercontent.com/48216/186595544-2a4e8821-edec-4bc9-b874-d297cb9bd0e4.png)

**Comment by shaolin95** [comment]
I would love to test this as well.
Thanks

**Comment by cagnulein** [comment]
@shaolin95 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@shaolin95 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by shaolin95** [comment]
Yes I am. Have been crazy busy with a new puppy...a handful!
Let me find the info you sent me so I can provide the information you need.
Thanks

**Comment by cagnulein** [comment]
wow! send some pics about the puppy! :)

**Comment by cagnulein** [comment]
@shaolin95 any news?
