### ISSUE TITLE
iOS - Echelon cadence is zero

### ISSUE THREAD

**Issue by andyw8** [cagnulein/qdomyos-zwift#71]
Hi, I bought the iOS app from the App Store. It connects successfully to my Echelon Sport bike and to my iPhone SE 2020. But the cadence stays at zero. I have the "Cadence Sensor (Peloton compatability)" enabled. Any suggestion for troubleshooting? I've tried restarting everything.

**Comment by marklogan17** [comment]
@andyw8 do you see the boxes appear (under the start/stop buttons) for speed/distance/cadence/output/etc?  Do any of them get values?  If you could post a picture or a screen shot that may be helpful.

The Cadence Sensor setting (and the Heart rate outside of FTMS) setting are only for the connection to Peleton or Zwift.  You should be able to essentially replicate the Echelon Free Ride functionality with just the iPhone connected to the device.

**Comment by andyw8** [comment]
Sorry, missed some detail – the cadence shows in the qdomyos-zwift app but not in the Peleton app.

**Comment by andyw8** [comment]
<img width="211" alt="Screen Shot 2020-12-11 at 3 01 11 PM" src="https://user-images.githubusercontent.com/13400/101949527-bb2dcd00-3bc1-11eb-86d4-95d520835c3d.png">
<img width="565" alt="Screen Shot 2020-12-11 at 3 01 03 PM" src="https://user-images.githubusercontent.com/13400/101949528-bbc66380-3bc1-11eb-97f8-9d555653642f.png">

**Comment by marklogan17** [comment]
Interesting.  I never saw that.  What are your settings in the bridge (top left corner menu, then settings)?

**Comment by andyw8** [comment]
"Use Miles unit in UI" off
"Cadence Sensor (Peloton compatability)" on
"Heart Rate service out FTSMS" off
Zwift Resistance Offset 4
Zwift Resistance Gain 1

**Comment by cagnulein** [comment]
Could you try to short up your phone name and avoiding strange character?
Maybe just "iphone".

Il ven 11 dic 2020, 21:11 Andy Waite <notifications@github.com> ha scritto:

**Comment by marklogan17** [comment]
You also may want to try 'Heart Rate' set to 'on' too.  That's where I have it set.

**Comment by andyw8** [comment]
Thanks for both suggestions but no luck so far.

**Comment by cagnulein** [comment]
Just to be sure: qdomyos runs on iphone 2020 se, peloton where does it run? You know that you need another device isn't it? 

I know this is a dumb question, but i have to evaluate every way.

@marklogan17 could we try another app instead of peloton?

**Comment by marklogan17** [comment]
@andyw8 could you install Kinetic or Wahoo apps and try and connect the cadence sensor to them instead of the peleton app?

**Comment by andyw8** [comment]
I'm running the Peleton app on an iPad mini 2, 32GB, iOS 12.4.8.

I'll try with one of those other apps.

**Comment by marklogan17** [comment]
@andyw8 are you on the beta or the released version?

**Comment by andyw8** [comment]
> @andyw8 are you on the beta or the released version?

Official release from the app store.

**Comment by andyw8** [comment]
So I tried both Kinetic and Wahoo - no luck. Could it be that the Bluetooth hardware in my iPad is too old? It's from ~2014.

**Comment by marklogan17** [comment]
I'm finally (almost) finished work for the day.  I'll be trying to replicate this shortly...

**Comment by taylorschaerer** [comment]
This is a long shot, but may be worth trying. I have the same bike (echelon sport) and I just downloaded the domyos-Zwift app in the store to try it today. I'm running the app on a 2020 iPhone SE and Zwift on a first gen iPad Pro. I had trouble keeping stable Bluetooth connection between the phone and iPad. I eventually disabled WiFi and Antenna (leaving Bluetooth enabled) and my connections were stable after that. Again, it's a long shot, but might be worth trying to disable WiFi/Antenna on the phone just to be sure.

**Comment by marklogan17** [comment]
I just ran some tests.  My Pixel 2 XL worked perfectly with the most recent version, connecting to my Galaxy S20 FE and to my iPhone 8.  On the galaxy I connected to Wahoo.  On the iPhone I connected to Wahoo and Peleton.  I then tried from Galaxy S20 and neither my pixel nor the iPhone received it.  I did get a couple of times within Wahoo where it saw the connection briefly but not constant and it never connected.  
So @taylorschaerer you may be on to something.  I'll try again later tonight with wifi and such off on the galaxy and/or the iPhone/Pixel.  In the mean time I've attached the logs from the pixel and the Galaxy for the sessions in case there's a difference.  

@cagnulein this was both with the version you gave me today (1.5.1 was the zip file but log is saying 1.4.8?).

[galaxy-debug-Fri Dec 11 18_46_11 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5682149/galaxy-debug-Fri.Dec.11.18_46_11.2020.log)
[pixel-debug-Fri Dec 11 18_18_12 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5682150/pixel-debug-Fri.Dec.11.18_18_12.2020.log)

**Comment by andyw8** [comment]
I tried disabling wifi (it's non-cellular iPad) but it didn't seem to have any effect.

**Comment by marklogan17** [comment]
> I tried disabling wifi (it's non-cellular iPad) but it didn't seem to have any effect.

Try on your iPhone.  Its feeling to me like maybe its the broadcasting that is weak, more than the receiving...

**Comment by marklogan17** [comment]
Interesting.  I connected my Galaxy to my bike.  I started Wahoo app on iPhone.  No connection.  Turned off wifi on my Galaxy, instant connection to iPhone and cadence came across.  While pedaling I turned on the wifi on the galaxy phone again and the cadence value disappeared right away.  Waited a few seconds, turned off wifi on the galaxy again - had to 'search' for the connection in the wahoo app but it came up right away and cadence value appeared.

I wonder if newer bluetooth chipsets are showing this problem?   Could be as simple as antenna designs I guess.  Anyway, give it a try.

**Comment by cagnulein** [comment]
> [galaxy-debug-Fri Dec 11 18_46_11 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5682149/galaxy-debug-Fri.Dec.11.18_46_11.2020.log)
> [pixel-debug-Fri Dec 11 18_18_12 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5682150/pixel-debug-Fri.Dec.11.18_18_12.2020.log)

@marklogan17 could you please collect me some logs when wifi is on? on both these logs everything seems fine, i saw cadence to peloton/zwift is ok

**Comment by marklogan17** [comment]
@cagnulein both of those were with wifi on.  That galaxy log was where I didn't get a connection to any other device.  i.e. it connected to the bike and ran perfectly, but the connection to peleton/wahoo/etc just didn't appear.

The log below is from when I triggered wifi on and off on the galaxy.  This is the one where I got the connection to wahoo when the wifi was off and then the connection went away with wifi on.  

[debug-Fri Dec 11 20_20_22 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5683202/debug-Fri.Dec.11.20_20_22.2020.log)

**Comment by marklogan17** [comment]
Did a bunch of testing - here are steps and results:
1) Rebooted Galaxy S20 
2) Started app and connected to bike - note:  wifi ON
3) Ran nrf Connect on Pixel 2XL - found S20, found cadence
4) Thought I closed nrf Connect (didn't actually but turned out not to matter), ran Wahoo on Pixel.  Found cadence sensor, connected, cadence came across correctly, closed Wahoo
5) Ran wahoo on iPhone 8 - did NOT find cadence sensor
6) Turned off wifi on iPhone 8 - did NOT find cadence sensor
7) realized nrf Connect was still running on pixel so closed it.  Repeated 4, 5 and 6 - same results
8) airplane mode on/off on iPhone - still no connection
9) Back to pixel - immediate connection on wahoo
10) Reboot iPhone - go into wahoo, took some time but suddenly cadence sensor appeared, signal was good, cadence came across.  Stayed consistent.  Note that this was with wifi ON on both devices.

I did NOT restart the qdomyous app at any time during these tests.  It stayed up, running and connected to the bike.  I would pedal during the tests to make sure there was cadence going across the interface.

Seems to me to be related to iOS bluetooth stack, but may be just weirdness between devices because I never had a problem from my pixel to the iPhone.

**Comment by cagnulein** [comment]
@marklogan17 thank you very much for sharing your discoveries! so we can summarize it "if the iphone doesn't see the bridge, restart the phone", isn't it?

**Comment by marklogan17** [comment]
:)  Well that certainly fixed it for me this time.  Interested to see if others have the same experience.  If I can make it fail consistently again, I'll reboot and see.

**Comment by cagnulein** [comment]
@andyw8 any news about it?

**Comment by cagnulein** [comment]
i just open an issue to Qt guys https://bugreports.qt.io/browse/QTBUG-89730

**Comment by cagnulein** [comment]
**Notes to myself: try to use 16bit UUID instead of the qt default for cadence and heart service on iOS**

**Comment by cagnulein** [comment]
https://bugreports.qt.io/browse/QTBUG-89768

**Comment by cagnulein** [comment]
i'm closing this one for god sake!
