### ISSUE TITLE
[REQ] Add Reebok FR30 treadmill

### ISSUE THREAD

**Issue by cernst** [cagnulein/qdomyos-zwift#710]
The treadmill works with kinomap, but doesn't show up in zwift.

The QZ app (android) is also not able to find it.
It would be great if we could add it to the app.

Here is the btsnoop-log:
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8167987/btsnoop_hci.log)

The treadmill shows up as REEBOK0928.
 - I've started the treadmill
 - Increased speed to 1
 - Increased inclination to 1
 - Increased speed to 5
 - Set inclination to 3
 - Set inclination to 0
 - Stopped the treadmill

Let me know, if I can do anything to help :)

**Comment by cernst** [comment]
Hey, after restarting my phone the QZ app now finds my treadmill and connects to it :)
Yesterday I only got the "connecting..." label.
The app shows the correct speed and inclination, but I can't change these with the app.

When I try to connect to zwift, it finds my pixel phone and connects to it.
In the game unfortunately it does not show the speed. Instead I get the connection error notification in the top left corner...

**Comment by cagnulein** [comment]
> The app shows the correct speed and inclination, but I can't change these with the app.

neither the inclination?
you should be able to change it




> In the game unfortunately it does not show the speed. Instead I get the connection error notification in the top left corner...

check this https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift

**Comment by cernst** [comment]
> neither the inclination?

yes, if I tab on the '+' or '-' buttons, nothing happens.
I tried it on my pixel3a phone and on my Samsung Galaxy Tab S6 Lite tablet.

I also couldn't fix the connection problem.
 - I tried changing the device name to 'bike'
 - virtual device setting is enabled
 - when I swapped phone and tablet, zwift couldn't even find the tablet to connect.

**Comment by cagnulein** [comment]
> yes, if I tab on the '+' or '-' buttons, nothing happens.

i guess i got this. you need the beta for this. Join the from the play store and let me know if it changes something. You have to see version 2.10.39 then

> * I tried changing the device name to 'bike'

did you reboot after? did you see the device "bike" on zwift?

> * virtual device setting is enabled
> * when I swapped phone and tablet, zwift couldn't even find the tablet to connect.

so the tablet can't act as a bridge for sure. Don't you have other android device to try? or a pc for zwift?

**Comment by cernst** [comment]
The beta helped for the inclination. I can know change it with the app :)

> did you reboot after? did you see the device "bike" on zwift?

yes, and it was listed as 'bike' in zwfit

> or a pc for zwift?

zwift on the pc is not able to find my phone. I also tried using the companion app on my tablet, but the pc still couldn't find it.

**Comment by cagnulein** [comment]
if you can't see the companion app you have another issue with zwift because the companion app is by wifi not bluetooth. are you able to get metrics on the companion app from the pixel? don't you have a thrid android device? even an older one?

**Comment by cernst** [comment]
ok, I just tried it with a third android device (running android 12) and I got the companion app to connect the treadmill, but it has the same problem. Zwift doesn't know the speed and just says connection failure.
The heartrate-sensor connected through the companion app is working fine.

Same result when I run zwift directly on the third phone. It pairs my pixel phone running QZ app, but then I get no data...

**Comment by cagnulein** [comment]
which device is the android 12 one? can you try to enable the "Run Cadence Sensor" setting and restart QZ? Let me know

**Comment by cernst** [comment]
> which device is the android 12 one?

My pixel 3a phone and the third phone a running android 12. The samsung tablet is running android 11.

> can you try to enable the "Run Cadence Sensor" setting and restart QZ?

after enabling, the cadence sensor and the treadmill were both connected in the zwift pairing screen, but the problem in the game is the same: connection failure.

**Comment by cagnulein** [comment]
@cernst so strange: don't you have even an old iOS device to try? it seems that all the android device that you're using don't have bluetooth capabilites to run the bridge mode on bluetooth

**Comment by cernst** [comment]
Sorry no iOS devices...

But I had an raspberry pi on hand, and it works fine with the pi. no connection issues and zwift gets the correct speed :)

One small thing: the treadmill doesn't change it's inclination. Should that work?

Anyway, thanks for all your help! :)

**Comment by cagnulein** [comment]
Great @cernst , this means that you were very unlucky with the choice of your android phones :D

For the inclination: do you have any other app from reebok that allow you to change the inclination from the app itself?

**Comment by cernst** [comment]
> do you have any other app from reebok that allow you to change the inclination from the app itself

The reebok app changes the inclination based on the training program. But there are no direct buttons to change it.
Kinomap is also able to change the inclination.

But the only direct buttons I've found so far where in your app.

**Comment by cagnulein** [comment]
> The reebok app changes the inclination based on the training program. But there are no direct buttons to change it.
> Kinomap is also able to change the inclination.

great so follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device using kinomap and I will able to add it too on QZ!

Let me know

**Comment by cernst** [comment]
ok, here is the bt-snoop-log:
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8176672/btsnoop_hci.log)

The inclination changes: 10->4->1->3->1

**Comment by cagnulein** [comment]
got it! it's a slightly different protocol. I'm doing this right now @cernst

**Comment by cagnulein** [comment]
done @cernst ! pull it and rebuild it. I added a new setting under the toorx treadmill with the name of your treadmill. Let me know if it works

**Comment by cernst** [comment]
ok, thanks :)

Just to make sure: to apply the setting I have to start it like this?
> qdomyos-zwift -no-gui -no-log -heart-service -reebok-fr30-treadmill

**Comment by cagnulein** [comment]
i didn't add a new command line option for this, if you need i can add it. otherwise you have to run QZ with the -qml flag so you will see the same UI interface of the phone. Let me know which path you want to follow ;)

**Comment by cagnulein** [comment]
@cernst -reebok_fr30_treadmill added. pull it

**Comment by cernst** [comment]
I pulled it, rebuild it and started it wit '-reebok_fr30_treadmill', but it doesn't seem to be working.
Zwift won't change the inclination.

**Comment by cagnulein** [comment]
@cernst for zwift auto inclination you need to folllow my youtube video about "QZ auto inclination on zwift"

**Comment by cagnulein** [comment]
@cernst any news? can we close this?

**Comment by cernst** [comment]
yes, it's working so the issue can be closed.
