### ISSUE TITLE
Metrics glitch on Inspire bike

### ISSUE THREAD

**Issue by diegom3** [cagnulein/qdomyos-zwift#719]
**Describe the bug**
Some metrics (calories, and watts start showing incorrect values after user stops pedaling
**To Reproduce**
1. Open app'
2. user starts pedaling
3. user stops pedaling with app open

**Expected behavior**
App to show correct metrics even after user stops pedaling

**Screenshots**
![Mon Mar 7 18_00_49 2022](https://user-images.githubusercontent.com/67805146/157134614-cb8a734e-02ad-4c7d-8c90-e9a5c52d8152.jpg)
![Mon Mar 7 17_59_35 2022](https://user-images.githubusercontent.com/67805146/157134502-0efd9f28-11e2-48b1-9d8d-49af4145cde2.jpg)
![Mon Mar 7 17_59_46 2022](https://user-images.githubusercontent.com/67805146/157134504-d833c4b3-01e7-44ed-b665-7b484f8a3871.jpg)
![Mon Mar 7 18_00_49 2022](https://user-images.githubusercontent.com/67805146/157134484-e50982c4-8116-4911-88df-e6f01ed8cf79.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 13.3.1
 - Version QZ 2.9

**Append a debug log

[debug-Mon_Mar_7_17_58_22_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8201423/debug-Mon_Mar_7_17_58_22_2022.log)
[debug-Mon_Mar_7_17_59_51_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8201425/debug-Mon_Mar_7_17_59_51_2022.log)
**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@diegom3 thanks, i guess i fixed now in the beta. It will be in the version 2.10.45
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@diegom3 did you try this?

**Comment by diegom3** [comment]
Yes, it’s working fine now. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
