### ISSUE TITLE
[BUG][debug builds only?] Unable to connect to Strava

### ISSUE THREAD

**Issue by grantland** [cagnulein/qdomyos-zwift#721]
**Describe the bug**
Connect to Strava doesn't seem to work, but not sure if this is just an issue on debug builds or just my dev env

**To Reproduce**
1. Click on "Connect to Strava"
2. Go through flow and see success page

**Expected behavior**
1. Debug output `strava_code <valid_data>`
2. `replyDataReceived` gets called 
3. Strava is connected

**Actual behavior**
1. Debug output `strava_code <valid_data>`
2. `replyDataReceived` does not get called
3. No Strava tokens saved

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: emulator, Pixel 4, Fire HD 8
 - OS: API 30
 - Version: master

**Append a debug log**
 https://gist.github.com/grantland/a4e1b81aee07d6f94f2601c56fcf07af
  
**Additional context**

**Comment by cagnulein** [comment]
you need the api key. check the define in the homeform.cpp
you need also to change your client if

**Comment by grantland** [comment]
Ah that makes sense! Is that `STRAVA_CLIENT_ID` in `homeform.cpp` or something else?

**Comment by cagnulein** [comment]
and also this STRAVA_SECRET_KEY @grantland

**Comment by grantland** [comment]
Works thanks!

For future reference:
1. Create API Application at https://developers.strava.com/
2. Modify `src/secret.h`:
```
#ifndef STRAVA_CLIENT_ID
#define STRAVA_CLIENT_ID <client id>
#endif
#ifndef STRAVA_SECRET_KEY
#define STRAVA_SECRET_KEY <client secret>
#endif
```

**Comment by cagnulein** [comment]
i'm using the file secret.h to add those, of course it's not commited
