### ISSUE TITLE
Initial setup with raspberry pi 4 400 no heart rate seen

### ISSUE THREAD

**Issue by skoregon** [cagnulein/qdomyos-zwift#726]
**Describe the bug**
I am setting up headless qdoymos on a raspberry pi 4 400 running Bullseye.   When I finish the installation instructions I run the command sudo ./qdomyos-zwift -no-gui -heart-service but do not detect a heart rate service from Zwift running on an AppleTV

**To Reproduce**
Installed fresh copy of RaspberryOS (Bullseye) Raspberry Pi OS Lite from https://www.raspberrypi.com/.
Execute qdoymos installation instructions:
$ sudo apt update && sudo apt upgrade # this is very important on raspberry pi: you need the bluetooth firmware updated!
$ sudo sudo apt install git libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-assistant libqt5networkauth5-dev libqt5websockets5-dev
$ git clone https://github.com/cagnulein/qdomyos-zwift.git
$ cd qdomyos-zwift
$ git submodule update --init src/smtpclient/
$ git submodule update --init src/qmdnsengine/
$ cd src
$ qmake
$ make -j4
$ sudo ./qdomyos-zwift

run 
sudo ./qdomyos-zwift -no-gui -heart-service 

**Expected behavior**
I expected to be able to detect a heart rate bluetooth service in Zwift or using my iPhone.  I did not. No service visible for heart rate.  I am able to detect the heart rate service from my heart rate strap as usual.  Debug log appended.

**Screenshots**

**Desktop (please complete the following information):**
Raspberry Pi 4 400
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

**Append a debug log**
see attached.

**Comment by cagnulein** [comment]
@skoregon sorry but i don't see the log attached. Could you please attach it again?

**Comment by skoregon** [comment]
[debug log.txt](https://github.com/cagnulein/qdomyos-zwift/files/8224748/debug.log.txt)
`Wed Mar 9 04:46:38 2022 1646801198565 Debug: main.cpp int main(int, char**) "version " ""
Wed Mar 9 04:46:38 2022 1646801198566 Debug: main.cpp int main(int, char**) "battery_service" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198566 Debug: main.cpp int main(int, char**) "bike_cadence_sensor" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198566 Debug: main.cpp int main(int, char**) "bike_power_sensor" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198567 Debug: main.cpp int main(int, char**) "bike_wheel_revs" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198567 Debug: main.cpp int main(int, char**) "bluetooth_no_reconnection" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198567 Debug: main.cpp int main(int, char**) "bluetooth_relaxed" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198567 Debug: main.cpp int main(int, char**) "miles_unit" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198567 Debug: main.cpp int main(int, char**) "nordictrack_10_treadmill" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198568 Debug: main.cpp int main(int, char**) "reebok_fr30_treadmill" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198568 Debug: main.cpp int main(int, char**) "run_cadence_sensor" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198568 Debug: main.cpp int main(int, char**) "service_changed" QVariant(bool, false)
Wed Mar 9 04:46:38 2022 1646801198568 Debug: main.cpp int main(int, char**) "template_inner_QZWS_enabled" QVariant(QString, "true")
Wed Mar 9 04:46:38 2022 1646801198569 Debug: main.cpp int main(int, char**) "template_inner_QZWS_folders" QVariant(QString, ":/inner_templates//chartjs")
Wed Mar 9 04:46:38 2022 1646801198569 Debug: main.cpp int main(int, char**) "template_inner_QZWS_ips" QVariant(QString, "192.168.1.16")
Wed Mar 9 04:46:38 2022 1646801198569 Debug: main.cpp int main(int, char**) "template_inner_QZWS_port" QVariant(QString, "0")
Wed Mar 9 04:46:38 2022 1646801198569 Debug: main.cpp int main(int, char**) "template_inner_QZWS_type" QVariant(QString, "WebServer")
Wed Mar 9 04:46:38 2022 1646801198570 Debug: main.cpp int main(int, char**) "template_inner_ids" QVariant(QString, "inner_QZWS")
Wed Mar 9 04:46:38 2022 1646801198570 Debug: main.cpp int main(int, char**) "template_user_QZWS_enabled" QVariant(QString, "false")
Wed Mar 9 04:46:38 2022 1646801198570 Debug: main.cpp int main(int, char**) "template_user_QZWS_folders" QVariant(QStringList, (":/templates//debug", ":/templates//example"))
Wed Mar 9 04:46:38 2022 1646801198570 Debug: main.cpp int main(int, char**) "template_user_QZWS_ips" QVariant(QString, "192.168.1.16")
Wed Mar 9 04:46:38 2022 1646801198570 Debug: main.cpp int main(int, char**) "template_user_QZWS_type" QVariant(QString, "WebServer")
Wed Mar 9 04:46:38 2022 1646801198571 Debug: main.cpp int main(int, char**) "template_user_ids" QVariant(QStringList, ("user_vlc", "user_qz", "user_QZWS"))
Wed Mar 9 04:46:38 2022 1646801198571 Debug: main.cpp int main(int, char**) "template_user_qz_enabled" QVariant(QString, "false")
Wed Mar 9 04:46:38 2022 1646801198571 Debug: main.cpp int main(int, char**) "template_user_qz_type" QVariant(QString, "TcpClient")
Wed Mar 9 04:46:38 2022 1646801198571 Debug: main.cpp int main(int, char**) "template_user_vlc_enabled" QVariant(QString, "false")
Wed Mar 9 04:46:38 2022 1646801198572 Debug: main.cpp int main(int, char**) "template_user_vlc_type" QVariant(QString, "TcpClient")
Wed Mar 9 04:46:38 2022 1646801198576 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Load start from" "QZTemplates"
Wed Mar 9 04:46:38 2022 1646801198577 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Load start from" ":/templates/"
Wed Mar 9 04:46:38 2022 1646801198577 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template Dir Found" ":/templates/d
ebug"
Wed Mar 9 04:46:38 2022 1646801198578 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template File Found" ":/templates/
vlc-TcpClient.qzt"
Wed Mar 9 04:46:38 2022 1646801198578 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template type" "TcpClient" " id" "
user_vlc"
Wed Mar 9 04:46:38 2022 1646801198578 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template" "user_vlc" " is disabled
: not created"
Wed Mar 9 04:46:38 2022 1646801198579 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template File Found" ":/templates/
qz-TcpClient.qzt"
Wed Mar 9 04:46:38 2022 1646801198579 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template type" "TcpClient" " id" "
user_qz"
Wed Mar 9 04:46:38 2022 1646801198579 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template" "user_qz" " is disabled:
 not created"
Wed Mar 9 04:46:38 2022 1646801198579 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template Dir Found" ":/templates/e
xample"
Wed Mar 9 04:46:38 2022 1646801198580 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Folder List" (":/templates//debug", ":/templates//example")
Wed Mar 9 04:46:38 2022 1646801198580 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "addressList " ("192.168.1.16")
Wed Mar 9 04:46:38 2022 1646801198588 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Template" "user_QZWS" " is disabled: not created"
Wed Mar 9 04:46:38 2022 1646801198588 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Setting template_ids" ("user_vlc", "user_qz", "user_QZWS")
Wed Mar 9 04:46:38 2022 1646801198601 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Load start from" ":/inner_templates/"
Wed Mar 9 04:46:38 2022 1646801198601 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::createTemplatesFromFolder(const QString&, const QString&, QStringList&) "Template Dir Found" ":/inner_templ
ates/chartjs"
Wed Mar 9 04:46:38 2022 1646801198601 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Folder List" (":/inner_templates//chartjs")
Wed Mar 9 04:46:38 2022 1646801198602 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "addressList " ("192.168.1.16")
Wed Mar 9 04:46:38 2022 1646801198611 Debug: templateinfosenderbuilder.cpp void TemplateInfoSenderBuilder::load(const QString&, const QStringList&) "Setting template_ids" ("inner_QZWS")
Wed Mar 9 04:46:38 2022 1646801198624 Debug:   Bluez 5 detected.
Wed Mar 9 04:46:38 2022 1646801198630 Debug:   Creating QtBluezDiscoveryManager
Wed Mar 9 04:46:38 2022 1646801198634 Debug:   BluetoothManagement: Ignored event: 13
Wed Mar 9 04:46:38 2022 1646801198638 Debug:   BluetoothManagement: found random device "76:99:64:48:AC:F0"
Wed Mar 9 04:46:38 2022 1646801198638 Debug:   Discovered:  "76-99-64-48-AC-F0" "76:99:64:48:AC:F0" Num UUIDs 0 total device 0 cached RSSI -73 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198639 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 76-99-64-48-AC-F0 (76:99:64:48:AC:F0) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198718 Debug:   BluetoothManagement: found random device "C9:86:74:CB:D5:D4"
Wed Mar 9 04:46:38 2022 1646801198719 Debug:   BluetoothManagement: found random device "04:DD:D1:72:78:41"
Wed Mar 9 04:46:38 2022 1646801198720 Debug:   Discovered:  "C9-86-74-CB-D5-D4" "C9:86:74:CB:D5:D4" Num UUIDs 0 total device 1 cached RSSI -68 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198720 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: C9-86-74-CB-D5-D4 (C9:86:74:CB:D5:D4) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198721 Debug:   Discovered:  "04-DD-D1-72-78-41" "04:DD:D1:72:78:41" Num UUIDs 0 total device 2 cached RSSI -41 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198721 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 04-DD-D1-72-78-41 (04:DD:D1:72:78:41) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198739 Debug:   BluetoothManagement: found random device "1D:E0:69:E9:81:F3"
Wed Mar 9 04:46:38 2022 1646801198740 Debug:   Discovered:  "1D-E0-69-E9-81-F3" "1D:E0:69:E9:81:F3" Num UUIDs 0 total device 3 cached RSSI -79 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198740 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 1D-E0-69-E9-81-F3 (1D:E0:69:E9:81:F3) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198827 Debug:   Discovered:  "LEDnetWF01003323C7EE" "B4:E8:42:23:C7:EF" Num UUIDs 0 total device 4 cached RSSI -66 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198828 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: LEDnetWF01003323C7EE (B4:E8:42:23:C7:EF) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198828 Debug:   Discovered:  "D0-D2-B0-A3-C1-4B" "D0:D2:B0:A3:C1:4B" Num UUIDs 0 total device 5 cached RSSI -44 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198829 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: D0-D2-B0-A3-C1-4B (D0:D2:B0:A3:C1:4B) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198846 Debug:   BluetoothManagement: found random device "DA:2B:0C:A7:45:1B"
Wed Mar 9 04:46:38 2022 1646801198854 Debug:   Discovered:  "KICKR CORE 963B" "DA:2B:0C:A7:45:1B" Num UUIDs 2 total device 6 cached RSSI -55 Num ManufacturerData 0
Wed Mar 9 04:46:38 2022 1646801198854 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: KICKR CORE 963B (DA:2B:0C:A7:45:1B) \u0000:\u0000"
Wed Mar 9 04:46:38 2022 1646801198922 Debug:   Updating RSSI for "B4:E8:42:23:C7:EF" QVariant(short, -61)
Wed Mar 9 04:46:38 2022 1646801198922 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "deviceUpdated LEDnetWF01003323C7EE \u0001"
Wed Mar 9 04:46:38 2022 1646801198950 Debug:   BluetoothManagement: found random device "68:50:91:F0:30:A1"
Wed Mar 9 04:46:38 2022 1646801198951 Debug:   Discovered:  "68-50-91-F0-30-A1" "68:50:91:F0:30:A1" Num UUIDs 0 total device 7 cached RSSI -76 Num ManufacturerData 1
Wed Mar 9 04:46:38 2022 1646801198951 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 68-50-91-F0-30-A1 (68:50:91:F0:30:A1) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199321 Debug:   BluetoothManagement: found random device "57:16:75:4E:39:CD"
Wed Mar 9 04:46:39 2022 1646801199323 Debug:   Discovered:  "57-16-75-4E-39-CD" "57:16:75:4E:39:CD" Num UUIDs 0 total device 8 cached RSSI -84 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199324 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 57-16-75-4E-39-CD (57:16:75:4E:39:CD) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199345 Debug:   BluetoothManagement: found random device "40:CB:7E:FF:22:18"
Wed Mar 9 04:46:39 2022 1646801199347 Debug:   Discovered:  "40-CB-7E-FF-22-18" "40:CB:7E:FF:22:18" Num UUIDs 0 total device 9 cached RSSI -77 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199348 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 40-CB-7E-FF-22-18 (40:CB:7E:FF:22:18) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199568 Debug:   BluetoothManagement: found random device "2B:CD:ED:95:5B:FB"
Wed Mar 9 04:46:39 2022 1646801199570 Debug:   Discovered:  "2B-CD-ED-95-5B-FB" "2B:CD:ED:95:5B:FB" Num UUIDs 0 total device 10 cached RSSI -94 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199572 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 2B-CD-ED-95-5B-FB (2B:CD:ED:95:5B:FB) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199589 Debug:   BluetoothManagement: found random device "38:47:9C:7C:F6:90"
Wed Mar 9 04:46:39 2022 1646801199591 Debug:   Discovered:  "38-47-9C-7C-F6-90" "38:47:9C:7C:F6:90" Num UUIDs 0 total device 11 cached RSSI -89 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199593 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 38-47-9C-7C-F6-90 (38:47:9C:7C:F6:90) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199597 Debug:   BluetoothManagement: found random device "4A:51:6A:36:E3:6D"
Wed Mar 9 04:46:39 2022 1646801199599 Debug:   Discovered:  "4A-51-6A-36-E3-6D" "4A:51:6A:36:E3:6D" Num UUIDs 0 total device 12 cached RSSI -83 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199601 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 4A-51-6A-36-E3-6D (4A:51:6A:36:E3:6D) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199605 Debug:   Discovered:  "E6-F7-FD-C7-7F-F3" "E6:F7:FD:C7:7F:F3" Num UUIDs 0 total device 13 cached RSSI -73 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199606 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: E6-F7-FD-C7-7F-F3 (E6:F7:FD:C7:7F:F3) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199609 Debug:   BluetoothManagement: found random device "E6:F7:FD:C7:7F:F3"
Wed Mar 9 04:46:39 2022 1646801199632 Debug:   BluetoothManagement: found random device "3F:A5:63:01:6B:BF"
Wed Mar 9 04:46:39 2022 1646801199634 Debug:   Discovered:  "3F-A5-63-01-6B-BF" "3F:A5:63:01:6B:BF" Num UUIDs 1 total device 14 cached RSSI -82 Num ManufacturerData 0
Wed Mar 9 04:46:39 2022 1646801199636 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 3F-A5-63-01-6B-BF (3F:A5:63:01:6B:BF) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199638 Debug:   BluetoothManagement: found random device "CF:81:E5:5D:88:1B"
Wed Mar 9 04:46:39 2022 1646801199639 Debug:   Discovered:  "CF-81-E5-5D-88-1B" "CF:81:E5:5D:88:1B" Num UUIDs 0 total device 15 cached RSSI -87 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199641 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: CF-81-E5-5D-88-1B (CF:81:E5:5D:88:1B) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199654 Debug:   Discovered:  "40-CB-C0-A9-E6-33" "40:CB:C0:A9:E6:33" Num UUIDs 0 total device 16 cached RSSI -80 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199655 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 40-CB-C0-A9-E6-33 (40:CB:C0:A9:E6:33) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199789 Debug:   BluetoothManagement: found random device "22:FD:EA:F1:44:91"
Wed Mar 9 04:46:39 2022 1646801199791 Debug:   Discovered:  "22-FD-EA-F1-44-91" "22:FD:EA:F1:44:91" Num UUIDs 0 total device 17 cached RSSI -90 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199324 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 57-16-75-4E-39-CD (57:16:75:4E:39:CD) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199345 Debug:   BluetoothManagement: found random device "40:CB:7E:FF:22:18"
Wed Mar 9 04:46:39 2022 1646801199347 Debug:   Discovered:  "40-CB-7E-FF-22-18" "40:CB:7E:FF:22:18" Num UUIDs 0 total device 9 cached RSSI -77 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199348 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 40-CB-7E-FF-22-18 (40:CB:7E:FF:22:18) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199568 Debug:   BluetoothManagement: found random device "2B:CD:ED:95:5B:FB"
Wed Mar 9 04:46:39 2022 1646801199570 Debug:   Discovered:  "2B-CD-ED-95-5B-FB" "2B:CD:ED:95:5B:FB" Num UUIDs 0 total device 10 cached RSSI -94 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199572 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 2B-CD-ED-95-5B-FB (2B:CD:ED:95:5B:FB) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199589 Debug:   BluetoothManagement: found random device "38:47:9C:7C:F6:90"
Wed Mar 9 04:46:39 2022 1646801199591 Debug:   Discovered:  "38-47-9C-7C-F6-90" "38:47:9C:7C:F6:90" Num UUIDs 0 total device 11 cached RSSI -89 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199593 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 38-47-9C-7C-F6-90 (38:47:9C:7C:F6:90) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199597 Debug:   BluetoothManagement: found random device "4A:51:6A:36:E3:6D"
Wed Mar 9 04:46:39 2022 1646801199599 Debug:   Discovered:  "4A-51-6A-36-E3-6D" "4A:51:6A:36:E3:6D" Num UUIDs 0 total device 12 cached RSSI -83 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199601 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 4A-51-6A-36-E3-6D (4A:51:6A:36:E3:6D) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199605 Debug:   Discovered:  "E6-F7-FD-C7-7F-F3" "E6:F7:FD:C7:7F:F3" Num UUIDs 0 total device 13 cached RSSI -73 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199606 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: E6-F7-FD-C7-7F-F3 (E6:F7:FD:C7:7F:F3) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199609 Debug:   BluetoothManagement: found random device "E6:F7:FD:C7:7F:F3"
Wed Mar 9 04:46:39 2022 1646801199632 Debug:   BluetoothManagement: found random device "3F:A5:63:01:6B:BF"
Wed Mar 9 04:46:39 2022 1646801199634 Debug:   Discovered:  "3F-A5-63-01-6B-BF" "3F:A5:63:01:6B:BF" Num UUIDs 1 total device 14 cached RSSI -82 Num ManufacturerData 0
Wed Mar 9 04:46:39 2022 1646801199636 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 3F-A5-63-01-6B-BF (3F:A5:63:01:6B:BF) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199638 Debug:   BluetoothManagement: found random device "CF:81:E5:5D:88:1B"
Wed Mar 9 04:46:39 2022 1646801199639 Debug:   Discovered:  "CF-81-E5-5D-88-1B" "CF:81:E5:5D:88:1B" Num UUIDs 0 total device 15 cached RSSI -87 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199641 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: CF-81-E5-5D-88-1B (CF:81:E5:5D:88:1B) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199654 Debug:   Discovered:  "40-CB-C0-A9-E6-33" "40:CB:C0:A9:E6:33" Num UUIDs 0 total device 16 cached RSSI -80 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199655 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 40-CB-C0-A9-E6-33 (40:CB:C0:A9:E6:33) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199789 Debug:   BluetoothManagement: found random device "22:FD:EA:F1:44:91"
Wed Mar 9 04:46:39 2022 1646801199791 Debug:   Discovered:  "22-FD-EA-F1-44-91" "22:FD:EA:F1:44:91" Num UUIDs 0 total device 17 cached RSSI -90 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199793 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 22-FD-EA-F1-44-91 (22:FD:EA:F1:44:91) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199808 Debug:   Discovered:  "64-07-F6-3F-9F-66" "64:07:F6:3F:9F:66" Num UUIDs 0 total device 18 cached RSSI -91 Num ManufacturerData 1
Wed Mar 9 04:46:39 2022 1646801199809 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 64-07-F6-3F-9F-66 (64:07:F6:3F:9F:66) \u0000:\u0000"
Wed Mar 9 04:46:39 2022 1646801199848 Debug:   BluetoothManagement: found random device "04:FC:06:07:17:2A"
Wed Mar 9 04:46:39 2022 1646801199850 Debug:   Discovered:  "04-FC-06-07-17-2A" "04:FC:06:07:17:2A" Num UUIDs 1 total device 19 cached RSSI -77 Num ManufacturerData 0
Wed Mar 9 04:46:39 2022 1646801199851 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 04-FC-06-07-17-2A (04:FC:06:07:17:2A) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200069 Debug:   BluetoothManagement: found random device "74:BA:4A:7F:B2:28"
Wed Mar 9 04:46:40 2022 1646801200081 Debug:   Discovered:  "SS3" "A4:CF:12:6F:29:1E" Num UUIDs 1 total device 20 cached RSSI -86 Num ManufacturerData 0
Wed Mar 9 04:46:40 2022 1646801200083 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: SS3 (A4:CF:12:6F:29:1E) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200087 Debug:   Discovered:  "74-BA-4A-7F-B2-28" "74:BA:4A:7F:B2:28" Num UUIDs 0 total device 21 cached RSSI -91 Num ManufacturerData 1
Wed Mar 9 04:46:40 2022 1646801200089 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 74-BA-4A-7F-B2-28 (74:BA:4A:7F:B2:28) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200231 Debug:   BluetoothManagement: found random device "72:6D:37:BD:1A:7D"
Wed Mar 9 04:46:40 2022 1646801200233 Debug:   Discovered:  "72-6D-37-BD-1A-7D" "72:6D:37:BD:1A:7D" Num UUIDs 0 total device 22 cached RSSI -92 Num ManufacturerData 1
Wed Mar 9 04:46:40 2022 1646801200235 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 72-6D-37-BD-1A-7D (72:6D:37:BD:1A:7D) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200333 Debug:   BluetoothManagement: found random device "61:B4:68:72:E0:A7"
Wed Mar 9 04:46:40 2022 1646801200335 Debug:   Discovered:  "61-B4-68-72-E0-A7" "61:B4:68:72:E0:A7" Num UUIDs 0 total device 23 cached RSSI -93 Num ManufacturerData 1
Wed Mar 9 04:46:40 2022 1646801200337 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: 61-B4-68-72-E0-A7 (61:B4:68:72:E0:A7) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200414 Debug:   Discovered:  "C8-69-CD-3B-97-F7" "C8:69:CD:3B:97:F7" Num UUIDs 0 total device 24 cached RSSI -93 Num ManufacturerData 1
Wed Mar 9 04:46:40 2022 1646801200415 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: C8-69-CD-3B-97-F7 (C8:69:CD:3B:97:F7) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200566 Debug:   BluetoothManagement: found random device "DE:B8:8F:3B:3C:06"
Wed Mar 9 04:46:40 2022 1646801200578 Debug:   Discovered:  "SS3" "08:3A:F2:99:B5:F6" Num UUIDs 1 total device 25 cached RSSI -86 Num ManufacturerData 0
Wed Mar 9 04:46:40 2022 1646801200580 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: SS3 (08:3A:F2:99:B5:F6) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200585 Debug:   Discovered:  "DE-B8-8F-3B-3C-06" "DE:B8:8F:3B:3C:06" Num UUIDs 0 total device 26 cached RSSI -85 Num ManufacturerData 1
Wed Mar 9 04:46:40 2022 1646801200588 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Found new device: DE-B8-8F-3B-3C-06 (DE:B8:8F:3B:3C:06) \u0000:\u0000"
Wed Mar 9 04:46:40 2022 1646801200703 Debug:   Updating RSSI for "C8:69:CD:3B:97:F7" QVariant(short, -93)
Wed Mar 9 04:46:40 2022 1646801200704 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "deviceUpdated C8-69-CD-3B-97-F7 \u0001"
Wed Mar 9 04:46:40 2022 1646801200804 Debug: bluetooth.cpp virtual bool bluetooth::handleSignal(int) "SIGINT"
Wed Mar 9 04:46:40 2022 1646801200805 Debug:   Destroying QtBluezDiscoveryManager`

**Comment by cagnulein** [comment]
@skoregon i need a log where you're trying to send HR data to zwift. In this log there's nothing :(

**Comment by skoregon** [comment]
Perhaps I misunderstand.  I have a bluetooth Garmin heart rate strap that I can see in the pairing screen of Zwift on my AppleTV.  I can also see and connect to the strap using NRF Connect (see below) on my iphone.    When I run sudo ./qdomyos-zwift -no-gui -heart-service on my raspberry pi it endlessly appears to be hunting for something to connect to.  The bluetooth strap is not connected to another device when I run the command above.  I stand within 20 inches/50cm of the raspberry pi when executing the command wearing the heart rate strap. 
[debug.log](https://github.com/cagnulein/qdomyos-zwift/files/8241555/debug.log)
![IMG_4811](https://user-images.githubusercontent.com/72465448/158101019-8143b3ac-5152-475a-a33e-e10042f20bb6.PNG)
![IMG_4810](https://user-images.githubusercontent.com/72465448/158101026-79fd83bf-0ed2-433d-9429-d40381cb2e46.PNG)
![zwift](https://user-images.githubusercontent.com/72465448/158101098-0deb57ce-674c-410b-9193-b441cea5c59d.jpg)

**Comment by cagnulein** [comment]
hi @skoregon yes i guess you're missing the main piece :) which your machinery? I mean bike, treadmill..? QZ is looking for one and then, with the QML interface (-qml flag in the console), you can choose the Heart Rate device to link to QZ.

**Comment by skoregon** [comment]
Clearly I did misunderstand!  I first assumed the -heart-service flag would make a simulated heart rate Bluetooth signal from qdomyos then assumed it would accept only a heart rate signal and pass it through by itself. Wrong on both counts. We can close this thread, although it may be helpful to put in the instructions that your compatible exercise device must be active to successfully run the sudo ./qdomyos-zwift -no-gui -heart-service command.

**Comment by cagnulein** [comment]
@skoregon is everything ok?
