### ISSUE TITLE
[BUG] Zwift Autoresistance stops working after about 1 hour

### ISSUE THREAD

**Issue by gustavoagp** [cagnulein/qdomyos-zwift#728]
**Describe the bug**
After roughly an hour, either autoresistance stops working and resistance falls to minimum or it bounces from valid value to minimum

**To Reproduce**
It happens randomly after about an hour

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
[debug-Fri_Mar_11_08_24_34_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8234438/debug-Fri_Mar_11_08_24_34_2022.log)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13
 - OS: [e.g. iOS8.1] iOS 15.3.1
Zwift runs on Apple TV

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks! i will check this tomorrow

**Comment by cagnulein** [comment]
Hi @gustavoagp the problem is about that you have the "training program random" setting enabled. Turn it off and it will work. Let me know

P.S. This is the first issue solved using Oculus Quest and Immersed app :)

**Comment by gustavoagp** [comment]
Hello Roberto,

 

Thanks for the update! I will change the param, test it and get back to you.

 

Grazie!

**Comment by cagnulein** [comment]
@gustavoagp any news?

**Comment by gustavoagp** [comment]
> @gustavoagp any news?

Sorry Roberto, the problem was indeed the parameter for "training program random". It is working now like a charm. AS always, Grazie Mille!!! I am closing the issue now

**Comment by cagnulein** [comment]
great! thanks!
