### ISSUE TITLE
[REQ] Have a peloton charts with target and converted to Peloton if not using Peleton Bike

### ISSUE THREAD

**Issue by Toasterme** [cagnulein/qdomyos-zwift#735]
Have a peloton charts with target and converted to Peloton if not using Peleton Bike.
So i can see if i am getting close to the target!

Thanks !

**Comment by janabouc** [comment]
My charts look very similar, with the resistance way above the peloton target line. Will this be helpful for me too with my Assioma Power Meter pedals and manual resistance?

**Comment by cagnulein** [comment]
Yes @janabouc it could be helpful too
I'm only wondering if I should create a new chart or change this one. I don't want to break the legacy...

**Comment by cagnulein** [comment]
ok i guess the best way to achieve this is to create a new chart called "peloton resistance vs target peloton resistance" in order to don't break the legacy. What do you think @janabouc @Toasterme ?

**Comment by janabouc** [comment]
Makes sense to me to add a new chart that is more accurate for bikes with calculated resistance.

**Comment by cagnulein** [comment]
done @Toasterme ! are you on ios or android?

**Comment by Toasterme** [comment]
That was quick :)
I’m iOS , can I test it with tesflight ? Or any other way

**Comment by cagnulein** [comment]
yes send me an email to roberto.viola83@gmail.com indicating this ticket and i will send you the testflight version!

**Comment by cagnulein** [comment]
I didn't have the time today to build it, I will do tomorrow
Have a nice day :)

**Comment by janabouc** [comment]
I see them and they're great!

**Comment by cagnulein** [comment]
Thanks @janabouc , I'm closing this one @Toasterme 
If you need anything else feel free to reopen it
