### ISSUE TITLE
Constant disconnects and apple watch heart rate not working

### ISSUE THREAD

**Issue by JohnR744** [cagnulein/qdomyos-zwift#736]
Son has purchased qz domyos on to his iphone X. Linked to Ipad and Zwift recognises his phone as the source for treadmill, HR and cadence.

When he starts to run, the treadmill will suddenly stop and the bluetooth connection icon will flash once to show the connection has dropped out..

Included debug log.

Works perfectly for me however I had to send you my logs for apple watch heart rate not showing, which you fixed for me after seeing the debug log.
**To Reproduce**

**Expected behavior**

**Screenshots**

[debug-Mon_Mar_21_13_44_19_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8315986/debug-Mon_Mar_21_13_44_19_2022.log)

**Smartphone (please complete the following information):**
 - Device: Iphone X

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@JohnR744 in this log i don't see at all the HR. Are you sure you opened the qz app on the watch? Did you see the HR there?
About your son's issue, i need the debug log from him in order to understand his issue
Thanks

**Comment by JohnR744** [comment]
Hi there, 

Yeah he has the QZ app opened in his watch and it shows his HR and cadence on the watch screen. 
I’ve ensured all permissions are enabled on phone and watch. 
The debug log is from his phone, I just got him to send out to me as I have created a GitHub account. I’ll get him to send create his own GitHub and send it to you himself. 

Thanks again.

**Comment by cagnulein** [comment]
Hah ok @JohnR744 sorry I thought it was from you. Let me check this again so

**Comment by JohnR744** [comment]
Hi, 
So turning off virtual device means that Zwift can’t see the iPhone when it comes to pairing. Just stays on searching with nothing showing.

**Comment by cagnulein** [comment]
Yes it's normal @JohnR744 with that setting off we're turning off the bridge to zwift. My test about this is checking if the connection is stable to the treadmill. Does it keep disconnecting from the treadmill with this off?

**Comment by JohnR744** [comment]
So it’s just ran perfectly with no disconnects with virtual device disabled with it recording speed and incline changes.

**Comment by hoveeman** [comment]
@JohnR744 You can see all my testing I did in the ticket @cagnulein mentioned above. It does seem like certain iOS devices work with the virtual device enabled and some don't. I had purchased the new iPad 9th gen to use for QZ and multiple other things, but its Bluetooth unfortunately had this issue. I eventually gave up and returned the iPad. I'm still using an older iPad that works with the virtual device capability. Let me know if I can help in anyway.

**Comment by JohnR744** [comment]
Nothing to report I’m afraid. No change in circumstances which is a shame as it was my son and I talked him into buying the app as it was working so well for me. 
He’s decided not to use Zwift anymore so just close this down please.

**Comment by cagnulein** [comment]
ok if he wants to try again let me know

**Comment by JohnR744** [comment]
Hi,

Thanks for letting me know. I’m running an iPad 8 with my iPhone 12 and it works flawlessly. So much so I got my son to purchase the QZ app onto his iPhone X and set to a profile on my iPad. 

He is getting constant disconnects which has frustrated him so much he’s given up on it and I feel bad for trying to get him into it. 

The only difference in our setups is the iPhone model, with his being older. 

Seems a shame but hopefully not insurmountable. 

Thanks for reaching out though. 

John.

**Comment by cagnulein** [comment]
ok @JohnR744 i don't know why I received this only today (my last message was from Apr 5 :) ) anyway I added a new feature to send HR to Ipad if your son wants to try #957
