### ISSUE TITLE
If you have time Nautilus B628 support please

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#738]
This has Bluetooth and electronic resistance. It only connects to Bowflex Explore the World (which used to be RideSocial, and was very good).

![Screenshot_20220319_135819_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630896-02993f35-7023-4f0e-bb28-f1c3d54d5bdc.jpg)![Screenshot_20220319_135825_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630908-340714fa-ec69-4c19-b5ff-9db4185b9fcb.jpg)![Screenshot_20220319_135830_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630925-406377fb-de43-4044-b086-2ebfc18d12d2.jpg)![Screenshot_20220319_135836_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630936-9f8893de-96aa-40b0-807f-28503611cc15.jpg)![Screenshot_20220319_135842_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630945-314c8a94-6a33-4ce7-87e9-64100f5a0ed1.jpg)![Screenshot_20220319_135848_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630970-2bf42e75-f769-4198-b58b-234953bf06db.jpg)![Screenshot_20220319_135855_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159630987-25ac2c29-900a-4645-9e24-39799a1f3643.jpg)![Screenshot_20220319_135900_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159631002-25f61635-bbfc-4be1-a462-b6ae2e5e2e30.jpg)![Screenshot_20220319_135907_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159631016-f18f9fc0-e699-44ab-8eeb-c13cffbe80f5.jpg)![Screenshot_20220319_135916_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159631042-ad82801f-1fc0-408b-a6c0-1f9bb7d4dbb8.jpg)![Screenshot_20220319_135921_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159631053-86b56c27-8bc7-41b2-82aa-95d83f2babde.jpg)![Screenshot_20220319_135926_no.nordicsemi.android.mcp.jpg](https://user-images.githubusercontent.com/4342400/159631060-599d4197-a63e-4d8f-ad6b-3f7b48561285.jpg)

**Comment by cagnulein** [comment]
hi @jonathancolledge i need an hci snoof for this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

thanks

**Comment by cagnulein** [comment]
[Archive.zip](https://github.com/cagnulein/qdomyos-zwift/files/8342735/Archive.zip)
thanks, @jonathancolledge i'm checking this

**Comment by cagnulein** [comment]
do you have also a fit file releated to this?

**Comment by jonathancolledge** [comment]
Oh dear, no fit file, the app is very basic and doesn't save anything. Cadence was fairly low, power a bit higher, and speed around 25 kph, if that helps.

**Comment by cagnulein** [comment]
cadence 70 more or less?

**Comment by cagnulein** [comment]
it seems to send only 3 metrics:
1) it's quite stable to 11000, so it could be 111W maybe?
2) it's quite stable to 1700, 17km/h? maybe the speed?
3) a valute that is around 44, could be the cadence

**Comment by jonathancolledge** [comment]
OK that looks right except 17 must be mph.

**Comment by jonathancolledge** [comment]
Yes! Until I manually increased it with the console to 8 at the very end.

**Comment by jonathancolledge** [comment]
Oops, yes resistance at 4 all the time. Sorry I didn't put it up to 8 for that one.

**Comment by cagnulein** [comment]
@jonathancolledge No problem. The code is ready, I will push it tomorrow. Will you be able to build it in the raspberry?

**Comment by jonathancolledge** [comment]
Thank you! Yes, I can do on Pi.

**Comment by cagnulein** [comment]
@jonathancolledge thank you so much for the coffes!

**Comment by cagnulein** [comment]
done @jonathancolledge , you can pull it. Just one note: since the bike doesn't send actually the cadence (i don't know why!?) i calculated it deriving the speed. Let me know if it could be ok.

**Comment by jonathancolledge** [comment]
Thank you! It works. Cadence is spot on 😊

**Comment by cagnulein** [comment]
Wow! This was fast!
