### ISSUE TITLE
Dropped packets from Neo?

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#742]
Is it plausible that QZ could be dropping packets from my Tacx Neo? I am finding that when I sharply increase power it can take maybe 2-3 seconds for this to be reflected in Zwift, which can lead to being unable to cover breaks in races, or getting dropped on rolling terrain in fast-paced group rides. I've experienced this with two different Android phones and a Pi Zero - suddenly jump on pedals and power reading remains unchanged for a couple of beats - but I've never seen it happen with a unbridged connection from the Neo straight to Zwift.

**Comment by cagnulein** [comment]
no it's impossible that qz lost packets from the neo, but actually i'm sending value to zwift every seconds. if you want you can easily change this in the raspberry. you have just to trim the virtual bike timer in the constructors. default is 1s
let me know

**Comment by smulrine** [comment]
I ran a BLE sniffer for a couple of minutes and the shortest interval between Neo broadcasts was 116ms, so in virtualbike.cpp I changed bikeTimer.start(1s) to bikeTimer.start(100). However it would crash quite a lot. Yesterday I changed bikeTimer.start(100) to bikeTimer.start(250), ran a git pull to update the code, and recompiled, then I was able to complete a 40-minute group ride without issues - not sure if it was the change from 100 to 250 or the update which (appears to have) solved the crashing issue. I probably still need to test it in a race to see how responsive it is to sudden increases in power.

**Comment by cagnulein** [comment]
maybe the 100 runs to a crash due to a collision. let me know how it will go, thanks

**Comment by smulrine** [comment]
I tried a few things to improve stability - make qz start only after the Bluetooth service, restart it again after 15 or 30 seconds, upgrade Bluez to 5.63, keep wifi power management enabled - and thought I had it working OK, then it got stuck at 240W about 8 minutes into a ride this afternoon. I'm not convinced the problem isn't actually with Bluetooth on the Pi Zero W so I will try building it on a Pi 4 when I get the chance. (Of course I would rather have had it working on the Zero because I can run that off a battery.)

**Comment by cagnulein** [comment]
Did you try to disable Wi-Fi on the pi0?

**Comment by smulrine** [comment]
No, I still need some way into it if I want to restart the service (I am running it headless using "-platform minimal") and USB networking is too much of a pain. It occurred to me that I can still try buster instead of bullseye so I will give that a go tomorrow.

**Comment by cagnulein** [comment]
i said so because i remember that i had a similar issue on my pi0 unless i disabled wifi 
But i tested this 1 year ago

**Comment by smulrine** [comment]
I disabled wifi and it seemed OK in a couple of very short test runs today, although for some reason I still appear to need "(sleep 30; systemctl restart qz) &" in rc.local to get it to connect to Zwift reliably - might have something to do with service startup order.

**Comment by cagnulein** [comment]
@smulrine any news? can we close this?

**Comment by cagnulein** [comment]
@smulrine thanks! i'm closing this one, feel free to reopen or submit patches if you have something! thanks
