### ISSUE TITLE
Cadence shows 0

### ISSUE THREAD

**Issue by nicholas720** [cagnulein/qdomyos-zwift#743]
**Describe the bug**
Cadence shows 0, all other fields (HR, Resistance, etc) are fine.  From Echelon Connect Prime, QZ ios app, Garmin FR 245 music HR monitor.  It worked fine before, don't know what happened suddenly to show zero.
Cadence shows on Echelon app fine.

**To Reproduce**
1. Open QZ
2. Start pedaling Echelon
3. All fields show, cadence shows zero.

**Expected behavior**
Cadence has always shown the correct figure.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Version 15.2.1

**Smartphone (please complete the
[debug-Sun_Mar_27_14_33_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8358445/debug-Sun_Mar_27_14_33_50_2022.log)
 following information):**
 - Device: iphone 12
 - OS: ios 15.2.1
 - Version qz 2.9.47

**Append a debug log**

 Follow this guide []([](https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F))
  
  
**Additional context**
[debug-Sun_Mar_27_14_33_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8358446/debug-Sun_Mar_27_14_33_50_2022.log)

**Comment by cagnulein** [comment]
@nicholas720 i checked the log and I confirm that I see cadence too on the log, so the bluetooth connection is fine. So your issue is that you don't see cadence on your tile? Could you post here a screenshot?

**Comment by nicholas720** [comment]
Yes cadence is at zero on the 
![IMG_2606](https://user-images.githubusercontent.com/7875489/160481107-2b619ddb-6932-468e-931d-d0b78ecf65b6.PNG)
tile

**Comment by cagnulein** [comment]
hah ok not the cadence, the target cadence! That one comes from the peloton workout. Do you see the popup in QZ when it starts the workout on peloton?
#744

**Comment by nicholas720** [comment]
Ya I'm sorry - I'm an idiot - it's been so long since I've ridden I forgot the cadence was in the upper left. Ya I know it comes from the peloton workout - I guess my mind just blanked!  Sorry again :)

**Comment by cagnulein** [comment]
@nicholas720 no problem :) have a nice day!
