### ISSUE TITLE
[BUG] Zwift, low cadence to power ratio

### ISSUE THREAD

**Issue by greghesp** [cagnulein/qdomyos-zwift#746]
**Describe the bug**

Zwift Resistance offset is set to 20, however in Zwift, it's impossible for me to get up a 13% incline slope, no matter how fast I pedal.  Flats seem to be OK, however inclines are impossible.  I'm also not sure auto resistance is working

![image](https://user-images.githubusercontent.com/768908/160786057-fceda403-a27e-41c4-bbda-697cea4c7943.png)

In the video in the thread below, I am outputting 63W at 103rpm on a 13% incline, however I can't get over 2kph which eventually grinds to a half as the incline increases

https://www.facebook.com/groups/149984563348738/posts/386960792984446/?comment_id=386962712984254&reply_comment_id=387413752939150&notif_id=1648505965926288&notif_t=group_comment_mention

**To Reproduce**
Set Zwift Resistance offset is set to 20, load Zwift and cycle

**Screenshots**
![IMG_0001](https://user-images.githubusercontent.com/768908/160791890-ca1114a0-67c3-4c00-8f26-82b8b9f29070.PNG)

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro, iPad
 - OS: Android (Zwift on iPad)
 - Version: Android 12, iOS 15.4

**Append a debug log**
  
[debug-Wed_Mar_30_07_44_06_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8378806/debug-Wed_Mar_30_07_44_06_2022.log)

  
**Additional context**

**Comment by cagnulein** [comment]
@greghesp hi, i checked your log and the first issue is that you "Zwift Force Resistance" put to OFF. You have to turn it on in order to have auto resistance. Let me know

**Comment by greghesp** [comment]
> @greghesp hi, i checked your log and the first issue is that you "Zwift Force Resistance" put to OFF. You have to turn it on in order to have auto resistance. Let me know

Thanks, i will check and try again. If the resistance is too low, that wouldn't necessarily stop me from going up the incline though would it

**Comment by cagnulein** [comment]
@greghesp once autoresistance will work you can change the actual resistance with the gear tile

**Comment by cagnulein** [comment]
great! @greghesp
