### ISSUE TITLE
[BUG] cadence drops to zero every few sec (debug log now attached)

### ISSUE THREAD

**Issue by Wavescrash** [cagnulein/qdomyos-zwift#752]
**Describe the bug**
While riding the cadence displayed and recorded on qz app drops to zero every few seconds despite steady pedaling. 

**To Reproduce**
Turn on bike computer. Press start on qz Apple watch7 heart rate app. Start qz on iPhone 11. Start peloton on ipad mini (casting to TV). Cadence and HR are detected in peloton via qz. Start ride. Everything seems to work Ok except for cadence dropping out problem (See graph). Does this impact resistance or watt calculations?

**Expected behavior**
Cadence remains steady when pedaling steady. 

**Screenshots**
![image](https://user-images.githubusercontent.com/102754579/161113275-e3053f20-95ae-452f-9cff-5879c15d3f60.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.3.1 (19D52)

[debug-Thu_Mar_31_12_26_04_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8391815/debug-Thu_Mar_31_12_26_04_2022.log)

  
**Additional context**

**Comment by Wavescrash** [comment]
[debug-Thu_Mar_31_12_26_04_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8391807/debug-Thu_Mar_31_12_26_04_2022.log)

**Comment by Wavescrash** [comment]
Is that the setting that says "Cycling Cadence Sensor (Peloton compatibility)"?

**Comment by Wavescrash** [comment]
Because under Accessories -> Cadence Sensor Options -> "Cadence Sensor as a Bike" is disabled already

**Comment by cagnulein** [comment]
@Wavescrash not "cadence sensor as a bike", just "cadence sensor" ;)

**Comment by Wavescrash** [comment]
Ok  thanks. I got it! I will give it a test and let you know.

**Comment by Wavescrash** [comment]
Thank you for all your prompt help!! It looks like it is working now without any cadence drops. Truly appreciate it!

**Comment by cagnulein** [comment]
Great!
