### ISSUE TITLE
[BUG] resistance is too low on zwift

### ISSUE THREAD

**Issue by Robski-Martin** [cagnulein/qdomyos-zwift#755]
[debug-Sat_Apr_2_10_39_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8402493/debug-Sat_Apr_2_10_39_30_2022.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]iPhone Xr
 - OS: [e.g. iOS8.1] 15.3.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
As I said on messenger the issue is just the trainer difficulty on zwift. Let me know if you have any other issues
