### ISSUE TITLE
Speed/Cadence/etc not displaying for MEKBELT SM36

### ISSUE THREAD

**Issue by voyagertodarkmatter** [cagnulein/qdomyos-zwift#758]
Verified hardware by connecting to Zwift app. Speed and cadence display. Bike is a rebadge/clone of the YESOUL S3. The Bluetooth wouldn’t auto select, but I suspect that’s because there are a lot of other Bluetooth devices around. (Unable to shut them off-belong to neighbors)
I manually selected the device in the settings. Rebooted device multiple times. Reinstalled app. Always started the app after I started pedaling to ensure Bluetooth is on on the bike.

let me know what else I can test/try.

thanks!

[debug-Tue_Apr_5_13_46_24_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8421027/debug-Tue_Apr_5_13_46_24_2022.log)

**Comment by cagnulein** [comment]
@voyagertodarkmatter i found out that i was already implemented it in the beta #730 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and i will add you to the beta. Thanks

**Comment by cagnulein** [comment]
@voyagertodarkmatter are you still interested in this?
