### ISSUE TITLE
Echeolon bike screen (EX5s) will not load software after recent firmware or software update

### ISSUE THREAD

**Issue by nskinner07** [cagnulein/qdomyos-zwift#762]
Echelon has changed the way the software on the bike screen interacts with the bluetooth connection on the bike with the lastest update. It now wants to connect to the bike prior to loading the software. If QZ is open and already connected to the bike, the Echelon software on the bike will not load correctly. The user can not run classes on the echelon bike screen. The software works correctly if the bike is not connected to QZ, and connects to the bike itself (intended use). Issue noticed/started for the user 03APR22. User does not use the bike every day.

- Echelon bike (EX5s) is connected to QZ on iPhone 6s Plus (ios 15.4)
- Echelon software (on attached screen) starts to load, asks to connect to bike.
- User chooses bike (says bike serial (says available bike ending in **399**))
- Software says bike is connected but quickly disconnects and cycles through process again.... or never connects; it just keeps trying to attach.

Have tried reproducing/ relaoding software by:

- unplugging/re-plugging in bike
- turning bike off/on
- resetting screen software

Software USED to load and then attach to bike when classes were started.
If QZ in not attached, the bike software will ask to connect to bike (says available bike ending in **397**)
- will connect properly and load software correctly. 
Note difference in "available" bike serial codes.
@cagnulein 
![277821243_1188261208649463_4284763632365189515_n](https://user-images.githubusercontent.com/103256662/162431807-506f77fa-a894-4108-a624-5aec36d9ed02.jpg)
![277597120_508358384108868_6425943506439142222_n](https://user-images.githubusercontent.com/103256662/162431809-1459dafd-f2f5-46aa-a8f5-17f2ee1fa316.jpg)

https://user-images.githubusercontent.com/103256662/162431811-7297b2bf-e64d-4008-973b-dc8ec6551310.mp4

https://user-images.githubusercontent.com/103256662/162431819-b4a1ac72-6977-41a6-aabe-faf1416670c5.mp4

[debug-Thu_Apr_7_20_49_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8451603/debug-Thu_Apr_7_20_49_44_2022.log)
[debug-Thu_Apr_7_20_42_17_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8451604/debug-Thu_Apr_7_20_42_17_2022.log)
[debug-Thu_Apr_7_20_46_32_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8451606/debug-Thu_Apr_7_20_46_32_2022.log)
[debug-Thu_Apr_7_20_44_31_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8451608/debug-Thu_Apr_7_20_44_31_2022.log)
[debug-Thu_Apr_7_20_59_59_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8451609/debug-Thu_Apr_7_20_59_59_2022.log)

**Comment by cagnulein** [comment]
thanks @nskinner07 i'm checking it

**Comment by nskinner07** [comment]
![Screenshot 2022-04-08 at 6 08 55 AM (1)](https://user-images.githubusercontent.com/103256662/162434183-54411951-f7a9-4adf-a11f-688b06b69058.png)
I don't know what "version" the phone is.
Thanks!

**Comment by nskinner07** [comment]
thanks!

**Comment by cagnulein** [comment]
@nskinner07 I asked the support of @ptgraham in the #695 that maybe he could provide a fresh log from an android device about the new logic of the Echelon app if needed

**Comment by cagnulein** [comment]
I write here my ideas about this in order to don't forget waiting for @ptgraham feedback
- the f0a1 frame could be copied from your ex5. I guess it has a newer firmware verson.
- i'm not actually sending the frame of the resistance after the first f0a1, instead your real bike does.

**Comment by cagnulein** [comment]
@nskinner07 I did some changes regarding this looking your log. I will release a new one this evening. 
Could you send me an email to roberto.viola83 at gmail.com indicating this ticket in order to remember me to send the new one? Thanks

**Comment by nskinner07** [comment]
email remider sent. I'm off for the day - so I'll leave you with this for now.

**Comment by ptgraham** [comment]
@nskinner07 what app version and bike firmware are you using? My app version doesn't connect to the bike right away (waits until you start a class or freestyle).  When I try to use QZ with the ex-5s screen running the app I'm unable to connect the virtual bike.  So, I've been using a work around - QZ on phone, echeolon app on ipad casting to ex-5s using screen mirroring.  Not ideal, but works.

I'd love to connect directly (run echelon app on my ex-5s) but thought it wasn't possible.

@cagnulein I'm happy to test out solutions and provide logs, let me know.

On my ex-5s I have app 2.2..1.10. 104 (and its telling me to update)
bike firmware 51.12.03

**Comment by ptgraham** [comment]
note, the connect/disconnect loop was similar in my case, but happened after a class started.  My connect/disconnect loop would also interfere with the QZ app connection (bike would beep saying it had a new connection).

It seems they changed the software to connect on app loading, but I suspect its the same issue just pushed forward.

**Comment by cagnulein** [comment]
@ptgraham i thought that we fixed it when we closed the ticket last time, didn't?
i'm building a new one and we will try

**Comment by cagnulein** [comment]
@ptgraham @nskinner07 version sent! let me know!

**Comment by nskinner07** [comment]
@ptgraham
I'm on Firmware V. 51.12.03, Hardware V. 11.0
Screen app V. 2.3.0.72.112
Tablet Firmware V. Z33PM-JST-0-9.0-21.5-SW0.2-3V20210429

**Comment by nskinner07** [comment]
@cagnulein fixed! It's connecting fabulously! -Thanks

**Comment by cagnulein** [comment]
@ptgraham Same to you?

**Comment by ptgraham** [comment]
@cagnulein No luck.  When the echelon app connects to the virtual (QZ) device it seems to connect, then times out when it says checking firmware version.

Firmware V. 51.12.03, Hardware V. 11.0
Screen app V. 2.3.0.80.113
Tablet Firmware V. Z33P-JST-180-9.0-21.5-SW3.0-20200923

**Comment by cagnulein** [comment]
@ptgraham can you share a debug log?

**Comment by ptgraham** [comment]
@cagnulein debug log from iphone trying to connect to echelon ex-5s.  It says it connects, but then hangs

[debug-Mon-Apr-11-06-01-08-2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8463070/debug-Mon-Apr-11-06-01-08-2022.log)

**Comment by cagnulein** [comment]
@ptgraham i don't see any attempt of connection from the Echelon APP to QZ in this log. Maybe it could be a cache issue on the echelon device? Try to do a network reset and reboot it. Let me know

**Comment by ptgraham** [comment]
@cagnulein I don't seem to be able to get the virtual bike to connect to the Echelon app on the Ex5s screen.  I tried clearing caches, and even did a factory reset and the bike never completes the connection.  Factory reset required the app to update, and it updated to the same version V. 2.3.0.80.113.  When I select the virtual bike serial number the app says its connected, but then hangs and eventually offers me to choose the bike to connect again.  

I was able to get it to connect to the android version on my tablet. app version 217 (2.2.3.2) in this debug log:
[debug-Mon-Apr-11-21-49-23-2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8468902/debug-Mon-Apr-11-21-49-23-2022.log)

**Comment by cagnulein** [comment]
@ptgraham so strange if it works for @nskinner07 
maybe you guys you can share a video of your exaclty procedure so we can match them. Maybe there is a little different in your process. For QZ side, android tablet or bike tablet are the same, so it has to work on both. Let me know

**Comment by ptgraham** [comment]
@cagnulein here's a video of of me trying to connect.
https://photos.app.goo.gl/6fjBtGrgwkM9yLBb6

start with app open on my phone, bike and echelon monitor are unplugged
plug in power, bike instantly connects to qz, tablet boots op
when the tablet boots up it asks to connect to the virtual bike, says it connects, but then does nothing and eventually offers to connect again.

**Comment by nskinner07** [comment]
@cagnulein, he doesn't use the echelon classes, and I think he loads from his watch/iPhone. I'll ask if he has beta there. He's a Zwift guy😃
We have TOO many devices to keep it all straight.

**Comment by nskinner07** [comment]
Hi Roberto,
His email is ***@***.***

**Comment by cagnulein** [comment]
@nskinner07 github blocks the email you have to separate it like roberto.viola83 at gmail.com

**Comment by ptgraham** [comment]
> @nskinner07 thanks. The version is the production one. Send me an email from your husband so i can send the beta to him too @ptgraham Do you notice something different from your video?

The only difference I see is that after the device connected notification at the bottom mine does nothing, waits then offers to connect again.

Trying to reduce variables... could I try on another device?  I can install on my wife's ipad, email is kate.p.graham at gmail.com for test flight

**Comment by cagnulein** [comment]
sent!


Il giorno mer 13 apr 2022 alle ore 13:57 ptgraham ***@***.***>
ha scritto:

**Comment by nskinner07** [comment]
Could there be a difference in Android vs. iOS?

**Comment by ptgraham** [comment]
@cagnulein Success!
Iphone SE2 connected properly.  Oddly, the virtual device showed as ECHEX-5S (no 113399)
Did not work with ipad
pervious attempts with iphone 8 were not successful.

**Comment by cagnulein** [comment]
strange about the advertisment name...i have to think about. At least you have a working scenario now :)

**Comment by cagnulein** [comment]
@ptgraham this is a good call. Seems that with the device it doesn't work, you have a limit on the advertisment bytes! That's explain the different name (toggling the Heart Rate service outside FTMS the advertisment data will increase/decrease). @hoveeman maybe it's releated to the #708 ?

**Comment by ptgraham** [comment]
@cagnulein just to clarify, the advertisement name changes on all both devices when I switch "Heart Rate service outside FTMS".  When its on I get the device ECHEX-5s-113399
Off I get ECHEX-5s (both devices)

Also, getting another notification from the echelon app on Echelon 5s display tablet to update.  Worried that it'll break again if I accept.

**Comment by cagnulein** [comment]
@ptgraham Hah ok, so we're overloading the advertisement room if you turn it off. So maybe I can force it to true when virtual echelon is on, what do you think?
For the update, no worries, I will follow you if you want to update it

**Comment by nskinner07** [comment]
@ptgraham, every time I get on it updates. I think I've done 4 since Roberto fixed the issue the first time. It should be ok.

**Comment by ptgraham** [comment]
Thanks, did the update and no noticeable changes
Still works with iphone SE2
does not work with iphone 8 or ipad mini 4

**Comment by cagnulein** [comment]
@ptgraham for iphone 8 or ipad mini 4 did you try to reset the network settings?

**Comment by cagnulein** [comment]
@ptgraham did you solve it?

**Comment by ptgraham** [comment]
I'm able to run using the Iphone SE2, so I'm good to close this.

Still not working for iphone 8 or ipad mini (even resetting network
settings)

**Comment by cagnulein** [comment]
ok @ptgraham thanks, feel free to reopen in case you need it!
