### ISSUE TITLE
[BUG] Training programs with "Ramp" sections show Time Remaining as 1 second

### ISSUE THREAD

**Issue by rjbutler** [cagnulein/qdomyos-zwift#763]
**Describe the bug**
When using a ZWO with a 5 minute ramp from power 0.5 to 0.7, the time remaining tile shows 1 second remaining for the entire ramp period.

**To Reproduce**
1. Load the attached ZWO file as a training program
2. The ramp is the first section, so the issue occurs immediately.
3. There is also a ramp at the end that I think prevents QZ from recognizing the end of the program, but I haven't confirmed this yet.

**Expected behavior**
Time remaining should show the time remaining in the Ramp up/down

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 15.4.1
 - Version 2.10 - personal build with no changes except for SS2K/Schwinn 

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Fri_Apr_8_17_24_44_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/8457589/debug-Fri_Apr_8_17_24_44_2022.log.zip)
[HIIT For Weight Loss.zwo.zip](https://github.com/cagnulein/qdomyos-zwift/files/8457593/HIIT.For.Weight.Loss.zwo.zip)

**Comment by cagnulein** [comment]
@rjbutler done! Could you please build and verify that it's what you need? I also did the same fix to the elapsed time for row tile

**Comment by rjbutler** [comment]
@cagnulein The ramp time works, but the other stages don't seem right, and at the end of the workout it repeated the final ramp

**Comment by cagnulein** [comment]
mmmm ok i will try again. thanks for the feedback

**Comment by cagnulein** [comment]
@rjbutler i totally did it wrong! i'm trying to fixing it ;)

**Comment by cagnulein** [comment]
@rjbutler fixed! if you want you can build it or i will build this in the next days

**Comment by cagnulein** [comment]
@rjbutler version sent!

**Comment by rjbutler** [comment]
@cagnulein it worked perfectly!
