### ISSUE TITLE
[REQ] include bug report in email with charts

### ISSUE THREAD

**Issue by janabouc** [cagnulein/qdomyos-zwift#764]
**Is your feature request related to a problem? Please describe.**

It's really hard to figure out which is the right bug report to send you when I've done several tests.

**Describe the solution you'd like**

Include the bug report with each email. It would be so much easier to select correct one than scrolling through multiple ones with only time stamps if you don't recall the times you finished or started each class. 

**Describe alternatives you've considered**

**Additional context**

**Comment by cagnulein** [comment]
I already did that but the server mail was rejecting it thinking it's a virus. So I can't do it, or maybe I should upload it somewhere else but it could be wrong for privacy. So I guess it's better to leave it in the device. Thanks

**Comment by janabouc** [comment]
Ok. I understand.

**Comment by cagnulein** [comment]
#405
