### ISSUE TITLE
[BUG]  'delete all' files from QZ folder returns error message

### ISSUE THREAD

**Issue by janabouc** [cagnulein/qdomyos-zwift#765]
**Describe the bug**
I want to delete all 5000 QZ bug, fit and image files from QZ folder in iPhone Files app but get error message. (See screen capture video). 

**To Reproduce**

A. Quit QZ
1. Go to QZ folder in Files app
2. Click on Select
3. Click on Select All
4. Deselect Settings and Profile Folders
3. Click on trash can
4. See error message "The operation cannot be completed. Cannot connect to helper application"

**Expected behavior**

Files are deleted

**Screenshots**

https://user-images.githubusercontent.com/60453297/162628788-8d895f31-7c33-42cb-96ed-37cf069daaec.MOV

![image](https://user-images.githubusercontent.com/60453297/162628885-fd438fc3-4f5e-4a26-862c-a693f2e3efcf.jpeg)

**Smartphone (please complete the following information):**
 - Device: iphone XS Max
 - OS: 15.3.1
 - Version 2.10.62
  
**Additional context**
All of the QZ fit files show the icon for RunGap. I contacted apple support and they referred me back to you. 
![image](https://user-images.githubusercontent.com/60453297/162628845-b95b1ac5-1788-4cfe-9def-eabc1843ce09.jpeg)

**Comment by cagnulein** [comment]
@janabouc You can use the clear button in the end of the experimental settings. Let me know

**Comment by janabouc** [comment]
Will it delete my settings and profiles too or just the other files?

**Comment by janabouc** [comment]
It worked!  Fantastic! I duplicated and moved the settings and profiles folders just in case but it left them intact so all is well. One more excellent feature to explain better in guide!

**Comment by janabouc** [comment]
I just updated Guide to add what's in bold below: "Clear History Buttons: Clears all the QZ logs, QZ .fit files and QZ images from the user’s device **while leaving in place your Profiles and Settings folders.**"

**Comment by cagnulein** [comment]
great! Thanks!
