### ISSUE TITLE
Unable to connect App to Wahoo Kickr Bike

### ISSUE THREAD

**Issue by llanellijack** [cagnulein/qdomyos-zwift#770]
[debug-Wed_Apr_13_15_30_57_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8482326/debug-Wed_Apr_13_15_30_57_2022.log)

The App will 'find' the bike but will not connect. No tiles are showing
![490B1A6B-B618-4CE4-A3B9-9D9A3839543B](https://user-images.githubusercontent.com/103586595/163205856-8e94f005-560f-490d-a759-bf10f9d7e08d.jpeg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Iphone 13 Pro
 - OS: 15.4
 - Version .1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
@llanellijack got your issue now. Your bike is advertising in a different way than the other wahoo devices. Could you please attach here a nrfconnect screenshot about it? Thanks

**Comment by llanellijack** [comment]
[text.txt](https://github.com/cagnulein/qdomyos-zwift/files/8482486/text.txt)

**Comment by llanellijack** [comment]
![44E91AE5-7B31-4882-A435-76A292BA8274](https://user-images.githubusercontent.com/103586595/163210890-69ab5a93-2f4f-427e-9c82-fdfcb3dc919f.jpeg)

**Comment by cagnulein** [comment]
@llanellijack thanks i will add this tomorrow!

**Comment by llanellijack** [comment]
Thank you !! 👌👍

**Comment by cagnulein** [comment]
done, please send me an email to roberto.viola83 at gmail.com indicating this ticket and that you are on  iOS. Thanks

**Comment by llanellijack** [comment]
App now connects to my Wahoo Kickr Bike ! Thank you Roberto ! 👍👍

**Comment by cagnulein** [comment]
Great! Thanks for the feedback! If you have any issues I'm here!
