### ISSUE TITLE
[BUG] Connect Taurus z9 pro / iconsole

### ISSUE THREAD

**Issue by word-up81** [cagnulein/qdomyos-zwift#771]
**Describe the bug**
ios App crashes when connecting to Taurus z9 pro (iconsole bike; acoording to sticker on the console, the iconsole is from 2017)

**To Reproduce**
1. start the app
2. enable "Toorx/iConsole Bike"
3. close app to save settings
4. start app again
5. crashes immediately after connecting to iconsole

**Expected behavior**
not crash

**Screenshots**

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
 - Device: iphone 12
 - OS: ios
 - Version: 15.3.1

**Append a debug log**

  
  
**Additional context**
[debug-Wed_Apr_13_21_39_14_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8484269/debug-Wed_Apr_13_21_39_14_2022.log)

**Comment by cagnulein** [comment]
@word-up81 i guess i already fixed this in the beta, please send me an email to roberto.viola83 at gmail.com indicating this ticket and that you are on iOS. Thanks

**Comment by word-up81** [comment]
@cagnulein I am interested in this, yes. But as you commented above, it was apparently already fixed in the beta and thsi version solved the issue for me. So if your question is whether I'd like to have this in the next release, then yes. Thanks

**Comment by cagnulein** [comment]
@word-up81 did you send to me an e mail to getting the beta?
