### ISSUE TITLE
PZ stats from Peloton directly

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#774]
https://www.pelobuddy.com/class-plan-body-activity-web/

**Comment by cagnulein** [comment]
#761

**Comment by cagnulein** [comment]
@grantland did you see this news? I guess we can collect Peloton PZ metrics directly from their server now! I don't have a peloton account, could you please try to check if it's possible? Thanks!

**Comment by grantland** [comment]
Oh this is cool! Yeah I can play with the API sometime later this week to see if the current endpoint returns PZ data.

If this ends up working, I'll have to finally try out PZ training!

**Comment by cagnulein** [comment]
great thanks!

**Comment by rjbutler** [comment]
@cagnulein Here's a class that seems to have the data you'd need.  I can get more examples if it looks good. 
[30m PZ Denis Morton 220413.json.zip](https://github.com/cagnulein/qdomyos-zwift/files/8508113/30m.PZ.Denis.Morton.220413.json.zip)

**Comment by cagnulein** [comment]
It's perfect @rjbutler I will implement this today!

**Comment by cagnulein** [comment]
@rjbutler If I got this right this metrics are available for new workout only, isn't it? I guess it's a good idea cloning the current hfb db in case they will remove them. So I can add them directly to qz

**Comment by rjbutler** [comment]
i can try an older workout, ill let you know

**Comment by cagnulein** [comment]
@rjbutler i already have a log from another user from a ride of the 2019 done yesterday and there is no segment_v2 in there. but it's ok since HFB is online ;)

**Comment by cagnulein** [comment]
done @rjbutler @grantland i'm building ;)
i did in a way that i'm preferring the peloton one, but if i don't found them i fallback to PZP or HFB as usual
@janabouc this could be very useful also for you ;)

**Comment by janabouc** [comment]
Does this mean you won't have to get PZ class Zone info from HFB going forward?

**Comment by cagnulein** [comment]
yes only for the old rides. i kept the hfb as a fallback

**Comment by tmills1073** [comment]
Debug from 4/13 PZ ride. No metrics.

**Comment by cagnulein** [comment]
@tmills1073 I don't see the attachment

**Comment by tmills1073** [comment]
> Debug from 4/13 PZ ride. No metrics. [debug-Tue_Apr_19_14_28_55_2022 3.log](https://github.com/cagnulein/qdomyos-zwift/files/8515699/debug-Tue_Apr_19_14_28_55_2022.3.log)

Sorry, couldnt upload a file from the ios github app.

**Comment by cagnulein** [comment]
@tmills1073 got the issue, @rjbutler with which end api did you get the json that you sent me? It's not the one that I already use right now, that's why I didn't work

**Comment by rjbutler** [comment]
/api/ride/:rideId/details

**Comment by cagnulein** [comment]
> /api/ride/:rideId/details

Thanks! I'm fixing it now!

**Comment by cagnulein** [comment]
@rjbutler @tmills1073 sent a new one! i'm going to bed right now! i hope it will work (without a peloton account i can test it directly ;) )

**Comment by tmills1073** [comment]
@cagnulein  woohoo!! Installed it, and it picked up the Pelo class and started!  I don't have time to do the workout (still working hours for me), but I will do a ride tomorrow am est and confirm.  Thanks!!

**Comment by rjbutler** [comment]
I tried it with a different PZ class and it worked well at first, then stopped tracking about 25 minutes in.  This might be the SS2K issue that pops up occasionally, not sure.
[debug-Tue_Apr_19_17_26_23_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/8518161/debug-Tue_Apr_19_17_26_23_2022.log.zip)

**Comment by cagnulein** [comment]
@tmills1073 great! let me know if you have any issues!

@rjbutler i will check the log tomorrow, thanks. today it's a travel day

**Comment by cagnulein** [comment]
i guess we can close this. Please feel free to reopen it in case of issues!
