### ISSUE TITLE
Neither bug nor feature, just help please! 

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#783]
I just tried this with 64 bit Jammy Jellyfish Raspberry Pi version from here:
https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04&architecture=server-arm64+raspi

I installed the desktop GUI as I think that way there are fewer extras than if I used the desktop version. I think! 

All seemed fine, make seemed to work, but when I try to run QZ, I get the following error:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
OK, you are root

Then I get back to the terminal prompt with nothing happening. 

This is the same error that I get on Impish Idri AMD64 Desktop version on my big computers.

I've googled this error and there are a lot of different half-solutions and no convincing real solution.

Should I just go back to my old 32 bit image!? Have you come across this? It's not a QZ problem, so I think my best solution is to go back to my working setup, but I thought I'd ask in case you'd come across it.

**Comment by cagnulein** [comment]
@jonathancolledge you need to install the qml modules

sudo apt install qml*

did you try it?

**Comment by jonathancolledge** [comment]
Amazing! Thank you, I'm glad I asked! I thought I shouldn't bother you again!

**Comment by cagnulein** [comment]
@jonathancolledge Ahah no problem at all! I had a prompt response because yesterday another user had the same issue :)
