### ISSUE TITLE
Bug report between Gfit App and Fitfiu MC-460 Tradmill

### ISSUE THREAD

**Issue by aherrang** [cagnulein/qdomyos-zwift#784]
**Describe the bug**
This is just a bug report to understand the behaviuor of the bluethood communication between Gfit App and Fitfiu MC-460 Tradmill.

**To Reproduce**
1. Go to 'Gfit App on an Andoid device
2. Register the bluethood communication on a bug report

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3
 - Version Android 5.1.1

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8547029/btsnoop_hci.log)

**Comment by cagnulein** [comment]
#778

**Comment by cagnulein** [comment]
some example:
Value: 033c0000006441 --> speed 6.0
Value: 033d0000006540 --> speed 6.1

is this right @aherrang ? if so I guess I got the issue

**Comment by cagnulein** [comment]
@aherrang done! I added a new setting called "Fitfiu MC-V460" in the RunnetT section in the new 2.10.72 version. I will build this today/tomorrow
I also covered the inclination fixed to 1 with this setting.

**Comment by aherrang** [comment]
You are a machine!!!!!

By the way, the correct model name is MC-460

Thanksssssss

Alberto Herrán González
________________________________
De: Roberto Viola ***@***.***>
Enviado: Saturday, April 23, 2022 6:19:46 PM
Para: cagnulein/qdomyos-zwift ***@***.***>
Cc: Alberto Herrán ***@***.***>; Mention ***@***.***>
Asunto: Re: [cagnulein/qdomyos-zwift] Bug report between Gfit App and Fitfiu MC-V460 Tradmill (Issue #784)


@aherrang<https://github.com/aherrang> done! I added a new setting called "Fitfiu MC-V460" in the RunnetT section in the new 2.10.72 version. I will build this today/tomorrow
I also covered the inclination fixed to 1 with this setting.

**Comment by cagnulein** [comment]
ok i'm changing the name! thanks @aherrang

**Comment by cagnulein** [comment]
[btsnoop_hci (1).log](https://github.com/cagnulein/qdomyos-zwift/files/8552056/btsnoop_hci.1.log)

**Comment by cagnulein** [comment]
@aherrang fixed! i will upload it later today!

**Comment by aherrang** [comment]
Thanks again @cagnulein

**Comment by cagnulein** [comment]
@aherrang sent, i hope it will be the good one ;)

**Comment by cagnulein** [comment]
yeah! i guess the 0.1 step issue is not working because i put a limit on the high level.
Enjoy QZ unchained now :D
Can we close this? Inclination is ok?

**Comment by aherrang** [comment]
Oh, I forgot to test the inclination. I will test it this afternoon!

**Comment by aherrang** [comment]
The inclination works perfectly as well as the plus/minus buttons and the workouts.
However, the app stopped sending the Apple Watch heart rate to Zwift (I can see the heart rate only on the corresponding tile)

**Comment by cagnulein** [comment]
@aherrang toggle the heart rate outside ftms setting, i guess you changed it by mistake;)

**Comment by aherrang** [comment]
No, I also tried with that option activated and didn’t work.
However, with the official release it works perfectly.

Alberto Herrán González
________________________________
De: Roberto Viola ***@***.***>
Enviado: Monday, April 25, 2022 11:13:24 PM
Para: cagnulein/qdomyos-zwift ***@***.***>
Cc: Alberto Herrán ***@***.***>; Mention ***@***.***>
Asunto: Re: [cagnulein/qdomyos-zwift] Bug report between Gfit App and Fitfiu MC-460 Tradmill (Issue #784)


@aherrang<https://github.com/aherrang> toggle the heart rate outside ftms setting, i guess you changed it by mistake;)

**Comment by cagnulein** [comment]
@aherrang i will check this later today

**Comment by cagnulein** [comment]
@aherrang Just tried, it works perfectly here. I suggest to do a network reset on your zwift device 

![image](https://user-images.githubusercontent.com/48216/165224305-c9a8ce8a-fa49-4e0a-a023-cdbf40695d60.png)

**Comment by aherrang** [comment]
What do you mean with a network reset?
I unpaired and paired again several times from the Zwift initial screen that you show on the screenshot.

I have these options enabled:

[Image.jpeg][Image.jpeg]
________________________________
De: Roberto Viola ***@***.***>
Enviado: Tuesday, April 26, 2022 6:53:52 AM
Para: cagnulein/qdomyos-zwift ***@***.***>
Cc: Alberto Herrán ***@***.***>; Mention ***@***.***>
Asunto: Re: [cagnulein/qdomyos-zwift] Bug report between Gfit App and Fitfiu MC-460 Tradmill (Issue #784)


@aherrang<https://github.com/aherrang> Just tried, it works perfectly here. I suggest to do a network reset on your zwift device

[image]<https://user-images.githubusercontent.com/48216/165224305-c9a8ce8a-fa49-4e0a-a023-cdbf40695d60.png>

**Comment by cagnulein** [comment]
@aherrang i mean this one https://support.apple.com/en-us/HT201415#:~:text=Reset%20your%20Network%20Settings,that%20you've%20used%20before.

**Comment by aherrang** [comment]
Oh but are correct the options that I have currently enabled on the attached pictures?

Alberto Herrán González
________________________________
De: Roberto Viola ***@***.***>
Enviado: Tuesday, April 26, 2022 8:36:15 AM
Para: cagnulein/qdomyos-zwift ***@***.***>
Cc: Alberto Herrán ***@***.***>; Mention ***@***.***>
Asunto: Re: [cagnulein/qdomyos-zwift] Bug report between Gfit App and Fitfiu MC-460 Tradmill (Issue #784)


@aherrang<https://github.com/aherrang> i mean this one https://support.apple.com/en-us/HT201415#:~:text=Reset%20your%20Network%20Settings,that%20you've%20used%20before.

**Comment by cagnulein** [comment]
@aherrang i don't see any pictures. You have to attach them in the Github website, otherwise by email they don't get through

**Comment by aherrang** [comment]
![Uploading 340FD4F8-B670-4743-BFE0-C5E07082DF0B.png…]()

**Comment by aherrang** [comment]
![BBDD5FE9-5A57-4F72-8F0C-334363EFFFC4](https://user-images.githubusercontent.com/16987996/165239198-1b829244-939a-40e5-9dc7-7e85f376029f.png)

![9A1F7BB8-27E5-4356-A116-967F0C0E501E](https://user-images.githubusercontent.com/16987996/165239241-fa03cf95-d1b2-4d47-9d3d-a4b6b687430f.png)

**Comment by cagnulein** [comment]
@aherrang iOS peloton workaround must be ON, on iOS
Enable it and let me know

**Comment by cagnulein** [comment]
@aherrang also disable the heart rate outside ftms

**Comment by aherrang** [comment]
Perfect!
