### ISSUE TITLE
Bike Weight setting

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#785]
Useful for the speed calculation when speed is based on power
@janabouc

**Comment by janabouc** [comment]
Is this a new setting where you enter the weight of the rider? Or the bike? Or is this a new addition to the way you calculate speed from a power meter? I don’t understand what this is exactly.

**Comment by cagnulein** [comment]
Since speed based on power calculation is based on power + weight, the weight of the player only could lead an incorrect value.
Since I'm doing a lot of Vzfit ride, following real path that I know in RL, i noticed that the Speed calculate with only my weight is too fast because I'm not taking in account the bike weight.
So I added this to taking in. The default value is 0 so it doesn't affect the legacy users.
I mentioned you here in order to add to the guide. This setting is in the Bike option section

**Comment by janabouc** [comment]
I just looked at VZFit and it looks fantastic! So fun! Can you really just pick any google street view map and travel along it, choosing to turn where you want to? I WANT THIS!  

What headset are you using and does it get super sweaty? 

I see the setting in the Bike Options but I don’t see a setting for entering the weight of the bike. Is there one? 

Or when you use VZFit or Zwift do you add your weight and the weight of your bike and enter that in General Options/Player Weight? Or do enter bike weight in Zwift or VZFit? 

 If you’re not concerned about accurate speed/distance in Zwift or vzfit you can just leave it off, right?

**Comment by cagnulein** [comment]
> I just looked at VZFit and it looks fantastic! So fun! Can you really just pick any google street view map and travel along it, choosing to turn where you want to? I WANT THIS!  
> 
Yeah! This is exactly what it does! Isn't it amazing? I told to @emalafeew (the developer) that he deserve more advertisements about his work!

> 
> What headset are you using and does it get super sweaty? 
> 
I started with an Oculus Quest 2 and yes at at the end it was very sweaty. I sold my Quest due to economic issue (the gas here in Italy increased of more than 200% and I can't afford so expensive gadgets) and @emalafeew built me an android version to debug it.
I told him that he should consider to sell a 2d version of it because it's as fun as the 3d version!

> 
> I see the setting in the Bike Options but I don’t see a setting for entering the weight of the bike. Is there one? 
> 
I just added in the code, I didn't push it yet
> 
>  If you’re not concerned about accurate speed/distance in Zwift or vzfit you can just leave it off, right?

Yes exactly

**Comment by janabouc** [comment]
I might buy a quest at a store with good return policy so i can try it. I know what you mean about gas prices. Over $6 a gallon here but that's more like 25% increase. I don't drive a lot so it's not affecting me as much. Long lines at the gas station too.

**Comment by janabouc** [comment]
And i totally agree--a 2-D version would actually be preferable to me. I love traveling around in street view. I used to do it a lot for finding things to draw and paint by wandering down random roads in other countries.

**Comment by cagnulein** [comment]
> I might buy a quest at a store with good return policy so i can try it. I know what you mean about gas prices. Over $6 a gallon here but that's more like 25% increase. I don't drive a lot so it's not affecting me as much. Long lines at the gas station too. 

Good move, try it! Vzfit has also a trial week.
Yeah I don't use the car either, but the gas is also used for the heater here :)

**Comment by cagnulein** [comment]
> And i totally agree--a 2-D version would actually be preferable to me. I love traveling around in street view. I used to do it a lot for finding things to draw and paint by wandering down random roads in other countries. 

Exactly, I love to ride/run on places where I haven't been or I would like to!

**Comment by janabouc** [comment]
When you say he built you an android version, do you mean in 2D? How do you use it with just android and no head set? I would love to try it too if that’s what it is (though not sure my Android tablet has the power, speed or memory to be able to run something like that.

**Comment by cagnulein** [comment]
Yes in 2D. I have to ask to @emalafeew if he can release a debug version also for you. I guess he would like to understand if the android version is suitable to be sold.
It doesn't need a powerful tablet, i have an old chinese one and it works beafutifully ;)

**Comment by janabouc** [comment]
That would be great if you don’t mind asking him. I would be happy to help with debugging too. I would really rather do it in 2D anyway, especially for running and probably cycling. I like to stay in connection with my environment, though I do want to try Holofit for rowing at some point.  I’m guessing the headset would be uncomfortable, especially with wearing glasses. Can you wear AirPods with a head set on?

**Comment by cagnulein** [comment]
> Can you wear AirPods with a head set on?

yes ;)

> That would be great if you don’t mind asking him. I

Yeah sure

**Comment by emalafeew** [comment]
@janabouc we are happy to share the 2D version on a trial basis.  This build was made a week before our latest VR release so is pretty up-to-date.  

https://drive.google.com/file/d/117sUncKApmNihoP8s8Fh0sY9XC6XVY2k/view?usp=sharing

We haven’t officially mentioned it or even setup a forum for feedback but tell me what you think at emalafeew@virzoom.com

**Comment by janabouc** [comment]
Huge thank you! Can't wait to try it.

**Comment by janabouc** [comment]
@emalafeew I had a chance to experiment a little and I think this is going to be great! I actually prefer the 2D version. I'll send an email as you requested about a problem I had and some questions. Thanks so much for this opportunity!
