### ISSUE TITLE
Build error with the last pull from the repository on Raspberry Pi?

### ISSUE THREAD

**Issue by alexrojo77** [cagnulein/qdomyos-zwift#787]
noob here so please be gentle.  trying to compile the latest version of qdomyos-zwift to run on a raspberry pi 3b as a bridge for my bike.  error popped up part way through then stopped on an Error 1.  
 
here's a copy/paste of what i see in the terminal:

`In file included from dirconmanager.h:14,
                 from virtualbike.h:29,
                 from virtualbike.cpp:1:
dirconprocessor.h: In copy constructor ‘DirconProcessorCharacteristic::DirconProcessorCharacteristic(const DirconProcessorCharacteristic&)’:
dirconprocessor.h:21:5: warning: base class ‘class QObject’ should be explicitly initialized in the copy constructor [-Wextra]
     DirconProcessorCharacteristic(const DirconProcessorCharacteristic &cp) { this->operator=(cp); }
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
virtualbike.cpp: In member function ‘void virtualbike::characteristicChanged(const QLowEnergyCharacteristic&, const QByteArray&)’:
virtualbike.cpp:708:30: error: ‘const class QByteArray’ has no member named ‘compare’
                    !newValue.compare(QByteArray::fromHex("0112b472461cf0be92403ceacea488764a2804e2"))) {
                              ^~~~~~~
virtualbike.cpp: In member function ‘void virtualbike::bikeProvider()’:
virtualbike.cpp:968:14: warning: unused variable ‘normalizeSpeed’ [-Wunused-variable]
     uint16_t normalizeSpeed = (uint16_t)qRound(Bike->currentSpeed().value() * 100);
              ^~~~~~~~~~~~~~
make: *** [Makefile:9491: virtualbike.o] Error 1
`
i'm attaching a screen shot as well.

i'm trying to do this on a raspberry pi 3b rev1.2
qmake version 3.1
qt version 5.11.3

if i'm missing a detail or you want to ask a followup/question, please do.  thank you.
  
**Additional context**
![2022-04-23_qdomyos-zwift_error](https://user-images.githubusercontent.com/104282483/164949804-f9bc2d1a-b22d-46dd-870a-4b382acd4d58.png)

**Comment by cagnulein** [comment]
hi @alexrojo77 
the problem is about the Qt version is too old. QZ requires 5.15.2
Can you update it?

**Comment by alexrojo77** [comment]
i took a quick look this morning and i saw a bunch of sites talking about compiling the binaries in order to get the latest 5.15.2 version.  grr...i'll have to dig around some more and see if i can figure out how to do this.  perhaps you can comment as to whether this sounds about right?  thanks for your reply.

**Comment by cagnulein** [comment]
@alexrojo77 i believe raspberry pi os 64 bit (the latest one) don't require to build from source

**Comment by cagnulein** [comment]
@OswaldKolle1977 did you need to build it from source?

**Comment by OswaldKolle1977** [comment]
@cagnulein No - it worked out of the box (with one typo)

> $ sudo apt update && sudo apt upgrade # this is very important on raspberry pi: you need the bluetooth firmware updated!
> $ sudo sudo apt install git qt5quickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-assistant libqt5networkauth5-dev libqt5websockets5-dev
> **Typo: qt5quickcontrols2-5-dev << This one has to be changed to qtquickcontrols2-5-dev**
> $ git clone https://github.com/cagnulein/qdomyos-zwift.git
> $ cd qdomyos-zwift
> $ git submodule update --init src/smtpclient/
> $ git submodule update --init src/qmdnsengine/
> $ cd src
> $ qmake
> $ make -j4
> $ sudo ./qdomyos-zwift

This worked with the current 32 Bit Version of Raspberry OS -- Not sure about the 64 Bit Version - my compilation there is several weeks old (but it worked, too)

**Comment by cagnulein** [comment]
thanks for the feedback @OswaldKolle1977

**Comment by alexrojo77** [comment]
when i have a chance and some time i'll have to re-image my sd card to the before state and give it another try.  either that or load on the latest version of raspberry pi.  i'm sort of hesitant in doing the latter as i also use this as a pi hole which would probably mean having to reinstall and configure things.  anyways much thanks for the comments/help.

**Comment by cagnulein** [comment]
@alexrojo77 ok let us know ;) you can just do a full apt update apt upgrade without losing anything

**Comment by alexrojo77** [comment]
thanks.  maybe i'll give the full apt update a try first after restoring the sd card back to the before state.  this might be the easier path as i read that building the latest qt from the source will require quite a bit of time.

**Comment by cagnulein** [comment]
@alexrojo77 any news?

**Comment by shoulih** [comment]
> @cagnulein No - it worked out of the box (with one typo)
> 
> > $ sudo apt update && sudo apt upgrade # this is very important on raspberry pi: you need the bluetooth firmware updated!
> > $ sudo sudo apt install git qt5quickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-assistant libqt5networkauth5-dev libqt5websockets5-dev
> > **Typo: qt5quickcontrols2-5-dev << This one has to be changed to qtquickcontrols2-5-dev**
> > $ git clone https://github.com/cagnulein/qdomyos-zwift.git
> > $ cd qdomyos-zwift
> > $ git submodule update --init src/smtpclient/
> > $ git submodule update --init src/qmdnsengine/
> > $ cd src
> > $ qmake
> > $ make -j4
> > $ sudo ./qdomyos-zwift
> 
> This worked with the current 32 Bit Version of Raspberry OS -- Not sure about the 64 Bit Version - my compilation there is several weeks old (but it worked, too)

I am able to compile the latest code on Pi3 B with 32 Bit Version of Raspberry OS, but not able to launch it from CI:
**pi@raspberrypi:~/qdomyos-zwift/src $ sudo ./qdomyos-zwift
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
OK, you are root.
pi@raspberrypi:~/qdomyos-zwift/src $** 

Did I miss a step?

**Comment by cagnulein** [comment]
You need also the qml modules, do

apt install *qml*

Let me know

**Comment by shoulih** [comment]
> You need also the qml modules, do
> 
> apt install _qml_
> 
> Let me know

did it, but the same result:

sudo apt install qml

**Comment by cagnulein** [comment]
Nope sorry GitHub format qml in a strange way because I added the *

sudo apt install starqmlstar

Replace star with *

**Comment by shoulih** [comment]
![image](https://user-images.githubusercontent.com/66762397/168491344-ccecd6aa-7958-415c-8a3d-26b6fa734f5e.png)

**Comment by cagnulein** [comment]
Try 
sudo apt install qml-modulesstar
Replace start with *

**Comment by shoulih** [comment]
still no go :-)

![image](https://user-images.githubusercontent.com/66762397/168491632-a4d845a1-4f65-47a8-804d-378b196a873c.png)

**Comment by cagnulein** [comment]
Sorry without the s, qml-modulestar

**Comment by shoulih** [comment]
third time is a charm :-); up and running and really appreciated your help!

![image](https://user-images.githubusercontent.com/66762397/168492023-964e90e2-8be8-45b5-9d06-4a641a67b27a.png)

**Comment by cagnulein** [comment]
Great can you do a PR with the fix for the installation? Thanks

**Comment by cagnulein** [comment]
Also if you have some issues check this https://github.com/cagnulein/qdomyos-zwift/issues/769

**Comment by shoulih** [comment]
sure, will do.

**Comment by shoulih** [comment]
BTW, the newly built QZ connects my Proform CTC from off state without any issue, but when I exit QZ and restart QZ for applying some setting changes while the Proform is on, Bluetooth status remains "connecting" for some reason, which seems to prevent data from displaying on my p3:

![image](https://user-images.githubusercontent.com/66762397/168495594-52b00e76-e4e8-460a-8920-b6561ed42e19.png)

**Comment by cagnulein** [comment]
it's the #769 issue
switch to the raspberry branch

**Comment by shoulih** [comment]
I cloned the whole repository to my pi and what is the easy way to switch to the raspberry branch?

Thanks1

**Comment by shoulih** [comment]
thanks and do I need to get the following updates after checking out raspberry branch?
$ git submodule update --init src/smtpclient/
$ git submodule update --init src/qmdnsengine/

**Comment by shoulih** [comment]
thanks Robert, raspberry branch resolved the data missing issue when reconnecting while the bike is still on.
One minor issue: connection status UI text still is still showing "Connecting...", but actually the QZ is connected to the bike's BT already.

![image](https://user-images.githubusercontent.com/66762397/168721018-64d01d9a-c176-4225-a36e-e978ad3c5669.png)

**Comment by cagnulein** [comment]
yes, thanks for the feedback:)

**Comment by shoulih** [comment]
I have a requirement to run QZ on Debian Buster Image on Pi3 along with Parsec, which is only compatible with Debian Buster.
On the Pi3 with Debian Buster,  when run the QZ complied on Debian Bullseye I got the following error:
![execution_error](https://user-images.githubusercontent.com/66762397/169390886-f66fcdae-345a-4637-83fc-c471bd46fb89.JPG)

When I tried to compile the raspberry branch on Pi3 with Debian Buster, I got the following error:

![build_error](https://user-images.githubusercontent.com/66762397/169392500-477fbb6e-868f-42ad-bdad-55262ae5f416.JPG)

Just wondering if there is any workaround?

**Comment by cagnulein** [comment]
@shoulih i guess you're not using qt 5.15 isn't it?

**Comment by shoulih** [comment]
![image](https://user-images.githubusercontent.com/66762397/169427300-41eb348d-e605-4d52-b7dd-3529b97bf9b7.png)

**Comment by cagnulein** [comment]
@shoulih you need qt 5.15 for qz

**Comment by shoulih** [comment]
@cagnulein do we know how to upgrade qt 5.11 to qt 5.15 on Debian Buster on Pi3?

**Comment by cagnulein** [comment]
i guess you need to upgrade to debian 11

**Comment by shoulih** [comment]
unfortunately, I don't have this option as Parsec is only compatible with debian 10.

**Comment by cagnulein** [comment]
so you have to compile it from source. it will take a while

**Comment by shoulih** [comment]
yes, looks like that is the last option :-)

**Comment by cagnulein** [comment]
maybe you can also download the deb files from debian 11 handling all the dependencies

**Comment by shoulih** [comment]
> maybe you can also download the deb files from debian 11 handling all the dependencies

that is a great idea and I really want to try!  can tips what deb files I need to download from debian 11?

**Comment by cagnulein** [comment]
did you manage it @shoulih ?

**Comment by shoulih** [comment]
no, I didn't try that yet.  But I managed to make Parsec run on debian 11 intead :-)

**Comment by cagnulein** [comment]
Any news @shoulih ?
