### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jrw1982** [cagnulein/qdomyos-zwift#788]
**Describe the bug**
Tacx neo bike 2
Garmin hrm3-ss
Peloton app
Qd running on s21 ultra
Peloton running on tab s6

Bike detects straight away and seems to dip in and out resulting in wild cadence measurements as well as incorrect speed and odometer. 

Hrm doesn't function despite showing hr on bike display. 

Peloton resistance doesn't work at all. 

[debug-Sun_Apr_24_17_01_52_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8550052/debug-Sun_Apr_24_17_01_52_2022.log)

**Comment by cagnulein** [comment]
#388 please use this ticket 
thanks
