### ISSUE TITLE
Echelon EX3 Zwift Auto Resistance issues

### ISSUE THREAD

**Issue by durew** [cagnulein/qdomyos-zwift#789]
Hi Roberto, love the app, and have it mostly working with Zwift, but notice that the dynamic updating of auto resistance does not work most of the time for me
. I'm running QZ on my Android S10, Zwift on Windows 10 PC. When Zwift calls for a change in resistance during workouts, it will change my resistance to fairly close (sometimes it hits the correct for me), but won't auto correct itself if it's wrong, even if I'm 20w+ over/under the target watts. These workouts don't have a target cadence I've noticed, just wattage if that matters.

Attaching the debug log from my last ride, I noticed specifically at 19 minutes and 43 minutes I think during the ride was an example of QZ not correcting the auto resistance and I had to do it manually. I've tried stopping pedaling to disable ERG and pedaling to start again, but it doesn't auto correct, just gets it close to what it thinks the resistance I should be at

Let me know if you need more information or if I just have a setting wrong?
![Screenshot_20220424-112143](https://user-images.githubusercontent.com/62513662/164988675-b3e0dee2-c1cc-4f31-b776-89c0e260c51e.jpg)
![Screenshot_20220424-112124](https://user-images.githubusercontent.com/62513662/164988677-f181ec3a-e867-4bff-b74d-888fe2f4399b.jpg)
![Screenshot_20220423-111911](https://user-images.githubusercontent.com/62513662/164988679-a2650763-5b39-476c-a5c6-27cd134bd759.jpg)
[debug-Sat_Apr_23_11_38_28_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8550158/debug-Sat_Apr_23_11_38_28_2022.log)
.

**Comment by cagnulein** [comment]
thanks, i will check this tomorrow! have a nice sunday

**Comment by cagnulein** [comment]
hi @durew this is the main events from your log
as you can see, every time the first argumentt of the filter events is bigger than 10 there is a writing resistance event (means that i'm changing the resistance).
Specifically, at 19 and 43 minutes I saw a change on resistance. 
Could you help me to understand better your issue? It is everything fine from the log

<pre>
Sat. Apr. 23 11:38:33 2022 1650735513167 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 11:41:22 2022 1650735682862 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  16 -16 10 10"
Sat. Apr. 23 11:41:22 2022 1650735682863 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 51
Sat. Apr. 23 11:41:22 2022 1650735682881 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 58 66 65
Sat. Apr. 23 11:41:22 2022 1650735682983 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 18"
Sat. Apr. 23 11:45:23 2022 1650735923708 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  65 -65 10 10"
Sat. Apr. 23 11:45:23 2022 1650735923709 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 0
Sat. Apr. 23 11:45:23 2022 1650735923770 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 32"
Sat. Apr. 23 11:45:49 2022 1650735949450 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -79 79 10 10"
Sat. Apr. 23 11:45:49 2022 1650735949451 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 37
Sat. Apr. 23 11:45:49 2022 1650735949470 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 62 70 70
Sat. Apr. 23 11:45:49 2022 1650735949572 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 24"
Sat. Apr. 23 11:45:50 2022 1650735950571 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 23"
Sat. Apr. 23 11:46:04 2022 1650735964391 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -48 48 10 10"
Sat. Apr. 23 11:46:04 2022 1650735964392 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 60
Sat. Apr. 23 11:46:04 2022 1650735964408 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 71 82 75
Sat. Apr. 23 11:46:04 2022 1650735964574 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 17"
Sat. Apr. 23 11:46:34 2022 1650735994450 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -18 18 10 10"
Sat. Apr. 23 11:46:34 2022 1650735994451 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 78
Sat. Apr. 23 11:46:34 2022 1650735994465 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 69 82 80
Sat. Apr. 23 11:46:34 2022 1650735994574 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 14"
Sat. Apr. 23 11:46:49 2022 1650736009385 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  4 -4 10 10"
Sat. Apr. 23 11:47:04 2022 1650736024456 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  2 -2 10 10"
Sat. Apr. 23 11:47:34 2022 1650736054393 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  7 -7 10 10"
Sat. Apr. 23 11:47:49 2022 1650736069390 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  8 -8 10 10"
Sat. Apr. 23 11:48:04 2022 1650736084391 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  15 -15 10 10"
Sat. Apr. 23 11:48:04 2022 1650736084392 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 89
Sat. Apr. 23 11:48:04 2022 1650736084407 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 96 112 105
Sat. Apr. 23 11:48:04 2022 1650736084575 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 15"
Sat. Apr. 23 11:48:34 2022 1650736114395 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  20 -20 10 10"
Sat. Apr. 23 11:48:34 2022 1650736114396 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 86
Sat. Apr. 23 11:48:34 2022 1650736114408 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 106 113 110
Sat. Apr. 23 11:48:34 2022 1650736114574 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 11:48:49 2022 1650736129447 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  20 -20 10 10"
Sat. Apr. 23 11:48:49 2022 1650736129447 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 79
Sat. Apr. 23 11:48:49 2022 1650736129459 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 112 126 115
Sat. Apr. 23 11:48:49 2022 1650736129572 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 18"
Sat. Apr. 23 11:49:04 2022 1650736144460 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -2 2 10 10"
Sat. Apr. 23 11:49:34 2022 1650736174453 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  13 -13 10 10"
Sat. Apr. 23 11:49:34 2022 1650736174454 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 79
Sat. Apr. 23 11:49:34 2022 1650736174469 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 112 126 125
Sat. Apr. 23 11:49:49 2022 1650736189454 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -16 16 10 10"
Sat. Apr. 23 11:49:49 2022 1650736189455 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 92
Sat. Apr. 23 11:49:49 2022 1650736189470 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 127 146 130
Sat. Apr. 23 11:49:49 2022 1650736189573 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 17"
Sat. Apr. 23 11:50:04 2022 1650736204462 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  11 -11 10 10"
Sat. Apr. 23 11:50:04 2022 1650736204463 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 91
Sat. Apr. 23 11:50:04 2022 1650736204480 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 124 144 135
Sat. Apr. 23 11:50:34 2022 1650736234456 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  13 -13 10 10"
Sat. Apr. 23 11:50:34 2022 1650736234457 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 92
Sat. Apr. 23 11:50:34 2022 1650736234473 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 127 146 140
Sat. Apr. 23 11:50:34 2022 1650736234935 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  33 -33 10 10"
Sat. Apr. 23 11:50:34 2022 1650736234936 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 92
Sat. Apr. 23 11:50:34 2022 1650736234950 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 157 169 160
Sat. Apr. 23 11:50:34 2022 1650736234983 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 19"
Sat. Apr. 23 11:52:51 2022 1650736371143 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -3 3 10 10"
Sat. Apr. 23 11:52:51 2022 1650736371259 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -3 3 10 10"
Sat. Apr. 23 11:55:39 2022 1650736539800 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -30 30 10 10"
Sat. Apr. 23 11:55:39 2022 1650736539801 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 102
Sat. Apr. 23 11:55:39 2022 1650736539817 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 139 152 145
Sat. Apr. 23 11:55:39 2022 1650736539986 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 12:00:39 2022 1650736839814 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  13 -13 10 10"
Sat. Apr. 23 12:00:39 2022 1650736839815 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 108
Sat. Apr. 23 12:00:39 2022 1650736839829 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 147 161 160
Sat. Apr. 23 12:01:30 2022 1650736890271 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  32 -32 10 10"
Sat. Apr. 23 12:01:30 2022 1650736890272 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 96
Sat. Apr. 23 12:01:30 2022 1650736890288 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 154 164 160
Sat. Apr. 23 12:01:30 2022 1650736890539 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 18"
Sat. Apr. 23 12:05:39 2022 1650737139881 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -17 17 10 10"
Sat. Apr. 23 12:05:39 2022 1650737139881 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 100
Sat. Apr. 23 12:05:39 2022 1650737139898 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 136 149 145
Sat. Apr. 23 12:05:39 2022 1650737139984 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 12:10:39 2022 1650737439764 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  15 -15 10 10"
Sat. Apr. 23 12:10:39 2022 1650737439765 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 106
Sat. Apr. 23 12:10:39 2022 1650737439782 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 158 172 160
Sat. Apr. 23 12:10:39 2022 1650737439853 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 17"
Sat. Apr. 23 12:15:39 2022 1650737739773 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -19 19 10 10"
Sat. Apr. 23 12:15:39 2022 1650737739774 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 110
Sat. Apr. 23 12:15:39 2022 1650737739788 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 135 150 145
Sat. Apr. 23 12:15:39 2022 1650737739794 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 15"
Sat. Apr. 23 12:16:35 2022 1650737795372 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 12:20:39 2022 1650738039843 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  11 -11 10 10"
Sat. Apr. 23 12:20:39 2022 1650738039844 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 109
Sat. Apr. 23 12:20:39 2022 1650738039860 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 149 162 160
Sat. Apr. 23 12:20:45 2022 1650738045170 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 17"
Sat. Apr. 23 12:21:05 2022 1650738065234 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 18"
Sat. Apr. 23 12:21:13 2022 1650738073170 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 17"
Sat. Apr. 23 12:25:39 2022 1650738339845 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -20 20 10 10"
Sat. Apr. 23 12:25:39 2022 1650738339845 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 111
Sat. Apr. 23 12:25:39 2022 1650738339861 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 137 151 145
Sat. Apr. 23 12:25:39 2022 1650738339984 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 15"
Sat. Apr. 23 12:25:49 2022 1650738349977 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 16"
Sat. Apr. 23 12:30:39 2022 1650738639785 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -14 14 10 10"
Sat. Apr. 23 12:30:39 2022 1650738639786 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 102
Sat. Apr. 23 12:30:39 2022 1650738639800 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 110 125 125
Sat. Apr. 23 12:30:39 2022 1650738639986 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 14"
Sat. Apr. 23 12:30:54 2022 1650738654786 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  11 -11 10 10"
Sat. Apr. 23 12:30:54 2022 1650738654787 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 101
Sat. Apr. 23 12:30:54 2022 1650738654801 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 109 124 120
Sat. Apr. 23 12:31:40 2022 1650738700033 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  3 -3 10 10"
Sat. Apr. 23 12:32:24 2022 1650738744790 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  5 -5 10 10"
Sat. Apr. 23 12:33:09 2022 1650738789851 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  13 -13 10 10"
Sat. Apr. 23 12:33:09 2022 1650738789852 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 90
Sat. Apr. 23 12:33:09 2022 1650738789867 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 98 114 105
Sat. Apr. 23 12:33:09 2022 1650738789986 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 15"
Sat. Apr. 23 12:33:54 2022 1650738834926 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  6 -6 10 10"
Sat. Apr. 23 12:34:39 2022 1650738879790 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -10 10 10 10"
Sat. Apr. 23 12:35:24 2022 1650738924796 Debug: ../src/bike.cpp virtual void bike::changePower(int32_t) "filter  -13 13 10 10"
Sat. Apr. 23 12:35:24 2022 1650738924797 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 92
Sat. Apr. 23 12:35:24 2022 1650738924808 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 87 95 90
Sat. Apr. 23 12:35:24 2022 1650738924987 Debug: ../src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 13"</pre>

**Comment by durew** [comment]
Hi Roberto,
Not sure where in the log file corresponds to the elapsed time, I’ve done some programming many years ago so can somewhat understand the log. I remember during my run, at almost all of the wattage change request segments during the workout, QZ would only change it initially and not dynamically.
Example I remember was when I was around 19 minutes elapsed after starting QZ, Zwift sent a 140w request (from 155w), and QZ set the resistance to I think from 18 to 16? I was only pedaling at 120w @ 16% at the cadence I wanted to maintain, and stayed there for around 30-40s waiting for it to increase automatically to hit the 140 and it never did, so I always had to change it manually, this may be what you’re seeing with the change?
Thanks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by cagnulein** [comment]
@durew in the log you started riding at 11:41:22, so minute 19 should be 12:00 more or less.
the only 140W request from zwift in the whole file is this

> Sat. Apr. 23 11:50:34 2022 1650736234473 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 127 146 **140**

but there is also immediately another power change of 160W

> Sat. Apr. 23 11:50:34 2022 1650736234950 Debug: ../src/echelonconnectsport.cpp virtual uint8_t echelonconnectsport::resistanceFromPowerRequest(uint16_t) "resistanceFromPowerRequest" 157 169 **160** 

so maybe this is unexpected from you?
I suggest to do another ride, always checking the target power tile from QZ. On that tile you should see the realtime value reuqested from zwift, maybe this was a Zwift UI bug

let me know

**Comment by cagnulein** [comment]
@durew is it ok?

**Comment by durew** [comment]
I think so, while doing a workout I assumed that QZ will update dynamically on the fly even when Zwift doesn’t call for a resistance change, but it seems that it only updates when the workout changes the target power and then QZ changes to match based on my current cadence. When free riding without a workout, I have to turn off the workout/erg mode in QZ and it will update resistance on all incline changes quite nicely.
I’m assuming workouts are meant to work that way?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cagnulein** [comment]
hi @durew no during an erg mode, QZ will change dinamically the resistance based on your cadence. Send me a debug log to check if you have some wrong settings
Let me know

**Comment by cagnulein** [comment]
@durew can we close this? are we ok?

**Comment by durew** [comment]
Yes I believe so, sorry for the slow reply 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
