### ISSUE TITLE
Connect to other Cycling Services?

### ISSUE THREAD

**Issue by tbendis** [cagnulein/qdomyos-zwift#79]
I purchased the iOS app of qdomyos-zwift yesterday, and it works great! It's really nice to use Zwift with my Echelon exercise bike - very nice work!

Question: is it possible to add functionality to the qdomyos-zwift app that would allow it to connect to other riding services (e.g., iFIT, Rouvy, FulGaz, etc.)

**Comment by cagnulein** [comment]
hi @tbendis thanks! it already possibile, did you try? qdomyos advertise itself as a bluetooth cadence sensor or FTMS sensor. You have just to play with the "peloton setting" in order to change this behaviour (it depends about the app you wuold like to use).

I hope i answered to your question.

**Comment by tbendis** [comment]
Because of the "zwift" in the title of the project/app, I just assumed that it was only compatible with Zwift -- sorry about that!

I will try it with other services this evening.

**Comment by cagnulein** [comment]
Hahah i definitely need to change the name of the project :D

Il mer 16 dic 2020, 19:52 tbendis <notifications@github.com> ha scritto:

**Comment by cagnulein** [comment]
any news @tbendis ?

**Comment by tbendis** [comment]
I was able to successfully use your app with FulGaz!

**Comment by cagnulein** [comment]
i'm closing this one, if you need help, please reopen it or create a new one. Thanks!

**Comment by Spodnet** [comment]
Apologies for commenting on a closed ticket...

I've tried to connect my echelon sport via the app to other apps like rouvy/fulgaz, they only seem to recognise cadence - is this correct, they don't recognise power/watts like zwift does ?

**Comment by cagnulein** [comment]
Did you try to turn off the peloton setting? I didn't try yet these
services so I really don't know them

Il mer 20 gen 2021, 21:44 Spodnet <notifications@github.com> ha scritto:
