### ISSUE TITLE
[BUG] Stages SB20 auto resistance not working on peloton or zwift

### ISSUE THREAD

**Issue by qgriffith** [cagnulein/qdomyos-zwift#790]
**Describe the bug**
Using the current beta of QZ on iOS, connecting to a Stages Sb20 smart trainer, the auto resistance is not functioning.  Also tested using Zwift on Android and having it connect to QZ on iOS. Attaching the Bluetooth logs from Android while using Zwift on Android connected to the Stages bike and not QZ

**To Reproduce**
1. Launch QZ
2. Pair with Stages Bike Bluetooth
3. Launch Peloton or Zwift
4. No resistance changes

**Expected behavior**
Resistance should increase

**Screenshots**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-somethin
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8550188/btsnoop_hci.log)
g-doesn't-work%3F
  
  
**Additional context**
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8550190/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@qgriffith in the log i can't see a zwift interaction with the bike, i mean I see a connection but not a quick ride with a resistance change. Is what you did? If so, could you please repeat it including a small ride?
Thanks

**Comment by qgriffith** [comment]
I did a 1 mile ride on a hilly course that should have changed resistance. I can do another later on, how long should I go?

**Comment by cagnulein** [comment]
hah so that's strange because it seems that i just got the very init phase. try to do a 5 min workout. it could be enough. thanks

**Comment by qgriffith** [comment]
Okay I did a five min ride with a step incline. Attaching a picture of when I was going up the incline. Zwift slowed my speed way down to 3mph. The bike didn't increase resistance and I was peddling the same speed. The QZ app had me at 12mph.
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/8554819/btsnoop_hci.log)
![Screenshot_20220425-085923](https://user-images.githubusercontent.com/91335936/165096213-01198054-9231-4a8d-9a23-8e07d8b2927e.png)
![Screenshot_20220425-090423](https://user-images.githubusercontent.com/91335936/165096227-a9f47a35-c59c-411e-98ab-513ebb1db99d.png)

**Comment by cagnulein** [comment]
i guess there is a bit of confusion:) you don't have to qz for this. just zwift and the bike :)

**Comment by cagnulein** [comment]
@qgriffith so strange, it's very standard the control from the zwift point of view. Do you have a debug log when you tried to use QZ on iphone with zwift on another device? I would like to compare the QZ debug log with your last HCI file.
I guess there is a thin difference!
Thanks

**Comment by qgriffith** [comment]
Where would I find the debug log on Ios for QZ :)

**Comment by cagnulein** [comment]
here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
@qgriffith in this case the resistance doesn't work because the "zwift erg mode" on QZ was on. Could you please turn it off and try again to use QZ as a bridge to your bike and zwift and post a debug log?
If we got it working in this scenario, I can use the same engine to change it for peloton
Let me know

**Comment by cagnulein** [comment]
@qgriffith  perfect! now i'm tryting to port this for peloton! could you
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. So when i finish this i will send you the new beta.
Thanks

**Comment by qgriffith** [comment]
[debug-Tue_Apr_26_17_19_02_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8567013/debug-Tue_Apr_26_17_19_02_2022.log)
[debug-Tue_Apr_26_17_07_55_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8567015/debug-Tue_Apr_26_17_07_55_2022.log)
[debug-Tue_Apr_26_17_02_42_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8567016/debug-Tue_Apr_26_17_02_42_2022.log)
Adding more logs for the most recent test on the version you just released. It could be I have a setting wrong ::(

**Comment by cagnulein** [comment]
@qgriffith thanks, i saw them and understood! I did several mistakes. I'm trying to fixing them. I will send you a new one later today or tomorrow

**Comment by qgriffith** [comment]
[debug-Fri_Apr_29_08_08_43_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8590910/debug-Fri_Apr_29_08_08_43_2022.log)

**Comment by cagnulein** [comment]
@qgriffith the issue about this log it's the fact that QZ is not connected to the SB20 but to your stages pedal. Put the SB20 to the manual device setting in the advanced setting section to be sure to use the SB20 and restart QZ and share me a new log.
Thanks!

**Comment by qgriffith** [comment]
[debug-Sun_May_1_10_23_23_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8602875/debug-Sun_May_1_10_23_23_2022.log)
I tried it this morning and it did engage resistance but to like 100% as soon as the class started and didn't adjust down. It was so hard I could hardly pedal even in the lowest gear.

**Comment by cagnulein** [comment]
ok thanks @qgriffith i will check this later

**Comment by cagnulein** [comment]
@qgriffith ok sorry for the delay. I checked the log and the good news is that it's working as I planned :) but maybe the current conversion that i implemented is too much

as I did for the #388 , @Jrw1982 can cofirm this,

I'm translating peloton resistance to % hill grade / 10

so for example peloton resistance 50 is a 5% grade

In the log the peloton trainer asks for resistance 35 and i put your bike to 3.5%
Maybe it's too hard for you? What do you suggest instead?
Maybe I can handle the peloton offset and peloton gain setting in this so you can change the response of your bike. Will it be ok for you?

**Comment by Jrw1982** [comment]
Yes I can confirm the resistance works as it should be its very much related to the cadence. If you stop pedalling it is very hard to get going again. Imagine being on a hill on a real bike from a standing start and trying to get going. If you keep the cadence matched to the class in peloton then the resistance changes aren't even noticeable until the sweat starts pouring it of you.

**Comment by cagnulein** [comment]
@Jrw1982 @qgriffith you can use the gear tile to lower it down so you can get it easy on the startup, and change it when you're ready like you will do on a real bike during a hill

**Comment by qgriffith** [comment]
Oh awwesome work! I will do a full class later this week. THank you so much

**Comment by cagnulein** [comment]
@qgriffith let me know! of course if, after the test, you still think that it's too hard it could be a good solution to add an offset from the peloton difficulty (for example, resistance 35 on peloton should be 0,5%; resistance 45 should be 1,5% and so on) using the peloton offset setting.
I'm open to all the solutions :)

**Comment by cagnulein** [comment]
@qgriffith send me the debug log, maybe there is a setting with a wrong value

**Comment by Jrw1982** [comment]
Sorry, I haven't been on the bike much due to injury.

I would agree that the settings are too harsh with Peloton.  There is also a big time offset from the video to the changes being reflected in QZ.  I find myself turning down the resistance on the QZ tile to around 93-97%.  I have no basis on what the resistance would be like if I was on an actual peloton bike though so its all very subjective.

**Comment by cagnulein** [comment]
@qgriffith the video desync is easily fixable with the peloton offset tile. also you have to press yes on the popup on qz when the peloton timer hits 0:00

let me know when you will ride again :)

today i just dismissed the bot action i didn't mean to disturb you :)

**Comment by cagnulein** [comment]
@Jrw1982 how the rehab goes?
@qgriffith are you still interesting on this?
