### ISSUE TITLE
KingSmith WalkingPad X21

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#791]
[btsnoop_hci.log.tar.gz](https://github.com/cagnulein/qdomyos-zwift/files/8563045/btsnoop_hci.log.tar.gz)

**Comment by cagnulein** [comment]
[debug-Fri_Apr_29_09_03_20_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8588382/debug-Fri_Apr_29_09_03_20_2022.log)

@d3m3vilurr hi! how are you? Could you please check this log? It should be releated to your implementation on #436 
Thanks!

**Comment by d3m3vilurr** [comment]
hi @cagnulein  yes. it looks same as my implementation.

**Comment by d3m3vilurr** [comment]
it uses app version's table key. idk reason when i test with my kingsmith r2, two chars of key table has been swapped.('Z' and 'S')

this device seems use original table; `ZaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEijklmnopQrsBuvMxXz1yA2t5078KS3=`

detail information is 77~85 line of [this](https://gist.github.com/d3m3vilurr/69b84ce4d57ed8c93b19c93600570394#file-get_beacon_key-py)

**Comment by cagnulein** [comment]
Thanks, I will try to patch it!

**Comment by cagnulein** [comment]
@d3m3vilurr done. Just to be sure I added a new setting (disabled by default) in order to use the new encryption table

**Comment by cagnulein** [comment]
BTW the original poster doesn't answer me anymore by email :D

**Comment by d3m3vilurr** [comment]
idk what value decides swap position of encrypt table, so maybe different device would use different table, so on/off toggle wouldn't help future device cases.
(I'll recheck the values when I have a time. but reversing flutter app is pretty s*cks)

imo, an another idea is adding new argument for passing a integer value into constructor of the kingsmaithr2treadmill.
but these opinions have same purpose to decide encrypt table automatically. anyway it's your call :)

**Comment by cagnulein** [comment]
> idk what value decides swap position of encrypt table, so maybe different device would use different table, so on/off toggle doesn't help future device cases.

Why do you say so? I mean a toggle is perfect because in any case the user can try to the different table regardless the name or the model of his treadmill, isn't it? Maybe i'm missing something in the translation to Italian :)



> imo, an another idea is adding new argument for passing a integer value into constructor of the kingsmaithr2treadmill.
> but these opinions have same purpose to decide encrypt table automatically. anyway it's your call :)

yes of course, but i did in this way also for other treadmills/bikes so I'm keeping the same format. Settings are easy understandable in the code too I guess

**Comment by d3m3vilurr** [comment]
my point is.. 

we have 3 tables
v0 is original (`ZaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEijklmnopQrsBuvMxXz1yA2t5078KS3=`)
R2 uses v1 that swapped `Z` and `S`
X21 uses v2 that swapped `V' and 'M'

it means if kingsmith release new walking pad device, they can use different swap position.
and just on/off toggle would be bad condition for users. (becasue it makes multiple exclusive toggle switch for them..)
so, imo good option is one of them;
- adding drop down switch for selection (it's easier for devs)
- selector swap positions (it's more friendly for devs but it's not for end users)
- automatically detect table from device type/name (imo it's more friendly for users than other options)

but sorry idk what value determine the swap position of original table.
(maybe communicate between devices during handshake time or just use hardcode value in source code for each devices.
at least my device always swap `Z` and `S` position, so position could related device or device type)

**Comment by cagnulein** [comment]
got now your point. Of course the automatic detection will be the perfect one.
Let's see how it will go, i can collect here on github a compatibility list so it will be easy to enable/disable the toggle for a particular treadmill..

Thanks for the explanation!

**Comment by cagnulein** [comment]
it worked!

**Comment by cagnulein** [comment]
hi @d3m3vilurr another new case :)
[debug-Sat_Aug_6_22_18_54_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275238/debug-Sat_Aug_6_22_18_54_2022.log)

**Comment by cagnulein** [comment]
[debug-Sat_Aug_6_22_50_07_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275281/debug-Sat_Aug_6_22_50_07_2022.log)
it crashes here with the v2 disabled. So i guess the v2 must be disabled. Let me check the ANR report

**Comment by cagnulein** [comment]
@d3m3vilurr check if you like my patch

**Comment by d3m3vilurr** [comment]
imo, a new key is `0aCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEijklmnopQrsBuvMxXz1yA2t5Z78KS3=`
plus if string contains outside char of the alphabet + number, we use wrong key for cipher

**Comment by cagnulein** [comment]
thanks @d3m3vilurr i'm adding a v3 with this one for testing purpose.

**Comment by cagnulein** [comment]
confirmed! @d3m3vilurr the new key works with this Taiwan version! Thanks!
