### ISSUE TITLE
[REQ] Elevation in Miles for treadmill

### ISSUE THREAD

**Issue by wmccumbers** [cagnulein/qdomyos-zwift#792]
When connected to my Sole F85 Treadmill, my elevation shows in meters instead of feet. 

**Describe the solution you'd like**
I would like to see the elevation units displayed in feet in the app while on treadmill 

**Describe alternatives you've considered**
My alternatives are to leave it in Meters and calculate it myself once I've uploaded my activity

**Additional context**

**Comment by cagnulein** [comment]
@wmccumbers done! i will send you the new beta later today or tomorrow!

**Comment by cagnulein** [comment]
@wmccumbers is it ok? did you test it?

**Comment by wmccumbers** [comment]
Roberto,

It did not, not sure what the issue was. I may have had something wrong in
the settings for the Sole treadmill. I will try to check again tomorrow or
Friday and send you screenshots of it doesn’t work. If it does, I will let
you know as well.

respectfully,
Will

**Comment by cagnulein** [comment]
@wmccumbers Send me a debug log if it doesn't work 
Thanks

**Comment by wmccumbers** [comment]
Roberto,

Sorry for the late reply. I was able to test it, it worked just fine. Thank
you for all the hard work.

respectfully,
Will McCumbers

**Comment by cagnulein** [comment]
Great @wmccumbers thanks for the update!

**Comment by cagnulein** [comment]
@wmccumbers hi, how are you? a user sent me a request for the same treadmill in order to have auto inclination support. Are you interested on this?

**Comment by wmccumbers** [comment]
Of course

**Comment by cagnulein** [comment]
@wmccumbers i don't remember: are you running qz on an android or ios?

**Comment by wmccumbers** [comment]
I’m on iOS

**Comment by cagnulein** [comment]
@wmccumbers don't you have any android devices nearby? Just to collect some log?

**Comment by wmccumbers** [comment]
I don’t. I’m sorry

**Comment by cagnulein** [comment]
ok we have to wait the other user so, i will let you know ;)
