### ISSUE TITLE
Trouble with starting resistance on RGT-wahoo 

### ISSUE THREAD

**Issue by gewahr** [cagnulein/qdomyos-zwift#794]
Used to train on zwift pc and qz s21galaxy android phone with echelon ex3 . My mimimum resistance is set at 20 in qz. 
I am trying the new rgt-wahoo. In rgt if control of autoresistance is on my resistance does not start at 20 like in zwift but instead at values like 3 . So my wattage is  very low. 
 QZ - OS: [android]
 - Version [2.10.74

**Smartphone (galaxy s21 5g):**
 - 
 - OS: [android 12)
 - Version [e.g.4.1
 - ]

**Append a debug log**

 there was many debug files . do not know which is the good one . i registered it at around 10:25 pm.

could retry with zwift to see if I have the same problem
  
[debug-Thu_Apr_28_11_23_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8587790/debug-Thu_Apr_28_11_23_41_2022.log)
[debug-Thu_Apr_28_10_41_47_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8587792/debug-Thu_Apr_28_10_41_47_2022.log)
[debug-Thu_Apr_28_11_19_05_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8587793/debug-Thu_Apr_28_11_19_05_2022.log)

**Comment by cagnulein** [comment]
hi @gewahr i didn't find in the log the one of the 10:25 anyway i guess i got your issue.
Seems that RGT uses ERG mode not INDOOR SIMULATION as zwift does. That's why the conversion is different. RGT requires to follow a power as a zwift workout does. Are you aware of this?

**Comment by gewahr** [comment]
No .I do not understand. 
Then what setting should i use in QZ to be able to compete ? or should i set the resistance manually ?

**Comment by cagnulein** [comment]
@gewahr nevermind, delete my previous comment.

now i checked the [debug-Thu_Apr_28_11_23_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8587790/debug-Thu_Apr_28_11_23_41_2022.log) and it was fine but i understood your issue: the zwift resistance offset is to 4! you need to put it to 20!
Let me know

**Comment by gewahr** [comment]
AH ok thanks , will give it a try :)

**Comment by gewahr** [comment]
1) I Set  the starting resistance to 20 and  the offset to 20 and strangely this time the control tab does not show in RGT. Any idea why ?
2) Is the QZ app available yet for windows ??  .  I did not see it on the microsoft store. 

thanks

**Comment by cagnulein** [comment]
@gewahr 
1. No it's not related to those parameters. Try to reboot your devices
2. Microsoft is still approving my request..they are very slow. Anyway in the meantime you can enable the wahoo direct connection settings in the qz iOS version in order to use dircon instead of Bluetooth

**Comment by gewahr** [comment]
thank you very much!

Le mar. 3 mai 2022 à 00:16, Roberto Viola ***@***.***> a
écrit :

**Comment by cagnulein** [comment]
@gewahr did the S5 always work before on RGT as control? If yes maybe it's just a cache issue on the RGT device or RGT itself.
No, there isn't a setting to disable the controllable from QZ to RGT, so if you see QZ as power and cadence you have too see also as CONTROL always.

**Comment by gewahr** [comment]
tried the wahoo direct on the same device (S5) and i have 2 wahoo direct connections . They connect right away but no data is registered in RGT. So power and cadence are at 0
I'm not sure if the S5 worked before as a control ??

will try the wahoo direct on IOS later . thanks

**Comment by cagnulein** [comment]
@gewahr maybe the control disappeard when you turned on Wahoo direct connect? This could be the reason (it should works also as controllable but it could be an explanation)
Ok let me know if it works on iOS

**Comment by gewahr** [comment]
no it disappeared before. it shows with wahoo connect except that i do not register any data on RGT. Will try the IOS later. Thanks

**Comment by gewahr** [comment]
Tried both qz apps with wahoo connect on  and both  with RGT and SystM wahoo
1) QZ  on android galaxy s21 app- the wahoo connect shows in both apps , connect easily but stays at zero so cannot move.
RGT crashed twice
2) QZ on IPAD mini with wahoo direct  on ....wahoo connect does not show in the sensors list so no connection is possible.
both Bluetooth and wifi were on on both QZ devices.
Would be a very interesting solution if it works because of the instability of bluetooth but no luck. So any hint would be appreciated when you have time  . Thanks

**Comment by cagnulein** [comment]
@gewahr i think i have to try myself this because rgt on dircon was working before my zwift dircon changes, i have to try it again
i will let you know

**Comment by gewahr** [comment]
Ok, thanks.

Le mer. 4 mai 2022 à 00:24, Roberto Viola ***@***.***> a
écrit :

**Comment by gewahr** [comment]
Hi Roberto !

Additionnal info : QZ app on my galaxy s21phone with wahoo connect on - Galaxy S5 tablet with ZWift . Wahoo kicker shows and connects easily but all values are at zero. So the problem is not related to RGT. 
thanks

**Comment by cagnulein** [comment]
@gewahr Thanks, so android is involved somehow. I usually test iOS to iOS and it worked.

**Comment by gewahr** [comment]
If you need more testing, let me know! have a nice day!

**Comment by cagnulein** [comment]
@gewahr do you have a windows pc or a mac to try?

**Comment by cagnulein** [comment]
@gewahr i just add qz to the microsoft store https://apps.microsoft.com/store/detail/qz-fitness/9NNQLXD4TR4L?hl=it-it&gl=it

if you want i can give you a free code to try
let me know

**Comment by cagnulein** [comment]
@gewahr did you try again now?

**Comment by gewahr** [comment]
yes  wahoo connect only work with zwift on windows . It connects to RGT/wahoo but no data is sent.
