### ISSUE TITLE
[BUG] Auto-Resistance with Peloton App not Working

### ISSUE THREAD

**Issue by skyfxl** [cagnulein/qdomyos-zwift#797]
Hi,

I just purchased qdomyos-zwift on the Google Play Store and installed it on my Echelon EX-5S bike along with the Peloton app. I successfully have the two apps running in parallel (split screen) and would like to take advantage of the auto resistance feature. According to a related post online (see step 53 here: https://forum.xda-developers.com/t/upgrading-glory-star-nebula-21-5-tablet-to-basic-android-rom.4023915/post-86523325), I was expecting a pop-up to appear in the qdomyos-zwift app prompting me to sync to Peloton, but it doesn't. Thoughts?

Debug log: [debug-Sun_May_1_14_46_53_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8599715/debug-Sun_May_1_14_46_53_2022.log)

Thanks!

**Comment by cagnulein** [comment]
@skyfxl you need to set your peloton credentials in qz settings press ok on both password and username restart qz and then you have to see a green check mark right to your username 
let me know

**Comment by cagnulein** [comment]
@skyfxl did you fix this?

**Comment by skyfxl** [comment]
@cagnulein, apologies for the delayed response. Yes, entering the Peloton username and password in the options fixed the issue. Thanks for your help!

FYI - for any others that encounter the same issue in the future:

1. A simple restart of the qdomyos-zwift app after entering the Peloton username and password did not resolve the issue. I had to restart the Echelon tablet.
2. After the popup screen appears in the qdomyos-zwift app asking to activate the Peloton sync, wait until the video on the Peloton App goes to 00:00 time to click yes on the sync. Otherwise the resistance changes will happen at the wrong time.
3. The resistance will sync to one level below that suggested by the instructor (e.g., if the instructor says 25-40, the app will sync to 24).

**Comment by cagnulein** [comment]
@skyfxl perfect!
1. ok probably because you lost the link once QZ restarted
2. yes it's the suppose way to sync them. Also with the peloton offset tile you can trim the delay in realtime
3. yes because the conversion ratio is not 1:1 so since the resistance is an integer there is no perfect way to sync them. Anyway you can use the gear tile if you want to trim it
