### ISSUE TITLE
[REQ] Getting QZ to Work with True PS800 Treadmill

### ISSUE THREAD

**Issue by rmorenopdx** [cagnulein/qdomyos-zwift#799]
**Is your feature request related to a problem? Please describe.**
QZ doesn't seem to recognize my treadmill, even though it is recognized and works with Zwift.  I have a True PS800 Treadmill that is a little over a year old. QZ doesn't recognize it - the name “True 250” flashes briefly on the screen, but QZ goes quickly by it, just like it skips other generic Bluetooth devices - TV, speakers, etc. 

Again, the treadmill connects to Zwift successfully, so it it seems to be able to “talk” to an iOs device via bluetooth. Interestingly, the treadmill does not connect to the Kinomap app either.

**Describe the solution you'd like**
I'd love to have this work with my treadmill so I can then connect to Peloton.

**Describe alternatives you've considered**
N/A

**Additional context**
I was able to connect to it using NRF connect for iOs. Log is attached
[text-D59441F87947-1.txt](https://github.com/cagnulein/qdomyos-zwift/files/8618022/text-D59441F87947-1.txt)
[text-4463FCB8C521-1.txt](https://github.com/cagnulein/qdomyos-zwift/files/8618031/text-4463FCB8C521-1.txt)

**Comment by cagnulein** [comment]
thanks @rmorenopdx 
just a couple of questions:
1. do you know if exist an app for this treadmill? I mean a one from True company for example? If so which is its name?
2. do you have also an android device? If so are you able to follow this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

let me know

**Comment by cagnulein** [comment]
@rmorenopdx ok so we need several steps. Let's create a plan:
1. i will send tonite a version to collect some data from your treadmill. send me an email to roberto.viola83 at gmail.com indicating this ticket . Thanks
2. then, when you will receive it, you need to enable the debug log in the experimental settings in QZ 
3. restart qz
4. do a quick run on the treadmill writing down what you do
5. send me the debug log and the steps that you did in the session

is it ok for you?

**Comment by cagnulein** [comment]
argh i saw an issue there, we need to repeat the test when i will release a new version tomorrow. sorry for the issue

**Comment by rmorenopdx** [comment]
No problem.

Thanks

Ray

**Comment by cagnulein** [comment]
@rmorenopdx i didn't forget about you, i just have a terrible day at work. i will upload a new version tomorrow 
thanks and have a nice friday evening!

**Comment by rmorenopdx** [comment]
Don’t worry! This is an “extra” thing you do, not your primary focus. Donut on your schedule. Thank you for what you are doing for all of us. 

Ray

**Comment by cagnulein** [comment]
@rmorenopdx sent! redo the steps that you did with this version. Thanks and sorry for the delay

**Comment by rmorenopdx** [comment]
All right. I just redid it with the same timings as above.
@
[debug-Sat_May_7_11_27_35_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8645749/debug-Sat_May_7_11_27_35_2022.log)
`

**Comment by rmorenopdx** [comment]
Let me know if I did it correctly. Thanks.

ray

**Comment by cagnulein** [comment]
@rmorenopdx You did it perfectly! I see the metrics! I will implement them tomorrow or Monday!
Have a nice Saturday night!

**Comment by cagnulein** [comment]
For my reference 

16 73 49 8a 00 01 00 e3 01 71 01 00 1d 00 2d 1e 00"

01e3 -> 483 -> 4,83 km/h -> 3 miles/h
1e -> 30 -> inclination 3

**Comment by cagnulein** [comment]
@rmorenopdx Sent!

**Comment by rmorenopdx** [comment]
It works, and is reading speed and incline. We’ll done! Thank you. 

Is there any possibility of two way communication so I can control speed/incline from the QZ App. I’m guessing not, but figured I’d ask.

Thanks again!

Ray

**Comment by cagnulein** [comment]
great! @rmorenopdx unfortunately it seems that your treadmill doesn't accept control from 3rd party app.

does gymtrakr  is able to control it?

**Comment by rmorenopdx** [comment]
I do not think that GymTrakr can control anything, but I will try again tonight. Thank you again for the quick response.

**Comment by rmorenopdx** [comment]
I have confirmed that GymTrakr can NOT control the treadmill. 

QZ is not reading speed and incline targets from Peloton. It identifies the workout correctly , and the Peloton elapsed time us read, but no speed or incline targets. Any suggestions?

**Comment by cagnulein** [comment]
@rmorenopdx not all the peloton workouts have metrics. @janabouc any suggestions about a workout with the metrics?

**Comment by janabouc** [comment]
I will look through my Strava and previous notes about some that will work.

**Comment by rmorenopdx** [comment]
Thank you!

**Comment by janabouc** [comment]
This is one that worked for me. https://members.onepeloton.com/classes/walking?utm_source=ios_app&utm_medium=in_app&modal=classDetailsModal&classId=0d4499d36b89417c9958b254a47abc94&locale=en-US

**Comment by cagnulein** [comment]
@rmorenopdx any news?
