### ISSUE TITLE
Calculate calories burned for devices that don't provide it

### ISSUE THREAD

**Issue by marklogan17** [cagnulein/qdomyos-zwift#80]
I've been researching how we can get a reasonably accurate calculation for calories burned based on output.  I looked at the two links below to get somewhat consistent values for METs vs output in watts.  The first link also provides the equation for calories burned per minute for a given MET output and bodyweight.  Since you now have bodyweight in the application, you should have everything you need to calculate.  I believe you are looking at the cadence/output every second, but if not, rather than divide by 60 I guess just divide by whatever fraction of a minute you're doing the calculation for :)

https://captaincalculator.com/health/calorie/calories-burned-spinning-calculator/
http://prevention.sph.sc.edu/tools/docs/documents_compendium.pdf

I put the values for Output vs MET in my handy dandy spreadsheet and came up with an equation for MET based on Output.  It matches the guidance really well.  Have a look at tab four on the spreadsheet below.  Seems most accurate when I look at the high end of the range provided vs the MET value.

https://docs.google.com/spreadsheets/d/1OHoZsEx-0i6ETi83g0uI7q3Ug8ET0u-fVVSm8rAUC3s/edit?usp=sharing

Now we put all the formulas together:
Calories burned per minute = (MET x body weight in Kg x 3.5) ÷ 200
Calories / second = ((MET x body weight in Kg x 3.5 ) / 200 ) / 60 
  = (( (0.048* Output in watts +1.19) * body weight in kg * 3.5) / 200 ) / 60

If you're not calculating for a second at a time, just change the / 60 as appropriate.

I have no 'real' proof that this will give accurate calories but its based on the literature that I could find so its probably not 'wrong'.

**Comment by cagnulein** [comment]
added to 1.6.1 if i didn't wrong :D
