### ISSUE TITLE
Renpho doesn't do auto resistance wih vzfit

### ISSUE THREAD

**Issue by chawa2** [cagnulein/qdomyos-zwift#804]
Hi, I still cant get it to work. connected heartrate monitor and renpho bike to the app to use in vzfit. both are connected in the app but automatic resistance does not work. ` 
I think i managed to attach the log fileto this issue (used the attach pic button. If not, how do i do so?

**Comment by cagnulein** [comment]
Hi, unfortunately I can't see the log, GitHub allows attach files only from the desktop (windows or Mac)
Let me know

**Comment by chawa2** [comment]
[debug-Sun_May_8_12_27_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8646391/debug-Sun_May_8_12_27_13_2022.log)

**Comment by chawa2** [comment]
That must have been it then, tried on my android phone. This should be the log? Emailed it to my mac

**Comment by cagnulein** [comment]
@chawa2 Unfortunately in this log there is nothing, probably it's another session. Anyway I suggest to join the beta on android. I did a lot of modifications for renpho bikes in these months
Let me know

**Comment by chawa2** [comment]
I only tried it twice and both times it didnt work. How do I join the beta? Also, would it work on an apple device as I do have an old ipad that i could use.
--
Sent from myMail for Android Sunday, 08 May 2022, 09:44pm +10:00 from Roberto Viola  ***@***.*** :

***@***.*** Unfortunately in this log there is nothing, probably it's another session. Anyway I suggest to join the beta on android. I did a lot of modifications for renpho bikes in these months

**Comment by cagnulein** [comment]
For the beta you just need to join it from the play store page of QZ.
The problem of this log is there is nothing inside, probably you have more logs if you enabled the debug log setting before of your workout
Which iOS version do you have on the iPad?

**Comment by chawa2** [comment]
Hi Roberto, not sure why there is nothing in the logfile. I opened the file in console and (while I dont know what it means) I do see quite some lines lf text. I purchased the app for IOS as well and it works so I will use the old ipad ( very cracked but usuable). i will try again on my android phone in a while to check ifit has changed. I just gave it another try and it just doesnt connect my bike.
Connected heartrate sensor to the app and also the Renpho bike. the screen with all the tiles comes up. But in VZfit (connected to my phone) I can see the heartrate and my bike is not connected (i can tell as the dial had the option on .0.5 increments which are 1.0 increments when connected with auto resistance. The only thing different in the settings is that on the ipad heartrate outside FTMS is off and on on android this is on. But then you already said this could not be the issue.
Cheers,
Chantal
--
Sent from myMail for Android Sunday, 08 May 2022, 09:58pm +10:00 from Roberto Viola  ***@***.*** :

**Comment by cagnulein** [comment]
the log file is valid but simply it's not about a real workout. qz is writing a log file for each time you open the app, even if you're not doing a workout. that's why i'm saying "the log is empty", i mean the log doesn't contains information about a workout :)

**Comment by cagnulein** [comment]
@chawa2 any news?
