### ISSUE TITLE
Sole e25 elliptical distance calibration

### ISSUE THREAD

**Issue by Slyisby** [cagnulein/qdomyos-zwift#808]
My Sole e25 elliptical's displayed distance and that recorded by QZ do not match.  This morning, the elliptical recorded 1.9 miles, while QZ recorded 1.2 miles, for a difference of 36.8%. At your suggestion on Facebook, I confirmed that everything is recorded in miles, not kilometers, so that can't be the problem.  I am attaching the debug log from today's session if that helps.

Thank you, as always!

[debug-Wed_May_11_05_32_16_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8669089/debug-Wed_May_11_05_32_16_2022.log)

**Comment by cagnulein** [comment]
@Slyisby 1.2 * 1.6 = 1.9 so it's just this :)
in order to do so i need to add a new setting for you
i will let you know in the next days

**Comment by cagnulein** [comment]
@Slyisby i guess that also the speed is affected by this, isn't it?

**Comment by cagnulein** [comment]
@Slyisby modification done. 
could you please send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS as a reminder? Thanks

**Comment by cagnulein** [comment]
@Slyisby mail sent

**Comment by Slyisby** [comment]
Perfect, Roberto. Thank you very much!

Phil

Sent from my iPhone

On May 12, 2022, at 4:26 PM, Roberto Viola ***@***.***> wrote:

﻿

@Slyisby<https://github.com/Slyisby> mail sent

**Comment by cagnulein** [comment]
@Slyisby can we close this?

**Comment by Slyisby** [comment]
Yes, thank you again.

**Comment by Slyisby** [comment]
Yes, thank you again.
