### ISSUE TITLE
t900 - pi0w - zwift on laptop (connection fails without segfault)

### ISSUE THREAD

**Issue by rickoneeleven** [cagnulein/qdomyos-zwift#81]
i'm only getting one connection drop between bridge and treadmill approximately every hour, although this isn't a specific pattern. just on average it drops once per hour.

the problem is, it isn't segfaulting - otherwise my auto restart script would just restart it and reconnect. the bridge continues to run but just treadmill stops and disconnects, i can't tell if it's also disconnected from zwift.

to fix, I have to CTRL-C script, then start it up again manually

[debug-Sun Dec 20 15_14_09 2020.zip](https://github.com/cagnulein/qdomyos-zwift/files/5721395/debug-Sun.Dec.20.15_14_09.2020.zip)

**Comment by cagnulein** [comment]
The strange thing is that it's not connected again automatically...i will check it tomorrow.

**Comment by rickoneeleven** [comment]
even if you can get the bridge to exit/close when it loses connection to the treadmill so my auto restart script kicks it back into action and restores the connection - that would help.

maybe when this event occurs: BTLE stateChanged InvalidService

**Comment by cagnulein** [comment]
I could add an option to do it, yes.
You're the king of workaround :)

Il dom 20 dic 2020, 22:15 Ryan Partington <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment]
@rickoneeleven pull it and build it. i added a -no-reconnection for you. Tell me if it will work

**Comment by rickoneeleven** [comment]
beautiful thank you, i'll test over the next few days ❤️

**Comment by cagnulein** [comment]
this is my christmas present for you :D

**Comment by rickoneeleven** [comment]
❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️  ❤️

**Comment by rickoneeleven** [comment]
got a load of these during make? 
![mstsc_u3lW2pFzIg](https://user-images.githubusercontent.com/8156878/102779498-3d6d7c80-438c-11eb-8e5c-e2e7a5727fc6.png)

**Comment by cagnulein** [comment]
yes they are normal, i added the FIT library from garmin and it has some warning, ignore them

**Comment by rickoneeleven** [comment]
cool thanks

**Comment by rickoneeleven** [comment]
[debug-Tue Dec 22 17_14_36 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5731375/debug-Tue.Dec.22.17_14_36.2020.log)

disconnected today but the bridge kept running, so had to CTRL+C it myself to restart it, also when it restarted the speed and incline had reset (0% incline and 1 speed i think) whereas I was running 1% incline and 6.4 speed

this is the event I was hoping it would auto stop at: Debug: bluetooth.cpp void bluetooth::debug(QString) "Tue Dec 22 17:54:32 2020 1608659672656 BTLE stateChanged InvalidService"

but it kept running 🐑

**Comment by cagnulein** [comment]
Argh, tomorrow i will check it, sorry :/

Il mar 22 dic 2020, 19:11 Ryan Partington <notifications@github.com> ha
scritto:

**Comment by cagnulein** [comment]
@rickoneeleven sorry, my fault. i was so used to write for mobile app that i forgot the behaviour for the linux target ;) (the parameter wasn't active, simply :/ )

**Comment by rickoneeleven** [comment]
ahh cool, i'll pull it and give it a go over a next few days ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by rickoneeleven** [comment]
-no-reconnection fixed issue, still crashes (ill open another issue) for the program dumps out now and restarts at the correct speed ❤️
