### ISSUE TITLE
[BUG] Auto resistance not working on SportPlus SP-HT-1004-iE with IOS app

### ISSUE THREAD

**Issue by Angi2412** [cagnulein/qdomyos-zwift#812]
**Describe the bug**
The auto resistance is not working in Zwift or Peleton app on my SportPlus SP-HT-1004-iE with IOS app. Additionally the cadence is shown as 0 in the Peleton app.

**To Reproduce**
1. Start bike
2. Open IOS app on phone
3. Open Zwift or Peleton app on iPad
4. Start workout
5. Resistance is not changed.

**Expected behavior**
Resistance should automatically change within the workout.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: IOS 15.4

**Additional context**
Does the current IOS app version include the SportPlus bike? I saw a recent commit adding it.

**Comment by cagnulein** [comment]
hi @Angi2412 i need a debug log to understand the issue. thanks

**Comment by Angi2412** [comment]
Hi @cagnulein,
Here is the log file: [debug-Mi__Mai_18_18_54_12_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8718495/debug-Mi__Mai_18_18_54_12_2022.log). 
I was literally driving up the volcano and it stayed at resistance level 7/26. Also, the heart rate is not shown.
I then installed/compiled the program on my raspberry pi 3 and the auto resistance is working, but the heart rate is still not. Finally, is it possible to use the apple watch and peleton app with my raspberry pi?

**Comment by cagnulein** [comment]
@Angi2412 Ok I will check the log but if you're saying that on a raspberry auto resistance works it could be the case that I added the code in the beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you it

No, Apple Watch is available only on iPhone

**Comment by Angi2412** [comment]
@cagnulein ok, thanks! But is peloton available with raspberry pi? And any idea about why the heart rate is not showing from the bike?

**Comment by Angi2412** [comment]
I tried it now with the iOS beta and peleton. Auto resistance is working in general, but it is much to high:
E.g. instructor says 24 resistance and it automatically sets 24 on my bike but the bike only has 26 resistance in total. Furthermore cadence is only showing 0 in peleton. Here is the log of this short session (
[debug-Mi__Mai_18_22_39_38_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8720852/debug-Mi__Mai_18_22_39_38_2022.log)
).

**Comment by cagnulein** [comment]
about the resistance: so it's the same behavior that you see on the raspberry isn't it? i will scale the resistance to the 100 unit on peloton, no problem.

about the cadence: reset the network settings on your peloton device, i guess it's just a bluetooth cache issue

**Comment by Angi2412** [comment]
> about the resistance: so it's the same behavior that you see on the raspberry isn't it?

Yes, I see the same behaviour as on my raspberry pi. I guess it's this (8138793f0c2c4b844bf2213ca46b78b71affc766) commit from version ~2.10.

> i will scale the resistance to the 100 unit on peloton, no problem.

Thanks, that would be great.

> about the cadence: reset the network settings on your peloton device, i guess it's just a bluetooth cache issue

Ok, I'll try.

**Comment by cagnulein** [comment]
@Angi2412 changes done. If you want you can try to the raspberry in the meanwhile.
What about the HR? Is an HR built in on your bike?

**Comment by Angi2412** [comment]
> @Angi2412 changes done. If you want you can try to the raspberry in the meanwhile

How do I sync with peleton on raspberry pi? I will be able to test on Sunday/Monday.

> What about the HR? Is an HR built in on your bike?

Yes, there is an HR built in, but the heart rate is not propagated.

**Comment by cagnulein** [comment]
> How do I sync with peleton on raspberry pi? I will be able to test on Sunday/Monday.

in the same way as you do on iOS. Which problem do you have?

> Yes, there is an HR built in, but the heart rate is not propagated.

is the HR active in the log that you provided me? I can try to check if i see in the raw data

**Comment by cagnulein** [comment]
> Because there's no way for a sync pop-up to show?

did you add your peloton credentials in the settings on the raspberry?

**Comment by cagnulein** [comment]
> Yes, should be included in the [first log file](https://github.com/cagnulein/qdomyos-zwift/issues/812#issuecomment-1130265988).

do you see the HR on any external app from your bike? I checked the log and there isn't any HR information on it unfortunately so it seems that the bike doesn't send that information on bluetooth

**Comment by cagnulein** [comment]
@Angi2412 any news?

**Comment by Angi2412** [comment]
> @Angi2412 any news?

My bike stopped working and I need to return it. After that I can test the changes🙈

**Comment by cagnulein** [comment]
hah ok :( so sorry to hear this
