### ISSUE TITLE
Proform elliptical Proform HIIT Trainer model # PFEL09915.2

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#817]
![image](https://user-images.githubusercontent.com/48216/170834790-cb273bb7-429d-4d32-b5c4-e3ce3779614f.jpeg)

**Comment by gitoutofhere8** [comment]
Thanks for looking into this!

My estimated resistance mapping to Peloton is 7 =35, 9=40, 12=50, 15=60, 18=70.

**Comment by gitoutofhere8** [comment]
Bonus points if app can connect to Peloton on screen cadence (iOS) and can add 40 rpm.

**Comment by cagnulein** [comment]
@gitoutofhere8 No problem! Are you on iOS or Android? We probably need some version to stabilize it because I will assume that it has the same protocol of other elliptical proform trainers

**Comment by cagnulein** [comment]
> Bonus points if app can connect to Peloton on screen cadence (iOS) and can add 40 rpm.

Do you mean that I have to add 40rpm to the current reading? Even on the qz stats (so they will add to strava too)

**Comment by gitoutofhere8** [comment]
I would run qz on android and Peloton on iOS.  Is that mix compatible?

**Comment by cagnulein** [comment]
> I would run qz on android and Peloton on iOS.  Is that mix compatible?

yes but if you are running on android higher than version 9 you can send to peloton only one metric (cadence or hr, not both at the same time)

**Comment by gitoutofhere8** [comment]
Yes even on qz.  The elliptical/stepper cannot go as fast as a spin bike because of the standing motion and the wheel size.  Looking to map it to something comparable to a spin bike.

**Comment by gitoutofhere8** [comment]
The limitation of one data stream would be ok!

**Comment by cagnulein** [comment]
ah because you would like to simulate a spin bike with this elliptical. makes sense

**Comment by cagnulein** [comment]
@gitoutofhere8 ok good news. I managed it. And I also add 2 new settings in the advances settings called "cadence gain" and "cadence offset" so you will be able to manage the cadence as you wish.
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by marklogan17** [comment]
> @gitoutofhere8 ok good news. I managed it. And I also add 2 new settings in the advances settings called "cadence gain" and "cadence offset" so you will be able to manage the cadence as you wish. send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

Moving fast again @cagnulein :)

**Comment by cagnulein** [comment]
actually I was a little delayed by Ikea :D now @gitoutofhere8 is fighting with google play beta system :)

**Comment by cagnulein** [comment]
[btsnoop_hci (2).log](https://github.com/cagnulein/qdomyos-zwift/files/8799409/btsnoop_hci.2.log)
@gitoutofhere8 perfect! i will check this tomorrow. could you please tell me what did you o in this workout? for example i started from speed 2.0km/h cadence 50, then after 30 seconds....something like this. It will simplify the process. Thanks

**Comment by gitoutofhere8** [comment]
I played the default Ifit class that incremented the incline on auto
resistance from 1 to 2 immediately and then 2 to 3 after about a minute.  I
pushed the cadence into the 70s near the end of the sample.  I only
captured about 90 seconds.

I could take it again at a more controlled level if that would be helpful.

**Comment by cagnulein** [comment]
@gitoutofhere8 thanks, i think it should be enough. i will manage it tomorrow

**Comment by cagnulein** [comment]
@gitoutofhere8 i guess I did almost everything. I'm not sure about 2 things:
- speed: did you get a 4,6 mi/h max during this workout?
- resistance: i handled the reading and I guess also the writing but probably I will need a full resistance change (from res 1 to max (btw which is the max resistance value?)) and back

**Comment by cagnulein** [comment]
perfect thanks, as soon i will receive it, i will build the new beta

**Comment by cagnulein** [comment]
I took a new 2.5 minute sample and played the same iFit class.  Had to launch twice.

The second time I immediately disabled follow instructor (auto resistance).  I started at resistance 1 and incremented +1 every 5 seconds until reached the max of 24.

Interestingly you can't see the speed on any view in the trainer.  I could see it on the iFit app but only in the screen without the instructor.  After the test to resistance 24 I took it down to 9 then to 6.  From 6 I briefly touched 10.8 MPH as the max.
[btsnoop_hci (1).log](https://github.com/cagnulein/qdomyos-zwift/files/8805002/btsnoop_hci.1.log)

**Comment by cagnulein** [comment]
Ok I figured out resistance from the app.  At the end of the log I went from 1 to 24 in +1 increments about 5 seconds apart ending on 24.
[Uploading btsnoop_hci (2).log…]()

**Comment by cagnulein** [comment]
@gitoutofhere8 ok I guess I fixed everything in the 2.10.93
The problem about peloton was that you're the first one that wants to use an Elliptical device with peloton :)
Also be sure that "Treadmill as a Bike" in the Treadmill options is enabled on QZ (I know that it's sound confusing, but in this way you're telling to QZ to transform your elliptical in a bike to peloton) and also that the peloton cadence sensor setting is enabled in the peloton section settings.
I will send you the 2.10.93 later today.
Thanks for all the debug

**Comment by cagnulein** [comment]
Here is the snoop log when iFit is connecting to the trainer without pedaling.
[btsnoop_hci (3).log](https://github.com/cagnulein/qdomyos-zwift/files/8876857/btsnoop_hci.3.log)

**Comment by cagnulein** [comment]
@gitoutofhere8 i added some new frames to the init phase in order to fix the init issue that you saw. Let me know if it will be better with the 2.10.102
Thanks

**Comment by cagnulein** [comment]
[debug-Mon_Jul_11_09_16_38_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9084366/debug-Mon_Jul_11_09_16_38_2022.log)
