### ISSUE TITLE
Xiaomi k12 pro treadmill KS-ST-K12PRO 

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#819]
Scanner On.
Device Scanned.
Connected.
Discovered 1234 Services.
Discovered Characteristics FED7 and FED8 for Service 1234.
Discovered 0000, 0000, and 0000 for Characteristic FED7
Discovered Client Characteristic Configuration for Characteristic FED8
Disconnected.
Connected.
Discovered 1234 Services.
Discovered Characteristics FED7 and FED8 for Service 1234.
Discovered 0000, 0000, and 0000 for Characteristic FED7
Discovered Client Characteristic Configuration for Characteristic FED8
Disconnected.
Scanner Off.
Connected.
Discovered 1234 Services.
Discovered Characteristics FED7 and FED8 for Service 1234.
Discovered 0000, 0000, and 0000 for Characteristic FED7
Discovered Client Characteristic Configuration for Characteristic FED8
Disconnected.
Connected.
Discovered 1234 Services.
Discovered Characteristics FED7 and FED8 for Service 1234.
Discovered 0000, 0000, and 0000 for Characteristic FED7
Discovered Client Characteristic Configuration for Characteristic FED8
Disconnected.
Connected.
Discovered 1234 Services.
Discovered Characteristics FED7 and FED8 for Service 1234.
Discovered 0000, 0000, and 0000 for Characteristic FED7
Discovered Client Characteristic Configuration for Characteristic FED8
Disconnected.
![Image-3](https://user-images.githubusercontent.com/48216/171402197-93dc4673-4eec-4cbb-ba9e-cc86f40fa7be.png)
![Image-2](https://user-images.githubusercontent.com/48216/171402214-26657d6b-6ef4-458f-8652-e94eb8c6fe2a.png)
![Image-1](https://user-images.githubusercontent.com/48216/171402219-c2ea7a28-bee3-4825-b57e-1f650e4c294e.png)
![Image](https://user-images.githubusercontent.com/48216/171402225-0247a71c-ffc0-4cf1-9cb0-efa77c56fc5f.png)

we have a new one @d3m3vilurr :)

**Comment by d3m3vilurr** [comment]
it's not `K12 Pro`. it's `K12 Pro 双模`. I couldn't google detail information. at least it's different device in ksfit official application.
(`K12 Pro` doesn't have BLE filter rule in the app and maybe it only has wifi mode).
and if 7cd0543 patch wouldn't work, it needs more logs of btsnoop to check the encryption table

**Comment by cagnulein** [comment]
yeah, let's see. today i will build the version for the OP

**Comment by cagnulein** [comment]
[debug-Чт_июня_2_12_39_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8822607/debug-._._2_12_39_08_2022.log)
@d3m3vilurr as you imagined, i didn't work. Maybe it's just an issue on the key?

**Comment by cagnulein** [comment]
@d3m3vilurr I asked to the OP about a hci snoof, let's see if he will be able to generate it.

**Comment by d3m3vilurr** [comment]
or we can use `adb logcat | grep KsLogProvider`
it would be easier than capturing btsnoop logs.

and also key seems similar as x21 table but i think it has different point of it.

**Comment by d3m3vilurr** [comment]
I'm not sure, the table could be `ZaCw4FGHIJqLhN+P9RVTU/WcY6ObDdefgEijklmnoMQrsBuvpxXz1yA2t5078KS3=`
(`p` <-> `M`)
but it still needs original dump for cross checking.

**Comment by cagnulein** [comment]
@d3m3vilurr  perfect, the OP is buying an android phone tonight

**Comment by cagnulein** [comment]
[bugreport-dandelion_ru-QP1A.190711.020-2022-06-05-21-55-15.txt](https://github.com/cagnulein/qdomyos-zwift/files/8842222/bugreport-dandelion_ru-QP1A.190711.020-2022-06-05-21-55-15.txt)
@d3m3vilurr i can't see the table here, maybe am I missing something?

**Comment by d3m3vilurr** [comment]
it's not logcat messages.... it's dumpstate message...
i couldn't remember that non-rooting android system support to read full logcat messages or not.
if phone shows empty logcat, an OP should do bt dumping.

**Comment by cagnulein** [comment]
Let's see if the OP can do it ;)
