### ISSUE TITLE
Clear stats button

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#82]
Add a button to clear the stats for the current session

**Comment by fooeynet** [comment]
This can be accomplished now via Stop/Start, no?

**Comment by cagnulein** [comment]
Yes. Does it work for.you?

Il mer 3 mar 2021, 00:58 fooeynet <notifications@github.com> ha scritto:

**Comment by fooeynet** [comment]
Yes, that works for me.  I didn't know if the original request was for a specific "reset/clear" button or not.
