### ISSUE TITLE
[REQ] Merach U3 Pro-Y

### ISSUE THREAD

**Issue by z2i** [cagnulein/qdomyos-zwift#820]
I've got one nice home treadmill called [Merach U3 Pro-Y](https://www.merach.com/prodetails/175.html).
It supports FTMS and could be connected to Zwift and any other app to read treadmill speed and other info.

I've searched for some app that will allow me to automatically (or manually from the app UI) control speed and incline of this treadmill.
Example: create custom run workouts in Zwift (or other app that allows to create custom programs) and to run on a treadmill according to this workout.
It's like running using programs predefined inside a treadmill, but gaining an ability to create your own custom.

Could you please create a profile for this treadmill Merach U3 Pro-Y for qdomyos-zwift app for android/iOS?

You can find nRF connect log attached.
[Log 2022-06-02 17_42_26.txt](https://github.com/cagnulein/qdomyos-zwift/files/8826433/Log.2022-06-02.17_42_26.txt)

Thank you in advance

**Comment by cagnulein** [comment]
thanks! i will try to do it in this weekend.

**Comment by cagnulein** [comment]
done! @z2i 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS so I will send you the beta. Thanks

**Comment by z2i** [comment]
Thnx!
v2.10.71 installed
But unfortunately the app doesn't see the treadmill.
In bluetooth settings the treadmill is shown as MERACH-U3-000B68, if it is important.

**Comment by cagnulein** [comment]
2.10.71 is not the latest one. is your google play account the same of your email?

**Comment by z2i** [comment]
Managed to get v2.10.96.
The app found and connected to treadmill successfully.
It can read info from the treadmill, but, unfortunately, speed and incline (red boxed on image) cannot be changed.
Probably it is something with the treadmill itself, or it needs other control sequences to be sent.
![2022-06-03 20 45 36](https://user-images.githubusercontent.com/20382621/171921442-f8272292-9de2-4b43-b459-03429a586b9f.jpg)

In nRf connect, Fitness Machine Control Point shows 'WRITE" properties:
![2022-06-03 20 48 28](https://user-images.githubusercontent.com/20382621/171921771-7ec89bce-b736-4287-8bae-c21c962fe500.jpg)

**Comment by cagnulein** [comment]
Probably is something in the control mechanism, send me a debug log while you're trying to change speed and incline via qz in this way https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Let me know

**Comment by z2i** [comment]
Yep, of course
- Enabled logging
- Powered on the treadmill
- Run the app
- Pressed Start a few times
- Started treadmill manually
- Pressed +/- a few times for speed and incline
[debug-Fri_Jun_3_22_18_20_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8835184/debug-Fri_Jun_3_22_18_20_2022.log)

**Comment by cagnulein** [comment]
@z2i Thanks I will check this tomorrow

**Comment by cagnulein** [comment]
@z2i mmm it seems everything right. I did a new modification in the newest version: i tried to use the same technogym treadmill profile for yours. Let's see if it's better. Let me know. You should see an update in a 2-3 hours.

**Comment by z2i** [comment]
Thank you.
On v2.10.97 it doesn't even show info from the treadmill.
So, it was better on v2.10.96.
The interesting thing is that 'START' button blinking red. It was also the same on 2.10.96, but if I started treadmill manually it was also started in the app.
![2022-06-04 14 48 41](https://user-images.githubusercontent.com/20382621/172013661-2624a774-e1a0-4311-a7a0-af7a3fa3aa2b.jpg)

Maybe there is some kind of a lock on controlling treadmill.
I will contact manufacturer to ask if there are any locks and how it can be controlled via FTMS.

[debug-Sat_Jun_4_14_47_12_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8838196/debug-Sat_Jun_4_14_47_12_2022.log)
[debug-Sat_Jun_4_14_48_46_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8838194/debug-Sat_Jun_4_14_48_46_2022.log)
[debug-Sat_Jun_4_14_49_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8838195/debug-Sat_Jun_4_14_49_11_2022.log)

**Comment by cagnulein** [comment]
if with the previous you read the metrics i definitely did something wrong in this one. i will double check it. it's a good sign the start and stop works means that we should be on the right path
i will check this later today

**Comment by z2i** [comment]
oh, sorry for confusion:
'but if I started treadmill manually it was ALSO STARTED COUNTING TIME in the app ON 2.10.96'.
So, unfortunately I couldn't start/stop the treadmill in 96 and 97, could read data from treadmill on 96 and not on 97.
Sorry once again.

I've contacted manufacturer for possible workarounds on controlling matter. Will wait for their reply.

**Comment by cagnulein** [comment]
hah ok, now i reverted the changes. Let's see if the manufacturer will help about this! Let me know!
