### ISSUE TITLE
Doubling Power Option for separate power sensors.

### ISSUE THREAD

**Issue by liftoff1968** [cagnulein/qdomyos-zwift#822]
In Power Sensor Options is an option 'Doubling Cadence for Run'. Is it possible to add an option 'Doubling Power' ?

**Comment by cagnulein** [comment]
i was thinking that you can use already the watt gain with 2.0 :)

**Comment by liftoff1968** [comment]
Documentation says:
Watt Gain (max value 1.25)
:-)

**Comment by cagnulein** [comment]
it's old date:) you can use whatever value you want . the update guide in on facebook, the @janabouc pdf ;)

**Comment by liftoff1968** [comment]
Ok. i will try it.

**Comment by liftoff1968** [comment]
With gain 2 it doubles the power 2 times. 

Fr. Juni 3 19:43:44 2022 1654278224810 Debug: /Users/cagnulein/qdomyos-zwift/src/metric.cpp void metric::setValue(double) "watt value was " 40 "but it will be transformed to" 80
Fr. Juni 3 19:43:44 2022 1654278224811 Debug: /Users/cagnulein/qdomyos-zwift/src/metric.cpp void metric::setValue(double) "watt value was " 80 "but it will be transformed to" 160

[debug-Fr__Juni_3_19_42_34_2022_GAIN_1.log](https://github.com/cagnulein/qdomyos-zwift/files/8834944/debug-Fr__Juni_3_19_42_34_2022_GAIN_1.log)
[debug-Fr__Juni_3_19_43_30_2022_GAIN_2.log](https://github.com/cagnulein/qdomyos-zwift/files/8834946/debug-Fr__Juni_3_19_43_30_2022_GAIN_2.log)
0

**Comment by cagnulein** [comment]
Hah I know where the issue is, doubling on assioma profile and also In renpho bike profile. I will fix it tomorrow, thanks

**Comment by cagnulein** [comment]
fixed, i will send you a new version later today

**Comment by liftoff1968** [comment]
Doesn't work. 
Doubling power option on the pedals is off and watt gain is set to 2.
[debug-Di__Juni_7_19_28_18_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8858400/debug-Di__Juni_7_19_28_18_2022.log)

**Comment by cagnulein** [comment]
@liftoff1968 is this ok?

**Comment by liftoff1968** [comment]
I'll tested it asap.

**Comment by cagnulein** [comment]
@liftoff1968 is it ok?
