### ISSUE TITLE
qmake error on raspberry

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#823]
Now there is an error and make won't work:
jonathan@jonathan-desktop:~/qdomyos-zwift/src$ qmake
Info: creating stash file /home/jonathan/qdomyos-zwift/src/.qmake.stash
Project ERROR: Unknown module(s) in QT: texttospeech

Is there a new dependency to install? I tried relate qtspeech things and I seemed to have something already installed.
Thanks,
Jonathan

**Comment by cagnulein** [comment]
yes libqt5texttospeech5-dev and libqt5texttospeech5

let me know

**Comment by jonathancolledge** [comment]
Ah, Github had stopped notifying me of responses, so I've only just seen your reply. Thank you, I will try in the morning!

**Comment by jonathancolledge** [comment]
Works!

**Comment by shoulih** [comment]
cloned the latest source from Master and install all the dependencies on pi3 running the Bullseye:
sudo apt install git qtquickcontrols2-5-dev libqt5bluetooth5 libqt5widgets5 libqt5positioning5 libqt5xml5 qtconnectivity5-dev qtpositioning5-dev libqt5charts5-dev libqt5charts5 qt5-assistant libqt5networkauth5-dev libqt5websockets5-dev qml-module* libqt5texttospeech5-dev libqt5texttospeech5

Got the following qmake waring:

![image](https://user-images.githubusercontent.com/66762397/174655083-d1d33f31-d0d0-4904-888f-92b0f351f30c.png)

can I ignore it and compile?

Thanks!

**Comment by cagnulein** [comment]
@shoulih Do a make clean first

**Comment by shoulih** [comment]
ok
