### ISSUE TITLE
trouble connecting qzwindows to other devices than bikes like echelon and sending info to Zwift on my PC

### ISSUE THREAD

**Issue by gewahr** [cagnulein/qdomyos-zwift#825]
Hi Roberto . trying to connect all my devices to zwift and QZ on my windows computer to be able to use one device
Echelon EX-3 is recognised and info sent to zwift. Works perfectly

Nordictrack F5si shows but doesnt seems to control the bluetooth of the elliptical as no blue light shows contrary to when i control it through my phone or tablet either in android or IOS

Concept 2 PM5 rower doesnt work at all  ( should be compatible with QZ)  ... no info sent to zwift on my PC . The only way to make it work is through an app called rowedbiker on my phone and it shows it zwift as my phone

any ideas on what to do ?
thanks.

**Comment by cagnulein** [comment]
hi @gewahr i need the debug logs for all the issue that you have. It's the only way to understand them. Thanks
Just a question: did you connect them into the bluetooth settings on Windows first?

**Comment by gewahr** [comment]
yes i connected them in the bluetooth settings on windows first. will get
back to you with the debug files. thanks

Le mar. 7 juin 2022 à 02:22, Roberto Viola ***@***.***> a
écrit :

**Comment by gewahr** [comment]
here are the debug files anyway. First one is with PM5, second with Fs5
[debug-mar__juin_7_08_18_10_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8853184/debug-mar__juin_7_08_18_10_2022.log)
[debug-mar__juin_7_08_21_14_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8853185/debug-mar__juin_7_08_21_14_2022.log)
i

**Comment by cagnulein** [comment]
@gewahr PM5 is not working because QZ also finds the treadmill. You have to put the PM5 as a manual device in the advanced setting

**Comment by gewahr** [comment]
Manual connection for the treadmill fs5i and the rower concept 2 PM5 do not work ; they do not show in the list of manual devices . Only the echelon EX3 bike shows.
All 3 devices are approved for a connection to the windows computer.
txs
![20220607_182937](https://user-images.githubusercontent.com/98962725/172494697-095a0465-d035-4dfd-8458-b2f5599cc5b5.jpg)

**Comment by cagnulein** [comment]
can you try to remove the pairing from windows of the devices that you don't want to use. for example removing echelon and i_fs if you want to use the rower
Just a guess to understand why it's not populating the manual device combo box

**Comment by gewahr** [comment]
It is like the renew devices button does not work
If I unpair all devices and connect the rower , the connection is established but no data is sent to QZ
I i do the same for the treadmill, data is sent but when i connect to zwift the data is not renewed so my speed and cadence stay the same at for exemple 1 km/h ( starting speed) and cadence of 41.
the longest debug log is for the treadmil
[debug-mer__juin_8_06_34_42_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8860890/debug-mer__juin_8_06_34_42_2022.log)
[debug-mer__juin_8_06_40_21_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8860891/debug-mer__juin_8_06_40_21_2022.log)
l

**Comment by cagnulein** [comment]
hi @gewahr for the rower the main issue is:

 Unable to set value for descriptor "{00002902-0000-1000-8000-00805f9b34fb}" for characteristic "{00002a05-0000-1000-8000-00805f9b34fb}" of the service "{00001801-0000-1000-8000-00805f9b34fb}" : "Accès refusé."

So the rower is denying the qz connection. I don't know if I can do something about it. Is it deterministic?

for your treadmill instead I guess you just need to enable the setting for your treadmill as you do on the mobile version "nordictrack_fs5i_treadmill"

Let me know

**Comment by gewahr** [comment]
the rower connect easily to QZ on my android phone and sends all the info to QZ android. Why would the rower deny connection to QZ windows ?? Any idea 
Here is the debug files on my phone
[debug-Wed_Jun_8_22_31_40_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8866335/debug-Wed_Jun_8_22_31_40_2022.log)

**Comment by cagnulein** [comment]
ok @gewahr good news! I guess I found the reason of the issue. The new windows version is building, you can find it here https://github.com/cagnulein/qdomyos-zwift/actions/runs/2466792141 when the build is complete. Let me know

**Comment by cagnulein** [comment]
@gewahr are we ok with this?
