### ISSUE TITLE
QZ not recognising Garmin speed sensor 2

### ISSUE THREAD

**Issue by DamianBa** [cagnulein/qdomyos-zwift#826]
Reminder: 
using QZ to transpose output from Garmin speed sensor 2 into Zwift run as a treadmill. 

QZ not recognising the Bluetooth output from the sensor. 

[debug-Tue_Jun_7_15_53_32_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8854347/debug-Tue_Jun_7_15_53_32_2022.log)

**Comment by DamianBa** [comment]
Thanks - I'll try again.

Perhaps the revolutions from an elliptical might be too slow for a cycle
speed sensor to register - I have ordered a cadence sensor as well, which
should arrive in the next few days, and I'll try that when it comes.

Thanks again.

Damian

**Comment by DamianBa** [comment]
The sensor is definitely sending - tested on bike wheel connected to Garmin bike computer yesterday. 

Here’s a new debug log from this morning - switched off Garmin beforehand. 

[debug-Wed_Jun_8_08_48_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8859476/debug-Wed_Jun_8_08_48_08_2022.log)

**Comment by cagnulein** [comment]
@DamianBa now you connected as a cadence sensor on QZ. You should only use power sensor for this purpose. Anyway I don't see any bluetooth data (I see the devices and QZ is connected to it, but the sensor is not sending any information on the characteristics). I guess on your garmin device you're getting them by ANT+. Please use nrfconnect app on the phone in order to double check that you can get the metrics by bluetooth or just wait for the cadence sensor

**Comment by DamianBa** [comment]
Thanks - I have downloaded nrfconnect and it connected to the speed sensor
2 through BLE fine.  I've sent a log to GitHub but not sure if that
contains what you need.

I'd really like to get this sorted, and from your perspective, you'd be
able to say that QZ recognises Garmin sensors which allow dumb ellipticals
and cross trainers to join Zwift Run.  Seems a big gap in the market from
my research to date.

Thanks again for your help.

Damian

**Comment by cagnulein** [comment]
Hi @DamianBa very busy day. yes i checked the log but you don't try to subscribe to the cadence notification in order to see if you see the metrics coming in.

You can subscribe to the notification pressing the 3 downs arrow ![image](https://user-images.githubusercontent.com/48216/172665847-01a3f07c-97ae-4745-9237-4e51694d836a.jpeg)

maybe the best way is recording a video of your nrfconnect session so i can see it 

you have to subscribe to the cadence characteristics 

let me know

**Comment by DamianBa** [comment]
Done that but not sure what I’m looking at

Also wondered if it might be something to do with this issue

https://forums.garmin.com/sports-fitness/cycling/f/accessories-sensors/218973/speed-and-cadence-sensor-2-not-transmitting-data-over-bluetooth

**Comment by DamianBa** [comment]
PS I have a Windows PC and an Apple MacBook as alternatives.

**Comment by cagnulein** [comment]
@DamianBa i can't see the video, you have to attach directly on github thanks

**Comment by cagnulein** [comment]
windows version is here https://github.com/cagnulein/qdomyos-zwift/releases/tag/2.10.89
remember to pair the sensor on windows before opening qz

**Comment by DamianBa** [comment]
thanks - did that but no luck.  Cannot find the debug log - if you tell me where it is I'll add it here.

**Comment by DamianBa** [comment]
Hi - the Windows PC paired with the sensor but didn't see any data.

I've run the debug logger, but cannot see where the debug log is saved in
the windows PC

**Comment by cagnulein** [comment]
the debug log should be in the same folder where the executable is if you enabled the debug log in the experimental settings

**Comment by cagnulein** [comment]
ok so just copy and paste the shell log. Now i'm going to bed. Have a nice
evening

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 8 giu 2022 alle ore 23:05 DamianBa ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@DamianBa are you able to provide me the video of the nrfconnect as I requested here https://github.com/cagnulein/qdomyos-zwift/issues/826#issuecomment-1150120471

**Comment by cagnulein** [comment]
@DamianBa the video that I need it was about the 0:18 of the first video. You subscribed correctly to the CSC measurement but as you can see the VALUE still to N/A. There you should see a value while you're running. Could you please try when you have time?
Also do you have a garmin app for this sensor? maybe there is some settings to enable the BLE on this sensor?
did the cadence sensor arrive?

**Comment by cagnulein** [comment]
Ok no problem, we will catch up Saturday! Have a nice day!

**Comment by DamianBa** [comment]
Hello. Happy weekend. Hope you have some great plans. 

Not urgent but when you have a minute perhaps look at this and tell me what I’m doing wrong. Got a new cadence sensor and the iPhone saw something briefly then I must have changed a setting so it doesn’t come through any more. 

[debug-Fri_Jun_10_18_38_16_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8881027/debug-Fri_Jun_10_18_38_16_2022.log)

**Comment by DamianBa** [comment]
Nrf video 
https://photos.app.goo.gl/r9so6d4XSy1U45BS6

**Comment by cagnulein** [comment]
> Nrf video https://photos.app.goo.gl/r9so6d4XSy1U45BS6

<img width="528" alt="Screenshot 2022-06-10 at 21 26 32" src="https://user-images.githubusercontent.com/48216/173136414-1008f2da-9bc8-4bc2-9046-05785a01dd49.png">
you should focus on this. click the 3 arrows icon here and stay here while you're riding. we need to see something moves here.
almost 10pm here, i will back to you tomorrow.
I have an idea about this
R.

**Comment by DamianBa** [comment]
Hi

Found an old Android phone and got qz on that. 

Qz now recognizing the cadence sensor but I cannot work out how to transpose it to Zwift running - it won't recognize it as a power sensor. 

Debug log 
[debug-Sat_Jun_11_11_13_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8883669/debug-Sat_Jun_11_11_13_15_2022.log)

![Screenshot_20220611-113157](https://user-images.githubusercontent.com/106930642/173184286-5810aaaa-95ab-43cc-900c-aa38ebd36139.png)

**Comment by DamianBa** [comment]
[debug-Sat_Jun_11_11_38_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8883677/debug-Sat_Jun_11_11_38_30_2022.log)

**Comment by DamianBa** [comment]
[debug-Sat_Jun_11_11_37_49_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8883682/debug-Sat_Jun_11_11_37_49_2022.log)

**Comment by cagnulein** [comment]
ok thanks @DamianBa today is a very rough day, i will try my best to check this today/tomorrow

**Comment by DamianBa** [comment]
No problems. No rush.

**Comment by cagnulein** [comment]
> Hi
> 
> Found an old Android phone and got qz on that.
> 
> Qz now recognizing the cadence sensor but I cannot work out how to transpose it to Zwift running - it won't recognize it as a power sensor.
> 
> Debug log [debug-Sat_Jun_11_11_13_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8883669/debug-Sat_Jun_11_11_13_15_2022.log)
> 

here I can see the device connected to QZ but you connected as a cadence sensor instead of the power sensor. Please redo this disabling the cadence sensor anb put in the power sensor and also power sensor as a treadmill.
Report the new debug log while you do a little of running even if you don't see anything on the tiles.
Thanks

**Comment by DamianBa** [comment]
[debug-Sat_Jun_11_17_20_45_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8884345/debug-Sat_Jun_11_17_20_45_2022.log)

**Comment by cagnulein** [comment]
Perfect! I have to do a small fix but I guess this one is working. I will try to do tomorrow

**Comment by DamianBa** [comment]
Fine. No probs. Whenever it works for you.

D

**Comment by cagnulein** [comment]
modification done!

**Comment by DamianBa** [comment]
Ok thanks. I'll check it out

**Comment by DamianBa** [comment]
It won't get past the connecting screen. 
[debug-Sun_Jun_12_11_05_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8885606/debug-Sun_Jun_12_11_05_41_2022.log)
![Screenshot_20220612-110559](https://user-images.githubusercontent.com/106930642/173228242-728200d0-af16-400b-9485-993290a72df9.png)

**Comment by cagnulein** [comment]
@DamianBa you have the "fake elliptical" turned on in the experimental settings. Turn it off and restart QZ.

**Comment by cagnulein** [comment]
@DamianBa also, when you will see the cadence, you will have to chaneg the cadence-speed ratio in the cadence senor setting (cadence ratio)

**Comment by DamianBa** [comment]
Ok. Must be getting there now.

 Didn't see anything on the tiles but there's z1 on the graph. 

[debug-Sun_Jun_12_13_46_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8885845/debug-Sun_Jun_12_13_46_11_2022.log)

**Comment by cagnulein** [comment]
i see the connection but not the metric as yesterday. did you try to run? try to check with nrfconnect first that it still working and then give a try again with qz
let me know

**Comment by DamianBa** [comment]
[debug-Sun_Jun_12_13_46_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8885861/debug-Sun_Jun_12_13_46_11_2022.log)

Must be getting there now  but Nothing on the tiles and won't run in Zwift.

**Comment by cagnulein** [comment]
nope no metrics as before. please try again with nrfconnect to be sure

**Comment by cagnulein** [comment]
any news @DamianBa ? another user confirmed that the patch is working for him
let me know

**Comment by DamianBa** [comment]
[debug-Mon_Jun_20_20_26_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8943205/debug-Mon_Jun_20_20_26_50_2022.log)

**Comment by DamianBa** [comment]
Can't see it in Zwift and no register in the Android app

**Comment by DamianBa** [comment]
[Log 2022-06-20 20_44_39.txt](https://github.com/cagnulein/qdomyos-zwift/files/8943271/Log.2022-06-20.20_44_39.txt)

**Comment by DamianBa** [comment]
Nrf connect log above. Can't see how to record screen on this old Android phone

**Comment by cagnulein** [comment]
> [debug-Mon_Jun_20_20_26_50_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8943205/debug-Mon_Jun_20_20_26_50_2022.log)
> 
> 

Hi @DamianBa in this log there is nothing at all. Did you let it run for at least 1 minute? Are you sure Bluetooth is working on this device?

**Comment by cagnulein** [comment]
@DamianBa any news?

**Comment by DamianBa** [comment]
Hi

I tried briefly on Nrf connect and it failed to pass data so I gave up. I’m
in London today so earliest I can try again is this evening.

Regards

Damian

**Comment by cagnulein** [comment]
ok no problem, it's strange that I received this message only today since June :O maybe a github issue?

**Comment by DamianBa** [comment]
v strange - I've not logged in since June.  Hope you are well.  

Please do let me know if you ever fix the Garmin cadence sensor on dumb cross trainer issue - I'm still interested, but it wouldn't recognise iPhone and I don't have any recent Android devices, so it was too painful to debug.

Regards

Damian

**Comment by cagnulein** [comment]
Unfortunately no, I was waiting for you :( but as I said in the past month we need a nrfconnect trace so if you can't see on the iphone I guess we are on a dead road :(

**Comment by DamianBa** [comment]
Hi.

I’m struggling with the set up. The iPhones don’t seem to register the
cadence sensor  and I only have a really old android phone which won’t
charge properly.

Do you have a laptop beta version which I could try please?

Thanks

Damian

**Comment by cagnulein** [comment]
yes @DamianBa you can download if from here https://github.com/cagnulein/qdomyos-zwift/suites/8703627865/artifacts/392962876

first login to github then download it. You have to pair the cadence sensor first on your bluetooth settings on windows.
Let me know

**Comment by DamianBa** [comment]
I think something is wrong with GitHub - I didn't send you this request today (but had sent it in July).  I might try it again in any case but it was difficult last time.

**Comment by cagnulein** [comment]
yes i thought the same :)
anyway if you need help i'm here :)
