### ISSUE TITLE
QZ program self-calculates calorie burn [REQ]

### ISSUE THREAD

**Issue by tuffdadsf** [cagnulein/qdomyos-zwift#830]
I was told this is something that can be done but needed it's own ticket so it can get done.

QZ should be able to calculate the calorie burn based on HR and possibly using the sex, age, and weight of the person to fine tune it?

I also read an article saying this could be a good way to calculate it:
https://www.businessinsider.com/how-to-calculate-calories-burned-exercise-met-value-2017-8#

and

https://sites.google.com/site/compendiumofphysicalactivities/

codes|METS|Activity
01015 | 7.5 | bicycling, general

**Comment by cagnulein** [comment]
already done @tuffdadsf this morning https://github.com/cagnulein/qdomyos-zwift/commit/1418067957dbf2b6f162cfc90804654640ce88d7 :)

**Comment by tuffdadsf** [comment]
Holy crap! That is great! Thanks and I'm looking forward to trying it out

**Comment by tuffdadsf** [comment]
Looking at the code - is the weight only in kg or does it make the conversion of people who set their weight in lbs., or should we put our weight in kg in QZ settings?

**Comment by cagnulein** [comment]
@tuffdadsf it's already converted on the up layer ;)

**Comment by cagnulein** [comment]
QZ is all Metric insde

**Comment by tuffdadsf** [comment]
Cool - I thought you probably took that into consideration. Great job!
