### ISSUE TITLE
Life fitness t5 

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#834]
![Screenshot_20220613_112619_no nordicsemi android mcp](https://user-images.githubusercontent.com/48216/173352838-6573df16-a191-4e33-887a-0775b0552fa5.jpg)

**Comment by cagnulein** [comment]
@pinkpopgirlsdad In this debug log the tape was running? If so at which speed? And which incline?
Thanks

**Comment by cagnulein** [comment]
@pinkpopgirlsdad in the log I can parse a 3 km/h speed and then a 2.5km/h speed; inclination 3 then 2. Is it right?

`" << 19 53 cb 1a 21 06 00 00 **fa 00** 34 03 00 00 00 46 00 **02** 00 00"`
first speed, second incline (for my reference)

let me know if they are right

**Comment by pinkpopgirlsdad** [comment]
Sounds right. I can do it again later on if you want to make sure.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
done @pinkpopgirlsdad i'm uploading the new version. When will you be able to try?

**Comment by pinkpopgirlsdad** [comment]
Say in 40 mins

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
ok should be online any minute, check the play store ;)

**Comment by pinkpopgirlsdad** [comment]
Not updated yet. Will try again in about an hour

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pinkpopgirlsdad** [comment]
Hi, Google play hasn't got the update yet, so will try later on.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
yeah today they are slow, sometimes happens:(
Il 14 giu 2022, 13:01 +0200, pinkpopgirlsdad ***@***.***>, ha scritto:

**Comment by cagnulein** [comment]
it's live now

**Comment by pinkpopgirlsdad** [comment]
Didn't work, incline was 1.5% speed 2.5 then I increased it. 
[debug-Tue_Jun_14_14_01_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8900023/debug-Tue_Jun_14_14_01_08_2022.log)

**Comment by cagnulein** [comment]
it worked but there is a glitch! i'm fixing it

**Comment by cagnulein** [comment]
@pinkpopgirlsdad the speed is ok but i don't see the inclination in the log. could you please generate a log where you go from 0 to max inclination and reverse?
Thanks

**Comment by pinkpopgirlsdad** [comment]
Speed 2.5 incline 0 to 15% and down
[debug-Tue_Jun_14_14_41_38_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8900317/debug-Tue_Jun_14_14_41_38_2022.log)

**Comment by cagnulein** [comment]
in the meanwhile, do you see the virtual device on zwift even if the speed is 0 of course?

**Comment by cagnulein** [comment]
@pinkpopgirlsdad uploaded the new version

**Comment by pinkpopgirlsdad** [comment]
Yes zwift connects to phone with 0km/h

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
@pinkpopgirlsdad New update is live!

**Comment by pinkpopgirlsdad** [comment]
Thanks I'll test it in the morning

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pinkpopgirlsdad** [comment]
Getting closer. Qz recognised the speed and incline but then when I connected zwift the speed wasn't updated. Even though zwift was paired to my phone no speed was seen.  Zwift did complain on a connection failure but as you can see it was paired. When pairing tm was at 2.5km/h and that didn't seem to be picked up. I'm using apple tv to run zwift.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pinkpopgirlsdad** [comment]
![IMG_20220615_092820](https://user-images.githubusercontent.com/82227044/173789125-6ccafadf-0f8d-4b87-9f1f-cae3dc4d2628.jpg)
![IMG_20220615_092723](https://user-images.githubusercontent.com/82227044/173789171-5398ce38-201f-470e-9c99-0f24e7d14072.jpg)
![Uploading IMG_20220615_092640.jpg…]()

**Comment by pinkpopgirlsdad** [comment]
You can see the run speed was 0. Anyway I'll rename my phone

**Comment by cagnulein** [comment]
yes but the connect failure is the issue. Try to rename it, trust me :)

**Comment by pinkpopgirlsdad** [comment]
OK so connected to run but still no speed even though tm was on 2km/hr. No connection failure now. 
![IMG_20220615_104523](https://user-images.githubusercontent.com/82227044/173798819-09ce1333-ec98-40d9-9f81-e777eb231a2f.jpg)
You can see on pairing screen paired OK but no speed detected

**Comment by cagnulein** [comment]
send me a fresh debug log just to be sure. Thanks 
In the meantime, try with a different device for zwift, just to double check if it's a bluetooth cache issue on the apple tv.

**Comment by cagnulein** [comment]
#579 same as this device probably (info for me)

**Comment by cagnulein** [comment]
do you see the wahoo direct connect from zwift? if it's a bluetooth issue you can use that one

**Comment by cagnulein** [comment]
try to use that one instead
Il 15 giu 2022, 17:07 +0200, pinkpopgirlsdad ***@***.***>, ha scritto:

**Comment by cagnulein** [comment]
Yes the flow is correct and no, you have to stay in the meet up as far as I remember, but you can try
