### ISSUE TITLE
Polar HR9 Heart rate issues..

### ISSUE THREAD

**Issue by Qdomyos1978** [cagnulein/qdomyos-zwift#835]
Having issues with Polar HR9.
It can connect to qdomyos OK only, by not send the data to Zwift.
Also doesn't work stand alone.

**Comment by Qdomyos1978** [comment]
Tried to attach file.

**Comment by Qdomyos1978** [comment]
As it doesn't work to attach it here, can I js email it to you?
I've selected it but it never attachs, maybe it's expecting a picture.

**Comment by cagnulein** [comment]
send me an email to roberto.viola83 at gmail.com indicating this ticket

**Comment by Qdomyos1978** [comment]
I tried via email!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Qdomyos1978** [comment]
Hi
Yes this an issue with the HR9 heartrate monitor.
You can make it work with Zwift, it seems it only stays "on" for approximately 30 seconds after you wet it!
So, I get my cycling stuff on and phones ready, get on the bike, open Qdomyos, pu bike on open Zwift and get it in pairing mode, do the first one, then get it pairing on heartrate. Also make sure companion is ready.
Then get out of the garage, go and wet the sensor (only cold tapwater works) and immediately get back on the bike. If I am quick enough then Zwift can see it!



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cagnulein** [comment]
ok so i'm closing this! thanks !
