### ISSUE TITLE
Bundling example workouts with QZ

### ISSUE THREAD

**Issue by jonathancolledge** [cagnulein/qdomyos-zwift#839]
I was thinking about the problems of distributing videos, but one totally unrelated thing I thought was that workouts take up no space so these could be easily bundled if you are interested. I have a few workouts all my own with no copying from others, so no copyright issues.

I have attached a zip file and you are welcome to include these with QZ if you think they are appropriate.

They are all ZWO with no ramps. My originals had ramps, but there is no training benefit apart from looking prettier. The ramps weren't compatible with all apps.

They have some references to scientific papers. Also, there are tags and a description for each. The tags may help to sort in the future and I hope the descriptions are helpful.

[ZWO workouts to send to Roberto.zip](https://github.com/cagnulein/qdomyos-zwift/files/8934118/ZWO.workouts.to.send.to.Roberto.zip)
.

**Comment by jonathancolledge** [comment]
I forgot to say one of my workouts is 7th out of 2984 in popularity on TrainerDay! (Opensource repository that used to be ErgDb). That's quite good when you consider that some of the erg workouts on there are copies from Zwift and the like.

**Comment by cagnulein** [comment]
I love the idea! With Brad we already thought about this!
I will add ASAP, thanks!
I have to think where I can show the tags to the user. Any idea?

**Comment by jonathancolledge** [comment]
For tags, I think when you import the directory of files, maybe you could have a filter box?

I haven't added time to my tags, a filter for that would be really useful. Would adding as a tag be easier or harder than calculating from the zwo file? I was going to add some sort of time description, but haven't decided on a format.

**Comment by cagnulein** [comment]
i think the actual ZWO open window should be redisigned in order to show a little chart about the workout and the tag. Not the end of the world, but it needs to be done first. What do you think?

**Comment by cagnulein** [comment]
@jonathancolledge maybe we can integrate this project somehow https://github.com/breiko83/zwo-editor

**Comment by jonathancolledge** [comment]
> i think the actual ZWO open window should be redisigned in order to show a little chart about the workout and the tag. Not the end of the world, but it needs to be done first. What do you think?

Yes, I think that'd be great!

**Comment by cagnulein** [comment]
@jonathancolledge already started :) I will show you a very alpha version in a couple of hours ;)

**Comment by jonathancolledge** [comment]
> @jonathancolledge maybe we can integrate this project somehow https://github.com/breiko83/zwo-editor

Yes to that too, but it doesn't cope well with a small screen!

**Comment by cagnulein** [comment]
@jonathancolledge very very alpha version 
![image](https://user-images.githubusercontent.com/48216/174602569-b6062ba2-57d6-4a27-b95e-3f5c42e108a2.png)

**Comment by cagnulein** [comment]
@jonathancolledge description and tags added! now it's time to filter. But first let's post this on the group to great some exciment :D
![image](https://user-images.githubusercontent.com/48216/174628784-cec50630-2ee2-4c17-a337-57d9ca0dfa6b.png)

**Comment by cagnulein** [comment]
@jonathancolledge i have also this list of zwo that we can add maybe renaming them somehow 
They are from zwift mainly

**Comment by jonathancolledge** [comment]
I think Zwift and Trainer Road have confirmed they don't like their workouts being used if people have no subscription active. TrainerDay which used to be ErgDb has many open source workouts, but I think care would be needed there as some of the contributors have used TrainerRoad and Zwift workouts. Another place that has a few is Trainerdb https://trainerdb-84bdb.firebaseapp.com/listplan

Finally, what might be better is if people have done some rides they like or even iconic rides or races, then the gpx could be used to create a ZWO workout based on the ride or race by using this: https://whatsonzwift.com/gpx-to-zwift-workout

So we could collect some crit races, or hill climbs, or hill repeats, and so on from rides on Strava. There would be no copyright issues there and people could use them to train for things they want to do. I'll start looking for some tomorrow (if a new baby let's me sleep!). I already have a good sprint set I can use. And a good set of VO2max hill climb repeats, and some anaerobic hill climb repeats too.

**Comment by cagnulein** [comment]
> I think Zwift and Trainer Road have confirmed they don't like their workouts being used if people have no subscription active. 

Yeah you're totally right about this.

> TrainerDay which used to be ErgDb has many open source workouts, but I think care would be needed there as some of the contributors have used TrainerRoad and Zwift workouts. Another place that has a few is Trainerdb https://trainerdb-84bdb.firebaseapp.com/listplan

I didn't know this, I will take a look 

> Finally, what might be better is if people have done some rides they like or even iconic rides or races, then the gpx could be used to create a ZWO workout based on the ride or race by using this: https://whatsonzwift.com/gpx-to-zwift-workout

I love the idea,but probably we can just bundling the gpx from strava epic segments using what I already did for Cesium (even if the users don't want to see the 3d maps they can have the workout following the gpx and the strava map at the end of the workout!)

> So we could collect some crit races, or hill climbs, or hill repeats, and so on from rides on Strava. There would be no copyright issues there and people could use them to train for things they want to do. I'll start looking for some tomorrow (if a new baby let's me sleep!). 

Oh wow did you have a new baby?

> I already have a good sprint set I can use. And a good set of VO2max hill climb repeats, and some anaerobic hill climb repeats too.

Great!

**Comment by jonathancolledge** [comment]
_Oh wow did you have a new baby?

Not yet, maybe in a few hours!

**Comment by cagnulein** [comment]
Oh wow! I'm so excited for you! My wife is also pregnant, she should born on August

**Comment by cagnulein** [comment]
text box filter added on top. Ready to merge to master in order to test it
![image](https://user-images.githubusercontent.com/48216/174749193-90ecc5fb-bcbd-4148-bc4d-8387020a4383.png)

**Comment by jonathancolledge** [comment]
> Oh wow! I'm so excited for you! My wife is also pregnant, she should born on August 

Congratulations to you and your wife too.

Latest screenshot looks great. Can it filter on tags too? No problem if not, I think using sensible names for the filename/title will work well for filtering.

**Comment by cagnulein** [comment]
Thanks!
Actually no, just file name. Adding tags on the filter means keeping a db of the workout files so it will require more work.
It's better to use the file name with tags and descriptions
Also it's better to add a suffix for treadmill, bike, rower and also for power zones....
Il 21 giu 2022, 12:48 +0200, jonathancolledge ***@***.***>, ha scritto:

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/175049579-acc2343f-eb99-4ab8-9c92-6f107b970189.png)
[Italy - Passo dello Stelvio.zip](https://github.com/cagnulein/qdomyos-zwift/files/8958345/Italy.-.Passo.dello.Stelvio.zip)

@jonathancolledge for example Passo dello Stelvio in Italy is one of the most famous rides for "Giro d'Italia". It's 20km with 1500 D+ in the Alps. The file is quite small (150k) and it could be bundled as with many other great rides in the world

**Comment by jonathancolledge** [comment]
> @jonathancolledge for example Passo dello Stelvio in Italy is one of the most famous rides for "Giro d'Italia". It's 20km with 1500 D+ in the Alps. The file is quite small (150k) and it could be bundled as with many other great rides in the world
> 

Yes! I have some I will send tomorrow morning. The originals have 0.5 m spacing of GPX points and elevation from LiDAR again, but that makes them from 4 to 20 mb. If I reduce the point spacing to 10 m, then the size will be much smaller, but it'll still be as accurate since no indoor trainer or bike can adjust quick enough to make use of the 0.5 m spacing anyway (I just have it because I can).

**Comment by jonathancolledge** [comment]
[Small GPX files for Roberto.zip](https://github.com/cagnulein/qdomyos-zwift/files/8974328/Small.GPX.files.for.Roberto.zip)

I reduced the size from 50 mb to 3.2 mb. That is the best I can do without losing the elevation accuracy. I used the simplify filter on GPX Magic here: http://stepwiserefinement.co.uk.s3-website-eu-west-1.amazonaws.com/GPXmagic/index.html?fbclid=IwAR0Zj0JRQNSKG_d9F4hEmhRl0e50DCC2zTSlma53qYZlRxNCxvNXX3uAkWw

The filter works a bit like a Douglas-Puecker but instead of doing it only in 2D, it preserves the elevation. That way these small files are within 1 m of the actual elevation gain and points are concentrated at the areas of maximum change. So the elevation data remains far better in terms of accuracy than Strava.

Is the size small enough? Maybe it is not.

I guess I need to give you descriptions of each ride! I'll write that in the next post later this morning.

**Comment by cagnulein** [comment]
Wow! Really handy tool! Thanks for sharing this!

About the GPXs: the size could still too big, i mean we should have 100kb every 10km top I guess, but I didn't think about this since today, so maybe I'm wrong :)

but I'm also wondering if these tracks are famous or not :D I mean I was wondering about add some epic tops or similar, maybe it's just me, but I don't know them at all :D

**Comment by jonathancolledge** [comment]
So, Box Hill and Richmond Park are famous - both were in the 2012 Olympic games. They aren't iconic routes though. They are popular routes for London cyclists as they are so close to the city, but in terms of the actual quality of the route, they aren't anything you'd travel to do! It is just that people in London have nothing better. The rest are rather obscure. If you were to pick one, I'd ditch them all and only have Crater Lake. In fact, now that I think about it, and given that size/memory is important forget all the rest! Give Crater Lake a try and see if it is worthy! [Crater Lake](https://user-images.githubusercontent.com/4342400/175507700-57965255-1775-4573-b6a9-9b7783fdb467.jpg)
.

**Comment by cagnulein** [comment]
I just finished to add colors to the inclination chart in the bottom right corner in the 3d map. I did a 1h run this morning and I really enjoyed it. This afternoon I will try the "Passo dello Stelvio" by bike, let's see how far I will go :)

**Comment by cagnulein** [comment]
i also added the name of the gpx/zwo in the strava title ;)

**Comment by jonathancolledge** [comment]
Here are the ride descriptions:

This is a great route for a quick 30 minute climb. It starts at Government Camp (Govi) and ends at Timberline Lodge on Mount Hood. It’s a beautiful, smooth ride up the base of the volcano through wooded areas and past meadows until you see Palmer Glacier above you and arrive at the lodge used as the location in the film The Shining!
The average gradient is 7% with no steep sections. And elevation data were obtained from LiDAR.

Box Hill

This is the loop from the London 2012 Olympics with elevation data provided by LiDAR. The route was re-tarmacked for the Olympic race. As part of the larger route, competitors repeated the loop until they had ridden Box Hill nine times. 


Richmond Park Anticlockwise 

An 11 km anticlockwise loop with some short hills. It starts just beyond Robin Hood gate. The London 2012 Olympic road race  passed through Richmond Park and it is a popular destination for London cyclists. 
Elevation data obtained from LiDAR. 


Butterfield Canyon Road

A punishing climb near the world's deepest open-pit mine. There is a rolling lead-in and several leg-busting steep sections, after which you can look forward to a gentle finish. Elevation were data obtained from LiDAR.

Pittenweem to St Andrews

A picturesque ride through Scottish countryside up to a hill where you can look down on the sea and the ancient University town of St Andrews. Elevation data were obtained from LiDAR.

St Andrews to Pittenweem

A ride from Prince William's alma mater to Pittenweem, a picturesque fishing village on the Fife coast. Elevation data were obtained from LiDAR.

**Comment by cagnulein** [comment]
thanks, i'm planning to add a similar view as I did for the training program also for the gpx. adding a 2d map and a description and metrics summary
Il 24 giu 2022, 16:39 +0200, jonathancolledge ***@***.***>, ha scritto:

**Comment by cagnulein** [comment]
i'm doing the gpx preview right now. I hope to have a very alpha today. Also this evening I'm planning to give a go to the Crater lake gpx ;)

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/176443300-f2ee96a5-7fa3-4d0c-9321-445447546ac4.png)
