### ISSUE TITLE
[BUG] Not Working with Sole E95S Elliptical

### ISSUE THREAD

**Issue by taseidel** [cagnulein/qdomyos-zwift#844]
**Describe the bug*
Unable to get any data showing up with Sole E95S Eliptical

**To Reproduce**
1. Hit start on Sole E95S elliptical
2. Open qdomos-zwift and it finds and connects to E95S
3. Open Zwift and Google Pixel 4 shows up and connect to it, cadence does not show up or shows up as Wahoo Tread 
4.  With or without cadence selected going into run, does not let you move the runner.

NOTE: Outside of qdomos-zwift with Zwift alone, the elliptical will connect and work in cycling mode, so it's obviously transmitting data.

**Expected behavior**
Expect to be able to use qdomos-zwift to connect to Zwift for running.

**Desktop (please complete the following information):**
 - OS: Windows on MS Surface
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4 XL
 - OS: Android
 - Version 12

**Append a debug log**
Debug log attached.
[debug-Tue_Jun_21_16_09_05_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8953384/debug-Tue_Jun_21_16_09_05_2022.log)

**Comment by cagnulein** [comment]
@taseidel the issue about this log is that you have the elliptical machine also in the power sensor setting. Set to disable and press ok and restart QZ. If it doesn't work send me a fresh log again.
Thanks
