### ISSUE TITLE
[BUG] Issue with iPhone 8 Plus sensor not connecting on Peloton App

### ISSUE THREAD

**Issue by fdosani** [cagnulein/qdomyos-zwift#846]
**Describe the bug**
My wife and I have iPhone 8 Plus and 13 respectively. Aside from the phone the setup is exactly the same (iPhone to Echelon bike to iPad with Peloton app). For some reason recently she hasn't been able to connect the sensors on the Peloton app. I checked her iOS version and it is the latest, rebooted both the iPad and iPhones and it isn't able to connect. She is getting the notice for auto resistance when connecting to an on-demand class so it seems the connection is being made between the [qdomyos-zwift](https://github.com/cagnulein/qdomyos-zwift) and the bike.

My iPhone 13 connects fine which makes this even more bizarre. Attaching the logs where I was getting the "can't connect" message on the Peloton app.

**debug log**

[debug-Mon-Jun-27-11-11-05-2022.log](https://github.com/cagnulein/qdomyos-zwift/files/8992874/debug-Mon-Jun-27-11-11-05-2022.log)

**Comment by cagnulein** [comment]
Hi, first of all did you try to do a network reset to your ipad and reboot it?
Il 27 giu 2022, 18:52 +0200, Faisal ***@***.***>, ha scritto:

**Comment by fdosani** [comment]
I did reboot the iPad and iPhone yielding the same result. Let me try that again. When you say network reset is there a particular thing I should be doing. I turned the wifi/Bluetooth and and off etc.

**Comment by cagnulein** [comment]
yes it's a particular step https://www.verizon.com/support/knowledge-base-89833/
remember to reboot it then
Il 27 giu 2022, 20:45 +0200, Faisal ***@***.***>, ha scritto:

**Comment by cagnulein** [comment]
@fdosani any news?

**Comment by fdosani** [comment]
Sorry for the delay. I couldn’t get it working so we decided to upgrade to an iPhone 13 mini. Was time for an Upgrade anyway. Everything is working now with no changes.  On Sat, Jul 2, 2022 at 7:29 AM, Roberto Viola ***@***.***> wrote:  
@fdosani any news?

**Comment by cagnulein** [comment]
ok great @fdosani !
