### ISSUE TITLE
[BUG] GPX Ride crashed

### ISSUE THREAD

**Issue by rjbutler** [cagnulein/qdomyos-zwift#851]
**Describe the bug**
Using 2.10 (92), I loaded a gpx file from a local ride I recorded and rode it in QZ.  The ride followed the track, but I didn't feel like the resistance matched the hills on the ride (too low) and the ride took longer in QZ despite my keeping up a pretty high cadence the whole way through.  My average heart rate was also much lower than on the outdoor ride..  At the end of the ride, QZ froze and then crashed and didn't record the ride properly.   

Overall though it was pretty fun to re-ride and see the map go by.

It may be that I don't have my settings quite right.  I do have my bike weight set, speed calculates on power, Erg Mode.  Anything else?  Do I need to set the Zwift resistance gain maybe?  Resistance at startup?  Those two are default currently.

Debug and GPX file attached.  This is a ride from Kirkland across Lake Washington into Seattle.

[GPX Ride.zip](https://github.com/cagnulein/qdomyos-zwift/files/9042526/GPX.Ride.zip)

**Comment by rjbutler** [comment]
Here are the JPG files that were written.  No .fit files, sorry, I was wrong in chat -- I was looking at the same timestamp different day.
[GPX Ride JPGs.zip](https://github.com/cagnulein/qdomyos-zwift/files/9043291/GPX.Ride.JPGs.zip)

**Comment by cagnulein** [comment]
> Here are the JPG files that were written. No .fit files, sorry, I was wrong in chat -- I was looking at the same timestamp different day.

strange, QZ reported that the files are correctly saved

<pre>Mon Jul 4 16:18:31 2022 1656976711648 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:19:31 2022 1656976771552 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:20:31 2022 1656976831624 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:21:31 2022 1656976891555 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:22:31 2022 1656976951556 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:23:31 2022 1656977011556 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:24:31 2022 1656977071557 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:25:31 2022 1656977131558 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:26:31 2022 1656977191559 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:27:31 2022 1656977251561 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:28:31 2022 1656977311562 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:29:31 2022 1656977371562 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:30:31 2022 1656977431563 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:31:31 2022 1656977491564 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:32:31 2022 1656977551566 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:33:31 2022 1656977611565 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:34:31 2022 1656977671567 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:35:31 2022 1656977731568 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:36:31 2022 1656977791570 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:37:31 2022 1656977851571 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:38:31 2022 1656977911572 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:39:31 2022 1656977971573 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:40:31 2022 1656978031574 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:41:31 2022 1656978091576 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:42:31 2022 1656978151577 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:43:31 2022 1656978211578 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:44:31 2022 1656978271580 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:45:31 2022 1656978331580 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:46:31 2022 1656978391581 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:47:31 2022 1656978451583 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:48:31 2022 1656978511584 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:49:31 2022 1656978571587 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:50:31 2022 1656978631588 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:51:31 2022 1656978691589 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:52:31 2022 1656978751591 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:53:31 2022 1656978811594 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:54:31 2022 1656978871595 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:55:31 2022 1656978931597 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:56:31 2022 1656978991598 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:57:31 2022 1656979051600 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:58:31 2022 1656979111601 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 16:59:31 2022 1656979171602 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:00:31 2022 1656979231604 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:01:31 2022 1656979291606 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:02:31 2022 1656979351607 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:03:31 2022 1656979411608 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:04:31 2022 1656979471610 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:05:31 2022 1656979531612 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:06:31 2022 1656979591612 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:07:31 2022 1656979651614 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:08:31 2022 1656979711616 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:09:31 2022 1656979771619 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:10:31 2022 1656979831619 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:11:31 2022 1656979891621 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:12:31 2022 1656979951623 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:13:31 2022 1656980011625 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:14:31 2022 1656980071627 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:15:31 2022 1656980131629 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:16:31 2022 1656980191630 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:17:31 2022 1656980251632 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:18:31 2022 1656980311635 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:19:31 2022 1656980371636 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:20:31 2022 1656980431638 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:21:31 2022 1656980491640 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:22:31 2022 1656980551642 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:23:31 2022 1656980611644 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:24:31 2022 1656980671648 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:25:31 2022 1656980731649 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:26:31 2022 1656980791651 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:27:31 2022 1656980851653 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:28:31 2022 1656980911655 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:29:31 2022 1656980971658 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:30:31 2022 1656981031659 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:31:31 2022 1656981091661 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:32:31 2022 1656981151663 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:33:31 2022 1656981211665 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:34:31 2022 1656981271666 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:35:31 2022 1656981331668 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:36:31 2022 1656981391670 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:37:31 2022 1656981451672 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:38:31 2022 1656981511673 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:39:31 2022 1656981571675 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:40:31 2022 1656981631677 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."
Mon Jul 4 17:41:31 2022 1656981691677 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::backup() "saving fit file backup..."</pre>

**Comment by cagnulein** [comment]
> The ride followed the track, but I didn't feel like the resistance matched the hills on the ride (too low) and the ride took longer in QZ despite my keeping up a pretty high cadence the whole way through.

the problem it's about your zwift resistance offset (4) and zwift resistance gain (1). They are the default value (used for domyos bike) and for sure they are not right for your bike.

In order to calibrate them I suggest to find the right offset for a flat road (maybe something like 40, 45?) and then you can play with the gain if, during a hill, you don't feel it enough.

Don't you ever used zwift with your setup?

**Comment by cagnulein** [comment]
another good news @rjbutler I fixed the crash: it was a stupid one from me :)

**Comment by cagnulein** [comment]
@rjbutler did you test it again?

**Comment by rjbutler** [comment]
Yes, I did.  It worked great!  Thanks
