### ISSUE TITLE
Developer Documentation

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#852]
I have looked through the discussions, the wiki, the projects, the issues. 

I've cloned my fork of the repo, and tried to build the Visual Studio solution. I managed to get Qt 5.15.2 installed and the compiler trying to build the project, but it seems some include directories need to be set up and there are some files missing in the qmdnsengine folder.

I've got the source code on my RP4, and I've been able to install qd-creator but none of the "qt4-dev-tools" or "qt5-default" packages an internet search refers to are found.

I'm wondering, is there documentation somewhere for how to get started with development on this project? e.g. what's the preferred development environment?

**Comment by cagnulein** [comment]
hi, start from there https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md

and on windows use qt creator instead of visual studio

**Comment by drmason789** [comment]
Thanks.

**Comment by drmason789** [comment]
With the current set of packages, on the RP I'm getting this on qmake:

Project ERROR: Unknown module(s) in QT: texttospeech location quickcontrols2

I'm busy looking for additional packages I might need.

For Windows, is there a specific QtCreator project file I should open somewhere?

**Comment by drmason789** [comment]
In the instructions on 10_Installation.md, the sudo command is there twice. 

![image](https://user-images.githubusercontent.com/29954900/177876088-1584a3da-2968-404e-a038-c26434dcba38.png)

Also, for qt5quickcontrols2-5-dev is not found:
![image](https://user-images.githubusercontent.com/29954900/177876348-18d3b5da-d6de-49c9-8e5d-359d0be789f1.png)

**Comment by drmason789** [comment]
I had some trouble installing "qt5quickcontrols2-5-dev" as specified, but eventually I found that qtquickcontrols2--dev (i.e. no 5 after the qt) gets me to the next problem:

![image](https://user-images.githubusercontent.com/29954900/177879765-1b386ad7-0f43-48ff-928e-82ab21e34713.png)

WARNING: Failure to find: qdomyos-zwift_metatypes.json

Maybe this is not a problem.

**Comment by janstadt** [comment]
I had issues installing on jellyfin raspberry pi (the OG 1 pi lol). Had to install `qtlocation5-dev` and `qtquickcontrols2-5-dev`, `libqt5texttospeech5-dev`, and  `libqt5texttospeech5` separately to get qmake to run.

**Comment by cagnulein** [comment]
yes as documented here https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/10_Installation.md

**Comment by janstadt** [comment]
Thanks @cagnulein i was following the raspberry pi installation steps that do not include those.

**Comment by cagnulein** [comment]
@janstadt hah ok i will add them, i forgot them, sorry ;)

**Comment by janstadt** [comment]
no worries man. great work here! love this!

**Comment by cagnulein** [comment]
done!
