### ISSUE TITLE
Units of class members unknown

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#856]
BluetoothDevice has some protected members:

```
 metric elapsed;
    metric moving; // moving time
    metric Speed;
    metric KCal;
    metric Distance;
    uint8_t FanSpeed = 0;
    metric Heart;
    int8_t requestStart = -1;
    int8_t requestStop = -1;
    int8_t requestIncreaseFan = -1;
    int8_t requestDecreaseFan = -1;
    double requestFanSpeed = -1;
    double m_difficult = 1.0;
    metric m_jouls;
    metric elevationAcc;
    metric m_watt;
    metric WattKg;
    metric WeightLoss;
    metric Cadence;
    metric Resistance;
    metric METS;
    QGeoCoordinate coordinate;
    metric Inclination;
    metric HeartZone;
    metric PowerZone;

```

Bike has some others.

Could we have comments on these to define what they are and what the units are? 

e.g.

```
    /**
     * @brief Heart The heart rate reported by the device. Unit: beats per minute
     */
    metric Heart;
    
    /**
     * @brief Cadence The time taken for a crank to complete a full revolution. Unit: Radians per second
     */
    metric Cadence;
    
    /**
     * @brief Resistance The resistance requested from the device. Unit: 0..get_MaxResistance()
     */
    metric Resistance;
```

**Comment by cagnulein** [comment]
I'm a bit overwhelmed by requests as you can imagine but if you want we can
make this in this way: ask me when you have some doubts and you can create
a PR for this. It will be much appreciated for the whole community. What
do you think?




Il giorno dom 10 lug 2022 alle ore 19:12 David Mason <
***@***.***> ha scritto:

**Comment by drmason789** [comment]
I'm happy to do the code edits and PR. 

Could we start with these ones? I'm not sure their clear definition and units. Here are some guesses that are probably wrong:

Speed - Flywheel speed. Units: radians per second
Distance - Cumulative flywheel revolutions multiplied by the wheel circumference. Units: meters
Heart - the heart rate. Units: beats per minute
Cadence - the speed at which the crank is turning. Unit: Radians per second
Resistance - the currently requested resistance level. Expected range: 0 to getMaximumResistance()

**Comment by cagnulein** [comment]
> Speed - Flywheel speed. Units: radians per second

km/h

> Distance - Cumulative flywheel revolutions multiplied by the wheel circumference. Units: meters

km

> Heart - the heart rate. Units: beats per minute

yes

> Cadence - the speed at which the crank is turning. Unit: Radians per second

nope, RPM 

> Resistance - the currently requested resistance level. Expected range: 0 to getMaximumResistance()

exactly

**Comment by cagnulein** [comment]
Hi @drmason789 how is it going with this? Is everything clear enough?

**Comment by drmason789** [comment]
I've put some comments on a few fields / functions that I use for my main contribution to this project (#855) and submitted a PR.
