### ISSUE TITLE
Blank Screen/No Metrics after Class

### ISSUE THREAD

**Issue by shmaddox** [cagnulein/qdomyos-zwift#857]
Issue started on July 9th and happened through 2 classes on July 9th, 3 on July 10th, and one on July 11th.

When class is finished, a blank white screen shows (no metrics), and I don't receive a summary email after. However, the workout is still uploaded to strava.

[debug-Mon_Jul_11_09_11_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085623/debug-Mon_Jul_11_09_11_25_2022.log)

**Comment by shmaddox** [comment]
[debug-Sun_Jul_10_09_30_42_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085751/debug-Sun_Jul_10_09_30_42_2022.log)
[debug-Sun_Jul_10_00_01_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085754/debug-Sun_Jul_10_00_01_41_2022.log)
[debug-Sat_Jul_9_11_56_35_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085755/debug-Sat_Jul_9_11_56_35_2022.log)
[debug-Sat_Jul_9_09_05_26_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085756/debug-Sat_Jul_9_09_05_26_2022.log)
[debug-Sat_Jul_9_02_25_18_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085759/debug-Sat_Jul_9_02_25_18_2022.log)
[debug-Mon_Jul_11_09_11_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085760/debug-Mon_Jul_11_09_11_25_2022.log)
[debug-Mon_Jul_11_01_33_19_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085761/debug-Mon_Jul_11_01_33_19_2022.log)
[debug-Sun_Jul_10_14_20_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9085762/debug-Sun_Jul_10_14_20_13_2022.log)

**Comment by cagnulein** [comment]
thanks @shmaddox of these do you remember which one are good and which ones are not?

**Comment by shmaddox** [comment]
I *think* all had issues - they're all the logs between Saturday and today.

**Comment by cagnulein** [comment]
@shmaddox I found a big issue on the flow: i mean in the majority of the logs there isn't any trace of a stop event at all. Charts and email are generated ONLY when you're pressing the STOP button.
Does it make sense to you? Are you always pressing STOP at the end of the workout?

**Comment by cagnulein** [comment]
ok let me try to understand. This is what I saw on the logs

  C:\Users\violarob\Downloads\charts\debug-Fri_Jul_8_15_38_21_2022 (1).log (1 hit)
	Line 481: Fri Jul 8 15:38:31 2022 1657316311978 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" false
  C:\Users\violarob\Downloads\charts\debug-Mon_Jul_11_01_33_19_2022 (2).log (5 hits)
	Line 2872: Mon Jul 11 08:32:59 2022 1657549979418 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" false
	Line 4868: Mon Jul 11 08:35:56 2022 1657550156023 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" true "stopped" false
	Line 6565: Mon Jul 11 08:38:08 2022 1657550288448 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" false
	Line 7107: Mon Jul 11 08:38:50 2022 1657550330384 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" true "stopped" false
	Line 28620: Mon Jul 11 09:06:40 2022 1657552000709 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
  C:\Users\violarob\Downloads\charts\debug-Sat_Jul_9_09_05_26_2022 (1).log (5 hits)
	Line 2654: Sat Jul 9 10:51:13 2022 1657385473275 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" false
	Line 15090: Sat Jul 9 11:07:18 2022 1657386438341 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" true "stopped" false
	Line 18008: Sat Jul 9 11:11:04 2022 1657386664945 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
	Line 33268: Sat Jul 9 11:30:56 2022 1657387856110 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" true
	Line 48959: Sat Jul 9 11:51:17 2022 1657389077309 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
  C:\Users\violarob\Downloads\charts\debug-Sun_Jul_10_09_30_42_2022 (1).log (7 hits)
	Line 4728: Sun Jul 10 13:33:27 2022 1657481607632 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" false
	Line 6922: Sun Jul 10 13:36:17 2022 1657481777053 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" true "stopped" false
	Line 25043: Sun Jul 10 13:56:19 2022 1657482979932 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
	Line 25629: Sun Jul 10 13:57:01 2022 1657483021303 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" true
	Line 34578: Sun Jul 10 14:07:03 2022 1657483623806 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
	Line 35405: Sun Jul 10 14:08:03 2022 1657483683695 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Start_inner(bool) "Start pressed - paused" false "stopped" true
	Line 43465: Sun Jul 10 14:18:31 2022 1657484311938 Debug: /Users/cagnulein/qdomyos-zwift/src/homeform.cpp void homeform::Stop() "Stop pressed - paused" false "stopped" false
Search "pressed" (17 hits in 3 files)


So it seems that in the one that works good, you press start at Fri Jul 8 15:38:31 2022 but never stops. Here I can't see any email sent so I guess this is not a working session unfortunately.

In the others, probably some files are just little useless session. The others big 3 files instead have multiple stops. Were you doing 2/3 different workouts on the same QZ sessions, isn't it? 

Let's do another experiment. Open QZ even without the bike nearby you should see this:

**Comment by shmaddox** [comment]
![IMG_5072](https://user-images.githubusercontent.com/98183101/178516662-8a8a0f1d-a851-47cf-8ea0-1647115de222.PNG)

This is what I see when I open QZ (nowhere near my bike; I'm at my office, actually).

Yes, I did two workouts on Saturday, July 9th (two Logan Aldridge live strength classes), and 3 workouts on Sunday, July 10th (20 minute country ride with Bradley Rose, 10 minute low impact ride with Matt Wilpers, and 10 minute Arms & Light Weights with Ally Love), plus a 30 minute PZE ride on Monday, July 11th with Christine D'Ercole.

If I didn't stop the workout on July 8th, is there a way to force stop it?  I force close QZ by closing on my Apple Watch first, then swiping QZ off the screen after I've completed my workouts for the day.

**Comment by cagnulein** [comment]
> This is what I see when I open QZ (nowhere near my bike; I'm at my office, actually).

press the left side bar and press charts , i forgot to say :P



> If I didn't stop the workout on July 8th, is there a way to force stop it? I force close QZ by closing on my Apple Watch first, then swiping QZ off the screen after I've completed my workouts for the day.

wait, you missed the stop button on the QZ app on this flow. Is it intentional?

**Comment by shmaddox** [comment]
Okay I see that page now.

I do stop each workout. I’m wondering if I possibly missed stopping on July 8th specifically?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shmaddox** [comment]
Interestingly, it all worked perfectly fine today! I'm not sure what the
difference was...

**Comment by cagnulein** [comment]
mmm I found something that could explain this random issue. I will send you a new one today/tomorrow to double confirm that the issue has been solved. Thanks as always for the feedbacks!

**Comment by cagnulein** [comment]
nervermind, It wasn't that one...so keep me updated about this..let me know if it happens again

**Comment by cagnulein** [comment]
@shmaddox did it happen again since the last time?

**Comment by shmaddox** [comment]
Nope, all is well!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
ok i'm closing this one, if it will happen again, let me know

**Comment by shmaddox** [comment]
Hi Roberto! Just happened on the ride I just finished. Here’s the debug!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
hi @shmaddox debug log is missing. You need to attach it from github interface. Thanks!

**Comment by shmaddox** [comment]
Sorry!  Here you go :)
[debug-Tue_Aug_2_11_11_00_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9244545/debug-Tue_Aug_2_11_11_00_2022.log)

**Comment by cagnulein** [comment]
@shmaddox unfortunately this is a short log from a no-workout session. maybe you have another one in a similar time range?

**Comment by shmaddox** [comment]
[debug-Tue_Aug_2_00_44_06_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9251995/debug-Tue_Aug_2_00_44_06_2022.log)

**Comment by cagnulein** [comment]
@shmaddox thanks for the file! I get an idea this time. Looking at your log, seems that the QZ session starts at Tue Aug 2 00:44:06 2022 but you really start riding at Tue Aug 2 10:29:10 2022  isn't it?
So maybe QZ was always on the background for the whole time, and when you started it, the chart things went crazy.
In order to put value on my idea, can you please try, on the next rides, to always close QZ first before launching it?

**Comment by shmaddox** [comment]
I'm not sure how it could have been on in the background, I wasn't awake at
that point (providing I'm reading the times correctly, this would have
started at 12:44am my time and my workout was at 10:30am). But, yes, I will
make sure QZ is closed and then relaunched before my workouts!

**Comment by cagnulein** [comment]
@shmaddox I didn't forget about this! I just did a small patch ( @p3g4asus will hate this, because it's horrible I know) that it should fix this issue once and for all. If you agree I will send you the new beta. Let me know

**Comment by shmaddox** [comment]
Sounds great, I just downloaded the build and will let you know how it goes
after a few rides!

**Comment by shmaddox** [comment]
Haven't had an issue since, but will let you know if it becomes a problem
again!

Sarah

**Comment by cagnulein** [comment]
wow that's an amazing news! thanks @shmaddox for the feedback!

**Comment by cagnulein** [comment]
@shmaddox everything is still okay?

**Comment by shmaddox** [comment]
Still okay!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
