### ISSUE TITLE
Elliptical Domyos

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#86]
[debug-Wed Dec 23 12_03_03 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5737176/debug-Wed.Dec.23.12_03_03.2020.log)
[debug-Wed Dec 23 13_09_11 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5737177/debug-Wed.Dec.23.13_09_11.2020.log)

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/103038114-e32c1180-456d-11eb-85da-4e2dc8742f58.png)
![image](https://user-images.githubusercontent.com/48216/103038123-e921f280-456d-11eb-8756-cf3c189f700f.png)

**Comment by guidel96** [comment]
Able to sync the Domyos EL520 elliptical trainer with the Android phone (Huawei Mate 20 Lite). 
But unable to sync the android app with Zwift (on both iOS and MacOS).
The Android app "Speed transmitter" was able to connect the Android phone with Zwift (iOS and MacOS).
Have tried to connect my iPad with my Android phone with the nrfconnect but the app didn't find my phone.

Also, cadence is not showing up on the Android app.

**Comment by cagnulein** [comment]
ok @guidel96 i've done all the modifications. now you should read cadence on the UI.
it's very strange that you don't see the bridge from your phone. Are you sure that it doesn't popup with a different name, for example "DomyosBridge"? I saw in your logs that the bridge interface was correctly set up. Maybe is a lack of the bluetooth stack of your phone (peripheral and central bluetooth at the same time)? But it seems strange to me. Do you have another phone or tablet just to try?

**Comment by cagnulein** [comment]
[debug-Thu Mar 18 21_38_35 2021.log](https://github.com/cagnulein/qdomyos-zwift/files/6169208/debug-Thu.Mar.18.21_38_35.2021.log)
inclination needs to be managed

**Comment by cagnulein** [comment]
#438
