### ISSUE TITLE
Techogym run trendmill

### ISSUE THREAD

**Issue by Melbtrip** [cagnulein/qdomyos-zwift#870]
![FB_IMG_1658639239421](https://user-images.githubusercontent.com/109889049/180633169-776a0615-ee3f-4705-9f11-bbce1ce1d38e.jpg)
Techogym run trendmill

**Comment by cagnulein** [comment]
@Melbtrip i need a full screenshot while it's connected. now this screenshot says connecting...

**Comment by cagnulein** [comment]
@Melbtrip did you read this?

**Comment by cagnulein** [comment]
@Melbtrip any news?
