### ISSUE TITLE
Proform SE inclination

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#871]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9175248/btsnoop_hci.log)

**Comment by rattie94** [comment]
> 
[Uploading bugreport-T671H_EEA-RKQ1.201112.002-2022-07-24-09-21-30.zip…]()

**Comment by cagnulein** [comment]
@rattie94 you need to wait the upload before pushing comment. please attach it again

**Comment by rattie94** [comment]
[bugreport-T671H_EEA-RKQ1.201112.002-2022-07-24-09-21-30.zip](https://github.com/cagnulein/qdomyos-zwift/files/9175319/bugreport-T671H_EEA-RKQ1.201112.002-2022-07-24-09-21-30.zip)

**Comment by rattie94** [comment]
I think it's done now 👍

**Comment by cagnulein** [comment]
#779 same protocol

**Comment by rattie94** [comment]
![image](https://user-images.githubusercontent.com/109894056/180646805-9561b106-e8d3-4984-a49a-6e9c8c1d0c4c.jpeg)![image](https://user-images.githubusercontent.com/109894056/180646806-d9777871-d5ff-4949-8e80-abb7b44fc49a.jpeg)

**Comment by rattie94** [comment]
![image](https://user-images.githubusercontent.com/109894056/180646857-fa3f092e-5655-4670-8f16-e32aed2ff687.png)![image](https://user-images.githubusercontent.com/109894056/180646865-9c71b12a-8576-4193-a47c-493d82534ca7.jpeg)

**Comment by rattie94** [comment]
[debug-Sun_Jul_24_16_08_39_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9175973/debug-Sun_Jul_24_16_08_39_2022.log)

**Comment by rattie94** [comment]
Still the same problem

**Comment by cagnulein** [comment]
@rattie94 in this log there isn't any incline plus/minus pressions. Could you please generate one where you're pressing at least one time the inclination plus button from QZ ?
Thanks

**Comment by rattie94** [comment]
That I done but as I said nothing happens. But will try again

**Comment by cagnulein** [comment]
yes but i need the debug log to
understand it

**Comment by cagnulein** [comment]
[debug-Mon_Jul_25_15_54_48_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/9181877/debug-Mon_Jul_25_15_54_48_2022.log.zip)

**Comment by cagnulein** [comment]
[Uploading debug-Tue_Jul_26_16_12_15_2022.log…]()

**Comment by cagnulein** [comment]
[debug-Tue_Jul_26_16_12_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9190562/debug-Tue_Jul_26_16_12_15_2022.log)

**Comment by cagnulein** [comment]
[debug-Thu_Jul_28_15_17_19_2022.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/9210140/debug-Thu_Jul_28_15_17_19_2022.log.zip)

**Comment by cagnulein** [comment]
[Håbafjell-Sandved.gpx.zip](https://github.com/cagnulein/qdomyos-zwift/files/9210450/Habafjell-Sandved.gpx.zip)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9259574/btsnoop_hci.log)

**Comment by cagnulein** [comment]
[debug-Sat_Aug_6_17_25_02_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275360/debug-Sat_Aug_6_17_25_02_2022.log)
