### ISSUE TITLE
Assioma Duo

### ISSUE THREAD

**Issue by Nix258** [cagnulein/qdomyos-zwift#872]
I am using Schwinn IC4 with Assioma Duo power pedals and Vortec Heart Rate chest strap meter.

I installed QZ yesterday.  It recognised the Assioma pedals in setup.  However, when I ride it shows no data of any type.

To test the pedals were working I downloaded TrainerDay and SuperCycle.  Both these apps recognised the bike and pedals and produced numbers without much setup effort.  So I know the pedals, bike and HRM are all transmitting OK.

Phone: Samsung Galaxy J2Pro - SM-J250G, running Android 7.1.1. 

3 bug files from today are attached.

Thanks, Nick

[0QZ-backup-Mon Jul 25 23_40_06 2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/9182091/0QZ-backup-Mon.Jul.25.23_40_06.2022.zip)

**Comment by cagnulein** [comment]
hi @Nix258 in order to help you, you need to send here the debug log, not the fit files. Follow this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Nix258** [comment]
[debug-Mon_Jul_25_23_30_12_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9182179/debug-Mon_Jul_25_23_30_12_2022.log)
[debug-Mon_Jul_25_23_32_02_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9182180/debug-Mon_Jul_25_23_32_02_2022.log)

**Comment by cagnulein** [comment]
@Nix258 there is something strange. I have the Assioma too (only one, not the duo) and your assioma doesn't stream over bluetooth with standard power metrics. Actually it doesn't stream at all in this log.
It seems that there isn't the power service at all. Could you please run nrfconnect app on this device and try to connect to your assioma? I would like to check if the services that nrfconnect gets are the same of the QZ one.

QZ is gotting these ones:

"serviceDiscovered {00001800-0000-1000-8000-00805f9b34fb}"
"serviceDiscovered {00001801-0000-1000-8000-00805f9b34fb}"
"serviceDiscovered {6e400001-b5a3-f393-e0a9-e50e24dcca9e}"
"serviceDiscovered {0000180a-0000-1000-8000-00805f9b34fb}"
"serviceDiscovered {0000180f-0000-1000-8000-00805f9b34fb}"

but the power one is missing

**Comment by Nix258** [comment]
Hi Roberto,
Thanks for response.  I got an email from Assioma, they want me to do some things to recallibrate, and then reconnect to their app and they can check the pedals are working from their end.  I will do this first and then look at what you are asking.
Nick

**Comment by cagnulein** [comment]
ok i'm here if you still have issue. also consider that assioma is an italian company so you can put me in CC if there are some misunderstandings
Let me know

**Comment by Nix258** [comment]
OK, what is your email?

**Comment by cagnulein** [comment]
roberto.viola83 at gmail.com

**Comment by cagnulein** [comment]
@Nix258 any news?
