### ISSUE TITLE
[BUG] No watt output on SportPlus SP-HT-1004-iE with latest version

### ISSUE THREAD

**Issue by Angi2412** [cagnulein/qdomyos-zwift#874]
**Describe the bug**
With the latest version of the IOS app, the watt output remains 0. Therefore the bike is not moving in e.g. Zwift.
See the debug log: [debug-Mi__Juli_27_16_33_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9200179/debug-Mi__Juli_27_16_33_08_2022.log)

**To Reproduce**

1. Start the app
2. Connect to bike
3. Start driving
4. See that watt is 0

**Expected behavior**
The watt output should not be 0 when the bike is moving.

**Screenshots**
![IMG_3550](https://user-images.githubusercontent.com/11177877/181277895-59007782-e6b2-407c-9c80-cf244dc0fabc.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: IOS 15.6
 - Version 2.11

**Append a debug log**

[debug-Mi__Juli_27_16_33_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9200179/debug-Mi__Juli_27_16_33_08_2022.log)
  
  
**Additional context**
It was working with the previous app version. I already reset the network settings on my phone.

**Comment by cagnulein** [comment]
@Angi2412 could you please send me a debug log where the cadence is greater than 0? Also did you notice that you have the setting sp_ht_9600ie enabled? I don't remember if for your bike is needed.
Let me know

**Comment by Angi2412** [comment]
@cagnulein I disabled the `sp_ht_9600ie` setting, but nothing changed.
Here is another debug log: [debug-Mi__Juli_27_18_18_55_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9200955/debug-Mi__Juli_27_18_18_55_2022.log)

**Comment by cagnulein** [comment]
#812 
@Angi2412 i will check this tomorrow, thanks

**Comment by cagnulein** [comment]
@Angi2412 fixed! it will be in the 2.11.11 that I will send you today. 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by Angi2412** [comment]
@cagnulein thank you very much for the fast support 👍

**Comment by Angi2412** [comment]
@cagnulein works now again, thanks again 👍

**Comment by cagnulein** [comment]
glad to hear it!

**Comment by Angi2412** [comment]
@cagnulein Hi, did this commit make it into master? I have no access to the version on testflight anymore and in the current version 2.15 on ios, it does not show wattage again.

**Comment by cagnulein** [comment]
Yes it's on the master branch. I will check your log asap.

**Comment by cagnulein** [comment]
@Angi2412 you have to disable the `sp_ht_9600ie` setting in order to use the patch that I did
Let me know

**Comment by Angi2412** [comment]
@cagnulein thank you for the fast response. 
I disabled the `sp_ht_9600ie` setting. Now there is watt output. But there seems to be a problem with the cadence. It takes the heart bpm as cadence 🙈 
![IMG_8037](https://github.com/cagnulein/qdomyos-zwift/assets/11177877/33739d6f-502f-4f9c-b18f-c1a5c641bce5)


[debug-Mo__Jan__15_08_43_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13936238/debug-Mo__Jan__15_08_43_35_2024.log)

**Comment by cagnulein** [comment]
@Angi2412 only to understand, did it work in the past after my wattage patch or it's the first time you're trying this?

**Comment by cagnulein** [comment]
just as a reference for me: yes cadence and hr in the code are using the same bytes so there is for sure an error. anyway i don't know if your bike has a builtin heart rate device @Angi2412 does it?

**Comment by cagnulein** [comment]
just as a reference for me: yes cadence and hr in the code are using the same bytes so there is for sure an error. anyway i don't know if your bike has a builtin heart rate device @Angi2412 does it?

**Comment by Angi2412** [comment]
> @Angi2412 only to understand, did it work in the past after my wattage patch or it's the first time you're trying this?
Actually, I am not quite sure. I know it already worked at a point of time, but I don't quite remember if it was the version on TestFlight.

> just as a reference for me: yes cadence and hr in the code are using the same bytes so there is for sure an error. anyway i don't know if your bike has a builtin heart rate device @Angi2412 does it?

Yes, it has a built-in heart rate device. The heart rate (and cadence) is zero, until I put both of my hands on the heart rate sensors (as it should be with the heart rate value).

**Comment by cagnulein** [comment]
I checked and other than speed, power and heart rate the bike doesn't seem to send anything else. Maybe we can derive cadence from speed? in the bike console are you getting speed and cadence? if so if you can send me a video about 1 minute showing the console and with a debug log I can try to parse it

**Comment by Angi2412** [comment]
> I checked and other than speed, power and heart rate the bike doesn't seem to send anything else. Maybe we can derive cadence from speed? in the bike console are you getting speed and cadence? if so if you can send me a video about 1 minute showing the console and with a debug log I can try to parse it

Yes, I get speed and cadence (rpm) in the console of the bike. I made the video (had to shorten it because of size limitations on GitHub) and have the logs. I couldn't make the video and have both hands on the heart rate sensors, therefore there are no readings of it.

Video: https://github.com/cagnulein/qdomyos-zwift/assets/11177877/3272d5f5-410e-4bbd-b04f-87638e3da042
Logs: [debug-Mo__Jan__15_13_47_31_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13939265/debug-Mo__Jan__15_13_47_31_2024.log)

**Comment by Angi2412** [comment]
> thanks for the video @Angi2412 it was exactly what I need! Just to confirm me: I found a math rule more or less. The cadence seems the (speed from qz * 10) + 2
> 
> So for example when the speed in qz is 6.6 the cadence is 78 (so 6.6 * 10 = 66 + 2 = 78). I guess so this is not the speed but the cadence actually.
> 
> If so I can use this math rule and use the wattage to calculate the speed.
> 
> Let me know if you agree!

I see the correlation as well. But I think You missed a `+10`?
`6.6*10 = 66 + 2 = 68 != 78`

**Comment by cagnulein** [comment]
yes sorry you're right, i did on my brain but not in the message! let me do the mod and send you the beta
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by Angi2412** [comment]
Thank you 🙂

**Comment by Angi2412** [comment]
@cagnulein I've tested it. The formular seems to approach the actual cadence value pretty good. But It alternates with zero every other second. I don't know if this will affect peleton or zwift?
The bigger thing is, that speed remains 0, no matter if I ticked "speed calculation on power" option or not. I attached another debug log.
[debug-Mo__Jan__15_17_41_39_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13941268/debug-Mo__Jan__15_17_41_39_2024.log)
