### ISSUE TITLE
[BUG] Peloton and Echelon auto resistance

### ISSUE THREAD

**Issue by Nklein86** [cagnulein/qdomyos-zwift#879]
**Describe the bug**
Auto resistance is a few points off the suggested resistance, different to how it used to be
[debug-Tue_Aug_2_07_20_20_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9245466/debug-Tue_Aug_2_07_20_20_2022.log)
[debug-Tue_Aug_2_07_53_14_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9245467/debug-Tue_Aug_2_07_53_14_2022.log)
[debug-Sun_Jul_31_17_20_59_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9245468/debug-Sun_Jul_31_17_20_59_2022.log)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @Nklein86 i checked your log and it seems fine to me. Here is an example

trainprogram::scheduler() "trainprogram change resistance14"
trainprogram::scheduler() "trainprogram change cadence92"
trainprogram::scheduler() "trainprogram change requested peloton resistance35"

peloton asks for resistance 35, QZ is setting 14 of echelon resistance.

This is the formula that it's on since the first day of QZ for echelon

// 0,0097x3 - 0,4972x2 + 10,126x - 37,08
where X is the echelon resistance

with X = 14 the result is 33,84 that it's ok. Infact 15 will be 35,67.

So could you please detail more the expected result? Thanks

**Comment by Nklein86** [comment]
It’s more noticeable at higher resistance. The ones I have noticed was when suggested 52, it puts me at 48 instead of 51. 
65 puts me at 57. 
Not a big deal, I turn the knob to catch up. But prior to getting a new phone it was closer to suggested resistance

**Comment by cagnulein** [comment]
you can use the peloton offset if you want a stable push, anyway i will
check again the maths with higher number but I didn't change anything
there. maybe in the older phone you have a different peloton offset setting?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 3 ago 2022 alle ore 14:42 Nklein86 ***@***.***>
ha scritto:

> It’s more noticeable at higher resistance. The ones I have noticed was
> when suggested 52, it puts me at 48 instead of 51.
> 65 puts me at 57.
> Not a big deal, I turn the knob to catch up. But prior to getting a new
> phone it was closer to suggested resistance
>
> Sent from my iPhone
>

**Comment by cagnulein** [comment]
Tue Aug 2 07:35:12 2022 1659440112132 Debug: /Users/cagnulein/qdomyos-zwift/src/trainprogram.cpp void trainprogram::scheduler() "trainprogram change requested peloton resistance 70"
Tue Aug 2 07:35:12 2022 1659440112228 Debug: /Users/cagnulein/qdomyos-zwift/src/echelonconnectsport.cpp void echelonconnectsport::update() "writing resistance 27"

resistance 27 is peloton resistance 64,7
resistance 28 is peloton resistance 69,5

you're right, at hight resistance there is something strange. I will investigate on this. Thanks

**Comment by cagnulein** [comment]
@Nklein86 fixed! it will be in the 2.11.16 and above! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and i will send you the new beta when it will be ready. Thanks again for the feedback!
