### ISSUE TITLE
Raspberry Pi WZero crashes when doing $ make -j4

### ISSUE THREAD

**Issue by IvanFernandezR** [cagnulein/qdomyos-zwift#88]
After doing $ make -j4, it is working about 1min and finally the raspberry crashes and I have to reboot manually.
What I'm doing wrong?
Thanks

**Comment by cagnulein** [comment]
Run just make, without -j4.
Pi0w has one only core and few ram :)
I should definitely report in the faq.

Il mer 23 dic 2020, 22:53 IvanFernandezR <notifications@github.com> ha
scritto:

**Comment by IvanFernandezR** [comment]
Hi @cagnulein!
Thanks for answering.
I tried again and now the proccess finished but I got an Error at the end.
Sorry because of so many questions but I am begginer in Raspberry and have no idea.
I think I am following the steps you described, but i am not achiving.
![image](https://user-images.githubusercontent.com/76537714/103111995-91a98280-4652-11eb-9a12-a0010946ba2e.png)

**Comment by cagnulein** [comment]
Do:
make clean
make

It should fix it
