### ISSUE TITLE
[BUG] 3d map shows white screen

### ISSUE THREAD

**Issue by z28kid** [cagnulein/qdomyos-zwift#880]
**Describe the bug**

Today when on my iphone 13, if I load a gpx and start riding with the map in "3d" mode. I was seeing nothing but a white screen. Worked in 2d mode.

**To Reproduce**
1. Make sure you're in the 3d mode for the gpx
2. Click on any gpx file and load/ start your ride
3. Touch the icon to enable the map.
5. White screen of death

**Expected behavior**
I expected to see the 3d map like prior

**Screenshots**
attached a blank white screen

**Smartphone (please complete the following information):**
 - Device: iphone 13 pro
 - OS: 15.6

![IMG_5468](https://user-images.githubusercontent.com/32517066/182982610-d659ec79-c4e4-4b80-9343-6bc760532158.jpeg)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**
[debug-Wed_Aug_3_19_35_26_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9264512/debug-Wed_Aug_3_19_35_26_2022.log)

**Comment by cagnulein** [comment]
hi @z28kid is this behaviour deterministic? did you try to restart QZ? If so, can you please share the gpx file that you're using?

**Comment by cagnulein** [comment]
hi @z28kid i found the issue, did you try to restart QZ? it's the same issue that #857 that @shmaddox had.
It seems that sometimes QZ stars on background and stays there. Infact in your log I saw that a QZ session starts at Wed Aug 3 19:35:26 2022 but you start riding at Thu Aug 4 17:30:16 2022

**Comment by cagnulein** [comment]
@p3g4asus i guess I finally understood the webserver error, check my comments above and the #857 
Now I have to think about a solution...

**Comment by p3g4asus** [comment]
Uhm: I will think about the a solution too. I think we need to debug what gets sent to javascript (if anything is actually sent). We absolutely need to write some rows on the log from the javascript code,

**Comment by cagnulein** [comment]
@p3g4asus i guess that iOS simply close the server without notifyng QZ: in the log there is nothing for 22 hours, so every QZ timers didn't fire too.
Maybe a simple workaround will be to check if the last log written was greater than a 1 hour ago, and then quit the app. Just to be sure to start on a clean condition. Or in that case, restart the webserver from scratch. I guess now we have a trigger, so we can use this ;)

**Comment by cagnulein** [comment]
@z28kid let's continue on the #857 thread, this one at the end is a duplicate

**Comment by z28kid** [comment]
Hey it’s curtis march, I rode both days actually. I can share the gpx file

**Comment by cagnulein** [comment]
@z28kid as I said after, it's not releated to the gpx then, just restart QZ and it should work. Let me know

**Comment by z28kid** [comment]
Will do, I usually close the app after every ride but I guess I didn’t force the watch app closed which is what might have kept it “on”

**Comment by cagnulein** [comment]
yes absolutely it could be the issue. If when you open the phone app, you will not see the QZ logo, remember to close it and reopen it ;) it's also a suggestion for @shmaddox
