### ISSUE TITLE
[BUG] Cannot get qdomyos to work with Peloton

### ISSUE THREAD

**Issue by sgarora** [cagnulein/qdomyos-zwift#881]
Hi,

Continuing from my YouTube comments-

I am trying to run qdomyos with Peloton split screen on an Echelon ex4s. I cannot get it to work. I've attached the debug log.

When I try to use my android phone to connect to the bike, I
[debug-Fri_Aug_5_09_09_39_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9264596/debug-Fri_Aug_5_09_09_39_2022.log)
 cannot get it to connect. It only connects with the qdomyos app running on the bike itself.

**Comment by cagnulein** [comment]
@sgarora I'm not sure that I understood completely the issue.
In the log I saw that the bike connects perfectly with QZ but after sometime, the bike disconnects itself.
Is QZ running always on foreground? Because on Android, QZ can't do on background otherwise will lose the bluetooth connection.
So this log is from the phone or the bike tablet?

**Comment by sgarora** [comment]
Hi,

This is from the bike. It is running in the foreground

**Comment by cagnulein** [comment]
@sgarora if it's from the bike it means that peloton was on side by side? probably that's the reason of the disconnection. For Android side by side means background, that's why it's disconnecting.

From the phone instead? is it working? do you have a debug log also from the phone?

**Comment by sgarora** [comment]
Even if peloton isn't open it disconnects. This is wywnnqdomyos is only
running, after a while the cadence will drop to zero and it won't show me
pedaling.

My phone doesn't connect with the bike at all.

**Comment by cagnulein** [comment]
leave for a moment the tablet, @sgarora  send me the debug log from the phone. Because on the tablet of the echelon i can't support it, I mean it's not officially supported. On the phone, instead, it has to work.
let me know

**Comment by sgarora** [comment]
Hi,

The debug log even though it doesn't connect?

**Comment by cagnulein** [comment]
yes, not connected but when the bike light it's blinking blue @sgarora

**Comment by sgarora** [comment]
Hi,

Does this attached log show auto resistance to be working? This was during
a Peloton ride

**Comment by cagnulein** [comment]
@sgarora you need to attach the file from github interface, via mail it doesn't come through

**Comment by sgarora** [comment]
[debug-Fri_Aug_5_21_35_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9269273/debug-Fri_Aug_5_21_35_11_2022.log)

Hi I've attached via github

**Comment by cagnulein** [comment]
@sgarora it's working in this log

 ```
"Current Local elapsed: 00:06:34"
 "Current Speed: 35.9977"
 "Current Calculate Distance: 2.40137"
 "Current Cadence: 96"
 "Current Distance: 3.9"
 "Current CrankRevs: 308"
 "Last CrankEventTime: 9863"
 "Current Watt: 79"
```

which issue do you have here?

**Comment by sgarora** [comment]
I was playing around with the app on the bike itself, I turned off virtual
and enabled a few things in the advanced section. I wasn't sure if the auto
resistance was working.

I know you don't support it but the app would connect to the bike and few
mins later it would beep again and then it would stop. By changing those
settings, the app seems to work even in the background. So it seems to be
working now. I still couldn't get my phone (s22+ ultra) to connect to the
bike though but I'll use it like this now.

**Comment by cagnulein** [comment]
@sgarora auto resistance is working in the log. I said the fact it's not supported because when there is strange issue, it's easier to start from a working scenario. So now that we know that both phone and bike works, we know for sure that the echelon tablet has something.

First of all in the tablet disable the "virtual device" in the experiemntal settings and restart QZ.

Let me know if it's better

If you have a debug log also for the s22+ I will check it

**Comment by cagnulein** [comment]
@sgarora any news?

**Comment by sgarora** [comment]
Just to confirm - auto resistance was working in that last log?

**Comment by cagnulein** [comment]
yes @sgarora
