### ISSUE TITLE
Elliptical NORDICTRACK C5.5

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#882]
![297663331_10221395511093467_457506430813096179_n](https://user-images.githubusercontent.com/48216/183089978-71298943-300e-4c09-8a24-b6805bfc48cc.jpeg)
![296728217_10221395510893462_7720921881707566655_n](https://user-images.githubusercontent.com/48216/183089984-4869df09-a5ce-41a3-8a00-8d65f7e2308f.jpeg)
![297449316_10221395510733458_6429931538331385039_n](https://user-images.githubusercontent.com/48216/183089988-785d1837-a654-40cc-8e54-bdce46915675.jpeg)
![297633025_10221395509013415_495588954539182502_n](https://user-images.githubusercontent.com/48216/183089993-596b1eda-ee24-4332-baa8-ae4459f85bd0.jpeg)

**Comment by cagnulein** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9270691/btsnoop_hci.log)

**Comment by xnaldax** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9274706/btsnoop_hci.log)
resistance step 1 (default) to 20 and 19 to 1

**Comment by xnaldax** [comment]
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9274791/btsnoop_hci.log)
resistance from app

**Comment by xnaldax** [comment]
QZ log - wrong speed 
[debug-Sat_Aug_6_17_53_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275386/debug-Sat_Aug_6_17_53_44_2022.log)

**Comment by xnaldax** [comment]
[debug-Sat_Aug_6_20_12_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275549/debug-Sat_Aug_6_20_12_41_2022.log)
+ button changed resistance to 2 (app showing 1 all the time) and next click to + or - button not changing resistance on elliptical

**Comment by xnaldax** [comment]
speed is correct with resistance 1, higher speed with others resistances
[debug-Sun_Aug_7_11_33_27_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9276541/debug-Sun_Aug_7_11_33_27_2022.log)

**Comment by cagnulein** [comment]
@xnaldax are you able to change resistance from the app now?

**Comment by xnaldax** [comment]
@cagnulein app can change resistance to 2 only and app is showing resistance 1 after change - button "+" and "-" do nothing after that

**Comment by cagnulein** [comment]
@xnaldax but the resistance change correctly to 2 on the elliptical?

**Comment by xnaldax** [comment]
@cagnulein yes, when I click on "+" from app resistance is changed to 2 on elliptical

**Comment by cagnulein** [comment]
@xnaldax found the resistance issue! now i'm focusing on speed

**Comment by cagnulein** [comment]
@xnaldax what i was thinking that was the speed I guess it's the wattage, because I saw that when you change the resistance, it increases, that's why you told me that the speed only works with speed at resistance 1.

**Comment by cagnulein** [comment]
@xnaldax ok i found also the speed! i'm implementing it!

**Comment by xnaldax** [comment]
@cagnulein speed isn't working on version 2.11.24 - showing 0 (worked on 2.11.22 for resistance 1)
- default resistance is 0 on APP, default resistance on elliptical is 1
- resistance is working perfect from 1 to 17 (up and down), when i want resistance 18 app will show resistance 1 (no change happend on elliptical) instead 18
- 
[debug-Sun_Aug_7_15_12_41_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9276864/debug-Sun_Aug_7_15_12_41_2022.log)

**Comment by cagnulein** [comment]
thanks! fixed both, i guess we almost get it :) @xnaldax

**Comment by xnaldax** [comment]
Switching resistance from 18 to 19 - app show resistance 1, elliptical switched to 19
[debug-Wed_Aug_10_15_32_16_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9300479/debug-Wed_Aug_10_15_32_16_2022.log)

**Comment by cagnulein** [comment]
fixed! @xnaldax i will send you a new one this evening!

**Comment by xnaldax** [comment]
@cagnulein everything is working perfectly now

**Comment by cagnulein** [comment]
yeah!

**Comment by xnaldax** [comment]
@cagnulein 
- fake device disabled: app connected with elliptical - speed isn't working on app, resistance is working
[debug-Mon_Aug_15_14_43_44_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9337412/debug-Mon_Aug_15_14_43_44_2022.log)

- fake device enabled - app can't connect with elliptical - it connect after click on "refresh Devices list" -  speed and resistance are not working
[debug-Mon_Aug_15_15_07_52_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9337415/debug-Mon_Aug_15_15_07_52_2022.log)

**Comment by cagnulein** [comment]
@xnaldax found a workaround, i will send you this tomorrow!

**Comment by xnaldax** [comment]
no speed on 2.11.28
[debug-Tue_Aug_16_18_26_13_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9352791/debug-Tue_Aug_16_18_26_13_2022.log)

**Comment by xnaldax** [comment]
v2.11.29 is working currently! Thank you!

**Comment by cagnulein** [comment]
great news @xnaldax !
