### ISSUE TITLE
Cable Bluetooth converter does not populate qdomyos screen

### ISSUE THREAD

**Issue by DTGreat** [cagnulein/qdomyos-zwift#884]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work
[debug-Sat_Aug_6_13_18_36_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9275609/debug-Sat_Aug_6_13_18_36_2022.log)
%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks @DTGreat , I guess I fixed, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta

**Comment by cagnulein** [comment]
@DTGreat i don't remember, did I send you the beta?
Let me know

**Comment by DTGreat** [comment]
Yes thank you. It worked well.

**Comment by cagnulein** [comment]
great!
