### ISSUE TITLE
docs/10_installation.md is outdated due to the addition of the multimedia module in the .pro file

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#885]
I was getting this after a recent pull: 

`Project ERROR: Unknown module(s) in QT: multimedia`

I found I needed to do this (or at least some of them):

`sudo apt-get install qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5`

**Comment by cagnulein** [comment]
done thanks!

**Comment by drmason789** [comment]
What do you think of adding a bash script to issue these commands, changing this .md file to tell the user to run the bash script, then all contributors need to do is update the bash script.

If you're agree, I'll make a new issue and do this.

**Comment by cagnulein** [comment]
mmm it should be fine but probably we need to do several scripts because every distro could have different packet name.
anyway we can add them time by time
nice idea!
