### ISSUE TITLE
[BUG] Echelon Row, the app connects to the rower but no metrics are getting reported.

### ISSUE THREAD

**Issue by mikek5** [cagnulein/qdomyos-zwift#886]
**Describe the bug**
Using the app with the Echelon Row, the app connects to the rower but no metrics are getting reported, except the resistance. Also, no heart rate from apple watch is being reported. It happens both on iPhone and iPad. If I connect to the echelon app, it displays the metrics.

**To Reproduce**
1. Turn on rower
2. Open the app
3. Connect
4. See bug

**Expected behavior**
Being able to see metrics.

**Screenshots**
![IMG_0757 - Copy](https://user-images.githubusercontent.com/110756034/183275895-e357e1f2-1e1e-49cc-9786-1497f8d67dcc.PNG)
![IMG_0756 - Copy](https://user-images.githubusercontent.com/110756034/183275898-312262db-ad45-41bc-a16c-44ff3786e894.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 15.5

**Append a debug log**
[debug-Sun-Aug-7-00-35-53-2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9276204/debug-Sun-Aug-7-00-35-53-2022.log)

During the logged session I connected to the rower, started the heart rate from apple watch, increased the resistance to 6 using the buttons on the handle, did about 5 strokes, pressed the stop button, closed the app.

**Comment by cagnulein** [comment]
thanks @mikek5 got the issue! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta!
