### ISSUE TITLE
t900c with pi0w intermittent crashes

### ISSUE THREAD

**Issue by rickoneeleven** [cagnulein/qdomyos-zwift#89]
helps massively with the -no-reconnection but if you're still interested in stopping the crashes in general:

it started up and crashed quite quick, treadmill stopped and then restarted (thanks to -no-reconnection)
[debug-Fri Dec 25 17_23_53 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742345/debug-Fri.Dec.25.17_23_53.2020.log)

now the following log is interesting, because I didn't even know it had crashed! only when looking at the logs did i find that it crashed here, but because of the -no-reconnection it auto reconnected and I was none the wiser! so i guess this this is less significant as it's kind of already resolved by -no-reconnection as the treadmill kept running
[debug-Fri Dec 25 17_24_25 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742347/debug-Fri.Dec.25.17_24_25.2020.log) ----> [debug-Fri Dec 25 17_35_44 2020.zip](https://github.com/cagnulein/qdomyos-zwift/files/5742350/debug-Fri.Dec.25.17_35_44.2020.zip)

**Comment by cagnulein** [comment]
Thank you for providing me the log.
I'm looking very quickly to your log and i saw a strange issue just before the crash happens

`Debug:   HCI event triggered, type: 13
Debug:   HCI event triggered, type: 13`

Usually it just one time I guess.
I will look into it

**Comment by rickoneeleven** [comment]
here's a log of the same happening today, although a lot further into the session. the auto reconnect (while loop) saved the day again, i'm so thankful for that implementation, but here's the log anyway incase you can get to the bottom of the crashes in the first place - although could just be my t900c with a poor bluetooth implementation?
[debug-Sun Dec 27 11_49_32 2020.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/5744904/debug-Sun.Dec.27.11_49_32.2020.log.zip)

**Comment by cagnulein** [comment]
this time there is not the double HCI event, so it's not releated...

**Comment by cagnulein** [comment]
i'm closing this one
