### ISSUE TITLE
[BUG] Resource leak in PathController

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#890]
This call can identify a device on a COM port as a geo-location device, when it actually isn't.

![image](https://user-images.githubusercontent.com/29954900/183779464-a419f2e2-6950-44da-a9ae-ba183d12b67a.png)

I found this when investigating why QZ couldn't open the port my Trixter X-Dream V1 bike was on #855. This bike uses a Prolific PL2303HXA Serial to USB converter. The problem occurs in Windows, but not Linux.

I found that whenever the bike was plugged in when QZ starts, QZ was not able to open the port, but if I plugged the bike in while QZ was already scanning, it would be detected. Looking at the handles qdomyos-zwift had open in Process Explorer, I discovered QZ was opening a handle called "\Device\ProlificSerial0" before any of my detection code that tries to open the port was reached. I found that if I delete the handle, QZ would connect to the bike. 

I eventually found that the handle appears when this call in the screenshot is made. So I checked if the coordinate coming out is valid. It isn't. So basically, this "source" hangs around, keeping the port open, while not doing anything useful.

**Comment by drmason789** [comment]
Here's a video clip of debugging through the fixed code. On thr right you can see Process Explorer, which shows the FILE handles open in the qdomyos-zwift process. The \Device\ProlificSerial0 appears during the call into createDefaultSource. The clip demonstrates that the source is returned, and the coordinate obtained from it is invalid. 
The source object is deleted, but the handle doesn't actually disappear until after the method is exited from (not sure why this is). In any case, it's gone by the time the code for the Trixter bike tries to open the port, which can be seen in the log with the bytes coming in, and the reappearance of a \Device\ProlificSerial0 FILE handle.

https://user-images.githubusercontent.com/29954900/184040869-ee622596-47c4-4d41-9e10-5bab0ee9808c.mp4

**Comment by cagnulein** [comment]
Thanks @drmason789 ! Merged!
The issue was about the fact that on QT on Windows the QT guys added also the possibility to talk with an external GPS by serial port (via NMEA codes) and that's why that they're scanning the port.
Of course QZ doesn't need this, so your patch is fine!
Thanks for this troubleshooting! It was a really hidden bug!
