### ISSUE TITLE
[BUG] Resistance tile labelling indicates %, but it's not really

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#895]
The resistance tile is labelled to indicate its numbers refer to a % resistance:

![image](https://user-images.githubusercontent.com/29954900/184444379-5cf34dbe-02e1-428a-a9d2-22e58442e221.png)

However, it isn't really.

The bluetoothdevice sublass I am testing this with overrides maxResistance() to return 250 (see the Resistance box on the right of the bottom window in the video), which is the device's maximum resistance. However, the bike::changeResistance(int8_t) slot is being sent values up to 127, the upper limit of the argument's data type of int8_t.

https://user-images.githubusercontent.com/29954900/184446323-83d4891c-2b06-4d56-9733-46dc08e184fd.mp4

Perhaps it could be made a rule that bike::changeResistance(int8_t) will be sent a percentage from 0 to 100, and it should adjust according to whatever maxResistance() returns for the class.

Or perhaps the tile could calculate an increment, scale = 0.01 * bike::maxResistance() and send its (the tile's) current value * scale to bike::changeResistance(int8_t).

**Comment by cagnulein** [comment]
you're right, this is not a %. It's a raw value from each bike. So I'm just removing the %

**Comment by drmason789** [comment]
I see you've removed the % sign. 

There is still the problem if the device supports more than 127 resistance levels, the int8_t parameter on the changeResistance slot is too small.

**Comment by cagnulein** [comment]
hah sorry I didn't read it carefully. So we need to change the int8 to int16 everywhere

**Comment by drmason789** [comment]
I could do this if you prefer.

**Comment by cagnulein** [comment]
hah ok thanks! In these days I have my wife at the hospital so I'm quite busy

**Comment by drmason789** [comment]
Perhaps I should 

`#define resistance_t int16_t`

and use that. There are many locations to change.

**Comment by cagnulein** [comment]
Yes sounds good. Also all the slots and signals must be changed...

**Comment by drmason789** [comment]
I've got this done. 

Perhaps another issue with power_t, pelotonResistance_t, heartRate_t, ...

**Comment by drmason789** [comment]
I've done the testing I can by merging into a branch of my branch for #855 - it seems to work. 

https://user-images.githubusercontent.com/29954900/184517624-60e3088a-2757-451b-84e6-74a34829447a.mp4

**Comment by drmason789** [comment]
@cagnulein Do you prefer to be the one that closes issues?

**Comment by cagnulein** [comment]
> @cagnulein Do you prefer to be the one that closes issues?

no absolutely:)
