### ISSUE TITLE
Bike connecting, but not sending data

### ISSUE THREAD

**Issue by Stewe1977** [cagnulein/qdomyos-zwift#896]
My indoor bike (Progressive XF1000) has a built-in sensor with Bluetooth output.  QZ recognizes the bike as FS-BF09B3, but all the data on the display shows 0. Other programs, like Zwfit or Kinomap recognize the bike fine. 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52 5G
 - OS: Android
 - Version 12

Attached the debug log
[debug-Sat_Aug_13_12_12_11_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9331224/debug-Sat_Aug_13_12_12_11_2022.log)

**Comment by cagnulein** [comment]
hi @Stewe1977 try enabling this one ![image](https://user-images.githubusercontent.com/48216/184480181-08e71b43-d17c-4383-bb5e-103e0e35b886.jpeg)

**Comment by Stewe1977** [comment]
Thank you very much, now it works!
