### ISSUE TITLE
Frequent disconnects with zwift, logs attached

### ISSUE THREAD

**Issue by venkateshks** [cagnulein/qdomyos-zwift#90]
[debug-Fri Dec 25 21_41_11 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742760/debug-Fri.Dec.25.21_41_11.2020.log)
[debug-Fri Dec 25 21_59_35 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742761/debug-Fri.Dec.25.21_59_35.2020.log)
[debug-Fri Dec 25 21_52_24 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742762/debug-Fri.Dec.25.21_52_24.2020.log)
[debug-Fri Dec 25 22_16_27 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742763/debug-Fri.Dec.25.22_16_27.2020.log)
[debug-Fri Dec 25 22_06_48 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742764/debug-Fri.Dec.25.22_06_48.2020.log)
[debug-Fri Dec 25 22_21_04 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742765/debug-Fri.Dec.25.22_21_04.2020.log)
[debug-Fri Dec 25 21_47_33 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742766/debug-Fri.Dec.25.21_47_33.2020.log)
[debug-Fri Dec 25 21_50_37 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742767/debug-Fri.Dec.25.21_50_37.2020.log)
[debug-Fri Dec 25 21_46_26 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742768/debug-Fri.Dec.25.21_46_26.2020.log)
[debug-Fri Dec 25 21_55_23 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742769/debug-Fri.Dec.25.21_55_23.2020.log)
[debug-Fri Dec 25 21_56_32 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742770/debug-Fri.Dec.25.21_56_32.2020.log)
[debug-Fri Dec 25 21_57_56 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742771/debug-Fri.Dec.25.21_57_56.2020.log)
[debug-Fri Dec 25 22_04_46 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742772/debug-Fri.Dec.25.22_04_46.2020.log)
[debug-Fri Dec 25 22_18_37 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742773/debug-Fri.Dec.25.22_18_37.2020.log)
[debug-Fri Dec 25 22_02_27 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742774/debug-Fri.Dec.25.22_02_27.2020.log)
[debug-Fri Dec 25 21_49_54 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742775/debug-Fri.Dec.25.21_49_54.2020.log)
[debug-Fri Dec 25 22_09_38 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742776/debug-Fri.Dec.25.22_09_38.2020.log)
[debug-Fri Dec 25 22_03_21 2020.log](https://github.com/cagnulein/qdomyos-zwift/files/5742777/debug-Fri.Dec.25.22_03_21.2020.log)

**Comment by cagnulein** [comment]
Ok @venkateshks as i said on messenger, let's see if the relaxed bluetooth setting helps.
Let me know

**Comment by venkateshks** [comment]
@cagnulein I did another ride today, with experimental feature enabled. I still saw frequent disconnects (even though I didnt see multiple duplicate entries anymore). I was using HRM from garmin, through an ANT+ dongle. Once I unpaired the HRM, kept the HRM far away (so that my laptop would not see the bluetooth) I was able to ride without any disconnects for an hour. I have the logs for this too.

**Comment by venkateshks** [comment]
I will try again in the my next ride to connect my HRM using bluetooth and see if that improves connection stability.

**Comment by cagnulein** [comment]
I will add a feature to connect hr directly on my app if it helps

**Comment by venkateshks** [comment]
@cagnulein Dont bother for now. Though it would help for other users. It worked well this time, did a 1hr ride with bluetooth HRM (without ANT+ dongle).  So disconnects, if it happens again will report here. Else we can close this issue
