### ISSUE TITLE
Peloton resistance conversion seems to have changed

### ISSUE THREAD

**Issue by Skpipak** [cagnulein/qdomyos-zwift#901]
The Echelon to Peloton conversion seems different than it was previously

12 Echelon used to convert to 30 Peloton, but now it's converting to 29.

Unfortunately I don't have any debug from before this change but I've attached two from after the change.

Let me know if additional information is helpful. Thank you. 

[debug-Thu_Aug_18_07_14_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9375826/debug-Thu_Aug_18_07_14_03_2022.log)
[debug-Wed_Aug_17_17_31_27_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9375831/debug-Wed_Aug_17_17_31_27_2022.log)

**Comment by cagnulein** [comment]
@Skpipak I'm trying to understand what could be changed but i'm not finding any reason. The conversion of echelon resistance 12 is 29.6 to peloton, so we are in the middle (so for sure it doesn't change anything on your workout).
But when was the last time you saw 30? Do you remember which version was?

**Comment by Skpipak** [comment]
Sorry I'm not sure exactly. I'm running the beta version and updated the
app earlier this week, and that's when it changed.  That said I don't
always update the app everytime an update is available so I'm not sure on
the exact versions.

You've mentioned before how the output calculation is the same, and now it
seems to be more of a display/rounding thing. I can just get used to how it
is now.

I had thought originally that the whole conversion chart changed or
something like that and was just concerned my output wouldn't be comparable
to the past. Seems that's not the case so that's good!

**Comment by cagnulein** [comment]
good news @Skpipak i guess I found your issue https://github.com/cagnulein/qdomyos-zwift/commit/c986b9ad4bc713defe2733c6ba3550ad037ed6ca
I'm reverting it and I will send a new version today **2.11.30**
let me know!

**Comment by Skpipak** [comment]
Wow! Okay thanks. I'll download it when I see it and plan to try it out
tomorrow!

**Comment by cagnulein** [comment]
@Skpipak it's available already now ;)

**Comment by Skpipak** [comment]
I see it now! Thanks! Planning to ride within the hour so will try it out!

**Comment by Skpipak** [comment]
The Peloton converted resistance is back like it was originally. Thank you!

**Comment by cagnulein** [comment]
great! thank you for your precious feedback!
