### ISSUE TITLE
[BUG zwift-auto resistance 

### ISSUE THREAD

**Issue by rica2323** [cagnulein/qdomyos-zwift#908]
Hello, 

I have a domyos fold bike from Decathlon.
I downloaded qdomyos-zwift, but auto resistance doesnt work in Zwift app.
Could you check my debug file?

**Comment by cagnulein** [comment]
@rica2323 hi i don't see the debug file here

**Comment by rica2323** [comment]
I’m sorry

Stáhnout Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: Roberto Viola ***@***.***>
Odesláno: Monday, August 22, 2022 9:38:00 PM
Komu: cagnulein/qdomyos-zwift ***@***.***>
Kopie: rica2323 ***@***.***>; Mention ***@***.***>
Předmět: Re: [cagnulein/qdomyos-zwift] [BUG zwift-auto resistance (Issue #908)


@rica2323<https://github.com/rica2323> hi i don't see the debug file here

**Comment by cagnulein** [comment]
@rica2323 you need to attach it directly from the github page

**Comment by rica2323** [comment]
[1QZ-backup-po srp 22 21_15_52 2022.zip](https://github.com/cagnulein/qdomyos-zwift/files/9400367/1QZ-backup-po.srp.22.21_15_52.2022.zip)

**Comment by cagnulein** [comment]
@rica2323 this is the fit file, i need the debug log file

**Comment by rica2323** [comment]
Unfortunately i can’t find this file in my iPhone…

Stáhnout Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: Roberto Viola ***@***.***>
Odesláno: Tuesday, August 23, 2022 9:42:48 AM
Komu: cagnulein/qdomyos-zwift ***@***.***>
Kopie: rica2323 ***@***.***>; Mention ***@***.***>
Předmět: Re: [cagnulein/qdomyos-zwift] [BUG zwift-auto resistance (Issue #908)


@rica2323<https://github.com/rica2323> this is the fit file, i need the debug log file

**Comment by cagnulein** [comment]
share a screenshot here of your files app on ios @rica2323

**Comment by rica2323** [comment]
Stáhnout Outlook pro iOS<https://aka.ms/o0ukef>
________________________________
Od: Roberto Viola ***@***.***>
Odesláno: Thursday, August 25, 2022 7:24:44 AM
Komu: cagnulein/qdomyos-zwift ***@***.***>
Kopie: rica2323 ***@***.***>; Mention ***@***.***>
Předmět: Re: [cagnulein/qdomyos-zwift] [BUG zwift-auto resistance (Issue #908)


share a screenshot here of your files app on ios @rica2323<https://github.com/rica2323>

**Comment by cagnulein** [comment]
@rica2323 you have to attach the screenshot directly from the github website. Thanks

**Comment by rica2323** [comment]
![Uploading EDB1BF54-B323-4EA5-BED4-4B472182DDFC.png…]()

**Comment by cagnulein** [comment]
@rica2323 you need to wait the end of the upload before pressing the submit button :/

**Comment by rica2323** [comment]
![20FC36FC-4BC3-452D-AA47-A8CD670E922A](https://user-images.githubusercontent.com/111796046/187026597-31290764-2cf8-4d05-86f4-5aa12515949c.png)

**Comment by cagnulein** [comment]
@rica2323 are you sure debug log
is on? could you please share a screenshot of your experimental settings?

**Comment by cagnulein** [comment]
@rica2323 any news?
