### ISSUE TITLE
[REQ] Automated testing

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#911]
@cagnulein  You've suggested this before [here](https://github.com/cagnulein/qdomyos-zwift/pull/888#issuecomment-1209305409)

Suggestions for making a start:
- new folder alongside src called tst
- project file tst/qdomyos-zwift-tests.pro
- folders for the tests for each device

**Comment by drmason789** [comment]
I can make a start by importing my Google tests for the trixterxdreamv1client class.

**Comment by cagnulein** [comment]
ok thanks, I was thinking about QT tests because so it will be all integrated on the IDE but I never did a test class so I'm a newbie on this.

**Comment by drmason789** [comment]
I would convert them to Qt tests. I just want to check you're okay with the file system organisation before doing anything.

**Comment by cagnulein** [comment]
great! thanks! yes the fs proposed is perfect to me

**Comment by cagnulein** [comment]
A first level of testing could be injecting each Bluetooth name in the discovery functions checking if a device will be created 

Every fitness machine module must be its Bluetooth name lists to test

**Comment by drmason789** [comment]
[Connecting the projects](https://dragly.org/2014/03/13/new-project-structure-for-projects-in-qt-creator-with-unit-tests/)

**Comment by drmason789** [comment]
It seems that with QtTest you can only have 1 test class per project, otherwise QtCreator won't recognise the test class.

Consequently I've copied the structure of the Qt source code and used a tree of projects using the SUBDIRS template, with the tests at the leaf nodes. 

The project that includes the main application and the test projects is in the root directory, qdomyos-zwift.pro.

No classes from the main project instantiated in the tests yet.

**Comment by drmason789** [comment]
I believe I'm going to need to change something so that the current qdomyos-zwift executable produced from the code in src must be a lib output, for the test project to link its outputs to.

I have a couple of ideas to explore:
1. Define much of the src/qdomyos-zwift.pro in a pri file that is shared between two replacement pro files that include this and differ only in that one specifies TEMPLATE = app and the other TEMPLATE = lib 
2. Split the current /src code into an app for the UI and a lib project for the devices and other "business". Then have the tests link to the lib project.

**Comment by drmason789** [comment]
I've implemented approach 1 and have a test case that creates an activiotreadmill object working.

Next up, testing the bluetooth name recogniser.

**Comment by drmason789** [comment]
@cagnulein  If you want to take a look, open the qdomyos-zwift.pro file in the root directory, not the src directory. This contains references to the lib project and the test project. 

I had the app project in there as well, but QtCreator kept building it when I built the test project even though I didn't specify it as a dependency. I've removed it for now,

**Comment by cagnulein** [comment]
this one right? https://github.com/drmason789/qdomyos-zwift/blob/automated_testing_911/qdomyos-zwift.pro
I never did a test project on QT so it will be the first time for me too. Looks like you did exactly what I was thinking! The tree looks really clean!

**Comment by drmason789** [comment]
Yes, that's the one. 

I don't know that this is the most optimal layout. The build times for me are horrendous, compared with similar projects in C#/.NET.  E,g, 10 minutes instead of 10s. We may get a far quicker build time if all the tests go in 1 huge class.

Additionally, the way I have things now, if you add a file to the src project, it has to be removed from the pro file and put into the pri file so it is shared between the lib and app pro files. I think it would be better to commit to at least a 3 project structure:

app/qdomyos-zwift
lib/qdomyos-zwift-lib
tst/qdomyos-zwift-test

app: UI components, links to the lib output
lib: static library, contains devices and bluetooth functionality
tst: testing project, links to lib output.

**Comment by drmason789** [comment]
I've added the beginnings of a test for bluetooth::deviceDiscovered, with some skeleton code to pass in a name and see if bluetooth::device() returns the right type of object. I'm going to want to refactor this class a bit so it can be created without starting bluetooth discovery, so the test can target just the device recognition.

Unfortunately I've into linking errors again, so the tests are not working.

**Comment by drmason789** [comment]
Note to self: 

The DECLARE_TEST macro might help to avoid having a tree of projects and the associated configuration work.

http://qtcreator.blogspot.com/2009/10/running-multiple-unit-tests.html

**Comment by drmason789** [comment]
I'm really not happy with QtTest and QtCreator. I plan to try out one more arrangement, then try Google Test.

**Comment by drmason789** [comment]
I've reverted to the more standard (for Qt) structure of 1 test case (class) per project, with these projects in a subdirs template project, itself in a subdirs template project. It's not building currently, and I've abandoned QtTest for now. There's probably something simple to be done with project setup or makefile configs to make it share code with other subprojects, but I don't want to spend time hunting for it. Compared to .NET/C#.Visual Studio, there seems to be lot of messing around with project config to achieve simple things.

I think the expectation for Qt is that there be one test case (class) which an unspecified number of tests in it, per project, with each such project a subproject within a subdirs template project. QtCreator looks for the use of QTEST_MAIN, QTEST_APPLESS_MAIN or QTEST_GUILESS_MAIN to find tests. There can be only one use of these per project. I think that QtCreator only directly supports 1 test case (a group of tests in a class) per project. 

There is the autotest workaround, but QtCreator doesn't recognise it's DECLARE_TEST macro so the tests don't appear the UI. Apparently you can recompile QtCreator so it does. I worked around this by using the QTEST_APPLESS_MAIN macro inside the class definitions. However, although the tests all appeared in the UI, if I tried to run 1, they all ran.

Additionally, it's C++, each cpp file built into an object file then linked together to form a library or executable. Building the while project takes several minutes on my machine. With VS/.NET/C# and mstest or nunit, for example, projects of similar size take seconds to build, a test project can be created in seconds, it can have thousands of tests spread over many test fixtures, the tests viewed, run and debugged from VS's test explorer or Resharper. 

I've abandoned QtTest for now. I'll try out Google Test next. QtCreator supports it.

**Comment by cagnulein** [comment]
ok @drmason789 they seem all reasonable motivation to abandon QtTest :) and the fact that QtCreator supports natively Google Test seems another push to this technology. Let me know how it will go! Thanks!

**Comment by drmason789** [comment]
Current problem: QtCreator won't stop on breakpoints when running Google tests.

**Comment by drmason789** [comment]
@cagnulein 

In my test for the Renpho bike detection, with the bluetooth device name set to "TOORX" and toorx_ftms enabled in the settings, this combination is identified this combination as the TrxAppGateUSBTreadmill, not the Renpho bike. 

Is this expected? 

https://github.com/cagnulein/qdomyos-zwift/blob/c2d0176b67d84424d82b5e9cd6063633153a759d/src/bluetooth.cpp#L1631-L1636

**Comment by cagnulein** [comment]
@drmason789 confirmed, the toorx bike in that case has a ftms behavior so the same of renpho bikes

**Comment by drmason789** [comment]
@cagnulein Do you have an example for valid manufacturer data for the m3ibike for testing its "isCorrectUnit" criteria?

**Comment by drmason789** [comment]
[Helpful video for Qt and Google Test](https://www.ics.com/webinars/qt-test-driven-development-using-google-test-google-mock-video-demand) Not much help for UI tests though.

**Comment by drmason789** [comment]
@cagnulein  This is now in a state where you could try it out for yourself. It's not creating the actual bluetoothdevice objects, but it's setting up test scenarios that have the bluetooth class identify the device and produce an enumeration value which a bluetooth class instance running in that application could then use to create the object.

Currently creating an instance of the bluetooth class crashes the test application because it communicates with the UI. I believe I will need to decouple this class from the template managers in order to proceed.

**Comment by cagnulein** [comment]
> @cagnulein Do you have an example for valid manufacturer data for the m3ibike for testing its "isCorrectUnit" criterion?

@p3g4asus any hints?

**Comment by cagnulein** [comment]
@drmason789 wow I will check in these days!

**Comment by p3g4asus** [comment]
> > @cagnulein Do you have an example for valid manufacturer data for the m3ibike for testing its "isCorrectUnit" criterion?
> 
> @p3g4asus any hints?

I will collect some hex data ASAP.
Unfortunately I am currently not using my bike because, as you know, I am seriously injured. But I can easily collect some data.

**Comment by drmason789** [comment]
>I will collect some hex data ASAP.
>Unfortunately I am currently not using my bike because, as you know, I am seriously injured. But I can easily collect some data.

@p3g4asus Thanks. 

`

**Comment by drmason789** [comment]
@cagnulein I've added code to test the bluetooth object creating bluetoothdevice instances using the enum value from the detection part. There are some new failures because some objects are trying to start a timer on a thread not started with QThread.

I also found an issue with SignalHandler from which the bluetooth class inherits. It only allows 1 instance per process - after the first one is deleted, the assert in the constructor fails because g_handler is not set back to NULL by the destructor. I prefer to create a new bluetooth object for each test so I changed the SignalHandler destructor to set the g_handler back to NULL. Do you think this will be problematic elsewhere?

**Comment by drmason789** [comment]
> @drmason789 confirmed, the toorx bike in that case has a ftms behavior so the same of renpho bikes

The problem I perceive is that the Renpho bike will never be detected because those conditions lead to the other devices first.

If the bluetooth device name is "TOORX12234" and toorx_ftms==true in the settings, which bluetoothdevice object should be created? Because if toorx_bike is enabled, the trxappgateusbbike comes first, then if toorx_bike is disabled then trxappgateusbtreadmill comes first.

**Comment by cagnulein** [comment]
> I also found an issue with SignalHandler from which the bluetooth class inherits. It only allows 1 instance per process - after the first one is deleted, the assert in the constructor fails because g_handler is not set back to NULL by the destructor. I prefer to create a new bluetooth object for each test so I changed the SignalHandler destructor to set the g_handler back to NULL. Do you think this will be problematic elsewhere?
> 

No i guess not, it should be used only on the Linux build actually

**Comment by cagnulein** [comment]
> > @drmason789 confirmed, the toorx bike in that case has a ftms behavior so the same of renpho bikes
> 
> 
> 
> The problem I perceive is that the Renpho bike with bluetooth name starting with "TOORX "will never be detected because those conditions lead to the other devices first.
> 
> 
> 
> If the bluetooth device name is "TOORX12234" and toorx_ftms==true in the settings, which bluetoothdevice object should be created? Because if toorx_bike is enabled, the trxappgateusbbike comes first, then if toorx_bike is disabled then trxappgateusbtreadmill comes first. 
> 
> 

Yes this is a classic example of settings conflicts. I didn't have the time in the past to avoid these kind of conflicts in the settings qml so now you're seeing this because of my laziness :)

So answering to your question, yes what you are seeing it's normal, and I tag this as an "user error" :)

Is it possible to run several test run for the same type of device (using different settings)?
Thanks

**Comment by p3g4asus** [comment]
> > I will collect some hex data ASAP.
> > Unfortunately I am currently not using my bike because, as you know, I am seriously injured. But I can easily collect some data.
> 
> @p3g4asus Thanks.
> 
> `

Here are some data captured from my bike in hex format (each line represents the content of the QByteArray given in input to parse_data):
02010639009F00000000000000000014008001
02010639009F00000000000000000014008001
02010639009FBA000000020000000014008001
02010639009FBA000000020000000013008001
02010639009FBA000000020000000013008001
02010639009FBA000000020000000012008001
02010639009FBA000000020000000012008001
02010639009FBA000000000000000011008001
02010639009FBC000000020000000010008001
02010639009FBC000000020000000010008001
02010639009FBC00000002000000000F008001
02010639009FBC00000002000000000F008001
02010639009FBC00000002000000000E008001
02010639009FBC00000002000000000E008001
02010639009F0000000003000000000C000001
02010639009FDD00000003000000000C000001
02010639009FDD00000003000000000C000001
02010639009FDD00000003000000000B000001
02010639009FDD00000003000000000B000001
02010639009FDD00000003000000000B000001
02010639009FDD00000003000000000A000001
02010639009FDD00000003000000000A000001
02010639009F0000000000000000000A000001
02010639009FE8000000030000000009000001
02010639009FE8000000030000000009000001
02010639009FE8000000030000000009000001
02010639009FE8000000030000000008000001
02010639009FE8000000030000000008000001
02010639009FE8000000030000000008000001
02010639009FE8000000030000000007000001
02010639009FE8000000030000000000000001
02010639009FD3000000030000000000000001
02010639009FD3000000030000000000000001
02010639009FD3000000030000000000000001
02010639009FD3000000030000000000000001
Please let me know if this is enough for you or you need anything more / different.

**Comment by drmason789** [comment]
@p3g4asus 
> Please let me know if this is enough for you or you need anything more / different.

Thanks, the 1st line was enough to make a passing test. I've left the rest in as a comment for future consideration.

**Comment by drmason789** [comment]
@cagnulein 

> Is it possible to run several test run for the same type of device (using different settings)?

Currently only 2 scenarios: a set of settings that enables and a set of settings that disables.  I have already observed how it is preferable to produce all the combinations that need testing as there are multiple enabling and multiple disabling combinations in some cases.

It's already dealing with multiple names - I can make it deal with multiple settings configurations.

**Comment by drmason789** [comment]
@cagnulein 

> So answering to your question, yes what you are seeing it's normal, and I tag this as an "user error" :)

Current behaviour:
```
Name		toorx_bike	toorx_ftms	detected
--------------------------------------------------------
TOORX1234	true		true		trxappgateusbbike
TOORX1234	true		false		trxappgateusbbike
TOORX1234	false		true		trxappgateusbtreadmill
TOORX1234	false		false		trxappgateusbtreadmill
```
What I think you want:

```
Name		toorx_bike	toorx_ftms	detected
--------------------------------------------------------
TOORX1234	true		true		renphobike
TOORX1234	true		false		trxappgateusbbike
TOORX1234	false		true		renphobike
TOORX1234	false		false		trxappgateusbtreadmill
```

**Comment by cagnulein** [comment]
> What I think you want:
> 
> ```
> Name		toorx_bike	toorx_ftms	detected
> --------------------------------------------------------
> TOORX1234	true		true		renphobike

renphobike or trxappgateusbbike in this case could be right both. I mean, since there is a conflict, one of them are ok. Of course the perfection will be disabling the opposite setting, once the user is enabled one

> TOORX1234	true		false		trxappgateusbbike
> TOORX1234	false		true		renphobike

mmm...no in this case is correct the trxappgateusbtreadmill because the user doesn't want to treat is TOORX device as a bike (maybe because it's a treadmill and it just forgot to disable the toorx_ftms)

> TOORX1234	false		false		trxappgateusbtreadmill
> ```

So at the end, I would leave the thing as they are

**Comment by drmason789** [comment]
Well, if you change your mind about leaving it as is, perhaps deprecate the toorx_* settings in favor of a new text/enum setting:

```
Name		toorx_device	detected
--------------------------------------------------------
TOORX1234	FTMS		renphobike
TOORX1234	Bike		trxappgateusbbike
TOORX1234	Treadmill	trxappgateusbtreadmill
```

Update policy from older versions:

```
toorx_bike	toorx_ftms	toorx_device
--------------------------------------------------------
true		true/false	Bike
false		true/false	Treadmill
```

**Comment by drmason789** [comment]
@cagnulein Is there way to do an iOS build on Windows or Linux?

**Comment by cagnulein** [comment]
Thanks for the suggestion, but I guess there is more important things to do :)

**Comment by drmason789** [comment]
I did the initial tests using a basic TEST_F for each test data class. In QtCreator, this means every test is detected and can be run individually. It has the downside that you need to have a TEST_F for each test, for every test data class. The test I'm doing here tests a few things that I'd rather split up into many tests.

https://user-images.githubusercontent.com/29954900/200665936-e6a92db2-601c-473c-9b50-34da6ea0a75a.mp4

**Comment by drmason789** [comment]
Next, I tried using the parameterised test functionality. I've copied the test functionality into a different test suite class and have 1 TEST_P that is used for all the test data classes that are supplied via some supporting code I have elsewhere. I am using a name_generator as the 4th arg to  INSTANTIATE_TEST_SUITE_P to call into the test data object to get the test name.
This way, to add a new device, you just set up its test data class (or classes, depending on the detection conditions) and add them to a test data registration method somewhere else. Then they are included in the parameterised test.

Downside: with these named tests, QtCreator won't let you run or debug one individually.

https://user-images.githubusercontent.com/29954900/200667017-64969696-b7d0-4182-b4a8-672ec06f5b10.mp4

**Comment by drmason789** [comment]
If I comment out the name_generator, the tests in the test results are simply numbered, and you can run each one individually:

https://user-images.githubusercontent.com/29954900/200667767-a3092ef9-ec44-4f4e-be54-0fa69d8fd2be.mp4

**Comment by drmason789** [comment]
I'll see what I can do with type parameterized tests. These are value parameterized tests. Previously I had difficulty getting QtCreator to recognise those at all, but what I was trying to do was based on something I typically to in C#/NUnit and probably not what the creators of Google Test intended.

**Comment by drmason789** [comment]
Typed tests, not quite Type Parameterized Tests gets me a list of tests with test data class type names. So there is an initial run of all the tests in the suite to get the test case details, but after that, you can select individual tests.

![image](https://user-images.githubusercontent.com/29954900/200679382-09d0d740-0603-4bb0-bb29-b460f7c0db2b.png)

**Comment by drmason789** [comment]
I'm considerably happier with this configuration, which uses typed tests.

https://user-images.githubusercontent.com/29954900/200687927-1fb684f0-bff0-41f4-b7d6-5e758bcfc4ce.mp4

**Comment by cagnulein** [comment]
wow! Looks very clean!

**Comment by cagnulein** [comment]
Is it possible also to run on a Github action?

**Comment by drmason789** [comment]
> Is it possible also to run on a Github action?

I expect so, I believe it's just a matter of running an executable and doing something with the results.

**Comment by drmason789** [comment]
I'm going with the "typed tests" approach and I've reworked the original 1 large test into multiple smaller tests, and have changed it to use the bluetooth class the way it currently works in the master, rather the refactored one from #996.

It's not working at the moment.  I'm about to switch to configuring the QSettings for each test, rather than the way I was doing this previously (bypass the QSettings for testing, and using the devicedetectionoptions class in bluetooth itself).

**Comment by drmason789** [comment]
Last working [commit](https://github.com/drmason789/qdomyos-zwift/commit/faa6bdf4cf9040890c9eb5c4eaec34b44750ba1e).

**Comment by drmason789** [comment]
By this [commit](https://github.com/drmason789/qdomyos-zwift/commit/11848c6abb8085d9658858ebe3e4eea960247a5f) tests are running, but some are failing.  I need to get the code to use the test QSettings rather than the default one.

**Comment by drmason789** [comment]
![image](https://user-images.githubusercontent.com/29954900/210021436-4a4874da-26de-442a-b42a-a28cc1769794.png)

**Comment by cagnulein** [comment]
merry christmas @drmason789 :)

**Comment by drmason789** [comment]
I'm about to create a PR for this.

The tests are not all passing. This is because some bluetoothdevice classes cannot be instantiated without the presence of the device they represent. This problem also affects the tests where a device that would otherwise be detected is not detected because a different device has already been detected.

![image](https://user-images.githubusercontent.com/29954900/210260034-1cbbbb66-04f0-4a49-b8fa-edd81bddb383.png)

I don't consider it a good use of time to fix this at the moment. If we split the device detection if statement into 2 phases, 1 that detects and returns an enum value, and another that creates the bluetoothdevice object, we can do this exclusion using only the enum values and not need the excluding device object created. 

Additionally, to test the device creation itself, we could rework the problem classes to be creatable, but not required a signal from the device they represent until they've been instructed to connect to it.

![image](https://user-images.githubusercontent.com/29954900/210260095-a331771d-3f86-4ca4-8a16-a21e5ff5ef4e.png)

There are 5 basic tests for device detection:
- Test that a device is not detected if its exluding devices have already been detected.
- Test that if a device is enabled in the settings, and no excluding devices have already been detected, the device under test will be created if a valud bluetooth name is provided.
- Test that if a device is disabled in the settings, and no excluding devices have already been detected, the device under test will NOT be created if a valid bluetooth name is provided.
- Test that for devices whose detected depends on valid bluetooth device info data, invalid bluetooth device info prevents detection.
- Test that if a device is enabled in the settings, and no excluding devices have already been detected, the device under test will NOT be created if an invald name is provided. e.g.starts with correct text, but not the right length and/or wrong case.
     
Looking through the test results you'll see many have been skipped. If you click in you can see the reason.
- Not all the devices have invalid names defined in test data
- Not all the devices have disabling QSettings configurations
- Only 1 device depends on bluetooth device info. 
- Many devices don't have excluding devices.

![image](https://user-images.githubusercontent.com/29954900/210260283-8015864e-5d0e-4541-8860-db52ca9dd873.png)
