### ISSUE TITLE
[REQ] Additional Bluetooth Remote Functionality

### ISSUE THREAD

**Issue by throw-away1** [cagnulein/qdomyos-zwift#914]
The current use of Bluetooth remote volume controls to change gears works great. Would it be possible to expand functionality of the remote? For example, using the skip forward/backward buttons to increase/decrease 5 gears with a single press. 

Thanks!

**Comment by cagnulein** [comment]
done @throw-away1 
as you requested I add the +/- 5 gears on the next/previous event. Let's see if it works, if so, we can add more settings to override the behaviour. What do you think?

**Comment by cagnulein** [comment]
@throw-away1 did you receive the beta?
