### ISSUE TITLE
"Virtual Treadmill"

### ISSUE THREAD

**Issue by gadi247** [cagnulein/qdomyos-zwift#917]
Looking to use a Treadmill without linking to the Tread itself. Virtual HR and Virtual device gets QZ started but info like Target Speed and Incline are not coming through because its not recognizing its a Treadmill in QC

**Comment by cagnulein** [comment]
done @gadi247 i'm pushing the version 2.11.41 in the private beta channel. Let me know when you will try it!

**Comment by gadi247** [comment]
Cool - waiting for the push
