### ISSUE TITLE
Spirit Xt485 Treadmill Connection (Log file attached)

### ISSUE THREAD

**Issue by gmoo2546** [cagnulein/qdomyos-zwift#918]
Hi Roberto - as requested my HCI snoop log is attached below. Please let me know if this is what you need!

Turned on treadmill, started treadmill app (Spirit Fit), connected treadmill to app. Started walk on treadmill, adjusted speed and incline. 

Thanks again!

[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9472838/btsnoop_hci.log)

**Comment by cagnulein** [comment]
@gmoo2546 thanks! i will check this today!

**Comment by cagnulein** [comment]
@gmoo2546 I guess I did it: just one question: don't you changed the speed and inclination from the app directly, isn't it? If you want, you can send me another hci snoof where you're chagning speed and incline from the app so also QZ will be able to do so.
Let me know

**Comment by cagnulein** [comment]
@gmoo2546 Any news?
