### ISSUE TITLE
[REQ] Apple Watch/Health integration - indoor walk for treadmill instead of indoor cycle

### ISSUE THREAD

**Issue by RickNY** [cagnulein/qdomyos-zwift#924]
**Is your feature request related to a problem? Please describe.**
When using the Apple Watch integration with QZ and a treadmill, it adds the activity to the workouts as an Indoor Cycle activity instead of Indoor Walk.  This lacks information such as distance, average pace, and splits.

**Describe the solution you'd like**
It would be very helpful for treadmill activities that the activity is identified correctly, and if possible - to add distance (from the treadmill), average pace and split information.

**Describe alternatives you've considered**
Currently using built-in Apple Watch Inside Walk activity -- but distance calculated by Apple Watch indoors is off a bit from treadmill stance

**Additional context**

**Comment by cagnulein** [comment]
thanks for the reminder :)

**Comment by cagnulein** [comment]
done @RickNY 
it will be in the next beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you would like to try! Thanks

**Comment by cagnulein** [comment]
> OK.. So I did a quick walk to capture what was going on.. This was a 0.27 mile walk.  Once again, the Fitness app showed the Fitness app showed “Indoor Walk”.  It did not include Distance or Avg Pace.  However — QZ is sending that info, because when I go to Settings, Health, Data Access, qdomyoszwift, Data from “qdomyoszwift” — I can see it — but its in a few different spots — “Walking + Running Distance” shows the 0.27 mile, “Active Energy”  shows the 57.5 calories.  “Workouts” shows only Time, Duration, Indoor Walk, Total Active Calories, and Average Heart Rate (this appears to be the same info that shows in the Fitness app for the Workout)

![image](https://user-images.githubusercontent.com/48216/188561239-29105e4c-661e-48e8-b673-eaf2ae67ad5e.png)
![image](https://user-images.githubusercontent.com/48216/188561275-bf47cd59-3adc-45a2-9d5e-eadc94535853.png)

**Comment by cagnulein** [comment]
I guess I fixed @RickNY 
I will send you another one later today about this

**Comment by cagnulein** [comment]
great @RickNY let me know!

**Comment by RickNY** [comment]
OK, I used this for my treadmill walk tonight.. It didn't record distance again in the Fitness app.. Apple Health does show the distance under Walking & Running Distance with QZ as the source.  Also, what got sent to Strava was the full thing.  I have a debug log from the app - not sure if that helps - Ill attach it here.

Also - I opted to disable kcal from my equipment and instead use what was calculated by QZ -- that seems very high to me. On a comparable outdoor walk, the watch logged 407 active calories -- but who knows which is accurate?

Adding elevation gain would be nice as well --- but lets work on the distance issue first

![workout1_0906](https://user-images.githubusercontent.com/702933/188762371-028855d0-f3ca-4f82-9e4a-31df395c8d42.jpg)


![workout2_0906](https://user-images.githubusercontent.com/702933/188762376-1e2e1969-da82-425d-a591-7616926b0ac8.jpg)


[debug-Tue_Sep_6_18_33_54_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9501613/debug-Tue_Sep_6_18_33_54_2022.log.txt)

**Comment by cagnulein** [comment]
could you think about some differences from the last try? I mean for example, you pressed stop on the iphone first?
did you see the distance during the workout on the watch?
let me know

**Comment by RickNY** [comment]
I started the treadmill first, pressed start on the watch app and when the phone app started registering speed, I started my walk. When I was done, I pressed stop on the watch app and then stop on the phone app. And it did record the distance - just not in the workout. 
![2B37D9F3-56C9-4735-9958-B47EC4D861CD](https://user-images.githubusercontent.com/702933/188860178-4c89a398-9fdf-4e8b-badd-890ae65ce21f.jpeg)

**Comment by cagnulein** [comment]
@RickNY got it, but did you remeber to have done something different when you got this https://github.com/cagnulein/qdomyos-zwift/issues/924#issuecomment-1238038305 ?

**Comment by RickNY** [comment]
I honestly cant remember doing anything different.  One thing I will say - and I am not sure if this is normal -- after I press stop on the watch, and then I press stop on the phone app -- the treadmill stops, but the phone app is still showing the last speed instead of dropping to 0.0 -- is that normal?

**Comment by cagnulein** [comment]
probably because the treadmill doesn't seend anymore the speed so QZ will should the last value received. It's another thing to fix for your treadmill.

Ok so for this ticket I have to try it myself.
Anyway, if you have the possibility, let's try this again, we should try to understand when this is happening. Thanks

**Comment by RickNY** [comment]
I did just try two more times this morning, and had the same results.  No distance in the Fitness app, but it is showing in Walking & Distance section.  Looking at my workout history in the fitness app - I have 10 QZ "Indoor Works" where I tried this -- only 2 of the 10 recorded a distance.  And these were all tests where I was on the treadmill and actually walking.

**Comment by cagnulein** [comment]
so it's seems a problem of timing...I have to test this myself so

**Comment by RickNY** [comment]
Does the fact that I'm using Watch OS 9 beta impact anything?

**Comment by cagnulein** [comment]
argh absolutely! I'm working on the 8 version and I don't want to test the 9 before it will be on production (since I have only one apple watch and I don't want to "destroy" the battery)

**Comment by RickNY** [comment]
OK.. My fiancee has a new Series 7 being delivered tomorrow.. I'll see if I can temporarily test on hers with Watch OS 8.. The good news is I anticipate the RC of Watch OS 9 to be released either today or by the end of the week.

**Comment by cagnulein** [comment]
great! let's see what they will present today!

**Comment by cagnulein** [comment]
@RickNY i tried 3 times this morning and all the 3 times it worked perfectly 

so i guess it's something on the beta i guess

![image](https://user-images.githubusercontent.com/48216/189064817-8631a2d8-0fbb-46f7-8390-46936a323c91.png)

**Comment by RickNY** [comment]
OK, well I updated last night to the RC of the beta.. That is likely the same version that will be released on the 12th.. I didn't see any change.. I did notice looking through the Healthkit API, and it looks like totalDistance is deprecated in WatchOS 2.0-9.0, but not sure if that has anything to do with it.    Its very strange how every once in a while, it is properly recording the Walking + Running Distance as part of the workout -- but always recording it in the "Walking + Distance" data item within Health.  I guess we put this on hold until you're on Watch OS 9 - thanks!

**Comment by cagnulein** [comment]
@RickNY Could you point me to the total distance deprecation? Thanks

**Comment by cagnulein** [comment]
Got it https://developer.apple.com/documentation/healthkit/hkworkout/1615756-totaldistance

**Comment by RickNY** [comment]
I would think though that it still should work -- since its replacement (allStatistics?) is classified as "Beta"

**Comment by cagnulein** [comment]
yea it's exactly what i was thinking. i feel it like a bug of 16 unfortunately

**Comment by RickNY** [comment]
Ok, tested 3 times on her new Series 7 with WatchOS 8.7 and her iPhone on iOS 15.6 and all but one walk on hers showed the distance in the workout. The one that didn’t was similar to what mine did where it reported 0 ft. I do want to test some more tomorrow, but she had a lot of important texts coming in once I started so I had to stop.  I had loaded my QZ settings file in to her phone when I tested. I then tested three times on mine running the RC versions of iOS 16 and WatchOS 9, and had three failures to show distance.

**Comment by cagnulein** [comment]
ok at this point let's wait ios 16 and i will test it directly and hopefully i will see also the problem myself :)
thanks!

**Comment by RickNY** [comment]
So - I realized today I could workaround this issue by just turning on syncing to Health from Strava, since I have QZ set to update Strava.  Doing that, all shows up in Apple Health.. So QZ -> Strava -> Health gets a workout entered with the distance metrics.

**Comment by cagnulein** [comment]
@RickNY good workaround, let's see monday:)

in the meantime i will try to find time to check the horizon issue but my baby is giving me a lot of work to do :)

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/191233383-579ec39c-ded3-4ed1-8d41-f352f5a6923a.jpeg)

same here with my first long run with this feature.
unbelievable, i have to dig in

**Comment by RickNY** [comment]
I think one of the bigger problems is that its also random.. Sometimes it does actually do what its supposed to
![C5A176E5-C3DB-4654-A156-D7DC228EEF7D](https://user-images.githubusercontent.com/702933/192104272-972a791e-b15e-42bc-931b-d9a2dab07402.jpeg)

**Comment by cagnulein** [comment]
i have an idea about the reasons of the randomness but i don't know yet how can workaround it

**Comment by cagnulein** [comment]
https://stackoverflow.com/questions/52265670/watchos-5-hkliveworkoutbuilder-hkworkoutroutebuilder-and-workout-distance

**Comment by cagnulein** [comment]
good news @RickNY I should be able to find a fix for this. I will send you a new beta today!

**Comment by RickNY** [comment]
So far so good. I just did a walk and the distance recorded properly from QZ in the Fitness app

**Comment by cagnulein** [comment]
Yeah! I'm very positive on this! I'm closing this one, feel free to open it again in case of issues
Thanks!
