### ISSUE TITLE
[BUG] zwift can't connect to QZ on ios

### ISSUE THREAD

**Issue by nb43201** [cagnulein/qdomyos-zwift#925]
Zwift will not pair. Setup echelon ex4s+, iPhone X, iPad Air 2, dell xps 15 laptop. I have tried every combination of qz and Zwift on each system, but can not get Zwift to pair. Qz pairs immediately on each system with no issue. I have also tried just pairing Zwift, without qz on each system with the same results. 

iPhone X - iOS 15.6
iPad Air 2 - iOS 14.6
dell xps 15 - windows  10
Echelon Tablet - rooted and unlocked

![48C7DFD1-1D71-443C-817B-74F0DA79F4BA](https://user-images.githubusercontent.com/112879260/188477099-f2e09b56-3af5-4a27-85a4-4f761cb09c4e.png)

I emailed the debug file to Roberto, because I couldn’t figure out how to add it here.

**Comment by cagnulein** [comment]
@nb43201 you need to disable the "virtual echelon" setting in the experimental settings and restart qz. that's the issue!

**Comment by nb43201** [comment]
That was it. You’re the best.

**Comment by cagnulein** [comment]
@nb43201 so it's working also with the bike tablet now?

**Comment by nb43201** [comment]
No. That still doesn’t pair with Zwift. Only iPhone and iPad

**Comment by cagnulein** [comment]
is the echelon tablet connected to same wifi of the zwift device? 
is the wahoo direct connect settings enabled in qz?
send me also a debug log from the tablet directly

**Comment by nb43201** [comment]
It is connected to same wifi. Wahoo direct connect is enabled.

**Comment by nb43201** [comment]
I’ll send that debug as well, when I get a chance.

**Comment by cagnulein** [comment]
ok i'm here ;)
