### ISSUE TITLE
[BUG]Cant enter colon for times in iOS app under pace options

### ISSUE THREAD

**Issue by RickNY** [cagnulein/qdomyos-zwift#926]
**Describe the bug**
On the iOS app, when attempting to change the default pace times under Training Program Options, the iOS numeric-only keyboard appears with no ability to enter colons between hh:mm:ss.  Attempting to just enter the enter number without the colons just results in NaN:NaN:NaN.  Workaround is to use iOS's ability to move the cursor with the keyboard to make edits around existing colons.

**To Reproduce**
1. Go to Settings in iOS app
2. Click on Training Program Options
3. Scroll down to '1 mile pace'
4. Clear existing value

**Expected behavior**
Either automatically add colons after every two characters or have iOS pull up a keyboard with a colon available.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16 Beta 8  (Cant confirm if this also occurs in production OS, but suspect same behavior)
 - Version 20A5358a

**Append a debug log**

  
[debug-Tue_Sep_6_08_09_04_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9496714/debug-Tue_Sep_6_08_09_04_2022.log)

![IMG_DAF0E45474A3-1](https://user-images.githubusercontent.com/702933/188631780-843133b9-27aa-4b01-964c-e92ceb422152.jpeg)
![IMG_36C53B66B3C2-1](https://user-images.githubusercontent.com/702933/188631832-fa8bfbde-1b40-4584-9565-3749b6007e4a.jpeg)

**Comment by cagnulein** [comment]
done! thanks!
