### ISSUE TITLE
[REQ] bluetooth::startDiscovery and stopDiscovery

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#927]
While aligning the starting and stopping of discovery of non-bluetooth devices with the that of the bluetooth device discovery in another issue #855, and I saw that the bluetooth discovery is started in different ways on different platforms, but this is not consistent across all "starts".

For example,  bluetooth::bluetooth and bluetooth::finished have:

```
    if (!trx_route_key && !bh_spada_2 && !technogym_myrun_treadmill_experimental) {
#endif
        discoveryAgent->start(QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
#ifndef Q_OS_IOS
    } else {
        discoveryAgent->start(QBluetoothDeviceDiscoveryAgent::ClassicMethod |
                              QBluetoothDeviceDiscoveryAgent::LowEnergyMethod);
    }
#endif
```

but bluetooth::restart has:

```
    if (onlyDiscover) {
        onlyDiscover = false;
        discoveryAgent->start();
        return;
    }
```

and at the end

`discoveryAgent->start();`

_Originally posted by @drmason789 in https://github.com/cagnulein/qdomyos-zwift/issues/889#issuecomment-1214200327_

Apparently these should be the same. https://github.com/cagnulein/qdomyos-zwift/issues/889#issuecomment-1214211876_

**Comment by drmason789** [comment]
I would have done this for #889 but that could be a while away.
- put the full code from bluetooth::bluetooth and bluetooth::finished into a new method bluetooth::startDiscovery() and call it from all the places that currently call discoveryAgent->start().
- add a bluetooth::stopDiscovery() which calls discoveryAgent->stop(). Replace all discoveryAgent->stop() with a call to that. At a later time, other actions (e.g. stopping a non-bluetooth device discovery process) can be added here in a single place.

@cagnulein Do you approve?

**Comment by drmason789** [comment]
I've actually already done this  for #855, but that could take a while.

**Comment by cagnulein** [comment]
yes absolutely, it's actually a bug. Do a dedicated PR for this one and i will merge it asap ;)
