### ISSUE TITLE
[BUG]qz immediately crashes 

### ISSUE THREAD

**Issue by Davedlmt** [cagnulein/qdomyos-zwift#929]
[debug-Wed_Sep_7_11_53_18_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9507804/debug-Wed_Sep_7_11_53_18_2022.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks i will check this tomorrow 

Inviato da iPhone

**Comment by cagnulein** [comment]
the app is connecting to a nautilus bike, set the echelon to the manual device in the advanced setting it should fix the issue. Feel free to reopen the ticket if it still happens
