### ISSUE TITLE
Cannot connect to Zwift[BUG]

### ISSUE THREAD

**Issue by Imtazalli** [cagnulein/qdomyos-zwift#931]
I am unable to connect to Zwift. I named my device "Run" and connected to Wahoo but my avatar does not move when I peddle. 

I am running the qdom app on my Samsung galaxy s10 and the zwift app on an iPad. The bike I'm using is an echelon ex3
![inbound3726677618791225731](https://user-images.githubusercontent.com/113073496/189007948-b514d070-ccaa-4229-bbb7-ea6f52ef4de3.jpg)
![inbound605329455779597237](https://user-images.githubusercontent.com/113073496
![inbound3352593838043727777](https://user-images.githubusercontent.com/113073496/189008237-4ce3d0ad-02ed-4ce7-9f03-59516c354100.jpg)
/189007952-b27dd809-1efe-4034-86c1-423e3ab7e6dd.jpg)
![inbound7620424486780306043](https://user-images.githubusercontent.com/113073496/189007972-b9abb782-0dbd-4453-b63f-6f0bf46a1447.jpg)
![inbound3185927710064700775](https://user-images.githubusercontent.com/113073496/189007992-8c5814ec-ece8-4e9a-b6f3-db72cbbbe8e1.jpg)
![inbound26840706266179323](https://user-images.githubusercontent.com/113073496/189008166-74b2db5f-4926-4525-9b86-4da0d0fced8b.jpg)

**Comment by Imtazalli** [comment]
[inbound1321057699674612202.zip](https://github.com/cagnulein/qdomyos-zwift/files/9522522/inbound1321057699674612202.zip)

**Comment by cagnulein** [comment]
@Imtazalli I checked your log: disable the virtual Bluetooth device setting (only this setting) and restart qz
Let me know if it's better, otherwise send me again the log
Thanks

**Comment by Imtazalli** [comment]
Hello, it is still not working. Attached is the log. Thank you!

**Comment by cagnulein** [comment]
@Imtazalli hi, you need to attach the debug log from the github interface. let me know

**Comment by Imtazalli** [comment]
Hello, sorry about that. It's now attached

[debug-Sat_Sep_10_12_22_36_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9541254/debug-Sat_Sep_10_12_22_36_2022.log)

**Comment by Imtazalli** [comment]
@cagnulein

**Comment by cagnulein** [comment]
@Imtazalli do you have any firewall on the Zwift device or in your home network? Seems that the Dircon protocol has filtered out from your network. Explain me better your scenario

**Comment by Imtazalli** [comment]
@cagnulein I do not have a firewall on the iPad that is running Zwift.

I should be connecting to the "Wahoo" device when connecting to Zwift, right?

**Comment by Imtazalli** [comment]
@cagnulein would it be worth a video call?

**Comment by cagnulein** [comment]
> @cagnulein I do not have a firewall on the iPad that is running Zwift.

what about your network? which access point so you use? do you have a firewall on your network?

> 
> 
> I should be connecting to the "Wahoo" device when connecting to Zwift, right? 

yes or you can use also the bluetooth one, the one that performs better

**Comment by Imtazalli** [comment]
@cagnulein no firewall. I used my computer as well with no luck

**Comment by Imtazalli** [comment]
> > @cagnulein I do not have a firewall on the iPad that is running Zwift.
> 
> what about your network? which access point so you use? do you have a firewall on your network?
> 
> > I should be connecting to the "Wahoo" device when connecting to Zwift, right?
> 
> yes or you can use also the bluetooth one, the one that performs better

@cagnulein 
I tried using a Hotspot as well to connect in case my home network was the issue but I could not connect. I am unable to find anything to connect for the power source. It just says searching for a long time

**Comment by cagnulein** [comment]
@Imtazalli with qz open and connected use this app https://apps.apple.com/it/app/discovery-dns-sd-browser/id1381004916?mt=12 on the zwift device and share a screenshot 

you should find the qz device at the bottom. let me know

**Comment by Imtazalli** [comment]
@cagnulein is this what you're looking for?
![20221002_181028](https://user-images.githubusercontent.com/113073496/193478535-a8c42c37-21ba-4780-bb15-ee2aa630489f.jpg)

**Comment by Imtazalli** [comment]
> @cagnulein is this what you're looking for? ![20221002_181028](https://user-images.githubusercontent.com/113073496/193478535-a8c42c37-21ba-4780-bb15-ee2aa630489f.jpg)

This is the only thing I could find when opening up the discovery app on the ipad

**Comment by cagnulein** [comment]
@Imtazalli the previous page of the one that you sent should shows all the services. you should find a wahoo one

**Comment by Imtazalli** [comment]
@cagnulein I found it and connected but I still cannot ride. The attached said connection failure and then when I left the Qd app, it is just blue like the attached

![20221004_221604](https://user-images.githubusercontent.com/113073496/193965039-bb7281e8-4f4e-40d4-8a4f-71b9424de339.jpg)

**Comment by cagnulein** [comment]
@Imtazalli Did you try to use the iPad only like this video Zwift DIRCON for all the bike with QZ Fitness
https://youtu.be/gYYUXNWFAok ?

**Comment by Imtazalli** [comment]
@cagnulein please issue a refund for this app. I am unable to get this to work and the time involved in this is not what I expected upon purchase. 

Thank you

**Comment by cagnulein** [comment]
@Imtazalli developers can't refund directly, you have to talk with google. Also I gave you assistance as you can see above and you didn't answer from Oct5.
I can help you again of course!
