### ISSUE TITLE
Connecting TUNTURI Fitcycle 50i

### ISSUE THREAD

**Issue by YdRo7** [cagnulein/qdomyos-zwift#932]
**Describe the bug**
The Tunturi Fitcycle 50i, connecting to Zwift. No problem with Tunturi-tours and Kinomap, but unknown by Zwift. I've succeeded to connect it with the QZ-app by adding it at the accessories. So I get the tiles vissible, but the figures stay on 0.0. 
**To Reproduce**
1. Putting on and start cycling the hometrainer
2. Starting the QZ-app
3. Connected with QZ, but no data receiving, no interaction.

**Screenshots**
![Screenshot do sep  8 14_00_01 2022](https://user-images.githubusercontent.com/113110760/189120160-f8e8234c-5d97-4cf2-a5b3-a0f3ac229064.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14.7.1

**Append a debug log**
[debug-do_sep__8_13_58_59_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9526651/debug-do_sep__8_13_58_59_2022.log)

  
**Additional context**
TUNTURI Fitcycle 50i is an Hometrainer with powermeter (ergometer), cadance and heartratesensor.

**Comment by cagnulein** [comment]
I checked the code @YdRo7 and I just added your bike in the beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
@YdRo7 When you will receive the beta remember to disable the power sensor setting and press ok

**Comment by YdRo7** [comment]
Hi Roberto, Here's the new log:
[debug-do_sep__8_16_18_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9527648/debug-do_sep__8_16_18_03_2022.log)
Regards, Yves

**Comment by YdRo7** [comment]
I'll look for smething to try that out. Strange that with the other apps it is communicating in a correct way.

**Comment by cagnulein** [comment]
because other apps collaborated to tunturi to integrate this firmware. qz is community driven and I need a hci snoof from a working scenario to implement this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by YdRo7** [comment]
Hi Roberto,
I've tried to make a bluetooth snoop log while connecting and using the
bike with the tunturi tours app, I hope this can help you.
Best regards, Yves

Op do 8 sep. 2022 om 18:44 schreef Roberto Viola ***@***.***>:

**Comment by cagnulein** [comment]
Hi @YdRo7 I don't see the attachment. You have to add it from the GitHub website 
Thanks

**Comment by YdRo7** [comment]
Hi @cagnulein, I can't attache it because it has an .LAST-extension. Or did I do something wrong making the snoop log? 
Thanks

**Comment by cagnulein** [comment]
@YdRo7 zip the file :)

**Comment by YdRo7** [comment]
Of course, thank you ;-)
[btsnoop_hci.log.zip](https://github.com/cagnulein/qdomyos-zwift/files/9539758/btsnoop_hci.log.zip)

**Comment by YdRo7** [comment]
Hi Roberto, 
Thanks a lot for the new Beta and your attepmts to figure it all out ;-). 
Some things have changed now, but it is still not usable. 
- With starting up, it gives resistance on the bike (I also hear the resitor moving). On the tiles, it marks 0 resistance and whe I push '+' on the tile, resistance falls to nothing. 
- There's no speed, power, heartrate or cadance registered. I've tried several settings, but no difference. 
- First time I used the new Bèta, the epapsed time started counting. Next session-attempts , it stayed on zero.

Hope I help wth this information ;-)
Best regards, Yves

[debug-zo_sep__11_10_57_16_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9542134/debug-zo_sep__11_10_57_16_2022.log)

[debug-zo_sep__11_10_52_48_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9542135/debug-zo_sep__11_10_52_48_2022.log)

![PrintscreenQZ](https://user-images.githubusercontent.com/113110760/189520047-44932748-36b0-47a0-99b0-2617e0f8390a.jpg)

**Comment by cagnulein** [comment]
@YdRo7 it's so strange, the packets are the same. Only a question: in the hci snoof that you sent me, i saw 2 different session, one where there is no metrics, and one where i found the metrics after 30 seconds more or less. Could you explain what you did in the app? Maybe I have to wait something in QZ too.
Let me knw

**Comment by YdRo7** [comment]
I think that the first session was not an active session (just started the TunturiTours app and closed it again. Second session I did some excersising with the TunturiTours app. That's the difference.

**Comment by cagnulein** [comment]
ok, i tried to change some timing, i will send you another one today. Let me know! @YdRo7

**Comment by YdRo7** [comment]
Hi Roberto, it works ;-). QZ is registering speed, cadance and heartbeats and sends it to Zwift. Power and resistance is still a bit weird, when the resistance changes, wattage is still the same. I think I have to figure that out with the settings? There is resistance when I start the app, but when I touch the resistance-tile, resistance goes to zero.

**Comment by cagnulein** [comment]
@YdRo7 in this session did you use resistance 8 and 7? If so i found the resistance issue.
For the wattage, instead, the bike doesn't seem to change the value when the resistance is changing. Does the console of your bike show the current wattage while you're riding? if so, can you take a video of qz and the console side by side with a debug log of qz of the same session so i can compare it?
Thanks!

**Comment by cagnulein** [comment]
maybe it's the app that calculate different wattage using the resistance value...
what about my resistance question? did you use resistance 8 and 7 in that session?

**Comment by cagnulein** [comment]
also @YdRo7 just to give me an idea, with resistance 8 at cadence 70 how much watt do you have in the console when you're riding without QZ? with this value I can check inside the log the corresponding value

**Comment by YdRo7** [comment]
@cagnulein 
I made a little chart with the power/resistance level relationship.  
On level 10, I also registered the relation Power/cadance. 
Hope this helps ;-)
Yves
[Tunturi 50i Res vs Power.xlsx](https://github.com/cagnulein/qdomyos-zwift/files/9577656/Tunturi.50i.Res.vs.Power.xlsx)

**Comment by cagnulein** [comment]
@YdRo7 Thanks! what about my resistance question? did you use resistance 8 and 7 in that session?

**Comment by YdRo7** [comment]
Sorry, but I couldn't see a levels while connected with an app. I only hear the servomotor and feel resistance change in order off inclination on the app.

**Comment by cagnulein** [comment]
got the issue of the power @YdRo7 ! i'm sending a new one later today!

**Comment by YdRo7** [comment]
Sei incredibele! Grazie mille ;-)

Op vr 16 sep. 2022 om 11:29 schreef Roberto Viola ***@***.***

**Comment by cagnulein** [comment]
@YdRo7 version sent, let me know ;)

**Comment by YdRo7** [comment]
@cagnulein, it works well on Zwift, there is clearly a connection between the resistance and the wattage. Thing that I have to figure out are the gears and the cadance. Cadance is not always correct and somtimes it jumps from 80 to 15 for example? Also in a Zwift-workout, I'm asked to change gears to get a higher cadance with the same wattage, so I have to look how I can change the resistance in that case. Didn't have time yet to figure that out. 
But, to be clear, thanks a lot to develop a useable cannection between the Tunturi and the Zwift app. 
Enjoy your Sunday eve ;-)
Best regards Yves

**Comment by cagnulein** [comment]
For the resistance send me a debug log with the issue and I will fix it
For the gears let me know when you will have another ride and I will help you to the setup
Have a good Sunday too!

**Comment by cagnulein** [comment]
@YdRo7 Any news?
