### ISSUE TITLE
[REQ] Quit option

### ISSUE THREAD

**Issue by smulrine** [cagnulein/qdomyos-zwift#939]
It would be useful to have a Quit option to come out of QZ on non-Android platforms. Running it in Ubuntu using linuxfb or eglfs as the QT platform plugin, I have to kill the process from a separate SSH session or just reboot my device.

**Comment by cagnulein** [comment]
@smulrine i don't remember, the close button in the app bar is visible and it doesn't work?

**Comment by smulrine** [comment]
@cagnulein I don't think I have a close button at all. Top left - little running man and menu icon which opens the menu. Top right - padlock to lock the position of the tiles, magnet thing to control auto-resistance. It's running full-screen on the console so there's no kind of window management which would allow me to close it.

**Comment by cagnulein** [comment]
Hah right it's running full scree! Best option is to add a close button in the left side bar. What do you think?

**Comment by smulrine** [comment]
@cagnulein Yes, maybe "Quit" at the bottom of the menu? That would work for me.

**Comment by cagnulein** [comment]
@smulrine done https://github.com/cagnulein/qdomyos-zwift/pull/941
change the branch, pull it and build it and let me know if it's ok (i didn't try this yet)

**Comment by smulrine** [comment]
@cagnulein Yes, that works perfectly!

**Comment by cagnulein** [comment]
great!
