### ISSUE TITLE
Zwift Power Source not Pairing

### ISSUE THREAD

**Issue by unwirednet** [cagnulein/qdomyos-zwift#94]
Hi,

I am trying to bridge my Echelon Bike to use it with Zwift, because of the below issue the avatar is not moving.

Attached print screens from the App Host [Iphone 8] and the Zwift Host [Ipad Pro 1st Gen].
In short, Zwift is not able to pair with the Power Source from the App, it keeps searching endlessly. 
The Cadence is paired and and value is displayed.  Attached also prints screens of the App Configuration.

To test it out, Zwift is able to pair with Speed Sensor over the App, but again the Speed Measurement acquired by the App is not Transferred to Zwift, the values is always zero.

Like your App, and if anything I can help with, let me know or additional information needed let me know.

Regards

![Ipad-Zwift-01](https://user-images.githubusercontent.com/76827995/103431759-7d5e0c00-4ba3-11eb-9593-26ebd5ba605c.png)
![Ipad-Zwift-02](https://user-images.githubusercontent.com/76827995/103431762-8058fc80-4ba3-11eb-96e5-dc529597449d.png)
![Ipad-Zwift-03](https://user-images.githubusercontent.com/76827995/103431763-82bb5680-4ba3-11eb-9388-21bb35f008b9.png)
![Ipad-Zwift-04](https://user-images.githubusercontent.com/76827995/103431764-84851a00-4ba3-11eb-907e-12fa2e3b4018.png)
![Iphone-App-04](https://user-images.githubusercontent.com/76827995/103431757-7c2cdf00-4ba3-11eb-82cc-ab35040f5a8b.PNG)
![Iphone-App-01](https://user-images.githubusercontent.com/76827995/103431765-88b13780-4ba3-11eb-8d99-fa9ed6748a95.PNG)
![Iphone-App-02](https://user-images.githubusercontent.com/76827995/103431766-8949ce00-4ba3-11eb-843c-4f4894b28e40.PNG)
![Iphone-App-03](https://user-images.githubusercontent.com/76827995/103431767-8949ce00-4ba3-11eb-9452-e40e6a56cff7.PNG)

**Comment by cagnulein** [comment]
Hi, you have simply disable the cadence sensor option and reboot my app :)
Give it a try!

Il ven 1 gen 2021, 02:55 unwirednet <notifications@github.com> ha scritto:

**Comment by unwirednet** [comment]
Thank You Roberto, that made it work, appreciate your support and happy new year.

Had my best 1 hour Zwifting this morning,

Regards

**Comment by cagnulein** [comment]
I Love to hear it! Don't forget to rate it on the store!
Thank you, have a nice evening!

Il ven 1 gen 2021, 20:22 unwirednet <notifications@github.com> ha scritto:
