### ISSUE TITLE
Heart rate disconnecting [BUG]

### ISSUE THREAD

**Issue by hnbrace** [cagnulein/qdomyos-zwift#942]
Heart rate disconnecting during ride. Not sure why I have several logs. Probably from me trying different settings to get heart rate to show up

**Comment by cagnulein** [comment]
hi @hnbrace i don't see any log here. please attach them
thanks

**Comment by hnbrace** [comment]
[debug-Tue_Sep_13_16_22_30_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9574789/debug-Tue_Sep_13_16_22_30_2022.log)
[debug-Tue_Sep_13_16_23_01_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9574790/debug-Tue_Sep_13_16_23_01_2022.log)
[debug-Tue_Sep_13_16_23_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9574792/debug-Tue_Sep_13_16_23_25_2022.log)
[debug-Tue_Sep_13_16_42_05_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9574793/debug-Tue_Sep_13_16_42_05_2022.log)
[debug-Tue_Sep_13_16_43_37_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9574794/debug-Tue_Sep_13_16_43_37_2022.log)
[Uploading debug-Tue_Sep_13_16_44_21_2022.log

**Comment by hnbrace** [comment]
I am sorry. First time using GitHub. I think they are now loaded.

**Comment by cagnulein** [comment]
@hnbrace got it, no problem. I see that you have a  Rhythm 24 0663  but you have the ant+ setting enabled. Can you try to turn off the ant+ setting and also to set the  Rhythm 24 0663 to the heart rate bel setting, press ok and restart qz. If the error persists send me a new log about the issue.
Thanks

**Comment by hnbrace** [comment]
Thanks. I thought I turned off the ant+. I will definitely try again this afternoon with these changes.

**Comment by cagnulein** [comment]
@hnbrace any news?
