### ISSUE TITLE
[BUG] rizer won't connect to QZ anymore

### ISSUE THREAD

**Issue by benjaminfrombe** [cagnulein/qdomyos-zwift#943]
bad weather, zwift season is starting up again :)

so I tried my setup tonight (neo 1 + rizer), but unfortunately I can't manage to get the rizer to pair with QZ. Did anything change over the last few months that could cause this ? It used to work in January ...

**Comment by cagnulein** [comment]
hi @benjaminfrombe  nope :) are you on android? do you have location services enabled? nearby devices permissions enable? if you are on android 13 you need the beta from the play store

let me know

**Comment by cagnulein** [comment]
what do you see on qz? @benjaminfrombe send me a screenshot or better a debug log

**Comment by cagnulein** [comment]
hi @benjaminfrombe any news?

**Comment by benjaminfrombe** [comment]
no. Kind of giving up. It's the stupid implementation of the rizer: it
autoconnects to a nearby trainer. So if it doesn't connect to QZ, I doubt
there will be anything in the QZ logs ... Very hard to debug ...

**Comment by cagnulein** [comment]
@benjaminfrombe Maybe I should broadcasting qz as a trainer? Can't you turn off your trainer before starting qz?

**Comment by benjaminfrombe** [comment]
yes that's how I did it before (so last winter), and that worked. I shut
down the trainer and then it would cinnect to QZ. Now for some reason it
won't connect to QZ anymore ...

**Comment by cagnulein** [comment]
But do you see it on nrfconnect? Sorry if I bug you but I'm always trying to understand strange issue, it's a illness:)

**Comment by benjaminfrombe** [comment]
see what ? The rizer, the neo, or QZ ?

**Comment by cagnulein** [comment]
The device that qz can't find it, so I assume the rizer. If on nrfconnect you will see the rizer, so a debug log from qz will explain everything

**Comment by cagnulein** [comment]
Now I'm starting a riding session (2h long)

**Comment by benjaminfrombe** [comment]
so the issue is that the rizer autoconnects to a nearby trainer. I shut
down the NEO and I use a fake device in QZ to start the virtual trainer
(QZ). Then I push the re-pair button on the rizer and it starts blinking =
looking for a compatible trainer. I attached 3 logs:

this is the log from nrf connect towards QZ (without NEO turned on and with
a fake device):

Scanner On.
Device Scanned.
Device Appearance switched from Generic to Heart Monitor.
Connected.
Discovered Device Information, Battery Service, Current Time Service,
D0611E78-BBB4-4591-A5F8-487910AE4366, 9FA480E0-4967-4542-9390-D343DC5D04AE,
Heart Rate, Fitness Machine, and Cycling Speed and Cadence Services.
Discovered Characteristics Manufacturer Name String and Model Number String
for Service Device Information.
Discovered Characteristics Battery Level for Service Battery Service.
Discovered Characteristics Current Time and Local Time Information for
Service Current Time Service.
Discovered Characteristics 8667556C-9A37-4C91-84ED-54EE27D90049 for Service
D0611E78-BBB4-4591-A5F8-487910AE4366.
Discovered Characteristics AF0BADB1-5B99-43CD-917A-A77BC549E3CC for Service
9FA480E0-4967-4542-9390-D343DC5D04AE.
Discovered Characteristics Heart Rate Measurement for Service Heart Rate.
Discovered Characteristics Fitness Machine Feature, Supported Resistance
Level Range, Fitness Machine Control Point, Indoor Bike Data, Fitness
Machine Status, and Training Status for Service Fitness Machine.
Discovered Characteristics CSC Feature, Sensor Location, CSC Measurement,
and SC Control Point for Service Cycling Speed and Cadence.
Characteristic Manufacturer Name String has no Descriptors.
Characteristic Model Number String has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic Battery
Level
Discovered Client Characteristic Configuration for Characteristic Current
Time
Characteristic Local Time Information has no Descriptors.
Discovered Characteristic Extended Properties and Client Characteristic
Configuration for Characteristic 8667556C-9A37-4C91-84ED-54EE27D90049
Discovered Characteristic Extended Properties and Client Characteristic
Configuration for Characteristic AF0BADB1-5B99-43CD-917A-A77BC549E3CC
Discovered Characteristic Extended Properties and Client Characteristic
Configuration for Characteristic Heart Rate Measurement
Characteristic Fitness Machine Feature has no Descriptors.
Characteristic Supported Resistance Level Range has no Descriptors.
Discovered Characteristic Extended Properties and Client Characteristic
Configuration for Characteristic Fitness Machine Control Point
Discovered Client Characteristic Configuration for Characteristic Indoor
Bike Data
Discovered Client Characteristic Configuration for Characteristic Fitness
Machine Status
Characteristic Training Status has no Descriptors.
Characteristic CSC Feature has no Descriptors.
Characteristic Sensor Location has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic CSC
Measurement
Discovered Characteristic Extended Properties and Client Characteristic
Configuration for Characteristic SC Control Point
Disconnected.
Scanner Off.


the log from NRF connect towards the rizer:

Scanner On.
Device Scanned.
Connected.
Discovered Device Information, Secure DFU Service, and
347B0001-7635-408B-8918-8FF3949CE592 Services.
Discovered Characteristics Manufacturer Name String, Serial Number String,
Hardware Revision String, Firmware Revision String, and Software Revision
String for Service Device Information.
Discovered Characteristics Buttonless DFU Without Bonds for Service Secure
DFU Service.
Device Appearance switched from Generic to NordicDFU.
Discovered Characteristics 347B0012-7635-408B-8918-8FF3949CE592,
347B0013-7635-408B-8918-8FF3949CE592, 347B0014-7635-408B-8918-8FF3949CE592,
347B0016-7635-408B-8918-8FF3949CE592, 347B0017-7635-408B-8918-8FF3949CE592,
347B0019-7635-408B-8918-8FF3949CE592, 347B0030-7635-408B-8918-8FF3949CE592,
347B0031-7635-408B-8918-8FF3949CE592, 347B0032-7635-408B-8918-8FF3949CE592,
347B0022-7635-408B-8918-8FF3949CE592, 347B0020-7635-408B-8918-8FF3949CE592,
and 347B0021-7635-408B-8918-8FF3949CE592 for Service
347B0001-7635-408B-8918-8FF3949CE592.
Characteristic Manufacturer Name String has no Descriptors.
Characteristic Serial Number String has no Descriptors.
Characteristic Hardware Revision String has no Descriptors.
Characteristic Firmware Revision String has no Descriptors.
Characteristic Software Revision String has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
Buttonless DFU Without Bonds
Characteristic 347B0012-7635-408B-8918-8FF3949CE592 has no Descriptors.
Characteristic 347B0013-7635-408B-8918-8FF3949CE592 has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
347B0014-7635-408B-8918-8FF3949CE592
Characteristic 347B0016-7635-408B-8918-8FF3949CE592 has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
347B0017-7635-408B-8918-8FF3949CE592
Characteristic 347B0019-7635-408B-8918-8FF3949CE592 has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
347B0030-7635-408B-8918-8FF3949CE592
Characteristic 347B0031-7635-408B-8918-8FF3949CE592 has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
347B0032-7635-408B-8918-8FF3949CE592
Discovered Client Characteristic Configuration for Characteristic
347B0022-7635-408B-8918-8FF3949CE592
Characteristic 347B0020-7635-408B-8918-8FF3949CE592 has no Descriptors.
Discovered Client Characteristic Configuration for Characteristic
347B0021-7635-408B-8918-8FF3949CE592

QZ log is attached

**Comment by cagnulein** [comment]
@benjaminfrombe you need to attach the log from the github interface directly. thanks

**Comment by benjaminfrombe** [comment]
[debug-Sat_Oct_1_15_34_00_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9690598/debug-Sat_Oct_1_15_34_00_2022.log)

**Comment by cagnulein** [comment]
@benjaminfrombe the main issue is you have the elite rizer setting in qz disabled. That's why qz is not connecting to it. Infact in the log i see the rizer device but QZ doesn't try to connect to it. Let me know

**Comment by benjaminfrombe** [comment]
I know, but that’s not the issue. QZ connecting to the Rizer is only for
showing data and changing some basic resistance settings. The Rizer itself
has to pair with QZ (the other way around) and that’s the issue. I’ll
upload a log with the Rizer enabled in QZ but won’t make a difference

Something has changed in the virtual device why the Rizer won’t pair with
QZ anymore

**Comment by benjaminfrombe** [comment]
[debug-Sat_Oct_1_18_59_06_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9690801/debug-Sat_Oct_1_18_59_06_2022.log)

**Comment by benjaminfrombe** [comment]
so for some more explanation: the rizer has 2 leds: a blue and a green one. The blue led in on when something is paired to it (like QZ which works). The green light is is pulsing, trying to pair with a trainer, in order to chage it's gradient, and should stay on when paired, which doesn't happen. If I turn on my NEO it immediately pairs to the NEO and stays on. Perhaps one day we should do a video call live to show you what's happening :)

**Comment by cagnulein** [comment]
hah now i remember @benjaminfrombe ! yes the virtual device is not on in your log because i'm turining it on ONLY when I see the NEO. 
So i think it's a dog chasing its own tail. 
The startup procedure should be:
1) turn on qz
2) turn on the neo
3) turn on the rizer

if it doesn't work i have to put some logic to force the connection first to the neo, bringing up the virtual bike and then connect to the rizer.
Does it make sense?

**Comment by benjaminfrombe** [comment]
[Uploading debug-Sun_Oct_2_10_45_32_2022 2.log…]()

**Comment by benjaminfrombe** [comment]
tried that, but the rizer keeps connecting directly to the Neo, not QZ ...

**Comment by benjaminfrombe** [comment]
[debug-Sun_Oct_2_10_45_32_2022 2.log](https://github.com/cagnulein/qdomyos-zwift/files/9692319/debug-Sun_Oct_2_10_45_32_2022.2.log)

**Comment by cagnulein** [comment]
maybe the rizer has a cache of the device used last time, so it's still trying to connect to it. is there no option to force a different connection in the rizer? maybe we should try to contact elite?

**Comment by cagnulein** [comment]
my last attempt could be a modification in the code, but if the tacx still broadcast itself even when it's paired to qz, the rizer will always try to connect to the tacx instead of qz. What do you think?

**Comment by benjaminfrombe** [comment]
well if the virtual device could be started without the neo being turned
on, it should pair with QZ. and then afterwards turn on the NEO and let QZ
pair to it ...
I thought that was what the "fake device" was for in settings ? But that
doesn't seem to work.

**Comment by cagnulein** [comment]
> the virtual device could be started without the neo being turned on

maybe you would say "without the rizer being turned on"

qz now with the rizer and neo paired in the settings it's trying to do

1) find both devices
2) when they are both visible qz will connect at the same time to the tacx and the rizer
3) turn on the virtual device 

what i would like to change is

1) find the tacx
2) connect to the tacx
3) turn on  the virtual device
4) you should turn on the rizer now
5) qz is looking for the rizer
6) qz is connecting to the rizer

does it make sense?

about the fake device: yes the fake device will bring up immediately when you see the tiles the virtual device. do you see the tiles with the fake device on?

**Comment by benjaminfrombe** [comment]
no I did mean without the neo being on:

1. start a virtual device in QZ
2. turn on the rizer (so the neo can only find QZ as a device to pair to,
because here lies the problem)
3. turn on the neo
4. qz connects to the neo + rizer

**Comment by cagnulein** [comment]
@benjaminfrombe it's still not completely clear to me but anyway we can test this scenario before doing any modification with the fake device setting.

So test it in this way:
1) turn off the rizer and the neo
2) open qz and enable the fake device
3) exit from qz
4) turn on the rizer (it shouldn't connect to anything since there is no FTMS devices around)
5) turn on qz. it should instantly connect to the rizer and turning on the ftms device for the rizer too

let me know

**Comment by benjaminfrombe** [comment]
this is what I tried :) But without succes. For some reason, when use the
face device, the Rizer won't pair with QZ. (while it did last winter). I
understand it's very hard to debug why ...

**Comment by cagnulein** [comment]
just to double check: when qz is open, you can try to check with nrfconnect from another device that QZ is broadcasting itself like a FTMS device. Other than this i don't know how can I fix this, i mean it's all in the hand of elite. Maybe we can contact them

**Comment by cagnulein** [comment]
> why I was wondering whether anything had changed in your code between last winter and now regarding the virtual device you expose .

yes now I understood :D 
have there been updates on the rizer firmware since last winter?

**Comment by benjaminfrombe** [comment]
no, none ...

**Comment by cagnulein** [comment]
ok so I hope that you will see something strnage on nrfconnect

**Comment by cagnulein** [comment]
@benjaminfrombe any news?
