### ISSUE TITLE
[BUG] Apple IOS 16 devices running peloton have problems conencting to qdomyos on Android FireHD device

### ISSUE THREAD

**Issue by nadims** [cagnulein/qdomyos-zwift#946]
**Describe the bug**
Since my devices updated to IOS 16 I can no longer get my FireHD running qdomyos to connect to my Ipad Air running the Peloton app. On the FireHD on qdomyos I see it has cadence from my Echelon EX-3 bike and HeartRate from my Polar H7. On the Ipad running the Peloton App I can see the firehd device on both Heartrate and Cadence but it has trouble connecting. When it does connect the heart rate is 0 and cadence is 0 then after 30seconds it disconnects. It never gets a stable connection, and even when it thinks it is connected cadence and heartrate is 0

**To Reproduce**
Followed all instructions on the website. 
-Have the peloton user working
-Cycling Cadence Sensor (peloton compatibility) on
-Enable Virtual Device  on
-Virtual device bluetooth on

FireHD app has location enabled for qdomyos app

This setup was working perfectly on IOS15. It also works with 2 IOS 16 devices using the same settings

**Expected behavior**
Bluetooth connection should stay connected and send information not 0

**Smartphone (please complete the following information):**
Running qdomyos 
- Device: FireHD 8  (10th generation)
 - OS: FIre OS 7.3.2.4
 - Version Qdomyos 2.11.41

Running peloton
-Device: ipad air 3gen
-OS: ios16
-verions: Peloton 15.39.0

**Comment by nadims** [comment]
![IMG_2302_HEIC](https://user-images.githubusercontent.com/934123/190879149-8cd33280-d839-48c0-8f9a-e47a55fc2aad.png)
![IMG_2304_HEIC](https://user-images.githubusercontent.com/934123/190879168-158c7493-c6bf-44b0-b615-029608d2e5f9.png)

**Comment by nadims** [comment]
I also tried connecting to the Peloton app on a FireTV, same result it connects and disconnects randomly, and if it ever connects heartrate is shown as 0

**Comment by cagnulein** [comment]
@nadims did you already try to reset the network settings of your ipad and reboot it?

**Comment by nadims** [comment]
I did a reset of network settings from general / reset / reset network settings. That did not work. I had the same result. It seems to connect to bluetooth, heartbeat and cadence at -- and 0. Then it disconnects.

**Comment by cagnulein** [comment]
@nadims install nrfconnect on the fire hd. With QZ open on the ios device, check on your fire hd what you see from the QZ device and send some screenshot while you're connected.

also did you try to use another ios device instead of the ipad, just to understand if the problem is the ipad itself or something else. 

Let me know

**Comment by nadims** [comment]
Sorry for the delay, here are the test that you suggested.

I've installed the nrfconnect on the fire HD. I opened QZ on the Ipad. Here are the screen shots of that setup.
![IMG_2322](https://user-images.githubusercontent.com/934123/193026722-a83466ec-de36-4ec5-a826-fe3d3dcdd314.jpg)

![IMG_2325](https://user-images.githubusercontent.com/934123/193026769-589b4545-3cc9-4954-8851-d20d94efbdd4.jpg)

![IMG_2326](https://user-images.githubusercontent.com/934123/193026788-9dfb8a9b-9dcb-4f6c-95e4-b3060e5bb84c.jpg)

![IMG_2323](https://user-images.githubusercontent.com/934123/193026883-a2b4b77c-0c4b-4f0b-8752-42572db17b24.jpg)

![IMG_2328](https://user-images.githubusercontent.com/934123/193026950-942bcc86-2e76-4a4f-8c00-f41948304ed9.jpg)

![IMG_2329](https://user-images.githubusercontent.com/934123/193027017-827217e6-e316-4430-8ae1-38994862a750.jpg)

![IMG_2330](https://user-images.githubusercontent.com/934123/193027044-f4f607c8-c6e9-47a9-b0d4-b10614a7ed73.jpg)

As far as I can tell the fire HD tablet can connect to the ipad and see it.

I did other experiments: 
1) Iphone 13 running QD and the Ipad running Peloton works. 
2) Ipad running QD and iphone 13 running Peloton works.
3) FireHD tablet running QD to FireTV stick running Peloton does not work
and the original scenario that was working before
4) FireHD tablet running QD to Ipad running Peloton does not work

So I am assuming the FireHD is the device that is having troubles sending the information to the Ipad Peloton app.

**Comment by cagnulein** [comment]
@nadims i'm guessing that you have the ios peloton workarkound disabled in the experimental settings? if so turn it on again and retry. I guess it could be the issue

**Comment by nadims** [comment]
So I tried turning on the IOS peloton workaround as you suggested last friday. It worked once, and I thought it was all good. Then on my next workout on monday and tues it no longer worked. I tried resetting the IOS setting on and off again. It wouldn't connect again and I am back to the it connects and disconnects, sending -- or zero for the heartrate and cadence. 

So good thing, we know it can work. Bad thing, I can not make it work reliably

**Comment by cagnulein** [comment]
ok so for sure the iOS peloton workaround must be on.
The thing that I can say is to always try to reboot your devices when you see these kind of issues. More than this I don't know what it can cause the issue. Did you try again the nrfconnect thing with the ios peloton workaround on?

**Comment by nadims** [comment]
For sure it has to be in the Fire Tablet... if I turn on the qd on my iphone it connects at the first try. I will try your suggestions on the fire tablet

**Comment by cagnulein** [comment]
any news @nadims ?

**Comment by nadims** [comment]
Sorry for the delay again. Here is qd running on the fire tablet running nfrconnect trying to connect to the ipad running peloton app. 

Since that time that it worked once, I haven't been able to get it to connect and send data again. I've tried resetting the fire tablet networking and bluetooth. I still get -- and 0 on the peloton app when it connects, and it disconnects 5 seconds later. I don't know what else to try. During this time I have had to use my iphone for QD and that always works. 


![IMG_2350](https://user-images.githubusercontent.com/934123/197200486-85628336-e2db-44ec-88a0-c38761e6cb3b.jpg)
![IMG_2351](https://user-images.githubusercontent.com/934123/197200512-6544bb49-d10e-440d-bcfc-7c381e1ba561.jpg)
![IMG_2352](https://user-images.githubusercontent.com/934123/197200518-b6418374-9fbb-4171-afcd-355c2cf78743.jpg)
![IMG_2353](https://user-images.githubusercontent.com/934123/197200522-de8f467e-6cf8-4e17-bccf-6b073961b8e3.jpg)
![IMG_2354](https://user-images.githubusercontent.com/934123/197200525-eb244e67-9c1e-4c02-ba04-f06b3620368f.jpg)
![IMG_2357](https://user-images.githubusercontent.com/934123/197200526-e72ed7f
![IMG_2355](https://user-images.githubusercontent.com/934123/197200533-e7ead491-c2cc-4441-b8a0-30c4431efa23.jpg)
6-6265-476a-a1da-22b3a2c14d94.jpg)

**Comment by cagnulein** [comment]
hi @nadims thanks but these nrfconnect screenshot are not about a connection to an iphone. I see a N/A in the name in the top bar. Don't you see the QZ in the nrfconnect?

Just to clarify the test that you need to do:
1) open qz on a device and connect it to your bike
2) open nrfconnect to the other device
3) select, on nrfconnect, the QZ device, and connect to it
4) send some screenshots

Let me know

**Comment by nadims** [comment]
That N/A was what popped up on the NFRconnect when the QD (fire) -> Peloton (IPAD) connected.
NFRconnected that was running on the background on the fire tablet. It popped out on the foreground when the attempt to connect happens and it showed that N/A mac address and the info above.

**Comment by nadims** [comment]
To under stand your steps.

1) open qz on a device and connect it to your bike
Fire tablet with QD connected to the bike

2) open nrfconnect to the other device
Do this on a seperate device not the Fire device. I think I will need a PC version as I do not have another andorid tablet or phone. Does NFC connect exist for Iphone/ipad or PC?

3) select, on nrfconnect, the QZ device, and connect to it send some screenshots
On the thrid device not the ipad

**Comment by cagnulein** [comment]
> To under stand your steps.
> 
> 
> 
> 1) open qz on a device and connect it to your bike
> 
> Fire tablet with QD connected to the bike

ok

> 2) open nrfconnect to the other device
> 
> Do this on a seperate device not the Fire device. 

yes it must be a separate one. the ipad or the iphone is good

> I think I will need a PC version as I do not have another andorid tablet or phone. Does NFC connect exist for Iphone/ipad or PC?

yes it's available for ios!

> 3) select, on nrfconnect, the QZ device, and connect to it send some screenshots
> 
> On the thrid device not the ipad

check above

**Comment by nadims** [comment]
Here are the pics of what you requested. Let me know if you need to click other options.
![IMG_2362](https://user-images.githubusercontent.com/934123/198286639-a38b4c38-82f7-4b43-833c-cfe6be12ea7e.jpg)
![IMG_2363](https://user-images.githubusercontent.com/934123/198286655-959defcd-261e-4237-8d21-8a187d5f14bd.jpg)
![IMG_2364](https://user-images.githubusercontent.com/934123/198286675-9b5cc688-f562-4e51-bc2d-d154e2d6a08e.jpg)
![IMG_2365](https://user-images.githubusercontent.com/934123/198286686-144d7d8f-9a96-4d54-b56e-9f6ab81e2294.jpg)
![IMG_2366](https://user-images.githubusercontent.com/934123/198286695-394f2423-4967-4a20-b980-b54cc7209d71.jpg)
![IMG_2367](https://user-images.githubusercontent.com/934123/198286707-87bc7ab3-11ee-48e1-ab7c-869e7913debd.jpg)

**Comment by cagnulein** [comment]
all the info here are right @nadims
It seems so some sort of issue on the peloton app :(
maybe you can try to change the name of the fire to something else like "bike", maybe the peloton device is keeping some sort of cache?

**Comment by nadims** [comment]
Well I made it work again, at least the cadence sensor. What is better is that I can systematically make it work or break.
This is the setting that makes the cadence work again. 

Under Heart Rate Options, I toggle Heart Rate service outside FTMS to ON. Then restart the app, and the cadence sensor now syncs with the Peloton app.

This has the (unintended effect) that the peloton app no longer sees a heart rate sensor for the QD device, but at least the cadence works.

The Experimental IOS Workaround makes no difference if it is on or off for cadence to work.

If I turn the Heart Rate service outside FTMS off again, then I see a heart rate sensor again for the QD device, but I am back to it not being able to stay sync, getting 0 for the heart rate, and getting 0 for the cadence. 

My theory is that something with the Heart Rate monitor section of the app is making the connection not stable or not work. The Heart Rate service outside FTMS probably disables the whole thing (guess) and that allows the cadence sensor to work. 

I flipped it on and off several times, and the result was predictable as mentioned aboved

**Comment by nadims** [comment]
My Heart rate band is a Polar H7, not sure if that helps

**Comment by nadims** [comment]
The only bad thing of this workaround is that the heart rate information can not be sent via the QD app

**Comment by cagnulein** [comment]
Using the heart rate outside ftms setting shouldn't make any difference since the peloton cadence sensor is on and also the iOS peloton workaround.
Did you try to reset everything, qz and peloton and restart both devices starting from scratch? 
The result from nrfconnect was ok, so I'm assuming that the issue is on the peloton device itself

**Comment by nadims** [comment]
I know the result I am posting makes no sense. But I have tried resetting the fire tablet name, and resetting everything. I've also reinstalled both the peloton app and the qd app on the fire. Reset wireless and bluetooth on both devices.  Nothing else I have done has helped. I am not thinking that the FTMS fixes the problem cadence, I think it disables the heart rate sensor, then the cadence sensor is able to work. 

I can try more things if you want. 

With the FTMS setting on, qd heart rate sensor doesn't show on peloton app, and the qd cadence sensor works, stays synced, and reports the real number and not a 0. If i turn the FTMS setting off, qd heart rate sensor show in the peloton app, but never stays stable synced, never sends a number that isn't 0, qd cadence sensor also shows but doesn't stay synced and never sends a number that is not 0. I have tried this several times so I know it is not a fluke, or a coincidence. I can record a video if you want to see this.

**Comment by cagnulein** [comment]
@nadims do you try to run peloton on a different device? we need to bisect the issue

**Comment by nadims** [comment]
I can run the peloton app in another ipad or iphone. I can also run it on firetv, appletv, roku... but I think those might not sync heartrate only the cadence because of the peloton app. 

Let me know which one you want me to try

**Comment by cagnulein** [comment]
hah wait, now I got the issue: which android version is running over the fire tablet? if it is greater than 9 that's the issue! There is a limitation on android 10 and above that can't send cadence and heart rate as a separate metrics at the same time (it's actually a peloton limitation, because, for example, on zwift, you can reiceve them both with the same android source)

**Comment by nadims** [comment]
It is Running FireOS 7.3.2.4 which according to this wiki page https://en.wikipedia.org/wiki/Fire_OS#Fire_OS_7 is based on Android 9

**Comment by cagnulein** [comment]
did you have some news @nadims actually i'm out of ideas

**Comment by nadims** [comment]
I agree. Thanks for all the help. At the moment I am just using for the cadence and that is fine. 

Thank you AGAIN Roberto.... I really appreciate and like your app
