### ISSUE TITLE
[SUGGESTION] QSettings keys as QStringLiteral constants rather than repeated hardcoded string literals

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#948]
**Is your feature request related to a problem? Please describe.**
The QSettings object  is accessed via hard-coded string literals. The programmer needs to know what these are and what they mean.  It would be convenient if they were available as constants somewhere with comments describing what they are available in QtCreator's intellisense.

**Describe the solution you'd like**
A new class, e.g. QZSettings, which contains QStringLiteral members defining the general QZ settings keys.
Default values also defined as constants.
Device-specific settings keys also in the new class OR in the device's bluetoothdevice subclass
Code documentation on each i.e. /** @brief etc.
Replace calls into QSettings that use hardcoded string literals with references to these constants.

Even better: static strongly-typed accessors where the getter applies the default.

**Describe alternatives you've considered**
Replace that whole QSettings class with one that provides an integer index for your settings key, and replaces the text lookup with an O(1) array lookup so we can trim some milliseconds. Also notifies subscribers when a change occurs so clients can cache the values instead of looking them up repeatedly.

**Who's going to do it?**
I'll do it. The first one...not the alternative.

**Comment by drmason789** [comment]
@cagnulein By "I'll do it" I mean I'll do the change if you agree to it.

**Comment by cagnulein** [comment]
Yes thanks, it's something that I have to do but how could this works into the qml? Also I was scary about doing some error and causing problem to the users

**Comment by drmason789** [comment]
I'd leave the QML alone. The access to the settings in the C++ would still go through the QSettings object so I believe there would be not change of function in the QML.

**Comment by cagnulein** [comment]
Yeah I was saying so because if we put the constants for all the settings, it will be nice to have a constant for whole code, otherwise we will have the string for each settings in the c++ new module and in the QML.
But ok, let's do the c++ first, in case I will do the QML then

**Comment by drmason789** [comment]
I've used a namespace instead of a class to contain the constants. I was thinking in C# when I suggested the class. Could still do that though. An instance attached to a QSettings instance providing strongly typed accessor functions that transparently handle the default values would shrink the calling code.
