### ISSUE TITLE
[BUG] no charts at the end

### ISSUE THREAD

**Issue by stategirl85** [cagnulein/qdomyos-zwift#949]
**Describe the bug**
Ride works well during ride, as soon as I hit stop the screen goes blank. It does not show a graph. I also no longer receive the emails with graphs. This seems to happen every other time. My phone also gets hot/warm feeling when this happens. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 15.6.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 13 Pro
[Uploading debug-Wed_Sep_21_06_02_25_2022.log…]()

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
Hi @stategirl85 , the file is not uploaded correctly. You have to stay there until the end of the upload
Anyway be sure to close qz before starting a new session in order to be sure to have a clean qz startup when you ride.

The hotness of your phone depends on the brightness, qz is not cpu hungry :)

**Comment by stategirl85** [comment]
[debug-Wed_Sep_21_06_02_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9626587/debug-Wed_Sep_21_06_02_25_2022.log)

@cagnulein So sorry about that. I think it’s fully uploaded now..?

**Comment by cagnulein** [comment]
got it now @stategirl85 
the problem is the same of #857 
sometimes seems that the engine that generates the charts hangs unexpectedly.
It should be fine the next time. Let me know if it happens again

**Comment by stategirl85** [comment]
@cagnulein Thank you so much!
