### ISSUE TITLE
Incorrect Watt value on Echelon Bike

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#95]
bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567289 Current Watt: 609"
[debug-Fri-Jan-1-09_10_42-2021.log](https://github.com/cagnulein/qdomyos-zwift/files/5759143/debug-Fri-Jan-1-09_10_42-2021.log)

Current resistance: 29
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567281 Current Heart from Apple Watch: 134"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567282 Current Local elapsed: "
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567283 Current Speed: 44.6222"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567284 Current Calculate Distance: 13.2171"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567286 Current Cadence: 119"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567287 Current Distance: 21.25"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567288 Current CrankRevs: 1729"
Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(QString) "Fri Jan 1 09:39:27 2021 1609515567289 Last CrankEventTime: 36137"

**Comment by cagnulein** [comment]
@marklogan17 just for your info :)

**Comment by cagnulein** [comment]
@dsmitty166

**Comment by ptrinephi** [comment]
Looks like this issues has been fixed on 2.4.4

**Comment by cagnulein** [comment]
Yes!
