### ISSUE TITLE
[BUG] no metrics for Echelon Row

### ISSUE THREAD

**Issue by EdwinIguina** [cagnulein/qdomyos-zwift#952]
**Describe the bug**
Not getting stroke rate on the Echelon Row 

**To Reproduce**
1. Go to turn on rower
2. Open QZ app
3. ensure Bluetooth connection is secured
4. Tap start workout
5. Start working out
6. No metrics shown

**Expected behavior**

1. Go to turn on rower
2. Open QZ app
3. ensure Bluetooth connection is secured
4. Tap start workout
5. Start working out
6. See metrics begin to be recorded 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 
 - Version 16.1

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 
 - Version 16.1

**Append a debug log**

[debug-Thu_Sep_22_09_03_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9626253/debug-Thu_Sep_22_09_03_15_2022.log)

**Comment by EdwinIguina** [comment]
[debug-Thu_Sep_22_09_03_15_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9626244/debug-Thu_Sep_22_09_03_15_2022.log)

**Comment by cagnulein** [comment]
hi @EdwinIguina good news! I already fixed this in https://github.com/cagnulein/qdomyos-zwift/issues/886
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the beta. Thanks

**Comment by EdwinIguina** [comment]
> hi @EdwinIguina good news! I already fixed this in #886 send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the beta. Thanks

Email sent. Thank you so much!
