### ISSUE TITLE
[REQ] Improve ANT+ support

### ISSUE THREAD

**Issue by jwatral** [cagnulein/qdomyos-zwift#953]
Current implementation uses outdated library and has hard to resolve bugs (like #167).
As discussed with @cagnulein on Facebook Group, we could improve the ANT+ feature using other library from Garmin.
More details to be provided by @cagnulein.

**Comment by cagnulein** [comment]
@jwatral This is our starting page https://www.thisisant.com/developer/ant/ant-in-android

My idea is porting this library inside qz.
So for starting you can create a simple Java app that, for example, send fake power and speed to your watch.

Also will be good to read hr by ant+

If it works we can add it to qz quite easily

**Comment by jwatral** [comment]
@cagnulein I did some digging and here are the results:
- the ANT+ SDK - is only for reading sensor data via multiple ANT+ profiles
- the ANT SDK does supports custom communications, allows sending data via ANT (but without ANT+ profiles)
- there are some paid membership options as well, like this:
> Note that ANT+ Members can also [download the member early release Android ANT+ SDK version P.B2. MO1](https://www.thisisant.com/developer/ant/%7Bpage_562%7D), which also contains support for FE-C.

FE-C would be extremely useful for us, but I'm not sure if this will cover the server side or only the client one.

Your current implementation is based on ANT SDK (android_antlib_4-14-0.jar), which to my current understanding, is the only one we can really use, without buying membership. What's even more interesting - in the official download page, there seems to be an older version (4-12-0) so really no point in changing the lib.

I've contacted their support and requested an account - let see if they will able to help.

But maybe I missed smth?
Btw, are you already ANT member?

**Comment by cagnulein** [comment]
Thanks @jwatral a lot of information that I didn't know!

> But maybe I missed smth?

Mmm not really, I guess I were just misinformed 

> Btw, are you already ANT member?

Nope unfortunately 

So our best hope is to fix the current implementation?
Maybe it's an easy task: if you want you can easily take my Java file to use in a single project to play with it.

What do you think?

**Comment by jwatral** [comment]
>So our best hope is to fix the current implementation?

I think so, yes. But because the power and cadence are working fine, I have high hopes on this ;-)

> Maybe it's an easy task: if you want you can easily take my Java file to use in a single project to play with it.

Sure, will do that. Is there an easy way to build the android apk locally? I could then install it on the galaxy S7 and test it right away.

**Comment by cagnulein** [comment]
> I think so, yes. But because the power and cadence are working fine, I have high hopes on this ;-)

Yes me too!

> Sure, will do that. Is there an easy way to build the android apk locally? I could then install it on the galaxy S7 and test it right away.

You mean the full qz? I don't know if this will be the easiest and quickest thing to do.
In my opinion you can just take the Java files and the library and create an android project from scratch on android studio

Anyway if you want to build qz instead, you have to download qt 5.15.2 and build it from qt creator

Let me know if you need help

**Comment by cagnulein** [comment]
@jwatral a lot of people point me to https://github.com/starryalley/CSC_BLE_Bridge

**Comment by jwatral** [comment]
@cagnulein afaik, they're using plugin lib, which can only read ant signal from multiple ant+ enabled sensors. I've searched for a bridge from FTMS to FE-C but it doesn't seem to exist.

**Comment by cagnulein** [comment]
@jwatral it seems that this project could solve the hr reading from some garmin ant watches

**Comment by cagnulein** [comment]
@nzbrian maybe could you be interested on this too?

**Comment by cagnulein** [comment]
closing this, since we already did what it's possible. Thanks @jwatral

**Comment by mgarcea** [comment]
Any chance that ANT+ could be further implemented for QZ to allow full bike control (full Smart Trainer functionality through ANT+).  There are a few virtual riding platforms that only use ANT+ (for whatever reason).  
https://bikethe.world/
https://www.bigringvr.com/

**Comment by cagnulein** [comment]
> Any chance that ANT+ could be further implemented for QZ to allow full bike control (full Smart Trainer functionality through ANT+).  There are a few virtual riding platforms that only use ANT+ (for whatever reason).  
> 
> https://bikethe.world/
> 
> https://www.bigringvr.com/

@jwatral Do you think it could also possible? With a new Java module?

**Comment by cagnulein** [comment]
@jwatral I was thinking about the problem that you mentioned yesterday in the email and it can't be a collision because the power is ok over ant+, so it must be something else.

I'm opening this again. Since @mgarcea is also interested it's better to talk here

**Comment by cagnulein** [comment]
> The power and cadence reading might be more resilient to such drops, because it's not timestamp based and just send current cadence value, cumulativePower, current power and eventCount. Speed sends a timestamp and number of wheel revolutions, which together with wheel circumference gives you a speed.

what if you fix the value in the java code? we should see a fixed value?

> Nonetheless, I think we should separate speed related issues from this ticket and here focus on the improvement suggested.

yes go ahead, open a new ticket for this

> Overall ANT+ seems to be dying slowly, giving way to BLE and DIRCON (especially on mobile devices). The android libs weren't updated since 2015, Samsung abandoned ANT+ support in S22 and Android 11+ has some unresolved issues with ANT HAL. Not sure if it's reasonable to spend that much time on smth no longer supported.

yeah it's my same feeling

> Do you mean the `antpluginlib`? It's just for **receiver**'s end.

nope of course i mean something else, something to find out :) but I guess this will remain a dream in the @mgarcea mind :D

**Comment by mgarcea** [comment]
Yup I get it. Definitely doesn’t seem like it’s worth it. I would think that if those developers want their products to be able to be used in the iOS ecosystem at some point, they will eventually have to implement Bluetooth connectivity for their products.

**Comment by cagnulein** [comment]
@mgarcea i checked the project that you sent and they are already usable with qz! I mean you can download their video from YouTube and use the video feature builtin in qz! Isn't it @Bepo7012 :)

**Comment by cagnulein** [comment]
#838 @mgarcea

**Comment by mgarcea** [comment]
Ok this is a feature that I have heard about, but not tested myself.  I will check it out! I am assuming you mean without a GPX file though?

**Comment by cagnulein** [comment]
@mgarcea no, with the gpx! I saw in their YouTube channel that he also added the segments so I guess there is also their gpx track

**Comment by Bepo7012** [comment]
> @mgarcea i checked the project that you sent and they are already usable with qz! I mean you can download their video from YouTube and use the video feature builtin in qz! Isn't it @Bepo7012 :)

If gpx and Video is available i see no reason why it should not work. But i have seen no possibility to get the gpx?

**Comment by mgarcea** [comment]
Yes, I see a link to a segment on Strava, but I don’t think GPX is available for that specific video.

**Comment by cagnulein** [comment]
> Yes, I see a link to a segment on Strava, but I don’t think GPX is available for that specific video. 

We just need to find the attempt in the segment history :)

**Comment by Bepo7012** [comment]
> > Yes, I see a link to a segment on Strava, but I don’t think GPX is available for that specific video.
> 
> We just need to find the attempt in the segment history :)

If there is a public one you get the gpx, BUT: gpx and video must match and the attempt is definitely different in speed and therefore in length. So the synchronization between gpx and video Position would be impossible 👎

**Comment by cagnulein** [comment]
any news @jwatral ?

**Comment by cagnulein** [comment]
@jwatral we have good news for bluetooth sensor to garmin https://github.com/cagnulein/qdomyos-zwift/issues/1044
