### ISSUE TITLE
[BUG] NordicTrack S22i support using issue 877 as example

### ISSUE THREAD

**Issue by Ktrum161** [cagnulein/qdomyos-zwift#954]
I used Issue 877 troubleshooting as my example and followed the same setup as used for the ProForm Tour de France 10 bike.  Using treadmill for options with Proform/Nordictrack Options set as Nordictrack2950 IP to S22i bike address and using the last tested QZCompanion apk tested to function with the TDF 10 Bike.  The QZCompanion is sending data via UDP, as witnessed in Wireshark. 

Expected behavior:
Expected bike metrics to be recognized using the QZ Companion App on the S22i bike.  Metrics  for speed and inclination appear to work as described in the README for the QZ Companion application. 

Problem:
Cadence is not populating.  This may be a feature versus a bug, but would like cadence to populate to be recognized as a bike.  

Attachments:

![IMG_0001](https://user-images.githubusercontent.com/15612994/192591476-298e333b-7cb4-4bea-b85e-dea861eeaf11.PNG)

**Smartphone (please complete the following information):**
 - Device: iphone 7
 - Version 14.7.1

**Append a debug log**

[debug-Tue_Sep_27_11_42_33_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9658203/debug-Tue_Sep_27_11_42_33_2022.log)

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
i guess it's because you're not using the beta @Ktrum161 
since the wifi bike support is still in beta

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by cagnulein** [comment]
#877

**Comment by Ktrum161** [comment]
@cagnulein, Beta App has same behavior using the setting recommended.  No Cadence (rpm) is collected.

**Comment by cagnulein** [comment]
@Ktrum161 Could you send me a fresh debug log to understand if all the settings are right? Thanks

**Comment by Ktrum161** [comment]
Fresh debug log:
[debug-Tue_Sep_27_13_25_33_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9658729/debug-Tue_Sep_27_13_25_33_2022.log)

**Comment by cagnulein** [comment]
@Ktrum161 nordictrack_2950_ip" QVariant(QString, "192.168.1.138") is still set. You have to blank it completely there and press ok. It must be without any character there
Let me know

**Comment by Ktrum161** [comment]
@cagnulein Confirmed that was the problem. Cadence is now populating!  Looking forward to testing this out!

**Comment by cagnulein** [comment]
Great! Let me know @Ktrum161

**Comment by Ktrum161** [comment]
@cagnulein is there any known issues with connecting to zwift from the apple beta app?  I was able to connect to zwift last night with an android device running a non-beta minus the cadence so couldn't go anywhere.  I am "searching" for a power device in Zwift with no devices found.  Zwift is running on a Windows 10 system.

**Comment by cagnulein** [comment]
Nope, it has to work as the production one. Try again with the android one.
If it works you have to play with the windows version of zwift. Zwift on windows is a headache for Bluetooth

**Comment by Ktrum161** [comment]
@cagnulein, could I get the beta version for Android as well?

**Comment by cagnulein** [comment]
@Ktrum161 Done, click here to join https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

**Comment by Ktrum161** [comment]
@cagnulein. I am having crashing on the beta app for Android.  I have setup the same configuration as on the iOS device, but it crashes over an over on startup.  If I am able to get one change on the app settings it is a miracle.  I was able to see the non-beta connect to ZWIFT last night, without cadence.  I now have the correct data being fed to the iOS device, but it is not showing up in either Windows or MAC versions of ZWIFT as a power device.

**Comment by cagnulein** [comment]
> am having crashing on the beta app for Android. I have setup the same configuration as on the iOS device, but it crashes over an over on startup. If I am able to get one change on the app settings it is a miracle

@Ktrum161 disable the bluetooth and wifi and enable the debug log. Then enable wifi and bluetooth back and if it crashes, send me the debug log here. It's the only way to understand which is the issue. 

> I now have the correct data being fed to the iOS device, but it is not showing up in either Windows or MAC versions of ZWIFT as a power device.

On the mac version unpair the iphone from the mac and leave it unpaired and reboot the mac, it should appear. On Windows, don't you see neither the Wahoo virtual device from QZ? Did you try to pair the iphone on windows?

Bluetooth is a nigthmare also with real bluetooth bike, so you're not alone in this mad world :)
But, no problem, you will fix it.

**Comment by Ktrum161** [comment]
@cagnulein I will test later today and get you the debug logs.  Eventually last night the wahoo kicker 0000 devices showed up from iOS sporadically.  When I start Zwift and have the Power and Cadence sensors connected, I can see my data in QZ app populating, but my avatar does not move in Zwift, as it is not detecting Cadence.  Is there supposed to be a "connected device" sensor appearing as well or just the two?

**Comment by cagnulein** [comment]
> Is there supposed to be a "connected device" sensor appearing as well or just the two?

Do you mean controllable device? Yes you have to see all the 4 green tile in the setup screen.
The fact that the wahoo kicker 0000 appears sometimes it seems to me a wifi issue or similar (wahoo dircon virtual device work with the wifi).

**Comment by Ktrum161** [comment]
@cagnulein Yes, Connected Device.  It shows up randomly and I actually had the wifi and bluetooth disabled and it was still showing up there in ZWIFT.  If I try to start riding, no cadence or movement is detected by ZWIFT. BTW, where are logs in Android?

**Comment by cagnulein** [comment]
> BTW, where are logs in Android?

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by cagnulein** [comment]
@Ktrum161 which model of mac do you have? we can try to run qz on windows or mac directly

**Comment by cagnulein** [comment]
@Ktrum161 any news?

**Comment by Ktrum161** [comment]
@cagnulein I wish. My controller board on the s22i died again, which controls incline, cadence, watts, and most important, resistance. I just put this one in 4 days prior. They are now sending all new wiring before sending another board. Right now my trainer is a paperweight. If all goes well, I might be able to build my own bike with all these spare parts

**Comment by Ktrum161** [comment]
@cagnulein, starting to wonder which bikes have the least reliance on circuitry. The resistance aspect is not good. I bought it for the feauture of automatic resistance that is controlled by the ifit workouts, but dont like that if the controller board goes, magnetic resistance also goes. I like the smart connectivity, but too much breakable components.

**Comment by cagnulein** [comment]
the majority of the bikes are made in this way, so I guess you were just unlucky :(

**Comment by Ktrum161** [comment]
With the s22i wifi connection, is the udp traffic only 1 direction to QZ. Any idea if it would ever be possible to adjust the incline or resistance based on Zwift terrain for this bike? Debating my options. I just rode on Zwift today for the 1st time and I am just using Wahoo cadence and speed sensors with a coros watch for heart rate on a dump trainer. I can see why auto resistance is needed.

**Comment by cagnulein** [comment]
Yes actually with @victorypoint in the #815 we started experimenting auto resistance but we hit a problem on the tcp socket 
I need time to port the socket to tcp to test it

**Comment by cagnulein** [comment]
Yes but I need to do auto inclination, thanks!

**Comment by bstoney** [comment]
I was able to get cadence and power working on my S22i with just a few adjustments to step 5 in the QZ Companion App instructions.

1. I am using QZ built and running on a Raspberry Pi
2. I set the `tdf_10_ip` instead of the `nordictrack_2950_ip`

After that it worked as described. Thanks @cagnulein ! I did try with QZ on my Android phone, but the TDF 10 IP setting is not available in the version I have installed.

![zwift-paired-devices](https://user-images.githubusercontent.com/1164857/196583579-37b74b74-1a45-4bc1-8033-a046f6fc82fa.PNG)

![s22i-ifit](https://user-images.githubusercontent.com/1164857/196583602-47e9a068-1d8c-457d-bc6f-291647ec1764.JPG)

**Comment by cagnulein** [comment]
@bstoney great!
If you want we can collaborate in order to add auto resistance to your bike! Check https://github.com/cagnulein/qdomyos-zwift/issues/815 i was attempting to do it, but the tablet drops the udp connection so I would like to port it to a tcp connection. Are you able to to so? It will much faster and easier if you can try yourself directly (i don't have a nordictrack device on my own).
Let me know 

@victorypoint FYI

**Comment by victorypoint** [comment]
Excellent news @bstoney !!

**Comment by bstoney** [comment]
Yeah I'll definitely take a look. I have been looking for a way to use zwift for ages and would be happy to help. Also I did a 25 min zwift ride and everything worked great. Auto resistance will make it even better.

**Comment by Ktrum161** [comment]
Also happy to help. I am waiting on my replacement controller board.

**Comment by bstoney** [comment]
I did see an issue in request resistance code of the companion app where the path to '/bin/sh' doesn't fallback to '/system/bin/sh' like the metrics code does.

**Comment by cagnulein** [comment]
> I did see an issue in request resistance code of the companion app where the path to '/bin/sh' doesn't fallback to '/system/bin/sh' like the metrics code does. That should be easy for me to test, if that doesn't work I look at implementing the TCP connection. 

ops! thanks!

**Comment by Ktrum161** [comment]
I am running the beta android app 2.11.41, not the raspberry pi edition. I do not have tdf_10_ip as an option. I got my new controller board installed and am ready to go to get this working with tcp and auto inclination/auto resistance.

**Comment by cagnulein** [comment]
@Ktrum161 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the latest beta

**Comment by cagnulein** [comment]
@Ktrum161 wow! I guess @bstoney is looking to create something about this, so let's wait his feedback.

**Comment by mash2k3** [comment]
Just requested the beta version for Android for my s22i
Besides the TDF10_IP settings, what other settings is important for correct output?
@bstoney mentioned a Qz companion app instruction i can not seem to find.

Thanks in advance and i am willing to help with troubleshooting as well.

**Comment by cagnulein** [comment]
> mentioned a Qz companion app instruction i can not seem to find.

check here https://github.com/cagnulein/QZCompanionNordictrackTreadmill

**Comment by mash2k3** [comment]
I installed beta version 2.11.82 and i can not find TDF10_IP field

**Comment by Ktrum161** [comment]
@mash2k3 
![Screenshot_20221027_171641](https://user-images.githubusercontent.com/15612994/198408575-dc9d5061-2dda-499a-b36b-e416d7f545b6.jpg)

**Comment by mash2k3** [comment]
@Ktrum161 that worked thank you

**Comment by mash2k3** [comment]
Is there additional settings to worry about in QZ app or in Zwift settings?

**Comment by cagnulein** [comment]
@mash2k3 sorry, what do you mean?

**Comment by mash2k3** [comment]
Just checking if there are additional settings that was missed to get the best zwift experience using the s22i bike

**Comment by cagnulein** [comment]
@mash2k3 do you have any particular issue? actually there aren't any specific setting.
usually on my proform bike i set the inclination gain to 2,  and i enable the negative double inclination setting

but i don't remember if your bike also manage the inclination

**Comment by mash2k3** [comment]
thank you, just curious is using an exercise bike for zwift just as good as a bike and a smart trainer?

**Comment by cagnulein** [comment]
@mash2k3 everything is about wattage. since the wattage is a standard unit, excercise bike or a smart trainer doesn't make any difference :)

**Comment by mash2k3** [comment]
I found double inclination and enabled it, but i cant find inclination gain.
Also is the resistance number on bike supposed to match the number on qz app?
Yesterday while i was riding on resistance 14 it said 8 in qz app

**Comment by mash2k3** [comment]
is it the one under advanced setting that says Zwift inclination gain?

**Comment by cagnulein** [comment]
> but i cant find inclination gain.

advances settings, zwift inclination gain

> Also is the resistance number on bike supposed to match the number on qz app?

for zwift, i'm using the inclination, so no

**Comment by mash2k3** [comment]
last question, does that mean you set your resistance to zero and just use inline for zwift or is there another value you leave it at?

**Comment by cagnulein** [comment]
> last question, does that mean you set your resistance to zero and just use inline for zwift or is there another value you leave it at?

no, i'm simply only commanding the inclination to the bike. The resistance is governed by the bike itself accordingly to the gear and the inclination

**Comment by Ktrum161** [comment]
@mash2k3, at this point with S22i all we can do is ride our bikes and see our power measured accurately in Zwift. Resistance isn't controlled by Zwift, nor is inclination. Further development and testing will be needed to add those features to allow zwift to control the bike, if possible. When I ride, I just leave incline at 0 for now and adjust resistance to try to hit power targets.

**Comment by cagnulein** [comment]
@Ktrum161 @mash2k3 actually an user made a PR https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/11 that works with his device. You can try on your device too.

**Comment by mash2k3** [comment]
If auto incline and resistance works that would be great, for now i believe its no big deal to manage resistance manually.
The icing on the cake would be to get zwift working on the built in tablet but the rom does not have enough space to install zwift

**Comment by Ktrum161** [comment]
@mash2k3 I think the issue is that zwift won't run on older Android 7. It needs Android 9+. Our bikes are running an end of life Android

**Comment by mash2k3** [comment]
@cagnulein what does PR mean? is it public release? and what did they get working. all i see is them talking about getting speed requests. did they get incline and resistance working?

**Comment by cagnulein** [comment]
@mash2k3 pr means pull request. a change that someone made.

if we achieve the speed forcing for the treadmill we can use the same algorithm for the resistance and inclination 

@bstoney is working on this :)

**Comment by mash2k3** [comment]
cool thanks, cant wait

**Comment by cagnulein** [comment]
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/15 we're getting closer
@JuergenNeubauer @mash2k3

**Comment by jjharaldson** [comment]
When I try to install the Norditrack Treadmill APK I get an error that says "Unfortunately the Qz Companion Norditrack Treadmill has stopped working". Also I seem to not be able to download the APK at all.

**Comment by Ktrum161** [comment]
@jjharaldson, the .apk must be installed using the adb install command. I also was not able to download and install directly via a web browser.

**Comment by jjharaldson** [comment]
I just sideloaded the apk via the usb port and still the same error. I also tried to install using Method 1 on the readme page but I couldn't get it to work. Can I ask how you did it? I was actually going to do another factory reset and see what happens.

**Comment by cagnulein** [comment]
> When I try to install the Norditrack Treadmill APK I get an error that says "Unfortunately the Qz Companion Norditrack Treadmill has stopped working". Also I seem to not be able to download the APK at all.

send me an adb logcat and i will be able to help you!

**Comment by jjharaldson** [comment]
@cagnulein what do I have to do to do that?

**Comment by cagnulein** [comment]
@jjharaldson with the usb cable connected do 

adb logcat -d > logcat.log

while you're recreating the issue

Let me know

**Comment by jjharaldson** [comment]
@cagnulein I tried a couple usb cables but when I list the connected devices the bike doesn't show up. I have debugging mode turned on, enabled stay awake and switched the usb connection from MTP to PTP . I tried to connect to it via my network with adb connect and it says the target machince actively refused it. Any suggestions? New cable?

**Comment by cagnulein** [comment]
@jjharaldson How did you put the apk on the tablet? By the browser? If so you can download some apk that can collect adb logcat directly from the tablet and then you can share the log generated via Wi-Fi. For example https://apkpure.com/it/logcat-extreme/scd.lcex

**Comment by jjharaldson** [comment]
I did it by the browser and by side loading from a usb drive. I will try what you suggest.

**Comment by jjharaldson** [comment]
@cagnulein Here is what I got, should be the last couple log(s) in the file.
[Log_2022-11-27_02-25-10.txt](https://github.com/cagnulein/qdomyos-zwift/files/10097389/Log_2022-11-27_02-25-10.txt)

**Comment by cagnulein** [comment]
@jjharaldson hi, thanks. in this log there is any trace of qz companion. did you run it while you're getting the log?

**Comment by jjharaldson** [comment]
@cagnulein I had the debugger open and then tried to open the qz companion app and the error message would pop up but nothing would log in debugger. This message does pop up when first opening the debugger app.  #window.
![AACE7C6B-F535-45C0-A41C-FB1FB01E2A51](https://user-images.githubusercontent.com/119028599/204145443-8a6091d7-55de-450e-a80e-4b883b59a8e6.jpeg)

**Comment by cagnulein** [comment]
@jjharaldson try to export the logs anyway, it should logs everything theoretically

**Comment by cagnulein** [comment]
@jjharaldson any news?

**Comment by jjharaldson** [comment]
@cagnulein i am going to try and trouble shoot this weekend. I’ll let you know

**Comment by JuergenNeubauer** [comment]
When I use the logcat with the -d (dump) option, is that different from using it without the -d? The dump is a one time dump, but without -d, the log file keeps growing until you cancel the logcat process.

There's also the option to do "-b all" to log all different systems. Might be overkill though.

**Comment by cagnulein** [comment]
> When I use the logcat with the -d (dump) option, is that different from using it without the -d? The dump is a one time dump, but without -d, the log file keeps growing until you cancel the logcat process.

-d
`Dumps the log to the screen and exits.`

doesn't the button on the qz companion work? i mean the logcat button. this should be enough to understand

**Comment by Ktrum161** [comment]
[logcat.log](https://github.com/cagnulein/qdomyos-zwift/files/10309421/logcat.log)
[debug-Tue_Dec_27_09_08_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10309422/debug-Tue_Dec_27_09_08_03_2022.log)

**Comment by cagnulein** [comment]
@Ktrum161 for the qz adb remote standalone I need also the logcat directly from the qz device instead of the qz companion device. Thanks!

**Comment by Ktrum161** [comment]
The "debug-Tue" is the log from QZ directly.  logcat.log is from Companion.

**Comment by Ktrum161** [comment]
[debug-Wed_Dec_28_07_31_40_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10314473/debug-Wed_Dec_28_07_31_40_2022.log)

**Comment by Ktrum161** [comment]
Sorry, thought I was shooting a video, but the screenshot shows what was happening over and over.  It is working to send swipe, whether in the ifit app or not, which makes sense.  However, on zwift I was at 0% while this continuous swiping down from around 9 to 0, like it was on a loop.  When zwift went up to 1, then 2, I didn't get an incline on the bike that matched.  

[debug-Thu_Dec_29_08_36_24_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10320041/debug-Thu_Dec_29_08_36_24_2022.log)
![screenshot](https://user-images.githubusercontent.com/15612994/209969868-1d91f4a7-6177-4bb6-a5fe-11b5d8e37f61.jpg)

**Comment by Ktrum161** [comment]
@cagnulein 
[debug-Thu_Dec_29_14_33_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/10322021/debug-Thu_Dec_29_14_33_25_2022.log)
Getting much closer. QZ is moving my bike, but zwift is showing much less movements, while the swipe commands are every second. Maybe we only take every 4 seconds? Worried the resistance motor is going to burn up.

**Comment by cagnulein** [comment]
i guess this is done! :)

**Comment by jjharaldson** [comment]
Sorry, Robert. I can’t get it to log any debug file. I tried and tried, for some reason it doesn’t work. I can’t believe that I cannot connect via the usb to do anything either.

**Comment by cagnulein** [comment]
@jjharaldson with @Ktrum161 we have a working setup (controlling resistance and metrics). I don't remember, do you have the metrics on qz at least?

**Comment by Ktrum161** [comment]
@jjharaldson , how far did you get in these instructions?:
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/README.md

I had issues doing the install via the browser.  I recommend executing the .bat script as an administrator.  Make sure your bike and the windows computer you are running the script from are on the same wireless network.  Please make sure that the QZ application on your phone is not running at the same time as you are trying to install.  If you have the QZ application running and it is configured properly, it will be connecting to your bike via ADB, which may cause issues with the script also trying to connect to the bike via ADB.  I had issues with only being able to connect to the bike, 1 device at a time.  Also, once the companion application is installed on the console, go into application settings in the console and give the QZ companion app permissions to read the file structure.  It is reading the ifit logs and broadcasting the logs.  The QZ app on your phone is able to read those logs, but will also (if Android), be able to send ADB commands to the S22 to change the incline to follow along with your Zwift ride. 

@cagnulein I see the companion app was updated recently.  We went through numerous beta versions.  The last one I used and had success with was the original basic one that did not have adb built in.  I just want to make sure the current version is correct.  Multiple ADB connections has a problem for some reason on the S22.

**Comment by cagnulein** [comment]
@Ktrum161 right, he has to use yours version. I didn't change the companion app yet to remove the adb remote for your bike 

That's why I asked if at least he can get the metrics

**Comment by Ktrum161** [comment]
@cagnulein But to get the metrics, he needs to be able to install the companion app. Or am I misunderstanding what you are asking for.

**Comment by cagnulein** [comment]
Yes right, but the metrics are correctly sent from all the companion versions. Viceversa for the controllable point of view, you need that the specific version

**Comment by jjharaldson** [comment]
I can’t even get the app to run. I install it and it gives me the error message that the app has stopped working, immediately when in open it. I tried to debug via the usb port and i can’t see the bike when connected. And then tried that app that robert suggested but nothing logs when I run it while the error happens. I just don’t understand why the usb port won’t see the bike on my pc.

**Comment by cagnulein** [comment]
@jjharaldson that error should be fixed now with the latest companion.give it a try!

**Comment by jjharaldson** [comment]
Sounds good, I will also install it the way @Ktrum161 suggest too.

**Comment by Ktrum161** [comment]
@jjharaldson which bike do you have? You are mentioning usb ports.

**Comment by jjharaldson** [comment]
S22i

**Comment by jjharaldson** [comment]
@Ktrum161 @cagnulein  I try to install via your suggestion and it pings the bike fine but cannot establish and ADB connection. I attached the log.txt. I remember it doing that before as well. That is why I did the browser.
[QZ-Companion-log.txt](https://github.com/cagnulein/qdomyos-zwift/files/10421382/QZ-Companion-log.txt)

**Comment by Ktrum161** [comment]
@jjharaldson just to make sure, did you go into admin mode on the s22i console, enable developer mode, then go into developer settings and enable adb on the s22?  Also, make sure that the QZ app on your phone is completely off, just in case it is trying to connect via adb at the same time. I sometimes had issues with the adb connection. Usually turning off on the console, then enabling again seemed to work. ADB should be able to have multiple connections, so it is strange that the s22i is temperamental about it.

**Comment by jjharaldson** [comment]
yep, enabled usb debugging and actually uninstalled the app on my phone. tried connecting from a different pc and it still refuses the connection. i can try to rebooting the bike to see if that works.

**Comment by Ktrum161** [comment]
That might help

**Comment by jjharaldson** [comment]
Rebooted a few times and same issue.

**Comment by Ktrum161** [comment]
Are you running android on your phone or iOS? If Android, you might try this Remote ADB Shell - Apps on Google Play 
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Remote ADB Shell - Apps on Google Play
 
Connect to ADB running on another Android device over the network
  |   |

  |

  |

  

This app is embedded into the QZ beta. See if you can connect with this. 


Sent from Yahoo Mail for iPhone


On Sunday, January 15, 2023, 5:24 PM, jjharaldson ***@***.***> wrote:




Rebooted a few times and same issue.

**Comment by jjharaldson** [comment]
I am on iOS but I probably could find and old android phone to see if that works

**Comment by jjharaldson** [comment]
Connection failed, says connection was refused. I appreciate your time man. But for some reason my tablet won’t let and adb connection. Sucks

**Comment by Ktrum161** [comment]
Yeah, ya got me. If it is set for adb enabled, no idea why it wouldn’t be enabled.

**Comment by JuergenNeubauer** [comment]
Hello,

When I had the issue with the refused connection, what helped most of the time was to switch off USB debugging AND Revoke USB debugging authorizations. Then, switch USB debugging on again.
Hope that helps.

**Comment by cagnulein** [comment]
@jjharaldson you can install the apk from the tinyurl. did you try?  https://tinyurl.com/qz-companion

**Comment by jjharaldson** [comment]
I tried that way the very first time. And that’s when that error occurred. I will try again

**Comment by cagnulein** [comment]
yes but i updated it in the mean time @jjharaldson 
let me know
