### ISSUE TITLE
Apple Watch Heart Rate using the iPad

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#957]
Broadcasting via UDP the HR from the phone to the ipad, we should be able to get the HR into the iPad directly. The ipad should answers back with the kcal and the distance at least.

**Comment by cagnulein** [comment]
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

**Comment by cagnulein** [comment]
I requested a Multicast Networking Entitlement https://developer.apple.com/contact/request/networking-multicast

**Comment by cagnulein** [comment]
https://github.com/eugenebokhan/bonjour

**Comment by cagnulein** [comment]
https://boramaapps.medium.com/ios-osx-connections-with-network-framework-and-bonjour-service-7fa6130f5789

**Comment by cagnulein** [comment]
https://github.com/standinga/PeerConnections/tree/main/MultiConnect

**Comment by cagnulein** [comment]
```
UIDevice.current.userInterfaceIdiom == .pad
UIDevice.current.userInterfaceIdiom == .phone
```

**Comment by RickNY** [comment]
Log files from iPhone & iPad - no HR from watch.  Watch was displaying HR.  iPad was linked to tread, but not displaying HR. 

[iPad_debug-Sun_Oct_2_13_21_33_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9693100/iPad_debug-Sun_Oct_2_13_21_33_2022.log.txt)
[iPhone_debug-Sun_Oct_2_13_21_33_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9693101/iPhone_debug-Sun_Oct_2_13_21_33_2022.log.txt)

**Comment by cagnulein** [comment]
@RickNY i checked the logs. I guess maybe i found why you're not seeing it. I'm updating the heart tiles only when i receive some metrics from the treadmill. So try to do the same but also starting the treadmill.
Let me know

**Comment by RickNY** [comment]
> @RickNY i checked the logs. I guess maybe i found why you're not seeing it. I'm updating the heart tiles only when i receive some metrics from the treadmill. So try to do the same but also starting the treadmill. Let me know

Maybe I'm misunderstanding -- the iPad was receiving metrics from the treadmill in that previous log..  I've attached two more just in case
`Sun Oct 2 13:23:47 2022 1664731427524 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Speed: 0.80467"
Sun Oct 2 13:23:47 2022 1664731427526 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Inclination: 0"
Sun Oct 2 13:23:47 2022 1664731427527 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current KCal: 5.11463"
Sun Oct 2 13:23:47 2022 1664731427529 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Distance: 0.02297"
Sun Oct 2 13:23:47 2022 1664731427530 Debug: /Users/cagnulein/qdomyos-zwift/src/bluetooth.cpp void bluetooth::debug(const QString &) "Current Heart from Apple Watch: 0"`

[iPad-debug-Mon_Oct_3_06_32_33_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9696824/iPad-debug-Mon_Oct_3_06_32_33_2022.log.txt)
[iPhone-debug-Mon_Oct_3_06_31_22_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9696825/iPhone-debug-Mon_Oct_3_06_31_22_2022.log.txt)

**Comment by cagnulein** [comment]
sorry @RickNY you were right, i probably checked the iphone log instead of the ipad one.
Ok let's try to understand this. This morning I saw an issue about this feature that maybe it's the same that you're facing.

The problem is: if you close one app (iphone or ipad) you have also to close the other one. I mean, it works only if they starts from a clean session. Of course it's something that I have to fix.

So in order to do so, let's do in this way:
1) open qz on the ipad and full close it with the swipe
2) do the same thing on the iphone
3) start again qz on the ipad and let it connect to the treadmill
4) start the workout from your apple watch

in this way does it work all the time? On my end yes, so it should works to you too.
In the meantime I'm trying to fix the desync when you close a side.
Thanks

**Comment by RickNY** [comment]
I’ll try this in the order you specified - I’m pretty sure I had tried those combos, and also swiped away the watch app on the phone as well. I’ll get back to you.

**Comment by cagnulein** [comment]
ok i fixed the problem that I saw this morning. I hope it will fix also your issue. I'm sending you another one later today @RickNY

**Comment by RickNY** [comment]
OK, got a little closer with the update that came.. I was getting heart rate initially -- but it stopped updating on the iPad.. iPad kept reporting 70, it changed a few times but stopped updating after maybe a minute or so.. The QZ app on the watch was showing the correct HR the entire time.

These should be the logs from that.. 

[iPhone_debug-Mon_Oct_3_17_44_16_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9701734/iPhone_debug-Mon_Oct_3_17_44_16_2022.log.txt)
[iPad_debug-Mon_Oct_3_17_43_55_2022.log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9701735/iPad_debug-Mon_Oct_3_17_43_55_2022.log.txt)

**Comment by cagnulein** [comment]
@RickNY Did you check also the distance and kcal on the watch? They stop too? 
Today I will work on creating on a better debug log for this

**Comment by RickNY** [comment]
Sorry I wasn’t clear with last sentence - watch was updating properly entire run.

**Comment by cagnulein** [comment]
@RickNY hah so it means that iphone is getting the metrics from the ipad correctly. it's just the ipad that it sometimes lost the connection from the iphone.

**Comment by RickNY** [comment]
OK... Just decided to try something on a whim.. Did a "Reset Network Settings" on both the iPhone & iPad.. Now, it seems to be working -- BUT -- I may have been missing an important step before (DUH).  I dont think I was manually launching QZ on the phone -- I was making sure it was closed so it wouldnt latch on to the BT connection to the tread -- and thinking that launching the watch app by itself was also opening the app on the phone.  So -- here is what is working:

1) Swipe/close app on iPad and iPhone
1) On tread, I set my profile name, weight and start manually
2) Immediately open QZ app on iPad
3) Open QZ app on iPhone <-- was missing this step
4) Open QZ app on watch and choose workout type and click Start
5) HR appears after around 5-10 seconds on iPad
6) Tread finishes init after 30-40 secs

Since its raining today (and cold) - I'll be doing my workout on the tread later today.

Also - I'm going to open another feature request - but I think should be easy -- is it possible to include elevation gain in the workout email?  I realize Apple Health may not allow it as part of the workout for indoor exercises, but having in the summary email would be nice.

**Comment by cagnulein** [comment]
> and thinking that launching the watch app by itself was also opening the app on the phone

yes it should auto run it. Infact it's the same flow as I did every time



> Also - I'm going to open another feature request - but I think should be easy -- is it possible to include elevation gain in the workout email? I realize Apple Health may not allow it as part of the workout for indoor exercises, but having in the summary email would be nice.

absolutely I thought that it was already in!

**Comment by ndevries84** [comment]
This is awesome, worked first try!  Turned iPad on first, then turned on apple watch app, it asked for permissions, and then instantly connected.  Way quicker then any other HR monitor I have used in terms of connecting and supplying the initial HR

**Comment by RickNY** [comment]
OK.. Did my walk this evening on the iPad.. Everything worked great with Apple Watch HR!

![ipad_hr](https://user-images.githubusercontent.com/702933/193944231-e572d668-5016-429b-9bc1-3064d6a8c87f.jpg)

**Comment by cagnulein** [comment]
yeah! thank you guys for the feedbacks! i'm closing this one but if you have issue let me know

@RickNY so the reset help somehow?

**Comment by cagnulein** [comment]
seems that ios 16.3.1 broke something about this

**Comment by cagnulein** [comment]
> just checked and it worked on my side. BUT i saw something that could explain your issue and also how to fix it as a workaround. Follow these steps:
> 1) be sure that your iphone and ipad are on the same wifi network
> 2) turn on the QZ app on the watch and press start, your HR will appear on the QZ app on the watch
> 3) turn on QZ on the ipad and be sure your heart rate belt name is set to "Disabled" (should already be)
> 4) if your HR doesn't appear on the ipad or it just freezes, press stop on the watch app; on the iphone, open the qz app, and full close it (with the swipe gesture). Then put the iphone sleep (i mean you don't need to use it anymore, it has just to stay connected to the wifi) and press start again on the QZ app on the watch. In this way it works every time on my side
> Also, in order to debug it, you can install the discovery app, and you should see something like this.
![Screenshot 2023-04-01 at 17 48 34](https://user-images.githubusercontent.com/48216/229299840-a35245ca-bca7-4899-a155-044a85bf8d20.png)
 If the qz_iphone is empty, you have to repeat the point 4. Let me know!
