### ISSUE TITLE
[BUG] Should NordicTrack Commercial X11i treadmill work with Android app? 

### ISSUE THREAD

**Issue by JuergenNeubauer** [cagnulein/qdomyos-zwift#961]
**Describe the bug**
Android app doesn't connect to NordicTrack X11i treadmill.

**To Reproduce**
Switch on treadmill
Switch on Android app.
Program doesn't see treadmill. There is a Bluetooth device appearing when I switch on the treadmill.

**Expected behavior**
Android app should connect to X11i treadmill. How can I debug? I can't connect with nfconnect either.

**Comment by cagnulein** [comment]
@JuergenNeubauer What do you see on nrfconnect about your treadmill? Send me a screenshot 
Thanks

**Comment by JuergenNeubauer** [comment]
Hello Roberto,

I hope the screenshots are clear enough, I could possibly do them again.

Two devices appear when I switch on the treadmill and start the belt: NDNB2
and NDN9U

Thanks for any help. My wife wanted to have this incline treadmill/trainer.
I've been riding on Zwift ever since our kids arrived. I would love to go
back to my running days, too, by using the treadmill on Zwift in just the
same immersive way that I'm used to from riding my bike in Zwift with a
Taxc Neo.

Best, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer are you sure that they are the treadmill? are you already use an app for the treadmill? if so which one? are you able to provide an hci snoof log following this guide while you're using the actual android treadmill app and while you're changing the inclination and the speed from the app directly 

https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

**Comment by JuergenNeubauer** [comment]
Hi,
I think I'm sure that as soon as I start the belt or increase the speed or change the inclination these Bluetooth devices appear.

I just saw a note on Nordictrack's site that their treadmills with touch displays do not work with their Android iFit app. So I can't observe any communication via Bluetooth either.

Any other ideas? I'm not sure this is worth the effort, it seems these iFit pieces of art are a big pain. In the worst case I would have to ask you to refund me the costs for purchasing your app so that I can also uninstall it from my phone.

Please let me know either way.

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer Does your treadmill has an android tablet with ifit built in? If so it's the same of #815

Did you try to use the qzcompanion app on the tablet?
Let me know

**Comment by JuergenNeubauer** [comment]
Hi Roberto,

That's correct, the treadmill has an Android tablet that runs iFit. Some time ago it updated itself to a version where I could not access the Privileged Mode any more. But that's a different issue many iFit and NordicTrack users are struggling with right now.

Via a factory reset I reverted to an iFit version where I can still access Privileged Mode. I can try to install qzcompanion directly onto this tablet. I can report back once I tried getting this done. I'm not sure what the next steps would be to reach my goal to enable Zwift to control the inclination (and/or speed) of the treadmill if this works.

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer Me and the original poster of that ticket we elaborated a way to control speed and incline via qz. I just need a little time to trim it because the android tablet of the treadmill has some limitations, and since I don't have a treadmill here, every time I have to ask to the OP to test it :)

But let's see first if the companion app works for you too
Let me know

**Comment by JuergenNeubauer** [comment]
Ok, great, some success. I was able to install the NordicTrack QZ Companion following the instructions.

But when I tried to set up the QZ Fitness app on Android, the Android app crashed as soon as I restarted after setting the IP address for the iFit treadmill.

I would probably like to run the QZ Fitness program on the Windows machine where I run Zwift, but I could not find a Windows version that has the iFit IP address option. I only found an older version, about 3 versions behind the latest which only has sources and OSX executables in the release files.

I don't know whether I can help with testing on my NordicTrack X11i incline trainer. Please let me know.

Thanks, Juergen

**Comment by cagnulein** [comment]
Hi @JuergenNeubauer 
For android send me the debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
For windows you can get it here https://github.com/cagnulein/qdomyos-zwift/actions/runs/3166737988/jobs/5156666656

Let me know

**Comment by JuergenNeubauer** [comment]
Hi Roberto,

Thanks for the instructions. See the debug logs attached.

I tried the Windows exe and it would not show any tiles nor does it connect
or show up in Zwift.

So what's next?

Best, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer for windows: do you have a dongle Bluetooth on it? Qz needs the Bluetooth to discover also Wi-Fi devices

I will check the log tomorrow 
Thanks

**Comment by cagnulein** [comment]
Note for me

`bool nordictrackifitadbbike::connected() {}`

**Comment by JuergenNeubauer** [comment]
[debug-Sun_Oct_2_10_46_48_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9694801/debug-Sun_Oct_2_10_46_48_2022.log)

Hi,

I attached a debug log of the Windows app. Still no tiles although my Windows laptop should have Bluetooth built in and I even added a Bluetooth USB dongle. Maybe you can find something useful.

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer the windows issue is that you're not connected to any bluetooth devices at all. QZ (something i need to fix) wants to see at least 1 bluetooth device. So for example connect a bluetooth headphone to windows and try again.
In the meantime I'm fixing the android issue

**Comment by cagnulein** [comment]
in the meantime @JuergenNeubauer 
send me an email to roberto.viola83 at gmail.com indicating this ticket so I can send you the new beta for android
Thanks!

**Comment by JuergenNeubauer** [comment]
> @JuergenNeubauer the windows issue is that you're not connected to any bluetooth devices at all. QZ (something i need to fix) wants to see at least 1 bluetooth device. So for example connect a bluetooth headphone to windows and try again. In the meantime I'm fixing the android issue

Oh, ok. I had switched off all the BT devices so not to confuse this. I paired the Tacx Neo and now QZ displays that. But I still don't seem to get data from the treadmill where the NordicTrack Companion should be running. I can ping the treadmill's IP address. How else can I tell whether or not the Companion is alive on the treadmill? Should I go back to Privileged Mode?

Thanks, Juergen

**Comment by cagnulein** [comment]
@JuergenNeubauer now put the manual device setting to "wifi" in the advanced setting. 
I mentioned about the headphone previously because i don't want to show a compatibile device to QZ :D because, as you see now, you're seeing the tiles from the tax neo instead of the treadmill :D

Let me know

**Comment by JuergenNeubauer** [comment]
Only a BT headphone connected: Tiles don't appear though

[debug-Sun_Oct_2_23_27_03_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9695115/debug-Sun_Oct_2_23_27_03_2022.log)

Taxc Neo attached via BT: tiles appear, but with Neo data

Switched WIFI on in the Advanced settings to no avail.
[debug-Sun_Oct_2_23_29_45_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9695137/debug-Sun_Oct_2_23_29_45_2022.log)

**Comment by cagnulein** [comment]
> Switched WIFI on in the Advanced settings to no avail.
> [debug-Sun_Oct_2_23_29_45_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9695137/debug-Sun_Oct_2_23_29_45_2022.log)

this last attempt is ok from the log but i don't receive any data from the companion. Is the companion app running? Are all the permission to the qz companion app are granted in the treadmill tablet?

**Comment by JuergenNeubauer** [comment]
I don't know, I never set any specific permissions on the treadmill tablet. What should I be looking for? I will check the treadmill tablet tomorrow, it's late here in Arizona.

**Comment by cagnulein** [comment]
@JuergenNeubauer sure no problem! in the tablet settings, you will find the permissions section for apps (as in the android phone). Check the qz companion, ALL the permissions must be granted (by default they aren't).
Let me know and have a good night!

**Comment by cagnulein** [comment]
@victorypoint FYI ;)

**Comment by JuergenNeubauer** [comment]
Hi Roberto,

Here are all the log files of the QZ Companion installation I could find. Anything else missing?

FYI, I set all possible permission for the QZ Companion on the treadmill tablet. Now QZ receives data from the Companion. 
This is a NordicTrack Commercial X11i Incline Trainer treadmill.

So will it be possible to control the inclination of the treadmill from Zwift?

Best, Juergen

[dumpsys.log](https://github.com/cagnulein/qdomyos-zwift/files/9701877/dumpsys.log)
[logcat.txt](https://github.com/cagnulein/qdomyos-zwift/files/9701878/logcat.txt)
[QZ-Companion-log.txt](https://github.com/cagnulein/qdomyos-zwift/files/9701879/QZ-Companion-log.txt)

**Comment by JuergenNeubauer** [comment]
Hello,
The latest update to the QZ Android app now doesn't crash any more when I configure the IP address for the WIFI connection with the QZ Companion app on the treadmill.

However, when I select the Wahoo connection in Zwift, both speed and inclination are zero permanently. Is there something missing? Will this be eventually able to let Zwift control the incline of the treadmill?

Thanks, Juergen

**Comment by cagnulein** [comment]
> Hello,
> 
> The latest update to the QZ Android app now doesn't crash any more when I configure the IP address for the WIFI connection with the QZ Companion app on the treadmill.

Great!

>
> However, when I select the Wahoo connection in Zwift, both speed and inclination are zero permanently. Is there something missing? Will this be eventually able to let Zwift control the incline of the treadmill?


Are you seeing the speed and the inclination correctly on qz? Yes this will control the inclination as soon as I will have time to implement it :)
> 
> 
> 
> Thanks, Juergen

**Comment by JuergenNeubauer** [comment]
Sorry, I wasn't clear about it. Both speed and inclination are correctly displayed in the QZ Android app.

Thanks, so exciting.

**Comment by cagnulein** [comment]
wow that's great @JuergenNeubauer !
About the zwift issue, are you running zwift on a separate device?
could you please collect a debug log from android https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks!

**Comment by JuergenNeubauer** [comment]
I'm using an Android phone to run QZ. Zwift runs on a Windows laptop with built-in Bluetooth.

At some point I ran QZ on the Windows computer. That worked to transmit running pace data to Zwift. Until the unexpected event happened that an unexpected "Trial time" was up and I was asked to pay for further service. That was both unexpected and upsetting, as it was never disclosed from the beginning that this service is based on a subscription model. I already paid for the Android app, so I'll stay with that.

Here's a debug log from the phone:
[debug-Tue_Oct_4_17_48_59_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9711831/debug-Tue_Oct_4_17_48_59_2022.log)

**Comment by cagnulein** [comment]
sorry for the subscription request but it's the only way to achieve something like this in the windows world. @JuergenNeubauer  i will check the log

**Comment by JuergenNeubauer** [comment]
Sure, I understand the monetary constraint, it would just be nice to know about it from the beginning so that there is no surprise jumping out. 

Thanks, Juergen

**Comment by cagnulein** [comment]
Yes you're right,I will add popup from the beginning

**Comment by cagnulein** [comment]
I checked the android log @JuergenNeubauer and I saw 2 things:
1) there isn't any connection via Wahoo virtual device to the android. It seems that there is some firewall or something that prevents the connection. Do you have something similiar on your network?
2) QZ is streaming bluetooth FTMS correctly. Did you try the bluetooth virtual device instead on zwift? If so and it didn't work, did you already try to change the name of the android phone to "run" (only 3 letters) and restart your phone?

@JuergenNeubauer since you already paid for the android version, 
send me an email to roberto.viola83 at gmail.com indicating this ticket and I will add you to the full time version for windows

**Comment by JuergenNeubauer** [comment]
Hello,

1. My home network is "typical" in the sense that I never configured anything in particular for the WIFI system or the Windows 10 laptop. I don't know whether I need to grant any permissions in the Windows Firewall. I don't know what to look for though, whether it's about Zwift or Bluetooth? Should I try to run a Wireshark capture?
2. That's interesting. I renamed the Bluetooth name of my phone to "run" as suggested and now Zwift connects to this Bluetooth device called "run" just fine. I only see the Wahoo virtual device show up as a "Cadence" sensor in Zwift, but it doesn't do anything because there is no sensor connected to this, I think.

So now the data transfer from the treadmill to Zwift works. If there were any instructions about the Bluetooth device name anywhere, I certainly didn't catch that.

Thanks, Juergen

**Comment by cagnulein** [comment]
> So now the data transfer from the treadmill to Zwift works. If there were any instructions about the Bluetooth device name anywhere, I certainly didn't catch that.

that's about specific bluetooth chip of your phone. it shouldn't be necessary but i saw that with cheap bluetooth chip on android phone it helps

so we are ok with this?

**Comment by JuergenNeubauer** [comment]
I guess the Pixel 2 is showing its age.

Yeah, this part works.  I don't know about the reverse, Zwift controlling the inclination. Should that also work now? I forgot to check.

**Comment by cagnulein** [comment]
Nope, I have to do this part of code. I will do in the next weeks

**Comment by cagnulein** [comment]
yeah bot I have to do this :)

**Comment by cagnulein** [comment]
I’m closing this one since you opened also #1010
