### ISSUE TITLE
Setting bluetooth_lastdevice_* should be done for ALL the devices

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#962]
about the bluetooth_lastdevice_* yes it has to be in ALL the devices, confirmed.

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/issues/950#issuecomment-1264552934_

**Comment by drmason789** [comment]
i.e. this needs to be done for all the devices:

https://github.com/cagnulein/qdomyos-zwift/blob/5c8c8881e0f089c0cb6daccf8059a3aeb0344d95/src/bluetooth.cpp#L1287-L1292

I would point out that the code for the non-bluetooth devices being searched for here will simply register the name and address/UUID of the unrealted device being processed...but that's another issue I would connect to #889 .

I intend to implement this for all the devices by putting the code to store the values in the settings and call that. 
In #921 this can be implemented in one place, at the end of the loop.

**Comment by cagnulein** [comment]
Yes bot, I have to do also this test

**Comment by cagnulein** [comment]
@drmason789 this would be ok for merge?

**Comment by drmason789** [comment]
> @drmason789 this would be ok for merge?

Yes

**Comment by cagnulein** [comment]
could you do a PR or you did already? I can't see it
Thanks @drmason789

**Comment by drmason789** [comment]
> could you do a PR or you did already? I can't see it
> Thanks @drmason789

#963

**Comment by cagnulein** [comment]
ops sorry!

**Comment by cagnulein** [comment]
Thanks @drmason789
