### ISSUE TITLE
[BUG] Dircon virtual device is not showing on Zwift for sole f80 treadmill

### ISSUE THREAD

**Issue by Olspei** [cagnulein/qdomyos-zwift#965]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
[debug-Mon_Oct_3_10_32_19_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9697917/debug-Mon_Oct_3_10_32_19_2022.log)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @Olspei i don't see the log

**Comment by Olspei** [comment]
[debug-Mon_Oct_3_10_32_19_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9697920/debug-Mon_Oct_3_10_32_19_2022.log)

**Comment by cagnulein** [comment]
@Olspei do you have another one? this one is truncated, thanks

**Comment by Olspei** [comment]
[debug-Mon_Oct_3_10_43_56_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9697992/debug-Mon_Oct_3_10_43_56_2022.log)

**Comment by cagnulein** [comment]
@Olspei so can i close this?

**Comment by cagnulein** [comment]
> [debug-Mon_Oct_3_10_43_56_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9697992/debug-Mon_Oct_3_10_43_56_2022.log)

i need a log where you are correctly connected to the f80 treadmill with qz, so i can double check the dircon connection
thanks

**Comment by cagnulein** [comment]
@Olspei any news?

**Comment by Olspei** [comment]
We think we have it working.  Just with two devices.

**Comment by cagnulein** [comment]
hah sorry i missed the connection between your nick here and messenger ;)
ok i'm closing this one. Reopen it in case you have some news
