### ISSUE TITLE
VZFit cadence sensor detected, but RPM tile doesn't change

### ISSUE THREAD

**Issue by geodrome** [cagnulein/qdomyos-zwift#967]
I'm using QZ with VZFit cadence sensor. In Settings under Accessories > Cadence Sensor Options, I'm able to select my sensor. I also enabled "Cadence Sensor as a Bike." QZ detects the sensor, but when I pedal RPM tile doesn't change. The VZFit cadence sensor works fine when I use it directly with VZFit.

It's an "old school" VZFit sensor that Virzoom used to produce, not a "mainstream" sensor. I don't believe Virzoom produce this sensor any longer. They now rely on mass produced sensors. Perhaps the issue is that it's an unusual sensor? It's one of these: [https://virzoom.com/vzfit-for-personal-use-now-available.../](https://virzoom.com/vzfit-for-personal-use-now-available-for-pre-order/?fbclid=IwAR0x_cWkj0weDwbFRTVaUowCx5kB1yZRZRzpOt3rDfAcrha-k6WAwZ9YawA)

HERE'S THE DEBUG LOG:
[debug-Tue_Oct_4_19_38_45_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9708999/debug-Tue_Oct_4_19_38_45_2022.log)

**Comment by cagnulein** [comment]
hi @geodrome yes unfortunately this is not a standard cadence sensor. It's a custom one and it's use a custom protocol that I don't know. We can move in 2 ways
1) buy a very cheap classic cadence sensor
2) we can ask to VZfit the specification of it

Let me know what you think

**Comment by geodrome** [comment]
I am unable to get a new cadence sensor right now, so if possible, I’d like to go with your second suggestion.

I've been in touch with Eyal from VZFit Support about the issue. Just sent the message to him, so he hasn't had the chance to reply. I've directed him to this issue.

Perhaps you have another contact at VZFit that you've worked with before?

**Comment by cagnulein** [comment]
yes @geodrome @emalafeew could you please help here? thanks!
