### ISSUE TITLE
Open Train Program Update Suggestions[REQ]

### ISSUE THREAD

**Issue by ndevries84** [cagnulein/qdomyos-zwift#968]
**Is your feature request related to a problem? Please describe.**

I have a 9 week program Power Zone program I want to create and upload to the Train Program Area, but if I add 36 workouts it 
will quickly become cluttered.
 
IF I add a folder it just looks like this and isn't navigable
![File](https://user-images.githubusercontent.com/10392137/193938962-1f87aea8-34ba-435e-8eac-9d9771cc4668.jpg)

**Describe the solution you'd like**
Allow for nesting of Folders, and files 

- Easy Intervals.zwo
- HIIT Aerobic.zwo
- Programs
   - Power Zone
      - Week 1 Class 1.zwo
      - Week 1 Class 2.zwo   
      - Week 2 Class 2.zwo
      - etc
   - Half marathon in 10 weeks
   - My first 10k

**Describe alternatives you've considered**

The other alternative is to  add them one at a time, but that involves finding them through the iPhone files app which is even more complicated when I just want to work out.

**Additional context**
This probably applies to the Open GPX, and Video GPX project your working on as well. 
A way to mark the workout as complete would also be amazing, so you can see what you have completed.
Auto Progress to the next workout in the list if its alphabetical (like creating a workout stack)

**Comment by cagnulein** [comment]
@ndevries84 thanks for the feedback! Done for both gpx and training program!
If you have the folder already and there isn't any copyright on them I can bundle them in the QZ app if you add the folder to this ticket. Let me know!

**Comment by cagnulein** [comment]
@ndevries84 any news?

**Comment by cagnulein** [comment]
@ndevries84 any news?
