### ISSUE TITLE
[REQ] Add option to update weight from Apple Health

### ISSUE THREAD

**Issue by RickNY** [cagnulein/qdomyos-zwift#969]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice if there was a checkbox under the user weight section allowing QZ to automatically update this from "Weight" stored in Apple Health. 

**Describe alternatives you've considered**
Manual updating of weight when it changes to keep stats more accurate.. 

**Additional context**

**Comment by cagnulein** [comment]
Same as #520 :)
