### ISSUE TITLE
Average Speed in the Email doesn't match

### ISSUE THREAD

**Issue by istvanszegedi** [cagnulein/qdomyos-zwift#977]
The problem is not with the program or the connection, but with the email report received afterward.
Treadmill: Capital Sports Infinity Pro 4
QZ (v 2.11.67) runs on Samsung S20+ (Android 12)
ZWIFT runs on Lenovo Yoga Tab 11 Pro (Android 12)

This data was sent by e-mail:
Average Speed: 4.9
Max Speed: 11.0
Calories burned: 388
Distance: 4.6
Elevation Gain (meters): 0.0
Average Watt: 207
Max Watts: 219
Average Watt/Kg: 2.7
Max Watts/Kg: 2.9
Average Heart Rate: 140
Max Heart Rate: 156
Total Output: 341
Elapsed Time: 00:27:27
Moving Time: 00:27:27
Weight Loss (Kg): 0.05
Estimated VO2Max: 36.8

It can be seen that the values contradict each other. The distance is 4.6 km, time: is 27min 27sec, however, the average speed cannot be 4.9 km/h.
In reality, my speed was 10.5 km/h. The max 11 km/h is still correct because I pressed the 11 km/h button and went back to 10.5 from there.

The Weight Loss (Kg): 0.05 is also strange. I think 0.5 is closer to reality than the 0.05

I attached the debug logs.
[qz_debugfiles_Istvan.Szegedi_2022.10.11.zip](https://github.com/cagnulein/qdomyos-zwift/files/9758782/qz_debugfiles_Istvan.Szegedi_2022.10.11.zip)

**Comment by cagnulein** [comment]
@istvanszegedi the debug log is missing in the zip file. could you please attach it?

**Comment by cagnulein** [comment]
> The Weight Loss (Kg): 0.05 is also strange. I think 0.5 is closer to reality than the 0.05

no, that's right. 388 / 7716.1854 = 0.05 kg // comes from 1 lbs = 3500 kcal. Converted to kg

**Comment by istvanszegedi** [comment]
[qz_debugfiles_Istvan.Szegedi_2022.10.11.zip](https://github.com/cagnulein/qdomyos-zwift/files/9762738/qz_debugfiles_Istvan.Szegedi_2022.10.11.zip)
debug files added to zip

**Comment by cagnulein** [comment]
fixed @istvanszegedi you will see this patch in the 2.11.68 Are you still in the private beta of android, isn't it?

**Comment by cagnulein** [comment]
ok thanks, you will see an update in the next hours

**Comment by istvanszegedi** [comment]
I did a test Today just now. I run 1 km with a speed between 10.5 - 15 km/h. Now the average speed: OK.
