### ISSUE TITLE
[REQ] Bike Support Merach MRK-S02-0B8D

### ISSUE THREAD

**Issue by etorr** [cagnulein/qdomyos-zwift#978]
**Bike Support for IOS\Android APP

I was able to get the bluetooth log from android device , app sees bike but does not connect to it. Bike works on some other 3rd party apps fine. 
![Screenshot_20221011-082636](https://user-images.githubusercontent.com/9095448/195220048-d09a2779-7f4f-496c-a96a-3e4f3edbe9ed.png)
[btsnoop_hci.log](https://github.com/cagnulein/qdomyos-zwift/files/9760428/btsnoop_hci.log)
![Screenshot_20221011-082607](https://user-images.githubusercontent.com/9095448/195220069-a59e82b2-8111-4e36-8d82-b94e36295ad4.png)

Thank You !

**Comment by cagnulein** [comment]
hi @etorr thanks! i will check this out!

**Comment by cagnulein** [comment]
Done @etorr send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks
