### ISSUE TITLE
[REQ] Merach MRK-S02-0B8D Resistance Change

### ISSUE THREAD

**Issue by etorr** [cagnulein/qdomyos-zwift#984]
Currently my bike has resistance sent through bluetooth but the default range is 1-8 which makes it hard to make small adjustments to, this also affects the peloton resistance shown in app. Maybe there is a way to show resistance based on calculation from power and cadence in the app to make finer adjustments.

**Comment by cagnulein** [comment]
done @etorr I will send you a new version later today!

**Comment by etorr** [comment]
hi @cagnulein  have you had a chance to compile new version? no rush just checking

**Comment by cagnulein** [comment]
sorry @etorr you are right, i just had terrible days at work. i will today, i promise

**Comment by cagnulein** [comment]
@etorr i don't remember did I send you the version?
