### ISSUE TITLE
[REQ] Disable TTS prefixes for frequent repetitions

### ISSUE THREAD

**Issue by GinTonicX** [cagnulein/qdomyos-zwift#986]
The TTS system is a useful tool when QZ and the phone itself is shrouded from vision via using VR googles when exercising. It is beneficial to use the TTS system to, say, loudly announce ones' heart rate every few seconds. The problem there is that every announcement of this single stat is prefixed with what this stat is, eg. with every announcement of a heart rate every few seconds one hears "heart rate X" and this "heart rate" prefix gets really annoying really fast when repeated over and over again.

My suggestion is to have an option to disable such prefixes so that instead of a "heart rate X" one would hear just the "X" every few seconds. That's it, sanity restored instantly! An even advanced approach would be to select the stats to be announced first and then have the ability to manually edit the string TTS will be announcing every time.

**Comment by cagnulein** [comment]
Done @GinTonicX ! 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the new beta. Thanks

**Comment by GinTonicX** [comment]
Thank you, @cagnulein :) It is much better now and works like a charm with what I had in mind - have a single number announced every 2 seconds. However, it might soothe your inner programmer to make little changes in the code - in homeform.cpp for those s.append if statements replace false "" to ", " or the app now with descriptions off just throws one BIG number when more than one stat is selected (idk why someone would do that, maybe some debugging), like heart rate 80 and calories 500 now outputs 50080 (fifty thousand-ish) :)

**Comment by cagnulein** [comment]
@GinTonicX great! Go ahead with a pull request! I will be glad to review it!

**Comment by cagnulein** [comment]
Any news @GinTonicX ?

**Comment by GinTonicX** [comment]
@cagnulein Nope, no news, really. I am really not a proficient github user to mettle with pull requests and code edits, and since your commit does what I asked for, I am not bothered with this tiny bug. And relating to the reasons I asked it for, I have had no news from VZfit support since they pinned an engineer to check my logs more than two weeks ago, they warned though it might take a while. So as of now I cycle in VR an use qz to loudly announce my heart rate every 2 seconds, it's not that bad of a workaround.

**Comment by cagnulein** [comment]
ok i will do myself so, no problem :)

**Comment by cagnulein** [comment]
done  @GinTonicX 
you will find this in the next beta!
