### ISSUE TITLE
[REQ] Back from the same gpx path (START - END - START - END all the time)

### ISSUE THREAD

**Issue by MatMuski** [cagnulein/qdomyos-zwift#987]
**Is your feature request related to a problem? Please describe.**
Back from the same gpx path (START - END - START - END all the time)

**Describe the solution you'd like**
The gpx loop works if the start and end are in the same place.

It proposes the same functions to do for a straight route with a different start and end. the route simply bounces like a boomerang (start - end - start - end).

In the program settings you can add options whether to loop GPX files or not.

**Comment by cagnulein** [comment]
thanks @MatMuski 
@RickNY this is the other user #973

**Comment by MatMuski** [comment]
Will this be the solution?

**Comment by cagnulein** [comment]
> Will this be the solution?

what do you mean? I would like to add the setting that you described in the first comment

**Comment by MatMuski** [comment]
I mean, are you going to work on this topic?

I already know you do.

I am waiting for a solution :)

**Comment by cagnulein** [comment]
yes sure, i have only to find the time :)
Why don't you start coding yourself too!? :)

**Comment by MatMuski** [comment]
Lack of knowledge. Only tester or user :)

**Comment by cagnulein** [comment]
Yes thanks for the reminder

**Comment by cagnulein** [comment]
so @MatMuski about this you just need a setting to disable the loop? I'm understanding this right?

**Comment by MatMuski** [comment]
I need a loop for the episode. When the finish line is at a different point than the start, the treadmill does not stop but returns to the start.

**Comment by cagnulein** [comment]
hah so you want a setting that force the restart of the training program. This will lead into an error on strava for sure because you will see a jump in the map...are you sure about this?

**Comment by MatMuski** [comment]
The file must be read backwards then there will be continuity on strava as if I was going back the same route to the start.

**Comment by cagnulein** [comment]
hah right, sorry I didn't connect the brain yet this morning :) Let me try to do this today

**Comment by cagnulein** [comment]
done, i'm doing a static test and then I will let you test it during a real workout :P

**Comment by MatMuski** [comment]
Great, will test tonight :)

**Comment by cagnulein** [comment]
when you will receive the new version, i added a new setting under the maps section settings called Loop Start-End-Start so, of course, enable it before importing the gpx :)
I tested with the Passo dello Stelvio one

**Comment by cagnulein** [comment]
@MatMuski i'm uploading right now! In this version i also added the #1058 
You will see a QZ notification like 
![Screenshot_20221130-100232_Samsung capture](https://user-images.githubusercontent.com/48216/204753585-bd4b95cb-a048-4af5-abff-d7ccf0d0fb32.jpg)
It should helps to leave QZ running on background.
Let me know if it helps and also if the patch of the GPX loop works :)
Thanks!

**Comment by MatMuski** [comment]
It doesn't work for me. Crashes apps.

I have versions 2.12.5

Log (Samsung S21): [debug_log.zip](https://github.com/cagnulein/qdomyos-zwift/files/10126924/debug_log.zip)

**Comment by cagnulein** [comment]
there is already the 2.12.6 online :) update it @MatMuski

**Comment by MatMuski** [comment]
Okay I'll check right now :)

**Comment by MatMuski** [comment]
The first loop was ok. I came to the end point and returned the same route.

Only the second loop began with a strange jump by about 100m in the trail on Stravie:

https://user-images.githubusercontent.com/115629983/204912992-94c3462d-ebc4-4dca-aef0-c422e3092bd5.mp4

Debug: [debug+file orginal gpx.zip](https://github.com/cagnulein/qdomyos-zwift/files/10127495/debug%2Bfile.orginal.gpx.zip)

**Comment by cagnulein** [comment]
fixed! @MatMuski are you using android 13 isn't it? If so with the new version 2.12.7 you can try to enable the notification icon in the experimental settings too
Let me know when you will receive it!

**Comment by MatMuski** [comment]
I have 2.12.7

I think I'll check tonight and let you know.

**Comment by MatMuski** [comment]
Route ok :)

I don't have notifications on the bar. I wonder if the program is missing permissions in the phone settings, I will verify it.

Take a look at the debug after 50 minutes of training, the treadmill stopped, I think I was losing connection. I don't know if it's the fault of the phones or the treadmill.

[debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/10138816/debug.zip)

**Comment by cagnulein** [comment]
> Route ok :)

great!

> I don't have notifications on the bar. I wonder if the program is missing permissions in the phone settings, I will verify it.

highly possible, please confirm me this. Thanks

> Take a look at the debug after 50 minutes of training, the treadmill stopped, I think I was losing connection. I don't know if it's the fault of the phones or the treadmill.
> 
> [debug.zip](https://github.com/cagnulein/qdomyos-zwift/files/10138816/debug.zip)

i don't see any connection lost BUT i saw that at around 50 minutes your treadmill stop the tape from the outside. Maybe a unwanted stop? maybe a sweat drop? anyway the communication was fine all the time

**Comment by MatMuski** [comment]
It's just a walk, I'm not sweating. I didn't touch anything on the treadmill panel. It happened about 3 times in a short period of time.

This is my second treadmill from Domyos, the previous one did such numbers after 20 minutes. I will have to check it in their application, maybe for this model the limit is about 50 minutes :D

**Comment by cagnulein** [comment]
hahah but do you feel also the tape is stopping or only the metrics in qz? which exactly model is it?

**Comment by MatMuski** [comment]
Domyos Intense Run

Yesterday the tape stopped at QZ, I had to press start on the treadmill to get back to training.

I didn't do such long workouts on this new treadmill. usually around 45 minutes, so I thought the new treadmill was no longer a problem.

On the previous treadmill (same model) it seems to me that in Zwift the avatar was standing and the treadmill was working normally. Using only QZ or Econnected Domyos, I don't remember how the old treadmill behaved.

Now that I have a map in QZ, I don't use Zwift.

I will have to go back to the Econnected Domyos app for a few trainings and again a complaint :D

**Comment by cagnulein** [comment]
Strange, I have the same TM and I had dozens of half marathons on it without this issue.
Anyway i saw some holes as you described in yoru log, and the strangest thing is that some hole are just 300 ms, and then the treadmill started again by itself. So it's very very strange.
Let me know how it goes

**Comment by cagnulein** [comment]
Anyway I'm closing this ticket since the feature is working now :)
