### ISSUE TITLE
[BUG] No heart rate data displayed in Wahoo RGT with QZ's Direct Connect

### ISSUE THREAD

**Issue by shoulih** [cagnulein/qdomyos-zwift#989]
**Describe the bug**
No heart rate data displayed in Wahoo RGT with QZ's Direct Connect option.

**To Reproduce**
1. Enabled heart rate and Direct Connect for RGT in QZ's setting.
2. Make sure HR data displayed correctly in QZ
3. Start the RGT on the same Lan
4. See the power and cadence data displayed in RGT, but not the HR data. 

**Expected behavior**
Able to see the HR data along with power and cadence data in the RGT.
Somehow, feel like in RGT there should be a switch bar under "Heart Rate" for WAHOO HRM device and there are no switch bars under "Power", "Cadence" and "Control" - see the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/66762397/196545115-e1ddd50e-7c9a-43ea-898b-c2aefe35b700.png)

**Desktop (please complete the following information):**
 - OS: Raspberry pi 
 - Version Bullseye 

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 
 - Version 13

**Append a debug log**

Available upon request 
  
**Additional context**

**Comment by shoulih** [comment]
@cagnulein I will try to confirm that with RGT support.  BTW, do we know if hr data from QZ is supported by the Wahoo Direct Connect for Zwift app?

**Comment by cagnulein** [comment]
@shoulih I'm quite sure that zwift works with it. But I can confirm you this, this weekend

**Comment by shoulih** [comment]
> @shoulih I'm quite sure that zwift works with it. But I can confirm you this, this weekend

Thank you Robert and I will let you know once I hear back from Whaoo support.

**Comment by shoulih** [comment]
> @shoulih I'm quite sure that zwift works with it. But I can confirm you this, this weekend

According to this youtube link for zwift:  https://www.youtube.com/watch?v=DBoCCrYbDi8
Wahoo Direct Connect doesn't seem to support HRM, which was fed from the Zwift Companion app with a Bluetooth connected HRM from that Youtube viedo.  But that could be just zwift's poor implementation of Direct Connect communication.

**Comment by cagnulein** [comment]
separate log about no auto resistance on RGT
[debug-Tue_Oct_25_13_55_42_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9866601/debug-Tue_Oct_25_13_55_42_2022.log)

**Comment by cagnulein** [comment]
@shoulih I checked and it seems they are sending completely wrong packets over DIRCON. Do you still see cadence and power? If so it seems they broken something by mistake. Maybe we should reach them by email?

**Comment by shoulih** [comment]
Another debug log with QZ virtual BT and  both cadence and power were shown
up co

**Comment by cagnulein** [comment]
@shoulih i guess your message was truncated. i don't see any log

**Comment by shoulih** [comment]
Attaching the log again, which is about 1.41 MB

**Comment by cagnulein** [comment]
@shoulih you have to attach it from the github website. you cannot add them by email

**Comment by shoulih** [comment]
You are correct and the issue seems to be between Wahoo RGT Remote app and
Wahoo RGTApp on Windows.  QZ's auto resistance works with the Wahoo RGT app
on Android and please find the debug log for the working case att (1.9 MB)

Thanks,

Shawn

**Comment by cagnulein** [comment]
@shoulih the debug log must be attached from the github page :) i can't see nothing otherwise 
Hah so it's a RGT bug, what a shame! :D
