### ISSUE TITLE
Unable to sync iFit to QZ App

### ISSUE THREAD

**Issue by smaxwell360** [cagnulein/qdomyos-zwift#990]
I am attempting to sync the iFit app to my QZ app. I'm using an Echelon EX3 bike, an iPhone 13 Pro (for the QZ app), and an Amazon Fire tablet (for iFit) but the QZ app is not connecting to iFit.

I have the QZ Debug log file saved, but Github will not let me attach the file (".fit" file type). How can I attach the Debug file to this ticket?

In the QZ app, I have enabled te iFIT setting in the Experimental settings. I also renamed the iPhone “I_TL”.

I followed this process:

1. Enabled the Virtual iFIT setting on QZ under experimental. Closed and restarted the QZ app on the phone.
3. Renamed the iphone I_TL and rebooted the iPhone.
5. Started iFIT on the Amazon Fire tablet.
7. When it reaches the Bluetooth connection screen on iFIT, it says no connection found.
9. I manually connected the Bluetooth from iPhone to Amazon Fire Tablet.
11. Still no Bluetooth connection showing in iFIT.
13. I tried starting a cycling class in iFIT but the Echelon ex3 bike did not auto adjust the resistance.

Did I miss anything along the way?

**Comment by cagnulein** [comment]
fit file is not the debug log, the debug log starts with debug prefix. zip it when you have it

**Comment by smaxwell360** [comment]
Hmm, the Debug Log setting is enabled under Experimental Features but I don't see any debug prefix files in my IOS Files folder. It's all "0QZ-Backup..."

**Comment by smaxwell360** [comment]
[debug-Fri_Oct_14_17_04_38_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9821702/debug-Fri_Oct_14_17_04_38_2022.log)

Here's the correct debug file

**Comment by cagnulein** [comment]
mmm @smaxwell360 could you install nrfconnect app on the tablet and check, while qz is open on the iphone, what do you see about the iphone?
let me know

**Comment by cagnulein** [comment]
@smaxwell360 any news?
