### ISSUE TITLE
Output for 10-16 less than 4-9 at same cadence.

### ISSUE THREAD

**Issue by faet** [cagnulein/qdomyos-zwift#991]
[debug-Wed_Oct_19_13_10_08_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9822736/debug-Wed_Oct_19_13_10_08_2022.log)

Setting the resistance from 4-9 results in a progressive increase in output. But once I set the resistance to 10 the output drops by 30points compared to resistance of 9. It isn't until I set the resistance to 16 that the output equals that of 9.

**Comment by cagnulein** [comment]
@faet check if you have the same behaviour without the mgarcea echelon profile. Let me know

**Comment by faet** [comment]
@cagnulein I do, even with the default echelon profile it drops. Not *as* much though. But, I tried both.

**Comment by cagnulein** [comment]
ok i will check the other settings later. my baby is claiming me so my time is over for today (8pm here :) )

**Comment by cagnulein** [comment]
![image](https://user-images.githubusercontent.com/48216/196764471-622ddd49-d1ca-44ee-9cdb-7936325e6eae.png)
![image](https://user-images.githubusercontent.com/48216/196764489-af5933fc-31b7-40c3-81a6-ab16630085fe.png)

**Comment by cagnulein** [comment]
@faet the mgarcea profile was collected with a power pedal, so it could something in the physys of the bike itself

**Comment by faet** [comment]
Thanks and have a good evening. I'll spend some time seeing if there are firmware updates for the bike as well as take it apart  tonight.

**Comment by faet** [comment]
I took some stuff apart and blew canned air in to see if that helped. With the new power setting it is at least linear when increasing the resistance now. but it is still short of echelon's power estimate. 10 resistance @ 100 cadence is ~83 vs ~100.

(This is the first 5min of a log as I did an hour long ride, if you want the full log/new one lemme know. )

[debug-Fri_Oct_21_16_10_18_2022-split.log](https://github.com/cagnulein/qdomyos-zwift/files/9842621/debug-Fri_Oct_21_16_10_18_2022-split.log)



![qz](https://user-images.githubusercontent.com/202275/197291517-a9a3af64-bfa2-4002-bb3b-07ac45d85b85.png)
![echelon](https://user-images.githubusercontent.com/202275/197291519-0f892731-c981-4b74-a4a4-0bbb219458f8.png)

**Comment by cagnulein** [comment]
I guess I understood what you mean.
Over cadence 99 a different formula is used. Check this https://github.com/cagnulein/qdomyos-zwift/blob/1cfb556e6ce0a2225ac3983fd89bc3e8e14a195d/src/echelonconnectsport.cpp#L613

That comes from the behaviour of the echelon app 2021. I guess they changed something. If i'm right, if you stay on cadence 99 you should have similiar output. Otherwise they change the power formula again.

@mgarcea are you still using this? what do you think over cadence 99?

**Comment by faet** [comment]
16 resistance @ 75 cadence is 102ec vs 87qz, so it looks like they changed the power formula again. Anything else I can do to help update the power formula or are you able to grab it from them somewhere?

![qz](https://user-images.githubusercontent.com/202275/197419776-db853a7b-7d3d-49a0-af94-2f7b48651576.png)
![ec](https://user-images.githubusercontent.com/202275/197419777-ae8d351f-8bd7-4ea5-ac1e-80a266b59830.png)

**Comment by cagnulein** [comment]
yes sure @faet 

you just need to fill this table with the new values that you're reading from the echelon app

```
    double wattTable[wattTableFirstDimension][wattTableSecondDimension] = {
        {Epsilon, 1.0, 2.2, 4.8, 9.5, 13.6, 16.7, 22.6, 26.3, 29.2, 47.0},
        {Epsilon, 1.0, 2.2, 4.8, 9.5, 13.6, 16.7, 22.6, 26.3, 29.2, 47.0},
        {Epsilon, 1.3, 3.0, 5.4, 10.4, 14.5, 18.5, 24.6, 27.6, 33.5, 49.5},
        {Epsilon, 1.5, 3.7, 6.7, 11.7, 15.9, 19.6, 26.1, 30.8, 35.2, 51.2},
        {Epsilon, 1.6, 4.7, 7.5, 13.7, 17.6, 22.6, 29.0, 36.9, 42.6, 57.2},
        {Epsilon, 1.8, 5.2, 8.0, 14.8, 19.1, 23.5, 32.5, 37.5, 50.8, 61.8},
        {Epsilon, 1.9, 5.7, 8.7, 15.6, 20.2, 25.5, 33.5, 39.6, 52.1, 65.3},
        {Epsilon, 2.0, 6.2, 9.5, 16.8, 21.8, 28.1, 37.0, 42.8, 57.8, 68.4},
        {Epsilon, 2.1, 6.8, 10.8, 18.2, 23.6, 29.5, 40.0, 47.6, 60.5, 72.1},
        {Epsilon, 2.2, 7.3, 11.5, 19.3, 26.3, 33.5, 45.3, 51.8, 66.7, 76.8},
        {Epsilon, 2.4, 7.9, 12.7, 20.8, 29.8, 37.6, 52.2, 56.2, 73.5, 83.6},
        {Epsilon, 2.6, 8.5, 13.5, 23.5, 33.6, 41.9, 55.1, 59.0, 78.6, 89.7},
        {Epsilon, 2.7, 9.1, 14.2, 25.6, 35.4, 45.3, 57.3, 62.8, 81.3, 95.0},
        {Epsilon, 2.9, 9.6, 16.8, 29.1, 37.5, 49.6, 62.5, 69.0, 84.7, 99.3},
        {Epsilon, 3.0, 10.0, 22.3, 31.2, 40.3, 51.8, 65.0, 70.0, 92.6, 108.2},
        {Epsilon, 3.2, 10.4, 24.0, 36.6, 42.5, 56.3, 74.0, 85.0, 98.2, 123.5},
        {Epsilon, 3.5, 10.9, 25.1, 38.5, 47.6, 65.4, 83.0, 93.0, 114.8, 136.8},
        {Epsilon, 3.7, 11.5, 26.0, 41.0, 53.2, 71.6, 90.0, 100.0, 121.7, 149.2},
        {Epsilon, 4.0, 12.1, 27.5, 43.6, 56.0, 82.3, 101.0, 113.6, 143.0, 162.8},
        {Epsilon, 4.2, 12.7, 29.7, 46.7, 64.2, 87.9, 109.2, 128.9, 154.0, 172.3},
        {Epsilon, 4.5, 13.7, 32.0, 50.0, 71.8, 95.6, 113.8, 135.6, 165.0, 185.0},
        {Epsilon, 4.7, 14.9, 34.5, 54.2, 77.0, 100.7, 127.0, 147.6, 180.0, 200.0},
        {Epsilon, 5.0, 15.8, 36.5, 58.3, 83.4, 110.1, 136.0, 168.1, 196.0, 213.5},
        {Epsilon, 5.6, 17.0, 39.5, 64.3, 88.8, 123.4, 154.0, 182.0, 210.0, 235.0},
        {Epsilon, 6.1, 18.2, 44.0, 70.7, 99.9, 133.3, 166.0, 198.0, 230.0, 253.5},
        {Epsilon, 6.8, 19.4, 49.0, 79.0, 108.8, 147.2, 185.0, 217.0, 255.2, 278.0},
        {Epsilon, 7.6, 22.0, 54.8, 88.0, 127.0, 167.0, 212.0, 244.0, 287.0, 305.0},
        {Epsilon, 8.7, 26.0, 62.0, 100.0, 145.0, 190.0, 242.0, 281.0, 315.1, 350.0},
        {Epsilon, 9.2, 30.0, 71.0, 114.4, 161.6, 215.1, 275.1, 317.0, 358.5, 390.0},
        {Epsilon, 9.8, 36.0, 82.5, 134.5, 195.3, 252.5, 313.7, 360.0, 420.3, 460.0},
        {Epsilon, 10.5, 43.0, 95.0, 157.1, 228.4, 300.1, 374.1, 403.8, 487.8, 540.0},
        {Epsilon, 12.5, 48.0, 99.3, 162.2, 232.9, 310.4, 400.3, 435.5, 530.5, 589.0},
        {Epsilon, 13.0, 53.0, 102.0, 170.3, 242.0, 320.0, 427.9, 475.2, 570.0, 625.0}};
```

every row is a resistance level (starting from 1 to 32). Every column is a step of 10 cadence value that will be interpolated. The value themself are ofcourse the wattage
The one that you're seeing now it's the echelon tablet from 2021

Let me know if you need any information

**Comment by cagnulein** [comment]
#483

**Comment by faet** [comment]
Cool, I'll work on this over the week. For reference I have an Echelon Prime/EX-15/Sport Connect (Same bike different naming) running firmware 41.04.04

Only questions I have at the moment is how do you get the decimals for wattage? My app seems to round to whole numbers. 

Also, is there an easier way to pull the numbers? Otherwise I was going to screen record and ride at various intervals and pull the numbers that way.

**Comment by cagnulein** [comment]
> Cool, I'll work on this over the week. For reference I have an Echelon Prime/EX-15/Sport Connect (Same bike different naming) running firmware 41.04.04

Great!

> Only questions I have at the moment is how do you get the decimals for wattage? My app seems to round to whole numbers.

Just use the integer value, it doesn't mean a lot of difference.

> Also, is there an easier way to pull the numbers? Otherwise I was going to screen record and ride at various intervals and pull the numbers that way.

Yes record the video it's the best method I guess

**Comment by mgarcea** [comment]
Hi Roberto,

Just looking at this.  Hope all is well with you!  It might be that the Prime Bike is different I’m not sure, but I can tell you that on the EX-3 or EX-5 etc the resistance of 16 does not produce 100 Watts at 75 cadence measured using power pedals.  In fact we measured it even lower than 87 on our bike.  Probably closer to 70 watts.  But the bikes are different and have different fly wheels so maybe that is where the discrepancy is.  I think I remember one of the Facebook members upgrading his bike from the front flywheel version to the rear flywheel version some time ago and he indicated that the resistances were not equivalent.  But maybe Echelon does use two different formulas now, and perhaps a separate lookup table is needed for different versions of the bike.  In the end we always use power pedals now to give a more accurate assessment.  On another note I was wondering if QZ will be able to simulate the gradients using ANT+ at some point or is this impossible?  There are some programs that for whatever reason use just the ANT+ protocol (Open Road, BigRing VR etc), and we noticed that the power can be passed from QZ to the program, however it won’t auto change the resistance (no controllable function).

Michele

**Comment by cagnulein** [comment]
> Hi Roberto, Just looking at this. Hope all is well with you! 

hi! Yes everything is good! what about you?

> It might be that the Prime Bike is different I’m not sure, but I can tell you that on the EX-3 or EX-5 etc the resistance of 16 does not produce 100 Watts at 75 cadence measured using power pedals. In fact we measured it even lower than 87 on our bike. Probably closer to 70 watts.

Since it's just software, I guess Echelon just want to push up their users feelings :D

> But the bikes are different and have different fly wheels so maybe that is where the discrepancy is.

Yeah but it's not the case :)

> I think I remember one of the Facebook members upgrading his bike from the front flywheel version to the rear flywheel version some time ago and he indicated that the resistances were not equivalent. But maybe Echelon does use two different formulas now, and perhaps a separate lookup table is needed for different versions of the bike. In the end we always use power pedals now to give a more accurate assessment. 

oK

> On another note I was wondering if QZ will be able to simulate the gradients using ANT+ at some point or is this impossible?

Yes it could be possible. Actually we are checking on ANT+ with another user #953  Send a message here.

**Comment by faet** [comment]
If echelon is overstating I'd probably prefer to be closer to the actual output than an inflated one. I can continue to create the table for you if the plan is to have a "Sport Connect" profile for those looking to be closer to what echelon's current output is.

**Comment by cagnulein** [comment]
Thank you.


Inviato da Apple Watch

**Comment by mgarcea** [comment]
Anyone else noticed the difference between the two? I wonder if the difference occurs in the EX-3X.  I can check on our bike this evening and report back.

**Comment by cagnulein** [comment]
> Anyone else noticed the difference between the two? I wonder if the difference occurs in the EX-3X. I can check on our bike this evening and report back. 

nope because most of the users never tried the echelon app

**Comment by mgarcea** [comment]
Here is a quick video showing our bike's Echelon Output at a few different resistance levels.  We have an EX-4S which is a Costco Version of the EX-3/EX-5.  I also have the Garmin Vector Power Pedals displaying the power and cadence on the split screen. It is very hard to get obtain repeatable accurate measurements from the power pedals. In the past when doing this we tried to hold power and cadence for at least 20-30 secs and then tried to get a reasonable 5 sec average.  I used Golden Cheetah when trying to compare and analyze the power, but found it very difficult.

Anyways, it appears they have changed the formula as my numbers don't match the QZ lookup table anymore.  However, my numbers don't match the numbers that were displaying on your EX-15 either.  I am a little surprised that Echelon is displaying over 100 watts at resistance 16 and cadence 75 on the EX-15. It was my understanding that the EX-15 top resistance is less than the other Echelon bikes with the bigger flywheels.  Anyways you can find the video here and a pic of the firmware that we are using.  Hope that helps.

https://drive.google.com/drive/folders/1L4BDng5g-i93y9N-tUTipeuSlRgWP-SD?usp=sharing
________________________________

**Comment by cagnulein** [comment]
> Anyways, it appears they have changed the formula as my numbers don't match the QZ lookup table anymore. 

Do you mean that since they update it, it affects also the cadence sent from the bike? 
I mean, since we are using our lookup table based on cadence and resistance, their firmware or lookup table shouldn't affect us

**Comment by mgarcea** [comment]
Yeah kind of interesting although Echelon’s values do seem a little more conservative now. But interesting that the other user has a completely different power value at the same resistance level and lower cadence. I guess it doesn’t really matter unless you are racing on Zwift and even then there is all sorts of other cheating going on.

**Comment by cagnulein** [comment]
@faet any news?
