### ISSUE TITLE
No communication between treadmill and android phone.

### ISSUE THREAD

**Issue by TomD87** [cagnulein/qdomyos-zwift#993]
QZ Installed on my Android Phone
QZ Companion for Nordictrack installed on my T8.5 s
Installed as per the instructions, all went well, but I'm not getting any data on my phone. IP address is correct.
I get Hello World if I go back to privileged mode and open the app on the treadmill so it looks to be installed correctly.

See log attached
[debug-Thu_Oct_20_18_59_07_2022[2200].log](https://github.com/cagnulein/qdomyos-zwift/files/9832786/debug-Thu_Oct_20_18_59_07_2022.2200.log)

**Comment by cagnulein** [comment]
I don't remember if the production version can run this treadmill 

send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you the latest beta. Thanks

**Comment by TomD87** [comment]
Thanks, sent that now.

**Comment by TomD87** [comment]
Still the same, appreciate you helping with this.
Here are more logs.


[debug-Thu_Oct_20_19_25_25_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9832939/debug-Thu_Oct_20_19_25_25_2022.log)
[debug-Thu_Oct_20_19_23_51_2022.log](https://github.com/cagnulein/qdomyos-zwift/files/9832940/debug-Thu_Oct_20_19_23_51_2022.log)

**Comment by cagnulein** [comment]
@TomD87 Can you get the log from the treadmill tablet directly via adb? I suspect that the companion has no data to send for some reason. Are all the permissions ok for the companion app?

**Comment by TomD87** [comment]
The companion app had no storage permission. Enabled and reading data perfect.
No control over speed of incline from the QZ app but I think this is expected on this model.
Thanks for your support.

**Comment by cagnulein** [comment]
Yes there is a ticket open for the automatic inclination. It's on my list!
