### ISSUE TITLE
[SUGGESTION] Further encapsulation of virtual device

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#994]
Currently the virtual device is exposed through the public interface of each bluetoothdevice subclass as void *, but these are not actually used outside the class itself, apart from some code in bluetooth.cpp which deletes the virtual device from outside. 

Refactor so that the virtual device is private (or protected if need be), and deleted by the contianing object's destructor rather than relying on an additional call from outside.

There are numerous cases where a bluetoothdevice is used to represent a different kind of device, and in these cases the virtual device object is not exposed via the VirtualDevice function. Provide a facility to set a virtual device as hidden or exposed.

**Comment by drmason789** [comment]
This is already done as part of #887. I'll separate the PR.

**Comment by drmason789** [comment]
Here is the place where the virtual devices are deleted from outside the containing object:

https://github.com/cagnulein/qdomyos-zwift/blob/69d95ee27d22a896b872957fd40c4c82f5243579/src/bluetooth.cpp#L2035-L2044

**Comment by cagnulein** [comment]
bot shut up
