### ISSUE TITLE
[REQ] Handle multiple detected devices

### ISSUE THREAD

**Issue by drmason789** [cagnulein/qdomyos-zwift#996]
> * Non-bluetooth devices, e.g. wifi devices and my serial device from [Add support for the Trixter X-Dream V1 bike #855](https://github.com/cagnulein/qdomyos-zwift/issues/855) won't be detected unless there is a bluetooth device - ANY bluetooth device in range of the computer. This problem should be fixed by [[REQ] Alternative "discovery agent" for non-bluetooth devices #889](https://github.com/cagnulein/qdomyos-zwift/issues/889).

Wow, great yes i'm aware of this! Thanks for the patch!

> * If multiple devices are found, bluetooth or not, a bluetoothdevice object will be created for them and stored, all but 1 unused, in the bluetooth object.
> 
> As I think about how to test device detection in #911, and about these problems, I think a course of action would be to reduce the current device detection to produce a simple list of identifiers for each device type, present them to the user in a drop down, and create and connect a single bluetoothdevice subclass object for the selected device, when it's selected. If there's only 1 device, it could be auto-selected.

Wow this should be amazing! I totally agree about the solution that you purposed!

_Originally posted by @cagnulein in https://github.com/cagnulein/qdomyos-zwift/issues/887#issuecomment-1287833205_

**Comment by drmason789** [comment]
At this point, (4c88cb8) I believe the device detection behaviour to be unchanged, but I've separated detection from creation of the bluetoothdevice subclass objects. 

1. Collect the bool and string values from the settings into a single object and use that in the enormous if statement.
2. Copy and paste the enormous if statement into a separate method. This should be easily comparable side by sied with a diff tool to see what has, or hasn't changed.
3. Establish an enumeration to identify a device type, and split the new discovery method into 2: one that does the comparisons as before but sets an enum value instead of creating the device object; the other that creates and connects the device object based on the enum passed in. Both of these should be easily comparable, side by side, with a diff tool to see what has, or hasn't changed.
4. Return the created object so that common functionality can be performed on it.
5. Set up the template manager in common code.

This puts it in a state I can use for the automated testing of #911, I think: a test that checks that the bluetooth object's detectDevice function produces the expected enum value for the given bluetooth device name, and that the createObject function generates an object of the expected type when supplied with a specific enum value.

Overall target of this issue is not completed, however.

**Comment by cagnulein** [comment]
> This puts it in a state I can use for the automated testing of #911, I think: a test that checks that the bluetooth object's detectDevice function produces the expected enum value for the given bluetooth device name, and that the createObject function generates an object of the expected type when supplied with a specific enum value. All while avoiding activating bluetooth and having to get the device names via bluetooth.

Yes, sounds perfectly! In this way we can test everything without a real hardware!

**Comment by drmason789** [comment]
> At this point, (https://github.com/cagnulein/qdomyos-zwift/commit/4c88cb8c6f2632576237c4a99a183f2ce35f6a8f) I believe the device detection behaviour to be unchanged, but I've separated detection from creation of the bluetoothdevice subclass objects.

Unfortunately this is wrong. Since the device detection is affected by the devices for which objects have already been created, this will not because the same. More thinking required.

**Comment by drmason789** [comment]
Not completed, just in the queue behind #911.

**Comment by cagnulein** [comment]
ok
